### ISSUE TITLE
Scrolling in side menu scrolls content instead

### ISSUE THREAD

**Issue by Manduro** [ionic-team/ionic#10017]
**Ionic version:**
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Occurs when running iOS in MD mode. GIF demo:
![untitled](https://cloud.githubusercontent.com/assets/2545042/21934592/43bd02b8-d9aa-11e6-9ae4-79d12f8e19b4.gif)

**Expected behavior:**
The content should not scroll.

**Steps to reproduce:**
1. `ionic start mySideMenu sidemenu --v2`
2. Set iOS to MD mode in `app.module.ts`
3. Make the content of `page1` long enough to scroll
4. Run in iOS simulator
5. Open side menu
6. Try scrolling

**Related code:**

```
  imports: [
    IonicModule.forRoot(MyApp, {
      platforms: {
        ios: {
          mode: 'md'
        }
      }
    })
  ]
```

**Ionic info:**

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by mhartington** [comment]
Confirmed, thanks for the detailed issue.

**Comment by longzheng** [comment]
+1 also affected by this issue

**Comment by Manduro** [comment]
The same goes for an MD mode action sheet on iOS, and probably other component using the overlay. The overlay does not stop the content from scrolling.
