### ISSUE TITLE
Binding data to pages can randomly stop working

### ISSUE THREAD

**Issue by le0pard** [ionic-team/ionic#10016]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Updating data in templates stop working in random way and update only if you call `this.ref.detectChanges();` in app.component (on video added it on click of menu), there `this.ref` is `ChangeDetectorRef`.

Here video how it is looks like:

http://take.ms/Phud5

**Expected behavior:**
Data binding to template should works.

**Steps to reproduce:**
It happen randomly after using `this.nav.setRoot(somePage)` from one page to another. I do not have clear step to reproduce. If I click on link in left menu, which make `this.nav.setRoot(somePage)` from app.component to the same page, binding start works again on page. As I can see, I get this bug often, if my PC or tested device is slowing down (reproduced on browser and devices).

**Related code:**

Example of code, which stop working in random way on pages.

```
     <button ion-button default
        (click)="minusTapped($event, item)"
        class="minus-button"
        color="light"
      >-</button>
      <input clearInput
        value="0"
        type="text"
        size="2"
        [(ngModel)]="item.count"
        [disabled]="!isPersonChangeEnabled"
        class="ticketing-count"
      />
      <button ion-button default
        (click)="plusTapped($event, item)"
        class="plus-button"
      >+</button>
```

methods `plusTapped` and `minusTapped` get events (checked by `console.log`), object `item` is changing, but template not update.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5-201701121905
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

package.json:

```
"dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.7",
    "crypto-js": "3.1.9-1",
    "gulp": "^3.9.1",
    "ionic-angular": "nightly",
    "ionic-native": "2.2.15",
    "ionicons": "3.0.0",
    "lodash": "^4.17.3",
    "moment": "^2.17.1",
    "ng2-translate": "5.0.0",
    "rollup-plugin-replace": "^1.1.1",
    "rxjs": "5.0.0-beta.12",
    "sw-toolbox": "^3.4.0",
    "zone.js": "0.6.26"
  },
"devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "typescript": "2.0.9"
  },
```

Mostly I need advice how to debug this problem, because I do not understand why this happen.

**Comment by gerits** [comment]
I've encountered the same issue in rc4. Same behavior is with setPages (internally it is the same as setRoot). Calling this method twice also solves the issue. 

We call setPages from platform.ready(). We want the user to start not on the root page in some cases. This cause this issue consistently, might help to reproduce it.

**Comment by le0pard** [comment]
@gerits thanks for feedback. But in my cases looks like it is more random. I was expected is Angular 2.2.1 problem, but update to 2.4.3 doesn't solve this problems.

**Comment by nicopeeters** [comment]
Hi all, this still seems to be an issue. I've also managed to work around it by calling the setPages method twice like @gerits advised. Do we need to keep working around it like this or will this be fixed in one of the upcoming releases?

**Comment by falkoschumann** [comment]
I use Ionic 2.3.0 and Angular 2.4.8.

Only `AppComponent` breaks data binding, other components works without problems.

I add `this.ref.detectChanges();` (`ref` is `ChangeDetectorRef`) after every set property, works as a workaround, but is no proper solution.
