### ISSUE TITLE
Refresher component dependent on being first child of component

### ISSUE THREAD

**Issue by AlDrag** [ionic-team/ionic#10034]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The Ionic V2 Refresher component seems to be dependent on the component being defined as the first child of the ion-content component? This limits it's use.

**Expected behavior:**
Just like with Ionic V1, you should be able to use ion-refresher anywhere, as this gives a lot more flexibility with its use. However maybe I am wrong and there is a good reason you guys have designed it this way?

**Comment by YasirPanjsheri** [comment]
I just wanted to add also... it not cancellable, lets say when the user pulls down for refresh..once its pulled a certain distance where the refresh is triggered, the user is not able to do anything until the refresh task is completed....the user should be able to cancel back the action...by pushing up the content again for example and therefore canceling the action
