### ISSUE TITLE
Menu content won't scroll unless main content is tall enough

### ISSUE THREAD

**Issue by patrickmcd** [ionic-team/ionic#10039]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
In Safari, the scrolling of the menu is tied to the content. If the main content isn't taller than the view, then the menu won't scroll even though its content is taller than the view. When you add content to the main view, scrolling in the menu will work.

**Expected behavior:**
Scrolling in the menu should always work if the content is long enough.

**Steps to reproduce:**
Try scrolling in the menu, then toggle the segment and try again.
http://plnkr.co/edit/YpOJBp?p=preview

**Related code:**
```
n/a
```

**Other information:**
Safari Version 10.0.2 (Haven't tested on an iPhone)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by wbhob** [comment]
Works fine for me in Chrome... do you mean test it on a device?

**Comment by patrickmcd** [comment]
It's specifically a Safari bug.

**Comment by wbhob** [comment]
Does it happen when you test on device?

**Comment by Manduro** [comment]
Duplicate of #10017 ;)
