### ISSUE TITLE
text-wrap is not working on a button

### ISSUE THREAD

**Issue by theunreal** [ionic-team/ionic#10031]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using text-wrap on a button does not apply any effect

**Expected behavior:**
Text shouldn't cut when there are long button text

**Related code:**

```
<button ion-button text-wrap full large>This is a long text button to view all text</button>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by sabbyt** [comment]
Any news on this?

**Comment by EWBears** [comment]
I also wanted to check in on this issue and see if it would be resolved any time soon.
