### ISSUE TITLE
Styling conflict with forms, lists, and list headers

### ISSUE THREAD

**Issue by patrickmcd** [ionic-team/ionic#10033]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
There are some styling / border / highlight issues regarding form tags and lists. They are better explained by looking at the Plunker.

**Expected behavior:**
n/a

**Steps to reproduce:**
http://plnkr.co/edit/wioLDW?p=preview

**Related code:**
n/a

**Other information:**
n/a

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
n/a
```

**Comment by leonardobazico** [comment]
Any solution for that?
