### ISSUE TITLE
Slides are throwing a slide change event for a slide that does not exist

### ISSUE THREAD

**Issue by cfjedimaster** [ionic-team/ionic#10057]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Imagine two slides with a ionSlideChange event. In my testing with 2 slides, when I tried to slide to 3, the app correctly stopped me, but the event handler fired. Also, this.slider.getActiveIndex() returned 2 which is invalid since the app only had 2 slides.

**Expected behavior:**
I would expect ionSlideChange to not fire. The slide didn't change.

**Related code:**

https://github.com/cfjedimaster/Cordova-Examples/tree/master/ionicweatherv3/src

**Comment by chrisbenseler** [comment]
Same for me

**Comment by darron1217** [comment]
Same for me...

Also 'ionSlideDidChange' event fires whenever I try to swipe-right the slide at the end of slides (eventhough slide did not changed!)
