### ISSUE TITLE
Virtual scroll in a popover shows an empty list

### ISSUE THREAD

**Issue by olmo** [ionic-team/ionic#10052]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using a virtual scroll in a popover shows an empty list. In the DOM there isn't any ion-item inside the ion-list. The same code works outside the popover. This happens in RC5, I don't know if previous versions have the same bug.

**Expected behavior:**
ion-items should be generated if a virtual scroll is used in a popover.

**Comment by ghenry22** [comment]
virtualscroll has issues loading lists when nested inside a conditional, crops up with segments or just a list that is being ngIf'd.  Probably the same or similar issue with popovers.
