### ISSUE TITLE
Item slider options on IOS not viewable

### ISSUE THREAD

**Issue by karlpatrickespiritu** [ionic-team/ionic#10051]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
![issue](https://cloud.githubusercontent.com/assets/10472504/21978961/e9b408e6-dc17-11e6-9f1d-ef9bd9244119.png)

**Expected behavior:**
- Slider options must be visible

**Steps to reproduce:**
- Just slide another item after slider another one
- Or just slide randomly at any time

````
Your system information:

Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
````

**Comment by gigocabrera** [comment]
+1 
And the official ItemSliding demo page also behaves somewhat similar. 
http://ionicframework.com/docs/v2/api/components/item/ItemSliding/
Take the Twitter item under Logins, for example, and slide it left past the phone background. The 'mute' button disappears completely 

![issue-10051](https://cloud.githubusercontent.com/assets/6364855/21986835/06eb285c-dbcf-11e6-9bc1-1ac36834c1d5.png)

**Comment by wbhob** [comment]
Looks like you're on rc2, have you updated to 5?

**Comment by gigocabrera** [comment]
@wbhob I'm having a similar issue like @karlpatrickespiritu described in this issue and I'm using RC5. Also, your official demo page is behaving somewhat weird with  the ItemSliding and I didn't have this issue with RC4 that I can recall.

**Comment by gigocabrera** [comment]
@wbhob I rolled back to RC4 and the issue goes away. My ItemSliding controls are behaving as expected

**Comment by wbhob** [comment]
Yes, because that new slider is RC5. They are fixing it in RC6.

**Comment by karlpatrickespiritu** [comment]
Yep. Issue still occurs on RC5. Hope this will be fixed on RC6. Thanks ionic team!
