### ISSUE TITLE
Strange behaviour in slider with centeredSlides and 2 slides

### ISSUE THREAD

**Issue by chrisbenseler** [ionic-team/ionic#10068]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Slider is 'sliding' to an slide that does not exists (after the last one)

**Expected behavior:**
Should not slide

**Steps to reproduce:**
Build an simple ion-slider (3 items), and set the properties:
centeredSlides = true
slidesPerView = 2

add some css to highlight the active slide (just to make things easy to view in the browser). When you are in the last slide, if user slide again, the components seems to slide to a slide that does not exists and the last slide loose the active property.

[Plunker here](http://plnkr.co/edit/9KfwgykFBmlPyXtL8Q3e)
Better viewd in the [embed](http://embed.plnkr.co/9KfwgykFBmlPyXtL8Q3e/).
-->

**Related code:**

```
//html
<ion-slides #slider>
    <ion-slide>
      <h1>Slide 1</h1>
    </ion-slide>
    <ion-slide>
      <h1>Slide 2</h1>
    </ion-slide>
    <ion-slide>
      <h1>Slide 3</h1>
    </ion-slide>
  </ion-slides>
// component
@ViewChild('slider') slider: Slides;
...
ionViewDidLoad() {
  	this.slider.centeredSlides = true
  	this.slider.slidesPerView = 2
  }
//css
.swiper-slide-active  {
	background-color: #FF0000;
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.0
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.4.0
Xcode version: Not installed

```

**Comment by CooleyGit** [comment]
Im seeing the same issue, we are using the slider to switch between data so this was causing issues when swiping to the phantom slide with no data associated.

I was able to temp work around it by checking against event.getActiveIndex(); and event.length(); length is correct on the event so you can stop it before active becomes equal to length.

**Comment by chrisbenseler** [comment]
@CooleyGit can u explain a little bit more how u did that? In which event are you doing this check (ionSlideDidChange?)?
