### ISSUE TITLE
Ionic 2 pull to refresh + ion-list and open navigation content disappears

### ISSUE THREAD

**Issue by bolivir** [ionic-team/ionic#10086]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently i am using the Pull the refresh and the ion list component on a page. My content disappears when i use the pull to refresh and after that i open the navigation. Currently i am not able to setup a plunker but i will try that later.

**Expected behavior:**
When i use the pull to refresh and scroll down the list and then open the menu the content will not be gone.

**Steps to reproduce:**
- Create a ion list that contains enough items so the list is scrollable.
- Use the pull the refresher
- Afther the refresh is done, scroll the list down.
- Now open the navigation panel, the content will dissapear.

**Other information:**
Currently i cannot setup a plunker with RC5, i will try that later and add the link in this ticket.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.2.1
Xcode version: Not installed

**Comment by ghenry22** [comment]
I just noticed the same on pages without refresher, just have a list in the page, scroll down a bit and open the side.menu, the content will fully or partially disappear and will pop back when you close the window.  I only see it on iOS

**Comment by bolivir** [comment]
For me it will not happen always when not using the refresher first. If i use the refresher the content will always disappear or partially disappear. I didnt had the time to test it on ios. Hope that they come with a fix soon :(

**Comment by bolivir** [comment]
Any feedback from the ionic team would be nice

**Comment by unfg** [comment]
I have the same issue from at least RC4, may be earlier. @bolivir, have you find some temporary fix or some another solution.

**Comment by daveshirman** [comment]
I think this is related to a bug I submitted guys, see the gif in the bug report:

#9518

**Comment by unfg** [comment]
@daveshirman i think both tasks have a one reason. But i have this bug without virtual scroll element. I have this bug only when i use menu component with ion-refresher.

**Comment by ozexpert** [comment]
This doesn't seems like refresher problem. I do have problem without refresher. 
but same problem as https://github.com/driftyco/ionic/issues/9518

**Comment by MaherSaif** [comment]
I found that, the issue happens if `translate: transformZ(0px);` is added to **.scroll-content** element, and that is what **ion-refresher** do when activated.

If I overrided that attribute with none, everything goes ok.

**Comment by imamjnn** [comment]
I am experiencing similar problems, and I am trying to change in this section in app.scss

`ion-content {
  pointer-events: auto !important;
}`
