### ISSUE TITLE
RC5: Invalid form is submitted when pressing the 'enter' ('Go') key on iOS

### ISSUE THREAD

**Issue by ValterSantosMatos** [ionic-team/ionic#10088]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Create a form with a require input field. Click on the first input but don't input any data. Click ('go') on the IOS keyboard, the form is submitted.

**Expected behavior:**
The form is not submitted if the form is invalid.

**Steps to reproduce:**
Couldn't test Android only IOS.

**Comment by ataraxus** [comment]
@ValterSantosMatos yould you provide a minimal test case, based on `ionic start --v2 issue-10088 blank` 

Do you built it with --prod flag or without? do they behave the same way?

**Comment by ValterSantosMatos** [comment]
Hi there, sorry for the lack of details. Actually I tested a bit more and this only happens if you have a ion-select element inside the form. 
I build with both --prod flag and without. 

[This is the repo](https://github.com/ValterSantosMatos/ionic-10088)

Let me know if I can help,

The relevant code:

```
<form [formGroup]="form" novalidate (ngSubmit)="submit()">
    <ion-item-group>
      <ion-item>
        <ion-label stacked>Name</ion-label>
        <ion-input type="text" formControlName="name"></ion-input>
      </ion-item>
      <ion-item>
        <ion-select formControlName="gender">
          <ion-option value="f" selected="true">Female</ion-option>
          <ion-option value="m">Male</ion-option>
        </ion-select>
      </ion-item>
      <ion-item>
        <button ion-button default block type="submit" [disabled]="!form.valid || form.untouched">Submit</button>
      </ion-item>
    </ion-item-group>
  </form>
  <p>Counter: {{counter}}</p>
```
```
import { Component } from '@angular/core';
import { Validators, FormBuilder } from '@angular/forms';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  public form;
  public counter = 0;

  constructor(private formBuilder: FormBuilder) {
    this.form = formBuilder.group({
      name: [null, Validators.required],
      gender: ['m'],
    });
  }
  submit() {
    console.log(this.form.value);
    this.counter++;
  }
}
```
