### ISSUE TITLE
datetime showing 'A...' instead of 'AM' in Windows version

### ISSUE THREAD

**Issue by aggarwalankush** [ionic-team/ionic#10096]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
'A...' is showing instead of 'AM'.

**Expected behavior:**
'AM' should be shown instead of 'A...' 😛 

**Steps to reproduce:**
Go to https://ionicframework.com/docs/v2/components/#datetime and switch to windows and click start time.

![ionic component documentation](https://cloud.githubusercontent.com/assets/8744282/22092311/9f625b8a-ddb1-11e6-8615-364b380876e5.png)

**Comment by AmitMY** [comment]
@jgw96 Can't reproduce anymore
