### ISSUE TITLE
ion-img exception when using ng-content

### ISSUE THREAD

**Issue by alan-agius4** [ionic-team/ionic#10093]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
An exception is being thrown `Cannot read property 'isImgsUpdatable' of null ; `

Looks like the `DI` for `Content` is being lost. Even though it is present in a parent component.

**Expected behavior:**
No exception

**Steps to reproduce:**

In my application I have like a layout system which is using ng-content, DI seems to be lost for the Content for a reason or another. I tried to create custom components and tested the DI and it does work. So it doesn't seem to be a limitation from Angular.

http://plnkr.co/edit/WZFafhdPqir6XaR4xIzt?p=preview

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic 2 RC5 
```

**Comment by mhartington** [comment]
In this case, ion-img needs to be a direct child of ion-content. It cannot work with content projection because of how it gets a reference to the ion-content.

Also, ion-img is meant to be used with virtual scroll.
