### ISSUE TITLE
Dismissing an alert will dismiss a second alert if the second was opened while dismissing the first one

### ISSUE THREAD

**Issue by peterbakonyi05** [ionic-team/ionic#10124]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
If an alert is dismissed calling .dismiss() before the button handler calls dismiss in a setTimeout in ViewController and we open another alert in the meantime, the second alert will be dismissed too.

**Expected behavior:**
Second alert stays open.

**Steps to reproduce:**
https://embed.plnkr.co/HDxdnbYNt9sBZ4F8mUwv/

Click on Display Alert button and see what happens.

**Related code:**

```
// this will be called reacting to a button click
displayAlert() {
    const alert = this.alertCtrl.create({
      title: "First alert",
      message: "Body",
      buttons: [
        {
          text: "OK",
          handler: () => {
            alert.dismiss();
            this.displaySecondAlert();
          }
        }
      ]
    });
    
    alert.present();
  }
  
  private displaySecondAlert() {
     this.alertCtrl.create({
        title: "Second alert",
        message: "Body",
        buttons: ["Close"]
      }).present();
  }
```

**Comment by danishin** [comment]
I'm experiencing the same issue in V2.2.0. This issue seems to be related to #7009 and possibly #5818 (at least what i could find so far).

Putting `alert2.present()` inside `alert1.onDidDismiss` doesn't work either without nesting it with another `setTimeout`.
