### ISSUE TITLE
Popover doesn't change position on Screen Orentation Change if kept open

### ISSUE THREAD

**Issue by mayurdhanokar8527** [ionic-team/ionic#10139]
Hi

I am using ionic Popover but seems to be not working well on screen orientation change. I tried in android as well as ios platforms but the css-left does not change on screen orientation change for the Popover's native element.

Portrait mode- when a Popover is opened 

![img1](https://cloud.githubusercontent.com/assets/19168446/22192225/256935ec-e158-11e6-9ca1-ef7ef38b87cf.JPG)

Landscape mode - it appears un-responsive. css-left doesnt change

![img2](https://cloud.githubusercontent.com/assets/19168446/22192253/6e4ad888-e158-11e6-9c30-59baaf7449d7.JPG)

If Popover is opened in landscape mode

![img3](https://cloud.githubusercontent.com/assets/19168446/22192301/e3c9c718-e158-11e6-9f3a-d851dbd0263e.JPG)

Now on changing orientaion to Portrait mode- Popover goes out of the screen

![img4](https://cloud.githubusercontent.com/assets/19168446/22192355/67db2998-e159-11e6-9813-c64abd7fa808.JPG)

Overall it seems that when a Popover is opened and once the css-left style is set it doesnt change on Screen Orentation.

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

**Comment by YasirPanjsheri** [comment]
yes I have the same problem as well.... it disposition itself.... even not opening the popover, and just changing the orientation and back , the popover doesn't respond, or it responds positioned off screen

**Comment by mayurdhanokar8527** [comment]
@brandyscarney I have a doubt why calculated and allign from left..  If it consists `float: right` it will require none handling. Are there some issues it need to be calculated from left????

**Comment by sudattadesai72** [comment]
I am facing the same issue. Temporary work-around add below code in app.scss   
.popover-content {
  left:unset!important;
  right:0px!important;
}

**Comment by s2hsieh** [comment]
I'm kind of cheating by closing and reopening the PopOver. Probably not advisable for resource-sake, but it works.  I'll try the CSS way now.
