### ISSUE TITLE
Ion-tabs work wrong in full screen mode 

### ISSUE THREAD

**Issue by wlz19930129** [ionic-team/ionic#10132]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I use video and ion-tabs in my app.When the video becomes full screen, the ion-tabs at the bottom also  worked, although the icons disappear.

**Expected behavior:**

When switching element to full screen mode, ion-tabs will completely disappeared and not worked.

**Steps to reproduce:**

1.Change video to full screen mode.
2.Click the zone of ion-tabs.
**Related code:**

```
IonicModule.forRoot(MyApp, {
    tabsHideOnSubPages: true
})
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.4.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.4
Xcode version: Not installed
```
insert the output from ionic info here
```

**Comment by mpaland** [comment]
Do you have a plunker, screenshot?
What are you using? Windows app, browser (which browser)?

**Comment by wlz19930129** [comment]
Briefly ,I developed the system on WIN7, and packaged it to android app to run. Besides , I added a plugin which called cordova-plugin-crosswalk-webview while packaging. 

When running “ionic serve” on chrome 54.0.2840.99 m (64-bit) and the video fills the screen, the icon-tabs will still in the bottom.
![image](https://github.com/wlz19930129/test_project/blob/master/full%20screen%20mode%20in%20browser.png)
On the other hand, When ionic is running on a android phone platform and the video fills the screen, the icon-tabs disappeared and video control does not worked. Meanwhile ,the app will switch to ‘home tab’ page when I click the PLAY button.
![image](https://github.com/wlz19930129/test_project/blob/master/full%20screen%20mode%20in%20android.png)

**Comment by wlz19930129** [comment]
Briefly ,I developed the system on WIN7, and packaged it to android app to run. Besides , I added a plugin which called cordova-plugin-crosswalk-webview while packaging.

When running $B!H(Bionic serve$B!I(B on chrome 54.0.2840.99 m (64-bit) and the video fills the screen, the icon-tabs will still in the bottom.

On the other hand, When ionic is running on a android phone platform and the video fills the screen, the icon-tabs disappeared and video control does not worked. Meanwhile ,the app will switch to $B!F(Bhome tab$B!G(B page when I click the PLAY button.


Do you have a plunker, screenshot?
What are you using? Windows app, browser (which browser)?

-

**Comment by wlz19930129** [comment]
Thanks for your reply!
Briefly ,I developed the system on WIN7, and packaged it to android app to run. Besides , I added a plugin which called cordova-plugin-crosswalk-webview while packaging.

When running $B!H(Bionic serve$B!I(B on chrome 54.0.2840.99 m (64-bit) and the video fills the screen, the icon-tabs will still in the bottom.
[image1.PNG][image2.PNG]
On the other hand, When ionic is running on a android phone platform and the video fills the screen, the icon-tabs disappeared and video control does not worked. Meanwhile ,the app will switch to $B!F(Bhome tab$B!G(B page when I click the PLAY button.
[image3.PNG]

Do you have a plunker, screenshot?
What are you using? Windows app, browser (which browser)?

$B!=(B

**Comment by mhartington** [comment]
Related: https://github.com/driftyco/ionic/issues/10143

**Comment by shawnlan** [comment]
I see the same issue with 2.0.1.

**Comment by shawnlan** [comment]
Current workaround for me is to set the following:

.ion-page,ion-tab{
contain:none !important
}

**Comment by Floyd1256** [comment]
Same bug exists for ionic 3+ on android. @shawnlan 👍

**Comment by ceeliro** [comment]
Facing same issue with ionic 3.5.0. Lastest tab button is pressed and navigation is performed when video is in full screen when switching to minimize mode as both minimize button and last tab button seem to be overlapping each other. Still a bug? Any plan to fix or should i go with a workaround?

Thanks in advance

**Comment by gregd** [comment]
This is the screenshot from the Chrome Remote Debugging. The tab button isn't visible but for an unknown reason the button captures click events, so I cannot use Video Controls buttons.

![video fullscreen tabs](https://user-images.githubusercontent.com/59068/31128880-4c1f3048-a853-11e7-9d55-9baf78e3a420.png)

**Comment by RailgunWinjoy** [comment]
hi have you fixed the problems video controls bar in fullscreen mode on android

**Comment by maxpaj** [comment]
Just wanted to bump the thread.

```
$ ionic info
cli packages: (C:\Users\\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.3.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.6.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

I'm using `video.js` in my Ionic app, which is simply a wrapper for the HTML5 video element. When in video fullscreen, tabs are still showing at the bottom.

**Comment by updraftiq** [comment]
Any progress on this issue? I am seeing the same thing using Ionic 3.
- on android
- video in full screen on my media tab
  
**user cannot get out of full screen mode** because clicking the icon to do so in the video player doesn't work, **ionic just navigates to the tab that is hidden behind it**

**Comment by chhota89** [comment]
any Progress on this issue. Facing same issue when full screen mode is open control is not clickable.

**Comment by KiwiKilian** [comment]
Still a problem with Ionic 3 on Android. In my case the tabs are still visible when in fullscreen. The fix by https://github.com/ionic-team/ionic/issues/10132#issuecomment-282454472 works but should be properly fixed.
