### ISSUE TITLE
[RC.5] swipe events on ion-scroll not triggered anymore

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#10131]
**Ionic version:**  (check one with "x")
2.0.0-rc.5

**I'm submitting a ...**  (check one with "x")
[X ] bug report

**Current behavior:**
swipe events on ion-scroll elements aren't triggered anymore

**Expected behavior:**
swipe events should be triggered on ion-scroll elements (as it was, was working till RC.4)

**Steps to reproduce:**
see related codes and swipe

**Related code:**

html:

    <ion-scroll #datePickerScrollY scrollY="true" id="datePickerScrollY" (swipe)="swipeDatePicker($event)">
       
    </ion-scroll>

ts:

    swipeDatePicker($event: any) {
        alert('swipe');
    }

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We will take a look at this.
