### ISSUE TITLE
Ionic 2 VirtualScroll inside Menu not displaying

### ISSUE THREAD

**Issue by justinlettau** [ionic-team/ionic#10148]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
With 2.0.0-rc.5, when using the `VirtualScroll` inside a `ionc-menu` component, the list does not display.

**Expected behavior:**
`VirtualScroll` should work inside of `ion-menu` component.

**Steps to reproduce:**
http://plnkr.co/edit/liDB70?p=preview

**Related code:**
Workaround:
```css
ion-menu {
    display: block;
    left: 100%;
}

ion-menu.show-menu {
  left: 0;
}
```

The `display: block` allows `offsetHeight` in `virtual-util.ts` to work correctly, and `left: 100%` keeps the menu off-screen when not open.

**Other information:**
The issue seems to be `VirtualScroll` uses the `offsetHeight` of its parent element ([virtual-util.ts#L545](https://github.com/driftyco/ionic/blob/master/src/components/virtual-scroll/virtual-util.ts#L545)). However, when inside of `ionc-menu`, `offsetHeight` is always `0` because the element is hidden via CSS [(menu.scss#L17)](https://github.com/driftyco/ionic/blob/master/src/components/menu/menu.scss#L17).

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by mhartington** [comment]
Right now this isn't supported, but should be something we revisit later on

**Comment by jgw96** [comment]
This also happens when virtualScroll is nested inside a div, probably because it cannot get the correct height that it would normally get from ion-content.

**Comment by edcampos** [comment]
This issue was reported on Jan, are you working on it ? Do you know when will be it fixed?
Thks..!
