### ISSUE TITLE
Windows virtual keyboard constantly pops up

### ISSUE THREAD

**Issue by iaincooper4** [ionic-team/ionic#10145]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request

**Current behavior:**
On a Windows 10 tablet or device with a virtual keyboard (no hardware keyboard), after you have tapped on an Input field, the virtual keyboard continually pops up every time you tap somewhere on screen.

**Expected behavior:**
The virtual keyboard should only be displayed when an Input field has focus.

**Steps to reproduce:**
Tap on an Input field to focus it, the virtual keyboard will popup.
Close the Virtual Keyboard
Tap on any part of the screen (but not on another element)
The virtual keyboard will popup, with no Input focus.

**Related code:**
Can reproduce on any Ionic 2 app, including the sample app located here
https://github.com/driftyco/ionic-conference-app

**Other information:**
Only occurs on Windows (10) devices. Both Android and iOS do not have this issue.

**Ionic info:**:

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by iaincooper4** [comment]
The latest version of EdgeHTML in the Windows 10 Creator's Update seems to have fixed this keyboard issue.

**Comment by jgw96** [comment]
Hello all! I can confirm that the latest release of edge does not seem to have this issue. Thanks for using Ionic!
