### ISSUE TITLE
Transparent buttons on hover with colored navbar and config mode: 'ios'

### ISSUE THREAD

**Issue by ohh2ahh** [ionic-team/ionic#10166]
**Ionic version:**
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Forcing the iOS style in `IonicModule.forRoot` results in a strange hover effect on buttons (normal buttons and the back button) in the navigation bar when the navigation is colored at the same time. The button text disappears because it gets the same color as the navigation bar.

This happens only in the browser with `ionic serve` (`http://localhost:8100`). It doesn't happen with `http://localhost:8100/?ionicplatform=android` or `http://localhost:8100/?ionicplatform=ios`.

The issue is not present with `mode: 'android'` (the hover color is dark).

**Expected behavior:**
The button should not get an hover effect or the effect should be a different color as the navigation bar.

**Steps to reproduce:**
Plunker: [http://plnkr.co/edit/97f1WQpYHRk7wL1aXry0?p=preview](http://plnkr.co/edit/97f1WQpYHRk7wL1aXry0?p=preview)

1. Start new project
2. Add `mode: 'ios'` to `src/app/app.modules.ts`:

```js
IonicModule.forRoot(AppComponent, {
  mode: 'ios'
})
```

3. Add the following header to a page:

```html
<ion-header>
  <ion-navbar color="primary">
    <ion-title>Page</ion-title>
    
    <ion-buttons start>
      <button ion-button>Button Text</button>
    </ion-buttons>
    
  </ion-navbar>
</ion-header>
```

**Related code:**
See above.

**Other information:**
-

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.6
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We will take a look into this.
