### ISSUE TITLE
searchbar: add showClearButton config option

### ISSUE THREAD

**Issue by ghenry22** [ionic-team/ionic#10162]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
even when there is text present in a searchbar once the input is unfocused the clear button is hidden.  User has to focus the searchbar input again in order to simply clear the search term.

**Expected behavior:**
similar to the showCancelButton option
add an option to always show the clear button when search input.length > 0.
 [showClearButton]="shouldShowClear"

this would leave the little clear icon visible and able to be tapped to clear the input without having to first focus on the searchbox and bring up the keyboard.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We will take a look at this post 2.0 stable. Thanks for using Ionic!

**Comment by jaufgang** [comment]
I believe that that this should be the default behaviour, and not just an option.  when the  searchbar has a value and the user has set showcancelbutton="true", the button should show persistently evem when the searchbar loses focus.  I can't see any reason why you would want to hide it when the searcbar has lost focus.  

Also, FWIW, I have figured out a a workaround.  You can obtain the desired behaviour by adding this to your css:

```css
.searchbar-has-value .searchbar-clear-icon {
    display: block;
}
```
