### ISSUE TITLE
v2 secondary toolbar added dynamically does not change ion-content dimensions

### ISSUE THREAD

**Issue by barocsi** [ionic-team/ionic#10164]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I want to add another network indicator toolbar  dynamically to the header. However when it happens, it does not recalculate the size of the content resulting the OVERLAY of the toolbar.

**Expected behavior:**
Something finally please please just make thinks reliable and working, its a so simple pattern that I want to add another toolbar on the header.

**Related code:**

```
<ion-header>
    <ion-navbar>
        <ion-title>{{car.name}}</ion-title>
        <ion-buttons end>
            <button ion-button small outline (click)="editCarClicked()">
                {{ 'GENERIC.EDIT' | translate}}
            </button>
        </ion-buttons>
    </ion-navbar>
    <ion-toolbar>
        <ion-segment [(ngModel)]="menu">
            <ion-segment-button (ionSelect)="selectedItem('pins')" value="pins">
                {{'CAR_PAGE.COMMANDS.TITLE' | translate}}
            </ion-segment-button>
            <ion-segment-button (ionSelect)="selectedItem('information')" value="information">
                {{ 'CAR_PAGE.INFORMATION.TITLE' | translate}}
            </ion-segment-button>
        </ion-segment>
    </ion-toolbar>
    <ion-toolbar class="network-indicator-wrapper" *ngIf="networkService.is_offline">
    <div class="network-indicator">{{'GENERIC.OFFLINE_MODE' | translate}}</div>
</ion-toolbar>
</ion-header>
```

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.6
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.3.0
Xcode version: Not installed

```

![image](https://cloud.githubusercontent.com/assets/851560/22283175/10f59d96-e2e1-11e6-87ea-5502245f2117.png)

**Comment by comfortme** [comment]
you should call content.resize()
http://ionicframework.com/docs/v2/api/components/content/Content/

**Comment by barocsi** [comment]
Thanks

**Comment by barocsi** [comment]
```
export class NetworkIndicatorComponent {

    @Input() target_container: Content;
    subscription: any;

    constructor(private networkService: NetworkSerice) {
    }

    ngOnInit() {
        this.subscription = this.networkService.is_offline.subscribe(item => {
            if (this.target_container) {
                this.target_container.resize();
            }
        });
    }
}
```

Uncaught TypeError: Cannot read property 'ev' of null
    at Content._readDimensions (content.js:526)
    at dispatch (dom-controller.js:128)
    at DomController._flush (dom-controller.js:102)
    at rafCallback (dom-controller.js:95)

**Comment by barocsi** [comment]
Well it kind of works, however my dynamically added components STAY on screen during the animation.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. We will take a look into this!

**Comment by brandyscarney** [comment]
@barocsi Can you please create a plunker or sample repository that we can use to look into this?

**Comment by barocsi** [comment]
sorry im in a rush currently, so I have hacked it to work, 
To reproduce you might want to use the example
http://ionicframework.com/docs/v2/api/components/content/Content/
but by adding it on a modal, then just close the modal, preview it on iOS/Chrome+iOS and see when the modal slides out on back/close, the dynamically added div stays in a layover mode until animation completes.

**Comment by ghenry22** [comment]
On iOS the resize call works to push the content down below the newly added toolbar, however, once the toolbar is hidden again if you call resize again the content size is not readjusted, leaving an extra space at the top the size of the now hidden toolbar.
