### ISSUE TITLE
Buttons and forms doesn't update/work the first time I install/open/serve the app.

### ISSUE THREAD

**Issue by synga** [ionic-team/ionic#10182]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When i first open an app after install/serve and use the login (via firebase email auth) the buttons, forms, inputs, radio buttons, nothing works. I can click, select, type and anything, but it doesn't update my view só *ngIf, [ngSwitch], [ngClass] and any other directive can work.
But if i close the app or press home button on device, or f5 my browser page it all works as expected in most of cases.
(Everything was working some days ago before i updated to rc5, now it persists on 2 final release).

**Expected behavior:**
Forms and buttons updating their states with angular directives as they've ever done.

**Steps to reproduce:**

**Related code:**

```
Example of a page where i have a form that it's not working, it's in the footer and was working days ago

<ion-footer color="azul-background" *ngIf="paciente.vinculado" class="footer-mensagem">
    <ion-item [formGroup]="novaMensagem">
        <input type="text" formControlName="mensagem" placeholder="Nova mensagem" />
        <button type="submit" ion-button clear item-right (click)="enviarMsg()" [disabled]="!novaMensagem.valid">Enviar</button>
    </ion-item>
</ion-footer>

THE PAGE .TS FILE

import { Component, ViewChild } from '@angular/core';
import { NavController, NavParams, ToastController, LoadingController, Content } from 'ionic-angular';
import firebase from 'firebase';
import { Storage } from '@ionic/storage';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Http, Headers, RequestOptions } from '@angular/http';

@Component({
    selector: 'page-medico-mensagem-direta',
    templateUrl: 'medico-mensagem-direta.html'
})
export class MedicoMensagemDiretaPage {
    @ViewChild(Content) content: Content;

    novaMensagem: FormGroup;
    mensagem: any;
    paciente: any;
    mensagens: any[] = [];

    constructor(public navCtrl: NavController, public navp: NavParams, public toastCtrl: ToastController, public load: LoadingController, public storage: Storage, public http: Http, public formb: FormBuilder) {
        this.paciente = navp.data;

        this.novaMensagem = formb.group({
            mensagem: ['', Validators.required]
        })
    }

AND THIS IS A PART OF A PAGE WHERE IT'S SUPOSED TO CHANGE THE BUTTON COLOR IF THE USER CLICK ON THAT BUTTON
<ion-content class="page-paciente page-paciente-reportar">
    <ion-item-group>
        <ion-item-divider>Como estou me sentindo?</ion-item-divider>
        <h5 *ngIf="ultimoSentindo != null" padding-horizontal text-center>Último reportado: {{ultimoSentindo}}</h5>

        <ion-grid padding class="panel-buttons">
            <ion-row>
                <ion-col width-25>
                    <button class="button-default evento" [class.botao-selecionado]="sentindo == 'Mal'" (click)="sentindo = 'Mal'" id="mal"><i class="flaticon-sad"></i><span>Mal</span></button>
                </ion-col>
                <ion-col width-25>
                    <button class="button-default evento" [class.botao-selecionado]="sentindo == 'Indisposto'" (click)="sentindo = 'Indisposto'" id="indisposto"><i class="flaticon-surprised"></i><span>Indisposto</span></button>
                </ion-col>
                <ion-col width-25>
                    <button class="button-default evento" [class.botao-selecionado]="sentindo == 'Bem'" (click)="sentindo = 'Bem'" id="bem"><i class="flaticon-happy"></i><span>Bem</span></button>
                </ion-col>
                <ion-col width-25>
                    <button class="button-default evento" [class.botao-selecionado]="sentindo == 'Otimo'" (click)="sentindo = 'Otimo'" id="otimo"><i class="flaticon-vary-happy"></i><span>Ótimo</span></button>
                </ion-col>
            </ion-row>
        </ion-grid>
    </ion-item-group>
  </ion-conten>

MY PACKAGE.JSON
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve",
    "minify": "ionic-app-scripts minify"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/app-scripts": "^1.0.0",
    "@ionic/cloud-angular": "^0.8.0",
    "@ionic/storage": "1.1.7",
    "@types/jasmine": "^2.5.36",
    "angular2-text-mask": "^2.1.0",
    "angularfire2": "^2.0.0-beta.6",
    "cordova-plugin-fcm": "^1.1.5",
    "cordova-plugin-googleplayservices": "^19.0.3",
    "firebase": "^3.6.6",
    "ionic-angular": "2.0.0",
    "ionic-native": "2.2.11",
    "ionicons": "3.0.0",
    "moment": "^2.17.1",
    "rxjs": "^5.0.0-beta.12",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^1.0.0",
    "@types/request": "0.0.30",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [],
  "description": "Doutor Acompanha App Project"
}

```

**Other information:**
So as i said it was working, haven't installed anything but uninstalled some plugins (network info and device orientation), just have created new pages, nothing more.
Using the console i've seen it's not setting the form input class to ng-touched and ng-dirty.
In the buttons example i've tryed calling a function to update the var i'm using to compare in the [class]/[ngClass] and then console.loging it. It logs the value to my console, but the button clas doesn't change, if i change my browser tab and then come back it sets the class to the button or the ng-touched/dirty to the input.

**Here's a example:**
This is my footer code working, if i open the page and star typing it doesn't changes anything in the view
![input untouched](https://cloud.githubusercontent.com/assets/9086829/22331996/af3de902-e3b5-11e6-823a-4ba32e3b91f3.PNG)

But if i change to another tab in my browser, when i come back to the ionic serve page it updates. The same works for installed apk
![input touched](https://cloud.githubusercontent.com/assets/9086829/22332028/d902373e-e3b5-11e6-8eb9-da14452bfba1.PNG)

I'm posting this here, but if you guys says it's a angular 2 problem i'll transfer this to angular issues.
Thanks in advance.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by mhartington** [comment]
can you put this together in a small git repo? It will make debugging a bit easier

**Comment by synga** [comment]
ok, will post the repo here soon

**Comment by synga** [comment]
Here's the repo:
https://github.com/synga/Ionic2

In the read.me there's some new info

**Comment by synga** [comment]
So i made a workaround in this.
It looks like using NavControll methods inside a Firebase promisse seems to break some of the app's functions. I don't know what is breaking, if it's TypeScript, Angular, Firebase or Ionic, so i'll leave this issue open and if someone judges it's not a Ionic problem, feel free to close. This is what i've done:

I have a auth provider where all my firebase auth methods are, so i encapsulated my login inside a types Promise<> and returned it like this:

    `login = (email: string, senha: string): Promise<{ name: string, gen: string, pic: string }> => {
        let loader = this.load.create({ content: 'Wait...' });
        loader.present();
        return new Promise<{ name: string, gen: string, pic: string }>((resolver, rejeitar) => {
            this.fireAuth.signInWithEmailAndPassword(email, senha).then(res => {
                firebase.database().ref('Usuarios/' + res.uid).once('value').then(snapshot => {
                    loader.dismiss();
                    resolver({
                        name: snapshot.val().nome,
                        gen: snapshot.val().genero,
                        pic: snapshot.val().avatar
                    });
                });
       });
    }`

And then in my login.ts when all is done i use setRoot.
This works for loging in, creating new account and logout (all basic firebase auth operations).

**Comment by daviddk** [comment]
Also having similar issues where binding a [disabled]="myString.length > 3" or [disabled]="!myForm.valid" isn't updating after the string or form is updated.. only happens the first time the app is opened.. 

Used to work fine up until we upgraded to Ionic Final 2.0.0 (and now 2.0.1). 

However, on blur, the element with the [disabled] binding is updated. When it used to update all the time constantly as the value in the input box/form was changing

**Comment by alexnu** [comment]
Hey @synga I am facing the exact same issue with my app (Ionic 3.4.2, Angular 4.1.3, Typescript 2.3.4, Firebase 4.1.3). The problem in my case is that I am using FirebaseUI for the authentication which doesn't give me control to apply the workaround that you suggested.

The only thing that I can change is the callback for onAuthStateChanged() which is this simple code set on `app.component.ts` when the app starts:

````javascript
firebase.auth().onAuthStateChanged((user) => {
  if (user) {
    // User is authenticated.
    this.nav.setRootPage('HomePage');
  } else {
    // User is not authenticated.
    this.nav.setRootPage('LoginPage');
  }
});
````

Have you found any other solution by now?

**Comment by synga** [comment]
Hi @alexnu I've seen some people subscribing to the Auth event, and some people using ngZone to help. So try this:

    const unsubscribe = firebase.auth().onAuthStateChanged(user => {
      if (user) {
        this.nav.setRootPage('HomePage');
        unsubscribe();
      } else {
        this.nav.setRootPage('LoginPage');
        unsubscribe();
      }
    });

And with `ngZone`

    import { NgZone } from '@angular/core';

    zone: NgZone;

    this.zone = new NgZone({});
    const unsubscribe = firebase.auth().onAuthStateChanged((user) => {
      this.zone.run(() => {
        if (user) {
          this.nav.setRootPage('HomePage');
          unsubscribe();
        } else {
          this.nav.setRootPage('LoginPage');
          unsubscribe();
        }
      });
    });

Both examples i've seen on JaveBratt's tutorials, the ngZone one is a little more old. I'm using the ngZone one, haven't tried the simpler newer one to know if it works. Hope this helps.

**Comment by alexnu** [comment]
Thanks, I tried the ngZone solution and it works fine, I also saw it in this [issue](https://github.com/ionic-team/ionic/issues/9798).

So it appears as a problem with firebase, but does this mean that all firebase callbacks should be invoked in the proper zone, like the example below, or is it only a problem with firebase auth?

````javascript
itemsRef.push(newItem).then(() => this.navCtrl.pop());
````

**Comment by synga** [comment]
Yes, the callback should be invoked like in your example and it's only a problem with `firebase.auth()`. In a early version of Ionic 2 there was a concurrence problem with every firebase method for using the with `LoadinController` or `NavControll push(), pop() and setRoot()`. So they made LoadingController's `present()` return a promise. But there's something wrong with the firebase's promise returned, when i used

    someFunction().then(() =>{
      firebase.auth().signOut().then(() =>{
        this.navCtrl.push();
      });
    });

It had errors, i wasn't able to click buttons, the view didn't render the way it's suposed to.

But having the firebase methods inside another functions it worked fine, like this:

    someFunction().then(() =>{
      myPromise().then((res) =>{
        this.navCtrl.push();
      });
    });

    myPromise = (): Promise<boolean> => {
      return new Promise<boolean>(res => {
        firebase.auth().signOut().then(() => {
          res(true);
        });
      })
    };

The case is it's not a problem with firebase (i think), there's something in Ionic that's not getting right after a firebase return.
The way is using auth() methods inside of functions you create, return your promise and then do your code.

**Comment by alexnu** [comment]
Wow thanks, that was really helpful! I will be using this solution until the problem is fixed.
