### ISSUE TITLE
[BUG] content disappears when keyboard is up

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#10183]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When having slides, with a scroll, as suggested [here](https://github.com/driftyco/ionic/issues/9839), in the last comment, the content disappears when opening the keyboard, except for the first input.

Note: this happens on device, in this example I am using an android emulator, but it also happens if you `serve` and open the page via iPhone.

[Here ](https://www.youtube.com/watch?v=C9w15LK10w0) is a video demonstration

**Expected behavior:**
Normal input behavior

**Steps to reproduce:**
As said, I am running this on a device, so plunkr won't work.
This is the relevant code:
```
<ion-slides #slider pager class="swiper-no-swiping">
    <ion-slide class="scroll-content">
        <ion-scroll scrollY="true">
            <h2>Tab title</h2>
            <ion-list>
                <ion-item *ngFor="let i of [1,2,3,4,5,6,7,8,9,10]">
                    <ion-label floating>Text field</ion-label>
                    <ion-input type="text" [(ngModel)]="text"></ion-input>
                </ion-item>
            </ion-list>
        </ion-scroll>
    </ion-slide>
</ion-slides>
```

This is the CSS:
```
ion-scroll {
	position: absolute;
	top: 0;
	bottom: 0;
	width: 100%;
}
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello @AmitMY , thanks for opening an issue with us and a HUGE thanks for the detailed info and repro case. We will take a look into this.

**Comment by mattbryan9** [comment]
I have this as well, with an ion-content inside an ion-slide. Unfortunately, everything in the ion-slides remains invisible after the keyboard is closed; I can actually interact with elements, type into inputs, etc, but can't see anything. Any manual changes to styling (i.e. in the web inspector) immediately make the contents of the slider visible again. For us this only happens on iOS.

```
<ion-slides runCallbacksOnInit="true" [pager]="false"(ionSlideDidChange)="onSlideChange()">
    <template [ngIf]="condition">
        ${require('./foo.html')}
    </template>
    <template ngFor let-s [ngForOf]="slides" let-i="index">
        <ion-slide layout="column">
            <ion-content flex fullscreen="true">
                <div>
                   content goes here
                </div>
            </ion-content>
        </ion-slide>
    </template>
</ion-slides>
```

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: macOS Sierra
Node Version: v4.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by chrislow** [comment]
1+ same issue here, using inputs inside slides.

**Comment by ghaiat** [comment]
any update on this ? or any workaround?

**Comment by daraul** [comment]
I had this issue, but found this [fix on stackoverflow](https://stackoverflow.com/questions/36827211/ionic2-content-in-slides-not-scrolling#41176943). So far this seems like an alright solution, but I'm not certain. The padding above the keyboard still feels too big I took some screenshots in Chrome's devtools 

Without keyboard: 
![image](https://cloud.githubusercontent.com/assets/2440975/24819239/d4af949a-1bb1-11e7-94c7-99f1ff3d3feb.png)

With keyboard:
![image](https://cloud.githubusercontent.com/assets/2440975/24819262/e12b5470-1bb1-11e7-9034-8c40987ca7e2.png)

**Comment by zakton5** [comment]
+1

**Comment by chrismclarke** [comment]
+1

**Comment by aymehri** [comment]
+1

**Comment by milanosie** [comment]
Problem still open.... Having the same issue here

**Comment by gbrits** [comment]
.scroll-content {
        margin-bottom: -56px !important;
    }

**Comment by tr049** [comment]
Facing same issue

**Comment by llalueza** [comment]
Same issue on my side too and it seems there´s no fix/temporal patch working like in other versions.

**Comment by raessafathulalim** [comment]
have same issue here.
`cli packages: (/usr/local/lib/node_modules)
@ionic/cli-utils : 1.19.0
ionic (Ionic CLI) : 3.19.0
global packages:
cordova (Cordova CLI) : 7.1.0 
local packages:
@ionic/app-scripts : 3.1.4-201711302144
Cordova Platforms : android 6.3.0
Ionic Framework : ionic-angular 3.9.2
System:
Node : v6.11.4
npm : 3.10.10 
OS : OS X El Capitan
Xcode : Xcode 8.2.1 Build version 8C1002`

i have try with this but not working

[https://gist.github.com/EvanWillms/8773f8cfa12f469fabf0bdd7a75723e7](https://gist.github.com/EvanWillms/8773f8cfa12f469fabf0bdd7a75723e7)

`config: {
    // These options are available in ionic-angular@2.0.0-beta.2 and up.
    scrollAssist: false,    // Valid options appear to be [true, false]
    autoFocusAssist: false  // Valid options appear to be ['instant', 'delay', false]
  } // http://ionicframework.com/docs/v2/api/config/Config/`

is not supported with ionic 3 i guess

**Comment by iamongit** [comment]
Is there an actual solution for this issue anywhere? I've found at least a dozen threads linking each other but no definitive solution. I've wasted lot of time on it, tried all solutions but nothing is working. The scrolling behavior on focus is unpredictable.

**Comment by pradt** [comment]
@gbrits  solution worked for me thank you.

**Comment by carvarr** [comment]
any solution ?
