### ISSUE TITLE
issue(prompt alert): Should show in middle of the screen as per native alert

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#10187]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] issue
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
A prompt alert on a large device like an iPad (on iOS) is being displayed at the top half of the screen:

![image](https://cloud.githubusercontent.com/assets/2852839/22339667/7e65adea-e3f3-11e6-9726-294d35c2e270.png)

I am assuming this is done because then the keyboard appears, the alert will be in the right place.

**Expected behavior:**
This needs to work more like a native app. The prompt to appear in the center of the screen. When the software keyboard opens up, the alert needs to slide into the correct position near the top of the screen.

**Steps to reproduce:**
Create any [prompt alert](http://ionicframework.com/docs/v2/components/#alert-prompt) on an iPad and note it's positioning.  

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by AmitMY** [comment]
The reasoning: ([here](https://github.com/ionic-team/ionic/blob/2743c635376dec35c8aaf472fbdda3cda6de81f7/src/components/alert/alert-component.ts#L183))

> this alert has a text input and it's on a mobile device so we should align
> the alert up high because we need to leave space for the virtual keboard
> this also helps prevent the layout getting all messed up from
> the browser trying to scroll the input into a safe area

The new keyboard fixes might fix this, as "alert padding when it has text-inputs #10187 (fix: new keyboard plugin)"

**Comment by shawnlan** [comment]
@AmitMY so we can have prompt alert in the middle of the screen now?

**Comment by AmitMY** [comment]
@shawnlan 
> The new keyboard fixes might fix this
This needs device testing, which I can not do myself.

**Comment by davorpeic** [comment]
This is also kinda annoying on iphone too, can we help testing something? I have latest keyboard plugin

**Comment by AmitMY** [comment]
Currently it still is with a fixed top.
If you can change it for yourself, and it works well on an iPhone, let us know, and let’s make a PR of it.

**Comment by davorpeic** [comment]
Ok, at this moment it is not critical, if I do something will let you know. thanks

**Comment by Tyler-Darby** [comment]
We are facing this issue as well. Not critical for us at the moment either, but it would be nice to see this resolved. This doesn't happen on Android for us, only iOS. 

I know there is some reworking with the keyboard plugin coming out soon involving WKWebView, maybe this could be worked in with that?

**Comment by DorthyS** [comment]
I am having this issue too

**Comment by vzts** [comment]
It happens in Android 6.0.1 as well, was kinda confused for a moment.

**Comment by dgbrunoh** [comment]
I've override the "alert-top" class with the code below:
```css
.alert-top{
    padding: 0 !important;
    align-items: center !important;
}
```
don't know about the main issues with keyboard though ... but this solved my problem...
