### ISSUE TITLE
Nested Slides, wrong length()

### ISSUE THREAD

**Issue by escobar5** [ionic-team/ionic#10195]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When you have one <ion-slide> inside another, the length() of the parent one is wrong, the length() is returning the sum of all slides (parent and children)

**Expected behavior:**
The parent slide should return only it's own count of slides.

**Steps to reproduce:**
Open the plunkr, and click on the button "Check length", the length must be 4 but it is 16.

http://plnkr.co/edit/wL8NXdQeqdbUayQvqWJW?p=preview

**Comment by jgw96** [comment]
Hello @escobar5 , did this used to work in a previous rc release? Assuming your on 2.0.0 now?

**Comment by escobar5** [comment]
Yes, I'm on 2.0.0, and yes, it used to work, I had other problems, like wrong number of bullets in pagination (also because of nested slides), this one was fixed, but the other appeared.

**Comment by jgw96** [comment]
Alright, thanks for getting back to me. We will take a look into this (:

**Comment by JoeriShoeby** [comment]
Are there any updates on this one? Running into the same issue ..

**Comment by darron1217** [comment]
This is what happening on my app...
npm 'ionic-angular' version 2.0.1

![sample](https://cloud.githubusercontent.com/assets/8064923/22958657/02537d64-f374-11e6-948d-8889d60904bc.gif)

**Comment by darron1217** [comment]
@jgw96 
https://github.com/driftyco/ionic/blob/master/src/components/slides/swiper/swiper.ts#L357
This line causes current problem. Swiper should use a method which selects 'ion-slide' which is direct children of current 'ion-slides', instead of using .querySelectorAll()

**Comment by mlacorte** [comment]
Thanks @darron1217, you saved me a lot of debugging time. I submitted a pull request that should fix the issue.
