### ISSUE TITLE
No nested property on Slides Component

### ISSUE THREAD

**Issue by Artfloriani** [ionic-team/ionic#10192]
I am recreating this issue as it was closed as I might not have explained it well and it was not solved.
Original issue: https://github.com/driftyco/ionic/issues/10191

**Ionic version:** 
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  
[x] bug report

**Current behavior:**
After the Slides component was changed on Ionic RC.5, the `nested` parameter is not available on the Slides component even when using the Advanced options. The `nested` parameter is not available on the [Slides.ts](https://github.com/driftyco/ionic/blob/master/src/components/slides/slides.ts)

**Expected behavior:**
Expose `nested` Slides parameter as an advanced option.

**Ionic info:**

```
Cordova CLI: 6.5.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Ahh sorry about that @Artfloriani , my fault and thanks for reopening!

**Comment by Artfloriani** [comment]
Is there any temporary workaround for this?

**Comment by jgw96** [comment]
Sorry but at the moment there isnt, we would have to add this feature back.

**Comment by Artfloriani** [comment]
If i manually edit the Slides.ts just to include this parameter would this work? Or is there a deep magic happening to bind the options with the Swipper API?

**Comment by mhartington** [comment]
It's a bit more than just adding the nested property. Looking at swipers original codebase, there's a lot of logic in the internals that check for nested slides, so we'd have to go back and add that functionality

**Comment by darron1217** [comment]
@jgw96 @mhartington 
I also really need this feature...

What I'm planning to make is... (http://idangero.us/swiper/)
![nested_slide](https://cloud.githubusercontent.com/assets/8064923/22962205/c1b88dd8-f38e-11e6-8137-53eb314c5eb5.gif)

But I'm stuck here...
![nested_slide_mine](https://cloud.githubusercontent.com/assets/8064923/22962283/4d9270d0-f38f-11e6-9a2a-276dee17f580.gif)

Any workaround would be appreciated :)

**Comment by snortblt** [comment]
+1. Looking for vertical Slides within a horizontal one.

**Comment by gsimonpotla** [comment]
Hi, would there be any update or workaround or at least ETA for this regression ?

**Comment by gitmyhub** [comment]
Hi...I need to add vertical slides within a horizontal slide which is possible using nesting with swiper API. Could you please let us know if this is going to be added?
