### ISSUE TITLE
(bug) iOS scroll bounce glitch on a list with inputs

### ISSUE THREAD

**Issue by Reeeemi** [ionic-team/ionic#10204]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On a list that contains input fields, the scroll bouncing glitches. While bouncing, 'ghosting' list items are shown. It happens at the top of the list, as well as at the bottom of the list. The following GIF illustrates the problem:
![bounce_problem](https://cloud.githubusercontent.com/assets/10634742/22366834/f374d44a-e47e-11e6-9e55-30c7b35f6a83.gif)

**Expected behavior:**
The bouncing should be smooth, just like on lists that do not contain inputs.

**Steps to reproduce:**

Create a list containing one or more input fields, run on iOS, then drag and quickly release the top or bottom of the list so it bounces. It does not happen every time, so do it a couple of times.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Could you please post a repo or code sample we can use to reproduce this issue? Thanks!

**Comment by Reeeemi** [comment]
Sure. It's just the 'ionic start --v2 myApp tabs' with an input list added to the first page:

https://github.com/Reeeemi/ionic-scroll-list

**Comment by Reeeemi** [comment]
Any news?

**Comment by gabrielvisconti89** [comment]
Still happening in Ionic 3.19.0 with iOS 11
