### ISSUE TITLE
ion-content flicker when i tap status bar on ios

### ISSUE THREAD

**Issue by taygundonma** [ionic-team/ionic#10205]
**Ionic version:**  
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...** 
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When i tapped to status bar ion-content flicker suddenly. I think there is a problem with animation when i tapped to status bar list become to top as default next tapping to status bar flicker. Btw i m currently using V2 RC.6

This is the gif of mhartington example from github

https://giphy.com/gifs/26xBuwLSnTRBtVlmM

**Comment by jgw96** [comment]
Hello, thanks for using Ionic, we will look into this.

**Comment by taygundonma** [comment]
@jgw96 What about that bug, do you have any solution ?

**Comment by mobinius-shreesha** [comment]
In IOS,if we tap on statusbar whole ion-content will blinks in IONIC2.How to resolve this issue.Please suggest..
Thank You.

**Comment by mobinius-shreesha** [comment]
Please resolve issue..

**Comment by jainpiyushb** [comment]
@taygundonma Its a problem on Ionic v1 as well.

**Comment by jainpiyushb** [comment]
If you try to debug this on Xcode, WebView throws the following exceptions every time you click on the status bar.

```
[WebActionDisablingCALayerDelegate willBeRemoved]: unrecognized selector sent to instance 0x170016900

*** WebKit discarded an uncaught exception in the webView:willRemoveScrollingLayer:withContentsLayer:forNode: delegate: <NSInvalidArgumentException> -[WebActionDisablingCALayerDelegate willBeRemoved]: unrecognized selector sent to instance 0x170016900

-[WebActionDisablingCALayerDelegate willBeRemoved]: unrecognized selector sent to instance 0x170016900

*** WebKit discarded an uncaught exception in the webView:willRemoveScrollingLayer:withContentsLayer:forNode: delegate: <NSInvalidArgumentException> -[WebActionDisablingCALayerDelegate willBeRemoved]: unrecognized selector sent to instance 0x170016900

-[WebActionDisablingCALayerDelegate willBeRemoved]: unrecognized selector sent to instance 0x170016900

*** WebKit discarded an uncaught exception in the webView:willRemoveScrollingLayer:withContentsLayer:forNode: delegate: <NSInvalidArgumentException> -[WebActionDisablingCALayerDelegate willBeRemoved]: unrecognized selector sent to instance 0x170016900

[WebActionDisablingCALayerDelegate willBeRemoved]: unrecognized selector sent to instance 0x170016900

*** WebKit discarded an uncaught exception in the webView:willRemoveScrollingLayer:withContentsLayer:forNode: delegate: <NSInvalidArgumentException> -[WebActionDisablingCALayerDelegate willBeRemoved]: unrecognized selector sent to instance 0x170016900
```
(Removed the timestamp and project name from the logs above)

Don't know it this is helpful.

**Comment by jainpiyushb** [comment]
Use overflow-scroll="false" on ion-content fixed the problem. (Using Ionic v1)

**Comment by RohinMohanadas** [comment]
In ionic 2 and ionic 3, setting 

`<ion-content no-bounce>
</ion-content>`

Seems to solve the issue ..
