### ISSUE TITLE
Keyboard causes content to abruptly render which feels janky and shows white blocks

### ISSUE THREAD

**Issue by bliitzkrieg** [ionic-team/ionic#10218]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I click on an input, the keyboard comes up and the content jumps abruptly and white blocks appear (I assume it's the content rendering).

**Expected behavior:**
It should smoothly push the content up. I was looking at apps on the market place and in their demos the keyboard scrolls smoothly. Not sure what I am doing wrong.

**Steps to reproduce:**
1. Click on input

**Related code:**

```
<ion-content padding>
  <div class="landing-container">
    <h1>my app</h1>

    <ion-list>

      <ion-item>
        <ion-label floating>Email</ion-label>
        <ion-input></ion-input>
      </ion-item>

      <ion-item>
        <ion-label floating>Password</ion-label>
        <ion-input></ion-input>
      </ion-item>

    </ion-list>

    <ion-row responsive-sm>
      <ion-col>
        <button ion-button block round>Login</button>
      </ion-col>
      <ion-col>
        <button ion-button block round>Register</button>
      </ion-col>
    </ion-row>

  </div>
</ion-content>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.2.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Input scrolling is something we are hard at work on making more performant. Out of curiosity, what device are you seeing this issue on?

**Comment by bliitzkrieg** [comment]
Nexus 6P

**Comment by bliitzkrieg** [comment]
@jgw96 Do you know how to disable the content pushing. I've added the following:

app.component.ts
```
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import {StatusBar, Splashscreen, Keyboard} from 'ionic-native';

import {Home} from "../pages/home/home";

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage: any = Home;

  constructor(public platform: Platform) {
    this.initializeApp();
  }

  initializeApp(): void {
    this.platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
      Splashscreen.hide();
      Keyboard.disableScroll(true);
    });
  }
}
```

app.module.ts:
```
  imports: [
      IonicModule.forRoot(MyApp, {
      scrollAssist: false,
      autoFocusAssist: false
    })
  ],
```

and when an input comes up, it still pushed all my content. My desired behavior is to overlay the keyboard on my content.

**Comment by bliitzkrieg** [comment]
bump

**Comment by dPary** [comment]
the same question

**Comment by Tyler-Darby** [comment]
Has anyone had any luck with this? I am having the same bug. Here's a video of my scenario: [Video](https://i.gyazo.com/757e3134a2d6733985a1ff2db7dcd515.mp4)

**Comment by afgallo** [comment]
Got the same problem with recent update to 2.3.0. Is this a regression @jgw96? I don't recall having this problem with 2.0.

**Comment by Tyler-Darby** [comment]
For me, i've had the issue since the v2 betas. It's always been jumpy.
