### ISSUE TITLE
bug(slides): pager not set correctly after being hidden

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#10212]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**.
As per https://github.com/driftyco/ionic/issues/10176, even when calling the update method, the pager does not set itself correctly after being hidden on `ion-slides`. 

![pager](https://cloud.githubusercontent.com/assets/2852839/22380331/c62f79bc-e4c5-11e6-851b-8dada8ee0f09.gif)

**Expected behavior:**
Pager must be correctly set after the slide becomes visible. 

**Related code:**

```
<div [hidden]="loading">
   <ion-slides #slides pager>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will take a look at this.

**Comment by PoojithaThunuguntla** [comment]
is there any solution ??

**Comment by dylanvdmerwe** [comment]
This is still an issue. See attached repo.
[slidertest.zip](https://github.com/ionic-team/ionic/files/1144694/slidertest.zip)


![jul-13-2017 11-41-48](https://user-images.githubusercontent.com/2852839/28160398-5a4fad1a-67c0-11e7-8e92-8cfaa289ccb4.gif)


```
global packages:

    @ionic/cli-utils : 1.5.0
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 6.0.0
    npm        : 5.1.0
```

**Comment by Summerdx** [comment]
Same issue, for now I use *ngIf to fix it.
The only problem is when open the menu at first time, user will see a blank page for few seconds.


Here is my code

- **side-menu.html**
`
<ion-menu #sideMenu [content]="myContent" (ionOpen)="menuOpened()">
  <ion-slides #slides pager="true" *ngIf="menuHasOpened" (ionSlideDidChange)="slideChanged($event)">
....
  </ion-slides>
</ion-menu>
`

- **side-menu.component.ts**
`
  private menuHasOpened:boolean = false;
  @ViewChild('slides') public slides: Slides;
  @ViewChild('sideMenu') public sideMenu: Menu;
  ...

  menuOpened() {
    this.menuHasOpened = true;
    // ensure slides component has init
    if (this.slides) {
      // first time open
      if (typeof this.slides.clickedSlide ==='undefined' && this.slides.getActiveIndex() === 0) {   
        setTimeout(() => {
          this.slides.update();
        });
      }
    }
  }`
