### ISSUE TITLE
Enter key bypasses `lockSwipeToNext()`

### ISSUE THREAD

**Issue by dipolediamond** [ionic-team/ionic#10234]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The arrow key on the keyboard bypasses the `lockSwipeToNext()` method on the slide with an input.
Not only does it move to the next slide, the ActiveIndex is not updated to the newly displayed slide causing the slides to increase by 1 (the last slide is blank)
![screenshot_20170130-002814](https://cloud.githubusercontent.com/assets/2545819/22409058/5418d3ee-e684-11e6-907b-80178eaf4c88.png)

**Expected behavior:**
The arrow key should not be able to move to the next slide.

**Steps to reproduce:**
Create a slide with two or more slides having ion-input (forms)
In the component containing the slides, lockSwipeToNext()
fill last field in form on first slide and use arrow key to move to the next slide 

**Related code:**

```
ionViewDidLoad() {
    this.slider.lockSwipeToNext(true);
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v6.2.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us! We will take a look into this.

**Comment by miguelmchavez** [comment]
I'm experiencing this issue too. Any news?
