### ISSUE TITLE
ScrollToBottom on Android scrolls too much

### ISSUE THREAD

**Issue by capewaterAP** [ionic-team/ionic#10249]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Editing a field on Android opens the virtual keybord and the screen is pushed up (to have the edit field just at the top of it).
If while editing I enable another portion of the view (below the edit field) and then call ScrollToBottom(), the view moves up too much, hiding the edit field and the newly enabled portion.

I have to manually scroll up to see again my view.

This behavior seems not to appear on iOs.

**Expected behavior:**

-

**Steps to reproduce:**

To replicate the problem, I created a brand new app (ionic start newApp --v2) and added android platform to it (cordova platform add android).

**Related code:**

I modified the home.html as follows:

```
<ion-header>
  <ion-navbar>
    <ion-title>Home</ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <h2>Welcome to Ionic!</h2>
  <p>
    This starter project comes with simple tabs-based layout for apps
    that are going to primarily use a Tabbed UI.
  </p>
  <p>
    Take a look at the <code>src/pages/</code> directory to add or change tabs,
    update any existing page or create new pages.
  </p>
  <p>
    Need a longer text to test scrolling.....
    Take a look at the <code>src/pages/</code> directory to add or change tabs,
    update any existing page or create new pages.
  </p>
  <ion-item>
    <ion-label>Code:</ion-label>
    <ion-input [(ngModel)]="code"  (input)="codeEdited()"></ion-input>
  </ion-item>
	<ion-card *ngIf="codeOk">
		<ion-card-content>
      <p>
        This starter project comes with simple tabs-based layout for apps
        that are going to primarily use a Tabbed UI.
      </p>
      <p>
        Take a look at the <code>src/pages/</code> directory to add or change tabs,
        update any existing page or create new pages.
      </p>
		</ion-card-content>
	</ion-card>
  <div *ngIf="codeOk">
  <span  item-left>
    <button ion-button color="primary" outline round >Code Ok</button>
  </span>
  <span item-right>
    <button ion-button color="primary" outline round>Code KO</button>
  </span>
  </div>

</ion-content>

```
And the home.ts as follows:

```
import { Component, ViewChild } from '@angular/core';

import { NavController } from 'ionic-angular';
import { Content } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
	@ViewChild(Content) content: Content;

  code: string = '';
  codeOk: boolean = false;
  0
  constructor(public navCtrl: NavController) {

  }

  codeEdited() {
    if (this.code.length >= 6) {
      this.codeOk = true;
      let localThis = this;
      setTimeout(function() {
        localThis.content.scrollToBottom();
      }, 200);
    }
    else
     this.codeOk = false;
  }
}

```

**Other information:**

I run the app on a Nexus 5 (ionic run android --prod)
For the test, try to edit the "Code" field: at the sixth character the code is checked and the page scrolls down.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.4
Xcode version: Not installed

```

**Comment by jgw96** [comment]
Thanks for opening an issue with us! I will take a look!

**Comment by capewaterGU** [comment]
Hi Justin,

Have you had the time to verify the bug?

Thanks.
