### ISSUE TITLE
IOS setFocus on input make screen jump

### ISSUE THREAD

**Issue by llorenspujol** [ionic-team/ionic#10257]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have multiple inputs in a page, and I focus them manually every time using the setFocus() method. The problem is that when i do so, the page makes the correct scroll but when this scroll is finished it return to de no scroll position, is like something is cancelling the scroll. I have read a lot of issues of IOS keyboard and i still couldn't find exactly what the problem is.

In this gif is shown the current behaviour.
https://i.gyazo.com/53f5d32e166e3ef9929402bb6e9dc822.gif

**Expected behavior:**

Of course the current behaivour would be that when focusing the scroll stays stable.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will take a look into this.

**Comment by ricardojbertolin** [comment]
+1

**Comment by zucchinidev** [comment]
+1

**Comment by larssn** [comment]
In your module, try adding the options:
`IonicModule.forRoot(MyApp, { scrollAssist: false, autoFocusAssist: false }),` to your forRoot.

**Comment by llorenspujol** [comment]
Thank you @larssn , but I tried this and I got no result, in fact nothing changed. I've to notice that I have installed the ionic-keyboard-plugin in my app, and maybe the keyboard plugin autoScroll is making conflict with ionic scrollAssist. This is because if I disable the autoscroll from the plugin like this: 

`cordova.plugins.Keyboard.disableScroll(true);` 

This strange jump disapears, but when focusing between fields the scroll is not moved anymore, and the last field gets hidden... so with this I can solve one problem but I get another... I think that the problem is the conflict between the autoScroll from ionic and the autoScroll from the keyboard plugin, but really not sure at all.

**Comment by michaelyuen** [comment]
Off the top of my head, Ionic adds 300px of bottom padding to accommodate the keyboard. Looking at your gif, a guess is that the 'jump' is caused by this. You could probably debug and watch the DOM to see if that's it. Do you have styling to override this? If not, maybe try?

Curiously, I'm not sure why the 'disableScroll' method would have any affect on the 'jump'. From my understanding, what this does shouldn't have anything to do with the input autoscroll.

**Comment by krvajalmiguelangel** [comment]
Having the same issue

**Comment by skyserpent** [comment]
my iOS preview doesn't jump on inputs, but Android jumps on all inputs 😞

**Comment by nacimux** [comment]
Did you find any solution ?

**Comment by bogomips** [comment]
I am experiencing the same behaviour with an ion-textarea inside a modal.
At the beginning it is fullscreen, on desktop (with emulation on) it works well, on android (browser, it's a pwa) when i put the focus on the ion-textarea there is an extra padding between the keyboard and the bottom of the text-area

**Comment by mino922** [comment]
Does anyone have a solution to this problem I am seeing this on iOS?

Here is the output of Ionic Info:
`    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.3.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node  : v6.11.2
    npm   : 2.15.12
    OS    : macOS High Sierra
    Xcode : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy`

**Comment by xuanranGit** [comment]
Pleace conside set style for input like this:
  .input-cover{
    position:static;
  }

**Comment by AlokGupta007** [comment]
I am still facing the same issue. Please help to resolve, I have tried all above option.
