### ISSUE TITLE
ion-icon text-outline not showing in android in chrome

### ISSUE THREAD

**Issue by cozzbie** [ionic-team/ionic#10251]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ion-icon text-outline doesn't display on android emulators in Chrome dev but it displays for iOS

**Expected behavior:**
ion-icon text-outline should display for both.

**Steps to reproduce:**
Test on both android and ios emulations in Chrome. <ion-icon name="text"></ion-icon>

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will take a look at this.
