### ISSUE TITLE
ion-navbar back button unloads extra pages

### ISSUE THREAD

**Issue by manishoswal** [ionic-team/ionic#10252]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.1.0**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If i have 3 screens with nav bar and action buttons on top left corner.
Screen 1 - Nav bar has open screen 4  button
Screen 2 - Nav bar Back Button 
Screen 3 - Nav bar Back button 

If we tap the back button area of nav bar quickly on screen 3, 2 and 1. It unloads screen 3,2 and 1.
**Expected behavior:**

If we tap the back button area of nav bar quickly on screen 3, 2 and 1. It should unload screen 3 and 2. and load screen 4 

**Steps to reproduce:**

It works fine on android and chrome but not on iOS (checked on version 10). 

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Unfortunately I cannot reproduce this issue, could you provide a repo or plunker I can use to reproduce this issue?

**Comment by manishoswal** [comment]
@jgw96 - I have uploaded the code with node modules @ https://drive.google.com/open?id=0B382r1nAg1rCZGtJWk0xLTBaSGM

**Comment by manishoswal** [comment]
@jgw96  - I am still facing this issue.
