### ISSUE TITLE
Virtual scroll performance issue on nested object

### ISSUE THREAD

**Issue by FrancescoMussi** [ionic-team/ionic#10269]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

My list is a nested object. 
First loop: group of groups
Second loop: users of group

I need virtualScroll because there may be many many users.

But it doesn't work properly. There are inconsistent white spaces between users as in this screenshot:

![screen shot 2017-02-01 at 11 27 07](https://cloud.githubusercontent.com/assets/5312907/22503304/69db1748-e871-11e6-9d42-5f51989c6eae.png)

**Expected behavior:**

Could be nice to use virtualScroll inside another loop.

**Steps to reproduce:**

Here is a plunker where I recreated the situation (in the home-page component):

http://plnkr.co/edit/QDxECxMD2Kdk8jKdaiFe?p=preview

Scrolling up and down makes visible that performance issue

**Ionic info:** 

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0-rc.6
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by justas-kuizinas** [comment]
At the moment there are a lot of problems with virtual scroll, maybe anyone can suggest alternative?

**Comment by FrancescoMussi** [comment]
Guys do we have some news about this issue?

**Comment by JustasKuizinas** [comment]
@FrancescoMussi  at the moment it's totally broken :) though I see some issues being resolved in the milestones

**Comment by FrancescoMussi** [comment]
Ok thanks. Just wondering if it is on their tasks list or has been forgotten.
