### ISSUE TITLE
Visual error ion-item with ion-input

### ISSUE THREAD

**Issue by Langstra** [ionic-team/ionic#10274]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
![Screenshot of the bug](http://pix.toile-libre.org/upload/original/1485961050.jpg)

**Expected behavior:**
![Screenshot of how it should be](http://pix.toile-libre.org/upload/original/1485961135.jpg)

**Steps to reproduce:**
http://plnkr.co/edit/XCGzIp7aDfuWKC2QEBkl?p=preview

**Related code:**

**Other information:**
When inserting 
`
<ion-item></ion-item>
`
after the last item the visual bug does not appear anymore. So it seems to be a bug on the last item of a list.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.3.0
Xcode version: Not installed

**Comment by jgw96** [comment]
Thanks, we will look into this.

**Comment by fabiodomingues** [comment]
Is there a solution? Or solution forecast?

**# ionic info**

global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
