### ISSUE TITLE
Gesture events not working.

### ISSUE THREAD

**Issue by sebwal** [ionic-team/ionic#10285]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Gesture events mentioned in the docu (https://ionicframework.com/docs/v2/components/#gestures) do not work for me. Rotate and pinch events don't seem to get triggered. Tap, press, swipe and pan work fine. This problem occurs on Android and Web, other platforms not tested. I'd expect this simple example to work - is it not supposed to?

**Related code:**

***html***
```
<ion-content padding
    (tap)="tapHandler($event)"
    (press)="pressHandler($event)"
    (swipe)="swipeHandler($event)"
    (rotate)="rotateHandler($event)"
    (pinch)="pinchHandler($event)">
</ion-content>
```
***controller***
```
    tapHandler(args) {
        alert('tap');
    }
    pressHandler(args) {
        alert('press');
    }
    swipeHandler(args) {
        alert('swipe');
    }
    rotateHandler(args) {
        alert('rotate');
    }
    pinchHandler(args) {
        alert('pinch');
    }
```

**Comment by flolovebit** [comment]
gesture event "pinch"  do not work also using import { Gesture } ....

**Comment by sebwal** [comment]
Ok, same for the rotate event I assume? Maybe this should be mentioned in the docu, the way it is listed right now seems misleading to me.

**Comment by iron9light** [comment]
I use `Gesture` directly and got pinch event.
But most event triggered at the wrong time.
Some events delay and then all delayed event will trigger when next touch.

**Comment by JasonZzs** [comment]
@iron9light I met the same question these daya,  did u have any solutions?

**Comment by JasonZzs** [comment]
@iron9light  @iron9light  Hey, I met the same question these days, did u have any solutions?

**Comment by iron9light** [comment]
@JasonZzs No. I just gave up

**Comment by JasonZzs** [comment]
@iron9light  ok....it's really a pitty;
