### ISSUE TITLE
Swapping between tabs on Ionic 2 for iOS has flickering white screen

### ISSUE THREAD

**Issue by adamhughes86** [ionic-team/ionic#10288]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When swapping between ion tabs on ios device there is a brief moment of oblivion

**Expected behavior:**
Instant swapping of screens. No white flicker

**Steps to reproduce:**
- Download the ionic 2 tabs starter template
- Copy home content into about or contact template
- Run on ios device or emulator (does not happen on browser)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: 5.0.4 
OS: OS X El Capitan
Node Version: v6.9.4
Xcode version: Xcode 7.3.1 Build version 7D1014
```

I'm think this issue has been raised multiple times in the past but can't see any resolution on those posts other than updating Ionic. Now we're on 2.0.0 production I hoped this would have fixed it.

**Comment by JustinPierce** [comment]
@adamhughes86 On a whim, I gave the WKWebView plugin another shot just now, and our app was able to launch (first time this has worked for me!). When running on WKWebView, I no longer see the flashing between tabs. You may want to give that a shot. https://github.com/driftyco/cordova-plugin-wkwebview-engine

For @jgw96, this issue may only apply to UIWebView.

**Comment by adamhughes86** [comment]
@JustinPierce Not sure if I've installed that plugin right but it doesn't seem to be making a difference for me :(

**Comment by metz0r** [comment]
+1 for WKWebView
