### ISSUE TITLE
AlertCtrl handler does not receive input data in the handler params

### ISSUE THREAD

**Issue by christofferjjohansen** [ionic-team/ionic#10293]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Setup AlertController as per the documentation. On button click, the handler is not passed a parameter of the inputs, in this case ```data.username``` && ```data.password```, rather you receive an empty string, instead of the defined input params in the alertCtrl.

**Expected behavior:**
Should pass the input data to the handler, to perform action.

**Steps to reproduce:**
Use template from documentation for quick repro.

```presentPrompt() {
  let alert = this.alertCtrl.create({
    title: 'Login',
    inputs: [
      {
        name: 'username',
        placeholder: 'Username'
      },
      {
        name: 'password',
        placeholder: 'Password',
        type: 'password'
      }
    ],
    buttons: [
      {
        text: 'Cancel',
        role: 'cancel',
        handler: data => {
          console.log('Cancel clicked');
        }
      },
      {
        text: 'Login',
        handler: data => {
          if (User.isValid(data.username, data.password)) {
            // logged in!
          } else {
            // invalid login
            return false;
          }
        }
      }
    ]
  });
  alert.present();
}

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will take a look into this!

**Comment by theunreal** [comment]
I am working with some inputs in alerts and it works fine for me..  what does console.log(data) shows?

**Comment by christoffer-Van** [comment]
blank string ```""```

**Comment by R-Jones** [comment]
Think I just stumbled on this one...
![ionicalertctrlissue](https://user-images.githubusercontent.com/7097781/33804273-7f575b26-dd45-11e7-92b5-a3c72675d3a2.PNG)

**Comment by petrot** [comment]
Same problem here. the handler data is empty on Android (it works on iOS and browser)

**Comment by cybertim** [comment]
After bashing my head on the table multiple times I happen to have this exact same bug.
```
local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2
```
It works fine on iOS (debug and release) and Android (debug). But when 'compiled' with '--release' it simply returns empty strings on alertController input's. You can imagine the amount of ??? when receiving Beta feedback for Android.
