### ISSUE TITLE
datetime picker is too close to the edge

### ISSUE THREAD

**Issue by NamelessChen** [ionic-team/ionic#10346]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
use datetime that  displayFormat="YYYY-MM-DD HH:mm"

**Expected behavior:**
the first column and the last cloumn don't  close to the edge

**Steps to reproduce:**

**Related code:**

```
  <ion-datetime (ionChange)="validateInpt()" class="text-left" cancelText="取消" doneText="确定" displayFormat="YYYY-MM-DD HH:mm" pickerFormat="YYYY-MM-DDTHH:mm" min="{{minDateTime}}" max="{{maxYear}}" yearValues="{{yearValues}}" minuteValues="0,5,10,15,20,25,30,35,40,45,50,55"
                                      [(ngModel)]="travel.departureOn"></ion-datetime>
```

**Other information:**
![1486450123 1](https://cloud.githubusercontent.com/assets/12457060/22720470/fa7a13ca-ede5-11e6-8649-cf25b3dd0974.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Thanks for using ionic, we will take a look into this.

**Comment by pinpointpanda** [comment]
@NamelessChen keep an eye on this issue too:
https://github.com/driftyco/ionic/issues/10140

Although I guess with Chinese date format "DDD" is not so useful? But reducing the picker columns to fewer than 5 should help solve this.
