### ISSUE TITLE
Ionic Tabs duplicate when reloading component

### ISSUE THREAD

**Issue by RobertBroersma** [ionic-team/ionic#10349]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In my page, in ionViewWillEnter, I create an array of objects with data and a reference to a component. Then I use this array in my template to construct ion-tabs with ngFor. This works fine.

When I navigate to a different page, then navigate back using navCtrl.pop(), The tabs seem to get duplicated. The first iteration of tabs doesn't work anymore, only the second, "new ones" do. It seems like the cached tabs don't get removed or something. However my array is correct. A new set of tabs appears everytime the component gets navigated to from navCtrl.pop(). 

This doesn't happen when navigating with navCtrl.setRoot()

**Expected behavior:**
No duplicate tabs.

**Related code:**

```
ionViewWillEnter() {
        let rawDayPlannings = [];
        Observable.forkJoin([
            this.planningService.getWeekPlannings(),
            this.planningService.getMealSettings()
        ])
        .map(res => {
            rawDayPlannings = res[0].results[0].dayplannings;
            res['weekPlanningId'] = res[0].results[0].id;
            res[0] = _(rawDayPlannings).groupBy(item => item.day_of_the_week)
            return res;
        })
        .subscribe(res => {
            let groups = res[0];
            for (let i = 0; i < 7; i++) {
                this.dayTabs[i] = {
                    component: PlanningTab,
                    title: this.daysOfTheWeek[i],
                    weekPlanningId: res['weekPlanningId'],
                    dayOfTheWeek: i,
                    allDayPlannings: rawDayPlannings,
                    allMealSettings: res[1],
                    dayPlannings: null
                }

                if (groups[i]) {
                    this.dayTabs[i].dayPlannings = groups[i];
                }
            }
        });
    }
```

```
<ion-content>
    <ion-tabs #tabRef tabsPlacement="top" preloadTabs="false">
        <ion-content>
            <ion-tab *ngFor="let tab of dayTabs" tabTitle="{{tab.title[0]}}" [root]="tab.component" [rootParams]="tab"></ion-tab>
        </ion-content>
    </ion-tabs>
</ion-content>
```

**Ionic info:**:

```
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

```

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this.

**Comment by RobertBroersma** [comment]
I also have this issue outisde of changing components. I since have a different component that fetches data and constructs tabs based on the data. Afterwards I call the function again to fetch new data, and the old tabs remain there.

**Comment by soundshed** [comment]
I have the same issue. I have an ngIf="isAdmin" which conditionally shows a tab (in this case if the user is admin). If I toggle between isAdmin=true and isAdmn=false over time I get additional copies of the tab.

**Comment by billygerhard** [comment]
I am using an observable to create tabs, and I ran into this issue too when the observable is updated it doubles up my tabs as well. This item has been open for a while now, is there any update on this?

**Comment by simonmartinez** [comment]
Same problem with the *ngIf

**Comment by haifzhan** [comment]
Same issue here,  any update?
