### ISSUE TITLE
Ionic 2 infinite scrolling gets stuck

### ISSUE THREAD

**Issue by Isigiel** [ionic-team/ionic#10345]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

In my newsfeed, when I reach the end of the displayed items I'm using ionic infinite scroll to load more. Now when I reach it it keeps loading more posts and apparently jumps doen when new ones are loaded.

**Expected behavior:**

New posts would be added to the document without me jumping down and triggering the infinite scrolling again.

**Steps to reproduce:**

Sadly I can not reproduce this behaviour on plunker. The best I can do is this video of it happening.
https://1drv.ms/v/s!ApVFL9Vn_38dgu9PLyUGVWDUtw9HVA

**Related code:**
This is the page I experience the weird behaviour on
https://gitlab.com/pikandpeople/mobile-next/blob/master/src/pages/news/news.html

**Other information:**

Happens on the pc and phone, I'd say not since long.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
$ ionic info

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.4.0
Xcode version: Not installed
```

**Comment by Daskus1** [comment]
I have the exact opposite. In my case infinitescroll does not load anything at all. #9596

**Comment by jgw96** [comment]
Thanks for using ionic, we will take a look into this.

**Comment by jgw96** [comment]
Hello @Isigiel . What browser or device are you seeing this issue on?

**Comment by Daskus1** [comment]
@jgw96 could you please also have a look at #9596?

**Comment by Isigiel** [comment]
Hey @jgw96, thanks for looking into this.
I experience this issue on chrome with serve as well as on a One plus 2 in a builded version

**Comment by jodybrewster** [comment]
I can recreate this issue on any ion-content view on iOS 10 in platform browser or ios.  What you can do is once you have enough content to scroll vertically, you can scroll the content to the bottom of the view, tap once on the bottom of the screen, then start scrolling like crazy. It immediately goes into an unresponsive frozen like state but you can see the scrollbar moving with your finger.  Just that the content doesn't move.  This is a little hard to reproduce and its gotten better with releases.  But its still there.

**Comment by numerized** [comment]
Hi there, 
I experiment the same type of behaviour while loading data from Firebase.

**Comment by vzharkov** [comment]
I have the same issue on iOS10 with WKWebView. Infinite-scroll stuck when it at the end of list.
There is a demo video of this bug on the real device: https://drive.google.com/open?id=0B_zETA6tw6i1YUxyR0lIQlNsRjg

I think this problem is related with the some scroll activation or animation. May be it related with the following PR: https://github.com/driftyco/ionic/pull/8099

Some additional info:
```
$ ionic info

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.7.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by craftpip** [comment]
In my case, initially ion-list has 10 items, 
i scroll down, ion-infinite-scroll is triggered and +10 items are added,
The next time i scroll down, it shows the loading icon, but onInfinite is not trigged. it gets stuck here.

any ideas ?
