### ISSUE TITLE
gulp lint.sass fails with `Fatal undefined` if Ruby/scss-lint is not installed

### ISSUE THREAD

**Issue by huerlisi** [ionic-team/ionic#10358]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
When running `gulp lint.sass` without having Ruby and the `sass-lint` gem installed, I get a `Fatal undefined`.

The issue is that the `scsslint.failReporter` in `scripts/gulp/tasks/lint.ts` cannot handle the error message produced by `scsslint()`. When dropping the piping into the failReporter, I get the following error:

```
Message:
    You need to have Ruby and scss-lint gem installed
```

**Expected behavior:**
Possible ways to of "nice" behavior, in descending preference:
* No dependency on Ruby, but using https://www.npmjs.com/package/sass-lint or https://www.npmjs.com/package/stylelint
* Fixing upstream so the error about missing Ruby is properly propagated by `failReporter`
* Hacking the `lint.ts` gulp task to properly show the error
* Document the need to install Ruby/scss-lint gem in the README

**Comment by jgw96** [comment]
Thanks for using ionic, we will look into this.

**Comment by brandyscarney** [comment]
We do currently have it documented that you need Ruby for the Sass linter here: https://github.com/driftyco/ionic/tree/master/scripts#running-sass-linter

I've tried using the alternative Sass linters but the last time I tried them out the errors weren't as nice and the configuration didn't allow us to check for everything we wanted to.

Which task were you running? Maybe we can add a nice error message. 🙂

**Comment by huerlisi** [comment]
@brandyscarney Ha! of course I missed that documentation:-) Thanks for the pointer.

I was playing around with bumping the Angular version (related to https://github.com/driftyco/ionic-app-scripts/issues/197). So I run the `gulp validate` task (and others) to check what would fail when bumping (it's 70 tests btw:-)

The main issue seems that while the error outputed by piping into `scsslint()` is nice and dandy, the piping into `scsslint.failReporter` creates the generic `Fatal Error`.

So moving something between them handling (and simply showing) this specific error should help.

**Comment by peterkelly** [comment]
The "Fatal undefined" error message was appearing instead of "You need to have Ruby and scss-lint gem installed" due to a bug in error handling within gulp-scss-lint; see https://github.com/juanfran/gulp-scss-lint/issues/75

I have submitted a pull request to gulp-scss-lint (https://github.com/juanfran/gulp-scss-lint/pull/81) which fixes the bug - it was just a case of an incorrectly-named variable. Once a new release of gulp-scss-lint is made that includes the fix, and Ionic's dependencies are updated appropriately, this issue can be closed.

Full repro steps (to see the "Fatal undefined") message:

```
$ docker run --rm -it node:8.1.2 bash
npm install -g gulp@3.9.1
echo -e "\nHost github.com\nStrictHostKeyChecking no\n" >> /etc/ssh/ssh_config
git clone https://github.com/ionic-team/ionic.git
cd ionic
npm install
gulp lint.sass
```

which produces the following output:

```
root@e709600faf15:/ionic# gulp lint.sass
[11:35:59] Using gulpfile /ionic/gulpfile.js
[11:35:59] Starting 'lint.sass'...
Fatal undefined
```
