### ISSUE TITLE
Refreshing a page with a modal open overrides Deeplinker

### ISSUE THREAD

**Issue by highfieldjames** [ionic-team/ionic#10353]
**Ionic version:**
[ x ] **2.x**

**I'm submitting a ...**
[ x ] bug report

**Current behavior:**
When opening a modal, the Deeplinker behaviour is overridden to be {{hostname}}:{{port}}/#/. Therefore, when the user refreshes the page, they are taken to the root page.

**Expected behavior:**
The page should refresh with the current activate page.

**Steps to reproduce:**
1. Add deeplinking: [https://ionicframework.com/docs/v2/api/navigation/DeepLinker/]
2. Open a modal from a deep-linked page with:
`this.modalCtrl.create(YourPageComponent);`
3. Refresh the page

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Thanks for using ionic, we will look into this.

**Comment by BatMen** [comment]
My deeplink segment with a modal does not work at all (showing #/). Worked only with regular push.
