### ISSUE TITLE
Android statusbar and navbar remain visible after the keyboard is gone in fullscreen app

### ISSUE THREAD

**Issue by bmagni** [ionic-team/ionic#10366]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have an app with Fullscreen=true. On android, when the keyboard open when editing text on any type of inputs (ion-input, ion-searchbar, ion-textarea, ...) statusbar and navbar are showing up. The problem is that when the keyboard disappears, statusbar and navbar don't. They're hiding top and bottom parts of the app.

**Expected behavior:**
I expect statusbar and navabr to hide with the keyboard when leaving inputs.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.0.0
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Could you post a screenshot of the behavior your seeing?

**Comment by bmagni** [comment]
Hi ! Thanks for your time ! 
I can't take a screenshot because the app comes back to fullscreen as soon as I open anything else on the phone. So I took a picture of the phone instead... sorry about that ! But you can see the tabs hidden by the navbar on it. 
I suppose I'm doing something wrong but I really can't put my finger on it... I hope you will ! 

![20170209_163551](https://cloud.githubusercontent.com/assets/22218143/22790555/dbd1fb8e-eee6-11e6-81a0-72026f207d3f.jpg)

**Comment by jbarbede** [comment]
I actually have the same problem on Android with fullscreen.

I made some video so you can see clearly what's happening: https://youtu.be/UQoiTtyAQLQ
