### ISSUE TITLE
ion-refresher - never inactive when released

### ISSUE THREAD

**Issue by alexbainbridge** [ionic-team/ionic#10376]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[* ] **2.x**

**I'm submitting a ...**  (check one with "x")
[* ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you pull down an ion-refresher a little bit (so that it doesn't trigger). If you release, it never goes back to state inactive (or it may, but an event with that state is not fired)

**Expected behavior:**
I expect letting go of the refresher would return to state inactive, progress 0

**Steps to reproduce:**
http://plnkr.co/edit/4tKUuDk0bYS3XCSgBw3k?p=preview
See Plunker

a) Pull a few pixels down then let go
b) Oddly you can see that console.log(event) shows that the state is inactive - but event.state stays as pulling for the output from console.log(event.state); 

**Other information:**
Version as per Plunker above (final 2.0)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We will take a look into this (:

**Comment by alexbainbridge** [comment]
Thanks Justin @jgw96 

Frankly I am a bit mystified why console log of the whole object has one value, while console.log of a specific value is the previous value.  Although there is a message (on Chrome console) saying whole object recently updated...... that is from Google, not you or my code. 

I think you can see that in the Plunker too..... 

Was trying to create a workaround for https://github.com/driftyco/ionic/issues/7507 (which I think has come back as an issue) and found this one ;)

**Comment by alexbainbridge** [comment]
This is definitely an issue, but I have avoided it, so please consider it low priority until someone else has it!
