### ISSUE TITLE
Customized components in <ion-navbar> don't display properly

### ISSUE THREAD

**Issue by xiehaom7** [ionic-team/ionic#10379]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you have a customized component and place it within the ion-navbar, the elements in your components seems cannot get the proper class to style. Like this:
![screen shot 2017-02-09 at 4 47 25 pm](https://cloud.githubusercontent.com/assets/9370981/22806412/90945dbe-eee7-11e6-9f54-44654714820d.png)

**Expected behavior:**
The elements in the customized component should be styled as if the customized component doesn't exist.

**Steps to reproduce:**
1. Create the component containing an icon button
2. Add an ion-buttons into the page's ion-navbar
3. Add the component into the ion-buttons
4. shown on iOS

**Related code:**
home.html
```
<ion-header>
  <ion-navbar>
    <ion-title>
      Ionic Blank
    </ion-title>
    <ion-buttons end>
      <my-header></my-header>
    </ion-buttons>
  </ion-navbar>
</ion-header>

<ion-content padding>
  The world is your oyster.
  <p>
    If you get lost, the <a href="http://ionicframework.com/docs/v2">docs</a> will be your guide.
  </p>
</ion-content>
```
The component created 
```
import { Component } from '@angular/core';

@Component({
  selector: 'my-header',
  template: `
    <button ion-button icon-only clear
      (click)="onClicked()">
      <ion-icon
        name="information-circle">
      </ion-icon>
    </button>`
})
export class MyHeaderComponent {
  constructor() {}
  onClicked() {
    console.log("clicked");
  }
}
```
**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by karlpatrickespiritu** [comment]
I'm also having this problem on Lists. When adding Item in another custom component, some styles won't work unlike having them in one component.
