### ISSUE TITLE
ion-refresher flash on pull

### ISSUE THREAD

**Issue by alexbainbridge** [ionic-team/ionic#10377]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ *] **2.x**

**I'm submitting a ...**  (check one with "x")
[ *] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you pull a few pixels on a refresher, I am finding the whole screen is flashing. Literally a couple of pixels down, very very slowly. If you pull fast, you get over this bump with no flash, so it does not happen all the time as most users pull faster. 

Happens on device (IOS), not android, not browser / ionic serve.
Happens Ionic View and directly on device.

**Expected behavior:**
No Flash

**Steps to reproduce:**
Slightly struggling with creating something that can be simply reproduced (although I can reproduce on ipad and iphone). 

Probably I will need to create an app you can put to device, to see this yourself. 

**Other information:**
I have a feeling its 
https://github.com/driftyco/ionic/issues/7507
that has come back.

My current research has excluded anything I am doing (to the extent I can) 

I appreciate this issue is light on information.

Its really a holding issue remarking that it was seen (and addressed) in 7507 but refactoring / new adjustments has brought it back. (or its something new, that sounds the same)

**Was really hoping you could remember what fixed 7507 and see if somehow that was taken out in the last 6 months.** 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2 Build version 8C38

**Comment by graphefruit** [comment]
Maybe provide a short video which demonstrates it for further understanding

**Comment by alexbainbridge** [comment]
OK so I have half addressed this by adding the following CSS

```
ion-refresher {
  -webkit-transform: translate3d(0,0,0); 
  -webkit-backface-visibility: hidden;

  // For some unknown reason, benefits from having a background colour specifically set
  &.refresher-active {
    background-color: transparent;
  }

}
```
Not perfect, not even really OK, but certainly better (i.e. flickers less often)

Also, with overflow:hidden on div.scroll-content never get a flicker..... but, er, can't scroll either!

Think we are up against performance optimisation challenges here rather than something specifically "wrong" somewhere. As such, may be a hard one to resolve.
