### ISSUE TITLE
bug: ItemReorder+ItemSliding with Ckeckbox not working

### ISSUE THREAD

**Issue by tzimpel** [ionic-team/ionic#10400]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>When an ion-list is set to reorder="true" with ion-item-sliding, the reorder function does not work on iOS. In the browser with ionic serve, as well as on Android, everything is working fine.

Code to reproduce:

```
<ion-list no-lines reorder="true" (ionItemReorder)="reorder($event)">
    <ion-item-sliding *ngFor="let item of items">
      <ion-item>
        <ion-label>
            {{item.title}}
        </ion-label>
        <ion-checkbox [(ngModel)]="item.checked"></ion-checkbox>
      </ion-item>
      <ion-item-options side="right">
        <button ion-button icon-only (click)="editItem(item)">
          <ion-icon name="settings"></ion-icon>
        </button>
        <button ion-button icon-only color="danger" (click)="deleteItem(item)">
          <ion-icon name="trash"></ion-icon>
        </button>
      </ion-item-options>
    </ion-item-sliding>
  </ion-list>
```

When `<ion-checkbox [(ngModel)]="item.checked"></ion-checkbox>` is commented out, the reorder works on iOS.
When the sliding items are changed to normal items (ion-item-sliding tags as well as ion-item-options block commented out), the reorder also works on iOS.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We will take a look into this.

**Comment by Dennis-Do** [comment]
Same problem here. Any progress on that?

**Comment by ErikAugust** [comment]
Any updates on this? Thanks!

**Comment by kensodemann** [comment]
See this comment https://github.com/ionic-team/ionic/issues/12760#issuecomment-325470731 for another permutation of this.
