### ISSUE TITLE
Scrollbars shown in alerts even when not necessary

### ISSUE THREAD

**Issue by cfjedimaster** [ionic-team/ionic#10402]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Testing in desktop (the docs), I'm seeing scroll bars in the alert UI when it's not necessary:

![image](https://cloud.githubusercontent.com/assets/393660/22854618/1f7fb658-f038-11e6-90c6-0372f8392261.png)

**Expected behavior:**

I would expect the scroll bars to only show up when necessary. I used DevTools to remove most of the text, curious to see if maybe it was just a bit too much, but it didn't remove the scrollbars.

**Steps to reproduce:**

View the docs/demo in Chrome.

**Comment by cfjedimaster** [comment]
I'm seeing it elsewhere as too. To be clear, this is all in the desktop, not the mobile emulator/device, but it seems new.

![image](https://cloud.githubusercontent.com/assets/393660/22854646/db386ca0-f038-11e6-82f9-0c95fe108936.png)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This is on a windows 10 machine im guessing? Do you see the same behavior in edge?

**Comment by cfjedimaster** [comment]
Wow, actually it is worse in Edge:

![image](https://cloud.githubusercontent.com/assets/393660/22890608/7d44974a-f1d2-11e6-9eca-1a17b0497a9d.png)
