### ISSUE TITLE
Nested ionic sliders triggering events from the background slider in browsers

### ISSUE THREAD

**Issue by vajura** [ionic-team/ionic#10418]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you have a site with a ionic slider component and push a site with another ionic slider it causes buggy behaviour and you cant control the new slider page, it also causes events (ionSlideNextStart etc) to trigger on the previous slider even though its not on screen.

**Expected behavior:**
When the new slider page is opened it should be controllable.

**Steps to reproduce:**
Create a page with a ionic slider component, with a "(click)" function this.nav.push another ionic page with another slider component.

This bug only occurs in browsers (chrome etc)

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will take a look into this issue.
