### ISSUE TITLE
ItemSliding event doesn't update associated values

### ISSUE THREAD

**Issue by nonamez** [ionic-team/ionic#10423]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
[As described in API](https://ionicframework.com/docs/v2/api/components/item/ItemSliding/) `ItemSliding` has event `ionDrag` which is fired when swipe happens. The problem is that when I do object update inside the function which is bind to `ionDrag` object doesn't  update its value in to the view. Only if you swipe until the `percent >= 1`. If `percent <= 1` so the title doesn't change.

**Expected behavior:**
When `ionDrag` event fired is should update object and title should change in the HTML.
 
**Steps to reproduce:**
Slowly drag slider a little further than the second button.

http://plnkr.co/edit/1ZNdW0XjyUrRj2zjMfaE?p=preview

https://youtu.be/6punxSL7UnM
**Related code:**

```
<ion-item-sliding *ngFor="let activity of activities" (ionDrag)="itemDragged($event, activity)">
	<ion-item>
		<h2>{{ activity.status }}</h2>
	</ion-item>
	<ion-item-options side="right">
		<button ion-button color="light" icon-left>
			<ion-icon name="ios-more"></ion-icon>
			More
		</button>
		<button ion-button color="primary" icon-left>
			<ion-icon name="text"></ion-icon>
			Note
		</button>
	</ion-item-options>
</ion-item-sliding>
```

```
itemDragged(event, index) {
	let percent = event.getSlidingPercent()

	if (percent > 0.5) {
		this.activities[index].status = 'open'
	} else {
		this.activities[index].status = 'close'
	}
	
	console.log(percent, this.activities[index].status)
}
```
Also tried to pass `activity` directly instead of index.

**Ionic info:**

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v7.5.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I will take a look into this.

**Comment by mfdeveloper** [comment]
Hello @nonamez ! I've got the same problem on latest `3.x` ionic version. This happens because the **Change Detection** strategy is `PUSH` for this component. So, I suggest the "workaround" below:

```ts
...

// Injects the changeDetectionRef service into your component
constructor(protected changeDetectorRef: ChangeDetectionRef){}

itemDragged(event, index) {
	let percent = event.getSlidingPercent()

	if (percent > 0.5) {
		this.activities[index].status = 'open';
                this.changeDetectorRef.detectChanges();
	} else {
		this.activities[index].status = 'close';
                this.changeDetectorRef.detectChanges();
	}
	
	console.log(percent, this.activities[index].status)
}
```
However, sometimes the "close" action of a swiped item, not trigger this event. For fix this, I've created the PR: [!13605](https://github.com/ionic-team/ionic/pull/13605). Sadly, I think that won't be merged until the **4.x** ionic version is released. So, whether you need this changes by now, get this from my forked repo :)
