### ISSUE TITLE
ion-select sets its bound model to an empty object when there are no ion-options

### ISSUE THREAD

**Issue by zakton5** [ionic-team/ionic#10435]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[] feature request
[ ] support request

**Current behavior:**
If I open a select with no ion-options and then click 'OK', the bound model's value becomes {}. 

**Expected behavior:**
I expect the bound model's value to become null or undefined.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this!
