### ISSUE TITLE
ion-select multiple won't update if ngModel is changed elsewhere

### ISSUE THREAD

**Issue by AleFons** [ionic-team/ionic#10448]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you change the contents of an ion-select multiple's ngModel to something that would still be considered valid, it does not update the ion-select; so if you have an array of numbers as the ngModel and you push a number into it outside of the page's constructor, the option equivalent to it will not be checked.

**Expected behavior:**
Changing the content of the ngModel, regardless of where, should update the ion-select, as happens when the multiple option is not used.

**Steps to reproduce:**
Create an ion-select multiple, use two-way data binding on the ngModel and push valid data onto the ngModel array; if done outside the constructor, the ion-select will not update, becoming inconsistent with the ngModel.

**Related code:**
I've set up a plunker example [here](http://plnkr.co/edit/1153zscVdr7ARmKZn9Jf?p=preview)

**Other information:**
The issue only happens with ion-select multiple; on ion-select, any changes to the ngModel are reflected correctly.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.3.1 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.4
Xcode version: Not installed

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this!

**Comment by joshterrill** [comment]
Any update on this one?

**Comment by AleFons** [comment]
I believe I've found a workaround of sorts, but I haven't actually tested it; I've run into a similar issue recently where a ion-button's wasn't updating basing on a change in the model. Basically:
`
    import { NgZone } from '@angular/core';

    zone : any = new NgZone({ enableLongStackTrace: false });

    this.zone.run(() => {
        //code that changes the ion-select's array
    });
'

I haven't actually tested this on this specific issue, but I'll get back to you when I have.

**Comment by AleFons** [comment]
Alas, it didn't work. I thought it involved the model being changed and no change detection running, but it seems like either that was not the case or I did it wrong. Guess we'll have to wait for an official fix.

**Comment by bhaveshvyas007** [comment]
any updates?
model change is not detected by ion-select.

**Comment by svojislav** [comment]
I think the problem is related with the thing that model isn't used for ion-select it is just updated when ion-select alert is closed. The problem is there even when one has initial values in a model. So it is obvious that ion-select do not use ngModel list. I would like to see a solution for this.

**Comment by joshterrill** [comment]
@svojislav I don't know if that's true. According to the documentation, `[(ngModel)]` can go in an `ion-select` component. 

Documentation link to `ion-select`: https://ionicframework.com/docs/components/#select

**Comment by MumblesNZ** [comment]
Any update on this? I think I have an issue which stems from the same bug where I'm filtering the ion-options using a pipe, and the option content doesn't update when the pipe is executed.

**Comment by eltonrodrigues-github** [comment]
@Vatsov  Thanks, work for me in ionic 4.

Any update on this one?
