### ISSUE TITLE
bug: Floating Labels and Numeric Inputs

### ISSUE THREAD

**Issue by jmcenteno** [ionic-team/ionic#10453]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Greetings!

There seems to be a problem combining a floating ion-label with a numeric ion-input. When starting with an empty value, the ion-label moves to the top when the ion-input is focused to allow room for a value to be entered, and stays on top when a valid numeric value is entered. That works as expected. However, when entering a value like 0-0-0, which is an invalid numeric value, the ion-label goes back to its original position and overlaps the value that was entered.

Here's a sample template to reproduce the issue:

```html
<ion-list>
	<ion-item>
		<ion-label floating>Label</ion-label>
		<ion-input type="number" inputmode="numeric" pattern="[0-9]*"></ion-input>
	</ion-item>
</ion-list>
```

By the way, thank you for all of your hard work in creating such a wonderful framework!</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Thanks for bringing this issue up, we will look into this!

**Comment by vintage** [comment]
I've been able to reproduce the issue using Ionic `3.1.1`. When invalid value is provided into number input the floating labels overlaps the text.

**Comment by euljr** [comment]
I'm also having this issue with Ionic 3.5.2

**Comment by cabralRodrigo** [comment]
I'm also having this issue with Ionic 3.7.1
