### ISSUE TITLE
ion-tabs create anchor elements, which trigger blank 3d touches

### ISSUE THREAD

**Issue by dalemugford** [ionic-team/ionic#10462]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Because `ion-tab` outputs anchor tags, 3D Touch can be performed on the the tab buttons, triggers a white preview overlay like any other link in a safari web view. There is no safari api or method to disable this behaviour.

**Expected behavior:**
`ion-tab` elements would not be anchor tags, and thus would not trigger 3D Touch.

**Steps to reproduce:**
Create a tabs template, and press any tab using an iPhone 6s or later.

**Comment by khalidawwad** [comment]
+1

**Comment by mhartington** [comment]
merging with #11896
