### ISSUE TITLE
this.nav.canGoBack() gives wrong result

### ISSUE THREAD

**Issue by tmvnk** [ionic-team/ionic#10464]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.01**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
this.nav.canGoBack() result is TRUE when open a Tab, perform NavPush, and return to previous (Tab)Page.

**Expected behavior:**
this.nav.canGoBack() result needs to be FALSE when open a Tab, perform NavPush, and return to previous (Tab)Page.

**Steps to reproduce:**
- Open a TabRoot / Tabpage
- Push to a new page. this.nav.push(ProfilePage, {profile}); Needs to be the same with different parameters.
- Return to the TabPage
- Detect in  ionViewWillEnter(){console.log(this.nav.canGoBack());}
- Result is true while you are now back on the TabRoot.

**Related code:**

```

//Open this page first as root/tab
tab3Root: any = ProfilePage;

//Open a new ProfilePage with different parameters
goToProfile(profile) {
  this.nav.push(ProfilePage, {profile});
}

//Return to the ProfilePage TabPage root

ionViewWillEnter(){
  console.log(this.nav.canGoBack());
  //result is true, needs to be false
}

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.6
OS: macOS Sierra
Node Version: v7.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this.

**Comment by jwjenkin** [comment]
Not sure if you are having these issues still, but we still are seeing this in our application. When console logging this.nav.length(), the output returns 2 even though you are on the tab root, which I'm guessing is why this.nav.canGoBack() keeps on returning true. Hopefully this helps narrow down the issue!

**Comment by iget-master** [comment]
@jwjenkin did you found the reason for this problem?

I'm having an issue where for some reason `canGoBack()` returns true when I directly type the url on the browser after the app is loaded:

- Load the application http://localhost:4200/home
- Change the url on browser to http://localhost:4200/login (the login page have an redirect "back" if canGoBack, or setRoot otherwise)

The following error appears:

```
core.es5.js:1020 ERROR Error: Uncaught (in promise): navigation stack needs at least one root page
    at c (polyfills.js:3)
    at Object.reject (polyfills.js:3)
    at NavControllerBase._fireError (nav-controller-base.js:223)
    at NavControllerBase._failed (nav-controller-base.js:216)
    at nav-controller-base.js:263
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.es5.js:3890)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
```

**Comment by Stromwerk** [comment]
I am having the same problem. After using setRoot to change the root page I still get 2 when running `this.navCtrl.length()`
