### ISSUE TITLE
[Bug] fullscreen + ion-refresher hides refresh

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#10490]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When having a `ion-content` with `fullscreen`, and an `ion-refresher` the refresher is hidden behind the header

**Expected behavior:**
The refresher must always appear just below the header

**Steps to reproduce:**
- Use this demo: https://github.com/driftyco/ionic/tree/dbfc183cac036099603f9e51611bfccbc900a08b/demos/src/refresher
- Add `fullscreen` to `ion-content`

**Related code:**

```
<ion-content fullscreen>
    <ion-refresher (ionRefresh)="refreshList($event)">
        <ion-refresher-content></ion-refresher-content>
    </ion-refresher>
</ion-content>
```

**Other information:**
Motivation:
Having a list you can pull down to refresh, or pull up and hides the header

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will look into this (:

**Comment by mhartington** [comment]
Hmm, I'm not able to replicate this locally. 
Are you seeing it specifically on a device or in the browser?

**Comment by AmitMY** [comment]
Both.
I used the header scroll example
Though even though I removed the scroll and was left with fullscreen the bug persisted.

**Comment by shawnlan** [comment]
Same issue. When pulling down, I can see the refresher, but during refreshing, it is hidden.

**Comment by airstep** [comment]
+1

**Comment by shawnlan** [comment]
I remembered I used transparent for the background color as a workaround.

**Comment by elmartino** [comment]
Same here.. have a background image in header, so transparent not working..

**Comment by dimitri320** [comment]
Same here, hides refresher in the browser and on the device.

**Comment by inikolin** [comment]
Did anyone find workaround for this issue?
