### ISSUE TITLE
Slides instance is undefined after ngAfterViewInit

### ISSUE THREAD

**Issue by sidlauskaslukas** [ionic-team/ionic#10501]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using this example below from your documention the Slides instance will always be undefined and you will be getting an error saying "Cannot set property 'freeMode' of undefined". 

https://ionicframework.com/docs/v2/api/components/slides/Slides/#advanced

Then in the source code (slides.js:777) I found that "Slides" initiliazation is wrapped in the setTimeout function:

```
Slides.prototype.ngAfterContentInit = function () {
       var _this = this;
       this._plt.timeout(function () {
           _this._initSlides();
       }, 300);
   };
```

So I think it's pretty clear now why the example in your documentation doesn't work as expected.

It starts to work only if you wrap your code in the setTimeout function as well:

```
setTimeout(() => {
    this.slides.freeMode = true;  
},1000);
```

But it's not acceptable either.

**Expected behavior:**

It should be possible to access the Slides instance methods and properties without using the setTimeout function.

**Steps to reproduce:**
Use the example in your documentation: https://ionicframework.com/docs/v2/api/components/slides/Slides/#advanced

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.8
OS: OS X El Capitan
Node Version: v7.4.0
Xcode version: Xcode 7.3 Build version 7D175
```

**Comment by jgw96** [comment]
Thanks, we will look into this.

**Comment by aslaugsollilja** [comment]
any update on this? 

I'm trying to use the `slide` component on a page but nothing renders and I get this error `Error: Uncaught (in promise): TypeError: Cannot read property '__zone_symbol__setTimeout' of undefined`

```
@ionic/cli-plugin-cordova       : 1.6.1
@ionic/cli-plugin-ionic-angular : 1.4.1
@ionic/cli-utils                : 1.7.0
ionic (Ionic CLI)               : 3.7.0
Cordova CLI : 7.0.1
Cordova Platforms  : ios 4.4.0
Ionic Framework    : ionic-angular 3.4.2
Node : v7.9.0
OS   : macOS Sierra
npm  : 4.2.0
```

**Comment by FdezRomero** [comment]
Hi @sidlauskaslukas! Is this still an issue in Ionic 3.9.2? (I'm volunteering to triage issues). Thanks!
