### ISSUE TITLE
Common <ion-nav> component for iOS does not have top margin

### ISSUE THREAD

**Issue by ray-z** [ionic-team/ionic#10515]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Created a common `<ion-navbar>`:

    @Component({
      selector: 'sb-modal-navbar',
      template: `
        <ion-navbar>
          <ion-title>{{ title }}</ion-title>
          <ion-buttons start>
            <button (click)="dismiss()" text-center ion-button clear color="light">
              Cancel
            </button>
          </ion-buttons>
          <ion-buttons end *ngIf="buttonName">
            <button>
              {{ buttonName }}
            </button>
          </ion-buttons>
        </ion-navbar>
      `
    })

Use common component in page `TestPage`:

    <ion-header>
      <sb-modal-navbar title="Nickname" buttonName="Save"></sb-modal-navbar>
    </ion-header>

**Current behavior:**
In iOS, if I use `this.navCtrl.push(TestPage)` to enter this `TestPage`, the top margin of the header bar is gone. Same as using `this.modalCtrl.create(TestPage).present()`

**Other information:**
It works fine in Android but not in iOS (tested in 10.2).

**Ionic info:** 

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.6
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by mhartington** [comment]
This is something that is posted pretty often.
It has to do with content projection and being able to find the correct element in the DOM.
At the moment, there's not a whole lot we can do without a big refactor, since angular 2 does not have the same `replace` functionality that angular 1 has.
