### ISSUE TITLE
<ion-range> (Slider) is not draggable on touchscreen for Windows 10

### ISSUE THREAD

**Issue by liuxh0** [ionic-team/ionic#10525]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Using `<ion-range>` in Windows UWP app, the slider can be dragged by mouse but cannot be dragged using touchscreen.

**Expected behavior:**

The slider should be draggable on touchscreen.

**Steps to reproduce:**

**Related code:**

```
<ion-range></ion-range>
```

**Other information:**

I am aware that this problem is caused by Internet Explorer, which affects the generated app. It works fine with other browsers like Chrome.

I found this thread https://forum.ionicframework.com/t/range-slider-not-movable-in-internet-explorer/19592/4 but it seems that it is for Ionic 1, since the author uses `<input type="range" />` and furthermore I couldn't find `ionic.bundle.js`.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed
```

**Comment by mhartington** [comment]
Hi there! Is this an issue inside Edge or is it specific to IE?

**Comment by liuxinhu** [comment]
This is an issue inside Edge, IE11 and Windows UWP app on Windows 10.
