### ISSUE TITLE
Sidemenu is not draggable/swipable in android 4.4

### ISSUE THREAD

**Issue by btdevn** [ionic-team/ionic#10539]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

In a fresh install of the ionic2-starter-sidemenu, the side menu opens if the icon/button is tapped, and similarly can be dismissed with a tap, but it cannot be dragged open or closed on swipe from the side.

**Expected behavior:**

One should be able to drag open and close the side menu

**Steps to reproduce:**

The bug is viewable on a fresh installation of ionic2-starter-sidemenu and when deployed on android 4.4 via "ionic run android"

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.2
Node Version: v5.4.1
Xcode version: Not installed

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this.

**Comment by btdevn** [comment]
Any updates please?

**Comment by btdevn** [comment]
The problem seems to be some sort of conflict with native touch events. if I do
`document.ontouchmove = function(e){e.preventDefault();}`
the menu dragging works properly, however the touchmove effects like scrolling fails in the rest of the app.

**Comment by Floppy1009** [comment]
Have you found a way to solve this conflict so that scrolling, etc keeps working?
