### ISSUE TITLE
Segments breaks Infinite scroll

### ISSUE THREAD

**Issue by Jai-Krish** [ionic-team/ionic#10548]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Infinite scroll is not triggered for pages with Segments

**Expected behavior:**
Infinite scroll should be triggered for pages with Segments

**Steps to reproduce:**

http://plnkr.co/edit/zNxlBj0R8Zmt7BT3qKPn?p=preview

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.5.0
Xcode version: Not installed
```

**Comment by mhartington** [comment]
Hi there! 

I'm not really understanding the issue. From the plunkr, everything appears to be working fine.
Could you explain the issue with a bit more detail?

**Comment by Jai-Krish** [comment]
![feb 27 2017 12-51 am](https://cloud.githubusercontent.com/assets/8928850/23350806/205dc93e-fc8b-11e6-971a-a271648ead4e.gif)

I'm using Chrome Version 56.0.2924.87 (64-bit) on Windows 10 Version 1607 (OS Build 14393.0)

**Comment by front-stream** [comment]
I have the same issue
