### ISSUE TITLE
ToastController, dismissOnPageChange does not properly detect page change

### ISSUE THREAD

**Issue by kamok** [ionic-team/ionic#10544]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Suppose a toast is created on tabs page's tab, even with `dismissOnPageChange` set to `true`, it will not detect when a user visits another tab. This event is registered in the ViewController.didLeave observable, but the ToastController doesn't use it with `dismissOnPageChange`.

**Expected behavior:**
I expect `dismissOnPageChange` to use ViewController's idea of what it means when a page changes. Since the nomenclature is not `dismissOnPageDestroy`, but rather "Change". A page could be hidden from the user, but is still alive, as with the case of navigating between tabs.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
ios-deploy version: 1.9.0
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Thanks, we will look into this!
