### ISSUE TITLE
[Bug] Can't place ion-refresher inside custom component 

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#10540]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If I try to add `ion-refresher` to a custom component.
> Parse Error: No provider for Content

**Expected behavior:**
Although such behavior is not to be recommended, sometimes it is needed to place the `ion-refresher` inside a component, for example on my case:
I have 3 lists which are identical in look and behavior, but with different content every time. So my list component should have virtual-scrolling, refresher, infinite-scroll etc in that one component.

**Steps to reproduce:**
Place an `ion-refresher` inside a custom component and not in a page's view directly

**Related code:**

```
<ion-refresher (ionRefresh)="refreshList($event)">
    <ion-refresher-content></ion-refresher-content>
</ion-refresher>
```

**Other information:**
This is very similar to this problem: https://github.com/driftyco/ionic/issues/6531
And as such can be resolved with same solution in principal I believe: 
https://github.com/driftyco/ionic/pull/10507

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by tmvnk** [comment]
Experienced the same issue

**Comment by jgw96** [comment]
Thanks, we will look into this.

**Comment by viniciusgandrade** [comment]
This issue appears to affect when the app uses the split-pane component. The same issue on ion-refresher occurs.

**Comment by digaus** [comment]
Since the introduction of split-pane the refresher is not working for me anymore. Throwing this error: 
`Error in ./Page1 class Page1 - inline template:10:2 caused by: Unable to get property 'push' of undefined or null reference`

**Comment by digaus** [comment]
Latest nightly fixed the refresher for me :)

**Comment by AmitMY** [comment]
On latest beta, still an issue:
> No provider for Content ("[ERROR ->]<ion-refresher (ionRefresh)="refreshList($event)">

**Comment by millerbarros** [comment]
+1

**Comment by ermamud** [comment]
+1

**Comment by abierbaum** [comment]
Anyone found a way around this issue?

**Comment by abierbaum** [comment]
Has anyone tried removing the @Host() in ion-refresher and making a custom build of Ionic?  I think that would resolve the bug as @AmitMY pointed out in the report.

**Comment by Mary-Ya** [comment]
This answer may help [https://github.com/ionic-team/ionic/issues/6531#issuecomment-253423430](url)
Try to add `Content` to your components `viewProviders`

```
import { Content } from 'ionic-angular';
...
@Component({
...
  viewProviders: [Content]
})
```

**Comment by WilixLead** [comment]
Put your refresher and other tags to "<ion-content></ion-content>"

**Comment by mubasshir** [comment]
Thanks @WilixLead. It worked

**Comment by sKuD51** [comment]
Thanks @WilixLead but we can't add another <ion-content> inside a component :-(

**Comment by danilocecilia** [comment]
if ion-content is outside the component, it doesn´t work..

**Comment by granthoff1107** [comment]
I can get you past this level but I haven't beaten the game yet

    ```@Component({
          selector: 'custom-list',
          templateUrl: 'custom-list.html',
          viewProviders:[Content]
    })```
