### ISSUE TITLE
nav pop is called too many times in platform.registerBackButtonAction()

### ISSUE THREAD

**Issue by uzumakinaruto123** [ionic-team/ionic#10549]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report (possible bug)
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

On overriding hardware back button , nav pop() inside registerBackButtonAction() is called multiple times.
(check related code). I don't think I am calling nav pop() more than once.

![navpop](https://cloud.githubusercontent.com/assets/15323421/23302172/9f4b5178-fab3-11e6-9370-82bcb322b4ad.png)

**Expected behavior:**

nav.pop() to fire once according to the condition's.

**Related code:**

```
platform.registerBackButtonAction(() => {
                  let tabNav=this.tabs.getActiveChildNav();
                if(this.nav.canGoBack()){
                  this.nav.pop();
                }else{
                    if(tabNav['_views'].length > 1){
                        this.tabs.viewCtrl['_nav'].pop();
                    }else if(tabNav['_views'].length == 1){
                      platform.exitApp();
                    }
                }
          });
```

**Reason for overriding back button:**

because of this issue [https://github.com/driftyco/ionic/issues/9827](https://github.com/driftyco/ionic/issues/9827) , I am overriding back button inside popoverpage just to dismiss the popup.

On didDismiss , I override again as in related code.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.3.1
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.1.0
Xcode version: Not installed
```

**Comment by manucorporat** [comment]
registerBackButtonAction() does not override the default implementation, it just subscribes to the events.

**Comment by uzumakinaruto123** [comment]
Oh !  I consider it as overriding because once I register it , hardware back button stops working. If , it was just subscribing then default behaviour of navigation should not break.  Hardware button not working once registering , is it an existing issue ?

**Comment by manucorporat** [comment]
@uzumakinaruto123 sorry!! you were right, it does override it. Taking a look
