### ISSUE TITLE
Changing page of tab dynamically requires a physical click

### ISSUE THREAD

**Issue by zoinkydoink** [ionic-team/ionic#10556]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...** 
[ x] bug report

**Current behavior:**
I also reported this here.. but no replies

https://forum.ionicframework.com/t/changing-page-of-tab-dynamically-requires-a-physical-click/79879/1

I have a tab that i assign 2 different pages two depending on some user action, however if i dynamically change the root page of a tab and select it, it does select the right tab but the content is not refreshed with the new page, i have to physically click the tab button AGAIN in order for it to update the content.

It seems i need to force a "click" event of a tab

Switching tabs dynamically/changing their rootpage doesnt seem to do anything until i physically click the tab again

**Expected behavior:**
Expect the tab to switch and the new root page to show 

**Steps to reproduce:**
1. Initially set one of the tabs pages to Page1 (any page)
2. Dynamically try to set the root page of that tab to another page using the code in related code section
3. the tab will switch, however the tab's page will not (content still showing the old page)
4. physically click the tab again (that was suppose to be switched to)
5. Then expected behavior works (content of the new page shows up)

For Ionic 1 issues - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

For Ionic 2 issues - http://plnkr.co/edit/z0DzVL?p=preview
-->

**Related code:**
`
var homeTab = navCtrl.parent.getByIndex(0);
homeTab.root = HomePlacePage;
navCtrl.parent.select(0);`

`

**Comment by zoinkydoink** [comment]
i attached the src (to minimize the upload)
steps to repo.

![src](https://cloud.githubusercontent.com/assets/15949978/23379683/e464d0fa-fd05-11e6-924b-5c458a9a8367.png)

**RENAME TO ZIP (some reason it didnt let me upload a zip)**

1. ionic serve
2. click About tab
3. click "Home Two" which is suppose to change the content of the homepage to a different page, the tab switches, but the content does not.
4. click the Home Tab couple of times then it will switch to the expected results

**Comment by jgw96** [comment]
Hello @zoinkydoink , does this still happen with the latest version of Ionic?

**Comment by zoinkydoink** [comment]
yep it happens with latest version and across all platforms (including --lab)

**Comment by zoinkydoink** [comment]
any idea when this will be fixed?

**Comment by jgw96** [comment]
Hey @zoinkydoink , i'm very sorry for the delay on this. While this is not our top priority issue at the moment we will be looking into this sometime in the future. We work on a priority/severity based queue so while it may be some time we will get this fixed up. Thanks for using Ionic!

**Comment by zoinkydoink** [comment]
Any idea when this will get added, I have literally been waitingmonths for an update on this

**Comment by beduardo** [comment]
Hi,

I had a similar problem navigating between two pages with <ion-tabs> here and found this topic when I was looking for a solution.
I solved with a ngIf with a boolean variable in the <ion-tabs> and making the variable go from false to true between ionViewWillEnter and ionViewDidEnter.

HTML:
`<ion-tabs *ngIf="show">
    <ion-tab [root]="tab1Root"></ion-tab>
     .
     .
     .
</ion-tabs>`

TS
`
  ionViewWillEnter(){
    this.show = false;
  }

  ionViewDidEnter(){
    this.show = true; 
  }`

Maybe you can do something similar with setTimeout() without the timeout parameter to force the tabs reload:
`loadTab() {
   this.show = false;
   setTimeout(_ => { this.show = true; });
}`

**Comment by ratshidaho** [comment]
My work around:
`setTimeout(() => {
          this.navCtrl.getActiveChildNav().select(0);
        }, 100)`

**Comment by nmrony** [comment]
@jgw96 I am facing the same issue. For my case the page changes to selected Tab Index but the Tab bar active state remains unchanged. I am using 
```
cli packages:

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v8.9.0
    npm               : 5.5.1
    OS                : macOS Sierra
    Xcode             : Xcode 9.1 Build version 9B55
```

**Comment by JoaoPortella** [comment]
This work fine in my case:

```
cli packages: 
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0
global packages:
    cordova (Cordova CLI) : 6.5.0
local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.1.2
    Ionic Framework    : ionic-angular 3.9.2
System:
    Android SDK Tools : 26.0.1
    Node              : v6.10.3
    npm               : 3.10.10
    OS                : Windows 10

//
let tabIndex = 2; // This is your tab index
let myTab = this.navCtrl.parent.getByIndex(tabIndex);
myTab.setRoot(NewPage); // NewPage component is your new page to load
//
```
