### ISSUE TITLE
Tabs being pushed up by keyboard when searchbar is blurred (iOS 10.2)

### ISSUE THREAD

**Issue by designcouch** [ionic-team/ionic#10552]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In iOS 10.2, I am having an issue with my tabs when blurring a searchbar component. When the keyboard slides down, the tabs suddenly appear in the middle of the screen for about 300-500ms, and then drop back down to the bottom.

![](http://g.recordit.co/YOoAVbr6Se.gif)

**Expected behavior:**
I would expect that the tabs would remain hidden behind the keyboard, and when it slides back down, they would be revealed again, in the same position.

**Steps to reproduce:**
This only appears when you're actually previewing the app on an iOS device; not in the browser (since, obviously, the soft keyboard is not shown in browser).

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by rossholdway** [comment]
I've also run into this issue when using a standard input on a custom autocomplete component. Not sure what's causing it.

**Comment by designcouch** [comment]
@rossholdway were you able to identify a fix at all when you encountered it?

**Comment by rossholdway** [comment]
@designcouch The only way I could get around the issue was to use an ion-input, but it looks like this won't apply to your situation :/

**Comment by nowitz** [comment]
I have same problem :-/

**Comment by shobhitchittora** [comment]
I'm having a similar issue. I'm using `<ion-input>` in a `<form>`. When filling the form on Android the tabs are sticking to the keyboard. Haven't checked on iOS though. Can we try to change the component , so that we can send an event to add as `display: none `to it.
