### ISSUE TITLE
ionSlideDidChange event does not fire when we switch out from the tab containing ion-slides

### ISSUE THREAD

**Issue by AlGantori** [ionic-team/ionic#10581]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have setup a plunker to reproduce the behavior I am experiencing.
ion-slides does not fire ionSlideDidChange configured hanlder when user switch to a different tab.

**Expected behavior:**
ion-slides continues to play (ie. fire ionSlideDidChange event and calling the associated hanlder SlideChanged() code until my code logic stops calling **this.slides.slideNext()**

**Steps to reproduce:**
http://plnkr.co/edit/bYhKWhGtA0FQepd9Y28P?p=preview

1. Display developer console in your browser with F12
2. Visit the second tab "Players" and press the button that starts the ion-slides playback,
3. As soon as the first or second slides completes switch the first tab "Media"
4. You should observe ion-slides stops playing even though **this.slides.SliderNext()** was called.

**Related code:**
Template...
```
<ion-slides #mySlider  effect='slide'  (ionSlideDidChange)="SlideChanged()" style="height:100px">
    <ion-slide  *ngFor="let s of SlidesData ;  let ii=index">
      <p>Slide {{ii+1}} of {{SlidesData.length}}</p>  
    </ion-slide>
</ion-slides>
```
Component/Controller...
```
    SlideChanged() {
        console.log("Page2<<e------------SlideChanged");
        try {
            var index = this.slider.getActiveIndex();
            console.log("Page2-----------slide CHANGED", index);
            this.PlayIndex(index + 1);
        }
        catch (e) {
            console.log(<Error>e.message);
        }
    }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Page2------------>>PlayIndex 1  Page2.ts!transpiled:81:9
Page2------------>>SlidePostPause  Page2.ts!transpiled:102:9
Page2<<promise------------SlidePostPause DONE  Page2.ts!transpiled:85:13
Page2------------>>SlideNext  Page2.ts!transpiled:58:9
Page2<<e------------SlideChanged  Page2.ts!transpiled:68:9
Page2-----------slide CHANGED 1  Page2.ts!transpiled:72:13
Page2------------>>PlayIndex 2  Page2.ts!transpiled:81:9
Page2------------>>SlidePostPause  Page2.ts!transpiled:102:9
Page2<<promise------------SlidePostPause DONE  Page2.ts!transpiled:85:13
Page2------------>>SlideNext
```
expecting SlideChanged() getting called like when we don't switch tabs.

Thank you.

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this!

**Comment by AlGantori** [comment]
Some background info

I switch tabs with navcontroller  .select(), thus I don't push/pop navigation in hope to keep players tab alive.

I would like to be able to keep my slides playback playing while I browse other media.  Also because I have sound, a postpause, etc... associated with a slide playback, and my current logic is based on this event everything stops (audio, etc...).

I could see the argument about ion-slides not being visible, which would mean I would have to make my own events and restore the correct slide when the tab's particular player content becomes visible.
However, I find that awkward, especially that other players will continue playing like I am using npm package plyr to play videos in the same tab.
I have not tried to use directly slider.js to see if this an ionic2 implementation-introduced new behavior.

Thank you for taking a look.
