### ISSUE TITLE
Split Pane Deep Linker Support

### ISSUE THREAD

**Issue by roblouie** [ionic-team/ionic#10597]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using Split Pane, Deep Linking initially works fine, enabling the browser back button as you navigate from within one of your panes:
![Deep Linking while navigating](http://i66.tinypic.com/10elttw.jpg)

However, as soon as I hit the refresh button, simulating opening the app from that url, both panes are given the component matching the url:
![](http://i64.tinypic.com/j9q25i.jpg)

**Expected behavior:**
I would expect that only the main content pane would be updated based on the url. It seems currently the deep linker has no knowledge of the split pane, and only tries to retrieve the active nav, however I don't know why that would cause both panes to update like they do.

**Steps to reproduce:**
Modify the starter side menu app to use the split pane similar to how the blog post demonstrates it, moving the menu logic into a new side-menu component. Add the deep linker config to the app module. I have a sample of this here: https://github.com/roblouie/split-panel-demo

In the left pane menu, click 'Page 2' to navigate to the list page, then click on one of the items in the list. This should update the url to 'item/:itemId' as shown in the images attached.  Now hit the refresh button on the browser and watch as both panes get the component from 'item/:itemId'.

**Other information:**
The SidePane class has both a sideContent and a mainContent. It would be nice if the SidePane let you choose which of those was the "true" root of the project, with the default being mainContent. Only that nav would be affected by the deep linked url. It would also be nice to have access to each pane's nav, so that navigation in one could be triggered by the other.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.3.1
Ionic Framework Version: 2.0.1-201702161925
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Thanks, we will look into this.

**Comment by astec** [comment]
Also hit this and spent an hour trying to understand if I do something wrong.

I would categorize it as a bug, not a feature request.

**Comment by JWesorick** [comment]
I'm seeing this too. And yea, definitely a bug not a feature.

**Comment by vgb1993** [comment]
Hy I'm having the same issue, both panes load with the same view after refresh. I have two nav instead of a nav and a menu. Is that ok?

```
<ion-content>
  <ion-split-pane (ionChange)="ionChange($event)">
    <ion-nav [root]="side"></ion-nav>
    <ion-nav [root]="content" main></ion-nav>
  </ion-split-pane>
</ion-content>
```

I am building a PWA that needs to take advantage of the side pane as the amount of info is very big. I am wondering how to move forward..

It use to work alright without the deep linking urls. I am thinking, can I disable the deep url system in order to keep having a stable split pane? I have been looking for a way to do that in Ionic's git repository but I couldn't find a way to do it..

I would be very grateful if someone could show me a workaround for this or if the bug gets solved. Which options do we have right now?

Victor
