### ISSUE TITLE
Strange behavior when placing a ion-range inside an ion-item

### ISSUE THREAD

**Issue by slzr** [ionic-team/ionic#10599]
**Ionic version:**  (check one with "x")
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
I get strange behavior when placing an `ion-range` inside a` ion-item`, hide almost all the elements inside

**Expected behavior:**
show all the elements inside the `ion-item`, included the `h2` and `p` elements

**Steps to reproduce:**
[Plunker example](http://plnkr.co/edit/3jdJgD?p=preview)
```html
<ion-item>
  <ion-thumbnail item-left>
    <img src="url">
  </ion-thumbnail>
  <h2>Title</h2>
  <p>Artist • Album</p>
  <button ion-button clear item-right large color="primary" (click)="togglePlay()">
    <ion-icon *ngIf="!playing" name="play"></ion-icon>
    <ion-icon *ngIf="playing"  name="pause"></ion-icon>
  </button>
  <ion-range class="audio-progress"
    [(ngModel)]="audioPos"
    color="primary"
    step="1" max="100"></ion-range>
</ion-item>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```bash
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.10.0
Xcode version: Not installed
```

**Comment by comfortme** [comment]
i think this is expected . ion items can only have one component in them. range, toggle, checkbox vs..
you should place range in a different ion item

**Comment by slzr** [comment]
@comfortme I see what you say, and it make sense, at the end I used a html5 `progress ` element and make it looks like material design with css. I just wanted make a simple audio player, but since there is not a `progress` component in Ionic [#6669](https://github.com/driftyco/ionic/issues/6669#issuecomment-283475061),  I thought to use a `range `component was a good idea, my bad

```html
<progress class="progress" max="{{ audioDuration }}" value="{{ audioPos }}"></progress>
```

![imagen](http://i.imgur.com/YTPSAFu.gif)

**Comment by godzsa** [comment]
Is there any other workaround for this? I really need ion-range with other elems in one ion-item-sliding.

**Comment by realappie** [comment]
@slzr There will be an ionic progress component soon ;)

**Comment by shootdaj** [comment]
I believe you have to place the ion-range inside a <div item-content>
