### ISSUE TITLE
swipe up or down event doesn't work 

### ISSUE THREAD

**Issue by alaa-alshamy** [ionic-team/ionic#10609]
**Ionic version:**  2.1.0

**I'm submitting a ...**  bug report

**Current behavior:**

swipe gesture doesn't work with up and down directions, just work with left and right

**Expected behavior:**

should work with any direction 

**Steps to reproduce:**

this plnkr showing how the swipe event doesn't work if you swipe up or down and the swipe work as expected if you swipe left or right 

http://plnkr.co/edit/Fpr7ij1pbXT5sz93O3oo?p=preview-->

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.2
Node Version: v6.3.1
Xcode version: Not installed
```

**Comment by saschwarz** [comment]
I believe vertical swipe is not enabled by default:
http://hammerjs.github.io/getting-started/#usage

Take a look here for how to enable it in Ionic/Angular2: http://stackoverflow.com/a/39999724/457935
