### ISSUE TITLE
Format text on pin of ion-range knob

### ISSUE THREAD

**Issue by stefanhuber** [ionic-team/ionic#10615]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently it is not possible to format the output on the pin of the range knob. A formatted output seems to be necessary in many cases. E.g. a music player: https://forum.ionicframework.com/t/change-text-on-range-knob-pin-true/81390

**Expected behavior:**
It would be great to somehow allow for formatting the text on the pin!

**Other information:**
https://forum.ionicframework.com/t/change-text-on-range-knob-pin-true/81390

**Comment by chetanPfizer** [comment]
Any update/workaround on this?

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#246
