### ISSUE TITLE
Ionic 2 IOS Keyboard GO button submits form even though submit button disabled.

### ISSUE THREAD

**Issue by mikelunn** [ionic-team/ionic#10621]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

IOS 10.2 Keyboard GO button submits form even though Submit button is disabled.

**Expected behavior:**

IOS GO button does not submit form when form submit button is disabled.

**Steps to reproduce:**

![keyboard-submit-issue](https://cloud.githubusercontent.com/assets/3696624/23512694/775b5106-ff2f-11e6-90c7-a8ce67080c57.gif)
**Related code:**
I'm using Angular's Model driven approach to forms and are disabling the form button within the form tag like below:
```
<form [formGroup]="form" (ngSubmit)="submit(form.value)">
<button type="submit" ion-button color="secondary" full large [disabled]="form.invalid">Submit</button>
</form>
```

**Other information:**

I have another Ionic 2 app that was developed with Ionic 2.0.0 where the issue does not exist.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002

```

**Comment by mikelunn** [comment]
The obvious work around for this is to simply check if the form is valid within the components save/submit function (that should be there anyway), but it would be nice if the on-screen keyboard honored the disabled form submit button.

**Comment by Anujmoglix** [comment]
Same problem for me . Did you get any solution ?

**Comment by iMario999** [comment]
Did you find a solution for that?

**Comment by meshal500** [comment]
Same issue here.
