### ISSUE TITLE
Invisible tabs - when generated from an observable

### ISSUE THREAD

**Issue by Joey33** [ionic-team/ionic#10632]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When generating tabs with *ngFor with data from an observable the tabs element is invisible. But when hovering the mouse the cursor changes and you can click tabs - then they become visible and their respective root pages load

**Expected behavior:**
Tabs should be visible

**Steps to reproduce:**
My tabs.ts (simpilified) - data used to generated tabs with *ngFor is brought from php backend:

```
import ...

export interface Group {
        id: number;
        group: string;
    };

@Component( {
        template: `
    <ion-tabs selectedIndex="0">
        <ion-tab *ngFor="let tab of userGroups" [root]="page" [rootParams]="tab.id" [tabTitle]="tab.group" tabIcon="pulse"></ion-tab>
    </ion-tabs>
    `
    })

    export class GroupsTabsPage {
        userGroups: Group[];
        page: any = TabStudentsPage; //the same - only dif params from each tab

        constructor( public app: App, public api: Api, public navParams: NavParams ) {

            this.api.getGroupsList()
                .subscribe(
                data => {
                    this.userGroups = data;
                },
                err => {
                    this.app.getRootNav().push( LoginPage )
                }
                );

            //  ionViewDidEnter() {
            //  }

        }
    }
```

When I used @ViewChild to refer to the tabs elements, the interesting thing is that its 'length' property is always 0 (I checked in ionViewDidLoad event). Trying to select one of the tabs programatically also fails - they are like ghosts;)

Also when you place at least one static tab next to *ngFor ones in the template, all *ngFor ones show up but the static is always selected no matter what you select programatically or in selectedIndex property on tabs element.

For now I must query the backend BEFORE (in app.ts) and send the result in NavParams to 'tabs' view.
Using all possible lifecycle hooks in 'tabs' view has no results. It must be tabs issue since displaying the results in eg a list works as expected - they show up. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1
ios-deploy version: Not inst
ios-sim version: Not install
OS: Windows 7
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Thanks for opening an issue, we will look into this.

**Comment by mariohmol** [comment]
Hei there.. i dont know if this exactly same issue.. but is same version at least... i had to add this class  

`.tabbar{
opacity: 1;
}
`

**Comment by Joey33** [comment]
Hi, yes that's exactly the hack I came up with as well - I forced the tabs to be visible BUT 
still they're dead on the start = nothing selected

see the last line:)
https://forum.ionicframework.com/t/dynamic-tabs-invisible-tabbar/81424

**Comment by mariohmol** [comment]
did u tryed this: `<ion-tabs  tabbarPlacement="bottom" #myTabs> @ViewChild('myTabs') tabRef: Tabs; this.tabRef.select(0); `  ?

**Comment by Joey33** [comment]
Indeed:) http://stackoverflow.com/questions/42576091/ionic2-invisible-tabs-when-generated-from-an-observable - my reply to a reply;

**Comment by mariohmol** [comment]
uhmm.. seems to be related with lifecycle..  what happens if you do this console.log in a ionChange .. like `ionChange="myfunc()"   myfunc(){ console.log(this.tabRef.length()) }` .. try to do this same console log inside the subscribe as well

**Comment by Joey33** [comment]
always 0 - tried it as well (I spent 3 days so nuuuuuuuumerous options were underway:)
Tried to populate the variables at different lifecycle hooks - to no avail:)

**Comment by Joey33** [comment]
it's a buggy bug my friend:)

**Comment by mariohmol** [comment]
just now.. i have one page that is showing the tabs.. but other that is pretty the same is not showing.. i had to add another hacking in css like `.tabbar{ bottom: 55px}`.. so went dive into.. and seems to be related with scroll.. try to use the ion-scroll but got a blank ... in my case seems to be something related with scrolls and tabs

**Comment by Joey33** [comment]
Another workaround I found is to do server query BEFORE the tabs page not on it. So try passing data to populate the tabs as params of the push/set method.

**Comment by bushybuffalo** [comment]
@jgw96 Hey, any news regarding this issue ? 
I have also encountered it while trying to set a different root for a tab depending on the presence of an element in IonicStorage, as it returns a promise.
I'm using Ionic 3.2.1

**Comment by Joey33** [comment]
I haven't checked - for now I stick to my workaround.

Actually I was hoping for a fix in the latest ver but from your comment I see it's 
left unresolved..

**Comment by csi-stasik** [comment]
Creating ion-tab from observable (dynamically) has some bugs (duplicates, wrong rendering etc) I use a workaround to avoid it, it consist of removing and loading the ion-tabs in runtime every time then observable changes.

parent template:
`    <div #pluginTabContainer></div>
`

parent component:

`     @ViewChild('pluginTabContainer', {read: ViewContainerRef}) pluginTabContainer:ViewContainerRef;

...

plugins$.subscribe((pluginTabs:Array<PluginTabType>) => {
                let componentFactory = this.componentFactoryResolver.resolveComponentFactory(PluginTabContainerComponent);
                this.pluginTabContainer.clear();
                this.pluginTabContainertRef = this.pluginTabContainer.createComponent(componentFactory);
                this.pluginTabContainertRef.instance.data = pluginTabs;

...


    ngOnDestroy() {

        this.pluginTabContainertRef.destroy();
}
`

loaded ion-tabs template:
`<ion-tabs>
    <ion-tab *ngFor="let tab of data"
             [root]="'PluginTabPage'" [rootParams]="tab"></ion-tab>
</ion-tabs>`

loaded ion-tabs component (getting parameter):
`    @Input() data: PluginTabType;
`

Hope will be helpful for you.

**Comment by rinoymjoseph** [comment]
I had a similar issue during development and I was able to solve this by making ngOninit async and calling a timeout to set the selected tab.

view
```
 <ion-tabs #ctrlPanelTabs class="tabs-basic">
        <ion-tab *ngFor="let appTab of appTabs" tabTitle={{appTab.name}} [root]="rootPage"></ion-tab>
    </ion-tabs>
```
1) ngOninit is async
2)  this.ctrlPanelTabs.select(0); is set inside a timeout function
```
import { Component, OnInit, ViewChild } from '@angular/core';
import { NavController, Tabs } from 'ionic-angular';
import { AppSettings } from '../../common/app.config';
import { AppTab } from '../../models/app-tab';
import { AppTabService } from '../../services/app-tab.service';
import { PanelTabComponent } from './panel-tab';

@Component({
    selector: 'page-control-panel',
    templateUrl: 'control-panel.html',
    providers: [AppTabService]
})
export class ControlPanelPage implements OnInit {

    @ViewChild("ctrlPanelTabs") ctrlPanelTabs: Tabs;

    appTabs: AppTab[] = [];
    message: string;
    rootPage = PanelTabComponent;
    constructor(public navCtrl: NavController,
        private appTabService: AppTabService) {

        console.log("Control Panel Page : Constructor called..");
    }

    async ngOnInit() {
        console.log("Control Panel Page : Entering ngOninit..");
        await this.loadAppTabs();
        setTimeout(() => {
            this.ctrlPanelTabs.select(0);
        }, 100);
        console.log("Control Panel Page : Exiting ngOninit..");
    }

    async loadAppTabs() {
        console.log("Control Panel Page : Entering loadAppTabs..");
        await this.appTabService.getAppTabsHierarchyBySlaveDeviceId(AppSettings.selSlaveDeviceId)
            .then((response: any) => {
                this.appTabs = JSON.parse(response.result);
                console.log(this.appTabs);
                console.log("Control Panel Page : Exiting loadAppTabs..");
            });
    }

}
```

**Comment by P-de-Jong** [comment]
I had the same problem and solved it using the following method:
```
 <ion-tabs *ngIf="items$ | async; let items;">
        <ion-tab *ngFor="let item of items" [tabTitle]="item.title"></ion-tab>
 </ion-tabs>
```
This will render the tabs only if the observable has data in it and works perfectly. At least for my use case...
