### ISSUE TITLE
ionViewCanEnter executed only when tab first activated

### ISSUE THREAD

**Issue by samastur** [ionic-team/ionic#10634]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ionViewCanEnter executed only when tab is first activated, but not later.

**Expected behavior:**
ionViewCanEnter method of a tab to be executed every time user switches to it.

**Steps to reproduce:**
See related code.

**Related code:**
Repo with example app demonstrating the problem:
https://github.com/samastur/ionic2-sample

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:

Cordova CLI: 6.4.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by mchenx** [comment]
No one looked at this? Or this isn't a bug?

Actually I encountered similar issue that I wanted to hack the switching of tab pages and prevent it from going to a different tab page in some cases, like user is not authorized, etc.

However, it seems not possible to achieve that for tab pages...

**Comment by slejnej** [comment]
Hi. This is still valid bug. Any updates on this after more than 6 months???

**Comment by slejnej** [comment]
Thank you for that.
v4 is like a year away? What can we do to overcome this issue in the meantime? There isn't any proper guard in place, so functionality of it can be in this event, but because it is not working, how can we do guard that will fire on route change (tabs in this case) and fire checking? Angular Route does not work also.
Thank you.
