### ISSUE TITLE
ion-slides only allows integer values for slides per view after RC-5

### ISSUE THREAD

**Issue by suau** [ionic-team/ionic#10661]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request

**Current behavior:**
The `ion-slides` component allows only integer values for `slidesPerView`, and will turn any float values into full ints. Pre-RC5 with the now deprecated `options` input this worked perfectly fine.
[sourcecode](https://github.com/driftyco/ionic/blob/master/src/components/slides/slides.ts#L360)

**Expected behavior:**
The `ion-slides` component allows float values for `slidesPerView`, this is an important UX/UI element as half cut-off content gives the user a hint that horizontal sliding is the interaction method here. Pre-RC5 this was working as expected

**Steps to reproduce:**

http://plnkr.co/edit/Bm89QtZXvFgp91KNe2FR?p=preview

**Related code:**

```
<ion-slides [slidesPerView]="1.8">
    <ion-slide style='background-color:#00FF00;'>
      <div>
        <img src="http://lorempixel.com/600/400/sports/" />
      </div>
    </ion-slide>
    <ion-slide style='background-color:#FF0000;'>
      <div>
        <img src="http://lorempixel.com/600/400/city/" />
      </div>
    </ion-slide>
    <ion-slide style='background-color:#0000FF;'>
      <div>
        <img src="http://lorempixel.com/600/400/people/" />
      </div>
    </ion-slide>
  </ion-slides>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by suau** [comment]
temporary workaround is to find the component in the node_modules folder and this line:
[https://github.com/driftyco/ionic/blob/master/src/components/slides/slides.ts#L360](https://github.com/driftyco/ionic/blob/master/src/components/slides/slides.ts#L360)
and change `parseInt` to `parseFloat`.

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.
