### ISSUE TITLE
Attribute changes in templates not reflecting when using live reloading

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic#10665]
_From @jgw96 on March 6, 2017 14:46_

_From @aplimovil on March 3, 2017 21:45_

**Ionic version:**
[x] **2.x**

**I'm submitting a ...**
[x] bug report

**Current behavior:**
When I make a change to an attribute of an element in a template (.html file of a page) using live reloading, the app refreshes and the live reloading is triggered, but when I check the updated page template in the app, the changes are not reflected, almost as if the attributes of the elements of the template are being cached.

Note that if other aspects of the template like structure or added/removed elements do work correctly, it's only attribute changes that aren't being reflected with live reloading.

If I terminate the "ionic serve" process and run it again, then the template is now updated correctly with the attribute changes.

This started happening after I upgraded to the 2.0.1 release from the 2.0.0 version. I just updated to 2.1.0 to check if the bug was fixed but it's not, it's still hapenning.

**Expected behavior:**
All template changes should be reflected immediately on live reloading.

**Steps to reproduce:**
Run "ionic serve" with live reloading, make a change to a template, wait for the app to reload (on browser or device), and the change will not be reflected.

Here's a link to a screencast I recorded showing the problem, where I update a template by adding a padding attribute to 2 DIVs so they have padding, but after live reloading no padding is added:
http://quick.as/0vnVcvx16

**Ionic info:**

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: OS X Mavericks
Node Version: v6.2.0
Xcode version: Xcode 6.2 Build version 6C131e
```

_Copied from original issue: driftyco/ionic#10640_

_Copied from original issue: driftyco/ionic-cloud-issues#285_

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#794

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud-issues#284

**Comment by comfortme** [comment]
i can confirm this issue. 
it was fine with 2.0
my nightmare https://github.com/driftyco/ionic-app-scripts/issues/363 is back.

**Comment by duydao** [comment]
This issue was resolved for me after upgrading my outdated packages and ionic to 2.2.0

**Comment by comfortme** [comment]
this is not resolved for me in 2.2.0.
sometimes view goes 3 or 4 saves back.

it is like this: update html with text1 and save, then type text2 and save... go on like this and when i reach text5 and save i see text1. very confusing.

if i close ionic serve and serve again view is text5 as normal again

**Comment by rashnk** [comment]
The issue exist in latest app script, changes not reflect in browser, delete www folder works..
every time i need to stop server and restart ionic serve, wt..

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.3
Xcode version: Not installed
```

**Comment by heikoholland** [comment]
I'm having the same issue. Only workaround I got at the moment is aborting the current `ionic serve` and restarting it.

**Comment by okonon** [comment]
Same issue. But i am on oder setup:
```
W
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.2
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by Assdi** [comment]
I m facing the same issue @jgw96
