### ISSUE TITLE
Textarea does not scroll

### ISSUE THREAD

**Issue by Isigiel** [ionic-team/ionic#10677]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When my textarea has overflowing text I am not able to scroll up and down on it.

**Expected behavior:**

Mouse and touch scrolling should work on the textarea as well.

**Steps to reproduce:**

Have a textarea and enter enough to get an overflow.
http://plnkr.co/edit/5xOTTVLeLazj0bIEUhdQ?p=preview
This textarea does not scroll anymore when viewed with the chrome device preview.
It seems like a `div.input-cover` is catching the scroll events, the scrolling works when I remove it.

**Related code:**

https://gitlab.com/pikandpeople/mobile-next/blob/master/src/pages/conversation/conversation.html#L30

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI:  You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.5.0

Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.6.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Thanks for opening an issue, we will look into this.

**Comment by Isigiel** [comment]
Any news or workarounds on this?
