### ISSUE TITLE
ion-item-divider[sticky] overlaps newly added items

### ISSUE THREAD

**Issue by nonamez** [ionic-team/ionic#10691]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When trying to add new array item in to the beginning of array from which list with dividers is generated the first existing divider overlaps just added one. 

**Expected behavior:**
Should go down to the second position

**Steps to reproduce:**
Here is an example, but it works. May be because of different versions of framework...

https://plnkr.co/edit/0MomLgUGewEsvNB1q3Mc?p=info

**Related code:**

```
let groups_of_tests = this['test_' + this.testType]
// some code
groups_of_tests.unshift({DateEnd: date, items: data.tests})
```

```
<ng-container *ngFor="let group of tests">
	<ion-item-divider sticky>
		<ion-label>
			{{ group.DateEnd }}
		</ion-label>
	</ion-item-divider>
	<ion-item *ngFor="let test of group.items">
		<h3>{{ test.Reason }}</h3>
	</ion-item>
</ng-container>
```

The thing that only helps is to remove all `sticky` before adding new items and then re-add `sticky` attribute.

**Other information:**
Before adding it looks like this http://i.imgur.com/hBgP4AI.png

When added (date is 2017-03-09) it still shows `2017-03-08` which overlaps `2017-03-09` http://i.imgur.com/Q79u8Bb.png

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.7.1
Xcode version: Not installed

```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! So that plunker is using ionic 2.1.0 (the latest stable version of Ionic) which from your `ionic info` seems to be the same your using. Is there any way that you could make a plunker or repo that we can use to reproduce this issue?

**Comment by nonamez** [comment]
Ok, i will try today...

**Comment by nonamez** [comment]
Mmm, sorry, I could not reproduce the error... Dont know why. But while doing that found another strange thing... 

https://plnkr.co/edit/0MomLgUGewEsvNB1q3Mc

When you add same thing two times there are to sticky titles http://i.imgur.com/653HKdy.png

**Comment by jgw96** [comment]
Hello @nonamez , is this still an issue with ionic 2.3.0?

**Comment by nonamez** [comment]
![screenshot_2017-03-27_10-04-28](https://cloud.githubusercontent.com/assets/1894964/24344569/ca9cdc00-12d4-11e7-8976-5ed7d76c61cc.png)

Yep, it still there. Overlaps previous list item on smaller screens when adding to the beginning of  array.

**Comment by nonamez** [comment]
May be it would help. My current fix for it:

```
let dividers = document.querySelectorAll('ion-item-divider')

for (let i = 0, divider; divider = dividers[i]; ++i) {
	divider.removeAttribute('sticky')
}

groups_of_tests.unshift({DateEnd: date, items: data.tests})

setTimeout(() => {
	for (let i = 0, divider; divider = dividers[i]; ++i) {
		divider.setAttribute('sticky', '')
	}
})
```

**Comment by jgw96** [comment]
Alright, thanks for the info! We will look into a fix for this issue.
