### ISSUE TITLE
Popover - Nav Push with Dismiss breaking nav stack

### ISSUE THREAD

**Issue by davec21** [ionic-team/ionic#10694]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using a popover as a navigation menu, each button would run the following basic code:

`this.navCtrl.push(SettingsPage).then(() => {
    this.viewCtrl.dismiss(SettingsPage);
});`

If I did it this way, then the Settings page would have the back button as expected, and would properly navigate back to the page that the popover was opened on and the popover would be dismissed. Doing it with dismiss first would cause no back button to appear and would make Settings appear as root. 

I added a nav push into the settings page. When pushing the new page, the new page would have the back button allowing me to go back to Settings. Upon returning to the Settings the back button was gone and Settings was treated like a root page.

**Expected behavior:**
A way to have the popover dismiss after pushing a page but not cause the new pages in the nav stack to become root while not actually being set as root.

**Steps to reproduce:**
- Create three pages (Page1, Page2, Page3).  
- Add button that will do a nav push of page3 in page2. 
- Add a popover that does a nav push of page2 and then dismisses itself (using code above).  
- Add the popover to Page 1.   
- Open popover on page 1, press the button to push page2 onto the stack and dismiss the popover. Notice the back button is visible on Page2.  On page 2 press button to push page3 onto the stack. Page3 has back button, press it to return to Page2.  Page2 no longer has a back button.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Running Ionic2 2.1.0

**Comment by BrandonWardley** [comment]
Can confirm that this is a thing.

Can add that, as well as the back button becoming hidden, the hardware back button no longer navigates back either.

Interestingly enough, this only seems to be happening on Android in my case. iOS has the expected back button, even when view.dismiss() is used in the popover.

**Comment by priyag676** [comment]
try this https://github.com/driftyco/ionic/issues/7659

**Comment by s2young** [comment]
Hmm. I did try #7659 but still have no back button.  I also tried the showBackButton method. I'm just building in the browser at this point.

**Comment by alvesmarcos** [comment]
works for me [#7659](https://github.com/ionic-team/ionic/issues/7659)

**Comment by justjcool** [comment]
@davec21 same issue going on with me... have you found any solution?
