### ISSUE TITLE
ion-searchbar adn IOS keyboard closing issue

### ISSUE THREAD

**Issue by jamalsleman** [ionic-team/ionic#10692]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
No way to close  keyboard on iphone when using ion-searchbar

**Expected behavior:**
when clicking return " on keyboard" => keyboard will be hide

**Steps to reproduce:**
here is example ( you can take it from your demo)
<ion-searchbar (ionInput)="getItems($event)"></ion-searchbar>
<ion-list>
  <ion-item *ngFor="let item of items">
    {{ item }}
  </ion-item>
</ion-list>

**Explanation:**

on Iphone when you click on search bar, you can use the keyboard
after typing each key page will refesh the list,  but i cannot hide the keyboard all all ( till i go to other page).

We just want to give user option to hide the keyboard,
Important i donot want to close keyboard while typing ( we donot know when he finish typing).

Adding cancel button will hide the keyboardwhen user click it  but i is also cancel the search and it is not good for us.

**Comment by jgw96** [comment]
Thanks, we will look into this.

**Comment by steveacalabro** [comment]
+1 The search bar seems to be a very broken version of the regular input

**Comment by filipsuk** [comment]
This is really annoying issue and makes searchbar quite unusable on iOS. Ugly hack is to setTimeout on ionClear event to hide keyboard after 500ms :/

**Comment by guoyongxin** [comment]
Any updates? I still face this issue on 3.9.2

**Comment by JasonAsmk** [comment]
Experiencing the same issue. I'm using the recommended cordova-plugin-ionic-keyboard which does not allow for hide and show on iOS so I can't even hook to the (keyup.enter) event.

**Comment by estacks** [comment]
Some click event is triggering multiple times to hit anything under the Cancel button, like the search bar itself to bring the keyboard back up. Unlike most event bubbling this is actually several events firing, stopping the first one does nothing. 

This works for me:

```
onClear() {
    if (this.platform.is('ios')) {
      let element = this.el.nativeElement.querySelector('.searchbar-input');

      element.style.pointerEvents = 'none';

      setTimeout(() => {
        element.style.pointerEvents = 'auto';
      }, 350);
    }
}
```
