### ISSUE TITLE
Nav-component content is not projected

### ISSUE THREAD

**Issue by lujakob** [ionic-team/ionic#10704]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In order to have a "global" element across different pages that slides out with the currently selected page when animating the menu in, I want to add a new element/component in the nav-component like this:

```
<ion-nav [root]="rootPage" #content swipeBackEnabled="false">
  <div class="player" *ngIf="showPlayer">Media player</div>
</ion-nav>
```
This code disappears in the compiled HTML output.

**Expected behavior:**
Code added here should be projected to be able to add elements/components on the DOM level of the displayed page.

**Related code:**
Adding an ng-content directive to the nav-component template would solve this.

**Other information:**
I will create a pull request for this issue.

**Comment by lujakob** [comment]
I created the following pull request:
https://github.com/driftyco/ionic/pull/10705

**Comment by jgw96** [comment]
Thanks for the issue and the PR! We will look into this.
