### ISSUE TITLE
ion-slides stops autoplaying after popping another page

### ISSUE THREAD

**Issue by ysgk** [ionic-team/ionic#10720]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`ion-slides` stops autoplaying after popping.

**Expected behavior:**
Keep autoplaying even after popping.

**Steps to reproduce:**
http://plnkr.co/edit/NRt9VyW6MLLY0ITjZs0h?p=preview

1. Push page.
2. Wait for a few seconds.
3. Pop page.

And slides stops autoplaying.

**Related code:**

**Other information:**
I tried below code from https://github.com/driftyco/ionic/issues/10163, but it did not work for this case.

```ts
    @ViewChild(Slides) slides: Slides;
    
    ionViewDidEnter() {
        this.slides.autoplayDisableOnInteraction = false;
    }
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
From plunker:
```
      '@angular/core': 'npm:@angular/core@2.2.1/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common@2.2.1/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler@2.2.1/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser@2.2.1/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic@2.2.1/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http@2.2.1/bundles/http.umd.js',
      '@angular/forms': 'npm:@angular/forms@2.2.1/bundles/forms.umd.js',
  
      'ionic-angular': 'npm:ionic-angular@2.1.0',
      'rxjs': 'npm:rxjs@5.0.0-beta.12',
      'ts': 'npm:plugin-typescript@5.2.7/lib/plugin.js',
      'typescript': 'npm:typescript@2.0.7/lib/typescript.js',
```

**Comment by AlanRezende** [comment]
Any updates about this issue?

**Comment by leoruhland** [comment]
Hey @ysgk and @AlanRezende!
 
I had this same problem and fix it this way:

```
ionViewDidEnter() {
    if (this.slides !== undefined) {
      this.slides.startAutoplay();
    }
}
ionViewWillLeave() {
    if (this.slides !== undefined) {
      this.slides.stopAutoplay();
    }
}
```

I hope it helps someone!

**Comment by pavei** [comment]
@leoruhland do you know how to do this on @Component?
