### ISSUE TITLE
issue(toggle): tapping the label should activate the toggle action.

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#10725]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On the Toggle control (http://ionicframework.com/docs/v2/components/#toggle) when you tap the `ion-label` in the `ion-item`, the `ion-toggle` does not activate the toggle and switch states.

This should work exactly as per the Checkbox control (http://ionicframework.com/docs/v2/components/#checkbox) when clicking/tapping on the `ion-label`. Or anywhere in the `ion-item`.

**Expected behavior:**
The toggle should be activated and switch states when it's `ion-label` is clicked/tapped.

```html
<ion-item>
  <ion-label> Sam</ion-label>
  <ion-toggle disabled checked="false"></ion-toggle>
</ion-item>
```

This occurs on version 2.2.0.

**Comment by manucorporat** [comment]
@dylanvdmerwe  just try a native iOS app. The toggle does not switch when you click the item, you have to click the toggle.

**Comment by Iyashu5040** [comment]
@manucorporat I just tested this on Android in WhatsApp, Facebook and Slack. All these apps switch the toggle when the items are tapped. So this should at least be enabled on this platform to ensure consistency.

And having it as an option for iOS would be very helpful since it would minimise the amount of precise tapping the user has to do. I'm sure you agree there's nothing more annoying than missing that small control my a fraction of an inch and having to try again until you hit it.

**Comment by dylanvdmerwe** [comment]
![toggle](https://cloud.githubusercontent.com/assets/2852839/23856922/f1930662-0803-11e7-95bb-4ec6cc14f804.gif)

I think it's mainly just a consistency issue between checkboxes and toggles. On a website when you have a <label> and a <input> when you click the label it also affects the input's checkbox/radio control.

**Comment by jgw96** [comment]
Reopening this for now as atleast on android (i need to test on iOS) toggles "toggle" when an item is clicked on. As it may be a little while before this hits in the framework (we are working on alot of other cool things at the moment, code-splitting (: (: (: (: ) as a workaround you can just bind to a click event on the item and then toggle a variable that the toggle is bound to from there.
