### ISSUE TITLE
VirtualScroll with radio-group

### ISSUE THREAD

**Issue by riccardotreagles** [ionic-team/ionic#10726]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If I select a radio on radio-group list with virtual scroller the selection is wrong. Virtual scroll reuses items and if you check a radio, also other items in the list are checked.

**Expected behavior:**
Correct selection of radio in radio-group in the list with virtual scroller

**Steps to reproduce:**
In this plunker http://plnkr.co/edit/hVLSKQF76ELJSaLq1PbT?p=preview4
you can see:

1. if you select the first item (my0), all it is ok.

2. If you select the 2nd "my1" item, and then if you scroll down, you can see that also "my60" is selected, and then if you scroll up, the selection on my1 disappears, or another item is selected.

3. If you select "my2" item and then you scroll, "my61" also is selceted.. etc...

All custom code is in:

pages/home/home.html
pages/home/home.ts

**Other information:**
the discussion on the ionic forum:
https://forum.ionicframework.com/t/virtualscroll-with-radio-group/80773/3

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by nnonimus** [comment]
@jgw96 facing the same issue with ionic 3 .Any work around which we could use?
