### ISSUE TITLE
bug(popup): Android back button does not dismiss the control

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#10724]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On Android, the DateTime control (http://ionicframework.com/docs/v2/components/#datetime) and the Select control (http://ionicframework.com/docs/v2/components/#select) that shows up can only be dismissed by tapping outside of the component or pressing the Cancel or Done buttons. 

**Expected behavior:**
The hardware back button should dismiss the controls as it would any other popup.

**Comment by dylanvdmerwe** [comment]
Note that I thought this had been resolved in the 2 RCs but obviously not.

**Comment by Iyashu5040** [comment]
Hi guys. I work in a team with Dylan, we were looking at an app I had put on a device with my machine.

Ionic Info:
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
OS: Windows 10
Node Version: v6.9.1
