### ISSUE TITLE
no-bounce doesn't work on iPhone SE

### ISSUE THREAD

**Issue by gustavosfq** [ionic-team/ionic#10734]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

when content is < screen work, when content is > screen doesn't work

**Expected behavior:**

a no-bounce screen in iPhone

**Steps to reproduce:**

https://github.com/gustavosfq/ionic2nobounce
 
i only create a new project and add "no-bounce" to ion-content

**Related code:**

**Other information:**

https://www.youtube.com/watch?v=1cQ3oCsk_50

this video have a list > screen

https://www.youtube.com/watch?v=M_piQ4cdh4g

this video have both cases

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
 

ps: sorry for my english :(

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this!

**Comment by Alex0x47** [comment]
Same issue on iPhone 6.

$ ionic info

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by peterpeterparker** [comment]
Related https://github.com/driftyco/ionic/issues/10329?
