### ISSUE TITLE
Flicker/Ghosting Issue on Over scrolling

### ISSUE THREAD

**Issue by scott-alvis** [ionic-team/ionic#10733]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When over scrolling buttons and images flicker or ghost, showing duplicate content.

**Expected behavior:**
No flickering or ghosting should occur.

**Steps to reproduce:**
The effect can be seen on the IOS simulator as well as on a physical device.

`ionic start --v2 flicker blank`

Add the code below to `src/pages/home/home.html`.

Run the application on the IOS simulator or a physical device.

`ionic build ios`

`ionic emulate ios --target=iPhone-6`

Swipe up over scrolling and the login button will ghost/flicker.
**Related code:**

src/pages/home.html

```
<ion-header>
  <ion-navbar>
    <ion-title>
      Ionic Blank
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <ion-icon name="md-person"></ion-icon>
  <ion-input type="text" placeholder="Username"></ion-input>
  <ion-icon name="md-lock"></ion-icon>
  <ion-input type="text" placeholder="Password"></ion-input>
  <button ion-button block>Login</button>
</ion-content>
```

**Other information:**
Removing the second ion-icon and ion-input resolves the issue.

If you add an image before the first ion-icon the same flicker/ghosting happens to the image when swiping down.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v6.1.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

Attached zip file is a mov demonstrating the issue.

[Flicker-Minimal.zip](https://github.com/driftyco/ionic/files/835152/Flicker-Minimal.zip)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We will look into this.

**Comment by oliverseddon** [comment]
I am having similar issues and have narrowed it down to Safari adding placeholder shadow dom elements.

If you remove the placeholder from one of your inputs the flickering will stop. It seems as though if more than one element uses the placeholder attribute the flickering/ghosting appears.

Hopefully this may point someone in the right direction in terms of resolving the issue.

**Comment by DrJonnie** [comment]
Hi, having the same problem and this issues is exactly the same as
described here:

[iOS bounce flicker glitch ](https://github.com/ionic-team/ionic/issues/11844)

**Comment by ahmadao** [comment]
Any news on this?

**Comment by mlynch** [comment]
Submitted a PR with a possible fix. Needs more testing to verify no regressions but it does remove the flicker. See PR #14265 for a code snippet you could patch your apps with if you wish.
