### ISSUE TITLE
Problem with ion-scroll and ion-segment

### ISSUE THREAD

**Issue by CarlosAdrianM** [ionic-team/ionic#10790]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I think that ion-scroll does not work properly with an ion-segment. If you explore in Chrome with Developer Tools, it is there, but it is hidden, not visible.

**Expected behavior:**
I would like to see the ion-scroll content like I see when I do not use ion-segment.

**Steps to reproduce:**
From this other issue:
https://github.com/driftyco/ionic/issues/7022

I have copied this Plunker that works well:
http://plnkr.co/edit/jSaeo3WemjWYMoCmEnwK?p=preview

But if I add a ion-scroll, you cannot see  the Puppies segment (I have only changed home.html with an ion-scroll):
http://plnkr.co/edit/lswCu6x2sObh2fXYd2Ks?p=preview

**Other information:**
I know that I do not need the ion-scroll in this particular case, but I have some components that have a ion-scroll inside them, and I cannot use them in a page with ion-segment (I use them with no problem in every other page with no ion-segment).

Conclusion: I cannot use a component with a ion-scroll inside, in a page that has a ion-segment. Am I doing something wrong or is it a bug?

Thank you

**Comment by datencia** [comment]
Hi all, I'm facing the same issue.

**Ionic info:**

```
global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by dimitri320** [comment]
Me too!
