### ISSUE TITLE
this.nav.getActiveChildNav().canGoBack() is not a function

### ISSUE THREAD

**Issue by kamok** [ionic-team/ionic#10793]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In my `app.component.ts`, I have a bit of code that sets timeout. I want to pop off the view, but only `pop` if that page can go back (if user is at a component that is not root). I try to access the current instance of the NavController with `this.nav.getActiveChildNav`), which does give me something not undefined. But I can't call `canGoBack()` on it for some reason.

**Expected behavior:**
It should let me call canGoBack(). Unless I am misreading the docs and not actually getting the active child nav instance.

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.9.1
```

**Comment by manucorporat** [comment]
what does `this.nav.getActiveChildNav()` return?

**Comment by kamok** [comment]
`Tabs {_config: Config, _elementRef: ElementRef, _renderer: DebugDomRenderer, _componentName: "tabs", _mode: "md"…}`

**Comment by paulsouche** [comment]
Hi,

I was in the same situation and the explaination is that this.nav.getActiveChildNav() return NavContainer[] and not NavController[] with tabs.

My feature was to display a confirm alert before exit app on back button. But I wanted to keep the possibility to pop navigation history before the alert.

Everything works fine with [this](https://github.com/ionic-team/ionic/blob/master/src/components/app/app.ts#L338)

Hope it helps

**Comment by Nick-lab** [comment]
@paulsouche not too much help when link expires
