### ISSUE TITLE
Setting min/max on datetime component does not work with 12-hour clock; am/pm column.

### ISSUE THREAD

**Issue by flivni** [ionic-team/ionic#10797]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Use 12-hour time with a am/pm column, and min/max time, e.g.

`<ion-datetime displayFormat="hh:mm a" min="01:20" max="13:45"></ion-datetime>`

Hours/minutes columns are not shown.

**Expected behavior:**
Hours/minutes columns should be displayed and limited to 01:20 am and 01:45 pm.

**Other information:**
I was working on a pull request that allowed specifying a min/max time. My code was obviated by https://github.com/driftyco/ionic/commit/afd99baba02a657667c970b43f12fc2941690103

I have some insight into how to fix.

1. You will need to adjust the 12 hour clock to run from 12 to 11 rather than from 1 to 12. I.e. [12, 1, 2, 3, ..., 10, 11]

2. You will need to check am/pm min/max values before checking hour values, i.e. between day and hour. 

I am happy to contribute a pull request that does this, but it will take me a few days because my old code is now incompatible with the new approach.

Thanks!

**Comment by flivni** [comment]
FYI, I just added a pull request for this: https://github.com/driftyco/ionic/pull/10812

**Comment by dannyf620** [comment]
`  <div *ngIf="!form.open24">
    <ion-item>
      <ion-label>Hora de inicio</ion-label>
      <ion-datetime [(ngModel)]="form.start" [max]="form.end" displayformat="HH:mm" pickerFormat="HH:mm"></ion-datetime>
    </ion-item>
    <ion-item>
      <ion-label>Hora de cierre</ion-label>
      <ion-datetime [(ngModel)]="form.end" [min]="form.start" minuteValues="[15,30,45,55]" displayformat="HH:mm" pickerFormat="HH:mm"></ion-datetime>
    </ion-item>
  </div>
  <ion-item>
    <ion-label>24 horas</ion-label>
    <ion-checkbox [(ngModel)]="form.open24"></ion-checkbox>
  </ion-item>`

`pickerFormat="hh:mm" A`

**Comment by sirin8** [comment]
Facing below when setting the min and max value for 12hr format

**Ionic version**
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2
global packages:
    Cordova CLI : 7.0.1
local packages:
    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.2.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.8.0
System:
    Android SDK Tools : 25.1.7
    Node              : v8.1.2
    npm               : 5.0.3
    OS                : Windows 7

_Issue:_ Not able to select the time for current date in the picker hh:mm:ss not displaying.

**Sample.html**
<ion-datetime displayFormat="MM/DD/YYYY hh:mm:ss A" pickerFormat="MM/DD/YYYY hh:mm:ss A" 
        [min]="startDatetimeMin"  [max]="maxAddDaysStartTime" ></ion-datetime>

**Sample.ts**
 this.startDatetimeMin = (new Date(Date.now() - (new Date()).getTimezoneOffset() * 60000)).toISOString();// set the current date time
        this.endDatetimeMax = (new Date((new Date(Date.now() - (new Date()).getTimezoneOffset() * 60000)).getTime() + 30 * 24 * 60 * 60 * 1000).toISOString()) // sets the  30 days from the current date time

![image](https://user-images.githubusercontent.com/16587658/36200774-c17de848-11a3-11e8-8337-1a54cc6c8374.png)
![iondatetimemin](https://user-images.githubusercontent.com/16587658/36200860-017e842a-11a4-11e8-8a63-4028ecaa2516.PNG)

**Comment by zeel91297** [comment]
Thanks a lot. It works!
