### ISSUE TITLE
Dynamically added tabs appear at wrong position

### ISSUE THREAD

**Issue by judithhartmann** [ionic-team/ionic#10805]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

In Ion Tabs I have a static tab at the front, then  a variable number of dynamic tabs using ngFor and then one final static tab.

Doing this at the moment causes the dynamic tabs to appear after the tab that should be at the end

**Expected behavior:**

Dynamic Tabs appear between static tabs, the position they get assigned in the code

**Steps to reproduce:**

https://plnkr.co/edit/0dQorbsCuRz5anQMLaob?p=preview (this is an older ionic version, but issue still exist in current version)

**Related code:**

```
<ion-tabs>
  <ion-tab [root]="tab1Root" tabTitle="Start Tab" tabIcon="pulse"></ion-tab>
  <ion-tab *ngFor="let tab of tabArray" [root]="tab1Root" [tabTitle]="tab" tabIcon="pulse"></ion-tab>
  <ion-tab [root]="tab1Root" tabTitle="End Tab" tabIcon="pulse"></ion-tab>
</ion-tabs>
```

**Other information:**

**Ionic info:**:

```
Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Thanks, we will look into this.

**Comment by digaus** [comment]
@judithhartmann 
Couldnt you just add the first and last tab to the tabArray to solve this?!

**Comment by judithhartmann** [comment]
@digaus 
Of course I could.
I just wanted to point out that doing something like I did will lead to unexpected behaviour and therefore is a bug that should be documented.

**Comment by btribouillet** [comment]
Hi,

I'm facing the exact same issue. 

However i'm having troubles as well when i add a new tab, edit or delete. Not sure it is related but it can be good to know while checking for this issue.

I described the issue on [stackoverflow](http://stackoverflow.com/questions/43440652/ionic-2-refresh-tabs-view-after-adding-a-new-dynamic-tab?noredirect=1#comment74044496_43440652) and [ionic forum](https://forum.ionicframework.com/t/refresh-tabs-view-after-adding-a-new-dynamic-tab/86757).

**Comment by shawnlan** [comment]
Having the same problem here!
