### ISSUE TITLE
Long press on ion-textarea to show "paste" menu does not work (android)

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [ionic-team/ionic#10800]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When long tapping on an ion-textarea using an android device, the keyboard disappears instead of showing the standard android overlay for pasting content.
I found a workaround by doing
```
ion-textarea .input-cover {
  display: none;
}
```
, knowing that this probably breaks something else.

**Expected behavior:**
The standard android overlay for pasting content should appear

**Steps to reproduce:**
create an ion-textarea somewhere and do a long tap on it on an android device

**Other information:**
[forum link](https://forum.ionicframework.com/t/textarea-paste-clipboard-content-on-long-press/82435)

**Ionic info:**

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.9
Node Version: v6.9.5
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. We will look into this.

**Comment by NoNameProvided** [comment]
I have the same issue, but using `display: none;` for `.input-cover` will break the blur on ion-inputs for ios, after leaving the input (by tapping something else) the input field will re-focus the input and pop-up the keyboard again. This only happens if you tab below the selected input field not above. (Which is really weird behaviour but I could not find find any reason for it.)

**Comment by jgw96** [comment]
Hello all, unfortunately, i cannot reproduce this issue on either a moto g running Android 4.4.4 or a Nexus 6 running Android 7.1.1. Could you guys create a minimal repo we could use to reproduce this issue?

**Comment by matheper** [comment]
Hello all, I had same problem and I looked for this for a long time.
I found the solution for my problem [here](https://github.com/ionic-team/ionic/issues/11438). Make sure `<ion-textarea>` in an `<ion-item>`.

**Comment by Vivek-abstract** [comment]
Thanks @matheper it worked. I think this issue should be closed now
