### ISSUE TITLE
Bug: Ion-Textarea toggles and losses focus everytime on tap

### ISSUE THREAD

**Issue by shyamal890** [ionic-team/ionic#10828]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Clicking/tapping on textarea toggles focus and keyboard. 

**Expected behavior:**
When tap occurs, if the focus/keyboard is not shown -> show keyboard and focus input. If the textarea has focus and keyboard is open -> tap on `ion-textarea` should not loose focus and close keyboard, instead should allow user to change the location of cursor and select text in textarea.

**Steps to reproduce:**
Just create a ion-textarea and try in android
-->

**Related code:**

```
<ion-textarea class="name-input"
                  placeholder="name"
                  [(ngModel)]="name"></ion-textarea>
```

**EDIT:** I tested by wrapping `ion-textarea` with `ion-item` and it works fine.

**Comment by jgw96** [comment]
Thanks, we will look into this.

**Comment by ejiyuan** [comment]
+1

**Comment by liugogal** [comment]
the same problem
+1

**Comment by bhavincb** [comment]
same problem in ionic 3.19.0
+1

**Comment by jakobwilkenson** [comment]
Any solution to this?

**Comment by pyummm** [comment]
confirm glitch also, 3.19.1

**Comment by madsheep** [comment]
https://github.com/ionic-team/ionic/issues/5744#issuecomment-404232682
