### ISSUE TITLE
bug: ion-toggle ngModel doesn't trigger checked

### ISSUE THREAD

**Issue by ZenSide** [ionic-team/ionic#10838]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Using [(ngModel)] with a ion-toggle component doesn't visually checked the component at start if binded value is true. [(ngModel)] attribute works fine but the component is not visually updated at load regarding its value.

Not checked at component load if myProperty is true
`<ion-toggle [(ngModel)]="myProperty"></ion-toggle>`

As a workaround, we can bind the "checked" attribute to the same property of the model. Is it supposed to be the right way to do it ?

Checked at component load if myProperty is true
`<ion-toggle [(ngModel)]="myProperty" [checked]="myProperty"></ion-toggle></span>`

<span is-issue-template></span>

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by plul** [comment]
I'm still having this issue on Ionic 3 FYI.

**Comment by almishlab8** [comment]
a better way to do that would be to bind the toggle to a property from your component by using **ngModel**

```
public isToggled: boolean;

constructor(...) {
  this.isToggled = false;
}

public notify() {
  console.log("Toggled: "+ this.isToggled); 
}

```
View:

`<ion-toggle [(ngModel)]="isToggled" (ionChange)="notify()"></ion-toggle>`

**Comment by jayzzz00** [comment]
i have same problem with ion-toggle the toggle button value are set properly but not visually set when i apply for checked then every time the ion-button set "on" visually

**Comment by leonardocoutinho** [comment]
I have the same problem,  [(ngModel)] and [checked] dont work together

**Comment by almishlab8** [comment]
@leonardocoutinho 
check 
https://github.com/almishlab8/ion-toggle-issue-

**Comment by leonardocoutinho** [comment]
@almishlab8 i have found a solutin a week ago, im only using [(ngModel)] to apply the boolean value from firebase data, and (ionChange) to change the value in firebase. In my example i discard the [checked] attribute
