### ISSUE TITLE
Touching more than one ion-range slider at a time will cause value of one to snap to the other

### ISSUE THREAD

**Issue by kbeirne** [ionic-team/ionic#10848]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When touching and moving 2 ion-ranges at the same time the value of the 2nd ion-range you touch will jump to the value of the first (according to the slider position). This means two ion-ranges can't be altered at the same time.

**Expected behavior:**
More than 1 ion-range should be selectable at a time. Each should be able to keep track of it's own value whilst you alter another.

**Steps to reproduce:**
Reproduced on android (don't know if it happens on iOS or other platforms) 

Instructions:
Press slider 1 with 1 finger and begin sliding to change it's value. Whilst it's held start sliding slider 2 with another finger. Slider 2 will keep jumping to the current value of Slider 1.
http://plnkr.co/edit/hloE1BfktOX8jdY9yu0R?p=preview

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Your system information:
 ordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.6.0
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello, thanks for opening an issue, we will look into this.
