### ISSUE TITLE
VirtualScroll: changes in bound properties of items only reflected after scrolling the list

### ISSUE THREAD

**Issue by szerner** [ionic-team/ionic#10849]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In a Virtual Scroll list, if a list item changes its visual appearence due to a users interaction (button click, some property binding on the item), that change is reflected only after some scrolling of the list.

**Expected behavior:**
The changes of the items visual representation should be reflected immediately after the items bound property has changed.

**Steps to reproduce:**
[plnkr](http://plnkr.co/edit/ToodtBYTiM9NVpWtDLZA?p=preview)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed
```

**Comment by arthurcaetanotb** [comment]
Getting the same issue with 3.2.0.

**Comment by batesy87** [comment]
I've got this too, I got a fairly big array with select boxes to filter. On each item is a + and - button with a quantity, everything works until the list is filtered, after that random items show the quantity increment until either another button is tapped or the list is scrolled.

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1
    cordova (Cordova CLI) : not installed
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2
    Android SDK Tools : 26.0.2
    Node              : v6.10.3
    npm               : 3.10.10
    OS                : Windows 10
    ANDROID_HOME : D:\Android\sdk
    backend : pro

**Comment by dpotoole** [comment]
Any update on this? Running into the same issue.
