### ISSUE TITLE
ion-textarea disappearing on focus when inside slide and inside modal

### ISSUE THREAD

**Issue by ilkkanisula** [ionic-team/ionic#10844]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Demonstrates modal with slides and ion-textarea disappearing when focused.

**Expected behavior:**
Text are keeps visible and shows cursor.

**Steps to reproduce:**
Checkout example posted in related code.
Do following steps:

 - Open modal
 - Click the "Type here" text
 - Text area disappers
 - Press any key on keyboard and textarea appears.
 - Click outside textarea to blur selection.
 - Click again to focus and ion-textarea should disappear again.

**Related code:**
https://github.com/ilkkanisula/iontextareaproblem

**Other information:**
Tested on Chrome osx and Android 6 emulator.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.6.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us! We will look into this.

**Comment by jayeshanandani** [comment]
Facing same issue with latest release of ionic 2.x

**Comment by vladtheimpala** [comment]
The only way I found was to put ion-textarea inside ion-row and ion-col like this : 
`<ion-row><ion-col col-12><ion-textarea></ion-textarea></ion-col></ion-row>`

**Comment by hananurrehman** [comment]
@vladtheimpala's solution works

**Comment by lordsteggu** [comment]
Wrapping the text area in the row and col works, but it then messes it up for android.

Has to do an *ngIf to show dependant on platform

Cheers
