### ISSUE TITLE
Menu scroll bug

### ISSUE THREAD

**Issue by iMiodrag** [ionic-team/ionic#10843]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

What you need to do, is:

1. Run this on a device(I have tested it on iPhone 6 Plus ios 10.2)

**Expected behavior:**

The scroll on the menu doesn't work
**Steps to reproduce:**

1. Run on device 
2. swipe to the second slide
3. go to the menu
4. Try to scroll up/down.. the scroll doesn't work
5. The bug is here: ```<div style="height:calc(100vh - 200px);background:blue"> ```
If you remove the height the menu scroll works

**Related code:**

```
The code is here: https://github.com/iMiodrag/ionic-menu-bug
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.0.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Unfortunately I cannot reproduce this issue, could you share a plunker or repo we could use to reproduce this?

**Comment by iMiodrag** [comment]
1. The code is here: https://github.com/iMiodrag/ionic-menu-bug just compile it and run it on the device.

2. Swipe to the second or third slide, click on the menu and try to scroll up/down, the scroll on the menu won't work.

This bug is only on device.

I will try to make a video

**Comment by iMiodrag** [comment]
@jgw96 Here is the video, you need to swipe and after that open the menu and you will see that the scroll doesn't work https://screencast.com/t/EldIM04N

**Comment by AmitMY** [comment]
I can't scroll the menu, on android, with latest version (3.0.1)

**Comment by manucorporat** [comment]
@iMiodrag looks like this is one more of the scroll bugs associated with UI.
The ion-scroll is being the ion-menu and the scroll events are not being focused in the menu, but the ion-scroll behind it

I have tried several ideas like: `pointer-events:none` but it didn't make the trick.

Why are you still using UI? what is stopping you to start using WK?

**Comment by iMiodrag** [comment]
@manucorporat 
I'm new to ionic so, I have used what I found based on the documentation and what was provided by default. So I assume I can use WKWebView as a plugin or something? Can you give me an url where I could find more for this setup? Thank you!

**Comment by AmitMY** [comment]
You can read about it here, it seems very simple to use:
https://www.npmjs.com/package/cordova-plugin-wkwebview

@manucorporat because the bug also happens on android, I don't think that is the problem.. (but what do I know ;)

**Comment by manucorporat** [comment]
@iMiodrag 
Try this one: https://github.com/driftyco/cordova-plugin-wkwebview-engine
The official's repo has many issues.

@AmitMY so it is a combination of ion-slides + ion-scroll + ion-menu, right?

**Comment by AmitMY** [comment]
@manucorporat not sure.. this happens for me on `ion-menu` only, other stuff do scroll.

**Comment by manucorporat** [comment]
@AmitMY does it happen always in `ion-menu`? you never can scroll on ion-menu? because that way, it is a completely different bug

**Comment by AmitMY** [comment]
@manucorporat  That is correct. On android (Galaxy S4 5.0.1) I can never scroll, while in any other scrollable thing I can. If this is not this bug, I will try and find more info, and create a new issue.

**Comment by iMiodrag** [comment]
For me the solution was to set the menu to "overlay" and the scroll works @AmitMY  @manucorporat
