### ISSUE TITLE
bug: Slides Component Display Issues on Remove Slide

### ISSUE THREAD

**Issue by matthew-valenti** [ionic-team/ionic#10846]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>

plnkr: http://plnkr.co/edit/fosgnU4V2NKGCwFcyULx
Couldn't find latest Ionic 2 plnkr but this is at least a recent version and has the same behavior as the latest version.

Slide component is data bound to an array.

```
<ion-slides>
    <ion-slide *ngFor="let product of products">
```

We remove the first item in the array.

```
this.products.shift();
this.slides.update();
```

Slider automatically jumps to the next slide (without sliding). Would not expect the slides component to automatically display a new slide unless the the visible slide is the one being deleted.</span>

If the last slide is visible and the first slide is removed then the entire slide component is hidden.

<span is-issue-template></span>

**Comment by aydus-matthew-valenti** [comment]
Work around. Remove item from array and immediately call slidePrev with speed = 0.

```
this.productSets.shift();
this.slides.slidePrev(0);
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic, we will look into this!

**Comment by xenogenesi** [comment]
I believe I'm having a similar issue for the same reason, my template also use `*ngFor` but I'm inserting 10 Slide to the beginning. I think any shift/unshift could leave the slide component displaying the wrong Slide, if I understand correctly the current [Slides::update()](https://github.com/ionic-team/ionic/blob/master/src/components/slides/slides.ts#L931) implementation call [swiper::update()](https://github.com/ionic-team/ionic/blob/master/src/components/slides/swiper/swiper.ts#L597) without any value for the optional `updateTranslate`, but evaluated to false there's no left adjustment on the update

**Comment by dannyconquer** [comment]
stop! Please




At 2017-07-04 20:30:17, "xenogenesi" <notifications@github.com> wrote:


I believe I'm having a similar issue for the same reason, my template also use *ngFor but I'm inserting 10 Slide to the beginning. I think any shift/unshift could leave the slide component displaying the wrong Slide, if I understand correctly the current Slides::update() implementation call swiper::update() without any value for the optional updateTranslate, but evaluated to false there's no left adjustment on the update

**Comment by dalezak** [comment]
Unfortunately the suggestion above with `this.products.shift();` only works if you are removing the first item, it doesn't work if you'd like to remove a slide in another position. This worked for me:

```
let index = this.slides.getActiveIndex();
if (index == 0) {
  this. products.shift();
  this.slides.slideTo(0, 0, true);
}
else {
  this. products.splice(index, 1);
  this.slides.slideTo(index-1, 0, true);
}
```

**Comment by izakblom** [comment]
@dalezak Solution worked for me as well. Thanks

**Comment by asimon91** [comment]
> Unfortunately the suggestion above with `this.products.shift();` only works if you are removing the first item, it doesn't work if you'd like to remove a slide in another position. This worked for me:
> 
> ```
> let index = this.slides.getActiveIndex();
> if (index == 0) {
>   this. products.shift();
>   this.slides.slideTo(0, 0, true);
> }
> else {
>   this. products.splice(index, 1);
>   this.slides.slideTo(index-1, 0, true);
> }
> ```

Thank you for this workaround, works as expected!
