### ISSUE TITLE
ion-split-pane conflict with video fullscreen mode

### ISSUE THREAD

**Issue by nampdn** [ionic-team/ionic#10851]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I'm building video app using ionic2. Everything goes fine when I play video without fullscreen mode. If I switch to fullscreen mode then all screen is totally in black.

**Expected behavior:**

Video can display in fullscreen when use ion-split-pane component.
**Steps to reproduce:**

**Related code:**

```
    <ion-split-pane when="md">
       <ion-menu [content]="content">
        <ion-header>
          <ion-toolbar color="primary">
            <ion-title>Play list</ion-title>
          </ion-toolbar>
        </ion-header>
        <ion-content>
        </ion-content>
      </ion-menu>
      
      <ion-nav #content [root]="rootPage" main></ion-nav>
    </ion-split-pane>
```
```
//I place video inside tabs
<video #video
       width="100%"
       autoplay
       controls>
</video>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.0.0
Xcode version: Not installed
```

**Comment by klemensz** [comment]
Same issue here. Since using <ion-split-pane> the video isn't visible in fullscreen any more. In our case the page becomes completely white.

**Comment by phamduongnhatnam** [comment]
Hi @klemensz, do you have any update on this?

**Comment by klemensz** [comment]
@phamduongnhatnam No... but haven't updated to Ionic 3 yet (don't know if this would help).

**Comment by alesgenova** [comment]
I noticed the same issue.
In firefox the video goes fullscreen correctly, in chrome/chromium instead I see a white/gray screen.
Has anyone found a workaround?

**Comment by lgmnemesis** [comment]
This is still open 👎 
Is there any time frame for working on this issue?
thanks.

**Comment by pcgeonet** [comment]
Ionic3 same issue

**Comment by alexvibealex** [comment]
same issue any solution anyone please

**Comment by alexvibealex** [comment]
Sorry to bother you again but this is a serious issue for me . Any solution on this one please?

**Comment by klemensz** [comment]
Still an issue with Ionic 3.9.2.

**Comment by NTXAggie** [comment]
verifying this is still an issue on 3.9.2....Is there any ETA on this fix?

**Comment by Spartanace1024** [comment]
Same problem here

**Comment by NTXAggie** [comment]
@Spartanace1024 Fixed it for me
