### ISSUE TITLE
ion-toggle capable of entering a buggy state on EMU/device

### ISSUE THREAD

**Issue by marcthomsen** [ionic-team/ionic#10872]
**Ionic version:** 
[x] **2.x**

**I'm submitting a ...** 
[x] bug report

**Current behavior:**
The toggle button is able to enter a buggy state which can be demonstrated by making a button that has a disabled attribute linked to the state of the toggle. 
Clicking in a small limited area around the toggle causes the toggle to enter a state which happens to inverse the synchronization with the button.

The bug has been observed in these emulators: 
- iPhone SE on iOS 10.2
- Galaxy Nexus on Android 7.0.

and on these devices: 
- iPhone 6 Plus on 10.2.1
- Samsung Galaxy S5 on Android 6.0.1. 

![inverse on-off behavior](https://cloud.githubusercontent.com/assets/7867908/24095183/2f6d2172-0d5c-11e7-92f8-0caa20ee1625.png)

**Expected behavior:**
The toggle should not be able to enter this buggy state when clicking just outside the toggle button.

**Steps to reproduce:**
Deploy the related code snippet to either of the above mentioned devices, emulated or physical. Since this bug occurs when hitting inside a small limited area outside the toggle the easiest way to reproduce this bug is to emulate an iPhone and scale the window of the emulator to 100 % to make the area where the toggle is able to enter the buggy state - as large as possible. 

![reproduce bug](https://cloud.githubusercontent.com/assets/7867908/24104477/95b3e9fe-0d82-11e7-9e3d-70bca729a422.png)

**Related code:**
Below is a simple ion-toggle as well as an ion-button with a disabled attribute linked to the state of the toggle:

<ion-content>

    <ion-item>
        <ion-toggle checked="false" [(ngModel)]="toggleState"></ion-toggle>
    </ion-item>

    <button ion-button [disabled]="!toggleState">Continue</button>

</ion-content>

**Ionic info:**
Cordova CLI: 6.5.0 
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by marcthomsen** [comment]
Hi @jgw96 
Do you know if this issue has been solved in some version of Ionic 3?
