### ISSUE TITLE
Slides height not updated

### ISSUE THREAD

**Issue by mbakker96** [ionic-team/ionic#10891]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`resize` function is not working. The only update the height when triggering a swipe. 

The calendar hides the inactive weeks with `*ngIf`

**Expected behavior:**
slide automatically updates the height. 

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.3 Build version 8W143q

```

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/10044261/24258301/9a126e72-0fed-11e7-944b-c3b95c8167a4.gif)

**Comment by mbakker96** [comment]
@jgw96 Problem is also in v3

**Comment by medst** [comment]
slides not resize in v2 and v3

**Comment by mbakker96** [comment]
@medst By me it resize it self only when I trigger something of the calendar. Like a swipe.
