### ISSUE TITLE
Ionic input api issue with value and FormArray

### ISSUE THREAD

**Issue by cambronjay** [ionic-team/ionic#10895]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If you use Angular 2 FormArray with ionic inputs to interpolate date into the value attribute of an ionic input or ion-textarea it will not work and will make the value undefined. 
**Expected behavior:**

When using FormArray the data interpolated into value should stick and appear in the input box as the initial value.  If the data is interpolated into the actual input and not the value attribute then it will work for ion-input, but nothing works for ion-textarea
**Steps to reproduce:**

**Related code:**
```
  <form [formGroup]="myForm">
    <div formArrayName="formQuestions">
    <ion-list *ngFor="let question of formQuestions.controls; let i = index" [formGroupName]="i">
      <ion-input placeholder="Enter comment" formControlName="Comment1">{{detail.Comment}}</ion-input>

<ion-input placeholder="Enter comment" formControlName="Comment2" value="{{detail.Comment}}"></ion-input>

      <ion-textarea formControlName="Comment3" value="{{detail.Comment}}" placeholder="Enter comments"></ion-textarea>

<ion-textarea formControlName="Comment4" placeholder="Enter comments">{{detail.Comment}}</ion-textarea>

    </ion-list>
    </div>
</form>
```

**Other information:**

https://angular.io/docs/ts/latest/guide/reactive-forms.html#!#form-array

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 1.0.0
OS: Windows 7 SP1
Node Version: v6.9.1
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. We will look into this (:

**Comment by cambronjay** [comment]
No problem @jgw96  I am always happy to help out the ionic team.
