### ISSUE TITLE
DateTime picker opens with wrong values on certain conditions

### ISSUE THREAD

**Issue by hcsalis** [ionic-team/ionic#10908]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
DateTime picker opens with wrong values when both of these conditions are met:

- model has time value between '00:00' and '00:59' (e.g. '00:27', '00:27Z', '2017-03-24T00:27')
- picker format is an 12-hour format (e.g. 'h:mm A', 'h:mm a', 'YYYY-MM-DD h:mm A')

_example:_
when data bound to ngModel is '00:27' and picker format is 'h:mm A', picker opens as '1:27 am'

**Expected behavior:**
when data bound to ngModel is '00:27' and picker format is 'h:mm A', picker should open as '12:27 am'

**Steps to reproduce:**

[plunkr with reproducer](http://plnkr.co/edit/HpJjViBNDvGJpxS84cB0?p=preview)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
iIonic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.7.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this (:

**Comment by flivni** [comment]
Fyi, this issue also resolved by: 
https://github.com/driftyco/ionic/pull/10812

@jgw96 - I would love if someone could take a look at this pull request.
