### ISSUE TITLE
Tab bar highlight needs workaround for Chrome bug

### ISSUE THREAD

**Issue by Lingomat** [ionic-team/ionic#10915]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**

With current desktop Chrome including up to the latest Canary build, Ionic Tabs tabsHighlight = true will render a highlight bar under/over a tab button and this position is incorrect. The highlight bar extends further to the right than expected, partially underneath the next tab. 

**Expected behavior:**

The highlight bar should only be under the current tab bar button.

**Steps to reproduce:**

Any instance of the tab bar on Chrome will show this effect. The effect can be observed in the standard Ionic tabs starter project once you edit tabs.html to add  tabsHighlight = true.

**Related code:**

When Tabs tabsHighlight = true, the tab-highlights.js part of the tabs component transforms and scales a div to achieve the highlighted bar effect (line 16). This works correctly and can be verified by mousing over the element with the element selector to find the <div class="tab-highlight animate">.

**Other information:**

This would appear to be a Chrome bug. E.g. the background for an element is rounded outside of the actual bounding box. It works as expected on Firefox. It seems that a fix would need to use another method other than setting a div to 1px and scaling by x * pixels. 

```
    Cordova CLI: 6.3.1
    Ionic Framework Version: 2.0.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.5.0
    Xcode version: Not installed
```

**Comment by Lingomat** [comment]
For anyone that cares, this is a ridiculous hack to get it working:
```
<ion-tabs  (ionChange)="selectedTab()">
  <ion-tab [root]="tab1Root" tabIcon="home"></ion-tab>
  <ion-tab [root]="tab2Root" tabIcon="search"></ion-tab>
  <ion-tab [root]="tab3Root" tabIcon="map"></ion-tab>
  <div *ngIf="isTab" class="highlight"
    [style.width]="highlight.width"
    [style.left]="highlight.left"
    [style.top]="highlight.top">
  </div>
</ion-tabs>
```
And in the tabs page:
```
  highlight: {left: string, top: string, width: string}
  isTab: boolean = false
  selectedTab() {
    let thisTab = this.tabRef.getSelected()
    let fbox = thisTab.btn.getNativeElement().getBoundingClientRect()
    this.highlight = {
      left: fbox.left+'px',
      top: fbox.bottom-2+'px',
      width: fbox.width+'px'
    }
    this.isTab = true
  }
```
and with CSS:
```
  .highlight {
    position: absolute;
    height: 2px;
    background: color($colors, light);
    transition-duration: 300ms;
    transition-timing-function: ease;
    z-index: 100;
  }
```

You'd also need to run selectedTab() on orientation change. Sigh :)

**Comment by bushybuffalo** [comment]
I have been experiencing the same problem (using Ionic 3.5.3), it happens only when I'm using Chrome (59.0.3071.115)  - I tested it on Firefox and Edge and it worked fine.

I also noticed that I can reproduce this bug only when Windows' scaling is set up to more than 100%. The highlight is smaller than expected when set to 125%, and bigger when set to 150%. or 175%.

![](https://www.thurrott.com/wp-content/uploads/2015/07/change-the-size.jpg)

**Comment by Lingomat** [comment]
You are right! I had another look at this and noticed it was fine on mobile. Given this affects just one buggy browser on one OS, with one OS setting. It's probably such an edge case that this issue should be closed.

**Comment by bushybuffalo** [comment]
Well, I'd rather see it fixed than ignored, the project I'm currently working will be running on Windows tablets with this particular zoom setting, and the browser required by my client is Chrome,..

So if the Ionic team is not able to solve this issue, I'll have to stick with a dirty workaround :(
