### ISSUE TITLE
ionic2 status bar non transparent background

### ISSUE THREAD

**Issue by msolima** [ionic-team/ionic#10922]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I do NavCtl.push(Page), the next page opens up with a statusBar that has a white background and all content is pushed down althought I have StatusBar.overlaysWebView(true);

<img width="335" alt="screen shot 2017-03-26 at 3 57 12 pm" src="https://cloud.githubusercontent.com/assets/5561372/24334726/c338e6f8-123d-11e7-88cb-d5cab263ed50.png">

**Expected behavior:**
The statusBar should be transparent and should be overlapping with the content.
<img width="339" alt="screen shot 2017-03-26 at 4 03 13 pm" src="https://cloud.githubusercontent.com/assets/5561372/24334727/c339b920-123d-11e7-98b0-72db3d4e4cb6.png">

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by sfaizanh** [comment]
**config.xml**
`<preference name="Fullscreen" value="true" />`

**Component.ts**
`StatusBar.overlaysWebView(true);`

https://ionicframework.com/docs/v2/native/status-bar/

**Comment by msolima** [comment]
This will make the app full screen and hide the status bar completely.
Any way around that?
