### ISSUE TITLE
Ion-navbar not transitioning some icons in iOS mode

### ISSUE THREAD

**Issue by benharpers** [ionic-team/ionic#10934]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In iOS mode, when transitioning from one page to another, especially if you are swiping and can do it slowly, some icons in the navbar do not transition, rather they just get cut-off by the page that is transitioning.

![img_0066](https://cloud.githubusercontent.com/assets/583258/24366487/1cf25a90-12ce-11e7-9a4a-4f6e2bd0170d.PNG)

**Expected behavior:**
The icons in the navbar should fade out as the new pages icons fade in.

**Steps to reproduce:**
View this demo:
http://plnkr.co/edit/OrlG51?p=preview

Click the gear at the top right, then click back and watch the area where the gear was.

**Related code:**
Code is on Plunker, also on the forum:
https://forum.ionicframework.com/t/ion-navbar-not-transitioning-some-icons-in-ios-mode/84166

**Other information:**
n/a

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002



******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Unfortunately I cannot reproduce this issue, would you mind sharing a repo we can use to reproduce this?

**Comment by benharpers** [comment]
If you look at the plunker it couldn't be more simple just two pages in iOS mode click the gear and then swipe back slowly so you can control the transition and watch the gear get cut by the second page during the back swipe. Or record the back putting and play back the recording slowly and you'll see the gear doesn't fade. Happens on safari on desktop and on mobile

http://run.plnkr.co/yffBWs6WjAJVAhpH/

Let me know if you still don't see the issue. It's not a perminent issue on the screen, it's just during the swipe or back animation that you see it.

**Comment by benharpers** [comment]
Sorry typo above putting = button

**Comment by benharpers** [comment]
![out](https://cloud.githubusercontent.com/assets/583258/24387518/62f96054-132a-11e7-80da-98fbf00a3970.gif)

See above, watch when back button is clicked, gear doesn't fade in, it just appears from behind the previous page.
