### ISSUE TITLE
bug(input): Inputs misbehave on saved passwords

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#10944]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When for example, going to https://apps.ionic.io/login and logging in, then telling chrome to remember your password, when trying to login again, the password label is not floating.
![image](https://cloud.githubusercontent.com/assets/5757359/24403409/6a6bdd1c-13c5-11e7-83b7-80b642b2564c.png)
Every focus around the page fixes it.

**Expected behavior:**
Floating label, like for email

**Other information:**
This issue happens since v2, 
Chrome/Windows:
>"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
  Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.0-beta.2
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.1
    Xcode version: Not installed

```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! So is this an issue with the framework or the `apps.ionic` site? Sorry, just a little confused if your just using the apps site as an example or if its an issue with the framework.

**Comment by AmitMY** [comment]
Sorry for being vague.
This is an issue with the framework. It was not introduced with the new version, but existed for at least 3 months now.

The ionic website is just an example, because it is easier than making a repro plunker or something.

**Comment by mebibou** [comment]
I am using ionic `3.7.0` and the issue is still present. I am deploying the app as a website, i.e. using the `www` folder directly on Chrome. I am setting this in the form:
```
<ion-item>
  <ion-label floating>Password</ion-label>
  <ion-input type="password" formControlName="password" required></ion-input>
</ion-item>
```
When the page loads, if the password was saved and autocompleted by the browser, the floating label stays on top on the input. This does not happen when using `<input type="email">` for example.

Here's what it looks like:
![preview](https://user-images.githubusercontent.com/305342/31053117-4ce638b4-a696-11e7-9db6-5616479aa308.png)

**Comment by aleksander351** [comment]
@jgw96 for me it is the same as with @mebibou . But the same is happening also with the email field.

![login-issue-chrome](https://user-images.githubusercontent.com/7508670/44587659-e8b59900-a7b3-11e8-8b94-de7e0d000b6b.png)
