### ISSUE TITLE
Chip: Icon button positioned out of place in iOS 9

### ISSUE THREAD

**Issue by FdezRomero** [ionic-team/ionic#10956]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When a chip contains a button with an icon, it is rendered off to the left of the button area in iOS 9 WKWebView and Safari. The icon is correctly centered in iOS 10 and Safari on macOS.

Screenshot (check the close icons in the chips under "Delete Chips"):

![image1](https://cloud.githubusercontent.com/assets/1807985/24431072/340d8d88-141a-11e7-8232-2ce5cfeb49c3.PNG)

**Expected behavior:**
Icon to be horizontally centered inside the button, as they do in the other browsers.

**Steps to reproduce:**
1. Open Safari on iOS 9 (the Simulator might work).
2. Navigate to the official Chip demo at https://ionicframework.com/docs/v2/demos/src/chip/?production=true&ionicplatform=ios
3. Scroll down to the "Delete Chips" area.

**Related code:**
```
  <ion-chip #chip1>
    <ion-label>Default</ion-label>
    <button ion-button clear (click)="delete(chip1)">
      <ion-icon name="close-circle"></ion-icon>
    </button>
  </ion-chip>
```

**Other information:**
Looks that it may be related to flexbox. I tried overriding some styles but wasn't able to fix it.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

``` 
    Cordova CLI: 6.5.0
    Ionic Framework Version: 2.3.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: 1.9.1
    ios-sim version: 5.0.13
    OS: macOS Sierra
    Node Version: v6.10.1
    Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will look into this.
