### ISSUE TITLE
ion-range dualknobs bug

### ISSUE THREAD

**Issue by vsebastian6** [ionic-team/ionic#10950]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The bug appear when i assign dualknobs ion-range to a form. I've tried with template driven form and model driven and have the same problem

**Steps to reproduce:**
http://plnkr.co/edit/AkYp4Jjd14nJrT2qp3K2?p=preview

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will look into this.

**Comment by Labcowork** [comment]
Hi friend ... I had the same problem. Try it this way .. I'm sure it will work.  i used latest version
try with this in the .html :

<ion-range dualKnobs="true" [(ngModel)]="knobValues" min="21" max="72" step="3" snaps="true"></ion-range>

and try with this in the .ts

knobValues: any = {
  upper:100,
  lower:50
}

It should work now.

**Comment by AmitMY** [comment]
@jgw96 Can't reproduce with current form controls.
