### ISSUE TITLE
ion-datetime ng-valid handling inconsistency 

### ISSUE THREAD

**Issue by gregd** [ionic-team/ionic#10952]
**Ionic version:**  (check one with "x")
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report

**Current behavior:**
Please take a look at attached picture. Validation css classes are applied to ion-input outer ion-item. But in case of ion-datetime they are not reflected in outer ion-input.

**Expected behavior:**
The behavior should be consisted. So if there is green underline for ng-valid ion-input fields then ion-datetime should also have that green underline.

**Steps to reproduce:**
http://embed.plnkr.co/dNQal7/

**Other information:**
The problem was already described here https://github.com/driftyco/ionic/issues/7270

![datatime-ng-valid](https://cloud.githubusercontent.com/assets/59068/24416701/f8ed91e6-13e5-11e7-92bd-7126f21e03ba.png)

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by bogomips** [comment]
I noticed ion-select has excatly the same wrong behaviour

**Comment by hugoblanc** [comment]
Still present with ionic 3.20

**Comment by ricardoparro** [comment]
this is still a problem. a very annoying one.
