### ISSUE TITLE
ion-tabs: select() doesn't immediately set active state on initialized ion-tab

### ISSUE THREAD

**Issue by metz0r** [ionic-team/ionic#10975]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When a tab that's already been initialized (clicked) is selected again programmatically with Tabs::select() the tab content is rendered but the tab button itself is not active until some other action repaints the view.  
Note that if switching to a tab for the first time this works as it should.

**Expected behavior:**
The tab button should gain active state immediately.

**Steps to reproduce:**
Scenario: 2 tabs, index 0-1

1. Open app, tab 0 is active by default
2. Click tab 1
3. Click tab 0
4. Call Tabs::select(1)
5. The contents of tab 1 is now rendered, but the tab itself remains inactive until something triggers  a repaint. The ionChange() event is called as it should.

**Related code:**

`ionic start --v2 myApp tabs`
tabs.html: add tab ref: `<ion-tabs #tabs ..`
tabs.ts: declare tab ref: `@ViewChild('tabs') tabRef: Tabs;`
tabs.ts: declare helper function in constructor: `(<any>window).switchTab = (index: number) => this.tabRef.select(index);`

call this function from browser console in reproduction step 4: `switchTab(1);`

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.3 Build version 8E162

**Comment by metz0r** [comment]
A workaround is to call ApplicationRef.tick() after the select()

**Comment by nonamez** [comment]
Same bug for me.

**Comment by dima-gusyatiner** [comment]
I stumbled upon this issue as well.
I have a button on a side menu, that should navigate to a page, that has to be a child page of a tab.

I think `tabsRef.select()` should be an Observable.
Calling `tabsRef.getSelected().push()` right after does not behave as expected. This is because `tabsRef.getSelected()` holds the previous tab at this point, and not the new one yet.

For now a have a dirty workaround with setTimeout.

**Comment by machadoapoena** [comment]
@dima-gusyatiner  Im with the same problem here. Timeout works like you told. Any news about how to solve this?

**Comment by kuklyuk** [comment]
Another approach that works perfect for me.
In HTML:
<ion-tabs [selectedIndex]="getSelectedIndex()">
...
</ion-tabs>

In .TS we must define getSelectedIndex() function, that returns integer, the index of the tab, that must be selected.
So we can pass a param, which page must be initially selected, then get that param in the constructor of the tab page component, for example:
this.currentTab = this.navParams.get( "currentTab" );
And then return that param from getSelectedIndex function.
Works without delay.

**Comment by darkguy2008** [comment]
@metz0r solution worked, Sep 2018

**Comment by kevinpallado** [comment]
@metz0r can you show some snippet on how to apply on it? thanks best regards

**Comment by fradali** [comment]
Hi, is there a solution for this problem ? I tried the timeout solution and ApplicationRef.tick() also, but it didn't work (ionic v3.9.2).
Thanks.
