### ISSUE TITLE
ion-content: tabbar height miscalculation when using multiple ion-tabs 

### ISSUE THREAD

**Issue by metz0r** [ionic-team/ionic#10978]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using 2 ion-tabs on a page (with them having differing heights), the margin calculation for ion-content is incorrect.

**Expected behavior:**
The ion-content should have the correct margin set, based on the height of the closest ion-tabs.

**Steps to reproduce:**
1. Create a starter tabs app
2. Add more tabs with tabsPlacement="top"
3. Make the bottom tabs larger than the top tabs
4. The ion-content margins are incorrect for the top tabs

**Related code:**
See repo: https://github.com/metz0r/ionic-issue-myApp-1
PR on the way

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.3 Build version 8E162

**Comment by tezcane** [comment]
Here is a workaround:
```
home { // your selector name
  ion-tabs .tabbar {
    max-height: 30px; //set pixels here
  }
}
```

**Comment by lpsantana** [comment]
tab-bar really a problem in ionic
