### ISSUE TITLE
ActionSheet - No styling for subTitle

### ISSUE THREAD

**Issue by mgreenwood11** [ionic-team/ionic#10983]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When presenting an action sheet that includes a subTitle, that subtitle gets displayed with no styles applied to it.

**Expected behavior:**
The subtitle should be styled in a way that works well with each platform.

**Steps to reproduce:**
Just use an action sheet with a subtitle like the one in this example
http://plnkr.co/edit/JEyebc?p=preview

**Related code:**

**Other information:**
I plan on submitting a pull request to fix the issue

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
Your system information:

 ordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will look into this.

**Comment by Remco75** [comment]
any updates on this? Im running into this as well

**Comment by Remco75** [comment]
And to add, the subtitle is added as a separate element. I would expect the title and the sub-title to be in one element or group for easy styling

**Comment by vveerrgg** [comment]
From what I can see in the code, it looks like the title has all the attributes for it, but the sub-title does not have any attributes defined or set to a default.

I haven't gotten it working,... but I think it's in the actual component code itself, and not in what we're doing within the templates. 

I would look for the action scss files for the actual component:
- action-sheet.ios.scss
- action-sheet.md.scss
- action-sheet.wp.scss

**Comment by Remco75** [comment]
Yeah I think it would be pretty easy to fix. @jgw96 can you confirm that this is actually a bug, and would you accept a PR from my side to fix it?
