### ISSUE TITLE
bug - the no clicking zone

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#10985]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In many components having `(click)` set for them, or  just regular activity, a click on the padding of those elements triggers the click animation (iOS grey something, android ripple effect), but does not trigger the event set.
This is frustrating as it is a horrible UX, for the click effect to show, but the click to not register.
*No, `tappable` does not fix it.
Short video:
https://i.gyazo.com/429deceeb5ad3ade66c8c92ef1149d4c.mp4

**Expected behavior:**
When clicking on an element, even on padding, the click effect should take place.
There can not be a situation in which a click animation is shown, but action is not happening.

**Steps to reproduce:**
Create some tabs, then click where the cursor is just above the border-bottom, but not on the text.

**Additional Info:**
This is not just a problem with tabs. It happens in other places too

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.0-beta.3
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.1
    Xcode version: Not installed
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by jasonfairhead** [comment]
Does this happen only on child pages and when you are clicking near the middle of the element/screen?

**Comment by AmitMY** [comment]
@jasonfairhead No, can be on root pages, and in the top or bottom as well

**Comment by Cheng007** [comment]
This issue still exist 3.3.0，when can fix this?

**Comment by AmitMY** [comment]
I did some testing, and it seems like the angular `(click)` event. It will only fire if the entire cursor is inside the element. Not sure why is that, but at least I now think it is not a problem with ionic and is a problem with angular itself.

The animation (ripple-effect) happens unrelated to the click, but on `pointerDown` and `pointerUp` events on the element.

**Comment by jrmlt** [comment]
So... had the same issue. I tried to investigate a little bit more but yeah it seems it is related/not related to ionic due to the use of `pointerDown` and `pointerUp`. Using `(tap)` seems to bring a consistency between event handler and ionic `activated` state and ripple effect.
