### ISSUE TITLE
Loading widget doesn't show text content in slow network conditions

### ISSUE THREAD

**Issue by cfjedimaster** [ionic-team/ionic#11007]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm using a Loading widget with text in the content value. When I use Chrome DevTools network throttling it works as expected, UNTIL I select GRPRS, and then the widget works, but with no text, just a circling icon. You can see space for the text, but it doesn't show up.

Video: https://www.youtube.com/watch?v=bugRptk91HQ

**Expected behavior:**
I'd expect the text to show up.

**Steps to reproduce:**
Open DevTools, enable throttling, and compare 2G to GRPS.

**Related code:**

Just a vanilla use of Loading with content:'stuff'

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Can't copy and paste as it's on another machine - so pardon any typos:
Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
ios-deploy version: 1.9.1.
ios-sim version: 5.0.13
OS: OS X El Capitan
Node Version: v6.1.0.1
XCode version: XCode 7.3.1. Build version 7D1014

**Comment by jgw96** [comment]
Hmm, thats an interesting issue. Thanks for opening this, we will look into this.
