### ISSUE TITLE
Windows - hardware back button problem

### ISSUE THREAD

**Issue by almost92** [ionic-team/ionic#11016]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Windows - hardware back button stops working after clicking it once while on root pages (exists/suspends)

**Expected behavior:**
back button should always work

**Steps to reproduce:**
starter tab project (ionic start --v2 myApp tabs).

1. build for windows and deploy on a windows device.
2.  then click back button on one of the root pages (app goes to background).
3. open the app from background
4. click back button again

after some debugging, I think the code that generates the problem is in Platform implementation:
```
var Platform = (function () {
    function Platform() {
..
..
        this.backButton.subscribe(function () {
            // the hardware back button event has been fired
            (void 0) /* console.debug */;
            // decide which backbutton action should run
            _this.runBackButtonAction();
        });
    }
```

on Windows, an exception is thrown when trying to exit the app, as Cordova specifies (http://cordova.apache.org/docs/en/6.x/cordova/events/events.html#windows-quirks)
the exception unsubscribes the handler, so the handler isn't called anymore on back button events.

**Comment by manucorporat** [comment]
@almost92 could try try this fix?
https://github.com/driftyco/ionic/pull/11017

**Comment by almost92** [comment]
@manucorporat tested, it doesn't suspend the app anymore.
(clicking hardware back button from root page doesn't send the app to the background)

**Comment by almost92** [comment]
@manucorporat tested, it doesn't suspend the app anymore.
(clicking hardware back button from root page doesn't send the app to the background)

**Comment by digaus** [comment]
With the fix I get this error '0x800a138f - JavaScript runtime error: Unable to get property 'exitApp' of undefined or null reference' when debugging with Visual Studio. This crashes the app...

**Comment by manucorporat** [comment]
@digaus is cordova running?

**Comment by digaus** [comment]
I am building it as a windows application and then run it.
