### ISSUE TITLE
Input doesn't support correctly programmatical change with android virtual keyboard

### ISSUE THREAD

**Issue by adriendomoison** [ionic-team/ionic#11033]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
When using `onInputChange` to modify input programmatically, cursor is not moving when using android virtual keyboard on mobile like when using keyboard on browser, emulator or even chrome remote debugging

**Expected behavior:**
Cursor should have the same behavior with virtual keyboard as physical keyboard

**Steps to reproduce:**
Video of the bug here: https://goo.gl/photos/b24S9eNXkECvWtij7

**Related code:**

```
import {Directive, EventEmitter, Output} from '@angular/core';
import card from "creditcards/card";

@Directive({
    selector: '[ngModel][formatCreditCardNumber]',
    host: {
        "(input)": 'onInputChange($event)'
    }
})
export class CreditCardNumberDirective {

    @Output() ngModelChange: EventEmitter<any> = new EventEmitter();

    constructor() {
    }

    onInputChange($event) {
        this.ngModelChange.emit(card.format(card.parse($event.target.value)))
    }
}
```
HTML
```
<input #cardNumber type="text" class="card-number" name="card-number"
placeholder="4111 1111 1111 1111" maxlength="19" [(ngModel)]="paymentCard.cardNumber" formatCreditCardNumber>
```
**Ionic info:**
```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v7.6.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Does this issue also happen in a plain Angular app ? We do not do anything special with emitting events or inputs.

**Comment by adriendomoison** [comment]
The issue doesn't happen in plain Angular App, any idea what kind of quick fix could work here? :)

**Comment by jgw96** [comment]
Interesting, correct me if im wrong, but you are using a regular html input right? Does the same issue happen with an `ion-input` ? Sorry i dont have a quick solution at the moment, this is definitely a strange issue ive never seen before haha.

**Comment by adriendomoison** [comment]
I know right! No worries :)
I tried before with the `ion-input`, no difference at all...

**Comment by jgw96** [comment]
Hmmm ok. Would you mind sharing a repo i can use to reproduce this issue?

**Comment by adriendomoison** [comment]
[Here you go](https://github.com/adriendomoison/ionic-input-auto-formatting) 
Thank you very much ! :+1:

**Comment by adriendomoison** [comment]
Hello,
I was trying on iPhone and the issue doesn't exist. Only using the virtual keyboard of Android created this bug.
