### ISSUE TITLE
Ion-datetime picker optClick event not triggered in android

### ISSUE THREAD

**Issue by ShayShaked** [ionic-team/ionic#11040]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Open ion-datetime picker.
When clicking one of the days/months/years the clicked item not being selected.
**Expected behavior:**

Clicking one of the days/months/years item causing it to be the selected item.
**Steps to reproduce:**

**Related code:**
The event should trigger the function **PickerColumnCmp.prototype.optClick**
```
insert any relevant code here
Template in picker-component.ts:
'<button *ngFor="let o of col.options; let i=index"' +
        '[class.picker-opt-disabled]="o.disabled" ' +
        'class="picker-opt" disable-activated (click)="optClick($event, i)">' +
        '{{o.text}}' +
      '</button>'

The optClick function implementation:
  optClick(ev: UIEvent, index: number) {
    if (!this.velocity) {
      ev.preventDefault();
      ev.stopPropagation();

      this.setSelected(index, 150);
    }
  }
```
**Other information:**

With android user agent it's not working but with chrome user agent and ios user agent it's working fine.
Tried it on iphone 7 and the browser in desktop mode and it worked perfect.
Not working in all kind of android devices (nexus 6p, lg g3, samsung note 5, samsung s7 etc.)
When switching the browser to device mode in dev tools it's not working either.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Would you mind sharing a repo we can use to reproduce this?

**Comment by ShayShaked** [comment]
Hi, sorry but i can't share all the project because of our firm information security reasons.
I can ,however, share the css and html of the specific page that include the ion-datetime element.

**Comment by stionic** [comment]
Hi,

I have get same problem, then i have fixed it.
Please see my pull request:
https://github.com/ionic-team/ionic/pull/14139

Regards.
