### ISSUE TITLE
bug(navigation): swipe back stuck

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#11053]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In some pages, when swiping to go back, if not swiping all of the way, it is just stuck, showing half of the page you want to close, and half of the parent page. Very odd, especially when it happens only for some pages (consistently for those pages)

**Expected behavior:**
Transition can never be stuck. either close the page, or show the page, never half and half

**Steps to reproduce:**
I don't know

**Other information:**
I have a video showing the issue in one case, but I can't share it publicly. Is there a way to share it with devs only?

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.0-beta.3
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.1
    Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hey, thanks for opening an issue with us! You can share the video to `justin@ionic.io` but if you can provide a repo we could use to reproduce the issue that would be even better (:

**Comment by AmitMY** [comment]
@jgw96 Did you get my emails with the videos?
This specific issue is quite horrible for UX

**Comment by kensodemann** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by SalmanTariq** [comment]
Facing the same issue. Pressing back makes the previous screen halfway and the other half of the screen stays white.

![img_1805](https://user-images.githubusercontent.com/13284494/35180011-fb38f388-fdc7-11e7-8c6c-ca962bc2a95d.JPG)
