### ISSUE TITLE
bug(render): iOS takes time to render / unrenders  parts of view

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#11052]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In some situations, some parts of the view are just not rendered and then rendered after a second or 2. This happens on iOS (I think only) and occurs a lot while scrolling. (even in production build, on iOS 10, on iPhone 6s)

**Expected behavior:**
Always render what is viewed, no unrendering when it is in content

**Steps to reproduce:**
I don't know

**Other information:**
I have a video showing the issue in one case, but I can't share it publicly. Is there a way to share it with devs only?

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.0-beta.3
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.1
    Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind sharing a repo we can use to reproduce this issue?

**Comment by NeoLSN** [comment]
I have the same issue
See [video](https://youtu.be/2AeRV_Apfs8).

It works fine on Android, but iOS will be broken.
If I don't touch the screen again. The item will not show again.

**Comment by AmitMY** [comment]
@NeoLSN This is not fully the same, but similar. My components disappear and reappear when scrolling with acceleration

**Comment by NeoLSN** [comment]
In fact, I need to do a little swipe down gesture then the item will show. Only touching it will not let item show.

**Comment by kensodemann** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by ChristosGeorgiou** [comment]
Hi!

I have the same problem with the latest version.
I can verify that this happens only on iOS build and the screen renters when I scroll

[how it looks like](https://cdn.echofin.co/uploads/ebb9d2c4/DED117110CF0CAA30D6BE749A2DF6257.jpg)
[how it should look like](https://cdn.echofin.co/uploads/ebb9d2c4/A45782941EF18193D5A4CC0F09EC5C1C.jpg)

````
cli packages:
    @ionic/cli-utils : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:
    cordova (Cordova CLI) : 8.0.0 

local packages:
    @ionic/app-scripts : 3.1.7
    Cordova Platforms : android 6.4.0 ios 4.5.4
    Ionic Framework : ionic-angular 3.9.2

System:
    ios-deploy : 1.9.2 
    ios-sim : 6.1.2 
    Node : v8.5.0
    npm : 5.6.0 
    OS : macOS High Sierra
    Xcode : Xcode 9.2 Build version 9C40b
````
