### ISSUE TITLE
Floating label with input undefined

### ISSUE THREAD

**Issue by lucasbasquerotto** [ionic-team/ionic#11068]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
An `ion-input` with value `undefined` and an `ion-label` marked with `floating` have the label over (inside) the field when the value is `null` or `''`, but above it if it is `undefined`.

If I click inside the field and then go out, the label goes over the field correctly.

**It only happens if the field has `formControlName` and `ngModel`, and the value of `ngModel` is `undefined`.**

**Expected behavior:**
The label should be over (inside) the field when the value is `undefined` without needing to click the field, like when it is `null` or `''`.

**Related code:**

	<ion-row ion-item no-padding>
		<ion-label floating>Email</ion-label>
		<ion-input type="text" [formControlName]="email" [(ngModel)]="email"></ion-input>
	</ion-row>

**Ionic info:**

Cordova CLI: 6.4.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v4.4.7
Xcode version: Not installed

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.
