### ISSUE TITLE
Ionic 3 lazy load doesn't handle dependency injection correctly when a component is inherited.

### ISSUE THREAD

**Issue by maitbayev** [ionic-team/ionic#11080]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
```
// base.component.ts
@Component()
export class BaseComponent {
   constructor(private navCtrl: NavController) {
       console.log(navCtrl);
   }
}
```
```

// lazy loaded component
@IonicPage()
@Component()
export class LazyComponent extends BaseComponent {

}
```

In this case, the output is undefined.

```
// base.component.ts
@Component()
export class BaseComponent {
   constructor(private navCtrl: NavController) {
       console.log(navCtrl);
   }
}
```
```

// lazy loaded component
@IonicPage()
@Component()
export class LazyComponent extends BaseComponent {
   constructor(private navCtrl: NavController) {
      super(naveCtrl);
   }

}
```

In this case, the output is object and it is expected behaviour. 

The first case works well without the lazy loading, i.e it prints object.

Relevant source from angular github about correct behaviour of constructor inheritance:
https://github.com/angular/angular/commit/f5c8e09

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Would you be able to share a repo that we can use to reproduce this issue. Im really interested in what your ngModule setup looks like.

**Comment by maitbayev** [comment]
I have set up a small sample repository for this issue: [ionic3-component-inheritance](https://github.com/maitbayev/ionic3-component-inheritance).

After narrowing down the issue I understood that it doesn't work when there is a class field declaration,
Please take a look at:[lazy.component.ts](https://github.com/maitbayev/ionic3-component-inheritance/blob/master/src/pages/lazy/lazy.component.ts)
and note ` private x = '111';` by deleting it works as expected. 
```
import {  IonicPage } from 'ionic-angular';

import { BaseComponent } from "../base.component";
@IonicPage({
  name: "Lazy"
})
export class LazyComponent extends BaseComponent {
  private x = '111';
}
```

**Comment by maitbayev** [comment]
@jgw96

**Comment by jgw96** [comment]
Hello, thanks for sharing! Would you mind trying changing that `private` declaration to `public` ?

**Comment by maitbayev** [comment]
Hi @jgw96 
It doesn't help; However it works fine with:
```
import {  IonicPage } from 'ionic-angular';

import { BaseComponent } from "../base.component";
@IonicPage({
  name: "Lazy"
})
export class LazyComponent extends BaseComponent {
  private x: number;
}

```
