### ISSUE TITLE
bug(ux): flickering content when range is active

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#11087]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When sliding an `ion-range`, other screen content flickers weirdly.
(Confirmed on Android, not the same in browser)
Video:
https://youtu.be/dwqprn1z7NI

**Expected behavior:**
No flickering.

**Steps to reproduce:**
Code below

**Related code:**

```
<ion-content>
    <ion-item>
        <ion-range [(ngModel)]="sensitivity" pin="true" min="0" max="100" (ionBlur)="changeSensitivity()">
            <ion-label range-left>0</ion-label>
            <ion-label range-right>100</ion-label>
        </ion-range>
    </ion-item>

    <div text-center margin padding>
        <small>{{"globals.tips.shakeToSkip" | translate}}</small>
    </div>
</ion-content>
```

**Other information:**
When moving the range, the console prints these warnings:
Many (depends on how long you move it) of (touch move):
> Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

When blur (touch end):
> Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
   Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.0
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.1
    Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind trying 3.0.1 and seeing if you have the same problems? Also, what version of Android are you testing on?

**Comment by AmitMY** [comment]
@jgw96 Same problems indeed.
I am using Android 5.0.1 on a Galaxy S4.
I just noticed that it happens in some other components, like `ion-item`, but it doesn't happen on browser. I guess it is something to do with the Android web page render engine..

**Comment by jgw96** [comment]
Hey @AmitMY , based on our discussion in one of your other issues, would you mind trying crosswalk and seeing if this solves this issue on that device? Im starting to suspect Samsung replaced the stock 5.0 and up Chrome webview with their own.

**Comment by nivida** [comment]
Same error here.. we have this error on ion-sliding-items to.. animation stucks..

**Comment by Floyd1256** [comment]
I have the same issue even in desktop chrome browser. What's weird is that the animation is a bit better when testing on android, but still laggy
