### ISSUE TITLE
Runtime Error on playing with encapsulated IonicPage ion-content/ion-toolbar and others

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#11108]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I get this error, and I'm not sure when this error is happening:

```
Runtime Error
Cannot read property 'links' of null
Stack
TypeError: Cannot read property 'links' of null
    at setupPreloadingImplementation (http://localhost:8100/build/main.js:60017:60)
    at http://localhost:8100/build/main.js:60049:17
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14529)
    at n.run (http://localhost:8100/build/polyfills.js:3:9741)
    at NgZone.runOutsideAngular (http://localhost:8100/build/main.js:4390:76)
    at http://localhost:8100/build/main.js:60048:20
```

I play around with encapsulated `IonicPage ion-content/ion-toolbar` and others
I'm not sure how I can help you to reproduce this.

**Expected behavior:**
It should work :smile: 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI: 6.5.0 
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Linux 4.8
    Node Version: v6.10.2
    Xcode version: Not installed
```

**Comment by brandyscarney** [comment]
Could you try updating to the latest release `3.2.0` and see if you're still running into this problem? The steps to upgrade are here: https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade

It should be fixed by this commit: https://github.com/driftyco/ionic/commit/2afc5cf

Please let me know, thanks! 🙂

**Comment by mburger81** [comment]
Hi, we are out of office, tomorrow for sure we will test it. But honestley we didn't recognize the bug I think for a long time (probably the bug was resolved by app-scripts??) and the main problem is: 
we are still on 3.0.1 because on version 3.1.x we have this problem #11374 which is still their and which is a breaking error for us for which we can not update. 
And now we see the bug is not closed with 3.2.0. (see Milestones) 
But anyway we will test it as and hope for a positive side efect for the other bug.

**Comment by mburger81** [comment]
We tested `3.2.0` which is working better then `3.1.1` and `3.1.0`.
But there remains always the two BIG BIG problems for which we can not migrate:
1) the INVALID VIEWS error: #11374
2) The error I described in another post/issue but I don't know where it is. Sometimes the `nav.setRoot` does nothing and also gives no error.

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue on the latest version, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
