### ISSUE TITLE
bug(grid): scrolling not working properly for inputs with grid

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#11118]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you build a layout using the new `ion-grid`, if you have any inputs or textareas in the columns, when the device's keyboard appears the form is not scrolled correctly to the right position. 

**Expected behavior:**
The input should be scrolled into position such that the user can see the input above the keyboard.

**Steps to reproduce:**
I have provided @jgw96 with a repo.

**Related code:**

```
<ion-content class='page-rating'>
  <ion-grid>
    <ion-row>
      <ion-col>
        <img src='assets/svg/logo.svg' class="logo-img" />
      </ion-col>
    </ion-row>
    <ion-row>
      <ion-col>
        <img class="profile-img" />
      </ion-col>
    </ion-row>
    <ion-row padding-top>
      <ion-col>
        <span class='please-rate-text'>Please rate the service you received</span>
      </ion-col>
    </ion-row>
    <ion-row>
      <ion-col>
        <span class='add-comment-text'>Add comments</span>
      </ion-col>
    </ion-row>
    <ion-row>
      <ion-col>
        <ion-textarea autocomplete [(ngModel)]='comment' placeholder="Your opinion is very important to us. We appreciate your feedback and will use it to improve our service."></ion-textarea>
      </ion-col>
    </ion-row>
    <ion-row>
      <ion-col>
        <button ion-button (click)='submit()'>SEND FEEDBACK</button>
      </ion-col>
    </ion-row>
  </ion-grid>
</ion-content>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by AmitMY** [comment]
Dup/related to:
https://github.com/driftyco/ionic/issues/10629
https://github.com/driftyco/ionic/issues/10854

**Comment by ScreamZ** [comment]
+1
