### ISSUE TITLE
Loading mess up browser's history, result in back screen, wrong history.back() navigation

### ISSUE THREAD

**Issue by bugbuka** [ionic-team/ionic#11133]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

i am developing a wechat h5 website, the default ionic navigation in header bar can not be used in my case.  Only by browser's back button can pop a page.   
it is ok if popping one page only.
But when popping multiple pages, eg:   

Page1 -> Page2 -> Page3 -> Page4   
Page4 -> Page1  

if Page2, Page3, Page4 have the same url(this can be achieved by setting NavOptions.updateUrl = false), click browser's button, Page4 can navigate to Page1.

so, NavOptions's property updateUrl is crucial for this kind of back navigation.

But Loading, Alert, Toast etc breaks expected behaviour of setting updateUrl: false.  

**Steps to reproduce:**
1, git clone https://github.com/driftyco/ionic-conference-app.git  
2, git checkout lazy-load
3, npm install
4, update ionic-conference-app/src/app/app.module.ts  
replace
```
line#25  IonicModule.forRoot(ConferenceApp, {
      preloadModules: true
    }),
```
with  
```
line#25  IonicModule.forRoot(ConferenceApp, {
      preloadModules: false,
      locationStrategy: 'hash',
      mode: 'ios'
    }),
```
5, update ionic-conference-app/src/pages/schedule/schedule.ts  
replace  
```
line#73  goToSessionDetail(sessionData: any) {
    // go to the session detail page
    // and pass in the session data
    this.navCtrl.push('SessionDetailPage', sessionData);
  }
```
with   
```
  goToSessionDetail(sessionData: any) {
    // go to the session detail page
    // and pass in the session data

    let loading = this.loadingCtrl.create({
      content: `loading ....`
    });

    loading.present({
      updateUrl: false
    });

    setTimeout(() => {
      loading.dismiss();

      this.navCtrl.push('SessionDetailPage', sessionData, {
        updateUrl: false
      });

    }, 2000);

    // this.navCtrl.push('SessionDetailPage', sessionData, {
    //   updateUrl: false
    // });
  }
```
6, execute ionic serve
7, open http://localhost:8100/#/tabs/schedule/schedule, click "Breakfast"

Actual: Loading pops up, then Loading dismissed, it goes to session-detail page, and url changes to http://localhost:8100/#/tabs/schedule/session-detail

Expected: Loading pops up, then Loading dismissed, it goes to session-detail page without url changing.  the url should remain the same  http://localhost:8100/#/tabs/schedule/schedule because updateUrl is false.  

**Other information:**

After several day's digging, i find out this issue. and figured out a temporary solution. 

in my case, mode ios is used
update ionic-conference-app/node_modules/ionic-angular/navigation/nav-controller-base.js
replace  
```
line#798    this._linker.navChange(opts.direction);
```
with
```
                let animation = null;
                if (transition.opts && transition.opts.animation) {
                    animation = transition.opts.animation;
                }

                if ((animation === null)
                    || (animation !== 'action-sheet-slide-out'
                        && animation !== 'alert-pop-out'
                        && animation !== 'loading-pop-out'
                        && animation !== 'modal-slide-out'
                        && animation !== 'picker-slide-out'
                        && animation !== 'popover-pop-out'
                        && animation !== 'toast-slide-out')) {

                    this._linker.navChange(opts.direction);
                }
```
The fix is temporary。 

Using updateUrl: false is the only way for poping out several pages by browser's back button, and Loading is also a must feature. Hopefully, this issue can be fixed officially asap.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
macs-MacBook-Pro:ionic-conference-app mac$ ionic info
******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.3.0-201704051913
ios-deploy version: Not installed
ios-sim version: Not installed
OS: OS X El Capitan
Node Version: v6.10.0
Xcode version: Xcode 8.0 Build version 8A218a



******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************

```

**Comment by bugbuka** [comment]
any feedback?

**Comment by danbucholtz** [comment]
Hi @bugbuka,

I think this is working as expected.

If I modify the code to look like this:

```
goToSessionDetail(sessionData: any) {
    // go to the session detail page
    // and pass in the session data

    let loading = this.loadingCtrl.create({
      content: `loading ....`
    });

    loading.present({
      updateUrl: false
    });

    setTimeout(() => {
      loading.dismiss().then(() => {
        setTimeout(() => {
          this.navCtrl.push('SessionDetailPage', sessionData, {
            updateUrl: false
          });
        }, 100);
      });



    }, 2000);

    // this.navCtrl.push('SessionDetailPage', sessionData, {
    //   updateUrl: false
    // });
  }
```

It works. The reason behind this change is because `loading.dismiss()` is an asynchronous call. We need to wait for it to complete before we can properly navigate. Once we do that, everything works as expected.

Thanks,
Dan
