### ISSUE TITLE
When a checkbox is inside ngIf which is inside ngFor the checkbox element is not rendered

### ISSUE THREAD

**Issue by SergioB** [ionic-team/ionic#11147]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
When a checkbox is inside ngIf which is inside ngFor the checkbox element is not rendered. When I replace with a **button** everything is displayed (probably because checkbox is composed of 2 elements: label and actual checkbox)

**Expected behavior:**
display the checkbox elements, like buttons here:
http://plnkr.co/edit/SPPd8yDYoqPlVtYhTd1X?p=preview

**Steps to reproduce:**
the checkbox elements inside are not displayed: (see above example in **expected behavior** displaying correctly buttons instead of checkboxes) 
http://plnkr.co/edit/l1eCH9OQmxl3nQpiTQ3v?p=preview

**Related code:**

```
    <ion-list>
      <ion-item *ngFor="let item of items">
        <ng-container *ngIf="isTrue">
          <ion-label>{{item}}</ion-label>
          <ion-checkbox checked="true"></ion-checkbox>
        </ng-container>
      </ion-item>
    </ion-list>
```

**Ionic info:** 

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002

```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We will look into this.

**Comment by Kaidanov** [comment]
is there a solution for it? 
is seems not to work with ngSwitch also.
Otherwise I would appreciate a link to working demo

**Comment by Kaidanov** [comment]
Working 

<ion-list>
                <ion-item *ngFor=" let answer of question.Answers">
                      <ion-label>{{answer.Description}}</ion-label>
                            <ion-checkbox (change)="change($event, answer)"></ion-checkbox>
               </ion-item>
            </ion-list>

Not working   1

<ion-list>
                <ion-item *ngFor="let answer of question.Answers">
                    <ng-container *ngIf="QuestionType.MutipleChoice==question.QuestionType_Id">
                            <ion-label>{{answer.Description}}</ion-label>
                            <ion-checkbox (change)="change($event, answer)"></ion-checkbox>
                    </ng-container>                    
                </ion-item>
            </ion-list>


Not working 2

<ion-list>
                <ion-item *ngFor=" let answer of question.Answers">
                    <ng-container [ngSwitch]="question.QuestionType_Id">
                        <ng-container *ngSwitchCase="QuestionType.MutipleChoice">
                            <ion-label>{{answer.Description}}</ion-label>
                            <ion-checkbox (change)="change($event, answer)"></ion-checkbox>
                        </ng-container>
                    </ng-container>
                </ion-item>
            </ion-list>


The ngSwitch works for other types like - yes no , or one choice , but not here when adding ion checkbox

Any ideas how I can solves this ?
