### ISSUE TITLE
navController remove method doesn't work

### ISSUE THREAD

**Issue by N4vros** [ionic-team/ionic#11152]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The navController remove method doesn't work as expected.
When the number of pages to remove are superior to 1 it's do nothing (and no errors are thrown).

**Expected behavior:**
In normal case it remove the number of pages.

**Steps to reproduce:**
I made a Plunker : https://plnkr.co/edit/lCPWvh?p=preview
You need to go to the last page (ionic go to home page) and click on the "Go to home page (bug)" button.

**Related code:**

```
this.navCtrl.remove(this.navCtrl.getActive().index, 2);
```

**Other information:**
I tried with index-1 (first parameter) but it not work. Same with -2 (second parameter) instead of 2.
In my project i use the following code in order to bypass this bug.
```
this.navCtrl.popTo(<any>(this.navCtrl.getActive().index-2));
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We will look into this.

**Comment by peterkelly** [comment]
Possibly related to https://github.com/ionic-team/ionic/issues/12238

**Comment by JeongJun-Lee** [comment]
This issue is still at ionic-angular@3.9.2.

**Comment by tonysamperi** [comment]
As @JeongJun-Lee I can confirm this is still an issue
<pre><code>ionic-angular@3.9.2</code></pre>
