### ISSUE TITLE
ion-select submitText not working

### ISSUE THREAD

**Issue by mizdler** [ionic-team/ionic#11156]
**Ionic version:**
[ ] **1.x**
[X] **2.x**
[X] **3.x**

**I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] support request

**Current behavior:**
ion-select submitText attribute does not work.

**Expected behavior:**
Setting submitText attribute should change text of submit button.

**Steps to reproduce:**
http://plnkr.co/edit/DZeXaoL1rpvwqaOvVmNm?p=preview

**Comment by jgw96** [comment]
Thanks, we will look into this.
