### ISSUE TITLE
ion-select(s) will break if one of them has no ion-option 

### ISSUE THREAD

**Issue by mizdler** [ionic-team/ionic#11158]
**Ionic version:**
[ ] **1.x**
[X] **2.x**
[X] **3.x**

**I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] support request

**Current behavior:**
let's say we have two ion-select component in a page if one of them has no ion-option available both of them will broke.

**Expected behavior:**
ion-select(s) should be independent!

**Steps to reproduce:**
http://plnkr.co/edit/WJgi4cPKRO32Akov1HLa?p=preview

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. We will look into this.

**Comment by cyberbobjr** [comment]
Agree, very annoying
