### ISSUE TITLE
iOnic 3 Modal opens wrong page after dismiss

### ISSUE THREAD

**Issue by danielsogl** [ionic-team/ionic#11150]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When I open a modal with lazy loading I have a strange bug.
The Modal is shown normally without problems but when I close the modal the app loads, not the page which created the modal, it loads a completely different page (intro.ts)

I open the modal with this code:

```
  openRentenInfoPage() {
    this.modalCtrl.create('InfoRentenbescheidPage').present();
  }
```

I close the modal with this code:

```
  dismiss() {
    this.viewCtrl.dismiss();
  }
```

I don't have this problem on other pages who use a Modal.
This problem is also there when i push the page with the navCtrl...

[Gif](https://gifyu.com/images/iOnic3_modal_bug.gif)
[Repo](https://github.com/MTechDE/ionic-modal-bug)
**Expected behavior:**

After clicking on dismiss the questions-before (the page which creates the modal) page should be the shown page.

For Ionic 1 issues - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

For Ionic 2 issues - http://plnkr.co/edit/z0DzVL?p=preview
-->

**Related code:**

```
insert any relevant code here
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
    Cordova CLI: 6.5.0 
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: macOS Sierra
    Node Version: v7.8.0
    Xcode version: Xcode 8.3.1 Build version 8E1000a
```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Hmm this is definitely interesting. Unfortunately I cannot reproduce this issue on our lazy-loading version of the conference app, which uses modals. Could you share a minimal reproducible example of this issue?

**Comment by MTechDE** [comment]
Here is the Code (i removed my private keys, calculators etc.)

https://github.com/MTechDE/ionic3-modal-bug

Clone the repo, run npm install (i use CLI v3 Beta), swipe the intro page, then navigate to page 4 and press the green text like in the gif.

**Comment by MTechDE** [comment]
I will share the code of the modal page and the modal creator page.
In the Browser URL I can see, that the Modal changes the link always back to localhost:8100/#/
On other modals the URL changes back like this localhost:8100/#/game

**Comment by MTechDE** [comment]
I created a new GitHub repo with the code: https://github.com/MTechDE/ionic-modal-bug

Just run npm install and navigate thru the intro page. On the fourth question page click on the green labeled Link like in this gif: https://gifyu.com/images/iOnic3_modal_bug.gif

**Comment by MTechDE** [comment]
@jgw96 I still have this problem in Ionic 3.0.1

**Comment by lpsantana** [comment]
Same problems here. So frustrating

**Comment by anooprehman** [comment]
@danielsogl Can you try adding return false after calling your function openRentenInfoPage().

Example: <a href="#" (click)="openRentenInfoPage(); **return false;**">

I think it will try o redirect to the link in href if return false is not added. [(Reference)](https://stackoverflow.com/questions/855360/when-and-why-to-return-false-in-javascript)
