### ISSUE TITLE
bug: Time Picker can't display midnight (12:00AM)

### ISSUE THREAD

**Issue by uniphonic** [ionic-team/ionic#11154]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Whenever I open a time that is set to midnight (12:00AM), it seems that the time picker switches to 1:00AM instead. 

To reproduce, make an ion-datetime showing time in the HTML

`<ion-datetime displayFormat="h:mm A" pickerFormat="h mm A" [(ngModel)]="startDate"></ion-datetime>`

bind it to a variable in the TS:

`startDate: String = new Date().toISOString();`

Then run it, and select midnight as the time then, and then immediately tap the field again to edit the time, and when the time picker opens it up shows 1AM instead of midnight. It happens regardless of what the minutes are set to (12:00AM through 12:59AM exhibits this behavior).

I've also posted the issue here in the forum:
https://forum.ionicframework.com/t/ionic-2-bug-time-picker-cant-show-midnight/86000

Is there a fix?

Thanks!
Jacob</span>

<span is-issue-template></span>

**Comment by JustinPierce** [comment]
I am seeing this behavior, as well. From my analysis, the time picker _can_ select midnight, and it does update the backing variable correctly. However, when you open the picker, it initializes to 1AM as described above. All other hours seem to work as expected.

**Comment by JustinPierce** [comment]
This is still a problem in the 3.x releases.

**Comment by VeteranCoder** [comment]
Is anybody working on this?  I cannot imagine this is a particularly complex problem to solve.
