### ISSUE TITLE
Ionic 3 - NavController.push does not accept Component as first argument

### ISSUE THREAD

**Issue by kashban** [ionic-team/ionic#11162]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The typescript transpiler throws an error when transpiling this:

`this.nav.push(tile.navigation, { animate: true, direction: 'forward' });`

> Typescript Error
> Argument of type 'Component' is not assignable to parameter of type 'string | Page'. Type 'Component' is not assignable to type 'Page'. Property 'apply' is missing in type 'Component'.
> C:/Daten/Entwicklung/Belfor/EquipmentAppGit/src/pages/dashboard/dashboard.ts
>   const tile:BlfTileConf = tileClickedEventData.tile;
>   this.nav.push(tile.navigation, { animate: true, direction: 'forward' });
> }
> Ionic Framework: 3.0.1
> Ionic App Scripts: 1.3.0
> Angular Core: 4.0.0
> Angular Compiler CLI: 4.0.0
> Node: 6.9.1
> OS Platform: Windows 10
> Navigator Platform: Win64
> User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0

**Expected behavior:**

NavController.push should accept Components being part of a structure as first argument as it did before (Ionic 2). 

**Steps to reproduce:**

See related code.

**Related code:**

We're using an interface to organize tile navigation: 

```
export interface BlfTileConf {
    title: string;
    subtitle: string;
    icon: string;
    badges:BlfTileBadgeConf[],
    navigation: Component,
    disabled?: Function
}
```
This is the structure adhering that interface:

```
import { MyJobsPage } from '../jobs/my-jobs';
import { MyVanPage } from '../van/my-van';
import { ExternalVanPage } from '../extvan/external-van';

MY_JOBS: {
              title: 'My Jobs',
              subtitle: 'Manage my jobs and their equipment',
              icon: 'jobs.jpg',
              badges: [
                {key: 'ALL_JOBS',count: 0}
              ],
              navigation: MyJobsPage
            },
            MY_VAN: {
              title: ' My Van',
              subtitle: 'Manage equipment on my van',
              icon: 'van.jpg',
              badges: [
                {key: 'UNCONFIRMED', count: 0, status: 'Unconfirmed', pending: true},
                {key: 'CONFIRMED', count: 0, status: 'Confirmed'}
              ],
              navigation: MyVanPage
            },
            EXTERNAL_VAN: {
              title: 'External Van',
              subtitle: 'Manage equipment in delivery',
              icon: 'delivery.jpg',
              badges: [
                {key: 'UNCONFIRMED', count: 0, status: 'Unconfirmed', pending: true},
                {key: 'CONFIRMED', count: 0, status: 'Confirmed'}
              ],
              navigation: ExternalVanPage,
              disabled: this.disableExternalVan.bind(this)
            }
```

The pages are standard components like in any starter template.

The project has been migrated from Ionic 2 RC5 to the latest Ionic 3 /Angular 4 by following the migration path, yet this error occurs which does not make sense to me because Components ought to be Pages. 

Yet Page seems to be different from Component in some way:

`abstract push(page: Page | string, params?: any, opts?: NavOptions, done?: Function): Promise<any>;`

The Page Class navController.push expects is defined like this and does not look like a Component at all:

```
export interface Page extends Function {
    new (...args: any[]): any;
}
```

If I change the interface to this:

```
export interface BlfTileConf {
    title: string;
    subtitle: string;
    icon: string;
    badges:BlfTileBadgeConf[],
    navigation: any,
    disabled?: Function
}
```

it works. So there seems to be some issue with the transpiler losing type information or rendering it incompatible when going through an interface like that. 

**Other information:**

I found none. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by rehannawab** [comment]
I have the same issue when passing a reference which is the type of an abstract component. It works well when passing a type of Concrete Component.

**Comment by jgw96** [comment]
Hello all, thanks for opening an issue with us, we will look into this.

**Comment by rapropos** [comment]
I think if OP imports `Page` from "ionic-angular/navigation/nav-util" and changes the type of `navigation` to `Page` this should work.

**Comment by kashban** [comment]
@rapropos I tried this before and it has several other sideeffects I don't want to cope with. For the most part because casting the actually Page Component to type Page in my interface fails miserably.

**Comment by queejie** [comment]
I'm sorry, but isn't this a show stopper?  How can one navigate if all one's pages are defined as Components?  Wasn't this considered a breaking change?  Is there a workaround.  I've just spent a couple of hours trying to figure this out.  If anyone has a suggestion, it would be greatly appreciated?  Thanks in advance.

**Comment by kashban** [comment]
@queejie The workaround is shown in my original issue post. Just drop type safety for this particular interface attribute.
