### ISSUE TITLE
Label inside ion-item crashes whole item

### ISSUE THREAD

**Issue by JanMesaric** [ionic-team/ionic#11167]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have ion-item-sliding with nested ion-item, inside is ion-label for ion-datetime. If I remove ion-label everything works fine, if I insert it, the whole ion-item renders empty.

**Expected behavior:**
Expect to display ion-item

**Steps to reproduce:**
 ion-item-sliding with nested ion-item, inside is ion-label for ion-datetime. This stopped working with upgrade to version 3.0.0

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. Could you share a repo or plunker we can use to reproduce this issue?

**Comment by JanMesaric** [comment]
Here is an example:

```
<ion-item-sliding>
  <ion-item (click)="action()">
    <ion-list>
       <ion-item>
          <ion-label>End Time</ion-label>
          <ion-datetime displayFormat="HH:mm" pickerFormat="HH:mm" placeholder="'00:00'" [(ngModel)]="model" (ngModelChange)="update($event)"></ion-datetime>
        </ion-item>
      </ion-list>
  </ion-item>
  <ion-item-options side="right">
    <button ion-button color="danger">
      <ion-icon name="close"></ion-icon>
    </button>
  </ion-item-options>
</ion-item-sliding>
```

**Comment by jgw96** [comment]
Thanks, i can now reproduce this. We will look into this.

**Comment by lincolnthree** [comment]
I just hit this as well. Ionic 3.1.0

**Comment by lincolnthree** [comment]
I believe it has to do with the ion-datetime component, not with the label.

**Comment by lincolnthree** [comment]
I now believe it has something to do with angular model binding of ion-datetime.

**Comment by JanMesaric** [comment]
It has happened for me again
