### ISSUE TITLE
Line separators in an ion-list missing on iPad Mini and iPad retina (ios 9.3.2)

### ISSUE THREAD

**Issue by nishantpant** [ionic-team/ionic#11172]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On Ipad mini and iPad retina (ios 9.3.2), line separators don't render in an ion-list. They show fine on the browser when tested using ionic serve.

**Expected behavior:**
Line separators should show as between each ion-item. 

**Steps to reproduce:**

**Related code:**
1. create an ionic project from scratch.
2. in home.html put this:
```
<ion-header>
 
  <ion-navbar>
    <ion-title>Groceries</ion-title>
  </ion-navbar>
 
</ion-header>
 
 
<ion-content>
 
    <ion-list>
        <ion-item *ngFor="let grocery of groceries">{{grocery}}</ion-item>
    </ion-list>
 
</ion-content>
```
3. In home.ts  put this 
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
groceries:any;
  constructor(public navCtrl: NavController) {
 this.groceries = [
            'Bread',
            'Milk',
            'Cheese',
            'Snacks',
            'Apples',
            'Bananas',
            'Peanut Butter',
            'Chocolate',
            'Avocada',
            'Vegemite',
            'Muffins',
            'Paper towels'
        ];
  }

}

```4. do an ionic build ios and deploy the app to an Ipad. You will see the issue. 

**Other information:**
More Info
https://forum.ionicframework.com/t/line-separators-in-an-ion-list-missing-on-ipads/86160

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by ChristopherTotty** [comment]
Also ran into this issue on iOS 9 devices.  Inspecting the item-inner shows a border-bottom width of 0.55px.  Overriding this to 1px allows the line to display.  I assume there is an issue with subpixel rendering on this version/device combination.  I was able to fix this issue on an original (non-retina) iPad Mini by adding the following to app.scss:
```
@media (-webkit-min-device-pixel-ratio: 1){
    .list-ios .item .item-inner {
        border-bottom-width: 1px;
    }
}
```

**Comment by xam41** [comment]
Any update on this?
