### ISSUE TITLE
On [ion-slides] instance with loop=true option, slideTo() method shows index-1 slide

### ISSUE THREAD

**Issue by darron1217** [ionic-team/ionic#11179]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

On [ion-slides] instance with loop=true option, slideTo() method shows index-1 slide
ex)
slideTo(0) = shows last slide
slideTo(1) = shows first slide

**Expected behavior:**

loop=true option should not affect on slideTo() method!!
ex)
slideTo(0) = shows first slide
slideTo(1) = shows second slide

**Steps to reproduce:**

http://plnkr.co/edit/h4XWj9eZ1GudST75E427?p=preview

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by darron1217** [comment]
@jgw96 I guess this issue is related with https://github.com/driftyco/ionic/issues/10195
We may check this issue after the 'slides.length() bug' is fixed.

**Comment by kinggolf** [comment]
Came across same issue today. Using ionic-angular 3.2.1.

**Comment by acaua** [comment]
My guess is that this problem is related with the duplication of slides when loop=true. Check Swiper docs on loop option:
http://idangero.us/swiper/api/
