### ISSUE TITLE
Grid Auto-layout don't work with iOS

### ISSUE THREAD

**Issue by BeliliFahem** [ionic-team/ionic#11186]
**Ionic version:** 
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...** 
[ x] bug report
[ ] feature request

**Current behavior:**

Grid Auto-layout does not work with iOS. The grid continues on the same line and does not fit as in Android (with the same code for iOS an Android). When I use Safari on Mac OS, it works.

Screen capture from real device iPhone7 with iOS 10.3
Portrait
![image](https://cloud.githubusercontent.com/assets/6841040/24957392/ec522fc6-1f8b-11e7-9251-60010236afde.png)

Landscape
![image](https://cloud.githubusercontent.com/assets/6841040/24957263/6d0350f6-1f8b-11e7-93bb-720db7103ba1.png)

**Expected behavior:** Screenshot for Android (also works with the web) with the same code that did not work well under iOS.

![image](https://cloud.githubusercontent.com/assets/6841040/24956348/7fe35206-1f87-11e7-9f2e-b369714c5bf6.png)
Image from Android

**Steps to reproduce:**

**Related code:**

```
<ion-grid>
  <ion-row>
    <ion-col>
      1 of 2
    </ion-col>
    <ion-col>
      2 of 2
    </ion-col>
    <ion-col>
      1 of 3
    </ion-col>
    <ion-col>
      2 of 3
    </ion-col>
    <ion-col>
      3 of 3
    </ion-col>
       <ion-col>
      1 of 2
    </ion-col>
    <ion-col>
      2 of 2
    </ion-col>
    <ion-col>
      1 of 3
    </ion-col>
    <ion-col>
      2 of 3
    </ion-col>
    <ion-col>
      3 of 3
    </ion-col>
   </ion-row>
</ion-grid>
```

**Other information:**

**Ionic info:**:
```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by ghenry22** [comment]
exactly the same issue that the grid in ionic 1 had and that the previous implementation of grid for ionic 2 had.  Been there for ever.  Works fine on android and chrome.  Doesn't work on ios.

The below code in my scss file fixes it for iOS and doesn't hurt Android.  90px is my min-width value.

```
ion-col.col{
	flex: 1 0 90px;
}
```

**Comment by HanrichPotgieter** [comment]
I have exactly the same issue in my project. I have not found a fix for it yet.
<img width="713" alt="screen shot 2017-04-13 at 3 24 33 pm" src="https://cloud.githubusercontent.com/assets/8564706/25006483/53a514c8-205d-11e7-8be4-240285174a3e.png">

**Comment by donjae** [comment]
Any progress on this issue?

**Comment by Kr0n092** [comment]
Would like to know more about this issue as well.

**Comment by Kr0n092** [comment]
Found a possible solution using [this](https://medium.com/curiouscaloo/fixing-wrap-ion-row-on-ios-with-ion-col-without-defined-width-92073f08b042) page. Helps me so far.

**Comment by gdinn** [comment]
Any progress on this?

**Comment by BeliliFahem** [comment]
I do not work on the project anymore and therefore I do not know if the problem has been solved.
The "grid" component is very important for the PWA so I think the ionic team can already solve this problem.
