### ISSUE TITLE
Ionic 3 - IonicPage Deeplinking - Url change not recognized

### ISSUE THREAD

**Issue by vandres** [ionic-team/ionic#11199]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

With the new IonicPage Deeplinking, manual changes to the url are not recognized. If I have a url #/home and change it to #/about, nothing happens. When reloading the browser, the AboutPage gets loaded 

**Expected behavior:**

Manual changes to the url are recognized, as used to when using Ionic without IonicPage

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.8.0
Xcode version: Xcode 8.3.1 Build version 8E1000a

```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Could you make a repo we could use to reproduce this issue?

**Comment by vandres** [comment]
Hi @jgw96 

To speed things up, do you have any running examples of the new @IonicPage Deeplinking?

**Comment by Barryrowe** [comment]
I am with @vandres  on this. I came across this issue specifically trying to find an official example project using the new IonicPage decorators for Deeplinking. I was on the verge of scrapping Ionic for a project we have, and then this feature was announced. It's a make or break decision on our use of Ionic for projects that need to be deployed for both Mobile and Desktop experiences.

**Comment by Barryrowe** [comment]
@rapropos  provided this link in the forums that shows a "working" example.
https://github.com/mhartington/star-track-ionic/tree/master/src

**Comment by vandres** [comment]
@jgw96 
You can reproduce it with https://github.com/mhartington/star-track-ionic/tree/master/src

Search for "test". 
Click the first entry.
Refresh. -> now you are on a blank page which seems to be a bug of the star-track repo
Try to change the url back to "#/menu/search". -> nothing happens

**Comment by izee** [comment]
nothing happens with IonicPage from 3.0.0 to 3.1.1
has any test before publish?
@jgw96 please use blank-starter or any starter with IonicPage to reproduce this.

**Comment by jmchaves** [comment]
I'm using ionic 3.7 and I got the same issue. Any progress about this?
