### ISSUE TITLE
Tabs Don't Highlight if error caused during ionViewDidLoad

### ISSUE THREAD

**Issue by davec21** [ionic-team/ionic#11197]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you have a page with a bound ngFor and in that ngFor is an invalid binding to another item, pushing the tabs page as root causes tabs to not highlight but still work.  There is also no error in the console. This only happens if the for binding is populated in the ionViewDidLoad. If the for binding is populated in the WillEnter/DidEnter/Constructor the error is thrown and ionic displays the error page.

My guess is that the ionViewDidLoad is catching the error and not displaying anything. Though the functionality of the tabs still works.. the highlighting doesn't.

**Expected behavior:**
Error in console and ionic error visible.

**Steps to reproduce:**
Git Repo: https://github.com/davec21/taberror.git
Repo home: https://github.com/davec21/taberror

Basically.. create a landing page (not the tabs page) and set it as root in the app. Have a bound array that is looped through using *ngFor have code that would echo out an invalid item: ie {{notMy.item}}.  Have the array be empty until ionViewDidLoad() is called. By setting the array to have items in the ionViewDidLoad() function, angular rebinds and will run the *ngFor and try to parse the invalid item.

Have a button to set root to the tabs page, and notice that the tabs function but do not highlight. 

Having the array be populated anywhere else will throw the error.  If you use my repo change ionViewDidLoad() to ionViewWillEnter() and see the problem.  Commenting out the populating of the array causes the *ngFor to not run (as no data) and tabs will highlight fine.

It's sort of a confusing error, so if you need more info.. let me know.

**Related code:**
Git repo posted above.

**Other information:**

Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.7.0
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will look into this.
