### ISSUE TITLE
Ionic 3 - IonicPage Deeplinking - navPush directive not setting correct href

### ISSUE THREAD

**Issue by vandres** [ionic-team/ionic#11198]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Found a small bug with the new IonicPage Deeplinking:

When setting a link from the navPush directive `<a [navPush]="'AboutPage'">About</a>`, the generated link always shows the current page `<a href="#/home" ng-reflect-nav-push="AboutPage">About</a>`

**Expected behavior:**

Behaviour without IonicPage: `<a href="#/about" ng-reflect-nav-push="AboutPage">About</a>`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.8.0
Xcode version: Xcode 8.3.1 Build version 8E1000a

```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will look into this.

**Comment by TanayParikh** [comment]
@vandres Are you still experiencing this issue? I am not able to replicate it as of Ionic 3.3.0.

**Comment by vandres** [comment]
@TanayParikh Yes, tested it with our current 3.3.0 app. Setting a link wit navPush and lazy loading shows the wrong link:

I am on ListPage and in the template is the following
`<a [navPush]="'HomePage'">Home</a>` -> `<a ng-reflect-nav-push="HomePage" href="#/list" class="">Home</a>`

**Comment by tommybananas** [comment]
Also seeing this
```
    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0
    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0
    Node       : v6.10.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.8
```

**Comment by lordgreg** [comment]
Exactly the same issue as @tommybananas described:
```
cli packages: (C:\Development\latestnews-ionic\node_modules)

    @ionic/cli-plugin-cordova       : 1.5.0
    @ionic/cli-plugin-ionic-angular : 1.4.0
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.0
    OS                : Windows 10
    npm               : 5.3.0
```

**Comment by vandres** [comment]
@tommybananas @lordgreg I think you have to use [navPush]="'NewPage'" as you are not using a variable but a string. This should not be related to the bug I reported

**Comment by DominikTrenz** [comment]
I can confirm this bug. Very annoying with locationstrategy path. Navpush is not usable in a pwa

**Comment by vandres** [comment]
@jgw96 Thank you for your talk on PWAs. Maybe you can push this issue a bit?!

**Comment by DominikTrenz** [comment]
That issue is still not fixed...  Here is a workaround:
html:
`
[attr.href]="'/'+someLink" (click)="openPage(someLink)"
`
ts:
`
  openPage(page) {
    event.preventDefault();
    event.stopPropagation();
    this.nav.push(page);
  }
`
