### ISSUE TITLE
content bounces when keyboard opens on ios

### ISSUE THREAD

**Issue by josh-m-sharpe** [ionic-team/ionic#11201]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When touching an input field on ios, the keyboard opens and the input/form bounces around.  It's not great UX.

**Expected behavior:**
The Input/Form would move smoothly.

**Steps to reproduce:**
I created a repo with a v3 app here.  Contains video as well:
https://github.com/josh-m-sharpe/ionicjumpingformdemo

I believe this is fairly similar to this recently closed issue: https://github.com/driftyco/ionic/issues/10984

**Comment by ScreamZ** [comment]
Also spotted on Android

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will look into this.

**Comment by ivanov84** [comment]
Perhaps it helps:
If I set IonicModule.forRoot(MyApp, { mode: 'ios' }),
then I see "content bounces when keyboard opens" even on Android device

**Comment by ivanov84** [comment]
@josh-m-sharpe Hello! Could you tell me please, is it possible to roll back something in ionic framework code? It's very important for me to make it work.
Thanks in advance.

**Comment by wsjwong** [comment]
Bouncing issue still persists. I am testing on iOS device.

**Comment by changulpaye** [comment]
Any update on this issue I am also facing same issue in iOS and Android is working fine.

**Comment by wsjwong** [comment]
I dont understand why this critical issue is still not being fixed. ;(

**Comment by mateoqac** [comment]
Some news about this??
