### ISSUE TITLE
VirtualScroll should work with grid

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic#11212]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

For example, in the conference app we use a grid on the [speakers page](https://github.com/driftyco/ionic-conference-app/blob/master/src/pages/speaker-list/speaker-list.html#L15). When making this list a `virtualScroll` list the list does not render correctly and cards overlap each other when in desktop mode. After discussing this with brandy this is most likely being caused by the items not all being the same size and therefore causing virtualscroll to not render them correctly. The workaround currently is to use css to give the cards a specific height on desktop (media query).

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by yonirab** [comment]
Thanks for documenting this so clearly! I saw this exact issue in the conference app today, and the nice Todo comment in [speaker-list.scss](https://github.com/ionic-team/ionic-conference-app/blob/master/src/pages/speaker-list/speaker-list.scss) pointed me in the right direction!
Thanks for keeping your users in mind ;-)

**Comment by ThomasKientz** [comment]
This issue is still live with the [speakers page](https://github.com/driftyco/ionic-conference-app/blob/master/src/pages/speaker-list/speaker-list.html#L15)

Any news about that ?
