### ISSUE TITLE
platform.is("windows") not working for windows 10 machine

### ISSUE THREAD

**Issue by zoinkydoink** [ionic-team/ionic#11226]
It seems my last issue created was not clear and it was closed so i will try again.

**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ x?] feature request

**Current behavior:**
platform.is("windows") returning false when app is a uwp app and running on desktop
platform.platforms() array returns:
cordova
core

**Expected behavior:**
platform.is("windows") should return true
platform.platforms() should return:
cordova
core
windows

**Steps to reproduce:**
output the array for platform.platforms() on a uwp on a full windows 10 machine
   <span *ngIf="platform.is('windows')">should should show on all windows</span>

**Other information:**
I understand there is the "core" but "windows" should return true regardless of its on desktop or device

**Comment by jgw96** [comment]
Hello, thanks for using Ionic and sorry for misunderstanding your earlier issue! We will look into this.

**Comment by ghenry22** [comment]
yep also just started trying to build for windows 10 devices and see the same (I am targeting desktop/surface type devices not phones).

**Comment by frankpapenmeier** [comment]
I am seeing the same issue and hope this will be fixed soon.

**Comment by digaus** [comment]
This is the fix I use:

```
 if (this.platform.userAgent().indexOf('Windows') !== -1) {
          this.platform.setUserAgent('Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; MSAppHost/3.0; Microsoft; Lumia 550) Apple WebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Mobile Safari/537.36 Edge/14.14322');
          this.platform.init();
      }
```

**Comment by karlbateman** [comment]
@digaus Does this target the desktop application or mobile?

**Comment by digaus** [comment]
@karlbateman This targets the desktop application

**Comment by karlbateman** [comment]
@digaus Thanks, what does `this.platform.init()` do?

**Comment by digaus** [comment]
It makes sure the changes are applied I suppose :) found the solution some time ago on stackoverflow ;)

**Comment by digaus** [comment]
Just noticed that it does not work anymore... need to use  

```
if (this.platform.userAgent().indexOf('Windows') !== -1) {
            this.config.settings({mode:'wp'});
            this.platform.setUserAgent('Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; MSAppHost/3.0; Microsoft; Lumia 550) Apple WebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Mobile Safari/537.36 Edge/15.15063');
            this.platform.init();
        }
```

**Comment by frankpapenmeier** [comment]
@digaus Thanks. I tried your solution and it even works when omitting the setUserAgent and init lines:
```
import { Platform, Config } from 'ionic-angular';

constructor(private config: Config, private platform: Platform){
        if (this.platform.userAgent().indexOf('Windows') !== -1) {
            this.config.settings({mode:'wp'});
        }
}
```

**Comment by digaus** [comment]
@frankpapenmeier 
You need setUserAgent, otherwise if you call `platform.is("windows")` it will return false

**Comment by frankpapenmeier** [comment]
@digaus 
Thanks for the info!

**Comment by DennisSmolek** [comment]
I wanted to add that its 9/20/17 and I'm still getting this issue..

Doing the `userAgent()` like suggested above outputs:
`Platforms Mozilla/5.0 (Windows NT 10.0; Win64; x64; MSAppHost/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063`

I'm not sure how to trigger it to pass to the `is()` function but digging through the platform.ts code there isn't even a windows platform test from what I can tell. I'm willing to mess with source code if someone could point me to where the platform tests are being done...

**Comment by DennisSmolek** [comment]
Update: If you do a "Browser" build or PWA on an app that you also have checking for if it's running on Native doing the UserAgent method will cause it to fire as if it's desktop as `"Windows"` is in the default UserAgent string for Chrome & Edge...

**Comment by 3h3c** [comment]
you can use the device Plugin to find out on which platform you are currently. see: https://ionicframework.com/docs/native/device/#platform
