### ISSUE TITLE
Refresher component is triggering by scrolling ion-scroll content

### ISSUE THREAD

**Issue by sneas** [ionic-team/ionic#11222]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[*] **3.x**

**I'm submitting a ...**  (check one with "x")
[*] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ion-refresher is triggering by scrolling ion-scroll content when both of them presents on ion-content.

**Expected behavior:**
ion-refresher shouldn't be affected by ion-scroll component.

**Steps to reproduce:**
1. Switch to mobile view
2. Scroll down one of the content panels
3. Scroll up one of the content panels

**Preview**
http://plnkr.co/edit/IJdg9n?p=preview

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. Could you share a repo we could use to reproduce this issue?

**Comment by sneas** [comment]
Hi, thanks for the fast reply. Here is prview: http://plnkr.co/edit/IJdg9n?p=preview

**Comment by sneas** [comment]
Here is the workaround could be used before the issue is fixed

```typescript
import { Directive, ElementRef } from '@angular/core';

/**
 * Wee need this directive to prevent page refresh on grid view scrolling
 */
@Directive({
    selector: '[scrollCatcher]'
})
export class ScrollCatcherDirective {

    private scrollElement: HTMLElement;

    constructor(private el: ElementRef) {
    }

    ngAfterViewInit() {
        this.scrollElement = this.el.nativeElement.getElementsByClassName('scroll-content')[0];
        this.scrollElement.addEventListener('touchstart', (event: Event) => {
            event.stopImmediatePropagation();
        });

        this.scrollElement.addEventListener('touchend', (event: Event) => {
            event.stopImmediatePropagation();
        });
    }
}
```

Apply this directive for `ion-scroll`.

```html
<ion-scroll scrollCatcher>Scroll content</ion-scroll>
```

**Comment by maitham1** [comment]
When is this expected to be fixed

**Comment by cxcxcxcx** [comment]
Unfortunately the workaround doesn't seem working. the touchstart and touchend events are caught, but the refresher are still triggered :(

**Comment by sneas** [comment]
@cxcxcxcx, updated the directive. Now it works as expected.

**Comment by glemiere** [comment]
I added the following condition to have a better UI. Thank you for the tip ;-)
```

if (this.scrollElement.scrollTop > 300) {
   event.stopImmediatePropagation();
   event.cancelBubble = true;
}
```

**Comment by chhavi2** [comment]
You will have to control the ion-refresher being enabled based on if the ion-slide scrollTop is less than 10. This way you will be restricting its enabled state and it won't be triggered with scroll up inside the ion-slide or ion-scroll and scroll position will be retained in each slide.
Code Sample below - 
    <ion-content>
    <ion-refresher [enabled]="isRefresherEnabled()"(ionRefresh)="doRefresh($event);">
        <ion-refresher-content 
          pullingText="Pull to refresh"
          pullingIcon="arrow-up"
          refreshingSpinner="crescent">

    </ion-refresher-content>

     </ion-refresher>


    <ion-slides>

        <ion-slide *ngFor="let slide of slides;let i = index;">
         <ion-scroll class="y-scroll-custom" scrollY="true" #myScroll>
          
         </ion-scroll>
        </ion-slide>
      </ion-slides>

    </ion-content>
    
in your corresponding *.ts file -


    import { ViewChildren, QueryList } from '@angular/core';
    import { Slides} from 'ionic-angular';

 


    @ViewChild('mySlider') slider: Slides;
    @ViewChildren('myScroll') components:QueryList<Scroll>;

	isRefresherEnabled() {
		if (this.slider) {
			const activeSlideIdx = this.slider.getActiveIndex();
			if (this.components && this.components['_results']) {
				if (this.components['_results'][activeSlideIdx]) {
					if (this.components['_results'][activeSlideIdx]['_scrollContent']) {
						if (this.components['_results'][activeSlideIdx]['_scrollContent'].nativeElement.scrollTop <= 10) {
							return true;
						}
					}
				}
			}
		}
		return false;
	}

**Comment by Bombaxo** [comment]
Hi @chhavi2, 

I found your solution interesting. It would fit perfectly into out app structure. We use exactly the same with ion-slides. Unfortunately it doesnt fully work. The scrollTop always return 0 and this enables all the time the refresher to be triggered even if you are at the bottom of the scroll content. 

We have 2 ion-slide within a component inside. Is there something I am missing? 

There is my code. The isRefresherEnabled function is exactly like your sample.

`<ion-refresher 

        [enabled]="isRefresherEnabled()"
        (ionRefresh)="loadDataCalendar($event, true)">
    </ion-refresher>
    <ion-slides
        #slideSubNav
        (ionSlideWillChange)="swipeToNextPage($event)">
        <ion-slide>
                {{ isRefresherEnabled() }}
            <ion-scroll class="y-scroll-custom" scrollY="true" #myScroll>
                <child-component1>
                </child-component1>
            </ion-scroll>
        </ion-slide>
        <ion-slide>
            <ion-scroll class="y-scroll-custom" scrollY="true" #myScroll>
                <child-component2>
                </child-component2>
            </ion-scroll>
        </ion-slide>
    </ion-slides> `

Thanks in advance. Gr

**Comment by chhavi2** [comment]
Hi @Bombaxo,

Can you please post what you have in your controller file?
Please check if this.slider.getActiveIndex() is returning the active slide's index.

The scrollTop does return the actual value provided we are looking for the scrollTop of the active slide. 
If you have the following code in the *.ts file, it will work perfectly - 
```
import { ViewChildren, QueryList } from '@angular/core';
import { Slides} from 'ionic-angular';


@ViewChild('slideSubNav') slider: Slides;
@ViewChildren('myScroll') components:QueryList<Scroll>;

isRefresherEnabled() {
	if (this.slider) {
		const activeSlideIdx = this.slider.getActiveIndex();
		if (this.components && this.components['_results']) {
			if (this.components['_results'][activeSlideIdx]) {
				if (this.components['_results'][activeSlideIdx]['_scrollContent']) {
					if (this.components['_results'][activeSlideIdx]['_scrollContent'].nativeElement.scrollTop <= 10) {
						return true;
					}
				}
			}
		}
	}
	return false;
}
```

**Comment by Bombaxo** [comment]
Hi @chhavi2, and thanks for the quick answer. 

Here is how my .ts looks like (I dont include the imports, they are the same):

```
@ViewChild('slideSubNav') slideSubNav: Slides;
@ViewChildren('myScroll') components:QueryList<Scroll>;

  isRefresherEnabled() {
    if (this.slideSubNav) {
       const activeSlideIdx = this.slideSubNav.getActiveIndex();
       if (this.components && this.components['_results']) {
        if (this.components['_results'][activeSlideIdx]) {
          if (this.components['_results'][activeSlideIdx]['_scrollContent']) {
            if (this.components['_results'][activeSlideIdx]['_scrollContent'].nativeElement.scrollTop <= 10) {
              return true;
            }
          }
        }
      }
    }
    return false;
  }
```

Additionally I had to add a css for displaying the content. Otherwise is not visible. 

`ion-slide {
        .scroll-zoom-wrapper{
            display: inline;
        }
`

I have done a console.log for the active index. The behaviour after load is the first 5 logs are undefined and then it takes the right slide active index and print it several times.  

Is it also depending on an scroll listener? After first load isRefresherEnabled is not call anymore.

**Comment by chhavi2** [comment]
Hi @Bombaxo ,
The only difference is that I have an *ngFor in the slides and QueryList Implements an iterable interface (Ref -https://angular.io/api/core/QueryList)  -
<ion-slides #mySlider>
				<ion-slide *ngFor="let slide of slides;let i = index;">
					<ion-scroll class="y-scroll-custom" scrollY="true" #myScroll>
					<some-component></some-component>
					</ion-scroll>
				</ion-slide>
			</ion-slides>
Can you try having an iterable for the ion-slide in ion-slides and rendering the child-components based on the slide id?

And yes it does depend on the scroll listener.
