### ISSUE TITLE
[Web app] window height is not correct in facebook in-app browser

### ISSUE THREAD

**Issue by qcnguyen** [ionic-team/ionic#11243]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
For facebook in-app browser, when use tab-page template, the tab-page is hidden.
However, for safari/chrome, it works fine.

**Expected behavior:**
show tab-page

**Other information:**
On Safari, it works great:
![image](https://cloud.githubusercontent.com/assets/11658651/25086196/cc051bdc-2398-11e7-9c44-8b6d270ed0d3.png)

On facebook in-app browser, the tab is hidden
![image](https://cloud.githubusercontent.com/assets/11658651/25086220/f2a1ceca-2398-11e7-83fa-aa9a99aa8332.png)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. We will look into this.

**Comment by guylillico** [comment]
I'm also desperate to get this resolved for a soon-to-be-launched competition web app. Most of out demographic will be accessing the web app via Facebook mobile in-app browser so this is a critical issue. 

I added this hack to app.component.ts constructor, which seems to help initially:

        // Viewport height hack for Facebook app browser
        window.addEventListener('resize', function() {
            onResize();
        });
        function onResize() {
            document.querySelector('html').style.height = window.innerHeight + 'px'
        };
        onResize();

However, when the device orientation is changed from landscape to portrait or inputs are focussed, the height doesn't respond accordingly, leaving the screen cut off halfway. I'm using Ionic 3.3.0.
