### ISSUE TITLE
Dynamic ion-select items not displaying correct bound value

### ISSUE THREAD

**Issue by schankam** [ionic-team/ionic#11242]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am adding different ion-select dynamically; nevertheless, when I change the value of one of them, the "displayed" value of the others are also updated for an unknown reason. The bound value is correct though.

**Expected behavior:**
The UI should reflect the values bound to each different select independently, not mixing with other select items of the page.

**Steps to reproduce:**

--> http://plnkr.co/edit/wPiUlBnQMaTklF4hTS6Q?p=preview

Go to the Plnkr, and click 4-5 times on the "Add an activity button" - Different ion-item containing an ion-select will be dynamically added. Then try to change the value of the first one, it will correctly update the bound value (which also displayed next the the "Activity [Index] - [Bound value] to double check that", but it will change the displayed value of the second line for no reason (the bound value displayed on the second line is still correct though). What is this really weird behaviour ?

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. We will look into this.
