### ISSUE TITLE
Content Does Not Resize on Keyboard Open

### ISSUE THREAD

**Issue by tylermakin** [ionic-team/ionic#11251]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When opening keyboard in iOS, content does not resize. Content does resize when closing keyboard, which causes blank space at the top or bottom of screen, followed by a second resize that corrects the screen size once the keyboard is fully closed.

**Expected behavior:**
Content should resize with opening keyboard and both footer and header should remain visible so long as `this.keyboard.disableScroll(true);` is called.

**Other information:**
Video of issue: https://streamable.com/4tkoj

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by gvolkan** [comment]
+1, its big issue and ionic team members can not resolve that problem form version 1... 
and its still issue on from 2.0.0 to  3.0.1 ....

**Comment by jgw96** [comment]
Hello @tylermakin, would you mind sharing a minimal repo we could use to reproduce this issue? Thanks!

**Comment by gvolkan** [comment]
i can share a repo from nice guy(thanks for that), https://github.com/yannbf/ionic3-components/blob/master/src/pages/miscellaneous/chat/messages/messages.html

this chat page has a input at bottom and if you focus to input, keyboard open and screen filliping :((( then input control is disappear and  behind the keyboard pad.

**Comment by tylermakin** [comment]
All examples on iPhone 6s running iOS 10

### Analysis
It seems as though the content is being resized at the start of a keyboard disappearing and once a keyboard has fully disappeared.

### Example 1
No modifications.

App displays blank space at top of app when closing keyboard via cancel button, then adjusts to display correctly once keyboard is fully closed.

### Example 2
Added `this.keyboard.disableScroll(true);` on app initialization.

Keyboard appears and covers content at bottom of screen, including the footer. As keyboard disappears, footer jumps to position at top of keyboard then drops to bottom of screen once keyboard is completely gone.

**Comment by hayuki** [comment]
There seems to be an issue on Android as well. E.g: there are two input fields with a login button on the page, and you add a transparent footer with text to the bottom of the page. When you click on the first input and the keyboard pops up, the footer contents overlap the main contents, i.e. the text in the footer overlaps the login button. 

Try to add a footer with text to the Login page on the Ionic Conference App (I tried that) and click on the username input field to reproduce the issue.

**Comment by pitamash** [comment]
ion-col,input,ion-input,col,.text-input {
  position: initial !important;
}
