### ISSUE TITLE
Provide clear direction for developers to report vulnerabilities with SECURITY.md

### ISSUE THREAD

**Issue by bdeanindy** [ionic-team/ionic#11259]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently Ionic OSS code repository does not include any information about what developers should do to submit any security issues or vulnerabilities which they might discover in a formal manner.

**Expected behavior:**
Would like to see Ionic repository include a `SECURITY.md` file at the root, similar to [Discourse](https://github.com/discourse/discourse/blob/master/docs/SECURITY.md) which provides clear guidelines and direction on how to report this type of sensitive information.

**Steps to reproduce:**
N/A

**Related code:**

```
// Example of use on Discourse OSS repo: https://github.com/discourse/discourse/blob/master/docs/SECURITY.md
```

**Comment by jgw96** [comment]
@bdeanindy do you think it would be possible for you to write up a draft of what this should look like? Also, I would think that this should be in all repositories, especially the Cordova ones as those dive into native code, is that assumption correct?

**Comment by bdeanindy** [comment]
Hey @jgw96 I would agree in having this same type feature in any sub-dependencies wherever it is possible to do so.

Here's something to support one reason I suggested this: https://npms.io/search?q=ionic (attached is a screenshot of what I'm seeing).

<img width="861" alt="screen shot 2017-04-20 at 11 21 40" src="https://cloud.githubusercontent.com/assets/2376876/25246199/c432045e-25bb-11e7-9467-0d71779e60bf.png">

I think that authoring this is going to require a higher-level discussion than me just authoring a SECURITY.md document. An example of what I had in mind is on Discourse's SECURITY.md file, here:  https://github.com/discourse/discourse/blob/master/docs/SECURITY.md

Discourse is leveraging **HackerOne Professional / Community Edition** which is free to OSS (Ionic could leverage this valuable free service as well: https://www.hackerone.com/blog/HackerOne-Professional-Free-For-Open-Source-Projects ).

Does that make sense, or would you still like me to try and take a poke at a draft of this?

**Comment by jgw96** [comment]
@bdeanindy ah ok, this definitely makes sense. We should definitely try to carve out some time to have a quick standup with the whole framework team about this. I have never really seen anything like this done with a front end javascript framework, only server side stuff so I think there is some discussing to do on how security things like this relate to the framework. Also, for our projects that deal more with server side or native code, or code that talks to our server side stuff, I think it makes sense to utilize some kind of service like the above almost immediately. @mlynch I'd love to get your input on all this if possible 😃
