### ISSUE TITLE
bug(): view disappears after button press

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#11267]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If I click a button, then open a menu (on Android), half of the view disappears until further action.
The problem occurs both on LTR and RTL (so not exactly what I thought in this video):
https://www.youtube.com/watch?v=wYn_9H3T0Sc

**Expected behavior:**
Visible view to be visible

**Steps to reproduce:**
- Clone https://github.com/AmitMY/ionic-rtl
- Serve (browser, having Nexus 6 as device)
- Home page, scroll to bottom
- Click on the second item (which is a button)
- Open the menu
Reproductabillity - 100%

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.1
    Xcode version: Not installed
```

Might be related to: https://github.com/driftyco/ionic/issues/11052
Although, that one is only iOS and happens in a different time

**Comment by jgw96** [comment]
Hey @AmitMY , thanks for the repo. We will take a look into this.

**Comment by AmitMY** [comment]
A tiny bit more info:
- It happens both on LTR and RTL
- It happens for every button on that page
- This app was created today, by doing `ionic start`, and the only thing edited was `home.html`, `home.ts` and `app.html`'s first line

**Comment by manucorporat** [comment]
I don't think this is because of the click button, but a rendering bug in chrome when the menu appears, I have seen that before randomly...

I have a couple of ideas about how we could fix it `transform: translateZ(0)`? but I worry about negative consequences.

**Comment by mo-mueller** [comment]
I have a similar problem. When I open the menu some parts of the view disappear. I have created a test page and here is the code: [https://pastebin.com/qmBRjEk3](https://pastebin.com/qmBRjEk3)

Here are some screenshots: [http://imgur.com/a/BVOyX](http://imgur.com/a/BVOyX)

It's on an android smartphone. Screenshot 3 is only when I use the android "Back-Button" on my phone. If I close the menu with tapping in the view the view appear again.

And this only happens if I scroll a bit. If i am on the top of my page and open the menu this didn't happen.

Ionic Info:

> Cordova CLI: 6.5.0 
> Ionic Framework Version: 3.0.1
> Ionic CLI Version: 2.2.2
> Ionic App Lib Version: 2.2.1
> Ionic App Scripts Version: 1.3.0
> ios-deploy version: Not installed
> ios-sim version: Not installed
> OS: Linux 4.8
> Node Version: v7.6.0
> Xcode version: Not installed
