### ISSUE TITLE
Pushing a view to the stack from inside a Popover breaks setToRoot()

### ISSUE THREAD

**Issue by josh-m-sharpe** [ionic-team/ionic#11283]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Following a link inside a popover to another page and then calling setToRoot() does not return the app to the root view.

**Expected behavior:**
I expect it to return to the root view

**Steps to reproduce:**
- From your root page navigate to a page with a popover on it
- Open the Popover
- From inside the popover, follow a link that pushes a page to the stack
- From that new page, trigger setToRoot();

I've created a repo that demonstrates this issue here:
https://github.com/josh-m-sharpe/popover-settoroot

You can follow the links on the page all day long and then click SetToRoot and it works as 
expected.  However, if you use the popover to get to page1 or 2 and then click SetToRoot, you do not return to root.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by jgw96** [comment]
Sorry about closing this issue @josh-m-sharpe , we will look into this.

**Comment by josh-m-sharpe** [comment]
@jgw96 v3, not v2 :)

**Comment by josh-m-sharpe** [comment]
@jgw96 bump.  should be v3.
