### ISSUE TITLE
dynamic link segment param fails with '$'

### ISSUE THREAD

**Issue by eikooc** [ionic-team/ionic#11307]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Pushing an object to the navParams with a key that starts with a '$' cannot be used in the segment property of the @IonicPage property to create dynamic links 

**Expected behavior:**

pushing an object that looks like this: `{title: "title", $key: "key"}` would create a dynamic link through the segment property of @IonicPage when I have specified the segment property to look like this: `page/:$key`

**Steps to reproduce:**
Try to push an object that looks like the above specified with `navCtrl.push('page', item)` to a new page that has the @IonicPage looking like: `@IonicPage({name: 'page', segment: 'page/:$key'})`

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.1.0
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.
