### ISSUE TITLE
Input loses focus when toast is presented

### ISSUE THREAD

**Issue by theunreal** [ionic-team/ionic#11309]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When typing in an input field, the input loses its focus when a toast is presented.
I use toats to show new activity in my app and currently it's hard to type in an input when it's loses focus every time toast is presented.

**Expected behavior:**
Input shouldn't lose focus in a toast present.

**Steps to reproduce:**
1. Create an input
2. Present a toast

**Related code:**

```
let toast = this.toastCtlr.create({
message: "Input will lose focus now",
duration: 2000
}).present();
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic v3.0.1. 
Had this issue in v2 aswell
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by Ramayana1202** [comment]
i try this, it woking:

let toast = this.toastCtlr.create({
message: "message",
duration: 2000
}).present().then(rs => {
      this.input.setFocus();
    });

**Comment by mfdeveloper** [comment]
@Ramayana1202 This is a workaround  that doesn't works when the form contains many fields. 

@theunreal and @jgw96 I've fixed this in PR: [!12515](https://github.com/ionic-team/ionic/pull/12515)

**Comment by mfdeveloper** [comment]
@solidrevolution This is a valid "temporary workaround" solution. But, the PR [!12515](https://github.com/ionic-team/ionic/pull/12515) contains a final fix, but was closed by IONIC owners, and needs a totally new code to the `4.0` version. I'm waiting for a stable version to do this.

But, you can get my branch and reference them into your `package.json`!!
