### ISSUE TITLE
ion-searchbar inside modal not allowing click events - only happens on a device/emulator.

### ISSUE THREAD

**Issue by VictorCoding** [ionic-team/ionic#11313]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If you have an `ion-searchbar` in a modal, and have at least one character in the search bar then you can't click any elements on the modal until the second click.

It's worthy to note that if you place a regular `<input>`, that does not happen.

**Expected behavior:**

I should not have to click(tap) twice at the item in order to trigger the click event.

**Steps to reproduce:**
I have a modal with an ion-searchbar. Below the ion-searchbar there is an empty list that gets populated as you search. Each item from the list is a button with `ion-item` attribute directive and also has a click handler to close the modal upon selection. if you have at least one character in the ion-searchbar the items are not clickable(tap) the first time you attempt to click(tap) them. It isn't until the second time that it recognizes the click. The first time to try clicking an item, the keyboard hides but the click event is not triggered until you click it a second time.

**Related code:**

```
import { ViewChild, Component } from '@angular/core';
import { Searchbar, ViewController } from 'ionic-angular';

@Component({
  selector: 'my-modal',
  template: `
    <ion-header>
    </ion-header>
    <ion-content>
      <ion-searchbar #searchbar (ionFocus)="search()"></ion-searchbar>
      <input (input)="search()">
      <ion-list>
        <ion-item (click)="close()">
          <ion-label>
            Hello
          </ion-label>
        </ion-item>
        <ion-item (click)="close()">
          <ion-label>
            Hello
          </ion-label>
        </ion-item>
        <ion-item (click)="close()">
          <ion-label>
            Hello
          </ion-label>
        </ion-item>
        <ion-item (click)="close()">
          <ion-label>
            Hello
          </ion-label>
        </ion-item>
      </ion-list>
    </ion-content>
  `
})
export class MyModal {
  constructor(private viewCtrl: ViewController) {}

  search() {
    console.log('searching')
  }

  close() {
    // this is not being triggered until the second click
    console.log('clicked');
    this.viewCtrl.dismiss();
  }
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.3 Build version 8E162

```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will look into this.

**Comment by minqidev** [comment]
Hi VictorCoding,

I thought I have the some problem. But I fixed it by adding (ionInput)="search($event)" in ion-searchbar

<ion-searchbar [(ngModel)]="search_term" **(ionInput)="getItems($event)"** placeholder="add item" (ionFocus)="search_flag=true"></ion-searchbar>
