### ISSUE TITLE
ion-avatar aspect ratio/overflow is incorrect when src != square

### ISSUE THREAD

**Issue by tmvnk** [ionic-team/ionic#11331]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Current ion-avatar (overflow?) changes aspect-ratio of images in ion-avatar

**Expected behavior:**
Each image in ion-avatar should contain it's origin aspect-ratio

**Steps to reproduce:**
Insert a image with a not a square. For example 375px * 300px

**Related code:**

```
          <ion-avatar item-left>
            <img src="user.profile_pic_url">
         </ion-avatar>
```

**Other information:**
Proposed solution:
ion-avatar{
  height: 36px !important;
  width: 36px !important;
  display: inline-block;
  border-radius: 50%;
  overflow: hidden;
}

ion-avatar img {
  width: auto !important;
  height: auto !important;
  border-radius: 0 !important;
  overflow: visible !important;
  max-height: 100% !important;
  max-width: none !important;
}

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

insert the output from ionic info here
Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1
ios-sim version: 5.0.6
OS: macOS Sierra
Node Version: v7.5.0
Xcode version: Xcode 8.3.1 Build version 8E1000a

**Comment by yannbf** [comment]
Hey, I also have this problem. A way to solve it is to use a div with the image as background and add `background-position: 50% 50%; background-size: cover`.

**Comment by jgw96** [comment]
Hello all, thanks for using Ionic! We will look into this.

**Comment by MvRemmerden** [comment]
Another solution is the following:

ion-avatar img {
    object-fit: cover;
}
