### ISSUE TITLE
Browser return key make  tabs hide or tabs page be white screnn when i use ionic 3 just for web

### ISSUE THREAD

**Issue by YouSirY** [ionic-team/ionic#11349]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

ionic 3 just for web, from pageA(with tabs) into  page B (without tabs) ,using Browser Return Key Back to pageA sometimes be white Screen and sometimes be pageA but missing tabs.
This phenomenon is very frequent。
 
**Expected behavior:**

i think  right is from pageA(with tabs) into Page B (without tabs) ,using Browser Return key back to tabs-Page A ,will show pages A and tabs 

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you share a minimal repo we can use to reproduce this issue?

**Comment by YouSirY** [comment]
I found the reason why tabs-bar disappear.
when Browser Back tabs-page it Generate another page.
![Uploading QQ截图20170428170332.png…]()

**Comment by jgw96** [comment]
Hello @YouSirY , unfortunately, we cannot reproduce this on our end. Would you be able to share a minimal repo we can use to reproduce the issue?

**Comment by YouSirY** [comment]
I create a repo https://github.com/YouSirY/ionic3-lazy-load-demo-v1 thanks for help
