### ISSUE TITLE
Add interfaces for all our public APIs

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#11402]
Sometimes we remove accidentally methods that our users use:
https://github.com/driftyco/ionic/issues/11397

Right now we don't have a good way to ensure this from happening. I think the best way is to move all our documentation + public API to TS interfaces as a contract between ionic and our users, this way we can detect at compiler time if the public API changes.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#245
