### ISSUE TITLE
[3.1.1] Toggle inside toolbar doesn't show properly on iOS

### ISSUE THREAD

**Issue by ThomasKientz** [ionic-team/ionic#11470]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

A toggle inside a toolbar, doesn't show properly on iOS. It appears too low and is unclickable :

<img width="349" alt="capture d ecran 2017-05-02 a 10 59 49" src="https://cloud.githubusercontent.com/assets/10157845/25605152/901a738a-2f26-11e7-8c4a-03a04d480288.png">

**Expected behavior:**
Before 3.1.0 it was showing as expected :

<img width="324" alt="capture d ecran 2017-05-02 a 11 02 09" src="https://cloud.githubusercontent.com/assets/10157845/25605196/d805c0b4-2f26-11e7-88be-cfcee96d8d54.png">

***Step to reproduce***

Use an iPhone or
use safari and user agent set to "Iphone" to test on computer.

**Related code:**

```
<ion-toolbar>
  <ion-toggle></ion-toggle>
</ion-toolbar>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.0.0-rc.0

local packages:

    @ionic/app-scripts              : 1.3.4
    @ionic/cli-plugin-cordova       : 1.0.0-rc.0
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v7.5.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.11 
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by anphu7492** [comment]
Hi, I'm having the same issue

**Comment by anupmca** [comment]
I have same issue but on android platform for few devices only.
bug: Ionic 3.x Toggle Component not rendering on few androids #12390
