### ISSUE TITLE
bug with floating input in slides

### ISSUE THREAD

**Issue by sijav** [ionic-team/ionic#11473]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ X ] **2.x**
[ X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Floating input shows strangely on slides with coverflow, flip or cube animation while the slide is not on their side

**Expected behavior:**
it must be hidden until slide is on their side

**Steps to reproduce:**
create four or more slides, put the slide with floating input in the middle
http://plnkr.co/edit/ly52eX80rg7zkW3fHOTj?p=preview

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.5.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. We will look into this.
