### ISSUE TITLE
Appropriate classes not being applied to ion-item in case of ion-datetime

### ISSUE THREAD

**Issue by naveedahmed1** [ionic-team/ionic#11482]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
It seems that the validation classs on ion-datetime are not being applied properly.
For example I have below formgroup:

```
this.form = fb.group({
            date: [null, Validators.required]
        });
```

And below template:

```

<ion-item>
            <ion-label stacked>Date</ion-label>
            <div class="select-label">Date</div>
            <ion-datetime formControlName="date" pickerFormat="MMMM YYYY" displayFormat="MM/YYYY"></ion-datetime>
</ion-item>
```
Since the date field is required, when the form is submitted its expected that it would apply the appropriate classes to ion-item as it does in case of ion-input:

`item item-block item-md item-label-stacked item-input ng-invalid ng-touched ng-dirty`

**Expected behavior:**

The appropriate classes should be applied to ion-item in case of ion-datetime

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.
