### ISSUE TITLE
Bug in webkit with nested flex

### ISSUE THREAD

**Issue by ghaiat** [ionic-team/ionic#11489]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
As discussed with @manucorporat  and according to this issue : https://bugs.webkit.org/show_bug.cgi?id=150445 
there is perf issues with deeply nested div that use a flex layout.

You should review where you use this kind of layout in ionic until the issue is fixed....

Cheers

**Comment by evenmind** [comment]
Thank you for pointing that. I am using ionic-angular component "grid" which use flex display... 
Hope this issue will be resolved in the next version of ionic!

**Comment by keithdmoore** [comment]
I am experiencing this issue as well.
