### ISSUE TITLE
ion-searchbar focus issues

### ISSUE THREAD

**Issue by Rockforced** [ionic-team/ionic#11484]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ion-searchbar has focus issues. Does not lose focus when touching other areas of the screen. Incidentally the keyboard stays up as well and persists through screen changes, effectively breaking the app.

https://www.youtube.com/watch?v=kXSUjTJPRqM   <- watch

**Expected behavior:**
The search bar should lose focus when other areas of the screen are touched. Further, the search bar should lose focus when transitioning screens.

**Other information:**
https://www.youtube.com/watch?v=kXSUjTJPRqM

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.4.0
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.4.1
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We will look into this.

**Comment by joewoodhouse** [comment]
Any update on when these keyboard fixes will be released? The ion-searchbar is completely unusable on iOS without this (as well as a number of other keyboard related things).
