### ISSUE TITLE
ion-select popover interface does not fire ionCancel

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#11490]
When opening an `ion-select` with popover interface and dismissing it by clicking in the backdrop, the ion-select's ionCancel event is not dispatched.

cc @ciekawy

**Comment by ciekawy** [comment]
@manucorporat are you sure we want `ionCancel` on backdrop click? I can see now `ionChange` to be fired only on Cancel button being explicitly clicked on `action-sheet` overlay.

**Comment by TheDuc** [comment]
I have the same problem, it seems logical to fire ionCancel on backdrop click.
