### ISSUE TITLE
ionic-angular Alert Input Options not exported

### ISSUE THREAD

**Issue by MohammadWaleed** [ionic-team/ionic#11509]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
importing AlertInputOptions gives 
.../ionic-angular-index has no exported member AlertInputOptions

**Expected behavior:**
be able to import and use the interface

**Steps to reproduce:**
1- import AlertInputOptions in code

**Related code:**

```
import { AlertInputOptions } from 'ionic-angular';

```

**Other information:**
the problem appeared after upgrading to ionic 3
and AlertButton is not exported too

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.6
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002

```

**Comment by jgw96** [comment]
Thanks for using Ionic, i can confirm this issue. We will look into this.

**Comment by rodolfojnn** [comment]
Same here

**Comment by sivasankarp** [comment]
HI 

Can any one suggest me in upgrading the ionic 2 app to ionic 3..

Thanks in advance

**Comment by Trokal** [comment]
Would not suggest upgrading to Ionic 3.. I'm facing a lot of issues to name a few AlertInputOptions not being imported....
