### ISSUE TITLE
Refresher closeDuration not working

### ISSUE THREAD

**Issue by cmedinasoriano** [ionic-team/ionic#11536]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
No matter how much milliseconds you specify, refresher always closes with same duration.

**Expected behavior:**
Should close with closeDuration.

**Steps to reproduce:**
Set any value to closeDuration and you will see.

**Related code:**
None

**Other information:**
closeDuration is never used in ionic/refresher.ts

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.6
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v7.7.4
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Could you post a repo we could use to reproduce this issue?

**Comment by cmedinasoriano** [comment]
Hi, I can't create a repo right now but you just need to create a project and in one page "html" add 

`<ion-content>
  <ion-refresher 
    closeDuration="2000" 
    snapbackDuration="2000">
    <ion-refresher-content
      pullingIcon="circles"
      pullingText="Pull to refresh"
      refreshingSpinner="circles"
      refreshingText="Refreshing...">
    </ion-refresher-content>
  </ion-refresher>
<ion-content>`

After running the project you will see that snapbackDuration works but closeDuration doesn't.  But looking at the refresher.ts file it is not using the closeDuration variable but it is using the snapbackDuration.
