### ISSUE TITLE
ion-textarea with ion-label breaks layout on resize

### ISSUE THREAD

**Issue by mebibou** [ionic-team/ionic#11546]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When manually resizing a `textarea` within an `ion-item` and along with a `ion-label`, if the textarea is resized horizontally the label will disappear.

**Expected behavior:**
We should only be able to resize vertically in that case, or no resize at all?

**Steps to reproduce:**
http://plnkr.co/edit/vlykwu?p=preview

**Related code:**

```
<ion-list>
  <ion-item>
    <ion-label>Description</ion-label>
    <ion-textarea></ion-textarea>
  </ion-item>
</ion-list>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.
