### ISSUE TITLE
Segment::value is typed as a string, even though it can be other types

### ISSUE THREAD

**Issue by dudeofawesome** [ionic-team/ionic#11541]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Segment::value is typed as a string, even though it can be other types, such as a number.

**Expected behavior:**
I'm not sure what the best type here would be. `any` might be the best option.

**Related code:**
https://github.com/driftyco/ionic/blob/master/src/components/segment/segment.ts#L71

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.1
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.6
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: OS X El Capitan
Node Version: v6.10.3
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will look into this.
