### ISSUE TITLE
Signature mismatch in Searchbar causing AOT builds to fail

### ISSUE THREAD

**Issue by kulshekhar** [ionic-team/ionic#11598]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
AOT build fails with a message:

```
ERROR in .....ionic-angular/components/searchbar/searchbar.d.ts.Searchbar.html (2,387): Supplied parameters do not match any signature of call target.
```

**Expected behavior:**
The AOT build should succeed

**Steps to reproduce:**
This was caught in a Travis job when upgrading to 3.2. 
- [The repo that has the current setup](https://github.com/kulshekhar/ng-cli-ionic) - it is just a barebones repo. This error can be seen when trying to build [this branch](https://github.com/kulshekhar/ng-cli-ionic/tree/greenkeeper/ionic-angular-3.2.0)
- [The relevant travis job](https://travis-ci.org/kulshekhar/ng-cli-ionic/jobs/230800812)

**Other information:**
This is probably caused due to mismatch in the signatures for the `inputBlurred` and `inputFocused` methods in [searchbar.ts](https://github.com/driftyco/ionic/blob/master/src/components/searchbar/searchbar.ts). These used to have a parameter which was [removed in the latest release](https://github.com/driftyco/ionic/commit/5d562166fcc648dd42b6e7415b2f267e8f7ac141#diff-2feb72bb86a933caa7eeafdb8f17acbfL286). [The corresponding calls from the template](https://github.com/driftyco/ionic/blob/master/src/components/searchbar/searchbar.ts#L37), however, were not updated.

**Comment by kulshekhar** [comment]
It would be great if you can create a minor release if/when this is fixed. I can't be the only one whose CI builds are breaking :)

**Comment by brandyscarney** [comment]
Thanks for the issue and the PR! I've released a nightly with your fix in it:

```
npm install --save --save-exact ionic-angular@3.2.0-201705111630
```

Please keep this issue open. We want to fix our build script so that we get these errors before we release. 🙂
