### ISSUE TITLE
Disabled `ion-datetime` label's color differs from disbaled `ion-input`' label's color.

### ISSUE THREAD

**Issue by Kopleman** [ionic-team/ionic#11592]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Disabled `ion-datetime` label's color differs from disbaled `ion-input`' label's color.  `ion-datetime` label's color has `opacity` that other inputs dont

**Expected behavior:**
Same styles for all input types

**Steps to reproduce:**
[http://embed.plnkr.co/YYcnxbsuwhMX9tXYW4Qn/](plunker)

**Related code:**

```
<ion-content>
  <ion-row>
      <ion-col>
        <ion-item >
            <ion-label>lifeTime</ion-label>
            <ion-input name="lifeTime" type="number" 
                       [disabled]="true"
                       >
            </ion-input>
          </ion-item>  
      </ion-col>
      <ion-col>
        <ion-item>
            <ion-label>From</ion-label>
            <ion-datetime displayFormat="DD/MM/YYYY HH:mm"
                           name="hotTimeEnd" [disabled]="true"
                          ></ion-datetime>
          </ion-item>
      </ion-col>
    </ion-row>     
</ion-content>
```

**Other information:**

![2017-05-10_13-28-11](https://cloud.githubusercontent.com/assets/3992563/25894464/8c160c68-3584-11e7-8258-f24a55ef2264.png)
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by brandyscarney** [comment]
Thanks for the issue! I can reproduce this. It looks like `item-input-disabled` needs to style the `ion-label` similar to datetime/select with opacity like:

```
.item-input-disabled ion-label {
  opacity: 0.4;
}
```

I'll need to confirm this is the correct fix though.

**Comment by Kopleman** [comment]
Or remove that opacity from disabled `datetime`'s label. I think that its more appropriate way becouze all other disabled input's lable dont have it.

**Comment by digaus** [comment]
This is still an issue with ion-select... also I tried to apply 100% opacity to the select-disabled label but it did not work..
