### ISSUE TITLE
Pressing search key (enter key) should automatically hide keyboard

### ISSUE THREAD

**Issue by naveedahmed1** [ionic-team/ionic#11611]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When we type a search term in searchbar and press search button on keyboard, it should hide the keyboard and blur event should fire. In current release, pressing search button once doesn't work, whereas if we press search button twice it closes the keyboard.

**Expected behavior:**
Pressing search button should close keyboard.

To achieve the desired behavior I am using the below code

```
onKey(e) {
        if (e.keyCode == 13) {
            let activeElement = <HTMLElement>document.activeElement;
            activeElement && activeElement.blur && activeElement.blur();
        }
    }
```

`<ion-searchbar (window:keydown)="onKey($event)"></ion-searchbar>`

Because **this.keyboard.close();** doesnt work.

I know its against Angular 2 best practices and we should never touch DOM directly as it prevents running Angular2 app in Webworker. Therefore looking for a fix in original component.

**Comment by nmarseaud** [comment]
I second this. First timer on ionic btw, feels bad when something that easy takes 3 hours of search instead :(
This workaround works tho so that's cool !
Thanks for the post @naveedahmed1 !

**Comment by omaxlive** [comment]
How I solved it:
in the input tag add the Event:  `(keyup.enter)="closeKeyboard()"`
Then `this.keyboard.close();` works fine, Check the plugin documentation if isn't working for you: [https://ionicframework.com/docs/native/keyboard/](url)

**Comment by ruancaetano** [comment]
Using @omaxlive's  answer, this.keyboard.close only removed focus of my input and the keyboard was still on the screen. I solved the problem by removing the input focus before calling the method this.keyboard.close.

**Comment by RS761** [comment]
@omaxlive could you show how it looks like inside of html's input tag ? How exactly to use `(keyup.enter)="closeKeyboard()"` ?

**Comment by ruancaetano** [comment]
@ShimshonMarketing66 I used `@ViewChild('inputSearch') inputSearch` to create a reference of my input in the .ts and then used `this.inputSearch.nativeElement.blur()` to remove the focus.
