### ISSUE TITLE
issue(item-reorder): Should be able to specify a side

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#11637]
**Ionic version:**  (check one with "x")
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] feature request

_Note that I don't think this is a feature request, because hard-coded logic like this shouldn't be there._

**Current behavior:**
You should be able to specify the side that you want an `ion-reorder` to appear. Currently it is hard-coded to be on the RHS. Even moving the reorder icon does not work as the logic is hard coded: https://github.com/driftyco/ionic/blob/master/src/components/item/item-reorder-gesture.ts#L137

**Expected behavior:**
Specify a side that the `ion-reorder` icon should be, and have the logic work when dragging an icon on the specified side.

See here for an unfinished PR: https://github.com/driftyco/ionic/pull/9250

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.9.5
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.0
    ios-sim    : 5.0.10
```

**Comment by AmitMY** [comment]
Is this specifically for RTL, or generally needed?

**Comment by dylanvdmerwe** [comment]
Would probably be useful for RTL, but is a general thing.

**Comment by manucorporat** [comment]
Yeah... so reorder already works in RTL, we just need to add some little logic + css
https://github.com/driftyco/ionic/blob/master/src/components/item/item-reorder-gesture.ts#L137

so the reorder burger shows in the left side in LTR apps.

**Comment by AmitMY** [comment]
@dylanvdmerwe Is this what you need? https://github.com/driftyco/ionic/pull/11639

**Comment by dylanvdmerwe** [comment]
Yes that looks exactly right! Epic @AmitMY

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#243
