### ISSUE TITLE
IonScroll event not update view changes

### ISSUE THREAD

**Issue by lweb20** [ionic-team/ionic#11633]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
IonScroll event not update changes on view.

**Expected behavior:**
Update changes just like other events.

**Steps to reproduce:**
http://plnkr.co/edit/OVrmykJB6rBj46mAEKcW?p=preview

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. This seems to be because the `IonScroll` event is not fired in zone and therefore will not update the view binding. I have created a plunker [here](http://plnkr.co/edit/e9kBJ3JSUErjfOWzOP8N?p=preview) which shows a workaround for this issue.
