### ISSUE TITLE
Input field underline missing when inside ion-card

### ISSUE THREAD

**Issue by DennisSmolek** [ionic-team/ionic#11640]
**Ionic version: **3.2.1**

**I'm submitting a **Bug Report**

**Current behavior:**
When I put an `<ion-input>` inside an `<ion-card>` The bottom border that acts as an underline is being overwritten with some [core css found here](https://github.com/driftyco/ionic/blob/master/src/components/card/card.md.scss#L150)
 **when using the `md` or `default` modes.** 

```
.card-md .item-md.item-block .item-inner {
  border: 0;
}
```
The password field has a border but only because it is also the last child of a list.
<img width="495" alt="screen shot 2017-05-12 at 4 17 29 pm" src="https://cloud.githubusercontent.com/assets/1397052/26017321/9f9a53ec-372e-11e7-8620-10abbd50b9da.png">

Code to produce:
```
<ion-card class="contentBox">
            <ion-card-header>
              <h3>Login</h3>
            </ion-card-header>
            <ion-card-content>
            <ion-list>
              <ion-item>
                <ion-label floating>Email</ion-label>
                <ion-input type="email"></ion-input>
              </ion-item>
              <ion-item>
                <ion-label floating>Password</ion-label>
                <ion-input type="password"></ion-input>
              </ion-item>
            </ion-list>
            </ion-card-content>
</ion-card> <!-- contentBox -->
```

**Expected behavior:**
Should leave the underline intact
Plunker: http://plnkr.co/edit/hSbLqd?p=preview

**Comment by jgw96** [comment]
Thanks, we will take a look into this.

**Comment by jeson114** [comment]
+1 ,got the same issue  
![screen shot 2017-06-18 at 8 32 25 pm](https://user-images.githubusercontent.com/8187342/27261675-66374ade-5465-11e7-8fb5-5ec8ae60a7e1.png)

**Comment by jeson114** [comment]
is this fixed ?

**Comment by DennisSmolek** [comment]
@jeson114 Not that I've seen

**Comment by iget-master** [comment]
Same issue here, @jgw96 the issue have almost 2 months with no fixes, looks a simple css adjustment!

**Comment by iget-master** [comment]
The issue can be fixed by updating the css that @DennisSmolek mentioned to this:

```
.card-md .item-md.item-block:not(.item-input) .item-inner {
  border: 0;
}
```

I've never contributed to this project, so I could not found yet where is the scss that defines this rule.

**Comment by iget-master** [comment]
While ionic-team doesn't fix it, the following rules could be added to your app.scss to fix it:

```
//@todo: Remove after Issue ionic-team/ionic#11640 is fixed
.card-md .item-md.item-block:not(:last-child) .item-inner {
  border-bottom: 1px solid #dedede;
}

.card-md .item-md.item-block:not(.item-input):not(.item-select):not(.item-radio):not(.item-checkbox) .item-inner {
  border: 0;
}
```

**Comment by lsoaresesilva** [comment]
+1

**Comment by wfmf** [comment]
+1, same issue here!

**Comment by airstep** [comment]
+1

**Comment by yaikhomba** [comment]
+1

**Comment by glennlawyer** [comment]
+1

**Comment by LiveLikeCounter** [comment]
+1 
@Ionic, please fix this issue

**Comment by xinbenlv** [comment]
+1

**Comment by waterkamp** [comment]
+1

**Comment by reyco1** [comment]
This worked for me. I just placed it in my pages scss file:

`.card-md .item-inner {
    border-bottom: 1px solid #dedede !important;
}`

**Comment by danielsotopino** [comment]
With @reyco1 solution did this to enable the bottom border on some inputs
.enableBottomBorder {
  .item-inner { border-bottom: 1px solid #dedede !important; }
}

<ion-item class="enableBottomBorder">

**Comment by dsgriffin** [comment]
The above solutions cause issues when working with FormBuilder and their underline validation colour changes, any solution from the team happening for this?

**Comment by musou1500** [comment]
any news? I think fix it from userland is not easy.
I will need to overwrite property value carefully according to `text-input-md-show-focus-highlight` and other some variables.

**Comment by samyfrii** [comment]
None of these work for me. At most it woks for the first time and once you reload after a modification, it stops working. I hope it will work on android.
