### ISSUE TITLE
`<ion-datetime>` strips handlers from custom buttons specified in `pickerOptions`

### ISSUE THREAD

**Issue by JustinPierce** [ionic-team/ionic#11641]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you specify custom buttons for an `<ion-datetime>` component, those buttons will be rendered, but clicking them will not do anything.

**Expected behavior:**
Clicking the custom buttons should execute their `handler` functions.

**Steps to reproduce:**
See the Plunkr below (running Ionic 3.2.1). The custom date picker button and the button on the page itself are hooked up to the same event handler, but only one produces an effect.

http://plnkr.co/edit/mOrDBPcWxXB0L2sFjHFJ?p=preview

**Other information:**
While stepping through the code for the `<ion-datetime>` component, I found that the `handler` property was present until [this line](https://github.com/driftyco/ionic/blob/5a895bb099bb559059bd9950f010d07d796dd5a1/src/components/datetime/datetime.ts#L502) is called in `datetime.ts:

`const pickerOptions = deepCopy(this.pickerOptions);`

It appears that the `deepCopy()` function is stripping off the `handler` property.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.
