### ISSUE TITLE
Problem with IonicPageModule.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [ionic-team/ionic#11662]
Reopen from #11550 

**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I try to use `PageModule` for navigation to page. `this.navCtrl.push('Page')` or `this.navCtrl.setRoot('Page')`.
That good, Because I didn't to import page in `app.module.ts`. But when i use command `ionic run ios -l -c` and save or reload app. It stuck in old page.

In `app.component.ts` I set `rootPage:any = 'Loading';`. This `loading.ts` has some logic about check database `SQLlite`. After check data it would take to other page `this.navCtrl.setRoot('Login')` or `this.navCtrl.setRoot('Tabs')` with data from database.

And yes, When i save the code or reload app. It will not load `'Loading'` page first. It will go to last page from `navController` and I will not get data from `Loading` page.

**Expected behavior:**
If I use old way.  ( Import page to `app.module.ts`)  Every thing is fine. After save the code or reload app. It will start with `Loading` page first. Not stuck in last `navController`.

**Steps to reproduce:**

**Related code:**

Good.
```
this.navCtrl.setRoot(Tabs)
this.navCtrl.push(SomePage)
```

Not good.
```
this.navCtrl.setRoot('Tabs')
this.navCtrl.push('SomePage')
```

**Other information:**
```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.0 
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v6.9.5
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 

```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. To be clear, this only happens with livereload correct?

**Comment by ThunderBirdsX3** [comment]
@jgw96 Yes, only livereload.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2387
