### ISSUE TITLE
MenuController#getMenus() return type mismatch

### ISSUE THREAD

**Issue by ippeiukai** [ionic-team/ionic#11663]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Result of `MenuController#getMenus()` is documented as `Array<Menu>`, but is in fact `Array<MenuInterface>` (where `MenuInterface` is `import { Menu as MenuInterface } from 'ionic-angular/components/app/menu-interface`).

This results in following error from tsc:
```
Type 'Menu' is not assignable to type 'Menu'. Two different types with this name exist, but they are  
unrelated. Property '_menuCtrl' is missing in type 'Menu'. 
```

**Expected behavior:**

Either return type of `MenuController#getMenus()` should be `Array<MenuInterface>` and `MenuInterface` is exported, or return type of `MenuController#getMenus()` should be `Array<Menu>` as in `Menu` type as exported from ionic-angular.

**Steps to reproduce:**

`let currentMenu: Menu = this.menuCtrl.getMenus().find(m => m.enabled);`

**Related code:**

https://github.com/driftyco/ionic/blob/v3.2.1/src/components/app/menu-controller.ts#L285
`Menu` here is not the exported `Menu` type of ionic-angular.

**Other information:**

It was okay with ionic 3.0. We are in progress to update to 3.2.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
$ ionic info

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : OS X El Capitan
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
```

**Comment by jgw96** [comment]
Thanks, we will look into this.
