### ISSUE TITLE
fixed ion-label custom width

### ISSUE THREAD

**Issue by mebibou** [ionic-team/ionic#11666]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using a `fixed` label, the `width` is set to `100px` as seen [here](https://github.com/driftyco/ionic/blob/master/src/components/label/label.scss#L36)

**Expected behavior:**
We should at least have a variable to change that default width, which imho only makes sense on some specific device. I am currently using it on desktop browser and the labels look extremely small.

**Related code:**

```
<ion-item>
  <ion-label fixed>Label that will be ellipsized</ion-label>
  <ion-input type="text"></ion-input>
</ion-item>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by jgw96** [comment]
Thanks, we will look into this.

**Comment by cmaas** [comment]
This should work. Put in **app.scss**:
```
.fixme {
    -webkit-flex: 0 0 200px;
    -ms-flex: 0 0 200px;
    flex: 0 0 200px !important;
    width: 200px !important;
    min-width: 200px !important;
    max-width: 200px !important;
}
```
Then:
```
<ion-label fixed class="fixme">Hello</ion-label>
```
You can probably target specific platforms with variables or different CSS classes.

**Comment by mebibou** [comment]
@cmass yes, I marked this as a feature request not a bug report

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#240

**Comment by aa-telali** [comment]
Hi guys, found this as I was looking to see if it had been fixed..

Shouldn't this have been marked as a bug - It's setting a Fixed label to always be 100px even if the screen is 1100px wide?

Guessing that was supposed to be 100% instead of 100px?
