### ISSUE TITLE
[SearchBar] ionClear event should only fire once, onInput event should not fire while clearing

### ISSUE THREAD

**Issue by hsxfjames** [ionic-team/ionic#11660]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I wrote a very simple function to watch the event object like this:
```javascript
onClear(event: any) {
    console.log("onClear event fired.");
    console.log(event);
}
```
When I click slowly, I can see an event being emitted only once per operation. But twice if I click quickly, one is **mousedown** and another is **click**:
```plain
adv-search.ts:22 onInput event fired.
adv-search.ts:23 testtest
adv-search.ts:32 onClear event fired.
adv-search.ts:33 MouseEvent {isTrusted: true, screenX: 1101, screenY: 301, clientX: 700, clientY: 32…}
adv-search.ts:32 onClear event fired.
adv-search.ts:33 MouseEvent {isTrusted: true, screenX: 1101, screenY: 301, clientX: 700, clientY: 32…}
adv-search.ts:22 onInput event fired.
adv-search.ts:23 undefined
```
and we also can see after it's cleared, onInput event is also fired.

**Expected behavior:**
Since the clear would immediately done on **mousedown**, and the clear can only be done once, it should emit a real clear event not simply just a mouse event.
And even though my searchbar's content is changed(cleared) after a clear click, it should not emit a onInput event since it's not a real input made by user. It differs from a implicit clear operation produced by selecting all and then backspace.

**Steps to reproduce:**
http://plnkr.co/edit/7fLxSYgA98mFbaQvcige?p=preview

**Other information:**
**Ionic info:**
```plain
global packages:
    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.0.0

local packages:
    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.1

System:
    Node       : v6.10.3
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by jgw96** [comment]
Thanks, we will look into this issue.

**Comment by Spartanace1024** [comment]
I have been staring at the `searchbar.js` all day. It seems that all the buttons are firing the events both on `(click)` and on `(mousedown)`. Is there any reason for this?
