### ISSUE TITLE
ion-toolbar close button does not match design

### ISSUE THREAD

**Issue by paulpatarinski** [ionic-team/ionic#11683]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Close button in toolbar on android renders on a separate line from the ion-title

<img width="345" alt="screen shot 2017-05-16 at 1 05 51 am" src="https://cloud.githubusercontent.com/assets/7964134/26091971/fd3ba364-39d3-11e7-9c8d-8741ab9d5ecb.png">

**Expected behavior:**

Close button in toolbar renders on the same line as ion-title

<img width="367" alt="screen shot 2017-05-16 at 1 04 46 am" src="https://cloud.githubusercontent.com/assets/7964134/26091960/f0c4dad8-39d3-11e7-89e7-e29d4503d11a.png">

**Steps to reproduce:**

1. Clone https://github.com/paulpatarinski/tiny-wallet
2. npm install 
3. npm run serve
4. Tap the "Add Card" button on the home screen
5. "Select Card Type" modal toolbar has the bug 

**Related code:**
```
<ion-header>
    <ion-toolbar>
        <ion-buttons>
            <button ion-button (tap)="dismiss()">
                <span ion-text color="primary" showWhen="ios">Cancel</span>
                <ion-icon name="md-close" showWhen="android, windows"></ion-icon>
            </button>
        </ion-buttons>
        <ion-title>
            Select Card Type
        </ion-title>
    </ion-toolbar>
</ion-header>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.0.0-rc.2
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0-rc.2

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.9.2
    OS         : OS X El Capitan
    Xcode      : Xcode 8.2.1 Build version 8C1002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind posting the markup you are using when you get this issue?

**Comment by paulpatarinski** [comment]
Apologies, the repro & markup was part of the comment but was commented out...FAIL

**Comment by jgw96** [comment]
Hello @paulpatarinski , sorry for the delay on this. To fix this issue you should add the `start` attribute to `ion-buttons` as we show [here](https://github.com/ionic-team/ionic-conference-app/blob/master/src/pages/schedule-filter/schedule-filter.html#L3). Thanks for using Ionic!
