### ISSUE TITLE
bug(Slides): Single tap on a zoomed image reset scale

### ISSUE THREAD

**Issue by DavidWiesner** [ionic-team/ionic#11689]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you have multiple slides and you swipe to a page with a zoomable image and you double tap the image and than tap the zoomed image ONCE again. The image would be rescaled to fit the page.

**Expected behavior:**
The image should be only rescaled to normal with another double tap.

**Steps to reproduce:**
1. run plunker
2. slide to the next page
3. double tap image 
4. wait until zoom finish
5. single tap on image

http://plnkr.co/edit/OTnisWLQBKtFG15SKqoh?p=preview

**Related code:**
The bug is in [`swiper-zoom.ts#L524`](https://github.com/driftyco/ionic/blob/24d0052541a31d3dd651780c29fdd1c2e67fa6ee/src/components/slides/swiper/swiper-zoom.ts#L524). You are subscribing to `ionSlideTouchEnd` but actual you want to listen to `ionSlideTransitionEnd`.

```diff
   // Scale Out
-  var transEndSub = s.ionSlideTouchEnd.subscribe(() => {
+  var transEndSub = s.ionSlideTransitionEnd.subscribe(() => {
     onTransitionEnd(s);
   });
   unRegs.push(() => { transEndSub.unsubscribe(); });
```
**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.0
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.5
ios-deploy version: 1.9.1 
ios-sim version: 4.1.1 
OS: macOS Sierra
Node Version: v7.7.4
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! The next release of Ionic (ionic 4) is going to include a rewrite of slides. Once we release a nightly of this release I will update here so that you can give it a try.

**Comment by jgw96** [comment]
Hello! After some testing, I have found that double tap to zoom, single tap to zoom out is actually behavior built into the browser and is standard behavior. If you try opening up a picture in the browser on your device you will see that it has the same behavior. Because this is standard browser behavior and not something we have control over I am going to close this issue for now.

**Comment by DavidWiesner** [comment]
@jgw96 thats maybe right for a browser, but with your project you try to reproduce the user experience for native apps. So you have to compare to the native apps and not to the behaviour of a browser. And the gallery app on android and ios do not reset their scale on a single tap. 

Also the original swiper libarary [`zoom.js#L350`](https://github.com/nolimits4web/Swiper/blob/master/src/js/zoom.js#L350), the event listener is binded to the transition end. This binding is responsible to reset the scale of an image if you swipe to the next page. 
So i think it is a typo in your code which introduce the wrong behaviour of the single tap and remove the "reset scale after swipe to another slide" functionality. So please reopen this issue.
