### ISSUE TITLE
Tapping on selected tab, scroll to top problem

### ISSUE THREAD

**Issue by dackom** [ionic-team/ionic#11685]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I am on current tab, and scrolled a bit down, pressing on that tab again it goes to top by using this piece of code:
`
	ionSelected() {
		this.content.scrollToTop();
	}
`
But, if scroll is still moving, (if you start scroll and release your finger of the screen, like making it stops naturally), if you tap on that tab while scrolling it goes to top, but after that, it continues to scroll.

**Expected behavior:**
It should stop natural scrolling, go to top, and stop there.

**Steps to reproduce:**
Just create empty tab project put some content in it. It is hard to replicate this in browser, so simulator or real device should be used. And this piece of code should done it:

**Related code:**

```
import { Component, ViewChild } from '@angular/core';
import { NavController, IonicPage, Content } from 'ionic-angular';

@ViewChild(Content) content: Content;

	ionSelected() {
		this.content.scrollToTop();
	}

```

**Other information:**
Here is video demonstration of problem:
http://dacko.suonline.net/scrolling.mov

You will first see how it is working properly when scroll is still. And then second time you will see when its rolling, how it goes wrong.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 3.2.1
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v7.7.3
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by jgw96** [comment]
Thanks, we will look into this.
