### ISSUE TITLE
bug(Slides): pan on zoomed image not preventing sliding to next/prev page

### ISSUE THREAD

**Issue by DavidWiesner** [ionic-team/ionic#11690]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you you pan a zoomed image the slider also slides to the next/previous page.

**Expected behavior:**
The slider should be permit sliding to the next/previous page until you pan to the corner of the image.

**Steps to reproduce:**
http://embed.plnkr.co/HwYIQs2CEFyluUO3cJt0/

1. double tap to zoom the image
2. try to pan the image
3. the slider starts to slide to the next page

**Related code:**
The bug is in [`swiper-zoom.ts#L512`](https://github.com/driftyco/ionic/blob/8bc827a531ff4b9dd1276b92e0766d34b559f5ba/src/components/slides/swiper/swiper-zoom.ts#L512). The event `s.touchEvents.move` is not defined. Furthermore you passing the the object `{passive: false, zone:false}` as config to `plt.registerListener`. But the subscription require a non passive listener to prevent the event from bubble up to the slides controller that handle the page slide event.

So the fix will look like this:
```diff
--- src/components/slides/swiper/swiper-zoom.ts	(date 1494926548000)
+++ src/components/slides/swiper/swiper-zoom.ts	(date 1494938667000)
@@ -509,9 +509,9 @@
   for (var i = 0; i < slides.length; i++) {
     slide = slides[i];
     if (slide.querySelector('.' + CLS.zoomContainer)) {
-      plt.registerListener(slide, 's.touchEvents.move', (ev: TouchEvent) => {
+      plt.registerListener(slide, s._touchEvents.move, (ev: TouchEvent) => {
         onTouchMove(s, plt, ev);
-      }, evtOpts, unRegs);
+      }, {zone:false}, unRegs);
     }
   }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.0
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.5
ios-deploy version: 1.9.1 
ios-sim version: 4.1.1 
OS: macOS Sierra
Node Version: v7.7.4
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! The next release of Ionic (ionic 4) is going to include a rewrite of slides. Once we release a nightly of this release I will update here so that you can give it a try.

**Comment by nibytes** [comment]
Please fix it, or how apply fix by @DavidWiesner  self and use?
