### ISSUE TITLE
Toast is stealing input focus.

### ISSUE THREAD

**Issue by RyanHow** [ionic-team/ionic#11692]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When a toast shows, any active input fields lose focus.

**Expected behavior:**
The toast should in no way affect focus

**Steps to reproduce:**
Have an async task open a toast while you have an input focussed.

I've made an example here

http://plnkr.co/edit/7lBnWL2ucp8N9qAHSAmt?p=preview

-->

**Related code:**

```

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.9.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by RyanHow** [comment]
Just to note that this is still happening on the latest version of Ionic. Sorry I'd dig in and try and fix it but I haven't had any time to work on this project.

**Comment by mfdeveloper** [comment]
Hello @jgw96 and @RyanHow I did a PR [!12515](https://github.com/ionic-team/ionic/pull/12515) that contains a suggestion solution for this problem. I hope that help you 😄

**Comment by m0nzderr** [comment]
Is there any solution or workaround to this?

**Comment by mfdeveloper** [comment]
@m0nzderr Which version of ionic are you using ? `3.9.x` ? If you wish, I can do a _rebase_ of `[toast-improvements]` branch with this version, and you can use the changes of PR [!12515](https://github.com/ionic-team/ionic/pull/12515) like this:

```json
{
"dependencies": {
    "ionic-angular": "mfdeveloper/ionic#toast-improvements"
  }
}
```

**Comment by redwolf2** [comment]
As a workaround, if you know the input, you can do:

```
@ViewChild('myInput') myInput: TextInput;

	public showToast(): void {

	let toast = this.toastCtrl.create({
		message: 'Message goes here',
		duration: 1000,
		position: 'bottom'
	});
		toast.onDidDismiss(() => {
		setTimeout(() => this.myInput.setFocus(), 300);
	});
	toast.present();
}
```
