### ISSUE TITLE
A modal presented from a modal does not trigger `onWillDismiss` when dismissed.

### ISSUE THREAD

**Issue by JustinPierce** [ionic-team/ionic#11702]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If a modal is presented from another modal, dismissing the top-most modal will not trigger the `onWillDismiss` handler. The `onDidDismiss` handler is triggered as expected.

**Expected behavior:**
Both the `onWillDismiss` and `onDidDismiss` handlers should be triggered.

**Steps to reproduce:**
Demo Plunker: http://plnkr.co/edit/yjjl5XHd8ru69V8vPDqC?p=preview

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Good find! We will take a look at this.
