### ISSUE TITLE
Ion-item wraps its content with ion-label if there's no ion-label provided

### ISSUE THREAD

**Issue by mahpour** [ionic-team/ionic#11704]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ion-label is automatically added to the contents of an ion-item if a non-ionic control is used inside ion-item causing unwanted spacing (margin + padding) around that control. 

**Expected behavior:**
If there's no ion-label in the content of ion-item, it should not add one 

**Steps to reproduce:**

In my case I have borrows a md-select from material design repo inside a ion-item box.
the ion-labels are not compatible with md-XXXX components to get floated and align well with others. 

**Related code:**

```
<ion-item>
                    <md-select no-margin [placeholder]="'LABEL' | translate " col-12 id="fromAccount" required name="test" formControlName="fromAccount">
                      <md-option *ngFor="let account of (accounts$| async).accounts | fromAccountPipe" [value]="account">
                        <ion-row>
                          <ion-col text-left> <strong>{{ account.productName }}</strong> {{ account.accountNumber.slice(-4) }}</ion-col>
                          <ion-col text-right>{{account | accountBalancePipe}}</ion-col>
                        </ion-row>
                      </md-option>
                    </md-select>
</ion-item>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.9.0
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by ChezRD** [comment]
Add item-content attribute

**Comment by ChezRD** [comment]
Because by default ion-item is complex component. If you don't need its behaviour - write your own or use styled divs

**Comment by RHinderiks** [comment]
@ChezRD This is still an issue. Using ion-avatar which seems to be really dependent of ion-item for decent sizing. Adding item-content does not seem to add anything to fix the problem.

**Comment by cankemik** [comment]
What i'm trying to achieve is to dynamically generate inputs in `ion-item` but it messes up by wrapping the component with `ion-label`

simple-input component
```
<ion-label stacked>NAME</ion-label>
<ion-input type="text"></ion-input>
```

dynamic usage:

```
<ion-item-sliding>
                    <ion-item>
                        <ng-template dynamic-template
                                     [template]="'<simple-input></simple-input>'"
                                     [extraModules]="[extraModules]">
                    </ion-item>
                </ion-item-sliding>
```

result is like below :
```
<ion-item class="item item-block item-ios item-input">
    <div class="item-inner">
        <div class="input-wrapper">
            <ion-label class="label label-ios">
                <simple-input>
                    <ion-label stacked="" class="label label-ios">NAME</ion-label>
                    <ion-input type="text" class="input input-ios" ng-reflect-type="text"><input
                            class="text-input text-input-ios" dir="auto" ng-reflect-klass="text-input"
                            ng-reflect-ng-class="text-input-ios" type="text" aria-labelledby="lbl-20" autocomplete="off"
                            autocorrect="off" placeholder="" ng-reflect-type="text"></ion-input>
                </simple-input>
            </ion-label>
        </div>
        <ion-reorder>
            <ion-icon name="reorder" role="img" class="icon icon-ios ion-ios-reorder" aria-label="reorder"
                      ng-reflect-name="reorder"></ion-icon>
        </ion-reorder>
    </div>
    <div class="button-effect"></div>
</ion-item>
```

Item-content doesn't seem to work. Are there workarounds to fix this issue or any options to disable wrapping?

**Comment by RHinderiks** [comment]
@cankemik It has been a while but in the end i just created my own ion-items

**Comment by cankemik** [comment]
@RHinderiks oh. my worst fear came true. thanks for quick response.

**Comment by brandyscarney** [comment]
This is no longer an issue in v4 since it is required to write the `ion-label` to use it. We will not be including a fix for this in v3, so please continue to use the existing workarounds or style the label's margin, thanks!

```
.item .label {
    margin: 0;
}
```
