### ISSUE TITLE
Events Unsubscribe with second param.

### ISSUE THREAD

**Issue by Bernardoow** [ionic-team/ionic#11716]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I using Events. One first page in functionionViewWillEnter I subscribe and in ionViewWillLeave I unsubscribe.

In moment when I unsubscript like this [1]Works.
But when I put like this [2]. Maybe can be a bug. I don't know.

[1] this.events.unsubscribe('pedido-acoes:atraso'); 
[2] this.events.unsubscribe('pedido-acoes:atraso', () => {});

**Expected behavior:**

I was expected this [2] unsubscribe event.

**Steps to reproduce:**

**Related code:**
this.events.unsubscribe('pedido-acoes:atraso'); 
this.events.unsubscribe('pedido-acoes:atraso', () => {});

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.10.3
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Could you post a plunker we could use to reproduce this issue?

**Comment by xmellado** [comment]
Hi!
@Bernardoow I think you are not using properly Ionic Events. You must subscribe and unsubscribe the very same object, as explained [here](https://forum.ionicframework.com/t/events-pub-sub-how-to-unsubscribe-in-lifecycle-hook/50596/5?u=xme) or you can remove all subscribers [at the same time](https://github.com/ionic-team/ionic/issues/8235).
IMHO, Ionic events are a bit limited. I prefer to use a shared service between the components that has one of the RxJS subject types. The source class can publish using a service function that does next on the subject, and the target class can observe the stream obtaining the subject as an observable, like in Observable Data Services.

Here you have an example of this kind of service:
```
import {Injectable} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import {Subject} from 'rxjs/Subject';

import {Booking} from '../../common/model/booking';


@Injectable()
export class BookingEventsService
{
    private _newChannel: Subject<Booking> = new Subject<Booking>();


    constructor()
    {
    }

    publishNew( booking: Booking )
    {
        this._newChannel.next( booking );
    }

    newChannel(): Observable<Booking>
    {
        return this._newChannel.asObservable();
    }
}
```

Hope it helps. Regards,
Xavi

**Comment by jgw96** [comment]
Hello, all! After further review, this seems like more of a support question. Because of this, I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
