### ISSUE TITLE
Segment button visual activation not working when the value is number

### ISSUE THREAD

**Issue by danielfpedro** [ionic-team/ionic#11718]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If the value of the segment button is `number` the visual activation of the segment is not being applied.
Again, only the visual activation is not working, the segment change is working.
For the record, if you click on the segment button the visual activation works, the bug just happens if you change the value of the segment model via code.

*Important: Value being `string` is working fine.

**Steps to reproduce:**
Just Watch

Not working:
http://plnkr.co/edit/WndLNaZuUiyBdwhzrCe9?p=preview
Working:
http://plnkr.co/edit/ZX6JrLSw7Eb66j3HPW65?p=preview

**Comment by jgw96** [comment]
Thanks, we will look into this.

**Comment by danielfpedro** [comment]
You tagged as `v2` but is `v3`.

**Comment by bushybuffalo** [comment]
I encountered the same issue (using v3.6.0) when binding the [value] attribute to an object. It works fine when setting the value to a property of the object though. I'm using segments as form inputs so I really need to be able to bind my segments to the full object.

http://plnkr.co/edit/EdhRbSgeUiLaAQm67bo6?p=preview
