### ISSUE TITLE
how to write the ion-slides with auto play in ionic3

### ISSUE THREAD

**Issue by vidyachilukuri** [ionic-team/ionic#11727]
I am new to ionic3 i am using ion-slides in my home page, but it is not work with auto play. ionic code:

```
<ion-slides autoplay=300>
      <ion-slide  *ngFor = "let banners of bannersImage">
        <img src={{banners.image}}>
      </ion-slide>
    </ion-slides>
```
error message:
Uncaught TypeError: Cannot read property 'hasAttribute' of undefined
    at autoplay (main.js:43827)
    at startAutoplay (main.js:43870)
    at initSwiper (main.js:43816)
    at Slides._initSlides (main.js:55290)
    at main.js:55311`enter code here`

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by brandyscarney** [comment]
I'm not able to reproduce this using the code provided. Can you paste the output of `ionic info` or give us a repository that we can use? Thanks!

**Comment by mindhells** [comment]
I've the same problem when loading slides asynchronously.
I've managed to start autoplay from controller after loading the slides and calling update method on Slides object. But there's something wrong with this approach:  when an autoplay cycle is completed it starts again on 2nd slide instead of 1st one... having you got the loop option set to true.

**Comment by zhihuwang** [comment]
I got the same error on 3.4.0, I have to remove the autoplay property,and invoke the method,
this.slidesEL.startAutoplay(); but it still does not work without error.
Runtime Error
Cannot read property 'hasAttribute' of undefined
Stack
TypeError: Cannot read property 'hasAttribute' of undefined
    at autoplay (http://localhost:8100/build/main.js:44430:20)
    at startAutoplay (http://localhost:8100/build/main.js:44473:5)
    at initSwiper (http://localhost:8100/build/main.js:44419:9)
    at Slides._initSlides (http://localhost:8100/build/main.js:60572:102)
    at http://localhost:8100/build/main.js:60593:19
Ionic Framework: 3.4.0
Ionic App Scripts: 1.3.7
Angular Core: 4.1.2
Angular Compiler CLI: 4.1.2
Node: 5.8.0
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by TonyLuo** [comment]
@brandyscarney the bannersImage should be loaded from server, and the page render very fast to trigger the error. pls try to use setTimeout to reproduce the error.

**Comment by TonyLuo** [comment]
I fix it by adding ngOnChanges to startAutoplay 
```
ngOnChanges(changes: SimpleChanges) {

      setTimeout(()=>{
        if(this.advertisementList && this.advertisementList.length > 0){
          this.slides.freeMode = true;
          this.slides.autoplay = 2000;
          this.slides.speed = 500;
          this.slides.loop = true;
          this.slides.startAutoplay()
        }

      },1000)
    }
  }
```

**Comment by vidyachilukuri** [comment]
<ion-slides  autoplay="5000" loop="true" speed="3000">
      <ion-slide  *ngFor = "let banners of bannersImage">
        <img src={{banners.image}}>
      </ion-slide>
    </ion-slides>

**Comment by gopi2mohan** [comment]
`changes: SimpleChanges` what does this reffers to @TonyLuo  and can you give some explaination for that
