### ISSUE TITLE
Cannot select ion-segment by default

### ISSUE THREAD

**Issue by ix-xerri** [ionic-team/ionic#11743]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

I'm trying to select an ion-segment by default and it's not preselecting. 

this is the code I have in the html

`<div [ngSwitch]="gmap">
    <ion-list *ngSwitchCase="'showMap'">
	</ion-list>`

and in the component I have a simple `gmap: string;` and `this.gmap = "showMap";`. The tabs work as intended but I cannot preselect a segment by default. This use to work in Ionic2 but doesn't work when upgrading to Ionic3

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. Could you post a repo or plunker we could use to reproduce this issue?

**Comment by ix-xerri** [comment]
try have a look at https://plnkr.co/edit/VtAh7WM1ZO9AqFdaQRoE?p=preview

**Comment by ix-xerri** [comment]
@jgw96 you added a label that it's for v2. I'm currently upgrading to v3 with this being left. I look at [ion-segments](https://ionicframework.com/docs/api/components/segment/Segment/) docs and nothing has changed. This was implemented in v2.

**Comment by ix-xerri** [comment]
Upgraded to 3.3.0. Note that the select work as I set 'gmap' to 'showList' but not 'showMap'. So selecting the first tab does not work.

**Comment by ix-xerri** [comment]
any updates on this issue?

**Comment by ix-xerri** [comment]
Here is more information. I am using ion-tab but I tried to set a timeout to select the tab I want, thinking that it is somehow being set before the page loads but it also fails.

**Comment by monad98** [comment]
Similar problem here, with the "puppies, kittens" demo, 'segment-activated' class is not applied to initially selected ion-segment-button.

**Comment by danishin** [comment]
I can also confirm this with Ionic 3.5.0. It seems like`segment-activated` class is simply not applied to the currently selected segment.

**Comment by ix-xerri** [comment]
Solved after reading [this page](https://forum.ionicframework.com/t/ion-segment-issues/97241/3). Disabled changeDetection

**Comment by danishin** [comment]
Can also confirm that removing ChangeDetectionStrategy.OnPush from @Component does make it work.
I guess somewhere in changeDetection there is a bug?

**Comment by aslaugsollilja** [comment]
no news on this??

**Comment by elvisgn** [comment]
The more detailed issue/workaround/future is here [https://github.com/ionic-team/ionic/issues/9374](url)

**Comment by himanshu1018** [comment]
i want to add the auto-scrolling on "segments" to center of the page which are being activated, when i click the segment link on side-menu bar? how do i achieve that, please help?
thanks in advance

**Comment by elvisgn** [comment]
@himanshu1018 : Kindly open a separate ticket for this as they are unrelated issues...in any case you can use the ngOnInit method, get the height of the content element and call `this.content.scrollTo(0, contentHeight/2, 300);`

**Comment by javalight** [comment]
If your issues was ChangeDetectionStrategy.OnPush breaking it: this worked for me. 
constructor(public ref: ChangeDetectorRef){}

ionViewDidLoad() {
    this.ref.markForCheck();
  }
