### ISSUE TITLE
DeepLinker: if rootNav has tab pages, rootNav.push() url is incorrect.

### ISSUE THREAD

**Issue by pikotea** [ionic-team/ionic#11756]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

rootPage has tab pages.

Pages
- TabPage -> url is "tab" and tabUrlPath is "tab-a".
- PageA -> url is "a". under "tab-a".
- PageB -> url is "b"

first app url is "xxx.com/tab/tab-a/a".
if execute `app.getRootNav().push(PageB)` , url is "xxx.com/**b**/tab/tab-a/a".

**Expected behavior:**

url is "xxx.com/b".

It is probably caused by returning the end of childNav irrespective of the page being displayed.

https://github.com/driftyco/ionic/blob/master/src/navigation/nav-controller-base.ts#L964

stacks:
https://github.com/driftyco/ionic/blob/master/src/navigation/deep-linker.ts#L114
https://github.com/driftyco/ionic/blob/master/src/components/app/app.ts#L208
https://github.com/driftyco/ionic/blob/master/src/components/app/app.ts#L315

**Comment by jgw96** [comment]
Hello, thanks for using Ionic, we will look into this!

**Comment by pikotea** [comment]
Thanks for your response!
