### ISSUE TITLE
virtualScroll page offset not considered

### ISSUE THREAD

**Issue by voegtlel** [ionic-team/ionic#11755]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Having a virtualScoll below some content with a large height makes items disappear too early.

**Expected behavior:**
It seems like the offset within the page is not taken into account when determining the scroll position. Expected behavior is obvious: The items should disappear/appear when out of view, not before, regardless of the offset within the page.

**Steps to reproduce:**
To reproduce have content with a large height before the virtualScroll. A workaround seems to be to increase the bufferRatio (but in the end I could just render the whole list).

Tested on desktop browser.

http://plnkr.co/edit/hAnh355BJAb9QiSChIaU?p=preview

**Related code:**

```
<ion-item>
  <ion-textarea rows="30"></ion-textarea>
</ion-item>
For demonstration, the following list only has a bufferRatio of 2. Also works with
a higher ration but requires the preceding space to be larger (approx one
window size should be enough though).
<ion-list [virtualScroll]="items" approxItemHeight="85px" bufferRatio="2">
  <ion-item *virtualItem="let item">
    <ion-label>
      <h2>{{item.title}}</h2>
      <h3>{{item.subTitle}}</h3>
      <p>{{item.text}}</p>
    </ion-label>
  </ion-item>
</ion-list>
```

After resizing the window, it seems to work again.
A better workaround seems to be:
```
@ViewChild(VirtualScroll) _virtualScroll: VirtualScroll;
ngAfterViewInit() {
  setTimeout(() => {
    this.ngZone.run(() => {
      this._virtualScroll.resize();
    });
  }, 1000);
}
```
although I can't get it to work in the Plunkr.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
(I use meteor CLI, thus no `ionic info`). Plukr should be up-to-date and demonstrates the issue.

Used Packages:
```
"@angular/core": "^4.1.1",
"ionic-angular": "^3.2.0",
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We will look into this soon.

**Comment by HugoHeneault** [comment]
I had this issue too, and while waiting for a fix, your workaround is working great!! Thanks!

**Comment by danielcrk** [comment]
Same issue here.

**Comment by HugoHeneault** [comment]
@danielcrk Have you tried @voegtlel's workaround? ;)
