### ISSUE TITLE
ion-select does not trigger form (change) event

### ISSUE THREAD

**Issue by doctorstal** [ionic-team/ionic#11764]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Changing value of ion-select inside the form does not trigger form change event.

**Expected behavior:**
Changing value of ion-select inside form should trigger form change event, like ion-input does.

**Steps to reproduce:**

1. Add form with change event handler on the page
2. Add ion-select component to form
3. serve, change ion-select value
4. Observe that handler is not triggered on change event

plnkr:
https://embed.plnkr.co/rlMRzE/

As you can see - editing ion-input value triggers change handler, but selecting from ion-select does not.

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by phpfs** [comment]
Hi :)

I also have this issue :(

**Comment by root-io** [comment]
Try with `(ionChange)`

**Comment by doctorstal** [comment]
@root-io Thanks for your suggestion. 
In my project I've added same handler to `ion-select(ionChange)`  as to the `form(change)`. 
It works as workaround and provides desired functionality (looks like `form.value` is updated silently).
But that's just ugly hack and the bug still needs to be fixed.

**Comment by phpfs** [comment]
(ionChange) works for me :) Thanks!

**Comment by j3gb3rt** [comment]
(ionChange) is not working for me when the ion-select is inside a form. The set function is not ever getting called. I also see, (ionChange) is no longer listed in the docs for [ion-select](https://ionicframework.com/docs/api/components/select/Select/#output-events) under output events.
Has it been removed in the 3.4.2?
