### ISSUE TITLE
No way to subscribe to app:online/offline via Events service

### ISSUE THREAD

**Issue by stalniy** [ionic-team/ionic#11773]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
no way to subscribe to `window`s `online` event through `Events` service. The code which should provide this kind of logic exists but `Events` service provided incorrectly in `IonicModule`

**Expected behavior:**
be able to subscribe to `app:online`, `app:offline` and `app:rotated` events via `Events` service

**Steps to reproduce:**
1. Inject `Events` service into component
2. Subscribe to `app:rotated` event
3. install app to phone
4. rotate phone -> callback subscribed to event was not called

**Related code:**
There is a function `setupProvideEvents` which creates an instance of `Events` service inside but then doesn't expose this instance anywhere. 

The problem is in `IonicModule` configuration  in this line https://github.com/driftyco/ionic/blob/master/src/module.ts#L421 
```
{ provide: APP_INITIALIZER, useFactory: setupProvideEvents, deps: [ Platform, DomController ], multi: true }
```

it should be changed to 
```
{ provide: Events, useFactory: setupProvideEvents, deps: [ Platform, DomController ] }
```

And `Events` service should be removed from providers here https://github.com/driftyco/ionic/blob/master/src/module.ts#L436 

**Alternative solution**
It's possible to leave module configuration as is but additionally inject `Events` service into `setupProvideEvents`, so the line should look like this:
```
{ provide: APP_INITIALIZER, useFactory: setupProvideEvents, deps: [ Events, Platform, DomController ], multi: true }
```
And instead of creating new `Events` instance `setupProvideEvents` function should use provided instance.

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into us.

**Comment by stalniy** [comment]
I recommend second approach because this way client application will be able to easily substitute `Events` service without diving into details of its configuration

**Comment by stalniy** [comment]
@jgw96 @manucorporat any updates on this? Could you please check PR?
