### ISSUE TITLE
Bug ion-refresher and ion-segment

### ISSUE THREAD

**Issue by wac2007** [ionic-team/ionic#11777]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using together, the refresher overlaps the content
<img width="1280" alt="captura de tela 2017-05-24 as 16 07 24" src="https://cloud.githubusercontent.com/assets/1892294/26421176/7657e4ec-409b-11e7-818b-5aab64e17da7.png">

My Code
```
<ion-content>
  <ion-refresher (ionRefresh)="getSales($event)">
    <ion-refresher-content
      pullingText="Puxe para atualizar">
    </ion-refresher-content>
  </ion-refresher>
  
  <ion-segment [(ngModel)]="tab">
    <ion-segment-button value="store">
      Loja
    </ion-segment-button>
    <ion-segment-button value="financial">
      Financeiro
    </ion-segment-button>
    <ion-segment-button value="seller">
      Vendedor
    </ion-segment-button>
  </ion-segment>

  <div [ngSwitch]="tab">
    <ion-list *ngSwitchCase="'store'">
      ...
    </ion-list>
    ...
  </div>
</ion-content>
```

I solved using css
```
.scroll-content {
   background: #FFF;
}
```

I don't know how to do pull requests and I don't know if this is the best approach but fixed my problem.
<img width="1280" alt="captura de tela 2017-05-24 as 16 07 35" src="https://cloud.githubusercontent.com/assets/1892294/26421331/173dc9e4-409c-11e7-8394-70e3c8c31eb7.png">

**Comment by Khalid-Nowaf** [comment]
the segment has no background color, that is why it shows the refresher behind it, usually, you won't need to use the segment to be scrolled down when you refresh, so you can add the segment in the header 
````html
<ion-header no-border>
  <ion-navbar>
    <ion-title>
      Ionic Blank
    </ion-title>
  </ion-navbar>

   <ion-segment >
    <ion-segment-button value="store">
      Loja
    </ion-segment-button>
    <ion-segment-button value="financial">
      Financeiro
    </ion-segment-button>
    <ion-segment-button value="seller">
      Vendedor
    </ion-segment-button>
  </ion-segment>

</ion-header>
````    

if you really need the segment to be used after the refresher, you can fix this by setting the background color for the segment only,
````css
ion-segment {
  background-color: $background-color;
}
````

**Comment by sonicwong** [comment]
You should wrap "ion-segment" with "ion-toolbar" and put it under "ion-header".
