### ISSUE TITLE
Events on elements with ion-checkbox inside ion-item do not work

### ISSUE THREAD

**Issue by ajcrites** [ionic-team/ionic#11775]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you have an `ion-item` that contains an `ion-checkbox` (and probably some other controls), you cannot use any events on elements inside of the same `ion-item`.

**Expected behavior:**
You should be able to trigger events on other items inside of the same `ion-item`

**Steps to reproduce:**
Example: http://plnkr.co/edit/zZCUfRbTLqhMd6LQ4CS8?p=preview

Create an `ion-item` layout that contains an `ion-checkbox` and another element that has a click/tap event:

```
<ion-item>
   <ion-label>Accept the <a (click)="showTermsAndConditions()">terms &amp; conditions</a></ion-label>
   <ion-checkbox></ion-checkbox>
</ion-item>
```

Notice that the checkbox is toggled, but the other desired event appears to be swallowed.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.9.0
Xcode version: Xcode 8.2.1 Build version 8C1002```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.
