### ISSUE TITLE
Refactor Events service to use rxjs

### ISSUE THREAD

**Issue by stalniy** [ionic-team/ionic#11770]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`Events` service doesn't use `rxjs` and developer is forced to manage subscriptions imperatively / manually. It's also increases amount of boilerplate code in an app

**Expected behavior:**
`Events` service provides interface based on `rxjs` `Observable`s what will allow to easily subscribe / unsubscribe and combine with other observable application wide events. In order to do that `Events` service need to provide a `topic(name: string)` method which returns `Subject` observable for a specific topic

**Related code:**
This will allow to do something like this

```ts
import { Subject } from 'rxjs'

@Component({ ... })
export class MyComponent {
   constructor(private events: Events) {
     this.destroyed = new Subject()
   }

   ngOnInit() {
      this.events.topic('app:offline')
         .takeUntil(this.destroyed)
         .subscribe(() => this.doStuff())
   }

  ngOnDestroy() {
    this.destroted.next(true)
    this.destroyed.complete()
  }
}
```

**Other information:**
I'm pretty sure that it can be easily done without breaking changes. I propose to rewrite `subscribe` and `unsubscribe` methods to use `Subject` instead of array of handlers and add additional method `topic` which exposes `Subject` for easier interactions with other application observables

**Comment by stalniy** [comment]
I can provide a PR for this if @manucorporat  and @jgw96 are ok with suggestion

**Comment by stalniy** [comment]
Just for comparison, the same thing can be achieved with the current interface only this way:
import { Subject } from 'rxjs'
```
@Component({ ... })
export class MyComponent {
   constructor(private events: Events) {
     this.offlineListener = this.doStuff.bind(this)
   }

   ngOnInit() {
      this.events.subscribe('app:offline', this.offlineListener)
   }

  ngOnDestroy() {
     this.events.unsubsribe('app:offline', this.offlineListener)
  }
}
```
And the same should be done for every subscribed event

**Comment by jgw96** [comment]
Hey @stalniy, this sounds like a good idea to me, feel free to throw together a PR!

**Comment by stalniy** [comment]
@jgw96 I just checked the codebase and it looks like it's impossible to keep backward compatibility for `Events`. 
There are 3 issues:
1. `publish` returns an array of responses (result of each handler invocation). This can't be handled with `Subject`.
2. `publish` accepts multiple parameters but `Subject.next` accepts only. This can be handled with wrapper function (here is also possible to put a warning that this behavior is deprecated)
3. In order to be able to unsubscribe `handler` from `Subject` I need to track all subscriptions internally (mapping of `handler` function to its subscription). So, we can leave it for some time and add warning that `Events#unsubscribe` method is deprecated

I can create a PR for what I did with 2 and 3 but 1 introduces breaking changes. So, what do you think is the best?
* introduce bigger breaking changes (no responses from `publish`, `publish` accepts only 1 argument, remove `unsubscribe`)
* introduce small breaking change in `publish` method
* try to find a solution  have to return responses from `publish` method

**Comment by stalniy** [comment]
I've chosen more aggressive refactoring :) So, waiting for comments!
