### ISSUE TITLE
Ion-tab breaks the behavior of ion-segment. Old bug occurring again, now on 3.1.1 version

### ISSUE THREAD

**Issue by lpsantana** [ionic-team/ionic#11786]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In an ionic's tabs based app, if we click in a tab button it breaks the behavior of ion-segment. 

**Expected behavior:**
Normal switches in the ion-segment elements of the screen after touch any tab.

**Other information:**
The solution for this error was released in (2017-01-11) by Ionic Team closing the follow issues: #9392 #9811. 

All topics about it was closed after this release but seems the error is occurring again in the version 3.1.1.
I am using 3.1.1 and facing exaclty the same problems with ion-tabs breaking the behavior of ion-segment like the issues reported before.

Is this error returned from the ashes just for me?

**Ionic info:**
Cordova CLI: 7.0.0 
Ionic Framework Version: 3.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.6
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.3
Xcode version: Not installed

**Comment by lpsantana** [comment]
Hey guys, here is a plunker related to the old issues. Im facing the same problem now.

 (http://plnkr.co/edit/QB4vcaQuIhKLYXSgyGvl?p=preview)

Steps to replicate:

    Load above Plunker.
    Tap "Go to Tabs"
    Observe the segment switches at the top (currently you can switch between "Camera" and "Bookmark").
    Tap the log out tab (bottom-right).
    Tap "No".
    Repeat step (3) and observe no switch.

**Comment by jgw96** [comment]
Thanks for opening an issue with us @lpsantana . Does this happen on the [latest release of ionic](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#330-2017-05-24) ?

**Comment by lpsantana** [comment]
Unfortunately the same behavior occur in the latest released yesterday from you guys ;(

Anyone else?

**Comment by adibbz** [comment]
@lpsantana I've ran into the same issue. I load some data in `ionViewWillEnter()` but it does not update when changing tabs by `this.tabs.select(3)`. 

Any idea of a fix @jgw96?
