### ISSUE TITLE
Angular height animation does not work well with itemSliding / ion-item

### ISSUE THREAD

**Issue by ajcrites** [ionic-team/ionic#11781]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`height` is not properly animated in some cases when using `ion-item` or `ion-item-sliding`. 
`ion-item` seems to require a wrapper for `height` animations to work properly.

`ion-item-sliding` will not animate this properly at all if it is not a child of `ion-list` or if it has a child that wraps its `ion-item`. In the latter case, its contents will not display [although the documentation does specify the parent/child requirements](https://ionicframework.com/docs/api/components/item/ItemSliding/).

However, this prevents you from creating a component that either contains an `ion-item-sliding` or its intended contents since there is no way to remove component elements in Angular. This means that if you want to get the correct height animation behavior for ion-item-sliding, you have to have all of the intended contents directly in the template.

**Expected behavior:**
You should be able to slide up/down ion-item / ion-item-sliding in lists. You should be able to do this with the `height` animation more freely.

**Steps to reproduce:**
Example code: https://plnkr.co/edit/duIXnwtZn5MkyHb9MbTi?p=preview

This contains several examples of different layouts of `ion-item` and `ion-item-sliding` with various containers within in `ion-list`

#### ```<ion-item *ngFor [@anim]>```
* Remove: This seems to shrink the height up till the contents of the item, and then it disappears. 
* Add: item pops into view

#### ```<div *ngFor [@anim]><ion-item>```
* Remove: Animates as expected _unless_ it's the last element in the list
* Add: item pops into view

#### ```<ion-item-sliding *ngFor [@anim]>```
Works as expected for both add and remove!

#### ```<component-containing-ion-item-sliding *ngFor [@anim]>```
Animations do not work.

#### ```<div *ngFor [@anim]><component-containing-ion-item-sliding>```
Similar to using a wrapper around `ion-item` above:

* Remove: Animates as expected _unless_ it's the last element in the list. _However_, the next element will slide under the visible element.
* Add: Element pops into view, but its wrapper seems to animate

#### ```<ion-item-sliding *ngFor [@anim]><component-containing-ion-item>```
Element contents are not displayed

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.9.0
Xcode version: Xcode 8.2.1 Build version 8C1002```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will look into this.

**Comment by adnansenyurt** [comment]
Hi, is there a resolution of this? or a workaround?
