### ISSUE TITLE
Rendering issue with ionic-infinite-scroll and ionic-list

### ISSUE THREAD

**Issue by wilkesreid** [ionic-team/ionic#11792]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
It seems to appear when scrolling to the bottom of an ion-list on iOS

**Expected behavior:**
There should show the default background instead of the strange visual artifact shown.

**Steps to reproduce:**
This is happens to me only sometimes, so I'm not sure of exact steps to always reproduce.

Here's a gif of the issue I'm seeing: https://bureaugravity.com/gif/bug.gif

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v7.4.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.8 
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Could you post a repo we could use to reproduce this?

**Comment by wilkesreid** [comment]
[This repo.](https://github.com/wilkesreid/ionic-app)

The initial page is a log in form, but you can use `tester` as the username and `ionic` as the password to get past it.

Also I'd like to note that this issue I've had doesn't occur in the browser when using ionic serve. It so far has only happened when running the app on an actual device, primarily iOS.
