### ISSUE TITLE
Bar buttons splitting into multiple lines in Android 4.4.2

### ISSUE THREAD

**Issue by lenilsondc** [ionic-team/ionic#11793]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Toolbar with multiple buttons breaks the buttons into a new line on Android 4.4.2.

![ionic-tabs-bar-button-bug](https://cloud.githubusercontent.com/assets/13702123/26467834/9b265b80-416a-11e7-915d-7c6bcbc91f59.png)

**Expected behavior:**

It's expected to all buttons be kept into a single line.

**Steps to reproduce:**

Start a simple tab app in `--v2` mode.

````bash
ionic start testingBarbuttons tabs --v2
````

Add some buttons into the home navbar or whatever page you want.

````html
  <ion-navbar>
    <ion-title>Home</ion-title>
    <ion-buttons end>
      <button ion-button icon-only>
        <ion-icon name="pin"></ion-icon>
      </button>
      <button ion-button icon-only>
        <ion-icon name="calendar"></ion-icon>
      </button>
      <button ion-button icon-only>
        <ion-icon name="calendar"></ion-icon>
      </button>
    </ion-buttons>
  </ion-navbar>
````
Run in an Android 4.4.2 device.

````bash
ionic run android --target Android4_4Device
````

**Other information:**

I managed to solve this by adding a floating left behaviour to the `bar-button` class but only for `android4_4` platform.

````scss
.platform-android4_4{
  .bar-button {
    float: left;
  }
}
````
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: 5.0.3 
OS: macOS Sierra
Node Version: v5.1.0
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Are you using crosswalk?

**Comment by lenilsondc** [comment]
No, I'm not using crosswalk to run the webview,

**Comment by tkem** [comment]
@lenilsondc: See also #10480 for a possible workaround

**Comment by jgw96** [comment]
Hello @lenilsondc , for reasons that I explain [here](https://github.com/ionic-team/ionic/issues/11445#issuecomment-298348758) we require using crosswalk for Android below 4.4.4. Thanks for using Ionic!
