### ISSUE TITLE
virtualScroll stops rendering after a certain amount of scroll - solution

### ISSUE THREAD

**Issue by raxim1** [ionic-team/ionic#11798]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
As i have found the culprit, i would like to share with you.

1, I have used virtuallScroll with infiniteScroll which worked fine, but after some attempt the virtualScroll leaves empty area.

2, The list hasn't got the right height, so it's cutting off from the screen. I have realized that the virtualScroll height is not filling up the whole area. I tried to introduce some sort of "manual resize", but it didn't help.
@ViewChild(VirtualScroll) scrollRef: VirtualScroll;
scrollRef.resize();

3, I have  noticed that the dom has been correctly rendered.

4, When i have introduced large treshold, it was working better, but after 1000 element or so, it stopped working again.

approxItemHeight does not really respond, as does not matter whether i set to '100px' or '170px'. (new version does not need that, i had problem previously with it, but it's solved with the upgrade)

5, ionInfinite has been called several times. (probably because the item has been in the dom, but the infiniteScroll tag, even if it has been disappeared was shown up hidden after the last really visible item in the list)

6, There is one tiny note what to mention, virtualScroll is scrolling a little bit faster downwards, then upwards. (as i have complex tags, and used canvas initially by mistake, the rendering was too slow, i was able to notice)

**Expected behavior:**
I have expected that the virtualScroll resize works automatically. The height was out of the sync.

**Workaround**
I have made a dirty workaround for a while, i'm not sure what it does, but i think this blocks other ionic items to be rendered. (like ion-item in ion-grid etc.)

.virtual-scroll {
    contain : inherit !important;
}

It was contain: content previously.

In the list exactly similar items are rendered. (same height, there is grid and card in it, some button and the image kept changing)

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Thanks for opening a detailed issue with us! We will look into this.

**Comment by rolaru** [comment]
@jgw96 , I'm having a similar issue as @raxim1 on my android phone (Xperia Z3 compact - Android 6.0.1), considering that my virtual scroll list is rendered in a container **div**  that's 35% of the screen height. The first 15 items out of the ~300 render, only.  I've investigated hte issue in _virtual-scroll.ts_ and _virtual-util.ts_ files and it seems that the **scrollUpdate** is not triggered. Please see:

`this._scrollSub = this._content.ionScroll.subscribe(this.scrollUpdate.bind(this));`

virtual-scroll.ts line 773.

**Comment by rolaru** [comment]
Hey, @raxim1 , @jgw96 , I've mananaged to solve my issue by **adding an extra DIV wrapper** around the virtual scroll list:
`
<div class="friends-list__container">
  <div> 
    <ion-list [virtualScroll]="friendsList">
      <ion-item *virtualItem="let friend">
        {{friend.name}}
      </ion-item>
    </ion-list>
  </div>
</div>
`

**Comment by masimplo** [comment]
Wrapping ion-list inside a div causes a forced reflow warning on chrome and navigating from another pages toward the page where virtual scroll is located has a large delay (due to the reflow). This needs a better solution imho.

**Comment by rolaru** [comment]
@masimplo, you're right. It seems that the solution would be to make the **scrollUpdate** method trigger correctly.
