### ISSUE TITLE
"mode" attribute missing from docs?

### ISSUE THREAD

**Issue by shawnlan** [ionic-team/ionic#11796]
I remembered seeing `mode` attribute on docs. It sets `mode` individually for components. For example:

`<ion-range mode="md"></ion-range>`

I tested it. It still works, but I don't see it on docs anymore? Is it deprecated?

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by mhartington** [comment]
This has to do with some input refactors we introduce a few releases ago. Since all input components extend a common base, we need to go back and figure out how to make sure these are documented.

**Comment by brandyscarney** [comment]
@mhartington This issue is related: https://github.com/driftyco/ionic-site/issues/1074

**Comment by brandyscarney** [comment]
This issue was moved to ionic-team/ionic-site#1145
