### ISSUE TITLE
Using the preference 'OverrideUserAgent' on config.xml will break the module 'Platform'

### ISSUE THREAD

**Issue by helderdiniz** [ionic-team/ionic#11790]
**Ionic version:**
[x] **3.x**

**I'm submitting a ...**
[x] bug report

**Current behavior:**
I'm currently trying to define the UserAgent used on my app, and for that I'm using the attribute [OverrideUseragent](https://cordova.apache.org/docs/en/latest/config_ref/) on cordova's config.xml. But it's causing me a problem while using the [Platform module](https://ionicframework.com/docs/api/platform/Platform/).
Whenever I use `this.platform.is('platformName')` it will return me false even though I'm on the device that I'm sending by argument. This only happens **if I define an user-agent that is not from the device**.
I've done some digging and the var `_platforms` returns `["cordova", "core"]` if I use the example useragent below on an Android device.

Here's the example user-agent that I'm using on config.xml `<preference name="OverrideUserAgent" value="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" />`
P.S: I'm trying to force a Windows user-agent for testing purposes.

**Expected behavior:**
By defining the preference `OverrideUserAgent` on `config.xml`, if I use `this.platform.is('android')` on an Android device, it should return `TRUE`.

**Steps to reproduce:**
* Add this preference on the file config.xml:
`<preference name="OverrideUserAgent" value="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" />`
* Now try to check the return of the platform.is method is correct, using the platform you're using (not the browser). Example for an Android device: `this.platform.is('android')`

**Related code:**
N/A

**Other information:**
```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.
