### ISSUE TITLE
Click() is not working for anchor tags in Ionic framework

### ISSUE THREAD

**Issue by dorjon** [ionic-team/ionic#11807]
I am currently working on automation of the ionic app and facing issue like `click()` is not working for anchor tags`<a>`. And its working for `<button>`.

Please help me out to how can I overcome this issue.

Let me put the piece of code.
HTML:-
```
<a class="hello" ng-click="changeView('Home')"></a>
```

Automation:- 
```
var elem = document.querySelector('.hello');
elem.click();
```

**Comment by Khalid-Nowaf** [comment]
Try to console.log(elem), and share the output

**Comment by rapropos** [comment]
I think this is a better fit for [the support forums](https://forum.ionicframework.com/).

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/]. Thanks for using Ionic!
