### ISSUE TITLE
Loading Controller error - getting passed upstream?

### ISSUE THREAD

**Issue by neo-split** [ionic-team/ionic#11803]
**Ionic version:**  (check one with "x")
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report

**Current behavior:**

Its a run-time error where which gets thrown at an unexpected place (see code below).
The error (**_this._loading.dismiss is not a function**) gets thrown and displayed as an Alert. But if you see my code, Im using Alert only to show errors that are thrown by Database operation. Errors related to Loading control are logged to the console. 

So somehow the Loading control error is getting mixed with database error? Have a look at the code to see what Im saying.

**Expected behavior:**

Loading should be displayed, then async action takes place, then dismissed and User transitions to different page.

**Steps to reproduce:**

**Related code:**

```
  // Display loading ctrl
  displayLoading() :Promise<any> {
    return this._loading = this._loadingCtrl.create({
    }).present()
  }

  // Dismiss loading ctrl
  dismissLoading() :Promise<any> {
    return this._loading.dismiss();
  }

  registerUser() {
    this.displayLoading()
      .then( () => {
        this._authSrv.createNewUser(this._registerUserForm.value.email, this._registerUserForm.value.password)
          .then( (data) => {
            console.log('User created :' + data);
            this._loading.dismiss()
              .then(() => {
                this._userSrv.uid = data.uid;
                this._nav.setRoot('UserProfilePage');
              })
              // dimissLoading error
              .catch(console.log)
          })
          // create new user error
          .catch ((error) => {
            this.showAlertToUser(error);    // <=======  error shown in an Alert
          })
      })
      // displayLoading error
      .catch(console.log)
  }

  showAlertToUser(error: Error){
    let alert = this._alertCtrl.create({
      title: error.name,
      message: error.message,
      buttons: [
        {
          text: "Ok",
          role: 'cancel',
        }
      ]
    });
    alert.present();
  }

```

**Other information:**
Here is the photo of how the error pops up as an Alert

![image](https://cloud.githubusercontent.com/assets/6942628/26488320/af5ffb00-420b-11e7-8d26-a17d9ce2d2b6.png)

Im using Ionic 3x and Firebase 4, all the library's are up to date.

    "angularfire2": "^4.0.0-rc.0",
    "firebase": "^3.9.0",
    "ionic-angular": "3.1.1",

    "@ionic/app-scripts": "^1.3.6",
    "@ionic/cli-plugin-cordova": "^1.2.1",
    "@ionic/cli-plugin-ionic-angular": "^1.2.0",

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. Could you create a plunker with the minimum use case required to get this bug?

**Comment by neo-split** [comment]
I figured out the error. I had assigned Promise<any> to my _loading variable as I was trying to save few more lines of code :|
```
    // Display loading ctrl
  displayLoading() :Promise<any> {
    return this._loading = this._loadingCtrl.create({
    }).present()     // <===== mistake here
  }
```
correct the code should be
```
    // Display loading ctrl
  displayLoading() :Promise<any> {
    return this._loading = this._loadingCtrl.create({
    })
    this._loading.present()     // <===== mistake here
  }
```

**Comment by jgw96** [comment]
Ahh, thanks for the info and glad you found your error 😃
