### ISSUE TITLE
TypeError: platform.trim is not a function (ionic cordova build android --prod)

### ISSUE THREAD

**Issue by sunilkconsultant** [ionic-team/ionic#11809]
**Ionic version:**  

[x] **3.x**

**I'm submitting a ...** 
[x] bug report

**Current behavior:**
After creating a new app with CLI ionic start xyz sidemenu --id xyz.com.app, move to app folder with CLI cd xyz, run CLI ionic cordova build android --prod, i get below error in red (TypeError: platform.trim is not a function)

? What platform would you like to build: ios, android: **android**
_TypeError: platform.trim is not a function_

**Expected behavior:**

it should build for android.

**Steps to reproduce:**

After creating a new app with CLI ionic start xyz sidemenu --id xyz.com.app, move to app folder with CLI cd xyz, run CLI ionic cordova build android --prod

? What platform would you like to build: ios, android: **android**
_TypeError: platform.trim is not a function_

**Ionic info:**

```
global packages:

    @ionic/cli-utils : 1.1.2
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.8.6 
    ios-sim    : 5.0.8 

```

**Package.json**

 ```
"dependencies": {
    "@angular/common": "4.1.2",
    "@angular/compiler": "4.1.2",
    "@angular/compiler-cli": "4.1.2",
    "@angular/core": "4.1.2",
    "@angular/forms": "4.1.2",
    "@angular/http": "4.1.2",
    "@angular/platform-browser": "4.1.2",
    "@angular/platform-browser-dynamic": "4.1.2",
    "@ionic-native/core": "3.10.2",
    "@ionic-native/splash-screen": "3.10.2",
    "@ionic-native/status-bar": "3.10.2",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.3.0",
    "ionicons": "3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.11"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.7",
    "@ionic/cli-plugin-cordova": "1.2.1",
    "@ionic/cli-plugin-ionic-angular": "1.2.0",
    "typescript": "2.3.3"
  },
```

**Comment by rapropos** [comment]
Should probably be migrated to CLI.

**Comment by reviloera** [comment]
getting same error when I run  `ionic cordova build --release android`

**Comment by asjain84** [comment]
use this command: cordova platforms add android

**Comment by satnam348** [comment]
getting same error when I run ionic cordova build

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2363

**Comment by ABr751** [comment]
the plugin is not working.I tried it in ios .It's not showing a trim bar nor its automatically trimming
