### ISSUE TITLE
TypeError: AppScripts.processProviderRequest is not a function

### ISSUE THREAD

**Issue by ianlikono** [ionic-team/ionic#11818]
Short description of the problem:

Running npm ionic g provider authService aborts with the following error:
TypeError: AppScripts.processProviderRequest is not a function
**Which version are you using?**
 @ionic/cli-utils : 1.2.0
 Ionic CLI        : 3.2.0

@ionic/app-scripts              : 1.1.4
@ionic/cli-plugin-ionic-angular : 1.2.0
Ionic Framework                 : ionic-angular 3.3.0

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2364
