### ISSUE TITLE
If I add the "ion-slides" in "ion-content" or "div", the slides are not in visible.

### ISSUE THREAD

**Issue by mediaon** [ionic-team/ionic#11814]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.2.1**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If I add the "ion-slides" in "ion-content" or "div", the slides are not in visible.

**Expected behavior:**

Have the slides inside ionic-content visible.

**Steps to reproduce:**
http://plnkr.co/edit/Mejtst3RDiJqCLISYzhH?p=preview

**Related code:**

```
<ion-content >
  <ion-slides pager>

    <ion-slide style="background-color: green">
      <ion-content>
        <h2>Slide 1: Inside content is not visible</h2>
      </ion-content>
    </ion-slide>

    <ion-slide style="background-color: blue">
      <h2>Slide 2</h2>
    </ion-slide>

    <ion-slide style="background-color: red">
      <h2>Slide 3</h2>
    </ion-slide>

  </ion-slides>
</ion-content>

**Comment by jgw96** [comment]
Hello thanks for opening an issue with us. It looks like plunker is down at the moment, but i will check this once it comes back up.

**Comment by jgw96** [comment]
Hello @mediaon , in the latest chrome your plunker works fine for me. Because of this I am going to close this issue for now but please feel free to open a new issue if you are still running into this issue.
