### ISSUE TITLE
App should have an event when start to load LazyPage

### ISSUE THREAD

**Issue by yozman** [ionic-team/ionic#11821]
now the events
```
      'viewDidEnter',
      'viewDidLeave',
      'viewDidLoad',
      'viewWillEnter',
      'viewWillLeave',
      'viewWillUnload'
```
always works when the page loaded,

there should be an event can subscribe when start to load LazyPage

I want to show a progress bar but I there isn't event when page start load

**Comment by AmitMY** [comment]
- Please correct your issue to follow the template
- Perhaps, instead, start a loader from `viewWillLeave` of your current page, to `viewWillEnter` of the desired page. Not sure how you are planning to make it a progress bar, as it is 0%, 100% no middle state..

**Comment by astec** [comment]
@AmitMY how about loading modules throw something like https://www.npmjs.com/package/angular-progress-http ?

```
import { ProgressHttp } from "angular-progress-http";
 
export class SomeClass {
    constructor(private http: ProgressHttp) {
        this.http
            .withDownloadProgressListener(progress => {
               console.log(`Downloading ${progress.percentage}%`); })
            .get("/app/moduleN")
            .subscribe((response) => {console.log(response);})
    }
}
```

**Comment by AmitMY** [comment]
@astec I am not saying it is not possible, just that using lifecycle for it is not the place..
Perhaps, there can be a a subscription in the Lazy Loading module, that would emit every percentage something like this method supplies. Or maybe it is not worth the overhead. That is why I would again request @yozman to follow the issue template, so this can be discussed as a feature request.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2366
