### ISSUE TITLE
Ionic g component generates wrong import

### ISSUE THREAD

**Issue by mflmartin** [ionic-team/ionic#11838]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
**ionic g component MyComponent**
Creates the wrong import inside my-component.module.ts

imports: [
    IonicPageModule.forChild(MyComponent),
  ],

**Expected behavior:**
The correct import should be:
imports: [
    IonicModule,
  ],

(If you want to provide the ionic module base). But in any case, generating a component should not generate the same import as if it was a page.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : browser 4.1.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by danielsogl** [comment]
I created a PR for your issue.

**Comment by jgw96** [comment]
Thanks @danielsogl for fixing this issue! I am going to close this issue as i just merged your PR.
