### ISSUE TITLE
Slides not working in --prod build with Crosswalk webview

### ISSUE THREAD

**Issue by siberianbearr** [ionic-team/ionic#11846]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Slides are not working as expected. Swiping to a slide for example does not work properly, the transition stops mid way when you take the finger off the screen. Also the sliding is not "limited", so you can swipe into infinity after you have swiped over all slides(it works as expected in non-prod build). Also the pager is not showing.

**Expected behavior:**

"Normal" slides

**Steps to reproduce:**

Create a new project `ionic start crosswalk-test blank`
Add platform `ionic cordova platform add android` 

Add slides to home page `
    <ion-slides pager="true" paginationType="bullets">
       <ion-slide>
            <h1>Slide 1</h1>
        </ion-slide>
        <ion-slide>
            <h1>Slide 2</h1>
        </ion-slide>
        <ion-slide>
            <h1>Slide 3</h1>
        </ion-slide>
    </ion-slides>
`
Add crosswalk `ionic cordova plugin add cordova-plugin-crosswalk-webview@2.3.0 --save`

And finally build an apk `ionic cordova build --prod`

**Other information:**
Note that this happens only when using the `--prod` flag. If I run the build process without it, the slides work as expected. 
Tested it with Android 4.3, 5.1 and 6.0 and happens on all of them

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Unfortunately, I cannot reproduce this issue locally on my Nexus 6 running Android 7.1.2 or my 1st gen moto g running Android 4.4.4. Could you please post a repo we could use to reproduce this?

**Comment by siberianbearr** [comment]
[Here](https://github.com/siberianbearr/ionic-slidestest) is the repo

**Comment by jgw96** [comment]
Hello @siberianbearr , sorry for the delay on this. I do not see slides being used anywhere in that repo?

**Comment by siberianbearr** [comment]
You can find the slides under crosswalk-test/src/pages/home/home.ts

**Comment by siberianbearr** [comment]
Some new info on this?

**Comment by zjhiphop** [comment]
Same issue, any updates?

**Comment by Mavlarn** [comment]
same issue, I am using latest verison of ionic and crosswalk. The slide is just stop, and hand on where is move to. for example, I move the slide between 2 slide page, and it will just stop there.

**Comment by paololoddo** [comment]
I have the same issue with the lastest version of Ionic and crosswalk plugin. I cannot see the slider selector and slides are dragged horizontally without animations. Is there a way to fix it?

**Comment by AspenLuoQiang** [comment]
so?how to fix it?

**Comment by piyushsharma21** [comment]
same issue any update
