### ISSUE TITLE
popToRoot does not close modals

### ISSUE THREAD

**Issue by Daskus1** [ionic-team/ionic#11849]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
Since version 3.2.0 when I call `this.appCtrl.getRootNav().popToRoot();` and set a new root-page (`this.appCtrl.getRootNav().setRoot('LoginPage')`) the modals remain open.
This is probably due to #11499 

I don't even know if this is the way you intended to do this but I could not find anything documented on how to close every page/popover/modal from outside a page. I think this is really important if a user logs out and needs to be pushed to a login/home page.

**Expected behavior:**
When I call `this.appCtrl.getRootNav().popToRoot();` and then push a new root-page every page (modal, popover) should be dismissed.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 3.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.6.0
Xcode version: Not installed

```

**Comment by AmitMY** [comment]
Your expected behavior is incorrect - 
> When I call this.appCtrl.getRootNav().popToRoot(); and then push a new root-page every page (modal, popover) should be dismissed.

Modals and popover are not a part of the navigation stack, and thus should not be closed when popping.

I do think that you are correct in that that if an initiator of a popover or a modal is destroyed, they should be too.

**Comment by Daskus1** [comment]
@AmitMY thanks for you're response. So how would I go about closing all modals/popovers/overlays from an external service which has `appCtrl` injected? I cannot find anything about such a usecase in docs/forum.

**Comment by AmitMY** [comment]
@Daskus1 I don't know of a way to currently do so.
I think it calls for a refactor as I mentioned in the comment above, or perhaps add a `dismissAll` method like for `loadingCtrl` or `toastCtrl`

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by jayeshanandani** [comment]
@Daskus1 : any luck you had doing this?

**Comment by chicobaptista** [comment]
In case someone else stumbles here:

I had the same issue, [this](https://ionicframework.com/docs/api/navigation/NavController/#navigating-from-an-overlay-component) helped me solve it.
basically I did the following:
``` 
this.appCtrl.getRootNav().setRoot(HomePage);
this.navCtrl.pop;
