### ISSUE TITLE
$tabs-tab-color-inactive does not change color on android (md)

### ISSUE THREAD

**Issue by charlouze** [ionic-team/ionic#11847]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When settings a value for $tabs-tab-color-inactive, it's working well with ios and wp but not with md. The color stays the default one.

**Expected behavior:**
The color should be the one from the $tabs-tab-color-inactive variable.

**Steps to reproduce:**
* create a ionic project with tabs
* add the variable $tabs-tab-color-inactive to the variables.scss with a custom color.
* debug your app using chrome

**Related code:**
[L36 of ionic.theme.default.md.scss](https://github.com/driftyco/ionic/blob/master/src/themes/ionic.theme.default.md.scss#L36) that is not using the variable.

**Other information:**
I can create a pull request if needed !

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : browser 4.1.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Feel free to create a PR and we can review it. Here is our [contributing doc](https://github.com/ionic-team/ionic/blob/master/.github/CONTRIBUTING.md) if you need any help on creating that PR.

**Comment by brandyscarney** [comment]
Closing this issue as this is the desired behavior, please see my comment here: https://github.com/ionic-team/ionic/pull/11874#issuecomment-306221848
