### ISSUE TITLE
Unable to write provisioning.plist

### ISSUE THREAD

**Issue by pdxwebdev** [ionic-team/ionic#11852]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
$ ionic package build
then I choose ios
then in the ionic console, I see the build failed.
the output is: "Unable to write provisioning.plist"

**Expected behavior:**
successful build

**Steps to reproduce:**
As seen above. I'm pretty new to ionic so I don't really know what to include.

For Ionic V1 issues - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

For Ionic issues - http://plnkr.co/edit/z0DzVL?p=preview
-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by danielsogl** [comment]
Can you run ionic cordova build iOS locally without any errors?

**Comment by pdxwebdev** [comment]
Correct. The build succeeds locally.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2365
