### ISSUE TITLE
Ionic 3.2.0 Scrolling in a basic blank starter app causes the app to crash due to increasing memory usage

### ISSUE THREAD

**Issue by gitdisrupt** [ionic-team/ionic#11853]
**Ionic version:**
[ X] **3.2.0**

**I'm submitting a ...**
[X ] bug report

**Current behavior:**
Scrolling in a basic Ionic App causes the App to crash.
After about an hour of scrolling, the app crashes with the following error message in the XCode console:` Terminated due to memory issue`

_Unfortunately, this makes it impossible to move forward using Ionic as a framework for real world deployment. Sincerely hope someone can look into this as we opened this issue before as it related to ionic 3.1 but the issue was closed when it really should not have been? Any help addressing this greatly appreciated. Or, are we missing something? If so, how could this behavior be considered normal or OK? Is there something we should be doing inside of our Page / Component to clear this memory manually?_

I am attaching a screenshot and video of this behavior:
![screen shot 2017-05-29 at 8 55 55 pm](https://cloud.githubusercontent.com/assets/5187647/26564625/39d6bbbe-44b1-11e7-991e-88661718b425.png)

Video attached below....

**IMPORTANT NOTE:** This behavior occurs on an **ACTUAL DEVICE**, and **NOT** in a simulator. 
I ran this test on an iPhone 6s running iOS 10.2 and also 10.3. 

**Expected behavior:**
Memory should eventually be released, but it is not. If i were to continue to scroll, it will eventually crash. See the attached video below...

**Steps to reproduce:**
Create an ionic app using the CLI using the `blank` template.
command line:` ionic start memorytest blank`
The **ONLY** modification done was to edit `src/pages/home/home.html` template. I added the following paragraph 10 times inside of `<ion-content padding>`:
```
<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent convallis nisi at metus auctor, nec egestas mauris vestibulum. Curabitur id pretium massa. Vestibulum maximus sagittis imperdiet. Cras pretium dui a dolor scelerisque iaculis. Fusce convallis velit in mi ultrices, ac imperdiet arcu pulvinar. Sed ornare luctus nulla a suscipit. Praesent pulvinar quis quam ac tristique. Vivamus id nibh sed risus tincidunt hendrerit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse egestas sapien quis orci tempor finibus.
  </p>
```
command line: `ionic cordova platform add ios`
i was prompted to install: `@ionic/cli-plugin-cordova` 
then, in XCode i applied a provision profile to the app in-order to test it on an actual device.
command line: `ionic cordova build --prod`
then in XCode i run the app and monitor memory usage while scrolling the home page continuously up and down.
After about an hour the app crashes. The only error output to the XCode console is: ` Terminated due to memory issue`
**Ionic info:** 
```
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.9.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3 Build version 8W120l 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
```
[videoOfMemorytest.zip](https://github.com/driftyco/ionic/files/1036996/videoOfMemorytest.zip)

**Comment by pacMakaveli** [comment]
I can confirm that this is an issue. I've just updated from 3.1.1 to 3.2.0 today and the app is using a disgusting amount of CPU and RAM when running.
3.2.0 is currently unusable. I haven't tried previous versions and I won't bother for now. I shall move back to 3.1.1 for the time being.

<img width="1017" alt="screen shot 2017-06-02 at 11 11 53 am" src="https://cloud.githubusercontent.com/assets/894272/26721597/517a42f6-4784-11e7-959e-b5f02defec2e.png">

```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 3.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by astec** [comment]
@gitdisrupt & @pacMakaveli may be you can take memory heap snapshot and post info here?

https://webkit.org/blog/6425/memory-debugging-with-web-inspector/
