### ISSUE TITLE
Ionic 3.3.0 iOS Problems displaying <img> drawings from the camera

### ISSUE THREAD

**Issue by aspidvip** [ionic-team/ionic#11854]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[ x ] **3.3.0**

**Related code:**

foto.html
```
<ion-content>
  <div *ngIf="base64Image.length>0">
<div *ngFor="let img of base64Image">
<img (press)="DelFoto(img)" style="width:100%; height: 100%;" [src]="img.src_full"/>
</div>
</div>
</ion-content>
```
foto.ts
```
      options = {
            quality: 50,
            destinationType: this.camera.DestinationType.DATA_URL,
            sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
            encodingType: this.camera.EncodingType.JPEG,
            mediaType: this.camera.MediaType.PICTURE,
            allowEdit: true,
            targetWidth: 1000,
            targetHeight: 1000,
            correctOrientation: true
        }
      }

 this.camera.getPicture(options).then((imageData) => {
     setTimeout(()=>{
       this.base64Image.push({
         id: null,
         procent: 0,
         src_full: 'data:image/jpeg;base64,' + imageData
       });
     },500);
}, (err) => {
});
```

**Other information:**
Ios When adding new photos from the camera, or selecting from a photo album, the ```<img>``` tag does not show photos.
On Android shows well.

If you download a picture from the Internet, the ```<img>``` tag will show it, but does not show it from the camera.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 7.0.1
Ionic Framework Version: 3.3.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8
Node Version: v6.10.3
Xcode version: Not installed

**Comment by AmitMY** [comment]
I think it will be better if you open this issue with ionic-native, as it is the camera plugin that is problematic.

I just tested in my app, in which I have something like yours, on iOS, but only with `sourceType`, `destinationType`, and `encodingType` set (exactly the same values as yours), and it does show that image.
So I recommend to also try remove all of the other properties just for a test, perhaps one of your properties is causing it on iOS.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-native#1620
