### ISSUE TITLE
Docs for ionicons allow for selectable icon.

### ISSUE THREAD

**Issue by SimonFricker** [ionic-team/ionic#11857]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Non selectable icons on https://ionicframework.com/docs/ionicons/ for designers to be able to copy and paste the icons.

**Expected behavior:**
Users can select icons from the https://ionicframework.com/docs/ionicons/ page and use them as a font.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-site#1128
