### ISSUE TITLE
tabsHideOnSubPages in the app config or as ion-tab attribute not working

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic#11869]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When tabsHideOnSubPages is set to true in the app configure or/and as ion-tab attribute and a child component pushed to the current tab nav stack the tabs header is shown/duplicated

**Expected behavior:**

Tabs are hidden on tab sub pages

**Steps to reproduce:**

Navigation is performed from the service using the navigation controller obtained from Application.getActiveNav(). The current page is one of the tabs
[See plunk](https://plnkr.co/edit/aLKQR9?p=preview)
When opened please click Go Home button under the first tab

**Related code:**

```
            let navCtrl = this.app.getActiveNav();
            navCtrl.push(ChildPage);

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 7.0.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since you are getting the active nav, which in this case is the home page, and pushing that it makes sense that the tabs that are on the home page are still going to be there when you push that page onto the stack. `tabsHideOnSubPages` makes pages that are pushed onto the stack get pushed "over" tabs on the root page, but if you have tabs on the page you are pushing, it is not going to hide those tabs.

**Comment by ryaa** [comment]
Since you are getting the active nav, which in this case is the home page
> 
In my real application getActiveNav returns Tab not the container page. getRootNav returns the container page (Home in this sample).
So if i invoke getActiveNav toget NavController and push the page with tabs into it I get the problem described. If I invoke getRootNav to get NavController and push the page with tabs into it I get the desired behaviour (no tabs duplicated).
