### ISSUE TITLE
Keyboard WKWebview Test Branch - update needed please

### ISSUE THREAD

**Issue by jrmcdona** [ionic-team/ionic#11862]
Hi All,
Can somebody on the ionic team please update this thread?

I left my feedback in here regarding the issue I saw.  Also, when is the test branch getting merged into main?

https://github.com/ionic-team/ionic/issues/11501

Thanks

**Comment by mhartington** [comment]
Hi there! Let's keep the conversation in one place. I'm going to close this for now.
