### ISSUE TITLE
Unable to Hide Modal (instead of dismiss)

### ISSUE THREAD

**Issue by shawns582** [ionic-team/ionic#11867]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a modal with content that is supposed to persist while the app is alive.  In Ionic v1 this worked fine since you could show/hide the modal. In Ionic v2 when you want to close the modal, the dismiss function destroys the modal.  

**Expected behavior:**
You should be able to show/hide the modal as well as create/destroy it.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#232

**Comment by shawns582** [comment]
Ok thanks! It's the last hurdle in my app before being able to publish it..would love to see it be handled as soon as possible.
