### ISSUE TITLE
android 6 tablet scroll issue after keyboard close

### ISSUE THREAD

**Issue by wallstudios** [ionic-team/ionic#11868]
Ionic 2.0.0
Android 6.1.2
ionic-plugin-keyboard 2.2.1 "Keyboard"

When I open a model window on an Android (API 23) Tablet and click on an input field the following happens.

"keyboard-open" is added to the body tag and "keyboard-up" is added to the ion-modal ion-content tag.

When I click off the input the "keyboard-open"  is removed BUT the "keyboard-up" remains and prevents the modal from being able to scroll.

![image](https://cloud.githubusercontent.com/assets/8520022/26612714/bfbb264e-45f5-11e7-8029-9111c0b08c9b.png)

![image](https://cloud.githubusercontent.com/assets/8520022/26612740/d7e237da-45f5-11e7-8cc9-aba7c2a5642e.png)

Expected result is the "keyboard-up" class to be removed and scrolling to be re enabled.

On a standard android device the "keyboard-up" class is not added.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. Could you provide a repo we could use to reproduce this issue?

**Comment by wallstudios** [comment]
I think I've discovered the problem or issue. I was do a new build and trying to replicate the issue for a test repo and realised I was running a nightly build of ionic (1.2.4-nightly-1917).

I've updated the platform and lib files (1.3.3) and is working as expected.
