### ISSUE TITLE
Provide a way to set a different "description" metatag for each page

### ISSUE THREAD

**Issue by SusanKern** [ionic-team/ionic#11878]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently it is only possible to set a single "description" metatag for the entire web app.  This is set in the `index.html` file.

**Expected behavior:**
It is possible to set a different "title" metatag for each page, by setting it on the "App" itself when the page is opening.  It would be helpful to be able to set the description tag in the same way. 
This feature is necessary to help with SEO for the web app.  Having the same description show up for every page is very undesirable in search engine results.

**Related code:**

```
    public ionViewDidEnter() {
        // Set document title (not shown on UI) for use by search engines
        this.app.setTitle("Nice informative title");

        // It would be nice to set the description in the same way :
        this.app.setDescription("Great description of my page filled with searchable keywords");
    }
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#233

**Comment by patrickmcd** [comment]
An alternative spot for setting this, rather than the `ionViewDidEnter` lifecycle, could be in the `@IonicPage` decorator:

```
@IonicPage({
  name: 'detail-page',
  title: 'Nice informative title',
  description: 'Great description of my page filled with searchable keywords',
  segment: 'detail/:id',
  defaultHistory: ['list']
})
```

I'd consider setting titles and descriptions more of a metadata responsibility than a code thing, so that seems like a better place.
