### ISSUE TITLE
ionic v 3.2.0  --- slides not autoplay  in tabs   when you shift   from tabs.

### ISSUE THREAD

**Issue by BoltLiu** [ionic-team/ionic#11870]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

 when the init , it works well  in a tab ,i mean autoplay well. but  as soon as i shift from tabs it not work .
**Expected behavior:**

once i set the varible of autoplay ,pager,loop . it should be autoplay ,whenever i shift from other component.
**Steps to reproduce:**

the plnkr show is below:
http://plnkr.co/edit/BqSDbOsUQn6rtdn1AfrY?p=preview
**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by BoltLiu** [comment]
http://plnkr.co/edit/BqSDbOsUQn6rtdn1AfrY?p=preview

**Comment by BoltLiu** [comment]
finally, make it work , use : ionViewWillEnter(){this.slider.startAutoplay();}
                                           ionViewWillLeave(){this.slider.stopAutoplay();}

if   in nest tabs ;    can use Events to publish event and consume it with    start and stop  autoplay();
