### ISSUE TITLE
bug: invalid component null: ionic build --prod

### ISSUE THREAD

**Issue by jayson-imfreemobile** [ionic-team/ionic#11875]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>the web app throws an error invalid component: null when build using the command: ionic build browser --prod</span>

<span is-issue-template></span>

**Comment by AmitMY** [comment]
Can you share the repo? or create a reproduction repo?

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2374
