### ISSUE TITLE
bug: Slider 'longSwipes' flag is ignored

### ISSUE THREAD

**Issue by edzillion** [ionic-team/ionic#11876]
**Ionic version:**  (check one with "x")
[x ] **3.2.0**

**I'm submitting a ...**  (check one with "x")
[x ] bug report

**Current behavior:**

I have some `Slides` and I want to disallow swiping across two slides at a time:
`@ViewChild(Slides) profileSlider: Slides;`

If I am not mistaken; setting longSwipes to false should achieve this.
`ngAfterViewInit() {
...
this.profileSlider.longSwipes = false; }`

This property exists, and is set to true initially, but when set to false I can still swipe across two slides.
  
**Expected behavior:**

When `Slider.longSwipes = false` and a user initiates a long swipe, a short swipe should be initiated instead. 

**Other information:**

Not really sure how to debug this. Setting longSwipes works, and sticks, but is ignored it seems. 

Is the ionic2 slider based on this one? http://idangero.us/swiper/api/ - it seems to have the same API

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.1.2 browser 4.1.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.2
    OS         : Windows 8.1
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by edzillion** [comment]
Oh btw, thanks for the great software! 👍 👍 👍

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by edzillion** [comment]
Well I tried but I got stuck trying to import

`import { ViewChild } from '@angular/core';`

maybe you can help?
https://plnkr.co/edit/PooBnF

**Comment by edzillion** [comment]
any ideas? I've got a demo of the issue running locally, perhaps I could put it on github?

**Comment by edzillion** [comment]
After further testing it seems it's only happening on the web version. My android build seems to have disabled longswipes.

**Comment by jgw96** [comment]
Hello @edzillion , sorry for the delay on this. When you say `web version` are you using the cordova browser platform?

**Comment by edzillion** [comment]
No worries. 

So I just went and tested with latest and `longSwipes = false` seems to be ignored on `ionic serve` and `ionic cordova run browser` but works on android.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! So the issue here seems to be that you are using the cordova browser platform. We do not recommend that you use the cordova browser platform as it is very buggy and was not really meant to be used as a production cordova platform to begin with. The fix here would be to completely remove the cordova browser platform from your app. If your wanting to build a web app with Ionic you should run `npm run ionic:build --prod` and then your `www` folder will be your built web app. Thanks!
