### ISSUE TITLE
bug: Ion-toggle relies on contain:strict Webkit problem

### ISSUE THREAD

**Issue by james-cook** [ionic-team/ionic#11883]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When rendering to wp or md the toggle has code generated which relies on contain:strict which is not available on Webkit (e.g. samsung internet browser 5.4.00-75)

Reported initially on forum https://forum.ionicframework.com/t/ion-toggle-on-samsung-internet-browser-toggle-relies-on-contain-strict/92478

To reproduce:
In Chrome for Android inspect the toggle element and find `.toggle-wp {`  or `.toggle-md {` if you then
deselect contain:strict you will SEE the effect. Webkit does not have contain:strict which is why the toggles render incorrectly  

Template and css:
```
<ion-slide>
<ion-card>
<h5>{{'WEBSHOP_SUMMARY_BEFORE_PAYMENT'| translate}}</h5>
<ion-list>
<ion-item (click)="presentTermsPopover()">
<ion-label [innerHTML]="'WEBSHOP_ACCEPT_TERMS' | translate"></ion-label>
<ion-toggle [(ngModel)]="acceptTerms"></ion-toggle>
</ion-item>
<ion-item>
<ion-label>{{'WEBSHOP_ACCEPT_NEWSLETTER' | translate}}</ion-label>
<ion-toggle [(ngModel)]="acceptNewsletter"></ion-toggle>
</ion-item>
</ion-list>


.toggle-wp {
position: relative;
width: 40px;
height: 18px;
box-sizing: content-box;
/* contain: strict; */
}</span>

<span is-issue-template></span>

**Comment by AmitMY** [comment]
Fix is pending merge: https://github.com/ionic-team/ionic/pull/11819

**Comment by Khalid-Nowaf** [comment]
I thought this bug only exist in IOS ! for now, you can try this in your app.scss.
````css

.toggle-ios {
display: block; 
}

.toggle-md {
 display: block;
}

.toggle-wp {
 display: block; 
}
````
let me know if this fix it.

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us! So there is some discussion around this at the moment but this is actually a docs issue. All inputs, including `ion-toggle` should always be wrapped in an `ion-item`. We are working on getting this into the docs as we speak. Thanks for using Ionic!

**Comment by AmitMY** [comment]
@jgw96 The fix here seem trivial, so if there are no other reasons to object, can you get this fix in? it is tiny and will save a lot of time for people (when they realise it doesn't work on device, they will fiddle for some time, google it, maybe find in the docs that you have to do it inside ion-item, and then fix their style as now it doesn't match)

**Comment by james-cook** [comment]
ion-toggle must have ion-item as the direct parent?

**Comment by james-cook** [comment]
Khalid-Nowaf  - it's works with your display:block solution

**Comment by james-cook** [comment]
I tried wrapping ion-toggle with ion-item directly - 
`            <ion-list>
              <ion-item>
                <ion-label (tap)="presentTermsPopover()" [innerHTML]="'WEBSHOP_ACCEPT_TERMS' | translate"></ion-label>
                <ion-item>
                  <ion-toggle [(ngModel)]="acceptTerms"></ion-toggle>
                </ion-item>
              </ion-item>
              <ion-item>`

this had the effect of removing the button from the dom altogether (?) - nested ion-items...
`  <ion-list>
              <ion-item>
                <ion-label (tap)="presentTermsPopover()" [innerHTML]="'WEBSHOP_ACCEPT_TERMS' | translate"></ion-label>
              </ion-item>
              <ion-item>
                <ion-toggle [(ngModel)]="acceptTerms"></ion-toggle>
              </ion-item>
              <ion-item>`

this DOES work - but the toggle is not on the same line as the label (needs styling)

**Comment by james-cook** [comment]
The display:block solution works.Wrapping in ion-item doesn't work.
-------- Original message --------From: Amit Moryossef <notifications@github.com> Date: 01/06/2017  18:09  (GMT+01:00) To: ionic-team/ionic <ionic@noreply.github.com> Cc: james-cook <james.cook@bluewin.ch>, Author <author@noreply.github.com> Subject: Re: [ionic-team/ionic] bug: Ion-toggle relies on contain:strict Webkit problem (#11883) 
@jgw96 The fix here seem trivial, so if there are no other reasons to object, can you get this fix in? it is tiny and will save a lot of time for people (when they realise it doesn't work on device, they will fiddle for some time, google it, maybe find in the docs that you have to do it inside ion-item, and then fix their style as now it doesn't match)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ionic-team/ionic","title":"ionic-team/ionic","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ionic-team/ionic"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AmitMY in #11883: @jgw96 The fix here seem trivial, so if there are no other reasons to object, can you get this fix in? it is tiny and will save a lot of time for people (when they realise it doesn't work on device, they will fiddle for some time, google it, maybe find in the docs that you have to do it inside ion-item, and then fix their style as now it doesn't match)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/ionic-team/ionic/issues/11883#issuecomment-305541879"}}}
