### ISSUE TITLE
Why I am not getting generated files in ‘www’ folder in ionic1 app after 'ionic serve'?

### ISSUE THREAD

**Issue by tousif12** [ionic-team/ionic#11889]
I am using ionic 1 to run a already build app 1 year ago . Now after ionic serve its not creating data in 'www' folder . Just gave this
'Error: ENOENT: no such file or directory, open '/home/m/DimDrop_graphs/www/index.html'' 
According to my knowledge it should create itself 'www' folder data ? as I have lost now 'www' folder.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2379
