### ISSUE TITLE
bug: ionic 2  -----  ionic cordova resources  -i   could not generate rounded icon

### ISSUE THREAD

**Issue by BoltLiu** [ionic-team/ionic#11884]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

   $   "ionic cordova resources  android -i "  command  could not generate rounded icon.but just a square icon.
**Expected behavior:**

 want generating  rounded icon for app.

**Steps to reproduce:**

**Related code:**

  $ ionic cordova resources android -i
  $ ionic cordova resources android 

```
insert any relevant code here
```
➜  mytabs git:(master) ✗ ionic info

global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2380
