### ISSUE TITLE
bug: error when creating service on sample project

### ISSUE THREAD

**Issue by martineca** [ionic-team/ionic#11898]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>To reproduce the bug simply do 'ionic start sampleApp' then choose super as option. After installation is complete try creating a service with 'ionic g provider sampleService' and you will get error: cannot read property of 'length' of undefined.</span>

<span is-issue-template></span>

**Comment by AmitMY** [comment]
What version CLI are you using? Please add the output of `ionic info`

**Comment by martineca** [comment]
global packages:

    @ionic/cli-utils : 1.2.0
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by AmitMY** [comment]
Thanks, so it seems like the issue should be moved to ionic-cli. @jgw96 can you please move it?

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2386
