### ISSUE TITLE
A small problem with  SegmentButton component

### ISSUE THREAD

**Issue by iSteveLiu** [ionic-team/ionic#11899]
**Ionic version:** 3.3

**Current behavior:**

I control the status of the SegmentButton by a variable.When the type of the variable is number,default check state cannot be set.
**Expected behavior:**

If the type of the variable is string,evething is ok.

**Comment by AmitMY** [comment]
Can you please supply an example or a code snippet?

**Comment by iSteveLiu** [comment]
`export class Message implements OnInit {`
`    //this is a number variable.I use it to control the status of SegmentButton`
`    private status:number=2`
`}`

Below is a code snippet of Segment:
`<ion-segment [(ngModel)]="status">`
`      <ion-segment-button value="0">`
`        0`
`      </ion-segment-button>`
`      <ion-segment-button value="1">`
`        1`
`      </ion-segment-button>`
`      <ion-segment-button value="2">`
`        2`
`      </ion-segment-button>`
`    </ion-segment>`

The third button  is not selected.

**Comment by AmitMY** [comment]
@iSteveLiu That is because you are binding  a string. To bind with type, use `[value]="1"` for example

**Comment by iSteveLiu** [comment]
It works! You are right. Thank you!

**Comment by jgw96** [comment]
Thanks for the help @AmitMY 😃
