### ISSUE TITLE
Ionic splashbar overlap in ios.

### ISSUE THREAD

**Issue by Bernardoow** [ionic-team/ionic#11890]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I develop Ionic for IOS and Android. When I build for IOS statusbar overlap my view.
I researched and founded topics like this [1] with team sugesting use [2]. I try but don't works.
For my solution I added this code [3] in app.scss and work good.  But for my case is some restriction I use config mode md. 
For other case for IOS continues some break at navbar need add more height to nav.. 

[1] https://forum.ionicframework.com/t/ios-navbar-overlaps-statusbar/50402/18
[2] `platforms: {
    ios: {
      statusbarPadding: true
    }
  }`

[3] `body > ion-app.platform-ios {
  margin-top:20px;
}
`
**Expected behavior:**
I expected view with margin. With margin at top like 20 statusbar not overlap my view.

**Other information:**
https://forum.ionicframework.com/t/ios-navbar-overlaps-statusbar/50402/18

My case with mode md. With margin works perfect.
IMG 1 without margin-top
![ioniclab_antes](https://cloud.githubusercontent.com/assets/4077212/26681640/3459b6fa-46b4-11e7-85db-d9c420670404.png)
IMG 2 with margin-top
![ioniclab-after](https://cloud.githubusercontent.com/assets/4077212/26681647/38ca5596-46b4-11e7-8a80-0fe28482cf7a.png)
IMG 3 with margin-top
![mycasewithmd](https://cloud.githubusercontent.com/assets/4077212/26681766/a0b801da-46b4-11e7-9b47-f0b0de738811.png)

Without mode md. works perfect too.
IMG 4  with margin-top
![ios-lab-withoulab](https://cloud.githubusercontent.com/assets/4077212/26681675/53247390-46b4-11e7-9bbb-d8d241481578.png)

without md, navbar with img is small.
IMG 5  with margin-top
![screenshot from 2017-06-01 10-09-57](https://cloud.githubusercontent.com/assets/4077212/26681698/6748a9d6-46b4-11e7-8161-1714ab8845f8.png)

**Ionic info:** 
Your system information:

Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.10.3
Xcode version: Not installed

**Comment by lukezona** [comment]
In iOS the navbar is always overlapping the view because it has a transparent background. You can discover more about it here: http://ionicframework.com/docs/native/status-bar/

Also I think it's iOS navbar style that have a max-height so it looks like the statusbar is overlapping and "cutting" your logo, I think you can avoid the use of margin setting a custom height with this variable in your scss: $navbar-ios-height.

Is that what are you looking for or I misunderstood?

**Comment by Bernardoow** [comment]
@lukezona 
Is good IOS overlap my view?

With my margin-top:20px. status-bar don't more overlapp my app.

See at first img. side bar overlap status only in IOS.

second img with my margin-top. not more and same equals android and wd.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
