### ISSUE TITLE
tabs without autoselection

### ISSUE THREAD

**Issue by Eraldo** [ionic-team/ionic#11897]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] feature request

**Current behavior:**
I can change the default selected tab, however I cannot start without any selection.
When defining tabs, I can either hide the tab button together with it's tab, nor not at all.
(I cannot hide the button only without adding custom css)

**Expected behavior:**
I want a page showing some meta information and some tabs with none of them selected at first.
(While still showing the tab bar)

**Steps to reproduce:**
I tried setting `selectedIndex="-1"` but that still selects the first tab.

**Related code:**
``` html
<ion-tabs selectedIndex="-1">
  <ion-tab root="DashboardPage" tabTitle="Dashboard" tabIcon="home"></ion-tab>
  <ion-tab root="FirstPage" tabTitle="First" tabIcon="flag"></ion-tab>
  <ion-tab root="SecondPage" tabTitle="Stats" tabIcon="star"></ion-tab>
</ion-tabs>
```

**Other information:**
As a workaround, I added a hidden tab: Another Page called `HomeMeta` which I added as the first tab and then made invisible by adding this scss rule:
``` scss
.tabbar .tab-button:first-child {
  display: none;
}
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by Eraldo** [comment]
I already did talk about this in the slack channel.
And I did not file it as an issue but rather as a feature. :)

**Comment by jgw96** [comment]
Ahh sorry about that! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#235
