### ISSUE TITLE
Module required for each tab when using lazy loading

### ISSUE THREAD

**Issue by LloydVincent** [ionic-team/ionic#11895]
**Ionic version:**  (check one with "x")
[3.0+ ] 

**I'm submitting a ...**  (check one with "x")
[ X ] bug report

**Current behavior:**
Using lazy loading in conjunction with a Tabs component requires each tab to also be lazy loaded.

**Expected behavior:**
Able to choose whether or not to use lazy loading for individual tabs.

**Steps to reproduce:**

Put a tabs component inside a lazy-loaded module, with an individual tab that is not lazy-loaded.

**Related code:**

https://github.com/LloydVincent/lazyLoadTabs/commit/f803d94159276e559bf7e401b8ea91fde4a5be7f

**Other information:**

Console error (runtime)
```
Error: Uncaught (in promise): Error: No component factory found for ContactPage. Did you add it to @NgModule.entryComponents?
Error: No component factory found for ContactPage. Did you add it to @NgModule.entryComponents?
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.2.0
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.4
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.9.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#236
