### ISSUE TITLE
[attr.col-4]="false" and [attr.col-3]="true" not working as they should (or at least how I think they should)

### ISSUE THREAD

**Issue by lukezona** [ionic-team/ionic#11891]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ X ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm trying to set dynamically col-3 or col-4 attribute of my Component based on an Input() that I receive in the template [large]="true" or [large]="false".

Both attributes are shown and sometimes it uses the last written in the css code.

**Expected behavior:**
Only one attribute should be shown based on the large attribute value.

**Steps to reproduce:**
I've made this plunker where you can see what is the problem.
https://plnkr.co/edit/QLNOFQ?p=info

```
<ion-col [attr.col-3]="!large" [attr.col-4]="large"></ion-col>
```

**Ionic info:**
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 
OS: macOS Sierra
Node Version: v6.0.0
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by JustinPierce** [comment]
@lukezona This is not an Ionic bug. Rather, it's a quirk of how Angular 2 applies HTML attribute bindings. If you change your bindings from `[attr.col-4]="large"` to `[attr.col-4]="large ? '' : null"`, then I believe you'll get the behavior you're looking for.

**Comment by lukezona** [comment]
Thanks a lot!
