### ISSUE TITLE
TABS - Disable ios 3d touch peek and pop

### ISSUE THREAD

**Issue by aggarwalankush** [ionic-team/ionic#11896]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I force(3d) press on tabs in ios, ios treats it as a link and shows preview. 

**Expected behavior:**
3d press on tabs should be ignored

**Steps to reproduce:**

**Related code:**

```
Any app with tabs should be good for testing. I tested with https://github.com/aggarwalankush/ionic2-mosum
```

<img src="https://cloud.githubusercontent.com/assets/8744282/26707337/0c63e8a6-46f9-11e7-9de3-06dc7fae7682.png" alt="first" width="250"/>

After force pressing the home tab

<img src="https://cloud.githubusercontent.com/assets/8744282/26707339/0f4ad70a-46f9-11e7-89d2-a6afc46c28ad.png" alt="second" width="250"/>

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by aggarwalankush** [comment]
@jgw96 To solve this issue, I replace anchor tag with button at https://github.com/ionic-team/ionic/blob/master/src/components/tabs/tabs.ts#L155

```
<a *ngFor="let t of _tabs" [tab]="t" class="tab-button" role="tab" href="#" (ionSelect)="select(t)"></a>
```
to 
```
<button *ngFor="let t of _tabs" [tab]="t" class="tab-button" role="tab" href="#" (ionSelect)="select(t)"></button>
```

let me know if it has any side effects.

**Comment by aggarwalankush** [comment]
If we replace `<a>` by `<button>` in tabs.ts, this issue will be fixed.

**Comment by mhartington** [comment]
Im unable to recreate this issue. 
I'm not a fan of replacing `<a>` with `<button>` as this would break routing with tabs.
Could you run `ionic info` and provide the output.

**Comment by aggarwalankush** [comment]
@mhartington I'll paste the `ionic info` later as I don't have access to my personal laptop right now. But I'm using everything latest cordova 7, node 8, ionic 3.3, ionic cli 3...

I'm surprised how are you unable to reproduce the issue 🤔  It's ios property to show peek and pop for anchor elements. I'll test with ionic-conference-app and paste the screenshots.

**Comment by liamdebeasi** [comment]
I am also experiencing this issue. I can reproduce it on an iPhone 7 running iOS 10.3.2.

Here is the output of` ionic info`. I should also note that I am using the WKWebView plugin as well. Maybe that's playing a part here?

```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.0 
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.1.2 ios 4.3.1
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.2.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
```

**Comment by aggarwalankush** [comment]
@mhartington My app is avilable on app store. https://itunes.apple.com/us/app/mosum/id1244641359
Can you try downloading it and see if you can reproduce the issue? Otherwise, here is the source code https://github.com/aggarwalankush/ionic2-mosum

**Comment by manucorporat** [comment]
I think we could fix this native side!
https://developer.apple.com/documentation/webkit/wkwebview/1415000-allowslinkpreview

what do you think? I will do some testing tomorrow

**Comment by aggarwalankush** [comment]
@manucorporat I tried disableLinkPreview using http://ionicframework.com/docs/native/3d-touch/#disableLinkPreview but it doesn't resolve this issue. It's internal implementation also uses `allowsLinkPreview` https://github.com/EddyVerbruggen/cordova-plugin-3dtouch/blob/master/src/ios/app/ThreeDeeTouch.m#L46 so it might not work. But on flip side, eddy pugin disables on UIWebView but ionic uses WKWebView so it might work also 👍

**Comment by manucorporat** [comment]
yeah, i am pretty sure it works, since that plugin does not support WK

**Comment by manucorporat** [comment]
@aggarwalankush ok, tested and pushed a change to the WK plugin:
https://github.com/ionic-team/cordova-plugin-wkwebview-engine/commit/a2049be5f9d24ac27bf9aaed260f494f11ca5b23

It fixes the issues to me, thanks for the report!! I think the PR does not make sense anymore right?
thanks anyways!

**Comment by aggarwalankush** [comment]
@manucorporat thanks for the change and I'm sure it will resolve this issue. Will test soon. But wouldn't it disable 3d touch for the entire app. What if I want anchor links in my app to have 3d touch peek and pop property? If I enable it in cordova property `cordovaBoolSettingForKey:@"AllowLinkPreview"` , tabs will again have this issue. I don't have requirement for 3d touch right now in my app, but may be someone else has and may report this issue. Wouldn't it be best to leave wkwebview default setting and make change in ionic tabs code?

**Comment by manucorporat** [comment]
@aggarwalankush yeah! I have a plan for that!

>Wouldn't it be best to leave wkwebview default setting and make change in ionic tabs code?
we don't want any <a> link to own app to show peak and pop, tabs is just a very specific case.

I think it is a better default to disable it, before I implement a better dynamic solution:
https://webkit.org/blog/7016/ios-10-link-preview-api-in-wkwebview/

```
optional func webView(_ webView: WKWebView,  shouldPreviewElement elementInfo: WKPreviewElementInfo) -> Bool
optional func webView(_ webView: WKWebView,  previewingViewControllerForElement elementInfo: WKPreviewElementInfo,  defaultActions previewActions: [WKPreviewActionItem]) -> UIViewController?
optional func webView(_ webView: WKWebView,  commitPreviewingViewController previewingViewController: UIViewController)
```

the WK plugin will be able to dynamically show the "peak and pop" thing. If the URL points to internet it is enabled, but if it points to the app, we disable it.

How does it sound?

**Comment by aggarwalankush** [comment]
Sounds perfect 👍
