### ISSUE TITLE
Ion-inputs and Ion-labels aren't visible in IE11

### ISSUE THREAD

**Issue by CORT0619** [ionic-team/ionic#11894]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

In IE11 ion-inputs and ion-labels are not visible unless the user clicks where the ion-labels and ion-inputs are supposed to be. Once the user clicks where the inputs/labels are supposed to be the ion-labels and inputs appear, but they still aren't fully visible as they appear in other browsers.

**Expected behavior:**

Ion-inputs and ion-labels would be fully visible in IE11 as they appear on all other devices, platforms.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

https://forum.ionicframework.com/t/demo-how-to-monkey-patch-for-ie11/64620

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI: 6.5.0 
    Ionic Framework Version: 3.1.1
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: 1.9.1 
    ios-sim version: 5.0.12 
    OS: macOS Sierra
    Node Version: v7.2.0
    Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by rapropos** [comment]
I'm pretty sure IE is not supported.

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! At this time we do not officially support IE11, although we do support Edge. Sorry for any hassle that causes (:
