### ISSUE TITLE
ion-select  Interfaces not work.

### ISSUE THREAD

**Issue by HsuanXyz** [ionic-team/ionic#11900]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If option's length is too long, `interfaces ` not work.

**Expected behavior:**
Show the scroll bar.

**Steps to reproduce:**
http://plnkr.co/edit/yWy2zYAxLPGN8FiIGm31?p=preview

**Related code:**

```
   <ion-select [(ngModel)]="toppings1" interface="action-sheet">
      <ion-option>Bacon</ion-option>
      ...
    </ion-select>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.0.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.9.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 

```

**Comment by danielsogl** [comment]
Hey @HsuanXyz,
can you please add your `ionic info` output

**Comment by HsuanXyz** [comment]
@danielsogl  Thank for your reminder

**Comment by AmitMY** [comment]
> Interface cannot be "action-sheet" with more than 6 options. Using the "alert" interface.

https://github.com/ionic-team/ionic/blob/master/src/components/select/select.ts#L261

I believe this is intended behavior.

**Comment by HsuanXyz** [comment]
@AmitMY Thank, I now use `popover `.
