### ISSUE TITLE
Slow loading of the page at the first transition.

### ISSUE THREAD

**Issue by Jinfaa** [ionic-team/ionic#11909]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
The project uses Crosswalk.
I previously used Framework7, but decided to make the application on ionic, I rewrote it for ionic v1 and I also had a problem with loading the pages, after which I decided to try IonicPage, and updated to v3. Problem still exists.

The transition to other pages takes a very long time, but this is only the first time.  I tried the application to IonicPage priority, but it's unsuccessful. 
This can be seen well on the android device.
Demonstration: https://drive.google.com/open?id=0BwwtdwgZwtycdWxvWnJfeHBOQW8
Without IonicPage: https://drive.google.com/open?id=0B3StdoHF0m-iRm9FRS1nRmhtaGs
I posted my project.

**Expected behavior:**
This is very critical for me, the application consists of two main pages.
Everything is loaded for a long time instantly, without delays.

**Related code:**
https://drive.google.com/open?id=0B3StdoHF0m-iRU5vbGRxSlhUeWc

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. I would recommend that you not lazy load the first page so that it gets rendered instantly. Would you mind giving that a try?

**Comment by Jinfaa** [comment]
Thanks for the answer. My scripts look like this:

app.components.ts:
```
import { Component, NgZone } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { Keyboard } from '@ionic-native/keyboard';
import { Network } from '@ionic-native/network';
import { HomePage } from '../pages/home/home';

@Component({
    templateUrl: 'app.html'
})
export class MyApp {
    rootPage = HomePage;

    constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen, keyboard: Keyboard, zone: NgZone, private network: Network, private global: Global) {
        var main = this;

        platform.ready().then(() => {
            if (platform.is("ios")) {
                keyboard.hideKeyboardAccessoryBar(true);
            }
            keyboard.disableScroll(true);
             if (window.statusbar) {
            statusBar.hide();
        }
}
```
app.module.ts:

```
import { NgModule, ErrorHandler } from '@angular/core';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { MyApp } from './app.component';

import { BrowserModule } from '@angular/platform-browser';
import { HttpModule } from '@angular/http';

import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

import {Global } from '../providers/global';

import { Camera } from '@ionic-native/camera';
import { Keyboard } from '@ionic-native/keyboard';
import { Network } from '@ionic-native/network';
import { Elastic } from '../components/elastic/elastic';

import { TabsPage } from '../pages/tabs/tabs';
import { HomePage } from '../pages/home/home';
import { ModalPage } from '../pages/form/modal';

import { InAppBrowser } from '@ionic-native/in-app-browser';

@NgModule({
    declarations: [
        MyApp,
        Elastic,
        ModalPage,
        TabsPage,
        HomePage,
    ],
    imports: [
        BrowserModule,
        HttpModule,
        IonicModule.forRoot(MyApp)
    ],
    bootstrap: [IonicApp],
    entryComponents: [
        MyApp,
        ModalPage,
        TabsPage,
        HomePage,
    ],
    providers: [
        Global,
        StatusBar,
        SplashScreen,
        Camera, Keyboard, Network, InAppBrowser,
        { provide: ErrorHandler, useClass: IonicErrorHandler }]
})
export class AppModule {}
```

home.ts:

```
import { Component } from '@angular/core';
import {Platform, IonicPage, NavParams, NavController } from 'ionic-angular';
import { InAppBrowser } from '@ionic-native/in-app-browser';
import {Global } from '../../providers/global';
import { TabsPage } from '../tabs/tabs';

@Component({
    selector: 'page-home',
    templateUrl: 'home.html'
})
    
export class HomePage {
    bannerHeight: any;

    constructor(public navCtrl: NavController, private platform: Platform, private iab: InAppBrowser, private global: Global) {
    }

    openModal() {
        this.global.openForm();
    }

    onPage(item: any) {
        this.navCtrl.push(TabsPage, { 
            type: item
        });
    }
}
```

global.ts:

```
import {Injectable} from '@angular/core';
import { Http } from '@angular/http';
import { ModalPage } from '../pages/form/modal';
import { ModalController,Modal } from 'ionic-angular';

@Injectable()
export class Global {
    private modal: Modal;
    constructor(public http: Http, public modalCtrl: ModalController) {
        this.modal = this.modalCtrl.create(ModalPage);
    }

    openForm() {
        this.modal.present();
    }
}
```

Result:
![screen shot 2017-06-06 at 12 05 58](https://cloud.githubusercontent.com/assets/3608113/26814641/49633cc8-4ab1-11e7-99cf-9f959d30224c.png)

On the analysis the first load Tab ~ 2 seconds, modal ~ 3.

**Comment by jgw96** [comment]
Hello @Jinfaa , what device are you testing on?

**Comment by Jinfaa** [comment]
Different devices: Lenovo A1000, ZenFon, Galaxy S6, Meizu. On all devices the same result. The only difference is that when I do not use CrossWalk, the sizes and positions of my items in the application are different.

**Comment by Jinfaa** [comment]
I uploaded my project on Github https://github.com/Jinfaa/ntpk . I also have a problem with opening the modal window, the first time the opening is 3 seconds, when I run again 2 seconds, the third time 1 second. 
I also have a problem with opening the modal window, the first time the opening is 3 seconds, when I run again 2 seconds, the third time 1 second. I don `t know what it 's connected with. The profiler in google chrome does not provide clarity. I just want the user to get positive emotions when they first open the application, seeing the smoothness and speed of the application.
I'm in another country (another time zone) and can not respond promptly to messages. Excuse me.
I hope you will help me, I do not really want to rewrite the applications to native.
