### ISSUE TITLE
Slider performance suggestion for touch emulation

### ISSUE THREAD

**Issue by tylkomat** [ionic-team/ionic#11904]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When the slider is initialized in the browser touch events are emulated. Especially an event listener for `mousemove` is registered on the `document` which fires events all the time while there might even be no interaction with the slider.

**Expected behavior:**
Wouldn't it not make much more sense to register the event on `mousedown` and only to the slider container and unregister it again on `mouseup`?

**Related code:**
The code in question can be found in [components/slides/swiper/swiper-events](https://github.com/ionic-team/ionic/blob/master/src/components/slides/swiper/swiper-events.ts#L70-L84)

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Are you testing this with the mobile emulation in chrome?

**Comment by tylkomat** [comment]
No just plain no emulation.
It should also be same for pointer events and ms equivalent. Unlike `touchmove` which only fires when someone moves the finger while touching, all the other events fire on `*move` without previous `*down` event.

**Comment by jgw96** [comment]
Ahh ok, now I understand what you're saying. Thanks, we will look into this!
