### ISSUE TITLE
scss inside page-xxx not affecting the outcome

### ISSUE THREAD

**Issue by zivlevy** [ionic-team/ionic#11905]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

scss rules inside the page-xxx selector has no affect.
for example:
`page-home {
  color:red;
p{
  color:red;
}
}`
will not change the color in any of the included elements in the page.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : not installed

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Unfortunately i cannot reproduce this issue, can you provide a repo we could use to reproduce this?

**Comment by AmitMY** [comment]
In your TS file, under `@Component`, what is the selector for that page?

**Comment by zivlevy** [comment]
Fixed - uninstalled ionic and reinstalled and all works fine now.
Should have done that before posting an issue ...

Thanks @AmitMY  and @jgw96  for your prompt response.
