### ISSUE TITLE
ion-select interface="popover" ignored

### ISSUE THREAD

**Issue by brugh** [ionic-team/ionic#11901]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

ion-select with interface popover shows an alert interface instead

**Expected behavior:**

show a popover without the ok and cancel buttons and without the title 

**Steps to reproduce:**
http://plnkr.co/edit/OIWA4P?p=preview

**Related code:**

```
<ion-item>
     <ion-label>Gender</ion-label>
      <ion-select interface="popover">
        <ion-option value="f">Female</ion-option>
        <ion-option value="m">Male</ion-option>
      </ion-select>
    </ion-item>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.1.3
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 2.1.0

System:

    Node       : v6.10.2
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by brugh** [comment]
sure thing: http://plnkr.co/edit/OIWA4P?p=preview

**Comment by brandyscarney** [comment]
@brugh Your plunker is using Ionic version `3.0.0`. The `popover` interface was not implemented until `3.1.0`, updating the plunker to use that version (at a minimum) works fine. Let us know if you see any issues on the latest Ionic version: `3.3.0`. Thanks!

**Comment by bollatialfredo** [comment]
Hi, I updated my Ionic version from 2.0 to 3.12.1 and can't make the interface "popover" to work. If I create a new project it works. 

<ion-select interface="popover">
          <ion-option value="10">10</ion-option>
          <ion-option value="20">20</ion-option>
          <ion-option value="50">50</ion-option>
          <ion-option value="100">100</ion-option>
</ion-select>

**Comment by brandyscarney** [comment]
@bollatialfredo Please run `ionic info` and make sure the following line has at least `3.1.0` by it:

```
Ionic Framework                 : ionic-angular 3.5.3
```

It sounds like you have updated the Ionic CLI (command line interface). If you are looking for how to upgrade the framework there are some steps in the changelog for each version: https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md

There is some documentation here on the differences between the CLI and framework: http://ionicframework.com/docs/developer-resources/using-npm/

If you are still having issues please create a post on our [forums](https://forum.ionicframework.com/) for help upgrading. Thanks! 🙂

**Comment by Tulika12** [comment]
how to remove this yellow line?
