### ISSUE TITLE
Runtime Error Cannot find module "ionic-native"

### ISSUE THREAD

**Issue by jns4u** [ionic-team/ionic#11908]
Ionic Framework: 3.0.1
Ionic App Scripts: 1.3.7
Angular Core: 4.0.0
Angular Compiler CLI: 4.0.0
Node: 6.10.3
OS Platform: Linux 4.4
Navigator Platform: Linux x86_64
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.110 Chrome/58.0.3029.110 Safari/537.36

Error: Cannot find module "ionic-native"
    at g (http://localhost:8100/build/polyfills.js:3:7133)
    at Object.<anonymous> (http://localhost:8100/build/main.js:80584:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:80290:93)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:116552:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at http://localhost:8100/build/main.js:140:18
    at http://localhost:8100/build/main.js:143:10

**Expected behavior:**
app should execute without any error on 127.0.01 at port 8100

I am in process of creating  an ionic app with some features. All the template files have been added as required. I had successfully created a basic ionic app now  following that and extending basic part when i upgraded ionic environment start facing this error. Also i have already tried available solutions to this problem like deleting node module folder and reviewing dependencies in package file and running install again. after successful installation reviewed available ionic-native folder, etc

Review following listed dependencies -

{
  "name": "ionic-feature-app",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.0.1",
    "ionicons": "3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.0",
    "@ionic/cli-plugin-ionic-angular": "1.3.0",
    "typescript": "~2.2.1"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [],
  "description": "Featured App: An Ionic project"
}

please review
thanks

**Comment by AmitMY** [comment]
Please fix your issue to fit the issue template.
From what I can understand from this mess, you are importing from  "ionic-native" (probably in app.module.ts) but you don't have that module. Either `npm install --save ionic-native` or remove the import

**Comment by rapropos** [comment]
I vote for "remove the import". It's obsolete.

**Comment by jns4u** [comment]
@rapropos it's not obsolete that is required by app. In fact the very basic app requires splash-screen and status-bar module.
@AmitMY i already tried you solution but this did not worked last time but i found ionic-native requires ionic/app-scripts latest version instead 1.3.0 as development dependency.

any way guy's thanks a lot you made my day great.

**Comment by rapropos** [comment]
> it's not obsolete

[Yes it is](https://github.com/ionic-team/ionic-native/blob/master/README.md). The monolithic "ionic-native" import has been superseded by a bunch of "@ionic-native/plugin" ones.
