### ISSUE TITLE
back navigation button not showing up

### ISSUE THREAD

**Issue by devanshsadhotra** [ionic-team/ionic#11903]
**Ionic version:*3.3.0*  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I cloned the code using "ionic start myProjectName tutorial", and changed the project according to ionic 3 , now , there is a file list.html , it has a button at header which opens side menu. i wanted to have a back button over there ,and removed the code for side menu opening. Expected that back button would automatically show up , but it did not happen, instead it shows header without any button with just title written

**Expected behavior:**
There must be back navigation button

**Related code:**

```
--> list.html
<ion-header>
  <ion-navbar>
    <ion-title>My First List</ion-title>
  </ion-navbar>
</ion-header>
<ion-content>
  <ion-list>
    <button ion-item *ngFor="let item of items" (click)="itemTapped($event, item)">
      <ion-icon name="{{item.icon}}" item-left></ion-icon>
      {{item.title}}
      <div class="item-note" item-right>
        {{item.note}}
      </div>
    </button>
  </ion-list>
</ion-content>

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.9.1
    OS         : Windows 10

```

![image](https://cloud.githubusercontent.com/assets/15092405/26728867/4a1027ac-47c9-11e7-9a0e-e38973902785.png)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
