### ISSUE TITLE
feat: Change ion-fab css position to fixed

### ISSUE THREAD

**Issue by Rhonun** [ionic-team/ionic#11902]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Currently the ion-fab buttons to not scroll with the container because they are position: absolute. If we change this to position: fixed it will stick to the bottom of the screen during scrolling.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#234

**Comment by Rhonun** [comment]
@jgw96 

The subsequent ticket should be closed. The FAB appears to be working correctly. Making the position fixed works fine on android but blows up on iOS. For scroll content the FAB needs to be placed outside of the ion-content tag
