### ISSUE TITLE
ion-segment not working with ion-navbar's "Back" on iOS

### ISSUE THREAD

**Issue by sunnypp** [ionic-team/ionic#11918]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The ion-segment stays at the top and suddenly disappears while the page (on which "Back" is clicked) slides away as expected.

**Expected behavior:**
The ion-segment should slide away with the page when Back is clicked.

**Steps to reproduce:**
(I am sorry I can only see a white screen on the Plunker using my Safari.. So I committed code to a repo to illustrate the issue:)
https://github.com/sunnypp/ion-segment-problem

Without pulling the code:
1. ionic start tutorial
2. In hello-ionic.ts, add / change these:
```
// import
import { NavController, NavParams } from 'ionic-angular';
import {ListPage} from '../list/list';
// change constructor
constructor(public nav: NavController, public navParams: NavParams) {
// add method
  pushPage() {
    this.nav.push(ListPage);
  }
```
3. In hello-ionic.html, change the button as follows:
`    <button ion-button color="primary" (click)="pushPage()">Push List Page</button>`
4. Delete the ion-title, then add a ion-segment to List page:
```
    <ion-segment>
      <ion-segment-button value="a">
        A
      </ion-segment-button>
      <ion-segment-button value="b">
        B
      </ion-segment-button>
    </ion-segment>
```
5. ionic serve --lab.  Note that the bug only happens on iOS (also on Ionic View).

**Related code:**
https://github.com/sunnypp/ion-segment-problem

**Other information:**
I found this as I was working on another project which I used lazy-loading.
In that project the Back button **even loses its function**.
Was expecting to reproduce that using the starter template, but feeling hard to create pages.module, index, etc... So let's see if that will be fixed when this is fixed :)

In the case when "Back" button loses its function, swiping from left to right still can go back to the last page as expected - however the "floating ion-segment" issue still persists.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.0
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 5.1.1 ios 4.1.1
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.9.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : not installed
    ios-sim    : not installed
```

Thanks in advance.

**Comment by danielsogl** [comment]
@sunnypp Can you update your app to Ionic 3.3 and test it again please?

**Comment by AmitMY** [comment]
Also, use `<ion-toolbar>` instead of `<ion-navbar>`, like the [docs](https://ionicframework.com/docs/api/components/segment/Segment/) suggest

**Comment by sunnypp** [comment]
@danielsogl 
Ran `npm update ionic-angular --save` info both my repositories. (The tutorial one and my working project)

In the tutorial one, `ionic-angular` is now on 3.3.0
Issue persists. (Image below is the "middle" transition state after clicking Back, we can see the segment buttons staying in the middle)
![screen shot 2017-06-05 at 2 29 11 am](https://cloud.githubusercontent.com/assets/15846960/26764298/ef49a63e-4996-11e7-845f-c1c0fa8d37b4.png)

By the way, in my working project, both `npm update @ionic/app-scripts --save` and `npm update ionic-angular` doesn't update my modules... 😨 (The tutorial's `@ionic/app-scripts` is on 1.3.7 while the working project is on 1.3.0...)

Sorry if this starts to look like a misconfiguration on my side... At the very least I think for the tutorial project it should be a bug.

@AmitMY 
Thanks for the advice.  Maybe I should implement my own "Back" Button and abandon the use of `<ion-navbar>`... Hope it won't be too hard to implement to swipe back :)

**Comment by AmitMY** [comment]
@sunnypp Ionic is complete. Meaning, you can do whatever you can do in iOS (and if you can't, the team would want to know).

I hope the toolbar fixed your transition.

If it didn't, let me know and I will check your project out.

I am not sure why you want to implement the back button, isn't there a "Back" when you push the page?

**Comment by AmitMY** [comment]
Checking the code [here](https://github.com/ionic-team/ionic/blob/master/src/transitions/transition-ios.ts#L141), it seems like you might need to wrap the `ion-segment` with `ion-title`

**Comment by sunnypp** [comment]
Thanks @AmitMY !! That worked like a charm for my tutorial project!

Now I am closing this issue and try debugging my work project... Because the back button cannot be clicked on that one (though the swiping back now doesn't have a UI glitch).  And seems I will have to first find out why `npm update` didn't work for me for that project....

Will reopen this once I've found a way to replicate the issue with the tutorial project - I hope that day will not come ;)

**Comment by sunnypp** [comment]
I have copied the whole `src/` folder and replaced my work project's src with the working one from tutorial.  And then the same code didn't work in my work project.  So this should be a misconfiguration problem due to whatever in my settings (like karma, protractor, or even npm since I cannot update my `@ionic/app-scripts`)...  So I guess I would put my `src/` code from my working project into the tutorial and hope it works well there.
