### ISSUE TITLE
bug(ion-datetime): User should not need to click to populate date values

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#11919]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
1) When changing the date to a day in the future, the hours and seconds columns do not update until a user clicks interacts with them. This is terribly confusing for a user. 

See the gif below

![slow date](https://cloud.githubusercontent.com/assets/2852839/26765070/9b56790c-4974-11e7-8d3c-85f36935d15b.gif)

**Expected behavior:**
As soon as the day or month changes, all values in the date picker should be updated immediately without having to wait for a users input. Or at the very least should be debounced. 

**Other information:**
See repo here: 
[datetimeset.zip](https://github.com/ionic-team/ionic/files/1050696/datetimeset.zip)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.0
    ios-sim    : 5.0.10
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#238
