### ISSUE TITLE
Creating a new project fails if quoted human-readable name contains spaces

### ISSUE THREAD

**Issue by gammelby** [ionic-team/ionic#11922]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I create a new project:

```
ionic start foo blank -n "Foo Bar" --skip-link
```

When changing to dir `foo` and executing `ionic serve`, the following error is seen:

```
$ ionic serve
Error: Cannot find module '@ionic/app-scripts'
```

Indeed, this module is missing from the `node_modules` dir:

```
$ ls -lart node_modules/\@ionic/
total 0
drwxr-xr-x    6 ug  staff   204 Jun  5 00:10 cli-plugin-ionic-angular
drwxr-xr-x    6 ug  staff   204 Jun  5 00:10 cli-utils
drwxr-xr-x    4 ug  staff   136 Jun  5 00:10 .
drwxr-xr-x  116 ug  staff  3944 Jun  5 00:10 ..
```

Executing `npm install` in the project dir fails:

```
$ npm install
npm WARN Invalid name: "Foo Bar"
npm WARN @ionic/cli-plugin-ionic-angular@1.3.0 requires a peer of @ionic/app-scripts@^1.3.7 but none was installed.
npm WARN foo No description
npm WARN foo No repository field.
npm WARN foo No README data
npm WARN foo No license field.
```

**Expected behavior:**

Project is created with necessary dependencies and is able to run `ionic serve` without errors. It works as expected if replacing space in quoted name with dash or underscore.

**Steps to reproduce:**

See above.

**Related code:**

N/A

**Other information:**

N/A

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

In failing project dir:

```
$ ionic info
[ERROR] Error with ./node_modules/ionic-angular/package.json file: FILE_NOT_FOUND
[ERROR] Error with ./node_modules/@ionic/app-scripts/package.json file: FILE_NOT_FOUND

global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : not installed
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Ionic Framework                 : not installed

System:

    Node       : v7.9.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
```

Outside project dir:

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

System:

    Node       : v7.9.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
```

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2394
