### ISSUE TITLE
Tap is ignored when done within 1.5 sec after entering view

### ISSUE THREAD

**Issue by servehermans** [ionic-team/ionic#11925]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When navigating back upon entering view I tap on an item which is ignored when done within the first 1-1.5 seconds. Tapping the item again after 1.5 seconds works. This happens only when I have navigated backwards.

**Expected behavior:**
The tap should be executed and not ignored.

**Steps to reproduce:**
Ionic view id: 914fb8a5
Github: https://shermans@bitbucket.org/shermans/taptest.git

I have used the blank template using just the homepage.

Tap the first item in the list. Navigate back. Tap the item again within 1 second. Nothing happens.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13

**Comment by jgw96** [comment]
Hello @tripleneo , what device are you seeing this issue on?

**Comment by tripleneo** [comment]
Hi Justin, the device I am using is an iPhone 5s. 

Servé!

**Comment by tripleneo** [comment]
Additional info: it only happens when you tap the back link. It does not happen when I just swipe back to the previous view.

**Comment by tripleneo** [comment]
@jgw96 any update on this issue?

**Comment by jgw96** [comment]
Hey @servehermans sorry for the delay on this. Is this still an issue with the latest release (3.4.2)?

**Comment by servehermans** [comment]
Hi @jgw96 . No problem. This time I am the one slow to response. I have upgraded to the 3.4.2 version and the issue still persists. You can download the example app from github or through Ionic view. It happens on my iPhone 5s device after tapping the back link. It works fine in the browser. It also works nice when using swipe to move back.

**Comment by servehermans** [comment]
Found a workaround: in the provided example I am using the (click) event on each item. When I started using the (tap) event, the issue is gone and I am able to tap the item as soon as the page transition is done. With the click event, the issue is still there.

**Comment by Sampath-Lokuge** [comment]
@servehermans Is that clicked element is `button` or else like `div` or `list item` etc. ?

**Comment by servehermans** [comment]
It's an ion-item. 

Servé!

**Comment by Sampath-Lokuge** [comment]
@servehermans It is a documented issue.Please see here [**Click Delays**](http://ionicframework.com/docs/troubleshooting/#click-delays)

**Comment by servehermans** [comment]
Not entirely. The document describes a delay of 300ms whereas my issue is about at least 1.5 seconds delay. It could even be 3 seconds before the tap is being handled. Please run the demo project that I have provided which is using the blank template and a list. Tap on one item, go back, and tap again. You will notice that any tap within 3 seconds after going back will be ignored which is much longer than 300ms. This can be solved by using tap instead of click as the event but still I think this is an issue as the delay is much longer than the one documented. 

Servé!

**Comment by Sampath-Lokuge** [comment]
Delay may differ but the solution is there no? @servehermans

**Comment by kensodemann** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue on the latest version of Ionic.

Thanks for using Ionic!
