### ISSUE TITLE
Error thrown when generating new page in Ionic 3

### ISSUE THREAD

**Issue by jordanpurinton** [ionic-team/ionic#11927]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently, when running `ionic generate page [page name], the automatically generated .module.ts file imports `IonicModule`, which throws the error `Property 'forChild' does not exist on type 'typeof IonicModule`.

**Expected behavior:**
The module that should be imported is `IonicPageModule`, which does not throw an error.

**Steps to reproduce:**
Run `ionic generate page [page name] and navigate to the module file that is generated. 

-->

**Related code:**

```
import { NgModule } from '@angular/core';
import { IonicModule } from 'ionic-angular';
import { DailyNotesPage } from './daily-notes';

@NgModule({
  declarations: [
    DailyNotesPage,
  ],
  imports: [
    IonicModule.forChild(DailyNotesPage), // error thrown here, should be IonicPageModule
  ],
  exports: [
    DailyNotesPage
  ]
})
export class DailyNotesPageModule {}
```

```
global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.10.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by danielsogl** [comment]
@jordanpurinton update your app-scripts to 1.3.7.
This problem is fixed a long time ago :)

**Comment by jordanpurinton** [comment]
@danielsogl Oh dang, really? I must not have the latest version of Ionic, then or something.

**Comment by jgw96** [comment]
Closing this issue as I can confirm this has been fixed.
