### ISSUE TITLE
@include ltr(){} produce an error

### ISSUE THREAD

**Issue by AsimNet** [ionic-team/ionic#11923]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

in my component.scss i'm trying to support ltr and rtl directions, so I did this:
```
myComponent {
@include ltr(){
.someClass {
text-align: right;
}
}

@include rtl(){
.someClass {
text-align: left;
}
}

}
```
 then it shows me this error:
>no mixin named ltr

**Other information:**

```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.2 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
