### ISSUE TITLE
ion-select ion-item: classes, validation and styling

### ISSUE THREAD

**Issue by silverbackdan** [ionic-team/ionic#11926]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using ion-select the parent ion-item class is not updated like it is when using ion-input such as validation classes. Also the 'floating' label does not appear to work with ion-select. Trying to get a consistent UI for text and select inputs.

**Expected behavior:**
I'd expect as the select begins with no value select it should not have 'input-has-value' on the ion-item tag until a value is selected, then the ng-valid classes etc. should be applied to the ion-item tag as it is when using a text input for example. This is to allow for consistent styling.

This is the HTML where I'd expect all the 2 inputs to look the same, have a floating label and the valid classes should be applied to the ion-item when the input becomes valid.
```
<form [formGroup]="questionsForm">
        <ion-list>
            <ion-item>
                <ion-label floating>Label 1</ion-label>
                <ion-input type="number" formControlName="number" pattern="[0-9]{1,2}(\.[0-9]{1})?" min="0" max="99" required></ion-input>
            </ion-item>
            <ion-item>
                <ion-label floating>Label 2</ion-label>
                <ion-select formControlName="select_hours" okText="Okay" cancelText="Cancel" required>
                    <ion-option>&lt; 1 hour</ion-option>
                    <ion-option>1-3 hours</ion-option>
                    <ion-option>3-6 hours</ion-option>
                    <ion-option>6-12 hours</ion-option>
                    <ion-option>12+ hours</ion-option>
                </ion-select>
            </ion-item>
        </ion-list>
</form>
```

**Comment by jgw96** [comment]
Hello! As this issue classifies more as a feature request than a bug I am going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#239
