### ISSUE TITLE
bug: Query isn't returning error on ortographic mistake

### ISSUE THREAD

**Issue by cdiazr** [ionic-team/ionic#11934]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I selected version 2 of Ionic because this form doesn't give me the option to select version 3.

Following code is working with no errors but is ignoring complete query.

```
uploadImages() {
      return new Promise((resolve, reject) => {
          this.db.list(`/${this.POSTS}`, {
              query: {
                limitToLas: 4,
                orderByKey: true,
                endAt: this.lastKey
              }
          }).subscribe( posts => {
              if( this.lastKey) {
                posts.pop(); 
              }
            
              if( posts.length == 0) {
                 console.log('Ya no hay más registros');
                 resolve(false);
                 return;
              }

              this.lastKey = posts[0].$key;

              for( let i = posts.length -1; i >= 0; i-- ) {
                let post = posts[i];
                this.imagenes.push( post );
              }

              resolve(true);
          });
      });
  }
```

If you notice, line 5 has an ortographic error "limitToLas:", is missing "t", rest of the code is working but, query is ignored.

Query is working perfectly when I add "t" in "limitToLast".</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by cdiazr** [comment]
thanks mate, It's done!
