### ISSUE TITLE
IonRangeSlider giving error ionRangeSlider() is not a function

### ISSUE THREAD

**Issue by apurvgandhwani** [ionic-team/ionic#11939]
I am trying to use ionRangeslider in my react application. I put the code to initialize the ionRangeSlider in my componentDidMount method. But i am getting an error

`Uncaught TypeError: (0 , _jquery2.default)(...).ionRangeSlider is not a function`
This is my react code

```
import $ from 'jquery'
class AddTagSection extends Component {

    componentDidMount() {

        $('#example_id').ionRangeSlider()
    }

    componentWillUnmount(){

    }
    render(){
        return (
            <div className='add-tag-section'>
                <div className='add-tag-section-footer'>
                    <input type="text" id="example_id" name="example_name" value="" />
                </div>
            </div>

        )
    }
}
```
I have jquery at two places in my application. One is included in html file and one is included in package.json, installed via npm. Is that conflicting? I tried removing one of them but then too ionRangeSlider didn't work?

In my package.json i have jquery version 2.2.3 and in html i have script link for version 2.0.1.

How can I make ionRangeSlider work?

**Comment by jgw96** [comment]
Hello, @apurvgandhwani! Thanks for using Ionic. At this time because our components are built with angular they are not going to work in a react application. We are working on some things internally though that through the magic of web components will allow you to use ionic components not only in react apps, but in pretty much every major framework (: Keep an eye on our [blog](https://blog.ionic.io/) for more info.

**Comment by apurvgandhwani** [comment]
@jgw96 But it worked in other react project. Here is how i used it

```
 <script src="dev/js/ionSlider/jquery-1.12.3.min.js"></script>

    <script src="http://vjs.zencdn.net/ie8/1.1.0/videojs-ie8.min.js"></script>

    <!-- ad markers plugin, depends from jquery -->


    <script src="dev/js/components/VideoPlayer/markers.js"></script>
    <link href="dev/scss/marker.css" rel="stylesheet">

    <script src="dev/js/components/VideoPlayer/rangeslider.js"></script>
    <link href="dev/scss/rangeslider.css" rel="stylesheet">

    <script src="dev/js/ionSlider/ion.rangeSlider.js"></script>
    <link href="dev/js/ionSlider/normalize.css" rel="stylesheet">
    <link href="dev/js/ionSlider/ion.rangeSlider.css" rel="stylesheet">
    <link href="dev/js/ionSlider/ion.rangeSlider.skinFlat.css" rel="stylesheet">
```

and my component 
```

export default class AppBarComponent extends Component {

    componentDidMount(){
            // Apply the plugin to the element
        var slider = document.getElementById('ionSlider-newTag');


        $(function () {

            $("#range").ionRangeSlider({
                hide_min_max: true,
                keyboard: true,
                min: 0,
                max: 5000,
                from: 1000,
                to: 4000,
                type: 'double',
                step: 1,
                prefix: "$",
                grid: true
            });

        });
    }

Here i have index.html file and not index.jade.

```

**Comment by manikandan07081995** [comment]
@jgw96 i got error while implemented this link **_https://www.npmjs.com/package/@types/virtual-keyboard_** for virtual keyboard. TypeError: __WEBPACK_IMPORTED_MODULE_3_jquery__(...).keyboard is not a function
TypeError: __WEBPACK_IMPORTED_MODULE_3_jquery__(...).keyboard is not a function How can i implement in ionic project.
