### ISSUE TITLE
Not able to create new ionic project

### ISSUE THREAD

**Issue by parveshhc** [ionic-team/ionic#11930]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

ionic start release blank
✔ Creating directory ./release - done!
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
✔ Downloading - done!
[INFO] Fetching starter template blank (https://github.com/ionic-team/ionic2-starter-blank/archive/master.tar.gz)
✔ Downloading - done!
✔ Updating package.json with app details - done!
✔ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
✖ Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):
        
        npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
        npm ERR! Cannot read property 'find' of undefined
        npm ERR! Cannot read property 'find' of undefined
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!     /Users/parvgarg/.npm/_logs/2017-06-05T17_09_03_157Z-debug.log

**Expected behavior:**

Should create new project and install all npm dependencies.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by parveshhc** [comment]
global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : not installed

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2396

**Comment by nelsonyrg** [comment]
in my case i had a similar issue, after several tries and upgrading everything [<packaege>] =  nodejs, npm, cordova and  ionic, one by one  with command 
sudo npm install [<package>]@latest -g
 then i ve changed permissions in my projects container directory 
(cause gave permission errors in ionic deployment)
and last, when call command instead 
iionic start ionicTemplate blank
use 
iionic start ionicTemplate
and select in the menu options one type of project

that worked for me
