### ISSUE TITLE
Ionic Update 3.3.0 (2017-05-24) didn't work on android jellybean or kitkat

### ISSUE THREAD

**Issue by fidoafif** [ionic-team/ionic#11935]
**Ionic version:**  (3.3.0)

**I'm submitting a ...**  (bug report)

**Current behavior:**
The apps just didn't work on android jellybean or kitkat and work fine on marshmallow

**Steps to reproduce:**
Create a new ionic project

    ionic start myApp tabs

Add Android platform

    ionic cordova platform add android

Run app on android device

    ionic cordova run android

**Other information:**
When I tested on android marshmallow work fine but when I tested on Android Kitkat and Android Jellybean its just showing me the blank screen or white screen.

**Ionic info:** :
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by danielsogl** [comment]
Ionic supports Android SDK >=16.
If you want to use lower SDKs Versions you have to use Crosswalk.

**Comment by fidoafif** [comment]
I tested on device that have Android Jellybean 4.2.1 Api 17 and Kitkat 4.4 Api 19.

**Comment by lweb20** [comment]
Right, I think we need to know device requirements.

**Comment by jgw96** [comment]
Hello everyone! I have tested this on both a nexus 4 running android 4.4.4 and a nexus 5 android emulator running 4.4.4 and on both devices it works fine. Our official android support is 4.4.4 and up with stock webview (although for best performance we recommend crosswalk for 4.4.4 devices) and on 4.4.2 and back we require crosswalk. 5.0 and up does not need crosswalk as those devices will always have the latest chrome webview. So, for jellybean you will need to install crosswalk. Thanks for using Ionic everyone!

**Comment by fidoafif** [comment]
Hi @jgw96 I am build an android app using ionic framework and before I update Ionic to "Ionic Update 3.3.0 (2017-05-24)" my ionic app its working fine on jellybean and up without install crosswalk, but after I update even when I am creating a starter project and running on android device (Jellybean) its just showing me a white screen back then its working fine, 

I cannot use a crosswalk because make my app size really big.

**Comment by aepsetiawan** [comment]
Hi Everyone. I'm using Crosswalk with Cordova 4.0. 
https://crosswalk-project.org/documentation/cordova.html
