### ISSUE TITLE
transparent property?

### ISSUE THREAD

**Issue by shawnlan** [ionic-team/ionic#11948]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Just found out that I can add `transparent` property to Navbar and Toolbar: https://forum.ionicframework.com/t/ionic-2-transparent-header/53017

However it's not in the documentation. Is it still supported?

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-site#1144
