### ISSUE TITLE
docs: documentation (getting started) out of date

### ISSUE THREAD

**Issue by JordanFarrow** [ionic-team/ionic#11941]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>3.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Several commands have been "renamed":
$ ionic platform add ios
The platform command has been renamed. To find out more, run:

$ ionic cordova platform ios
? The plugin @ionic/cli-plugin-cordova is not installed. Would you like to insta
ll it and continue? Yes

$ ionic build ios
The build command has been renamed. To find out more, run:

$ ionic cordova build ios
...
Error: ios-deploy was not found. Please download, build and install version 1.9.0 or greater from https://github.com/phonegap/ios-deploy into your path, or do 'npm install -g ios-deploy'

Seems a bit problematic for a "getting started" tutorial to not be up-to-date (and also not mentioning several dependencies).</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-site#1143
