### ISSUE TITLE
Range: dragstart and dragend events

### ISSUE THREAD

**Issue by shawnlan** [ionic-team/ionic#11949]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

It would be really helpful to add these events to `ion-range`. Right now there seems no way to detect when users start/stop dragging the knobs.

**Comment by AmitMY** [comment]
The events are `ionFocus` and `ionBlur`, added in https://github.com/ionic-team/ionic/pull/10761
`ionFocus` => `dragstart`
`ionBlur` => `dragend`

**Comment by jgw96** [comment]
Thanks for helping @AmitMY 😃

**Comment by shawnlan** [comment]
Cool! This needs to be in the docs.
