### ISSUE TITLE
Failed to start - node-sass

### ISSUE THREAD

**Issue by matheusrufca** [ionic-team/ionic#11947]
I'm getting this error on start command `ionic` start app tabs`:

**npm -v            5.0.3
node -v           v8.0.0
ionic -v           3.3.0
node-sass       4.5.3
libsass             3.5.0.beta.2**

> 
> [ERROR] An error occurred while running npm install (exit code 1):
> 
> npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
> npm WARN prefer global node-gyp@3.6.2 should be installed with -g
> 
> > node-sass@4.5.0 install D:\web\app\node_modules\node-sass
> > node scripts/install.js
> 
> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node":
> 
> HTTP error 404 Not Found
> 
> Hint: If github.com is not accessible in your location
> 	 try setting a proxy via HTTP_PROXY, e.g.
> 
> 	 export HTTP_PROXY=http://example.com:1234
> 
> or configure npm proxy via
> 
> 	 npm config set proxy http://example.com:8080
> 
> > fsevents@1.1.1 install D:\web\app\node_modules\fsevents
> > node install
> 
> 
> > node-sass@4.5.0 postinstall D:\web\app\node_modules\node-sass
> > node scripts/build.js
> 
> Building: E:\Program Files\nodejs\node.exe D:\web\app\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsas_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
> gyp info it worked if it ends with ok
> gyp verb cli [ 'E:\\Program Files\\nodejs\\node.exe',
> gyp verb cli   'D:\\web\\app\\node_modules\\node-gyp\\bin\\node-gyp.js',
> gyp verb cli   'rebuild',
> gyp verb cli   '--verbose',
> gyp verb cli   '--libsass_ext=',
> gyp verb cli   '--libsass_cflags=',
> gyp verb cli   '--libsass_ldflags=',
> gyp verb cli   '--libsass_library=' ]
> gyp info using node-gyp@3.6.2
> gyp info using node@8.0.0 | win32 | x64
> gyp verb command rebuild []
> gyp verb command clean []
> gyp verb clean removing "build" directory
> gyp verb command configure []
> gyp verb check python checking for Python executable "python2" in the PATH
> gyp verb `which` failed Error: not found: python2
> gyp verb `which` failed     at getNotFoundError (D:\web\app\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (D:\web\app\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (D:\web\app\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at D:\web\app\node_modules\which\which.js:89:16
> gyp verb `which` failed     at D:\web\app\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at D:\web\app\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
> gyp verb `which` failed  python2 { Error: not found: python2
> gyp verb `which` failed     at getNotFoundError (D:\web\app\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (D:\web\app\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (D:\web\app\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at D:\web\app\node_modules\which\which.js:89:16
> gyp verb `which` failed     at D:\web\app\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at D:\web\app\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
> gyp verb check python checking for Python executable "python" in the PATH
> gyp verb `which` failed Error: not found: python
> gyp verb `which` failed     at getNotFoundError (D:\web\app\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (D:\web\app\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (D:\web\app\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at D:\web\app\node_modules\which\which.js:89:16
> gyp verb `which` failed     at D:\web\app\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at D:\web\app\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
> gyp verb `which` failed  python { Error: not found: python
> gyp verb `which` failed     at getNotFoundError (D:\web\app\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (D:\web\app\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (D:\web\app\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at D:\web\app\node_modules\which\which.js:89:16
> gyp verb `which` failed     at D:\web\app\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at D:\web\app\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
> gyp verb could not find "python". checking python launcher
> gyp verb could not find "python". guessing location
> gyp verb ensuring that file exists: C:\Python27\python.exe
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> gyp ERR! stack     at PythonFinder.failNoPython (D:\web\app\node_modules\node-gyp\lib\configure.js:483:19)
> gyp ERR! stack     at PythonFinder.<anonymous> (D:\web\app\node_modules\node-gyp\lib\configure.js:508:16)
> gyp ERR! stack     at D:\web\app\node_modules\graceful-fs\polyfills.js:284:29
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
> gyp ERR! System Windows_NT 10.0.15063
> gyp ERR! command "E:\\Program Files\\nodejs\\node.exe" "D:\\web\\app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuld" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> gyp ERR! cwd D:\web\app\node_modules\node-sass
> gyp ERR! node -v v8.0.0
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> Build failed with error code: 1
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-sass@4.5.0 postinstall: `node scripts/build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the node-sass@4.5.0 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\XXX\AppData\Roaming\npm-cache\_logs\2017-06-07T01_10_22_416Z-debug.log
[debug-log.txt](https://github.com/ionic-team/ionic/files/1056690/debug-log.txt)

**Comment by anandraj9497** [comment]
I am also facing the same issue

**Comment by danielsogl** [comment]
Downgrade back to Node 6.10.3 and npm >=5. Ionic is not npm5 ready

**Comment by anandraj9497** [comment]
Let me try that and will update you

**Comment by danielsogl** [comment]
Trust me, that is the problem ;) I already fixed the outdated dependencies in the ionic-app-scripts repo. Wait for the next release and you will be able to use NPM 5 and ionic

**Comment by anandraj9497** [comment]
Now I have 
node : 6.10.3
npm : 5.0.2
 @ionic/cli-utils : 1.3.0
 Ionic CLI        : 3.3.0
Is there any issues with the above version ?

**Comment by danielsogl** [comment]
You still run NPM >= 5! Downgrade to npm 4 or 4 by running `npm install -g npm@4.6.1`.
Then remove your `node_modules` folder and run npm install again.

**Comment by fidoafif** [comment]
@danielsogl have u test your app on android 4.2 API 17? I tested and its give me a blank screen but on android 5.0 its work fine, do you know why? please tell me,

**Comment by danielsogl** [comment]
@fidoafif please open a new issue. This has nothing to do with this issue thread.

**Comment by jgw96** [comment]
Hello all! Closing this issue as it seems to have been fixed. Thanks, @danielsogl!

**Comment by kwstoikonomou** [comment]
it has been 4 months. Is ionic npm >= 5 ready yet?

**Comment by kensodemann** [comment]
@kwstoikonomou - can you post exactly the command you are using and what you are seeing? Also, some information about your environment might prove helpful.

I tried the `ionic start app tabs` that the OP tried an it worked just fine. Here is my environment:

```
C:\Users\ken\Projects\Issues\app>ionic info

cli packages: (C:\Users\ken\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.14.0
    ionic (Ionic CLI) : 3.14.0

local packages:

    @ionic/app-scripts : 3.0.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v8.7.0
    npm  : 5.4.2
    OS   : Windows 10

Misc:

    backend : pro
```

**Comment by MadAztec** [comment]
Hi guys,

I get a very similar error:
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node"

My Ionic info is:
    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0
local packages:
    @ionic/app-scripts : 1.1.4
    Ionic Framework    : ionic-angular 2.2.0
System:
    Node : v9.2.0
    npm  : 5.5.1 
    OS   : Windows 8
Misc:
    backend : pro

I installed node-sass globally but it got version 4.7.2, but "ionic start..." is trying to use 4.5.3.
Looking into node-sass repository version 4.5.3 does NOT support win32-x64-59 while version 4.7.2 does support that environment (or at least it is listed there).

Do you any suggestions of what should i do to solve the problem?

Regards,
Arturo

**Comment by jawad-aziz-farhad** [comment]
Thanks @danielsogl. you saved my Day. 👍

**Comment by keitaassane1** [comment]
Thanks @danielsogl. you saved my Day. +1

**Comment by luiz-claudio** [comment]
solucion of the problem: 
return  the node for version 7.10.1
sudo npm cache clean -f
sudo npm install -g n
sudo n 7.10.1
