### ISSUE TITLE
Full screen video playing behind tab bar

### ISSUE THREAD

**Issue by mrhirsch** [ionic-team/ionic#11942]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When using any type of video player in full screen mode (HTML5 video, Vimeo player, etc.), the video controls are not accessible and hidden behind the tab bar. So when you try to tap a video control, the tab bar is tapped instead.

Video controls are available if the video is in a modal window. 

**Expected behavior:**

The video controls should be available when a video is played in full screen mode in a tab bar application.

**Comment by jgw96** [comment]
Thanks for opening an issue with us! We will look into this.

**Comment by leonardocaldas** [comment]
+1
