### ISSUE TITLE
ngIf formGroup message not displayed inside ion-item

### ISSUE THREAD

**Issue by JanMesaric** [ionic-team/ionic#11959]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Does not display a message in example below if in same ion-item block.

**Expected behavior:**
Should display message

**Related code:**
```
<ion-item>
          <ion-label floating>Username</ion-label>
          <ion-input formControlName="username" type="text"></ion-input>
          <div *ngIf="!loginForm.controls.username.valid && (loginForm.controls.username.dirty || submitAttempt)">
            This message is not displayed but it should be (?)
          </div>
        </ion-item>
        
        <ion-item>
          <div *ngIf="!loginForm.controls.username.valid && (loginForm.controls.username.dirty || submitAttempt)">
            This message is displayed
          </div>
     
        </ion-item>

```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
