### ISSUE TITLE
Bug: Select option showing multiple selected

### ISSUE THREAD

**Issue by karlpatrickespiritu** [ionic-team/ionic#11952]
When switching multiple times (3 times) on the options given, this somehow gives me that there are two options were selected, which obviously is wrong. Or maybe I'm just missing something here?

![1](https://user-images.githubusercontent.com/10472504/26865823-feab9bf4-4b90-11e7-9b9c-580514990953.png)

![1](https://user-images.githubusercontent.com/10472504/26866069-2a173fe0-4b92-11e7-9849-7eb029ae1e0c.png)

template snippet
```html
        <ion-item *ngIf="eventPhotographers.data.length && !fetchingPhotographers">
          <ion-label padding-top>Photographer</ion-label>
          <ion-select
              [(ngModel)]="photographer.id"
              (ionChange)="onSelectPhotographerChange($event)"
              multiple="false"
              formControlName="user_id">
            <ion-option [value]="eventPhotographer ? eventPhotographer.id: null" *ngFor="let eventPhotographer of eventPhotographers.data">
              {{eventPhotographer.staff.name}}
            </ion-option>
          </ion-select>
        </ion-item>
```

function snippet
```typescript
  onSelectPhotographerChange(eventPhotographerId) {
    const selectedPhotographer = this.eventPhotographers.data.find((eventPhotographer) => eventPhotographer.id === eventPhotographerId)
    if (selectedPhotographer) this.teamSignOffForm.patchValue({ user_id: selectedPhotographer.id })
    console.log(this.teamSignOffForm.value)
  }
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 2.6
Node Version: v6.10.3
Xcode version: Not installed
```

**Comment by rapropos** [comment]
I don't understand why you are setting things in two different ways. Wouldn't it be considerably simpler to simply have `[value]="eventPhotographer"` on each `<ion-option>` and forgo the change handler entirely?

**Comment by khaled9544** [comment]
Hello,, did you found a solution for that,  I'm facing the same issue.
