### ISSUE TITLE
ionic serve -l chrome blank screen issue

### ISSUE THREAD

**Issue by ydornala** [ionic-team/ionic#11958]
@alakra @alexbbt Below is the ionic info
![image](https://user-images.githubusercontent.com/23229885/26878325-bdb55abc-4baa-11e7-971d-0f6323997297.png)

I'm getting blank screen in chrome and working in safari browser.

![image](https://user-images.githubusercontent.com/23229885/26878405-f2148c42-4baa-11e7-8bc3-2ea979f52f20.png)

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2400
