### ISSUE TITLE
ClearInput Property of <ion-input>  Bug in IOS  ionic 3.

### ISSUE THREAD

**Issue by HarshitPKing** [ionic-team/ionic#11956]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If clearInput property is set to true then it works fine in android but in IOS by clicking on clear button nothing happens.  
**Expected behavior:**
If clearInput property is set to true then it works fine in android this also should be happen clear text on textfield by clicking on clear button as android.
**Steps to reproduce:**

**Related code:**
  ```
<ion-item>
   <ion-input float placeholder="Enter Name" **clearInput=true**  id="txtfield1"  class="textinput" type="text" name="input" [(ngModel)]="enteredtext" blur focus> 
   </ion-input>
     </ion-item>
```
```
global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

System:

   Node       : v7.10.0
    OS         : OS X El Capitan
    Xcode      : Xcode 8.0 Build version 8A218a 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.8 

```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We will look into this.

**Comment by HarshitPKing** [comment]
any updates on this issue?
