### ISSUE TITLE
Multiple file uploading

### ISSUE THREAD

**Issue by nikhildhar1992** [ionic-team/ionic#11955]
Hi guys already uploaded my code on ionic forums regarding this one but got nothing there hope here will get some response.. I just want to  upload multiple files in angular 2 and sent to node js server so here below is my code ..

```
    this.camera.getPicture(options).then((imagePath) => {
         
        this.tempPath = "data:image/jpeg;base64," + imagePath;
        this.selectedImagePath = imagePath;
        this.signaturePad.fromDataURL(this.tempPath);

this.storage.set('savedSignature', this.signature);
      // this.signaturePad.fromDataURL(this.image);
      this.storage.get('savedSignature').then((data) => {         
          this.formData.append('uploadArray['+this.i+']', data);                            
       })
   }
```
Posting..
```
let headers: any = new Headers({ 'Content-Type': undefined  });
    headers.append('Accept', 'application/json');
    let options: any = new RequestOptions({ headers: headers }),
this.http.post(url,this.formData,options).map(res => res.json())
      .subscribe((data) => {})
```
on server side not able to get the files
just want to know the way I am sending and appending is correct or not

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by nikhildhar1992** [comment]
Hey bro thanks for replying ..

**Comment by nikhildhar1992** [comment]
But I really need help in this ...plz
