### ISSUE TITLE
[datetime] month days not updating after onth change

### ISSUE THREAD

**Issue by knulan** [ionic-team/ionic#11950]
**Ionic version:**  (check one with "x")
 - [ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
 - [ ] **2.x**
 - [x] **3.x**

**I'm submitting a ...**  (check one with "x")
 - [x] bug report
 - [ ] feature request
 - [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
1. open datepicker
2. select february 28th
3. save by pressing Done button
4. open datepicker
5. change month to march
6. showing only 28 days:

![2017-06-07_0813](https://user-images.githubusercontent.com/5101556/26863608-5b1db21c-4b5c-11e7-9f27-98226fedbfcf.png)

**Expected behavior:**
update number of days after month change

**Steps to reproduce:**
can reproduce in detetime component exemple on ionic documentation page https://ionicframework.com/docs/components/#datetime

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by RuneStenstroem** [comment]
I am having the same issue, so I will follow this.

**Comment by madhuramtrivedi** [comment]
There is a similar behavior, I noticed in ion-datetime control. 
1. I selected a date: Dec 31, 2017
2. Changed the month to Nov.
3. Able to select the date a Nov 31, 2017. 

On selecting month or year, number of days in the datepicker should update. 
Like, after selecting Nov, User shouldn't see 31. 

Thanks

**Comment by anooprehman** [comment]
Saw a similar issue in #12319 which has a  [Fix commit](https://github.com/eisene/ionic/commit/4aa494da1b3b082646c0a98ec1f69c823c126eb5).

**Comment by huxiamei** [comment]
Has this problem been solved?

**Comment by huxiamei** [comment]
> Thanks for opening an issue with us, we will look into this.

Has this problem been solved?
