### ISSUE TITLE
[BUG] $menu-ios-background and $menu-md-background not working

### ISSUE THREAD

**Issue by ramoncarreras** [ionic-team/ionic#11957]
**Ionic version:** 
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

After starting new ionic app using sidemenu template like this:
`ionic start test sidemenu`
And add the following line to the _variables.scss file:
`
$menu-ios-background: #ff0000;
$menu-md-background: #ff0000;
`
The background color of the side menu does not change

**Expected behavior:**
The background color should change to red.

**Ionic info:**

```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.1.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.0
    ios-sim    : 5.0.11
```

**Comment by ramoncarreras** [comment]
It seems the problem is that ion-content overwrites the background-color style:

https://drive.google.com/a/cesw.cat/file/d/0Bx3gxIsr_qiEVEtNSGZCcXd6dlU/view?usp=sharing

https://drive.google.com/a/cesw.cat/file/d/0Bx3gxIsr_qiEOVVXQkZDeVdNZ2M/view?usp=sharing

**Comment by ramoncarreras** [comment]
I've updated my last comment with correct images (screenshots).
Sorry for that.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! We will look into that.

In the meantime, you can work around this by adding some CSS similar to this in your `app.scss` file:

```css
.menu-inner {
  .content {
    background: none;
  }

  .item {
    background: none;
  }
}
```

Thank you for using Ionic
