### ISSUE TITLE
Errors when unzipping platforms/browser/build/package.zip

### ISSUE THREAD

**Issue by hadrien-toma** [ionic-team/ionic#11963]
**Ionic version:**  (check one with "x")
- [ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
- [ ] **2.x**
- [x] **3.3.0**

**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I get some errors when unzipping `platforms/browser/build/package.zip`.

**Expected behavior:**
Achieve to unzip all files successfully (these errors finally lead to unreadable files when web served).

**Steps to reproduce:**
```sh
ionic start my-app blank
cd my-app
ionic cordova build browser --prod
cd platforms/browser/build
unzip package.zip
```

**Related code:**

**Other information:**
Errors I have from `unzip`:
```sh
Archive:  package.zip
   creating: assets/
   creating: assets/fonts/
  inflating: assets/fonts/ionicons.eot  
  error:  invalid compressed data to inflate
  inflating: assets/fonts/ionicons.scss  
  inflating: assets/fonts/ionicons.svg  
  inflating: assets/fonts/ionicons.ttf  
  inflating: assets/fonts/ionicons.woff  
  inflating: assets/fonts/ionicons.woff2  
  inflating: assets/fonts/noto-sans-bold.ttf  
  error:  invalid compressed data to inflate
  inflating: assets/fonts/noto-sans-bold.woff  
  inflating: assets/fonts/noto-sans-regular.ttf  
  error:  invalid compressed data to inflate
  inflating: assets/fonts/noto-sans-regular.woff  
  inflating: assets/fonts/noto-sans.scss  
  inflating: assets/fonts/roboto-bold.ttf  
  inflating: assets/fonts/roboto-bold.woff  
  inflating: assets/fonts/roboto-bold.woff2  
  inflating: assets/fonts/roboto-light.ttf  
  error:  invalid compressed data to inflate
  inflating: assets/fonts/roboto-light.woff  
  inflating: assets/fonts/roboto-light.woff2  
  inflating: assets/fonts/roboto-medium.ttf  
  error:  invalid compressed data to inflate
  inflating: assets/fonts/roboto-medium.woff  
  inflating: assets/fonts/roboto-medium.woff2  
  inflating: assets/fonts/roboto-regular.ttf  
  error:  invalid compressed data to inflate
  inflating: assets/fonts/roboto-regular.woff  
  inflating: assets/fonts/roboto-regular.woff2  
  inflating: assets/fonts/roboto.scss  
   creating: assets/icon/
  inflating: assets/icon/favicon.ico  
   creating: build/
  inflating: build/main.css          
  inflating: build/main.js           
  inflating: build/polyfills.js      
  inflating: build/sw-toolbox.js     
  inflating: config.xml              
  inflating: confighelper.js         
   creating: cordova-js-src/
  inflating: cordova-js-src/confighelper.js  
  inflating: cordova-js-src/exec.js  
  inflating: cordova-js-src/platform.js  
  inflating: cordova.js              
  inflating: cordova_plugins.js      
  inflating: exec.js                 
  inflating: index.html              
  inflating: manifest.json           
  inflating: platform.js             
   creating: plugins/
   creating: plugins/cordova-plugin-device/
   creating: plugins/cordova-plugin-device/src/
   creating: plugins/cordova-plugin-device/src/browser/
  inflating: plugins/cordova-plugin-device/src/browser/DeviceProxy.js  
   creating: plugins/cordova-plugin-device/www/
  inflating: plugins/cordova-plugin-device/www/device.js  
   creating: plugins/cordova-plugin-splashscreen/
   creating: plugins/cordova-plugin-splashscreen/src/
   creating: plugins/cordova-plugin-splashscreen/src/browser/
  inflating: plugins/cordova-plugin-splashscreen/src/browser/SplashScreenProxy.js  
   creating: plugins/cordova-plugin-splashscreen/www/
  inflating: plugins/cordova-plugin-splashscreen/www/splashscreen.js  
   creating: plugins/cordova-plugin-statusbar/
   creating: plugins/cordova-plugin-statusbar/src/
   creating: plugins/cordova-plugin-statusbar/src/browser/
  inflating: plugins/cordova-plugin-statusbar/src/browser/StatusBarProxy.js  
   creating: plugins/cordova-plugin-statusbar/www/
  inflating: plugins/cordova-plugin-statusbar/www/statusbar.js  
   creating: plugins/ionic-plugin-keyboard/
   creating: plugins/ionic-plugin-keyboard/www/
   creating: plugins/ionic-plugin-keyboard/www/browser/
  inflating: plugins/ionic-plugin-keyboard/www/browser/keyboard.js  
  inflating: service-worker.js       
 ✘ 
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : browser 4.1.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by mhartington** [comment]
Hi there! Cordova-browser is not a fully completed target. It's very much an experiment and is not recommended. If you need to deploy a web-app with Ionic, we strongly suggest you do:

```bash

npm run ionic:build --prod
```

Then deploy the contents of `www `

**Comment by piotrowski** [comment]
Can you provide the `package.zip` so someone can look at it?
What is the result if you run `npm run ionic:build --prod` first and then `cordova build browser` directly?

**Comment by hadrien-toma** [comment]
Alright @mhartington, I didn't know that it was not a fully completed target, thank you for mentioning it.
@piotrowski, when running `npm run ionic:build --prod` first and then `cordova build browser`, there is no generated `package.zip`. [Here](https://github.com/hadrien-toma/ionic-app-conference-cordova-build-browser-errors) is the previous `package.zip` that was generated.

**Comment by piotrowski** [comment]
> when running npm run ionic:build --prod first and then cordova build browser, there is no generated package.zip.

Huh. So `cordova build browser` doesn't work run by itself?

**Comment by hadrien-toma** [comment]
How can I confirm that? Here is the content of the generated `platforms/browser` folder:
```sh
> ls
browser.json  config.xml  cordova  css  img  index.html  js  manifest.webapp  platform_www  res  www
```
This seems to be served correctly so I don't dare saying that it doesn't work. However, there is no `build` folder, neither `package.zip` in it.

**Comment by hadrien-toma** [comment]
@mhartington, is this implied that I can't use Cordova plugins designed for browser because of not having any `cordova.js` loaded?

**Comment by piotrowski** [comment]
> How can I confirm that?

Delete what is in the folder and run the command again.

I was expecting that `cordova` to generate the zip file - but this doesn't seem to be the case. Interesting.

**Comment by hadrien-toma** [comment]
> Delete what is in the folder and run the command again.

This is what I originally done ;).

**Comment by piotrowski** [comment]
Hm, just tested this locally: `cordova build browser` adds `\platforms\browser\build\package.zip` for me. (Cordova 7.0.1, cordova-browser 4.1.0)

**Comment by mhartington** [comment]
>@mhartington, is this implied that I can't use Cordova plugins designed for the browser because of not having any cordova.js loaded?

For now, yes, you cannot use any cordova plugins in the browser. 

For the most part, the browser platform was made to make testing easier. It is not fully functional and does not provide all the features as cordova-ios or cordova-android. 

For plugins that or functionality that you need on desktop or in a non-cordova env, you can either mock the plugin wrapper with ionic-native, or do some platform detection as described in the Plugins section:

http://ionicframework.com/docs/developer-resources/desktop-support/


Again, and I cannot stress this enough... 😄 

Please, do not use the cordova-browser platform. 

Thanks! 😄

**Comment by hadrien-toma** [comment]
@piotrowski, I totally re-tried on a fresh `ionic start` project and now the `build` folder is here again. When unzipping it, however errors are still there...

**Comment by hadrien-toma** [comment]
@mhartington, thank you for all the information. Maybe you know a good starting point for learning how to develop a new ionic-native module?

**Comment by hadrien-toma** [comment]
Found it [here](https://github.com/ionic-team/ionic-native/blob/master/DEVELOPER.md), let's get started!
