### ISSUE TITLE
Slides crash on iOS

### ISSUE THREAD

**Issue by clementcontet** [ionic-team/ionic#11960]
**Ionic version:**
[X] **3.3.0**

**I'm submitting a ...**
[X] bug report

**Current behavior:**
On iOS devices (tested on iPhone4s-iOS9, iPhone6+-iOS10 and iPhone7s-iOS10), the Slides component crashes when more than ~10 slides are loaded, with effect "flip".

The crash messages are: 
> Message from debugger: Terminated due to memory issue
> ... was killed by jetsam.

**Expected behavior:**
No crash.

**Steps to reproduce:**
Get test project from: https://github.com/clementcontet/IonicSlides-Crash
Run it on an iPhone
Try to slide

**Related code:**
See: https://github.com/clementcontet/IonicSlides-Crash/blob/master/src/components/section/section.component.html

**Other information:**
The crash doesn't happen if the effet is "slide".
The crash doesn't happen if I load only 5 slides.
The crash doesn't happen on XCode simulator, only on real device.
The crash doesn't happen on Android.

**Ionic info:**
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.3.0
Xcode version: Xcode 8.3.3 Build version 8E3004b

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We will look into this.

**Comment by clementcontet** [comment]
Sorry, but the tag should be `v3`, shouldn't it?

**Comment by HarshitPKing** [comment]
I have same issue.
