### ISSUE TITLE
ionic-datetime does not support clearing the value set

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic#11961]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

ionic-datetime does not support clearing the value once it is set

**Expected behavior:**

Allow clearing the datetime value set

**Steps to reproduce:**

Here is the ionic-datetime demo - see https://ionicframework.com/docs/api/components/datetime/DateTime/
It is not possible to clear/reset the value

**Related code:**
N/A

**Other information:**
N/A

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#248

**Comment by jasonz1987** [comment]
@jgw96 this url is broken , i also think it's very necessary to add a reset button for datetime picker.

**Comment by kensodemann** [comment]
Our feature requests repo is a private repo for several reasons, so the link is not actually broken. Thank you again for this feature request.

**Comment by jasonz1987** [comment]
@kensodemann okay,i get it!

how about this feature now?  will it be added in next version?

**Comment by kensodemann** [comment]
The focus of our next few releases will be:

4.x - getting Ionic v4 ready for release, this introduces Stencil components with the main focus being increased performance, especially pertaining to start times

3.x - high priority bug fixes

I cannot say when (or if) any particular feature request will be implemented. However, now that we are getting much closer to v4 going into Alpha milestones are beginning to be created. These will give you an idea of what we are currently working on for a release.

**Comment by smilee89** [comment]
Despite the lack of an "clear button" you can assign an empty string to a bound ngModel of the DatePicker. This way you can clear the date. (tested in Ionic 4.4.3)
