### ISSUE TITLE
<ion-item> swipe/scroll is not working in  <ion-list> only on windows/windows surface tablet

### ISSUE THREAD

**Issue by Raghu700** [ionic-team/ionic#11974]
**Ionic version:**  (check one with "x")
2.2.3

**Current behavior:**
Mouse scroll is working.But touch scroll/swipe is not working for windows surface.

**Expected behavior:**
Touch scroll should work for windows surface.

**Steps to reproduce:**
We are trying to touch swipe/scroll the "ion-item" in ion-list.
Its working fine on Android and on IOS but not working on windows/windows Surface.

**Related code:**
<ion-item class="item item-avatar-left item-checkbox item-text-wrap item-content list-item-animate downloadedCoursesList"
                      ng-repeat="course in CoursesVm.downloadedCourses">
              <ion-option-button id="btnDeleteCourse" class="button-assertive" ng-click="CoursesVm.deleteCourseFromSwipeDelete(course)" aria-label="{{'t_delete'| translate}}" role="button" tabindex="0">
                <span class="button-icon fa fa-trash"></span>
              </ion-option-button>
              <img ng-src="{{::course.contentImagePath}}" class="downloadedCoursesImage" image-load-error-src="assets/img/default_rep.png"
                   ng-style="{ 'margin-left': CoursesVm.showcheckboxes ? '40px' : '0px' }" aria-label="{{'t_activity_image' | translate}}" tabindex="0">
              <label ng-if="CoursesVm.showcheckboxes" class="checkbox leftCorner">
                <input id="btnItemCheckBox{{::course.id}}" type="checkbox" ng-model="course.selected" tabindex="0" />
              </label>
              <div class="downloadCourseLayout" ng-style="{'padding-left': CoursesVm.showcheckboxes ? '107px' : '67px' }">
                <activity-action-btn activity="course" showaction="!CoursesVm.showcheckboxes" tabindex="0"> </activity-action-btn>
                <p ng-if="!CoursesVm.showcheckboxes" class="courseDesc downloadCourseDesc ellipsis-secondline" tabindex="0">{{::course.description.trim() }}</p>
                <p ng-if="CoursesVm.showcheckboxes" class="courseDescDisabled downloadCourseDesc ellipsis-secondline" tabindex="0">{{::course.description.trim() }}</p>
                <div class="downloadCourseStatus">
                  <p class="floatLeft downloadedCourseStatusText" tabindex="0">{{CoursesVm.getDisplayStatusForCourse(course)}}</p>
                </div>
              </div>
            </ion-item>

insert any relevant code here
```

**Other information:**
Ionic  2.2.3
Used cordova for  hybrid mobile  with angularjs

**Comment by jgw96** [comment]
Hello @Raghu700 . Would you be able to post a repo we could use to reproduce this issue?
