### ISSUE TITLE
@Output() event doesnt work within context of Tab and Tabs

### ISSUE THREAD

**Issue by neo-split** [ionic-team/ionic#11977]
**Ionic version:**  (check one with "x")
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report

**Current behavior:**
I want to communicate between Tab (container) and Tabs (individual pages) by using @Output() binding provided by Angular (with EventEmitter). From Tabs page, I am able to fire an event using EventEmitter. And I want this event to be caught by the Tab (container). However, this fired event is not caught by the Tab (container) page.

**Expected behavior:**
The Tab page should catch the event so I can act upon it.

**Steps to reproduce:**
See plunker below. 
http://plnkr.co/edit/AcV9dH?p=preview

Please check the console for simple logging of "event fired" and "event caught" statements.

**Other information:**
I could use Ionic's Events but I am experiencing bugs with that too! That is why I resorted to Angular's event emitter but that doesnt seem to work either! Will create a new issue for that :(

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by neo-split** [comment]
Please note, it is v3 issue, not v2.  Do you mind correcting the label?

**Comment by prantikv** [comment]
Still getting this on Ionic v 3.9.2

**Comment by AUK4GIT** [comment]
I am facing the same issue in ionic v 3.13.1.
Neither @Output nor @ViewChild works. I guess the TabPage and Pages are not directly related as seen in the DOM. The NavigationController comes in the middle. Anyhow, to communicate with childs/Pages from Parent/Tabs, I am currently using the below code:

code1:
let recordPage: RecordPage = this.tabRef.getByIndex(0).root.prototype;
recordPage.loadTimeSheet();// a method on 'tab1Root' component

code2:
 let tab :Tab = this.tabRef.getSelected();
 tab.goToRoot({}); //this method reloads 'tab1Root' component i.e ionViewDidLoad method is triggered again.

**Comment by prantikv** [comment]
@jgw96 any update on this issue?
