### ISSUE TITLE
img#changePic can't change src when I select a new image.

### ISSUE THREAD

**Issue by baorr** [ionic-team/ionic#11971]
Ionic version: 3.2.0

I'm submitting a bug report

**Current behavior:**
addprofile.html

&lt;p&gt;
      &lt;ion-item no-lines&gt;
        &lt;ion-avatar item-left&gt;
          &lt;img id="changePic" src="http://ionicframework.com/dist/preview-app/www/assets/img/marty-avatar.png"&gt;
        &lt;/ion-avatar&gt;
        &lt;button ion-button item-right (click)="onPickUpImage()"&gt;
          &lt;ion-icon name="add"&gt;&lt;/ion-icon&gt;
          选择头像
        &lt;/button&gt;
      &lt;/ion-item&gt;
    &lt;/p&gt;

addprofile.ts
import { Component } from '@angular/core';
import { ImagePicker } from '@ionic-native/image-picker';

@Component({
  templateUrl: 'addprofile.html'
})
export class AddProfile{
  constructor(public imagePicker : ImagePicker) {
  }

  onPickUpImage(){
    var changePic = document.getElementById('changePic');
    this.imagePicker.getPictures({
    	maximumImagesCount: 1,
    	width: 2048,
    	height: 2048,
    	quality: 30
    }).then((results) => {
      for (var i = 0; i < results.length; i++) {
          changePic.src =  results[i];
      }
    }, (err) => { });
  }
}

**Expected behavior:**
img#changePic can change src when I select a new image.

**Steps to reproduce:**
1. click "选择头像" button, select a picture, then it cause an error, "changePic has no attribute 'src'".

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
