### ISSUE TITLE
bug: ionic android platform support limitations

### ISSUE THREAD

**Issue by 2016lalu** [ionic-team/ionic#11978]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>webview</span>

<span ionic-description>ui and performance issues in android 4.2 or below, so please help me</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! For reasons that I explain [here](https://github.com/ionic-team/ionic/issues/11445#issuecomment-298348758), we require using crosswalk for Android below 4.4.4. Hope this helps you (:
