### ISSUE TITLE
ion-slides  effect="fade" not working (with transparent PNG)

### ISSUE THREAD

**Issue by gino8080** [ionic-team/ionic#11975]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
cant' make the ion-slide fade effect working, images in the slides are always visibile

**Expected behavior:**
the previous slide should fadeOut with opacity 0

**Steps to reproduce:**
http://plnkr.co/edit/iAjerCaBLSHFrMIIWcD5?p=preview

**Ionic info:** 

```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.7.4
    OS         : macOS Sierra
    Xcode      : Xcode 8.1 Build version 8B62
    ios-deploy : 1.9.0
    ios-sim    : 5.0.12
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. We will look into this.

**Comment by mhartington** [comment]
This seems to be the default behavior of the swiper library.

https://codepen.io/mhartington/pen/XgmGjO?editors=1100

**Comment by gino8080** [comment]
mhmm you right 
anyway I think it can be considered a swiper bug what do yo u think?

**Comment by mhartington** [comment]
Actually, I am wrong. It looks like it's possible, but just need to modify a setting.

http://plnkr.co/edit/z0ugNlVIZnKgGLg4hQMX?p=preview

All the swiper API is available here, so for reference
http://idangero.us/swiper/api/
