### ISSUE TITLE
Ionic 3 is crashing just after opening splash on IOS (iphone & simulator)

### ISSUE THREAD

**Issue by abumuwaz** [ionic-team/ionic#11987]
I am getting the app crashing issue with Ionic 3.3.0 for IOS 10.32 iphone as well as simulator. Even it does not show home page, just crashing after opening splashing but android app using same code base is working very fine as i want. 

**What is going to IOS**

Not only that , i do not get any debug file named console.log at 

**my_mac_project_path/platforms/ios/cordova/console.log**
There is only  log as 
```
CORDOVA_PATH=$( cd "$( dirname "$0" )" && pwd -P)

tail -f "$CORDOVA_PATH/console.log"
```

Additional:
I have tried only the blank app to confirm with **fcm**  ionic-native plugin only but same result.

so now not only app is crashed but also my head with the pain after trying severals try.

i am really looking forward reply from the ionic team ASAP.

Thanks in advance after all.

**Comment by plul** [comment]
Try this: https://github.com/arnesson/cordova-plugin-firebase/issues/275#issuecomment-301818002

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-native#1674

**Comment by plul** [comment]
@abumuwaz did you figure this out? I am having the same problem. I tried removing the fcm plugin too, it still crashes immediately after splash.
