### ISSUE TITLE
Feature Request: multiple attribute for ion-segment

### ISSUE THREAD

**Issue by lukejoliat** [ionic-team/ionic#11985]
For the ion-select element, there is the option to add an attribute: `multiple="true"`

This attribute allows users, "to select multiple options. When multiple options can be selected, the alert overlay presents users with a checkbox styled list of options. The ion-select multiple="true" component's value receives an array of all the selected option values."

Is it possible to add this attribute for ion segments so that we can select several segments. I have a several segment buttons in my application and it would be fantastic if I could allow users to select several values:
![beacon](https://user-images.githubusercontent.com/23531241/26959738-abb3d99c-4c9f-11e7-87cc-ed8a460a89c5.png)

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#250

**Comment by Yonn-Trimoreau** [comment]
Any news on this feature ? The link is broken

**Comment by dwieeb** [comment]
We don't use the "ionic-feature-requests" repo anymore, so I reopened this issue.

**Comment by mhartington** [comment]
Hi there! After reviewing this, I don't this is something that we'll want to add. Segments are meant to be a context switch, meaning that as a segment is selected, there should be a change in content. Looking at how iOS and Material design implements this, you cannot select multiple segments. 

A good alternative would be use to ion-select instead, which would allow for multiple selections to be made. 

Thanks!
