### ISSUE TITLE
ionic2: in ion-tabs page,canGoBack() always return false.

### ISSUE THREAD

**Issue by longdw** [ionic-team/ionic#11984]
well, I listen back button at android like this,
```
registerBackButtonAction() {
      this.platform.registerBackButtonAction(() => {

        if (this.keyboard.isOpen()) {
          this.keyboard.close();
          return;
        }

        const overlay = this.app._appRoot._overlayPortal.getActive();
        const nav = this.app.getActiveNav();

        if(overlay && overlay.dismiss) {
          overlay.dismiss();
        } else if(nav.canGoBack()){
          nav.pop();
        } else {
          this.showExit();
        }
      });
  }
```
There has a child page called `MyPage.ts`, `MyPage.ts` has a `ion-tabs` component, when I was on the MyPage, `canGoBack()` always returned false, this will cause I can not normally return to the previous page.I don't know how to do.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by abitul** [comment]
same issues for me, canGoBack always return **false**, please help

**Comment by davincif** [comment]
Similar problem here.
In my case, I need to know if _canGoBack()_ every time the user comes to a certain page, so a placed this code inside _ionViewWillEnter_ and it also returns me a wrong state. It even says that a can go back when a can't, causing the application to crash.

**Comment by cpamp** [comment]
I ran into this issue when pushing a view to the stack from an overlay. When you do that `canGoBack()` always returns false when you can still go back without error.

@jgw96 Does this sound like a bug?
