### ISSUE TITLE
 Cordova encountered an error.  You may get more insight by running the Cordova command above directly.

### ISSUE THREAD

**Issue by iamkhan001** [ionic-team/ionic#11989]
getting error while adding android platform

D:\Imran\ionic\notifications>ionic cordova platform add android
> cordova platform add android --save
? Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova platform add android --save (exi
t code 1):

        Using cordova-fetch for cordova-android@~6.2.2
        Error: Failed to fetch platform cordova-android@~6.2.2
        Probably this is either a connection problem, or platform spec is incorr
ect.
        Check your connection and platform name/version/URL.
        Error: cmd: Command failed with exit code ENOENT

**Comment by piotrowski** [comment]
As the error message says:

> Probably this is either a connection problem
> ...
> Check your connection

Are you behind a corporate proxy?

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2412
