### ISSUE TITLE
AOT Fails with Angular2 external module : Error encountered resolving symbol values statically. 

### ISSUE THREAD

**Issue by hireton** [ionic-team/ionic#11993]
**Ionic version:**  
[ ] **1.x**
[ ] **2.x**
[x] **3.10.2**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
Building with --prod option fails if project uses an **external module with Angular2 dependencies** (@ angular/core)
I tried moving deps to dependencies or devDependencies with no change.
Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. 

Build succeeds without --prod option or if the external module has no Angular2 dependencies.

**Expected behavior:**
Build with --prod option should succeed.

**Steps to reproduce:**
# 1. Create new project

``` 
ionic start testproject blank
```
# 2. Create external plugin
```
mkdir testplugin
cd testplugin
```
add package.json TestClass.ts    

# 4. Install plugin
Install and link (or copy plugin to node_modules)

``` 
npm install
npm link
cd ../testproject
npm link @myexternals/testplugin
```

# 5. Register plugin in app.module.ts

# 6. Build in prod mode
```
ionic cordova build android  --prod
```

**Related code:**
3 files updated from ionic bootstrap :

testplugin/**package.json**
```
{
  "name": "@myexternals/testplugin",
  "scripts": {
    "tsc": "tsc",
    "tsc:w": "tsc -w"
  },
  "dependencies": {
  },
  "repository": {},
  "license": "",
  "peerDependencies": {
    "@angular/core": ">=2.0.0"
  },
  "devDependencies": {
    "@angular/core": "4.1.2",
    "rxjs": "5.1.1",
    "typescript": "^2.0.10",
    "@types/node": "^6.0.46"
  },
  "version": "0.1.1"
}
```

testplugin/**TestClass.ts**
```
import {Component} from "@angular/core"
@Component({
    selector:"testclass",
    template:"<div></div>"
})
export class  TestClass{
    constructor(){
    }
}
```

testproject/src/app/**app.module.ts**
```
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';
import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';

import {TestClass} from "@myexternals/testplugin/TestClass"

@NgModule({
  declarations: [
    MyApp,
    HomePage,
    TestClass
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    TestClass
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}
```

Files in this plunker : http://plnkr.co/edit/GcygCJ6GKuwdFpipZuEA?p=preview

**Other information:**
Build error : 
```
Error: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in D:/test/testproject/node_modules/@myplugins/testplugin/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in D:/test/testproject/node_modules/@myplugins/testplugin/node_modules/@angular/core/core.d.ts, resolving symbolɵ f in D:/test/testproject/node_modules/@myplugins/testplugin/node_modules/@angular/core/core.d.ts
```
**Ionic info:**
Node       : v6.10.3
OS         : Windows 10
Xcode      : not installed
ios-deploy : not installed
ios-sim    : not installed

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1031
