### ISSUE TITLE
Incorrect name in config.xml

### ISSUE THREAD

**Issue by shaneparsons** [ionic-team/ionic#11996]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behaviour:**
Creating a new project (i.e. `ionic start [app-name]`) will not update the name in the config.xml. It will remain as MyApp unless you intentionally remember to change it.

For a production app it will obviously be noticed at some point, but for a quick test app, it's often forgotten.

**Expected behaviour:**
For the config.xml to have the name you give the new app by default.

**Steps to reproduce:**
1. Run `ionic start test`
2. Once the project is created, open up the config.xml and look at the name tag. It will be MyApp.

**Ionic info:**
```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v8.0.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
```

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2413

**Comment by shaneparsons** [comment]
Ah, my bad.
