### ISSUE TITLE
close on keyboard, whole view gets blank(white) in ios

### ISSUE THREAD

**Issue by chetanawate28** [ionic-team/ionic#11995]
**Ionic version:**  (check one with "x")
 1.7.16

**Current behavior:**
when i type data in input box and going to click to another element on page or suppose to go to touch for another input box . my whole page elements gets hide (i.e. screen gets white .)  . 

**Expected behavior:**
normally i for other element in IOS app runs properly but in case of Input Box this issue occure.

**Steps to reproduce:**
click on input box then click on anywhere in page or another input box i case of IOS .

*** Observation of problem ***
HTML Structure: <ion-content> <ion-scroll> <input type="text" placeholder="keyboard open"> </ion-scroll> </ion-content>

**Keyboard plugin version **
tested with version- 1.0.8 and 2.2.1

**Related code:**
<ion-view>
<ion-content scroll="false">
<div >
****
</div>
<ion-scroll ...>
<div>
    <div class="col-50">
         {{ordermodel.price}}
    </div>
    <div class="col-50">
            <input type="tel" placeholder="price" maxlength="8" />
     </div>
</div>
 <div>
       <div class="col-50">
             {{ordermodel.quantity}}
       </div>
       <div class="col-50">
             <input type="tel" placeholder="quantity" maxlength="8"/>
       </div>
</div>
</ion-scroll>
</ion-content >
</ion-view>

**Other information:**
i get solution on it that change ion-scroll instead of ion-content , it solves my issue but i think its not feasible solution .

**Ionic info:**

cordova CLI - 6.4.0
gulp version - 3.9.1
gulp local - 3.9.1
ionic framework version- 1.3.3
ionic CLI version - 1.7.16
ionic app lib version -0.7.3
node version- v6.10.3

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Would you mind sharing a repo we could use to reproduce this issue?

**Comment by chetanawate28** [comment]
hey hi, which info you want , i cant share repo with u . its industry project .  

`<ion-view>
<ion-content scroll="false">
<div >
****
</div>
<ion-scroll ...>
<div>
    <div class="col-50">
         {{ordermodel.price}}
    </div>
    <div class="col-50">
            <input type="tel" placeholder="price" maxlength="8" />
     </div>
</div>
 <div>
       <div class="col-50">
             {{ordermodel.quantity}}
       </div>
       <div class="col-50">
             <input type="tel" placeholder="quantity" maxlength="8"/>
       </div>
</div>
</ion-scroll>
</ion-content >
</ion-view>
`

*** Observation of problem ***
HTML Structure: <ion-content> <ion-scroll> <input type="text" placeholder="keyboard open"> </ion-scroll> </ion-content>

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-v1#285
