### ISSUE TITLE
datetime - Allow pickerFormat to show weekday

### ISSUE THREAD

**Issue by Daskus1** [ionic-team/ionic#11999]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] feature request

**Current behavior:**
When selecting a date with `ion-datetime` it is not possible to see the weekday, thus users need to check a calendar (which shows the weekdays) and select the right date.
The following code **does not work** as expected, the first `DDDD` is ignore:

```
<ion-datetime 
    pickerFormat="DDDD, D MM YYYY" 
    displayFormat="DDDD MMM D, YYYY" 
></ion-datetime>
```

![current](https://user-images.githubusercontent.com/16157888/26980167-9bd29f94-4d31-11e7-971c-7527570270d4.PNG)

**Expected behavior:**
The weekday should be shown next to the date. This would improve a lot the user experience of users that need to know which day of the week the selected is.
![expected](https://user-images.githubusercontent.com/16157888/26980174-a1bcb142-4d31-11e7-97b4-c9bae3cf4a4e.png)

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#251

**Comment by saiprasad2595** [comment]
Hi, any update on this feature?
