### ISSUE TITLE
Infinite Scroll Not Firing (ionInfinite) event in IOS

### ISSUE THREAD

**Issue by stevenferretti** [ionic-team/ionic#11994]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Infinite Scroll works fine in broswer, but does not fire (ioninfinte) event when compiled to IOS app

**Expected behavior:**
(ionInfinite) to fire.

**Steps to reproduce:**
https://ionicframework.com/docs/api/components/infinite-scroll/InfiniteScroll/

**Comment by chriswdy** [comment]
Compareable issue here with ionic 3 on iOS, also with your reference implementation (link above).
Works fine on Android, but fires pagination event after a second swipe or a slow "scroll down" only.

@stevenferretti : Did you find a solution or workaround yet?
