### ISSUE TITLE
[Loading]: Being able to catch an error from the dismissAll method.

### ISSUE THREAD

**Issue by AlanAlbuquerque** [ionic-team/ionic#12009]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request

**Current behavior:**
```
import { Loading, LoadingController } from "ionic-angular";

this.loading = this.loadingCtrl.create({
      content: message
});
this.loading.present();

this.loading.dismissAll();
```

**Expected behavior:**
```
import { Loading, LoadingController } from "ionic-angular";

this.loading = this.loadingCtrl.create({
      content: message
});
this.loading.present();

this.loading.dismissAll().catch((e) => console.error(e)); // can catch the error
```

**Steps to reproduce:**

```
this.loading.dismissAll();
// call again in another part of my code (like an helper class that centralize loading requests)
this.loading.dismissAll();

```
-->

**Other information:**
STACK:

```
core.es5.js:1084 ERROR Error: Uncaught (in promise): no views in the stack to be removed
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.es5.js:4128)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.es5.js:4119)
    at t.invokeTask (polyfills.js:3)

```
**Ionic info:**

```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.1.2 ios 4.3.1
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.2
    OS         : Linux 4.8
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by digaus** [comment]
Imo I do not see a reason why there is an error thrown... just ignore dismissAll() if no loadings are active... should be better then manually handling the exceptions.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#253

**Comment by ayman-alkom** [comment]
hi @jgw96, hi @AlanAlbuquerque 
Can we make `Loading.dismissAll()` static?
I think that this error not have to happen, because we call this function to do a global work over all the loading objects.

**Comment by AmitMY** [comment]
@jgw96  While they classified it as a feature request, I think it is a bug.
[This line](https://github.com/ionic-team/ionic/blob/efd54750bf44b622a20078be02a2335aabc6dcec/src/components/loading/loading.ts#L96) should be:
```
if(!this.nav) {
  return Promise.resolve()
}
return this._nav.popAll()
```

And same for Toast.. Perhaps they should have a parent class handling this
