### ISSUE TITLE
Please provide a way to set default value to ion-datetime picker

### ISSUE THREAD

**Issue by kceiw** [ionic-team/ionic#12003]
I use ion-datetime to let the user to pick a day. But  I cannot set a default value to use when the picker shows. The picker shows some a first day a year.
It's not convenient for end users to use it.

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
