### ISSUE TITLE
Tapping the already active tab should scroll content up to top

### ISSUE THREAD

**Issue by joeflateau** [ionic-team/ionic#12001]
Many apps (see Twitter for an example) scroll to the top of the content when you tap the active tab. 

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Tapping the active tab does nothing 

**Expected behavior:**

Tapping the active tab would scroll to the top of the content

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by piotrowski** [comment]
Interesting. Is this default behaviour or only chosen behaviour of some apps?

Is there a way to achieve this manually?

**Comment by fephil** [comment]
I have done this by:

1. Including 'Content' ionic dependency in the page.
2. Having the following code:

```
  // When this tab is selected
  ionSelected() {
    this.content.scrollToTop(); // 300ms
  }
```

**Comment by danielsogl** [comment]
@fephil Can you add your ionic info output to your issue so we can see which version you exactly use?

**Comment by fephil** [comment]
@danielsogl As requested:

```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.1.0
```

**Comment by joeflateau** [comment]
@fephil when switching tabs does this scrollToTop? The behavior I'm looking for would only scroll to top if the current tab is already active

**Comment by joeflateau** [comment]
@piotrowski not 100% sure if it's default behavior. But many/most apps do this: Facebook, Twitter, LinkedIn. Enough to make me think "this is odd" when tapping the selected tab did not scroll me to the top.

**Comment by fephil** [comment]
@joeflateau no, it works as I believe you want it to work.

**Comment by joeflateau** [comment]
@fephil nice! I'm trying now...

**Comment by joeflateau** [comment]
@fephil wonder too if this could be made into a class decorator to simplify things.

**Comment by joeflateau** [comment]
@fephil sort of works. but if the content has some scroll momentum already it gets janky

**Comment by fephil** [comment]
Interesting, I don't get that behaviour on my app/devices. Perhaps adjust the animation time?

**Comment by joeflateau** [comment]
@fephil I'll bet it's because I also have pull to refresh on that page, tbh

**Comment by joeflateau** [comment]
@fephil nope, removed the refresher and same behavior. if it's already scrolling, the "scrollToTop" animation happens but then the page jumps to the place where the previous momentum would have it end up.

**Comment by fephil** [comment]
@joeflateau Sorry, can't help as I don't get that behaviour (just checked again).

**Comment by piotrowski** [comment]
What platform and environment (device, simulator, browser) are you both testing in?

Workaround for this of course would be to "stop" or "cancel" the active motion somehow.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#252

**Comment by joeflateau** [comment]
@jgw96 @fephil sorry to re-open this, i just realized that tapping the status bar to scroll to top works as expected (if a scroll is in progress it's aborted and the content is scrolled to top.) I am having trouble finding the code that actually does that, any ideas?

**Comment by janpio** [comment]
@joeflateau I think you are looking for https://github.com/ionic-team/ionic/blob/a8ceee467b1d83a74d875e2162732c31d72c566e/src/components/tabs/tabs.ts#L556-L559
