### ISSUE TITLE
Slides Component Stuck iOS Only

### ISSUE THREAD

**Issue by matthew-valenti** [ionic-team/ionic#12007]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Swiping slides component to go to next slide works for ~20 slides. Then, on iOS only, swipe slide (to go to next slide) goes backwards one slide.

**Expected behavior:**
Swipe should slide to next slide or if no slides then do nothing.

**Steps to reproduce:**
Unable to reproduce on web or android. Screencast of behavior on iOS can be seen here: http://www.screencast.com/t/7cKkyMyt

**Related code:**

```
html:
<ion-slides>
    <ng-container *ngFor="let item of items">
        <ion-slide>
            ...

add item ts:
this.items.push(item);
this.slides.update();

remove item ts:
this.items.shift();
this.slides.slidePrev(0); // IONIC BUG WORKAROUND: https://github.com/driftyco/ionic/issues/10846
this.slides.update();
```

**Other information:**
Slides are bound to an array of item objects. We get new items and add them to the array (which creates additional slides). As the array grows we remove old array items.

Sliding backwards thru slides works. However, getActiveIndex never changes. It's as if the slides component enters a stuck state and cannot recover.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 3.2.1
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.8.6 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. We will look into this.

**Comment by matthew-valenti** [comment]
Unable to reproduce this issue on release: 3.5.0
