### ISSUE TITLE
Footer background transparent after native keyboard opened

### ISSUE THREAD

**Issue by nrcrabbe** [ionic-team/ionic#12005]
**Ionic version:**
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On an `<ion-content>` clicking an ` <input>` that brings up a device's keyboard turns an `<ion-footer>`'s background transparent if the keyboard causes the `<ion-content>` to scroll.

***Without scroll (no bug)***

![image](https://user-images.githubusercontent.com/13173197/27008498-a161be9a-4ec6-11e7-9399-a664a58edc24.png)

***With scroll (bug)***

![image](https://user-images.githubusercontent.com/13173197/27008502-c69ae088-4ec6-11e7-8c40-ccaf3d48d121.png)

**Expected behavior:**
Background of the footer does not change

**Steps to reproduce:**
- Create a blank starter project.
- Paste the code below into home.html
- Run on android device or emulator.
- Scroll down an amount so that when the keyboard appears it causes the `<ion-content>` to scroll (in my example, try "Stacked Label"). Touch an input to reveal the keyboard. Footer background is now transparent

**Related code:**

```
<ion-header>
  <ion-navbar>
    <ion-title>
      Ionic Blank
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <ion-list>
  <ion-item>
    <ion-label color="primary">Inline Label</ion-label>
    <ion-input placeholder="Text Input"></ion-input>
  </ion-item>

  <ion-item>
    <ion-label color="primary" fixed>Fixed Label</ion-label>
    <ion-input type="tel" placeholder="Tel Input"></ion-input>
  </ion-item>

  <ion-item>
    <ion-input type="number" placeholder="Number Input with no label"></ion-input>
  </ion-item>

  <ion-item>
    <ion-label color="primary" stacked>Stacked Label</ion-label>
    <ion-input type="email" placeholder="Email Input"></ion-input>
  </ion-item>

  <ion-item>
    <ion-label color="primary" stacked>Stacked Label</ion-label>
    <ion-input type="password" placeholder="Password Input"></ion-input>
  </ion-item>

  <ion-item>
    <ion-label color="primary" floating>Floating Label</ion-label>
    <ion-input></ion-input>
  </ion-item>

  <ion-item>
    <ion-input placeholder="Clear Input" clearInput></ion-input>
  </ion-item>

  <ion-item>
    <ion-textarea placeholder="Enter a description"></ion-textarea>
  </ion-item>
</ion-list>
</ion-content>
<ion-footer padding>
  Look here
</ion-footer>
```

**Other information:**

Only tried on this version of ionic and on android (5.0 on device and 6.0 on emulator)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : Linux 4.8
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! The reason your seeing this is because you do not have an `ion-toolbar` in your footer. As our docs show [here](https://ionicframework.com/docs/api/components/toolbar/Footer/#usage) you should have an ion-toolbar inside your footer. Also, if you use an `ion-toolbar` you will not have to use the `padding` attribute on your footer anymore as the toolbar takes care of that for you 😃 .

**Comment by nrcrabbe** [comment]
Super, cheers. Could the docs be updated to say that the child of the ion-footer should be an ion-toolbar or else weirdness will ensue?
