### ISSUE TITLE
Ionic DateTime Picker Display Issue

### ISSUE THREAD

**Issue by NasserAssaly** [ionic-team/ionic#12019]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/
![ionic date time](https://user-images.githubusercontent.com/25197598/27033817-af4e2648-4f83-11e7-9394-afd12fa8b0af.png)

**Current behavior:**
when we display full date time into ionic datetime picker, month names not show with full string and tt in time too.

**Expected behavior:**
show all strings

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Would you be able to provide a repo we could use to reproduce this issue?

**Comment by NasserAssaly** [comment]
i am sorry i have large application with local svn repository so i cant upload it,
my main problem is only that date names not show in full mode correctly just like the image (image from my application),
so if there is any fix to solve this problem please advice.

**Comment by jgw96** [comment]
No problem @NasserAssaly 😃 , if you wouldn't mind could you just post a snippet of what your datetime code looks like?

**Comment by NasserAssaly** [comment]
import { EtQFieldUtilities } from './../../../core/business/field/etq-field-utilities';
import { EtQDateField } from './../../../core/business/field/etq-fields/etq-date-field.module';
import { DateField } from './field-date.module';
import { Component, NgZone } from '@angular/core';
import { Events } from 'ionic-angular';

/**
 * description: custom field to load attachment field design and functions
 * @export
 * @class EtqFieldDate
 * @author Nasser Assaly :)
 * @author Rana Abul-Haija
 * @author Mohammad Barghash
 */
@Component({
    templateUrl: 'field-date.component.html',
    selector: 'field-date'
})


export class EtqFieldDateComponent {
    /**
     * global model to set field properties and values
     * @type {EtQField}
     * @memberOf EtqFieldDate
     */
    private model: EtQDateField;
    private dateValue: any;
    private displayFormat: string;
    private readOnly: boolean;
    private borderColor: string = '#dedede';

    private event: Events
    constructor(private _ngZone: NgZone, ) { }

    /**
     * Init Date Type display format and values
     *  
     * @memberOf EtqFieldDateComponent
     * @author Nasser AlAssaly
     */
    ngOnInit() {
        if (this.model.setting.requiredType == 2) {
            this.model.isRequired = true;
        }
        if (this.event) {
            this.event.subscribe('validateFields', () => {
                if (this.model.isRequired && !this.model.values[0]) {
                    this.borderColor = 'red';
                }
            });
        }
        this.readOnly = EtQFieldUtilities.isReadOnly(this.model.setting);
        let dateFieldModule = new DateField();
        this.displayFormat = dateFieldModule.getDisplayFormat(this.model.setting.fieldType, this.model.setting.dateTimeStyle);
        this.dateValue = this.model.values[0];
        if (this.model.setting.fieldType == 17 || this.model.setting.fieldType == 15) {
            this.dateValue = dateFieldModule.toISOFormatString(this.model.values[0]);
        } else {
            this.dateValue = dateFieldModule.toISOFormatString('01-06-1993 ' + this.model.values[0]);
        }
    }

    public setFieldValue(event): void {
        let dateFieldModule = new DateField();
        this.model.values[0] = dateFieldModule.fromISOFormatString(this.dateValue);
    }

    public updateValue() {
        this.model.setValue(this.model.values[0]);
        if (this.model.setting.refreshOnChange) {
            this.model.onChange();
        }
    }
}
