### ISSUE TITLE
IonContent scroll has ionScrollEnd called too soon and an item click passes incorrect data

### ISSUE THREAD

**Issue by pjc2007** [ionic-team/ionic#12014]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
My application has a simple list within the main page content, where each I want to show another page based on which list item is clicked. The elements are just a `div` so I use the `tappable` attribute to get rid of the delay. A simplified example is [at this plunk](https://plnkr.co/edit/sqVX59zvKkXsyhs57RTZ?p=preview)

The problem is if I flick scroll, and then tap the list to stop, the click event fires, instead of allowing me to just stop the scroll. To get around this, I subscribe to the `ionScrollEnd()` and wait a set time after this is called before I allow the click. This seems to almost do what I am after except for two things.

1. More noticeable on iOS, but the `ionScrollEnd()` seems to be called just before the scroll finishes
2. If I click a list element just as the scroll is stopping (but not quite stopped), the incorrect data is passed to the click handler. 

These problems only seem to occur when I use either a button (instead of a div) or when I use the `tappable`. If I remove the `tappable`, the clicks then feel laggy when clicking one after another (there is too much delay). Again, seems worse on iOS.

**Expected behavior:**
1. ionScrollEnd is called once the scroll has completely stopped
2. Correct item passed to the handler (though if 1. is fixed I can stop the call to the click while there is any scrolling

**Steps to reproduce:**
There is an example [at this plunk](https://plnkr.co/edit/sqVX59zvKkXsyhs57RTZ?p=preview), however it can't be reproduced on the descktop, as we need the scroll to gradually stop as it does after a flick on a device
-->

**Related code:**
As per the plunk, I have the following...

		  public ionScrollStart(): void {
			this.scrollStartTime = Date.now();
		  }

		  /**
			* Handler for the ionScrollEnd event
			*/
		  public ionScrollEnd(): void {
			this.scrollEndTime = Date.now();
			console.log(this.scrollEndTime)
		  }
		  
		  public onClick(item) : void {
			if (this.content.isScrolling || !this.allowClick()) {
			  console.log("click not ready");
			  return;
			}
			console.log(item);
			alert(item);
		  }
		  
		  private allowClick() : boolean {    
			let now = Date.now();
			return (now - this.scrollStartTime >= this.scrollStopClickDelay &&  now - this.scrollEndTime >= this.scrollStopClickDelay);    
		  }

**Ionic info:** 

```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.1.2 ios 4.3.1 windows 4.4.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
```

**Comment by jgw96** [comment]
Thanks for using Ionic! We will look into this. Also, could you try installing [our wkwebview](https://github.com/ionic-team/cordova-plugin-wkwebview-engine) plugin and seeing if that fixes the issue for you?

**Comment by pjc2007** [comment]
@jgw96 thanks for the wkwebview suggestion. Have installed this and just running some app wide testing to make sure everything is still ok being hosted in the different webview. As far as this issue goes the wkwebview has certainly fixed it, and also a couple of other issues I was working around on iOS, which is great.  Looks like this could be the solution!

**Comment by jgw96** [comment]
Awesome news @pjc2007 ! We are planning on making the wkwebview plugin the default very soon, but it is production ready for 99% of use cases as it sits now. Thanks for using Ionic!
