### ISSUE TITLE
Toast button variable is applying to all modes

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic#12021]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Changing the value of the Sass variable `$toast-wp-button-color` affects all modes.

**Expected behavior:**
`$toast-wp-button-color` should only affect the Windows toast, and there should be other variables for the other modes. 

**Steps to reproduce:**
Add the following to the `theme/variables.scss` file:

```
$toast-wp-button-color : #387EF5;
```

Notice that the color of the toast button in `ios` and `md` changes, as well. 

**Related code:**

https://github.com/ionic-team/ionic/blob/master/src/components/toast/toast.wp.scss#L78

This should be changed to

```
.toast-wp .toast-button {
```

**Other information:**
Discovered in this issue: https://github.com/ionic-team/ionic-site/issues/1040

**Comment by brandyscarney** [comment]
This is no longer an issue with v4.

**Comment by betatools** [comment]
@brandyscarney This is still an issue for me. What do I need to update?

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 6.3.0 ios 4.5.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.0.0 
    Node              : v8.5.0
    npm               : 5.5.1 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

**Comment by brandyscarney** [comment]
v4 isn't released yet but it won't be an issue then, you can set the following if you'd like to null out the wp variable:

```
$toast-wp-button-color: null;
```
