### ISSUE TITLE
Programatically close DateTime component

### ISSUE THREAD

**Issue by pedropapa** [ionic-team/ionic#12022]
**Ionic version:**  (check one with "x")
3.4

**I'm submitting a ...**  (check one with "x")
[X] feature request

**Current behavior:**
There's no way to programmatically close a DateTime component.

Already tried the following options:
```
@ViewChild('dtStart') dtStart: DateTime;
```

```
<ion-datetime #dtStart displayFormat="DD/MM/YYYY"  cancelText="Cancelar" doneText="Aceitar" [(ngModel)]="navParams.data.dt_start"></ion-datetime>
```

```
setTimeout(() => {
            console.log('Close it!');
            this.dtStart._isOpen = false; //doesn't work
            this.dtStart.open(false) = false; //argument error
            this.dtStart.close(); //doesn't exists
        }, 10000);
```

**Why?**

On Android, there's the hardware back button, when it's triggered while a DateTime component is opened to the user, the `nav.pop` is called (programmatically) and the user goes back to the previous nav, but the DateTime component is still opened to the user. I just want to close it as well.

```
insert the output from ionic info here
```

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.4.0
    Gulp CLI         : CLI version 3.9.1 Local version 3.9.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.0
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-gulp          : 1.0.1
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.0.0 ios 4.3.1
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v7.8.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.0
    ios-sim    : 5.0.6
    npm        : 5.0.3

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#254

**Comment by alexnu** [comment]
+1!

Right now ionic seems to have trouble with android's hardware back button, which prevents an app from having a native feel. With the requested feature we can manually fix that.

**Comment by alexnu** [comment]
Also @pedropapa if you want a temporary solution try [this](https://github.com/ionic-team/ionic/issues/10168), I've tried it and it works for everything (modals/pickers/action-sheets etc.).

**Comment by pedropapa** [comment]
@alexnu Thanks for the tip, I will try it out.

**Comment by robertolocal** [comment]
+1
