### ISSUE TITLE
didn't work fine just showing blank screen on android nexus 4 api 17

### ISSUE THREAD

**Issue by fidoafif** [ionic-team/ionic#12025]
**Ionic version:**  (3.3.0)

**I'm submitting a ...**  (bug report)

**Current behavior:**
Looks like I am not able to target api 17. If I run my app in emulator on a different virtual device with api level 23 and up , everything works fine, but from api level 16, 17 (I tested) just showing a blank screen.

I checked my android manifest file also . It says minimum SDK version as 16. So running on api level 16 or 17 should not be an issue. 

Moreover, I also didn't start code yet I just create a new starter ionic project and start running to check if everything work fine, unfortunately it just didn't work as well on api level 16 or 17 beside on the file config.xml it saiys minimum version as 16. 

**Steps to reproduce:**

Just create a new starter project
`ionic start myApp tabs`
Then add android platform and start build and run on the emulator api level 17
`ionic cordova platform add android`
`ionic cordova run android`

I tested on Android emulator "Nexus_4_Api_17"
**Related code:**

**Other information:**
This issue I get when update ionic to 3.3.0 before then it work fine on api level 16 or 17 and higher. Now I just updated to ionic 3.4.0 and still nothing changes I still get the same issue.

**Ionic info:** 

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.6.1

```

**Comment by chandanch** [comment]
You will have to install [crosswalk](https://crosswalk-project.org/) plugin in order for your app to work on 4.4 and below.

Add the cross walk plugin to your project using this command:
 `ionic plugin add cordova-plugin-crosswalk-webview --save`

Refer to this issue: [#6281](https://github.com/ionic-team/ionic/issues/6281) for more details.
