### ISSUE TITLE
iOS 11 Issue Roundup

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic#12020]
Another year, another iOS version. This is to track various iOS issues that open up because of iOS 11 beta. 
Note that because iOS 11 is in beta, some of these issues will be fixed by the time it is released or will need addressing by us.

1) Viewport changes. (#12011)
Beta Version: iOS 11 Beta 1

![](https://user-images.githubusercontent.com/2486593/27014624-01745604-4efd-11e7-8361-a4386b0101a6.PNG)

Adding the new `viewport-fit=cover` seem to fix the top part, but also causes issues with the bottom of the screen.

![](https://user-images.githubusercontent.com/2486593/27014647-4b744af2-4efd-11e7-9d8f-6d523982bf5a.PNG)

There's also a thread about this causing other issues in UIWebview, which can become a big problem.

https://twitter.com/jcesarmobile/status/872120741495533568

**Comment by manucorporat** [comment]
beta versions usually have problems in UI/WK that are solved before final release, fingers crossed
