### ISSUE TITLE
some http request cannot send in ios9

### ISSUE THREAD

**Issue by MissCuriosity** [ionic-team/ionic#12027]
version:
    ionic:3.4.0
    angular:1.5.3
    node: 8.0.0

bug:
    some  http request cannot happen in ios9.But it's normal in web/ios10/android

methods I have tried but failed
    1、add the same function in other service,and then call it
    2、use https
    3、add <meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'"> in index.html
    4、use 'X-Requested-With' :'XMLHttpRequest'
    5、use other uri

I'd appreciate it if you can provide me with some solutions

**Comment by MissCuriosity** [comment]
plz do not close this issue,thx!

**Comment by AmitMY** [comment]
So please fill the issue template.
Also, some code to reproduce it will help

**Comment by jgw96** [comment]
As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
