### ISSUE TITLE
Using Date type causes build to fail

### ISSUE THREAD

**Issue by romainbebert** [ionic-team/ionic#12039]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using JavaScript's Date type causes build to fail and give a "*.ts Module parse failed" error

**Expected behavior:**
Just like any JavaScript standard type, Date shouldn't cause build to fail

**Steps to reproduce:**

`ionic start dateTest`

then add in whatever page the declaration of a Date Object, like this : 
`date : Date = new Date(2017,09,16,10,0,0,0);`

**Related code:**

```
`date : Date = new Date(2017,09,16,10,0,0,0);`
```

**Other information:**
stack trace : 

[15:15:17]  ionic-app-script task: "build" 
[15:15:17]  Error: ./src/pages/home/home.ts Module parse failed:
            /Users/XXXX/Documents/XXXX/dateTest/node_modules/@ionic/app-scripts/dist/webpack/loader.js!/Users/XXXX/Documents/XXXX/dateTest/src/pages/home/home.ts
            Invalid number (16:35) You may need an appropriate loader to handle this file type. | function
            HomePage(navCtrl) { | this.navCtrl = navCtrl; | this.date = new Date(2017, 09, 16, 10, 0, 0, 0); | } |
            return HomePage; @ ./src/app/app.module.ts 13:0-46 @ ./src/app/main.ts 
Error: ./src/pages/home/home.ts
Module parse failed: /Users/XXXX/Documents/XXXX/dateTest/node_modules/@ionic/app-scripts/dist/webpack/loader.js!/Users/XXXX/Documents/XXXX/dateTest/src/pages/home/home.ts Invalid number (16:35)
You may need an appropriate loader to handle this file type.
|     function HomePage(navCtrl) {
|         this.navCtrl = navCtrl;
|         this.date = new Date(2017, 09, 16, 10, 0, 0, 0);
|     }
|     return HomePage;
 @ ./src/app/app.module.ts 13:0-46
 @ ./src/app/main.ts
    at new BuildError (/Users/XXXX/Documents/XXXX/dateTest/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at callback (/Users/XXXX/Documents/XXXX/dateTest/node_modules/@ionic/app-scripts/dist/webpack.js:119:28)
    at /Users/XXXX/Documents/XXXX/dateTest/node_modules/webpack/lib/Compiler.js:256:15
    at Compiler.emitRecords (/Users/XXXX/Documents/XXXX/dateTest/node_modules/webpack/lib/Compiler.js:351:37)
    at /Users/XXXX/Documents/XXXX/dateTest/node_modules/webpack/lib/Compiler.js:249:12
    at /Users/XXXX/Documents/XXXX/dateTest/node_modules/webpack/lib/Compiler.js:344:11
    at next (/Users/XXXX/Documents/XXXX/dateTest/node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (/Users/XXXX/Documents/XXXX/dateTest/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/XXXX/Documents/XXXX/dateTest/node_modules/tapable/lib/Tapable.js:158:13)
    at Compiler.afterEmit (/Users/XXXX/Documents/XXXX/dateTest/node_modules/webpack/lib/Compiler.js:341:8)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.3.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.9.0
Xcode version: Xcode 8.3.3 Build version 8E3004b
```

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1043
