### ISSUE TITLE
"ionic start" failing over npm 404

### ISSUE THREAD

**Issue by starsky135** [ionic-team/ionic#12032]
**Ionic version:**
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Running _ionic start_ to create a new project fails because this file:
https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node
is not found. This is not an issue with my internet connection, you can see for yourself that the file is not there.

**Expected behavior:**
_ionic start_ should be able to create a new project without running into npm exceptions.

**Steps to reproduce:**
Run _ionic start_ and try to create a new project.

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node
        Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

npm config set proxy http://example.com:8080

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2426
