### ISSUE TITLE
In a custom plug-in callback, open a new page, the page to refresh the data

### ISSUE THREAD

**Issue by wardenlzr** [ionic-team/ionic#12044]
In a custom plug-in callback, open a new page, the page to refresh the data
Like this,
TreePlugin.template([T.R_MobileLaw.Api.MobileLawService.host], result => {
let data = result.split("#");
T.TemplateId = data[1];//模板Id
T.nav.push(Page_MobileLaw_Task_Investigate_Issue, { TemplateId: T.TemplateId});
}, error => {
// alert(error); //（失败的回调）
});

Page_MobileLaw_Task_Investigate_Issue
In this interface, data cannot real-time refresh

Who can help me?Thank you very much

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
