### ISSUE TITLE
cordova-plugin-video-editor

### ISSUE THREAD

**Issue by fermedina** [ionic-team/ionic#12040]
Hi.

I want to create a thumbnail of a video and I using [Video Editor](https://github.com/jbavari/cordova-plugin-video-editor) plugin. In old versions of android this work fine, but in the new versions this method fail because the plugin don't request the permission READ_EXTERNAL_STORAGE.

This element is very outdated and should not be recommended by IONIC

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-native#1693
