### ISSUE TITLE
Improve accessibility on searchbar

### ISSUE THREAD

**Issue by Fdom92** [ionic-team/ionic#12048]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request

**Current behavior:**
I audit my PWA ionic app with lighthouse to see the PWA score and on accessibility i got a warning with the searchbar cause the template (input) dont have aria label. 

**Expected behavior:**
Not have this warning

**Steps to reproduce:**
Just build an ionic app with searchbar and use the lighthouse chrome extension.

**Comment by Fdom92** [comment]
Hi, i was thinking on adding this as my first PR to Ionic cause i want to contribute to this awesome repo so i read the contribution guides and i have to create first an issue so here i am.

I think this is a simple change and hope it can be merge.

Keep going this hard guys!

**Comment by jgw96** [comment]
Congrats on your first PR to Ionic! I commented on the PR itself with some details.
