### ISSUE TITLE
ServiceWorker registration failed:  DOMException: Failed to register a ServiceWorker: The URL protocol of the current origin ('file://') is not supported.

### ISSUE THREAD

**Issue by hemnath11** [ionic-team/ionic#12046]
ServiceWorker registration failed:  DOMException: Failed to register a ServiceWorker: The URL protocol of the current origin ('file://') is not supported.

development android apk get this error i try to start service work for push notification when app is killed

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Most likely you have [this line](https://github.com/ionic-team/ionic2-app-base/blob/master/src/index.html#L18) un-commented. Service workers do not work in cordova, only in the browser when your app is deployed as a PWA.

**Comment by hemnath11** [comment]
thank you for information

**Comment by hemnath11** [comment]
I want to use in my android app. Please help me How to use service workers in mobile apps.
