### ISSUE TITLE
ionic 2 get previous page

### ISSUE THREAD

**Issue by anivaisu** [ionic-team/ionic#12041]
Hi all,

I am using ionic 2.

I need previous page name in app.component.ts

How can i do this.

Kindly advice me,

Thanks

**Comment by janpio** [comment]
This is more a question for the Ionic Forum:  https://forum.ionicframework.com/

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
