### ISSUE TITLE
Cannot get previous page name 

### ISSUE THREAD

**Issue by anivaisu** [ionic-team/ionic#12045]
Hi,

  I am using ionic 2.

 I need get previous page name.

 Here is my code

 import { Component, ViewChild } from '@angular/core';
 import { Nav } from 'ionic-angular';
export class MyApp {
    @ViewChild(Nav) nav1: Nav;

    constructor(){
        var val=this.nav1.getActive();
        console.log("VAL");
        console.log(val.name);
    }
}

It's work only browser.

I run my app on device.and consoled the value is 't'.

I am getting this err

TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context.
    at Function.remoteFunction (<anonymous>:3:14)
    at Object.InjectedScript.callFunctionOn (<anonymous>:751:66)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
