### ISSUE TITLE
ionic2 - from one page control the display state of an element which belongs to another page

### ISSUE THREAD

**Issue by chenhailun2006** [ionic-team/ionic#12059]
There have a tabs page which the code like the following:

    <ion-tabs tabsPlacement="top">
     <ion-tab *ngFor="let item of items | async; let i = index;" [root]="main" [rootParams]="{item: item, index: i}" [tabTitle]="item.title"></ion-tab>
    </ion-tabs>
    <div class="board-control" [class.selected]="showBoard | async">
     Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro similique ex voluptas adipisci, nulla iusto repudiandae suscipit consequuntur odio, nemo, blanditiis aperiam quisquam rem. Explicabo quibusdam cumque voluptatibus, eos itaque.
    </div>

And in the "main" page, I want to control the display state of the div.board-control which located in the tabs page.

**NOTE: it always works well on the browser, but it doesn't work on ios.**

I have tried to use the self-defined service to control the state, but it doesn't work. But if I create a new **test** project, which for test the functionality descripted above, and it works well on ios. that's so weird.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
