### ISSUE TITLE
Hope < ion-icon> will can using SVG sprite 

### ISSUE THREAD

**Issue by fssgh** [ionic-team/ionic#12058]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
< ion-icon> Current only using iconfont.

**Expected behavior:**
< ion-icon> will using iconfont and SVG sprite 
**reference:**
[ngx-svg-icon](https://github.com/achwilko/ngx-svg-icon)
[create-svg-sprite ](https://github.com/achwilko/create-svg-sprite)

SVG sprite can using multiple color icon.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#255

**Comment by wescoder** [comment]
The issue referenced does not exists anymore, are there any updates?

**Comment by kensodemann** [comment]
It exists. The `ionic-feature-requests` repo is just a private repo is all. Right now, most feature-requests are on hold until Ionic v4 is released, as that is the absolute highest priority feature at this point.
