### ISSUE TITLE
Browser "back" button

### ISSUE THREAD

**Issue by dalibor983** [ionic-team/ionic#12052]
**Ionic version:**  (check one with "x")
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ x] feature request

**Current behavior:**
I'm trying to create progressive web application, not mobile application, that will work in desktop and mobile browsers.

I have nested ion-nav directives (root component has ion-nav in template and it loads second component with ion-nav in template)

```typescript
import {SecondComponent} from 'start'

@Component({
  template: '<ion-nav [root]="rootPage"></ion-nav>'
})
class RootComponent {
  rootPage = SecondComponent;
}
``` 
```typescript
import {ThirdComponent} from 'start'

@Component({
  template: '<ion-nav #myNav [root]="rootPage"></ion-nav>'
})
class SecondComponent{
  rootPage = ThirdComponent;
  @ViewChild('myNav') nav
}
```

I defined DeepLinker configuration for all components. So when application starts I have this path in browser address bar **http://localhost:8100/#/second/third**.

Then I run ```nav.setRoot(FourthComponent)``` in second component and I got this path in browser address bar **http://localhost:8100/#/second/fourth**.

Then I press back browser button and I got this path in browser address bar **http://localhost:8100/#/second/third** but in ion-nav of root component I get rendered two SecondComponent-s (one is hidden).

**Expected behavior:**
After back button pressed I expect to have this structure in html:
***RootComponent -> ion-nav -> SecondComponent -> ion-nav -> ThirdComponent***

Instead I get:
***RootComponent -> ion-nav -> [(SecondComponent -> ion-nav -> FourthComponent : hidden), (SecondComponent -> ion-nav -> ThirdComponent)]***

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! So there are a few things going on here. First, we do not recommend or support nesting `ion-nav`'s at the moment and because of this I am going to close this issue. Second, and this not really specific to the issue your facing which is more coming from the fact that you have nested `ion-nav`'s, but we are currently refactoring `ion-nav` to better handle url's, lazy loading etc so that it works better for PWA's.

**Comment by dalibor983** [comment]
@jgw96 So are you planning to support nested ```ion-nav```s in the future.
I found that current implementation of ```NavController``` has this method ```getActiveChildNav()```
