### ISSUE TITLE
No compatible version found: ionic-angular@3.3.4

### ISSUE THREAD

**Issue by cozzbie** [ionic-team/ionic#12057]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After updating my `package.json` to feature `ionic-angular@3.3.4` that error is throw when I run `npm install`

**Expected behavior:**
Project should be loaded with npm modules

**Steps to reproduce:**
Change `ionic-angular` version in `package.json` to 3.3.4
```bash
npm install
```

**Comment by ghenry22** [comment]
ChNge it to 3.4.0 instead of 3.3.4

**Comment by mburger81** [comment]
Yeah man: **3.4.0** and not **3.3.4**

**Comment by cozzbie** [comment]
Thanks. The RC documentation however says **3.4.0**

**Comment by mburger81** [comment]
You can see the upgrade steps in the changelog, looking to the history of the file they had a mistake there, but now it is ok

https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md
