### ISSUE TITLE
No padding for statusbar (on iOS) when nav-pushing inside a modal 

### ISSUE THREAD

**Issue by fiznool** [ionic-team/ionic#12051]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On iOS, when pushing a new page inside a modal, the status bar padding is lost.

**Expected behavior:**

Statusbar padding is preserved when pushing a new page inside a modal.

**Steps to reproduce:**

You need to use the iOS simulator to reproduce. Clone project at https://github.com/zmbc/statusbar and try.

**Other information:**

This is a direct clone of #8151 since that has been closed for a while and there doesn't seem to be the appetite to open/address the issue.

A workaround is available, [see this comment](https://github.com/ionic-team/ionic/issues/8151#issuecomment-285387798).

Screenshot: ![modal](https://cloud.githubusercontent.com/assets/13357648/18695117/603a468a-7f64-11e6-86ec-ba0357c94c42.jpg)

**Comment by envmBw** [comment]
Also happen in Android

**Comment by wbhob** [comment]
Duplicate: #8151
