### ISSUE TITLE
Aplication very slow on start in API 21

### ISSUE THREAD

**Issue by XSkunk** [ionic-team/ionic#12064]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Español:
Al ejecutar el comando Ionic cordova run android sobre un dispositivo con api 21 (5.0.1) cualquier aplicacion de Ionic muestra en consola este mensaje:

06-15 22:32:00.199 10268-10268/josexs.XSMusic.app I/chromium: [INFO:CONSOLE(1223)] "deviceready has not fired after 5 seconds.", source: file:///android_asset/www/cordova.js (1223)
06-15 22:32:00.229 10268-10268/josexs.XSMusic.app I/chromium: [INFO:CONSOLE(104876)] "Ionic Native: deviceready did not fire within 5000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.", source: file:///android_asset/www/build/main.js (104876)
06-15 22:32:00.229 10268-10268/josexs.XSMusic.app I/chromium: [INFO:CONSOLE(104871)] "Ionic Native: deviceready event fired after 18011 ms", source: file:///android_asset/www/build/main.js (104871)

La aplicacion se abre (ya que he modificado el tiempo en el que aparece el mensaje de error) despues de 20 segundos. En el api 23 (5.1.1, emulador) funciona todo OK

When running the Ionic cordova run android command on a device with api 21 (5.0.1) any application of Ionic displays this message in console:

The application opens (since I modified the time in which the error message appears) after 20 seconds.

**Expected behavior:**

La aplicacion tiene que abrirse sin mostrar deviceready event fired after 18011 ms
**Steps to reproduce:**

ionic run android o ionic run --release android en version 5.0.1 (API 21)

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
ionic run android o ionic run --release android en version 5.0.1 (API 21)

**Comment by AmitMY** [comment]
that is because you don't use prod. Please try `ionic run --prod android`

**Comment by XSkunk** [comment]
@AmitMY So I tried and temporarily has served to solve the problem, I imagine in my case, --prod is the same as --release no? To sign I would use this version and everything ok?. Thank you!

**Comment by AmitMY** [comment]
Well no, `--prod` means: "angular, please compile this for production, using the AoT compiler", and `--release` signs the app with cordova.
The AoT compiler is much slower than the JiT compiler, but it makes the bundle much much smaller, so it runs faster.

**Comment by jgw96** [comment]
Thanks for handling this one @AmitMY (:
