### ISSUE TITLE
regression for input select with floating label

### ISSUE THREAD

**Issue by bogomips** [ionic-team/ionic#12068]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After the user completes his choice, the floating label returns back over the user's input.

**Expected behavior:**
the label has to remain "up"

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2 browser 4.1.0
    Ionic Framework                 : ionic-angular 3.4.0

System:

    Node       : v7.7.1
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.1.2 
```

**Comment by efstathiosntonas** [comment]
same here, using 3.4.0, label floats on top of the element when input has some text.

**Comment by manucorporat** [comment]
Can you provide some source code that reproduces the issue?

**Comment by efstathiosntonas** [comment]
nothing special: 

```
        <ion-label stacked>Gender</ion-label>
        <ion-select okText="ΟΚ" cancelText="Cancel" formControlName="selectedGender" multiple="false" [(ngModel)]="petGender">
          <ion-option>Male</ion-option>
          <ion-option>Female</ion-option>
        </ion-select>

```
demo:
https://media.giphy.com/media/xUA7aLZp1Qfhgnhgti/giphy.gif

**Comment by theHellyar** [comment]
This is till an issue in 3.5.3

Use Floating input with type="number" then enter any non number character and it will overlap.

**Comment by mieszczans** [comment]
It's because you did not contain ion-input and ion-label in ion-item. Inside that container everything work great. So I don't know if it should work like that.
