### ISSUE TITLE
Add transparency to Tabs bar

### ISSUE THREAD

**Issue by shamank** [ionic-team/ionic#12067]
**Description:**
This is a feature request (I'm not sure this is the right place to do this).
I couldn't find a way to add transparency to the tabs bar. This is what I want to achieve:

![transparent-tabs](https://user-images.githubusercontent.com/819192/27199971-572dca46-51ee-11e7-88db-d703e73d5e6b.png)

So I think a nice implementation would be a var in SASS config to adjust a transparency factor to the entire tabs bar. I've already seen this in some Android apps so it would be a nice and simple (I wish) feature.

Thanks!

**My `ionic info`:**
```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : Linux 3.19
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3 
```

**Comment by AmitMY** [comment]
Regardless of this getting in or not, here is how you can try to do it: (right now, not tested)
This is not as simple as making it transparent, as the actual scroll content is not located there, but has a `margin-bottom`.
However, if you change that to `padding-bottom` that might work for you, as now the element is there, and can be fully scrolled.

**Comment by AmitMY** [comment]
Regardless of if this gets into the framework or not, you can achieve this effect now by having `[fullscreen]="true"` on your `ion-content`, then setting `.tabbar` to have an opacity.

**Comment by shamank** [comment]
That worked! Thanks!

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#257
