### ISSUE TITLE
Just a question: why all the layers and elements are set with "position:absolute" by default?

### ISSUE THREAD

**Issue by gatoenano** [ionic-team/ionic#12066]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

Hi guys! 

Just a question regarding css. Why all the layers and elements are set with "position:absolute" by default? I'm in serious troubles to control the layers because of this... I have to say that the app that I'm working now, have its own design, and "to fight" to override some Ionic properties is hard sometimes, but the most one difficult thing to understand is, why all the elements are positioned in absolute, there's a good reason to do that? Why don't use a grid system by default? 

I just want to know and understand :) 

Many thanks in advance

**Comment by manucorporat** [comment]
not all layers are absoluted, which ones do you mean?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
