### ISSUE TITLE
bug: ion-datetime does not respect max/min value

### ISSUE THREAD

**Issue by howdoesthisthingwork** [ionic-team/ionic#12070]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>*Summary*
During date selection, this specific scenario allows user to select dates past the maximum date set by option, and also allows selection of Non-existent dates like September 31. 

Also occurs with allowing selection of dates before minimum dates.

**Steps to Reproduce**

Go to:
https://ionicframework.com/docs/api/components/datetime/DateTime/

1. Select the Firefox date.
2. Chose August 31, 2002.
3. Hit Done.
4. Open date picker again.
5. Without touching anything else, change month to September.

Date will show September 31. even though September only has 30 days. Allows save.

**Other scenarios**
There are multiple scenarios that lead to similar problems:
_Scenario 1:_
1. Select September 30.
2. Click done.
3. Open and change month to October.
4. October 31 does not show up as an option. In order to get it to show up, user must first cause some other change event on the date, like selecting October 29, and then October 31 will show as an option.

_Scenario 2:_
1. Set a min date in options in html. i.e. 6/15/2017.
2. Open datepicker. Select 7/1/2017.
3. Hit done.
4. Open datepicker. Change month to June. The 1 will remain so date will be 6/1. Hit done.

Datepicker allows June 1 to be saved.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by lpsantana** [comment]
Any news on this?
