### ISSUE TITLE
DateTime modal close with hardware back button wont work

### ISSUE THREAD

**Issue by craftpip** [ionic-team/ionic#12079]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using the DateTime plugin, when the date time selector is open, the user cannot use the hardware back button to close the date time modal.

**Expected behavior:**
The date time modal should close when back button is pressed.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.11.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10
```

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-native#1707

**Comment by craftpip** [comment]
afaik, this issues belongs here, as its part of the ionic framework components
https://github.com/ionic-team/ionic/blob/master/src/components/datetime/datetime.ts

Apologies, i got you confused by calling the DateTime component a plugin.

**Comment by guillerial** [comment]
Any news? Same issue here.
