### ISSUE TITLE
infinite scroll with ion-slide tabs will loading in every tabs elements

### ISSUE THREAD

**Issue by XiaoLuo01** [ionic-team/ionic#12076]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have use ion-slide tabs to slide subTitle ,so it can control the ion-content's content , but there is a problem,  when to scroll the first page ,it will load data, but other pages will also loading data too; because there are just one page with the same function, how to solve this issue?  there are so many page with same construction,  so  i  want to click one slide tabs  just load his own data, not influence others , thank you

**Expected behavior:**

**Steps to reproduce:**
<!-- If you are able to illustrate the bug or feature request with an example, please provide steps to reproduce and if possible a demo using one of the following templates:

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/cpeRJs?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
