### ISSUE TITLE
ion-textarea duplicates when focused and scrolled on Ionic 2

### ISSUE THREAD

**Issue by tokidoki11** [ionic-team/ionic#12088]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x] **2.x**
[x] **3.x** (edited: it seems happening on version 3.4 as well)

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When ion-textarea being focused and the container is scrolled, you can see that ion-text is duplicated rendering 2 textarea

**Expected behavior:**

There should not be any duplication

**Steps to reproduce:**
1. Click the text-area
2. Scroll outside text area

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.1
ios-sim version: 6.0.0
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.3.3 Build version 8E3004b
```

**Comment by manucorporat** [comment]
1. Update to latest 3.4.0
2. Which platform? iOs, android, desktop?
3. Does it actually cause any problem?

**Comment by tokidoki11** [comment]
Hi,
1. I just now updated to 3.4, issue still there
2. All platform (ios,android, and web)
3. It is quite disturbing because the application that im building looks glitchy
