### ISSUE TITLE
Input type DOM UI not updated

### ISSUE THREAD

**Issue by jeffreytck** [ionic-team/ionic#12081]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The input type doesn't updated in UI. It was workable in previous version (4.1.2), my input type change either password/text(for example password to show in cleartext), will change input.type and password able show in cleartext but it doesn't show password in cleartext in version 4.1.3 even try inspect element to check input type already updated to 'text'

**Expected behavior:**

Input type updated and UI for input updated

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```
--> html
<ion-item no-lines [class.invalid]="!myForm.controls.userPass.valid  && (userPass || submitAttempt)">
          <ion-icon name="lock" item-left></ion-icon>
          <ion-input #inputPass type="password" formControlName="userPass" placeholder="{{ 'PASS' | translate }}"></ion-input>
          <button ion-button item-right icon-only clear *ngIf="myForm.controls.userPass.value!==''" (click)="showPassword(inputPass)">
            <ion-icon name="{{showPass}}"></ion-icon>
          </button>
        </ion-item>

--> typescript
showPassword(input: any): any {
    input.type = input.type === 'password' ?  'text' : 'password';
    this.showPass = input.type === 'password' ? 'eye' : 'eye-off';
 }

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
Cordova CLI: 6.4.0 
Ionic Framework Version: 3.4.2
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.3.3 Build version 8E3004b

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/cpeRJs?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by jeffreytck** [comment]
sorry, i m not idea how to create it in plunker

**Comment by jgw96** [comment]
@jeffreytck , i made a plunker [here](http://plnkr.co/edit/RguTYbwclVv8DqyXGZlS?p=preview) using your code. I may be misunderstanding the issue here, but it seems that the password does show in cleartext.

**Comment by jeffreytck** [comment]
what is version of ionic-angular using? 
The plunker you created is issue that faced, e.g. field is in "PASSWORD" type and beside got a icon to click and change field to "TEXT". You might test it out enter some word in field and click beside icon, the text won't show but if u try focus on field again, the type of field will change to "TEXT" for the version u created. You might try to using ionic-angular 3.3.0, there is working without issue.

**Comment by jeffreytck** [comment]
Hi @jgw96 , any update for this?

**Comment by AngelaRg** [comment]
I´m not sure if I am understanding correctly the problem you describe, but I am also facing a problem regarding input fields when upgrading to ionic-angular 3.5.3. Sounds like it might be the same or related.

One case is a field for recovering password. We ask for the email address of the user. By default we give it the value of the email address stored on the device. But, if the user deletes this address, types in a new one, and taps the sending button without losing focus on the email address, the value won't be updated! However, if the user taps outside of the field before tapping the sending button, it works as expected.

This happens as well with other input fields. Is there any fix for this or anyone knows if is it solved in the new version of ionic-angular?

It also seems that it happened only on the iOS version. I hope I explained it enough, unfortunately I can´t provide the code now nor test any further but if it is needed I will do it later.

**Comment by AngelaRg** [comment]
For me, changing from using blur to ionblur did not solved, so i used the input event and it works again.
