### ISSUE TITLE
Cannot install third library

### ISSUE THREAD

**Issue by luckyboy07** [ionic-team/ionic#12084]
**Ionic version:**  (check one with "x")
[ ] 3.x

**I'm submitting a ...**  (check one with "x")
[ ] bug report

**Current behavior:**

**Expected behavior:**

**Other information:**
I have a screenshot here, can you help me what is wrong with this? 

> 
![screen shot 2017-06-19 at 10 38 50 am](https://user-images.githubusercontent.com/17866364/27267585-07560592-54dc-11e7-84f6-7e2f227ca616.png)

**Comment by AmitMY** [comment]
> Missing write access ... Permission denied

When you try to install global libraries, if you don't have permissions on your user, try running with `sudo`. or after moving to a super-user by `sudo -i`

This is not an issue with ionic.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
