### ISSUE TITLE
ion-tab  did not work  without root property

### ISSUE THREAD

**Issue by giscafer** [ionic-team/ionic#12082]
tab didnot work without root property,the page is blank，there is not a tab。

**Ionic version:**  (check one with "x")
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report

sample from http://ionicframework.com/docs/api/components/tabs/Tab/

**Related code:**

```
<ion-tabs>
  <ion-tab (ionSelect)="chat()" tabTitle="Show Modal"></ion-tab>
</ion-tabs>
```

**Comment by AmitMY** [comment]
This stracture works nicely:
```html
<ion-tab *ngFor="let tab of tabs"
             [root]="tab.component? tab.component: null"
             (ionSelect)="tab.action? tab.action(): null"
             tabBadge="{{tab.badge}}" tabBadgeStyle="danger"
             tabTitle="{{tab.title}}"
             tabIcon="{{tab.icon}}"></ion-tab>
```

So for your use case, to let ionic know you don't want to move to any component, do:
```
<ion-tabs>
  <ion-tab (ionSelect)="chat()" [root]="null" tabTitle="Show Modal"></ion-tab>
</ion-tabs>
```

**Comment by giscafer** [comment]
@AmitMY thks

**Comment by AmitMY** [comment]
Mind keeping this issue open? This either needs to be documented or set default value to `[root]`, so it is an issue :)

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.
