### ISSUE TITLE
in the ion-range dualknobs example knobs are not moving

### ISSUE THREAD

**Issue by comfortme** [ionic-team/ionic#12083]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
on the site dualknobs example is not working, knobs are not moving

**Expected behavior:**
knobs should move

**Steps to reproduce:**
directly copy this example which is on the ion-range example on the site.
` <ion-item>
    <ion-label>dual, step=3, snaps, </ion-label>
    <ion-range dualKnobs="true" [(ngModel)]="dualValue2" min="21" max="72" step="3" snaps="true"></ion-range>
  </ion-item>`

you wont be able to move knobs.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.7.0
    OS         : Windows 8.1
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.8

**Comment by AmitMY** [comment]
- Does `dualValue2` exist?
- Are you on RTL by any chance? (range is broken on RTL, fixed in next version)
- It works in the demo, so can you try the source:
```
    <ion-item>
      <ion-range dualKnobs="true" pin="true" [(ngModel)]="structure" color="dark">
        <ion-icon range-left small name="brush"></ion-icon>
        <ion-icon range-right name="brush"></ion-icon>
      </ion-range>
    </ion-item>
```

**Comment by comfortme** [comment]
your example is not working either
here you can see that on the plunker
[http://plnkr.co/edit/qHzkwh7UzRvyggZc0Ryb?p=preview](url)

**Comment by AmitMY** [comment]
You didn't set `structure`. Set it to `{lower: 33, upper: 60}` and it works

**Comment by comfortme** [comment]
@AmitMY thank you it is working now.
but if it's not a dualknob you don't need to set structure. that's weird

**Comment by AmitMY** [comment]
That is weird! Mind keeping this issue open?

Either there should be a default value set if value is not set (for example `{lower: min, upper: max}`, or it should be documented better: (I only knew how to help by looking at the source code)

Current doc:
> Setting the dualKnobs property to true on the range component will enable two knobs on the range. If the range has two knobs, the value will be an object containing two properties: lower and upper.

Need to add something like "using dualKnobs you must set your model to have `lower` and `upper`, otherwise it will try to get and set `undefined`"

**Comment by comfortme** [comment]
you are right.
if that helps ok i'll reopen

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this.
