### ISSUE TITLE
I can't add platform android

### ISSUE THREAD

**Issue by weitaoyang** [ionic-team/ionic#12099]
command：ionic cordova platform add android
result：
> cordova platform add android --save
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova platform add android --save
        (exit code 1):

        Using cordova-fetch for cordova-android@~6.2.2
        Error: Failed to fetch platform cordova-android@~6.2.2
        Probably this is either a connection problem, or platform spec is
        incorrect.
        Check your connection and platform name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! Maximum call stack size exceeded

        npm ERR! A complete log of this run can be found in:
        npm ERR!
        C:\Users\Administrator.PC-201605231631\AppData\Roaming\npm-cache\_logs\2
017-06-20T06_04_34_674Z-debug.log

dev environment：
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v8.1.1
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3

**Comment by weitaoyang** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'cordova-android@~6.2.2',
1 verbose cli   '--save' ]
2 info using npm@5.0.3
3 info using node@v8.1.1
4 verbose npm-session 9f9b7805f48d3075
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/cordova-android 31ms (from cache)
8 silly pacote range manifest for cordova-android@~6.2.2 fetched in 93ms
9 verbose stack RangeError: Maximum call stack size exceeded
9 verbose stack     at exports.create (D:\Program Files\nodejs\node_modules\npm\lib\install\node.js:33:25)
9 verbose stack     at D:\Program Files\nodejs\node_modules\npm\lib\install\node.js:36:14
9 verbose stack     at Array.forEach (native)
9 verbose stack     at exports.create (D:\Program Files\nodejs\node_modules\npm\lib\install\node.js:33:25)
9 verbose stack     at D:\Program Files\nodejs\node_modules\npm\lib\install\node.js:36:14
9 verbose stack     at Array.forEach (native)
9 verbose stack     at exports.create (D:\Program Files\nodejs\node_modules\npm\lib\install\node.js:33:25)
9 verbose stack     at normalizeTree (D:\Program Files\nodejs\node_modules\npm\lib\install.js:377:5)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (D:\Program Files\nodejs\node_modules\npm\lib\install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (D:\Program Files\nodejs\node_modules\npm\lib\install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (D:\Program Files\nodejs\node_modules\npm\lib\install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (D:\Program Files\nodejs\node_modules\npm\lib\install.js:379:19)
10 verbose cwd E:\work\sysj2\node_modules
11 verbose Windows_NT 6.1.7601
12 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cordova-android@~6.2.2" "--save"
13 verbose node v8.1.1
14 verbose npm  v5.0.3
15 error Maximum call stack size exceeded
16 verbose exit [ 1, true ]

**Comment by rapropos** [comment]
I do not believe npm 5 on Windows is compatible with the current version of app-scripts.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by mtayyip** [comment]
Hı 
have you solved the problem?

**Comment by ourarash** [comment]
I have the same problem on ios. Did you find any solutions?
