### ISSUE TITLE
3.4.0 Memory caching issues

### ISSUE THREAD

**Issue by SKempin** [ionic-team/ionic#12094]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
There appears to be caching issues with 3.4.0. Items saved in local storage do not render on page load, but do so on a hard refresh of the app. I have downgraded to 3.3.0 and this issue is not present.

**Expected behavior:**
The expected saved items would display. They are present in the console log, but the items are not being rendered.

**Steps to reproduce:**
1. Utilise local storage and save an item to it _(Note that other users have also experienced caching issues which do not involve local storage)_.
2. Navigate to a page that retrieves the saved items. The item is not rendered, but _will be_ listed in the console.
3. Refresh the app. The item will appear on the page, as originally expected.

**Related code:**

**Other information:**

```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.11.0
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

```

**Comment by tryadelion** [comment]
+1, happens the same to me.  http://graphs.lleugersdecatalunya.com/  shows the same issues under 3.4 or superior

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/cpeRJs?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by SKempin** [comment]
@jgw96 I'm unable to do that but would happily share my private repo with you, if that is suitable?

**Comment by jgw96** [comment]
Hey @SKempin , no need to share the full repo, we just need a minimal example to make this easier to debug.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
