### ISSUE TITLE
feat: menutype split (if open the menu, content will shrink)

### ISSUE THREAD

**Issue by mnewmedia** [ionic-team/ionic#12091]
**Ionic version:**
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
Currently there are 3 Menu-Types:
- reveal
- push
- overlay

**Expected behavior:**
I also would like to have the Menu-Type:
- split (named from split-pane)

**Reasons for the feature requests**
- With the `split pane`, I cannot specify to which side-menu it applies and since I have a `right` and a `left`-menu they will both be showed.
- With the `split pane`, I cannot open or toggle the menu, only do hacky stuff with the `when-input`

**Comment by AmitMY** [comment]
Please let me know if I got your right - 
You want something like - https://angular.io/docs where when you press the menu icon, it slides in and pushes the main content, while shrinking it's width?

**Comment by mnewmedia** [comment]
@AmitMY exactly what i want =)

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#256
