### ISSUE TITLE
ion-slides: click event not firing for the first slide

### ISSUE THREAD

**Issue by shawnlan** [ionic-team/ionic#12098]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

ion-slides with the following setup:

`<ion-slides pager [autoplay]="2000" [loop]="true">
    <ion-slide tappable (click)="handleClick()">
    </ion-slide>
  </ion-slides>`

Let it loop once. After that, try to click the first slide. The event handler won't execute. Once you stop the autoplay but swiping it manually, clicking the first slide works. The issue is only with the first slide, after the first loop.

Tested with Ionic 3.4.2 on Android and iOS.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/cpeRJs?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by shawnlan** [comment]
Here you go: http://plnkr.co/edit/V1zzIpzXHwuemkXBUz7W?p=preview

Notice that after the first auto loop of all three slides, clicking the first slide has no effect.

**Comment by polcham** [comment]
Also encountered this problem that the first and last slides doesn't trigger (click) events usually happens when I go from last and loop back to the first and vise versa. I also notice that the activeIndex() is increased by 1.

**Comment by Sneko** [comment]
@jgw96 Does Ionic Team plan to take a look at this issue soon? Thanks :)

Related to #9690 #10890

**Comment by Creawebs** [comment]
Also have the same issue on the first slide when populating slides dynamically. Click events wont work. Using latest ionic version.

**Comment by petemcwilliams** [comment]
Had same issue with loopedSlides where the click handler did not fire across the boundary.

**Comment by romanovma** [comment]
I end up with event delegation solution too:
```
clickHandler() {
    let index = this.slides.getActiveIndex(); // caution: starts from 1
   // do something
  }
```

though would be nice to have this issue fixed.
