### ISSUE TITLE
Issues in ionic(Windows platform) app with screen-reader ON

### ISSUE THREAD

**Issue by abhaymlv** [ionic-team/ionic#12107]
Ionic version: **2.2.3**

**I'm submitting a bug report** 

bug type- **Accessibility**
While implementing the accessibility standard in our windows ionic app(device used- Surface pro) I found out following issues,

1.
**Current behavior:**
Function is triggered twice on ng-click event when NVDA/JAWS(Screen-reader) is on

**Expected behavior:**
Function should triggered only once on ng-click event

**Steps to reproduce:**
device- Surface pro
html code- button with ng-click event
steps- select the element and double tap to trigger ng-click 

2.
**Current behavior:**
Reading anchor tag  twice on swipe action(To make NVDA/JAWS screen-reader read the <a> tag aria-label attribute was added)

**Expected behavior:**
On Right swipe anchor tag should not be read by screenreader twice

**Steps to reproduce:**
device- Surface pro
html code-anchor tag with aria-label 
steps- right swipe through the page, when focus comes to anchor tag it will read aria-label first and on right swipe reads the text inside the anchor tag as well

3.
**Current behavior:**
Tapping on blank area of app will read “Page title pane”

**Expected behavior:**
Function should triggered only once on ng-click event

**Steps to reproduce:**
device- Surface pro
steps- tap anywhere on ionic app screen it will read “Page title pane”

4.
**Current behavior:**
First time tap will read the element but if you tap Second time it will not read

**Expected behavior:**
screen-reader should read every time when user tap on element 
**Steps to reproduce:**
device- Surface pro
steps- tap on any element on ionic app screen

**Comment by AmitMY** [comment]
Can you try updating to 3.4.2? 

First, update to `3.0.0` which you can see steps for [here](https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#300-2017-04-05)
After that works, and your app boots correctly, update to `3.4.2` with steps [here](https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#340-2017-06-15)

**Comment by abhaymlv** [comment]
Let me try the version you have specified, I will let you know in the comments.

**Comment by abhaymlv** [comment]
Our company's project was build on ionic 1 and due to business reasons we can not upgrade it to ionic 3.0.0.
Can you please suggest some alternative solution with which we can solve the above issues?

Thanks

**Comment by janpio** [comment]
Then the "Ionic version" you mentioned was the Ionic CLI you ae using.

For your actual question, there is a repo for Ionic v1 here: https://github.com/ionic-team/ionic-v1
But as this is more of a question, you might want to try the community forum as well: https://forum.ionicframework.com/

**Comment by abhaymlv** [comment]
Apologies, by mistake we have uploaded the wrong version earlier.
Here is the correct version,

Your system information:
Cordova CLI: 7.0.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 1.5.0
Ionic App Lib Version: 0.1.0
OS: null
Node Version: v6.11.0
--

Thanks

**Comment by janpio** [comment]
Definitely v1 project, so you are in the wrong repo.

**Comment by abhaymlv** [comment]
ok so I am adding this issue in v1 project, hence closing this issue!

**Comment by janpio** [comment]
Also post at the forum, users that may have met this problem are more probably to hang out there.
