### ISSUE TITLE
Is there any a output event to handle the scenario when datetime selection is selected in DateTime Component ?

### ISSUE THREAD

**Issue by Sunny-Kid** [ionic-team/ionic#12105]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I need a new Output Events to handle the event when the datetime selection was selected and click OK.
**Expected behavior:**

A output event function to handle this scenario
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by AmitMY** [comment]
This needs to be documented.. so don't close this issue.

The datetime extends the base input, and as such, it has 3 more outputs that are hidden from the doc
`ionFocus`, `ionChange`, `ionBlur`

You are looking for `ionChange`

**Comment by jgw96** [comment]
Hello all. @AmitMY , we have a tracking issue for this [here](https://github.com/ionic-team/ionic-site/issues/1074), so I am going to close this as a duplicate. Thanks for using Ionic everyone!
