### ISSUE TITLE
I can't  add platform in ionic 3 getting these lines

### ISSUE THREAD

**Issue by abmnukmr** [ionic-team/ionic#12100]
Apples-MacBook-Pro:ionicc1 apple$ ionic cordova platform add ios
> cordova platform add ios --save
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.
        
[ERROR] An error occurred while running cordova platform add ios --save (exit
        code 1):
        
        Using cordova-fetch for cordova-ios@~4.4.0
        Adding ios project...
        Creating Cordova project for the iOS platform:
        Path: ../../../../documents/projects/ionic_vaioti/ionicc1/platforms/ios
        Package: com.vaioti
        Name: VAIOTI
        iOS project created with cordova-ios@4.4.0
        Error: Source path does not exist:
        resources\android\icon\drawable-xhdpi-icon.png

**#ionic info**
Apples-MacBook-Pro:ionicc1 apple$ ionic info

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.4
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2 ios 4.4.0
    Ionic Framework                 : ionic-angular 2.0.0-rc.5-201701232249

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

**Comment by AmitMY** [comment]
Reading your error gives it away. your `config.xml` file has a path to an icon, that does not exist in your `resources` folder. `ionic resources` to generate resources

**Comment by janpio** [comment]
( `ionic cordova resources` with CLI 3.x)

**Comment by jgw96** [comment]
Thanks @janpio and @AmitMY for handling this (:

**Comment by abmnukmr** [comment]
@AmitMY its not working. and this icon is already in resource folder

**Comment by AmitMY** [comment]
@abmnukmr It can also be the `\` needs to be reversed to `/` (find and replace)
or that now it cached something, so `cordova platform rm ios` & `cordova platform add ios`
If the error is different, comment with the updated error

**Comment by abmnukmr** [comment]
kk

**Comment by abmnukmr** [comment]
@AmitMY not working same error while changing  \ to / in  config.xml.

**Comment by janpio** [comment]
Open a topic at https://forum.ionicframework.com/ please, much easier to debug the problem there.
