### ISSUE TITLE
chat app problems

### ISSUE THREAD

**Issue by Sherlock0001** [ionic-team/ionic#12109]
Hello ionic communitiy!
I try endlessly to make a chat app like the one in the ionic tutorial but it never connect to firebase.
Can someone help me?
Thank u

**Comment by mnewmedia** [comment]
Issues more like for features and bugs of the framework.
You should close the issue and start a thread in https://forum.ionicframework.com/.

Have a good day 🌻 .

**Comment by alexbainbridge** [comment]
There is a firebase chat app starter https://github.com/sdey0081/ionic-messenger-starter

**Comment by brandyscarney** [comment]
Thanks for the issue! Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If you believe this is an issue with the framework, please create a new issue with answers to the pre-populated questions. Thanks!

**Comment by Sherlock0001** [comment]
Thank u i have sorted the problem off!
U're amazing guys

2017-06-21 17:19 GMT+02:00 Brandy Carney <notifications@github.com>:
