### ISSUE TITLE
Show plain text, links and images in toast

### ISSUE THREAD

**Issue by cesareian** [ionic-team/ionic#12106]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x] **2.x**
[x] **3.x**

Currently, we are using version 2.2.3

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently, toast shows only plain text even if you pass an URL or image link

**Expected behavior:**
Toast should show plain text, links and images properly

**Related code:**

```
template:
    '<div class="toast-wrapper" ' +
      '[class.toast-bottom]="d.position === \'bottom\'" ' +
      '[class.toast-middle]="d.position === \'middle\'" ' +
      '[class.toast-top]="d.position === \'top\'"> ' +
      '<div class="toast-container"> ' +
        '<div class="toast-message" id="{{hdrId}}" *ngIf="d.message">{{d.message}}</div> ' +
        '<button ion-button clear class="toast-button" *ngIf="d.showCloseButton" (click)="cbClick()"> ' +
          '{{ d.closeButtonText || \'Close\' }} ' +
         '</button> ' +
      '</div> ' +
    '</div>',
```

**Other information:**
Instead of using string interpolation, `[innerHTML]` should be used so that the consumer can show whatever text s/he wants being plain text, links to other pages or images

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#259

**Comment by cesareian** [comment]
Hi, I have created a PR for this issue https://github.com/ionic-team/ionic/pull/12108. Will it be looked into or it needs to be prioritize first?

**Comment by jgw96** [comment]
Thanks @cesareian , while we still need to prioritize this feature I am reopening this issue since you have opened a PR for it. Thanks a ton for implementing this, we will evaluate your PR once we make it down our queue to this issue. 🎉

**Comment by leonardopaiva** [comment]
hello, i`m interested on this update,

- i would like to set title and text on my toast, 
- Style both appropriately. 
- Should be interesting to have a title param, like alert hast, 
- And the possibility to add html tags to title and message of toast options with class attribute.

thanks

**Comment by Spaldin** [comment]
I have a problem with this issue. If I run in browser image is working but if I build for android with --prod image and html code disappears and replaces it with original code I wrote, just plain text.
