### ISSUE TITLE
bug: Java Heap out of mem: Fatal Error on `ionic serve`

### ISSUE THREAD

**Issue by itsru** [ionic-team/ionic#12114]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>When running 'ionic serve -c' I get 

[03:19:09]  transpile started ... 

<--- Last few GCs --->

  291753 ms: Mark-sweep 1317.9 (1432.4) -> 1312.3 (1432.4) MB, 385.9 / 0.0 ms [allocation failure] [GC in old space requested].
  292172 ms: Mark-sweep 1312.3 (1432.4) -> 1312.3 (1432.4) MB, 418.9 / 0.0 ms [allocation failure] [GC in old space requested].
  292621 ms: Mark-sweep 1312.3 (1432.4) -> 1312.3 (1401.4) MB, 449.3 / 0.0 ms [last resort gc].
  293046 ms: Mark-sweep 1312.3 (1401.4) -> 1312.3 (1401.4) MB, 425.2 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3158a58cfb39 <JS Object>
    1: [Symbol.replace] [native regexp.js:~540] [pc=0x14a1867d8c7c] (this=0x3ba250987f09 <JS RegExp>,D=0x2a08a33ed069 <Very long string[1854239]>,aw=0x3158a58ec999 <String[1]\: \n>)
    2: 0x3158a588aaf1 <Symbol: 20329980 <String[14]: Symbol.replace>>(aka [Symbol.replace]) [native regexp.js:~659] [pc=0x14a186675f2b] (this=0x3ba250987f09 <JS RegExp>,D=0x2a08a33ed069 <Very long string[1854239]>,a...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::Runtime_StringReplaceGlobalRegExpWithString(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x14a1844092a7
 8: 0x14a1867d8c7c
 9: 0x14a186675f2b
Abort trap: 6

----------------------------------
global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    npm        : 3.10.10</span>

<span is-issue-template></span>

**Comment by AmitMY** [comment]
I would suggest moving this to `ionic-app-scripts`, as it is more related to that repo

**Comment by itsru** [comment]
thanks closing
