### ISSUE TITLE
Ionic2 app reloads automatically every 10 seconds

### ISSUE THREAD

**Issue by mobinius-shreesha** [ionic-team/ionic#12110]
Hello,
       i am facing serious issue on ionic2 app which is running on iphone5.page is gettting reload every 10 seconds without any action.its reloading continuesly.please help me out with solution.

**Comment by mnewmedia** [comment]
Try:
- test in a browser with all addons disabled
- test in a different editor

In the issue template is this text which you shouldn't have deleted:
```
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```

**Comment by mobinius-shreesha** [comment]
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.4.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.6.1

**Comment by mobinius-shreesha** [comment]
But this problems not occuring in browser.its happening in iphone 5 phone device

**Comment by mnewmedia** [comment]
How did you run the app on you iphone?

**Comment by rapropos** [comment]
This seems like a better fit for [the support forums](https://forum.ionicframework.com/).

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
