### ISSUE TITLE
How do I move the segment around??

### ISSUE THREAD

**Issue by liershijiu** [ionic-team/ionic#12118]
<ion-header>
  <ion-navbar no-border-bottom>
    <ion-title>
      Segments
    </ion-title>
  </ion-navbar>

  <ion-toolbar no-border-top>
    <ion-segment [(ngModel)]="segmentModel">
      <ion-segment-button value="segmentOne">
        segmentOne
      </ion-segment-button>
      <ion-segment-button value="segmentTwo">
        segmentTwo
      </ion-segment-button>
      <ion-segment-button value="segmentThree">
        segmentThree
      </ion-segment-button>
    </ion-segment>
  </ion-toolbar>
</ion-header>

<ion-content (swipe)="swipeEvent($event)">
  <div [ngSwitch]="segmentModel">
    <ion-list *ngSwitchCase="'segmentOne'">
      <ion-item>
        <ion-thumbnail item-left>
          <img src="assets/icon/favicon.ico">
        </ion-thumbnail>
        <h2>segmentOne</h2>
      </ion-item>
    </ion-list>

    <ion-list *ngSwitchCase="'segmentTwo'">
      <ion-item>
        <ion-thumbnail item-left>
          <img src="assets/icon/favicon.ico">
        </ion-thumbnail>
        <h2>segmentTwo</h2>
      </ion-item>
    </ion-list>

    <ion-list *ngSwitchCase="'segmentThree'">
      <ion-item>
        <ion-thumbnail item-left>
          <img src="assets/icon/favicon.ico">
        </ion-thumbnail>
        <h2>segmentThree</h2>
      </ion-item>
    </ion-list>
  </div>
</ion-content>

I want this segment to slide,But you can't use swipe inside。

**Comment by AmitMY** [comment]
- Please fill the issue template, otherwise it will be difficult to help you. 
- Also, the image you attached is broken, please just paste it in github and it will be uploaded to their servers.

I do not understand your goal here, is [this](https://github.com/zyra/ionic2-super-tabs) what you want?

**Comment by liershijiu** [comment]
@AmitMY Thank you!!

**Comment by jgw96** [comment]
Hello all! Going to close this issue as it seems like @AmitMY 's link was what @liershijiu was looking for.
