### ISSUE TITLE
how to app keep running on background using ionic2

### ISSUE THREAD

**Issue by anivaisu** [ionic-team/ionic#12117]
I am using ionic 2.

I need app is run on background mode.

Actually i used this plugin

  ionic cordova plugin add cordova-plugin-background-mode

  npm install --save @ionic-native/background-mode

  this.backgroundMode.enable();
But its not work.

I need app is run on background mode when app is killed.

I have no idea.

Kindly Advise me,

Thanks

**Comment by mnewmedia** [comment]
Ionic issues are for bugs or feature requests regarding ionic. Sadly Your question is not one of those, so please close the issue and ask it on better fitting place like:

https://github.com/katzer/cordova-plugin-background-mode
https://forum.ionicframework.com/

**Comment by anivaisu** [comment]
No body response in use forum

**Comment by mnewmedia** [comment]
There are also other places than the forum.

- stackoverflow.com
- https://github.com/katzer/cordova-plugin-background-mode
- https://github.com/ionic-team/ionic-native

Maybe you should provide more information to get an answer in the forum..

- Like exact system and setup that you use (ionic info)
- code example (more than `this.backgroundMode.enable();`)
- to best would even be to make a github repo where others can reproduce your issue

But no body will response here either if it's not an ionic issue. Most likely a ionic team member will come here and close the issue. But you could help the ionic team with not spamming their bug-list with other questions...

**Comment by janpio** [comment]
> No body response in use forum

Really? Provide a link to the topic please.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic! Also, if you have already posted there feel free to provide the link to the topic here as @janpio suggested (:
