### ISSUE TITLE
"Error: Error encountered resolving symbol values statically." when console.log called from a forRoot static method.

### ISSUE THREAD

**Issue by Yermo** [ionic-team/ionic#12113]
I am not sure if this is an error in my understanding, an ionic error, an angular error, or a typescript error.

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

$ ionic cordova build android --prod 
generates the following error:

```
Error: Error encountered resolving symbol values statically. Calling function 'TestModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule
```

**Expected behavior:**

I expected the app to build.

**Steps to reproduce:**

ionic start TestBuild tabs

Create directory src/modules.
Create a module, TestModule in src/modules/test.module.ts with contents:

```
import { 
  NgModule, 
  ModuleWithProviders
} from '@angular/core';

export interface ITestConfig {
  value: string;
}

export class TestConfig implements ITestConfig {
  value: string;
}

@NgModule({

  declarations: [
  ],

  imports: [
  ],

  entryComponents: [
  ],

  providers: [
  ],

  exports: [
  ]

})

export class TestModule {

  // -----------------------------------------------------------------------------

  /** 
  * test set configuration
  */

  static forRoot( config: ITestConfig ): ModuleWithProviders {

    console.log( "This is a test" );

    return {
      ngModule: TestModule,
      providers: [

        { provide: TestConfig, useValue: config }

      ]
    };
  }

} // end of TestModule

```
Include module test module in src/app/app.module.ts

```
import { TestModule, TestConfig } from '../modules/test.module';

let config: TestConfig = { 
  value: 'test'
} 

....

  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    TestModule.forRoot( config )
  ], 
```

Run the build and notice the error.

Now remove the "console.log()" call and re-run the build.

Note that it builds.

Why would a call to console.log there cause the build to fail with this error?

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.4.0 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.0.0
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v7.10.0
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.2.0 

```

**Comment by AmitMY** [comment]
Thanks for the very detailed information. From looking at your code, I don't see anything specifically relevant to ionic, and I suspect it is an angular issue (when compiling with AoT).

**Comment by jgw96** [comment]
Hello everyone! I agree with @AmitMY here that this looks more like an Angular issue than an Ionic specific issue. The code all looks correct to me. I will say that I don't think it is common to call `console.log()` in a ngModule declaration, but I would think it should work. I would recommend you open an issue [here](https://github.com/angular/angular/issues) on the angular repo. Also, since this seems to be an Angular issue and not an Ionic specific issue I am going to close this issue for now.

**Comment by Yermo** [comment]
Thank you for the prompt reply. Submitted here: https://github.com/angular/angular/issues/17663
