### ISSUE TITLE
ionic build android --prod very slow

### ISSUE THREAD

**Issue by huangzk** [ionic-team/ionic#12122]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When I run "ionic build android --prod" in the windows,the time it cost is very large.

**Expected behavior:**

In the MAC,it cost about 40 minutes..why?
What difference with them..

**Comment by huangzk** [comment]
![default](https://user-images.githubusercontent.com/25288972/27380181-bec27d16-56b0-11e7-906e-53cdc5c2c1b4.png)

**Comment by AmitMY** [comment]
Building with `--prod` uses the AoT compiler, otherwise it uses the JiT compiler.
You can see that building for production has a much smaller bundle size, and is much faster on devices.
We would all love it to be faster, but it is a core angular thing, and not ionic's.

Read more - https://angular.io/guide/aot-compiler

**Comment by huangzk** [comment]
And In the window ,to build android apk,use more than 2 hoIurs...  It's normal ?
of course,our project is  a little big..

**Comment by jgw96** [comment]
@huangzk , exactly how big is your project? How many pages does your app have? @AmitMY is correct that most of the time here is going to be spent in AOT. AOT compiling is a very complicated, cpu intensive process. Also, from my experience build times with AOT drastically increase based on the amount of code you have. 40 minutes definitely sounds odd, but if your app is really huge, that time would not completely surprise me.

**Comment by AmitMY** [comment]
@jgw96 If I compile all of the e2e tests for ionic as one project (a lot of pages), it takes about 15 minutes. (in production mode). so 40 only makes sense for 500 pages+ (`gulp e2e.prod --f=snapshot/basic`)

**Comment by aggarwalankush** [comment]
I also raised the similar issue in ionic-app-scripts https://github.com/ionic-team/ionic-app-scripts/issues/920 @danbucholtz mentioned it's slow for prod builds because of AOT. But for me, it takes few minutes for prod and less than a minute for non-prod. @huangzk you mentioned, your app took more than 2 hours to build, it's too much. Did you left it overnight to build 😄 

Maybe try following as mentioned by dan in above issue
```
"config": {
    "ionic_build_to_es5": false
  }
```

**Comment by huangzk** [comment]
@jgw96  Our page is contain large lots of model and page, the number about 100 pages,now...last time we built  1.0 project costs 40 minutes,  and now ,with pages increasing, it comes to 2 hours....

**Comment by huangzk** [comment]
above-mentioned is in the windows ,,,in the mac  ,last time we built 1.0 project costs 10 minutes, and now ,with pages increasing, it comes to 40 minutes..

**Comment by jgw96** [comment]
Hey @huangzk , thanks for the info. Are you all doing code splitting? Also, can you try @aggarwalankush 's suggestion and see if that helps?

**Comment by huangzk** [comment]
@jgw96 yes,we defined  some module to let project more clear and  develop more fast,as the picture
![default](https://user-images.githubusercontent.com/25288972/27470263-b78fb934-5825-11e7-95a2-83b1d6783901.png)
the way can affect the compile? I don't know..I will try @aggarwalankush 's suggestion..

**Comment by huangzk** [comment]
@jgw96  the time ccost....
![lks 75phv 7mgn v o z o](https://user-images.githubusercontent.com/25288972/27485355-fdfe6422-585e-11e7-8b54-a356889abf9b.jpg
![default](https://user-images.githubusercontent.com/25288972/27485365-07a13626-585f-11e7-9dbf-fc0316cd79fa.png)   the time cost

**Comment by jgw96** [comment]
Hello @huangzk , would you be able to post your `ionic info` please?

**Comment by jgw96** [comment]
Hello, all! At this point, this issue seems to be more of an app-scripts issue than an actual framework issue. Because of this, I am going to move this issue to the app-scripts repo and we can continue the conversation there.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1054
