### ISSUE TITLE
Ionic2 SVG image zoom

### ISSUE THREAD

**Issue by mobinius-shreesha** [ionic-team/ionic#12121]
Hello team,
            which plugin suppose to use for svg image zooming.need pinch zoom.please help me.
Thanks

**Comment by mobinius-shreesha** [comment]
Please reply me team

**Comment by AmitMY** [comment]
This is a support request. Please ask in the forum,
I will give you one lead though, you can use any pinch to zoom angular directive, not related to ionic. (so even the forum might not be the right place)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
