### ISSUE TITLE
Ionic 2 Aws file upload.

### ISSUE THREAD

**Issue by rameshmkll** [ionic-team/ionic#12123]
How to upload an image to amazon s3 using ionic 2.

**Comment by AmitMY** [comment]
For support requests, please see the forum.
However, note that you are looking for how to upload an image using angular, not related to ionic.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
