### ISSUE TITLE
Drop-down interface for <ion-select>

### ISSUE THREAD

**Issue by jaufgang** [ionic-team/ionic#12125]
`<ion-select>` is a great component that provides `action-sheet` and `popover` interfaces for item selection on  mobile device.  However, when using ionic in a progressive web app, these interfaces are cumbersome in a desktop browser and users would be better served with a typical html-style drop-down select box.

Since `<ion-select>` already supports multiple interfaces, I would propose adding a 3rd interface called `html-select` or `drop-down` or something similar.  This interface could be styled consistently with the fonts and padding of a typical ionic input but would behave like a regular html select.  

It would be ideal if the component could be configured automatically use the `action-sheet` or `popover` interface on mobile devices and the `drop-down` interface in a desktop or large screen environment.

**Comment by bartcich** [comment]
What's the difference between popover and dropdown? This is ionic popover for ion-select:
![select](https://user-images.githubusercontent.com/3295025/27397543-fb4a0dfc-56b6-11e7-8e8b-474bd7345d3d.PNG)

**Comment by jaufgang** [comment]
Argh....  now I feel dumb.   I had been looking at the `alert` and `action-sheet` interfaces and got mixed up between `alert` and `popover`, which I hadn't closely looked at.   That does look pretty decent, at least in iOS mode (I don't really see the point of the radio buttons in Android mode)  

Thank you for your response... I will close this issue.
