### ISSUE TITLE
ion-tab navigation bar out of sync with page display when using deeplinks on mobile device

### ISSUE THREAD

**Issue by sharonswli** [ionic-team/ionic#12127]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
The tab navigation buttons do not correspond to the page being displayed when the app is opened through a deeplink. Opening the app through regular means (dashboard, xcode, terminal, etc) does not exhibit this behaviour and the tabs are working as expected. 

But when using deeplinks to launch the app, if I open `myapp://host/about` or any other matched routes, the app will be opened to the foreground with the correct selected tab highlighted in the navigation bar(see screenshot below) 
<img src="https://user-images.githubusercontent.com/18632451/27398941-27673578-5670-11e7-906f-d89e80fb5466.PNG" width="300">

However as soon as I click on other tabs using the navigation bar, the highlighted navigation tab does not update to match the displaying tab page (see screenshot: Current selectedTab/displayed page = ContactPage. The navigation bar shows 'AboutPage' is selected instead)
<img src="https://user-images.githubusercontent.com/18632451/27398970-41677dac-5670-11e7-8bcf-a1e14f97b0fd.PNG" width="300">

When it does update, it seems the tab navigation is lagging behind 1 click (see screenshot: Current displayed page = HomePage. The navigation shows 'ContactPage' is selected instead)
<img src="https://user-images.githubusercontent.com/18632451/27399077-7b8f6a9e-5670-11e7-9c1b-b9db5ab1c96a.PNG" width="300">

After two clicks, the navigation tabs stop updating all together, and is stuck on whichever tab that it last updated to.

**Expected behavior:**
The navigation tab bar should highlight the selected tab aka the displayed page. 

**Steps to reproduce:**
1. Clone bug demo repo [here](https://github.com/sharonsw/ionic-tab-deepink).
2. npm install
3. ionic build ios/android --debug (I'm using ionic CLI v. 2.2.3. Use corresponding CLI build command if using a different version of ionic CLI)
4. Open link: `myapp://example.com/about` and launch demo app.
5. Click on navigation buttons to push a different tab to view.

**Related code:**
- Related source code is located on Github: 
1. [app.component.ts](https://github.com/sharonsw/ionic-tab-deepink/blob/master/src/app/app.component.ts)
2. [app.html](https://github.com/sharonsw/ionic-tab-deepink/blob/master/src/app/app.html)
3. [tabs.ts](https://github.com/sharonsw/ionic-tab-deepink/blob/master/src/pages/tabs/tabs.ts)
4. [tabs.html](https://github.com/sharonsw/ionic-tab-deepink/blob/master/src/pages/tabs/tabs.html)

**Ionic info:**:

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.4.2
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.10.2
Xcode version: Xcode 8.3.3 Build version 8E3004b
```

**Comment by AmitMY** [comment]
Thanks for the detailed info! @danbucholtz is working on nav improvements for the next version, and most likely will check this out.

**Comment by jgw96** [comment]
@sharonsw , you can check out the latest nightly which already has some of the improvements that @AmitMY mentions. To install ionic-angular nightly just run `npm install ionic-angular@nightly --save`.

**Comment by sharonsw** [comment]
Some more info about the issue: After comparing the events fired when an ion-tab page is accessed via deeplink vs. accessed via dashboard, it seems like the TabPage is leaving and unloading itself inappropriately before the selected tab is even loaded/entered: 

## Using deeplink `app://host/about`
```
ionViewDidEnter (tabs.ts)
ionViewDidLeave (tabs.ts)
ionViewWillUnload (tabs.ts)
ionViewDidEnter (about.ts) 
```

## Using other navigation (e.g. though signing in)
```
ionViewDidEnter (tabs.ts)
ionViewDidEnter (about.ts)
```

**Comment by sharonsw** [comment]
@jgw96 I have updated ionic-angular to 3.5.0. Still an issue with the Tab Nav icons out of sync so I guess unfortunately the fix did not make it to the new release?

**Comment by auguried** [comment]
Hi, may i ask if this Tab Nav icons out of sync has been resolved? I'm still facing the problem. Thanks in advance for helping!
