### ISSUE TITLE
ionic install throws error  "@ionic/cli-utils@1.4.0"

### ISSUE THREAD

**Issue by sruthakeerthikotla** [ionic-team/ionic#12131]
npm version : 5.0.3
node version : 8.1.2
cordova version : 7.0.1

On trying to execute ionic using the command `npm install -g ionic cordova`, an error is thrown as follows : 
```
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! code E404
npm ERR! 404 Not Found: @ionic/cli-utils@1.4.0
```
I have tried installing with `sudo` as well but same error occurs and ionic does not install at all.

**Comment by janpio** [comment]
Wrong repo, this should be posted at the Ionic CLI one: https://github.com/ionic-team/ionic-cli

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2466
