### ISSUE TITLE
ion-datetime done event  support

### ISSUE THREAD

**Issue by giscafer** [ionic-team/ionic#12138]
**Ionic version:**  (check one with "x")
[ ] **3.3**

the component only a `ionCancel` event , i want to trigger event doing something when click the doneButton，but there is not a `ionDone` event. how can i do?

**Comment by giscafer** [comment]
ionChange???

**Comment by AmitMY** [comment]
First, please for the future fill the issue template.
Second, yes, `ionChange` is the event you are looking for, see https://github.com/ionic-team/ionic/issues/12105
This is a documentation issue: https://github.com/ionic-team/ionic-site/issues/1074

**Comment by giscafer** [comment]
sorry,i will do best next time，thks for answer
