### ISSUE TITLE
Ionc Image Not Working on release mode android

### ISSUE THREAD

**Issue by simoebenhida** [ionic-team/ionic#12137]
Hey When i build my apk file and upload it to my phone i can't see the pictures that i upload from local 
`<img *ngFor="let player of player2; let i = index" width="60" height="100" [id]="'active-'+i" [src]="'../img/'+player.number+'_'+player.type+'.jpg'" (click)="CartClicked($event,i)" alt="{{ player.number }}" />`

**Comment by AmitMY** [comment]
- Please fill the issue template.
- This seems like a support request. For support requests you can use the ionic forum.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
