### ISSUE TITLE
Fab button should shift up when Toast is visible at bottom

### ISSUE THREAD

**Issue by shyamal890** [ionic-team/ionic#12139]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently if both the toast and Fab button at present at the bottom of the screen the Fab button gets covered by the toast. So lets, say a user saved something and wants to add a new item he has to wait for toast to go away.

**Expected behavior:**
Incase toast and fab button both are present at the bottom. Fab button should move up so that user can immediately click on button and move forward.

**Comment by AmitMY** [comment]
- Please fill in your `ionic info` information.

I think you want the toast to push the content when presenting it, however, that is not the native behaviour of iOS nor Android. (it seems like an overlay)

**Comment by davec21** [comment]
I'm with @AmitMY on this. The toast is an overlay not an element (if that makes sense). You could move your toast to drop down from the top, or just raise your fabs up a bit from the bottom.

**Comment by shyamal890** [comment]
Guys you need to have a look at Gmail/Yahoo or any similar apps. Delete an email and you will see Fab button shifting up for the toast. Very logical UX flow.

@AmitMY How will my Ionic Info help here?!!

**Comment by davec21** [comment]
Inbox does definitely shift the fab up.. never noticed before. Guess he has a bit of an argument.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#260

**Comment by AmitMY** [comment]
@shyamal890 I stand corrected.
Your `ionic info` helps everywhere, as when this issue is revisited, we might see that your report is from an old version, or perhaps it will be fixed in 3.5.0 and there will be confusion on this issue's version.

From my experience with issues here, looking at an issue's version makes me understand if it is an old version, or there has been a regression, without comparing release dates.

**Comment by realappie** [comment]
According to the material design [spec](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-usage), the toast should push the fab up. Which is something the toast is not doing right now.

![](https://i.gyazo.com/00e8f83475e329cce7d3dbae36b42233.gif)


My ionic info

```

global packages:

    @ionic/cli-utils : 1.0.0-rc.2-alpha.f5850eb3
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0-rc.2-alpha.f5850eb3

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0-alpha.e838a5d7
    @ionic/cli-plugin-ionic-angular : 1.3.1-alpha.e838a5d7
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.9.5
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by shyamal890** [comment]
I guess this should be the first feature that they should implement in the next release. Hope they do so. If not, @jgw96 can you please share how to implement a tweak/hack for this?

**Comment by AmitMY** [comment]
Actually @shyamal890 I think this should be reopened as a bug report. @jgw96 what do you think?

**Comment by maumchaves** [comment]
I have implemented a temporary solution. It is an Angular / Ionic 3 directive that allows Ionic toasts to animate the fab buttons and other elements in the fixed-content div of a page accordingly.

All you have to do is to include the directive in your project and then add a corresponding element in your app component template:

<ng-container move-fixed-content-with-toast></ng-container>

Please check out the code here:
https://gist.github.com/maumchaves/d7270b54afd5c8ae120f34b41436a119

![toast_fab_demo](https://user-images.githubusercontent.com/2398379/38476936-75a35f40-3b6d-11e8-9dda-119bb35ec8da.gif)
