### ISSUE TITLE
Android Back Button closes ionic 3 Web App

### ISSUE THREAD

**Issue by alaborderie** [ionic-team/ionic#12130]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When switching page with `navCtrl.push(page)` and then using browser or android's back button, browser goes back to last website visited.

**Expected behavior:**

It should go back to the last page visited (e.g. the page before `navCtrl.push(page)` )

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:                                                                             
                                                                                             
    @ionic/cli-utils : 1.3.0                                                                 
    Ionic CLI        : 3.3.0                                                                 
                                                                                             
local packages:                                                                              
                                                                                             
    @ionic/app-scripts              : 1.3.7                                                  
    @ionic/cli-plugin-ionic-angular : 1.3.0                                                  
    Ionic Framework                 : ionic-angular 3.3.0                                    
                                                                                             
System:                                                                                      
                                                                                             
    Node       : v6.10.2                                                                     
    OS         : Linux 4.4                                                                   
    Xcode      : not installed                                                               
    ios-deploy : not installed                                                               
    ios-sim    : not installed                                                               
```

**Comment by AmitMY** [comment]
Back button should definitely have a rework, perhaps a stack so both user and framework can have actions together. I'll look into it.

For now, you can do:
```ts
this.platform.ready().then(() => {
  this.platform.registerBackButtonAction(() => {
    if (this.nav.canGoBack())
      this.nav.pop().then(() => {}, () => {}); // If called very fast in a row, pop will reject because no pages
  }, 500);
});
```

**Comment by jgw96** [comment]
Hello all! So back button support for PWA's is actually enabled by our deeplinker. [Here](https://github.com/ionic-team/ionic-conference-app/tree/lazy-load) is an example of the conference app using our `@IonicPage()` decorator that enables linking between pages. We have not pushed this hard yet as it has some issues that need polishing out, but the good news is that we are actually working on those fixes now. The latest nightly of `ionic-angular` includes some of these fixes and we have even more coming very soon. You can see this in action [here](https://ionic-team.github.io/ionic-conference-app/www). Thanks for using Ionic!
