### ISSUE TITLE
Canvas is not defined

### ISSUE THREAD

**Issue by Madhivarman** [ionic-team/ionic#12149]
I am trying to integrate CamanJs with the application but when i tried to run the error it shows canvas is not defined 

i installed canvas using  

>npm install canvas

i included 'canvas' in externals in webpack.config.js still there is a error

`externals : [
     'canvas'
],`

error it shows

> @http://localhost:8100/build/main.js:115815:1
__webpack_require__@http://localhost:8100/build/main.js:20:12
@http://localhost:8100/build/main.js:74369:14
@http://localhost:8100/build/main.js:74198:1
__webpack_require__@http://localhost:8100/build/main.js:20:12
@http://localhost:8100/build/main.js:74163:64
__webpack_require__@http://localhost:8100/build/main.js:20:12
@http://localhost:8100/build/main.js:115776:75
__webpack_require__@http://localhost:8100/build/main.js:20:12
@http://localhost:8100/build/main.js:105867:73
__webpack_require__@http://localhost:8100/build/main.js:20:12
@http://localhost:8100/build/main.js:78067:70
__webpack_require__@http://localhost:8100/build/main.js:20:12
@http://localhost:8100/build/main.js:63:18
@http://localhost:8100/build/main.js:1:1

my Ionic Information

> global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v8.0.0
    OS         : Linux 4.6
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3 

AnySolution for this..ThankYou..

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
