### ISSUE TITLE
Unable to build for Android with Ionic online packager

### ISSUE THREAD

**Issue by xims** [ionic-team/ionic#12148]
I'm using the online builder to build Ionic apps.

It worked before but in the last 2 days when I'm building Android apps, I keep getting the error below.
Tried to build both - dev and prod versions, with same results.
iOS apps are building ok.

Thanks

ANDROID_HOME=/opt/android-sdk
JAVA_HOME=/usr/lib/jvm/java-8-oracle
Error: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
Looked here: /opt/android-sdk/tools/templates/gradle/wrapper

**Comment by Madhivarman** [comment]
install gradle in their official website [Gradle-4.0](https://gradle.org/) and write the below command in the ***bash_profile*** file

> export   Path=$Path /opt/gradle/gradle-4.0/bin

and after save the file by the
>  ~/.source bash_profile.sh

and try to run the application 
> ionic cordova run android -l

i've cleared this error by this way..Make sure that your gradle file path is correct..
Thanks..

**Comment by xims** [comment]
Thanks, @Madhivarman but I'm using an online Ionic package builder at https://apps.ionic.io/.
I don't have access to the build environment.
Unless there is something new that needs to be specified in config.xml that wasn't needed previously.

**Comment by jgw96** [comment]
Hello @xims , thanks for opening an issue with us. This is happening because you are running an older version of the cordova android platform locally than we are running in the cloud. To update your local version you can run `cordova platform update android --save`. Thanks for using Ionic!

**Comment by xims** [comment]
Hi @jgw96, thanks for the reply.
Unfortunately, it didn't help.

I don't even have platforms installed locally, I'm using the cloud to package.
I did updated cordova (`npm install -g cordova`) to update from 6.5.0 to 7.0.1
I have Ionic 3.4.0 installed.

I tried building and still getting the same error
```
ANDROID_HOME=/opt/android-sdk
JAVA_HOME=/usr/lib/jvm/java-8-oracle
Error: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
Looked here: /opt/android-sdk/tools/templates/gradle/wrapper

```

If that helps, my app id is fab1796b

Thanks

**Comment by xims** [comment]
I found solution, what I actually needed is to add
`    <engine name="android" spec="latest" />`
to config.xml

**Comment by dqblanco** [comment]
@xims Thank you for the solution.

**Comment by azeemahmad0** [comment]
@xims Thank you man for the solution.
