### ISSUE TITLE
Attributes missing from most API component documentation pages

### ISSUE THREAD

**Issue by nikmartin** [ionic-team/ionic#12145]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Pages like: http://ionicframework.com/docs/api/components/toolbar/Header/ have no documentation about the attributes/directives that can be added to components to control their behaviour. For instance, the linked page has no documentation for the no-border attribute. The ion-content page has no documentation for the padding attribute.

**Expected behavior:**
All attributes of each component should  be documented
**Steps to reproduce:**
Navigate to http://ionicframework.com/docs/api/components/toolbar/Header/ and attempt to read about the no-border atribute

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-site#1167
