### ISSUE TITLE
GUI not refreshing until end of click event

### ISSUE THREAD

**Issue by Kaaarlsson93** [ionic-team/ionic#12142]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x** (3.4.0)

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have a Login Button with a click event that calls a AWS Cognito function to perform authentication. 

 ```
 doLogin() {
    this.isLoading = true;
    this.userLoginService.authenticate(this.username, this.password, this);
  }
```
And two buttons in my template that should be displayed depending on the isLoading variable:

```
<button *ngIf="!isLoading" ion-button block (click)="doLogin()">Log in</button>
<button *ngIf="isLoading" ion-button block (click)="doLogin()">Logging in..</button>
```

When the button is clicked, the entire doLogin() method is run and the GUI updates to the second button then the doLogin() method has completed.

**Expected behavior:**
The button should swap to the other one as soon as the isLoading variable is set to true in the beginning of the doLogin() method.

**Comment by AmitMY** [comment]
- Please fill in the `ionic info` in your question

What is your change detection strategy?

**Comment by mhartington** [comment]
@Kaaarlsson93  Im unable to replicate this issue using the latest version of the framework.

http://plnkr.co/edit/RmPSNT?p=preview

Please provide a demo (plunkr, github repo) that reproduces the error you are seeing.

**Comment by Kaaarlsson93** [comment]
Thank you for the provided demo @mhartington. 

I made some further research in to this problem and it seems like it's not a fault with the Ionic framework.

The login button makes a call to the AWS-cognito javascript sdk that makes some heavy calculations when performing authentication of the user. I think that the heavy authentication calculations togeather with running a node server on a not to powerful laptop causes the issue with the animations not running until the authentication calculations has completed.

The performance improved drastically when uploading the code on a server.
