### ISSUE TITLE
RTL animated Searchbar causes visual glitches.

### ISSUE THREAD

**Issue by shalaby** [ionic-team/ionic#12141]
**Ionic version:**  (check one with "x")
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report

**Current behavior:**
searchbar animation in rtl mode causes visual glitches.

**Expected behavior:**
work as intended.

**Steps to reproduce:**
![searchbar animation](https://user-images.githubusercontent.com/149119/27472680-f7be9fe6-5804-11e7-92ce-0bde6a94d640.gif)
**Related code:**

```
<ion-searchbar
            [(ngModel)]="term"
            name='term'
            [showCancelButton]="true"
            [cancelButtonText]="cancelButtonText"
            [placeholder]="'بحث'"
            [animated]="true"
            (ionClear)="clear()">
    </ion-searchbar>
```

**Other information:**
```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.8
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.1.1
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v8.1.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : not installed
    ios-sim    : 5.0.13 
    npm        : 5.0.3
```

**Comment by AmitMY** [comment]
It is something related to the desktop scrollbar.. I haven't seen it on device, so it is less critical. Nonetheless, let's try to fix it on desktop as well.
