### ISSUE TITLE
HTML5 video - problem when more than 16 videos

### ISSUE THREAD

**Issue by theomic** [ionic-team/ionic#12144]
**Ionic version:**  (check one with "x")
[x] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have multiple videos in my app.
When I play more than 16 videos, Ionic stops playing the videos.

**Expected behavior:**
Videos should work even with more than 16 plays.

**Steps to reproduce:**

**Related code:**

**Other information:**
For information I have dozens of videos packaged in my app and everithung is workng well until the 16th video is played.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-v1#271
