### ISSUE TITLE
ionic range the bullet is not moving

### ISSUE THREAD

**Issue by mehr30na** [ionic-team/ionic#12151]
Please kindly help me my `<ion-range></ion-range>` is not moving. I could see the value but the bullet does not move graphically. 
It was working well till yesterday and started not to move today.

**Comment by AmitMY** [comment]
- Please fill the issue template.

If you are on RTL, this is a bug, if you are on LTR, please supply reproduction plunker

**Comment by mehr30na** [comment]
Yeah Thanks I am using RTL.
