### ISSUE TITLE
compareWith not working...

### ISSUE THREAD

**Issue by Sid21m** [ionic-team/ionic#12155]
Getting this error message
`polyfills.js:3 Unhandled Promise rejection: Template parse errors:
Can't bind to 'compareWith' since it isn't a known property of 'ion-select'.
1. If 'ion-select' is an Angular component and it has 'compareWith' input, then verify that it is part of this module.
2. If 'ion-select' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.`

Here are my dependencies :
` "dependencies": {
    "@angular/common": "4.1.2",
    "@angular/compiler": "4.1.2",
    "@angular/compiler-cli": "4.1.2",
    "@angular/core": "4.1.2",
    "@angular/forms": "4.1.2",
    "@angular/http": "4.1.2",
    "@angular/platform-browser": "4.1.2",
    "@angular/platform-browser-dynamic": "4.1.2",
    "@ionic-native/core": "3.10.2",
    "@ionic-native/splash-screen": "3.10.2",
    "@ionic-native/status-bar": "3.10.2",
    "@ionic/cloud-angular": "^0.12.0",
    "@ionic/storage": "2.0.1",
    "cordova-android": "^6.2.3",
    "cordova-plugin-console": "^1.0.5",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-googleplus": "^5.1.1",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.2",
    "cordova-plugin-whitelist": "^1.3.1",
    "ionic": "^3.4.0",
    "ionic-angular": "3.4.1",
    "ionic-cli": "0.0.0",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "ngx-cookie": "^1.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.11"
  }`

**Comment by AmitMY** [comment]
- Please fill the issue template 
- What is the template that causes this?

**Comment by Sid21m** [comment]
@AmitMY I am using a template similar to this 
`<ion-item>
  <ion-label>Employee</ion-label>
  <ion-select [(ngModel)]="employee" [compareWith]="compareFn">
    <ion-option *ngFor="let employee of employees" [value]="employee"></ion-option>
  </ion-select>
</ion-item>`

**Comment by AmitMY** [comment]
- Please fill the issue template
- Do you have `IonicPageModule.forChild(YOUR-PAGE)` imported in the module? Also similar is not necessarily good enough, can you reproduce this in a plunker?

**Comment by adriallongarriu** [comment]
You need to update "ionic-angular": "3.4.2"

**Comment by Sid21m** [comment]
@adriallongarriu Thanks it worked
