### ISSUE TITLE
Angular 2 start repository is missing!

### ISSUE THREAD

**Issue by blackSpiderMan** [ionic-team/ionic#12158]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

when doing "ionic start [project name] blank" attempt to download from https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz fails to download. 
**Expected behavior:**

Should have scafolded a new project automatically.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by AmitMY** [comment]
- Please check your network connection and try again

**Comment by jgw96** [comment]
Hello all! We are actively looking in to this. It looks like some issues with the CLI.

**Comment by jgw96** [comment]
Thanks for the heads up @AmitMY . Closing this one for now.
