### ISSUE TITLE
when i use ionic printer to print a page ,bug it have a blank page more.

### ISSUE THREAD

**Issue by fengyefeiwu** [ionic-team/ionic#12163]
printInBrowser() {
    if (!this.el) return;
    let page = this.el.outerHTML;
    let printWindow = window.open('', 'PRINT', 'height=600,width=800');
    printWindow.document.write('<html><head><title>' + document.title + '</title>');
    printWindow.document.write('<link href="' + this.href + '" media="all" rel="stylesheet" type="text/css" />');
    printWindow.document.write('</head><body>');
    printWindow.document.write(page);
    printWindow.document.write('</body></html>');
    printWindow.document.close(); // necessary for IE >= 10
    printWindow.focus(); // necessary for IE >= 10*/
    setTimeout(function () {
      printWindow.print();
      printWindow.close();
    }, 1000)
    return true;
  }

![image](https://user-images.githubusercontent.com/29601673/27568917-36af3c54-5b27-11e7-812f-39be4655c3ba.png)

**Comment by AmitMY** [comment]
- Please fill issue template.
- I would assume that the printer window that is opened is not waiting to ready event, and creates a temp PDF of an empty page. You have access to the opened window's window object, listen for the ready event and only when ready try to print, might work

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-native#1737
