### ISSUE TITLE
When app running in background with keyboard open then it shows some white gap

### ISSUE THREAD

**Issue by mobileias** [ionic-team/ionic#12164]
Hello 

we are using ionic 1.2.4 and creating build using phonegap website.

`<preference name="phonegap-version"           value="cli-6.5.0" />`

we used ionic keyboard plugin with below config. 

`<preference name="KeyboardDisplayRequiresUserAction" value="false"/>`
`<plugin name="ionic-plugin-keyboard" source="npm" version="2.2.1" />`
  `<feature name="Keyboard">`
	`<param name="ios-package" value="IonicKeyboard" onload="true" />`
  `</feature>`

Now all is fine in android but in ios when we put app in background with keyboard open then after 2-3 min when we see app running in background then it shows like below.

http://prntscr.com/folhwa
![ios-issue](https://user-images.githubusercontent.com/14582437/27571179-7597a2f4-5b21-11e7-8302-b413f213f33c.png)

So possible to give any idea why this type behavior occur in only ios.

After we open app from background it hide that white gap and fine but when we see app in background that time only it shows gap.

Regards

**Comment by AmitMY** [comment]
- Please fill in the issue template
- For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1
- On iOS, use the [ionic wkwebview plugin](https://github.com/ionic-team/cordova-plugin-wkwebview-engine), it might help, though I have no experience with ionic v1

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-v1#272
