### ISSUE TITLE
bug: cannot find name 'Buffer'

### ISSUE THREAD

**Issue by RashmiPandey** [ionic-team/ionic#12169]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>I am developing a Nodejs mobile app using Ionic, Angular 2 and Aws Cognito. After  integrating  amazon-cognito-identity-js, it shows error cannot find name 'Buffer'

AWS Cognito installed using the command: npm  install --save amazon-cognito-identity-js

 After adding following statement:
 import { CognitoUserPool, CognitoUserAttribute, CognitoUser, AuthenticationDetails } from 'amazon-cognito-identity-js'

getting the following error: 
 Cannot find name 'Buffer'.
 L1031:  export type _Blob = Buffer|Uint8Array|Blob|string;
 L1032:  export type Boolean = boolean;</span>

<span is-issue-template></span>

**Comment by janpio** [comment]
Probably not a bug in Ionic Framework, but in the way you use this library. Try https://forum.ionicframework.com of StackOverflow.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
