### ISSUE TITLE
URL Cleanup

### ISSUE THREAD

**Issue by danbucholtz** [ionic-team/ionic#12178]
In order to support `n` root level navs, we went back to basics on URLs. The URLs are temporarily longer while we complete the refactor of our navigation.

- [x] Rather than use a generated `id` like `n4` or `t0`, it would be better to allow a name to be provided to the nav. This name must be unique.

- [x] Reduce URLs down to have the minimal set of hierarchy information

Thanks,
Dan

**Comment by iget-master** [comment]
Just a suggestion, this issue should be on the release notes/change log, although it's explained that things has changed, it should be clear that's "normal".

**Comment by Rhonun** [comment]
@danbucholtz is there an eta on this? The urls are very ugly right now and my product people are freaking out. Is there a way to turn of n root navigation or get the urls to look like they used to?

E.g.

Before:
myapp.com/login -> myapp.com/welcome -> myapp.com/content/article/new

Now:
myapp.com/nav/n4/login -> myapp.com/nav/n4/welcome -> myapp.com/nav/n4/content/article/new

It looks terrible now. Is there a way to make it look like it did before?

**Comment by danbucholtz** [comment]
@Rhonun,

This is out today.

Thanks,
Dan
