### ISSUE TITLE
[BUG] Issue with item-md.scss

### ISSUE THREAD

**Issue by killianperea** [ionic-team/ionic#12171]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When the SASS variable $item-md-sliding-content-background on the ion-item is modified, the background-color doesn't change.

**Expected behavior:**
The ion-item background  should be changed with the color of the $item-md-sliding-content-background.

**Steps to reproduce:**
Go to variables.scss and change the SASS variable $item-md-sliding-content-background

-->

**Related code:**
The item-md.scss has a misstype and the class .item-md uses the variable $list-md-background-color directly and should use the $item-md-sliding-content-background one. 
```
.item-md {
  @include padding-horizontal($item-md-padding-start, 0);

  position: relative;

  font-size: $item-md-font-size;
  font-weight: normal;
  text-transform: none;

  color: $list-md-text-color;
  background-color: $item-md-sliding-content-background;
  box-shadow: none;
  transition: background-color 300ms cubic-bezier(.4, 0, .2, 1);
}
```

**Comment by AmitMY** [comment]
Thanks for reporting this.
I think it might be a problem with the name, but it is correct. `$item-X-sliding-content-background` means the `ion-item-sliding`'s background.

Perhaps there should be a doc change. What would be clearer?

Current:
```
@prop - Background for the sliding content
```

**Comment by killianperea** [comment]
Currently the .item-md class uses directly the SASS variable $list-md-background-color instead of $item-md-sliding-content-background so if you change the $item-md-sliding-content-background nothing happens because no one is using it.
