### ISSUE TITLE
How to close ion-select automatically?

### ISSUE THREAD

**Issue by Gopalakrishnakodimela** [ionic-team/ionic#12172]
My ionic version is..
Cordova CLI: 7.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.10.0
Xcode version: Not installed

I am using Ion-select for loading some data,by default its taking Alert controller.
Can any one tell me how to close Ion-select like radio list automatically.

**Comment by AmitMY** [comment]
- Please fill the issue template
- This is a support request. You will find more help in the forum

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
