### ISSUE TITLE
List item reorder don't work with Push mode

### ISSUE THREAD

**Issue by iron9light** [ionic-team/ionic#12177]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
List item reorder don't work with Push mode.

**Expected behavior:**
Works with `ChangeDetectionStrategy.OnPush` of it's container page.

**Steps to reproduce:**
Change the sample code: https://github.com/ionic-team/ionic/blob/master/demos/src/item-reorder/pages/page-one/page-one.ts
Mark `PageOne` class as `ChangeDetectionStrategy.OnPush`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.8
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.11.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.4
```

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this.
