### ISSUE TITLE
Ion-Select does not trigger ng2-translate pipe when changing language after selection (With a bonus GIF example!)

### ISSUE THREAD

**Issue by kamok** [ionic-team/ionic#12179]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
A picture is worth a thousand words, a gif is worth more: 
http://g.recordit.co/p7l0KyysW0.gif

But here's a summary: Using ion-select, when first selecting a value, then changing the language, the selectedValue requires a click on the ion-select component for the value to update in the background. 

What can I do to make it update without having to manually set the selectedValue?

This is the template: 

```
<ion-item>
     <ion-label>{{ inputArray['ethnicity_id'].label | translate }}</ion-label>
     <ion-select type="text" formControlName="ethnicity_id" (blur)="onInputChange(inputArray['ethnicity_id'])">
            <ion-option *ngFor="let ethnicity of local.ethnicities" [value]="ethnicity.id">{{ ethnicity.name | translate }}</ion-option>
     </ion-select>
</ion-item>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.8
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.9.1
    OS         : OS X El Capitan
    Xcode      : Xcode 8.2.1 Build version 8C1002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    npm        : 4.1.2
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by kamok** [comment]
Ended up using this hack to fire the update method on ion select. The field is translated when ionSelect updates:

```
// Select all the Selects with ViewChildren
@ViewChildren(Select) ionSelects: QueryList<Select>;

// when changing language... fire this below: 
if (this.ionSelects) this.ionSelects.map((select) => select._inputUpdated());
```

**Comment by alexandre-pereira** [comment]
Up

**Comment by peterpan666** [comment]
Had the same issue, answered [here](https://github.com/ionic-team/ionic/issues/8561#issuecomment-391079689)
