### ISSUE TITLE
Improve ion-select customisation

### ISSUE THREAD

**Issue by mebibou** [ionic-team/ionic#12175]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
It is only possible to override a few sass variables on `ion-select`

**Expected behavior:**
We should be able to set more things, like the `font-size`, or the size of the arrow, override the `max-width` attribute that defaults to 45%, etc. Other components like `ion-button` have a lot more variables to customize it.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.0
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.0.0
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v7.4.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 4.1.2 
```

**Comment by AmitMY** [comment]
Thanks for opening a feature request.
Ionic tries to keep to the design spec of the native components, and thus it does not allow customization on stuff that are to spec.

You can customize it by overriding ionic's css, but imo it is less than recommended as it will be out of spec.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#261
