### ISSUE TITLE
How to compile a lower version support

### ISSUE THREAD

**Issue by wardenlzr** [ionic-team/ionic#12182]
How to compile a lower version support?
cordova build android --release -- --gradleArg=-PcdvMinSdkVersion=16
I use this command, but compiled or cannot run on low version of the android devices

my ionic info

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.0.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.0
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.0.0

System:

    Node       : v7.9.0
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.2.0

**Comment by AmitMY** [comment]
How low exactly? what is the target version?
Also, try with `--prod` so it will transpile your output bundle as well

**Comment by wardenlzr** [comment]
I want to run on android 4.1

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
