### ISSUE TITLE
Problem with max length on ion-input type="text"

### ISSUE THREAD

**Issue by RuneStenstroem** [ionic-team/ionic#12184]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I set max length on an ion-input type="text" it do not work correct on Android (I have not tried it on iOS). If i set the max length to 75 I can write more than 75 characters, but the exstra characters disappear when I hide the virtual keyboard. When i use type="tel" with max length I cannot write the exstra characters.

**Expected behavior:**
I would expect the input to not accept more characters than the max lenght when the virtual keyboard is open.

**Related code:**
 <ion-input maxlength="75" type="text" formControlName="title"></ion-input>

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:
    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.0
    OS         : Windows 8.1
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10
```

**Comment by AmitMY** [comment]
I tried to do something like this once, take a look at [this](https://stackoverflow.com/questions/43213582/angular-ngmodel-doesnt-update-when-ngmodelchange-keeps-value), see if it is relevant.

In my case, the problem was that writing for example more than 75 characters, trims the new characters, so the change detection does not recognize anything as changed, but when I do something that updates the change detection it gets the correct value.

Not sure this is the case though.

**Comment by jgw96** [comment]
@RuneStenstroem out of curiosity are you using the default google keyboard that comes in stock android? We've ran into some weird issues before that were similar to this with people using third party keyboards on android.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by RuneStenstroem** [comment]
Sorry for the late reply, i am using a huwai phone so i do not think it is a stock keyboard. I will try it on another phone today.
