### ISSUE TITLE
deeplink not works with non-root path

### ISSUE THREAD

**Issue by izee** [ionic-team/ionic#12186]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior and Steps to reproduce:**
1.set `<base href="/">` in index.html
2.rewrite all request to index.html
3.open http://hostname/any_path_mapping_to_ionic_app/deeplink_args
4.ionic will relocation to root path `http://hostname/` and deeplink not works.

**Expected behavior:**
in step 4, keep location as `http://hostname/any_path_mapping_to_ionic_app/deeplink_args` and deeplink working with `deeplink_args`

**Other information:**
```
locationStrategy: 'path'
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.1
Ionic Framework Version: 3.4.2
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! So there are two issues here, first, with the way our deeplinks work you do not want to do rewrites. Also, with our setup, you do not need to set up a `base`. If you remove your rewrites and also remove your `base` that will fix the issue. Thanks! We may support rewrites in the future, but do not have any plans for this soon.
