### ISSUE TITLE
Inconsistent device behavior on content padding

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#12188]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have an app with `ion-content` and `ion-footer`.
If I run using serve, everything is fine, however, if I run on iOS device, I get sometimes with and sometimes without padding bottom:
![padding](https://user-images.githubusercontent.com/5757359/27633024-3f7788ca-5c06-11e7-9f28-542c09949a2b.png)

(Image taken from the same app, force closed a couple of times to get different results)

**Expected behavior:**
Consistent behavior, padding bottom for content

**Steps to reproduce:**
I can give you access to the repo, ping me in slack

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v7.9.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : not installed
    npm        : 5.0.3 

```

**Comment by jgw96** [comment]
Hello! What version of iOS is this? Also, is this on the iOS simulator or an actual device? Finally, do you have any kind of custom css on the content or footer?

**Comment by jgw96** [comment]
Oh also, do you have an `ion-toolbar` wrapping the contents of your `ion-footer` ?

**Comment by AmitMY** [comment]
- What version of iOS is this? 
  - 10.3.2
  - 11 Public beta
- Is this on the iOS simulator or an actual device? 
  - Both
- do you have any kind of custom css on the content or footer?
  - no
- do you have an ion-toolbar wrapping the contents of your ion-footer ?
  - yes

The weird thing that it happens most of the time without padding, but sometimes with, makes me think there must be something weird in play.
