### ISSUE TITLE
Config.set custom value returns Null

### ISSUE THREAD

**Issue by masoud919** [ionic-team/ionic#12180]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

In the documentation it says:
https://ionicframework.com/docs/api/config/Config/
> Any value can be added to config, and looked up at a later in any component.

and:
> `set(platform, key, value)`
The platform (either 'ios' or 'android') that the config value should apply to. Leaving this blank will apply the config value to all platforms. OPTIONAL

I'm trying to set a value (for ex. my API URL) in Config for all platforms.
I run the app on browser by running `ionic serve` in terminal, get null in console. Is this a bug?

**Related code:**

```
this.config.set('', 'url', 'http://localhost/cpapi/public');
console.log(this.config.get('url'));
```

**Other information:**

**Ionic info:** 

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v8.1.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : not installed
    npm        : 5.0.3 
```

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this.
