### ISSUE TITLE
ionic package build android - Gradle wrapper error

### ISSUE THREAD

**Issue by bode94** [ionic-team/ionic#12189]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
*ionic package build android*
Build fails with Error: 
**ANDROID_HOME=/opt/android-sdk
JAVA_HOME=/usr/lib/jvm/java-8-oracle
Error: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
Looked here: /opt/android-sdk/tools/templates/gradle/wrapper**

Looks like the Package server does not provide a gradle wrapper.

**Expected behavior:**
No Error should occur on building process.

**Steps to reproduce:**
Run *ionic package build android*

**Ionic info:**:

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.8
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.8
```

**Comment by AmitMY** [comment]
You have to install android sdk with all tools to get gradle, or android studio

**Comment by bode94** [comment]
I can build my app by using *ionic cordova build android*. That works just fine. 

Though I am trying to build my app using [ionic package](https://docs.ionic.io/services/package/)

I think the error occurs due to the missing gradle wrapper on ionic's package server.

**Comment by AmitMY** [comment]
Oh oops sorry I am used to see `cordova build`s going wrong, I work on auto mode :)

**Comment by davec21** [comment]
Try updating your android to 6.2.3 and see if you still have the issue.

I get that error locally if I have android 6.1.2 but not 6.2.3.  Apparently there was an android sdk update which changed paths and such.

**Comment by jgw96** [comment]
Hello all! I can confirm that the fix for this issue is to update to 6.2.3 of the cordova android platform. Thanks for using Ionic!

**Comment by chris-bryant** [comment]
I am experiencing this error on android 6.2.3.

`global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Gulp CLI         : CLI version 3.9.0 Local version 3.9.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-gulp          : 1.0.1
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.4.0
    OS         : Linux 3.13
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.2.0 
`

**Comment by davec21** [comment]
Do you have Android studio installed?

**Comment by chris-bryant** [comment]
I removed the android platform and added it back and the last build worked. :dizzy_face:
