### ISSUE TITLE
Problems with List and Navigation in UWP

### ISSUE THREAD

**Issue by Machareder** [ionic-team/ionic#12183]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In uwp app (phone or tablet) the app takes 1-6 seconds after clicking on an item until it navigates to the next page. The delay is not so bad if the list is small (20 Items/ 1-2 second delay), but in my project i have over 14k items.
By clicking on a Button i have to wait 1-2 Seconds on my developer PC (16GB Ram, Intel i7-6700HQ 2,6 GHZ)
On the test device (that our employees use/ 4GB Ram, Intel Atom Z3795 1,6 GHZ) it has a delay of 2-6 Seconds, and that is a big problem.

**Expected behavior:**
Like in the Browsermode, click and navigate without delay

**Steps to reproduce:**
Steps todo:
Step 1: Download both Projects and install:
As Example i have created two projects:
	One use IonicPage´s:
		https://github.com/Machareder/example-ionicpage-list.git
	The other use the "normal" way of ionic:
		https://github.com/Machareder/example-ionic-list.git
		
Step 2: Add the windows platform

Step 3: Enjoy the bug...

PS: Both projects have the same bug...
-->

**Related code:**

```
insert any relevant code here
```

**Other information:**
There is/was a Thread here: https://github.com/ionic-team/ionic/issues/11783

mhartington said: 

mobidev111 having used ionic and windows uwp the other day, it is much improved. I'm going to lock this issue as the conversations here are not being constructive.

Does he mean the current version of ionic? Or is there coming an improved ionic version for uwp?

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

global packages:

    @ionic/cli-plugin-proxy : 1.3.1
    @ionic/cli-utils        : 1.4.0
    Cordova CLI             : 6.4.0
    Ionic CLI               : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.8
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : windows 4.4.3
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.11.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.1.2

**Comment by Machareder** [comment]
Hey jgw96,
in chrome it works great.

I tested Edge now  the first time, there is the same delay like in the uwp app.

**Comment by jgw96** [comment]
@Machareder which version of edge are you testing with?

**Comment by Machareder** [comment]
@jgw96 
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393
