### ISSUE TITLE
Ionic 3 ignores arguments passed to Modal's dimiss method and does not forward them to onDidDismiss callback

### ISSUE THREAD

**Issue by 4mp3R** [ionic-team/ionic#12190]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Modal's `onDidDismiss` callback is called ignoring the `dismiss()` arguments.

**Expected behavior:**
`onDidDismiss` should be called with `data` passed `dismiss()`.

**Steps to reproduce:**
http://plnkr.co/edit/VmigY40g2VQGuknIEYT4?p=preview

Just push the `Opned modal` button.
A modal will open, then it will be automatically dismissed after 1 second with `.dismiss('data here')`.
`onDidDismiss` will then be called and show the data passed in an alert, which will be `undefined`.

**Related code:**
https://github.com/ionic-team/ionic/blob/master/src/navigation/overlay-proxy.ts#L45
I'd expect the data to be passed to `this.overlay.dismiss` here.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 3.4.2
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.8
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: OS X El Capitan
Node Version: v6.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.
