### ISSUE TITLE
Ion-input validation message

### ISSUE THREAD

**Issue by iget-master** [ionic-team/ionic#12196]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Actually, looks impossible to have a nice input validation feedback using only ionic features.

**Expected behavior:**
I think that isn't so hard to implement a message attribute on `ion-input` component:

`<ion-input message="my message">`

This message field could be used also to provide a helper text to that field.

Actually we need to add a list item to our list, and style it manually to make it beautiful.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#262
