### ISSUE TITLE
Add ability to disable URL with lazy loading

### ISSUE THREAD

**Issue by Daskus1** [ionic-team/ionic#12199]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[x] feature request
**Current behavior:**
Currently it's not possible to disable the URL when using lazy loading. As deeplinking does not work well with complex navigation structures (yes I already tested v3.5.0) we need to be able to at least hide the URL.

**Expected behavior:**
For example with a config property which disables/hides the URL.
In my opinion this is really important because if someone wants to publish their app as PWA but the deeplinker does not work well with their nav-structure the user-experience will be even worse as with deeplinks.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind opening an issue with us about the deeplinking issues your seeing? Also, thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#263

**Comment by mebibou** [comment]
@jgw96 any update on this? I'm trying to prevent users from navigating to lazy-loaded pages using their link if the user is not logged in, and having a way to disable navigation as long as the user is not logged in would be the best way to do it imo.
