### ISSUE TITLE
Modal with header and navbar height is too big

### ISSUE THREAD

**Issue by viethoang88** [ionic-team/ionic#12209]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Currently it's height is 2x height of normal standard header navbar
![simulator screen shot jun 30 2017 3 38 32 am](https://user-images.githubusercontent.com/1701310/27709388-146f1fbc-5d46-11e7-9043-1451f38138e9.png)

**Expected behavior:**
It should have normal height as standard ion-navbar inside ion-header

**Related code:**

```
<ion-header>
  <ion-navbar>
    <ion-title>
     Profile name
    </ion-title>
    <ion-buttons end>
      <button ion-button [hidden]="hideCloseButton" (tap)="dismiss()">
        <span ion-text color="primary" showWhen="ios">Close</span>
        <ion-icon class="close" name="md-close" showWhen="android,windows"></ion-icon>
      </button>
    </ion-buttons>
  </ion-navbar>
</ion-header>
```

**Comment by AmitMY** [comment]
It is normal height, including `statusbar-padding`.

- Please specify your `ionic info`
- If this is IOS 11 it is a known bug, and will be fixed before stable iOS 11.
- If you set your statusbar not a part of your view in the `config.xml`, then you should also set `this.config.set('', 'statusbarPadding', false)` and it will not add that padding.
- Else, let us know what is the exact environment, or perhaps create a repo we can clone and test it

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by DavidRyu123** [comment]
After the stable version we are still experiencing same issue with UIview. Any update plan to address this issue?
