### ISSUE TITLE
NavCtrl Remove view and 3.5.0

### ISSUE THREAD

**Issue by tgensol** [ionic-team/ionic#12207]
Hi there,

I was using the .remove() function for removing a view after going to another one. But since the new 3.5.0, there is an issue, and it is impossible to going back. (I created a plunkr)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Steps to reproduce:**

http://plnkr.co/edit/cThaA6XScBVvbuLtRRwk?p=preview

With ionic 3.4.X, you can go from the page Test 2 to the main page with the back button,
With ionic 3.5.0, if you tried to remove the view Test 1, it will be then impossible to use the navCtrl.pop() function, even if the promise resolves well.

Maybe there is a better way to do what I want to do (one user has to do views A->B->C and then going back to A), but the fact is there is something broken with the new version

Thanks ! 
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.1.0 
    npm        : 3.10.10 

```

**Comment by astec** [comment]
This is a common scenario and is very critical issue.

**Example**: `List page` => `Add page` => `Details page` => _back to_ `List page`

**Comment by danbucholtz** [comment]
We'll take a look and fix it.

Thanks,
Dan

**Comment by danbucholtz** [comment]
@tgensol, @astec,

Can you try `ionic-angular@nightly` and see if it makes a difference? I believe this is fixed.

Thanks,
Dan

**Comment by tgensol** [comment]
Working on my side, thanks ! @danbucholtz

**Comment by lucasvanhalst** [comment]
Thanks for the issue/fix, had been pulling my hair out because it wouldn't work and I didn't understand why...
