### ISSUE TITLE
Ionic 2 Tab component Maximum call stack size exceed

### ISSUE THREAD

**Issue by GrantHoffman** [ionic-team/ionic#12206]
**Ionic version:**  (check one with "x")
[ X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
  Having a layout page, with a tabs component, whose root page uses the layout page causes a the stack to exceed maximum support
**Expected behavior:**

All Components should support native features of angular 2 or be specified in the documentation that this is not supported and steps should be provided on how to avoid this issue. 

**Related code:**

I have a layout component in which I would like to wrap all my pages in which looks like so:
```
<ion-header>
  <ion-navbar>
    <button ion-button icon-only menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>
      {{pageName}}
    </ion-title>
  </ion-navbar>
</ion-header>
<ng-content>
</ng-content>
<ion-footer>
  <ion-toolbar>
    <ion-tabs>
     <ion-tab [root]="usersPage" tabTitle="Chat" tabIcon="chat"></ion-tab>
    </ion-tabs>
  </ion-toolbar>
</ion-footer>
```
And Typescript file which looks like so:

```
export class AstootLayoutComponent {

    @Input() pageName: string;

    usersPage: any = UsersPage;
    profilePage: any = ProfilePage;
}
```
In the layout I reference my root Users page who HTML looks like so:

```
<astoot-layout [pageName]="pageName">
  <ion-content padding>
    <page-list-base [detailPageType]="userDetailType" [baseProvider]="baseProvider" [config]="pageListConfiguration"></page-list-base>
  </ion-content>
</astoot-layout>
```
just incase it's need my Type script looks like so:

```
 export class UsersPage {

    public pageName: string = "Users";

    public userDetailType: any = ProfilePage;
    public pageListConfiguration: PageListConfiguration = { canDelete: false, canCreate: true };

  constructor(public navCtrl: NavController, public navParams: NavParams, public baseProvider: Users) {
  
  }
}
```

When my Layout Component Root page does not contain my layout component everything works fine, but when it does a forever loops seems to be created.

How can I reuse this component?
What can I do to make my project work again?
Why is this not in the Tabs documentation?

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind sharing a repo we can use to reproduce this issue? This is definitely not expected behavior.

**Comment by GrantHoffman** [comment]
@jgw96 Thanks for your quick reply.  I will do so when I get back home tonight

**Comment by granthoff1107** [comment]
I've created a repo, took a bit I needed to scrub a few details out the repo, and point it to the github  public api.   

Just as a warning, since you are in a forever loop you are going to hit the Github api serveral times.  During my test I did not hit the rate limit, but because it's in a loop it might, which would be bad. 

Inside the repo is a zip file called Ionic_Sample.Zip  that includes all of my current package and if you unzip it you should be able to run directly.  

My base provider does not provide the url for the api, because I override it in the http-interceptor, from my enviorment.ts incase you want to change the api

https://github.com/granthoff1107/Ionic-Sample-Max-Exceed

Thanks for your help

**Comment by jgw96** [comment]
Hello @granthoff1107 , thanks for the repo, this is awesome! Quick question, do you get the memory error when you do not hit the api or when you remove your custom http logic?

**Comment by GrantHoffman** [comment]
@jgw96, Thanks I've just been playing around trying to make everything generic.    
If you do not hit the api,  I believe you will still get the memory error it will just take a whole lot longer, because your memory is not being consumed by the obtaining resources, but I'm not 100% I haven't waited the full time, but I'm assuming because it never loads, it locked in a loop.

I haven't tried with removing the custom http logic, I can do that when I get home tonight.

What I can tell off the top of my head you is that: 
 
The code will work and only go to the api once if you remove the nested reference to the tabs.  For example if you a referencing the profile page, and the profile page does not contain my layout element.  The tabs controller will be there.

This code also works fine if there is no tabs controller.

**Comment by granthoff1107** [comment]
@jgw96 so this is not expected behavior right?  Do we have any information on why this is happening or perhaps a work around I can use to solve this?

**Comment by granthoff1107** [comment]
@jgw96  Why did you say this is expected behavior? I solved this by adding a bounty to this, https://stackoverflow.com/questions/44815548/ionic-2-tabs-maximum-call-stack-size-exceeded

Can you update your documentation
