### ISSUE TITLE
unable to update ionic from npm

### ISSUE THREAD

**Issue by ivanovvitaly** [ionic-team/ionic#12205]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I get error when trying to install ionic to global packages

npm ERR! registry error parsing json
⸨    ░░░░░░░░░░░░░░⸩ ⠧ fetchMetadata: ERR! registry error parsing json

**Expected behavior:**
Ionic updated in global packages

**Steps to reproduce:**
```
sudo npm install -g ionic
```
**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by ivanovvitaly** [comment]
seems like not actual anymore, works now

**Comment by codebeauty** [comment]
I tried again and it runs without any errors.
