### ISSUE TITLE
Ionic 2 Range Slider

### ISSUE THREAD

**Issue by Venu25** [ionic-team/ionic#12208]
how to use dual range selection ;
like  :  values should be  customize  45 to 90 

did't work  
              <ion-range dualKnobs="true" [min]=selectMin [max]=selectMax step="3" 
                snaps="true" [(ngModel)]="time"   ></ion-range>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
