### ISSUE TITLE
Ion-select activated on enter in input field

### ISSUE THREAD

**Issue by peterssonanton** [ionic-team/ionic#12202]
**Ionic version:** 3.x

**I'm submitting a ...** bug report

**Current behavior:**

An ion-select element is activated when hitting the enter key while in an ion-input field on the same page. It seems to be the same issue as this that was fixed but has appeared again:
https://github.com/ionic-team/ionic/issues/5596

**Expected behavior:**

It should not open.

**Steps to reproduce:**

Have an ion-select an ion-input element on the same page.
Enter something in the input field.
When hitting enter (or Go/Submit on devices), the select window is activated as if you clicked the element.
**Related code:**

```
<ion-item >
  <ion-label>Select one:</ion-label>
  <ion-select>
    <ion-option>Option 1</ion-option>
    <ion-option>Option 2</ion-option>
    <ion-option>Option 3</ion-option>
    <ion-option>Option 4</ion-option>
  </ion-select>
</ion-item>
<ion-item>
  <ion-label>Input:</ion-label>
    <ion-input type="text"></ion-input>
</ion-item>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.11.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.1.2


```

**Comment by jgw96** [comment]
Hello @peterssonanton , mind sharing a minimal repo we can use to reproduce this issue? I am not able to reproduce this on my Nexus 6 running Android 7.1.1. Thanks!

**Comment by peterssonanton** [comment]
Hi @jgw96 ,
I used the ionic components preview app to demonstrate the issue: https://github.com/peterssonanton/example
I can reproduce it both in the browser and on device.

**Comment by llioss** [comment]
Hi,
I have the same issue in my project with :
```
<form>
    <ion-list>
        <ion-item>
            <ion-label>AnyLabel</ion-label>
            <ion-select>[...]</ion-select>
        </ion-item>
        <ion-item>
            <ion-label>AnyInput</ion-label>
            <ion-input>[...]</ion-input>
        </ion-item>
        <ion-item>
            <button ion-button type="submit">MySubmitButton</button>
        </ion-item>
    </ion-list>
</form>
```

And when i press enter key on desktop or mobile in the ion-input, the select window is activated.

**Comment by japostigo-atsistemas** [comment]
Still reproducing the same issue. I had fixed it putting an invisible button at the top of the form, so that button is triggered instead of the ion-select when enter key is pressed.
