### ISSUE TITLE
Alert Prompt auto-focus of first input element broken since 3.4.2

### ISSUE THREAD

**Issue by frankpapenmeier** [ionic-team/ionic#12214]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.4.2 and above**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
First input element in alert prompt created with AlertController is not focused automatically anymore since ionic-angular 3.4.2

**Expected behavior:**
First input element should be focused automatically

**Steps to reproduce:**
Original Behavior in 3.4.1:
http://plnkr.co/edit/TUAhgAC6V0HLdyNDXQjh?p=preview
(click open alert prompt button and watch auto-focus of input element)

Behavior in 3.4.2:
http://plnkr.co/edit/I8K6JuAIijbGldtxwnyA?p=preview
(no auto-focus anymore)

Behavior in 3.5.0:
http://plnkr.co/edit/9AuxpB27vQwgzxR4TgPz?p=preview
(still broken)

** Further Info **

Issue might be related to the following PR:
https://github.com/ionic-team/ionic/pull/12023
(Although it is tagged with 3.4.1 also, the changes seem to have been effective with 3.4.2 only.)

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this.

**Comment by nateOVO** [comment]
I have also been experiencing this issue for a few weeks now. Any update on this?

**Comment by frankpapenmeier** [comment]
Just tried upgrading to 3.5.3: Unfortunately, this regression still exists in 3.5.3

**Comment by lostdev** [comment]
Problem for me in 3.5.2 as well.

**Comment by Rudimo** [comment]
The same in version 3.6.0

**Comment by lostdev** [comment]
Is there a recommended work-around for this?

**Comment by Rudimo** [comment]
@lostdev Nothing helps. Previously, the alerts were normal.

**Comment by lostdev** [comment]
@Rudimo have you attempted re-focusing the input manually once the modal is displayed?

**Comment by Rudimo** [comment]
@lostdev No. It seems to me it will not help.

**Comment by lostdev** [comment]
@jgw96 Any update on this issue? I have a work-around for my most important screens but this issue is occurring across the board for me, and the work-around isn't ideal.

Thank you!
