### ISSUE TITLE
ion-select not updating model for default selected option

### ISSUE THREAD

**Issue by AdeshAtole** [ionic-team/ionic#12215]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When an `ion-option` is selected by default using `[selected] = true`, the model doesn't reflect the value. When the selection is updated, the model gets updated though

**Expected behavior:**

The model should contain the selected value even when the selection is not updated.
**Steps to reproduce:**

http://plnkr.co/edit/uYaiiuBsyXXv3mMwT26P?p=preview
**Related code:**

```
    <ion-select [(ngModel)]="selectedOption">
      <ion-option >Lorem</ion-option>
      <ion-option [selected]=true>Ipsum</ion-option>
    </ion-select>
    
    {{selectedOption}}
```

**Other information:**

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.0
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.1.2
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this

**Comment by AdeshAtole** [comment]
@jgw96 What does a 'v2' label resemble?

**Comment by janpio** [comment]
It means that this probably is due to functionality that was present in/since Ionic Framework v2. 
(I find that confusing as well...)
