### ISSUE TITLE
Unable to cordova build android --prod

### ISSUE THREAD

**Issue by ivanovvitaly** [ionic-team/ionic#12216]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I run ionic cordova build android --prod it fails with error

**Expected behavior:**
Should create optimized for production android package 

**Steps to reproduce:**

**Related code:**

```
bash: dnvm.sh: No such file or directory
ionic cordova build android --prod
Running app-scripts build: --prod --iscordovaserve --externalIpRequired --nobrowser

[16:05:17]  build prod started ...
[16:05:17]  clean started ...
[16:05:17]  clean finished in 2 ms
[16:05:17]  copy started ...
[16:05:17]  ngc started ...
[16:05:27]  ngc finished in 9.72 s
[16:05:27]  preprocess started ...
[16:05:27]  deeplinks started ...
[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova). Your plugins may be out of
       date.
Error: The RegExp to find the DeepLinkConfigToken did not return valid data
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.0
    ios-sim    : not installed
    npm        : 5.0.4
```

**Comment by AmitMY** [comment]
First thing I would check:
>[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova). Your plugins may be out of date.

If you update the plugin to latest, and still have the error, please open an issue in [ionic-app-scripts](https://github.com/driftyco/ionic-app-scripts) as here it is just for the framework.

**Comment by ivanovvitaly** [comment]
I have latest version of the @ionic/cli-plugin-cordova installed. It always warn about that

**Comment by tgensol** [comment]
I also have this issue since I updated my angular. Do you use the last angular 4.2.4 ? @ivanovvitaly

**Comment by ivanovvitaly** [comment]
@tgensol angular 4.1.3

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1072
