### ISSUE TITLE
swipeBackEnabled not working in 3.5.0

### ISSUE THREAD

**Issue by Mike1707** [ionic-team/ionic#12219]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After upgrading to 3.5.0 the swipeBackEnabled is not working anymore (in any view).
 
After downgrading to 3.4.2 everything works fine.

**Expected behavior:**
Pages should go back with a swipe on iOS.

**Related code:**

Configuration in app.module.ts:

```
ionicModule.forRoot(MyApp, {
	swipeBackEnabled: true
})
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v7.7.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : not installed
    npm        : 4.1.2 
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. We are looking into this as we speak.

**Comment by jgw96** [comment]
Hey @Mike1707 , would you mind giving the latest nightly at try `npm install ionic-angular@nightly --save` and seeing if that fixes it for you? thanks!

**Comment by Mike1707** [comment]
Hey @jgw96 , thanks for your fast reply! It works now again as expected :-)

**Comment by ericmorentin** [comment]
I might be missing something (apologies in advance), but we moved our app to 3.5.3 today and swipeBackEnabled stopped working. Previous on 3.4.2 it was working.

**Comment by Mike1707** [comment]
Hey @ericmorentin for me it's working with 3.5.3. 
Maybe you have to set in app.module.ts

`ionicModule.forRoot(MyApp, {
	swipeBackEnabled: true
})`

**Comment by ericmorentin** [comment]
Thanks @Mike1707. That didn't seem to work for me, but it is enough to know it is working for you. I will try and identify whats missing.

**Comment by ericmorentin** [comment]
Found out that my problem is caused by using tabs. When my app root page is set to be a page with tabs the swipe to go back no longer works (as the check for canSwipeBack will return false as the Tabs are set as a child nav!).

**Comment by giumarzo** [comment]
Thanks @Mike1707!

**Comment by jjjhanreyyy** [comment]
@ericmorentin How did you fixed your problem?

**Comment by ericmorentin** [comment]
Sadly we didn't.
