### ISSUE TITLE
Only when the user lifts his finger should refresh performed

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic#12227]
**Ionic version:**  (check one with "x")
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] feature request

**Current behavior:**
We cannot handle this behavior.

**Expected behavior:**
I'm using [**Refresher component**](https://ionicframework.com/docs/api/components/refresher/Refresher/) with `Ionic 3` app.It is working fine.But now I have a requirement where **only when the user lifts his finger should refresh performed, if not, then refresh action is canceled**.

**Related code:**

.html

```
 <ion-refresher (ionRefresh)="getData($event)">
    <ion-refresher-content pullingIcon="arrow-dropdown" pullingText="Pull to refresh" 
     refreshingSpinner="circles" refreshingText="Refreshing...">
    </ion-refresher-content>
  </ion-refresher>
```
.ts

```
getData(refresher?: any) {
  Observable.forkJoin([myTopicApi, myarticlApi, myPicksAPi])
      .subscribe(res => {
        if (refresher) { refresher.complete(); }//terminate refresher
      },
      error => {
        if (refresher) { refresher.complete(); }
      },
      () => { if (refresher) { refresher.complete(); } }
      )
}
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.8
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.10.0
    OS         : Windows 8.1
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by Sampath-Lokuge** [comment]
Hi @jgw96 
There is no support yet for this feature.So this is not and support question.I have put this question on both StackOverflow and ionic forum.But no solution yet due to there is no such API support from the Refresher.So please move this as a new feature request.Thanks.

[Ionic ](https://forum.ionicframework.com/t/refresher-only-when-the-user-lifts-his-finger-should-refresh-performed/96494)

[StackOverflow ](https://stackoverflow.com/questions/44853897/only-when-the-user-lifts-his-finger-should-refresh-performed)
