### ISSUE TITLE
New URL segments in 3.5.0 destroying notification data

### ISSUE THREAD

**Issue by thierce** [ionic-team/ionic#12221]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
URLs now have at least two additional segments 'nav/n4'.
eg:  http://somedomain.com/home has become http://somedomain.com/nav/n4/home

When a notification sends a user to a URL, the exact URL must match or the addtionalData in the notification is not retrieved.
With 3.5.0, the URL sent to is passed to the new one with the 'nav/n4' within it thus causing the addtionalData to not be retrieved.
I am using OneSignal's 'additionalData' as the example. I am not sure how others work.

**Expected behavior:**
URLs remain as they are intended and not routed to another with the extra 'nav/n4' ( or alternative).
Or there be a way to Turn Off this.

Ionic Info:
global packages:
    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.4.0
local packages:
    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.5.0
System:
    Node       : v7.9.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.2.0

On a sidenote but relative to this, I just created a new sidemenu project, added a deep-linked homepage ( with @IonicPage )  to the sidemenu list and it works. But, if I go directly to the URL eg: http://localhost:8100/nav/n4/home
it does not load and errors with:
GET http://localhost:8100/nav/n4/home 404 (Not Found)
Refreshing the page also does not load with the same error.

DeepLinking seems to have been rendered useless.

**Comment by danbucholtz** [comment]
@thierce,

Please navigate to the `home` in your app and grab the url that way.

As for the notifications, sorry, but we are making some changes around the URL to make it a first-class citizen. Deep links are working better than ever!

Try `nightly`. You can add a `name` attribute to your `nav` or `tabs` like so:

```
<ion-nav name="myCoolNav">

<ion-tabs name="myCoolTabs">
```
This will get you a nicer url in the short term. Longer term, we need to shrink the URL back down.

Thanks,
Dan

**Comment by thierce** [comment]
Hi Dan, thanks for following up so quickly.

“Please navigate to the home in your app and grab the url that way.”

I am missing something here. Is this in response to the Notification problem or the not being able to go to a URL directly?
I’m not sure what you are meaning or intending to resolve with that statement.

You say deep-linking is working better than ever.. that’s great. But it seems in development using ionic serve, if I go directly to a URL or if reloading a page with a ‘nav/n4’ in it does not load. Do you experience this as well?

In regards to ion-nav name , can I use it like so: navCtrl.name=”myCoolNav” ? ( assuming navCtrl is NavController ).

The ion-nav name sounds like a good thing IF the additionalData from a notification is not lost.
I don’t suppose you know if this works or not?
Thanks,
Andrew

**Comment by thierce** [comment]
With the nightly build, navCtrl.name = "myCoolNav"  works - But it fails on reload and sends location back to homepage.
I have still to test the AdditionalData in notifications.

**Comment by vellengs** [comment]
Why add additional "nav/n4" for URL, where can I find the document for that?
