### ISSUE TITLE
Give ion-option an ionSelect counterpart - ionDeselect?

### ISSUE THREAD

**Issue by dovestyle** [ionic-team/ionic#12234]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
There's currently no event for ion-option deselection in multiple-option ion-selects. The ion-select's ionChange event is not sufficient enough because it only gets called when the OK button is pressed, and the ion-option's ionSelect is only fired when the option is selected.

**Expected behavior:**
Since there is already an ionSelect event for ion-option; how about an ionDeselect? Or even just an all-encompassing ionClick? I'd just like to be notified when changes happen *before* they're saved so I can manipulate the options while the selection (alert) window is still open, eg. applying, (and subsequently clearing), an "All" selection.

**Steps to reproduce:**
I guess just create an ion-select with `multiple="true"` and a bunch of ion-options, and try to to get notified when any of the ion-options are DEselected while the dialog is option

**Related code:**

```
insert any relevant code here
```

**Other information:**
I've spent the last 2 days Googling and hacking, but to no avail. I can't find anyone else who has this particular issue, so it's totally possible I missed something.

EDIT: I've achieved what I want using AlertController with checkbox inputs and manually updating the list, but I still think an ionDeselect output event would be very useful.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.5.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.12
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.11.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#267
