### ISSUE TITLE
IONIC 3 - Can't install native push

### ISSUE THREAD

**Issue by HamzaLJ** [ionic-team/ionic#12236]
**Ionic version:**  (check one with "x")
[ X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
When trying to install native push, I get the following:

          ionic cordova plugin add phonegap-plugin-push

> cordova plugin add phonegap-plugin-push --save
✖ Running command - failed!
[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.        
[ERROR] An error occurred while running cordova plugin add phonegap-plugin-push --save (exit code 1):  
        Installing "phonegap-plugin-push" for android
        Plugin doesn't support this project's cordova version. cordova: 6.3.0, failed version requirement: >=6.4.0
        Skipping 'phonegap-plugin-push' for android
        Plugin "phonegap-plugin-push" already installed on browser.
        Installing "phonegap-plugin-push" for ios
        Plugin doesn't support this project's cordova version. cordova: 6.3.0, failed version requirement: >=6.4.0
        Skipping 'phonegap-plugin-push' for ios
        Saved plugin info for "phonegap-plugin-push" to config.xml
        Error: Cannot find plugin.xml for plugin "com.googlemaps.ios". Please try adding it again.

**Expected behavior:**
It should install with no issues

**Steps to reproduce:**

Try simply to create a new project, then try to install native push and you'll fall in the same error.

**Other information:**
I've tried to uninstall both cordova and ionic and install it from scratch, then created a new project, but I got the same issue by the end.

I am guess that I need to update cordovan-cli to 6.5.0 or higher, I've done everything and it didn't work, after a new fresh ionic installation I got cordova 6.3.0

**Ionic info:**

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.3.0 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.8
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 5.2.2 browser 4.1.0 ios 4.2.1
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.8.6 
    ios-sim    : 5.0.8 
    npm        : 3.10.10 
```

**Comment by AmitMY** [comment]
As it says, it requires 6.4.0 or higher, no way around it. Try `npm install -g cordova@latest` or your preferred version if you have any

**Comment by HamzaLJ** [comment]
@AmitMY of course I've tried that already, it seems to be installed; however, when running an `ionic info` it shows `6.3.0`

**Comment by AmitMY** [comment]
`cordova -v` output?

**Comment by HamzaLJ** [comment]
@AmitMY as I told you before that was `7.0.1` on `ionic info` it's still `6.3.0`

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-native#1756
