### ISSUE TITLE
Clipboard copy/paste not working

### ISSUE THREAD

**Issue by thanhdn9120** [ionic-team/ionic#12231]
Hi everybody,
I'm using ionic 3, I want to implement copy/paste function but currently it not working
below is my code (It's very simple):
```
// copy function
   this.clipboard.copy('Hello world').then(rs => {
      alert(rs);
    }).catch(error => {
      alert(error);
    })
// paste function
    this.clipboard.paste().then(
      (resolve: string) => {
          alert(resolve);
        },
        (reject: string) => {
          alert('Error: ' + reject);
        }
      );
    }
```
when I running on:
- Android: nothing happen
- IOS: It's alert error "plugin is not install" although I installed plugin Clipboard before

Anybody can help me. I think it very simple but It's amazing that this function is not working.
Thanks,
Thanh Nguyen

**Comment by AmitMY** [comment]
- Please fill the issue template
- First thing I would check is remove `platforms` and `plugins` folders, and `ionic cordova prepare`, then make sure that the plugin is in the `plugins` folder, if it not, reinstall it.
- If that doesn't work, please create an issue with `ionic-native` as `clipboard` is a native plugin and is not related to the ionic core

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-native#1758
