### ISSUE TITLE
if I use NavController class   'remove' method, pop and push is not use

### ISSUE THREAD

**Issue by 791060555** [ionic-team/ionic#12238]
if I use NavController class   'remove' method, pop and push is not use

ionic version:3.5

**Comment by AmitMY** [comment]
- Please fill the issue template fully.
The Ionic team is aware of this issue, I can not find the original issue though. I believe @danbucholtz is working on a fix.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. This issue has actually already been fixed and will be in the next release. If you would like to try it now you can get the latest nightly by running `npm install ionic-angular@nightly --save`. Thanks for using Ionic!

**Comment by supryin** [comment]
I am still facing this issue. Ionic-angular 3.5.3.
isTransitioning is still true after remove

**Comment by AmitMY** [comment]
What about 3.6.0?

**Comment by supryin** [comment]
I can't upgrade to the 3.6.0 in the current project due to other business requirements.

**Comment by tonysamperi** [comment]
Same here on <pre><code>ionic-angular@3.9.2</code></pre>
