### ISSUE TITLE
Application terminated when Android platform paused

### ISSUE THREAD

**Issue by Smoke1987** [ionic-team/ionic#12230]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
an application using Ionic v3, when the state of the platform is switched to pause (the application is minimized or the camera is activated), the application is destroyed. 
Android studio log (the camera is activated):
```
D / CordovaActivity: Paused the activity.
I / chromium: [INFO: CONSOLE (38630)] "platform.pause-> event {" isTrusted ": false}", source: file: ///android_asset/www/build/main.js (38630)
D / CordovaActivity: Stopped the activity.
W / ManagedEGLContext: doTerminate failed: EGL count is 3 but managed count is 1
W / ManagedEGLContext: doTerminate failed: EGL count is 3 but managed count is 1
W / IInputConnectionWrapper: showStatusIcon on inactive InputConnection
Application terminated.
```

**Expected behavior:**
Don`t destroy app

**Steps to reproduce:**
-

**Related code:**
-

**Other information:**
-

**Ionic info:**

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
