### ISSUE TITLE
Keyboard hides bottom tabs on iOS 

### ISSUE THREAD

**Issue by neoassyrian** [ionic-team/ionic#12245]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The keyboard hides the tabs (located at the bottom) on iOS when the keyboard is opened (e.g. when you click on an input to enter text).

**Expected behavior:**
Tabs should be displayed/visible when the keyboard is opened on iOS (Similar to Android)

**Steps to reproduce:**
Create an app with Tabs located at the bottom. 
Click on an input element to enter text
Keyboard opens automatically
Tabs gets hidden

**Related code:**

**Other information:**

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.4.1

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

**Comment by AmitMY** [comment]
If I go to the phone app on iOS, which is a tabbed application, and click on "search", the keyboard indeed hides the tabs, so the current behavior is to spec.

**Comment by jgw96** [comment]
Hello all! As @AmitMY stated, this behaves this way because it follows the design spec. Thanks for using Ionic!

**Comment by neoassyrian** [comment]
is this an iOS design spec? 
Can you provide more information please?

**Comment by AmitMY** [comment]
While I do not find a link that shows keyboard on tabs in the iOS spec, if you open any app that comes with the device, like "phone", and you bring up the keyboard, for example by searching something, it hides the tabs
