### ISSUE TITLE
brief black screen while loading the lazyLoadTabs  demo project

### ISSUE THREAD

**Issue by hellogithub2014** [ionic-team/ionic#12240]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
While loading the [lazyLoadTabs demo](https://github.com/mhartington/lazyLoadTabs) in chrome,  there is a brief black screen before the whole page loaded

**Expected behavior:**
no black screen

**Steps to reproduce:**
1. download the lazyLoadTabs demo, install and start it. 
2. typing localhost:8100 in chrome, and open dev tools, choose a device like iphone6 Plus,  then enter the demo, maybe a refresh is needed.
3. if you look carefully, you will find there is a brief black screen before the whole page loaded
4. you can see the black screen every time you refresh

**Related code:**
just the demo can reproduce the bug

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.4
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.9.2
    OS         : macOS Sierra
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.9 
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is happening in that particular demo because the first page (the root) is being lazy loaded. Our current recommended setup is to not lazy load the first view, but lazy load all the other views. We will have more documentation around this soon.

**Comment by hellogithub2014** [comment]
@jgw96  I followed your recommendation, but still black screen.  What you said "the root" is the TabsPage or not?  Because what I had done is not lazy load the TabsPage
