### ISSUE TITLE
New getRootNavById returns NavigationContainer instead of NavController

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#12248]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
New method `getRootNavById` from app.ts which in feature should replace `getRootNav` returns `NavigationContainer`, but I think you wanted to return `NavController`, at this moment for example you can not use `setRoot('')` because it is not in `NaviagionContainer`.

![image](https://user-images.githubusercontent.com/3778892/27817711-d4d62a44-6092-11e7-8419-6bbb90953174.png)

If this is not a bug but as designed (which IMO it isn't), how should we call `setRoot` with the new router? In this case `getRootNavById` is not replacing `getRootNav` because they have another scope.

**Comment by danbucholtz** [comment]
I'll give this some thought and put out a patch release. A root nav could be both an `ion-tabs` (which is not a NavController) or an `ion-nav` (which is a NavController). WRT Tabs, `ion-tabs` is a container that holds `ion-tab`, and `ion-tab` is a NavController instance.

I think you ultimately want to call this method instead:
https://github.com/ionic-team/ionic/blob/master/src/components/app/app.ts#L211

Thanks,
Dan

**Comment by mburger81** [comment]
Okay I'll test tomorrow with `getActiveNavs(navId?: string) :)

From pure curiosity, the name "getActiveNavs" suggest IMO more to get the activeated nav to use for example in the menu, and not to get the wanted root nav where we can set a new Page.
Not sure if I explained well (sorry)

**Comment by danbucholtz** [comment]
You can get the root navs too. Active Nav will equal root Nav unless you're doing nested navs or a nav-then-tabs set-up.

Thanks,
Dan

**Comment by mburger81** [comment]
We have this scenario, we use nested navs for example like this: `http://localhost:8100/#/nav/n4/main/nav/n5/lt-node-settings`
As you can see there are two navs `n4` and `n5` and on an http `403` error we would set nav `n4` to the login page. But `this.appCtr.getActiveNavs()` is returning always only `n5` and if we do 
`this.appCtr.getActiveNavs('n4') ` this is also returning the nav of `n4`. This should be a bug, right?

`getRootNav` is deprectaed instead of `getRooNavById` but this is working and returns the right `n4` nav.
If we use `getRootNavBYId('n4')` on the returned object we can not setRoot.

Sorry if we misunderstood something and don't use the new rooter in the right way.

Thanks
Michael

**Comment by danbucholtz** [comment]
No, `getActiveNavs` gets the top nav for each root nav. Basically, it gets the furthest "leaf" or child most nav. Does that make sense? You can get the parent of a nav from that nav, or walk the tree from parent-to-child from `app.getRootNavs`

Thanks,
Dan

**Comment by mburger81** [comment]
Okay, so to redirect user from general auth provider we will use getRootNavs and setRoot there, if we would like to change page on actual nav we can use getActiveRootNavs. 

I suposed getActiveNavs returns the activatet navs in the "tree"  (n4, n5) 

I'll try it tomorrow

Thx a lot
Michael

**Comment by epetre** [comment]
It's very weird and confusing that the word root is used in so many ways when it should mean the top of the tree...

**Comment by danbucholtz** [comment]
@epetre,

It does mean the starting point of the tree. How else is it used? The change here was going from one root nav to potentially many. A real world use case would be in your `app.component.ts` having split-pane or something.

Thanks,
Dan

**Comment by epetre** [comment]
@danbucholtz Got it! Makes sense, thx.

**Comment by mburger81** [comment]
Sorry guys but as wrote some days ago, I think getRootNavs for us does not return the start of the tree. But no we are out of office and can not verify it. @epetre does it work for you?

**Comment by danbucholtz** [comment]
https://github.com/ionic-team/ionic/blob/master/src/components/app/app.ts#L236-L240,

https://github.com/ionic-team/ionic/blob/master/src/components/app/app.ts#L257-L264

https://github.com/ionic-team/ionic/blob/master/src/components/app/test/app.spec.ts#L315-L485

Thanks,
Dan

**Comment by danbucholtz** [comment]
This is fixed. We now return an `any` since it could be either an `ion-nav` or `ion-tabs`.

Thanks,
Dan

**Comment by dalezak** [comment]
@danbucholtz once you've found a `NavigationContainer` using `getRootNavById`, how do you `push` into it?

The only attribute which returns a `NavController` is `parent`, and that's returning a `null` for me.

https://github.com/ionic-team/ionic/blob/a8ceee467b1d83a74d875e2162732c31d72c566e/src/navigation/navigation-container.ts
