### ISSUE TITLE
Refresher and lists with click events don't play well with each other

### ISSUE THREAD

**Issue by mahnuh** [ionic-team/ionic#12247]
**Ionic version:**
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a ion-list with buttons and (click) and an ion-refresher. Pulling down to refresh just a little and pulling back up results in the list item being tapped. Releasing the tap the click event is fired.

**Expected behavior:**
When pulling down the refresher there should be no tap event on the list item.

**Steps to reproduce:**
Create a list with items and (click), add a refresher to the ion-content.

**Other information:**
I made a short video: http://sharedby.manuel-heidrich.com/kjwTe/2SagyfWV

**Ionic info:**

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : not installed
    npm        : 5.0.3
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Would you mind sharing a repo or plunker we could use to reproduce this, please?

**Comment by jgw96** [comment]
Also, from the video it looks like this was on an iOS device, does the same happen on an Android device?

**Comment by mahnuh** [comment]
Hi Justin,
unfortunately I do not have an Android device at hand, but I created a repo where I reproduced the described behaviour: https://github.com/mahnuh/ionic-issue-12247-demo

**Comment by jgw96** [comment]
Hello, thanks for sharing the repo (: I was not able to reproduce this issue on any of my android devices and after looking at your repo i noticed that you are not using our [wkwebview plugin](https://github.com/ionic-team/cordova-plugin-wkwebview-engine). UiWebView has notoriously buggy click and tap events which sounds like may be causing this issue. WKWebView fixes alot of these issues, so if you would mind installing that wk plugin and giving this another try that would be awesome.

**Comment by mahnuh** [comment]
Hi Justin,
tried the ionic wkwebview plugin but the issue remains. I also verified, if the app is really using the wkwebview.

**Comment by mahnuh** [comment]
Hi @jgw96 do you still need more information?

**Comment by tmvnk** [comment]
V3 label

**Comment by mahnuh** [comment]
Any news on this one?
