### ISSUE TITLE
how to change splash page   Dynamic

### ISSUE THREAD

**Issue by wangying11** [ionic-team/ionic#12257]
Ionic3.x
I want to change splash by http request ,how to do

**Comment by AmitMY** [comment]
- Please fill in the issue template fully
- This seems like a support request, please ask it in the forum

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
