### ISSUE TITLE
Feature : Toast Customize "Close" button behaviour

### ISSUE THREAD

**Issue by MohammadWaleed** [ionic-team/ionic#12256]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
when creating a toast can't give the button any handler
only can change the text

**Expected behavior:**
give the toast button a  custom handler other than just closing

**Related code:**

```
//Current
  let infoMessage = this.toastController.create({
            message:"Current toast",
            closeButtonText:"Close",
            position: 'bottom',
            showCloseButton: true
        });

//Proposed
  let infoMessage = this.toastController.create({
            message:"toast with custom button handler",
            buttonText:"Click Me",
            position: 'bottom',
            showCloseButton: true,
            buttonHandler: ()=>{console.log("Button Click");}
        });
```

**Other information:**
and change the name from close button to just button

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#266
