### ISSUE TITLE
lazy load of ionic3 tabs app  messed up at android and browser Back Button

### ISSUE THREAD

**Issue by hellogithub2014** [ionic-team/ionic#12253]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
While  switching pages 3 or more layers deeper， then click back button of android or browser, can not go back to the page previous visited.

**Expected behavior:**
go back to the page previous visited.

**Steps to reproduce:**
The bug repo is at [back-button-bug](https://github.com/hellogithub2014/back-button-bugs)
1.  start the project using `ionic serve`
2. go to the `contact` tab, then click the `go detail` button, then click the `go detail deeper` button
3. click the back button of android or browser, you will find that you can not go back to the page previous visited. More clearly, it should be the page where `go detail` button display.

**Other information:**
the back button works fine if you only view 1 or 2 layer。

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.4
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.9.2
    OS         : macOS Sierra
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.9
```

**Comment by hellogithub2014** [comment]
-----------update-------------
1. After I updated my ionic-angular to 3.5.0(I copied the package.json from [ionic-conference-app](https://github.com/ionic-team/ionic-conference-app) ), some of the above bugs were fixed.  Thanks for your guys' hard working! 
2. BUT there is one another bug I found:
The back button of page's behavior **does not**  consistent with the back button of browser's. The previous one often does not change the hash of url, but the latter one does.  So if you  use different button with different order, then bugs come out.


![image](https://user-images.githubusercontent.com/7734518/27856068-6205171a-619f-11e7-8a5a-6606eb722702.png)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind sharing a repo we could use to reproduce this issue?

**Comment by hellogithub2014** [comment]
this is the repo for bugs:[back-button-bugs](https://github.com/hellogithub2014/back-button-bugs).

**Comment by karansharma27** [comment]
Whats the status of this issue? I am facing the same issue. Android app's hardware back button is not in sync with navigation bar's back button. Its a major bug in my application. Please provide me a solution.

**Comment by karansharma27** [comment]
@hellogithub2014 Did you find any solution? I am facing the same issue.

**Comment by hellogithub2014** [comment]
@karansharma27  Yes, I found  why that happened. If you have two pages , A is lazy loaded, B is not. 
When you navigate to B from A, after a while you want go back to A,  you will find this issue. 
**THE SOLUTION** is make A and B both lazy loaded, that works for me.

**Comment by kensodemann** [comment]
Hello! Is this still an issue with the latest version of ionic and with the whole app being lazy loaded as @hellogithub2014 points out?

If so, can you please provide a sample application demonstrating your issue and I will be happy to repopen this.

 Thanks!
