### ISSUE TITLE
Disabled ion-toggle and ion-checkbox still changeable by pressing tab

### ISSUE THREAD

**Issue by digaus** [ionic-team/ionic#12254]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Toggle and checkbox can be used even when disabled by pressing tab... 

**Expected behavior:**
There should be no way to trigger the Toggle or checkbox when it is disabled

**Steps to reproduce:**
Create toggle and disable it. Press tab until toggle highlights blue, then you can change it with pressing enter.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15358538/27830208-a2450f0e-60c5-11e7-93a6-5e1257ba7cde.gif)

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-plugin-proxy : 1.3.1
    @ionic/cli-utils        : 1.4.0
    Cordova CLI             : 6.5.0
    Ionic CLI               : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 5.2.1 browser 4.1.0 ios 4.2.0 windows 4.4.3
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.6.1```

**Comment by AmitMY** [comment]
I understand why it happens on toggle, because there is no disabled check [here](https://github.com/ionic-team/ionic/blob/6dee17b89bafdae588d2bfbadf29c92e1440e08f/src/components/toggle/toggle.ts#L205), but no idea why it happens on checkbox. Do you have a clue?

**Comment by digaus** [comment]
@AmitMY 
Yes looks like the best way to check if it is disabled.
Same with checkbox here: https://github.com/ionic-team/ionic/blob/6dee17b89bafdae588d2bfbadf29c92e1440e08f/src/components/checkbox/checkbox.ts#L124
Altought I do not know why enter press is registered as a click event?

**Comment by AmitMY** [comment]
That is why I couldn't find it for checkbox.. I don't know why it registers like this. Especially, that click on disabled does not work, so it can not be the same function

**Comment by digaus** [comment]
@AmitMY 
I added the checks on the positions which I posted and it works now. Spacebar and enter are registered as click events it seems.

**Comment by AmitMY** [comment]
Ok cool. Mind making a PR?

**Comment by digaus** [comment]
Will try if I find the time. Also the normal input should also check if disabled or readonly. Otherwise one can change the input if you remove the disabled attribute via chrome developer tools.  Adding a check here: [onKeyDown](https://github.com/ionic-team/ionic/blob/master/src/components/input/input.ts#L432)
and here: [onInput](https://github.com/ionic-team/ionic/blob/master/src/components/input/input.ts#L397)
fixes this.
Now there is no way to change the data if it is disabled.

**Comment by digaus** [comment]
Toggle also needs a check here: [shouldToggle](https://github.com/ionic-team/ionic/blob/master/src/components/toggle/toggle.ts#L188)

**Comment by AmitMY** [comment]
Ok, so concluding there are a bunch of places to add a check in.
On input, is a bit different though, because if we add a `disabled` check there, I think DOM will show the new value, but input will have the disabled value stored, until further change detection kicks in. (it won't kick in here, because there is no change). Might need to `return false` on [`onKeydown`](https://github.com/ionic-team/ionic/blob/master/src/components/input/input.ts#L432)

**Comment by digaus** [comment]
@AmitMY 
I added an if else statement on input: 

```
onInput(ev: any) {
		if(!this._disabled && !this._readonly){
			this.value = ev.target.value;
			// TODO: deprecate this
			this.input.emit(ev);
		}else{
			this._inputUpdated();
		}
};
```
this calls this calls the inputUpdated function which triggers an update. Seems to work fine on my local tests.

**Comment by AmitMY** [comment]
Yep, that approach should work as well, setting the value on the element strictly and not waiting for angular's change detection cycle.
However, as it is "disabled", the "keyDown" event needs to be disabled, and not the update itself, really, plus it will avoid a DOM write so that is good.

I wonder what @manucorporat thinks of this issue in general, perhaps there is a place in the base class to fix this, however I couldn't find one that will also accept value change from code, just not from user.

**Comment by digaus** [comment]
I also disabled the onKeydown event but it is only needed when _clearOnEdit is set:
```
onKeydown(ev: any) {
if (ev && this._clearOnEdit && !this._disabled && !this._readonly) {
            this.checkClearOnEdit(ev.target.value);
        }
}
```

**Comment by AmitMY** [comment]
Oh tiny misunderstanding, I meant to add there something like:
```
if(this._disabled) {
  ev.preventDefault();
  return false;
}
```

Which stops the event altogether

**Comment by digaus** [comment]
Yeah that seems better. ALso noticed button is not checked but dont know where to include that since it just uses angulars stuff? Any idea?

**Comment by AmitMY** [comment]
Sorry which button?

**Comment by digaus** [comment]
The normal button. If you remove the disabled attribute via chrome you can click it and it is not checked again.

**Comment by AmitMY** [comment]
oh ok. In v3, that is strictly angular's property, so it is possible this is how they want it, or it is a bug that needs addressing.
In v4 however, it is planned to move to `ion-button` instead, and when that happens we can talk about adding the check because that property will be ionic's
