### ISSUE TITLE
App on iPad flashed back after running 10 days

### ISSUE THREAD

**Issue by Sunny-Kid** [ionic-team/ionic#12259]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I‘ve runned the `ionic cordova build ios` and use the XCode to install the app on iPad , but after runing 10 days , it flashed back and when I open it again , it flashed once again. But after i reinstall this app , this problem doesn't exist
**Expected behavior:**

This app doesn't flash back 
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by AmitMY** [comment]
- Can you please fill in your `ionic info`?
- What do you mean by "flashed back"?

**Comment by Sunny-Kid** [comment]
1.**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
my iPad IOS version 10.1.1
```
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.0
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : ios 4.3.1
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : not installed

```
2."flashed back" means crash in splash screen
Thank you for your reply

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/]. Thanks for using Ionic!
