### ISSUE TITLE
Ionic does not properly follow material design for forms in android

### ISSUE THREAD

**Issue by fabiocarneiro** [ionic-team/ionic#12262]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The material design styling for form is not adhering to the specification. The guidelines say that inputs are expacted to have a **Input line** as part of the layout, but ionic is using the `ion-item` separator as a hack. This cause weird errors and inconsistencies as it can be observed in https://ionicframework.com/docs/components/#inset-labels:

- No line for the password input
- User input starts in the middle of the textfield. 

All the other examples are missing the margin in the right side.

**Expected behavior:**

- Margin on both sides of the line (works properly only on inset labels example)
- Input line in all the inputs
- Drop support to inset labels in material version. The label always should go to the top or start already there.

**Steps to reproduce:**

Reproduce-able by observing the examples in ionic docs

**Other information:**

Two examples on how the forms should look like

| <img src="https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B5ZSepuCX1xOV21vLWJFeUFoUXc/required_example.png" width=300> | <img src="https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B5ZSepuCX1xOM3NVblRxVVc3T3M/full_width1.png" width=300> |
|:---:|:---:|
| Regular form | Full-width field form |

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We will look into this!

**Comment by fabiocarneiro** [comment]
Any progress?
