### ISSUE TITLE
error npm install --save @ionic-native/device

### ISSUE THREAD

**Issue by wardenlzr** [ionic-team/ionic#12261]
npm install --save @ionic-native/device
ionic-hello-world@ D:\Work\Code_NJYDZF\MobileApp
+-- @ionic-native/device@3.13.1
`-- UNMET PEER DEPENDENCY @ionic/app-scripts@1.3.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (cu
rrent: {"os":"win32","arch":"x64"})
npm WARN @ionic/cli-plugin-ionic-angular@1.3.1 requires a peer of @ionic/app-scripts@^1.3.7 but none was installed.

ionic info

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.0.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.0
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.0.0

System:

    Node       : v7.9.0
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.2.0

how to solve?please?

**Comment by wardenlzr** [comment]
npm install --save @ionic-native/device
ionic-hello-world@ D:\Work\Code_NJYDZF\MobileApp
+-- @ionic-native/device@3.13.1
`-- UNMET PEER DEPENDENCY @ionic/app-scripts@1.3.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (cu
rrent: {"os":"win32","arch":"x64"})
npm WARN @ionic/cli-plugin-ionic-angular@1.3.1 requires a peer of @ionic/app-scripts@^1.3.7 but none was installed.

**Comment by wardenlzr** [comment]
UNMET PEER DEPENDENCY @ionic/app-scripts@1.3.0

**Comment by wardenlzr** [comment]
UNMET PEER DEPENDENCY @ ionic/app-scripts @ 1.3.0

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
