### ISSUE TITLE
NavController stuck isTransitioning() true after insert/remove view

### ISSUE THREAD

**Issue by jamesgroat** [ionic-team/ionic#12267]
**Ionic version:**  (check one with "x")
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
Inserting or removing a view other than the active view does not require a transition and navcontroller incorrectly sets itself to isTransitioning() true.

**Expected behavior:**
Insert or remove a view should leave transitioning false and allow further navigation like pop() etc.

**Steps to reproduce:**
http://plnkr.co/edit/uvcyfZociUQHtizSLiyA?p=preview

I am submitting a PR to fix.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us and thanks for the PR! We will be reviewing this shortly.

**Comment by danbucholtz** [comment]
Can you test `nightly`? I think this is fixed.

```
npm install ionic-angular@nightly
```

Thanks,
Dan

**Comment by jamesgroat** [comment]
Sure -- do you know which commit fixed it?

**Comment by jamesgroat** [comment]
Yes works in nightly. Seems like 48b3243689cc728fcce566b6fc32ab6f134db046 fixed it.
