### ISSUE TITLE
$event.target is unavailable from the (ionBlur) event

### ISSUE THREAD

**Issue by youssmak** [ionic-team/ionic#12264]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
$event.target is undefined since i have changed the (blur) deprecated event by (ionBlur) event in my template
**Expected behavior:**
$event.target property should be available

**Steps to reproduce:**

**Related code:**

```
<ion-input (blur)="onBlur($event)"></ion-input>
```

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this.

**Comment by playuntildark** [comment]
Same issue with 3.6.0. Please fix!

**Comment by jcviau** [comment]
Same issue with ionFocus and ionic-angular version 3.6.1

**Comment by leegee** [comment]
Still an issue with 3.19.0

**Comment by KevinKelchen** [comment]
The event type change from `blur` to `ionBlur` for `ion-input` seems to have resulted in the `$event` value passed from the template changing from the native event object to an Ionic [`TextInput`](https://github.com/ionic-team/ionic/blob/fed4fd95d2545c324c45d891b837e2bcc4ded79d/src/components/input/input.ts#L144).

I still found a way to access the blur event target but it's probably not the wisest approach.

Old way with `blur`:

```html
<ion-input (blur)="onChange($event)">
```

```typescript
onChange(event: FocusEvent) {
  const eventTarget = event.target;
}
```

New way with `ionBlur`:

```html
<ion-input (ionBlur)="onChange($event)">
```

```typescript
onChange(textInput: TextInput) {
  const eventTarget = textInput._native.nativeElement;
}
```

In the `ionBlur` scenario, the `_native` property is [labeled with a `@hidden` comment](https://github.com/ionic-team/ionic/blob/fed4fd95d2545c324c45d891b837e2bcc4ded79d/src/components/input/input.ts#L209) and it's excluded from the [docs](https://ionicframework.com/docs/api/components/input/Input/), so it's probably not considered part of the public API contract.

Would appreciate guidance on a recommended way to access the blur event target! 😃 

Thank you!

**Comment by tperrelli** [comment]
If you want to use $event.target.select() to select all input text, this way will not work in device.
Instead of it, try something like this:

https://gist.github.com/tperrelli/fd17c2fe95c8b17b460b15e80687f9f6

**Comment by diegovallarta** [comment]
Hi,

Just use the event on scope inside the callback

`<ion-input (ionBlur)="onChange(some.data)">`

`onChange(data) {
       const eventTarget = event.target;
}`
