### ISSUE TITLE
Error: Build Android :(

### ISSUE THREAD

**Issue by rhernandez-itemsoft** [ionic-team/ionic#12265]
Help me please,
I can't build for android on Ubuntu 16 :S

![captura de pantalla de 2017-07-05 15-22-06](https://user-images.githubusercontent.com/4327356/27883499-454ade60-6196-11e7-8c3c-a9abd7c0008b.png)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
