### ISSUE TITLE
Ion toggle button insid ion slides android bug

### ISSUE THREAD

**Issue by BDominik** [ionic-team/ionic#12260]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On android device.
When I'm using an ion-toggle inside ion-slides, and clicking on the toggle, then the slide event also fired.
So its just sliding to the next or the previous screen.

**Expected behavior:**
To stay at the current slide after clicking on ion slide.
**Steps to reproduce:**

```
<ion-slides>
			<ion-slide>
				<p>Page 1 </p>
			</ion-slide>
			<ion-slide>
				<ion-toggle [(ngModel)]="toggleMe"></ion-toggle>
				<p>Page 2</p>
			</ion-slide>
			<ion-slide>
				<p>Page 3</p>
			</ion-slide>
		</ion-slides>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by RapidWorks** [comment]
Adding stopPropagation in ToggleGesture seems to fix this. 
`
    ToggleGesture.prototype.onDragStart = function (ev) {
        ev.preventDefault();
        ev.stopPropagation();
        this.toggle._onDragStart(pointerCoord(ev).x);
    };`

Adding it anywhere in the code works too (as a quick fix).

**Comment by RapidWorks** [comment]
Stopping propagation in ToggleGesture seems to fix this

` ToggleGesture.prototype.onDragStart = function ( ev) {
        // console.log( "Slide event tyle " + event.type );
        ev.preventDefault();
        ev.stopPropagation();
        this.toggle._onDragStart(pointerCoord(ev).x);
    };`

**Comment by surajrao** [comment]
This is still present in Ionic v3.9.2
