### ISSUE TITLE
Allow hooking into an 'app exit' (similar to `ionCanLeave` but for the app as a whole)

### ISSUE THREAD

**Issue by fiznool** [ionic-team/ionic#12275]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

It's difficult to detect when the app is about to exit (typically when an Android user presses the 'back' hardware button at a root nav page). Apps may want to intercept this and present an alert box to confirm quitting the app.

This can be somewhat achieved today by taking advantage of the `registerBackButtonAction` method on the `Platform` class, but the difficulty is knowing whether the app is in a state where it should quit the app (should not have menu open, not be showing any modals, alerts, action sheets, etc and also be at the root page level). Another issue here is that when overriding the default back button action, you can't call through to the default handler if you somehow did work out that the app should not be exited yet.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    npm        : 5.0.3
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#269
