### ISSUE TITLE
this.user is not filled after auth.signup 

### ISSUE THREAD

**Issue by raugaral** [ionic-team/ionic#12271]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After register a new user using auth.signup the object user is not filled.

**Expected behavior:**
As described in the docs,  the object user should be filled with the registered user
https://docs.ionic.io/services/auth/#signup

**Steps to reproduce:**

>  this.auth.signup(this.registerData.value).then(() => {
>       console.log('>> After Register', this.user); // this.user.id is empty
>       this.auth.login('basic', this.registerData.value).then(() => {
>         console.log('>> After Login', this.user); // this.user.id is filled
>         this.navCtrl.setRoot(RegisterLegalPage);
>       });
>    }

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

> 
> global packages:
> 
>     @ionic/cli-utils : 1.4.0
>     Cordova CLI      : 7.0.1 
>     Ionic CLI        : 3.4.0
> 
> local packages:
> 
>     @ionic/app-scripts              : 1.3.12
>     @ionic/cli-plugin-cordova       : 1.4.0
>     @ionic/cli-plugin-ionic-angular : 1.3.1
>     Cordova Platforms               : android 6.2.3 ios 4.3.1
>     Ionic Framework                 : ionic-angular 3.5.0
> 
> System:
> 
>     Node       : v6.11.0
>     OS         : Linux 4.10
>     Xcode      : not installed
>     ios-deploy : not installed
>     ios-sim    : not installed
>     npm        : 3.10.10 
>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
