### ISSUE TITLE
ionic generate class

### ISSUE THREAD

**Issue by KyDenZ** [ionic-team/ionic#12272]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Unable to generate class with command line, no files created

**Expected behavior:**
Generate a class automatically

**Steps to reproduce:**
In terminal : ionic generate class user

`[OK] Generated a class named user!`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#268

**Comment by RenaldasK** [comment]
The link is dead and the feature is not yet available.
