### ISSUE TITLE
Ionic datetime not allowing correct ISO8601 to be passed

### ISSUE THREAD

**Issue by digaus** [ionic-team/ionic#12273]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The datetime component does not recognize ISO8601 conform datetime string. The ISO8601 allows the fraction of seconds to be 1 or more digits longer however Ionic is only allowing 3 digits!

>  s    = one or more digits representing a decimal fraction of a second

**Expected behavior:**
ISO8601 datetime should be accepted. The solution is to change the regex to allow 1 or more digits:

```
const ISO_8601_REGEXP = /^(\d{4}|[+\-]\d{6})(?:-(\d{2})(?:-(\d{2}))?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(?:\.(\d{1,}))?)?(?:(Z)|([+\-])(\d{2})(?::(\d{2}))?)?)?$/;
const TIME_REGEXP = /^((\d{2}):(\d{2})(?::(\d{2})(?:\.(\d{1,}))?)?(?:(Z)|([+\-])(\d{2})(?::(\d{2}))?)?)?$/;
```

**Steps to reproduce:**
Create datetime with this ISO8601 string: 2015-07-23T12:55:11.70

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-plugin-proxy : 1.3.1
    @ionic/cli-utils        : 1.4.0
    Cordova CLI             : 6.5.0
    Ionic CLI               : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 5.2.1 browser 4.1.0 ios 4.2.0 windows 4.4.3
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.10.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.6.1

```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by wbhob** [comment]
If you know the solution, please open a PR! The Ionic community would really appreciate it. Thanks for your contribution!
