### ISSUE TITLE
ion-segment: (ionSelect) callback is fired before the ngModel is updated

### ISSUE THREAD

**Issue by bogomips** [ionic-team/ionic#12276]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The (ionSelect) callback is fired before the ngModel is updated, so from the callback I read the previous value unless I introduce a delay.

**Expected behavior:**
The callback should be fired after the ngModel is updated

```
 <ion-segment [(ngModel)]="carType" color="secondary">
            <ion-segment-button value="electric" (ionSelect)="selectCarType()" >
                <ion-icon name="home"></ion-icon>
            </ion-segment-button>
            <ion-segment-button value="fuel" (ionSelect)="selectCarType()" >
                <ion-icon name="car"></ion-icon>
            </ion-segment-button>
        </ion-segment>

controller

  selectCarType() {
        setTimeout(()=> {
            console.log(this.carType);
        },100);
    }

```

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2 browser 4.1.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v7.7.1
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.1.2 

```

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this.

**Comment by wbhob** [comment]
That seems like an uncommon usage of the segment. From a UX perspective, you have 2 options: 

1. use radios
2. if you insist on using a segment, `(ionSelect)` should have the function `selectCarType('electric')` and update the value like that. To my knowledge, segment is not a form element, so you will have to use the method aforementioned. Then, your function should look like this:

```
selectCarType(type:string) {
this.carType=type
}
