### ISSUE TITLE
Tabs: after nav.push() I have to click 2 times on the tab's icon

### ISSUE THREAD

**Issue by bogomips** [ionic-team/ionic#12274]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Hello, 
I have a page with tabs, the first tab has links, by clicking one on them I change the page by using
nav.push() (the tabs bar remains visible)
When i click on the first tab's icon, the first time ionic reloads exactly the same page (the one I opened with push), the second time it finally goes to the original tab.

**Expected behavior:**
I expect to return immediately to the right tab

**Other information:**
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2 browser 4.1.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v7.7.1
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.1.2

**Comment by jgw96** [comment]
Thanks for opening an issue with us, would you mind sharing a minimal repo we can use to reproduce this issue?

**Comment by bogomips** [comment]
I discovered the source of the problem.
When I push a page, starting from a tab, I don't want the tab I start from remains highlighted, 
I think it is misleading for the user so the all tabs should be "off" 

I achieved the result by the following line:
this.navCtrl.parent._tabs[0].isSelected=false;

This introduces the problem...
Can you advice for the correct way to achieve the goal, without breaking things?

Thanks!

**Comment by jgw96** [comment]
As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/]. Thanks for using Ionic!
