### ISSUE TITLE
Unit tests by default

### ISSUE THREAD

**Issue by renatoalencar** [ionic-team/ionic#12277]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Not implemented

**Expected behavior:**
Well, Angular framework supports unit test by default. Why in Ionic just have to run several commands, write configuration files and install many npm packages to just run a simple thing like unit tests? Thanks.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by AmitMY** [comment]
Thanks for opening an issue.
Can you please fill out the template for new issues?

**Comment by renatoalencar** [comment]
Right, just made it

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by demsey2** [comment]
could anyone confirm when we can expect the next release?

**Comment by AmitMY** [comment]
@demsey2 This is not the right place for a question like this, next time please try the forum.
Usually, there is a release every 2 weeks on Wednesday, and a patch release the day after if major issues were discovered.
If something was implemented on master, and you want to use it, make sure there is a nightly build for it by `npm view` of the package, and install the nightly you desire.
