### ISSUE TITLE
Packaging is fast,Special slowly into the APP

### ISSUE THREAD

**Issue by wardenlzr** [ionic-team/ionic#12270]
Packaging is fast,Special slowly into the APP
I have used --prod  
How can I solve?

ionic info

global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v7.9.0
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.2.0

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/_). Thanks for using Ionic!

**Comment by wardenlzr** [comment]
Thank you, I think I found the reason is I cordova version 6.0.0
