### ISSUE TITLE
Problems with duplicate inclusion of ionicons package in ionic-angular

### ISSUE THREAD

**Issue by sinedied** [ionic-team/ionic#12284]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using package `ionic-angular@3.5.0`, there is a problematic duplicate inclusion of `ionicons`:

- `ionicons` are included in `ionic-angular`, which is a non-sense since it is available as a separate package (and ionic starters use the `ionicons` package)

- At the end of the file `theme/ionic.components.scss`, this forces the inclusion of the `ionicons` version built-in `ionic-angular`:
```scss
[..]
// Fonts
// --------------------------------------------------
@import
"../fonts/ionicons",
[...]
```
But the referenced file does not compile properly outside `ionic-cli` builds, since it references other files assuming their paths are within sass include paths:
```scss
// inside fonts/ionicons.scss
[...]
@import "ionicons-icons"; // <- breaks bulild
@import "ionicons-variables"; // <- breaks build
```

If I comment the offending line in `theme/ionic.components.scss` and properly include `ionicons` using `@import "~ionicons/dist/scss/ionicons";` it works as expected.

**Expected behavior:**
At least the file `theme/ionic.components.scss` should not contains any `ionicons` reference, at best `ionicons` should be removed completely from `ionic-angular`.

**Steps to reproduce:**
`npm install ionic-angular`
Try to build an app including `ionic-angular` scss without any special `sassIncludePaths` setting.

I use `angular-cli` for example.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

global packages:

    @ionic/cli-plugin-proxy : 1.3.1
    @ionic/cli-utils        : 1.4.0
    Ionic CLI               : 3.4.0

System:

    Node       : v7.9.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.4 
    npm        : 4.2.0 
```

**Comment by AmitMY** [comment]
"Best" solution can not happen in my opinion, as then `icon` will be meaningless, so `< Back` won't show the icon, and tabs won't show the icon. I do however understand that it is indeed silly to include in both places, and so I think it should only be included from `ionic-angular`. But I am not sure if there is no reason for this, so we'll wait for someone to comment if there is.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! At this time because `ionic-angular` and how it works is so tied to our `ionic cli` we cannot provide official support for using the angular cli or custom builds to build ionic-angular apps. But we do have awesome communities on our [forum](https://forum.ionicframework.com) and our [slack channel](https://ionicworldwide.herokuapp.com/] that can provide support for this . Thanks for using Ionic!

**Comment by sinedied** [comment]
@jgw96 Then why bother publishing an npm package? Even when using `ionic-cli`, do you find it normal that `ionic-angular` embeds the contents of the `ionicons` package? O_o

**Comment by AmitMY** [comment]
That module develops independently of the main ionic core, and is a dependency of this module. It is separate, and not a sub module, so people can use `ionicons` independently of ionic.

**Comment by sinedied** [comment]
@AmitMY In that case, which include the `ionicons` package in all ionic starters?

In any case, an npm package like this should not assume anything regarding how the scss include folders are configured for the build, especially considering the problems is only 1-line, and the `ionicons` package itself has no issues whatsoever.

**Comment by sinedied** [comment]
This is even more fun that what I thought: `ionic-angular` includes the fonts and the file `ionicons.scss` as duplicate of `ionicons` package, but cannot build without the `ionicons` package because it's missing `ionicons-icons.scss` and `ionicons-variables.scss`.

So 2 possible fixes here, either:
- include `ionicons` properly in `ionic-angular` so it can build properly without the `ionicons package`, if it was really your intention to do this
- remove `ionicons` reference in `ionic-angular` and keep the 2 packages separate

Either way @jgw96 this has noting related to `ionic-cli` here.

**Comment by AmitMY** [comment]
This is quite messy. You are saying you can't build because of this? because I don't see an error or reproduction, just info. 
Can you please supply a reproduction repo if that is the case?

**Comment by sinedied** [comment]
Here is a repo to reproduce the issue: https://github.com/sinedied/ionic-build-issue
Steps:
1. clone the repo
2. `npm install`
3. `npm run build`
See `src/main.css` for the inclusion of `~ionic-angular/theme/ionic.components` that's causing the issue

**Comment by AmitMY** [comment]
@jgw96 Please reopen, this seems like a problem. Might be because this was generated with angular-cli and not ionic's

**Comment by FOAPP** [comment]
This is still an issue.  I am using ngx-rocket, and when building with ionic (per the TUI client provided with ngx extending angular-cli), and it took a stupid amount of searching to identify what was really going on.

**Comment by andreyradkevich** [comment]
**npm install ionicons --save** here is a solving

**Comment by sinedied** [comment]
@andreyradkevich This does not solve the duplication issue at all, please look at the first post.
