### ISSUE TITLE
perf: Back navigation in android doesn't work

### ISSUE THREAD

**Issue by ezzuah86** [ionic-team/ionic#12289]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>when you navigate to a different page and you have the back button, when you click on back it doesn't take you back on Android but it works on IOS. i tested the android on chrome and on device and its having the same issue</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
