### ISSUE TITLE
TextInput.setFocus doesn't work

### ISSUE THREAD

**Issue by ammulder** [ionic-team/ionic#12288]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

This problem appears in v3.4.2 and v3.5.0 but not v3.3.0 or v3.4.0

Controller Code:
```
@ViewChild('LoginUsername') usernameInput:TextInput;
...
ngAfterViewInit(): void {
  this.usernameInput.setFocus();
}
```
Behavior: The username input takes the focus, and then immediately loses the focus.  You can see one flash of the cursor and then it's gone again.  Putting the setFocus() in a setTimeout() doesn't work for me for delays of 0-350ms, but works OK for a delay of 1000ms -- though that is not acceptable in practice.

**Expected behavior:**

In v3.3.0 and v3.4.0 with the code as above, the text field takes the focus and keeps it.

**Steps to reproduce:**

**Related code:**

See above

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 3.4.0

System:

    Node       : v6.11.0
    OS         : OS X El Capitan
    Xcode      : Xcode 8.2.1 Build version 8C1002
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10
```
(as indicated, attempted in ionic-angular 3.3.0, 3.4.0, 3.4.2, 3.5.0 with the rest the same)

**Comment by AmitMY** [comment]
Is this in browser or device?
If this is on device, this is the current state of things: (from https://github.com/ionic-team/ionic/issues/11453)

> Unfortunately this is likely an unfixable issue. Input.focus() only works if called inside an stack initiated by a touch/mouse/keyboard event.
> 
> It is known limitation of WK and UIWebView.

If this is in browser, please create a plunker showing the issue, as I manage to use `setFocus` just fine on 3.4.2

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by buszito** [comment]
```

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : ios 4.5.3
    Ionic Framework    : ionic-angular 3.9.2
```


setFocus() still doesn't work in this case:

```
ionViewDidEnter()
  {
    setTimeout(() => {
      this.inputToFocus1.setFocus();
    },200)
  } 
```

But it works when I fire it from the button
