### ISSUE TITLE
popTo method signature is different from implementation

### ISSUE THREAD

**Issue by zakton5** [ionic-team/ionic#12287]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
When calling `nav.popTo`, the intellisense leads me to believe that the signature is this: `popTo(page: Page | string | ViewController, params?: any, opts?: NavOptions, done?: Function)`, which is found in `nav-controller.ts` on line 477 (master branch), but the actual implementation is in `nav-controller-base.ts` on line 116 as `popTo(indexOrViewCtrl: any, opts?: NavOptions, done?: () => void)`.

Calling popTo and passing animation parameters like `popTo(MyPage, null, { animate: false })` results in errors, of course. The quick fix is to ignore intellisense and call it like `popTo(MyPage,  { animate: false })` 

**Expected behavior:**
I expect the signature and implementation to match. The abstract class signature needs to be changed to match the implementation.

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this.

**Comment by jgw96** [comment]
We just figured this out. There is an issue in our docs, which is causing the IntelliSense to be wrong here and are pushing a fix for that as we speak. This will make it into the next release. Thanks!
