### ISSUE TITLE
custom font issue ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by ajaysaini95700** [ionic-team/ionic#12296]
i have added all font file inside src/assets/fonts/**. and use these file in app.scss like
@font-face {
    font-family: 'myfont';
    src: url('./assets/fonts/myfont.eot');
    src: url('./assets/fonts/myfont.eot') format('embedded-opentype'), url('./assets/fonts/myfont.woff') format('woff'), url('./assets/fonts/myfont.ttf') format('truetype'), url('./assets/fonts/myfont.svg#myfont') format('svg');
}

* {
    font-family: 'myfont' !important;
}
 when i run app then these file also added in www/assets/fonts/**. but it is showing error http://localhost:8100/build/assets/fonts/myfont.ttf ERR_FILE_NOT_FOUND
http://localhost:8100/build/assets/fonts/myfont.woff  ERR_FILE_NOT_FOUND

why ?

**Comment by AmitMY** [comment]
Thanks for opening an issue.
Can you please fill out the template for new issues?
You need `../assets`, as the assets are located outside of the `build` folder

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by ajaysaini95700** [comment]
Thanks now working fine

On Jul 9, 2017 8:48 PM, "Amit Moryossef" <notifications@github.com> wrote:

Thanks for opening an issue.
Can you please fill out the template for new issues?
You need ../assets, as the assets are located outside of the build folder

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ionic-team/ionic/issues/12296#issuecomment-313926119>,
or mute the thread
