### ISSUE TITLE
Why gesture api page is not found?

### ISSUE THREAD

**Issue by moh3n9595** [ionic-team/ionic#12295]
hi, I want check gestures and know about swipe more, but this page is not there! why?
[Previous link](https://ionicframework.com/docs/v2/api/components/gestures/Gesture/) :
`https://ionicframework.com/docs/v2/api/components/gestures/Gesture/`

**Comment by AmitMY** [comment]
Thanks for opening an issue.
Can you please fill out the template for new issues?
What is the link that got you there?

**Comment by moh3n9595** [comment]
@AmitMY , It's about gestures and events like `tap,swipe,longpress` and so on

**Comment by Sampath-Lokuge** [comment]
See here: https://ionicframework.com/docs/components/#gestures

**Comment by wbhob** [comment]
Close this?

**Comment by AmitMY** [comment]
@wbhob Still don't know how they got to that link, probably a broken link somewhere, gotta find and fix.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-site#1185
