### ISSUE TITLE
perf: Ionic 2 : ngFor get slow to load

### ISSUE THREAD

**Issue by yhugow** [ionic-team/ionic#12298]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi!
I build a simple mobile application. 
It has too many array data almost 350 data inside of an array.
I create two pages home.html and words.html 
I load all data in words.html using ngFor.
From home.html go to words.html page it gets delay 2s to display.
Take not i use "ngFor". 
Platform i use ASUS Zenfone max.
Please help, I not sure if its the data or the android phone.</span>

<span is-issue-template></span>

**Comment by ACEsLegendary** [comment]
why not try use VirtualScroll instead?

**Comment by AmitMY** [comment]
Thanks for opening an issue.
- Can you please fill out the template for new issues?
- As @ACEsLegendary said, virtual scroll, although quite buggy, can help you a lot. There is an open PR with amazing amount of changes, so I count on it being fixed soon

**Comment by JustasKuizinas** [comment]
@ACEsLegendary VirtualScroll is has to many bugs and is not ready for production yet

**Comment by AmitMY** [comment]
@JustasKuizinas If you tread lightly, you can get it to work. I use it myself in several places, in my apps, that work just fine, by I too know that it is complicated to get it right. https://github.com/ionic-team/ionic/pull/12194 will fix many of the annoying constraints. So I think they should be able to work with Virtual Scroll, as there is no other way to unload the DOM from all of these items..

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
