### ISSUE TITLE
Proposal: Allow divs as thumbnails

### ISSUE THREAD

**Issue by mzealey** [ionic-team/ionic#12292]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently you need to specify `<img>` under an `<ion-thumbnail>` in a list. This is a bit annoying as you loose a bit of flexability with the CSS eg cannot do a cover image. I suggest adding something roughly equivelent to the following code so that you can do eg cover backgrounds and nice image sizing preserving ratios where the backend does not produce nice 80x80 crops:

```
ion-thumbnail .img {
    width: $item-md-thumbnail-size;
    height: $item-md-thumbnail-size;
    background-position: 50% 50%;
    background-size: cover;
}
```

```
<ion-thumbnail item-start>
    <div class="img" [style.background-image]="'url(' + img.url + ')'"></div>
</ion-thumbnail>
```

**Comment by wbhob** [comment]
Have you tried setting a background image on the actual thumbnail?

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!
