### ISSUE TITLE
Include a verbose output when running Cordova commands via the Ionic CLI

### ISSUE THREAD

**Issue by kelvindart** [ionic-team/ionic#12299]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
At the moment, when running `ionic cordova prepare` you get a detailed overview of the Ionic build steps which is great! However, Cordova states `Running command`, which contains a lack of information if you have many and/or large plugins to install.

The current output is as follows:

![ionic cordova prepare](https://media.giphy.com/media/l4FGA7F8rIO4jI4tq/giphy.gif)

**Expected behavior:**
It would be great to expand this so you have a detailed view of `cordova prepare` similar to when you run it raw (not via the Ionic CLI). If this is by design, maybe a `--verbose` option would be great.

I.e. to see the same output as `cordova prepare`:

![cordova prepare](https://media.giphy.com/media/l4FGDVzSJpLgDyNaM/giphy.gif)

**Steps to reproduce:**
1. Start a new project `ionic start myApp blank && cd myApp`
2. Run `ionic cordova prepare` and observe.
3. Remove platforms/plugins `sudo rm -r pl*`
4. Run `cordova prepare`.
5. Observe the differences in output.

**Related code:**
N/A

**Other information:**
N/A

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 2.0.0
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 4.2.0
```

**Comment by wbhob** [comment]
Run with the `--verbose` flag

**Comment by kelvindart** [comment]
@wbhob - I was not aware a `--verbose` flag existed. However, this still does not output the `cordova` command information.

**Comment by wbhob** [comment]
Seemingly, the cordova output comes after it completes.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2508
