### ISSUE TITLE
Ion-slidesde's ionSlideDoubleTap and ionSlideTap events

### ISSUE THREAD

**Issue by jsercao** [ionic-team/ionic#12291]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I bind the ionSlideDoubleTap () event and the ionSlideTap () event on the ion-slides,the result is always perform ionSlideTap ()  event twice, and then execute ionSlideDoubleTap () event once.

**Expected behavior:**
When I ` double taps` on the slide's container, execute the `ionSlideDoubleTap () `event,
When I  `taps/clicks` on the slide's container, execute the `ionSlideTap ()` event

**Steps to reproduce:**
Run the related code where lazy loading is used in the project.

**Related code:**

```
  <ion-slides #Slides *ngIf="slideData.length>0"  pager loop autoplay=3000 autoplayDisableOnInteraction=false
    (ionSlideDoubleTap)="ionSlideDoubleTap()" 
    (ionSlideTap)="ionSlideTap()">
    <ion-slide tappable *ngFor="let slide of slideData">
      <div class="swiper-zoom-container">
        <img [src]="slide.iconUrl" />
      </div>
    </ion-slide>
  </ion-slides>
```

```
  ionSlideDoubleTap() {
    console.log('do something DoubleTap')
  }
  
  ionSlideTap() {
    console.log('do something Tap')
  }
```

**Other information:**

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.9.4
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

```

**Comment by jsercao** [comment]
I suspend the use of these two methods, but can't we use the two method? Or there are other considerations?

**Comment by yanglongji** [comment]
true.
please add the interval of two clicks to judge doubletap or tap....
