### ISSUE TITLE
Middle toast not closing 

### ISSUE THREAD

**Issue by praveenandpraveen** [ionic-team/ionic#12293]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a bug report

**Current behavior:**

ionic toast not closing automatically.

**html code:**
`<ion-content padding>
  <button ion-button block (click)="showToast('top')">Show Toast Top Position</button>
  <button ion-button block (click)="showToast('middle')">Show Toast Middle Position</button>
  <button ion-button block (click)="showToast('bottom')">Show Toast Bottom Position</button>
  <button ion-button block (click)="showLongToast()">Show Long Toast</button>
  <button ion-button block (click)="showToastWithCloseButton()">Show Toast W/ Close Button</button>
</ion-content>`

**ts code**
`import { Component } from '@angular/core';

import { ToastController } from 'ionic-angular';

@Component({
  templateUrl: 'template.html'
})
export class BasicPage {
  constructor(public toastCtrl: ToastController) { }

  showToast(position: string) {
    let toast = this.toastCtrl.create({
      message: 'Mmmm, buttered toast',
      duration: 2000,
      position: position
    });

    toast.present(toast);
  }

  showToastWithCloseButton() {
    const toast = this.toastCtrl.create({
      message: 'Your files were successfully saved',
      showCloseButton: true,
      closeButtonText: 'Ok'
    });
    toast.present();
  }

  showLongToast() {
    let toast = this.toastCtrl.create({
      message: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea voluptatibus quibusdam eum nihil optio, ullam accusamus magni, nobis suscipit reprehenderit, sequi quam amet impedit. Accusamus dolorem voluptates laborum dolor obcaecati.',
      duration: 2000,
    });
    toast.present();
  }
}
`

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova   : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.0

**Comment by praveenandpraveen** [comment]
![toast](https://user-images.githubusercontent.com/29179199/27985689-45ce7ce2-640d-11e7-810c-54ac71e87919.png)

**Comment by wbhob** [comment]
toast.present doesn't take arguments, but you passed in `toast.present(toast)`. Also, pleasepleasepleaseplease format your code next time

**Comment by jgw96** [comment]
Hello thanks for using Ionic! This was fixed in `ionic-angular` 3.5.1, would you mind updating to that version and giving this another try?

**Comment by yurik94** [comment]
Same bug (@3.5.0).. Gonna check 3.5.1 👍

**Comment by yurik94** [comment]
@jgw96 How can I update to 3.5.1 ?

**Comment by jgw96** [comment]
Hello @yurik94 , you can update to the latest by following the changelog here https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#352-2017-07-13

**Comment by yurik94** [comment]
Got it, thanks

Il 14 lug 2017 17:31, "Justin Willis" <notifications@github.com> ha scritto:

**Comment by jgw96** [comment]
@yurik94 , is this issue still happening?

**Comment by praveenandpraveen** [comment]
issue not happening in 3.5.2 and above  version .
please add chip and spinner components in ionic documents (in component section )

**Comment by yurik94** [comment]
Seems working perfectly on 3.5.3 😀

Il 17 lug 2017 18:24, "Justin Willis" <notifications@github.com> ha scritto:

**Comment by jgw96** [comment]
Awesome, very glad to hear its fixed 😃 . @praveenandpraveen , site issues should be opened on the [site repo](https://github.com/ionic-team/ionic-site). Thanks everyone!
