### ISSUE TITLE
Add the option to override the default ion-navbar back button OR implement an ion-nav-back-button component

### ISSUE THREAD

**Issue by kelvindart** [ionic-team/ionic#12302]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
At the moment, having an `ion-navbar` component on a page adds a back button if there is a page in the NavController stack to go back to. This is great.

There is a limitation when using the back button if you want to pop off the root navigation stack, for instance when you are in a tab nav stack. It is difficult to replicate the precise styling used on the current back-button.

**Expected behavior:**
Is it, therefore, possible to either:

1. Add a `(click)` handler to the `ion-navbar` directive which handles the default back button click, overriding the usual behaviour (which I am guessing does a `NavController.pop()`).

2. Add a new component, something like `<ion-nav-back-button></ion-nav-back-button>` (much like in v1) this has a `click` output so you can control default behaviour. Otherwise, the default behaviour should be the `NavController.pop()` as per the `ion-navbar` back button.

**Steps to reproduce:**
N/A

**Related code:**
N/A

**Other information:**
N/A

**Ionic info:**
```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 2.0.0
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 4.2.0
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#271
