### ISSUE TITLE
Images from remote server does not render after release build to publish on google play

### ISSUE THREAD

**Issue by vitorbarros** [ionic-team/ionic#12308]
Hi Everyone.

I have a big problem that i don't know anymore what to do to resolve this.

There we go...

My app gets imgs urls wich is in documents from database to render. This imgs are in s3 Amazon and at this time everything is really good. But now i moved all media from amazon to an dedicated server and changed all records in database to a new url base. 

For example:

Old URL:
https://s3-us-west-2.amazonaws.com/dotpet/imgs/Serv-Banho-Tosa_58caf5d66c39b.jpg

New URL:
https://cdn.dotpet.com.br/imgs/Serv-Banho-Tosa_58caf5d66c39b.jpg

The problem is:

1 - When I had opened the APP from browser all images is normally there.

2 - When I had builded a debug APK and installed that in device all images were normally renderized.

3 - When I had signed the unsigned APK with jarsigner command I really don't know why, but all images don't render.

Is there any one who have experienced this?

I'm so sorry about my poor english. But i really need help. I don't know what to do to resolve this.

**Comment by AmitMY** [comment]
Thanks for opening an issue.
Can you please fill out the template for new issues?

When you connect with remote dev-tools using chrome, is there an error in console, perhaps an origin related one?

**Comment by davec21** [comment]
We commonly use remote images in our projects and haven't had issues. Do the images render if given a good chance to load? I noticed your server seems kind of slow. 

If you do a signed debug build does it work?

**Comment by vitorbarros** [comment]
Thanks for reply. Now I'll try this and post here the results.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
