### ISSUE TITLE
When a Modal is present, the URL is reset to the root

### ISSUE THREAD

**Issue by 5im0n** [ionic-team/ionic#12306]
**Ionic version:**
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
I've wrapp all my pages component into distinct modules to get the lazy load power 💨!
In my application, I have a page component that I display as Modal: 

```
@IonicPage()
@Component({
  selector: 'app-info-modal',
  templateUrl: 'infos-modal.html',
})
export class InfosModalPage {}
```
```
const modalInfos = this.modalCtrl.create('InfosModalPage');
modalInfos.present();
```

1. Before I present the Modal my URL is something like that  `http://localhost:8085/#/machine/1/dashboard`
2. After the Modal has been present the URL is: `http://localhost:8085/#/`
3. When the Modal is dismiss the URL returns as before `http://localhost:8085/#/machine/1/dashboard`

**Expected behavior:**
I know that modal uses the `NavController` to present itself in the root nav stack, but to my mind the URL shouldn't be reset to the root.

**Ionic Info**
```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.4.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 2.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.3
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind posting your `ionic info` please?

**Comment by 5im0n** [comment]
Done

**Comment by 5im0n** [comment]
This issue is now resolve with the version `ionic-angular v3.5.0`
