### ISSUE TITLE
Cannot find module './features/localecompare'

### ISSUE THREAD

**Issue by rhernandez-itemsoft** [ionic-team/ionic#12313]
Help me,
i don't build ionic app
Debian 9 AMD64

![captura de pantalla de 2017-07-10 18-04-15](https://user-images.githubusercontent.com/4327356/28043981-40e61e9a-659a-11e7-8658-57aae12cdd1f.png)

![captura de pantalla de 2017-07-10 18-06-07](https://user-images.githubusercontent.com/4327356/28044014-78b96cd2-659a-11e7-954c-aca2583712be.png)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by rhernandez-itemsoft** [comment]
This error occurs by the  ".gitignore" file. I do not know what's wrong with this.
anyone know how to properly set the ".gitignore" file?

![captura de pantalla de 2017-07-25 14-43-10](https://user-images.githubusercontent.com/4327356/28590415-a78f39b6-7147-11e7-9a85-46373d97f722.png)
