### ISSUE TITLE
[IONIC 1] Please, Help me! Error in Geolocation!

### ISSUE THREAD

**Issue by rdiegoss** [ionic-team/ionic#12314]
**Ionic version:**  (check one with "x")
[ x] **1.x** 
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: 

**Current behavior:**
When open my app

**Expected behavior:**
Ugly message dissapear

**Steps to reproduce:**
Open app first time, ok! Close app and open again, ugly message appear!

**Other information:**
![erroor](https://user-images.githubusercontent.com/10976074/28045407-4023d664-65b3-11e7-8715-2734af77f2ff.jpeg)

```
Cordova CLI: 7.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.11
OS: macOS Sierra
Node Version: v6.9.0
Xcode version: Xcode 8.3.3 Build version 8E3004b
```

**Comment by yanxiaodi** [comment]
Do you need to use Geolocation plugin in your app? If you do not need it, remove it from your package.json.

**Comment by AmitMY** [comment]
For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1 or the forum.

**Comment by rdiegoss** [comment]
I'm use Geolocation plugin but dont work. 

@AmitMY Ok, thank you.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-v1#278
