### ISSUE TITLE
ion-toggle event

### ISSUE THREAD

**Issue by kokchyuan** [ionic-team/ionic#12329]
<ion-toggle [(ngModel)]="item.enabled" (ion-change)="saveSettings()"></ion-toggle>
<ion-toggle [(ngModel)]="item.enabled" (click)="saveSettings()"></ion-toggle>

both of it not working, can anyone tell me how to handle the toggle change event?

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by mburger81** [comment]
I notice the same or a similar issue!

But we have the issue only on mobile devices and if we use in chrome the "mobile inspector" using the `toogle toolbar`, if we debug normal as `WebApp` the `click` event is fired.

Can you confirm that?

**Comment by manucorporat** [comment]
It is not `(ion-change)`, but `(ionChange)`

**Comment by mburger81** [comment]
It seems `(click)` event is not fired  neither on device nor on chrome's "device toolbar mode" but on the normal web browser mode it does work.

(ionChange) event is fired always.

Is it wanted like that?

**Comment by manucorporat** [comment]
why are you using (click) in ion-toggle? ion-toggle just like ion-input, ion-checkbox is an component for user input, not a button.

You should use (ionChange)

**Comment by mburger81** [comment]
Obviousley it was a mistake and we changed to use `(ionChange)`.

I wrote this hint only to let you know the different behavior on different systems, so you can decide if it is a bug or not.
That was all, it should only be a help. :+1:
