### ISSUE TITLE
Back button in navbar is not working on Android

### ISSUE THREAD

**Issue by Geschan** [ionic-team/ionic#12323]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When clicking on the back button on the top left corner in Android, nothing happens.
The hardware back button does work - the back button in the navigation bar does not.
I found other people experiencing the same problem but no solution provided:
https://forum.ionicframework.com/t/android-back-button-not-working/82021
https://forum.ionicframework.com/t/navbar-back-button-not-working-in-android/81428

**Expected behavior:**
Back button in navbar should work the same as it does on iOS.

**Related code:**

```
<ion-header>
  <ion-navbar>
    <button ion-button menuToggle start>
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>{{ 'OVERVIEW' | translate}}</ion-title>
  </ion-navbar>
</ion-header>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.9.5
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.3.0
```

**Comment by peterkelly** [comment]
Possibly related to https://github.com/ionic-team/ionic/issues/12238

**Comment by Geschan** [comment]
I tried the latest nightly version, because I experienced the same bug with `navCtrl.remove()` mentioned in #12238, but this did not solve the back button problem.

**Comment by Geschan** [comment]
Found the problem.
Used a css suggested in [this topic](https://forum.ionicframework.com/t/navbar-ion-title-align-center-for-android/52263/13) to center the title on Android devices.
It actually had the effect of overlapping the menu icon (but just in case it was a back button *weird*) so it wasn't clickable.

**Comment by Aunk21** [comment]
I sloved it.

Add CSS in app.scss file

.back-button-md {
margin: 0 6px;
min-width: 44px;
-webkit-box-shadow: none;
box-shadow: none;
z-index: 100000;
}

Now it's working

**Comment by rrundle** [comment]
@Geschan that recommended css in the link worked like a charm!
