### ISSUE TITLE
All declarations of ‘WeakMap’ must have identical type parameters

### ISSUE THREAD

**Issue by faustbrian** [ionic-team/ionic#12325]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Application boots and serves me with this issue http://imgur.com/a/Qm22A saying `All declarations of ‘WeakMap’ must have identical type parameters` in multiple places.

**Expected behavior:**
Application should just boot and work since it is a fresh installation without any modifications.

**Steps to reproduce:**

```
ionic start myApp --v2
cd myApp
yarn install
ionic serve
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 3.5.0
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 2.0.1
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v8.1.3
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by danbucholtz** [comment]
Hi, How do I recreate this? I do not use yarn and I'm not sure that we support yarn. Can you recreate with npm?

Thanks,
Dan

**Comment by faustbrian** [comment]
npm results in the same scenario. Tried both before posting.

**Comment by jgw96** [comment]
@faustbrian are you on npm 5.2.0?

**Comment by faustbrian** [comment]
Yep, on 5.2.0.

**Comment by danbucholtz** [comment]
This is a known issue with `5.2.0`. Please revert to `5.1.0`. There is nothing we can about the npm bug unfortunately.

Thanks,
Dan
