### ISSUE TITLE
Loader is not being presented immediately.  

### ISSUE THREAD

**Issue by premcarver** [ionic-team/ionic#12320]
**Ionic version:** global packages:

    @ionic/cli-plugin-proxy : 1.3.1
    @ionic/cli-utils        : 1.4.0
    Cordova CLI             : 7.0.1 
    Ionic CLI               : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    npm        : 5.1.0 

**I'm submitting a bug report

**Current behavior:**
I am trying to present a loader while making http request from service and calling from controller.
I place my request through service once loder.present() promise becomes suceessful/true. But at the view level it comes just like a flash after a long time. During the duration my http call has returned and displays a toast as well.

**Expected behavior:**
Since show toast command has written after present the loader should come first. Which is not!
**Steps to reproduce:**

**Related code:** .   loader.ts
```
import { Injectable } from '@angular/core';
import { LoadingController, Loading } from 'ionic-angular';

import { Http } from '@angular/http';
import 'rxjs/add/operator/map';


@Injectable()
export class LoaderProvider {
  private loader: Loading;

  constructor(public http: Http, public loadingCtrl: LoadingController) { }

  showLoading(content: string) {
    this.loader = this.loadingCtrl.create({
      //spinner: 'bubbles',
      content: content
    });
    //this.loader.setShowBackdrop(false);
    this.loader.setDuration(5000);
    return this.loader.present();
  };

  hideLoading() {
    return this.loader.dismiss();
  }
}
```
controller code responsible to submit request..........
```
this.loader.showLoading("Please wait...").then(() => {
          this.settingsform.controls['picture'].setValue(this.picture);
          this.restServiceProvider.updateUserDetails(this.user_id, { user: this.settingsform.value })
            .subscribe(res => {
              this.storage.set('user_details', res).then(
                sucess => {
                  this.loader.hideLoading();
                  this.toast.showToast("Successfully saved.");
                  this.updateUserData();
                },
                error => {
                  this.loader.hideLoading();
                  this.toast.showToast(error);
               
                }
              )
            }, error => {
                this.loader.hideLoading();
                this.toast.showToast(error);
               
            });
        });

```

**Comment by Sampath-Lokuge** [comment]
Please format the code properly and remove unnecessary auto generated comments.

**Comment by premcarver** [comment]
Done. @Sampath-Lokuge Can you help me to get it fixed?

**Comment by Sampath-Lokuge** [comment]
Remove this and see it `this.loader.setDuration(5000);`

**Comment by premcarver** [comment]
I have tried every possible way and removed the suggested line of code. But being Unlucky again and again ...it failed.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
