### ISSUE TITLE
ble observable data not updating template variables

### ISSUE THREAD

**Issue by PurpleEdge2214** [ionic-team/ionic#12324]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
There have been several reports on the Ionic support forum about variables within a ble observable not updating the display variables on a template...

https://forum.ionicframework.com/t/page-wont-refresh-in-ionic/97100
https://forum.ionicframework.com/t/results-from-ble-scan-not-invoking-angular-update/91935

Basically, when a declared variable is assigned a value within a ble observable the screen doesn't get updated until there is some interaction with the screen - e.g. tapping a button.

**Expected behavior:**
Values assigned within a ble observable should update the template display variables immediately.

**Steps to reproduce:**
See code below, ble needs a device so can't reproduce on plunker.

**Related code:**

```
import { Component, NgZone } from '@angular/core';
import { NavController } from 'ionic-angular';
import { BLE } from '@ionic-native/ble';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  private deviceId: string;
  private characteristics = [];
  private heartRate = 50;
  private connected = false;
  
  constructor(
    public navCtrl: NavController,
    private ble: BLE,
    private zone: NgZone
  ) {

  }

  getConnection() {
    this.connectToDevice()
    .then((connected) => {
      this.connected = connected;  // this gets updated in template
    })
  }

// this is a hack to get the data from the observable to a promise
// so the variable DOES get updated
  connectToDevice(): Promise<any> {
    console.log('clicked');
    return new Promise(resolve => {
      this.ble.scan([], 5)
        .subscribe((data) => {
          if (data.id) {
            this.deviceId = data.id;
            this.ble.connect(data.id)
              .subscribe((subData) => {
                this.characteristics = subData.characteristics;
                console.log('this.characteristics', this.characteristics);
                resolve(true);
              })
          }
        })
    })
  }

  readHR() {
    this.startHrNotification()
      .subscribe((response) => {
        var data = new Uint8Array(response);

// this is a WORKAROUND to resolve the issue
        this.zone.run(() => this.heartRate = data[1]);  // this gets updated
        console.log(this.heartRate);
      })
  }

  startHrNotification(): Observable<any> {
    if (!this.connected) {
      console.log('Not Connected');
    } else {
      return this.ble.startNotification(this.deviceId, "180d", "2a37")
    }
  }

  disconnect() {
    this.ble.disconnect(this.deviceId);
  }

}

```

**Other information:**

WORKAROUND - use ngZone and zone.run() to update display

```
 ordova CLI: 7.0.1
Ionic Framework Version: 3.4.2
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-native#1794
