### ISSUE TITLE
ion-input with ion-checkbox on the same line tap steals focus

### ISSUE THREAD

**Issue by dr1v3** [ionic-team/ionic#12335]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a row with ion-checkbox and two ion-inputs on the same line. When I tap on the checkbox, ion-input steals focus and checkbox state does not changing. This happens on android and ios devices. In browser all works correctly. You can check the screencast from Galaxy S4 [here](https://youtu.be/cXxKek0jdYI)

**Expected behavior:**
ion-checkbox on device should work the same as in a browser.

**Steps to reproduce:**

**Related code:**

```
<ion-navbar>
  <ion-title>Test</ion-title>
</ion-navbar>

<ion-content padding >
  <ion-list>
      <ion-item-sliding>
          <ion-item>
              <ion-checkbox col-1 ></ion-checkbox>
              <ion-input placeholder="Option name" col-9></ion-input>
              <ion-input class="option-price" placeholder="+$1.00" type="number" col-3></ion-input>
          </ion-item>
          <ion-item-options side="left">
              <button ion-button color="danger">
                  <ion-icon name="trash"></ion-icon>
                  Remove
              </button>
          </ion-item-options>
          <ion-item-options side="right">
              <button ion-button color="danger">
                  <ion-icon name="trash"></ion-icon>
                  Remove
              </button>
          </ion-item-options>
      </ion-item-sliding>
  </ion-list>
</ion-content>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.2.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.0
    ios-sim    : 5.0.13
    npm        : 3.10.10
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We will look into this.

**Comment by dr1v3** [comment]
I found a workaround for this

```
<ion-item>
    <ion-row>
        <ion-col><ion-item><ion-checkbox></ion-checkbox></ion-item></ion-col>
        <ion-col><ion-item><ion-input placeholder="Option name"></ion-input></ion-item></ion-col>
        <ion-col><ion-item><ion-input class="option-price underlined" placeholder="+$1.00"  type="number"></ion-input></ion-item></ion-col>
    </ion-row>
</ion-item>
```

**Comment by bergergit** [comment]
Any updates on this, without @dr1v3 workaround? When I use multiple ion-item inside <ion-col>, I get a totally incorrect styled screen.
With a single ion-item my screen looks good, but indeed the ion-input does steal the focus, on Android and iOS (works OK in browser)

**Comment by abcdurga** [comment]
@dr1v3 - I i have fixed it by writing the following style in my .scss file:

```
.input-cover{
        display: none;
    }
```

**Comment by etchen99** [comment]
This was happening to me on ios/android, but not web, where I had an `<ion-item>` with nested clickable `<img>`, `<ion-input>`, and `<button>` and the `<ion-input>` was preventing the other two from being clickable.  @abcdurga 's fix worked for me.

**Comment by dalezak** [comment]
Although the `.input-cover{ display: none; }` seems to fix the issue with not being able to select the `ion-checkbox`, upon focusing on the `ion-input` the navbar disappears off the top of the screen when the keyboard appears.

Looks like the `.input-cover` is used in relation to showing and hiding the keyboard. 😞
