### ISSUE TITLE
bug: Ionic Generate Provider is giving the wrong path

### ISSUE THREAD

**Issue by DaniloCouto** [ionic-team/ionic#12337]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When you generate an provider with Ionic CLI 3, it automatically fill the app.module.ts with the provider, but the path is wrong:

Ionic generates this path:
import { TestProvider } from '..\providers\test/test';

Should Be:
import { TestProvider } from '../providers/test/test';</span>

Ionic info:

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Gulp CLI         : CLI version 1.2.2 Local version 3.9.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.0
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-gulp          : 1.0.2
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v7.8.0
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.1.1

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2521
