### ISSUE TITLE
Multiple Pages in one module

### ISSUE THREAD

**Issue by Daskus1** [ionic-team/ionic#12333]
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
There is no way to lazy load multiple pages at once. 

Take a look at this pretty common scenario:
An app has a settings page with multiple sub-settings pages for more detailed settings.

Obviously the sub-setting pages are part of the same "settings-feature" and belong in the same module. Or at least Angular is promoting this "module for feature" approach in their documentation.

In Ionic it is not possible to put everything in one module because every lazy loaded page has its own IonicPage() decorator and thus needs its own module.

This approach leads to **very bad and not well organized folder structure as well as app architecture**  (My app for example has about 40 pages, which all need an individual module even if they could/should be grouped into one).

**Expected behavior:**
Modules can contain multiple Pages which can be lazy loaded all at once. This improves folder structure and modularization per feature.

**Comment by Kuldeep78** [comment]
I am too concerned about this approach. It does not feel tidy to have separate module file for all the pages which logically belong to same group. Any updates on this issue?

**Comment by jgw96** [comment]
Hello all! The next version of generators, which is coming out soon, is going to make it optional to add a separate module for each page, therefore allowing you to customize it however you would like it. Thanks for using Ionic!

**Comment by Daskus1** [comment]
@jgw96 can we do that also manually right now? Let's say I have `Page1` and `Page2` and want to put them in one module `page1and2.module` and lazy laod the module. Is this possible or will it be possible with the next version?

**Comment by Sampath-Lokuge** [comment]
@Daskus1 Hope you'll try that and will let us know too before the new generator :1st_place_medal:

**Comment by trenthm** [comment]
@jgw96 Is this available in the 3.6.0 release? (I don't see it) Or, is it going to be in a future version?

**Comment by Daskus1** [comment]
@jgw96 any update on this? I would like to port my app to ngrx v4 and would like to adapt their folderstructure...currently it is not possible due to ionics restrictions on lazyloaded modules

**Comment by plul** [comment]
Can this issue please be re-opened until we have a working solution?

**Comment by tattivitorino** [comment]
Hello you all.. any update on this! thats exactly what i need! i want to create one module (say entry point module) which consists of a login, sign up, forgot password, terms and tutorial pages! Most of my apps starts like this so i thought that would be nice to put them together in one module!

**Comment by FazioNico** [comment]
same needed...any solution to do module loading as Angular do??

**Comment by sebrojas14** [comment]
Any news?

**Comment by mborca** [comment]
Doesn't seem to work. For every page not having a corresponding module deeplinking throws an error (ex. for SomePage, it looks for a module called some-page.module.ts).

**Comment by maxruby** [comment]
@jgw96  why is this issue closed if there is no solution from Ionic right now?  I too agree that it would be very useful at least to have the option to group together Pages under one module.

**Comment by tattivitorino** [comment]
@jgw96 why is it closed? totally agree with @maxruby!!!

**Comment by graphicsxp** [comment]
Why is this closed ? I'm having the same issue and I'm using the latest ionic version.  One page per module is NOT the way to go and makes modules usage irrelevant...

**Comment by Daskus1** [comment]
@jgw96 @kensodemann is there any update on this? It seems like a lot of people are have this problem...This issue should be opened until a proper solution is found

**Comment by kazzkiq** [comment]
Just had a huge issue with a production build (`ionic cordova build ios --prod`) in my work due to this multiple modules approach of Ionic. We decided to deliver the app building it in development mode to keep the schedule.

Looking forward to a solution without multiple modules, so we can use it just like any other Angular application (which means a single `app.module.ts` without hassle).

**Comment by keyss2014** [comment]
what's the meaning ? no any comments?

**Comment by pdvorchik** [comment]
Adding my voice to the chorus of people who would like to see this feature.

As of now I'm simply giving up on lazy-loading some of my pages...but that's far from ideal.  Would love to hear an update on this @jgw96 even if it's just a rough ETA.  Thank you for the work you do on this project.

**Comment by tattivitorino** [comment]
well this issue is closed, shouldn't we open another? @jgw96 any news?

**Comment by webkhushboo** [comment]
I am also facing the same issue , my ionic app has setting page which consists of multiple sub pages .
I don't want to create module file for each sub pages , Is there any way to do it in one module ? Please help !!

**Comment by hakano** [comment]
There is an Ionic blog post [here](https://blog.ionicframework.com/ionic-and-lazy-loading-pt-2/) which explains two different approaches that can be used for lazy loading pages. I think the second option explained here might be the solution for this issue.

>...
**Option 2: Shared Common Modules**
_(Creating a shared module for each component and pipe your app may have)_
With this approach, instead of splitting things into their own isolated module, everything gets bundled into a shared components.module.ts The same would go for any pipes we have or any directives we might have as well.
...

**Comment by varunkumarm** [comment]
@jgw96 Please reopen the issue - it is clear that this issue has not been addressed and many are eagerly waiting for a resolution.
