### ISSUE TITLE
Issue when updating to Angular 4.2.x

### ISSUE THREAD

**Issue by DedSec49** [ionic-team/ionic#12330]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Whenever I update to angular 4.2.x and run the the command.
`ionic cordova run android --prod`
I get an error: 
`[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova). Your plugins may be out of
       date.
Error: The RegExp to find the DeepLinkConfigToken did not return valid data`

and the command fails and exits.

ionic info: 
`global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.3 browser 4.1.0 ios 4.3.1
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.4.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.0.5`

Please help me out.

**Comment by Jahrenski** [comment]
ionic 3.5.0 does not supports angular 4.2.x, only 4.1.3

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Angular 4.2.x support is coming out in today's 3.5.1 release. (:

**Comment by DedSec49** [comment]
Thank you very much @jgw96  for your support.

**Comment by luckylooke** [comment]
Please reopen, I have v3.5.3 and it still depends on angular 4.1.3

```
npm WARN ionic-angular@3.5.3 requires a peer of @angular/common@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.3 requires a peer of @angular/compiler@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.3 requires a peer of @angular/compiler-cli@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.3 requires a peer of @angular/core@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.3 requires a peer of @angular/forms@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.3 requires a peer of @angular/http@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.3 requires a peer of @angular/platform-browser@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.3 requires a peer of @angular/platform-browser-dynamic@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.3 requires a peer of rxjs@5.4.0 but none was installed.
npm WARN ionic-angular@3.5.3 requires a peer of zone.js@0.8.12 but none was installed.
```
