### ISSUE TITLE
ionictabsHideOnSubPages doesn't work in ionic 3.5.0

### ISSUE THREAD

**Issue by medst** [ionic-team/ionic#12338]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ionictabsHideOnSubPages doesn't work in ionic 3

**Expected behavior:**
ionictabsHideOnSubPages work fine

**Steps to reproduce:**
that's my url : http://localhost:8100/?ionictabsHideOnSubPages=true
but the tabs are showen on subpages

you can start a new ionic 3.5.0 tabs app and test it.

**Comment by astec** [comment]
@medst what is `ionictabsHideOnSubPages`?
Google does not return any results on this: https://www.google.co.uk/search?q=ionictabsHideOnSubPages

Can you add a link to the docs and a plunker?

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! If you put `tabsHideOnSubPages="true"` in the config of your app, does it work?

**Comment by medst** [comment]
i put tabsHideOnSubPages="true" in the config, but it doesn't work, when i have light theme (background color is light) the tabs ara visible in subpages, but when the theme is dark (background color is dark) tabs are invisible in subpages !!!

**Comment by medst** [comment]
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : not installed
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v8.0.0
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.0
