### ISSUE TITLE
ActionSheet Can't dismiss bug

### ISSUE THREAD

**Issue by kevinlincg** [ionic-team/ionic#12340]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

this issue is on 3.5.0, 3.4.2 is not happen

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When I use an actionsheet after an actionsheet. The second actionshett will left on the screen forever.
Like this gif
![Alt text](https://raw.githubusercontent.com/kevinlincg/ionic_actionsheet_test/master/bug.gif)

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
Source code is here
https://github.com/kevinlincg/ionic_actionsheet_test/blob/master/src/pages/home/home.ts

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
λ ionic info

global packages:

    @ionic/cli-utils : 1.5.0
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.0.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.0

**Comment by dylanvdmerwe** [comment]
Can you show some code on how you are dismissing the action sheet before displaying the next one?

**Comment by wbhob** [comment]
Try getting rid of your handler function

**Comment by kevinlincg** [comment]
Here is the code 

```
  testsheet() {
    let actionSheet = this.actionSheetCtrl.create({
      buttons: [
        {
          text: 'Confirm Delete',
          role: 'destructive',
          handler: () => {
            this.testsheet();
          }
        }, {
          text: 'Cancel',
          role: 'cancel',
          handler: () => {
          }
        }
      ]
    });
    actionSheet.present();
  }

  pressbtn() {
    let actionSheet = this.actionSheetCtrl.create({
      buttons: [
        {
          text: 'Delete',
          role: 'destructive',
          handler: () => {
            this.testsheet();
          }
        }, {
          text: 'Cancel',
          role: 'cancel',
          handler: () => {
          }
        }
      ]
    });
    actionSheet.present();
  }
```

**Comment by daveshirman** [comment]
Just a thought: Maybe you should use an alert for the confirm as technically it is a destructive action.

**Comment by dylanvdmerwe** [comment]
Please see the `Dismissing And Async Navigation` docs [here](http://ionicframework.com/docs/api/components/alert/AlertController/) with regards to dismissing these kinds of alerts.

**Comment by kevinlincg** [comment]
I tried alert and it is same issue happen.
If I use v3.4.2 ,it works fine.
Is any changes in v3.5?

**Comment by aceoliver** [comment]
Maybe this is related: https://github.com/ionic-team/ionic/issues/12225
