### ISSUE TITLE
form validation border on ion-items with select inputs (ion-select)

### ISSUE THREAD

**Issue by cyptus** [ionic-team/ionic#12345]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

ion-items with text text inputs gets the class "item-input" and a validation border (e.g. $text-input-ios-show-invalid-highlight) if it is invalid (for example required).
ion-items with select inputs does not get this validation border if they are required (css class item-select on ion-item).

**Expected behavior:**

While select-inputs can have a required input, the validation borders should been visible on ion-items with select inputs too.

**Steps to reproduce:**

**Related code:**

```html
<form [formGroup]="personForm">
  <ion-list>
    <ion-item> <!-- shows a validation border -->
      <ion-label color="primary">Name</ion-label>
      <ion-input type="text" placeholder="Name" formControlName="username"></ion-input>
    </ion-item>

    <ion-item> <!-- does not show a validation border -->
      <ion-label color="primary">Gender</ion-label>
      <ion-select interface="popover" formControlName="gender">
        <ion-option value="1" selected="true">Male</ion-option>
        <ion-option value="2">Female</ion-option>
      </ion-select>
    </ion-item>
  </ion-list>
</form>
```

```javascript
    this.personForm = formBuilder.group({
      username: ['', Validators.required],
      gender: ['', Validators.required],
    });
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.10.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

**Comment by bArraxas** [comment]
The same problem exist for &lt;ion-datetime&gt;
Here my personal fixe :
```
<ion-item [ngClass]="{ 'ng-valid': myDate !== null, 'item-input': true }">
  <ion-datetime [(ngModel)]="myDate " displayFormat="DD/MM/YYYY" pickerFormat="DD/MM/YYYY" [min]="min" [max]="max" placeholder="a placeholder..."></ion-datetime>
</ion-item>
```

**Comment by kensodemann** [comment]
Hello everyone! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#304

**Comment by bArraxas** [comment]
404 not found

**Comment by kensodemann** [comment]
It is a private repo.

**Comment by JeongJun-Lee** [comment]
Is this issue solved? because I've still met this issue at Ionic 3.9.x.

**Comment by AntonTrapp** [comment]
No idea, sorry, not using ionic any more.
