### ISSUE TITLE
Strange behaviour of the range sliders

### ISSUE THREAD

**Issue by arturalkaim** [ionic-team/ionic#12342]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[X ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Strange behaviour of the range sliders on the desktop version running with 
`ionic run browser` as you can see in the [screen capture here](https://www.dropbox.com/s/va1k7b6pl9ly2la/just-sliders-ionic-run.mov?dl=0).

However, when running with `ionic serve` this problem doesn't appear at all as you can [see here](https://www.dropbox.com/s/mh88zoq93d4l5oq/just-sliders-serve.mov?dl=0).

**Expected behavior:**
The slides responds smoothly with `ionic run browser` as it does with `ionic serve`

**Steps to reproduce:**
Create a page with a slider and run in with `ionic run browser` in a pc.

**Other information:**
https://forum.ionicframework.com/t/sliders-on-browser-bug/98012

**Ionic info:**:

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.0
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.2
ios-deploy version: 1.9.0 
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We currently do not recommend using the cordova browser platform. The cordova browser platform was mainly an experiment in native plugin mocking for plugin developers to be able to easily develop their plugins in the browser. It was not meant to actually be used for apps. If you want to run your app in the browser `ionic serve` is the command you want to use, no need for a cordova browser platform.
