### ISSUE TITLE
Properties value is undefined in method which returns promise 

### ISSUE THREAD

**Issue by david95thinkcode** [ionic-team/ionic#12343]
**Ionic version:** 
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I'm trying to use a parameter in one method. 
When I show the object with a console.log, The object is correctly displayed with its various properties.
When I tried to get value of one property of this object, I realize that it shows me :  **undefined**. It seems like the values disappear.
The following pictures explain that : 
The code :
![undefined](https://user-images.githubusercontent.com/24503308/28165536-1458bd4a-67cc-11e7-9aab-2c5c1149f65d.png)
The console : 
![undefined2](https://user-images.githubusercontent.com/24503308/28165561-30cbd9da-67cc-11e7-9428-c50ea6cb007c.png)
 
**Expected behavior:**
The properties of my object should not be "undefined", they should contain there real values inside this object.

**Steps to reproduce:**

**Related code:**

```
public getCurrentForecast(origins: IonicNativeGeoposition): Promise<DarkSkyApiResponse> {
        
        // !!!!!!!!!!!!!! THIS WORKING FINE !!!!!!!!!!!!!!
        console.log(origins);

        //!!!!!!!!!!!!!! THIS IS NOT WORKING  !!!!!!!!!!!!!!
        console.log(origins.latitude + ',' + origins.longitude);

        
        let parameters: string = '';
        let language = `lang=${this.defaultLanguage}`;
        //TODO: régler le problème de réception de origins
        if (origins.latitude == undefined || origins.latitude==undefined) { 
            //On utilisera des valeurs par défaut en attendant que le problème d'origins soit réglé
            let or : IonicNativeGeoposition = new IonicNativeGeoposition();
            or.latitude = 6.3604233;
            or.longitude = 2.3769492000000003;
            parameters = `${or.latitude},${or.longitude}?${language}`;
        }
        else {
            parameters = `${origins.latitude},${origins.longitude}`;
        }
        const url: string = this.baseURL+this.apikey+'/'+parameters;

        return this.http.get(url)
        .toPromise()
        .then(response => response.json() as DarkSkyApiResponse)
        .catch(error => console.log('DarkSkyService error : ' + error));

    }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 2.0.0
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.11.0
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10 

```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
