### ISSUE TITLE
Cannot find module '@angular/tsc-wrapped/src/tsc'

### ISSUE THREAD

**Issue by vksgautam1** [ionic-team/ionic#12357]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[1 ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

 
E:\Working Project\schoolsDna>ionic cordova run android --prod
? The plugin @ionic/cli-plugin-cordova is not installed. Would you like to install it and continue? Yes
> npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest
√ Running command - done!
[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova). Your plugins may be out of       date.
Error: Cannot find module '@angular/tsc-wrapped/src/tsc'

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v7.10.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.1.0

**Comment by peterpeterparker** [comment]
Duplicate https://github.com/ionic-team/ionic/issues/12065

**Comment by peterpeterparker** [comment]
P.S.: Update npm to last version may most probably gonna help

**Comment by vksgautam1** [comment]
done this with npm 5.3 and install node modules again. but still facing same issue

**Comment by peterpeterparker** [comment]
sorry didn't saw you weren't using the actual ionic app-scripts :(

then downgrade npm 
or upgrade npm and ionic app-scripts and ionic-angular (but pay attention to the change log https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md a line need to be added to index.html)

**Comment by jgw96** [comment]
Hello, all! At this point, this is due to issues in the latest release of npm. Downgrading to npm 5.1 fixes the issue, but we are considering just adding this package to our package.json (even though we technically shouldn't have too) for the meantime until npm fixes their issue. Gonna keep this one open for now as we discuss what we should do.

**Comment by peterpeterparker** [comment]
@jgw96 downgrading ... or upgrading everything might work too I think

about adding the package in our package.json...at one point npm gonna be fine again, no need to rush ;)

**Comment by wbhob** [comment]
Run `npm install --save-dev @angular/tsc-wrapped` in your shell

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by Barryrowe** [comment]
This still occurs with npm > 5.1 correct?

Is it Ionic's direction that we should just add @angular/tsc-wrapped to our package.json, or is that still under consideration?

**Comment by kensodemann** [comment]
@Barryrowe - FWIW, I am using npm version 5.3 and do not have this issue. What version are you using?

**Comment by Barryrowe** [comment]
Node v8.4.0
NPM 5.3.0

I just downgraded to NPM 5.2.0 due to this [issue](https://github.com/npm/npm/issues/17858) and still get the error with @angular/tsc-wrapped not found

**Comment by wbhob** [comment]
Try npm installing that module, angular/etc-wrapped

**Comment by Barryrowe** [comment]
@wbhob that's where I am at now, which is where my original question comes from. Is that the official path forward, and the templates for Ionic will include the package in package.json?

**Comment by wbhob** [comment]
It's the only fix I have found, and it's pretty standard practice: if one module depends on another, you have to install it.

**Comment by Barryrowe** [comment]
@wbhob agreed if you depend directly, just odd that it would be installed as a transitive dependency with npm 4.X and not 5.x. Simple solution, just odd.

**Comment by mlynch** [comment]
Hi all, I ran into this myself and was able to resolve it by removing my package-lock.json and node_modules and installing again, after having upgraded node and npm. There must have been an issue with the older version that stayed broken even after upgrading.

**Comment by bkarv** [comment]
@mlynch Hi which version of Node and NPM are you using?

**Comment by wbhob** [comment]
Node 8 / NPM 5

**Comment by ommyjay** [comment]
This can also happen if you lost internet connection while running ```npm install```. @bkarv steps solve the issue.
