### ISSUE TITLE
docs(navigation): what's the id of the root nav?

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#12354]
**Ionic version:**  (check one with "x")
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] support request (linked with https://forum.ionicframework.com/t/getrootnav-deprecated-use-getrootnavbyid-whats-the-value-of-the-root-nav-id)

**Current behavior:**
Following the introduction of Ionic 3.5.0, getRootNav was marked as deprecated. I would like to use then getRootNavById but I've got no idea what's the id of the root nav or how I could set my own id.

    (getRootNav) is deprecated and will be removed in the next major release. Use getRootNavById instead.

**Expected behavior:**
Document what's the root nav Id or how to set the root nav Id

**Steps to reproduce:**
- Update to ionic-angular >= 3.5.0
- Use getRootNav

**Other information:**

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Gulp CLI         : CLI version 1.2.2 Local version 3.9.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-gulp          : 1.0.2
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.2

System:

    Node       : v8.1.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13 
    npm        : 5.2.0

**Comment by realtebo** [comment]
Same problem here. Near identical sistem configuration.
I'm using this function to force tabs to disappear when loggin out.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-site#1197
