### ISSUE TITLE
docs(navigation): mistake in comment within ionViewCanEnter method example

### ISSUE THREAD

**Issue by raxkaynan** [ionic-team/ionic#12353]
**Description:**
Under the [Nav Guards examples](https://ionicframework.com/docs/api/navigation/NavController/#nav-guards), the method `ionCanViewEnter` has a comment that says "_here we can either return true or false depending on if we want to **leave** this view_". The expected comment should be "_here we can either return true or false depending on if we want to **enter** this view_".

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-site#1196
