### ISSUE TITLE
$ionicTabsDelegate.$getByHandle('my-handle').select(index) using id or name

### ISSUE THREAD

**Issue by brunoheringer** [ionic-team/ionic#12350]
I am using $ionicTabsDelegate in my project Cordova with Ionic for manager tabs in my view. But, in the oficial documentation the orientation is to use for select a specific tab. (The index is int):
'$ionicTabsDelegate.$getByHandle('my-handle').select(index)'

> I would like to know if it is possible to use id or name.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-v1#281
