### ISSUE TITLE
app.getActiveNav() was deleted in version 3.5.2

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#12362]
**Ionic version:**  (check one with "x")
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ X] support request 

**Current behavior:**
Ionic version 3.5.2 doesn't contains method app.getActiveNav() anymore

**Expected behavior:**
Is it correct that app.getActiveNav() was effectively deleted?

- Yes: 
a. Could you plz update the documentation because the method still appear https://ionicframework.com/docs/api/components/app/App/#getActiveNav
b. Could you instruct in that case which method replacement should be use

- No:
Could you plz inject back the method app.getActiveNav()

**Steps to reproduce:**
- Update to Ionic 3.5.2
- Use this.app.getActiveNav()

**Related code:**

this.app.getActiveNav()

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Gulp CLI         : CLI version 1.2.2 Local version 3.9.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-gulp          : 1.0.2
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.2

System:

    Node       : v8.1.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13 
    npm        : 5.3.0

**Comment by tim-hoffmann** [comment]
That was removed with this commit fce4422ab163ad24279c8648b17f629ca12c0d31

**Comment by danbucholtz** [comment]
Hi all,

Whoops, I am really sorry about that. We should not have deleted this method. I think I must have been using the refactoring tools in VS Code and that's why I didn't notice. I will put this back in and release a patch today.

Once again I'm very sorry.

Thanks,
Dan

**Comment by danbucholtz** [comment]
`3.5.3` is available with this fixed. Please let me know if you have any issues.

Thanks,
Dan

**Comment by peterpeterparker** [comment]
Everything is fine, getActiveNav is back and functional. Thx @danbucholtz

**Comment by elless** [comment]
Hi @danbucholtz - getActiveChildNav was also deleted in that commit - is there a chance that this also by accident, or was it intentional? Should we user getActiveChildNavs instead?
