### ISSUE TITLE
FR: Automatically dismiss ion-select on selecting an item

### ISSUE THREAD

**Issue by kelvindart** [ionic-team/ionic#12364]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
At the moment, when you use an `ion-select`, you tap on it, tap the option and tap "OK" to dismiss and confirm the selected the `ion-option`.

**Expected behavior:**
It would be great to have a config option (something like `dismissOnSelect (boolean)`) which triggers the OK button automatically and dismisses the pop-up, firing the ionSelect with the newly tapped value.

**Steps to reproduce:**
N/A

**Related code:**
```
<ion-select [dismissOnSelect]="true">
  <ion-option value="1">1</ion-option>
  <ion-option value="2">2</ion-option>
  <ion-option value="3">3</ion-option>
</ion-select>
```

**Other information:**
N/A

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
N/A

**Comment by kelvindart** [comment]
I am aware of the `ActionSheet` interface, but that's not ideal in all circumstances. 😃

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#274

**Comment by kelvindart** [comment]
Awesome - thanks @jgw96. 😄
