### ISSUE TITLE
docs: documentation

### ISSUE THREAD

**Issue by viking2917** [ionic-team/ionic#12365]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>on this page: http://ionicframework.com/docs/v1/guide/publishing.html

it says to build an ios app for production do this:

ionic cordova build ios --release

this errors when run. Should it not say: 
ionic build ios --release (without the cordova?)</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Those commands (the ones with `cordova`) are the instructions for the latest cli (cli v3). At this time we do not support the old cli.

**Comment by viking2917** [comment]
ok thanks!
