### ISSUE TITLE
not able to open link in system browser using anchor tag

### ISSUE THREAD

**Issue by ajaysaini95700** [ionic-team/ionic#12360]
I am using `"<a href="http://www.swasti.org/">"`open link</a> inside innerhtml. whenever i click on "open link" , link will be open in internal webview not system browser(see attached image
![www swasti org- iphone 5](https://user-images.githubusercontent.com/18483093/28208189-22525bca-68aa-11e7-8005-5acd12c1d2e6.png)
). and also used <a href="#" (click)="foo("http://www.swasti.org/")">open link</a>. and in ts file define  function 
foo(link:any)
{
 window.open(link, '_system');
}
then click event not working. i think click event will not be work inside innerhtml.  
so please give solution how to open link in system browser or how to handle click event inside innerhtml. with example

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
