### ISSUE TITLE
build with prod  failed   Function calls are not supported   with providers useFactory 

### ISSUE THREAD

**Issue by steavengong** [ionic-team/ionic#12361]
build with prod  failed   Function calls are not supported   with providers useFactory 

providers:[
{
      provide:DataOaProvider,
      useFactory:function(
        oaConfig:any,
        http:HttpProvider,
        util:UtilProvider){
        let dataOaProvider : DataOaProvider;

        if(oaConfig.isDev == 0){
          dataOaProvider = new DataOaProvider(http,util);
        }
        else if(oaConfig.isDev == 1){
          dataOaProvider = new DataOaDebugProvider(http,util);
        }
        else if(oaConfig.isDev == 2){
          dataOaProvider = new DataOaLocalProvider(http,util);
        }

        return dataOaProvider;
      },
      deps:["Data_OA_Config",HttpProvider,UtilProvider]
    },
    {
      provide:"Data_OA_Config",
      useValue:{isDev:0}
    }]

when i use  cli: ionic-app-scripts build --prod   failed
error:
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider 
            replacing the function or lambda with a reference to an exported function

but the same code
when i use cli:  ionic-app-scripts build  success

when code has no  useFactory its success

when cli: ionic-app-scripts serve success
but cli: ionic-app-scripts serve --address 192.168.1.1  failed
error:
Cannot read property 'launchBrowser' of undefined

Please Help me!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
