### ISSUE TITLE
Ionic g page not seting @IonicPage() on create.

### ISSUE THREAD

**Issue by synga** [ionic-team/ionic#12368]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When generating a page via CLI it doesn't set the `@IonicPage()` decorator inside the generated .ts of the component.

**Expected behavior:**

When creating a new page via CLI it should set the `@IonicPage()` over `@Component` so it doesn't throw an error of invalid link for those using Deeplinking.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 7.0.1
Ionic Framework Version: 3.5.2
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 2.0.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.2
Xcode version: Not installed
```

**Comment by mburger81** [comment]
For what I saw,  they removed it from generator. 
https://github.com/ionic-team/ionic/pull/12347

**Comment by synga** [comment]
@mburger81 oh, haven't seen this, my bad. Thanks 😄 will close this and wait for some news.
