### ISSUE TITLE
Ionic CLI - Generated page and components does to include modules

### ISSUE THREAD

**Issue by chukwu** [ionic-team/ionic#12375]
After upgrading my app to ionic 3.5.3 via the guide, Each time i run ionic generate component or page, the generated file does not include ngmodule as earlier. Is this a change or a bug. My CLI is still ionic 3.5.0 though even after removing and reinstalling ionic. Am i missing something?

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by Maik3345** [comment]
is a problem whit the cli of ionic o is absolute this change? after update to 3.5.0 not creates the module.ts

**Comment by litts** [comment]
someone needs to comment on this. Is this the new expected behavior or its a BUG?

**Comment by Fabiryn** [comment]
https://github.com/ionic-team/ionic-app-scripts/issues/1105 for more informations

**Comment by jgw96** [comment]
Hello all! I am going to close this as a dupicate of https://github.com/ionic-team/ionic-app-scripts/issues/1105
