### ISSUE TITLE
mousedown event wait for click

### ISSUE THREAD

**Issue by narf** [ionic-team/ionic#12371]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Only in mobile (real device or chrome mobile simulator) The mousedown event is sent only when a click is detected (for example, there is zero mouse down event sent for swipes) and only after a click is done (after the mouse goes up).

**Expected behavior:**
mousedown event should be fired directly when the mous goes down, without delay

**Steps to reproduce:**
Add snippet below to app component, serve code on chrome, activate mobile simulation and try to mouse down.
I tried this on my project and on a brand new project created with "ionic start hop super"

**Related code:**

```
 @HostListener("mousedown") onMouseDown() {
        console.log("mousedown")
    }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.2

System:

    Node       : v8.1.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3
```

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Does this also happen in a plain angular app?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by ziwenzhao** [comment]
Hi I got the same problem, did you find the solution finally?
