### ISSUE TITLE
Toast alert can't close.when show double component

### ISSUE THREAD

**Issue by shenmingxuanyi** [ionic-team/ionic#12378]
**Ionic version:**  (check one with "x")
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Related code:**

```
    showToast($event) {
        this.toastController.create({message: 'fuck', position: 'middle'}).present();
    }

```

![image](https://user-images.githubusercontent.com/4010806/28253980-4343a932-6adb-11e7-94ba-9cc3eb86b441.png)

###since 3.4.2 after version

**Comment by Sampath-Lokuge** [comment]
Can you show your component code also?

**Comment by astec** [comment]
@shenmingxuanyi

> `'****'`

I myself use curse words quite a lot but posting this to public forum is not funny.

**Comment by shenmingxuanyi** [comment]
Hello, I am a loyal user of your attention to your products, I have for a long time, from the first generation of products, there is a serious problem, I use a button to trigger the toast, click toast to close several times will lead to.

**Comment by shenmingxuanyi** [comment]
, continuous click several times, resulting in toast cannot be closed.
