### ISSUE TITLE
ion-card as directive

### ISSUE THREAD

**Issue by patrickmcd** [ionic-team/ionic#12377]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] feature request

**Feature Request:**

Just as `ion-item` can be used as a directive on a `button`:

```
<button ion-item *ngFor="let item of items" (click)="itemSelected(item)">
  {{ item }}
</button>
```

I'd like to be able to use `ion-card` as a directive:

```
<button ion-card *ngFor="let card of cards" (click)="cardSelected(card)">
  <ion-card-header>{{card.title}}</ion-card-header>
  <ion-item>{{card.someProperty}}</ion-item>
  <!--etc.-->
</button>
```

Then we could use cards without worrying about adding `tappable`, but my hope would be that the ripple effect would work across the whole card area.

**Comment by vitorsilvalima** [comment]
Actually, if you want to check if the user has clicked, tapped or done something on the card, you can use the event (click) directly on the card as shown bellow:
```
<ion-card class='card'  class="movie-info" (click)='itemSelected(item)'>
</ion-card>
```

Checkout my example add for more details: 
* https://github.com/vitorsilvalima/ionic-tmdb

**Comment by patrickmcd** [comment]
Thanks for the suggestion, but I am aware that I can put `(click)` on the card. That's why I mentioned the `tappable` attribute, which should be added to your example to remove the 300ms delay.

```
<ion-card tappable (click)='itemSelected(item)'>
</ion-card>
```

The point of this request is for "first class" support of cards as buttons. As I mentioned, the ripple effect would be nice. We would gain improved accessibility as well.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#276
