### ISSUE TITLE
Error when logging in from CLI over slower connection: Error: Response timeout of 5000ms exceeded

### ISSUE THREAD

**Issue by newpointmedia** [ionic-team/ionic#12370]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When running ionic login and entering the correct username and password the following message is returned: Error: Response timeout of 5000ms exceeded

I am on satellite connection which can be a little slower at times and this should not prevent a successful login from occurring. 

**Expected behavior:**
I can log in successfully even if it takes longer than 5000ms

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2534
