### ISSUE TITLE
ionic 3 slides unstablity issue

### ISSUE THREAD

**Issue by selvin007** [ionic-team/ionic#12376]
Whenever a new slide is added before current slide
this.slides.slideTo(current_slide_index, 0, false) is used to maintain the slide position

This doesn't work in following cases

1) on load no slide is appended after current slide (bypasses by adding 50 ms timeout)
2) if the view containing slides component is loaded from app.component.ts/notification tap
this.slides.slideTo function doesn't work at on load

on ionSlideDidChange event prepend & append both work fine maintaining the slide position

Major issue here is Prepending slides works differently onload, onloadfrom app.component.ts, from deeplink & onevent

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Would you mind posting a code sample that we could use to reproduce this issue?

**Comment by selvin007** [comment]
item.ts

@ViewChild(Slides) slides: Slides;
public items = [];
constructor(public navCtrl: NavController, public navParams: NavParams, public api: Api, public sqliteService: Sqlite) {
    this.sqliteService.getSingleItem(this.selectedItem.id).then(s => {
        this.items.push(this.sqliteService.itemArray);
    });
}
//next 2 items
this.sqliteService.getItemsNext(this.selectedItem.id, 2).then(s => {
    for (let item of this.sqliteService.nextArray) {
        this.items.push(item);
    }
});

//prev 2 items
this.sqliteService.getItemsPrev(this.selectedItem.id, 2).then(s => {
    for (let item of this.sqliteService.prevArray) {
    	this.items.unshift(item);
        this.slides.update();
    }
    **if (this.sqliteService.nextArray.length == 2) {
        this.slides.slideTo(this.sqliteService.prevArray.length, 0, false);
    } else {
        setTimeout(() => {
            this.slides.slideTo(this.sqliteService.prevArray.length, 0, false);
        }, 50);
    }**
});

item.html
<ion-content class="cards-bg social-cards">
  <ion-slides #slider (ionSlideDidChange)="updateSlides($event)">
    <ion-slide *ngFor="let item of items">
        <ion-card>
        	{{item.data}}
        </ion-card>
    </ion-slide>
  </ion-slides>
</ion-content>

This is implemented with ionic 3 

Issue is while executing the highlighted code
