### ISSUE TITLE
Problem with two subsequent dollar signs ($$)

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic#12379]
**Ionic version:**

[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

I add two dollar signs (`$$`) somewhere in the content page, but when running `ionic serve`, it only shows one. If I use three or four signs, it shows two. If I use five or six, it shows three, and so on.

I think that one `$` sign is shown as one but if I have two subsequent `$` signs, they are "escaped" to only one or whatever. Using `&#36;` instead works as expected.

**Expected behavior:**

`$$` should output two dollar signs in text.

**Steps to reproduce:**

Create a new ionic project (e. g. `ionic start test-app blank`). Add two dollar signs somewhere in the body text like

```html
The world is your oyster.
  <p>
    $$ If you get lost [...]
  </p>
```

The output looks like this:

![image](https://user-images.githubusercontent.com/3410759/28254210-c5ec2544-6afe-11e7-9c64-9dc345a29c02.png)

I tried to reproduce it in plunker, but there it works as expected somehow. 

**Other information:**

Tested in Chrome and Firefox. Also happens when previewing the app in Ionic View (iOS App).

**Ionic info:**

```plain
global packages:

    @ionic/cli-utils : 1.5.0
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v8.1.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 6.0.0
    npm        : 5.1.0
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by simonhaenisch** [comment]
was this fixed by <https://github.com/ionic-team/ionic-app-scripts/commit/de09048> (`@ionic/app-scripts@3.1.1`)?
