### ISSUE TITLE
3.5.3 wont build memory heap error

### ISSUE THREAD

**Issue by CooleyGit** [ionic-team/ionic#12388]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When trying to build --prod I get memory heap error

**Expected behavior:**

App should build.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

I already rolled back so not relevant to the issue but here is my info.
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.4.2
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.8.6 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.0 Build version 8A218a

```

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1125
