### ISSUE TITLE
Mixing Material Design mode 'md' with 'ios' results to styling issue in Alert Component

### ISSUE THREAD

**Issue by NBAMj** [ionic-team/ionic#12382]
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
Sometimes I want to mix *Material* styles with *iOS* styles.
For example, when the app mode is set to `md` *Material Design*,
```
@NgModule({
  declarations: [
      ...
  ],
  imports: [
      ...
    IonicModule.forRoot(MyApp, {
      mode: 'md'
    })
] ....
```
And the `Alert` component's mode is set to `ios`:
``_alert.setMode('ios');``
The ripple effect of Material Design is not aligned correctly on the items in the list

**Expected behavior:**
Align the ripple effects properly on the items, or remove the effect altogether.

**Steps to reproduce:**

[Plnkr code](http://plnkr.co/edit/oUEIovr7LCzoYlwJfo1y?p=preview)

**Comment by Manduro** [comment]
I ran into the same issue a while back and it was easily fixable by applying the css in the PR I just submitted.

**Comment by jgw96** [comment]
Thanks for using Ionic and thanks for the PR! We will look into this.
