### ISSUE TITLE
Ionic 3 Refresher need to set a value for startY

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic#12387]
[X ] **3.x**

[X ] feature request

**Current behavior:**
At this moment where pull to refresh can be triggered from anywhere on the screen. 

**Expected behavior:**
Need an option on Ionic that the gesture used to trigger pull ONLY works when pulling down is done from the very upper part of the screen.That means we need to set a value for `startY`.At this moment it seems a `getter` property only.

This is not working?

```
<ion-refresher (ionRefresh)="getData($event)" [pullMin]="180" startY="80">
    <ion-refresher-content pullingIcon="arrow-dropdown" pullingText="Pull to refresh" refreshingSpinner="crescent" refreshingText="Refreshing...">
    </ion-refresher-content>
  </ion-refresher>
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#277

**Comment by Sampath-Lokuge** [comment]
Thanks @jgw96

**Comment by celiostat** [comment]
hello @jgw96 Do you have any update on the issue mentioned above ?
