### ISSUE TITLE
How does the newly installed ionic interact with android?There is no exec () method?

### ISSUE THREAD

**Issue by 12ThMicrowave** [ionic-team/ionic#12383]
[**Ionic](url) version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use 
****
- [

- [ ] @1. 

](https://github.com/ionic-team/ionic-v1))

[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
