### ISSUE TITLE
Ionic - There is no js folder and templates folder under Android under assets/www/folder

### ISSUE THREAD

**Issue by 12ThMicrowave** [ionic-team/ionic#12380]
Download new requests for help: 
new project: the project/platforms/android/assets/WWW/folder without js folder app. Js, controllers, js
also does not have the templates folder.html

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
