### ISSUE TITLE
bug:ionic-app-scripts build --prod lost some css

### ISSUE THREAD

**Issue by steavengong** [ionic-team/ionic#12381]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I use git   https://github.com/squallliu/app-scripts-test1  for test
I change the HomePage html 
in the ion-content , I use the ion-list
 
when use ionic-app-scripts build  (dev)
![image](https://user-images.githubusercontent.com/10862092/28260958-e892153e-6b0f-11e7-9ab9-ff68249e7411.png)
![image](https://user-images.githubusercontent.com/10862092/28260990-060321e4-6b10-11e7-8bf7-70259cd02b11.png)
It's no problem,

but use ionic-app-scripts build --prod
![image](https://user-images.githubusercontent.com/10862092/28261016-20c5106e-6b10-11e7-983c-2cd2580be9ad.png)
![image](https://user-images.githubusercontent.com/10862092/28261037-413622ca-6b10-11e7-97b7-afeb1c48d8bf.png)
it's has problem

in ion-label  there lost some css 

Please check !

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
global packages:

    @ionic/cli-utils : 1.5.0
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Ionic Framework                 : ionic-angular 3.5.2

System:

    Node       : v7.9.0
    OS         : Windows 8.1
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.3.0

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1120
