### ISSUE TITLE
I dont browse show ‘/#/nav/n4/***’

### ISSUE THREAD

**Issue by 791060555** [ionic-team/ionic#12391]
ionic：3.5.3
"@ionic/app-scripts": "2.0.2",
if use refresh browse,all error;

if i use "NavController"  method  "removeView" or "pop",and use 
  this.nav.push('AgentManagePage', {
        addAgentInit: true
      });

location  change #/nav/n4/agentManage;

I want hide " #/nav/n4/agentManage;"

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
