### ISSUE TITLE
Ionic version not upgraded on Windows even after uninstalling 

### ISSUE THREAD

**Issue by abhi05b** [ionic-team/ionic#12395]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ x] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I was earlier working on Ionic1, now I want to build a new project in ionic2.
I uninstalled the previous version using commnads:
npm uninstall -g ionic
npm uninstall -g cordova

Cleaned the npm cache also. But still the on windows command prompt, the ionic cli version is still 2.1.18 and the ionic start is creating Ionic1 starter files.

**Expected behavior:**

Ionic start should create Ionic3 starter folder

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2535
