### ISSUE TITLE
update  to  angular 4.3.0 manualy is possible?

### ISSUE THREAD

**Issue by webmobiles** [ionic-team/ionic#12396]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I've updated angular to last version 4.3.0

here part of  my package.json:

    "dependencies": {
        "@angular/common": "^4.3.0",
        "@angular/compiler": "^4.3.0",
        "@angular/compiler-cli": "^4.3.0",
        "@angular/core": "^4.3.0",
        "@angular/forms": "^4.3.0",
        "@angular/http": "^4.3.0",
        "@angular/platform-browser": "^4.3.0",
        "@angular/platform-browser-dynamic": "^4.3.0",

with:
$ npm update --save

I get 

npm WARN ionic-angular@3.5.0 requires a peer of @angular/common@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.0 requires a peer of @angular/compiler@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.0 requires a peer of @angular/compiler-cli@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.0 requires a peer of @angular/core@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.0 requires a peer of @angular/forms@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.0 requires a peer of @angular/http@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.0 requires a peer of @angular/platform-browser@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.0 requires a peer of @angular/platform-browser-dynamic@4.1.3 but none was installed.

after that i do:

$ ionic serve

i get:
Error: Cannot find module '@angular/tsc-wrapped/src/tsc'

It's possible to have a last  angular version with an  ionic last version? or always angular version is tied to ionic version?

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.0
    OS         : Linux 4.8
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3 


```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! While it is possible to update the version of angular you are using to a newer one than we have out of the box, it is not recommended. We do all of our testing with a specific version of angular so that we can assure there are no angular related issues in the framework. Because of this when we do a release we may be behind the latest version of Angular, but we feel that providing a working experience out of the box is a good trade off to possibly not always being on the latest version of Angular.

**Comment by webmobiles** [comment]
thanks ;, well understood

**Comment by barakbd** [comment]
When will 4.3 be integrated? I would like to use interceptor, as BaseReqeustOptions have an issue reading data from localstorage, and adding to headers, asynchronously.

**Comment by sharonsw** [comment]
^On top of that, the ionic-recommended option to support multi-lingual apps, `@ngx-translate/core` now requires `@angular/common` and `@angular/core` at >=4.3.0 for its http-loader to work correctly. It would be nice to get an update on whether 4.3.0 support will be on the horizon for future releases.

**Comment by yelhouti** [comment]
@jgw96 since angular uses semantic versioning, wouldn't it be better to use a version range ex: ^4.1.3. so we can use the latest features like the angular http client...

**Comment by shadoWalker89** [comment]
I upgraded my app successfully to the latest of ionic-angular and angular by following the changes that they made in this repository https://github.com/ionic-team/ionic-conference-app

You can see that they started upgrading from this commit https://github.com/ionic-team/ionic-conference-app/commit/d2bd480b6f02f12a833d05666aa29a2a906a36ea

These are the changes that i made to my package.json

![image](https://user-images.githubusercontent.com/1449151/30913936-2bd75916-a392-11e7-84c3-268875518a06.png)

![image](https://user-images.githubusercontent.com/1449151/30913978-4bf85e98-a392-11e7-85c6-acf282baabd2.png)

![image](https://user-images.githubusercontent.com/1449151/30913986-52b70d24-a392-11e7-86e7-31adf048bbb6.png)

Then i deleted the `node_modules` directory and run the `npm install`

**Comment by kensodemann** [comment]
@shadoWalker89 - I suggest waiting until `3.7.0` is released, which will include updating Angular to 4.4.3.

The problem with what you have (using the `nightly` for `ionic-angular` and `@ionic/app-scripts` is that you are just getting whatever we last pushed to the `nightly` tag which may or may not be completely broken at any given time depending on what is being tested, etc.

You certainly don't want that in production code.

Version `3.7.0` should be shipped some time today.

**Comment by shadoWalker89** [comment]
@kensodemann Great news that 3.7 will be out soon.
I made these changes to the app that i'm currently developing, it's not yet in production.
thanks

**Comment by imagine4me** [comment]
What is the proper way to upgrade to the latest version of Ionic? 
I currently have the following in my package.json. Will ionic cli just prompt me automatically to upgrade at some point?

"ionic-angular": "3.5.0",
"ionic": "3.12.0",
"@angular/core": "4.1.3",
etc.

**Comment by kensodemann** [comment]
@imagine4me  - Go here: https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md

It looks like you are currently on version `3.5.0` of the Ionic Framework, so start reading there and work your way up to see what manual mods are needed (if any). Then it should mostly mean following a combination of the instructions for `3.7.0` and `3.7.1` (and testing your app, etc.)
