### ISSUE TITLE
ion-header has a custom component, change some looks in ios.

### ISSUE THREAD

**Issue by longdw** [ionic-team/ionic#12394]
<strong>Ionic Version: 3.x</strong>

<strong>Current behavior:</strong>
it works fine in android device, but in ios, it looks like this:
![image](https://user-images.githubusercontent.com/4987178/28307970-5cbb62b8-6bd7-11e7-9f2f-fede166a0ebc.png)

<strong>Related code:</strong>
```
<ion-header>
    <titleview [title]="title" (titleClick)="handleMore($event)"></titleview>
</ion-header>
```

in custom component html:
```
<ion-navbar [color]="navColor">
    <ion-title>{{title}}</ion-title>

    <ion-buttons end>
        <button ion-button icon-only (click)="titleClick($event)">
            <ion-icon name={{iconName}}></ion-icon>
        </button>
    </ion-buttons>
</ion-navbar>
```

@brandyscarney   @jgw96  @Tusharbalar   like this [https://github.com/ionic-team/ionic/issues/9663](url)  described, but i can't work around it by add css the answers said.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! The `ion-navbar` should not be inside your custom component. Our navbar relies on `ion-header` being its direct parent element to style things in a certain way.
