### ISSUE TITLE
ion-select shown as alert when specifying multiple=true and interface=popover

### ISSUE THREAD

**Issue by DrSensor** [ionic-team/ionic#12403]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`ion-select` shown as `alert` when specifying `multiple="true"` and `interface="popover"`

**Expected behavior:**
`ion-select` must be shown as `popover` when specifying `multiple="true"` and `interface="popover"`

**Steps to reproduce:**
- http://plnkr.co/edit/QDQCgyxCP9FnrngwXreI?p=preview

**Related code:**
```html
    <ion-select placeholder="Checkbox popover/dropdown" interface="popover" multiple="true">
      <ion-option>1</ion-option>
      <ion-option>2</ion-option>
      <ion-option>3</ion-option>
    </ion-select>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v7.7.3
    OS         : Linux 4.8
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.1.2 
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this. Does it work if you remove the `multiple: true` option?

**Comment by cimenx** [comment]
Yes it work, but its behaving like radio option

Pada tanggal 20 Jul 2017 2.28 AM, "Justin Willis" <notifications@github.com>
menulis:

**Comment by brandyscarney** [comment]
This is actually on purpose. In the documentation for Select here: http://ionicframework.com/docs/api/components/select/Select/#multiple-value-checkboxes

It states:

> Note: the `action-sheet` and `popover` interfaces will not work with a multi-value select.

**Comment by brandyscarney** [comment]
Updated the issue to a feature request. Thanks!
