### ISSUE TITLE
Ionic 3.5 Black Screen on QQ Browser 7.7.0.3440

### ISSUE THREAD

**Issue by Immortalt** [ionic-team/ionic#12406]
I developed an ionic3.5 website and publish it using
ionic cordova build browser --prod
It can display well except in QQ Browser(in Android)
How can I solve this problem?
The URL of my website is:
https://talk.immortalt.com

**Comment by Immortalt** [comment]
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.0
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : browser 4.1.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.1.0

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! At this time the QQ browser is not one of our officially supported browsers, so unfortunately i cannot provide direct support for this. But, https://conferenceapp-176d4.firebaseapp.com/#/tabs/schedule/schedule, which is our flagship demo app currently does work for me on the qq browser on my Nexus 6, so it does not look like this is an issue in ionic-angular, but in your code. Sorry that we cannot provide direct support, but you may be able to get help on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).
