### ISSUE TITLE
Angular 4.3 support

### ISSUE THREAD

**Issue by mcm-ham** [ionic-team/ionic#12405]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request

**Request:**
We have a mostly angular setup but using a few components from the ionic framework since we're building a desktop and mobile website from the same core. So we were wandering if ionic will support angular 4.3 anytime soon, we're interested in making use of the new features that HttpClient brings.

Is there a reason not support any angular minor version greater than the minimum that ionic requires since Angular is semver? I notice another angular component library we use simply use `peerDependencies: { "@angular/common": "^4.0.0" }` in packages.json allowing us to use whatever version we want.

**Comment by aks0020** [comment]
Have you tried manually updating angular version in `package.json` to 4.3.0 ? since angular 4+ is following SEMVER it should work without breaking changes ideally. I don't know why ionic is using fixed version by default. it should use `^4.x.x` by default.

**Comment by danielsogl** [comment]
This PR is open over a month now: https://github.com/ionic-team/ionic/pull/12000

**Comment by astec** [comment]
@aks0020 there is a closed but not resolved issue with Angular 4.2+ support - https://github.com/ionic-team/ionic/issues/12330 that prevents manual upgrade. @jgw96 could you please re-open?

**Comment by mcm-ham** [comment]
Thanks @aks0020 I have tried changing `package.json` to `4.3.0` to see if it causes any problems and everything seemed to work ok. However since I'm working on commercial software that's sold I'm required to stick to dependencies packages specify they work with.

**Comment by astec** [comment]
@mcm-ham did it work if you do the --prod build? I wonder if issue https://github.com/ionic-team/ionic/issues/12330 is resolved.

**Comment by mcm-ham** [comment]
@astec We're not building an ionic mobile phone app, we're just borrowing some components for a mobile website using our own webpack build setup. So I haven't tested your scenario.

**Comment by jgw96** [comment]
Hello all! At this time we do not support the latest release of Angular. We always release with the version of Angular that we did all of our testing for that release with, so sometimes we may be a few versions behind the latest version of Angular. While we always strive to be on the latest of Angular, rxjs etc, we would rather ship something that has been tested but is a little behind on the version of  Angular were using than ship something that is using the latest of everything, but that has not been tested. We are looking to be on 4.3.x in our next release of ionic-angular. Thanks!

**Comment by wilgert** [comment]
@jgw96 out of curiosity do you mean manual or automated testing?

**Comment by msari1** [comment]
@jgw96 Do you have timeframe for the upcoming 4.3 support - it sucks to patch  4.1.3  (animation bug,..) manually.

**Comment by kensodemann** [comment]
Hello all!

Short answer: timeframe is yesterday
Long answer: https://blog.ionic.io/updates-for-all-ionic-angular-3-7-and-more/

Be sure to grab `ionic-angular@3.7.0` and `@ionic/app-scripts@3.0.0` and also follow the other instructions in the post.

**Comment by astec** [comment]
@kensodemann , please have a look to this issue: https://github.com/ionic-team/ionic/issues/13014

**Comment by kensodemann** [comment]
@astec - Thx! I have already scheduled #13014 as something to look at for the next release.

**Comment by msari1** [comment]
Ah nice, I have missed that :) thx
