### ISSUE TITLE
npm run ionic:serve: Cannot find module 'buffer-shims'

### ISSUE THREAD

**Issue by karlpatrickespiritu** [ionic-team/ionic#12407]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[X ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`npm run ionic:serve` works just fine before I tried to get a build on ios. After I created a build. I tried to do `npm run ionic:serve` again. Then gives me this error:

```javascript
module.js:471
    throw err;
    ^

Error: Cannot find module 'buffer-shims'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

**Expected behavior:**
Should just serve fine.

**Steps to reproduce:**
Try to build ios first:
sudo ionic cordova platform remove ios
sudo ionic cordova resources --icon
sudo ionic cordova platform add ios
sudo ionic cordova build ios --release

Then after build do:
`npm run ionic:serve`

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 5.2.2 ios 4.4.0
    Ionic Framework                 : ionic-angular 2.3.0

System:

    Node       : v6.9.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.3.0
```

**Comment by wbhob** [comment]
`rm -r node_modules; rm package-lock.json; npm install` in your shell

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1131

**Comment by karlpatrickespiritu** [comment]
Well, that worked. Thanks @wbhob!

**Comment by wbhob** [comment]
Can you please close the app scripts issue @jgw96?
