### ISSUE TITLE
Live reload does not working as expected, have to save several times the file to get it work

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#12409]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The sample app I created for you, is using your sidemenu starter template. I changed the pages to `IonicPage's` and use them for `lazyloading`. Also the `HomePage` has a Button to open a ModalPage which is also lazy loaded.

![image](https://user-images.githubusercontent.com/3778892/28373664-2021913e-6ca3-11e7-884d-9a87db3410d1.png)

The current behavior is, if we change anyhting in the for example `home.html` like button color, the framework is reloading the app in the chrome browser, but the changes are not applied. We have to save several times the file to get the livereload work and see the changes in browser.

We are not sure what is the reason for that, but at our normal production app where we had this bug after upgrade ionic-angular, it looked like this problem is only on lazy loaded `ModaPages`, for that reason this demo app has a ModalPage included. But on this example I'm sharing here we have the problem also on the simple `home.html` file.

Sometimes we also get a old old page in the browser, for example the file as it was 5 or 6 save events earlier. :call_me_hand: 

**Steps to reproduce:**
I created a simple repository to reproduce the error:
https://github.com/mburger81/modal-page-live-reload
(please test it :+1:)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:
    @ionic/cli-utils : 1.5.0
    Ionic CLI        : 3.5.0

local packages:
    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Ionic Framework                 : ionic-angular 3.5.3

System:
    Node       : v6.11.1
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.3.0 

```

**Edit**
I'm using latest chrome: 
Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by mburger81** [comment]
OMG: I'm testing now again the demo app I shared here, and at the moment I can't reproduce the issue anymore. :sob:

Does anyone have a similar issue, or see this in the last time?

**Comment by Sampath-Lokuge** [comment]
Me too have this issue.I'm using latest `Ionic 3.5.3`.For me, this is mostly for the `.ts` files.I think this is happening due to reloader doesn't wait till we'll finish our changes.I don't know whether is this normal behavior of the live reloader.

**Comment by mburger81** [comment]
https://forum.ionicframework.com/t/page-lazy-loading-ionic-livereload-of-typescript-code-not-working/98593/5

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1132
