### ISSUE TITLE
bug(nav-controller): remove() never sets isTransitioning back to false

### ISSUE THREAD

**Issue by zakton5** [ionic-team/ionic#12410]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
When calling `remove()`, future navigation methods no longer work. This is because the `isTransitioning()` method returns true on subsequent calls.

**Expected behavior:**
I expect remove to work

**Related code:**
This is the code I was using when I encountered the problem
```
this.navCtrl.push(page, params).then(() => {
  this.navCtrl.remove(this.sideNav.length() - 2, 1);  
});  
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : windows 5.0.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.9.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13 
    npm        : 3.10.8

**Comment by zakton5** [comment]
I am making a PR for this

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind updating to our [latest release](https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#353-2017-07-14) and giving this another try please?

**Comment by zakton5** [comment]
Ah wonderful, that works! My apologies, I thought I already had updated to the latest.

**Comment by supryin** [comment]
I am still facing this issue. Ionic-angular 3.5.3.
isTransitioning is still true after remove
