### ISSUE TITLE
Not able to download app code from ionic view 

### ISSUE THREAD

**Issue by guessmyfuture** [ionic-team/ionic#12413]
I am using ionic 2 to build my app. I have uploaded my app to ionic view. My app id is **779eb729**

I lost my code locally.

How can i download the code uploaded to ionic view?

I have tried the following

1. Entering app Id to download it as a zip using the below link.

https://apps.ionic.io/settings/data

Getting error as below.

`<Error>`
`<script/>`
`<Code>NoSuchKey</Code>`
<Message>The specified key does not `exist.</Message>`
`<Key>e5ca31a4-6c38-11e7-8adb-0a16d4594913.zip</Key>`
`<RequestId>214F9C8D72CC27EF</RequestId>`
`<HostId>`
`m7KAm/NPBiADxHzhMs8z9lbqHEQni+4wvxRHNlK+tyTH9JHDcsW95hhqth87u2Ds7XrpJZCbwoU=`
`</HostId>`
`</Error>'

2. Using ionic view app.

I dont seee my apps listed in the app when i click on load app.

I can see the list when i log into pc, not in mobile app.

Can u pls help me in downloading the app. My app id is **779eb729**

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind opening a ticket [here](https://ionic.zendesk.com/hc/en-us/requests/new?ticket_form_id=632068) please? Thanks!
