### ISSUE TITLE
stop ion-range slider from sliding when some condition met

### ISSUE THREAD

**Issue by kanishka801mehta** [ionic-team/ionic#12418]
Hello Team,

I am using ion-range slider of ionic2, everything works perfectly but i want to know how can i stop ion-range slider from sliding/dragging when some condition fullfil, for example if difference between my upper and lower value is 30 step, it will stop dragging.

Difference i will calculate at my end but i want how to make slider ill not move then.

Thanks in advance!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
