### ISSUE TITLE
Add `console.log` with hint to use `--prod` for non-prod builds

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic#12417]
**I'm submitting a ...**  
[ ] bug report
[x] feature request

**Current behavior:**
Many new users don't know they should be using `--prod` to get an app with a faster startup time.

**Expected behavior:**
A `console.log` output for non-prod builds that says something like "Add `--prod` to your build command for faster app boot time" on startup could help to point them into the right direction.

**Comment by jgw96** [comment]
Hey @janpio , I think this is a great idea. As this would be something that would have to be implemented in app-scripts and not the framework, im gonna move it over to app-scripts.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1136
