### ISSUE TITLE
Use custom colors for ranges / ionic components

### ISSUE THREAD

**Issue by HugoHeneault** [ionic-team/ionic#12424]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I would like to set custom colors for my ranges, based on dynamic server config. But I can't.

**Expected behavior:**
This code should be working:

```
<ion-range [(ngModel)]="singleValue" [color]="user.profile.color" pin="true"></ion-range>
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by HugoHeneault** [comment]
I don't understand why this is not a feature request. Should this be working? Thanks!

**Comment by HugoHeneault** [comment]
@jgw96 Could you please explain me why this feature request is a support question? 
I asked my question on both but got no answer, and I think it's not supported by ionic currently. 
Thank you very much!
