### ISSUE TITLE
Ionic infinite-scroll not fired on landscape

### ISSUE THREAD

**Issue by Alb93** [ionic-team/ionic#12421]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Ionic infinite-scroll is not fired when the device (real android one but also within chrome) is in landscape mode.

**Expected behavior:**
Ionic infinite-scroll is fired when the device is in landscape mode.

**Steps to reproduce:**
Create a list of cards by copying the "social card" in the official guide. Append as the last element of the content an infinite-scroll. Try to fire the infinite scroll when landscape mode is set

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 browser 4.1.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We will look into this. Does this issue only happen on Android?

**Comment by Alb93** [comment]
Now I can only test it on Android and on the browser simulating the iOS platform.
The infinite scroll is there (there are some white pixels) but never fired in landscape.

**Comment by Alb93** [comment]
It works in ios, both portrait and landscape mode. With android still not works on landscape.
I'm also not able to show the `<ion-infinite-scroll-content loadingSpinner="bubbles" loadingText="Loading..."
      ></ion-infinite-scroll-content>`, never.
