### ISSUE TITLE
@angular/common/http module not found in ionic

### ISSUE THREAD

**Issue by Mackolicious** [ionic-team/ionic#12422]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Creating a new ionic 2 app does not include the angular/common/http module

**Expected behavior:**
- the common http module should exist here node_module/angular/common

**Steps to reproduce:**
- npm install -g cordova ionic
- ionic start myApp tabs
- cd myApp
- cd node_modules/angular/common (no http module exists)

**Related code:**

```
import { HttpClientModule } from '@angular/common/http';
```

**Other information:**

 etc. -->

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v6.11.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.7.1

```
![ng-error](https://user-images.githubusercontent.com/25466120/28420739-0102a50a-6d5b-11e7-9ae6-3f2fbfe2593d.png)

**Comment by danielsogl** [comment]
HTTPClient comes with Angular 4.3 but  Ionic uses 4.1.3 so you can't use the new HTTPClient

**Comment by Mackolicious** [comment]
Thanks for your response
