### ISSUE TITLE
Ionic Account stopped working when I changed my linked email address

### ISSUE THREAD

**Issue by jordanpurinton** [ionic-team/ionic#12423]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Today, I attempted to change my email linked to my ionic account, however, now when I try logging in with either my old or newer email address, the login is invalid.

I already attempted to reset the password for both accounts, but the email told me that an Ionic account doesn't exist for either email address.

Any Ionic team members on here that can help me out?

Ionic info:

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.0
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.10.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Would you mind opening up a ticket with us [here](https://ionic.zendesk.com/hc/en-us/requests/new?ticket_form_id=632068) please? Thanks!
