### ISSUE TITLE
Add property for disable url changing

### ISSUE THREAD

**Issue by Hofmanix** [ionic-team/ionic#12439]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Every change in page changes url, no matter what, only option to change it is to pass updateUrl: false to navigation options

**Expected behavior:**
Create option in IonicModule config (eg. urlDisabled: true) to stop url changes in whole app

**Other information:**
I have app, which i want to publish to mobile devices and also to web, but it will be a game and on the web i don´t want to show url changes, this would really help me

**Comment by Sampath-Lokuge** [comment]
#https://github.com/ionic-team/ionic/pull/12440

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#279

**Comment by keithdmoore** [comment]
@jgw96 above link is broken
