### ISSUE TITLE
phoneCall plugin.I want to stay same page

### ISSUE THREAD

**Issue by mtayyip** [ionic-team/ionic#12431]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ x] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I want to use phone call and import phoneCall plugin.
But this plugin click call button , push the phone call screen.

**Expected behavior:**
I want to stay same page click the button and call process is statusBar v.s..
How is that?

**Other information:**
![ios7-1-beta-3-yenilikler-indir-iphone-ipad-ipod-touch](https://user-images.githubusercontent.com/17318742/28466577-91ad51f6-6e35-11e7-980a-5dec07b15da7.jpg)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by mtayyip** [comment]
Thank you,I'm waiting to hear from you.
