### ISSUE TITLE
Rendering error in Headings ÜÄÖ --> UAO

### ISSUE THREAD

**Issue by Martin-Luckow** [ionic-team/ionic#12436]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[X ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Code like

```
<ion-item text-wrap no-lines padding>
  <ion-radio [(value)]="level.id" checked></ion-radio>
  <div item-content>
    <h2 class="introTitle">
      Ü or Ä or Ö
    </h2>
    <p class="introDescription">{{ lang.val(level.description) }}</p>
  </div>
</ion-item>
```

lead to `"beheaded" Ü, Ä, Ö,` i.e. the dots are missing.
REASON:
In the generated CSS you will find 

```
[padding] h1:first-child, [padding] h2:first-child, [padding] h3:first-child, [padding] h4:first-child, [padding] h5:first-child, [padding] h6:first-child {
  margin-top: -0.3rem;
}
```

**Expected behavior:**
`Ü, Ä, Ö` would appear as `Ü, Ä, Ö` :)

**Steps to reproduce:**
See above

Remarks:
COOL FRAMEWORK!!!!

**Comment by jgw96** [comment]
First, thanks for the `remarks` section haha 😃. Does this also happen in a regular angular app, or only in ionic-angular?

**Comment by Martin-Luckow** [comment]
Hi Justin.
Its only in ionic-angular. See the "[padding]..."-CSS above. 
If I switch off the statement "margin-top: -0.3rem;" it works. 
If I switch it on, it moves the uper clipping border of the heading downwards to the chars and that kills the dots of an Ü :)
