### ISSUE TITLE
http://localhost:8100/ionic-lab is impossible to use

### ISSUE THREAD

**Issue by DiegoNovati** [ionic-team/ionic#12443]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
http://localhost:8100/ionic-lab doesn't work properly with 
    Ionic Framework: 3.5.3
    Ionic App Scripts: 2.0.2
    Angular Core: 4.1.3
    Angular Compiler CLI: 4.1.3

**Expected behavior:**
See the App in the browser without overlay and errors

**Steps to reproduce:**
1. Create a new project: 
    ionic start MyNewApp blank

2. Start it
   ionic serve -lab 

   The browser displays the following: 
<img width="804" alt="ionicnewapp" src="https://user-images.githubusercontent.com/19746712/28490372-61b699f8-6ed0-11e7-85be-2428675a3d85.png">

  Clicking on the "Back" button this is the result:
<img width="806" alt="ionicnewapp2" src="https://user-images.githubusercontent.com/19746712/28490383-c0e99ede-6ed0-11e7-97d5-cbafe5b6a4f2.png">

For Ionic V1 issues - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

For Ionic issues - http://plnkr.co/edit/cpeRJs?p=preview
-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
global packages:

    @ionic/cli-utils : 1.5.0
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v7.6.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    npm        : 4.3.0
```

**Comment by wbhob** [comment]
That is either a config issue, or a code issue, not an Ionic issue. Please close this and ask on the forums.

**Comment by mhartington** [comment]
Part of this seems like a css-build issue that has just been fixed. Please `rm -rf node_modules` and run `npm install` again.

**Comment by DiegoNovati** [comment]
I confirm that it has been fixed. Thank you
