### ISSUE TITLE
Can’t install production app on iOS

### ISSUE THREAD

**Issue by royibernthal** [ionic-team/ionic#12448]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Issue:**
I'm not sure if this is a bug, so just in case I'm sending it here as well as in the forum.

I'm building my app for iOS using ionic package.

https://docs.ionic.io/services/package/

I created certificates for both development and production, including push.

https://docs.ionic.io/services/profiles/

development - built successfully using ionic package, installed on iOS with no problem.

production - built successfully using ionic package, when I try installing it on iOS it starts installing the app normally, then when almost finished the app disappears and it ends up not being installed, no errors appear.

Why does it happen?

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.9.5
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10
```

**Comment by Sampath-Lokuge** [comment]
@royibernthal How can you install production version on your device? You must send it to iTunes(apple store) and then you need to install it from there.

**Comment by royibernthal** [comment]
I'm installing via iTunes the same way I'm doing with development version. Is that not supposed to work?

**Comment by Sampath-Lokuge** [comment]
@royibernthal OK.Sorry, I didn't get your question exactly.Hope someone will answer your question.

**Comment by royibernthal** [comment]
@Sampath-Lokuge Would you like me to try to clarify it or do you understand now and simply don't know the answer?

**Comment by Sampath-Lokuge** [comment]
@royibernthal You're right.I don't have any experience on iOS deployment yet.I would like to ask a question from you.Hope you'll give a feedback for me.Can't you use development version without sending it to the iTunes? On Android device where we can install debugger `apk` manually without putting that into google play.Can't we do it with iOS?

**Comment by royibernthal** [comment]
By iTunes I'm referring to the software that is used by the average apple user to transfer files from iPhone <-> Computer, not to sending it to the app store. In other words, that's exactly what I'm doing, with both development and production.

**Comment by Sampath-Lokuge** [comment]
@royibernthal Ok, if that is the case then you cannot test the production version like that.You have to send it to the apple store for that.After that, you need to install it from there.Hope someone will correct me if I'm wrong here.

**Comment by royibernthal** [comment]
May I know what you're basing that on?

On Android for instance I'm having no problems testing the production version like that.

**Comment by Sampath-Lokuge** [comment]
@royibernthal Can you tell me how do that on Android? I have tried that.But it doesn't allow me to install the production `apk` on my android device.

**Comment by royibernthal** [comment]
I'm literally transferring to my Android device a production apk built with ionic package and installing it, the exact same thing I'm doing with the development version.

**Comment by Sampath-Lokuge** [comment]
@royibernthal I have used this `ionic cordova build android --prod --release` and then it is not working.Next time I'll try the Ionic package.Thanks for the info 👍

**Comment by royibernthal** [comment]
Worth a try, let me know if that works for you. Glad to help.

**Comment by Sampath-Lokuge** [comment]
@royibernthal Thanks.One another question, when we use the ionic package with iOS build, hope we still need the apple account($99.00) no? I mean for creating debug and production builds?

**Comment by royibernthal** [comment]
Yup

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/]). Thanks for using Ionic!

PS: thanks @royibernthal for being a huge help on this issue!

**Comment by royibernthal** [comment]
@jgw96 No problem.

I'm not getting any answers to my questions in those places though.

Do you have any premium / paid support?
