### ISSUE TITLE
Your current PostCSS version is 5.2.17, but autoprefixer uses 6.0.8. Perhaps this is the source of the error below.

### ISSUE THREAD

**Issue by tunathoni** [ionic-team/ionic#12441]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Last night i try to create new project with ionic 3.x version, but there is no bug, today i try to create new project and then try to `ionic serve` the error message show in cli like this : ` "Your current PostCSS version is 5.2.17, but autoprefixer uses 6.0.8. Perhaps this is the source of the error below." ` what should i do ? please help me, ASAP. Thanks.

**Expected behavior:**

if it normal it will be run well, i think it's newest bug in ionic CLI.

**Steps to reproduce:**

**Related code:**

```
$ionic serve

16:11:46]  watch started ...
[16:11:46]  build dev started ...
[16:11:46]  clean started ...
[16:11:46]  clean finished in 2 ms
[16:11:46]  copy started ...
[16:11:46]  transpile started ...
[16:11:49]  transpile finished in 2.98 s
[16:11:49]  preprocess started ...
[16:11:49]  deeplinks started ...
[16:11:49]  deeplinks finished in 20 ms
[16:11:49]  preprocess finished in 22 ms
[16:11:49]  webpack started ...
[16:11:49]  copy finished in 3.28 s
[16:11:58]  webpack finished in 8.96 s
[16:11:58]  sass started ...
Your current PostCSS version is 5.2.17, but autoprefixer uses 6.0.8. Perhaps this is the source of the error below.
[16:11:59]  dev server running: http://localhost:8101/

[INFO] Development server running
       Local: http://localhost:8101
```

**Comment by luciorubeens** [comment]
Same issue..

**Comment by tunathoni** [comment]
Hopefully it will be fix soon. :(

**Comment by AbanoubNassem** [comment]
same here ,

more details tho

`Your current PostCSS version is 5.2.17, but autoprefixer uses 6.0.8. Perhaps thi
s is the source of the error below.
[12:08:02]  ionic-app-script task: "build"
[12:08:02]  TypeError: Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:186:7)
    at eachParent (C:\Users\Abanoub\Desktop\myApp\node_modules\browserslist\inde
x.js:65:18)
    at getStat (C:\Users\Abanoub\Desktop\myApp\node_modules\browserslist\index.j
s:79:12)
    at browserslist (C:\Users\Abanoub\Desktop\myApp\node_modules\browserslist\in
dex.js:188:15)
    at Browsers.parse (C:\Users\Abanoub\Desktop\myApp\node_modules\autoprefixer\
lib\browsers.js:61:16)
    at new Browsers (C:\Users\Abanoub\Desktop\myApp\node_modules\autoprefixer\li
b\browsers.js:52:30)
    at loadPrefixes (C:\Users\Abanoub\Desktop\myApp\node_modules\autoprefixer\li
b\autoprefixer.js:67:24)
    at plugin (C:\Users\Abanoub\Desktop\myApp\node_modules\autoprefixer\lib\auto
prefixer.js:78:24)
    at LazyResult.run (C:\Users\Abanoub\Desktop\myApp\node_modules\@ionic\app-sc
ripts\node_modules\postcss\lib\lazy-result.js:274:20)
`

**Comment by Justinzhq** [comment]
Same too ...

**Comment by VictorBac** [comment]
Same here

**Comment by huadeang** [comment]
same issue

**Comment by pvdyck** [comment]
any downgrade solution ?

**Comment by shadeeka** [comment]
Same issue here.. 
any solution for this ? running npm install on any ionic 2  project will face the issue.

**Comment by barissonmez** [comment]
Same issue

**Comment by erdemozveren** [comment]
Hi,I changed my package.json part with my old project's package.json and it worked for me
```
 "dependencies": {
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@ionic-native/background-mode": "^3.6.1",
    "@ionic-native/core": "^3.6.1",
    "@ionic-native/local-notifications": "^3.6.1",
    "@ionic-native/splash-screen": "3.4.2",
    "@ionic-native/status-bar": "3.4.2",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.0.1",
    "ionicons": "3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.0",
    "typescript": "~2.2.1"
  },
```

**Comment by SaurabhLele** [comment]
Same issue..

**Comment by tunathoni** [comment]
Hi @erdemozveren , i've tried change package.json but still the same. You only change package.json ? or any other file you've changed ?

**Comment by fifafu** [comment]
You ned to downgrade @ionic/app-scripts to version 1.3.7 for now. (rm -rf node_modules first)

**Comment by erdemozveren** [comment]
@tunathoni  I only change my package.json and delete my node_modules then type npm install.That's all.

**Comment by pvdyck** [comment]
@fifafu confirmed ! downgrade to 1.3.7 did the trick. thx.
Any explanation ? ( some npm cross dependency overnight update ? )

**Comment by tunathoni** [comment]
Hi @erdemozveren thanks for your help. It's worked properly.. Thank you so much. 👍

**Comment by tunathoni** [comment]
@pvdyck i think npm update overnight, so it caused any issue.

**Comment by ravindranrahul** [comment]
@pvdyck i think so, scared the sh*t out of me though!

**Comment by pvdyck** [comment]
the problem comes from autoprefixer.
In ionic/app-scripts to version 1.3.7 it links to  "autoprefixer": "6.7.2"
In 1.3.8 to "autoprefixer": "7.1.1"
The change is here https://github.com/ionic-team/ionic-app-scripts/commit/ccb4042d6000af5a5dfa2179b75a25e5eea87e7c

Neither postcss or autoprefixer were updated overnight it must come from one of their dependencies ( or dependencies of dependencies) 

possible candidate : browserlist / updated 5 hours ago

**Comment by pvdyck** [comment]
confirmed https://github.com/ai/browserslist/issues/158

**Comment by pvdyck** [comment]
@tunathoni  please do not close the issue

**Comment by tunathoni** [comment]
Ok @pvdyck i'll make it open again

**Comment by mhartington** [comment]
Closing as this related to app scripts, not the framework. Will continue this over there

**Comment by pvdyck** [comment]
please link to issue in app scripts

**Comment by KishuPro** [comment]
Hey guys, lets refer to this link only as it is in the proper category: https://github.com/ionic-team/ionic-app-scripts/issues/1142

**Comment by malaotou** [comment]
Search the issue for half a day!!!!!!!!!!!!!!!!!

**Comment by w3icon** [comment]
Changing app scripts version to 1.3.7 kind of works - but doesn't create the vendor.js file in build - console shows 404 not found error!

**Comment by abdulrahmanasmuei** [comment]
same issue here...any solution ?

**Comment by aubinho93** [comment]
You need to downgrade ionic/app-scripts to version 1.3.7 for now. (rm -rf node_modules first)
--
this worked for me!

**Comment by tunathoni** [comment]
The final way is change your package.json and find `"devDependencies": { ... ` then change `"@ionic/app-scripts":` to `"@ionic/app-scripts":"1.3.7"`

**Comment by pvdyck** [comment]
solution is coming => https://github.com/ai/browserslist/pull/159

**Comment by iamadhihere** [comment]
You need to downgrade ionic/app-scripts to version 1.3.7 for now.

this worked for me too!
thanks

**Comment by cmargulhano** [comment]
Same here. I will try to downgrade to version 1.3.7 👍

**Comment by dovk** [comment]
After wasting a few hours trying to figure out what I did wrong, I go to this page - I wonder if there is an email alert when these things happen. Thank you to the person that figured out that going down to 1.3.7 would allow us to continue for now.

**Comment by pvdyck** [comment]
What happened is related to unconstrained transitive dependencies. 

Some npm libraries are published with "^version" numbers and depends on the very last and untested version of another library. Upgrade is automatic if version numbers are unconstrained. 

Welcome to npm ;-)

**Comment by atopus** [comment]
Well, downgrading to app-script 1.3.7 did not work for me. Tried twice, and same result :+1: 

```
[ERROR] app-scripts serve unexpectedly failed.settings: undefinedcontext: [object
        Object]
```
 Any idea ? (and thanks by the way to the npm / ionic community) ;)

**Comment by IhsanSayim** [comment]
Changing ionic/app-scripts to version 1.3.7 worked for me but i have another issue like this:

**Comment by Nayami** [comment]
Changing package.json partly solve this issue, but now "vendor.js" not found

**Comment by dovk** [comment]
Yes, that was shortlived as we need vendor.js ... but I followed the advice above qnd did pm install browserslist@2.2.0 --save and that seemd to help, though it is having other problems with forms...

**Comment by mhartington** [comment]
https://github.com/ionic-team/ionic/issues/12441

**Comment by mhartington** [comment]
This should be fixed now. Please upgrade back to the latest version of app-scripts, and reinstall your node-modules.

**Comment by atopus** [comment]
@mhartington Yes, it works now with app-scripts 2.0.2
