### ISSUE TITLE
feat(nav): Add url for modals

### ISSUE THREAD

**Issue by Daskus1** [ionic-team/ionic#12444]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] feature request

**Current behavior:**
Currently when opening a page as a modal the URL does not change, thus when refreshing the page the modal is not opened.

**Expected behavior:**
It would be awesome if a page opened with the `ModalController` would be part of the URL.

Let's say I'm on Page1, the URL looks like this:
`http://localhost:8100/#/nav/page1`
Now a user opens a second page with the ModalController and the URL could change to something like:
`http://localhost:8100/#/nav/page1/modal/page2`
The `/modal/` is needed to identify that this is a modal page, so the modal is opened on top of Page1, when the user refreshes the page. But of course this detail is going to be decided when being implemented.

If we don't want this behavior as the default one, we could add a property `showModalsInURL` to the config.

This would drastically improve userexperience on webapps that use modals for detail or edit views.

I think this is a good moment to implement this feature as you are currently working on refactoring, fixing and improving the navigation of Ionic.

**Comment by AmitMY** [comment]
imo modals should not be routed to, it seems odd. 
@danbucholtz thoughts?

**Comment by Daskus1** [comment]
@AmitMY I think this really depends on the app. 
If you want to show the user a detail page with just a small amount of information it's not good user experience if the user gets to a completely new page. Modals are the perfect way to show such things in a quick and nice way. But what if the user wants to get directly to that detail page?
As I proposed **this should only be optional** and could be activated with a config flag.

**Comment by jgw96** [comment]
Hello, all. I tend to agree with @AmitMY that modals should not really be routed too. Modals are kind of like an alert, and I don't think you would want to route to an alert. But, this might be something that we could think about making optional. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks everyone!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#278
