### ISSUE TITLE
How can I know the  builded filename of a lazy load page ?

### ISSUE THREAD

**Issue by hellogithub2014** [ionic-team/ionic#12449]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Other information:**
1. While in ionic3, if I made a page lazy load, after the build process, there will be a corresponding js file generated in the  www/build folder.  
2. Now I want to customize my build process, for some reason I need to know the corresponding builded js filename of every lazy load page. What should I do?  For example, when PageA is lazy load, which file in www/build is the js filename of PageA.
3. I'm trying to read the source code of app-scripts, but if anyone of you guys can tell me, I think 
the efficiency will be more higher. 
4. Thanks for any help!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
