### ISSUE TITLE
Popover doesn't close while swiping on IOS

### ISSUE THREAD

**Issue by AleksandrChernyavenko** [ionic-team/ionic#12453]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Open popover, then swipe on aria outside of popover content.
Result: page scrolling, popover present

**Expected behavior:**
Close popover

**Steps to reproduce:**
Can be reproduced using ionic-preview-app Popover
 https://github.com/ionic-team/ionic-preview-app
( need  build for IOS - iPhone 6 )

Video to reproduce - https://drive.google.com/open?id=0B8XIoiu_hafMMjFrc3c1UmI2THM

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```



global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.2

System:

    Node       : v8.1.4
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.3.0 

```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by AleksandrChernyavenko** [comment]
@jgw96 Why you add label "v2", not "v3" ?  I use `ionic-angular 3.5.2`
