### ISSUE TITLE
Descriptive naming convention for chunks

### ISSUE THREAD

**Issue by longgt** [ionic-team/ionic#12455]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When I build PWA project with n lazy loading module with `npm run build` or `npm run build --prod`, I see something like this in _build_ folder:

```
0.main.js
1.main.js
...
n.main.js
main.js
```

However, it's difficult to know which chunk is coming from which lazy module.
I tried to modify webpack.config.js in folder ionic/app-scripts/config with the following setting

```
chunkFilename: '[name].main.js'
```
but the name of chunk file is same as above.

**Expected behavior:**

Chunk file name having information about where it's coming from. (lazy module name or base name in location)

**Steps to reproduce:**

**Related code:**

**Other information:**

[https://github.com/angular/angular-cli/issues/6700](url)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:
    @ionic/cli-utils : 1.5.0
    Ionic CLI        : 3.5.0

local packages:
    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Ionic Framework                 : ionic-angular 3.5.3

System:
    Node       : v6.11.0
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.2.0
```

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#280
