### ISSUE TITLE
3.5: ionViewWillEnter trigger not fired when setting location in browser

### ISSUE THREAD

**Issue by mzealey** [ionic-team/ionic#12457]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I'm using ionic 3.5.3's new location code and trying to handle the case where a user visits a link but is not logged in.

Post login I can't just `setRoot('page', { opts })` any more as this is under some tabs. It seems like the best way is to save `location.hash` prior to showing the login page, and then set it after leaving it.

`location.hash = ...` changes to the page correctly after login, but the `ionViewWillEnter` and `ionViewDidEnter` triggers are not fired.

Whilst I think this bug needs fixing, a nicer solution than manually setting `location.hash` would be to store `location.hash` and have eg a `rootNavCtrl.setFromHash()` function which would parse out the segments and any data associated with each page under it; and/or the ability to take a full status of the path to the current page (controllers and paramater settings) and replicate it later.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Would you mind posting a minimal repro case we could use to reproduce this issue?

**Comment by mzealey** [comment]
3.6 appears to fix this once manually patched the issue in https://github.com/ionic-team/ionic/issues/12526
