### ISSUE TITLE
bug: Unable to set enableBackdropDismiss to false for modals

### ISSUE THREAD

**Issue by gvhuyssteen** [ionic-team/ionic#12459]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

```
let modal = modalCtrl.create(SomePage, {}, { enableBackdropDismiss: false });
modal.present();
```
In Chrome (Version 59.0.3071.115 (Official Build) (64-bit)), I inspected `$ ionic serve` and enabled the device toolbar through DevTools with iPad Mini selected.
The modal appears, but clicking on the backdrop, the modal closes.

**Expected behavior:**

The modal appears and clicking on the backdrop will not close the modal.

**Steps to reproduce:**

Using the latest Ionic (v3.5.3), I ran the application in the browser using `$ ionic serve` command and through Chrome DevTools, I inspected the application and turned on the Device Toolbar with the iPad Mini device selected.

I also added a log to `ModalCmp` class in the generated `www/vendor.js` file to ensure that the option is pulling through.

The `this._bdDismiss` private variable stays true and does not allow me to change the default option.

**Related code:**

```
function ModalCmp(_cfr, _renderer, _elementRef, _navParams, _viewCtrl, gestureCtrl, moduleLoader) {
        this._cfr = _cfr;
        this._renderer = _renderer;
        this._elementRef = _elementRef;
        this._navParams = _navParams;
        this._viewCtrl = _viewCtrl;
        this.moduleLoader = moduleLoader;
        var opts = _navParams.get('opts');
        (void 0) /* assert */;
        this._gestureBlocker = gestureCtrl.createBlocker({
            disable: [__WEBPACK_IMPORTED_MODULE_4__gestures_gesture_controller__["d" /* GESTURE_MENU_SWIPE */], __WEBPACK_IMPORTED_MODULE_4__gestures_gesture_controller__["b" /* GESTURE_GO_BACK_SWIPE */]]
        });
        this._bdDismiss = opts.enableBackdropDismiss;

        console.log('------------------------');
        console.log(_navParams.get('opts'));
        console.log(this._bdDismiss);

        if (opts.cssClass) {
            opts.cssClass.split(' ').forEach(function (cssClass) {
                // Make sure the class isn't whitespace, otherwise it throws exceptions
                if (cssClass.trim() !== '')
                    _renderer.setElementClass(_elementRef.nativeElement, cssClass, true);
            });
        }
    }
```

**Other information:**

<img width="889" alt="screen shot 2017-07-25 at 06 06 53" src="https://user-images.githubusercontent.com/1265536/28555336-8aa5fd14-70ff-11e7-9efb-27ebe6152b70.png">

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.0.8
    npm        : 3.10.10
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Unfortunately, I am not able to reproduce this issue. Would you mind posting a repo we could use to reproduce this issue?

**Comment by gvhuyssteen** [comment]
@jgw96 
Thanks.  I created a brand new project and could not re-create the issue.
Closing this issue.
