### ISSUE TITLE
I can't add plugin 

### ISSUE THREAD

**Issue by xiekong** [ionic-team/ionic#12451]
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v8.1.4
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3

E:\Ionic\HxWaterApp>ionic cordova plugin add cordova-plugin-camera
> cordova plugin add cordova-plugin-camera --save
× Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova plugin add cordova-plugin-camera --save (exit code 1):

        Error: Failed to fetch plugin cordova-plugin-camera via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! Maximum call stack size exceeded

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-07-24T07_44_12_321Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'cordova-plugin-app-version',
1 verbose cli   '--save' ]
2 info using npm@5.0.3
3 info using node@v8.1.4
4 verbose npm-session a1701f060ef547b4
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/cordova-plugin-app-version 791ms (from cache)
8 silly pacote tag manifest for cordova-plugin-app-version@latest fetched in 824ms
9 verbose stack RangeError: Maximum call stack size exceeded
9 verbose stack     at exports.create (D:\Program Files\nodejs\node_modules\npm\lib\install\node.js:33:25)
9 verbose stack     at D:\Program Files\nodejs\node_modules\npm\lib\install\node.js:36:14
9 verbose stack     at Array.forEach (native)
9 verbose stack     at exports.create (D:\Program Files\nodejs\node_modules\npm\lib\install\node.js:33:25)
9 verbose stack     at D:\Program Files\nodejs\node_modules\npm\lib\install\node.js:36:14
9 verbose stack     at Array.forEach (native)
9 verbose stack     at exports.create (D:\Program Files\nodejs\node_modules\npm\lib\install\node.js:33:25)
9 verbose stack     at normalizeTree (D:\Program Files\nodejs\node_modules\npm\lib\install.js:377:5)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (D:\Program Files\nodejs\node_modules\npm\lib\install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (D:\Program Files\nodejs\node_modules\npm\lib\install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (D:\Program Files\nodejs\node_modules\npm\lib\install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (D:\Program Files\nodejs\node_modules\npm\lib\install.js:379:19)
10 verbose cwd E:\Ionic\HxWaterApp\node_modules
11 verbose Windows_NT 6.1.7601
12 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cordova-plugin-app-version" "--save"
13 verbose node v8.1.4
14 verbose npm  v5.0.3
15 error Maximum call stack size exceeded
16 verbose exit [ 1, true ]

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
