### ISSUE TITLE
Lazy load pages - Error if rename page.ts to page.component.ts

### ISSUE THREAD

**Issue by panakour** [ionic-team/ionic#12464]
I'm new to ionic.

It's more convenient for me to have to all of my pages the component string so I can navigate faster. I did this and all works great but when I stop my app and serve it again later the error below occurs.

**Ionic version:** 
[x] **3.x**

**I'm submitting a ...** 
[x] bug report

**Current behavior:**

> home.component.ts has a @IonicPage decorator, but it does not have a corresponding "NgModule" at home.component.module.ts

**Steps to reproduce:**

1. stop ionic serve.
2. in any page rename from page-name.ts to page-name.component.ts
3. run ionic serve.

**Related code:**

HomePage
```
import { Component } from '@angular/core';
import { NavController, IonicPage } from 'ionic-angular';

@IonicPage()

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController) {

  }

}
```

home module:
```
import { NgModule } from '@angular/core';
import { HomePage } from './home.component';
import { IonicPageModule } from 'ionic-angular';
@NgModule({
  declarations: [HomePage],
  imports: [IonicPageModule.forChild(HomePage)],
})
export class HomePageModule { }

```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We will look into this soon.

**Comment by danbucholtz** [comment]
Hi @panakour,

This is an issue for right now. We have a customizable suffix for each file, so we take whatever the file name is, so `some-page.component.ts`, and then remove the `.ts` and add `.module.ts`, so the file name by default for the ng-module would be `some-page.component.module.ts` in that case.

We will work on making this more customizable in the future.

Thanks,
Dan

**Comment by johannesnormannjensen** [comment]
Hi Dan,

Could it be possible to define the module file in the @IonicPage annotation? 
Maybe something like: 
@IonicPage({
    module: 'some.module.ts'
})
