### ISSUE TITLE
Docs wrong for ionSwipe event on expandable ItemSliding

### ISSUE THREAD

**Issue by jwt02180** [ionic-team/ionic#12467]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X ] documentation error
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I've been trying to add the full-swipe action to a sliding item in a list. When placed on the `<ion-item-sliding>` element as per the [ItemSliding Docs](http://ionicframework.com/docs/api/components/item/ItemSliding/#usage) the ionSwipe event didn't seem to fire properly for me.

The [ItemOptions Docs](http://ionicframework.com/docs/api/components/item/ItemOptions/#usage) **are** correct

**Expected behavior:**
The ionSwipe event should fire when a full swipe occurs on an a list item.

**Other information:**
The documentation says to place the event listener on the `<ion-item-sliding>` element, but the source code fires the event on the `<ion-item-options>` element. This makes sense so you can have the ionSwipe event be set for options on each sliding direction of an item.

_**I'm just asking that the docs get updated to reflect this.**_

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-site#1213
