### ISSUE TITLE
Two the same id in Ionic html layout

### ISSUE THREAD

**Issue by klochko7** [ionic-team/ionic#12466]
Hi all ! Could anyone suggest please .. is it possible to see two the same id Ionic html ?

![ionic_example](https://user-images.githubusercontent.com/8359280/28576905-dff339a4-715d-11e7-881a-b5762a0d8940.jpg)

When it happend I have a problem with javascript,needed page dose not rebuilt, some javascript event dose not run .. I do not understand why ... It happend when I go through pages back and forth,go back ..

My system information:

Сordova CLI: 7.0.1
Ionic Framework Version: 3.5.3
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 2.0.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.0
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
