### ISSUE TITLE
Not getting scroll positions value immediately in ios 

### ISSUE THREAD

**Issue by ajaysaini95700** [ionic-team/ionic#12460]
I am not getting scroll position top value immediately in ios. i get value after scrolling stop. but in android getting value immediately.
please give me solution how to get value on scrolling in ios

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
