### ISSUE TITLE
how to handle token timeout and redirect to login page?

### ISSUE THREAD

**Issue by TonyLuo** [ionic-team/ionic#12461]
**Ionic version:**  (check one with "x")
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")

[x ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

I would like to handle the token timeout issue, and redirect to the login page, but this.navCtrl.push(LoginPage) doesn't work for me
**Related code:**

```
private listenToAuthorizationEvents() {
    this.events.subscribe('user:unauthorized', () => {
     this.redirectToLoginPage();
    });
  }

  private redirectToLoginPage() {
    this.navCtrl.push(LoginPage);

  }
 ```
**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by daveshirman** [comment]
This should be on StackOverflow as a question, not as a support request.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
