### ISSUE TITLE
v3.5.3 App.getActiveNavs() is missing 

### ISSUE THREAD

**Issue by jing-zhou** [ionic-team/ionic#12465]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

App.getActiveNavs() is missing from app.d.ts in version v3.5.3
**Expected behavior:**

according to the v3.5.3 on-line [doc](http://ionicframework.com/docs/api/components/app/App/) , 
App.getActiveNavs() "is preferred when we need access to the top-level navigation controller while on the outside views..."
**Steps to reproduce:**

reproduce and if possible a demo using one of the following templates:
upgrade to v3.5.3, 
this statement in a component file
**Related code:**

```
this.app.getActiveNavs().slice(-1)[0].push('MapPage');
```
will trigger an  non-existing error on "getActiveNavs()"
**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.0.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.4
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3 

```

**Comment by ernofi** [comment]
You have installed ionic-angular version 3.5.0. Update to 3.5.3.

**Comment by jgw96** [comment]
Hey @jing-zhou , @ernofi is correct, it looks like you are still running `ionic-angular 3.5.0`. To update to `3.5.3` you can run `npm install ionic-angular@3.5.3 --save`. Thanks!
