### ISSUE TITLE
ionic cordova platform add ios 

### ISSUE THREAD

**Issue by 395779222** [ionic-team/ionic#12462]
when i run  ionic cordova platform add ios , Always show  '⠋ Running command' never success

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
