### ISSUE TITLE
ViewEncapsulation seems broken in 3.5.3

### ISSUE THREAD

**Issue by Rhonun** [ionic-team/ionic#12478]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Styles in components are bleeding out of the component. E.g. foo.component.ts defines the component with a selector foo-component and has foo.component.scss with some styles defining rules for .list. The .list styles are bleeding out into other components

**Expected behavior:**
The foo.component.scss .list styles should be encapsulated and only applied to the .list class inside the <foo-component></foo-component> element

**Other information:**
Seems like ViewEncapsulation is being set to NONE by default instead of Emulated

**Comment by AmitMY** [comment]
When you generate a component, lets say 'clock', it generates a `clock.scss` file with the following code:
```
clock {

}
```

Put your custom component styles inside the clock for the proper encapsulation you are looking for.
(It seems like you aware that this works, but I am saying that this is the guideline)

There are some changes coming in the next major version that will give you a bit more freedom in your configurations, like this, to tailor to your needs.

**Comment by jgw96** [comment]
Thanks for handling this issue @AmitMY 😃
