### ISSUE TITLE
scss setting issues in android prod mode

### ISSUE THREAD

**Issue by beerchyan** [ionic-team/ionic#12474]
When i setting 35 colors in $color(theme/variables.scss) and run in prod mode, it will become semitransparent when click any where on any pages. But when i set 20 colors app works well.Is there any limit on scss setting? [screenshot in stackoverflow](https://stackoverflow.com/questions/45024275/ionic2-product-mode-in-android-not-work-properly)

**Comment by ramoncarreras** [comment]
If you declare 35 color in theme/variables, ionic-app-scripts will generate css for buttons for this 35 colors, headers for this 35 colors, ion-toggles for this 35 colors, checkboxes for this 35 colors, etc... and this will result into really big compiled css file.

https://github.com/ionic-team/ionic-app-scripts/issues/506

Really you need all this colors? I recommend you to only put colors that you need for buttons, headers, etc.. to your $colors var and declare another var '$colors2' for others.

What I do is the following:

```
$colors: (
        primary: #7eb444,
        secondary: #ec1313
);

$colors2: (
        blanc: #fff,
        grisclar: #c1c1c1,
        blau: #3690c4,
        marroclar: #736965,
        gris: #a6a19d,
        verdblau: #5c8882,
        groc: #f7e90c
);
```

And then...

```
p {
  color: map_get($colors2, marroclar)
}
```

... and ...

```
<button ion-button color="primary">DO SOMETHING</button>
```

**Comment by beerchyan** [comment]
do you mean if i need badge be colorful then i just set 
$colors2: (
        blanc: #fff,
        grisclar: #c1c1c1,
        blau: #3690c4,
        marroclar: #736965,
        gris: #a6a19d,
        verdblau: #5c8882,
        groc: #f7e90c
);

and 

ion-badge {
  color: map_get($colors2, marroclar)
}

am i right?

**Comment by ramoncarreras** [comment]
Sorry for my english. It's not good.
But no, this is not what I mean.

The qüestion is:
Your app shows _ion-badge_ in this 35 colors? _(badge, button, toggle or any component that accepts the color attribute)_

You must reduce your list of colors to the minimum. If you make a search for _**color="**_ inside your src folder, all of that 35 colors appear? **All the colors that you're not using on color attribute must be in another var**, like $colors2.

If you really need to show buttons _(or any ionic component)_ in 35 different colors, I can't help you.

I hope to have explained more clearly.

More info:
https://github.com/ionic-team/ionic/issues/9326

**Comment by beerchyan** [comment]
not such colorful 
i will reduce it 
thx 
: )
