### ISSUE TITLE
NavController docs reference goToRoot(), which does not exist

### ISSUE THREAD

**Issue by c0bra** [ionic-team/ionic#12476]
See here: https://ionicframework.com/docs/3.5.0/api/navigation/NavController/#goToRoot

I am running 3.5.0 currently and got this error: `Property 'goToRoot' does not exist on type 'NavController'.`

Looks like `popToRoot()` does what I want. I looked into updating the NavController docs but wasn't sure if this was a future/deprecated method.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Could you update to 3.5.3 please and see if you still run into this issue?

**Comment by c0bra** [comment]
@jgw96 3.5.3 isn't available on npm yet.

**Comment by c0bra** [comment]
Oh, ionic-angular, not the cli; durr. The cli is on 3.5.0 as well hence my confusion.

**Comment by c0bra** [comment]
@jgw96 yea upgrading to newer ionic-angular fixed it. And I was actually on a much older version than I thought!

Sorry and thanks for your help.
