### ISSUE TITLE
ion-select within *ngFor updates the wrong item

### ISSUE THREAD

**Issue by satocw** [ionic-team/ionic#12471]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`ion-select` within `*ngFor` updates the wrong item

**Expected behavior:**
`ion-select` within `*ngFor` must update the corresponding item.
i.e. First `ion-select` must update the first item.

**Steps to reproduce:**
http://plnkr.co/edit/G7xBVJOLsx0thgoT5MM5?p=preview

When you select one of the options from the first `<ion-select>`, it updates the value of the last item.
I think it should update the value of the first item. Is there any way to get it work?

**Comment by AmitMY** [comment]
`ion-select` is not to be used this way.
This is not because of the ngFor, but because there is no item surrounding it.

```
<ion-item *ngFor="let i of items">
    <ion-label>{{i.val}}</ion-label>
    <ion-select [(ngModel)]="i.val">
      <ion-option value="a">a</ion-option>
      <ion-option value="b">b</ion-option>
    </ion-select>
  </ion-item>
```

Works

**Comment by satocw** [comment]
Thank you for your reply!
Surrounding by `ion-item` worked as I expected.
