### ISSUE TITLE
IE11 Alert Prompt not working

### ISSUE THREAD

**Issue by vandres** [ionic-team/ionic#12475]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Any alerts with prompt do not open on IE11.

**Expected behavior:**

Prompts open on IE11

**Steps to reproduce:**

Open the official doc under http://ionicframework.com/docs/components/#alert-prompt in IE11. Click then the "Show Prompt Alert" button.

**Comment by vandres** [comment]
I found out, if you provide the type, the error is gone in IE11:

```
            inputs: [
                {
                    type: 'text',
                    name: 'description',
                    value: attachment.meta.description,
                    placeholder: ''
                },
            ],
```

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! At this time we do not officially support IE11.
