### ISSUE TITLE
Ionic-native app rate: uses until prompt not working.

### ISSUE THREAD

**Issue by monichols** [ionic-team/ionic#12470]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

using the plugin as instructed by the docs does not initiate a prompt after x number of uses when x>0.

**Expected behavior:**
the prompt to rate the app will launch successfully after 3 uses or launches.

**Steps to reproduce:**

**Related code:**

```
I inserted the following code into my app.component.ts:
import { AppRate } from '@ionic-native/app-rate';

constructor(public apprate:AppRate){

platform.ready().then(() => {
this.apprate.preferences= {
        storeAppURL: {
          ios: '849930087',
          android: 'market://details?id=com.ionic.viewapp'
        },
        usesUntilPrompt: 3,
        customLocale: {
          title: "Rate Passion Project",
          message: "We value your feedback! Please take a moment to tell us how we're doing",
          cancelButtonLabel: 'No Thanks',
          rateButtonLabel: 'Rate it!',
          laterButtonLabel: 'Ask Later'
        }

  }
      this.apprate.promptForRating(false);
});
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v7.8.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 4.6.1 

```

**Comment by AmitMY** [comment]
Thanks for opening an issue.
You will get better help by moving this issue to https://github.com/ionic-team/ionic-native, as this repo handles the ionic core, and that one handles the cordova plugins

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-native#1849
