### ISSUE TITLE
Reorder handles disappear if I change reoder state quickly 3 times.

### ISSUE THREAD

**Issue by samastur** [ionic-team/ionic#12487]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Our app has a toggle button in header that switches reorder input of the list in content window. Pressing this button 3x switches reordering first on, then off and finally on again.

If you do this sequence quickly slowly, then everything works fine. However if you execute it quickly enough, then reorder handles don't appear after 3 press.

Using dev tools we can observe that third switch changes toggle state correctly.

We can see this behaviour on both Android and iOS.

**Expected behavior:**
Reordering handles should always appear when reorder attribute is true.

**Steps to reproduce:**
See above.

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.1.2 ios 4.3.1
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v6.10.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.1 Build version 8E1000a
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    npm        : 5.3.0
```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Would you mind sharing a code sample that we could use to reproduce this issue? Thanks!

**Comment by samastur** [comment]
Sorry for taking so long (vacation+cold). Here it is: https://github.com/samastur/ionic-sort-bug

If you press Edit button 3 times at right speed (approx. within second), you can/will end up with state where button will say Done (so should be in sort order state), but handles will be missing.

Might take a few tries to find the right tempo to experience this bug.
