### ISSUE TITLE
Feature request: Autocomplete component

### ISSUE THREAD

**Issue by MatanYed** [ionic-team/ionic#12489]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**
http://www.material-ui.com/#/components/auto-complete

**Related code:**
https://github.com/kadoshms/ionic2-autocomplete

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#281
