### ISSUE TITLE
Issue MOCA SDK cordova plugin 

### ISSUE THREAD

**Issue by nibaldoperot** [ionic-team/ionic#12486]
**MOCA SDK plugin issue** 
I am trying to implement MOCA SDK plugin on my Ionic 2 project but I'm having issues when calling the plugin from app.component.ts, I started as documentation directions says adding the plugin using the following command: 
```
cordova plugin add https://github.com/mocaplatform/moca-phonegap-sdk.git#:/MOCASDK --nofetch
```
After that when trying to use it on app.component.ts using the following code:

```
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { HomePage } from '../pages/home/home';

declare let MOCA: any;


@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage:any = HomePage;

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      statusBar.styleDefault();
      splashScreen.hide();
    });

  }
    showMOCA(){
      console.log(MOCA)
    }
}
```

Can anyone help me please ?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
