### ISSUE TITLE
URL's look terrible after 3.5.0

### ISSUE THREAD

**Issue by Rhonun** [ionic-team/ionic#12488]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The urls are very ugly right now and my product people are freaking out. Is there a way to turn of n root navigation or get the urls to look like they used to?

E.g.

Before:
myapp.com/login -> myapp.com/welcome -> myapp.com/content/article/new

Now:
myapp.com/nav/n4/login -> myapp.com/nav/n4/welcome -> myapp.com/nav/n4/content/article/new

It looks terrible now. Is there a way to make it look like it did before?

**Expected behavior:**
Urls don't have the /nav/n4 in them and look like normal urls

**Comment by AmitMY** [comment]
It is fixed in 3.6.0 releasing today probably.
You can use the nightly version for now.
See: https://github.com/ionic-team/ionic/issues/12346

**Comment by Rhonun** [comment]
@AmitMY thanks. We can close this one then :D

**Comment by Sneko** [comment]
@Rhonun @AmitMY 

Hi, I'm on the 3.6.0 version and nothing has disappeared. Did you do something special?

Thanks

**Comment by AmitMY** [comment]
@Sneko Negative. I think this stays if you have nested navigations, but if you only have 1 it is fine.
If you are on 3.6.0 and the current behavior bothers you, please create a new issue, with reproduction, and note this issue so it won't be closed as a duplicate.

**Comment by Sneko** [comment]
@AmitMY 

It was failing with ionic-angular 3.5.3 but updating it a bit make it work !

`$ npm install ionic-angular@3.5.3-201707251952 --save --save-exact`

Thanks to your answer on #12346

**Comment by AmitMY** [comment]
Glad to help.
You really should use 3.6.0, not that nightly.. if there are issues with 3.6.0, please create a new issue. (For me it works perfectly)

You shouldn’t use a nightly because it is less tested, and just an intermediary version.
