### ISSUE TITLE
Can’t read ionic build in iOS app from document folder 

### ISSUE THREAD

**Issue by Sudalaiyandi** [ionic-team/ionic#12482]
Hi All,
I read ionic build file from document folder which is in iOS app.First time it’s work correctly.Then i updated build file in document folder but updated changes not reflected in UI.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
