### ISSUE TITLE
Default history not being used when translating URL to pages

### ISSUE THREAD

**Issue by soumak77** [ionic-team/ionic#12481]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x** (nightly)

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a set of pages designed to fit a specific hierarchy.  For instance I have the following root pages:
- applicant
```
@IonicPage({
  name: 'applicant.root',
  segment: 'applicant'
})
```
- business
```
@IonicPage({
  name: 'business.root',
  segment: 'business'
})
```

Each of those pages has a tabs component with a `profile` and `settings` tab.  The page for each of those tabs is shown below along with the URL that should load that page.
- applicant/profile
```
@IonicPage({
  name: 'applicant.profile',
  segment: 'profile',
  defaultHistory: ['applicant.root']
})
```
- applicant/settings
```
@IonicPage({
  name: 'applicant.settings',
  segment: 'settings',
  defaultHistory: ['applicant.root']
})
```
- business/profile
```
@IonicPage({
  name: 'business.profile',
  segment: 'profile',
  defaultHistory: ['business.root']
})
```
- business/settings
```
@IonicPage({
  name: 'business.settings',
  segment: 'settings',
  defaultHistory: ['business.root']
})
```

When the browser is at `applicant/profile` and the page is reloaded, ionic is detecting the current pages to be `applicant.root` and `business.profile`.

**Expected behavior:**
I would expect the `defaultHistory` for each page to be taken into account when parsing the url.  This would ensure the parsed url of `applicant/profile` to result in the pages `applicant.root` and `applicant.profile`.

**Other information:**

In the example provided, I also have a menu in each root page which can navigate to the other pages.  For instance I should be able to navigate from `applicant.profile` to `business.profile`.  In order to do this I am calling `nav.setRoot('business.root')`, which should then default to selecting `business.profile` since it is the first tab.

The problem is that the code reads the browser URL to determine which tabs to load.  This is being done before ionic updates the URL with the new root page.  Therefore it is causing the navigation from `applicant.profile` to `business.profile` to fail.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.1.0
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.6.0

System:

    Node       : v6.9.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 5.3.0 
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by mdo7s** [comment]
I have a similar issue after upgrading to 3.6 whenever I reload the first tab is always selected.
