### ISSUE TITLE
Allow scrolling in ion-datetime for browser

### ISSUE THREAD

**Issue by soumak77** [ionic-team/ionic#12495]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The `ion-datetime` component is difficult to use when in the browser as it requires dragging the values to scroll through the list.

**Expected behavior:**
It would be better if you could also scroll through the values using a normal scroll event from the mouse wheel.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.1.0
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v6.9.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 5.3.0
```

**Comment by soumak77** [comment]
This is somewhat related to https://github.com/ionic-team/ionic/issues/12336, however, this request is much smaller in that no redesign is necessary.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#283

**Comment by amreladawy** [comment]
Hi,
What is the status of this feature?  I am using material design date picker, which is not doing will inside `ion-item`.
