### ISSUE TITLE
radio-group doesnt's show the checked radio after the radio list changed

### ISSUE THREAD

**Issue by lovanya** [ionic-team/ionic#12498]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

    radio-group doesnt's show the checked radio after the radio list changed
**Expected behavior:**

    show the checked radio after the radio list changed
**Steps to reproduce:**

    before refreshList run:
![default](https://user-images.githubusercontent.com/16385444/28715351-07e4fe66-73ca-11e7-9675-f612528e36b6.png)

    after refreshList run:
![default](https://user-images.githubusercontent.com/16385444/28715314-e01bfe0c-73c9-11e7-9dd1-a710c4d73b6c.png)
**Related code:**
```
_itemChecked = "3";
_list = [{id:"1"},{id:"2"},{id:"3"},{id:"5"},{id:"37"}]

  <ion-list  [(ngModel)]="_itemChecked" radio-group>
          <ion-item *ngFor="let item of _list">
              <ion-label>{{item.id}}</ion-label>
              <ion-radio [value]="item.id"></ion-radio>
          </ion-item>
   </ion-list>
   refreshList(){
        this._list = JSON.parse(JSON.stringify(this._list));
   }
```
**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
the ionic cli doesn't show any error!!!
```

**Comment by shtaif** [comment]
+1

**Comment by ionut-movila** [comment]
I can confirm this problem, still present in ionic-angular 3.6.0

**Comment by cherrypengpeng** [comment]
i got same problem.i solve it.when you refreshList   you should reset the _list

**Comment by cherrypengpeng** [comment]
set the _itemChecked=""

**Comment by brucesgit** [comment]
do like this can solve the problem:
```
refreshList(){
      let tmp = this._itemChecked;
      this._itemChecked = "" ;
      this._list = JSON.parse(JSON.stringify(this._list));
      let timer = setTimeout(()=>{ 
          this._itemChecked = tmp;
          clearTimeout(timer);
      },500)
 }  
```
but it's not a good solution， I want to know if it is a bug or my wrong using？

**Comment by Zwoch** [comment]
I have the same problem. I use 
`
"@angular/animations": "^6.0.3",
        "@angular/cdk": "^6.2.1",
        "@angular/common": "^6.0.3",
        "@angular/compiler": "^6.0.3",
        "@angular/core": "^6.0.3",
        "@angular/forms": "^6.0.3",
        "@angular/http": "^6.0.3",
        "@angular/material": "^6.2.1",
        "@angular/platform-browser": "^6.0.3",
        "@angular/platform-browser-dynamic": "^6.0.3",
        "@angular/router": "^6.0.3",
        "@ionic-native/core": "^4.7.0",
        "@ionic-native/network": "^4.7.0",
        "@ionic/angular": "^4.0.0-alpha.7",
        "@ionic/core": "^4.0.0-alpha.7",
        "@ionic/storage": "^2.1.3",
`

I had the following construct:

`
<ion-radio-group *ngIf="mitarbeiterListe$|async">
                            <ion-list *ngFor="let g of (mitarbeiterListe$|async)?.value?.results" class="scroll-content"
                                      no-margin>
                                <ion-list-header no-margin text-center #{{g.group}} id="{{g.group}}">
                                    <ion-label>{{g.group}}</ion-label>
                                </ion-list-header>
                                <ion-item class="ItemInList" button tappable detail (click)="mitarbeiterAnzeigen(p)"
                                          *ngFor="let p of g.results">
                                    <ion-label>{{p.vorname}} {{p.nachname}}</ion-label>
                                    <ion-radio slot="start"
                                               [value]="p.mitarbeiter_id"
                                               [checked]="((mitarbeiterListeSelected$| async) === p.mitarbeiter_id)"></ion-radio>
                                </ion-item>
                            </ion-list>
                        </ion-radio-group>
`
On select with the mouse, all is ok. But if the mitarbeiterListe$ changed and the list rerender, i had no selected item.
