### ISSUE TITLE
Version 3.2.0 installed in place of Latest (3.6.0)

### ISSUE THREAD

**Issue by mayurmarwa** [ionic-team/ionic#12491]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
npm install -g ionic@latest
should install 3.6.0 but it is installing 3.2.0.

**Expected behavior:**
install 3.6.0

**Steps to reproduce:**
run:
npm install -g ionic@latest

**Comment by janpio** [comment]
Please include your `ionic info` output so we actually know what is being installed.

**Comment by mayurmarwa** [comment]
before:
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.1.2
    Ionic Framework    : ionic-angular 3.2.0

System:

    Node       : v7.9.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.5.0`
 
after running npm install -g ionic@latest :

`global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.1.2
    Ionic Framework    : ionic-angular 3.2.0

System:

    Node       : v7.9.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed`

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Im not able to reproduce this on my machine. Also, i checked our npm tags and the `latest` tag is 3.6.0, as it should be. If you run `npm install ionic-angular@3.6.0 --save` that will get you the latest version. Thanks for using Ionic!
