### ISSUE TITLE
webpackJsonp is not defined

### ISSUE THREAD

**Issue by arapocket** [ionic-team/ionic#12492]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Since updating to 3.6 i'm getting "webpackJsonp is not defined" when I try to run my project.

**Comment by arapocket** [comment]
A fresh install of everything in a new directory fixed it ¯\_(ツ)_/¯

**Comment by jasonhoch23** [comment]
My experience on this issue was missing <script src="build/vendor.js"></script> inside index.html

**Comment by mayurmarwa** [comment]
As @jasonhoch23 stated, including the vendor.js file fixes this issue. It is to be included before main.js. https://github.com/ionic-team/ionic-app-scripts/releases/tag/v2.0.0

**Comment by cmartin81** [comment]
I have the same problem on devices running on android 4.4.4.
It works fine on newer models.

**Comment by ollyjohn** [comment]
We're getting this issue on older Android devices too ( pre 4.4.4 ) - is there a fix/workaround?

**Comment by ourarash** [comment]
I have the same problem only on Android 4.4. Did anyone come up with a solution?

**Comment by cmartin81** [comment]
It might be a cordova plugin which does not support android 4.4.4. Please remove one by one and try to emulate it on android 4.4.4. This is how I isolated the problem and managed to find a solution for it.

**Comment by atheerahassan** [comment]
still getting the same error with Android 5.0 and vendor.js is already in index.html :/
