### ISSUE TITLE
ionic cli  create icon and splash throw ERROE

### ISSUE THREAD

**Issue by 1483799920** [ionic-team/ionic#12494]
ionic-cli run 
> ionic cordova resources

throw ERROR

>✔ Collecting resource configuration and source images - done!
[WARN] Error occurred during command execution from a CLI plugin
       (@ionic/cli-plugin-cordova).
✖ Uploading source images to prepare for transformations - failed!
Error: read ETIMEDOUT

why is that?

>nodejs   v6.11.0
npm       v3.10.10
ionic-cli v3.6.0
cordova v7.0.1

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2583
