### ISSUE TITLE
Feature request: Multiple inputs in single line

### ISSUE THREAD

**Issue by MatanYed** [ionic-team/ionic#12490]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**
https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B5ZSepuCX1xOLTFIRURTTl9mQWc/single2.png

**Related code:**

**Comment by davec21** [comment]
Being able to do this in just a one ion-item thing would be awesome. You can however use `ion-row` with `ion-col` and wrapping the code in `ion-item` to get this effect.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#282
