### ISSUE TITLE
Multiple instances of old pages/components running in background

### ISSUE THREAD

**Issue by sujit77** [ionic-team/ionic#12496]
**Ionic version:**
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Multiple instances of old/previous pages/components running in background.
All [Ionic page events](http://ionicframework.com/docs/api/navigation/NavController/) are working correctly. 

**Expected behavior:**

There should be single instance of each page/component. 
#or
Instance of old/previous pages/components should be destroyed.

`this.navCtrl.setRoot(SomePage)` should clear constructor of this class after it loads the new page (in this case `SomePage`)

**Steps to reproduce:**
Sorry, I failed to create working example to point out the issue.

#### But its simple to produce - 

1. Create a sample `sidemenu` project using `ionic start SampleMenuProject sidemenu`.
2. Edit `list.ts` file present under `src` -> `pages` -> `list` folder.
3. Add following lines in `list.ts` file - 

   ```bash
   counter = 0;
   ngOnInit(){
       this.calledFunction();
   }
   
   calledFunction(){
       this.counter++;
       console.log('List page called ' + this.counter);
       setTimeout(()=>{
           this.calledFunction();
       }, 5000)
   }
   ```

#### Run the project (view in browser) and follow below steps (don't reload this browser's tab):

1. This project has 2 pages.
2. From `main menu`, select the `List` page.
3. In console, you should be seeing logs like `List page called <counter>`. It updates in 5 secs.
4. **Now select links from the list. (This creates new instances of List page, `and the issue too`)**
5. Also, keep noticing logs generated in console. (They continue even if you close recently pushed pages from stack)
6. **Now choose `Home` page (from menu). All previous counters still continues along with calling the `calledFunction()`.**
7. If you go back to `List` page again, you will generate new instance of ListPage constructor.

**Related code:**

I tried to tackle solution using 

```bash
// Present in app.components.ts
// Confirmed that `import { NgZone } from '@angular/core';` was added

openPage(page) {
  this.zone.run(() => {
    this.nav.setRoot(page.component);
  });
}
```

Tried Ionic page leave events too (Thinking stacked page behavior of Ionic).

```bash
ionViewDidLeave(){
    this.navCtrl.pop();
}
```

**Other information:**

Found similar issues here - 
1. https://github.com/ionic-team/ionic/issues/5960
2. https://github.com/ionic-team/ionic/issues/9401

I tried the solution mentioned in below link. Didn't worked in my case. - 
1. https://forum.ionicframework.com/t/after-setroot-tabspage-the-default-tab-page-appears-twice/71770/10

  ```bash
  openPage(page) {
    this.zone.run(() => {
      this.nav.setRoot(page.component);
    });
  }
  ```

**Ionic info:**

```
cli packages:

    @ionic/cli-plugin-ionic-angular : 1.4.0 (C:\Users\Sujit***\Project\node_modules\@ionic\cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (C:\Users\Sujit***\Project\node_modules\@ionic\cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (C:\Users\Sujit***\Project\node_modules\ionic)

local packages:

    @ionic/app-scripts : 2.0.2
    Ionic Framework    : ionic-angular 3.5.3

System:

    Node : v8.1.3
    OS   : Windows 10
    npm  : 5.0.3
```

![list page view](https://user-images.githubusercontent.com/26189654/28711659-fb8ab2ce-73a5-11e7-82fd-c598ba6344c7.png)

![home page view](https://user-images.githubusercontent.com/26189654/28711660-fb8dbb54-73a5-11e7-9b98-fba3c3b4c6b0.png)

**Comment by Iyashu5040** [comment]
`setTimeout` returns an integer with an ID for that timeout. You should save this ID in your page, something like this
`this.timeoutId = setTimeout(...)`
then on ionViewWillLeave call `clearTimeout(this.timeoutId)`
this will stop the timeout and prevent code from running when the page is gone.

Also, if you want to call a function repeatedly I'd recommend using `setInterval()`

**Comment by sujit77** [comment]
@Iyashu5040, your suggestion worked perfectly in this situation. 
Thank you.

Please help me understand this, [Ionic page events](http://ionicframework.com/docs/api/navigation/NavController/) are working perfectly. 
Which means Ionic must be removing old instances of unused components.
Then why the `setTimeout()` of old object remained executing?

There shouldn't be any necessity of clearing the timeout if its parent object have been destroyed.

**Comment by Iyashu5040** [comment]
@sujit77 `setTimeout()` and `setInterval()` are functions that exist on the `window` object, which is the parent of basically everything in javascript. So the functions aren't children of the controller, so destroying the controller won't remove them.

See https://www.w3schools.com/jsref/met_win_settimeout.asp, https://www.w3schools.com/jsref/met_win_setinterval.asp and https://www.w3schools.com/js/js_window.asp

**Comment by sujit77** [comment]
Thank you @Iyashu5040.
Thanks for mentioning above links.
