### ISSUE TITLE
ng-valid on required field - ion-item vs ion-input inconsistency

### ISSUE THREAD

**Issue by sirhaplo** [ionic-team/ionic#12503]
**Ionic version:**  (check one with "x")
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report

**Current behavior:**
A ion-input **required** with a valid value inside a ion-item is not highlighted correctly.
The ion-item has ng-invalid, while the inner ion-input has correctly a ng-valid.
So the field is not correctly highlighted

**Expected behavior:**
if the inner ion-input has ng-valid so should have the outer ion-item.
A valid input should have the green highlight

**Steps to reproduce:**

**Related code:**
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

export class Pdv {  
    insegna:String;    
}

@Component({
  selector: 'page-home',
  templateUrl: 'app/home.page.html'
})
export class HomePage {

  appName = 'Ionic App';
  
  pdv:Pdv = new Pdv();
  
  constructor(public navController: NavController) { }

  ionViewDidLoad(): void {

		this.pdv.insegna = 'Prova';

  }

  
}
```

```
<form (ngSubmit)="onSubmit(pdvForm)" #pdvForm="ngForm">
    <ion-list>
      <ion-item>
        <ion-label floating>Insegna</ion-label>
        <ion-input type="text" required [(ngModel)]="pdv.insegna" name="insegna" insegna="ngModel">
/ion-input>
      </ion-item>
    </ion-list>
  </form>
```

**Other information:**
in v3 does not works.
v3 Plunker : https://plnkr.co/edit/p7V3OjAanCXrUO0cAcDN?p=preview

In ionic v2 works.
v2 Plunker : https://plnkr.co/edit/ohzPVs1kQD98mGNdf0aT?p=preview

**Ionic info:** 

```
cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0 (c:\riquesto2.2\node_modules\@ionic\cli-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.4.0 (c:\riquesto2.2\node_modules\@ionic\cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (c:\riquesto2.2\node_modules\@ionic\cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (c:\riquesto2.2\node_modules\ionic)

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.2.0 windows 4.4.2
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.11.0
    OS   : Windows 10
    npm  : 3.10.10
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will look into this.

**Comment by Nehluxhes** [comment]
I have the same problem, I think it's related to https://github.com/angular/angular/issues/14189

For now since I am using reactive forms I use 
```
<ion-item [class.ng-invalid]="!group.get('name').valid">
      <ion-input type="text" formControlName="name"></ion-input>
    </ion-item>
```
as a workaround.

**Comment by kensodemann** [comment]
See #12753 for another good Plunkr sample source for this issue.

**Comment by montulli** [comment]
Does anyone have a workaround for this issue?   Very frustrating...

**Comment by nosTa1337** [comment]
Fix would be nice.

@montulli you can work with viewchild 
`@ViewChild('quantityUnitCode', { read: ElementRef }) quantityUnitCodeElementRef: any;
this.render.setElementClass(this.quantityUnitCodeElementRef.nativeElement.children[0], 'ng-invalid', false);
          this.render.setElementClass(this.quantityUnitCodeElementRef.nativeElement.children[0], 'ng-valid', true);
`

**Comment by obkdev** [comment]
Any update on this? I am using an angular 2 forms and this issue is a problem as the css does not reflect the form validation.  

I have a [http://plnkr.co/edit/yRafoAWv6MOk0TB1B0Qn?p=preview](Plunker) here.

**Comment by ZameelAmjed** [comment]
I am experiencing the same issue after running custom validation. Upon `Form.controls.input.updateValueAndValidity(); `  the input gets 'ng-valid' class but not the outer ion-item div. 
@Nehluxhes 's solution did not worked for me so i had following workaround

```HTML
<ion-item [ngClass]="{'inputvalid':(form.controls.input.valid)}">
 <ion-input type="text" formControlName="input"></ion-input>
</ion-item>
```

```scss
 .inputvalid{
  .item-inner{
     border-bottom-color: #32db64 !important;
     -webkit-box-shadow: inset 0 -1px 0 0 #32db64 !important;
      box-shadow: inset 0 -1px 0 0 #32db64 !important;
    }
 }
```

**Comment by nickwinger** [comment]
months have gone by and nothing happened ? Why are there even issues opened...
How do you style validation if this is not working...
ion-item sets wrong css classes....
the ion-input inside the ion-item is valid, but the parent ion-item is ng-invalid
(just because another ion-input (outside this ion-item) is invalid...

**Comment by DrMabuse23** [comment]
Hey i need this fix too :/ any news here , Form is at the moment still unusable for the endusers may label is red and my input is green ^^

**Comment by iget-master** [comment]
Same issue here, for some reason my fields almost never get error hightlighted.

**Comment by RoyeA** [comment]
Workaround ( for me ):
~~~~~~~~~~ HTML ~~~~~~~~~~~
<ion-item [class.myInvalid]="usernameCtrl.invalid" [class.myValid]="usernameCtrl.valid">
  <ion-input type="text" #usernameCtrl="ngModel" minlength="3" required'></ion-input>
</ion-item>
~~~~~~~~ CSS ~~~~~~~~~~~~
ion-item.myInvalid { border-left:5px solid red;}
ion-item.myValid   { border-left:5px solid green;}
~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by iget-master** [comment]
Serious that after 6 months this issue with a basic feature broken still open?! Do really make sense Ionic team think in a new version if the current version is broken?!

**Comment by pierresh** [comment]
It would be great to get a fix on this, that is something really important for end-users experience and the various work around mentioned in this discussion do not work with dynamic forms..
