### ISSUE TITLE
Feature Request: ionViewCanLeave - pass the ViewController instance for the page being navigated to

### ISSUE THREAD

**Issue by kelvindart** [ionic-team/ionic#12502]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am in two minds as to whether to raise this as a bug, or a feature request, but there is an argument to say `ionViewCanLeave` is currently operating as it should be (which it is).

As it stands, `ionViewCanLeave` is triggering for page X, whenever you are pushing another page onto the NavController within page X (or a modal), or when you are popping this page.

What would be handy is to control how `ionViewCanLeave` operates, depending on whether you are pushing or popping the nav stack. (see **Expected behavior** below).

**Expected behavior:**
There are instances where you want to control whether the `ionViewCanLeave` should always resolve to `true` when, for instance, pushing pages onto the stack, or to decide whether or not to resolve `ionViewCanLeave` if you are popping said page. 

E.g. say you have three pages:

1. Login Page
2. Profile Page
3. Settings Page

If you are logged in, on the Profile Page, you will want the user to access Settings Page without any confirmation, and to resolve `ionViewCanLeave` without any prompt.

If you navigate back, and `pop()` is called on the Profile Page, then you may want to confirm with the user whether they want to log out or not. An implementation in its simplest form would look like the following:

```
ionViewCanLeave(isPopped: boolean) {
  // user is not going back, resolve true
  if (!isPopped) {
    return true;
  }

  return new Promise((resolve, reject) => {
    let alert = this.alertCtrl.create({
      title: 'Logout',
      message: 'Do you want to log out?',
      buttons: [
        {
          text: 'Yes',
          handler: () => {
            alert.dismiss().then(() => resolve());

            return false;
          }
        },
        {
          text: 'No',
          role: 'cancel',
          handler: () => {
            reject();
          }
        }
      ]
    });

    alert.present();
  });
}
```

Thinking about the flexibility, I guess it would be better to return (if possible) the ViewController being navigated to, since it may not necessarily be a case of a simple push/pop navigation. Then the user can decide how to resolve the nav guard based on which page the user is attempting to go to. But that is thinking further down the line.

**Steps to reproduce:**
N/A

**Related code:**
N/A

**Other information:**
![Nav Guards](https://media.giphy.com/media/26n6yvWsoLIMhuBjO/giphy.gif)

**Ionic info:**

```
cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0 (/Users/kelvindart/src/NavGuards/node_modules/@ionic/cli-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.4.0 (/Users/kelvindart/src/NavGuards/node_modules/@ionic/cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (/Users/kelvindart/src/NavGuards/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (/Users/kelvindart/src/NavGuards/node_modules/ionic)

global packages:

    Cordova CLI : 6.5.0 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v8.2.1
    OS                : macOS Sierra
    Xcode             : Xcode 8.2.1 Build version 8C1002 
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.13 
    npm               : 5.3.0
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#284
