### ISSUE TITLE
item-reorder does not place item in correct order

### ISSUE THREAD

**Issue by lostdev** [ionic-team/ionic#12504]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using the itemReorder on list items, the order is not correctly maintained when dragging an item from it's original position, to a new position, and back to it's original position.

**Expected behavior:**
If I start dragging an item, move it, and then move it back to it's original position (because I changed my mind), I expect the item to stay exactly where I stopped reordering.

**Steps to reproduce:**
1. Visit https://ionicframework.com/docs/api/components/item/ItemReorder
2. Click Edit.
3. Move the "Everything Beta" option to the second item in the list (moving the Hello item to the top), WITHOUT releasing your mouse button.
4. Move "Everything Beta" back to the top item.
5. Let go of the item (expecting "Everything Beta" to stay at position 1)
6. Instead, the "Everything Beta" moves back to position 2.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0 (C:\git\mobile\node_modules\@ionic\c
li-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.4.0 (C:\git\mobile\node_modules\@ionic\c
li-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (C:\git\mobile\node_modules\@ionic\c
li-utils)
    ionic (Ionic CLI)               : 3.6.0 (C:\git\mobile\node_modules\ionic)

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3 ios 4.3.1
    Ionic Framework    : ionic-angular 3.5.3

System:

    Android SDK Tools : 25.2.5
    Node              : v6.10.3
    OS                : Windows 8.1
    npm               : 3.10.8
```

**Comment by AmitMY** [comment]
I am not sure what you are seeing. The "Hello" option is the second option, are you not seeing `Everything Beta`?

![image](https://user-images.githubusercontent.com/5757359/28736620-5da6452a-73f3-11e7-9781-4eeeae7d52dd.png)

**Comment by AmitMY** [comment]
Oh ok, so the important part is "WITHOUT releasing your mouse button."
@jgw96 This does not longer needs info, it is a reproducible bug.

**Comment by jasonvdzeeuw** [comment]
I think I've just created a duplicate, but as a request for feature: #12940 
I have the same issue 👍
