### ISSUE TITLE
bug in cordova build: view not refreshing after browser back

### ISSUE THREAD

**Issue by christophenne** [ionic-team/ionic#12512]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
An IonicPage A contains buttons, which - when clicked - update a property in the component. This property itself is used in an `*ngIf` in the template of the page. Long story short: Clicking a button should change something in the view. 
Bug: When the user navigates from this Page A to an IonicPage B via the navController push method, and then uses the **browser back button** to get back to Page A, the view is not updated properly anymore. The page looks like before, and you can click the buttons, and the properties will be set, but the view does not get rerendered (at least not until the window is resized). 
This only happens when I use the cordova browser build, it's fine with the ionic dev server.

**Expected behavior:**
Like described above, if I go back to Page A, it should have the same behaviour like on the first visit: When a property in the component is updated, and that property somehow affects something on the template via `*ngIf,`, the view should be rerendered immediately. 

**Steps to reproduce:**
I created a little example project based on the blank template, you can get it here: https://github.com/christophenne/ionic3-ngIf-problem .
To reproduce, run `npm install`, followed by `ionic cordova run browser`. As soon as you see the app in your browser window, click the select buttons a few times to verify that the view gets updated.
Then click the link to go to "page 2". And then use the browser back button, to get back to the home page. 
Clicking the buttons again, you should see that the view is not updated anymore.

Also have a look into the browser console when you try it. You will see, that the click Method gets called and the property in the component does get updated. It's only that the template is not updated after a new value is set. As soon as you resize the browser window, the view gets updated also.

**Related code:**

Please have a look at the example I created in https://github.com/christophenne/ionic3-ngIf-problem

**Other information:**
I already tried to get help in the ionic forum: https://forum.ionicframework.com/t/problem-with-ionic-cordova-browser-build-ngif-browser-back/100090 , but got no answer yet.
I also haven't found any related issues. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : browser 4.1.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node       : v6.11.0
    OS         : Linux 3.13
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10 
```

**Comment by christophenne** [comment]
Update: When I inject a `ChangeDetectorRef` and call `detectChanges()` manually inside the click method, view gets updated. 

Like this:

```
constructor(public navCtrl: NavController,
    private cdr : ChangeDetectorRef) {
}

click(val : number){
    console.log("click(" + val + ")");
    this.selected = val;
    console.log("this.selected = " + this.selected);
    this.cdr.detectChanges();   //this should not be necessary
}
```

Is there some other way to fix it ? 
I don't think it's a good solution to go through every single possible event in my whole application, and call `detectChanges` there - that's definetly something Angular/Ionic is here for.

I also tried to `detach` and `reattach` the `ChangeDetectorRef` when the component loads, but this doesn't change anything.

Also, there has got to be a reason why this strange behaviour exactly occurs when you come back to the page with the browser back button. It works fine in every other case.

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this.

**Comment by christophenne** [comment]
Thanks. Did you close this by accident ?

**Comment by christophenne** [comment]
Hello, could you please reopen this, so it has a chance to actually get looked into ? Thanks.

**Comment by kaiserdan** [comment]
Have the same problem. @jgw96 why did you close this issue, or is it resolved already?
