### ISSUE TITLE
npm WARN @angular/animations@4.3.2 requires a peer of @angular/core@4.3.2 but none was installed.

### ISSUE THREAD

**Issue by mokupindia** [ionic-team/ionic#12514]
**Ionic version:**  
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
Creating a new blank Ionic 3.x app and adding Angular Material latest NPM packages with below command:
`npm install --save @angular/material @angular/animations @angular/cdk`

throws exception in CLI as below:
`npm WARN @angular/animations@4.3.2 requires a peer of @angular/core@4.3.2 but none was installed.`

**Steps to reproduce:**
Same as above

**Ionic info:**:

```
global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v6.11.1
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy        : 1.8.6 
    ios-sim           : 5.0.8 
    npm               : 3.10.10 
```

**Comment by Sampath-Lokuge** [comment]
Because `Ionic` still uses lower version of angular ` "@angular/core": "4.1.3",`.

**Comment by jgw96** [comment]
Hello, all! @Sampath-Lokuge is correct. Currently, we are running on an older version of Angular than angular material is. We are planning on updating to the latest angular in the next release. Thanks!
