### ISSUE TITLE
cordova android livereload on localhost

### ISSUE THREAD

**Issue by condorman** [ionic-team/ionic#12517]
Hi, 
Usualy work on trip or in companies where it is not possible to use wifi routers, in the ionic version 1 and 2 I resolved with command "Ionic cordova run android -l --address localhost" after set 

- adb reverse tcp: 53703 tcp: 53703
- Adb reverse tcp: 35729 tcp: 35729
- Adb reverse tcp: 8100 tcp: 8100

But from v3 it is no longer possible to indicate the address "localhost" it's possible to implement this function? Do you have others suggest to give me to develop in livereload on physical device only via usb cable?

thank you!!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2585
