### ISSUE TITLE
Cannot read property 'match' of undefined TypeError

### ISSUE THREAD

**Issue by webkader** [ionic-team/ionic#12516]
Ionic version: 3.6.0

Typescript:
```typescript
@Component({
    templateUrl: 'tabs-page.html'
})
export class TabsPage {
    public tabCourse: any = CoursePage;
    public tabNews: any = NewsPage;
    public selectedTabMain: number;

    constructor(private navParams: NavParams) {
        if(this.navParams.data.tabIndex > 0) {
            this.selectedTabMain = this.navParams.data.tabIndex;
        } else {
            this.selectedTabMain = 0;
        }
    }
}
```

Html:
```html
<ion-tabs [selectedIndex]="selectedTabMain" tabsPlacement="bottom" name="maintab">
    <ion-tab [root]="tabCourse" tabTitle="Course" tabIcon="calendar"></ion-tab>
    <ion-tab [root]="tabNews" tabTitle="News" tabIcon="contacts"></ion-tab>
</ion-tabs>
```

How to fix this error that says Cannot read property match. 

![ion_error](https://user-images.githubusercontent.com/11710306/28755732-bf7fcee6-7561-11e7-9a87-35c7126f7e25.jpg)
![ion_ang](https://user-images.githubusercontent.com/11710306/28756680-6227f1b2-7573-11e7-983d-7568e2546ee8.jpg)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by lostdev** [comment]
This started happening to me too starting with my last update to 3.7.0. Used to work fine.

Happens when you load a deep link directly on a tab page.

**Comment by richardgong1987** [comment]
+1

**Comment by tiamat52** [comment]
Hello,
Same problem here...
Has someone found a solution?

**Comment by tallsam** [comment]
+1

**Comment by tiamat52** [comment]
It was perfectly working in the previous version of Ionic and now it doesn't work anymore...

**Comment by kensodemann** [comment]
Hello! Would you be able to provide a sample application via GitHub that demonstrates this issue? 

Thanks for using Ionic!

**Comment by cnsimbe** [comment]
Hi guys,
I had a similar painful experience with this bug.
Upgrade to ionic angular 3.6.1
https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md

I think it is a problem with the secondary identifier of tabs being null. That with as fixed in the latest official ionic angular release

**Comment by tiamat52** [comment]
Hi cnsimbe, it solved the problem!
Thanks for your feeback!
