### ISSUE TITLE
DateTime [displayFormat] input Properties hasChange But the  DateTime text Didn't update.

### ISSUE THREAD

**Issue by fssgh** [ionic-team/ionic#12523]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
DateTime [displayFormat] input Properties hasChange But the DateTime text Didn't update.
I using NgZone run the code  DateTime View Didn't update too.

**Expected behavior:**
when [displayFormat] input Properties hasChange the TextShould be update.

**Steps to reproduce:**

**Related code:**
```
temple:
<ion-datetime [displayFormat]="YMDFormat" [(ngModel)]="myDate" cancelText="取消" doneText="确定"></ion-datetime>
 <ion-segment [(ngModel)]="YMDSwitch" mode="ios" color="secondary">
            <ion-segment-button value="Y" (ionSelect)="YMDChange()">
              年
            </ion-segment-button>
            <ion-segment-button value="M" (ionSelect)="YMDChange()">
              月
            </ion-segment-button>
            <ion-segment-button value="D" (ionSelect)="YMDChange()">
              日
            </ion-segment-button>
          </ion-segment>
script:
 YMDChange() {
    setTimeout(() => {
      this._ngZone.run(() => {
        switch (this.YMDSwitch) {
          case 'D':
            this.YMDFormat = 'YYYY-MM-DD';
            break;
          case 'M':
            this.YMDFormat = 'YYYY-MM';
            break;
          case 'Y':
            this.YMDFormat = 'YYYY';
            break;
        }
      });
    }, 100);
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Framework: ^3.6.0
Ionic App Scripts: 2.1.3
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 8.1.3
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by fssgh** [comment]
@kensodemann  [the bug sample ](https://github.com/fssgh/ion-datetimeTest.git)

**Comment by kensodemann** [comment]
Thank you for the sample application. I have duplicated the issue.
