### ISSUE TITLE
Default App Name is always MyApp

### ISSUE THREAD

**Issue by nelsonkd** [ionic-team/ionic#12522]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When creating a new app using ionic start the app name <name></name> is always MyApp <name>MyApp</name>. 

**Expected behavior:**
This should be the name of that app that you specify in the ionic start command. ionic start kensApp blank
\**Steps to reproduce:**
ionic start kensApp blank
edit kensApp/config.xml
see that the name is MyApp

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
I can reproduce with ionic 3.3, 3.5, and 3.6

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2586
