### ISSUE TITLE
Adding scrollTo function to <ion-scroll>

### ISSUE THREAD

**Issue by kemalcany** [ionic-team/ionic#12525]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x** (latest)

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
<ion-scroll> component doesn't have scroll (ScrollView) property that would allow developers to programmatically control the scroll functions, for example the scroll position. <ion-content> have that function. (scrollTo method)

**Expected behavior:**
Scroll has a wider use than content, since there could be components on the screen that needs scrolling without the the rest of content properties and functions. Having scrollTo method is therefore useful to also have in ion-scroll (IMO)

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#286
