### ISSUE TITLE
3.6.0 issue with location.hash changes

### ISSUE THREAD

**Issue by mzealey** [ionic-team/ionic#12526]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

https://github.com/ionic-team/ionic/commit/a8ceee467b1d83a74d875e2162732c31d72c566e#diff-f2dfcd10c23466548c0e3079049da688L418

introduces a typo as the definition of https://github.com/ionic-team/ionic/blob/master/src/navigation/nav-controller-base.ts#L141 only has 3 parameters defined but you are passing 4. I'm not sure how the typescript compiler missed this. But the `{}` is now passed as the `done` function which causes navigation to blow up further down the line. This seems to be triggered sometimes when changing page using `window.location.hash`. Simply removing the `{}` fixes the bug but perhaps the `{}` was intended to replace the existing 2nd option's arguments.

**Comment by jgw96** [comment]
Ahh good find. We will fix this.

**Comment by kensodemann** [comment]
I believe @danbucholtz fixed this issue with this commit: https://github.com/ionic-team/ionic/commit/318737535f95810f5a7c5296cd7fe68a1899c580, which is part of the `ionic-angular 3.6.1` release.

If that is not the case, please let me know and I will reopen this issue.
