### ISSUE TITLE
ionSwipe event not being called when ion-item-options has content

### ISSUE THREAD

**Issue by SPhrenic** [ionic-team/ionic#12528]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Tested in 3.6 with below code

With below code ionSwipe event is not being triggered

```
	<ion-list>
	  <ion-item-sliding>
	    <button ion-item>text</button>
	    <ion-item-options (ionSwipe)="sayLogged()">
	      content
	    </ion-item-options>
	  </ion-item-sliding>
	</ion-list>

```
while without content, ionSwipe does trigger
```
	<ion-list>
	  <ion-item-sliding>
	    <button ion-item>text</button>
	    <ion-item-options (ionSwipe)="sayLogged()">
	      
	    </ion-item-options>
	  </ion-item-sliding>
	</ion-list>

```
**Expected behavior:**
ionSwipe event should be fired with or without content inside ion-item-options

**Steps to reproduce:**
see above code

**Ionic info:**
```
cli packages:

    @ionic/cli-plugin-ionic-angular : 1.4.0 (D:\Projects\ionic2\EQ\node_modules\@ionic\cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (D:\Projects\ionic2\EQ\node_modules\@ionic\cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (D:\Projects\ionic2\EQ\node_modules\ionic)

local packages:
    @ionic/app-scripts : 2.0.0
    Ionic Framework    : ionic-angular 3.5.0

System:
    Android SDK Tools : 25.2.5
    Node              : v6.9.4
    OS                : Windows 10
    npm               : 3.10.10

```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. If you use this markup from our docs ``` <ion-list>
  <ion-item-sliding #item>
    <ion-item>
      Item
    </ion-item>
    <ion-item-options side="left">
      <button ion-button (click)="favorite(item)">Favorite</button>
      <button ion-button color="danger" (click)="share(item)">Share</button>
    </ion-item-options>

    <ion-item-options side="right">
      <button ion-button (click)="unread(item)">Unread</button>
    </ion-item-options>
  </ion-item-sliding>
</ion-list>``` does everything work as expected?

**Comment by SPhrenic** [comment]
It seems you have removed the ionSwipe. (click) functionality works as expected. So by using your code, everything does indeed work as expected.

The code below is the exact code I'm using
``` 
	<ion-list>
	  <ion-item-sliding #item>
	    <button ion-item>
	      <h2>text</h2>
	    </button>
	    <ion-item-options side="right" (ionSwipe)="onRemoveClick(item)">
	    <button ion-button (click)="sayLogged()">text</button>
	    </ion-item-options>
	  </ion-item-sliding>
	</ion-list>
``` 

onRemoveClick(item) is not triggered when swiped
sayLogged() is triggered when pressed
