### ISSUE TITLE
Modal's do not close when you pass the view controller,

### ISSUE THREAD

**Issue by granthoff1107** [ionic-team/ionic#12521]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

I just went through an issue where my modals did not close, because I was passing the view controller to them, Why is this happening? This is the contents of the original stack question

I'm trying to dismiss my modal in ionic 2.

I have component which looks like this:

    export class DynamicModalComponent<T extends IHasId> {

        modalOptions: DynamicModalOptions<T>
    
        constructor(public navCtrl: NavController, public navParams: NavParams) {
            this.modalOptions = navParams.get('modalOptions');
        }

        close() {
            this.modalOptions.viewCtrl.dismiss();
        }
    }

and my html looks like this:

    <ion-header>
      <ion-navbar align-title="center">
        <ion-title> Dynamic Modal Header </ion-title>
        <ion-buttons end>
          <button (click)="close()" ion-button>
            <ion-icon name="save"></ion-icon>
            &nbsp;Cancel
          </button>
        </ion-buttons>
      </ion-navbar>
    </ion-header>

When I click the cancel button, my function gets triggered but nothing dismisses.   I don't think the issue would be in the calling class but just incase ill post the relevant pieces:

    constructor(public navCtrl: NavController, public viewCtrl: ViewController, public navParams: NavParams, public baseProvider: UserSkills,
        public enumProvider: Enums, public modalCtrl: ModalController, routes: Routes) {
    }

    showModal(modalOptions: DynamicModalOptions<UserSkill>) {
        let modal = this.modalCtrl.create(DynamicModalComponent, { modalOptions });
        modal.present();
        return modal;
    }

    onItemClick(entity) {
        var modalOptions = this.getDynamicModalOptions(entity);
        this.showModal(modalOptions);
    }

    getDynamicModalOptions(entity: UserSkill): DynamicModalOptions<UserSkill> {
        var modalOptions = new DynamicModalOptions<UserSkill>();

        modalOptions.entity = entity;
        modalOptions.editOptions = this.editOptions;
        modalOptions.inputMetadata = this.getInputMetadata(); 
        modalOptions.viewCtrl = this.viewCtrl;

        return modalOptions;
    }

This was my old code

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind sharing a repo we could use to reproduce this issue?

**Comment by kensodemann** [comment]
I am going to close this as it has been quite a while without a response.

If you can provide a sample application via GitHub or https://stackblitz.com that duplicates this issue I will be happy to reopen the issue and have a look.
