### ISSUE TITLE
Ionic 2 rest call can not catch http code 401 on ios

### ISSUE THREAD

**Issue by ajaysaini95700** [ionic-team/ionic#12531]
If the user credentials are incorrect the server returns 401, IOS did not return http code 401, but it did work on Android. how to handle this

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
