### ISSUE TITLE
<ion-datetime> allows non existing dates to select

### ISSUE THREAD

**Issue by Michazzz** [ionic-team/ionic#12533]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
User is able to select non existing date for example 06/31/2017 or 02/29/2017

**Expected behavior:**
User should not be able to select non existing dates. 

**Steps to reproduce:**
Add to you template ion-datetime 
```
    <ion-datetime pickerFormat="YYYY-MM-DD" displayFormat="YYYY-MM-DD"  max="{{maxDate}}" min="{{minDate}}"
                      [(ngModel)]="temDate" (ionChange)="moveForward()" placeholder="{{selectedDate}}"></ion-datetime>
```
1. Select date for example 07/31/2017, click 'Done' button. Correct date should be printed on <ion-datetime>. 

2. Click on <ion-datetime> to change date. 

3. Very carefully change month to June. The day should be still 31st. 

4. Click done button. The date should be printed on <ion-datetime>. 

**Other information:**
I have some screenshot with this bug. 

**Ionic info:** :

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10
```

**Comment by Michazzz** [comment]
![1](https://user-images.githubusercontent.com/1652051/28819487-b3580162-76ae-11e7-986b-2402c5144c30.png)
![2](https://user-images.githubusercontent.com/1652051/28819488-b3645502-76ae-11e7-8537-e563eb639077.png)
![3](https://user-images.githubusercontent.com/1652051/28819489-b3689e32-76ae-11e7-8e36-77c236eeb6e5.png)
![4](https://user-images.githubusercontent.com/1652051/28819490-b36902c8-76ae-11e7-992b-932b6c7d1508.png)

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by brassier** [comment]
Just saw this.  Here's a quick plunker demonstrating the issue.  From the given datetime, just change the month to June.  Notice it allows June 31.

http://plnkr.co/ISksKiSCNjRdVW6jZxt3?p=preview

**Comment by kensodemann** [comment]
Issue #13287 also has some good sample code demonstrating this issue.

**Comment by devnetics** [comment]
Useful Gif further demonstrating the issues:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/6577282/32191439-7f4ec9c6-bd87-11e7-9332-f00a3a43ed0e.gif)

**Comment by anooprehman** [comment]
Saw a similar issue in #12319 which has a  [Fix commit](https://github.com/eisene/ionic/commit/4aa494da1b3b082646c0a98ec1f69c823c126eb5).
