### ISSUE TITLE
Pin ionic-cli on the ionic-team orgnization profile page

### ISSUE THREAD

**Issue by Emeryao** [ionic-team/ionic#12532]
Hi team,
Can we pin the [`ionic-cli`](https://github.com/ionic-team/ionic-cli) repo on the [orgnization profile page](https://github.com/ionic-team) just like [`ionic`](https://github.com/ionic-team/ionic) repo did?
Since the `ionic-cli` repo is another *most visited* one like `ionic`

![image](https://user-images.githubusercontent.com/3591899/28818963-4011c77a-76df-11e7-943f-b48609dd5778.png)

**Comment by adamdbradley** [comment]
Good idea, done and done, thanks
