### ISSUE TITLE
Unable to set attribute: autocapitalize on a searchbar

### ISSUE THREAD

**Issue by kelvindart** [ionic-team/ionic#12535]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently, setting `autocapitalize` has no effect on controlling how input is typed into a searchbar and is effectively ignored.

```
<ion-searchbar autocapitalize="none"></ion-searchbar>
```

This has no effect.

**Expected behavior:**
When setting the `autocapitalize` feature, for it to be set on the native input.

See documentation:

**MDN:** 
https://developer.mozilla.org/en/docs/Web/HTML/Element/input#attr-autocapitalize

**Apple:**
https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html#//apple_ref/doc/uid/TP40008058-autocapitalize

**Steps to reproduce:**
N/A

**Related code:**

```
<ion-searchbar autocapitalize="none"></ion-searchbar>
```

**Other information:**
I am opening this issue as part of a pull request I have made to implement said behaviour.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-ionic-angular : 1.4.0 (/Users/kelvindart/src/searchbar/node_modules/@ionic/cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (/Users/kelvindart/src/searchbar/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (/Users/kelvindart/src/searchbar/node_modules/ionic)

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v8.2.1
    OS                : macOS Sierra
    Xcode             : Xcode 8.2.1 Build version 8C1002 
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.13 
    npm               : 5.3.0
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us and thanks for the PR (: We will take a look into this.
