### ISSUE TITLE
feat(ion-segment): add readonly property

### ISSUE THREAD

**Issue by bushybuffalo** [ionic-team/ionic#12530]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
There is no way to set readonly mode on an ion-segment, only disabled.

**Expected behavior:**
Make the  readonly property available on ion-segment. 
I'm using ion-segments as form inputs, as I find them quite a handy replacement for radio buttons in a horizontal layout. 
I managed to work around this issue by using a hidden input for retaining the info, but I'm really not fond of this kind of practice.

**Steps to reproduce:**
Not sure if this is relevant, there is simply no attribute available on the components.

**Related code:**

I'd like to be able to have the following code working:
```
<ion-segment [readonly]="condition" [(ngModel)]="myObject">
  <ion-segment-button [value]="1">foo</ion-segment-button>
  <ion-segment-button [value]="2">bar</ion-segment-button>
</ion-segment>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0 (D:\dev\workspace\keolis-guidebars-app-front\node_modules\@ionic\cli-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.4.0 (D:\dev\workspace\keolis-guidebars-app-front\node_modules\@ionic\cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (D:\dev\workspace\keolis-guidebars-app-front\node_modules\@ionic\cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (D:\dev\workspace\keolis-guidebars-app-front\node_modules\ionic)

global packages:

    Cordova CLI : 6.0.0

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v7.5.0
    OS                : Windows 10
    npm               : 5.3.0
    Cordova CLI : 6.0.0 
```

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#287
