### ISSUE TITLE
Toast component with duration doesn't dismiss if another toast is present.

### ISSUE THREAD

**Issue by SPhrenic** [ionic-team/ionic#12539]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If multiple Toasts are created on top of each other, only the lowest one wil dismiss. Others will stay.

**Expected behavior:**
Every individual toast will disappear when duration has ended

**Steps to reproduce:**
call the function showToast() multiple times before the duration of 2000 has ended (see related Code below)

**Related code:**

```
  showToast() {
    let toast = this.toastCtrl.create({
      message: ('deleted'),
      duration:2000
    });
    toast.onDidDismiss(() => {
    });
    toast.present();
  }
```

**Other information:**

**Ionic info:** 

```
cli packages:

    @ionic/cli-plugin-ionic-angular : 1.4.0 (D:\Projects\ionic2\EQ\node_modules\@ionic\cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (D:\Projects\ionic2\EQ\node_modules\@ionic\cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (D:\Projects\ionic2\EQ\node_modules\ionic)

local packages:
    @ionic/app-scripts : 2.0.0
    Ionic Framework    : ionic-angular 3.5.0

System:
    Android SDK Tools : 25.2.5
    Node              : v6.9.4
    OS                : Windows 10
    npm               : 3.10.10

```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this. A workaround in the meantime is to manually dismiss the toast using `toast.dismiss()` when you are showing two toasts at a time.

**Comment by SPhrenic** [comment]
Actually, I've tried to make a workaround but that doesn't seem to work

```
  private showToast(item) {
    let timer = setTimeout(() => { toast.dismiss(); }, 2000);
    let toast = this.toastCtrl.create({ message: ('Toast text') });

    toast.onDidDismiss(() => {
      clearTimeout(timer);
    });
    
    toast.present();
  }
```
so although this does show the toast, If I call this function showToast() multiple times, I get the same issue

**Comment by Remco75** [comment]
I narrowed this down to version 3.5.0. It works in 3.5.1
see this plunker
http://plnkr.co/edit/S4KNr7PCLlVzRFBWYc4r?p=preview
Here it does not works (it uses version 3.5.0)

If you change the version in systemjs.config.js on line 37 it starts to work

**Comment by SPhrenic** [comment]
Is there something I'd be able to do to update to 3.5.1? Somehow I'm unable to google information about it (Admitting I'm not a very experienced coder).

I'm taking the comment about changing the version in systemjs.config.js on line 37, was a refference to the plunker example, as I'm unable to find systemjs.config.js on my own desktop.

**Comment by Remco75** [comment]
just update the entry in your package.json  file in the root of your project and run npm install again.
If you update to 3.6, be a bit carefull, I had to fix some stuff after that.

**Comment by SPhrenic** [comment]
That worked! I've changed dependencies in my package.json to "ionic-angular": "3.5.1" instead of 3.5.0, and now it's working.

**Comment by jgw96** [comment]
Hello all! As it looks like this has already been fixed in `ionic-angular` I am going to close this issue for now. Thanks!
