### ISSUE TITLE
Iframe blocks input filling when scrolling in it

### ISSUE THREAD

**Issue by feoche** [ionic-team/ionic#12534]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[X] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When focusing an `<input>` field in an `<iframe>`, view is not scrolled to the focused `<input>`.
When scrolling in an embedded `<iframe>`, no character can be added inside the already focused `<input>` field, the only way to put extra characters is to blur the field and focus it again afterwards.

**Expected behavior:**
The focused `<input>` should be seen when typing in it, and should be accessible during actions on `<iframe>`.

**Steps to reproduce:**
- Put an `<iframe>` in a `<ion-content>` that contains a form page with `<input>`s
- Try to focus on a iPhone (iOS 8+)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
******************************************************

Your system information:

Cordova CLI:  7.0.1

Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.5
Xcode version: Not installed


******************************************************
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We currently do not recommend that you use iFrames and especially not on pages with inputs.
