### ISSUE TITLE
Feature request: textarea input support in AlertController

### ISSUE THREAD

**Issue by lostdev** [ionic-team/ionic#12537]
**Ionic version:**
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Feature**
It would be great to support a text-area as an input element in the alert controller. I would like to create a quick "contact" form with two textboxes, and one textarea but it's currently not possible, would be a time-saver to have this functionality built-in!

Thanks!

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#288

**Comment by dudanogueira** [comment]
@jgw96 link is to 404. Is this feature on the roadmap? Thanks!
