### ISSUE TITLE
html 5 validation

### ISSUE THREAD

**Issue by aggarwal59** [ionic-team/ionic#12548]
How to use html5 validation in ionic without using third party library
or 
override keyboard button with our app submit button

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
