### ISSUE TITLE
rtl slider not working ionic3

### ISSUE THREAD

**Issue by mohamedsharaf** [ionic-team/ionic#12549]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
rtl direction and slider error
cant slide as slide direction reverse 

**Expected behavior:**

normal slider

**Steps to reproduce:**

**Related code:**

```

            this.platform.setDir('rtl', true);
 <ion-slides >
                <ion-slide>
                    <h1>Slide 1</h1>
                    <img src="assets/img/1.png" class="slider-img">

                </ion-slide>
                <ion-slide>
                    <img src="assets/img/2.png" class="slider-img">
                </ion-slide>
                <ion-slide>
                    <img src="assets/img/3.png" class="slider-img">
                </ion-slide>
            </ion-slides>

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0 (Z:\conf\node_modules\@ionic\cli-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.4.0 (Z:\conf\node_modules\@ionic\cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (Z:\conf\node_modules\@ionic\cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (Z:\conf\node_modules\ionic)

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v8.1.2
    OS                : Windows 10
    npm               : 5.0.3
```

**Comment by AmitMY** [comment]
Currently, for slides, you have to explicitly write on the `ion-slides` `dir="rtl"`. See this fix, that is not merged yet: https://github.com/ionic-team/ionic/pull/12026

**Comment by mohamedsharaf** [comment]
thx @AmitMY it really fixed and i made the slider free mode so i can slide in both direction
