### ISSUE TITLE
Livereload halts geolocation

### ISSUE THREAD

**Issue by arapocket** [ionic-team/ionic#12542]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

- Position gets watched when i do a fresh run of the app using
`ionic cordova run ios --device -l -c`

- When I make changes to my code (in this case just saving) app rebuilds but device does not ask me to allow location tracking, thus breaking the geolocation.

**Other information:**

- Device only asks for allowing location when I restart my device
Edit: Restarting the device doesn't help either. Deleting the app and rebuilding it works.
Edit 2: Deleting the app doesn't even work now!!!
Edit 3: Ran the command again and it worked, but now watchposition is not working properly.
**When installing the app without livereload everything works fine.**

- nothing happening in the console to indicate an error

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2597
