### ISSUE TITLE
infinite-scroll not fired when scroll inertially to bottom in ios

### ISSUE THREAD

**Issue by elon-hu** [ionic-team/ionic#12544]
** environment:**  (check one with "x")
ionic:  **3.6.0**
angular:  **4.1.3**
phone:  **iphone 6plus 10.3.3**
cordova:  **7.0.1**
**Current behavior:**

android is ok.

but in ios,

when i slide up content at full tilt,

the list scroll inertially to bottom and the infinite-scroll not fired,

and it is fired untill slide up again.

by the way,the ion-content has bounce.

the bounce do it?

thanks a lot for you!

**Related code:**

```
<ion-content>
    <ion-refresher [pullMax]="200" (ionRefresh)="doRefresh($event)">
        <ion-refresher-content></ion-refresher-content>
    </ion-refresher>
    <ion-list>
        <button *ngFor="let x of dataList; let i = index;"  ion-item>
        </button>
    </ion-list>
    <ion-infinite-scroll (ionInfinite)="dropScrollLoad($event)">
       <ion-infinite-scroll-content></ion-infinite-scroll-content>
    </ion-infinite-scroll>
</ion-content>
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! So this only happens when scrolling very fast? Could you try installing [this plugin](https://github.com/ionic-team/cordova-plugin-wkwebview-engine) and testing this again? Thanks!

**Comment by elon-hu** [comment]
Thanks for reply,I have tried out  cordova-plugin-wkwebview-engine.but i face a new problem,the plug create a local serve "http://localhost:8080/", it made me ajax failure.do i have to use @ionic-native/http?

**Comment by jgw96** [comment]
No you dont. Do you have the latest version of the plugin installed? Also, are you making requests to a cors enabled server?

**Comment by jgw96** [comment]
Hello @elon-hu , with the latest versions of iOS and the new iOS webview (WKWebView) they have started to be more strict with http requests to servers. This includes wanting web servers to properly implement cors and use HTTPS. I would recommend setting up an [express server](https://expressjs.com/) to use as a proxy to set up cors and HTTPS correctly. Thanks for using Ionic!

**Comment by elon-hu** [comment]
@jgw96 i‘ve got it, thanks for your patient reply!

**Comment by jannikbeushausen** [comment]
@elon-hu I have exactly the same issue. How did you solved it?

**Comment by kulpreets** [comment]
@elon-hu I was able to solve this issue by installing the Ionic Webview plugin and following the steps at https://github.com/ionic-team/cordova-plugin-ionic-webview

**Comment by fwchen** [comment]
oh, I use ionic as web. any idea to resolve this?
