### ISSUE TITLE
White label branding support

### ISSUE THREAD

**Issue by irundaia** [ionic-team/ionic#12550]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

** Desired functionality
I'm currently working on an app that is going to be rebranded for a number of different client. Currently, what I have to do is: 
# replace the `config.xml` (with different app name/id)
# replace the spashscreen and icon resources
# replace the theme in the `src/theme` directory
# replace the fonts and images in `src/assets`

It would be great if this would be supported by the ionic cli.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2598
