### ISSUE TITLE
On scrolling popover it scrolls background list. IOS only

### ISSUE THREAD

**Issue by mobile-support93** [ionic-team/ionic#12553]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On scrolling popover it scrolls background list.

**Expected behavior:**
after opening popover it shoould not allow any action on background screen until closed

**Steps to reproduce:**
Should have scroll in popover and long list in background. Now scroll on popover it also scrolls background list. It happens only in IOS, working fine in android.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.0
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.1
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 browser 4.1.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.10.0
    OS         : Windows 8.1
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

```

**Comment by sufiiiyan** [comment]
Facing same issue

**Comment by jgw96** [comment]
Hello all! Could you try installing [our WKWebView plugin](https://github.com/ionic-team/cordova-plugin-wkwebview-engine) and seeing if you still run into this issue please? Thanks!

**Comment by sfaizanh** [comment]
Same issue with Modals, Try changing opacity of the modal page to `0.5` and adding `no-bounce` directive in `ion-content` then try to scroll, foreground page will scroll. (Tested on iOS)

```
Cordova CLI : 6.5.0 
WKWebView Plugin : 1.1.4-dev
@ionic/app-scripts : 2.1.3
@ionic/cli-plugin-cordova : 1.4.1
@ionic/cli-plugin-ionic-angular : 1.3.2
Cordova Platforms : ios 4.3.1
Ionic Framework : ionic-angular 3.6.0
```

**Comment by jgw96** [comment]
Hello all, have you been able to give the wkwebview plugin a try?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by chiragebiztrait4** [comment]
Hello @jgw96,

Yes there is still issue of overscroll in backdrop with actionsheet,loaders,popup. (IOS ONLY)

I am using cordova-ios@4.4, someone suggested to use WKWebView to solve this issue, but WKWebView plugin generates new issue of CORS in my app, so my app is stuck here.

Ionic info
`
 cli packages: 

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node  : v8.9.4
    npm   : 5.6.0 
    OS    : macOS Sierra
    Xcode : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
`

**Comment by ThonyBG** [comment]
Hi @jgw96 

Yes there is still issue. (IOS ONLY)

I can scroll through the backdrop.
If I touch the modal or the backdrop and in back I've an input or any form element, the touch close the modal and fire the focus for the input.

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : android 6.4.0 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 2.0.0 
    ios-sim           : 7.0.0 
    Node              : v10.8.0
    npm               : 2.15.12 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4.1 Build version 9F2000
