### ISSUE TITLE
--Prod flag no working 

### ISSUE THREAD

**Issue by Riderxyz** [ionic-team/ionic#12557]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Every time I try to run "ionic cordova buid IOS --release" i get the error that says that my component is duplicated when in fact it's not

**Expected behavior:**

--prod works without errors

**Steps to reproduce:**

pick an Ionic project
Be sure to be on an Mac 
run "ionic cordova build ios --prod"
Watch the error

**Related code:**

```
ionic cordova build IOS --prod
```

**Other information:**

Hello. I've been trying to build the production build for weeks, and i always get this error in particular. 
imageCropperComponent is a component crucial to my app. I've already check my code, built another app form 0 and the error still remains. The funny thing is that the --release flag works, without problems.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages:
   @ionic/cli-plugin-cordova       : 1.5.0 (/Users/imag/ondemand/skin/node_modules/@ionic/cli-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.4.0 (/Users/imag/ondemand/skin/node_modules/@ionic/cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (/Users/imag/ondemand/skin/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (/Users/imag/ondemand/skin/node_modules/ionic)

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : browser ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node       : v6.11.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    npm        : 3.10.10 

Error: Type ImageCropperComponent in /Users/imag/ondemand/skin/node_modules/ng2-img-cropper/src/imageCropperComponent.d.ts is part of the declarations of 2 modules: ImageCropperModule in /Users/imag/ondemand/skin/node_modules/ng2-img-cropper/src/imageCropperModule.d.ts and AppModule in /Users/imag/ondemand/skin/src/app/app.module.ts! Please consider moving ImageCropperComponent in /Users/imag/ondemand/skin/node_modules/ng2-img-cropper/src/imageCropperComponent.d.ts to a higher module that imports ImageCropperModule in /Users/imag/ondemand/skin/node_modules/ng2-img-cropper/src/imageCropperModule.d.ts and AppModule in /Users/imag/ondemand/skin/src/app/app.module.ts. You can also create a new NgModule that exports and includes ImageCropperComponent in /Users/imag/ondemand/skin/node_modules/ng2-img-cropper/src/imageCropperComponent.d.ts then import that NgModule in ImageCropperModule in /Users/imag/ondemand/skin/node_modules/ng2-img-cropper/src/imageCropperModule.d.ts and AppModule in /Users/imag/ondemand/skin/src/app/app.module.ts.

![captura de tela 2017-08-02 as 16 00 22](https://user-images.githubusercontent.com/29984665/28890066-50188146-779c-11e7-99ea-7ac8d37f64cd.png)

**Comment by jgw96** [comment]
Hello. This stackoverflow answer will help you with this issue https://stackoverflow.com/questions/43598311/component-is-part-of-the-declaration-of-2-modules. 
also, as this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
