### ISSUE TITLE
some mobile can't support "el.closet()"

### ISSUE THREAD

**Issue by Zettle** [ionic-team/ionic#12552]
Ionic version: (check one with "x")
[ ] 1.x (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[] 2.x
[X] 3.x

I'm submitting a ... (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

I use <ion-slide> and run in MeiZu， it report errors "undefined is not a function"

![image](https://user-images.githubusercontent.com/21301933/28874873-3949458e-77c6-11e7-9772-17f2f8f6a56b.png)

![image](https://user-images.githubusercontent.com/21301933/28874284-cdf69e00-77c3-11e7-9da9-be7357536aaa.png)

![image](https://user-images.githubusercontent.com/21301933/28874300-de55eef4-77c3-11e7-9d97-099c32fcbf65.png)

the browser's UA： **Mozilla/5.0 (Linux; Android 5.1; m3 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/40.0.2214.117 Mobile Safari/537.36**

and I find this problem is cause by "el = el.closest(selector);"

![image](https://user-images.githubusercontent.com/21301933/28874256-a43acb5e-77c3-11e7-9423-94f048bc6650.png)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! It looks like you are running on an old chrome webview. Most likely, Meizu is not using the modern chrome webview that comes with Android and is instead using their proprietary version of it that unfortunately, does not support modern web standards. To get around this and ensure your app is using a modern chrome webview I would recommend using [crosswalk](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview).
