### ISSUE TITLE
ion-label inside ion-item ion-range doesn't reflect disabled' styles

### ISSUE THREAD

**Issue by Luukschoen** [ionic-team/ionic#12551]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If we create an ion-item which contains an ion-label and ion-range with labels and we enable the disabled attribute on the ion-range, the first ion-label (the one outside the ion-range component) doesn't reflect the disabled styling. i.e. it still looks active. item-range-disabled does get set on the top ion-item though.

**Expected behavior:**

When I add the disabled attribute to an ion-item with an ion-label, I expect all ion-labels to grey out so that it's evidently disabled for the user. Not only the ones that are in the ion-range slider.

**Steps to reproduce:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0 (/Users/luukschoenmakers/Development/philips-voucherscan-app/node_modules/@ionic/cli-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.4.0 (/Users/luukschoenmakers/Development/philips-voucherscan-app/node_modules/@ionic/cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (/Users/luukschoenmakers/Development/philips-voucherscan-app/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (/Users/luukschoenmakers/Development/philips-voucherscan-app/node_modules/ionic)

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.3

System:

    Android SDK Tools : 25.2.5
    Node              : v7.7.2
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.2 Build version 8E2002 
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.11 
    npm               : 4.1.2 
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.
