### ISSUE TITLE
iOS date picker - not to spec

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#12564]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
This is the native & the ionic date pickers both shown:
![image](https://user-images.githubusercontent.com/5757359/28916694-c6a7fea4-784b-11e7-8fe3-b62f6375ffd8.png)

**Expected behavior:**
They should be in the same size

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (D:\xampp\htdocs\apps\locals-menu\node_modules)

    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.1.2
    OS   : Windows 10
    npm  : 5.3.0 

```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this. Out of curiosity is the taller one or the shorter one our datetime ?

**Comment by AmitMY** [comment]
Front is the native one, back is the ionic one.
