### ISSUE TITLE
How do I click the external web address and jump to the system browser? I'm going to jump in my App.

### ISSUE THREAD

**Issue by 12ThMicrowave** [ionic-team/ionic#12567]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**

How do I click the external web address and jump to the system browser? I'm going to jump in my App.
Where can I control the jump in the App?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
