### ISSUE TITLE
can't use [ngClass] in ion-option 

### ISSUE THREAD

**Issue by shivangcnc** [ionic-team/ionic#12562]
Hello
I am try to use class in ion-option but not working 
<ion-option *ngFor="let x of read_datas" [ngClass]="{'hide':read_data[x].new != true}" [value]="read_data[x].pray_id">{{read_data[x].title}}</ion-option>

<ion-option *ngFor="let x of read_datas" class="hide" [value]="read_data[x].pray_id">{{read_data[x].title}}</ion-option>

class attr not woking here at all

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by AndresOchoaS** [comment]
I have the same problem. Even if we put tags span, div or some other within ion-option to add the custom classes does not work.
