### ISSUE TITLE
Retrieve the active component of a tab

### ISSUE THREAD

**Issue by 5an1ty** [ionic-team/ionic#12568]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
There is no public way to retrieve the current active component instance on a tab.

**Expected behavior:**
I need to get the current active component per tab every time I click a tab in order to call a refresh data method.

**Steps to reproduce:**
Example (snippets):

```
this.activatedTabs = [];

<ion-tabs id="tabBar" preloadTabs="true" (ionChange)="tabPressed($event)">

  tabPressed(tab) {
    if (this.activatedTabs.find(tb => tb.index == tab.index)) {
      if (tab._views[tab._views.length -1].instance.refreshData) {
        tab._views[tab._views.length -1].instance.refreshData();
      }
    } else {
      this.activatedTabs.push(tab);
    }
  }
```

This works but is really hacky and I would prefer if there was another or at least a support way of retrieving the active component of tabs.

**Comment by Remco75** [comment]
I have the same requirements. When overriding the hardware backbutton on android I have to know wether we more than 1 pages in the active tab stack. I user the _views as well, but again, hacky and probably prone to change.

Is there a better way?

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#290
