### ISSUE TITLE
Deep linking syntax is confusing

### ISSUE THREAD

**Issue by raxim1** [ionic-team/ionic#12573]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Deep linking is using for view push a string, instead of the component.

**Expected behavior:**
I think that stuff should be more error prone, as it took me hours to realize, what i made wrong.

constructor(public nav: NavController)
...
this.nav.setRoot("IntroComponent") - this.nav.setRoot(IntroComponent)

The two syntaxes are totally confusing. I think there is an easy way to accept both, and figure out from the IonicPage annotation, how it should be handled.

As usual, angular sent me a totally nonsense error, so i had no idea, what was wrong, just when i checked a working example line by line. (after 1-2 hours i was not able to figure out, just suddenly i spotted)

I must say, it was a bunker.

**Comment by DavidStrausz** [comment]
There is actually a reason for that: When pushing a component-class itself on the nav-stack you have to import it which means there is a dependency and the component has to be in the same webpack bundle. On the other side if you the tell the nav-controller which page you want to push with just a string there is no need for an import statement and the component can be put into its own bundle which enables lazy loading.
