### ISSUE TITLE
[ERROR] Unable to find command: state restore

### ISSUE THREAD

**Issue by mluis** [ionic-team/ionic#12579]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
$ ionic state restore
[ERROR] Unable to find command: state restore
*snip*
$

**Expected behavior:**
$ ionic state restore
The most similar command is
    <command here>
$

**Steps to reproduce:**
$ ionic state restore

**Related code:**

**Other information:**
Not easy to find documentation.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
[ERROR] Error with www/lib/ionic/version.json file:
        FILE_NOT_FOUND

cli packages: (node_modules)

    @ionic/cli-plugin-cordova : 1.6.2
    @ionic/cli-plugin-gulp    : 1.1.1
    @ionic/cli-plugin-ionic1  : 2.1.1
    @ionic/cli-utils          : 1.7.0
    ionic (Ionic CLI)         : 3.7.0

global packages:

    Cordova CLI : 7.0.1 
    Gulp CLI    : CLI version 3.9.1 Local version 3.9.1

local packages:

    Cordova Platforms : ios 4.4.0
    Ionic Framework   : unknown

System:

    Node       : v6.9.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    npm        : 3.10.9 
```

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2611
