### ISSUE TITLE
Ionic 3.6 IonicPage and Deeplink loading the page 2 time

### ISSUE THREAD

**Issue by Lyuke13** [ionic-team/ionic#12575]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using the new deeplink and IonicPage decorator, when i reload a "page" it's loaded 2 time, first at 1-2 seconds after the browser has been refreshed, the 2nd time when the platform.ready finished.

This cause the page to return an error since my variable are not ready. While the page is loaded the first time by itself, the app.component.ts init function are still running, after platform.ready end, the page load a 2nd time. In local i still see the error, online the page is loaded fine but i can se the error on the console.

I know i can improve my code significally, but for now my main issue is that i can't init my user information, because the page load before platform ready, making every attempt on loading my user information and redirecting him to the right page useless...

**Expected behavior:**
I expect the page to reload after the platform.ready where i can place my init function so my varaible are ready to be used on the whole application.

**Steps to reproduce:**
The steps to test this are easy:
1- ionic start myNewProject tabs
2- Code IonicPage inside every page
3- Write console.log() with new Date before the platform.ready, inside the platform.ready and inside news.ts costructor
4- Serve ionic and look at the console when reloading the page, starting off two time the consol.loge inside news.ts constructor.

I have an online example too, but i've been doing heavy edit on the platform.ready and init function to see if i could fix the bug but they didn't work, here is even more visible that the console.log inside news.ts constructor start 2 time at different time.

I will link it here and edit it later time since this will be a private project for my gaming guild: https://dorf-5a4a6.firebaseapp.com

Login: prova@prova.it
Pass: provaprova

1- Login
2- Now that you are inside news page, look at the console and see that the "started..." consol.log run 1 time
3- Reload the page and see that "started..." run two time as stated before.

**Related code:**

**Other information:**
I think the main issue is that IonicPage and deeplink preload the page one time when you refresh or copy and paste the link and load it again after platform.ready.

I don't know if that how you wanted it to work, but i'm having an hard time to init my variable since i can't find the right point where to place my function. I could in every page constructor check if my var are initialzied, but that would be stupid since without IonicPage and deeplink my var are always initialized correctly.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-ionic-angular : 1.4.0
    @ionic/cli-utils                : 1.6.0
    ionic (Ionic CLI)               : 3.6.0

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.10.3
    OS   : Windows 10
    npm  : 3.10.10
```

**Comment by ChezRD** [comment]
Did you tried using function resolving to promise as nav guard in ionViewCanEnter?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! I am closing this issue due to this issue and issue #12684 being duplicates. I will make sure #12684 also references this issue. Please track that issue for further updates. Also please comment on that issue with any new information you may have to share.  Thank you for using Ionic
