### ISSUE TITLE
[textMask] being ignored, now showing up in any of the text fields after upgrade to CLI 3.7.0

### ISSUE THREAD

**Issue by raviada** [ionic-team/ionic#12578]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am using angulra2-text-mask, it was working until Ionic CLI 3.6.0 and I upgraded to 3.7.0 yesterday, I don't see masks in any of the input fields that are configured to use mask. We have a data collection intensive app and is impacting the usability significantly.

**Expected behavior:**
Phone number, date of birth, zip codes type of fields are setup to use ```[textMask]```, it was working great until yesterday.

**Related code:**

```
import { TextMaskModule } from 'angular2-text-mask';
....
this.phoneMask = ['(', /[1-9]/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/];  
....
<ion-input formControlName="mobile" type="tel" [(ngModel)]="data.mobile" [textMask]="{mask: phoneMask}"></ion-input>
```

**Other information:**
It seems to work fine when running the app in Ubuntu, but on on Mac. I tried it on two different macbooks.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/medlio/projects/ionic/medlioapp/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.0
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node       : v7.8.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    npm        : 5.3.0 

```

**Comment by fatalcaron** [comment]
If you have upgrade your package angular2-text-mask to 8.0.3, see this issue: https://github.com/text-mask/text-mask/pull/591

**Comment by jgw96** [comment]
Hello all! I am going to close this issue as this is not an ionic issue, but an issue with that package specifically. Thanks!
