### ISSUE TITLE
this.nav.setRoot('Page') == Cannot read property 'getActiveChildNavs' of undefined

### ISSUE THREAD

**Issue by Bubelbub** [ionic-team/ionic#12572]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[X] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I open a page which is not on my home page tab bar and then I get this error.

![2017-08-04 01_00_25](https://user-images.githubusercontent.com/319352/28947529-ace2c11a-78b0-11e7-8d10-7f2c2b6347e6.png)

**Expected behavior:**
I get no error.

**Steps to reproduce:**
Hard to explain.

Button: `(click)="openPage(page)"`
Function:

    openPage(component) {
        this.menu.close();
        this.nav.setRoot(component);
    }

**Ionic info:**:

```
cli packages: (C:\xampp\htdocs\node_modules)

    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v6.9.1
    OS                : Windows 10
    npm               : 5.3.0
```

**Comment by AmitMY** [comment]
Is there an active `ion-nav` components?

**Comment by Bubelbub** [comment]
Yes, @AmitMY, there is one.

    <ion-nav [root]="rootPage" main #content swipe-back-enabled="true"></ion-nav>

**Comment by Bubelbub** [comment]
It seems to be a problem of a used component:
https://github.com/zyra/ionic2-super-tabs/issues/117
https://github.com/zyra/ionic2-super-tabs/issues/135
https://forum.ionicframework.com/t/ionic-3-6-0-getactivechildnavs-of-undefined/100810

**Comment by albrecht-jun-zhang** [comment]
if you have `<super-tabs [selectedTabIndex]="selectedTabIndex"></super-tabs> `, in your typescript file, you have to initialize this selectedTabIndex to 0, otherwise you would get this error

**Comment by jasonz1987** [comment]
@albrecht-jun-zhang it does't work for me.
 
i get this error when i push back to a super tab page
