### ISSUE TITLE
Placing ion-buttons component in ion-navbar inside custom component breaks navbar button styles.

### ISSUE THREAD

**Issue by lpikora** [ionic-team/ionic#12570]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When you create custom component (or attribute directive - https://angular.io/guide/attribute-directives) eg. `navbar-buttons` with template:
```
      <button ion-button icon-only>
        <ion-icon name="contact"></ion-icon>
      </button>
```
and place it to `ion-buttons` inside `ion-navbar` of `ion-header` component: 
```
<ion-header>
  <ion-navbar>
    <ion-title>
    Title
    </ion-title>

    <ion-buttons navbar-buttons end>
    </ion-buttons>

  </ion-navbar>
</ion-header>
```

it breaks `<button ion-button>` styles.

**Expected behavior:**
It should display same as: 
```
<ion-header>
  <ion-navbar>
    <ion-title>
    Title
    </ion-title>

    <ion-buttons end>
       <button ion-button icon-only>
        <ion-icon name="contact"></ion-icon>
      </button> 
    </ion-buttons>

  </ion-navbar>
</ion-header>
```

**Steps to reproduce:**
described in Current behavior

**Related code:**

code in Current behavior

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0 (/home/lukas/Mapotic/mapotic_app/node_modules/@ionic/cli-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.4.0 (/home/lukas/Mapotic/mapotic_app/node_modules/@ionic/cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (/home/lukas/Mapotic/mapotic_app/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (/home/lukas/Mapotic/mapotic_app/node_modules/ionic)

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v8.2.1
    OS                : Linux 4.10
    npm               : 5.2.0
```

**Comment by AmitMY** [comment]
Can confirm. I write custom styles to fix this, would be nice if it was done inside ionic.

**Comment by AmitMY** [comment]
Duplicate of https://github.com/ionic-team/ionic/issues/10379
Although I like this issue more as it is in an up to date version

**Comment by yigitbacakoglu** [comment]
Still having this issue

**Comment by none100p** [comment]
same problem here with
cli packages: 

    @ionic/cli-plugin-proxy : 1.5.6
    @ionic/cli-utils        : 1.19.2
    ionic (Ionic CLI)       : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0 browser 5.0.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.11.5
    npm  : 3.10.10 
    OS   : Linux 4.4

**Comment by AmitMY** [comment]
@eduardoRoth v4 is in alpha.
 if the problem persists there, please note here and it should be addressed

**Comment by eduardoRoth** [comment]
@AmitMY, so there's nothing that we could do to fix this only wait for v4 to be released?

**Comment by AmitMY** [comment]
@eduardoRoth as far as I know, yes

**Comment by Amosss** [comment]
Just encountered the same problem. I understand that I should wait for the next version of ionic (when is it?), has anyone found a temp fix til then? Thanks

**Comment by ghenry22** [comment]
So the answer on 4 Aug 2017 was just hang out for V4.  Anyone with any kind of deadline or live application that needs to resolve this is pretty screwed.  There must be a way to resolve this so that the correct styles are applied.

**Comment by lpikora** [comment]
Rewriting whole app in React Native solved this issue for me (and many more issues). 
Closing this issue because Ionic V4 is here already and there will be no fix for V3 i think.

**Comment by ghenry22** [comment]
I resolved it like this:
In my component html file apply the customButton class:
```
<button ion-button icon-only clear (click)="openDownloadStatus($event)" [className]="customButton">
  <ion-icon name="md-cloud-outline" color="light"></ion-icon>
</button>
```

in my component .ts file:
```
customButton:string = "disable-hover bar-button bar-button-ios bar-button-default bar-button-default-ios";

    if(this.platform.is('android'){
      this.customButton = "disable-hover bar-button bar-button-md bar-button-default bar-button-default-md";
    }
```

I default it to IOS style but adjust it in ngOnInit for android.  Could you also pass in the platform as an @Input parameter.
