### ISSUE TITLE
ion-input in android  ，execute focus method invalid !

### ISSUE THREAD

**Issue by wqe146273123** [ionic-team/ionic#12571]
import {Directive, ElementRef, OnInit } from '@angular/core';

@Directive({
  selector:'[autofocus]'
})
export class AutoFocusDirective implements OnInit{

  constructor(private elementRef:ElementRef) {  }

  ngOnInit() {
    Array.from(this.elementRef.nativeElement.getElementsByClassName('text-input')).map((node:any)=>{
      //this.renderer.setAttribute(node,'autofocus','autofocus');
      node.focus();
    });
  }

}

<ion-item>
      <ion-label stacked>用户名</ion-label>
      <ion-input autofocus (focus)="test()" type="text" placeholder="请输入用户名" (input)="getUserName($event)" clearInput>
      </ion-input>
    </ion-item>

code a Directive for auto focus , in iOS or  pc is work ! but android is invalid !!!

help me.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
