### ISSUE TITLE
[BUG] <ion-item> listen "ng-valid" / "invalid onChanges and not when the value is changed manually from code

### ISSUE THREAD

**Issue by alex12de** [ionic-team/ionic#12588]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request 

**Current behavior:**

When using ```<ion-item><ion-input>``` in a reactive form or template-driven-form with Validators if the previous status of the control was INVALID setting the value of with formgroup.controls.setValue('validValue') or to binded model manually from code to a VALID value/state does not remove the ```<ion-item>``` "ng-invalid" class from the tag, even if the control.state is VALID and there is no control.errors in the control / model.

It only calculates the status of the control when the user input a value in the control not when it is changed manually.

controls.setValue should revaluate the status of the control by default, and it does. but for some reason the ng-invalid class remains in <ion-item> tag even if the controls.errors is null.

Also is the method control.setError({customErr : true}) is used the classes does not change.

All i just wanted to do was to set a custom format/mask to the value that the user input onBlur

**Expected behavior:**

Changing from code or by user input a value in the ```<ion-input> ```should remove/add the ng-valid || invalid class from <ion-item> element depending on the state of the control.

**Steps to reproduce:**

Step 1: Fill the input with a invalid value
Step 2: With an event (etc) change the value to a valid one from code.

**Related code:**

```
    <form [formGroup]="myForm">
      <ion-item>
        <ion-label>Phone</ion-label>
        <ion-input formControlName="phone" type="tel" (ionBlur)="formatPhone()"> </ion-input>
      </ion-item>
    </form>
    
    this.myForm = formBuilder.group({
    phone : ['', Validators.compose([Validators.pattern([0-9-]*)])]
    })
    
    formatPhone(){
        this.myForm.controls.phone.setValue("132-123-12-12");
        console.log(this.myForm.controls.phone.errors) //to see if there is an validation error. 
   }
```

**Other information:**

Fix: Remove/Add manually the ng-invalid | valid class from ```<ion-item>```editing the DOM.

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.9.1
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.8

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this (:
