### ISSUE TITLE
[BUG] in ionic cordova run ios --prod __Error: Uglify failed: Unexpected token: name (MyPage) in undefined at line undefined, col undefined, pos undefined

### ISSUE THREAD

**Issue by mahmoudrabie** [ionic-team/ionic#12585]
**Ionic version:**  (check one with "x")
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report

**Current behavior:**
ionic serve -l, is working well. However, running the following command:
`ionic cordova run ios --prod
`
gives
`Error: Uglify failed: Unexpected token: name (MyPage) in undefined at line undefined, col undefined, pos undefined
`

**Expected behavior:**
It should deploy the App into the device

**Steps to reproduce:**
`ionic cordova run ios --prod`

**Ionic info:** 

```
cli packages: (MYPROJDIR/node_modules)
    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:
    Cordova CLI : 7.0.1

local packages:
    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:
    Node       : v6.11.0
    OS            : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.1.0
    npm        : 5.3.0
```

Regards
Mahmoud

**Comment by AmitMY** [comment]
Does `cordova run ios` work?

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2618
