### ISSUE TITLE
How to log transition from one NavController push to other?

### ISSUE THREAD

**Issue by imaheshbabu** [ionic-team/ionic#12583]
I am building an app which has heavy usage of Nav and tab controls. I want to track user behavior on my app. 

Ex: User navigated Page A to Page B
      User navigated Page B to Tab C

Initially, I thought of function wrapping each NavController's push method but that doesn't seems to be a good idea.

Version : 2.1.0

Anyone has any other thoughts of solving this problem?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
