### ISSUE TITLE
Ionic 2-Alert Controller input disabled is not working

### ISSUE THREAD

**Issue by mdashiff** [ionic-team/ionic#12586]
Hello!!

Disabled property is not working inside input on alert controller. Read the documentation online it says that the disabled property is not available for input alert controller. Is there any other way to implement this.

            inputs: [
                {
                    label : 'Nationality',
                    disabled : true,
                    name: 'Nationality',
                    placeholder: 'nationality',
                    value: nationality + " 1",
                    type: 'text'
                    
                } 

I need this on alert controller. Any Help???

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
