### ISSUE TITLE
(panend) is never triggered when intercepted by <ion-content> as a view scroll

### ISSUE THREAD

**Issue by PAFsec** [ionic-team/ionic#12587]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
While triggering a pan event over a <div> present inside a <ion-content> that allows scrolling, the events (panstart) and (pan) are triggered and it gets hooked by the <ion-content> that makes the view scroll. Tha behavior is perfectly normal, except that the (panend) event is never triggered for the <div> element.   

**Expected behavior:**
The (panend) event should be triggered as we are not "panning" on the element, but in the <ion-content>, as we are scrolling in the view

**Steps to reproduce:**
1) start panning up on the div element
2) (panstart) and (pan) are triggered
3) the ion-view can't scroll up (as we are already at the top)
4) release the "pan"
5) (panend) is never triggered.
                   
**Related code:**

```
<ion-content>
    <ul>
        <li *ngFor="let el of elements">
            <div class="ElementGo">
                <div class="ElementIn" (panstart)="dragStart($event)" (pan)="dragging($event)" (panend)="dragEnd(el)" >
                </div>
             </div>
        </li>
    </ul>
</ion-content>
```

**Ionic info:** :

```
cli packages:

    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v8.2.1
    OS                : Linux 4.8
    npm               : 5.3.0 
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.
