### ISSUE TITLE
Update URL when changing NavParams for page

### ISSUE THREAD

**Issue by soumak77** [ionic-team/ionic#12596]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Feature Request**
Lets say that you have a page with an `ion-segment` whose default value is configurable via the NavParams (e.g. `/page/:segment`).   When the value for the `ion-segment` is changed, the URL is not updated.  Therefore when the user reloads the browser, they are not shown the same view they had seen prior to reloading.

I understand the above case can be fixed by using tabs, but I can proposing there exist a general solution that allows updating the URL when the value for one or more NavParams is changed.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#291

**Comment by mparpaillon** [comment]
@jgw96 The link is dead. Is this feature request still a thing ?
