### ISSUE TITLE
ion-input of type number allows non-numeric input on iOS

### ISSUE THREAD

**Issue by royalcheeseburger** [ionic-team/ionic#12597]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using a ion-input of type number allows to type non-numeric values on iOS.

**Expected behavior:**
Expecting to be able to enter only [0-9] values

**Steps to reproduce:**

**Related code:**

```
<!-- Limit -->
  <ion-item>
    <ion-label stacked>Limiter le nombre de participants</ion-label>
    <ion-toggle formControlName="isLimited" color="secondary" checked="{{isLimited}}"></ion-toggle>
  </ion-item>

  <ion-item>
    <ion-label stacked>Nombre de participants maximum</ion-label>
    <ion-input [disabled]="!newEventForm.controls['isLimited'].value" formControlName="limitNumber" type="number" placeholder='Nombre limite de participants' tappable></ion-input>
  </ion-item>
```

```
// Creating the newEventForm and specifying controls
    this.newEventForm = this.formBuilder.group({
      title: ['', Validators.required],
      sport: ['', Validators.required],
      date: ['', Validators.required],
      duration: ['', Validators.required],
      location: ['', Validators.required],
      isLimited: [{ value: false, disabled: (this.id ? true : false) }, Validators.required],
      limitNumber: [{ value: '', disabled: (this.id ? true : false) }, Validators.pattern("^[1-9][0-9]*")],
      additionalInfo: ['']
    });
```

**Other information:**
Screenshot: 
<img width="320" alt="capture d ecran 2017-08-07 a 10 32 34" src="https://user-images.githubusercontent.com/1223627/29018561-e1fed48a-7b5b-11e7-928a-b1fe24202182.png">

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.6.0
    ionic (Ionic CLI)               : 3.6.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts        : 1.3.12
    @ionic/cli-plugin-cordova : 1.4.1
    Cordova Platforms         : android 6.2.3 ios 4.4.0
    Ionic Framework           : ionic-angular 3.2.1

System:

    Android SDK Tools : 25.2.3
    Node              : v6.9.2
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.2 Build version 8E2002 
    ios-deploy        : 1.9.0 
    ios-sim           : 5.0.13 
    npm               : 3.10.9
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind installing our [wkwebview plugin](https://github.com/ionic-team/cordova-plugin-wkwebview-engine) and giving this another try?

**Comment by royalcheeseburger** [comment]
Hi @jgw96 I surely can. I am working on a production app. Any risk installing your plugin?

**Comment by royalcheeseburger** [comment]
@jgw96 I just installed the wkwebview plugin and the problem persists...

**Comment by jgw96** [comment]
Hmm interesting. @royalcheeseburger thanks for giving that a try. If you inspect that `ion-input` do you see the `type=number` on the real input that it wraps?

**Comment by royalcheeseburger** [comment]
@jgw96 yes that's, by the way, the most incomprehensible part... see the screenshot
<img width="861" alt="capture d ecran 2017-08-09 a 17 22 17" src="https://user-images.githubusercontent.com/1223627/29129550-7424265e-7d27-11e7-8952-6713a847ca6e.png">

**Comment by royalcheeseburger** [comment]
@jgw96 yes that's, by the way, the most incomprehensible part... see the screenshot
<img width="861" alt="capture d ecran 2017-08-09 a 17 22 17" src="https://user-images.githubusercontent.com/1223627/29129648-c81a7830-7d27-11e7-9b64-c721dfd396d7.png">

**Comment by jgw96** [comment]
Hmm, so it looks like `type=number` is being added. After further research https://github.com/angular/material/issues/8502#issuecomment-220329325 this looks like a safari issue. [This article](http://danielfriesen.name/blog/2013/09/19/input-type-number-and-ios-numeric-keypad/) looks like a good workaround for it. Thanks!

**Comment by royalcheeseburger** [comment]
@jgw96 alright. Thanks for the research and the help !
