### ISSUE TITLE
Buggy InfiniteScroll position=top on iOS

### ISSUE THREAD

**Issue by stalniy** [ionic-team/ionic#12598]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently when you scroll top on iOS, scrollTop position of `ion-content` is not properly updated, thus infinite scroll is called until everything is loaded and scroll position jumps

**Expected behavior:**
When a new set of items is loaded scrollTop should be properly updated without jumps

**Steps to reproduce:**
1. Open `components/infinite-scroll/test/position-top` on iOS and scroll top

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0 (/home/sergii/projects/misto/node_modules/@ionic/cli-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.4.0 (/home/sergii/projects/misto/node_modules/@ionic/cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (/home/sergii/projects/misto/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (/home/sergii/projects/misto/node_modules/ionic)

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v8.1.4
    OS                : Linux 3.19
    npm               : 5.0.3 
```

**Comment by jobvanstiphout** [comment]
I assume you are using WKWebView here? If so, this is a duplicate of #11587.

**Comment by stalniy** [comment]
@jobvanstiphout correct, thanks!
