### ISSUE TITLE
ionBlur on ion-textarea not firing on iOS (or firing too late)

### ISSUE THREAD

**Issue by chris08002** [ionic-team/ionic#12595]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Modal with ion-textarea and close button.

Close button does a dismiss of the modal.
ion-textarea has an ionBlur event which calls updateField() and should do a database update.

ionBlur event is not triggered on iOS, it is only called on "ionic serve"

**Expected behavior:**
ionBlur event should be fired before dismissing the modal

Works correctly on ion-input filed or when using ionic-serve

**Steps to reproduce:**

**Related code:**

```
<button (tap)="close()" ion-button></button>

<ion-textarea
    [(ngModel)]="object[field.key]"
    (ionChange)="textareaOnChange($event)"
    (ionFocus)="textareaOnFocus($event)"
    (ionBlur)="updateField($event, $event.value, field.key, field.type)" >
</ion-textarea>

updateField(event: any, value: any, key: string, type: string): void {
  this.loadingFields = true;
  this.provider.updateField(this.object.id, key, value, type)
  .subscribe(({ loading }) => this.loadingFields = loading );
}
  
close(): void {
    // with workaround timeout to fix the bug
    setTimeout( ()=> {
      this.viewCtrl.dismiss({ id: this.object.id });
    }, 1000);
}


```

**Other information:**
Workaround: Use a 1000ms timeout in close() before calling vievCtrl.dismiss()

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0 (/Users/chris/Development/viq-app/node_modules/@ionic/cli-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.4.0 (/Users/chris/Development/viq-app/node_modules/@ionic/cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (/Users/chris/Development/viq-app/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (/Users/chris/Development/viq-app/node_modules/ionic)

global packages:

    Cordova CLI : 6.5.0 

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.1.2 ios 4.3.1
    Ionic Framework    : ionic-angular 3.5.3

System:

    Android SDK Tools : 25.2.5
    Node              : v6.9.5
    OS                : OS X El Capitan
    Xcode             : Xcode 8.2.1 Build version 8C1002 
    ios-deploy        : 1.9.0 
    ios-sim           : 5.0.3 
    npm               : 4.2.0 
```

**Comment by jgw96** [comment]
Hello, would you mind installing our [wkwebview plugin](https://github.com/ionic-team/cordova-plugin-wkwebview-engine) and trying again please? Thanks!

**Comment by kensodemann** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by chris08002** [comment]
@kensodemann @jgw96 Sorry for the late reply. I am using wkwebview now and it looks like this issue is solved.
