### ISSUE TITLE
ionic3 import angular4(user typescript) package error

### ISSUE THREAD

**Issue by sunnyke** [ionic-team/ionic#12593]
hi, this is my problem:
Runtime Error
Module build failed: Error: ENOENT: no such file or directory, open 'D:\sunny\project\wow-test\node_modules\b-wit-pilot-login\index.js' at Error (native)

Stack
Error: Module build failed: Error: ENOENT: no such file or directory, open 'D:\sunny\project\wow-test\node_modules\b-wit-pilot-login\index.js'
    at Error (native)
    at Object.defineProperty.value (http://localhost:8100/build/vendor.js:113518:7)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.224 (http://localhost:8100/build/main.js:208:27)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.208 (http://localhost:8100/build/main.js:180:20)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at webpackJsonpCallback (http://localhost:8100/build/vendor.js:26:23)
    at http://localhost:8100/build/main.js:1:1

Ionic Framework: 3.6.0
Ionic App Scripts: 2.1.3
Angular Core: 4.1.1
Angular Compiler CLI: 4.1.1
Node: 6.11.1
OS Platform: Windows 7
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

How to solve this problem?
Thanks!

**Comment by AmitMY** [comment]
`b-wit-pilot-login` is not a real package, run a project search for that string to figure out where you import it.

**Comment by sunnyke** [comment]
@AmitMY  b-wit-pilot-login is my private compoment(use angular4 and typescript write).
This question is how to npm install a typescript write package into a ionic project. Thinks for your answer.

**Comment by AmitMY** [comment]
So the issue seems to be in your import. instead of importing from `b-wit-pilot-login`, do a relative path like `../b-wit-pilot-login` or the correct right path.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
