### ISSUE TITLE
ionic 3 ion select with search bar

### ISSUE THREAD

**Issue by ominfowave** [ionic-team/ionic#12594]
how to add search bar in ion select in ionic 3 such as how to search country in list of country in ion select

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
