### ISSUE TITLE
Allow using ion-tabs without navigation

### ISSUE THREAD

**Issue by soumak77** [ionic-team/ionic#12591]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Feature Request:**
Due to all the navigation issues introduced by version 3.6, I can no longer use the latest version of this framework.  The biggest issue I'm facing is that navigation is completely broken with the Tabs component.  Rather than have Ionic control the navigation, I'm wondering if I need to switch to use my own solution.  However, I would still like to use the Tabs component in various places.

I would like to request the ability to use the Tabs component with navigation support disabled.  The approach I'm using now to get this support is to use an `ion-segment` within an `ion-toolbar`, however, this does not match the exact styling that `ion-tabs` provides.

**Comment by ghenry22** [comment]
Being able to use tabs & segments in the same way either with navigation and seperate pages or with the ngswitch style that segments currently support would be really good.

Because I have segments and want to use navigation between them, the opposite of your case but quite related ;)

**Comment by jgw96** [comment]
@soumak77 Sorry your having issues where the tabs are not working for your use case. Would you mind elaborating more on what is not working with them for you? I know you have opened an issue or two around some router issues with tabs but is there more going on?

**Comment by lostdev** [comment]
I agree with @soumak77, I have action buttons at the bottom of my view; I lost 4 hours attempting to tweak the tabs to call actions on my page to no avail (it worked using (ionSelect) but the tabs are simply too tied into the navigation mechanism that I could not continue).

I ended up styling buttons to look like the tabs.

**Comment by soumak77** [comment]
@jgw96 When I have some time I'll try out the latest version again and provide you with more info on my issues with tabs and navigation.  However, regardless of those issues, it appears this request is still valid as others have confirmed.

**Comment by soumak77** [comment]
@jgw96 I believe most of my issues with navigation boil down to https://github.com/ionic-team/ionic/issues/12481.  If default history is utilized correctly, I believe that would solve a lot of issues with my layout and the way in which Ionic generates a page stack from a URL.
