### ISSUE TITLE
bug with cordova: view not updating after browser back

### ISSUE THREAD

**Issue by christophenne** [ionic-team/ionic#12608]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
An IonicPage A contains buttons, which - when clicked - update a property in the component. This property itself is used in an `*ngIf` in the template of the page. Long story short: Clicking a button should change something in the view. 
Bug: When the user navigates from this Page A to an IonicPage B via the navController push method, and then uses the **browser back button** to get back to Page A, the view is not updated properly anymore. The page looks like before, and you can click the buttons, and the properties will be set, but the view does not get rerendered (at least not until the window is resized). 
This only happens when I use the cordova browser build, it's fine with the ionic dev server.

**Expected behavior:**
Like described above, if I go back to Page A, it should have the same behaviour like on the first visit: When a property in the component is updated, and that property somehow affects something on the template via `*ngIf,`, the view should be rerendered immediately. 

**Steps to reproduce:**
I created a little example project based on the blank template, you can get it here: https://github.com/christophenne/ionic3-ngIf-problem .
To reproduce, run `npm install`, followed by `ionic cordova run browser`. As soon as you see the app in your browser window, click the select buttons a few times to verify that the view gets updated.
Then click the link to go to "page 2". And then use the browser back button, to get back to the home page. 
Clicking the buttons again, you should see that the view is not updated anymore.

Also have a look into the browser console when you try it. You will see, that the click Method gets called and the property in the component does get updated. It's only that the template is not updated after a new value is set. As soon as you resize the browser window, the view gets updated also.

**Related code:**

Please have a look at the example I created in https://github.com/christophenne/ionic3-ngIf-problem . An interesting finding, is that it works when I manually call `detectChanges()` like this:
```
click(val : number){
    console.log("click(" + val + ")");
    this.selected = val;
    console.log("this.selected = " + this.selected);
    this.cdr.detectChanges();   //this should not be necessary
}
```
where `this.cdr` is a ChangeDetectorRef injected like this:
```
constructor(public navCtrl: NavController,
    private cdr : ChangeDetectorRef) {
}
```

I had to use this workaround to get the project I am working on into production for now, but it definetly is not a permanent fix for this kind of issue.

**Other information:**
I have already created the exact same issue here a few days ago, but it seems that it was closed by accident and then never looked into - and now it probably never will be answered again: https://github.com/ionic-team/ionic/issues/12512

I also tried to get help in the ionic forum: https://forum.ionicframework.com/t/problem-with-ionic-cordova-browser-build-ngif-browser-back/100090 .

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : browser 4.1.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node       : v6.11.0
    OS         : Linux 3.13
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10 
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! At this time we do not recommend using the cordova browser platform as it is experimental and very buggy (as you can see from the issue your seeing haha). If you would like to deploy your ionic app to the web you can run `npm run ionic:build --prod` and then your www folder will be what you want to deploy to your web server/hosting service.
