### ISSUE TITLE
New code style issue

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#12606]
**Ionic version:**  (check one with "x")
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] styling issue

**Current behavior:**
Shouldn't [these two lines](https://github.com/ionic-team/ionic/blob/mono-refactor/packages/core/src/components/searchbar/searchbar.tsx#L355) be `onClick`  and `onMousedown`?

**Comment by brandyscarney** [comment]
You are correct, closed by https://github.com/ionic-team/ionic/commit/487948eeb9c97164be141444fd8b3877a6895b59
