### ISSUE TITLE
ion-slides w/ loop enabled causes ionSlideDidChange to fire immediately when the component loads

### ISSUE THREAD

**Issue by josh-m-sharpe** [ionic-team/ionic#12603]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
A simple ion-slides setup with loop and ionSlideDidChange:

```
  <ion-slides (ionSlideDidChange)='ionSlideDidChange()' loop>
      <ion-slide>
        1
      </ion-slide>
      <ion-slide>
        2
      </ion-slide>
  </ion-slides>
```

This causes ionSlideDidChange to fire one time when the component is loaded before any user interaction.  ionSlideWillChange behaves the same way - i guess it's possible other events are affected.

It seems like those events should only fire when an interaction occurs.

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this issue.

**Comment by josh-m-sharpe** [comment]
@jgw96 this is v3.
