### ISSUE TITLE
DateTime picker changing the location

### ISSUE THREAD

**Issue by maantje** [ionic-team/ionic#12604]
**Ionic version:**
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**
[x] bug report
[x] feature request

**Current behavior:**
Currently when using a ion-datetime the picker for selecting the date the picker opens at the bottom of the screen, When trying to use the wheel to make a selection sometimes the IOS Control Center is opened instead. 

**Expected behavior:**
What I propose is to allow to change the location where the picker opens, so it is possible to open it in the center or top of the screen removing the problem of the IOS Control Center. I tried doing this manually by editing the CSS but can't get the animation to play correctly and it would be nice to be able to just add a position property.

**Steps to reproduce:**
Make a view with a ion-datetime.
Click on it.

**Dead link in docs**

Also the link to the picker api docs is dead on this [page](https://ionicframework.com/docs/api/components/datetime/DateTime/)  on the following line
pickerOptions | any | Any additional options that the picker interface can accept. See the [Picker API docs](https://ionicframework.com/docs/v1/api/components/picker/Picker) for the picker options.

**Ionic info:** 

```
cli packages: (/Users/Maantje1/Documents/Developing/igsys/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    npm        : 4.2.0
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#292
