### ISSUE TITLE
Documentation for ion-input incorrect for autocomplete and autocorrect attributes

### ISSUE THREAD

**Issue by kelvindart** [ionic-team/ionic#12609]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The documentation for the two attributes: `` and `` are incorrectly labelled: `@input {string} Instructional text that shows before the input has a value.`

**Expected behavior:**
For these to be labelled correctly. I have created a pull request and raising this to link the two.

N/A

**Comment by kelvindart** [comment]
I pushed some commits incorrectly for the first pull. Ignore this - the second Open link is correct.

**Comment by jgw96** [comment]
Thanks for the PR @kelvindart ! Since Manu merged it I am going to close this issue for now. Thanks!
