### ISSUE TITLE
Base64 not displayed on iOS devices 10.3.2

### ISSUE THREAD

**Issue by speedfl** [ionic-team/ionic#12612]
**Ionic version:**  (check one with "x")
2.3.0

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The base 64 images are not displayed on any views with iOS 10.3.2
This is currently working with android devices and web.
I saw that people have issues with ionic view but here I am testing on real device (iPhone SE)
I tried with
```<img src="data:image/{{profilePicture.type}};base64,{{profilePicture.elementBase64}}">```
```<ion-img="data:image/{{profilePicture.type}};base64,{{profilePicture.elementBase64}}">```

**Expected behavior:**
The base64 image must be displayed

**Steps to reproduce:**
Create a sample project with ionic 2.3.0
Create a variable profilePicture which contains type png and elementBase64 with the base64 content

ionic build iOS and deploy on iOS device 10.3.2

**Comment by speedfl** [comment]
Hello,

So after an update of my app by removing the Content-Security-Policy the base64 image appears. However it is just shown when the page is reloaded (example I navigate to a page and go back to the one where the image is not displayed)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by speedfl** [comment]
@jgw96 this is not support. This is a bug. The base64 is not loaded the first time and the issue only occurs on iOS devices. The base64 is there as I tried to display the code as text and I can see it.
You can make a simple try and you will see.

**Comment by speedfl** [comment]
Just for information I even put a timeout and the pictures is grayed.
Once I switch the tab and go back the picture appears

This only occurs on ios.
This is reproducible with serve --lab
