### ISSUE TITLE
Add a new LinkAlert component

### ISSUE THREAD

**Issue by Spartanace1024** [ionic-team/ionic#12618]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I wanted to add a very simple link below some text using a BasicAlert. I was able to do so, but upon adding a (click) to the link it fails due to sanitization issues.
 
**Expected behavior:**

It would be nice to have this functionality in the future by either adding a bypassSecurityFlag for the message, or by possibly adding a new Alert type such as Link Alert.
 
*Sample Image*

![image](https://user-images.githubusercontent.com/2967721/29090299-b44fa87c-7c44-11e7-8e25-44404b071eae.png)

**Steps to reproduce:**

1.Create a basic project.
2.Add code below to new project.
3.Invoke createAlert().
3.Check console for sanitization error
**Related code:**

```
public createAlert(){
    let linkAlert = this.alertCtrl.create({
      title: 'Support',
      message:`
      Phone: 555-555-5555<br />
      Email: email@email.com<br />
      <a (click)="someFunction()">Test Link</a>
      `,
      cssClass: "support-alert",
      buttons: ['OK']
    });
    linkAlert.present();
}
private someFunction(){
    console.log("hello");
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#294
