### ISSUE TITLE
Unable to close a modal after closing another one in background

### ISSUE THREAD

**Issue by HugoHeneault** [ionic-team/ionic#12616]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a lalyloaded modal A opened. From this modal, I open another lazyloaded modal B, and then close the A modal while the B is opened. When I try to close the B one with `dismiss()`, it's not closing.

**Expected behavior:**
The B modal should close when `dismiss()` is called.

**Steps to reproduce:**
I tried a plunker without lazy loading, and it's working, so I tried with lazy loading, but I have an issue with my plunker and lazy loading. :(
The code is here, but it's not working as I have a lazy loading issue : http://plnkr.co/edit/PCVIKNSpIT5FOmfc9vIm?p=preview
It's probably an easy thing but I can't manage to fix it 😭 

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.0

System:

    Android SDK Tools : 26.0.2
    Node              : v7.10.1
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b
    ios-deploy        : 1.9.1
    npm               : 4.2.0
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by HugoHeneault** [comment]
Thanks @jgw96 ! If you have any idea on why my plunkr is failing, I'll update it.
