### ISSUE TITLE
Lazy loading from one tabs page to another tabs page doesn't load tab of second page

### ISSUE THREAD

**Issue by shajeeck** [ionic-team/ionic#12619]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When nav.setRoot using lazyLoad is called from one page with tabs to another page with tabs, the tabs are loaded but doesn't load the first tab of second page, but instead shows first tab of first page itself.
Only clicking on first tab shows the page

assuming i have 2 pages

- page1 with two tabs first, second

- page2 with two tabs third, fourth

initial url : http://localhost:8100/#/page1/first/first
url after setRoot page2 : http://localhost:8100/#/page2/third/first

**Expected behavior:**
when navigating to page2 show first tab of page2
url after setRoot page2 should be : http://localhost:8100/#/page2/third/third

**Steps to reproduce:**
Create a sidemenu app with 2 pages page1 and page2 and make page loading with lazyloading (@IonicPage())
page1 should have 2 tabs named first and second
page2 should have 2 tabs named third and fourth

now ionic serve and navigate from page1 to page2

**Other information:**
I am using LazyLoading for all Pages

**Ionic info:**:

```
@ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.9.1
    OS   : Windows 10
    npm  : 4.1.2
```

**Comment by jgw96** [comment]
Thanks for using Ionic! Would you mind sharing a repo we could use to reproduce this issue?

**Comment by shajeeck** [comment]
My same issue is better explained in this issue

https://github.com/ionic-team/ionic/issues/12625

**Comment by shajeeck** [comment]
Closing this issue, better explained here https://github.com/ionic-team/ionic/issues/12625
