### ISSUE TITLE
docs: CLI documentation is broken

### ISSUE THREAD

**Issue by Polyergic** [ionic-team/ionic#12620]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>https://ionicframework.com/docs/cli/build kicks me back to https://ionicframework.com/docs/cli/.  There doesn't seem to be a way to access the documentation for `build`</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-site#1230
