### ISSUE TITLE
ionInput components with clearInput attribute should have a (ionClear) event

### ISSUE THREAD

**Issue by thibaultehrhart** [ionic-team/ionic#12627]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently there is no way to know when the user taps on the clear button on ionInput components with the clearInput attribute.

**Expected behavior:**
Adding a ionClear event would allow doing specific actions when the user clears the input

For example, ionSearchBar has a ionClear event that is [triggered (searchbar.ts#L333)](https://github.com/ionic-team/ionic/blob/6dee17b89bafdae588d2bfbadf29c92e1440e08f/src/components/searchbar/searchbar.ts#L333) when the user clicks on the clear button.

**Steps to reproduce:**
```
<ion-input clearInput (ionClear)="onInputClear($event)"></ion-input>
```
```
onInputClear(ev: any) {
  // do something
}
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : ios 4.3.1
    Ionic Framework    : ionic-angular 3.5.3
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#295
