### ISSUE TITLE
Datetime min/max not accepting Date objects

### ISSUE THREAD

**Issue by viki53** [ionic-team/ionic#12626]
**Ionic version:**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request

**Current behavior:**

When using an `ion-datetime` component, I need to use dynamic `min` and `max` params, but the component expect strings, so I have to convert my `Date` objects to strings, which causes more un-necessary work.

**Expected behavior:**

`min` and `max` should accept `Date`, as well as `string` and `number` types, just like `ngModel`.

**Steps to reproduce:**

```typescript
@Component({
	selector: 'datetime-text',
	template: '<ion-datetime [min]="minDate" [max]="maxDate"></ion-datetime>'
})
export class TestPage {
	public minDate: Date = new Date();
	public maxDate: Date = new Date();

	constructor() {
		this.minDate.setMonth(this.minDate.getMonth() - 1);
	}
}
```

**Ionic info:**

```
cli packages: (~/project/path/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node  : v8.1.2
    OS    : macOS Sierra
    Xcode : Xcode 8.3.2 Build version 8E2002 
    npm   : 5.3.0 
```

---

**Note:** The doc should also be updated accordingly once this is fixed

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#293

**Comment by mubasshir** [comment]
For some needy,

html
`<ion-datetime displayFormat="DD MMM YYYY, h A" formControlName="due_date" max="2050" [min]="getCurrentTime()"></ion-datetime>`

ts
```
getCurrentTime() {
    return moment().format();
}
```
