### ISSUE TITLE
How to use slice javascript function in ionic 3 ?

### ISSUE THREAD

**Issue by tunathoni** [ionic-team/ionic#12621]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Hi ionic team, i just to know how to slice an array in ionic 2 ? in javascript we know that `slice()` function is for get custom array index. but i try it on my provider it cannot. and show error like this : 

`property slice doesn't exist on type void`

**Comment by AmitMY** [comment]
Well, you can use `slice` on arrays, but not on a `void` type..

**Comment by tunathoni** [comment]
Thanks @AmitMY can you tell me the example ?

**Comment by AmitMY** [comment]
```ts
class Someclass {
  someArray: Array<any>;
  constructor() {
    this.someArray.slice(0, 1); // ERROR
    this.someArray = [1, 2];
    this.someArray.slice(0, 1); // [1]
  }
}
```

**Comment by tunathoni** [comment]
Thanks @AmitMY it's work.. 👍
