### ISSUE TITLE
platform.is('ios') return false in ios simulator?

### ISSUE THREAD

**Issue by longdw** [ionic-team/ionic#12622]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
platform.is('ios') return false in ios simulator

**Related code:**

```
this.platform.is('ios')
```

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic. Does this only happen on the simulator or on an actual device too? Also, is it using the iOS styles or the material design styles on the app running on the sim?

**Comment by longdw** [comment]
@jgw96  I used iOS styles and only happen on the simulator

**Comment by jgw96** [comment]
Hello @longdw , are you loading cordova in your app? Do you see any warnings in the console about cordova taking to long to init?

**Comment by longdw** [comment]
@jgw96  It's my fault, I init the platform with new Platform(), when I init it in construstor(private platform Platform), it comes ok. thank you.

**Comment by anjildhamala** [comment]
I would like to ask Ionic Team on why new-ing up platform doesn't work and only works when injected?
