### ISSUE TITLE
white screen on touch for lower resolution phones after building using --prod flag

### ISSUE THREAD

**Issue by wizlif** [ionic-team/ionic#12623]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Screen goes white on touch for phones with resolution 480x800 and below

**Other information:**

Illustration
![ezgif-4-4bca89e97b](https://user-images.githubusercontent.com/15793624/29111791-5a36b488-7cf4-11e7-8524-51722c0e6d6f.gif)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-utils  : 1.6.0 (/root/Templates/Akorion Projects/EzyExtensionV2/node_modules/ionic/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI) : 3.6.0 (/root/Templates/Akorion Projects/EzyExtensionV2/node_modules/ionic)

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Android SDK Tools : 26.0.2
    Node              : v7.4.0
    OS                : Linux 4.9
    npm               : 5.0.0 

```

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Hmm this is interesting. First, what version of android is this device running? Looks like 4.x from the screenshot. Also, if you open this https://conferenceapp-176d4.firebaseapp.com in chrome on that device does the same issue happen?

**Comment by wizlif** [comment]
It's using android 4.4 and on opening the confrence app it works fine.
The app actually works fine when i run it without the --prod

**Comment by jgw96** [comment]
Hello, thanks for using Ionic-Angular. Unfortunately we cannot reproduce this issue. Because of this I am going to recommend you take this issue to our [forum](https://forum.ionicframework.com) or our [slack channel](https://ionicworldwide.herokuapp.com/)
