### ISSUE TITLE
Ionic 2 - Angular 2 | The Website doesn't load with [(ng-Model)] (with brackets) in the input

### ISSUE THREAD

**Issue by frautomke** [ionic-team/ionic#12632]
**Ionic version:**  (check one with "x")
[x ] **3.7.0**

**I'm submitting a ...**  (check one with "x")
[x ] bug report

**Current behavior:**
If I enter "ionic serve", the website only loads, if I leave in the import the braces around the ng-model

**Expected behavior:**
The website should also load with the brackets around ng-Model, because as far as I know, this is the correct spelling

**Related code:**
![image](https://user-images.githubusercontent.com/30658306/29157997-7d8a6ece-7da9-11e7-91df-9badb5057fc7.png)

**Other information:**
I am currently working in Ionic and Angular. I would just like a simple program that reads two values, adds and outputs again.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
No Errors or warnings

**Comment by davec21** [comment]
It's because there shouldn't be a hyphen. It's just ` [(ngModel)]`

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
