### ISSUE TITLE
cant't link a list

### ISSUE THREAD

**Issue by ChenYCL** [ionic-team/ionic#12634]
### error info
-----
**Runtime Error 
Uncaught (in promise): invalid link: LotteryPage**
```
imports: [
    HttpModule,
    BrowserModule,
    FormsModule,
    JsonpModule,
    IonicModule.forRoot(
      MyApp,
      {
        backButtonText: "",
        mode: "ios"
      },
      {
        links: [
          { component: LotteryPage, name: "Lottery", segment: "page-lottery" , defaultHistory: [HomePage] },
          // { component: AdDetailPage, name: "AdDetail", segment: "ad-detail/:uuid" , defaultHistory: [HomePage] },
          // { component: GoodDetailPage, name: "GoodDetail", segment: "good-detail/:goodsuuid" , defaultHistory: [HomePage] }
      ]
      }
    )
  ],
```
- ![image](https://github.com/ChenYCL/img_bug/raw/master/ionic.jpg)

**Comment by davec21** [comment]
The error is pretty clear. You have the LotteryPage referenced in two modules. You can't do that, you need to import it in whatever the highest level module is.  The error message is pretty clear.

**Comment by ChenYCL** [comment]
@davec21  Thx first,it's mean that  i need to import only one module? ,but there's  a  needs in here, when i share the message about Lottery info-page in some app,  people click it and should locate in the page, now issues is people click it,show mainPage,not lotteryP?  i try deeplink router-config ,but it not wroks

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
