### ISSUE TITLE
Navigation/deeplink with tabs

### ISSUE THREAD

**Issue by rodrigoreal** [ionic-team/ionic#12631]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Deeplink is not working when using tabs.
I'm setting an value to the `segment` on the `IonicPage()` and it changes the url correctly
But if i copy and paste the url on a new tab, it is being redirected to my home page.
On my home page i have that:
```@IonicPage({
  name: 'pets-list',
  segment: 'pets'
})
```
It generate this url: `http://localhost:8100/#/tabs/0/pets`

And i have an pet detail page with
```
@IonicPage({
  name: 'pets-detail',
  segment: 'pets/:pet',
  defaultHistory: ['pets-list'],
})
```
And i get this url: `http://localhost:8100/#/tabs/0/pets/-KqPjNf6_S9uTDZ_X2vd`

If i try to access direct this url: `http://localhost:8100/#/tabs/0/pets/-KqPjNf6_S9uTDZ_X2vd` i'm being redirected to `http://localhost:8100/#/tabs/0/pets`

But if i remove the tabs from my app and put the `pet-list` as root it works perfect.
`http://localhost:8100/#/pets/` and `http://localhost:8100/#/pets/-KqPjNf6_S9uTDZ_X2vd` work
`http://localhost:8100/#/tabs/0/pets/` and `http://localhost:8100/#/tabs/0/pets/-KqPjNf6_S9uTDZ_X2vd` don't work

My `tabs.ts`:
```
import { Component } from '@angular/core';
import { IonicPage } from 'ionic-angular';

@IonicPage({})
@Component({
  templateUrl: 'tabs.html'
})
export class TabsPage {

  tab1Root: string = 'pets-list';
  tab2Root: string = 'pets-vaccines';

  constructor() {}
}
```

`tabs.html`:
```
<ion-tabs>
  <ion-tab [root]="tab1Root" tabUrlPath="0" tabIcon="paw" tabsHideOnSubPages="true"></ion-tab>
  <ion-tab [root]="tab2Root" tabUrlPath="1" tabIcon="calendar" tabsHideOnSubPages="true"></ion-tab>
</ion-tabs>
```

**Expected behavior:**
https://mhartington.io/star-track-ionic/#/menu/nav/list/menu-list/nav/main/detail/452905764

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.1.2 ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node       : v6.9.5
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.0.8
    npm        : 3.10.10
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Could you share a repo we could use to reproduce this issue?

**Comment by kensodemann** [comment]
Hello! Is this still an issue with the latest version of ionic? If so, could you please provide a sample application via GitHub that demonstrates the issue you hare having?

Also, check #12680 and see if the workarounds mentioned there get you past your issue.

Thanks!

**Comment by danbucholtz** [comment]
Hi,

I cannot recreate this. Please let us know if you are still experiencing the issue and provide a sample project.

Thanks,
Dan

**Comment by yunderboy** [comment]
@danbucholtz I'm experiencing the same issue, take a look: https://github.com/wemuda/detectox

Sincerely Emil
