### ISSUE TITLE
bug: Deep links and tabbed navigation don't work

### ISSUE THREAD

**Issue by snortblt** [ionic-team/ionic#12639]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>When using @Page() deep linking in Ionic 3.6.0, I can't find a combination of settings that allows deep linking to work properly. Reloading the browser doesn’t push the defaultHistory correctly and the back button is not shown for the top page on the stack inside a tab after a reload. Also the URL stops tracking correctly after a reload. I have tried every possible combination of approaches I can think of based on the sparse information provided in the docs to no avail. It's very unclear how this should work in a tabbed situation and, in general, how this works with the deep links plugin.</span>

<span is-issue-template></span>

**Comment by hous04** [comment]
I have the same error with Ionic 3.6.6 `Uncaught (in promise): invalid link:`

**Comment by kensodemann** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by snortblt** [comment]
:( Well, I did just that @kensodemann, but there has been no action there other than one user assuring me that I would get no answer on the forum as the team is too busy and suggesting this was the correct place to post. Shrug.

**Comment by danbucholtz** [comment]
@snortblt,

Can you provide a basic minimized reproduction case? Also, please fill out the issue template.

Thanks,
Dan

**Comment by snortblt** [comment]
Thanks @danbucholtz. That helped quite a bit, at least with respect to URLs tracking and reloading consistently. I had assumed (apparently incorrectly) that deep linking and lazy loading were independent and was mixing lazy and eager loading, which appears to break things. 

After moving to lazy loading entirely, the only problem still persisting is the defaultHistory isn't being honored after a reload. This could be because I'm not using it right, but I can't find a single example in the test projects you referred to that use the history. Please see my attached
project.

[nav-more-demo.zip](https://github.com/ionic-team/ionic/files/1226181/nav-more-demo.zip)

**Comment by snortblt** [comment]
The issue with my minimal project can be seen if you nav to More (...) Contacts via the UI. You'll see you get a back button to return to the More nav overflow menu. Reload the Contacts page and the back button is gone.

**Comment by snortblt** [comment]
Hi. Any news on this or other examples I could pull down? Not being able to restore the nav stack is a show stopper for us.

**Comment by danbucholtz** [comment]
Hi, this should be fixed. Please comment if it does not. It will be in the next release on Wed.

```
npm install ionic-angular@3.7.1-201710060319
```

Thanks,
Dan

**Comment by adjmb** [comment]
Hi @danbucholtz. In the release, **3.7.1-201710060319** it was not working for me. However, it worked with **3.7.1-201710101557**

**Comment by snortblt** [comment]
Thanks Dan, but it's not working for me. The browser history is working as expected but I don't get a Back button in the nav bar after reloading a child page in the example I had uploaded.
