### ISSUE TITLE
Why the url still contain 'tabs' after setting the 'name' property of Tabs?

### ISSUE THREAD

**Issue by johnnytung** [ionic-team/ionic#12643]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

My url is like 'http://localhost:8100/#/nav/mainNav/tabsPage/tabs/mainTabBar/tab-favourites/favourites'

**Expected behavior:**

I think it should be 'http://localhost:8100/#/mainNav/tabsPage/mainTabBar/tab-favourites/favourites',
after I set the name property of Nav and Tabs
**Steps to reproduce:**

**Related code:**

```
<ion-nav [root]="rootPage" #content swipeBackEnabled="false" main name="mainNav"></ion-nav>
...
<ion-tabs [selectedIndex]="mySelectedIndex" name="mainTabBar">
...
</ion-tabs>

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.0.1-201707121621
    Cordova Platforms  : android 6.1.0 ios 4.3.1
    Ionic Framework    : ionic-angular 3.5.0-201707121632

System:

    Node  : v8.1.2
    OS    : macOS Sierra
    Xcode : Xcode 8.3.3 Build version 8E3004b 
    npm   : 5.3.0 

```

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I am looking into your issue. In the meantime, please provide your "Ionic info" information (run `ionic info` from the terminal/command prompt).

Thank you for using Ionic

**Comment by johnnytung** [comment]
@kensodemann Thanks for your response, I have appended ionic info.

**Comment by danbucholtz** [comment]
@johnnytung,

I'm not sure, but try `ionic-angular` 3.6.0. In most cases, the `tabs` will go away from the URL. If `3.6.0` isn't work for you, please provide a minimal reproduction case and we'll take a look.

Thanks,
Dan

**Comment by johnnytung** [comment]
@danbucholtz 
It works, thank you!
