### ISSUE TITLE
ItemSliding and VirtualScroll issues

### ISSUE THREAD

**Issue by Tankatronic** [ionic-team/ionic#12649]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using ItemSliding in combination with VirtualScroll, if an item is slid open and the user scrolls down additional items are also slid open. The amount depends on the height of each item and the buffer ratio.

**Expected behavior:**
Only one item is ever opened at a time.

**Steps to reproduce:**
http://plnkr.co/edit/J4kbb9Dj3JqqZfYHvT3N?p=preview

in the above example, if you slide open item 1, items 47, 93, 139, and 185 are also slid open.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

> cli packages:
>     ionic/cli-plugin-cordova: 1.6.2
>     ionic/cli-plugin-ionic-angular : 1.4.1
>     ionic/cli-utils: 1.7.0
>     ionic (Ionic CLI): 3.7.0
>     
> global packages:
>     Cordova CLI : 7.0.1
> 
> local packages:
>     @ionic/app-scripts : 1.3.7
>     Cordova Platforms  : android 6.2.3 browser ios
>     Ionic Framework    : ionic-angular 3.4.1
> 
> System:
>     Android SDK Tools : 25.2.4
>     Node              : v6.9.2
>     OS                : Windows 7
>     npm               : 4.0.5

**Comment by kensodemann** [comment]
Thank you for submitting this issue. I have added a link to this issue to #8744 where we are tracking all of our virtual scroll related issues.
