### ISSUE TITLE
400 ms delay from tap to focus on searchbar input on iOS

### ISSUE THREAD

**Issue by gammelby** [ionic-team/ionic#12654]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Add an `ion-searchbar` component to a page, when tapping the searchbar observe a noticeable delay until the component has focus. If adding `performance.now()` in `searchbar.js` tap and focus events, the delay is measured to about 400 ms between the two.

A similar issue was once reported but closed as performance was "pretty fast": https://github.com/ionic-team/ionic/issues/6028 - 400 ms is indeed not fast and far from the close-to-native experience expected.

**Expected behavior:**
Instant focus like a normal input field.

**Steps to reproduce:**

Reproduced with a template as follows:

```
<ion-header>

  <ion-navbar>
    <ion-title>Searchbar test</ion-title>
  </ion-navbar>

  <ion-toolbar>
    <ion-searchbar [(ngModel)]="searchTerm"
                   [formControl]="searchControl"
                   </ion-searchbar>
  </ion-toolbar>

</ion-header>
```

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/ug/git/ionic-starter-nabto/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v7.9.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy        : 1.9.1 
    ios-sim           : 6.0.0 
    npm               : 4.2.0
```

**Comment by AmitMY** [comment]
You are on iOS, so are you using WKWebView?

**Comment by gammelby** [comment]
No, just the default platform as per ionic info above.

**Comment by AmitMY** [comment]
So try integrating WKWebView:
https://github.com/ionic-team/cordova-plugin-wkwebview-engine

**Comment by gammelby** [comment]
I had a bit of struggle with our own plugin that does not seem to work out of the box with wkwebview, but if reproducing in a simple example with just the searchbar, the delay dropped from 400 ms to less than 40 ms (I verified the 400 ms to still be there with the clean example and no wkwebview). Amazing! Thanks for the suggestion. Should we keep the ticket open as it might be interesting to understand why the regular webview performs as observed?

**Comment by AmitMY** [comment]
Glad it helped you. I hope that next major ionic version will ship with wk, I'll ask the devs.
No, ticket should be closed, as the issue was solved.
