### ISSUE TITLE
[Feature Request] Support text-only avatars

### ISSUE THREAD

**Issue by Airblader** [ionic-team/ionic#12656]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`ion-avatar` can only be used with images.

**Expected behavior:**
It should be possible to also use it with text only to get a text / letter avatar. This is a common use-case for avatars used widely by many companies and applications for cases where no image is available. A very simple such use-case would be an email inbox where no profile picture is available and thus the first letter of the name is used instead to achieve visual consistency.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/home/ingo/.npm-global/lib/node_modules)

    @ionic/cli-utils  : 1.7.0
    ionic (Ionic CLI) : 3.7.0

System:

    Node : v8.2.1
    OS   : Linux 4.11
    npm  : 5.3.0 
```

**Comment by Airblader** [comment]
If accepted, I did write this directive myself in a way that is completely in line with how images are currently styled. Integrating this into ionic would actually make this a change of merely a few lines of code (an empty directive and a couple of lines of SCSS).

I'd be happy to provide a PR if the feature would be accepted. We'd simply need a fitting name, such as `ion-text-avatar` to allow

```
<ion-list>
  <ion-item>
    <ion-avatar item-start>
      <ion-text-avatar>A</ion-text-avatar>
      <h2>Test</h2>
    </ion-avatar
  </ion-item>
  <ion-item>
    <ion-avatar item-start>
      <ion-text-avatar color="secondary">A</ion-text-avatar>
      <h2>Test</h2>
    </ion-avatar
  </ion-item>
</ion-list>

<ion-chip>
  <ion-avatar item-start>
    <ion-text-avatar>A</ion-text-avatar>
  </ion-avatar>
  <ion-label>Test</ion-label>
</ion-chip>
```

**Comment by Airblader** [comment]
Screenshot of examples:

![screenshot-2017-08-13_22-22-28](https://user-images.githubusercontent.com/2392216/29253130-edc1b57a-8075-11e7-9916-87f2ded4762a.png)

**Comment by janpio** [comment]
Would it be possible to write and include this as a standalone component?

**Comment by Airblader** [comment]
Yes and no. I do have it »standalone« right now, but of course it relies on Ionic and in fact requires duplicating styling from Ionic because `ion-avatar` styling has a hard dependency on `img`, for example:

```
.item-ios ion-avatar ion-img,
.item-ios ion-avatar img {
  @include border-radius($item-ios-avatar-border-radius);

  overflow: hidden;

  width: $item-ios-avatar-size;
  height: $item-ios-avatar-size;
}
```

and

```
ion-chip ion-avatar img {
  @include border-radius($chip-avatar-border-radius);

  display: block;

  width: 100%;
  max-width: 100%;
  height: 100%;
  max-height: 100%;
}
```

Integrating it into Ionic directly would mean simply adding another selector here while a standalone component has to duplicate all of this.

**Comment by kensodemann** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#297

**Comment by Airblader** [comment]
Thanks! In the mean time, for anyone looking, I've created https://github.com/Airblader/ionic-text-avatar

**Comment by janpio** [comment]
@Airblader Awesome! Make sure to make a `showcase` or `demo` category post about this in the forum as well!

**Comment by alltej** [comment]
What is the status of this feature? Is it in any of the latest releases yet? Thanks
