### ISSUE TITLE
Content exceeds the margin of the view or interface

### ISSUE THREAD

**Issue by PterPmnta** [ionic-team/ionic#12652]
I've been developing an app on Ionic v1, but today a very strange and confusing problem has appeared.

The problem is that only two devices that I have tried the application so far, the interfaces seem to have errors, as if they did not recognize the `ion-content` tag or any other attribute that helps keep the content inside the margin of view .

For example, the next code, represent the profile teacher view

### Code

```
<ion-header-bar class="bar-balanced" align-title="center">
     <a href="#/menuprof" class="button button-icon icon ion-ios-arrow-back"></a>
     <p class="title">Perfil Docente</p>
 </ion-header-bar>
```
<ion-view>    
    <ion-content has-header="true">
    
            <div class="list logo-perfil">            
                <div id="res" ng-click="obtenerFoto()">
                    <img ng-src="{{data.ImageURI}}" id="myImage" class="image-size" />
                </div>
            </div>
    
            <div class="list row">
    
                <div class="col">
                    <div class="list-borderless">
                        <p class="item">Identificacion</p>
                        <p class="item">Nombres</p>
                        <p class="item">Apellidos</p>
                        <p class="item">Rol</p>
                        <p class="item">Facultad</p>
                        <p class="item">Programa</p>
                        <p class="item">Periodo</p>
                    </div>
                </div>
    
                <div class="col">
                    <div class="list-borderless texto-izquierda">
                        <h3 class="item"><strong>{{Cedula}}</strong></h3>
                        <h3 class="item"><strong>{{Nombre}}</strong></h3>
                        <h3 class="item"><strong>{{Apellido}}</strong></h3>
                        <h3 class="item"><strong>{{Rol}}</strong></h3>
                        <h3 class="item"><strong>{{Facultad}}</strong></h3>
                        <h3 class="item"><strong>{{Programa}}</strong></h3>
                        <h3 class="item"><strong>{{Periodo}}</strong></h3>
                    </div>
                </div>
    
            </div>
    
    </ion-content>    
</ion-view>`

### The views

[with error](http://i.imgur.com/UPZC1Cr.png)
[with out error](http://i.imgur.com/EM6fYhK.png)

I tested in multiples devices

Android version works fine

- 4.2.2
- 5.0.1
- 7.0+
- 6.0.1

Android version error appeared

- 5.1
- 6.0.1

If they are fixed well place that in versions 6.0.1 works and fails, this is due to probe in two computers with the same version and in one works well, while in the other not.

- Ionic version: 2.2.3
- SO: W10 
- Node: 8.2.1

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Can you provide your ionic info output? (type `ionic info` in the terminal/cmd prompt from the root directory of your project)

Thank you for using Ionic!

**Comment by PterPmnta** [comment]
@kensodemann see that

Your system information:

- Cordova CLI: 6.5.0
- Ionic CLI Version: 2.2.3
- Ionic App Lib Version: 2.2.1
- ios-deploy version: Not installed
- ios-sim version: Not installed
- OS: Windows 10
- Node Version: v8.2.1
- Xcode version: Not installed

**Comment by kensodemann** [comment]
Thank you for your reply. I am somewhat confused by your response and the original post / HTML markup that you provided. In the original post, it appears that you are developing an Ionic V1 application. Is that correct?

**Comment by PterPmnta** [comment]
@kensodemann i develop tha app using Ionic V1

**Comment by kensodemann** [comment]
OK, thank you. I will move this issue over to https://github.com/ionic-team/ionic-v1 then.

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-v1#298
