### ISSUE TITLE
why? The name  mast is  xxxx.module???

### ISSUE THREAD

**Issue by whzooo** [ionic-team/ionic#12655]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

import { tstService } from './tstService';
import { tst } from './tst';
import { MyApp } from './../../../app/app.component';
import { NgModule } from '@angular/core';
import { IonicApp, IonicModule ,IonicPageModule} from 'ionic-angular';

@NgModule({
declarations: [
tst
    ],
    imports: [
        IonicPageModule.forChild(tst)
    ],
    entryComponents: [
tst
    ],
    providers: [
tstService
    ]

}) export class tstModule {}

I  want use the ionicpage 
I don't like  the filename like xxxx.module
in java,c#,as3.....   the module name = the file name

I want to unify the filename with the module name. I've been doing this before using ionicpage, but ionicpage requires that the name of xxx.module be used to work properly

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
G:\newWork\nodejs\taobao_xiao_client\taobao_xiao_client\src\pages\index\tst\tst.ts has a @IonicPage
            decorator, but it does not have a corresponding "NgModule" at
            G:\newWork\nodejs\taobao_xiao_client\taobao_xiao_client\src\pages\index\tst\tst.module.ts

**Comment by whzooo** [comment]
G:\newWork\nodejs\taobao_xiao_client\taobao_xiao_client\src\pages\index\tst 的目录

2017/08/14  00:58    <DIR>          .
2017/08/14  00:58    <DIR>          ..
2017/08/14  00:17               124 tst.html
2017/08/14  00:17                 5 tst.scss
2017/08/14  00:24               780 tst.ts
2017/08/14  00:58               462 tstModule.ts
2017/08/14  00:17               840 tstService.ts

**Comment by whzooo** [comment]
that the name of tst.module.ts be used to work properly
i want tstModule.ts

**Comment by AmitMY** [comment]
First of all this took ages to figure out. Please write an issue to the issue format.

Currently, ionic only supports `.module` and it does not seems it gonna change soon. If you want, you can create a feature request.

**Comment by whzooo** [comment]
sorry
