### ISSUE TITLE
ion-input scrolls to top on focus and select control shows options on "Go" button click

### ISSUE THREAD

**Issue by JuanJoseRhoads** [ionic-team/ionic#12651]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Hi Ionic team! I'm facing an issue in ionic 3.x with inputs. The problem occurs when the user clics on an input and tries to type the text, when the keyboard shows all the content is scrolling up and some inputs are not visible. This issue is a major issue in Android devices.
Also I noticed that if I have an "ion-select" control into a form with a submit button and I click on the "Go" button (this button shows in the keyboard when the user is typing in another input) it shows the "ion-select" options instead of submiting the form.

**Expected behavior:**
The input should be visible, this way the user can see what he is typing.
Ion options should not show when I click over "Go" button

**Steps to reproduce:**
With a simple application (created with ionic start) you can add a simple form with many inputs (5 or 6 would be enough).

**Related code:**
Here is my code in the frontend:
```
<form [formGroup]="addressForm" (ngSubmit)="searchAddress()">
  <div class="form-primary" style="vertical-align: top;">
    <ion-list>
      <!-- Zip code -->
      <ion-item class="input">
        <!-- <ion-label>
          <ion-icon name="pin"></ion-icon>
        </ion-label> -->
        <ion-input clearInput 
                   type="tel" 
                   placeholder="Zipcode" 
                   formControlName="zipCode"
                   (keyup)="findZipCode()">
        </ion-input>
      </ion-item>

      <!-- Estates -->
      <ion-item class="input">
        <ion-label>
          <ion-icon name="pin"></ion-icon>
        </ion-label>
        <ion-select formControlName="selectedEstate" 
                    (ionChange)="estateChanged()"
                    placeholder="Estate"
                    cancelText="Cancel"
                    okText="Accept">
          <ion-option value="{{ e }}" *ngFor="let e of estates">{{ e }}</ion-option>
        </ion-select>
      </ion-item>

      <!-- Municipalities -->
      <ion-item class="input">
        <ion-label>
          <ion-icon name="pin"></ion-icon>
        </ion-label>
        <ion-select formControlName="selectedMunicipality" 
                    (ionChange)="municipalityChanged()"
                    placeholder="Municipality"
                    cancelText="Cancel"
                    okText="Accept"
                    [disabled]="!municipalities || municipalities.length === 0">
          <ion-option value="{{ m }}" *ngFor="let m of municipalities">{{ m }}</ion-option>
        </ion-select>
      </ion-item>

      <!-- neighborhoods-->
      <ion-item class="input">
        <ion-label>
          <ion-icon name="pin"></ion-icon>
        </ion-label>
        <ion-select formControlName="selectedNeighborhood" 
                    (ionChange)="changeNeighborhood()"
                    placeholder="Neighborhood"
                    cancelText="Cancel"
                    okText="Accept"
                    [disabled]="!neighborhoods|| neighborhoods.length === 0">
          <ion-option value="{{ c }}" *ngFor="let c of neighborhoods">{{ c }}</ion-option>
        </ion-select>
      </ion-item>

      <!-- Street -->
      <ion-item class="input">
        <ion-input clearInput 
                   type="text" 
                   placeholder="Street" 
                   formControlName="street">
        </ion-input>
      </ion-item>

      <!-- External number -->
      <ion-item class="input">
        <ion-input type="tel" 
                   placeholder="House number" 
                   formControlName="externalNumber">
        </ion-input>
      </ion-item> 

      <ion-item class="input">
        <ion-input type="tel" 
                  placeholder="Department number"
                   formControlName="internalNumber">
        </ion-input>
      </ion-item> 
    </ion-list>
  </div>

  <ion-row class="form-footer">
    <button type="submit" ion-button block>
      Search address
    </button>
  </ion-row>
  
</form>
```

**Other information:**
This is happening since Ionic v2 and also in Ionic v3

**Ionic info:**:

This is what I get when I run Ionic info

```
    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.4.2

System:

    Node : v6.10.3
    OS   : Windows 10
    npm  : 3.10.10
```

**Comment by kensodemann** [comment]
Hello! Thank you for submitting this issue. This is an issue that we are aware of and are working on, but do not have a solution for at this time.

One work-around that you can try is positioning the input above where the keyboard would normally come up (if possible), which will prevent the scrolling logic from triggering. Does this work-around solve your issue until a fix is available?

**Comment by juanjoseadan** [comment]
Yeah, that worked for me, but looks a little weird.
Thank you for your help

**Comment by juanjoseadan** [comment]
Hi Ionic team. I'm JuanJoseRhoads, I lost my password and email to that account.
Yeah, that solution worked for me.

Do you have any solution for the "submit" issue?

**Comment by kensodemann** [comment]
Hello! For the submit issue, would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by johnroper100** [comment]
https://stackoverflow.com/questions/45197469/ionic-2-disable-scrolling-on-login-form-input-focus
