### ISSUE TITLE
Component doesn't generate Module

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic#12658]
[X ] **3.x**

[X ] feature request

**Current behavior:**
`ionic generate component SubscribeTopicComponent` CLI command doesn't generate the `Module` file.

**Expected behavior:**
We need a `Module` by default like `Page` component. But you can give `--no-module` for someone who doesn't like this feature.In other words, we like the same way of generation `Page` CLI commands. 

**Ionic info:**

> @ionic/cli-plugin-cordova       : 1.6.2
>     @ionic/cli-plugin-ionic-angular : 1.4.1
>     @ionic/cli-utils                : 1.7.0
>     ionic (Ionic CLI)               : 3.7.0
> 
> global packages:
> 
>     Cordova CLI : 7.0.1
> 
> local packages:
> 
>     @ionic/app-scripts : 2.1.3
>     Cordova Platforms  : android 6.2.3
>     Ionic Framework    : ionic-angular 3.6.0
> 
> System:
> 
>     Android SDK Tools : 25.2.5
>     Node              : v6.10.0
>     OS                : Windows 8.1
>     npm               : 3.10.10

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2632
