### ISSUE TITLE
Not able to close the info window directly on iOS 

### ISSUE THREAD

**Issue by ix-xerri** [ionic-team/ionic#12665]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am trying to implement google maps inside ionic. I am implementing a js script not using the cordova plugin. Everything work well but I and not able to close the info window directly on iOS. Able to normally close it in the browser.

**Expected behavior:**
Info window should close when clicking the close icon on iOS

**Steps to reproduce:**
I am showing a Google Maps on my ionic application based on Josh's tutorials. https://www.joshmorony.com/creating-an-advanced-google-maps-component-in-ionic-2/

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.2

System:

    Node       : v6.10.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    npm        : 5.3.0

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

We have a sample application that uses the Google Maps API. Can you fork this project and try to reproduce your issue there? https://github.com/ionic-team/ionic-conference-app

Also, have you tried using WKWebView? The standard UIWebView has some known issues on iOS, and the eventual plan is to replace UIWebView with WKWebView. Here is the repo for the WKWebView plugin: https://github.com/ionic-team/cordova-plugin-wkwebview-engine

Thanks for using Ionic!

**Comment by kensodemann** [comment]
@ix-xerri - did either of the above items resolve your issue? Please let me know. If not, could you please provide a sample application via GitHub that demonstrates the issue you are having.

I am going to close this issue in the meantime but would be happy to reopen it in the future.

**Comment by ix-xerri** [comment]
Hi @kensodemann, sorry for the delay but was working on some other features. I've gone though the page you sent and followed instructions. I could not understand in which part to paste the "Required Permissions" section in the config.xml but just ran the app on iOS and it shows that I'm loading WKWebView (with the console.log example in the tutorial).

However the Google Info window **does not** close.

**Comment by ix-xerri** [comment]
I've loaded the application you showed on and iOS device running iOS 11 and the Map does not load. I get the "Oops! Something went wrong" message. All I did was clone your application `ionic cordova platform add ios`.

**Comment by kensodemann** [comment]
We'll have to have a look at our sample app to see what is going on there.

For your issue, can you create a sample application that demonstrates the issue and post it to GitHub?

**Comment by ix-xerri** [comment]
The google map component is quite large but to go into more detail, I am using the javascript api and then building it with ionic on iOS. One important thing is that even info windows on Google Maps (not on my custom markers) do not close so it looks like there is another element in the way. I have disable double click zoom in mapOptions but still no luck.

**Comment by ix-xerri** [comment]
So I have been trying to see whats the issue. I have looked at [Paul Halliday's video](https://www.youtube.com/watch?v=0Ue6fNPOdB4) and loaded it on iOS. Now my application is much larger but nothing interacts with GMaps itself. Found no solution so I am lost.
