### ISSUE TITLE
deep-link url change when pushing page on top of tabs

### ISSUE THREAD

**Issue by jorrit-wehelp** [ionic-team/ionic#12666]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Have a 'tabs' page. Inside one of the page, I try to push a page 'on top of' the tabs page (so it's outside the tabs/doesn't show tabbar and 'back' goes back to the tabs).
This works, but the URL isn't changed like it's normally done when there are just two pages in the root navCtrl stack.

**Expected behavior:**
I would expect the URL to change when something is pushed on the root navCtrl.

**Steps to reproduce:**
Example: https://stackblitz.com/edit/ionic-j8gkde
(stackblitz crashes with ionic 3.6.0, but the 3.5 version shows the same issue)

Click on the 'nav on top of tabs' button.
It goes to the 'other' page.

**Related code:**
https://github.com/ionic-team/ionic/blob/v3.6.0/src/navigation/nav-controller-base.ts#L785
There is this.hasChildren() condition which prevents it going into the deep-link navChange...
I'm not sure what it's trying to prevent here...

**Comment by astec** [comment]
@jorrit-wehelp I used same approach for hiding tabs but switched to using [`Tab:tabsHideOnSubPages`](http://ionicframework.com/docs/api/components/tabs/Tab/#input-properties) property. In this case I push on current nav controller and URL changes as expected.

Still it looks like a bug and URL should change when pushed on root navigation.
