### ISSUE TITLE
Unable to install a plugin without downgrading npm to version 4.6.1 ( had 5.3.0 )

### ISSUE THREAD

**Issue by vhb56** [ionic-team/ionic#12662]
**Ionic version:**  (check one with "x")
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report

**Current behavior:**
Unable to install a plugin without downgrading npm to version 4.6.1 ( had 5.3.0 )

**Expected behavior:**
Installing it without downgrading npm. 

**Steps to reproduce:**
Try to install this plugin with my configuration & node 5.3.0:

https://ionicframework.com/docs/native/local-notifications/

this part:
`ionic cordova plugin add de.appplant.cordova.plugin.local-notification`

**Other information:**
Without downgrading npm from 5.3.0 to 4.6.1 i couldn't install this plugin.

i had looong error, but first one was something about 'node_modules/cordova-plugin-app-event'
so googling i've found this issue:

https://github.com/ionic-team/ionic/issues/12061

The error wasn't just the same(it was something about writing problems), but  'node_modules/cordova-plugin-app-event' was in my error too, so dowgrade of npm worked to me too.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.1
    Node              : v6.11.0
    OS                : Windows 7
    npm               : 4.6.1 (was 5.3.0)
```

**Comment by vhb56** [comment]
Just to do things properly i've uninstalled plugin, upgraded npm back to 5.3.0 & tried to install it again, just to get an error message:

`
> cordova plugin add de.appplant.cordova.plugin.local-notification --save
? Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova plugin add de.appplant.cordova.plugin.local-notification --save (exit
        code 1):

        Installing "de.appplant.cordova.plugin.local-notification" for android
        Plugin dependency "cordova-plugin-device@1.1.4" already fetched, using that version.
        Dependent plugin "cordova-plugin-device" already installed on android.
        Failed to install 'de.appplant.cordova.plugin.local-notification': CordovaError: Failed to fetch plugin
        cordova-plugin-app-event via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 4294963228 Error output:
        npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
        npm WARN ionic-angular@3.6.0 requires a peer of rxjs@5.4.0 but none was installed.

        npm ERR! path D:\ion\node_modules\cordova-plugin-app-event
        npm ERR! code EISDIR
        npm ERR! errno -4068
        npm ERR! syscall symlink
        npm ERR! EISDIR: illegal operation on a directory, symlink
        'D:\ion\node_modules\cordova-plugin-app-event' ->
        'D:\ion\node_modules\cordova-plugin-app-event'

        npm ERR! A complete log of this run can be found in:
        npm ERR! C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2017-08-14T20_59_53_204Z-debug.log
        at C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:205:33
        at _rejected
        (C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:864:24)
        at C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:890:30
        at Promise.when
        (C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:1142:31)
        at Promise.promise.promiseDispatch
        (C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:808:41)
        at C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:624:44
        at runSingle
        (C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:137:13)
        at flush
        (C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:125:13)
        at _combinedTickCallback (internal/process/next_tick.js:73:7)
        at process._tickCallback (internal/process/next_tick.js:104:9)
        Error: Failed to fetch plugin cordova-plugin-app-event via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 4294963228 Error output:
        npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
        npm WARN ionic-angular@3.6.0 requires a peer of rxjs@5.4.0 but none was installed.

        npm ERR! path D:\ion\node_modules\cordova-plugin-app-event
        npm ERR! code EISDIR
        npm ERR! errno -4068
        npm ERR! syscall symlink
        npm ERR! EISDIR: illegal operation on a directory, symlink
        'D:\ion\node_modules\cordova-plugin-app-event' ->
        'D:\ion\node_modules\cordova-plugin-app-event'

        npm ERR! A complete log of this run can be found in:
        npm ERR! C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2017-08-14T20_59_53_204Z-debug.log
`

I've tried to install it from visual studio code terminal, from win7 cmd, from win7 cmd with admin rights.
No luck, until npm downgrade.

This error got from native win7 cmd run with admin rights.

**Comment by vhb56** [comment]
It seems in order to work this plugin installs "cordova-plugin-app-event" and for some reason installation goes wrong with npm 5.3.0

**Comment by AmitMY** [comment]
Please open an issue with the cordova plugin's repo, as ionic does not manage the cordova plugins

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am closing this issue since it has been logged with Cordova.

Thank you for using Ionic
