### ISSUE TITLE
Searchbar can be scrolled while keyboard open

### ISSUE THREAD

**Issue by 0x62** [ionic-team/ionic#12667]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

1. Open app which implements `ion-searchbar` or any input field
2. Focus input field
3. Click and drag header
4. Header (and whole body content) scrolls
4b. This issue can also be seen when focusing on an input field within `ion-content`, and attempting to scroll the header

**Expected behavior:**
Header/content should not scroll

**Steps to reproduce:**
This can be reproduced on any device (tested on iOS/Android only) which implements the `ion-searchbar`.

**Other information:**
Demo: https://youtu.be/c4XCQTkdTCY

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! And thank you for including the YouTube demo. That was very helpful.

I was able to duplicate this issue in a simple project using the (currently) standard UIWebView. I was able to fix the issue in that project by using the WKWebView. Please follow the instructions in the following repo and let us know if that fixes your issue: https://github.com/ionic-team/cordova-plugin-wkwebview-engine

Thank you for using Ionic!
