### ISSUE TITLE
the style of app 样式丢失

### ISSUE THREAD

**Issue by 395779222** [ionic-team/ionic#12663]
1.ionic serve then browser show 
![image](https://user-images.githubusercontent.com/8910144/29297831-34c67cb4-8196-11e7-8dc9-2aa8cf37b842.png)
2.ionic cordova build ios --prod --release  then browser show 
![image](https://user-images.githubusercontent.com/8910144/29297965-13726ff4-8197-11e7-9626-7479bdd044e3.png)

**Comment by 395779222** [comment]
Running app-scripts build: --build --prod --iscordovaserve --nobrowser

[09:10:17]  build prod started ...
[09:10:17]  clean started ...
[09:10:17]  clean finished in 3 ms
[09:10:17]  copy started ...
[09:10:17]  ngc started ...
[09:10:28]  ngc finished in 10.80 s
[09:10:28]  preprocess started ...
[09:10:28]  deeplinks started ...
[09:10:30]  deeplinks finished in 1.72 s
[09:10:30]  optimization started ...
[09:10:30]  copy finished in 12.73 s
[09:10:46]  optimization finished in 15.87 s
[09:10:46]  preprocess finished in 17.58 s
[09:10:46]  webpack started ...
[09:12:29]  webpack finished in 103.24 s
[09:12:29]  sass started ...
[09:12:29]  webpack started ...
[09:12:29]  uglifyjs started ...
[09:13:56]  uglifyjs finished in 86.62 s
[09:14:13]  webpack finished in 103.65 s
[09:14:13]  sass finished in 103.79 s
[09:14:13]  cleancss started ...
[09:14:13]  cleancss finished in 550 ms
[09:14:13]  postprocess started ...
[09:14:13]  postprocess finished in 6 ms
[09:14:13]  lint started ...
[09:14:13]  build prod finished in 236.02 s

**Comment by 395779222** [comment]
![image](https://user-images.githubusercontent.com/8910144/29299200-93be94e6-819f-11e7-87f9-1789b47cd229.png)

**Comment by AmitMY** [comment]
Can you please check the network tab to see if it does load a stylesheet, but an empty one, or just can't load the file with like 404 or something?

**Comment by 395779222** [comment]
![image](https://user-images.githubusercontent.com/8910144/29308220-8b952ca2-81d7-11e7-9fd4-5418ffb78d2b.png)
no 404 error

**Comment by kensodemann** [comment]
Hello! Hello, thank you for opening an issue with us!

What happens if you click on the `build/main.css` link that you have circled in the screenshot above? Also, if you could click where it says "network", reload your app, and show us the part of the output where `main.css` is loaded, that would be very helpful.

Thank you for using Ionic

**Comment by 395779222** [comment]
![image](https://user-images.githubusercontent.com/8910144/29313225-73a501d0-81eb-11e7-829e-1f481a9146f1.png)
![image](https://user-images.githubusercontent.com/8910144/29313246-90bdfac4-81eb-11e7-97cd-4667b7916ba2.png)

**Comment by 395779222** [comment]
1.to solve the problem, i start a new project then building with prod is no problem.

2.but the problem  reappeared  when  i delete node_modules from app, next i run npm install , then build with prod 

my english is poor, thanks for your help.

**Comment by kensodemann** [comment]
Can you provide the `ionic info` information? (run "ionic info" from the terminal/cmd prompt from the root directory of the project)

**Comment by kensodemann** [comment]
Also, can you please provide the contents of your `package.json`?

**Comment by 395779222** [comment]
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.7.0
    ionic (Ionic CLI) : 3.7.0

System:

    Node       : v8.1.4
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    npm        : 5.3.0

package.json:
{
    "name": "tonglunApp",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/app-minimize": "^4.1.0",
        "@ionic-native/app-version": "^4.1.0",
        "@ionic-native/camera": "^4.1.0",
        "@ionic-native/core": "3.12.1",
        "@ionic-native/file": "^4.1.0",
        "@ionic-native/image-picker": "^4.1.0",
        "@ionic-native/in-app-browser": "^4.1.0",
        "@ionic-native/network": "^4.1.0",
        "@ionic-native/splash-screen": "3.12.1",
        "@ionic-native/status-bar": "3.12.1",
        "@ionic-native/toast": "^4.1.0",
        "@ionic-native/transfer": "^3.14.0",
        "@ionic/storage": "2.0.1",
        "chart.js": "^2.6.0",
        "com.synconset.imagepicker": "https://github.com/Telerik-Verified-Plugins/ImagePicker.git",
        "cordova-android": "^6.2.3",
        "cordova-ios": "^4.4.0",
        "cordova-plugin-app-version": "^0.1.9",
        "cordova-plugin-appminimize": "^1.0.0",
        "cordova-plugin-camera": "^2.4.1",
        "cordova-plugin-compat": "^1.1.0",
        "cordova-plugin-console": "^1.0.5",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-file": "^4.3.3",
        "cordova-plugin-file-transfer": "^1.6.3",
        "cordova-plugin-inappbrowser": "^1.7.1",
        "cordova-plugin-network-information": "^1.3.3",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.2",
        "cordova-plugin-telerik-imagepicker": "git+https://github.com/Telerik-Verified-Plugins/ImagePicker.git",
        "cordova-plugin-whitelist": "^1.3.1",
        "cordova-plugin-x-toast": "^2.6.0",
        "ionic-angular": "3.5.3",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionic2-city-picker": "^0.0.11",
        "ionicons": "3.0.0",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "videogular2": "^5.4.11",
        "zone.js": "0.8.12"
    },
    "devDependencies": {
        "@ionic/app-scripts": "2.0.2",
        "@ionic/cli-plugin-cordova": "1.6.2",
        "@ionic/cli-plugin-ionic-angular": "1.4.1",
        "@types/core-js": "^0.9.42",
        "ionic": "3.7.0",
        "typescript": "2.3.4"
    },
    "description": "An Ionic project",
    "cordova": {
        "plugins": {
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-app-version": {},
            "cordova-plugin-camera": {
                "CAMERA_USAGE_DESCRIPTION": " ",
                "PHOTOLIBRARY_USAGE_DESCRIPTION": " "
            },
            "cordova-plugin-file": {},
            "com.synconset.imagepicker": {
                "PHOTO_LIBRARY_USAGE_DESCRIPTION": "coffice"
            },
            "cordova-plugin-inappbrowser": {},
            "cordova-plugin-network-information": {},
            "cordova-plugin-x-toast": {},
            "cordova-plugin-file-transfer": {},
            "cordova-plugin-appminimize": {}
        },
        "platforms": [
            "android",
            "ios"
        ]
    }
}

**Comment by kensodemann** [comment]
Hello! Thank you for supplying that information for us!

I have tried your exact configuration with a sample project and have not seen any issues, including when removing the `node_modules/` and re-running npm install.

Questions:
1. have you looked in the console while the application is running to see if any errors are being raised?
2. when your SASS files are processed during the build, are there any warnings or errors raised?
3. do you have a public repo for your project on a service like GitHub where we can clone your project and have a look?
4. if not, could you create a small sample application that duplicates the issue and post that to GitHub?

Thank you for using Ionic

**Comment by gineign** [comment]
It's not the problem of ionic. It's because you are in China and using cnpm (taobao npm)
use the original npm to install
then you don't have the problem.
I had the same issue  but now it's solved reinstalling with original npm

**Comment by kensodemann** [comment]
@395779222 - please let me know if the suggestion that @gineign provided fixes your issue.

**Comment by 395779222** [comment]
thank you， just close this issue.
