### ISSUE TITLE
style error

### ISSUE THREAD

**Issue by 395779222** [ionic-team/ionic#12660]
the style of app that i build with ionic cordova build  ios --prod is not same to the style of app that i build with ionic cordova build  ios

**Comment by AmitMY** [comment]
Thanks for opening an issue.
Can you please fill out the template for new issues?
Also, please attach screenshots if possible, so we will know what you are talking about

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
