### ISSUE TITLE
No support for yarn package manager (instead of npm)?

### ISSUE THREAD

**Issue by IncognitoCore** [ionic-team/ionic#12668]
**Ionic version:**  (check one with "x")
[  ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[  ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[x] feature request
[  ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When running 'ionic start my-app' it errors on not finding npm and quitting.
```
    [INFO] Installing dependencies may take several minutes!
    ✖ npm install - failed!
    [ERROR] Command not found: npm
```

**Expected behavior:**
Using yarn when npm isn't available and yarn is. OR not crashing but skipping installing packages when no npm installation is detected, and allowing the user to manually install packages via his/her choice of package manager.

**Other information:**
https://yarnpkg.com/en/

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
cli packages: (/Users/Kevin/.config/yarn/global/node_modules)

    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v7.8.0
    npm  : not installed
    OS   : macOS Sierra

```

**Comment by AmitMY** [comment]
Definitely understandable. 
@jgw96 Can you please move this to the `ionic-cli` repo?

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2639
