### ISSUE TITLE
Ionic 3 Slides not Visible in iOS 10.3

### ISSUE THREAD

**Issue by rachelpopa** [ionic-team/ionic#12672]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ion-slide within ion-slides works as expected in iOS 9.3, but is flickering when on auto-play and invisible when not auto-playing in iOS10.3

**Expected behavior:**
Expecting to see a working slideshow.  

**Steps to reproduce:**
Implement <slides> as a component, include it in a page, and run it on iOS 10.3 (simulator or device)

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/rpopa/Programming/SafetyDays2017/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.3

System:

    Node       : v7.1.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.6 
    npm        : 3.10.9 
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I attempted to duplicate your issue using our [sample conference application](https://github.com/ionic-team/ionic-conference-app) but was unable to duplicate it. The tutorial slides on the conference app ran smoothly on iOS 10.3 on both the emulator and on an iPhone.

Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

One difference I see is that I used `ionic-angular 3.6.0` and you are using `ionic-angular 3.5.3`. You could also try upgrading to the latest `ionic-angular` and see if that has any effect.

Thanks for using Ionic!

**Comment by rachelpopa** [comment]
It seemed to be caused by the fact that I had my ion-slides inside an ion-grid>ion-row.  Moving it outside the grid fixed it.  When it is in the grid it's invisible on iOS 10.3, but still there as I can click on the blank space and my click events for the slideshow are triggering as expected.

**Comment by kensodemann** [comment]
Excellent! I was just about to ask for some sample code as I just tried using it in a grid this morning without issue... :)

Glad to hear it is working for you. I will close this now.
