### ISSUE TITLE
Cannot use async await in a button handler with AlertController

### ISSUE THREAD

**Issue by dhasilva** [ionic-team/ionic#12675]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using an `Alert` with `AlertController`, the `handler` function of a button does not accept async functions because of a type definition.

**Expected behavior:**
Being able to use async functions in a button `handler` function.

**Steps to reproduce:**
Create an `Alert` with a button with a handler that is marked as an `async` function.
(The plunker demo does not seem to be working at all)

**Related code:**

```
editEmail() {
        let prompt = this.alertCtrl.create({
            title: 'Email',
            inputs: [
                {
                    name: 'email',
                    placeholder: 'Your e-mail address'
                },
            ],
            buttons: [
                { text: 'Cancel' },
                {
                    text: 'Save',
                    handler: async function(data: any): Promise<void> {
                       await sendToServer(data);
                    }
                }
            ]
        });
        prompt.present();
    }
```

**Other information:**

In `ionic-angular/components/alert/alert-options.d.ts`, line 28:
```
handler?: (value: any) => boolean | void;
```
Adding `| Promise<void>` seems to solve the problem.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-utils  : 1.6.0 
    ionic (Ionic CLI) : 3.6.0 

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Android SDK Tools : 26.0.2
    Node              : v7.10.1
    OS                : Linux 4.4
    npm               : 4.2.0 
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

[The code that handles the button click](https://github.com/ionic-team/ionic/blob/26b09f1d4907b1c90978d55b21743563fd189caa/src/components/alert/alert-component.ts#L233-L255) events does not handle a `Promise <void>`.  Specifically, line 246 will run the handler which will return a Promise object, which is truthy. Thus `shouldDismiss` will remain true and the alert will dismiss immediately rather than waiting for `sendToServer(data)` to complete, which appears to be what you want.

If you want to close the alert only after `sendToServer(data)` completes, then you need to:

1. return false from the handler
2. dismiss the alert manually from the handler

The code for that looks something like this:

```
handler: () => {
  sendToServer(data).then(() => prompt.dismiss());
  return false;
}
```

Thank you for using Ionic

**Comment by kensodemann** [comment]
It occurred to me after I wrote the above reply that dismissing the alert asynchronously like this seems like very bad UX to me. If `sendToServer(data)` takes any significant amount of time, then there will be a delay between the user clicking the button on the alert and the alert closing without any indication that anything is happening, which is not a good idea. If you have a use case where you do want to wait until `sendToServer(data)` finishes before closing the alert, then you should also add some sort of indicator such as a [loading indicator](http://ionicframework.com/docs/components/#loading)

I would like to better understand what your use case for using async/await in the handler is.

**Comment by dhasilva** [comment]
Thank you for the quick response.

Yes, I'm using the loading indicator. Right now I have a service that centralizes access to a loader and I always show and dismiss the indicator manually.
An administrator can change an user's email address by clicking in some edit button, which pops up the `Alert`, so the handler sends the new email for the backend server that validates the data and saves it to the database. If this operation is successful, the app updates the user's email and dismisses the loading indicator.

```
handler: function(data: any): void {
    page.notification.loader.present();
    let _id = page.user._id;
    page.backend.post(`/user/${_id}/email`, data)
    .then(function(data) {
        page.user.contact.email = data;
        page.dataService.setUser(page.user);
        page.notification.loader.dismiss();
    })
    .catch(function(error) {
        console.log(error);
        page.notification.loader.dismiss();
    });
}
```
Where `page` is set to `this` in the constructor, because `this` in an async function has a different context.

This works as initially intended. I just wanted to get rid of the `then` function since I'm using `async await` everywhere instead of dealing with promises directly, for code style reasons, and so far this is the only place where `async await` does not work.

After reading your explanation, though, I understand why it does not work, I simply did not notice that the alert itself closes depending on the return value, I thought it always closed immediately.

**Comment by dhasilva** [comment]
Using another `Alert`, now a confirmation alert, I actually can use `async await`, but only if all buttons have handlers(???).

This works:
```ts
async deleteEmail() {
    let confirm = this.alertCtrl.create({
        title: 'Confirmation',
        message: 'Do you really want to delete the email address?',
        buttons: [
            {
                text: 'Cancel',
                handler: () => {}
            },
            {
                text: 'Delete',
                handler: async function() {
                    page.notification.loader.present();
                    let _id = page.user._id;
                    await page.backend.delete(`/user/${_id}/email`);
                    page.user.contact.email = null;
                    page.dataService.setUser(page.user);
                    page.notification.loader.dismiss();
                }
            }
        ]
    });
    await confirm.present();
}
```
This does **not** work. Notice the lack of a hander in the first button:
```ts
async deleteEmail() {
    let confirm = this.alertCtrl.create({
        title: 'Confirmation',
        message: 'Do you really want to delete the email address?',
        buttons: [
            {
                text: 'Cancel'
            },
            {
                text: 'Delete',
                handler: async function() {
                    page.notification.loader.present();
                    let _id = page.user._id;
                    await page.backend.delete(`/user/${_id}/email`);
                    page.user.contact.email = null;
                    page.dataService.setUser(page.user);
                    page.notification.loader.dismiss();
                }
            }
        ]
    });
    await confirm.present();
}
```

I tried adding a handler to the 'Cancel' button in the example of the first post, but it still does not work there.

Now I'm really confused. Why does the first `deleteEmail` implementation transpile at all? Is it a TypeScript issue, an `Alert` issue or an ionic type definition issue?

**Comment by kensodemann** [comment]
I am going to have to guess that it is a TypeScript issue. It should not transpile without error so far as I can tell reading it.

Here is the type for a button on an Alert:

```ts
export interface AlertButton {
  text?: string;
  role?: string;
  cssClass?: string;
  handler?: (value: any) => boolean|void;
}
```
