### ISSUE TITLE
Upgrading CLI versions causing problems w/ polyfills

### ISSUE THREAD

**Issue by jordanpurinton** [ionic-team/ionic#12670]
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

After upgrading CLI versions I'm getting this error that I haven't encountered before.
I've tried multiple times to reinstall the Ionic CLI and ran npm install/update and haven't had any success in resolving this issue.

![asdf](https://user-images.githubusercontent.com/12102971/29324422-3457a928-81a1-11e7-946b-abf1dd18e2eb.PNG)

```
    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 1.3.0
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.4.2

System:

    Android SDK Tools : 25.2.5
    Node              : v6.10.0
    npm               : 3.10.10
    OS                : Windows 10


```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

Also, I am moving this issue to the ionic-cli repo since this appears to be an issue with the CLI.

Thanks for using Ionic!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2640
