### ISSUE TITLE
Ion input components disappear from DOM when in 2 levels of Angular Structural Directives

### ISSUE THREAD

**Issue by dudeofawesome** [ionic-team/ionic#12674]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I’m having an issue with using Ionic inputs inside of Angular structural directives. 

It seems that when some Ionic Components are placed inside 2 levels of structural directives (`ngIf`, `ngSwitch`, `ngFor`, etc), they disappear from the DOM tree entirely.

**Expected behavior:**
I would expect all Ion Components to not disappear inside 2 levels of structural directives.

**Steps to reproduce:**
I've put together a demo repo here: https://github.com/dudeofawesome/ionic-bug-inputs
And a Plunkr here: http://plnkr.co/edit/TRU28JTvpbDUEB7zkSaQ?p=preview

**Related code:**
```HTML
<ion-item *ngFor="let input of slide.inputs" [ngSwitch]="input.type">
  <ng-template ngSwitchCase="select">
    <ion-label floating>{{input.label}}</ion-label>
    <ion-select>
      <ion-option *ngFor="let option of input.options" [value]="option.value">{{option.label}}</ion-option>
    </ion-select>
  </ng-template>

  <ng-template ngSwitchCase="range">
    <ion-label>{{input.label}}</ion-label>
    <ion-range></ion-range>
  </ng-template>

  <ng-template *ngSwitchDefault>
    <ion-label floating>{{input.label}}</ion-label>
    <ion-input [type]="input.type"></ion-input>
  </ng-template>
</ion-item>
```

**Other information:**
Components that I’ve tested:
- Doesn’t work: 
    - `ion-input`
    - `ion-label`
    - `ion-select`
    - `ion-range`
- Works
    - `ion-icon`
    - HTML `input`s

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
cli packages: (~/Github/ionic-bug-inputs/node_modules)

    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.11.1
    npm  : 3.10.10
    OS   : macOS Sierra
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. If you change your markup to something similar to this: ```HTML
<div *ngFor="let input of slide.inputs" [ngSwitch]="input.type">
  <ng-template ngSwitchCase="select">
   <ion-item>
    <ion-label floating>{{input.label}}</ion-label>
    <ion-select>
      <ion-option *ngFor="let option of input.options" [value]="option.value">{{option.label}}</ion-option>
    </ion-select>
    </ion-item>
  </ng-template>

  <ng-template ngSwitchCase="range">
     <ion-item>
    <ion-label>{{input.label}}</ion-label>
    <ion-range></ion-range>
    </ion-item>
  </ng-template>

  <ng-template *ngSwitchDefault>
    <ion-item>
    <ion-label floating>{{input.label}}</ion-label>
    <ion-input [type]="input.type"></ion-input>
    </ion-item>
  </ng-template>
</div>
```

**Comment by dudeofawesome** [comment]
```html
<ng-container *ngFor="let input of slide.inputs" [ngSwitch]="input.type">
  <ion-item *ngSwitchCase="'select'">
    <ion-label floating>{{input.label}}</ion-label>
    <ion-select [formControlName]="input.name">
      <ion-option *ngFor="let option of input.options" [value]="option.value">{{option.label}}</ion-option>
    </ion-select>
  </ion-item>

  <ion-item *ngSwitchCase="'range'">
    <ion-label>{{input.label}}</ion-label>
    <ion-range [formControlName]="input.name"></ion-range>
  </ion-item>

  <ion-item *ngSwitchDefault>
    <ion-label floating>{{input.label}}</ion-label>
    <ion-input [type]="input.type" [formControlName]="input.name"></ion-input>
  </ion-item>
</ng-container>
```

This works!

It looks like ion-input has to be a direct child of ion-item?

**Comment by dudeofawesome** [comment]
![image](https://user-images.githubusercontent.com/1683595/29380268-03cfbfe6-827a-11e7-9366-e4864a8a7ccf.png)
I'm noticing that the inputs don't have the normal underline beneath them unless they're active. It looks like it's caused by some styling on `ion-card`.

```css
.card-md .item-md.item-block .item-inner {
    border: 0;
}
```

Is this intentional?

**Comment by jgw96** [comment]
@dudeofawesome Awesome, glad that worked! So yeah at the moment `ion-item` should be a direct parent of input components. Also, on that second issue you found, would you mind opening a separate issue please? Since this issue has been solved I am going to close this for now. Thanks!
