### ISSUE TITLE
Changing page with a ion-toggle switch does not work properly

### ISSUE THREAD

**Issue by Julieng50** [ionic-team/ionic#12678]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When a ion-toggle must show a page, the new page is bugged when the ion-toggle has been switched, but it works if we only "click" on it.
Things like [class.activated], or conditional angular in html, does not work.

**Expected behavior:**
ion-toggle must show the new page properly with all the functions working ([class.***] ...etc), by clicking or by switching.

**Steps to reproduce:**
Use this codepen : https://codepen.io/anon/pen/GvOBME
First, click on the ion-toggle, then go back.
Second, switch the ion-toggle (from left-to-right or right-to-left), you cannot go back !

Thanks.

**Comment by Julieng50** [comment]
Well... upgrading to ionic-angular 3.6.0 (and other packages) fixed that problem.
:)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! I am glad to hear that ionic-angular 3.6.0 fixed the issue for you.

Thank you for using Ionic
