### ISSUE TITLE
IonicPage segment: Allow multiple URLs to a Page

### ISSUE THREAD

**Issue by dbgupta** [ionic-team/ionic#12688]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
IonicPage is not working for multiple urls after a space (please let me know if following feature exist in any other form) , for example:
```
@IonicPage({
   segment: ':city/offers, offers',
})
@Component({
  selector: 'page-list',
  templateUrl: 'list.html'
})
export class ListPage {
```
for navigation if i do

```
 if(!this.userCity){
      this.navCtrl.push('ListPage');
    } else {
      this.navCtrl.push('ListPage', { city: this.userCity.toLowerCase()});
    }
```
I am getting redirection in web browser as below
if usercity is undefined
```
http://localhost:8100/#/nav/n4/:city/offers, offers
```
if usercity is defined
```
http://localhost:8100/#/nav/n4/delhi/offers, offers
```
**Expected behavior:**
if usercity is undefined
```
http://localhost:8100/#/nav/n4/offers
```
if usercity is defined
```
http://localhost:8100/#/nav/n4/delhi/offers
```

**Steps to reproduce:**
as explained above

**Related code:**

```
@IonicPage({
   segment: ':city/offers, offers',
})
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
@ionic/cli-plugin-cordova       : 1.6.1
@ionic/cli-plugin-ionic-angular : 1.4.1
@ionic/cli-utils                : 1.6.0
 ionic (Ionic CLI)               : 3.6.0
global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.0.0
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.5.0

System:

    Node : v6.10.1
    OS   : Windows 7
    npm  : 3.10.10
```

**Comment by danbucholtz** [comment]
We are in the process of redoing routing with Ionic V4 so we'll keep this in mind. It seems to me like you should navigate to two separate components when the data in different.

Thanks,
Dan

**Comment by dbgupta** [comment]
Thanks Dan! 

just curious, by when will ionic 4 be rolling out.

Regards
Deep

**Comment by nicothed** [comment]
I have the same request.I'm working on a system with a similar url convention as Foursquare, i.e. 
https://foursquare.com/v/floriana/3fd66200f964a520b3f11ee3
can also be called as
https://foursquare.com/v/3fd66200f964a520b3f11ee3 (without the venue name in the url)

They redirect, but ideally it shouldn't (for me).

So, when is V4 coming out!? :)

**Comment by HudsonAfonso** [comment]
+1
when is V4 coming out????

**Comment by dalezak** [comment]
@HudsonAfonso @dbgupta @nicothed a temporarily workaround until V4 is released, is to add another page and inherit from the previous page to override the `segment` path.

```
@IonicPage({
  name: 'PersonDetailsPage',
  segment: 'people/:person_id',
  defaultHistory: ['PersonListPage']
})
@Component({
  selector: 'page-person-details',
  templateUrl: 'person-details.html'
})
export class PersonDetailsPage 
```

```
@IonicPage({
  name: 'PersonProfilePage',
  segment: 'profile'
})
@Component({
  selector: 'page-person-details',
  templateUrl: '../../pages/person-details/person-details.html'
})
export class PersonProfilePage extends PersonDetailsPage
```

This way you can override the `segment` yet reuse all the existing logic and layout from the other page.
