### ISSUE TITLE
Unable to close a modal containing tabs and Promise

### ISSUE THREAD

**Issue by SquallX** [ionic-team/ionic#12681]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Unable to close a modal containing tabs and Promise.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
// competition.ts => load the modal
openTeam(teamId) {
    let modal = this.modalCtrl.create(TeamTabsPage, {"id": teamId});
    modal.present();
  }

// TeamTabsPage
export class TeamTabsPage {

  team: any;

  teamTabHome = TeamPage;
  teamTabPlayers = TeamPlayersPage;
  teamTabArticles = TeamArticlesPage;
  teamTabCalendar = TeamCalendarPage;

  constructor(public navController: NavController, public navParams: NavParams, public teamProvider: TeamProvider, public viewCtrl: ViewController) {}

  ionViewCanEnter(): Promise <any> {
    return new Promise((resolve, reject) => {
      this.teamProvider.get(this.navParams.get('id'), {data: 'infos'}).subscribe(response => {
        this.team = response.team;
        resolve();
      }, error => {
        reject();
        console.log(error);
      })
    });
  }

  /**
   * Petit hack pour placer le logo de la compétition dans les tabs
   */
  ionViewDidEnter() {
    setTimeout(() => {
      let element = document.querySelectorAll('.ion-ios-team-custom');
      let parent = element[0].parentNode;
      element[0].parentNode.removeChild(element[0]);

      let img = document.createElement("img");
      img.setAttribute("class", "tab-icon-custom tab-button-icon icon icon-ios");
      img.setAttribute("src", this.team.logo);
      parent.insertBefore(img, parent.firstChild);
    }, 500)
  }

}

// TeamPage => dismiss action
closeTeam() {
    this.viewCtrl.dismiss();
  }
```

**Other information:**

> ERROR Error: Uncaught (in promise): navigation stack needs at least one root page
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.es5.js:4140)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at HTMLButtonElement.invoke (polyfills.js:3)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
li packages: (/Users/alexandre/Sites/app-mobiles/leRugbynistere/node_modules)

    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.3

System:

    Android SDK Tools : 25.2.4
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.13 
    Node              : v7.5.0
    npm               : 4.1.2 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? The sample code you provided is great, but out of context is not sufficient to duplicate the issue.

Thanks for using Ionic!

**Comment by SquallX** [comment]
Hello !

Of course, I've created a tiny repo with the code. You can found it here : https://github.com/SquallX/ionic-demo

On index, when you click on "Article Title", you open a modal with the article content, and when you try to close the modal, ou get this error : 

`core.es5.js:1084 ERROR Error: Uncaught (in promise): navigation stack needs at least one root page
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.es5.js:4140)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at HTMLButtonElement.invoke (polyfills.js:3)`

<img width="635" alt="capture d ecran 2017-08-17 a 10 55 03" src="https://user-images.githubusercontent.com/818564/29404233-ca391482-833a-11e7-9f2a-53f5b97d3c29.png">
<img width="665" alt="capture d ecran 2017-08-17 a 10 55 09" src="https://user-images.githubusercontent.com/818564/29404232-ca36b7e6-833a-11e7-9b56-0e1bab7834c7.png">
<img width="629" alt="capture d ecran 2017-08-17 a 10 55 15" src="https://user-images.githubusercontent.com/818564/29404231-ca35d6fa-833a-11e7-96d4-9e133c66db7a.png">

**Comment by kensodemann** [comment]
Excellent! Thank you. I will have a look at that.

**Comment by kensodemann** [comment]
Right now, you have the code that closes the modal existing in the child views that are shown by each tab. You can get this to work properly if you can refactor your code such that that the close that closes the modal is defined in the class for the modal itself.

That is, take this code:

```ts
  closeArticle() {
    this.viewCtrl.dismiss();
  }
```

and move it from `tab-one.ts` into `modal-tabs.ts`

**Comment by SquallX** [comment]
Hi,

Thanks for your answer, when I do your manipulation, I obtain this error : 

`TabOnePage.html:11 ERROR TypeError: co.closeArticle is not a function
    at Object.eval [as handleEvent] (TabOnePage.html:11)
    at handleEvent (core.es5.js:11914)
    at callWithDebugContext (core.es5.js:13206)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:12794)
    at dispatchEvent (core.es5.js:8814)
    at core.es5.js:9406
    at HTMLButtonElement.<anonymous> (platform-browser.es5.js:2687)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.es5.js:4140)
    at t.invokeTask (polyfills.js:3)`

<img width="250" alt="capture d ecran 2017-08-17 a 20 48 34" src="https://user-images.githubusercontent.com/818564/29428460-96f1b284-838d-11e7-80b1-7925707b0a80.png">

**Comment by kensodemann** [comment]
OK, thx. I'll have a look.

**Comment by kensodemann** [comment]
@SquallX - right now, you have the code that does close in `modal-tabs.ts` (which is the correct place for it), but you have the markup that is bound to it still in the `tab-one` view.

```html
<ion-header>

  <ion-navbar>
    <ion-buttons start>
      <button ion-button icon-only (click)="closeArticle()">
        <ion-icon name="close"></ion-icon>
      </button>
    </ion-buttons>
    <ion-title>{{ article.title }}</ion-title>
  </ion-navbar>

</ion-header>
```

You either need to refactor your design such that the header definition can be put in the `modal-tabs` view, or if you need to have the header defined in the child pages for any particular reason then you need to use some sort of pub-sub pattern where `tab-one`, `tab-two`, etc. emit do whatever handling they need to do and emit an event telling `modal-tabs` to dismiss the modal.

I suggest moving the header if possible since that is much more straight forward and only going with the pub-sub pattern if you absolutely need to.

**Comment by SquallX** [comment]
Hi,

Thank you very much ! I understand better now.

It works perfectly =)
Thank you for your explanations.

**Comment by kensodemann** [comment]
You're welcome!! Glad to hear it is all working for you now.
