### ISSUE TITLE
when landing on a tab, tab's ionViewDidLoad called twice

### ISSUE THREAD

**Issue by oren-gershoni** [ionic-team/ionic#12684]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
when landing directly on a tab page its's ionViewDidLoad is called twice (as apposed to navigation to the tab from within the app, where it works as expected)

**Expected behavior:**
it should only be called once

**Steps to reproduce:**
i took a fresh copy of ionic-confrence-app , went into speaker-list.ts and added 
console.log('hello world') to ionViewDidLoad.

if you refresh (http://localhost:8101/#/tabs-page/speakers/speakerList) you see it printed twice,
navigating from within the app to the tab will only print once (as intended).

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Unfortunately, with the latest master branch of the conference app, I cannot reproduce this issue. Are you sure you have the latest?

**Comment by oren-gershoni** [comment]
yes, i have it updated to commit 36db2f7 , just ran npm install again to make sure
the only other change i made was to add "serve": "ionic-app-scripts serve" to packge.json scripts.

![gif11](https://user-images.githubusercontent.com/25790435/29419037-8f5f0060-835d-11e7-8c95-c348a2b83892.gif)

**Comment by jgw96** [comment]
@oren-gershoni ahh ok, its when you refresh on that page, thanks for clearing that up. We can now reproduce this and will look into it.

**Comment by kensodemann** [comment]
Issue #12575 also describes this issue.

**Comment by doender** [comment]
Any progress on this issue?

**Comment by doender** [comment]
I'm also running into this. Any progress on this issue?

**Comment by rodriguezmanu** [comment]
+1

**Comment by koenoe** [comment]
+1

**Comment by remisture** [comment]
+1

**Comment by cmer4** [comment]
+1

**Comment by cyberundertakor** [comment]
+1

**Comment by pbxcyde** [comment]
+1

**Comment by nikhilmathew** [comment]
+1

**Comment by enricodeleo** [comment]
+1

**Comment by fagianijunior** [comment]
+1

**Comment by inmotionSIEGE** [comment]
+1 having same issue. Any update on that?

**Comment by bhumin3i** [comment]
Any update ?

**Comment by siddiq-rehman** [comment]
+1 any update on this.

**Comment by tejon-melero** [comment]
Any update on this? This issue is causing our project a lot of trouble.

**Comment by DMalagonH** [comment]
A year later...

**Comment by rodrigosanchezg8** [comment]
Yay! a post of my problem made 2 years ago, it must already be solved.
¿Guys?

**Comment by cyberundertakor** [comment]
Its still there

**Comment by lourencogtac** [comment]
I found two ways to fix this error:

The first was the input check for that, only with the definition of a 'root' that would enter the screen. According to code below:

` ionViewCanEnter() {
    var current = this.app.getActiveNav();
    if (typeof (current.getActive) == "function")
      return true;
    return false;
  }`

The second was using a timeout to reset the root: As below:

`setTimeout(() => {this.navCtrl.setRoot(TabsPage);}, 1000);`

Hope this helps.

**Comment by Chethannp** [comment]
It is still an issue just use the tabs template and in the first tab's constructor add an alert it is called twice :( this causing our application to do multiple xhr calls.

**Comment by AlfacomTonyCheong** [comment]
Issue #11122 also describes this issue. This issue is still happening with Ionic 4.1.1.

**Comment by siddiq-rehman** [comment]
Hi,


You can use "ionViewCanEnter" lifecycle function to escape from it as a
work around

Regards,
Siddiq Smd.
