### ISSUE TITLE
Ionic serve not working (exit code 130)

### ISSUE THREAD

**Issue by Alvaroctal** [ionic-team/ionic#12696]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Trying to compile the code, `ionic serve` or `ionic build` will end in exit code 

**Expected behavior:**
The ionic serve starts watching and opens the web server.

**Steps to reproduce:**

Since ionic left v3.6, using typescript version 2.3.4 (the one that works with rxjs) (upper versions of typescript in fact allows ionic start watching and work fine, but the project doesn't work due to type errors in rxjs).
 
```
$ ionic serve --verbose
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 
    '/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project', 
    local: true, binPath: '/usr/local/lib/node_modules/ionic/bin/ionic', 
    libPath: 
    '/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project/node_modules/ionic/dist/index.js' 
    }
[DEBUG] Daemon found (pid: 628)
[INFO] Starting app-scripts server: --address 0.0.0.0 --port 8100 
   --livereload-port 35729 - Ctrl+C to cancel
[16:41:59]  watch started ... 
[16:41:59]  build dev started ... 
[16:41:59]  clean started ... 
[16:41:59]  clean finished in 1 ms 
[16:41:59]  copy started ... 
[16:41:59]  transpile started ... 
[16:42:05]  transpile finished in 5.30 s 
[16:42:05]  preprocess started ... 
[16:42:05]  deeplinks started ... 
[16:42:05]  deeplinks finished in 71 ms 
[16:42:05]  preprocess finished in 72 ms 
[16:42:05]  webpack started ... 
[16:42:05]  copy finished in 5.65 s

And then the prompt is returned with exit code 130.
```

**Related code:**

Doesn't seems to be related with the code it self but setting typescript version to 2.4.1 or newer seems to allow ionic to complete the compilation, for some reason.   

**Other information:**

Moving to typescript 2.4.1 or newer it starts watching, opens the browser and seems to work fine (but as I said, this version of typescript doesn't work with rxjs).

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project/node_modules)

   @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node  : v6.11.2
    npm   : 3.10.10 
    OS    : macOS Sierra
    Xcode : Xcode 8.3.2 Build version 8E2002 
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! I am moving this issue to ionic-team/ionic-cli as it appears to CLI related. Please track the issue over there. Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2670
