### ISSUE TITLE
Fail on first start

### ISSUE THREAD

**Issue by TwanoO67** [ionic-team/ionic#12691]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[* ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ *] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Followed instruction to compile the "tabs template" after installing ionic3.
Result with a bug:

 ```
/usr/bin/codesign --force --sign - --timestamp=none /Users/aweber/Desktop/0SDV/0GIT/ionic3-angular4/platforms/ios/build/emulator/MyApp.app
** BUILD SUCCEEDED **
Error: Cannot read property 'replace' of undefined

[ERROR] An error occurred while running cordova run ios (exit code 1).
```

**Expected behavior:**
Running the app on a ios simulator

**Steps to reproduce:**
On a mac:
npm i -g ionic@latest
npm i -g cordova
ionic start ionic3-angular4 tabs
cd ./ionic3-angular4
ionic cordova run ios

**Related code:**

**Other information:**
Fresh install on a mac sierra

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/opt/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.1
    ionic (Ionic CLI) : 3.9.1

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node  : v6.9.5
    npm   : 5.3.0 
    OS    : macOS Sierra
    Xcode : Xcode 8.3.3 Build version 8E3004b 
```

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2662
