### ISSUE TITLE
serve in HTTPS mode 

### ISSUE THREAD

**Issue by Qvatra** [ionic-team/ionic#12699]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
not possible to serve locally in HTTPS mode. Its important because if remote host is SSL any secure cookies are lost when they come back to the non-SSL browser.

**Expected behavior:**
possibility to configure ionic to serve on HTTPS locally

**Reproduction**
What I'm trying to achieve in my app:
1) I’m sending authentication request from my app to SSL server using ionic proxy.
2) Server response contain sessionId in secure cookie.
3) I’m sending another request that suppose to have this sessionId in requestHeader cookie.

In reality the last request doesn’t have sessionId in requestHeader cookie and that's why I get 401 ‘Unauthorized’. When I look at responseHeader cookie of the first request I see the following: set-cookie:PHPSESSID=5583u6dcq803qlm5mnnc79vua4i0hs10htoj1mavskhv0bdg8m31; path=/; secure; HttpOnly

My idea is to make ionic somehow run locally in secure mode so that this secure cookie would be passed through.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Since this is not a feature request for the Ionic framework itself but is a feature request for the CLI, I am moving this issue over to ionic-team/ionic-cli.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2671
