### ISSUE TITLE
Google Maps getCameraPosition and GoogleMapsEvent are bugging

### ISSUE THREAD

**Issue by Julieng50** [ionic-team/ionic#12702]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
GoogleMaps plugin does not work properly.
If I'm doing `let pos = this.map.getCameraPosition();`, it always return `undefined`.
And if I'm doing : 
```
this.map.getCameraTarget().then((pos) => {
    alert("1");
});
```
The alert is never showing.

I found no other way to get the position...

Another thing : GoogleMapsEvent seems not working properly (MAP_READY is OK but CAMERA_IDLE isn't working).

**Related code:**

```
ngAfterViewInit() {
    this.loadMap();
}
loadMap(){
    let element: HTMLElement = document.getElementById('map');
    this.map = this.googleMaps.create(element, this.googleMapsOptions);

    this.map.one(GoogleMapsEvent.MAP_READY).then(() => {
        this.map.on("camera_idle").subscribe(()=>{
          let pos = this.map.getCameraPosition();
          // pos = undefined
        });
    }):
}
```

**Other information:**
2 forums link : 
https://forum.ionicframework.com/t/ionic-googlemaps-getcameraposition-returns-undefined/102495
https://forum.ionicframework.com/t/ionic-native-googlemapsevent-not-working/102443

```

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.1.2 browser 4.1.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v7.5.0
    npm  : 4.1.2
    OS   : Windows 10

```

From package.json : 
```
  "dependencies": {
    "@angular/animations": "4.3.5",
    "@angular/common": "4.3.5",
    "@angular/compiler": "4.3.5",
    "@angular/compiler-cli": "4.3.5",
    "@angular/core": "4.3.5",
    "@angular/forms": "4.3.5",
    "@angular/http": "4.3.5",
    "@angular/platform-browser": "4.3.5",
    "@angular/platform-browser-dynamic": "4.3.5",
    "@ionic-native/camera": "^4.1.0",
    "@ionic-native/core": "^4.1.0",
    "@ionic-native/geolocation": "4.1.0",
    "@ionic-native/google-maps": "^4.1.0",
    "@ionic-native/splash-screen": "4.1.0",
    "@ionic-native/status-bar": "4.1.0",
    "@ionic/storage": "2.0.1",
    "angular2-jwt": "^0.2.2",
    "ionic": "^3.9.1",
    "ionic-angular": "3.6.0",
    "ionicons": "3.0.0",
    "rxjs": "5.4.3",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.16"
  },
  "devDependencies": {
    "@ionic/app-scripts": "2.1.4",
    "ionic": "3.9.2",
    "typescript": "2.4.2"
  }
```

Thanks :)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! This does not appear to be an issue with the Ionic Framework, so I am closing this issue.

You may find the answer to your issue here: https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md

For example, according to the example in the [getCameraTarget() reference](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/getCameraTarget/README.md) it returns a lat-lng and not a promise.

I hope this helps you out.

Thank you for using Ionic

**Comment by Julieng50** [comment]
There is no description for a camera position undefined and when I'm looking in the source of GoogleMap, I found : 
    ```
    // File : @ionic-native/google-maps/index.d.ts
    /**
     * Get the position of the camera.
     * @return {CameraPosition}
     */
    getCameraPosition(): CameraPosition;
    /**
     * Get the current camera target position
     * @return {Promise<CameraPosition>}
     */
    getCameraTarget(): Promise<CameraPosition>;
```
So the getCameraTarget returns a Promise and not a target like the [getCameraTarget() reference](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/getCameraTarget/README.md) says.

Is the ionic native wrapper is working well ? How to get this around ?

**Comment by kensodemann** [comment]
Hmmmm, well, that seems rather incongruous then. I will move this issue over to the ionic-team/ionic-native repo.

**Comment by Julieng50** [comment]
Thanks !

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-native#1902
