### ISSUE TITLE
Popover location changes if app is opened horizontally vs vertically on a horizontal page

### ISSUE THREAD

**Issue by paqogomez** [ionic-team/ionic#12701]
**Description:**
The issue is based on the direction of the device when the app is opened. 

If the app is opened up and the device is horizontal, then when going to the page that is locked in landscape, the popover is centered just fine. 

If the app is opened and the device is vertical, forcing the window to flip horizontal when the landscaped page is opened, then the window appears off center and low.

**Steps to Reproduce:**

Popover code: 
    
    import { PopoverController } from 'ionic-angular';
    ...
    let popover = this.popoverCtrl.create(ImageSigPopOverPage, {
      carriage: this.carriage,
      callback: data => {
        this.log.debug('message', 'In the callback for popover. The data returned: ', data);
        this.signaturePad.fromDataURL(img);
        this._generateSignatureObject(data.title, img, data.autoDispatch);
      }
    }, {showBackdrop: true, enableBackdropDismiss: true, cssClass: "signature--popover"});

In the constructor:
   
    _platform.ready().then(() => {
      screenOrientation.lock('landscape');
    });

**My `ionic info`:**

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 6.0.0 
OS: OS X El Capitan
Node Version: v7.8.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Other Information:**

Stackoverflow question: https://stackoverflow.com/q/45744914/2589202

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

Also, for the `ionic info` information, if you could provide the output of running `ionic info` from the terminal/command prompt from your project's directory that would be very helpful.

Is the version of Ionic given above the version of the Ionic CLI you have installed or is it the version of the Ionic Framework your application is written in?

Thanks for using Ionic!

**Comment by paqogomez** [comment]
Thanks, I updated my ionic info.

As yet, i'm unable to do a sample application, but I'll try to put something together.

Are there better ways to position a popover?  Passing in the event seems to make the popover disappear.

**Comment by kensodemann** [comment]
Hello! Is this still an issue with the latest version of ionic? Have you been able to put some sample code together? Thanks!

**Comment by paqogomez** [comment]
Yes, it is still an issue for me, but I have not tested it on ionic 3.
I have gotten around it by allowing the page to rotate to vertical.  Its not ideal, but it works.

I still intend on creating a sample, but perhaps i'll close this ticket and open it again when i have a sample.  Thanks for you attention.
