### ISSUE TITLE
<ion-input> and <ion-icon> click events not firing after upgrade to 3.4.0

### ISSUE THREAD

**Issue by stevebread** [ionic-team/ionic#12703]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

After upgrade from 3.3.0 to 3.4.1, click event is not fired for &lt;ion-input&gt; and &lt;ion-icon&gt;

**Expected behavior:**

Click events should be fired as before

**Steps to reproduce:**
This issue is reproducible on Android (I'm using Genymotion with Galaxy S7 7.1.0 API 25 virtual device). The same code on Plunkr does not exhibit this issue.
Please see the attached file for an app that reproduces the issue. The package.json is for v3.3.0. Clicking on the input field and the icon increments the counters. The zip also includes the package.json for 3.4.1. With a 3.4.1 build the counters do not increment when clicking either the input or icon.

**Related code:**
View:
```
<ion-header>
</ion-header>
<ion-content padding [formGroup]="myForm">
  <ion-item>
    <ion-label stacked>Selected value:</ion-label>
    <ion-input formControlName="selectedValue" (click)="onInputClick()"></ion-input>
    <ion-icon name="search" item-right (click)="onIconClick()"></ion-icon>
  </ion-item>
  <div>inputClickCount: {{inputClickCount}}</div>
  <div>iconClickCount: {{iconClickCount}}</div>
</ion-content>
```
ts:
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import {FormBuilder, FormGroup} from "@angular/forms";

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  inputClickCount = 0;
  iconClickCount = 0;
  myForm: FormGroup;
  
  constructor(public navController: NavController, private fb: FormBuilder) { }
  
  ngOnInit() {
        this.myForm = this.fb.group({
      selectedValue: [{value: 'click me', disabled: true}],
    });
  }
  
  onInputClick() {
    this.inputClickCount++;  
  }

  onIconClick() {
    this.iconClickCount++;  
  }
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
For 3.3.0
```
cli packages: (C:\Users\Steve\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.1.2
    Ionic Framework    : ionic-angular 3.3.0

System:

    Android SDK Tools : 25.2.5
    Node              : v6.9.5
    npm               : 3.10.10
    OS                : Windows 10
```
For 3.4.1
```
cli packages: (C:\Users\Steve\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.1.2
    Ionic Framework    : ionic-angular 3.4.1

System:

    Android SDK Tools : 25.2.5
    Node              : v6.9.5
    npm               : 3.10.10
    OS                : Windows 10
```
[sample-app.zip](https://github.com/ionic-team/ionic/files/1236567/sample-app.zip)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I just tried your code in a sample application using `ionic-angular` version `3.6.0` and it worked as expected. Have you tried this on `3.6.0`?

Thank you for using Ionic

**Comment by stevebread** [comment]
Got the same behavior on 3.6.0. I found that on both 3.4.1 and 3.6.0, the input click is registered if I tap somewhere on the far left edge of the input box. I examined the HTML with Chrome inspect and found that if I remove `<div class="input-cover"></div>` clicks start working on both 3.4.1 and 3.6.0. This element also appears in 3.3.0 but has a `tappable` attribute.

**Comment by kensodemann** [comment]
I duplicated this in both the Android and iOS emulators. In iOS, the input never receives a click event. My code is here: https://github.com/kensodemann/test-bed-blank/tree/test/inputClick. If anyone clones it, be sure to look at the test/inputClick branch, not master.

Note also that I had to make the input enabled to receive click events. This makes sense given that if you were to create a standard HTML form with a disabled input it would not receive click events either.

I will leave this open. It might be helpful to leave your use case here so that it can be better understood or so that someone could potentially suggest a work around.

**Comment by stevebread** [comment]
Thanks @kensodemann.

The use case: The input is part of a form. Clicking the input/search icon opens a modal where the user sees a list of items and can filter them to find the required one. The item is not a string and so the user should not be able to enter text, it must be selected from a list. That's why the input is disabled. I made the input clickable in addition to the search icon because I think a user would expect to be able to tap the value to change it.

**Comment by shahramSo** [comment]
I've encountered  with this problem in 3.12.0, any idea to resolve it?

**Comment by coderReview** [comment]
Have you tried changing the z-index property for ion-icon?

**Comment by jkhask** [comment]
This is occurring for me on ionic 3.20! I know it was behaving properly not too long ago. Any updates here?

**Comment by thakurinbox** [comment]
I have same issue, I am able to call function on browser but its does work in Emulator and Device. 

@coderReview  z-index does not help here.
