### ISSUE TITLE
Can't close keybord after typing in searchbar

### ISSUE THREAD

**Issue by juanjoseadan** [ionic-team/ionic#12706]
**Ionic version:**  (check one with "x")
[ ] **1.x** 
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
I have a single app (starting a new project) with an "<ion-searchbar>" control in the top, this searchbar has the "Cancel" button active.

When you type something in the searchbar and then you tap on "Cancel" button, the keyboard hides a second and then shows again, this seems to be an infinite loop (you need yo tap in the "<ion-content>" or another control to hide the keyboard).

I've tried to hide the keyboard manually triggering the "ionCancel" event and calling the ionic native keyboard method to hide -> "this.keyboard.close()" but nothing happens.

I'm experiencing this issue with no apparently solution in the forum, it's getting very annoying to achieve this "simple" behavior.

**Expected behavior:**
Hide the keyboard when tap/clic in "cancel" button.

**Steps to reproduce:**
Just try it yourself by creating a blank application, add an ion-searchbar and run it on a real device

**Related code:**

This is my HTML code
```
<ion-header>
  <ion-navbar color="primary-strong">
    <ion-title >Blank app</ion-title> 

    <ion-buttons>
      <button ion-button icon-only menuToggle>
        <ion-icon name="menu"></ion-icon>
      </button>
    </ion-buttons>

    <ion-buttons end>
      <button ion-button icon-only (click)="openSearch()">
        <ion-icon name="search"></ion-icon>
      </button>
    </ion-buttons>

  </ion-navbar>

  <ion-toolbar *ngIf="showSearchbar">
    <ion-searchbar placeholder="Search bar..."
                   cancelButtonText="Cancel"
                   [showCancelButton]="true"
                   [(ngModel)]="keyword"
                   (ionCancel)="cancelSearch(null, $event)">
    </ion-searchbar>
  </ion-toolbar>
</ion-header>

<ion-content no-padding>

  <ion-label>This is just a test application...</ion-label>

</ion-content>
```

And this is the Typescript code...

```
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams, LoadingController, ModalController } from 'ionic-angular';
import { Dialogs } from '@ionic-native/dialogs';
import { Keyboard } from '@ionic-native/keyboard';

@IonicPage()
@Component({
  selector: 'page-find-people',
  templateUrl: 'find-people.html',
})
export class FindPeoplePage {

  public showSearchbar: boolean = false;
  public keyword: string = '';

  constructor(public navCtrl: NavController, 
              public navParams: NavParams,
              public dialogs: Dialogs,
              public keyboard: Keyboard) {
    // Code here
  }

  openSearch() {
    this.showSearchbar = true;
  }

  cancelSearch(args, evt) {
    // Here i'm trying to hide the keyboard manually but it does not work
    this.keyboard.close();
  }
}
```

**Other information:**
Nope

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/myosxusername/Projects/ExampleApp/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.4.2

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    npm        : 3.10.10
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? I want to make sure whatever I try this on is using the same plugins you are using, etc.

Thanks for using Ionic!

**Comment by longdw** [comment]
I have a same issue.when click cancel button in searchbar the keyboard can't close.

**Comment by juanjoseadan** [comment]
Please follow the next steps:

1. Compile the project for iOS: ** ionic cordova build ios **

2. Run it on a real device (i'm using an iPhone 7+ with iOS 10.3.3)

3. Tap the searchbar and type something

4. Tap on "Cancel" button located beside the searchbar. It's suppused to close the keyboard but after a moment the keyboard shows up again and again

**Comment by juanjoseadan** [comment]
@kensodemann Have you found the issue?

**Comment by kensodemann** [comment]
Not yet. I will try to carve out time to look at it today.

**Comment by kensodemann** [comment]
Thank-you for supplying the sample application. That was a great help!

Using your sample application I solved the issue by using the [WKWebView Engine](https://github.com/ionic-team/cordova-plugin-wkwebview-engine) in place of the default UIWebView engine.

Please try that in your project and let me know if that fixes the issue for you.

**Comment by juanjoseadan** [comment]
If I use WKWebView Engine in my project it will change the application behaviour? We have a lot of functionalities and we don't want to refactorize them

**Comment by kensodemann** [comment]
@juanjoseadan - not that I know of. Your logic should remain the same. Like with any such change I suggest testing.

Using WKWebView is following Apple's own advice, however: https://developer.apple.com/documentation/uikit/uiwebview
https://developer.apple.com/documentation/webkit/wkwebview

**Comment by juanjoseadan** [comment]
Ok. We will test it later and I'll let you know the results. Thank you @kensodemann

**Comment by kensodemann** [comment]
I am going to close this issue. If using WKWebView does not fix the issue for you, please let me know and we can re-open the issue.
