### ISSUE TITLE
ionic serve error: Cannot find namespace 'NodeJS'. No error on ionic build --prod

### ISSUE THREAD

**Issue by laitedliang** [ionic-team/ionic#12708]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
When running `ionic serve`, it gives me error  *Cannot find namespace 'NodeJS'.*

**Expected behavior:**
`ionic serve` runs without error

**Steps to reproduce:**
1. create new blank ionic project
1. `npm install @types/node`
1. open `home.ts`, add `timeout: NodeJS.Timer;`  before constructor
1. `ionic serve`

**Related code:**

```ts
// home.ts
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  timeout: NodeJS.Timer;
}
```

**Other information:**

- The error exists only on `ionic serve`. Running `ionic build --prod` produce no error

- `@types/youtube` YT also have the same issue

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\AsahiArts\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v7.10.0
    npm  : 4.2.0
    OS   : Windows 7
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

I have attempted to duplicate this using your code above in one of my sample applications and do not get the issue.

Thanks for using Ionic!

**Comment by laitedliang** [comment]
@kensodemann thanks for your reply

I have setup a [repo](https://github.com/laitedliang/ionic-test-namespace-error) for the demonstration

Just pull it, npm install, ionic build, and the error occurs (at least for me)

I have also tried installing the latest node and npm version, and reinstall ionic. But still got the error

ionic info:

```
cli packages: (C:\Users\AsahiArts\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.4.0
    npm  : 5.3.0
    OS   : Windows 7
```

**Comment by kensodemann** [comment]
Thank you for posting that repo. I am sorry that it took a while for me to to be able to it.

I cloned your repo and it built and ran just fine.

I am going to close this issue as it is not an issue with the Ionic Framework itself so far as I can tell.

I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Perhaps someone else has run across this as well and can offer some guidance.

Thanks for using Ionic!

**Comment by miloslavskacel** [comment]
solved by https://github.com/ionic-team/ionic-app-scripts/issues/1209
