### ISSUE TITLE
Inconsistent width for lists inside virtual scroll

### ISSUE THREAD

**Issue by Airblader** [ionic-team/ionic#12705]
**Ionic version:**  (check one with "x")
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
When using an `ion-item-group`-based list with virtual scroll, the width of the items is inconsistent. In particular, text truncation no longer works properly as the items become potentially wider than the viewport (but on browser they instead end up being too short).

**Expected behavior:**
The width should still be 100% inside virtual scrolls.

**Steps to reproduce:**

```
    <div [virtualScroll]="items">
        <div *virtualItem="let item">
            <ion-item-group>
                <ion-item>{{ item }}</ion-item>
            </ion-item-group>
        </div>
    </div>
```

**Other information:**
The problem can be fixed by adding `[style.width.%]="100"` to the `div` containing the `*virtualItem`. This is basically the same problem and fix as #6239 which has been closed a long time ago as fixed because it only considered sliding items, I guess(?)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/home/ingo/.npm-global/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

System:

    Node : v8.3.0
    npm  : 5.3.0 
    OS   : Linux 4.11

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/cpeRJs?p=preview) or a simple demo application via a GitHub repo that demonstrates this issue? Thanks for using Ionic!

**Comment by Airblader** [comment]
I tried to create a plunker, but cannot reproduce the issue there. I'll try to find the time to reproduce it with a simple app.

**Comment by kensodemann** [comment]
@Airblader - I will close this issue in the meantime. If you are able to recreate the issue via a sample app, please provide the GitHub repo here and I will reopen the issue.

**Comment by Airblader** [comment]
Yes, that's fair. Thanks!
