### ISSUE TITLE
URL not setting back (in browser) if clicked on "(App)Back-Button"

### ISSUE THREAD

**Issue by big-r81** [ionic-team/ionic#12709]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If you pushing a (lazy loaded) page on the nav stack and go back (Back-button of the navbar) then
the url isn't set back.
Example:

1. App starts with the following url:
```
localhost:8100
```
2. Press the “Nav!” - Button and the test page is shown with URL:
```
localhost:8100/#/test
```
3. Press “Back”-Button (in the app, not browser!), app shows the homepage and the url is:
```
localhost:8100/#/test
```

**Expected behavior:**

URL should be
```
localhost:8100
```
again!

If you have livereload enabled and you change the code, the pushed page is shown instead of the homepage. If you create a page without lazy loading, all is fine an the url stays tha same (localhost:8100) for all pages!
 
**Steps to reproduce:**

1. Create a new blank project:
```
ionic start TestApp blank
```
2. Generate new page:
```
ionic g page test
```
3. Create a button on the homepage which pushes a new page on the nav stack.

home.ts:
```
push() {
  this.navCtrl.push('test');
}
```

home.html:
```
<ion-content padding>
  <button ion-button (click)="push()">Nav!</button>
</ion-content>
```
4. Start the app in the browser:
```
ionic serve
```
5. App starts with the following url:
```
localhost:8100
```
6. Press the “Nav!” - Button and the test page is shown with URL:
```
localhost:8100/#/test
```
7. Press “Back”-Button (in the app, not browser!), app shows the homepage and the url is:
```
localhost:8100/#/test
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.1.3
    npm  : 5.3.0 
    OS   : macOS Sierra
```

**Comment by Gerryzhang** [comment]
I also met the same problem, with what method can solve?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I think the problem you are seeing is due to not lazy loading the home page. I suggest lazy loading that page as well. I put together a [sample application](https://github.com/kensodemann/test-bed-blank) that shows this working.

If you apply that change and it still does not work for you, please provide a GitHub repository that duplicates the issue.

Thank you for using Ionic

**Comment by Gerryzhang** [comment]
@kensodemann 
Your project will be an error,use by chrome backbutton for test.
你的项目一样会报错，要使用chrom的返回按钮来测试才能复现出来报错现象。

zrhcode@163.com

**Comment by big-r81** [comment]
@kensodemann 
Hi,

thank you for your hints. If the HomePage is a lazy loaded page too, it works as expected. 👍 

Some questions:
1. Should the templates (e.g blank,...) be updated to support lazy loaded (Home-) pages?
2. Should it work wheter it is a lazy loaded page or not?
3. Should it work if pages (non lazy vs. lazy loaded pages) mixed up?

**Comment by kensodemann** [comment]
@Gerryzhang - I believe the error you are referring to is covered by issue #12499

**Comment by kensodemann** [comment]
@big-r81 - Glad to hear it is working for you.

Here are some answers to your questions.

1. an argument could be made to make the templates favor lazy load by default, I am not completely sure what is in the works with regard to that for the next Ionic version
2. yes, and it does work without lazy loaded pages
3. I suggest sticking with a single strategy in the app, it just works better

I tossed this together to explain items 2 and 3: https://github.com/kensodemann/test-nav-strategies

If you look at the commits, it walks the app through the following stages:

1. the base app (results of blank starter)
2. add child page using basic nav, note that the URL never changes in this case, no deep linking is supported, not a good PWA experience, but fine for a lot of mobile applications
3. adds deep linking parameters, note that the URL changes properly as you nav, still completely eagerly loaded, if you look in the network tab as you use the app the whole thing is downloaded on load
4. lazy loaded, URL changes properly, tiny bundles are downloaded as you nav to new pages

Hopefully, that example clears up your questions. If not please let me know.

**Comment by karansharma27** [comment]
@kensodemann my home page is lazy loaded too, still I am facing the same issue. What can I do?

**Comment by kensodemann** [comment]
@karansharma27 - your best bet is to have source available for people to look at, preferably via GitHub. Then ask your question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/), providing a link to the source so people can go look at it. Thanks for using Ionic!

**Comment by Martinspire** [comment]
The thing is: if you load the page with `localhost:8100/#/home` instead of just `localhost:8100` it does seem to work and put the `/#home` at the end of the URL when you navigate back from page 2 to 1.

I'm wondering whether it is better then to force it and just load the page at /#/home because then the navigation will be properly set.
