### ISSUE TITLE
Selection box goes outside when scrolling(by swiping the screen) in iOS Emulator in Ionic 2

### ISSUE THREAD

**Issue by rifathaqueamit** [ionic-team/ionic#12712]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
![slidingproblem](https://user-images.githubusercontent.com/13817512/29517012-ce5aaa64-8694-11e7-8e39-4257c00e6f74.gif)

Platform : iOS 10.3
Device : Emulator(iPhone 7 Plus)

In the input component input, I write something and select it, then I swipe(using mouse) the screen to scroll,
during that time, the selection box moves outside of the input component.

**Expected behavior:**
The selection box and the cursor of the input should stay in the right place during scrolling of
the screen when swiping.

**Steps to reproduce:**
1. create a blank ionic 2 app with 
ionic start SelectionTest blank --v2

2. then in the home.html file, add 10 buttons
then one input then again more 10 buttons.

3. then swipe the screen to scroll

**Other information:**
I tried some ways to solve this problem including using ApplicationRef to force update the
screen. But I couldn't able to solve the problem.

**Ionic info:**
Cordova CLI: 7.0.1 
Ionic Framework Version: 3.6.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 2.1.3
ios-deploy version: 1.9.1 
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.11.1
Xcode version: Xcode 8.3.3 Build version 8E3004b

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

I attempted to duplicate this using version 3.6.0 of the ionic framework and was unable to.

Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello! Is this still an issue with the latest version of ionic? If so, please provide a GitHub repo with a sample application that demonstrates your issue and I will reopen the issue.

Thanks!

**Comment by rifathaqueamit** [comment]
@kensodemann 
Sorry for the late reply. I have uploaded my project on github
https://github.com/rifathaqueamit/SelectionTest
You have to build and run on real device or in emulator to check. I also added a video (https://youtu.be/19brzIqD1Js) done in iPhone4s where you can see this issue (watch from 25seconds)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I was able to reproduce with your sample application. I also installed WKWebView and it still occurred. I also updated your plugins, ionic-angular version, etc. Will try later with similar app generated fresh using the latest versions of Ionic.

Thank you for using Ionic

**Comment by rifathaqueamit** [comment]
Is the bug fixed with latest version of Ionic ?
