### ISSUE TITLE
On mobile Safari the input element does not float above keyboard 

### ISSUE THREAD

**Issue by tmvnk** [ionic-team/ionic#12710]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On mobile Safari input element does not float above keyboard 

**Expected behavior:**
On mobile Safari input element needs to float above keyboard 

**Steps to reproduce:**

**Related code:**

```
.ios .input-cover is position is now absolute but should be:

.ios .input-cover {
  position: static;
}

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.1.0 browser 4.1.0 ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1
    ios-sim           : 6.0.0
    Node              : v7.5.0
    npm               : 4.3.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by kensodemann** [comment]
There are a couple of plugins that may help as well. There are known issues with the default UIWebView on iOS. For this reason, the WKWebView was created:

https://github.com/ionic-team/cordova-plugin-wkwebview-engine

There is also an updated keyboard plugin:
https://github.com/ionic-team/cordova-plugin-keyboard

You will need to uninstall the current keyboard plugin and replace it with this plugin.

**Comment by kensodemann** [comment]
Hello! Is this still an issue when using the updated plugins? If it is, please provide a GitHub repo with a sample application that demonstrates the issue and I will reopen this.

Thanks!
