### ISSUE TITLE
feat(alert): add a Sass variable for the title's text color

### ISSUE THREAD

**Issue by bushybuffalo** [ionic-team/ionic#12715]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
There is no Sass variable acting on alert titles' color property, which has no particular value set.

**Expected behavior:**
I would like to be able to customize my alerts title text color using variables, as I currently do for the message, radio and checkbox labels, and buttons.
This would involve adding 3 variables, one for each platform (see code below).

**Steps to reproduce:**
Irrelevant.

**Related code:**

```
$alert-ios-title-text-color: color($colors, primary);
$alert-md-title-text-color: color($colors, primary);
$alert-wp-title-text-color: color($colors, primary);
```

**Other information:**
I'm trying to do this because I'm creating a dark theme for a customer's app. This could also be an opportunity to make some changes to Ionic's dark theme. 
Speaking of which, I think it could be some major visual improvements, as I found myself tweaking quite a lot of Sass variables to get a nice result.
Let me know if you think it could be nice to open another issue to discuss about the dark theme, I would be happy to help you improve it ! 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: 

    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 6.0.0 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : browser 4.0.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v7.5.0
    OS                : Windows 10
    npm               : 5.3.0 
```

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thank-you for using Ionic!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#298
