### ISSUE TITLE
ion-infinite-scroll can't triger ionInfinite event when scroll to bottom of page quickly.

### ISSUE THREAD

**Issue by longdw** [ionic-team/ionic#12717]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Platform**
iOS

**Current behavior:**
If we include ion-infinite-scroll in a Page, then I scroll the list quickly, and the list auto slide to the end.A blank white space is added at bottom of the page, and doMore() function can't be trigered.

**Expected behavior:**
when scroll to bottom of the page auto,it should triger the ionInfinite event.

**Related code:**

```
<ion-content>
    <retryview (retryViewClick)="retryViewClick()"></retryview>
    <ion-refresher (ionRefresh)="doRefresh($event)">
        <ion-refresher-content
            pullingIcon="arrow-dropdown"
            pullingText="pulling to refresh"
            refreshingSpinner="circles"
            refreshingText="loading...">
        </ion-refresher-content>
    </ion-refresher>

    <ion-card tappable *ngFor="let item of datas;let i = index;" (click)="itemClick(item)">
		<ion-card-content class="list-style">
            <div class="main-title">
                {{item.title}}
            </div>
        </ion-card-content>
    </ion-card>
    
    <ion-infinite-scroll (ionInfinite)="doMore($event)">
        <ion-infinite-scroll-content loadingSpinner="circles" loadingText="loading..."></ion-infinite-scroll-content>
    </ion-infinite-scroll>
</ion-content>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: 

    @ionic/cli-utils  : 1.8.0
    ionic (Ionic CLI) : 3.8.0

global packages:

    Cordova CLI : 6.5.0 

local packages:

    @ionic/app-scripts : 1.3.12
    Cordova Platforms  : android 6.1.2 ios 4.3.1
    Ionic Framework    : ionic-angular 3.5.2

System:

    ios-deploy : 1.9.1 
    Node       : v7.2.1
    npm        : 4.0.5 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by longdw** [comment]
@kensodemann  thanks for your reply. I create a project [TestScroll](https://github.com/longdw/TestScroll), the gif describe the problem.

**Comment by kensodemann** [comment]
@longdw - thank you for creating the sample project for us to look at. I will take some time to look at this later today.

**Comment by mifkys** [comment]
I have similar problem in my project and I can't use WKWebView Engine because of CORS issue.

**Comment by longdw** [comment]
@kensodemann  Perfect solution to my problem.thank you very much.

**Comment by kensodemann** [comment]
@longdw - excellent!! Glad to hear it.

**Comment by mifkys** [comment]
Why you close this issue? Using WKWebView Engine is not solution because it's not useful in some situations when app must to do api calls to external service.

**Comment by kensodemann** [comment]
@mifkys - you may want to have a look at this issue and see if it solves your problem: https://github.com/ionic-team/cordova-plugin-wkwebview-engine/issues/163

**Comment by kensodemann** [comment]
@mifkys - thanks for your question. The issue is closed here because this is not an issue with the Ionic framework but with the underlying view engine. The only fix for that is to use a different view engine.

**Comment by mifkys** [comment]
@kensodemann cool! Not see this solution. Thanks!
