### ISSUE TITLE
NavController.popTo seems to have unwanted extra parameter

### ISSUE THREAD

**Issue by rapropos** [ionic-team/ionic#12716]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
TypeScript 2.5.1 (perhaps some earlier versions as well) seems to be stricter about certain things, throwing fatal build errors such as the one described in [this forum thread](https://forum.ionicframework.com/t/class-tabs-incorrectly-implements-interface-navigationcontainer-types-of-property-parent-are-incompatible-type-navcontrollerbase-is-not-assignable-to-type-navcontroller-types-of-property-popto-are-incompatible/102729).

**Expected behavior:**
No fatal build error.

**Steps to reproduce:**
Try to build a tabs starter project with TypeScript 2.5.1.

**Other information:**
[Line 482 of NavController](https://github.com/ionic-team/ionic/blob/master/src/navigation/nav-controller.ts#L482) has four parameters: `page`, `params`, `opts`, and `done`. Implementing class `NavControllerBase` [line 141](https://github.com/ionic-team/ionic/blob/master/src/navigation/nav-controller-base.ts#L141) has but three: `indexOrViewCtrl` which is hopefully equivalent to `page`, `opts` and `done`. `params` is missing. Since [every location in the code that calls this](https://github.com/ionic-team/ionic/search?utf8=%E2%9C%93&q=popto&type=) seems to give it three arguments, I consider it more likely that it is the abstract declaration in `NavController` that is wrong, and should have the `params` argument removed.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! We will look into this.

Thank you for using Ionic

**Comment by danbucholtz** [comment]
@rapropos, I've noticed this was weird for awhile. We'll update in V4.

Thanks,
Dan

**Comment by rapropos** [comment]
I'm not clear why this is tagged "breaking change required". The method in question is tagged `@hidden`,  and is not documented in the public API. Removing `params` would just bring all of the existing code implementing the interface into compliance with how it is already being used.

**Comment by kensodemann** [comment]
Updated abstract `nav-controller.ts` to match the definition in the base. Will be part of the v4 release.
