### ISSUE TITLE
I tried virtual scroll to display a list but in 3.9.2 its not displaying anything 

### ISSUE THREAD

**Issue by hasnentai** [ionic-team/ionic#12718]
Thats my code

 <div class="list1 main-content">

        <ion-list no-lines [virtualScroll]="my_prg" [approxItemHeight]="'100px'">
            <ion-item ion-item *virtualItem="let item">
                {{item.name}}
            </ion-item>

        </ion-list>
    </div>

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out please.

Also, if you could provide a [plunker](http://plnkr.co/edit/cpeRJs?p=preview) or a simple demo application via a GitHub repo that demonstrates this issue that would be very helpful.

Thanks for using Ionic!
