### ISSUE TITLE
I can't import ActionSheetButton from ionic-angular module

### ISSUE THREAD

**Issue by JaviRpo** [ionic-team/ionic#12719]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.9.2**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I can't import **ActionSheetButton** from **ionic-angular** module

![image](https://user-images.githubusercontent.com/8562436/29545830-36382a14-86b6-11e7-8714-54f1ae279262.png)

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! We will look into this. Thank you for using Ionic

**Comment by kensodemann** [comment]
@JaviRpo - this will be fixed in v4.

**Comment by pickfire** [comment]
I think the same is happening in `@ionic/angular@4.0.0-alpha.7`.
