### ISSUE TITLE
File Encryption plugin not installed. ( but plugin already installed )

### ISSUE THREAD

**Issue by jeeva001** [ionic-team/ionic#12711]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
File Encryption with "cordova-safe" plugin, not working well.

**Expected behavior:**
need to implement File Encryption with  "cordova-safe" plugin.

**Steps to reproduce:**

**Related code:**

var fileRoot = this.dir.externalRootDirectory + "Audio/" + this.fileName + ".wav";
this.fileEncryption.encrypt(fileRoot , 'passpass');

**Other information:**
https://stackoverflow.com/questions/44969832/is-cordova-safe-still-working-with-ionic3

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
cli packages: (D:\recording_project\node_modules)

   @ionic/cli-utils  : 1.9.1
   ionic (Ionic CLI) : 3.9.1

global packages:

   Cordova CLI : 7.0.1

local packages:

   @ionic/app-scripts : 2.1.3
   Cordova Platforms  : android 6.2.3
   Ionic Framework    : ionic-angular 3.6.0

System:

   Node : v6.11.2
   npm  : 5.3.0
   OS   : Windows 10

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This appears to be either an issue with the ionic-native wrapper or with the Cordova plugin itself and not an issue with the Ionic Framework. I am moving this issue to ionic-team/ionic-native. Please track the issue over there.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-native#1907

**Comment by manojbhardwaj** [comment]
still this issue is coming why it is not fixed?

**Comment by truptikumbhar** [comment]
same here..

**Comment by manojbhardwaj** [comment]
any solution for this

**Comment by truptikumbhar** [comment]
No..I also trying to fixed it..

**Comment by arekkoperek** [comment]
I think cordova safe plugin is still not fixed so the ionic plugin does not work also. (https://github.com/disusered/cordova-safe/issues/19)  . Anyone managed to fix the issue?

**Comment by CharlesGrimont** [comment]
Always not solved for cordova-save / File Encryption !!!
Any help would be appreciated.

Tanks !!!
