### ISSUE TITLE
Ionic cordova plugin add --link doesn't work the same as cordova plugin add --link to link to a plugin that is in development

### ISSUE THREAD

**Issue by ashgibson** [ionic-team/ionic#12726]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Ionic cordova plugin add --link doesn't work the same as cordova plugin add --link to link to a plugin that is in development. Shouldn't it accept the same cli arguments?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

It appears that this is a CLI issue and not an issue with the Ionic Framework (ionic-angular). I will move this issue over to ionic-team/ionic-cli. 

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2691
