### ISSUE TITLE
perf: The propblem with using createJS lib (v2015)

### ISSUE THREAD

**Issue by alexandrsashin** [ionic-team/ionic#12723]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>After adding code for canvas in controller, in console message has shown "Uncaught TypeError: cjs.MovieClip is not a constructor". But createJS lib was included.
http://plnkr.co/edit/XODJDi?p=catalogue</span>

<span is-issue-template></span>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! This is an issue with Ionic V1 so I am moving it to the ionic-team/ionic-v1 repo. Please track the item over there.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-v1#301
