### ISSUE TITLE
Android: Alert cancelled make focus lost

### ISSUE THREAD

**Issue by speedfl** [ionic-team/ionic#12722]
**Ionic version:**  (check one with "x")
2.3.0

**I'm submitting a ...**  (check one with "x")
[x ] bug report

**Current behavior:**
The focus is lost when user cancel an alert

**Expected behavior:**
The focus must stay

**Steps to reproduce:**
1/ User click on button 1 which launch an alert
2/ User cancel the alert (by clicking somewhere else or on a cancel button)
3/ User want to click again on button 1 
4/ The button is not focus at click

**Related code:**

I prepared a little example to expose what I am saying.
So there is a list of element clickable with checkbox

When I click on the button start it launches the alert. Then I cancel it (by clicking somewhere else for example)
Then I want to click on it again. However instead of clicking on it the screen go back to the top and I am clicking on addElem. 

ts file:

```
@Component({
  selector: 'page-pageOne',
  templateUrl: 'pageOne.html'
})
export class PageOne {

  listElement = [
    {
      label : "One",
      checked : false
    },
    {
      label : "Two",
      checked : false
    },
    {
      label : "Three",
      checked : false
    },
    {
      label : "Foor",
      checked : false
    },
    {
      label : "Five",
      checked : false
    },
    {
      label : "Six",
      checked : false
    },
    {
      label : "Seven",
      checked : false
    },
    {
      label : "Eigth",
      checked : false
    },
    {
      label : "Nine",
      checked : false
    },
    {
      label : "Ten",
      checked : false
    }
  ];

  constructor(private nav : NavController,
              private alertCtrl : AlertController,) {
  }

    addElem(){
      this.nav.push(OtherPage);
    }

    start(){
        let alert = this.alertCtrl.create();
        alert.setTitle("Title");
        alert.setMode("md");

          alert.addInput({
          type: 'radio',
          label: "Do something",
          value: 'SOMETHING',
          checked: true
        });

          alert.addInput({
          type: 'radio',
          label: "Do something else",
          value: 'SOMETHING_ELSE'
        });
        alert.addButton({
          text: 'OK',
          handler: data => {
            console.log("Ok clicked: " + data);
          }
        });
        alert.addButton({
          text: 'Cancel',
          handler: () => {
            console.log("Cancel click");
          }
        });
        alert.present();
    }
}
```

html file:

```
<ion-header>
  
  <ion-navbar color="primary">
    <ion-title>Title</ion-title>
  </ion-navbar>
  
</ion-header>

<ion-content padding>
  <ion-list>
    <ion-item *ngFor="let elem of listElement" text-wrap>
      <ion-label>
        <h2 color="primary">
          {{elem.label}}
        </h2>
      </ion-label>
      <ion-checkbox color="primary" checked="false" [(ngModel)]="elem.checked"></ion-checkbox>
    </ion-item>
    <button ion-item (click)="addElem()" class="aprimary"> Select more
      <ion-icon name="add-circle" item-left></ion-icon>
    </button>
  </ion-list>
  
  <div class="center">
    <button mode="ios" ion-button color="primary" (click)="start()"> Start  </button>
  </div>
</ion-content>
``` 

css file:
```
page-pageOne{
.center {
  margin-left: auto;
  margin-right: auto;
  display: block;
  text-align: center;
}
}
```

**Other information:**
It seems that there is a margin which is added when the alert is presented (I have more scroll when I cancel it)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I attempted to duplicate your issue, but everything appears to be working fine for me. Here is my Ionic Info output so you know which version of stuff this was tested with:

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    Node       : v8.3.0
    npm        : 5.3.0 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
```

Can you provide the output of running `ionic info` for your project?

Can you provide a GitHub repo of a simple sample application that exhibits the issue you are having?

Thank you for using Ionic

**Comment by speedfl** [comment]
Hello.
Thanks for your fast reply. I will do it tomorrow morning (french hour) so you can reproduce the issue.
Regards

**Comment by speedfl** [comment]
Hello,

So I was able to reproduce the issue explained by my user with a starter project.
The link is here:

[fail2Scroll](https://github.com/speedfl/fail2scroll)

Here are my ionic info (I tried with latest version of ionic angular as well and it is reproducible):

`
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v4.6.0
Xcode version: Not installed
`


When I click on the alert a div class button-effect is created and added in the button.

`
<div class="button-effect" style="transform: translate3d(-20px, -26px, 0px) scale(1); height: <HEIGHT>px; width: <WIDTH>px; opacity: 0; transition: transform 300ms, opacity 210ms 90ms;"></div>
`

Width and height always have the same value

All the properties depend on the button size.
If you have a button with a single word like "OK" or "Start" the width and height will be short enougth to not have this losting of focus

However if the text of the button is too big the width will be bigger as well as the height so the focus is lost. I attached a picture of the issue.

Here are two example with two different texts ( first is "start" and second is "Start customization")

`
<div class="button-effect" style="transform: translate3d(-20px, -26px, 0px) scale(1); height: 93px; width: 93px; opacity: 0; transition: transform 300ms, opacity 210ms 90ms;"></div>


<div class="button-effect" style="transform: translate3d(42px, -97px, 0px) scale(1); height: 240px; width: 240px; opacity: 0; transition: transform 377ms, opacity 264ms 113ms;></div>

`
![image](https://user-images.githubusercontent.com/23298035/29604628-5fc4c882-87e8-11e7-8a62-bf0154a17ec5.png)

**Comment by kensodemann** [comment]
Thank you for your sample application and for your detailed explanation. I will have a look at this later today.

**Comment by kensodemann** [comment]
I have tried to duplicate this issue using your repo, but after a few attempts in a couple of different browsers, I cannot. If I understand correctly, the issue you have is:

1. start with long text in button (Start customization)
2. click that button
3. dismiss the alert by touching outside of alert
4. hit button again
5. ??? something other than alert happens ???

For me, once I get to item #5, I get the alert again, so it appears to be working fine for me. I tried this on Chome, Firefox, Safari, and the Android emulator.

Is my understanding of your issue correct?

**Comment by speedfl** [comment]
Hello

Thanks for your investigation. So basically nothing appears really (we cannot view it).
I only viewed it when I highligthed it with chrome debugger.

The issue does not occures on emulator and on browser unfortunately. I was just able to reproduce on mobile.

Galaxy s6, s7 and lg g5.

In fact as I said in the button a new div is created when alert is launched ( the one I showed in the image)
I made a little video to explain the steps.

1/ I Click on next page
2/ I scroll to the really bottom of the page (I cannot go further)
3/ I click on the alert and cancel it (by clicking somewhere else)
4/ I continue scrolling (at that moment I can go further)
5/ I restart to click on the button but as you can see the check box is selected (while I tried to click on the button)

Hope it will help.

The solution would be to remove this div if the alert is cancelled

[2017_08_23_20_33_20.zip](https://github.com/ionic-team/ionic/files/1246602/2017_08_23_20_33_20.zip)

**Comment by jgw96** [comment]
Hello all! @speedfl so I also pulled down your repo and tested it on my devices. One is a Nexus 6P running Android 8.0 and the other is a Nexus 6 running Android 7.1.1 and unfortunately, on both of those devices, I was not able to reproduce this issue. Because of this I would recommend taking this issue to our [forum](https://forum.ionicframework.com) or our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
