### ISSUE TITLE
ion-menu option for decide to block or not the content

### ISSUE THREAD

**Issue by jromerob** [ionic-team/ionic#12729]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ * ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ * ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On:

`<ion-menu side="right" [content]="content"  type="push">
  <menu-right></menu-right>
</ion-menu>
<ion-nav [root]="rootPage" #content swipeBackEnabled="false" ></ion-nav>
`

When open the ion-menu i can't interact with ion-nav content . In maps apps i need to interact with the map.

**Expected behavior:**
ion-menu option for decide to block or not the content

**Steps to reproduce:**

For Ionic V1 issues - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

For Ionic issues - http://plnkr.co/edit/cpeRJs?p=preview
-->

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (D:\dev\visor_jcyl\node_modules)

    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts        : 2.0.2
    @ionic/cli-plugin-cordova : 1.4.1
    Cordova Platforms         : none
    Ionic Framework           : ionic-angular 3.5.3

System:

    Node : v6.11.1
    OS   : Windows 10
    npm  : 3.10.10
```

**Comment by kensodemann** [comment]
Hello everyone! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#301
