### ISSUE TITLE
Putting <a> tag with navPush directive inside <p> tag forces user to double click on IOS

### ISSUE THREAD

**Issue by tolgaek** [ionic-team/ionic#12725]
**Ionic version:**
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
on iOS, when a `navPush` directive is put inside an `<a>` that is inside a `<p>` tag, the user has to click the link twice on ios to open (not an issue on desktop

**Expected behavior:**
On ios, the link should open on first click

**Steps to reproduce:**
```ts
<p>
   <a href="javascript:void(0)" [navPush]="paperlessPushPage">Link Name</a>Some other text
</p>
```
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/tekm/projects/apricot-hybrid-web-app/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-plugin-proxy         : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v8.2.1
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b
    npm               : 5.3.0
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

I attempted to duplicate your issue in a sample application I have but could not. I tried this on both the emulator and on my iPhone.

Here is my markup:

```html
  <p>
    You really should <a href="javascript:void(0)" [navPush]="'ChildPage'">Click Me!!</a> I will open up a child window. It is cool. One Last Try!!
  </p>
```

As you can see, I just took your markup and modified it slightly to work in my app (and added extra text), but it is essentially the same as yours.

Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello! Is this still an issue with the latest version of ionic? If so, can you please provide a GitHub repo with a sample app that demonstrates the issue? I will re-open this issue if that is the case.

Thanks!

**Comment by tolgaek** [comment]
Sorry @kensodemann I have a temp fix for this, I will create a repo next week and create a new issue. Thanks

**Comment by kensodemann** [comment]
@tolgaek - OK. You can also just link the repo here and I will re-open this issue rather than creating a new one. That would probably be best. Thanks!
