### ISSUE TITLE
Dynamic Splash Screen

### ISSUE THREAD

**Issue by christianwico** [ionic-team/ionic#12721]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Splash Screen is nothing but a static image reliant on pre-generation by `ionic cordova resources`.

**Expected behavior:**
Allow some sort of mechanism to programatically customize the splash screen (e.g. text overlays, version number, copyright, etc.) without having to modify them pre-build with an image editor.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\doireallyneedtohidethisname\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

System:

    Node : v6.11.2
    npm  : 3.10.10
    OS   : Windows 10
```

**Comment by AmitMY** [comment]
This issue is more closely related to cordova, as the ionic framework does not have access to the device before it loads.

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. As @AmitMY points out, this is more closely related to Cordova. However it may also serve as a catalyst for other ideas such as a build script that generates the resource from a template at build time, etc.

We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository if have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#299

**Comment by mdanics** [comment]
any updates on this? @kensodemann the link is dead

**Comment by kensodemann** [comment]
The link isn't dead, it just points to a private repo. Once Ionic v4 is released there will be an improved process for feature requests that will allow for more public comment. This one, however, is not Ionic related. It is something that would need to be handled by Cordova, Capacitor, or some other such thing.
