### ISSUE TITLE
Latest Ionic starter templates dont work on windows 10

### ISSUE THREAD

**Issue by agyepong** [ionic-team/ionic#12720]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Install latest ionic CLI on Windows 10 and run commands like:
$ ionic start cutePuppyPics
$ ionic start MyTabsIonicProject tabs 
$ ionic start MySuperIonicProject super
Get the following

C:\GitHub\ionic2>ionic start cutePuppyPics

? What starter would you like to use: tabs
√ Creating directory .\cutePuppyPics - done!
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
√ Downloading - done!
[INFO] Fetching starter template tabs (https://github.com/ionic-team/ionic2-starter-tabs/archive/master.tar.gz)
√ Downloading - done!
√ Updating package.json with app details - done!
√ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
√ Running command - done!
> git init
> git add -A
[ERROR] An error occurred while running git add -A (exit code 128):
        fatal: LF would be replaced by CRLF in .editorconfig

**Expected behavior:**

There should be no errors

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
C:\GitHub\ionic2>ionic start cutePuppyPics

? What starter would you like to use: tabs
√ Creating directory .\cutePuppyPics - done!
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
√ Downloading - done!
[INFO] Fetching starter template tabs (https://github.com/ionic-team/ionic2-starter-tabs/archive/master.tar.gz)
√ Downloading - done!
√ Updating package.json with app details - done!
√ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
√ Running command - done!
> git init
> git add -A
[ERROR] An error occurred while running git add -A (exit code 128):

        fatal: LF would be replaced by CRLF in .editorconfig

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This appears to be an issue with the CLI and not with the Ionic Framework itself, so I am moving this issue to ionic-team/ionic-cli. Please track the issue over there for updates.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2688
