### ISSUE TITLE
lazy loading error

### ISSUE THREAD

**Issue by kinglionsoft** [ionic-team/ionic#12732]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
```
Error: Uncaught (in promise): Error: Cannot find module '../pages/home/home.module'.
Error: Cannot find module '../pages/home/home.module'.
```

**Expected behavior:**

**Steps to reproduce:**

[https://github.com/kinglionsoft/ionic-lazy-loading](https://github.com/kinglionsoft/ionic-lazy-loading)

**Related code:**

1. app.module.ts
``` ts
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';
import { MyApp } from './app.component';
// import { HomePage } from '../pages/home/home';

@NgModule({
  declarations: [
    MyApp
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp
  ],
  providers: [
    StatusBar,
    SplashScreen,
    { provide: ErrorHandler, useClass: IonicErrorHandler }
  ]
})
export class AppModule { }

```
2. app.component.ts

``` ts
import { Component } from '@angular/core';
import { Platform, IonicPage } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage: any = 'HomePage';

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
    platform.ready().then(() => {
      statusBar.styleDefault();
      splashScreen.hide();
    });
  }
}
```
3. home.ts

```ts
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';

@IonicPage()
@Component({
  selector: 'page-home',
  templateUrl: 'home.html',
})
export class HomePage {
  constructor(public navCtrl: NavController, public navParams: NavParams) {
  }
}

```

4.  home.module.ts
``` ts
import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { HomePage } from './home';

@NgModule({
  declarations: [
    HomePage,
  ],
  imports: [
    IonicPageModule.forChild(HomePage),
  ],
})
export class HomePageModule {}

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Framework: 3.6.0
Ionic App Scripts: 2.1.3
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 6.11.0
OS Platform: Windows 10
Navigator Platform: Win32
```

Any help? Thanks in advance.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I cloned your repo and then built and ran your code without error. Here is the Ionic Info for the system I ran it on:

```
~/Projects/Ionic/ionic-lazy-loading (master): ionic info

cli packages: (/Users/kensodemann/Projects/Ionic/ionic-lazy-loading/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.3.0
    npm  : 5.3.0 
    OS   : macOS Sierra
```

The biggest difference I see is the OS. I will contact someone here who runs Windows and ask them if they have the same issue.

Thank you for using Ionic

**Comment by jgw96** [comment]
Hello all! I am unable to reproduce this issue on the latest stable build of windows 10. Here is my ionic info ```cli packages: (C:\Users\jgw96\Projects\ionic-lazy-loading\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.2.1
    npm  : 5.3.0 
    OS   : Windows 10 ```
At this time, since we are unable to reproduce, I am going to ask that you take this issue to the [forum](https://forum.ionicframework.com) or to our [slack channel](https://ionicworldwide.herokuapp.com/]. Thanks for using Ionic!

**Comment by kinglionsoft** [comment]
I found the point: I installed the dependencies not from registry.npmjs.org. Now, I reinstall dependencies from registry.npmjs.org and the problem fixed.

Thanks.

**Comment by sjjjjs** [comment]
i got the same issue, solved by using ```npm``` instead of ```cnpm``` install dependencies.
