### ISSUE TITLE
(click)= "" event on an ion-item causes slowdown and eventual freezing on compiled iOS app.

### ISSUE THREAD

**Issue by mikethm** [ionic-team/ionic#12737]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

(click)= "" event opening a modal or pushing a page to NavCtrl on an ion-item causes slowdown and eventual freezing on compiled ios app. Note: does not occur with android compiled on the same code, or on the web browser.

**Steps to reproduce:**
put a click event on an ion-item, so it will open either a modal or push to a navctrl
cycling opening and closing the modal 20 times will completely freeze a modern device (e.g. iphone 7) on a production compiled build.

tested on ionic 3.6.0

Note: adding tappable attribute avoids the slowdown and freeze.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? I tried this with a simple sample application but had no issues.  This was on an iPhone 7.

Also, please provide `ionic info` output after running `ionic info` from the terminal/command prompt while in your project's directory.

Thanks for using Ionic!

**Comment by dylanvdmerwe** [comment]
A simple repo would also be great. 

This looks like something @manucorporat would love to sink his teeth into when he can.

Issues like this are pretty NB to be fixed.

**Comment by kensodemann** [comment]
I am going to close this as something that I cannot duplicate.

If you can provide a sample application via GitHub or https://stackblitz.com that duplicates this issue I will be happy to reopen the issue and have a look.

**Comment by tuxd** [comment]
Yeah I had this problem

**Comment by kensodemann** [comment]
@tuxd - can you provide a sample application duplicating this issue?
