### ISSUE TITLE
Ignored attempt to cancel a touchmove event with cancelable=false

### ISSUE THREAD

**Issue by PanBachynskyi** [ionic-team/ionic#12730]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a warning: 
```
Ignored attempt to cancel a touchmove event with cancelable=false,
for example because scrolling is in progress and cannot be interrupted.
```
but after this warning app crashes.
Can I remove this warning?

**Expected behavior:**
All should be works.

**Steps to reproduce:**
Clicked on ion-item very fast. Also I used ion-range on this page.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 1.3.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.0.1

System:

    Node  : v8.1.2
    npm   : 5.3.0 
    OS    : macOS Sierra
    Xcode : Xcode 8.3.3 Build version 8E3004b 
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/cpeRJs?p=preview) or a simple demo application via a GitHub repo that demonstrates this issue? Thanks for using Ionic!

**Comment by kensodemann** [comment]
I see also that your version of the framework is old (`Ionic Framework    : ionic-angular 3.0.1`). You might want to give this a try with `3.6.0` and see if that fixes the issue.

**Comment by PanBachynskyi** [comment]
I have updated 'ionic-angular', but warning still present.
No, I can't provide demo, because my code is big. It just happens when I use Refresher and then very fast click on ion-item.

**Comment by kensodemann** [comment]
Thanks for trying the upgrade. I understand that your code is big, but have you tried duplicating your issue outside of your code in a smaller sample application? Thanks!

**Comment by PanBachynskyi** [comment]
Sorry, it was only warning. Bug was in other place.
Thanks!
