### ISSUE TITLE
v3.6 : Missing Life Cycle Event

### ISSUE THREAD

**Issue by tobiasmuecksch** [ionic-team/ionic#12731]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] feature request

**Current behavior:**
When you start swiping back from Page B to A (swiping the finger from left to right) the Event "ionWillLeave" is triggered. But when the user doesn't finish the swiping and instead swipes back so Page B stays active none of the known life-cycle event fires.

**Expected behavior:**
I'd suggest to either 
- add a new lifecycle event or 
- fire the ionViewDidEnter event

**Steps to reproduce:**
1. Start empty ionic project
2. Add two pages
3. Add functions for all life cycle events (see *Relevant code* below). 
4. Add a link from A to B
5. Start the app in Simulator or iPhone
6. Klick on the the from A to B
7. Swipe a bit from left to right (DO NOT LET GO THE FINGER)
8. Continue swiping in to the other direction so you'll stay in page B.
9. Observe console. You will notice that only ionWillLeave is triggered

**Related code:**

```
	ionViewWillEnter() {
		console.log('WILL ENTER');
	}

	ionViewDidEnter() {
		console.log('DID ENTER');
	}

	ionViewWillUnload() {
		console.log('WILL UNLOAD');
	}

	ionViewWillLeave() {
		console.log('WILL LEAVE');
	}

	ionViewDidLeave() {
		console.log('DID LEAVE');
	}

	ionViewDidLoad() {
		console.log('DID LOAD');
	}
```

**Other information:**
Why do you need this?!

Because I have to hide some elements during the swipe transition, because they cause some flickering during the transition.

The currently life cycle hooks only allow me to hide the elements when the swiping starts. But in case the user stays on the page they have to be shown again. The current life cycle hooks do not allow me to implement that second part.

**Ionic info:**

```
cli packages: (/Users/tmuecksch/Sites/XXX/app/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.1
    Node       : v8.4.0
    npm        : 5.3.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
```

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#300

**Comment by tobiasmuecksch** [comment]
Thanks. I really appreciate it. 😃 👍

**Comment by kensodemann** [comment]
You are very welcome!! :)
