### ISSUE TITLE
how to enable bouncing for ion-content with ionic v2.2.3 ?

### ISSUE THREAD

**Issue by mchenx** [ionic-team/ionic#12734]
I know there are a few issues related to this, but I didn't get any reply and I saw some one replied with a question months ago, he didn't get answered as well, so I put this in a new thread hope some one can see the title. Sorry about the duplication

Basically I cannot see bouncing is working in the ion-content of my project, is there any document regardign this? I didn't find anything about bouncing from ionicframework.com/docs 
Can any one help?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). 

Also, providing a sample application via GitHub that duplicates the issue you are having would be very helpful when you do so.

Thanks for using Ionic!
