### ISSUE TITLE
Can't change drag area size for menu

### ISSUE THREAD

**Issue by mifkys** [ionic-team/ionic#12738]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The menu starts to open when you drag it from 5-10% of the left edge.

**Expected behavior:**

Need ability to increase width of drag area size for menu

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-cordova       : 1.6.0-alpha.3abb0d6b (/Users/admin/apps/app/node_modules/@ionic/cli-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.5.0-alpha.3abb0d6b (/Users/admin/apps/app/node_modules/@ionic/cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.7.0-alpha.3abb0d6b (/Users/admin/apps/app/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI)               : 3.7.0-alpha.3abb0d6b (/Users/admin/apps/app/node_modules/ionic)

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    npm        : 3.10.10 
```

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#302

**Comment by mifkys** [comment]
Can I change this value in some way ? I need to do this in near future.

**Comment by kensodemann** [comment]
@mifkys - not sure off of the top of my head. I'll probably have time later to day to have a look. In the meantime, I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Someone in there may have tried doing this already.

**Comment by mifkys** [comment]
No one don't know how to change this on forum and slack :)

**Comment by kensodemann** [comment]
Digging around the code a bit I _think_ I found what you may need.

If you set the `maxEdgeStart` value you control how close to the edge the user has to be in order to open the menu.  Examples:

```html
<ion-menu [content]="content" [maxEdgeStart]="10">

<ion-menu [content]="content" [maxEdgeStart]="50">

<ion-menu [content]="content" [maxEdgeStart]="150">
```

So, if you have the first one, the user has to be within 10 pixels of the edge in order to slide open the menu, making it pretty tough to open but not impossible.

If you have the second one, the user has to be within 50 pixels of the edge. This is actually the default behavior, so this has no real effect.

If you have the third one, the user has to be within 150 pixels of the edge in order to open the menu, making it super easy to open the menu but also meaning the menu could be more easily opened in cases where the user would not want to because 150 pixels is actually pretty far from the edge.

Does this get you what you are looking to adjust?

**Comment by mifkys** [comment]
Working like a charm! Thanks! Need to add this to docs.

**Comment by kensodemann** [comment]
Excellent. I'll update the linked feature request to note that what is really needed is an update to the docs.

**Comment by bossjon** [comment]
@kensodemann, How to add `100%` `[maxEdgeStart]="'100%'"` or get page width in constructor then add?

**Comment by kensodemann** [comment]
@bossjon - if you create a sample application that demonstrates your issue and post it up on GitHub, I can take a look when I have a moment. I do not know off of the top of my head if %'s work or if it is just by pixel

**Comment by bossjon** [comment]
@kensodemann - here is sample application [https://github.com/bossjon/ionic3-swipe-area-menu-subpages](https://github.com/bossjon/ionic3-swipe-area-menu-subpages) or if you not have a time to git you can use [plnkr](https://plnkr.co/edit/bR7JlTrBKsuKWUGXK42g?p=preview)

Try to open new page and close by swiping. Now i set `[maxEdgeStart]="400"`, but subPage is not closing in `400px` only in default `80px` why? or any config for `swipeBack` area ? thanks!

Ps: and see how to set `[maxEdgeStart]="'100%'"`. 
If you see Viber app and Telegram, where you can open `side menu` from everywhere and close `SubPages` too, for this i ask you about set `[maxEdgeStart]="'100%'"` to side menu!

**Comment by kensodemann** [comment]
@bossjon - looking at the code, the `maxEdgeStart` value only deals with pixels, so the answer to your how to do a percent question is that currently, you cannot.

For the child page, I see this behavior:

- if I try closing by sliding from the very left, it works fine
- if I try sliding from further out, it opens the menu

This seems like a bug to me. My suggestion would be to wait until after v4 is released and if this is still an issue in v4 write up a bug at that time.
