### ISSUE TITLE
ion-item-sliding does not work on IOS with a lot of list items

### ISSUE THREAD

**Issue by uj** [ionic-team/ionic#12749]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using ionic-angular 3.6.0
Using ionic 3.9.2

With IOS;
use ion-item-sliding with 10 items in the list, it works great.
use ion-item-sliding with 100+ items in the list, it doesn't work at all.

With ANDROID;
use ion-item-sliding with 10 items in the list, it works great.
use ion-item-sliding with 100+ items in the list, it still works.

**Expected behavior:**
ion-item-sliding should work with 100+ items in the list on an IOS device

**Steps to reproduce:**
Create a list of 100+ items, try to swipe on an iphone, nothing happens.

For Ionic V1 issues - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

For Ionic issues - http://plnkr.co/edit/cpeRJs?p=preview
-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
cli packages:

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 browser 4.1.0
    Ionic Framework    : ionic-angular 3.6.0

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by uj** [comment]
Actually, installing the wkwebview 
https://github.com/ionic-team/cordova-plugin-wkwebview-engine instead of 
using the default uiwebview seems to have fixed the issue completely.  
Evidently, wkwebview is much better at handling large lists than 
uiwebview is.

Josh



------ Original Message ------

**Comment by kensodemann** [comment]
Excellent! Glad to hear that your issue is fixed.

**Comment by SnehaSSD** [comment]
After Adding the wkwebview cordova plugin also still the performance is not fine on older iOS device's (iPad Mini iOS 9.3). there is some improvements in the scrolling part. But the ion-item-sliding part is still effected.
