### ISSUE TITLE
Problem with NavController events when open tabbed page again from menu

### ISSUE THREAD

**Issue by mifkys** [ionic-team/ionic#12740]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When I open page with tabs subpages again from menu (SplitPane) I got next order of navController events for active subpage:

> subpage ionViewDidLoad()
> subpage ionViewWillUnload()

Events `ionViewDidLeave` and `ionViewWillLeave` not fired. They fired only when I change current tab to another.

**Expected behavior:**

I think events must be fired in next correct way:

> ionViewWillUnload()
> ionViewDidLoad()

and also must be fired event `ionViewDidLeave` and `ionViewWillLeave`.
In current version I can't do some things (unsubscribe important events) on `ionViewWillUnload` event because it fired after `ionViewDidLoad`!

**Steps to reproduce:**

Open page with tabs subpages from menu then open this page again from menu.

**Related code:**

MenuPage.html
```
<ion-split-pane>
  <ion-menu [content]="content">
    <ion-list>
    	<ion-item *ngFor="let p of pages" menuClose detail-none (tap)="openPage(p)">
	    	<ion-icon name="{{p.icon}}" item-start></ion-icon>
        {{p.title}}
      </ion-item>
    </ion-list>
  </ion-menu>
  <ion-nav #content main [root]="rootPage"></ion-nav>
</ion-split-pane>
```

MainPage.html
```
<ion-content>
	<ion-tabs #mainTabs ion-fixed>
	  <ion-tab [root]="page1Page"></ion-tab>
	  <ion-tab [root]="page2Page"></ion-tab>
	</ion-tabs>
</ion-content>
```
page1Page.ts
```
ionViewDidLoad() {
    console.log('ionViewDidLoad page1Page');
    this.events.subscribe('page:subevent', (format, period) => {
     ...
    });
  }
ionViewWillLeave() {
  	console.log('ionViewWillLeave page1Page'); // not fired when open mainPage again
  }
  ionViewDidLeave() {
  	console.log('ionViewDidLeave page1Page'); // not fired when open mainPage again
  }
  ionViewWillUnload() {
  	console.log('ionViewWillUnload page1Page');
	this.events.unsubscribe('page:subevent');
  }
```

console output:
>ionViewDidLoad page1Page // opened first time
>// opened second time
>ionViewDidLoad page1Page
>ionViewWillUnload page1Page

After this actions page not subscribed to `page:subevent` event.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    npm        : 3.10.10 
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue with the page not having subscriptions?

Each load of the page should be its own instance of the page, not a shared instance. So it should work as such:

pageOne-Instance1 loaded, instance 1 subscriptions made
pageOne-Instance2 loaded, instance 2 subscriptions made
pageOne-instance1 unloaded, instance 1 subscriptions unsubscribed

At that point, though, the instance 2 subscriptions should remain subscribed as they exist on an entirely different object than the instance 1 subscriptions.

**Comment by mifkys** [comment]
It's not about subscription. It's about order of NavController events. Subscription it's only example what works uncorrected with current behavior.

**Comment by kensodemann** [comment]
Also, my sample app is getting the ionViewWillLeave and ionViewDidLeave LC events when I click on the same menu item twice, so please include an example of that issue in your sample app as well.

**Comment by mifkys** [comment]
Do you use tabs subPages on this page?

**Comment by kensodemann** [comment]
It would be best if you would provide a GitHub repo showing how this is causing issues in your application.

After discussing this issue with one of the developers who is familiar with the nav system coding and specifically the lifecycle events I have marked this as something to be addressed in version 4.x of Ionic.

**Comment by mifkys** [comment]
Here I am again. I created repo (modified Tabs template): https://github.com/mifkys/ionic3-nav-problems and record video with wrong order of ionView events: https://youtu.be/FZe9Rm8Mc5w

**Comment by kensodemann** [comment]
Thank you. This will be very helpful when we revisit navigation and the lifecycle events.

**Comment by danbucholtz** [comment]
Hi - we'll take a look at this ASAP.

Thanks,
Dan

**Comment by danbucholtz** [comment]
Hi, this should be fixed. Please comment if it does not. It will be in the next release on Wed.

```
npm install ionic-angular@3.7.1-201710060319
```

Thanks,
Dan
