### ISSUE TITLE
Menu List item lines disappearing on hover in UWP

### ISSUE THREAD

**Issue by wacton** [ionic-team/ionic#12748]
**Ionic version:** 
[ ] **1.x** 
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
On a UWP app using a the menu, there seems to be a hover effect that causes the lines in the list to disappear. Strange thing is, it only seems to happen when you move your mouse pointer from the bottom to the top of the list. Moving from the top to the bottom doesn't do the same thing, in that case there's only a momentary disappearing of the line.
![image](https://user-images.githubusercontent.com/2299141/29696549-08c14d84-898d-11e7-8b5c-3381159f8e30.png)

**Expected behavior:**
Moving the mouse pointer up or down over the items should react the same.

**Steps to reproduce:**
- Create new app with super template
- Add Windows platform
- Add windows-target-version = 10 preference to config.xml
- Run on Windows
- Open menu
- Move mouse pointer over items from bottom to top
- Repo:  [https://github.com/wacton/ionic-menu](https://github.com/wacton/ionic-menu)

**Ionic info:**:

```
cli packages: (C:\src\tests\super\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.1.2 ios 4.3.1 windows 4.4.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v7.8.0
    npm               : 4.2.0
    OS                : Windows 10
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind posting a repo we could use to reproduce this issue? Thanks!

**Comment by wacton** [comment]
Hi,

Sure thing, created one here using the menu starter [https://github.com/wacton/ionic-menu](https://github.com/wacton/ionic-menu)

It looks like it only happens on slightly larger lists. It normally happens to items more or less in the middle of the list.

Thanks!
