### ISSUE TITLE
Ionic3 document viewer plugin not work

### ISSUE THREAD

**Issue by Tusharbalar** [ionic-team/ionic#12744]
**Ionic Info**

```
tushar@localhost:~/.../Ionic3/CornerStone/cornerstone-parent$ ionic info

cli packages: (/home/tushar/workspace/Ionic3/CornerStone/cornerstone-parent/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.3 browser 4.1.0
    Ionic Framework    : ionic-angular 3.5.3

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.2
    npm               : 3.10.10
    OS                : Linux 4.11

```

I used [Document Viewer](https://ionicframework.com/docs/native/document-viewer/) plugin in my app.
it gives error: **Error in SitewaertsDocumentViewer.viewDocument():  Missing Command Error**

Test with this command: **ionic serve and  ionic cordova run browser** 
![err screenshot](https://user-images.githubusercontent.com/4783557/29668928-6eff3e28-88ff-11e7-89f5-0b65672027b7.png)

**Comment by AmitMY** [comment]
Please move this issue to `ionic-native`. This repo is about the framework itself

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I have moved this issue to ionic-team/ionic-native. Please track the issue over there.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-native#1922
