### ISSUE TITLE
Using @IonicPage (lazy loading) pages loads by default a page

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#12742]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Hi, we are using from the beginning `LazyLoading` and the new `IoniPage` decorator in our app. Now we think we have discovered a new bug or something we simple don't understand.

Our `app.module.ts` is something like that:
```
...
@NgModule({
    declarations: [
        MyApp
    ],
    imports: [
        BrowserModule,
        HttpModule,
        IonicModule.forRoot(MyApp, {
            preloadModules: true
      })
    ],
    bootstrap: [
        IonicApp
    ],
    entryComponents: [
        MyApp
    ],
....
```
our app.component.ts is something like that

```
@Component({
    templateUrl: 'app.html'
})
export class MyApp {
    rootPage: string;

    constructor(public platform: Platform, public statusBar: StatusBar, public splashScreen: SplashScreen) {
        this.initializeApp();
    }

    initializeApp() {
        this.platform.ready().then(() => {
            // Okay, so the platform is ready and our plugins are available.
            // Here you can do any higher level native things you might need.
            this.statusBar.styleDefault();
            this.splashScreen.hide();

            // this.rootPage = 'MainPage';
        });
  }
}
```
as you can see the `MainPage` would not be loaded it is commented, so at startup we would have a blank page and the constructor of `MainPage` is not loaded. Now we uncomment `this.rootPage = 'MainPage';` and live reload does reload the page, and now the `MainPage` is shown, but the problem is the constructor is called twice time.
Next step we do, we re comment the `this.rootPage = 'MainPage';` the page does a reload and page is still loaded and the constructor is loaded one time. So this is a very strange thing!

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/lib/node_modules)
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:
    Cordova CLI : 7.0.1 

local packages:
    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:
    Android SDK Tools : 26.0.2
    Node              : v6.11.2
    npm               : 5.3.0 
    OS                : Linux 4.10
```

**Comment by kensodemann** [comment]
Your `app.component.ts` should look more like this:

```ts
@Component({
    templateUrl: 'app.html'
})
export class MyApp {
    rootPage = 'MainPage';

    constructor(public platform: Platform, public statusBar: StatusBar, public splashScreen: SplashScreen) {
        this.initializeApp();
    }

    initializeApp() {
        this.platform.ready().then(() => {
            // Okay, so the platform is ready and our plugins are available.
            // Here you can do any higher level native things you might need.
            this.statusBar.styleDefault();
            this.splashScreen.hide();
        });
  }
}
```

That is, set the main page right away, don't wait until the platform is ready.

Here is what is happening with various scenarios and the code you have now:

**No rootPage Defined**

When you initially load the app, you get no page because you didn't set one

**Set rootPage after Platform Ready**

Works OK on first load.

Subsequent reloads while on that page (including live-reload) do this:

1. URL is /#/main
2. nav loads said url, so MainPage construction is scheduled
3. platform ready eventually fires
4. rootPage changes from undefined to 'MainPage', so MainPage is scheduled for construction again
5. MainPage gets constructed twice

Or something like that. I haven't verified the exact firing on that

**Comment out setting of rootPage in device ready**

Now MainPage loads once, but this is because of the URL


So if you just set the rootPage right away, everything is fine.

**Comment by mburger81** [comment]
I think this wasn't before so and in this case it is a small breaking change. 
I tried also loading the page on top which is the default scenario but I had the same result, or at least I think so. I'll test it again tomorrow when I'm back in office. 
But honestly there is a reason why we do this we have to wait for platform ready to get work willenter logic in page. We need cordova plugins loaded for our page guards. 
If this is not a valid scenario we have to add an empty stupid loading page and wait there until platform is ready and set only now the root page to LoginPage. 
But as I mentioned before, I think in the default way the problem persist but I have to check it again and let you know tomorrow. 

Thx
