### ISSUE TITLE
bug: Interpolated strings not automatically updated on

### ISSUE THREAD

**Issue by Muralilive** [ionic-team/ionic#12743]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Interpolated strings not automatically updated on variable change</span>

<span is-issue-template></span>

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
