### ISSUE TITLE
FAB & AdMob Pro do not coexist properly

### ISSUE THREAD

**Issue by juanqui66** [ionic-team/ionic#12746]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x**3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using an FAB in the bottom, in a page where we have enabled in the foot an AdMob Pro banner and in that same page, when we enter it (in event ngOnInit) we load an interstitial of AdMob Pro, when closing the interstitial, the FAB is hidden under the banner.

This only happens in IOS. Android works properly and the FAB is above the banner.

In IOS, in addition to hiding the FAB, the bottom of the page is also covered by the banner. It is as if after showing the interstitial, the size of the page happens to occupy the entire screen space of the mobile, without realizing that at the bottom of it has been loaded a banner.

**Page loaded with bottom banner, bottom FAB and non interstitial loaded yet (good looking):**

![img_0037](https://user-images.githubusercontent.com/28297694/29685576-324bcd72-8916-11e7-87d3-6b94dceeba2d.jpg)

**After loading and closing the interstitial (or video):**

![img_0034](https://user-images.githubusercontent.com/28297694/29685719-9630d044-8916-11e7-829e-1962387f478f.jpg)

**Expected behavior:**
The FAB should be above the banner, as in the first image.

**Steps to reproduce:**
It has already been described (I think).

**Related code:**
N/A.

**Other information:**

*package.json:*

ionic-native/admob: ^3.13.1
cordova-plugin-admobpro: ^2.29.21

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages: (/.../node_modules)

    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 1.3.12
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.0

System:

    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    Node       : v6.9.4
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b

P.D.: Excuse my English.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?


Thanks for using Ionic!

**Comment by juanqui66** [comment]
Hello! Sorry for the delay, but this is the first time I uploaded a project to GitHub. I hope everything is correct. 

In README.md I have put some small indications. Any questions you have, let me know.

Greetings.

**Comment by kensodemann** [comment]
Thank you for providing that. I have duplicated the issue.

I do not believe this is a framework issue but is either an issue with the plugin or some additional coding is required to deal with iOS.

I have found a couple of issues pertaining to this on the plugin's GitHub site:
https://github.com/floatinghotpot/cordova-admob-pro/issues/38
https://github.com/floatinghotpot/cordova-admob-pro/issues/94

You can also try asking about this on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

I will move this issue to `ionic-team/ionic-native`. Please post any updates that you may have over there.

Thank you for using Ionic!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-native#1928
