### ISSUE TITLE
"Error: No provider for ElementRef!" when adding IonicApp as Provider for Unit Testing w/ TestBed

### ISSUE THREAD

**Issue by amnonjw** [ionic-team/ionic#12755]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When performing unit testing using Karma + Jasmin + TestBed, "Error: No provider for ElementRef!" appears even though I have no direct usage of ElementRef in my code. 

output from `ng test --sourcemap=false`:
```
Error: No provider for ElementRef!
        at injectionError (webpack:///C:/Ionic/QRtest/~/@angular/core/@angular/core.es5.js?:1437:86)
        at noProviderError (webpack:///C:/Ionic/QRtest/~/@angular/core/@angular/core.es5.js?:1475:12)
        at ReflectiveInjector_._throwOrNull (webpack:///C:/Ionic/QRtest/~/@angular/core/@angular/core.es5.js?:2976:19)
        at ReflectiveInjector_._getByKeyDefault (webpack:///C:/Ionic/QRtest/~/@angular/core/@angular/core.es5.js?:3015:25)
        at ReflectiveInjector_._getByKey (webpack:///C:/Ionic/QRtest/~/@angular/core/@angular/core.es5.js?:2947:25)
        at ReflectiveInjector_.get (webpack:///C:/Ionic/QRtest/~/@angular/core/@angular/core.es5.js?:2816:21)
        at DynamicTestModuleInjector.get (ng:///DynamicTestModule/module.ngfactory.js:257:146)
        at DynamicTestModuleInjector.getInternal (ng:///DynamicTestModule/module.ngfactory.js:394:48)
        at DynamicTestModuleInjector.NgModuleInjector.get (webpack:///C:/Ionic/QRtest/~/@angular/core/@angular/core.es5.js?:3783:44)
        at resolveDep (webpack:///C:/Ionic/QRtest/~/@angular/core/@angular/core.es5.js?:11245:45)
```

**Expected behavior:**
there will be no error and the tests will be successful, and peace will fall on the Earth

**Steps to reproduce:**
By elimination, I reduced the problem to:
* MyApp constructor includes IonicApp as a Provider. In my use case I need this for choosing the proper response to pressing the hardware back button in Android - I need to access _modalPortal and _overlayPortal, so I can tell if the user wants to go back from a modal or an alert
* In TestBed configuration I add IonicApp as a Provider

**Related code:**
UPDATE: [Example in GitHub repo](https://github.com/amnonjw/Tester/tree/IonicApp-ElementRef)

**app.spec.ts (relevant section)**
```
describe('Component: Root Component', () => {
 
    beforeEach(async(() => {
 
        TestBed.configureTestingModule({
 
            declarations: [MyApp],
 
            providers: [
                StatusBar,
                SplashScreen, 
                BarcodeScanner,
                IonicApp,
```

**app.component.ts**
```
import { Component } from '@angular/core';
import { Platform, IonicApp } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

import { HomePage } from '../pages/home/home';
@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage:any = HomePage;

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen, ionicApp: IonicApp) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      statusBar.styleDefault();
      splashScreen.hide();
    });
  }
}
```

**Other information:**
**Ionic info:**
Update: this is the output for the test project I uploaded to GitHub (the original post had android platform, which appears to be irrelevant to the bug
```
cli packages: (C:\Ionic\Tester\node_modules)
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:
    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:
    Node : v6.11.1
    npm  : 5.3.0
    OS   : Windows 10
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by amnonjw** [comment]
I added a link to GitHub repo
[](https://github.com/amnonjw/Tester/tree/IonicApp-ElementRef)

**Comment by kensodemann** [comment]
Thank you for providing some example source.

I don't see exactly where you are using the injected `IonicApp` in your code, perhaps it is more complex in your actual application, but in the sample application you can just mock the `IonicApp` in your test as such:

```ts
class IonicAppMock { }
...
  beforeEach(async(() => {

    TestBed.configureTestingModule({

      declarations: [MyApp],

      providers: [
        StatusBar,
        SplashScreen,
        { provide: IonicApp, useClass: IonicAppMock }
      ],

      imports: [
        IonicModule.forRoot(MyApp)
      ]

    }).compileComponents();

  }));
```

If that will not work for you, you may want to ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). 

Thanks for using Ionic!

**Comment by amnonjw** [comment]
Yes - this works for me. Thank you.

**Comment by kensodemann** [comment]
Excellent!! Glad to hear it.
Thank you for using Ionic!
