### ISSUE TITLE
Ionic info doesn't report global package cordova

### ISSUE THREAD

**Issue by Jun711** [ionic-team/ionic#12754]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Ionic info doesn't report global package cordova

**Expected behavior:**
Expect to see cordova version

**Steps to reproduce:**
running ionic info in a ionic project directory, but it doesn't report global packages.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.4
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v7.3.0
    npm  : 4.2.0 
    OS   : macOS Sierra
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Have in installed any platforms in your project?

If I just do an `ionic start myApp blank`, let it run, `cd myApp` and then do `ionic info`, I get basically what you get.

But if I then do `ionic cordova platform add ios` I will then get way more info. Like this:

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    Node       : v8.3.0
    npm        : 5.3.0 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
```

Based on the output you have, though, I would say you haven't actually added any platforms yet.

Thank you for using Ionic

**Comment by Jun711** [comment]
The platforms were added before I updated ionic. I will re-add the platforms and see.

it seems that moving from cordova 6.5 and ionic 3.4 to ionic 3.6, there seems to be change in command such ionic prepare has become ionic cordova prepare.

Where can I review all the changes in commands?

**Comment by kensodemann** [comment]
I usually just do `ionic --help` from the command line. It is terse but very useful, IMO. If I need more info, I then [hit the docs](http://ionicframework.com/docs/cli/).

There is also [Change Log Entry](https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#300-2017-05-09) that may be useful for this purpose.

Hope that helps. Let me know how things go after you re-add the platforms. If you still don't have the right info from `ionic info` I will move this over to the ionic-cli repo.

**Comment by Jun711** [comment]
I can see global packages after I re-add the platforms. thanks
