### ISSUE TITLE
Toggle-button overlays overlaying div

### ISSUE THREAD

**Issue by JaneDawson** [ionic-team/ionic#12757]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm struggling with a strange issue with the toggle-component.
On my pages I've got a pink, almost full-page-sized help div, which overlays the page content. The user can close this help div.

This works fine on all pages, except of one where I'm using the toggle component. The toggle button comes to the front on iOS devices (iOS 10.3.3), as you can see in the following picture. It's not like this all the time, but if you slided to the left or right for example, or move the page just a little bit to the left or right, then it may happen.

![Image Toggle issue:](http://i.imgur.com/W6ty5m6.png)

I'm using the [ionic2-super-tabs](https://github.com/zyra/ionic2-super-tabs), in case that might be important. And the page where the issue occurs is one of the main tabs.

Everything works fine on `ionic serve` (iOS and Android) and on android devices.

I tried to use z-index in different ways, but I don't get it running as expected. Would be gratefull vor any idea where to look at.

**Expected behavior:**
Toggle stays behind the help div and doesn't come to the front. Like all other components do.

**Steps to reproduce:**
Create Ionic 3 Project -> use toggle component -> add an overlaying div (code below).

**Related code:**
Here's my code. Tried different things (everything with `!important` as well, as you can see...).

**html**

```
<ion-content>

  <div class="helpDiv" *ngIf="showHelp">
    Helptext
  </div> 

  <ion-list no-lines class="profile_list">
    
    <ion-item no-padding>
      <ion-label>Label</ion-label>
      <ion-toggle [(ngModel)]="shopOpenToggle" class="toggle_class"></ion-toggle>
    </ion-item>

  </ion-list>
  
</ion-content>
```

**CSS**

```
    .toggle-icon{
        z-index: 3!important;
        position: relative;
    }

    .toggle-inner{
        z-index: 3!important;
        position: relative;
    }

    .toggle_class{
        z-index: 3!important;
        position: relative;
    }

    .helpDiv{
        position: absolute;
        z-index: 9999!important;
    }
```

**Ionic info:**
```

    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v8.2.1
    npm               : 5.3.0
    OS                : Windows 10
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? I tried your code, but out of context like that, it didn't reproduce your issue.

Thanks for using Ionic!

**Comment by JaneDawson** [comment]
Hi @kensodemann. Thank you for looking into this.
I helped myself by just not showing the toggle if the overlaying help-div is shown. This isn't a real solution, but it's good enoug for now...
