### ISSUE TITLE
Delay for validation CSS classes on ion-item

### ISSUE THREAD

**Issue by DavidTalamona** [ionic-team/ionic#12753]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.6.0**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Validation CSS classes for inputs inside list items are not properly applied (delayed by one input event) to their containging item.

**Expected behavior:**
Validation CSS classes should be applied suddenly to the input field itself, the containing item and the form.

**Steps to reproduce:**
http://plnkr.co/edit/s8GHhetlXV3hJMJy5dIn?p=preview

The form field has `[minlength="4"]`, so focus the form field and enter 4 characters. It is still red (invalid).

If you inspect the HTML you'll see the `ion-input` and the `form` are updated and have `.ng-valid` classes but the `ion-item` is not yet updated.

If you enter another character or blur the field, the `ion-item` gets updated, too.

It's the exat same behaviour the other way around - if you delete some characters and drop below the 4 required ones.

**Related code:**
```
<ion-list>
	<form>
		<ion-item>
			<ion-input type="text" minlength="4" [(ngModel)]="username" name="username" required></ion-input>
		</ion-item>
	</form>
</ion-list>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\...)
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:
    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:
    Node : v6.9.1
    npm  : 4.0.2
    OS   : Windows 10
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am closing this because I believe it is a repeat of #12588 & (especially) #12503, but your example is really good so I will make sure those issues link back here. Please follow those issues for further updates.

Thank you for using Ionic
