### ISSUE TITLE
v3.6.0 icon does not display in <ion-option> under <ion-select>

### ISSUE THREAD

**Issue by jing-zhou** [ionic-team/ionic#12756]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
icon does not display in "ion-option"
**Expected behavior:**

icon should display in "ion-option"
**Steps to reproduce:**

**Related code:**

```
<ion-item>
    <ion-label>{{'concat' | translate}}</ion-label>
    <ion-select [(ngModel)]="contact.cat" interface="popover">
      <ion-option *ngFor="let cat of concat.cats" [value]="cat">
        <ion-icon item-left name="pin"></ion-icon>
        {{concat.getIcon(cat)}}
      </ion-option>
    </ion-select>
  </ion-item>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/home/wjz/ion/pcion/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.2.1
    npm  : 5.3.0 
    OS   : Linux 4.4

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by jing-zhou** [comment]
Hi, please follow this link for the sample application:
https://github.com/jing-zhou/ion-issue-12756

take a look of  "about" page

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us and for providing an example repo.

It turns out that this is not something that we have ever supported. The underlying select option just passes text to the overlay that gets presented, so there is no way for it to grab an icon.

Thank you for using Ionic

**Comment by lumega** [comment]
[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/GyTug.png

This worked for me.

using CSS to modify the inner span in the button tag of each option, removing radius and assigning a brackground image

the options keep the same order, and that is why the attribute selector worked for me

    .alert-radio-icon{
        border-radius: 0 !important;
        border: none !important;
        height: 40px !important;
        width: 40px !important;
        background-size: 40px 40px !important;
        background-repeat: no-repeat ;
    }

        [id^="alert-input-"][id$="-0"] .alert-radio-icon{
            background-image: url("../assets/images/menu/flag_ni.png") !important;
        }
         [id^="alert-input-"][id$="-1"] .alert-radio-icon{
            background-image: url("../assets/images/menu/flag_gt.png") !important;
        }
        .alert-radio-inner{
            background-color: transparent !important;
        }

**Comment by wangxiaomo** [comment]
@lumega can't use origin ionic icons with your hack.
