### ISSUE TITLE
Ionic serve does not recognise platform anymore

### ISSUE THREAD

**Issue by EmmanuelFRANCOIS** [ionic-team/ionic#12758]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When launching Ionic serve with the following command:
ionic serve --platform android --browser chrome
Platform reports that app is running on a desktop instead of a mobile...
this.platform.is('core') returns true
this.platform.is('mobile') returns false
this.platform.is('tablet') returns false
this.platform.is('phablet') returns false
This makes testing in browser difficult...

**Expected behavior:**
Platform should report:
this.platform.is('core') returns false
this.platform.is('mobile') returns true
this.platform.is('tablet') returns true
this.platform.is('phablet') returns true

**Steps to reproduce:**

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
cli packages: (C:\Users\OSCAR\AppData\Roaming\npm\node_modules)
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2
global packages:
    Cordova CLI : 7.0.1
local packages:
    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0 windows 5.0.0
    Ionic Framework    : ionic-angular 3.6.0
System:
    Android SDK Tools : 25.2.5
    Node              : v6.11.2
    npm               : 5.0.3
    OS                : Windows 7

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This appears to be an issue with the Ionic app scripts, so I am moving this issue to the `ionic-team/ionic-app-scripts` repo.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1195
