### ISSUE TITLE
Error: EPERM: operation not permitted installing ionic 3 and cordova

### ISSUE THREAD

**Issue by amirensit** [ionic-team/ionic#12762]
I tried to install ionic 3 and cordova in the first time in my desktop
`npm install -g ionic cordova` shows this error 

`Error: EPERM: operation not permitted` 
[https://img11.hostingpics.net/pics/377440ionicErreur.png](url)
even running windows powerShell in administration mode
Any idea please

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

I know of some things you can try:

1. make sure you are running as administrator when installing globally
2. try each separately and see if it is an issue with one or the other (`npm install -g cordova`, `npm install -g ionic`)
3. if those both fail, try installing something else globally (npm install -g gulp-cli, or something like that)
4. if only one fails, check the global install area and see if some clean-up is required

Thanks for using Ionic!

**Comment by melani08** [comment]
couldn't understand clearly
