### ISSUE TITLE
Cannot specify color map with base color and contrast color in variable $colors

### ISSUE THREAD

**Issue by hkericb** [ionic-team/ionic#12766]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The following SASS compilation error is shown.
```
[16:06:52]  sass: src/theme/variables.scss, line: 62
            (base: #55acee, contrast: #ffffff) isn't a valid CSS value.
```

**Expected behavior:**
SASS compilation with no error is expected.

**Steps to reproduce:**

1. Open `variables.scss` to replace the variable $color with the following:
```
$colors: (
  primary:    #488aff,
  secondary:  #32db64,
  danger:     #f53d3d,
  light:      #f4f4f4,
  dark:       #222,
  twitter: (
    base: #55acee,
    contrast: #ffffff
  )
);
```
2. Run `ionic serve`

**Ionic info:**

```
cli packages: (/Users/ericb/git/ionic-project/node_modules)

    @ionic/cli-utils  : 1.8.0
    ionic (Ionic CLI) : 3.8.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.0
    Cordova Platforms  : android 6.2.1 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.3

System:

    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    Node       : v7.9.0
    npm        : 4.2.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am closing this since it is not an Ionic Framework issue. Your code contains invalid SASS.

As an example, if we were to simplify what you have to just the basics and run in through SASS directly (no Ionic involved at all):

This is valid:

```css
$foo: #121212;

.test {
        background: $foo
} 
```

this is not:

```css
$foo: (base: #121212, contrast: #ffffff);

.test {
        background: $foo
} 
```

Thank you for using Ionic
