### ISSUE TITLE
ion-slides bug

### ISSUE THREAD

**Issue by mm580486** [ionic-team/ionic#12767]
hi guys

i have a problem on ion-slides , i build a slider on ios and works exactly but on android not working exactly ( for sample when i focus on input box slides beginning to move next page automatic !!!! )

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please. Be sure to include a sample application via GitHub that demonstrates the issue you are having.

Thanks for using Ionic!
