### ISSUE TITLE
How to view or read a pdf, doc and ppt file in ionic mobile app

### ISSUE THREAD

**Issue by dinesh93** [ionic-team/ionic#12768]
Hi All, 

**IONIC PDF,DOC,PPT Viewer**

I am developing an ionic application. In the I want the use read the file in application.

The file document's are give from the DB as url , when click it  need to open the file.

What i want is the list of document is show in a screen if click any one of the document is it will show as a separate view

Any one please give me some suggest for this.

Thanks
Dinesh

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
