### ISSUE TITLE
Icon of radio box

### ISSUE THREAD

**Issue by Muneem** [ionic-team/ionic#12764]
How to change icon of radio box in ionic 2? I cant find way to change its icon. In ionic1 i have used like this
<ion-radio icon="icon ion-checkmark-circled"></ion-radio> 

It apply checkmark. I want same stylinh in ionic2. but i am unable to find so. Is this support available in ionic 2?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
