### ISSUE TITLE
Cannot build, error at copy-www-build-step

### ISSUE THREAD

**Issue by tsupol** [ionic-team/ionic#12778]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Cannot build using the command **`ionic cordova build ios` or build using XCode**. It appears like the Cordova's `Copy www directory` process got killed'. Noted that I tested this on fresh ionic template without doing anything fancy. 

Here are more details
```
PhaseScriptExecution Copy\ www\ directory /Users/tonsu/Library/Developer/Xcode/DerivedData/MyApp-guoiiessxhrkleexghgevznwdrwo/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyApp.build/Script-304B58A110DAC018002A0835.sh
    cd /Users/tonsu/Dev/Ionic/IonicExample/platforms/ios
    /bin/sh -c /Users/tonsu/Library/Developer/Xcode/DerivedData/MyApp-guoiiessxhrkleexghgevznwdrwo/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyApp.build/Script-304B58A110DAC018002A0835.sh
```

```
/Users/tonsu/Library/Developer/Xcode/DerivedData/MyApp-guoiiessxhrkleexghgevznwdrwo/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyApp.build/Script-304B58A110DAC018002A0835.sh: line 2:  1116 Killed: 9               node cordova/lib/copy-www-build-step.js
Command /bin/sh failed with exit code 137
```

**Expected behavior:**
Being able to build and run the app or emulator

**Steps to reproduce:**

- sudo npm install -g cordova ionic
- ionic start myApp tabs
- ionic cordova platform add ios
- ionic cordova platform build ios

**Related code:**
I tested this on fresh ionic templates without doing anything fancy. 

**Other information:**
I tried re-installing Ionic, Cordova, Xcode, Node and even downgraded Cordova and Node but I still got the same error. It's was fine before I re-install my mac.

**Ionic info:**

```
cli packages: (/Users/tonsu/.nvm/versions/node/v8.4.0/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 2.0.0 
    Node              : v8.4.0
    npm               : 5.3.0 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this is a support question rather than a framework issue I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
