### ISSUE TITLE
Weird Transition behavior if next page is longer than view height

### ISSUE THREAD

**Issue by sooonism** [ionic-team/ionic#12779]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If we have `PageA` and `PageB`, 
`PageA` have a button to trigger `this.navCtrl.push(PageB)`. 
if `PageB` with content longer than `view height`, There will be a weird transition behavior (the whole screen will slide to right by total white screen, then only display `PageB`.)

If `PageB` with the content shorter than `view height`, the transition is fine.

**Expected behavior:**
Normal `this.navCtrl.push()` transition behavior.

**Steps to reproduce:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages: (/Users/xuanxi/.nvm/versions/node/v6.9.1/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 6.4.0 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.1.2 ios 4.1.1
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.0 
    Node       : v6.9.1
    npm        : 3.10.8 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
