### ISSUE TITLE
How can run ionc 3 on server?

### ISSUE THREAD

**Issue by Swapniltdatalogy** [ionic-team/ionic#12772]
**Ionic version:**  (check one with "x")

[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by faraazc** [comment]
@Swapniltdatalogy This is not an issue. I would request you to submit your queries in a ionic forum (forum.ionicframework.com) or stackoverflow.

thanks

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this is a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
