### ISSUE TITLE
Status Bar in Splashscreen

### ISSUE THREAD

**Issue by yhugow** [ionic-team/ionic#12771]
Hi Ionic,

Is there any ways to change the color of status bar during splashscreen?

Thannks
Yugo

**Comment by AmitMY** [comment]
In the `config.xml` segment [here](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-statusbar/) you can set the color before anything loads.

**Comment by yhugow** [comment]
It doesn't work. I shows only after the splash screen loads. 
I want is during the splash screen.

Is it possible to add statusbar code in splashscreen plugins?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
