### ISSUE TITLE
Add support for custom animations with ion-slides

### ISSUE THREAD

**Issue by irundaia** [ionic-team/ionic#12777]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
For my current project, I'm working with a ion-slides component. The interaction designers have decides that we should have a specific kind of animation for our onboarding slides component. (A combination of fading and panning). Ionic however only supports the standard Swiper.js animations.

Would it be possible to add the possibility to create custom animations for the ion-slides component?

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#305
