### ISSUE TITLE
Ionic's polyfills.modern.js should have a polyfill for Math.hypot()

### ISSUE THREAD

**Issue by mnasyrov** [ionic-team/ionic#12781]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
I have an issue while running under android emulator 5: when I click/tap on a button or other tappable element I've got an error in a logcat console:
```
I/chromium( 3569): [INFO:CONSOLE(133)] "Uncaught TypeError: undefined is not a function", source: file:///android_asset/www/index-cordova.html (133)
```

After some investigation I found that a reason is in `ionic-angular/tap-click/ripple.ts`: there is a using of `Math.hypot()` function which was introduced in es2015 (as I see), but a system webview of Android 5 does not support it. At the same time, documentation of Ionic polyfills (https://github.com/ionic-team/ionic/blob/master/scripts/polyfill/readme.md) states that `polyfills.modern.js` supports Android 5.0+ devices.

As a workaround I had to switch to using a more common `polyfills.js` instead of `polyfills.modern.js`.

**Expected behavior:**
Include a polyfill for `Math.hypot()` to `polyfills.modern.ts` to be compatible with WebView of Android 5.

**Steps to reproduce:**
Ionic version: 3.6.0
Bundle an app with `polyfills.modern.ts` and try to click on a button running on an emulator. The emulator can be created by a command:
```
avdmanager -v create avd --name nexus4 --device "Nexus 4" --package "system-images;android-21;google_apis;x86" --abi google_apis/x86 --sdcard 200M
```

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Android 5.0+ devices use the updateable from the play store chrome powered webview. This means that these devices support all the modern es6 features (including this method on the Math object) that Chrome the browser does. Im thinking that whats going on here is that the stock 5.0 image you ran here was running an old version of the chrome webview and just needed to be updated through the play store. On an actual android 5.0 device (which should be updated as the webview auto updates) do you run into the same issue?

**Comment by mnasyrov** [comment]
I've no Android 5.0 devices for testing. However, it would be nice to have a support for stock emulator's images for CI reasons.

**Comment by gkappel** [comment]
Even if the webview can be updated through the play store frequently it is not so you are stuck with the original/stock webview

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. 

Thanks for using Ionic!

**Comment by mnasyrov** [comment]
@kensodemann Could you please to tell me why exactly this issue was closed? Is it fixed or Ionic team won't fix it? 
It is not good to close an issue without a resolution just because it was created long time ago.

**Comment by kensodemann** [comment]
@mnasyrov - we are not going to fix it in v3.

If it is a big enough issue after the next major release of Ionic we may address it at that time, but for now we are going through and closing out v3 issues that will not be addressed. As we get closer to the v4 release, these will likely all be closed so we can better manage the v4+ issues going forward.

**Comment by mnasyrov** [comment]
@kensodemann, sounds reasonable, thank you.
