### ISSUE TITLE
Can we use bootsrtap and ionic together, if not then why, Please let me know the reason.

### ISSUE THREAD

**Issue by spitech** [ionic-team/ionic#12788]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by mhartington** [comment]
Hi there! So this doesn't appear to be an issue with the framework itself, rather a question, so I'm going to close it. Please post your question on the [Ionic Forum](https://forum.ionicframework.com) instead.
