### ISSUE TITLE
App crashes after switching to another app and locking the screen

### ISSUE THREAD

**Issue by loffler** [ionic-team/ionic#12785]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.6.0**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Any Ionic app crashes after switching to another app and then locking the screen. After that, when I unlock the screen and try to open my Ionic app from the recent apps list, it makes a clean start (with splashscreen), as if it weren't running before.

**Expected behavior:**
The app should continue running (or waiting) in the background. When I open it in recent apps list, the app shoud be shown immediately - in the same state I left it in.

**Steps to reproduce:**
1. run any Ionic app, e.g. with `ionic start crashTest blank`,
2. switch to any other application,
3. lock the screen using hardware screen-lock button and wait 1-2 seconds,
4. unlock the screen and switch back to your Ionic app
5. the app makes clean start instead of being resumed

**Related code:**
- none

**Other information:**
- This bug appears on my Huawei Honor 6 (H60-L04) with Android 6.0. My Moto G hasn't any problems at all.

- When I debug the app's WebView, there is no relevant output at the moment of crash, only message 'Device disconnected' appears. However, I identified some relevant messages in the [adb logcat](https://pastebin.com/KP3hJMDy) debug output (line 340).

- The app doesn't crash if I lock the screen while having the app in foreground. 
- Neither does the app crash, if I open web browser by tapping on a link in my app and then lock the screen.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/home/user/.npm-global/lib/node_modules)
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:
    Cordova CLI : 7.0.1 

local packages:
    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:
    Android SDK Tools : 26.0.2
    Node              : v6.11.2
    npm               : 5.1.0 
    OS                : Linux 4.9
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

After internal discussions about this issue, we believe that on your Huawei Honor 6 phone, the Android OS is purging your application if it is in the background when you lock the phone. This is not something that the framework controls, it is something the Android OS controls.

Thank you for using Ionic

**Comment by DAKZH** [comment]
On my emulator also
