### ISSUE TITLE
Firebase Phone Authentication

### ISSUE THREAD

**Issue by CarlosMacedo** [ionic-team/ionic#12787]
Hi there,

**Ionic version:**  (check one with "x")
[ ] **1.x** 
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request 

**Current behavior:**
Firebase is one of the most commonly used tools in ionic, according to a survey you did yourself. I'm using it on my startup too.

The firebase phone authentication feature does not work on ionic 3. Given that, it expects a http (or https) directory and the ionic directory is file: //assets/index.html.
It work on the 'ionic serve' because it's in the browse. But does not work on the device.

Do you create support phone authentication (firebase)?

If you can not, that's fine. But if you can, how much time can you make?
I need the answer to decide whether to continue using Ionic on my startup

**Expected behavior:**
A plugin that makes firebase phone authentication work on ionic3.

**Steps to reproduce:**
1- create a blank project
2- Add firebase to project: https://firebase.google.com/docs/web/setup
3- add phone authentication to project: https://firebase.google.com/docs/auth/web/phone-auth

Thanks.

**Comment by AmitMY** [comment]
Are you using WK? I think it does use http.

**Comment by CarlosMacedo** [comment]
No. I don't know what WK is. Is the wkwebview plugin?
That? Https://github.com/apache/cordova-plugin-wkwebview-engine

In the link says that it's only installable in IOS. But, I need to android.

**Comment by AmitMY** [comment]
Yeah that is what I meant. 
If you need it for android I am not sure, sorry.

**Comment by Sampath-Lokuge** [comment]
@CarlosMacedo Did you try this article from Jorge: https://stackoverflow.com/a/45922881/1077309

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by CarlosMacedo** [comment]
Hi, jgw96

I have already tested and done all the tutorials (there are few) and found that Ionic is incompatible.
I created the Issue just to know if it plans to implement any such plugin.

Thanks. Sorry.

**Comment by Sampath-Lokuge** [comment]
@CarlosMacedo Plugin is already there: https://github.com/silverio/cordova-plugin-firebase

See this too: https://github.com/silverio/cordova-plugin-firebase#phone-authetication-ios-only

**Comment by CarlosMacedo** [comment]
Hi Sampa, thanks for the reply.

We can talk here? https://forum.ionicframework.com/t/phone-authentication-firebase-in-ionic-with-cordova-plugin-firebase/102058

Have you been able to use the phone authentication in ionic?
So far I have not found anyone who has succeeded.

Sajtempler is also trying (from the link above).

**Comment by Sampath-Lokuge** [comment]
@CarlosMacedo I didn't use.But it seems working fine on PWA. You can see discussion here on this article too.See the comments section: https://javebratt.com/firebase-phone-authentication/

**Comment by Sampath-Lokuge** [comment]
@CarlosMacedo Here you can see the commercial template too.That means that guy did it with `Ionic 3` no? See this on market place: https://market.ionic.io/starters/ionfirebaseaccountkitphoneauth

**Comment by CarlosMacedo** [comment]
This one was available 3 hours ago.
Thanks Sampath!!

I'll look at this one. He used some trick with Facebook AccountKit.

**Comment by Sampath-Lokuge** [comment]
Yep, Good luck and hope you share your experience here too: https://stackoverflow.com/questions/45922763/authentification-whith-phone-number-with-firebase-in-ionic3/45922881#45922881
