### ISSUE TITLE
Alert prompt input lost focus (and keyboard glitch) after transition complete

### ISSUE THREAD

**Issue by davidef** [ionic-team/ionic#12784]
**Ionic version:**  (check one with "x")
[X] **3.5+**

**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
Alert prompt input lost focus (and keyboard glitch) after transition complete

**Expected behavior:**
Alert prompt input retain focus after transition complete and keyboard remain open

**Steps to reproduce:**
http://plnkr.co/edit/aYrg3PIL49XRQxQlyPnc?p=preview

**Other information:**
Testing with ionic-angular 3.4.0 it seems to be working as expected

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I have marked this as something to look into after the release of Ionic v4.

Thank you for using Ionic

**Comment by kensodemann** [comment]
Note to others looking at this, to see the difference in behavior:

1. open http://plnkr.co/edit/aYrg3PIL49XRQxQlyPnc?p=preview
2. press "Show Popup" and note the input in the alert is **not** focused
2. change ionic-angular version to 3.4.0 (in system.config.js)
3. press "Show Popup" and note the input in the alert is focused

**Comment by JasonAsmk** [comment]
This probably happens because the input is focused on ionViewDidEnter when the input element isn't ready yet. It's kind of a race condition and maybe in 3.4.0 the input had the time to init before getting focused.
