### ISSUE TITLE
Unable to add a cordova plugin from local folder

### ISSUE THREAD

**Issue by Khusbu** [ionic-team/ionic#12783]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On adding a cordova plugin to my app from local folder I get below error:

`
> cordova plugin add ../local-cordova-plugin --save
✖ Running command - failed!
[ERROR] An error occurred while running cordova plugin add ../local-cordova-plugin --save (exit code 1):

        
        Error: Failed to get absolute path to installed module

`

**Note**: This error occurs if I add it after I have added plugins from npm repository or adding any platform to my app. If I had it first, before adding any other plugin or platform, it gets added successfully.

**Expected behavior:**
I should be able to add a local cordova plugin to my ionic app at any stage.

**Steps to reproduce:**

`$ ionic cordova plugin add ../local-cordova-plugin` 

Please note you should add the local cordova plugin after adding a platform or a plugin from npm repository to your ionic app.

**Related code:**

**Other information:**
[Stackoverflow link for similar issue](https://stackoverflow.com/questions/43856285/failed-to-get-absolute-path-to-installed-module)  I have used flags like `--nofetch, --force, --noregistry, --searchpath` but it didn't resolve my issue. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v7.0.0
    npm               : 3.10.8 
    OS                : macOS Sierra
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by Khusbu** [comment]
I am developing a cordova plugin which I can't share as its in a private repo. I am trying to add this plugin to my ionic project. Please note that after I make changes to `platforms/android/AndroidManifest.xml` file of my ionic project and then try to add my plugin, it throws above error. It got added successfully before I made any changes to AndroidManifest file but not after that even after I removed my changes. Also, I don't face any such issue in my cordova sample app when I try to add my same local plugin.

**Comment by kensodemann** [comment]
Thank you for the reply. I understand that your code is in a private repo. Would you be able to provide perhaps a simple sample application that loads a local plugin that demonstrates the issue? The plugin could just be a simple stub plugin that does nothing, just so long as it demonstrates the same issue. That way we can verify the issue and any potential fix.

Since this is a CLI related issue, I am moving this issue to `ionic-team/ionic-cli`. Please post any follow-up you have to the `ionic-team/ionic-cli` issue.

Thank you for using Ionic.

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2709
