### ISSUE TITLE
onDidDismiss return the modal/alert itself

### ISSUE THREAD

**Issue by dfa1234** [ionic-team/ionic#12789]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

Not sure if its bug or feature, but I would like that onDidDismiss of a modal return the modal, that is, I can chain like this:

```javascript
let modalRecipients = this.modalCtrl.create(...).onDidDismiss(...).present()
```

Your source code concerned (onDidDismiss return void):
```javascript
export declare class OverlayProxy {
    _app: App;
    _component: any;
    _config: Config;
    _deepLinker: DeepLinker;
    overlay: Overlay;
    _onWillDismiss: Function;
    _onDidDismiss: Function;
    constructor(_app: App, _component: any, _config: Config, _deepLinker: DeepLinker);
    getImplementation(): Overlay;
    /**
     * Present the modal instance.
     *
     * @param {NavOptions} [navOptions={}] Nav options to go with this transition.
     * @returns {Promise} Returns a promise which is resolved when the transition has completed.
     */
    present(navOptions?: NavOptions): Promise<any>;
    dismiss(data?: any, role?: string, navOptions?: NavOptions): Promise<any>;
    /**
     * Called when the current viewController has be successfully dismissed
     */
    onDidDismiss(callback: (data: any, role: string) => void): void;
    createAndPresentOverlay(navOptions: NavOptions): Promise<any>;
    /**
     * Called when the current viewController will be dismissed
     */
    onWillDismiss(callback: Function): void;
}

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello everyone! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!
