### ISSUE TITLE
webapp使用浏览器后退键没法后退上级页面

### ISSUE THREAD

**Issue by baobz** [ionic-team/ionic#12794]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

我使用ionic开发webapp,因为在Android手机上有返回的按键效果类似于浏览器的返回按钮,但是我在点击返回时url变化了,页面没有返回上一级页面,我家在页面使用的是lazy-load

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Can you please edit your issue to describe the current behavior in English, and to provide the `Ionic info` output in the appropriate section?

Also, please provide a sample application via GitHub that demonstrates the issue you are having.

Thank you for using Ionic


Google Translate says: I use the web development webapp, because the Android phone has a return button similar to the browser's return button, but I click on the return url changes, the page did not return to the previous page, my home in the page using lazy- load

**Comment by baobz** [comment]
I'am so sorry, I am still improving my English. I downloaded a case from the website and solved the problem, I quit using lazy loading.
Thanks!
----- 原始邮件 -----
发件人：Ken Sodemann <notifications@github.com>
收件人：ionic-team/ionic <ionic@noreply.github.com>
抄送人：baobz <baobz@sina.cn>,  Author <author@noreply.github.com>
主题：Re:_[ionic-team/ionic]_webapp使用浏览器后退键没法后退上级页面_(#12794)
日期：2017年09月01日 19点10分

Hello! Thank you for opening an issue with us!
Can you please edit your issue to describe the current behavior in English, and to provide the Ionic info output in the appropriate section?
Also, please provide a sample application via GitHub that demonstrates the issue you are having.
Thank you for using Ionic
Google Translate says: I use the web development webapp, because the Android phone has a return button similar to the browser's return button, but I click on the return url changes, the page did not return to the previous page, my home in the page using lazy- load

&mdash;

**Comment by vellengs** [comment]
@baobz 
you can register "setupBrowserBackButtonBehavior"  on app.component.ts
private setupBrowserBackButtonBehavior(): void {
        window.onpopstate = (event) => {
            if (this.ionicApp) {
                let activePortal: any =
                    this.ionicApp._loadingPortal.getActive() ||
                    this.ionicApp._modalPortal.getActive() ||
                    this.ionicApp._toastPortal.getActive() ||
                    this.ionicApp._overlayPortal.getActive();

                if (activePortal) {
                    activePortal.dismiss(); 
                    return;
                }
            }
        };
    }

**Comment by vellengs** [comment]
webapp使用浏览器后退键没法后退上级页面.
It means "can not go back using BrowserBackButton  on web Application".

**Comment by kensodemann** [comment]
Thank you for the responses. If I understand this conversation correctly, it sounds like you have found a solution. I am going to close this issue for now but will be happy to reopen it if the solutions being discussed do not work for you.

**Comment by baobz** [comment]
Thank you, I quit the method of lazy loading and It's working now
----- 原始邮件 -----
发件人：vellengs <notifications@github.com>
收件人：ionic-team/ionic <ionic@noreply.github.com>
抄送人：baobz <baobz@sina.cn>,  Mention <mention@noreply.github.com>
主题：Re:_[ionic-team/ionic]_webapp使用浏览器后退键没法后退上级页面_(#12794)
日期：2017年09月04日 16点48分

@baobz

you can register "setupBrowserBackButtonBehavior"  on app.component.ts

private setupBrowserBackButtonBehavior(): void {

window.onpopstate = (event) => {

if (this.ionicApp) {

let activePortal: any =

this.ionicApp._loadingPortal.getActive() ||

this.ionicApp._modalPortal.getActive() ||

this.ionicApp._toastPortal.getActive() ||

this.ionicApp._overlayPortal.getActive();
            if (activePortal) {
                activePortal.dismiss(); 
                return;
            }
        }
    };
}


&mdash;
