### ISSUE TITLE
 adb install 

### ISSUE THREAD

**Issue by IssaGithub** [ionic-team/ionic#12793]
Hi All, 

having Problem with 
adb install platforms/android/build/outputs/apk/android-debug.apk

Getting error message:
Windows Script host
row:90
sign 6
error: Bezeichner erwartet
Code 800A03F2
Source: Kombilierungsfehler in Microsoft JScricpt

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am closing this as it is not an Ionic issue. Rather, it appears to be an issue with the Android dev tools.

Thank you for using Ionic

**Comment by IssaGithub** [comment]
But it's an Android Project within ionic!

2017-09-01 13:03 GMT+02:00 Ken Sodemann <notifications@github.com>:
