### ISSUE TITLE
Ionic documentation links not working

### ISSUE THREAD

**Issue by nitinpund** [ionic-team/ionic#12796]
Don't know where to post this issue, so adding it here.

from few days, we are not able to access the ionic documentation links, all links are broken

![ionic](https://user-images.githubusercontent.com/4629680/29968256-696eda24-8f38-11e7-8e92-58cbee4edaef.png)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Hmmm, interesting. I just went to that exact URL (https://forum.ionicframework.com/t/navigation-stack-needs-at-least-one-root-page/90576) and it loaded fine.

I will leave this open for a bit while I ask around to see if anyone has any ideas.

Thank you for using Ionic

**Comment by nitinpund** [comment]
I m going to close this issue as it is related to our server firewall, Thanks a lot.
