### ISSUE TITLE
<ion-datetime> can not display on ios9

### ISSUE THREAD

**Issue by tincyho** [ionic-team/ionic#12792]
**Ionic version:**  (check one with "x")
ionic 3.7.0

**I'm submitting a ...**  (check one with "x")
bug report

**Current behavior:**
the `<ion-datetime>` can not display on ios9. but on ios10, it works well.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

I added an `<ion-datetime>` to a sample app I had laying around and it worked just fine in iOS9 and iOS10 (both times on the simulator as I do not have an actual iOS 9 device to run this on).

Thanks for using Ionic!

**Comment by tincyho** [comment]
Thank you.
I have found the reason. On iOS9, I must use the ISO datetime format. like "2017-09-04T10:11:00Z". So it can work well.

**Comment by kensodemann** [comment]
Glad to hear you found the solution. I will close this then.
