### ISSUE TITLE
Tabs and Pages don't cache (lazy loaded)

### ISSUE THREAD

**Issue by rory-pickering** [ionic-team/ionic#12795]
**Ionic version:**  (check one with "x")
[x] **3.6**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
I have lazy loaded all my tabs and page components.
Now when i go from a tab, to a page, when hitting back the tab re-instantiates losing the information.
Just flipping between tabs is ok, but navigating away and coming back causes the issue. 
I've highlighted the issue in this video
[![youtube](https://img.youtube.com/vi/6rrSxeWZau4/0.jpg)](https://www.youtube.com/watch?v=6rrSxeWZau4)

**Expected behavior:**
The view shouldn't be destroyed and re-created, it should remain in memory (well it actually does, but then on enter destroys and recreated. it doesnt get destroyed before you go back so to speak)

**Steps to reproduce:**
Use lazy loaded tabs and navigate to pages through the NavController.push

**Ionic info:**
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.0-201707262225
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1 
    ios-sim           : 6.0.0 
    Node              : v6.9.4
    npm               : 3.10.10 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.1 Build version 8E1000a

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! We will look into that.

Thank you for using Ionic

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

I attempted to duplicate your issue using a [tab test bed application](https://github.com/kensodemann/test-bed-tabs) but when my app goes to children or to children of children (can be done from about page), only the `ionPageDidEnter()` is called and not the `ionPageDidLoad()` indicating the view did not re-load only re-enter.

Thanks for using Ionic!

**Comment by rory-pickering** [comment]
Hi Ken,

Thanks for the response, I have stripped back the app and created a repo for you here https://github.com/rory-pickering/IonicNavBugExample

you can search for an artist, hit the artist page, then when you hit back the issue appears.

These are the logs i get from `ngAfterViewInit` and `ionViewDidEnter`

APP LOAD
`SEARCH:ngAfterViewInit`
`SEARCH:ionViewDidEnter`
SEARCH THEN RETURN
`SEARCH:ionViewDidEnter`
`SEARCH:ngAfterViewInit`
`SEARCH:ionViewDidEnter`

**Comment by rory-pickering** [comment]
AHHH I'm not using the `ion-navbar` and i'm manually calling `navCtrl.pop` if i just chuck the `ion-navbar` in the issue doesn't happen! but with `navCtrl.pop` the issue is there

**Comment by rory-pickering** [comment]
So after looking in navbar i see the only difference was stopping the event propagation
changing 
`<a href="#" (click)="navCtrl.pop();"><i class="fi flaticon-back-arrow"></i></a>`
to
`<a href="#" (click)="$event.preventDefault();$event.stopPropagation();navCtrl.pop(null, null);"><i class="fi flaticon-back-arrow"></i></a>` fixed the issue. 

Thanks for your time looking into this, and sorry for wasting your time 👎  🤒

**Comment by kensodemann** [comment]
Thank you for the responses. I am glad to hear that this issue has been solved.
