### ISSUE TITLE
Any ETA about stencil update?

### ISSUE THREAD

**Issue by HugoHeneault** [ionic-team/ionic#12807]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

I just saw your [impressive presentation ](https://www.youtube.com/watch?v=UfD-k7aHkQE)at the Polymer summit, and I'd like to know when we'll be able to start testing / working with ionic-v4.

Do you guys have some ETA? In the upcoming weeks or late 2017?

Thanks a lot for all your awesome job, keep going :)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us and for the kind comments!

We do not have an official release schedule for Ionic v4, but it is our primary focus at this time.

Thank you for using Ionic

**Comment by HugoHeneault** [comment]
Thanks for your reply! Even without any release schedule, would it be in the upcoming weeks or months? :)
