### ISSUE TITLE
Error during installation of ngx-translate

### ISSUE THREAD

**Issue by gtzinos** [ionic-team/ionic#12804]
Hi,

i am following your docs to install ngx translate but it returns my the following error message

```
├── UNMET PEER DEPENDENCY @angular/common@4.1.3
├── UNMET PEER DEPENDENCY @angular/core@4.1.3

```

Ionic version: 3.9.2
Template: Blank

**Comment by gtzinos** [comment]
After a search i found that you can't use HttpClient before angular version 4.3.0 (I am using 4.1.3 on your latest blank template)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Please provide a link for the guide you are following.

Thank you for using Ionic

**Comment by gtzinos** [comment]
This is the guide. https://ionicframework.com/docs/developer-resources/ng2-translate/

Thank you again!

**Comment by kensodemann** [comment]
Thank you for the reply. If your `package.json` is similar to the project where you are trying to install the Google Maps plugin, then everything _should_ be fine.

This isn't really an Ionic Framework issue so I am going to close this. This looks more like an npm issue or an issue with the various plugins you are trying to install.

There are a couple of things you can try, though:

1. remove the node_modules subdirectory and the `package-lock.json` file (if it exists) and redo the `npm install` command
2. ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).
3. you could try opening an issue in the ngx-translate repo
