### ISSUE TITLE
Bug: ionViewDidEnter not is fired after it becomes the active page with Lazy Load

### ISSUE THREAD

**Issue by allansduarte** [ionic-team/ionic#12805]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ionViewDidEnter should fire after the page becomes active, but after the implementation of Lazy Load this does not happen anymore. ionViewDidEnter is firing before the page becomes active.

**Expected behavior:**
ionViewDidEnter: Fired when entering a page, after it becomes the active page. ([http://blog.ionic.io/navigating-lifecycle-events/](http://blog.ionic.io/navigating-lifecycle-events/))

**Steps to reproduce:**

In an Ionic project with Lazy Load implemented. It is possible to generate the two-page code with the CLI generators version 3.6.0:

**Related code:**

```
@IonicPage()
@Component({
  selector: 'ib-page-a',
  templateUrl: 'a.html',
})
export class APage {

  constructor(private _navCtrl: NavController) { }

  goToBPage() {
    this._navCtrl.setRoot('BPage');
  }

}
```

```
@IonicPage()
@Component({
  selector: 'ib-page-b',
  templateUrl: 'b.html',
})
export class BPage {

  ionViewDidEnter() {
    console.log('I am called before being displayed / become active');
  }

}
```

**Other information:**
Sometimes we have performance issues with Ionic, even using its best practices. Now, with Lazy Load on Ionic 3, application startup has improved wonderfully! But page startup is slow. With this fix, I believe it is possible to take key performance measures.

**Ionic info:**

```
cli packages:

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 6.4.0 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.0.0 ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node  : v6.11.1
    npm   : 3.10.10 
    OS    : OS X Yosemite
    Xcode : Xcode 7.2.1
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I did some testing by setting a breakpoint at line 776 of `nav-controller-base` and looking at the state of things at the time the breakpoint is hit. It appears that this works fine when using `this._navCtrl.push('BPage');` (that is, the page has fully transitioned and is active and then the breakpoint is hit) whereas it seems to be hit early when ``this._navCtrl.setRoot('BPage');` is used.

We will take a look at this.

Thank you for using Ionic

**Comment by allansduarte** [comment]
@kensodemann The ionViewDidEnter is called, but it seems that the transition time is disregarded when running `this._navCtrl.setRoot ('BPage');` or `this._navCtrl.setRoot ('BPage', null, { animate: false });`

Note that when `this.navCtrl.setRoot ('BPage', null, { animate: true, duration: 2000 });` is executed; the transition time seems to be considered. (The duration attribute only exists to see the page transition.)

The critical point is when using `this._navCtrl.setRoot ('BPage');` and not being able to use the Ionic lifecycle.

**Comment by kensodemann** [comment]
Thank you for the extra information.

**Comment by kabus202** [comment]
@kensodemann any update on this? I have the same problem pushing to a new TabsPage page with:

` this.navCtrl.push('aNewTabsPage')
`
After the push, clicking on a random page of 'aNewTabsPage' will trigger ionViewDidEnter before entering.
