### ISSUE TITLE
ion-button medium attribute not working 

### ISSUE THREAD

**Issue by gtzinos** [ionic-team/ionic#12806]
Hi,

I am using your attribute "medium" on my button but it doesn't change the size, but it works with large attribute.

`<button ion-button medium>Button text</button>`

Example Code:
https://github.com/ionic-team/ionic-preview-app/blob/master/src/pages/buttons/sizes/sizes.html

Platform Tested: Browser (Chrome)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

According to [the documentation](http://ionicframework.com/docs/components/#button-sizes), the defined attributes are `small` and `large` and if you don't include those you get the default button size. This is also reflected in the code. If we had a `medium` attribute it would logically just be the default and not change anything anyhow.

The demo source is perhaps mildly confusing in that it includes a `medium` attribute which doesn't actually exist.

Thank you for using Ionic
