### ISSUE TITLE
Error using TypeScript greater than 2.5.1

### ISSUE THREAD

**Issue by feliperfmarques** [ionic-team/ionic#12800]
**Ionic version:**
[X] **3.x**

**I'm submitting a ...**
[X] bug report

**Current behavior:**
I got the following errors bellow when updated TypeScript to version greater than 2.5.1. 

PS: Version 2.5.0 work's fine.

**Related code:**

```
Typescript Error

Class 'Tabs' incorrectly implements interface 'NavigationContainer'. Types of property 'parent' are incompatible. Type 'NavControllerBase' is not assignable to type 'NavController'. Types of property 'popTo' are incompatible. Type '(indexOrViewCtrl: any, opts?: NavOptions, done?: () => void) => Promise<any>' is not assignable to type '(page: string | Page | ViewController, params?: any, opts?: NavOptions, done?: Function) => Promi...'. Types of parameters 'done' and 'opts' are incompatible. Type 'NavOptions' is not assignable to type '() => void'. Type 'NavOptions' provides no match for the signature '(): void'.


node_modules/ionic-angular/components/tabs/tabs.d.ts

151 export declare class Tabs extends Ion implements AfterViewInit, RootNode, ITabs, NavigationContainer {

```

```
Typescript Error
Class 'NavControllerBase' incorrectly implements interface 'NavController'. Types of property 'popTo' are incompatible. Type '(indexOrViewCtrl: any, opts?: NavOptions, done?: () => void) => Promise<any>' is not assignable to type '(page: string | Page | ViewController, params?: any, opts?: NavOptions, done?: Function) => Promi...'. Types of parameters 'done' and 'opts' are incompatible. Type 'NavOptions' is not assignable to type '() => void'. Type 'NavOptions' provides no match for the signature '(): void'.


node_modules/ionic-angular/navigation/nav-controller-base.d.ts

20 export declare class NavControllerBase extends Ion implements NavController {
```

**Expected behavior:**

Build without got this errors.

**Steps to reproduce:**

Update TypeScript version to > 2.5.1 and run ```ionic cordova build/run``` or ```ionic serve```.

**Ionic info:**:

```
cli packages:

    @ionic/cli-plugin-proxy : 1.4.6
    @ionic/cli-utils        : 1.9.2
    ionic (Ionic CLI)       : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    Node       : v6.9.1
    npm        : 3.10.8
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
```

**Comment by AmitMY** [comment]
The dependency is `"typescript": "~2.3.3",` which means `2.3.x` so 2.5.1 is not supported currently.

**Comment by aks0020** [comment]
#12716 might be related to this fixed but will be released with v4.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to close this as typescript `2.5.1` is not currently supported, and since @danbucholtz rolled in a fix for the underlying issue with the inconsistent type definitions.

Thank you for using Ionic

**Comment by anjildhamala** [comment]
I don't think this is just limited to typescript version. I do have 2.3.4 typescript and 3.1.8 ionic-app-script version and I'm still seeing this issue. In addition to 'tabs incorrectly implementing navigationController interface', i am also seeing 'navControllerBase incorrectly implementing navController interface' and couple of rxjs issues where subject is incorrectly extending observable and websocket incorrectly extending anonymousSubject error. My 'rxjs' version is '5.4.0'.
