### ISSUE TITLE
Error: Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by mtaita** [ionic-team/ionic#12809]
Hi All 
 I am having the following error when i run this command ionic cordova build android --prod

Error: Error encountered resolving symbol values statically. Calling function 'makeParamDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in C:/wamp64/www/new-smart-mauzo/node_modules/ion2-datetime-picker/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in C:/wamp64/www/new-smart-mauzo/node_modules/ion2-datetime-picker/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in C:/wamp64/www/new-smart-mauzo/node_modules/ion2-datetime-picker/node_modules/@angular/core/src/di/opaque_token.d.ts

Please any suggestions.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

This may also be an issue for `ionic-team/ionic-cli` but I suggest trying the forum first.

One question I have: what happens with a basic `ionic serve` command?

Thanks for using Ionic!

**Comment by mtaita** [comment]
Thanks 
I will do so
