### ISSUE TITLE
Ionic2: Http sends ERROR :{"isTrusted":true}

### ISSUE THREAD

**Issue by mzl1988** [ionic-team/ionic#12819]
Ionic2: Http sends ERROR: {"_body":{"isTrusted":true},"status":200,"statusText":"Ok","headers":{},"type":3,"url":null}

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out please.

When doing so please provide a sample application via GitHub that demonstrates the issue you are having.

Thanks for using Ionic!
