### ISSUE TITLE
bug: @ionic-native/http has a wrong pluginRef

### ISSUE THREAD

**Issue by howrujh** [ionic-team/ionic#12818]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>@ionic-native/http has a pluginRef as 'cordovaHTTP'. but this one is used by cordova-plugin-http. not cordova-plugin-advanced-http.

pluginRef should change to cordova.plugin.http</span>

<span is-issue-template></span>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This seems to be an issue with `ionic-team/ionic-native` so I am moving it to that repo. Please provide any follow-up over there.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-native#1945
