### ISSUE TITLE
Change the default color of input component's typing area line's color

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic#12814]
**Ionic version:** 
[X ] **3.x**

[X ] feature request

**Current behavior:**

There is no `SaaS` variable for changing the typing area line's color (Please see the image below).

**Expected behavior:**

We need a `SaaS` variable for this. 

**Steps to reproduce:**

Here is the [Ionic input component](http://ionicframework.com/docs/api/components/input/Input/)

Let's say I need to change it to `Blue` color.

```
 <ion-item>
    <ion-input type="password" placeholder="Password Input"></ion-input>
  </ion-item>
```

Plunker : http://plnkr.co/edit/iKS6Jd?p=preview

![Alt Text](https://i.stack.imgur.com/4m1If.png)

**Ionic info:** 

cli packages: (C:\Users\lokuge\AppData\Roaming\npm\node_modules)

>     @ionic/cli-utils  : 1.9.2
>     ionic (Ionic CLI) : 3.9.2
> 
> global packages:
> 
>     Cordova CLI : 7.0.1
> 
> local packages:
> 
>     @ionic/app-scripts : 2.1.4
>     Cordova Platforms  : android 6.2.3
>     Ionic Framework    : ionic-angular 3.6.0
> 
> System:
> 
>     Android SDK Tools : 25.2.5
>     Node              : v6.10.0
>     npm               : 3.10.10
>     OS                : Windows 8.1

**Comment by seed880505** [comment]
@Sampath-Lokuge Have a try this one $list-ios-border-color/$list-md-border-color

This variable is used across many components , but at leat your can use it for the moment.

**Comment by kensodemann** [comment]
Hello everyone! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#308

**Comment by Sampath-Lokuge** [comment]
Thanks @kensodemann

**Comment by Sampath-Lokuge** [comment]
@seed880505 I have tried many ways.But unfortunately, none of them worked. On this use case where we have to consider so many things. Those are validation color changes (error and Succesful) and it must support all the platforms (iOS/Androids/windows) and more. So very complex use cases. So we would like to have this feature out of the box from the Ionic Team.
