### ISSUE TITLE
next method inside provider doesn't work

### ISSUE THREAD

**Issue by mokrea** [ionic-team/ionic#12815]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
method next() doesn't work inside a provider.

**Expected behavior:**
this.checklistObserver.next(true) works inside a provider and send a message to home.ts code:
myservice.checklistUpdates().subscribe(data => {
  console.log(data);
});

**Steps to reproduce:**
ionic start ObservableTest blank
ionic g provider MyService
 ionic serve -l -s -c

**Related code:**
home.ts
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { MyServiceProvider } from '../../providers/my-service/my-service';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, myservice: MyServiceProvider) {
    myservice.addItem("asd");
    
  }

  ionViewDidLoad() {
   this.myservice.checklistUpdates().subscribe(data => {
           console.log(data);
    });
  }

}

```
my-service.ts
```
import { Injectable } from '@angular/core';
import 'rxjs/add/operator/map';
import {Observable} from 'rxjs/Observable';
/*
  Generated class for the MyServiceProvider provider.

  See https://angular.io/docs/ts/latest/guide/dependency-injection.html
  for more info on providers and Angular DI.
*/
@Injectable()
export class MyServiceProvider {

  checklist: any;
  checklistObserver: any;

  constructor() {
    console.log('Hello MyServiceProvider Provider');
    this.checklist = Observable.create(observer => {
     this.checklistObserver = observer;
   });
  }

  addItem(item): void {

    this.checklistObserver.next(true);

  }

}

```

**Ionic info:** 

```
cli packages: (/Users/marcosmachado/.nvm/versions/node/v8.4.0/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.4
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.4.0
    npm  : 5.3.0 
    OS   : macOS Sierra


Uncaught (in promise): TypeError: undefined is not an object (evaluating 'this.checklistObserver.next')
addItem@http://localhost:8100/build/main.js:113:31
HomePage@http://localhost:8100/build/main.js:60:26
createClass@http://localhost:8100/build/vendor.js:11254:34
createDirectiveInstance@http://localhost:8100/build/vendor.js:11082:48
createViewNodes@http://localhost:8100/build/vendor.js:12445:72
createRootView@http://localhost:8100/build/vendor.js:12350:20
callWithDebugContext@http://localhost:8100/build/vendor.js:13565:47
create@http://localhost:8100/build/vendor.js:10271:60
_viewInit@http://localhost:8100/build/vendor.js:43064:50
http://localhost:8100/build/vendor.js:42856:32
onInvoke@http://localhost:8100/build/vendor.js:4508:43
run@http://localhost:8100/build/polyfills.js:3:4458
http://localhost:8100/build/polyfills.js:3:14079
onInvokeTask@http://localhost:8100/build/vendor.js:4499:47
runTask@http://localhost:8100/build/polyfills.js:3:5153
o@http://localhost:8100/build/polyfills.js:3:2210
promiseReactionJob@[native code]
```

**Comment by seed880505** [comment]
@mokrea I have found a problem in your code.

`constructor(public myservice: MyServiceProvider) {
 }`
> public/protected/private is necessary when you use your provider outside the constructor.

I always have a compiling error like this in typescript.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

There are a lot of problems with your sample code.

```ts
@Injectable()
export class MyServiceProvider {

  checklist: any;
  checklistObserver: any;

  constructor() {
    console.log('Hello MyServiceProvider Provider');
    this.checklist = Observable.create(observer => {
     this.checklistObserver = observer;
   });
  }

  addItem(item): void {
    this.checklistObserver.next(true);
  }
}
```

1. I doubt you want to use create here. Have a look at the [create documentation](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-create) and the sample code that is there. I am not exactly sure what you are trying to do, but it seems like you want to look into using (subject)[http://reactivex.io/rxjs/manual/overview.html]
2. With your use of `create` here, you are setting `checklist` to an Observable and you are setting `checklistObserver` to whatever observer(s) subscribe to it, yet nothing is subscribing to it since you are attempting to call `addItem()` before subscribing (see below).

```ts
export class HomePage {

  constructor(public navCtrl: NavController, myservice: MyServiceProvider) {
    myservice.addItem("asd");
    
  }

  ionViewDidLoad() {
   this.myservice.checklistUpdates().subscribe(data => {
           console.log(data);
    });
  }

}
```

1. You are subscribing to `this.myservice.checklistUpdates()` which does not exist in your service
2. You are calling `addItem()` in the constructor and subscribing in `ionViewDidLoad()`, but the constructor has to run before `ionViewDidLoad()` can run, so even if `this.myservice.checklistUpdates()` did exist, the only thing emitting the observable is run before the subscription is made.


As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). 

Thank you for using Ionic

**Comment by mokrea** [comment]
Yes @kensodemann, there is a mistake in the code.. but the main idea is that you can't run the method `next()` inside a provider.. whether you change the code and put `addItem()` inside a method that runs before the subscriber the error will persist, I can't run the method `next()`... but if you change Observer by Subject, the method `next()` works.  Probably I failed to explain the problem: when you use Observer like this example: https://www.joshmorony.com/building-mobile-apps-with-ionic-2/observables-in-ionic2.html works.  But if you take the same code and transform `ChecklistModel` in `ChecklistProvider` (creating a provider instead model), the source code doesn't work cuz method next() doesn't work inside a provider. Of course, if it's the expected behavior, my mistake.

**Comment by kensodemann** [comment]
You can run `next()` inside a provider just fine. The problem with your code is that you are trying to call it before anything has subscribed to the observable so your provider's `checklistObserver` does not have a value yet. Let's make a few simple changes to show you that it does indeed work:

**home.html**
```html
<ion-header>
  <ion-navbar>
    <ion-title>Test Bed Blank</ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <button ion-button (click)="updateData()">Update</button>
</ion-content>
```

**home.ts**
```ts
import { MyServiceProvider } from '../../providers/my-service/my-service';

@IonicPage()
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, private myservice: MyServiceProvider) { }

  ionViewDidLoad() {
    this.myservice.checklist.subscribe(data => {
      console.log(data);
    });
  }

  updateData() {
    this.myservice.addItem('a');
  }
}
```

**my-service.ts**
```ts
import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';

@Injectable()
export class MyServiceProvider {

  checklist: any;
  checklistObserver: any;

  constructor() {
    this.checklist = Observable.create(observer => {
     this.checklistObserver = observer;
   });
  }

  addItem(item): void {
    this.checklistObserver.next(new Date());
  }
}
```

If you build that and run it you will see the current date output in the console, emitted from the service and subscribed to in the controller.
