### ISSUE TITLE
Where i can find a keyboard-attach document for IONIC 3

### ISSUE THREAD

**Issue by phantoxe** [ionic-team/ionic#12816]
I need use this in my inputs and text-areas in my project, but i can't find any place with a good document explaning all the steps. I'm a dummie... :-) 

Thanks to all guys!

**Comment by Sampath-Lokuge** [comment]
Here it is: http://ionicframework.com/docs/native/keyboard/

**Comment by phantoxe** [comment]
No man... I am looking about keyboard-attach... u know? For example: I have a text area in my projet... and then when i click in text-area my keyboard hide my input field. Understood? Other peoples tellme about this... that i need use a keyboard-attach!

**Comment by phantoxe** [comment]
Maybe i gonna try this method disableScroll(disable)... :-) It's right?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
