### ISSUE TITLE
segment content scroll position

### ISSUE THREAD

**Issue by KevinFu** [ionic-team/ionic#12810]
the first segment content scrolled to the bottom 
the second one also scrolled bottom
but I dont want the second one scroll 

how to solve

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

If this is an Ionic Framework issue (as in, you are reporting a bug in the Ionic Framework code), please open a new issue that has the issue template filled out, please.

Thanks for using Ionic!
