### ISSUE TITLE
Very Long Delay (3-4 seconds NOT 300ms) for event handler to trigger after clicking button

### ISSUE THREAD

**Issue by panuganti** [ionic-team/ionic#12817]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[] **2.x**
[ x] **3.x** (also observed in 2.x)

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have built multiple ionic apps. This bug happens with every app of mine.
Button clicks initially work fine. But after the complexity of the app grows suddenly the button clicks have a long delay. After the click, it takes almost 2-3 seconds for the app to respond to the click. 
I can't share the code here since there is nothing my code specific that makes this behavior.
THIS IS NOT the 300 ms delay,. It is 3-4 seconds delay.

**Expected behavior:**

I expect the event handler to react immediately. 

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by antoine92190** [comment]
I can also experience this issue.
For me it does not appears with all click events inside the app, but only with tabs button.
Plus, it occurs only at the first click of each tabs button. The second click works fine.

@panuganti Do you have a similar behaviour, or is it a different issue?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

Without knowing what your click event handlers are actually doing, I cannot really help you at all.

Have you tried profiling your code to see what it is doing?

Just a note: there is no 300ms delay with button clicks. That has long been removed.

Thanks for using Ionic!

**Comment by panuganti** [comment]
Let's first try to resolve this issue without requiring code please. Since its not a particular snippet and there are issues around sharing the code.

Yes, I tried profiling. When I opened the issue, I tried to sharing pics of profiling. 
Here is the application: http://rajkiran.ngrok.io -- I think, you can run it and also profile and see the code too.

How to repro: After initial loading, try to open any dropdown and change selection and click 'OK'. You will notice the delay. Most likely, it seems to be appearing when some objects are being destroyed.

My suspicion is around Garbage Collector kicking in. 
Here are some snapshots from the profile. 
![image](https://user-images.githubusercontent.com/2431946/30071857-52b74054-921d-11e7-93a8-8c6d1c726184.png)

![image](https://user-images.githubusercontent.com/2431946/30071939-8d119e0c-921d-11e7-81f2-c2f943680fba.png)

![image](https://user-images.githubusercontent.com/2431946/30071961-a020f722-921d-11e7-9585-74552d7a1574.png)

![image](https://user-images.githubusercontent.com/2431946/30071995-c33a404c-921d-11e7-8c06-4aa6035cbe2b.png)

**Comment by mnasyrov** [comment]
I faced with a similar issue: UI is freezing on 1-2 second after clicking on a tab.
My case: Ionic v3.7.1, no lazy-loading pages, 4 tabs, 3 of them contain virtual scrolls with 5-7k items.

I did some profiling and suspected that `Content.resize()` causes browser reflow. The resize was caused by `Tab.load()` method which is called by tab's click handler.

<img width="990" alt="screen shot 2017-10-16 at 18 15 35" src="https://user-images.githubusercontent.com/445680/31609781-bdb54ae8-b29f-11e7-9d35-49e4dca662d7.png">

After a closer investigation I found that the reflow happens when a tab is hided/shown by `show-tab` css class which is added/removed in `Tab.setSelected()` method.

As a hotfix I decided to try to make non-visible tabs be offscreen instead be off a layout tree to reduce cost of a future reflow. For this I overload `Tab.setSelected()` method with additional actions. Below is a hotfix directive with a CSS style:

```scss
// ionTabsFreezeHotfix.scss
.hotfix-show-tab--offscreen {
  overflow: hidden;
  position: absolute;
  left: 100vw;
  height: 100vh;
  width: 100vw;
}
```

```ts
// ionTabsFreezeHotfix.ts
import {Directive, HostListener, Self} from '@angular/core';
import {Tab, Tabs} from 'ionic-angular';
import './ionTabsFreezeHotfix.scss';

// TODO: HOTFIX, remove after Ionic issue will be resolved (https://github.com/ionic-team/ionic/issues/12817)
@Directive({
    selector: 'ion-tabs'
})
export class IonTabsFreezeHotfix {
    constructor(@Self() private tabs: Tabs) {
    }

    @HostListener('ionChange', ['$event'])
    onTabChange(tab: Tab) {
        tab.setSelected = function (isSelected: boolean) {
            // Hotfix: don't do anything in case the state is unchanged.
            if (this.isSelected === isSelected) {
                return;
            }

            this.isSelected = isSelected;

            // Hotfix: make a tab be off-screen
            this.setElementClass('hotfix-show-tab--offscreen', !isSelected);

            // this.setElementClass('show-tab', isSelected);
            this.setElementAttribute('aria-hidden', (!isSelected).toString());

            if (isSelected) {
                // this is the selected tab, detect changes
                this._cd.reattach();
            } else {
                // this tab is not selected, do not detect changes
                this._cd.detach();
            }
        };
    }
}
```

After applying the hotfix a time consumed by restyling and relayouting is reduced significantly:

<img width="1006" alt="screen shot 2017-10-16 at 18 42 13" src="https://user-images.githubusercontent.com/445680/31611107-f808ef38-b2a4-11e7-9216-a8aab3d87cb8.png">

I'm not sure that this is a stable solution, but it might be a right direction for investigations.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by mnasyrov** [comment]
@kensodemann Could you please explain more why you closed this issue? It is a performance issue because implementation of Tab component can cause heavily browser reflow according to my investigations which was described above..

**Comment by kensodemann** [comment]
@mnasyrov - cleaning up old issues mostly. The OP never provided a repo that could be used to demonstrate the issue or to use for investigation, and the original web-site he posted is not available (but also nowhere near as good as code from a repo).

If you can provide a GitHub repo that demonstrates the issue so it can be used for investigation I can reopen this and we can investigate it after v4 is released.

Or if you wish, you can re-run your tests after v4 is released and let us know if this is still an issue.

**Comment by Sampath-Lokuge** [comment]
Oh. Man .. You're talking about V4. It seems very close to release no? Any hint about the ERD? @kensodemann

**Comment by mnasyrov** [comment]
@kensodemann I made a demo for the issue, please check info below.

Demo app: https://ionic-9h59a2.stackblitz.io
Demo app with the hotfix directive applied: https://ionic-9h59a2.stackblitz.io/?hotfix
Source codes: https://stackblitz.com/edit/ionic-9h59a2
Used Ionic: 3.5.2

There are two tabs with plain ionic lists of 5000 items. Firstly click on each tab to compile components and render DOM elements. After that compare how long it takes to switch between tabs. Original tabs take ~1300ms to show a tab. Hotfixed version takes ~250ms to do the same (MacBook Pro, i7).

Original tabs
<img width="1440" alt="screen shot 2017-10-22 at 14 17 09" src="https://user-images.githubusercontent.com/445680/31859461-9cbd9052-b736-11e7-834c-7f1557527bc0.png">
[Profile-original_tabs-20171022T141721.zip](https://github.com/ionic-team/ionic/files/1404683/Profile-original_tabs-20171022T141721.zip)

Hotfixed tabs
<img width="1440" alt="screen shot 2017-10-22 at 14 50 28" src="https://user-images.githubusercontent.com/445680/31859605-6d5b6756-b738-11e7-8ca0-ba60ccec1615.png">
[Profile-hotfix_tabs-20171022T145017.zip](https://github.com/ionic-team/ionic/files/1404696/Profile-hotfix_tabs-20171022T145017.zip)

**Comment by kensodemann** [comment]
Sweet! Thanks!

**Comment by mnasyrov** [comment]
@panuganti Your demo app is unavailable. According to your profiler images, you rendered 110k of elements and it may take its 3 seconds to render. Also you may have an issue slow template bindings: there are 3.2 seconds used by setting properties and inner HTMLs. I did not see any long freezing by GC.

**Comment by HugoHeneault** [comment]
I had the same issue and always got they fixed by limiting the number of nested elements to < 5 in VS lists :)

**Comment by jmarginier** [comment]
Same here with 3.9.2...very crappy perf for button in tab and the back button (>2s) !
