### ISSUE TITLE
Constant put inside 'defaultHistory' is not working

### ISSUE THREAD

**Issue by vhb56** [ionic-team/ionic#12826]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
I have constant HOME_PAGE, that i import & would like to use instead of string, but it doesn't work:

```
import { HOME_PAGE } from "../pages.constants";

@IonicPage({
  defaultHistory: [HOME_PAGE]
})
```
Constant works if i push page or create modal, but not in defaultHistory.

When i reload/refresh page in browser i got this error: 
```
Runtime Error
Uncaught (in promise): invalid link: HOME_PAGE
Stack
Error: Uncaught (in promise): invalid link: HOME_PAGE
    at c (http://localhost:8100/build/polyfills.js:3:13535)
    at c (http://localhost:8100/build/polyfills.js:3:13221)
    at http://localhost:8100/build/polyfills.js:3:14067
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4500:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9888)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:5143)
    at o (http://localhost:8100/build/polyfills.js:3:2203)
    at <anonymous>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.11.0
    npm  : 5.4.0
    OS   : Windows 10
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello! Is this still an issue with the latest version of ionic? If so, please provide a sample application via GitHub that demonstrates the issue you are having. Thanks!

**Comment by danbucholtz** [comment]
Hi @vhb56,

I don't think we're going to be able to fix this before V4 of Ionic, where we get rid of the DeepLink decorator. It won't be an issue in the future I don't think.

Thanks,
Dan
