### ISSUE TITLE
docs: Suggested Correction to the installation Doc

### ISSUE THREAD

**Issue by ixaxion** [ionic-team/ionic#12821]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Suggestion for Documentation Change: For those that already have Android Studio installed, they can find the path to the Android SDK in the hidden AppData folder. Location: C:\Users\[Your Name]\AppData\Local\Android\sdk.

So %ANDROID_HOME% should be C:\Users\[Your Name]\AppData\Local\Android\sdk

This will be easier than downloading the SDK separately. The separate download doesn't include the platform-tools or the build-tools needed. I'm not sure if Google changed some things around, or if it requires another download, but it took me a few hours of trial and error just to get the application to run on my device.</span>

<span is-issue-template></span>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Can you provide a link to the exact document you are talking about just to make sure there is no confusion?

Thank you for using Ionic

**Comment by mokupindia** [comment]
@ixaxion - FYI, Google now requires you to download Android studio by default https://developer.android.com/studio/index.html, so I don't see any change in documentation into Ionic install guide. Earlier it all worked just by using - **_Get just the command line tools_** and invoking the android sdk manager.

**Comment by kensodemann** [comment]
This appears to be a request for an update to `ionic-team/ionic-site`, so I am moving this issue to that repo. Please follow the issue in that repo.

Thank you.

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-site#1244
