### ISSUE TITLE
post().map function cannot be called in latest ionic

### ISSUE THREAD

**Issue by kherP** [ionic-team/ionic#12824]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

post().map is not a function.... shown in console. 

**Expected behavior:**

post().map should be able to call

**Steps to reproduce:**
 I created a service to get data from api

**Related code:**

```
import { Injectable } from "@angular/core";
import { Observable } from 'rxjs/Rx';
import { Http, Headers, Response, RequestOptions } from '@angular/http';

@Injectable()
export class HomeService {
  constructor( private http: Http) {}

  retrieveCellLocationData(gsm, siminfo, cellsignal) {
    let url = 'http://localhost:8100/api';

    var headers = new Headers({
        "Content-Type": "application/json",
        "Accept": "application/json"
    });

    let options = new RequestOptions({ headers: headers });

    let postParams = {
      token: "1234567",
      radio: "gsm",
      mcc: siminfo.mcc,
      mnc: siminfo.mnc,
      cells: [{
        lac: gsm.lac,
        cid: gsm.cid
      }],
      address: 1
    }

    return this.http.post( url, postParams, options)
      .map((res: Response) => res.json())
      .catch((error: any) => Observable.throw(error.json().error || 'Server error'));
  }

}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\User\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.2.0
    npm  : 5.3.0
    OS   : Windows 10
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by kherP** [comment]
Hi,

Here's the [link](https://github.com/kherP/ionic-test-v2)for sample app. I've changed the method to get, still I cannot get map method to work.

**Comment by kensodemann** [comment]
I don't see where you have imported the operator anywhere. In order to use a rxjs operator you need to import it as such: `import 'rxjs/add/operator/map';`

**Comment by kherP** [comment]
I remember I added that before and it was not working, but it works now, thank you!
