### ISSUE TITLE
SQLite updating create method adding new column to a table  - BUG

### ISSUE THREAD

**Issue by carolgit** [ionic-team/ionic#12822]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When SQLite updating create method adding new column to a table, some mobiles can not identify the change returning the error "table x has no column named y", being necessary change the widget id on config.xml to solve the problem.

**Expected behavior:**
Identify the change in all devices without need to change config.xml

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Since this is an issue with one of the Ionic Native Plugins and not with the Ionic Framework itself, I am moving this issue to `ionic-team/ionic-native`. Please follow the issue over there.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-native#1951
