### ISSUE TITLE
Add has-fab class to ion-content

### ISSUE THREAD

**Issue by mebibou** [ionic-team/ionic#12825]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When adding a `ion-fab` component into an `ion-content`, the fab is put outside of the content. I think it would be nice to have a class on the `ion-content` that states that there is a fab inside, for example to avoid putting elements under the fab (let's say the fab is at the bottom and we want to add padding at the bottom). If the fab is put within a component in the content, it might be hard to know and just add the class manually to the content

**Related code:**

```
// my-component.html
<ion-fab right bottom>
  <button ion-fab></button>
</ion-fab>

// my-page.html
<ion-content>
  <my-component></my-component>
</ion-content>
```

**Other information:**
Other components like the `refresher` add a class `has-refresher` to the content

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/guillaumeroyer/Documents/workspace/actimirror/AMStoreApp/node_modules)

    @ionic/cli-utils  : 1.9.1
    ionic (Ionic CLI) : 3.9.1

global packages:

    Cordova CLI : 6.5.0 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.1.2
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.13 
    Node              : v7.4.0
    npm               : 4.1.2 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
```

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#309
