### ISSUE TITLE
ionic 3 comment the service-worker script after ionic build

### ISSUE THREAD

**Issue by power19942** [ionic-team/ionic#12832]
every time i change the www/index.html file and build the project ionic delete my change for example i un comment the service-worker script but after ionic build its back as comment

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

You shouldn't be changing anything in `www`, that is not source, that is the build output. Change `src/index.html` and then do your build.

Thank you for using Ionic
