### ISSUE TITLE
How to config Ionic app Deeplink using IonicPage  with queryString?

### ISSUE THREAD

**Issue by Hezier1223** [ionic-team/ionic#12834]
I need to add a query string into the url, so the url will be like 'localhost:4200/#/list?appKey=2d23d3fs'. Then I can get the param appKey in my component ,can anyone tell me how to implement this>..< Thanks a  =lot

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this is a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by BenjaminWatts** [comment]
did you get a resolution to this?
