### ISSUE TITLE
bug: There seems to be a bug when writing tags in Korea

### ISSUE THREAD

**Issue by IosAnkitsingh** [ionic-team/ionic#12836]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>1.) Enter 'simple tags input' in Korean. input text --> '한태그'

2.) Press return key, enter '한태' and press return key again.
If so, it will be listed as '그한태' in the tag.

3.) That is, the last string entered before the last tag is registered together.

4.) In this demo page, the minimum number of characters is 3 characters. Therefore, when inputting '한태' and pressing return key, an error should be displayed.</span>

<span is-issue-template></span>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by IosAnkitsingh** [comment]
Thanks for your quick response.
i can share with you screenshot of this issue.

![img_5421](https://user-images.githubusercontent.com/31728882/30159805-93006a98-93e7-11e7-9ddf-ec888f1624f8.jpg)

**Comment by kensodemann** [comment]
Thank you for the screenshot.

I just noticed this: "Ionic Version: 1.x"

Ionic v1 issues are tracked in their own repo. I will move this issue over there. Please track this issue in that repo.

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-v1#309
