### ISSUE TITLE
InfiniteScroll with custom content

### ISSUE THREAD

**Issue by vovikdrg** [ionic-team/ionic#12833]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**
I should be able to access state inside of InfinteScroll

**Steps to reproduce:**
I want to add my custom spinner but in this case spinner is always visible

 <ion-infinite-scroll (ionInfinite)="doInfinite($event)">
    <spinner [color]="'white'"></spinner>
  </ion-infinite-scroll>

I would like to i have possibility to access scrolls state

 <ion-infinite-scroll (ionInfinite)="doInfinite($event)" #inf>
    <spinner [color]="'white'" [attr.state]="inf.state"></spinner>
  </ion-infinite-scroll>

Also I've posted [question here ](https://stackoverflow.com/questions/46063928/ionic-infinite-scroll-with-custom-content)

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#310
