### ISSUE TITLE
Ionic select box option are opening twice?

### ISSUE THREAD

**Issue by bharathd** [ionic-team/ionic#12837]
I was using ionic 1 with cordova 5 facing a issue in IPAD like when i select dropdown option are able to display once when we select a option ,options are getting displayed once again.
this issue is happening using angular and basic jquery also

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out please.

Also, if you are using Ionic 1, please note that the proper repository for posting issues is https://github.com/ionic-team/ionic-v1. This repo is only for Ionic v2+ issues.

Thanks for using Ionic!
