### ISSUE TITLE
Share code between ionic and front app

### ISSUE THREAD

**Issue by ptitbibice** [ionic-team/ionic#12835]
Hi !

I've an issue, i would like share my mobile app(ionic) with my front app. Because, they use the same services. It's good to do that ?

Thanks

**Comment by gocha-gochitashvili** [comment]
Hello, What you mean when you say: share

**Comment by ptitbibice** [comment]
Thanks for your reply,

Share / mutualise : i have one application (a single code) for ionic and front app.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Feel free to keep talking here as well. You will just be more likely to get more traction in either of the above forums.

Thanks for using Ionic!
