### ISSUE TITLE
bug: http post

### ISSUE THREAD

**Issue by jayzee182** [ionic-team/ionic#12830]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>when make a post call, for example:

        var creds = "username=" + user.username + "&password=" + user.password;
        var headers = new Headers();
        headers.append('Content-Type', 'application/x-www-form-urlencoded');
        headers.append('Cache-Control', 'no-cache');
        headers.append('Cache-Control', 'no-store');
        headers.append('Expires', '0');
        headers.append('Pragma', 'no-cache');
        
        return new Promise(resolve => {

            console.log('credenziali: ', creds);

            this.http.post('SERVER-URL', creds, {headers: headers})
            .map(res => res.json())

            .subscribe(data => {
                
                console.log('risultato chiamata: ', data);

                //if(data.json().success){
                  if(data.status == 200 && data.statusText == "OK"){
                    
                    this.storeUserCredentials(data['_body']);
                    resolve(true);
                }
                else
                    resolve(data.statusText);
            },
            
            error => {
                   console.log("error", error)
                  resolve(error.statusText);
              },
            
            () => {
                    console.log('onComplete')
          });

These is the bug:

correct user data -> login process ok

wrong user data -> login process ko -> correct user data -> login process ko

wrong user data -> delete app data from Android Settings -> open app -> correct user data -> login process ok

It seems that (angular or ionic) caches somehow http call or something like that.

Thank you.</span>

<span is-issue-template></span>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

A few questions that might help solve this:
Is this only on Android? What happens if you run on iOS? locally via web browser?
Have you run remote debug on it and looked at the network traffic? What does the communication back and forth look like? 

Thanks for using Ionic!

**Comment by jayzee182** [comment]
i followed this tutorial:
https://www.djamware.com/post/58c1703e80aca7585c808ec1/step-by-step-tutorial-building-ionic-2-rest-api-authentication

when i don't make mistakes using the correct username and password the process login is all ok but when i try to put wrong data it gives me an error 401 unauthorized error even when in the third and later attempt i put the correct data.
I tried only on Android and via browser ( via browser i have cors issues )

**Comment by kensodemann** [comment]
Thank you for the reply.

> when i try to put wrong data it gives me an error 401 unauthorized error even when in the third and later attempt

Have you verified that the correct data is being sent in the request on the third and later attempts?

**Comment by jayzee182** [comment]
Yes and this is the reason i think thai there is some cache process because when i delete app data of the app from settings and i retry the login process if i put directly the correct auth data it gives me no error.
Thank you very much

Inviato da iPhone

Il giorno 06 set 2017, alle ore 20:35, Ken Sodemann <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Thank you for the reply.

when i try to put wrong data it gives me an error 401 unauthorized error even when in the third and later attempt

Have you verified that the correct data is being sent in the request on the third and later attempts?

**Comment by kensodemann** [comment]
Just to clarify, when you try this with the wrong credentials, you see something like this in Chrome's network tab:

![screen shot 2017-09-06 at 2 47 17 pm](https://user-images.githubusercontent.com/1526846/30131749-8aec29c0-9313-11e7-9038-16f5387acd80.png)


And then when you subsequently send the correct login information you see something very similar only with the correct data? But then still get a 401?

Also, have you tried asking this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).


At this point, I will have to close this as more of a support question but if you can provide a GitHub repo that demonstrates a bug in the Ionic Framework regarding this I will be happy to reopen the issue.
