### ISSUE TITLE
Share data between ionic app and electron app

### ISSUE THREAD

**Issue by ptitbibice** [ionic-team/ionic#12839]
Hi !

I would like send data from mobile app (ionic) to my pc app (electron) by usb connect. I search since two days, but i don't found ..

Someone has an idea ?

Thanks

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support / howto question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
