### ISSUE TITLE
Escape key dismiss both opened select and modal below the select

### ISSUE THREAD

**Issue by miloslavskacel** [ionic-team/ionic#12843]
**Ionic version:** 
[ x] **3.x**

**I'm submitting a ...**  
[x ] bug report

**Current behavior:**
When user presses Escape key, the currently opened select is dismissed, but also modal page from which select was opened is dismisses.

**Expected behavior:**
Escape key shall dismiss only the first view on the stack.

**Steps to reproduce:**
http://plnkr.co/edit/5Ognro?p=preview
Open modal
Open select
Press Escape
Both select and modal are dismissed
![screen shot 2017-09-08 at 10 47 45](https://user-images.githubusercontent.com/2547672/30204058-6c677e7e-9484-11e7-8f50-438f2bfc055c.png)

**Ionic info:**:

```
cli packages: 

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.4
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.9.1
    npm  : 5.3.0 
    OS   : macOS Sierra
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

We will look into this.

Thank you for using Ionic

**Comment by chancezeus** [comment]
As stated in #13126 this issue also presents when using the alertController alerts.

For now I have been able to do a quick & (really) dirty fix by forcing the backdropDismiss to false on the modal (using a private/internal property (`this.viewCtrl._cmp.instance._bdDismiss` (I know this is asking for a heap of trouble but for now this is the only thing that works)). Setting this property to false before opening the alert and then using the `alert.onDidDismiss` to return it to true (so it catches any variation of the alert being dismissed) does prevent the modal from closing.

A similar solution might work in other cases (but for the original issue of the select this will require listening/checking for the select being opened/closed in order for the property to be switched to the desired state)...

**Comment by erickbrenesLT** [comment]
Any updates on this issue?

**Comment by ghybs** [comment]
FWIW, I posted a workaround on the Ionic Forum:
https://forum.ionicframework.com/t/prevent-closing-of-multiple-modal-alert-picker-etc-on-escape-key/127695
