### ISSUE TITLE
Allow custom callback for ion-navbar back button

### ISSUE THREAD

**Issue by soumak77** [ionic-team/ionic#12841]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Desired behavior:**
I have a case where I am displaying a modal and need to add a close button in the toolbar.  I would like the modal to have a back button similar to when navigating between pages.  This will also make the modal look like a regular page when viewing on mobile since the modal takes up the full screen.

When inside a modal, the code executed by the back button does not work as expected since it pops the current page, but since we're in a modal we need to call `viewCtrl.dismiss()`.

I am proposing adding an `@Output back: EventEmitter<UIEvent>` property to `ion-navbar` which will emit the event when the back button is pressed.  This will allow the user to run custom code when the button is pressed.  You can check to see if the user is listening for the event by checking if `back.observers.length > 0`.  If true, the event will be emitted, otherwise the default code will be run and the page will be popped.

**Comment by soumak77** [comment]
I tried to implement this, however, I am running into issues with the back button being hidden in certain scenarios due to the page transition logic which shows/hides the back button.

I think a better solution would be to create a new component which renders just the back button.  This way the button can be used inside an `ion-toolbar`, which is preferred if using a modal anyway.

The back button component would need to be aware of the `mode` used for the `ion-navbar` or `ion-toolbar`.  **Is there a way to get the mode of a parent component within a child component?**

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#311

**Comment by soumak77** [comment]
@kensodemann is there any way to get a public view of the current feature requests and where they plan to land?  It's great you guys are keeping track of these requests in another repo, however, without the community being able to view those requests and provide their feedback/inputs (e.g. having people comment saying they also need the new feature), I assume these requests aren't going to be fulfilled.

Also there may be cases where the community wants to provide a PR for new functionality, but by moving the issue to a private repo, you block them from being able to discuss potential solutions with the Ionic team.
