### ISSUE TITLE
Drag event failed in build or run browser

### ISSUE THREAD

**Issue by raymond-kolorbox** [ionic-team/ionic#12842]
**Resources:**

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using ngx-color-picker and ng-pick-datetime module, the drag and drop cursor is working fine with "ionic serve". But it is broken with "ionic cordova run browser" and "ionic cordova build browser".

**Expected behavior:**
the drag and drop cursor should work for "ionic cordova run browser" and "ionic cordova build browser".

**Steps to reproduce:**
ionic start myApp blank
ionic cordova platform add browser
npm install ngx-color-picker --save

In app.module.ts, add
import { ColorPickerModule } from 'ngx-color-picker';
@NgModule({
...
  imports: [
...
    ColorPickerModule
  ],
})

in home.html, add
<input class="colorPicker" [(colorPicker)]="color" [style.background]="color" />

in home.ts, add
export class HomePage {
color: string;
...

Use "ionic serve" to start, the color picker cursor can drag smoothly.
Use "ionic cordova run browser" to start, cannot drag the color picker cursor.

**Related code:**
provided in "Steps to reproduce"

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.1
    ios-sim           : 5.0.13
    Node              : v6.10.3
    npm               : 5.3.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by raymond-kolorbox** [comment]
https://github.com/raymond-kolorbox/TestIonic

**Comment by mburger81** [comment]
I think It doesn't wok on cordova, if you try to use build a webapp if I can remember do something like this ionic run:build - - prod I hope it is the righr command

**Comment by raymond-kolorbox** [comment]
Yes, I know "npm run ionic:build --prod" can make it work just like "ionic serve", but it cannot use any cordova plugin which is one of the main purpose for using ionic to build hybrid app.

**Comment by mburger81** [comment]
I think and for what I know cordovo browser is still not to use. Which plugin do you want to use? Most of them doesn't work on browser.
But for those plugins wchich work you should be able to use them also for ionic build

**Comment by kensodemann** [comment]
There is an open issue out there to add a note to the documentation instructing people not to use the browser platform.

https://github.com/ionic-team/ionic-site/issues/1106

Basically, most Cordova plugins are not supported, and for many of them that are supported, the functionality is often mocked or stubs. It is our opinion that the platform is best used only as a testing platform.
