### ISSUE TITLE
There's a line between two divs,Some brands have android phones, some don't

### ISSUE THREAD

**Issue by zhangyuyuan123** [ionic-team/ionic#12859]
You need to zoom 150 percent in debugging to see it
![6q67gdv r ua 72 y 14](https://user-images.githubusercontent.com/26377801/30306938-aa48ee2c-97ad-11e7-8952-b08c0d4b83f5.jpg)

**Comment by zhangyuyuan123** [comment]
![6q67gdv r ua 72 y 14](https://user-images.githubusercontent.com/26377801/30306930-9b164f80-97ad-11e7-9eeb-caeb0c0017fc.jpg)

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out please.

Also, if you could provide a sample project that demonstrates the issue that would be very helpful.

Thanks for using Ionic!
