### ISSUE TITLE
perf: Application start duration is so long

### ISSUE THREAD

**Issue by ugurayan** [ionic-team/ionic#12853]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>After production of the project. Start duration takes around 15-20 secs.
I did everything 
like 
import { enableProdMode } from '@angular/core';
enableProdMode();
ionic build android --prod --release and remove 3rd party libraries etc...

But problem continues ...</span>

<span is-issue-template></span>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Can you please provide the results of the `ionic info` command from within your project directory? When run, it should look something like this:

```
~/Projects/Home/savitr (feature/authProvider): ionic info

cli packages: (/Users/kensodemann/Projects/Home/savitr/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 
    Gulp CLI    : CLI version 1.4.0 Local version 3.9.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.1 
    ios-sim           : 6.0.0 
    Node              : v8.4.0
    npm               : 5.3.0 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
```

Are you using lazy loading? This can have some impact. If you are already using it, great, if not you may want to give that a try.

Also, performance issues like this are a big focus of all of the work being done for Ionic 4.x

Thank you for using Ionic

**Comment by ugurayan** [comment]
cli packages:
    @ionic/cli-utils  : 1.6.0 
    ionic (Ionic CLI) : 3.6.0 
global packages:
    Cordova CLI : 7.0.1 
local packages:
    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.3
System:
    Android SDK Tools : 26.0.2
    Node              : v8.2.1
    OS                : Linux 4.4
    npm               : 5.3.0

**Comment by kensodemann** [comment]
Thank you. Everything looks reasonably up to date. You could try updating your libraries just to see if that has any effect (CLI is now at `3.9.2` and `ionic-angular` is now at `3.6.1` for example).

Are you currently using [lazy loading](http://blog.ionic.io/ionic-and-lazy-loading-pt-1/)? If not, that may be your biggest boost right now until v4.x is out.
