### ISSUE TITLE
font url on browser platform 

### ISSUE THREAD

**Issue by mm580486** [ionic-team/ionic#12864]
Hello guys
i want report a bug about ionic path , i added a font to assets folder ( like this `src/assets/xxxx.ttf` ) this code perfectly on ios, android and windows phone but on browser platform not working exactly !!!
and browser cant find font ( you can see on [app.pinsood.com](https://app.pinsood.com) )

**Ionic info:**

```
cli packages: (/Users/mac/Documents/agorna_phone/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.3.1 windows 4.4.3
    Ionic Framework    : ionic-angular 3.6.1

System:

    Node  : v8.4.0
    npm   : 5.3.0
    OS    : macOS Sierra
    Xcode : Xcode 8.2 Build version 8C38
```

**Comment by mm580486** [comment]
and also cant load splash screen

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

For the splash screen, looking at the [Cordova Plugin Page](http://cordova.apache.org/plugins/?q=splashscreen) at the splash screen plugins and then clicking the "Browser" button on the top to limit to just those plugins compatible with the browser platform shows no plug-ins being compatible.

I will consult our PWA expert regarding your other issues with the browser platform.

I also urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thank you for using Ionic

**Comment by mm580486** [comment]
thanks for follow up my issues
