### ISSUE TITLE
white screen after splash closed in ionic 2

### ISSUE THREAD

**Issue by Ali-H-A** [ionic-team/ionic#12869]
I'm trying to publish my application to other users but when I test it on my android phone there is a white screen that take more than 20 seconds after splash screen

This is my preferences (in config.xml)
`<preference name="loadUrlTimeoutValue" value="700000"/>`
` <preference name="Orientation" value="portrait"/>`
 ` <preference name="webviewbounce" value="false"/>`
  `<preference name="UIWebViewBounce" value="false"/>`
 ` <preference name="DisallowOverscroll" value="true"/>`
`  <preference name="android-minSdkVersion" value="16"/>`
 ` <preference name="BackupWebStorage" value="none"/>`
  `<preference name="SplashMaintainAspectRatio" value="true"/>`
`  <preference name="FadeSplashScreenDuration" value="300"/>`
 ` <preference name="SplashShowOnlyFirstTime" value="false"/>`
  `<preference name="SplashScreen" value="screen"/>`
  `<preference name="SplashScreenDelay" value="3000"/>`

Also I type this code in my app.ts contructor but still I can't skip the white screen 
` platform.ready().then(() => {
      statusBar.styleDefault();
	 setTimeout(() => {
	     splashScreen.hide();
          }, 100);	
    });`

I checked alot of solutions for same problem but the white screen still shown

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out please.

Please provide a GitHub repo with a sample application that duplicates your issue.

Thanks for using Ionic!
