### ISSUE TITLE
H5 video full screen show nothing

### ISSUE THREAD

**Issue by Gavin-cn** [ionic-team/ionic#12862]
Ionic version: (check one with "x")
[ ] 1.x (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] 2.x
[x] 3.x

I'm submitting a ... (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Current behavior:

If using HTML5 video in a nav in `ion-split-panel`, full screen mode show nothing(**only chrome with this bug**).

Expected behavior:

full screen.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello! Is this still an issue with the latest version of ionic? If so, can you please provide a sample application via GitHub or https://stackblitz.com? Thanks!

**Comment by kensodemann** [comment]
It has been quite a while without a response, so I am going to close this issue. If this is still an issue for you, please provide a sample application demonstrating the issue that we can use to help debug and test this out, and I will be happy to reopen the issue.
