### ISSUE TITLE
ion-select double bottom border on iOS

### ISSUE THREAD

**Issue by nymbl3d** [ionic-team/ionic#12865]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When a page containing an ion-select is first loaded, choosing a value for that ion-select will cause it to display a double bottom border line, as pictured in the example below. This only occurs  for the first ion-select the user interacts with on a given page, and seems to disappear after the content containing the ion-select is scrolled by the user.

I haven't been able to reproduce this on android or in chrome on desktop, and it does not occur when running the app in iOS Safari via a local server.

**Expected behavior:**
ion-select component renders correctly with a single bottom border on iOS

**Steps to reproduce:**
Create a page containing the example HTML below
Package the application for iOS
Run the application on device
Pick an item from the ion-select

**Related code:**
```
<ion-content>
  <ion-item>
    <ion-label color="primary" floating>Item</ion-label>
    <ion-select>
      <ion-option value="0">Item One</ion-option>
      <ion-option value="1">Item Two</ion-option>
      <ion-option value="2">Item Three</ion-option>
      <ion-option value="3">Item Four</ion-option>
    </ion-select>
  </ion-item>
</ion-content>
```

**Other information:**
[Image Example](http://i.imgur.com/Epw4NgA.png)
Note the double border below the bottom ion-select element.
(Ignore the floating backtick on the left side of the screen- that's an unrelated issue that has since been solved.)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\Josh\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.4
    Ionic Framework    : ionic-angular 3.6.1

System:

    Node : v6.10.2
    npm  : 3.10.10
    OS   : Windows 10
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

I just tried copy-pasting markup you supplied here into home.html in an app generated with `ionic start test-app blank` and it worked just fine both on the emulator and on my iPhone 7. No extra line.

Thanks for using Ionic!

**Comment by kensodemann** [comment]
I am going to close this as something that I cannot duplicate.

If you can provide a sample application via GitHub or https://stackblitz.com that duplicates this issue I will be happy to reopen the issue and have a look.
