### ISSUE TITLE
Hide Spinner

### ISSUE THREAD

**Issue by Muneem** [ionic-team/ionic#12863]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
There is no method to turn spinner off of loading container at run time. We can change content of loading spinner by using loading.setContent() method. But i cant find any method to turn spinner off

**Expected behavior:**
There should be some method to turn spinner off

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Before moving this to the feature request repo, I want to make sure I understand what you mean by "turn the spinner off"

Did you have a look at the [demo app](http://ionicframework.com/docs/api/components/loading/LoadingController/) ([source here](https://github.com/ionic-team/ionic/tree/master/demos/src/loading))? There is an option shown there called "Show Text Only" Is that what you mean? If so, have a look at the source for how to do that.

If not, please expand on what you mean.

Thank you for using Ionic

**Comment by kensodemann** [comment]
Hello! Thank you for opening this issue. I am going to close it due to lack of response. If you have further clarifications that you can make on your requirements, I will be happy to repopen this and then create a feature request entry out of it.

Thank you for using Ionic!
