### ISSUE TITLE
Lifecycle hooks being executed twice

### ISSUE THREAD

**Issue by sebaferreras** [ionic-team/ionic#12878]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When setting the `rootPage` in the `app.component.ts` file after an async method (for example if we want to check if the user is logged in), the lifecycle events (like `ionViewWillLoad` or `ngOnInit`) on that page are being executed twice.

**Expected behavior:**
The lifecycle events (like `ionViewWillLoad` or `ngOnInit`) should be executed only once

**Steps to reproduce:**
You can take a look at [this repo](https://github.com/sebaferreras/LifeCycleHooksDuplicated).

When running `ionic serve` for the first time, you'll see in the console:

```
---------------------
+++++++++++++++++++++
```

If you refresh the page of the browser (or make any change in the code, so Ionic will try tor refresh the view), you'll now see

```
---------------------
+++++++++++++++++++++
---------------------
+++++++++++++++++++++
```
You can try by placing a `debugger` and you will see that both `ionViewWillLoad` and `ngOnInit` are being called twice.

This may no be a real issue when running the app on a physical device, but it makes extremely difficult to work in the browser since every change in the code tries to refresh the browser, and when that happens the callbacks are being called twice.

**Related code:**

```
// app.component.ts file
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage;

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      statusBar.styleDefault();
      splashScreen.hide();


      setTimeout(() => {
        this.rootPage = 'HomePage';
      }, 1000);

    });
  }
}

```

```
// home.ts file
import { Component } from '@angular/core';
import { NavController, IonicPage } from 'ionic-angular';

@IonicPage()
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController) { }

  ionViewWillLoad() {
    console.log('---------------------');
  }

  ngOnInit() {
    console.log('+++++++++++++++++++++');
  }

}
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.10.1
    ionic (Ionic CLI) : 3.10.1

Local packages:

    @ionic/app-scripts : 2.1.4
    Ionic Framework    : ionic-angular 3.6.1

System:

    Node : v6.9.2
    npm  : 4.2.0
    OS   : macOS Sierra
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The problem with the way you have your app set up is that when it first starts up, `app.rootPage` is undefined. This means that if you hit `http://localhost:8100`, you will have a blank app (white screen) until your "am I logged in" call comes back. If this takes a while, you are going to have a white screen for a while.

Then, when you hit `http://localhost:8100/#/home` either on refresh or live reload, your `app.rootPage` is still undefined (that is a one-way binding) but the URL has loaded the home page. Then after you 1000ms timeout you tell it to load again by changing the root from undefine to `HomePage`.

What I normally do is architect my apps such that:

1. my auth service has an event that fires when the user logs out and another for explicit login
2. my app.component subscribes to those events and sets the rootPage appropriately
2. the default value for the `rootPage` when declared is whatever the login subscription would have set it to (`rootPage: string = 'HomePage';` for example)
3. navigating to a page kicks hits the back end as needed assuming that a user is logged in
4. I create a custom HTTP service that extends Angular's HTTP service and simply pings the auth service if I get a 401 back, causing it to emit the logout event, causing the subscription in `app.component` to set the root to the login page.
5. successful login then causes auth to emit the login event, causing the other subscription in `app.controller` to set the rootPage to whatever the default is

I have used a few different variations on that theme and they all work very well for me, and they avoid both the "white screen on startup if my data service fell asleep" (at least the user will get a loading spinner then while the DS wakes up), as well as the issue you are having here..

There are probably other ways to architect this as well. I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/) to see if there are other ideas that will also work for you.

Thank you for using Ionic

**Comment by sebaferreras** [comment]
Thanks for your answer @kensodemann. It makes sense for some scenarios, but **that wont be an option if the app should not allow the user to navigate to any page if he/she is not logged in** (so if the user is not logged in, the `LoginPage` should be the first and only page shown in the app).

Besides that, I used a `setTimeout` just to make the issue more obvious, but im my apps I actually read some data from the storage (so if the data is there, I know the user is logged in, and if that data is null, I need to show the `LoginPage` as the first page of the app). That just takes a few ms, so there's no white screen being shown to the user.

```
this.storage.get(this.storageDbName).then(data => {
    // ...
    this.rootPage = data ? 'HomePage' : 'LoginPage';
});
```

I'm very active in the [Ionic2/3 tags on StackOverflow](https://stackoverflow.com/users/3915438/sebaferreras?tab=profile) and I've seen that this pattern (reading data from the Storage to decide which page should be the root page) is used very frequently (although is not so obvious now to notice that the lifecycle hooks are being executed twice).

That was working previously, and seems to be changed with the latest changes made on the navigation logic.

**Comment by obbe79** [comment]
Basically I have a similar issue.
My `app.component` constructor is like so:

```
constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen, 
            private auth: AuthServiceProvider) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      this.auth.getAuthenticatedUser().subscribe(auth => {
        if (!auth) {
          this.rootPage = 'LoginPage';
        } else {
          this.authState = auth;
          this.rootPage = 'HomePage';
        }
      });
      statusBar.styleDefault();
      splashScreen.hide();
    });
}
```

Now, if I try to reload (when already authenticated) or when working with live reload  `http://localhost:8100/#/home`, I see that the `ngOnInit `method of a component which is part of `HomePage`, is fired twice.
This is the `ngOnInit `method:
```
ngOnInit() {
    this.auth.getAuthenticatedUser().subscribe(authUser => {
      if (authUser != null) {
        this.authKey = authUser.uid;
        //Do something
      } else {
        console.log("error")
      }
    })
    console.log("OnInitFired")
  }
```

So, is this a normal behavior? Otherwise how can I prevent this from happening?
