### ISSUE TITLE
icon resources not working anymore?

### ISSUE THREAD

**Issue by devtobo** [ionic-team/ionic#12873]
```
ionic resources --icon
Ionic icon resources generator
 uploading icon.psd...
```

No error, the command exit, but I don't have the icons...

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out please.

Also, this is not an Ionic Framework issue. It appears to be a CLI issue, so please create the issue in the [CLI repo](https://github.com/ionic-team/ionic-cli) using that repo's issue template.

Finally, what version of the CLI are you using? The `ionic resource` command has not existed for a while so I would have expected you to get an error. It is now `ionic cordova resources` with the output looking something like this:

```
~/Projects/Ionic/test-bed-blank (master *): ionic cordova resources
✔ Collecting resource configuration and source images - done!
✔ Filtering out image resources that do not need regeneration - done!
✔ Uploading source images to prepare for transformations - done!
✔ Generating platform resources: 18 / 18 complete - done!
✔ Modifying config.xml to add new image resources - done!
```

You may be using a really old version of the CLI and in that case you will likely want to look at upgrading.

Thanks for using Ionic!
