### ISSUE TITLE
 Browser back button no working when in tabs page

### ISSUE THREAD

**Issue by steavengong** [ionic-team/ionic#12877]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

1. ionic start newProject tabs
2.in app.modules.ts code  
  IonicModule set links: [
       xxxxxxx
      ]
3.tabs/map/map ==> tabs/map/demo
4 click browser back button 
   the browser address is change ,but the view don't change
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

git code: https://git.oschina.net/842228597/callpu-dangjian.git

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
@ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.4
    Ionic Framework    : ionic-angular 3.6.1

System:

    Node : v7.9.0
    npm  : 5.4.1 
    OS   : macOS Sierra

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I cannot get your source from your repo as it asks for authentication:

```
~/Projects/Ionic: git clone https://git.oschina.net/842228597/callpu-dangjian.git
Cloning into 'callpu-dangjian'...
Username for 'https://git.oschina.net': 
Password for 'https://git.oschina.net': 
```

Is there any way you could share this via a public [GitHub](https://github.com/) repo?

I have a [tabs test repo](https://github.com/kensodemann/test-bed-tabs) that shows navigation working, including with the browser back button, so this isn't really a bug or feature request so far as I can tell.

As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

If you can get me access to your sample application, however, I will be happy to take a quick look at it.

Thank you for using Ionic

**Comment by steavengong** [comment]
Thanks your demo , I get it .

**Comment by jjjhanreyyy** [comment]
Hi @steavengong . I am current experiencing the same issue. Could you please discuss how did you fixed this problem?

**Comment by steavengong** [comment]
you can use router like this
@IonicPage({
  name: 'demo',
  segment: 'demo'
})
@Component({
  selector: 'page-demo',
  templateUrl: 'demo.html',
})
export class DemoPage {
}

if tabs page don't set it's name as ‘tabs’   it will be error
