### ISSUE TITLE
Ionic View - SVGs not working 

### ISSUE THREAD

**Issue by Kapsul-Brice** [ionic-team/ionic#12870]
**Ionic version:**  
[ ] **1.x** 
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  
[X ] bug report
[ ] feature request
[ ] support request

**Current behavior:**
The SVG images are visible on devices (both android+ios) / working fine on devices and emulators
The SVG images are hidden in Ionic View / Not working in Ionic View

**Expected behavior:**
The SVG images should be visible / working in Ionic View

**Steps to reproduce:**
Push an app with SVGs <img> to ionic pro backend
Open this app in Ionic View

**Related code:**

```
<img src="assets/images/home_btn_1.svg"  />
```

**Other information:**
Forum link : https://forum.ionicframework.com/t/svg-file-is-not-shown-on-ionic-view/105063

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 
    Gulp CLI    : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2 
    Node              : v6.11.2
    npm               : 5.4.1 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This appears to be an issue with Ionic View and not the Ionic Framework, so I am going to move this issue to `ionic-team/ionic-view-issues`. Please follow the item over there.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-view-issues#231

**Comment by sebfie** [comment]
This repo does not exists anymore :(

**Comment by kensodemann** [comment]
I believe that team has decided that since Ionic View is part of Ionic Pro that issues should go through Ionic Pro's support portal (http://support.ionicjs.com)

**Comment by willyboy** [comment]
So how will we receive updates for when this is fixed?

**Comment by teomaragakis** [comment]
This is so disappointing. I too have the same issue. SVG works in the iOS simulator and web view but not on the view app on iOS. PNG images work fine everywhere.

**Comment by sebfie** [comment]
Yes, plz fix it!

Sébastien fieloux
Développeur freelance
0698458781 <//0698458781>
sebastien.fieloux@gmail.com
http://www.sebfie.com

Le 22 octobre 2017 à 19:54:16, Teo Maragakis (notifications@github.com) a
écrit:

**Comment by gope153** [comment]
Same Issue here :/

**Comment by rodriggochaves** [comment]
I couldn't find the post related to this issue in http://support.ionicjs.com. Have anyone found it?

**Comment by chitty** [comment]
I'm having this issue as well. But didn't find any related post in http://support.ionicjs.com either, so I submitted a new request to them.

I'll post here later if I get a response.

**Comment by chitty** [comment]
I got a reply from the Ionic support team confirming this is still an issue on their side. They do not have a public issue tracking for Ionic Pro, but they said I'll get a notification once this is fixed (I'll add a comment here).

They didn't provide a time estimate.

For now, SVGs will not display.
