### ISSUE TITLE
Hint in documentation that you have to restart ionic serve after adding new page

### ISSUE THREAD

**Issue by NIX-Pepe** [ionic-team/ionic#12871]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] documentation request

**Current behavior:**
Hello, 

i stumbled on this bug here after I did encounter the same issues:
https://github.com/ionic-team/ionic/issues/11374

I'm pretty new to ionic but did some work with angular 2 before. After a lot of research and debugging there was a simple solution: I had to restart "ionic serve" after adding a new page. I'm sure a lot of people complaining in the thread mentioned made the very same mistake as I.

People get lazy when there normally is no need to restart your webserver. So maybe add a hint that a rebuild is necessary for ionic to discover new pages. I would have replied to older issues but discussions where closed.

Kind regards,
Pepe

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am not entirely sure if this is something we want to document as such or if it is an issue with the live reloading. It seems to me that adding a new page ought to be detected and a rebuild executed. I did that with `ionic serve` running with an application that uses lazy loading, and the application rebuilt just fine. Then when I modified the application to access the page, that also worked just fine.

It may be that I just don't understand the issue fully.

Anyhow, this does not appear to be an Ionic Framework related bug or feature request, so I am going to close this issue. Please reply back if I am misunderstanding the situation and I may reopen it or potentially move it to the `ionic-team/ionic-cli` as this also appears to perhaps be more of a CLI issue. I would need to understand more about it first, however.

Thank you for using Ionic
