### ISSUE TITLE
convert my ionic 2 app from http protocol to https

### ISSUE THREAD

**Issue by kanityi** [ionic-team/ionic#12886]
i want to use geolocation plugin in my app, but my request is denied since geolocation is using secure protocols like ssh, https etc.

i've got this error : PositionError {code: 1, message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)."} 

*its not a new issue thou, just that i don't how to implement those solutions

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
