### ISSUE TITLE
Cant create platform or resources

### ISSUE THREAD

**Issue by tobbbe** [ionic-team/ionic#12888]
**Ionic version:** 
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I try to do `ionic cordova platform add ios` I get

> ionic source path does not exist resources/ios/icon/icon-40.png

Which means resources are missing. So I try to do `ionic cordova resources ios`. But then the cli tells me ios platform is missing. So its a catch-22..

**Expected behavior:**
Should be able to create resources without a platform

**Steps to reproduce:**
Create new project, remove `resources/ios `.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is not an issue with the Ionic Framework, nor is it an issue with the Ionic CLI. If you where to follow your steps and then type `cordova platform add ios` (no 'ionic', just the cordova CLI) you would get the exact same error message, so Cordova itself does not support this.

That said, it isn't really a catch-22, just don't remove your resources after you create your project, and if you accidentally did that, then create another project and copy the resources from there to restore them and you will be fine.

Thank you for using Ionic

**Comment by tobbbe** [comment]
Okey, I see that its not a problem with Ionic. But Im 100% sure you could do it in earlier versions of the cli.

The reason for removing the platform specific resources is because I dont want to have these big files in my remote repo.

Also, the `ionic cordova platform` command has a `--noresources` flag (Do not add default Ionic icons and splash screen resources). Maybe there could be a `--addresources` flag to?

**Comment by kensodemann** [comment]
You can open a feature request on the [Ionic CLI](https://github.com/ionic-team/ionic-cli) if the `--addresources` flag would be useful to you.
