### ISSUE TITLE
problem when use  --prod    or    --aot

### ISSUE THREAD

**Issue by BahgatMashaly** [ionic-team/ionic#12887]
Hello all,

the command "ionic cordova run android" is work fine

but when use
ionic cordova run android --prod --release
it gives me an error:

Error: Cannot determine the module for class IonicApp in /Volumes/MACData/programing/programing11/projects/ssp/ssp-v91/node_modules/ionic-angular/umd/components/app/app-root.d.ts! Add IonicApp to the NgModule to fix it.

i tried to add IonicApp  in declarations array but it gives me another error : 
Error: Type IonicApp is part of the declarations of 2 modules:  "ionic-angular/module.d.ts " and AppModule
 

how can i fix this issue ?

ionic info:
@ionic/cli-plugin-proxy : 1.4.9
    @ionic/cli-utils        : 1.10.2
    ionic (Ionic CLI)       : 3.10.3
global packages:
    Cordova CLI : 7.0.1 
local packages:
    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android ios 4.4.0
    Ionic Framework    : ionic-angular 3.4.2
System:
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    Node       : v7.2.0
    npm        : 3.10.9 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
