### ISSUE TITLE
Google autocomplete failing to set input

### ISSUE THREAD

**Issue by dallinski** [ionic-team/ionic#12892]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using google.maps.places.Autocomplete and selecting an item from the list of suggested completions, the input field is not filled with the new value. Also, the "place_changed" event is never triggered. Autocomplete works just fine when using ionic-angular v3.3.0, but is broken on v3.4.0 and newer.

**Expected behavior:**
When an item is selected on the dropdown of suggested completions, the value in the input field is changed to the value of the selected item. The "place_changed" google.maps.event is then fired. This is working when using ionic-angular v3.3.0.

**Steps to reproduce:**
Build and run demo app (which uses ionic-angular v3.3.0): https://github.com/dallinski/ionic-autocomplete-bug
It works as expected.

Change to v3.4.0 branch (which uses ionic-angular v3.4.0): https://github.com/dallinski/ionic-autocomplete-bug/tree/v3.4.0
It does not work as expected. onPlaceChange is never called.

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages:

    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 6.4.0

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : ios 4.2.1
    Ionic Framework    : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    npm        : 3.10.9

**Comment by giumarzo** [comment]
I used https://github.com/danielehrhardt/Ionic-2-Google-Maps-Marker-Cluster

**Comment by kensodemann** [comment]
> I don't have the time to create a plnkr right now, but I will soon.

Marked as `needs info` awaiting some sample code.

**Comment by dallinski** [comment]
I got a demo app coded up that exhibits the bug:

Build and run demo app (which uses ionic-angular v3.3.0): https://github.com/dallinski/ionic-autocomplete-bug
It works as expected.

Change to v3.4.0 branch (which uses ionic-angular v3.4.0): https://github.com/dallinski/ionic-autocomplete-bug/tree/v3.4.0
It does not work as expected. onPlaceChange is never called.

**Comment by kensodemann** [comment]
I tried your demo app using the following versions of ionic-angular: 3.3.0, 3.4.0, and 3.7.1 (which also involves upgrades to Angular, rxjs, zone.js, and @ionic/app-scripts)

In all cases, your demo app worked and did not exhibit any issue with onPlaceChange not being called.

I am going to close this but will be happy to reopen it if it can be duplicated.

**Comment by dallinski** [comment]
Here's a video of the v3.4.0 build exhibiting the bug on my machine: http://recordit.co/DpkcgT4hlO

I'm super confused why it's not behaving that way for you.

**Comment by kensodemann** [comment]
One key bit I get from your video that is not in your write-up is that you are running your test on an iOS device. I ran my tests in the browser. Worked fine... :)

I'll re-open and re-run the tests on both an iOS device and an Android device when I get a chance (probably tomorrow).

**Comment by dallinski** [comment]
Sorry for not mentioning that, and thanks for taking a look at this issue.

**Comment by tyholby** [comment]
@kensodemann I'm having same problem. Any update on this?
