### ISSUE TITLE
Cursor scroll with screen in IOS device

### ISSUE THREAD

**Issue by JaswinderImmanent** [ionic-team/ionic#12896]
I am working in Ionic 1 .I have a form with 6-7 fields.When i tried to fill the form the cursor scroll with the screen and cursor move out of screen.
It is working fine in android and in browser.The problem is only with IOS device.
I tried to test on 
Xcode2 - iPhone7 (iOS 10.1)
in iphone 6

Please help as soon as possible!

Thanks in advance.

**Comment by aks0020** [comment]
For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1

**Comment by JaswinderImmanent** [comment]
Thanks

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As @aks0020 pointed out, Ionic v1 has its own repo. I would move this issue over there for you, but it does not have the template properly filled out so it would likely just be closed and you would be asked to create a new one using the template 

I will also urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Those forums get a lot more traffic than the Ionic v1 issues list gets.

Thanks for using Ionic!
