### ISSUE TITLE
Bouncing ion-content not working in Android

### ISSUE THREAD

**Issue by JasonAsmk** [ionic-team/ionic#12899]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Android ion-content never bounces even when config ha DisallowOverscroll to false.

**Expected behavior:**
When scrolling reaches the end, overscrolling should show the native Android shadow effect.

**Steps to reproduce:**
Create a sample list like [this](http://plnkr.co/edit/ZPcPNoMXJ5nhUdXQokj2?p=preview). Change the following from true to false.
`    <preference name="DisallowOverscroll" value="false" />
`

**Related code:**
Even setting the scroll-content css like [this](https://github.com/ionic-team/ionic/blob/a30379bef6bf323b512b12eeb6904abab4690115/src/components/content/content.ios.scss#L61) doesn't solve the issue.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/home/jasonasmk/.nvm/versions/node/v6.9.5/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.0.2
    Node              : v6.9.5
    npm               : 3.10.10 
    OS                : Linux 4.12

```

**Comment by masimplo** [comment]
Just tried it in my app and sample apps and cannot get it to work in android. I know people have it working in iOS but native android has this as well nowadays.
Is this not supported at all? Is it a bug? Are we doing something wrong in our configurations?
