### ISSUE TITLE
ion-infinite-scroll threshold cannot be a percentage

### ISSUE THREAD

**Issue by WilliamDASILVA** [ionic-team/ionic#12891]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Threshold value for infinite scroll does not work when the value is a percentage. But when it's a pixel value, it works properly.
Using for example a "50%" value, the event is not fired when reaching 50% of the content but is fired when reaching 100px distance from the bottom I guess. That same value I found searching for 'threshold' in the source code.

**Expected behavior:**
When scrolling to 50% of the screen, the infinite scroll event should be fired.

**Steps to reproduce:**
Demo here: http://plnkr.co/edit/yQ8E8syVZtkA2mBs9TPU?p=preview

**Related code:**

```
<ion-header>
  <ion-navbar>
    <ion-title>{{ appName }}</ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <ion-list>
   <ion-item *ngFor="let i of items">
     my item value
   </ion-item>
 </ion-list>

 <ion-infinite-scroll threshold="50%" (ionInfinite)="doInfinite($event)">
   <ion-infinite-scroll-content></ion-infinite-scroll-content>
 </ion-infinite-scroll>
</ion-content>
```

**Other information:**
As said in the documentation here: https://ionicframework.com/docs/api/components/infinite-scroll/InfiniteScroll/
The threshold value can be a percentage. If it's not the case, the documentation should be updated.

> The threshold value can be either a percent, or in pixels.

**Ionic info:**:

```
cli packages: (/Users/mycuistot/.nvm/versions/node/v6.10.2/lib/node_modules)

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

global packages:

    Cordova CLI : 7.0.0 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.0 
    ios-sim           : 5.0.13 
    Node              : v6.10.2
    npm               : 5.4.1 
    OS                : OS X El Capitan
    Xcode             : Xcode 8.2.1 Build version 8C1002 
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

It is easier to see how this works with numbers in place, so I changed your code as such:

```ts
export class HomePage {

  appName = 'Ionic App';
  items: Array<string> = [];
  
  constructor(public navController: NavController) {
    this.addItems(100);
    }

  doInfinite(scroll) {
    alert('scrolling');
    setTimeout(() => {
      this.addItems(16);
      scroll.complete();
    }, 500);
  }
  
  private addItems(c: number): void {
    for (let i = 0; i < c; i++) {
      this.items.push(`item # ${this.items.length + 1}`);
    }
  }

}
```

Some of this depends on how fast you scroll, so scroll at a moderate pace. Also, the current size of the page matters. On my display, your plunkr shows 16 items.

With the threshold set to 50%, I expect `doInfinite()` to kick in around the item number 92 mark (display holds roughly 16 items,  half of that is 8 items, I have 100 items, 50% of the screen from the bottom is then 92 items).

With the threshold set to 50px, I expect `doInfinite()` to kick in around the item number 100 mark as the items are close to 50px tall themselves so the 50px left threshold would be passed around item 99 or so and by the time things register item 100 will likely be shown.

If you scroll at a reasonable speed, you will see that this is indeed the way things play out with the code above. You will also see that this is the way things continue to play out as items are added. With the threshold set to 50%, the fetch is triggered when roughly half of a screen height of items are left unshown, and with 50px when basically the last item is shown.

So far as I can tell, everything is working as designed. I will close this.

Thank you for using Ionic

**Comment by marianoo-andres** [comment]
Hi. I believe it does not make sense to set a % threshold of the display. If I set the threshold to be 50% I expect doInfinite() to trigger at 50% of scroll height or similar. This is what @WilliamDASILVA meant.
