### ISSUE TITLE
ion-split-pane center issue for date, toast etc.

### ISSUE THREAD

**Issue by yoffe** [ionic-team/ionic#12893]
**Ionic version:**  (check one with "x")
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
 date (ion-picker-cmp), toast (ion-toast) etc. show at the center of the screen and not at the center of the main content.

**Expected behavior:**
@mhartington said in the slack channel that it should be in the center

**Steps to reproduce:**

![image](https://user-images.githubusercontent.com/2963687/30443139-38e6f36a-9987-11e7-8bd4-a34d9c0e85d0.png)

**Ionic info:**

![image](https://user-images.githubusercontent.com/2963687/30443220-7636978e-9987-11e7-8e96-c5d726c1143a.png)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

It would help greatly for verification and testing when we look into this.

Thanks for using Ionic!

**Comment by yoffe** [comment]
Hi @kensodemann 

![image](https://user-images.githubusercontent.com/2963687/30514792-dfc57bd6-9b24-11e7-90c0-c316bc9498dd.png)

https://github.com/yoffe/ionsplitpanecenter

**Comment by kensodemann** [comment]
Excellent! Thank you very much!

**Comment by manucorporat** [comment]
I don't think this is an issue at all. Modals, actionsheets, alerts, toast etc. are screen wide components that are designed to disrupt the user interaction so all the user focus goes to the component.

cc @mhartington have you seen the opposite behavior in natives apps or documented by Apple?

From a technical point of view, it would not be easy to do that.

**Comment by manucorporat** [comment]
Same can be applied to datetime and toast. This issue is a "won't fix" to me

![img_0220](https://user-images.githubusercontent.com/127379/30515875-33874e92-9afe-11e7-805c-7527f5621241.PNG)
![img_0218](https://user-images.githubusercontent.com/127379/30515876-34ebbdea-9afe-11e7-8455-4bdfe2530742.PNG)
![img_0217](https://user-images.githubusercontent.com/127379/30515877-367f3696-9afe-11e7-8711-8329aa05ace2.PNG)
