### ISSUE TITLE
 Didn’t see any log when `lonic cordova run ios -l -c`.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [ionic-team/ionic#12890]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After update version, I didn’t see any log when lonic cordova run ios -l -c.

ionic info
```
cli packages: (.../node_modules)

    @ionic/cli-utils  : 1.10.1
    ionic (Ionic CLI) : 3.10.1

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    Node       : v6.11.0
    npm        : 5.4.1 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
```

After run command.
```
** BUILD SUCCEEDED **

No target specified for emulator. Deploying to iPhone-SE, 10.3 simulator

com.xxxxxx.xxxxxx: 25997
logPath: /...ProjectPath.../platforms/ios/cordova/console.log
```
Didn’t get any log.

**Expected behavior:**
After run command `lonic cordova run ios -l -c` will get log.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2739

**Comment by jgw96** [comment]
Hey! Since this is a cli issue I moved it to the ionic-cli repo. Thanks!
