### ISSUE TITLE
Docs broken by tag class

### ISSUE THREAD

**Issue by viki53** [ionic-team/ionic#12909]
**Ionic version:**
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

![Screenshot from https://ionicframework.com/docs/components/#cards](https://user-images.githubusercontent.com/1763364/30520815-5e03e8da-9bb5-11e7-8ef8-82d4c2dfc474.png)

**Expected behavior:**

No blue rounded rectangles and proper syntax highlighting like before

**Steps to reproduce:**

Just go to any component docs on the official website.

**Related code:**

See `css/components/_tag.scss:1`

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Can you provide a specific link? I am not seeing this. I went to the page I think you screenshot, and it looked like this:

<img width="762" alt="screen shot 2017-09-17 at 4 04 32 pm" src="https://user-images.githubusercontent.com/1526846/30524894-f8aa4742-9bc1-11e7-9858-e4840e94f231.png">


Thank you for using Ionic

**Comment by kensodemann** [comment]
I am going to close this since I cannot duplicate it and since it is not an Ionic Framework issue.

Thank you for using Ionic

**Comment by viki53** [comment]
I am using Chrome 60 on macOS Sierra.

Here is a screenshot with the DevTools open, where you can see the applied CSS:

![Screenshot](https://user-images.githubusercontent.com/1763364/30560474-53c2e52a-9cb8-11e7-833b-80aa0b7386c4.png)

**Comment by kensodemann** [comment]
Interesting...

According to "About Chrome" here is what I have: Version 61.0.3163.91 (Official Build) (64-bit)

Also MacOS

Can you check your "About Chrome" just to make sure you aren't on a BETA or anything?

Also, my markup looks slightly different than what you have:

![screen shot 2017-09-18 at 2 39 17 pm](https://user-images.githubusercontent.com/1526846/30561023-55012336-9c7f-11e7-976a-a27a490feaff.png)


Weird.

If this continues to be an issue for you, you may want to open an issue over at https://github.com/ionic-team/ionic-site
