### ISSUE TITLE
How is written default ionic splash screen?

### ISSUE THREAD

**Issue by giorgi94** [ionic-team/ionic#12903]
I've been searching how to make ionic splash screen, where many of them said to disable cordova splash and show svg animation. I made it, but it runs only when application is ready and till that it shows black white screen.

I noticed that default splash screen is animated, but I cannot find how it is made. Where is it located?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
