### ISSUE TITLE
Font not Found - ionic v3

### ISSUE THREAD

**Issue by Barathwaja** [ionic-team/ionic#12918]
**Roboto Fonts** are missing in **build/assets/fonts** folder , because of that it affects debug and prod too.

using Ionic CLI : 3.10.3

![error](https://user-images.githubusercontent.com/5066436/30558572-95c7ea08-9ccf-11e7-87d1-33bfadb67334.png)

**Comment by Bleno** [comment]
+1

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue for the following reasons: this is not an issue with the Ionic Framework, but is more likely an issue with Ionic App Build Scripts, and the template was not filled out with all of the pertinent information.

I ask you to please re-open this issue in the [Ionic App Build Scripts repo](https://github.com/ionic-team/ionic-app-scripts) and to please fill out the issue template that exists in that repo.

Thanks for using Ionic!

**Comment by Barathwaja** [comment]
Sure. @kensodemann 

Thanks.. !!
