### ISSUE TITLE
buttons in list (suddenly?) have rounded corners

### ISSUE THREAD

**Issue by patrickmcd** [ionic-team/ionic#12912]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
If you give a `<button ion-item>` a color property, you'll notice slight rounded corners. Previous behavior was that buttons as list items would have square corners, which makes more sense to me.

![image](https://user-images.githubusercontent.com/764290/30523158-5e07e7a6-9baa-11e7-8849-85c8a9ffed69.png)

**Steps to reproduce:**
https://stackblitz.com/edit/ionic-b4uv88

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
@ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 24.4.1
    ios-deploy        : 1.9.2
    ios-sim           : 6.0.0
    Node              : v6.11.2
    npm               : 5.4.2
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b
```

**Comment by kensodemann** [comment]
When I run your StackBlitz, I see square corners:

<img width="524" alt="screen shot 2017-09-17 at 3 47 14 pm" src="https://user-images.githubusercontent.com/1526846/30524797-d3c9210c-9bbf-11e7-9472-542a63346651.png">

I tried this on a Mac using Safari, Chrome, and Firefox.

**Comment by patrickmcd** [comment]
Interesting. FF and Safari look fine (I'm on Mac as well).

I just updated to Chrome Version 62.0.3202.18 (Official Build) beta (64-bit). Is that different than your version?

**Comment by kensodemann** [comment]
I have Version 60.0.3112.113 (Official Build) (64-bit), but an update it installing now. I'll check again after it is done

**Comment by kensodemann** [comment]
I now have Version 61.0.3163.91 (Official Build) (64-bit), and they are still square. Perhaps something to do with the beta?

**Comment by patrickmcd** [comment]
Yep. Back to square corners on stable. Apologies. I'd forgotten I was on beta and thus to test against it.

I'll look into reporting a Chromium bug...never done that.

**Comment by patrickmcd** [comment]
This is now happening on the release version of Chrome.

Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by kensodemann** [comment]
It appears that is the way Google wants these things to look. They added this to their User Agent Stylesheet: `border-radius: 4px;` for several inputs including the buttons.

I'll mark this as something to potentially look at after v4 is released. In the meantime, I believe you can easily get around this without messing up places that we intentionally add the border-radius by adding the following to your `app.scss`

```
button {
  border-radius: 0;
}
```

**Comment by brandyscarney** [comment]
I have fixed this in v4 so that even if `border-radius` ends up being set by the browser our item will normalize it to `0`. I am not able to reproduce this using the latest Chrome, but I did manually set all `button` elements to have a border-radius in order to verify that this is fixed. Thanks for the issue!
