### ISSUE TITLE
Problem with innerHtml on ion-textarea

### ISSUE THREAD

**Issue by RuneStenstroem** [ionic-team/ionic#12915]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Hi I am having a problem using [innerHtml] binding og an ion-textarea. It works on ion-input. I am using it to show emojis. So when I save the data I use angular sanitize html and when is show the data i us byPassTrhustedHtml

**Current behavior:**
The textarea inside the ion-textarea is not showing

**Expected behavior:**
The text area is showing with and the innerHtml corresponds with the binding.

**Steps to reproduce:**
make a ion-textarea with an innerHtml binding. Use byPassThrustedHtml on a string of html and bind it to the text area

``

insert the output from ionic info here

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 browser ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.3
    Node              : v6.10.0
    npm               : 3.10.10
    OS                : Windows 8.1

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by kensodemann** [comment]
I am closing this issue since it has been quite a while without a response. If this is still an issue for you, please provide a sample application we can use to help resolve and test the issue and I will be happy to reopen this.
