### ISSUE TITLE
Clear Crosswalk Cache when new profile picture?

### ISSUE THREAD

**Issue by JonasWestAlro** [ionic-team/ionic#12925]
Hi, 

I have a problem om android, when the user is updating the profile picture, the image is cached and doesn't change, though it has been changed on the remote server. 

Does anyone know if and how I can clear the cache and reload the picture? It doesn't even help to restart the app.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
