### ISSUE TITLE
Virtual scroll with infinite scroll

### ISSUE THREAD

**Issue by francoro** [ionic-team/ionic#12920]
this is my problem : https://imgur.com/a/FwS4d

you will see there the draw piece thats is my problem after afeew scrolls my infinite scroll takes more height and overlap the property(data).

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out please. Also please include a sample application that duplicates your issue, either via GitHub or a tool such as [StackBlitz](https://stackblitz.com) Thanks for using Ionic!
