### ISSUE TITLE
@ionic/app-scripts@2.1.4 depends on deprecated babili@0.1.2

### ISSUE THREAD

**Issue by Polyergic** [ionic-team/ionic#12928]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

`npm install` gives this warning:

```
npm WARN deprecated babili@0.1.2: babili has been renamed to babel-minify. Please update to babel-minify
```

**Expected behavior:**

There should be no warnings

**Steps to reproduce:**

Put `@ionic/app-scripts` in `devDependencies` in `package.json`

**Other information:**

dependency found by `npm ls babili`:
```
└─┬ @ionic/app-scripts@2.1.4
  └── babili@0.1.2
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Global packages are begging to shoot yourself in the foot, so I ran `npx ionic info`:
```

cli packages: (/Users/ssterling3/Documents/2017/IIT/Apps/Student Dashboard/mobile-dashboard/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : browser 4.1.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node  : v6.10.3
    npm   : 5.4.2
    OS    : macOS Sierra
    Xcode : Xcode 8.3.3 Build version 8E3004b
```

Node 6.10.3 is used to match the latest version [available in AWS Lambda](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html)

**Comment by danielsogl** [comment]
With the new release babili will be removed

**Comment by Polyergic** [comment]
We're currently devDepending on `"@ionic/app-scripts": "2.1.X"` (and generally basing our dependency versions on https://github.com/ionic-team/ionic2-app-base/blob/master/package.json).  

Will we have to update our dependencies to get the new release, or will it fall under "2.1.X"?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to move this issue over to the `ionic-team/ionic-app-scripts` repo. Please follow the issue over there for updates.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1230
