### ISSUE TITLE
Why when I run android, have a 'loading' in the screen, but IOS don't have.. and how to delete it.

### ISSUE THREAD

**Issue by YuyangHYY** [ionic-team/ionic#12923]
After I build ios and android successfully, IOS run without loading showing, but android have loading showing when I run my apps. How can I delete the loading

This is the android apps 'loading', when I open android apps.
![2017-09-19 15 09 42](https://user-images.githubusercontent.com/19391002/30579770-9d120014-9d4c-11e7-8c07-0d113d25e480.png)

![2017-09-19 15 11 42](https://user-images.githubusercontent.com/19391002/30579839-ed2b1a04-9d4c-11e7-900e-9c482549da43.png)

**Comment by YuyangHYY** [comment]
![screenshot_2017-09-19-15-02-00-56](https://user-images.githubusercontent.com/19391002/30579728-60ca9a6c-9d4c-11e7-822b-5f315ed715ea.png)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
