### ISSUE TITLE
Ionic Deploy snapshot applied to freshly installed ipa with higher version number

### ISSUE THREAD

**Issue by media4learning** [ionic-team/ionic#12922]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Install version 1.0.0 of app on ios.
Update app with Ionic Deploy snapshot. Snapshot versions set to min and max 1.0.0
Install version 1.0.1 - download from .plist link on remote server (Enterprise program)
Launch version 1.0.1 - most recent snapshot from version 1.0.0 is applied. AppVersion plugin is showing 1.0.1, but all other files are from the latest snapshot that shouldn't apply to 1.0.1
Close and relaunch version 1.0.1 - app now loads correct files for v 1.0.1 (ignores any snapshots from 1.0.0)

**Expected behavior:**
When installing new .ipa over an older version, no snapshot from previous versions should be loaded.

**Steps to reproduce:**
Install ipa.
ionic upload -n 'update for version 1.0.1' --nobuild
apply snapshot to app
change version number in config xml, export new ipa and install over previous version
launch new version - snapshot from previous version is loaded
Close and relaunch app, old snapshot is not longer loaded, and everything is loaded as expected
-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages: (/Users/chrisdelambert/Documents/stjohncpg/node_modules)

@ionic/cli-utils  : 1.10.2
ionic (Ionic CLI) : 3.10.3
global packages:

Cordova CLI : 7.0.1 
local packages:

@ionic/app-scripts : 2.1.4
Cordova Platforms  : android 6.2.3 ios 4.4.0
Ionic Framework    : ionic-angular 3.6.0
System:

Android SDK Tools : 26.0.2
ios-deploy        : 1.9.1 
ios-sim           : 6.0.0 
Node              : v8.1.4
npm               : 5.1.0 
OS                : macOS Sierra
Xcode             : Xcode 8.3.3 Build version 8E3004b

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This appears to be an Ionic Pro support issue. Please use the [Ionic Pro Support Portal](support.ionicjs.com) for this issue.

Thank you for using Ionic
