### ISSUE TITLE
bug: Blank Screen building app with --prod tag

### ISSUE THREAD

**Issue by labrada83** [ionic-team/ionic#12929]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>Current behavior:

App hangs with a white screen during startup on android emulators. After hours of debugging with no errors, I was able to find out that this issue happens only when the color array (theme/variables.scss) has more than 45 items and it's deployed using the --prod tag.

Note: The issue is only on android devices

Steps to reproduce:

1- $ ionic start TestProject blank
2- $ ionic cordova platform add android
3- Modify theme/variables.scss and add more than 45 items to color's array.
4- $ ionic cordova run android --prod

Repository:
https://github.com/labrada83/BlankScreen

Ionic Info:

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2
    Node              : v8.5.0
    npm               : 5.4.2
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b

Cordova requirements:

Requirements check results for android:
Java JDK: installed 1.8.0
Android SDK: installed true
Android target: installed android-26,android-25,android-24,android-23,android-22,android-21,android-20,android-19,android-18,android-17,android-16,android-15,android-14
Gradle: installed /Applications/Android Studio.app/Contents/gradle/gradle-3.2/bin/gradle</span>

<span is-issue-template></span>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is a known issue with no easy answer other than to reduce the number of colors that you have defined. Therefore I will close this issue and link to the existing open issue.

Here is the state of the current discussion: https://github.com/ionic-team/ionic-app-scripts/issues/506

Thank you for using Ionic
