### ISSUE TITLE
Wrong type for parameter "source" of FileTransfer.download: Expected string but got undefined

### ISSUE THREAD

**Issue by aeab13** [ionic-team/ionic#12936]
**Ionic version:**
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
I've created a new APP using the CLI and choosing the *conference* template.

I've pushed it to my Ionic Dashboard to test it in my phone using **Ionic View** but trying to open the app I've got the following error:
Wrong type for parameter "source" of FileTransfer.download: Expected string but got undefined.
![ionicscreenshot](https://user-images.githubusercontent.com/16917468/30639427-17340fce-9dff-11e7-8c4e-f0d29392ca3c.jpg)

**Expected behavior:**
The app should run without showing this error.

**Steps to reproduce:**
`ionic start TestApp`
-Select conference template
-Link to ionic dashboard
`cd TestApp`
`git push ionic master`
-Test in phone using ionic view

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This appears to be an issue with the Ionic Pro product. Please open a ticket for this on the [Ionic Pro Support](http://support.ionicjs.com) site.

Thank you for using Ionic
