### ISSUE TITLE
v1 misses 'CFBundleIconName' in config.xml for Info.plist

### ISSUE THREAD

**Issue by renege** [ionic-team/ionic#12939]
When trying to submit a V1 app to Apple since iOS 11 I get the following error:

> Missing Info.plist value - A value for the Info.plist key CFBundleIconName is missing in the bundle ‘foo.bar.sheep’. Apps that provide icons in the asset catalog must also provide this Info.plist key

How to add this via the ```config.xml```?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
