### ISSUE TITLE
ionic3.x  build apk is not running

### ISSUE THREAD

**Issue by xswolf** [ionic-team/ionic#12935]
I useing ionic3.x 

use "ionic build android"  command , Obtain apk is not running

error:
![qq 20170920162638](https://user-images.githubusercontent.com/7678277/30634107-84ac02fc-9e20-11e7-8e4b-e001455f2983.png)

I tryed set loadUrlTimeoutValue  ， but not success

**Comment by konrin** [comment]
@xswolf add in config.xml the line:
```
<platform name="android">
        <preference name="loadUrlTimeoutValue" value="700000" />
</platform>
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is not an issue with the Ionic Framework. It might be an issue that is better logged over in the https://github.com/ionic-team/ionic-app-scripts repo. If you log one there, please be sure to fill out the issue template.

This may also be best handled via community support. It is likely that someone else has run into this issue before. In that case, I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thank you for using Ionic
