### ISSUE TITLE
Not gettring provider when running --prod

### ISSUE THREAD

**Issue by rodriguesgm** [ionic-team/ionic#12934]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ **x**] **3.x**

**I'm submitting a ...**  (check one with "x")
[ **x**] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a custom provider  definition and injector class in my app.module.ts, so this way I can mock the provider to work in browser. But when I execute the command _ionic cordova run android --prod_, I don't get a instance of this provider. Running as dev mode, the provider is instantiate normally and the code works fine.

**Expected behavior:**
Running the command on prod mode should work as well as on dev mode

**Steps to reproduce:**
Create a project with a custom provider, you can check some examples on the links bellow. Run the project with _ionic cordova run android --prod_. Same behavior if run with _ionic cordova run browser --prod_

Links used to custom provider and injector
https://www.joshmorony.com/automating-mocks-in-ionic-native-3-x/
https://stackoverflow.com/questions/33970645/how-to-extend-a-component-with-dependency-injection-in-angular-2

**Related code:**

My app.module.ts
```
  providers: [
    { provide: ErrorHandler, useClass: IonicErrorHandler },
    {
      provide: Network,
      useFactory(platform: Platform) {
        return platform.is('cordova')
          ? new Network()
          : new NetworkMock();
      },
      deps: [Platform]
    },
  ...
})
export class AppModule {
    constructor(private injector: Injector) {
    	 MyInjector.instance = this.injector;
    }
}
```
My custom injector class

```
import { Injector } from "@angular/core";
export class MyInjector {	
    static instance: Injector;
}
```

**Other information:**

So, when I try to retrieve an instance of Network using the MyInjector it didn't work for prod mode, but works ok for dev mode.

```
MyInjector.instance.get(Network)
```

I even tried to put so console.log in the userFactory method of custom provider, but it only log when running dev mode, on prod, nothing happens. When I try to get an instance, on prod mode is always null

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by erwinokken** [comment]
Could it be related to https://github.com/angular/angular-cli/issues/4752 ?

**Comment by rodriguesgm** [comment]
@kensodemann Sure, this is the sample I created with the issue https://github.com/rodriguesgm/ionic_issue_12934

@erwinokken  I tried to fix with the solution they suggested, but I didn't work

thanks

**Comment by rodriguesgm** [comment]
Just to add some more comment. I do the same injection with the Http from @angular/http, and it works fine when running --prod.

**Comment by kensodemann** [comment]
I changed your code as such to get it to work (all in `app.module.ts`)

Added a factory function:

```ts
export function networkFactory(platform: Platform) {
  return platform.is('cordova') ? new Network() : new NetworkMock();
}
```

Changed how `Network` is provided:

```ts
    {
      provide: Network,
      useFactory: networkFactory,
      deps: [Platform]
    },
```

Please apply this mod to your app and let me know if it works.

**Comment by rodriguesgm** [comment]
@kensodemann Interested.. It worked. What's the difference? Is it a bug?
thanks man

**Comment by kensodemann** [comment]
The optimizer ends up making jibberish out of it the way you had it. I was actually somewhat surprised it worked at all when I saw your original code, but then I thought about it a bit and could see how that worked un-optimized.

I believe once we move to a newer version of Angular, you could change to an arrow function like they use in the [Angular docs](https://angular.io/api/core/FactoryProvider).

That is, something like this:

```ts
    {
        provide: Network,
        useFactory: (platform: Platform) => platform.is('cordova') ? new Network() : new NetworkMock(),
        deps: [Platform]
    },
```

That will not currently play nice with the optimizer right now though either.  I think once `ionic-angular 3.7.0` is released you can try using the arrow function like that if you wish.

Glad to hear it is working for you. I am going to close this.
