### ISSUE TITLE
Update Ionic Cordova Resources to Generate LaunchStoryBoardImages

### ISSUE THREAD

**Issue by selected-pixel-jameson** [ionic-team/ionic#12949]
Based on this stackoverflow post (https://stackoverflow.com/questions/46232812/cordova-app-not-displaying-correctly-on-iphone-x-simulator/46232813#46232813) and this PR (https://github.com/apache/cordova-plugin-statusbar/pull/85) it looks like the ability to generate LaunchStoryBoard Images (https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/index.html#launch-storyboard-images) is going to be a necessity. 

Maybe I'm missing something but it doesn't look like the ionic cordova resources cli command is generating these right now. I also don't see that listed as a cordova plugin so I'm not sure how Ionic is handling this.

**Comment by janpio** [comment]
Ionic CLI command `ionic cordova resources` uploads the source files to a server where they get processed and downloads the results and puts them in the correct places.

**Comment by peterpeterparker** [comment]
ionic cli >= 3.11.0 do generate one `launch storyboard image` respectively do generate `Default@2x~universal~anyany.png`

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Verified using version `3.12.0` of the CLI. Closing.

Thank you for using Ionic
