### ISSUE TITLE
Toggle does not display correctly when ion list up or down ios 11

### ISSUE THREAD

**Issue by javi124** [ionic-team/ionic#12943]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The handle momentarily disappears when the list is up or down 

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
Is the basic code example




```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    ios-deploy : 1.9.1 
    Node       : v8.1.4
    npm        : 5.4.0 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235 
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

Also, please fill in the steps to reproduce and the results of `ionic info`

Thanks for using Ionic!

**Comment by javi124** [comment]
<img width="383" alt="captura de pantalla 2017-09-20 a las 17 17 30" src="https://user-images.githubusercontent.com/22007165/30652266-440ceb5a-9e28-11e7-8440-d463cdb33f93.png">

**Comment by javi124** [comment]
I did not want to close it

**Comment by kensodemann** [comment]
OK, reopening... Also, love the screenshot!! Extra points for LOTR refs!!

Do you have that in a GitHub repo so I don't have to rerwite that?

**Comment by kensodemann** [comment]
I duplicated your issue in a test sample application that I have.

The issue went away when I switched from using UIWebView to using WKWebView (which will be the default in a future release).

For now, you can install WKWebView by installing the plugin from here: https://github.com/ionic-team/cordova-plugin-wkwebview-engine

I will close this issue. Please let me know if this works for you or not. If it does not, I will be happy to re-open the issue.

**Comment by javi124** [comment]
Yes, works for me.
Thank you.

**Comment by javi124** [comment]
Hi Ken, I install this plugins and works, but now the app crashes when I update the data from http server (to add markers) in native google maps that I have in the page one. I install too the wkwebview v 1.1.4, and works well, but the nav bar is not in position, there are a blank frame in the button of the screen.I do not know if you can help me with this, any ideas?

**Comment by kensodemann** [comment]
@javi124 - can you expand on what you mean by "crashes"? Do you get any particular errors in the console log? Is an exception screen being shown?  For now, I will assume you are having a CORS issue and direct you to the CORS section of our [WKWebView guide](http://ionicframework.com/docs/wkwebview/). You should probably review all items in that guide just to make sure.

Can you post a screenshot of your other issues?

Also, have you made the adjustments from this recent blog post?
http://blog.ionic.io/ios-11-checklist/

Please let me know if that all works for you.

**Comment by javi124** [comment]
Yes, there were things I had not contemplated from the blog.
Works fine now.
Thanks Ken

**Comment by kensodemann** [comment]
Excellent!! Glad to hear it.
