### ISSUE TITLE
bug: ionic views not rendering on iphone 7 plus

### ISSUE THREAD

**Issue by ecotech-yashwant** [ionic-team/ionic#12951]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>browser</span>

<span ionic-description>when on iPhone 7 plus mobile browser, when i logging in into my app its take me to a blank page and get stuck. I had to close the browser and reopen for it to work. Also seeing blank white area sometimes while typing into input fields.</span>

<span is-issue-template></span>

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-v1#319
