### ISSUE TITLE
Problems with JDK9?

### ISSUE THREAD

**Issue by arthurflor** [ionic-team/ionic#12954]
**Ionic version:**
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

**Current behavior:**
Recentemente atualizei o JDK para a versão 9 e desde então a criação de apk retorna o erro:
```
Requirements check failed for JDK 1.8 or greater.
```

Retorno do java -version: 
```
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

**Expected behavior:**
APK creation

**SIfteps to reproduce:**
The command:
```
ionic cordova build android --prod --release
```
**Other information:**
It's real problem from the ionic? Other softwares doesn't any problem with the new version.

**Ionic info:**

```
cli packages:

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.5.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.0.2
    Node              : v8.5.0
    npm               : 5.4.2 
    OS                : Linux 4.12

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

As this appears to be an issue with Ionic App Scripts and not with the Ionic Framework, I will move this issue to https://github.com/ionic-team/ionic-app-scripts. Please follow the issue over and provide any further feedback or information over there.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1237
