### ISSUE TITLE
Ionic tabs doesn’t update view while changing from tab to tab

### ISSUE THREAD

**Issue by Xdabier** [ionic-team/ionic#12957]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ionic tabs doesn't update view while changing from tab to tab, unless a pop appears, 
here is tab1  
![image](https://user-images.githubusercontent.com/20482799/30772749-2989dcb4-a05a-11e7-92ce-03e5311dcfe0.png)
and here it's the second tab files that's supposed to be highlighted in the tabs bar and zeros should be the numbers of files 
![image](https://user-images.githubusercontent.com/20482799/30772753-3e26d32a-a05a-11e7-9255-d19acff9de6a.png)
and here is how it updated when the alert showed
![image](https://user-images.githubusercontent.com/20482799/30772758-51c1be4a-a05a-11e7-96ef-cb2b54f4ef50.png)
 ..

**Expected behavior:**
the expected behavior here is that the tab's view updates whenever I change the tab

**SIfteps to reproduce:**
the weird part here there are no special steps to reproduce, because when I run `ionic serve` at first it works perfectly with no issues and when I reload the page, or it automatically reloads after a a new build, the issue is back.
**Related code:**
*My tabs.ts*
```
import {Component, NgZone} from '@angular/core';
import {AlertController, App, Events} from "ionic-angular";

import {FilesPage} from '../files/files';
import {UsersPage} from '../users/users';
import {LoginPage} from "../login/login";
import {ToastProvider} from "../../providers/toast/toast";
import {SyncerProvider} from "../../providers/syncer/syncer";

@Component({
  templateUrl: 'tabs.html'
})
export class TabsPage {

  tab1Root = UsersPage;
  tab2Root = FilesPage;

  constructor(public alert: AlertController, public app: App, public zone: NgZone,
              public toast: ToastProvider, public event: Events, public syncer: SyncerProvider) {

    this.event.subscribe('logout', () => this.logout());
  }
  ionViewDidLoad() {
    this.syncer.sync(false);
  }


  logout() {
    let alert = this.alert.create({
      title: "Log-out ?",
      message: 'Are you sure you want to log-out?',
      buttons: [{
        text: 'No',
        handler: () => {
          console.log('No clicked')
        }
      },
        {
          text: 'Yes',
          handler: () => {
            localStorage.removeItem('loggedIn');
            this.toast.showToast('See you soon! :)', 2000, 'bottom');
            this.app.getRootNav().setRoot(LoginPage);
          }
        }
      ]
    });
    alert.present();
  }
}
```
*my tabs.html*
```
<ion-tabs color="toolbar">
  <ion-tab [root]="tab1Root" tabTitle="Users" tabIcon="people"></ion-tab>
  <ion-tab [root]="tab2Root" tabTitle="Files" tabIcon="folder"></ion-tab>
</ion-tabs>

```

**Other information:**
I have this issue opened here in the ionic forum => https://forum.ionicframework.com/t/ionic-tabs-doesnt-update-view-while-changing-from-tab-to-tab/106439?u=xdabier

**Ionic info:** 

```
ionic info

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 25.2.5
    Node              : v7.10.1
    npm               : 4.2.0 
    OS                : Linux 4.4

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? The code you posted looks fine, but it is really hard to tell what the issue could be out of context like that.

Unless you are able to share your actual app, I would start with `ionic start ionic-tabs-issue tabs` and then take it just far enough to demonstrate your issue.

Thanks for using Ionic!

**Comment by Xdabier** [comment]
I'll do that right now

**Comment by Xdabier** [comment]
[here's the app ](https://github.com/Xdabier/ionic-tabs-issues)

**Comment by kensodemann** [comment]
@Xdabier - I notice that you closed this. Did you find a solution for your issue?

**Comment by Xdabier** [comment]
@kensodemann yes this reply [here](https://forum.ionicframework.com/t/ionic-tabs-doesnt-update-view-while-changing-from-tab-to-tab/106439/29?u=xdabierr) heleped me finding a way out.
The issue is that I was calling a plugin that is not zone aware before getting to my main view which is the tabs page, which have put all of my app out the angular zone, so I had to call `NgZone.run()` to fix the issue

**Comment by matejkramny** [comment]
perhaps the `setRoot` method of `NavController` could warn or run inside `NgZone`.. Thanks @Xdabier
