### ISSUE TITLE
node_modules/@angular/core/index"' has no exported member 'NgIterable'.

### ISSUE THREAD

**Issue by lovepreetsingh03** [ionic-team/ionic#12959]
hii,
i Update my ionic version than I facining a this error 
node_modules/@angular/core/index"' has no exported member 'NgIterable'.
node_modules/@angular/core/index"' has no exported member 'TrackByFunction'.
node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

this is my ionic info

cli packages: (F:\mobileApp\DrivekoolApp\node_modules)
    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:
    Cordova CLI : 7.0.1

local packages:
    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.1.2
    Ionic Framework    : ionic-angular 3.6.1

System:
    Node : v6.11.3
    OS   : Windows 10
    npm  : 3.10.10

please help me to get out soltion

**Comment by kensodemann** [comment]
What is in the `dependencies` section of your `package.json` file?

**Comment by lovepreetsingh03** [comment]
[dependencies.txt](https://github.com/ionic-team/ionic/files/1327561/dependencies.txt)

please find the attachment.

**Comment by kensodemann** [comment]
Your Angular versions are inconsistent. Currently, you have:

```
    "@angular/common": "^4.4.3",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
```

When using `ionic-angular@3.6.1` you should use version `4.1.3` of Angular, so those dependencies should look like this:

```
Your Angular versions are inconsistent. Currently, you have:

```
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@angular/platform-server": "4.1.3",
``` 

Note that the version is pinned at `4.1.3` (no '^' or '~').

**Comment by kensodemann** [comment]
Did making your dependencies consistent with what `ionic-angular@3.6.1` expects solve your issue? Please let me know. In the meantime, I am going to close this issue, but will be happy to reopen it if need be.
