### ISSUE TITLE
Actionsheet need more bottom spacing on iPhone X

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#12956]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[X ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] feature request

**Current behavior:**
The last action of an `actionsheet` is displayed to close from the home button on iPhoneX (see screenshot)

**Expected behavior:**
A bit of more spacing between the last action of an `actionsheet` and the home button on iPhoneX

**SIfteps to reproduce:**

Sample minimal application: https://github.com/peterpeterparker/ionic-iphonex

**Other information:**

<img width="411" alt="capture d ecran 2017-09-23 a 09 04 50" src="https://user-images.githubusercontent.com/16886711/30771021-a6dfea80-a03e-11e7-9d0a-b6841b71f1d5.png">

For example, share action sheet as a bottom-padding

<img width="412" alt="capture d ecran 2017-09-23 a 10 58 21" src="https://user-images.githubusercontent.com/16886711/30771725-44f93dac-a04e-11e7-8eed-8af40caefa99.png">

**Comment by kensodemann** [comment]
Thank you for checking on that. I had noticed that as well and informed the team that is working on the iPhone X adjustments. I had also noticed similar issues with the date picker and "bottom" toasts.

If you notice any others, please let me know. This information is very helpful to us.

**Comment by kensodemann** [comment]
I just tested this with `ionic-angular@3.7.0` and the issue is resolved. Please give `3.7.0` a try in combination with the [iOS 11 checklist](https://blog.ionic.io/ios-11-checklist/).

**Comment by peterpeterparker** [comment]
@kensodemann I could confirm that this issue is resolved. Bottom spacing of the action sheets is correct on `iPhone X` and is still correct too on `iPhone 8` for example (tested both with simulator).

thx guys for the enhancement!
