### ISSUE TITLE
Toolbar/Navbar height should be bigger on iPhone X

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#12952]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[X ] **2.x**
[ X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] feature request

**Current behavior:**
After updating WkWebView and the PR for cordova-plugin-statusbar, my app fits better the iPhone X but the Toolbar/Navbar height doesn't match. I compared then my app with the native app like `Photos` and noticed that on this device the Navbar/Toolbar height should be bigger.

**Expected behavior:**
Bigger Navbar/Toolbar height on iPhone X.

**Other information:**

<img width="411" alt="capture d ecran 2017-09-22 a 10 25 11" src="https://user-images.githubusercontent.com/16886711/30735921-017302de-9f81-11e7-81c5-9f9e6b1636c3.png">

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Can you verify that this cordova-status-bar plugin PR works for you? 
https://github.com/apache/cordova-plugin-statusbar/pull/87

Instructions on how to install until it is merged are here: https://blog.ionic.io/ios-11-checklist/

Thank you for using Ionic

**Comment by peterpeterparker** [comment]
@kensodemann updating the `ionic-angular` to nightly solved this issue

**Comment by hagan10** [comment]
@peterpeterparker I'm having the same issue. Could you take a look at my post?
https://forum.ionicframework.com/t/iphone-x-navbar-position/120931

**Comment by peterpeterparker** [comment]
@hagan10 I did followed up on the Ionic forum

**Comment by aiyuzhou** [comment]
@peterpeterparker I have same issue, but after I updated ionic-angular, it wasn't fixed, the Toolbar/Navbar height also doesn't match, any idea?

**Comment by peterpeterparker** [comment]
@aiyuzhou follow the checklist https://blog.ionicframework.com/ios-11-checklist/
if still don't work, post your questions on the https://forum.ionicframework.com
