### ISSUE TITLE
Footer Toolbar need more spacing on iPhone X

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#12953]
**Ionic version:**  (check one with "x")
[X ] **2.x**
[ X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] feature request

**Current behavior:**
After updating WkWebView and the PR for cordova-plugin-statusbar, my app fits better the iPhone X  but it looks like the content of the Toolbar inside a Footer would need more bottom spaces to avoid to display the content/buttons above the home button

This occurs in case of "tabs buttons" or button or segment inside a footer toolbar (see screenshots)

**Expected behavior:**
On iPhone X the toolbar in footers need a bit of more (bottom) spacing

** Code **

In case of segment:

    <ion-footer>
    <ion-toolbar>
        <ion-segment>
            <ion-segment-button value="something">
                <ion-icon name="pin"></ion-icon>
                <span>something</span>
            </ion-segment-button>
            <ion-segment-button value="something2">
                <ion-icon name="cash"></ion-icon>
                <span>something2</span>
            </ion-segment-button>
        </ion-segment>
    </ion-toolbar>
    </ion-footer>

button:

    <ion-footer>
    <ion-toolbar role="buttons" padding-left padding-right>
        <button ion-button (click)="doStuff()">
            Hello is it you?
        </button>
    </ion-toolbar>
    </ion-footer>
    
**Other information:**

<img width="409" alt="capture d ecran 2017-09-22 a 10 35 55" src="https://user-images.githubusercontent.com/16886711/30736269-5afdd3b4-9f82-11e7-9713-392dfba3df55.png">

<img width="416" alt="capture d ecran 2017-09-22 a 13 11 03" src="https://user-images.githubusercontent.com/16886711/30742004-8bcf8ab8-9f97-11e7-9f4a-324464f16a16.png">

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This should be fixed in the latest nightly build of `ionic-angular`. Please give that build a test as outlined here: https://blog.ionic.io/ios-11-checklist/

The changes in that nightly build will also be out in the next full release of `ionic-angular`.

I am going to close this, but will happily reopen it if those fixes do not work for you.

Thank you for using Ionic

**Comment by peterpeterparker** [comment]
@kensodemann nope sorry it didn't solved the issue.

did all the steps described in the blog post inclusive updating to nightly, still same issue as described above. could you reopen the issue plz?

**Comment by kensodemann** [comment]
Sure thing!

Can you provide a sample application demonstrating this issue via GitHub? It worked in my sample application, but that is really just a slightly modified version of the tabs starter.

**Comment by peterpeterparker** [comment]
I could try to build one from scratch, mine is a private repo...give me a couple of minutes

**Comment by peterpeterparker** [comment]
@kensodemann here you go

https://github.com/peterpeterparker/ionic-iphonex

right now I only added the code for a ion-footer / ion-toolbar / button

**Comment by peterpeterparker** [comment]
here you go @kensodemann

https://github.com/peterpeterparker/ionic-iphonex

I only displayed the issue with ion-footer > ion-toolbar > button (see home.html)

I didn't displayed the issue with ion-footer > ion-toolbar > ion-segments, if you wish me to add it let me know

NOTE: after the git clone you still will have to patch cordova-plugin-statusbar locally (I did that locally manually)

<img width="414" alt="capture d ecran 2017-09-22 a 14 06 55" src="https://user-images.githubusercontent.com/16886711/30743783-6868ab10-9f9f-11e7-9510-d3603d0cc4bf.png">

**Comment by kensodemann** [comment]
Thank you. We will have a look.

**Comment by mhartington** [comment]
Hmm, alright I know whats up. Right now we're only applying padding to ion-tabs for the bottom. I'll add the ion-footer padding as well

**Comment by kensodemann** [comment]
@peterpeterparker - when you get a chance, can you apply the following `ionic-angular` build to your project and let me know if it handles the remaining issues you have?

`npm install ionic-angular@3.6.1-201709221715 --save`

I tried it with your sample project and it worked for that case.

**Comment by peterpeterparker** [comment]
it works like a charm, ion-footer > ion-toolbar > button or segment has now the proper size on iPhone X (and still got the proper size on iPhone 7, tested both with Xcode simulator)

thx @kensodemann @mhartington

**Comment by peterpeterparker** [comment]
@kensodemann I've the feeling that a same improvement should be applied to `action sheets`

Therefore I opened a new feature issue: https://github.com/ionic-team/ionic/issues/12956

**Comment by arcanys-ivan** [comment]
my version of ionic-angular is 3.9.2, and seems `ion-footer` is not yet fixed for iPhoneX Devices, i still need to add some bottom margin in order to give some space on it

**Comment by davidst2017** [comment]
I have same problem as arcanys-ivan

**Comment by hueppee** [comment]
I have the same problem

Ionic:

   ionic (Ionic CLI)  : 4.0.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.4

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 5.0.13
   NodeJS            : v8.11.3 (/usr/local/bin/node)
   npm               : 5.6.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.2 Build version 9C40b


![simulator screen shot - iphone x - 2018-08-13 at 15 34 40](https://user-images.githubusercontent.com/22764168/44035331-849a061a-9f0f-11e8-9004-2ba55243b9a3.png)
![simulator screen shot - iphone x - 2018-08-13 at 15 40 48](https://user-images.githubusercontent.com/22764168/44035332-84d2dee0-9f0f-11e8-9b5d-1f0bd17aa290.png)
