### ISSUE TITLE
One signal not working when i build my app for production

### ISSUE THREAD

**Issue by gtzinos** [ionic-team/ionic#12961]
Hi guys,

I am developing an app with your great framework. I am using the plugin name one signal in my app and all working perfect on dev mode but when i run ionic cordova emulate android --prod then it can't find the one signal plugin. Also i am using lazy loading on my project.

Warnings

```
Native: tried calling OneSignal.startInit, but the OneSignal plugin is not installed.
vendor.js:1 Install the OneSignal plugin: 'ionic cordova plugin add onesignal-cordova-plugin'
vendor.js:1 Native: tried calling OneSignal.inFocusDisplaying, but the OneSignal plugin is not installed.
vendor.js:1 Install the OneSignal plugin: 'ionic cordova plugin add onesignal-cordova-plugin'
vendor.js:1 Native: tried calling OneSignal.handleNotificationReceived, but the OneSignal plugin is not installed.
vendor.js:1 Install the OneSignal plugin: 'ionic cordova plugin add onesignal-cordova-plugin'
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is not an issue with the Ionic Framework. It could be an issue with the scripts used to build the application  (https://github.com/ionic-team/ionic-app-scripts).

I will urge also that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).



Thanks for using Ionic!
