### ISSUE TITLE
Could I use the Ionic documents for my speech on Microsoft Tech Summit  2017, please?

### ISSUE THREAD

**Issue by yanxiaodi** [ionic-team/ionic#12974]
Hi, Ionic team,

I'm a software engineer from China. I'll take a public speech on Microsoft Tech Summit  2017, China. My speech is about how to develop a flexible, high-performance Hybrid App/SPA/PWA with Angular, TypeScript and Ionic. I'll demonstrate how to use Ionic to develop a simple app demo in a short time, including lazy loading, integration of the third party libraries, etc.

I have a question that could I use the documents and the code sample on the Ionic Official Site, please? Is there any problem with copyright? The code sample is easy to be implemented by myself. But can I use the description of Ionic directly? I want to propagate this amazing framework to more developers. But I need your authorization first.

Thank you very much!

**Comment by mlynch** [comment]
Hi @yanxiaodi, of course, we'd love that. The docs are Apache 2.0 licensed which is very permissive, there shouldn't be any problems. Good luck!

**Comment by yanxiaodi** [comment]
@mlynch Thank you for your kind reply.
