### ISSUE TITLE
docs(registerModeConfigs): empty page

### ISSUE THREAD

**Issue by danielsogl** [ionic-team/ionic#12973]
**Resources:**
No docs content avaiable: https://ionicframework.com/docs/api/config/registerModeConfigs/

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Comment by brandyscarney** [comment]
This issue was moved to ionic-team/ionic-site#1328
