### ISSUE TITLE
Ionic Package service Failing :  ld: framework not found IOSurface for architecture arm64

### ISSUE THREAD

**Issue by pvdyck** [ionic-team/ionic#12988]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

Build failing with 👍 
ld: framework not found IOSurface for architecture arm64

**Expected behavior:**
Build NOT failing => source code has *not* been changed.
Rebuilding does not work since 6 hours.
Did you upgrade the build machine to High Sierra ? it seems to be linked to the xcode version ?

**Steps to reproduce:**
look @ https://apps.ionic.io/app/7949705f/package

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! I am going to close this issue as it does not appear to be an Ionic Framework related issue (that is, a bug in `ionic-angular` itself).

It looks like you are using Ionic Pro to do your builds. Is that correct? If so, you should be using http://support.ionicjs.com to log this issue.

Thank you for using Ionic.
