### ISSUE TITLE
TypeError: msg.trim is not a function in Ionic project

### ISSUE THREAD

**Issue by Papamilo** [ionic-team/ionic#12989]
Ionic last version (3.6.1) on MacOS Sierra v 10.12.6

I am trying to start my first Ionic project following theses steps : Ionic framework get started page

But when I am writing in the terminal ionic serve (step 3) I have got this error message even if I run the Development server at http://localhost:8100 (my app is running but I still got this error message):

In my Ionic console I've got this error message:

`TypeError: msg.trim is not a function
at Logger.log (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/utils/logger.js:78:21)
at Logger.error (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/utils/logger.js:35:14)
at Object.<anonymous> (/usr/local/lib/node_modules/ionic/dist/index.js:261:22)
at throw (native)
at rejected (/usr/local/lib/node_modules/ionic/node_modules/tslib/tslib.js:94:69)
Also during the setup when I write the command sudo ionic start myApp tabs I have got this : Running command - failed! [ERROR] An error occurred while running npm install (exit code 1):`

Complete Error message in the the terminal (I am on macOS) is:

    `npm WARN deprecated babili@0.1.2: babili has been renamed to 
    babel-minify. Please update to babel-minify
    npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed 
    to babel-minify. Please update to babel-preset-minify
    npm WARN deprecated object-keys@0.2.0: Please update to the latest 
    object-keys

    > fsevents@1.1.2 install 
    /Users/emilio/TestIonic/myApp/node_modules/fsevents
    > node install

    [fsevents] Success: 
    "/Users/emilio/TestIonic/myApp/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" 
    already installed
    Pass --update-binary to reinstall or --build-from-source to recompile

    > node-sass@4.5.3 install 
    /Users/emilio/TestIonic/myApp/node_modules/node-sass
    > node scripts/install.js

    Unable to save binary 
    /Users/emilio/TestIonic/myApp/node_modules/node-sass/vendor/darwin-x64-48 
    : { Error: EACCES: permission denied, mkdir 
    '/Users/emilio/TestIonic/myApp/node_modules/node-sass/vendor'
         at Error (native)
         at Object.fs.mkdirSync (fs.js:924:18)
         at sync 
    (/Users/emilio/TestIonic/myApp/node_modules/mkdirp/index.js:71:13)
         at Function.sync 
    (/Users/emilio/TestIonic/myApp/node_modules/mkdirp/index.js:77:24)
         at checkAndDownloadBinary 
    (/Users/emilio/TestIonic/myApp/node_modules/node-sass/scripts/install.js:111:11)
         at Object.<anonymous> 
    (/Users/emilio/TestIonic/myApp/node_modules/node-sass/scripts/install.js:154:1)
         at Module._compile (module.js:570:32)
         at Object.Module._extensions..js (module.js:579:10)
         at Module.load (module.js:487:32)
         at tryModuleLoad (module.js:446:12)
       errno: -13,
       code: 'EACCES',
       syscall: 'mkdir',
       path: '/Users/emilio/TestIonic/myApp/node_modules/node-sass/vendor' }

    > uglifyjs-webpack-plugin@0.4.6 postinstall 
    /Users/emilio/TestIonic/myApp/node_modules/uglifyjs-webpack-plugin
    > node lib/post_install.js

    > node-sass@4.5.3 postinstall 
    /Users/emilio/TestIonic/myApp/node_modules/node-sass
    > node scripts/build.js

    Building: /usr/local/bin/node 
    /Users/emilio/TestIonic/myApp/node_modules/node-gyp/bin/node-gyp.js 
    rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= 
    --libsass_library=
    gyp info it worked if it ends with ok
    gyp verb cli [ '/usr/local/bin/node',
    gyp verb cli   
    '/Users/emilio/TestIonic/myApp/node_modules/node-gyp/bin/node-gyp.js',
    gyp verb cli   'rebuild',
    gyp verb cli   '--verbose',
    gyp verb cli   '--libsass_ext=',
    gyp verb cli   '--libsass_cflags=',
    gyp verb cli   '--libsass_ldflags=',
    gyp verb cli   '--libsass_library=' ]
    gyp info using node-gyp@3.6.2
    gyp info using node@6.11.3 | darwin | x64
    gyp verb command rebuild []
    gyp verb command clean []
    gyp verb clean removing "build" directory
    gyp verb command configure []
    gyp verb check python checking for Python executable "python2" in the 
    PATH
    gyp verb `which` failed Error: not found: python2
    gyp verb `which` failed     at getNotFoundError 
    (/Users/emilio/TestIonic/myApp/node_modules/which/which.js:13:12)
    gyp verb `which` failed     at F 
    (/Users/emilio/TestIonic/myApp/node_modules/which/which.js:68:19)
    gyp verb `which` failed     at E 
    (/Users/emilio/TestIonic/myApp/node_modules/which/which.js:80:29)
    gyp verb `which` failed     at 
    /Users/emilio/TestIonic/myApp/node_modules/which/which.js:89:16
    gyp verb `which` failed     at 
    /Users/emilio/TestIonic/myApp/node_modules/isexe/index.js:42:5
    gyp verb `which` failed     at 
    /Users/emilio/TestIonic/myApp/node_modules/isexe/mode.js:8:5
    gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
    gyp verb `which` failed  python2 { Error: not found: python2
    gyp verb `which` failed     at getNotFoundError 
    (/Users/emilio/TestIonic/myApp/node_modules/which/which.js:13:12)
    gyp verb `which` failed     at F 
    (/Users/emilio/TestIonic/myApp/node_modules/which/which.js:68:19)
    gyp verb `which` failed     at E 
    (/Users/emilio/TestIonic/myApp/node_modules/which/which.js:80:29)
    gyp verb `which` failed     at 
    /Users/emilio/TestIonic/myApp/node_modules/which/which.js:89:16
    gyp verb `which` failed     at 
    /Users/emilio/TestIonic/myApp/node_modules/isexe/index.js:42:5
    gyp verb `which` failed     at 
    /Users/emilio/TestIonic/myApp/node_modules/isexe/mode.js:8:5
    gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
    gyp verb `which` failed   stack: 'Error: not found: python2\n    at 
    getNotFoundError 
    (/Users/emilio/TestIonic/myApp/node_modules/which/which.js:13:12)\n    
    at F (/Users/emilio/TestIonic/myApp/node_modules/which/which.js:68:19)\n 
       at E 
    (/Users/emilio/TestIonic/myApp/node_modules/which/which.js:80:29)\n    
    at /Users/emilio/TestIonic/myApp/node_modules/which/which.js:89:16\n    
    at /Users/emilio/TestIonic/myApp/node_modules/isexe/index.js:42:5\n    
    at /Users/emilio/TestIonic/myApp/node_modules/isexe/mode.js:8:5\n    at 
    FSReqWrap.oncomplete (fs.js:123:15)',
    gyp verb `which` failed   code: 'ENOENT' }
    gyp verb check python checking for Python executable "python" in the 
    PATH
    gyp verb `which` succeeded python /usr/bin/python
    gyp verb check python version `/usr/bin/python -c "import platform; 
    print(platform.python_version());"` returned: "2.7.10\n"
    gyp verb get node dir no --target version specified, falling back to 
    host node version: 6.11.3
    gyp verb command install [ '6.11.3' ]
    gyp verb install input version string "6.11.3"
    gyp verb install installing version: 6.11.3
    gyp verb install --ensure was passed, so won't reinstall if already 
    installed
    gyp verb install version is already installed, need to check 
    "installVersion"
    gyp verb got "installVersion" 9
    gyp verb needs "installVersion" 9
    gyp verb install version is good
    gyp verb get node dir target node version installed: 6.11.3
    gyp verb build dir attempting to create "build" dir: 
    /Users/emilio/TestIonic/myApp/node_modules/node-sass/build
    gyp ERR! configure error 
    gyp ERR! stack Error: EACCES: permission denied, mkdir 
    '/Users/emilio/TestIonic/myApp/node_modules/node-sass/build'
    gyp ERR! stack     at Error (native)
    gyp ERR! System Darwin 16.7.0
    gyp ERR! command "/usr/local/bin/node" 
    "/Users/emilio/TestIonic/myApp/node_modules/node-gyp/bin/node-gyp.js" 
    "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" 
    "--libsass_ldflags=" "--libsass_library="
    gyp ERR! cwd /Users/emilio/TestIonic/myApp/node_modules/node-sass
    gyp ERR! node -v v6.11.3
    gyp ERR! node-gyp -v v3.6.2
    gyp ERR! not ok 
    Build failed with error code: 1
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the node-sass@4.5.3 postinstall script.
    npm ERR! This is probably not a problem with npm. There is likely 
    additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/emilio/.npm/_logs/2017-09-25T08_05_30_711Z-debug.log`

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). This forum is for reporting Ionic Framework bugs or for making Ionic Framework related feature requests.

One question I have is on this statement, however: "Also during the setup when I write the command sudo ionic start myApp tabs I have got this"

Did you do `sudo ionic start myApp tabs`? (with the `sudo`)?

If so, don't.

For the `npm -g install cordova ionic` you may or may not need to use `sudo` or be admin depending on your platform and how you have `npm` installed since it is writing to a system area.

For the `ionic start myApp tabs` however, you should never have to use `sudo` as you should be creating your app under your own home directory somewhere and should have all required access there.

My guess at what happened is that you created your app via `sudo ionic start ...` thus creating it with one set of permissions, then you try running it using `ionic serve` which is using your own permissions. Thus you are getting the `EACCES` errors shown above, which is leading to all of your other trouble.

That is just a guess, though, based on what you wrote above. Please double check that you are doing everything as the correct user.

Thanks for using Ionic!

**Comment by Papamilo** [comment]
Thanks for your help i'll try this out 👍
