### ISSUE TITLE
This is a question about page jumps

### ISSUE THREAD

**Issue by Overflowhiddenno** [ionic-team/ionic#12986]
I set up a tabs page, A, B, C. like this: 
tab1Root: any = HomePage;
tab2Root: any = AboutPage;
tab3Root: any = ContactPage;
When I jump from PageB to a new pageC
**The URL becomes ：“http://localhost:8102/#/about/shopping”;**
when I reload the shopping page,I have a error:  **Component AboutPage is not part of any NgModule or the module has not been imported into your module.** 
I'm newcomer, hold someone can help me;
here are my code:
`about.ts:

import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';

@IonicPage()
@Component({
  selector: 'page-about',
  templateUrl: 'about.html',
})
export class AboutPage {
  lists = Lists
  constructor(public navCtrl: NavController, public navParams: NavParams) {
  }
  
  ionViewDidLoad() {
    
  }
  openPage(page){
    this.navCtrl.push(page)
  }
}

about.module.ts

import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { AboutPage } from './about';

@NgModule({
  declarations: [
    AboutPage,
  ],
  imports: [
    IonicPageModule.forChild(AboutPage),
  ],
})
export class AboutPageModule {}

`

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
