### ISSUE TITLE
ru.js:7 Uncaught TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by SquallX** [ionic-team/ionic#12981]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I try to run Ionic Serve, I have an error message but when I try it on private page, it works. 

**Expected behavior:**
`
Runtime Error
Object prototype may only be an Object or null: undefined
Stack
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (http://localhost:8100/build/vendor.js:98997:9)
    at http://localhost:8100/build/vendor.js:99030:5
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:99043:2)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.470 (http://localhost:8100/build/main.js:3826:86)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.428 (http://localhost:8100/build/main.js:3421:73)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.423 (http://localhost:8100/build/main.js:3401:70)
Ionic Framework: 3.5.3
Ionic App Scripts: 2.1.4
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 7.5.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/alexandre/Sites/app-mobiles/leRugbynistere/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 25.2.4
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.13 
    Node              : v7.5.0
    npm               : 4.1.2 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

Misc:

    backend : pro

```

**Comment by SquallX** [comment]
Hi,

I've try to work with a fresh install, an I've the same error just after the install...

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

If after trying a fresh install as @SquallX suggests this continues to be an issue, please open an issue against the https://github.com/ionic-team/ionic-app-scripts repo.

Thank you for using Ionic
