### ISSUE TITLE
Can I use ionic CLI generate pages in my own floder ？

### ISSUE THREAD

**Issue by JiaXinYi** [ionic-team/ionic#12984]
like this
ionic g page hello
how can I generate in mypages folder，not in pages？
no move folder~

![image](https://user-images.githubusercontent.com/18085971/30842303-fd567e2a-a2b3-11e7-93c0-8e7a8da6c002.png)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
