### ISSUE TITLE
Standalone ion-checkbox is still clickable when disabled

### ISSUE THREAD

**Issue by wilgert** [ionic-team/ionic#12994]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When you use an `ion-checkbox` outside of an `ion-item` but inside a `label` it is still possible to click the checkbox because the click event on the `label` is propagated to the button.

**Expected behavior:**
The button is disabled when the checkbox is disabled.

**Steps to reproduce:**
`<label><ion-checkbox disabled="true"></ion-checkbox></label>`

**Related code:**
http://plnkr.co/edit/dHW9WereNR2v8OXoCv05?p=preview

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us and for providing a pull request! We will have a look at it.

Thank you for using Ionic
