### ISSUE TITLE
docs: native android-permissions plugin usage is wrong

### ISSUE THREAD

**Issue by smoral** [ionic-team/ionic#12998]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>browser</span>

<span ionic-description>De usage documentation in https://ionicframework.com/docs/native/android-permissions/ its wrong. Success response on checkPermission method has as result an object indicating if the app has permission, for example: {"hasPermission":false}.</span>

<span is-issue-template></span>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is not an Ionic Framework issue. I am moving this to the https://github.com/ionic-team/ionic-native repository. Please follow the issue over there.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-native#2000
