### ISSUE TITLE
sass variables not working when using color attribute for ion-tabs

### ISSUE THREAD

**Issue by xyboox** [ionic-team/ionic#12999]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Setting sass variables, such as $tabs-ios-tab-text-color, $tabs-ios-tab-text-color-active, $tabs-md-tab-text-color, $tabs-md-tab-text-color-active in /theme/variables.scss file are not being used if "color" attribute is used when declaring <ion-tabs>. 

**Expected behavior:**

CSS style should consider sass variables declared in /theme/variables.scss file when using color attribute with <ion-tabs>

**Steps to reproduce:**

`<ion-tabs color="secondary">
<ion-tab [root]="HomePage"></ion-tab>
<ion-tab [root]="NewsPage"></ion-tab>
<ion-tabs>`

in /theme/variables.scss:
```
$colors: (
primary: #212121,
secondary: #b8d63c
);
$tabs-ios-tab-text-color: color($colors, primary);
$tabs-ios-tab-text-color-active: color($colors, primary);
$tabs-md-tab-text-color: color($colors, primary);
$tabs-md-tab-text-color-active: color($colors, primary);

```
**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    ios-deploy : 1.9.0 
    ios-sim    : 6.1.1 
    Node       : v6.11.3
    npm        : 5.3.0 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy
```

**Comment by brandyscarney** [comment]
Thanks for the issue! This is the expected behavior. Styling the sass variables for the tabs only modifies the default tabs. If you add a color to the tabs then it performs some operations to determine what the text color should be. 

If you're looking to override the text color for `secondary`, you can do something like this:

```
$colors: (
  primary:    #212121,
  secondary:  (
    base: #b8d63c,
    contrast: #212121
  )
);
```

**Comment by xyboox** [comment]
Thanks Brandy, this works. Just a hint: maybe this spec should be made ( more? ) visible in the documentation as I couldn't find it. Regards!

**Comment by brandyscarney** [comment]
@xyboox We have a section on it in Theming here: http://ionicframework.com/docs/theming/theming-your-app/

We're always interested in ways to improve though if you have any ideas. 🙂
