### ISSUE TITLE
[INFO] Fetching app base (https://github.com/ionic-team/ionic-app-base/archive/master.tar.gz) × Downloading - failed! Error: getaddrinfo ENOTFOUND github.com github.com:443     at errnoException (dns.js:28:10)  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

### ISSUE THREAD

**Issue by Navitam** [ionic-team/ionic#12993]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please.

Also, based on the title of this issue, this is not an Ionic Framework issue. A better place for this might be https://github.com/ionic-team/ionic-cli.

If I had to venture a guess, it seems like it might be an issue with your network or perhaps you are currently behind a corporate firewall that is blocking this for some reason or something like that.

Thanks for using Ionic!
