### ISSUE TITLE
ion-label floating cursor in very odd position

### ISSUE THREAD

**Issue by philipbrack** [ionic-team/ionic#12990]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**
When using <ion-label floating> in the most vanilla way with ios 11 on Iphone 6 the cursor when the keyboard appears is a bad location.  This did not appear in ios 10.

![img_0950](https://user-images.githubusercontent.com/13687270/30895963-857f5aa8-a302-11e7-8a29-39aed463e156.jpg)

**Expected behavior:**
Expect see cursor inline with inserted text.

**Related code:**

<ion-content padding>
  <ion-list>

    <ion-item>
      <ion-label floating>Username</ion-label>
      <ion-input type="text"></ion-input>
    </ion-item>

    <ion-item>
      <ion-label floating>Password</ion-label>
      <ion-input type="password"></ion-input>
    </ion-item>

  </ion-list>
</ion-content>

**Ionic info:** 

```

cli packages: (/Users/pbrack/.nvm/versions/node/v8.5.0/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    ios-deploy : 1.9.2
    ios-sim    : 5.0.8
    Node       : v8.5.0
    npm        : 5.3.0
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235

Misc:

    backend : legacy

```

**Comment by philipbrack** [comment]
github [sample project](https://github.com/philipbrack/ionic_12990) uploaded.  ionic cordova build ios and run on device will mainfest issue.  FYI this is simply the blank starter project using the prescribed [floating label example](https://ionicframework.com/docs/components/#floating-labels).

**Comment by mino922** [comment]
+1. Issue seems to have popped up after upgrading to iOS 11.

**Comment by kensodemann** [comment]
I cannot duplicate this with your sample project. I tried on an iPhone 7 running iOS 11 and on an iPhone 6 simulator also running iOS 11.

**Comment by philipbrack** [comment]
You know what...  In playing with my sample this afternoon, it appears to only happen sometimes when I click on the label itself.  Never seems to happen if I click toward the right of the screen.

**Comment by philipbrack** [comment]
I took my app where I discovered this initially and remove the viewport-fit=cover in the meta tag for my index.html.  
`<meta name="viewport"
        content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">`
After this change the cursor shows up in the correct place when I interact with the inputs and the keyboard.

However it did something weird to the status bar.
![img_0951](https://user-images.githubusercontent.com/13687270/30947276-a3d59dc6-a3bd-11e7-8a74-e0d39c2f4b5a.jpg)

**Comment by philipbrack** [comment]
I fixed my issue.  with the following-
```

ionic cordova plugin add cordova-plugin-ionic-webview --save
ionic cordova platform update ios
rm -rf ./plugins
ionic cordova prepare
ionic cordova build ios

```
for some reason before when I installed the cordova-plugin-ionic-webview it wasn't saved.
