### ISSUE TITLE
CLI commands never stop

### ISSUE THREAD

**Issue by javilingt** [ionic-team/ionic#12997]
Hi, I am having troubles with the CLI commands, all the commands works, but I must to stop them manually with ctrl+C beacuse they never stop themself. Ionic version is 3.12.0

If I use 'ionic cordova platform add ios', the result is the next

   Running command done!

But not stop the proccess, I need that the proccess finish because I am launching several commands from Jenkins. All works perfectly until I arrive to the ionic commands.

I have install @ionic/cli-plugin-proxy but it doesnt fix nothing.

Thx

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am closing this as it is not an Ionic Framework issue but rather a CLI issue. It appears that you have already opened this same issue in the ionic-cli repo.

Thank you for using Ionic
