### ISSUE TITLE
support Angular4？

### ISSUE THREAD

**Issue by xingag** [ionic-team/ionic#13002]
whether support Angular4 or not ？

**Comment by rdlabo** [comment]
Ionic v3(current_version) support Angular 4.

**Comment by chandanch** [comment]
Yes, ionic 3 supports Angular 4.

**Comment by xingag** [comment]
thanks a lot

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to close this as it is not an issue, and it appears that you got your question answered.

Just for future reference, this issue list is for reporting bugs with or requesting new features for the Ionic Framework. For general questions, please ask your questions on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

This question would probably be more appropriate to the Slack channel given its nature.

Thank you for using Ionic
