### ISSUE TITLE
ARkit?

### ISSUE THREAD

**Issue by shaneparsons** [ionic-team/ionic#13008]
**Ionic version:**
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**
[ ] bug report
[x] feature request

This might not belong here, and please move it if it doesn't, but with the recent release of ARKit (iOS' AR framework) I've been wondering if there will ever be a possibility to integrate it with Ionic? I haven't looked too much into ARKit yet, but I have tried to integrate some Cordova AR platforms / plugins into Ionic in the past with undesirable results. I figured that since iOS "nativley" supports AR now, that it may be a step in the right direction.

I realize that this would be an iOS only solution, but I imagine that Android has their own version of ARkit that could fill the void.

I'd love to hear your view / feedback on this. Is this something that would be better integrated into Cordova directly rather than Ionic?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

At first glance, this sounds like it would be something best supported via a Cordova plugin wrapped by Ionic Native.

There is an #ionic-native channel on our [Ionic Worldwide Slack](https://ionicworldwide.herokuapp.com/). That would probably be the best place to start the conversation on this.

Thank you for using Ionic
