### ISSUE TITLE
Navigation between complex page is extremely slow

### ISSUE THREAD

**Issue by alshimaa14** [ionic-team/ionic#13004]
I'm using Ionic2, I noticed that navigating between complex pages or opening complex page is very slow, Are there solutions for this problem?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

You may need to provide some code for people to look at. There are multiple reasons navigation could be slow between pages. Some that I have personally run into in my own apps include: slow data fetching, fetching too much data, trying to do complex data manipulation with a large data set, binding too much data at one time. There are ways to fix each of these, but how you do that is highly dependent on what you are doing in the first place.

Thanks for using Ionic!
