### ISSUE TITLE
why ion-searchbar doesn‘t has ionBlur and ionFocus but still can use and work well?

### ISSUE THREAD

**Issue by woodstream** [ionic-team/ionic#13006]
ionBlur and ionFocus had been removed from ion-searchbar since version 3.1.0:
https://github.com/ionic-team/ionic/blob/master/src/components/searchbar/searchbar.ts

but now still can use like this and  work well:
<ion-searchbar (ionBlur)="checkBlur()" (ionFocus)="checkFocus()"></ion-searchbar>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Please only use this issue list to either report bugs with the Ionic Framework or to request new features. A question like you have here would be better discussed on our [slack channel](https://ionicworldwide.herokuapp.com/).

To answer your question, look at the code you linked. You will see that this class extends the BaseInput class. So go look at the code for the BaseInput class and you will find your answers.

Thank you for using Ionic
