### ISSUE TITLE
Ionic 2/3: Keyboard covers input inside grid component

### ISSUE THREAD

**Issue by daveshirman** [ionic-team/ionic#13009]
This is a serious issue and has received absolutely no reply from anyone at Ionic.  Can someone please look at this issue and reply.  I am not the only one experiencing it and it is ruining using forms with inputs and they are hidden/randomly positioned it seems behind the keyboard!

#10629

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Please add your comment to the issue itself, not start a new issue. Keyboard issues are one of several issues we are looking at tackling in the near future (there are several that we have tagged, and I just added the tag to the one you linked).

Thank you for using Ionic
