### ISSUE TITLE
Faild to fetch plugin via registry

### ISSUE THREAD

**Issue by iamAloTheGreat** [ionic-team/ionic#13005]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Failed to Fetch a plugin (specifically a native plugin) or problem in adding a cordova plugin

below is the error message in the terminal:
`> cordova plugin add cordova-plugin-browsertab --save
✖ Running command - failed!
[ERROR] An error occurred while running cordova plugin add cordova-plugin-browsertab --save (exit code 1):

        Error: Failed to fetch plugin cordova-plugin-browsertab via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: npm: Command failed with exit code 194 Error output:
        npm ERR! path /Users/aloimmaculata/Documents/Sushi Joint latest
        Project/SushiJoint/node_modules/cordova-plugin-add-swift-support/package.json
        npm ERR! code ELOOP
        npm ERR! errno -62
        npm ERR! syscall open
        npm ERR! ELOOP: too many symbolic links encountered, open '/Users/aloimmaculata/Documents/Sushi
        Joint latest Project/SushiJoint/node_modules/cordova-plugin-add-swift-support/package.json'

        ┌──────────────────────────────────────────────────────────────────┐
        │                     npm update check failed                      │
        │               Try running with sudo or get access                │
        │               to the local update config store via               │
        │ sudo chown -R $USER:$(id -gn $USER) /Users/aloimmaculata/.config │
        └──────────────────────────────────────────────────────────────────┘

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /Users/aloimmaculata/.npm/_logs/2017-09-28T08_31_34_637Z-debug.log`

**Expected behavior:**

Should add the plugin

**Steps to reproduce:**

**Related code:**

```
cordova plugin add cordova-plugin-browsertab --save
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.1
    Node       : v8.2.1
    npm        : 5.4.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to close this as it is not an issue with the Ionic Framework.

You should search the issues lists of the following two repos first to see if there are any open or closed issues matching yours:
https://github.com/ionic-team/ionic-cli
https://github.com/ionic-team/ionic-native

If you don't find any hits there, I suggest opening an issue in the https://github.com/ionic-team/ionic-cli repo.

Thank you for using Ionic
