### ISSUE TITLE
Navigation History (Forwards and Backwards)

### ISSUE THREAD

**Issue by elliotstoner** [ionic-team/ionic#13011]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request

**Current behavior:**
Ionic doesn't preserve pages after they have been popped off the navigation stack. In some instances, this behavior is expected and wanted. In other cases, it would be helpful for a user to hit a back button (pop) and then go forward again (push) to that page, saving the page's [user-edited] content (same behavior as when popping to a previous page - the [user-edited] content is still there).

**Expected behavior:**
I've thought of and attempted to implement a few different options:

- popSaveHistory() - identical to pop(), except it adds the page to a "history stack" and skips any destruction of the page _(I need help with the skipping the destruction part)_
- pushTo(requestedPage) - loops through the history stack and pops (from history)/pushes (to nav) pages one by one until a page of the same type of the requestedPage is popped/pushed. If the end of the history stack is reached without a match, it pushes a new page
- pushOrKillAll(requestedPage) - checks the history stack to see if the next page to be popped is of the same type of the requestedPage; if it is, the popped page from the history stack is pushed; if it is not, the requestedPage is pushed and the history stack is cleared (similar to current browser functionality for plain HTML pages)
- pushBlind() - attempts to push the next page from the history stack - if there are no pages, it returns false

My implementations are basically wrappers around pop() and push() - my experience in coding source code for a language is... none 😄 . I would love to see this implemented (or understand why it wouldn't/shouldn't, if there's a best practice I don't know about), but I need help to get there!

**Steps to reproduce:**
N/a

**Related code:**

https://github.com/elliotstoner/ionic/blob/NavHistory/src/navigation/nav-controller-base.ts (lines 112-170)
https://github.com/elliotstoner/ionic/blob/NavHistory/src/navigation/nav-controller.ts (interface)

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

System:
    Node : v6.11.2
    npm  : 5.4.2 
    OS   : macOS Sierra

Misc:
    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#312
