### ISSUE TITLE
iOS 11 Floating Cursor Above Ion-SearchBar

### ISSUE THREAD

**Issue by mino922** [ionic-team/ionic#13013]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When I click on an ion-search bar, the cursor appears to float above and is not inline with the input area. 

**Expected behavior:**

The cursor should be inline with the input field. This was working correctly in iOS 10, but not longer in iOS 11

**Steps to reproduce:**

Click on the ion-searchbar in the project below.

[Here is a video demoing the problem on an iPhone 6s:](https://raw.githubusercontent.com/mino922/ionSearchBar-Issue/master/Image%20uploaded%20from%20iOS.MP4)

**Related code:**

[Sample Project](https://github.com/mino922/ionSearchBar-Issue)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.0

System:

    ios-deploy : 1.9.1 
    ios-sim    : 5.0.8 
    Node       : v6.11.2
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy


```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Installing the WKWebView plugin took care of the issue for me. https://github.com/ionic-team/cordova-plugin-ionic-webview#installation-instructions. Please give that a try and let me know if that took care of it for you.

Be sure to have a look at this doc as well: http://ionicframework.com/docs/wkwebview/

Side Note: This seems to be weirdly specific to the iPhone 6s. Could not duplicate on my iPhone 7 nor on any sim I tried other than iPhone 6s. Very strange.

Thank you for using Ionic

**Comment by mqasem92** [comment]
@kensodemann I have the same issue here the cursor is not stable when foucing on the text input or scrolling the page.

WKWebView plugin installed and configured, but the problem still on IPhone 6s and IPhone 7 plus 
 with IOS11.1

Any advice please ?

**Comment by mino922** [comment]
I'm having trouble getting my app to run with that plugin installed. I looked at the additional documentation you provided, but not having much luck. 

Here is the error I get in xcode console _libc++abi.dylib: terminating with uncaught exception of type NSException_ 

It seems to be pointing to this section of code:

`#import <UIKit/UIKit.h>

int main(int argc, char* argv[])
{
    @autoreleasepool {
        int retVal = UIApplicationMain(argc, argv, nil, @"AppDelegate");
        return retVal;
    }
}`

**Comment by mqasem92** [comment]
@mino922 are you fix your issue ?

**Comment by kensodemann** [comment]
@mino922 - is that happen in the sample app for you as well, or only in you actually application? It _did not_ happen for me in the sample app. If it does not happen in the sample app for you either but does happen in your app, then we have some work to do to determine what specific difference(s) between the apps lead to the issue.

Regardless, you should log an issue in the https://github.com/ionic-team/cordova-plugin-ionic-webview repo about that.

**Comment by kensodemann** [comment]
@mqasem92 - the issue you describe sounds more like #12992, this issue is specific to the IonSearchBar and (at least in my testing) appears to be specific to the iPhone6s when running iOS 11.

**Comment by mqasem92** [comment]
@kensodemann Yes, u're right.
I'm sorry for this confused, I'll be updated on this one  #12992

**Comment by mino922** [comment]
@kensodemann it only happens in my actual app. Works fine in the sample I provided. 

Any thoughts on where I should begin my troubleshooting? 

I will also post on the repo you provided. 

Thanks.

**Comment by mino922** [comment]
@kensodemann [Here is the issue, if you'd like to follow](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/7)

**Comment by mhartington** [comment]
Hmm, Im not able to replicate on my end using the lates wkwebview plugin and the nightly version of Ionic. Could you test this and confrm @mino922

**Comment by mino922** [comment]
There is an issue with wkwebview plugin and cordova-plugin-background-mode. My app requires cordova-plugin-background-mode, but I did a quick test and removed that plugin and the floating cursor issue went away. However, with wkwebview enabled I am seeing other issues.

Is there a solution to this problem that does not include the wkwebview plugin?

**Comment by Tyler-Darby** [comment]
I started facing this issue after applying `viewport-fit=cover` to fix the status bar issue that came with iOS 11. The cursor floats above any inputs for me.

**Comment by mhartington** [comment]
@Tyler-Darby do you have a sample project?

**Comment by mino922** [comment]
I found a bug in my code, which was causing some of the issues I was seeing with wkwebview enabled. That is now resolved. 

The floating cursor issue is no longer an issue. I just have a problem using wkwebview and cordova-background-mode in conjunction. I opened an issue on that page, but have yet to hear anything.

**Comment by mhartington** [comment]
the background plugin has a PR that should address this, but the plugin is not using a public/documented APIs so there's a chance Apple will reject an App with it or even break when Apple releases a new OS version.

**Comment by mino922** [comment]
@mhartington What do you mean by PR? 

Are there any alternatives to the background plugin?

**Comment by Tyler-Darby** [comment]
@mhartington I'll try to repro in a fresh project but right now all I have is my company project. I'll get back on that in a bit.

**Comment by mhartington** [comment]
Any luck on that demo @Tyler-Darby ?

**Comment by Tyler-Darby** [comment]
@mhartington When I upgraded to WKWebView the problem resolved itself. I can try to repro on UIWebView at some point if you need me to but it seems that WKWebView solved it for me.

**Comment by ggravand** [comment]
Please also address this problem on UIWebView as WKWebView does not work well with the search bar and hence prevents me from using WKWebView at all. For instance, WKWebView prevents setting focus programmatically (e.g. see https://github.com/ionic-team/ionic/issues/11453) - some has made various hacks and patches to make it work, but it still is not possible in my use cases).

**Comment by ourarash** [comment]
I have the same problem with UIWebView, and viewport-fit=cover. I cannot use WKWebView because it has issues with resizing pictures.

**Comment by mhartington** [comment]
@ourarash WKWebview is going to be a hard requirement moving forward as UIwebview has some serious issues involving the safe-layouts values we now use in the framework
