### ISSUE TITLE
model and parent component are using the same child component ,the modal will be error

### ISSUE THREAD

**Issue by DerekMar** [ionic-team/ionic#13018]
![tim 20170929172053](https://user-images.githubusercontent.com/20637828/31009603-a354c93e-a53a-11e7-87c5-0f6fc169dc87.png)
this is parent component html
![image](https://user-images.githubusercontent.com/20637828/31009720-07c98896-a53b-11e7-94f7-5a826cc9092d.png)
this is model's html
![image](https://user-images.githubusercontent.com/20637828/31009753-24687278-a53b-11e7-8d15-33003d1777c7.png)

I wrote an ionicpage with modal,and using the component 'leafletlayerlist' both of the parentp page and modal. but when I open then modal,it will be error!
this is error
![image](https://user-images.githubusercontent.com/20637828/31009795-3d654198-a53b-11e7-8f01-7c6b4261bd79.png)

```

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please.

Also please provide a sample application demonstrating the issue you are having and share it via GitHub or StackBlitz. This will be especially important in your case as this seems like a somewhat complex scenario and I want to make sure we are properly addressing your actual issue.

Thanks for using Ionic!
