### ISSUE TITLE
iOS 11 Keyboard Accessory Bar Arrows

### ISSUE THREAD

**Issue by cp16** [ionic-team/ionic#13012]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[X ] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

On a page with multiple ion-inputs, when the keyboard is displayed with the accessory bar navigation arrows, the focus is not moved when the down arrow is selected resulting in the cursor moving to the next input but focus not moving to the next input on iOS 11.

**Expected behavior:**

When the accessory bar navigation arrow is selected, both the cursor and focus should move down similar to previous versions of iOS.

**Steps to reproduce:**

On a page with multiple inputs:
1. Select an input.
2. Select the down arrow.
3. Note that the cursor moves down but the focus does not.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by brunoAltinet** [comment]
+1. The issue is present on previous versions too, focus moves but the page doesn't scroll to the focused field if the field is below the fold. the expected behaviour can be seen on any simple form page opened in iOS device, eg. https://www.w3schools.com/html/html_forms.asp. When in latest ionic app, this does not happen.

**Comment by cp16** [comment]
[https://github.com/cp16/Ionic_Keyboard_iOS11](Example)

This is specific to iOS 11. Previous to iOS 11, native.keyboardshow would be called each time the arrow button is selected to move the focus.

**Comment by mhartington** [comment]
@cp16  it doesn't look like you added any keyboard specific changes to the app. I just cloned it and it's setup as a default sidemenu template. Would you be able to copy/paste some code here?

**Comment by mhartington** [comment]
Any luck on a more up to date demo @cp16 ?

**Comment by cp16** [comment]
Sorry for the delay. I have updated the repo to include the keyboard configuration and ion-inputs

**Comment by SopoB** [comment]
Is this issue resolved?

**Comment by Yuripetusko** [comment]
Still happening to me using latest version of `cordova-plugin-ionic-keyboard` - `^2.0.5`
