### ISSUE TITLE
zone.js 0.8.17 XMLHttpRequest Bug

### ISSUE THREAD

**Issue by Jimmysh** [ionic-team/ionic#13014]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

 see https://github.com/angular/zone.js/issues/886

please use zone.js 0.8.18

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I have marked this as something that we will need to get into our next release.

Thank you for using Ionic

**Comment by kensodemann** [comment]
Released `3.7.1` with this fix.
