### ISSUE TITLE
whether are other ways to handle  data interactions and native development  or not

### ISSUE THREAD

**Issue by xingag** [ionic-team/ionic#13019]
Except [cordova-broadcaster](https://github.com/bsorrentino/cordova-broadcaster)，whether are other ways to handle  data interactions and native development  or not?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by xingag** [comment]
okay,thanks.
