### ISSUE TITLE
IonicModule not importing in ComponentsModule when use ionic component generator

### ISSUE THREAD

**Issue by nuruddinXbadawi** [ionic-team/ionic#13016]
I have the issue when working in Lazy component and after searching I see should I import IonicModule in ComponentsModule file but the generator not do this, and it caused lost time to solve the problem. 

ionic info 

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : ios 4.1.1
    Ionic Framework    : ionic-angular 3.6.1

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is not an issue with the Ionic Framework, but is potentially is an issue with the Ionic CLI. I will move this issue there for you. Please follow the new issue in the CLI repo.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2775
