### ISSUE TITLE
INFO: toolbar-background Class name ng-reflect-klass typo confirmation

### ISSUE THREAD

**Issue by mokupindia** [ionic-team/ionic#13023]
**Ionic version:**  
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  
[X] bug report

**Current behavior:**

```<div class="toolbar-background toolbar-background-md" ng-reflect-klass="toolbar-background" ng-reflect-ng-class="toolbar-background-md"></div>```

**Expected behavior:**

Wondering why ng-reflect-klass is spelled as KLASS and not Class?

**Ionic info:** 

```
cli packages: 

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.8 
    Node              : v6.11.3
    npm               : 3.10.10 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 

Misc:

    backend : legacy

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

You would really have to ask the Angular folks that question. The `ng` prefix indicates it comes from Angular.

Thank you for using Ionic
