### ISSUE TITLE
ion-datetime years order different than days and months

### ISSUE THREAD

**Issue by remcoderksen** [ionic-team/ionic#13027]
**Resources:**
I've looked into this but the only link I find is a closed ticket (#11225) allready placed on the Ionic issues but that was interpreted as a feature request and closed too quickly. 
(https://github.com/ionic-team/ionic/issues/11225)
I think it's really an unwanted behaviour and i see it as a bug.

No response on the forum at ionicframework website so far on this issue.
(https://forum.ionicframework.com/t/ion-datetime-years-order/107151)

**Ionic version:**  (check one with "x")
3.12.0

**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The ion-datetime picker shows a scroll on the bottom where you can select the date. I choose to pick it with day, month and year. The days and months are oredered ascending from low to high. But the years roll is ordered descending from high to low.

```
days     months    years
1        january   2020
2        february  2019
3        march     2018
etc.     etc.      2017
                   2016
                   etc.
```

**Expected behavior:**
All rolls should be ordered the same ascending or all descending. 

**Steps to reproduce:**
Create a blank ionic project an place the ion-datetime in it like the code below.

**Related code:**
```
<ion-content padding>
<ion-item>
  <ion-label>MyDate</ion-label>
  <ion-datetime displayFormat="DD MMMM YYYY" min="2010-01-01" max="2020-12-31" pickerFormat="DD MMMM YYYY"></ion-datetime>
</ion-item>
</ion-content>
```

A sample application via GitHub

http://plnkr.co/edit/fw3SYXVUBkjwUuXkKRDj?p=preview

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\Remco\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.9.4
    npm  : 3.10.10
    OS   : Windows 10

Misc:

    backend : legacy
```

![2017-09-30 21_05_31-](https://user-images.githubusercontent.com/32420024/31048706-3cb77d22-a623-11e7-942a-b10b76959a88.png)

**Comment by davec21** [comment]
I am going to have to agree with this. Using the native date time picker on my Galaxy S7 (settings -> change date/time manually) the years definitely are in ascending order not descending.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

We have this marked as needing a design decision. Various options are being discussed to allow more flexibility with this.

Thank you for using Ionic

**Comment by remcoderksen** [comment]
Thanks for your attention to this. I'll watch this thread..

**Comment by patrickmcd** [comment]
You should do a poll on how often devs use `ion-datetime` for date selection vs. time selection. I'm guessing it's 80/20.

If that's true, a calendar picker is vastly better UX compared to the dials of a picker.

**Comment by jlariza** [comment]
Hi!

I am having the same problem. I need the years on an ascending order. Any progress on this issue? Ty

**Comment by thisIsChetan** [comment]
Having the same issue. Please suggest a quick fix or a workaround.

**Comment by kenitri** [comment]
i fixed this issue today and here is solution:
i add  [yearValues] and it's prety fine 👍 
<ion-datetime [doneText]="'common.button.submit' | translate" [cancelText]="'common.button.cancel' | translate" (ionFocus)="offFocusAC()"
                            [yearValues]="selectedDate" class="inputFont" [(ngModel)]="startDate" formControlName="startDate" displayFormat="DD/MM/YYYY"
                center></ion-datetime>

**Comment by dsgriffin** [comment]
Is the only solution for this to manually order each date using `yearValues` like `yearValues="[1950, 1951, 1952, ...]"?

**Comment by dsgriffin** [comment]
Is the only solution for this using `yearValues` like `yearValues="[1950, 1951, 1952, ...]"`?

**Comment by kenitri** [comment]
@dsgriffin  yes, is years lik the min that you define  for example 1960. and doing for loop for  show it in the good way

**Comment by mahfooz14** [comment]
good question!

but still i dont get the solution
