### ISSUE TITLE
Popover is hidden by the keyboard on Android

### ISSUE THREAD

**Issue by solinder** [ionic-team/ionic#13020]
**Ionic version:** 
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request

I create and present a popover without passing $event. It is displayed in the center of the screen.
Popover contain text input. When i focuse this input keyboard is opened.
In Ios popover adapts to changed size of keyboard-free part of the screen (it goes up).
But in Android popover doesn't adapt (it stays on the same place) and the part of the popover becomes hidden by keyboard.

**Current behavior:**
In Android popover that was presented in the center of the screen doesn't adapt to changed size of keyboard-free part of the screen after keyboard was opened.

**Expected behavior:**
In Android popover go up to the center of keyboard-free zone like in Ios.

Ionic info:
```
cli packages:
    @ionic/cli-plugin-proxy : 1.4.11
    @ionic/cli-utils        : 1.12.0
    ionic (Ionic CLI)       : 3.12.0
global packages:
    cordova (Cordova CLI) : 7.0.1
local packages:
    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.1
System:
    Node : v6.11.2
    npm  : 3.10.10
    OS   : Windows 10
Misc:
    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

This will help us in debugging and testing any resolution to your issue.

Thanks for using Ionic!

**Comment by solinder** [comment]
This is a sample application with example of how i use popover: https://github.com/solinder/ionic-test-popover

Screenshot of this example:

![screenshot_2017-09-29-17-51-42_with_notice](https://user-images.githubusercontent.com/26798247/31022600-f0c9980a-a541-11e7-8bab-0cb6a5991c85.png)

**Comment by iyriarte-valmar** [comment]
Hello there!

Any update on this? I am having the same issue

Thanks in advance!

**Comment by sertal70** [comment]
Hello!
+1 to have this fixed. 

Is there any chance to have this issue fixed in 3.x? Or are you guys too busy with the 4.0 release?
