### ISSUE TITLE
Passing an object with 2049 characters crashes on iOS (2048 is okay)

### ISSUE THREAD

**Issue by zoinkydoink** [ionic-team/ionic#13024]
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have ``   navCtrl.push(EventDetailsPage, { event: event });``
When my  event object has a property that has more than 2048 characters, the app crashes on iOS (closes)

**Expected behavior:**
For the app not to crash

**Steps to reproduce:**
Create an object with a  text property of 2049 characters, I used http://www.charactercountonline.com/ to count the characters. And then try to display those characters on navcontrol page

**Related code:**

``   navCtrl.push(EventDetailsPage, { event: event });``

**ionic info**
``
  @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 browser 4.1.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 25.2.5
    Node              : v7.9.0
    npm               : 4.2.0
    OS                : Windows 10

Misc:

    backend : pro
``

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by zoinkydoink** [comment]
Seems this issue is not related to json at all, but specifically calendar.findEvent crashes if finding note field with 2049 characters or line breaks. Consider this issue closed
