### ISSUE TITLE
Building Ionic app with PhoneGap result in missing build folder and files(main.css,main.js.vendor.js and polyfills.js)

### ISSUE THREAD

**Issue by avaiskhatri** [ionic-team/ionic#13025]
My app is working on desktop using `ionic-serve` but when I pull the code on to phonegap for generating android build it is showing only white blankscreen, on searching I found a way to inspect the error through chrome using

`chrome://inspect/#devices`
Its shows the blank screen aswell with 4 files missing error in console log;
main.js
main.css
vendor.js
polyfills.js

Please someone help to get this problem solved.

Thanks

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one in the https://github.com/ionic-team/ionic-app-scripts repo with the issue template filled out, please.

Thanks for using Ionic!
