### ISSUE TITLE
ion-content hidden behind ion-header on Android in Ionic 3.7

### ISSUE THREAD

**Issue by charlierz** [ionic-team/ionic#13028]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
When you navigate to another page, open and dismiss the keyboard and go back to the previous page the ion-content will be hidden behind the ion-header. 

**Expected behavior:**
ion-content not hidden behind the ion-header

**Steps to reproduce:**
Using the ionic-conference-app with version 3.7 or 3.7.1 of Ionic add a text input in session-detail.html.
Navigate to a session-detail through the schedule page. 
**Open** and **dismiss** the keyboard with the text input added.
Go back to the schedule page.
You will now see some content is hidden behind the ion-header. If you change tabs it will restore.

**Comment by Reactor13** [comment]
We have this issue too.

**Comment by tgart** [comment]
Confirm, i have same problem. Problem generated when upgrade to 3.7+

**Comment by saschwarz** [comment]
I'm seeing this same behavior on iOS too. Forcing a content resize in the parent page (at least in my app) is a workaround:

```
export class LayoutsPage {
  @ViewChild('content') content: Content;
...
  ionViewDidEnter() {
    this.content.resize();
  }
```

I'm also seeing this problem if you change orientation in the child page (without opening a keyboard) and then return the parent page and change the orientation back while on the parent page.

**Comment by claudiozam** [comment]
Same problem in ionic 3.7.1

**Comment by wormling** [comment]
Confirmed in ionic 3.7.1 on a Samsung galaxy note 4

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I have duplicated this. Note to self: does not occur with `3.6.1`, does occur starting with `3.7.0`

Thank you for using Ionic

**Comment by mhartington** [comment]
This could be related to the iPhoneX css changed, though I would have thought the css was isolated to iOS only...

Could someone install `ionic-angular@nightly` and please test?

**Comment by charlierz** [comment]
Same problem with `ionic-angular@nightly`

**Comment by saschwarz** [comment]
Another test case is device rotation change while off the list view and returning to the list view. 

Using the Ionic Conference app deployed on a physical device:
0. Holding the phone in portrait mode
1. Select the Schedule tab
2. Select the "8:00 am Breakfast entry"
3. Rotate the phone to landscape mode
4. Select the Back button to return to the Schedule list view.
5. The scroll position will hide the "8:00 am" header and part of the Breakfast entry. Changing the orientation again will fix the layout. Scroll to refresh doesn't fix the layout either.

**Comment by menegain** [comment]
I have this same bug with these steps : 

1. In page pushed with NavController i focus a ion-input or ion-textarea
2. I close the keyboard and i click for back in my main page
3. See the bug : ion-list behind the header

This bug it's not declare when i back with my keyboard is open.

**Comment by huker** [comment]
I have same problem in ionic 3.7.1

**Comment by zakton5** [comment]
+ 1

**Comment by mariossavva** [comment]
I have same issue with 3.7.1.

Basically from what I could tell when there is a resize while a pushed page is in view, the margin-top property get's removed from ion-content css and when you pop the stack it does not force a resize in the main content.  Resizing it manually fixes it.

**Comment by AbanoubNassem** [comment]
@mariossavva, yup same issue here

**Comment by FilipMatys** [comment]
Experiencing the same issue with 3.7.1 in these two scenarios:

**Screen orientation change**
1. Push page to navigation stack
2. Change screen orientation
3. Pop page
4. All pages in the navigation stack now have content covered by header

**Hardware keyboard** 
1. Push page to navigation stack
2. Edit using platform keyboard
3. Pop page
4. All pages in the navigation stack now have content covered by header

**Comment by viktor-shmigol** [comment]
I have this same bug in ionic 3.7.1(Android/IOS)

**Comment by aduttonomni** [comment]
Same here. Android and iOS on 3.7.1

**Comment by genelim** [comment]
Experiencing the same thing.

To Reproduce:
1. Parent page with rootpage set.(ion-nav rootpage='RootPageName')
2. Rootpage is loaded
3. Nav.push('AnotherPage')
4. Click on input type number
5. Keyboard of numbers appear
6. Close keyboard
7. Setroot('ParentPage')
8. Content of rootpage of parent is pushed up behind parents navbar.

Downgrading it to 3.6 to fix the problem.

**Comment by mhartington** [comment]
Can someone please provide a sample project that has this issue? I have not been able to replicate this locally.

**Comment by kensodemann** [comment]
@mhartington - duplicated using instructions from OP:

```
Using the ionic-conference-app with version 3.7 or 3.7.1 of Ionic add a text input in session-detail.html.
Navigate to a session-detail through the schedule page.
Open and dismiss the keyboard with the text input added.
Go back to the schedule page.
You will now see some content is hidden behind the ion-header. If you change tabs it will restore.
```

This is on a Galaxy Note 4. Will update with version in a bit.

**Comment by kensodemann** [comment]
Also tried with latest nightly (`ionic-angular@3.7.1-201710181432`) and still can duplicate. Here is repo if it is helpful:

https://github.com/kensodemann/test-bed-conference

**Comment by rfoel** [comment]
This behavior happens when I pop the view using the Android back button only, works fine if I pop using the app back button. Can reproduce in >= 3.7.0.

**Comment by mhartington** [comment]
Perfect, I can replicate this. Thanks yall.

**Comment by mhartington** [comment]
Hey yall, I got a fix for this that I would like you to test out.

Please unzip this and place it in your node_modules, then deploy to your device. 

We were originally calling `content.resize()` when ever the window would resized, which was causing the issue. Now we only call it on orientation change.

[ionic-angular.zip](https://github.com/ionic-team/ionic/files/1400109/ionic-angular.zip)

**Comment by genelim** [comment]
@mhartington Hi, I have tested it. It works!

Tested with :
1. this.nav.pop()
2. this.nav.setRoot('PageName")
3. input type="text"
4. input type="number"
5. ion-searchbar
6. Rotating orientation while doing 1 to 5

All the above works. Great work! 👍  🥇 

By the way, what was the ionic-angular.zip version based on? was it 3.7.1?

**Comment by gammelby** [comment]
@mhartington I tried the patch on the scenario described in https://github.com/ionic-team/ionic/issues/13172 but the problem still persists in the Ionic super starter app: If I rotate an iOS device 90 degrees and back again and presses back, the topmost content on the previous page is still hidden by the navbar. Perhaps I prematurely closed that ticket if the problems are not as related as believed?

**Comment by Sampath-Lokuge** [comment]
Can you please this issue too? @mhartington 
https://github.com/ionic-team/ionic/issues/13194

**Comment by mhartington** [comment]
@gammelby I will look at it and try to recreate

**Comment by mhartington** [comment]
Can people try this? Same instructions as before, this should take care of the shifting content.

[ionic-angular.zip](https://github.com/ionic-team/ionic/files/1403168/ionic-angular.zip)

**Comment by kensodemann** [comment]
Works fine on my Galaxy Note 4 (Android 6.0.1) and fixes the issue.
On my iPhone 7 iOS 11.0.3 it just hangs on the splash screen (app does not hang on splash screen with 3.7.1)

I am going to try re-installing and re-verifying with your zip just to be sure.

**Comment by kensodemann** [comment]
UPDATE - must have been something wonky with my first install. After re-copy it works great on both platforms.

**Comment by gammelby** [comment]
@mhartington When I try the latest patch, I get a runtime error when rotating the iOS device: "null is not an object (evaluating this.getNav().isActive), stack: handleOrientationChange [native code]"

It happens on the super starter app whenever I rotate the device.

**Comment by ptitjes** [comment]
@mhartington I can confirm that your fixes on master (i.e. 3.7.1-201710201922) do fix the problem at least on android and browser builds. Thank you very much !

**Comment by plul** [comment]
Thanks for working on this. Please include this fix in 3.7.2 and release asap.

**Comment by genelim** [comment]
I can confirmed it worked flawlessly. Test are done the same as my previous post.

**Comment by charlierz** [comment]
Thank you very much on solving this issue.

**Comment by Simpler1** [comment]
@mhartington With your latest fixes, if the original page was using virtualScroll, after pushing, editing, and popping another page, the original list only shows a single list item in the middle of the page.  It appears that the page height is not calculating correctly after popping the other page.

**Comment by gammelby** [comment]
@mhartington With ionic-angular@3.7.1-201710201922, I still see the same issue as described in https://github.com/ionic-team/ionic/issues/13172 with the default super starter app - but the null exception in the patch attached here has been fixed.

**Comment by polfernandez** [comment]
Having the same issue. With ionic-angular 3.7.1, the entire screen moves up when ionic-native keyboard shows (from a ion-textarea input).

With (3.7.1-201610202012) got an error:
Error: Failed to transpile program
    at new BuildError (/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /node_modules/@ionic/app-scripts/dist/transpile.js:137:20
    at transpileWorker (/node_modules/@ionic/app-scripts/dist/transpile.js:103:12)
    at Object.transpile (/node_modules/@ionic/app-scripts/dist/transpile.js:61:12)
    at buildProject (/node_modules/@ionic/app-scripts/dist/build.js:97:78)
    at /node_modules/@ionic/app-scripts/dist/build.js:47:16

**Comment by kensodemann** [comment]
@polfernandez - I think you have that in the wrong issue. This issue had to do with the `ion-content` section being hidden behind the navbar when you would:

1. open a child
2. open the keyboard
3. close the keyboard
4. close the child

(see full description in OP)

This one did not have to do with the whole screen scrolling when the keyboard displays.

**Comment by huker** [comment]
Thank you on solving this issue，it works on 3.7.1-201710201922！

**Comment by edugolive** [comment]
+1, thanks, this work for me

**Comment by zaq962** [comment]
+1 I have this same bug in ionic 3.7.1 ios9.3  when i use cordova-plugin-ionic-webview 

how can i resolve it

**Comment by malwatte** [comment]
Is this fixed in Ionic 1.3.5 ?

**Comment by pnnrahul** [comment]
[https://forum.ionicframework.com/t/ion-content-is-hiding-behind-ion-header/123048](url)
#123048

**Comment by Sami-Haroon-Khan** [comment]
@saschwarz  your solution works on if I change the orientaion. Without changing orientation contetn remains behind header.
