### ISSUE TITLE
property 'filter' does not exist on type 'FirebaseListObservable<'product'>

### ISSUE THREAD

**Issue by kuveri** [ionic-team/ionic#13035]
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';

import { FirebaseListObservable, AngularFireDatabase } from 'angularfire2/database';
import { Product } from '../../models/products/product.interface';
import { ComparePage } from '../compare/compare';
import { ProductdetailPage } from '../productdetail/productdetail';
import 'rxjs/operator/filter';

@IonicPage()
@Component({
  selector: 'page-single',
  templateUrl: 'single.html',
})
export class SinglePage {
  items;
  ProductRef$: FirebaseListObservable<Product[]>

  constructor(public navCtrl: NavController, public navParams: NavParams, private database: AngularFireDatabase) {
    //this.ProductRef$ = this.database.list('product');
    this.initializeItems();
  }

  navigatetoComparePage(){
    //Navigate user to add item page
    this.navCtrl.push(ComparePage);
  }

  itemTapped(event, item){
    this.navCtrl.push(ProductdetailPage, {
      item: item
    });
  }

  initializeItems() {
    this.ProductRef$ = this.database.list('product');
  }

  getItems(ev) {
    // Reset items back to all of the items
    this.initializeItems();

    // set val to the value of the ev target
    var val = ev.target.value;

    // if the value is an empty string don't filter the items
    if (val && val.trim() != '') {
      this.ProductRef$ = this.ProductRef$.filter((ProductRef$) => {
        return (ProductRef$.toLowerCase().indexOf(val.toLowerCase()) > -1);
      })
    }
  }

}

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to close this issue because it appears to have nothing to do with the Ionic Framework based on the description.

If you have found a bug in the Ionic Framework, please another issue with the issue template completely filled out accurately describing the issue that you have found.

Thank you for using Ionic
