### ISSUE TITLE
Request: Please support breakpoints config value for Slides component

### ISSUE THREAD

**Issue by mharrisn** [ionic-team/ionic#13037]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
There appears to be no available property for the [breakpoints](http://idangero.us/swiper/api/#.breakpoints) parameter, which is available in Swiper JS

**Expected behavior:**
This should be available option, please. With the push for PWA, being able to make the Slides component work in these scenarios is vital.

**Other information:**
http://idangero.us/swiper/api/

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation.

The slides and swiper are getting a major overhaul as part of Ionic-v4, including more direct usage of the Swiper code, so this should be revisited after v4 has been released to determine if it is still an issue or if it has been fixed.

Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#313
