### ISSUE TITLE
[ios11] Pages without ion-header

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#13031]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[X ] **3.x**
[ X] **4.x**

**I'm submitting a ...**  (check one with "x")
[ X] feature request

**Current behavior:**
In pages where I don't want to use display `ion-header` I just used to not add the element in the html pages. With ionic-angular `3.7.1` it turns out that if I don't specify this element, some pixels (20px I guess) will be added in any case, like if a missing status bar/navbar had to be displayed. 
 
**Expected behavior:**
If `ion-header` is not specified in the html pages, then no spaces should be added respectively no status/navbar should be displayed.

**Steps to reproduce:**

In an html pages, don't specify `ion-header`

**Related code:**

    
    <ion-content fullscreen="true" no-bounce>
       Super
    </ion-content>

**Workaround**

As temporary workaround I did the following:

1-Add an empty ion-header

    <ion-header></ion-header>
    <ion-content fullscreen="true" no-bounce>
       Super
    </ion-content>

2-Set the header as not displayed in css

    my-component {
        ion-header {
           display: none;
        }
    }

**Other information:**

cli packages: 

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0 ios 4.5.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 5.0.13 
    Node              : v8.5.0
    npm               : 5.3.0 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy

**Screenshot**

You could find a screenshot of the problem in the forum: https://forum.ionicframework.com/t/white-space-between-header-and-content/106733/11

**Comment by mhartington** [comment]
This should be fixed in the latest nighlty

Mid scroll here:
![simulator screen shot - iphone x - 2017-10-03 at 18 17 26](https://user-images.githubusercontent.com/2835826/31151792-2daaf2be-a867-11e7-9857-1103342bd3d0.png)

![simulator screen shot - iphone x - 2017-10-03 at 18 17 29](https://user-images.githubusercontent.com/2835826/31151791-2da49cca-a867-11e7-94fa-863200628826.png)

```
npm i ionic-angular@3.7.1-201710032000
```

**Comment by peterpeterparker** [comment]
@mhartington could confirm, looks good! thx
