### ISSUE TITLE
Component ion-datetime does not bind value to the parent page

### ISSUE THREAD

**Issue by sebfie** [ionic-team/ionic#13038]
**Ionic version:**
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a **
[x] bug report
[ ] feature request

**Current behavior:**

I have an issue using an `ion-datetime` into a custom component called `picker-input` on my ionic 2 project. 
If I use `ion-datetime`  component inside an other component it does not "bind" value changed to parent page. If I put directly the `<ion-datetime></ion-datetime>` in my page template, both components (ion-datetime and picker-input) will work....

**Expected behavior:**

The value of my ngModel should be bind to parent view

**Steps to reproduce:**
I created a Plunker to show my issue.

**Related code:**

I created a Plunker to show my issue : 

http://plnkr.co/edit/qy6Wrw2cakL69nqP9XIU?p=preview

Same plunker but with two ion-datetime (one in my custom component and the other one directly in the home page)

http://plnkr.co/edit/vLm2jrfXYWywV1YsPLQQ?p=preview

**Ionic info:** :

```
cli packages: (/Users/sebfie/.nvm/versions/node/v7.2.1/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : ios 4.5.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    ios-sim : 6.1.2
    Node    : v7.2.1
    npm     : 5.3.0
    OS      : macOS High Sierra
    Xcode   : Xcode 9.0 Build version 9A235

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Your outer page has this: `<picker-input [(field)]="my_model"></picker-input>`

But Angular doesn't _really_ have two-way data binding. They have property bindings and event bindings. The combination of those two effectively provides two-way bindings. The "banana-in-a-box" syntax of `[(field)]` is just syntactic sugar for this: `<picker-input [field]="my_model" (fieldChange)="my_model=$event"></picker-input>`. For more info, see here: https://angular.io/guide/template-syntax#two-way-binding---

So, your PickerInput should have an `@Input() field`, which it does. It should also have an `@Output() fieldChange` which should be an event emitter. It should also have code that emits data when the field changes. In your case, this is probably most effectively done using getters and setters as shown in [this example](https://blog.thoughtram.io/angular/2016/10/13/two-way-data-binding-in-angular-2.html#creating-custom-two-way-data-bindings).

I am going to close this as it is not an issue with the Ionic Framework.

Thank you for using Ionic
