### ISSUE TITLE
Ionic 3.7.1 Compiler Detection Issues 

### ISSUE THREAD

**Issue by bkarv** [ionic-team/ionic#13033]
Hi All,

After upgrading my App to Ionic 3.7.1 including the new Ionic compiler app scripts, I am having issues with the change detection with the Ionic Compiler. Long story short is sometimes when I make changes in my app in both the html and/or ts file, save and it auto compiles the changes are not detected in the recompiled app in my web browser via ionic serve (ie progressive web browser).

I've managed to get around this by doing killing ion serve and then executing ionic serve. But today even doing this the changes were ignored. I had to restart the computer and only then the changes were detected.

Is anyone else getting this same issue? I've posted my package.json below, is there anything wrong with it?

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

`{
  "name": "myapp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.4.3",
    "@angular/compiler": "4.4.3",
    "@angular/compiler-cli": "4.4.3",
    "@angular/core": "4.4.3",
    "@angular/forms": "4.4.3",
    "@angular/http": "4.4.3",
    "@angular/platform-browser": "4.4.3",
    "@angular/platform-browser-dynamic": "4.4.3",
    "@ionic-native/core": "3.12.1",
    "@ionic-native/splash-screen": "3.12.1",
    "@ionic-native/status-bar": "3.12.1",
    "@ionic/storage": "2.0.1",
    "@types/lodash": "^4.14.68",
    "angular2-jwt": "^0.2.3",
    "angular2-uuid": "^1.1.1",
    "cordova-android": "~6.1.2",
    "cordova-ios": "~4.3.1",
    "cordova-plugin-console": "1.0.5",
    "cordova-plugin-device": "1.1.4",
    "cordova-plugin-splashscreen": "~4.0.1",
    "cordova-plugin-statusbar": "2.2.1",
    "cordova-plugin-whitelist": "1.3.1",
    "cordova-sqlite-storage": "~2.0.3",
    "ionic-angular": "^3.7.1",
    "ionic-plugin-keyboard": "~2.2.1",
    "ionicons": "3.0.0",
    "lodash": "^4.17.4",
    "ng-elastic": "^1.0.0-beta.3",
    "rxjs": "5.4.3",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.0.0",
    "typescript": "2.3.4"
  },
  "description": "An Ionic project",
  "cordova": {
    "platforms": [
      "android",
      "ios"
    ],
    "plugins": {
      "cordova-plugin-console": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "cordova-sqlite-storage": {},
      "ionic-plugin-keyboard": {}
    }
  }
}
`

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

On a side note, this sounds a lot to me like a browser caching issue. Which browser are you using for development? Are you sure you have it set up to not aggressively cache things?

Thanks for using Ionic!

**Comment by bkarv** [comment]
I am not sure it is a browser caching issue as I tested it on Safari and Chromium and both did not detect the changes. 

It is bizarre as it seems only to be the case when upgrading my ionic scripts. Anyway I will give it more time to see if anyone else has had the same issue.

**Comment by kensodemann** [comment]
Have you verified whether or not the application is actually being recompiled? Your original post made it sound like it was, but it is not entirely clear that it has been
