### ISSUE TITLE
ionic-anglar 3.6.1 white screen when ionic serve 

### ISSUE THREAD

**Issue by codot91** [ionic-team/ionic#13034]
after ionic start myApp tabs done, I try ionic serve.
But why only show white screen / blank page ?

my eror in console chrome
![qwe](https://user-images.githubusercontent.com/10111459/31066901-2f34e27c-a77a-11e7-89a8-ba8277adac2f.jpg)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
cli packages: (C:\Users\nafir\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

local packages:

    @ionic/app-scripts : 2.1.4
    Ionic Framework    : ionic-angular 3.6.1

System:

    Node : v6.11.3
    npm  : 5.4.2
    OS   : Windows 10

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I tried `ionic start myApp tabs` and everything worked fine when I did `ionic serve`. I assume based what you said in your issue, this is also all that you are doing. Is that correct?

When you do the `ionic serve` are there any error messages in the terminal window?

I ran my test on a Ubuntu Linux machine. I see your OS is Windows 10. Perhaps that is the key difference. @jgw96 - can you try this on your Windows 10 machine and see if you get an issue?

Thank you for using Ionic

**Comment by codot91** [comment]
yes i'm using windows 10.
i think no eror in terminal...
![qwe123](https://user-images.githubusercontent.com/10111459/31074002-b6b9c820-a798-11e7-8ff1-d9a0e1523e23.jpg)

**Comment by kensodemann** [comment]
That looks normal. Part of this that confuses me is your `ionic info` which states this:

```
local packages:

    @ionic/app-scripts : 2.1.4
    Ionic Framework    : ionic-angular 3.6.1
```

However, when I generate the app, I have the latest versions:

```
local packages:

    @ionic/app-scripts : 3.0.0
    Ionic Framework    : ionic-angular 3.7.1
```

I have asked someone here who has a Windows 10 machine to give this a look.

**Comment by kensodemann** [comment]
We tried the generation on a Windows 10 machine here and everything worked well.

Question: this problem you are reporting, is it on a fresh app? or was it generated prior? Have you made any modifications to the code? when was it generated?

I ask because a.) we cannot duplicate, and b.) we released `ionic-angular@3.7.0` with `@ionic/app-scripts@3.0.0` earlier last week and `ionic-angular@3.7.1` on Friday, so if this was freshly generated, I would expect to see some combinations of those versions in your `ionic info`

**Comment by codot91** [comment]
fresh app,
but before eror I always use ionic version 1 in my application.

right now i want to make app with ionic 3 and do like this
npm install -g cordova ionic
ionic start myApp tabs
cd myApp
ionic serve

but after ionic serve always white screen

**Comment by kensodemann** [comment]
Hmmmm.... Can you post the contents of the `package.json` file?

**Comment by codot91** [comment]
`{
  "name": "myApp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.4.3",
    "@angular/compiler": "4.4.3",
    "@angular/compiler-cli": "4.4.3",
    "@angular/core": "4.4.3",
    "@angular/forms": "4.4.3",
    "@angular/http": "4.4.3",
    "@angular/platform-browser": "4.4.3",
    "@angular/platform-browser-dynamic": "4.4.3",
    "@ionic-native/core": "3.12.1",
    "@ionic-native/splash-screen": "3.12.1",
    "@ionic-native/status-bar": "3.12.1",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.7.1",
    "ionicons": "3.0.0",
    "rxjs": "5.4.3",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.0.0",
    "typescript": "2.3.4"
  },
  "description": "An Ionic project"
}
`

**Comment by kensodemann** [comment]
I updated your comment to put in the three back-ticks for a blockquote. Didn't change anything else...

**Comment by kensodemann** [comment]
OK, I see some issues here:

1. your `package.json` looks good
2. your `ionic info` data from above does not actually match your `package.json` version

Specifically, `package.json` has:

- "ionic-angular": "3.7.1",
- "@ionic/app-scripts": "3.0.0",

But your `ionic info` output says:

```
local packages:

    @ionic/app-scripts : 2.1.4
    Ionic Framework    : ionic-angular 3.6.1
```

So I suggest the following:

1. remove the `node_modules` folder
2. remove the `package-lock.json` file
3. npm cache clear -f
4. npm install
5. ionic info

Hopefully after all of that, `ionic info` will show something more like this:

```
local packages:

    @ionic/app-scripts : 3.0.0
    Ionic Framework    : ionic-angular 3.7.1
```

And also hopefully your app will work...

**Comment by kensodemann** [comment]
I am closing this due to lack of inactivity. If this is still an issue for you and you have tried what I suggested above please let me know.
