### ISSUE TITLE
iOS 11/3.7.1 content has extra left padding in landscape

### ISSUE THREAD

**Issue by oddcb** [ionic-team/ionic#13040]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x** (3.7.1)
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
With Ionic 3.6.0 the content had no extra padding. After upgrading to 3.7.1 it seems safe-area-padding is added? I've added the meta view port setup as per the ios11 blog post.

**Expected behavior:**
Same as with 3.6.0. No extra padding in on to the left in landscape.

**Steps to reproduce:**

Open an app in either emulator, on the device or Safari/Chrome (with UA set to iPad/iPhone) and inspect a scroll-content div, it should have the following: 

```
@media screen and (orientation: landscape) {
  ion-app.ios .scroll-content {
    padding-left: calc(constant(safe-area-inset-left) + 16px);
  }
}
```

![extrapadding](https://user-images.githubusercontent.com/374889/31123734-7225081a-a841-11e7-9f29-d0c38ab2804b.png)

I also did a fresh checkout (ee2aa5435a9e8ab38b75a6356389e8b3dd483b3f) of the conference app, added the ios platform and ran in a simulator for iOS 11 iPad Pro. Same issue: 

![skjermbilde 2017-10-03 kl 13 58 06](https://user-images.githubusercontent.com/374889/31124083-2914c17c-a843-11e7-928c-25044ccbe2e7.png)

Both my app and the conference app are using the ionic wkwebview. Both apps does not exhibit the problem on e.g. iOS 9.3.5.

**Other information:**
I've just added this to my app.scss as a workaround: 

```
@media screen and(orientation: landscape) {
  ion-app.ios .scroll-content {
    padding-left: 0;
  }
}
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/oddcb/prosjekter/sf/styreplan-app/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.3.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    Node       : v8.6.0
    npm        : 5.3.0 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy
```

**Comment by mhartington** [comment]
@oddcb Hi, I just pushed a new nightly for this, can you install and test it out?

```
npm i ionic-angular@3.7.1-201710032000
```

**Comment by oddcb** [comment]
@mhartington looks good :-) Tested in simulator and safari. Will it be included in a release soon?

**Comment by mhartington** [comment]
This will probably be in the next release, or a patch release, we haven't finished our work yet, so hard to tell. We'll post about it through our blog/twitter when it's out though!

**Comment by mino922** [comment]
Is this fix available? I am seeing this on my Ipad (5th gen).

`cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.9.4
    npm        : 5.6.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro`
