### ISSUE TITLE
circleci build fail - not going to update docs

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic#13042]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

![capture1121](https://user-images.githubusercontent.com/140737/31139277-d5dc1252-a825-11e7-956d-fcd6fd4dda07.PNG)

![capture1120](https://user-images.githubusercontent.com/140737/31139281-da00ea42-a825-11e7-910b-aa3925f4b742.PNG)

**Comment by mhartington** [comment]
Thanks for the head up! We'll rebuild and get it fixed.
