### ISSUE TITLE
Lazy loading & resolveComponentFactory & navCtrl.push problem

### ISSUE THREAD

**Issue by petrot** [ionic-team/ionic#13041]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**

I have a leaflet map in my app. I use componentFactory to create custom page content (=unique component) to the leaflet popup.

Now I tried to refactor my code to use lazy loaded pages. Everything works fine, but I can't use the componentFactory with the component's name:

```
old, working code:
const compFactory = this._resolver.resolveComponentFactory(MapInfoWindow);

lazy loading:
const compFactory = this._resolver.resolveComponentFactory('MapInfoWindow');
```

For temporarly solution, now I import this page as normal page, and the other ones are used as lazy loaded pages. But I have a problem... 

I have a link in the popup window, which navigates to the next **tabbed** page. When I click to the link, on the first click (and only the first), the nav.push open's the required page, but redirects to the root immediately. When I open the popup again, it works as I expected.

**Expected behavior:**
Maybe the solution would be the lazy loading of the popup window?

**Steps to reproduce:**

[Sample video](https://www.youtube.com/watch?v=UIjpV9dXAII&feature=youtu.be)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
@ionic/cli-utils  : 1.12.0
ionic (Ionic CLI) : 3.12.0
cordova (Cordova CLI) : 7.0.1
@ionic/app-scripts : 3.0.0
Cordova Platforms  : android 6.3.0 browser 4.1.0 ios 4.4.0
Ionic Framework    : ionic-angular 3.7.1
ios-deploy : 1.9.2
Node       : v6.11.3
npm        : 3.10.10
OS         : macOS High Sierra
Xcode      : Xcode 9.0 Build version 9A235
backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

general questions:

> For temporarly solution, now I import this page as normal page, and the other ones are used as lazy loaded pages

You call this a "temporary" solution. Is there some other solution you are looking at?


Also, you have this marked as a `feature request`, but it reads more like a bug. What is the feature you are requesting?

Thanks for using Ionic!

**Comment by kensodemann** [comment]
Excellent!! I am going to close this then.

**Comment by davidoween** [comment]
@kensodemann thank you, helped me
