### ISSUE TITLE
ion-split-pane content area has incorrect class

### ISSUE THREAD

**Issue by ccmpj** [ionic-team/ionic#13045]
**Ionic version:** 
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  
[X] bug report
[ ] feature request

**Current behavior:**
When using a split pane, both the side pane and the main pane both have the class `split-pane-side`, therefore they are both the same width, rather than the main area covering the rest of the browser window.

**Expected behavior:**
The side area should have `split-pane-side` and the main area should have the class `split-pane-main` and should extend to fill the rest of the screen.

**Steps to reproduce:**
Create a new blank side menu project

`ionic start my-test-project sidemenu`

Then edit the `app.html` template to wrap the contents with `<ion-split-pane></ion-split-pane>`

serve the project
`ionic serve`

**Related code:**

**Other information:**

**Ionic info:** 

```
$ ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

local packages:

    @ionic/app-scripts : 3.0.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v7.10.0
    npm  : 4.2.0 
    OS   : macOS Sierra
```

**Comment by ccmpj** [comment]
I can currently get around this with CSS:

```
.split-pane {
  &.split-pane-md, &.split-pane-ios {
    ion-nav.split-pane-side {
      display: block;
      min-width: inherit;
      max-width: inherit;
      border: none;
    }
  }
}
```

I've added in `display: block` as I need to hide the side pane when my login screen is displayed. However, `.split-pane-side` is hidden, forcing my content area also to be hidden.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Double check that you have something set to be `main`

From the docs here: http://ionicframework.com/docs/api/components/split-pane/SplitPane/

> Here, SplitPane will look for the element with the main attribute and make that the central component on larger screens. The main component can be any Ionic component (ion-nav or ion-tabs) except ion-menu.

Thank you for using Ionic

**Comment by ccmpj** [comment]
ah, feel a bit daft now. That was it.
