### ISSUE TITLE
Activated state is kept on activable element

### ISSUE THREAD

**Issue by jrmlt** [ionic-team/ionic#13044]
**Ionic version:**
[X] **3.x**

**I'm submitting a ...**
[X ] bug report

**Current behavior:**
The .activated class is kept on a activable element when the finger or mouse is released on an non-activable element 

**Expected behavior:**
When releasing the finger or the mouse, whatever the position, the current activated state should be cleared

**Steps to reproduce:**
- Click or touch a button at its border
- Slide the mouse or finger outside the button
- The activated state is kept

**Related code:**
```
pointerEnd(ev: any, pointerEventType: number) {
    if (!this.dispatchClick) return;

    runInDev(() => this.lastTouchEnd = Date.now());

    if (!this.startCoord) {
      return;
    }
    if (this.activator && ev.target !== this.plt.doc()) {
      let activatableEle = getActivatableTarget(ev.target);
      if (activatableEle) { <============================= HERE
        this.activator.upAction(ev, activatableEle, this.startCoord);
      }
    }
    if (this.usePolyfill && pointerEventType === POINTER_EVENT_TYPE_TOUCH && this.app.isEnabled()) {
      this.handleTapPolyfill(ev);
    }
    this.startCoord = null;
  }
```

**Ionic info:**

```
cli packages: 

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.11.0
    npm  : 5.2.0
    OS   : Windows 10

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

We will look into this.

Thank you for using Ionic
