### ISSUE TITLE
IonicNative File does not work on real device with iOS 11.0.2

### ISSUE THREAD

**Issue by Math3v** [ionic-team/ionic#13055]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
When using File plugin from IonicNative. The "plugin_not_installed" error occurs on real device, even though it works as expected on iOS Simulator.

**Expected behavior:**
"plugin_not_installed" does not occur

**Steps to reproduce:**
1. Generate blank Ionic project
2. ionic cordova plugin add cordova-plugin-file
3. npm install --save @ionic-native/file
4. Add this plugin to your app's module
5. Copy contents of home.ts and home.html from the example repository

**Related code:**
[Sample IonicNative File application](https://github.com/Math3v/ionic-file)

**Other information:**
Real testing device: iPhone SE with iOS 11.0.2

**Ionic info:**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.5.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node  : v6.11.3
    npm   : 3.10.10 
    OS    : macOS High Sierra
    Xcode : Xcode 9.0 Build version 9A235 

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is not an issue with the Ionic Framework. It appears to be an issue with Ionic Native. I will move this to https://github.com/ionic-team/ionic-native. Please follow the issue over there.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-native#2021
