### ISSUE TITLE
option to prevent defaulting to first tab

### ISSUE THREAD

**Issue by patrickmcd** [ionic-team/ionic#13056]
**Ionic version:**  (check one with "x")
[x] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] feature request

**Current behavior:**
According to the docs "by default, the first tab will be selected upon navigation to the Tabs page". I would like an option to prevent this so I can decide which tab to load in an async operation.

While I can use `select()` to load the correct tab after async, that's after the first potentially incorrect tab has already loaded and you see a healthy flash between the two pages.

**Expected behavior:**
n/a

**Steps to reproduce:**
n/a

**Related code:**
n/a

**Other information:**
n/a

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
n/a

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#314
