### ISSUE TITLE
Setting statusBar.overlaysWebView(false) breaks the ion-footer on all iPhone models on 3.7

### ISSUE THREAD

**Issue by hugodes** [ionic-team/ionic#13054]
**Resources:**

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

The button in the footer is misplaced on iPhone < X and hidden on iPhone X

![iphone 6 bad](https://user-images.githubusercontent.com/1223591/31228538-2e3117d6-a9de-11e7-8862-30bdc383de3b.png)
![iphone x bad](https://user-images.githubusercontent.com/1223591/31228537-2e25d8bc-a9de-11e7-9c74-3fb2c012e9f2.png)

**Expected behavior:**

The button should have a normal padding on iPhone < X and be visible on iPhone X

![iphone 6 good](https://user-images.githubusercontent.com/1223591/31228544-32cf447a-a9de-11e7-81ed-6877d31db738.png)
![iphone x good](https://user-images.githubusercontent.com/1223591/31228543-32cdb6c8-a9de-11e7-88eb-4eba9a841b3b.png)

**Steps to reproduce:**

Run this app https://github.com/hugodes/ionic-statusBar-breaking in an iPhone(X and inferior) emulator and look at the button in the footer

**Related code:**

In this sample project created with ionic start, the only line I added is this one in the constructor of the main component.

```
      statusBar.overlaysWebView(false);
```

**Other information:**

In line with http://blog.ionic.io/ios-11-checklist/ , I used 

ionic cordova plugin rm cordova-plugin-statusbar
ionic cordova plugin add https://github.com/apache/cordova-plugin-statusbar.git

hoping that it would resolve my issue but it didn't.

~~This issue is also only apparent when using WKWebView~~

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
$ ionic info

cli packages: (/Users/hugodes/.nvm/versions/node/v8.6.0/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.5.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2 
    Node       : v8.6.0
    npm        : 5.3.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Duplicated on iPhone X, iPhone 8, & iPhone 6 iOS 11
Issue not present on iPhone 6 iOS 10.3.1
Issue also not present if downgrading to `ionic-angular@3.6.1`

Attempted `npm i ionic-angular@3.7.1-201710032000` which is nightly with upcoming iOS 11 fixes in it, but that also had the issue.

We will look into this.

Thank you for using Ionic

**Comment by mhartington** [comment]
Hmm, I'm not able to replicate this at the moment

![simulator screen shot - iphone x - 2017-10-06 at 11 23 16](https://user-images.githubusercontent.com/2835826/31285613-ca85572c-aa89-11e7-9cfa-365c5b6f7bab.png)
![simulator screen shot - iphone x - 2017-10-06 at 11 22 49](https://user-images.githubusercontent.com/2835826/31285614-ca8cb472-aa89-11e7-810c-69e12908072c.png)
 

The first one has the statusbar set to not overlay, and the second is set to true.


This is the conference app with 
1. Latest WKWebview installed 
2. Nightly statusbar plugin installed.

**Comment by mhartington** [comment]
Can you install 

```
npm i ionic-angular@3.7.1-201710091909
```



This should be fixed.

**Comment by kensodemann** [comment]
@mhartington - I tried the nightly against @hugodes's repo and it worked for me.

**Comment by hugodes** [comment]
@kensodemann how to I go about installing the nightly status bar plugin ?

**Comment by kensodemann** [comment]
@hugodes - info from here: http://blog.ionic.io/ios-11-checklist/ (there might be other handy info in there as well, so I included the link).

```
ionic cordova plugin rm cordova-plugin-statusbar
ionic cordova plugin add https://github.com/apache/cordova-plugin-statusbar.git
```

Note that this is only required until they do a release.

**Comment by hugodes** [comment]
@kensodemann thanks a bunch, you and the ionic team have been awesome at adressing this issue 👍

**Comment by kensodemann** [comment]
@hugodes - I have not had time to review this issue yet. Hope to get to it sometime this week.

**Comment by mhartington** [comment]
Hmm, ok I see why this is happening.

Toolbar is getting min-height, and also setting an explicit height.  Removing the explicit height fixes this.

Overlay
![simulator screen shot - iphone x - 2017-10-17 at 09 41 07](https://user-images.githubusercontent.com/2835826/31668411-22f76ab4-b320-11e7-8675-2cbde10c86fe.png)


No overlay

![simulator screen shot - iphone x - 2017-10-17 at 09 41 15](https://user-images.githubusercontent.com/2835826/31668410-22e5fa5e-b320-11e7-929c-c40402a27b44.png)

**Comment by gigocabrera** [comment]
https://github.com/ionic-team/ionic/issues/13144

**Comment by gigocabrera** [comment]
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/24

**Comment by hugodes** [comment]
@mhartington could you please give the reference to the nightly build including this commit so I can build against it ?

Cheers

**Comment by mhartington** [comment]
@hugodes Should just be able to run 

```
npm i @ionic/app-scripts@nightly ionic-angular@3.7.1-201710181432
```

**Comment by hugodes** [comment]
works like a charm !
