### ISSUE TITLE
ion-grid border collapse

### ISSUE THREAD

**Issue by MartinMuzatko** [ionic-team/ionic#13052]
**Ionic version:**  (check one with "x")
3.12.0

**I'm submitting a ...**  (check one with "x")
[x] documentation improvement/feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently, there is no way to apply a border collapsing behavior, since we are dealing with a flex grid, not a table. So to workaround the problem, is that we have to add `border-bottom` and `border-right` to all `ion-col`s and add exceptions for the first row.

This is not an acceptable solution. We need to add/remove rows in the middle of the grid to allow expanding/collapsing tabular content. We would need to have to add a first-row class to any new row.

**
Expected behavior:**
There is no documentation on how to deal with this.

**Related code:**

A sample application via GitHub
https://ionic-w8wuqk.stackblitz.io

What are our options? There is nothing like `border-collapse` on ion-grid.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C/dev/frontend/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

local packages:

    @ionic/app-scripts : 1.3.7
    Ionic Framework    : ionic-angular 3.3.0

System:

    Node : v8.6.0
    npm  : 5.3.0 
    OS   : Linux 4.4

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Do you have a sample of what you are trying to do with the grid?

I want to make sure I understand your use case. I have always viewed both the Ionic Grid and the Bootstrap Grid more as layout mechanisms than as data presentation mechanisms. Based on the StackBlitz you sent, it seems like you want to display data in a tabular format, for which I would use either a styled HTML table (if my needs were simple enough) or a third party "data grid" (of which there are several) which are usually just tables with extras, but only if my needs justified the added expense and complexity.

IOW, what I have always used:

- for layout: Bootstrap / Ionic Grid / Flex Layout
- for data: HTML Table / 3rd Party "Data Grid" (not layout grid)

Thank you for using Ionic

**Comment by MartinMuzatko** [comment]
Yes you are right. I think I should use a table for tabular data. The ion-grid should be used for laying out the components on a page, and not for displaying data.
Thanks. This is the wrong approach I have chosen.
