### ISSUE TITLE
HTML 5 Video Tag Controls Not Working in Full Screen

### ISSUE THREAD

**Issue by ebinsleeba** [ionic-team/ionic#13059]
Hi,
Am Trying to load video in my ionic app using html 5 video tag . It works fine in normal screen but when i switch to full screen video controls are displayed but am not able to click . But in IOS It work fine .

 video poster="{{fileUploadUrl}}{{postDetails.Thumbnail}}" preload="metadata" controls controlsList="nodownload">
                source src="{{fileUploadUrl}}{{postDetails.MediaUrl}}" type="video/mp4" />
            </video

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please.

Also please provide a sample application via GitHub that demonstrates the issue. This aids greatly with being able to replicate your issue and with debugging and fixing.

Thanks for using Ionic!
