### ISSUE TITLE
Blocker: Form field is in view only when I start typing on keyboard and not on focus; keyboard takes over the form when tap on field, Ionic 3.7.1

### ISSUE THREAD

**Issue by ghost** [ionic-team/ionic#13051]
**Ionic version:** 
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**

Form field is in view only when I start typing on keyboard and not on focus; keyboard takes over the form when tap on any field;

**Expected behavior:**

The focused field should be in view and scrolled automatically and forced to manually scrolled

**Steps to reproduce:**

![keyboard_issue](https://user-images.githubusercontent.com/30292233/31214028-fffa097a-a9c6-11e7-9266-8f8844cd7fe1.gif)

**Ionic info:** :

```
cli packages: 

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.8 
    Node              : v6.11.3
    npm               : 3.10.10 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 

Misc:

    backend : legacy
```

**Comment by mokupindia** [comment]
I have used below but no help:

```
IonicModule.forRoot(MyApp, {
            scrollPadding: false,
            scrollAssist: true,
            autoFocusAssist: false

    })
```

**Comment by aaronneon2** [comment]
Happens to me too. Somehow the scrollassist code in ionic-angular for ion-input component is not working properly. I fixed it by fixing the source code in ionic-angular/component/input/input.js in my working copy. I will be submitting a pull request soon and see if it can fix this issue for everyone else. No guarantee though.
