### ISSUE TITLE
ion-input type="text" stops working completely if you hold down a key

### ISSUE THREAD

**Issue by stellmaurer** [ionic-team/ionic#13050]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Hold down a key on your keyboard in the input area for ion-input and then it, and any other ion-inputs with type="text" on the same page become unresponsive

**Expected behavior:**

ion-input type="text" types the key held down until you let it up and keeps working as normal when you lift it up.

**Steps to reproduce:**

The bug occurs on your website (https://ionicframework.com/docs/components/#inputs) and while using ionic serve in my app. I haven't tested devices yet, but since the bug happens on your website I figured there wasn't a point.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Holding a key on a device does not repeat the key, even natively. Example on iOS:

1. open Notes app (iOS native, Apple supplied app)
2. go to edit a new note
3. press and hold the 'o' key, note that and menu of other types of 'o's comes up
4. press and hold some other key, note that maybe you get a menu, or maybe nothing happens until you let go of the key

Ionic is providing that same native experience.

Similar experience on Android native app.

I did not experience this, however:

> and any other ion-inputs with type="text" on the same page become unresponsive

once I let go of the key I was able to use the other inputs just fine.

Thank you for using Ionic

**Comment by stellmaurer** [comment]
You're welcome!

Okay good, that makes sense that it will work on a device then :)

I'm confused how you aren't experiencing the ion-inputs with type="text" becoming unresponsive on your website after a key is held down, especially since I tested it on Chrome, Firefox, and Safari and got the same result. I have to open a new tab for it to start working again (refreshing doesn't solve the issue).

I'm on a Mac if you think that'd make a difference.

Thanks for the help.

**Comment by kensodemann** [comment]
My tests were done in Safari (11) and in Chrome (61) on a Mac using both our website and a sample app. Never got a freeze up like you describe. Just tried again adding Firefox to the mix. Same results.

I am going to close this as the main part of this is how it is supposed to work on a device and the second part of this is something that cannot be duplicated.
