### ISSUE TITLE
VirtualScroll - List does not re-render when item position changes

### ISSUE THREAD

**Issue by aasimmomin** [ionic-team/ionic#13066]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have  a sorted array being displayed using virtual-scroll. When the position of an item within the sorted array changes the virtual-scroll does not render the data.
Adding a new row and removing a row updates the list though.

**Expected behavior:**

The ion-list should update the position of the item to display its new position.

**Steps to reproduce:**

A sample application has been built in stackblitz below
https://stackblitz.com/edit/ionic-mecik4?embed=1&file=pages/home/home.ts

1. App initialises list with 20 items, sorted descending by date timestamps
2. Clicking on "Add row" - adds a new item at top of list
3. Clicking "Remove row" - removes a row from top of list
4. Clicking on "Change item..."  - updates the timestamp of the last element in row and brings it to top (as can be seen in console log output)
However, the view does not update.

**Related code:**

```
<ion-list
    [virtualScroll]="items"
    [virtualTrackBy]="trackById"
    approxItemHeight="15px"
  >
    <ion-item *virtualItem="let item">
      <item-renderer        
        [item]="item"
      >
      </item-renderer>
    </ion-item>
  </ion-list>  

constructor(public navCtrl: NavController) {
    for(let i=0;i<20;i++){      
      let dt:Date=new Date();
      dt.setTime(new Date().getTime()+i);
      this.items.push(new ItemObject("id"+i,dt));      
    }
    this.sortItemsDescending();
  }

  sortItemsDescending(){
    this.items.sort((item1,item2)=>{return item2.date.getTime()-item1.date.getTime()});
    console.log(this.items)
  }

```

**Comment by kensodemann** [comment]
In the HTML, you have this:

```html
  <ion-list [virtualScroll]="items" [virtualTrackBy]="trackById" approxItemHeight="15px">
    <ion-item *virtualItem="let item">
      <item-renderer [item]="item">
      </item-renderer>
    </ion-item>
  </ion-list>
```

But the `trackById` method is not defined, and not really what you want anyhow as if it were defined it would track by ID and your IDs are not changing. So you get the default change detection, so to speak.

What you want is something like this:

**home.html**

```HTML
  <ion-list [virtualScroll]="items" [virtualTrackBy]="trackByDate" approxItemHeight="15px">
    <ion-item *virtualItem="let item">
      <item-renderer [item]="item">
      </item-renderer>
    </ion-item>
  </ion-list>
```

Note the change here: `[virtualTrackBy]="trackByDate"

**home.ts**

```ts
  trackByDate(index: number, item: ItemObject): number{
    return item.date.getTime();
  }
```

**Comment by aasimmomin** [comment]
Thanks @kensodemann for your reply.
I did try the trackByDate method as you suggested and that did show me the update on the list.
However
1. On updating even one row, I noticed that all my item renderers were being recreated, although the property defined by the trackBy method hadn't updated for them.
2. I tried the same example using a simple ion-list and ngFor which updated the position of the item correctly as well as didn't recreate all the item renderers.

Referring to the angular ngFor documentation (https://angular.io/api/common/NgForOf#change-propagation), I expected the third bullet point to hold true in case of virtual scroll.

Does the virtual scroll's virtualTrackBy work differently?

**Comment by kensodemann** [comment]
> Does the virtual scroll's virtualTrackBy work differently?

Not `virtualTrackBy` itself. All it does is logically say "here, look at this value to see if the item changed"

In the virtual-scroll code, however, this triggers a condition where a rebuild of the data is required.
