### ISSUE TITLE
Font size on the <h> tag in ion-col

### ISSUE THREAD

**Issue by shahramSo** [ionic-team/ionic#13064]
Hi,
I need all of font sizes of h1 up to h6 tag for my project but these tags don't work correctly when I use them in ion-grid, I have tested as follows:

>  <ion-row>
            <ion-col>
              <h1>Test1</h1>
              <h2>Test2</h2>
              <h3>Test3</h3>
              <h4>Test4</h4>
              <h5>Test5</h5>
              <h6>Test6</h6>
            </ion-col>
</ion-row>

as you see all font sizes from h4 to h6 are not changed in Ion-grid so these tags show font size like h3 for more info, I've tested on Ionic 3.7 project under Android device and emulator.

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please.

Also, provide a sample application that demonstrates the issue you are having. I tried copy-pasting your code into a new `ionic start myApp blank` app and way different text sizes all the way down in browsers, on an Adroid device, and on an iOS device.

Thanks for using Ionic!

**Comment by shahramSo** [comment]
In my requirement, I used these h tags tests between a ion-item, so I retested it in new ionic blank project and get the same issue as result. Please test the code as follows:

> 

`   <ion-list>
    <ion-item>
      <ion-grid>
        <ion-row>
          <ion-col>
            <h1>Test1</h1>
            <h2>Test2</h2>
            <h3>Test3</h3>
            <h4>Test4</h4>
            <h5>Test5</h5>
            <h6>Test6</h6>
          </ion-col>
        </ion-row>
      </ion-grid>
    </ion-item>
  </ion-list>`
     Thanks

**Comment by kensodemann** [comment]
That is because they are in a list item. `h3` through `h6` are intentionally set that way:

```scss
.item-md h3,
.item-md h4,
.item-md h5,
.item-md h6 {
  @include margin(2px, 0);

  font-size: 1.4rem;
  font-weight: normal;
  line-height: normal;
}
```

My guess is that this is tied to suggested font sizes within lists based on the Material Design specs. cc @brandyscarney - can you confirm this?

You are, or course, free to override this for your own particular requirements.

**Comment by shahramSo** [comment]
Thanks you for your explanation. I think it would be better that I write a style for my requirements.
