### ISSUE TITLE
Swipe to go back is not working on Ionic 3.12.0 using  nav.push(Page)

### ISSUE THREAD

**Issue by gurwinder-macrew** [ionic-team/ionic#13069]
**Ionic version: 3.12.0**

**I'm submitting a ...** Bug

**Current behavior:**
I can not get swipe to go back to previous page using the start tabs project in Ionic. Here is what I have:
`<ion-nav [root]="rootPage" #content swipeBackEnabled="true">`
and also added 
`IonicModule.forRoot(MyApp, { swipeBackEnabled: true })`
in app.module.ts

Swipe back is working fine when I am using navCtrl.push(Page),
but when I am use nav.push(Page) it doesn't works.
It should work in both cases.

**Working case:**
navCtrl.push(Page)

**Not Working case:**
nav.push(Page)

I am testing it on Android Device (Android 6.0.1)

**To reproduce same here is sample Application**
https://github.com/gurwinder-macrew/sampleProject

After openning application, Click on **INFO** button to open page and try swipe to go back, It will not work. 
And also it is not working in Tabs root page.
For test this, You need to click on center button "info icon" on Tabs, and this will open a Action Sheet, then you need to click on "About us" from Action Sheet. Now try swipe to go back. It will not working. 

Please help me on this issue.

**Ionic Info:**

cli packages: (C:\Users\Macrew\AppData\Roaming\npm\node_modules)

    @ionic/cli-plugin-proxy : 1.4.11
    @ionic/cli-utils        : 1.12.0
    ionic (Ionic CLI)       : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.2
    npm               : 3.10.10
    OS                : Windows 10

**Comment by mhartington** [comment]
Hi there! So this would make  a lot of sense. In you're code you have 

```
  constructor(
    public nav: Nav,
    public navCtrl: NavController,
  ) {}
  onClickFriends() {
    this.navCtrl.push(FriendsPage);
  }

  onClickInfo() {
    this.nav.push(InfoPage);
  }
```

The `nav` in this case references the global `ion-nav` that you've declared in app.html.  Here, `Nav` mean navComponent.

`navCtrl` how ever means the current navigation stack, so what ever one the current View is part of . 

It's just a error of targeting the wrong stack.

![](http://g.recordit.co/UBhcS9sNfw.gif)
