### ISSUE TITLE
Feature request: Stepper Component

### ISSUE THREAD

**Issue by MatanYed** [ionic-team/ionic#13061]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
No wizard component

**Expected behavior:**
Make forms inside modal or popup with steps

**Comment by kensodemann** [comment]
Hello @MatanYed 

Thank you for your feature request!

Before I move this to the feature request repo, could you edit your request to expand on how you envision this working, what you are looking for, stuff like that? I want to make sure the feature request reflects what you are looking for or what your idea of a wizard component is before it gets moved.

FWIW, I have created wizards in Ionic applications before, and I am not sure a generic Wizard component would have helped me much where-as something like a [stepper](https://material.io/guidelines/components/steppers.html#) component would have helped a lot.

Thank you for using Ionic

**Comment by MatanYed** [comment]
@kensodemann sorry, I actually meant stepper
I saw quasar framework's stepper and it looks like necessary component in Ionic Framework

**Comment by kensodemann** [comment]
OK, that makes sense. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#315
