### ISSUE TITLE
Hmmer.js pan direction is not working as expected

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#13063]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
We have created a directive to support drag&drop on ionic with the included hammer.js lib.

The logic we are using is:
a) on press start drag behavior and listen to pan events
b) after press and start drag behavior set supported directions to ALL
c) ater drag finished or drop set directions to initial direction

We have to set direction because on ionic default direction for components is only left-right and there is now support of up and down.

This is a snippet of our code
```
@Directive({
    selector: '[la-draggable]'
})
....
    ngAfterViewInit() {
        this.hammer = new window['Hammer'](this.srcElement);
        this.defaultDirection = this.hammer.get('pan').options.direction;

        this.hammer.on('press', (ev) => {
            this.onPress(ev);
        });

        this.hammer.on('panmove', (ev) => {
            if (this.isDragging) {
                this.onPanMove(ev);
            }
        });
.....
 private onPress(ev) {
        this.hammer.get('pan').set({ direction: window['Hammer'].DIRECTION_ALL });
        // start drag&drop with custom logic
.....
```
The drag&drop functionallity we implemented is working well, but there is a problem on the DIRECTION_ALL, after setting this in onPress we logged the direction and it is sett well.

The problem is, if first PAN (move) we do is to the left or right anything is fine we can drag it on every point of the screen, and any events pan/panright/panleft/panup/pandown/pressup are notified.
But if we the first PAN (move) we do is to the down or to the up, no event is notified and also moving left right or pressup is never notified from then. So I think this should not a Hammer.js problem but a combination from ionic and hammer.js.

Mainly the thing we do is comming from Josh Morony drag drictive example, you can have a look here

https://www.joshmorony.com/building-an-absolute-drag-directive-in-ionic-2/

**Other information:**
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/lib/node_modules)
    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:
    cordova (Cordova CLI) : 7.0.1 

local packages:
    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:
    Android SDK Tools : 26.1.1
    Node              : v6.11.3
    npm               : 5.4.2 
    OS                : Linux 4.10

Misc:
    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by mburger81** [comment]
Hi @kensodemann,
I created a private repository with a very very simple example, it is available only to you as collaborator.
https://github.com/mburger81/ionic-drag/settings/collaboration

There is a directive called `DraggableDirective` which is handling our drag behavior.

As you can see I register some events on constructor, and on `onPress` which is firing after `300ms` I start the ability to `DRAG` an element. As you know ionic has set `hammer.js` direciton only to `X`, because on a mobile app there is the scroll behavior fox Y direction.

So first thing we do on drag start is setting DIRECTION_ALL for component. At the end after drag stop we set the default DIRECTION we have saved in constructor before.

So if you run simple `ionic serve` anything is fine, click 300ms on DIV and drag element over the screen anything is fine.

If you run `ionic cordova run android` and test the drag behavior on an android device (probably also on ios but we don't support ios for now) after pressing on the DIV the drag behavior is starting but at this point if your first PAN move is for **X** direction you can from now on drag the DIV all over the screen and it is working well.
But if your first PAN move is for **Y** direction, the PAN is interrupted without any other event fired and you have a screen like this.

![image](https://user-images.githubusercontent.com/3778892/31390224-a187b41c-add3-11e7-817a-43b826aa2b20.png)

You can see in front the dragged div and in background the original DIV.
Now if you release the screen nothing is happen but if you touch the DIV again and MOVE it you can go forward with the dragging behavior and if you release now the div the drag is stopped


Sorry for my bad English, I hope I was clear enough.
Thx
Michael

**Comment by mburger81** [comment]
Hi @kensodemann was my repository helpful? Where you able to reproduce the issue?

**Comment by kensodemann** [comment]
I have not had time to look at this issue yet.

**Comment by mburger81** [comment]
I opened also an issue for this problem on the hammer.js github repository
https://github.com/hammerjs/hammer.js/issues/1164
