### ISSUE TITLE
Misaligned navbar components in iOS 10

### ISSUE THREAD

**Issue by CoDanny** [ionic-team/ionic#13062]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.7.1**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Navigation bar icons are vertically misaligned in iOS 10

<img width="650" alt="screen shot 2017-10-06 at 3 27 03 pm" src="https://user-images.githubusercontent.com/542760/31279925-0b157904-aaab-11e7-8877-091c8533fe14.png">

**Expected behavior:**
The icons are vertically centered. Which happens in iOS 11

<img width="399" alt="screen shot 2017-10-06 at 3 30 50 pm" src="https://user-images.githubusercontent.com/542760/31280053-611bd136-aaab-11e7-8ff4-247dccdc4df3.png">

**Steps to reproduce:**

**Related code:**

```
  <ion-navbar>
    <ion-title (click)="scrollToTop()">{{'DASHBOARD.FILE_MANAGER' | translate }}</ion-title>
    <ion-buttons left>
      <button ion-button icon-only menuToggle>
        <ion-icon name="menu"></ion-icon>
      </button>
    </ion-buttons>
    <ion-buttons end>
      <button ion-button icon-only (click)="goToDashboard()">
        <ion-icon name="apps"></ion-icon>
      </button>
    </ion-buttons>
  </ion-navbar>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/arroyo/3dagogo-repos/AstroPrint-Mobile/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.5.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 5.0.8 
    Node              : v8.1.4
    npm               : 5.4.2 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy
```

**Comment by mhartington** [comment]
Hm, would you be able to try installing 

`npm i ionic-angular@3.7.1-201710032000`

This has a few more fixes for ios11, and does not seem to be causing issues for ios10 in my tests.

![simulator screen shot - iphone 6 10 2 - 2017-10-06 at 11 02 36](https://user-images.githubusercontent.com/2835826/31284657-38d7bab0-aa87-11e7-984d-778b30b69d3d.png)

**Comment by DavidRyu123** [comment]
I have tried to install the ionic-angular@3.7.1-201710032000 and still have same issue in iOS 10.

![kakaotalk_photo_2017-10-08-23-49-48](https://user-images.githubusercontent.com/29181677/31324713-8ab10e10-ac83-11e7-9226-e97bdd7afd19.jpeg)

**Comment by mattss** [comment]
I am seeing the same issue. Upgrading to ionic-angular@3.7.1-201710032000 had no effect on the problem.

**Comment by mattss** [comment]
I can replicate this by just cloning the ionic conference app (https://github.com/ionic-team/ionic-conference-app), and deploying to an iOS 10 simulator using XCode 9. Switching the same app to a simulator on iOS 11 looks fine.

<img width="432" alt="screen shot 2017-10-09 at 14 49 27" src="https://user-images.githubusercontent.com/1155400/31341315-15c7d39e-ad01-11e7-9ea5-61f9de050afd.png">

**ionic info** output

cli packages: 

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.5.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.3
    ios-deploy        : 1.9.2
    ios-sim           : 5.0.13
    Node              : v8.1.3
    npm               : 5.0.3
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235

Misc:

    backend : legacy

**Comment by mattss** [comment]
@mhartington As far as I can tell, this is due to ionic's base styles using the new 'safe area' CSS constants to calculate the header padding values. These are not available prior to iOS 11, and there don't appear to be any fallback styles set in the ionic stylesheets.

**Comment by mattss** [comment]
@mhartington More specifically, some items have a fallback padding value (e.g. child elements of ion-navbar), which is why the title and ion-segment look correct. However, ion-navbar itself has no fallback padding, which is why the buttons are positioned incorrectly.

**Comment by mhartington** [comment]
@mattss I'm still not able to replicate this. Using 

```
npm i ionic-angular@3.7.1-201710061612
```

![screen shot 2017-10-09 at 10 18 32 am](https://user-images.githubusercontent.com/2835826/31342633-62e70724-acdb-11e7-9e3c-83598b1cf523.png)
 
This is iPhone 6 running ios10.2, which doesn't have constant or env functions in css, it has the fall back values. 


In the screen shot, you can see the correct css padding/positioning being applied.

**Comment by mattss** [comment]
@mhartington that's a different version to the one you suggested above - will try that one instead thanks.

**Comment by kensodemann** [comment]
I am unable to duplicate _this_ issue with `npm i ionic-angular@3.7.1-201710061612`. iOS 11 is on the left, iOS 10.3.1 on the right:

<img width="913" alt="screen shot 2017-10-09 at 10 51 55 am" src="https://user-images.githubusercontent.com/1526846/31346939-5b00eec6-ace0-11e7-938a-375a18dde235.png">


However, it appears that #13046 is still an issue. Note the slightly lower title on the iOS 11 device:

<img width="925" alt="screen shot 2017-10-09 at 10 53 45 am" src="https://user-images.githubusercontent.com/1526846/31347040-a50e9fd6-ace0-11e7-9173-c3e23cc30a1b.png">


@mhartington - would you like me to reopen #13046? or would you like to just deal with that alignment issue here as well?

**Comment by mattss** [comment]
@mhartington I've just realised that this is only an issue if you build for production i.e with:

    ionic cordova build ios --prod

If you build without '--prod', the issue goes away. As far as I can tell, some CSS rules are being evaluated differently in production mode.

**Comment by mhartington** [comment]
Hmm, interesting. Alright, thanks for the tip @mattss

**Comment by DavidRyu123** [comment]
Put this CSS in each affected pages solved issues for me

`		@media only screen and (max-width: 767px) {
		.toolbar-ios.statusbar-padding:first-child {
		    padding-top: calc(20px + 4px);
		    min-height: calc(44px + 20px);
		}
		
		.toolbar-ios.statusbar-padding:first-child ion-title {
		    padding-top: 20px;
		    height: calc(44px + 20px);
		    min-height: calc(44px + 20px);
		}
	}`

**Comment by mhartington** [comment]
Hi, while this could work as a work around, it will be fixed in the framework.

**Comment by mhartington** [comment]
Hey everyone, can you try to update app-scripts to the `3.0.0-201710091726`

```
npm i @ionic/app-scripts@3.0.0-201710091726
```

There was a bug in dep where css was getting removed, causing this issue

**Comment by kensodemann** [comment]
@mhartington - the update to app-scripts fixed the main issue for me (tested with and without `--prod`)

The title being slightly lower than the `< Back` button on iOS 11 is still an issue, but. didn't really expect an app-scripts update to fix that...

**Comment by mhartington** [comment]
Title is looking good now.

Just pushed a fix, cut a release soon.

![screen shot 2017-10-09 at 2 46 03 pm](https://user-images.githubusercontent.com/2835826/31353465-b36e188e-ad00-11e7-8771-ff7ecdb114a1.png)

**Comment by mhartington** [comment]
New nightly is out!

```
npm i ionic-angular@3.7.1-201710091909
```

**Comment by mattss** [comment]
Works for me! Thanks @mhartington 👍

**Comment by zaq962** [comment]
it Works for me! Thanks @mhartington 

npm i @ionic/app-scripts@3.0.0-201710091726
