### ISSUE TITLE
Scroll-2-focus input issue with rendering on iOS

### ISSUE THREAD

**Issue by brunoAltinet** [ionic-team/ionic#13073]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On iOS, when focusing and scrolling to the top element that is half hidden, cloning and rendering breaks in a way that looks like duplicate element see image
1st image before focusing
![fullsizeoutput_3](https://user-images.githubusercontent.com/4034604/31313469-64e69c44-abe4-11e7-9f99-710fc51930b3.jpeg)

And second in the middle of scrolling to focus
![fullsizeoutput_4](https://user-images.githubusercontent.com/4034604/31313471-6d99dff4-abe4-11e7-892e-79f810c753ec.jpeg)

The end state:
![fullsizeoutput_5](https://user-images.githubusercontent.com/4034604/31313473-7ab3062a-abe4-11e7-8bc3-90ae677c03ce.jpeg)

**Expected behavior:**
No duplication or artefacts

**Steps to reproduce:**
have multiple input items, scroll down a bit and focus the top most input. To easily see what happens, have inputs as non-transparent (like in my example). Additionally, you can set breakpoint on subtree modification of input-wrapper
![screen shot 2017-10-08 at 03 38 58](https://user-images.githubusercontent.com/4034604/31313331-68d25bd0-abe0-11e7-891a-7cdd0550975e.png)

**Related code:**

I managed to mitigate the issue with setting visibility setting on cloned input while the clone input was present: add these lines to input.js:

-->

```
//add to cloneInputComponent function
//after line: srcComponentEle.style.pointerEvents = 'none';
srcComponentEle.style.visibility='hidden';

//add to removeClone function:
//after line: srcComponentEle.style.pointerEvents = '';
srcComponentEle.style.visibility='';
```
The scrolling is also much smoother when visibility is modified.

However, this causes a different issue with keyboard not popping up every time when trying to focus input.

**Comment by brunoAltinet** [comment]
Yea, visibility doesn't work because of the iOS touch and keyboard behaviour. opacity is better.

```
focusedInputEle.style.opacity = '0';
```

However, for some reason, it seems much smoother with visibility. That one would be ideal

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by brunoAltinet** [comment]
It's literally present on any form with inputs. You can see it on untappd app, register form, but it's less noticeable because inputs are transparent. The way it manifests itself in that app is that labels tend to show after the scroll event is finished, but in reality the textbox pushes the label outside the div with overflow hidden.
