### ISSUE TITLE
input: "ng-untouched ng-valid" becomes green

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic#13077]
**Ionic version:**  
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  
[x] bug report
[ ] feature request

**Current behavior:**  
I create a form

```html
<form [formGroup]="form">
  <ion-list>
    <ion-item>
      <ion-label floating>Number</ion-label>
      <ion-input type="number" formControlName="n"></ion-input>
    </ion-item>
  </ion-list>
</form>
```

and a form group with a default value for the input:

```ts
form = this.formBuilder.group({
  n: 10,
});
```

The input shows the value `10` and gets a green border (with android or wp styles).

**Expected behavior:**  
Since the input has not been touched yet and only shows the default value, it is indeed valid, but should not be validated yet. The class `ng-untouched ng-valid` should render a gray border and only `ng-touched ng-valid` should render as green/valid. I know this is an opinionated view but it doesn't make sense to give the user feedback on their input if they haven't input anything yet.

**Related code:**  
<https://ionic-pdttzg.stackblitz.io>

**Ionic info:**

```
cli packages:

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2
    Node       : v8.6.0
    npm        : 5.5.1
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

We have an upcoming review of various styling issues. I have marked this as something to look at when we do that.

Thank you for using Ionic

**Comment by simonhaenisch** [comment]
The design decision was to solve this in Ionic 4, I assume 😄
