### ISSUE TITLE
Lifecycle Events as Observables

### ISSUE THREAD

**Issue by patrickmcd** [ionic-team/ionic#13070]
**Ionic version:**  (check one with "x")
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] feature request

Please make the lifecycle events available as observables. There is a [similar feature request for Angular proper](https://github.com/angular/angular/issues/10185) to do the same ([and a second FR](https://github.com/angular/angular/issues/18876)).

The most obvious use case to unsubscribe from streams that you can't manage with the template.

```
constructor(
  private navCtrl: NavController,
  private lifecycleCtrl: LifecycleController
) { }

//...

ionViewDidLoad(): void {
  Observable.timer(0, 1000)
  .do(timerInt => {/* do stuff */})
  .takeUntil(this.lifecycleCtrl.ionViewWillLeave$);
  .subscribe();
}

// Or maybe it's part of the NavController?
// - this.navCtrl.lifecycle.ionViewWillLeave$ or
// - this.navCtrl.ionViewWillLeave$
```

But this could factor into your [nav guards discussion](https://github.com/ionic-team/ionic/issues/12193#issuecomment-334890769) as well.

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#316
