### ISSUE TITLE
Back button icon showing as a square box

### ISSUE THREAD

**Issue by lordnino** [ionic-team/ionic#13072]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**

Back button icon in the header showing as an square box

**Expected behavior:**

Normal Back button icon should appear in the header
![bug](https://user-images.githubusercontent.com/18020993/31312627-1b03773a-abc8-11e7-9621-5bcfce926fdf.png)

Sample App:
https://github.com/lordnino/sample-app.git

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by lordnino** [comment]
I found the issue in the package.json and solved thank you

**Comment by kensodemann** [comment]
Excellent! Glad to hear!

**Comment by CoachMorta** [comment]
hi , i have the same issue , what was the solution ?
