### ISSUE TITLE
Hardware back not working after displaying ads

### ISSUE THREAD

**Issue by prantikv** [ionic-team/ionic#13075]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**
After registering the hardware back then if ads are displayed, pressing the hardware back exits the app and does not bind to the normal behaviour

**Expected behavior:**
Hardware back should execute the registered fuctions

**Steps to reproduce:**

1.  Create a new app with any template add.
2.  Add the admob-free plugin
3.  Register hardwarback to log something(Not to exit).
4. Display ads.
5. Press hardware back

**Related code:**

**In the constructor of app.component.ts** register the back handler

```
        platform.registerBackButtonAction(() => {
        console.log("Back Pressed");
      });

```
Display banner ads or interstitals then without pressing anything in the app press the back button.
The app will exit. We are not exiting the app in our handler.

APP REPO [HERE](https://github.com/prantikv/ionicAdsBack).

A related issue can be seen [here.](https://github.com/floatinghotpot/cordova-admob-pro/issues/161)

**Ionic Info:**
```
cli packages: (C:\Users\prantikv\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.0.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.5
    Node              : v6.11.3
    npm               : 5.4.2
    OS                : Windows 10

Misc:

    backend : pro
```

**Comment by prantikv** [comment]
@kensodemann any update on this?

**Comment by kensodemann** [comment]
@prantikv - I have not had a chance to look at this yet.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is not an issue with the Ionic Framework. It appears to be some sort of issue with the plugin itself or with the way it interacts with the system.

If I change your code as such:

```ts
      setTimeout(() =>  this.displayBannerAds(), 10000);
      platform.registerBackButtonAction(() => {
        console.log("Back Pressed");
      });
```

I can bang on the hardware back button and keep getting the "Back Pressed" message in the console. As soon as the ad is displayed, hitting the app button will cause the app to exist without the handler being called, indicating the ad or the ad plugin is handling the back button press event and it is never getting to the Ionic app for us to handle.

Thank you for using Ionic
