### ISSUE TITLE
ImagePicker not working on iOS 11

### ISSUE THREAD

**Issue by lcoppinger** [ionic-team/ionic#13076]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have been successfully developing with the ImagePicker plugin up until recently, with what I believe to be the iOS11 update. Android is still working fine.

From what I can gather the .getPictures() function is not firing and no errors are shown in the console. The native iOS image picker is not launched at all nor is the request for access.

I am happy to explain further, I just wanted to initially check if this was an iOS11 issue or if others are not experiencing this, its probably something in my code.

**Expected behavior:**
.getPictures() function to open native image picker on iOS

**Steps to reproduce:**
Use ImagePicker on iOS 11 device or emulator

**Related code:**

addImages() {
    this.hasReadPermission();
    let imageCount = 10 - this.images.length;
    let options = {
      maximumImagesCount: imageCount,
      quality: 100,
      width: 500,
      height: 500,
      outputType: 1
    }
    this.imagePicker.getPictures(options).then(
      file_uris => { 
        for (let uri of file_uris) {
          var cameraImage 	= "data:image/jpeg;base64," + uri;
          let newImage = this.fb.group({
            image: cameraImage
          });
          this.images.push(newImage);
        }
      },
      err => console.log(err)
    );
  }

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages: (/Users/lisacoppinger/Projects/Development/TravelApp/node_modules)

    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 1.3.0
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.0.0

System:

    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    Node       : v6.11.2
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235

**Comment by lcoppinger** [comment]
When running on Xcode I get this error: 
ERROR: Plugin 'ImagePicker' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to close this issue because it does not appear to be an issue with the Ionic Framework but with a specific Cordova plugin. You should create an issue for that plugin.

You can also ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/) to see if anyone else has run across this.

Thank you for using Ionic
