### ISSUE TITLE
Android show footer tabs when focus on search input.

### ISSUE THREAD

**Issue by vellengs** [ionic-team/ionic#13079]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Android show footer tabs when focus on search input.
IOS is expected. 

**Expected behavior:**
The tabs bar should not goes up when keyboard showing.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by vellengs** [comment]
![image](https://user-images.githubusercontent.com/5743338/31365419-897ad69a-ad30-11e7-8773-170bf4c75430.png)
The tabs bar goes up following the keyboard.
It can be reproduced by new project " ionic start app super", just go to the search page.

**Comment by vellengs** [comment]
BTW, I run it with "ionic serve",  then use android browser.

**Comment by tem-akinduro-intraedge** [comment]
You use android browser on the web? do share details please @vellengs. That would come in handy. I also ran into the same issue. My fix was to do this. Would be ideal if the keyboard in view went over the footer tabs, andnot brought it into view:
```this.keyboard.onKeyboardShow().subscribe((): void => {
                document.body.classList.add('keyboard-in-view');
            });

            this.keyboard.onKeyboardHide().subscribe((): void => {
                document.body.classList.remove('keyboard-in-view');
            });``` 
I am then using that class to hide the footer tab with css

**Comment by vellengs** [comment]
@tem-akinduro-intraedge 
Can it work on web application without cordova?

**Comment by vellengs** [comment]
I found these API, 
https://ionicframework.com/docs/api/platform/Keyboard/
But I can not performance any effect with 'willHide' or 'willShow';
Anybody can show a demo with them?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This appears to be the default behavior for Android. I have found ways to make iOS behave like Android  via `keyboard.shrinkView(true);`, but not the other way around.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by TehCrucible** [comment]
@kensodemann Apologies, I know this isn't the place to ask however I was hoping you could quickly expand on this before closing this issue.

> I have found ways to make iOS behave like Android via `keyboard.shrinkView(true);`

I am actually after this behaviour, but the Keyboard class as referenced in the API docs doesn't contain this method?
