### ISSUE TITLE
No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

### ISSUE THREAD

**Issue by jordanpurinton** [ionic-team/ionic#13088]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
When I try to build for Android I run into this cryptic error message listed below.

**Expected behavior:**
For it to build successfully.

```
C:\...\platforms\android\build\intermediates\res\merged\debug\values-v26\values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.


 FAILED

BUILD FAILED

Total time: 26.595 secs

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\...\platforms\android\build\intermediates\res\merged\debug\values-v26\values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

C:\...\platforms\android\build\intermediates\res\merged\debug\values-v26\values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

[ERROR] An error occurred while running cordova run android (exit code 1).
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\...\node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.5
    Node              : v6.11.4
    npm               : 3.10.10
    OS                : Windows 10

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This isn't an Ionic Framework issue, so I am going to close this, but did you try the stuff mentioned here: https://stackoverflow.com/questions/45301203/no-resource-found-that-matches-the-given-name-attr-androidkeyboardnavigationc

Thank you for using Ionic

**Comment by Baburaomannepalli** [comment]
compileSdkVersion 26
    buildToolsVersion "26.0.1"
add this two fieelds in build.gradle file

**Comment by stplShubham** [comment]
@Baburaomannepalli Can you please specify exactly where do we need to add these two lines?

**Comment by grandhisubrahmanyam35** [comment]
Same issue, I am also facing but I am using Cordova. @stplShubham @Baburaomannepalli Could you please let me know if you find anything about this.

**Comment by marcjae** [comment]
@grandhisubrahmanyam35 and @stplShubham. Search for 'compileSdkVersion' or 'buildToolsVersion' in 'platforms/android/build.gradle'. Should find the following:
```
compileSdkVersion cdvCompileSdkVersion  
buildToolsVersion cdvBuildToolsVersion
```
Replace as above, then Gradle sync. Should be noted these values will be replaced each time the cordova project is generated.
