### ISSUE TITLE
Memory exhaustion [malloc_error_break]

### ISSUE THREAD

**Issue by qlic-git** [ionic-team/ionic#13086]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**
When trying to stringifying an Array of objects consisting of more than 8 pictures base64 encoded we are getting a memory warning followed by a failed to alocate resulting in a black screen

**Expected behavior:**
Getting a JSON string.

**Steps to reproduce:**
Install the cordova camera plugin use the following options 

```
quality: 100,
destinationType: this.camera.DestinationType.DATA_URL,
encodingType: this.camera.EncodingType.JPEG,
mediaType: this.camera.MediaType.PICTURE
```

Append 8 images to an array and JSON stringify the array.

**Other information:**
2017-10-09 15:54:22.453947+0200 xxxx[656:193147] -- MEMORY WARNING --
2017-10-09 15:54:22.471475+0200 xxxx[656:193147] -- MEMORY WARNING --
xxxx(656,0x42681000) malloc: *** mach_vm_map(size=96837632) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug

**Extra info**
This is using an Ipad 4. On an Ipad air 2 I dont seem to get the error.
**Ionic info:** 

```
cli packages: (/Users/Maantje1/Documents/Developing/igsys/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    npm        : 4.2.0
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to close this as it does not appear to be an issue with the Ionic Framework, but either with a plug-in or with the way the photos are being serialized.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/), or contact the maintainer of the plugin.

Thanks for using Ionic!

Thank you for using Ionic
