### ISSUE TITLE
timer stops on Android

### ISSUE THREAD

**Issue by Muneem** [ionic-team/ionic#13080]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have implemented timer. Its working fine. But this timer stops when there is input event like scroll. I get error in console that Blink Deffered a task in order to make scrolling faster. This behaviour is in android only. I have tried observable.timer, observable.interval and interval also. but same behaviour

**Expected behavior:**
Timer should not be stopped by input events. it should work as normal

**Steps to reproduce:**
create infinite scroll. Put timer of 10 minutes in each item in list. Do scroll. after sometime ou will notice timer stops when you scroll.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am closing this issue as it is not an issue with the Ionic Framework. I have linked a SO question that does a pretty good job describing the issue and what to do about it.

https://stackoverflow.com/questions/37367200/deferred-long-running-timer-tasks-to-improve-scrolling-smoothness

Basically, it sounds like you have a long running task or timeout while user input is still enabled, the browser detects that fact, and either suspends or completely dumps your long running timers.

The links given in the warning are also good reading, especially the RAIL link.

Thank you for using Ionic
