### ISSUE TITLE
Ionic 3 plays only 16 HTML5 videos present in a list

### ISSUE THREAD

**Issue by depakn** [ionic-team/ionic#13083]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
I have a list of videos.
The First 16 videos play as expected. But starting from 17th, the video keeps loading but it never played. 

I find this bug only on IOS device. On Android it works fine

**Expected behavior:**
All the videos in the list should play

**Steps to reproduce:**
An ion-list containing more than 20 videos makes this happen all time for me.

**Related code:**

`<ion-list>
     <ion-item *ngFor="let video of videos"> // Runs 50 times in a loop
         <video autoplay muted webkit-playsinline playsinline loop preload="auto">
              <source src="video.mp4" type="video/mp4"/>
         </video>
     </ion-item>
</ion-list>
`

**Other information:**
[#271](https://github.com/ionic-team/ionic-v1/issues/271) also is the same issue with Ionic 1. But i didnt find any answer in that

**Ionic info:**:

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.10.1
    ionic (Ionic CLI) : 3.10.1

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2
    Node       : v8.5.0
    npm        : 5.4.2
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by depakn** [comment]
You can find the application code [here](https://github.com/depakn/hahu-video16-bug).

**Comment by mhartington** [comment]
I dont think this is an issue with Ionic really.
I think you're hitting a memory limit trying to load a bunch of videos, and having them all autoplay.

Trying to run this on a simulator made my macbook pro CPU usage shoot right up.

This can be very expensive, since you're auto-playing all of the videos.

**Comment by depakn** [comment]
I've updated my code [here](https://github.com/depakn/hahu-video16-bug). Im playing only one video which is in the viewport. But, still i'm stuck with the same issue. Can you suggest some other way to solve this issue. Thanks for the reply anyways.
