### ISSUE TITLE
Ionic : Any solution for this error "git-sh-setup: file not found", attaching the log

### ISSUE THREAD

**Issue by jlahare** [ionic-team/ionic#13081]
C:\ionic\Orientation>ionic cordova plugin add cordova-plugin-screen-orientation
> cordova plugin add cordova-plugin-screen-orientation --save
x Running command - failed!
[ERROR] An error occurred while running cordova plugin add

        cordova-plugin-screen-orientation --save (exit code 1):

        Installing "cordova-plugin-screen-orientation" for android
        Failed to install 'cordova-plugin-screen-orientation': Error
             at
        C:\Users\Eclat\AppData\Roaming\npm\node_modules\cordova\node_modules\cor
dova-lib\src\plugman\fetch.js:205:33
             at _rejected
        (C:\Users\Eclat\AppData\Roaming\npm\node_modules\cordova\node_modules\co
rdova-fetch\node_modules\q\q.js:864:24)
             at
        C:\Users\Eclat\AppData\Roaming\npm\node_modules\cordova\node_modules\cor
dova-fetch\node_modules\q\q.js:890:30
             at Promise.when
        (C:\Users\Eclat\AppData\Roaming\npm\node_modules\cordova\node_modules\co
rdova-fetch\node_modules\q\q.js:1142:31)
             at Promise.promise.promiseDispatch
        (C:\Users\Eclat\AppData\Roaming\npm\node_modules\cordova\node_modules\co
rdova-fetch\node_modules\q\q.js:808:41)
             at
        C:\Users\Eclat\AppData\Roaming\npm\node_modules\cordova\node_modules\cor
dova-fetch\node_modules\q\q.js:624:44
             at runSingle
        (C:\Users\Eclat\AppData\Roaming\npm\node_modules\cordova\node_modules\co
rdova-fetch\node_modules\q\q.js:137:13)
             at flush
        (C:\Users\Eclat\AppData\Roaming\npm\node_modules\cordova\node_modules\co
rdova-fetch\node_modules\q\q.js:125:13)
             at _combinedTickCallback (internal/process/next_tick.js:131:7)
             at process._tickCallback (internal/process/next_tick.js:180:9)
        Error: Failed to fetch plugin
        https://github.com/vstirbu/PromisesPlugin.git via registry.
        Probably this is either a connection problem, or plugin spec is
        incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! code 1
        npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule
        update -q --init --recursive
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule:
        line 7: basename: command not found
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule:
        line 7: sed: command not found
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule:
        line 19: .: git-sh-setup: file not found
        npm ERR!

        npm ERR! A complete log of this run can be found in:
        npm ERR!
        C:\Users\Eclat\AppData\Roaming\npm-cache\_logs\2017-10-09T06_17_20_143Z-
debug.log

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

It may also help to look at the issues list in the [Ionic CLI repo](https://github.com/ionic-team/ionic-cli) as I believe issues like this have been reported and resolved in the past.

Have you tried installing the plugin via `cordova plugin add cordova-plugin-screen-orientation --save`? If that gives the same error, then there is likely an issue with the plugin.

Thanks for using Ionic!
