### ISSUE TITLE
Ionic 3 / Sqlite

### ISSUE THREAD

**Issue by kamalkech** [ionic-team/ionic#13089]
**Ionic version:**  **3.x**

**Plugins added:**
ionic cordova plugin add cordova-sqlite-storage
npm install --save @ionic-native/sqlite
ionic cordova plugin add cordova-plugin-x-toast
npm install --save @ionic-native/toast

Why we can't test sqlite lite on emulator ionic (ionic lab) : with this case my app not working and i get : 
"Runtime Error
Uncaught (in promise): cordova_not_available"

But working if i test on emulator android (ADB : Android Studio).

there is possibility to test on local : http://localhost:8100/ionic-lab ???

Any idea ?

**Comment by mhartington** [comment]
Since these cordova plugin, they need to be run on a real device or simulator in order to be used/tested

http://ionicframework.com/docs/troubleshooting/#cordova-plugins-not-working-in-the-browser

**Comment by rhernandez-itemsoft** [comment]
Help me please,
i get the "cordova_not_available"  error on my phone.
