### ISSUE TITLE
Toolbar primary color

### ISSUE THREAD

**Issue by piernik** [ionic-team/ionic#13084]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On chrome (in debugger - NexusX device) segment in header has blue text instead of white as in screenshot on https://forum.ionicframework.com/t/toolbar-primary-color/107917

**Related code:**

```
<ion-header>
    <ion-navbar color="primary">
        <button ion-button menuToggle>
            <ion-icon name="menu"></ion-icon>
        </button>
        <ion-title>Miejsca</ion-title>
    </ion-navbar>
    <ion-toolbar color="primary">
        <ion-segment [(ngModel)]="pet">
            <ion-segment-button value="kittens">
                Kittens
            </ion-segment-button>
            <ion-segment-button value="puppies">
                Puppies
            </ion-segment-button>
            <ion-segment-button value="kittens2">
                Kittens
            </ion-segment-button>
            <ion-segment-button value="puppies2">
                Puppies
            </ion-segment-button>
        </ion-segment>
    </ion-toolbar>
</ion-header>
```

**Comment by kensodemann** [comment]
The segment default to the color "primary", so if you set the thing the segment is in to also have a color of "primary" you need to set the color of the segment to something else. like this (note the `color="light"`:

```html
  <ion-toolbar color="primary">
      <ion-segment color="light" [(ngModel)]="pet">
          <ion-segment-button value="kittens">
              Kittens
          </ion-segment-button>
          <ion-segment-button value="puppies">
              Puppies
          </ion-segment-button>
          <ion-segment-button value="kittens2">
              Kittens
          </ion-segment-button>
          <ion-segment-button value="puppies2">
              Puppies
          </ion-segment-button>
      </ion-segment>
  </ion-toolbar>
```

**Comment by piernik** [comment]
Thanks - it's not clear though...

**Comment by kensodemann** [comment]
I didn't really like the way it looked with a darker background and the lighter text myself. Were it me, I would go with a light background and dark text for that, even if I had to go in and argue with a designer about it. I am not a fan of light text on dark backgrounds. I almost always find that harder to read.

If that wasn't going to work, I would probably adjust the font size and weight.

**Comment by piernik** [comment]
Saying 'clear' I was refering to syntax. I think if parent `ion-toolbar` has primary color it should also cover `ion-segment` - without extra code (`color light`).
