### ISSUE TITLE
Feature Request: Remove Windows UI and sort outstanding framework issues.

### ISSUE THREAD

**Issue by daveshirman** [ionic-team/ionic#13097]
**Ionic version:**  (check one with "x")
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] feature request

With the latest news that Microsoft has given up on Windows 10 for mobile, I suggest that: 

1. Windows UI portion of Ionic be scrapped.  
2. Any outstanding issues to do with Windows UI be scrapped.
3. Resources be re-focused on serious outstanding issues with the framework in Android, iOS + Desktop, e.g. keyboard, nav bugs, VirtualScroll

Please upvote this + comment if you think this could be a good move.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

RE item number 3, that is already what we are focused on, along with the general performance improvements that are part of version 4.

Thank you for using Ionic
