### ISSUE TITLE
Footer and toolbar inherit style class -md in Safari

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#13096]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request

**Current behavior:**
`ion-footer` and `ion-toolbar` inherit style class `-md` in Safari
 
**Expected behavior:**
If I'm not saying something wrong, in Safari these elements should inherit `-ios` style classes

**Steps to reproduce:**
1. See code
2. Test in Safari

**Related code:**

    <ion-header></ion-header>
    <ion-content><div>hello is it you?</div></ion-content>
    <ion-footer><ion-toolbar><div>-md class instead of -ios</div></ion-toolbar></ion-footer>

Result:

    <ion-footer class="footer footer-md">
        <ion-toolbar class="toolbar toolbar-md">

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages:

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0 ios 4.5.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 5.0.13 
    Node              : v8.5.0
    npm               : 5.3.0 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

See the [platform section of the theming docs](https://ionicframework.com/docs/theming/platform-specific-styles/).

Running on Safari on your Mac falls into the `core` bucket, and thus defaults to the MD styles.

Thank you for using Ionic

**Comment by peterpeterparker** [comment]
@kensodemann thx for the explanation!

I gonna keep an eye on that because I thought that this was the reason why my `flex` box inside my `ion-footer/ion-toolbar` since the fixes for iPhone X aren't properly displayed anymore on iOS (simulator and real devices, iPhone6 etc.). 

Anyway, in the meantime I found a workaround without flex (but I rather like with flex, css would be less ugly).

**Comment by kensodemann** [comment]
What I usually do to test the `-ios` styles in a browser is to run it in Chrome, open the dev tools, and then use the dev tools to emulate an iOS device. Works great (plus the dev tools in Chrome are _way_ better than what you get in Safari, so bonus there as well).

**Comment by peterpeterparker** [comment]
@kensodemann yes I usually do the same but in this special case, chrome (in dev tools as you described) rendered correctly my `flex` boxes in my `ion-footer/ion-toolbar` where the iOS terminals didn't, therefore I thought I would be maybe more close to the rendering result while trying with Safari

**Comment by peterpeterparker** [comment]
anyhow I found a workaround and I gonna keep an eye on it, I saw that some more fixes for iOS 11 are incoming ;)
