### ISSUE TITLE
ion-slides with both vertical and horizontal sliding

### ISSUE THREAD

**Issue by rangathedon** [ionic-team/ionic#13093]
Is it possible to have an ionic-slides component which supports both swiping vertically and horzontally? I need to implement a 4 way swipe where a swipe in a specific direction indicates an action to be performed and then loads the next view;

I tried nesting the slides with the code below but it only scrolls in the direction mentioned in the first nested ionic-slides element;

```
<ion-content>
 
<ion-slides loop parallax spaceBetween="10" effect="slide">
  <ion-slide style="background-color: green">
		<ion-slides loop parallax spaceBetween="10" effect="slide"  direction="vertical">
		<ion-slide style="background-color: green">
		<h2>Slide 1</h2>
		<h2>Slide 4</h2>
		</ion-slide>
		<ion-slide style="background-color: blue">
		<h2>Slide 1</h2>
		<h2>Slide 5</h2>
		</ion-slide>
		</ion-slides>
  </ion-slide>
  <ion-slide style="background-color: blue">
		<ion-slides loop parallax spaceBetween="10" effect="slide"  direction="vertical">
		<ion-slide style="background-color: green">
		<h2>Slide 2</h2>
		<h2>Slide 7</h2>
		</ion-slide>
		<ion-slide style="background-color: blue">
		<h2>Slide 2</h2>
		<h2>Slide 8</h2>
		</ion-slide>
		</ion-slides>
  </ion-slide>
</ion-slides>

</ion-content>
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Looking at the [Swiper documentation](http://idangero.us/swiper/api/#.WdzSXEyZPBI) (which is the library that this was adapted from, and will be used more directly in v4), it appears that vertical or horizontal is supported, but not both at the same time.

Thanks for using Ionic!

**Comment by rangathedon** [comment]
Thanks for the response but there is a swiper demo which shows nested swipers with vertical swiper nested within horizontal swipers; would this still be not considered an issue and some quick hack or solution provided??? 

The demo is available at http://idangero.us/swiper/demos/11-nested.html
