### ISSUE TITLE
virtual-scroll cards broken

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#13099]
Looks like ionic-conference-app is broken using latest ionic:
https://www.dropbox.com/s/d53z4ppe6hhxmtz/virtual-scroll-whoa.mov?dl=0

@masimplo any idea of what could be happening after your change?

**Comment by masimplo** [comment]
Wasn't aware conference-app was using virtual scroll with cards, otherwise I would have checked there first. Will check and let you know when I find something.

**Comment by manucorporat** [comment]
@masimplo I am also looking at it :) hope it is an easy fix, please let me know if you find something!

**Comment by masimplo** [comment]
Ok I have some findings. First, cards are not broken if being single column (try resizing the window to allow one column and scroll then).
So the issue is specific to multi-column virtual scroll.
Add a few debug messages I managed to pinpoint the issue in `adjustRendered` function. Problem is that the range of cells to render (ie. data.topCell - data.bottomCell) is smaller than the range of cell in the viewPort (i.e. data.topViewCell - data.bottomViewCell)

Not sure why this is so, but I will start from there.

```
virtual-util will render cells from 5 to 11 while viewCells are from 3 to 11
16virtual-scroll.js:643 virtual-scroll scrollUpdate stepNoChanges
virtual-util.js:471 virtual-util will render cells from 5 to 11 while viewCells are from 0 to 11
virtual-scroll.js:643 virtual-scroll scrollUpdate stepNoChanges
virtual-util.js:471 virtual-util will render cells from 2 to 8 while viewCells are from 0 to 8
8virtual-scroll.js:643 virtual-scroll scrollUpdate stepNoChanges
virtual-util.js:471 virtual-util will render cells from 2 to 8 while viewCells are from 0 to 8
```

**Comment by masimplo** [comment]
I think I have now pinpointed the issue.

AdjustRendered function calculates how many cells will fit in viewHeight * bufferRatio (minus a single item, not sure why, but it's ok), but it does not account for the fact that more than one cells per row might be rendered. I am pretty sure that this is how it worked previously as well, but I might be wrong... but pretty sure!

A possible remedy for that would be to have bufferRatio account for multiple columns. So if you rendered a single column list and had to use bufferRatio of value 3, then having a 5 column list, bumping bufferRatio to 3*5=15 would do the exact same job.

Problem is that I do not see passed value for bufferRatio to be propagated through the code. 

@manucorporat please let me know what you think of my reasoning and if a documentation entry for how bufferRatio should be leveraged for use of virtual scroll in multi-column list would be a plausible solution to this.

**Comment by masimplo** [comment]
BTW approxItemHeight is applied on the wrong element and approxItemWidth would help with this sample. Also resizing the window while in the speakers tab triggers an assertion

```
Error: IONIC ASSERT: contentTop has to be positive
    at _assert (http://localhost:8100/build/vendor.js:15511:15)
    at Content._writeDimensions (http://localhost:8100/build/vendor.js:30248:79)
    at dispatch (http://localhost:8100/build/vendor.js:19609:9)
    at DomController._flush (http://localhost:8100/build/vendor.js:19553:13)
    at rafCallback (http://localhost:8100/build/vendor.js:19542:22)
```
