### ISSUE TITLE
CORS error on Device

### ISSUE THREAD

**Issue by ZuraM** [ionic-team/ionic#13094]
i have a problem with CORS when i install built apk on my actual device. when i run app on emulator or with `ionic serve` or even with `ionic run` it works fine. after installing on actual device on every HTTP request it gives this output:

    {"_body": {"isTrusted": true}, "status": 0, "ok": false, "statusText": "", "headers": {}, "type": 3, "url": null}

here's `ionic info` output and proxy config in `ionic.config.json` file.

    cli packages: (/usr/lib/node_modules)
    
        @ionic/cli-plugin-proxy : 1.4.11
        @ionic/cli-utils        : 1.12.0
        ionic (Ionic CLI)       : 3.12.0
    
    global packages:
    
        cordova (Cordova CLI) : 7.0.1
    
    local packages:
    
        @ionic/app-scripts : 3.0.0
        Cordova Platforms  : android 6.2.3
        Ionic Framework    : ionic-angular 3.7.1
    
    System:
    
        Android SDK Tools : 26.1.1
        Node              : v8.6.0
        npm               : 5.3.0
        OS                : Linux 4.4

ionic.config.json

    {
    "name": "myapp",
    "app_id": "",
    "type": "ionic-angular",
    "integrations": {
        "cordova": {}
    },
    "proxies": [{
        "path": "/api",
        "proxyUrl": "https://www.someapi.com/"
    }]}
config.xml

    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
