### ISSUE TITLE
Multiple videos memory dump issue

### ISSUE THREAD

**Issue by DeepakNatraj** [ionic-team/ionic#13092]
Ionic version:
[x] 3.x

I'm submitting a ...
[x ] feature request

Current behavior:
I have a list of videos.
The First 16 videos play as expected. But starting from 17th, the video keeps loading but it never played.

I find this bug only on IOS device. On Android it works fine.

[mhartington](https://github.com/mhartington) on a reply told it was because of hitting a memory limit trying to load a bunch of videos and autoplaying all but here only one video which is in the viewport is being played. But even then then i'm getting the same issue. Im new to Ionic and not sure how to solve this.

Expected behavior:
All the videos in the list should play

Steps to reproduce:
An ion-list containing more than 20 videos makes this happen all time for me.

I have my code [here](https://github.com/DeepakNatraj/VideoFeedPlayOnViewport). 

Other information:
#271 also is the same issue with Ionic 1. But i didnt find any answer in that

Ionic info::

`cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.10.1
    ionic (Ionic CLI) : 3.10.1

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2
    Node       : v8.5.0
    npm        : 5.4.2
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235`

**Comment by dylanvdmerwe** [comment]
Why not just use a plain `<video>` tag?
