### ISSUE TITLE
ionic cordova platform add ios / ionic cordova resources dead

### ISSUE THREAD

**Issue by IncognitoCore** [ionic-team/ionic#13098]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ionic cordova platform add ios
> cordova platform add ios --save
✔ Running command - done!
> ionic cordova resources ios --force
✔ Collecting resource configuration and source images - done!
✔ Filtering out image resources that do not need regeneration - done!
✖ Uploading source images to prepare for transformations - failed!
HTTP Error 503: POST https://res.ionic.io/api/v1/upload
<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>

**Expected behavior:**
ionic cordova platform add ios
> cordova platform add ios --save
✔ Running command - done!
> ionic cordova resources ios --force
✔ Collecting resource configuration and source images - done!
✔ Filtering out image resources that do not need regeneration - done!
✔ Uploading source images to prepare for transformations - done!

**Steps to reproduce:**
ionic start
> test
> blank
cd test
ionic cordova platform remove ios
ionic cordova platform add ios

**Related code:**

**Other information:**
`ionic cordova resources` gives the same error.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
cli packages: (/Users/Kevin/.config/yarn/global/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 6.5.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.3.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.2
    ios-deploy        : 1.9.0
    ios-sim           : 5.0.8
    Node              : v8.4.0
    npm               : not installed
    OS                : macOS High Sierra
    Xcode             : Xcode 9.0 Build version 9A235

Misc:

    backend : legacy

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

As this is not an issue with the Ionic Framework, I am going to move this to the Ionic CLI repo.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2793
