### ISSUE TITLE
iOS: md mode missing statusbar-padding on toolbar-content when built with --prod

### ISSUE THREAD

**Issue by shawnlan** [ionic-team/ionic#13108]
Running on Ionic 3.7.0. This is a weird issue. My app is built with tabs and uses `md` mode on iOS:

```
IonicModule.forRoot(MyApp, {
      swipeBackEnabled: true,
      mode: "md"
    }),
```

The issue is when built the app with `--prod` option: `ionic cordova run ios --prod`, `statusbar-padding` class is not added to `toolbar-content`. The result is that the title of the nav bar moves upwards 20px.

You can reproduce it by generating a new project with `tabs` template, and force it to use `md` mode even when on iOS (see the code above). Build it with `ionic cordova run ios --prod` and see the title off position.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I believe this is a repeat of #13062, which is fixed via a soon to be released update to `@ionic/app-scripts` and `ionic-angular`

You can try the nightly pre-release builds as such:

```
npm i @ionic/app-scripts@3.0.0-201710091726
npm i ionic-angular@3.7.1-201710091909
```

Let me know the results of that. We are planning on releasing it soon.

Thank you for using Ionic

**Comment by shawnlan** [comment]
Works! Thank you!

**Comment by kensodemann** [comment]
Excellent! I am going to close this then. The fix will be included with the next release, which is currently in testing.
