### ISSUE TITLE
The package appears to be currupted

### ISSUE THREAD

**Issue by kaito-kaito** [ionic-team/ionic#13105]
Hi there
I'm trying to build my app with a release version but when I install it it always gives me (The package appears to be currupted)
I also tried to create a new app and then build it with release and prod, the problem still the same.
But with debug version it works fine.
I tried to use both release and prod.
I tried to install it in different device.
All attempts failed
Hope you can help me
Thank you

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

There is not enough information here, but this does not seem to be an Ionic Framework issue, but perhaps a [CLI](https://github.com/ionic-team/ionic-cli) or [app-scripts](https://github.com/ionic-team/ionic-app-scripts) issue, so looking at the issues posted on those repos may prove to be helpful as well.

Thanks for using Ionic!
