### ISSUE TITLE
Cannot read property '_getPortal' of undefined

### ISSUE THREAD

**Issue by jun58** [ionic-team/ionic#13109]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

**home.component.ts**
```
import { PopoverController } from 'ionic-angular';
import { PopoverPageComponent } from '../popover-page/popover-page.component';

presentPopover (myEvent) {
    let popover = this.popoverCtrl.create(PopoverPageComponent);
    popover.present();
  }
```
**popover-page.component.ts**
```
import {  ViewController } from 'ionic-angular';

constructor(
    public viewCtrl: ViewController
  ) { }
  close() {
    this.viewCtrl.dismiss();
  }
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
λ ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

cli packages: (F:\bud_mobile_static\node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

System:

    Node : v6.10.0
    npm  : 3.10.10
    OS   : Windows 10

Misc:

    backend : legacy

```
I create a app use angular2+, and want use **Popover** of ionic, like above,but when I run npm start click
element to show popover, a mistake happend, **Cannot read property '_getPortal' of undefined**
![rtx](https://user-images.githubusercontent.com/20509429/31420599-0ecfb7f8-ae75-11e7-9b5c-5a2dda65f8f1.png)

so what should I do ? it take me a lot of time

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

Also, based on your `ionic info` it does not look like you are in an Ionic project, so I am somewhat confused by what you are actually trying to do.

Thanks for using Ionic!

**Comment by jun58** [comment]
@kensodemann
thank you for your attention。as what I have said above，I create a App by angular-cli，and I just
want to use popover of ionic，so I install ionic
in my project，I use popover refer to demo 。I just want use ui component of ionic。but mistake happened

**Comment by kensodemann** [comment]
Thank you for opening an issue with us!

The current Ionic components were not designed to be used outside of Ionic applications. This _might_ become something that is possible once we are using [Stencil](https://stenciljs.com) to write our components. At least the component itself should be reusable anywhere at that point.

Thanks for using Ionic!
