### ISSUE TITLE
Ion-list buttons in menu are not vertically aligned for some icons

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#13102]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
We have a ion-list with different buttons and different ion-icons for our main menu, something like that
```
    <ion-list no-lines>
      <button ion-item menuClose><ion-icon name="wifi" item-left></ion-icon>Menu Point 1</button>
      <button ion-item menuClose><ion-icon name="outlet" item-left></ion-icon>Menu Point 2</button>
      <button ion-item menuClose><ion-icon name="videocam" item-left></ion-icon>Menu Point 3</button>
      <button ion-item menuClose><ion-icon name="appstore" item-left></ion-icon>Menu Point 4</button>
      <button ion-item menuClose><ion-icon name="stats" item-left></ion-icon>Menu Point 5</button>
      <button ion-item menuClose><ion-icon name="cloud-download" item-left></ion-icon>Menu Point 6</button>
      <button ion-item menuClose><ion-icon name="thermometer" item-left></ion-icon>Menu Point 7</button>
      <button ion-item menuClose><ion-icon name="alarm" item-left></ion-icon>Menu Point 8</button>
      <button ion-item menuClose><ion-icon name="pricetags" item-left></ion-icon>Menu Point 9</button>
      <button ion-item menuClose><ion-icon name="people" item-left></ion-icon>Menu Point 10t</button>
      <button ion-item menuClose><ion-icon name="log-out" item-left></ion-icon>Menu Point 11</button>
    </ion-list>
```
The problem is in this case the text for one button we the `cloud-download` icon is not aligned vertically with the other buttons, see the screenshot

![image](https://user-images.githubusercontent.com/3778892/31391271-58274ac8-add6-11e7-9980-44b2a27819d7.png)

Having a look to the icons the cloud-download icon is 26,25px width but most of the other are only 24px and some are 24.5px.

I created a repository where you can reproduce this issue
https://github.com/mburger81/ionic-menu-alignment

**Expected behavior:**
I don't know if the icons should be all the same size but I think for sure all the buttons and there label should be vertically aligned

**Steps to reproduce:**
https://github.com/mburger81/ionic-menu-alignment
`ionic serve`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/lib/node_modules)
    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

local packages:
    @ionic/app-scripts : 3.0.0
    Ionic Framework    : ionic-angular 3.7.1

System:
    Node : v6.11.4
    npm  : 5.4.2 
    OS   : Linux 4.10

Misc:
    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The `min-width` is set to 24px in **item-media.scss**:

```sass
.item > ion-icon:first-child,
.item-inner > ion-icon:first-child {
  @include text-align(center);

  min-width: 24px;
}
```

That is probably too low given that some icons are larger than 24px. Or perhaps the larger icons should be shrunk. That is a design issue, and I will mark this as such as we have a review coming up on this.

To get around your immediate issue you can add SASS similar to the following to whatever page has the buttons:

```sass
page-home {
  .item > ion-icon:first-child {
    min-width: 28px;
  }
}
```

Thank you for using Ionic
