### ISSUE TITLE
I got error while  adding platfrom for ios ....      $sudo ionic cordova platform add ios

### ISSUE THREAD

**Issue by abmnukmr** [ionic-team/ionic#13114]
Abhimanyus-MacBook-Pro:Vioti abhimanyukumar$ sudo ionic cordova platform add ios
> cordova platform add ios --save
✖ Running command - failed!
[ERROR] Exception: 

        You have been opted out of telemetry. To change this, run: cordova telemetry on.
        Using cordova-fetch for cordova-ios@~4.4.0
        Adding ios project...
        Creating Cordova project for the iOS platform:
                Path: platforms/ios
                Package: com.vaioti
                Name: VAIOTI
        iOS project created with cordova-ios@4.4.0
        Installing "com.googlemaps.ios" for ios
        Installing "cordova-plugin-actionsheet" for ios
        Installing "cordova-plugin-add-swift-support" for ios
        Installing "cordova-plugin-admobpro" for ios
        Plugin dependency "cordova-plugin-extension@1.5.1" already fetched, using that version.
        Installing "cordova-plugin-extension" for ios
        Installing "cordova-plugin-app-event" for ios
        Installing "cordova-plugin-camera" for ios
        Plugin dependency "cordova-plugin-compat@1.1.0" already fetched, using that version.
        Installing "cordova-plugin-compat" for ios
        Dependent plugin "cordova-plugin-compat" already installed on ios.
        Installing "cordova-plugin-console" for ios
        Installing "cordova-plugin-crop" for ios
        Installing "cordova-plugin-device" for ios
        Dependent plugin "cordova-plugin-extension" already installed on ios.
        Installing "cordova-plugin-facebook4" for ios
        Installing "cordova-plugin-file" for ios
        Plugin dependency "cordova-plugin-compat@1.1.0" already fetched, using that version.
        Dependent plugin "cordova-plugin-compat" already installed on ios.
        Installing "cordova-plugin-file-transfer" for ios
        Plugin dependency "cordova-plugin-file@4.3.1" already fetched, using that version.
        Dependent plugin "cordova-plugin-file" already installed on ios.
        Installing "cordova-plugin-filepath" for ios
        Installing "cordova-plugin-geolocation" for ios
        Plugin dependency "cordova-plugin-compat@1.1.0" already fetched, using that version.
        Dependent plugin "cordova-plugin-compat" already installed on ios.
        Installing "cordova-plugin-googlemaps" for ios
        Plugin dependency "com.googlemaps.ios@2.4.0" already fetched, using that version.
        Dependent plugin "com.googlemaps.ios" already installed on ios.
        
                      In order to run this plugin, you need to obtain Google Maps API key for iOS.
                      Visit https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Installation
        
                      Check our release notes.
                      https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Release-Notes
                
        Installing "cordova-plugin-googleplus" for ios
        Google Sign-In prerequisites
        START Running hook to add iOS Keychain Sharing entitlements (required since iOS 10)
        Will add iOS Keychain Sharing entitlements to project 'VAIOTI'
        END Running hook to add iOS Keychain Sharing entitlements (required since iOS 10)
        Installing "cordova-plugin-inappbrowser" for ios
        Installing "cordova-plugin-mauron85-background-geolocation" for ios
        Installing "cordova-plugin-nativegeocoder" for ios
        Plugin dependency "cordova-plugin-add-swift-support@1.6.0" already fetched, using that version.
        Dependent plugin "cordova-plugin-add-swift-support" already installed on ios.
        Installing "cordova-plugin-network-information" for ios
        Installing "cordova-plugin-settings-hook" for ios
        Installing "cordova-plugin-splashscreen" for ios
        Installing "cordova-plugin-statusbar" for ios
        Installing "cordova-plugin-uniquedeviceid" for ios
        Installing "cordova-plugin-whitelist" for ios
        Installing "cordova-plugin-wkwebview-engine" for ios
        Installing "cordova-plugin-x-toast" for ios
        Installing "cordova-sqlite-storage" for ios
        installing external dependencies via npm
        npm install of external dependencies ok
        Installing "cordova.plugins.diagnostic" for ios
        Installing "de.appplant.cordova.plugin.local-notification" for ios
        Plugin dependency "cordova-plugin-device@1.1.3" already fetched, using that version.
        Dependent plugin "cordova-plugin-device" already installed on ios.
        Plugin dependency "cordova-plugin-app-event@1.2.1" already fetched, using that version.
        Dependent plugin "cordova-plugin-app-event" already installed on ios.
        Installing "ionic-plugin-keyboard" for ios
        Installing "mx.ferreyra.callnumber" for ios
        Installing "phonegap-plugin-barcodescanner" for ios
        Installing "phonegap-plugin-push" for ios
        **Failed to install 'phonegap-plugin-push': undefined
        Error:     WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
             Consider adding the following to ~/.profile:
        
             export LANG=en_US.UTF-8
             
        /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as 
        root. (CLAide::Help)
        
        Usage:
        
             $ pod COMMAND
        
               CocoaPods, the Cocoa library package manager.
        
        Commands:
        
             + cache      Manipulate the CocoaPods cache
             + env        Display pod environment
             + init       Generate a Podfile for the current directory
             + install    Install project dependencies according to versions from a
                          Podfile.lock
             + ipc        Inter-process communication
             + lib        Develop pods
             + list       List pods
             + outdated   Show outdated project dependencies
             + repo       Manage spec-repositories
             + setup      Setup the CocoaPods environment
             + spec       Manage pod specs
             + update     Update outdated project dependencies and create new Podfile.lock
        
        Options:
        
             --silent     Show nothing
             --version    Show the version of the tool
             --verbose    Show more debugging information
             --no-ansi    Show output without ANSI codes
             --help       Show help banner of specified command
                from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:47:in `run'
                from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
                from /usr/local/bin/pod:22:in `load'
                from /usr/local/bin/pod:22:in `<main>'**

ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

System:

    Node : v6.11.4
    npm  : 3.10.10 
    OS   : macOS High Sierra

Misc:

    backend : pro

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

That said, why are you using `sudo` to install a plugin locally? You should never need to use `sudo` for a local install.

Globally you may or may not need it, depending on how you have `node` and `npm` installed.

Thanks for using Ionic!
