### ISSUE TITLE
ion-img doesn't use new angular HttpClient, preventing custom header usage

### ISSUE THREAD

**Issue by snortblt** [ionic-team/ionic#13115]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.7.1**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X ] feature request

**Current behavior:**
The ion-img component, besides being fairly hamstrung by it's limited use cases (within virtual scroll linear list only), doesn't appear to be using the new HttpClient for requests. In a mobile context, where token based auth is increasingly the norm, I can't send an http Authorize header with normal image requests.  This is currently a big hole in ionic/cordova that doesn't have a clean solution in apps that use images in a variety of places.

**Expected behavior:**
Ideally, the ion-img would not only work for ANY image use case (not just in virtual scroll) but also be using the HttpClient so one could provide an app-global HttpInterceptor to authenticate img requests. 

**Steps to reproduce:**
Self explanatory

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0 windows 5.0.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.1
    Node              : v6.11.3
    npm               : 3.10.10
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235

Misc:

    backend : legacy

**Comment by kensodemann** [comment]
Hell0! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#318
