### ISSUE TITLE
ion-slides with both vertical and horizontal sliding with nesting

### ISSUE THREAD

**Issue by rangathedon** [ionic-team/ionic#13110]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Is it not possible to have an ionic-slides component which supports both swiping vertically and horzontally? I need to implement a 4 way swipe where a swipe in a specific direction indicates an action to be performed and then loads the next view;

I tried nesting the slides with the code below but it only scrolls in the direction mentioned in the first nested ionic-slides element;

```
<ion-content>
	<ion-slides loop effect="slide" direction="vertical">
		<ion-slide style="background-color: green">
			<ion-slides loop effect="slide">
				<ion-slide style="background-color: green">
					<h2>Slide 1</h2>
					<h2>Slide a</h2>
				</ion-slide>
				<ion-slide style="background-color: blue">
					<h2>Slide 1</h2>
					<h2>Slide b</h2>
				</ion-slide>
			</ion-slides>
		</ion-slide>

		<ion-slide style="background-color: blue">
			<ion-slides loop effect="slide">
				<ion-slide style="background-color: green">
					<h2>Slide 2</h2>
					<h2>Slide a</h2>
				</ion-slide>
				<ion-slide style="background-color: blue">
					<h2>Slide 2</h2>
					<h2>Slide b</h2>
				</ion-slide>
			</ion-slides>
		</ion-slide>
	</ion-slides>
</ion-content>
```

**Other information:**
Also, there is a swiper demo which shows nested swipers with vertical swiper nested within horizontal swipers; would this still be not considered an issue and some quick hack or solution provided???

The demo is available at http://idangero.us/swiper/demos/11-nested.html

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

After discussions internally, we determined this is not a bug but a feature request as nesting the slides as such was not something that was taken into consideration in the design.

I'm going to move this issue over to our internal list of feature requests for future evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#317

**Comment by rangathedon** [comment]
Is there any quick setting or hack which may get this working for me? I just need to use it in one app;

**Comment by kensodemann** [comment]
Not that I know of.

Have you tried asking your question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/)?

**Comment by rangathedon** [comment]
Forums already have multiple unanswered questions on the same topic; its a basic feature for most apps of today; not sure why ionic is missing is in-spite of being around for some years now;

**Comment by mskrzyniarz** [comment]
Here is PR that resolving this issue:
https://github.com/ionic-team/ionic/pull/13370
