### ISSUE TITLE
Generate code using --minimal flag

### ISSUE THREAD

**Issue by CoreyCole** [ionic-team/ionic#13113]
I want to implement a flag for the [generate](https://ionicframework.com/docs/cli/generate/) command that uses alternative templates that only include the bare minimum copypasta. Inspired from the`--minimal` flag in the [angular-cli](https://github.com/angular/angular-cli/wiki/new).

The things I would omit would be:
- auto generated comments i.e. "Generated template for the ... "
- `ionViewDidLoad()` console log

But I'm open to suggestions about what else could be removed to be more "minimal". These are just the things that I delete straight away every time I use the generator, so I'd love to automate that.

Is this a possibility? Are you guys open to something like this? I saw no issues about anything similar, but I did find some similar interest on the forums from a while ago [[1](https://forum.ionicframework.com/t/how-can-i-modify-the-default-cli-templates-for-creating-page-or-provider-with-the-generate-option/51967)]

### Implementation Questions
I see that the template files live in https://github.com/ionic-team/ionic/tree/master/scripts/templates but I can't find where the bash flags are processed. I found https://github.com/ionic-team/ionic/blob/master/scripts/utils.sh.inc but I'm not much of a bash wizard and don't see where ARG_DEFS is defined. A search in the repository for `--no-module` or `--constants` didn't come up with anything. (current flags on generate command)

Once I figure that out.. A naive approach might be independently tracking `templates/minimal` as alternatives and then using those when the flag is present. But, this would cause extra work when changing the templates in multiple places. Like I said, I'm no bash wizard, but maybe wrap the unwanted copypasta in an IF block?

I'd love a little nudge in the right direction for this. Thanks~

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

That sounds like a great idea. I personally do this same thing (generate and then grumble as I remove the comments).

I would probably also remove `ionViewDidLoad()` entirely and not just the `console.log()` bit. If I want / need the lifecycle hooks, I know how to add them.

This query itself should probably be a feature request on the https://github.com/ionic-team/ionic-cli repo.

Thank you for using Ionic

**Comment by CoreyCole** [comment]
Thanks for a quick response! I opened a pull request with the ionic-cli repo [here](https://github.com/ionic-team/ionic-cli/pull/2799)
