### ISSUE TITLE
What is the origin of the ionic name?

### ISSUE THREAD

**Issue by AmazingMoon** [ionic-team/ionic#13112]
I would like the author to give a detailed description.
@alakra 
@mlynch 
@alexweber 
@ericb 
@lwu

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is neither a bug nor a feature request, so I am going to close it.

That is not a reflection on your question. It is just that we use this list to prioritize what work needs to be done with `ionic-angular`

Thank you for using Ionic

**Comment by mlynch** [comment]
When we started working on Ionic we were a small software company building app design tools (Codiqa and Jetstrap, if anyone remembers). We had an idea to build a better mobile web UI framework but needed a name.

I remember spending weeks writing every name that came to mind on a big whiteboard, and “Ionic” was the one we hated the least 😂

**Comment by AmazingMoon** [comment]
@mlynch 
Thank you for your answer! Is the Ionic logo inspired by the chemistry of ions?
