### ISSUE TITLE
No installed build tools found. Install the Android build tools version 19.1.0 or higher.

### ISSUE THREAD

**Issue by oceankai** [ionic-team/ionic#13120]
on my Mac，ionic build android
* What went wrong:
A problem occurred evaluating root project 'android'.
> No installed build tools found. Install the Android build tools version 19.1.0 or higher.

but i had install build tools? How to fix it?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Also, please make sure you have done the stuff shown here: https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html

Thanks for using Ionic!

**Comment by GNORRA** [comment]
I also have the same problem with my project...
SOMEBODY HELP ME PLEASE

**Comment by lkrubner** [comment]
I've the same issue.

**Comment by jfbourne** [comment]
1. Install Android Studio (NOTE: Chose SDK location to your root dir ~/Android)
2. Add the path to your ~/.bash_profile:
`export ANDROID_HOME=/Android/sdk
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH`
3. Quit your terminal and start again

Other things you might need in your bash_profile

`export PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home `

**Comment by marusker** [comment]
I finally found the solution.

1. Please launch android studio. Then go to Preferences -> Appearance & Behavior -> System SEttings -> Android SDK. You will find "Android SDK Location".
 In my PC, it's "/Users/{$user_name}/Library/Android/sdk".

2. Go to "SDK tools" tab and check "show package details". Please make sure Android SDK build tools 19.1.0 or higher is installed.

3. Edit .bash_profile and set ANDROID_HOME as "Android SDK Location" which you find in the Android Studio.  
In my case,
`ANDROID_HOME= /Users/{$user_name}/Library/Android/sdk`
 `export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools `

**Comment by luisameglio** [comment]
@marusker you're the man!

**Comment by nizardinho** [comment]
@marusker come on... you're the best

**Comment by Jerige** [comment]
I had the same issue. Setting a system environment variable ANDROID_HOME to the proper location C:\Users\...\AppData\Local\Android\android-sdk   fixed the issue.
Additional info: In that folder, you should have 'platforms' subfolder and there are downloads for Android SDK, for instance: folder 'android-24'  is for API 24 (Android 7.0). If you are missing API you would like to use for build download additional API with SDK manager.
