### ISSUE TITLE
ClearInput

### ISSUE THREAD

**Issue by syranoMain** [ionic-team/ionic#13127]
Hi Everybody

I'm using Ionic 3 with Angular 4 in my project.

I use <ion-input clearInput></ion-input>
Everything are right but, i want override the behavior of this button, i don't know if it's possible !
it'll be great if i can reset my input without loosing the focus.

do you have any idea ?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

If you believe you have found a bug, I urge you to open an issue with the template fully filled out and with a link to a sample application that demonstrates the issue you are having.

Thanks for using Ionic!
