### ISSUE TITLE
Ionic cordova build android error after ionic update

### ISSUE THREAD

**Issue by priyavaru** [ionic-team/ionic#13125]
ionic info:

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v8.2.1
    npm  : 5.3.0
    OS   : Windows 8.1

Misc:

    backend : legacy

Error : android cordova build android
 ANDROID_HOME=C:\Users\Priya\AppData\Local\Android\sdk
        JAVA_HOME=C:\Program Files\Java\jdk1.8.0_141
        Error: Requirements check failed for JDK 1.8 or greater

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

This is most likely a setup issue with your machine. Even though I am closing this, you can still respond with the answers to these questions. I will get notified.

1. When you say "after Ionic update" are you talking about the CLI (`ionic (Ionic CLI) : 3.13.0`) or the Ionic Framework (`Ionic Framework    : ionic-angular 3.7.1`)? Curious as to which was updated right before this started occuring.
2. What do you get if you type `java -version` at the command prompt?  My output is below:

```
~/Projects/Issues/test-bed-tabs (release): java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

Also, I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by priyavaru** [comment]
Thank you.

Output of command java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

ionic cordova build android command error:
Discovered plugin "cordova-plugin-statusbar" in config.xml. Adding it to the project
        Failed to restore plugin "cordova-plugin-statusbar" from config.xml. You might need to try adding it again.
        Error: Failed to fetch plugin cordova-plugin-statusbar@https://github.com/apache/cordova-plugin-statusbar.git
        via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! code ENOGIT
        npm ERR! No git binary found in $PATH
        npm ERR!
        npm ERR! Failed using git.
        npm ERR! Please check if you have git installed and in your PATH.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\Priya\AppData\Roaming\npm-cache\_logs\2017-10-13T04_56_10_907Z-debug.log
        Error: Failed to run "javac -version", make sure that you have a JDK installed.
        You can get it from: http://www.oracle.com/technetwork/java/javase/downloads.
        Your JAVA_HOME is invalid: C:\Program Files\Java\jdk1.8.0_141

**Comment by Anbarasan-321** [comment]
node:5396) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
ion id: 1): CordovaError: Failed to run “javac -version”, make sure that you ha
e a JDK installed.
ou can get it from: http://www.oracle.com/technetwork/java/javase/downloads.
our JAVA_HOME is invalid: C:\Program Files (x86)\Java\jdk1.8.0_161\bin

I got the above error while build apk file and My Ionic info

cli packages: (C:\Users\dell\AppData\Roaming\npm\node_modules)

@ionic/cli-utils  : 1.19.1
ionic (Ionic CLI) : 3.19.1
global packages:

cordova (Cordova CLI) : not installed
local packages:

@ionic/app-scripts : 3.1.6
Cordova Platforms  : android 7.0.0 browser 4.1.0 ios 4.5.4
Ionic Framework    : ionic-angular 3.9.2
System:

Android SDK Tools : 26.1.1
Node              : v8.9.3
npm               : 5.5.1
OS                : Windows 7
Environment Variables:

ANDROID_HOME : C:\Users\dell\AppData\Local\Android\Sdk
Misc:

backend : pro   
   
Please share solution for this?
