### ISSUE TITLE
bug: Fonts bugs ios ionic 3.11

### ISSUE THREAD

**Issue by msettecasse** [ionic-team/ionic#13129]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>since ionic 3.9.2 when doing "ionic cordova build ios" removes fonts from platform/www/assest/fonts 
Please fix this!
Thanks</span>

<span is-issue-template></span>

**Comment by sfaizanh** [comment]
@msettecasse place your fonts in `src/assets/fonts`

**Comment by msettecasse** [comment]
I’ve never took them away from that folder they are in that folder but when I update ionic to a version above 3.9.1 my fonts get removed when I downgrade the ionic version to 3.9.1 and running ionic Cordova build ios the fonts appear perfectly

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to close this as this is the issue list for the Ionic Framework (ionic-angular) and this appears to be an issue with the Ionic CLI. Please search the issues list of the [Ionic CLI repo](https://github.com/ionic-team/ionic-cli). There are already issues posted relating to this. I believe this one is probably the most applicable to your case: https://github.com/ionic-team/ionic-cli/issues/2675

Thank you for using Ionic
