### ISSUE TITLE
Refresher for iOS should use native overscroll

### ISSUE THREAD

**Issue by danielcrk** [ionic-team/ionic#13121]
**I'm submitting a ...**
[ ] bug report
[x] feature request

Now that WKWebView has become standard, the Refresher component should use native overscroll instead of the javascript based overscroll that it uses now. This wasn't possible before as the old webview didn't fire scroll events on overscroll, but WKWebView provides everything that is needed.

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#319
