### ISSUE TITLE
Virtual Scroll: Item position is not rendered properly after resized window

### ISSUE THREAD

**Issue by longgt** [ionic-team/ionic#13132]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
After resized window, the item position in virtual scroll list is not rendered properly.

**Expected behavior:**
The item position in virtual scroll list is rendered properly.

**Steps to reproduce:**
1. Create a virtual scroll list with 100 items.
2. Display list in maximize window of Chrome
3. Scroll to bottom of the list
4. Click any item to go to item-detail page
5. Resize window
6. Click Back button to come back to list page.
At this time, scroll to top and some part of list will be displayed like the image below.

![virtualscrollbug](https://user-images.githubusercontent.com/27258608/31530109-26b5051e-b008-11e7-846d-7fd5fad0c96e.PNG)

**Related code:**

A sample application via GitHub
https://github.com/longgt/ionic-virtual-scroll-demo

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 3.0.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v8.5.0
    npm  : 5.4.2
    OS   : Windows 7
    Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)
```

**Comment by longgt** [comment]
Follow the description in pull request [#13101](https://github.com/ionic-team/ionic/pull/13101).
I've made some change in list.html like this
```
<ion-list [virtualScroll]="items" approxItemHeight="49px" approxItemWidth="100%" bufferRatio="9">
```
Almost the position of item become properly except the first item disappeared.
![virtualscroll_firstitemdisappeared](https://user-images.githubusercontent.com/27258608/31533501-cbc0f2f2-b01c-11e7-8f01-d961a7d1830d.PNG)

**Comment by masimplo** [comment]
@longgt changing the bufferRatio will not really help you in this case (will render more items so might reduce the problem but by side effect).

I managed to reproduce you issue. What happens is that when you push a different page, virtual scroll is still running and specifically the part that listens for window resize events. When you resize the window in the second screen, that event is triggered in virtual scroll and tries to re-calculate the virtual scroll component. Unfortunately all the numbers that it takes into account then are wrong, as it is not visible.

A workaround might be to stop the component of running the resize method while it is not displayed. Apparently you can determine if an element is displayed in the viewport by checking its offsetParent as described in [this SO question](https://stackoverflow.com/questions/19669786/check-if-element-is-visible-in-dom)

Adding this check in resize seems to do the job:
```
    // check if component is rendered in the dom currently
    if (this._elementRef.nativeElement.offsetParent === null) {
      return;
    }
```

BUT 1st I don't know how well this is supported across browsers (tried chrome, safari on desktop and my android device)
2nd we should be able to trigger resize once again when the component becomes visible again

If anyone has any ideas on how this could be solved in the current codebase, would be happy to discuss and do a PR.

**Comment by manucorporat** [comment]
@masimplo thanks a lot for the help! currently master is frozen, but I will look at it just after next version is released.

**Comment by manucorporat** [comment]
Fixed!
