### ISSUE TITLE
feat(deafultHistory): add segment support

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#13137]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
in `defaultHistory` you have to use a page name

**Expected behavior:**
being able to use a segment, like the following:

```ts
  segment: 'businesses/:businessKey/specials',
  defaultHistory: ['businesses/:businessKey']
```

because for example in this case, I need parameters to go back,

or maybe make it a method of `IonicPage`, like a `defaultGoBack` method, that if exists you know there is history, and if you press on the back button and there are no pages in the stack, goes there

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#320

**Comment by AmitMY** [comment]
The internal feature requests lists, where good ideas die :)

**Comment by patrickmcd** [comment]
Dup: https://github.com/ionic-team/ionic/issues/11377

**Comment by AmitMY** [comment]
thanks @patrickmcd, definitely a dup
