### ISSUE TITLE
bug: Camera features not working in android nougat

### ISSUE THREAD

**Issue by Shobanabohs100** [ionic-team/ionic#13133]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>7.0</span>  <span ionic-webview>webview</span>

<span ionic-description>camera is not accessible in nougat</span>

<span is-issue-template></span>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

I also suggest checking the issues list of Ionic Native and the camera plugin itself.

Thanks for using Ionic!
