### ISSUE TITLE
Ionic start new-project

### ISSUE THREAD

**Issue by steavengong** [ionic-team/ionic#13139]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x] suggest

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Suggest Description:**
 when i use “Ionic start new-project”
 this cli will download
```
? What starter would you like to use: tabs
[INFO] Fetching app base
       (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
√ Downloading - done!
[INFO] Fetching starter template tabs
       (https://github.com/ionic-team/ionic2-starter-tabs/archive/master.tar.gz)
```
These resources can save in my computer cache ? when i start new project,it use cache resources, no cache it will download

if i have no network  ionic start new-project don`t work, it also use cache resources

**Comment by kensodemann** [comment]
Thank you for your suggestion. I am going to close this as it is not related to the Ionic Framework but is related to the Ionic CLI. I suggest creating a feature request in the [Ionic CLI Repo](https://github.com/ionic-team/ionic-cli).

Thank you for using Ionic!
