### ISSUE TITLE
Issue when released app in production mode

### ISSUE THREAD

**Issue by Gamerakki** [ionic-team/ionic#13131]
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
When app is release in production mode.. the ui get distorted. The ion-content sometimes randomly get overlap in ion-header. Some components doesnt get recognized . Keyboard start to behave in weird way,  it doesnt allow scroll when open  header get pushed up. 

**Expected behavior:**
Proper ui. keyboard working properly

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to close this as it is not an issue with the Ionic Framework, but is likely an issue with `@ionic/app-scripts` which is what builds the application.

I believe `3.0.0` has a couple of bugs building in production mode.

Please try the following nightly build:

```
npm i @ionic/app-scripts@3.0.0-201710091726
```
if that does not resolve your issue, please log on issue in the [app scripts repo](https://github.com/ionic-team/ionic-app-scripts)

Thank you for using Ionic
