### ISSUE TITLE
Vertical Grid using align-items-center does not work

### ISSUE THREAD

**Issue by MartinMuzatko** [ionic-team/ionic#13135]
![image](https://user-images.githubusercontent.com/2950505/31535702-50932386-affc-11e7-8500-9cb24331aaa2.png)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.12.0**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Documentation says, that by applying `align-items-center` the rows will turn into columns.
See https://ionicframework.com/docs/api/components/grid/Grid/#vertical-alignment
There is no test case connected to the code there.
It looks like this is not the case.

**Expected behavior:**
I would expect, that the columns form rows, as described in the docs.

**Related code:**

```html
<ion-content class="padding" scroll="false">
    <ion-row align-items-center>
        <ion-col>
            A
        </ion-col>
        <ion-col>
            A
        </ion-col>
    </ion-row>
</ion-content>
```

Sample app:
https://stackblitz.com/edit/ionic-tvcqbz?file=app%2Fapp.html

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

System:

    Node : v8.6.0
    npm  : 5.3.0 
    OS   : Linux 4.4

Misc:

    backend : pro
```

**Comment by JasonAsmk** [comment]
Align-items-center says to the row that every child column will have to go in the middle of the row's height unless there's another css blocking that. In your sample app, the row doesn't take the full height of the container(which is ion-content) so you don't see the effect. If you set
`ion-row{
       height: 100%;
}`
You'll see the columns aligning as you expected. Try inspecting the ion-row in your example and set its css to have height:100% .

**Comment by MartinMuzatko** [comment]
Isn't there an attribute selector that does that for me? [Since there are already ones for cols and rows](https://ionicframework.com/docs/api/components/grid/Row/), I would expect that there is an attribute to switch layouts. I'd hate writing the same CSS over and over again for every page that needs the same layout. A grid system should be able to handle these cases without custom css required.

[Flexproperties ](https://www.npmjs.com/package/flexproperties)is a good example of handling this. Which takes care of any of these scenarios: https://codepen.io/MartinMuzatko/full/EZeExR

I will file an issue in the documentation repo to show what exactly is needed for a vertical grid, since this lacks any demos.

**Comment by JasonAsmk** [comment]
Yeah just looked into the source code and there doesn't seem to be anything like that. My guess is that these directives are just shorthands or wrappers if you will for the css grid properties and because `display: grid` takes the height of its children by default Ionic keeps it that way.

Indeed you could file a feature request and maybe it will be implemented in some future version. But in any case, adding a css rule manually would solve your problem for now.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Please feel free to continue the conversation here is you wish. I am just going to close the issue as there is no code change required at this time.

Thank you for using Ionic
