### ISSUE TITLE
when  add custom plugins by Plugman ,encounter a problem

### ISSUE THREAD

**Issue by xingag** [ionic-team/ionic#13136]
hello ,i use ionic3  and when i add custom plugins by plugman ,it cause problem blow.

![qq 20171013172314](https://user-images.githubusercontent.com/5069818/31539589-9dabde76-b03b-11e7-8351-48a35e1b3616.png)

**Comment by xingag** [comment]
![qq 20171013173004](https://user-images.githubusercontent.com/5069818/31539771-3d8f1e6c-b03c-11e7-9900-7e06b5c067d5.png)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
