### ISSUE TITLE
bug: ion-select component of Ionic 3 not working in IOS

### ISSUE THREAD

**Issue by yogeshkrishnani** [ionic-team/ionic#13134]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>We have developed one application using Ionic 3. We have used ion-select component at multiple places. In android & IOS version > 10, everything is working fine as expected.

But In IOS 9, ion-select component breaks. It shows blank options when tapping on ion-select.

```
<ion-item>
   <ion-label>Gender</ion-label>
   <ion-select>
     <ion-option value="f">Female</ion-option>
     <ion-option value="m">Male</ion-option>
   </ion-select>
</ion-item>
```

Environment Details:

Specific IOS version in which issue is reproducible: 9.3.5

**global packages:**

ionic/cli-utils : 1.5.0
Cordova CLI      : 6.5.0
Ionic CLI        : 3.5.0

**local packages:**

ionic/app-scripts              : 1.3.7
ionic/cli-plugin-cordova       : 1.4.1
ionic/cli-plugin-ionic-angular : 1.3.2
Cordova Platforms               : android 6.1.2 ios 4.2.1
Ionic Framework                 : ionic-angular 3.7.1-201710060319

**System:**

Node       : v7.8.0
OS         : OS X El Capitan
Xcode      : Xcode 8.2.1 Build version 8C1002
ios-deploy : 1.9.1
ios-sim    : 5.0.13
npm        : 4.2.0</span>

<span is-issue-template></span>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I tried applying your sample code to a freshly created blank project and it worked just fine, including when doing a `--prod` build and running it on an iOS 9.x device in a simulator (I don't have an actual device running older versions).

Then I noticed that your versions of stuff are all over the board. Probably the biggest issue is that you are using a nightly `3.7.1` release with app-scripts `1.3.7` when the [changelog](https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md) states for `3.7.0` (and above) that you should be at app-scripts `3.0.0`.

The cordova and ionic CLIs are also out of date as is cordova-ios in your project. I doubt those are contributing to your issue, but they may be.

For reference, here is what I have on the machine I used for testing:

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.5.2
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2 
    ios-sim           : 6.1.2 
    Node              : v8.7.0
    npm               : 5.5.1 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

Misc:

    backend : pro
```

I am going to close this as something that cannot be duplicated.

If, after upgrading at least `@ionic/app-scripts` to `3.0.0` you still have the issue, please provide a GitHub repo with code that duplicates the problem and I will have another look.

Thank you for using Ionic

**Comment by Anujmoglix** [comment]
I am also facing issue. I am not able to select drop down value in iOS . My system info is as following 

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.9.1
    npm        : 5.2.0 
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
