### ISSUE TITLE
iOS build error with Xcode 9

### ISSUE THREAD

**Issue by jordanpurinton** [ionic-team/ionic#13138]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

I've tried every possible solution I could find for this cryptic error and no luck.

In my Ionic project, I've added the platform, but when I go to run the project in the simulator through Xcode, I get this error:

```error: cannot parse the debug map for "/Users/XXX/Library/Developer/Xcode/DerivedData/ProjectName-aedfralrxnetyceopmcioxkdhsxh/Build/Products/Debug-iphonesimulator/ProjectName.app/ProjectName": No such file or directory```

Not sure where else to go, so any help is appreciated!

Ionic info:
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.5.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v6.9.1
    npm        : 5.5.1
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
