### ISSUE TITLE
Slides with autoplay and loop props have different behaviour while sliding back to first slide ONLY in --prod build (Android)

### ISSUE THREAD

**Issue by yurik94** [ionic-team/ionic#13148]
**Ionic version:**
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request

**Current behavior:**
When the slider animates from the last to the first slide, **ONLY in --prod build**, it slides reversally from right lo left, while in **NON --prod** build it simply continues sliding from left to right (wanted behaviour)

**Expected behavior:**
Slides animations should have the same behaviour in --prod and dev builds.

**Steps to reproduce:**
`ionic start myApp blank`
`ionic cordova platform add android`

add following code to the home.html
```
<ion-slides autoplay="4000" loop="true">
   <ion-slide style="background-image: url(http://lorempixel.com/output/fashion-q-c-640-480-4.jpg)">
   </ion-slide>
   <ion-slide style="background-image: url(http://lorempixel.com/output/technics-q-c-640-480-1.jpg)">
   </ion-slide>
</ion-slides>
```
`ionic cordova run android`
Slides will roll always from right to left

Now:
`ionic cordova run android --prod`
While sliding from the last to the first slide, it will roll from left to right giving even an ugly visual effect

**Ionic info:**:
```
cli packages: (C:\Users\Kevin\AppData\Roaming\npm\node_modules)
    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:
    cordova (Cordova CLI) : 7.0.1

local packages:
    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.1

System:
    Android SDK Tools : 25.2.5
    Node              : v7.9.0
    npm               : 4.6.1
    OS                : Windows 10

Misc:
    backend : legacy
```

After a few hours of research I haven't found anything, should I open this issue also in ionic-app-scripts Repo?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I was able to duplicate the issue.

Thank you for using Ionic

**Comment by yurik94** [comment]
Really thanks, I haven't tested it on iOS yet but I will do in the next days.

**Comment by kensodemann** [comment]
Tried it on iOS and it exhibits the same issue. Clearly something goes wonky when building with `--prod`

**Comment by yurik94** [comment]
Any news?

**Comment by ArtKuz** [comment]
@kensodemann do you have news?

**Comment by kensodemann** [comment]
All development effort at this time is focused on getting Ionic v4 released. This will need to be retested once v4 is released.

**Comment by yurik94** [comment]
@kensodemann :+1:
