### ISSUE TITLE
CLI item selection doesn't work property using Git Bash

### ISSUE THREAD

**Issue by ciaran036** [ionic-team/ionic#13147]
**Ionic version:** 
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
- [ ] **2.x**
- [x] **3.x**
- [ ] **4.x**

**I'm submitting a ...**  (check one with "x")

- [x] bug report
- [ ] feature request

**Current behavior:**
When using Git Bash on Windows, when the Ionic CLI prompts for the user to make a selection, Ionic will choose the wrong item from the one I actually selected. 

![gitbash](https://user-images.githubusercontent.com/828400/31576764-825627b2-b0f9-11e7-8256-6f8e0798f9c9.gif)

**Expected behavior:**
When I move the cursor to a particular item, Ionic should actually perform the action for the correct selection. 

**Steps to reproduce:**
1) Open a Git Bash terminal on Windows 
2) Type any command which prompts for a selection, e.g. "ionic start myApp"
3) By using the keyboard to move the cursor to select an item, when the Enter key is pressed, Ionic will take the wrong option to the one I actually selected. 

I've found that if I use Powershell I can select items successfully (although I'd prefer to use Git Bash so I can use Git commands easily). 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\Ciaran\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

System:

    Node : v8.6.0
    npm  : 5.3.0
    OS   : Windows 10

Misc:

    backend : pro

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This does not appear to be an issue with the Ionic Framework but with the Ionic CLI. I will move it to the CLI repo. Please track the new issue over there. 

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2807
