### ISSUE TITLE
Ionic app not starting in IOs 9.3.5

### ISSUE THREAD

**Issue by gregor-srdic** [ionic-team/ionic#13149]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
I am trying to run an Ionic app on IOs 9.3.5 (simulator). The app is stuck at splashscreen and XCode console displays no significant messages, but in safari developer console I can see the following:
```
SyntaxError: Unexpected token '('
[Error] ReferenceError: Can't find variable: webpackJsonp
[Error] Failed to load resource: unsupported URL (gap://ready)
```

**Expected behavior:**
App to work normally.

**Other information:**
App works normally on simulator with IOs versions 10 and 11.
Does Safari 9 not support arrow functions? However target "es5" in typescript config should take care of that right?

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0
global packages:
    cordova (Cordova CLI) : 7.1.0 
local packages:
    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.5.1
    Ionic Framework    : ionic-angular 3.7.1
System:
    ios-deploy : 1.9.2 
    Node       : v6.11.2
    npm        : 4.6.1 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235

**Comment by gregor-srdic** [comment]
closer inspection shows that this might be due to default value initialisation in the get method of the Config class - is that in any way configurable?
![2017-10-15_15-34-11](https://user-images.githubusercontent.com/3057225/31585214-8847a8c4-b1be-11e7-8c5a-7af83965e4da.png)

**Comment by Gamerakki** [comment]
hi ,
@gregor-srdic can u provide a code or a create a small project on git and provide the link so i can see and help you out. the app works in 9.3.5, since i am currently working a project provide support from ios 9.0 and above. Also tell how are u running the project via command line or xcode . :D

**Comment by gregor-srdic** [comment]
I'll try with a blank Ionic project and let you know how it goes. I am building with "ionic cordova build ios" in terminal and then opening and running the project in xcode.
what versions are you using?
mine are:
ionic cli: 3.13.0
ionic-angular: 3.7.1
@ionic/app-scripts: 3.0.0
cordova: 7.1.0
cordova-ios: 4.5.2

**Comment by gregor-srdic** [comment]
The blank project (with the same package versions) did not produce an error. Further research indicates that the source of the problem in this line
https://github.com/ionic-team/ionic/blob/74c5871ac451461d3abc93bf927dbacaa21a392a/src/config/config.ts#L163
what is weird is that in project a (has quite a few plugins, generated with older ionic version, updated to newest - removed node_modules and package-lock) keeps this feedbackValue = null in vendor.js, while project b (empty newly generated ionic project) does not. 
Any idea what could be the cause of this? Checked tsconfig as well, they are identical.

**Comment by kensodemann** [comment]
> what is weird is that in project a (has quite a few plugins, generated with older ionic version, updated to newest - removed node_modules and package-lock) keeps this feedbackValue = null in vendor.js, while project b (empty newly generated ionic project) does not

I am not really fully grokking what you are saying there, sorry. Perhaps sharing what you see in the code?

**Comment by gregor-srdic** [comment]
What I meant to say was :) :
- the project that has the problem has been created with previous versions of app-scripts, ionic-angular, etc. (about 2 months old) and later updated to the newest (when I updated them, I removed the node_modules folder and run a clean npm install)
- it also uses quite a few plugins and ionic-native packages, but this does not seem to be the cause of the problem - I added them all to the empty project, and it still works
- what I am currently noticing about the code and is unexplained to me, is that after "ionic cordova build ios" the **vendor.js** in **/platforms/ios/www/build** is that from some point the code seems to be not translated in es5 or something https://gist.github.com/gregor-srdic/64e4b1e19dc911aa25639b02ed744f9f#file-vendor-js-L20588 . Any idea, what could cause this?

**Comment by gregor-srdic** [comment]
nevermind ... after days of struggle, it was just due to the one wrong import in one of my pages:
**import { Slides } from 'ionic-angular/es2015';**
which should obviously be 
**import { Slides } from 'ionic-angular';**
thanks for your effort!
