### ISSUE TITLE
Missing `[text-wrap] .label-ios` styles

### ISSUE THREAD

**Issue by rafbgarcia** [ionic-team/ionic#13157]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Please check [these styles for `[text-wrap] .label-md`](https://github.com/ionic-team/ionic/blob/master/src/components/label/label.md.scss#L36-L39)

They do not exist for `.label-ios`, hence my font-size on iOS is different than what I expect.

**Expected behavior:**
I expected a custom `$font-size-base` to change font-size on iOS.

**Related code:**
```html
<ion-item text-wrap *ngFor="let review of reviews">
  <ion-icon *ngIf="!review.user.hasAvatar" item-start name="md-contact"></ion-icon>
  <ion-avatar *ngIf="review.user.hasAvatar" item-start>
    <img [src]="review.user.thumb">
  </ion-avatar>
  <div class="flex-row">
    <div class="w-75">
      <strong>{{review.user.name}}</strong>
      <p>{{review.date}}</p>
      <p>{{review.user.comments}}</p>
    </div>
    <nf-review-avg [number]="review.average"></nf-review-avg>
  </div>
  <div>{{review.comments}}</div>
  <div>{{review.restaurantResponse}}</div>
</ion-item>
```

#### iOS (incorrect) / Android (correct)
<img src="https://user-images.githubusercontent.com/1904314/31609532-5ebf903a-b253-11e7-946f-5b78e6da61b9.png" width="49%"> <img src="https://user-images.githubusercontent.com/1904314/31609543-67ad4372-b253-11e7-8cf3-cdf2821d55e5.png" width="49%">

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I marked this to be discussed at our next milestone meeting to see if we can get this in an upcoming v3.x release.

Thank you for using Ionic

**Comment by rafbgarcia** [comment]
Thank you, @kensodemann
