### ISSUE TITLE
Lazy loading: modal from lazy loading page which loaded from split pane failed to load script in path location strategy 

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic#13156]
_From @longgt on October 16, 2017 7:6_

#### Short description of the problem:
modal from lazy loading page which loaded from split pane failed to load script in **path** location strategy.

#### What behavior are you expecting?
It should work as **hash** location strategy.

**Steps to reproduce:**
1. Clone repo
2. Start server, navigate to **List** page
3. Click any item in list, wait about 10 seconds and error handling screen will be displayed.

A sample application via Github
https://github.com/longgt/ionic-sidemenu-demo

**Which @ionic/app-scripts version are you using?**

```
cli packages: 

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 3.0.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v8.5.0
    npm  : 5.4.2
    OS   : Windows 7
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

_Copied from original issue: ionic-team/ionic-app-scripts#1281_

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This seems like it is a bug in the Ionic Framework and not a bug in the Ionic App Scripts. I will move the issue to the proper repo for that.

Thank you for using Ionic

**Comment by kensodemann** [comment]
Closing as this is a duplicate of #13154

**Comment by longgt** [comment]
The real problem here is with my repo, modal loading script with url like /split pane segment/lazy script.js instead of /lazy script.js
