### ISSUE TITLE
ion-item: click event is not triggered in menu of split-pane

### ISSUE THREAD

**Issue by longgt** [ionic-team/ionic#13154]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
**Click** event is not triggered in menu of split pane. **tap** will work.

**Expected behavior:**
**Click** event is triggered as **tap**.

**Steps to reproduce:**

1. Clone the following sample app below
2. Start server, navigate to list page
3. Click menu icon to show menu
4. Click **Home** item
**Home** page will not be displayed, **List** page remained.
5. Change (click) in side-menu.html to (tap)
Click **Home** item again, **Home** page will be displayed properly.

**Related code:**

A sample application via GitHub

https://github.com/longgt/ionic-sidemenu-demo

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: 

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 3.0.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v8.5.0
    npm  : 5.4.2
    OS   : Windows 7
    Chrome: Version 61.0.3163.100 (Official Build) (64-bit)
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

I have also take our side-menu app and made a lazy loaded version of it so you can use that as a model. See here: https://github.com/kensodemann/test-side-menu-lazy

Thanks for using Ionic!

**Comment by longgt** [comment]
Thank you for quick answer. 
This is a bug I realized when try to implement side menu on each page instead of root app. 

I used to move menu to root page and click or tap worked correctly. But with my repo only tap worked. Until now, in item I could use click or tap without different.
