### ISSUE TITLE
Back button not showing tabs container

### ISSUE THREAD

**Issue by OmarKhanfer** [ionic-team/ionic#13150]
Hello

I have home page has a list of item, when I select Item I am going to other page has tabs, the issue the back button is not showing up. the structure as the following, in the calls or events page the back button is not showing, please help

Home
|
| - Tab Container
    |----- Events
    |----- Calls

Regards

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

Based on your tree that you have, it does not sound like you should have a back button, but I may not be understanding your structure entirely, so using our tabs starter and then mimicking your structure as closely as possible with fake pages will probably be adequate.

Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
