### ISSUE TITLE
Changing icons dynamically from a list using index or something in ionic 2 

### ISSUE THREAD

**Issue by satish22** [ionic-team/ionic#13158]
On click of the toggleIcon(idx) how can i change the just the clicked icon only.

![123](https://user-images.githubusercontent.com/13430701/31611518-01a14226-b29a-11e7-9152-7d9ce72befbc.PNG)

**Comment by antoine92190** [comment]
You should ask this kind of question in the ionic forum: https://forum.ionicframework.com
But here is something that should help you out:

In your html file:
`<button ion-button clear item-end (click)="toggleIcon(post)">
      <ion-icon [name]="post.icon || initialButtonIcon"></ion-icon>
  </button>`

In your ts file:
`toggleIcon(post) {
      post.icon = "newIconName"
  }`

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
