### ISSUE TITLE
404 Not Found: @ionic/cli-utils@1.13.1

### ISSUE THREAD

**Issue by fera0013** [ionic-team/ionic#13167]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
I tried to install ionic using 

`npm install cordova ionic -g`

and got

> 404 Not Found: @ionic/cli-utils@1.13.1

[2017-10-17T12_47_17_618Z-debug.log](https://github.com/ionic-team/ionic/files/1391043/2017-10-17T12_47_17_618Z-debug.log)

here is the complete debug.log:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'install',
> 1 verbose cli   'ionic',
> 1 verbose cli   '-g' ]
> 2 info using npm@5.3.0
> 3 info using node@v8.2.1
> 4 verbose npm-session b70d7bf956f28a0b
> 5 silly install loadCurrentTree
> 6 silly install readGlobalPackageData
> 7 http fetch GET 200 https://artifactory.siemens.net/artifactory/api/npm/npm-remote/ionic 614ms
> 8 silly pacote tag manifest for ionic@latest fetched in 979ms
> 9 silly install loadIdealTree
> 10 silly install cloneCurrentTreeToIdealTree
> 11 silly install loadShrinkwrap
> 12 silly install loadAllDepsIntoIdealTree
> 13 silly resolveWithNewModule ionic@3.13.1 checking installable status
> 14 http fetch GET 200 https://artifactory.siemens.net/artifactory/api/npm/npm-remote/os-name 179ms
> 15 http fetch GET 200 https://artifactory.siemens.net/artifactory/api/npm/npm-remote/opn 185ms
> 16 http fetch GET 200 https://artifactory.siemens.net/artifactory/api/npm/npm-remote/tslib 181ms
> 17 http fetch GET 200 https://artifactory.siemens.net/artifactory/api/npm/npm-remote/chalk 198ms
> 18 http fetch GET 200 https://artifactory.siemens.net/artifactory/api/npm/npm-remote/rimraf 194ms
> 19 http fetch GET 200 https://artifactory.siemens.net/artifactory/api/npm/npm-remote/semver 197ms
> 20 silly pacote range manifest for os-name@^2.0.1 fetched in 204ms
> 21 silly resolveWithNewModule os-name@2.0.1 checking installable status
> 22 silly pacote range manifest for opn@^5.1.0 fetched in 205ms
> 23 silly resolveWithNewModule opn@5.1.0 checking installable status
> 24 silly pacote range manifest for tslib@^1.8.0 fetched in 200ms
> 25 silly resolveWithNewModule tslib@1.8.0 checking installable status
> 26 silly pacote range manifest for chalk@^2.0.0 fetched in 219ms
> 27 silly resolveWithNewModule chalk@2.1.0 checking installable status
> 28 silly pacote range manifest for rimraf@^2.6.2 fetched in 213ms
> 29 silly resolveWithNewModule rimraf@2.6.2 checking installable status
> 30 silly pacote range manifest for semver@^5.3.0 fetched in 215ms
> 31 silly resolveWithNewModule semver@5.4.1 checking installable status
> 32 http fetch GET 200 https://artifactory.siemens.net/artifactory/api/npm/npm-remote/@ionic%2fdiscover 756ms
> 33 silly pacote range manifest for @ionic/discover@^0.3.3 fetched in 779ms
> 34 silly resolveWithNewModule @ionic/discover@0.3.3 checking installable status
> 35 http fetch GET 200 https://artifactory.siemens.net/artifactory/api/npm/npm-remote/@ionic%2fcli-utils 889ms
> 36 http fetch GET 404 https://artifactory.siemens.net:443/artifactory/api/npm/npm-remote/@ionic/cli-utils/-/cli-utils-1.13.1.tgz 14ms
> 37 silly fetchPackageMetaData error for @ionic/cli-utils@1.13.1 404 Not Found: @ionic/cli-utils@1.13.1
> 38 verbose stack Error: 404 Not Found: @ionic/cli-utils@1.13.1
> 38 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:41:19)
> 38 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
> 38 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
> 38 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
> 38 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
> 38 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
> 38 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
> 38 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
> 38 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
> 38 verbose stack     at runCallback (timers.js:781:20)
> 38 verbose stack     at tryOnImmediate (timers.js:743:5)
> 38 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
> 39 verbose cwd D:\FullStackWebDevelopment
> 40 verbose Windows_NT 6.1.7601
> 41 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ionic" "-g"
> 42 verbose node v8.2.1
> 43 verbose npm  v5.3.0
> 44 error code E404
> 45 error 404 Not Found: @ionic/cli-utils@1.13.1
> 46 verbose exit [ 1, true ]

**Expected behavior:**

Succesful installation.

**Steps to reproduce:**

Enter 

`npm install cordova ionic -g`

in a proxy / artifactory environment.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Based on what I see above, this is most likely an issue with your network or environment.

Thanks for using Ionic!
