### ISSUE TITLE
Footer broken on 3.7 with status bar

### ISSUE THREAD

**Issue by hugodes** [ionic-team/ionic#13160]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The footer is missing margin / padding when statusBar.overlaysWebView is set to false
![ios ko](https://user-images.githubusercontent.com/1223591/31623945-602d498c-b2a1-11e7-85bc-4bae29dac928.png)

**Expected behavior:**

The footer should display correctly
![ios ok](https://user-images.githubusercontent.com/1223591/31623948-6520bca8-b2a1-11e7-9d40-1df39b6249f0.png)

**Steps to reproduce:**

**Related code:**

https://github.com/hugodes/ionic-statusBar-breaking

**Other information:**

This is a follow up to #13054 which was closed without being resolved. (I asked the team to reopen it, with no luck

The repo I linked is using nightly ionic-angular nightly build with https://github.com/apache/cordova-plugin-statusbar

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
[INFO] Not automatically updating your CLI.

cli packages: (/Users/hugodes/.nvm/versions/node/v8.6.0/lib/node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2 
    Node       : v8.6.0
    npm        : 5.3.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy
```

**Comment by harpster604** [comment]
I believe I'm having a related issue as well. App looks fine on iOS 10 on iPhone 6 Plus (simulator) but on iOS 11 iPhone 6 Plus (device) the footer is cut off.

Using ionic 3.7.1

**iOS 10**
![image](https://user-images.githubusercontent.com/671838/31625641-99a3ecb6-b25b-11e7-85c6-ab0a22bba49e.png)

**iOS 11**
![image](https://user-images.githubusercontent.com/671838/31625651-a1b991e4-b25b-11e7-85cc-c63975fb2a01.png)

**Comment by hugodes** [comment]
Closing this as the original issue has been re-opened

**Comment by hugodes** [comment]
@harpster604 this seems to have been fixe here: #13054
