### ISSUE TITLE
feat: wanted to generate dynamic ion-option

### ISSUE THREAD

**Issue by prvn1992** [ionic-team/ionic#13161]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Wanted to generate <ion-option> dynamically</span>

<span is-issue-template></span>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Can you please expand on exactly what you are looking for with this feature? I just tried a simple example with `3.7.1` and it seemed to work just fine dynamically adding options to the list.

Thank you for using Ionic

**Comment by kensodemann** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue I am closing it.
