### ISSUE TITLE
ViewController component properties differ in --prod build compared to a debug build

### ISSUE THREAD

**Issue by cnsimbe** [ionic-team/ionic#13162]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When ionic app is build is --prod, some ionViewController.component properties differ
**Expected behavior:**

They should n't differ
**Steps to reproduce:**

Build a simple app with a Nav as the root component
Push a page, ie
this.navCtlr.push('Page1').then(viewCtrl=> {

let consistent = viewCtrl.component.name=='Page1'
consistent will be false in a build with --prod and true in a build without --prod
})

**Related code:**

```
this.navCtlr.push('Page1').then(viewCtrl=> {

let consistent = viewCtrl.component.name=='Page1'
//consistent will be false in a build with --prod and true in a build without --prod
})
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by saschwarz** [comment]
This may be due to how uglify processes those names in prod mode: https://github.com/ionic-team/ionic/issues/11920

**Comment by kensodemann** [comment]
Good call @saschwarz and thank-you for the link to the other issue. FWIW @cnsimbe, once I got your sample app, I was going to use it to verify just what @saschwarz pointed to in order to verify that was the issue, but if you want to follow the link he provided and verify that on your own that may save you some time.

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
