### ISSUE TITLE
您好，请问官方有推出中文文档的计划吗？

### ISSUE THREAD

**Issue by BengBu-YueZhang** [ionic-team/ionic#13163]
您好，请问官方有推出中文文档的计划吗？

**Comment by aggarwalankush** [comment]
quick google translate 😅 

> Hello, may I ask the official plan to launch a Chinese document?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

So far as I know, there is no official plan to launch a documentation in any language other than English. If someone in the greater community were to undertake a project of properly translating our documentation into Chineses (or any other language) and keeping it up to date as we make releases, we would certainly not be opposed to it. We may also be able to offer some level of help and support as the documentation is mostly generated from the code, and could probably be auto-generated and machine translated before clean-up by someone who speaks the target language.

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. So I am going to close this issue. I urge that you start a discussion about this on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thank you for using Ionic
