### ISSUE TITLE
Navigation between pages that each have ion-tabs element fails

### ISSUE THREAD

**Issue by JarmoKukkola** [ionic-team/ionic#13165]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

Depending on the type of navigation used (each of the 10 buttons in demo project implement one way of navigation):

* Multiple Tabs elements are shown.
* Navigation to Tabs2Page succeeds but Tabs1Tab1Page is shown instead of Tabs2Tab1Page.

**Expected behavior:**

The example project (https://github.com/JarmoKukkola/ionic-tabs-problem) demonstrates navigation between two pages (Tabs1Page and Tabs2Page) that each have a ion-tabs element. 10 different ways to navigate are demonstrated.

* Clicking a blue button in Tabs1Tab1Page should navigate to Tabs2Page with Tabs2Tab1Page and Tabs2Tab2Page tabs.
* Clicking a blue button in Tabs2Tab1Page should navigate to Tabs1Page with Tabs1Tab1Page and Tabs1Tab2Page tabs.

**Steps to reproduce:**
Create two pages, which each have a ion-tabs elements and navigate from the first page to the second one or vice versa.

**Related code:**

https://github.com/JarmoKukkola/ionic-tabs-problem

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am not sure I fully grok the navigation in your example, but it _appears_ to be working for me. I click on the first button in Tabs1Tab1, and get a second set of tabs within that page with the title Tabs2Tab1, which I _think_ is what you looking to have happen. Right?

Anyhow, based on your description, I think this is a duplicate of #12625. Can you please have a look at that issue and verify?

Also, can you please try the [nightly referenced](https://github.com/ionic-team/ionic/issues/12625#issuecomment-334650345) there and see if that fixes your issue as I either cannot duplicate the issue using your sample or just don't understand that I should be looking for fully.

```
npm install ionic-angular@3.7.1-201710060319
```

Thank you for using Ionic

**Comment by JarmoKukkola** [comment]
Thank you very much for the reply.

I was using 3.7.1 during the test. The nightly seems to have fixed the problem.

Issue can be closed. Keep up the good work.

**Comment by jdrus** [comment]
Hi guys,

I have exactly the same issues, but my App use ionic-angular:"3.8.0".
Does I need to downgrade?
