### ISSUE TITLE
Android 4.4.2 doesn't support URL object

### ISSUE THREAD

**Issue by niconaso** [ionic-team/ionic#13179]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Android 4.4.2 doesn't support the URL object (https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) to parse an URL.

**Expected behavior:**

**Steps to reproduce:**
1. let url = new URL("http://www.google.com")
2. url.host <-- undefined

**Other information:**
I fixed it just installing this polyfill by npm: https://github.com/lifaon74/url-polyfill

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/home/nicolas/desarrollo/workspace/cabal-mobile/node_modules)

    @ionic/cli-plugin-proxy : 1.4.13
    @ionic/cli-utils        : 1.13.1
    ionic (Ionic CLI)       : 3.13.1

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0 ios 4.5.2
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 25.2.5
    Node              : v6.9.5
    npm               : 3.10.10 
    OS                : Linux 4.10

Misc:

    backend : legacy

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is not really a bug with the Ionic Framework, and it looks like you have solved your issue, so I am going to close this issue.

Thank you for using Ionic
