### ISSUE TITLE
Error on Android device version 4.4.2

### ISSUE THREAD

**Issue by ndnparis** [ionic-team/ionic#13176]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Got the following error when run the app on Android Device Samsung S4** 

Ionic Native: deviceready event fired after 15027 ms vendor.js:114769
accepted session main.js:1079
you are authenticated! main.js:853
ERROR 
Error {rejection: TypeError, promise: t, zone: r, task: e}
 vendor.js:1377
defaultErrorLogger vendor.js:1377
ErrorHandler.handleError vendor.js:1437
IonicErrorHandler.handleError vendor.js:113943
onError.subscribe.next vendor.js:4860
schedulerFn vendor.js:3992
SafeSubscriber.__tryOrUnsub vendor.js:32731
SafeSubscriber.next vendor.js:32678
Subscriber._next vendor.js:32618
Subscriber.next vendor.js:32582
Subject.next vendor.js:37568
EventEmitter.emit vendor.js:3978
(anonymous function) vendor.js:4269
t.invoke polyfills.js:3
r.run polyfills.js:3
NgZone.runOutsideAngular vendor.js:4201
zone._inner.zone._inner.fork.onHandleError vendor.js:4269
t.handleError polyfills.js:3
r.runGuarded polyfills.js:3
(anonymous function) polyfills.js:3
n.microtaskDrainDone polyfills.js:3
o polyfills.js:3
e.invokeTask polyfills.js:3
i.isUsingGlobalCallback.invoke polyfills.js:3
n

**Expected behavior:**

**Steps to reproduce:**

**Get started with the following Ionic AWS Starter** 

$ ionic start myApp aws
$ ionic cordova platform add android
$ ionic cordova build android

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
cli packages: (/home/develop/.npm-packages/lib/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v8.7.0
    npm  : 5.4.2 
    OS   : Linux 3.10

Misc:

    backend : pro

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Does this only happen when using the AWS starter? Or does it also happen when using other starters (blank, tabs, etc)? If only with the AWS starter, I will move this issue over to its repo.

Thank you for using Ionic

**Comment by ndnparis** [comment]
Hello,
Thanks a lot for your quick response.
Just when using the AWS starter. Please move this issue to its repo.
Best regards

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic2-starter-aws#43
