### ISSUE TITLE
Content hidden after device rotation, repro on default starter apps

### ISSUE THREAD

**Issue by gammelby** [ionic-team/ionic#13172]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**

If navigating back after rotating device back and forth, topmost content on the previous page is hidden under the navigation bar. Problem evident on both iOS and Android.

**Expected behavior:**

Content should not be hidden under navigation bar.

**Steps to reproduce:**

1. view a page A and navigate to page B which must contain a back button
2. on page B rotate your device 90 degrees 
3. on page B rotate your device back again
4. on page B press back
5. on page A notice the topmost content is hidden under the top nav bar

Problem is reproducible with the default ionic super starter app:

1. `ionic start default-starter-super super`
2. `ionic cordova platform add ios`
3. fix cert in xcode
4. `ionic cordova run ios -lcs`
5. on the items tab, topmost item is "Burt Bear", tap this
6. rotate 90 degrees back and forth
7. tap back
8. notice "Charlie Cheetah" is now the apparent topmost item - if dragging the list, you can see "Burt Bear" is actually still the topmost item, hiding under the navigation bar

**Related code:**

Default Ionic super starter app.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2 
    ios-sim           : 6.0.0 
    Node              : v7.9.0
    npm               : 4.2.0 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy```

**Comment by aduttonomni** [comment]
Probably related to issue #13028

**Comment by gammelby** [comment]
@aduttonomni yes, it indeed looks like the very same issue; in one of the comments I see the exact behavior I described here. I will close this issue as duplicate.

**Comment by gammelby** [comment]
Reopening as assumed duplicate https://github.com/ionic-team/ionic/issues/13028 has been closed while the problem described in this ticket persists.

**Comment by mhartington** [comment]
@gammelby can you install a nightly and test this out

`npm i ionic-angular@3.7.1-201710241735`

**Comment by gammelby** [comment]
@mhartington it fixes the problem! Thanks a lot!

**Comment by harshabonthu** [comment]
@mhartington I tried the latest nightly build on tabs template but that didn't work with screen orientation change.  Steps described in https://github.com/ionic-team/ionic/issues/13241
