### ISSUE TITLE
 The toggle component is easily triggered in scrolling up and down

### ISSUE THREAD

**Issue by coloz** [ionic-team/ionic#13173]
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request

**Current behavior:**
 The toggle component is easily triggered in scrolling up and down

**Expected behavior:**
The code does not add a judgment to the Y axis,
resulting in the upper and lower sliding time will trigger

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

I have a sample app with a page that is nothing more than a list of toggles, and it does not have this issue, so I cannot duplicate.

Thanks for using Ionic!

**Comment by coloz** [comment]
My page has multiple toggle buttons. When I scroll down the page, if my hand touches the toggle button at the beginning, the button will be triggered, but my finger is actually doing it up and down. Slide the action.
The reason for this problem is that the toggle button does not judge the change in the Y coordinate, and the upper and lower slips are judged to be the switch action.

**Comment by kensodemann** [comment]
Here is the app I am using to test:
https://github.com/kensodemann/test-bed-tabs

Go to the "About" tab and then "Open Child One" (use either button). That opens just a list of toggles.

I can easily scroll on without triggering the toggle. Maybe if I start the scrolling by actually touching a toggle off to the right, but I shouldn't do that unless I intend to trigger the toggle.

If you are seeing some different behavior, please provide a sample application demonstrating what you are experiencing.

**Comment by tradeli** [comment]
@kensodemann @coloz could this be related to #12872 and #12260?

**Comment by coloz** [comment]
@tradeli yes, #12260 is similar
