### ISSUE TITLE
webapp icon(logo.png) is missing in demo project

### ISSUE THREAD

**Issue by sonicwong** [ionic-team/ionic#13187]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

In "src/manifest.json", the icons image is linked to "assets/imgs/logo.png".
But this image is not provided in demo project.

**Expected behavior:**

logo.png in 512x512px stored in "assets/imgs/logo.png"

**Steps to reproduce:**

Just create any demo project.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I have updated the base starter template accordingly.

Thank you for using Ionic
