### ISSUE TITLE
ionScroll event is not firing, if i use ion-slides in the content.

### ISSUE THREAD

**Issue by yeshwantkumar** [ionic-team/ionic#13188]
**Ionic version:**  (check one with "x")
[ ] **3.6.0**

**Platform**
Android

**I'm submitting a ...**  (check one with "x")
[ ] bug report

**Current behavior:**
If i use ion-slides in the content, then ionScroll event is not firing. But If i don't use ion-slides in content, then ionScroll is firing correctly.

**Expected behavior:**
ionScroll event should get fire, if we use ion-slides in content.

**Related code:**
**HTML**
```
<ion-content no-padding (ionScroll)="doSomething()">
  <ion-slides (ionSlideDidChange)="slideChanged()">
    <ion-slide>
      <my-component [inputValue]="inputValue1"></my-component>
    </ion-slide>
    <ion-slide>
      <my-component [inputValue]="inputValue2"></my-component>
    </ion-slide>
 </ion-slides>
</ion-content>
```

**TS**
```
  doSomething(){
    console.log("Scroll fired");
 }
```
doSomething method is not getting called here.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

It will if you have something to scroll to, like this:

```html
<ion-content no-padding (ionScroll)="doSomething()">
  <ion-slides (ionSlideDidChange)="slideChanged()">
    <ion-slide>
      <div>lolz</div>
    </ion-slide>
    <ion-slide>
      <div>wut?</div>
    </ion-slide>
  </ion-slides>
  <div>Extra stuff at the bottom</div>
  <div>Extra stuff at the bottom</div>
  <div>Extra stuff at the bottom</div>
  <div>Extra stuff at the bottom</div>
  <div>Extra stuff at the bottom</div>
</ion-content>
```

I am not quite sure what you are trying to do with your code, however. Perhaps a sample application via GitHub?

Thank you for using Ionic

**Comment by yeshwantkumar** [comment]
Thank you @kensodemann for quick reply, Here is the [url](https://github.com/yeshwantkumar/Demo) of sample application. Here, ionScroll event is not firing, if i use ion-slides in the content. Even the page was not scroll able, i have to do a change in _home.scss_ file to make it scroll able, now i'm able to scroll the page, but ionScroll event is still not firing.
