### ISSUE TITLE
ionic3 ion-select interface popover and selectOptions mode md not working

### ISSUE THREAD

**Issue by androidhoya** [ionic-team/ionic#13184]
ionic3 ios mode.
<ion-select [interface]="'popover'" [selectOptions]="{mode: 'md'}">
interface popover is not mertial design....(md) T.T

how to ios mode, ion-select interface popover and md mode?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
