### ISSUE TITLE
Host Key Verification failure while running npm install during build

### ISSUE THREAD

**Issue by trinecast** [ionic-team/ionic#13186]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[X ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I use "git push ionic master" to push my linked application, it fails during the build process. When it is doing NPM install, it attempts retrieve ANOTHER private GIT repository listed in the package.json via NPN.  It fails with a Host Key verification failed message.

**Expected behavior:**
It should be able to retrieve the dependant github library using the uploaded SSH Key. This is the same SSH Key that I used on my machine.

**Steps to reproduce:**
Do an "git push ionic master" to initiate a new build.

**Related code:**
The application "Conferee in my account is exhibiting this issue.

A sample application via GitHub

StackBlitz (https://stackblitz.com)

Plunker (http://plnkr.co/edit/cpeRJs?p=preview)

-->

```
insert short code snippets here
```

**Other information:**
Stack Trace via Ionic Dashboard showing failed build:
Running with gitlab-ci-multi-runner 9.1.0 (0118d89)
  on Prod Snapshot Builds 1 (c9648220)
Using Shell executor...
Running on ip-10-2-57-120...
Cloning repository...
Cloning into '/home/gitlab-runner/builds/c9648220/0/project-1'...
Checking out fe642133 as master...
Skipping Git submodules setup
$ fetch-updates
Checking for build process updates...
$ build-app
Fetching build dependencies...
Running: npm install
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/trinecast/conferee-common.git
npm ERR! 
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitlab-runner/.npm/_logs/2017-10-18T23_31_36_188Z-debug.log
npm install failed
Running after script...
$ clean-up
Cleaning up files...
Successful clean up
ERROR: Job failed: exit status 1

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.2

global packages:
    cordova (Cordova CLI) : 7.0.1

local packages:
    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.4.0 windows 5.0.0
    Ionic Framework    : ionic-angular 3.7.1

System:
    Node : v8.1.4
    npm  : 5.0.3
    OS   : Windows 10

Misc:
    backend : pro

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am closing this as it is not an issue with the Ionic Framework. It appears to be an issue with Ionic Pro. For issues related to Ionic Pro, please use the [Ionic Pro support portal](http://support.ionicjs.com)

Thank you for using Ionic
