### ISSUE TITLE
DateTime Bug

### ISSUE THREAD

**Issue by StormKid** [ionic-team/ionic#13189]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

I have a bug for "ion-datetime" which show at this picture.I do not resove this time. 

![000000016](https://user-images.githubusercontent.com/13798727/31766600-9bcb7666-b4fa-11e7-9ef6-fd77a6df2c03.gif)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by StormKid** [comment]
@kensodemann 
 **This time . when I write a new project , I get a new bug:**

![1u28d y 55rwlvyd r71](https://user-images.githubusercontent.com/13798727/31803675-b6bf6148-b587-11e7-9d5f-33c53451c109.png)

**This is my code. I think it might be that I have updated ionic at yesterday:**

![ieg762k7y7 dzp 40e9](https://user-images.githubusercontent.com/13798727/31803832-87fec6d6-b588-11e7-8111-37300f0f5ff1.png)

![0tm4g 5tlbwe e4 z0f0 4e](https://user-images.githubusercontent.com/13798727/31803892-cdc2ad7c-b588-11e7-8774-49b07dbffc65.png)

**And this is my Ionic info**
![j7 qnr9fy lzaqysqoplbow](https://user-images.githubusercontent.com/13798727/31803905-e17c96fc-b588-11e7-83f1-09b03f77cc82.png)

**Comment by StormKid** [comment]
@kensodemann  I have wrote a project which url is 'https://github.com/StormKid/ionic---test---dateTime'. Then run serve and when you show timePick please fast move pickview also do not move smooth. You might look the bug at first time . Please try more time.

**This is my ionic info:**
![j7 qnr9fy lzaqysqoplbow](https://user-images.githubusercontent.com/13798727/31804527-7971cdc6-b58c-11e7-9cec-4a8a75fb09af.png)

**Comment by kensodemann** [comment]
I tried your sample in the browser and it always works fine, no matter what I do. Every time I had 'Done' the date is updated accordingly.

Also tried on an older Android device.

Maybe I just do not fully understand what you are reporting here. In your picture, it looks like the errant behavior is that the button is not being updated with the chosen date, but perhaps you are attempting to show something else.

Please expand your explanation of what you are reporting.

**Comment by kensodemann** [comment]
I see that sometimes the "min" and "max" limiting it not occurring appropriately. Is that what you are trying to show with your graphic? It is very hard to tell without any context.

**Comment by StormKid** [comment]
@kensodemann Look at this picture：
![000000017](https://user-images.githubusercontent.com/13798727/31921019-61c54494-b89f-11e7-9886-3aad8d3fbe0f.gif)

**Comment by kensodemann** [comment]
OK, so it looks like what you are trying to report is that sometimes the "min" or "max" are not auto-selected when the date is below the "min" or above the "max" which would allow for an invalid date. Is that correct? (just wanting to make sure, because pictures without words can be hard to interpret).

**Comment by StormKid** [comment]
@kensodemann ok , It's correct! I also want to ask about extra words is that ionic4 would use vue.js to product project?

**Comment by kensodemann** [comment]
@StormKid - short answer: yes, with v4 of Ionic you will be able to use Vue.js. Maybe not right away, but the plan is that it will at some point in the near future be something you can do.

Longer answer: http://blog.ionic.io/ionic-2017-18-roadmap/

**Comment by StormKid** [comment]
@kensodemann Thanks for you answer. I just like angular and typescript to product my project. I hope Ionic Team will make ionic-angular better than better.

**Comment by StormKid** [comment]
Sorry ,  I reply too late. This proplem has been resolved in ionic v3.19.1.  Thanks a lot . I hope that ionic v4.0  publish as soon as possible.

**Comment by chandanch** [comment]
Hello, when will ionic 4 beta release?
