### ISSUE TITLE
label : help wanted .  PopOver

### ISSUE THREAD

**Issue by ohrrkan** [ionic-team/ionic#13190]
Hi,

I have a ion-range in my popOver Component. I simply want to get the range value in the parent component who have create the popOver. How can i do this? 

I probably know that is it possible if i communicate via a service in the middle but i want to find a light solution. I try @output decorator but how to catch the event in the parents? or another solution?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
