### ISSUE TITLE
Ionic Pro Deploy from a subfolder

### ISSUE THREAD

**Issue by jdnichollsc** [ionic-team/ionic#13192]
Hi guys,

I can't see the way to deploy to Ionic Pro service if my app exist in a subfolder of my git repository **(I don't like the idea to have the "www" folder at the root of the repository)**, so I created the following script to deploy from **TeamCity**:

```
ssh-agent bash -c "ionic ssh use <ionicKey> --no-interactive; ionic login <email> <password> --quiet --no-interactive; ssh-add <ionicKey>; ionic git remote --no-interactive; git rm -r --cached .; git add .; git commit -m 'Updated with the last changes'; git push ionic HEAD:<branch> -f;"
```

IonicKey: A private key generated at the root of the cordova app folder

Let me know what you think, maybe you can add that script in the documentation of the Ionic website

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. This communication appears to be an Ionic Pro related issue.

For Ionic Pro issues, suggestions, etc., please use the [Ionic Pro support portal](http://support.ionicjs.com)

Thanks for using Ionic!
