### ISSUE TITLE
ipad ios 9.3.5 is not that touch responsive , they take delay in button click and scroll get hang when lots of data is loaded

### ISSUE THREAD

**Issue by Gamerakki** [ionic-team/ionic#13196]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In ipad with ios 9.3.5 the button click are taking delay even after adding tappable in attribute having the click command. The scroll get hanged when data above 500 is loaded. I have added the ionc-webview-plugin but the performance is still the same. Plus the header issue when keyboard get open it get pushed up out of the view not fixed at the top

**Expected behavior:**
the touch response should be smooth. the scroll shouln't get hanged when data is loaded more than 500. The header should be at top even though the keyboard is open.

**Steps to reproduce:**
please try deploying on ipad with ios 9.3.5

**Comment by oddcb** [comment]
@Gamerakki try taking a look at https://github.com/ionic-team/ionic/issues/12733 and see if the solutions/work arounds presented there works.

**Comment by Gamerakki** [comment]
already tried it but facing the same issue. can u please help a live project of mine is stuck due to this

**Comment by fakerLinXiao** [comment]
@Gamerakki same issue, do you have a solution now?
