### ISSUE TITLE
Upgrading ionic CLI has no effect

### ISSUE THREAD

**Issue by ddahan** [ionic-team/ionic#13191]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
Running `npm install -g ionic@latest` returns:
`+ ionic@3.13.2 removed 1 package and updated 11 packages in 23.97s`
But when running `ionic info`, the old version is still there: `ionic (Ionic CLI) : 3.9.2`
The new version is not installed.

**Expected behavior:**
running `ionic info` should return `ionic (Ionic CLI) : 3.13.2`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.4
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v8.3.0
    npm  : 5.3.0
    OS   : macOS Sierra
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Do you perhaps have the CLI installed local to your project? (check your `package.json`)

Also, what do you get if you type `ionic -v` at the command line?

Thank you for using Ionic

**Comment by ddahan** [comment]
Hello!
I installed it using the `-g`option and I can't find it the package.json

`ionic -v` returns the old version (3.9.2)

**Comment by kensodemann** [comment]
That is interesting...

```
~/Projects/Stencil/webpack (feature/addTests *): npm i ionic -g
/usr/local/bin/ionic -> /usr/local/lib/node_modules/ionic/bin/ionic
+ ionic@3.13.2
updated 4 packages in 9.59s
~/Projects/Stencil/webpack (feature/addTests *): ionic -v
3.13.2
~/Projects/Stencil/webpack (feature/addTests *): 
```

Note that for me, npm is creating the symlink in `/usr/local/bin` while for you it is being created in `/usr/local/lib/node_modules/node/bin`, which seems really weird.

What do you get with `which ionic`?

I am going to close this as it not an Ionic Framework issue, nor does it appear to be a CLI issue so I won't move this issue to that repo. It appears to be something with your npm setup. Feel free to keep commenting back here, though. I will help you to the point that we hit the end of my knowledge (which is actually probably coming up pretty quickly).

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Perhaps someone else has seen this as well.

**Comment by kensodemann** [comment]
Also, what does `npm config list` show?

```
~/Projects/Stencil/webpack (feature/addTests *): npm config list
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.5.1 node/v8.7.0 darwin x64"

; builtin config undefined
prefix = "/usr/local"

; node bin location = /usr/local/Cellar/node/8.7.0/bin/node
; cwd = /Users/kensodemann/Projects/Stencil/webpack
; HOME = /Users/kensodemann
; "npm config ls -l" to show all defaults.
```

**Comment by ddahan** [comment]
Thanks.
Actually, it seems there was a second binary of node, and it was used by Ionic. I can't explain why.
I deleted the whole `/usr/local/lib/node_modules/` folder, then reinstalled node/npm at the correct place, and then Ionic.
It now works as expected.
Thanks!
