### ISSUE TITLE
feat(Range) : using LEFT or RIGHT keys : knob is moved, but value is not modified, the event is not fired.

### ISSUE THREAD

**Issue by Titoch** [ionic-team/ionic#13199]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Using keyboard keys (left arrow or right arrow) to decrease or increase the ion-range value, the knob is moved, but the value model is not modified. Also, the (ionChange) event is not fired.

**Expected behavior:**
Moving Knob via LEFT, UP, DOWN or RIGHT keys on keyboard should modify the value model and fire the event ionChange as the knob is moved.

**Steps to reproduce:**
In a WEB browser with a keyboard, move the focus to the knob's <ion-range>. Then press LEFT, RIGHT,  UP, DOWN key to move the knob. The model value is not modified.

**Related code:**

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by Titoch** [comment]
Hello,
You can see the bug on the demo in ionic doc/api/components/range.

https://ionicframework.com/docs/api/components/range/Range/

On the displayed phone on the right (displayed as demo on large screen), 
1 => click above one of the ranges (in an empty zone) to set the focus on the phone app demo. 
2 => Press the [Tab] key 1, 2 or 3 times.  One of the knobs will get the keyboard focus. You should see a selection square around one of the knob on a range. 
3 => Now you can move the Knob using the keyboard arrows.
You can see that the displayed value in the badge never changes.

A lot of people like blind people, uses only keyboard to control applications, because they can't easily use a mouse. So this bug prevents them to use any application with Range.

**Comment by kensodemann** [comment]
Thank-you. Was able to duplicate.
