### ISSUE TITLE
Failed to fetch plugin git+ssh://git@ ... .git via registry

### ISSUE THREAD

**Issue by patrickbussmann** [ionic-team/ionic#13205]
**Ionic version:**
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**
[X] bug report
[ ] feature request

**Current behavior:**
I got an error if I'm execute `ionic cordova build android` because of plugin restore try.

**Expected behavior:**
I get no error because the plugin can be fetched.

**Steps to reproduce:**
I'm using cordova 7.1.0 and ionic 3.13.0.

    "dependencies": {
        "custom-plugin": "git+ssh://git@bitbucket.org/test/custom-plugin.git"
    },

**Error:**

```
Failed to restore plugin "custom-plugin" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin git+ssh://git@bitbucket.org/test/custom-plugin.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

**Other information:**
https://github.com/angular/angular-cli/issues/8006
https://forum.ionicframework.com/t/failed-to-restore-plugin-cordova-plugin-statusbar-in-ionic-cordova-platform-add-android/108151

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

	cli packages: (/bitrise/src/node_modules)
		@ionic/cli-utils  : 1.13.1
		ionic (Ionic CLI) : 3.13.1
	global packages:
		cordova (Cordova CLI) : 7.1.0 
	local packages:
		@ionic/app-scripts : 3.0.0-201710161925
		Cordova Platforms  : none
		Ionic Framework    : ionic-angular 3.7.1-201710101557
	System:
		Android SDK Tools : 26.1.1
		Node              : v8.7.0
		npm               : 5.5.1 
		OS                : Linux 4.4
	Misc:
		backend : pro

**Comment by danielehrhardt** [comment]
Yes same problem here!!

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

You should also search the issues list for the Ionic CLI here: https://github.com/ionic-team/ionic-cli

Thanks for using Ionic!

**Comment by patrickbussmann** [comment]
Hmm @kensodemann it's correct specified so this is no question, its an error.
Maybe the question is if this is a npm, cordova or ionic problem.
If I move the plugin to `config.xml` and remove it from package.json it will work fine.

So where to search for the problem? Ionic CLI? NPM? Cordova?

**Comment by kensodemann** [comment]
I would start with the Ionic CLI repo listed in my prior reply.

**Comment by ZalakSA** [comment]
@patrickbussmann I am facing similar issue like yours 

Error:- 

`Failed to restore plugin "branch-cordova-sdk" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin branch-cordova-sdk@^2.6.0 via registry.`

**Comment by fdambrosio** [comment]
I have the same problem

**Comment by patrickbussmann** [comment]
Hey @ZalakSA and @fdambrosio:

I temporarily fixed this by only adding this `git+ssh` plugins only to the `config.xml`.
So in my `config.xml` I have all plugins which contains `git+ssh` in the name/url and in the `package.json`  I have all other plugins.

The plugins will be added successfully and I have no problems 👍 
But it's bad because I must take care about both files. And the packages will be added automatically to package.json after install so I must take care to not commit them to git repository 👎

**Comment by DavidWiesner** [comment]
It's a problem of cordova > 7.0.2. Vote and comment on issue in cordova https://issues.apache.org/jira/browse/CB-13507
