### ISSUE TITLE
icon font from iconfont.com not work

### ISSUE THREAD

**Issue by lqjack** [ionic-team/ionic#13206]
I have try serval to make it work, but until now i cannot solve it .  The methods as blow : 

# 1 
I download the iconfont.*(eot,svg,ttf,woff) resources and copy them in the dir src/assets/chat(chat is the new folder name) .
I put the iconfont.scc in the src/theme.
I want to use the resource in the tabs.html , so according tot the structure of project generated angular-cli , i update the tabs folder under the src/pages/ and create the new file named tabs.scss. 
Then in the tabs.html . i refer the style as blow : 
```NodeJs
<ion-tabs>
  <ion-tab [root]="tab1Root" tabTitle="Home" tabIcon="chat"></ion-tab>
</ion-tabs>
```
But the style not show. the screenshot as below : 
![issue](https://user-images.githubusercontent.com/4533570/31848609-cede47d4-b5fb-11e7-8fff-edcd899d81a0.png)

# 2 
i try to put the iconfont.* resource into the folder www/assets/. and no luck .

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
