### ISSUE TITLE
Feature: Navbar large titles IOS 11

### ISSUE THREAD

**Issue by brtwister** [ionic-team/ionic#13203]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

Will Ionic implement Large titles on navbars? Feature of ios 11?
Thanks.
<img width="260" alt="72sjd" src="https://user-images.githubusercontent.com/4661438/31834440-b9308f72-b5ac-11e7-97d6-8731ba9472a7.png">

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#322

**Comment by jdeanwaite** [comment]
Link is dead, is there an updated one?

**Comment by arorak** [comment]
Please update the link. The above link is not working

**Comment by cperezabo** [comment]
Hey can someone fix the link? I want to know if this feature is going to be implemented or contribute to develop it! But I am not finding an active thread about it
