### ISSUE TITLE
ion-input in ionic-grid > ionic-row > ion-item can't work (ionic 2)

### ISSUE THREAD

**Issue by 13122310958** [ionic-team/ionic#13207]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ x] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

should can go to next input without next button in keyboard .

only can work in  ionic-list > ionic-item > ion-input. 

**Steps to reproduce:**

**Related code:**

```
<ion-grid>
<ion-row>
</ion-col>
<ion-item>
                <ion-label color="black" >test1</ion-label>
                <ion-input type="number"  text-right placeholder="0" name="a" [(ngModel)]="data.a" pattern="\d*">
                  </ion-input>
              </ion-item>
</ion-item>
</ion-col>
</ion-row>
<ion-row>
<ion-col>
<ion-item>
                <ion-label color="black" >can't go this input in ios</ion-label>
                <ion-input type="number"  text-right placeholder="0" name="b" [(ngModel)]="data.b" pattern="\d*">
                  </ion-input>

              </ion-item>
</ion-item>
</ion-col>
</ion-row>
</ion-grid>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1-201710181432

System:

    Android SDK Tools : 25.2.5
    Node              : v7.3.0
    npm               : 5.3.0
    OS                : OS X El Capitan
    Xcode             : Xcode 8.0 Build version 8A218a

Misc:

    backend : legacy

**Comment by sfaizanh** [comment]
Hi @13122310958 Everything works find you have a bad HTML
```
<ion-grid>
<ion-row>
</ion-col> -------- error (should not be closed here)
<ion-item>
                <ion-label color="black" >test1</ion-label>
                <ion-input type="number"  text-right placeholder="0" name="a" [(ngModel)]="data.a" pattern="\d*">
                  </ion-input>
              </ion-item>
</ion-item> -------- error (closed twice)
</ion-col>
</ion-row>
<ion-row>
<ion-col>
<ion-item>
                <ion-label color="black" >can't go this input in ios</ion-label>
                <ion-input type="number"  text-right placeholder="0" name="b" [(ngModel)]="data.b" pattern="\d*">
                  </ion-input>

              </ion-item>
</ion-item>  -------- error (closed twice)
</ion-col>
</ion-row>
</ion-grid>
```
*cleaned version*
```
<ion-grid>
	<ion-row>
		<ion-col>
			<ion-item>
				<ion-label color="black">test1</ion-label>
				<ion-input type="number" text-right placeholder="0" name="a" [(ngModel)]="data.a" pattern="\d*"></ion-input>
			</ion-item>
		</ion-col>
	</ion-row>
	<ion-row>
		<ion-col>
			<ion-item>
				<ion-label color="black">can't go this input in ios</ion-label>
				<ion-input type="number" text-right placeholder="0" name="b" [(ngModel)]="data.b" pattern="\d*"></ion-input>
			</ion-item>
		</ion-col>
	</ion-row>
</ion-grid>
```

**Comment by sfaizanh** [comment]
If you want **Next Button** wrap this in <form></form>

**Comment by 13122310958** [comment]
thanks .
