### ISSUE TITLE
IOS 11 Large title

### ISSUE THREAD

**Issue by brtwister2** [ionic-team/ionic#13201]
Will Ionic implement large titles on navbar, feture of IOS 11?
<img width="260" alt="72sjd" src="https://user-images.githubusercontent.com/4664818/31830303-94a59980-b59e-11e7-8055-0f5f3a214073.png">

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out as a feature request, please.

If you just want to discuss this question and not make a feature request, then I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
