### ISSUE TITLE
iOS UI Bug in case of disabled WKWebView 

### ISSUE THREAD

**Issue by codebeauty** [ionic-team/ionic#13219]
**Ionic version:** 
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  
[x] bug report
[ ] feature request

**Current behavior:**

In case you remove WKWebView you are able to scroll the whole app. The NavigationBar and the TabBar moves up and down. 

Like the docs says you can still remove WKWebView. In our case we remove WKWebView because we need to test more before we switch over to WKWebView.

Tested only on iOS11.

**Expected behavior:**

1. Elements like TabBar and NavigationBar stays fixed on their places
2. WKWebView is default but not a must have, right?

**Steps to reproduce:**

1. update your Env for Ionic 3.7.1
2. create app template for TabBar app _ionic start MyApp tabs_
3. remove WKWebView
4. add platform iOS
5. build & run app
6. swipe/scroll up and down on the right side

**Other information:**

**Ionic info:** 

```

    @ionic/cli-utils  : 1.14.0
    ionic (Ionic CLI) : 3.14.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.5.2
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2
    Node       : v6.11.4
    npm        : 5.5.1
    OS         : macOS High Sierra
    Xcode      : Xcode 9.0.1 Build version 9A1004

Misc:

    backend : legacy
```

Thank you.

**Comment by mhartington** [comment]
With iOS11, UIWebview (the older view) has a few bugs that make it un-useable for Ionic. So WKWebview is a requirement now

**Comment by codebeauty** [comment]
Thank you @mhartington Should be more clear in your blog post and in the documentation that WKWebview is required since 3.7.x.
