### ISSUE TITLE
Ionic tabs moves to the bottom after device camera closes

### ISSUE THREAD

**Issue by hsob** [ionic-team/ionic#13217]
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
ion-tabs move to the bottom after cordova camera open to take picture:

![img_1652](https://user-images.githubusercontent.com/32904281/31891536-fca4f3c2-b806-11e7-9bfb-e6a7526753a9.PNG)

**Expected behavior:**

Without the bug ion-tabs must stay in its position.

**Steps to reproduce:**

**Related code:**

I use to create ionic-tabs: 
<ion-tabs>
    <ion-tab> 
      ....
    </ion-tab>
</ion-tabs>

**Other information:**
I'm using:

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.2

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : ios 4.5.2
    Ionic Framework    : ionic-angular 3.5.3

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.0.0 
    Node              : v6.10.3
    npm               : 3.10.10 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0.1 Build version 9A1004

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
