### ISSUE TITLE
Ionic 2 / 3 <iOS> APP crashes after opening when using FCM  

### ISSUE THREAD

**Issue by ron-gonzalez** [ionic-team/ionic#13210]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
APP Crashes when after start, when using FCM as proposed in 
https://ionicframework.com/docs/native/fcm/
ONLY IOS, Android is OK.

The cause is that the Generated ".ipa" installer for IOS, Contains a **binary chuncked**  _"GoogleService-Info.plist"_ 

In My Repo on root folder ( same as config.xml ) I have uploaded the correct file, but it appears to be ignored, putting a invalid file on ".ipa".

Fell free to test with my APP uploaded in Ionic Pro (ID: **aa3fb976**)

**Expected behavior:**
GoogleService-Info.plist in .ipa file should be the same that I uploaded in my repo

**Steps to reproduce:**
Create any APP with FCM integration, upload the GoogleService-Info.plist file and compile for **IOS**
download the .ipa, uncompress it and check the included GoogleService-Info.plist

Thank you a lot,
brest regards,
Roni

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This appears to be an issue with an Ionic Native plugin and not an issue with the Ionic Framework, so I am going to move this issue to the Ionic Native repo. Please follow-up to the new issue created over there.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-native#2058
