### ISSUE TITLE
Unnecessary trailing commas when a page is generated

### ISSUE THREAD

**Issue by AhsanAyaz** [ionic-team/ionic#13216]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When a page is generated, the generated code contains unnecessary trailing commas
in almost all the generated files

**Expected behavior:**
It should not have unnecessary trailing commas in the code

**Steps to reproduce:**

create an ionic app
cd into your project
```bash
ionic g page OrganizationReferral --constants
```

**Other information:**
![screen shot 2017-10-23 at 3 49 18 pm](https://user-images.githubusercontent.com/9844254/31885576-68fd8586-b80a-11e7-8068-775eef5497f5.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/ahsanayaz/Desktop/Work/ModusCreate/Projects/quitters-circle/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.2

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Node  : v8.2.1
    npm   : 5.3.0
    OS    : macOS Sierra
    Xcode : Xcode 9.0.1 Build version 9A1004

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Trailing commas are perfectly valid and potentially useful syntax: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

Whether to use them or not is a matter of personal style. If you choose not to, that is fine. Others find them convenient, especially in generated code that will be added on to.

Thank you for using Ionic

**Comment by AhsanAyaz** [comment]
Hi ! 
Thanks for clearing that out @kensodemann

**Comment by kensodemann** [comment]
One idea that might be cool is to allow people to use custom templates. Not sure how that would work entirely. That would be a feature request for the app-scripts repo though.

Just thinking out loud...
