### ISSUE TITLE
Can't push ionic master from Ionic Pro. 

### ISSUE THREAD

**Issue by cemceliks** [ionic-team/ionic#13211]
After ssh is created I get the privatekey access denied as well. Read other articles for windows. I am on Mac Sierra. This is a second try to build and push first was totally erased as a new build computer. might be relative to know this. SSH was generated successfully and all the files are there. How can I resolve this issue. In windows some suggested deleting the config folder, which I have not done. Should I rename the folder instead and try again. 
<img width="654" alt="screen shot 2017-10-22 at 17 01 27" src="https://user-images.githubusercontent.com/33004134/31863638-7a6f2f14-b750-11e7-8aab-a51c23aee6b6.png">

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

The issue you are reporting appears to be an issue with the Ionic Pro service. For issues related to the Ionic Pro serverice, please consult the Ionic Pro support portal (http://support.ionicjs.com)

Thanks for using Ionic!
