### ISSUE TITLE
Header trail issue on ios with headers of different colors

### ISSUE THREAD

**Issue by mrvipinkashyap** [ionic-team/ionic#13225]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
My app has header with different color and main page with transparent header. When closing any page it is leaving a trail of header which stays on page for a second or so and then goes away. This is happening only on iOS. This is an unexpected behaviour and poor for user experience.

**Expected behavior:**
App should not leave header trail of closing page.

**Steps to reproduce:**
One should be able to reproduce this with any ionic starter app with pages having different header color.
![ios header trail issue](https://user-images.githubusercontent.com/6937626/31946779-625703c4-b8f0-11e7-8f95-4905c9c6735e.gif)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
   @ionic/cli-utils  : 1.14.0
    ionic (Ionic CLI) : 3.14.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2
    Node       : v6.11.1
    npm        : 3.10.10
    OS         : macOS High Sierra
    Xcode      : Xcode 9.0 Build version 9A235

Misc:

    backend : pro
```

Please let me know if any other information is required to replicate or resolve this issue.

Thanks

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by mrvipinkashyap** [comment]
This seems to have been an issue because we had given background color to 
`.toolbar-background-ios` and `.ion-header` in scss.
Commenting both and adding background color to just `.header-ios .toolbar-ios:last-child .toolbar-background-ios` for ios resolved this issue.

I guess this is something of a common mistake one can make so should probably be fixed in future versions of ionic.
