### ISSUE TITLE
Breaklines on ion-textarea in Android v7.0

### ISSUE THREAD

**Issue by memphis23** [ionic-team/ionic#13220]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After installing apk on an Android v7.0 device, breaklines on ion-textarea are not working. Meanwhile, it works properly when running on debug mode.   
      <ion-textarea rows="3" disabled="true" value="{{user.address}}\r\n{{user.postalCode}} {{user.city}}\r\n{{user.province}}"></ion-textarea>      
This is shown as
{{user.address}}\r\n{{user.postalCode}} {{user.city}}\r\n{{user.province}}

**Expected behavior:**
Breaklines should work on production mode. It should not show any \r\n.
It should be shown as
{{user.address}}
{{user.postalCode}} {{user.city}}
{{user.province}}

**Steps to reproduce:**
Insert this line in a html and generate a release of the apk 
      <ion-textarea rows="3" disabled="true" value="{{user.address}}\r\n{{user.postalCode}} {{user.city}}\r\n{{user.province}}"></ion-textarea>      

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

As this appears to be an Ionic App Scripts issue and not an Ionic Framework issue, I am moving this to the Ionic App Scripts repo. Please follow-up to this issue using the new issue over there.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1290

**Comment by memphis23** [comment]
Have you moved this issue to [ionic-team/ionic-app-scripts#1290](url)? But it seems to be closed. I do not understand why.

**Comment by kensodemann** [comment]
The linked issue is open, that is the one to follow. Perhaps I do not understand your question.
