### ISSUE TITLE
IMPORTANT iOS 11 update for Media Capture

### ISSUE THREAD

**Issue by trbsi** [ionic-team/ionic#13228]
When building an app for iOS 11, everything works fine with Camera and Capture Media plugins. Media Capture makes the problem because it doesn’t include all photo permissions and when I take a picture and want to crop it, it crashes.

What XCode 9 tells me:

This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app’s Info.plist must contain an NSPhotoLibraryAddUsageDescription
You need to add permission https://stackoverflow.com/a/44527525/18608904
See screenshot:
![94ff3fe545d0527d722497433471b6b1a58b3f8a_1_690x162](https://user-images.githubusercontent.com/3958715/31959782-efa5123e-b8f5-11e7-8afe-aed08ed66776.png)

**Comment by sfaizanh** [comment]
Try to add this in config.xml
```
<platform name="ios">
        ...
        ...
        ...
        <config-file mode="replace" parent="NSPhotoLibraryUsageDescription" platform="ios" target="*-Info.plist">
            <string>Allows to attach images from library to an asset.</string>
        </config-file>
</platform>
```

**Comment by sfaizanh** [comment]
Try this [https://github.com/cordobo/cordova-plugin-ios-camera-permissions](url)

**Comment by trbsi** [comment]
That's what I used to fix the problem, but I wanted to point out that because just by using Media Capture I wasn't aware of that so it  took some time to figure out why my app was crushing.

**Comment by sfaizanh** [comment]
Thanks, btw which cordova plugin did you use, this one? https://github.com/apache/cordova-plugin-camera

**Comment by trbsi** [comment]
This one https://ionicframework.com/docs/native/media-capture/

**Comment by sfaizanh** [comment]
Have you tried `ionic cordova plugin add https://github.com/apache/cordova-plugin-media-capture.git` pull directly from github but it can be unstable

**Comment by sfaizanh** [comment]
https://github.com/apache/cordova-plugin-camera/commit/51d665a7a1cfcab1a0e1a4803a53369f665e6c99 cordova-plugin-camera added NSPhotoLibraryAddUsageDescription but they haven't released it.

**Comment by trbsi** [comment]
I solved my problem with https://github.com/cordobo/cordova-plugin-ios-camera-permissions
I just wanted to warn about iOS 11 and Media Capture

**Comment by kensodemann** [comment]
I am going to close this because it appears to be resolved. If this is not the case, please let me know.

**Comment by apparatuspune** [comment]
i used media capture plugin and set the tome to 3 sec , after 3 sec there is a popup alert , stating that the maximum lenth reach , i want to that popup
