### ISSUE TITLE
Browser BackButton: View not reloaded, but URL changed

### ISSUE THREAD

**Issue by AlessandroSchneiderTest** [ionic-team/ionic#13224]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

**Current behavior:**
I use DeepLinking. With ionic 3.7.1. the error of reloading the wrong SubTabs while loading Tabs-Page does not occur anymore. But now the browser back button does not work anymore. This means that when I click on back/forward button the url changes but the content stays the same.

**Expected behavior:**
Content should change according to Back-Button and reloaded URl.

**Steps to reproduce:**
ionic serve (project) - I can give private access but I can't publish repository if needed.

**Related code:**
```
 imports: [
    TagInputModule,
    FileUploadModule,
    IonicModule.forRoot(MyApp, {}, 
      {
      links: [
      
        
        { component : VerifyPage, name: 'verify', segment : 'verify/:id'},
        { component: TestPage, name: 'TestPage', segment: 'test' },
        { component: TestPage, name: 'TestPage', segment: 'test' },
        { component: KontaktPage, name: 'KontaktPage', segment: 'kontakt' },
        { component: ImpressumPage, name: 'ImpressumPage', segment: 'impressum' },
        { component: BewerbenPage, name: 'BewerbenPage', segment: 'bewerbenaa' },
        { component: MyJobsPage, name :'MyJobsPage', segment: 'myjobs'},
        { component: JobFormPage, name:'JobFormPage', segment:'jobform'},
        { component: TabsPage, name:'TabsPages', segment:'tabs'},
        { component: ProfilePage, name : 'ProfilePage', segment: 'profile' },
        
      ]
    }
  
  ),




...



    {
      provide: AuthHttp,
      useFactory: getAuthHttp,
      deps: [Http]
    },
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.7.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 2.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: OS X Yosemite
Node Version: v7.9.0
Xcode version: Xcode 6.4 Build version 6E35b


```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

I have attempted to duplicate your issue using our sample "Conference App" https://github.com/ionic-team/ionic-conference-app but could not, even after changing `ionic-angular` from the `nightly` build it uses by default to the `3.7.1` release build.

Thanks for using Ionic!

**Comment by AlessandroSchneiderSignUP** [comment]
HI kensodemann,

thanks for your reply.

I checked with the ConferenceApp and I could not find any reason for my app to cause this error compared to the ConferenceApp. Though my code is a bit different from it.

I invited you as a contributor to the app. I cant share it public since it is an enterprise project.

Thanks for having a look!

**Comment by AlessandroSchneiderSignUP** [comment]
A live demo can be found here: http://cohooyo.com/#/tabs/bewerben/bewerben

If you click on Kontakt and Impressum on the left you should see the effect.

**Comment by Lsy-kg** [comment]
I have the problem too.

**Comment by Lsy-kg** [comment]
@AlessandroSchneiderSignUP Do you find something to solve it?

**Comment by kensodemann** [comment]
@AlessandroSchneiderSignUP - I have taken a look at your repo but have not found anything yet. I don't know when I will have time to take a closer look.

If you can duplicate this by taking one of our starters (probably sidemenu based on your app) and updating it until it demonstrates the issue that would be very helpful.

**Comment by AlessandroSchneiderSignUP** [comment]
Hello @Lsy-kg 

thanks for that tip @kensodemann 
The reason was:

        { component: TabsPage, name:'TabsPages', segment:'tabs'},
had to be renamed to
        { component: TabsPage, name:'TabsPages', segment:'tabs-page'},

**Comment by AlessandroSchneiderSignUP** [comment]
Hi there,

I just found out that this was exactly the opposing solution of the error  of "reloading the wrong SubTabs while loading Tabs-Page" mentioned by other devleopers here on GitHub where I was told to rename tabs-page to tabs.

Can you please have a look into that?

Thanks!!
