### ISSUE TITLE
Ionic Cordova Build --Prod not working

### ISSUE THREAD

**Issue by PrakashKularatnam** [ionic-team/ionic#13221]
Error: ./src/app/app.module.ngfactory.ts
Module not found: Error: Can’t resolve ‘@angular/compiler/compiler’ in 'D:\MobileRD\BARMobileClient\src\app’
resolve ‘@angular/compiler/compiler’ in 'D:\MobileRD\BARMobileClient\src\app’
Parsed request is a module
using description file: D:\MobileRD\BARMobileClient\package.json (relative path: ./src/app)
Field ‘browser’ doesn’t contain a valid alias configuration
after using description file: D:\MobileRD\BARMobileClient\package.json (relative path: ./src/app)
resolve as module
looking for modules in D:\MobileRD\BARMobileClient\node_modules
using description file: D:\MobileRD\BARMobileClient\package.json (relative path: ./node_modules)
Field ‘browser’ doesn’t contain a valid alias configuration
after using description file: D:\MobileRD\BARMobileClient\package.json (relative path: ./node_modules)
using description file: D:\MobileRD\BARMobileClient\node_modules@angular\compiler\package.json (relative path: ./compiler)
no extension
Field ‘browser’ doesn’t contain a valid alias configuration
D:\MobileRD\BARMobileClient\node_modules@angular\compiler\compiler doesn’t exist
.ts
Field ‘browser’ doesn’t contain a valid alias configuration
D:\MobileRD\BARMobileClient\node_modules@angular\compiler\compiler.ts doesn’t exist
.js
Field ‘browser’ doesn’t contain a valid alias configuration
D:\MobileRD\BARMobileClient\node_modules@angular\compiler\compiler.js doesn’t exist
.json
Field ‘browser’ doesn’t contain a valid alias configuration
D:\MobileRD\BARMobileClient\node_modules@angular\compiler\compiler.json doesn’t exist
as directory
D:\MobileRD\BARMobileClient\node_modules@angular\compiler\compiler doesn’t exist
[D:\MobileRD\BARMobileClient\node_modules@angular\compiler\compiler]
[D:\MobileRD\BARMobileClient\node_modules@angular\compiler\compiler.ts]
[D:\MobileRD\BARMobileClient\node_modules@angular\compiler\compiler.js]
[D:\MobileRD\BARMobileClient\node_modules@angular\compiler\compiler.json]
[D:\MobileRD\BARMobileClient\node_modules@angular\compiler\compiler]
@ ./src/app/app.module.ngfactory.ts 155:0-51
@ ./src/app/main.ts

Kindly help me on this issue.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by PrakashKularatnam** [comment]
Hi Sodemann,

*To whom I want to consult for this issue to resolve.  *

*We are unable to generate the production release now.*

*Regards,*

*Prakash*

**Comment by kensodemann** [comment]
Howdy!

The two links I provided above are good starting points. Also, you could have a look in the Ionic App Scripts repo issues. Please search all open and closed issues.

If you cannot find a resolution in any of those locations open an issue in the app scripts repo with the template fully filled out and containing detailed steps to reproduce including (ideally) a sample repo that demonstrates the issue.
