### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: No component factory found for t. Did you add it to @NgModule.entryComponents?

### ISSUE THREAD

**Issue by shindekaps** [ionic-team/ionic#13235]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If I create development build using command "ionic cordova build android" all functionality working fine. When I create production build using command "ionic cordova build android --prod" then for LoadingController.create method I am getting this issue
**Expected behavior:**

Should work same like development build.
**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```
/**
    * This method is used to show preloader
    * @param {void}
    * No param required
    * @example
    * showPreloader();
    * @returns  {void}
   *
    * Nothing to return
    */
  showPreloader() {
    this.hidePreloader();
    IonicModels.loader = this.loaderCtrl.create({});// loderCtrl is instance of LoadingController
    IonicModels.loader.present();
  }
  /**
    * This method is used to hide preloader
    * @param {void}
    * No param required
    * @example
    * hidePreloader();
    * @returns  {void}
    * Nothing to return
    */
  hidePreloader() {
    if (IonicModels.loader)
      IonicModels.loader.dismiss();
  }

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

cli packages: (C:\kapil\retailer-hybrid-app\node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 1.3.6
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.2.1

System:

    Android SDK Tools : 25.2.3
    Node              : v7.4.0
    npm               : 4.0.5
    OS                : Windows 7

Misc:

    backend : legacy
![androidprodbuildissue](https://user-images.githubusercontent.com/6639215/31996140-e576b0c4-b9a4-11e7-8c72-1d3adeebd733.PNG)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? It doesn't have to be your app, but if you could start with a starter app and then add the minimal stuff to get the issue to occur that would be great.

Also, your versions of app-scripts and ionic-framework are fairly old. I don't know if doing a general upgrade of your tools and libraries would help you are not, but you might want to give that a shot too.

Thanks for using Ionic!

**Comment by shindekaps** [comment]
Hello ! Thank you for quick response. As you mentioned I have updated the ionic framework and app-script. Now it is working fine. 

Thanks
Kapil Shinde

**Comment by aarthisippailab** [comment]
cli packages: (/../../.nvm/versions/node/v9.1.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.1.1
    Node              : v9.1.0
    npm               : 5.5.1 
    OS                : Linux 4.10

Misc:

    backend : pro

still i am getting the same error... 
Error: No component factory found for t. Did you add it to @NgModule.entryComponents?
