### ISSUE TITLE
Attribute application@allowBackup value=(false) from AndroidManifest.xml:4:18-45         is also present at [:barcodescanner:] AndroidManifest.xml:12:9-35 value=(true).

### ISSUE THREAD

**Issue by SumitManna** [ionic-team/ionic#13234]
Hi,

I'm trying to set the allowBackup attribute in my app manifest to false but gradle complains with the following error:

Attribute application@allowBackup value=(false) from AndroidManifest.xml:4:18-45
        is also present at [:barcodescanner:] AndroidManifest.xml:12:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:4:5-11:19 to override.

To Set allowBackup=false using below line in config.xml file 
<platform name="android">
    <edit-config file="AndroidManifest.xml"
                 target="/manifest/application"
                 mode="merge">
        <application android:allowBackup="false"/>
    </edit-config>
</platform>

I use Barcode Scanner in my app.(Repo: [https://github.com/phonegap/phonegap-plugin-barcodescanner] recommended in [https:https://ionicframework.com/docs/native/barcode-scanner/]) 

I'm happy to provide more details or a PR if needed.

Thanks!

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
