### ISSUE TITLE
Change detection not firing in setTimeOut on android

### ISSUE THREAD

**Issue by rajeevriitm** [ionic-team/ionic#13230]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a list of cards which are swipable. When all the cards are swiped it shows a load more div. I have an animation after each swipe so I have to wait 300ms to wait before I remove card from view. I use setTimeOut here. 

This works fine in browser. But it doesnt work well on my phone on app  startup.The load more div doesnt show up even all the cards are swiped. It does work as indented without setTimeOut. I have  tested only on android. Wrapping the ```shift``` function in ```ngZone``` does trigger change detection.

**Steps to reproduce:**
1. have a list which can be removed through swipe.
2. make items remove after a setTimeOut delay.
3. show a load more div when list is empty

**Related code:**

```hunts``` represent the list here. ```
```
  reviewHunt(status: string){
    this.anim[0]= status;
    setTimeout( () => {
      this.anim[0]= undefined  ;
      let hunt = this.hunts.shift();
    })
  },300)
```
```
  <div   class="load-more" *ngIf="hunts.length == 0">
      <div class="load-text" *ngIf="!loading">
        No more hunts.
      </div>
  </div>
```

-->

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/home/raj/.nvm/versions/node/v7.9.0/lib/node_modules)

    @ionic/cli-utils  : 1.14.0
    ionic (Ionic CLI) : 3.14.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.5
    Node              : v7.9.0
    npm               : 5.4.2 
    OS                : Linux 4.4

Misc:

    backend : legacy

```

**Comment by KillerCodeMonkey** [comment]
when is `reviewHunt` called?

try to inject the `ChangeDetectorRef` from `@angular/core` and call it:

```
this.changeDetectorRef.detectChanges()
```

after 

```
let hunt = this.hunts.shift();
```

BTW: do not set variables to `undefined` --> use `null` instead ;)

**Comment by rajeevriitm** [comment]
```reviewHunt``` is called when when a ```swipe```  event happens.  Thats the ```throwOut``` event in template

`<div swing-stack #myswing1 [stackConfig]="stackConfig" (throwout)="throwout($event)"  id="card-stack">`

And btw does using null instead of undefined matter ?
