### ISSUE TITLE
Click function sanitized from dynamic content

### ISSUE THREAD

**Issue by butavpaul** [ionic-team/ionic#13239]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

In my app I have articles with multiple images. What I want is to tap on the image to view it full screen with a modal. The problem is that my app content is created dynamic and I had to sanitize the content. The content is displayed perfectly but the (click) event which was sent into a json and sanitized is not working. Inside the source I can see the (click) function but nothing is happening.
**Expected behavior:**

As I read about angular and Ionic DomSanitizer should do the trick and is for security purpose but even with this is not working.
**Steps to reproduce:**

**Related code:**

```
import { DomSanitizer } from '@angular/platform-browser';
constructor
(
   private sanitizer: DomSanitizer
) 
	this.http.get('')
		.map(res => res.json())
		 .subscribe(data => {
			this.article = this.sanitizer.bypassSecurityTrustHtml(data[7]);
			});
	});
```
inside my html page
```
<div [innerHTML]="article"></div>
```

data[7] looks something like this inside my php file
```
<img src="img.src" (click)="openModal()">
```
**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.15.0
    ionic (Ionic CLI) : 3.15.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v8.4.0
    npm  : 5.4.2 
    OS   : macOS Sierra

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

Perhaps something that just gets a sample article from a status JSON file or something simple like that.

Thanks for using Ionic!

**Comment by butavpaul** [comment]
Hi.  Sorry but after half an hour I didn't find out how to put it on git ...

**Comment by kensodemann** [comment]
@butavpaul - please let me know which part of putting a sample application in GitHub you are having problems with and I will try to get you pointed in the correct direction.

**Comment by butavpaul** [comment]
Hi, I think I succeded. Please check here an example
https://github.com/butavpaul/myapp/tree/master/src/pages/home
Thank you!

**Comment by p4u1d34n** [comment]
same here @butavpaul - i have a (click)="somefunc(someval)" in the HTML coming back from my API, and it too is ignored by Ionic ( after DomSanitizer ). I've spent a day on this so far.

Is this normal behaviour?

**Comment by butavpaul** [comment]
In ionic 1 it worked perfectly! Until now I didn’t find any solutions!

**Comment by jasonz1987** [comment]
in ngAfterViewInit function ,your can add these code to add click event in innerhtml

```
this.elRef.nativeElement.querySelector(yourdom).addEventlistner('click',this.someFunc.bind(this));
```

  but it's not a good solution to deal with param,so anyone else have better ways?
