### ISSUE TITLE
What about switching from  sw-toolbox to Workbox?

### ISSUE THREAD

**Issue by bogomips** [ionic-team/ionic#13236]
No one pointed this out, but it seems workbox is the new standard and I guess the replacement would be pretty easy.

**Comment by mhartington** [comment]
@bogomips Yes, we've talked about moving off of SW-toolbox to Workbox before internally. Since it is technically an issue in app-scritps, I'm going to close this for now. Can you open an issue on the app-scripts repo?

**Comment by bogomips** [comment]
Thanks for the fast answer, I will open it there right now.
