### ISSUE TITLE
Position: fixed not working after pull-to-refresh

### ISSUE THREAD

**Issue by JaneDawson** [ionic-team/ionic#13237]
**Ionic version:**
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
A div that is positioned with `position: fixed` is not fixed anymore, after doing a pull to refresh on this page.

**Expected behavior:**
`position: fixed` works before and after a pull-to-refresh-event

**Steps to reproduce:**
- starter template
- insert a div with `position: fixed`
- implement pull-to-refresh

**Related code:**

see sample-project on github: https://github.com/JaneDawson/maptest

**Ionic info:** 

```
cli packages:

    @ionic/cli-utils  : 1.15.0
    ionic (Ionic CLI) : 3.15.0

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.5
    Node              : v8.2.1
    npm               : 5.4.2
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Program Files (x86)\Android SDK

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by JaneDawson** [comment]
Hi @kensodemann. Thanks for looking into this. I already posted a link to a GitHub repository with a sample project. Please look at my initial post in section "related code". Thank you.

**Comment by kensodemann** [comment]
Doh! Missed that! Thank :)

**Comment by JaneDawson** [comment]
Any idea on this?

**Comment by JaneDawson** [comment]
There must be a solution to this... I can't leave it like this, but don't know any way around this...

**Comment by Kreedzt** [comment]
Same issue here, had solved?

**Comment by nadietta** [comment]
Hi, i'm facing the same issue too. Any news for that?
