### ISSUE TITLE
After Upgrading to Ionic Cli - 1.15.1 No Longer Detecting Changes

### ISSUE THREAD

**Issue by bkarv** [ionic-team/ionic#13249]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
In 1.15.0 and prior when I click save in my editor, the changes would be detected and my app would recompile. After upgrading to 1.15.1 its no longer compiling automatically. Terminal window does not sure the build start or anything. Only way to compile is to kill ionic serve and re-execute ionic serve. 

**Expected behavior:**
Should recompile when changes made and save in text editor. 

**Steps to reproduce:**

Upgrade to Ionic CLI 1.15.1

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.15.1
    ionic (Ionic CLI) : 3.15.1

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.1.2 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.1 
    Node       : v8.6.0
    npm        : 5.5.1 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0.1 Build version 9A1004 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro


```

I need to fix this asap. How would I downgrade back to 1.15.0??

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to close this as it is not an Ionic Framework issue but rather an Ionic CLI issue. There is already an existing issue open in the CLI repo for this: https://github.com/ionic-team/ionic-cli/issues/2832 so if you have any additional information to add, please add it to that issue.

> How would I downgrade back to 1.15.0

I believe this is done just like any other NPM installed program, so in this case it would be something like: `npm -g install ionic@3.15.0` (NOTE: the version of the CLI is `3.15.x` and not `1.15.x` which is actually the version of the CLI utilities (`@ionic/cli-utils`) which you do not install directly but are installed for you as part of the CLI install).

Thank you for using Ionic

**Comment by bkarv** [comment]
It was a bug issue, live reload was set to off as default. They have released another update to resolve the matter.
