### ISSUE TITLE
Remove 300ms delay when selecting ion-inputs

### ISSUE THREAD

**Issue by connor-odoherty** [ionic-team/ionic#13242]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When clicking between ion-inputs, there is a significant delay between selecting the input and the input becoming usable. Specifically, there is a 300ms delay. 

**Expected behavior:**

Users can switch between input fields without the usability-killing lag.

**Steps to reproduce:**

Make an Ionic 2 Angular 2 app with ios 10.3.x (also saw this issue on iOS 11). Create a ion-form using ion-items and ion-inputs. Attempt to move between these input fields. Suffer the lag.

**Related code:**

```
insert short code snippets here
```

**Other information:**

Both FastClick and wkwebview plugins solved this, but had disastrous side effects. FastClick made context menus unusable and disabled button animations, while wkwebview killed CORS. 

It would be nice if the 'tappable' flag on an ion-item actually made it tappable.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/connorodoherty/Projects/jetinsight-mobile-crew/node_modules)

    @ionic/cli-utils  : 1.14.0
    ionic (Ionic CLI) : 3.14.0

global packages:

    cordova (Cordova CLI) : 6.5.0 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : browser 4.1.0 ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    Node       : v8.5.0
    npm        : 5.3.0 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Ionic handled and removed the 300ms tap delay quite a while ago. You can read more about it here: http://blog.ionic.io/hybrid-apps-and-the-curse-of-the-300ms-delay/

And here is a tiny app that demonstrates that there is no delay: https://github.com/kensodemann/test-input

Thank you for using Ionic

**Comment by connor-odoherty** [comment]
Hi Ken,

This works on buttons, but NOT on ion-inputs. Fastclick and wkwebview both solved this issue, but have unusable side effects. This makes me think it is the 300ms delay.

On top of that, the 300ms delay shows when profiling the app. Again, this happens on ion-input, not on buttons.

Why is the delay still being fired on inputs, but not on buttons?

**Comment by kensodemann** [comment]
My sample app uses four `ion-input` items and has no delay so far as I can tell.

It also uses WKWebView, however, as that is the way forward and is now our default configuration.

What issues are you having with WKWebView?

**Comment by connor-odoherty** [comment]
Ahhh, there it is. Yeah, the UI worked great with WKWebView!

However, this broke CORS and XHR. So I was looking for an alternative to WKWebView and FastClick. Am I using the correct WebView: https://github.com/ionic-team/cordova-plugin-ionic-webview ?

Without WkWebVIew, your example still has the delay on iOS :(

**Comment by kensodemann** [comment]
Yes, that is the correct webview.

For the CORS issues, be sure to see here: http://ionicframework.com/docs/wkwebview/#cors

**Comment by connor-odoherty** [comment]
Is there a way to solve this delay issue without additional plugins? Implementing WKWebView would require a fairly big refactor, and I would prefer to not keep layering plugin upon plugin to get things working.

**Comment by kensodemann** [comment]
Not that I know of. I do know that there are several bugs with UIWebView that Apple is not likely to fix. I believe most of those revolve around scrolling related issues.

You may want to try asking around on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

**Comment by kensodemann** [comment]
If you stick with UIWebView, you may want to have a look at this to get around some of those other issues with UIWebView (mostly iOS11 related): https://github.com/ionic-team/ionic-site/issues/1286
