### ISSUE TITLE
Keyboard hiding the content until I type in something

### ISSUE THREAD

**Issue by ATakaSKY** [ionic-team/ionic#13240]
I have the following content for my login page:

```
  <ion-content class="login">
    

      <button class="menu-button" ion-button menuToggle>
       <ion-icon name="menu"></ion-icon>
      </button>

       <div class="space"></div> 
      <ion-grid>
        <ion-row>
          <ion-col col-12 text-center>
              <h1>
                Incredible Weather
              </h1>
          </ion-col>
        </ion-row>
        <ion-row>
          <ion-col col-12 text-center>
              <h2>
                SignIn to access
              </h2>
          </ion-col>
        </ion-row>
      </ion-grid>

       <!-- <ion-content>  -->
      <form #f="ngForm" (ngSubmit)="onSignIn(f)">
         <ion-grid>
          <ion-row>
            <ion-col col-10 offset-1> 
              <ion-list>
                <ion-item>
                  <ion-label floating>Username</ion-label>
                  <ion-input type="text" ngModel name="Mail" required></ion-input>
                </ion-item>

                <ion-item>
                  <ion-label floating>Password</ion-label>
                  <ion-input type="password" ngModel name="Password" required></ion-input>
                </ion-item>
              </ion-list>
             </ion-col>
          </ion-row>

          <ion-row>
            <ion-col col-10 offset-1> 
              <button ion-button block type="submit" [disabled]="!f.valid">Sign In</button>
             </ion-col>
          </ion-row>
        
        </ion-grid> 
      </form>

      
        <p style="text-align:center;color:#fff;">Please <a style="text-decoration:underline; color:greenyellow" (click)='signInPage()'>sign up</a> before loggin in.</p>
      

       <!-- </ion-content>  -->

  </ion-content>
```

Styling code:

```
page-signin {

    .scroll-content{
        background-image: linear-gradient(
            rgba(0, 0, 0, 0.45)
            ),url("../assets/imgs/weather.jpeg");
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size:cover;
        width:100%;
        padding-bottom: 0 !important;

    }

    .input-cover{
        position: static;
    }
    

    .button-full{
        position: fixed;
        bottom:0;
        left:0;        
    }

    .menu-button{
        position: absolute;
        top:20px;
        left:25px;
        box-shadow: none;
        margin:0;
        padding: 0;
        background: transparent;

        ion-icon{
            font-size:2.9em;
            color:greenyellow
        }
    }

    .item-md,.item-ios{
        background: none !important;
        color:#fff;
        padding-left: 0;
    }

    .item-input .label-md{
        color:#fff;//text on label
    }

    .item-input.item-input-has-focus .label-md[floating], .input-has-focus .label-md[floating]{
        color:#fff;
    }

    .item-md.item-input.item-input-has-focus.item-inner,.item-md.item-input.item-input-has-focus .item-inner{
        border-bottom-color: #fff;
        box-shadow: inset 0 -1px 0 0 #fff;
        color:#fff;
    }

    .list-md .item-input.item-input-has-focus:last-child,.list-md .item-input.input-has-focus:last-child{
         border-bottom-color: #fff;
        box-shadow: inset 0 -1px 0 0 #fff;
    }

    .space{
        padding-top:100px;
    }

    h1{
        margin-top: 2rem;
    font-size: 4rem;
    margin-bottom: 3rem;
    color: greenyellow;
    }

    h2{
        margin-top:0;
        font-size: 3rem;
        color:#fff;
    }

}
```

Now when I tap on any field keyboard shows up but doesn’t align the input well with the keyboard; it instead hides it and then when I start to type it pushes the content a towards the top.

Attaching some images for clarity:

**Initial Login screen:**

![login](https://user-images.githubusercontent.com/17201629/32018050-4433266a-b9e6-11e7-81c4-a3861273bf4b.png)

**When user taps on a field like username(hides the input):**

![tapkeyboardlogin](https://user-images.githubusercontent.com/17201629/32018070-57c7431e-b9e6-11e7-8b10-453253050a5e.png)

**When user starts typing(inputs moves a lot up):**

![typelogin](https://user-images.githubusercontent.com/17201629/32018101-6b7dd076-b9e6-11e7-8d3c-e02574804047.png)

It might be that I am not following proper ionic styling as this is one of my starter apps in ionic. It would be great if someone can point me in the right direction so that I can learn more and proceed.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Due to issues which are beyond our control (a lot of this has to do with the way the underlying web view chooses to do things), our general design advice is that screens be designed such that all inputs (or at least the inputs most likely to be entered first) be placed in the top 50% of the screen. 

Thank you for using Ionic

**Comment by ATakaSKY** [comment]
I did think that as a workaround. But what if user has more than say 3 or 4 inputs on a page. What would you suggest in that case?

**Comment by kensodemann** [comment]
So I wrote something up to test this out and try things, but I don't actually get the same issue you are getting: https://github.com/kensodemann/test-input

Give that a try and let me know if the scrolling is working fine for you.

My Android testing device is a Note 4 running Android 6.0.1, though I also tried it on an emulator with a newer version of Android. In both cases, the input scrolled into view nicely.

**Comment by ATakaSKY** [comment]
Thanks a ton @kensodemann . 
With your example I was able to come to a conclusion that `ion-grid` should not be used within the form as it caused the behavior of hiding the input behind the keyboard.

I removed the `ion-grid` and it works as in it works in your example.

**Comment by kensodemann** [comment]
Excellent!! I am going to close this then.
