### ISSUE TITLE
Rotate only status bar when app orientation set portrait on iOS

### ISSUE THREAD

**Issue by ckris** [ionic-team/ionic#13243]
**Ionic version:**
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request

I remove all node_modules and created new app after that get package.json and package-lock.json and install it but this won't fix status bar problem.

**cordova plugin list**
```
com-sarriaroman-photoviewer 1.1.10 "PhotoViewer"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-firebase 0.1.24 "Google Firebase Plugin"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
Status bar rotate when app is set portrait mode.

**Expected behavior:**
Do not rotate status bar

**Steps to reproduce:**
After load app in portrait when you rotate landscape orientation app is stay portrait but status bar is rotate to landscape tested on iOS 11

**Related code:**

![untitled](https://user-images.githubusercontent.com/2426479/32019149-f22b8062-b9d4-11e7-88a2-5237ef3b1bbf.jpeg)

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.15.1
    ionic (Ionic CLI) : 3.15.1

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.2.3 ios 4.5.2
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node  : v6.11.4
    npm   : 5.5.1 
    OS    : macOS High Sierra
    Xcode : Xcode 9.0.1 Build version 9A1004 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by ckris** [comment]
Hello I prepare simple app for testing this bug.

**Deployment info iPhone**
![deployment-info](https://user-images.githubusercontent.com/2426479/32070361-c1cbe7c0-ba94-11e7-8116-1f7a4c084452.jpeg)

**Deployment info iPad**

![deployment-info-ipad](https://user-images.githubusercontent.com/2426479/32070439-fdff784c-ba94-11e7-9c32-822c17b7eed3.jpeg)

**Simple app**
[simple.zip](https://github.com/ionic-team/ionic/files/1419615/simple.zip)

**Comment by ColDrekken** [comment]
Hello, is there a solution?

best

**Comment by brynner** [comment]
Some update?

**Comment by RobinGiel** [comment]
I'm also having this same problem :-( if somebody as any kind of solution to this problem, that would be awesome, otherwise I'm actively looking for ways to fix this myself ''work around'

**Comment by RobinGiel** [comment]
https://github.com/onmyway133/notes/issues/2 
Just remove this in plist:

<key>UIMainStoryboardFile</key>
    <string>Main</string>

go to the link for more info
