### ISSUE TITLE
ion-infinite-scroll's ionInfite event not triggered

### ISSUE THREAD

**Issue by bogdbo** [ionic-team/ionic#13252]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

Quickly scrolling to the bottom does not trigger `ionInfinite` event.

**Expected behavior:**

Scrolling to the bottom should trigger the `ionInfinite` event.

**Steps to reproduce:**

I am able to reproduce the issue on an Android device as well but it's much easier on the PC Web View.
On PC Web View: 
1. Have a view with `ion-infinite-scroll`
2. Press `spacebar` **once** and make sure the view is scrolled to the bottom. 
3. the `ionInfinite` event is not triggered (not triggered up from scroll-view.js `scrollCallback` function)

On Android it happens rarely and you just need to scroll very fast to the bottom. 

**Other information:**

A standard `onscroll` event handler attached to the scroll container is correctly triggered in the scenario described above. (press spacebar to scroll)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\redacted\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.1

System:

    Node : v8.4.0
    npm  : 5.3.0
    OS   : Windows 8.1
```

**Comment by Squiggle** [comment]
We can also reproduce this issue on iOS if you swipe and let go, allowing the 'momentum' to scroll all the way to the bottom.

**Comment by elmartino** [comment]
Same problem here, sometimes when scrolling very fast, the event is not fired.

**Comment by lostdev** [comment]
I've been trying different threshold values to counter the issue, but to no avail. I can definitely reproduce this consistently, and it's quite a disturbance for users.

**Comment by leongzw** [comment]
nobody is looking into such serious issue?

**Comment by FanYeeChok** [comment]
We are facing the same issue here. Any workaround?

**Comment by lostdev** [comment]
Seems like the ionic-team is focused on ionic4. I haven't seen any progress on my known issues for months `:(`.

**Comment by smxdevst** [comment]
Same here on any IOS device

**Comment by vibinflogesoft** [comment]
Ys same here.issue with ion-infinite event triggering

**Comment by lostdev** [comment]
FYI there [is a workaround](https://github.com/ionic-team/ionic/pull/14160). I implemented these changes directly in the compiled source and its been working for months now.

**Comment by vibinflogesoft** [comment]
@lostdev So Infinite issue is still remains on v3

**Comment by zarko-tg** [comment]
Sadly we're still observing this issue (tested in desktop Chrome) with ionic-angular 3.9.2. I even tried @lostdev's workaround but it didn't seem to make a difference.
Given the unpredictability of the event in question, the whole ion-infinite-scroll is basically broken for us :/
@mhartington Any buttons you can push over there?
