### ISSUE TITLE
pls include the package.json change in the latest changelog 

### ISSUE THREAD

**Issue by bogomips** [ionic-team/ionic#13256]
I know it takes a minute to check the repository's package.json,  but less expert users could have problem with it.

npm WARN ionic-angular@3.8.0 requires a peer of @angular/common@4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.8.0 requires a peer of @angular/compiler@4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.8.0 requires a peer of @angular/compiler-cli@4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.8.0 requires a peer of @angular/core@4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.8.0 requires a peer of @angular/forms@4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.8.0 requires a peer of @angular/http@4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.8.0 requires a peer of @angular/platform-browser@4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.8.0 requires a peer of @angular/platform-browser-dynamic@4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-gallery-modal@0.2.7 requires a peer of ionic-angular@3.6.0 but none is installed. You must install peer dependencies yourself.

**Comment by Sampath-Lokuge** [comment]
Yes, This is a very good suggestion.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Updated changelog and release note accordingly WRT Angular deps

Thank you for using Ionic
