### ISSUE TITLE
HandleOrientationChange breaks my app

### ISSUE THREAD

**Issue by tgensol** [ionic-team/ionic#13253]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request

**Current behavior:**
Since the update of my app to the 3.8.0, I got this error : 
`This.getContent().resize is not a function `

**Related code:**

![capture d ecran 2017-10-27 a 10 16 00](https://user-images.githubusercontent.com/7864896/32094378-dace6a02-baff-11e7-997a-93bfcd5c33a7.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0 ios 4.5.2
    Ionic Framework    : ionic-angular 3.8.0

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.2 
    Node       : v6.11.4
    npm        : 2.15.12 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.0.1 Build version 9A1004 

Environment Variables:

    ANDROID_HOME : /usr/local/opt/android-sdk

Misc:

    backend : legacy
```

Do I have to do a procedure to update to the 3.8.0 ? (More than the one in the Changelog)

Thanking you in advance,

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by tgensol** [comment]
After some tests, I found the error when I am using the super-tabs (https://github.com/zyra/ionic2-super-tabs), so it does not come from ionic-angular.

Sorry about that, 
Regards

**Comment by mhartington** [comment]
So good to close?
