### ISSUE TITLE
Modal locked when created in Observable

### ISSUE THREAD

**Issue by arkkanoid** [ionic-team/ionic#13257]
Hi, I'm trying to create a modal after an event of inAppBrowser is detected.
The result is that the modal view is "locked", in my console I can see the events when I press a button but the page is not modified (it should).

If I create the modal outside the observable it works as expected.

                       var modal = this.modalCtrl.create(OrderStatus,{order:order,  paymentData:data} );
                       var modalOpened = false;
                       browser.on('loadstart').subscribe(function(event){
                        console.log(event.url);
                         if (event.url.includes('status=ok') && !modalOpened){
                           modalOpened = true;
                           modal.present();  
                           browser.close();
                        
                         }else if (event.url.includes('status=ko')){
                           console.log('statusko');
                            browser.close();
                            this.transactionError();
                         }
                        
                       });

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
