### ISSUE TITLE
Update package.json to angular 4.4.6 in order to fix a bug in HttpClient

### ISSUE THREAD

**Issue by bogomips** [ionic-team/ionic#13266]
After Angular 4.3.6 the HttpErrorResponse (basically when the server returns a status that's not 2XX)
returns the server response as a string and not as an object (so it does not parse the json)

The regression issue is here:
https://github.com/angular/angular/issues/19103

the fix is here:
https://github.com/angular/angular/commit/269f5ac

Since from the angular changelog I don't see any breaking change, I think it would be useful to update the version in the ionic dependencies in order to solve it and avoid that users write custom (ugly) solutions as workaround.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This seems like a reasonable thing to look at possibly doing for the `3.9.0` release.

Thank you for using Ionic
