### ISSUE TITLE
bug: --prod build hangs at webpack started

### ISSUE THREAD

**Issue by yogeshkrishnani** [ionic-team/ionic#13264]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I build my proejct with --prod flag, It hangs at webpack started. Does not respond even after half an hour. 

Running app-scripts build: --prod --platform android --target cordova
[19:16:14]  build prod started ... 
[19:16:14]  clean started ... 
[19:16:14]  clean finished in 7 ms 
[19:16:14]  copy started ... 
[19:16:15]  copy finished in 1.40 s 
[19:16:15]  deeplinks started ... 
[19:16:16]  deeplinks finished in 521 ms 
[19:16:16]  ngc started ... 
[19:17:06]  ngc finished in 49.91 s 
[19:17:06]  preprocess started ... 
[19:17:06]  preprocess finished in 1 ms 
[19:17:06]  webpack started ... 

If I omit --prod flag, It works fine. 

My environment info -->

cli packages: 

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.1.2 ios 4.2.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.3
    Node              : v8.8.1
    npm               : 5.5.1 
    OS                : Linux 4.10</span>

<span is-issue-template></span>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This does not appear to be an Ionic Framework issue. It might be an issue with the Ionic CLI. I will move the issue over there for you. Please follow the newly created issue for updates.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2846
