### ISSUE TITLE
ionic3 webpack lazy loading 

### ISSUE THREAD

**Issue by elon-hu** [ionic-team/ionic#13268]
Sorry to disturb  @ionic-team。

My company use webpack to package our ionic app.

I know ionic-cli is a good tool, but we need to full control our project.

So, we can not use lazyloading in our ionic3 project.

I can not understand the principle of ionic3 lazyloading.

Can you give us a starter  of ionic3 webpack lazyloading?@ionic-team

Please!

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I will ask around a bit to see if someone can get you started on some stuff to look at.

That said, I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by danbucholtz** [comment]
@elon-hu,

Josh Moroney has written some good content on the topic:

https://www.joshmorony.com/what-does-lazy-loading-do-in-ionic/

This branch of a sample application also should give you some details:
https://github.com/ionic-team/ionic-conference-app/tree/lazy-load

We also have docs on the subject on the Ionic Framework site. I hope this helps.

Thanks,
Dan
