### ISSUE TITLE
ion-slides coverflow effect - incorrect perspective applied to transforms of ion-slide, suggested workaround

### ISSUE THREAD

**Issue by petemcwilliams** [ionic-team/ionic#13263]
**Ionic version:** 
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**
[ x ] bug report
[ ] feature request

**Current behavior:**
Incorrect perspective applied to transforms on slide elements becoming more pronounced as you move to later slides when using coverflow effect

**Expected behavior:**
same perspective applied to all slides

**Steps to reproduce:**
See plnkr below

**Related code:**
A workaround that resolves the issue for me is placing the following in app.scss (the parent element with class swiper-container-3d  already has perspective applied)
```
// Fix for swiper on coverflow, perspective needs to be in the parent element only.
.swiper-container-coverflow .swiper-wrapper,
.swiper-container-flip .swiper-wrapper {
    perspective: unset;
}
```

Here is a plnkr created by someone else that illustrates the problem quite well, see that the visible space between the 1st and 2nd slide is much smaller than the penultimate and last slides

https://embed.plnkr.co/p8GeoDf9jUXzm8Gtntkl/

**Ionic info:**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0 ios 4.5.2
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    Node       : v8.2.1
    npm        : 5.3.0 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by mateusmirandaalmeida** [comment]
Thank you, friend. I was looking for this.

**Comment by chickenduy** [comment]
Year I can confirm, that it also happens to me.
