### ISSUE TITLE
Print using thermal printer via bluetooth 

### ISSUE THREAD

**Issue by rohitwebethics** [ionic-team/ionic#13260]
Hello

I want to print using thermal printer via bluetooth in ioni1 without any print preview option while printing, How can i do this?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
