### ISSUE TITLE
Ionic Email trying to spam me

### ISSUE THREAD

**Issue by almgwary** [ionic-team/ionic#13269]
**Ionic version:**  (check one with "x")
No version
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**

this email sent to me, I think it is hacker . check the email source. it seems a spam, all the email links go to it .

 I know i shouldn't post this here, but i don't know where it should be . there is no email support found . 

![image](https://user-images.githubusercontent.com/7817756/32131720-7a1b293c-bbb5-11e7-85fe-0dfcb35b467f.png)

**Comment by Sampath-Lokuge** [comment]
No.I don't think it is a spam.Those are official emails.Me too got one and you can see the details of sender here. He is the Ionic team member.

**Twiter A/C of the sender:** [](https://twitter.com/brodymkidd?lang=en)

![](https://i.imgur.com/e0zGwnG.png)

**Comment by almgwary** [comment]
why are email links going to intercom.com ?! why sending  from strange domain ?! how should i know .
it should be form you original domain

**Comment by murraybauer** [comment]
intercom is a website live chat and customer communications product used but just about every startup I know.  Definitely not spam - also since it's about their own product :-)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Definitely not spam. I believe this communication went out to anyone who has signed up for an Ionic Pro account, be it a free one or a paid one, in order to help them to better utilize the services.

Thank you for using Ionic
