### ISSUE TITLE
Bug: Virtual scroll scrollToTop not found when I called this.content.scrollToBottom()

### ISSUE THREAD

**Issue by MrBokeh** [ionic-team/ionic#13275]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
_co.ScrollToTop not found on virtual scroll

**Expected behavior:**
It should scroll to the bottom if I called this.content.scrollToBottom()

**Steps to reproduce:**
1) use Virtual Scoll
2) Call the this.content.scrollToBottom() to scroll the page to the bottom

**Related code:**

```
this.content.scrollToBottom();
```

**Other information:**
N/A

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0 browser 5.0.1 ios 4.2.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    ios-deploy : 1.9.2 
    Node       : v8.7.0
    npm        : 5.4.2 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0.1 Build version 9A1004 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by MrBokeh** [comment]
Hi @kensodemann there you go:
https://github.com/MrBokeh/VirtualScrollSampleApp/
or
https://github.com/MrBokeh/VirtualScrollSampleApp/blob/master/src/pages/home/home.ts

**Comment by MrBokeh** [comment]
@kensodemann I am suspecting that if the items total height is less than the screen height then this problem will occur.

**Comment by kensodemann** [comment]
Duplicated. Marked as Virtual Scroll issue, and set to review after v4 is released.

**Comment by ghenry22** [comment]
Virtualscroll has known issues with scrollTo functions (be it top, bottom or co-ords) there have been tickets open for a long time for these.

WKWebview helps resolve some but then it also creates some of its own.  For example hitting a scrollToTop, Bottom etc while the view is scrolling will stop the current scroll but completely disregard the scrollTo request.
