### ISSUE TITLE
Toast flood

### ISSUE THREAD

**Issue by fttx** [ionic-team/ionic#13272]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ ] **3.x**
[x ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request

When i present multiple toasts while the app is paused once it resumes the toasts are shown all at once. Wouldn't it be better if the toasts presented while the app is in background or paused are ignored? Or maybe show only the last one?

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#324
