### ISSUE TITLE
URL is not changed after using a deeplink in a web app

### ISSUE THREAD

**Issue by ddahan** [ionic-team/ionic#13277]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
I'm using ionic deeplinks (or "dynamic links") in my application.
When browsing a page, the URL is changed. But when leaving this page (with a Push or a SetRoot), the old URLs stays forever.

**Expected behavior:**
The URL should go back to `/#/` after leaving the page.

**Steps to reproduce:**

**Related code:**

*app.module.ts*
```
    IonicModule.forRoot(MyApp, {
        backButtonText: 'Préc'
      },
      {
        links: [
          {
            component: ResetPasswordPage,
            name: 'ResetPasswordPage',
            segment: 'reset-password/:token/:uuid'
          },
          {
            component: FlashActivationPage,
            name: 'flash-activation',
            segment: 'flash-activation/:token/:uuid/:email'
          },
          {
            component: FeedbackPage,
            name: 'feedback-invitation',
            segment: 'feedback-invitation/:token/:uuid/:rating'
          },
        ]
      }
    ),
```

*Exemple of a page Declaration*

```
@IonicPage()
@Component({
  selector: 'page-feedback',
  templateUrl: 'feedback.html',
})
export class FeedbackPage {
```

**Other information:**

Note that I tried to followed the [official documentation](https://ionicframework.com/docs/api/navigation/IonicPage/) to implement dynamic links in a different way, but it didn't work at all so I stayed with the code above. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.15.1
    ionic (Ionic CLI) : 3.15.1

local packages:

    @ionic/app-scripts : 3.0.1
    Ionic Framework    : ionic-angular 3.8.0 (but same effect with 3.7.1)

System:

    Node : v8.7.0
    npm  : 5.4.2
    OS   : macOS High Sierra
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by ddahan** [comment]
Hi @kensodemann 
For now, sorry it's difficult to find the time to do this.
However, could you at least point any error or thing I could have forgotten in the code I provided?

In addition, where if the official doc about these deepklinks?
I read [this](https://ionicframework.com/docs/api/navigation/IonicPage/) but it's very different from what I currently have, and didn't work at all when I tested it.

There is a lot of confusion about how to implement deeplinks for a wep ionic app.
Please help to to achieve the simple "how-to" for this.

Reminder: I'm trying to make deeplinks for **web** application, I'm not using Cordova at all.

Thanks for your help.
