### ISSUE TITLE
ERROR in C:/Users/vadnu/Desktop/move/final-app/node_modules/firebase/index.d.ts (166,9): Type expected

### ISSUE THREAD

**Issue by vad1986** [ionic-team/ionic#13271]
My app was working fine on my old computer but when I bought a new one and opened it there,I started getting all sorts of Errors a especially with freebase components and most of them areinside node_modules which i have no idea what is going on inside!! I tried deleting node_modules and running npm install latest""  but it doesnt help...can anyone solve this ****???

 nextOrObserver:
        | firebase.Observer<any, any>     ON THIS LINE IT WANTS ME TO ADD TYPE BUT I DONT HAVE A CLUE
        | ((a: firebase.User | null) => any),
      error?: (a: firebase.auth.Error) => any,
      completed?: firebase.Unsubscribe
    ): firebase.Unsubscribe;

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
