### ISSUE TITLE
 git push error

### ISSUE THREAD

**Issue by ahevia2014** [ionic-team/ionic#13279]
Hello,
I bought a developer account in IONIC ans when i try to push my code, I'm getting follwing error:

$ git push ionic master
error: src refspec master does not match any.
error: failed to push some refs to 'git@git.ionicjs.com:ahevia2017/rtax.git'

 npm install -g ionic@latest and ionic link --pro-id f59db55d were OK.

Tks & BR
Andrés

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features.

This is an Ionic Pro issue, and thus should be handled via the [Ionic Pro Support Portal](http://support.ionicjs.com)

Thanks for using Ionic!

**Comment by kensodemann** [comment]
That said, based solely on the error you are getting, it looks like you have not committed anything to your local `master` repo. What are the results of the following commands: `git branch` and `git log`?

**Comment by Glennvanderstraeten** [comment]
the results are : git branch > * master
git log : Author ( my username ) <myemail@github.com>
date
initial commit

**Comment by Glennvanderstraeten** [comment]
I have the same problem
