### ISSUE TITLE
ion-select's selectedText does not clear if ngModel set to null in ionChange event

### ISSUE THREAD

**Issue by juanfq** [ionic-team/ionic#13289]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
In the ionChange event, if one wants to change ngModel back to the value it was before the change occurred, the value itself is changed back but the selectedText is not.
In my case, it's changing it back to null in which case I would want the selectedText to be cleared.

**Expected behavior:**
I would wish for the selectedText to reflect the ngModel value (blank for null or the option text for an existing item).

**Steps to reproduce:**
In the Plunker example, ngModel starts as null. if 'A' is selected, I'm changing ngModel back to null but 'AAAAAA' remains displayed. If one selects first 'B' then selects 'A', the selectedText is cleared as expected. It's only when changing ngModel to whatever it was before.
null --> 'A' --> null or 'B' --> 'A' --> 'B' will still display 'A' while the value of ngModel will reflect accurately.

**Related code:**
[Plunker example](http://embed.plnkr.co/2KVqL2ecColaXgzAfxWI?p=preview)

html
```
    <ion-select [(ngModel)]="data" (ionChange)="change($event)">
      <ion-option value="a">A</ion-option>
      <ion-option value="b">B</ion-option>
      <ion-option value="c">C</ion-option>
    </ion-select>
```
ts
```
  data: any = null;
  change($event) {
    if($event == 'a') {
      this.data = null;
    }
  }
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
cli packages: (C:\Users\Juan\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

local packages:

    @ionic/app-scripts : 3.0.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v6.10.2
    npm  : 5.3.0
    OS   : Windows 10

Misc:

    backend : legacy
```

**Comment by alexspring123** [comment]
I have same problem

**Comment by X2Style** [comment]
Same problem too
