### ISSUE TITLE
Auto complete input

### ISSUE THREAD

**Issue by kanelloc** [ionic-team/ionic#13286]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

Is there a way to generate an autocomplete input field in version 3? This would be a very convenient add on..

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. This feature request already exists as https://github.com/ionic-team/ionic-feature-requests/issues/281 (private repo). We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!
