### ISSUE TITLE
Can scroll content behind the overlay menu in iOS Safari

### ISSUE THREAD

**Issue by longgt** [ionic-team/ionic#13282]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Can scroll content behind the overlay menu in iOS Safari.

**Expected behavior:**
Can't scroll when the overlay menu is opened.

**Steps to reproduce:**

1. Show List page in Safari
2. Toggle Menu button
After menu is showed, the content behind backdrop can scroll.

**Related code:**

The same issue is marked as resolved and closed but still reproduce on the latest version.
https://github.com/ionic-team/ionic/issues/6656

A sample application via GitHub

https://github.com/longgt/ionic-virtual-scroll-demo

**Ionic info:**

```
cli packages

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 3.0.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v8.5.0
    npm  : 5.5.1
    OS   : Windows 7
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I have marked this as something to look at after the initial v4 release of Ionic. Here is what I have noticed the behavior is:

1. Issue _only_ occurs on iOS, not in browsers, and not on android
2. Issue _only_ occurs when you first open the menu. If you scroll then stop scrolling you can no longer scroll the background. If you rotate the device you can no longer scroll the background.

Thank you for using Ionic
