### ISSUE TITLE
Ionic Icons comes up blank squares

### ISSUE THREAD

**Issue by Drewdizzy** [ionic-team/ionic#13299]
Researched for solution with no luck.

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I generate the app using the ionic super template but the Ionicons on the all app appear as square blank when previewed on the  browser. Never had this issue before when I created a new project in the past.

**Expected behavior:**

Should show the right icons. A good example the origin tab view generated by ionic cli all four tabs appear as square blanks.

**Steps to reproduce:**

run ionic start to create a new app an voila no icons just plain boxes.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Please fill out the results of `ionic info` above. Perhaps this has something to do with your particular set up or mix of versions or something. I tried it on my machine and it worked just fine. Here is my info:

```
~/Projects/Issues/test-super (master *): ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

local packages:

    @ionic/app-scripts : 3.0.1
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v8.7.0
    npm  : 5.5.1 
    OS   : macOS Sierra

Misc:

    backend : pro
```

Thank you for using Ionic

**Comment by kubiq** [comment]
Hello, im also affected by thix bug, here is ionic info
```
$ ionic info

cli packages: (C:\Users\user\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.1.1
    Node              : v7.4.0
    npm               : 4.0.5
    OS                : Windows 7

Environment Variables:

    ANDROID_HOME : C:\Users\user\AppData\Local\Android\Sdk

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Tried the test again on Windows since that is the environment you are on. It worked just fine for me.

```
C:\Users\ken\Projects\Issues\test-super>ionic info

cli packages: (C:\Users\ken\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

local packages:

    @ionic/app-scripts : 3.0.1
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v8.7.0
    npm  : 5.4.2
    OS   : Windows 10

Misc:

    backend : pro
```

Browser difference maybe? Which one are you using? I tried Edge, Firefox, and Chrome. I even crossed over to the dark side and tried IE11. They all worked.

**Comment by kubiq** [comment]
Problem is only on iOS, when i deploy my app and view it in Ionic View app. It works just fine in chrome, firefox, edge on pc.

**Comment by kensodemann** [comment]
OK. That is different then as the OP states: "I generate the app using the ionic super template but the Ionicons on the all app appear as square blank when previewed on the browser"

Ionic View is part of Ionic Pro, so for issues that only occur in Ionic View I suggest logging an issue in the [Ionic Pro Support Portal](http://support.ionicjs.com)

**Comment by Drewdizzy** [comment]
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

local packages:

    @ionic/app-scripts : 2.0.1
    Ionic Framework    : ionic-angular 3.5.0

System:

    Node : v6.11.5
    npm  : 3.10.10
    OS   : macOS Sierra

Misc:

    backend : pro

**Comment by kensodemann** [comment]
How long ago did you generate this app? This seems kinda old:

```
@ionic/app-scripts : 2.0.1
Ionic Framework    : ionic-angular 3.5.0
```

Not sure if that has anything to do with the issue or not, just stuck out to me as odd if you recently generated the app.

Can you post your sample app to GitHub?

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!

**Comment by aelshemy16** [comment]
im stuck with this issue icons not apper

**Comment by sharonswli** [comment]
Having the same issue. Here is my ionic info

```
cli packages: (/path/to/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.5.0
```
And in case someone is wondering why our app script is so outdated, it's because of [build issues in app-scripts 2.0+ for larger apps](https://github.com/ionic-team/ionic-app-scripts/issues/1291) so we are still stuck in 1.x.
