### ISSUE TITLE
Core: inconsistent naming with enabled property

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic#13295]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

Some of our components (scroll, split pane, tab) use the `enabled` property with a default of `true`, but most of them (alert, button, checkbox, fab…) use `disabled` with a default of `false`.

These should be renamed to `disabled` with a default of `false`. Also look into what this property is actually doing to make sure they're all behaving the same.

**Comment by brandyscarney** [comment]
All of the `enabled` properties were renamed to `disabled` but these I am unsure of:

reorder

```
  /**
   * If true, the reorder will be hidden. Defaults to `true`.
   */
  @Prop() disabled = true;
```

refresher

```
  /**
   * If true, the refresher will be hidden. Defaults to `true`.
   */
  @Prop() disabled = true;
```

split pane

```

  /**
   * If true, the split pane will be hidden. Defaults to `false`.
   */
  @Prop() disabled = false;
```

infinite scroll

```
  /**
   * If true, the infinite scroll will be hidden and scroll event listeners
   * will be removed.
   *
   * Call `enable(false)` to disable the infinite scroll from actively
   * trying to receive new data while scrolling. This method is useful
   * when it is known that there is no more data that can be added, and
   * the infinite scroll is no longer needed.
   */
  @Prop() disabled = false;
```

When I think of the `disabled` property I think of how buttons are still visible but opaque. Should these be renamed something else like `show` (to match tabs)??

cc @manucorporat @mhartington @camwiegert

**Comment by danbucholtz** [comment]
I feel strongly that we should unify this and event names before we ship a beta (not necessarily alpha) of Ionic Core.


Thanks,
Dan

**Comment by camwiegert** [comment]
I agree that `disabled` doesn't accurately describe these. I tend to think we should have `show` and `hide` boolean props. So, elements that are hidden by default have an optional `show` prop and elements that are visible by default have an optional `hide` prop.
