### ISSUE TITLE
just builded IOS app seems to use old files

### ISSUE THREAD

**Issue by raphaelbadia** [ionic-team/ionic#13296]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

I'm trying to upload the latest version of my app on my iphone.
First, I build it with the prod flags and generate an .ipa file that I put on my server.
Then, I download the app from my iphone and install it.
When I open the app for the first time I get the expected behavior with the last features and design.
Then, if I kill the app and reopen it, I get an old version of the app.

**Expected behavior:**

The app should always be running the latest build.

**Steps to reproduce:**

I haven't found an easy way to reproduce it atm.

**Other information:**

It seems like a cache related issue but I don't know what to do.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/raphaelbadia/Desktop/ABCSalles_Mobile/node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.0.2
    ios-sim           : 6.1.2
    Node              : v8.6.0
    npm               : 5.3.0
    OS                : macOS Sierra
    Xcode             : Xcode 9.0.1 Build version 9A1004

Environment Variables:

    ANDROID_HOME : /Users/raphaelbadia/Library/Android/sdk

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by alhilali** [comment]
I'm having the same issue, I tried every possible solution I could think of and still couldn't fix it.
Have you figured it out? @raphaelbadia
