### ISSUE TITLE
Initial value property is not working OnInit of DateTime Component

### ISSUE THREAD

**Issue by Ane-tta** [ionic-team/ionic#13292]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ x ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

**Current behavior:**
When DateTime Component is initialized, the initial value is not being set until you open the drop-down of dates.

**Expected behavior:**
When DateTime Component is initialized, the initial value should be set without having to click on the drop-down.

**Steps to reproduce:**
Check Related code section below.

**Related code:**

**html**
`
<ion-datetime [initialValue]="initialDate"></ion-datetime>
`

**typescript**
```
export class SamplePage implements OnInit {

    currentDate: string;

    ngOnInit() {
        this.initialDate = utc().local().format();
    }

} 
```

**Other information:**
The initial value is being set in **Generate()**, which is being used in **Open()** but not in the **this._initialize**.

**Comment by patrickmcd** [comment]
You're (understandably) misunderstanding `initialValue` and should just use `ngModel`.

`initialValue` is meant to set the picker wheels / dropdown to a sensible starting spot while not affecting the data in the model. It's not meant to set the initial value of the `DateTime` as the property name implies, but of the picker when it opens.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

@patrickmcd is correct. I am going to close this.

Thank you for using Ionic
