### ISSUE TITLE
Relative paths not work.

### ISSUE THREAD

**Issue by vellengs** [ionic-team/ionic#13298]
The relative paths settings on tsconfig.json not works.
for example
```
   "baseUrl": "src/",
    "paths": {
      "@shared": ["app/shared"],
      "@shared/*": ["app/shared/*"],
      "@core": ["app/core/"],
      "@core/*": ["app/core/*"]
    }
```
I would like to use 
```
import { Settings, CoreModule, Item, Items, Api, User } from '@core/core.module';
```
instead of 
```
import { Settings, CoreModule, Item, Items, Api, User } from './core/core.module';

```

**Comment by vellengs** [comment]
#https://github.com/ionic-team/ionic-app-scripts/issues/678

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to close this as it is not an issue with the Ionic Framework, but rather with the Ionic App Scripts (build tools), and there is already a feature request out there where the utility of this feature is being debated.

Thank you for using Ionic
