### ISSUE TITLE
print something using thermal printer via bluetooth in ionic1

### ISSUE THREAD

**Issue by rohitwebethics** [ionic-team/ionic#13300]
i want to implement functionality in ionic1 to print something using thermal printer via bluetooth, please help.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
