### ISSUE TITLE
When using IonicPages and LazyLoading, the mode:"md" override in app.module is lost

### ISSUE THREAD

**Issue by cjdreiss** [ionic-team/ionic#13309]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
When using IonicPages with URLs and LazyLoading, the app mode does not stay in android/"md" on page transition.  Also the back button is no longer an icon, but the word "BACK".
I have set the mode to 'md' in my app.module, so even on iOS we will use Material Design.

`IonicModule.forRoot` allows for config options, but `IonicPage.forChild` does not, and it doesn't seem to respect the options I've put in the root module.

**Expected behavior:**
Navigating to a page would remain in Android/Material Design mode.

**Steps to reproduce:**
Set your app module to use mode:'md'. You will need to test in the browser, emulating an iOS device via chrome or on a real iOS device.  Navigate to a page by passing its component to the nav (this doesn't do deep linking or change the URL).  It will still be in Material Design mode. 

Then navigate to the same component by pushing the string name for the IonicPage instead of the component.  It will now have a "BACK" button instead of a back arrow, and the UI will be in iOS mode instead of 'md' mode.  

**Related code:**

```
//setting the whole app to use material design in app.modue.ts
IonicModule.forRoot(MyApp, {
      mode: 'md',
      ios: {
        scrollAssist: false,
        autoFocusAssist: false,
        inputBlurring: false
      }
    }),
```

```
/// navigating with a component will behave normally
goToCategory(category) {
    this.rootNavCtrl.push(MyPage, {
      'categoryId': category.id,
    });
  }
```

```
/// navigating with a string will properly set the URL but revert to iOS mode
goToCategory(category) {
     this.rootNavCtrl.push('my-page', {
        'categoryId': category.id,
   });
  }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/USERNAME/.nvm/versions/node/v7.10.0/lib/node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1 
    ios-sim           : 4.1.1 
    Node              : v7.10.0
    npm               : 2.15.12 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0.1 Build version 9A1004 

Environment Variables:

    ANDROID_HOME : /usr/local/opt/android-sdk

Misc:

    backend : legacy

```

Here's some screenshots of whats happening:
Main page, before nav:
![screen shot 2017-11-01 at 7 24 14 pm](https://user-images.githubusercontent.com/2102916/32302842-37af1642-bf3b-11e7-9feb-f45d09ed9efb.png)

Loading the secondary page with a component, this is the normal behavior, still in "md" mode.
![screen shot 2017-11-01 at 7 24 24 pm](https://user-images.githubusercontent.com/2102916/32302855-46a88962-bf3b-11e7-9a72-91353e27d2f3.png)

Here is it if we change to using a string instead of a component.  Notice the URL changes as well, but its now back in iOS mode.  You can tell because of "back" and the ion-segments are styled for iOS.
![screen shot 2017-11-01 at 7 28 24 pm](https://user-images.githubusercontent.com/2102916/32302870-6c03f264-bf3b-11e7-8504-8fb80512a2ea.png)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by cjdreiss** [comment]
So I've made a sample repo... it doesn't seem to exhibit the same behavior.  While I was adding pages via ionic g, it did do it until I imported the page.  I've just made another new repo and took a video of it happening.

It seems when first generating a page, it switches back to iOS mode.  If I then import the page module into app.module, it goes back to MD mode.  Then after removing that import again, it doesn't seem to do that anymore.

Maybe this means I missed an import somewhere (my app is pretty big in comparison to this sample).  

Here's the working repo which doesn't help much I suppose... https://github.com/cjdreiss/ionic-page-ignores-mode-example

Here's a video of it happening on a brand new project.  It only happens the first time, and it does it every time I make a new project.  https://youtu.be/EupmOgQKnfw  (you may need to wait for YouTube to process it so you can see the text)

We have a very large amount of non IonicPage pages and after finally getting them to work with URLs we are starting to use it, in our app.  Maybe the two are related somehow.

**Comment by cjdreiss** [comment]
So, I guess I'll just post some progress here as a go along in case anyone else has this issue.  If you notice in my broken screen shot, there are no stars.  The icons were coming up as `ion-null-star` for their icon name.  I found this https://forum.ionicframework.com/t/ion-icon-produce-ion-null-icon-resolved/93308/3 which mentioned one of their modules was "outside ionic".

I've confirmed that adding a new simple page that doesn't do anything seems to work.  I'll need to look at the broken pages in my app and see what could be wrong with them...

**Comment by kensodemann** [comment]
Noticed your sample app was not _actually_ using lazy loading due to loading by component as well as string. Created a PR just in case that is helpful in your real app. https://github.com/cjdreiss/ionic-page-ignores-mode-example/pull/1

**Comment by kensodemann** [comment]
I am going to close this then as it appears to not be an issue with the Ionic Framework.

The wierdness you are seeing when you add the page _may_ have to do with live-reload and the rebuilding being done there, _maybe_. If that is the case, then please write up an issue in the ionic-app-scripts repo.

If you do find something Ionic Framework related as it pertains to this issue, let me know and I will certainly reopen this.

**Comment by cjdreiss** [comment]
@kensodemann I was able to get it to break in my sample app.

The difference between my sample app with working pages, and my real app is that I have a shared module with components.  They need IonicMoule.forRoot in one of them because I use built in ionic directives.  

I've just added that example to my master branch, and it does indeed break it.

Master, broken branch: https://github.com/cjdreiss/ionic-page-ignores-mode-example

Working branch, but no ionic directives can be used: https://github.com/cjdreiss/ionic-page-ignores-mode-example/tree/working-with-non-ionic-component

Is this a bug with Ionic, or am I just not making my modules correctly?  When I use things like `ion-spinner` or `ion-icon` in my directives, if I don't import IonicModule.forRoot(ComponentName) in the module, I get runtime errors.

**Comment by kensodemann** [comment]
I'll have a look a bit later today.

**Comment by kensodemann** [comment]
Your problem is here:

```ts
import { NgModule } from '@angular/core';
import { ComponentThatNeedsIonicComponent } from './component-that-needs-ionic/component-that-needs-ionic';
import { IonicModule } from 'ionic-angular';
@NgModule({
	declarations: [ComponentThatNeedsIonicComponent],
	imports: [IonicModule.forRoot(ComponentThatNeedsIonicComponent)],
	exports: [ComponentThatNeedsIonicComponent]
})
export class ComponentsModule {}
```

as the name implies, `forRoot` should only be used in the root module (`AppModule` in this case).

Just remove that bit, and you should be fine:

```ts
import { NgModule } from '@angular/core';
import { ComponentThatNeedsIonicComponent } from './component-that-needs-ionic/component-that-needs-ionic';
import { IonicModule } from 'ionic-angular';
@NgModule({
	declarations: [ComponentThatNeedsIonicComponent],
	imports: [IonicModule.forRoot(ComponentThatNeedsIonicComponent)],
	exports: [ComponentThatNeedsIonicComponent]
})
export class ComponentsModule {}
```

**Comment by cjdreiss** [comment]
Thanks so much!  I verified that it works in my sample app.  I had tried it before, but I realized my team and I had done it in many random places, and that my Find in path settings was filtering out some of them... 

Glad I finally asked, this had been driving me crazy for a few days now!
