### ISSUE TITLE
<ion-buttons> on fresh install

### ISSUE THREAD

**Issue by szorfein** [ionic-team/ionic#13301]
Hi, i have a problem with ion-buttons on fresh install.

So, i install last version of ionic & cordova.

```
$ sudo npm install -g cordova
$ sudo npm install -g ionic
```
Which install: ionic-3.15.2 & cordova 7.1.0
I create a new project:

```
$ ionic start ionictest blank --cordova --skip-link
```

Edit the `src/pages/home/home.html` and change that:
```
<ion-header>
  <ion-navbar>
    <ion-title>
      Ionic Blank
    </ion-title>
    <ion-buttons></ion-buttons>
  </ion-navbar>
</ion-header>
```
Launch app:

```
$ ionic serve
```
After somes time, the error appear to `http://localhost:8100`:

---
Runtime Error
---
```
Template parse errors: Unexpected closing tag "ion-buttons". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (" Ionic Blank </ion-title> <ion-bumadblons>[ERROR ->]</ion-buttons> </ion-navbar> </ion-header> "): ng:///AppModule/HomePage.html@5:20 Unexpected closing tag "ion-navbar". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (" </ion-title> <ion-bumadblons></ion-buttons> [ERROR ->]</ion-navbar> </ion-header> "): ng:///AppModule/HomePage.html@6:2 Unexpected closing tag "ion-header". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (" <ion-bumadblons></ion-buttons> </ion-navbar> [ERROR ->]</ion-header> <ion-content padding> "): ng:///AppModule/HomePage.html@7:0
```
---
Stack
---
```
Error: Template parse errors:
Unexpected closing tag "ion-buttons". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("
      Ionic Blank
    </ion-title>
    <ion-bumadblons>[ERROR ->]</ion-buttons>
  </ion-navbar>
</ion-header>
"): ng:///AppModule/HomePage.html@5:20
Unexpected closing tag "ion-navbar". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("
    </ion-title>
    <ion-bumadblons></ion-buttons>
  [ERROR ->]</ion-navbar>
</ion-header>

"): ng:///AppModule/HomePage.html@6:2
Unexpected closing tag "ion-header". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("
    <ion-bumadblons></ion-buttons>
  </ion-navbar>
[ERROR ->]</ion-header>

<ion-content padding>
"): ng:///AppModule/HomePage.html@7:0
    at syntaxError (http://localhost:8100/build/vendor.js:78265:34)
    at DirectiveNormalizer.normalizeLoadedTemplate (http://localhost:8100/build/vendor.js:90859:19)
    at http://localhost:8100/build/vendor.js:90845:76
    at Object.then (http://localhost:8100/build/vendor.js:78254:143)
    at DirectiveNormalizer.normalizeTemplateOnly (http://localhost:8100/build/vendor.js:90845:26)
    at DirectiveNormalizer.normalizeTemplate (http://localhost:8100/build/vendor.js:90827:36)
    at CompileMetadataResolver.loadDirectiveMetadata (http://localhost:8100/build/vendor.js:91859:75)
    at http://localhost:8100/build/vendor.js:103543:72
    at Array.forEach (<anonymous>)
    at http://localhost:8100/build/vendor.js:103542:72
Ionic Framework: 3.8.0
Ionic App Scripts: 3.0.1
Angular Core: 4.4.4
Angular Compiler CLI: 4.4.4
Node: 8.5.0
OS Platform: Linux 4.5
Navigator Platform: Linux x86_64
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.105 Safari/537.36 Vivaldi/1.92.917.43
```

It's frustrating to start ionic with that :-(.

**Comment by pwespi** [comment]
Take a look at your error:
`<ion-bumadblons>[ERROR ->]</ion-buttons>`

Try replacing `ion-bumadblons` with `ion-buttons`. ;-)

**Comment by szorfein** [comment]
the problem is here, i never wrote `<ion-bumadblons>` anywhere, the only change i made is to add `<ion-button></ion-buttons>` to `src/page/home/home.html`

**Comment by kensodemann** [comment]
I am going to close this as something that I cannot duplicate.

If you can provide a sample application via GitHub or https://stackblitz.com that duplicates this issue I will be happy to reopen the issue and have a look.

Also, you say:

> After somes time, the error appear

How much time? Were you just sitting there when the error occurred or did you have to do something to trigger it? Or are you just saying it occurs after the time it takes for `ionic serve` to start serving? I am not really sure on exactly what you mean, so some clarification there may help.

**Comment by szorfein** [comment]
Ok, i upload code [here](https://github.com/szorfein/penthotal)

**Comment by kensodemann** [comment]
@szorfein - is there something I need to do to trigger the error? Because I cloned your repo, and everything works fine when I run it.

**Comment by szorfein** [comment]
Thx for reply.  the error comes to me when ionic serve finish to start.  
you are luckier than me :), maybe i need clear somes cache file?, i have try to delete the directory `node_modules` and reinstalls all dependencies with `npm install` but no change.

**Comment by kensodemann** [comment]
I wonder if there is something platform specific going on here. What is your platform? Run `ionic info` from the command prompt within the project's directory and paste the output here like this:

```~/Projects/Issues/penthotal (master *): ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

local packages:

    @ionic/app-scripts : 3.0.1
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v8.9.0
    npm  : 5.5.1 
    OS   : macOS Sierra

Misc:

    backend : pro
```

Another option could be local changes you don't know about. You should be able to find those via `git status`:

```
~/Projects/Issues/penthotal (master): git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by szorfein** [comment]
`ionic info`:
```
TypeError: Cannot read property 'toLowerCase' of undefined
    at ary.sort (/home/izsha/node_modules/ionic/dist/commands/info.js:25:75)
    at Array.sort (native)
    at splitInfo (/home/izsha/node_modules/ionic/dist/commands/info.js:25:18)
    at InfoCommand.<anonymous> (/home/izsha/node_modules/ionic/dist/commands/info.js:34:50)
    at Generator.next (<anonymous>)
    at fulfilled (/home/izsha/node_modules/ionic/node_modules/tslib/tslib.js:100:62)
    at <anonymous>
``` 
 
```
cli packages: 

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2
 
local packages:
    
    @ionic/app-scripts : 3.0.1
    Ionic Framework    : ionic-angular 3.8.0

System:
    node -v ( 8.5.0 )
    npm -v  ( 5.3.0 )
    OS : gentoo hardened
```

**Comment by kensodemann** [comment]
Weird that `ionic info` does not work for you... I grabbed my Linux machine to give it a try and just to rule out some sort of weirdness with Linux itself. It worked fine:

```
~/Projects/Issues/penthotal (master *): ionic info

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

local packages:

    @ionic/app-scripts : 3.0.1
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v8.6.0
    npm  : 5.5.1 
    OS   : Linux 4.10

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
One thing I notice in your case is the path in the error message: `/home/izsha/node_modules/ionic/dist/commands/info.js`

With a proper global install of `ionic` I would have expected something a little more global. 

Example: 

```bash
~/Projects/Issues/penthotal (master *): ls -l `which ionic`
lrwxrwxrwx 1 root root 35 Nov  1 12:24 /usr/bin/ionic -> ../lib/node_modules/ionic/bin/ionic
```
I wonder if you are not dealing with conflicting installs of the Ionic CLI. One that is global in `/usr/local` and one that is in your `home` directory. It may be worth researching a bit down that path.

**Comment by szorfein** [comment]
> I wonder if you are not dealing with conflicting installs of the Ionic CLI.

I suspect that too, i will search, remove and reinstall ionic, we'll see. thx for the advice :)

**Comment by szorfein** [comment]
I have remove all content in `~/.node_modules` and `/usr/lib/node_modules`.
Then reinstall cordova, ionic.   

Now `ionic info` work :)
```
cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node              : v8.5.0
    npm               : 5.3.0
    OS                : Linux 4.5

Misc:

    backend : legacy

```
but always the same error when `ionic serve` has start.

**Comment by kensodemann** [comment]
Progress!! :)

Did you ever do a `git status` in the project directory just to make sure what you put out the GitHub is the same as what is on your file system? If so, and it does, then I am totally out of ideas.

**Comment by szorfein** [comment]
yaa no problem with git, i always make a `git add .` before commit :)  
And for this error (which is really strange...), im out of idea too, i would look a bit of research tomorrow, and try other thing than ionic if no success :(  
thx for you help.

**Comment by kensodemann** [comment]
You're welcome.

**Comment by szorfein** [comment]
Just to say if someone look, this error is entirely from my side, related to my proxy which denied http://localhost:8100.
However all content on http://127.0.0.1:8100 work fine... (...) :)
