### ISSUE TITLE
DateTime component not showing the active date when using onPush as ChangeDetectionStrategy

### ISSUE THREAD

**Issue by cesareian** [ionic-team/ionic#13303]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When a component is using OnPush as a change detection strategy, the default value of the DateTime component is not showing until the user chooses another date

**Expected behavior:**
When a component is using OnPush as a change detection strategy, the default value of the DateTime component should be shown immediately without having the user to choose another date

**Steps to reproduce:**
Check attached stackblitz link

**Related code:**

https://stackblitz.com/edit/ionic-oxa8ss

The code change is done in **home.ts** and **home.html**

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I have marked this as something to have a look at after the initial Ionic v4 release.

Thank you for using Ionic
