### ISSUE TITLE
change ion-option background color dynamically

### ISSUE THREAD

**Issue by jshupptechnologies** [ionic-team/ionic#13302]
I want to change 'ion-option' background color.
i was tried : 

<ion-option [ngStyle]="{ color: color.name, backgroundColor: color2 }">Hello</ion-option>
also tried [style] attribute & inline stylesheet but didn't work.

can anyone suggest how to change background color in ion-option.?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by jshupptechnologies** [comment]
@kensodemann  Thank you for quick reply.

**Comment by kuzun9x** [comment]
@jshupptechnologies Have you found out solution for this topic?

**Comment by jshupptechnologies** [comment]
@kuzun9x No but ended up using custom component.
