### ISSUE TITLE
BrowserAnimationsModule

### ISSUE THREAD

**Issue by marwa1994** [ionic-team/ionic#13305]
i try 

  i try to import BrowserAnimaionModule in my project
1- i install   npm install web-animations-js @angular/animations@4.0.0 --save 
2- i import polyfill   in main.ts      import 'web-animations-js/web-animations.min'; 
3- and when i try to add BrowserAnimationModule in app.module.ts into imports[] i got this error Object prototype may only be an Object or null: undefined

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

If this does turn out to be an issue with the Ionic Framework itself (that is, with `ionic-angular`), please open a new issue with the template fully filled out, and with a sample application that duplicates the issue you are having.

Thanks for using Ionic!
