### ISSUE TITLE
No statusbar padding-top on Android

### ISSUE THREAD

**Issue by fcraveiro** [ionic-team/ionic#13312]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Ionic version: (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] 2.x
[ x ] 3.x
[ ] 4.x

I'm submitting a ... (check one with "x")
[ x ] bug report
[ ] feature request

Current behavior:
The status bar overlaps with the header on an  LG X Power android 6.0.1

Expected behavior:

The header should have the correct top padding so the text does not overlap.

Steps to reproduce:

Create a new app with ionic start myApp blank
Add cordova statusbar

![sem titulo](https://user-images.githubusercontent.com/31604881/32311491-04be89d0-bf80-11e7-9562-021d377bec4b.jpg)

Add color to status bar
```
  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
    platform.ready().then(() => {
      statusBar.overlaysWebView(true); 
      statusBar.backgroundColorByHexString('#007ac1'); <--- color
      splashScreen.hide();
    });
  }
```

Build with Ionic and test on LG Xpower

In ionic serve or  DevApp does not happen because they do not show color in the status bar

![screenshot_2017-11-02-01-43-16](https://user-images.githubusercontent.com/31604881/32308952-aa17196c-bf6f-11e7-97d0-69621120a8c0.png)   NORMAL

![screenshot_2017-11-02-01-43-31](https://user-images.githubusercontent.com/31604881/32308965-ba5e263a-bf6f-11e7-97bc-305e00a160a5.png) ROTATE (BUG)

![screenshot_2017-11-02-01-43-40](https://user-images.githubusercontent.com/31604881/32308974-c643cc02-bf6f-11e7-8f00-3e2894acc986.png) RETURN (BUG) Don't back to normal

INFO

```
cli packages: (C:\Users\cfc\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.4
    npm               : 3.10.10
    OS                : Windows 7

Environment Variables:

    ANDROID_HOME : C:\Users\cfc\AppData\Local\Android\sdk

Misc:

    backend : pro

**Comment by kensodemann** [comment]
NOTE: edited the OPs post just to have the proper back-tick markdown so the `ionic info` and `package.json` stuff was readable.

**Comment by kensodemann** [comment]
I have found that it works perfectly on Android if you remove `status/bar.overlaysWebView(true)`

If you need it set to true for some cases, perhaps just set it true for those cases?

```ts
  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
    platform.ready().then(() => {
      statusBar.backgroundColorByHexString('#007ac1'); <--- color
      splashScreen.hide();
    });
  }
```

Please let me know if this works for you as well.

**Comment by fcraveiro** [comment]
Hi kensodemann !!
grateful for your help !!
I had done a test based on an answer for iphone, put the field as "false" and it worked, but all my apps in previous versions worked like the one described above, as I did not see any comment regarding this change I decided to describe the problem.
Thnaks again

**Comment by kensodemann** [comment]
Hello! Since this appears to be solved, I am going to close this issue.

Thanks for using Ionic!

**Comment by SteveBunlon** [comment]
Hello !

As @fcraveiro said, suddently my app had the same behavior. I didn't change anything in my app config and the header went under the status bar. 

As @kensodemann pointed out, removing the status/bar.overlaysWebView(true) worked for I android. 

I Hope this will help.

Thanks !
