### ISSUE TITLE
Navbar Margin breaks on rotate

### ISSUE THREAD

**Issue by HJBWeb** [ionic-team/ionic#13316]
**Ionic version:**
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request

**Current behavior:**
https://i.imgur.com/qEZsObj.gifv

**Expected behavior:**
Regular margin and navbar. Margin needs to return when returning to previous page.

**Steps to reproduce:**
When I enter a page using navPush, rotate while on said page and then go back to the previous page, the content margin does not return, meaning the navbar appears "inside" the page content. As long as the page rotates at least once it will break, rotating back to the original position does not change the effect.

You can see in the inspector at the bottom that margin-top is not added back to the content.

It's built on the navbar example, with tabs added. The "Task Information" page is linked using navPush.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\***\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.15.0
    ionic (Ionic CLI) : 3.15.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v6.11.4
    npm  : 3.10.10
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\***\AppData\Local\Android\android-sdk

Misc:

    backend : pro


```

**Comment by mhartington** [comment]
Can you update to 3.8.0, this should be fixed in that release

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
