### ISSUE TITLE
Revealing more options on image cards

### ISSUE THREAD

**Issue by felix9607** [ionic-team/ionic#13315]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request

**Current behavior:**
Well it Shows the Image in the Background and the text above and that's all fine so far.

**Expected behavior:**
[See 'Card Reaveal' Sektion](http://materializecss.com/cards.html)

This offers a Little more interaction possibilitys, since they look very nice on a main page.

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#325
