### ISSUE TITLE
setRoot from Tab1 to Tab2 

### ISSUE THREAD

**Issue by Prudhvirajdandi** [ionic-team/ionic#13314]
In Ionic 3…
i am having 2 Tabs

Tab1 contains 4 pages
Tab2 Contains 5 pages…

i am setRoot from Tab1 to Tab2 … i am getting Tab2 is active but Tab1 pages also Exists here & there are also displaying

How to setRoot completely from Tab1 to Tab2 without strucking the pages ?

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please.

Also, please provide a sample application via GitHub that demonstrates the issue you are having.

Thanks for using Ionic!

**Comment by Prudhvirajdandi** [comment]
Can i have one example please.. felix9607

**Comment by Prudhvirajdandi** [comment]
In Ionic 3…
i am having 2 Tabs

Tab1 contains 4 pages
Tab2 Contains 5 pages…

i am setRoot from Tab1-2nd Page to Tab2-total AllPages is my requirement … i am getting Tab2-1st Page only is active and remaining pages are Tab1 pages

How to setRoot completely from Tab1 to Tab2 without strucking the pages ?
