### ISSUE TITLE
Error Keyboard

### ISSUE THREAD

**Issue by iaronrp** [ionic-team/ionic#13322]
Hi
I'm having trouble on an ion-input,
I click on it it opens the keyboard, I close the keyboard and try to click again it will not, what can it be?

Sorry, Iam BR

**Ionic version:**  (check one with "x")

[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please.

Also, please include a sample application shared via GitHub that demonstrates the issue you are having.

Thanks for using Ionic!
