### ISSUE TITLE
Home bar and ion-footer overlap iPhone X landscape mode

### ISSUE THREAD

**Issue by EWBears** [ionic-team/ionic#13321]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
As seen in screenshot, I have a navigation bar (attached code below) in my ion-footer element and the home bar is obscuring the menu button in the center.  I am using the updated cordova-statusbar plugin which hides the statusbar on iPX landscape mode, but this bug occurs with old statusbar plugin and no statusbar plugin as well.

**Expected behavior:**
Padding/safe space will shift footer element above home bar

**Steps to reproduce:**
Use my footer code (below) and run on iPX in simulator

**Related code:**

```
<ion-footer>
    <ion-grid no-padding class="navbar">
        <ion-row>
          <ion-col>
            <button ion-button small block>
              <ion-icon name="arrow-back"></ion-icon>
            </button>
          </ion-col>
          <ion-col>
            <button ion-button small block>
              <ion-icon name="menu"></ion-icon>
            </button>
          </ion-col>
          <ion-col>
            <button ion-button small block>
              <ion-icon name="arrow-forward"></ion-icon>
            </button>
          </ion-col>
        </ion-row>
      </ion-grid>
</ion-footer>
```

**Other information:**
N/A

**Ionic info:**

```
cli packages:

    @ionic/cli-utils  : 1.14.0
    ionic (Ionic CLI) : 3.14.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0 ios 4.5.1
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2 
    Node              : v8.6.0
    npm               : 5.5.1 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy
```
![simulator screen shot - iphone x - 2017-11-02 at 21 43 20](https://user-images.githubusercontent.com/22261870/32358026-75ae4d90-c018-11e7-9461-0f74dc3a50c6.png)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Duplicated with the sample code you have above. Repo is here: https://github.com/kensodemann/test-iphonex

Thank you for using Ionic

**Comment by kensodemann** [comment]
I take that back. Your footer is not wrapped in `ion-toolbar`, which per [the documentation](http://ionicframework.com/docs/api/components/toolbar/Footer/) is what makes sure it sizes correctly, which includes sizing for this case.

Wrap your grid as such in the footer, and you will be fine:

```ts
<ion-footer>
  <ion-toolbar>
    <ion-grid no-padding class="navbar">
      <ion-row>
        <ion-col>
          <button ion-button small block>
            <ion-icon name="arrow-back"></ion-icon>
          </button>
        </ion-col>
        <ion-col>
          <button ion-button small block>
            <ion-icon name="menu"></ion-icon>
          </button>
        </ion-col>
        <ion-col>
          <button ion-button small block>
            <ion-icon name="arrow-forward"></ion-icon>
          </button>
        </ion-col>
      </ion-row>
    </ion-grid>
  </ion-toolbar>
</ion-footer>
```

Note that you may need to do a little extra styling to get it to look the way you want, but that is the correct way to deal with this.

Closing this, but will reopen if you can't get that to work for some reason.

**Comment by kensodemann** [comment]
Pushed above fix the repo I reference for this Issue

**Comment by EWBears** [comment]
Sorry for the mistake, Ken.  I’ll make sure to check the documentation better next time. Thanks for looking into this!
