### ISSUE TITLE
Angular 5 support

### ISSUE THREAD

**Issue by ivarkallejarv** [ionic-team/ionic#13326]
**Ionic version:**  (check one with "x")
"ionic-angular": "3.8.0"

**I'm submitting a ...**  (check one with "x")
[x] feature request

**Current behavior:**
ionic-angular doesn't support Angular 5, lots of small fixes that need to be done -
fonts need font type, some performance problems and so on 

**Expected behavior:**
Angular 5 is supported

**Steps to reproduce:**
Update to Angular 5

**Other information:**
https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced

**Comment by danielsogl** [comment]
Duplicate of #13310
You can close your opened issue. 

Thanks

**Comment by ivarkallejarv** [comment]
Sure, weird that search didn't show that, thanks anyway.

**Comment by ericis** [comment]
#13310 is closed @danielsogl
