### ISSUE TITLE
camera capture image & image picker selected image not view in UI iOS.

### ISSUE THREAD

**Issue by nirav4273** [ionic-team/ionic#13330]
i am using ionic 3.6
when i was capture image via camera plugin not able to view in UI
Tried source Type : FILE_URL,NATIVE_URI

same issue with image picker plugin.

not able to view selected image in UI which i was selected from gallery.
can any suggest solution for iOS ?

in android it's working file with FILE_URL.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
