### ISSUE TITLE
Typescript and ionic serve error

### ISSUE THREAD

**Issue by theparmis** [ionic-team/ionic#13338]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x] **2.x**
[ ] **3.x**
[ ] **4.x**

**Current behavior:**
When i run "ionic serve" i got this : 

> ionic-hello-world@ ionic:serve /mn/hamid
> ionic-app-scripts serve "--v2" "undefined" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"

[05:07:39]  ionic-app-scripts 1.2.2 
[05:07:39]  watch started ... 
[05:07:39]  build dev started ... 
[05:07:39]  clean started ... 
[05:07:39]  clean finished in 5 ms 
[05:07:39]  copy started ... 
[05:07:39]  transpile started ... 
[05:07:43]  typescript: src/pages/cart/cart.ts, line: 277 
            Argument of type '{ message: any; cssClass: string; buttons: ({ text: any; cssClass: string; handler: () => 
            void; }...' is not assignable to parameter of type 'AlertOptions'. Types of property 'buttons' are 
            incompatible. Type '({ text: any; cssClass: string; handler: () => void; } | { text: any; handler: () => 
            void; })[]' is not assignable to type '(string | AlertButton)[]'. Type '{ text: any; cssClass: string; 
            handler: () => void; } | { text: any; handler: () => void; }' is not assignable to type 'string | 
            AlertButton'. Type '{ text: any; cssClass: string; handler: () => void; }' is not assignable to type 'string 
            | AlertButton'. Object literal may only specify known properties, and 'cssClass' does not exist in type 
            'string | AlertButton'. 

     L276:  text: this.trans['confirm']["no"],
     L277:  cssClass: 'dark',
     L278:  handler: () => {
.
..
....
And Erros continues 

While running "npm install typescript@2.3.4" give me :
└── UNMET PEER DEPENDENCY typescript@2.3.4

<code>I tired npm install, removing typescript, removing "@angular/cli", removing node_moduels install them again, test npm 5, test node 9, test typescript @2.6 noting changed.</code>

Running " ionic-app-scripts build --prod "--release" give me:

/usr/local/lib/node_modules/@angular/compiler/bundles/compiler.umd.js:723
    var /** @type {?} */ isDefaultChangeDetectionStrategy = _angular_core.__core_private__.isDefaultChangeDetectionStrategy;
                                                                                          ^

TypeError: Cannot read property 'isDefaultChangeDetectionStrategy' of undefined
    at /usr/local/lib/node_modules/@angular/compiler/bundles/compiler.umd.js:723:91
    at /usr/local/lib/node_modules/@angular/compiler/bundles/compiler.umd.js:7:68
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/compiler/bundles/compiler.umd.js:10:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

ionic info : 
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.2
ios-deploy version: 1.9.2 
ios-sim version: 6.1.2 
OS: macOS High Sierra
Node Version: v6.11.0
Xcode version: Xcode 9.0 Build version 9A235
npm : 3.10.10
Angular CLI: 1.5.0
Node: 6.11.0
OS: darwin x64
Angular: 2.4.8
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, platform-server

@ angular/cli: 1.5.0
@ angular/tsc-wrapped: 4.4.6
@ angular-devkit/build-optimizer: 0.0.32
@ angular-devkit/core: 0.0.20
@ angular-devkit/schematics: 0.0.35
@ angtools/json-schema: 1.1.0
@ angtools/webpack: 1.8.0
@ schematics/angular: 0.1.0
typescript: 2.3.4
webpack-sources: 1.0.2
webpack: 3.8.1

I am working on it for weeks, Can anyone help me where is problem? :(

Thanks!

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by kensodemann** [comment]
Also, is it possible to share your project via GitHub or if not your project, a sample application that demonstrates the same issue so others can try it and try to help?
