### ISSUE TITLE
Feature request: MD Pull to Refresh

### ISSUE THREAD

**Issue by MatanYed** [ionic-team/ionic#13337]
![example](https://camo.githubusercontent.com/6fe805cf90e72e6babc4be0dd1b0f51ad6eec69d/68747470733a2f2f6d6174657269616c2d64657369676e2e73746f726167652e676f6f676c65617069732e636f6d2f7075626c6973682f6d6174657269616c5f765f342f6d6174657269616c5f6578745f7075626c6973682f3042364f6b647a3735747151734f585a4364304d33624546754d45552f7061747465726e735f7377697065746f726566726573685f706f736974696f6e342e706e67)
www.google.com/design/spec/patterns/swipe-to-refresh.html#swipe-to-refresh-swipe-to-refresh

**Comment by pwespi** [comment]
This exists and is called [ion-refresher](http://ionicframework.com/docs/api/components/refresher/Refresher/).

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

As @pwespi points out, this already exists. If you have something else in mind other that what already exists via ion-refresher, please open a new feature request with those differences fully described (even if it is just an enhancement to the existing refresher) and I will make sure it gets moved into the feature requests repo.

Thank you for using Ionic
