### ISSUE TITLE
show selected dates

### ISSUE THREAD

**Issue by mkamranhamid** [ionic-team/ionic#13340]
I'm using ion-datetime directive currently it has min and max to show range of a date but do we have anything which can show selected dates only

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

Currently we have max and min to show range of dates but as i need to skip weekends in my implementation i need something like an array to dates

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#326
