### ISSUE TITLE
Keyboard bug with other Apps

### ISSUE THREAD

**Issue by felix9607** [ionic-team/ionic#13347]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you enable the Avire Password Manager App on Android Smartphones, the Keyboard gets Buggy.
No matter what Kind of text Input, but if you type one letter, the Keyboard Closes and the Focus gets lost. Afterward if you click on the Input again, the Keyboard opens and Closes instantly again. Then These two steps repeat infinite.

**Expected behavior:**
No Keyboard Problems.

**Steps to reproduce:**
[Avira PWM](https://play.google.com/store/apps/details?id=com.avira.passwordmanager)
install the App and enable it completely.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\SCHUL256\AppData\Roaming\npm\node_modules)

    @ionic/cli-plugin-proxy : 1.4.12
    @ionic/cli-utils        : 1.13.0
    ionic (Ionic CLI)       : 3.13.0

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v6.11.3
    npm  : 3.10.10
    OS   : Windows 10

Misc:

    backend : pro
```

**Comment by ghenry22** [comment]
I have seen this keyboard behaviour a lot on the simulator without adding anything extra, have you tried it on a real device to check?

**Comment by felix9607** [comment]
Yes, only on real device of course.
