### ISSUE TITLE
Feature request: New ion-input keyboard type that uses only numbers and decimal point

### ISSUE THREAD

**Issue by connor-odoherty** [ionic-team/ionic#13349]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The only numeric keyboard type available currently is 'tel', which does not include a decimal point. This makes it extremely limited.

**Expected behavior:**

It would be nice to have a 'decimal' type, that is a pure numeric keyboard like 'tel', with the addition of a decimal point on the first level. I'm surprised that this isn't already a feature, as inputs like price are so common on mobile.

**Steps to reproduce:**

Not applicable

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#328
