### ISSUE TITLE
feat(no-highlight): New attribute to ion-item to disable highlights in md mode

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#13344]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In `md` mode, all `ion-item` inputs get the `md-input-highlight` style applied. This gives them the green, red, etc. colored underlines on the inputs. 

However sometimes this breaks designs, as the colors may not work, or the developer may not even _want_ to have the border-bottom set. 

Currently these highlights can be disabled globally with a SASS variable:
`$text-input-md-show-focus-highlight: false;`

However that is extreme - what happens if the developer only wants to disable this in certain situations?

I propose that a new attribute is added to either the `ion-item` or `ion-input` called `no-highlight`. This will disable the highlights on the specified tag. 

You would need to add `:not(attribute)` into the rules here somewhere:

```
// Input highlight mixin for focus, valid, and invalid states
@mixin md-input-highlight($highlight-color) {
  border-bottom-color: $highlight-color;
  box-shadow: inset 0 -1px 0 0 $highlight-color;
}

// Show the focus highlight when the input has focus
@if ($text-input-md-show-focus-highlight) {
  // In order to get a 2px border we need to add an inset
  // box-shadow 1px (this is to avoid the div resizing)

  // TODO remove all uses of input-has-focus in v4
  .item-md.item-input.item-input-has-focus .item-inner,
  .item-md.item-input.input-has-focus .item-inner {
    @include md-input-highlight($text-input-md-highlight-color);
  }

  // The last item in a list has a border on the item, not the
  // inner item, so add it to the item itself
  .list-md .item-input.item-input-has-focus:last-child,
  .list-md .item-input.input-has-focus:last-child {
    @include md-input-highlight($text-input-md-highlight-color);

    .item-inner {
      box-shadow: none;
    }
  }
}

// Show the valid highlight when it has the .ng-valid class and a value
@if ($text-input-md-show-valid-highlight) {
  // TODO remove all uses of input-has-focus in v4
  // TODO remove all uses of input-has-value in v4
  .item-md.item-input.ng-valid.item-input-has-value:not(.input-has-focus):not(.item-input-has-focus) .item-inner,
  .item-md.item-input.ng-valid.input-has-value:not(.input-has-focus):not(.item-input-has-focus) .item-inner {
    @include md-input-highlight($text-input-md-highlight-color-valid);
  }

  .list-md .item-input.ng-valid.item-input-has-value:not(.input-has-focus):not(.item-input-has-focus):last-child,
  .list-md .item-input.ng-valid.input-has-value:not(.input-has-focus):not(.item-input-has-focus):last-child {
    @include md-input-highlight($text-input-md-highlight-color-valid);

    .item-inner {
      box-shadow: none;
    }
  }
}

// Show the invalid highlight when it has the invalid class and has been touched
@if ($text-input-md-show-invalid-highlight) {
  .item-md.item-input.ng-invalid.ng-touched:not(.input-has-focus):not(.item-input-has-focus) .item-inner {
    @include md-input-highlight($text-input-md-highlight-color-invalid);
  }

  .list-md .item-input.ng-invalid.ng-touched:not(.input-has-focus):not(.item-input-has-focus):last-child {
    @include md-input-highlight($text-input-md-highlight-color-invalid);

    .item-inner {
      box-shadow: none;
    }
  }
}
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/dylan/Desktop/Projects/CochranePlus/node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : ios 4.5.2
    Ionic Framework    : ionic-angular 3.8.0

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v6.11.4
    npm        : 4.6.1
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#327

**Comment by gelder-ux** [comment]
Hi @kensodemann, have any efforts been made to add this new attribute? Thanks!

**Comment by kensodemann** [comment]
@gelder-ux - I believe the current focus with v4 is for the first releases to include all core components ported to using Stencil based web components and to fix well-known bugs in the Angular integration where possible but not to add new functionality (or minimal new functionality, depending).

You can track the current status by examining the master branch of this repo.
