### ISSUE TITLE
getting error for building ios.

### ISSUE THREAD

**Issue by RakeshKW** [ionic-team/ionic#13357]
hi...
i am trying to buliding ios .When i run command  "ionic cordova build ios" ,am getting following error:
1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/nirajviveksheel/Library/Developer/Xcode/DerivedData/MyApp-apjajhlwndfubsfptrmrlpqcehzw/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/x86_64/GCDWebServerDataRequest.o MyApp/Plugins/cordova-plugin-ionic-webview/GCDWebServerDataRequest.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/nirajviveksheel/myApp/platforms/ios/cordova/build-debug.xcconfig,-workspace,MyApp.xcworkspace,-scheme,MyApp,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 6s Plus,build,CONFIGURATION_BUILD_DIR=/Users/nirajviveksheel/myApp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/nirajviveksheel/myApp/platforms/ios/build/sharedpch

[ERROR] An error occurred while running cordova build ios (exit code 1).

please help me.......

**Comment by yemenifree** [comment]
try this

```ssh
ionic cordova remove platform ios
ionic cordova platforms add ios
ionic cordova build ios
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by RakeshKW** [comment]
i tried following thing  but still its not working...
ionic cordova platform remove ios
ionic cordova platforms add ios
ionic cordova build ios
