### ISSUE TITLE
Google maps showing on browser but not on real device

### ISSUE THREAD

**Issue by TitikshaDaga** [ionic-team/ionic#13353]
Hey, I have started to use Ionic platform for building mobile apps and I am stuck on a problem for days. I have to incorporate google maps in my app and get continous location updates of the user. I am able to achieve this on browser and emulator(ionic lab emulator) but on the real device. Below is my code.Please help me. I need the solution kind of urgently.Thanks in advance!!!

//home.ts file

    export class HomePage {
  @ViewChild('map') mapElement: ElementRef;
  map:any;
  latitude:any;
  longitude:any;
  //map:GoogleMap;

  constructor(platform:Platform,public navCtrl: NavController,
    public geolocation: Geolocation,public menu:MenuController) {
      this.menu.enable(true); 
      platform.ready().then(()=>{
      this.loadMap();
  })     
  }

  loadMap(){
    alert("inside load map");
    var options_watch = {timeout:50000,frequency:1000,enableHighAccuracy:true};
    let watch = this.geolocation.watchPosition(options_watch);
    watch.subscribe((data) => {
     // data can be a set of coordinates, or an error (if an error occurred).
     this.latitude= data.coords.latitude;
     this.longitude= data.coords.longitude;
     let latlng = new google.maps.LatLng(this.latitude,this.longitude);
     let mapOptions = {
       center: latlng,
       zoom: 15,
       mapTypeId: google.maps.MapTypeId.ROADMAP
     }

     this.map = new google.maps.Map(this.mapElement.nativeElement, mapOptions);
     let marker = new google.maps.Marker({
       map:this.map,
       animation:google.maps.Animation.DROP,
       position:latlng
     }) 
     alert("watch "+this.latitude+"  "+this.longitude);
    },(err)=>{
      let latlng = new google.maps.LatLng(0,0);
      let mapOptions = {
        center: latlng,
        zoom: 15,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      }

      this.map = new google.maps.Map(this.mapElement.nativeElement, mapOptions);
      let marker = new google.maps.Marker({
        map:this.map,
        animation:google.maps.Animation.DROP,
        position:latlng
      }) 
      alert("error " +err); 
    })   
  }
}

//home.scss file

page-home {

      #map {
        width: 100%;
        height: 100%;`enter code here`
        background-color: transparent;
      }
}

//home.html file //after header

```
<ion-content>
  <div #map id="map">
  </div>
</ion-content>

```
//index.html file

<script src="js/app.js"></script>
  <script src="http://maps.google.com/maps/api/js?key=KEY"></script>
  <script src="cordova.js"></script>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

Essentially if you could take your code snippets and assemble an app that demonstrates your issue, and then host the repo on GitHub, that would be adequate and very helpful.

Thanks for using Ionic!

**Comment by TitikshaDaga** [comment]
Sorry for the late reply. Here is the url for the repository
https://github.com/TitikshaDaga/Google-Maps-Ionic-Demo.git

**Comment by manelme** [comment]
I had the same problem with iOS 11, don't know if it's fixed already, but I fixed it adding manually in the info.plist of your app on Xcode "NSLocationWhenInUseUsageDescription", hope it helps.

**Comment by kensodemann** [comment]
Sorry for the late reply. Just getting caught up on some of this after the holidays and all of the work being done for the next Ionic release. Hopefully, you have solved this on your own in the interim...

@manelme  is correct. It does look like you are using GeoLocation without having the proper stuff set in the `config.xml` in order to set the attributes, Apple requires in order for this to work (and iOS fails semi-silently on it, though it does log the issue to Xcode's console output).

Here is what I have in the `config.xml` file of one of my projects to deal with that:

```
    <config-file parent="NSLocationWhenInUseUsageDescription" platform="ios" target="*-Info.plist">
        <string>Used to determine where to get passes</string>
    </config-file>
```

Let me know if that doesn't work for you and I can reopen this.
