### ISSUE TITLE
Include rtl error after update to 3.8.0

### ISSUE THREAD

**Issue by lpsantana** [ionic-team/ionic#13359]
I have updated my ionic version to version 3.8.0 and when i execute ionic serve command get the following error:

sass: node_modules/ionic-angular/fonts/ionicons.scss, line: 36 
            no mixin named rtl Backtrace: node_modules/ionic-angular/fonts/ionicons.scss:36 

      L36:    @include rtl() {
      L37:      &[aria-label^="arrow"]::before,

Seems a problem with ionic-angular version itself, but i did some research and haven't found any issue related.

Anyone?

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

cli packages: (/home/douglasqueiroz/.nvm/versions/node/v7.10.0/lib/node_modules)

    @ionic/cli-utils  : 1.17.0
    ionic (Ionic CLI) : 3.17.0

global packages:

    cordova (Cordova CLI) : 6.5.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 25.2.5
    Node              : v7.10.0
    npm               : 4.2.0 
    OS                : Linux 4.4

Environment Variables:

    ANDROID_HOME : /work/android_sdk/android-sdk-linux

Misc:

    backend : pro

**Comment by mhartington** [comment]
Do you have a sample project to look at? Im not able to recreate this locally.

**Comment by lpsantana** [comment]
Any news on this?

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
