### ISSUE TITLE
Upgrade from ionic-angular 3.6.0->3.7/3.8 breaks android build

### ISSUE THREAD

**Issue by goleary** [ionic-team/ionic#13350]
Ionic-angular 3.7.0/3.8.0
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
On Upgrade from ionic-angular 3.6.0->3.7/3.8:
after `ionic cordova run android` the app builds and deploys to device.  The splash screen shows followed by a blank white screen.  Using the chrome developer tools I am unable to view anything, no elements, no source files.
After looking at the Android Monitor log output I can see that the providers are being created as the console log output from their constructor is show in the log.

After looking at the 
**Expected behavior:**
app should work as it does with previous versions.

**Steps to reproduce:**
as of yet have been unable to create a minimal repro.

**Related code:**

package.json:
```
"dependencies": {
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@ionic-native/app-version": "3.4.2",
    "@ionic-native/background-mode": "^3.12.1",
    "@ionic-native/core": "3.10.2",
    "@ionic-native/in-app-browser": "3.4.2",
    "@ionic-native/phonegap-local-notification": "^4.1.0",
    "@ionic-native/social-sharing": "3.4.2",
    "@ionic-native/splash-screen": "3.10.2",
    "@ionic-native/status-bar": "3.10.2",
    "@ionic/storage": "^2.0.1",
    "android-versions": "^1.2.1",
    "cordova-android": "~6.3.0",
    "cordova-android-support-gradle-release": "0.0.2",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-console": "^1.0.7",
    "cordova-plugin-device": "^1.1.6",
    "cordova-plugin-inappbrowser": "^1.5.0",
    "cordova-plugin-psa-scraper": "file:scraper_plugin",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.3",
    "cordova-plugin-whitelist": "^1.3.2",
    "cordova-plugin-wkwebview-engine": "https://github.com/driftyco/cordova-plugin-wkwebview-engine.git",
    "cordova-plugin-x-socialsharing": "^5.1.8",
    "cordova-psa-scraper": "file:scraper_plugin",
    "cordova-sqlite-storage": "^2.0.4",
    "es6-promise-plugin": "^4.1.0",
    "ionic": "^3.7.0",
    "ionic-angular": "^3.6.0",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "lodash": "^4.17.4",
    "phonegap-plugin-local-notification": "^1.0.1",
    "reflect-metadata": "^0.1.10",
    "rxjs": "5.4.0",
    "sw-toolbox": "3.6.0",
    "urijs": "^1.18.12",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^2.1.3",
    "@types/lodash": "^4.14.52",
    "ionic": "3.16.0",
    "js-cookie": "^2.1.4",
    "ncp": "^2.0.0",
    "q": "^1.5.0",
    "ts-loader": "^2.3.7",
    "typescript": "2.3.4",
    "webpack": "^3.5.6"
  },
  "config": {
    "ionic_bundler": "rollup"
  },
```

A sample application via GitHub

StackBlitz (https://stackblitz.com)

Plunker (http://plnkr.co/edit/cpeRJs?p=preview)

-->

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
ionic info:
```

cli packages: (C:\Users\golear\Repos\MobileShoppingAssist\node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.4
    npm               : 3.10.10
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\golear\AppData\Local\Android\sdk

Misc:

    backend : pro
```

**Comment by mhartington** [comment]
Hi there! This doesn't appear to be an issue with the framework it self, but rather your code/upgrade process. Please post your question on the [Ionic Forum](https://forum.ionicframework.com) instead.

**Comment by goleary** [comment]
@mhartington I've posted this in the [ionic forum ](https://forum.ionicframework.com/t/android-blank-screen-on-update-from-3-6-3-7-1-or-3-8-0/109206/5)multiple times with essentially 0 response.  I would say this is an issue with the framework itself, the doesn't run and the debugging tools are to provide any recourse.

**Comment by mhartington** [comment]
Will continue the conversation on the forum. I dont think this is framework issue, or else we would have had a lot more posts about it. It could be something local to your setup.
