### ISSUE TITLE
<ion-menu (ionOpen)="myCallback"> myCallback not fired

### ISSUE THREAD

**Issue by luckylooke** [ionic-team/ionic#13351]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
I have only one menu in app defined and I added event listeners to all events available for ion-menu (ionOpen, ionClose, ionDrag). None of them is called.

As a workaround I have accessed this emitters via menuController in component controller
this.menuCtrl.get().ionOpen.subscribe(myCallback)

**Expected behavior:**
callbacks to be called

**Steps to reproduce:**
click to menu hamburger icon
menu will open
myCallback should be called, but it is not..
only workaround handlers are called 

**Related code:**

```
<ion-menu 
	side="right"
	[content]="content"
	persistent="true"
	(ionOpen)="myCallback"
	(ionDrag)="myCallback"
	(ionClose)="myCallback"
	>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/lucky/.npm-global/lib/node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.3.0 ios 4.5.2
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.0.0 
    Node       : v6.11.3
    npm        : 5.5.1 
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by darthdie** [comment]
I'd imagine that it's supposed to be:
`	(ionOpen)="myCallback()"
	(ionDrag)="myCallback()"
	(ionClose)="myCallback()"
`

(Note the parentheses)

**Comment by luckylooke** [comment]
Could I have done such a stupid mistake? :/ It will be the cause.. I am
sure. I will test in the morning. But I am 99.99% sure that it is the only
problem.

**Comment by luckylooke** [comment]
I am so embarassed, how could I overlook it. :disappointed:

**Comment by luckylooke** [comment]
@darthdie thanks
