### ISSUE TITLE
perf: performance issue

### ISSUE THREAD

**Issue by Pratik525** [ionic-team/ionic#13358]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I am facing issue in ion-list scrolling performance. I have a large list of data and the list is getting hanged while scrolling</span>

<span is-issue-template></span>

**Comment by yemenifree** [comment]
you can optimze performac of ion-list by use [`virtualScroll`](https://ionicframework.com/docs/api/components/virtual-scroll/VirtualScroll/)

```html
<ion-list [virtualScroll]="items">
  <ion-item *virtualItem="let item">
    {{ item }}
  </ion-item>
</ion-list>
```
