### ISSUE TITLE
Ionic start: Error spawn  ENOENT

### ISSUE THREAD

**Issue by elisea1986** [ionic-team/ionic#13355]
I want to create my first app by ionic start command, but i have this issue:

√ Creating directory .\App2 - done!
Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn "C:\Program Files\nodejs\node.exe" ENOENT
    at notFoundError (C:\Users\elisea\AppData\Roaming\npm\node_modules\ionic\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\elisea\AppData\Roaming\npm\node_modules\ionic\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\elisea\AppData\Roaming\npm\node_modules\ionic\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

Following there is a list of ionic info:
cli packages: (C:\Users\elisea\AppData\Roaming\npm\node_modules)

    @ionic/cli-plugin-proxy : 1.5.4
    @ionic/cli-utils        : 1.16.0
    ionic (Ionic CLI)       : 3.16.0

System:

    Node : v8.9.0
    npm  : 5.5.1
    OS   : Windows 10

Environment Variables:

    HTTP_PROXY       : http://proxy.example.com:8888
    http_proxy       : http://proxy.example.com:8888
    HTTPS_PROXY      : http://proxy.example.com:8888
    https_proxy      : http://proxy.example.com:8888
    IONIC_HTTP_PROXY : http://proxy.example.com:8888
    PROXY            : http://proxy.example.com:8888
    proxy            : http://proxy.example.com:8888

Misc:

    backend : pro

So, I am not able to create the app, only the directory of the project is created.
How can I solve the issue?

Thanks.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is not an issue with the Ionic Framework but is potentially an issue with the CLI. I will move this issue to the CLI repo for you.

I also urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2866
