### ISSUE TITLE
VirtualScroll Does Not Redraw on Resize

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [ionic-team/ionic#13361]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[X ] feature request

**Current behavior:**
When resizing the window, VirtualScroll does not recalculate positions.

**Expected behavior:**
VirtualScroll should recalculate positions or add a method to redraw the list.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by TimeTravelersHackedMe** [comment]
http://plnkr.co/edit/CSz70r?p=preview ... try resizing below 500px

**Comment by jmarginier** [comment]
Look here : https://plnkr.co/edit/rBNMZ9OOYoYkClQaViba?p=preview, in the home page you have a way to refresh the virtual scroll to fit the new size :)
