### ISSUE TITLE
 trouble to make http requests using @ionic-native/http or @angular/http on LG X Power

### ISSUE THREAD

**Issue by souzace** [ionic-team/ionic#13360]
Hi guys, i have a problem to make http requests using ionic-native/http or angular/http, 
the method this.http.get(uri) works on many device was tested, like: asus zenfone, motorola moto g, lg k10, motorola moto z, alcatel pixi
but on LG X Power, don't work, i make many requests, seems that will work before 10 tries, but when the method return something, return a 500 http message fail.

my environment:

cli packages: (/usr/lib/nodejs/node-v6.11.2/lib/node_modules)

   @ionic/cli-utils  : 1.10.0
   ionic (Ionic CLI) : 3.10.0

global packages:

   Cordova CLI : 7.1.0 

local packages:

   @ionic/app-scripts : 2.1.3
   Cordova Platforms  : android 6.2.3 ios 4.4.0
   Ionic Framework    : ionic-angular 3.6.0

System:

   Android SDK Tools : 26.0.2
   Node              : v6.11.2
   npm               : 3.10.10
   OS                : Linux 4.10

"angular/http": "4.1.3",
"ionic-native/http": "^4.3.3",
"cordova-plugin-advanced-http": "^1.5.9",

**Comment by darthdie** [comment]
I'd recommend posting either on the Angular GitHub (if you want to check into angular/http) or posting on on the repository for cordova-plugin-advanced-http as it sounds like this isn't really related to Ionic proper.

**Comment by mhartington** [comment]
Would have to agree to @darthdie, doesn't seem to be an issue with the framework itself. 
I'd post on the advanced-http plugin repo, as it could be the cause of the issue.
