### ISSUE TITLE
Improving Performance of Ionic ActionSheetController

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [ionic-team/ionic#13364]
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

**Current behavior:**
I have an Ionic app and I'd like to improve the performance of the ActionSheetController so it renders closer to 60FPS on mobile devices. The problem occurs when I have a VirtualScroll list of 30+ items - the ActionSheet gets slower. I tried using a OnPush change detection strategy in Angular 4 but that didn't really work. I'm thinking the problem has to do with having a large DOM. Does that sound right? I also am loading 300px x 300px images in 80px x 80px squares. Will that slow it down? Is there some trick I can use to increase performance?

I'm using a Samsung Galaxy S8+ and it seems like the app runs faster as a website in the Samsung browser than it does in the app. Maybe all the plugins are causing a slow down? Should I use Crosswalk?

**Expected behavior:**
60FPS transitions on mobile devices.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
