### ISSUE TITLE
iOS Simulator reopens for every ionic cordova run command

### ISSUE THREAD

**Issue by eduardoRoth** [ionic-team/ionic#13377]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
When running ionic cordova run ios the simulator opens and loads the app, if I stop the process and then run it again, after build the simulator closes and opens.

**Expected behavior:**
I'm not sure in which ionic version started happening but before it never closed the simulator and reopened it when targeting the same iOS version and simulator device; it just closed the app and loaded the new one.

**Steps to reproduce:**
Run the following commands:
- ionic cordova run ios -lc --target=iPhone-X
- Wait for the app to build and run in the simulator
- cmd-c
- ionic cordova run ios -lc --target=iPhone-X
- Wait again for the app to build and then you'll see it close the simulator and open it again

(The target param is just to make sure the run command opens the same simulator device)

**Related code:**

Starter template shows this behavior

**Other information:**
macOS High Sierra 10.13.1

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-plugin-proxy : 1.5.4
    @ionic/cli-utils        : 1.17.0
    ionic (Ionic CLI)       : 3.17.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.3.0 ios 4.5.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.2
    ios-sim           : 6.1.2
    Node              : v6.11.4
    npm               : 3.10.10
    OS                : macOS High Sierra
    Xcode             : Xcode 9.1 Build version 9B55

Environment Variables:

    ANDROID_HOME     : /usr/local/Cellar/android-sdk/24.4.1_1
    HTTP_PROXY       : not set
    http_proxy       : not set
    HTTPS_PROXY      : not set
    https_proxy      : not set
    IONIC_HTTP_PROXY : not set
    PROXY            : not set
    proxy            : not set

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This issue seems more like an Ionic CLI issue than an Ionic Framework issue. I will move it to that repo for you. Please follow up using the newly created issue.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2869
