### ISSUE TITLE
Ion-input focus doesn't work after a certain height

### ISSUE THREAD

**Issue by VianneyW** [ionic-team/ionic#13373]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm having a problem with ionic 3 and more precisely Ion-Item and Ion-Input.
When you click on the fourth input, you leave and go to the fifth you can't go back to the fourth (input-has-focus class doesn't appear on ion-item). Seems to be related to a certain height

**Expected behavior:**

**Steps to reproduce:**
Click on City input
Click on Foo Input
Click on City Input (doesn't work anymore)
Click on Foo Input (doesn't work anymore)

**Related code:**
https://stackblitz.com/edit/ionic-yjvv4q

Check the home.html code and paste it into a new ionic project then run ionic serve and test in your browser.

**Other information:**
I can reproduce this bug in all ionic starter i used.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\YaYap\AppData\Roaming\npm\node_modules)
    @ionic/cli-utils  : 1.17.0
    ionic (Ionic CLI) : 3.17.0

global packages:
    cordova (Cordova CLI) : not installed

local packages:
    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.9.2

System:
    Android SDK Tools : 25.2.3
    Node              : v8.5.0
    npm               : 5.4.2
    OS                : Windows 10

Environment Variables:
    ANDROID_HOME : C:\Apps\Android\sdk

Misc:
    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by VianneyW** [comment]
Hello, 
Thank you for your answer here is a directory containing the sample : [https://github.com/VianneyW/Ionic](url)

Thanks Ionic :)

**Comment by kensodemann** [comment]
Thank-you for providing that application. I tried your app and it worked without the issue you describe. I tried running it on an older Samsung Note 4. How are you running the application?

**Comment by Edmundoacosta** [comment]
Im having the same issue in ionic 3.9.2, when i focus my first input its everything ok but when i want to back to that input doesn't work anymore.

**Comment by TalesMattos** [comment]
Im having the same issue in ionic 3.19.0. 
It happens when I put and I leave the focus few times in the ion-input (test stress of focus in ion-input). The input field behaves as if it is disabled.

**Comment by kensodemann** [comment]
I am going to close this as something that I cannot duplicate.

I have seen similar behavior, such as described here: https://github.com/ionic-team/ionic/issues/13587 but that was more consistent and came down to a bug in the webview that was cleared up by the user updating their phone. I am not sure if the issue you are seeing here is related or not.
