### ISSUE TITLE
Tried the checklist for ios 11 but nothing working

### ISSUE THREAD

**Issue by Gamerakki** [ionic-team/ionic#13374]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
the header and footer are showing safe area even after doing the checklist instruction. I even itryied removing status bar plugin.  Also added the viewport-fit=cover in meta tag,

![screen shot 2017-11-09 at 12 29 20 pm](https://user-images.githubusercontent.com/11846774/32593893-cf34e040-c54f-11e7-9b7f-f50965dbc0e8.png)
 

**Expected behavior:**
it should cover the full screen with bottom at footer according to Apple instrcution

Step to reproduce:
Set meta tag viewport-fit=cover in index.html: <meta name="viewport" content="width=device-width, viewport-fit=cover, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

Use plugin name="cordova-plugin-ionic-webview" spec="1.1.8"/

Use plugin name="cordova-plugin-statusbar" spec="https://github.com/apache/cordova-plugin-statusbar.git"

Use "ionic-angular": "3.7.0"

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
cli packages: (D:\Projects\Mobile\KGK\kgkmobile\node_modules)

    @ionic/cli-utils  : 1.14.0
    ionic (Ionic CLI) : 3.14.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v6.11.2
    npm  : 3.10.10
    OS   : Windows 10

Misc:

    backend : legacy
```
insert the output from ionic info here
```

OR
this is the correct view for iphone X a bit confused

**Comment by mhartington** [comment]
You're missing a splash-screen image for the larger device. Please run `ionic cordova resources` again to generate the 2732x2732 image.

**Comment by Gamerakki** [comment]
Thnx you so much closing the issue
