### ISSUE TITLE
Using ${{}} now breaks in 3.9.2

### ISSUE THREAD

**Issue by thierce** [ionic-team/ionic#13388]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If I try to put a dollar sign $ in front of {{somevar}} like this:
${{somevar}}
I get error:
somevar is not defined
or:
Runtime Error
Unexpected token .

Putting a space in between is fine though $ {{somevar}}

This was not a problem prior to 3.9.2

**Expected behavior:**
 ${{somevar}} would produce something like: $3.00

**Steps to reproduce:**
Create a var in a .ts file and use the following in the template:
${{somevar}}

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
@ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

local packages:

    @ionic/app-scripts : 3.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v7.9.0
    npm  : 5.5.1
    OS   : Windows 10
```

**Comment by nikmartin** [comment]
OMG, i have been beating my head on my desk for the past 4 hours because of this! Thank you!

**Comment by matoos32** [comment]
I had a similar problem, if not the same, after upgrading to Angular 5. Escaping the '$' fixed the issue for me i.e.  `${{somevar}}` --> `\${{somevar}}`

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I was able to duplicate the `${{somevar}}` issue in an Ionic blank starter.
I also tried it in a new Angular CLI app to see if the issue also occurred there but it did not.

I am moving this to the `@ionic/app-scripts` repo.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1310
