### ISSUE TITLE
How to connect wifi in ionic 3?

### ISSUE THREAD

**Issue by sudhan-ionic** [ionic-team/ionic#13384]
How to connect wifi to ionic and angular 4?
I am done scanning the wifi and show it in list view but I don't know how to connect wifi device
can pls help me to how to connect to wifi in ionic 3
I am attached scanned wifi list image.
Here I am using hotspot plugin to list the wifi device.

![screen shot 2017-10-04 at 1 36 51 pm](https://user-images.githubusercontent.com/33175538/32660801-44c12a1c-c64a-11e7-9373-d75e15d3f649.png)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by sudhan-ionic** [comment]
ok and thanks
