### ISSUE TITLE
Splash screen quality not optimized for high resolution devices

### ISSUE THREAD

**Issue by antoine92190** [ionic-team/ionic#13387]
**Ionic version:**
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request

**Current behavior:**
The quality of splash screen is not optimized for high resolution devices.
For example the Samsung S8 has a native resolution of `2960x1440`.
However, the default splash screen PNG file in `/resources` is set to `2732x2732`.
Thus, it leads to a low quality splash screen on such device.

**Expected behavior:**
Splash screen quality should be optimized for high resolution devices.
Can a workaround be to set the splash screen size  in `/resources` to `2960x2960`?
Is it safe to do that?

**Ionic info:**

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.3.0 ios 4.5.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.9.1
    npm        : 5.5.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.0 Build version 9A235 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Here is some info. According to our docs here: https://ionicframework.com/docs/cli/cordova/resources/

> The source image for splash screens should ideally be at least 2732×2732px and located at resources/splash.png. If you used ionic start, there should already be default Ionic resources in the resources/ directory, which you can overwrite.

It is expected that you _will_ overwrite the default one that we give you with something more appropriate for your app. The dimensions you give certainly fit the documented criteria, so go for it.

Thanks for using Ionic!

**Comment by antoine92190** [comment]
@kensodemann Thanks for the info, it will probably fix my issue!
