### ISSUE TITLE
Scroll assist resets bottom padding

### ISSUE THREAD

**Issue by danielcrk** [ionic-team/ionic#13386]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[] **3.x**
[X] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

When an input is focused, the keyboard appears and padding is added to the .scroll-content element. However, when the keyboard is closed, the bottom padding is set to 0, event if the element had bottom padding before, e.g. to compensate for tabs when ion-content has the fullscreen attribute.

**Expected behavior:**
The scroll assist should check and save the bottom padding before it does anything, and revert it to the initial value on keyboard close.

**Steps to reproduce:**
In a tabbed application, create a page with the fullscreen attribute and add an input field. Focus the input for the keyboard to appear then close the keyboard. The initial bottom padding is gone.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by danielcrk** [comment]
Sure, here you go. Check the home tab on a real device. Note the bottom padding. Open the keyboard. Close the keyboard. The bottom padding is 0.

https://github.com/danielcrk/ionic-keyboard-padding

**Comment by danielcrk** [comment]
Hi @kensodemann , is the example provided enough or does the issue still need more info?

**Comment by kensodemann** [comment]
Sorry. Things are a little chaotic here as we ramp up for v4. I will give it a look when I get time.

**Comment by paulstelzer** [comment]
Thanks for the issue! I close this here because v4 is already at beta.17. So please take a look at it :) Please open a new issue if there is an issue in v4
