### ISSUE TITLE
bug: ion-toggle checked doesn't woks with ngModel 

### ISSUE THREAD

**Issue by almishlab8** [ionic-team/ionic#13380]
**Type: bug**

**Ionic Version: 3.x**

**Platform: all**

Using [(ngModel)] with a ion-toggle component doesn't visually checked the component at the start if binded value is true. [(ngModel)] attribute works fine but the component is not visually updated at load regarding its value.

Not checked at component load if [(ngModel)] is there
``
<ion-toggle checked="true" [(ngModel)]="n" (ionChange)="themestate(n)"></ion-toggle>
``

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by almishlab8** [comment]
check this https://github.com/almishlab8/ion-toggle-issue-

**Comment by leonardocoutinho** [comment]
I have the same problem, ion-toggle dont work with [(ngModel)] and [checked] together
