### ISSUE TITLE
issue with ionic cordova build android --prod

### ISSUE THREAD

**Issue by ashley-s** [ionic-team/ionic#13381]
[package.txt](https://github.com/ionic-team/ionic/files/1462270/package.txt)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Ionic Info: 

package.json:
{
  "name": "MFile",
  "author": "MRA",
  "homepage": "http://www.mra.mu/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "5.0.0",
    "@angular/common": "5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/compiler-cli": "5.0.0",
    "@angular/core": "5.0.0",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0",
    "@ionic-native/app-rate": "^4.2.1",
    "@ionic-native/core": "4.3.3",
    "@ionic-native/device": "3.4.4",
    "@ionic-native/globalization": "^4.0.1",
    "@ionic-native/native-storage": "3.4.4",
    "@ionic-native/network": "3.12.1",
    "@ionic-native/splash-screen": "3.12.1",
    "@ionic-native/sqlite": "3.4.4",
    "@ionic-native/status-bar": "3.12.1",
    "@ionic/app-scripts": "2.0.2",
    "@ionic/storage": "2.1.3",
    "@ngx-translate/core": "^8.0.0",
    "@ngx-translate/http-loader": "^0.1.0",
    "angular2-jwt": "^0.2.3",
    "cordova-plugin-apprate": "~1.3.0",
    "cordova-plugin-console": "1.0.5",
    "cordova-plugin-device": "1.1.4",
    "cordova-plugin-globalization": "^1.0.7",
    "cordova-plugin-splashscreen": "~4.0.1",
    "cordova-plugin-statusbar": "2.2.2",
    "cordova-plugin-whitelist": "1.3.1",
    "css-animator": "^2.1.1",
    "ionic-angular": "3.9.2",
    "ionic-plugin-keyboard": "~2.2.1",
    "ionic2-super-tabs": "^4.1.4",
    "ionicons": "3.0.0",
    "json-object-mapper": "^1.5.1",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "moment-range": "^3.0.3",
    "ng2-currency-mask": "^4.4.1",
    "reflect-metadata": "^0.1.10",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "web-animations-js": "^2.2.5",
    "zone.js": "0.8.18",
    "cordova-android": "~6.3.0"
  },
  "devDependencies": {
    "@angular/tsc-wrapped": "^4.4.6",
    "@ionic/app-scripts": "^3.1.0",
    "ionic": "3.18.0",
    "typescript": "2.4.2"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [],
  "description": "mraMfile: An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-globalization": {},
      "cordova-plugin-console": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "ionic-plugin-keyboard": {},
      "cordova-plugin-apprate": {}
    },
    "platforms": [
      "android"
    ]
  }
}
**Current behavior:**
When running ionic cordova build android --prod, the following error occurs

E:\Mobile Source\mraMfile2>ionic cordova build android --prod
Running app-scripts build: --prod --platform android --target cordova
[09:42:46]  build prod started ...
[09:42:46]  clean started ...
[09:42:46]  clean finished in 12 ms
[09:42:46]  copy started ...
[09:42:46]  ngc started ...
Error: Please update @angular/cli. Angular 5+ requires at least Angular CLI 1.5+
    at throwNotSupportedError (E:\Mobile Source\mraMfile2\node_modules\@angular\compiler-cli\src\ngtools_api.js:78:11)
    at Function.NgTools_InternalApi_NG_2.codeGen (E:\Mobile Source\mraMfile2\node_modules\@angular\compiler-cli\src\ngtools_api.js:31:15)
    at Object.doCodegen (E:\Mobile Source\mraMfile2\node_modules\@ionic\app-scripts\dist\aot\codegen.js:6:51)
    at E:\Mobile Source\mraMfile2\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:42:30
[09:42:47]  copy finished in 1.17 s

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (E:\Mobile Source\mraMfile2\node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v6.9.2
    npm               : 3.10.9
    OS                : Windows 8.1

Environment Variables:

    ANDROID_HOME : C:\Program Files (x86)\Android\android-sdk

Misc:

    backend : legacy
```

**Comment by yemenifree** [comment]
some of the dependencies is blank, attache content of `package.json` again

**Comment by aces-tm** [comment]
I have the same issue building the app with --prod. Here is my `package.json`

```
"dependencies": {
    "@amcharts/amcharts3-angular": "^1.5.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/compiler-cli": "5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0",
    "@ionic-native/app-version": "^4.1.0",
    "@ionic-native/badge": "^3.14.0",
    "@ionic-native/call-number": "^4.3.1",
    "@ionic-native/camera": "^3.8.1",
    "@ionic-native/core": "^4.3.3",
    "@ionic-native/email-composer": "^3.8.1",
    "@ionic-native/in-app-browser": "^3.12.1",
    "@ionic-native/network": "^3.8.1",
    "@ionic-native/push": "^3.8.1",
    "@ionic-native/screen-orientation": "^4.3.1",
    "@ionic-native/splash-screen": "^4.3.3",
    "@ionic-native/status-bar": "^4.3.3",
    "@ionic/storage": "2.1.3",
    "angular2-jwt": "^0.2.3",
    "angular2-moment": "^1.3.3",
    "call-number": "^1.0.1",
    "cordova-android": "~6.1.2",
    "cordova-ios": "4.3.1",
    "cordova-plugin-app-version": "~0.1.9",
    "cordova-plugin-badge": "~0.7.4",
    "cordova-plugin-camera": "~2.3.1",
    "cordova-plugin-console": "1.0.5",
    "cordova-plugin-device": "1.1.4",
    "cordova-plugin-email": "~1.2.6",
    "cordova-plugin-file": "~4.3.1",
    "cordova-plugin-file-transfer": "~1.6.1",
    "cordova-plugin-filepath": "~1.0.2",
    "cordova-plugin-inappbrowser": "~1.7.1",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-network-information": "~1.3.1",
    "cordova-plugin-screen-orientation": "^2.0.1",
    "cordova-plugin-splashscreen": "~4.0.1",
    "cordova-plugin-statusbar": "git+https://github.com/apache/cordova-plugin-statusbar.git",
    "cordova-plugin-whitelist": "1.3.1",
    "date-fns": "^1.28.5",
    "es6-promise-plugin": "git+https://github.com/vstirbu/PromisesPlugin.git",
    "intl": "^1.2.5",
    "ionic-angular": "^3.9.2",
    "ionic-plugin-deeplinks": "~1.0.14",
    "ionic-plugin-keyboard": "~2.2.1",
    "ionic2-calendar": "^0.3.11",
    "ionicons": "3.0.0",
    "moment": "^2.18.1",
    "phonegap-plugin-push": "~1.8.4",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.1.0",
    "typescript": "2.4.2"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-statusbar",
    "cordova-plugin-console",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
```

Thanks!

**Comment by yemenifree** [comment]
try 

```
 rm -rf node_modules && rm package-lock.json && npm install
```

**Comment by aces-tm** [comment]
@yemenifree I tried that and I also removed www still doesn't work.

**Comment by yemenifree** [comment]
@aces-tm check #13310

**Comment by aces-tm** [comment]
@yemenifree Unfortunately I don't see solution for my problem in that tread. They are talking about it, but it doesn't seem as they solved it...

**Comment by AbanoubNassem** [comment]
I have similar problem , when run with normal build the app runs fine , but when ran with --prod, it errors out :
```
vendor.js:1 Uncaught TypeError: P.a.defineLocale is not a function
vendor.js:1 Ionic Native: deviceready event fired after 441 ms
```

not sure what is this all about , I can't track the issue , nor sure where defineLocale being called from!

**Comment by ashley-s** [comment]
I opened it at ionic-cli repo.
