### ISSUE TITLE
wifi is not connecting in ionic 3 why?

### ISSUE THREAD

**Issue by sudhan-ionic** [ionic-team/ionic#13397]
this.hotspot.connectToWifi(SSID, password)
              .then((data) => {

              console.log(".........hotspot..........",data);
            }, (error) => {
                console.log(".........hotspot error..........",error);
              })

I am using following code .but wifi is not connecting to specific device why?

**Comment by iursevla** [comment]
See : https://ionicframework.com/docs/native/hotspot/

> This plugin is still in beta stage and may not work as expected. Please submit any issues to the plugin repo.

Go to https://github.com/hypery2k/cordova-hotspot-plugin, maybe you can gather more information there.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am closing this as it is not an Ionic Framework issue.

Thank you for using Ionic

**Comment by sudhan-ionic** [comment]
but it's ionic plugin only
pls refer this website
https://ionicframework.com/docs/native/hotspot/

**Comment by kensodemann** [comment]
@sudhan-ionic - that does not make it an Ionic Framework issue. The link you provided states at the top exactly where to submit issues:

> This plugin is still in beta stage and may not work as expected. Please submit any issues to the plugin repo. 
Repo: https://github.com/hypery2k/cordova-hotspot-plugin

**Comment by sudhan-ionic** [comment]
ok
