### ISSUE TITLE
docs: Ionic changelog apparently not updated

### ISSUE THREAD

**Issue by fbalbinoribeiro** [ionic-team/ionic#13395]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi, everybody. Apparently, the github changelog has not been updated since 2017-8.</span>

<span is-issue-template></span>

**Comment by AndreasGassmann** [comment]
What do you mean? Looks fine to me: https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Closing this as the Ionic Framework changelog has been updated several times since 2017-8.

@fbalbinoribeiro - if you are seeing something different, can you please supply a link as to what you are looking at?

Thank you for using Ionic
