### ISSUE TITLE
PopTo only works with index

### ISSUE THREAD

**Issue by speedfl** [ionic-team/ionic#13390]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
3.9.2

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

``` this.nav.popTo() ``` do not work either with a page name as string or a page as component.

This only work with a workaround by providing the index of the page targetted. However this is not allowed by the type navController as number so I had to tweek 

```
var type : number = 1;
this.nav.popTo(<any>type);
``` 

**Expected behavior:**

This should work with page name or you can improve the type to take the index.

**Steps to reproduce:**

Create 4 pages. Go to last one and put a popTo the second by providing the name

**Related code:**

https://github.com/ionic-team/ionic/blob/master/src/navigation/nav-controller-base.ts#L148

**Other information:**

N/A

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (d:\jdevcc\git\pr\appV3\node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.0.0

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.1.3
    Node              : v6.11.3
    npm               : 4.6.1
    OS                : Windows 7

Environment Variables:

    ANDROID_HOME : D:\Userfiles\Documents\perso\android\sdk

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

Nav is being re-done as part of v4. Having your use case documented via a sample app will help us try to have it covered or otherwise handled in some way.

Thanks for using Ionic!

**Comment by speedfl** [comment]
Hello,

Thanks for your answer

Here is a repository:

https://github.com/speedfl/issue-navigation-ionic-3

You have an example of the non working cases (providing the page and the page name) and the working case (with ID)

Regards

And thanks for all you work!
