### ISSUE TITLE
feat(fab): Options in close button in fab-list: handle click and icon

### ISSUE THREAD

**Issue by willoliveira** [ionic-team/ionic#13391]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
The close button on the fab-list is a 'ion-close' fixed and not possible handle a click.

**Expected behavior:**
Options to choose the icon and a handle click with 'fab-list' open. I think of this feature because of google calendar.

[https://www.androidcentral.com/sites/androidcentral.com/files/styles/larger/public/article_images/2016/09/google-calendar-event-1.jpg?itok=vWeAlj_z](https://www.androidcentral.com/sites/androidcentral.com/files/styles/larger/public/article_images/2016/09/google-calendar-event-1.jpg?itok=vWeAlj_z)

**Related code:**

```
  <ion-fab right bottom>
    <button ion-fab color="light"><ion-icon name="arrow-dropleft"></ion-icon></button>
    <ion-fab-list close-icon="calendar" [close-onclick]="OpenCreateEvent()" side="left">
      <button ion-fab><ion-icon name="logo-facebook"></ion-icon></button>
      <button ion-fab><ion-icon name="logo-twitter"></ion-icon></button>
      <button ion-fab><ion-icon name="logo-vimeo"></ion-icon></button>
      <button ion-fab><ion-icon name="logo-googleplus"></ion-icon></button>
    </ion-fab-list>
  </ion-fab>
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by willoliveira** [comment]
In my work, I had to simulate the same behavior as Google Calendar. On the first click, it displays the list of fabs, in the second, it goes to another page.

![screenshot_20171113-155247](https://user-images.githubusercontent.com/7832287/32740902-9658890e-c88b-11e7-84f0-55398a29fcc7.png)

![screenshot_20171113-155252](https://user-images.githubusercontent.com/7832287/32740913-9c124e16-c88b-11e7-9138-7f2573cd8672.png)

**Comment by willoliveira** [comment]
If I can, I can try implement the feature, if it is relevant to the Ionic.
