### ISSUE TITLE
Android 5.1 Delay on Drag

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [ionic-team/ionic#13400]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[# ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[# ] bug report
[ ] feature request

**Current behavior:**
On Android 5.1 when dragging through a list there is a delay before the drag registers. If you hold down for a little bit then the scroll registers and acts as it should

**Expected behavior:**
No delay when user swipes up or down through a list.

**Steps to reproduce:**
Ionic Angular 3.8 on Android 5.1

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
