### ISSUE TITLE
VirtualScroll ignoring content area size when changing screen sizes

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [ionic-team/ionic#13401]
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[# ] bug report
[ ] feature request

**Current behavior:**
VirtualScroll will render properly when the view initiates. After the view is resized by switching to landscape view on a device, the VirtualScroll will re-render its view port size. Then by rotating the device back to its initial portrait mode the VirtualScroll will inherit the same bottom-padding as used in the landscape mode.

**Expected behavior:**
VirtualScroll should resize to use the full allowed height and width of its content area even after switching bottom-padding during screen size changes.

**Steps to reproduce:**
VirtualScroll on Android 5.1 with Ionic Angular 3.8

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
