### ISSUE TITLE
How can I show tabs in sub page when I configuration "tabsHideOnSubPages: true" in the app config?

### ISSUE THREAD

**Issue by rcg1994** [ionic-team/ionic#13404]
@kensodemann Hi ! I have one question. when I set config in `IonicModule.forRoot`
```
IonicModule.forRoot(MyApp, {
  backButtonIcon: 'ios-arrow-back' ,
  backButtonText: '',
  pageTransition: 'md-transition',
  activator: 'ripple',
  mode: 'md',
  tabsHideOnSubPages: true
})
```
then, all of the sub page will show with play md-transition and the tabs will hides, yeah it works since now. but when I need some special sub page have different act, I set config in runtime like :
```
import { IonicPage, NavController,Config } from 'ionic-angular';
import { LoginPage } from '../login/login';

@IonicPage()
@Component({
  selector: 'page-mine',
  templateUrl: 'mine.html',
})
constructor(
  public navCtrl: NavController,
  public config: Config
) {
  ...
}
openLogin(){
  this.config.set('pageTransition', 'ios-transition')
  this.config.set('tabsHideOnSubPages', false)
  this.navCtrl.push(LoginPage)
}
```
well, the `pageTransition`  will work, but the `tabsHideOnSubPages` doesn't work like I expected.
How can I do if I want the sub page has its own `tabsHideOnSubPages`  ( just show tabs in sub page when I set 'tabsHideOnSubPages=true' in app config)
forgive my poor English and thank you so much !

my ionic info
```
cli packages: (C:\Users\PC\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 25.2.5
    Node              : v6.11.5
    npm               : 3.10.10
    OS                : Windows 7

Environment Variables:

    ANDROID_HOME : E:\program\Android\android-sdk

Misc:

    backend : pro

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by rcg1994** [comment]
@kensodemann Thanks for replying to me! there is a sample example.
https://github.com/rcg1994/ionic3-issue-sub-page

**Comment by EverettZ** [comment]
@kensodemann No updates on this?

**Comment by varunneelakantan** [comment]
Any updates, Would be great if there is a solution for this requirement!
