### ISSUE TITLE
ionic CLI

### ISSUE THREAD

**Issue by Kamar-Meddah** [ionic-team/ionic#13408]
the user is not free to structure the project as he want + ionic cli is not as useful as angular cli try to make it the same

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a complaint about the CLI, I am going to close this issue. If you would like to create a feature request for the CLI, please enter that request here: https://github.com/ionic-team/ionic-cli

Thanks for using Ionic!

**Comment by Kamar-Meddah** [comment]
ur welcome
