### ISSUE TITLE
Using overflow-scroll="true" makes some divs empty (1 second bug)

### ISSUE THREAD

**Issue by 1BJK903** [ionic-team/ionic#13403]
Hi all,

I am trying to optimise the performance of my app by changing the way I scroll. Right now, it's incredibly _laggy_ when I am scrolling, so I came up with this:

`<ion-content overflow-scroll="true" class="has-header">`

It actually seems like it's faster, **but... some divs at the end of the scrollbar (and top, if I scroll up again) when I scroll down are looking empty! Their content comes back 1 second after the scrolling is done, leaving it blank for approximately one second.** When I scroll up again, this time the most top div gets empty and the content comes back when scrolling is finished entirely. 

I don't like this buggy behaviour, but I don't know what is making it so buggy. Could someone help, please?

@dwieeb @mhartington 

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.0.1 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    Cordova Platforms : android 6.3.0 ios 4.4.0
    Ionic Framework   : ionic1 master

System:

    ios-deploy : 1.9.0 
    ios-sim    : 5.0.8 
    Node       : v6.8.1
    npm        : 4.6.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by gregor-srdic** [comment]
performance of scrolling in cordova ios apps can be greatly improved by using https://ionicframework.com/docs/wkwebview/ plugin
and it only requires some config, no changes to your source code

**Comment by 1BJK903** [comment]
Thanks @gregor-srdic, but I think that's not meant for Ionic 1, correct?

**Comment by gregor-srdic** [comment]
No, you can use it in any Cordova based app

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to close this because it is an Ionic Framework v1 issue and this list is for Ionic Framework v2+ issues. If the solution that @gregor-srdic suggested does not work for you, please open an issue in the Ionic Framework v1 repo: https://github.com/ionic-team/ionic-v1

Thank you for using Ionic
