### ISSUE TITLE
unable to create a sample project using ionic start

### ISSUE THREAD

**Issue by avramanaareddy** [ionic-team/ionic#13416]
$ sudo ionic start myapp sidemenu

? The directory myapp contains file(s) that could conflict. Would you like to overwrite the directory with
 this new project? Yes
✔ Creating directory ./myapp - done!
✔ Downloading and extracting sidemenu starter - done!
✔ Personalizing ionic.config.json and package.json - done!

Installing dependencies may take several minutes.

  ✨   IONIC  DEVAPP  ✨

 Speed up development with the Ionic DevApp, our fast, on-device testing mobile app

  -  🔑   Test on iOS and Android without Native SDKs
  -  🚀   LiveReload for instant style and JS updates

 ️-->    Install DevApp: https://bit.ly/ionic-dev-app    <--

> npm i
✖ Running command - failed!
[ERROR] An error occurred while running npm i (exit code 1):

        
        
        > fsevents@1.1.3 install /Users/venkataavula/Desktop/demo/myapp/node_modules/fsevents
        > node install
        
        [fsevents] Success: 
        "/Users/venkataavula/Desktop/demo/myapp/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" 
        already installed
        Pass --update-binary to reinstall or --build-from-source to recompile
        
        > node-sass@4.5.3 install /Users/venkataavula/Desktop/demo/myapp/node_modules/node-sass
        > node scripts/install.js
        
        Unable to save binary 
        /Users/venkataavula/Desktop/demo/myapp/node_modules/node-sass/vendor/darwin-x64-48 : { Error: 
        EACCES: permission denied, mkdir 
        '/Users/venkataavula/Desktop/demo/myapp/node_modules/node-sass/vendor'
             at Error (native)
             at Object.fs.mkdirSync (fs.js:924:18)
             at sync (/Users/venkataavula/Desktop/demo/myapp/node_modules/mkdirp/index.js:71:13)
             at Function.sync (/Users/venkataavula/Desktop/demo/myapp/node_modules/mkdirp/index.js:77:24)
             at checkAndDownloadBinary 
        (/Users/venkataavula/Desktop/demo/myapp/node_modules/node-sass/scripts/install.js:111:11)
             at Object.<anonymous> 
        (/Users/venkataavula/Desktop/demo/myapp/node_modules/node-sass/scripts/install.js:154:1)
             at Module._compile (module.js:570:32)
             at Object.Module._extensions..js (module.js:579:10)
             at Module.load (module.js:487:32)
             at tryModuleLoad (module.js:446:12)
           errno: -13,
           code: 'EACCES',
           syscall: 'mkdir',
           path: '/Users/venkataavula/Desktop/demo/myapp/node_modules/node-sass/vendor' }
        
        > uglifyjs-webpack-plugin@0.4.6 postinstall 
        /Users/venkataavula/Desktop/demo/myapp/node_modules/uglifyjs-webpack-plugin
        > node lib/post_install.js
        
        
        > node-sass@4.5.3 postinstall /Users/venkataavula/Desktop/demo/myapp/node_modules/node-sass
        > node scripts/build.js
        
        Building: /usr/local/bin/node 
        /Users/venkataavula/Desktop/demo/myapp/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose 
        --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
        gyp info it worked if it ends with ok
        gyp verb cli [ '/usr/local/bin/node',
        gyp verb cli   '/Users/venkataavula/Desktop/demo/myapp/node_modules/node-gyp/bin/node-gyp.js',
        gyp verb cli   'rebuild',
        gyp verb cli   '--verbose',
        gyp verb cli   '--libsass_ext=',
        gyp verb cli   '--libsass_cflags=',
        gyp verb cli   '--libsass_ldflags=',
        gyp verb cli   '--libsass_library=' ]
        gyp info using node-gyp@3.6.2
        gyp info using node@6.11.4 | darwin | x64
        gyp verb command rebuild []
        gyp verb command clean []
        gyp verb clean removing "build" directory
        gyp verb command configure []
        gyp verb check python checking for Python executable "python2" in the PATH
        gyp verb `which` failed Error: not found: python2
        gyp verb `which` failed     at getNotFoundError 
        (/Users/venkataavula/Desktop/demo/myapp/node_modules/which/which.js:13:12)
        gyp verb `which` failed     at F 
        (/Users/venkataavula/Desktop/demo/myapp/node_modules/which/which.js:68:19)
        gyp verb `which` failed     at E 
        (/Users/venkataavula/Desktop/demo/myapp/node_modules/which/which.js:80:29)
        gyp verb `which` failed     at 
        /Users/venkataavula/Desktop/demo/myapp/node_modules/which/which.js:89:16
        gyp verb `which` failed     at 
        /Users/venkataavula/Desktop/demo/myapp/node_modules/isexe/index.js:42:5
        gyp verb `which` failed     at 
        /Users/venkataavula/Desktop/demo/myapp/node_modules/isexe/mode.js:8:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
        gyp verb `which` failed  python2 { Error: not found: python2
        gyp verb `which` failed     at getNotFoundError 
        (/Users/venkataavula/Desktop/demo/myapp/node_modules/which/which.js:13:12)
        gyp verb `which` failed     at F 
        (/Users/venkataavula/Desktop/demo/myapp/node_modules/which/which.js:68:19)
        gyp verb `which` failed     at E 
        (/Users/venkataavula/Desktop/demo/myapp/node_modules/which/which.js:80:29)
        gyp verb `which` failed     at 
        /Users/venkataavula/Desktop/demo/myapp/node_modules/which/which.js:89:16
        gyp verb `which` failed     at 
        /Users/venkataavula/Desktop/demo/myapp/node_modules/isexe/index.js:42:5
        gyp verb `which` failed     at 
        /Users/venkataavula/Desktop/demo/myapp/node_modules/isexe/mode.js:8:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
        gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError 
        (/Users/venkataavula/Desktop/demo/myapp/node_modules/which/which.js:13:12)\n    at F 
        (/Users/venkataavula/Desktop/demo/myapp/node_modules/which/which.js:68:19)\n    at E 
        (/Users/venkataavula/Desktop/demo/myapp/node_modules/which/which.js:80:29)\n    at 
        /Users/venkataavula/Desktop/demo/myapp/node_modules/which/which.js:89:16\n    at 
        /Users/venkataavula/Desktop/demo/myapp/node_modules/isexe/index.js:42:5\n    at 
        /Users/venkataavula/Desktop/demo/myapp/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete 
        (fs.js:123:15)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb check python checking for Python executable "python" in the PATH
        gyp verb `which` succeeded python /usr/bin/python
        gyp verb check python version `/usr/bin/python -c "import platform; 
        print(platform.python_version());"` returned: "2.7.10\n"
        gyp verb get node dir no --target version specified, falling back to host node version: 6.11.4
        gyp verb command install [ '6.11.4' ]
        gyp verb install input version string "6.11.4"
        gyp verb install installing version: 6.11.4
        gyp verb install --ensure was passed, so won't reinstall if already installed
        gyp verb install version is already installed, need to check "installVersion"
        gyp verb got "installVersion" 9
        gyp verb needs "installVersion" 9
        gyp verb install version is good
        gyp verb get node dir target node version installed: 6.11.4
        gyp verb build dir attempting to create "build" dir: 
        /Users/venkataavula/Desktop/demo/myapp/node_modules/node-sass/build
        gyp ERR! configure error 
        gyp ERR! stack Error: EACCES: permission denied, mkdir 
        '/Users/venkataavula/Desktop/demo/myapp/node_modules/node-sass/build'
        gyp ERR! stack     at Error (native)
        gyp ERR! System Darwin 17.0.0
        gyp ERR! command "/usr/local/bin/node" 
        "/Users/venkataavula/Desktop/demo/myapp/node_modules/node-gyp/bin/node-gyp.js" "rebuild" 
        "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
        gyp ERR! cwd /Users/venkataavula/Desktop/demo/myapp/node_modules/node-sass
        gyp ERR! node -v v6.11.4
        gyp ERR! node-gyp -v v3.6.2
        gyp ERR! not ok 
        Build failed with error code: 1
        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
        npm ERR! Exit status 1
        npm ERR! 
        npm ERR! Failed at the node-sass@4.5.3 postinstall script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!     /Users/venkataavula/.npm/_logs/2017-11-14T15_45_36_938Z-debug.log

**Comment by avramanaareddy** [comment]
This is for ionic 3 project creation. It throws always the same error. I tried all the ways as per my knowledge

**Comment by ThorvaldAagaard** [comment]
Try running it as administrator,

**Comment by satsangamusa** [comment]
I am working on macOS, I tried it using sudo command, even though it throws the same error.

**Comment by ThorvaldAagaard** [comment]
Other issues might be newest version of NPM.

I can see the following in your log:

**Comment by satsangamusa** [comment]
I gave full read write permissions to my folder ionic3 in my local, then ran the command  $sudo ionic start myapp sidemenu

i don't know how come it throws the same error, again and again

$ sudo ionic start myapp sidemenu
Password:
✔ Creating directory ./myapp - done!
✔ Downloading and extracting sidemenu starter - done!
✔ Personalizing ionic.config.json and package.json - done!

Installing dependencies may take several minutes.

  ✨   IONIC  DEVAPP  ✨

 Speed up development with the Ionic DevApp, our fast, on-device testing mobile app

  -  🔑   Test on iOS and Android without Native SDKs
  -  🚀   LiveReload for instant style and JS updates

 ️-->    Install DevApp: https://bit.ly/ionic-dev-app    <--

> npm i
✖ Running command - failed!
[ERROR] An error occurred while running npm i (exit code 1):

        
        
        > fsevents@1.1.3 install /Users/venkataavula/Desktop/ionic3/myapp/node_modules/fsevents
        > node install
        
        [fsevents] Success: 
        "/Users/venkataavula/Desktop/ionic3/myapp/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" 
        already installed
        Pass --update-binary to reinstall or --build-from-source to recompile
        
        > node-sass@4.5.3 install /Users/venkataavula/Desktop/ionic3/myapp/node_modules/node-sass
        > node scripts/install.js
        
        Unable to save binary 
        /Users/venkataavula/Desktop/ionic3/myapp/node_modules/node-sass/vendor/darwin-x64-48 : { Error: 
        EACCES: permission denied, mkdir 
        '/Users/venkataavula/Desktop/ionic3/myapp/node_modules/node-sass/vendor'
             at Error (native)
             at Object.fs.mkdirSync (fs.js:924:18)
             at sync (/Users/venkataavula/Desktop/ionic3/myapp/node_modules/mkdirp/index.js:71:13)
             at Function.sync 
        (/Users/venkataavula/Desktop/ionic3/myapp/node_modules/mkdirp/index.js:77:24)
             at checkAndDownloadBinary 
        (/Users/venkataavula/Desktop/ionic3/myapp/node_modules/node-sass/scripts/install.js:111:11)
             at Object.<anonymous> 
        (/Users/venkataavula/Desktop/ionic3/myapp/node_modules/node-sass/scripts/install.js:154:1)
             at Module._compile (module.js:570:32)
             at Object.Module._extensions..js (module.js:579:10)
             at Module.load (module.js:487:32)
             at tryModuleLoad (module.js:446:12)
           errno: -13,
           code: 'EACCES',
           syscall: 'mkdir',
           path: '/Users/venkataavula/Desktop/ionic3/myapp/node_modules/node-sass/vendor' }
        
        > uglifyjs-webpack-plugin@0.4.6 postinstall 
        /Users/venkataavula/Desktop/ionic3/myapp/node_modules/uglifyjs-webpack-plugin
        > node lib/post_install.js
        
        
        > node-sass@4.5.3 postinstall /Users/venkataavula/Desktop/ionic3/myapp/node_modules/node-sass
        > node scripts/build.js
        
        Building: /usr/local/bin/node 
        /Users/venkataavula/Desktop/ionic3/myapp/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose 
        --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
        gyp info it worked if it ends with ok
        gyp verb cli [ '/usr/local/bin/node',
        gyp verb cli   '/Users/venkataavula/Desktop/ionic3/myapp/node_modules/node-gyp/bin/node-gyp.js',
        gyp verb cli   'rebuild',
        gyp verb cli   '--verbose',
        gyp verb cli   '--libsass_ext=',
        gyp verb cli   '--libsass_cflags=',
        gyp verb cli   '--libsass_ldflags=',
        gyp verb cli   '--libsass_library=' ]
        gyp info using node-gyp@3.6.2
        gyp info using node@6.11.4 | darwin | x64
        gyp verb command rebuild []
        gyp verb command clean []
        gyp verb clean removing "build" directory
        gyp verb command configure []
        gyp verb check python checking for Python executable "python2" in the PATH
        gyp verb `which` failed Error: not found: python2
        gyp verb `which` failed     at getNotFoundError 
        (/Users/venkataavula/Desktop/ionic3/myapp/node_modules/which/which.js:13:12)
        gyp verb `which` failed     at F 
        (/Users/venkataavula/Desktop/ionic3/myapp/node_modules/which/which.js:68:19)
        gyp verb `which` failed     at E 
        (/Users/venkataavula/Desktop/ionic3/myapp/node_modules/which/which.js:80:29)
        gyp verb `which` failed     at 
        /Users/venkataavula/Desktop/ionic3/myapp/node_modules/which/which.js:89:16
        gyp verb `which` failed     at 
        /Users/venkataavula/Desktop/ionic3/myapp/node_modules/isexe/index.js:42:5
        gyp verb `which` failed     at 
        /Users/venkataavula/Desktop/ionic3/myapp/node_modules/isexe/mode.js:8:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
        gyp verb `which` failed  python2 { Error: not found: python2
        gyp verb `which` failed     at getNotFoundError 
        (/Users/venkataavula/Desktop/ionic3/myapp/node_modules/which/which.js:13:12)
        gyp verb `which` failed     at F 
        (/Users/venkataavula/Desktop/ionic3/myapp/node_modules/which/which.js:68:19)
        gyp verb `which` failed     at E 
        (/Users/venkataavula/Desktop/ionic3/myapp/node_modules/which/which.js:80:29)
        gyp verb `which` failed     at 
        /Users/venkataavula/Desktop/ionic3/myapp/node_modules/which/which.js:89:16
        gyp verb `which` failed     at 
        /Users/venkataavula/Desktop/ionic3/myapp/node_modules/isexe/index.js:42:5
        gyp verb `which` failed     at 
        /Users/venkataavula/Desktop/ionic3/myapp/node_modules/isexe/mode.js:8:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
        gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError 
        (/Users/venkataavula/Desktop/ionic3/myapp/node_modules/which/which.js:13:12)\n    at F 
        (/Users/venkataavula/Desktop/ionic3/myapp/node_modules/which/which.js:68:19)\n    at E 
        (/Users/venkataavula/Desktop/ionic3/myapp/node_modules/which/which.js:80:29)\n    at 
        /Users/venkataavula/Desktop/ionic3/myapp/node_modules/which/which.js:89:16\n    at 
        /Users/venkataavula/Desktop/ionic3/myapp/node_modules/isexe/index.js:42:5\n    at 
        /Users/venkataavula/Desktop/ionic3/myapp/node_modules/isexe/mode.js:8:5\n    at 
        FSReqWrap.oncomplete (fs.js:123:15)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb check python checking for Python executable "python" in the PATH
        gyp verb `which` succeeded python /usr/bin/python
        gyp verb check python version `/usr/bin/python -c "import platform; 
        print(platform.python_version());"` returned: "2.7.10\n"
        gyp verb get node dir no --target version specified, falling back to host node version: 6.11.4
        gyp verb command install [ '6.11.4' ]
        gyp verb install input version string "6.11.4"
        gyp verb install installing version: 6.11.4
        gyp verb install --ensure was passed, so won't reinstall if already installed
        gyp verb install version is already installed, need to check "installVersion"
        gyp verb got "installVersion" 9
        gyp verb needs "installVersion" 9
        gyp verb install version is good
        gyp verb get node dir target node version installed: 6.11.4
        gyp verb build dir attempting to create "build" dir: 
        /Users/venkataavula/Desktop/ionic3/myapp/node_modules/node-sass/build
        gyp ERR! configure error 
        gyp ERR! stack Error: EACCES: permission denied, mkdir 
        '/Users/venkataavula/Desktop/ionic3/myapp/node_modules/node-sass/build'
        gyp ERR! stack     at Error (native)
        gyp ERR! System Darwin 17.0.0
        gyp ERR! command "/usr/local/bin/node" 
        "/Users/venkataavula/Desktop/ionic3/myapp/node_modules/node-gyp/bin/node-gyp.js" "rebuild" 
        "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
        gyp ERR! cwd /Users/venkataavula/Desktop/ionic3/myapp/node_modules/node-sass
        gyp ERR! node -v v6.11.4
        gyp ERR! node-gyp -v v3.6.2
        gyp ERR! not ok 
        Build failed with error code: 1
        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
        npm ERR! Exit status 1
        npm ERR! 
        npm ERR! Failed at the node-sass@4.5.3 postinstall script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!     /Users/venkataavula/.npm/_logs/2017-11-14T18_34_56_142Z-debug.log

**Comment by ThorvaldAagaard** [comment]
try 
```
npm -v
```
and give me the output

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am not sure on your full issue, but you should not use `sudo` when creating a project like that. You should only use `sudo` when you logically need to. Using `sudo` like that you probably have created some things using the wrong user and permissions, potentially leading to the issue you are seeing.

Thank you for using Ionic

**Comment by avramanaareddy** [comment]
Great.
thanks for your big help. now it works, when sudo is removed while creating the project.

**Comment by kensodemann** [comment]
Excellent!! Glad to hear it. I will close this now then.
