### ISSUE TITLE
Unable to animate full swipe on ion-item-sliding

### ISSUE THREAD

**Issue by sburnicki** [ionic-team/ionic#13413]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
When I try to animate gestures like "swipe to remove" on list items, I want the item itself to slide out, which is quite common for this gesture.

To do this I use an `ion-item-sliding` with a `ion-item-options` that has an `expandable` button.
Until I recently updated my ionic version, I could animate this via  `moveSliding` (see below). Now I can't animate this behavior and the slide always closes:

![swipe_to_remove_no_animation](https://user-images.githubusercontent.com/5701519/32770305-74558c1e-c91f-11e7-9ac0-b1a75480d096.gif)
*Behavior with current ionic version*

**Expected behavior:**
I want to call `moveSliding` in the swipe event handler, so to have a common "swipe to remove animation":

![swipe_to_delete](https://user-images.githubusercontent.com/5701519/32770395-c0d55e84-c91f-11e7-98c5-7496ca1b5d64.gif)
*Behavior before upgrading*

**Steps to reproduce:**
1. Call `moveSliding` in the swipe event handler
2. See that it doesn't have an effect anymore.

**Related code:**
[Minimal working example](https://github.com/sburnicki/ionic-swipe-to-remove)

Code called on `(ionSwipe)`
```typescript
  deleteItem(item: ItemSliding) {
    const nativeElement = <HTMLElement> item.item.getNativeElement();
    const moveFactor = item.getOpenAmount() > 0 ? -1 : 2.5;
    const x = nativeElement.offsetWidth * moveFactor;
    item.setElementClass("removed", true);
    item.moveSliding(x);
  }
```

**Other information:**
I report this as a bug as it did work before.
I suspect the following commit to be the reason why it doesn't work anymore:
https://github.com/ionic-team/ionic/pull/12157/commits/92c082a218fbb2da1a3084e7c99711bc46f031b3

Before, the code called `_setOpenAmount` first, so I could overwrite it in my handler by calling `moveSliding`. Now it's called after the handler, so it overwrites what I'm doing.

A *workaround* is to call `moveSliding` in `setTimeout`. However, this workaround easily breaks if other things are going on (like showing toast, multiple swipes, ...).

As this animation is really common for users, I'd really want to see it working again.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.0.0 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0 ios 4.5.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v6.11.5
    npm  : 4.1.2 
    OS   : Linux 4.9

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by avengyy** [comment]
Have you tried adding the `expandable` parameter to your `ion-item-options`?

Right now your code in GitHub is the following
`<ion-list>
        <ion-item-sliding *ngFor="let i of [1, 2, 3, 4]">
            <ion-item (click)="item.close()">
                <button>
                    <h3>Test {{i}}</h3>
                </button>
            </ion-item>
            <ion-item-options side="left" (ionSwipe)="deleteItem($event)">
                <button ion-button color="danger" expandable>
                    <ion-icon name="trash"></ion-icon>
                    </button>
                </ion-item-options>
        </ion-item-sliding>
    </ion-list>`

Could you try this

`<ion-list>
        <ion-item-sliding *ngFor="let i of [1, 2, 3, 4]">
            <ion-item (click)="item.close()">
                <button>
                    <h3>Test {{i}}</h3>
                </button>
            </ion-item>
            <ion-item-options side="left" expandable (ionSwipe)="deleteItem($event)">
                <button ion-button color="danger" expandable>
                    <ion-icon name="trash"></ion-icon>
                    </button>
                </ion-item-options>
        </ion-item-sliding>
    </ion-list>`
