### ISSUE TITLE
ionic play rtmp live

### ISSUE THREAD

**Issue by huxiaozhong** [ionic-team/ionic#13418]
i  want to play live  with:  "rtmp://live.bim-u.com/live/7a387074-ff74-4d4d-93f0-fec4ccb32ca0",
i am reference js below:

<link href="http://vjs.zencdn.net/5.19/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/ie8/1.1/videojs-ie8.min.js"></script>
  <script src="http://vjs.zencdn.net/5.19/video.js"></script>

   <video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="640"
           height="264" data-setup="{}">
      <source src="rtmp://live.bim-u.com/live/7a387074-ff74-4d4d-93f0-fec4ccb32ca0" type="rtmp/flv">
    </video>

it cant work,error:
not compatible source was found

is any one plugin can play rtmp in ionic

**Comment by LuizTokuhara** [comment]
You have to use the Streaming Plugin for it.
https://ionicframework.com/docs/native/streaming-media/
For help use the ionic forum (https://forum.ionicframework.com/) as this is only for bug report or feature request.

Good luck!

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
