### ISSUE TITLE
Impossible to use http protocol instead of ssh

### ISSUE THREAD

**Issue by Boussarhane** [ionic-team/ionic#13412]
I'm working under a Network and some ports are blocked by the Firewall. Actually I'm trying to use http protocol instead of ssh but it doesn't work.

I changed the entry `url = git@git.ionicjs.com/usename/myproject.git` to `https://git.ionicjs.com/usename/myproject.git` but still have the same ERROR.

I think that git.ionicjs.com has 2 different IP addresses. One of them (35.162.243.99) has port 22 open and the other (35.162.243.97) doesn't.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to close this as this is the issue list for the Ionic Framework and this is not related to Ionic Framework, but rather a feature request for Ionic Pro. I believe Ionic Pro intentionally restricts access to SSH only for security purposes, but I could be wrong about that.

For Ionic Pro related issues, please consult the Ionic Pro support portal (http://support.ionicjs.com)

Thank you for using Ionic
