### ISSUE TITLE
Swipe back on iOS should lock the scrolling view

### ISSUE THREAD

**Issue by gregavola** [ionic-team/ionic#13435]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On device, you can swipe back, at the same time pulling down at a diagonal area and see the small "white" bar in the top (http://im.grega.co/0u1x3f0f2y25). This basically means you swipe back and down in a diagonal way, you can see a small sliver of the background, because it's being pushed down (via scrolling). This only happens when using ionRefresher. If the refresher is not there, no bug.

This is evident in our Production version of Untappd, if you want to see in a production app. You can also see in this repo: https://github.com/gregavola/ionic-scrolling-repo

**Expected behavior:**
Scrolling should be locked at the same time the swipe to go back in happening.

**Steps to reproduce:**
Load this repo (https://github.com/gregavola/ionic-scrolling-repo) up on your device, using DevApp or build to app. Go to the detail page, and swipe diagonal down from top left to bottom right as if you are were swiping back, but not going straight across.

A sample application via GitHub

https://github.com/gregavola/ionic-scrolling-repo

**Other information:**
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ionic info

cli packages: (/Users/gregavola/.nvm/versions/node/v6.9.1/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

local packages:

    @ionic/app-scripts : 3.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.9.1
    npm  : 3.10.8
    OS   : macOS Sierra

Misc:

    backend : pro
```

**Comment by prashantpalikhe** [comment]
+1
