### ISSUE TITLE
Slides.update() should return a future allowing blocking until it is complete

### ISSUE THREAD

**Issue by rapropos** [ionic-team/ionic#13448]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
The documentation for the slides component tells us to call `update()` when child slides are added or removed. The problem is that the app has no way of knowing when this process has completed.

**Expected behavior:**
It would be very helpful if `update()` could return a future such as a `Promise` that resolves once the update process has completed.

**Steps to reproduce:**
Create a slides component backed by an `ngFor` loop over an array. Attempt to slide to a recently added slide.

```
<ion-slides>
<ion-slide *ngFor="let quote of quotes">{{quote}}</ion-slide>
</ion-slides>

addQuote(): void {
  this.quotes.push('lorem ipsum');
  this.slides.update();
  // this won't work because the update hasn't completed yet
  this.slides.slideTo(this.quotes.length-1);

  // this works but is well below optimal
  setTimeout(() => {
    this.slides.slideTo(this.quotes.length-1);
  }, 200);

  // this is what I would like to do
  this.slides.update().then(() => {
    this.slides.slideTo(this.quotes.length-1);
  });
}
```

**Other information:**

Potentially related: #6703.

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#331

**Comment by jgerstle** [comment]
Is there any way to keep track of the internal issue? Will you update this issue when it is fixed? Right now I have a timeout setup to wait for the update which is extremely ugly.
