### ISSUE TITLE
Android : Loader no dismiss on back button press

### ISSUE THREAD

**Issue by Ayesha17** [ionic-team/ionic#13442]
In my ionic app when the back button pressed loader present and the page will change behind the loader.
How can i dismiss the loader while pressing the back button ?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
