### ISSUE TITLE
First byte missing with the file upload function

### ISSUE THREAD

**Issue by tonyniu2008** [ionic-team/ionic#13444]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[X] feature request
I am using FileTransfer to upload images and videos from IOS devices. Test with ipad air and iphone 6 plus, system version 10.3.2 and 10.3.3.

**Current behavior:**
The server side receives the binary data but the first byte of the real data is missing, for example, a jpg image taken by iOS, the file starts like this(hex): ff d8 ff e0-00 10 4a.....

However the server receives the data like this: d8 ff e0-00 10 4a.....

I manually added ff as prefix on the server side, the image can be opened without any problem.

No any operations on the file from client side, simply call the filetransferobject.upload...
Server side is Java server, REST

**Expected behavior:**
the missing byte should be there.

**Steps to reproduce:**
Maybe just on my application.

**Related code:**
    let options: any = {
      fileKey: 'file',
      fileName: fileName,
      httpMethod: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'accept': 'application/json;odata=verbose',
        'X-Upload-OriginFilename': fileName.split('/').pop(),
        'X-Upload-Filename': namewithMark,
        'X-Upload-Description': description,
        mimeType
      }
    };

ft.upload(fileName, serviceUrl, options, false).then((uploadResult: FileUploadResult) => {
      this.toast.dismiss();
      this._modalHelper.showToast(name + ' is Uploaded successfully');
      Vibration.vibrate(1000);
      return new Promise<FileUploadResult>((resolve: any) => {
        resolve(uploadResult);
      });
    }).catch(this.handleError);

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.5.0
Ionic Framework Version: 3.6.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 2.1.3
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.9.0
Xcode version: Xcode 8.3.3 Build version 8E3004b

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I believe when you say "I am using FileTransfer..." you are referring to this plugin: https://ionicframework.com/docs/native/file-transfer/

Since this is more of an Ionic Native issue then, I will use move this to the ionic-native repo for you. Please follow up on the newly created issue over there.

You may also what to have a look at the issue list (both open and closed) for the underlying plugin as there may be some help to be had there: https://github.com/apache/cordova-plugin-file-transfer

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-native#2129
