### ISSUE TITLE
ionic2 bugs: menuToggle bugs

### ISSUE THREAD

**Issue by aiyuzhou** [ionic-team/ionic#13443]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

I'm develop an app using ionic2, I met an issue these days, ususlly the menuToggle works for me, but I don't know after what operations it didn't work anymore, then I find the reason, because the ng-component directive go out of page-app, it's weird, ng-component should be inside of page-app, I want to know which operation will move the directive, did anyone meet this problem? There are two ng-component in DOM, one inside of page-app, another outside of page-app, because menutoggle control the one inside, I can not touch the one outside, so it looks like menutoggle did not work, becuase page-app is covered by the outside ng-conponent [bugpic](http://7xnh02.com1.z0.glb.clouddn.com/bugpic.png)
@jgw96 @brandyscarney

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
