### ISSUE TITLE
Ionic 2 platform height and width inconsistency with orientation changes

### ISSUE THREAD

**Issue by PavlosIsaris** [ionic-team/ionic#13452]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am trying to get the screen height and width of the platform object, but evidently the screen orientation confuses these values. (See the code snippet below)

**Expected behavior:**
I would like the screen height and width to be consistent, independently of the phone's orientation 

**Steps to reproduce:**
See the code snippet below

**Related code:**

```
platform.ready().then(() => {
      console.log("orientation", screenOrientation.type);
      console.log("platform height", this.platform.height());
      console.log("platform width", this.platform.width());

      events.subscribe('orientation-changed', (screenOrientation) => {
        console.log("orientation", screenOrientation.type);
        console.log("platform height", this.platform.height());
        console.log("platform width", this.platform.width());
      });
    });
```

**Other information:**
[https://stackoverflow.com/questions/47347816/ionic-2-platform-height-and-width-orientation-changes](https://stackoverflow.com/questions/47347816/ionic-2-platform-height-and-width-orientation-changes)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/home/pisaris/projects/batler.io_new/batler.io/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.2.1

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.4
    npm               : 2.15.12 
    OS                : Linux 3.13

Environment Variables:

    ANDROID_HOME : /home/pisaris/Android/Sdk

Misc:

    backend : legacy

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

I took your code and incorporated it into an Ionic Blank application template and the tweaked it a bit to show the results on the screen rather than in the console. Running this on my iPhone 7, I get results that make perfect sense:
 
```
Portrait
Height: 667
Width: 375
```

```
Landscape
Height: 375
Width: 667
```

And it just keeps going back and forth like that as a change the orientation. Looks logical and very consistent to me.


Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
