### ISSUE TITLE
ionic4 vue.js bindings 

### ISSUE THREAD

**Issue by msaelices** [ionic-team/ionic#13451]
**Ionic version:**
[ ] **2.x**
[ ] **3.x**
[X ] **4.x**

**I'm submitting a ...**
[ ] bug report
[X] feature request

**Current behavior:**
The 4.X version will promise framework agnostic UI components, because of ionic components will be also web components, but if we want to use in a production-ready app we would need a vue-binding, which:

Firs, avoid ignoring elements in vue.js, like this:

    Vue.config.ignoredElements = [
      'ion-app',
      'ion-page',
      'ion-header',
      'ion-toolbar',
      'ion-title',
      'ion-content',
      'ion-list',
      'ion-item',
      'ion-label',
      'ion-button',
      'ion-searchbar',
    ]
    new Vue({
      el: '#app',
      render: h => h(App)
    })

Second, be able to listen and emit the ionic component's events, deriving the web components events to the vue components.

**Expected behavior:**

As [OnSen UI does](https://onsen.io/v2/guide/vue/), we would need wrapping all the ionic components, again, as [OnSen UI does](https://github.com/OnsenUI/OnsenUI/tree/master/bindings/vue/src/components), so the use of ionic components in vue apps would be something like this:

    import Vue from 'vue';
    import VueIonic from 'vue-ionic';

    Vue.use(VueIonic);

And use the components in vue files like this:

    <template>
      <v-ion-app>
        <v-ion-page class="show-page">
          <v-ion-header>
            <v-ion-toolbar>
              <v-ion-searchbar @input="handleInput"></ion-searchbar>
            </v-ion-toolbar>
          </v-ion-header>
          <v-ion-content class="content" padding>
              <v-ion-list>
                <v-ion-item v-for="user of users" v-bind:key="user.id">
                  <v-ion-label full>{{user.name}}</v-ion-label>
                </v-ion-item>
              </v-ion-list>
          </v-ion-content>
        </v-ion-page>
      </v-ion-app>
    </template>

    <script>
    import axios from 'axios';
    export default {
      name: 'app',
      data () {
        return {
          users: []
        }
      },
      created() {
          axios.get('http://foo.com/users.json')
          .then(response => {
            this.users = response.data
          })
      },
      methods: {
        handleInput(evt) {
          // handle input
        }
      }
    }
    </script>

    <style>

    </style>
 
I'd like to collaborate in this binding if you give me that honor.

**Comment by kensodemann** [comment]
Hello! I'm going to move this issue over to our internal list of feature requests just to clear it out of this list here.

Roadmap wise, the first release of v4 will likely just have the Angular bindings, but supporting other Frameworks such as Vue.js is certainly on our radar.

Also, thank-you for your offer to collaborate with us on this. We will keep that in mind when we start the Vue.js support effort.

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#329

**Comment by msaelices** [comment]
@kensodemann I think even if you will not work on this right now, we could work together on `stencil` to be ready for other frameworks outside the TS world.

For example I'd like to derive all the ionic's components events to Vue.js events to may wrap ionic components inside vue.js ones. But I think there is no an easy way to access the registered events.

But I don't know if we can inspect enough info about the web components events. Here is a fragment of my current code:

```
export const deriveEvents = {
  computed: {
    unrecognizedListeners() {
      // remove vue prefix 'v-' from the tag name
      // so 'v-ion-button' will be 'ion-button' 
      const tagName = this.$options._componentTag.slice(2);

      // TODO: what's the correct expression?
      // Ionic.components[tagName.toUpperCase()].foo?
      // customElements.get(tagName).events ?
      const ionComponentEvents = ...;

      return Object.keys(this.$listeners || {})
        .filter(k => (ionComponentEvents || []).indexOf(k) === -1)
        .reduce((r, k) => {
          r[k] = this.$listeners[k];
          return r;
        }, {});
    }
  },
  ...
```

How can I do this? Do you think I should open an issue for that in stencil github issue tracker?

**Comment by msaelices** [comment]
@kensodemann Just for comparison, OnSen UI does this explícitly on the custom elements definition, like here: https://github.com/OnsenUI/OnsenUI/blob/master/core/src/elements/ons-pull-hook.js#L461

**Comment by kensodemann** [comment]
@msaelices - right now the whole team is basically heads down on the initial `@ionic/angular` and `@ionic/core` v4 efforts. However, I am sure your input would be welcomed. It seems the Stencil repo would make the most sense based on my reading of your question above.
