### ISSUE TITLE
rotating phone on virtual list does not calculate the height of items correctly

### ISSUE THREAD

**Issue by fssrepository** [ionic-team/ionic#13450]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[X ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
1) rotating phone on virtual list which is inside a popup does not calculate the height of items correctly - it's slipping onto each other when you rotate back to portrait mode from landscape - (the first page, when you scroll to down it displays correctly from the second page)
2) item header inside the list disappears (non-popup version also), when you scroll (appears first without scrolling)

**Expected behavior:**
Unluckily from mobile browser you cannot really lock the screen programatically, feature hasn't been supported yet - the feature is in experimental version
At least when i rotate back, the original version should come back without resets/reloads.

**Steps to reproduce:**
create a popup window with a virtual scroll-able list inside, rotate your phone - (you can emulate in a browser simply going to developer tools)

I have used elements which has a full page or third page of height in the scroll-able list!!!

It's further edge cases, which has been already fixed some times before in different scenarios. I'm using very latest version of ionic 4.

It's inside the popup without header version. (It works without popup) one card is supposed to be 1/3 of the screen, maybe you have better idea on stylesheet. (i have two cards in the same row:), but let's make it easier)
```
.card_base {
    height: 25vh;
    width: 25vh;
    margin-top: 0.75vh;
    margin-bottom: 0.75vh;
    margin-left: auto;
    margin-right:auto;
    border-radius:1vh;
}

.no_grid_padding .grid{
    padding: 0 !important;
}

.img_div {
    position: relative;
    top:4.5vh;
}
<ion-content...
<ion-list [virtualScroll]="rows" [approxItemHeight]="'100px'">
<ion-item *virtualItem="let row">
<ion-card class="card_base no_grid_padding">
    <div class="img_div">
...
```
Header version:
It's a special panel inside, which has got lot's of columns, the item-divider also contains columns, what i cannot share:

```
<ion-content...
<ion-list [virtualScroll]="rows" [headerFn]="myHeaderFn" [approxItemHeight]="'1000px'">
<ion-item-divider class="table_header" *virtualHeader="let header">
            <p style="font-size:3vh"> something </p>
            <ion-grid class="small_label">
...
</ion-item-divider>
...
<ion-item ...>
</ion-item>
```

the special component of mine needs to be fixed, but the header shouldn't disappear on scrolling

I had to admit that vh is not the right thing on rotate, but when we are rotating back, the original version of the component should appear. When you scroll the header shouldn't disappear on either way in landscape mode.

The 100px and the 1000px hasn't caused any troubles on previous versions, it was mainly unaffected.

I cannot set %, which i would have liked, or vh.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by fssrepository** [comment]
Most of the time we are developing apps, which is private, and hasn't approached any audience yet.
It cannot be shared simply. (at the top of that i have own components, which never been seen any of ionic sites, and made it for months) I think if you are really interested on the issue, as similar issues was raised and fixed, i have added a well-detailed step.

**Comment by kensodemann** [comment]
I am going to close this as something that I cannot duplicate.

If you can provide a sample application via GitHub or https://stackblitz.com that duplicates this issue I will be happy to reopen the issue and have a look.
