### ISSUE TITLE
UDP connection example.

### ISSUE THREAD

**Issue by sudhan-ionic** [ionic-team/ionic#13457]
Hi, i am currently doing remote control  RC car project with the help of the android application .So I am decided to do it in ionic framework.First screen of the application is wifi scanner. First scan all wifi device near by surrounding and then connected to my RC car wifi device. I am need to control the RC by my mobile application. so i am near most done. But I am want to send accelerometer value to RC car wifi device.  In android they pass the value by UDP. I am need a example for an a  UDP connection in ionic 3 framework.
Can you please reply as soon as possible.

**Comment by dylanvdmerwe** [comment]
Hi. I think it's best to ask this kind of thing in the [Ionic Forums](https://forum.ionicframework.com/) as this is more of a support question than an issue with the framework which is this area is for.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by sudhan-ionic** [comment]
ok
