### ISSUE TITLE
Scroll issue in ion-slides

### ISSUE THREAD

**Issue by Muneem** [ionic-team/ionic#13461]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**
I have an ionic-slides which contain main ion-slides. I have a huge page and on top I am showing this ion-slides. now I am unable to do scrolling if I hold and drag on ion-slides. Scrolling works fine if I hold and drag outside.

**Steps to reproduce:**
1) Create ion-slides. and loop it to create multiple ion-slide inside it. Set its height to 500px
2) Put image in it 
3) Put dummy data below it so you need to scroll to go to bottom of page.
4) Hold and drag ion-slides. It will not work.

**Related code:**

https://stackblitz.com/edit/ionic-e4fu6k?file=pages%2Fhome%2Fhome.html

Check this. Click and hold on ion-slides(blank area). You will be unable to drag

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I have marked this as something to look at after the initial v4 release.

Thank you for using Ionic
