### ISSUE TITLE
It's got some delay when I use "getRootNav().push(SomePage)"  popup new page and click back button to close it

### ISSUE THREAD

**Issue by rarago** [ionic-team/ionic#13463]
I used tabs to show some Parallel page,  and used  "getRootNav().push(SomePage)"  method when need to popup a new page to above tabs page,   It's about a second delay  in  IOS when click back 
 button (left arrow) ， can't operate any element in parent page. Can anyone give me some advice?
 thanks a lot~

IONIC : 3.18.0

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

If you believe you have found a bug, please open a new issue with the template fully filled out and with a sample application that demonstrates the issue you are having.

Thanks for using Ionic!
