### ISSUE TITLE
PWA Service Worker integration improvement

### ISSUE THREAD

**Issue by jmarginier** [ionic-team/ionic#13462]
With Angular 5, we can use the angular/service-worker stable library.

Currently, ionic integrate the service worker inside the index.html. 
Now, with angular 5 we can use the service-worker library as a module to register the service.

Like this : 
```
imports: [
    ...
    ServiceWorkerModule.register('service-workerr.js')
]
```
With this line, we can remove the service worker inscription from the index.html.

But, the main improvement i wanna talk is about the way to update the service worker if they are a update.

Indeed, with the default version of the service worker we use the cacheFisrt strategy.
So, if they are a update of the PWA, the client doesn't now it and keep the old PWA.
If you wanna keep update your clients you need to use the networkFirst strategy. But, with this strategy you lose speed because you need to call your server first...

So, we need a hybrid strategy : 

- use the cacheFirst strategy
- when we launch the app, we can see if the service-worker between the client and the server is the same or not
- if its the same...do nothing
- if not, tell it to the user and reload the app with the new service-worker

=> this strategy is available here (with the old service-worker of angular) : https://github.com/shprink/ionic-angular-twitter-pwa

With the new angular service-worker library, we can do that easily wih SwUpdate : 

```
this.swUpdate.available.subscribe(event => {
      console.log("new update available");
}): 
```

I think it's important default behaviour to improve ionic app's.

**Ionic version:** 
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...** 
[ ] bug report
[X] feature request

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#330
