### ISSUE TITLE
Android apk wont work on tablets only on cellphone

### ISSUE THREAD

**Issue by danielkmx** [ionic-team/ionic#13467]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Cant run android apk on android tablets, i tried creating a new app from scracth and then running android apk asap, gets me the same error "Connection to the server was unsucceful (index.html)"

this is the project repo > https://github.com/danielkmx/estudoIonic , but as i said it probably not related with the project itself, not sure what tho.
My OS is the ubuntu 16.04.

IONIC INFO:
Java version -
 java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.6.0
    npm               : 5.4.2 
    OS                : Linux 4.10

Misc:

    backend : pro

```

**Comment by kensodemann** [comment]
I am going to close this as something that I cannot duplicate.

I tried your application on a Note 4 (phone) and on a Samsung Tab (tablet) and it worked fine on each device.  Perhaps this has something to do with your personal setup or the specific devices you are using? I am not sure.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). There is a wider audience there and perhaps someone else has run into this issue.

Thanks for using Ionic!
