### ISSUE TITLE
Ability to resume ionic start when an error occurs

### ISSUE THREAD

**Issue by qwertzguy** [ionic-team/ionic#13460]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

* Make sure `ionic ssh setup` is currently **not** setup.
* Run `ionic start` up until it asks you if you want to create a new SSH key or use an existing one.
* Choose existing one and give a wrong path.
* An error is displayed and the cli exits: `[ERROR] .\none-existant-file does not appear to exist. Please specify a valid SSH public key.`
* Re-run `ionic start`
* Give the same project name
* It does not offer to resume, instead it offers to overwrite the directory and start again from the beginning

**Expected behavior:**

Have an option such as `ionic start --resume` which would go straight back to asking about creating an ssh key or using an existing one.

**Steps to reproduce:**

Just follow steps in Current behavior section.

**Other information:**

Suggestion would be for ionic to store in a file the step at which it stopped and the project folder, in order for it to resume.

This could also apply to other commands of the cli.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

cli packages: (C:\Users\gaspa\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

local packages:

    @ionic/app-scripts : 3.1.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.11.3
    npm  : 3.10.10
    OS   : Windows 10

Misc:

    backend : pro


```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This does not seem like an Ionic Framework related feature request but more of a CLI related item. I will move it over there for you.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2890
