### ISSUE TITLE
Can’t disable swipe to go back in Ionic 2

### ISSUE THREAD

**Issue by ajayadglobal360** [ionic-team/ionic#13477]
i tried <ion-nav id=“content” [root]=“rootPage” #content swipeBackEnabled=“false”>
and IonicModule.forRoot(MyApp,{ swipeBackEnabled: false }),
but still i am facing this issue

ionic info:
@ionic/cli-utils : 1.17.0
ionic (Ionic CLI) : 3.17.0

global packages:

cordova (Cordova CLI) : 7.0.1
local packages:

@ionic/app-scripts : 2.1.3
Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.5.2
Ionic Framework    : ionic-angular 3.9.1-201711081842
System:

Node : v8.7.0
npm  : 2.15.12
OS   : Linux 4.10

**Comment by RyanHow** [comment]
How did you solve this? I can't get it to disable either.

**Comment by ajayadglobal360** [comment]
Add swipeBackEnabled="false" inside ion-nav tag in app.html and also add  swipeBackEnabled: false inside imports section in app.module.
<ion-nav [root]="rootPage" #content swipeBackEnabled="false">
</ion-nav>
IonicModule.forRoot(MyApp, { swipeBackEnabled: false }),

then delete www folder and rebuild project.

**Comment by pcsantana** [comment]
In browser and on Android works fine, but in iOS (simulator or device) I still facing this problem and cannot disable the swipe back.
Anyone tried something different?

**Comment by davidArg** [comment]
facing same problem, did what ajayadglobal360 commented but in safari still backing with swipe

**Comment by pcsantana** [comment]
@davidArg for me in safari browser works fine (not go back). But when I run on iOS device or simulator, I still go back swiping, strange...

**Comment by davidArg** [comment]
pcsantana your implementation was exact like ajayadglobal360 told? its a browser app so I need disable in safari!

**Comment by pcsantana** [comment]
Yes. I just had not tried to delete the www folder. But I did and not worked too.

**Comment by davidArg** [comment]
@pcsantana ionic cli and ionic versions pls?

**Comment by pcsantana** [comment]
Sure!

``` 
cli packages: (/Projetos/appcultura/src/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.1
    ios-sim    : 4.1.1
    Node       : v7.8.0
    npm        : 5.5.1
    OS         : macOS Sierra
    Xcode      : Xcode 9.0.1 Build version 9A1004
```

**Comment by pcsantana** [comment]
I finally solved the problem, my mistake! I noticed that in my config.xml had:
```
<preference name="AllowBackForwardNavigationGestures" value="true" />
```
I just deleted it and everything worked perfectly!!
Thanks.

**Comment by davidArg** [comment]
@pcsantana good! still with the issue, aint italled any platform cos its a web aplicattion, the config.xml its only the you intall ios/android platform?

**Comment by pcsantana** [comment]
Does Google Chrome works as expected?

**Comment by davidArg** [comment]
nope, using my iphone can swipe back in chrome and safari

**Comment by pcsantana** [comment]
weird.. Did you tested in desktop browser using 'ionic serve' command line? 
Try to compare your config.xml with the [Ionic Conference App](https://github.com/ionic-team/ionic-conference-app). I discovered my mistake doing it.

**Comment by davidArg** [comment]
yes, and the canSwipeBack() method retuns false, the swipe gesture doesnt works with chrome inspector.

The problem is when I publish my www folder in a server and open the app in my iphone

**Comment by leeduyoung** [comment]
Simply, put the **"swipeBackEnabled: false"** setting in the **import: [] area of the app.modules.ts file.** Please refer to the code below.

     IonicModule.forRoot (MyApp, {
       platforms: {
         ios: {
           swipeBackEnabled: false
         },
       }
     })
