### ISSUE TITLE
Iframe not loading in Ionic DevApp Ionic Pro

### ISSUE THREAD

**Issue by lukay97** [ionic-team/ionic#13472]
Hello, Im facing the problem that my Iframes which I fill wirh youtube URLs through Pipes not showing in DevApp. In Browser and Native all works perfect. Only in DevApp they dont work.

Anyone else facing that problem?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

This could also be an issue with DevApp itself, in which case you should log a support request at the [Ionic Pro Support Portal](http://support.ionicjs.com).

Thanks for using Ionic!
