### ISSUE TITLE
wifi is not scanning in android version 6 and 7?

### ISSUE THREAD

**Issue by sudhan-ionic** [ionic-team/ionic#13478]
Hi, I am doing a project on wifi scanner, I am almost done fine but two days before wifi is not scanning in android version 6 (marshmallow) and 7 (nougat).But It works fine on version 5 and 4. May I know why this is happening.
I am done this project in ionic framework version 3.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

This could also be an issue with the hotspot plugin assuming you are using it:
https://github.com/hypery2k/cordova-hotspot-plugin

Thanks for using Ionic!
