### ISSUE TITLE
Scroll-content looses margin-top after using input focus  keyboard

### ISSUE THREAD

**Issue by gcamana** [ionic-team/ionic#13470]
Scroll-content and fixed-content looses margin-top after using input focus  keyboard

https://www.youtube.com/watch?v=4zA2cuBn-lo

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please. 

Also please be sure to include a sample application that demonstrates the issue you are having.

Thanks for using Ionic!

**Comment by xiongdg** [comment]
Hi @gcamana How do you fix this issue?
