### ISSUE TITLE
ion-tabs lifecycle events not fire.

### ISSUE THREAD

**Issue by videmort** [ionic-team/ionic#13471]
Ionic  3.9.2
Imagine that we have got 2 tabs inside ion-tabs
When you enter to one view with ion-tabs. First time events like ionViewWillEnter works fine but... when you navigate to "next" page (doing for example--> this.navCtrl.push('myNextRoute') ) and later go back to the ion-tabs view, the event ionViewWillEnter (for example) not fire in the selected tab.
If you switch between tabs, event will fire. 

Only happen when go to next view and back.

One real example is if you come from next view to previous view and need to call one function to reload some data, you cannot do it automatically because event not fire.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
