### ISSUE TITLE
Dynamic Tabs not working correctly/Initialization issues (incl. demo)

### ISSUE THREAD

**Issue by bastibense** [ionic-team/ionic#13479]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
When initializing tabs dynamically, assumingly something goes wrong during initialization. Tabs are generated using `*ngFor` from a simple array in the .ts file. 

- The tab bar/Tabs are not visible, but a click in the bottom of the window suddenly makes it appear and switch to another tab.
- Tab content is not initialized correctly, leading to unexpected behavior; layout issues and other problems
- If dynamic and "static" tabs are mixed (hardcoded/non-dynamic ion-tab), the order will be mixed up.
- After initialization (or populating the dynamic tabs property) a call to `select(0)` does nothing (ionic probably assumes the first tab was already initialized while it was not due to dynamic loading with ngFor).

The provided minimal example should demonstrate the problem. 

**Expected behavior:**
Tabs should display after the list of tabs has been assigned to the property.

**Steps to reproduce:**
- Go to https://stackblitz.com/edit/ionic-b7vglc
- Wait 2 seconds for timer that will populate the list of dynamic tabs

**Related code:**
https://stackblitz.com/edit/ionic-b7vglc

**Other information:**
These issues might be related to this problem and contain other information:

* [Ionic 3] ion-tab with *ngFor does not show tabs #13265
* ion-tabs: select() doesn't immediately set active state on initialized ion-tab #10975

**Ionic info (dev machine):**

```
cli packages: (/Users/bbense/.config/yarn/global/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

local packages:

    @ionic/app-scripts : 3.1.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v7.10.0
    npm  : 4.2.0 
    OS   : macOS High Sierra

Misc:

    backend : legacy
```

**Comment by anatoly-spb** [comment]
There is work around:
`tabs.html`
```
<ion-tabs #tabContainer *ngIf="dynamicTabs">
  <ion-tab [root]="tab1Root" *ngFor="let tab of dynamicTabs" [tabTitle]="tab.name" tabIcon="home">
   </ion-tab>
</ion-tabs>
```
`tabs.ts`:
```
...
public dynamicTabs : any[]; // make it null 
...
```

**Comment by bastibense** [comment]
@anatoly-spb Thanks for the workaround. I tried to apply that in my actual app and it seems to show the tabs after the assignment of the dynamic property, *unfortunately* there still seems to be some initialization problems with that approach (besides it's not very nice and intuitive).

Switching to another tab and then back to the initial one suddenly re-layouts the tab content; possibly calling the correct initialization code only then.

My assumption is that ion-tabs is missing some code that properly initializes the tabs and content views whenever something is changed or ngFor finished its job.

**Comment by einfochips1** [comment]
@anatoly-spb Have you successfully implement this use-case? if yes, can you tell me what solution you have applied?
I am also facing the same issue.
Thanks,
Punita
