### ISSUE TITLE
bug: Show an error page for invalid segments

### ISSUE THREAD

**Issue by ShadSterling** [ionic-team/ionic#13484]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I don’t like that I can go to http://localhost:8100/#/asdfasd and get the normal start page. I want that to be an error page.

I tried to implement this by creating a NoSuchPageComponent and setting rootPage to that in the AppComponent. (I also made NoSuchPageComponent#ionViewDidEnter navigate to the home page when no segment is present.)

This works when the browser navigates to http://localhost:8100/#/asdfasd, but if I first open any real page and then change the address bar to http://localhost:8100/#/asdfasd, I get the Ionic error handler showing “Uncaught (in promise): invalid views to insert”

Is there another way this is expected to be done?
Is there somewhere I can catch that error?
Does this have anything to do with lazy loading?
How can I make this work as I intend?

Here's the full error message:
{{{
Runtime Error
Uncaught (in promise): invalid views to insert
Stack
Error: Uncaught (in promise): invalid views to insert
    at c (http://localhost:8100/build/polyfills.js:3:18260)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:17682)
    at NavControllerBase._fireError (http://localhost:8100/build/vendor.js:46029:16)
    at NavControllerBase._failed (http://localhost:8100/build/vendor.js:46017:14)
    at http://localhost:8100/build/vendor.js:46072:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:13979)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4248:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:13919)
    at r.run (http://localhost:8100/build/polyfills.js:3:9146)
    at http://localhost:8100/build/polyfills.js:3:18750
Ionic Framework: 3.7.0
Ionic App Scripts: 3.0.1
Angular Core: 4.4.3
Angular Compiler CLI: 4.4.3
Node: 6.12.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
}}}</span>

<span is-issue-template></span>

**Comment by Polyergic** [comment]
I tried [asking in the forums](https://forum.ionicframework.com/t/show-an-error-page-for-invalid-segments/111604) and got no responses, so I tried [asking on StackOverflow](https://stackoverflow.com/questions/47294475/ionic-error-page-for-invalid-segments) and got no responses, so now I'm trying making a bug report.  Is what I want to do even possible?
