### ISSUE TITLE
html table/ion-list scroll very slow

### ISSUE THREAD

**Issue by sannaroby** [ionic-team/ionic#13481]
**Ionic version:** 
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
We’ve an html table in a page created using a ngFor. The scroll of this table it’s **very slow** in ipad mini 2/4 (no problems with android and iphone 6/7/7 plus) also with **only 50 rows**. Also the selection of the rows is very slow (we’ve a checkbox for each row, with or without click event).

- We’re using the ionic wkwebview.
- We’ve removed all unecessary code in order to exclude some our slow business logic and we’re trying with just one column.
- We are using the workaround specificied [here](https://github.com/ionic-team/ionic/issues/12733)
- We’ve tested also with ion-grid (instead html table), but the situation remains the one described above and in this view we have the constraint of vertical and horizontal scroll.
- We’ve also used the ion-list with virtual/infinite scroll, but no improvements also in this way.

**Expected behavior:**
The same android and iphone devices behavior.

**Steps to reproduce:**
See related code below.

**Related code:**

```
<div style="overflow:scroll; -webkit-overflow-scrolling:touch">
   <table cellpadding="2" cellspacing="2" *ngIf="isDataLoaded">

    <thead>
      <tr>
        <th>{{ 'general.sel' | translate }}</th>
        <th style="text-align:left" *ngFor="let column of visibleColumns">{{column.description}}</th>
      </tr>
    </thead>


    <tbody [style.height]="tableHeight">

      <tr *ngFor="let row of gridData.data;  let rowIndex = index">

        <td tappable (click)="selectRow(row, rowIndex)">
          <input  type="checkbox" [checked]="row.selected">
        </td>

        <td style="text-align:left" *ngFor="let column of visibleColumns">
          <p>{{row[column.code].valueLabel}}</p>
        </td>

      </tr>

    </tbody>

  </table>
</div>
```

**Ionic info:**
```
cli packages:

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.0.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.1
    ios-sim    : 5.0.4
    Node       : v6.11.3
    npm        : 3.10.10
    OS         : macOS High Sierra
    Xcode      : Xcode 9.1 Build version 9B55
```

**Comment by anatoly-spb** [comment]
In ionic to process large list there are two features: 

1. https://ionicframework.com/docs/api/components/virtual-scroll/VirtualScroll/
2. https://ionicframework.com/docs/api/components/infinite-scroll/InfiniteScroll/

VirtualScroll is buggable so try to use it, if you will have problem, use InfiniteScroll instead.

**Comment by sannaroby** [comment]
@anatoly-spb Thanks for your reply. We’ve also used the ion-list with virtual/infinite scroll, but no improvements also in this way.

**Comment by sannaroby** [comment]
We've solved removing this from the main.css, as indicated in [here](https://github.com/ionic-team/ionic/issues/12733):

:focus,
:active {
outline: none;
}
