### ISSUE TITLE
Bug: Alert configuration not taking effect on 'disabled' attributes from inputs

### ISSUE THREAD

**Issue by mvsouza** [ionic-team/ionic#13488]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
When an alert input, that ain't a radio button or a checkbox, have the "disabled" attribute, the input is still editable.

**Expected behavior:**
The input field shouldn't be editable.

**Related code:**

https://ionic-ni3hse.stackblitz.io

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I couldn't think of a reason not to support `disabled` on all of the various types of inputs that are allowed. Currently, it is only supported by checkbox and radio buttons. Created pull requests to fix that in v3.x and v4.x

Thank you for using Ionic

**Comment by kensodemann** [comment]
PRs are merged. If there is a new release for v3.x it will be in that (there is not currently one planned, but that could change). Otherwise it will be in v4.x

**Comment by mvsouza** [comment]
Thanks Ken!
