### ISSUE TITLE
ionic building provider files even when they aren't imported

### ISSUE THREAD

**Issue by joeypedicini92** [ionic-team/ionic#13497]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
1. Create two providers with the same class name (If using the ionic super starter it would be the items provider and the items mock provider)
2. import one of the providers in the app.module.ts
3. depending on which one (maybe the order they were created?) you will either have no problems, or you will get the 
```
ERROR Error: Uncaught (in promise): Error: StaticInjectorError[NAME]: 
  StaticInjectorError[NAME]: 
    NullInjectorError: No provider for NAME!
Error: StaticInjectorError[NAME]: 
  StaticInjectorError[NAME]: 
    NullInjectorError: No provider for NAME!
```

**Expected behavior:**
It shouldn't matter if you have two files with the same class name, if you aren't using one at all and it isn't being imported it should get ignored.

Or at least provide a better error message. It took me a few hours to track this down, for the longest time I thought it was some weird caching issue or webpack issue

**Steps to reproduce:**
See current behavior

**Related code:**
Ionic Super Starter

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is not an issue with the Ionic Framework, but _could_ be an issue with Ionic App Scripts. I will move this to that repo for you.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1328
