### ISSUE TITLE
Ionic 3 keyboard is not working properly

### ISSUE THREAD

**Issue by kennedymca** [ionic-team/ionic#13498]
When i click the ion-input the keyboard is opening, then i closed the keyboard again i click the ion-input, the keyboard was not opening, this issue need to be solve immediatly.

Ex:

 ```
<ion-content padding class="login-content">
    <ion-row>
        <ion-col col-12 class="img_logo">
            <img src="images/logo.png"/>
        </ion-col>
    </ion-row>
    <form [formGroup]="login_info">
        <ion-items>
            <ion-item>
                <ion-input type="number" placeholder="Id Number" formControlName="id_number"></ion-input>
            </ion-item>
            <ion-item  *ngIf="!login_info.controls.id_number.valid  && submitAttempt">
                <p class="login-invalid">Please enter a valid id number.</p>
            </ion-item>
        </ion-items>
        <ion-row>
            <ion-col>
                <button ion-button class="btn-login-signup" color="ret_btn_color" full (click)="login(login_info)">Login</button>
            </ion-col>
        </ion-row>
    </form>
</ion-content>
```

when i click the id_number input field the keyboard properly working first time only, again i pressed the input item the keyboard was not opening.

**Comment by antonhappel** [comment]
+1

**Comment by JaviChaques** [comment]
I have the same issue on iPad 11.1 emulator.

**Comment by dlazzy** [comment]
Same issue on LG G4 Android 7.0 and OnePlus5 Android

**Comment by rodineijf** [comment]
+1

**Comment by tw949561391** [comment]
emulator setting problem

**Comment by ofellipeaugusto** [comment]
I have same problem with emulator and device android

**Comment by ragerious** [comment]
You can add the code below  in app.scss. When I click ion-input, I find that ion-input will have two class below, and the value is "pointer-events:none".When ion-input lose focus, these two class will be remove.   I think in some situation it does not be removed. So when you click ion-input, it can't get focus.

.item-input-has-focus.input-has-focus {
    pointer-events: auto !important;
}
