### ISSUE TITLE
Bug: Opening a page with tabs in the root nav, from inside a tabbed page confuses the navigation

### ISSUE THREAD

**Issue by adigourdi** [ionic-team/ionic#13490]
**Ionic version:**
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request

**Current behavior:**
Attempting to open a page with tabs in the root nav, from inside a tabbed page confuses the navigation
It reopens the original page inside the second tab of the target page
I created a repo to demonstrate the issue, the README is more detailed
https://github.com/adigourdi/ionic-tabs-navigation-issue

The demo app has seven (7) pages
* Home
  * Home-Tab1
  * Home-Tab2
* About
  * About-Tab1
  * About-Tab2
  * About-Tab3

And attempts to open the `About` page from inside `Home-Tab1` and `Home-Tab2` in the root nav using
```
this.appCtrl.getRootNavs()[0].push('AboutPage')
```

**Expected behavior:**
The new page is opened, and the first tab on the page is visible

**Steps to reproduce:**
*See [repo](https://github.com/adigourdi/ionic-tabs-navigation-issue) mentioned above*

**Other information:**
This issue happens only when the pages are decorated with `@IonicPage` and have their own module, there is a branch [`no-page-modules`](https://github.com/adigourdi/ionic-tabs-navigation-issue/tree/no-page-modules) where the issue doesn't occur

**Ionic info:**

```
cli packages: (C:\Users\adigourdi\AppData\Roaming\npm\node_modules)
    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:
    cordova (Cordova CLI) : 7.1.0

local packages:
    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:
    Android SDK Tools : 26.1.1
    Node              : v8.9.1
    npm               : 5.5.1
    OS                : Windows 10
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I have marked this as something to have a look at after Ionic v4 is released to make sure it is fixed in that version as tabs and navigation will both be getting some extensive work in that version.

Thank you for using Ionic
