### ISSUE TITLE
Swipe back gesture does not work if page pushed to stack using getRootNavs()

### ISSUE THREAD

**Issue by akhatri** [ionic-team/ionic#13492]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If you have a view that contains tabs and one tab page has a button that pushes a page to the stack using
`this.navCtrl.push('apage');` you can use the swipe back gesture to go back to the previous page in the stack

If however, the button uses this, so that the tabs are not visible when the new page is pushed, then the swipe back gesture does not work.
`this.app.getRootNavs()[0].push('apage');`

**Expected behavior:**

The swipe back gesture should work

**Steps to reproduce:**

**Related code:**

1) Create a tab view with more than one page, and another page called 'apage'
2) On a page in the tab view add 2 buttons
3) One button should run `this.app.getRootNavs()[0].push('apage');` and the other button `this.navCtrl.push('apage');`

Note you need this at the top:
```
    public navCtrl: NavController,
    public app: App
```

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/tarang/Desktop/mobile-ios/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : ios 4.5.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.0.0
    Node       : v8.7.0
    npm        : 5.4.2
    OS         : macOS High Sierra
    Xcode      : Xcode 9.0 Build version 9A235

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by akhatri** [comment]
Hi Ken I have created a sample Ionic project via GitHub and supporting notes. Please take a look at https://github.com/akhatri/ionic-test-case

**Comment by Tarang** [comment]
+1 have same issue

**Comment by liangscc** [comment]
this same issue +1
