### ISSUE TITLE
device hardware back button issue

### ISSUE THREAD

**Issue by gaurangkela** [ionic-team/ionic#13499]
issue related to device hardware back button has raised before this, but the issue which i'm facing, i did not find it anywhere that's why i have asked here. i have also asked this question [here](https://stackoverflow.com/questions/47433416/android-device-hardware-back-button-issue)

I am working in ionic when i install application in android device the hardware back button was not working, after some R & D i got solution to register back button i have done it. but my problem is **when select option popover is open and i press back button then it dismiss the popover that's OK but when i want to reopen select option after pressing hardware back button i'm unable to open it**. registering back button uses some condition to check active portals and dismiss the active portal if any found. but it does not allow to open select option again. can anyone help me to solve this issue? my code is below...

```
platform.ready().then(() => {
      // this.config.pullVersion();
      let ready = true;


      // to handle hardware back button in android
      platform.registerBackButtonAction(() => {
        console.log("Back button action called");

        let activePortal = ionicApp._loadingPortal.getActive() ||
          ionicApp._modalPortal.getActive() ||
          ionicApp._toastPortal.getActive() ||
          ionicApp._overlayPortal.getActive();

          let view = this.navCtrl.getActive();
        if (activePortal) {

           ready = false;
            activePortal.dismiss();
            activePortal.onDidDismiss(() => { ready = true; });

            console.log("handled with portal");
            return;

        }

        if (menuCtrl.isOpen()) {
          menuCtrl.close();

          console.log("closing menu");
          return;
        }

        if (this.navCtrl.canGoBack()) {

           this.navCtrl.pop();
            console.log("poping back");

          return;
        } else {
          console.log("exiting from app");
           platform.exitApp();
            console.log("poping back");

        }

      }, 1);
    });]
```

```
 <ion-select interface="popover">
        <ion-option value="1">1</ion-option>
        <ion-option value="2">2</ion-option>
        <ion-option value="3">3</ion-option>
        <ion-option value="4">4</ion-option>
        <ion-option value="5">5</ion-option>
      </ion-select>
```

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
when select option popover is open and i press back button then it dismiss the popover that's OK but when i want to reopen select option after pressing hardware back button i'm unable to open it. 
alert control  and popover Ctrl working fine that can be open after pressing back button and closed but that is not happening with (ion-select)

**Expected behavior:**
i want that select - option (ion-select) to be open after device hardware back button is pressed 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
cli packages: (*******)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.4
    npm               : 3.10.10
    OS                : Linux 4.10

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by gaurangkela** [comment]
i got it from [here](https://github.com/ionic-team/ionic/issues/6982) ans from **laserus**

**Comment by kensodemann** [comment]
@gaurangkela - not sure I understand your last comment. Are you saying you found an answer to your issue there? or that there is some sample code over that that should be looked at?

**Comment by gaurangkela** [comment]
i got the code from the link and having the issue in that code as above mention.
i'm having issue as above from the code as mentioned above
