### ISSUE TITLE
centeredSlides doesn't work

### ISSUE THREAD

**Issue by jdnichollsc** [ionic-team/ionic#13494]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Using `centeredSlides="false"` doesn't work, the content of the slider is always centered.

**Expected behavior:**
Has the content of the slider at the top.

**Steps to reproduce:**
Create a simple slides with a list of items.

**Related code:**

```
<ion-slides *ngIf="items.length" centeredSlides="false">
        <ion-slide style="background-color: green">
            <ion-list *ngFor="let filter of items" no-margin>
                <ion-item>{{ filter.name }}</ion-item>
            </ion-list>
        </ion-slide>
</ion-slides>
```

Plunker (http://plnkr.co/edit/VukUsyh6NSjhuYj9nehz?p=preview)

**Comment by tim-hoffmann** [comment]
I can confirm this.

**Comment by GeorgeL9** [comment]
+1 on this as well. my workaround:

```
  ion-slide{
    display: block !important;
    align-items: unset !important;
  }
```

**Comment by jdnichollsc** [comment]
By other hand, a lot of components like the slider doesn't work well without the Ionic navigation. It would be much better if they worked without this dependence, improving the design of the framework :)

**Comment by lourensdev** [comment]
This is still an issue. @GeorgeL9 had the only solution, but this simply overrides the CSS instead of changing Swiper's config settings.
