### ISSUE TITLE
Can i predicate feature price by giving some past price and date in ionic 

### ISSUE THREAD

**Issue by pmathulan** [ionic-team/ionic#13501]
Can i predicate feature price by giving some past price and date in ionic 
inputs: past price and date, 
output: feature price

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. I am not entirely sure what you are asking, but it does not seem to be a question dealing with the Ionic Framework, so I am going to close this issue.

Thanks for using Ionic!
