### ISSUE TITLE
extra padding on footer on ios 11

### ISSUE THREAD

**Issue by yanglongji** [ionic-team/ionic#13505]
on iphone x, it just works fine.
but on other iphone, there's extra 4px padding on footer > toolbar, 'cause of the following css:

.ios ion-footer .toolbar:last-child{
padding-bottom: calc(constant(safe-area-inset-bottom) + 4px);
...
}

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please, including a sample application that demonstrates the issue. Thanks for using Ionic!
