### ISSUE TITLE
 not to dismiss the radio alert box when clicking outside of it on ionic 3

### ISSUE THREAD

**Issue by sudhan-ionic** [ionic-team/ionic#13507]
How to control the radio alert box?
not to dismiss the radio alert box when clicking outside of it on ionic 3

Normal alert box we using  

> enableBackdropDismiss: false

For Radio alert box what must  be use

![videotogif_2017 11 25_15 25 27](https://user-images.githubusercontent.com/33175538/33229452-2d9f8516-d1f5-11e7-92ec-a1a7edd922c4.gif)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
