### ISSUE TITLE
ionic tab - dynamic tab creation and removal - suggestion

### ISSUE THREAD

**Issue by fssrepository** [ionic-team/ionic#13509]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[X] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

If you open more than 3-4 popup in the android app, it won't render the last one. (some styles here and there, but no text on the label, no input text etc.), that's why i had to introduce the dynamic tab creation.

I must say it was horrific. There is some related bugs which throws null pointer exception on getActive call in the Tabs.js. I have changed the code a little bit, to check whether views exist at least.

```
NavControllerBase.prototype.getActive = function () {
        if (this._views) {
            return this._views[this._views.length - 1];
        }
    };
```
I think the following lines are wrong as a concept. You are forcing the developer to create a tabs instance also.
```
<ion-tabs #multi_tab selectedIndex="0" class="no_tab_bar" (ionChange)="onTabChange($event)">
		<ion-tab *ngFor="let t of tabs" [root]="t.component" [rootParams]="t.param"></ion-tab>
	</ion-tabs>
```
The tabs and the @ViewChild("multi_tab") tabRef: Tabs; are not in sync.

tabRef has been used for selecting a tab:
`this.tabRef.select(1);`

this.tabs will be updated, if you assign a new variable to it, which is also a pain, but lets talk about the real issue...

you can add tabs by pushing them.
`this.tabs.push(...)`
but you can remove tab by popping it.
`this.tabs.pop()`
or remove tabs by splice
```
let tabs = this.tabs.slice(); //clone
tabs.splice(1, 1);
this.tabs = tabs; //as mentioned earlier the assignment will trigger the update, anyway it will be missed
```
The only problem with it, that the tabRef won't be updated. (so a destroyed one remains in the list)
So next time, when you are adding a tab, which has been removed.

Noting happen...
At the moment i have made a workaround introducing a remove function in the Tabs.js (Tabs.d.ts)

```
    Tabs.prototype.remove = function(idx) {
        this._tabs.splice(idx);
        this._ids = idx - 1;
        return this.id + "-" + (this._ids);
    }
```

and when i'm splicing the tabs, i also remove manually from the tabRef. 
`this.tabRef.remove(id)` - this one should go before the this tabs splicing.

You can call this.tabRef.add, thus you can remove the this.tabs, but the problem is, it has got so many parameters, that practically you cannot do it. (I suggest to the ionic team a GE Hammurabi style checker)
(Every function/constructor should contain max. 7 parameter.)

There are issues also raised related to the NavControllerBase.prototype.getActive, but it's left as "not able to reproduce". I was able to easily reproduce, so the guy, didn't even care about it.

There are 5-10 different ways to reproduce the nullpointer issue, i just showed one.

Pls. redisgn the tab a little bit, to make it less confusing.

It's not just your fault, it's the angular fault also, as i have been forced to use NgZone to make the this.tabs updated in the view, but if you separate the two variables tabRef and this.tabs from each other, what you suggest in the developer manuals, you are bumping into hundreds of similar bugs.

It should have been like:
```
<ion-tabs #multi_tab selectedIndex="0" class="no_tab_bar" (ionChange)="onTabChange($event)">
		<ion-tab *ngFor="let t of multi_tab._tabs" [root]="t.component" [rootParams]="t.param"></ion-tab>
	</ion-tabs>
```

With the latest approach the problem is that the Tabs.add function is not usable.

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please.

Specifically the following sections:

- Current Behavior
- Expected Behavior
- Steps to Duplicate
- Sample application that duplicates the issue

With all of the extraneous commentary above, it is impossible to determine what your exact issue is.

Thanks for using Ionic!
