### ISSUE TITLE
ion-datetime not showing months properly

### ISSUE THREAD

**Issue by juanjoseadan** [ionic-team/ionic#13503]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
It's simple, when using 
`<ion-datetime min="2017-11-24" max="2020-12-31"></ion-datetime> `
control (please note the min value, the max value doesn't needs to be 2020-12-31 but needs to be at least 2 years in the future) and you tap over the control, if you change the "year" value first to "2018" the months doesn't change to "January, February, ...", they still the same as the min date value (in this case, November and December).

If you change the year to 2019 (after changing to 2018) then you'll notice that Months values changes. This bug is only happening the first time you change the year without closing the control.

NOTE: To replicate it, please don't change the day or month before changing the year value.

**Expected behavior:**
Change the months to "January, February, ..." when you change the year.

**Steps to reproduce:**
1. Create a new Ionic project with the specified version (see Ionic version below)
2. In your first Page put the specified above <ion-datetime>
3. Tap over the control (see the pop up showing in screen to change the values)
4. Change the year from 2017 to 2018
5. See the Month values not changing properly (they still in November, December)
6. Change the year again, but this time to 2019 and you'll see the Month values changing properly good

**Related code:**

```
<ion-header>
  <ion-navbar color="primary">
    <ion-title>Request</ion-title>
  </ion-navbar>
</ion-header>

<ion-content no-padding>
  <ion-list>
    <ion-item-divider text-wrap>Please enter a date</ion-item-divider>
    <ion-item>
      <ion-label><strong>Request date</strong></ion-label>
      <ion-datetime displayFormat="MMMM D, YYYY" 
                    min="2017-11-24"
                    max="2020-12-31"
                    [(ngModel)]="requestDate">
      </ion-datetime> 
    </ion-item>
  </ion-list>  
</ion-content>
```

Above code is all the HTML Code I have (don't need more than this). In the Controller I just have the "requestDate" value set as "2017-11-24".

**Other information:**
No more info

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
This is my Ionic info
```
cli packages: (C:\Users\Juan J. Adan\Projects\ExampleProject\node_modules)

    @ionic/cli-utils  : 1.7.0
    ionic (Ionic CLI) : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node : v6.11.3
    OS   : Windows 10
    npm  : 3.10.10
```

Thank you!

**Comment by fssrepository** [comment]
I just read your bug report, i haven't noticed any similar behavior.
You need to use ISO date string. new Date(date.toDateString() + ' UTC').toISOString()

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! I was able to duplicate your issue and verify it is a duplicate Issue #12319 as @fssrepository pointed out, so I will close this one. Please track issue #12319 for further updates. Also please comment on that issue with any new information you may have to share.

@fssrepository - not sure what you are getting at with the ISO date but. The OP seems to be using ISO dates (just w/o the time, which is perfectly valid) everywhere from what I can see. More clarification may be needed.

Thank you for using Ionic
