### ISSUE TITLE
Event calling issue from different component

### ISSUE THREAD

**Issue by Anindo94** [ionic-team/ionic#13500]
hello guys,

I am trying to use events for calling method defined in one component to the other component but facing some issue I am posting my code Please help any help will be a great for me...

I had created one file named creation.ts and defining a method and I am trying to use this method in home.ts but it is not happening Please see and help....!!!!

=============code===============
 creation.ts 
===============================
import { Component } from '@angular/core';  used at the rate angular/core
import { NavController } from 'ionic-angular';
import { Events } from 'ionic-angular';

@Component({
  selector: 'page-creation',
  templateUrl: 'creation.html'
})
export class CreationPage {

  constructor(public navCtrl: NavController,public events: Events) {}

  
  showMessage(message)
  {
      console.log("I am the creater");
      this.events.publish('message:shown',message);
  }

  
}
=================================
home.ts
==================================
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Message } from '@angular/compiler/src/i18n/i18n_ast';
import { Events } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController,public events: Events) {
    events.subscribe('message:shown',(message)=>{
      console.log('welcome',message);
    });
  }

}

**Comment by dotnetdreamer** [comment]
I believe the HomePage isn't loaded yet, thats why its happening. Before publishing event, make sure, the HomePage is loaded (into navigation stack using `navCtrol.push(HomePae);`

**Comment by Anindo94** [comment]
it is loading i am sending you the screenshot please tell

**Comment by Anindo94** [comment]
if you need my whole sample demo project i can send

**Comment by dotnetdreamer** [comment]
where are you calling `showMessage()` ?

**Comment by Anindo94** [comment]
in home.ts if there is some mistake please tell

**Comment by Anindo94** [comment]
please see my whole code i had defined the showMessage in creation.ts and want to get the message in console in browser

**Comment by Anindo94** [comment]
https://ionicframework.com/docs/api/util/Events/

i am following this document

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
