### ISSUE TITLE
ion-input doesn't work properly on Android using adjustPan as windowSoftInputMode

### ISSUE THREAD

**Issue by aikewoody** [ionic-team/ionic#13511]
**Ionic version:**
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**
[x ] bug report
[ ] feature request

**Current behavior:**
When you repeat the following steps twice the ion-input stops working:
- Click on the input to focus
- Click anywhere else to unfocus

After doing this I'm unable to focus on the input and use it.

**Expected behavior:**
The ion-input shouldn't stop working after being focused and unfocused twice.

**Steps to reproduce:**
ionic start test super;
cd test;
ionic build;
ionic cordova platform add android;
nano platforms/android/AndroidManifest.xml; # change adjustResize to adjustPan
ionic cordova run android;

**Other information:**
See this YouTube video for an example: https://youtu.be/QxNm05cvLGQ

**Ionic info:**

```

cli packages: (/home/$user/.npm-global/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.1
    npm               : 5.5.1 
    OS                : Linux 4.8

Environment Variables:

    ANDROID_HOME : /home/$user/Android/Sdk

Misc:

    backend : legacy

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is likely due to this issue: #13414. Will leave this open for now just in case it is something different, but should double check when we resolve #13414.

Thank you for using Ionic

**Comment by aikewoody** [comment]
This issue seems to be resolved in the latest Ionic version, this is the ionic info output:

```
cli packages: (/home/$user/ionic)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.1
    npm               : 5.6.0 
    OS                : Linux 4.8

Environment Variables:

    ANDROID_HOME : /home/$user/Android/Sdk

Misc:

    backend : legacy
```
