### ISSUE TITLE
Local Notification is not shown immediately.

### ISSUE THREAD

**Issue by ArsalanSavand** [ionic-team/ionic#13515]
Hello everyone, I'm using Ionic **3.x**.
I recently installed: Ionic Native - Local Notifications.

I installed it: `ionic cordova plugin add de.appplant.cordova.plugin.local-notification` like so.

The problem is when I trigger the schedule method for showing the notification, it has a delay for like 4 seconds and this is too much for an immediate notification.

Maybe I'm doing it wrong, but take a look at my code:
```
      this.localNotifications.schedule({
        id: 1,
        title: "Title",
        text: 'A normal text',
        icon: 'res://icon.png',
        smallIcon: 'res://icon.png'
      });
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

This could also be an issue with the plugin in which case I suggest opening an issue in the plugin's repo or in the Ionic Native repo.

Thanks for using Ionic!
