### ISSUE TITLE
Multiple tab page load page from cache

### ISSUE THREAD

**Issue by supertensor** [ionic-team/ionic#13514]
I have multiple Tab page. When I push first tab page ( TP1.ts) to nav it is loading first index page . And after I push second tab page (TP2.ts) then it load previous index 0 page of first tab page (TP1.ts). I am using lazy load to load tab page

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please. Thanks for using Ionic!
