### ISSUE TITLE
Headers of pages that are in the stack disappear when popping a page that contains a filled input.

### ISSUE THREAD

**Issue by Hadjer13** [ionic-team/ionic#13516]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request

**Current behavior:**

Headers of pages that are in the stack disappear when popping a page that contains a filled input.

**Expected behavior:**

Header displayed 

**Steps to reproduce:**

I have an ionic page , let's call it page1 and an other ionic page, let's call it page2. 
- page2 contains an input 
- push page2 from page1 using the navController 
- select the input , write in it , then leave it. 
- click on back button of page2 to go back to page1
---> the header of page1 dissappears but what it contains is still there (buttons). 

**Other information:**

**Ionic info:

```
@ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.0

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.3
    npm               : 3.10.10
    OS                : Windows 10
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
