### ISSUE TITLE
On orientation change virtual scroll not rendered correctly, ion-header has incorrect margin

### ISSUE THREAD

**Issue by fssrepository** [ionic-team/ionic#13513]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ X] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
On orientation change virtual scroll not rendered correctly, header has incorrect margin

**Expected behavior:**

**Steps to reproduce:**
1, if you have virtual scroll in the tabs and orientation has been changed, then you need to make the following:
  ```
@ViewChild(VirtualScroll) scrollRef: VirtualScroll;

@HostListener('window:resize')
  onResize() {
    console.log("resize");
    setTimeout(() => {
      this.scrollRef.readUpdate(true);
      this.scrollRef.resize();
      this.scrollRef.renderVirtual(false);
    });
  }
```
2, If you have an ion-header next to the ion-content and you are making orientation change, i had to fix it on the ion-content, as the margin-top is not calculated properly:
```
.small-margin .scroll-content {
        margin-top: 1.8vh !important;
    }
```

Reproduce (to make it more reproducible):
1, Create two tabs with virtual scroll. Each tab contains the same height of items per virtual scroll, but different height of items per tab.
2, Go to the next tab
3, Go to the chrome developer tools
4, switch to handheld mode
5, switch to landscape mode
6, switch back to portrait mode
7, repeat 5-6 several times. The margin-top will be corrupted randomly.
8, the virtual scroll does not calculate the height correctly, when it goes back to portrait mode. I had to force the 2. point mentioned earlier.

You can do also:
1, go to the next tab
2, go to landscape mode 
3, go back the previous tab
4, Virtual scroll does not calculate the height correctly, the resize should be manually triggered on tab switch. Pls. look at the fact that the item size in the virtual scroll is different per tab.

Pls. consider to create a complex virtual scroll with buttons and with different heights to make the future testing easier, instead of labeling bugs "non-reproducible".

**Comment by fssrepository** [comment]
I figured out that the virtual scroll does not handle the resize event, it needs to behavior what i have mentioned, to make it work properly.

My css file is a chaos, i need to rewrite the toggle, as MacOS safari does not handle the transform : translate3d correctly - maybe it's just because i'm using virtual machine, maybe not.

The ionic css file is full of contain. (Safari does not support it)

If i just would have started my project just now, and not a year ago, i would have rewritten the whole ionic , just the base cordova container would have remained (at ionic nobody knows how to make browser independent css), and would have made totally separate components.

At the moment i was not able to use a single plugin, because it was just wasting time. I removed all the native component, and replaced by google one. The quality of the ionic projects really frustrates me what time i have wasted in the last year on it. (it's simply degrades the productiveness - just first time, you might think that it's fine - within the timeframe until i hacked the stylesheets making work on Safari / IOS / Android and chrome), i would have rewritten the components from scratch.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
