### ISSUE TITLE
Error: Uncaught (in promise): invalid views to insert with 3.9.2

### ISSUE THREAD

**Issue by sinedied** [ionic-team/ionic#13518]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Seems similar to #11873 and #11374, which are marked as resolved.
I'm using the latest `ionic-angular@3.9.2` with `angular@5.0.3` and `rxjs@5.5.2`.

I have to specific issue when navigating through the app, except when I start using the `back` and `next` buttons of the navigation, I get this error in the console:
```
ERROR Error: Uncaught (in promise): invalid views to insert
    at resolvePromise (zone.js:824)
    at Object.eval [as reject] (zone.js:746)
    at NavControllerBase._fireError (nav-controller-base.js:322)
    at NavControllerBase._failed (nav-controller-base.js:310)
    at eval (nav-controller-base.js:365)
    at ZoneDelegate.invoke (zone.js:392)
    at Object.onInvoke (core.js:4629)
    at ZoneDelegate.invoke (zone.js:391)
    at Zone.run (zone.js:142)
    at eval (zone.js:873)
```

**Expected behavior:**
No error in the console.

**Steps to reproduce:**
1. Clone this repo: https://github.com/ngx-rocket/starter-kit
2. `git checkout cordova/ionic`
3. `npm install`
4. `npm start` to run the app (the build warning can be safely ignored)
5. Enter any login pass, then navigate a bit between home and about views
6. Click back/next on your navigator to trigger the error (tested on Chrome)

**Related code:**
See https://github.com/ngx-rocket/starter-kit, branch `cordova/ionic`

Navigation is tied to `angular-router` only for the route/events, navigation events are catched and then the Ionic router is used to navigate using `setRoot` like this:
```
  private updateNav(route: ActivatedRoute) {
    if (route.component === IonicApp) {
      if (!route.firstChild) {
        return;
      }
      route = route.firstChild;
      if (!this.nav.getActive() || this.nav.getActive().component !== route.component) {
        this.nav.setRoot(route.component, route.params, { animate: true, direction: 'forward' });
      }
    }
  }
```
Nothing too strange here, ultimately it is the Ionic router used, only reacting to URL changes.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

System:

    Node : v8.9.1
    npm  : 5.5.1 
    OS   : macOS Sierra

Misc:

    backend : pro
```

**Comment by tonysamperi** [comment]
Incredible. I did the same.
