### ISSUE TITLE
Ionic 2 ion-scroll does not show in Modal View

### ISSUE THREAD

**Issue by monsif** [ionic-team/ionic#13510]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ x] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**
Modal View PopUp and the header is  shown but not <ion-scroll> content.

**Expected behavior:**
show a scrollable list content

**Steps to reproduce:**
1- create tabs based application
2-create page-one view with a button that open a ModalView using ModalController.
3-create ModalView page wiath an ion-segment
4-in one  of the segments put the following code :+1: 

<div [ngSwitch]="startingTab">
    <ion-list *ngSwitchCase="'description'">
      <ion-item>
        <ion-thumbnail item-start>
        </ion-thumbnail>
        <h2>Description goes here</h2>
      </ion-item>
    </ion-list>

    <div *ngSwitchCase="'photos'">
        <ion-item>
        <ion-thumbnail item-start>
        </ion-thumbnail>
        <h2>Photos slides goes here</h2>
      </ion-item>
    </div>

    <div *ngSwitchCase="'views'">
     <ion-scroll style="width:100%;height:100%" scrollY="true">
    <ion-list  scroll="true">
        <ion-item>
          <ion-thumbnail item-start>
          </ion-thumbnail>
          <h2>Ruby</h2>
        </ion-item>
        <ion-item>
          <ion-thumbnail item-start>
          </ion-thumbnail>
          <h2>Oscar</h2>
        </ion-item>
               ...
        </ion-list>
      </ion-scroll>
    </div>
  </div>

**Related code:**

A sample code 
http://plnkr.co/edit/JVE9hF?p=info

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 7.1.0 
Ionic Framework Version: 3.8.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 3.0.1
ios-deploy version: 1.9.2 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.11.5
Xcode version: Xcode 8.3.3 Build version 8E3004b
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Or fix the errors in your plunkr so it presents the modal.

Thanks for using Ionic!

**Comment by monsif** [comment]
Hello, i have updated plunkr http://plnkr.co/edit/qqt3mhTdriUxS3gRbstq?p=preview
Thanks.
