### ISSUE TITLE
ion-slides takes hundreds of ms' to emit resize (intentional debounce?)

### ISSUE THREAD

**Issue by Anarkin** [ionic-team/ionic#13528]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
As per 
- platform.ts, line 814 https://github.com/ionic-team/ionic/blob/master/src/platform/platform.ts#L814
- swiper-events.ts, line 840 https://github.com/ionic-team/ionic/blob/master/src/components/slides/swiper/swiper-events.ts#L840

**Expected behavior:**
I expect that when I resize the browser, it should resize the ion-slide with close to no delay. OR I expect that I can configure the debounce value.

**Steps to reproduce:**
Resize the window with ion-slides on it, there is a huge delay (2*200 ms?) before the new width is being set for each ion-slide.

**Related code:**
- platform.ts, line 814 https://github.com/ionic-team/ionic/blob/master/src/platform/platform.ts#L814
- swiper-events.ts, line 840 https://github.com/ionic-team/ionic/blob/master/src/components/slides/swiper/swiper-events.ts#L840

**Code:**
Not my fiddle, but presents the exact issue when you resize it a couple of times: http://embed.plnkr.co/8v0nBm/

**Comment by malwatte** [comment]
Any update please?
I am using Ionic 3.9.2 and it has this issue.

**Comment by vishnuvathsan** [comment]
Below workaround gave me an improvement.
```
slides.update(10);
setTimeout(() => {
  slides.slideTo(slides.getActiveIndex(), 0, false);
}, 20);
```
