### ISSUE TITLE
(click) event fires many times in iOS fullscreen-mode(starting PWA from Home)

### ISSUE THREAD

**Issue by gekijin** [ionic-team/ionic#13527]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
(cilck) event fires many times (14 times in my situation) in iOS fullscreen-mode

**Expected behavior:**
event fires only once

**Steps to reproduce:**
Using <meta name="apple-mobile-web-app-capable" content="yes">, "Add to Home Screen" on iOS Safari, and start from Home Screen.
Tap <button (click)="onClick()"> or <h1 tappable (click)="onClick()"> element.

**Other information:**
It causes only in iOS fullscreen-mode. In iOS Safari, it doesn't.
In case of non-clickable elements without "tappable" attribute, in iOS fullscreen-mode, (click) event fires only once.
Also (tap) event fires only once in iOS fullscreen-mode.

in iOS fullscreen-mode
```
<button (click)="onClick()"> fires 14 times
<h1 tappable (click)="onClick()"> fires 14 times
<h1 (click)="onClick()"> fires only once
<button (tap)="onTap()"> fires only once
<h1 tappable (tap)="onTap()"> fires only once
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by gekijin** [comment]
I found that it causes only at components divided to another module, and started from iOS home screen.

Please open
https://gekijin.github.io/
with iOS Safari, and "Add to Home Screen".
On Safari it works correctly.
But when you start from home screen, it works incrrectly ( button and h1 with tappable count double ).

sources here: https://github.com/gekijin/gekijin.github.io/tree/master/src

**Comment by gekijin** [comment]
And I resolved.

In "home.module.ts", I used `IonicModule.forRoot(HomePage)`.
That causes (click) event many times in iOS fullscreen-mode.

Removing `.forRoot(HomePage)` and adding `entryComponents: [HomePage]` resolved it.

Bad
```
@NgModule({
  imports: [
    IonicModule.forRoot(HomePage)
  ],
  declarations: [ HomePage ]
})
```

Good
```
@NgModule({
  imports: [
    IonicModule
  ],
  declarations: [ HomePage ],
  entryComponents: [ HomePage ]
})
```

thank you.

**Comment by kensodemann** [comment]
Excellent. Sorry it took a while to be able to circle back to this one, but glad to see you resolved your issue. Yup, `IonicModule.forRoot()` should typically only be used in the application module.

If your module definition is working for you, great. Typically, it would look more like this, at least if the page uses the `@IonicPage()` decorator:

```ts
import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';

import { HomePage } from './home';

@NgModule({
  imports: [IonicPageModule.forChild(HomePage)],
  declarations: [HomePage]
})
export class HomePageModule { }
```

If your pages do not use the `@IonicPage()` decorator then ignore what I just said and carry on... :)
