### ISSUE TITLE
UIWebView margin-top problems on iOS 11+

### ISSUE THREAD

**Issue by serpaulius** [ionic-team/ionic#13536]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
[Demo](https://github.com/serpaulius/ionic-uiwebview-rotation-issues/blob/develop/bug-animation.gif)
* after rotating portrait > landscape > portrait status bar overlays the header and/or content of the Ionic app. I can see, that margin-top property in HTML is set with the wrong values on these HTML elements:
`<div class="fixed-content" style="margin-top: 44px;"></div>`
`<div class="scroll-content" style="margin-top: 44px;"></div>`
* after rotating portrait > landscape there is a huge margin between screen and header - also, the same properties are set with wrong values

**Expected behavior:**
Same, as in WKWebView:
* header/content does not hide below the cutout in iPhone X on portrait mode
* status bar does not overlap app header/content on other iPhones
* top margin on landscape view is of normal size (e.g. top margin should not increase on landscape view, like it does now).

**Steps to reproduce:**
[GitHub repository](https://github.com/serpaulius/ionic-uiwebview-rotation-issues), or:
1. start blank Ionic project
2. add these lines to config.xml (enable UIWebView):
```
    <preference name="CordovaWebViewEngine" value="CDVUIWebViewEngine" />
    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />
```
3. add iOS platform
4. run app on iOS simulator or real device.
5. rotate device: portrait > landscape > portrait
6. see the problem when rotated to landscape, and when getting back to portrait.

**Related code:**
https://github.com/serpaulius/ionic-uiwebview-rotation-issues

**Other information:**
Similar issue: https://github.com/ionic-team/ionic/issues/13294

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-plugin-proxy : 1.5.6
    @ionic/cli-utils        : 1.19.0
    ionic (Ionic CLI)       : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v6.11.2
    npm        : 3.10.10
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55

Environment Variables:

    ANDROID_HOME     : not set
    HTTP_PROXY       : not set
    http_proxy       : not set
    HTTPS_PROXY      : not set
    https_proxy      : not set
    IONIC_HTTP_PROXY : not set
    PROXY            : not set
    proxy            : not set

Misc:

    backend : legacy
```

**Comment by mhartington** [comment]
Yes this is a known limitation of UIWebview. Unfortunately UIWebview has a bug that incorrectly reports the safe-area-values. WKWebview does not have this issue though, so you should be using that instead. Unfortunately this is beyond our control with UIWebview.
