### ISSUE TITLE
Focus item doesn't scroll to it on Android when StatusBar.overlaysWebView(true)

### ISSUE THREAD

**Issue by ErnstRoca** [ionic-team/ionic#13537]
**Ionic version:**
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request

**Current behavior:**
Using `StatusBar.overlaysWebView(true)` in Android we have the desired behaviour in statusbar, but now the app is not scrolling to input when I focus it, and keyboard overlaps the input

**Expected behavior:**
The app scroll to infput when I focus it in order to not be hidden by the keyboard

**Steps to reproduce:**
use that `StatusBar.overlaysWebView(true)` and try to focus an item input in that is in the bottom of the screen

**Ionic info:**

```
cli packages: (C:\Users\esta\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 6.5.0
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.4.0 ios 4.5.3
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.4
    npm               : 5.5.1
    OS                : Windows 8.1

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

I attempted to duplicate just as you describe using an app with a text input need to bottom of the screen, but the scrolling when bringing up the keyboard worked just fine in Android and iOS. 

Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
