### ISSUE TITLE
Adding icon in radio controller ionic 3 angular4

### ISSUE THREAD

**Issue by vigneshinsta** [ionic-team/ionic#13533]
If it is any possibility to add an icon in radio alert controller using Ionic 3 Angular 4 ??

home.html

<ion-item (click)="NewLoadPost()">
    <p>Post Enquiry</p>
    <p>Truck Post /p>
 </ion-item>

home.ts

NewLoadPost(){
let alert = this.alertCtrl.create();
      alert.setTitle('Mode of Service');
      alert.addInput({
        type: 'radio',
        label: 'Transporter',
        value: 'Transport',
        checked: false
      });
      alert.addButton('Cancel');
      alert.addButton({
        text: 'OK',

        handler: data => {
          this.testRadioOpen = false;
          this.testRadioResult = data;  
         }
      });
}

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
