### ISSUE TITLE
Impossible to display on IE11 the ion-label on an ion-list or ion-datetime field

### ISSUE THREAD

**Issue by romulus001** [ionic-team/ionic#13539]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If I put one of these elements in my html pages 
```
<ion-item>
   <ion-label color="primary" stacked>My date</ion-label>
   <ion-datetime displayFormat="DDDD D MMMM YYYY" min="2017" max="2099-12-31"  [(ngModel)]="MyDate"></ion-datetime>
</ion-item>
```

or 
```
<ion-list>
  <ion-item>
     <ion-label color="primary" stacked>My list</ion-label>
          <ion-select [(ngModel)]="MyElem">
            <ion-option *ngFor="let p of ListeElem" [value]="p">{{p.label}}</ion-option>
          </ion-select>
        </ion-item>
      </ion-list>
```

the content of the <ion-label> tab doesn't display on Internet Explorer 11, it does with Firefox and google chrome, strangely, the label on an <ion-input> tag is displayed on these 3 browsers.

**Expected behavior:**
The content of the <ion-label> has to be displayed with whatever browser is used.

**Steps to reproduce:**
Explained earlier

**Related code:**
Create an html page with this code 
```
<ion-item>
   <ion-label color="primary" stacked>My date</ion-label>
   <ion-datetime displayFormat="DDDD D MMMM YYYY" min="2017" max="2099-12-31"  [(ngModel)]="MyDate"></ion-datetime>
</ion-item>
```

and open the page with Internet Explorer 11

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\Administrateur.GMT\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.3.0 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 24.4.0
    Node              : v8.4.0
    npm               : 5.3.0
    OS                : Windows 8.1

Environment Variables:

    ANDROID_HOME : C:\Users\rsarrouilhe\AppData\Local\Android\android-sdk

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

As the Ionic Framework has historically been developed for hybrid mobile applications, there was not a need to support IE. Thus it continues to not be supported at this time. We do support Edge, however, as it is far more standards compliant. Future versions may offer better IE support.

Thank you for using Ionic
