### ISSUE TITLE
使用ionic cordova build android --prod打包出来之后<a>的(tap)事件点击报错

### ISSUE THREAD

**Issue by micolas** [ionic-team/ionic#13548]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**
ionic-angular: 3.7.1
ionic-cli: 3.9.2

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
got an error 'Loading chunk 2 Failed'

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

got an error 'Loading chunk 2 Failed'

**Expected behavior:**

push a page

**Steps to reproduce:**

1.When I'm use command 'ionic cordova build android',  the app work normal on my phone(a little slow);
2.When I'm use command 'ionic cordova build android --prod', the app work little problem on my phone.  I got an error(Loading chunk 2 Failed) from the chrome console when I tap the <a> element;
3.However, it work on some other mobile phone

**Related code:**
```
        <a href="javascript:void(0);" (tap)="goToPages(menu.value,menu.id)">
          <img src="./assets/material/{{menu.icon}}" style="" class="img{{menu.value}}"/>
          <div>{{menu.name}}</div>
        </a>

    public goToPages(pageName, resId): void {
        localStorage.setItem(pageName, resId);
        this.navCtrl.push(pageName);
    }
```

**Other information:**

    "@angular/common": "4.4.3",
    "@angular/compiler": "4.4.3",
    "@angular/compiler-cli": "4.4.3",
    "@angular/core": "4.4.3",
    "@angular/forms": "4.4.3",
    "@angular/http": "4.4.3",
    "@angular/platform-browser": "4.4.3",
    "@angular/platform-browser-dynamic": "4.4.3",
    "ionic-angular": "3.7.1"
    "ionic-cli": 3.9.2
    "typescript": "2.3.4"
    "@ionic/app-scripts": "3.0.1"

**Comment by mhartington** [comment]
Hi there! This doesn't appear to be an issue with the framework it self, so I'm going to close it. Please post your question on the [Ionic Forum](https://forum.ionicframework.com) instead. Thanks!
