### ISSUE TITLE
proxies suppose postfix?

### ISSUE THREAD

**Issue by eminoda** [ionic-team/ionic#13549]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ * ] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ * ] bug report
[  ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Related code:**
I try this blew,the result is ok.
````
"proxies": [
    {
      "path": "/abc",
      "proxyUrl": "http://121.40.156.190:8888/abc"
    }
  ]
````
but use wildcard,that is not good.
````
"proxies": [
    {
      "path": "/**.api",
      "proxyUrl": "http://121.40.156.190:8888/"
    }
  ]
````

**Comment by eminoda** [comment]
in http-server.js
````
var proxyMiddleware = require("proxy-middleware");
# can use "http-proxy-middleware"?
````

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This does not look like Ionic Framework related code or configuration so I am going to close this for now. Can you provide some context on this?

Thank you for using Ionic

**Comment by mburger81** [comment]
@eminoda, this is a valid and always present FR but you should open this FR on the ionic-cli github repository and not here! Can you do this please? Refernce here the new opened request.
Thx
