### ISSUE TITLE
Ionic Latest Version for Visual Studio 2017

### ISSUE THREAD

**Issue by Devel0per95** [ionic-team/ionic#13544]
Hi! i just want to ask about when will "ionic latest version" will be available on Visual Studio 2017?

or anyway to update it manually? and how?

Thank you for your hard work "Ionic Team" 😄

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
