### ISSUE TITLE
Standalone components

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#13546]
Make sure most of ion components work and look great when used in a non-ionic app (no `<ion-app>`). 

ion-alert for example has some css issues, since the size and weight of h1 elements is defined in ion-app.

**Comment by brandyscarney** [comment]
Closing this with this commit: https://github.com/ionic-team/ionic/commit/06c9377192cb93ac17820ca4a155cd94c7c7d685

I'm sure there are some components needing more work but this brought us a lot closer.
