### ISSUE TITLE
Tried building for iPhone X once...

### ISSUE THREAD

**Issue by danielpflood** [ionic-team/ionic#13542]
Tried building for iPhone X (it worked) once and then with the exact same code base I rebuilt using ionic cordova build ios and opened xcode and tried to launch on an iphone SE simulator. I feel like I've been forced all the sudden on the most cutting edge apple software and it broke my app. I have reverted to previous commits that I know work. I am now deleting node_modules and reinstalling everything just with fingers crossed... any ideas? 

My ionic info
`hta (firebase_auth) $ ionic info

cli packages: (/usr/local/npm_packages/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 1.2.2
    Cordova Platforms  : android 6.3.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.2.1

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.1 
    ios-sim           : 6.1.2 
    Node              : v7.8.0
    npm               : 4.2.0 
    OS                : macOS Sierra
    Xcode             : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : /Users/danielpflood/Library/Android/sdk

Misc:

    backend : legacy`

My 'npm outdated'

<pre>hta (firebase_auth) $ npm outdated
Package                                            Current           Wanted         Latest  Location
@angular/common                                      4.0.0            4.0.0          5.0.3  hta
@angular/compiler                                    4.0.0            4.0.0          5.0.3  hta
@angular/compiler-cli                                4.0.0            4.0.0          5.0.3  hta
@angular/core                                        4.0.0            4.0.0          5.0.3  hta
@angular/forms                                       4.0.0            4.0.0          5.0.3  hta
@angular/http                                        4.0.0            4.0.0          5.0.3  hta
@angular/platform-browser                            4.0.0            4.0.0          5.0.3  hta
@angular/platform-browser-dynamic                    4.0.0            4.0.0          5.0.3  hta
@auth0/cordova                                       0.1.0            0.1.0          0.2.0  hta
@ionic-native/core                                   3.7.0            3.7.0          4.4.2  hta
@ionic-native/splash-screen                          3.7.0            3.7.0          4.4.2  hta
@ionic-native/status-bar                             3.7.0            3.7.0          4.4.2  hta
@ionic/app-scripts                                   1.2.2            1.2.2          3.1.2  hta
angular2-jwt                                        0.1.28           0.1.28          0.2.3  hta
angularfire2                                    5.0.0-rc.4  5.0.0-rc.0-next     5.0.0-rc.4  hta
auth0-js                                             7.6.1            7.6.1         8.11.3  hta
cordova-plugin-geolocation                           2.4.3            2.4.3          3.0.0  hta
cordova-plugin-mauron85-background-geolocation       2.3.3            2.3.3  3.0.0-alpha.7  hta
firebase                                             3.9.0            3.9.0          4.6.2  hta
ionic-angular                                        3.2.1            3.2.1          3.9.2  hta
rxjs                                                 5.1.1            5.1.1          5.5.2  hta
typescript                                           2.2.2            2.2.2          2.6.2  hta
hta (firebase_auth) $ </pre>

Now I am really not sure if i have the versions I want/need in my packages file... :/

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please.

You have a lot of info here, but none of it really describes what sort of issue you are having.

Thanks for using Ionic!

**Comment by danielpflood** [comment]
Sorry about that, must have deleted it before seeing the template. Ill try this again

**Comment by danielpflood** [comment]
Seems I fixed it by 

`rm -rf node_modules` 
and 
`npm install` 

some node files had gotten corrupted somehow I think because of git merges.
