### ISSUE TITLE
in class decorator@IonicPage, default value of segment in IonicPageMetadata , is not the value of 'name' 

### ISSUE THREAD

**Issue by GuoLunHao** [ionic-team/ionic#13557]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

**Current behavior:**
After upgrade to ionic-angular 3.9.2 , default value of `segment` property doesn't use the value of `name`, which does in the ionic-angular 3.5.3 version

**Expected behavior:**
If `segment` property isn't provided, the `segment` will use the value of `name`.

**Steps to reproduce:**
1. define two component with the same class name in two different folder, such as "PC/MainPage.ts" "Mobile/MainPage.ts"

```
@IonicPage({name:"PC_MainPage"})
@Component({
    selector: "PC_MainPage",
    templateUrl: "MainPage.html",
})
export class MainPage  {
...
}
```

```
@IonicPage({name:"Mobile_MainPage"})
@Component({
    selector: "Mobile_MainPage",
    templateUrl: "MainPage.html",
})
export class MainPage  {
...
}
```

it works well with ionic-angular 3.5.3. After I upgrade the project to ionic-angular 3.9.2 with angular 5.0.3,  ionic serve shows the errors as below:

```
[14:09:54]  watch started ...
[14:09:54]  build dev started ...
[14:09:55]  clean started ...
[14:09:55]  clean finished in 4 ms
[14:09:55]  copy started ...
[14:09:55]  deeplinks started ...
Error: There are multiple entries in the deeplink config with the segment of MainPage
```

It seems that both of segment value of two components are 'MainPage' cause the problem.

After I modify the code with explicit segment value as below, no more errors
```
@IonicPage({name:"PC_MainPage", segment:"PC_MainPage"})
@Component({
    selector: "PC_MainPage",
    templateUrl: "MainPage.html",
})
export class MainPage  {
...
}
```

```
@IonicPage({name:"Mobile_MainPage", segment:"Mobile_MainPage"})
@Component({
    selector: "Mobile_MainPage",
    templateUrl: "MainPage.html",
})
export class MainPage  {
...
}
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

We are heavily into working on Ionic v4 right now and navigation will be getting a lot of thought and rework in that version so I have marked this as something for us to investigate after v4 is released to see if it is still an issue.

Thank you for using Ionic

**Comment by GuoLunHao** [comment]
https://github.com/ionic-team/ionic/pull/13022    this pr is same with my issues
