### ISSUE TITLE
ionViewWillEnter fire two times

### ISSUE THREAD

**Issue by aiyuzhou** [ionic-team/ionic#13551]
**Ionic version:*3.19.0*  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a bug report**  (check one with "x")
[ ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior: I build an app with ionic, when I launch it in my phone(iphone, I haven't test in android), and click the tab in tabs, then I found every ionViewWillEnter in tab page will be fired two times when I click the tab first time, but then, it will be fired only once when I click it second time, thrid time....**

**Expected behavior: Actually, in ionViewWillEnter, I will init my page datas, so it will show two time every data now, but it is not my expected behavior.**

**Steps to reproduce: **

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
Did anyone met this issue?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

I have a sample project here: https://github.com/kensodemann/test-bed-tabs that writes to the console with various lifecycle events. I added this for all tabs, and am now including the ionViewWillEnter event, and I am not seeing the results you are reporting.

Thanks for using Ionic!

**Comment by kensodemann** [comment]
I am going to close this as something that I cannot duplicate.

If you can provide a sample application via GitHub that duplicates this issue I will be happy to reopen the issue and have a look.
