### ISSUE TITLE
 Downloading and extracting tabs starter - failed!

### ISSUE THREAD

**Issue by cqiuping** [ionic-team/ionic#13550]
i am new on ionic, when i am creating a app project by ionic, i encounter a problem like this
![image](https://user-images.githubusercontent.com/16223597/33420769-c227f2f6-d5ea-11e7-88be-678b83f05f71.png)

can anyone help me? thanks!

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Question: are you behind some sort of firewall when you do this (corporate, school, etc.)? If so, that could potentially contribute to what you are seeing.

Thanks for using Ionic!

**Comment by cqiuping** [comment]
thanks for explaining, and i am sorry for opening an issue on here.

**Comment by wy6395727** [comment]
@kensodemann;   I have the same problem. What should I do?

**Comment by kensodemann** [comment]
Most of the time, these sorts of issues occur if you are behind a corporate or school firewall. Would either of these situations apply to you? If so, you need to work with whoever is in charge of said firewall. If not, then there is some other issue with your network such that something that `ionic start` is trying to fetch is not accessible at the moment. Double check your proxy settings as well.

**Comment by wy6395727** [comment]
I see. Thank you very much.
