### ISSUE TITLE
Error: `msbuild` failed with exit code: 1

### ISSUE THREAD

**Issue by ragavanrajan** [ionic-team/ionic#13553]
ragavanR@401-1285 MINGW64 /e/angularAPP/myWork/firstApp
$ npm install
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> node-sass@4.5.3 install E:\angularAPP\myWork\firstApp\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> uglifyjs-webpack-plugin@0.4.6 postinstall E:\angularAPP\myWork\firstApp\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.5.3 postinstall E:\angularAPP\myWork\firstApp\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe E:\angularAPP\myWork\firstApp\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\angularAPP\\myWork\\firstApp\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.0.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\angularAPP\myWork\firstApp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\angularAPP\myWork\firstApp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\angularAPP\myWork\firstApp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\angularAPP\myWork\firstApp\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\angularAPP\myWork\firstApp\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\angularAPP\myWork\firstApp\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\angularAPP\myWork\firstApp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\angularAPP\myWork\firstApp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\angularAPP\myWork\firstApp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\angularAPP\myWork\firstApp\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\angularAPP\myWork\firstApp\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\angularAPP\myWork\firstApp\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (E:\\angularAPP\\myWork\\firstApp\\node_modules\\which\\which.js:13:12)\n    at F (E:\\angularAPP\\myWork\\firstApp\\node_modules\\which\\which.js:68:19)\n    at E (E:\\angularAPP\\myWork\\firstApp\\node_modules\\which\\which.js:80:29)\n    at E:\\angularAPP\\myWork\\firstApp\\node_modules\\which\\which.js:89:16\n    at E:\\angularAPP\\myWork\\firstApp\\node_modules\\isexe\\index.js:42:5\n    at E:\\angularAPP\\myWork\\firstApp\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\angularAPP\myWork\firstApp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\angularAPP\myWork\firstApp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\angularAPP\myWork\firstApp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\angularAPP\myWork\firstApp\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\angularAPP\myWork\firstApp\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\angularAPP\myWork\firstApp\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\angularAPP\myWork\firstApp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\angularAPP\myWork\firstApp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\angularAPP\myWork\firstApp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\angularAPP\myWork\firstApp\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\angularAPP\myWork\firstApp\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\angularAPP\myWork\firstApp\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (E:\\angularAPP\\myWork\\firstApp\\node_modules\\which\\which.js:13:12)\n    at F (E:\\angularAPP\\myWork\\firstApp\\node_modules\\which\\which.js:68:19)\n    at E (E:\\angularAPP\\myWork\\firstApp\\node_modules\\which\\which.js:80:29)\n    at E:\\angularAPP\\myWork\\firstApp\\node_modules\\which\\which.js:89:16\n    at E:\\angularAPP\\myWork\\firstApp\\node_modules\\isexe\\index.js:42:5\n    at E:\\angularAPP\\myWork\\firstApp\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp verb check python version `C:\Python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.14\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.0.0
gyp verb command install [ '9.0.0' ]
gyp verb install input version string "9.0.0"
gyp verb install installing version: 9.0.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.0.0
gyp verb build dir attempting to create "build" dir: E:\angularAPP\myWork\firstApp\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? E:\angularAPP\myWork\firstApp\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows81SDK
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.16299.Desktop
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: E:\angularAPP\myWork\firstApp\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: E:\angularAPP\myWork\firstApp\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: E:\angularAPP\myWork\firstApp\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'E:\\angularAPP\\myWork\\firstApp\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\angularAPP\\myWork\\firstApp\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\angularAPP\\myWork\\firstApp\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\RagavanR\\.node-gyp\\9.0.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\RagavanR\\.node-gyp\\9.0.0',
gyp info spawn args   '-Dnode_gyp_dir=E:\\angularAPP\\myWork\\firstApp\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\RagavanR\\.node-gyp\\9.0.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\angularAPP\\myWork\\firstApp\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\angularAPP\\myWork\\firstApp\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\RagavanR\.node-gyp\9.0.0
gyp verb found first Solution file build/binding.sln
gyp verb `which` succeeded for `msbuild` C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild.EXE
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 1/12/2017 9:47:18 a.m..
Project "E:\angularAPP\myWork\firstApp\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "E:\angularAPP\myWork\firstApp\node_modules\node-sass\build\binding.sln" (1) is building "E:\angularAPP\myWork\firstApp\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) on node 1 (default targets).
Project "E:\angularAPP\myWork\firstApp\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) is building "E:\angularAPP\myWork\firstApp\node_modules\node-sass\build\src\libsass.vcxproj" (3) on node 1 (default targ
ets).
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, ple
ase install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [E:\angularAPP\myWork\
firstApp\node_modules\node-sass\build\src\libsass.vcxproj]
Done Building Project "E:\angularAPP\myWork\firstApp\node_modules\node-sass\build\src\libsass.vcxproj" (default targets) -- FAILED.

Done Building Project "E:\angularAPP\myWork\firstApp\node_modules\node-sass\build\binding.vcxproj.metaproj" (default targets) -- FAILED.

Done Building Project "E:\angularAPP\myWork\firstApp\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"E:\angularAPP\myWork\firstApp\node_modules\node-sass\build\binding.sln" (default target) (1) ->
"E:\angularAPP\myWork\firstApp\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
"E:\angularAPP\myWork\firstApp\node_modules\node-sass\build\src\libsass.vcxproj" (default target) (3) ->
(PlatformPrepareForBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, p
lease install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [E:\angularAPP\myWor
k\firstApp\node_modules\node-sass\build\src\libsass.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.14
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\angularAPP\myWork\firstApp\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:135:13)
gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\angularAPP\\myWork\\firstApp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\angularAPP\myWork\firstApp\node_modules\node-sass
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN Error: EPERM: operation not permitted, scandir 'E:\angularAPP\myWork\firstApp\node_modules\cryptiles\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'E:\angularAPP\myWork\firstApp\node_modules\cryptiles\node_modules'
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'E:\\angularAPP\\myWork\\firstApp\\node_modules\\cryptiles\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\RagavanR\AppData\Roaming\npm-cache\_logs\2017-11-30T20_47_20_065Z-debug.log

ragavanR@401-1285 MINGW64 /e/angularAPP/myWork/firstApp
$ ionic serve
Error: Cannot find module 'E:\angularAPP\myWork\firstApp\node_modules\@ionic\app-scripts'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\RagavanR\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\lib\ionic-angular\app-scripts.js:9:16)
    at Generator.next (<anonymous>)
    at C:\Users\RagavanR\AppData\Roaming\npm\node_modules\ionic\node_modules\tslib\tslib.js:103:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\RagavanR\AppData\Roaming\npm\node_modules\ionic\node_modules\tslib\tslib.js:99:16)
    at Object.importAppScripts (C:\Users\RagavanR\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\lib\ionic-angular\app-scripts.js:7:20)

+++++++++++++++++++++++++++++++++++++++++++++++++
Downgraded my npm > Still couldnt create project 

$ ionic info
[ERROR] Error with .\node_modules\@ionic\app-scripts\package.json file: FILE_NOT_FOUND

cli packages: (C:\Users\RagavanR\AppData\Roaming\npm\node_modules)

    @ionic/cli-plugin-proxy : 1.5.6
    @ionic/cli-utils        : 1.19.0
    ionic (Ionic CLI)       : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : not  #installed
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v9.0.0
    npm  : 4.6.1
    OS   : Windows 7

Environment Variables:

    ANDROID_HOME     : not set
    HTTP_PROXY       : http://mycompanyproxy:portnumber
    http_proxy       :  http://mycompanyproxy:portnumber
    HTTPS_PROXY      : not set
    https_proxy      : not set
    IONIC_HTTP_PROXY :  http://mycompanyproxy:portnumber
    PROXY            : not set
    proxy            : not set

Misc:

    backend : pro

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
