### ISSUE TITLE
ionic app window.location.reload

### ISSUE THREAD

**Issue by Sevenonclick** [ionic-team/ionic#13558]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

I build an app with ionic.
Every times `window.location.reload()` was executed, the app would shutdown,I have to kill that manually
I wonder how to fix it? It's very important .

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? I just added the following code to one of my apps and hooked it up to a button:

```ts
reload() {
    window.location.reload();
  }
```

Works fine...

If you could provide a minimal sample application that demonstrates the issue, that would be very helpful.

Also, please provide the output of the `ionic info` command when run from your project's root.


Thanks for using Ionic!

**Comment by kensodemann** [comment]
I am going to close this as something that I cannot duplicate.

If you can provide a sample application via GitHub that duplicates this issue I will be happy to reopen the issue and have a look.
