### ISSUE TITLE
ionic cordova build --prod Field 'browser' doesn't contain a valid alias configuration

### ISSUE THREAD

**Issue by lijieQAQ** [ionic-team/ionic#13556]
ionic3 if use ionic cordova build is ok! but use ionic cordova build --prod Field 'browser' doesn't contain a valid alias configuration

**Comment by Bleno** [comment]
+1

**Comment by GuoLunHao** [comment]
I have the same error here. It seems that ng cli, which ionic use for AoT, is not reporting errors correctly. 
I tried running `./node_modules/.bin/ngc` to find out the correct errors in my project.  After solving all errors , `ionic cordova build --prod ` works for me with no errors.

**Comment by jjjhanreyyy** [comment]
Adding more info about the project would be helpful.

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please.

Also providing a sample application via GitHub is always super helpful in duplicating and testing these issues.

Thanks for using Ionic!

**Comment by hubofhugo** [comment]
Had the same issue, did what GuoLunHao suggested - worked a charm.

I tried running ./node_modules/.bin/ngc to find out the correct errors in my project. After solving all errors , ionic cordova build --prod works for me with no errors.

**Comment by tskweres** [comment]
after I run ./node_modules/.bin/ngc , where do I look for the errors? My IDE is showing a bunch of new files generated, but no errors or warnings in the console
