### ISSUE TITLE
Browser back button from one page to another with the same controller does not fire

### ISSUE THREAD

**Issue by ericeslinger** [ionic-team/ionic#13554]
I'm pretty sure the line to blame is here - I've been stepping through the code.

https://github.com/ionic-team/ionic/blob/52c40da986c4455c0e1a5edaa8e6ffe2bd914a27/src/navigation/deep-linker.ts#L406

The scenario: I load a page at url `/items/1` in my browser, then click a link to load `/items/2`. This link can either setRoot() or push() the state into the nav stack, the behavior is the same. If you press the back button in the browser, nothing happens - the browser URL changes to `/items/1` but is still displaying `/items/2`. This "nothing happens" behavior only occurs when you're backing from one page to another that have the same page component class, but different URL parameters (item ids or whatever).

Pressing the back button in the browser will end up falling to the above line, where `viewController.id` is `ItemDetailComponent` (or whatever the name of the page component is), and that's the same as `segment.name`. 

I can work around this by manually setting the  page component's viewController.id in my page component constructor (just `this.vc.id = '/items'+id;`) but this feels super-brittle; I have no clue where else the viewController id is being set.

I think the comparison to see if we can say 'hooray we can recycle the item' needs to include a check to see if the viewController being pulled off the stack has the same navParams that the one we are proposing navigation to would have.

**Comment by ericeslinger** [comment]
yeah, a little deeper digging seems to indicate that the view controller's id is set here: 

https://github.com/ionic-team/ionic/blob/52c40da986c4455c0e1a5edaa8e6ffe2bd914a27/src/navigation/nav-util.ts#L20

and is used in NavControllerBase.getViewById() which, other than used by users, also plays a role in tab navigation.

It's possible that this is As Intended - I know Angular herself will recycle some view components (you have to listen to ngOnChanges for the new nav params) - maybe I just need to pay closer attention to a certain event, or does manually writing the id property of my viewController make sense as a workaround?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

Which event(s) are you looking to have fire?
I believe ionViewWillEnter and ionViewDidEnter will fire, but the "Load" events will not because the controller will still be cached. I _think_. But it would be best to prove that out via a sample application.

Thanks for using Ionic!

**Comment by ericeslinger** [comment]
None of the events fire (they fire just fine when clicking into the page, but the entire page lifecycle is skipped when the back button is pressed, as the referenced code just returns out of the event handler instead of calling popTo anywhere. I'll work on making an example case, but as (a) i've built a workaround and (b) this seriously does just look like bad logic on the line I specified, it may take a little bit before I can get to that.

**Comment by ericeslinger** [comment]
aha, here's the repro

https://github.com/ericeslinger/router-test

**Comment by ericeslinger** [comment]
hilariously, I can fix all of this by doing something like

```
window.history.pushState('foo', null, '/items/4');
window.history.pushState('foo', null, '/items/4');
window.history.back();
```

instead of navigating using the navController at all (push it twice, then pop to get the router to notice).

**Comment by ericeslinger** [comment]
okay, so the issue is here: 

https://github.com/ionic-team/ionic/blob/52c40da986c4455c0e1a5edaa8e6ffe2bd914a27/src/navigation/nav-controller-base.ts#L833

and here:
https://github.com/ionic-team/ionic/blob/52c40da986c4455c0e1a5edaa8e6ffe2bd914a27/src/navigation/nav-util.ts#L20

in nav-util, if you passed in a string as the name for a view (which is really handy for both lazy-loading and avoiding circular dependencies if you've got pages that can navigate to each other), it sets the created viewController's id value to the string name of the page inserted. I'm 95% certain this is a mistake and the id should be left unset. In the nav-controller-base line I highlighted, the new viewController is given an id even if it is currently unset, and this id is unique to the particular combination of view name and route parameters.

I think just changing the line in nav-util should fix the bug, but I'm not 100% sure about this, as it smells like a value that's used in a lot of different places, so there could be ramifications.

**Comment by ericeslinger** [comment]
interestingly, somewhere else, the viewController's id value gets set to its url when it's on the stack - like if I back into it, it goes from being named something like `n4-4` to `items/2`.

**Comment by kensodemann** [comment]
Thank-you very much. That will likely be very helpful as we move forward with the nav system in v4 where it is currently getting a lot of attention.

Also, I have to say that you have one of the best profile pics I have seen in a while. Love it! :)

**Comment by ericeslinger** [comment]
Honestly? Not really. I have migrated away from ionic for the project I was working on; the native angular pwa support was sufficient for my needs, and the angular router behaves a lot more "correctly"  (state following URL instead of URL being set as a side effect of state change)
