### ISSUE TITLE
Web Animation API types conflict with `animate` property on ActionSheet and Alert

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic#13565]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Was in https://github.com/jgw96/stencil-beer and had the web animations api types installed. This then threw an error with the latest ionic/core: 

``` 
[ ERROR ]  typescript: Users/justinwillis/Projects/ionic/packages/core/dist/collection/components.d.ts, line: 79
           Interface 'HTMLIonActionSheetElement' cannot simultaneously extend types 'ActionSheet' and 'HTMLElement'. 
           Named property 'animate' of types 'ActionSheet' and 'HTMLElement' are not identical. 

     L78:  };
     L79:  interface HTMLElementTagNameMap {  
     L80:    "ion-action-sheet": HTMLIonActionSheetElement;

[ ERROR ]  typescript: Users/justinwillis/Projects/ionic/packages/core/dist/collection/components.d.ts, line: 148
           Interface 'HTMLIonAlertElement' cannot simultaneously extend types 'Alert' and 'HTMLElement'. Named property 
           'animate' of types 'Alert' and 'HTMLElement' are not identical. 

    L147:  };
    L148:  interface HTMLElementTagNameMap {
    L149:    "ion-alert": HTMLIonAlertElement; 
```

**Expected behavior:**

**Steps to reproduce:**

- `git clone https://github.com/jgw96/stencil-beer && npm install`
- `npm link` the latest ionic/core
- `npm run dev`

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by mhartington** [comment]
Fixed via b31591b
