### ISSUE TITLE
Unexpected token ILLEGAL, white screen of death

### ISSUE THREAD

**Issue by rtmfpuser** [ionic-team/ionic#13569]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I download ionic conference app demo, remove the crosswalk plugin, and run it on android virtual device(x86 image, android 5.1.1), the app throws following error:
Runtime Error 
Unexpected token ILLEGAL

if i close the error page by clicking the close button, the app enters into a white screen of death. 

**Expected behavior:**

no error of this kind, no white screen of death.

**Steps to reproduce:**

1. download ionic conference app demo from github.
2. npm install to install all required plugins.
3. remove the crosswalk plugin in order to mimimize the apk size.
4. remove google maps link from index html file, because google is blocked by state fire wall
5. run the app into an Android Virtual Device( x86 image, android 5.1.1) with following command
    ionic cordova run android --livereload --target AVD511

**Related code:**
if i click the error from the chrome dev tools, the link goes to this code line:

           selector: 'page-about',template:/*ion-inline-start:"C:\developement\ionic-conference-app-master\src\pages\about\about.html"*/`<ion-header>\n  <ion-navbar>\n .....
![screenshot_1512353505](https://user-images.githubusercontent.com/4475189/33533424-fd83bcba-d8db-11e7-9c0d-d39546e0cdd6.png)

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
cli packages: (C:\Users\XD\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.6.0
    npm  : 4.3.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
![qq 20171204101839](https://user-images.githubusercontent.com/4475189/33533517-93d3a112-d8dc-11e7-95a5-964e15977bfe.png)
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Could you share your modified source via GitHub?

Thank you for using Ionic

**Comment by rtmfpuser** [comment]
thanks for the reply. actually I didn't make any changes to the source code downloaded from https://github.com/ionic-team/ionic-conference-app, except that:

I removed the crosswalk plugin with the following command:
ionic cordova plugin remove cordova-plugin-crosswalk-webview.

BTW, if i shouldn't remove that plugin, it would have worked well on the virtual device( x86 image, android 5.1.1). In that case, 2 apks will generated, on is for arm, and the other is for x86.  each of them has a very big size.

**Comment by cylon007** [comment]
Hi Don't know if this will help but:

I reproduced and it seems if you set the android target 5.x this message appears while > android 5.x will run

**Comment by cylon007** [comment]
Hi try this [https://stackoverflow.com/questions/47328879/ionic-unexpected-token-illegal-only-when-running-in-android-5-emulator/47682395#47682395](stackoverflow)

**Comment by rtmfpuser** [comment]
Thanks for your reply. actually unlike ios, many users are still using android lower version, and this issue was first reported by a local android app market to me. that's why I cannot ignore the lower version. For the suggested stackoverflow solution, i will try later. Thanks anyway.

**Comment by cylon007** [comment]
If the stackoverflow suggestion work mark it correct there. I need the rep.

**Comment by rtmfpuser** [comment]
hello cylon007, thanks for the solution. and starting from the stackflow post, i found my issue may overlap with this issue:
https://github.com/ionic-team/ionic/issues/13379

i tried the solution, upgrading app-scripts to 3.1.1 can fix the issue. Thanks and best regards.
