### ISSUE TITLE
Docs: Add deprecation notice for @ionic-native/contacts

### ISSUE THREAD

**Issue by tobiasmuecksch** [ionic-team/ionic#13567]
**I'm submitting a ...**  (check one with "x")
[X] Request to refactor the official docs.

**The situation**
over a week ago there was a deprecation notice added to Cordova-plugin-contacts. These guys even shutdown the issue tracker....

**More Info**
See the README.md under the following link for the deprecation info:
https://github.com/apache/cordova-plugin-contacts

**My Request**
I'd suggest to add a deprecation notice to the official ionic docs under this link:
http://ionicframework.com/docs/native/contacts/

**Also see**
https://github.com/ionic-team/ionic-native/issues/2153

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The documentation for any of the Ionic Native stuff is generated based on documentation comments in the code for the various plugins. Thus it is not really part of the Ionic Framework code. I suggest creating this request in the Ionic Native repo: https://github.com/ionic-team/ionic-native

Thank you for using Ionic

**Comment by tobiasmuecksch** [comment]
@kensodemann Well, as you can see in the issue I've created an issue in the native repo too. But since the ionic-team obviously ignores issues in any repos other than the main ionic repo, I've added it to this repo, where issues usually aren't ignored.
