### ISSUE TITLE
platform.registerBackButtonAction() not working build --prod 

### ISSUE THREAD

**Issue by leeduyoung** [ionic-team/ionic#13566]
hi.

I am work on the project using ionic 3.
$ IONIC CORDOVA RUN command to run in app. normal operation..
However, if you use the $ IONIC CORDOVA RUN ANDROID - PROD option, platform.registerBackButtonAction () will not work.
<img width="1367" alt="2017-12-02 1 07 28" src="https://user-images.githubusercontent.com/10377728/33511648-cbf75df8-d761-11e7-8a39-625958586b54.png">

My source code is below.
<img width="689" alt="2017-12-02 12 52 08" src="https://user-images.githubusercontent.com/10377728/33511616-208af452-d761-11e7-8cbf-bd7503215312.png">

how can i fix it?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by leeduyoung** [comment]
There are no samples in the cloud.
The key is that the value of currentPage.name changes.
$ ionic cordova run android command is normal.
but, If you use the --prod option, the value of currentPage.name appears as "l" on all pages.
What's the problem?

<img width="456" alt="2017-12-16 4 24 01" src="https://user-images.githubusercontent.com/10377728/34068484-10a1f4f0-e27e-11e7-85a2-b8b34659c974.png">

**Comment by leeduyoung** [comment]
I solved using instanceof.
uglify changed the current page name.

**Comment by kensodemann** [comment]
This is most likely related to https://github.com/ionic-team/ionic/issues/13718, which was fixed with version `3.1.7` of `@ionic/app-scripts`.

Please update your app-scripts then remove all of your `node_modules` and reinstall (`npm i`)

If that does not fix this issue, let me know and we can reopen it.

**Comment by franzisk** [comment]
How did you solve using instanceof?

I have:
```
this.platform.registerBackButtonAction(() => {
  let nav = this.app.getActiveNavs()[0];
  let activeView = nav.getActive();
  let pageName = activeView.name;
  this.global.showPopup("Closing...", "Page: " + pageName, function () {});
  if (pageName === 'HomePage' || pageName === 'LoginPage') {
    if (new Date().getTime() - lastTimeBackPress < timePeriodToExit) {
      this.platform.exitApp(); //Exit from app
    } else {
      this.global.showToast('Press BACK BUTTON again to confirm you want to exit the App');
      lastTimeBackPress = new Date().getTime();
    }
  }
});
```

**Comment by mkabdul** [comment]
Use like below...
let currInstance = this.navCtrl.getActive().instance;
if (currInstance instanceof LoginPage)
