### ISSUE TITLE
Help please 

### ISSUE THREAD

**Issue by usmanakram1996** [ionic-team/ionic#13564]
![image](https://user-images.githubusercontent.com/19502075/33497213-fa548da6-d6ee-11e7-91e9-53c464f4226d.png)

Using Ionic Storage and storage.get() giving this error again and again 
Please help in resolving it

**Comment by msevestre** [comment]
@usmanakram1996 Check that out
https://medium.com/@nisalperi/how-i-solved-the-localstorage-quotaexceedederror-dom-exception-22-b69db46f0cee

You are probably attempting to save too much data in local storage.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
