### ISSUE TITLE
Stacked labels unable to focus

### ISSUE THREAD

**Issue by eb-clickfusion** [ionic-team/ionic#13560]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x ] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**

On android, when two ionic inputs with stacked labels are next to each other, if you click in the first one then click the second, you are unable to click back in to the first.

**Expected behavior:**

You should be able to click between inputs freely.

**Steps to reproduce:**

See the stacked label demo page: https://ionicframework.com/docs/components/#stacked-labels and select the android platform. Click the username field, then click the password field, then you are unable to click back in to username.

**Comment by madara134** [comment]
me too !

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I was only able to duplicate this in the following situations:
1. Chrome or Opera using our documentation with the Android emulation
1. Chrome or Opera using devtools and Android emulation

I was not able to duplicate via our documentation and any other browser. For example, if you use Firefox and go to  https://ionicframework.com/docs/components/#stacked-labels and click Android it works just fine.

I was not able to duplicate in any browser when running the app as a web app.

I was not able to duplicate when the app was installed on an actual device.

This leads me to believe that this is not an issue with the Ionic Framework but is an issue with the current version of Chrome. If you are able to duplicate this outside of the specific combination of Chrome and Android emulation, especially if you can duplicate this when installed on an actual device, please share the sample code required to do so via GitHub and I will be happy to re-open this issue.

Thank you for using Ionic
