### ISSUE TITLE
Feature Request: Fully support PopoverController API options for ion-select

### ISSUE THREAD

**Issue by mharrisn** [ionic-team/ionic#13572]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently, PopoverController API options cannot be applied to ion-select. AlertController and ActionSheetController are supported by passing `selectOptions`, but options like `mode` are not supported when the `interface` is set to `"popover"`.

**Expected behavior:**
Expect to be able to set API options like `mode` for PopoverController

**Steps to reproduce:**
Add ion-select component and set `interface="popover"` and define `selectOptions` for the component as: 
```
{
    mode:'ios'
  }
```

The component's functionality breaks with this defined.

**Related code:**
https://stackblitz.com/edit/ionic-pvhxw7

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#332
