### ISSUE TITLE
Documentation Question

### ISSUE THREAD

**Issue by granthoff1107** [ionic-team/ionic#13577]
I'm attempting to implement infinite scroll, you seem to wrap the call to pull new data in a set timeout, 
 It's not clear why?  Can you explain and update your documentation to explain as well   

       setTimeout(() => {
          for (let i = 0; i < 30; i++) {
            this.items.push( this.items.length );
          }

           console.log('Async operation has ended');
           infiniteScroll.complete();
        }, 500);

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this is more of a support question I am going to close this issue.

I urge that you ask questions like this on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

To answer your question, though, the documentation is just an example, and the timeout is being done to simulate an asynchronous fetch of data.

Thanks for using Ionic!

**Comment by granthoff1107** [comment]
@kensodemann thanks for answering and not making me repost this.
