### ISSUE TITLE
Card title position vertical centering - card-background-page

### ISSUE THREAD

**Issue by gubbigubbi** [ionic-team/ionic#13578]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request

**Current behavior:**

Cards with a background image and text overlay could vertically center much better (i.e. 2 lines of text is not vertically centered)

**Expected behavior:**

**Steps to reproduce:**

Add a longer title and subtitle to a card with a background image.

**Related code:**
To have the title center perfectly wrap the card-title & card-subtitle divs in another div like this:

```
       <ion-card (click)="openProductPage(product)" class="card-has-background-image">
          <img [src]="product.images[0].src" /> 
          <div class="card-text is-vertically-centered">
            <div class="card-title">
              {{ product.name }} 
            </div>
            <div class="card-subtitle">
              Starting at {{ product.price }}
            </div>
          </div>
        </ion-card>
```

Then adjust your sass as follows:

```
.ios, .md {
    .card-has-background-image {
        .card-text { 
            padding-left: 8px; 
            padding-right: 8px; 
            &.is-vertically-centered {
                position: absolute;
                transform: translateY(-50%);
                top: 50%;
                width: 100%;
                > div {
                    position: relative; 
                }
            }
        }
    }
}
```

Now the card title will be perfectly v-centered no matter how many lines the title or subtitle wrap onto. You could also use flexbox to acheive the same effect.

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#333
