### ISSUE TITLE
App Does not Sync with ionic-view and github repositories

### ISSUE THREAD

**Issue by vinayak-dataman** [ionic-team/ionic#13570]
Hi,
I am working on IONIC App based on IONIC 2 and Made three commit. Whenever we sync it with IONIC View. it does not take latest instance. So Client pointing about the structure of code is not on IONIC 2. Please provide ionic 2 Office Project Structure and Please suggest what kind of issue and how i can resolve it.

Thanks and Regards,
Vinayak

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. This seems to be an Ionic Pro support issue, so I am going to close this issue.

Please log this issue on the [Ionic Pro Support Portal](http://support.ionicjs.com).

I am assuming you pushed your changes both to GitHub and to the Ionic Pro remote and that you have the builds set up correctly, but it would probably be good to double check that.

Thanks for using Ionic!
