### ISSUE TITLE
calling SetRoot() not closing certain ionic controls (ion-select, ion-datetime)

### ISSUE THREAD

**Issue by MattHirdler** [ionic-team/ionic#13575]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.19.0**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you are on a page that has a control such as a ion-select or datepicker open, and you navigate away using setRoot(), the page navigates but the controls remain open and active on the screen.

**Expected behavior:**
navigating to a page automatically closes open controls/inputs from the previous page (or better yet an API solution to configure behavior)

**Steps to reproduce:**
1. create application with two pages
2. on page one, create a ion-datetime control
3. set timer to programatically navigate to second page
4. open application and click on ion-datetime control to open the modal
5. wait for timer to navigate to second screen
6. see that the datetime picker has remained open after navigation

**Related code:**
`<ion-datetime displayFormat="MM/DD/YYYY" name="dob" formControlName="dob" required placeholder="Date of Birth" #dob></ion-datetime>`

```
setTimeout(
            function () {
                self.navCtrl.setRoot(LanguageSelectComponent);
            }, 2000);
```

**Ionic info:**
```
cli packages: (/home/matt/connected_repo/Mobile/connected_mind/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.1.4
    npm               : 5.5.1
    OS                : Linux 4.10

Environment Variables:

    ANDROID_HOME : /home/matt/Android/Sdk

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Can you please provide a use case for this functionality and a sample application via GitHub that demonstrates the issue and the use case for the functionality.

If this is addressed, it will be after v4 is released, but I want to make sure we have the use case clear so we can address it in the most logical way possible.

Thank you for using Ionic

**Comment by mymai91** [comment]
Same issue

**Comment by Pankaj2109** [comment]
same Issue. Any solution on this??
navigating using setRoot(), but <ion-datetime> overlay still opened.
