### ISSUE TITLE
Same parallax background on multiple slides.

### ISSUE THREAD

**Issue by romain10009** [ionic-team/ionic#13584]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[] bug report
[X] feature request

**Current behavior:**
It wont use the div with class bg-parallax as a background that slowly parallaxes to the side as each slide is slided. The documentation is quite unclear about that, it just mentions to go to Swiper/api page which does not tell me how to setup the background-parallax feature for ionic.

**Expected behavior:**

I would like to setup one parallax background that would slowly move to the side as total slider progressions goes forward.

this is what i would like :  slide 1 out of 5 the .bg-parallax div is moved 50px to the side. Slide 2 out of 5 it is moved 100px to the side and so on... 

**Steps to reproduce:**

Create an ion-slides directive, put a few ion-slide in there, try to set up a parallax background. Wont work. See code below for my "closest to working" trial.

**Related code:**
Typescript class : 
`
export class Test{
     public slideItems = ['','','',];
}
`
Template for the page :
```
<ion-content>
  <ion-slides #slides [pager]="true" [parallax]="true" (ionSlideDidChange)="slideChanged($event)">
    <div
      class="bg-parallax"
      style="background-image:url(https://loremflickr.com/320/240/)"
      data-swiper-parallax="-23%"></div>
    <ion-slide *ngFor="let slide of slideItems; let i = index">
      I'm slide {{i}}
    </ion-slide>
  </ion-slides>
</ion-content>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by cklaffer** [comment]
+1

**Comment by maximilianloy** [comment]
+1
