### ISSUE TITLE
Gradient for status bar colour

### ISSUE THREAD

**Issue by KevinShiCA** [ionic-team/ionic#13583]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

Is there a way to make the StatusBar colour a gradient?

I have tried the following with no success:
`statusBar.backgroundColorByHexString('linear-gradient(to left, #00bee4 0%, #0091d2 100%)');`

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. I am going to close this issue as it is not related to the Ionic Framework.

Here is the documentation for the method you are using:
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-statusbar/#statusbarbackgroundcolorbyhexstring

You can also ask questions like this on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
