### ISSUE TITLE
White navbar on ios and empty page on android when using the backbutton 

### ISSUE THREAD

**Issue by Niavart** [ionic-team/ionic#13580]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
From root: I pushed a page, then another. From here, I used the back button in the nav bar. On android, the whole page is white/empty. On iOs, the navbar is white. However, everything is still here, just hidden (clicking/tapping where buttons should be still work).

I don't think I used tricky css or html but I'm pushing pages through a event. (Root page subscribe to an event and child emit the event. Then root page push the correct data). The navbar back button isn't caught.
Root (List Page) is not lazy loaded ? (not module) but every child pushed is.

Looking with chrome inspector, I noticed this: (modal-infographie is NOT a modal and is the page I am supposed to see) (this css does not come from my code)
![wtfionicemptypage](https://user-images.githubusercontent.com/17954037/33614060-93a13fe2-d9d6-11e7-9c57-ff862c13c1ab.JPG)

```
element.style {
  z-index: 99;
  opacity: 0;
  transform: translateY(40px);
}
.ion-page.show-page {
  opacity: 1;
}
```

Putting !important to `opacity: 1` or removing `opacity: 0` showed the page again (removing transform put the navbar at the correct place).
If I use navctrl.pop() instead of the back button, it work correctly.
It looks like [this issue](https://github.com/ionic-team/ionic/pull/6361) but my ionic is up to date and the project was created a few months ago (using aws-starter)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```                                              
    @ionic/cli-utils  : 1.19.0                          
    ionic (Ionic CLI) : 3.19.0                          
                                                        
global packages:                                        
                                                        
    cordova (Cordova CLI) : 7.1.0                       
                                                        
local packages:                                         
                                                        
    @ionic/app-scripts : 3.1.0                          
    Cordova Platforms  : android 6.3.0 ios 4.5.4        
    Ionic Framework    : ionic-angular 3.9.2            
                                                        
System:                                                 
                                                        
    Node : v8.9.1                                       
    npm  : 5.5.1                                        
    OS   : Windows 7                                    
                                                        
Environment Variables:                                  
                                                        
    ANDROID_HOME : not set                              
                                                        
Misc:                                                   
                                                        
    backend : pro                                       
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? 

Said repo does not have to be your actual project but just a minimal app that demonstrates the issue you are seeing. I have several sample / test applications that do similar navigation and do not see this issue in any of them, so I will need to see what your code is doing.

Thanks for using Ionic!

**Comment by Niavart** [comment]
Wish I could but I'm running tight on schedule on this current project. 

I worked around this problem by doing it an other way but I still have the code somewhere. I was a pretty strange way to navigate between page though.

**Comment by kensodemann** [comment]
OK, that's cool. If you are able to provide one in the future I can re-open the issue at that point and have a look. In the meantime, I will close this.

We are currently working full-speed-ahead on v4, and once that is out this may or may not still be an issue. If this is still an issue then, certainly let us know.
