### ISSUE TITLE
ion-slides with loop="true" 

### ISSUE THREAD

**Issue by msc67** [ionic-team/ionic#13582]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[x] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
An ion-slides component with `loop="true"` does not copy the events on the duplicate slides. In my example I have 3 slides, when you click on the number in the slide, an alert box will give a feedback. After sliding from slide 3 to slide 1, the click event will not be triggered (because the slide is a "duplicate" slide). If you move the slide a little from left to right and back (without sliding to next slide), the events are attached (because of the internal call of `fixLoop`) - at least when you have `slidesPerView = 1`. When you set slidesPerView to 2, `fixLoop` creates an odd behaviour, click events are attached on the one and than again on the other slide (alternating between the two visible slides)

**Expected behavior:**
A click event on the slide should always be triggered, on every slide, regardless how often you executed a slide.

For `slidesPerView = 1` there is a workaround with `fixLoop` being called after slideChanged, for `slidesPerView = 2` I found no workaround

ion-slides with loop="true" and interaction on a slide (triggered by events) is not useable at the moment

**Steps to reproduce:**
slidesPerView = 1
- click on 1-1 --> alert box ok
- slide to 1-2 --> alert box ok
- slide to 1-3 --> alert box ok
- slide to 1-1 --> no event is triggered!! (move the slide a little and click then --> alert box ok)
- slide to 1-2 --> alert box ok ...

slidesPerView = 2
- click on 2-1 or 2-2 --> alert box ok
- slide to 2-2 --> alert box ok on 2-2 and 2-3
- slide to 2-3 --> alert box ok on 2-3, no event triggered on 2-1
- move slide a little without sliding to next -> alert box ok on 2-1, but no events triggered on 2-3
- move slide a little without sliding to next -> alert box ok on 2-3, but no events triggered on 2-1

**Related code:**

Plunker (http://plnkr.co/edit/xxvPsdr3YvzhLzPsA0UH?p=preview)

**Other information:**
similar issues, all closed:
- https://github.com/ionic-team/ionic/issues/10784
- https://github.com/ionic-team/ionic/issues/6678
and many more

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
ionic 2 and ionic 3, angular 2 / 3 / 4 / 5, not tested with ionic 4

**Comment by judithhartmann** [comment]
Sounds like a duplicate to #10890 (still open)

**Comment by maronski** [comment]
+1
