### ISSUE TITLE
ion-textarea - can't write again [solved]

### ISSUE THREAD

**Issue by sandrobirke** [ionic-team/ionic#13581]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**

I can write some Text in the textarea, after touch outside the keyboard is hiding as expected. But if i make this two times again i cant write more text into the textarea. It feels like it is blocked or diabled. The Label is not activated. If i open the Sidebar and close it, i can write again. 

If i remove the <ion-item> it works.

Test on Android

**Expected behavior:**

Want write more text

**Steps to reproduce:**

**Related code:**
`<ion-card>
    <ion-item>
      <ion-label stacked>Text/Beschreibung:*</ion-label>
      <ion-textarea [(ngModel)]="collectionText"></ion-textarea>
    </ion-item>
  </ion-card>`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages: 

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v6.9.4
    npm  : 5.5.1
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

I copy-pasted your exact code from the Related Code section into a new Ionic app, and tried running it each of these ways:

- In the browser
- In the browser emulating an Android device
- On an actual Android device (Note 4 with Android 6.0.x)

Perhaps it has something to do with your exact code, so I would like to try it with your code or code you have created that duplicates the issue (if not your actual project).

Thanks for using Ionic!

**Comment by sandrobirke** [comment]
ok, it seems this is a bug in combination with "cordova-plugin-statusbar". I create a blank ionic-app and place one <ion-card> after another. In the second one is the <ion-textarea>. Everything works fine, but after install "cordova-plugin-statusbar" and set 

`statusBar.overlaysWebView(true);`

in app.components.ts the issue above is reproducible.
