### ISSUE TITLE
Ios app not working- Ionic 

### ISSUE THREAD

**Issue by wildaces215** [ionic-team/ionic#13586]
I am trying to run my ionic app on my mac book pro 

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ x] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

The bug is not allowing me to run my ionic app on the ios behavior after it is successfully built. 

Supposed to open the app and display the ionic app.

I types the commmand
ionic cordova emulate ios 
In order to run the app.

**Related code:**

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0
```
```
global packages:

    cordova (Cordova CLI) : 7.1.0
```
```
local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.7.1
```
```
System:

    ios-deploy : 1.9.2 
    Node       : v6.9.2
    npm        : 5.5.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 
```
```
Misc:

    backend : pro
```

**Comment by mhartington** [comment]
Hi there! This appears to be an issue, but there's no information on how to recreate or how to debug this. Could you please provide some more information or a demo in the form of a github repo? Thanks!

**Comment by kensodemann** [comment]
Hello all! Is this still an issue with the latest version of ionic?

I am going to close this for now, but will gladly reopen it if you can provide the information that @mhartington requested above. The GitHub repo would be particularly useful.

Thanks!
