### ISSUE TITLE
ion-slides issues

### ISSUE THREAD

**Issue by kennynguyen06** [ionic-team/ionic#13591]
I got 2 issue about ion-slides on IONIC 3.6.0 control bellow:

- Zooming image not smoothly and sometime sliding to next/prev image when zooming, zoomed image overlay on image of next slide
- ion-slides stop playing youtube after change screen orientation

Could you help me about these issue!
Thanks

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

If you believe there is a bug with Ionic, please open a new issue (or issues if more than one problem) fully filling out the issue template, and including a sample application that demonstrates the issue.

Thanks for using Ionic!

**Comment by mhartington** [comment]
Will Take a look! Thanks!

**Comment by kennynguyen06** [comment]
Thanks Mike!

**Comment by basvdijk** [comment]
I can confirm this issue. On iPad 3 the slider stuttered and in my Chrome browser it sometimes got stuck.

```

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.4.0 ios 4.5.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    ios-sim    : 5.1.0
    Node       : v8.2.1
    npm        : 5.6.0
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by sssssshun** [comment]
how to let sliders-component continue auto play,after swipe the ion-slider component? ,I listen the on-release event ,but fail that the sliders-component still stop,not rework the autoplay state..

**Comment by chandanch** [comment]
I had the same issue with two sliders. I was not able to control the slide programatically
