### ISSUE TITLE
how to enable user can paste text on ion-input Ionic 2.

### ISSUE THREAD

**Issue by vinayak-dataman** [ionic-team/ionic#13593]
I am working on IONIC app where user have to put any url and get data from that. I have used <ion-input>. Now I want that user can paste the url in ion-input. Whenever i test it in Android phone it does not work to select or paste url in ion-input.

**Comment by mhartington** [comment]
Hi there! It appears this isn't really an issue, and more of a question. Please check out the [forum](https://forum.ionicframework.com) for any questions. Thanks!
