### ISSUE TITLE
Targeting browser in scss

### ISSUE THREAD

**Issue by Spartanace1024** [ionic-team/ionic#13599]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

It would be great to have a simple css class applied to the application root for when an ionic app is running in the browser.  Maybe "browser".

Currently the application i'm working on is targeting ios, Android, and web and styling the latter two via scss is very easy as i just have to extend from "md" or "ios" in my scss files. However when targeting browser there is no such "browser" class applied to root, so styling for browser is more difficult.

Maybe there is already a way to achieve this via "platform-core" class, but I have heard this is not very dependable.

Thanks in advance!

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#334
