### ISSUE TITLE
ion-fab in ionic/core throws a type error

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic#13596]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

In ionic/core this syntax 
``` 
<ion-fab bottom right>
    <ion-fab-button>Share</ion-fab-button>
    <ion-fab-list side="top">
      <ion-fab-button>Facebook</ion-fab-button>
      <ion-fab-button>Twitter</ion-fab-button>
      <ion-fab-button>Youtube</ion-fab-button>
    </ion-fab-list>
    <ion-fab-list side="left">
      <ion-fab-button>Vimeo</ion-fab-button>
    </ion-fab-list>
  </ion-fab>
```
Throws this type error ```Type '{ bottom: true; right: true; }' has no properties in common with type 'IonFabAttributes'. ``` After talking to Brandy about this its because `bottom` and `right` are css attributes, not JSX attributes. 

**Steps to reproduce:**

Use the JSX posted above in a render function with the latest ionic/core and stencil/core

**Comment by brandyscarney** [comment]
@jthoms1 This is similar to the issue with adding `padding` to elements we discussed previously. We can convert these to input(s), but they're currently just CSS attributes.
