### ISSUE TITLE
Using tsconfig "noUnusedLocals": true with IonicPage decorator returns errors

### ISSUE THREAD

**Issue by Inlustra** [ionic-team/ionic#13607]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using tsconfig `"noUnusedLocals": true` gives
```
typescript: src/app/pages/auth/login/login.page.ts, line: 2
            'IonicPage' is declared but never used.

       L1:  import { AuthRoutes } from '../../../store/navigation/auth-routes.const';
       L2:  import { IonicPage } from 'ionic-angular/navigation/ionic-page';
```

When used with the @IonicPage decorator

**Expected behavior:**
It should not produce an error.

**Steps to reproduce:**
Use the related code below, and run `ionic serve`

**Related code:**
```
Example tsconfig.json:
```{
  "compilerOptions": {
    "allowUnusedLabels": false,
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "strictNullChecks": false,
    "noImplicitReturns": false,
    "noImplicitAny": false,
    "noUnusedLocals": true
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "files": [
    "typings/environment-typings.d.ts"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```
Example component:
```
import { IonicPage } from 'ionic-angular/navigation/ionic-page';
import { Component } from '@angular/core';

@IonicPage({
  name: 'HomeDetails'
})
@Component({
  selector: 'myComponent',
})
class MyComponent {
}
```

**Other information:**
This is down to the deepLinks build step removing the decorator but not the associated import.

## Side note: 
Why can't we use variables inside the @IonicPage decorator name...? The deeplinks step takes the literal value. Useless when combined with splitting your app into libraries as you're unable to use the string, deeplink navigation. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (./node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node  : v8.3.0
    npm   : 5.4.2
    OS    : macOS High Sierra
    Xcode : Xcode 9.2 Build version 9C40b

Misc:
    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is not really an issue with the Ionic Framework, but an app-scripts issue (basically, an issue with our build scripts and not with the framework itself). I will move this issue to that repo for you.

For your side note, you cannot use a variable because the build scripts need to be able to determine the name value at build time via static analysis.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1336
