### ISSUE TITLE
Error while opening UI-automatorviewer.bat/android.bat and tools applications in Widows 10

### ISSUE THREAD

**Issue by vashisthdeepak** [ionic-team/ionic#13604]
**************************************uiautomatorviewer.bat*************************************
-Djava.ext.dirs=C:\Users\Mohit\AppData\Local\Android\Sdk\tools\lib;lib is not supported.  Use -classpath instead.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

***************************************Error while running android.bat**************************************

Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/swt/widgets/Display
        at com.android.sdkmanager.Main.showSdkManagerWindow(Main.java:403)
        at com.android.sdkmanager.Main.doAction(Main.java:391)
        at com.android.sdkmanager.Main.run(Main.java:151)
        at com.android.sdkmanager.Main.main(Main.java:117)
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.widgets.Display
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 4 more

******************************************System Information***********************************************
OS - windows 10
Eclipse Java EE IDE for Web Developers.(Version: Neon.3 Release (4.6.3)
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

***********************************Appium_doctor Result*************************************************

Your environment has been set up for using Node.js 6.10.0 (x64) and npm.

C:\Windows\System32>appium-doctor
info AppiumDoctor Appium Doctor v.1.4.3
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: C:\Program Files\nodejs\node.exe
info AppiumDoctor  ✔ Node version is 6.10.0
info AppiumDoctor  ✔ ANDROID_HOME is set to: C:\Users\Mohit\AppData\Local\Android\Sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: C:\Program Files\Java\jdk-9.0.1
info AppiumDoctor  ✔ adb exists at: C:\Users\Mohit\AppData\Local\Android\Sdk\platform-tools\adb.exe
info AppiumDoctor  ✔ android exists at: C:\Users\Mohit\AppData\Local\Android\Sdk\tools\android.bat
info AppiumDoctor  ✔ emulator exists at: C:\Users\Mohit\AppData\Local\Android\Sdk\tools\emulator.exe
info AppiumDoctor  ✔ Bin directory of %JAVA_HOME% is set
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor

@note: Appium is running and working fine. Test cases are passing. The error comes only when I tried to run uiautomatorviewer for finding elements Xpath.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
