### ISSUE TITLE
hardware backbutton ion-select popup

### ISSUE THREAD

**Issue by manojbhardwaj** [ionic-team/ionic#13602]
how can i handle android hardware backbutton ion-select popup

**Comment by smubarak-ali** [comment]
I think you need to manually write the logic in the register back button method in platform:
[Register Back Button Docs](https://ionicframework.com/docs/api/platform/Platform/#registerBackButtonAction)

You can write the below code on the registerBackButtonAction()
for example:
```
const currentPage = this.nav.getActive().name;
    const activePortal = this.ionicApp._loadingPortal.getActive() ||
      this.ionicApp._modalPortal.getActive() ||
      this.ionicApp._toastPortal.getActive() ||
      this.ionicApp._overlayPortal.getActive();

    const tabs = this.app.getActiveNav();

    if (activePortal) {
      await activePortal.dismiss();
      return;
    }
    else if (this.menu.isOpen()) {
      await this.menu.close();
      return;
    }

    if (tabs.canGoBack()) {
      await tabs.pop();
      return;
    }
    else if (this.nav.canGoBack()) {
      await this.nav.pop();
      return;
    }
    else {
      .....
      .....
    }
```

**Comment by manojbhardwaj** [comment]
i also try this and ion-select is dismiss but when i am try to open again it's not opening

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
