### ISSUE TITLE
ionic3 

### ISSUE THREAD

**Issue by ragulra** [ionic-team/ionic#13603]
Hi,
I have an issue, while using ionic-3 with angular-material-2. So when I navigate between tabs, the content suppose to loaded for that particular tab doesn't load into that ionic layout.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
