### ISSUE TITLE
Using media-capture plugin causes page to be repositioned relative to status bar

### ISSUE THREAD

**Issue by snortblt** [ionic-team/ionic#13616]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using the native media-capture plugin within a modal page, if another page is pushed after a photo is captured, that page is not correctly positioned to fit the status bar. Using WkWebView.

**Expected behavior:**
Page should have adequate padding to accommodate status bar.

**Steps to reproduce:**
1. Capture a photo via media-capture plugin (take photo and click "use" in preview)
2. In the media callback, push another page onto the nav stack.
3. Ba-bam! Page title bar is partially occluded by status bar

**Related code:**

Similar to #13600 except that once the messed up page is exited, previous pages look normal

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.2.3 browser 5.0.0 ios 4.5.4 windows 5.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v6.11.3
    npm               : 3.10.10
    OS                : macOS High Sierra
    Xcode             : Xcode 9.1 Build version 9B55

Environment Variables:

    ANDROID_HOME : /Users/josh/Library/Android/sdk

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by kensodemann** [comment]
I am going to close this due to inactivity. If this is still an issue, please provide a sample application that can be used to debug the issue and we will look in to it, probably after the next major Ionic release.

**Comment by snortblt** [comment]
As far as I know it's still an issue. Apologies--I haven't had time to put together a sample app for you. The app in question would be problematic to send to you as is.

**Comment by kensodemann** [comment]
That's cool, no need to apologize. At this point, I suggest waiting until after the next major release of Ionic and re-test in that version as there is most likely not going to be another v3 release.
