### ISSUE TITLE
ion-checkbox two way binding doesn't work with ngModel

### ISSUE THREAD

**Issue by lfxsantos** [ionic-team/ionic#13613]
**Ionic version:**  (check one with "x")
[x ] **3.7.1**

**I'm submitting a ...**  (check one with "x")
[X] bug report

I have a list of checkboxes and the user has a max limit to select. Exemple: Select 3 of 5 options.

I want to give him a warn when he try to select the fourth checkbox and unselect it.

I'm tryng something like that to unselect:

<ion-checkbox [(ngModel)]="teste" (ionChange)="updateTest()"></ion-checkbox>

updateTest(){
        console.log(this.teste); //true
        this.teste = false;
        console.log(this.teste); //false
 }

But on screen the checkbox continue checked (true).

I'm doing something wrong?

Tks,
Filipe

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask future questions like this on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

In your particular case, the following "two way" binding:

```<ion-checkbox [(ngModel)]="teste"></ion-checkbox>```

is actually short-hand for this:

```<ion-checkbox [ngModel]="teste" (ngModelChange)="teste = !teste"></ion-checkbox>```

See [this post](https://blog.thoughtram.io/angular/2016/10/13/two-way-data-binding-in-angular-2.html) for a pretty good write-up on how two-way bindings work in Angular.

Then you add your ```updateTest()``` binding on top of that, and you have the equivalent of:

```<ion-checkbox [ngModel]="teste" (ngModelChange)="teste = !teste" (ionChange)="updateTest()"></ion-checkbox>```

So now you have two things mucking with the value of `teste`, and perhaps even firing each other in an infinite loop.

If you just want the `teste` to toggle, then only use the two-way binding:

```<ion-checkbox [(ngModel)]="teste"></ion-checkbox>```

If you are trying to do something fancier, then you should post a question with exactly what you are trying to do on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
