### ISSUE TITLE
Angular Material tab doesn't work on Ionic 3...

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic#13629]
Hello guys,

How can I use Angular Material tabs on Ionic?

https://material.angular.io/components/tabs/overview

I installed Angular Material using npm command and I copied its example html contents on my ionic page:

```
<mat-tab-group>
  <mat-tab label="Tab 1">Content 1</mat-tab>
  <mat-tab label="Tab 2">Content 2</mat-tab>
</mat-tab-group>
```
However it shows basic html texts only. I don’t know why it’s not working on my ionic app.
I added following import to my html page ts file:

`import { MatTabsModule } from '@angular/material/tabs';`

and nothing changed.
I added it to app.module.ts and and put MatTabsModule to import declarations and now it throws me an error:

`Cannot find module: 'rxjs/operators/debounceTime'
`
and the whole app doesn’t load now...

Please help me out. I think Angular Material tab has really nice slide animations. 
For Ionic 4, please try to integrate everything Angular Material has! 

Thanks,

**Comment by mhartington** [comment]
Hi there! It appears this isn't really an issue, and more of a question. Please check out the [forum](https://forum.ionicframework.com) for any questions. Thanks!
