### ISSUE TITLE
[Feature]: iOS back button text should be the title from the previous page

### ISSUE THREAD

**Issue by Maistho** [ionic-team/ionic#13620]
**Ionic version:**
- [ ] **2.x**
- [x] **3.x**
- [ ] **4.x**

**I'm submitting a ...**
- [ ] bug report
- [x] feature request

In most iOS apps I've used the back button text shows what page you will be taken to when you click it. In Ionic, the back button text is static and always shows "Back".

**Requested feature**: Back button text should be the page title from the previous page, as is the default in most iOS apps.

This could be implemented as a setting (or default) in the Config, which would be great.

I think that a more powerful approach could be to allow users to set a custom `BackButtonComponent`. This component would be used instead of the current button generated in the [navbar template](https://github.com/ionic-team/ionic/blob/master/src/components/toolbar/navbar.ts#L51). There should of course be a default `BackButtonComponent` that has the same behaviour as today.

That way it would also be easier to integrate with translations and other more advanced use cases.

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#335
