### ISSUE TITLE
Angular Material doesn't work on Ionic 3...

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic#13623]
Hello Ionic team.

Would you guys please make Angular Material compatible with Ionic?
I would love to use Angular Material components on Ionic but it doesn't seem to work at all on Ionic.
Please unlock this feature for us!

material.angular.io

**Comment by vovikdrg** [comment]
It works :)

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please.

When filling that out, please provide further clarification on what is not working and what you are trying to accomplish. Given that both libraries essentially operate in the same space (they are both essentially libraries used to create and layout the UI) it is not clear to me why you want to use both at once. It is also not clear to me why you would not necessarily be able to, though it does seem to me, given the overlap in functionality of the two projects, that there would be a large potential for confusion or perhaps conflicting paradigms for how things get done, etc.  Basically, I think more information is required here.

You may also want to wait until version 4 is released. It may be easier to accomplish what you are trying to do with the new `@ionic/core` components.

Thanks for using Ionic!

**Comment by vovikdrg** [comment]
@kensodemann  Tabs is one of the reason why to use material.

**Comment by SamaludheenCignes** [comment]
I am facing same issue with data tables. Material theme not applied. I am using 
` import { MatTableModule } from '@angular/material/table'`

**Comment by jamesharvey2** [comment]
Well, I tried to use it for Angular Material Tabs..

Yes, please make a tab like Angular Material Tabs for Ionic 4.

**Comment by francovp** [comment]
Anyone know why it doesn't work? I imported the components and add them to the app.module.ts and they not showing up

**Comment by vovikdrg** [comment]
@francovp it's hard to guess. Create question on stackoverflow and provide details.

**Comment by andrewmcewen** [comment]
@francovp does yours work with a custom theme?
