### ISSUE TITLE
Problem in ?change detection? on page, activated from Virtualscroll item

### ISSUE THREAD

**Issue by pavimus** [ionic-team/ionic#13624]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

In example you'll see virtualscroll list with detail page for each item. On item page current item value is displayed and present button for incrementing this value. On some details pages value is not updated by clicking button. When i added logging, i saw, that value is actually incrementing, but not updated on view.

**Expected behavior:**
Displayed value on detail page must always update after clicking button.

**Steps to reproduce:**
Please try to open about 5-10 different items in different random parts of list (at end, at begin, in middle, etc) and try to click button. 
**Related code:**

https://github.com/pavimus/ionic_test

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

local packages:

    @ionic/app-scripts : 3.1.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.12.0
    npm  : 5.5.1
    OS   : macOS High Sierra

Misc:

    backend : pro
```

**Comment by pavimus** [comment]
Problem appers usually after opening 3-4 detail pages

**Comment by pavimus-nvii** [comment]
Someone tried to reproduce this problem?
