### ISSUE TITLE
virtual-scroll adds borders to :first-child in middle of list on ios

### ISSUE THREAD

**Issue by Maistho** [ionic-team/ionic#13621]
**Ionic version:** 
- [ ] **2.x**
- [x] **3.x**
- [ ] **4.x**

**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
See screenshot

![screenshow showing a border in the middle of a list](https://user-images.githubusercontent.com/2260305/33807902-f0ecca3a-dddd-11e7-80d2-459142c97d31.png)

This is fixed for `:last-child` by adding an extra last item in [virtual-scroll.ts#L585](https://github.com/ionic-team/ionic/blob/6978bb551f87d63543a4d442687c15280cc74123/src/components/virtual-scroll/virtual-scroll.ts#L585). Why is the same not done for the `:first-child`?

**Expected behavior:**
No extra borders on seemingly random elements in a list

**Steps to reproduce:**
Make a virtual-scroll list on ios, scroll down a bit

**Other information:**
Fix either by disabling the list styling
```css
.virtual-scroll.list-ios > .item-block:first-child {
    border-top: none;
}
```
Or by adding an extra element as is already done for last-child

**Comment by murillobarata** [comment]
Same issue
