### ISSUE TITLE
DeepLinker doesn't handle reloading views when parameters change

### ISSUE THREAD

**Issue by mzealey** [ionic-team/ionic#13631]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

If I have an app with a segment like /foo/:id and I change from say /foo/1 to /foo/2 in the browser bar (or via window.location), ionic doesn't detect and change this appropriately. Hitting F5 to reload the app then loads id 2 correctly.

I believe this is due to the loop in DeepLinker's `_loadViewForSegment` which calls `done()` only when comparing the viewcontroller/segment ids rather than the data that has been passed.

**Expected behavior:**

Changing a route parameter the browser bar or `window.location` should cause `ionViewWillEnter` to trigger 
and the `navParams` to reflect the new details.

**Comment by davec21** [comment]
I've noticed this, however I find that if I tell it to go to the url twice it will work.

1. change url from www/1 to www/2
2. hit enter, page does nothing
3. click to enter the address bar again
4. hit enter, page will navigate.

**Comment by mzealey** [comment]
@davec21 believe this is the browser intellegently refreshing the page when you try navigating twice rather than anythnig coming from ionic itself.

**Comment by davec21** [comment]
@mzealey Definitely possible!
