### ISSUE TITLE
ion-tab with *ngFor: Remove destroyed tabs and keep the order

### ISSUE THREAD

**Issue by dpalou** [ionic-team/ionic#13633]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
We have an app with "dynamic" tabs (the tabs displayed can change depending on some data retrieved some the server), so we're using *ngFor in the ion-tab components.

I noticed that if I remove an element from the array, the tab is still displayed. Also, if I add a new element at the start of the array, the tab is displayed last. I looked at [the code of ion-tabs](https://github.com/ionic-team/ionic/blob/master/src/components/tabs/tabs.ts#L379) and I've seen that the only thing it does is:

this._tabs.push(tab);

**Expected behavior:**
IMO, the displayed tabs should always match the array supplied to *ngFor. This means that removed tabs should be removed from the view, and new tabs should be displayed at the right position.

**Related code:**

```
<ion-tabs>
    <ion-tab *ngFor="let tab of tabs" [root]="tab.page" [tabTitle]="tab.title" [tabIcon]="tab.icon"></ion-tab>
</ion-tabs>

this.subscription = this.menuDelegate.getHandlers().subscribe((handlers) => {
    this.tabs = handlers.slice(0, 4); // Get first 4.
    this.tabs.push(this.moreTabData); // Add "More" tab.
});
```

**Ionic info:**

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 6.5.0 
    Gulp CLI    : CLI version 1.2.2 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.1.2 ios 4.3.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.8 
    Node              : v6.9.1
    npm               : 5.0.4 
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 
```

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#338
