### ISSUE TITLE
Transpile error in play().then of HTML5 video tag

### ISSUE THREAD

**Issue by sertal70** [ionic-team/ionic#13634]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
I have a `<video>` tag controlled by code for play/stop user actions. When user asks to play, the following code is executed (as per [Google Chrome hint:](https://developers.google.com/web/updates/2017/06/play-request-was-interrupted))

```
this.myVideo.play().then( 
  (value) => {
    // doing stuffs after video started (i.e. enable pause/stop button)
    ...
   },
   (error) => {
     // handling errors
     ...
   }
);
```

 
When I run the code using `ionic serve` everything goes fine, but when I compile for platform using `ionic cordova build iOS --prod` the following error occurs:

```
[10:10:41]  typescript: src/components/my-viewer/my-viewer.ts, line: 117
            Property 'then' does not exist on type 'void'.

     L117:  this.myVideo.play().then(
     L118:      (value) => {

Error: Failed to transpile TypeScript
    at errorCheckProgram (/Users/Sergio/Projects/myvideo-test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:119:39)
    at Object.<anonymous> (/Users/Sergio/Projects/myvideo-test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:89:21)
    at step (/Users/Sergio/Projects/sot-actionmode/myvideo-test/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/Users/Sergio/Projects/myvideo-test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/Users/Sergio/Projects/myvideo-test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
    at <anonymous>
[
```

**Expected behavior:**
I would expect that the transcript compiling process to complete successfully independently of what type of platform I'm building for.

**Steps to reproduce:**
Just create a simple page with a `<video>` tag and a button, then use the code above to start play when the user click on the button. Try to compile and see what happens. I don't provide any stackblitz/plunker because the issue is related to the transcript compiling process.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.2.3 ios 4.5.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    ios-sim           : 5.0.13
    Node              : v8.9.1
    npm               : 5.5.1
    OS                : macOS Sierra
    Xcode             : Xcode 9.0.1 Build version 9A1004

Environment Variables:

    ANDROID_HOME : /Library/Android/sdk

Misc:

    backend : legacy
```

**Comment by mhartington** [comment]
This looks like a typescript thing rather than Ionic issue. You can set the type of `this.myVideo` to be a `HTMLVideoElement` to get the proper info.


```

class MyClass{
  
  @ViewChild('video') myVideo: HTMLVideoElement;

```

**Comment by sertal70** [comment]
Thanks @mhartington, actually `this.myVideo` is already an `HTMLVideoElement` got via `@ViewChild()` but it doesn't work.

**Comment by mhartington** [comment]
Hey, sorry, mistake on my end. VideoChild returns an ElementRef, not a direct DOM reference. You need to then grab the nativeElement.

```
    this.video.nativeElement
      .play()
      .then(() => this.video.nativeElement.pause());
```

**Comment by sertal70** [comment]
Actually`this.video.nativeElement` it works, but consider the following:

```
  @ViewChild('myVideo') private myVideoRef: ElementRef;
  private myVideo: HTMLVideoElement;

  this.myVideo = this.myVideoRef.nativeElement;
  ....
```

then  `this.myVideoRef.nativeElement.play().then()` works but `this.myVideo.play().then()` returns the compile error `Property 'then' does not exist on type 'void'`. Why?

**Comment by sertal70** [comment]
Hello @mhartington, any news on this?

**Comment by mhartington** [comment]
That example does not happen for me.

```ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { NavController } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  @ViewChild('video') video: ElementRef
 private myVideo: HTMLVideoElement;
  constructor(public navCtrl: NavController) {
  }

  ionViewDidLoad(){
    this.myVideo = this.video.nativeElement;
  }

  togglePlay(){
     this.myVideo
      .play()
      .then(() => this.myVideo.pause());
  }

}
```

As an example, this compiles fine in both dev builds and production builds

**Comment by sertal70** [comment]
Can you please share the output of your ionic info?

**Comment by mhartington** [comment]
```
$ ionic info

cli packages: (/Users/mhartington/n/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 2.0.0
    Node              : v8.9.1
    npm               : 5.5.1
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Users/mhartington/Library/Android/sdk

Misc:

    backend : pro
```

This was a newly created project from the CLI. Let's continue the conversation over on the ionic forum instead of here.

**Comment by sertal70** [comment]
Thanks, I'll give it a try using a new project tomorrow morning (I'm from Italy) and let you know what happens
