### ISSUE TITLE
Bypassing gray blank screen, white splash screen problems....

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic#13630]
Hello Ionic team.
Thanks for all your efforts so far! 

As you guys already know, every apps built on Cordova gets problems with blank gray screen and white splash screen on starting an app. 
I tested Ionic apps, Apache Cordova apps, they showed this same behavior... which other apps built on Java & C# don't have. 

Is it possible for you guys to make a splash screen plug-in which will display an HTML page & CSS as main splash screen that will show up on start of ionic app?  ideally with ability to control its display time?
This update will be really essential. 

Please try to test Ionic apps or any apps built on Cordova on a little bit older smartphones from 2014. You guys will see they all have gray blank screen problem or white splash screens on start up. This 2-3 second long gray blank screen can't be removed! 
We need something that can hide or bypass them. 

Please release an HTML splash screen plugin along with Ionic 4 update.
It looks like some high end smartphones bypass this issue but apparently not all smartphones. If you guys can't observe this behavior on your smartphones, try to search 'ionic white screen', 'ionic gray screen' on google. There are so many people troubled with this same issue.  That is not a coincidence. I'm testing on HTC 710c smartphone running Android v5.0.  Every apps built on Ionic and Cordova is showing the same problem. 710c is still a decent quad-core CPU android smartphone which can run the majority of demanding 3D game apps. It can run those 3D game apps without gray blank screen or splash screen issues.

I would love to see Ionic 4 fix that problem permanently. Splash screen errors are really critical and they degrade quality of cordova apps. and this is about time to totally remove that problem.

**Comment by ghenry22** [comment]
I test all my apps on both an old iphone 5 and a HTC one m8 and I have never seen either of these issues?  I use the Cordova splashscreen plugin which is designed to hide the web view while it loads.

I have also experimented with not using the splashscreen plugin and using an HTML loading screen, so that it can be animated and work in browsers as well as native apps and this works fine for me with the exception that when running WKWebView on iOS there is a very brief white flash when the plugin is first loaded.  If using uiwebview this white flash does not occur.  Don’t have the code with me right now but I can post the steps needed to set this up.

**Comment by jamesharvey2** [comment]
That is so weird because I can observe this problem on my HTC and Alcatel smartphones... 
Some poor Alcatel smartphones can't even pass the white splashscreen.  I will upload an APK file with this issue shortly along with screenshots from my smartphones.

**Comment by kensodemann** [comment]
I have seen the grey screen issue that @jamesharvey2 is talking about. It happens on my Note4. However, this is before Cordova has control of the app (which is also before Ionic is loaded), and thus we cannot really do anything about that.

Not being able to get past the splashscreen sounds like a loading issue. Ionic v4 should greatly reduce load times, but if it does not do that for you please open a ticket about it at that time.

I will move this to our feature-requests repo as we _might_ be able to do something different with the startup process once the project currently code-named Avocado is released. We can review this request again at that time.

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#342

**Comment by jamesharvey2** [comment]
@kensodemann 
Yes, that would be fantastic! Avocado project seems to be about making a native layer for Ionic? 
 
We need a solid feature that enables ionic app to display an HTML page as the only splash screen. No gray screen, white blank screen should be there and its display time should be controllable with a simple command configuration. In my opinion, strange splash screen problem is the only factor that makes Ionic app look different from other apps.
