### ISSUE TITLE
Setting a tabs page as root does not load the first root page

### ISSUE THREAD

**Issue by Eraldo** [ionic-team/ionic#13636]
Please reopen this issue: https://github.com/ionic-team/ionic/issues/12625
It has been fixed, but the recent versions unfixed them.

**Comment by kensodemann** [comment]
Was it ever fixed in a released version or only in nightlies? I recall we had to back out some "fixes" because they broke other things, and this may have been one of them.

**Comment by Eraldo** [comment]
Thank you @kensodemann for your reply.
Your guess might explain the situation.

I was really wondering:
Do other people use tabs in the broken fashion?
Are they not using tabs?
Is there a workaround that I am not aware of?
