### ISSUE TITLE
Add cascading selection component

### ISSUE THREAD

**Issue by btpka3** [ionic-team/ionic#13641]
Not found official ionic  cascade selection component behave like `ion-datetime`. 
Can consider abstract and seprate it from `ion-datetime` ?

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[x ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
none
```

**Other information:**

- [ionic-citypicker](https://github.com/minh8023/ionic-citypicker) for ionic 1.x
- [ion-multi-picker](https://www.npmjs.com/package/ion-multi-picker) plugin for ionic 2&3
- [demo from ngx-weui ](https://cipchk.github.io/ngx-weui/#/example/picker) : need simulate touch event under browser developer tool.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
none
```

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#336
