### ISSUE TITLE
Random weird delay when Android back button is overriden to call page transition animation and the user has scrolled down a list on that page.

### ISSUE THREAD

**Issue by HubKing** [ionic-team/ionic#13646]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Randomly there is an up-to 2 second delay when the back button is pressed until the back button action is called. It randomly happens but not after that many trials, so it can be reproduced within a minute. On average, it I try 5~10 times, it surely happens.

**Expected behavior:**

There should be no such delay.

**Steps to reproduce:**

1. Create a blank project using 'ionic start test1 blank'.
2. Add a second page using 'ionic g page second-page.
3. Add a button on the home page, and when it is clicked open the second page like this.
    this.navCtrl.push(Page2Page,{},{animate:true, animation:'forward'});
4. Add the following code to the second page's back button on the toolbar, to slide out.
    this.navCtrl.pop({ animate: true, animation: "backward" });
5. Add a common code to override the back button, to do exactly the same thing as Step 4.
6. Start the app on an Android device.
7. Press the "Go" button to go to the second page.
8. Quickly scroll down the list to the bottom (If I do not scroll down the list, this bug does not happen.)
9. Press the Android system back button. (The arrow back button on the toolbar never causes this bug.)
10. If the delay does not happen, repeat Step 7~ Step 9 several times.

**Related code:**
As I wrote above, the code is very basic and simple. The only unusual thing is overriding the Android back button, but that all search results (StackOverflow, Ionic Forum) directed that method to slide out when the Android back button is pressed, so I think many people uses this method.

I zipped the complete source directory so that you could test it immediately without downloading modules. https://expirebox.com/download/161e6ef320349c56f6a7a0adaa34154f.html (72MB)

If that is too large, download this file that contains only the source code. https://expirebox.com/download/07765410c2e21acc07312cfcf653f751.html (2MB)

I have not used ExpireBox before but it was at the top of a Google search. If, for reason, you cannot download from ExpireBox, please let me know, and I will search for another file sharing service.

```
export class Page2Page {
  @ViewChild(Navbar) navBar: Navbar;
  public unregisterBackButtonAction: any;

  constructor(public navCtrl: NavController,
    private app: App,
    private plat: Platform,
    public navParams: NavParams) {
  }

  ionViewDidEnter() {
    this.navBar.backButtonClick = () => {
      this.slideOut();
    }

    this.unregisterBackButtonAction
      = this.plat.registerBackButtonAction(() => { this.slideOut() }, 10);
  }

  slideOut() {
    console.log("slideOut();");
    this.navCtrl.pop({ animate: true, animation: "backward" });
  }

  ionViewWillLeave() {
    console.log("ionViewWillLeave();");
    this.unregisterBackButtonAction && this.unregisterBackButtonAction();
  }
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: 

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.0
    npm               : 5.5.1

```

**Comment by Eloverflow** [comment]
Same issue as well
