### ISSUE TITLE
Cancel button in AlertController on iOS should be more consistent with HIG and native UIKit

### ISSUE THREAD

**Issue by ippeiukai** [ionic-team/ionic#13649]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**

With AlertController, buttons on alerts are ordered as specified left to right or top to right.

**Expected behavior:**

Button with role ‘cancel’ should be displayed at the left most / bottom position regardless of the specified order.

Current HIG states “Cancel buttons should always be on the left.”
UIAlertController since iOS 8.3 always positions cancel button at the left most / bottom position regardless of the specified order.
When buttons are stacked vertically, the current behaviour is especially lacking as the cancel button should be at the bottom but not as the default action (which we cannot achieve with the current AlertController API).

https://developer.apple.com/ios/human-interface-guidelines/views/alerts/
https://developer.apple.com/documentation/uikit/uialertcontroller

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#341
