### ISSUE TITLE
No Context view is appeared for IONIC application

### ISSUE THREAD

**Issue by sagarsheth27** [ionic-team/ionic#13642]
Here my code is like below:
Set contextName = driver.getContextHandles();
		System.out.println(contextName);
		for (Object o  : contextName) {
			String data=o.toString();
			System.out.println(data);}

From above code i am unable to find context view of the page. What action should i have to take for same?

**Comment by sagarsheth27** [comment]
I tried with multiple ways. But unable to do it. No context view appeared and if i am trying to click on element as we always do then its not working. PFB SS for same page. I need suggestion what i have to do for same. Tried as below:
1. driver.findElementByAccessibilityId("create EDIT ").click();
2.driver.findElement(By.xpath("/html/body/ion-app/ng-component/ion-nav/page-payment-source/ion-content/div[2]/div/div[1]/div[1]/div/div[1]/div[3]/div[1]/button")).click();
3.driver.findElementByAccessibilityId("create EDIT").click();

Also PFA of appium server log.
[appium-server-logs.txt](https://github.com/ionic-team/ionic/files/1555066/appium-server-logs.txt)
![untitled](https://user-images.githubusercontent.com/32329719/33934210-34511ee2-e01e-11e7-8f78-625cd29224f0.png)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
