### ISSUE TITLE
Got memory pressure notification (critical). Ionic 3 app crashed.

### ISSUE THREAD

**Issue by klochko7** [ionic-team/ionic#13643]
Hi all ! Could anyone suggest please … my Ionic 3 app always crashed with such error **Got memory pressure notification (critical)** when I am runnging post query. If there any idea how to solve such problem ?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
