### ISSUE TITLE
Hi Ionic-team , I  used the ionic-sliders component find a bug, Please help tanks! 

### ISSUE THREAD

**Issue by sssssshun** [ionic-team/ionic#13640]
//this is my code:

```
  <ion-slides loop="true" autoplay="1000" on-tap="test()" on-release="re()">
    <ion-slide>
      <h1>Slide 1</h1>
    </ion-slide>
    <ion-slide>
      <h1>Slide 2</h1>
    </ion-slide>
    <ion-slide>
      <h1>Slide 3</h1>
    </ion-slide>
  </ion-slides>
```

but I find when I swipe the component the auto slider is do not rework!
I want come true when after I swipe the ion-slide ,wait about few 3s,the ion-slides will rework autoplay .
hope your help me. I come from china ,I love ionic.

**Comment by sssssshun** [comment]
but I find when I swipe the component the auto slider is do not rework!
I want come true when after I swipe the ion-slide ,wait about few 3s,the ion-slides will rework autoplay .

**Comment by chandanch** [comment]
Refer to this: 
https://ionicframework.com/docs/api/components/slides/Slides/#startAutoplay

**Comment by sssssshun** [comment]
Thanks chandanch! Yesterday the problem  haved solved ,I do not be careful read Ionic Slides Document!!!
