### ISSUE TITLE
Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function

### ISSUE THREAD

**Issue by Vishwa17** [ionic-team/ionic#13652]
I have created 2 projects Project A has Firbase Login and Project is just like simple blank ionic app. but using List in Project A I am calling Project using relative path. While creating production app it is showing the error:

 typescript error
            Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing
            the function or lambda with a reference to an exported function (position 756:18 in the original .ts file)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by Vishwa17** [comment]
I am following in slack but the response is very late !! :( 
but thanks for update !!
