### ISSUE TITLE
how can i customized the height width of badge

### ISSUE THREAD

**Issue by KishanIos007** [ionic-team/ionic#13653]
how can i customized the property of badge like i want to be badge like this ..
![capture](https://user-images.githubusercontent.com/18045135/33990175-0f9c3d66-e0f0-11e7-9c74-3ad5ec0114bc.PNG)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
