### ISSUE TITLE
ActionSheetController should show popover on iPad

### ISSUE THREAD

**Issue by ippeiukai** [ionic-team/ionic#13651]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**

ActionSheetController displays action sheet at the bottom of the screen in full width.

**Expected behavior:**

Action sheet on iPad should be displayed in popover.

https://developer.apple.com/ios/human-interface-guidelines/views/action-sheets/
“On larger screens, an action sheet appears all at once as a popover.”

https://developer.apple.com/documentation/uikit/windows_and_screens/getting_the_user_s_attention_with_alerts_and_action_sheets

ActionSheetController may accept `popoverTarget` option to which `event.target` of the click event can be passed to specify where to show the popover. The button with cancel role should be removed automatically.

The same behaviour may also be desired on other tablet platforms like Android:
https://material.io/guidelines/components/bottom-sheets.html#bottom-sheets-modal-bottom-sheets
> Consider alternatives to modal bottom sheets on larger screens. Because bottom sheets may appear far from the place where the user clicked or touched to summon them, it splits the user’s attention across two different parts of the screen.

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#339
