### ISSUE TITLE
AlertController should have button with destructive role

### ISSUE THREAD

**Issue by ippeiukai** [ionic-team/ionic#13650]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**

App developer cannot specify buttons in AlerController to have destructive role. ActionSheetController accepts the role already.

**Expected behavior:**

Button with role ‘destructive’ should be displayed in different style.

In addition, on at least iOS, developer should be able to “make the Cancel button bold by marking it as the default button” as HIG states, when destructive button is present. 
https://developer.apple.com/ios/human-interface-guidelines/views/alerts/

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#340
