### ISSUE TITLE
Is there any support for adding html tags in tabTitle in ionic 3?

### ISSUE THREAD

**Issue by Mani-0503** [ionic-team/ionic#13661]
I need to add a heading and a span text in tabTitle in ionic tabs.

      <ion-tabs>
          <ion-tab tabTitle="<h2>Heading</h2><br/><span>This is a span text</span>"></ion-tab>
      </ion-tabs>

I have tried like above but it didn't work.But i want like above.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
