### ISSUE TITLE
Viewport=cover with Top tabs and no header 

### ISSUE THREAD

**Issue by vptcnt** [ionic-team/ionic#13660]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If there are tabs at the top position with no header for each tab :
- on IphoneX (iOS 11.0), the tabs appears on overlay on the statsubar.
![image](https://user-images.githubusercontent.com/814014/34018633-be93ccc8-e0f8-11e7-9132-e1629fbf2dc6.png)

- if I use :     this.statusBar.overlaysWebView(false), the result is : 
![image](https://user-images.githubusercontent.com/814014/34018896-25bcb6ca-e0fa-11e7-9824-fe08dce15ce1.png)
The red background color is just to show better the borders.

- On Iphone 7, with IOS 10.3, the problem is : 
![image](https://user-images.githubusercontent.com/814014/34018997-99dd169e-e0fa-11e7-82d7-5f0d7c7307a6.png)

**Expected behavior:**
![image](https://user-images.githubusercontent.com/814014/34018629-b5dc3de0-e0f8-11e7-9b7f-fb510deb0f19.png)

**Steps to reproduce:**
I used the code from the starter ionic template SUPER:

**Related code:**

tabs.html
```
<ion-tabs #tabs tabsPlacement="top" tabsHighlight="true" tabsLayout="title-hide">
    <ion-tab [root]="tab1Root" [tabTitle]="tab1Title" tabIcon="people" tabsHideOnSubPages="true"></ion-tab>
    <ion-tab [root]="tab2Root" [tabTitle]="tab2Title" tabIcon="star" tabsHideOnSubPages="true"></ion-tab>
    <ion-tab [root]="tab3Root" [tabTitle]="tab3Title" tabIcon="calendar" tabsHideOnSubPages="true" tabBadge="5" tabBadgeStyle="danger"></ion-tab>
    <ion-tab [root]="tab4Root" [tabTitle]="tab4Title" tabIcon="cog" tabsHideOnSubPages="true"></ion-tab>
</ion-tabs>
```

tab1Root.html
```
<ion-content no-padding>
    <ion-list>
        <ion-item-sliding *ngFor="let item of currentItems">
        <ion-avatar item-start>
          <img [src]="item.profilePic" />
        </ion-avatar>
        <h2>{{ item.nickname }}</h2>
        <p>{{ item.about }}</p>
    </ion-list>
</ion-content>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/vincent/.nvm/versions/node/v9.2.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.1.2 
    Node              : v9.2.0
    npm               : 5.5.1 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235 
```

Vincent

**Comment by mhartington** [comment]
Hmm, alright I can reproduce this. Looking into it! Thanks for the issue
