### ISSUE TITLE
add debounce ion input for ionChange event 

### ISSUE THREAD

**Issue by mobileias** [ionic-team/ionic#13665]
hello 
is there any way to add debounce  for ion input into ionic 2 or 3 ?

Thanks

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by mobileias** [comment]
ok i have added point into ionic forum. 
@kensodemann 
have you any solution for this question if yes then it will help us 
Thanks
