### ISSUE TITLE
Ionic 3 latest ion-option disabled option ignored on action-sheet display

### ISSUE THREAD

**Issue by mzealey** [ionic-team/ionic#13667]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

```
    <ion-select interface="action-sheet">
        <ion-option value="..." [disabled]="true">option</ion-option>
```

option does not get disabled. Alert/popover interfaces look at the disabled attribute (eg https://github.com/ionic-team/ionic/blob/master/src/components/select/select.ts#L333) but `ion-option` disabled attribute is not inspected for action-sheet interface.

**Expected behavior:**

Option should show as a disabled box

**Comment by thiphariel** [comment]
What about this ? I get the same behavior. `[disabled]` is not read with action-sheet interface.

**Comment by prasanthnv** [comment]
it's not yet solved...save here

**Comment by pierresh** [comment]
Hello, 

Yes this would really useful as I was thinking to use this attribute to display something similar to option group labels (since the option group is not available yet)..

https://stackoverflow.com/a/40416561/3994745
https://forum.ionicframework.com/t/grouping-inside-select-box/58530

Thanks!

**Comment by robmacecs** [comment]
I believe this is still the same in v4 for both the `action-sheet` and `popover` interfaces
