### ISSUE TITLE
NavController.popTo() not working

### ISSUE THREAD

**Issue by ifrankwang** [ionic-team/ionic#13672]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
APage push to BPage, BPage push to CPage. When CPage use popTo(PageA) function, instead of pop to Page A, it just pop to BPage.

**Expected behavior:**
It should've pop to APage

**Steps to reproduce:**
1. PageA.navCtrl.push(PageB);
2. PageB.navCtrl.push(PageC);
3. PageC.navCtrl.popTo(PageA);

**Related code:**

A sample application via GitHub
https://github.com/ifrankwang/ionic-popto-issue.git

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/mac_dev/.config/yarn/global/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.3
    npm               : 5.6.0 
    OS                : macOS High Sierra

```

**Comment by jayordway** [comment]
The popTo() method is not within the documentation:

https://ionicframework.com/docs/api/navigation/NavController/

This means it is not intended for use outside of the internal framework.

**Comment by herbzi** [comment]
Even though it says it accepts a Page type I don't think the implementation actually supports it. I myself do use it with a viewcontroller reference.  Although you have to be careful relying on undocumented implementation functions as they can change at any time without any notice. I would much prefer there was some documented way to do it, but there isn't unless you only want to popToRoot.

**Comment by ifrankwang** [comment]
@herbzi Using ViewController reference as param of popTo works for me! @jayordway popToRoot doesn't sounds logical, since PageA in my example project might not be the root page in a real project.
