### ISSUE TITLE
node-sass@4.5.3 error 404

### ISSUE THREAD

**Issue by juanglogic** [ionic-team/ionic#13677]
Node version: 9.3.0
npm version : 4.6.0
**Ionic version:**  
[] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  
[x ] bug report
[ ] feature request

**Current behavior:**
Hi, I'm trying to start a ionic project but seems have an error with with node sass, I tried change the node-sass version and npm version, but doesn't work

**Steps to reproduce:**

```
ionic start app blank
```

**Related code:**

> node-sass@4.5.3 install D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.3 postinstall D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe D:\tfsJuan\logi\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\tfsJuan\\logi\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.3.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Python27\python.exe" in the PATH
gyp verb `which` succeeded C:\Python27\python.exe C:\Python27\python.exe
gyp verb check python version `C:\Python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.13\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.3.0
gyp verb command install [ '9.3.0' ]
gyp verb install input version string "9.3.0"
gyp verb install installing version: 9.3.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.3.0
gyp verb build dir attempting to create "build" dir: D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'D:\\tfsJuan\\logi\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\tfsJuan\\logi\\node_modules\\@ionic\\app-scripts\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\tfsJuan\\logi\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\juan.gonzalez\\.node-gyp\\9.3.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\juan.gonzalez\\.node-gyp\\9.3.0',
gyp info spawn args   '-Dnode_gyp_dir=D:\\tfsJuan\\logi\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\juan.gonzalez\\.node-gyp\\9.3.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\tfsJuan\\logi\\node_modules\\@ionic\\app-scripts\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\tfsJuan\\logi\\node_modules\\@ionic\\app-scripts\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\juan.gonzalez\.node-gyp\9.3.0
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
Compilación iniciada a las 18/12/2017 4:11:23 p. m..
Proyecto "D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass\build\binding.sln" en nodo 1 (destinos predeterminados).
ValidateSolutionConfiguration:
  Compilando la configuración de soluciones "Release|x64".
El proyecto "D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass\build\binding.sln" (1) está compilando "D:\tfsJuan\logi\node_modules\@ionic
\app-scripts\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) en el nodo 1 (destinos predeterminados).
El proyecto "D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) está compilando "D:\tfsJuan\logi\node_m
odules\@ionic\app-scripts\node_modules\node-sass\build\src\libsass.vcxproj" (3) en el nodo 1 (destinos predeterminados).
PrepareForBuild:
  Creando directorio "Release\obj\libsass\".
  Creando directorio "D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass\build\Release\".
  Creando directorio "Release\obj\libsass\libsass.tlog\".
InitializeBuildStatus:
  Se creará "Release\obj\libsass\libsass.tlog\unsuccessfulbuild" porque se especificó "AlwaysCreate".
ClCompile:
  CL.exe /c /I"C:\Users\juan.gonzalez\.node-gyp\9.3.0\include\node" /I"C:\Users\juan.gonzalez\.node-gyp\9.3.0\src" /I"C:\Users\juan.gonzalez\.node-gyp\9.3.0\de
  ps\uv\include" /I"C:\Users\juan.gonzalez\.node-gyp\9.3.0\deps\v8\include" /I..\..\src\libsass\include /Zi /nologo /W3 /WX- /Ox /Ob2 /Oi /Ot /Oy /GL /D NODE_G
  YP_MODULE_NAME=libsass /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_DEPRECATION_WARNINGS=1 /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECA
  TE /D _HAS_EXCEPTIONS=0 /D "LIBSASS_VERSION=\"3.5.0.beta.2\"" /GF /Gm- /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"Release\obj\libsa
  ss\\" /Fd"Release\obj\libsass\libsass.pdb" /Gd /TP /wd4267 /wd4351 /wd4355 /wd4800 /wd4251 /errorReport:queue /GR /EHsc /MP ..\..\src\libsass\src\ast.cpp ..\
  ..\src\libsass\src\ast_fwd_decl.cpp ..\..\src\libsass\src\base64vlq.cpp ..\..\src\libsass\src\bind.cpp ..\..\src\libsass\src\check_nesting.cpp ..\..\src\libs
  ass\src\color_maps.cpp ..\..\src\libsass\src\constants.cpp ..\..\src\libsass\src\context.cpp ..\..\src\libsass\src\cssize.cpp ..\..\src\libsass\src\emitter.c
  pp ..\..\src\libsass\src\environment.cpp ..\..\src\libsass\src\error_handling.cpp ..\..\src\libsass\src\eval.cpp ..\..\src\libsass\src\expand.cpp ..\..\src\l
  ibsass\src\extend.cpp ..\..\src\libsass\src\file.cpp ..\..\src\libsass\src\functions.cpp ..\..\src\libsass\src\inspect.cpp ..\..\src\libsass\src\json.cpp ..\
  ..\src\libsass\src\lexer.cpp ..\..\src\libsass\src\listize.cpp ..\..\src\libsass\src\memory\SharedPtr.cpp ..\..\src\libsass\src\node.cpp ..\..\src\libsass\sr
  c\output.cpp ..\..\src\libsass\src\parser.cpp ..\..\src\libsass\src\plugins.cpp ..\..\src\libsass\src\position.cpp ..\..\src\libsass\src\prelexer.cpp ..\..\s
  rc\libsass\src\remove_placeholders.cpp ..\..\src\libsass\src\sass.cpp ..\..\src\libsass\src\sass2scss.cpp ..\..\src\libsass\src\sass_context.cpp ..\..\src\li
  bsass\src\sass_functions.cpp ..\..\src\libsass\src\sass_util.cpp ..\..\src\libsass\src\sass_values.cpp ..\..\src\libsass\src\source_map.cpp ..\..\src\libsass
  \src\subset_map.cpp ..\..\src\libsass\src\to_c.cpp ..\..\src\libsass\src\to_value.cpp ..\..\src\libsass\src\units.cpp ..\..\src\libsass\src\utf8_string.cpp .
  .\..\src\libsass\src\util.cpp ..\..\src\libsass\src\values.cpp
TRACKER : error TRK0005: Failed to locate: "CL.exe". El sistema no puede encontrar el archivo especificado. [D:\tfsJuan\logi\node_modules\@ionic\app-scripts\no
de_modules\node-sass\build\src\libsass.vcxproj]

Compilación del proyecto terminada "D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass\build\src\libsass.vcxproj" (destinos predeterminados
) -- ERROR.

Compilación del proyecto terminada "D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass\build\binding.vcxproj.metaproj" (destinos predetermi
nados) -- ERROR.

Compilación del proyecto terminada "D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass\build\binding.sln" (destinos predeterminados) -- ERR
OR.

ERROR al compilar.

"D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass\build\binding.sln" (destino predeterminado) (1) ->
"D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass\build\binding.vcxproj.metaproj" (destino predeterminado) (2) ->
"D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass\build\src\libsass.vcxproj" (destino predeterminado) (3) ->
(ClCompile destino) ->
  TRACKER : error TRK0005: Failed to locate: "CL.exe". El sistema no puede encontrar el archivo especificado. [D:\tfsJuan\logi\node_modules\@ionic\app-scripts\
node_modules\node-sass\build\src\libsass.vcxproj]

    0 Advertencia(s)
    1 Errores

Tiempo transcurrido 00:00:01.60
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\tfsJuan\logi\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\tfsJuan\\logi\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\tfsJuan\logi\node_modules\@ionic\app-scripts\node_modules\node-sass
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
logi@0.0.1 D:\tfsJuan\logi
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\juan.gonzalez\AppData\Roaming\npm-cache\_logs\2017-12-18T21_11_27_169Z-debug.log
-->

```
ionic start app blank
```
```

**Comment by jayordway** [comment]
I wouldn't say this is an issue with ionic. You are having issues downloading a platform dependent binary, win32-x64-59_binding.node, when install in node-sass. Are you behind a proxy? Can you access the link:
https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node

If you can get the binary and place it locally, you may be able to install it that way:

https://github.com/sass/node-sass#binary-configuration-parameters

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to close this issue and this issue list is intended for reporting bugs with the Ionic Framework or for requesting new features associated with it. For example if one of our [components](https://ionicframework.com/docs/components/) or [associated APIs](https://ionicframework.com/docs/api/) was not working properly.

As @jayordway points out, this is most likely an issue with your network configuration.

I also urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
