### ISSUE TITLE
Multiline input / textarea for ionic alert

### ISSUE THREAD

**Issue by derrohrbach** [ionic-team/ionic#13675]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[X] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request

**Current behavior:**
Currently the alert dialog already supports a wide variety of input methods. One important one is missing though: The ability to create multi line text input fields

**Expected behavior:**
If i specify input type as "textarea" i'd like it to create a text area in the alert dialog

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

There is already a feature request open for this (https://github.com/ionic-team/ionic-feature-requests/issues/288 (private repo, so you probably cannot navigate there, just including it for internal documentation purposes)), so I will close this.

We will copy the linked request back here when we begin work on it.

Thank you for using Ionic
