### ISSUE TITLE
Ionic mediastreaming app Issue?

### ISSUE THREAD

**Issue by Anbarasan-321** [ionic-team/ionic#13670]
https://ionicacademy.com/ionic-media-streaming/
i followed this above tutorial but got error like this tslint: C:/mediaStreaming/src/pages/home/home.ts, line: 2
All imports are unused.
L1: import { Component } from '@angular/core';
L2: import { NavController } from 'ionic-angular';
L3: import { StreamingMedia, StreamingVideoOptions, StreamingAudioOption
s } from '@ionic-native/streaming-media';
Please check this and tell me how i get output for this?

cli packages: 
    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:
    cordova (Cordova CLI) : not installed

local packages:
    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : browser 4.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:
    Node : v8.9.3
    npm  : 5.6.0
    OS   : Windows 7

Environment Variables:
    ANDROID_HOME : not set

Misc:
    backend : pro

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
