### ISSUE TITLE
ionic serve --lab, not working from next update in the code

### ISSUE THREAD

**Issue by dhrubo001** [ionic-team/ionic#13676]
ionic serve --lab, not working from next update in the code, the first serve is working, but the next update in code not working in the browser

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this as it does not have the issue template filled out with all the information that would be required to effectively help you. Also, it does not appear to be an Ionic Framework related issue.

What version of `@ionic/app-scripts` are you using? I have seen some issues on that project's issues list that resemble your general issue, but I cannot say for sure (not enough info). You should make sure you are using version `3.1.6` as that fixed those issues and if yours is the same perhaps it will fix yours.

I also urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

If the issue persists, the most appropriate repo to enter an issue against is https://github.com/ionic-team/ionic-app-scripts

Thanks for using Ionic!
