### ISSUE TITLE
Ionic 3 Won't run in Android 8.0 (Oreo) or earlier

### ISSUE THREAD

**Issue by abidakram01** [ionic-team/ionic#13684]
find the screen shots
![screenshot_20171220-123728](https://user-images.githubusercontent.com/16129333/34202722-a6cd76d4-e59e-11e7-9792-48b6e33733bb.jpg)
![screenshot_20171220-123947](https://user-images.githubusercontent.com/16129333/34202734-aad95af4-e59e-11e7-9d63-9ba1ec71ce37.jpg)

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please.

Especially important will be to provide a sample application that will not run on Android 8.0 or earlier and the steps you are following to build and load said application. I have installed and run plenty of Ionic 3 applications on my Note 4 which is running Android 6 without issue, so a full set of steps to duplicate would be very helpful.

If you are using Ionic Pro to do the building and deploying, be sure to use the Ionic Pro Support Portal (the URL is in the issue template).

Thanks for using Ionic!

**Comment by abidakram01** [comment]
thanks for your response
