### ISSUE TITLE
Problems with new ionic pro Git workflow

### ISSUE THREAD

**Issue by viveksinha9** [ionic-team/ionic#13681]
I was using legacy Ionic deploy in my Ionic 3 app. It was good but now it’s need an upgrade to Ionic pro (though I am too late, may be). So I created Ionic pro account, created new app there & linked my existing app to this newly created app.

Now when I am using git push ionic master commad, it shows this error:

Counting objects: 24427, done.
Connection to git.ionicjs.com closed by remote host.
fatal: The remote end hung up unexpectedly
Delta compression using up to 4 threads.
Compressing objects: 100% (23010/23010), done.
error: failed to push some refs to 'git@git.ionicjs.com:myapp/myapp.git'

But I see no changes in dashboard.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this an Ionic Pro question I am going to close this issue.

Please use the [Ionic Pro Support Portal](http://support.ionicjs.com) for Ionic Pro related questions and issue.

Thanks for using Ionic!
