### ISSUE TITLE
Lazy load TabsPage shows brief black screen when loading or reloading.

### ISSUE THREAD

**Issue by selotoprak** [ionic-team/ionic#13680]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Brief black screen when using lazy loading. Reloading window in google chrome using iphone layout.
Also when closing app and reopening it in ios.

**Expected behavior:**

The screen should not show any black screen when loading or reloading App.

**Steps to reproduce:**

Open google chrome developer and select iphone layout device or launh app in ios simulator.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by selotoprak** [comment]
This only happens when doing 

this.navCtrl.setRoot("TabsPage")

or 

this.rootPage = "TabsPage"

or 

this.rootPage = TabsPage;

my pages in tabs page are lazy loaded. 

Do I have to make the pages in TabsPage not lazy loaded?

**Comment by qikong333** [comment]
The reason is the tab style

You can add the following styles in app.scss

ion-tabs {
    background: #fff;
}

**Comment by qikong333** [comment]
@selotoprak

**Comment by selotoprak** [comment]
only this fixes

**Comment by qikong333** [comment]
您可以试试

**Comment by selotoprak** [comment]
The only thing that fixes the issue is 


IonicModule.forRoot(MyApp, {
      preloadModules: true
    })
After Preloading Modules everything work with or without lazy loading
:)

**Comment by qikong333** [comment]
谢谢，我也去尝试下

**Comment by selotoprak** [comment]
@NgModule({
  declarations: [
    MyApp,
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp, {
preloadModules: true
})     //like this
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}

**Comment by kensodemann** [comment]
I am going to close this as something that I can duplicate on neither the device nor the simulator. I can only duplicate the described behavior in Chrome in iOS simulation mode.

All tests were run without `preloadModules` set.

If you can provide a sample application via GitHub or https://stackblitz.com that duplicates this issue I will be happy to reopen the issue and have a look.
