### ISSUE TITLE
"ionic cordova run android" says $ANDROID_HOME is not set but it's set

### ISSUE THREAD

**Issue by SirajKakeh** [ionic-team/ionic#13693]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`ionic cordova run android --device` return an error:
"Error: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory."

**Expected behavior:**
expected `ionic cordova run android --device` to run the app on the connected device

**Steps to reproduce:**
`ionic cordova run android --device`
or
`ionic cordova run android`

**Other information:**
`` echo $ANDROID_HOME `` : "/home/leno/Android/Sdk"
I also have $ANDROID_HOME/tools and $ANDROID_HOME/platform-tools in my path:
`` echo $PATH `` : "/home/leno/Android/Sdk:/home/leno/flutter/bin:/home/leno/bin:/home/leno/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/leno/Android/Sdk/tools/bin/sdkmanager:/home/leno/Android/Sdk/platform-tools"

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.3
    npm  : 5.6.0 
    OS   : Linux 4.10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Out of curiosity, do you get the same thing if you just use `cordova run android`? (without running the cordova command through our CLI)

Thanks for using Ionic!

**Comment by SirajKakeh** [comment]
@kensodemann I tried it and it produced this error:
`(node:22951) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module '../cordova/platform_metadata'
(node:22951) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
Now even if I run with `ionic` I still get this new error.

**Comment by kensodemann** [comment]
OK. Thank-you for trying that. I just wanted to make sure we didn't have an issue with the Ionic CLI or anything, but since you are getting the exact same issue with `ionic cordova run android` and `cordova run android` there is no issue with the CLI.

The issue could be a Cordova issue, but is most likely in your configuration.

I suggest starting with just getting a generic Cordova app building using this as a guide: https://cordova.apache.org/docs/en/latest/guide/platforms/ubuntu/index.html

And then moving forward from there.
