### ISSUE TITLE
Time & Date picker should rotate in both direction indefinitly

### ISSUE THREAD

**Issue by kochraph** [ionic-team/ionic#13696]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ X] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently, if you want to select 59minutes, you need to start at 0 and slowly increase to 59...
Same for the dates, if you want to go to 28th day of the month, you need to go from 1 to 28th...
(in most case...)

**Expected behavior:**
instead of only incrementing, we should be able to go in reverse direction

**Steps to reproduce:**
is it really needed in this case ?
Open the Calendar on IOS and create a new event, you will see the behavior natively  on date and time ( you can go in both direction)

**Related code:**
Could I add a small movie from my iphone calendar app?

-->

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ionic info

cli packages: (/Users/xxxxx/Documents/Ionic_Source/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v6.11.1
    npm               : 5.4.2 
    OS                : macOS Sierra
    Xcode             : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : /Users/xxxxx/Library/Android/sdk/

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#343

**Comment by kochraph** [comment]
the page link is dead... any new url ?
