### ISSUE TITLE
Edit icon

### ISSUE THREAD

**Issue by erperejildo** [ionic-team/ionic#13695]
Could we have this new (and useful) icon?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. I am going to close this issue as it is related to Ionicons, which has its own repo and issue list.

Please request new icons here: https://github.com/ionic-team/ionicons

Thanks for using Ionic!

**Comment by erperejildo** [comment]
Thanks for pointing me out
