### ISSUE TITLE
tls.TLSSocket is not a constructor

### ISSUE THREAD

**Issue by Chinafreak** [ionic-team/ionic#13708]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

Hey guys,

any chance why "tls" from node won't work on Ionic? 

I imported tls (which it's already build-in in node)

```
import tls from "tls";
```

And I tried to run this 

```
var test = new tls.TLSSocket();
```

But all what I got is a Error:

```
Error: Uncaught (in promise): TypeError: __WEBPACK_IMPORTED_MODULE_3_tls___default.a.TLSSocket is not a constructor
```

This script runs absoluty fine on simple nodejs project.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
