### ISSUE TITLE
Fixed menu in Ionic

### ISSUE THREAD

**Issue by pelad2** [ionic-team/ionic#13703]
I use ionic 3 and i need a fixed menu for browser

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

I am not entirely sure what you are asking for, but have you looked into the split pane feature?

Thanks for using Ionic!
