### ISSUE TITLE
InAppBrowser.on(‘loadstop’) not working

### ISSUE THREAD

**Issue by HelloWar75** [ionic-team/ionic#13707]
I am cannot use .on in InAppBrowser i need help my code is:

```typescript
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { InAppBrowser } from "@ionic-native/in-app-browser";

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, private iab: InAppBrowser) {

  }

  doLoginTwitter() {
    const browser = this.iab.create("http://xxxxxxx.com/api.php",  '_self');
    browser.on('loadstop').subscribe(function(event){
      console.log("LOG: API Response");
      console.log(event);
    });
  }

}
```
I’ve tried it anyway but it never works on loadstart and loadstop does not work I want to know why it does not work I’m testing on my cell phone using Ionic DevAPP but it still does not work, it opens the normal API window but it does not work fires the logs on the console I am using the ionic command --lab -c to start the ionic server and it does not work please help me.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
