### ISSUE TITLE
HTML 5 Video Tag In Ionic 3 

### ISSUE THREAD

**Issue by ebinsleeba** [ionic-team/ionic#13701]
Hi,
Am trying to load video in my ionic app with HTML 5 Video tag. When i switched my video to full screen mode the controls are displaying but am not able to click on it or the controls not working. but in ios it just works fine . Is this a general issue in ionic can anybody help on this ??

video poster="{{fileUploadUrl}}{{postDetails.Thumbnail}}" preload="metadata"  controlsList="nodownload">
                    source src="{{fileUploadUrl}}{{postDetails.MediaUrl}}" type="video/mp4" />
                </video

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
