### ISSUE TITLE
statusbar show error

### ISSUE THREAD

**Issue by zhuzhiqiang** [ionic-team/ionic#13714]
iPhone 6.0 , iOS version:11.2.1
snapshot:
![image](https://user-images.githubusercontent.com/9068161/34354331-7fb84eb0-ea68-11e7-89ae-9ee941f89574.png)

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please.

Items that would be particularly helpful:

- create a repo on GitHub with a sample application that demonstrates the issue you are having
- provide exact steps on how you are getting the issue, including how you are building the application and how you are deploying it to your device.
- provide the output of `ionic info`

Also, make sure you are following everything here: https://blog.ionicframework.com/ios-11-checklist/ and are using Xcode 9 to build the application.

Thanks for using Ionic!
