### ISSUE TITLE
*ngFor on ion-item or div deactivates y-axis scroll in ion-segment or any tab component

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic#13716]
Hello, I found a big issue when using ion-segment.

I'm populating a page of ion-segment with ion-items which is getting item data from data provider. 
The issue is when items are populated from data provider, it looks like it automatically deactivates y-axis scroll. This only happens when I do this within ion-segment's page.
Is there any way to fix this problem? This is apparently a bug in Ion-segment.

```
<div ngSwitchCase="'segmentPage04'">
 <div  *ngFor="let item of items">  
                                
                                     <ion-item>
                                       <button tappable  (click)="navigate()" id="item-button">
                                    
                                        <h4><strong>{{item.title}}</strong></h4>
                                        <p>{{item.description}} </p> 
                  
                                     
                                        </button>
                                         
                                      </ion-item>

                              </div>

</div>
```

**Comment by jamesharvey2** [comment]
The same issue was found here:

https://forum.ionicframework.com/t/scroll-in-segment-with-list-of-cards-not-working/66543

It looks like this is a bug that needs to be fixed ASAP.

**Comment by wbhob** [comment]
Anything in the console?

**Comment by jamesharvey2** [comment]
Nope. It's easy to replicate this error. Make ion-segment divs. And create a data provider and make 12 items. Then try to populate ion-segment's div using *ngFor loop with the items from data provider. You will see ion-segment automatically deactivating y axis scroll..

**Comment by Nitingadhiya** [comment]
do you try "ion-list" instead of "div"?

**Comment by wbhob** [comment]
Yeah, like @Nitingadhiya said, your code is a little bizarre. That's not an ion-segment, that's an ion-list without the list.

**Comment by jamesharvey2** [comment]
Yes, I have tried ion-list and ion-item. The reason I'm using div in example is because ion-item didn't work and I wanted to try normal html5 component. 

This error can be easily replicated. Any looped items from data provider will deactivate y-axis scroll in ion-segment.

**Comment by jamesharvey2** [comment]
This bug happens on regular tab menu as well,,, if *ngFor loop is nested within any tab component, it will cause this error.

It needs to be fixed ASAP

**Comment by jamesharvey2** [comment]
Problem is solved by using ion-view instead of ion-item and then adding overflow-y: scroll to the main div container. This is not a usual way to work around this problem.. but it's working.
Ion-item has a bug apparently... I'll be using ion-view until Ionic team fixes this problem.
