### ISSUE TITLE
 [(ngModel)] two-way binding doesn't work with --minifyjs

### ISSUE THREAD

**Issue by sid-ihycq** [ionic-team/ionic#13712]
just a simple code

LoginPage:
```
@IonicPage()
@Component({
	selector: 'page-login',
	templateUrl: 'login.html',
})
export class LoginPage {
	private login: any = {};
	doLogin() {
		console.log(this.login.username);//this will be undefined
	}
}
```

login.html：
```
<div class="input-group">
	<ion-item>
		<ion-label fixed>name</ion-label>
		<ion-input type="text" [(ngModel)]="login.username"></ion-input>
	</ion-item>
</div>
<div class="login">
	<button ion-button block color="danger" (click)="doLogin()">Login</button>
</div>
```

this code：  [(ngModel)]="login.phoneNum" works fine when i run with serve cmd. but when i build the project with 'ionic build --minifyjs' and deployed on web server, it cann't bind my input to ts code: this.login.username, and doLogin will always output with undefined.

btw, i tryed to import FormsModule， it doesn't work too.

**Comment by jennielynshapiro** [comment]
probably related to https://github.com/ionic-team/ionic/issues/13718

**Comment by sid-ihycq** [comment]
@jennielynshapiro use raw html input for instead is ok！

**Comment by longgt** [comment]
@jennielynshapiro what do you mean when using **login.phoneNum** as ngModel and logging as **login.username**?
Is there something wrong?

**Comment by sid-ihycq** [comment]
@longgt 3q, i fixed the example code. the problem is still there.

**Comment by anatoly-spb** [comment]
As the workaround you can freeze uglyfy-es version in your project.json:
```

**Comment by anatoly-spb** [comment]
@sid-ihycq Change version of `@ionic/app-scripts` to 3.1.7
```
npm install @ionic/app-scripts@3.1.7 --save-dev --save-exact
```
 and try your example.

**Comment by topseom** [comment]
@anatoly-spb version 3.1.7 it's work for me.

**Comment by tiange008** [comment]
@anatoly-spb  it's work for me. thank you！

**Comment by kensodemann** [comment]
I am going to close this assuming that the upgrade to `@ionic/app-scripts` will work for @sid-ihycq  the same as it worked for @anatoly-spb. If it does not, we will be happy to re-open the issue.

**Comment by FanFanFantastic** [comment]
thanks a lot of the fix, I was getting frustrated how the ionic serve works but after deployment ionic-input just breaks down
