### ISSUE TITLE
ion-searchbar not working with --prod flag

### ISSUE THREAD

**Issue by robherman** [ionic-team/ionic#13722]
**Ionic version:**  
[ ] **2.x**
[x] **3.19.0**
[ ] **4.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request

**Current behavior:**
When building using the production flag: "ionic cordova build android --prod" or "ionic cordova build ios --prod", the ion-searchbar does not trigger searches and cannot be closed either once open (Cancel button has no effect).

**Expected behavior:**
ion-searchbar should work normally

**Ionic info:**

```
cli packages: (/Users/rob/Desarrollo/Git/consultorio-movil/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.4.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.7.0
    npm        : 5.5.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Please try using `@ionic/app-scripts` version `3.1.7`. It contains this fix: https://github.com/ionic-team/ionic-app-scripts/pull/1353

Thank you for using Ionic

**Comment by robherman** [comment]
Thanks a lot @kensodemann , it's working flawlessly with `@ionic/app-scripts` `version 3.1.7`.

**Comment by kensodemann** [comment]
Excellent!!
