### ISSUE TITLE
Default History missing when using browser's back button

### ISSUE THREAD

**Issue by soynog** [ionic-team/ionic#13723]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
I'm using Deeplinking in my Ionic v3 app. I've given all my pages a defaultHistory of the home page, configured in my app.module.ts:

```
     IonicModule.forRoot(MyApp, {}, {
      links: [
        { component: HelpMeFindPage, name: 'Home', segment: 'home' },
        { component: AboutUsPage, name: 'About Us', segment: 'about_us', defaultHistory: [HelpMeFindPage] },
        { component: ContactUsPage, name: 'Contact Us', segment: 'contact_us', defaultHistory: [HelpMeFindPage] },
        { component: UserLocatorPage, name: 'Locator', segment: 'locator/:viewType', defaultHistory: [HelpMeFindPage] },
        ...etc.
       ]})
```

If I navigate to a page within the app, it has a back button as normal with the app's nav stack. If I load a page from a url, or refresh a page, it gives me a back button with the home page only on the stack, as expected. However, if I navigate to a page and then navigate back to the previous page (or forward again) using the browser's back/forward buttons, the pages do not have a back button.

**Expected behavior:**
I would expect that when loading a page with the browser back/forward button it would act the same as loading it from a URL.

Am I misunderstanding how this is supposed to work? How can I get the default history to show up any time a page is loaded, rather than just if it's loaded cold from a URL or browser refresh?

Thank you.

**Comment by kensodemann** [comment]
From the documentation:

> The default history of any page can be set in the defaultHistory property. This history will only be used if the history doesn't already exist, meaning if you navigate to the page the history will be the pages that were navigated from.

If you are navigating using the browser back/fwd buttons, you have history of some sort so you will not get the default history bit to kick in at that point.
