### ISSUE TITLE
react 16 (fiber) support

### ISSUE THREAD

**Issue by webmobiles** [ionic-team/ionic#13720]
I was working a little bit with angular1 and then angular2,  then I've started with react. Then realized a lot of advantages of react over angular 2,4,5,etc

Ionic it's a nice environment, it's possible to change angular by React in the future? using it with apollo and redux, it's amazing

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Being able to work with other frameworks or without any framework at all if you so desire is a goal of the next version of Ionic. The initial release of Ionic will also include the Ionic Angular library for use when building your application is Angular, but I would expect other framework related libraries to follow shortly after that, including React.

Thank you for using Ionic
