### ISSUE TITLE
cant show URLSearchParams when set 'locationStrategy: "path"'

### ISSUE THREAD

**Issue by mike8625** [ionic-team/ionic#13725]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I input xxx.com/yyy?zzz=123 on locationbar, hit enter,  locationbar shows  xxx.com/yyy, zzz=123 is disappear.

**Expected behavior:**

 locationbar shows as same as I input
**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```
app.module.ts
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp,{ locationStrategy: "path" }, {links:[{ component: xxx, name: 'xxx', segment: 'xxx' }]})
  ],
**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

It is highly unlikely that there will be another v3 release. For the next major release of Ionic, nav is going through some major rework and will more directly use whatever router the given framework is using (we also plan on eventually supporting more than just Angular). Just letting you know what to expect coming up in the near future.

Thank you for using Ionic

**Comment by mike8625** [comment]
thank you
