### ISSUE TITLE
Autofocus in modal on android immediately loses focus

### ISSUE THREAD

**Issue by RyanHow** [ionic-team/ionic#13721]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
If a modal opens with a textfield with the autofocus attribute, the text field gains focus, then immediately loses focus. This only occurs on android. iOS appears to be ok, as does desktop.

**Expected behavior:**
The textfield would gain focus when the modal opens and retain that focus,

**Steps to reproduce:**
npm install -g ionic cordova
ionic start myapp blank
ionic generate page modal
Add code below and other app module entries, etc
ionic cordova emulate android

**Related code:**
In home.html
``` 
<button ion-button (click)="openModal()">Open Modal</button>
```
in home.ts
```
  openModal() {
    this.modalCtrl.create(ModalPage).present();
  }
```

In modal.html
```
  <ion-item>
    <ion-label>Name</ion-label>
    <ion-input type="text" autofocus></ion-input>
  </ion-item>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\ryan\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.11.0
    npm  : 3.10.10
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by Rhonun** [comment]
did you find a solution for this? its happening for contenteditable divs as well

**Comment by RyanHow** [comment]
@Rhonun I didn't dig into it. But I ended up not using autofocus and just called focus manually using a timer.

You need to make sure you manually focus with a timeout, otherwise it does the same thing if you try and focus straight away.

Ideally I've love it if it focused while the view was sliding in, otherwise the user waits for the transition to complete, then a small timeout, then waits for the keyboard to slide up.

**Comment by Kshitiz294** [comment]
@RyanHow can you share the working code here?
Even I am having the similar issue, input loses focus immediately.

**Comment by Rhonun** [comment]
@Kshitiz294 for me the problem was occurring because the [NavOption keyboardClose](https://github.com/ionic-team/ionic/blob/master/src/navigation/nav-util.ts#L203) is true by default. You need to pass this in as false on your present call to [prevent ionic from telling the active element to blur](https://github.com/ionic-team/ionic/blob/master/src/navigation/nav-controller-base.ts#L789).

**Comment by RyanHow** [comment]
@Kshitiz294 I just read the comment from @Rhonun. I'd go with that!. I'm about the try it. The setTimeout and focus calls are horrible, and they are slow to respond. Thanks @Rhonun !!!
