### ISSUE TITLE
Themed Action Sheets: No way to change .action-sheet-selected by scss-variables

### ISSUE THREAD

**Issue by Martin-Luckow** [ionic-team/ionic#13728]
I have an app with a customized theming. The background of my action sheets is dark. 
If I open an action sheet with a selected item in iOS, its background is #fff and can only be modified by direct css.

Proposal: introduce a scss-variable for the backgrounds of: 
 
.action-sheet-ios .action-sheet-selected {...}

.action-sheet-md .action-sheet-selected {...}

.action-sheet-wp .action-sheet-selected {...}

**Comment by brandyscarney** [comment]
This has been added for v4: https://github.com/ionic-team/ionic/commit/f41bb39ce34dcff75b65e040fb4fb9015dc93105

Thank you for the issue!
