### ISSUE TITLE
can't save base64 image string to mobile device gallery using native plugin (base 64 to gallery). please help me to save svg image as a png into mobile device gallery using ionic framework.

### ISSUE THREAD

**Issue by PriyankaTikande** [ionic-team/ionic#13729]
I am using ionic 2 framework. I want to save svg image as a png in mobile device gallery.
I have used base62 to gallery plugin to save image in gallery.
I have base 64 string.

here is my home.html code::

<button ion-button (click)="downloadImage()" color="primary">Download image</button>
 <img id="imgSvg" src="assets/imgs/mydesign1.svg" class="svg"/>
	
here s my home.ts code::
DecodeBase64 contains base 64 string
downloadImage(){
this.base64ToGallery.base64ToGallery(this.DecodeBase64,{ prefix: 'img_' }).then(
      res => console.log('Saved image to gallery ', res),
      err => console.log('Error saving image to gallery ', err)
    );
}

but image not save and did'nt give any output.
please help me.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by cesarbmolina** [comment]
Hi, happy late, I had the same problem but then I realized that the problem was that I did not have permissions for the multimedia gallery, so I had to use this plugin to solvertar my problem

https://ionicframework.com/docs/native/android-permissions/

in your ngOnInit place this
this._androidPermissions
      .checkPermission(this._androidPermissions.PERMISSION.READ_EXTERNAL_STORAGE)
      .then(err =>
        this._androidPermissions.requestPermission(this._androidPermissions.PERMISSION.READ_EXTERNAL_STORAGE)
      );

this._androidPermissions.requestPermissions([this._androidPermissions.PERMISSION.READ_EXTERNAL_STORAGE]);

**Comment by cheeroke** [comment]
@cesarbmolina ,
sorry for dragging it further, I can't find ngOnInit in my project...

**Comment by cesarbmolina** [comment]
https://ionicframework.com/docs/api/navigation/NavController/ 

check the app lifecicle, you should check the permissions where the screen is initialized. In my case it is ngOnInit, in your case it may be in the constructor or in the ionViewWillEnter

**Comment by cheeroke** [comment]
@cesarbmolina Thanks, it worked.
One question if you can, I've used PERMISSION.WRITE_EXTERNAL_STORAGE as I wanted to write to external memory, does READ include both read/write, do you know?
