### ISSUE TITLE
Meta from '@angular/platform-browser' is not working with Ionic

### ISSUE THREAD

**Issue by theunreal** [ionic-team/ionic#13738]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**
Simply trying to add meta tags dynamically using the Angular meta service. 
Meta tags are not added.

**Expected behavior:**
Meta tags should be added when using: 
`meta.addTag({property: 'description', content: metaContent});`

**Steps to reproduce:**
1. Import Meta service 
2. Add new meta tag

**Related code:**

```
import {Meta} from '@angular/platform-browser';

constructor( private meta: Meta, title: Title) {
const metaContent = `some meta content`;
meta.addTag({property: 'description', content: metaContent});
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\home\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.0.1
    Node              : v6.11.2
    npm               : 5.3.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\home\AppData\Local\Android\sdk

Misc:

    backend : pro

```

**Comment by kensodemann** [comment]
I am going to close this as something that I cannot duplicate.

I add the following lines to `app.component.ts`:

```ts
    this.meta.addTag({ name: 'description', content: 'This is metadata' });
    this.meta.addTag({ name: 'author', content: 'ken@ionic.io' });
```

And when run, I see that metadata in the `head`

If you can provide a sample application via GitHub or https://stackblitz.com that duplicates this issue I will be happy to reopen the issue and have a look.
