### ISSUE TITLE
android 7.0.0, build error: Cannot find module '../cordova/platform_metadata'

### ISSUE THREAD

**Issue by sid-ihycq** [ionic-team/ionic#13735]
since i remove(v6.3.0) and add android again(lastest v7.0.0), i got this error when build the app: 

(node:17320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module '../cordova/platform_metadata'
(node:17320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mhartington** [comment]
Hi there! Are you using the cordova-plugin-ionic, The Ionic Pro plugin?

**Comment by mburger81** [comment]
Now the default `cordova-android` is in version **7.0.0** and there are many plugins which does not work with this version of **corova-android**.
For example the plugin `cordova-plugin-fcm` still does not work, and `cordova-sqlite-storage` was resolved this morning and does work now.
See this issues for example
https://github.com/litehelpers/Cordova-sqlite-storage/issues/729#issuecomment-355271858
https://github.com/fechanique/cordova-plugin-fcm/issues/435
https://github.com/fechanique/cordova-plugin-fcm/issues/436

The fcm plugin has also a sever error, after installing this you are not able to install other plugins like your ionic-plugin-keyboard. So in this case also the order in config.xml file is important.

IMO for not it is not safe to use `android-cordova@7.0.0`

Thx

**Comment by greendome** [comment]
Hi, 

I'm getting the same error...not using the Ionic Pro plugin (I believe) or how can I check if I am?

`(node:58064) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module '../cordova/platform_metadata'`

Thanks

**Comment by greendome** [comment]
I have Ionic plugins installed:

"cordova-plugin-ionic": "^2.0.3"
"cordova-plugin-add-swift-support": "^1.7.0"

but still getting the same issue:
`(node:58064) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module '../cordova/platform_metadata'`

Any idea what can do to fix this, please? 

Many thanks.

**Comment by dickverweij** [comment]
I have the same problem

**Comment by mhartington** [comment]
Please **update** all of your plugins (remove/add them). This is an issue with a Plugin trying to use a feature that was removed in cordova 8. Plus open issues on the appropriate plugin repo as this is not specifically an ionic issue.
