### ISSUE TITLE
ionic cache is not working for first time when back from none tab view.

### ISSUE THREAD

**Issue by JennysGit** [ionic-team/ionic#13733]
Hi ,
I am using ionic 1.3.3 with tabs template, Ionic cache is not working when back from a none tabs view.
when I go to chat detail page and then back to tabs chat view for first time. the cache is not working and the controller reload. 
How to deal with the problem? I want to use ionic cache.
 $stateProvider

      // setup an abstract state for the tabs directive
      .state('tab', {
        url: '/tab',
        // abstract: true,
        cache: true,
        templateUrl: 'templates/tabs.html'
      })

      // Each tab has its own nav history stack:

      .state('tab.dash', {
        url: '/dash',
        views: {
          'tab-dash': {
            templateUrl: 'templates/tab-dash.html',
            controller: 'DashCtrl'
          }
        }
      })

      .state('tab.chats', {
        url: '/chats',
        views: {
          'tab-chats': {
            templateUrl: 'templates/tab-chats.html',
            controller: 'ChatsCtrl'
          }
        }
      })
      **.state('chatDetail', {
        url: '/detail/:chatId',
        templateUrl: 'templates/chat-detail.html',
        controller: 'ChatDetailCtrl'
      })** /* chat detail page, */

      .state('tab.account', {
        url: '/account',
        views: {
          'tab-account': {
            templateUrl: 'templates/tab-account.html',
            controller: 'AccountCtrl'
          }
        }
      });

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Also, for Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1

Thanks for using Ionic!

**Comment by wggley** [comment]
Still this problem occurs on 2018 and just recently I saw 3 posts regarding the same problem and when there is no answer, you say that is a support?

It's not, it's a bug, I'm debugging it right now and I'm seeing that loadViewElements asks fors navViewCtrl Elements and first view is not appearing there!
