### ISSUE TITLE
How to save svg image as a png on mobile device gallery with new folder?

### ISSUE THREAD

**Issue by PriyankaTikande** [ionic-team/ionic#13731]
I am new in ionic 2 and angular 2.
I want to save svg image as png in mobile device gallery using ionic 2.
Please help me.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
