### ISSUE TITLE
ion-segment is so slow...

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic#13740]
I realized when I put my contents inside ion-segment, everything becomes slower.
This doesn't happen on my custom made angular 5 tab menu. 
Please compare performance of ion-segment with angular 5 tab menu. 
Angular 5 tab menu is more stable and faster.. I guess ion-segment is buggy.

**Comment by kabus202** [comment]
@jamesharvey2  can you share your code? I'm also using segment without any problems or performance issues.

**Comment by jamesharvey2** [comment]
https://github.com/ionic-team/ionic/issues/13716

This is one of the examples.. I'm not doing anything special. 
Ion-segment responds slower than angular 5 tab. and it loads contents faster.
It has many many bugs.. I spent many many hours on fixing its bug.

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please.

Also, please provide a sample application via a GitHub repo that can be used to duplicate and debug your issue.

Thanks for using Ionic!

**Comment by jamesharvey2** [comment]
I will definitely do that @kensodemann 
The biggest concern about ion-segment is the loop problem.
It can be easily duplicated for debugging. 

any div or ion-item with *ngFor loop nested within ion-segment will deactivate y-axis scroll. 
and ion-segment is slower. 

Please fill ion-segment with lots of graphic contents, buttons, texts and then compare it with angular 5 tab menu. Ion-segment tabs will load items slower and react much slower... 
I'm not using any of ionic UI in my project besides ion-search-bar and ion-view due to many problems in UI. I'm making my own CSS3 UI. 
Great job on implementing Angular 5 but its Ionic UI components are still questionable in terms of performance.

Thanks and I hope all problems get fixed in this year!

**Comment by peterpeterparker** [comment]
I just gonna let that here...so I was facing the same problem, on one of my screens, the `ion-segment` were slow on iOS respectively not rendered enough fast when I was transitioning from one page to the other

Firstly I noticed that the problem only happened on iOS and that I was able to reproduce it even with `ionic serve` and debugging in Chrome. Secondly I found out that the lag only happened if the segment was contained in a `ion-footer`

    <ion-footer>
        <ion-toolbar>
          <ion-segment [(ngModel)]="something">
            <ion-segment-button value="myvalue">
                <ion-icon name="pin"></ion-icon>
                <span>Location</span>
            </ion-segment-button>
          </ion-segment>
        </ion-toolbar>
    <ion-footer>

Then I noticed that on another page, where I use segments too, they were rendered faster ... I began to try to find the difference and I finally found one of the weirdest workaround ever: if I add a `ngIf` on the `ion-toolbar` to check a variable I would init in `ionViewWillEnter` then the segments gonna be rendered super fast. 

For example

     myTrigger: boolean = false;
     
     ionViewWillEnter() {
       myTrigger = true;
     }

    <ion-footer>
        <ion-toolbar *ngIf="myTrigger">
          <ion-segment [(ngModel)]="something">
            <ion-segment-button value="myvalue">
                <ion-icon name="pin"></ion-icon>
                <span>Location</span>
            </ion-segment-button>
          </ion-segment>
        </ion-toolbar>
    <ion-footer>

Don't ask me why ... hope it could help someone else too
