### ISSUE TITLE
hello,I use ionic1 when,Ghosting occurs using ion-scroll in IOS，who can help me，thanks！！！

### ISSUE THREAD

**Issue by qinqinglin** [ionic-team/ionic#13744]

**Comment by qinqinglin** [comment]
@mhartington

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
