### ISSUE TITLE
URL in PWA changed when ionViewCanLeave returns false

### ISSUE THREAD

**Issue by abhibly** [ionic-team/ionic#13746]
**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

**Current behavior:**
URL in PWA gets changed even if ionViewCanLeave returns false

**Expected behavior:**

URL shouldnot be changed because the nav gaurd in dashboard page has returned false so the page is not destroyed and even url shouldn't be changed.It will create a confusion for the user if the url doesnot match the component.

**Steps to reproduce:**

1.Click on Go To Dashboard button in HomeScreen
2.Click browser back button when Dashboard page is loaded.You will see Home in url but Dashboard is the currently active page .
**Related code:**

https://stackblitz.com/edit/ionic-yc7yzn?file=components%2Fhome%2Fhome.component.html

**Comment by petamoriken** [comment]
I tried to push a history when the browser back button was pressed, but it did not go well.
https://stackblitz.com/edit/ionic-feeeab?file=components/dashboard/dashboard.component.ts

```js
ionViewCanLeave() {
  const hash = "#/nav/n4/Dashboard";
  if (location.hash !== hash) {
    location.hash = hash;
    // history.pushState(null, "", "Dashboard");
  }
  return false;
}
```

Does anyone know this solution?
