### ISSUE TITLE
Feature request - Native Java API & Objective-C API access

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic#13741]
Hi Ionic Team.

Would you please make it possible for us to access android's native java API & apple's objective-C api using simplified typescript command on Ionic 4? 
That'll be much better than using old cordova plugins which no one manages anymore. To be honest, it feels so weird to contact people who made those plugins 5 years ago to ask about bug fixes......

Android's java API provides what those plugins provide: 
https://developer.android.com/reference/packages.html
Actually, they have more to offer beyond what those old cordova plugins can do for us. 

What if we can get access to them by using typescript on Ionic 4? 
Java is a superior programming language for android overall but XML is nowhere close to HTML5 & CSS3 in terms of styling.. 

Please make this happen in Ionic 4.
Then Ionic app will be perfect.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to close this as we already have plans in place along these lines: https://ionic-team.github.io/avocado/

Thank you for using Ionic

**Comment by jamesharvey2** [comment]
WOW! thanks a lot for that.
I wanted to move to NativeScript just because of limited Java API features I could use on Ionic...
If you guys remove all existing problems in Ionic 3, I'm with you guys. 

- slow loading time, overall chunky & slow speed of app when lots of things are done on Angular 5
- bizarre loading screen problems which don't happen on other app frameworks. Gray loading screen can't be removed. 
- Java API, Objective-C API access not available. Google ships a plenty of android java APIs! 
- It relies on old cordova plugins which no one manages anymore. Users need to contact an unknown publisher who made those plugins 5 years ago. They have no idea about them at all...
- bugs in Ionic UI components. I had to spent roughly 20+ hours on some issues which have nothing to do with actual programming problem of my own. 
- Modal component is really slow... it takes 2 seconds to show up when you have lots of things going on in Angular 5. I'm choosing to not use it in my project.

**Comment by jamesharvey2** [comment]
Is Avocado going to use Angular 5? 
and will it integrate with Ionic 4? 
Angular 5 still works well and it provides lots of convenience for mobile development.

**Comment by kensodemann** [comment]
Avocado will have nothing to do with Angular per se. It will be filling the same layer in the stack that Cordova is currently filling.

**Comment by jamesharvey2** [comment]
I see.. I hope that will solve problems Cordova has. 
Can't wait to see what you guys will publish!

**Comment by jamesharvey2** [comment]
I learned React framework works with Typescript too... React is known to be faster than Angular so maybe using React with typescript on avocado will solve speed problem. Just an opinion...
