### ISSUE TITLE
Ionic.css is not working on ionic2 version. 

### ISSUE THREAD

**Issue by prafullwizorbit** [ionic-team/ionic#13745]
Hi
    I am using ionic2 version which  have main.css but it is conflict with ionic.css. means i am not using any css of ionic.css file in ionic2. any help

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
