### ISSUE TITLE
searchbar's (ionInput) not working on --prod build 

### ISSUE THREAD

**Issue by thorizer** [ionic-team/ionic#13743]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x] 3.9.2
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
- (ionInput) of searchbar never triggers on prod build on both android and web.
 - Works great on both platforms in debug build.

**Expected behavior:**
HTML : <ion-searchbar  (ionInput)=“logValue()” >
Ts: logValue() { console.log(“why”) }
Expected : logs "why"

**Steps to reproduce:**
the steps are simple. 
```
HTML : <ion-searchbar  (ionInput)=“logValue()” >
Ts: logValue() { console.log(“why”) }
```

**Other information:**
```
    angular : 5.1.2
    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.10.1
    npm               : 4.4.4
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\SBS\AppData\Local\Android\sdk

Misc:

    backend : legacy
```

**Comment by MrPutuLips** [comment]
I'm having the same issue.

I've tried `(ionInput)="search()"`, `(ionInput)="search($event)"`

Definitely only works when not using --prod flag.

**Comment by thorizer** [comment]
fixed my issue by installing: npm install @ionic/app-scripts@3.1.7 --save-dev --save-exact .

source : https://github.com/ionic-team/ionic/issues/13718

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I tried this but could not duplicate the results. Everything works fine even when built with `--prod`

I see you are using `@ionic/app-scripts@3.1.6` try `3.1.7`

Thank you for using Ionic

**Comment by kensodemann** [comment]
And I see you just tried that while I was typing... :)
