### ISSUE TITLE
chat project in ionic with socket.io, blank screen when running server and application, help please.

### ISSUE THREAD

**Issue by crisHU10** [ionic-team/ionic#13748]
it goes blank when running the server and then the application with ionic serve. https://github.com/crisHU10/chat-master

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
