### ISSUE TITLE
Ionic-CLI does not allow interactive shell input (git credentials)

### ISSUE THREAD

**Issue by wilk-polarny** [ionic-team/ionic#13755]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[  ] **2.x**
[X] **3.x**
[  ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[  ] feature request

**Current behavior:**
When running cordova commands through ionic whose resulting calls issue a git command, prompted credentials cannot be entered using the shell. Shell input is not being redirected to the credential helper. The cursor at the input field stays blinking, but input is not possible, nor is it possible to SIGTERM or close the command line windows without killing the wrapped npm process.

**Expected behavior:**
Ionic-CLI shall be able to process input for issued git commands.
using cordova commands directly works, but I noticed by the way that cordova simply clones repos, Ionic rather tries to create submodules, it seems (which failed on previous versions on git for windows with an error stating a missing package.json).

**Steps to reproduce:**
Add a plugin using the Ionic-CLI with a git repo as its location requiring basic authentication.

**Related code:**

```
ionic cordova plugin add git+https://github.enterprise.tld/ORGUNIT/cordova-enterprise-plugin.git
```

**Other information:**
OS: Win10
Ionic: 3.19.0
cli-utils: 1.19.0
Ionic-Framework: 3.9.2
App-scripts: 3.1.7
Cordova: 7.1.0
Node: 6.12.0
npm: 5.6.0
git: 2.15.1.windows.2
Shell: Windows Command Line Prompt

(no direct ionic info output, I had to write it down, as the machines are air gapped)

Another odd thing is, that the git credential manager for windows is not being called (even though the credential helper is set to manager, and the modal dialog setting is set to 'true'), wheras usuall git calls on the windows prompt and git bash usually trigger a modal dialog for the first time.

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2941

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Since this is not an Ionic Framework issue, I moved it to the Ionic CLI repo.

Thank you for using Ionic
