### ISSUE TITLE
Currency Recognition System

### ISSUE THREAD

**Issue by geekyorion** [ionic-team/ionic#13758]
Hi Team,

I am new to image processing and I want to develop currency recognition type stuff.
Can anyone tell me the name of valid open source s/w and how to use OpenCV in ionic 3.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
