### ISSUE TITLE
Barcode scanner camera preview overlay

### ISSUE THREAD

**Issue by Nitingadhiya** [ionic-team/ionic#13752]
current Behaviour : camera preview open Full screen of device. i wish camera preview open not Full screen.

Expected behaviour : camera preview open in ion-page. 
can i modify camera preview overlay ?
How to overlay button on camera preview of ion page?
I wish barcode scanner camera preview working like that Qr scanner camera preview plugins working. It's working in app. 

Advanced 
Thanks

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

If you believe that there is a problem with the plugin itself, please log an issue at the plugin's repo.

Thanks for using Ionic!
