### ISSUE TITLE
plugin_not_installed returned for health kit plugin which is installed.

### ISSUE THREAD

**Issue by CosmicWebServices** [ionic-team/ionic#13767]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The error plugin_not_installed is given for the health kit plugin which is installed which has at that point been used around 3 times.

**Expected behavior:**
That the code returns the weight from health kit

**Steps to reproduce:**
I run the code with `ionic cordova build ios`

**Related code:**
My code is wrapped in platform.ready() so I know that everything is loaded. I also have my health kit code that is throwing the error in a healthKit.available() and a healthKit.requestAuthorization which have no error.

```typescript
getWeight.then(function () {
    alert("Healthkit is ready!");
    alert(weight);
    healthKitReady = true;
 }).catch(function(err) {
     if (err) {
         console.log(err); // This is where the error is returned.
     }
  });
```

The function getWeight is this:

```typescript
const getWeight = new Promise(function(resolve, reject) {
    var error;
    healthKit.readWeight({
        unit: "lb"
    }).then(function (out) {
        weight = Math.round(out.value);
        alert("weight: " + weight);
        resolve(weight);
    }, function (err) {
        error = err;
        reject(error);
    });
});
```

**Other information:**

I made a slack overflow question also: https://stackoverflow.com/questions/48065114/why-am-i-getting-the-error-plugin-not-installed-with-the-ionic-framework-plugin

**Ionic info:** 

```
cli packages: (/usr/local/share/.config/yarn/global/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.2 
    Node       : v8.9.1
    npm        : 2.15.12 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by CosmicWebServices** [comment]
@kensodemann This seems like an ionic bug...

**Comment by kensodemann** [comment]
@CosmicWebServices - how so? I see zero Ionic Framework code above. This seems far more likely to be one of the following rather than an Ionic Framework issue:

- an issue with your code
- an issue with the plugin
- an issue with the ionic-native wrapper for the plugin
