### ISSUE TITLE
picker in ion-datetime doesn't have highlight

### ISSUE THREAD

**Issue by tarzanek** [ionic-team/ionic#13768]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Check ionic app conference About, click on datetime selector, the middle value won't have the "highlight"
(in browser on other than ios platform)

**Expected behavior:**

https://ionicframework.com/docs/api/components/datetime/DateTime/
shows it properly (since it forces ios scss files)

**Steps to reproduce:**

**Related code:**
https://github.com/ionic-team/ionic/blob/master/src/components/picker/picker.scss#L168
when I delete in browser the "display:none" inherited from here, the highlight works again

SO the fix:
IOS version has:
https://github.com/ionic-team/ionic/blob/master/src/components/picker/picker.ios.scss#L178

BUT
https://github.com/ionic-team/ionic/blob/master/src/components/picker/picker.md.scss#L181
LACKS it ... 

should I open a PR? Or will you be able to fix faster? (should be 2 lines of code that need to be added to md and wp scss files ... )

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by tarzanek** [comment]
alt. way to see(reproduce) is to run ionic conference app in lab and in about click the datetime for ios and android side by side ...

**Comment by tarzanek** [comment]
and similar for .picker-toolbar-button
and
.picker-toolbar-cancel
which also are in ios, but lack in md

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Just a heads-up that we probably will not be doing another release of Ionic v3. We are all working on the next major release of Ionic and Ionic for Angular (v4). If you could have a look at the `core` branch and let us know if you believe this has the same issue that would be helpful.

Thank you for using Ionic

**Comment by tarzanek** [comment]
if you meant https://github.com/ionic-team/ionic/tree/core/packages/core/src/components/picker
then yes, same problem in core, too ...

**Comment by tarzanek** [comment]
workaround is to put into your components (that uses ion-datetime) scss:
```
//workaround for https://github.com/ionic-team/ionic/issues/13768
.picker-above-highlight {
  display: block;
}
.picker-below-highlight {
  display: block;
}

.picker-toolbar-button {
  @include text-align(end);

  flex: 1;
}

.picker-toolbar-cancel {
  @include text-align(start);

  font-weight: normal;
}
```

**Comment by kensodemann** [comment]
@tarzanek - yeah, that is is one I was talking about...

**Comment by tarzanek** [comment]
so the prob is still there, but I am not a cross platform css expert, so I'll leave it up to you, the problem is nicely visible from --lab when comparing datetime between ios and md

**Comment by kensodemann** [comment]
Looking at the material design specs for a scrolling date picker: https://material.io/guidelines/components/pickers.html#pickers-date-pickers

We are following the guidelines on Android

Same if I look at a scrolling datepicker on a native iOS app.

I am going to close this as not a problem.

**Comment by tarzanek** [comment]
@kensodemann lol, what if there is an IF ?

e.g. in my case the picker which is in ionic if you use pickerFormat="DD MM YY HH mm"  looks completely like some crazy numbers spilled around whole screen without a simple way to see what is selected now ... (even though the middle number is a bit "highlighted" by a different colour)

does it still make sense to follow it and cripple usability, when for such type of picker ios guideline is much better and makes more sense?
(and I'd bet android engineers would adopt it for such use case without a blink, if they'd be made aware that their design needs a bit of improvement)

so I agree, this debate should probably moved to material design forums and I'd be curious if android is free to leverage ios design for better usability and out of box experience ...
(do you guys have a comm channel with them? would it make sense that they would revise for such case their designs?)

thnx
L
