### ISSUE TITLE
App automatic installation

### ISSUE THREAD

**Issue by zengyufang** [ionic-team/ionic#13760]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

Hi all，I have a requirement is: the need to automatically update the apk, at the moment, I only to installation interface, then requires the user to click on the install, to complete the installation, how can I do to skip the users click on the install steps?
The methods found on the Internet are native methods, and there is no way to solve this problem.
I hope you can provide me with a methods or provide a train of thought. Thank you

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

This also sounded like it could be related to Ionic Pro's Deploy feature, but that was not specified in the description so I am not sure. If so, please use the [Ionic Pro Support Portal](http://support.ionicjs.com) for Ionic Pro related questions and issue.

Thanks for using Ionic!
