### ISSUE TITLE
Zip native plugin not working in android

### ISSUE THREAD

**Issue by benson-jala** [ionic-team/ionic#13762]
every time I get the same message in android, ios it is working
I/chromium: [INFO:CONSOLE(1049)] "...............unzip process started....................", source: file:///android_asset/www/build/main.js (1049)
D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 1063 : [object Object]
I/chromium: [INFO:CONSOLE(1063)] "[object Object]", source: file:///android_asset/www/build/main.js (1063)
D/SystemWebChromeClient: file:///android_asset/www/build/vendor.js: Line 57499 : Native: tried calling Zip.unzip, but the Zip plugin is not installed.
I/chromium: [INFO:CONSOLE(57499)] "Native: tried calling Zip.unzip, but the Zip plugin is not installed.", source: file:///android_asset/www/build/vendor.js (57499)
D/SystemWebChromeClient: file:///android_asset/www/build/vendor.js: Line 57505 : Install the Zip plugin: 'ionic cordova plugin add cordova-plugin-zip'
I/chromium: [INFO:CONSOLE(57505)] "Install the Zip plugin: 'ionic cordova plugin add cordova-plugin-zip'", source: file:///android_asset/www/build/vendor.js (57505)
D/SystemWebChromeClient: file:///android_asset/www/build/vendor.js: Line 1703 : ERROR
I/chromium: [INFO:CONSOLE(1703)] "ERROR", source: file:///android_asset/www/build/vendor.js (1703)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

This may also be an issue with the plugin itself, in which case the issue should be logged with the plugin, not in the Ionic Framework repo.

Thanks for using Ionic!
