### ISSUE TITLE
the 'object' is not assigned to type 'any[]'  can u tell me the error in this.allMusic = musicList;

### ISSUE THREAD

**Issue by CsgeeksYoutube** [ionic-team/ionic#13775]
import { Component } from '@angular/core';
import { NavController ,LoadingController,ActionSheetController} from 'ionic-angular';
import { MusicsProvider } from '../../providers/musics/musics';
import { SocialSharing} from "@ionic-native/social-sharing";
import {MusicPlayerPage} from "../music-player/music-player";

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
	public allMusic =[];

  constructor(public navCtrl: NavController,
    private socalSharing: SocialSharing,
  	private actionSheetController: ActionSheetController,
  	public loadingController:LoadingController,
  	private musicProvider: MusicsProvider) {
  	

  }
  ionViewDidLoad(){
  	let allMusicLoadingController = this.loadingController.create({
  		content: "getting your songs from server"
  	});
  	allMusicLoadingController.present();

  	this.musicProvider.getMusic()
  		.subscribe((musicList) => {
  			allMusicLoadingController.dismiss();
  			this.allMusic = musicList;
  		});
  }
  shareSong(music){
  	let shareSongActionSheet = this.actionSheetController.create({
  		title:"Share song",
  		buttons:[
  		{
  			text:"Share on Facebook",
  			icon:"logo-facebook",
        handler:()=> {
          this.socalSharing.shareViaFacebook(music.name, music.image, music.music_url)
        }
        

  		},
  		{
  			text:"Twitter",
  			icon:"logo-twitter",
        handler:()=> {
          this.socalSharing.shareViaTwitter(music.name, music.image, music.music_url)
        }
  		},
  		{
  			text:"Share",
  			icon:"share",
        handler:()=> {
          this.socalSharing.share(music.name,"", music.image, music.music_url)
        }

  		},
  		{
  			text:"Cancel",
  			role:"destructive"
  		}

  		]
  	});
  	shareSongActionSheet.present();
  }
  goToMusic(music){
    this.navCtrl.push(MusicPlayerPage, {
      music: music
    });

  }

}

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
