### ISSUE TITLE
ion-select not contains output ionChange?

### ISSUE THREAD

**Issue by hiagodotme** [ionic-team/ionic#13778]
ion-select not contains output ionChange?

**Ionic version:**  (check one with "x")
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please. Thanks for using Ionic!
