### ISSUE TITLE
many ion-select will report  non-unique id #undefined

### ISSUE THREAD

**Issue by Merlin-Xu** [ionic-team/ionic#13779]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)

[ionic ] **3.x**

**I'm submitting a ...**  (check one with "x")
[1 ] bug report

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Create many ion-select . the button id of select  always is undefined.

Browser will print error log as below .
>  [DOM] Found 13 elements with non-unique id #undefined: (More info: https://goo.gl/9p2vKq) <button aria-haspopup=​"true" class=​"item-cover disable-hover item-cover-ios item-cover-default item-cover-default-ios" ion-button=​"item-cover" type=​"button" id=​"undefined" aria-disabled=​"false">​…​</button>​ <button aria-haspopup=​"true" class=​"item-cover disable-hover item-cover-ios item-cover-default item-cover-default-ios" ion-button=​"item-cover" type=​"button" id=​"undefined" aria-disabled=​"false">​…​</button>​ <button aria-haspopup=​"true" class=​"item-cover disable-hover item-cover-ios item-cover-default item-cover-default-ios" ion-button=​"item-cover" type=​"button" id=​"undefined" aria-disabled=​"false">​…​</button>​ <button aria-haspopup=​"true" class=​"item-cover disable-hover item-cover-ios item-cover-default item-cover-default-ios" ion-button=​"item-cover" type=​"button" id=​"undefined" aria-disabled=​"false">​…​</button>​ <button aria-haspopup=​"true" class=​"item-cover disable-hover item-cover-ios item-cover-default item-cover-default-ios" ion-button=​"item-cover" type=​"button" id=​"undefined" aria-disabled=​"false">​…​</button>​ <button aria-haspopup=​"true" class=​"item-cover disable-hover item-cover-ios item-cover-default item-cover-default-ios" ion-button=​"item-cover" type=​"button" id=​"undefined" aria-disabled=​"false">​…​</button>​ <button aria-haspopup=​"true" class=​"item-cover disable-hover item-cover-ios item-cover-default item-cover-default-ios" ion-button=​"item-cover" type=​"button" id=​"undefined" aria-disabled=​"false">​…​</button>​ <button aria-haspopup=​"true" class=​"item-cover disable-hover item-cover-ios item-cover-default item-cover-default-ios" ion-button=​"item-cover" type=​"button" id=​"undefined" aria-disabled=​"false">​…​</button>​ <button aria-haspopup=​"true" class=​"item-cover disable-hover item-cover-ios item-cover-default item-cover-default-ios" ion-button=​"item-cover" type=​"button" id=​"undefined" aria-disabled=​"false">​…​</button>​ <button aria-haspopup=​"true" class=​"item-cover disable-hover item-cover-ios item-cover-default item-cover-default-ios" ion-button=​"item-cover" type=​"button" id=​"undefined" aria-disabled=​"false">​…​</button>​ <button aria-haspopup=​"true" class=​"item-cover disable-hover item-cover-ios item-cover-default item-cover-default-ios" ion-button=​"item-cover" type=​"button" id=​"undefined" aria-disabled=​"false">​…​</button>​ <button aria-haspopup=​"true" class=​"item-cover disable-hover item-cover-ios item-cover-default item-cover-default-ios" ion-button=​"item-cover" type=​"button" id=​"undefined" aria-disabled=​"false">​…​</button>​ <button aria-haspopup=​"true" class=​"item-cover disable-hover item-cover-ios item-cover-default item-cover-default-ios" ion-button=​"item-cover" type=​"button" id=​"undefined" aria-disabled=​"false">​…​</button>​
> **Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
<ion-select cancelText="{{'USER_MANAGE.LABEL.CANCEL' | translate }}" interface="popover" class="width100 bg-light-gray border-radius5" formControlName="functionCode" placeholder="{{ 'USER_MANAGE.LABEL.FUNC' | translate }}" [id]="id+'func'">
                            <ion-option *ngFor="let opt of funcs" (ionSelect)="selectFunc(opt,i)" [value]="opt.functionCode">{{opt.functionName}}</ion-option>
                        </ion-select>
<ion-select cancelText="{{'USER_MANAGE.LABEL.CANCEL' | translate }}" interface="popover" class="width100 bg-light-gray border-radius5" formControlName="functionCode" placeholder="{{ 'USER_MANAGE.LABEL.FUNC' | translate }}" [id]="id+'func'">
                            <ion-option *ngFor="let opt of funcs" (ionSelect)="selectFunc(opt,i)" [value]="opt.functionCode">{{opt.functionName}}</ion-option>
                        </ion-select>
<ion-select cancelText="{{'USER_MANAGE.LABEL.CANCEL' | translate }}" interface="popover" class="width100 bg-light-gray border-radius5" formControlName="functionCode" placeholder="{{ 'USER_MANAGE.LABEL.FUNC' | translate }}" [id]="id+'func'">
                            <ion-option *ngFor="let opt of funcs" (ionSelect)="selectFunc(opt,i)" [value]="opt.functionCode">{{opt.functionName}}</ion-option>
                        </ion-select>
<ion-select cancelText="{{'USER_MANAGE.LABEL.CANCEL' | translate }}" interface="popover" class="width100 bg-light-gray border-radius5" formControlName="functionCode" placeholder="{{ 'USER_MANAGE.LABEL.FUNC' | translate }}" [id]="id+'func'">
                            <ion-option *ngFor="let opt of funcs" (ionSelect)="selectFunc(opt,i)" [value]="opt.functionCode">{{opt.functionName}}</ion-option>
                        </ion-select>
<ion-select cancelText="{{'USER_MANAGE.LABEL.CANCEL' | translate }}" interface="popover" class="width100 bg-light-gray border-radius5" formControlName="functionCode" placeholder="{{ 'USER_MANAGE.LABEL.FUNC' | translate }}" [id]="id+'func'">
                            <ion-option *ngFor="let opt of funcs" (ionSelect)="selectFunc(opt,i)" [value]="opt.functionCode">{{opt.functionName}}</ion-option>
                        </ion-select>
<ion-select cancelText="{{'USER_MANAGE.LABEL.CANCEL' | translate }}" interface="popover" class="width100 bg-light-gray border-radius5" formControlName="functionCode" placeholder="{{ 'USER_MANAGE.LABEL.FUNC' | translate }}" [id]="id+'func'">
                            <ion-option *ngFor="let opt of funcs" (ionSelect)="selectFunc(opt,i)" [value]="opt.functionCode">{{opt.functionName}}</ion-option>
                        </ion-select>
```

**Other information:**

**Comment by jeanpfs** [comment]
This bug happened to me also with an opinion and has a password type field

**Comment by 7freaks-otte** [comment]
This just seems to happen if ion-select is not used inside an ion-item and might be resolved if BaseInput (util/base-input) would initialize id with null. (Sorry no time to test)
Also this was always present though unnoticed until Chrome decided to throw an error on duplicate ids (which is technically correct).
