### ISSUE TITLE
Allow changing default component texts globally 

### ISSUE THREAD

**Issue by tricki** [ionic-team/ionic#13786]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
Currently translations for default components (for example `cancelText` and `okText` in the [Select component](https://ionicframework.com/docs/api/components/select/Select/#input-properties)) have to be provided on each use.

**Expected behavior:**
We should have the ability to add the default texts to the config parameters (just like `backButtonText`) while still allowing the texts to be replaced on every instance.

**Other information:**
https://forum.ionicframework.com/t/allow-changing-default-component-texts-globally/115042
https://forum.ionicframework.com/t/how-to-globally-set-ionic-components-buttons-translations/111554/4
https://stackoverflow.com/questions/47200427/how-to-globally-set-ionic-components-buttons-translation

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (npm/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.1.4
    npm               : 5.4.2
    OS                : Windows 10

Misc:

    backend : pro```

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#344

**Comment by tricki** [comment]
That **internal** list makes it impossible to figure out the (evaluation) status/priority/details of a feature request. I can't even see if/how often it was requested before. It also prevents non-Ionic developers from participating in the discussion.
I'm especially confused since this repo's contribution guidelines say:

> We appreciate you taking the time to contribute! Before submitting a pull request, we ask that you please create an issue that explains the bug or feature request and let us know that you plan on creating a pull request for it.

Since this feature would most likely include changes in the core config, the Ionic team would probably have to check for name collisions etc. 
Where is the correct place to discuss implementation details of a requested feature? Is the idea that I'll just make the changes in a fork and hope that you'll accept it? And what about related non-code changes (e.g. Docs)? 

I guess for now the quickest way is to just create my own components with this feature (or continue adding the texts in every instance). But I'd prefer a cleaner solution with a pull request.

**Comment by kensodemann** [comment]
@tricki - you are correct about the private repo making things difficult. We are evaluating how this will be handled in the future.

I would not suggest doing a pull request at this time as it is _highly_ unlikely that there will be another release of Ionic for v3, and if there was it would just contain fixes for fatal bugs, not any new features.

My suggestion is to wait until v4 is released and revisit this issue at that time. That would probably be the most productive solution at this point given the team's current focus, which is getting the base functionality for the next major Ionic release solidified. All feature requests are essentially "on hold" until that is accomplished.

If you want to plan for what you might be able to do in the future to contribute a PR on this, please have a look at the `core` branch. That is the branch that will eventually become `master`

**Comment by tricki** [comment]
@kensodemann - thanks for the clarification, I didn't consider the impact of v4. Looking forward to it.
