### ISSUE TITLE
Iframe crashes on ionic v1 IOS

### ISSUE THREAD

**Issue by brwa88** [ionic-team/ionic#13781]
Hello i build a mobile app with ionic v1 and in my app i needed iframe i had no issue with android ,
But when i deploy my app on an ios device sometimes my app crashes the iframe stuck and crash ,
Please help. 

Best regards
Brwa

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
