### ISSUE TITLE
ion-select validation error not showing

### ISSUE THREAD

**Issue by ferozsho** [ionic-team/ionic#13780]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
When ion-select set to 'none' the red border bottom not showing

<img src="http://intellibiz.in/github-images/error.png" alt="error">

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\feroz\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.3
    npm               : 5.6.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : D:\Android\sdk

Misc:

    backend : pro
```

**Comment by ferozsho** [comment]
Hi Team,
Anyone there, to resolve this issue ???

**Comment by ferozsho** [comment]
hi,
Please review @kensodemann 
[https://github.com/ionic-team/ionic/issues/12345](url)

Still no update on this???

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Given the current focus on getting the next major release completed, you are unlikely to see any resolution to this issue until after that release is complete.

Thank you for using Ionic

**Comment by ferozsho** [comment]
Thanks for your response,
i manage to highlight the bottom border using 
```  
ctrlIsValid(formGroup: FormGroup, ctrlName: string) {
    let shadesEl = document.querySelector('[formControlName="' + ctrlName + '"]').parentElement.parentElement.parentElement;
    const control = formGroup.get(ctrlName);
    if (control.errors != null) {
      shadesEl.classList.remove('ng-untouched');
      shadesEl.classList.add('ng-invalid', 'ng-touched', 'ng-dirty');
    } else {
      shadesEl.classList.remove('ng-dirty', 'ng-invalid');
    }
  }
```
## in scss
```
.item-md.item-select.ng-invalid.ng-touched:not(.input-has-focus):not(.item-input-has-focus) .item-inner {
    border-bottom-color: #f53d3d;
    -webkit-box-shadow: inset 0 -1px 0 0 #f53d3d;
    box-shadow: inset 0 -1px 0 0 #f53d3d;
  }

  .list-md .item-select.ng-invalid.ng-touched:not(.input-has-focus):not(.item-input-has-focus):last-child {
    border-bottom-color: #f53d3d;
    -webkit-box-shadow: inset 0 -1px 0 0 #f53d3d;
    box-shadow: inset 0 -1px 0 0 #f53d3d;
  }

```

But I would like an proper method to resolve.
Please Advice

**Comment by kensodemann** [comment]
> But I would like an proper method to resolve.

There have been a lot of changes with the way this works in `@ionic/core` and the upcoming v4 release. My suggestion is to re-test this after that release, and it if is still a problem to create a new issue at that time as it is clearly something that should be fixed in the framework.

I am going to close _this_ issue based on the fact that you have a workaround in place for v3.
