### ISSUE TITLE
scrolling issue when keyboard is open

### ISSUE THREAD

**Issue by najilouis** [ionic-team/ionic#13788]
When keyboard is open in a form a padding-bottom is getting added to .scroll-content (eg: padding-bottom: 300px) so user can keep scrolling even after reaching the bottom of the form
![26772718_10159715508555577_20375930_o](https://user-images.githubusercontent.com/25154477/34694262-1af98f18-f4cf-11e7-8aa7-b1dc0098fdce.jpg)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Ionic info:**

```
cli packages: 

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 6.4.0 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.1
    Node              : v9.3.0
    npm               : 5.6.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b
```

**Comment by jeffminsungkim** [comment]
I'm having the same issue.

**Comment by followfire** [comment]
Have you solved this problem? I have the same problem, and have no idea how to resolve it.Many thanks if u have any solution.

**Comment by najilouis** [comment]
I did a workaround by override it to 0
```
.scroll-content{
    padding-bottom: 0 !important;
}
``` 
hope this can you
