### ISSUE TITLE
ion-infinite-scroll threshold

### ISSUE THREAD

**Issue by michalsindler** [ionic-team/ionic#13782]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
Ion-infinite-scroll does not fire event on threshold where is expected - if I set threshold 50%, event is firing very near of the end of scroll content.

**Expected behavior:**
Ion-infinite-scroll should fire event at percentage position in scroll content.

**Steps to reproduce:**
Set 50% in threshold attribute in ion-infinite-scroll, run app and scroll down to middle of content and event is not firing - no matter what number of percent is inserted, event is firing near end of whole list.
After some searching I think I found what is wrong in your source code - will demonstrate it below.

**Related code:**
```
Original code in infinite-scroll.js:
var threshold = this._thrPc ? (height * this._thrPc) : this._thrPx;

I think that "height" (which has value from "d.contentHeight") should be changed to "d.scrollHeight", because "d.contentHeight" is just a visible part of whole list, so computed threshold is very small number of pixels.

I changed this code to this (and it works much better):
var threshold = this._thrPc ? (d.scrollHeight * this._thrPc) : this._thrPx;
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/home/michal/Sources/ECHOapp/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.1.2
    npm               : 5.3.0 
    OS                : Linux 4.10

Environment Variables:

    ANDROID_HOME : /home/michal/Android/Sdk

Misc:

    backend : pro
```

**Comment by marianoo-andres** [comment]
#12891

**Comment by Bengejd** [comment]
Thanks for this. Staring, and hoping a PR can come from this eventually.

**Comment by dertuerke** [comment]
+1
