### ISSUE TITLE
ion-textarea should be improved

### ISSUE THREAD

**Issue by Andionic** [ionic-team/ionic#13795]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

Wish to have an easy way to config ion-textarea:
a) attribute(s) to set an initial height and
b) attribute to set a flexible height (textarea grows automatically on every new line input)

In the community forum there are workarounds, I know. But in comparison to quality of all other components ion-textarea should be improved!

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#345
