### ISSUE TITLE
 Failed to deploy to device, no devices found when it's connected 

### ISSUE THREAD

**Issue by Genarito** [ionic-team/ionic#13798]
**Ionic version:**
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**JDK version:**
[x ] **1.8.0_151**

**I'm submitting a ...**
[x ] bug report
[ ] feature request

**Current behavior:**
"Failed to deploy to device, no devices found" appears randomly when device is connected correctly.
Note: I can access my device's files normally from computer when error occurs.

**Expected behavior:**
Run on device normally.

**Steps to reproduce:**

Connect the device, run with --device flag activated, sometimes it works, and sometimes doesn't.
Re plug doesn't work, but restart the computer does.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
