### ISSUE TITLE
ionic cordova plugin add cordova-plugin-file-transfer Failure

### ISSUE THREAD

**Issue by LiamInJapan** [ionic-team/ionic#13791]
**Ionic version:** 
3.10.3

**Cordova Version:**
8.0.0

**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
ionic cordova plugin add cordova-plugin-file-transfer fails with the following output:

`
> cordova plugin add cordova-plugin-file-transfer --save
✔ Running command - done!
Installing "cordova-plugin-file-transfer" for browser
Failed to install 'cordova-plugin-file-transfer': CordovaError: Version of installed plugin: "cordova-plugin-file@4.3.3" does not satisfy dependency plugin requirement "cordova-plugin-file@^5.0.0". Try --force to use installed plugin as dependency.
    at /Users/liam/.nvm/versions/node/v6.9.4/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:557:37
    at _fulfilled (/Users/liam/.nvm/versions/node/v6.9.4/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/liam/.nvm/versions/node/v6.9.4/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/liam/.nvm/versions/node/v6.9.4/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /Users/liam/.nvm/versions/node/v6.9.4/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:509:49
    at flush (/Users/liam/.nvm/versions/node/v6.9.4/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

Thus in turn the following fail:
ionic cordova run ios
ionic cordova run browser
ionic cordova run android

**Expected behavior:**
The required plugin should install and everything should run

**Steps to reproduce:**
run the command, with the specified environment

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/liam/Development/Web/ionic/dwango-gemaga-original/node_modules)

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

global packages:

    Cordova CLI : 8.0.0 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.2
    ios-sim           : 6.1.2 
    Node              : v6.9.4
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question or perhaps an issue with the plug-in itself I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/) or to open an issue with the author of the plugin or with 
https://github.com/ionic-team/ionic-native

Thanks for using Ionic!
