### ISSUE TITLE
setRoot Tabs is not working, with option (tabsHideOnSubPages: true)

### ISSUE THREAD

**Issue by bossjon** [ionic-team/ionic#13794]
I set option (tabsHideOnSubPages: true) and navigation is not working, when i change navigation on SubPage.

for example, i clone ionic-conference-app and set option (tabsHideOnSubPages: true). When i open sessionDetail page and navigation from side menu is not working.

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please. Please include a sample application that we can use to duplicate the issue.

Thanks for using Ionic!
