### ISSUE TITLE
Attach Audio files from IOS for upload to firebase using Ionic3

### ISSUE THREAD

**Issue by touqeeraslam** [ionic-team/ionic#13790]
Can anyone please guide me how to upload audio files in ionic app from ios 

I am using simple input type="file"
in case of android it is working fine when the file chooser is clicked it is navigated to file manager and shows audio files and images and videos but in case of IOS it show only photo library containing images and videos but in my case i want to upload audio from IOS .
can you please guide me how to attach audio from IOS using ionic app.

**Comment by astec** [comment]
You better ask support questions either at https://forum.ionicframework.com/ or https://stackoverflow.com/questions/tagged/ionic3

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
