### ISSUE TITLE
Transpiler tries to find templateUrl that is listed in a comment

### ISSUE THREAD

**Issue by oldfool** [ionic-team/ionic#13807]
**Ionic version: 3.x**

**I'm submitting a bug report**

**Current behavior:**
The transpiler sees an at-decorator in a comment and tries to process it.

**Expected behavior:**
The transpiler ignores the comment and builds the project normally.

**Steps to reproduce:**
1. Create a new Ionic project from the command line: `ionic start comment-bug blank`
2. Add this comment into the *home.ts* module:
```
/**
 * @Component({
 *   templateUrl: 'sample.html'
 * })
 */
```
3. Compile and run: `ionic serve`
4. Transpile error:
```
transpile started ... 
template error, "/path/to/project/comment-bug/src/pages/home/sample.html": Error: 
            ENOENT: no such file or directory, open 
            '/path/to/project/comment-bug/src/pages/home/sample.html' 
transpile finished in 1.70 s 
```
In the developer console, the following is displayed:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
Unhandled Promise rejection: Failed to load home.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load home.html 
```

**Other information:**
1. So far, I've only found this bug when using the Component at-decorator.
1. The bug manifests itself even if you leave off the at-sign; however, if you use a lower-case "component", the comment is correctly ignored.
1. The same bug occurs when using `//` commenting style.

**Ionic info:**
```
cli packages: (/path/to/project/comment-bug/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

local packages:

    @ionic/app-scripts : 3.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.2.1
    npm  : 5.3.0 
    OS   : macOS Sierra

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this is an [Ionic app-scripts](https://github.com/ionic-team/ionic-app-scripts) but, I am going to close this issue.

Given the work that is currently being done, I suggest waiting to see if this is still an issue after the next major release of Ionic, which will involve a lot of changes to the Ionic CLI and build tooling and that if it is still an issue at that point to open a new issue.

Thanks for using Ionic!
