### ISSUE TITLE
Data entered lost if navigate away from page then use [navPush] to navigate back

### ISSUE THREAD

**Issue by tnguyen-lh** [ionic-team/ionic#13809]
Ionic version 3.19.0

In ionic 1 we have a handy cache-view="true", if I have a view with cache, everytime I navigate to it, it present the last state I was in. With ionic 3, NavController does not provide cache-view, every time I use [navPush]="destinationPage", it insert a new page with new state into the nav stack, with all data entered lost. Is there anyway to add cache-view to future ionic?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
