### ISSUE TITLE
Back button pushes title to the right on ios (not screen centered anymore)

### ISSUE THREAD

**Issue by warri93** [ionic-team/ionic#13802]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
When pushing a page on the root, the back button is added to the header bar. Unfortunately the back button pushes the ion-title to the right. Therefore the placement of the title is different on the subpage than when on the root. It's +- 20px more to the right. 

This is because when there are no buttons, or in my case, when there are ion-buttons (start and end) in the header bar on the root page, the title is still taking the full width (100%). When the back button is added the title is only taking the space it has (minus the space the back button is taking). Because of this the title is placed more to the right on subpages.

**Expected behavior:**
When the back button is added, the title should still be placed in the middle of the screen instead of the space it has because of the back button.

**Steps to reproduce:**
Add a subpage
Push the subpage on the rootpage with the navController
Back button is shown on the screen now
==> title is placed more to the right than it was on the root page

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    @ionic/cli-utils  : 1.17.0
    ionic (Ionic CLI) : 3.17.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1 
    ios-sim           : 4.1.1 
    Node              : v9.3.0
    npm               : 5.5.1 
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/melissawarrens/Library/Android/sdk

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
I am going to close this as something that I cannot duplicate.

If you can provide a sample application via GitHub that duplicates this issue I will be happy to reopen the issue and have a look.

The following are with no modification to the standard Ionic styling. If you are making modifications to the styling make sure that your styling changes are not contributing to your issue.

Here is my parent page:
<img width="388" alt="screen shot 2018-01-16 at 5 29 57 am" src="https://user-images.githubusercontent.com/1526846/34986842-b96794d8-fa7e-11e7-8a90-a7014a4c8504.png">

Here is my child page:
<img width="410" alt="screen shot 2018-01-16 at 5 31 25 am" src="https://user-images.githubusercontent.com/1526846/34986843-b977126e-fa7e-11e7-905e-c63d49698539.png">

The title is centered in each.

**Comment by warri93** [comment]
It appears to only happen when I have the header bar in a reusable component.
