### ISSUE TITLE
All 3.9x Ionic apps doesnt work on android 5.x anymore

### ISSUE THREAD

**Issue by ralph-fuechtenkort** [ionic-team/ionic#13805]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After upgrading one app to angular5 ionic 3.9.0 it show the error: 
Uncaught SyntaxError: Unexpected token ILLEGAL 
pointing to a line in main.js: 
Object(__WEBPACK_IMPORTED_MODULE_0__angular_core__["m" /* Component */])({template:/*ion-inline-start:"/projects/learning/test50/src/pages/tabs/tabs.html"*/`<ion-tabs>\n <ion-tab [root]="tab1Root" t..........
I initiated a clean tabs app and the issue is actually the same.

**Expected behavior:**
should work on android 5.1

**Steps to reproduce:**
create a new app, try to run it on and android 5.x device

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
I am going to close this as something that I cannot duplicate.

If you can provide a sample application via GitHub that duplicates this issue I will be happy to reopen the issue and have a look.

**Comment by ralph-fuechtenkort** [comment]
Hi,
here is the GitHub
https://github.com/ralph-fuechtenkort/test50.git
Its basically a empty project based on the tab template.
It works on serve and phones with android 6.x > but not on Android 5x devices.

**Comment by kensodemann** [comment]
Thank-you. I will have a look.

**Comment by kensodemann** [comment]
```
  "devDependencies": {
    "@ionic/app-scripts": "3.1.0",
    "typescript": "2.4.2"
  },
```

When I upgraded `@ionic/app-scripts` from `3.1.0` to `3.1.7` your app worked perfectly. Give that a try and let me know how that works for you.
