### ISSUE TITLE
How to get User Network OR GPS Location time in Ionic 3?

### ISSUE THREAD

**Issue by kalimulhaq** [ionic-team/ionic#13804]
I'm working on Multi Players Game and Ionic 3, In which time accuracy is very important so I can't rely on user device time. The user can easily change the device time and can hack the game. So I want to get the user network or GPS location time.

Does anybody know how to get the User Location Time or Device Network time in Ionic 3?

I can't use `new Date();` it gives me devise time it can be wrong.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by alejox21** [comment]
https://forum.ionicframework.com/t/how-to-prevent-time-cheat/117116
may this post help you
