### ISSUE TITLE
Tab select pushes view onto navstack ?

### ISSUE THREAD

**Issue by RHinderiks** [ionic-team/ionic#13806]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When navigating to a tab page we use this.tabRef.select(defaultTabIndex) to set different default tabs for different users, i.e. some users need to start in tab 1, some need to start in tab 3. However using this.tabRef.select() causes a back button to appear (only on the selected tab) pressing it keeps reloading itself. on android this behaviour when pressing the hardware back button and on both ios and android swiping right to left also triggers a navigate back to the same tab. This leads me to believe the tab is put on a nav stack as some weird bug.

**Expected behavior:**
No back functionality on the tab pages

**Steps to reproduce:**
Using this.tabRef.select(defaultTabIndex) to set a tab

**Other information:**
This happened after updating to the latest angular, ionic etc.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages: (/usr/local/Cellar/node@6/6.10.0_1/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.0.0 
    Node              : v6.10.0
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/robinhinderiks/Library/Android/sdk

Misc:

    backend : legacy

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a minimal sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by RHinderiks** [comment]
@kensodemann Created a new project and recreated the situation but it works as expected. Thought it may be related to lazy loading but also implementing that it still worked fine. So it's probably an issue on my side. It's just a bit weird it worked fine before updating ionic and angular and libraries
