### ISSUE TITLE
will ionic-slides ionSlideDidChange event and call a method ?

### ISSUE THREAD

**Issue by Piraban** [ionic-team/ionic#13811]
My requirement is that have to show multiple charts dynamically. [[This is actual Ques](https://stackoverflow.com/questions/48209894/ionic-create-multiple-charts-with-dynamic-data)]

Since I didn't get any solution, I thought to render in slide <ion-slides (ionSlideDidChange)="methodname">, here also problem method is not triger/called

Angular Cor : 4.4.3
Ionic framework 3.7.1
Node 9.2

Please suggest me, ionic will support slide change event? I have spent 3 more days to get solutions

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
