### ISSUE TITLE
self-signed ssl certificate not being blocked when deployed to Android.

### ISSUE THREAD

**Issue by mrcl** [ionic-team/ionic#13818]
I noticed that my app, when deployed to android is accepting self-signed certificates in the server.

To help with the issue I created a snapshot of what I am doing on StackBlitz as recommended.

https://stackblitz.com/edit/ionic-login-test

I added the cordova android platform and then run

ionic cordova run android --prod

I then set a local development server using django and set a self-signed ssl certificate managed by nginx, which is listening on https://192.168.0.10/

When I access the phone for debugging on Chrome, I can see the the Login occurs successfully.
I would expect to see an error and be sure that the data was not sent to the server, as it could not be verified.

What I would expect is a result
    `Response with status: 0  for URL: null`
and a 
    `Failed to load resource: net::ERR_INSECURE_RESPONSE`
at the console.

But instead I am getting the error from the server of a failed login.

I am running everything on Arch Linux.

**Comment by ghenry22** [comment]
Android builds require an extra flag to build in release mode versus dev.

`--prod` only builds the javascript part in production mode

you need` --release` as well to build a release bundle for android.  You will also then have to sign the built apk before it can be tested.

then you will see invalid and self signed certificates blocked.

**Comment by mrcl** [comment]
Brilliant @ghenry22!!!! That was not clear to me. Thanks for explaining!
Now the requested is not passed anymore, but because I am running with the `--release` flag I can't access the console anymore to see the error. I can verify that it fails though, as expected.

Maybe this behaviour could receive a note at the documentation. So other users could find it more easily.

Cheers

**Comment by mburger81** [comment]
`self-signed ssl certificate` doesn't matter anything with `--release` flag.

**Comment by ghenry22** [comment]
Yes it does as debug builds allow connection to invalid and self signed ask whereas production builds will block these.

**Comment by mburger81** [comment]
sorry, I misunderstood the issue. Yes naturally a `release` bundle doesn't accept `self signed certificate`!!! 
Was confused ;) thx

BTW, there are ways to get it work also on release bundles.
