### ISSUE TITLE
iframe Redirect  problem  in ionic，App crash and restart.

### ISSUE THREAD

**Issue by bigthing33** [ionic-team/ionic#13812]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ x] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
- App  crash and restart

**Expected behavior:**

- Back to the previous page

**Steps to reproduce:**

- ionic serve
- Go to a new page, this page has a ifram with loaded "https://getvobot.com/faq"
-  In the iframe, there is a button. when you click on the button, this iframe will redirect to  another URL  "https://getvobot.com/faq?keywords=h"
- Click back button in ionic navbar
- Then the App will return to the previous page，**crash and restart**

**Related code:**

```
  <iframe id="iframe" class="iframe"
          sandbox="allow-presentation allow-scripts allow-top-navigation allow-pointer-lock allow-same-origin allow-popups allow-forms"
          [src]="helpUrl|safe"
          (load)="loaded()">
  </iframe>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 6.0.0

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 5.1.1, browser 4.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.3
    Node              : v6.11.0
    npm               : 3.10.10
    OS                : Windows 7
```

**Comment by alquifran** [comment]
I had this problem too. If you return the iframe to its original state (right click inside the iframe -> back) there is no problem and the app doesn't crash. As a workaround, you can try to use window.history.back() (the amount of times you have navigated inside the iframe) to prevent the crash, but I would like an official answer or solution to the problem you describe.

**Comment by bigthing33** [comment]
@alquifran  Thank you for your answer.
I have followed your instruction, but now I have a new problem when I ran the code:
```
  @ViewChild(Navbar) navBar: Navbar;
  @ViewChild('iframe') iframe: ElementRef
  ionViewDidLoad() {
    console.log('ionViewDidLoad HelpPage');
    this.navBar.backButtonClick = (e: UIEvent) => {
      // this.iframe.nativeElement.contentWindow.history.back();
      this.iframe.nativeElement.contentWindow.history.go(-(this.iframe.nativeElement.contentWindow.history - 1));
      console.log('backButtonClick', e);
      this.navCtrl.pop();
    }
  }
```
 The App crashes, and the error log is 
```
ERROR DOMException: Blocked a frame with origin "http://localhost:8100" from accessing a cross-origin frame.
```
Any idea about it?

**Comment by alquifran** [comment]
Try with just window.history.back(), what happened to you has to do with Cross Origin Security: https://stackoverflow.com/questions/25592186/using-javascript-to-control-navigation-of-iframe-not-applying-src-property

Other than that, I'm pretty lost with this too

**Comment by bigthing33** [comment]
@alquifran Thank you very much. It helps me a lot. 
It works for me.
```
  ionViewDidLoad() {
    console.log('ionViewDidLoad HelpPage');
    this.navBar.backButtonClick = (e: UIEvent) => {
      window.history.go(-(window.history.length - 1));
      console.log('backButtonClick', e);
      this.navCtrl.pop();
    }
  }
```

**Comment by ywcsz** [comment]
i have the same problem,how to do?

**Comment by ywcsz** [comment]
i userd tabs page,history,back() will no tab part,so i can not workaroud it

**Comment by FdezRomero** [comment]
Hi @bigthing33! Is this problem still an issue? (I'm volunteering to triage issues) Thanks!

**Comment by ywcsz** [comment]
@FdezRomero Thank you for your attention and tracking。the problem still an issue

**Comment by bigthing33** [comment]
The problem still persists, and I finally used InAppBrowser instead of iframe. @FdezRomero

**Comment by FdezRomero** [comment]
@ywcsz @bigthing33 Thanks for confirming! I looked a bit into it and I hope that the navigation/routing improvements being made in v4 will solve this.

**Comment by windwp** [comment]
i have same issue.
My solution is call popToRoot() before you go to frame page.
```
this.navCtrl.popToRoot({ animate: false });
 this.navCtrl.push("framepage");
```
use this code if you want to get back to a previous page.
`  ionViewDidLoad() {
    this.navBar.backButtonClick = () => this.navCtrl.pop({ animate: false });
  }
  ionViewWillLeave() {
    // https://github.com/ionic-team/ionic/issues/13812
      if (this.listPages) this.navCtrl.insertPages(1, this.listPages, { animate: false });
  }`

**Comment by joesleiman** [comment]
i have same problem but the iframe is with flipping book  when i use window.history.back() the page of the book back 1 page from first click, second click not do anything, third click back one page, fourth nothing etc....so how can i let the back button return completely from the page that have the iframe not the page of the book. thanks
