### ISSUE TITLE
When I enter the Tabs => List => List-detail, The browser returns the error.

### ISSUE THREAD

**Issue by xiechunyan** [ionic-team/ionic#13820]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I use ionic start test and choose tabs , and navigate with IonicPage. The tabs contains three items: home, content and setting
When I enter the setting => setting-list => list-detail, The browser returns the error.The error message is as follows：
ERROR Error: Uncaught (in promise): removeView was not found

When I enter http://localhost:8100/#/tabs/setting/detail/001 link directly.The application link is automatically replaced with http://localhost:8100/#/tabs/home/setting and the page displays the setting page content.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!
