### ISSUE TITLE
How to use ionSelect attribute

### ISSUE THREAD

**Issue by pratik906** [ionic-team/ionic#13822]
Hi team,
I am not sure if this issue has been already resolved but I am new to ionic and I have tried all my possible sources to get the issue solved but unable to do so.

I have a select component in my code and I want to check its value after user has selected the one of the options. As far as I know the only way to do it is using ionSelect component but how should I use it ?

This is my html page:
![capture](https://user-images.githubusercontent.com/28717794/34921715-edd3ca74-f953-11e7-86c1-fba44795b015.JPG)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
