### ISSUE TITLE
Ionic serve error for sass

### ISSUE THREAD

**Issue by noor07** [ionic-team/ionic#13829]
I am getting a error like :- 
Error in plugin 'sass'
Message:
    scss\ionic.app.scss
Error: File to import not found or unreadable: ../www/lib/ionic/scss/*.scss.
       Parent style sheet: E:/BackUP(KathaApp)/myapp/scss/ionic.app.scss
        on line 5 of scss/ionic.app.scss
>> @import "../www/lib/ionic/scss/*.scss";

please help.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
