### ISSUE TITLE
how to set clearInput and icon on alertController input?

### ISSUE THREAD

**Issue by se7enmfk** [ionic-team/ionic#13827]
<ion-input clearInput type="password" formControlName="password" maxLength='16'></ion-input>
    <ion-icon name="{{showPass?'eye':'eye-off'}}" color="light"></ion-icon>

     this.alertCtrl.create({
      title: title,
      inputs: [
      {
        type: 'password',
        name: 'password',
        placeholder: 'password',
        checked: false
      }],
      buttons: [
        {
          text: 'Cancel',
          role: 'cancel',
          handler: (data: any) => {
            cancelCallBack(data);
            return true;
          }
        },
        {
          text: 'Save',
          handler: (data: any) => {
            successCallBack(data);
            return true;
          }
        }
      ]
    });
    alert._setIONContent
    alert.present();

how to set clearInput and icon on alertController input?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
