### ISSUE TITLE
ion-list missing bulk delete functionality present in ionic v1.x

### ISSUE THREAD

**Issue by jwt02180** [ionic-team/ionic#13826]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ X ] feature request

**Current behavior:**
I remember from ionic v1.x that you could toggle a bulk delete UI in an `<ion-list>`  and it was very handy since it mirrored similar functionality to the native mail app in iOS for example. After looking through the documentation for ionic v3.x I could not find anything like this.

**Expected behavior:**
An option on the `<ion-list>` to facilitate some "bulk select" UI on the `<ion-item>`'s. You could toggle/perform some action *(eg. remove items from list)* via a button in a toolbar for example

**Steps to reproduce:**
If you look at the v1 documentation for [ionList](https://ionicframework.com/docs/v1/api/directive/ionList/) the example demonstrates the missing functionality I've described.

**Other information:**
I'm sure you guys are busy enough working on ionic v4 and all the other great projects you've announced recently. I'd really like to see this added to the roadmap for some point in the future though as I think this was a nice feature to have.

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#348
