### ISSUE TITLE
Feature Request - SDK Integration

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic#13837]
Hello Ionic team,

Is it possible for you guys to integrate some of the popular high-end SDK packages into Capacitor (avocado), ideally with typescript command interface to trigger their functions?

While studying Java & XML development, I found amazing SDKs for Android and iOS. They're much better than cordova plugins and are 100% open source.

http://www.superpowered.com/

https://www.mapbox.com

I think there are quite many of these open source SDKs are out there.  If Capacitor offers these SDKs like plugins or ships them built-in, it would be really great. Currently, only native Java, objective C developers can use them. 

They have maintenance.. there are active developers behind these SDK packages & they seem more professional.

Thanks,

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to close this as it is not related to the Ionic Framework and is thus off-topic for this issues list. Max has been made aware of your request.

Thank you for using Ionic
