### ISSUE TITLE
Feature Request: Tablet styling

### ISSUE THREAD

**Issue by shaneparsons** [ionic-team/ionic#13833]
**Ionic version:**
[x] **2.x**
[x] **3.x**
[x] **4.x**

**I'm submitting a ...**
[ ] bug report
[x] feature request

**Current behavior:**
By default, Ionic apps and components tend to look either small or stretched on tablets as there doesn't seem to be much in terms of default styling to set it apart from phone styling. I feel that things like text, lists, buttons etc... should ideally have some increases on tablet sizes to make the most of the big screens and make it look more "designed for tablets" rather than "compatible with tablets".

Of course style tweaks could be added by the user, but the way the default variables are set up make it more difficult than it should be, and to have to do it on every project seems redundant.

**Expected behavior:**
Some default styling changes / considerations for tablets.

**Steps to reproduce:**
Take any of your apps, or create a temporary conference app, serve the app, and view it in the developer / device inspector of Chrome or Safari in an iPad or Android tablet layout. Notice how everything looks like it should be bumped up a bit.

Note: the conference app uses the permanent menu on the left on tablet sizes, which makes it look a lot more "designed for tablets"... but apps that don't have a side menu don't really have that option.

**Other information:**
I realize this request is fairly subjective, but I hope that you can see or understand my point of view.

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#346

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#347
