### ISSUE TITLE
Problem with navigations

### ISSUE THREAD

**Issue by Gone4Coding** [ionic-team/ionic#13831]
**Ionic version:**  
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...** 
[X] bug report
[ ] feature request

**Current behavior:**
I have a login page as root. After login, I set the next page the root (it's called PatientListPage) [Code snippet 1]. In this page I can add patients and I do "this.navCtrl.push('NewPatientPage')" [Code snippet 2] and in that page, when I want to leave, I do this.navCtrl.pop() [Code snippet 3] but I get 2 errors. The first says "inserted view was already destroyed" [First stack trace] ; and the second one says "removeView was not found" [Second stack trace] . And when I do a console.log() of the navigation stack, it shows that the root page is the login page.

**Expected behavior:**
It was expected that the pop() function would navigate me to the root page (e.g. PatientListPage).

**Steps to reproduce:**
1. The first page of the app must be the root.
2. Navigate to a second page and placing that second one as the root.
3. Navigate to a third page through push() function of the navigation.
4. On that third page, use the pop() of the navigation. 

Code snippet 1.
```
this.navCtrl.setRoot('PatientListPage');
this.toast.create({
    message: "Seja benvindo",
    duration: 2000
}).present();
```
Code snippet 2.
```
this.navCtrl.push('NewPatientPage');
```

Code snippet 3.
```
this.navCtrl.pop();
```

**Other information:**
Stack Trace 1.
```
vendor.js:1703 
ERROR Error: Uncaught (in promise): inserted view was already destroyed
    at c (polyfills.js:3)
    at Object.reject (polyfills.js:3)
    at OverlayPortal.NavControllerBase._fireError (vendor.js:50809)
    at OverlayPortal.NavControllerBase._failed (vendor.js:50802)
    at vendor.js:50849
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:4982)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
```
Stack Trace 2.
```
vendor.js:1703
 ERROR Error: Uncaught (in promise): removeView was not found
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:4973)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at e.invokeTask (polyfills.js:3)
    at i.isUsingGlobalCallback.invoke (polyfills.js:3)
```

**Ionic info:**
```
cli packages:
    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

local packages:
    @ionic/app-scripts : 3.1.2
    Ionic Framework    : ionic-angular 3.9.2

System:
    Node : v8.7.0
    npm  : 5.4.2
    OS   : Windows 10

Misc:
    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by Gone4Coding** [comment]
@kensodemann Hey, thanks for your reply! 
I really can't put this project on GitHub.. But the problem is that simple, as that I stated.

**Comment by kensodemann** [comment]
@Gone4Coding - you don't have to put your actual project out there. Just a minimal sample application we can use for debugging.

**Comment by msevestre** [comment]
@Gone4Coding Can you create a brand new project that reproduces the issue?

**Comment by Gone4Coding** [comment]
@msevestre Yes. I'll try that. Thank you. I'll give feedback

**Comment by Gone4Coding** [comment]
I already solved it. It was a problem with the loading object. I was creating the object in the constructor and presenting it on ```ionViewWillEnter```. I had to move the creation of the object to the ```ionViewWillEnter``` function.

**Comment by kensodemann** [comment]
Sweet! In that case, I am going to close this.
