### ISSUE TITLE
NavController should have a method to move a page in middle of stack to last index and keep ui state remember

### ISSUE THREAD

**Issue by tnguyen-lh** [ionic-team/ionic#13838]
Feature request
Removing a page from the NavController in middle of stack array, then insert the removed page back to the last index, the app show the page but ui state have been lost. 
However, popTo() can retain the ui state, but pages clear each other out of stack.

Should we have a method move(fromIndex, toIndex) and retain ui state?

I have tried below method to detect if the page is already in history, if it was in history, popTo it, otherwise push a new page, however it work in linear direction only:
Navigate from page A -> B -> C, then come back to A, page A retain state.
However from B -> A -> C, then come back to B, then A, page A lost state.

This feature will serve the use case where we have a search page with keyword, filter, infinitive scrolling. Users search something, filter it, scrolling to more paging. Then users navigate away, when they come to search page, everything is clear out. implement store with ngrx or cache provider getting very complex as it has to remember lots of things (keyword, results, pager, scrolling position) in the page.

`public goToPage( page: any ) {
        let hasPage: boolean = false;
        let oldPage: Component;
        let index: number;
        console.log( "......Nav size: " + this.navCtrl.length() )
        for ( index = 0; index < this.navCtrl.length(); index++ )
        {
            let v = this.navCtrl.getViews()[index]
            if ( page.name === v.component.name )
            {
                oldPage = v.component;
                hasPage = true;
                console.log( ".......Pop to page from history: " + page.name ) 
                break;
            }
        }
        if ( !hasPage )
            this.navCtrl.push( page );
        else
        {
          
                    this.navCtrl.popTo( oldPage );
        }
    }`

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#349

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by nicolo-paganin** [comment]
Hi, any news on this feature?

We need it too, it's very boring lose the page state everytime the user change page.
