### ISSUE TITLE
<ion-input> element is not clickable on IOS Only

### ISSUE THREAD

**Issue by DanielnetoDotCom** [ionic-team/ionic#13839]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Any <ion-input> element is not clickable on IOS Only (Device and Emulator), it is clickable on Android (Device and Emulator) and ionic serve
BTW, I have put an <ion-searchbar> element on the same page and it works fine

**Expected behavior:**
Be clickable as is in other platforms

**Steps to reproduce:**
I have a login page that loads first if the user is not logged
I have put in the login page only the  <ion-content> element and the <ion-input> and it does not work

**Other information:**
I do not know if it is happened regarding the css I am using, or the way I am loading the Login page.
I have google a lot and I could not find any answer

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\msn\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.11.3
    npm  : 3.10.10
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

NOTE: the repo does not have to be your actual project but can be a minimal application that duplicates the issue.

Thanks for using Ionic!

**Comment by DanielnetoDotCom** [comment]
@kensodemann  Thanks for your feed back

I found somewhere someone saying something about this

`IonicModule.forRoot(MyApp,{ scrollAssist: false }),`

it works for me, looks like is a bug on scrollAssist

**Comment by kensodemann** [comment]
@DanielnetoDotCom - I just tried a sample application with several inputs both with and without `{ scrollAssist: false }`, some with floating labels and some with standard labels. In all cases, it worked fine running on my iPhone 7 which has the latest iOS 11 installed.

I am going to close this as something that cannot be duplicated. If you can provide a sample application that duplicates the issue, I can look into why it is occurring for you and perhaps suggest a fix for your code, or perhaps you are doing something totally different from something I am doing that is triggering an actual bug in the Framework, in which case I could potentially suggest a workaround.
