### ISSUE TITLE
Typescript errors - e.g. cannot find modules including 'ControlValueAccessor' 

### ISSUE THREAD

**Issue by kierandesmond** [ionic-team/ionic#13835]
Hi Guys and gals,

Was trying to install a typescript based package earlier in the day. Now everything has gone hay-wall on one of my projects. 

![image](https://user-images.githubusercontent.com/34133202/35059075-dbb394cc-fbb1-11e7-8a8e-66072a2e9544.png)

**Current behavior:**
When I run ionic serve the errors in the image above appear.

**Expected behavior:**
Should run as normal (ordinarily)

** Attempts to date **

I've tried the obvious ones like
npm install
Re-installing ionic-angular
uninstalling and reinstalling typescript
uninstalling and reinstalling node types

I've created another ionic 3 project in a neighbouring project folder, that runs fine with ionic serve.

Any help would be welcome.

Thanks!

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
