### ISSUE TITLE
Using local Ionic

### ISSUE THREAD

**Issue by jindalabhishek** [ionic-team/ionic#13846]
Hi,
I don't have sudo permission on server. So I am using local installation of ionic. I installed it by using:
"npm install ionic" and it installed locally. After that I used: "./node_modules/.bin/ionic serve" to start the application. I throws the following error:
ERR: Your Node.js version is v6.3.0. Please update to the latest Node 8 LTS

Please help me out. As I don't have sudo permission to upgrade node js.

Thanks

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by jindalabhishek** [comment]
Hi,

I want to if global installation is must for ionic and local can't be used !

Regards
Abhishek Jindal
