### ISSUE TITLE
Deeplinking plugin using tabs

### ISSUE THREAD

**Issue by cdelgadob** [ionic-team/ionic#13843]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

I had an app using a side menu with deeplinks working as expected. The I had to change to tab navigation and before hitting the deeplink configuration the app is *somehow* rerouted to /tabs-0/start, losing the info that came in the url.
I can see the redirection is there looking at the tabRef object, which has a _linker object and inside it it has a _history array with two entries, the first is the original url and the second this redirection to the tabbed page.

**Expected behavior:**

The original URL should hit the deeplinks configuration and the app should follow the flow.

**Steps to reproduce:**

Create an app with tabbed navigation and deeplinks plugin, when the url hits the deeplinks config, the URL has been rewritten.

![captura de pantalla 2018-01-18 a las 11 12 29](https://user-images.githubusercontent.com/4520338/35092966-39a690c2-fc41-11e7-986b-05806c4f8c13.png)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!
