### ISSUE TITLE
Ibeacon app is crashing in android 8 (Oreo)

### ISSUE THREAD

**Issue by sidPuttur** [ionic-team/ionic#13844]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

I have developed an android Ibeacon app using ionic 3 according to this tutorial. https://ionicallyspeaking.com/2017/01/16/creating-a-beacon-application-with-ionic-2/

App is working fine in all the devices except android 8 (Oreo). App is crashing and also cannot find any error logs. Trying to debug using chrome inspect., expecting some error logs in catch., But could not find any error log. Can we mark this as a bug?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by sidPuttur** [comment]
Please check the  sample code here https://github.com/sidPuttur/sampleBeacon which works with android device other than Oreo.

**Comment by kensodemann** [comment]
Cloned your repo and updated the Android platform from `6.3.0` to `7.0.0` and everything worked fine on an emulated Android 8 device (I don't have a physical Android 8 device, the newest I personally have is an Android 6 device, and I won't be in the Ionic offices to try it on an actual device for at least a week or two).

Try it with the updated Cordova Android platform if you can and see if you have the same results.

Here is my environment:

```
~/Projects/Issues/sampleBeacon (master *): ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.1.2 
    Node              : v8.9.0
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/kensodemann/Library/Android/sdk/

Misc:

    backend : pro
```

**Comment by chandanch** [comment]
I'm getting the following error 
`Uncaught ReferenceError: startMonitoringForRegionis not defined`

`
cli packages: (C:\Users\admin\AppData\Roaming\npm\node_modules)

    @ionic/cli-plugin-proxy : 1.5.7
    @ionic/cli-utils        : 1.19.1
    ionic (Ionic CLI)       : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v9.3.0
    npm               : 5.5.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME     : C:\Users\admin\AppData\Local\Android\Sdk\
    HTTP_PROXY       : not set
    http_proxy       : not set
    HTTPS_PROXY      : not set
    https_proxy      : not set
    IONIC_HTTP_PROXY : not set
    PROXY            : not set
    proxy            : not set

Misc:

    backend : pro
`

**Comment by kensodemann** [comment]
@chandanch - that is not an Ionic issue. That message looks like it comes from the plugin. Raise that with the author of the plugin.

**Comment by sidPuttur** [comment]
@kensodemann sorry for the late reply. Updated my cordova to 8.0.0 and cordova platforms to android 7.0.0. as yours, but it is still crashing. Tested in 2 devices, OnePlus 5  and Google Pixel (Oreo). We got a major release in a week. So any help in finding the issue would be appreciated.  Thanks.

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:
    Node : v6.9.1
    npm  : 5.5.1
    OS   : Linux 4.4

Environment Variables:

    ANDROID_HOME : /home/siddiq/Android/Sdk

Misc:

    backend : pro

**Comment by kensodemann** [comment]
Have you tried contacting the plugin author or duplicating your issue in another application that does not use the plugin? Without an error message, it is very hard to tell what could be wrong. The only reason I lean towards an issue with the plugin is that I have not heard a lot of Ionic or Cordova apps in general not running on newer versions of Android (older versions, yes, newer not so much).

You may also want to ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). That will reach a much wider audience than this issue list does.

**Comment by fbiceo** [comment]
I got same problem, and here is my ionic info

`C:\ionic-projects\sampleBeacon>ionic info


cli packages: (C:\Users\User\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.6.0
    OS   : Windows 8.1

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
`

I clone this repo [https://github.com/sidPuttur/sampleBeacon](https://github.com/sidPuttur/sampleBeacon) and update android platform to 7.0.0, it works fine on both Android 5 and Android 6 devices, but can't work on Android 8 device.

What I found is that you must setup right UUID in this file
> sampleBeacon/src/providers/beacon/beacon.ts

`  // setup a beacon region
        this.region = this.IBeacon.BeaconRegion('my-IBeacon', 'abca1234-1234-1234-1234-123412341234');
                  console.log("Inside Region");`

It will crash on Android 8.0 device if UUID is correct. But I don't know how to log error on Android devices, any tips to log error message on Android devices?

**Comment by chandanch** [comment]
I updated cordova and re-installed the plugin the error is not appearing now

**Comment by fbiceo** [comment]
Finally I learn some skill to watch logcat, but I have no idea what's wrong, here is log 

>  D SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 76 : Hello BeaconProvider Provider
 D SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 80 : Inside initialize
 D SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 86 : Inside requestAlwaysAuthorization
 D SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 98 : Inside Region
 D CordovaWebViewImpl: >>> loadUrl(about:blank)
 W cr_AwContents: WebView.destroy() called while WebView is still attached to window.

And here is code from [link](https://github.com/sidPuttur/sampleBeacon/blob/master/src/providers/beacon/beacon.ts)

       // we need to be running on a device 
      if (this.platform.is('cordova')) {
     
        // Request permission to use location on iOS
        this.IBeacon.requestAlwaysAuthorization();
        console.log("Inside requestAlwaysAuthorization");

        // create a new delegate and register it with the native layer
          this.delegate = this.IBeacon.Delegate();
      
        // Subscribe to some of the delegate's event handlers
        this.delegate.didRangeBeaconsInRegion()
          .subscribe(
          data => {
            console.log("didRangeBeaconsInRegion");
            resolve(true);
            this.events.publish('didRangeBeaconsInRegion', data);
          },
          error => console.error()
          );

        // setup a beacon region
        this.region = this.IBeacon.BeaconRegion('my-IBeacon', 'abca1234-1234-1234-1234-123412341234');
                  console.log("Inside Region");

        // start ranging
        this.IBeacon.startRangingBeaconsInRegion(this.region)
          .then(
          () => {
            console.log("startedRangingBeaconsInRegion");
            resolve(true);
          },
          error => {
            console.error('Failed to begin monitoring: ', error);
            resolve(false);
          }
          );
      

      } else {
        console.error("This application needs to be running on a device");
        resolve(false);
      }

After trace log I found that crash event stop at 
    // start ranging
    this.IBeacon.startRangingBeaconsInRegion(this.region)

Any idea to solve this problem?
