### ISSUE TITLE
swipeBackEnabled not working in 3.13.1

### ISSUE THREAD

**Issue by huchun666** [ionic-team/ionic#13849]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
no work 

**Expected behavior:**
I can go back by sliding to the right 

**Steps to reproduce:**

**Related code:**
Configuration in app.module.ts:
```
ionicModule.forRoot(MyApp, {
	swipeBackEnabled: true
})
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
ionic info
cli packages: (C:\Users\think\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.1-201711081842

System:

    Android SDK Tools : 25.2.5
    Node              : v8.9.4
    npm               : 5.6.0
    OS                : Windows 10

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
I am going to close this as something that I cannot duplicate.

If you can provide a sample application via GitHub that duplicates this issue I will be happy to reopen the issue and have a look.

**Comment by huchun666** [comment]
@kensodemann 
https://github.com/huchun666/cos
