### ISSUE TITLE
Popover delay on dismiss should be an option

### ISSUE THREAD

**Issue by warri93** [ionic-team/ionic#13842]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request

**Current behavior:**
When closing a popover (dismiss) there is a delay of 500ms which is visibly for the users. It makes the application unusable for this amount of time.

**Expected behavior:**
Maybe it's an idea to have this delay set in the popover options so we can choose ourselves what kind of delay we want.

**Steps to reproduce:**
Open a popover and close it.

**Related code:**
Related code can be found in on line 189: https://github.com/ionic-team/ionic/blob/2273fb5d47eb64375f1608370d32b330cdc30bd9/src/components/popover/popover-transitions.ts

```
export class PopoverPopOut extends PopoverTransition {
  init() {
    let ele = this.leavingView.pageRef().nativeElement;
    let backdrop = new Animation(this.plt, ele.querySelector('ion-backdrop'));
    let wrapper = new Animation(this.plt, ele.querySelector('.popover-wrapper'));

    wrapper.fromTo('opacity', 0.99, 0);
    backdrop.fromTo('opacity', 0.08, 0);

    this
      .easing('ease')
      .duration(500)
      .add(backdrop)
      .add(wrapper);
  }
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 @ionic/cli-utils  : 1.17.0
    ionic (Ionic CLI) : 3.17.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.2 
    ios-sim           : 4.1.1 
    Node              : v9.3.0
    npm               : 5.5.1 
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/melissawarrens/Library/Android/sdk

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#350

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by warri93** [comment]
Hey @kensodemann, thanks for answering me! Unfortunately the link you provided isn't working.. 

Thanks!

**Comment by kensodemann** [comment]
That is a link to a private repo. It won't work for you. It is there mostly for team members to be able to tie the two items together.

FWIW, this process will be changing in the future, but for now it is what it is.
