### ISSUE TITLE
ion-slides pager overlapping with the ion-slide content

### ISSUE THREAD

**Issue by venkadesh02** [ionic-team/ionic#13851]
I am creating ion-slides as follows,

```
<ion-slides pager="true" *ngIf="canShowPieChart">
    <ion-slide *ngFor="let pieChartObject of pieChartObjects">
      <h3 style="color:#2D5F8A"> Sample Name</h3>
      <div style="display: block">
        <canvas baseChart [data]="pieChartObject.chartData" [colors]="pieChartColors" [labels]="pieChartObject.chartLabels" [chartType]="pieChartObject.chartType" [options]="pieOptions"></canvas>
      </div>
    </ion-slide>
  </ion-slides>
```

But pager dots overlapping with the chart content.

![screen shot 2018-01-19 at 12 24 00 pm](https://user-images.githubusercontent.com/3060733/35138252-b965523a-fd13-11e7-8b4a-5dc4f6b89714.png)

How to fix this?

**Comment by srinidhirao** [comment]
I have this issue too. Is there a way to position the slider control so that it does not overlap with the content?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Have you looked at our conference app sample project? https://github.com/ionic-team/ionic-conference-app

I believe it uses the slider without this issue.

Thanks for using Ionic!
