### ISSUE TITLE
Unable to run ionic commands

### ISSUE THREAD

**Issue by ZengYJ** [ionic-team/ionic#13850]
ionic version: v3.19.1
os: win7 x64
nodejs:v8.9.4
npm:v.5.6
I hava install nodejs and npm.Then I run "npm install -g cordova ionic" . In "C:\Users\zhoum\AppData\Roaming\npm\node_modules\ionic" ionic has installed. 
But in cmd,  when  I run "ionic --version" and "ionic start myNewProject",error apperas.

C:\Windows\system32>ionic -version
[ERROR] The config file (..\..\Users\zhoum\.ionic\daemon.json) is not valid JSON 
        format. 
        Please fix any JSON errors in the file.

In ionic directory, the file "daemond.json" doesn't exist.

I would appreciate for help. 
Thx.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

You may also want to try searching the issues in the `ionic-cli` repo

Thanks for using Ionic!
