### ISSUE TITLE
Error when creating project with Deepin 15.5

### ISSUE THREAD

**Issue by joserdaw** [ionic-team/ionic#13853]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Unexpected error at make a new project

**Expected behavior:**
Project created successfully

**Steps to reproduce:**
Typing at console "ionic start test tabs". If i exec the command with administrator privileges i get the same error.

**Related code:**

```
> npm i
⠧ Running command 
<--- Last few GCs --->

[2216:0x3ed88d0]   508446 ms: Mark-sweep 1348.7 (1406.3) -> 1348.7 (1406.3) MB, 835.0 / 0.0 ms  allocation failure GC in old space requested
[2216:0x3ed88d0]   509615 ms: Mark-sweep 1348.7 (1406.3) -> 1348.7 (1374.8) MB, 1169.7 / 0.0 ms  last resort GC in old space requested
[2216:0x3ed88d0]   510515 ms: Mark-sweep 1348.7 (1374.8) -> 1348.7 (1374.8) MB, 900.0 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3c7aa75a5739 <JSObject>
    1: /* anonymous */ [/usr/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/utils/shell.js:~44] [pc=0x15870c82c57c](this=0x3c710cf469d1 <Socket map = 0x293770a86be9>,chunk=0x25c76b854c59 <Uint8Array map = 0x293770a97d89>)
    2: emit [events.js:~108] [pc=0x15870c827bf8](this=0x3c710cf469d1 <Socket map = 0x293770a86be9>,/* anonymous */=0x3c7aa75b5011 <String[4]: data>)
    3: arguments ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [ionic]
 2: 0x11ef43c [ionic]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [ionic]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [ionic]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [ionic]
 6: 0xdf0023 [ionic]
 7: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [ionic]
 8: 0x15870c6842fd
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

System:

    Node : v8.9.4
    npm  : 5.6.0 
    OS   : Linux 4.9

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

FWIW, that looks like a classic "node is out of memory" error. I am not sure why you would run into that just generating an app like that. I never have on any of my machines (Mac, Linux, and Windows). However, if you google for "node JavaScript heap out of memory" you will see lots of posts like this: https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory

You may also want to look at issues in the `ionic-cli` or `ionic-app-scripts` repos.

Thanks for using Ionic!
