### ISSUE TITLE
This Problem is node_module,App-script or Sass.

### ISSUE THREAD

**Issue by yeshchaubey** [ionic-team/ionic#13854]
Dear Sir.

I am tray to new Ionic App credited.but this problem is after ionic serve.

node: v8.9.4
npm: v5.6.0
cordova: v8.0.0
os: windows7

Error: Cannot find module 'd:\Nikhil_IOS\go\gocoding\Go_Login\node_modules\@ionic\app-scripts'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\gplnikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\lib\ionic-angular\app-scripts.js:9:16)
    at Generator.next (<anonymous>)
    at C:\Users\gplnikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\tslib\tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\gplnikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\tslib\tslib.js:103:16)
    at Object.importAppScripts (C:\Users\gplnikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\lib\ionic-angular\app-scripts.js:7:20)
[ERROR] Error with .\node_modules\@ionic\app-scripts\package.json file: FILE_NOT_FOUND

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

FWIW, I attempted to duplicate this using a newly generated app on my Windows machine, but it worked just fine.

Based on the messages you are getting, you may want to try completely removing the `node_modules` folder from your project and re-running `npm i`

Thanks for using Ionic!

**Comment by yeshchaubey** [comment]
Dear Sir.

Thanks For suggestion "npm i"  running. but after running "npm i" same issue.



  Building solution configuration "Release|x64".
Project "D:\Nikhil_IOS\go\gocoding\Go_Login\node_modules\node-sass\build\binding.sln" (1)
is building "D:\Nikhil_IOS\go\gocoding\Go_Login\node_modules\node-sass\build\binding.vcxpr
oj.metaproj" (2) on node 1 (default targets).
Project "D:\Nikhil_IOS\go\gocoding\Go_Login\node_modules\node-sass\build\binding.vcxproj.m
etaproj" (2) is building "D:\Nikhil_IOS\go\gocoding\Go_Login\node_modules\node-sass\build\
src\libsass.vcxproj" (3) on node 1 (default targets).
D:\Nikhil_IOS\go\gocoding\Go_Login\node_modules\node-sass\build\src\libsass.vcxproj(20,3):
 error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confi
rm that the path in the <Import> declaration is correct, and that the file exists on disk.
Done Building Project "D:\Nikhil_IOS\go\gocoding\Go_Login\node_modules\node-sass\build\src
\libsass.vcxproj" (default targets) -- FAILED.

Done Building Project "D:\Nikhil_IOS\go\gocoding\Go_Login\node_modules\node-sass\build\bin
ding.vcxproj.metaproj" (default targets) -- FAILED.

Done Building Project "D:\Nikhil_IOS\go\gocoding\Go_Login\node_modules\node-sass\build\bin
ding.sln" (default targets) -- FAILED.


Build FAILED.

"D:\Nikhil_IOS\go\gocoding\Go_Login\node_modules\node-sass\build\binding.sln" (default tar
get) (1) ->
"D:\Nikhil_IOS\go\gocoding\Go_Login\node_modules\node-sass\build\binding.vcxproj.metaproj"
 (default target) (2) ->
"D:\Nikhil_IOS\go\gocoding\Go_Login\node_modules\node-sass\build\src\libsass.vcxproj" (def
ault target) (3) ->
  D:\Nikhil_IOS\go\gocoding\Go_Login\node_modules\node-sass\build\src\libsass.vcxproj(20,3
): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Con
firm that the path in the <Import> declaration is correct, and that the file exists on dis
k.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.06
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Nikhil_IOS\go\gocoding\Go_Login\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\node.exe" "D:\\Nikhil_IOS\\go\\gocoding\\Go_Login\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Nikhil_IOS\go\gocoding\Go_Login\node_modules\node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gplnikhil\AppData\Roaming\npm-cache\_logs\201

8-01-19T12_16_14_733Z-debug.log

**Comment by kensodemann** [comment]
OK, Thank-you. Is your project using the latest version of `@ionic/app-scripts`? 

The only other difference I noticed between my Windows machine was that I am using Windows 10 and you have Windows 7. I am not sure if that contributes to the issue or not.

Be sure to ask your question in either of the forums I mentioned in my previous comment. You will reach a much wider audience there.

If the issue persists, the https://github.com/ionic-team/ionic-app-scripts repo would be a more appropriate location for this issue. I highly suggest the forums I mentioned in my last reply though first as you are more likely to get the most traction there.
