### ISSUE TITLE
platforms/android/app/res/xml/config.xml (No such file or directory)

### ISSUE THREAD

**Issue by skygragon** [ionic-team/ionic#13857]
This error occurs after I upgrade my ionic/cordova. Now the build android failed with this error:
```
* Where:
Script '/Users/xxx/Projects/xxx/platforms/android/CordovaLib/cordova.gradle' line: 168

* What went wrong:
A problem occurred evaluating script.
> /Users/xxx/Projects/xxx/platforms/android/app/res/xml/config.xml (No such file or directory)
```

Following is my ionic env:

```
ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.2.1

System:

    Node  : v8.1.4
    npm   : 5.6.0
    OS    : OS X El Capitan
    Xcode : Xcode 8.2.1 Build version 8C1002

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by chandanch** [comment]
Remove the android platform add again and then try building it. I also had the same issue earlier

**Comment by skygragon** [comment]
@chandanch yep I tried but not help. I have to revert to cordova 7.1.0 and everything goes well now. There might be some bugs in 8.0.0.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

FWIW, I am using Cordova 8 and it works fine in _most_ cases, but I have run into issues with some plugins not being updated for it, so you might want to check that all of your plugins are up to date, and if you still have the issue, eliminate all except the standard set that Ionic uses and then add them back one by one. At least that has been my experience.

Thanks for using Ionic!

**Comment by jackycjh** [comment]
@skygragon I think this is related to https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/188#issuecomment-354438731

**Comment by kevin-ripley** [comment]
Cordova CLI v8.0 will use cordova-android@7.0.0 by default.

As most of the cordova plugins do not support cordova-android@7.0.0 yet, you can also try using the older one by specifying version:
```
ionic cordova platform add android@6.4.0
```

**Comment by ShahidMirza2017** [comment]
Cordova 8.0.0 have many issues till now it automatically set android 7.0.0 version which is not support by all android studio version so downgrade to @6.4.0 by using ionic cordova platform add android@6.4.0

**Comment by VladyslavGoloshchapov** [comment]
thank you, this helped

**Comment by mikecastrodemaria** [comment]
Same probleme here, the : ionic cordova platform rm android && ionic cordova platform add android@6.4.0 && ionic cordova build android work now.

**Comment by snowdream** [comment]
get it , thank you.

**Comment by gratitudeapps** [comment]
after downgrading to android 6.4:

Execution failed for task ':processDebugResources'.

**Comment by syedjafer** [comment]
Saved My day @ShahidMirza2017  Thank u
