### ISSUE TITLE
Feature Request - Background behavior control

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic#13859]
Hello Ionic team,

I have a feature request for Ionic 4 & Capacitor. 

Is it possible for you guys to create a plugin which can control its background behavior.
For instance, I want my app to automatically shut down after 10 minutes in background.

Right now, when I press android hardware home button, it will save the last status of app and when I open the app again, it will load that last status. 
However I want my app to completely shut down after being in background for 10 minutes and start from splash screen when user opens it up again. 

I realized there's no cordova plugin for this yet. 
Some of native apps have this behavior. They turn off itself after being 10 minutes in background and start from splash screen when I open it up later on. 

We should be able to control this behavior like this: 

```
if ( app is in background mode ) {
   setTimeOut ==> {
   exit,
 600,000ms
}
}
```

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#352
