### ISSUE TITLE
Ionic CLI not updating latest code with file save/refresh

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/ionic#13855]
When I save a file most of the time when the browser refreshes my new code hasnt been compiled, sometimes I have to resave the file again and again or if I want o be certain of my new code getting compiled I stop ionic and `rm -rf www/build && mkdir -p www/build` Im just wondering if there is a way to make sure that the build folder is rebuilt on every file save so that my latest code is being displayed. 

my environment is as follows:

```
ionic -v
3.19.1
ionic info
cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1
global packages:
    cordova (Cordova CLI) : 7.1.0 
local packages:
    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2
System:
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.8 
    Node       : v8.9.1
    npm        : 5.5.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 
Environment Variables:
    ANDROID_HOME : not set
Misc:
    backend : pro
```

**Comment by mburger81** [comment]
Should be same issue then this https://github.com/ionic-team/ionic-app-scripts/issues/1132

**Comment by kensodemann** [comment]
@mburger81 - thx! now I don't have to go look that up... :)

@REPTILEHAUS - I am going to close this for the following reasons:

- it is in the wrong issues list, this is an issue with `@ionic/app-scripts` and not the Ionic Framework
- it is a duplicate (unfortunately, I believe there are more than just the one that @mburger81 linked, but if you look in that issues list you can find others)

Please follow the linked issue and respond in it with any new information you may have.

**Comment by mburger81** [comment]
@kensodemann, yes there are many of this errors. 
Can we know why you ignore all this issues from so many time? I personally think in v4 you finally and hopefully will kick out `app-scripts` and so all this bugs should be obsolete, is that the reason?
It would be really really nice if we could have a feedback from you on this issues.
thx a lot

**Comment by kensodemann** [comment]
@mburger81 - you will have to ask that question on the `app-scripts` issue list. I don't do anything with that project (other than paying attention to it so I can suggest ppl upgrade to the latest if I know a bug is fixed).

My best guess is that no one has found a good solution to it yet, but that is just a guess on my part. I doubt the maintainers of `app-scripts` are ignoring the issue.
