### ISSUE TITLE
Ionic-3 Ion Slides are breaking the styles as half while orientation

### ISSUE THREAD

**Issue by AlbenJohn** [ionic-team/ionic#13858]
Hi,
 I know this is already asked lot . But i did not get the correct solution.

If I serve the ionic project that is in portrait mode, the slides are working fine . If I rotate the orientation its break down as half. If I refresh again the styles are fixing properly. 

Please guide me with the correct solution.
Thanks in advance.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
