### ISSUE TITLE
Feature Request - Compatibility with React.js

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic#13860]
Hello Ionic team,

Is Capacitor going to be able to use React.js & Redux?
I realized React.js is much faster than Angular. Everyone points out that as a fact. 
And many people including myself have pointed out slow speed as a problem of hybrid app. 
So I'm wondering if using React & Redux as front end will make Ionic apps faster.

http://voidcanvas.com/angular-vs-react-vs-ember-vs-vue-js/

and I recommend you guys to consider integrating anime.js as an official animation framework of Ionic 4

http://animejs.com/

It's much better than Anuglar animations & CSS3 animations. 
I think it's the best open source animation framework ever created. It beats Green sock animation platform. Angular animation is buggy and it has limitations.. It causes lots of problems... and 'BrowserAnimationsModule' doesn't feel very stable.  It crashes app all the time for a real tiny bit of mistakes. When I discovered anime.js, I realized there's no more reason to even use angular animations... 
Anime.js has everything a user will ever need and it's free. 

It looks like there are still more advantages of using JavaScript than TypeScript which needs typings. So React JS makes sense here.

**Comment by jamesharvey2** [comment]
Ideal toolset would be: 

- React.js
- Open source JavaScript libraries which work without typings
- JavaScript interface
- Cordova Plugins
- Open source SDKs pre-installed or offered as installable packages with javascript control interface
- Capacitor WebView without problems of old cordova (splash screen issues, slow speed) 

I imagine this will prevent speed problems & aged / outdated plugins problems of hybrid apps.

**Comment by jamesharvey2** [comment]
TypeScript is great but honestly I would like to ask for JavaScript this time because nothing is better than using javascript libraries in this set up and typescript just makes it more difficult to do that. React.js is the best candidate for fast progressive app development.

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#351

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!
