### ISSUE TITLE
Bug on iOS when scrolling dynamic forms

### ISSUE THREAD

**Issue by EduardoBarrero** [ionic-team/ionic#13868]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**
Only on iOS. When I do scroll on a dynamic form, floating labels of existing inputs out of bounds of screen are lost. 
When I say dynamic form I mean forms that are filled by using formGroup.addControl/removeControl methods.
When I say out of bounds of screen I mean content hidden by scrolling, when all content cannot be shown due to screen size.
When I say are lost, I mean I cannot see it. It seems a render bug.

**Expected behavior:**
When I add new controls to a form, existing floating labels out of the bounds of screen musnt't dissapear

**Steps to reproduce:**
1 . Create a form whith, for example, 5 fixed text input, with floating labels.
2. Below, create a button which insert few text input dynamically on click. This make scroll to se the new added content.
3. Scroll up to see the first text inputs. The floating labels of these inputs are not shown

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by EduardoBarrero** [comment]
Here you can see it working
https://youtu.be/Hw3gVI_GOTI

**Comment by EduardoBarrero** [comment]
More info. I realised that this only occurs from iOS 11. In previous versions, it works OK

**Comment by kensodemann** [comment]
Thank you for the video. We need the sample application for debugging purposes.

Based on your last statement (only happening on iOS 11), please make sure you are following all of the advice here: https://blog.ionicframework.com/ios-11-checklist/

Especially the WKWebView advice.

**Comment by pcsantana** [comment]
I have a similar problem. I did realize that when I have a **floating** label input forms, if I scroll quickly, I can see a delay to render the page, and If I do it more times (scroll quickly) sometimes some components disappear. 
But I only can reproduce this in a real device, and in my case I was using an **Android** device.

The problem seems to be the floating label input. Because if I change it for stacked label input, the delay rendering disappears.
