### ISSUE TITLE
Webpack Imported Module

### ISSUE THREAD

**Issue by CodeDruid13** [ionic-team/ionic#13863]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I've been getting the webpack error on ALL my projects since today and honestly a lot of Google consumption ain't helping
__WEBPACK_IMPORTED_MODULE_0__angular_core__.n is not a constructor
    at Object.__webpack_exports__.b (common.js.pre-build-optimizer.js:52)
    at __webpack_require__ (bootstrap a2c9e0e48c15d7bf651c:54)
    at Object.<anonymous> (button.ngfactory.js.pre-build-optimizer.js:17)
    at __webpack_require__ (bootstrap a2c9e0e48c15d7bf651c:54)
    at Object.<anonymous> (gesture-controller.js.pre-build-optimizer.js:255)
    at __webpack_require__ (bootstrap a2c9e0e48c15d7bf651c:54)
    at Object.defineProperty.value (ChildrenNode.js.pre-build-optimizer.js:502)
    at __webpack_require__ (bootstrap a2c9e0e48c15d7bf651c:54)
    at Object.<anonymous> (label.js.pre-build-optimizer.js:117)
    at __webpack_require__ (bootstrap a2c9e0e48c15d7bf651c:54)

**Expected behavior:** 

All my projects were fine and i have not updated or changed anything

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.6.0
    OS   : Linux 4.13

Environment Variables:

    ANDROID_HOME : not set

Misc:

**Comment by CodeDruid13** [comment]
Any help would be appreciated.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by gabolucuy** [comment]
I had the same problem, no idea why. But I solved it by erasing the node_modules folder from the project and runnig `npm install`  and the app start working again
