### ISSUE TITLE
Ionic highlight by mousedrag.

### ISSUE THREAD

**Issue by urfli911** [ionic-team/ionic#13878]
Hi All, I would like to ask for help on how to highlight/select multiple dates in  ionic calendar by pressing the mouse and drag and the dates along the cursor's path will be selected as long as I am pressing the mouse.
It appears to me that only onChange event by which you need to click all the dates you want to select is accepted in the calendar.

Thanks.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
