### ISSUE TITLE
"Failed to restore plugin" after version updates

### ISSUE THREAD

**Issue by jfrohn** [ionic-team/ionic#13874]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I updated Ionic and Cordova (see below). Now `ionic cordova prepare && ionic cordova platform add android && ionic cordova platform add ios` fails for some plugins on iOS, e.g.:
```
Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project
Installing "cordova-plugin-splashscreen" for android

Installing "cordova-plugin-splashscreen" for ios
Failed to restore plugin "cordova-plugin-splashscreen" from config.xml. You might need to try adding it again. Error: Error: Cannot find module '../cordova/platform_metadata'
```

I already updated all plugins to their newest versions:
```
> cordova plugin ls
com.lampa.startapp 0.1.4 "startApp"
cordova-android-support-gradle-release 1.2.0 "cordova-android-support-gradle-release"
cordova-plugin-add-swift-support 1.7.1 "AddSwiftSupport"
cordova-plugin-android-fingerprint-auth 1.4.1 "FingerprintAuth"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-camera 4.0.1 "Camera"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 2.0.1 "InAppBrowser"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-nativegeocoder 2.0.4 "NativeGeocoder"
cordova-plugin-secure-storage 2.6.8 "SecureStorage"
cordova-plugin-splashscreen 5.0.1 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-touch-id 3.3.1 "Touch ID"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
> ionic info

cli packages: (C:\Users\...\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v6.9.3
    npm               : 5.6.0
    OS                : Windows 10 

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by kensodemann** [comment]
You can also check the Ionic CLI issue lis: https://github.com/ionic-team/ionic-cli
