### ISSUE TITLE
How to restrict state change handling using ionic?

### ISSUE THREAD

**Issue by ankushgoyal27** [ionic-team/ionic#13875]
Scenario.

Application has presignon and post signon pages.

In post signon, there is a functionality which has Step 1 , Step 2 and Step 3.

Requirement:
From menu, User always landed on Step 1.
Once user filled and submit the form then only application allows user to navigate to Step2,
Once confirmed on Step2 and Submit than navigate to Step 3

If user manually enter the URL to Step2 or Step3, then also application doesnt allow user to land on Step2 or Step 3.

If User click the browser back button on step3 then user lands on Step1.

I want to implement the above scenario in my app.

Is there any way to implement using ionic 3?

I have already tried the above scenario using ionic lifecycle hooks. but didnt achieve the goal.

Thanks

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
