### ISSUE TITLE
Is play.ionic.io now dead ?

### ISSUE THREAD

**Issue by JammiM** [ionic-team/ionic#13872]
Is play.ionic.io now dead ?

http://play.ionic.io/

**Comment by mhartington** [comment]
Hey @JammiM ! Yes, we decided to sunset play.ionic for now. Another alternative that we suggest is http://stackblitz.com

**Comment by JammiM** [comment]
@mhartington That stackblitz website looks great, is there a version for Ionic 1,

**Comment by mhartington** [comment]
No, but you could use codepen instead.
