### ISSUE TITLE
TestBed for HttpInterceptor: NullInjectorError: No provider for Events

### ISSUE THREAD

**Issue by srjovanovic** [ionic-team/ionic#13881]
I’ve wrote TestBed for HttpInterceptor. I start Karma, it shows an error:
Error: StaticInjectorError[Events]:
StaticInjectorError[Events]:
NullInjectorError: No provider for Events!

How can I provide Events in TestBed?

// My HttpInterceptor

> import {HttpEvent, HttpHandler, HttpInterceptor, HttpRequest} from “@angular/common/http”;
> import {Injectable} from “@angular/core”;
> import {Events} from “ionic-angular”;
> import {Observable} from “rxjs/Observable”;
> 
> @Injectable()
> export class APIAuthInterceptorProvider implements HttpInterceptor {
> 
> constructor(private connectionEvent: Events) {
> }
> . . .
>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
