### ISSUE TITLE
Feature Request: Meridiem (AM/PM) Localization

### ISSUE THREAD

**Issue by bbagdad** [ionic-team/ionic#13880]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] feature request

**Requested Feature**
Add localization for Meridiem (AM/PM) in ion-datetime component.

I did fork the project and added a suggested enhancement for this feature.
I will be submitting a pull request to add this in.

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#354
