### ISSUE TITLE
Feature Request: Hardlimit on number of rendered VirtualScroll entries

### ISSUE THREAD

**Issue by Farbdose** [ionic-team/ionic#13889]
**Ionic version:**
[ ] **2.x**
[x] **3.x**
[x] **4.x** (dunno?, didn't read up on planed changes yet)

**I'm submitting a ...** 
[ ] bug report
[x] feature request

**Current behavior:**
When used in UIWebView and/or environments with unclear content dimensions the VirtualScroll sometimes can't figure out how many entries it should display because the content height is not known.

This results in the VirtualList displaying **ALL** entries which can freeze/crash the app if your raw data has enough entries (e.g. >2000)

**Expected behavior:**
Limit the number of displayed entries to e.g. 100 regardless of what the content dimensions report on the container height. This limit should be accessible as an input parameter for customization.

**Steps to reproduce:**
Nest a VirtualScroll inside other components with unclear content dimensions.

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#353

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!
