### ISSUE TITLE
Ionic calendar issue

### ISSUE THREAD

**Issue by urfli911** [ionic-team/ionic#13885]
Hi, I would like to ask why the dates in the ionic calendar are not selected using pan gesture? When I do a pan gesture to the right starting from day 1 , the dates along the mouse cursor path should've been selected.  I  2,3,4,5 and 6 should be higlighted and execute the method assigned to (onchange) event emitter. My pickmode is already set to 'multi'.

Thanks.

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please, with a sample application that demonstrates the issue you are having. Thanks for using Ionic!
