### ISSUE TITLE
Feature Request - Virtual DOM for Ionic & Angular

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic#13884]
Hello Ionic team,

I do believe the main reason which people say ionic app is slow in general is slow rendering speed of Angular 5. 
In this article, this company discusses speed problem of angular 2.

https://clockwise.software/blog/angular-vs-react-vs-vue/

> **Lower render speed**
> The limited usage of shadow DOM and lack of virtual DOM result in lower performance. The view render/re-render speed is slower compared to the performance shown by other JavaScript frameworks on our chart. 

I think this is true.  App's UI rendering speed was one of my main concerns while working on Ionic apps. I followed every documentation & tutorials but all apps were rather slower than normal apps. Some of them were too slow when triggering many functions so I had to rewrite their codes. This is mainly because of use of Angular. Angular is slowing down the app. 

Then I found some PhoneGap apps are actually faster than Ionic apps.
If you can't believe, please try this PhoneGap app (https://play.google.com/store/apps/details?id=com.tricedesigns.InstantHalloween). It's as fast as normal native apps. It uses virtual DOM style js framework which renders HTML from js files.  It's possible to achieve this level of performance without angular... angular helps building UI logic but when it's used on Cordova, it makes everything slower than normal.

Is it possible for Ionic team to implement virtual DOM to Ionic and Angular? 
That'll perhaps solve the problem.
Vue.js uses html file, js but still come with virtual dom and it's actually as fast as React. 

I'm one of the people who think Angular & Ionic app is slower than normal native apps written in Java & Objective -C.

React's UI rendering speed is up to twice faster than that of Angular 5. On desktop, we may not feel that much difference due to high performance CPU but on smartphones, we can feel that difference. 

In 2018, we should stop making slow speed apps. 
Everyone's pointing out angular's slow UI rendering speed as a problem...
and many people have been saying hybrid app is slower than native apps. 

**Three solutions are here:** 

- Implement virtual DOM to angular & Ionic UI 
- Use React.js & Redux as front end
- Use Vue.js & Vuex as front end

**Comment by mhartington** [comment]
Hello there! Thanks for the issue! 

We're working on this actually with Ionic 4, using Stencil/Web components as our base

https://stenciljs.com


Closing this as it's part of our V4 target.

**Comment by jamesharvey2** [comment]
Hi Mike, That's good to know.

This must be implemented to Ionic & Ionic version Angular 5. 

FACT: Phonegap apps using virtual dom style js UI is faster than Ionic. I have tested this on many smartphones... 

I wondered why people use angular & Ionic to build apps because it's way too slower than normal apps. 
Everything I build on angular & ionic combo responds much slower than on native java apps. This is why Google didn't make their own app framework based on Angular. They made Angular for desktops and laptops which come with more powerful CPUs..  and not for smartphone apps originally. 

React.js & Vue.js on the other hand were created for fastest rendering that can be found in the market. 
So I would highly recommend you guys to completely change the way current UI is rendered on cordova. 

Capacitor's UI must use virtual DOM.. otherwise it will no longer make sense in 2018. 
Adobe published PhoneGap in 2012 and speed wasn't a problem as it didn't use angular which has slow UI rendering speed.
