### ISSUE TITLE
ionic tabs lag at first startup

### ISSUE THREAD

**Issue by giuliastully** [ionic-team/ionic#13883]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

**Current behavior:**
In my Ionic 3 app I have 4 tab but I have a problem at startup of the app (real device).          
When I change tab, the color doesn't change and It seem the app have a strong lag.     
The next starts of the app are ok, tab change color perfectly.   
In every page I load data from Firebase Realtime Database, but the problem is not the page, but tabs. 
In browser emulator I have no problem (using ionic serve).

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!
