### ISSUE TITLE
searchbar issue with Chinese keyword on ios?

### ISSUE THREAD

**Issue by skygragon** [ionic-team/ionic#13891]
* ionic: 3.19.1
* cordova: 7.1.0
* ionic-plugin-keyboard: 2.2.1

On IOS when I type Chinese word in searchbar, extra chars are added in the output text, e.g. to type Chinese “中” I need to type 5 chars: "z","h","o","n","g" and select "中" in the keyboard. But the final output in searchbar will be "zhong中".

While if I type same words in a plain html input tag, the output text is correct.

Android doesn't have this issue..

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by skygragon** [comment]
similar issue to https://github.com/ionic-team/ionic/issues/11566
