### ISSUE TITLE
Ionic Page Segment with multiple values does not work

### ISSUE THREAD

**Issue by LeonardoGuimaraes** [ionic-team/ionic#13894]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have three pages in my application. with this configurations:

PageA:
```
@IonicPage({
	segment: ":courseId/:classId"
})...
```
PageB:
```
@IonicPage({
	segment: ":courseId"
})...
```
PageC:
```
@IonicPage({
	segment: "all"
})...
```

Everytime I access the `[HOST]/#/all`, it's load the PageC, OK!
Everytime I access the `[HOST]/#/someID`, it's load the PageB, OK!

Everytime I access the `[HOST]/#/someID/someID_2`, it's load the PageB, ERROR!
OBS: When it's happen, the someID (of PageB) gets the value someID_2.

**Expected behavior:**

Everytime I access the `[HOST]/#/all`, PageC is loaded, OK!
Everytime I access the `[HOST]/#/someID`, PageB is loaded, OK!

_Everytime I access the `[HOST]/#/someID/someID_2`, PageA is loaded_

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by FdezRomero** [comment]
Hi @LeonardoGuimaraes! I use deeplinks all the time and I haven't found this problem. Is it possible that you have 2 pages or tabs using the same `segment` or `name` value? Can you link to an example that reproduces the problem?
