### ISSUE TITLE
Ionic 3 Unable to fix maxlength for prompt input of alert controller

### ISSUE THREAD

**Issue by AltRoot17** [ionic-team/ionic#13892]
ionic-3 I have some small issue, I want to set the max length dynamically, I tried but not work that Unable to fix max length for prompt input of alert controller I want to know how to do that dynamically, and Im tried to used  `max:'4',`
          type:'number', but not work ,

Thanks

```
 doPrompt() {
        let prompt = this.alertCtrl.create({
          title: 'Add your digit code',
          message: "",
          inputs: [
            { 

             type:'number',
              name: 'title',


           placeholder: '* * * *',
              max:'4',
            },
          ],
          buttons: [
            {
              text: 'Cancel',
              handler: data => {
                console.log('Cancel clicked');
              }
            },
            {
              text: 'Save',
              handler: data => {
                console.log('Saved clicked');
              }
            }
          ]
        });
        prompt.present();
      }
    }
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by AltRoot17** [comment]
@kensodemann  Sir I all ready asked my question, https://forum.ionicframework.com/t/ionic-unable-to-fix-maxlength-for-prompt-input-of-alert-controller/119472  but I don't have any solution :(
