### ISSUE TITLE
I can not delete images from storage 

### ISSUE THREAD

**Issue by velonicatt** [ionic-team/ionic#13900]
I can not delete images from storage 
display images by VirtualScroll

`<ion-list [virtualScroll]="imageList">`
`<ion-item *virtualItem="let item">`
`<ion-icon name="trash" class="deleteIcon" (click)="removeItem(item)"></ion-icon>`
 `<ion-img [src]="item" class="thumb-img" (click)="presentModal(item)"></ion-img>`

`this.imageList = [];`
    `this.storage.get('imageScreen').then((val) => {`
     ` this.imageList = val;`
 `   });`

I tried this but after close page and open again the picture does not go away.

`for(let i = 0; i < this.imageList.length; i++) {`
     ` if(this.imageList[i] == item){`
        `this.imageList.splice(i, 1);`
    `  }`
`  }`

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
