### ISSUE TITLE
Date for ionic 4  

### ISSUE THREAD

**Issue by wuilmerj24** [ionic-team/ionic#13901]
ionic output date 4?

**Comment by bryce13950** [comment]
I am also very curious about this

**Comment by alanhg** [comment]
same question

**Comment by tiagogomes07** [comment]
me too.

**Comment by xjstddj** [comment]
me too！

**Comment by kensodemann** [comment]
The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this is neither, I am going to close and lock discussion on this issue.
