### ISSUE TITLE
V3 back button text use previous page's title

### ISSUE THREAD

**Issue by dreamhuan** [ionic-team/ionic#13908]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
back button text is 'Back', and it just can be config to plain text
```
IonicModule.forRoot(MyApp, {
    backButtonText: 'plain text',
}),
```

**Expected behavior:**
A convenient way to set it be previous page's title

**Other information:**
now I just set every page's button text use
```
<ion-header>
    <ion-navbar hideBackButton>
        <ion-buttons>
            <button ion-button clear side="left" (click)="back()">
                <ion-icon name="arrow-back"></ion-icon>
                <div class="back-text">last page's title</div>
            </button>
        </ion-buttons>
        <ion-title>this page's title</ion-title>
        <ion-buttons end>
            <button ion-button clear side="right" (click)="add()">
                <ion-icon name="add"></ion-icon>
                <div>Add</div>
            </button>
        </ion-buttons>
    </ion-navbar>
</ion-header>
```
this way is terrible in big application

in [this issue](https://github.com/ionic-team/ionic-site/issues/436) @danbucholtz 's thought is the same as me

**Comment by jwt02180** [comment]
I would like to point out that when in the android mode, this is already accomplished for you.
But if you'd like this behavior on other platforms there is a function you can call on the Navbar, shown in the [docs](https://ionicframework.com/docs/api/components/toolbar/Navbar/#setBackButtonText).
