### ISSUE TITLE
ion-infinite-scroll doesn't work inside ion-scroll (ion-scroll doesn't fire scrolling events)

### ISSUE THREAD

**Issue by pavelglebov** [ionic-team/ionic#13904]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
ion-scroll component doesn't fire scroll events, this affects functionality which is dependent on them (e.g. ion-infinite-scroll inside ion-scroll doesn't work).

**Expected behavior:**
ion-infinite-scroll works inside ion-scroll

**Steps to reproduce:**
Please check code below:

**Related code:**
```
<ion-content>
  ... // some dynamic non-scrollable content

  <ion-scroll scrollY="true">
    <ion-infinite-scroll (ionInfinite)="loadMore($event)" position="top">
      <ion-infinite-scroll-content></ion-infinite-scroll-content>
    </ion-infinite-scroll>

    <div>
      <custom-component *ngFor="let message of messages" [message]="message"></custom-component>
    </div>
  </ion-scroll>
</ion-content>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v6.11.5
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 
```

**Comment by vinicius91carvalho** [comment]
https://stackoverflow.com/questions/48019693/ion-infinite-scroll-not-working-inside-ion-scroll?rq=1
