### ISSUE TITLE
Feature request: dynamic screen orientation

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic#13915]
Hello Ionic team,

I have a feature request for capacitor & ionic 4. 
Current cordova screen orientation plugin allows you to set your app to one particular screen orientation, either portrait or landscape mode. 
This doesn't really solve problems in all situations... for instance, for smartphone screens, I want my app to stay in portrait mode and for tablet screens (7 inch+) I want my app to stay in landscape mode. 
The plugin should be able to work according to pixel width just like on CSS3 media queries.. unfortunately, this is not the case for the current cordova plugin..
Media query alone will not solve this problem. I think screen orientation plugin should be able to change its orientation dynamically according to device's screen width. 
Please make this happen.

Ideally, something like this would be great: 

```
@screen-orientation (max-width: 500px) {
  this.screen-orientation.setPortrait() 
}

@screen-orientation (max-width: 1200px) {
  this.screen-orientation.setLandscape()
}
```

**Comment by mhartington** [comment]
Hi there! First off, please fill out the issue template when opening new issues.  As for media queries, css already has this.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/orientation

For what you want, you can use Javascript match media API.

**Comment by jamesharvey2** [comment]
You're right
https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia

I will take a look into this.

Thanks!
