### ISSUE TITLE
dynamic compile html code fragment  throws a strange error with @Component

### ISSUE THREAD

**Issue by sid-ihycq** [ionic-team/ionic#13917]
this is my dynamic content page:
```
export class MyPage {
	@ViewChild('container', { read: ViewContainerRef }) container;

	constructor(private compiler: Compiler, ...) { ... }

	dynamicContent() {
		const that = this;

		@Component({ template: this.activity.content })
		class DynamicComponent {
			...
		}
		@NgModule({
			declarations: [DynamicComponent],
			imports: [IonicPageModule.forChild(DynamicComponent)]
		})
		class DynamicModule { }

		this.compiler.compileModuleAndAllComponentsAsync(DynamicModule)
			.then(factories => factories.componentFactories.find((x => x.componentType === DynamicComponent)))
			.then((factory: ComponentFactory<any>) => {
				this.container.createComponent(factory);
			})
		}
	}
}
```

I had try those build cmd on ionic3@lastest: 
ionic cordova build ios --debug
ionic cordova build ios --minifyjs --minifycss --optimizejs

it runs ok on web edition。but in app，it throws an exception at this line during runtime:
> @Component({ template: this.activity.content })
and the error position is the end  of "this";

finally, i found that use a temp variable works fine：
```
dynamicContent() {
	const that = this;
	const content = this.activity.content;
	@Component({ template: content })
	class DynamicComponent { ... }
}
```
does anyone can explain?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
