### ISSUE TITLE
FAB container needs a main <button ion-fab>

### ISSUE THREAD

**Issue by chrifrachid** [ionic-team/ionic#13910]
Error:

![issue2](https://user-images.githubusercontent.com/16919684/35565318-ffb04d04-05b4-11e8-99ab-7dbde4829e90.jpg)

-------
Code:

![issue1](https://user-images.githubusercontent.com/16919684/35565320-052c2fb4-05b5-11e8-945f-3e84d43fcce2.jpg)

**Comment by raymonddavis** [comment]
@chrifrachid Is the `ion-fab` placed inside an `ion-content` as a direct child?

**Comment by medMethnani** [comment]
This is how it should be used the ion-fab:

<ion-content>
  <ion-fab bottom right>
  <button ion-fab>Contact</button>
  <ion-fab-list side="left">
    <button ion-fab (click)="twitter()"><ion-icon name="logo-twitter"></ion-icon></button>
    <button ion-fab (click)="facebook()"><ion-icon name="logo-facebook"></ion-icon></button>
  </ion-fab-list>
</ion-fab>
</ion-content>

**Comment by Roleofm** [comment]
I think it because of the ngIf.  Depending on the outcome of the conditiont the ion-fab button is missing in the ion-fab container
