### ISSUE TITLE
(click) vs (tap) delay in ios9

### ISSUE THREAD

**Issue by SBuiteman** [ionic-team/ionic#13911]
Using ionic 3.19.1 there is an issue with the click delay on apple devices running on iOS 9. Even when using (click) only on button and a elements, or when adding tappable to the elements. 
This issue can currently be "resolved" by replacing (click) with (tap). Another solution would be to use Fastclick for ios devices, which is also not a preferable option. However this should not be necessary.

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please.

Also please provide a sample application via GitHub that demonstrates the issue.

Thanks for using Ionic!
