### ISSUE TITLE
Feature request: compatibility layers (or adapters) for NativeScript & React Native Plugins???

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic#13916]
Hi Ionic team,

This may sound strange but is it possible for you guys to create nativescript & react native plugin compatibility layers on capacitor? 
If capacitor can have cordova compatibility layer, I think NativeScript & React Native compatibility layer may not be an impossible idea. 
React Native has 8,000 npm packages... NativeScript has 800 plugins. 

https://market.nativescript.org/plugins/

https://www.npmjs.com/search?q=react+native

All of them are newer than cordova plugins (which are likely from 2010-2013) and have better functionality. 
If we can use plugins of cordova, nativescript, react native at a time in one framework, It would be amazing.

On React Native and NativeScript, it's possible to use all web features by using WebView and setting webview's visibility to none. 
For instance, you can use native components with web API features. So I'm wondering if the opposite can work out. 

There was a guy creating Cordova plugin adapter for React Native:
https://www.npmjs.com/package/react-native-cordova-plugin

So maybe something like React Native plugin adapter for cordova layer could work too. 

This can solve aging plugin problems of cordova... users will be able to get access to the newest plugins out there. Also it can prevent users from switching frameworks to use different plugins.

**Comment by mhartington** [comment]
Hi there! This issue does not appear to be an issue with the framework itself, so it will be closes. Please review your issue and open a new ticket on the appropriate project repository, or feel free to post a question on the [Ionic Forum](http://forum.ionicframework.com). Thanks!

**Comment by jamesharvey2** [comment]
This is a good idea though. If you guys make an adapter, a lot of new plugins will be unlocked for use on capacitor. 
All of them are from 2015 - 2017.

**Comment by jamesharvey2** [comment]
and this is a valid opinion. 
Now cordova contact plugin is deprecated. 
Original creator of old cordova plugins no longer remember what they created...

How is it correct to still rely on old cordova plugins for the future? 

and it can be a lot of work to re-create those plugins.. so the best method is creating a nativescript & react native plugin adapter for capacitor. That'll solve this problem right out of box.
