### ISSUE TITLE
Please provide platform-generic styles for custom look and feel

### ISSUE THREAD

**Issue by snortblt** [ionic-team/ionic#13912]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[X] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After building two Ionic apps for companies that both wanted a custom look and feel on mobile, attempting to override the Ionic styles for iOS and Android is tedious and brittle.

**Expected behavior:**
I would love to have a bare-bones generic theme that can be more easily customized for a primarily unified style on both mobile platforms (and desktop too, ideally). This would help avoid selectors like `.list-form .item-ios.item-block:not(.item-checkbox) .item-inner, .list-form .item-md.item-block:not(.item-checkbox) .item-inner {
	border-bottom: 1px solid color($colors, item, border);	
}`
which is not terribly practical.
Also, it's unclear what best practices are for overriding styles in components. A "how to" guide for deep theming would be much appreciated.

**Steps to reproduce:**
Try customizing things like ion-item, ion-tabs, ion-segment, ion-button extensively. You very quickly get outside the limited theming capabilities that come with Ionic.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v6.11.3
    npm               : 3.10.10
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Users/josh/Library/Android/sdk

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#355
