### ISSUE TITLE
How to delete images from device - ionic

### ISSUE THREAD

**Issue by velonicatt** [ionic-team/ionic#13925]
I try .splice but it's not work

`<ion-content padding>`
  `<ion-list [virtualScroll]="imageList">`
    `<ion-item *virtualItem="let item">`
        `<ion-icon name="trash" class="deleteIcon" (click)="removeItem(item)"></ion-icon>`
        `<ion-img [src]="item" class="thumb-img" (click)="presentModal(item)"></ion-img>`
    `</ion-item>`
  `</ion-list>`
`</ion-content>`

`removeItem(item) {`
    `for (let i = 0; i < this.imageList.length; i++) {`
      `if (this.imageList[i] == item) {`
       ` this.imageList.splice(i, 1);`
      `}`
   ` }`
`  }`

after click delete icon image was lost after close and open app those images is com back.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
