### ISSUE TITLE
ion-select with popover interface wrong position

### ISSUE THREAD

**Issue by mariossavva** [ionic-team/ionic#13923]
**Ionic version:** 
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
ion-select with interface popover when it's close to the bottom of a page pop down towards the bottom and shows very small.

**Expected behavior:**
the popover should pop up (towards the top of the page)

**Steps to reproduce:**

**Related code:**

**Other information:**

**Ionic info:**:
cli packages: (/usr/local/lib/node_modules)
    ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:
    cordova (Cordova CLI) : 8.0.0 

local packages:
    ionic/app-scripts : 3.1.8
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:
    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

![problem](https://user-images.githubusercontent.com/32732988/35645401-912204b2-06c3-11e8-8e5e-17c7a937cd53.png)

**Comment by DenisTis** [comment]
I expect similar issue, it is not possible to influence popover behavior. For example, I am able to center ion-select in the middle of the screen, but popover is displayed by the left corner of ion-select div. Does not look good
