### ISSUE TITLE
How to use setFocus() in ionic3

### ISSUE THREAD

**Issue by LakshmanMurthy** [ionic-team/ionic#13921]
Hi

I want to focus after alert or confirm or prompt messages in (blur) or (ionBlur) functions

my html code:
----------------
 <ion-item>
        <ion-input formControlName="scanid" [(ngModel)]="scanid_model" autofocus #myInput (ionBlur)="ScanTextBox_Onchange(scanid_model)"></ion-input>
      </ion-item>

ts code:
--------

this.GlobalFunction.showAlert_New('Select Bin Location !!'); 
   this.scanid_model.setFocus();

if i use '#myInput' id or ng-model 'scanid_model.' facing the prbolem.

could you please help me..

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
