### ISSUE TITLE
After adding the firebaseAnalytics plugin i am unable to Build the Project

### ISSUE THREAD

**Issue by Prudhvirajdandi** [ionic-team/ionic#13936]
Found com.google.android.gms:play-services-auth:+, but version 11.0.+ is needed for the google-services plugin.
Found com.google.android.gms:play-services-identity:+, but version 11.0.+ is needed for the google-services plugin.

:processDebugGoogleServices FAILED

compile "com.facebook.android:facebook-android-sdk:4.+"
compile "com.google.firebase:firebase-core:11.0.+"
compile "com.google.android.gms:play-services-auth:+"
compile "com.google.android.gms:play-services-identity:+"
if Change this to this..
compile "com.facebook.android:facebook-android-sdk:4.+"
compile "com.google.firebase:firebase-core:11.0.+"
compile "com.google.android.gms:play-services-auth:11.0.+"
compile "com.google.android.gms:play-services-identity:11.0.+"

while building its changing to previous one ..could any help me on this please

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
