### ISSUE TITLE
attribute "mode" ignored in the select component on action-sheet interface

### ISSUE THREAD

**Issue by Hanzofm** [ionic-team/ionic#13930]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Ion-select with interface action-sheet ignores the mode attribute fixed on selectOptions attribute

**Expected behavior:**
When I set up the mode to android like this:

```
selectOptions = {
    title: 'title',
    mode: "md"
  };
```

```
<ion-select  [selectOptions]="selectOptions"  interface="action-sheet">
          <ion-option value="value">foo</ion-option>
        </ion-select>
```
The select interface must be showed as android.

**Other information:**
We come from this issue:

https://github.com/ionic-team/ionic/issues/10531

@brandyscarney already tested select and alert modes and reports that action-sheet is the unique mode that not takes care of mode attribute.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.2 
    Node       : v6.10.3
    npm        : 3.10.10 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

```

**Comment by brandyscarney** [comment]
Thanks for the issue! This is fixed in v4.
