### ISSUE TITLE
Error using @ionic/core in another Stencil app

### ISSUE THREAD

**Issue by bitflower** [ionic-team/ionic#13943]
**I'm submitting a ...**  (check one with "x")
[ x ] bug report

**Current behavior:**
npm run dev in the stencil app throws these 2 errors (2 files are missing in the build/npm repo):
```terminal
[ ERROR ]  ENOENT: no such file or directory, stat '/Users/xxx/stencil-app/node_modules/@ionic/core/dist/collection/dependencies/icon/icon.ios.scss'

[ ERROR ]  ENOENT: no such file or directory, stat '/Users/xxx/stencil-app/node_modules/@ionic/core/dist/collection/dependencies/icon/icon.md.scss'
```
Adding empty files is enough to make it "work".

**Expected behavior:**
Dev build starts without error / missing files.

**Steps to reproduce:**
1. npm install @ionic/core
2. Add @ionic/core to stencil.config.ts in the collections property
3. npm run dev

**Related code:**
```javascript
exports.config = {
  collections: [
    {
      name: "@stencil/router"
    },
    {
      name: "@stencil/redux"
    },
    {
      name: "@case-os/ui-kit" // This is the NPM package name of the lib!
    },
    {
      name: "@ionic/core"
    }
  ]
};

```

**Comment by snowyu** [comment]
Confirmed in the IonicHN demo too. After fixed the error `clear` to `fill='clear'`.

**Comment by bitflower** [comment]
Hey @snowyu, I don't understand. How did you fix it? Thanks!

**Comment by aaronksaunders** [comment]
this error happens without use `clear` @snowyu - i am not using `clear` or `fill='clear'`

**Comment by jgw96** [comment]
@bitflower what version of @ionic/core are you running?

**Comment by bitflower** [comment]
@jgw96 these:
```javascript
  "dependencies": {
    "@ionic/core": "0.0.2-30",
    "@stencil/core": "^0.3.0-5"
  }
```

**Comment by jgw96** [comment]
@bitflower can you update to `@ionic/core@0.0.2-48` please?

**Comment by snowyu** [comment]
@jgw96  This error disappeared after updated to @ionic/core@0.0.2-48, but the new error coming on the official [IonicHN demo](https://github.com/ionic-team/ionic-stencil-hn-app):

```
... Uhoh. Got error write EPIPE ...
Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)

```

**Comment by bitflower** [comment]
Hey @jgw96 it worked! Thanks! Gotta stay up to date....

Not sure about closing. @snowyu's problem seems to be another one....

**Comment by jgw96** [comment]
Thanks @bitflower ! Glad the latest fixed your issue (: @snowyu that looks like a separate issue, mind opening an issue on that here https://github.com/ionic-team/stencil ?
