### ISSUE TITLE
Blank screen on preview

### ISSUE THREAD

**Issue by Muzzammil15** [ionic-team/ionic#13944]
![screen shot 2018-02-03 at 01 56 41](https://user-images.githubusercontent.com/26815555/35756711-b501771e-0885-11e8-95a8-8028bf580c56.png)

Can anyone help me with this? 

i am trying to preview my app and getting a blank screen

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
