### ISSUE TITLE
android sdk issue

### ISSUE THREAD

**Issue by sam33r33** [ionic-team/ionic#13950]
Microsoft Windows [Version 10.0.16299.192]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Owner>cd desktop\test\myapp

C:\Users\Owner\Desktop\test\myapp>ionic cordova build android
Running app-scripts build: --platform android --target cordova
[19:13:21]  build dev started ...
[19:13:21]  clean started ...
[19:13:21]  clean finished in 32 ms
[19:13:21]  copy started ...
[19:13:23]  deeplinks started ...
[19:13:23]  deeplinks finished in 500 ms
[19:13:23]  transpile started ...
[19:13:31]  transpile finished in 8.07 s
[19:13:31]  preprocess started ...
[19:13:31]  preprocess finished in 18 ms
[19:13:31]  webpack started ...
[19:13:32]  copy finished in 10.51 s
[19:13:41]  webpack finished in 10.27 s
[19:13:41]  sass started ...
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
[19:13:47]  sass finished in 5.31 s
[19:13:47]  postprocess started ...
[19:13:47]  postprocess finished in 16 ms
[19:13:47]  lint started ...
[19:13:47]  build dev finished in 25.94 s
> cordova build android
Android Studio project detected

ANDROID_HOME=C:\SocketeQ\windowsandroid_root\system\bin\platform-tools
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_161
studio
Subproject Path: CordovaLib
Subproject Path: app
[19:13:54]  lint finished in 7.08 s

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Owner\Desktop\test\myapp\platforms\android\CordovaLib\cordova.gradle' line: 68

* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> No installed build tools found. Install the Android build tools version 19.1.0 or higher.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Owner\Desktop\test\myapp\platforms\android\CordovaLib\cordova.gradle' line: 68

* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> No installed build tools found. Install the Android build tools version 19.1.0 or higher.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

[ERROR] An error occurred while running cordova build android (exit code 1).

C:\Users\Owner\Desktop\test\myapp>

C:\Users\Owner\Desktop\test\myapp>ionic info

cli packages: (C:\Users\Owner\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.6.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\Owner\AppData\Local\Android\Sdk\platform-tools

Misc:

    backend : pro

C:\Users\Owner\Desktop\test\myapp>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of an Android dev tool install / support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
