### ISSUE TITLE
Can i create 1 mb mobile application with ionic 3

### ISSUE THREAD

**Issue by manojbhardwaj** [ionic-team/ionic#13954]
Can i create 1 mb mobile application with ionic 3 and also want to use plugins like social sharing,File,File transfer,network information,Camera,Statusbar etc

**Comment by kensodemann** [comment]
The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. It is neither intended for use as a support forum nor as a place to have general discussions about Ionic. We have both a support forum and a Slack channel that are to be used for that purpose.

Therefore, I am going to close this issue and urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).
