### ISSUE TITLE
Ionic events not working in Lazy Loaded app

### ISSUE THREAD

**Issue by Abhi0725** [ionic-team/ionic#13955]
**Ionic version:** 
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request

**Issue:**
I am using events to notify the app.component whenever a 401 http status code occurs. Now this event is published from a base service provider where 'Events' is injected via `ionic-angular` and has a method which handles any http error.:

          getErrorMessages(errors) {
		if (errors.status == 401) {  //<= unauthorised
			this.toast.present('You need to login first!');
			this.events.publish('app:unauthorised');
			return;
		}
		if (errors.status == 403) {  //<= forbidden
			this.toast.present("Sorry! You are not authorised to access this screen.");
			return;
		}
		if (errors.status == 400) {  //<= Bad Request
			this.toast.present("Invalid entries made.");
			return;
		}

		let error_messages = [];
		if (errors.status == 422) { //<= validation error
			let validation_messages = JSON.parse(errors.text())
			for (var key in validation_messages) {
				if (validation_messages.hasOwnProperty(key)) {
					var messages = validation_messages[key];
					error_messages.push(...messages);
				}
			}
		} else { //<= timeout or http code 500, 405 etc.
			error_messages.push('Technical error occured... please try again later.');
		}
		return error_messages;
	   }

Now, There are several child classes like `auth-service` which is used to get auth user from api. Now if the api returns a 401 error then the parent service will catch this in `getErrorMessages` and will publish the unauthorised error. But unfortunately this isn't happening. Surprisingly though is I publish an event from the constructor of base service then that event is captured in app.component. So I tried to log the 'this' of this.events.publish in service provider getErrorMessages method and found this instead:

`AuthServiceProvider {http: Http, toast: Toast, events: Events, storage: LocalStorage, ENV: "local", …}
ENV
:
"local"
TIME_OUT
:
15000
apiUrlLocal
:
"http://192.168.0.118:8000"
apiUrlProduction
:
"https://dashboard.kidminapp.com"
apiUrlStaging
:
"https://staging.kidminapp.com"
events
:
Events
_channels
:
Array(0)
length
:
0
__proto__
:
Array(0)
__proto__
:
Object
http
:
Http {_backend: XHRBackend, _defaultOptions: BaseRequestOptions}
storage
:
LocalStorage {storage: Storage}
toast
:
Toast {toastCtrl: ToastController}
__proto__
:
ServiceProvider`

This clearly shows that the channels of events attribute is empty array. means no events is being registered. While the case when I directly publish the event from base service the events array isn't empty.

Further note that I am using lazy loading and injecting these services in the pages module rather than the app module.

**EDIT:**

I am subscribing to events in app.component as follows:

   `listenToEvents() {
    console.log('listening events');

    this.events.subscribe('app:unauthorised', () => {
      console.log('user unauthorised take to login page');
      this.storage.clear();
      this.nav.setRoot('LoginPage');
    });

    this.events.subscribe('app:auth_user_fetched', () => {
      console.log('auth_user_fetched event');
      this.getUser();
      this.getpages();
    });
    }`

and calling this listenToEvents() method from the constructor of app.component.

**Sample App** https://github.com/Abhi0725/ionicevents

**Comment by Abhi0725** [comment]
Added a sample app.

**Comment by saumya04** [comment]
@adamdbradley Any update on this?

**Comment by Abhi0725** [comment]
Looks like this is related https://forum.ionicframework.com/t/buildin-publish-subscribe-eventbus-stopped-working-in-lazy-loading-app/97716

**Comment by dsgriffin** [comment]
Did you manage to resolve this? Adding `Events` to `app.component`'s ``providers did nothing for me,
