### ISSUE TITLE
scrollbars not need but displayed, e.g. on ActionSheet, on Windows Chrome

### ISSUE THREAD

**Issue by miloslavskacel** [ionic-team/ionic#13966]
**Ionic version:**  
[ x] **3.9.2**

**I'm submitting a ...** 
[ x] bug report

**Current behavior:**
ActionSheet displays scrollbars.

**Expected behavior:**
ActionSheet does not display scrollbars.

**Steps to reproduce:**
> ionic start myApp tabs

add button to home page, with  presentActionSheet() handler

> ionic serve

in Chrome Version 64.0.3282.140 (Official Build) (64-bit)
scrollbars are displayed:

![scrollbars-actionsheet](https://user-images.githubusercontent.com/2547672/35865713-8b297914-0b55-11e8-9761-5c0565e8945e.png)

**Related code:**

```
  public presentActionSheet() {
    let actionSheet = this.actionSheetCtrl.create({
      title: 'Modify your album',
      buttons: [
        {
          text: 'Destructive',
          role: 'destructive',
          handler: () => {
            console.log('Destructive clicked');
          }
        },
        {
          text: 'Archive',
          handler: () => {
            console.log('Archive clicked');
          }
        },
        {
          text: 'Cancel',
          role: 'cancel',
          handler: () => {
            console.log('Cancel clicked');
          }
        }
      ]
    });

```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\uzimskacel\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

local packages:

    @ionic/app-scripts : 3.1.8
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.1
    npm  : 5.5.1
    OS   : Windows 10

Misc:

    backend : legacy
```

**Comment by miloslavskacel** [comment]
Maybe related to #13763?

**Comment by StefanRein** [comment]
@miloslavskacel No it is not related.

Just add 

`.action-sheet-group {
    overflow: auto;
}`

To reproduce the issue:

`ionic start tabs`
`IonicModule.forRoot(MyApp, {mode: 'md'})`

add to home.html
`<p><button ion-button block (click)="presentActionSheet()">presentActionSheet</button></p>`

Use above code and `actionSheet.present();`

The scrollbars are not visible if you are using the emulator (mac and windows).

![image](https://user-images.githubusercontent.com/4970737/36014175-c7a30940-0d68-11e8-8d38-d6f5405c7ca2.png)

If you are not using the emulator (on windows, or mac with scrollbars always visible) the scrollbars will appear.

**Windows:** 
![image](https://user-images.githubusercontent.com/4970737/36014227-f524af68-0d68-11e8-87a4-9224b0ee9b9a.png)

**Mac (with options for scrollbars always on):**
![image](https://user-images.githubusercontent.com/4970737/36014304-56615a1a-0d69-11e8-80de-43a7dc9f995e.png)

With `overflow: auto`

![image](https://user-images.githubusercontent.com/4970737/36014410-ec938e7c-0d69-11e8-9542-222dbeefe6c6.png)

**Comment by miloslavskacel** [comment]
Thanks. 
The same problem is on class="scroll-content".
There is  a vertical scroll bar on the screenshot.
