### ISSUE TITLE
No hooks Folder found in my root directory

### ISSUE THREAD

**Issue by noor07** [ionic-team/ionic#13963]
hi guyz, my ionic version is=> 

Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.6
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 8.9.4
OS Platform: Windows 10
Navigator Platform: Win32

I write a command ionic start appname, and there is no hooks folder, plz help, cause i have to use the onesignal plugin.

**Comment by brandyscarney** [comment]
This issue was moved to ionic-team/ionic-cli#2977
