### ISSUE TITLE
ion-content show content under ion-header

### ISSUE THREAD

**Issue by suketuvyas** [ionic-team/ionic#13970]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Taken the blank ionic app using ionic pro version is 3.9.1

all content of <ion-content> starts under header and header overlaps 2-3 lines in brower and android decvices

on iphone X content are showing up on status bar of phone and header is overlapping more content.

**Expected behavior:**

Content should display after header

**Steps to reproduce:**

**Related code:**

<ion-header>
  <ion-navbar>
    <ion-title>
      Ionic Blank
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content>
  The world is your oyster.
  <p>
    If you get lost, the <a href="http://ionicframework.com/docs/v2">docs</a> will be your guide.
  </p>

</ion-content>

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by suketuvyas** [comment]
```
 @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.1.4
    npm        : 5.0.3 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

How are you running these apps on your Android and iOS devices? I ask because:

- I don't see any platforms listed in your Ionic Info and would expect the Android and iOS platforms to be there
- When I generate a blank app and run it either on an emulator or a physical device, it looks fine

For iOS, I am doing an `ionic build` and then using Xcode to package the app and load it on my device.

For Android, I am using `ionic cordova run android` to build, package, and load the app on my device.

Thank you for using Ionic

**Comment by legend-oe** [comment]
Hello.
I have the same problem in my project.
I am starting blank ionic start project, doing an ionic build ios. Then start it on my device and emulator (iPhone 6s, iOS 11.2.5) by using Xcode to package the app.
Emulator haven't problem, but on iPhone up part of content (~10px) show under header.
Also I run this app on old Ipad 3 (9.3.5). Ipad haven't this problem.

**ionic info:**
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node  : v8.9.4
    npm   : 5.6.0 
    OS    : macOS High Sierra
    Xcode : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

![simulator screen shot - iphone 6s - 2018-02-09 at 20 13 40](https://user-images.githubusercontent.com/26469560/36041784-b8caada2-0dda-11e8-9e99-04a942ee2c92.png)
![img_6270](https://user-images.githubusercontent.com/26469560/36042151-f0cb733e-0ddb-11e8-8881-5237f2341182.png)

**Comment by legend-oe** [comment]
Additional information. Tested app on device iPhone 5s and 6 (11.2.5). It's worked correct. First app installation.
