### ISSUE TITLE
Can anybody give me an example for modalCtrl.create(ModalClass) with common Component, rather than @IonicPage?

### ISSUE THREAD

**Issue by janckerchen** [ionic-team/ionic#13976]
I  have a specific modal component,  and I dont want to use @IonicPage in isolate module.

is there a demo for it  with ionic3?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
