### ISSUE TITLE
Ionic 3 PWA & Firebase Cloud Messaging (web notifications) article required

### ISSUE THREAD

**Issue by cmer4** [ionic-team/ionic#13987]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
If we develop Ionic 3+ based Progressive Web App (PWA) it is natural that we want to ensure push notifications are also available (subject to browser comptatibility of course. The current leading solution is to leverage FCM - Firebase Cloud Messaging.
As of now there is no documentation or a guide that explains recommended generic way of adding web notifications to Ionic 3+ based PWAs.

There are articles/guide for Angular such as this one: https://angularfirebase.com/lessons/send-push-notifications-in-angular-with-firebase-cloud-messaging/ but since Ionic has its default service worker it is unclear what is recommended implementation path specifically in Ionic 3 and going forward.

**Expected behavior:**
Ionic developer documentation should have a simple recipe type of a guide to implement web notifications based on FCM.

**Comment by cmer4** [comment]
OK I did my first pass and captured the way i did it [here.](https://stackoverflow.com/questions/48669406/ionic-3s-pwa-firebase-cloud-messaging-registration) Maybe I am wrong and good developers already know how to do it;)

**Comment by lzehrung** [comment]
@cmer4 thank you for the guide!

Did you look at using the Ionic Native - Push plugin for web notifications? I'm confused because the plugin claims to support browser as one of the platforms but I can't seem to make it work.

**Comment by cmer4** [comment]
@lzehrung hey, I did look into what existed at the time I did my guide and nothing worked for me either. I am not sure at this point what browser support means for the plugin.

I may give it a try though at some point, but as of now I am just using the web apis hoping Apple will add its support soon;)
