### ISSUE TITLE
Core styles: update default colors

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic#13988]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

Our current colors:

<img width="272" alt="screen shot 2018-02-08 at 11 49 33 am" src="https://user-images.githubusercontent.com/6577830/35986106-2abed21e-0cc6-11e8-88b2-e26ba3d07644.png">

The new colors (per @bensperry):

<img width="268" alt="screen shot 2018-02-08 at 11 49 20 am" src="https://user-images.githubusercontent.com/6577830/35986105-2aad8f04-0cc6-11e8-8e78-78b84414dd78.png">

In code form for easy copy pasta:

```
$primary:         #3880ff;
$secondary:       #0cd1e8;
$tertiary:        #f4a942;
$success:         #10dc60;
$warning:         #ffce00;
$danger:          #f14141;
$light:           #f4f5f8;
$medium:          #989aa2;
$dark:            #222428;
```

This is something that I need to do, but I'd like to wait on this one: https://github.com/ionic-team/ionic/issues/13986

**Comment by bensperry** [comment]
Latest colors for v4:

```
$primary:         #3880FF;
$secondary:       #0CD1E8;
$tertiary:        #7044FF;
$success:         #10DC60;
$warning:         #FFCE00;
$danger:          #F04141;
$light:           #F4F5F8;
$medium:          #989AA2;
$dark:            #222428;
```

**Comment by brandyscarney** [comment]
This has been completed in core :tada:

<img src="https://user-images.githubusercontent.com/6577830/36556661-f0bcdd7c-17d3-11e8-94b9-7cbd97d47d3f.png" width="75%">
