### ISSUE TITLE
ion-searchbar return false even if the value present in JSON array and initialize the values again

### ISSUE THREAD

**Issue by abhinpai** [ionic-team/ionic#13994]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ion-searchbar returns false even if the value present in the JSON array and initialize all the array value again 

**Expected behavior:**
when i search a like name="ABC" this should return true and only ABC value show be show in the view

**Steps to reproduce:**

**Related code:**

 initialize(){
    this.type = "primary";
    this.familyService.loadFamily(this.type)
        .then(data =>{
          this.primaryData = data;
          console.log("Primary data");
          console.log(this.primaryData);
        });
  }

getItems(ev) {
        this.initialize();
        var val = ev.target.value;
        if (val && val.trim() != '') {
          this.primaryData = this.primaryData.filter((item) => {
            console.log(item.display_name.toLowerCase().indexOf(val.toLowerCase()) > -1);
            return (item.display_name.toLowerCase().indexOf(val.toLowerCase()) > -1);
          })
        }
      }

<ion-searchbar (ionInput)="getItems($event)" ></ion-searchbar>  
 <ion-item *ngFor="let primary of primaryData">
        <h2>{{ primary.display_name }}</h2>
        <p>{{ primary.created_at }}</p>
        <button ion-button icon-only clear item-end>
          <ion-icon name="md-chatbubbles" color="primary"></ion-icon>
        </button>
  </ion-item>

**Other information:**

![2018-02-09 4](https://user-images.githubusercontent.com/15942876/36015009-8cb9853c-0d92-11e8-9957-975654a1afb9.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

 @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1
global packages:
    cordova (Cordova CLI) : not installed
local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 browser 5.0.3
    Ionic Framework    : ionic-angular 3.9.2
System:
    Node : v8.7.0
    npm  : 5.6.0
    OS   : Windows 10

**Comment by adamlepkowski** [comment]
The same. Use NgZone to set value in a primaryData property. Workaround but works.
