### ISSUE TITLE
Storage with NG5 will throw StaticInjectorError[Storage] exception

### ISSUE THREAD

**Issue by LaiYao** [ionic-team/ionic#13995]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**

As I use the storage with NG5, I got a StaticInjectorError[Storage] exception, all the code is same as https://ionicframework.com/docs/storage/ described.

**Expected behavior:**

The error should not here.

**Steps to reproduce:**

refer to https://ionicframework.com/docs/storage/

**Related code:**

```
// app.module.ts
@NgModule({
  declarations: [
    // ...
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    IonicStorageModule.forRoot()
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    // ...
  ],
  providers: [
    // ...
  ]
})
export class AppModule {}

// MyPage.ts
import { Storage } from '@ionic/storage';

export class MyPage {
  constructor(private storage: Storage) { }
}
```

**Other information:**

As I google this problem with keyword "angular5 StaticInjectorError", I got many results about it. And from https://github.com/ngrx/platform/issues/549, I take notice of what MattiJarvinen-BA said:

> platformXXXX() no longer accepts providers which depend on reflection. Specifically the method signature went from Provider[] to StaticProvider[].

So I change my code like this:
```
// app.module.ts
@NgModule({
  declarations: [
    // ...
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    IonicStorageModule
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    // ...
  ],
  providers: [
    // ...
    { provide: Storage, useFactory: provideStorage, deps: [{}] }
  ]
})
export class AppModule {}
```
Then the error is gone.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/LeoLai/.npm-global/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node  : v8.4.0
    npm   : 5.6.0
    OS    : macOS Sierra
    Xcode : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by lsoaresesilva** [comment]
I had the same problem. It was caused because I wasn't importing the correct Storage class, which was injected in my page. After I added it, the error was gone:

import { Storage } from '@ionic/storage'; // <-- I missed this, and VisualStudio was not alerting me.

export class MyApp {
  constructor(private storage: Storage) { }
