### ISSUE TITLE
Support for mono-repo structure in ionic scripts

### ISSUE THREAD

**Issue by johneast** [ionic-team/ionic#13999]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request

**Current behavior:**

When working on a system that has multiple apps, all using the same API it is convenient to have all code in a mono-repo rather than one git repo per application. 

Given the following folder structure:
```
|-my-project/
|----apps/
|--------awesome-app1/
|------------(ionic app in here)
|--------awesome-app2/
|------------(ionic app in here)
|----libs/
|--------services/
|------------(shared service code)
|--------model/
|------------(shared model and business logic)
```
It would be good if the package.json file in the `my-project` folder could describe all of the dependencies across all of the apps. This way only one `node_modules` folder in `my-project` would be needed, instead currently each app needs it's own `node_modules`. I know it's possible to have multiple apps in a mono repo, sharing a libs folder and the same `node_modules` folder in angular. It's a shame the benefits are lost as soon as I add an Ionic project into the mono repo

Given that IonicPro requires the app code to be pushed into a git repo in order for it to become available in IonicView, then I'm assuming the above structure won't work with IonicView.

**Comment by brandyscarney** [comment]
This issue was moved to ionic-team/ionic-cli#2988
