### ISSUE TITLE
PWA live broadcast not starting

### ISSUE THREAD

**Issue by kyr0** [ionic-team/ionic#13990]
;-)

<img width="1384" alt="bildschirmfoto 2018-02-08 um 19 01 41" src="https://user-images.githubusercontent.com/454817/35989842-9062e92a-0d02-11e8-9643-abadc283be94.png">

**Comment by cyberundertakor** [comment]
+1

**Comment by MariuszHenn** [comment]
+1

**Comment by kyr0** [comment]
Also the other one is down; https://www.youtube.com/watch?v=iUxbb14MIYo

<img width="1359" alt="bildschirmfoto 2018-02-08 um 19 08 11" src="https://user-images.githubusercontent.com/454817/35990144-76c1f4e2-0d03-11e8-8e79-59405b675e96.png">

**Comment by cyberundertakor** [comment]
WorkAround:

https://www.youtube.com/watch?v=iUxbb14MIYo

**Comment by Yonn-Trimoreau** [comment]
He is probably doing his live alone in front of his computer by now...

**Comment by Artfloriani** [comment]
https://www.youtube.com/watch?v=ooWIY_bnwKs

**Comment by kyr0** [comment]
Epic "Looks like we're having some link Issues" @ https://www.youtube.com/watch?v=iUxbb14MIYo

**Comment by cyberundertakor** [comment]
WorkAround 2

https://www.youtube.com/watch?v=ooWIY_bnwKs

**Comment by kensodemann** [comment]
Please use this link: https://www.youtube.com/c/Ionicframework/live

**Comment by kyr0** [comment]
Yep, this works. Awesome.

**Comment by pablo-gonzalez** [comment]
Ionic Live Straming EPIC FAIL!!! 😂😂😂

**Comment by kensodemann** [comment]
I am going to lock conversation on this but leave it open for a while.
