### ISSUE TITLE
Virtual Scroll Items disappearing when container not at top of page

### ISSUE THREAD

**Issue by Chris1234567899** [ionic-team/ionic#14003]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
When using the virtual scroll in mid page (e.g. below another component), during scrolling down items are disappearing on top, where the above component was located. Scrolling up seems to work properly though.

**Expected behavior:**
All items should be showing in the viewport.

**Steps to reproduce:**
place a virtual scroll below some container element with a certain height

https://plnkr.co/edit/2HBXDHhi7KRbnaEnywN3?p=preview

```
<ion-content padding>

  <ion-card>
    <ion-card-header>
      Placeholder
    </ion-card-header>
    <ion-card-content>
      Wasting space
      <br> Wasting space
      <br> Wasting space
      <br> Wasting space
      <br> Wasting space
      <br> Wasting space
      <br> Wasting space
      <br> Wasting space
      <br> Wasting space
      <br> Wasting space

      <br>
    </ion-card-content>
  </ion-card>

  <ion-list [virtualScroll]="items" approxItemHeight="100px">
    <ion-item style="height:100px;" *virtualItem="let item">
      {{item.id}}: {{item.name}}
    </ion-item>
  </ion-list>


</ion-content>

[...]

items:{id:number,name:string}[]=[];
  ionViewDidLoad() {
     for(let i = 0; i<500; i++){
      this.items.push({id:i, name:"Test"})
    }
  }
```

**Other information:**
![image](https://user-images.githubusercontent.com/12623865/36104354-c84a52e4-0fdf-11e8-8542-bf6c3c4f2a7c.png)

->

![image](https://user-images.githubusercontent.com/12623865/36104443-06433e30-0fe0-11e8-899f-909b29e91c25.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

cli packages: (C:\Users\ADMIN\AppData\Roaming\nvm\v8.9.0\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v8.9.0
    npm               : 5.5.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\ADMIN\AppData\Local\Android\Sdk

Misc:

    backend : legacy
```

**Comment by Chris1234567899** [comment]
While waiting for a solution, a dirty workaround is to put the virtual scroll in an additional ion-content. So something like:
```
<ion-content padding>

  <ion-card>
    <ion-card-header>
      Placeholder
    </ion-card-header>
    <ion-card-content>
      Wasting space
      <br> Wasting space
      <br> Wasting space
      <br> Wasting space
      <br> Wasting space
      <br> Wasting space
      <br> Wasting space
      <br> Wasting space
      <br> Wasting space
      <br> Wasting space

      <br>
    </ion-card-content>
  </ion-card>

  <ion-content>
    <ion-list [virtualScroll]="items" approxItemHeight="100px">
      <ion-item style="height:100px;" *virtualItem="let item">
        {{item.id}}: {{item.name}}
      </ion-item>
    </ion-list>
  </ion-content>

</ion-content>
```

**Comment by TwitchBronBron** [comment]
Any updates on this? Same thing is happening for me.

**Comment by pascalrijk** [comment]
Did anybody find a solution? I have the same problem.

**Comment by lunedam-git** [comment]
Thanks for this. I still had the problem after applying this fix whilst using a custom component above my virtual scroll, but simply wrapping it in a plain div with a defined css height sorted that.

**Comment by sadalsuud** [comment]
I have a same problem ... Here is my ionic info
```

Ionic:

   ionic (Ionic CLI)  : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.10

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (2 plugins total)

System:

   NodeJS : v8.10.0 (/usr/bin/node)
   npm    : 3.5.2
   OS     : Linux 4.15

```
And nothing happen... 

This is my code
```
 <ion-list [virtualScroll]="restaurantes" approxItemHeight="100px">

        <ion-item *virtualItem="let restaurante">
            <img [src]="restaurante.image" />
        </ion-item>

      </ion-list>
```
restaurantes has data

**Comment by pascalrijk** [comment]
Are there any other elements in the dom above your virtual scroll between the ion-content tags?
