### ISSUE TITLE
Implementing 'active' css class on active ion-slide.

### ISSUE THREAD

**Issue by glemiere** [ionic-team/ionic#14000]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[X] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request

**Current behavior:**

Active ion-slide inside ion-slides doesn't get any class to differentiate it from other slides.

**Expected behavior:**

Active ion-slide inside ion-slides should get an 'active' class, so style can be applied without extra code.

**Related code:**
```
<ion-slides>
  <ion-slide class="swiper-slide"></ion-slide>
  <ion-slide class="swiper-slide active"></ion-slide> // <-- Active slide in DOM
  <ion-slide class="swiper-slide"></ion-slide>
</ion-slides>
```

**Comment by jpmasud** [comment]
You can use the (ionSlideDidChange) API on ion-slides, use getActiveIndex() on the ViewChild to see the current active slide, and add a conditional css class using [ngClass] on the ion-slide.

Similar to the example in https://ionicframework.com/docs/api/components/slides/Slides/

**Comment by glemiere** [comment]
Thank you for your answer and your help. That's what I did already but it would have been nice to simply add a style instead, it would just make the code a bit more readable ;-)

**Comment by barcoma** [comment]
Hey, this is exactly what im trying to do atm. 
I am new to Ionic and Angular in general.
Could you maybe show me an example on how to implement this in JS and HTML?

thank you!

**Comment by glemiere** [comment]
Hey!

For some reasons it didn't appear in my console at first, but there is actually a class called "swiper-slide-active" if I remember well. You can check this in your console ;-)

**Comment by paulstelzer** [comment]
Thanks for your issue! This should fixed in latest `@ionic/angular@beta.17`!
