### ISSUE TITLE
Feature Request: Have alerts and input alerts have a default handler on `return`

### ISSUE THREAD

**Issue by AjkP** [ionic-team/ionic#14001]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
Inputs and alert inputs do not have callbacks on the default device keypad's return button. (the button simply dismisses the alert)

**Expected behavior:** (wanted)
Introduce a callback option to an input/alert input.
Another option could be for alert inputs only, to have a button act as "default".

**Steps to reproduce:**
1. Set up an alert like:
```
        let alert = alertCtrl.create({
            title: popup.title,
            subTitle: popup.description,
            inputs: [
              {
                name: 'email',
                placeholder: 'Email',
                type: 'email'
              },
            ],
            buttons: ['OK']
       });
```
2. Clicking on the input from an actual device, gives you the option to "return/submit" the input form.
3. Clicking on the "return/submit" from the device's keypad dismisses the popup with no callback.

EDIT: Looking at the code it seems like the inputs on alerts have a `handler`... though this is undocumented. Will give it a try.

EDIT2: nvm, `handler` didn't work.

**Comment by brandyscarney** [comment]
I'm going to close this issue as it was created against a very old version of Ionic Framework, but if you're still running into it please open a new issue with a code reproduction. Thank you!
