### ISSUE TITLE
@Listen('ionScroll') doesn't fire

### ISSUE THREAD

**Issue by TamoMaez** [ionic-team/ionic#14004]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
`@Listen('ionScroll')` doesn't fire

**Expected behavior:**
Scrolling through (ion) content should fire scrolling event (probably doesn't "bubble")

**Steps to reproduce:**
clone https://github.com/ionic-team/ionic-pwa-toolkit
add  `@Listen('ionScroll') scroller(ev) { console.log(ev) }` to a page

**Related code:**

```
export class AppHome {

  @Listen('ionScroll')
  logger(ev) {
    console.log(ev)
  }
....
render() {
    return (
      <ion-page class='show-page'>
        <ion-content >
         <p style="height:1000px">hei</p>
        </ion-content>
      </ion-page>
    );
....
```

**Comment by manucorporat** [comment]
<ion-content scrollEvents={true}>

In order to receive ionic scroll events
