### ISSUE TITLE
Range: How to increase the knob size?

### ISSUE THREAD

**Issue by venkadesh02** [ionic-team/ionic#14002]
I am using simple ion-range. I want to increase the size of the knob of the ion-range. How to set the width and height of the knob?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
