### ISSUE TITLE
Ionic slide zoom is not working in ionic 3

### ISSUE THREAD

**Issue by noor07** [ionic-team/ionic#14019]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

hey Everyone ionic slider zoom is not woking, please help,

This is my Code:-

```
<ion-slides zoom>
  <ion-slide>
  <img src="asset/img/image name" />  
</ion-slide>
  </ion-slides>
```

And I tried this too:- 

```
<ion-slides zoom>
  <ion-slide>
    <div class="swipe-zoom-cotainer">
  <img src="assets/img/image `name"` />  
  </div>
</ion-slide>
  </ion-slides>

```
Please suggest something....

**Comment by noor07** [comment]
Any Help???

**Comment by anxinghuang** [comment]
@noor07 I got same issues, but my finally solution is setting slides options, you can review [slides docs](http://idangero.us/swiper/api/#zoom)
