### ISSUE TITLE
Ionic 3 html 5 Ios video

### ISSUE THREAD

**Issue by enestdharam** [ionic-team/ionic#14018]
Video is not load in ionic 3. 
I'm using following code
	<video preload="auto" autoplay loop class="video bg-vid" playsinline>
			
				<source src="assets/vid/1-shutterstock_v4503179.mp4" type='video/mp4'>
			</video>

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
