### ISSUE TITLE
event binding navbar (ionOpen) not `emitting event changes`

### ISSUE THREAD

**Issue by davidvalen95** [ionic-team/ionic#14024]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x** 3.19.1
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**

html ngFor array's value not updated when the array is updated inside (ionOpen)="updateArray()" until view is pressed,

its view updated correctly if array was updated inside (click)="updateArray()"

**Expected behavior:**

should capture and update on changes

**Steps to reproduce:**

```html
<ion-menu  (ionOpen)="updateMyMenu()"  [content]="content" *ngIf="userProvider.userSession.isLoggedIn && !rootParams.isPartial" >
  <ion-header>
    <ion-toolbar  >
      <ion-title>Menu</ion-title>
    </ion-toolbar>
  </ion-header>
</ion-menu>

<p *ngFor="let menu of (this.myMenu)">
{{menu.name}} {{menu.badge.count}}
</p>
```

```typescript
//html is already descriptive i guess
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0 browser 5.0.1 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.4.0
    npm        : 5.6.0 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro


```

**Comment by ikbal84** [comment]
Hi,

ionOpen is an attribute. This code should work : 
<ion-menu  [attr.ionOpen]="updateMyMenu()"  [content]="content" *ngIf="userProvider.userSession.isLoggedIn && !rootParams.isPartial" >
  <ion-header>
    <ion-toolbar  >
      <ion-title>Menu</ion-title>
    </ion-toolbar>
  </ion-header>
</ion-menu>

**Comment by stripathix** [comment]
ionOpen is not triggering even for ion-menu
