### ISSUE TITLE
iOS: When ionic keyboard appears, status bar becomes un-overlayed

### ISSUE THREAD

**Issue by Yuripetusko** [ionic-team/ionic#14022]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**
[x] **Plain Cordova**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
on iOS I set `<preference name="StatusBarOverlaysWebView" value="false" />` and using `cordova-plugin-ionic-keyboard` with `<preference name="KeyboardResize" value="true" />` and resize method set to `native`. When keyboard opens, statusbar becomes overlaid. I can fix it by manually calling 

```
window.StatusBar.hide();
window.StatusBar.show();
```

**Expected behavior:**
If I set `<preference name="StatusBarOverlaysWebView" value="false" />` it should remain un-overlayed even when keyboard opens

**Steps to reproduce:**
Install:

`<plugin name="cordova-plugin-statusbar" spec="git+https://github.com/apache/cordova-plugin-statusbar.git" />`
`<plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />`

set following settings 

```
<preference name="StatusBarStyle" value="default" />
<preference name="StatusBarOverlaysWebView" value="false" />
<preference name="KeyboardResize" value="true" />
```

Focus on any input field and observe status bar

**Comment by jotae1e** [comment]
The same happens with IONIC 3.  One workaround is hide statusbar, for example, but is not a solution.  It's very annoying.

**Comment by Yuripetusko** [comment]
There's a fix in one of the forks

 https://github.com/bostondv/cordova-plugin-ionic-keyboard.git#master

**Comment by jotae1e** [comment]
Yes.  It works well.  Thanks a lot.  Nice job. 

I can't understand that is not commited to the master branch.  And, the Ionic Documentation of the Keyboard is a link to a deprecated repository.
