### ISSUE TITLE
Ionic 3 - Slow load tabs first time

### ISSUE THREAD

**Issue by NurGuz23** [ionic-team/ionic#14021]
Hi,

I have problems when I loaded my TabPage for first time, the page stay on blank for 10 seconds! Some can help me?

Thx

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by NurGuz23** [comment]
Sure? I saw that it's pass in a lot of device. Maybe is issue of ionic

2018-02-14 23:35 GMT+01:00 Ken Sodemann <notifications@github.com>:

**Comment by booraik** [comment]
Same issue for me on android. Only android, not ios device
