### ISSUE TITLE
Virtual Scroll error - "Cannot read property 'left' of undefined"

### ISSUE THREAD

**Issue by Chris1234567899** [ionic-team/ionic#14027]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
I'm doing a search on an item array that is displayed in a virtual scroll, so the array is changing a lot. Then and now the app crashes with error "Cannot read property 'left' of undefined". See the full error stack below.

**Related Error:**
```
Uncaught TypeError: Cannot read property 'left' of undefined
    at writeToNodes (virtual-util.js:344)
    at VirtualScroll._stepDOMWrite (virtual-scroll.js:543)
    at virtual-scroll.js:500
    at dispatch (dom-controller.js:139)
    at DomController._flush (dom-controller.js:108)
    at rafCallback (dom-controller.js:101)
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\ADMIN\AppData\Roaming\nvm\v8.9.0\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v8.9.0
    npm               : 5.5.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\ADMIN\AppData\Local\Android\Sdk

Misc:

    backend : legacy
```

**Comment by mebibou** [comment]
Same error here. My template is as follows:
```
<ion-searchbar autocomplete="off" autocorrect="off" spellcheck="false" animated="true"
  [(ngModel)]="searchInput"
></ion-searchbar>

<ion-item-group
    [virtualScroll]="configurations | filterBy:['name','application.name']:searchInput"
    [headerFn]="headerText" approxItemHeight="69px"
  >
```
If typing in the search box quickly (like you would type text normally), the error will appear. Only way is to type slowly...

**Comment by jayands** [comment]
@mebibou have you tried a debounce function as a temporary solution, a la [`lodash.debounce`][debounce]? And post the relevant TS file?

[debounce]: https://css-tricks.com/debouncing-throttling-explained-examples/

**Comment by mebibou** [comment]
@jayands actually there is a `debounce` on the `ionInput` event, so doing this worked:
```
<ion-searchbar autocomplete="off" autocorrect="off" spellcheck="false" animated="true"
  [(ngModel)]="searchInput" (ionInput)="searchValue = searchInput"
></ion-searchbar>

<ion-list [virtualScroll]="configurations | filterBy:['name','application.name']:searchValue">
```

This is a good solution when using `ion-searchbar`, and yes debouncing is the workaround
