### ISSUE TITLE
[feature request] support bootstrap new project using IPFS

### ISSUE THREAD

**Issue by beenotung** [ionic-team/ionic#14039]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
When starting a new project from boostrap template, e.g. `ionic start myapp super`. The cli tools download files from ionicframework.com. This is slow and even impossible under restricted network (e.g. failed 5/5 times in Mainland China)

There is ionic-cli-proxy but it may not solve the problem of mainland users.

**Expected behavior:**
In the cli tool, support extra flag to download required files from local IPFS, or use local archive files if exist.

**Steps to reproduce:**
1. Go to Mainland China (or ssh to one machine in mainland
2. Turn off VPN if any
3. Open terminal
4. Enter `ionic start ipfs-demo super`

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/home/beenotung/.config/yarn/global/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

System:

    Node : v9.5.0
    npm  : 5.6.0 
    OS   : Linux 4.15

Misc:

    backend : legacy
```

**Comment by brandyscarney** [comment]
This issue was moved to ionic-team/ionic-cli#3000
