### ISSUE TITLE
ion-select not functioning properly in vuejs

### ISSUE THREAD

**Issue by aaronksaunders** [ionic-team/ionic#14040]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
no data appears in popup, options are displayed in label and not hidded

**Expected behavior:**
to perform as it does in angular

**Steps to reproduce:**
the code below is used in a vuejs application utilizing ionic frame work components

**Related code:**

[https://jsfiddle.net/ho54hjta/16/](https://jsfiddle.net/ho54hjta/16/)

```html
<div id="app">
  <ion-page>
    <ion-header>
      <ion-toolbar class="toolbar-md-primary">
        <ion-title>TodoList</ion-title>
      </ion-toolbar>
    </ion-header>
    <div class="content">
      <p>{{ count }}</p>
      <p>
        <button @click="increment">+</button>
        <button @click="decrement">-</button>
      </p>

      <ion-item>
        <ion-label><strong>Filter On Favorite Type</strong></ion-label>
        <ion-select >
          <ion-option v-for="f in optionValues" :key="f.id" :value="f.name">
            <ion-label full style="color:black">{{f.name}}</ion-label>
          </ion-option>
        </ion-select>
      </ion-item>
    </div>

  </ion-page>
</div>
```

**Comment by aaronksaunders** [comment]
I solved this, I found the actual documentation for the component.

https://github.com/ionic-team/ionic/tree/core/packages/core/src/components/select

**Comment by paritosh149** [comment]
The url returns 404 error.
