### ISSUE TITLE
Splitpane not working in phone view mode , working fine in browser

### ISSUE THREAD

**Issue by afzal415** [ionic-team/ionic#14048]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The ion-spit pane is not working properly. In browser mode when the screen is big , the split pane is working good. When the screen size is reduced , i am not able to see the menu itself or the menu toggle button. In the ionic serve --lab mode , the screen is blank white screen.

**Expected behavior:**
menu should be toggled when in small screen and should not be blank white screen in ionic serve --lab mode

**Steps to reproduce:**

**Related code:**
<ion-split-pane>
![code snip shot](https://user-images.githubusercontent.com/27876738/36405916-33075aba-162e-11e8-85dd-132436a201e4.PNG)

![mobile view](https://user-images.githubusercontent.com/27876738/36405736-257a6686-162d-11e8-8016-ac87d665e587.PNG)
![browser big screen](https://user-images.githubusercontent.com/27876738/36405738-25fd3426-162d-11e8-98ff-ed3bb5b4b9df.PNG)
![browser small screen](https://user-images.githubusercontent.com/27876738/36405739-2675c63e-162d-11e8-8a88-03bff42662e5.PNG)

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.6.0
    OS   : Windows 7
```
insert the output from ionic info here
```

**Comment by jwt02180** [comment]
From what I can see, the first issue could be that you have your `menuToggle` button in the wrong place (header of the side menu). This should be placed in the header of any page that would be shown inside the `#someContent` nav.

Also unless you have navigation inside your side menu, I'm unsure why you have an `ion-navbar` present.

As for the blank screen, I'm not sure what to say without more information there.
