### ISSUE TITLE
Navigating to a page with no tabs still shows tabs

### ISSUE THREAD

**Issue by ix-xerri** [ionic-team/ionic#14053]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Running an Ionic application using 3.9.2 and it the app where there are tabs and a login page where there are no tabs. When I logout, I navigate to the login page using `this.navCtrl.setRoot("LoginPage");` but the tabs still show on the login page.

**Expected behavior:**

The tabs should not start showing on the login page.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (xxx)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v8.9.4
    npm        : 5.6.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by lonwi** [comment]
Just try to use the root navigation instead like this maybe...
`import { App } from 'ionic-angular';`
and then
`this.app.getRootNavs()[0]. setRoot('Page')`
