### ISSUE TITLE
scrollbars not showing in android (blank project, API 27, no crosswalk)

### ISSUE THREAD

**Issue by chriswep** [ionic-team/ionic#14055]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
When running in Android (via Cordova) scrollbars are never shown while scrolling

**Expected behavior:**
A scrollbar should appear on the right while the user is moving the content within a scroll container (ion-content, ion-scroll)

**Steps to reproduce:**
- create new ionic project, template "super" (or "conference" without crosswalk)
- ionic cordova run android (i'm using API 27 emu)
- scrollbars are not showing while scrolling within the emulator

**It works in ...**
- with the crosswalk plugin
- iOS (although i have the same behaviour on some pages in my production app. but the ionic conference starter does scroll)
- Google Chrome Canary (others not tested)
- Safari (ionic "conference" template)

**Also doesn't work in ...**
- Safari (ionic "super" template, e.g. "Items" list)

**Comment by jorrete** [comment]
Hi,
Is there any progress/solution on this issue?
Thanks.
