### ISSUE TITLE
java.lang.RuntimeException: Unable to pre-dex

### ISSUE THREAD

**Issue by dhavaljivani** [ionic-team/ionic#14050]
Application working fine when I am build and run but I am facing below error when generate release APK using **ionic cordova build --release android** command 

```
Execution failed for task ':transformClassesWithPreDexForRelease'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException
: java.lang.RuntimeException: Unable to pre-dex 'C:\Users\Dhaval\.gradle\caches\
modules-2\files-2.1\xerces\xmlParserAPIs\2.6.2\65acede1e5305bd2b92213d7b5761328c
6f4fd9\xmlParserAPIs-2.6.2.jar' to 'E:\Relax.java\application\SanManDriverIonicO
ldDesign\platforms\android\build\intermediates\transforms\preDex\release\32.jar'
```

**Full stack trace :**

trouble processing "javax/xml/namespace/QName.class":
Ill-advised or mistaken usage of a core class (java.* or javax.*)
when not building a core library.
This is often due to inadvertently including a core library file
in your application's project, when using an IDE (such as
Eclipse). If you are sure you're not intentionally defining a
core class, then this is the most likely explanation of what's
going on.
However, you might actually be trying to define a class in a core
namespace, the source of which you may have taken, for example,
from a non-Android virtual machine project. This will most
assuredly not work. At a minimum, it jeopardizes the
compatibility of your app with future versions of the platform.
It is also often of questionable legality.
If you really intend to build a core library -- which is only
appropriate as part of creating a full virtual m

**Comment by FdezRomero** [comment]
Hi @dhavaljivani! Are you still having this problem? Can you run the `ionic info` command from your project folder and paste the output here so we can have more information about your environment? Thanks.

**Comment by UISTRepo** [comment]
Im having the same issue. cordova build works fine, but cordova build --release does not.
Here is my ionic info

`cli packages: (/home/tunte/WebProjects/Spot/dogwalkmobileapp/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    Cordova Platforms : android 6.4.0
    Ionic Framework   : ionic1 1.2.4

System:

    Node : v8.10.0
    npm  : 5.6.0 
    OS   : Linux 4.13

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
`

**Comment by FdezRomero** [comment]
@UISTRepo Can you paste your error output? Thanks.

**Comment by UISTRepo** [comment]
Its identical as dhavaljivani reported it above, only the paths are different because i use Linux.
I solved it by downgrading cordova android platform from 6.4.0 to 6.3.0.
This was caused by mauron85 background geolocation plugin.

Everything was fine when you build it for debug, but when you build it for release it throws that error.

**Comment by FdezRomero** [comment]
@UISTRepo Then the problem seems to be related to `cordova-plugin-mauron85-background-geolocation` and not Ionic.

@dhavaljivani Are you also using this plugin? If not, what are the plugins you're using? You can paste the output of `cordova plugin ls`.

**Comment by aelshemy16** [comment]
@FdezRomero Same Issue here

`> cordova plugin ls
call-number 0.0.2 "Cordova Call Number Plugin"
com.synconset.imagepicker 2.1.8 "ImagePicker"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 1.4.5 "cordova-googlemaps-plugin"
cordova-plugin-googleplus 5.2.1 "Google SignIn"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.6.0 "Toast"
cordova.plugins.diagnostic 3.9.1 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.10.6 "PushPlugin"
twitter-connect-plugin 0.6.0 "Twitter Connect"`

**Comment by aelshemy16** [comment]
> > cordova plugin ls
call-number 0.0.2 "Cordova Call Number Plugin"
com.synconset.imagepicker 2.1.8 "ImagePicker"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 1.4.5 "cordova-googlemaps-plugin"
cordova-plugin-googleplus 5.2.1 "Google SignIn"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.6.0 "Toast"
cordova.plugins.diagnostic 3.9.1 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.10.6 "PushPlugin"
twitter-connect-plugin 0.6.0 "Twitter Connect"

**Comment by FdezRomero** [comment]
@aelshemy16 You have some plugins that have been deprecated and are no longer necessary, like `cordova-plugin-compat` and `cordova-plugin-console`: https://cordova.apache.org/news/2017/09/22/plugins-release.html

Can you post of the output of `ionic info`?

Thanks
