### ISSUE TITLE
Documentation for lists inside of cards is contradictory/unclear

### ISSUE THREAD

**Issue by orasestravis** [ionic-team/ionic#14064]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

This is a bug in the documentation.

See "Lists In Cards": https://ionicframework.com/docs/components/#card-list

The docs say "Add an `ion-list` component inside of the `ion-card-content` to display a list".

However, the sample markup immediately below this sentence does *not* include an `ion-card-content` element – the `ion-list` is nested directly inside of the `ion-card`.

Should the `ion-list` be wrapped inside of an `ion-card-content`, or shouldn't it?

Experimentation suggests that a `ion-card-content` should *not* be used, but I'm not certain what's intended.

**Expected behavior:**

I expect the documentation to be self-consistent.

**Comment by brandyscarney** [comment]
This issue was moved to ionic-team/ionic-site#1326
