### ISSUE TITLE
Unable to build sample project

### ISSUE THREAD

**Issue by geraldapeoples** [ionic-team/ionic#14063]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
I installed the latest cordova and ionic as per instructions.
I installed the latest android studio.
I created a new sample project.
I added the android platform
I attempted to build the project and it fails with the error "(node:2855) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Could not find an installed version of Gradle either in Android Studio,
or on your system to install the gradle wrapper. Please include gradle 
in your path, or install Android Studio"

**Expected behavior:**
I expect the project to build

**Steps to reproduce:**
Install as per usage instructions, create app as per guide, attempt to build project.

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

**Comment by davec21** [comment]
Make sure you install the latest android platform.

`cordova platform add android@latest`

Google likes to move SDKs around and the default cordova android is old.
