### ISSUE TITLE
Ionic Geolocation either highly accurate or very wrong...

### ISSUE THREAD

**Issue by SimonKomlos** [ionic-team/ionic#14074]
I'm using Ionic and geolocation to get the users coordinates. What I've found is that it's either really accurate or not at all.. Off by 10km or by 30 meters.. 

This first picture is the **NOT accurate** results: 

[![enter image description here][1]][1]

The first lat/long is the user location and the second line under it is the lat/long of a landmark. The value below that is the meters away from each other. 

As you can see from the first set, geolocation thinks I'm 11km away from this landmark, even though I am only 1km away. 

Here is a different picture with the **accurate** results:

[![enter image description here][2]][2]

Much better, and using the ionic `coords.accuracy` returns `30` meters away for the accurate one, but something like `47000` for the non-accurate one. For both of these tests I was in the exact same position. The coordinates seem to change randomly every 10-20 minutes..

Here is my code:

      let userLocation = {lat: 0, lng: 0}

      this.geolocation.getCurrentPosition({enableHighAccuracy: true}).then((resp) => {
         userLocation.lat = resp.coords.latitude;
         userLocation.lng = resp.coords.longitude;
         console.log(resp.coords.accuracy)
      }).catch((error) => {
        console.log('Error getting location', error);
      });

      getDistance(userLocation, {lat: 35.904912, lng: -79.046913}) //calling the function that returns the distance between each point in meters

      var rad = function(x) {
        return x * Math.PI / 180;
      };

      var getDistance = function(p1, p2) {
        var R = 6378137; // Earth’s mean radius in meter
        var dLat = rad(p2.lat - p1.lat);
        var dLong = rad(p2.lng - p1.lng);
        var a = Math.sin(dLat / 2) * Math.sin(dLat / 2) +
          Math.cos(rad(p1.lat)) * Math.cos(rad(p2.lat)) *
          Math.sin(dLong / 2) * Math.sin(dLong / 2);
        var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
        var d = R * c;
        return d; // returns the distance in meter
      };

Is there a way to make this more accurate? Or rather, just show the accurate one? The geolocation seems to randomly change every few minutes.. 

I also made a stackoverflow post for this: https://stackoverflow.com/questions/48964064/geolocation-highly-accurate-at-times-but-very-wrong-at-other-times

  [1]: https://i.stack.imgur.com/NQuPU.png
  [2]: https://i.stack.imgur.com/nmRbZ.png

**Comment by m-cameron** [comment]
Can Ionic support [IP2Location LITE](https://lite.ip2location.com)? It is a free geolocation database with good accuracy.

**Comment by SimonKomlos** [comment]
@m-cameron I don't think that is helpful in this situation.. Geolocation should be fairly accurate as it is.. I'm not saying down to the meter, but definitely not 10km off..

**Comment by lolaswift** [comment]
@SimonKomlos Have you found any solution? I noticed that I am having the same issue!
