### ISSUE TITLE
Zoom not working in ion-scroll v3.9.2

### ISSUE THREAD

**Issue by praveenraji2i** [ionic-team/ionic#14088]
<ion-scroll zoom="true">-Tag won't seem to allow zoom ion-content
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

```
<ion-scroll scrollX="true" scrollY="true" zoom="true" maxZoom="10" style="height: calc(100vh - 230px)">
</ion-scroll>
```

**Comment by tgirgin23** [comment]
Seeing the same issue on my end

**Comment by lucashsilva** [comment]
Any updates about this?
