### ISSUE TITLE
The ion-range web component doesn't fire the ionChange event when using the keyboard

### ISSUE THREAD

**Issue by richardruiter** [ionic-team/ionic#14090]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

When you focus a `ion-range` component using the tab key and then hit the right arrow key `ionChange` is not fired.

**Expected behavior:**
The `ionChange` event should be fired when using the keyboard as well.

**Steps to reproduce:**

Focus the input field. Then press tab and use the arrow keys. The input is not updated.

**Related code:**
```
	<input type="number" id="demo-input"></input>
	<ion-range id="demo" min="0" max="100" value="0"></ion-range>
	<script>
		(function () {
			var slider = document.querySelector('#demo');
			var input = document.querySelector('#demo-input');
			slider.addEventListener('ionChange', function (e) { input.value = e.detail.value; });
			input.addEventListener('input', function (e) { slider.setAttribute('value', e.target.value); });
		}());
	</script>
```

**Comment by paulstelzer** [comment]
Is this issue still exist in beta.17?

**Comment by manucorporat** [comment]
Duplicated of https://github.com/ionic-team/ionic/issues/13978
