### ISSUE TITLE
<ion-content> goes behind <ion-header> in Ionic.

### ISSUE THREAD

**Issue by pnnrahul** [ionic-team/ionic#14092]
`<ion-header> <ion-navbar> <ion-title>Physics</ion-title> </ion-navbar> </ion-header> <ion-content padding has-header contentTop="200px"> <ion-list class="chapter-list"> <button ion-item no-padding *ngFor="let chapterList of chapterLists" (click)="chapterListItemClk(event)" no-border> {{ chapterList.video_name }} <img src="{{chapterList.video_icon}}" item-left alt=""> </button> </ion-list> </ion-content>`
@ATakaSKY @falasvand
![localhost_8100_ nexus 6](https://user-images.githubusercontent.com/34025235/36838285-c7c35306-1d64-11e8-8bf3-3f73f2490cbb.png)
![localhost_8100_ nexus 6 1](https://user-images.githubusercontent.com/34025235/36838286-c7fcd0ea-1d64-11e8-88da-98904175db7c.png)
`<ion-content>` is hidden behind `<ion-header>`
My ionic version is 3.19.1
I have tried 'has-header' as well.
But not fixed.
@camwiegert 
My code above. #7084 
[https://forum.ionicframework.com/t/ion-content-is-hiding-behind-ion-header/123048](url)

**Comment by janpio** [comment]
Why do you mention me here to subscribe to this topic?
This is inappropriate and impolite.

**Comment by pnnrahul** [comment]
@janpio For help.

**Comment by janpio** [comment]
And why do you think it is appropriate to mention random people then?
It is not.

**Comment by pnnrahul** [comment]
This is not you fb account plzzz........
if u don't know answer 
BUZZ OFF!!!!!!!!!
commenting like shits!!!!

**Comment by janpio** [comment]
Good luck getting help with your problem 🥇

**Comment by pnnrahul** [comment]
Thanks!!!

**Comment by pnnrahul** [comment]
Fixed
