### ISSUE TITLE
Cannot read property 'scrollToBottom' of undefined

### ISSUE THREAD

**Issue by ragod123** [ionic-team/ionic#14098]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In my chat application i am using scrollToBottom to scroll the chat content to the bottom.
i am using google chrome browser for output of my application but its showing me " ERROR TypeError: Cannot read property 'scrollToBottom' of undefined at ChatPage.webpackJsonp.56.ChatPage.ionViewDidEnter (chat.ts:45)" in the console.

**Expected behavior:**
this.content.scrollToBottom() should scroll it to the end of the ion-content.

**Steps to reproduce:**

**Related code:**

import { Component, ViewChild } from '@angular/core';

export class ChatPage {

  @ViewChild('ChatScroll') ChatScroll: Content;

constructor(public navCtrl: NavController, public navParams: NavParams) {
  }
  ionViewDidLoad() {
    console.log('ionViewDidLoad ChatPage');
  }

  ionViewDidEnter(){
    this.ChatScroll.scrollToBottom();//300ms animation speed
    //console.log('ionViewDidEnter ChatPage');
  }

}

**Comment by jayands** [comment]
Silly question: what are you importing from? is your code _exactly_ that, or do you have the right import line?

**Comment by paulstelzer** [comment]
Issue should fixed, if not please open a new issue
