### ISSUE TITLE
Toolbar and Searchbar combo looks weird in iOS

### ISSUE THREAD

**Issue by danbucholtz** [ionic-team/ionic#14104]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I use this mark-up, it looks weird on iOS. This is with the `next` release of `@ionic/core`, no custom css.
![screen shot 2018-03-02 at 4 47 02 pm](https://user-images.githubusercontent.com/4680488/36925630-673af07c-1e39-11e8-8096-3d31c05c1bbb.png)

```
<ion-header>
        <ion-toolbar>
          <ion-title>Unsplash</ion-title>
          <ion-searchbar place-holder="Surfing" ></ion-searchbar>
        </ion-toolbar>
      </ion-header>
```

**Expected behavior:**
It to look a lil' bit better 🤠 

Thanks,
Dan

**Comment by brandyscarney** [comment]
Hey! 🙂 

Placing both a title and a searchbar in the same toolbar is not currently supported. You can try something like this:

```
<ion-header>
  <ion-toolbar>
    <ion-title>Unsplash</ion-title>
  </ion-toolbar>
  <ion-toolbar>
    <ion-searchbar placeholder="Surfing"></ion-searchbar>
  </ion-toolbar>
</ion-header>
```

Note that `placeholder` doesn't have a dash in it:

![screen shot 2018-03-09 at 11 48 12 am](https://user-images.githubusercontent.com/6577830/37218884-c7473c2c-238f-11e8-994e-1d04cdbe977e.png)

Thanks!
