### ISSUE TITLE
Unit Tests Break with Latest @ionic/angular Version

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic#14112]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ x] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**

Repo: https://github.com/kensodemann/test-blank
I have a blank v4 project with the following modifications:

1. inject Platform service in `app.component.ts`
1. provide a mock platform in `app.components.spec.ts`

With the latest version of `@ionic/angular`, I get the following with `npm test`:

```
Chrome 64.0.3282 (Mac OS X 10.13.3) ERROR
  {
    "message": "Uncaught Error: ionic.js script missing from index.html
at http://localhost:9877/_karma_webpack_/vendor.bundle.js:769:5
Error: ionic.js script missing from index.html\n    at Object.../../../../@ionic/angular/dist/index.js (http://localhost:9877/_karma_webpack_/vendor.bundle.js:769:11)
    at __webpack_require__ (http://localhost:9877/_karma_webpack_/inline.bundle.js:55:30)\n    at Object.../../../../../src/app/app.component.spec.ts (http://localhost:9877/_karma_webpack_/main.bundle.js:59:17)
    at __webpack_require__ (http://localhost:9877/_karma_webpack_/inline.bundle.js:55:30)\n    at webpackContext (http://localhost:9877/_karma_webpack_/main.bundle.js:10:9)
at Array.map (<anonymous>)\n    at Object.../../../../../src/test.ts (http://localhost:9877/_karma_webpack_/main.bundle.js:194:16)
    at __webpack_require__ (http://localhost:9877/_karma_webpack_/inline.bundle.js:55:30)
    at webpackJsonpCallback (http://localhost:9877/_karma_webpack_/inline.bundle.js:26:23)
    at http://localhost:9877/_karma_webpack_/main.bundle.js:1:1",
```

Rolling back to version `0.0.2-28` (npm i @ionic/angular@0.0.2-28) results in a properly working test.

So:

1. `npm i`
1. `npm test` - broken
1. `npm i @ionic/angular@0.0.2-28`
1. `npm test` - works
1. `git checkout -- .`
1. `npm i`
1. `npm ls @ionic/angular` - shows 0.0.2-29
1. `npm test` - broken again

**Expected behavior:**

Should work, or we need to document a modified unit test setup.

**Steps to reproduce:**

**Related code:**
https://github.com/kensodemann/test-blank

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
~/Projects/Home/test-blank (master): ionic info
cli packages: (/usr/local/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-alpha.f69a036f
   ionic (Ionic CLI) : 4.0.0-alpha.f69a036f

local packages:

   @angular/cli    : 1.6.8
   @ionic/core     : 0.0.4-1
   Ionic Framework : @ionic/angular 0.0.2-29

System:

   Node : v8.9.0
   npm  : 5.6.0 
   OS   : macOS High Sierra
```

**Comment by adamdbradley** [comment]
Fixed: https://github.com/ionic-team/ionic/commit/aa91d117268cd0c02ed1a38442e2c01cfdad9451 thanks
