### ISSUE TITLE
The world is not currently my oyster with v4 blank starter

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic#14113]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The home page on the v4 blank starter is blank even though the content in the HTML is not.

**Expected behavior:**

The world should be my oyster.

**Steps to reproduce:**

1. clone this repo: https://github.com/kensodemann/test-blank & npm i  (or use ionic@canary to create your own)
1. ionic serve
1. deal with sadness when you see blank content on page :(
1. open `src/app/pages/home/home.page.html` and remove `ion-page` tags
1. rejoice greatly as the world is now your oyster

I have no idea if this is an issue with the `ionic-page` tags themselves or if we should just remove them from the template and not use them.

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
~/Projects/Home/test-blank (master *): ionic info
cli packages: (/usr/local/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-alpha.f69a036f
   ionic (Ionic CLI) : 4.0.0-alpha.f69a036f

local packages:

   @angular/cli    : 1.6.8
   @ionic/core     : 0.0.4-1
   Ionic Framework : @ionic/angular 0.0.2-29

System:

   Node : v8.9.0
   npm  : 5.6.0 
   OS   : macOS High Sierra
```

**Comment by brandyscarney** [comment]
This might have been caused by @dwieeb's changes to the starter for v4. `ion-page` is no longer needed for v4 so if that is the case it can be removed.
