### ISSUE TITLE
BUILD --prod --release FAILED: Execution failed for task ':app:transformClassesWithStackFramesFixerForRelease'.

### ISSUE THREAD

**Issue by francovp** [ionic-team/ionic#14110]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
"ionic cordova build android --prod --release" failed

**Expected behavior:**
Build successfull

**Steps to reproduce:**
Run "ionic cordova build android --prod --release" command

**Other information:**
```
BUILD FAILED in 14s

36 actionable tasks: 3 executed, 33 up-to-date
(node:4784) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithStackFramesFixerForRelease'.
> java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
```

Stack trace

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\fvale\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 7.0.0 browser 5.0.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\fvale\AppData\Local\Android\sdk

Misc:

    backend : pro
```

**Comment by francovp** [comment]
Update: I fixed it by installing the android platform, witch is super weird because ``ionic cordova build android`` and ``ionic cordova build android --prod`` works just fine.

Well

**Comment by brandyscarney** [comment]
Closing this since it has been fixed. Please open a new issue if you run into problems again. Thanks!
