### ISSUE TITLE
Ionic's live reload showing an older version of the page in the browser.

### ISSUE THREAD

**Issue by Natanael1234** [ionic-team/ionic#14121]
**Ionic version:**  
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ x] **4.x** (version in package.json. Ionic CLI version is 1.3.19.1)

**I'm submitting a ...**
[X ] bug report
[ ] feature request

**Current behavior:**
Sometimes, when I change and save a layout, component, page or class, the version of the application showing in the browser is an older version that the one showning a minute ago.

Sometimes I need to save other file related to the file failing or need to restart ionic server so that I get the most recent version of the page.

Sometimes it just don’t get updated during so much time that it is making my work impossible.

I tried to reinstall Visual Studio Code, Ionic CLI, NodeJS and NPM but it don’t solved the problem. The version of NodeJS don’t affects it.

To me, the error appears just after I start the live reload server and still appears after I restart the server.

Sometimes it shows a version of code modified days ago.

Months ago it was not a so frequent problem…

The problem don’t happens only form me. Here where I work, other people are facing the same problem in projects created from the ground.

I’m not sure about that, but it’s like if Ionic Projects keeps cache of older versions of the code and, sometimes, loses itself to show the correct version.

How can I get Ionic App update at every change?

**Expected behavior:**
When any file in src folder is modified and saved the live reload must reflect the most recent version of this changes in the browser.

**Steps to reproduce:**
Change and save some file in a Ionic project's src folder. For example, a template.
Wait the live reload update the page in the browser.
See an older version of the page (sometimes).
Save the file again or save some related file (for example, the class of a page related to a template).
Wait the live reload update the page in the browser.
See the newer version of the page (sometimes).

**Comment by comfortme** [comment]
welcome to the club
https://github.com/ionic-team/ionic-app-scripts/issues/363

**Comment by brandyscarney** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1410
