### ISSUE TITLE
Setting root page on back button (bug)

### ISSUE THREAD

**Issue by MiguelHernandezCh** [ionic-team/ionic#14135]
**Ionic version:**  

[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
I have a list on a page with tabs, when I select an item I go the details page, when I click the back button the root page changes and the back button disappears. 
I'm not doing anything extra on the back button, only happening in iOS

![ezgif-1-47a83ce64a](https://user-images.githubusercontent.com/22020959/37142444-bfb9b5ec-227d-11e8-946f-b2a9af77b9a1.gif)

**Ionic info:** 

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.9.3
    npm        : 5.6.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : Users/gobae/Library/android/sdk

Misc:

    backend : pro


```

**Comment by kensodemann** [comment]
It is really hard to tell from the animation above what is going on but it looks like:

1. start on list page
1. click on Sitio Hospital Civil
1. details page open
1. click on back button
1. list page shown for a little bit
1. page switches to Sitio Hospital Civil page again without anyone touching anything

That last bit is the problem you are reporting, that the app should be showing the list page after the back button is hit but is instead switching back to the detail page after showing the list page for a short bit. Is that correct? If not, can you please clarify?

Either way, can you also please provide a sample application via GitHub that demonstrates this issue?

**Comment by MiguelHernandezCh** [comment]
Yes that's exactly what is happening, and also removes the tabs. And do you need a whole project or just the code of the list and the details page?

**Comment by MiguelHernandezCh** [comment]
I created updated ionic, created a new project and migrated `/src` directory and carefully installed al plugins and dependencies. It works now.
