### ISSUE TITLE
Support for textarea in alert

### ISSUE THREAD

**Issue by fareshan** [ionic-team/ionic#14153]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The Alert.create() doesn't support multine inputs ( textarea )

**Expected behavior:**
Create an alert and add something like:
`alert.addInput({
      type: 'textarea',
      name: 'about',
      placeholder: 'Optional message'
    });`

**Other information:**
related issue:
https://github.com/ionic-team/ionic/issues/8125
by SebastianGiro

**Comment by AgusFran** [comment]
+1

**Comment by tryadelion** [comment]
+1

**Comment by shazadmaved** [comment]
+1

**Comment by nokturnal** [comment]
+1

**Comment by tawfiek** [comment]
I  will work on that.

**Comment by robingenz** [comment]
Any updates?

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been added via https://github.com/ionic-team/ionic/pull/16851 and will be available in an upcoming release of Ionic Framework.
