### ISSUE TITLE
config ionic_www_dir

### ISSUE THREAD

**Issue by milanjya** [ionic-team/ionic#14152]
ionic_www_dir default is www,
for some reason,i config it to another folder,
then i do 'sudo ionic cordova platform add ios',
i found there was no www files in 'platforms-ios-www' folder.
how can i solve it?
all those will all right when i delete my ionic_www_dir config.

**Comment by brandyscarney** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1409
