### ISSUE TITLE
bug(fonts): built version has no text on android

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#14162]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When building for production:
![image](https://user-images.githubusercontent.com/5757359/37370082-cb1723da-2713-11e8-97b7-1d9e21de7994.png)

On ionic view you can see the text, but in production Cordova build either manually or ionic pro cloud build, text does not seem to exist.

**Expected behavior:**
See the text on android

**Other information:**
Device: Meizu Pro 7+

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Tested on ionic pro as well.
```
li packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0 
    OS                : macOS High Sierra

Environment Variables:

    ANDROID_HOME : /Users/eliyacohen/Library/Android/sdk/

Misc:

    backend : pro
```

**Comment by Newbie012** [comment]
It happens even without production.

**Comment by mhartington** [comment]
@AmitMY Can you provide a test app to look at? I'm not able to replicate
