### ISSUE TITLE
Scrollbars showing on alerts even when the content is not scrollable

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic#14178]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

On a desktop device:
- Add a favorite in the ionic-stencil conf app
- Remove that favorite
- Notice the confirmation alert has a scrollbar

![scrollbar](https://user-images.githubusercontent.com/8823093/37531803-396a660a-290b-11e8-8d8c-2f862dab7ffa.png)

**Expected behavior:**

There would not be a scrollbar since that content is not actually scrollable

**Steps to reproduce:**

On a desktop device:
- Add a favorite in the ionic-stencil conf app
- Remove that favorite
- Notice the confirmation alert has a scrollbar

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by paulstelzer** [comment]
Scrollbars are still showing in beta.17 ;)

**Comment by abennouna** [comment]
Please merge 🙏 it's not sexy at all in Windows 😒

**Comment by liamdebeasi** [comment]
Hi there,

This has been fixed via https://github.com/ionic-team/ionic/pull/16767 and will be in the next release of Ionic.

We appreciate your patience!
