### ISSUE TITLE
Nav events not firing when switching tabs

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic#14179]
Using the conference app as an example. 

Given an event listener for `ionViewDidEnter` on the Schedule page

>page-schedule/page-schedule.tsx

```ts
  @Listen('ionViewDidEnter')
  viewDidEnter(e){
    console.log(e)
  }
```

When first loading the page, the event is fired. But if you change tabs and then navigate back to the schedule page, the event will not fire again.

**Comment by TomDemulierChevret** [comment]
Any update on this ?

**Comment by paulstelzer** [comment]
@mhartington I close this here because I think this issue is better for it -> #14566
