### ISSUE TITLE
Back button is not the correct color in MD mode

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic#14177]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The back button should be white in MD mode and black in iOS mode. Currently, the back button is black in both modes. This is happening because the back button is not using the same color as regular bar buttons.

**Expected behavior:**

The back button would be white in MD mode and black in iOS mode.

**Steps to reproduce:**

- pull down the master branch of the ionic-stencil conf app
- run it in chrome with device mode and notice that on Android devices the color is not correct but in iOS devices, it is (I can also reproduce on an actual device)

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
Reopening this to fix ios
