### ISSUE TITLE
No option to change ion-backdrop opacity, hardcoded values within animation functions. 

### ISSUE THREAD

**Issue by joe-scotto** [ionic-team/ionic#14189]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Value is hardcoded to `0.08` within the animation functions located at: https://github.com/ionic-team/ionic/tree/d37623a2caaad64f66f1e008c6f8411c6bf8642a/core/src/components/popover/animations

**Expected behavior:**
Should have the option to define a variable that controls the opacity of `ion-backdrop`

**Comment by Mushr0000m** [comment]
Same for modals etc. When your have a dark app you need a stronger opacity... Having it hardcoded is a problem.
