### ISSUE TITLE
ionViewCanEnter no work 

### ISSUE THREAD

**Issue by davidoween** [ionic-team/ionic#14183]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Before running the guard, load the page for a few moments

**Expected behavior:**
I should not load until I run guard.

Code:

```
async ionViewCanEnter(): Promise<any> {

    const token = await this.storage.get('token')

    if (token) {
      return true;
    }
    Observable.fromPromise(this.navCtrl.setRoot('LoginPage'));

  }
```

version of ionic is 3.2.0

**Comment by davidoween** [comment]
...

**Comment by Dellos7** [comment]
Check out this issue: https://github.com/ionic-team/ionic/issues/11459

**Comment by Dellos7** [comment]
@davidoween I wanted to show you that perhaps you've got issues using guards in **ionViewCanEnter** because of everything mentioned in that issue. Maybe you should try other method in order to guard your views as it seems not to be working properly.

**Comment by davidoween** [comment]
What alternavida could you use?

2018-04-08 15:35 GMT+02:00 David López Castellote <notifications@github.com>
:

**Comment by davidoween** [comment]
@Dellos7 What alternavida could you use?
