### ISSUE TITLE
Using ion-menu in multiple pages toggles the menu on the first page only

### ISSUE THREAD

**Issue by mebibou** [ionic-team/ionic#14187]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you push `PageA` then `PageB`, which both contain an `ion-menu` on the same side (`right` for example), and using `menuToggle="right"` in `PageB` will try to open the menu on `PageA`, resulting in the menu in `PageB` not to show

**Expected behavior:**
Using `menuToggle` on a page should try to open the menu on the current page and not the first one found in the navigation stack

**Steps to reproduce:**
Using http://plnkr.co/edit/dOfF8jJOaeOpyk5EI1Q3?p=preview, you can see that the menu only opens on the home page. If you remove the menu from the home page, it will work on Page 1

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: 

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    Gulp CLI : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.8
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v7.4.0
    npm  : 4.1.2 
    OS   : macOS High Sierra

Misc:

    backend : pro
```

**Comment by loohopen** [comment]
ye, i met this problem too, and i solved it by this method:
First:  add `id` on `ion-menu` like this:
`pageA`
``` html
<ion-menu [content]="pageAcontent" id="pageA" type="overlay">
```

`pageB`
``` html
<ion-menu [content]="pageBcontent" id="pageB" type="overlay">
```
Then replace `menuToggle` directive by `(tap)=menutoggle()`, ye, use method!

and finaly:
in componet, you can write menutoggle method like this: 
`pageA`:
``` typescript
menutoggle () {
    this.menuCtr.enable(false, 'pageB');
    this.menuCtr.enable(true, 'pageA');
    this.menuCtr.toggle('pageA');
}
```

also `pageB`:
``` typescript
menutoggle () {
    this.menuCtr.enable(false, 'pageA');
    this.menuCtr.enable(true, 'pageB');
    this.menuCtr.toggle('pageB');
}
```

if you don't want to add method in every page, you can rewrite `menutoggle` directive， the thinking is:
disabled other page's menus, only enable this page's menu add add toggle method to this page's menu;

hope this is useful for you

**Comment by mebibou** [comment]
@loohopen hum your `menutoggle()` solution involves referencing the id of the menu in pageB from pageA, which is not good as one page should not know what is inside another. I've tried to use the technique like this:
```
class Page1 {
  ionViewWillEnter() {
    this.menuCtrl.enable(true, 'page1Menu');
  }
  
  ionViewWillLeave() {
    this.menuCtrl.enable(false, 'page1Menu');
  }
}
```
I've created a [new plunkr](http://plnkr.co/edit/uLc4CI5K9c87UR5oJE7a?p=preview) for it but it doesn't work, any idea why?

**Comment by mebibou** [comment]
The only ugly solution I find to be working wether you use `side` or `id` is to put a condition on the menu like this:
```
// template
<ion-menu side="right" *ngIf="menuEnabled">...

export class Page1 {
  menuEnabled = false;

  ionViewWillEnter() {
    this.menuEnabled = true;
  }
  
  ionViewWillLeave() {
    this.menuEnabled = false;
  }
}
```

**Comment by loohopen** [comment]
ye, you are right, 
your method is better,
it seems that the ion-menu only allows one enabled menu, hope later version can consider this problem.

**Comment by Eraldo** [comment]
@mebibou Somehow `menuEnabled = false;` does not work for me. :|
I don't understand why yet.
I am looking into it right now.

**Comment by Eraldo** [comment]
Okay.. in the end all I needed was this:
```ts  
  ionViewDidEnter() {
    this.menuCtrl.enable(true, 'my-id-on-this-page')
  }
```

According to the docs this will automatically disable all others on the same side.
(https://ionicframework.com/docs/api/components/app/MenuController/#multiple-menus-on-the-same-side)
