### ISSUE TITLE
Pages with a datepicker open bounce when i scroll up and down on the datepicker

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic#14192]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

(Note: this only happens on iOS)
When swiping up and down on the datepicker on https://ionic-stencil-conf-app.firebaseapp.com/about the page will bounce because its also trying to scroll

**Expected behavior:**

Page would not bounce when swiping on the datepicker

**Steps to reproduce:**

- Open https://ionic-stencil-conf-app.firebaseapp.com/about on an iOS device (I'm using an iPad pro)
- Open the datepicker and swipe up and down on it

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by manucorporat** [comment]
Fixed
