### ISSUE TITLE
Scrollbars show on multiple components with mouse attached (OS X)

### ISSUE THREAD

**Issue by mlynch** [ionic-team/ionic#14194]
Several components show scrollbars with an attached mouse on OS X. My guess is the use of `overflow: scroll` instead of `auto`:

![screenshot 2018-03-19 14 00 05](https://user-images.githubusercontent.com/11214/37616413-d622c112-2b7d-11e8-9f8a-19e7fba5f316.png)

![screenshot 2018-03-19 14 00 18](https://user-images.githubusercontent.com/11214/37616426-df1b3452-2b7d-11e8-8a14-07e5373337ed.png)

**Comment by paulstelzer** [comment]
This is in the meantime fixed :)
