### ISSUE TITLE
InvalidPipeArgument: '[object Object]' for pipe 'AsyncPipe' at invalidPipeArgumentError

### ISSUE THREAD

**Issue by paanazam96** [ionic-team/ionic#14190]
Hi guys, i have error on my ionic project which is the piping. it cannot call back the data of the user that has just updated to profile page. please help. thanks :)
---------------------------------------------------------------------------------------------------------------
<ion-header>

  <ion-navbar>
    <ion-title>Profile</ion-title>
  </ion-navbar>

</ion-header>

<ion-content padding class="masters">
    
    <ion-card>

      <ion-card-header text-center>
        <h1>My Profile</h1>
      </ion-card-header>

      <ion-card-content>
        <p>Name: {{(profileData | async)?.name}}</p>
        <p>Matric No.: {{(profileData | async)?.matric}}</p>
        <p>Course: {{(profileData | async)?.course}}</p>
        <p>Gender: {{(profileData | async)?.gender}}</p>
      </ion-card-content>

      <button ion-button full clear (click)="update()">Update Profile</button>

    </ion-card>

    <button ion-button full large color="light" (click)="createevent()">Create Event</button>
    <button ion-button full large color="danger" (click)="logout()">Log Out</button>
    
</ion-content>
------------------------------------------------------------------------------------------------------------
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams, App } from 'ionic-angular';
import { AngularFireDatabase, AngularFireObject } from 'angularfire2/database';
import { Profile } from './../../models/profile';
import { AngularFireAuth } from 'angularfire2/auth';
import { Observable } from 'rxjs/Observable';

@IonicPage()
@Component({
  selector: 'page-profile',
  templateUrl: 'profile.html',
})
export class ProfilePage {

  profileData: AngularFireObject<Profile>

  constructor(
    public navCtrl: NavController, 
    public navParams: NavParams,
    private app: App,
    private afDatabase: AngularFireDatabase,
    private afAuth: AngularFireAuth,
  ) {
  }

  ionViewWillLoad() {
    this.afAuth.authState.subscribe(data => {
      if (data && data.email && data.uid) {
          this.profileData = this.afDatabase.object(`profile/${data.uid}`);
        }
      });
  }

  logout() {
    //Api Token
    this.app.getRootNav().setRoot('WelcomePage');
  }
    
  createevent() {
     this.navCtrl.setRoot('CreatePage');
  }

  update(){
    this.navCtrl.push('UpdatePage');
  }

}
--------------------------------------------------------------------------------------------------------------

Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.8
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 6.11.4
OS Platform: Windows 10

**Comment by iamSaikat** [comment]
You need to return the data as Observable.
And declare profileData as a
`profileData: FirebaseListObservable<any[]>;`
