### ISSUE TITLE
animate do not support on iphone safari

### ISSUE THREAD

**Issue by steavengong** [ionic-team/ionic#14198]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request

**Current behavior:**

my animate file code ：
trigger(
    'fadeInLeft',
    [
      state('void',style({transform: 'translate3d(-100%,0,0)','-webkit-transform': 'translate3d(-100%,0,0)',opacity:0})),
      state('animated',style({transform: 'translate3d(0,0,0)','-webkit-transform': 'translate3d(0,0,0)',opacity:1})),
      transition('void => animated',[
        animate('.8s cubic-bezier(0.215, 0.61, 0.355, 1)')
      ]),
      transition('animated => void',[
        animate('.8s cubic-bezier(0.215, 0.61, 0.355, 1)')
      ])
    ]
  )

it will animate on PC browser,but it don't support on iphone safari

it's angular bug ? or ionic team can solve it?

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

local packages:

    @ionic/app-scripts : 3.1.8
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v7.9.0
    npm  : 3.10.10 
    OS   : macOS High Sierra

Misc:

    backend : legacy

```

**Comment by FdezRomero** [comment]
Hi @steavengong! At first sight, it seems that the problem might be coming from Angular Animations and not Ionic. Can you post a link to a live example to reproduce this issue? Thanks.

**Comment by lincolnthree** [comment]
Also an issue here.

**Comment by FdezRomero** [comment]
@lincolnthree Can you post an example that reproduces the issue? That would help to isolate the cause and check if its coming from Ionic or Angular Animations. Thanks!

**Comment by lincolnthree** [comment]
If I can get some time. Two full time jobs at the moment :) Will try.
