### ISSUE TITLE
ion-item hides validation divs

### ISSUE THREAD

**Issue by newuser44** [ionic-team/ionic#14200]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...** 
[X] bug report
[ ] feature request

**Current behavior:**

On a card,  creating a from.   (which has this bug also   https://forum.ionicframework.com/t/bug-with-ios-input-on-card/124880).  

Adding in <ion-item> around my input and validation we get this.

```
<ion-col col-12 col-sm-9 col-md-6 col-lg-4>
                <ion-item>
                <ion-label floating for="firstName">First Name</ion-label>
                <ion-input type="text"  [(ngModel)]="firstName" #firstNameVal="ngModel" name="firstName" id="firstName" required></ion-input>
                <div *ngIf="firstNameVal.invalid && (firstNameVal.touched || firstNameVal.blur)" class="serverErrorRed">
                   First Name is Required
                  </div> 
              </ion-item>                               
            </ion-col>
```
But on the screen the div validation never shows.  

**Expected behavior:**
I would expect validation div to show just under the input.  

If I change the above code to have the div outside the ion-item closing tag it shows up as expected (but not aligned correctly). 

**Steps to reproduce:**
Set up a form with input values that are required.
Do an ngIf on the invalid value.  See if the validation text shows up.

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/home/.npm-global/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.1.0 browser 4.1.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    Node              : v6.12.3
    npm               : 3.10.10
    OS                : Linux 3.13

Environment Variables:

    ANDROID_HOME : /home/Android/Sdk

Misc:

    backend : legacy
```

**Comment by brandyscarney** [comment]
Thanks for the issue! This is caused by the content projection inside of Item. Please see the docs for more information: https://ionicframework.com/docs/api/components/item/Item/#item-placement
