### ISSUE TITLE
[searchbar] Add type="search" in searchbar component

### ISSUE THREAD

**Issue by poohia** [ionic-team/ionic#14201]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[X] **2.x**
[X] **3.x**
[X] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request

Add type="search" in searchbar component

**Comment by brandyscarney** [comment]
Thanks for the issue! The searchbar currently uses `type="search"` in both v3: https://github.com/ionic-team/ionic/blob/v3/src/components/searchbar/searchbar.ts#L130

and v4: https://github.com/ionic-team/ionic/blob/master/core/src/components/searchbar/searchbar.tsx#L90

Are you seeing anything particularly wrong with the behavior?

**Comment by masimplo** [comment]
Maybe related to https://github.com/ionic-team/ionic/issues/6161
