### ISSUE TITLE
App has the chance to stay on the splash screen  and not enter

### ISSUE THREAD

**Issue by sunjianghong** [ionic-team/ionic#14204]
My app has a chance to stop at the SplashScreen   and not enter,
There's probably a 5 chance, and some iphone models will appear, and Andorid doesn't have a problem.
We are using iOS Wkwebview packaging, it should not be like a front-end code logic problem, this problem has plagued me for a long time,
Will it be the bottom of the ionic, or wkwebview,cordova the bottom of the problem, or the resulting JS file too large to have a chance to load the page, Please help to see if we have ever seen such a problem

**Comment by sunjianghong** [comment]
development environment
packages: 
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2
global packages:
    Cordova CLI : 7.1.0
local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0 ios 4.5.1
    Ionic Framework    : ionic-angular 3.9.0
System:
    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.2
    ios-sim           : 5.1.0
    Node              : v8.6.0
    npm               : 5.2.0
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

**Comment by FdezRomero** [comment]
Hi @sunjianghong! Can you make a screen capture of the problem so others can better understand what the problem is?

Also, if I may suggest, it's easier to get help if you respect and fill the issue template.

**Comment by sunjianghong** [comment]
this is my app  screen capture
App has the chance to stay on the splash screen and not enter
![screen](https://user-images.githubusercontent.com/2868375/37886909-0da7c1aa-30f1-11e8-9789-88b4304e2126.png)

**Comment by FdezRomero** [comment]
@sunjianghong I'm assuming you have the `cordova-plugin-splashscreen` installed.
- Are you calling to `this.splashscreen.hide()` (Ionic Native) or `navigator.splashscreen.hide()` when the app has initialized?
- If you add `console.log('Splashscreen hidden');` just below this line, does it always show, even if the splashscreen doesn't hide?

**Comment by sunjianghong** [comment]
@FdezRomero 
is randomly appearing.Not every time this happens.
Who can help me, don't know what's wrong

**Comment by FdezRomero** [comment]
@sunjianghong I’m trying to help you, but it’s really hard if you delete the issue template and don’t give more details. Can you check the questions from my previous message? Thanks.
