### ISSUE TITLE
more than one library with package name 'com.google.android.gms.license 

### ISSUE THREAD

**Issue by ejaz47** [ionic-team/ionic#14205]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

Not able to build platform android using **"ionic cordova run android"** command

**Expected behavior:**

Should run properly

**Steps to reproduce:**

 Run **"ionic cordova run android"** command

  
![sss](https://user-images.githubusercontent.com/16835868/37698601-a4e5f500-2d09-11e8-8e6c-cd36077aab6c.png)

**Other Information:**

>     @ionic/cli-utils  : 1.19.1
>     ionic (Ionic CLI) : 3.19.1
> 
> global packages:
> 
>     cordova (Cordova CLI) : 7.1.0
> 
> local packages:
> 
>     @ionic/app-scripts : 1.3.7
>     Cordova Platforms  : none
>     Ionic Framework    : ionic-angular 3.2.1
> 
> System:
> 
>     Node : v6.11.3
>     npm  : 3.10.10
>     OS   : Windows 7
>

**Comment by DBnR1** [comment]
Do you use the Firebase plugin? If so, check this ticket: https://github.com/arnesson/cordova-plugin-firebase/issues/610

**Comment by nvirth** [comment]
I also have this problem. Last time everything built; we did not change anything; today the android build is dead with this error

**Comment by ejaz47** [comment]
@DBnR1, no i am not using Firebase plugin.

**Comment by nvirth** [comment]
Btw, I am using Firabese plugin...
But in this case maybe it is not at all a Firebase plugin bug?

I could see on the console during the build that these dependencies were updated:
[deps-updated.txt](https://github.com/ionic-team/ionic/files/1833915/deps-updated.txt)

**Comment by nvirth** [comment]
Actually, for me it was really the Firebase plugin. Thanks for the link @DBnR1, it solved for me.
Specifically, for me the solution was in this comment: https://github.com/arnesson/cordova-plugin-firebase/issues/610#issuecomment-374941040

**Comment by ejaz47** [comment]
Actually for me it was the Google plus plugin **"cordova-plugin-googleplus"**
Thanks for the link @DBnR1, however i added 2 more dependencies to solve the issues.

**Add bellow code at the end of platforms/android/build.gradle file**

```
configurations.all {
   resolutionStrategy {

       force "com.google.android.gms:play-services-auth:11.8.0"
       force "com.google.android.gms:play-services-identity:11.8.0"

       force "com.google.android.gms:play-services-ads:11.8.0"
       force "com.google.android.gms:play-services-base:11.8.0"
       force "com.google.android.gms:play-services-gcm:11.8.0"
       force "com.google.android.gms:play-services-analytics:11.8.0"
       force "com.google.android.gms:play-services-location:11.8.0"
       force "com.google.android.gms:play-services-basement:11.8.0"
       force "com.google.android.gms:play-services-tagmanager:11.8.0"
       force 'com.google.firebase:firebase-core:11.8.0'
       force 'com.google.firebase:firebase-crash:11.8.0'
       force 'com.google.firebase:firebase-auth:11.8.0'
       force 'com.google.firebase:firebase-common:11.8.0'
       force 'com.google.firebase:firebase-config:11.8.0'
       force 'com.google.firebase:firebase-messaging:11.8.0'
   }
}
```

**Comment by FdezRomero** [comment]
Hi @ejaz47! The problem you were having seems to be more related to Cordova than Ionic. Is it still an issue? If not, can you please close it? (I'm volunteering to triage issues). Thanks!

**Comment by ejaz47** [comment]
@FdezRomero, yes its related to cordova so  closing it. Thanks
