### ISSUE TITLE
google map (javascript) not work some time

### ISSUE THREAD

**Issue by athlona64** [ionic-team/ionic#14218]
when open application some time application crash show this error affter that my app freeze screen
![selection_008](https://user-images.githubusercontent.com/3031787/37812021-2e97f528-2e90-11e8-813e-7acf4d045a09.png)

![selection_007](https://user-images.githubusercontent.com/3031787/37812005-12600b84-2e90-11e8-96ab-9d03e5eec541.png)

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 6.4.0 browser 5.0.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v9.8.0
    npm               : 5.6.0 
    OS                : Linux 4.13

Environment Variables:

    ANDROID_HOME : /home/manzer/Android/Sdk

Misc:

    backend : pro

```

**Comment by rdlabo** [comment]
not loaded `<script async defer src="https://maps.googleapis.com/maps/api/js"></script>` in `src/index.html`  .

Ionic team think `google maps script is loaded last as to not block rendering` . so error will result if the method runs when the loading is not completed.

If you want eliminate errors, you can block rendering or load googlemap api set position up.
Maybe.

```
<body>

  <!-- Ionic's root component and where the app will load -->
  <ion-app></ion-app>

  <script src="cordova.js"></script>

  <!-- 【Change this】 -->
  <script async defer src="https://maps.googleapis.com/maps/api/js"></script>
  
  <!-- The polyfills js is generated during the build process -->
  <script src="build/polyfills.js"></script>

  <!-- The bundle js is generated during the build process -->
  <script src="build/vendor.js"></script>

  <!-- The bundle js is generated during the build process -->
  <script src="build/main.js"></script>
</body>
```

thanks.

**Comment by athlona64** [comment]
Yeah i think googmap load not complete some time , right now i used  script async defer src="https://maps.googleapis.com/maps/api/js"></script> in src/index.html.

How to solve this problem ? Guide me pls.
