### ISSUE TITLE
Ionic 3.19.0 asks for CLI update but continues to ask for update after accepting.

### ISSUE THREAD

**Issue by bfontana** [ionic-team/ionic#14215]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

**Current behavior:**

When running a "ionic serve" command CLI asks to upgrade. After enter Y it seems to upgrade but next time you run "ionic serve" (or any other ionic command) upgrade question appears again.

**Expected behavior:**

CLI updated after accepting update.

**Steps to reproduce:**

macOS Sierra with Ionic CLI 3.19.0. Issue any CLI command (except for "ionic cordova ..." commands) and you'll see this

> ionic serve --lab --locale

> The Ionic CLI has an update available (3.19.0 => 3.20.0)! Would you like to in
stall it? Yes
> npm i -g ionic@latest
✔ Running command - done!

[OK] Updated Ionic CLI to 3.20.0! 🎉

> Please re-run your command.

> Note: You can downgrade to your old version by running: npm i -g ionic@3.19.0
>$ ionic serve --lab --locale

> The Ionic CLI has an update available (3.19.0 => 3.20.0)! Would you like to in
stall it? 

and again, ...and again.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : browser 5.0.1 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.6.0
    npm        : 5.5.1 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by brandyscarney** [comment]
This issue was moved to ionic-team/ionic-cli#3021
