### ISSUE TITLE
WKWebView has CORS issues with Firebase Storage

### ISSUE THREAD

**Issue by axalon** [ionic-team/ionic#14210]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**

Receiving a

`Origin is not allowed by Access-Control-Allow-Origin.`

error when trying to download files from Firebase.

This is happening in a compiled app (`ionic cordova build ios`) and running it from XCode.

**Expected behavior:**

Any file I attempted to pull with `ref.getDownloadURL()` should download with no issue.

**Steps to reproduce:**

Pull an image from firebase storage, e.g.:
`
const ref = this.storage.ref(result.imagePath);
ref.getDownloadURL().subscribe(data => {							  					
});
`

**Other information:**

The only workaround seems to be switching back to UIWebView, doing so alleviates all issues with CORS.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 6.5.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.1.2 ios 4.3.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.3
    ios-deploy        : 1.9.2 
    ios-sim           : 6.0.0 
    Node              : v6.9.4
    npm               : 3.10.10 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

```

**Comment by axalon** [comment]
Found a solution to this.

Had to adjust the CORS for my firebase storage bucket to:

`[
  {
    "origin": ["*"],
    "method": ["GET"],
    "maxAgeSeconds": 3600
  }
]`

As per the instructions found here: https://firebase.google.com/docs/storage/web/download-files

You'll need gsutil: https://cloud.google.com/storage/docs/gsutil_install#install

I guess my question now is why was this not an issues with UIWebView? Did it not respect CORS and  WKWebView does?

**Comment by FdezRomero** [comment]
> I guess my question now is why was this not an issues with UIWebView? Did it not respect CORS and WKWebView does?

@axalon Yes, you guessed right. More info about CORS and WKWebview here: https://ionicframework.com/docs/wkwebview/#cors

Since you found the solution on the Firebase side, I think you can close this issue.

**Comment by kensodemann** [comment]
As this appears to not be an Ionic issue at all, I am going to close this.
