### ISSUE TITLE
Slow opening ionic 3 project

### ISSUE THREAD

**Issue by Ayoubaddi** [ionic-team/ionic#14228]
i finish my application and i build it with this command ionic build android --release , and i use a splash screen , and is work fine in google chrome browser 
but in android device is take **180 second** to open before show the splash screen
i try to use ionic build android --prod  , but is show me this error [https://i.imgur.com/DpQY5ir.png](https://i.imgur.com/DpQY5ir.png)
can anyone help me ?
Thank for the time

**Comment by Ayoubaddi** [comment]
this is my ionic info
![image](https://user-images.githubusercontent.com/37641470/37866442-a594c9e2-2f82-11e8-8ec9-263cf9beaf71.png)

**Comment by ghenry22** [comment]
you need to use
`ionic build android --prod --release`
Each of those flags services a different purpose
`--prod optimizes the javascript / html / css build`
`--release builds a signed release binary for android`

**Comment by Ayoubaddi** [comment]
@ghenry22  Thank You So much 
That solve my problem 
Thank you so much i still a lot of time complain because my project doesn't complete because this problem 
now i fixed with 'delete node modules folder'
Thank You So much again
