### ISSUE TITLE
ion-datetime does not allow to select 31 day of a month

### ISSUE THREAD

**Issue by JStumpp** [ionic-team/ionic#14233]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**
```
"@ionic/core": "0.1.5-2",
```
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

The month selector prevents non-valid day of month inputs but uses an old month to determine day of month range.

**Expected behavior:**

Being able to select the correct day of month after changing the month.

**Steps to reproduce:**

Select a month with 30 days per month e.g.: Apr 30, 2018
Close with "Done"
Try to select a date with 31 days e.g. March is not possible.

**Related code:**

```
<ion-item>
  <ion-label>Date</ion-label>
  <ion-datetime></ion-datetime>
</ion-item>
```

**Comment by kondrekat** [comment]
I have same problem. But I want to add that this problem is only then I change mouth to one before or after. For example from Feb to March or from Feb to Jan but if I change from Feb to May it works in correct way.

**Comment by RHinderiks** [comment]
Same here

**Comment by warntjo** [comment]
Same here

**Comment by RHinderiks** [comment]
@paulstelzer Definitely still a bug. The selection wheel even seems to disappear now when trying to drag it into a "forbidden" date and becomes visible again when released

**Comment by brylie** [comment]
Same here on Firefox for Android.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us. I am going to close this for now, but we will be re-evaluating the `ion-datetime` functionality and bugs soon during which we will take a closer look at this issue.

Thanks for using Ionic!
