### ISSUE TITLE
ion-slides doesn't work with firestore

### ISSUE THREAD

**Issue by AbdullahZaher** [ionic-team/ionic#14247]
Hi ionic team;
I face a lot of problem while using ion-slides with google firebase or firestore! Why I can't use them together?

This is a screenshot!
![020 - dawri star - http___localhost_8100_](https://user-images.githubusercontent.com/29790195/38055057-55e09036-32e1-11e8-9377-eeffd3b6faa0.png)
 
The code that I'm using:
`  <ion-slides pager autoplay="2000" pager="true" loop="true" speed="500">
    <ion-slide *ngFor="let slides of items">
      <img class="card-img" [src]="slides.img"/>
      <div class="card-title"><span class="card-title-cat" [innerHTML]="slides.title"></span></div>
    </ion-slide>
  </ion-slides>`

**Comment by kensodemann** [comment]
Based solely on the error message you are getting, it sounds like `items` is not a proper Array, but it is impossible to tell without more context. Can you please provide a simple sample application via GitHub that duplicates your issue so it can be examined? It is far more likely that someone will be able to help you then.

**Comment by lucasbasquerotto** [comment]
@AbdullahZaher Like  @kensodemann said above, `items` must be an array. If it is an `Observable`, you can use the `async` pipe: `*ngFor="let slides of items | async"`, or subscribe to it and update the items.

**Comment by AbdullahZaher** [comment]
Thank you so so much @kensodemann and @lucasbasquerotto for having my issue. I found the issue after read it at chrome console error. It was from these things:
`pager autoplay="2000" pager="true" loop="true"`
How I can customize my ion-slides throw another way?
Thanks

**Comment by lucasbasquerotto** [comment]
@AbdullahZaher I don''t undarstand exactly what you are saying, maybe you could try to remove all properties of the `ion-slides` and add them one per one. 

One thing I noted, though, is that you have **the property `pager` defined twice**:

`<ion-slides pager autoplay="2000" pager="true" loop="true" ...`

Try this instead:

`<ion-slides autoplay="2000" pager="true" loop="true" ...`

That doesn't seem to be the error you posted in the 1st post, though, about `ngFor`.

**Comment by AbdullahZaher** [comment]
@lucasbasquerotto  I removed all the properties and its work. Thanks
