### ISSUE TITLE
DateTime display format with extra text

### ISSUE THREAD

**Issue by hdlopesrocha** [ionic-team/ionic#14250]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

I am trying to display a DateTime picker like this 12h30m.
The display format should be something like "HH[h]mm[m]".
But apparently the [h] and [m] are including the hours and minutes.
The result is something like "12[12]30[30]"

**Expected behavior:**

The result should be "12h30m"

```
<ion-datetime pickerFormat="HH:mm"
              displayFormat="HH[h]mm[m]"
              [(ngModel)]="time"
              [initialValue]="time">
</ion-datetime>
```

**Other information:**

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

local packages:

    @ionic/app-scripts : 3.1.8
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v9.10.0
    npm  : 5.6.0 
    OS   : Linux 4.4

Misc:

    backend : pro

Best regards.
Henrique Rocha

**Comment by emcniece** [comment]
There was a PR made to allow this, but it was closed without merging. 😢 

https://github.com/ionic-team/ionic/pull/12097

**Comment by xumingyi** [comment]
I see a lot of people mentioned that the picker display is not clear, I hope to add the picker label to identify, is this problem solved? 
![614488457524677973](https://user-images.githubusercontent.com/14070569/43118993-31f59e74-8f47-11e8-9275-16615789f4f9.jpg)
