### ISSUE TITLE
ion-input password clears password on focus again

### ISSUE THREAD

**Issue by Muneem** [ionic-team/ionic#14260]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**

ion-input type password is clearing password when you type once and then again come back to this field and type something. it will clear password field

**Expected behavior:**

It should not clear previous password. This feature is used by many other libraries like 1 password. so those libraries will not work with it

**Steps to reproduce:**

1) Create 1 password field
2) Put any random password there.
3) get out of that field. Click on any place outside that field
4) Get to that field again. Start typing something. 
5) . It will clear previous password.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by manucorporat** [comment]
@kshaaban- you are correct! closing issue

**Comment by Muneem** [comment]
its not present in document. I think we should add this in documents

**Comment by chakri3130** [comment]
Perfect.
