### ISSUE TITLE
A problem occurred evaluating project ':app'.

### ISSUE THREAD

**Issue by Story5** [ionic-team/ionic#14275]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**

Hey guys, I meet a problem that I can't build my android apk.
Got this error 
```
* Where:
Script '/Users/Story5/Story5/01Project/OSChina/03 BlueEarth/05 BIM_Market/platforms/android/CordovaLib/cordova.gradle' line: 132

* What went wrong:
A problem occurred evaluating project ':app'.
> No match found
```
**My Ionic info:**

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v8.11.1
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.3 Build version 9E145 

Environment Variables:

    ANDROID_HOME : /Users/Story5/Library/Android/sdk

Misc:

    backend : pro
```

**Comment by Kinzi** [comment]
Same here. Any news @Story5? Did you solve this?

**Comment by Kinzi** [comment]
For me the android-versionCode was faulty in my config.xml. make sure it's formatted with numbers only: android-versionCode="291". No "." or other characters.

**Comment by Story5** [comment]
@Kinzi I solved by change the android-versionCode in config.xml to the corrent value. I set the value "1.0.0" which is not a int value cause the problem.
