### ISSUE TITLE
npm warning when installing npm install -g ionic

### ISSUE THREAD

**Issue by themhz** [ionic-team/ionic#14279]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**

when I run npm install -g ionic I get 
PS C:\wamp64\www\ionic> npm install -g ionic
C:\Users\themhz\AppData\Roaming\npm\ionic -> C:\Users\themhz\AppData\Roaming\npm\node_modules\ionic\bin\ionic
npm WARN rollback Rolling back readable-stream@2.2.9 failed (this is probably harmless): EPERM: operation not permitted,
 lstat 'C:\Users\themhz\AppData\Roaming\npm\node_modules\ionic\node_modules\fsevents\node_modules'
npm WARN rollback Rolling back tar-pack@3.4.0 failed (this is probably harmless): EPERM: operation not permitted, lstat
'C:\Users\themhz\AppData\Roaming\npm\node_modules\ionic\node_modules\fsevents\node_modules'
npm WARN rollback Rolling back ajv@4.11.8 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\
Users\themhz\AppData\Roaming\npm\node_modules\ionic\node_modules\fsevents\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\ionic\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})

+ ionic@3.20.0
added 253 packages from 152 contributors in 18.001s
**Expected behavior:**

I don't know
**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
PS C:\wamp64\www\ionic> ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

cli packages: (C:\Users\themhz\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:

    Node : v8.9.1
    npm  : 6.0.0-next.0
    OS   : Windows 10

Misc:

    backend : pro

**Comment by brandyscarney** [comment]
This issue was moved to ionic-team/ionic-cli#3059
