### ISSUE TITLE
"ionic cordova build android --prod" gives error! Any Solution?

### ISSUE THREAD

**Issue by Tanzeel064** [ionic-team/ionic#14273]
Running app-scripts build: --prod --platform android --target cordova
[10:28:42]  build prod started ...
[10:28:42]  clean started ...
[10:28:42]  clean finished in 19 ms
[10:28:42]  copy started ...
[10:28:43]  deeplinks started ...
[10:28:43]  deeplinks finished in 222 ms
[10:28:43]  ngc started ...
[10:28:53]  typescript error
            Type AboutusPage in D:/Projects/Cveer/src/pages/aboutus/aboutus.ts is part of the declarations of 2 modules:
            AppModule in D:/Projects/Cveer/src/app/app.module.ts and AboutusPageModule in
            D:/Projects/Cveer/src/pages/aboutus/aboutus.module.ts! Please consider moving AboutusPage in
            D:/Projects/Cveer/src/pages/aboutus/aboutus.ts to a higher module that imports AppModule in
            D:/Projects/Cveer/src/app/app.module.ts and AboutusPageModule in
            D:/Projects/Cveer/src/pages/aboutus/aboutus.module.ts. You can also create a new NgModule that exports and
            includes AboutusPage in D:/Projects/Cveer/src/pages/aboutus/aboutus.ts then import that NgModule in
            AppModule in D:/Projects/Cveer/src/app/app.module.ts and AboutusPageModule in
            D:/Projects/Cveer/src/pages/aboutus/aboutus.module.ts.

Error: The Angular AoT build failed. See the issues above
    at D:\Projects\Cveer\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:237:55
    at step (D:\Projects\Cveer\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:32:23)
    at Object.next (D:\Projects\Cveer\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:13:53)
    at fulfilled (D:\Projects\Cveer\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:4:58)
    at <anonymous>
[10:28:53]  copy finished in 10.21 s

**Comment by lucasbasquerotto** [comment]
@Tanzeel064 Like the error says, it seems your are importing your page in 2 different modules: `AppModule` (`/src/app/app.module.ts`) and `AboutusPageModule` (`/src/pages/aboutus/aboutus.module.ts`).

**Import it only in `AboutusPageModule`** (remove `AboutusPage` from the `AppModule`).

**If** you want that page without lazy loading (it will be included in the generated `main.js`, instead of `0.js`, `1.js` and so on) you can import `AboutusPageModule` (not `AboutusPage`) in your `AppModule`:

```
@NgModule({
	declarations: [
		MyApp,
	],
	imports: [
		...,
		AboutusPageModule,
	],
	bootstrap: [
		IonicApp
	],
	entryComponents: [
		MyApp,
	],
	...
})
export class AppModule { }
```
