### ISSUE TITLE
parsing nested json in ionic 

### ISSUE THREAD

**Issue by manvfx** [ionic-team/ionic#14289]
how to parsing nested json in ionic?

```
[
   {
       "id": "1",
        "title":"today",
       "inputs":[
           {
              "id":"2",
              "name":"mary",
              "county":"germany",
              "age":"33"
            },
      "outputs":[
           {
              "id":"2",
              "name":"joe",
              "county":"england",
              "age":"16"
            },
           {
              "id":"2",
              "name":"peter",
              "county":"canada",
              "age":"42"
            }
       ]
   }
]

```

**Comment by sfaizanh** [comment]
Not related to Ionic, It's related to Javascript use `JSON.parse(data);`
What do you want to achieve with this object is a different question. if it's simple then you can use Javascript methods or something complex with a easy way use **[lodash](https://lodash.com/)** or **[underscore.js](http://underscorejs.org/)**

_Note: You have an issue with your JSON string **missing `]` in `inputs`**. You can validate your JSON on [JSONLint](https://jsonlint.com/)_
