### ISSUE TITLE
PANIC: Missing emulator engine program for 'x86' CPU on Mac

### ISSUE THREAD

**Issue by wilfredonoyola** [ionic-team/ionic#14291]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request

**Current behavior:**
When I try `ionic cordova run android` and then I see this "PANIC: Missing emulator engine program for 'x86' CPU."

**Expected behavior:**
This will launch a real device or virtual device to run the app.

**Steps to reproduce:**

I have removed entire Android Studio and all files and folder on MacOs and then I have installed the last version of Android Studio and after that I have created a test application on Android Studio to test it and finally The app runs correctly with virtual device. Later I have created an App with Ionic and I have tried to test it, but I get this error "PANIC: Missing emulator engine program for 'x86' CPU."

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-plugin-proxy : 1.5.8
    @ionic/cli-utils        : 1.19.2
    ionic (Ionic CLI)       : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v6.11.3
    npm               : 3.10.10 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME     : /Users/wilfredonoyola/Library/Android/sdk/
    HTTP_PROXY       : not set
    http_proxy       : not set
    HTTPS_PROXY      : not set
    https_proxy      : not set
    IONIC_HTTP_PROXY : not set
    PROXY            : not set
    proxy            : not set

Misc:

    backend : pro

```

**Comment by nekic** [comment]
I encountered the same problem, I refer to  [this method](https://www.stkent.com/2017/08/10/update-your-path-for-the-new-android-emulator-location.html) to solve the problem

**Comment by nick-xie** [comment]
Note sure if you've fixed your problem but check which system image your android virtual device is using (you can check on android studio under the 'API' column in the AVD list). Make sure you're not using anything too new, I tried using 28 and 27 and neither worked but 26 (Android Oreo 8.0) did. Cheers!

**Comment by ElLocoNutz** [comment]
Had the same problem, solved it with these lines added to .bash_profile:

export ANDROID_SDK_ROOT=/Users/<username>/Library/Android/sdk
export PATH=$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools:$PATH

**Comment by sirajalam049** [comment]
@ElLocoNutz , it is not working for me, Ran both commands, still the same output.

**Comment by ElLocoNutz** [comment]
Ok my wrong, apparently I used the wrong expression when I wrote the path, it should look like this:

```
export ANDROID_SDK_ROOT=/Users/**[username]**/Library/Android/sdk
export PATH=$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools:$PATH
```

But don't just run those commands or the change won't stay. You should add those lines to your ~/.bashrc or ~/.bash_profile and after that you need to reload the bash, restart the console or source the edited file, e.g.
"me@localhost:~$ source .bashrc"

But keep in mind those are the folders that worked for me, your system might be using different ones, check the folder before you change anything, you should find there the emulator.
