### ISSUE TITLE
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.

### ISSUE THREAD

**Issue by ghost** [ionic-team/ionic#14304]
I'm trying to build my ionic project, but getting following error (compilation fails in gradle configuration):

> PS C:\Workspace\mobileapp> ionic cordova build android --debug
> Running app-scripts build: --platform android --target cordova
> [13:05:08]  build dev started ...
> [13:05:08]  clean started ...
> [13:05:08]  clean finished in 7 ms
> [13:05:08]  copy started ...
> [13:05:08]  transpile started ...
> [13:05:19]  transpile finished in 11.49 s
> [13:05:19]  preprocess started ...
> [13:05:19]  deeplinks started ...
> [13:05:20]  deeplinks finished in 255 ms
> [13:05:20]  preprocess finished in 256 ms
> [13:05:20]  webpack started ...
> [13:05:20]  copy finished in 12.27 s
> [13:05:37]  webpack finished in 17.47 s
> [13:05:37]  sass started ...
> [13:05:41]  sass finished in 3.91 s
> [13:05:41]  postprocess started ...
> [13:05:41]  removed unused font files
> [13:05:41]  postprocess finished in 80 ms
> [13:05:41]  lint started ...
> [13:05:41]  build dev finished in 33.78 s
> > cordova build android --debug
> ANDROID_HOME=C:\Users\user\AppData\Local\Android\Sdk
> JAVA_HOME=C:\Program Files\Java\jdk1.8.0_151
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> BUILD SUCCESSFUL in 17s
> 1 actionable task: 1 executed
> Subproject Path: CordovaLib
> The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
> 
>         at build_bbib3h28v2rns6xj5u95qezuw.run(C:\Workspace\mobileapp\platforms\android\build.gradle:137)
> The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
> 
> Incremental java compilation is an incubating feature.
> The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
> 
> File C:\Users\user\.android\repositories.cfg could not be loaded.
> 
> 
> BUILD FAILED
> 
> Total time: 20.704 secs
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'android'.
> > Could not resolve all dependencies for configuration ':_debugApkCopy'.
>    > Could not find com.google.android.gms:play-services-auth:11.8.0.
>      Searched in the following locations:
>          file:/C:/Users/user/AppData/Local/Android/Sdk/extras/google/m2repository/com/google/android/gms/play-services-auth/11.8.0/play-services-auth-11.8.0.pom
>          file:/C:/Users/user/AppData/Local/Android/Sdk/extras/google/m2repository/com/google/android/gms/play-services-auth/11.8.0/play-services-auth-11.8.0.jar
>          file:/C:/Workspace/mobileapp/platforms/android/sdk-manager/com/google/android/gms/play-services-auth/11.8.0/play-services-auth-11.8.0.jar
>          file:/C:/Users/user/AppData/Local/Android/Sdk/extras/android/m2repository/com/google/android/gms/play-services-auth/11.8.0/play-services-auth-11.8.0.pom
>          file:/C:/Users/user/AppData/Local/Android/Sdk/extras/android/m2repository/com/google/android/gms/play-services-auth/11.8.0/play-services-auth-11.8.0.jar
>          file:/C:/Workspace/mobileapp/platforms/android/sdk-manager/com/google/android/gms/play-services-auth/11.8.0/play-services-auth-11.8.0.jar
>      Required by:
>          project :
>    > Could not find com.google.android.gms:play-services-identity:11.8.0.
>      Searched in the following locations:
>          file:/C:/Users/user/AppData/Local/Android/Sdk/extras/google/m2repository/com/google/android/gms/play-services-identity/11.8.0/play-services-identity-11.8.0.pom
>          file:/C:/Users/user/AppData/Local/Android/Sdk/extras/google/m2repository/com/google/android/gms/play-services-identity/11.8.0/play-services-identity-11.8.0.jar
>          file:/C:/Workspace/mobileapp/platforms/android/sdk-manager/com/google/android/gms/play-services-identity/11.8.0/play-services-identity-11.8.0.jar
>          file:/C:/Users/user/AppData/Local/Android/Sdk/extras/android/m2repository/com/google/android/gms/play-services-identity/11.8.0/play-services-identity-11.8.0.pom
>          file:/C:/Users/user/AppData/Local/Android/Sdk/extras/android/m2repository/com/google/android/gms/play-services-identity/11.8.0/play-services-identity-11.8.0.jar
>          file:/C:/Workspace/mobileapp/platforms/android/sdk-manager/com/google/android/gms/play-services-identity/11.8.0/play-services-identity-11.8.0.jar
>      Required by:
>          project :
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> (node:15112) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'android'.
> > Could not resolve all dependencies for configuration ':_debugApkCopy'.
>    > Could not find com.google.android.gms:play-services-auth:11.8.0.
>      Searched in the following locations:
>          file:/C:/Users/user/AppData/Local/Android/Sdk/extras/google/m2repository/com/google/android/gms/play-services-auth/11.8.0/play-services-auth-11.8.0.pom
>          file:/C:/Users/user/AppData/Local/Android/Sdk/extras/google/m2repository/com/google/android/gms/play-services-auth/11.8.0/play-services-auth-11.8.0.jar
>          file:/C:/Workspace/mobileapp/platforms/android/sdk-manager/com/google/android/gms/play-services-auth/11.8.0/play-services-auth-11.8.0.jar
>          file:/C:/Users/user/AppData/Local/Android/Sdk/extras/android/m2repository/com/google/android/gms/play-services-auth/11.8.0/play-services-auth-11.8.0.pom
>          file:/C:/Users/user/AppData/Local/Android/Sdk/extras/android/m2repository/com/google/android/gms/play-services-auth/11.8.0/play-services-auth-11.8.0.jar
>          file:/C:/Workspace/mobileapp/platforms/android/sdk-manager/com/google/android/gms/play-services-auth/11.8.0/play-services-auth-11.8.0.jar
>      Required by:
>          project :
>    > Could not find com.google.android.gms:play-services-identity:11.8.0.
>      Searched in the following locations:
>          file:/C:/Users/user/AppData/Local/Android/Sdk/extras/google/m2repository/com/google/android/gms/play-services-identity/11.8.0/play-services-identity-11.8.0.pom
>          file:/C:/Users/user/AppData/Local/Android/Sdk/extras/google/m2repository/com/google/android/gms/play-services-identity/11.8.0/play-services-identity-11.8.0.jar
>          file:/C:/Workspace/mobileapp/platforms/android/sdk-manager/com/google/android/gms/play-services-identity/11.8.0/play-services-identity-11.8.0.jar
>          file:/C:/Users/user/AppData/Local/Android/Sdk/extras/android/m2repository/com/google/android/gms/play-services-identity/11.8.0/play-services-identity-11.8.0.pom
>          file:/C:/Users/user/AppData/Local/Android/Sdk/extras/android/m2repository/com/google/android/gms/play-services-identity/11.8.0/play-services-identity-11.8.0.jar
>          file:/C:/Workspace/mobileapp/platforms/android/sdk-manager/com/google/android/gms/play-services-identity/11.8.0/play-services-identity-11.8.0.jar
>      Required by:
>          project :
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
>     at ChildProcess.whenDone (C:\Workspace\mobileapp\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
>     at ChildProcess.emit (events.js:159:13)
>     at maybeClose (internal/child_process.js:943:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
> (node:15112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:15112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I'm having following version of tools:

Ionic: 3.20.0
Cordova: 8.0.0
Cordova-Android: 6.2.3
Any help would be very grateful.

**Comment by Simpler1** [comment]
See https://github.com/ionic-team/ionic-cli/issues/3002
