### ISSUE TITLE
FR: support both direction gesture on Ionic4

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#14301]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
On **Ionic4** it seems you are not using anymore Hammer to control gestures like **PAN**, you have done a custom implementation, which looks very good!!

I had a look to your GestureController, and PanRecognizer. As on ionic3 with Hammer you are not permitting do a PAN in BOTH direction on the same time.

With **hammer.js** we could do a workaround doing all this manually, like described at @joshuamorony blog  https://www.joshmorony.com/building-an-absolute-drag-directive-in-ionic-2/, which +- minus works great.
With this we had implemented a DRAG AND DROP behavior, we check if user is PRESS component and set BOTH direction for HAMMER on component. Not anything is working as requested, I opened in past some issues and also some posts in forum.

With your GestureController now we can not do this anymore.

**Expected behavior:**
Adapt your Gesture implementation, to let us set a custom Controller over a component where we can PAN an both direction. In this way we can add recognize a PRESS event and ADD manually a GestureController over component for pan in both direction. 

This would be a feature many of us is searching from months/years.

**Steps to reproduce:**
If you have a look on gesture documentation, https://ionicframework.com/docs/components/#gestures you can see the same error we have with  HAMMER, documented in some issues and forum posts.
WHEN you PAN over component, you have first to pan HORIZONTALLY before a VERTICAL pan recognized.
![image](https://user-images.githubusercontent.com/3778892/38563998-7c406272-3cde-11e8-87ac-d7430830dfaa.png)

**Comment by manucorporat** [comment]
Hammerjs can still be added to any angular application: https://blog.angularindepth.com/gestures-in-an-angular-application-dde71804c0d0

Ionic 4 will not provide it by default in order to keep bundle as small as possible.
Exporting a ionic gesture controller could be done, but it requires extensive design work to come up with a good public API.
