### ISSUE TITLE
Is `@angular/http` required in ionic starter?

### ISSUE THREAD

**Issue by surajrao** [ionic-team/ionic#14303]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
The current Ionic 3.x starter app seems to install a dependency [@angular/http](https://github.com/ionic-team/starters/blob/master/ionic-angular/base/package.json#L21) which according to the docs [is deprecated](https://angular.io/api/http/Http).
The newer API is already present in the `@angular/common` package which is present in the [starter app](https://github.com/ionic-team/starters/blob/master/ionic-angular/base/package.json#L16).

Also `ionic g provider newProvider` inserts the newer `@angular/common/http`

**Note**: Locally removing the package does not throw any compilation issues.

Is this package required somewhere where I am not seeing?

**Comment by mburger81** [comment]
I'm not sure why they continue do use `@angular/http,`  theoretically you should use instead `import { HttpClient, HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';` 

Not sure what think the team about it, but you can make a PR or a open a issue on the start project
https://github.com/ionic-team/starters

**Comment by surajrao** [comment]
@mburger81 thanks! But I would like to know from ionic whether its needed or not before I submit a PR there.

**Comment by mhartington** [comment]
Technically, no it's not required for client side apps. This will be removed for ionic-angular starters, and is no longer added for `ionic/angular` starter projects. Thanks!
