### ISSUE TITLE
Actionsheet not working in v4 with angular

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [ionic-team/ionic#14314]
**Just copied the actionsheet usage code for angular but not able to present the actionsheet.**

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

ERROR TypeError: actionSheet.present is not a function

**Expected behavior:**

actionsheet.present should be working normally and actionsheet should open

**Steps to reproduce:**

**Related code:**

```
const actionSheet = this.actionSheetController.create({
      header: 'Albums',
      buttons: [{
        text: 'Delete',
        role: 'destructive',
        icon: 'trash',
        handler: () => {
          console.log('Delete clicked');
        }
      }, {
        text: 'Share',
        icon: 'share',
        handler: () => {
          console.log('Share clicked');
        }
      }, {
        text: 'Play (open modal)',
        icon: 'arrow-dropright-circle',
        handler: () => {
          console.log('Play clicked');
        }
      }, {
        text: 'Favorite',
        icon: 'heart',
        handler: () => {
          console.log('Favorite clicked');
        }
      }, {
        text: 'Cancel',
        icon: 'close',
        role: 'cancel',
        handler: () => {
          console.log('Cancel clicked');
        }
      }]
    });

    actionSheet.present();
```

**Comment by manucorporat** [comment]
this.actionSheetController now returns a promise:

```
const actionSheet = await this.actionSheetController.create({
      header: 'Albums'
    });

await actionSheet.present();
```

**Comment by ASHFAQPATWARI** [comment]
@manucorporat  shouldn't this be handled in usage docs, may be in upcoming release, and then close it ?
