### ISSUE TITLE
Background plugin not compatible with ImagePicker plugin

### ISSUE THREAD

**Issue by deounix** [ionic-team/ionic#14316]
**Ionic version:**
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**
[ x ] bug report
[ ] feature request

**Current behavior:**
Background plugin not compatible with ImagePicker plugin

**Expected behavior:**
ImagePicker  shouldn't return empty array

ImagePicker work good with out Background plugin but when I install Background plugin with or without adding it to `app.module.ts` ImagePicker return empty array.

**Comment by ghenry22** [comment]
You should log an issue against the background plugin repo or the image picker repo as the issue would be with the plugins not with ionic.
