### ISSUE TITLE
Testing Ionic 4 - Slides indicator moves into the picture on resize

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic#14315]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

(or is it a feature request ???)

**Current behavior:**
Slides indicator moves into the picture on resize

**Expected behavior:**
It should stay below the picture

**Steps to reproduce:**

**Related code:**

A sample application via GitHub

Code: https://github.com/peterennis/aeion4
Demo: https://aeion4.adaept.com/

**Comment by paulstelzer** [comment]
Thanks for your issue! This should fixed in latest `@ionic/angular@beta.17`! You also have to add some css if it's not working correctly
