### ISSUE TITLE
Menu Registration Doesn't Work Right With Shadow DOM

### ISSUE THREAD

**Issue by danbucholtz** [ionic-team/ionic#14312]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
When you have `shadow: true` set in Stencil, this code fails always. When you have it set to false, it works as expected.

https://github.com/ionic-team/ionic/blob/master/core/src/components/menu/menu.tsx#L136-L138

I believe this does not work because you cannot query into a host element that has shadow dom enabled. This is just a theory.

**Expected behavior:**
It should correctly register the menu.

**Steps to reproduce:**
1. Create component with stencil with `shadow: true` set
2. Add Menu
3. Add peer element with `main` attribute set.
4. Execute code, see bug
5. Set `shadow: false` and see it work as expected.

Thanks,
Dan

**Comment by manucorporat** [comment]
I think this is already fixed! please let me know if it's not
