### ISSUE TITLE
Ionic build command is not progressing after showing ":app:mergeArm64DebugResources" in console

### ISSUE THREAD

**Issue by khaled-ansary** [ionic-team/ionic#14313]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**

I have tried to build my ionic app but it is not progressing after  showing ":app:mergeArm64DebugResources" in console i.e. the building process continue forever. I wait to see any result for about 5-10 min but the building process are still in that line. 
**Expected behavior:**

Want to build the ionic app
**Steps to reproduce:**

**Related code:**
I have tried the following

`> ionic cordova build android

Running app-scripts build: --platform android --target cordova
[09:27:12]  build dev started ...
[09:27:13]  clean started ...
[09:27:13]  clean finished in 88 ms
[09:27:13]  copy started ...
[09:27:13]  deeplinks started ...
[09:27:13]  deeplinks finished in 9 ms
[09:27:13]  transpile started ...
[09:27:20]  transpile finished in 6.61 s
[09:27:20]  preprocess started ...
[09:27:20]  preprocess finished in 1 ms
[09:27:20]  webpack started ...
[09:27:20]  copy finished in 7.39 s
[09:27:32]  webpack finished in 12.24 s
[09:27:32]  sass started ...
[09:27:34]  sass finished in 1.55 s
[09:27:34]  postprocess started ...
[09:27:36]  postprocess finished in 1.90 s
[09:27:36]  lint started ...
[09:27:36]  build dev finished in 23.37 s
> cordova build android
cordova-android-support-gradle-release.after-prepare: Wrote custom version '27.+' to G:\test\test-ionic-app\platforms\android\build.gradle
cordova-android-support-gradle-release.before-prepare: Wrote custom version '27.+' to G:\test-test\test-ionic-app\platforms\android\cordova-android-support-gradle-release\properties.gradle
Android Studio project detected

cordova-android-support-gradle-release.after-prepare: Wrote custom version '27.+' to G:\test\test-ionic-app\platforms\android\build.gradle
ANDROID_HOME=C:\Users\ka\AppData\Local\Android\Sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_121
studio
Subproject Path: CordovaLib
Subproject Path: app

Could not find implementations for the following rules specified in the configuration:
    directive-selector
    component-selector
    use-input-property-decorator
    use-output-property-decorator
    use-host-property-decorator
    no-input-rename
    no-output-rename
    use-life-cycle-interface
    use-pipe-transform-interface
    directive-class-suffix
    no-access-missing-member
    templates-use-public
    invoke-injectable
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.

Starting a Gradle Daemon, 6 busy Daemons could not be reused, use --status for details

[09:27:43]  lint finished in 7.45 s
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
null
+-----------------------------------------------------------------
| cordova-android-support-gradle-release: 27.+
+-----------------------------------------------------------------
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_9mmqhxln4ueqqp69gop94w6ki.run(G:\test\test-ionic-app\platforms\android\app\build.gradle:145)

org.xwalk:xwalk_core_library:22+
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
:CordovaLib:preBuild
UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugAidl
 UP-TO-DATE

:CordovaLib:compileDebugRenderscript
 UP-TO-DATE
:CordovaLib:checkDebugManifest
 UP-TO-DATE
:CordovaLib:generateDebugBuildConfig
 UP-TO-DATE
:CordovaLib:prepareLintJar UP-TO-DATE
:CordovaLib:generateDebugResValues

UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources
 UP-TO-DATE

:CordovaLib:platformAttrExtractor UP-TO-DATE
:CordovaLib:processDebugManifest
 UP-TO-DATE
:CordovaLib:processDebugResources
 UP-TO-DATE

:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:javaPreCompileDebug UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac
 UP-TO-DATE
:CordovaLib:processDebugJavaRes NO-SOURCE
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
 UP-TO-DATE

:app:preBuild UP-TO-DATE
:app:preArm64DebugBuild

Download https://maven.google.com/com/android/support/support-v4/27.1.1/support-v4-27.1.1.pom

Download https://maven.google.com/com/android/support/support-compat/maven-metadata.xml

Download https://maven.google.com/com/android/support/support-compat/27.1.1/support-compat-27.1.1.pom

Download https://maven.google.com/com/android/support/support-media-compat/maven-metadata.xml

Download https://maven.google.com/com/android/support/support-media-compat/27.1.1/support-media-compat-27.1.1.pom

Download https://maven.google.com/com/android/support/support-core-utils/maven-metadata.xml

Download https://maven.google.com/com/android/support/support-core-utils/27.1.1/support-core-utils-27.1.1.pom

Download https://maven.google.com/com/android/support/support-core-ui/maven-metadata.xml

Download https://maven.google.com/com/android/support/support-core-ui/27.1.1/support-core-ui-27.1.1.pom

Download https://maven.google.com/com/android/support/support-fragment/maven-metadata.xml
Download https://maven.google.com/com/android/support/support-fragment/27.1.1/support-fragment-27.1.1.pom
Download https://maven.google.com/com/android/support/support-annotations/maven-metadata.xml

Download https://maven.google.com/com/android/support/support-annotations/27.1.1/support-annotations-27.1.1.pom

Download https://maven.google.com/com/android/support/support-fragment/27.1.1/support-fragment-27.1.1.aar

Download https://maven.google.com/com/android/support/support-media-compat/27.1.1/support-media-compat-27.1.1.aar

Download https://maven.google.com/com/android/support/support-core-ui/27.1.1/support-core-ui-27.1.1.aar

Download https://maven.google.com/com/android/support/support-v4/27.1.1/support-v4-27.1.1.aar

Download https://maven.google.com/com/android/support/support-core-utils/27.1.1/support-core-utils-27.1.1.aar

Download https://maven.google.com/com/android/support/support-compat/27.1.1/support-compat-27.1.1.aar

:app:compileArm64DebugAidl
UP-TO-DATE
:CordovaLib:packageDebugRenderscript

NO-SOURCE
:app:compileArm64DebugRenderscript
 UP-TO-DATE

:app:checkArm64DebugManifest UP-TO-DATE
:app:generateArm64DebugBuildConfig UP-TO-DATE
:app:prepareLintJar UP-TO-DATE
:CordovaLib:mergeDebugShaders
 UP-TO-DATE
:CordovaLib:compileDebugShaders UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
 UP-TO-DATE

:app:mergeArm64DebugShaders UP-TO-DATE
:app:compileArm64DebugShaders UP-TO-DATE
:app:generateArm64DebugAssets UP-TO-DATE
:app:mergeArm64DebugAssets

:app:createXwalkCommandLineFileArm64Debug

:app:generateArm64DebugResValues UP-TO-DATE
:app:generateArm64DebugResources
UP-TO-DATE
:app:mergeArm64DebugResources
`
after `:app:mergeArm64DebugResources`, the building process is not progress anymore

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

`
ionic info

cli packages: (C:\Users\ka\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 7.1.0 ios 4.5.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.1
    npm               : 5.8.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\ka\AppData\Local\Android\Sdk

Misc:

    backend : pro

`
**Dependencies `package.json`**
`
"dependencies": {
    "`@`angular/animations": "^5.2.0",
    "`@`angular/common": "^5.2.0",
    "`@`angular/compiler": "^5.2.0",
    "`@`angular/compiler-cli": "5.0.0",
    "`@`angular/core": "^5.2.0",
    "`@`angular/forms": "^5.2.0",
    "`@`angular/http": "^5.2.0",
    "`@`angular/platform-browser": "^5.2.0",
    "`@`angular/platform-browser-dynamic": "^5.2.0",
    "`@`angular/router": "^5.2.0",
    "`@`ionic-native/core": "^4.3.1",
    "`@`ionic-native/in-app-browser": "^4.3.1",
    "`@`ionic-native/splash-screen": "^4.3.1",
    "`@`ionic-native/status-bar": "^4.3.1",
    "`@`ionic/storage": "2.1.3",
    "angular-gridster2": "^3.9.0",
    "angular-oauth2-oidc": "^3.1.4",
    "chart.js": "2.5.0",
    "cordova-android": "7.1.0",
    "cordova-android-support-gradle-release": "^1.3.0",
    "cordova-ios": "^4.5.2",
    "cordova-plugin-crosswalk-webview": "^2.4.0",
    "cordova-plugin-device": "^1.1.7",
    "cordova-plugin-inappbrowser": "^1.7.2",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.1.19",
    "cordova-plugin-splashscreen": "^4.1.0",
    "cordova-plugin-statusbar": "^2.4.1",
    "cordova-plugin-whitelist": "^1.3.3",
    "core-js": "^2.4.1",
    "crypto-js": "^3.1.9-1",
    "d3": "3.5.17",
    "flag-icon-css": "2.9.0",
    "font-awesome": "^4.7.0",
    "fullcalendar": "^3.9.0",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "moment": "2.18.1",
    "ng-dynamic-component": "^2.0.0",
    "ng-pick-datetime": "^5.2.1",
    "ng2-bootstrap-modal": "^1.0.1",
    "ng2-charts": "1.5.0",
    "ng2-dnd": "^5.0.2",
    "ng2-dragula": "^1.3.0",
    "ng2-nvd3": "^2.0.0",
    "ng2-pdf-viewer": "^4.1.2",
    "ng2-tree": "^2.0.0-rc.4",
    "ng2-validation": "^4.2.0",
    "ngx-bootstrap": "1.6.6",
    "ngx-loading": "^1.0.14",
    "ngx-pipes": "^2.1.2",
    "ngx-simple-modal": "^1.3.3",
    "nvd3": "1.8.5",
    "primeng": "^5.2.1",
    "rxjs": "5.5.2",
    "simple-line-icons": "^2.4.1",
    "sw-toolbox": "3.6.0",
    "ts-helpers": "1.1.2",
    "tslib": "^1.9.0",
    "underscore": "^1.8.3",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.5",
    "typescript": "~2.5.3"
  },
  "cordova": {
    "platforms": [
      "ios",
      "android"
    ],
    "plugins": {
      "cordova-plugin-crosswalk-webview": {
        "XWALK_VERSION": "22+",
        "XWALK_LITEVERSION": "xwalk_core_library_canary:17+",
        "XWALK_COMMANDLINE": "--disable-pull-to-refresh-effect",
        "XWALK_MODE": "embedded",
        "XWALK_MULTIPLEAPK": "true"
      },
      "cordova-plugin-device": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-android-support-gradle-release": {
        "ANDROID_SUPPORT_VERSION": "27.+"
      }
    }
  }
`

**Comment by paulstelzer** [comment]
This issue is related to Apache Cordova
