### ISSUE TITLE
NavController or ViewController does not work when I do a new build for production

### ISSUE THREAD

**Issue by wilfredonoyola** [ionic-team/ionic#14311]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

**Current behavior:**

`ionic cordova run ios --prod` 
The app works correctly But I see a mistake when I want to get info about a view, for example :

`isSamePage(page: any){
      return this.currentPage.name === page.name;
  }`

This case 
` ionic cordova run ios --prod (does not work)
   this.current.name returns 'n' and page.name returns 'n'

  ionic cordova run ios (It works!)`

**Expected behavior:**

It should work for both environment (development and production) 

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/wilfredonoyola/workspace/statusfy/sf-ionic-1/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.3
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v6.11.3
    npm               : 3.10.10 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/wilfredonoyola/Library/Android/sdk/

Misc:

    backend : pro

```

**Comment by ramkrishna70** [comment]
Hi,
Are you able to run app in normal build.
