### ISSUE TITLE
ion-cordova-platform typo. Can't call platform.ready()

### ISSUE THREAD

**Issue by michele-franchi** [ionic-team/ionic#14317]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

Platform.js inside @ionic/core at line 91 has a typo: ion-cordova-plaform. If you call platform.ready() it doesn't work.

**Expected behavior:**

 const cordovaPlatform = this.el.querySelector('ion-cordova-platform');

**Steps to reproduce:**

**Related code:**

```
  constructor(platform: Platform) {
    platform.ready().then(() => {
    });
  }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/michele/.nvm/versions/node/v8.9.4/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.4
   ionic (Ionic CLI) : 4.0.0-rc.4

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.5.5
   @angular-devkit/schematics : 0.5.5
   @angular/cli               : 6.0.0-rc.4
   @ionic/schematics-angular  : 1.0.0-rc.4
   Cordova Platforms          : android 7.0.0
   Ionic Framework            : @ionic/angular 4.0.0-alpha.1

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   NodeJS            : v8.9.4
   npm               : 5.7.1
   OS                : macOS Sierra
   Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

   ANDROID_HOME : /Users/michele/Library/Android/sdk
```

**Comment by manucorporat** [comment]
` ion-cordova-plaform` does not longer exist, the ionic/angular provider should work the same as it did in ionic v3
