### ISSUE TITLE
Popover: present popover from click

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#14324]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Presenting a popover with an event `popover.present({ ev });` presents it on the event target, from the start.

**Expected behavior:**
Should open popover from the mouse click, or allow for opening from the end of the element.

**Steps to reproduce:**
Create a date-time input in an ion-item, catch the click event, prevent default and try to show a popover.

```
cli packages: (D:\dev\apps\locals-menu\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v9.7.1
    npm  : 5.3.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by AmitMY** [comment]
Jenky fix:
```
    const mockEvent = {
          target : {
            getBoundingClientRect : () => {
              return {
                top: (ev.target as any).getBoundingClientRect().top,
                left: ev.pageX
              };
            }
          }
        };
        popover.present({ ev: mockEvent });
```

**Comment by manucorporat** [comment]
interesting, i think this could be implemented in popover without a mock event

cc @brandyscarney @bensperry
