### ISSUE TITLE
La app se minimiza en IOS no avanza del Splash Screen

### ISSUE THREAD

**Issue by jonathanquinonez** [ionic-team/ionic#14332]
##    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-sim : 6.1.2 
    Node    : v8.9.4
    npm     : 5.6.0 
    OS      : macOS High Sierra
    Xcode   : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

--------------------
Creo el .ipa , lo subo a itunes connect para iniciar las pruebas,  en el xcode no presenta ningún error, cuando hago las pruebas por TestFlight, el usuario descarga la app y al abrirla muestra el splashScreen,  se minimiza, y no avanza de ahí.

no me proporciona ningún mensaje de error,  entonces he intentado muchas cosas y no he tenido solución.

**Comment by paulstelzer** [comment]
Please ask in English!
