### ISSUE TITLE
Ionic Build for Production Breaks UI in iOS 11.3

### ISSUE THREAD

**Issue by alejandro-heredia-coderoad-com** [ionic-team/ionic#14349]
**Ionic version:**
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request

**Current behavior:**
Building the application for production breaks the UI interaction (inputs, buttons, forms elements, keyboard) in iOS 11.3. 

**Expected behavior:**
Building for production should result in the application build working even more performant than in development.

**Steps to reproduce:**
Build the application for production with the --prod flag in an iOS 11.3 device.

**Related code:**

```javascript 
ionic cordova run ios --prod --device
```
**Other information:**
I've already tested with different versions of the **app-scripts** module since I'm aware of the related reported issue [13718](https://github.com/ionic-team/ionic/issues/13718). So I also tested **uglify-es:3.2.2** version independently as a dev-dependency.

**Ionic info:**

```
@ionic/cli-utils  : 1.19.2
ionic (Ionic CLI) : 3.20.0

global packages:

cordova (Cordova CLI) : 7.1.0 / 8.0.0 (tested with both versions)
local packages:

@ionic/app-scripts : 3.1.7 / 3.1.8  (tested with both versions)
Cordova Platforms  : android 6.3.0 ios 4.5.4
Ionic Framework    : ionic-angular 3.9.2
System:

Android SDK Tools : 26.1.1
ios-deploy        : 1.9.2 
ios-sim           : 6.1.2 
Node              : v8.11.1
npm               : 5.6.0 
OS                : macOS High Sierra
Xcode             : Xcode 9.3 Build version 9E145 
```

**Comment by alexmgrant** [comment]
My guess is with ionic 4 releasing soon, some/all of these issues are resolved. I'd hang tight and take a look at the master branch for `ionic-angular` for upcoming breakage and changes.
