### ISSUE TITLE
Where's v4 docs

### ISSUE THREAD

**Issue by iget-master** [ionic-team/ionic#14345]
Not using the template since it's not a bug, but a pertinent question:

Where is the v4 docs? There's any online hosted docs for it?

We are now stuck on v3 with many bugs, and cannot start migrating to v4 since it's undocumented!

**Comment by michele-franchi** [comment]
You can learn a lot of things from this example:
https://github.com/ionic-team/ionic-conference-app/tree/core-update

**Comment by iget-master** [comment]
@michele-franchi Yes, but it's far of being a documentation. 

I'd like the Laravel framrework approach about documentation: even before the new version release, the documentation is already available. You can choose to see "MASTER" documentation. Of course that it isn't updated realtime, but it's as soon as possible.

**Comment by brandyscarney** [comment]
The v4 documentation is not published yet, but you can find each component's documentation in its source folder. For example, the action sheet documentation is in the `readme.md` file here:

https://github.com/ionic-team/ionic/tree/master/core/src/components/action-sheet

and usage in angular is in `angular.md` here:

https://github.com/ionic-team/ionic/tree/master/core/src/components/action-sheet/usage

All components can be found here: https://github.com/ionic-team/ionic/tree/master/core/src/components

We're actively developing the documentation site for v4. We also have an upgrade guide here: https://docs.google.com/document/d/1hQzp0Z2gRHN5aoMCv-RCqSEe2DmSNUPoTxbt-bQEwb0/edit

v4 is still in early alpha though, so we don't recommend using it in a production app.
