### ISSUE TITLE
Ionic tabs break after page reload

### ISSUE THREAD

**Issue by ildar-icoosoft** [ionic-team/ionic#14344]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ *] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ *] bug report
[ ] feature request

**Current behavior:**
I have an application with tabs page.

Tabs page:

```
@Component({
  selector: 'page-tabs',
  template: `
    <ion-tabs>
      <ion-tab root="HomePage" tabTitle="Home" tabUrlPath="home-tab" tabIcon=""></ion-tab>
      <ion-tab root="NewsPage" tabTitle="News" tabUrlPath="news-tab" tabIcon=""></ion-tab>
    </ion-tabs>
 `
})
export class TabsPage {
}
```

HomePage:

```
@IonicPage()
@Component({
  selector: 'page-home',
  template: `
  	some content
  `
})
export class HomePage {
}
```

NewsPage:

```
@IonicPage()
@Component({
  selector: 'page-news',
  template: `
  	some content
  `
})
export class NewsPage {
}
```

When a tab is opened then URL is changed to: http://localhost/#/home-tab/home
After page reload then URL is changed to: http://localhost/#/home and there is no tabs

**Expected behavior:**
URL must not be changed after page reload

**Comment by HardikDG** [comment]
@ildar-icoosoft  I am also having the same issue. Please let me know if you find any solution for it

**Comment by ildar-icoosoft** [comment]
@HardikDG I had this error because in my TabsPage class HomePage and NewsPage were imported classes:
```
import {HomePage} from '.....';
import {NewsPage} from '.....';

@Component({
  selector: 'page-tabs',
  template: `
    <ion-tabs>
      <ion-tab root="HomePage" tabTitle="Home" tabUrlPath="home-tab" tabIcon=""></ion-tab>
      <ion-tab root="NewsPage" tabTitle="News" tabUrlPath="news-tab" tabIcon=""></ion-tab>
    </ion-tabs>
 `
})
export class TabsPage {
    HomePage = HomePage;
    NewsPage = NewsPage;
}
```
Instead, the links must be strings:
```
export class TabsPage {
    HomePage = 'HomePage';
    NewsPage = 'NewsPage';
}
```
