### ISSUE TITLE
Does not compile when TypeScript strict mode is enabled

### ISSUE THREAD

**Issue by sinedied** [ionic-team/ionic#14358]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
When typescript `strict` option is enabled in `tsconfig.json`, I have this compilation error:
```
20 04 2018 09:03:00.396:ERROR [karma]: Error: node_modules/ionic-angular/util/base-input.d.ts(23,22): error TS2420: Class 'BaseInput<T>' incorrectly implements interface 'CommonInput<T>'.
  Types of property 'ionFocus' are incompatible.
    Type 'EventEmitter<BaseInput<T>>' is not assignable to type 'EventEmitter<CommonInput<T>>'.
      Types of property 'observers' are incompatible.
        Type 'Observer<BaseInput<T>>[]' is not assignable to type 'Observer<CommonInput<T>>[]'.
          Type 'Observer<BaseInput<T>>' is not assignable to type 'Observer<CommonInput<T>>'.
            Type 'CommonInput<T>' is not assignable to type 'BaseInput<T>'.
```
This used to works, but I don't know exactly which version of `ionic-angular` caused the regression.

**Expected behavior:**
App should build properly with  typescript `strict` option enabled

**Steps to reproduce:**
1. clone this repo
2. switch to the `cordova/ionic` branch
3. `npm install`
4. add `"strict": true` in `tsconfig.json` compiler's options
5. `npm run build`

**Related code:**
I cannot use StackBlitz as tsconfig.json file is inaccessible.

**Other information:**
I use `ionic-angular@3.9.2` without the ionic CLI.

**Comment by manucorporat** [comment]
It's unlikely this will be fixed for ionic 3.9.x, since it's not longer a problem in ionic 4
