### ISSUE TITLE
More than 72 SCSS $colors map entries causes strange CSS issues

### ISSUE THREAD

**Issue by snortblt** [ionic-team/ionic#14352]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

**Current behavior:**
More than 72 SCSS $colors map entries causes strange CSS issues; Overridden class not displaying correctly. 

**Expected behavior:**
Expect to be able to add unlimited color keys to color map or at least a very large number

**Steps to reproduce:**
Results may be unpredictable due to strange and random nature of the issue. No error is given. 
1. Create an ionic project
2. Override some styles in your app.scss (was not honoring .`col{ padding: 0}` in my project. Other classes rendered correctly)
3. Build, run and verify styles display as set
4. Add > 72 color entries (top level keys) to color map
5. Build, run and verify styles are wonky

Tried deleting an existing style and adding the same one initially attempted. This works. The bug also manifests even if the 73rd color is not even referenced.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v6.11.3
    npm               : 3.10.10
    OS                : macOS High Sierra
    Xcode             : Xcode 9.3 Build version 9E145

Environment Variables:

    ANDROID_HOME : /Users/josh/Library/Android/sdk

Misc:

    backend : legacy
```

**Comment by brandyscarney** [comment]
Thanks for the issue! We do not recommend using that many colors in the colors map. Each color you add will generate about 1200 selectors in the CSS. This may be the issue you're running into: https://github.com/ionic-team/ionic-app-scripts/issues/506

I would recommend creating your own colors map if you are not using the colors to style Ionic components via the `colors` attribute.

**Comment by snortblt** [comment]
Ha ha! Thanks Brandy. Yes that would be a lot of selectors, which may explain why the SASS compiler is so slow lately. A second map should work fine in this case. 

BTW, it seems pretty intuitive to just add to the existing map for custom styling (not theming), and apparently that's an assumption others have made too. A warning in the docs would be nice, since the existing themes are pretty inadequate for anything but vanilla apps. I had no idea this would be generating a selector for every color use case in Ionic.

**Comment by brandyscarney** [comment]
@snortblt Thanks for the suggestion! I created an issue for the site here: https://github.com/ionic-team/ionic-site/issues/1361

We have redone theming for v4, so I don't believe this will be an issue anymore but I need to confirm that. Here's a sneak peek at the new theming docs: https://github.com/ionic-team/ionic-docs/tree/master/src/docs-content/theming

I am going to close this since it is resolved. 🙂
