### ISSUE TITLE
setRoot() on ion-router-outlet doesn't use {animate: false}

### ISSUE THREAD

**Issue by modemlooper** [ionic-team/ionic#14361]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
Passing {animate: false} to ion-router-outlet via navCtrl.setRoot(page, null , {animate: false}) doesn't work. The code is setting the animation boolean from the ion-router-outlet component and doesn't update it because its using this.animated.

it stops animation if you pass in 0 duration navCtrl.setRoot(page, null , {duration: 0})

The code however has an || checking both. 

https://github.com/ionic-team/ionic/blob/master/core/src/components/router-outlet/route-outlet.tsx#L123

**Expected behavior:**
Passing navCtrl.setRoot(page, null , {animate: false}) should stop the router from animating

**Steps to reproduce:**

**Related code:**

```
  async noAnimate( page ) {
      const navCtrl: HTMLIonNavElement = await (this.nav as any).componentOnReady();
      navCtrl.setRoot(page, null , {animate: false});
  }

<ion-item onClick={()=> this.noAnimate('app-home')}>
 <ion-label>
   home
 </ion-label>
</ion-item>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by manucorporat** [comment]
fixed https://github.com/ionic-team/ionic/commit/aa53563944de2af1a1cd48d938513679cfb067db
