### ISSUE TITLE
Ionic4.alpha.2: Breaking change, missing Document.resume and Document.pause

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#14360]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
At the moment it seems, `pause` and `resume` are not implemented on angular's `Platform`. https://github.com/ionic-team/ionic/blob/2b3c14b608d1fb6c41b469e7ed3f001f40d62d5a/angular/src/providers/platform.ts

**Expected behavior:**
I think having a look to the v2/v3. docs https://ionicframework.com/docs/api/platform/Platform/ and at the sourcecode of v4 there are also other functions which probably at the moment are not implemented.

I think some of this features, like the pause and resume for us are very important.

Not sure if this breaking changes is an accident or wanted. I hope the first one. :)

**Comment by manucorporat** [comment]
fixed https://github.com/ionic-team/ionic/commit/c929dad2e930b809feda07ffbb4c4c2a0ef59335
