### ISSUE TITLE
Using ion-router-outlet with ion-menu

### ISSUE THREAD

**Issue by cwoolum** [ionic-team/ionic#14363]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

I am trying to use ion-router-outlet with ion-menu. I receive the error ```Menu: must have a "content" element to listen for drag events on.```

**Expected behavior:**

I would expect the menu to work with the ion-router-outlet. I also think the message might need to be updated to reflect the actual property that needs set.

**Steps to reproduce:**

Looking at the code for ion-menu, it looks like only a contentId property exists now or it seems you can use a [main] attribute on the menu as well but I have tried both and the error still pops up.

**Related code:**

```
<ion-app>
  <ion-menu contentId="content">
    <ion-header>
      <ion-toolbar>
        <ion-title>Menu</ion-title>
      </ion-toolbar>
    </ion-header>

    <ion-content>
      <ion-list>
        <div>
          <button menuClose ion-item>
            My Button
          </button>
        </div>  
      </ion-list>
    </ion-content>
  </ion-menu>

  <ion-router-outlet #content></ion-router-outlet>
</ion-app>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\slick\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.5
   ionic (Ionic CLI) : 4.0.0-rc.5

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.5.5
   @angular-devkit/schematics : 0.5.5
   @angular/cli               : 6.0.0-rc.3
   @ionic/schematics-angular  : 1.0.0-rc.5
   Cordova Platforms          : android 6.4.0 browser 5.0.3
   Ionic Framework            : @ionic/angular 4.0.0-alpha.2

System:

   NodeJS : v8.11.1
   npm    : 5.6.0
   OS     : Windows 10

Environment Variables:

   ANDROID_HOME : not set

```

**Comment by manucorporat** [comment]
contentId actually means the ID of the main content:
```
<ion-router-outlet id="content"></ion-router-outlet>
```

**Comment by cwoolum** [comment]
Isn't the template reference ```#content``` the equivalent of ```id="content"```

**Comment by pedrotcm** [comment]
How can  i close the menu when click in ion-item? `menuClose` doesn't work. And also `swipeBackEnabled`.
`<ion-menu contentId="content">
  <ion-header>
    <ion-toolbar>
      <ion-title>Cadastro Pré-Pago</ion-title>
    </ion-toolbar>
  </ion-header>
  <ion-content>
    <ion-list>
      <ion-item menuClose button *ngFor="let p of pages" (click)="openPage(p)">
        {{p.title}}
      </ion-item>
    </ion-list>
  </ion-content>
</ion-menu>
<ion-router-outlet id="content" swipeBackEnabled="false"></ion-router-outlet>`
