### ISSUE TITLE
No margin on block buttons

### ISSUE THREAD

**Issue by mlynch** [ionic-team/ionic#14383]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

Using an `<ion-button>` with `block` does not add necessary margin around the button:

<img width="881" alt="screenshot 2018-04-24 09 51 26" src="https://user-images.githubusercontent.com/11214/39195262-13f15d6c-47a5-11e8-81ad-515a23ee86c8.png">

**Expected behavior:**

Margin around the button

**Steps to reproduce:**

```jsx
  render() {
    return [
      <ion-header>
        <ion-toolbar color='primary'>
          <ion-title>Amplify Login</ion-title>
        </ion-toolbar>
      </ion-header>,
      <ion-content>
        <form onSubmit={(e) => this.doSubmit(e)}>
          <ion-list>
            <ion-item>
              <ion-input type="email" placeholder="Email" value={this.username} onInput={(e: any) => this.username = e.target.value} />
            </ion-item>
            <ion-item>
              <ion-input type="password" placeholder="Password" value={this.password} onInput={(e: any) => this.password = e.target.value} />
            </ion-item>
            <ion-button expand="block" type="submit">Log in</ion-button>
          </ion-list>
        </form>
      </ion-content>
    ];
  }
```

Ionic Core 4.0.0-alpha.3

**Comment by brandyscarney** [comment]
What margin are you looking for? This is currently how v3 works: https://ionicframework.com/docs/api/components/button/Button/

**Comment by mlynch** [comment]
Ah, so to add padding you should have a wrapper with padding?
