### ISSUE TITLE
Ion Modal CSS makes custom modal sizes difficult

### ISSUE THREAD

**Issue by corysmc** [ionic-team/ionic#14392]
**Ionic version:**
[ ] **2.x**
[ ] **3.x**
[X] **4.x**

**I'm submitting a ...**
[ ] bug report
[X] feature request

**Current behavior:**
Current implementation of ion-modal positions the modal based on a fixed with and height. If I want to change the width/height of the modal, it requires a lot of css overrides.

**Expected behavior:**
Using flexbox the wrapper could use `align-items:center` and `justify content:center` that way any height or width change would still be centered.

**Steps to reproduce:**

**Related code:**

For the modal change the css to use flexbox
```
ion-modal {
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    position: absolute;
    contain: strict;
    display: flex;
    justify-content: center;
    align-items: center;
}
```

Then Change the modal-wrapper css
```
.modal-wrapper {
  width: 100%;
  height: 100%;
}
@media only screen and (min-height: 600px) and (min-width: 768px) {
  .modal-wrapper {
    width: 600px;
    height: 500px;
  }
}
```
With those changes adjusting width is much easier.

**Comment by IsaacSomething** [comment]
Dont you just need to change the top & left properties based on the change in height width?

    .test-modal {
        .modal-wrapper {
            width: 600px;
            left: calc(50% - (600px/2));
            height: 500px;
            top: calc(50% - (500px/2));
        }
     }
