### ISSUE TITLE
Status bar overlaps with header when navigate new page in modal

### ISSUE THREAD

**Issue by JackZhang1988** [ionic-team/ionic#14401]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**

![img_4181](https://user-images.githubusercontent.com/1697710/39391151-a422e75a-4ad1-11e8-86aa-e0694515deff.PNG)

I very same like the bug here: https://github.com/ionic-team/ionic/issues/13294, but the issue closed seems hard to reproduce, now i finally reproduced.

**Steps to reproduce:**

These bug happen when you nav a new page in a modal,  I have create repository for this: https://github.com/JackZhang1988/ionic_statusbar_bug

```
// in hello-ionic page ,you open modal
openModal() {
    let curModal = this.modalCtrl.create("Modal1Page");
    curModal.present();
  }

// the in modal page,  click a button to nav new page
 navModal2() {
    this.navCtrl.push('Modal2Page');
  }
```

run `sudo ionic cordova prepare ios`, and build on iPhone by Xcode.

then, you can reproduce the bug show as the picture.

i tried add newest `cordova-plugin-statusbar` but it is not work

**Ionic info:**
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2
    ios-sim           : 6.0.0
    Node              : v8.9.1
    npm               : 6.0.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.3 Build version 9E145

Environment Variables:

    ANDROID_HOME : /Users/jianbo/Library/Android/sdk

Misc:

    backend : pro

**ionic cordova plugin list**
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

**Comment by charlyBerthet** [comment]
Same problem, I had to use `this.viewCtrl.dismiss({goTo:pageName})` in the modal then push in the parent page like this : 
```
modal.onDidDismiss(data => {
          if(data && data.goTo){
             this.navCtrl.push(data.goTo);
          }
})
```

**Comment by JackZhang1988** [comment]
@charlyBerthet yes, your solution is right, but sometime i need to keep modal open when i nav to new page.

**Comment by derek90** [comment]
I'm having a similar problem. There are some solutions here: https://github.com/ionic-team/ionic/issues/8151

**Comment by ggobea** [comment]
Same problem!

**Comment by smxdevst** [comment]
This issue were open last year April and still weren't resolved...
