### ISSUE TITLE
dynamic tabs root not change

### ISSUE THREAD

**Issue by utpaul** [ionic-team/ionic#14402]
I'm building a apps using ionic 3. I have a requirement for switch one tabs to another tabs. I switch this tabs based on condition but my problem is that root page is not changes he takes cache previous active page. More specifically user are switch **page-admin-tabs** to **page-teachers-tabs**, page are switch but  selected root of page-admin-tabs show in page-teacher-tabs.

**Here i include my condition**

    if( item == 'ADMIN'){
      this.nav.setRoot('page-admin-tabs',{ tabIndex: 0 });
    } else if(item == 'TEACHER'){
      this.nav.setRoot('page-teachers-tabs',{ tabIndex: 0 });
    } else{
      if(this.auth.currentUser.user_flag == 2){
        this.nav.setRoot('page-teachers-tabs',{ tabIndex: 0 });
      }else{
        this.nav.setRoot('page-students-tabs',{ tabIndex: 0 });
      }
    }

**Comment by matejkramny** [comment]
you need to reference the class name not a string. Ie `this.nav.setRoot(PageAdminTabs)`
