### ISSUE TITLE
Deeplinker navigation not working

### ISSUE THREAD

**Issue by HardikDG** [ionic-team/ionic#14403]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**

I have added this to the IonicPage decorator

In the app.module I have set DeepLinker in the IonicModule.forRoot method for some other pages

```
@IonicPage({
  name: 'SamplePage',
  segment: 'Sample',
  defaultHistory: ['AboutPage']
})

export class SamplePage {
}
```
Now on the other page, I am trying to navigate to this page, but I am getting an error in doing that 

I am getting invalid link while I try to navigate to this page

The code i have tried for push is
```
this.navCtrl.push('SamplePage');
this.navCtrl.push('Sample');
this.navCtrl.push(SamplePage);
```

The first two is showing the invalid link while the third one shows entry component error. 

**Expected behavior:**

It should navigate to the sample page using the name decorator of the IonicPage 

**Steps to reproduce:**

I have just created 2 pages from the Ionic CLI which has an individual module for the page. now from one page, I am trying to navigate to the second page using IonicPage decorator name

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.13 
    Node              : v9.5.0
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.1 Build version 9B55 

Misc:

    backend : legacy

**Comment by solumyr** [comment]
I have the same issue.  I have a segment-bar and a menu on the same page, however, the menu bar is in a ion-navbar HTML element.  When I click on button on the menu, nav works.  When I click on a segment bar, outside of the ion-navbar, it throws me that error.  Maybe ion-navbar is the key here?  Also, I had two ion-navbars and it still didn't work.
