### ISSUE TITLE
Feature or Bug. Set ionic v3 button height to take 100% height in a row

### ISSUE THREAD

**Issue by Yerkon** [ionic-team/ionic#14418]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.20.0
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[x] feature request

**Current behavior:**

Please look at this SO question: https://stackoverflow.com/q/44248261/5677886. It's asked one year ago
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by lucasbasquerotto** [comment]
@Yerkon you can achieve that with css, just set the column (`ion-col`) as `flex` and the `button` height with `aut`o.

Solution to the SO question:

https://stackoverflow.com/a/50260148/4850646

**Comment by Yerkon** [comment]
Fixed, can be closed. Thanks @lucasbasquerotto .
