### ISSUE TITLE
Failed to load resource "ionic/ionic.dtdxjdv4.js:1" 

### ISSUE THREAD

**Issue by divanvb** [ionic-team/ionic#14416]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

Created a new Ionic V4 Sidemenu starter and upgrade to alpha.4 as stated in the app.module if released then tried running the app and received this error 
```ionic/ionic.dtdxjdv4.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)```

**Expected behavior:**

It should run without issues as it is clean project

**Steps to reproduce:**

1. ionic start --type=angular myApp sidemenu
2. Upgrade ionic to alpha.4
3. Uncomment list route in app.module.ts
4. ionic serve

**Related code:**

```
ionic/ionic.dtdxjdv4.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
local packages:

   @angular-devkit/core       : 0.5.11
   @angular-devkit/schematics : 0.5.11
   @angular/cli               : 6.0.0-rc.8
   @ionic/schematics-angular  : 1.0.0-rc.5
   Ionic Framework            : @ionic/angular 4.0.0-alpha.4

System:

   NodeJS : v9.11.1
   npm    : 5.6.0
   OS     : Windows 10
```

**Comment by divanvb** [comment]
Without upgrading, I now get this error with the sidemenu starter:
`GET http://localhost:8100/ionic/ionic.hckpwxgi.js 404 (Not Found)`

**Comment by divanvb** [comment]
Surely someone from Ionic can just give some sort of reply!

**Comment by mhartington** [comment]
Unable to replicate this with the latest release.

```
ionic start myApp sidemenu --type=angular
cd myApp
ionic serve
```

I would check the angular.json file to make sure the proper copy tasks are being setup.

**Comment by chaumo** [comment]
Sorry to reopen but I think the problem still persists, at least when trying to run any starter (tried with blank, tabs) on android device 
```
ionic start test tabs --type=angular
cd test
ionic serve
```
Ionic serve works, but when `ionic cordova run android` i only get a blank screen after the loading splash, and with chrome dev tools I see failed to load on every file (runtime.js, polyfill.js, cordova.js....) 

Weird thing is it works when run with the -l option
```
ionic cordova run -l android
```

**Comment by sailarg** [comment]
same issue here !!! today (10/08/2018) 

I only did 
`ionic start myApp tabs --type=angular`

Ionic serve works, but ionic cordova run android only get a blank screen

Ionic:

   ionic (Ionic CLI)          : 4.0.6 (C:\Users\Gary\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 6.5.0
   Cordova Platforms     : android 6.1.2

System:

   Android SDK Tools : 25.2.3
   NodeJS            : v8.11.3 (D:\nodejs\node.exe)
   npm               : 6.3.0
   OS                : Windows 10
