### ISSUE TITLE
@ionic/angular@4.0-alpha.4 content.scrollToBottom not worked.

### ISSUE THREAD

**Issue by snowyu** [ionic-team/ionic#14428]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[X] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**

It can not scroll to bottom.

**Expected behavior:**
It should scroll to bottom after called the `content.scrollToBottom()` method.

**Steps to reproduce:**

use the standard tabs starter demo and upgrade the package to `@ionic/angular@4.0-alpha.4`.

navigate to the contacts page and click the `down` button on the toolbar.

**Related code:**

`contacts.page.html`

```html
<ion-header>
  <ion-toolbar>
    <ion-title>
      Contact
    </ion-title>
    <ion-buttons slot="end">
      <ion-button (click)="addChat()">
        <ion-icon name="send" slot="ionc-only"></ion-icon>
      </ion-button>
      <ion-button (click)="toBottom()">
        <ion-icon name="arrow-down" slot="ionc-only"></ion-icon>
      </ion-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>

<ion-content>
  <ion-list>
    <ion-list-header>Follow us on Twitter</ion-list-header>
    <ion-item *ngFor="let chat of chats">
      <ion-icon name="logo-ionic" slot="start"></ion-icon>
      @ionicframework
    </ion-item>
  </ion-list>
</ion-content>

```
`contacts.page.ts`

```ts
import { Component, ViewChild } from '@angular/core';
import { Content } from '@ionic/angular';

@Component({
  selector: 'app-page-contact',
  templateUrl: 'contact.page.html',
  styleUrls: ['contact.page.scss']
})
export class ContactPage {
  @ViewChild(Content) content: Content;
  chats = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];

  toBottom(){
    console.log('toBottom');
    this.content.scrollToBottom();
  }

  addChat(){
    this.chats.push(0);
  }
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
   @ionic/cli-utils  : 2.0.0-rc.5
   ionic (Ionic CLI) : 4.0.0-rc.5

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.0
   @ionic/schematics-angular  : 1.0.0-rc.5
   Ionic Framework            : @ionic/angular 4.0.0-alpha.4

System:

   NodeJS : v8.11.1
   npm    : 5.6.0
   OS     : Linux 4.15
```

**Comment by brandyscarney** [comment]
Thank you for the issue! We are currently looking into issues related to the`ion-content` and `ion-scroll` components. I will add this to our project board. 

cc @manucorporat

**Comment by manucorporat** [comment]
Yes, this is fixed in master, beta.2 will include the fix this wednesday! thanks for the issue

**Comment by ohrrkan** [comment]
Since beta.3 we can find scrollToBottom in Content but  also get a : TypeError: this.content.scrollToBottom is not a function
