### ISSUE TITLE
ion-checkbox not working well with nav.setRoot

### ISSUE THREAD

**Issue by johnopaluwa** [ionic-team/ionic#14422]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request

**Current behavior:**
The checkbox in my app works well when I set the rootpage like this

```template: `<ion-nav [root]="rootPage"></ion-nav>` ```
```this.rootPage = HomePage;```

However I am setting the root page dynamically and it seems the best way to do it  is to use this
 ``` this.nav.setRoot(page);```  because using the first method leads to a white screen.

But using  ``` this.nav.setRoot(page);``` causes my checkbox  ```ion-checkbox``` to begin malfunctioning.( It gets check randomly).

**Expected behavior:**
Checkbox should be check-able   on tapping 

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**
I think this may be related to this - https://github.com/ionic-team/ionic/issues/11675

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 browser 5.0.3 ios 4.5.4 windows 4.4.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    Node       : v8.10.0
    npm        : 6.0.0
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by goldman94** [comment]
This seems related to an issue I'm having. I do a nav.push() to the same Ionic Page that the user is currently viewing, but with new data in params. The use case for this nav.push() is to capture searches in navigation history. When the view updates with the new search results, click events on my search page only have visible effect register after I move focus away from the browser then return to the browser. Click events are working fine in my navbar and footer components (wrappers for built-in navbar/footer components).

**Comment by johnopaluwa** [comment]
Solved the problem by injecting NgZone into the component. Code snapshot looks like this:
```
 this.zone.run(()=>{
          this.nav.setRoot(Login)
            splashScreen.hide();
        }) 
```
