### ISSUE TITLE
content inside ion-content does not appear on screen using ionic 4 via CDN

### ISSUE THREAD

**Issue by isaacabdel** [ionic-team/ionic#14432]
**Ionic version:**  **4.x**

**I'm submitting a ...**  bug report

**Current behavior:**

[ion-content](https://github.com/ionic-team/ionic/tree/master/core/src/components/content) is not displaying the components within. So while `<ion-button>button</ion-button>` might work `<ion-content><ion-button>button</ion-button></ion-content>` doesn't display. 

Inspecting the components reveals that the components inside ion-content does render but maybe due to a css issue they don't display on screen.

_here are some examples of the current behavior_:
https://stackblitz.com/edit/js-ypm733
https://glitch.com/edit/#!/neighborly-bison?path=views/index.html:54:5

locally:
```
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
</head>

<body>
  <ion-header>
    <ion-toolbar>
      <ion-title>Toolbar</ion-title>
    </ion-toolbar>
  </ion-header>

  <ion-content>

    <ion-card>
      <ion-card-header>
        Header
      </ion-card-header>
      <ion-card-content>
        The British use the term "header", but the American term "head-shot" the English simply refuse to adopt.
      </ion-card-content>
    </ion-card>

  </ion-content>

  <ion-footer>
    <ion-toolbar>
      <ion-title>Footer</ion-title>
    </ion-toolbar>
  </ion-footer>
  <script src="https://unpkg.com/@ionic/core@4.0.0-alpha.4/dist/ionic.js"></script>
</body>

</html>

```
**Expected behavior:**

expected behaivor is that the components within ion-content display.

**Steps to reproduce:**

1. adding ionic core via the CDN
   <script src="https://unpkg.com/@ionic/core@4.0.0-alpha.4/dist/ionic.js"></script>

**Other information:**

It seems to work fine when using the [ ionic pwa toolkit ](https://github.com/ionic-team/ionic-pwa-toolkit).

**Comment by airstep** [comment]
+1 but I'm trying to combine ionic core latest buid with vue.js in one project and there is no visible part in ion-content (it seems like it has zero width or in "hidden" mode")

**Comment by sntran** [comment]
I see the same issue, and here is what I have found out:

- You need to wrap everything with `<ion-app>`.
- If you use `<ion-page>`, it won't have a height. You need to use an element with class `ion-page` instead. This is probably a bug. It sets `flex: 1` to that element to make it take the remaining space.

**Comment by isaacabdel** [comment]
@sntran wrapping the app with `<ion-app>` does resolve the issue.

**Comment by sntran** [comment]
@airstep, see my second bullet point. There is no `<ion-page>` in alpha 4. Use class `ion-page` instead.

**Comment by stripathix** [comment]
I can't see footer on using ion-page

```
<ion-page>
  <ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-menu-button></ion-menu-button>
    </ion-buttons>
    <ion-title>
      Airport
    </ion-title>
  </ion-toolbar>
</ion-header>
<ion-content id="content" padding>
    Hello Airportss
</ion-content>
<ion-footer>
    <ion-toolbar>
      <ion-title>Footer</ion-title>
    </ion-toolbar>
  </ion-footer>
</ion-page>

```

<img width="760" alt="screen shot 2018-08-13 at 5 36 23 pm" src="https://user-images.githubusercontent.com/8480351/44030774-720bf534-9f1f-11e8-8e19-41249d758f77.png">
