### ISSUE TITLE
Cannot read property 'length' of undefined.

### ISSUE THREAD

**Issue by chrifrachid** [ionic-team/ionic#14435]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```
Home.ts
![home html](https://user-images.githubusercontent.com/16919684/39678641-287437f4-5188-11e8-8b1b-2b45f12a182a.jpg)

Home.html
![home html](https://user-images.githubusercontent.com/16919684/39678646-389055b4-5188-11e8-8871-a916abc447f3.jpg)

Data Provider
![provider ts](https://user-images.githubusercontent.com/16919684/39678649-494e36e6-5188-11e8-8380-c9a84950ebcc.jpg)

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
![error](https://user-images.githubusercontent.com/16919684/39678638-2294d2ee-5188-11e8-9e9f-a74da56a95bb.jpg)

**Comment by MattijsE** [comment]
The virtualscroll expects data to make it work.
The data only gets provided after the GET request has completed.

To fix this issue, initialize items as an empty array.
After the data has been fetched, the list will show the data.
