### ISSUE TITLE
v4:bug(back-button): misaligned back-button inside the toolbar

### ISSUE THREAD

**Issue by DavidWiesner** [ionic-team/ionic#14444]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
 * ion-back-button inside ion-buttons in a ion-toolbar is misaligned 
![daccfe6b-2c3b-489f-8cdf-38a45d2678d5](https://user-images.githubusercontent.com/243115/39754454-89e8ae6c-52c2-11e8-9e6e-00c5c02bf0f2.png)

**Expected behavior:**
 * ion-back-button should be centered vertically inside the toolbar with less margin
 * ion-title should be start at 72px from the client left

**Steps to reproduce:**

 * run: npm run dev
 * open: http://localhost:3333/src/components/back-button/test/basic 
 * navigate to page two

**Related code:**
```
.back-button-md {
    margin: 2px 6px 0 0;
    padding: 0 5px;
}
```

```
insert short code snippets here
```

**Other information:**

 * removing the margin the css class back-button-md will solve some of the problems but i do not know the implications to other ion-back-button usages 
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
@ionic/core@4.0.0-alpha.4 dev
```

**Comment by brandyscarney** [comment]
Thank you for the issue! I confirmed that the back button is aligning properly vertically now, but I'd like to look into the spacing more to match the spec still.

**Comment by paulstelzer** [comment]
@brandyscarney did you finished this since then?

**Comment by brandyscarney** [comment]
@paulstelzer No I think it is still off from the spec.

**Comment by brandyscarney** [comment]
I know the button spacing is definitely off, here's ours vs theirs

| Ionic | Material Design |
| ---| ---|
| ![localhost_3333_src_components_toolbar_test_spec galaxy s5 1](https://user-images.githubusercontent.com/6577830/49392741-53546a00-f6fd-11e8-90b9-fa345c9a8f7a.png) | ![material-components github io_material-components-web-catalog_ galaxy s5 1](https://user-images.githubusercontent.com/6577830/49392736-4e8fb600-f6fd-11e8-8eea-c4c56f9b28da.png) |
