### ISSUE TITLE
Feature request: Online cordova emulator to replace Ionic View? 

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic#14440]
Hello guys,

Recently, Apple have frustrated all of us by taking down Ionic View and PhoneGap test apps. 
How about you guys create an online cordova emulator which runs underneath a browser? so we can continue test our apps regardless of Apple's policy? 
If beta test emulator can run underneath a browser, you guys can bypass Apple App Store permanently.

This company for instance, has a browser emulator which runs underneath a browser.

www.browserling.com

Their browser emulator creates a virtual browser per each visitor. 

This kind of cordova emulator running on a browser will solve all the Apple hassles for the next ten years.

**Comment by mhartington** [comment]
Hi there! This issue does not appear to be an issue with the framework itself, so it will be closes. Please review your issue and open a new ticket on the appropriate project repository, or feel free to post a question on the [Ionic Forum](http://forum.ionicframework.com). Thanks!
