### ISSUE TITLE
GitHub integration doesn't list the repos I'm part of

### ISSUE THREAD

**Issue by vishu321** [ionic-team/ionic#14454]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[X] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
Connected to GitHub from Ionic Pro. No repositories listed.

**Expected behavior:**
All repositories that I have access to should be listed.

**Steps to reproduce:**
Connect to GitHub with an account that has no personal repos but that is part of an organization.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by mhartington** [comment]
Hi there! This sounds like an issue regarding ionic-pro, the paid services.

This repository and issue tracker are for the Framework and open source project. 

Please use one of paid support issue tools, [listed here](http://ionicframework.com/support#support) (account, bugs, using ionic services).

Thanks!
