### ISSUE TITLE
ion-infinite-scroll

### ISSUE THREAD

**Issue by xingzouzaiqian** [ionic-team/ionic#14455]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by mhartington** [comment]
Hi there! It appears that you've opened an issue, but have not provided the necessary information we require in order to debug. Im going to close this issue because of that. Please open a **new** issue and completely fill out the issue template. Thanks!
