### ISSUE TITLE
Strong typing with ComponentProps

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/ionic#14456]
# Feature Request

**Ionic Info**

```
cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0
System:
    Node : v8.9.1
    npm  : 5.7.1
    OS   : macOS High Sierra
Misc:
    backend : pro
```

**Describe the Feature Request**

There are various Ionic components that have properties or function parameters to specify a component and componentProps.  For example:

```tsx
ionNav.push(component: NavComponent, componentProps?: ComponentProps ...);
```

This can lead to fragile interfaces because the componentProps object is not strongly typed.  

Potential issues include:
- No intellisense when typing the properties.
- No type checking for property values.
- No refactoring if property names are changed.
- No design time or runtime errors for invalid properties.

**Describe Preferred Solution**

Allow the functions to support JSX content as an alternative calling syntax.

For example:

```tsx
// Method parameter example
ionNav.push(<my-component first="John" last="Smith" />);

// Component property example
<ion-popover component={<my-component first="John" last="Smith" />} />
```

This leverages the JSX type checking, intellisense, refactoring, etc.

There are many parts of ionic core (and router) that could benefit from this approach.
- `<ion-nav>`
- `<ion-popover>`
- `<ion-route>`
- `<ion-modal>`
- etc.

**Comment by manucorporat** [comment]
@cjorasch while I like the API you suggested, it might not play well with the router and it will require a mayor API refactor

however I have stated a branch added strong typing for componentProps!
https://github.com/ionic-team/ionic/tree/core-ts-components :slightly_smiling_face:

**Comment by manucorporat** [comment]
@cjorasch 
<img width="546" alt="screenshot 2018-08-27 at 00 45 16" src="https://user-images.githubusercontent.com/127379/44633946-94b4db00-a992-11e8-8ef6-7092e9726810.png">

**Comment by manucorporat** [comment]
Fixed https://github.com/ionic-team/ionic/commit/57d23753a628657045b664a34976f9e441b6d6a8
