### ISSUE TITLE
Ionic 3 - iOS device scrollbar visibility is inconsistant

### ISSUE THREAD

**Issue by rajeshi2i** [ionic-team/ionic#14461]
# Bug Report

**Ionic Info**

```
icli packages:

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2
```

**Describe the Bug**
In iOS touch devices, sometimes scrollbar is visible during scroll the content and sometimes not visible.

**Steps to Reproduce**
1. Created a new ionic project with Tabs Starter Templates
2. Add 1000 list on the contact page.
3. Try to scroll the list.
4. Switch different tabs and do the **Step 3** again

**Expected Behavior**
Scrollbar is always visible during scroll the content.

**Additional Context**
Please find the attachment for more details 

![1](https://user-images.githubusercontent.com/1394198/39938928-6cd40238-5509-11e8-89ce-17d428cb9990.gif)
![2](https://user-images.githubusercontent.com/1394198/39938929-6cf068ba-5509-11e8-88e8-e02182cdbd8a.gif)

**Comment by KevRyan2** [comment]
+1
