### ISSUE TITLE
v4: @ionic/angular: bug - platforms array is empty 

### ISSUE THREAD

**Issue by AhsanAyaz** [ionic-team/ionic#14465]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (/Users/ahsanayaz/.nvm/versions/node/v8.11.1/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.5.7
   @angular-devkit/schematics : 0.5.7
   @angular/cli               : 6.0.0-rc.5
   @ionic/schematics-angular  : 1.0.0-rc.5
   Cordova Platforms          : android 7.0.0 ios 4.5.4
   Ionic Framework            : @ionic/angular 4.0.0-alpha.6
```

**Describe the Bug**
 
The `platforms` or specifically `_platforms` array isn't populated on a v4 app. I've tested on browser as well as on devices. The steps to populate the platform are missing. I'll be raising a PR soon around that.

**Steps to Reproduce**
1. Import `Platform` in one of your v4 app's components as:
```javascript
import { Platform } from '@ionic/angular';

@Component({
    selector: 'app-todo-list',
    templateUrl: './todo-list.page.html',
    styleUrls: ['./todo-list.page.scss'],
})
export class TodoListPage implements OnInit {
  isAndroidDevice: boolean;
  constructor(
    private platform: Platform
  ) { }

  ngOnInit() {
    this.isAndroidDevice = this.platform.is('android');
    console.log(this.isAndroidDevice);
  }
}
```
2) Run the app on android using `ionic cordova run android` and debug using chrome devtools.
You'll see that the console.log would log `false`. The reason is that the `_platforms` array in the `ionic/angular/src/providers/platform.ts` is empty and isn't populated initially.

**Expected Behavior**
Should get the appropriate platform check back.

** Additional Details**
Attaching a snapshot here. App is running on a Nexus 5x device. Debugging via DevTools.

<img width="356" alt="screen shot 2018-05-13 at 5 20 45 pm" src="https://user-images.githubusercontent.com/9844254/39967344-cc3fc264-56d2-11e8-8f2f-7f3350b09447.png">

**Comment by manucorporat** [comment]
FIXED!
