### ISSUE TITLE
ADB device going offline

### ISSUE THREAD

**Issue by aishusarangapani** [ionic-team/ionic#14475]
I'm trying to deploy my ionic app to HONOR 5X phone. Before deploying i hv checked device status using 'adb devices' command. It's showing status "device" with ID. But at the end of deploying, my device status going to **"offline"** and skipping the build and then build failed with this error "(**node:1952) UnhandledPromiseRejectionWarning: Error: D:\My Android SDK\platform
tools\adb.exe: Command failed with exit code 1**".

**Comment by WillPoulson** [comment]
Hey @aishusarangapani I often get this, I solved it by using a different USB port on my Mac.

If that doesn't solve it. Try reinstalling adb or checking that you have the correct drivers if you're on Windows.
