### ISSUE TITLE
V4 - ion-item href not working correctly from ion-menu

### ISSUE THREAD

**Issue by danbucholtz** [ionic-team/ionic#14473]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
$ ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:

    Node : v8.11.1
    npm  : 6.0.0
    OS   : macOS High Sierra

Misc:

    backend : pro
```

**Describe the Bug**

When I make an `ion-list` with a few `ion-item` entries, the `href` attribute works awesomely.

When I do this from the context of an `<ion-menu>`, it doesn't work correctly.

```
<ion-list>
   <ion-item href="/about">
      <ion-label>Home</ion-label>
   </ion-item>
</ion-list>
```

Works great.

But this code inside of a menu doesn't work correctly.

```
<ion-menu side="start">
   <ion-content>
      <ion-list>
         <ion-item href="/about">
            <ion-label>Home</ion-label>
         </ion-item>
      </ion-list>
   </ion-content>
</ion-menu>
```

**Steps to Reproduce**
1. Create a stencil component with a menu that works as expected
2. Get the menu working with an `<ion-list>` and `<ion-items>`
3. Add the href
4. Observe the url does not update to the href value

Here's a repo to easily reproduce the issue:

```
git clone git@github.com:danbucholtz/tinkering.git
cd tinkering
npm install
npm run dev

Open chrome
Shrink size to pretty small such that top navigation shows a menu button
Give that menu entry a click
Observer the url doesn't update
```

Thanks,
Dan

**Comment by WillPoulson** [comment]
Hey @danbucholtz I've noticed that you've submitted this as a V4 bug however in your info you're running 3?

**Comment by paulstelzer** [comment]
Think this is fixed in beta.17. If not, just write here!

**Comment by guimleme** [comment]
I'm having the same issue in beta.17.

**Comment by paulstelzer** [comment]
please not use href as mentioned in todays changelog for beta.18 -> https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#400-beta18-2018-12-13

Always use routerLink from Angular. If it's not working, would you please open a new issue, fill out the form and add a repo?
