### ISSUE TITLE
[v4] Router not navigating in lazyloaded children

### ISSUE THREAD

**Issue by WillPoulson** [ionic-team/ionic#14478]
# Bug Report

**Ionic Info**

```
cli packages: (/usr/local/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.0
   @ionic/schematics-angular  : 1.0.0-rc.5
   Cordova Platforms          : android 7.0.0
   Ionic Framework            : @ionic/angular 4.0.0-alpha.3

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.11.1
   npm        : 6.0.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.3.1 Build version 9E501

Environment Variables:

   ANDROID_HOME : not set
```

**Router not navigating in lazyloaded children**
I've got the router navigation doing the following

> Remove following line in the AppModule.
> { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }

That got the router working however I'm running into issues when navigating into lazyloaded child pages where if I back out of them using the back button then the routerlinks no longer do anything, I've subscribed to the nav events and nothing happens other than the usual "ionRouterOutletActivated" that gets spit out in the console.

**Comment by danielehrhardt** [comment]
Yes same here!! Also happen if i use the Tabs.

**Comment by FdezRomero** [comment]
Check the issue #14566, it seems to be linked to an Angular bug.

**Comment by rodrigoreal** [comment]
Same problem here, and the angular bug has being fixed.

**Comment by paulstelzer** [comment]
Think this is fixed. If not, just write here!
