### ISSUE TITLE
[V4] Whitescreen when building to device

### ISSUE THREAD

**Issue by WillPoulson** [ionic-team/ionic#14485]
# Bug Report

**Ionic Info**

```
cli packages: (/usr/local/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.6.1
   @angular-devkit/schematics : 0.6.1
   @angular/cli               : 6.0.1
   @ionic/schematics-angular  : 1.0.0-rc.5
   Cordova Platforms          : android 7.0.0 ios 4.5.4
   Ionic Framework            : @ionic/angular 4.0.0-alpha.3

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.11.1
   npm        : 6.0.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.3.1 Build version 9E501

Environment Variables:

   ANDROID_HOME : not set
```

**Describe the Bug**
When building to an android or ios device you'll be greeted with a white screen and no errors when using the following code on your first page.

**Steps to Reproduce**
1. Generate new project.
2. Put example code in home page html
3. Build to a real ios or android device.

**Related Code**

```
<ion-header>
</ion-header>

<ion-grid slot="fixed" vertical="center" horizontal="center" padding>
  <ion-row>
    <ion-col>
      A
    </ion-col>
  </ion-row>
  <form>
    <ion-row>
      <ion-col>
        <ion-list>
          <ion-item>
            <ion-label>
              B
            </ion-label>
            <ion-input type="text"></ion-input>
          </ion-item>
        </ion-list>
      </ion-col>
      <ion-col>
        C
      </ion-col>
    </ion-row>
  </form>
</ion-grid>

<ion-footer>
</ion-footer>

```

**Comment by WillPoulson** [comment]
Yea exactly the same for me @ASHFAQPATWARI . Tried the usual solutions for that issue such as making the timeout longer and allowing origin and still no luck. Works fine in V3 :(.

**Comment by ASHFAQPATWARI** [comment]
I have also added the timeout preference but no luck. I have tried in ios/android both devices.

**Comment by WillPoulson** [comment]
Could be related to #14489 However only seems to not fire when using the code above.

**Comment by jgw96** [comment]
Hello all! This has been fixed with the latest versions of Ionic and our new beta version of the webview plugin. To get the fix first make sure you have the latest version of ionic 4 (npm install @ionic/angular@4.0.0-alpha.10 --save-exact) and then run these two commands ionic cordova plugin rm cordova-plugin-ionic-webview ionic cordova plugin add cordova-plugin-ionic-webview@2.0.0-beta.1. Thanks!
