### ISSUE TITLE
iframe fixed element not fixed on iOS

### ISSUE THREAD

**Issue by Danitrebu** [ionic-team/ionic#14495]
Hello,

I am working on an application for reading some instructions, and those instructions are external .html that I am linking in an iframe, like this:
manual.html:
`<ion-content>
    <iframe width="100%" height="100%" #iframeManual></iframe>
</ion-content>`
manual.ts:
`ionViewDidLoad() {
    this.iframeManual.nativeElement.src = this.htmlSrc;
  }`
where this.htmlSrc is the url of the manual.

I have a search bar fixed of top of the .html, which is working perfectly on Android, but not on iOS. If you scroll down, the search bar is not fixed and just goes up, as well as the 'increase size' and 'decrease size' buttons on the bottom, which are fixed on Android, but not on iOS. They are located at the end of the whole .html in the bottom.

I also tried adding
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`
but still not working on iOS correctly.

Sorry if you had troubles trying to understand me, english is not my native language.

In case you need it, fixed element at external .html:
`<div class="resize-btns-container">
      <button onclick="resizeText(1)">A+</button>
      <button onclick="resizeText(-1)">A-</button> 
    </div>`
style:
`.resize-btns-container {
	      position: fixed !important;
	      bottom: 0;
	      right: 15px;
      }
      .resize-btns-container button {
	      background: #C3D600;
	      padding: 18px;
	      border-radius: 50%;
	      color: white;
	      font-size: 16px;
	      border: 0;
	      outline: none;
	      box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23);
      }
      .resize-btns-container button:first-child {
	      margin: 10px;
      }`

but I don't think CSS is the problem since it is working perfectly on Android, Explorer and even on iOS explorer

**Comment by guycalledseven** [comment]
I have exact issue using both ionic w/ cordova and ionic w/ capacitor. it is driving me insane.
iframe works flawlessly on android, on IOS it behaves crazy (flashing content, reloading iframe, etc).

**Comment by adrach** [comment]
iframe on iOS completely ignores explicitly set height attribute and produces a lot of bugs. I even tried setting the height explicitly using the following methods
1.height attribute
`
<iframe width="200px" height="100px" #detailsIFrame [src]="url" (load)="initFrame()" scrolling="on"></iframe>
`
2. JS style using setInterval
`
  setInterval(() => {
      const elm1 = this.detailsIFrame.nativeElement;
      elm1.style.minHeight = "100px";
      elm1.style.height = "100px";
      elm1.style.maxHeight = "100px";
      console.log(elm1.offsetHeight);
  }, 100);
`
