### ISSUE TITLE
Testing Ionic 4 - SVG animation stops on android

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic#14494]
# Bug Report

**Ionic Info**
```
C:\ae\adaept.com\aeion4>ionic info
cli packages: (C:\Users\peter\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.6.1
   @angular-devkit/schematics : 0.6.1
   @angular/cli               : 6.0.1
   @ionic/schematics-angular  : 1.0.0-rc.6
   Cordova Platforms          : none
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7

System:

   NodeJS : v8.11.1
   npm    : 6.0.1
   OS     : Windows 10

Environment Variables:

   ANDROID_HOME : not set


C:\ae\adaept.com\aeion4>
```

**Describe the Bug**
The svg animation is auto-run.
Works in IE, Edge, Firefox, Chrome
Works on iPhone
Works with Lab
Stalls on Android phone

**Steps to Reproduce**
Open:
https://aeion4.adaept.com
on android phone (my phone is LG K20 V) and scroll to stars.
The animation stops on scroll, and restarts on touch.

**Related Code**
https://github.com/peterennis/aeion4

**Expected Behavior**
Should not stall.
Not sure where the problem lies, but android is the biggest phone
market and I would expect the same result as other devices
and platforms.

**Additional Context**
![stars](https://user-images.githubusercontent.com/140737/40217346-216cd2bc-5a21-11e8-9e02-d166306af8fd.gif)

**Comment by paulstelzer** [comment]
Is this issue still exist in beta.17?

**Comment by peterennis** [comment]
@paulstelzer - beta.17 update
Here: httsp://aetabs.adaept.com
Repo: https://github.com/peterennis/aetabs/commit/e4ab2f8e92d270f1dcd586396301b19a86893bce
Looks good on my Android phone now.
If it turns up again I will create a new ticket.

![stars2](https://user-images.githubusercontent.com/140737/49398008-f99a7280-f6f1-11e8-964e-2e397d20f38a.gif)
