### ISSUE TITLE
Dedicated Ionic OIDC plugin

### ISSUE THREAD

**Issue by Aeseir** [ionic-team/ionic#14499]
# Feature Request

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
insert the output from ionic info here
```

**Describe the Feature Request**
Ionic needs to have a OIDC connector implementation to take advantage of the new OpenID Connect standards utilised in the industry, and leverage custome OIDC Providers.
As can be seen in various forums (especially stackoverflow.com) it is a problem that is tackled in a hacky manner currently using plugins/packages that just don't fit in with ionic framework effectively or smoothly.
The ability to leverage OIDC standards becomes critical the more security becomes part of mobile apps, especially in business transactions.

**Describe Preferred Solution**
The ideal solution is for Ionic team to develop a authentication component/service for the framework, that meets the OpenID Connect specifications/standards.
This component/service should be easily used, and configured as per other components to enable devs to focus on business/client need rather than hacking away security implementations.

**Describe Alternatives**
Current alternatives explored:

- OIDC-JS
- angular-auth-oidc-client
- OpenID-Client
- Creating restful connections on custom IDP servers (against OpenID standards)

Currently none of these are effective implementations (either don't work due to dependencies or hacky implementations or breach the standards)

**Related Code**
Good example in Angular world is https://github.com/damienbod/angular-auth-oidc-client. Certified and easily implementable. Enables users to go from blank canvas to full security implementation in less than 5 min.

**Additional Context**
Stackoverflow:

- https://stackoverflow.com/search?q=%5Bionic-framework%5D+openid
- https://stackoverflow.com/search?q=%5Bionic-framework%5D+oidc

**Comment by granthoff1107** [comment]
I agree, This would be a very useful feature

**Comment by BadiuAlexandru** [comment]
Does anybody has an alternative for this? working in native device? I am really stuck at this moment and cannot make it work on mobile device.
