### ISSUE TITLE
Update swiper version to latest

### ISSUE THREAD

**Issue by ghaiat** [ionic-team/ionic#14505]
Hello

Currently Ionic 4 is using version 3.4.2 of swiper. Could you update to 4.2.6?
I am trying to use noSwipingSelector which was introduced in 4.1.5 (https://github.com/nolimits4web/swiper/blob/master/CHANGELOG.md#swiper-415---released-on-february-10-2018)

Cheers

**Comment by GuilhermeBCC** [comment]
realIndex of ion-slides is not being updated when I move from slide.

ionic info

```
cli packages: (C:\Users\Guilherme\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.3
   @ionic/schematics-angular  : 1.0.0-rc.6
   Cordova Platforms          : none
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.10.0
   npm               : 6.0.1
   OS                : Windows 10
```

**Comment by mhartington** [comment]
@GuilhermeBCC Please open a new issue. This is to track upgrade the slider internals, not about issues related to the current release.

**Comment by brandyscarney** [comment]
Thank you for the issue! This has been merged in master and should be in the latest alpha release.
