### ISSUE TITLE
ioniv4: mssing 'IonicDevServer' and angulars isDevMode is not enough

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#14518]
# Bug Report & Feature Request

**Describe the Bug or Feature Request**
Some of us need to know if we are running on browser or on cordova in dev or prod mode.

In ionic3 we can check for `((<any>window)['IonicDevServer'] != undefined)` to know if we are in a DEV environment or not. If the property is set we know we have run **ionic serve** or are on **emulator** or using **-lc** on **cordova run**, where we have always the proxy.
This was useful for different behaviors.

Now on **ionic4** we do not have anymore this property, using angulars `isDevMode` is not nough, because this is also true if we run **ionic cordova run android** which naturally is a DEV build but there is no proxy loaded and this is not the classical old ionic DEV environment.

We think it is important to have a tool where we can check if we are on prod/dev build behind or not behind the proxy.

thx

**Comment by paulstelzer** [comment]
For this reason you have the Angular environment variable. More information on https://medium.com/beautiful-angular/angular-2-and-environment-variables-59c57ba643be or https://alligator.io/angular/environment-variables/
