### ISSUE TITLE
Ionic 4: platform.is('electron') failed for electron 2.0.1

### ISSUE THREAD

**Issue by WolfWalter** [ionic-team/ionic#14517]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (/usr/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.3
   @ionic/schematics-angular  : 1.0.0-rc.6
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7

System:

   NodeJS : v8.11.2
   npm    : 5.6.0
   OS     : Linux 4.15
```

**Describe the Bug**
When I tried to use this.platform.is('electron') inside electron with a ionic v4 app the result was negative.

**Expected Behavior**
Result should be true.

**Additional Context**
I checked the platform ionic source. https://github.com/ionic-team/ionic/blob/3bb661fa11e027f4cc55bd920d2353485beecff5/core/src/utils/platform.ts#L57 It is checked if the userAgent includes 'electron' but the electron 2.0.1 userAgent electron starts with a capital 'E':

win.navigator.userAgent:
> "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko).../0.0.1 Chrome/61.0.3163.100 Electron/2.0.1 Safari/537.36"

**Comment by brandyscarney** [comment]
Thank you for the issue! I am going to close this issue and merge it into #15165 to keep all platform issues in one.
