### ISSUE TITLE
Ionic V4 Wrong Statusbar Padding on Cordova Android

### ISSUE THREAD

**Issue by orlyapps** [ionic-team/ionic#14513]
# Bug Report

**Ionic Info**

```
cli packages: (/usr/local/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.1
   @ionic/schematics-angular  : 1.0.0-rc.6
   Cordova Platforms          : android 7.0.0
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   NodeJS            : v8.11.2
   npm               : 6.0.1
   OS                : macOS High Sierra
   Xcode             : Xcode 9.3.1 Build version 9E501

Environment Variables:

   ANDROID_HOME : /Users/hackfrag/Library/Android/sdk
```

**Describe the Bug**
Statusbar Padding Top is wrong

**Steps to Reproduce**
ionic start MyTest
cd ./MyTest
ionic cordova run android

**Related Code**
<img width="576" alt="bildschirmfoto 2018-05-22 um 13 41 32" src="https://user-images.githubusercontent.com/5220826/40360346-2f708126-5dc6-11e8-8964-944fbfa42201.png">

**Expected Behavior**
![bildschirmfoto 2018-05-22 um 13 43 48](https://user-images.githubusercontent.com/5220826/40360353-356b4b6a-5dc6-11e8-8743-52ff65ad7afb.png)

**Comment by jgw96** [comment]
Hello! This has been fixed in the latest releases. To update you can run `npm install @ionic/angular@4.0.0-alpha.10 --save-exact`. Thanks!
