### ISSUE TITLE
iPhone X UI mode for Ionic v4?

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic#14529]
Hello guys,

As we aware, iPhone X comes with different screen dimensions. It has rounded corners and it's much bigger. 
I tried Ionic's material design UI on iPhone X and it really didn't work well. Navigation button will not be in correct place and UI generally doesn't look balanced. Ionic material UI works well on iPhone SE, 5s, 6, 7. 

Will we see UI improvements on models like LG Q6, iPhone X in Ionic v4?  
Rounded corner large screen is becoming more popular so I hope Ionic will cope with this trend. 

Thanks,

**Comment by jgw96** [comment]
Hello! We have added notch support to Ionic since this issue was opened. Because of this I will be closing this issue for now. Thanks!
