### ISSUE TITLE
ActionSheet - Add ability to return data

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/ionic#14531]
# Feature Request

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

System:

    Node : v8.9.1
    npm  : 5.7.1
    OS   : macOS High Sierra

Misc:

    backend : pro
```

**Describe the Feature Request**
When using an `ion-action-sheet` it is not possible to dismiss with a resulting data.

Other overlay components (`ion-alert`, `ion-modal`, `ion-popover`) specify data for the dismiss event.

There are times where it is useful to use an action sheet that returns a value rather than building all the handling logic into the buttons.
```tsx
colorPickerSheet.onDidDismiss(detail => this.color = detail.data);
```

To implement this, the `ActionSheetButton` interface could include an optional data value that would be passed to `dismiss`.

**Comment by manucorporat** [comment]
@cjorasch this is a great idea!
going to add this feature to Alert and action-sheet so button handlers can return an object.

**Comment by paulstelzer** [comment]
This is integrated now :)
