### ISSUE TITLE
iOS package build fails

### ISSUE THREAD

**Issue by ALander26** [ionic-team/ionic#14535]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (/Users/perfectedtech/.nvm/versions/node/v8.11.1/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.11.1
    npm        : 5.8.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Describe the Bug**
When trying to build iOS package, an error occurs in the build process. The issue just started happening -- the library stated hasn't changed in previous successful builds.

**Steps to Reproduce**
Steps to reproduce the behaviour:

Push new git version to Ionic.
Wait for build to finish.
Start package build for iOS
Build fails with:

npm WARN deprecated cordova-plugin-contacts@3.0.1: This plugin has been deprecated
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ionic/.npm/_logs/2018-05-28T05_40_48_744Z-debug.log

**Comment by mhartington** [comment]
Hi there! This was an issue with package yesterday. 

https://status.ionicframework.com/incidents/f5jtjr6dqv6v

This issue should be resolved already. Thanks!
