### ISSUE TITLE
Google maps api

### ISSUE THREAD

**Issue by 3jFernando** [ionic-team/ionic#14543]
Hola, tengo la siguiente duda; lo que pasa es que estoy trabajando con un proyecto con Google Maps Api y necesito ubicar markers con determinadas posiciones en el mapa, el problema es que no estoy trabajando con Latitudes y Longitudes, si no por el contrario con Coordenadas de Norte Sur Oriente y Occidente ademas de una altura sobre el nivel del mar, como podria realizar eso ??

Ayuda por favor!

**Comment by kensodemann** [comment]
Your question is more of a Google Maps API question than an Ionic question. The Ionic Issue Bot's response is going to direct you to our forums, but a better choice for this question may be StackOverflow or the Google Maps API docs.
