### ISSUE TITLE
'Ionic serve' periodically serves old code and requires restart

### ISSUE THREAD

**Issue by swvcc** [ionic-team/ionic#14557]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Ionic serve reverts to a previous version of my app randomly, causing me to have to restart it.

**Expected behavior:**
Ionic serve should provide the latest version of my app for viewing in the browser.

**Steps to reproduce:**
Run ionic serve, update app a few times, observe behavior.  Try it for an hour or so at most.  Should manifest soon.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v8.9.4
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/swarren/sdk/android-sdks

Misc:

    backend : pro

**Comment by mhartington** [comment]
Hi there! This appears to be an issue with ionic-app-scripts, not the framework. Please open your issue there.
http://github.com/ionic-team/ionic-app-scripts/

Thanks!
