### ISSUE TITLE
ionic v4 Datetime cannot have first value

### ISSUE THREAD

**Issue by dmastag** [ionic-team/ionic#14563]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (C:\Users\julian\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.1
   @ionic/schematics-angular  : 1.0.0-rc.6
   Cordova Platforms          : none
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7

System:

   NodeJS : v10.3.0
   npm    : 6.1.0
   OS     : Windows 10

Environment Variables:

   ANDROID_HOME : not set
```

**Describe the Bug**
When using ion-datetime, for each column if I choose the first value then it does not show anything.

**Steps to Reproduce**
1. Use ion-datetime
2. Fill in 01 Jan 2018 (first option for every column)
3. Result empty (the value is from placeholder)
4. Fill in 02 Jan 2018
4. Only the Date is there, Month and Year are still empty

**Related Code**
html
```
<ion-datetime class="text-border" displayFormat="DD/MM/YYYY" pickerFormat="DD/MMM/YYYY" min="2000" max=2019 placeholder="dd/mm/yyyy"></ion-datetime>
```

**Expected Behavior**
That we can choose the first value for each column

**Comment by FdezRomero** [comment]
I can also reproduce this issue with `@ionic/angular@4.0.0-alpha.7` and the new docs (locally).

Thanks,
Rodrigo

**Comment by pwespi** [comment]
For a possible solution, see https://github.com/ionic-team/ionic/pull/14479 and https://github.com/ionic-team/ionic/pull/14480.

**Comment by brandyscarney** [comment]
Thank you for the issue! This will be fixed in the `beta.3` release.
