### ISSUE TITLE
Unable to modify variables for the Responsive Grid

### ISSUE THREAD

**Issue by benjcallaghan** [ionic-team/ionic#14562]
# Bug Report

**Ionic Info**

```
cli packages: (/Users/benj/.nvm/versions/node/v8.11.2/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.1
   @ionic/schematics-angular  : 1.0.0-rc.6
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7

System:

   NodeJS : v8.11.2
   npm    : 5.6.0
   OS     : macOS High Sierra
```

**Describe the Bug**
Within my `theme/variables.scss` file, I attempted to change the breakpoints for the responsive grid layout. I tried using the CSS4 variable syntax from the [alpha docs](http://ionic-docs.herokuapp.com/docs/layout/grid#customizing-the-grid) as well as the SASS variable syntax from the [Ionic 3 docs](https://ionicframework.com/docs/theming/responsive-grid/#customizing-the-grid). Neither method showed any visible results. I then tried other grid-related variables with the same non-result.

**Steps to Reproduce**
1. Generate a new project with `ionic start`.
2. Add a grid to the main page with four columns.
3. Give each column the following attributes: `col-6` and `col-sm-3`.
4. In `theme/variables/scss`, add the following to the `:root` element: `--grid-breakpoint-sm: 400px`.
5. Run the app and set the browser size between 400px and 576px (default for sm).
6. The grid is only displaying 2 columns per row instead of the expected 4.
7. Increase the browser size to 576px.
8. The grid is now displaying 4 columns per row.

**Expected Behavior**
Because the `sm` breakpoint had been changed to 400px, the app should respect the `col-sm-3` attribute over the `col-6` attribute. Browsers whose width is greater than or equal to 400px should be displaying 4 columns per row.

**Additional Context**
I tried both of the following methods while trying to modify the breakpoints. Both snippets are from my `theme/variables.scss` file. The default values held through all attempts. I was able to change the variables for the primary color using CSS4 variables, so it appears this issue is confined to the responsive grid. 

```
:root {
    --grid-breakpoint-xs: 0;
    --grid-breakpoint-sm: 400px;
    --grid-breakpoint-md: 768px;
    --grid-breakpoint-lg: 992px;
    --grid-breakpoint-xl: 1200px;
}
```

```
$grid-breakpoints: (
  xs: 0,
  sm: 400px,
  md: 768px,
  lg: 992px,
  xl: 1200px
);
```

**Comment by hal1984** [comment]
I think it could be related with this, cause in iOS/Safari i have the same problem:

https://github.com/ionic-team/ionic/blob/08c6c974d5dbc11c6500ffc1a53e630920e0f157/core/src/components/col/col.tsx#L5

In latest Chrome versions that way of checking for CSS Custom Variables support works at expected

<img width="560" alt="image" src="https://user-images.githubusercontent.com/6789405/44301557-4a3fb880-a319-11e8-9c8b-43ca4576d24a.png">

but not in Safari and need to use a alternative expression syntax:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/6789405/44301506-727ae780-a318-11e8-97c9-6b660012a3e9.png">

This is a open bug in Webkit:

https://bugs.webkit.org/show_bug.cgi?id=154669
