### ISSUE TITLE
how can I use `.pug` with templateUrl?

### ISSUE THREAD

**Issue by yozman** [ionic-team/ionic#14561]
# Support Question

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Comment by mhartington** [comment]
Hi there! It appears this isn't really an issue, and more of a question, so Im going to close this. Please check out the [forum](https://forum.ionicframework.com) as this is a better place for questions. Thanks!
