### ISSUE TITLE
NavBar back button not working on android

### ISSUE THREAD

**Issue by ramkrishna70** [ionic-team/ionic#14569]
Hi, 
In my ionic project, navbar back button is not working. 
Hardware back button works fine. Here I have attached code snippet.
```
<ion-header>
    <ion-navbar color="primary">
        <ion-buttons left>
            <button ion-button icon-only (click)="view.dismiss()">
            </button>
        </ion-buttons>
    </ion-navbar>
</ion-header>
``` 
I am pushing a page from root page and the pushed page has above ion-header.

Please help me to find the issue.
Thanks

**Comment by mhartington** [comment]
Hi there! This appears to be an issue, but there's no information on how to recreate or how to debug this. Could you please provide some more information or a demo in the form of a github repo? Thanks!

**Comment by ramkrishna70** [comment]
Hi Mike,
Here's my ionic environment:
```
   @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    Node       : v9.2.1
    npm        : 3.10.10 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3.1 Build version 9E501 

```
Actually I am pushing a page from root page, the new pushed page shows the back button and title as 
```
<ion-header>
       <ion-navbar color="primary">
        <ion-buttons left>
            <button ion-button icon-only (click)="view.dismiss()">
            </button>
        </ion-buttons>
       <ion-title text-center>
            <span ion-text class="fw700"> My Profile </span>
        </ion-title>
       <ion-icon name="qr-scanner" class="qr-scanner" (tap)="scan_qr_code()"
    </ion-navbar> 
</ion-header>
```
The hardware button works fine, but navBar back button takes 5-10 taps(clicks) to pop out the current page.

If more info needed please let me know.
Thanks :)

**Comment by ramkrishna70** [comment]
I resolved this issue, it was related to "margin-left", taken time to find it.
