### ISSUE TITLE
Virtual Scroll + Infinite Scrolling not work in iOS UIWebkit

### ISSUE THREAD

**Issue by fwchen** [ionic-team/ionic#14568]
# Support Question
#### ionic3.9.2

Hello, my project app use iOS UIWebkit, and I found "virtual scroll" + "infinite scrolling" not work in my app. 

and i found `virtual-scroll.ts`  \\\ ionic3.9.2

```
private _listeners() {
    assert(!this._scrollSub, '_listeners was already called');
    if (!this._scrollSub) {
      if (this._config.getBoolean('virtualScrollEventAssist')) {
        // use JS scrolling for iOS UIWebView
        // goal is to completely remove this when iOS
        // fully supports scroll events
        // listen to JS scroll events
        this._content.enableJsScroll();
      }

      this._resizeSub = this._plt.resize.subscribe(this.resize.bind(this));
      this._scrollSub = this._content.ionScroll.subscribe(this.scrollUpdate.bind(this));
      this._scrollEndSub = this._content.ionScrollEnd.subscribe(this.scrollEnd.bind(this));
    }
  }
```
virtualScrollEventAssist is false in UIWebkit, 
and that code make scrollTop always zero in Infinite component, so infinite scroll not work.

How make Virtual Scroll + Infinite Scrolling work in iOS UIWebkit, thanks very much.

**Comment by mhartington** [comment]
We strongly suggest upgrading to using WKWebview for this. UIWebview does not offer the APIs needed in order to correctly report scroll events. Please upgrade to use the https://github.com/ionic-team/cordova-plugin-ionic-webview/
