### ISSUE TITLE
ng-if doesn't work with ion-content

### ISSUE THREAD

**Issue by MrSparklle** [ionic-team/ionic#14575]
# Bug Report

```
cli packages: (/Users/joeldaros/.nvm/versions/node/v8.11.2/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.11.2
    npm        : 5.10.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4 Build version 9F1027a 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Describe the Bug**
Ng-if doesn't work with ion-content. 

**Steps to Reproduce**

**Related Code**
```
<ion-header>
  <ion-navbar color="primary" no-padding>
    <img src="assets/imgs/pic.png">
  </ion-navbar>
</ion-header>

<ion-content *ngIf="userProfile$ | async as profile">

  <ion-fab top right edge>
    <button ion-fab mini color="primary-dark" border (click)="navigateToEditProfile(profile)">
      <ion-icon name="create"></ion-icon>
    </button>
  </ion-fab>

  <ion-list-header color="secondary" no-margin>
    <h1 text-uppercase>PERFIL</h1>
  </ion-list-header>

    ....

</ion-content>
```
Note that the  `<ion-list-header ...>` is not show and the fab button is displayed incorrectly.

![image](https://user-images.githubusercontent.com/992049/40939488-2c2ec1a8-681b-11e8-9938-1f076225c026.png)

If I put the `*ngIf="userProfile$ | async as profile"` inside a `<div>` the `<ion-list-header ...>` is displayed but the fab button is displayed under the navbar.

``` 
<ion-content>
<div *ngIf="userProfile$ | async as profile">
...
</div>
</ion-content>
```

![image](https://user-images.githubusercontent.com/992049/40939731-ef5bfc5e-681b-11e8-8aa3-7a41c9796ca2.png)

**Comment by mhartington** [comment]
This is a known thing. Anytime content changes on a page (ion-content/toolbars/footers are added or removed), you need to call `ionContent.resize`

https://ionicframework.com/docs/api/components/content/Content/#resizing-the-content

Using the *ngIf on the div is how you should handle things.
