### ISSUE TITLE
Looking for a way to import rest member like OverlayInterface in utils to extend components based on ionic & stencil

### ISSUE THREAD

**Issue by malaohus93** [ionic-team/ionic#14587]
# Feature Request

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (C:\Users\39463\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

System:

   NodeJS : v8.9.3
   npm    : 5.5.1
   OS     : Windows 10
```

**Describe the Feature Request**
hello guys! I got this error as below when I was building a stencil component and import OverlayInterface from @ionic/core@4.0.0-alpha.7

```
[ WARN  ]  '@ionic/core/dist/types/utils/overlays' is imported by
           __tmp__in__memory__\components\image-viewer\image-viewer.js, but could not be resolved – treating it as an
           external dependency
```

then I noticed that index.d.ts, the entry types file, did not import some members of utils directory.Is there any way to using overlay or solve this problem in a future edition?

**Comment by mhartington** [comment]
Hi there! The correct way would be to import the types from `@ionic/core` vs trying to do deep imports. 


You can just do 

```
import @ionic/core

```

And the types should be available.
