### ISSUE TITLE
Text-only tabs are misaligned

### ISSUE THREAD

**Issue by lowe0292** [ionic-team/ionic#14585]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (/usr/local/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.1
   @ionic/schematics-angular  : 1.0.0-rc.6
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7
System:

   NodeJS : v8.11.2
   npm    : 5.6.0
   OS     : macOS High Sierra
```

**Describe the Bug**
When setting the `tabbarLayout` property of the `ion-tabs` component to `"icon-hide"`, the text on the tab is still aligned as though the icon were displayed:
<img width="349" alt="screen shot 2018-06-06 at 3 32 51 pm" src="https://user-images.githubusercontent.com/3045356/41068561-e7c860e8-699e-11e8-8fe8-41321ef28e01.png">

**Steps to Reproduce**
1. Generate a new starter app with the CLI rc
2. Adding the below html to any page
3. Open the app with `ionic serve`, then navigate to said page

**Related Code**
```
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button></ion-back-button>
    </ion-buttons>
    <ion-title>Property</ion-title>
  </ion-toolbar>
</ion-header>



<ion-content padding>
  <ion-tabs tabbarPlacement="top" tabbarHighlight="true" tabbarLayout="icon-hide">
    <ion-tab label="Details"></ion-tab>
    <ion-tab label="Units"></ion-tab>
  </ion-tabs>
</ion-content>
```

**Expected Behavior**
I expect properly aligned text-only tabs, as seen on the [v3 docs](https://ionicframework.com/docs/api/components/tabs/Tabs/).

**Comment by brandyscarney** [comment]
I'm not able to reproduce this in latest (master which will become `4.0.0-beta.13`) using the following markup:

```
<!-- No icons -->
<ion-tab-bar color="primary" selected-tab="1">
  <ion-tab-button tab='1' layout="icon-hide">
    <ion-label>Recents</ion-label>
    <ion-icon name="call"></ion-icon>
  </ion-tab-button>

  <ion-tab-button tab='2' layout="icon-hide">
    <ion-label>Favorites</ion-label>
    <ion-icon name="heart"></ion-icon>
    <ion-badge color="danger">6</ion-badge>
  </ion-tab-button>

  <ion-tab-button tab='3' layout="icon-hide">
    <ion-label>Settings</ion-label>
    <ion-icon name="settings"></ion-icon>
  </ion-tab-button>
</ion-tab-bar>
```

If you are still seeing this issue please create a new issue with ways to reproduce, thanks!

<img width="372" alt="screen shot 2018-10-26 at 5 02 06 pm" src="https://user-images.githubusercontent.com/6577830/47592366-07194b80-d941-11e8-8127-5c9e29722817.png">
