### ISSUE TITLE
Ionic v4: IonToolbar creates extra margin at the top in Android

### ISSUE THREAD

**Issue by dotnetdreamer** [ionic-team/ionic#14584]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (C:\Users\pak43\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:

    Node : v8.11.2
    npm  : 5.3.0
    OS   : Windows 10

Misc:

    backend : legacy
```

**Describe the Bug**
I just created a new app with sidemenu template and run it with capacitor in android. There is too extra margin at the top.

**Steps to Reproduce**
1. Create new sidemenu template with --type angular
2. add capacitor to the project
3. run it in adroid in android studio in **Samsung Galaxy S9+**
![image](https://user-images.githubusercontent.com/10280821/41056828-6eb584be-69d6-11e8-84c0-c670fcadb4b8.png)

**Expected Behavior**
There shouldn't be extra margin at the top

**Comment by paulstelzer** [comment]
Think this is fixed in beta.17. If not, just write here!
