### ISSUE TITLE
Ionic-Angular V4.RC.7 - Impossible to run : 'npm run build.dev'

### ISSUE THREAD

**Issue by izio38** [ionic-team/ionic#14589]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:

    Node : v8.11.2
    npm  : 5.6.0
    OS   : Linux 4.4

```

**Describe the Bug**
I just follow the steps in the angular project subfolder. so I fork the repo, i placed myself in angular, ran `npm i`. A few moment later, the operation was finished, so I ran : `npm run build.dev`.
Output : 
```
> node scripts/build-core.js --dev

stencil build --config /mnt/d/workspace/ionic/New folder/core/stencil.config.js --dev
stencil build --config /mnt/d/workspace/ionic/New folder/angular/stencil.config.js --dev
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./stencil ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Steps to Reproduce**
1. Fork the repo
2. Place yourself into angular
3. Execute : npm i
4. Execute : npm run build.dev. see the error.

**Expected Behavior**
I expected Ionic working on WLS with angular 6.0.

**SOLUTION**
The documentation didn't mention we need to install the core directory too with `npm i`.
Also, the child_process.spawn() should have an listener on the error event.

**Comment by GordoRank** [comment]
I still have precisely this issue.
