### ISSUE TITLE
ionic 4 serve works but not build.

### ISSUE THREAD

**Issue by RZR666** [ionic-team/ionic#14599]
ionic serve --prod works fine.

ionic build --prod doesn't.

I end up with a lot of .js and .js.map files.  There's an index.html in there but when I load it, it logs the below errors...

Failed to load resource: net::ERR_FILE_NOT_FOUND
runtime.708139da31090c0aa69c.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
polyfills.b5a4875d27f6761196b9.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
scripts.a8d156b92ea2ded28ebf.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
main.e2ee0d3a624f4c0e52ad.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/assets/icon/favicon.png:1 Failed to load resource: net::ERR_FILE_NOT_FOUND

**Ionic Info**
   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.8
   @ionic/schematics-angular  : 1.0.0-rc.6
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7

System:

   NodeJS : v10.4.0
   npm    : 6.1.0
   OS     : macOS High Sierra

**Comment by RZR666** [comment]
Incase anyone else has the same issue it works on server root.

**Comment by laker007** [comment]
I have the same problem.How do you fix it?

**Comment by matheusdavidson** [comment]
@RZR666, can you please explain what you did?
