### ISSUE TITLE
VirtualScroll and InfiniteScroll 

### ISSUE THREAD

**Issue by andreandev** [ionic-team/ionic#14597]
Hello guys!
I have to display a large list of data ( ionic v3 ) and i have read many posts regarding issues with the Virtual Scroll.

I did not find anything about a combination with InfiniteScroll.
Has anyone ever had any experience?

I'm trying without success.

**Comment by kael** [comment]
There are lots of examples like https://github.com/ionic-team/ionic/tree/v3/src/components/virtual-scroll/test/infinite-scroll. Not sure it's the right place to ask.
