### ISSUE TITLE
ion-input autofocus

### ISSUE THREAD

**Issue by followfire** [ionic-team/ionic#14605]
I want to set an ion-input component to be focused when the page was loaded, so I use 'this.text.nativeElement.focus()' to do this work. But when I enter the page, the ion-input only get focus for a second, then the focus disapeared immediately. So,can anyone tell me what happend, and how can I fixed the Issue?My English is poor,hope u can understand what I said, thx.

**Comment by izio38** [comment]
This is not an Ionic issue you're exeprienced.
This is not an issue at all to be honnest.
First, please google your problem, then read the first result which say to create an attribute directive:
```
import { Directive, AfterViewInit, ElementRef } from '@angular/core';
 
@Directive({
  selector: '[autoFocus]'
})
export class AutofocusDirective implements AfterViewInit {
 
  constructor(private el: ElementRef) {
  }
 
  ngAfterViewInit() {
    this.el.nativeElement.focus();
  }
 
}
```
then use it like this:
```
<ion-input autoFocus> </ion-input>
```

**Comment by followfire** [comment]
@izio38 thx a lot for your answer. I'd try it right now.
