### ISSUE TITLE
[sovled]Ionic  showing old content  

### ISSUE THREAD

**Issue by walid-deutscher** [ionic-team/ionic#14603]
hi ;
i have a big problem

the ionic show old value in variable

for show new conent  i need to clear cache in divice but this annoying  for users

**Comment by walid-deutscher** [comment]
the probleme ist 100% solved by me
when i use http  Plugin  seem this problem


i see old  data http  not updated  
............................
first step yu need to  host  json.php  in domain free or paid like do yu want
www.yourdomain.com/json.php
 your code
<?php
header("Access-Control-Allow-Origin: *");
?>
<meta http-equiv="refresh" content="4" />
<?php

	
	$url = ' your json lik  the sourcee'; 
$data = file_get_contents($url);  
$characters = json_decode($data); 

$myJSON = json_encode($characters);

echo $myJSON;

?>

 in ionic in http plugin you need to use this


dz=new Date();  // very importante

	  this.http.get('www.yourdomain.com/json.php.php?dz='+dz).map(res => res.json()).subscribe(data => {

consol.log(data); 
	 );

**Comment by mhartington** [comment]
Closing then!
