### ISSUE TITLE
ion-tab titles not well aligned on iPhone X

### ISSUE THREAD

**Issue by adrm** [ionic-team/ionic#14606]
# Bug Report

**Ionic Info**
```
cli packages: (/usr/local/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

global packages:

   cordova (Cordova CLI) : 7.0.1

local packages:

   @angular-devkit/core       : 0.6.7
   @angular-devkit/schematics : 0.6.7
   @angular/cli               : 6.0.7
   @ionic/schematics-angular  : 1.0.0-rc.6
   Cordova Platforms          : ios 4.5.4
   Ionic Framework            : @ionic/angular 4.0.0-alpha.6

System:

   NodeJS : v8.11.2
   npm    : 6.1.0
   OS     : macOS Sierra
   Xcode  : Xcode 9.0 Build version 9A235

Environment Variables:

   ANDROID_HOME : not set
```

**Describe the Bug**
Please see attached screenshot. Tab titles are not well aligned on iPhone X.

![photo_2018-06-11_15-58-38](https://user-images.githubusercontent.com/307945/41236190-c5da435c-6d90-11e8-96bc-3bd6ab688423.jpg)

**Steps to Reproduce**
Steps to reproduce the behavior: Create an ionic app with bottom tabs. Run it on an iPhone X simulator.

**Expected Behavior**
Tab titles should not overlap iPhone X controls.

May be related to this Ionic v3 issue: https://github.com/ionic-team/ionic/issues/14421

**Comment by mhartington** [comment]
Can confirm this. Will look into what happened!

**Comment by jamesharvey2** [comment]
@mhartington 
Also, please try md mode navigation on iPhone X.
Navigation title will not align with navigation button icon.  and I think md mode navigation takes too much space on iPhone X. I tried to fix this using media queries but it didn't work.

**Comment by mhartington** [comment]
@adrm should be fixed, thanks!  Will be part of the next release
