### ISSUE TITLE
Evaluate the possible use of Github Community forum for help requests

### ISSUE THREAD

**Issue by kael** [ionic-team/ionic#14601]
### Feature Request

People are submitting help requests on Github tickets and not following the recommended way. In the meantime, there exists [Github Community](https://github.community/t5/Project-Development-Help-and/bd-p/Project-development-help-and-advice). Perhaps it could be an occasion to bind both with a redirection to Github Community forums. (I for one rarely hang on Ionic forums).

There already exists the Ionic forums and StackOverflow, so this might add some fragmentation. But perhaps something could be considered otherwise, like using exclusively Github Community pages (which not sure I'd do, though), or perhaps as a third place to ask.

**Comment by mhartington** [comment]
Hi there! Thanks for the suggestion. I don't think we're going to go down that road for feature request. In the future, I think a better option would be to adopt a RFC process, where all feature requests can go through a detailed process of getting verified and all potential issues could be discussed before any code is written. 

This will not only give the ionic team a clear idea of what a feature should do and the consequences of adding such a feature, but also act as a "design  doc" for community member who would like to submit a PR.

I think this in the long run would be the better/more maintainable way to discuss new features. 

Thanks!

**Comment by kael** [comment]
Alright then. The idea was more of having a place on Github to help people, not specially for feature requests, though.

Anyway, thanks for your attention.

Cheers.
