### ISSUE TITLE
Possible memory leak when using IntersectionObserver polyfill

### ISSUE THREAD

**Issue by sbannigan** [ionic-team/ionic#14600]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (/usr/local/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

local packages:

   @angular-devkit/core       : 0.0.28
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.1
   @ionic/schematics-angular  : 1.0.0-rc.6
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7

System:

   NodeJS : v8.11.2
   npm    : 6.0.1
   OS     : macOS High Sierra
```

**Describe the Bug**
See [this issue on the ionicons repo](https://github.com/ionic-team/ionicons/issues/563).
**TL;DR:** IntersectionObserver polyfill does not properly disconnect sometimes when an item is destroyed in a virtual scroll. This would in theory also cause a memory leak for the `ion-img` component as well.

**Steps to Reproduce**
1. Put an `ion-icon` or `ion-img` component inside a virtual scroll
2. Test on mobile safari for most noticeable memory leak
3. Add [IntersectionObserver polyfill](https://github.com/w3c/IntersectionObserver/tree/master/polyfill) to the project 
4. Scroll up and down in the virtual scroll area very fast, the app will slowly become more and more unresponsive and laggy.

**Expected Behavior**
The components that use the IntersectionObserver should either support the polyfills quirks, or warn against using the polyfill in the documentation.

**Additional Context**
Using these components without the polyfill works completely fine. I also modified the `ion-icon` component to disconnect from the IntersectionObserver on componentDidUnload and that also fixed the issue while still using the polyfill.

**Comment by kael** [comment]
With Stencil/Ionic4, I've aslo noticed something that looks like a leak when using virtual scroll that includes elements with `ion-icon`:
- when scrolling, the __number of DOM nodes never stops increasing__ despite that no data are explicitly added - apart from the `renderNode` function call (create the element, or use an existing one and update its content) ;
- the JS __heap size never decrease when refreshing the page__, like if there were some orphan DOM nodes kept somewhere (which can easily lead Chrome and then my laptop to freeze, and to make Chrome crash on Android). Although not sure that _"increasing memory"_ is related to virtual scroll.

I tried to investigate following that [HowTo](https://developers.google.com/web/tools/chrome-devtools/memory-problems/heap-snapshots) but didn't find much. Gotta give another try.

**Comment by mhartington** [comment]
Thanks for the issue! I'll have @manucorporat take a look as he did the work for ion-icon and virtual scroll.

Are you seeing any memory leaks without the polyfil? If so, this could an issue in the polyfil itself.

**Comment by sbannigan** [comment]
@mhartington I'm not seeing any memory leaks on iOS without the polyfill, so that makes me think that it is a polyfill issue, however I have not yet tested on an Android device that supports IntersectionObserver to determine if there are leaks there as well.

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you take a look if this is fixed in `@ionic/angular@beta.17`?

**Comment by manucorporat** [comment]
Pretty sure this is not longer an issue in latest beta!
