### ISSUE TITLE
Keyboard events are cancelled when app loads until the user's first click event

### ISSUE THREAD

**Issue by vali-de-man** [ionic-team/ionic#14604]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

In an Ionic app (e.g. a tabs starter) hitting the enter key doesn't activate tabs or buttons until the user has clicked at least once anywhere in the window. The keyboard interface doesn't work until at least one click has been registered.

**Expected behavior:**

The Ionic tabs (and other UI elements as well) should be responsive to the key strokes that should activate them (enter, spacebar) from the beginning, from the moment the page loads. No click should be required as the app needs to be accessible for users who use no mouse.

**Steps to reproduce:**

1. Generate a tabs starter and launch it
2. Move focus to one of the non-activated tabs by using the Tab key only, and hit Enter. Nothing happens. The tab is not activated.
3. Now left mouseclick anywhere in the window. 
4. Move focus again to one of the non-activated tabs by means of the keyboard and hit Enter. This now does activate the tab.

**Related code:**
node-modules > ionic-angular > tap-click > tapclick.js

```
insert short code snippets here
The events fired by hitting Enter or Spacebar on the keyboard are cancelled in the if(!this.dispatchClick) statement until the dispatchClick variable is given a value upon the user's first mouseclick. 

    TapClick.prototype.shouldCancelClick = function (ev) {
        if (this.usePolyfill) {
            if (!ev.isIonicTap && this.isDisabledNativeClick()) {
                (void 0) /* console.debug */;
                return true;
            }
        }
        else if (!this.dispatchClick) {
            (void 0) /* console.debug */;
            return true;
        }
        if (!this.app.isEnabled()) {
            (void 0) /* console.debug */;
            return true;
        }
        if (this.gestureCtrl.isCaptured()) {
            (void 0) /* console.debug */;
            return true;
        }
        return false;
    };
```

**Other information:**

I posted this on the forum but had no luck yet: https://forum.ionicframework.com/t/bug-in-keyboard-navigation-tabs-starter/131800/2
I found that the keyboard events that should activate elements are cancelled in the function shouldCancelClick() in tapclick.js until the private variable this.dispatchClick is set to true. This happens in the function pointerStart(), which the keyboard events do not seem to call. The first mouseclick does call the function pointerStart(). This seems to explain the bug but I want to make no changes in the node-modules!

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
$ ionic info

Ionic:

   ionic (Ionic CLI)  : 4.1.0 (C:\Users\Gebruiker\AppData\Roaming\npm\node_modules\ionic
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

System:

   NodeJS : v8.11.1 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10

**Comment by paulstelzer** [comment]
For me it sounds like a feature request

**Comment by vali-de-man** [comment]
Maybe it is indeed better categorised as a feature request. In any case, for our product owner it is important that users can access the full functionality of the app in a desktop browser by keyboard, without using a mouse at all. 

The issue no longer arises with the tabs starter based on Ionic/Angular v 4.0.0-rc.0 so I'll close this issue now. Thanks for having a look at it.
