### ISSUE TITLE
this.nav.getActive().component.name returns letter

### ISSUE THREAD

**Issue by ronaiza-cardoso** [ionic-team/ionic#14616]
# Bug Report

**Ionic Info**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-plugin-proxy : 1.5.5
    @ionic/cli-utils        : 1.19.1
    ionic (Ionic CLI)       : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v6.11.2
    npm               : 4.6.1 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4 Build version 9F1027a 

Environment Variables:

    ANDROID_HOME     : /Users/ronaiza.cardoso/Library/Android/sdk
    HTTP_PROXY       : not set
    http_proxy       : not set
    HTTPS_PROXY      : not set
    https_proxy      : not set
    IONIC_HTTP_PROXY : not set
    PROXY            : not set
    proxy            : not set

Misc:

    backend : pro


```

**Describe the Bug**
When I build the project with `--prod` the method `this.nav.getActive().component.name` returns letter instead component name. 

**Steps to Reproduce**
build project with `--prod` 

**Expected Behavior**
return compoment name

**Comment by izio38** [comment]
https://github.com/ionic-team/ionic/blob/v3/src/navigation/view-controller.ts#L243
`this.nav.getActive()` should return a ViewController.
So.. `this.nav.getActive().name` should return the name.

**Comment by maxtacco** [comment]
I wonder if it has to do with minification and obfuscation during prod build. The class names are probably different in this case.

**Comment by mhartington** [comment]
As @maxtacco said, this is due to minification in the build process. I will note, that you should not rely on ViewCtrl.name, as there is no way to protect it from being minified
