### ISSUE TITLE
Ionic 1 - swiping up and down cause page to move on IOS

### ISSUE THREAD

**Issue by tamarcarmon** [ionic-team/ionic#14618]
When swiping up and down with the finger cause page to move, showing white background..only on IOS

**Comment by mhartington** [comment]
Hi there! This repo is not the place for Ionic 1 related issue.

https://github.com/ionic-team/ionic-v1

I will add, that Ionic 1 is no longer receiving any bug fixes or updates.
I would post on the forum to see if anyone seen anything similar 

http://forum.ionicframework.com
