### ISSUE TITLE
Virtual Scroll Check Box Issue

### ISSUE THREAD

**Issue by vivekk24** [ionic-team/ionic#14628]
# Bug Report

**Ionic Info**
```
cli packages: (/Users/sysquare/Desktop/IonicHome/frontend/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.0.0 ios 4.3.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v9.3.0
    npm               : 6.1.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.3 Build version 9E145 

Environment Variables:

    ANDROID_HOME : /Users/sysquare/Library/Android/sdk

Misc:

    backend : pro
```

**Describe the Bug**

 <ion-list [virtualScroll]="testList" approxItemHeight="50px">
    <ion-item *virtualItem="let member">
      <ion-label>{{member?.testName || 'N/A'}}</ion-label>
      <ion-checkbox color="btn-purple" (click)="selectMember(member)" [(ngModel)]="member.checked"></ion-checkbox>
    </ion-item>
  </ion-list>

**Steps to Reproduce**
1. Have to show list of 2000 records.
2. Click on any checkbox
3. Scroll down to list but selected checkbox index showing selected when reload new data this is not happening with *ngfor.

**Expected Behavior**
If i select any records and scroll the list than another data should not show selected till i did not click on checkbox.

**Comment by Arieru** [comment]
+ 1 I have the same issue. Did you figure out any solution for this?
