### ISSUE TITLE
v4 What version of typescript is supported?

### ISSUE THREAD

**Issue by granthoff1107** [ionic-team/ionic#14627]
I'm trying to integrate the latest version of Singlar into my Ionic App.   My resolution requires "typescript": "^2.7.1".  What version of Typescript Ionic 4 support?

**Comment by kael** [comment]
[Ionic v4.0.0-alpha.7](https://github.com/ionic-team/ionic/tree/v4.0.0-alpha.7) depends on [@stencil/core ^0.9.1](https://github.com/ionic-team/ionic/blob/v4.0.0-alpha.7/core/package.json#L28) which depends on [typescript ^2.8.3](https://github.com/ionic-team/stencil/blob/v0.9.1/package.json#L53).

**Comment by granthoff1107** [comment]
@kael perfect thanks
