### ISSUE TITLE
[v4] Toast don't appears with modal open

### ISSUE THREAD

**Issue by rodrigoreal** [ionic-team/ionic#14623]
When i present a toast from a modal, the toast is being presented behind the modal.
With the modal open the toast is being hidden, but if i close the modal, the toast appears, maybe it is something related to z-index.

**Comment by rodrigoreal** [comment]
Just open a modal and then show a toast.
You will notice that the toast is showing behind the modal.

**Comment by adamlacombe** [comment]
I experienced this as well. Try setting the 'cssClass' option to a class that has a z-index value greater than the modal.

```typescript
const toast = await this.toastCtrl.create({
      message: 'testing',
      duration: 2500,
      position: 'top',
      cssClass: 'test-toast'
    });
    toast.present();
```

```css
.test-toast {
  z-index: 99999;
}
```

**Comment by daem0ndev** [comment]
Also experiencing this issue in v4. Can obviously fix with my own manual CSS, but would be nice to have it resolved in the framework code. Also for anyone else, heres how I patched it globally so I dont have to manually apply the custom class every time I show a toast:

```
ion-toast { z-index: 30000; }
```

I noticed modal z-indexes were in the 20000 range so this should put it just high enough.
