### ISSUE TITLE
V4: Toggles overflow 

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic#14626]
Toggles seem to overflow the background color.
![img_6445](https://user-images.githubusercontent.com/2835826/41488565-c0d3395e-70ba-11e8-86b9-4939ddfb3802.PNG)
![img_6444](https://user-images.githubusercontent.com/2835826/41488566-c364a5e0-70ba-11e8-8549-6da2189d1632.PNG)

**Steps to Reproduce**
- See the toggle e2e demo

**Comment by brandyscarney** [comment]
Note that this is only in Safari / iOS

**Comment by modemlooper** [comment]
This is still an issue in beta 12
