### ISSUE TITLE
Swipe toast down to close.

### ISSUE THREAD

**Issue by joe-scotto** [ionic-team/ionic#14625]
# Feature Request

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0
    @ionic/cli-plugin-ionic-angular : 1.4.0
    @ionic/cli-utils                : 1.6.0
    ionic (Ionic CLI)               : 3.6.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node       : v6.11.3
    OS         : macOS High Sierra
    Xcode      : Xcode 9.0 Build version 9A235
    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    npm        : 3.10.10
```

**Describe the Feature Request**
Swiping down would close a toast

**Describe Preferred Solution**
Swiping down on a toast should dismiss it

**Describe Alternatives**
A close button isn't an option since I'm using a custom implementation of the toast component with a yes and no button

**Comment by HansKrywaa** [comment]
+1
