### ISSUE TITLE
Plugin doesn't support this project's cordova-android version. While installing cordova-plugin-geofence plugin

### ISSUE THREAD

**Issue by Shadzzz** [ionic-team/ionic#14621]
C:\My App\test>ionic cordova plugin add cordova-plugin-geofence
> cordova plugin add cordova-plugin-geofence --save
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted
 {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ minimist@1.2.0
+ xml2js@0.4.19
updated 2 packages in 33.453s

Installing "cordova-plugin-geofence" for android

Installing "cordova-plugin-add-swift-support" for android

Android Studio project detected

Installing "cordova-plugin-compat" for android

**Plugin doesn't support this project's cordova-android version. cordova-android: 7.0.0, failed
 version requirement:
      <6.3.0**

Skipping 'cordova-plugin-compat' for android
Installing "es6-promise-plugin" for android

Subproject Path: CordovaLib
Subproject Path: app
Adding cordova-plugin-geofence to package.json

Saved plugin info for "cordova-plugin-geofence" to config.xml

Ionic Versions Info :

cli packages: (C:\Users\Shadab\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.6.0
    OS   : Windows 7

Environment Variables:

    ANDROID_HOME : C:\Users\Shadab\AppData\Local\Android\sdk;

Misc:

    backend : pro

**Comment by mhartington** [comment]
Hi there! This issue does not appear to be an issue with the framework itself, so it will be closes. Please review your issue and open a new ticket on the appropriate project repository, or feel free to post a question on the [Ionic Forum](http://forum.ionicframework.com). Thanks!
