### ISSUE TITLE
V4 Ion-Navbar throws error

### ISSUE THREAD

**Issue by granthoff1107** [ionic-team/ionic#14635]
I'm working on upgrading my Ionic App to Ionic 4 and Angular 6.  I have a component which uses some of the ionic's components but they seem to not be registered.  I've created a new project and I'm using the Tabs Start,  My Html looks like so:

    <ion-header>
      <ion-navbar align-title="center">
         <ion-title>Home</ion-title
      </ion-navbar>
    </ion-header>

I changed the home page to use the ion-navbar but now I'm getting an error:

>ERROR Error: Uncaught (in promise): Error: Template parse errors:
'ion-navbar' is not a known element

Has the nav-bar been removed from Ionic?

**Comment by kinggolf** [comment]
@granthoff1107 This is broken - please see [link](https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#navbar)! Be forewarned, if building to cordova platform there seems to be issues with V4 ionicons - see [this bug](https://github.com/ionic-team/ionic/issues/14509). I just came across same thing with back arrow icon in nav bar while building to Android.

**Comment by granthoff1107** [comment]
Interesting, i also noticed ion-search bar throws the same error, I didn’t see anything mentioning that, the then again I’m looking from my phone. Is that deprecated as well

**Comment by kinggolf** [comment]
All breaking changes listed [here](https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md). Do not see ion-search in list, but seems likely it should be.

**Comment by brandyscarney** [comment]
Navbar has been removed in favor of using Toolbar. Please see the breaking changes here: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#navbar

There shouldn't be any breaking changes with `ion-searchbar`, please let me know if you are seeing issues there. Thanks!
