### ISSUE TITLE
Popovercontroller Ionic 4?

### ISSUE THREAD

**Issue by RZR666** [ionic-team/ionic#14633]
# Bug Report

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.1
   @ionic/schematics-angular  : 1.0.0-rc.6
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7

System:

   NodeJS : v10.4.0
   npm    : 6.1.0
   OS     : macOS High Sierra

```
const popover = this.popoverCtrl.create({
  component: 'PopupMenuComponent',
  ev: event
});

popover.present();
```

```
[ts] Property 'present' does not exist on type 'Promise<HTMLIonPopoverElement>'.
```

I don't see it mentioned in the Breaking Changes

**Comment by kael** [comment]
The `present()` method [exists](https://github.com/ionic-team/ionic/blob/v4.0.0-alpha.7/core/src/components/popover/popover.tsx#L176).

There's an [example for Ionic-Angular](https://github.com/ionic-team/ionic/blob/master/core/src/components/popover/usage/angular.md) (haven't tested as I'm using Ionic with Stencil).

**Comment by brandyscarney** [comment]
Thanks @kael for replying with the example. 🙂 

@RZR666 You need to use `async`/`await` like the example kael replied with. I have added this to the breaking changes now: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#overlays

**Comment by RZR666** [comment]
Thanks, that solved one issue but left me with another.

Trying to load the component I have created is just not working.  Is it a routing issue?

I've added the CLI created Component to AppModule and the Page Module itself but none are working.
