### ISSUE TITLE
Ionic v3 Ion-Popover in --aot or --prod brakes app

### ISSUE THREAD

**Issue by yurafox** [ionic-team/ionic#14637]
**Ionic Info**
cli packages: (C:\Users\Yura\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 6.3.0 browser 5.0.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.2
    npm               : 5.4.2 
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Android\android-sdk

Misc:

    backend : pro

**Describe the Bug**
Presenting and further closing of Ion-popover does not removes it from DOM, causing app to "freeze". This only happens as a result of --aot or --prod builds. 

**Expected Behavior**
After closing of popover (or dismissing of loading), popovers should be removed from DOM and do not lock the app.

**Additional Context**
Such things happens as a result of every modal (loadings, toasts, popovers etc) presentation and further dismiss

**Comment by pmenager** [comment]
We have users reporting the same problem.
@yurafox did you fint a solution, is the problem still here?
