### ISSUE TITLE
ion-router: dynamic <head/> Meta Tags (for Open Graph and other social metadata)

### ISSUE THREAD

**Issue by kael** [ionic-team/ionic#14638]
**Feature Request**
When sharing a link from a Ionic-based PWA, it'd be nice to have a way to dynamically setup the `<meta property="og:*" content="*">` headers so that the recipient of the link can get a nice preview using social apps.

The router could receive a new `headers` parameter to then pass them as some additional `<meta/>`or `<link/>`, that would generate something like:

```html
<meta property="og:title" content="My Social Page">
<meta property="og:description" content="Whatever">
<meta property="og:image" content="http://host/assets/image/1/thumbnail.jpg">
<meta property="og:url" content="http://host/page/1">
<link rel="canonical" href="http://host/page/1">
```

See _[Meta Tags for Social Media](https://css-tricks.com/essential-meta-tags-social-media/)_.

**Comment by kael** [comment]
Nice, thanks. I didn't know about the _Angular_ `Meta` service.

I'm using _Stencil_ with _Ionic Core_, so I was looking for something perhaps around the `ion-router`. But I'll dig further so. Thanks !

**Comment by MichaelHuy** [comment]
also happen on ionic 3
