### ISSUE TITLE
Ionic View App is unavailable in Russian App Store

### ISSUE THREAD

**Issue by glebmachine** [ionic-team/ionic#14632]
# Feature Request
Made View App available in Russian App Store (like dev app, and other apps)
![Image of Fail](http://joxi.ru/v29pRJi3jNeJmG.jpg)

**Describe Alternatives**
There is no alternatives. 
That's odd, i can do everything (pay account, develop an app, build, monitor, deploy, except testing it)

I hope you will unlock testing app soon, thank you guys)
@mlynch could you please pay attention

**Comment by mlynch** [comment]
Apple is banning al testing/preview apps and they rejected View. There’s nothing we can do and they are killing off the whole category. 

It’s out of our hands

**Comment by glebmachine** [comment]
@mlynch, thank you for quick response!

That’s so bad(
Do you plan to add ability to unstall-via-link? (Like PhoneGap do)
