### ISSUE TITLE
ion-reorder-group bugs in ionic/core

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/ionic#14640]
# Bug Report

**Ionic Info**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

System:

    Node : v8.9.1
    npm  : 5.7.1
    OS   : macOS High Sierra

Misc:

    backend : pro
```

**Describe the Bug**
There are several issues when using the `<ion-reorder-group>` component with ionic/core and Stencil.

1. There does not appear to be a way to get an event when the user moves an item.  Prior versions of Ionic used `<ion-list reorder="true" (ionItemReorder)="moveItem($event)">` so that the application could act on the change that was made by the user.  The new `<ion-reorder-group>` component does not raise an event.
2. The `<ion-reorder>` component does not result in the icon being displayed.  It looks like the icon is getting rendered but it does not display.  I used the style from the example:
```tsx
<ion-content>
  <ion-list>
    <ion-reorder-group>
      <ion-item>
        <ion-label>
          Item 1
        </ion-label>
        <ion-reorder slot="end"></ion-reorder>
      </ion-item>
    </ion-reorder-group>
  </ion-list>
</ion-content>
```
3. Dragging and dropping does not move the items.

**Comment by olivier-po** [comment]
1. (ionItemReorder) is definitely missing.
2. I don't have any issue with the icon rendering.

**Comment by pwespi** [comment]
Furthermore, https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md does not contain anything about the reorder components.

**Comment by pwespi** [comment]
For me the reorder icon renders fine in Chrome, but not in Firefox or Edge.
(reproduce by opening https://beta.ionicframework.com/docs/api/reorder/ in all three browsers and click toggle in the preview)

**Comment by cranderveldt** [comment]
It may also be worth noting that this page doesn't have content: https://beta.ionicframework.com/docs/reorder/

**Comment by hcassar93** [comment]
(ionItemReorder) still definitely missing. Hope someone can look at this soon. 

Loving v4 so far. Cant wait till the few bugs are gone.
