### ISSUE TITLE
<ion-tab> does not update when badge is changed

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/ionic#14649]
# Bug Report

**Ionic Info**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

System:

    Node : v8.9.1
    npm  : 5.7.1
    OS   : macOS High Sierra

Misc:

    backend : pro
```

**Describe the Bug**
If a `<ion-tabs>` component is re-rendered and attempts to change a `badge` on one of the tabs, the element is not updated.

For example:

```tsx
    @State() badgeText: string;
    render() {
        return (
            <div>
                <ion-tabs>
                    <ion-tab label="A">
                        <ion-nav />
                    </ion-tab>
                    <ion-tab label="B" badge={this.badgeText}>
                        <ion-nav />
                    </ion-tab>
                </ion-tabs>
            </div>
        );
    }
```

If the component renders with an initial `badgeText` value of `5` then the tab bar is displayed with the correct badge.

I the badgeText is changed to `6` then the render method is called again but the displayed tab bar does not change and still shows a value of 5.  If you click on tab B then the value then changes to `6`.

Looking at the source code it looks like this may happen for changes to other other tab properties (label, icon, badgeColor).  The `<ion-tab-button>` element is assuming that the `<ion-tab>` element is immutable but any of it's properties can end up changing if the parent renders with different values.

Some more details on Stencil prop changes related to rendering are here: 

https://github.com/ionic-team/stencil/issues/791

**Comment by DmytroKurapin** [comment]
Same issue I have with:
```
   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

System:

   NodeJS : v8.11.3
   npm    : 6.1.0
   OS     : Windows 10
```
