### ISSUE TITLE
BreakingChanges.md file for ionic v4

### ISSUE THREAD

**Issue by sachinsemlety** [ionic-team/ionic#14644]
Hi,
Everything is perfect in [BREAKING.md](https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md) file but only one thing is not perfect it is small mistake made in the document i.e in overlays there is new and old Usage  example but for new Usage it should be async/await and old usage it was not there, please check that

**Comment by brandyscarney** [comment]
Thanks! This is fixed now: https://github.com/ionic-team/ionic/commit/30646d8ad08be0bec41c8c32821947882fe2a58c
