### ISSUE TITLE
VirtualScroll Starts List Too Far Down in Viewport - Causes White Space with Large Lists When Rapidly Scrolling Up and Down

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [ionic-team/ionic#14645]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

cli packages: (/home/brian/Websites/Music-Blobs/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.1.0 browser 5.0.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v9.11.2
    npm  : 5.10.0 
    OS   : Linux 4.15

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Describe the Bug**
When a large number of items is inside of a virtualScroll there are cases where the list starts too far down in the viewport. This causes there to be white space where there should be items.

**Steps to Reproduce**
1. Go to https://musicblobs.com on a mobile device (I've be able to replicate the issue in Chrome on rare occasions as well)
2. Load a couple hundred songs with the infinite scroll (by scrolling down)
3. Scroll up and down rapidly

**Expected Behavior**
This should never happen. Ideally, there should be a way of forcing X number of items on the top and bottom of the list. Does anybody have any tips on how I can accomplish this? The VirtualScroll library is daunting so I haven't taken a swing at it yet but I figured this is worthy of a bug report.

**Comment by torsorensen** [comment]
Same for me.
I cannot get the "officially supported " VirtualScroll from ionic to work properly on neither iOS nor Android. After researching it quite a bit, it seems there are more things broken in the library. I would leave it for now,

In the meantime, this project saved me. Especially on an iPhone SE it scrolls through 1000 items flawlessly!

https://github.com/rintoj/angular2-virtual-scroll

**Comment by TimeTravelersHackedMe** [comment]
Hmm... thanks for the suggestion but that didn't work with my project. I'm using Angular 5 and the project says it's for Angular 2. What version are you using?

**Comment by TimeTravelersHackedMe** [comment]
This fix appears to be working for me:

1. Go into node_modules/ionic-angular/components/virtual-scroll/virtual-util.js
2. Replace the line that says startCellIndex = Math.max(startCellIndex, 0);
3. With the following:

```
  startCellIndex = Math.max(startCellIndex, 0);
  startCellIndex = startCellIndex - 6;
  if(startCellIndex < 0) {
    startCellIndex = 0;
  }
```

This code will keep another 6 items at the top of the list. Adjust the number to your liking.
