### ISSUE TITLE
Ios password autofill prediction

### ISSUE THREAD

**Issue by vladnaiden** [ionic-team/ionic#14654]
Is there a way to achieve password autofill prediction on ios application in Ionic? 
![image](https://user-images.githubusercontent.com/6985633/41666561-7ae0220c-74b3-11e8-8028-bfa736f110d4.png)

We've been struggling on this problem for several days and couldnt find appropriate the answer. First of all there should be some plugin or configuration to add webcredentials to assosiated domains on build as plugin ionic-plugin-deeplinks doing with applinks. 
Not sure is that theme related to bugs or feature request as I couldnt find any usefull information describing the problem. 

    @ionic/cli-plugin-proxy : 1.5.8
    @ionic/cli-utils        : 1.19.2
    ionic (Ionic CLI)       : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.3
    ios-deploy        : 1.9.2 
    Node              : v8.11.3
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4 Build version 9F1027a 

**Additional Context**
We followed Apple video presentation https://developer.apple.com/videos/play/wwdc2017/206/ and any guide with additional information we could find. In device console we received AASA validation 
![image](https://user-images.githubusercontent.com/6985633/41666968-76e5cbce-74b4-11e8-87d7-07ad298a143b.png). So everything should be working well as there should not be any difficulties with that feature.
Also, we had created another blank ios application and by following this article https://medium.com/@abhimuralidharan/password-autofill-for-ios-apps-for-faster-login-ios-11-1d9f77deb35a have set content-type for email and password field and as expected the feature of password autofill worked.

**Comment by OakBehringer** [comment]
+1
