### ISSUE TITLE
v4 Breaking Change for IonicErrorHandler

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#14651]
# Bug Report

**Ionic Info**
```
Ionic:
   ionic (Ionic CLI)          : 4.0.0-rc.9 (/usr/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7
   @angular-devkit/core       : 0.7.0-rc.0
   @angular-devkit/schematics : 0.7.0-rc.0
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.8
   @ionic/schematics-angular  : 1.0.0-rc.8

System:
   NodeJS : v8.11.1 (/usr/bin/node)
   npm    : 6.1.0
   OS     : Linux 4.15
```

**Describe the Bug**
In ionic 2/3 there was Ionic's custom `ErrorHandler` which was named `IonicErrorHandler`. In `Ionic4.beta7`  and previous we can not extend anymore this custom error handler because it doesn't exist.
So perhaps it is was only forgotten, or under development but if not not perhaps you should document it as breaking change.

**Comment by adamdbradley** [comment]
`IonicErrorHandler` will no longer be provided from Ionic, and was largely available for app-script's dev server error logging. You can still extend Angular's `ErrorHandler`: https://angular.io/api/core/ErrorHandler
