### ISSUE TITLE
ionScroll event not firing

### ISSUE THREAD

**Issue by popcorn245** [ionic-team/ionic#14668]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

System:

   NodeJS : v8.11.1
   npm    : 5.6.0
   OS     : Windows 10
```

**Describe the Bug**
When using Ionic PWA toolkit I can't seem to listen for the ionScroll event.  I have added the prop scrollEvent={true} to the ion-content and still get nothing.  I have create a public repo to demo the issue.

**Steps to Reproduce**
1. Clone repo https://github.com/MadnessLabs/ionic-ionscroll
2. npm install
3. npm start
4. Open 'app-home.tsx' and you will see that it should be console logging events from scrolling

**Related Code**
I spun up a public repo that reproduces the issue.
[GitHub Repo](https://github.com/MadnessLabs/ionic-ionscroll).

**Expected Behavior**
I expect it to allow me to listen for ionScroll

**Additional Context**
I tried listening on the body and on the main component that loads my app and all give me nothing.

**Comment by paulstelzer** [comment]
You have to activate scoll events, see https://beta.ionicframework.com/docs/api/content
