### ISSUE TITLE
ion-thumbnail does not maintain aspect ratio

### ISSUE THREAD

**Issue by shamilovtim** [ionic-team/ionic#14660]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v9.8.0
    npm        : 6.1.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4.1 Build version 9F2000

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Describe the Bug**
Reopening  #3988 , this should be the stock behavior of the component. It's almost always warped in daily use if the image isn't 1:1, which most images aren't.

**Comment by abritopach** [comment]
I don't know if it's the right solution but adding a class with auto width and auto
 height solves the problem.

`
<ion-thumbnail slot="start">
       <img *ngIf="project.thumbnail !== ''" [src]="project.thumbnail" class="thumbnailImg">
</ion-thumbnail>


.thumbnailImg {
    width: auto;
    height: auto;
}
`
**NOTE**: Attached gif where you see the problem

![example](https://user-images.githubusercontent.com/2934069/47662115-a2592d80-db9a-11e8-9167-5b6316ef0f1b.gif)
