### ISSUE TITLE
AngularFire2 Google Login in android not working when Native-Firebase or Native-FCM plugins are installed 

### ISSUE THREAD

**Issue by krngd2** [ionic-team/ionic#14663]
Whenever i try to implement any firebase push notification feature, Google-Plus Login stopped working on android device without trowing any errors,

[Here i have described my error in stack-overflow ](https://stackoverflow.com/questions/50898959/ionic-3-firebase-google-auth-stoped-working-in-android-device?noredirect=1#comment88851157_50898959)

I have implemented the google plus sign in method in try catch method and found the entire try catch method is not running at all. 
First i installed native firebase plugin and then native FCM plugin and both had same issue, remove it and started working again.

Here is my package.json file 

> {
  "name": "VBFashions",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "5.2.10",
    "@ angular/common": "5.2.10",
    "@ angular/compiler": "5.2.10",
    "@ angular/compiler-cli": "5.2.10",
    "@ angular/core": "5.2.10",
    "@ angular/forms": "5.2.10",
    "@ angular/http": "5.2.10",
    "@ angular/platform-browser": "5.2.10",
    "@ angular/platform-browser-dynamic": "5.2.10",
    "@ ionic-native/base64": "^4.7.0",
    "@ ionic-native/camera": "^4.7.0",
    "@ ionic-native/core": "4.7.0",
    "@ ionic-native/file": "^4.7.0",
    "@ ionic-native/file-transfer": "^4.7.0",
    "@ ionic-native/google-plus": "^4.7.0",
    "@ ionic-native/image-picker": "^4.7.0",
    "@ ionic-native/image-resizer": "^4.7.0",
    "@ ionic-native/splash-screen": "4.7.0",
    "@ ionic-native/status-bar": "4.7.0",
    "@ ionic/storage": "2.1.3",
    "angularfire2": "^5.0.0-rc.10",
    "com-badrit-base64": "^0.2.0",
    "cordova-android": "^6.3.0",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-firebase": "^1.0.5",
    "cordova-plugin-googleplus": "^5.3.0",
    "cordova-plugin-image-picker": "^1.1.3",
    "cordova-plugin-ionic-keyboard": "^2.1.2",
    "cordova-plugin-ionic-webview": "^1.2.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-telerik-imagepicker": "^2.1.10",
    "cordova-plugin-whitelist": "^1.3.3",
    "firebase": "^5.0.3",
    "firebase-admin": "^5.12.1",
    "firebase-functions": "^1.0.2",
    "info.protonet.imageresizer": "^0.1.1",
    "ionic-angular": "3.9.2",
    "ionic-image-loader": "^5.0.0",
    "ionic-img-viewer": "^2.9.0",
    "ionicons": "3.0.0",
    "promise-polyfill": "^7.1.2",
    "rxjs": "^6.2.1",
    "rxjs-compat": "^6.1.0",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.10",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-file": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-image-picker": {},
      "cordova-plugin-whitelist": {},
      "com-badrit-base64": {},
      "info.protonet.imageresizer": {},
      "cordova-plugin-googleplus": {
        "REVERSED_CLIENT_ID": "******"
      },
      "cordova-plugin-compat": {}
    },
    "platforms": [
      "android"
    ]
  }
}

**Comment by fdambrosio** [comment]
I have the same problem
