### ISSUE TITLE
Icons are showing incorrectly when adding Ionic PWA Elements

### ISSUE THREAD

**Issue by json-derulo** [ionic-team/ionic#14678]
# Bug Report

**Ionic Info**

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

local packages:

    @ionic/app-scripts : 3.1.10
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.3
    npm  : 5.6.0 
    OS   : macOS High Sierra

Misc:

    backend : pro
```

**Describe the Bug**
I am developing a Capacitor App. I added the Ionic PWA Elements for PWA support. But now icons are showing incorrectly. For example the menu icon is displayed twice. If I remove PWA Elements, everything is working again as expected.

**Steps to Reproduce**
1. Create an Ionic project with the sidemenu template
2. Add the following code to the `index.html`: `<script src="https://unpkg.com/@ionic/pwa-elements@0.0.11/dist/ionicpwaelements.js"></script>` (tried different positions inside `index.html`)
3. Run `ionic serve` and display the app in the browser

**Expected Behavior**
Icons are showing correctly

**Additional Context**
I got the snippet for PWA support from the following issue: https://github.com/ionic-team/capacitor/issues/358

Screenshot of the issue:<br> ![image](https://user-images.githubusercontent.com/18580672/41848942-89e5b1e8-787f-11e8-9799-d79372881a25.png)

**Comment by zsoflin** [comment]
I am having the same issue.

**Comment by rakshasaini20** [comment]
I am finding the same issue in my app.

**Comment by JVanloofsvelt** [comment]
Exactly the same issue here

**Comment by matthew-valenti** [comment]
Confirmed this is still an issue with:
ionic 4.0.0-beta.3
capacitor 1.0.0-beta.7
https://unpkg.com/@ionic/pwa-elements@0.0.14/dist/ionicpwaelements.js

**Comment by dalepo** [comment]
I have the same issue
