### ISSUE TITLE
Cannot create a new project with Ionic

### ISSUE THREAD

**Issue by alim90** [ionic-team/ionic#14698]
I am unable to create a new ionic project with cordova.

When the prompt ask me if I want to integrate cordova with the app and whatever my answer was (Yes or no), I have to wait hours and hours and nothing happens and just a folder with just single file (src) is created.

I am using the latest version of Node and NPM.

I tried to uninstall everything globally and re-install it again, but still having the same problem.

Any help would be appreciated.

**Comment by mburger81** [comment]
You should close and open this issues with a few mor information on the ionic cli github page https://github.com/ionic-team/ionic-cli

**Comment by alim90** [comment]
I did. Here is a link https://github.com/ionic-team/ionic-cli/issues/3347
