### ISSUE TITLE
My navbar is being pushed out of the view when i'm focusing an ion-input

### ISSUE THREAD

**Issue by DeveloperMatheus** [ionic-team/ionic#14695]
# Bug Report

**Ionic Info**
cli packages:

  @ionic/cli-utils  : 1.19.2
  ionic (Ionic CLI) : 3.20.0

global packages:

  cordova (Cordova CLI) : 7.0.1

local packages:

  @ionic/app-scripts : 3.1.8

  Cordova Platforms  : android 6.3.0 ios 4.5.4
  Ionic Framework    : ionic-angular 3.9.2

System:

  Android SDK Tools : 26.0.2
  ios-deploy        : 1.9.2
  ios-sim           : 6.0.0
  Node              : v6.11.2
  npm               : 5.5.1
  OS                : macOS High Sierra
  Xcode             : Xcode 9.4.1 Build version 9F2000

Environment Variables:

  ANDROID_HOME : /Users/adss/Library/Android/sdk

Misc:

  backend : legacy

**Describe the Bug**
This bug just happens in iOS devices, not on Android OS.

When i tap to focus an ion-input that is not on the top (more like in the middle and below) of the page and require the automatic scroll, the keyboard goes up, and pushes upwards the header itself.

**Steps to Reproduce**
1. I tap on an input that makes this scroll
2. The scroll to focus the input happens (so the input will not overlap the input itself)
3. This is where the unexpected behavior begins: The header goes out of my view, above the screen, and to see i need to unfocus the input

**Related Code**
Well, i can provide a snippet of the page, but i can't reproduce since this is related to the device... Anyway, here's the snippet:  https://pastebin.com/871yPviu

**Expected Behavior**
The header should not be pushed up when i focus an input that requires the automatic scroll. It should stay inside my view.

**Additional Context**
Here is a gif showing what is going on: https://giphy.com/gifs/Yj7fd4ooQgNl6wRI8f you guys can see the big purple bar ApPet being pushed out

I have tried to replace the width properties of the columns to col-number, i tried to place the most basic header and navbar from the docs, i have tried to change the scrollassist properties inside my app.module.ts. The only thing i still didn't try yet, was to change the webview of my app to WK. This is happenning on all screens of my app.

**Comment by aaronneon2** [comment]
Happens to me too and I managed to fix it.
Can you check if you are using the cordova-plugin-ionic-keyboard plugin? If you are, add these 2 lines in config.xml
<preference name="KeyboardResize" value="true" />
<preference name="KeyboardResizeMode" value="ionic" />

See if these solves your issue.
