### ISSUE TITLE
VirtualScroll CSS Not Updating Until List is Scrolled

### ISSUE THREAD

**Issue by adampaul88** [ionic-team/ionic#14696]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
When using a virtual scroll list, randomly the styles of elements stop updating.

**Expected behavior:**
As I click on different elements (buttons) in my virtual list, I would expect their styles to update. 

**Steps to reproduce:**
(1) Create a virtual list of 1000 items. 
(2) On click of an element store the elements id, and then using ngClass or [style.x] have the style of the selected item change. 
(3) It will work for a little while but as you scroll further down it will stop working, and 

**Related code:**
https://github.com/NextCenturyMeters/IonicVirtualScrollBug is a sample project I quickly made that shows the issue. You will notice clicking on the different buttons works for a little bit, but after scrolling around eventually the background color of the buttons stop changing as you click them. 
If you check the console, you will notice the click events still come through, the css just doesn't get updated until the list is scrolled. 

Main List HTML
```
<ion-content padding>
  <ion-list [virtualScroll]="testListData" approxItemHeight="57px" approxItemWidth="100%">
    <div *virtualItem="let td" style="width: 100%; height: auto; margin: 4px 0">
      <button ion-button style="width: 100%; height: 57px; color: black"
              (click)="selectedItem = td._id; logClick(td._id)"
              [style.background-color]="selectedItem === td._id ? 'red' : 'blue'">
        {{td.name}}
      </button>
    </div>
  </ion-list>
</ion-content>
```

Main List .ts
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

export interface ITestListData {
  _id: number;
  name: string;
  value: number;
}

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  public testListData: ITestListData[] = [];
  public selectedItem: number = null;

  constructor(public navCtrl: NavController) {
    for(let i = 0; i < 1000; i++) {
      this.testListData.push({
        _id: i,
        name: 'Item #' + i,
        value: i,
      });
    }
  }

  public logClick(id) {
    console.log('Item Clicked:', id, 'Selected Item:', this.selectedItem);
  }

}
```

**Comment by adampaul88** [comment]
Was able to resolve this by changing logClick() to

```
  public logClick(id) {
    console.log('Item Clicked:', id, 'Selected Item:', this.selectedItem);
    this.applicationRef.tick();
  }
```

Looks like the virtual scroll component is missing the changes sometimes.

**Comment by zwacky** [comment]
The docs point out that you should be using [[virtualTrackBy]](https://ionicframework.com/docs/api/components/virtual-scroll/VirtualScroll/#changing-dataset-should-use-virtualtrackby-) for changing data sets. Haven't tried myself, but this might help.

I'm using `ion-virtual-scroll` on v4 and have the same issue, that it starts updating only after there's been a resize event that triggers the diffing. Only [this approach](https://github.com/ionic-team/ionic/issues/14681#issuecomment-403000988) works for me but the whole list also gets flickery and doesn't look nice:

```
const event:any = (new window['Event']('resize') as any);
window.dispatchEvent(event);
```
