### ISSUE TITLE
v4: Ion grid does not work as expected

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#14699]
# Bug Report

**Ionic Info**
```
Ionic:
   ionic (Ionic CLI)          : 4.0.0-rc.9 (/usr/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7
   @angular-devkit/core       : 0.7.0-rc.0
   @angular-devkit/schematics : 0.7.0-rc.0
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.9
   @ionic/schematics-angular  : 1.0.0-rc.9

Cordova:
   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.0

System:
   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.1 (/usr/bin/node)
   npm               : 6.1.0
   OS                : Linux 4.15

Environment:
   ANDROID_HOME : /...../android/sdk
```

**Describe the Bug**
We are migrating our app to ionic4, we have several problems with the grid which need a lot of work to migrate it, but we love the new approach.

Having a look to this documentation (http://ionic-docs.herokuapp.com/docs/layout/grid/), we see (or we think we can see) some of the same problems we have in our app.

We'll list some of the (perhaps) bugs we think there are, perhaps they could be also only documentation error.

1) Column 2 are not wider then the others
![image](https://user-images.githubusercontent.com/3778892/42214415-cfd13d5c-7ebb-11e8-958f-3316f85ca0b6.png)

2) Having a look at the markup column 1 and 4 should be twice larger then col 2 and 3, also there is  documented some times to use **col-** but this should be the new **size-** right?
![image](https://user-images.githubusercontent.com/3778892/42214785-c8379bf8-7ebc-11e8-82d5-186e67970ccc.png)

3) This example of stacked seems to not work
![image](https://user-images.githubusercontent.com/3778892/42214901-175bdcee-7ebd-11e8-8cf7-dc50dcac76f7.png)

4) Horizontal alignment seems to not work at all, not sure if all row and col attributes does work as expected
![image](https://user-images.githubusercontent.com/3778892/42214934-35a4deb2-7ebd-11e8-9346-d68c0d99619a.png)

Thx a lot

**Comment by brandyscarney** [comment]
Thanks for the issue! The latest alpha release still uses the old grid attributes (`col-*`, `offset-*`, etc.) but the documentation has been updated for what is on master. We aren't able to do a new alpha release until the `core-css-variables` branch is stable, but the new grid API is what is documented in the markup tabs and the previews will work as soon as we get a new release out. Sorry about that!

**Comment by MrSparklle** [comment]
This issue has been solved in beta-11, please close.

**Comment by brandyscarney** [comment]
Thanks @MrSparklle!

I confirmed the documentation is looking good now, thanks for the issue! 

https://beta.ionicframework.com/docs/layout/grid
