### ISSUE TITLE
v4: ion-item underline flickering in and out on navigation transitions in capacitor

### ISSUE THREAD

**Issue by 509dave16** [ionic-team/ionic#14692]
# Bug Report

**Ionic Info**
```
platform:
Android emulator, SDK 25

ionic packages:
- @ionic/core@4.0.0-alpha.7
- @capacitor/cli": "^1.0.0-beta.0
- @capacitor/core": "^1.0.0-beta.0

cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

System:

    Node : v8.9.1
    npm  : 5.5.1
    OS   : macOS High Sierra
```

**Describe the Bug**
When navigating through pages in an app using @ionic/core that's dropped into capacitor, ion-items have underline text style applied and then removed.

**Steps to Reproduce**
1. Have an `<ion-router>` defined with at least two `<ion-routes>`(ionic-pwa-toolkit is what my project is based off of)
2. Defined `<ion-list>` with at least one `<ion-item>` in one of the Stencil Components referred to in your routes that has an href referring to another Stencil Component(this component should also have an `<ion-list>` with at least one `<ion-item>`
3. Click on an item.
4. You should see the flickering of the underline text-style on the items as you transition to a page

NOTE: This was dropped into capacitor following this guide: https://capacitor.ionicframework.com/docs/basics/building-your-app

**Related Code**
https://github.com/ionic-team/ionic-pwa-toolkit

**Expected Behavior**
No flickering of style affects on transition to another component.

**Additional Context**
Capacitor
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2925882/42052886-e3e3ebe6-7ac4-11e8-94f6-7f7ec78edd91.gif)

**Comment by dotnetdreamer** [comment]
Looks like everyone is sleep :D

**Comment by paulstelzer** [comment]
COuld you please post this issue at the Capacitor repository if it still exist?
