### ISSUE TITLE
VirtualScroll Prevents Smooth Scrolling on WebKit Based Browsers

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [ionic-team/ionic#14694]
# Bug Report

**Ionic Info**
cli packages: (/home/brian/Websites/Music-Blobs/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.1.0 browser 5.0.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v9.11.2
    npm  : 5.10.0 
    OS   : Linux 4.15

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Describe the Bug**
On some mobile browsers VirtualScroll prevents smooth scrolling. It works but it prevents the smooth scrolling that apps have. It works fine on Samsung Mobile and Firefox Mobile but not on Chrome Mobile or the Android WebView.

**Steps to Reproduce**
1. Go to https://musicblobs.com/home on Chrome for Mobile
2. Scroll through the list
3. See the laggy performance

**Expected Behavior**
Performance should be similar to Samsung Mobile Browser or Firefox Mobile Browser

**Additional Context**
Issue also occurs on Edge for Mobile. Couple questions... is there a way I can throttle the VirtualScroll from firing as often? Maybe this will fix the issue. Or is there a way I can use the Samsung Browser engine in my Android app instead of Android WebView. Scrolling seems to be fine on iOS... just webkit-based browsers seem to be affects (and Edge).

**Comment by azzedine221** [comment]
Hllo please i need you hellp please contact me  : https://www.facebook.com/stock.exchnge
