### ISSUE TITLE
v4: Custom Elements with Shadow DOM won't work in forms

### ISSUE THREAD

**Issue by arjunyel** [ionic-team/ionic#14702]
**Describe the Feature Request**
Its a known limitation that Custom Elements with Shadow DOM don't currently work in forms. Currently the form tests pass I believe because without Shadow DOM the form is able to see the native inputs in the light DOM.

**Describe Preferred Solution**
There are three solutions to this

1. Wait for the custom element form API to land in all browsers which may be a while. I don't think a current polyfill exists https://github.com/w3c/webcomponents/issues/187

1. Create a stencil version of iron-form https://github.com/PolymerElements/iron-form

1. Document that you will have to proxy values from ionic components to hidden regular inputs as described in these video, Monica is the world leading expert on this issue so for more details on how to best solve this consider contacting her https://youtu.be/AVXu1_vaY2U https://youtu.be/K76g5DGCBOk 

**Additional Context**
Because ionic components are going to marketed as use anywhere in any framework inevitably people are going to try and use them in forms and be confused when they don't work. Unfortunately till the browser API lands this is gonna involve painful workarounds 😞

**Comment by goelectricstations** [comment]
same issue

**Comment by mhesler74** [comment]
Just ran into this issue while attempting to use an ion-input in a form.
In my particular case it was trying to figure out why the enter button wouldn't submit the form that lead me here.

**Comment by seiyria** [comment]
I've tested this against beta 3 and I can use ngModel again.
