### ISSUE TITLE
VirtualScroll refresh issue on orientation change in iPhone X (and similar screens)

### ISSUE THREAD

**Issue by malwatte** [ionic-team/ionic#14706]
# Bug Report

**Ionic Info**
```
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0
    cordova (Cordova CLI) : 8.0.0
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2
    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v8.10.0
    npm               : 5.6.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4 Build version 9F1027a
```

**Describe the Bug**
I have a page with a VirtualScroll. After a refresh through ion-refresher, virtual items in the VirtualScroll get mispositioned when I change the orientation to landscape.

![screen shot 2018-06-26 at 2 00 38 pm](https://user-images.githubusercontent.com/2534778/42256867-4c203fc4-7f71-11e8-8cef-9c879cb41cf2.png)

As shown in the above screenshot, some of the items are on top of another items.

![screen shot 2018-06-26 at 2 02 45 pm](https://user-images.githubusercontent.com/2534778/42256876-57183a76-7f71-11e8-8ad6-6534525057e1.png)

Here is the rendered html. I see mispositioned items has wrong values for the css property translate3d.
This happens only on wider screens (similar to iPhone x or Galaxy s8). Tested on a iPhone 6 and worked fine.
This can be reproduced in browser too. Set to responsive mode and increase the width little by little. After a certain width, items get overlapped.

**Steps to Reproduce**
1. Set the device to iPhone X
2. Pull to refresh
3. Change the orientation to landscape
4. See items get overlapped

**Related Code**
```
<ion-content padding>
	<ion-refresher (ionRefresh)="reloadItems($event)">
		<ion-refresher-content pullingText="Pull to refresh" refreshingText="Refreshing..."></ion-refresher-content>
	</ion-refresher>
	<ion-list [virtualScroll]="itemList" approxItemHeight="90px" approxItemWidth="100%">
		<button ion-item detail-none no-lines *virtualItem="let item" no-padding no-margin style="height: 90px;width: 100%;">
      <ion-row>
        <ion-col col-2>
          {{item.severity}}
        </ion-col>
        <ion-col col-10>
          <ion-row>{{item.index}} {{item.title}}</ion-row>
          <ion-row>
            <ion-col text-left no-margin>{{item.type | titlecase}}</ion-col>
            <ion-col text-center no-margin>{{item.status | titlecase}}</ion-col>
          </ion-row>
        </ion-col>
      </ion-row>
    </button>
	</ion-list>
</ion-content>
```

Or code sample
https://stackblitz.com/edit/ionic-2ktf9j?file=pages%2Fhome%2Fhome.html

**Expected Behavior**
VirtualScroll should resize properly. Items should not overlap.

[Related question in Ionic forum](https://forum.ionicframework.com/t/virtualscroll-issue-in-iphone-x-and-similar-screens/133599)

**Comment by malwatte** [comment]
Looks like orientation change does not trigger a full refresh. So, I tried this
```
@ViewChild('virtualScroll', { read: VirtualScroll }) virtualScroll: VirtualScroll;

this.virtualScroll.resize();
```
But it didn't work. Nothing happens.

Is there anyway we can force refresh the VirtualScroll?

**Comment by paulstelzer** [comment]
Is this issue still exist in beta.17?

**Comment by malwatte** [comment]
We are still using Ionic 3. We are thinking to move to Ionic 4 soon. But I can check the issue on the latest ionic 4 beta.

**Comment by paulstelzer** [comment]
Ups, my fault - sry. This repository is only for Ionic 4 issues, I will transfer it to Ionic 3
