### ISSUE TITLE
v4 Ion-button [disabled] doesn't stop click

### ISSUE THREAD

**Issue by pedrotcm** [ionic-team/ionic#14719]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.9 (C:\Users\ptome\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7
   @angular-devkit/core       : 0.7.0-rc.0
   @angular-devkit/schematics : 0.7.0-rc.0
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.9
   @ionic/schematics-angular  : 1.0.0-rc.9

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : none

System:

   NodeJS : v8.11.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.1.0
   OS     : Windows 10

Environment:

   ANDROID_HOME : not set
```

**Describe the Bug**
Even if the button disabled the click event is working
```
    <ion-button  [disabled]="!agreeOfTerms" (click)="continueToAuth()">Continuar</ion-button>
```

**Steps to Reproduce**
1. Create a button disabled and a method with a console.log for example. 
2. Click on button
3. See the log

**Expected Behavior**
The click is not to call the method if the button is disabled.

**Comment by brandyscarney** [comment]
Thanks for the issue! I am able to reproduce this in the conference app. 

Note to team:

After discussing with @adamdbradley, we determined there is something going on with shadow DOM. We believe we will need to add this to button when the button is disabled:

```
@Listen('touchstart', { capture: true, enabled: true, passive: false })
@Listen('mousedown', { capture: true, enabled: true, passive: false })
preventClick(ev: UIEvent) {
  console.log('preventClick');
  ev.stopImmediatePropagation();
  ev.preventDefault();
}
```

**Comment by camwiegert** [comment]
Fixed [here](https://github.com/ionic-team/ionic/commit/89d15267083668b9c2b9beacd86fd8f3b3135d20).
