### ISSUE TITLE
ionic 4 beta or ionic 3 + ng router

### ISSUE THREAD

**Issue by dfa1234** [ionic-team/ionic#14714]
### Support Question

I would need to decouple the router from ionic (see the previous issues case I participated to), and to use the one from angular, like it is expected in ionic 4.

I have 2 questions:

- how many time before beta version of ionic 4? and RC? ( I didn't see any roadmap on the blog or anything)
- May I already follow a process to replace ionic router with angular router, already from ionic 3 (and to stay lazy for Modals and Pages).

**Comment by mburger81** [comment]
Forget it to use angular router on ionic3. Old long story, it's not so simple to get it work and you will get no support on it. Wait for ionic4 and you'll have it +- out of the box.
There is no roadmap for ionic4 and you'll never get one. But probably we are close to RC.

For sure this issue would be closed by the team.

**Comment by brandyscarney** [comment]
Thanks for your issue! We have a migration guide on our beta version of the docs for v4 here: https://beta.ionicframework.com/docs/building/migration

We are also working on a migration tool that will let you know what changes need to be made to go from v3 -> v4 (contributions welcomed!): https://github.com/ionic-team/v4-migration-tslint

Our goal is to make the process to upgrade as easy as possible, so please let us know if you find issues with any of us this.

As far as releases & roadmaps, we try to keep our weekly team meeting notes up-to-date with what we're working on and what the latest releases are: https://docs.google.com/document/d/1LrPDUkfXpqPIsghaSCxHyN1GIZ0TK2bwFxOZx2GKWtI/edit?usp=sharing

We've been running into a lot of unknowns that we've had to work through which has set us back on getting to beta, but our last major holdup has been theming. All of our work for theming can be found on this branch: https://github.com/ionic-team/ionic/tree/core-css-variables. Once we have finished porting the components that require custom theming to shadow dom (we're at 96% or so ported), we plan on releasing a new alpha, testing & then moving on to beta. This is something we hope will be done in the next couple of weeks, unless something major comes up. 🤞
