### ISSUE TITLE
v4: Some bugs on ion-card

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#14723]
**Describe the Bug**
We try to use your `ion-card` and sub components using `alpha.7` with latest beta documentation.
We also created a demo repo https://github.com/mburger81/ionic4-tests where you can navigate to `Cards` menu to see bugs and simulate them.

This is what we have figured out, or we think we have figured out :)

1. You can use `ion-card-subtitle` before `ion-card-title`, but this should be a wrong usage and probably you can avoid this by using slots, right? In this case it would be independent from the order you list it in code, we found this bug on your first card example in docs https://beta.ionicframework.com/docs/api/card 
2. The `ion-card-header` on MD should be 20px instead of 24px, right?
3. setting `color` attribute to `ion-card-header` does not have any effect, perhaps color attribute is already documented on docs but not implemented on `alpha.7`?

![image](https://user-images.githubusercontent.com/3778892/42371900-147dc248-8111-11e8-9570-2456fa53c1b1.png)

4. We are not sure how to use `ACTIONS` in `ion-card-header`, perhaps we are missing something or there is a bug, but having a look to your documentation we found this out
    - we should use `ion-item` in `ion-header` if we wan' to use buttons, wrapping `ion-card-title` and `ion-card-subtitle` in `ion-label`
    - if we use `ion-item` in `ion-card-header` the padding is completely different from first example, which should be the right padding

![image](https://user-images.githubusercontent.com/3778892/42372197-e4754c82-8111-11e8-9aea-b20d225452aa.png)

**Comment by Ritzlgrmft** [comment]
I have the same problem with `<ion-card-header color="...">`, using 4.0.0-beta.7
