### ISSUE TITLE
v4: ion-scroll always scrollable even for short content

### ISSUE THREAD

**Issue by ghybs** [ionic-team/ionic#14720]
# Bug Report

**Ionic Info**
Using @ionic/core version 4.0.0-alpha.7 directly from npm / unpkg CDN.
Firefox 60.0.2 (64 bits) and Chromium 66.0.3359.181 (64 bits)
Ubuntu 16.04.4 LTS

**Describe the Bug**
The `<ion-scroll>`'s height is set higher than the available container height when its parent `<ion-content>` has no padding, but child elements need some margin (which is typically the case of an `<ion-menu>` with an `<ion-list>`).
Therefore, even if the content is short and should not require scroll, the content is scrollable.

**Steps to Reproduce**
1. Go to https://beta.ionicframework.com/docs/api/4.0.0-alpha.7/menu
2. Click on the 'Open start menu' button.
3. The menu is scrollable even if its content is shorter than the available height.

This happens for both iOS and MD modes, in all browsers I have tried.

**Related Code**
Simple example for both a menu and a main content:
https://plnkr.co/edit/gTBGa2rqBnxrLeWSJRtZ?p=preview

**Expected Behavior**
When the content is shorter than the available height, it should not be scrollable.

**Additional Context**
Was working fine in version 4.0.0-alpha.6 (https://beta.ionicframework.com/docs/api/4.0.0-alpha.6/menu).
Surely introduced by commit https://github.com/ionic-team/ionic/commit/3da0c989b2cd7e98c2c08cf7496309e7d1219730
Removing the `min-height: 100%` CSS rule (typically with developer tools) removes the bug, but I guess this rule has a reason.

**Comment by manucorporat** [comment]
This will be fixed in next version (alpha.8), the root of the problemas was the collapsible margin
