### ISSUE TITLE
v4 scroll position is not restored

### ISSUE THREAD

**Issue by coonmoo** [ionic-team/ionic#14737]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.9 (C:\Users\xxxx\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7
   @angular-devkit/core       : 0.7.0-rc.0
   @angular-devkit/schematics : 0.7.0-rc.0
   @angular/cli               : 6.1.0-rc.0
   @ionic/ng-toolkit          : 1.0.0-rc.9
   @ionic/schematics-angular  : 1.0.0-rc.9

System:

   NodeJS : v10.5.0 (C:\Program Files\nodejs\node.exe)
   npm    : 5.2.0
   OS     : Windows 10
```

**Describe the Bug**
The scroll position is not restored when navigating back from a page.
If you scroll down a list and then navigate to a detail page and then hit the back button, the scroll position on the originating page is set back to [0, 0], basically loosing the context.
This behaviour is really bad for the user experience.

**Steps to Reproduce**

1. Run ionic serve
2. On home page wait until the list loads and scroll down to e.g. to the last list entry.
3. Click on the list entry and then navigate back from the detail page to the home page.
4. After navigating back the scroll position is set to [0,0], the previously scroll state is not restored.

**Related Code**
Example reproduction: https://github.com/coonmoo/IonicScrollPosBug

**Expected Behavior**
The scroll position should be correctly restored when navigating back from a page.

**Additional Context**
I tried to fix it with the latest Angular 6.1.0 feature of scrollPositionRestoration, but it does not seem to work. Angular's ViewportScroller always reports [0,0] scroll position when navigating back. I suppose that is an Ionic issue, because using plain Angular it seems to work (see also https://github.com/angular/angular/issues/24547).

**Comment by mmlleevvyy** [comment]
@coonmoo  Because ionic uses its own content scrolling component ```ion-scroll```, there has to be implementation of ViewportScroller (angular/common), that will handle scroll position restoration. Angular's default implementation uses window's scroll and that is the reason why it is not working with ionic right now. So, for now, you can implement your very own ViewportScroller and provide in your app module, hopefully ionic will have it implemented as well someday :-)

**Comment by mmlleevvyy** [comment]
Very quick and dirty implementation of ViewportScroller, but if you need it now, you may find it useful:
```
import {NgModule} from '@angular/core';
import {Routes, RouterModule} from '@angular/router';
import {ViewportScroller} from '@angular/common';

const routes: Routes = [];

class IonicViewportScroller extends ViewportScroller {

	private routerOutlet: HTMLElement;

	private offset: () => [number, number] = () => [0, 0];

	private getRouterOutlet(): HTMLElement {

		if (!this.routerOutlet) {
			this.routerOutlet = document.querySelector("ion-router-outlet");
		}

		return this.routerOutlet;
	}

	private getActivePageScroll(which: "active" | "toBeActive") {

		let activePage: HTMLElement;
		let activePageIndex: number;

		let toBeActivePage: HTMLElement;
		let toBeActivePageIndex: number;

		let pages = this.getRouterOutlet().querySelectorAll(".ion-page");
		for (let i = 0; i < pages.length; i++) {
			let p = pages.item(i) as HTMLElement;
			try {

				let index = parseInt(p.style.zIndex);

				if (!activePageIndex || activePageIndex < index) {
					activePageIndex = index;
					activePage = p;
				}
				
				if (activePageIndex > index && (!toBeActivePageIndex || toBeActivePageIndex < index)) {
					toBeActivePage = p;
					toBeActivePageIndex = index;
				}

			} catch {
			}
		}

		let page = (which == "toBeActive" && toBeActivePage) || activePage;

		if (page) {
			return page.querySelector("ion-content > ion-scroll") as HTMLElement;
		}
	}

	setOffset(offset: [number, number] | (() => [number, number])): void {
		if (Array.isArray(offset)) {
			this.offset = () => offset;
		} else {
			this.offset = offset;
		}
	}

	getScrollPosition(): [number, number] {

		let scroll = this.getActivePageScroll("active");
		if (scroll) {
			return [scroll.scrollLeft, scroll.scrollTop];
		} else {
			return [0, 0];
		}
	}

	scrollToPosition(position: [number, number]): void {
		let scroll = this.getActivePageScroll("toBeActive");
		if (scroll) {
			scroll.scrollTo(position[0], position[1]);
		}
	}
	
	scrollToAnchor(anchor: string): void {
		throw new Error("Method not implemented.");
	}

	setHistoryScrollRestoration(scrollRestoration: "auto" | "manual"): void {
	}
}

@NgModule({
	imports: [RouterModule.forRoot(routes, {scrollPositionRestoration: "enabled"})],
	providers: [
		{provide: ViewportScroller, useClass: IonicViewportScroller},
	],
	exports: [RouterModule]
})
export class AppRoutingModule {}
```

**Comment by coonmoo** [comment]
Thanks alot! Your implementation of the `ViewportScroller ` so far rworks like a charm!

**Comment by bashoogzaad** [comment]
What is the latest status of this? Should I implement a ViewPortScroller or are you guys at Ionic working on a solution?

**Comment by rdlabo** [comment]
+1
I also want to know about this Issue.

**Comment by ptitjes** [comment]
@coonmoo Would you mind to share your implementation of ViewPortScroller ?

**Comment by naveedahmed1** [comment]
Any update on this?

**Comment by joanroig** [comment]
Seems like I have the same issue, I've described it here:
https://forum.ionicframework.com/t/ionic-4-returning-to-previous-page-loses-scroll-position/140886
After some research, I've tried the same scrollPositionRestoration as @coonmoo with no success in lastest version 4.0.0-beta.7

**Comment by joanroig** [comment]
My current workaround for this:
https://github.com/joanroig/Ionic4-restore-scroll-position

**Comment by mhartington** [comment]
Hey yall, just chiming in on an update for this.

1) Why is this happening.

In 6.1 of ngRouter, there was a new API in place for restoring scroll position. Only issue is that the API used the document body to work with scrolling. While this works for typical Angular Apps, it does not work with nested scroll containers, like ion-content. 

2) What can be done.

Similar to how we override the router `RouteReuseStrategy` class, we can do the same thing for the `ViewportScroller` API. This is what I'm working on currently and hope to have something to present soon.
