### ISSUE TITLE
v4 bug: ion-datetime allows invalid values

### ISSUE THREAD

**Issue by Simpler1** [ionic-team/ionic#14732]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.9 (/home/user1/.npm-global/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7
   @angular-devkit/core       : 0.7.0-rc.0
   @angular-devkit/schematics : 0.7.0-rc.0
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.9
   @ionic/schematics-angular  : 1.0.0-rc.9

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.3 (/usr/bin/node)
   npm               : 5.6.0
   OS                : Linux 4.13

Environment:

   ANDROID_HOME : /home/user1/Android
```

**Summary**
During date selection, this specific scenario allows user to select dates past the maximum date set by option, and also allows selection of Non-existent dates like September 31.

Also occurs with allowing selection of dates before minimum dates.

**Steps to Reproduce**
```
npm i -g ionic@rc
ionic start myApp blank --type=angular
cd myApp
ionic serve --livereload
```
Paste the following code into within the `ion-content` tags of `src/app/pages/home/home.page.html`
```
  <ion-item>
    <ion-label>Date</ion-label>
    <ion-datetime></ion-datetime>
  </ion-item>
```
Save the file

Chose August 31, 2018.
Hit Done.
Open date picker again.
Without touching anything else, change month to September.
Date will show September 31. even though September only has 30 days. Allows save.

Other scenarios
There are multiple scenarios that lead to similar problems:

Scenario 1:

Select September 30.
Click done.
Open and change month to October.
October 31 does not show up as an option. In order to get it to show up, user must first cause some other change event on the date, like selecting October 29, and then October 31 will show as an option.

Scenario 2:

Set a min date in options in html. i.e. 6/15/2017.
Open datepicker. Select 7/1/2017.
Hit done.
Open datepicker. Change month to June. The 1 will remain so date will be 6/1. Hit done.
Datepicker allows June 1 to be saved.

**Related Code**
`<ion-datetime></ion-datetime>
`
**Expected Behavior**
Don't allow invalid dates to be entered.

**Additional Context**
This is an exact duplicate of #12070 which was closed without any investigation.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us. I am going to close this for now, but we will be re-evaluating the `ion-datetime` functionality and bugs soon during which we will take a closer look at this issue.

Thanks for using Ionic!

**Comment by Simpler1** [comment]
@liamdebeasi , Are you kidding me?
[#12070](https://github.com/ionic-team/ionic/issues/12070) was closed without any investigation.
Now this issue is closed without any investigation.
No wonder everyone is moving away from Ionic.  Issues are always just closed without any reasoning.
Ionic has become a joke.
I'm very disappointed.
