### ISSUE TITLE
v4: ion-item "button" directive not respecting "type" attribute for resulting button

### ISSUE THREAD

**Issue by TehCrucible** [ionic-team/ionic#14740]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.9 (C:\Users\jamie\AppData\Roaming\nvm\v8.9.1\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7
   @angular-devkit/core       : 0.7.0-rc.0
   @angular-devkit/schematics : 0.7.0-rc.0
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.9
   @ionic/schematics-angular  : 1.0.0-rc.9

System:

   NodeJS : v8.9.1 (C:\Program Files\nodejs\node.exe)
   npm    : 5.5.1
   OS     : Windows 10
```

**Describe the Bug**
Setting the attribute `type="submit"` on a button created with ion-item's `button` directive results in a button with type defaulting to "button" instead of the requested "submit".

**Steps to Reproduce**
Create a button inside a list with ion-item button and set type to submit. See related code.

**Related Code**
This results in a button type of "button":
```
<ion-item button type="submit">
    <ion-label>Submit</ion-label>
</ion-item>
```

**Expected Behavior**
I would expect this to behave as the ion-button component does, where this results in a button type of "submit" as expected:
```
<ion-button type="submit">
    Submit
</button>
```

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed in the next release.
