### ISSUE TITLE
Breaking change missing: attributes for ion-tabs

### ISSUE THREAD

**Issue by gydammin** [ionic-team/ionic#14745]
For your page, in ionic 3:
<ion-tabs [tabsPlacement]="tabsPlacement" [tabsLayout]="tabsLayout">
<ion-tabs>

In ionic 4:
<ion-tabs [tabbarPlacement]="tabsPlacement" [tabbarLayout]="tabsLayout">
<ion-tabs>

Cheers

**Comment by gydammin** [comment]
Btw, title changed for label therefore tabbarLayout should have possibly value `label-hide`and not `title-hide` ;)

**Comment by brandyscarney** [comment]
Thanks for the issue! I was actually just working on adding these. :smile:

**Comment by gydammin** [comment]
@brandyscarney thanks for updating.
Fyi, https://github.com/ionic-team/ionic/issues/14611 is not working at all despite following comments in tabs.d.ts, thanks for the hard work !
