### ISSUE TITLE
v4[@ionic/angular]: alhpa-9 migration guide?

### ISSUE THREAD

**Issue by gogo217** [ionic-team/ionic#14748]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

> After upgraded from **v4-alhpa.7** to **v4-alpha-9** app _routing_ is broken, as well as all _styles_ I customized not working(broken).

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```

"@angular/common": "6.0.7",
"@angular/core": "6.0.7",
"@angular/forms": "6.0.7",
"@angular/http": "6.0.7",
"@ionic/angular": "4.0.0-alpha.9",

...

"@angular-devkit/core": "0.7.0-rc.1",
"@angular-devkit/schematics": "0.7.0-rc.1",

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ionic (Ionic CLI)          : 4.0.0-rc.10 
Ionic Framework            : @ionic/angular 4.0.0-alpha.9
@angular-devkit/core       : 0.7.0-rc.1
@angular-devkit/schematics : 0.7.0-rc.1
@angular/cli               : 6.0.8
@ionic/ng-toolkit          : 1.0.0-rc.9
@ionic/schematics-angular  : 1.0.0-rc.9
```

**Comment by gogo217** [comment]
Since `alpha-8`, lazy-loading with `ion-tabs` has gone from  :(

**Comment by jgw96** [comment]
Hello! Thanks for using the alpha versions of v4! First, we are going to have a migration guide as part of the new docs. We are not sharing it publicly just yet, but its coming very soon. As far as routing, we have not seen any issues in our app, could you put together a simple repro case showing the specific routing issues?

**Comment by jgw96** [comment]
Oh and on lazy loading with tabs. `ion-tabs` has never worked (although its on our roadmap to make it work) with lazy loading yet due to an issue with the Angular router.

**Comment by gogo217** [comment]
I will create a simple repo with those two versions(`alpah-7` and `alpha-9`), and I am pretty sure it worked on `alpha-7`. Thanks.
