### ISSUE TITLE
v4: upgrade to alpha.8 seems to broken

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#14746]
**Describe the Bug**
Upgrading only @ionic/core to alpha.8 does not work as expected. We are running into this errors

```
ERROR in node_modules/@ionic/core/dist/types/components/gesture-controller/gesture-controller.d.ts(1,30): error TS2307: Cannot find module '@stencil/core'.
[ng] node_modules/@ionic/core/dist/types/components/menu/menu.d.ts(1,51): error TS2307: Cannot find module '@stencil/core'.
[ng] node_modules/@ionic/core/dist/types/components/nav/nav.d.ts(1,40): error TS2307: Cannot find module '@stencil/core'.
[ng] node_modules/@ionic/core/dist/types/components/toast/toast.d.ts(1,30): error TS2307: Cannot find module '@stencil/core'.
[ng] node_modules/@ionic/core/dist/types/utils/helpers.d.ts(1,30): error TS2307: Cannot find module '@stencil/core'.
[ng] node_modules/@ionic/core/dist/types/utils/input-interface.d.ts(1,30): error TS2307: Cannot find module '@stencil/core'.
[ng] node_modules/@ionic/core/dist/types/utils/overlays.d.ts(1,30): error TS2307: Cannot find module '@stencil/core'
```

Probably there is something missing? Can you also update your starter templates with latest requirements?

**Comment by brandyscarney** [comment]
Thanks for the issue! Alpha 8 is definitely broken. We don't recommend using it at this time. We're currently working on getting an alpha.9 out to fix these errors.

**Comment by MT--** [comment]
after adding `@stencil/core`, I am getting this error:
![image](https://user-images.githubusercontent.com/10172541/42524681-429d46b8-843f-11e8-9baa-51023d657f0f.png)

**Comment by brandyscarney** [comment]
We have released an `alpha.9` version that should be working much better. We're going to be releasing an `alpha.10` with some more fixes later today. Let me know if you still see these particular errors with `alpha.9` though! Thanks!

**Comment by MT--** [comment]
will the CLI pull the `alpha.9` when running `ionic start`? I know that is a separate repo, but just wondering if we should start a new app (and move files there since there were updates to other Ionic packages) or if simply updating will work?

**Comment by brandyscarney** [comment]
@MT-- Yes we have updated the starters to use `alpha.9`! If you ever want to compare your app to the current base you can find the starter here: https://github.com/ionic-team/starters/tree/master/angular/base

You _should_ be able to update the version number and import the new external css files and be good to go. If you are just using `@ionic/core` without angular it would be the following imports:

```
@import "~@ionic/core/css/normalize.css";
@import "~@ionic/core/css/structure.css";
@import "~@ionic/core/css/typography.css";
@import "~@ionic/core/css/colors.css";

@import "~@ionic/core/css/padding.css";
@import "~@ionic/core/css/float-elements.css";
@import "~@ionic/core/css/text-alignment.css";
@import "~@ionic/core/css/text-transformation.css";
@import "~@ionic/core/css/flex-utils.css";
```

and the `@ionic/angular` version will be the following, **but** we found that the css didn't get published for this package, so we're working to get a new release out with it published. 😓

```
@import "~@ionic/angular/css/normalize.css";
@import "~@ionic/angular/css/structure.css";
@import "~@ionic/angular/css/typography.css";
@import "~@ionic/angular/css/colors.css";

@import "~@ionic/angular/css/padding.css";
@import "~@ionic/angular/css/float-elements.css";
@import "~@ionic/angular/css/text-alignment.css";
@import "~@ionic/angular/css/text-transformation.css";
@import "~@ionic/angular/css/flex-utils.css";
```

In the meantime pointing to the `@ionic/core` for the css (my first code block) should work.

**Comment by MT--** [comment]
@brandyscarney Thank you (all) so much! I know what you're doing is not the most fun part of development, but I really appreciate it!

**Comment by jgw96** [comment]
Hello! Thanks for helping us test Ionic V4. I am closing this issue for now as it was fixed in the alpha.10 release. To update to alpha.10 you can run `npm install @ionic/angular@4.0.0-alpha.10 --save-exact`. Thanks!

**Comment by mburger81** [comment]
@brandyscarney @jgw96 Your starter imports the css files from the wrong repo, I created a PR for this issue https://github.com/ionic-team/starters/pull/320
