### ISSUE TITLE
4.0.0-alpha.8: item button misses cursor:pointer

### ISSUE THREAD

**Issue by ghybs** [ionic-team/ionic#14743]
# Bug Report

**Ionic Info**
Using @ionic/core version 4.0.0-alpha.8 directly from npm / unpkg CDN.
Chromium 66.0.3359.181 (64-bit) on Ubuntu 16.04

**Describe the Bug**
When mouse hovering an ion-list > ion-item button in Chromium, the mouse cursor no longer changes to `pointer`.
Works fine in Firefox 61.0 (64-bit), but the latter does not seem to use Shadow DOM.

**Steps to Reproduce**
1. Go to https://plnkr.co/edit/a6LpmDb5V7W24PYIhz71?p=preview **with Chrome / Chromium**
2. Move the mouse cursor over one of the `<ion-item button>` of the list (the 2 bottom ones), or open the menu and hover the 2 bottom menu items
3. The mouse cursor should change to `pointer` (a hand like over an hyperlink / the `<ion-buton>`), but it does not in Chrome.
4. Move the mouse over the first `<ion-item>` (it is not set as a `button`): the mouse cursor _does_ change to `pointer`, whereas it should not. (same in Firefox)

**Related Code**
- Version 4.0.0-alpha.8: https://plnkr.co/edit/a6LpmDb5V7W24PYIhz71?p=preview (does not work)
- Version 4.0.0-alpha.7: https://plnkr.co/edit/28VqOHDy2pN6S2TGYAs0?p=preview (works)

**Expected Behavior**
`<ion-item button>` should have the `cursor:pointer` CSS rule, i.e. change the mouse cursor to a pointer / hand when hovering it, like a normal `<ion-button>`.
On the contrary, simple `<ion-item>` (no `button` attribute) should not have this CSS rule.

**Additional Context**
None.

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed in the next alpha release.
