### ISSUE TITLE
Ionic v4 : ERROR in node_modules/@ionic/angular/dist/types/components/nav/view-controller.d.ts(1,56): error TS2307: Cannot find module '../../interface'.

### ISSUE THREAD

**Issue by filol** [ionic-team/ionic#14749]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.10 (/usr/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7
   @angular-devkit/core       : 0.7.0-rc.0
   @angular-devkit/schematics : 0.7.0-rc.0
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.9
   @ionic/schematics-angular  : 1.0.0-rc.9

System:

   NodeJS : v10.6.0 (/usr/bin/node)
   npm    : 6.1.0
   OS     : Linux 4.17

```

**Describe the Bug**
Using `ViewController`, ionic serve is totally broken: does not compile but does not display an error. Ionic buil indicates this error.

**Steps to Reproduce**
add `import { ViewController } from '@ionic/angular/dist/types/components/nav/view-controller';` in your code

**Related Code**
for example created a modal : 
```
@Component({
    templateUrl: 'modal.html',
})
export class Modal {
    myParam: string;

    constructor( public viewCtrl: ViewController ) {
    }

    dismiss() {
        this.viewCtrl.dismiss();
    }
}
```

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic v4! That import path is not correct. To import the `ViewController` class and most other Ionic classes you want to use this import path ```import { ViewController } from '@ionic/angular'; ```.
