### ISSUE TITLE
Viewport Fit issue on ios 10

### ISSUE THREAD

**Issue by dnyaneshwaruttarwar** [ionic-team/ionic#14750]
Hi Ionic Team,

I'm getting the issue for ios 10 device version

**viewport argument key "viewport-fit" not recognized and ignored.**

As app is perfectly running on ios 11

**Comment by Aman1324** [comment]
I am also getting this same issue in ios 10.
 **viewport argument key "viewport-fit" not recognized and ignored.** 
as app is working fine in ios 11.x

**Comment by llinq** [comment]
+1

**Comment by siphiwe** [comment]
Also getting the same issue on iOS 9.3.2. Got it working on another device though. I didn't note the version

**Comment by llinq** [comment]
For IOS 10.3+ it worked fine for me, I'm thinking that the problem is the SHADOW-DOM that IOS 10.2- does not understand.
