### ISSUE TITLE
v4 JS: menu stuck half way if swiping in + touch

### ISSUE THREAD

**Issue by ghybs** [ionic-team/ionic#14766]
# Bug Report

**Ionic Info**
Directly using @ionic/core version 4.0.0-alpha.10 from npm / unpkg CDN.
Chrome Mobile 67.0.3396.87 (Android 8.0.0)
Chrome desktop 67.0.3396.99 64-bit (Win10 with touchscreen)

**Describe the Bug**
While swiping in the menu to reveal it, if user makes a second touch on the menu, the latter becomes stuck at its current position (no longer moving with the swipe gesture). The backdrop does not respond to click / touch.
Therefore if the menu itself does not provide a mean to close it (e.g. through navigation...), we can no longer use the app. Only swiping in the end menu still works.

**Steps to Reproduce**
1. Go to https://beta.ionicframework.com/docs/content/api//menu-demo.html (currently uses version 4.0.0-alpha.10)
2. Use a finger to start a swipe gesture to open the start menu (i.e. touch down at the left edge of the app, then swipe rightwards slowly)
3. Using another finger, touch anywhere on menu while it is half open (looks like even touching the backdrop triggers the bug).
4. The menu becomes stuck, whether the first finger is released or not. Touching the backdrop overlay does not close the menu.

<img width="227" alt="screenshot_ionic_bug_menu_stuck" src="https://user-images.githubusercontent.com/12232803/42675106-9ad52274-8683-11e8-8259-2f04f6e7c1c4.png">

After injecting the alpha.10 CSS into the demo app:

<img width="226" alt="screenshot_ionic_bug_menu_stuck2" src="https://user-images.githubusercontent.com/12232803/42675118-a5f1d4a4-8683-11e8-9aef-047f7544c0d4.png">

Also happens with `"push"` and `"reveal"` types. But in those cases, since there is no backdrop overlay, it is still possible to access some parts of the app, but the behavior might not be totally as expected. E.g. in the case of the demo app, you can still press the "Set overlay" button. The menu closes, but the backdrop overlay appears and does not respond to touches... making the whole app stuck.

**Related Code**
Simple version on Plunker: https://next.plnkr.co/edit/y9Ri34xUkfvdOOwR?preview

**Expected Behavior**
- Touching the backdrop while menu is half open should either have no effect (i.e. user can continue swiping the menu), or cancel the swipe (i.e. closes the menu). Most probably the first would be better.
- Touching the menu while it is half open should either have no effect,trigger the touched element (e.g. if it is a button), or forcibly open the menu fully. And in all cases the menu should still be closable.

**Additional Context**
As first mentioned in https://github.com/ionic-team/ionic/issues/14722#issuecomment-404726970

**Comment by ghybs** [comment]
Same bug with end menu.

**Comment by paulstelzer** [comment]
Think this is fixed in beta.17. If not, just write here!
