### ISSUE TITLE
Alpha.10 Tab Styling Issue

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic#14764]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.11 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.10
   @angular-devkit/core       : 0.7.0-rc.1
   @angular-devkit/schematics : 0.7.0-rc.1
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.10
   @ionic/schematics-angular  : 1.0.0-rc.10

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.4

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v9.8.0 (/usr/local/Cellar/node/9.8.0/bin/node)
   npm               : 6.1.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/kensodemann/Library/Android/sdk/
```

**Describe the Bug**
A community member asks me:

i m struggling with the new shadow dom by default
for example, im trying to change the ion-tabs styles
so i did :

```
ion-tabs {
  --ion-tabbar-background-color: cssvar(light);
}
```

which works, but when i try to change the ion-tab-button

```
ion-tab-button {
  --color-selected: var(--success);
  --ion-color-contrast: var(--grey);
}
```

it s not beeing applyed
(ion-tab-button are part of the shadow dom of the ion-tabs)

I performed a similar attempt in a basic tab starter:

```
ion-tabs {
  --ion-tabbar-background-color: var(--ion-color-dark);
}

ion-tab-button {
  --ion-tabbar-text-color-active: #ff0000
}
```

My result was the same (background ended up dark, but the active button was still blue rather than red.

**Steps to Reproduce**
1. Generate a tabs starter
1. add the second set of styling above to the tabs page scss
1. note that the tab bar turns black as expected but the selected icon does not turn red.

**Comment by kensodemann** [comment]
When this one gets fixed, please provide a link to the commit. The person who reported it to me is having a similar issue with some of their own components and would like some guidance.

**Comment by kensodemann** [comment]
@camwiegert - created a repo to duplicate. This may come down to just me and the person I am working with trying to accomplish this the wrong way.

https://github.com/kensodemann/test-tab-styling

See the `tabs.page.scss` file.

Let me know if this is the proper way to style the tabbar or not. Feel free to point to some docs if they exist as well and I will pass the info along.

**Comment by camwiegert** [comment]
Thanks @kensodemann - I'm looking into it this morning. Should have more info soon.

**Comment by kensodemann** [comment]
Here is the CSS that solves the issue for the OP:

```css
ion-tabs {
  --ion-tabbar-background-color: var(--ion-color-dark);
  --ion-tabbar-text-color: #fff;
  --ion-tabbar-text-color-active: #ff0000
}
```

**Comment by brandyscarney** [comment]
This should be fixed by the updates to the tabs API in this PR: https://github.com/ionic-team/ionic/pull/16048

Just need to confirm this.

**Comment by brandyscarney** [comment]
Please let the user know that [these](https://beta.ionicframework.com/docs/theming/advanced#application-colors) are the updated tab globals which can be set on the root:

<img width="669" alt="screen shot 2018-11-02 at 10 57 45 am" src="https://user-images.githubusercontent.com/6577830/47922744-273f9200-de8e-11e8-88d6-b26e68b746c4.png">

The individual tab buttons can also be styled using the tab button component variables like:

```
ion-tab-button {
  --background: var(--ion-color-dark);
  --color: #fff;
  --color-selected: #ff0000
}
``` 

Let me know if there are any questions or concerns, thanks!
