### ISSUE TITLE
v4 JS: click outside menu should close it (Edge)

### ISSUE THREAD

**Issue by ghybs** [ionic-team/ionic#14767]
# Bug Report

**Ionic Info**
Using @ionic/core version 4.0.0-alpha.10 directly from npm / unpkg CDN.
Firefox 61.0.1 (64 bits) on Win10 and on Ubuntu 16.04

**Describe the Bug**
When the menu is open, user can normally close it by clicking on the backdrop overlay (MD mode / overlay type) / main app content that remains visible (iOS mode / push and reveal types).
But since version alpha.8, this does not work in Firefox. Works fine in Chrome.

**Steps to Reproduce**
1. Go to https://beta.ionicframework.com/docs/api/menu **with Firefox**
2. Open the start menu by any mean (toggle button, swipe gesture...)
3. Click / touch the remaining main content (iOS mode) or backdrop overlay (MD mode) to try to close the menu
4. Menu does not close.

Direct link to demo app:
https://beta.ionicframework.com/docs/content/api//menu-demo.html?ionic:mode=md&ionic:statusbarPadding=true

This was working fine in alpha.7:
https://beta.ionicframework.com/docs/api/4.0.0-alpha.7/menu

**Related Code**
On Plunker: https://plnkr.co/edit/N662lbHFigjx3XS8gsjT?p=preview
(for some reason Plunker crashes on my Firefox 61, possibly due to trying its new "next" version).

**Expected Behavior**
When clicking / touching anywhere outside the menu (i.e. the backdrop overlay, or the remaining main content), the menu should close.

**Additional Context**
As first mentioned in https://github.com/ionic-team/ionic/issues/14701#issuecomment-404721569

**Comment by paulstelzer** [comment]
Can confirm - It's working on Chrome, but not on Firefox (this is an issue in beta.0, too) @brandyscarney

**Comment by paulstelzer** [comment]
Still not working in Edge

**Comment by codybeebework** [comment]
Should a new issue be created for this?  Changing the title would work just as well.

It took me a while to find out if this was already reported for Edge.  I didn't want to make a duplicate issue.  I'm glad you all are already aware of the problem!

**Comment by damsorian** [comment]
Any workaround for this?
