### ISSUE TITLE
4.0.0-rc.9: Typescript error using willAnimate property of ModalOptions when creating modal. 

### ISSUE THREAD

**Issue by TehCrucible** [ionic-team/ionic#14775]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.9 (C:\Users\jamie\AppData\Roaming\nvm\v8.9.1\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.9
   @angular-devkit/core       : 0.7.0-rc.1
   @angular-devkit/schematics : 0.7.0-rc.1
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.9
   @ionic/schematics-angular  : 1.0.0-rc.9

System:

   NodeJS : v8.9.1 (C:\Program Files\nodejs\node.exe)
   npm    : 5.5.1
   OS     : Windows 10
```

**Describe the Bug**
When creating a modal using ModalController, the property `willAnimate` does not appear to be part of the interface causing editors to flag an error:

```
Object literal may only specify known properties, and 'willAnimate' does not exist in type 'ModalOptions'.
```

Project then won't compile.

**Steps to Reproduce**

Create a modal using ModalController and specify the `willAnimate` property in the options using a TypeScript aware editor.

**Related Code**
```
    const modal = await this.modalCtrl.create({
      component: ModalComponent,
      willAnimate: false,
    });
```

**Comment by TehCrucible** [comment]
The `ModalOptions` interface is declared at `@ionic\core\dist\types\components\modal\modal-interface.d.ts` and clearly doesn't have the `willAnimate` property in it.

Adding the line `willAnimate?: boolean;` to the interface allows me to compile and the functionality appears to work as expected. Is this property being phased out or phased in?

```
export interface ModalOptions {
    component: ComponentRef;
    componentProps?: ComponentProps;
    showBackdrop?: boolean;
    enableBackdropDismiss?: boolean;
    enterAnimation?: AnimationBuilder;
    leaveAnimation?: AnimationBuilder;
    cssClass?: string | string[];
    delegate?: FrameworkDelegate;
}
```

**Comment by goelectricstations** [comment]
same issue
