### ISSUE TITLE
v4: menuController enable method not working in lifecycle events

### ISSUE THREAD

**Issue by matthew-valenti** [ionic-team/ionic#14779]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.11 (C:\Users\matth\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.9
   @angular-devkit/core       : 0.7.0-rc.1
   @angular-devkit/schematics : 0.7.0-rc.1
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.10
   @ionic/schematics-angular  : 1.0.0-rc.10

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

**Describe the Bug**
To hide the side menu on a page it should be possible to add this.menuController.enable(false) to a lifecycle event (e.g. 
 ionViewWillEnter, ionViewDidEnter).

**Steps to Reproduce**
1. Create a sidemenu starter app.
2. Create a test page.
3. Add the code below to the test page.
4. Navigate to the test page, side menu is still visible.

**Related Code**
```
import { MenuController } from '@ionic/angular';

constructor(
    public menuController: MenuController,
) { }

ionViewDidLoad() {
    this.menuController.enable(false);
}
```

**Expected Behavior**
Side menu is not visible.

**Comment by cleversolutions** [comment]
@matthew-valenti try ionViewDidEnter. It seems that the MenuController is unable to find menus in events earlier in the lifecycle.

**Comment by matthew-valenti** [comment]
Using ionViewDidEnter on the latest Ionic version seems to be working well. Thanks!

```
ionViewDidEnter() {
    this.menuController.enable(false);
}
```
