### ISSUE TITLE
Native APIs not working in ionic4/Angular

### ISSUE THREAD

**Issue by Alex1000A** [ionic-team/ionic#14781]
# Bug Report

**Ionic Info**

ionic (Ionic CLI)          : 4.0.0-rc.11 (C:\Users\alex.auyong\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.9
   @angular-devkit/core       : 0.7.0-rc.1
   @angular-devkit/schematics : 0.7.0-rc.1
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.10
   @ionic/schematics-angular  : 1.0.0-rc.10

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0

System:

   NodeJS : v8.11.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.2.0
   OS     : Windows 10

Environment:

   ANDROID_HOME : C:\Users\alex.auyong\Tools\androidSDK;

**Describe the Bug**
I'm getting a unexpected error when I try to use the Native Plugin
(1-GooglePlus)
(2-BarcodeScanner)

**Steps to Reproduce**
1-Create template by CLI
2-Install the plugin from https://beta.ionicframework.com/docs/native/barcode-scanner
4-Add dependancy injection to the constructor
3-Lanuch on device:ionic cordova run android -l 

**Related Code**
![error](https://user-images.githubusercontent.com/27215710/42746491-df7e8a40-888c-11e8-8a20-407e0155867e.PNG)
Github:https://github.com/Alex1000A/ionic_Alpha

**Expected Behavior**
The App should launch properly

**Comment by mhartington** [comment]
Hi there! So a few things that are needed.

- Update Ionic native to V5 beta

```shell
npm i @ionic-native/barcode-scanner@beta --save
npm i @ionic-native/core@beta --save
```

- Update the imports to the newer paths.

```
import { BarcodeScanner } from "@ionic-native/barcode-scanner";
```

Becomes 

```
import { BarcodeScanner } from "@ionic-native/barcode-scanner/ngx";
```

This should resolve the issue. 
With V4 of the framework, we've upgraded to RXJS V6. So Ionic-Native needed a new release to account for that as well.

**Comment by goelectricstations** [comment]
@mhartington 

Hi, I had the same issue with;
import { Geolocation } from '@ionic-native/geolocation/ngx';

even after add "/ngx" I get module not found.

Please, help
