### ISSUE TITLE
Tab badge doesn't dynamically update update until tapped

### ISSUE THREAD

**Issue by corysmc** [ionic-team/ionic#14783]
# Bug Report

**Ionic Info**

```
4.0.0-alpha.10
```

**Describe the Bug**
When dynamically setting `ion-tab`'s `badge` = new badge value isn't  rendered until you tap on it.

**Steps to Reproduce**
1. Create ion-tabs layout
2. Set badge value some time after the page renders (via api call, or setTimeout)
3. See that the badge doesn't update

**Related Code**
https://codepen.io/corysmc/pen/NzzXMW

**Expected Behavior**
Badge re-renders anytime it's value is updated

**Additional Context**

**Comment by brandyscarney** [comment]
Thanks! This should be fixed on the next release with this commit, but I need to confirm: https://github.com/ionic-team/ionic/commit/00c4c775426d5bd1376359963baac67d215be511

**Comment by brandyscarney** [comment]
I confirmed that the tab badge count updates in latest, but the badge color is not updating. cc @manucorporat
