### ISSUE TITLE
[Ionic v4] content.clearScrollPaddingFocusOut is missing

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#14793]
**Ionic Info**

v4.0.0-alpha.9

**Support Question**

In v3 I used `content.scrollTo` and `content.clearScrollPaddingFocusOut` to scroll the page when the keyboard is opened and closed in order to avoid to display the fields the user is filling behind the keyboard

I didn't found them in v4. Did I miss something or are they still on the roadmap?

**Code**

     import {Content} from '@ionic/angular';
      
     @Input() content: Content;
      
      private addContentPadding = (event: any) => {
          this.content.scrollTo(0, myValue);
      }
      
      private removeContentPadding = () => {
        this.content.clearScrollPaddingFocusOut();
    }

**Update beta.3**

`scrollTo` respectively `scrollToPoint` has been reinjected

`clearScrollPaddingFocusOut` is still missing

**Comment by kael** [comment]
https://github.com/ionic-team/ionic/tree/master/core/src/components/scroll

**Comment by eiriko2303** [comment]
You can use getScrollElement() on this.content and then call scrollToTop(duration).

`this.content.getScrollElement().scrollToTop(duration)`

**Comment by peterpeterparker** [comment]
I the end I didn't needed (I guess) this and since the issue is old I would say, let's close it.
