### ISSUE TITLE
V4: Export Gesture/Gesture-Controller components to Angular

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic#14791]

**Comment by ArezooK** [comment]
I also see this issue when upgrading to v4: ..node_modules/@ionic/angular/dist/index has no exported member Gesture

**Comment by manucorporat** [comment]
Gesture/Gesture-Controller will not be exported yet, a lot design work needs to be done to expose a public API for gestures. In the meantime, hammerjs can be added to your angular application:
https://blog.angularindepth.com/gestures-in-an-angular-application-dde71804c0d0
