### ISSUE TITLE
[Ionic 4] error TS2339: Property 'width' does not exist on type 'HTMLIonMenuElement'.

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#14794]
**Ionic Info**

v4.0.0-alpha.9

**Support Question**

In v3 `Menu` use to expose a `width()` method. Didn't found it in v4. Did I miss something or are they still on the roadmap?

**Code**

     const menu: HTMLIonMenuElement = await this.menuController.get('myMenu');
     menu.width();

**Comment by peterpeterparker** [comment]
In v4.0.0-alpha.12 `getWidth` is there, could confirm it compiles

I'm not there to test it but looks good

Side note:

In Ionic v3 method's name is `width()` and in v4 `getWidth()` just in case someone would land on that in the future

**Comment by brandyscarney** [comment]
@manucorporat Can we document the breaking change for the method name?

**Comment by peterpeterparker** [comment]
Ok so I just tested, I probably did something wrong, but I was unable to get the width of the menu thru this exposed function, I always get `undefined` 

But I found I guess a workaround

    const menu: HTMLIonMenuElement = await this.menuController.get('myMenu');
    console.log(menu.getWidth()); // --> undefined
    console.log(menu.clientWidth); // --> the width of the menu
