### ISSUE TITLE
[Ionic v4] padding-left and padding-right not allowed on divs

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#14798]
# Bug Report

**Ionic Info**
@ionic/angular: "4.0.0-alpha.11"

**Describe the Bug**
Attributes padding-left and padding-right aren't allowed on divs. For example margin, margin-left or padding are ok, but not padding-left and padding-right

**Related Code**
    
     <div padding-left padding-right>
         no padding
     </div>

**Expected Behavior**
Being able to use padding-left and padding-right on divs too

**Comment by brandyscarney** [comment]
Thanks for the issue! We changed the `padding-*` attributes to use `start` and `end` instead of `left` and `right`, respectively.

However, I do think this causes some inconsistencies with the way `margin` works and I'd like them to all behave the same. cc @manucorporat @camwiegert 

https://github.com/ionic-team/ionic/blob/master/core/src/css/padding.scss

**Comment by peterpeterparker** [comment]
@brandyscarney thx for the feedback. furthermore than the inconsistencies, may I ask, is that documented somewhere? maybe I missed that info but I didn't saw it listed in the breaking changes list

**Comment by brandyscarney** [comment]
@peterpeterparker No it hasn't been documented. It's been on my list of things to look at. I didn't want to document it because I'm considering adding it back in. We need to have some internal discussion around those attributes. 🙂

**Comment by peterpeterparker** [comment]
@brandyscarney thx for the extra information 👍  good good, then for the moment I just gonna ignore the margin/padding errors I may see 😉

**Comment by manucorporat** [comment]
I think we should remove `[margin-left]` and `[margin-right]`, supporting both now that we have CSS variables in place would add too much complexity for little (or inexistent) win.

**Comment by peterpeterparker** [comment]
Perfect, tested, I could confirm the fix in v4.0.0-alpha.12, thx 👍

Also thx for adding a note about it in the breaking changes list 👍
