### ISSUE TITLE
[Ionic v4, support] Use css preprocessor variables as css4 variables value

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#14801]
# Support Question

First of all, plz excuse me for asking this support question here, I just thought, since it's related to the migration from v3 to v4, that it might be more relevant first to ask that here than on Stackoverflow (maybe someone later may face the same question during the migration)

**Ionic Info**
@ionic/angular: "4.0.0-alpha.11"

**Describe the question**

My goal is to style one particular button most precisely a "Facebook login" button which should be displayed with the Facebook's official background color. In order to do this, I set a `class` to the button and style it like the following

     ion-button.facebook.button {
         --background: #3b5998;
     }

Cool that works fine

But, purpose of my question, I would rather like not have to explicitly set the color code but rather like to use a variable. I tried the following

     ion-button.facebook.button {
         --background: $my-facebook-color;
     }

but it doesn't work, the `$my-facebook-color` isn't interpreted respectively preprocessed and therefore the color won't be applied. I also tried something like

     ion-button.facebook.button {
         --background: --my-facebook-color;
     }

That didn't worked neither

Is there any way to set a variables and to reuse them in order to set the value of css4 variables?

Thx in advance for the help

**Comment by kensodemann** [comment]
I _should_ close and lock this, but I may have a simple answer, so I will wait until after I hear back from you.

RE: your latter try using the custom property, did you try using `var()` as per here? https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

```
 ion-button.facebook.button {
     --background: var(--my-facebook-color);
 }
```

For the sass example you may need to try using interpolation:

```
 ion-button.facebook.button {
     --background: #{$my-facebook-color};
 }
```

I am not really all that familiar with that, so not entirely sure.

I suggest using the custom properties and minimizing (or eliminating) the use of sass.

Let me know if either of those worked.

**Comment by peterpeterparker** [comment]
@kensodemann wow both solutions just work like a charm 👍 

I feel a bit dumb, really tried x solutions and hours before effectively deciding to disturb you. thx a lot for the quick answer 😃

**Comment by kensodemann** [comment]
Excellent, glad to hear it!!
