### ISSUE TITLE
v4: Platform.is not detecting core when run inside browser

### ISSUE THREAD

**Issue by marcelgoya** [ionic-team/ionic#14802]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.11 (/usr/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.11
   @angular-devkit/core       : 0.7.0-rc.2
   @angular-devkit/schematics : 0.7.0-rc.2
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.11
   @ionic/schematics-angular  : 1.0.0-rc.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.0 ios 4.5.4

System:

   NodeJS : v9.11.2 (/usr/bin/node)
   npm    : 6.2.0
   OS     : Linux 4.4

Environment:

   ANDROID_HOME : not set
```

Hi folks, I'm currently migrating my codebase to v4 and noticed that when I run ionic serve inside Google Chrome, that platform.platforms returns Android instead of Core. I had a look at the show-hide-when-utils source file and noticed that core is not inside the PLATFORM_CONFIGS array. 

My question, is core detection still supported and simply missing or do you plan to remove it completely?

Thanks in advance,

Marcel

**Comment by thruthesky** [comment]
I see something wrong in https://github.com/ionic-team/ionic/blob/master/core/src/utils/platform.ts
The code inside platform.ts is not right.

**Comment by brandyscarney** [comment]
Thank you for the issue! I am going to close this issue and merge it into #15165 to keep all platform issues in one.
