### ISSUE TITLE
ion-toggle collide with toast closing button

### ISSUE THREAD

**Issue by wrebisz** [ionic-team/ionic#14814]
# Bug Report

**Ionic Info**
```
cli packages: (.../node_modules)

    @ionic/cli-plugin-proxy : 1.5.5
    @ionic/cli-utils        : 1.19.0
    ionic (Ionic CLI)       : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : ios 4.5.3
    Ionic Framework    : ionic-angular 3.8.0

System:

    ios-deploy : 1.9.2
    Node       : v8.9.2
    npm        : 6.1.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4.1 Build version 9F2000

Environment Variables:

    ANDROID_HOME     : not set
    HTTP_PROXY       : not set
    http_proxy       : not set
    HTTPS_PROXY      : not set
    https_proxy      : not set
    IONIC_HTTP_PROXY : not set
    PROXY            : not set
    proxy            : not set

Misc:

    backend : pro
```

**Describe the Bug**
ion-toggle collides with the toast closing button. When close button is pressed it also change value of the toggle. 
**Problem is related to iOS devices.** 

**Steps to Reproduce**
1. Top toast is on the screen and covers ion-toggle item (ion-toggle switch have to be just behind toast closing button)
2. User click on toast closing button;
3. Toast closes + ion-toggle item toggle its value;

**Related Code**
https://stackblitz.com/edit/ionic-x6x5xh

**Expected Behavior**
When closing toast **on iOS device**, toggle item shoud stay not change its value.

**Additional Context**
Works fine in desktop browsers & android devices.

**Comment by paulstelzer** [comment]
Is this issue still exist in beta.17?

**Comment by wrebisz** [comment]
It seems so, that it still exist. Problem is related to ionic on ios - not to application.
It can be fixed by work around. Its related with quite big effort or some user interface redesing.
Possible solutions: 
- Discover when toast is presented and block other actions than close it (a lot of work and complicated... so potentially can bring some new issues)
- Redesign of the user interface, so toasts will always appear in safe area, that do not contain any active elements.

**Comment by wrebisz** [comment]
Veryfied- problem can not be reproduced any more. Seems that it doesnt exist.
