### ISSUE TITLE
[Ionic v4] Attribut no-margin doesn't set --margin variables to zero

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#14826]
**Ionic Info**
@ionic/angular: "4.0.0-alpha.11"

**Describe the Bug**
Using the attributes `no-margin` on an element doesn't set the css4 variables `--margin` zero

**Steps to Reproduce**
For example:

     <ion-button no-margin no-padding>Something</ion-button>

no-margin will be generate as

     ion-app [no-margin] {
        margin: 0;
     }

where no-padding will be correctly generated as

    [no-padding] {
       padding: 0;
       --padding-start: 0;
       --padding-end: 0;
       --padding-top: 0;
       --padding-bottom: 0;       
    }

**Expected output**

     ion-app [no-margin] {
        margin: 0;
       --margin-start: 0;
       --margin-end: 0;
       --margin-top: 0;
       --margin-bottom: 0;  
     }

**Comment by peterpeterparker** [comment]
@brandyscarney same as https://github.com/ionic-team/ionic/issues/14798?

if yes, should I then close this issue?

**Comment by brandyscarney** [comment]
@peterpeterparker Thanks 🙂 They're related and hopefully we'll solve them both at once but I'll leave this open to make sure it gets fixed.

**Comment by peterpeterparker** [comment]
@brandyscarney excellent, thx for the feedback

**Comment by peterpeterparker** [comment]
Tested, I could confirm the fix in v4.0.0-alpha.12, thx 👍
