### ISSUE TITLE
v4: new components are created with the css file instead scss

### ISSUE THREAD

**Issue by vadost** [ionic-team/ionic#14820]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.11 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.11
   @angular-devkit/core       : 0.7.0-rc.2
   @angular-devkit/schematics : 0.7.0-rc.2
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.11
   @ionic/schematics-angular  : 1.0.0-rc.11

System:

   NodeJS : v8.11.1 (/usr/local/bin/node)
   npm    : 5.6.0
   OS     : macOS High Sierra

```

**Describe the Bug**
New components are created with the css file instead scss

**Steps to Reproduce**
1. Run ionic g component components/login-form --change-detection=OnPush

```
> ng generate component components/login-form --change-detection=OnPush
CREATE src/app/components/login-form/login-form.component.css (0 bytes)
CREATE src/app/components/login-form/login-form.component.html (29 bytes)
CREATE src/app/components/login-form/login-form.component.spec.ts (650 bytes)
CREATE src/app/components/login-form/login-form.component.ts (360 bytes)
UPDATE src/app/components/components.module.ts (310 bytes)
[OK] Generated component!
```

**Comment by peterennis** [comment]
Have a look here:
fix(css): use default css if sass plugin not installed
https://github.com/ionic-team/stencil/commit/a61dc3bc0644dc2d8332a1447ce97b53fd28b8be

**Comment by dwieeb** [comment]
@vadost Thank you for the issue!

Existing apps will need to have their `angular.json` configured like the starters now are: https://github.com/ionic-team/starters/commit/eccef0dc5d3e16a9e6f43d28f9c07fba7779d178

Angular defaults to `.css` unless configured otherwise. See https://github.com/ionic-team/ionic-cli/issues/3312 for more details.
