### ISSUE TITLE
ion-icon is randomly empty

### ISSUE THREAD

**Issue by M00dl3** [ionic-team/ionic#14848]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.11 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.11
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.11
   @ionic/schematics-angular  : 1.0.0-rc.11

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.1
   @capacitor/core           : 1.0.0-beta.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   NodeJS            : v9.11.1 (/usr/local/Cellar/node/9.11.1/bin/node)
   npm               : 5.8.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**

Sometimes ion-icons stop showing (but if used inside button, button keeps working), inspection shows that the missing icons have a empty .icon-inner Behaviour is random, can't seem to find a clear cause.

App is build around the ionic starte with sidemenu

**Steps to Reproduce**
1. Generate ionic starter with sidemenu
2. `ionic capacitor add android` 
3. `ionic build`
4. `ionic capacitor copy android`
5. Generate APK with Android studio
6. Install APK on Android

**Expected Behavior**
I expect icons to show up all the time.

**Additional Context**
Below is a screenrecording of the app running on my Android device:
![screenrecording](https://user-images.githubusercontent.com/31840781/43127438-c06a83b2-8f2f-11e8-8d91-c93df51077fe.gif)

**Comment by brandyscarney** [comment]
Are you still seeing this on latest? `4.0.0-beta.13`

**Comment by M00dl3** [comment]
> Are you still seeing this on latest? `4.0.0-beta.13`

Sorry for the extremely late response, just tested it and can confirm that I no longer can reproduce this bug.
