### ISSUE TITLE
Ion-datetime can not add a display unit per column after opening, for example: [yearValues]=[2020+'year'] or pickerFormat="MM month YYYY day", my suggestion is to be able to add units by yourself. The display adaptation allows the user to decide on their own.

### ISSUE THREAD

**Issue by xumingyi** [ionic-team/ionic#14844]
# Feature Request

**Ionic Info**
PS C:\11_IONIC_WS\app-user> ionic info

cli packages: (C:\Users\FTD_2014\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.12.0
    npm               : 3.10.10
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\FTD_2014\AppData\Local\Android\Sdk

Misc:

    backend : pro

PS C:\11_IONIC_WS\app-user>
PS C:\11_IONIC_WS\app-user>
PS C:\11_IONIC_WS\app-user>
PS C:\11_IONIC_WS\app-user> ionic info

cli packages: (C:\Users\FTD_2014\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.12.0
    npm               : 3.10.10
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\FTD_2014\AppData\Local\Android\Sdk

Misc:

    backend : pro

```
insert the output from ionic info here
```

i hope Support effect, example：
![614488457524677973](https://user-images.githubusercontent.com/14070569/43116868-7679c120-8f3c-11e8-93a6-fef2a0ade3fc.jpg)

**Comment by xumingyi** [comment]
nobody answered how to solve it?

**Comment by jorge13300** [comment]
________________________________
De: FTD_2014 <notifications@github.com>
Enviado: martes, 24 de julio de 2018 10:36 p. m.
Para: ionic-team/ionic
CC: Subscribed
Asunto: Re: [ionic-team/ionic] Ion-datetime can not add a display unit per column after opening, for example: [yearValues]=[2020+'year'] or pickerFormat="MM month YYYY day", my suggestion is to be able to add units by yourself. The display adaptation allows th...


nobody answered how to solve it?

**Comment by xumingyi** [comment]
What do you mean?  I want to know if you have any plans to improve datetime?

**Comment by xumingyi** [comment]
update to ionic4 can resolve this program ?
