### ISSUE TITLE
Testing Ionic 4 - ion background color only set in part of the component

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic#14845]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
C:\ae\adaept.com\ae-svg-components>ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   ionic (Ionic CLI) : 4.0.0-rc.11

System:

   NodeJS : v8.11.1
   npm    : 6.2.0
   OS     : Windows 10


C:\ae\adaept.com\ae-svg-components>
```

**Describe the Bug**
--ion-background-color only sets part of the component

**Steps to Reproduce**
![capture351](https://user-images.githubusercontent.com/140737/43117634-b0866e1a-8ec2-11e8-8233-d8261d481b56.png)
![capture350](https://user-images.githubusercontent.com/140737/43117635-b5250940-8ec2-11e8-8a67-48b64baf3d58.png)

**Related Code**
https://github.com/peterennis/ae-svg-components/commit/c368704e81b74318ee16353bda212a7cc85cdd55
https://aesvg.adaept.com/

**Expected Behavior**
I expect the component background to be set.
Only part of it is set.
I do not know what really should happen.

**Additional Context**

**Comment by peterennis** [comment]
this commit:
https://github.com/peterennis/ae-svg-components/commit/3e881ed19eed71ca8b5cf25b943aac11a54b1dca

test() add ion background color to ae-spinner-component

It has no effect in the component.
I really do not know what is going on!

**Comment by paulstelzer** [comment]
Think this is fixed in beta.17. If not, just write here!
