### ISSUE TITLE
[Ionic v4] ion-slides missing event ionSlideTap

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#14859]
**Ionic Info**
@ionic/angular: "4.0.0-alpha.12"

**Describe the Feature Request**
As in Ionic v3, `ion-slides` should provide the event `ionSlideTap`

**Describe Alternatives**
If this won't be implemented, a breaking change alternative should be provided

**Related Code**
https://github.com/ionic-team/ionic/blob/a7f1f4daa7166281f0735552b122d4c827cd20f1/core/src/components/slides/readme.md

**Comment by adamlacombe** [comment]
I also noticed this. I've been working on a fix and will submit a pull request. It looks like the Swiper version was updated and some of the options have been renamed.

**Comment by krngd2** [comment]
you can use  ` (click) ` event

**Comment by peterpeterparker** [comment]
@krngd2 thx that might be an alternative but @adamlacombe provided a PR which solves it, gonna wait for that first

**Comment by peterpeterparker** [comment]
I just did forget to close this issue. Don't remember if it was solved in beta.1 or beta.2, but the PR of @adamlacombe totally solves it, `ionSlideTap` is back in v4
