### ISSUE TITLE
Bug with light segment in primary toolbar

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic#14854]
# Bug Report

There is an issue with the active segment button color where it is black on a light segment in a primary toolbar:

```
<ion-toolbar color="primary">
  <ion-segment color="light">
    <ion-segment-button value="sunny">
      Sunny
    </ion-segment-button>
    <ion-segment-button value="rainy" checked>
      Rainy
    </ion-segment-button>
  </ion-segment>
</ion-toolbar>
```

![localhost_3333_src_components_segment_test_basic iphone 6_7_8](https://user-images.githubusercontent.com/6577830/43165876-03fe602a-8f63-11e8-95be-69ad672ae649.png)

**Comment by dtaalbers** [comment]
I think I am having the same issue with the searchbar.

At first glance its fine. This is the route `Tabs > Browse`

![screen shot 2018-08-16 at 11 13 20](https://user-images.githubusercontent.com/6512556/44199845-7a366280-a145-11e8-9cca-314de785cc54.png)

When I navigate to `Tabs > Browse > Categories` and then back to `Tabs > Browse` it shows like this

![screen shot 2018-08-16 at 11 12 45](https://user-images.githubusercontent.com/6512556/44199859-84586100-a145-11e8-862a-7e3e3db6490c.png)

Btw the searchbar on the `Categories` page is also black after nagivating `Tabs > Browse > Categories`. It has the same HTML as the `Browse` page. See below

My header on the `Browse` and `Categories` pages.

```
<ion-header>
    <ion-toolbar color="primary" no-border-bottom>
        <ion-title>Bladeren</ion-title>
        <ion-buttons slot="right">
            <ion-spinner class="spinner" *ngIf="is_loading"></ion-spinner>
        </ion-buttons>
    </ion-toolbar>
    <ion-searchbar [(ngModel)]="q" [showCancelButton]="true" (ionChange)="search()" (ionClear)="cancel_search()" (ionCancel)="cancel_search()" debounce="850" placeholder="Zoek naar een product" cancelButtonText="Annuleren" animated="true">
    </ion-searchbar>
</ion-header>
```

I navigate with this:
```
this.nav_controller.goForward(`/tabs/(browse:categories)?id=${group.id}&parent='Bladeren'`);
```

Not sure if my issue is related to this one, but it seems so. If it is not related should I create a separate issue for this?

**Comment by dtaalbers** [comment]
Work around:

```
ion-header {
  background: var(--ion-color-white) !important;

  ion-searchbar {
      --background: var(--ion-color-light-gray);
  }
}

```

**Comment by camwiegert** [comment]
@brandyscarney I think this is actually related to how we're applying the toolbar colors to segment children without a `color` attribute. I have a fix I'll push shortly.

**Comment by brandyscarney** [comment]
@camwiegert Sorry, I was specifically talking about his issue with the black background on toolbars. I don't think that one is related to this issue, and the issue I linked to is what Manu is working on. 🙂
