### ISSUE TITLE
ion-input focus event fires for two when clicking on one

### ISSUE THREAD

**Issue by swvcc** [ionic-team/ionic#14851]
# Bug Report

**Ionic Info**
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

local packages:

    @ionic/app-scripts : 3.1.11
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.6.0 
    OS   : macOS High Sierra

Misc:

    backend : pro

**Describe the Bug**
Sometimes when tapping a field with a focus event handler, two fields' handlers are triggered at once. 

**Steps to Reproduce**
You may have to try this demo for a few minutes to get it to work. Tap one text field and then the other while watching the debug console. I recommend clicking away from the fields and then back to get the effect. At some point, you will see it display a console.log() for both fields when you've only clicked one. 
Try this demo locally, not on a stackblitz. it won't work in stackblitz for some reason.

**Related Code**
https://www.dropbox.com/s/5i38tg4ai0iz9hi/src.zip?dl=0

**Expected Behavior**
focus event should fire one time on the input box clicked.

**Additional Context**

**Comment by paulstelzer** [comment]
Think this is fixed in beta.17. If not, just write here!
