### ISSUE TITLE
Testing Ionic 4 - Standard color names are not recognized

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic#14857]
# Bug Report / Feature Request ???

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
4.0.0-alpha.11
```

**Describe the Bug**
Using a standard color name does not work for a component

**Steps to Reproduce**
![capture299](https://user-images.githubusercontent.com/140737/43161910-4df0a064-8f3e-11e8-8192-387b0f155778.png)

**Related Code**
https://github.com/peterennis/ae-svg-components/blob/master/src/index.html#L34-L37

**Expected Behavior**
Use known names (preferred) or hex codes
Ref: https://en.wikipedia.org/wiki/Web_colors

**Additional Context**
This commit refers to "The color to use from your application's color palette."
https://github.com/ionic-team/ionic/commit/b4976dd914e47c78a743a640f1221836498c2153

I would like to use named colors in my component.
It may be necessary to extend Ionic theming.
Where is a good place to start?

**Comment by brandyscarney** [comment]
You can add new colors by creating classes that define them, for example with `yellow` it would be:

```
.ion-color-yellow {
  --ion-color-base: #ffff00;
  --ion-color-rgb: 255,255,0;
  --ion-color-contrast: #000000;
  --ion-color-contrast-rgb: 0,0,0;
  --ion-color-shade: #e0e000;
  --ion-color-tint: #ffff1a;
}
```

You could use our color generator to auto generate some of these values here: https://beta.ionicframework.com/docs/theming/color-generator/

We have some documentation on the different layers that make up a color and why they're needed here: https://beta.ionicframework.com/docs/theming/advanced/#color-language

The documentation does need to be updated to include the _new_ way of adding a color though.

**Comment by peterennis** [comment]
@brandyscarney  Great! Thanks for the note. I will play with this and check the docs.

**Comment by peterennis** [comment]
@brandyscarney 
I have an initial working demo for all named colors here: https://aesvg.adaept.com/
div background colors are hard coded to show some contrast with the icon colors.

How can I reference the base/contrast... colors with vars?
How would this be passed into the component as an option?

I want to test the color presentation effects more thoroughly.

**Comment by brandyscarney** [comment]
Thanks for the issue! At this time we are not going to be adding this functionality to the `color` attribute. Please use CSS and the CSS variables available to change specific background/colors. 

See this forum post for ways to reference the added colors base/contrast: https://forum.ionicframework.com/t/ionic-4-how-to-get-color-values-from-element-styled-with-color-directive/145458

I also created an issue to document that here: https://github.com/ionic-team/ionic-docs/issues/159

For future theming questions, please ask on the [forum](https://forum.ionicframework.com/) as it will help other people out, as well. Thanks! 🙂
