### ISSUE TITLE
[Ionic v4] Can't bind to 'ngModel' since it isn't a known property of 'ion-toggle' / 'ion-range' / 'ion-checkbox' etc.

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#14868]
**Ionic Info**
@ionic/angular: "4.0.0-alpha.12"

**Describe the Bug**
The property `ngModel` isn't supported on `ion-toggle`

When I run a prod build I get the following error:

> ERROR in : Can't bind to 'ngModel' since it isn't a known property of 'ion-toggle'.
> 1. If 'ion-toggle' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
> 2. If 'ion-toggle' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

According the example in the documentation this should be still possible as it was with Ionic v3

https://github.com/ionic-team/ionic/blob/a4659f03b4300a51e52f9f1a4e885cfca9b66f52/core/src/components/toggle/usage/angular.md

**Expected Behavior**
Being able to use 'ngModel' on `ion-toggle`

**Code**

    <ion-toggle [(ngModel)]="pepperoni"></ion-toggle>

**UPDATE**

Same error for 'ion-range', 'ion-checkbox', 'ion-input' etc. so generally speaking is that a breaking change or a bug?

**Question**
I don't use reactive forms or forms module on my side

**Comment by paulstelzer** [comment]
No, this is working. Please keep in mind to add the FormsModule to your module or create a  SharedModule to import and export FormsModule

```
@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    RouterModule.forChild([
      {
        path: '',
        component: HomePage
      }
    ])
  ],
  declarations: [HomePage]
})
export class HomePageModule { }
```

**Comment by peterpeterparker** [comment]
@paulstelzer funny thing is that with Ionic v3 respectively Angular v5 you didn't had to import `FormsModule` in any modules in order to be able to use `ngModel`, but, you are right, now with Ionic v4 respectively Angular v6, if you want to, it's a must

Side note, same with `ReactiveFormsModule ` if you use `formGroup` or `formControlName` which need to be imported
