### ISSUE TITLE
Back Button not Working

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic#14861]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.11 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.13
   @angular-devkit/core       : 0.7.0-rc.1
   @angular-devkit/schematics : 0.7.0-rc.1
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.11
   @ionic/schematics-angular  : 1.0.0-rc.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.4

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v9.8.0 (/usr/local/Cellar/node/9.8.0/bin/node)
   npm               : 6.1.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/kensodemann/Library/Android/sdk/
```

**Describe the Bug**
With Alpha.13, the `ion-back-button` component does not take me back to the prior page, but rather displays a blank page.

**Steps to Reproduce**
1. `git clone git@github.com:kensodemann/test-prolea.git`
1. `npm i`
1. `ionic serve`
1. go to the contacts tab
1. press the `Open Child Page One` button (top button)
1. press the `back` button in the app's nav bar
1. everything appears to work *
1. upgrade to alpha 13
1. repeat above starting with step 2
1. page is blank after `back`

* I say "appears to work" because even with Alpha.12, the`ion-back-button` takes me to http://localhost:8100/tabs and not http://localhost:8100/tabs/(contact:contact), but at least the contacts page is shown even if the URL is incorrect.

**Related Code**
https://github.com/kensodemann/test-prolea

**Expected Behavior**
The `ion-back-button` would take me back to http://localhost:8100/tabs/(contact:contact) instead of http://localhost:8100/tabs, the contacts page would be displayed again, and all life would be happiness and joy.

**Comment by kensodemann** [comment]
Testing: I just upgraded https://github.com/kensodemann/test-prolea to `beta.3` and this is still an issue.

**Comment by corcorb** [comment]
I'm getting the same behavior on a tabs page, with an added issue — if, after going back, I click on either the current tab or another tab, the whole page reloads.

**Comment by kensodemann** [comment]
Updated the sample app from beta.3 to beta.15 and verified that this is still an issue with the latest beta.

**Comment by kensodemann** [comment]
I am going to close this because:

1. we do not use the named router outlets anymore, and the demo app for this used that.
1. while we still have a related issue, it is covered by several other reported issues, including #16923, #15216, and #17421

Any further comments should be directed to #15216
