### ISSUE TITLE
Ion-Input not inheriting color

### ISSUE THREAD

**Issue by popcorn245** [ionic-team/ionic#14864]
# Bug Report

**Ionic Info**
```
    "@ionic/core": "4.0.0-beta.0",
    "@stencil/core": "0.10.9",
```

**Describe the Bug**
Color not being inherited for ion-input

**Steps to Reproduce**
1. Set color on input
2. Cry...

**Expected Behavior**
Have tried setting color on ion-input as well as setting various CSS variables but nothing will change the font color.

**Additional Context**
![image](https://user-images.githubusercontent.com/4184680/43212395-779e752e-8ff9-11e8-9d11-6232a6e328fd.png)

**Comment by abalad** [comment]
same here 

![image](https://user-images.githubusercontent.com/5459282/43296310-07d92b3e-9121-11e8-8063-e0222f617172.png)
