### ISSUE TITLE
Ionic 4 tabbar icon customization 

### ISSUE THREAD

**Issue by lander854** [ionic-team/ionic#14862]
# Support Question

I could not find on documentation or anywhere on the internet a way to customize ionic 4 tabbar specific icon size…
And in the v4 there is a way to set custom colors for each tabbar icon?

**Comment by manucorporat** [comment]
cc @brandyscarney maybe we should add a CSS variable for that?

**Comment by peterennis** [comment]
@lander854 
Working on something similar.
Here: https://aesvg.adaept.com/
https://github.com/peterennis/ae-svg-components/tree/master/src/ae-icons-component
I plan to include all named web colors for the first version
and time it with Ionic 4 release.
I intend to split out the CSS into a separate project outside
of my sandbox.

Ionic 3 playground with animation here: https://aeicons.adaept.com/
https://github.com/peterennis/aeicons
It will eventually be migrated to Ionic 4.

@manucorporat CSS variables are good for props into stencil components.

Related: https://github.com/ionic-team/ionic/issues/14857

**Comment by paulstelzer** [comment]
The tabbar has changed in one of the latest betas. Is your issue solved with this or is it still available?

**Comment by paulstelzer** [comment]
Fixed by beta.17
