### ISSUE TITLE
[Ionic v4] content.resize() should be public

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#14875]
**Ionic Info**
@ionic/angular: "4.0.0-alpha.12"

**Describe the Bug**
`content.resize()` isn't a `public` as it was in v3

**Expected solution**
Set the method `content.resize()` as `public` for backwards compatibility or provide guidance about how to migrate in the breaking changes list

**Related code**
see method `resize()` in https://github.com/ionic-team/ionic/blob/a7f1f4daa7166281f0735552b122d4c827cd20f1/core/src/components/content/content.tsx

**Comment by manucorporat** [comment]
is it causing problems the lack of this API in your app?

**Comment by peterpeterparker** [comment]
@manucorporat plz excuse me but I'm not sure I understand your question. you mean generally speaking or regarding `content.resize()`?

**Comment by peterpeterparker** [comment]
@manucorporat I went thru my git history and it looks like I use the `resize()` method for my chat and details pages on iOS special because of bounce or something

Since I'm not there right now with the migration, i would then suggest that, if it's ok for you, we let this one on the side, and I comeback or close it later in the future

**Comment by vovikdrg** [comment]
I have same thing. My app dynamically show/hide toolbars. In v3 I used to call resize method to make sure that empty space goes away

**Comment by mhartington** [comment]
@vovikdrg in this case the content should be resizing automatically to account for the new content

**Comment by cvaliere** [comment]
@mhartington @manucorporat I'm also using content.resize() in my Ionic v3 apps

if in Ionic v4 it's not needed anymore, I'm happy because it felt quirky

but then please just document it in the Breaking changes section; currently, there are still a lot of APIs that have disappeared (#14923, #14883, #14882, #14881, #14880, ...) without guidance how to migrate

**Comment by peterpeterparker** [comment]
A month later, I still didn't feel the need to have reuse this method `.resize()` so I guess yes, could confirm, it's not needed anymore in v4 ;)
