### ISSUE TITLE
medium/large apps on Windows nearly unusable, finally found reason: Selectors (mostly)

### ISSUE THREAD

**Issue by DennisSmolek** [ionic-team/ionic#14876]
We've deployed nearly identical code on iOS, Android, and Windows UWP systems and across the board the Windows systems are horrendously slow...
Like, 4s to calculate item position slow:
![pre css](https://user-images.githubusercontent.com/1397052/43245579-6efb476e-9074-11e8-82af-dd31f3bda8cc.PNG)

Scouring the internet for the issue I found [ALL](https://github.com/ionic-team/ionic/issues/10009) [THESE](https://github.com/ionic-team/ionic/issues/8710) [OTHER](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11555978/) [ISSUES](https://forum.ionicframework.com/t/ionic2-very-slow-on-windows-phone-10/76051/7)

And across the board the devs didn't get much of a reply, and in [some cases](https://github.com/ionic-team/ionic/issues/11783#issuecomment-311356104) were simply blown off. 

But those dev's had the right of it, using more complex apps besides basic tabs/hello world like the [iOffice Conference App]( https://nghiacc.github.io/ionic-conference-app/) will show you how its happening. 

### Why is IE/Edge Slower? ###
The first most obvious thing is it doesn't support shadow dom and a few other things so it handles tons of DOM elements very very poorly. Instead of only repainting/adjusting the small changes it triggers an entire reflow. 
[Gregor Srdic Did a nice write up on it here](https://medium.com/@gregor.srdic/optimising-ionic-application-for-microsoft-edge-46e62562ae2)

So first the layout is thrashing hard (thats why it triggers over and over) But then a single layout calculation takes 4S Compared to 20ms or less in chrome. WTF?

Doing more searching I found [this article by Alexei Antipov](https://medium.com/@antipov.alexei/ie11-performance-bottleneck-de304569361d) That matches my issue EXACTLY. 

### Material in Angular 1 Had the same issue ###
More googling got me to Angular having the [SAME](https://github.com/angular/material/issues/3455) [ISSUES](https://github.com/angular/material/issues/1771) back in 2015.. Same looking performance charts. 

Their solutions? Remove all `:active` sudo selectors ([link](https://github.com/angular/material/issues/1771#issuecomment-198626165))
And [go line by line and strip all Attribute selectors](https://github.com/angular/material/pull/4282)

[CSS Lint even has a warning for the attributes](https://github.com/CSSLint/csslint/wiki/Disallow-unqualified-attribute-selectors)

### Testing The Theory ###
So the first thing I did was start using Edge to test my build. It seems most devs use Chrome/FF/Not Edge so they haven't seen and dont really care about the issue. 

I then ripped apart main.css. I stripped out ALL the iOS related selectors reducing the file by 30%
I then just did a super broad scrubbing of attribute selectors. (1330!)

Then I ran the build:
![firstsimple](https://user-images.githubusercontent.com/1397052/43246937-d7d4e0fc-9078-11e8-9762-4bcd8a4e064a.PNG)

WHAAT? I got a 92% reduction from 4,000ms to 342ms just by reducing the file size a bit and removing those selectors. 

Further refinement of my app by removing other plugins like flexbox has helped some, and of course I re-wrote a LOT of code to hide/ remove if not needed. I've gotten it down to 100-200ms which I think is as best as I'm going to be able to get it.

### What's happening ###
First, because IE doesn't support Shadow Dom it renders the entire body of content on every layout change. Then with it being super slow at [attribute & other selectors](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13348719/) it runs through the entire matching stack for **EVERY ELEMENT.** You can see in my first image it takes 1-2ms PER ELEMENT

```
[tabsLayout=icon-left] .tab-button,
[tabsLayout=icon-right] .tab-button,
[tabsLayout=icon-start] .tab-button,
[tabsLayout=icon-end] .tab-button {
  -webkit-box-orient: horizontal;
  -webkit-box-direction: normal;
  -webkit-flex-direction: row;
  -ms-flex-direction: row;
  flex-direction: row;
}

[tabsLayout=icon-left] .tab-button .tab-button-icon,
[tabsLayout=icon-start] .tab-button .tab-button-icon {
  padding-right: 8px;
  text-align: right;
  text-align: end;
}

[tabsLayout=icon-right] .tab-button .tab-button-icon,
[tabsLayout=icon-end] .tab-button .tab-button-icon {
  padding-left: 8px;
  text-align: left;
  text-align: start;
  -webkit-box-ordinal-group: 11;
  -webkit-order: 10;
  -ms-flex-order: 10;
  order: 10;
}
```
Bad Selectors

### Ok Great you found it, what's the fix? ###
Well, one way is to do what Material did and simply stop using attribute selectors, start with unqualified ones and try to get rid of them in general with a preference on classes. This core level fix will immediately see significant Windows performance gains. 

As thats super unlikely to happen what Im doing is creating a `baseIonic.css` and using [This Article](https://www.joshmorony.com/including-custom-css-files-in-the-ionic-build-process/) I've changed my SASS to ignore the `npm-modules` of ionic.. This way my code gets merged without the offending selectors. 

I'm went a bit extreme and removing all of them, not just unqualified ones. So I'm doing a version now where I only adjust the unqualified selectors. There's als an INSANE amount of pseudo selectors that I understand run perfectly fine on Chrome, but are killing larger apps. 

I don't have a quick fix right away solution, I'm working through it now.. But I wanted to get the update to the issue out there...

**Comment by adamdbradley** [comment]
This is a great issue, thank you so much for putting together the data! You're right, it comes down to all the attribute selectors. Good news is that we don't have to use `data-` attributes for scoped styles to work, that was just a choice at the time. But we can update stencil to use css classes instead.

Thanks again for opening the issue! We'll get this fixed up in stencil and then update ionic. Thanks!

**Comment by adamdbradley** [comment]
Currently fixed in stencil master. The next release of Ionic will no longer be using `data-` attributes for polyfilled shadow dom. Thank!
