### ISSUE TITLE
[Ionic v4] ion-refresher has no property enabled

### ISSUE THREAD

**Issue by cvaliere** [ionic-team/ionic#14879]
**Ionic Info**
@ionic/angular: "4.0.0-beta.0"

**Describe the Bug**
ion-refresher has no property enabled as it had in v3

**Expected solution**
Put it back or provide guidance about how to migrate in the breaking changes list

**Comment by brandyscarney** [comment]
Thanks for the issue! Right now `disabled` is the property to use, but I'd like to bring this up for discussion.

@ionic-team/framework - I know we changed this to make `disabled` the consistent attribute across the components, but I am kind of thinking in the two cases where `disabled` defaults to `true` it should be changed to `enabled` defaulting to `false`. Just so by default the attribute is not there & adding it makes it `true.`

<img width="504" alt="screen shot 2018-07-26 at 11 19 18 am" src="https://user-images.githubusercontent.com/6577830/43271531-c39b7630-90c5-11e8-97c4-b8fe9cb650bc.png">

**Comment by mhartington** [comment]
mmm, I think it should stay the same.

Having most of the components use `disabled` as the prop name and 2-3 use `enabled` makes people have to second guess when to use the right one. By keeping things as `disabled`, this is not an issue.

If we made the switch, i'd rather it be all or nothing.

**Comment by cvaliere** [comment]
my 2 cents: why refresher is disabled by default? it seems to me that in v3 it was enabled by default, wasn't it?

**Comment by brandyscarney** [comment]
@cvaliere Hmm you are correct. 🤔 

https://github.com/ionic-team/ionic/blob/v3/src/components/refresher/refresher.ts#L103

I think we need to switch the default back. It seems counterintuitive to set `disabled="false"` by default.

**Comment by cvaliere** [comment]
thank you, that was really fast!

you can look at the others issues I created today, it's all the same kind of stuff 😁
