### ISSUE TITLE
[Ionic v4] Datetime not displaying when value = max value

### ISSUE THREAD

**Issue by lassesteffen** [ionic-team/ionic#14877]
# Bug Report
**Ionic Info**
https://unpkg.com/@ionic/core@4.0.0-beta.0/dist/ionic.js

**Describe the Bug**
Datetime does not display a value, when the value choosen equals the max picker value

**Steps to Reproduce**
1. Go to https://beta.ionicframework.com/docs/components#datetime
2. Set the datetime picker to the max date
3. See that nothing is displayed

**Expected Behavior**
I always want to see the date that I picked. Even when the date is the maximum possible date, I want to see the whole date.

**Comment by diver2** [comment]
it does not allow even you to pick the max day, or the max month. For ex, if you don't specify max date, it starts for me on 01/01/2017. 
Any date I try to pick with 01 on the day, or 01 on the month, or 2017, that part will be blank. So if I try to pick 01/01/2017 = all blank. If 01/03/2015 it will show /03/2015 - if 03/01/2015 - 03//2015

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us. I'm not seeing this issue anymore on v4.0.1. Would you be able to try this again with the latest version of Ionic, and let me know if you are still experiencing this issue?

**Comment by lassesteffen** [comment]
Did not have this problem any more!
