### ISSUE TITLE
[Ionic v4] Padding not working

### ISSUE THREAD

**Issue by lassesteffen** [ionic-team/ionic#14878]
# Bug Report

**Ionic Info**
https://unpkg.com/@ionic/core@4.0.0-beta.0/dist/ionic.js

**Describe the Bug**
Padding attribute does not apply padding

**Steps to Reproduce**
1. Go to https://jsfiddle.net/zj2eo31n/3/
2. See that no element has padding

**Expected Behavior**
Padding is applied when padding attribute is set.

**Comment by brandyscarney** [comment]
Thank you for the issue! The ionic CSS needs to be included in order for padding to work. It can be added with the following line:

```
<link rel="stylesheet" href="https://unpkg.com/@ionic/core@4.0.0-beta.0/css/ionic.min.css">
```

I updated your jsfiddle to reflect this: https://jsfiddle.net/n1ve7rcg/

Or it can be imported directly into your CSS. Some more information on that can be found here: https://gist.github.com/manucorporat/4a8955134bb90fa7f6ed0bb80b21ef59

I am currently working on getting this added to our breaking changes document and updating some of our beta documentation on it.

Please note that `padding-left` and `padding-right` have been removed: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#css-utilities
