### ISSUE TITLE
[Ionic v4] Tabs scroll not working with toolbar

### ISSUE THREAD

**Issue by lassesteffen** [ionic-team/ionic#14886]
# Bug Report

**Ionic Info**
https://unpkg.com/@ionic/core@4.0.0-beta.0/dist/ionic.js

**Describe the Bug**
Tabs are not scrollable in combination with a toolbar.

**Steps to Reproduce**
1. Go to https://jsfiddle.net/qh9g5oLj/12/
2. See that you can not scroll down the first tab

**Expected Behavior**
Tabs are scrollable

**Comment by gregor-srdic** [comment]
I believe you should use <ion-content> wrapper around your content inside <ion-tab>

**Comment by lassesteffen** [comment]
Fixed it for me

**Comment by brandyscarney** [comment]
Scrollable was added to the segment component in the [4.0.0-beta.15](https://blog.ionicframework.com/ionic-release-v4-beta-15-out-today/) release by the following PR: https://github.com/ionic-team/ionic/pull/16273.
