### ISSUE TITLE
App unresponsive on iOS after selecting photo/video from photos library

### ISSUE THREAD

**Issue by hebra** [ionic-team/ionic#14887]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)  : 4.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.3.0, browser 5.0.3, ios 4.5.4

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.7.0 (/usr/local/Cellar/node/10.7.0/bin/node)
   npm        : 6.2.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : not set
```

**Describe the Bug**
(only iOS) When selecting a video from the iPhone media library (aka Photos) triggered via a HTML <input type=file> tag, or when taking a photo/video triggered via that input field the app does not respond anymore as soon as Choose is tapped. Instead the last camera view/media library view is stuck on the screen, froze.

What works as expect is: selecting a video or photo via the file browser (aka Files), selecting a photo from the media library (but not if I select a video).

What doesn't work: choosing a video from the library, or taking a photo or video via camera.

Side note: when adding a change handler to the input field to console print information about the selected file, that information is printed even for the 'crashed' state, but only after I pressed the home button to put it into the background and then reopen the app again 

**Steps to Reproduce**
1. Create a simple app with Angular 6 support (don't think Angular is the problem here though)
2. in a test page add an <input type=file> tag
3. Update the Ionic/Cordova plugins and permissions to allow access to the Camera and Media Library on iOS devices
4. build and deploy the app to an iPhone (not a simulator)
5. start the app and tap on the Choose File button
6. tap on Photo Library
7. Select a video and tab Choose
8. app doesn't return to the app screen

**Expected Behavior**
After choosing/taking a video or photo the app should show the original app screen again with an updated input file selector.

**Comment by hebra** [comment]
@brandyscarney shouldn't the v3 label a v4 label as I am using Ionic 4 beta?

**Comment by marcorinck** [comment]
@hebra you are only using v4 of the ionic-cli but you are still using ionic 3.9.2 (thats the library being used at runtime).

Ionic4 beta would look like this:

```` 
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.1
   @angular-devkit/schematics : 0.7.1
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

````

**Comment by brandyscarney** [comment]
@marcorinck Is correct. 🙂 I add the `v3` label based off of the framework version in your `ionic info`:

```
   Ionic Framework    : ionic-angular 3.9.2
```

**Comment by hebra** [comment]
@marcorinck thanks for the hint. I now created a new Ionic 4 Beta project with below info output. Still the same issue remains as posted originally.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.1.1
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : ios 4.5.5

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.7.0 (/usr/local/Cellar/node/10.7.0/bin/node)
   npm        : 6.2.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : not set

```

**Comment by hebra** [comment]
Some more findings on this issue:
- it is definitally an issue with Ionic and/or Angular as when I create a raw Cordova project (7.1.0, same the Ionic one) the selection works w/o issues
- by default the raw Cordova input type=file allows multiple file selection from the photos library
- Ionic/Angular by default only allows a single file
- when adding a 'multiple' attribute to the input tag, I can also select more than one file but with some weird behaviour as I need to go into an Album, select something, then go back into main library sceen, and then back into e.g. Videos again to actually trigger the Done button, afterwards the files are properly available in the app
- if I don't do this in-out-in the Done button is responding when touching it but nothing happens

**Comment by hebra** [comment]
This issue has been fixed after upgrading to cordova-plugin-ionic-webview 2.x and cordova-plugin-file 6.x.
