### ISSUE TITLE
[Ionic v4] ion-menu has no property content

### ISSUE THREAD

**Issue by cvaliere** [ionic-team/ionic#14880]
**Ionic Info**
@ionic/angular: "4.0.0-beta.0"

**Describe the Bug**
ion-menu has no property conten as it had in v3

**Expected solution**
Put it back or provide guidance about how to migrate in the breaking changes list

**Comment by ThonyFD** [comment]
Some work arround to handle this?

**Comment by jaden210** [comment]
content is now contentId see: [here](https://github.com/ionic-team/ionic/issues/14363)

**Comment by manucorporat** [comment]
Yeah, since ion-menu now needs to work everywhere (even if angular is not used), the new API is contentId
