### ISSUE TITLE
[Ionic v4] What Keyboard should we use?

### ISSUE THREAD

**Issue by cvaliere** [ionic-team/ionic#14882]
**Problem**

In v3, ionic-angular had a class [Keyboard ](https://ionicframework.com/docs/api/platform/Keyboard/)
This class apparently disappeared in v4, while not listed in the [breaking changes](https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#menu-toggle)

**Solutions**

There seems to be a [Ionic-Native keyboard](https://ionicframework.com/docs/native/keyboard/) which provides similar API. But it's a wrapper around [ionic-plugin-keyboard](https://github.com/ionic-team/ionic-plugin-keyboard), which is deprecated. It suggests to use [cordova-plugin-ionic-keyboard](https://github.com/ionic-team/cordova-plugin-ionic-keyboard) instead, but this one has no ionic-native wrapper.

So, in the end, what Keyboard should we use?

**Comment by peterpeterparker** [comment]
@cvaliere it isn't v4 related but rather related to the plugin

my understanding is that https://github.com/ionic-team/cordova-plugin-ionic-keyboard is the supported and actual plugin and that there isn't any native wrapper for it, at least the last time I upgraded my Ionic v3 app I went that way

**Comment by cvaliere** [comment]
If I were to guess, I would make the same guess as yours

But it definitely is a breaking change of v4, because the class Keyboard just disappeared
I think the Ionic team should write it in the Breaking Changes and provide an official recommendation to replace it

**Comment by peterpeterparker** [comment]
@cvaliere I'm agree it's confusing, but again, not really v4 related I think, if you upgrade the plugin (switching from the old to the new one) in v3 you would face the same issue

anyhow you are right, maybe the answer is just "there won't be any wrapper for the new plugin." that's it

but I guess the following issue in native is the one you may looking for:

https://github.com/ionic-team/ionic-native/issues/2306

**Comment by cvaliere** [comment]
@peterpeterparker I really believe there are **two** issues:
- The plugins are a mess; thanks for pointing out [ionic-team/ionic-native#2306](https://github.com/ionic-team/ionic-native/issues/2306)
- There is a breaking change in **Ionic v4**, which is that the class Keyboard from the package ionic-angular (absolutely not related to plugins) has disappeared

I'm just saying that this breaking change in **Ionic v4** should be written somewhere.

**Comment by peterpeterparker** [comment]
@cvaliere oki doki no worries, let's see what the team would do ;)

sorry didn't want to had noise in the topics, but anyhow your last comment is a good summary!
