### ISSUE TITLE
Date Time Picker Year Value not including 2018

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic#14895]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0
   @angular-devkit/schematics : 0.7.0
   @angular/cli               : 6.1.0
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.1.2
   NodeJS     : v8.9.1 (/usr/local/bin/node)
   npm        : 6.2.0
   OS         : OS X El Capitan
   Xcode      : Xcode 8.2.1 Build version 8C1002

Environment:

   ANDROID_HOME : not set
```

**Describe the Bug**
When setting the DT picker with no default values, the year range stops at 2017.

**Steps to Reproduce**
1. Bring up the DT picker (on DevApp or web)
2. 2017 is the last year in the picker

**Related Code**
```
<ion-item>
      <ion-label>Action Time</ion-label>
      <ion-datetime display-format="MMM DD, YYYY h:mm A"></ion-datetime>
    </ion-item>
```

**Expected Behavior**
The current year should be the default value for the picker.

Sample via Ionic DevApp:
![img_9476](https://user-images.githubusercontent.com/527875/43288851-0327117a-90de-11e8-8f69-e6587834f4aa.PNG)

**Comment by troyanskiy** [comment]
Same for me.
Reproducible here https://beta.ionicframework.com/docs/api/datetime

**Comment by crebuh** [comment]
Same here, any workarounds?

**Comment by Franrredo** [comment]
Another error appears when you select '01' or '1' at the day or month, the number isn't displayed in the datepicker.

Sorry for my bad english.
