### ISSUE TITLE
[Ionic v4] - CLI generates blank app with wrong ionic-angular library

### ISSUE THREAD

**Issue by loicsalou** [ionic-team/ionic#14892]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)  : 4.0.1 (/Users/loicsalou/.nvm/versions/node/v9.11.1/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

System:

   NodeJS : v9.11.1 (/Users/loicsalou/.nvm/versions/node/v9.11.1/bin/node)
   npm    : 6.2.0
   OS     : macOS High Sierra
```

**Describe the Bug**
when creating a new blank app using "ionic start blankApp" the generated package.json references the old library "ionic-angular@3.9.2" instead of "@ionic/angular". This is rather misleading because when trying to migrate my ionic3 app I tried to get rid of ionic-angular but I lost quite some time wondering wether to remove it and use the new one or not. 

**Steps to Reproduce**
1. issue the CLI command "ionic start blankApp", no cordova, no ionic pro.
2. check package.json

**Related Code**

**Expected Behavior**
blank app, like any other, should reference the correct librairies to be used because we're using such blank apps as a ref implementation for our own apps.

**Additional Context**
if I'm wrong then the v4 documentation should explain clearly what is the intention for letting old library ionic-angular alive

**Comment by dwieeb** [comment]
The [beta docs](https://beta.ionicframework.com/docs/installation/cli#start-an-app), our blog post, etc. clearly explain that `--type=angular` is required to start an Ionic 4 project. Without it, you are creating a v3 app. 

The CLI version is not the Framework version. CLI 4 is released, but Framework is still in beta, so the default project type is a v3 app. The default will switch to Ionic 4 in a later version of CLI 4.
