### ISSUE TITLE
v4: GestureController x AND y simultaneously for both direction (perhaps also a breaking change)

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#14909]
**Describe the Feature Request**
In **v3** we was able directly to use `Hammer.js` where we had a workaround described by @joshuamorony in this blog https://www.joshmorony.com/building-an-absolute-drag-directive-in-ionic-2/

```
let hammer = new window['Hammer'](this.element.nativeElement);
hammer.get('pan').set({ direction: window['Hammer'].DIRECTION_ALL });
```
This had some bugs on mobile devices, which I opened some bugs and forum posts, but I was not able to resolve the bug.

Now in **ionic4** you introduced the `GestureController`, which is great. But there is some limitation you can only choose for direction X or direction Y. We are not able to have both of them simultaneously.

Perhaps there are some technical or mobile browser problems related on this behavior, or for sure there could be some problems with scrolling. But I really hope we can use this controller to simulate a out of the box drag simulation.
I'm not asking to have a drag and drop, which probably is not your target. But having the possibility to use the controller for one of the or both direction could be very very important, so we can omit to import or gesture libs which perhaps goes in conflict with the ionic one.

BTW:
Could it be, most or all of the gestures are not in v4?
https://ionicframework.com/docs/components/#gestures

Also I think it could be important to have a classical `press` (300ms) event. For example we would like to enable a gesture only on press, this perhaps could also prevent some problems with scrolling?
For example if we have a drag with your controller which has enabled XY simultaneously we would like to enable it only after long press.

Best regards
Michael

**Comment by manucorporat** [comment]
Hammerjs can still be used in your angular application, https://blog.angularindepth.com/gestures-in-an-angular-application-dde71804c0d0

Ionic don't provide it by default :)
