### ISSUE TITLE
[Ionic v4] no arrows in the menu

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#14907]
**Ionic Info**
@ionic/angular: "4.0.0-beta.0"

**Describe the Bug**
First of all, maybe that's a choice from Ionic and I missed it in documentation, if it's the case, just close the issue. But if it isn't a choice, where are the arrows for the items in the menu?

**Expected Behavior**
If it isn't a deprecated design choice, I would except to have arrows next to every clickable items in the menu pane

**Additional Context**

Here some screenshots. I have also created a blank project to be sure that the issue isn't a side issue of my styling and could confirm than even straight after "ionic start" there aren't any arrows displayed in the menu

Ionic v4:

<img width="283" alt="capture d ecran 2018-07-27 a 15 34 51" src="https://user-images.githubusercontent.com/16886711/43323734-c1a11a54-91b2-11e8-8a57-f6301d6aa520.png">

Ionic v3:

<img width="291" alt="capture d ecran 2018-07-27 a 15 34 46" src="https://user-images.githubusercontent.com/16886711/43323742-c627c956-91b2-11e8-9e9b-5500507d7e13.png">

**Comment by brandyscarney** [comment]
Thanks for the issue! Could you paste the markup you're using for this? Are these button items?

**Comment by peterpeterparker** [comment]
@brandyscarney in Ionic v3 like in the doc, buttons, https://ionicframework.com/docs/components/#menus

in Ionic v4, like in a blank app `ionic start -type=angular`, like https://github.com/peterpeterparker/ion-title-component/blob/master/src/app/app.component.html

should I use `ion-button` instead of `ion-item`? if so shouldn't the starter app also use `ion-button`?

thx a lot for the support in advance

**Comment by peterpeterparker** [comment]
@brandyscarney sorry I understand now, it's all good, adding the attribute `button` to the items solves that

maybe would be could to add these attributes to the start app but not a must, other persons are probably more clever than me ;)

    <ion-app>
      <ion-split-pane>
        <ion-menu>
          <ion-header>
            <ion-toolbar>
              <ion-title>Menu</ion-title>
            </ion-toolbar>
          </ion-header>
          <ion-content>
            <ion-list>
              <ion-menu-toggle auto-hide="false" *ngFor="let p of appPages">
                <ion-item button [routerDirection]="'root'" [routerLink]="[p.url]"> 
                  <ion-icon slot="start" [name]="p.icon"></ion-icon>
                  <ion-label>
                    {{p.title}}
                  </ion-label>
                </ion-item>
              </ion-menu-toggle>
            </ion-list>
          </ion-content>
        </ion-menu>
        <ion-router-outlet main></ion-router-outlet>
      </ion-split-pane>
    </ion-app>
