### ISSUE TITLE
[ionic v4 with angular] Calling Slides methods (ex. slideTo) in ngAfterViewInit throws error

### ISSUE THREAD

**Issue by bilalrazamoon** [ionic-team/ionic#14919]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (/Users/bilal/.config/yarn/global/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v8.9.4 (/Users/bilal/.nvm/versions/node/v8.9.4/bin/node)
   npm               : 6.2.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/bilal/Library/Android/sdk
```

**Describe the Bug**
When call slides methods (ex. slideTo) in `ngAfterViewInit` throws following error:
Error: Uncaught (in promise): TypeError: Cannot read property 'slideTo' of undefined
TypeError: Cannot read property 'slideTo' of undefined

**Steps to Reproduce**
1. Go to stackblitz example.
3. Check console.

**Related Code**
https://stackblitz.com/edit/ion-slides-afterviewinit

**Expected Behavior**
Slides methods (ex. slideTo) should work in `ngAfterViewInit`.

**Comment by GuilhermeBCC** [comment]
Internally the ion-slides are still starting Swiper when you call the methods.
I suggest creating the ionSlidesLoaded event for ion-slides.

**Comment by GuilhermeBCC** [comment]
This is not yet documented, but this must have been fixed by # 14865

**Comment by bilalrazamoon** [comment]
Now we can use `ionSlidesDidLoad` event in  "v4.0.0-beta.1" for calling slides methods.
