### ISSUE TITLE
v4 ion-button: override material design text transform

### ISSUE THREAD

**Issue by haydenbr** [ionic-team/ionic#14927]
# Feature Request

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI) : 4.0.1

System:

   NodeJS : v8.11.1
   npm    : 5.6.0
   OS     : macOS High Sierra
```

**Feature Request**
As an ionic developer, I would like to be able to override the `text-transform` css property for buttons in the material design mode in ionic v4, because this would allow me to use t

**Preferred Solution**
Provide a `--text-transform` variable that could be overwritten along with the other css variables in `ionic/core/src/components/button/button.md.scss` 

**Alternatives**
I could also just do the following:

```
<ion-button>
    <span style="text-transform: none">Here's my button text</span>
</ion-button>
```

which I will do for now, but it would be nice to be able to set text-transform along with the other variables I am overriding.

**Comment by peterennis** [comment]
@haydenbr 
Possibly related: https://github.com/ionic-team/ionic/issues/14862
Add a thumbs up as the suggestion is from one of the ionic css devs
and it relates to providing css variables for overriding.

**Comment by peterpeterparker** [comment]
I've got another open feature variable for button (adding variable `--contain`). I guess both tasks could be solve at once, therefore I just link my feature here https://github.com/ionic-team/ionic/issues/14899

**Comment by manucorporat** [comment]
There is not need to add a new variable, text is part of light dom, it can be styled using standard CSS properties:

<img width="1672" alt="screenshot 2018-07-29 at 13 16 02" src="https://user-images.githubusercontent.com/127379/43365731-a270aa48-9331-11e8-845b-8fa541439986.png">

**Comment by haydenbr** [comment]
Thanks for clarifying. At first I was confused as to why this would work, but that makes sense now. Thanks!
