### ISSUE TITLE
[ionic v4 with react] Integrating @ionic/core 4.0 beta defineCustomElements error

### ISSUE THREAD

**Issue by ferparra** [ionic-team/ionic#14925]
Hi everyone,

I'm having issues integrating Ionic Web Components to a React project.

So far, I have followed these instructions:
[https://stenciljs.com/docs/framework-integration/#react](https://stenciljs.com/docs/framework-integration/#react)

However, I get an error saying that `defineCustomElements` is not a function?

### Error screenshot
![image](https://user-images.githubusercontent.com/102316/43360939-b56fd888-9298-11e8-8d57-f755371b5de4.png)

### Sandbox code
[![Edit 4rkl487537](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4rkl487537)

**Comment by Hotell** [comment]
yup same issue here. 

Here is why is this happening:

- if you're using webpack or rollup, they'll consume `module` package.json field, which points to es2015 module files ( not es5 ) 

![image](https://user-images.githubusercontent.com/1223799/43458547-e941bcf6-94ca-11e8-87ce-b8d508c487b8.png)

which doesn't export `defineCustomElements`. This function is exported only from the `main` bundle, which is wrong.

![image](https://user-images.githubusercontent.com/1223799/43458630-33d3d48e-94cb-11e8-9592-0e8537684adb.png)


## Quick Fix

![image](https://user-images.githubusercontent.com/1223799/43458679-67416368-94cb-11e8-80dc-e700af2d9f99.png)


hope this is gonna be resolved sooner than later ✌️

**Comment by ferparra** [comment]
Awesome @Hotell!

I have changed the path to my Ionic JS library import, no errors.

Have you had to add anything else? My components styles are looking all wrong. Perhaps an import statement just for the stylesheet files?

**Comment by Hotell** [comment]
you need to import `ionic.css`

![image](https://user-images.githubusercontent.com/1223799/43468980-781302a4-94e5-11e8-99df-2539d39fba60.png)

but I'll save you the effort, I've tested today ( it took me almost whole day poor me...) ionic v4 components with react, and, well. It doesn't work ( also as ionic core devs stated on twitter "ionic v4 is primarily for Angular, react is not supported, yet" . Don't do the same mistake as I did :)

**Comment by ferparra** [comment]
Oh, I see... thanks! (I was also driving insane).

Yeah, it's confusing. My understanding is that thanks to Ionic 4 components being developed in Stencil, they should be framework agnostic. Seems like that's not entirely true.

**Comment by paulstelzer** [comment]
This is issue should be resolved in beta.17. If I am wrong, please write here!
