### ISSUE TITLE
[ionic v4 with angular] Security Vulnerability - hoek 2.16.3 - in package-lock.json

### ISSUE THREAD

**Issue by gigocabrera** [ionic-team/ionic#14920]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0
   @angular-devkit/schematics : 0.7.0
   @angular/cli               : 6.1.0
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : none

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.11.3 (/usr/local/bin/node)
   npm        : 6.2.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
My github repo is displaying the following warning 

> We found a potential security vulnerability in one of your dependencies.
> A dependency defined in package-lock.json has known security vulnerabilities and should be updated.

**Steps to Reproduce**
1. npm install -g ionic
2. ionic start myApp tabs --type=angular
3. npm i
4. Search for hoek version 2.16.3 in the package-lock.json

**Comment by CyberBLN** [comment]
https://github.com/ionic-team/ionic-app-scripts/pull/1493 will fix this
