### ISSUE TITLE
[Ionic 4] ion-textarea and ion-input color can't be styled

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#14931]
**Ionic Info**
@ionic/angular: "4.0.0-beta.0"

**Describe the Bug**
The color of `ion-textarea textarea` and `ion-input input` is fixed to `color: initial`, therefore, if I'm not mistaken, their colors can't be styled

**Expected Behavior**
Add the ability to style the `color` of `ion-textarea`  and `ion-input`

or

Set the `color: inherit` to `ion-textarea textarea` and `ion-input input`

**Comment by manucorporat** [comment]
Thanks for the issue! already fixed in master!
