### ISSUE TITLE
[IONIC V4]Local Host doesn't stop after Ctrl+C 

### ISSUE THREAD

**Issue by krngd2** [ionic-team/ionic#14938]
I have been using Ionic V4 for a couple of days and seen that after `ionic serve ` starting the local host in the vs code terminal , after pressing Ctrl+v the process cancelled but the local host is still running in the background, until I close the VS code completely. If I ran ionic serve again before closing, its showing error 

>  An error occurred while running subprocess npm.

**Comment by Neustart** [comment]
the same issue. I've came here to open the same ticket. Can somebody suggest how to fix this ?
