### ISSUE TITLE
[Ionic v4] ion-item-option doesn't get style class `activated` when clicked

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#14943]
**Ionic Info**
@ionic/angular: "4.0.0-beta.0"

**Describe the Bug**
When I click an `ion-item-sliding > ion-item-options > ion-item-option` the item doesn't get the style class `activated` (as in v3) in order to display the user that is click was effectively detected

**Related Code**

As in the breaking change doc

    <ion-item-sliding>
    <ion-item>
      <ion-label>Slide and click, not activated</ion-label>
    </ion-item>
    <ion-item-options side="end">
      <ion-item-option expandable (click)="clickSlideItem()">
        <ion-icon name="star"></ion-icon>
      </ion-item-option>
    </ion-item-options>
  </ion-item-sliding>

or

    git clone https://github.com/peterpeterparker/ion-title-component

**Expected Behavior**
Add style class `activated` when sliding items are clicked / activated

**Comment by brandyscarney** [comment]
I added the ripple and activated class, @camwiegert could you make sure the style is right for activated when you work on converting away from `--ion-color` vars?

**Comment by erperejildo** [comment]
shouldn't it be with `icon-only`?

https://beta.ionicframework.com/docs/api/item-sliding
