### ISSUE TITLE
ionic v4 Can't bind to 'ngModel' 

### ISSUE THREAD

**Issue by goelectricstations** [ionic-team/ionic#14942]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

Ionic:

   ionic (Ionic CLI)          : 4.0.1 (C:\Users\Computer\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.3.0-next.0
   OS     : Windows 10

Environment:

   ANDROID_HOME : not set

insert the output from ionic info here

compiler.js:215 Uncaught Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'ion-toggle'.
1. If 'ion-toggle' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'ion-toggle' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Comment by peterpeterparker** [comment]
Yep I run on that too https://github.com/ionic-team/ionic/issues/14868

To solve it, import `FormsModule` and if needed `ReactiveFormsModule` in the modules where you need it

**Comment by goelectricstations** [comment]
fixed

**Comment by goelectricstations** [comment]
@peterpeterparker  thank you fixed
