### ISSUE TITLE
[ionic 4.0.2] list item icon direction on iOS mode in rtl is opposit

### ISSUE THREAD

**Issue by HalwestRasul** [ionic-team/ionic#14958]
**list item icon direction on iOS mode in RTL is opposite** 

look this:

![ionic-rtl-issue](https://user-images.githubusercontent.com/10852176/43477474-f3a483b6-9503-11e8-9756-fc952b915ac3.PNG)

**Comment by abennouna** [comment]
Still an issue with beta.17. My current workaround is at template level because I didn't find a way to hack the CSS:

**component**
```typescript
public detailIcon;

constructor() {
  this.detailIcon = document.dir === 'rtl' ? 'ios-arrow-back' : 'ios-arrow-foward';
}
```

**template**
```html
<ion-list>
  <ion-item [detailIcon]="detailIcon">...</ion-item>
</ion-list>
```
