### ISSUE TITLE
[Ionic v4] menu pops out of split-pane within tabs

### ISSUE THREAD

**Issue by cleversolutions** [ionic-team/ionic#14957]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.0

System:

   NodeJS : v8.10.0 (/usr/local/bin/node)
   npm    : 5.6.0
   OS     : macOS High Sierra
```

**Describe the Bug**
The menu starts acting as a regular menu, rather than occupying the space in the split-pane.  

**Steps to Reproduce**
Reproduce on a device with sufficient width so that the split-pane is visible
1. Run the example project (see Related Code below)
2. Click About tab
3. Click Contact tab
4. Click Home tab - menu is rendered as a menu rather than in the left split pane
5. Click About tab - menu is rendered as a menu rather than in the left split pane
6. Click Contact tab - this one is still fine.

**Related Code**
I've put together an example project to illustrate this bug.
[GitHub](https://github.com/cleversolutions/ioic4TabsSplitPane).

**Expected Behavior**
The left split-pane contain the menu

**Additional Context**
As i understand it, when there are multiple menus in an app, you have to enable the appropriate menu. Normally I would do this in ionViewDidEnter, and the menu stays in the split-pane. Tabs are a bit of a different animal, so in tabs.page.ts I enable the appropriate tab when the tabs change.

**Comment by paulstelzer** [comment]
Is this issue still exist in beta.17?

**Comment by cleversolutions** [comment]
Unfortunately it still is. I upgraded the example project to beta.17 and it still exhibits the same behaviour.

**Comment by cleversolutions** [comment]
Actually I should clarify. It doesn't work as expected, but is different now. The menu will function if you enable it with each tab change; however, on a wider screen, it operates as a small device menu, not as a split pane menu should. I've updated the example repo with the updated version for beta.17.
