### ISSUE TITLE
[Ionic v4] Ugly modal transition when loading data in ionViewWillEnter or ngOnInit

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#14969]
**Ionic Info**
@ionic/angular: "4.0.0-beta.0"

**Describe the Bug**
Loading data in modals in lifecycle `ionViewWillEnter` or `ngOnInit` result in an ugly transition. As long as the data won't be loaded the modals won't be totally rendered, respectively the content and background of the modal will remains transparent

**Screenshots**

Open the modal:

<img width="259" alt="capture d ecran 2018-08-01 a 09 22 42" src="https://user-images.githubusercontent.com/16886711/43507568-cd543cc8-956d-11e8-934e-46657f1a8a4c.png">

Transition:

As you could see, title of the modal is rendered, modal is opened but content and background aren't rendered

<img width="267" alt="capture d ecran 2018-08-01 a 09 23 21" src="https://user-images.githubusercontent.com/16886711/43507758-384bf43a-956e-11e8-9eb9-8cc0f6504cf1.png">

**Code and demo repo**

    git clone https://github.com/peterpeterparker/ion-title-component

**Workaround**
Load data afterwards respectively in lifecycle `ionViewDidEnter`

**Expected Behavior**
As in Ionic v3, I want to be able to load data earlier than only when modal is rendered otherwise my users will always face loading spinner or something and wait time and will at the end have the feeling that the app is slow

**Comment by cvaliere** [comment]
@peterpeterparker should we still use `ionViewDidEnter` in Ionic v4?
This [paragraph](https://beta.ionicframework.com/docs/building/migration/#lifecycle-events) is definitely unclear to me. They say that `Some of the Ionic lifecycle events are equivalent to Angular lifecycle hooks`, but they don't see which ones... Any clue on that?

**Comment by peterpeterparker** [comment]
@cvaliere my understanding is that `ionViewWillEnter` or `ionViewDidEnter` are still a thing (my migrated app still rely on them)

on the other side, as described in the the paragraph you mentioned, `ionViewDidLoad` has been deprecated and even don't exist anymore. To replace it, `ngOnInit` should be used

**Comment by peterpeterparker** [comment]
It just works like a charm in v4-beta.7 👍 
Thx a lot
