### ISSUE TITLE
[Ionic v4] Tab History Lost with Angular Routing

### ISSUE THREAD

**Issue by danbroadbent** [ionic-team/ionic#14960]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**

When navigating past the root level of the tab, the history of that tab is lost when switching between tabs.

**Expected behavior:**

When navigating past the root level of the tab, the history of that tab is maintained when switching between tabs.

**Steps to reproduce:**

Clone Ionic Conference App https://github.com/ionic-team/ionic-conference-app
Switch to core-update branch
Run ionic serve
Click into one of the events on the Schedule Tab
Click the Speakers Tab
Click the Schedule Tab
Observe you are now back to the root of the tab, and have lost the history for that tab

```
Ionic:

   ionic (Ionic CLI)          : 4.0.1    
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.9
   @ionic/schematics-angular  : 1.0.0-rc.9

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : none

System:

   NodeJS : v8.11.2 
   npm    : 5.6.0
   OS     : macOS Sierra

Environment:

   ANDROID_HOME : not set
```

**Comment by GRRook** [comment]
Is there any news on solving this problem?

**Comment by agustinhaller** [comment]
Having the same issue

**Comment by Dema1348** [comment]
same issue here

**Comment by mhartington** [comment]
This has been fixed in beta 16, please update your apps.
