### ISSUE TITLE
Searchbar ionic V4 no show icon search android

### ISSUE THREAD

**Issue by wuilmerj24** [ionic-team/ionic#14967]
Hello I have a searchbar, but in andorid it does not show the icon of the magnifying glass
```
<ion-searchbar 
type = "search" 
animated = true 
spellcheck = true 
[(ngModel)] = "searchTerm" 
(ionInput) = "setFilteredItems ($ event)" 
show-cancel-button = true 
clear-icon = "close-circle "
search-icon =" search "> </ ion-searchbar>
```

![screenshot_1533104793](https://user-images.githubusercontent.com/7539995/43504692-0871f956-952a-11e8-8473-43cfb7ca5ef2.png)

**Comment by peterpeterparker** [comment]
I noticed the same problem when I set a `background-color` to `ion-searchbar input.searchbar-input` because the input is above the icon

Adding a `z-index: 1` to the icon solved it

    ion-searchbar {
        input.searchbar-input {
            background-color: red;
        }

        ion-icon.searchbar-search-icon {
            z-index: 1;
        }
    }

maybe that solves it for you too?

**Comment by brandyscarney** [comment]
This looks like an `@ionic/angular` app judging by the `ngModel` use. The properties in Angular should be camelCased:

```
<ion-searchbar 
  type="search"
  animated="true" 
  spellcheck="true" 
  [(ngModel)]="searchTerm"
  (ionInput)="setFilteredItems($event)"
  showCancelButton="true" 
  clearIcon="close-circle"
  searchIcon="search">
</ion-searchbar>
```

See usage example here: https://beta.ionicframework.com/docs/api/searchbar#usage

Does the icon only not show up when it's deployed to a device/simulator? Or are you not seeing it in Chrome as well?

**Comment by wuilmerj24** [comment]
I test it in the emulator with android 7. It does not show the search icon. I tested it on android 8 and it worked correctly

**Comment by manucorporat** [comment]
@peterpeterparker can you test again in beta.2?

**Comment by peterpeterparker** [comment]
@manucorporat with beta.2 it seems all good to me. also the workaround I described above isn't needed anymore

    ion-searchbar input.searchbar-input {
        background-color: #f7f7f7;

screenshot for proof

<img width="317" alt="capture d ecran 2018-08-12 a 10 27 31" src="https://user-images.githubusercontent.com/16886711/44000120-6f8c4300-9e1a-11e8-9ca4-1e314d1e9040.png">

**Comment by manucorporat** [comment]
Thanks David!

**Comment by peterpeterparker** [comment]
My pleasure
