### ISSUE TITLE
Simple Ionic 3 App Not Working on Android Device

### ISSUE THREAD

**Issue by dummywebdemo** [ionic-team/ionic#14977]
A simple hello world ionic 3 app working perfectly fine on ionic serve command in browser but when I run it using any of the following commands i am getting an error of "Couldn't connect to the server. (http://localhost:8080/)": 

**Commands:**

ionic cordova run android
ionic cordova run android (with liverelad) 

I have also done <preference name="loadUrlTimeoutValue" value="70000" />

Also done:

    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />

removed and added again whitelist and webview (also removed permanently) plugins also removed and added back the android platform.

Also disabled the firewall. Already on same network / wifi (both mobile and pc).
I have searched each and every forum / website pertinent to this error and also tried all the solutions but none of them worked.

I am using genymotion emulator but getting same error on that.

**Ionic Info:**

Ionic:

   ionic (Ionic CLI)  : 4.0.1 (C:\Users\PC\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 4.0.0
   OS                : Windows 7

Environment:

   ANDROID_HOME : C:\Users\PC\AppData\Local\Android\Sdk

**My plugins:**

ionic cordova plugins
-> cordova plugin ls

cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.0.2 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"

Please help me to solve this problem. Positive response highly appreciated.
![plugins](https://user-images.githubusercontent.com/22809323/43546423-090b28b0-95f2-11e8-8962-9d6c23a4cb96.png)
![screenshot_2018-08-01-13-47-56](https://user-images.githubusercontent.com/22809323/43546424-0974fb28-95f2-11e8-92be-1d4099039f85.png)
![plugins](https://user-images.githubusercontent.com/22809323/43546426-09f1d094-95f2-11e8-9698-ebe7038a7421.png)

**Comment by dummywebdemo** [comment]
Please somebody reply... still my problem not solved yet.

**Comment by jejotom996** [comment]
Same Issue with me, It works on my android 8, however when i tested it out on my Android 4.4.2 kitkat, it appears the same issue with this. Anybody up?

**Comment by hamid-moghadam** [comment]
suggest to check this article : https://ionic.zone/debug/ionic-and-android-4

**Comment by mhartington** [comment]
Hi there! From the look of your screenshots, it appears to be an Android 4.4 device. We just released a version of the cordova-plugin-ionic-webview to extend support to Android 4.4. Please update the plugin.

```bash
ionic cordova plugin rm cordova-plugin-ionic-webview
ionic cordova plugin add cordova-plugin-ionic-webview@latest

```
