### ISSUE TITLE
What constitutes a "Binary Change", in regards to Ionic Deploy?

### ISSUE THREAD

**Issue by Bengejd** [ionic-team/ionic#14978]
# Support Question

In the Ionic documentation, it states: 

> Note: The Deploy feature only works on binary compatible changes (HTML, CSS, JS), meaning if you rely on native code updates you must resubmit to the app store first before using Deploy.

What does this statement really encompas in regards to binary compatible changes? Does this include adding new cordova-plugins to an existing project? Or would that be considered a "binary change", and would require you to submit a new build to the app store?

**Comment by kensodemann** [comment]
Only HTML/CSS/JavaScript.

Adding new cordova plugins or upgrading existing ones is a binary change that requires a new submission to the app stores.

See here for details.
https://ionic.zendesk.com/hc/en-us/articles/360002243614-What-Are-Binary-Compatible-Changes-
