### ISSUE TITLE
Lazy loading and 404 page on wrong url

### ISSUE THREAD

**Issue by jguichot** [ionic-team/ionic#14986]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)  : 4.0.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.0

System:

   NodeJS : v8.9.3 (/usr/local/bin/node)
   npm    : 5.5.1
   OS     : macOS High Sierra
```

**Describe the Bug**
Hi everyone, I use lazy loading and IonicPage() for my navigation. It's works fine except when I declare a 404 page with segment ```**```. It does not go on page 404 when I want it.

**Steps to Reproduce**
Case 1:
1. Enter in navigator ```mywebsite/#/dlfhjsdkjfslfjsldkj```
2. It's redirect to my "rootPage" (Login page for example) declaration in "MyApp" principal module and not to my 404 Page.

Case 2:
1. Open app in navigator
2. Change url to ```mywebsite/#/dlfhjsdkjfslfjsldkj```, I get ```Uncaught (in promise): invalid views to insert``` error.  It does not go on 404 page.

**Related Code**

NotFound404Page
```
@IonicPage({
    'name': '*',
    'segment': '**'
})
@Component({
    selector: 'page-404',
    templateUrl: 'not-found.page.html',
    providers: []
})
export class NotFound404Page implements OnInit, OnDestroy
...
```

NotFound404PageModule
```
import { NgModule } from "@angular/core";
import { IonicPageModule } from "ionic-angular";
import { TranslateModule } from '@ngx-translate/core';
import { NotFound404Page } from "@app/features/not-found/pages/not-found.page";

@NgModule({
    declarations: [
        NotFound404Page
    ],
    imports: [
        IonicPageModule.forChild(NotFound404Page),
        TranslateModule.forChild()
    ],
    entryComponents: [
        NotFound404Page
    ]
})
export class NotFound404PageModule {}
```

**Expected Behavior**
I would like to display 404 page when a wrong URL is entered.

Thank's :)

**Comment by manucorporat** [comment]
Ionic 4 relies on angular router in order to implement navigation
