### ISSUE TITLE
[v4] segment-button add click() method (workaround Shadow DOM)

### ISSUE THREAD

**Issue by ghybs** [ionic-team/ionic#14980]
# Feature Request

**Ionic Info**
Directly using \@ionic/core version 4.0.0-beta.1 from CDN (e.g. unpkg)

**Describe the Feature Request**
Now that Ionic components use Shadow DOM, it is more complicated to programmatically access their inner Elements (i.e. use [`shadowRoot`](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot) in environments that use Shadow DOM, normal access otherwise).
In some cases this was necessary to workaround some current API shortages.

For instance, programmatically clicking on an [`<ion-segment-button>`](https://github.com/ionic-team/ionic/tree/v4.0.0-beta.1/core/src/components/segment-button) (e.g. with `.click()` method) does not trigger the segment highlight.
Therefore the current workaround is to access its inner DOM, query for the underlying `<button>` and `click()` on it.

Without Shadow DOM, it can be as simple as:
```javascript
document.querySelector('#segmentButtonId button').click()
```
With Shadow DOM, we have to query the Segment Button first, then query within its `shadowRoot`.
Handling both environments adds even more code.

**Describe Preferred Solution**
Add a `.click()` method on the `<ion-segment-button>` that gets it highlighted as if user had manually clicked on it.

**Describe Alternatives**
Expose the underlying `<button>` somehow?

**Related Code**
https://next.plnkr.co/edit/IvkXQw5I6LDI3frj?preview
- Button "Click on Button 1" programmatically clicks on Segment Button 1, but the latter does not get highlighted.
- Button "Click on Button 2" queries for the underlying Button of Segment Button 2 and programmatically clicks on the former; the Segment Button gets properly highlighted. But querying must take care of possible Shadow DOM.

**Additional Context**
N/A

**Comment by ghybs** [comment]
Hi,

Thanks for your message!

To answer the primary sense of your question, I use the `<ion-segment-button>` exactly like I would do for an `<input type="radio" />`.

But thinking further about it and giving more sense to your question, it seems that I am misled by this analogy. If I understand correctly, the common practice in Ionic is to manage the segments button through their parent segment container? It seems that it indeed provides an elegant 2-way binding of the selected value and to execute a callback when it changes, but v4 has a "hole" compared to v3:

| `<input type="radio" />` | UI | Events |
| ---------- | ---------- | ---------- |
| User click / tap | Selected | `"click"` |
| Programmatic `.click()` | Selected | `"click"` |
| Programmatic `checked = true` | Selected | **None** |

This shows why the common practice is to programmatically click on the radio input.

| `<ion-segment-button>` v4 | UI | Events | `<ion-segment>` value | `<ion-segment>` events |
| ---------- | ---------- | ---------- | ---------- | ---------- |
| User click / tap | Highlighted | `"click"` + `"ionSelect"` | Selected button value | `"ionChange"` |
| Programmatic `.click()` | **Nothing** | `"click"` **only** | **No change** | **None** |
| Programmatic `checked = true` | Highlighted | `"ionSelect"` **only** | Selected button value | `"ionChange"` |
| Programmatic `value = newValue` | Highlighted | `"ionSelect"` **only** | newValue | `"ionChange"` |

For ion-segment-button v4, using the `"ionSelect"` event instead of `"click"` and setting the `checked` property instead of clicking, we can mimic the behaviour of the radio input.
But the Ionic way seems rather to manage it from the ion-segment value level.

For the sake of completeness, in v3 we could still use the programmatic click to modify the selected value and have the UI highlighted:

| `<ion-segment-button>` v3 | UI | Events | `<ion-segment>` model | `<ion-segment>` events |
| ---------- | ---------- | ---------- | ---------- | ---------- |
| User click / tap | Highlighted | Native `"click"` + Angular `"ionSelect"` | Selected button value | Angular `"ionChange"` |
| Programmatic `.click()` | Highlighted | Native `"click"` + Angular `"ionSelect"` | Selected button value | Angular `"ionChange"` |
| Programmatic `checked = true` | N/A | N/A | N/A | N/A |
| Programmatic `model = newValue` | Highlighted | Angular `"ionSelect"` only? | newValue | Angular `"ionChange"` |

I guess we could live with the current situation, although patching the ion-segment-button hole would improve the analogy with the radio input, and I guess it would also make it easier for UI testing?

**Comment by ghybs** [comment]
Example of UI testing use case: https://github.com/ionic-team/ionic/issues/15337

**Comment by manucorporat** [comment]
This is already fixed in rc.2!
