### ISSUE TITLE
[Ionic v4-beta.1] Flexbox properties not working anymore

### ISSUE THREAD

**Issue by marcelgoya** [ionic-team/ionic#14985]
My dynamic column height flex properties stopped working after upgrading to beta1. They working fine on beta0.

# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```

Ionic:

   ionic (Ionic CLI)          : 4.0.2 (/usr/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.1
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.4

System:

   NodeJS : v9.11.2 (/usr/bin/node)
   npm    : 6.2.0
   OS     : Linux 4.4

Environment:

   ANDROID_HOME : not set
```

**Describe the Bug**
The height: 100% seems to have stopped working with the latest beta.

**Steps to Reproduce**

**Related Code**

```
<ion-content> 
    <ion-grid> 
      <ion-row style="background-color: #e74c3c;">
        <ion-col>Alizarin!</ion-col>
      </ion-row>
 
      <ion-row style="background-color: #f1c40f;">
        <ion-col>Sunflower!</ion-col>
      </ion-row>
 
      <ion-row style="background-color: #9b59b6;">
        <ion-col>Amethyst!</ion-col>
      </ion-row>
 
    </ion-grid> 
</ion-content>
```

```

ion-scroll {
    display: flex;
    flex-direction: column;
}

ion-grid {
    padding: 0;
    height: 100%;
}

ion-row {
    flex: 1;
}

```

**Expected Behavior**
The total row height should be 100% and each row should have a dynamic height. 

**Additional Context**

**Comment by peterpeterparker** [comment]
Same here, all the styling I developed for beta.0 regarding flex doesn't work anymore in beta.1

**Comment by marcelgoya** [comment]
@peterpeterparker Also, exactly the same styling worked for v3 and below as well ...

**Comment by peterpeterparker** [comment]
@marcelgoya not 100% the same, I have to custom made a couple of changes for beta.0 but they doesn't work anymore in beta.1

**Comment by peterpeterparker** [comment]
@marcelgoya I mean per definition a beta software is a beta software

if you wish to have a more stable core you should then maybe had wait for a release candidate or even later stage I guess

P.S.: https://en.wikipedia.org/wiki/Software_release_life_cycle#Beta definition: "Beta phase generally begins when the software is feature complete but likely to contain a number of known or unknown bugs"

**Comment by marcelgoya** [comment]
@peterpeterparker Alright, then per definition its still classified as alpha then because there is a lot of small stuff still missing like correct platform detection, proper css element styling  etc ...

**Comment by peterpeterparker** [comment]
@marcelgoya as you wish

**Comment by peterpeterparker** [comment]
As https://github.com/ionic-team/ionic/issues/14996 for me this issue would also be resolve with the PR https://github.com/ionic-team/ionic/pull/15012 I did submit
