### ISSUE TITLE
[Ionic v4] Select Option not showing data with ngFor

### ISSUE THREAD

**Issue by DasCode94** [ionic-team/ionic#14981]
# Bug Report

**Ionic Info**

**Ionic**:

   ionic (Ionic CLI)          : 4.0.3
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

**Cordova**:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

**System**:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.3 (/usr/bin/node)
   npm               : 5.6.0
   OS                : Linux 4.15

**Describe the Bug**
I am trying to dynamically populate the select list using ngFor.  The select is showing the proper number of option but the text for it is blank. I tried iterating the same array on a list and it's working perfectly.

**Related Code**

**The HTML Code**

```html
<ion-item>
      <ion-label>Cryptocurrency</ion-label>
      <ion-select>
        <ion-select-option *ngFor="let crytpo of cryptoList" [value]="crypto">{{ crypto }}</ion-select-option>
      </ion-select>
 </ion-item>
```

**The Page/Component Code**

```
export class HomePage {

  cryptoList: string[] = [
    "Bitcoin",
    "Ethereum",
    "Bitcoin Cash",
    "Ripple",
    "Litecoin"
  ];
  constructor( ) {
  }
}
```

**Expected Behavior**
Should show the list of Cryptocurrency in the select list.

**Comment by Sprauch** [comment]
<ion-select-option *ngFor="let **crytpo** of cryptoList" [value]="crypto">{{ crypto }

There is a typo.

**Comment by mhartington** [comment]
As @Sprauch stated, there is spelling error in your template. 

```
        <ion-select-option *ngFor="let crytpo of cryptoList" [value]="crypto">{{ crypto }}</ion-select-option>
```
