### ISSUE TITLE
[Ionic v4] Set ion-scroll div.scroll-inner height to 100%

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#14996]
**Ionic Info**
@ionic/angular: "4.0.0-beta.1"

**Describe the Feature Request**
I would like to set the height of `ion-scroll div.scroll-inner` to 100% like it's content parent

Without adding this, it would not possible to add children to an `ion-scroll` with relative height in percent (see screenshots)

**Screenshots**

<img width="938" alt="capture d ecran 2018-08-02 a 16 40 04" src="https://user-images.githubusercontent.com/16886711/43591197-0ec7f64e-9673-11e8-84ed-42195c7e3b25.png">

<img width="939" alt="capture d ecran 2018-08-02 a 16 40 12" src="https://user-images.githubusercontent.com/16886711/43591201-12056972-9673-11e8-948b-5bcab9b43461.png">

**Update**

At first I thought this should be solved with a new variable but actually setting `height: 100%` solves it

**Comment by GuilhermeBCC** [comment]
Taking advantage.. add a CSS4 var to text-align in ion-input and ion-textarea

**Comment by abalad** [comment]
same issue here

**Comment by manucorporat** [comment]
Fixed in master thanks to the refactored ion-scroll, .scroll-inner is not longer a thing

**Comment by peterpeterparker** [comment]
All good with v4.0.0-beta2, thx a lot 👍
