### ISSUE TITLE
Ionic 3.20.0 to slow startup on Android

### ISSUE THREAD

**Issue by jimonreal** [ionic-team/ionic#14990]
Good day everyone,

I am quite new with Ionic, but when deploying the app to my phone, the startup is too slow.
I added different options like --prod --optimizejs --aot  but nothing seems to work.

Is there any other option or something I should look first like modules I am using, and versions?

Any help I would be greatful

Best regards,
José

**Comment by manucorporat** [comment]
Upcoming version Ionic 4 fixes this
