### ISSUE TITLE
Cross-origin resource sharing (CORS) error triggered even with <access origin="*" />

### ISSUE THREAD

**Issue by bibounet** [ionic-team/ionic#14995]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)  : 4.0.3 (C:\Users\toto\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

**Describe the Bug**
Cross-origin resource sharing (CORS) error is triggered once I try to http get google.com for example.
These didn't happen on my Ionic 3 apps, but happen on ionic 4.

I used <access origin="*" /> on my ionic 3 app, but with a newly created ionic 4 app CORS seems to be forbidden. is there a clue to make it work?

error on logcat (android 7) :
```
SystemWebChromeClient: http://localhost:8080/: Line 0 : Failed to load https://www.google.com/?gws_rd=ssl: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

chromium: [INFO:CONSOLE(0)] "Failed to load https://www.google.com/?gws_rd=ssl: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.", source: http://localhost:8080/ (0)
```

**Related Code**
```
export class HomePage {

    public data: string;

    constructor(public http: HttpClient) {

        this.http.get('https://www.google.com/?gws_rd=ssl', { responseType: 'text' }).subscribe(
            (res: string) => this.data = res,
            error => this.data = JSON.stringify(error, null, 4))
    }

}
```

**Comment by ANDRES2A** [comment]
Im facing the same issue even though I have the 'Access-Control-Allow-Origin' header set on my backend

**Comment by bibounet** [comment]
As written here : 

https://ionicframework.com/docs/wkwebview/

> If it is not an possibility to implement or configure CORS in the server, there is a native plugin that can “proxy” the HTTP requests using native code, so CORS can be completely bypassed:
> 
> Read more here: [cordova-plugin-http](https://ionicframework.com/docs/native/http/). 


So the workaround is to use HTTP native (cordova) instead of HTTP from httpClient (angular)

* npm i @ionic-native/http@beta --save
* npm i @ionic-native/core@beta --save
* import { HTTP } from '@ionic-native/http/ngx'; (inside your service + app.module)
* constructor(private httpNative: HTTP) { }
* this.httpNative.get(url, {}, {}).then(data => { ... });
