### ISSUE TITLE
Ionic 4 - components are hidden inside the menu - CSS bug in the ion-menu component

### ISSUE THREAD

**Issue by maziTR** [ionic-team/ionic#14991]
# Bug Report

**Ionic Info**
Ionic:

   ionic (Ionic CLI)          : 4.0.3 (C:\Users\msbit\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

System:

   NodeJS : v8.11.2 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10

**Describe the Bug**
when calling a component inside the "ion-menu" badge, the component is invisible,
the solution I found is to give my implemented component a height property, but it need to be fixed from the system itself .

the "app-menu" was invisible until i gave it a height.

**Steps to Reproduce**
1. create a menu
2. create a component in your app
3. put the component in the component's module
 and import it to the page you will implement it in..
4. try to put the component inside the menu like the example below..
 you will not see it..

**Related Code**

**this is the html:**

```
<ion-tabs main id="main">
  <ion-tab label="Home" icon="home" href="/nav/(home:home)">
    <ion-router-outlet name="home"></ion-router-outlet>
  </ion-tab>
  <ion-tab label="About" icon="information-circle" href="/nav/(about:about)">
    <ion-router-outlet name="about"></ion-router-outlet>
  </ion-tab>
  <ion-tab label="Contact" icon="contacts" href="/nav/(contact:contact)">
    <ion-router-outlet name="contact"></ion-router-outlet>
  </ion-tab>
</ion-tabs>

  <ion-menu menu-id="main-menu" side="end" type="overlay" content-id="main">
    <app-menu class="menu-content"></app-menu>
  </ion-menu>
```

**Expected Behavior**
I should have seen the component..

**Comment by manucorporat** [comment]
Your component is missing the `.ion-page` class:
```
<app-menu class="ion-page menu-content"></app-menu>
```

**Comment by maziTR** [comment]
Thank you, that helped!
can somebody put this in the documentation for the next developers who will bump into this issue?
it happens a lot in ionic 4 components implementation (it has also fixed a modal's content view component we have)
