### ISSUE TITLE
[Ionic v4] ion-refresher is not working

### ISSUE THREAD

**Issue by samarthagarwal** [ionic-team/ionic#14992]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

System:

   NodeJS : v8.10.0 (/usr/local/bin/node)
   npm    : 5.3.0
   OS     : macOS High Sierra
```

**Describe the Bug**
Using ion-refresher in a blank Ionic project does not work. If I try pulling from the top, nothing happens. It works as if the ion-refresher is not even there. If I check the HTML of the page, I can see the ion-refresher component there. Check screenshot [here](http://prntscr.com/kds6xz).

**Steps to Reproduce**
1. Create a new Ionic v4 project - `ionic start ionictest blank --type=angular`
2. Open the project and run `ionic serve`.
3. Then go to the `home.page.html` and add the following markup.

```
<ion-content padding>
  <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
    <ion-refresher-content></ion-refresher-content>
  </ion-refresher>
  <ion-list>
    <ion-item *ngFor="let i of arr">
      {{ i }}
    </ion-item>
  </ion-list>
</ion-content>
```
4. Add the following code to your `home.page.ts`
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {

  arr = [1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,];

  doRefresh(event){
    console.log("Refreshing...");
  }

}
```

5. Now try to refresh the page by pulling it down from the top. It does not work.

**Expected Behavior**
The ion-refresher should try to refresh the page and the function `doRefresh()` should be invoked. But it does not happen.

**Comment by Defee** [comment]
+1 I have the same problem with refresher in beta.

**Comment by garygrossgarten** [comment]
@samarthagarwal @Defee  Have you tried to give the `ion-refresher` component the property` [disabled]="false"` to enable it?

**Comment by garygrossgarten** [comment]
@samarthagarwal Yes, of course. This is most likely a bug. But the workaround helps for the moment.

**Comment by praveen252elite** [comment]
works with disabled="false"

**Comment by manucorporat** [comment]
THis is fixed in master, ion-refresher is now enabled by default!
