### ISSUE TITLE
Top padding required for standalone PWA

### ISSUE THREAD

**Issue by corysmc** [ionic-team/ionic#15000]
# Bug Report

**Ionic Info**
```
@ionic/core@4.0.0-beta.1
```

**Describe the Bug**
padding is off for PWAs, content is all shifted up

**Steps to Reproduce**
1. Include necessary header info for standalone pwa (see related code).
2. Save to home screen
3. Launch PWA from home screen
4. observe padding

**Related Code**
```
  <meta name="viewport" content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="theme-color" content="#131b28">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-title" content="Sworkit">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <link rel="apple-touch-startup-image" href="/assets/img/launch.png">
  <link rel="apple-touch-icon" href="/assets/icon/apple-touch-icon.png">
  <link rel="icon" type="image/x-icon" href="/assets/icon/favicon.ico">
  <link rel="manifest" href="/manifest.json">
```

**Expected Behavior**
app fills screen within a "safe area" when in standalone mode with "black-translucent" status-bar. 
I'm thinking extra padding needs to be added to the ion-header.

**Additional Context**
![image](https://user-images.githubusercontent.com/6452188/43604849-0a1e97ca-9654-11e8-943e-6144c5658798.png)

![image](https://user-images.githubusercontent.com/6452188/43604898-222f4b48-9654-11e8-9ef8-77d443b807e7.png)

**Comment by skol-pro** [comment]
Having the same issue. Fixed ? How to get the "patch" ?

**Comment by corysmc** [comment]
It’s on master, but should be available in the next npm version (beta.3 is my guess)

**Comment by skol-pro** [comment]
Do you know when does this next beta version will be released ?
