### ISSUE TITLE
[v4 JS] ion-ripple effect broken

### ISSUE THREAD

**Issue by ghybs** [ionic-team/ionic#15008]
# Bug Report

**Ionic Info**
Directly using @ionic/core version 4.0.0-beta.1 from CDN (e.g. unpkg or jsdelivr)
Tried on Chrome and Firefox.

**Describe the Bug**
In MD mode, all ion elements have lost their ripple effect (`<ion-button>`, `<ion-item button>`…).
In iOS mode, buttons have a hover effect, but they no longer have their subtle "taint" effect.

**Steps to Reproduce**
1. Go to https://beta.ionicframework.com/docs/api/ripple-effect/ (defaults in MD mode)
2. Click on any of the buttons of the device simulator.
3. No ripple effect on click.

**Related Code**
- v4.0.0-beta.1 (MD mode): https://next.plnkr.co/edit/dXIqMtK1jX91BuLS (no visual effect at all)
- v4.0.0-beta.1 (iOS mode): https://next.plnkr.co/edit/CkjufAerAIEYj7QH (no tainting)
- v4.0.0-beta.0 (MD mode): https://next.plnkr.co/edit/ghWyz0OyaT2bKkSA (works in Chrome, slight tainting in FF)
- v4.0.0-beta.0 (iOS mode): https://next.plnkr.co/edit/LuYKBQxtZ6myXQ7f (works)
- v4.0.0-alpha.8 (MD mode): https://next.plnkr.co/edit/5efKvrZLaPjTOCiY (works in Chrome, slight tainting in FF)
- v4.0.0-alpha.8 (iOS mode): https://next.plnkr.co/edit/aK27GGzQctBq4Saj (works)
- v4.0.0-alpha.7 (MD mode): https://next.plnkr.co/edit/ZjmATa7Q5eKtci8f (works)
- v4.0.0-alpha.7 (iOS mode): https://next.plnkr.co/edit/ZPsoaLpNEebkPQga (works)

**Expected Behavior**
On user click / tap, buttons should have their ripple effect in MD mode, and a "taint" effect in iOS mode.

**Additional Context**
N/A

**Comment by manucorporat** [comment]
This is fixed in master! Thanks for reporting the issue
