### ISSUE TITLE
datacloneerror: failed to execute 'postmessage' on worker

### ISSUE THREAD

**Issue by avramanaareddy** [ionic-team/ionic#15004]
I am working to view the pdf file. I used npm install ngx-document-view component and then tried executing it, it gives me the following error. I am not able to find what is the reason. can you please solve it. This one I am getting on ionic 4

<img width="1440" alt="screen shot 2018-08-02 at 9 44 07 pm" src="https://user-images.githubusercontent.com/8145899/43619720-40d3a2bc-969d-11e8-9a9a-2813e59682e4.png">

**Comment by avramanaareddy** [comment]
The issue is coming on chrome and safari both the browsers.

**Comment by mhartington** [comment]
Hi there! This issue does not appear to be an issue with the framework itself, so it will be closes. Please review your issue and open a new ticket on the appropriate project repository, or feel free to post a question on the [Ionic Forum](http://forum.ionicframework.com). Thanks!
