### ISSUE TITLE
icon color always black only in firefox (works on chrome) @ionic/angular 4.0.0-beta.1

### ISSUE THREAD

**Issue by Nightbr** [ionic-team/ionic#15009]
Hey,

# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (/home/nightbringer/.nvm/versions/node/v8.11.3/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.1
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.3 (/home/nightbringer/.nvm/versions/node/v8.11.3/bin/node)
   npm               : 5.6.0
   OS                : Linux 4.15

Environment:

   ANDROID_HOME : /home/nightbringer/Android/Sdk

```

**Describe the Bug**

In ion-button, or ion-label, it seems to be the icon color is always black but in CSS it shows #FFFFFF color is calculated. Even more weird, it is working well on Chrome browser.

Firefox on left, Chrome on right side.
![image](https://user-images.githubusercontent.com/4228646/43632456-808da2a4-9706-11e8-96c5-ba3a3bd129a7.png)

Firefox Debug element
![image](https://user-images.githubusercontent.com/4228646/43632828-8bc1bff6-9707-11e8-9d0a-f006457df836.png)

**Steps to Reproduce**
1. Create a page with ion-label and ion-button 
2. Add ion-icon in them
3. On firefox icon color is always black
4. On Chrome icon color is inherited properly

**Related Code**

```
 <ion-item>
        <ion-label>
          <ion-icon name="mail" slot="start" class="text-primary"></ion-icon>
          {{ 'LOGIN.EMAIL' | translate }}
        </ion-label>
        <ion-input type="email" name="email" formControlName="email"></ion-input>
      </ion-item>
```

or in button

```
<ion-button expand="block" type="submit" [disabled]="!loginForm.valid">
        {{ 'LOGIN.SIGN_IN' | translate }}
        <ion-icon name="log-in" slot="end"></ion-icon>
      </ion-button>
```

**Expected Behavior**

On Firefox the icon color must be the correct one.

If you need more debug/info don't hesitate to ask!

Thanks!

**Comment by manucorporat** [comment]
This is already fixed in master! beta.2 will have the fix! Thanks for reporting the issue!
