### ISSUE TITLE
Environment file support

### ISSUE THREAD

**Issue by Abhi0725** [ionic-team/ionic#15006]
# Environment file support (Like Laravel .env file)

**Background**
I found a need of it since the beginning when I started working with Ionic. But the real problem occurred yesterday when I made a prod build of the app tested on my phone but when I uploaded it to play store people started complaining that the app stuck on splash screen. 
I later found that I forgot to change the routes to production (why it worked for me then at first? well I was on my local wifi).

**Env File**

The idea is to have some environment variable file which is picked with build commands. Say, I run

```
ionic cordova build android --prod
```
It should automatically pick the production env file. While for build command without prod flag it can pick dev env file.

The env file for prod may look something like:

```
API_BASE_URL=http://prod.example.com
```
While for dev:

```
API_BASE_URL=http://localhost:8000
```

We can have staging or testing files too and there can be other environment related variables in these files.

**Comment by artemtool** [comment]
Ionic uses angular-cli under the hood and there is such possibility.
Check this: https://github.com/angular/angular-cli/wiki/stories-application-environments

Use something like this  to provide env variables: 
`ionic build --configuration=production `

**Comment by artemtool** [comment]
If i am not mistaken ionic-cli uses angular-cli under the hood.
Check this https://github.com/angular/angular-cli/wiki/stories-application-environments.
To provide env variable you need something like this:
`ionic build --configuration=production`

**Comment by mhartington** [comment]
This is supported in Angular projects in V4. 
V3 also recently got env support as well. 

Going to close this as this exists for V3, and with V4, we'll be proxying this out to the underlying CLI/framework tools. Thanks
