### ISSUE TITLE
[Ionic v4] Hamburger menu icon not rendered after a few root navigation

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#15010]
**Ionic Info**
@ionic/angular: "4.0.0-beta.1"

**Describe the Bug**
As you could see in the following video, the hamburger menu icon get lost aka is not rendered randomly anymore  after a few root navigation

https://www.dropbox.com/s/60ikv1ho36o803z/hamburger_menu.mov?dl=0

**Expected Behavior**
An icon always rendered

**Code**

As in the documentation

    <ion-header>
      <ion-toolbar>
        <ion-buttons slot="start">
        <ion-menu-toggle>
          <ion-button>
            <ion-icon slot="icon-only" name="menu"></ion-icon>
          </ion-button>
         </ion-menu-toggle>
       </ion-buttons>
    
       <ion-title>WHATEVER</ion-title>
    </ion-toolbar>
    </ion-header>

**Comment by M00dl3** [comment]
Duplicate of #14848

**Comment by manucorporat** [comment]
@peterpeterparker i can't reproduce, can someone debug it a little bit? what is causing it to not be render?

**Comment by peterpeterparker** [comment]
@manucorporat I tested a bit more, I have the feeling that you effectively can't reproduce the problem with a blank light app, I had to "charge" a bit more data (enhancing a loop from 10 to 100) in order to be able to reproduce it

to try it, you could clone following repo

    git clone https://github.com/peterpeterparker/ionic-hamburger-menu

then run

    ionic serve

and debug the app in Chrome and be sure to toggle to the device view, like iPhone 6/7/8

like reported by @M00dl3, it looks like time to time the `icon-inner` isn't rendered

it doesn't happens just in the hamburger menu but generally speaking with the icons

I was able to reproduce the problem with this demo repo and doing so, here a couple of screenshots 

<img width="1002" alt="capture d ecran 2018-08-12 a 11 27 19" src="https://user-images.githubusercontent.com/16886711/44000618-b1e52eac-9e23-11e8-9721-2d1644ae0e88.png">

<img width="1003" alt="capture d ecran 2018-08-12 a 11 26 12" src="https://user-images.githubusercontent.com/16886711/44000620-b673093a-9e23-11e8-9c43-52a14ea02dc2.png">

**Comment by peterpeterparker** [comment]
@manucorporat I've maybe an idea why you we rent's able to reproduce the problem, did you explicitly test on or selected an iOS device in your Chrome debug, like iPhone 6/7/8, in order to try to reproduce the problem?

I've the feeling that this may **only happens on iOS**

@M00dl3 do you have the same observation?

**Comment by M00dl3** [comment]
@peterpeterparker I do not share your observations. I had my issue on my Android phone, my screencapture is also recorded from that build.

Tonight I will retest to check if the issue still persists for me on the latests builds.

**Comment by peterpeterparker** [comment]
@M00dl3 thx for the feedback and for tonight's feedback ;)

one on the other, for sure I still do face the problem

**Comment by peterpeterparker** [comment]
I think that problem has been solved since a while therefore I close the issue :)
