### ISSUE TITLE
Beta 1 - string.prototype.startswith polyfill does not work in IE 11

### ISSUE THREAD

**Issue by Ajji11** [ionic-team/ionic#15016]
**Describe the Bug**
Although a polyfill exists on the project a .startswith function is throwing a 'Syntax' error in IE 11, preventing the website from loading.  #14922 was closed with a fix but it still doesn't work in Beta1.

**Steps to Reproduce**
Include AWS-Amplify / AWS-Amplify-Angular in Angular project and use one of the modules. It adds ionic/core dependency which has this function causing the issue. In my case I used AmplifyService.api().

**Related Code**
```
function configFromURL() {
    const config = {};
    const win = window;
    win.location.search.slice(1)
        .split('&')
        .filter(entryText => entryText.startsWith('ionic:'))
        .map(entryText => entryText.split('='))
        .forEach(entry => {
        config[entry[0].slice(6)] = decodeURIComponent(entry[1]);
    });
    return config;
}
```
**This line is causing the break: .filter(entryText => entryText.startsWith('ionic:'))**

**Expected Behavior**
Polyfill should work and website should load in IE11

**Comment by manucorporat** [comment]
Should be fixed in beta.2
