### ISSUE TITLE
Material Desing V2

### ISSUE THREAD

**Issue by nicobytes** [ionic-team/ionic#15020]
Hello!

Now the material design system is version 2
- https://www.youtube.com/watch?v=1Dh8ZBQp9jo
- https://material.io/design/components/buttons.html#contained-button
- https://uxdesign.cc/previewing-material-design-2-0-ec0215f0588f

Will the be updated in this lib for use?

**Comment by mhartington** [comment]
Hi there! We're constantly checking to make sure our Material Design implementation is correct is follow the guidelines. I am going to close this issue as material design is constantly updating and tracking particular updates is not feasible. Thanks!
