### ISSUE TITLE
ionic hangs on splash when run ios 10

### ISSUE THREAD

**Issue by bachlongkocanh** [ionic-team/ionic#15021]
# Bug Report

**Ionic Info**
```

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 browser 5.0.3 ios 4.5.4 osx 4.0.1 windows 5.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.2 
    Node       : v8.10.0
    npm        : 6.1.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3 Build version 9E145 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Describe the Bug**
I create app have scanQR, copy,file. App work for android, web, ios 11.3. But when i build with `--prod`, this hangs on splash on ios 11.2 or lower. On debug of safari:
_#SyntaxError:Cannot declare a let variable twice: 't'.
#ReferenceError: Can't find variable: webpackJsonp._
I build nomal not `--prod` then work.
**Please help me**

**Comment by mhartington** [comment]
Hi there! It appears this isn't really an issue, and more of a question, so Im going to close this. Please check out the [forum](https://forum.ionicframework.com) as this is a better place for questions. Thanks!
