### ISSUE TITLE
v4 Docs: ion-virtual-scroll

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic#15032]
Rendering the sample incorrectly.

Also, mark internal attributes as hidden or provide information about them. see domRender as an example.

**Comment by kael** [comment]
Odd way to report a bug.

**Comment by chrisgriffith** [comment]
[image: Screen Shot 2018-08-05 at 9.31.00 PM.png]
Here is the rendering issue.

**Comment by kael** [comment]
I can't see no image.

What I meant is that you can't open as many tickets describing alleged issues, even more when described in a laconic manner, without even giving some context as suggested by the template you're ignoring.

I'm just a Stencil & Ionic user, but I feel like you should revisit the way you report bugs.

The Ionic team is drawn under more than a thousand of tickets, I'm not sure you're taking the best approach.

For a free software, I would not be able to claim, to demand anything to the Ionic team in such a manner.

**Comment by chrisgriffith** [comment]
Thank you for the concerns, but I am not **demanding** anything from the team. I am simply contributing to the project but denoting problems. I have been a contributor to the project for some time, and in fact, written several books on it. I will let the team triage and sort the issues. I actually have spoken with team members about reporting issues like this, and they informed me to proceed in this manner. 

I ignored the template as it really is for code specific issues. Since these are all documentation issue, which cli I have installed was of no matter to the report

I would have happily tried to fix them (for the solutions I know), but the docs are more complex than they appear. More portions of the docs are auto-generated from the component's themselves, so it is not as simple as editing some HTML and calling it a day. 

As to the image, reattaching so you can get a sense of why I am reporting this error.
![screen shot 2018-08-05 at 9 31 00 pm](https://user-images.githubusercontent.com/527875/43723529-ba456034-994c-11e8-988f-017e6a385bba.png)
