### ISSUE TITLE
this.platform.ready() spent long time to get result when App start  in IOS

### ISSUE THREAD

**Issue by bigthing33** [ionic-team/ionic#15037]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.10.0
    npm        : 3.10.10 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4.1 Build version 9F2000 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Describe the Bug**
Until I had to release the IOS APP, everything worked fine. When I run the ios app, the app always displays the splasscrenn page, which takes about a minute to go to home page. I have used --prod --release is still the same.

**Steps to Reproduce**
1. sudo ionic cordova build ios --prod --release
2. open Xcode
3. build and run App on device
4. The app always displays the splasscrenn page, which takes about a minute to go to home page

**Related Code**

```javascript
    console.log('MyApp constructor this.platform.ready() start')
    this.platform.ready().then(() => {
      console.log('MyApp constructor this.platform.ready() result', this.platform)
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      this.statusBar.styleDefault();
      this.splashScreen.hide();
})
```

**Expected Behavior**
I hope that the ios app can be started in about 5 seconds, just like the android app.

**Additional Context**
- the logs from xcode
```MyApp
2018-08-04 19:30:33.314857+0800 AppName[1867:129784] MyApp ngOnInit initApp complete
2018-08-04 19:31:45.075118+0800 AppName[1867:129784] MyApp ngOnInit this.platform.ready() [object Object]
[object Object]

```

```ms
2018-08-04 19:30:28.907877+0800 AppName[1867:129784] [CDVTimer][console] 0.100970ms
2018-08-04 19:30:28.908324+0800 AppName[1867:129784] [CDVTimer][handleopenurl] 0.301003ms
2018-08-04 19:30:28.913296+0800 AppName[1867:129784] [CDVTimer][intentandnavigationfilter] 4.861951ms
2018-08-04 19:30:28.913530+0800 AppName[1867:129784] [CDVTimer][gesturehandler] 0.156045ms
2018-08-04 19:30:28.956675+0800 AppName[1867:129784] [CDVTimer][splashscreen] 43.056965ms
2018-08-04 19:30:28.959238+0800 AppName[1867:129784] [CDVTimer][keyboard] 2.326965ms
2018-08-04 19:30:28.964230+0800 AppName[1867:129784] [CDVTimer][ble] 4.819036ms
2018-08-04 19:30:28.964400+0800 AppName[1867:129784] [CDVTimer][TotalPluginStartup] 56.701064ms
2018-08-04 19:30:32.259342+0800 AppName[1867:129784] Ionic Native: deviceready event fired after 1222 ms
```

**Comment by bigthing33** [comment]
I think it may be because my build failed caused this problem, I can only build successfully after the first time, and always the build fails.
There is my solution：
- sudo ionic cordova platform rm ios
- sudo rm -rf node_moduls
- npm install 
- ionic cordova build ios --prod --release
- open xcode to build distrbution app

**Comment by bigthing33** [comment]
The first time I ran the app, everything worked fine, but it took about a minute or so to run again. Finally, I had to use an alternative method.
```
 hideSplash() {
    try {
      setTimeout(() => {
        console.log('MyApp hideSplash 3500 timeout')
        this.statusBar.styleDefault();
        this.splashScreen.hide();
        PlatformUtil.sPlatform = AppConstant.PLATFORM.IOS;
      }, 3500)
    } catch (e) {
      console.error('MyApp hideSplash error', e)
      this.hideSplash()
    }
  }


 ngOnInit(): void {
    console.log('MyApp ngOnInit start');
    this.hideSplash();

  }
```

**Comment by mhartington** [comment]
`ngOnInit` does not necessarily mean that the native APIs are ready to be called. `platform.ready() ` is recommended as it resolves when cordova is ready. What this sounds like is the app could be rather large and takes a while to parse. If your app is not using lazy-loading, I would suggest making those changes first to only load the code needed to start the app. This can reduce the start up time and make the splash-screen hide faster. I would suggest moving the conversation/question to the [ionic forum](http://forum.ionicframework.com)
