### ISSUE TITLE
[Ionic v4] First card behind toolbar if ion-content has no padding

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#15039]
**Ionic Info**
@ionic/angular: "4.0.0-beta.1"

**Describe the Bug**
If no `padding` is specified for the `ion-content` then the first `ion-card` will be partially rendered behind the `ion-toolbar`

**Expected Behavior**
The first `ion-card` should not be behind the toolbar regardless if the content has or not padding

**Code**

    git clone https://github.com/peterpeterparker/first-ion-card

**Screenshot**

<img width="298" alt="capture d ecran 2018-08-04 a 14 59 08" src="https://user-images.githubusercontent.com/16886711/43676741-4f7a8b72-97f7-11e8-8d61-586064f6ce9f.png">

**Comment by manucorporat** [comment]
Confirmed this is already fixed thanks to the .scroll-inner refactor!!

**Comment by peterpeterparker** [comment]
All good with v4.0.0-beta2, thx a lot 👍
