### ISSUE TITLE
Ionic 4.0.3 + plugin Globalization = ERROR TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by Anthony2539** [ionic-team/ionic#15035]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.0.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : ios 4.5.5
```

**Describe the Bug**
i installed the plugin Globalization and i added this plugin in my app's module, when i run my app, i have this error :
```
index.js:275 Uncaught TypeError: Object(...) is not a function
    at index.js:275
    at Object../node_modules/@ionic-native/globalization/index.js (index.js:402)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/app.module.ts (app.firebase.config.ts:8)
    at __webpack_require__ (bootstrap:81)
    at Object../src/main.ts (environment.ts:15)
    at __webpack_require__ (bootstrap:81)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:81)
    at checkDeferredModules (bootstrap:43)
```
**Steps to Reproduce**
1. Install plugin Globalization
2. Add in your app's module
3. Run app with ionic serve

**Comment by peterpeterparker** [comment]
1. Have you installed its ionic-native wrapper in version >= v5-beta
2. Did you add `/ngx` to your imports like `import { Globalization } from '@ionic-native/globalization/ngx`;

**Comment by Anthony2539** [comment]
1. I installed the last version of this plugin = "@ionic-native/globalization": "^4.11.0" and i use "@ionic-native/core": "5.0.0-beta.14"
2. I imported like that ``` import { Globalization } from '@ionic-native/globalization';```

**Comment by peterpeterparker** [comment]
@Anthony2539 so here you go, that's your problem

try as I described

doc for reference: https://beta.ionicframework.com/docs/native/

**Comment by Anthony2539** [comment]
i installed the plugin like this =>
``` ionic cordova plugin add cordova-plugin-globalization ```
 ``` npm install --save @ionic-native/globalization ```

and when i imported like that ``` import { Globalization } from '@ionic-native/globalization/ngx';``` in my app.module the import doesn't work.

I forgot something?

**Comment by peterpeterparker** [comment]
@Anthony2539 I mean, again, like I said above twice, install only wrappers >= v5!

 "@ionic-native/globalization": "^4.11.0" => not good for ionic 4
 "@ionic-native/globalization": "^5.0.0-beta.14" = good for ionic 4

**Comment by Anthony2539** [comment]
@peterpeterparker sorry i didn't understand, my bad.
It work, thank you i close the issue.
