### ISSUE TITLE
[Ionic v4] slidesPerView does not work on ion-slides unless window is resized

### ISSUE THREAD

**Issue by ivas123** [ionic-team/ionic#15044]
# Bug Report

**Ionic Info**
@ionic/angular: "4.0.0-beta.1"

**Describe the Bug**
Setting  slidesPerView in [options] on ion-slides does not work. Only after the window is resized then do I see the correct amount of slides for the corresponding view. Otherwise, I am only able to see one slide per view. 

**Related Code**
```
<ion-slides [options]="slideOpts">
    <ion-slide>
        1
    </ion-slide>
    <ion-slide>
        2
    </ion-slide>
    <ion-slide>
        3
    </ion-slide>
    <ion-slide>
        4
    </ion-slide>
    <ion-slide>
        5
    </ion-slide>
    <ion-slide>
        6
    </ion-slide>
    <ion-slide>
        7
    </ion-slide>
</ion-slides>

  slideOpts = {
    loop: false,
    slidesPerView: 6,
    slidesPerGroup: 6,
    grabCursor: true,
    spaceBetween: 30
  };
```

**Expected Behavior**
I should be able to have slidesPerView active without having to resize the window.

**Comment by ivas123** [comment]
I discovered a workaround. We can use the Swiper angular wrapper instead which seems to be more updated than the ionic v4 version. `npm i ngx-swiper-wrapper`

  <div class="swiper-container" [swiper]="slideOpts" >

```
  <div class="swiper-wrapper">
    <div class="swiper-slide">
      <p>
        test1
    </p>
  </div >
  <div class="swiper-slide">
    <p>
      test1
  </p>
</div>

<div class="swiper-slide">
  <p>
    test1
</p>
</div>
<div class="swiper-slide">
  <p>
    test1
</p>
</div>
<div class="swiper-slide">
  <p>
    test1
</p>
</div>
<div class="swiper-slide">
  <p>
    test1
</p>
</div>
<div class="swiper-slide">
  <p>
    test1
</p>
</div>
```
```
    this.slideOpts = {
      observer: true,
      observeParents: true,
      slidesPerView: 6
    }
```

**Comment by sean-perkins** [comment]
@ivas123 Add this style block to the page/component you are rendering the `ion-slides` component in:

```
.swiper-slide {
    width: auto;
}
```

**Comment by ivas123** [comment]
Thanks. Will do!
