### ISSUE TITLE
[Ionic v4] Type definition of InfiniteScroll event

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#15049]
**Ionic Info**
@ionic/angular: "4.0.0-beta.1"

**Describe the Feature Request**
As displayed in the breaking changes list, https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md, the `ionInfinite` get an `event` as parameter with which the scrolling could/should be stopped

This `event` is provided, correct me if I'm wrong, without any typings definition

    doInfinite(event: any) {
        event.target.complete();
    }

**Proposal solution**
As already reported regarding other types, https://github.com/ionic-team/ionic/issues/14784, I would like to have the ability to use a type definition for this event too, something like

    doInfinite(event: InfiniteScrollEvent) {
        event.target.complete();
    }

**Comment by ashinpaugh** [comment]
Not sure if this is what you're looking for, but here's what I've been using.

```
/**
 * Defines properties that really Ionic should be shipping with their components.
 * Built initially for the IonInfiniteScroll's ionInfinite event.
 *
 * @author Austin Shinpaugh
 */
export interface AsyncEvent extends CustomEvent {
  target: EventTarget & {
    /**
     * Disable the ability to trigger another async event.
     */
    disabled: boolean;

    /**
     * How far the user should have to scroll before loading the next chunk of content.
     */
    threshold: string;

    /**
     * The position of the infinite loading component.
     *
     * Possible values are top or bottom.
     */
    position: string;

    /**
     * Ends the async loading animation.
     */
    complete(): void;
  };
}
```

**Comment by peterpeterparker** [comment]
I guess as https://github.com/ionic-team/ionic/issues/14784 I recently closed, I could also close this one as I was able to migrate without it and as it seems that no one else is interested of having access to an exposed type definition
