### ISSUE TITLE
Ionic v4 datetime binded to reactiveform

### ISSUE THREAD

**Issue by jchapelle** [ionic-team/ionic#15059]
# Bug Report

```
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (/opt/node-v10.5.0-linux-x64/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0

System:

   NodeJS : v10.5.0 (/opt/node-v10.5.0-linux-x64/bin/node)
   npm    : 6.2.0
   OS     : Linux 4.15

Environment:

   ANDROID_HOME : not set
```

**Describe the Bug**
Ion-datimetime cannot be binded properly to reactive form control. ion-input can be binded to the form but ion-datetime value are not binded properly to the form. The form control is not updated when ion-datetime is changed ...

**Steps to Reproduce**
Create a simple reactive form with one single control.
Bind the control to a template ion-datetime

**Comment by jekes** [comment]
Same result for me

**Comment by MrSparklle** [comment]
Using Ionic Framework            : @ionic/angular 4.0.0-beta.5

Ionic The `ion-datetime` has been binded properly to form control. But instead of a ISO-8601 format like '2017-08-21T00:00:00' it persist a object like this:

```
{
  "dateBk": {
    "day": { "text": "21", "value": 21, "columnIndex": 0 },
    "month": { "text": "Aug", "value": 8, "columnIndex": 1 },
    "year": { "text": "2017", "value": 2017, "columnIndex": 2 }
  }
}
```

**Comment by jchapelle** [comment]
It works and can be closed ! Thanks

**Comment by aronrodrigues** [comment]
In which version it is working?
In @ionic/angular 4.0.0-beta.13 ion-datetime returns null every time.
