### ISSUE TITLE
Can't create new project

### ISSUE THREAD

**Issue by uda1099** [ionic-team/ionic#15052]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

**Expected behavior:**

When I try to create a new project with cordova integration, I get the error: 
Error: ENOENT: no such file or directory, mkdir 'C:\Users\Admin\AppData\Local\Temp;C:'

**Steps to reproduce:**

npm install -g ionic cordova
ionic start test blank

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
C:\Users\Admin\Desktop\teste>ionic info
[ERROR] Error loading ionic-angular package.json: Error: Cannot find module 'ionic-angular/package'
[ERROR] Error loading @ionic/app-scripts package.json: Error: Cannot find module '@ionic/app-scripts/package'

Ionic:

   ionic (Ionic CLI)  : 4.0.3 (C:\Users\Admin\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : not installed
   @ionic/app-scripts : not installed

System:

   NodeJS : v10.7.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.1.0
   OS     : Windows 10



```

**Comment by jaggu07** [comment]
look at this for reference

The Ionic CLI has an update available (3.20.0 => 4.0.3)!

[WARN] No write permissions for global node_modules--automatic CLI updates are 

       disabled.
       To fix, see https://docs.npmjs.com/getting-started/fixing-npm-permissions
       
       Or, install the CLI update manually:
       
       npm i -g ionic@latest
       


cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v6.9.0
    npm               : 3.10.8 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4.1 Build version 9F2000 

Environment Variables:

    ANDROID_HOME : /Users/jaggu/Library/Android/sdk

Misc:

    backend : pro



follow this procedure
[https://ionicframework.com/docs/v1/guide/installation.html](url)

**Comment by uda1099** [comment]
Hey @jaggu07 thanks for the reply, but I've already uninstalled and installed again Node, Ionic and Cordova and it's still giving me the same error...

**Comment by jaggu07** [comment]
can u send me all the commands u have used for installation @uda1099
