### ISSUE TITLE
ionic v4 platform specify like ionic v3

### ISSUE THREAD

**Issue by windwp** [ionic-team/ionic#15051]
# Feature Request
this.platform.ready().then(() => {
 console.log(this.platform.platforms());
})

In ionic v4 :

When I run it in chrome desktop browser and chrome mobile browser it always displays ["android"]

In ionic v3 :

If i run in chrome desktop it will displays ["core"]
and in chrome mobile browser it will display   ["mobile", "android", "mobileweb"]

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
   ionic (Ionic CLI)          : 4.0.3 (C:\Users\Admin\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1
```

**Comment by bgies** [comment]
When I run it in the chrome desktop (on windows) I get [android,tablet]

**Comment by brandyscarney** [comment]
Thank you for the issue! I am going to close this issue and merge it into #15165 to keep all platform issues in one.
