### ISSUE TITLE
Page refreshing when navigate inside tabs

### ISSUE THREAD

**Issue by danial060696** [ionic-team/ionic#15050]
# Bug Report

**Ionic Info**
ionic V4.0.2

**Describe the Bug**
I’m getting problem of page refreshing when navigate to others tabs. for example I got 3 tabs (homepage, account, feedback) then inside account tabs got a link that navigate to other page (give name as detail page) then I go back to account tabs by pressing ion-back-button inside detail page. Then, when I want to navigate to feedback tabs, the page will become white like refreshing and go to homepage by default.

**Steps to Reproduce**
1. Go to any tabs and create one button or link that will navigate you to other page lets say detail page.
2. Then click that link/button and navigate to detail page.
3. Inside detail page, click on ion-back-button to go back to previous tabs
4. Then try to navigate to any different tabs
5. See error (page will refresh and go back to default tabs)

**Expected Behavior**
Can navigate to others tabs smoothly without refreshing page occurs.

**Comment by windwp** [comment]
I have same problem

**Comment by omaxlive** [comment]
The same here, but there’s already open issues related.
