### ISSUE TITLE
[IOS] Bug with tabs page and non-tab page

### ISSUE THREAD

**Issue by Anthony2539** [ionic-team/ionic#15054]
# Bug Report

**Ionic Info**
```
   ionic (Ionic CLI)          : 4.0.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : ios 4.5.5

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.1.1
   NodeJS     : v10.6.0 (/usr/local/bin/node)
   npm        : 6.3.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

```

**Describe the Bug**
I have an application with a tabs ( 5 pages home, search, map , info and tarif).
From the search page i can go on a non-tab page like this ```this.router.navigate(['station'], { queryParams: station}); ```
On the station page i have a back button to return to the search page ``` <ion-button routerLink="/search"> ````
When i click on the tab menu on an other page, i have a white screen without log on xcode.
On web all work fine, i reproduce the bug only on IOS.
Here are some additional informations:

**tabs.router.module.ts**
```
const routes: Routes = [
  {
    path: 'tabs',
    component: TabsPage,
    children: [
      {
        path: 'home',
        outlet: 'home',
        component: HomePage
      },
      {
        path: 'search',
        outlet: 'search',
        component: SearchPage
      },
      {
        path: 'map',
        outlet: 'map',
        component: MapPage
      },
      {
        path: 'info',
        outlet: 'info',
        component: InfoPage
      },
      {
        path: 'tarif',
        outlet: 'tarif',
        component: TarifPage
      }
    ]
  },
  {
    path: '',
    redirectTo: '/tabs/(home:home)',
    pathMatch: 'full'
  },
  {
    path: 'search',
    redirectTo: '/tabs/(search:search)',
    pathMatch: 'full'
  }
];
```

**app-routing.module.ts**
```
const routes: Routes = [
  { path: '', loadChildren: './tabs/tabs.module#TabsPageModule' },
  { path: 'map', loadChildren: './map/map.module#MapPageModule' },
  { path: 'search', loadChildren: './search/search.module#SearchPageModule' },
  { path: 'station', loadChildren: './station/station.module#StationPageModule' },
  { path: 'info', loadChildren: './info/info.module#InfoPageModule' },
  { path: 'tarif', loadChildren: './tarif/tarif.module#TarifPageModule' }
];
```

i don't know if it's my bad or a bug ?

**Steps to Reproduce**
1. Click on tab menu to go to search page
2. From search page go to station page ( a non-tab page)
3. Go back to search page
4. Click on tab menu to go on an other page

**Expected Behavior**
Fix nav when i from a non-tab page

**Additional Context**
Only on IOS, works on web

**Comment by omaxlive** [comment]
There’s already two open issues related to this, I will link them after.

**Comment by Anthony2539** [comment]
@omaxlive thx for your response. Do you link them when the bug will be fix ?

**Comment by knutto** [comment]
#14885 
#14888 
#15045 
#15050

**Comment by Anthony2539** [comment]
hello @manucorporat thx to fix the bug.
If i want to try i have to update ionic with ```npm i -g ionic``` to pull the last ionic core ?
