### ISSUE TITLE
fatal: 'ionic' does not appear to be a git repository

### ISSUE THREAD

**Issue by Jaskerv** [ionic-team/ionic#15060]
I'm new to ionic but I'm trying to push a fresh new project to git using:
`git push ionic master`
and it returns with an error:

> fatal: 'ionic' does not appear to be a git repository
> fatal: Could not read from remote repository.

I have an empty git project that's linked to the Ionic Pro project.|
What do I do here

**Comment by kensodemann** [comment]
Within your project's directory, try running `git remote -vv` and see if there is an `ionic` remote there and if it is correct. If not, set it up via `ionic git remote`.  You should also check the `ionic.config.json` file to make sure the project is indeed linked to a project on Ionic Pro (it will have a valid `pro_id` matching the project ID on the pro dashboard if it is).

This article refers to having a similar issue after transferring a project, so the circumstance may be different than yours, but a lot of the steps should be the same: https://ionic.zendesk.com/hc/en-us/articles/115015930687--git-push-ionic-master-fails-after-transferring-project-to-organization



If after that you are still having issues, contact Pro support (see the bot's message above for link).
