### ISSUE TITLE
Form not submit when button click in ionic v4 

### ISSUE THREAD

**Issue by bhagwatupe** [ionic-team/ionic#15063]
`<ion-button type="submit" expand="block">Login</ion-button>`
when i click button then that time show me these url : `http://localhost:8100/login?ion-input-0=&ion-input-1=&ion-cb-0=on`

**Comment by manucorporat** [comment]
Are you using beta.1?

**Comment by bhagwatupe** [comment]
I am using V4 BETA

And my complete form submit code is 

<ion-content>
	<ion-grid class="vertical-align-content">
	    <ion-row class="m-b-15">
		    <ion-col text-center>
		      <img src="assets/imgs/logo.png" width="200">
		    </ion-col>
		</ion-row>
		<ion-list>
			<form (ngSubmit)="doLogin()" class="login-form" #heroForm="ngForm">		
				<ion-item>
					<ion-icon slot="start" name="person"></ion-icon>
					<ion-input type="text" placeholder="User Name"></ion-input>
				</ion-item>
				<ion-item>
					<ion-icon slot="start" name="lock"></ion-icon>
					<ion-input type="password" placeholder="Password"></ion-input>
				</ion-item>
				<ion-item lines="none">
					<ion-label>Remember me</ion-label>
					<ion-checkbox slot="end" checked="true"></ion-checkbox>
				</ion-item>
				<ion-button type="submit" expand="block">Login</ion-button>
			</form>
		</ion-list>
	</ion-grid>
</ion-content>

**Comment by manucorporat** [comment]
This should be fixed in beta.1, you are probably using beta.0. Closing, but feel free to reopen if this is still a thing

**Comment by bhagwatupe** [comment]
Thanks for quick reply 
but i am not able to find beta 1 .
I am currently using https://beta.ionicframework.com/docs/
