### ISSUE TITLE
Slides within form: On pressing enter, it jumps to the first page instead of submitting.

### ISSUE THREAD

**Issue by creat-or** [ionic-team/ionic#15061]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (/Users/johe/.nvm/versions/node/v9.0.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    ios-sim           : 5.0.4
    Node              : v9.0.0
    npm               : 6.1.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4.1 Build version 9F2000

Environment Variables:

    ANDROID_HOME : /usr/local/opt/android-sdk

Misc:

    backend : pro
```

**Describe the Bug**
I made a multi-slides form. Problem: Whenever a user presses enter on an input, it jumps to the first slide instead of submitting the form.

**Steps to Reproduce**
To reproduce

1. open the [stackblitz example](https://stackblitz.com/edit/ionic-cpllfv)
2. slide to the second page
3. click on the textfield and press enter.

It will slide to page one. 

**Related Code**
https://stackblitz.com/edit/ionic-cpllfv

**Expected Behavior**
I expect the form to submit. It only submits when I directly press the button.

**Comment by manuelmager** [comment]
+1
