### ISSUE TITLE
ionic 4, ios devices the server responded with a status of 401 (Unauthorized)

### ISSUE THREAD

**Issue by symeonmattes** [ionic-team/ionic#15066]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)  : 4.0.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.7.1
   @ionic/app-scripts : 3.0.0

Cordova:

   cordova (Cordova CLI) : 7.0.1
   Cordova Platforms     : android 6.4.0, ios 4.4.0

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 2.0.0
   ios-sim           : 6.0.0
   NodeJS            : v7.8.0 (/usr/local/Cellar/node/7.8.0/bin/node)
   npm               : 4.2.0
   OS                : macOS Sierra
   Xcode             : Xcode 9.1 Build version 9B55

Environment:

   ANDROID_HOME : /Users/myname/Library/Android/sdk
```

**Describe the Bug**
ios 9.3.5 devices produce a 401 error when https get request is done to the server. Actually there are 3 errors whenever an https request is done:

- Failed to load https://myserver/public/search?start_date=%222018-08-06T12:11:05.734Z%22&stop_date=%222018-08-06T13:11:05.734Z%22 resource: the server responded with a status of 401 (Unauthorized)
- Failed to load https://myserver/public/search?start_date=%222018-08-06T12:11:05.734Z%22&stop_date=%222018-08-06T13:11:05.734Z%22 resource: Origin http://localhost:8080 is not allowed by Access-Control-Allow-Origin.
- XMLHttpRequest cannot load https://myserver/public/search?start_date=%222018-08-06T12:11:05.734Z%22&stop_date=%222018-08-06T13:11:05.734Z%22. Origin http://localhost:8080 is not allowed by Access-Control-Allow-Origin.

**Related Code**
```
var headers = new Headers();
headers.append('access_token', MYTOKEN );
let options = new RequestOptions({ headers: headers });

return this.http.get('https://myserver/public/search?start_date="2018-08-06T12:11:05.734Z"&stop_date="2018-08-06T13:11:05.734Z"',options)
        .retry(NUM_HTTP_RETRIES)
        .map((res:Response) => res.json())
        .toPromise();
```
**Expected Behavior**

A json object is expected to be returned.

**Comment by manucorporat** [comment]
We are sorry but this is a not an error related with Ionic, but a server-side issue, stackoverflow might can help you better. Thanks!

**Comment by symeonmattes** [comment]
It's not a server issue because in android devices and in ios 11 the application works fine. The server doesn't accept authentication anyway!
