### ISSUE TITLE
animation bug in "overlay" and "push" type ion-menu with side set to "end" in 4.0.0-beta.1

### ISSUE THREAD

**Issue by tru03** [ionic-team/ionic#15078]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

In 4.0.0-beta.1 the ion-menu slides in from the left side instead of the right when side property is set to "end" and it is an "overlay" or "push" type. It also produces a jump when closing the menu (clicking the overlay).

**Expected behavior:**

The menu should animate in from the right side and close without a jump.

**Steps to reproduce:**

Set the side property on ion-menu to "end" and type property to "overlay" or "push" or simply check it in an "md" style view.

The bug can be also easily reproduced in the API docs: [https://beta.ionicframework.com/docs/api/menu](https://beta.ionicframework.com/docs/api/menu)

**Related code:**

```
<ion-app>
    <ion-menu side="end" type="overlay">
        <ion-content>
            lorem ipsum
        </ion-content>
    </ion-menu>
    <ion-router-outlet main></ion-router-outlet>
</ion-app>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
   ionic (Ionic CLI)          : 4.0.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.1
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1
```

**Comment by manucorporat** [comment]
This is already fixed in master! it was a bug in the animation code, thanks for reporting the issue!
