### ISSUE TITLE
Ionic V4 <ion-button> page refresh after submit

### ISSUE THREAD

**Issue by askona** [ionic-team/ionic#15080]
From Ionic3  to --->> Ionic4 
`<button ion-button>` becomes `<ion-button>` and when using it in `<form>` submiting, the page is refreshed after submitting.

**Comment by manucorporat** [comment]
Are you using beta.1?

**Comment by 777wills** [comment]
how I update from beta 0 to beta 1

**Comment by manucorporat** [comment]
in package.json, change beta.0 to beta.1 in `@ionic/angular` then run `npm i` in the terminal

**Comment by manucorporat** [comment]
Going to close this issue since, internal testing reveals this was already fixed, but please let us know in case it's not, so we can reopen

**Comment by bleuscyther** [comment]
i have the same issue in 4.0.2 Beta
