### ISSUE TITLE
V4 --inner-padding-end css does not work

### ISSUE THREAD

**Issue by kkbear1985** [ionic-team/ionic#15088]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
--inner-padding-end does not affect .item-inner padding-right 

**Expected behavior:**
.item-inner padding-right show change with --inner-padding-end

**Steps to reproduce:**
any <ion-item> with global.scss set as below
:root{
--inner-padding-end: 0px;
}
.item-inner padding-right will still exist

**Comment by manucorporat** [comment]
These are component CSS custom properties to have to set directly in the component:
```
ion-item {
--inner-padding-end: 0px;
}
```

We are currently working to document styling with CSS variables
