### ISSUE TITLE
Ion-select-options rerendering in v4 beta

### ISSUE THREAD

**Issue by jhavinay** [ionic-team/ionic#15089]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.2
   @angular-devkit/schematics : 0.7.2
   @angular/cli               : 6.1.0
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : browser 5.0.3

System:

   Android SDK Tools : 26.1.1
   ios-sim           : 5.0.13
   NodeJS            : v9.2.0 (/usr/local/bin/node)
   npm               : 5.6.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.2 Build version 9C40b

Environment:

   ANDROID_HOME : /Users/vinay/Library/Android/sdk/
```

**Describe the Bug**

Parent component has an array, which is passed to child component with @Input().
child component displays a ion-select with array elements as options.
parent modifies the array, but select popup(alert) remains same.
while new values of arrays are reflected in heading, confirming that values were propagated to child component.

**Steps to Reproduce**

**Related Code**
it will be nice to have a template on plunker or stackblitz

**Expected Behavior**
I would expect ion-select-options (in child) should reflect values of array when array changes in parent component and propagates it using @input to cild component

**Additional Context**
https://forum.ionicframework.com/t/ion-select-in-v4-beta/137554

**Comment by nikmartin** [comment]
this bug does exist in beta.17, and it's driving us mad. no amount of detectChanges, NgZone.run, etc seems to have any effect.

**Comment by paulstelzer** [comment]
Could it be that this issue is the same like #16453 and #15716

**Comment by nikmartin** [comment]
It is possible the same as #16453, but we've tried the workarounds associated with #15716 with no luck.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! We have pushed a nightly build containing some fixes for loading/re-loading select options. Would you be able to try it out in your app and let me know if the issue you are running into here is fixed? (`npm i @ionic/core@dev @ionic/angular@dev`)

Thanks for your patience as we work to resolve this issue!
