### ISSUE TITLE
ios: video hls issue

### ISSUE THREAD

**Issue by Kadinvanvalin** [ionic-team/ionic#15081]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)  : 4.0.3 (/Users/kadin/.nvm/versions/node/v9.10.1/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.9

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, browser 5.0.3, ios 4.5.4

System:

   Android SDK Tools : 26.0.1
   ios-deploy        : 1.9.2
   NodeJS            : v9.10.1 (/Users/kadin/.nvm/versions/node/v9.10.1/bin/node)
   npm               : 4.6.1
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/kadin/Android/
```

**Describe the Bug**
When playing a HLS video in ios the video freezes but the timer continues. 

**Steps to Reproduce**
1. put a .m3u8 manifest as the source for a video tag
2. use network conditioner until the video has to buffer
3. this only seems to happen a quarter of the time- and when I inspect the network in safari
there are multiple requests for the same file 

**Related Code**
If you are able to illustrate the bug with an example, please provide a sample application via an online code collaborator such as [StackBlitz](https://stackblitz.com), or [GitHub](https://github.com).

**Expected Behavior**
I expect the video player to "pause" the video until it is buffered them resume playing

**Additional Context**
none

**Comment by manucorporat** [comment]
This issues does not seem related to any ionic component. Ionic relies in browser engines like Chrome, Safari...
