### ISSUE TITLE
[Ionic v4] ion-content missing scrollToBottom() method.

### ISSUE THREAD

**Issue by JoeBoxr** [ionic-team/ionic#15095]
# Bug Report or by design

**Ionic Info**
ionic (Ionic CLI) : 4.0.2 (C:\Users\admin\AppData\Roaming\npm\node_modules\ionic)
Ionic Framework : @ionic/angular 4.0.0-beta.0
@angular-devkit/core : 0.7.2
@angular-devkit/schematics : 0.7.2
@angular/cli : 6.0.8
@ionic/ng-toolkit : 1.0.0
@ionic/schematics-angular : 1.0.1

**Describe the Bug**
ion-content had a scrollToBottom method allowing updating content to be scrolled on demand.  This is required for chat applications.  Is this by design and replaced with another component?

Regards

**Comment by marcelgoya** [comment]
You have to use the scrollview element instead:

```
const scroll = await this.content.getScrollElement();
scroll.scrollToBottom();
```

**Comment by manucorporat** [comment]
Fixed by https://github.com/ionic-team/ionic/commit/997cda06674cef269b338cc4137618619ccdf4f4

**Comment by manucorporat** [comment]
We have merged ion-scroll and ion-content into the same component!!
