### ISSUE TITLE
[Ionic 4] - ItemReorder

### ISSUE THREAD

**Issue by pradt** [ionic-team/ionic#15093]
# Support Question
Is ItemReorder supported with Ionic 4 ? I'm unable to find it in the documents. 

Specifcally I'm in the process of converting my current project that is using item reorder to Ionic 4. I was importing reorderArray from ionic-angular, and I'm unable to locate it under @ionic/angular, I've checked the beta documentation(https://beta.ionicframework.com/docs/api/list/) for Ionic 4 and this is not listed.

**Comment by pwespi** [comment]
It is supported, see https://beta.ionicframework.com/docs/api/reorder.

However, there are still some bugs, e.g.
* there is no ionItemReorder event, see https://github.com/ionic-team/ionic/issues/14640
* the reorder icon does not render in Firefox or Edge (open https://beta.ionicframework.com/docs/api/reorder and press toggle)

see see https://github.com/ionic-team/ionic/issues/14640 for more details

**Comment by pradt** [comment]
Ahhh right, it is called ion-reorder within a ion-reorder-group tag. Thank you. 

Is there a complete documentation that you are aware of that tells you of the differences between ionic 3 vs 4. I found a document on github but it hasn't covered most of what I had encountered so far, including this.

**Comment by pradt** [comment]
Closing this question.

**Comment by pwespi** [comment]
https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md
and
https://beta.ionicframework.com/docs/building/migration
are the only resources I know off about migration. But you are right, they don't cover the reorder.
