### ISSUE TITLE
ionic 4 ion-page-invisible after router navigation from a page

### ISSUE THREAD

**Issue by dannyreil** [ionic-team/ionic#15090]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.1
   @angular-devkit/core       : 0.7.2
   @angular-devkit/schematics : 0.7.2
   @angular/cli               : 6.1.2
   @ionic/ng-toolkit          : 1.0.5
   @ionic/schematics-angular  : 1.0.4

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   NodeJS            : v8.11.2 (/usr/local/bin/node)
   npm               : 6.1.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/danreil/Library/Android/sdk

```

**Describe the Bug**

I have an Auth Guard which protects my routes, which is working fine. I also have a Login Page which is not protected by the Auth Guard, when going directly to the login page, then logging in (using Azure AD) and being redirected back I am then logged in which works fine and the Dashboard page is loaded correctly.

However I also have a check in the constructor of the login page

```
const url = this.route.snapshot.queryParams['return'] || '/';
 
if (this.adalService.userInfo.authenticated) {
  this.router.navigate([url]);
}
```

When you are logged in this will redirect you through to the logged in page. I am using the Angular router to navigate back to the dashboard page, it routes through to the page fine however the `app-main` (Page which contains the nav and a router-outlet, which loads the dashboard) has the class `ion-page-invisible` which has `opacity:0;` and the `app-login` still exists in the dom but is not visible, so neither page is displayed (removing the `opacity` on the `app-main` does show the page so it is loaded correctly).

Also tried using the `NavController` using `goRoot()` which loads `app-main, however still has the class 'ion-page-invisible' so is not shown. This time however the 'app-login' is visible and has a higher index and is shown first.

**Expected Behavior**

Using either the angular router `navigate()` or the NavController `goRoot()` should remove the class `ion-page-invisible` on the route which you are navigating to

**Comment by hdlopesrocha** [comment]
I have the same problem :-(

**Comment by FrankMa1** [comment]
My approach to getting rid of the **ion-page-invisible** is by removing the class after a user is authenticated and redirected to the HomePage. 
I guess it is not the best approach putting it in **ngOnInit()** so I will be happy if you correct me.

```
import ...

@Component({
    selector: 'app-home',
    templateUrl: 'home.page.html',
    styleUrls: ['home.page.scss'],
})
@Directive({
    selector: '[ion-page]'
})
export class HomePage implements OnInit {
....
constructor( private router: Router, public auth: AuthService, public renderer: Renderer2, private el: ElementRef) {}
ngOnInit() {
        this.renderer.removeClass(this.el.nativeElement, 'ion-page-invisible');
}
```
