### ISSUE TITLE
[Ionic 3] [Ion-input] [Keyboard] Ion-input doesn't fire click callback for clearInput

### ISSUE THREAD

**Issue by mikaelboff** [ionic-team/ionic#15094]
# Bug Report

**Ionic version: (check one with "x")**
[ ] 2.x
**[x] 3.x**
[ ] 4.x

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
@ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 6.3.0 browser 5.0.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.0.2
    Node              : v8.9.4
    npm               : 5.6.0
    OS                : Windows 7

Environment Variables:

    ANDROID_HOME : C:\Users\S0015\AppData\Local\Android\Sdk
```

**Describe the Bug**
When I click on the clearInput button on the ion-input, it doesn't fire the click callback.

**Steps to Reproduce**
1. Put the ion-input element with the clearInput directive and (click) function on any html page;
2. Create the function on the .ts file;
3. Fill the ion-input and then click on the clear icon;
4. The click callback is not fired.

**Related Code**
```
.html
<ion input clearInput (click)="test($event)">

.ts
test(event){
     console.log('clicked');
}
```

**Expected Behavior**
The click event (or another event related to the click on the clear icon) must have been fired.

**Additional Context**
This is necessary because when I click on the clear icon, the input closes, and I don't want to close the keyboard, so i would capture this event and re-open the keyboard.

**Comment by teerasej** [comment]
I don't see the `ion-input` event **click** documented in Ionic4 beta and Ionic 3's documentation. I'm wondering, is this the best way to capture clear event from `ion-input`?

**Comment by mikaelboff** [comment]
Hi @teerasej , do you know a way to capture the clear event? Because I dig through the documentation of ion-input and i didn't find anything about it.

**Comment by teerasej** [comment]
I think we have to wait the team tell us is this issue about **Feature request** or **Bug report** because we just assumed 'it should work with ...' but there is nothing related to their document.

**Comment by mikaelboff** [comment]
Ok, thanks for the replying ^^
