### ISSUE TITLE
docs(content): document [no-bounce] breaking change

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#15106]
**Ionic Info**
@ionic/angular: "4.0.0-beta.2"

**Describe the Bug**
The property `no-bounce` seems to be not implemented. I searched it thru the Ionic repo and seems that this attribute is also use in different test but I couldn't found any implementation

Furthermore, test on my iPhone 6s, the pages are bouncing

**Expected Behavior**
Provide, like in v3, an attribute/option to be able to set  content to be `no-bounce`

**Related Code**

    <ion-content no-bounce>

**Comment by manucorporat** [comment]
I renamed the issue, so we can track it better!

**Comment by peterpeterparker** [comment]
@manucorporat sorry for a bit dumb issue, I could have found that by myself...but cool if you add it to the breaking changes list 👍
