### ISSUE TITLE
Ionic4 beta1 doesn't run in IE11 (@ionic/core/dist/utils/config.js is not transpiled)

### ISSUE THREAD

**Issue by martijnlutgens** [ionic-team/ionic#15119]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.1
   @angular-devkit/core       : 0.7.2
   @angular-devkit/schematics : 0.7.2
   @angular/cli               : 6.1.2
   @ionic/ng-toolkit          : 1.0.5
   @ionic/schematics-angular  : 1.0.4

Cordova:

   cordova (Cordova CLI) : 6.5.0
   Cordova Platforms     : android 7.0.0, ios 4.3.1

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.11.3 (/Users/martijnlutgens/.nvm/versions/node/v8.11.3/bin/node)
   npm        : 5.6.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : not set
```

**Describe the Bug**
Hi there,

I was looking into Ionic 4 beta1 and tested it in IE11, but it doesn't work. I get an error: SCRIPT1002: Syntax error.  vendor.js (71725,21).

**Steps to Reproduce**
1. Enable these polyfills:
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

import 'core-js/es6/reflect';
2. use 'ionic serve' to run the app and open it in IE11 (I was using browserstack on Mac)

**Related Code**
It seems that the @ionic/core/dist/utils/config.js is not transpiled and is using fat arrow functions:
export function configFromURL() {
    const config = {};
    const win = window;
    win.location.search.slice(1)
        .split('&')
        .map(entry => entry.split('='))
        .map(([key, value]) => [decodeURIComponent(key), decodeURIComponent(value)])
        .filter(([key]) => startsWith(key, IONIC_PREFIX))
        .map(([key, value]) => [key.slice(IONIC_PREFIX.length), value])
        .forEach(([key, value]) => {
        config[key] = value;
    });
    return config;
}

**Expected Behavior**
Use ionic serve and the app will run on IE11 out of the box

**Additional Context**

**Comment by troyanskiy** [comment]
As far as I know Ionic does not support IE at all.

**Comment by martijnlutgens** [comment]
Ok. I see. I must say that  I am a bit disappointed. I thought that with Ionic 4 moving closer to angular standards would also allow it to work with IE polifills. This means it’s still a showstopper for a lot of projects since a lot of corporations are still using IE as the corporate browser....

**Comment by prmths128** [comment]
Hello
I've managed to run my ionic 4 app on IE11 by using babel to get rid of arrow functions.
Here's my .babelrc
```
{
  "presets": [
    ["env", {
      "targets": {
        "ie": 11
      }
    }]
  ],
  "plugins": ["transform-es3-member-expression-literals","transform-es3-property-literals","transform-es2015-arrow-functions"]
}
```
Haven't had time to look at the css4 variables compatibility yet.

**Comment by bornhauser** [comment]
Hi
What do I need to do to activate this .babelrc in Ionic 4.

**Comment by kellycrowther** [comment]
I wanted to share what our company did to enable IE11. We were targeting es5, so we didn't need to set up a babel configuration to remove fat arrow syntax. My coworker did figure out how to use `css-vars-ponyfill` to transform css4 into something usable by ie11. In our app component, after the platform is ready, we did this

`      cssVars({
        onComplete(cssText: any, styleNode: any, cssVariables: any): void {
          cssVars({
            onlyLegacy: true
          });
        }
      });
`
this along, along with enabling angular's default polyfills for ie11, we got it to render. We've been adding in css selectors to target ie11 to fine tune the styles

**Comment by royanon** [comment]
There is still 10% of desktop user using IE at this moment, and when using ionic 4 with PWA, it is not reasonable not supporting it. Angular have it's polyfill enabled to backward support IE at least IE11. Then, ionic 4 should support IE as long as it is for PWA.

**Comment by royanon** [comment]
> I wanted to share what our company did to enable IE11. We were targeting es5, so we didn't need to set up a babel configuration to remove fat arrow syntax. My coworker did figure out how to use `css-vars-ponyfill` to transform css4 into something usable by ie11. In our app component, after the platform is ready, we did this
> 
> ` cssVars({ onComplete(cssText: any, styleNode: any, cssVariables: any): void { cssVars({ onlyLegacy: true }); } });`
> this along, along with enabling angular's default polyfills for ie11, we got it to render. We've been adding in css selectors to target ie11 to fine tune the styles

Dear Kellycrowther, 

can you please give me some hints to fix the style? I try using css-vars-pnlyfill, trying to fix the scrollToBottom issue, due to nexted calc css var not being calculate in IE11. But I can't get it fix after setting variables and have cssVars run.

Regards,
Roy

**Comment by kellycrowther** [comment]
@royanon here is the relevant code that worked for us. 

Be sure to install css-vars-ponyfill then in your app.component

`import cssVars from 'css-vars-ponyfill';` // import this at the top of app.component

stick this below your constructor

`  public ngOnInit(): void {
    this.platform.ready().then(() => {
      cssVars({
        onComplete(cssText: any, styleNode: any, cssVariables: any): void {
          cssVars({
            onlyLegacy: true
          });
        }
      });
    });
  }`

this alone got us 60% - 70% of the way there. 

Further tweaks needed in the scss were with selectors like this `@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) { */ style here */ }`

**Comment by manucorporat** [comment]
This should be fixed in rc.1!

**Comment by MikeLallemont** [comment]
Hey @manucorporat are you saying Ionic 4.0.0-rc.1 supports IE 11?
