### ISSUE TITLE
[Ionic v4] Hardware back button not working

### ISSUE THREAD

**Issue by joseadrian** [ionic-team/ionic#15117]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.0.2
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.4

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.4.0

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.2.0
   OS     : Windows 10

Environment:

   ANDROID_HOME : not set
```

**Describe the Bug**
The hardware back button on and Android device doesn't have its default behaviour. Going to a page and then pressing the back button doesn't do anything.

**Steps to Reproduce**
1. Go to any page
2. Press the hardware back button
3. Doesn't go back

**Related Code**
I have followed the steps on the `Starting` and `Running on android` pages of the beta docs. This is the repo I have tested it with https://github.com/joseadrian/ionicv4-backbutton 

**Expected Behavior**
The hardware back button to work. Go to the previous page, close alerts and modals. 

**Additional Context**
- Forum link https://forum.ionicframework.com/t/hardware-back-button-with-ionic-4/137905/16
- Build of the app on the repo. https://i.diawi.com/eidDPJ

**Comment by redhaanggara** [comment]
same like me

**Comment by peterpeterparker** [comment]
I found out that the problem was already reported https://github.com/ionic-team/ionic/issues/14803
