### ISSUE TITLE
[Ionic v4] ion-header ion-toolbar height to big on Android devices

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#15116]
**Ionic Info**
@ionic/angular: "4.0.0-beta.2"

**Describe the Bug**
The `ion-header ion-toolbar` height is too big on (real) Android devices (see Screenshot)

**Expected Behavior**
A correct header size on devices

**Related**
In beta.2 the same issue was solved for iOS, don't know if it's related https://github.com/ionic-team/ionic/issues/15073

**Screenshot**
![screenshot_20180810-101102](https://user-images.githubusercontent.com/16886711/43946580-e9b81848-9c85-11e8-9b40-25ab6f39cb94.png)

**Comment by JAYiSON021** [comment]
@peterpeterparker  I tried that in my newly generated project (v4) because i had the same problem on native device.

**Comment by peterpeterparker** [comment]
@JAYiSON021 in that case that's a workaround, thx ;) Out of the box I think that the height of the header of a Ionic app should match the device without any modification in the platform code therefore I think it need a fix

**Comment by peterpeterparker** [comment]
@bleuscyther I migrate my app from v3 to v4, the statusbar settings are exactly the same

**Comment by bleuscyther** [comment]
i just noticed that the page looking at for a reference has no header. 
Same issue reported here: https://github.com/ionic-team/ionic/issues/15138

**Comment by brandyscarney** [comment]
@peterpeterparker Are you still seeing this on `beta.3`?

**Comment by peterpeterparker** [comment]
@brandyscarney thx for asking. yes the issue is still here with beta.3

screenshot of my paired device

<img width="1241" alt="capture d ecran 2018-08-17 a 07 11 55" src="https://user-images.githubusercontent.com/16886711/44248792-f20b9800-a1ec-11e8-93a6-1488ea95a856.png">

screenshot from the device

![screenshot_20180817-071103](https://user-images.githubusercontent.com/16886711/44248807-0a7bb280-a1ed-11e8-85b9-b936515d18ea.png)

**Comment by brandyscarney** [comment]
@manucorporat I think we need to check for the platform class for this: https://github.com/ionic-team/ionic/blob/master/core/src/components/app/app.scss#L6

**Comment by abou-emish** [comment]
@brandyscarney you are right, the following CSS fixed it
```
ion-header.header-md ion-toolbar:first-child {
    padding-top: 0;
}
```

**Comment by peterpeterparker** [comment]
I could confirm that, with v4-beta.5, the height of my toolbar/header is now correct on both real iPhone 6s and Android Samsung Edge and simulated iPhone X

Thx a lot!
