### ISSUE TITLE
Revisit all components with `disabled` prop

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#15129]
- Click/focus/blur event should not be emitted
- Provide `aria-disabled` from accessibility in the host element
- Provide visual feedback (opacity?)
- Do we need to pass disabled down to the native `button`, `a`, `input`? or aria-disabled on the host is enough?

**Comment by jaufgang** [comment]
The fact that disabled buttons still fire a `click` event is a pretty serious bug.  This can cause forms to submit even if the submit button is disabled when form validation fails.  This can result in data corruption and subsequent buggy behaviour that can be difficult to trace back to the original form validation problem. 

@manucorporat, could this issue could be bumped up in priority?  Or at least this aspect of the issue (accessibility and visual feedback may be less urgent as they do not lead to  data corruption)?

Thanks!.
