### ISSUE TITLE
[Ionic v4] Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#15122]
**Ionic Info**
@ionic/angular: "4.0.0-beta.2"

**Describe the Bug**
The following error poped up in my Chrome debug console a couple of times today. I don't know effectively when unfortunately

> d6ubnyaf.js:5 Uncaught TypeError: Cannot read property 'split' of undefined
>     at i.removeClass (d6ubnyaf.js:5)
>     at t.destroy (d6ubnyaf.js:5)
>     at t.destroy (d6ubnyaf.js:5)
>     at d6ubnyaf.js:5
>     at Array.forEach (<anonymous>)
>     at d6ubnyaf.js:5
>     at Array.forEach (<anonymous>)
>     at t.push../node_modules/@ionic/core/dist/esm/es5/d6ubnyaf.js.h.emit (d6ubnyaf.js:5)
>     at t.destroy (d6ubnyaf.js:5)
>     at e.componentDidUnload (d6ubnyaf.js:5)

where `d6ubnyaf.js:5` is

`removeClass:function(e){for(var t=e.split(" "),i=0;i<t.length;i+=1)for(var s=0;s<this.length;s+=1)void 0!==this[s].classList&&this[s].classList.remove(t[i]);return this},hasClass:function(e){return!!this[0]&&this[0].classList.contains(e)},`

which according the header is an Ionic file

```
/*!
 * (C) Ionic http://ionicframework.com - MIT License
 * Built with http://stenciljs.com
 */
```

**Expected Behavior**
No such error ;)

**Comment by manucorporat** [comment]
it's actually Swipper, not our code :(

**Comment by mhartington** [comment]
@peterpeterparker got a sample project or test case for this?

**Comment by peterpeterparker** [comment]
@mhartington I'll observe the situation during the next days and will see if I found a way of providing such info/samples

**Comment by peterpeterparker** [comment]
I just faced the error again and I ask my self if the error "just" happens in a particular state where the slider is added to the dom but not fully loaded

For example might generated with

   isNotFirstSlide(): boolean {
        return this.slider && this.slider.nativeElement && this.slider.nativeElement.getActiveIndex() > 0;
    }

which would fails in that particular case

As workaround I think I would be able to do something like

    isNotFirstSlide(): boolean {
        try {
            return this.slider && this.slider.nativeElement && this.slider.nativeElement.getActiveIndex() > 0;
        } catch (err) {
            return false;
        }
    }

will try this and will update the issue

**Comment by peterpeterparker** [comment]
I didn't face the error the last three days so I'm guessing that my above explanation and workaround aren't that wrong, therefore I close this issue

If you land on the error and you are not willing to use **try/catch**, @rapropos provided another possible option on the Ionic forum https://forum.ionicframework.com/t/ionic-4-slides/138717/3?u=reedrichards which might works too respectively

    slides: Slides;

  @ViewChild(Slides) set slidesvc(slides) {
    this.slides = slides;
  }

**Comment by peterpeterparker** [comment]
btw. 10 days later, didn't encounter the problem anymore, so definitely all good

**Comment by mhartington** [comment]
👍
