### ISSUE TITLE
[Ionic v4] ion-toolbar with opacity doesn't render the correct color

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#15121]
**Ionic Info**
@ionic/angular: "4.0.0-beta.2"

**Describe the Bug**
Setting an `--opacity` to an `ion-toolbar` doesn't render the proper cooled. See screenshot white + 0.9 end up being grey

Note: This problem poped with beta.2, was ok in alpha.11 till beta.1

**Expected Behavior**
A proper rendering of background with opacity on the toolbar

**Screenshot**

<img width="1082" alt="capture d ecran 2018-08-10 a 13 01 21" src="https://user-images.githubusercontent.com/16886711/43954929-8c370508-9c9e-11e8-8ab7-9d6bebea0c66.png">

**Comment by brandyscarney** [comment]
Thanks for the issue! Is the `ion-toolbar` inside of an `ion-footer` or another element?

This might be the same issue I am seeing with the conference app when making the toolbar transparent:

<img width="1330" alt="screen shot 2018-08-10 at 11 22 32 am" src="https://user-images.githubusercontent.com/6577830/43966632-64234abc-9c90-11e8-8511-2ff78192f975.png">

cc @manucorporat @camwiegert

**Comment by peterpeterparker** [comment]
@brandyscarney exactly, the `ion-toolbar` is inside an `ion-footer` (sorry for having not posted the code in a first place)

**Comment by brandyscarney** [comment]
@peterpeterparker Thanks! I also noticed this upon upgrading to beta.2. Added it to the project board to look into!

**Comment by peterpeterparker** [comment]
@manucorporat finally it took me hours but I was able to reproduce the problem in a starter app but it's really a tricky one to reproduce

I kind of think that it only happens in "sub-pages" (nav.goForward) and only on iOS devices (in my app it happens too on Android but in this starter app I was only able to reproduce the problem on iOS)

##How to reproduce the problem##

    git clone https://github.com/peterpeterparker/ion-toolbar-opacity.git
    cd ion-toolbar-opacity
    ionic serve
    open chrome
    open chrome debugger
    toggle device toolbar
    select iPhone 6/7/8
    access http://localhot:8100
    click button "Navigate" to access the 2nd page
    scroll the all list and observe the color of the footer, from white with opacity it will turns grey

##Code##

component:

    <ion-header>
       <ion-toolbar>
          <ion-buttons slot="start">
          <ion-back-button></ion-back-button>
          </ion-buttons>
          <ion-title>
           SECOND PAGE
         </ion-title>
       </ion-toolbar>
    </ion-header>
    
    <ion-content fullscreen="true">
      <ion-list>
         <ion-item>
          <ion-label>Whatever item</ion-label>>
        </ion-item>
      </ion-list>
   </ion-content>
    
    <ion-footer>
     <ion-toolbar>
      <ion-button expand="full" shape="round">
         Whatever action
       </ion-button>
      </ion-toolbar>
    </ion-footer>
 
scss

    ion-toolbar {
       --background: white;
       --opacity: 0.9;
    }

**Comment by peterpeterparker** [comment]
I confirm that this is solved in v4-beta.5

❤️ @manucorporat @brandyscarney

**Comment by chrisgriffith** [comment]
In Beta 7, the opacity is being applied correctly to the toolbar, but the fullscreen is not being applied to the <ion-content>
