### ISSUE TITLE
[Ionic v4] Wrong CSS in Splitpane when using ion-menu with side="end"

### ISSUE THREAD

**Issue by domiSchenk** [ionic-team/ionic#15123]
# Bug Report

**Ionic Info**

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   ionic (Ionic CLI) : 4.0.5

System:

   NodeJS : v9.11.2
   npm    : 6.1.0
   OS     : Windows 10
```

**Describe the Bug**
When using an an ion-split-pane with ion-menu and the ion-menu uses side="end".  
It still appears on the left side.

**Related Code**
```
<ion-split-pane id="splitpane">
    <ion-menu menuId="menuRight" side="end">
...
    </ion-menu>
    <ion-router-outlet main></ion-router-outlet>
</ion-split-pane>
```
![image](https://user-images.githubusercontent.com/6347221/43959858-80cec11c-9cb0-11e8-9eef-6614a4529e3a.png)

**Expected Behavior**
Splitpane is on the right side when menu uses `side="end"`

I think this can be solved when when the CSS got the right specification.

**Comment by JoeBoxr** [comment]
This has already been addressed and fixed.

https://github.com/ionic-team/ionic/issues/15013

**Comment by domiSchenk** [comment]
my mistake, didnt fint this issue.
