### ISSUE TITLE
[Ionic V4] Click event on disabled fab-button 

### ISSUE THREAD

**Issue by aam-antonio** [ionic-team/ionic#15120]
# Bug Report

**Ionic Info**
`Ionic Framework            : @ionic/angular 4.0.0-beta.2`

**Describe the Bug**
Disabled ion-fab-button stills allowing interaction with the user.

**Related Code**
```
<ion-fab-button disabled (click)="test()">
  <ion-icon name="add"></ion-icon>
</ion-fab-button>

test() {
  console.log('hello');
}
```

**Expected Behavior**
The user should not interact with the fab button.

**Comment by brandyscarney** [comment]
Thanks for the issue!

@camwiegert Could you see if this is the same issue as https://github.com/ionic-team/ionic/issues/14719? We may want to double check some of our other buttons.

**Comment by manucorporat** [comment]
Probably adding pointer-none to all host components if there are disable
