### ISSUE TITLE
Issue with large padding top ion-header>toolbar

### ISSUE THREAD

**Issue by zinzinday** [ionic-team/ionic#15138]
![39010110_505885766526733_8030323408715644928_n](https://user-images.githubusercontent.com/441560/43998194-39f027d4-9e1a-11e8-99df-bbc3ae193c6d.png)

✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)          : 4.0.6 (/home/base/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.4

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.3 (/usr/bin/node)
   npm               : 5.6.0
   OS                : Linux 4.15

**Comment by thruthesky** [comment]
I am experiencing same issue.

![kakaotalk_photo_2018-08-12-18-12-22](https://user-images.githubusercontent.com/5080329/44000935-4f0a140e-9e5b-11e8-90fb-a6565921ec3a.jpeg)

**Comment by brandyscarney** [comment]
Are you still seeing this in latest (`4.0.0-beta.13`)?
