### ISSUE TITLE
<ion-content class="has-footer"> not working on ionic 4 beta 2

### ISSUE THREAD

**Issue by MrBokeh** [ionic-team/ionic#15133]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.4

System:

   NodeJS : v8.11.3 (/usr/local/bin/node)
   npm    : 6.3.0
   OS     : macOS High Sierra
```

**Describe the Bug**
`<ion-content class="has-footer">` not working on ionic 4 beta 2
It used to make sure the footer won't hide stuff of the list of the list is longer than the screen, it is a must feature for any chat apps with auto scroll to bottom

**Steps to Reproduce**
1. create ion-list
2. keep adding item to ion-list
3. auto scroll to bottom with the ion-content 
4. the footer is hiding the last item behind so the auto scroll to bottom is always missing the last item

**Related Code**

**Expected Behavior**
if I add has-footer as a class with ion-content, it shoud fix the issue like ionic 3.9.2
`<ion-content class="has-footer">`

**Additional Context**

**Comment by manucorporat** [comment]
I don't understand, i don't remember we had an API like `.has-footer`. Can you provide additional information about what you want to accomplish, screenshots welcome.

**Comment by MrBokeh** [comment]
Here is the scenario, if I am adding more items on the ion-list and the total height of the content is over the screen height, the list item will go underneath the footer but not the header. The problem is if I try to auto scroll to the bottom of the list whenever I add an item like a chat history, I will call the scrollToBottom function of the scroll element of the content, it will scroll to the bottom of the list but the last one is blocked the footer and hided hehind the footer. I don’t want any content go behind the footer, is there a way to add some css or set an attribute to make sure no content will go underneath the footer like the header?

**Comment by paulstelzer** [comment]
I close this because as manu says there is no has-footer. If you want it as feature, open a new issue as feature request
