### ISSUE TITLE
swiper-pagination swiper-pagination-bullets bug

### ISSUE THREAD

**Issue by lim-enhui** [ionic-team/ionic#15139]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[X] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**

The swiper pagination is not shown in chrome by default behavior. Only upon changing the emulator in chrome, it shows.

**Expected behavior:**

To be consistent in all slides

**Steps to reproduce:**

Load swipe pagination. And change device emulation in chrome

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by paulstelzer** [comment]
This is issue should be resolved in beta.17. If I am wrong, please write here!
