### ISSUE TITLE
White screen when using UIWebView in ionic 4

### ISSUE THREAD

**Issue by mvollebregt** [ionic-team/ionic#15134]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

In an ionic 4 application, I'm forcing UIWebView usage by following the steps described in https://ionicframework.com/docs/wkwebview#downgrading-to-uiwebview. I added the preference to config.xml and uninstalled the Ionic Webview Plugin.

Now, when I start the application on an iPhone (real device or simulator) I only get a white screen, and the following output:

```
...
[CDVTimer][TotalPluginStartup] 34.731984ms
Resetting plugins due to page load.
NSURLConnection finished with error - code -1100
NSURLConnection finished with error - code -1100
NSURLConnection finished with error - code -1100
NSURLConnection finished with error - code -1100
NSURLConnection finished with error - code -1100
Finished load of: file:///Users/.../www/index.html
...
```

The application did load normally before I forced usage of UIWebView. Also, when I create an identical app in Ionic 3 and force usage of UIWebView using the same steps, the application works as expected.

I do need UIWebView for my app instead of WKWebView, because WKWebView needs CORS-headers and I don't control the server I'm talking to.

**Expected behavior:**

Instead of showing a white screen, the application should load on the iPhone (device or simulator).

**Steps to reproduce:**

1. Generate an ionic 4 application: `ionic start testapp blank --type angular --cordova`
2. Build the application: `ionic cordova build ios --prod`
3. Run the application on an iPhone (simulator or device): the application works as expected
4. Add `<preference name="CordovaWebViewEngine" value="CDVUIWebViewEngine" />` to config.xml as described in https://ionicframework.com/docs/wkwebview#downgrading-to-uiwebview.
5. `rm -rf platforms`
6. `rm -rf plugins`
7. Repeat step 2 and 3.
8. The application does not show up, you see only a white screen.

Instead of following steps 1 to 6 manually, you can also check out the github project at https://github.com/mvollebregt/ionic-4-uiwebview-error and proceed immediately to step 7. The github project contains the exact result of following steps 1 to 6.

**Related code:**

I generated the app by exactly following steps 1 to 6 above. You can find it at:

https://github.com/mvollebregt/ionic-4-uiwebview-error

**Other information:**

The full output in the xcode debug window when running the non-working app:

```
Apache Cordova native platform version 4.5.5 is starting.
Multi-tasking -> Device: YES, App: YES
Using UIWebView
[CDVTimer][console] 0.084996ms
[CDVTimer][handleopenurl] 0.067949ms
[CDVTimer][intentandnavigationfilter] 3.059030ms
[CDVTimer][gesturehandler] 0.067949ms
[CDVTimer][splashscreen] 29.217958ms
CDVIonicKeyboard: resize mode 1
CDVIonicKeyboard: WARNING!!: Keyboard plugin works better with WK
[CDVTimer][keyboard] 1.921058ms
[CDVTimer][TotalPluginStartup] 35.464048ms
Resetting plugins due to page load.
NSURLConnection finished with error - code -1100
NSURLConnection finished with error - code -1100
NSURLConnection finished with error - code -1100
NSURLConnection finished with error - code -1100
NSURLConnection finished with error - code -1100
Finished load of: file:///Users/.../testapp.app/www/index.html
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)          : 4.0.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.4

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 2.0.0
   NodeJS            : v10.4.0 (/usr/local/bin/node)
   npm               : 6.3.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/michel/lib
```

**Comment by manucorporat** [comment]
UIWebView has been deprecated by Apple, and will be discontinued soon, even Cordova. Ionic 4 does not longer support UIWebView, it such a big engineering effort to support a old browser when there are much better alternatives.

I would suggest to stay with ionic 3, look at this (https://ionicframework.com/docs/native/http/) or try to get the server in line.
