### ISSUE TITLE
[Ionic v4] ion-datetime ionChange events not passing the selected date

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#15131]
**Ionic Info**
@ionic/angular: "4.0.0-beta.2"

**Describe the Bug**
When using `ion-datetime`, the events passed from `ionChange($event)` doesn't contains the selected date

**Expected Behavior**
Begin able to read and process the selected date

**Code**

v3:

    <ion-datetime displayFormat='DD/MM/YYYY' (ionChange)="updateMyDate($event)"></ion-datetime>

    updateMyDate($event) {
      console.log($event); // --> wil contains $event.day, $event.month and $event.year
    }

in v4, same code will results on having $event.day, $event.month and $event.year equals to `undefined`

**Workaround**

The following workaround seems to be ok, the only side effect is that if the user doesn't pick a day or or month, instead of becoming the value "1" the value "null" gonna be passed

    <ion-datetime #myPicker displayFormat='DD/MM/YYYY' (ionChange)="updateMyDate(myPicker.value)"></ion-datetime>
    
    updateMyDate($event) {
      console.log($event); // --> wil contains $event.day.value, $event.month.value and $event.year.value
    }

**Comment by manucorporat** [comment]
Fixed by https://github.com/ionic-team/ionic/commit/2e7d355edf1cd0836dd6afc3090f02c905e490da
