### ISSUE TITLE
Get invalid value from datepicker

### ISSUE THREAD

**Issue by Alex1000A** [ionic-team/ionic#15148]
# Bug Report

**Ionic Info**
Version:Ionic 4.0.2@beta

**Describe the Bug**
Ionic Datepicker get invalid value 

**Steps to Reproduce**
1. Go to https://beta.ionicframework.com/docs/api/datetime
2. Click one of the datepicker and select done without choose any value
3. Invalid value appear

**Expected Behavior**
Able to get the default value from the options

**Additional Context**
![ionic_bug_color png](https://user-images.githubusercontent.com/27215710/44015361-77540cf6-9e85-11e8-8606-8b13f390856b.jpg)

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed in `beta.3` (and the docs once it is released) by the following commit: d19061c863f8558a0e597e3a5a53f1567b271b7b
