### ISSUE TITLE
[ionic v4] can't dismiss modal from current modal page component

### ISSUE THREAD

**Issue by hr1992** [ionic-team/ionic#15149]
# Bug Report

**Ionic Info**

```

Ionic:

   ionic (Ionic CLI)          : 4.0.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.2
   @angular-devkit/schematics : 0.7.2
   @angular/cli               : 6.1.2
   @ionic/ng-toolkit          : 1.0.5
   @ionic/schematics-angular  : 1.0.4

Cordova:

   cordova (Cordova CLI) : 6.5.0
   Cordova Platforms     : not available

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.1.3
   NodeJS     : v8.9.4 (/usr/local/bin/node)
   npm        : 5.6.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : not set
```

**Describe the Bug**
In v3 of ionic, we can use viewController to dismiss from current modal component.But in v4, there is not viewController in `@ionic/angular`.

**Steps to Reproduce**
1. Creating any modal and present with a page component.
2. Can't dismiss this modal from current modal inside.

**Expected Behavior**
I think we need a service to dismiss from modals.

**Comment by mrnvr** [comment]
I had the same problem. Take a look at this issue #15118

**Comment by peterpeterparker** [comment]
`modalController.dismiss()` -> dismiss modal
`popoverController.dismiss()` -> dismiss popover

**Comment by hr1992** [comment]
@peterpeterparker @cvaliere Thanks you all guys, i will cose this issue.
