### ISSUE TITLE
<ion-tabs> is 'floating' on iOS

### ISSUE THREAD

**Issue by Robinyo** [ionic-team/ionic#15147]
# Bug Report

```
Ionic:

   ionic (Ionic CLI)          : 4.0.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.2.0-beta.2
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.4

System:

   NodeJS : v10.8.0 (/usr/local/Cellar/node/10.8.0/bin/node)
   npm    : 6.2.0
   OS     : macOS Sierra
```

**Describe the Bug**
`<ion-tabs>` is 'floating' above the bottom of the devices screen on iOS (see screen shots below) and bounces up and down when tapped.

**Steps to Reproduce**
1. Launch the App

**Related Code**
```
<ion-tabs>

  <ion-tab label="Recents" icon="time" href="/tabs/(recents:recents)">
    <ion-router-outlet name="recents"></ion-router-outlet>
  </ion-tab>

  <ion-tab label="Folders" icon="folder" href="/tabs/(folders:folders)">
    <ion-router-outlet name="folders"></ion-router-outlet>
  </ion-tab>

  <ion-tab label="Files" icon="document" href="/tabs/(files:files)">
    <ion-router-outlet name="files"></ion-router-outlet>
  </ion-tab>

  <ion-tab label="Offline" icon="download" href="/tabs/(offline:offline)">
    <ion-router-outlet name="offline"></ion-router-outlet>
  </ion-tab>

  <ion-tab label="Settings" icon="settings" href="/tabs/(settings:settings)">
    <ion-router-outlet name="settings"></ion-router-outlet>
  </ion-tab>

</ion-tabs>
```

**Expected Behavior**
The tabbar should be locked to the bottom of the device's screen.

**Additional Context**
iOS:

![img-0884](https://user-images.githubusercontent.com/12203540/44013948-3a1e4a04-9f0c-11e8-9300-3e94e29e1419.PNG)

![img-0885](https://user-images.githubusercontent.com/12203540/44013959-47f4d0e4-9f0c-11e8-98d0-eaec2e3730cd.PNG)

Android:

![folders](https://user-images.githubusercontent.com/12203540/44013968-53bae030-9f0c-11e8-8850-72e6cf9eb4bc.png)

**Comment by KevinGruber** [comment]
I can confirm that issue i also noticed it, locally i solved the problem with setting 

html {
   height: 100vh;
}

in global.scss as a workaround

which solves the problem. But i don't really know why the 100% are not really working.

**Comment by Robinyo** [comment]
Thanks for the workaround :)

**Comment by gabrielmaldi** [comment]
In #15275 I attached a screenshot and a video showing the behavior described here, if it's of any help.

**Comment by gabrielmaldi** [comment]
I'm still seeing this in `4.0.0-beta.13`.

**Comment by paulstelzer** [comment]
Is this issue still exist in beta.17?
