### ISSUE TITLE
[Ionic v4.beta.2] ion-selects not displaying correctly with stacked or floating ion-labels in ion-items

### ISSUE THREAD

**Issue by cranderveldt** [ionic-team/ionic#15140]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.4 (~/.nvm/versions/node/v10.8.0/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.4

Cordova:

   cordova (Cordova CLI) : 6.3.1
   Cordova Platforms     : not available

System:

   ios-deploy : 1.9.2
   NodeJS     : v10.8.0 (~/.nvm/versions/node/v10.8.0/bin/node)
   npm        : 6.2.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : not set
```

**Describe the Bug**
When using an `ion-select` in an `ion-item`, setting an `ion-label`'s `position` to `floating` or `stacked` will cause the components to display incorrectly. Fixed `ion-label`s work fine. Screenshot below:

![Screenshot](https://i.imgur.com/fNB3AqU.png)

**Steps to Reproduce**
1. Add any `ion-item` to an `ion-list`
2. Add `ion-select`
3. Add `ion-label` with the `position` attribute set to `stacked` or `floating`

**Related Code**
[Example code used for screenshot](https://gist.github.com/cranderveldt/a14363dd9d3f81210d2999c52954f9a7)

**Expected Behavior**
`ion-select` should display more closely to how `ion-inputs` display when using a stacked or floating `ion-label` in an `ion-item`.

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed in the `beta.3` release!
