### ISSUE TITLE
Ionic 4 black area in page transitions between page with and without ion-header 

### ISSUE THREAD

**Issue by Sebschock** [ionic-team/ionic#15158]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.2
   @angular-devkit/schematics : 0.7.2
   @angular/cli               : 6.1.2
   @ionic/ng-toolkit          : 1.0.5
   @ionic/schematics-angular  : 1.0.4

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5

System:

   Android SDK Tools : 25.2.5
   ios-deploy        : 1.9.2
   NodeJS            : v8.11.3 (/usr/local/Cellar/node@8/8.11.3_1/bin/node)
   npm               : 5.6.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
When transitioning between a page with and without the ion-header a black area enters the transition animation.
![transition](https://user-images.githubusercontent.com/6289019/44035970-fb64223e-9f10-11e8-8772-9cfbd05483aa.gif)

**Steps to Reproduce**
```
ionic start myApp tabs --type=angular
ionic generate page new
```
Remove ion-header from home.page.html and add button.

**Expected Behavior**
No black area.

**Comment by sasos90** [comment]
Still an issue at 4.0.0-beta.15.
I see its in core, good job!

**Comment by manucorporat** [comment]
Is it still a problem in rc-0?

**Comment by Sebschock** [comment]
It seems to be fixed. Thanks! 

![nav-2](https://user-images.githubusercontent.com/6289019/50829355-8c0ee100-1344-11e9-97e4-06156f0bcef2.gif)
