### ISSUE TITLE
Platform.is returns wrong value in v4

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [ionic-team/ionic#15165]
# Bug Report
When running on chrome desktop browser, `this.platform.is('core')` should return true. But currently it returns false.
**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.1
   @angular-devkit/schematics : 0.7.1
   @angular/cli               : 6.1.1
   @ionic/ng-toolkit          : 1.0.1
   @ionic/schematics-angular  : 1.0.2

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   NodeJS : v10.1.0 (/usr/local/bin/node)
   npm    : 6.3.0
   OS     : macOS High Sierra
   Xcode  : Xcode 9.4.1 Build version 9F2000
```

**Steps to Reproduce**
1. Console log this.platform.is('core') and run on desktop browser.
4. See that it logs `false`

**Expected Behavior**
`this.platform.is('core')` Should return true

**Additional Context**
`this.platform.platforms()` also returns ['android'] which is wrong.

Related issue: https://github.com/ionic-team/ionic/issues/15051

**Comment by brandyscarney** [comment]
Thanks for the issue! We will look into this.

Merging the following issues into this one to verify/fix:
- ionic v4 platform specify like ionic v3 #15051
- v4: Platform.is not detecting core when run inside browser #14802
- platform.is('ios') return false on ios when deployed as app #14646
- Ionic 4: platform.is('electron') failed for electron 2.0.1 #14517

**Comment by gbacskai** [comment]
similar here:
ionic serve: 
native chrome (osx) : ["core"] - ok
change chrome as browse in iPhoneX: ["mobile", "ios", "iphone", "mobileweb"] - ok

but when I put the whole code behind a load balancer (--prod):
native chrome : ["cordova", "core"] - ok
change chrome as browse in iPhoneX: ["cordova", "mobile", "ios", "iphone"] - not ok as this is a web browser

**Comment by goelectricstations** [comment]
same issue
