### ISSUE TITLE
Ionic 4 item sliding bug

### ISSUE THREAD

**Issue by imadbakir** [ionic-team/ionic#15169]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.0.6 (/Users/imadbakir/.nvm/versions/node/v9.3.0/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.4

System:

   NodeJS : v9.3.0 (/Users/imadbakir/.nvm/versions/node/v9.3.0/bin/node)
   npm    : 5.5.1
   OS     : macOS High Sierra
```

Ionic sliding item causes the whole view to disappear even in the docs link 
https://beta.ionicframework.com/docs/api/item-sliding

**Steps to Reproduce**
make a page with item sliding in it https://beta.ionicframework.com/docs/api/item-sliding

**Comment by brandyscarney** [comment]
I am not able to reproduce this in the latest documentation. If you are still seeing this can you please create an issue on our ionic-docs repo? Thank you! https://github.com/ionic-team/ionic-docs/issues/new
