### ISSUE TITLE
[v4] Content.ionScroll is missing

### ISSUE THREAD

**Issue by ptitjes** [ionic-team/ionic#15160]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.0.6 (/opt/npm/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.4

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.4
   @capacitor/core           : 1.0.0-beta.4

System:

   NodeJS : v8.9.1 (/usr/local/bin/node)
   npm    : 6.3.0
   OS     : Linux 4.17
```

**Describe the Bug**

There is no `ionScroll` event emitter on class `Content`. (There is no `ionScrollStart` or `ionScrollEnd` either).

```
src/app/toolkit/directives/scroll-to-top.ts(52,20): error TS2339: Property 'ionScroll' does not exist on type 'Content'.
```

**Steps to Reproduce**
1. import `Content`
2. add `private content: Content` to your component's constructor to get it by injection
3. try to access to the `ionScroll` event emitter : `this.content.ionScroll`

**Expected Behavior**
We should be able to access the `ionScroll` event emitter programatically.

**Comment by manucorporat** [comment]
This is already fixed in master, next beta.3 (scheduled for this wednesday) will include the fix

**Comment by ptitjes** [comment]
@manucorporat Thanks.

**Comment by ptitjes** [comment]
@manucorporat Unfortunately, the `ionScroll`, `ionScrollStart` and `ionScrollEnd` properties are now defined on `beta.3` but they are non-functional.

The events are correctly triggered when `(ionScroll)` is used on the `<ion-content>` element directly. However, nothing is streamed in the `content.ionScroll` `EventEmitter`... :(

My code:
```
this.content.scrollEvents = true;
this.content.ionScrollEnd.subscribe(
  e => console.log('In ScrollToTop-bis: ' + JSON.stringify(e))
);
```

Would you mind reopening this ticket or should I open a new ticket ?
Also when do you expect to do the next release ?

**Comment by ptitjes** [comment]
@manucorporat I suspect that the problem comes from https://github.com/ionic-team/ionic/blob/master/angular/src/directives/proxies.ts#L14 where the `proxyOutputs` function only creates the `EventEmitter` but does not proxy the events themselves. Maybe a call to the `proxyEvent` function from https://github.com/ionic-team/ionic/blob/master/angular/src/util/util.ts#L11 should be added.

Something along the lines:
```typescript
import { proxyEvent } from '../util/util';

export function proxyOutputs(instance: any, el: ElementRef, events: string[]) {
  events.forEach(eventName => {
    instance[eventName] = new EventEmitter();
    proxyEvent(instance[eventName], el.nativeElement, eventName);
  });
}
```

Am I wrong ?

**Comment by ptitjes** [comment]
@manucorporat I opened a ticket in Stencil (https://github.com/ionic-team/stencil/issues/1025) and a corresponding PR to fix all the event emitters in Angular proxies.

**Comment by manucorporat** [comment]
Thanks for reporting this issue! it's already fixed in master of stencil: 
https://github.com/ionic-team/stencil/commit/dabcf5ee74cb14c2a7a9f4801ee64b3f20fd48e5

Next version of IOnic will have this fixed!
