### ISSUE TITLE
Build wpa dont work in ms Edge

### ISSUE THREAD

**Issue by geltoncruz** [ionic-team/ionic#15173]
# Support Question

`ionic build --prod --service-worker`. 
The result is all rigth, except on browser msEdge

**Comment by geltoncruz** [comment]
The problem is with the HTTP request. When I try to do a GET request I received an console error. See the details:

My .ts code
```js
this.http
      .get<any[]>(this.url) //the return is an array
      .pipe(map(data => data[0]))
      .subscribe(
        value => {
          console.log(value); //this line is not called
        }
      )`
```
**Edge Console ERROR on start of the application:**

```js
[object Object]: {error: Object, headers: Object, message: "Http failure response for (unknown url): 0 Unknown Error", name: "HttpErrorResponse", ok: false...}


error: Object

headers: Object
message: "Http failure response for (unknown url): 0 Unknown Error"
name: "HttpErrorResponse"
ok: false
status: 0
statusText: "Unknown Error"
url: null

__proto__: Object
```


But the URL is right because the project ran withou errors on Chrome and Firefox.


**IONIC INFO**

```
Ionic:

   ionic (Ionic CLI)          : 4.0.5 (/usr/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

System:

   NodeJS : v10.8.0 (/usr/bin/node)
   npm    : 6.2.0
   OS     : Linux 4.15

```

**Comment by astec** [comment]
What is the value of the `this.url` variable?

**Comment by geltoncruz** [comment]
Hi @astec 
before I wore the absolute uri is the result was the same

**Comment by astec** [comment]
This is not a place for support questions so you should probably move this to StackOverflow or Ionic forum.

Based on your error log:
```
statusText: "Unknown Error"
url: null
```
I would check if in Edge the `this.url` is not assigend for some reason. Try to replace it with hard coded value? Check it's actually is not null.

It most probably the problem is not with Ionic and does not belong to this tracker.

**Comment by geltoncruz** [comment]
ok! understand thanks!
