### ISSUE TITLE
 ion-slides undefined in unit test

### ISSUE THREAD

**Issue by davidanaya** [ionic-team/ionic#15182]
# Bug Report

**Ionic Info**

```
cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0
local packages:
    @ionic/app-scripts : 3.1.11
    Ionic Framework    : ionic-angular 3.9.2
System:
    Node : v8.11.1
    npm  : 5.6.0
    OS   : macOS High Sierra
Misc:
    backend : pro
```

**Describe the Bug**
I have component which is using ion-slides to display some info to the user. Every slide shows a list of options and the user has to select one, and when that happens the slide changes to the next one.
I also have a header which shows the title of the slide and provides 2 buttons, BACK (previous slide or nothing if we are on the first slide) and CLOSE.

This is working fine. When I unit test this component I'm trying to test the buttons, so that when I'm in the first slide and I press BACK I should not move to the previous slide but call CLOSE instead. 

Problem is that my slides are undefined. I'm using ```fixture.detectChanges()``` but that does not seem to work, so I'm forced to use a setTimeout with 1000 ms and then my slides are defined.
Then I check that I'm in index 0 (first slide) but slides.isBeginning() returns false, so nothing works as expected.

**Steps to Reproduce**
I created a github project to showcase this. I'm using Jest for testing and vscode for development, so you can check myslides.spec.ts and run that file (jest current in launch.json included) or just run ```npm test```.

**Related Code**
Please see my github project that illustrates the problem.
[https://github.com/davidanaya/ionic-slides-test](https://github.com/davidanaya/ionic-slides-test).

This is basically how I have my slides defined in my html

```html
<ion-content>
  <ion-slides>
    <ion-slide *ngFor="let selector of selectors">
      <ion-toolbar hideBackButton="true">
        <ion-buttons left>
          <button ion-button icon-only (click)="back()">
            <ion-icon name="arrow-back"></ion-icon>
          </button>
        </ion-buttons>
        <ion-title>{{ selector.title }}</ion-title>
        <ion-buttons right>
          <button ion-button icon-only (click)="close()">
            <ion-icon name="close"></ion-icon>
          </button>
        </ion-buttons>
      </ion-toolbar>
      <ion-list>
        <button text-center ion-item *ngFor="let option of selector.options" no-lines (click)="onSelect(option)">
          {{ option }}
        </button>
      </ion-list>
    </ion-slide>
  </ion-slides>
</ion-content>
```

and this is (part of) my component class

```ts
export class MySlidesComponent implements AfterViewInit {
  @ViewChild(Slides)
  slides: Slides | undefined;

  @Input()
  selectors: any[];
  @Output()
  answer = new EventEmitter<string[]>();

  private answers: string[] = [];

  constructor() {}

  ngAfterViewInit() {
    this.slides!.onlyExternal = true;
  }
}
```

and finally, this is my test

```js
  test("when click on back on first slide, close the modal", async done => {
    fixture.detectChanges();

    // setTimeout(() => {
    console.log(
      component.slides.length(),
      component.slides.getActiveIndex(),
      component.slides.getPreviousIndex(),
      component.slides.isEnd(),
      component.slides.isBeginning()
    );
    component.back();
    console.log(component.slides.getActiveIndex());
    done();
    // }, 1000);
  });
```

If I uncomment the commented lines, the test works because my slides are defined, but if you check the logs you will see that even though I'm in slide 0, component.slides.isBeginning() is false

**Expected Behavior**
I would expect that by using ```fixture.detectChanges();``` my slides were already defined.
I would also expect that if ```component.slides.getActiveIndex()``` returns 0, also ```component.slides.isBeginning()``` returns true.

Thanks!

**Comment by Judgeja** [comment]
I'm having the same issue. Tests worked fine with karma but after changing to jest and my `@ViewChild slides ` is undefined. So its presumably not an ionic issue.
Did you find the reason for this @davidanaya?
