### ISSUE TITLE
Ion Toolbar color isn't rendered correctly in safari if there are multiple toolbars in one header

### ISSUE THREAD

**Issue by corysmc** [ionic-team/ionic#15193]
# Bug Report

**Ionic Info**
```
@ionic/core@4.0.0-beta.2
```

**Describe the Bug**
If a header contains more than one ion-toolbar, the ion-toolbar background color isn't rendered correctly.

**Steps to Reproduce**
1. View this: [https://codepen.io/corysmc/full/EpzJVR/](https://codepen.io/corysmc/full/EpzJVR/)
2. In Chrome the colors are correct
3. In Safari the background colors are all light, button/text colors are correct.

**Related Code**

[https://codepen.io/corysmc/full/EpzJVR/](https://codepen.io/corysmc/full/EpzJVR/)

**Expected Behavior**
color is consistent across browsers.

**Additional Context**
We have several screens where I might want a few toolbars in the header, the primary toolbar is dark, where the search toolbar is light.

Also note, this is broken in beta.0, beta.1, beta.2, and works in alpha.11.

**Comment by brandyscarney** [comment]
Thank you for the issue! We'll look into this.

**Comment by brandyscarney** [comment]
Will be fixed in the `beta.4` release. 🙂
