### ISSUE TITLE
Proper package for Angular 

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic#15191]
**Describe the Bug**
Right now the `ionic/angular` is not shipping using the Angular package format.  This is creating issues where webpack will pull in ES6 code, when the expected result is to use ES5. Specific example, building out the server side portion of an app with Angular universal will lead to build failures due to ES6 import statements. 

**Additional Context**
We should investigate using [ng-packagr](https://github.com/dherges/ng-packagr) to properly bundle the angular portion of the library to create the correct format entries. 

https://github.com/ionic-team/ionic/issues/14538
https://github.com/ionic-team/ionic/issues/15041

**Comment by zhiwo** [comment]
ionic4 在beat13  on android5.0 not working

**Comment by hiepxanh** [comment]
I think it is really important issue. I'm using async, await and it causing my app white screen. 
ionic 4. beta 15 android 7.

**Comment by hebra** [comment]
@hiepxanh as mentioned in this ticket #15038 at the moment Android 7.1.1 (patch levels are important!) and the related SDK API version is the minimum required Android version for Ionic 4 to work on Android. The mentioned tickets also suggests a workaround for older versions of Android using the Android System Web View system extension on these devices.

**Comment by hiepxanh** [comment]
@hebra  thank you so much, that help me and other people alot

**Comment by hiepxanh** [comment]
but the work around using webpack method not working with me, it broking my app

**Comment by mhartington** [comment]
I think this can be closed for now. `@ionic/angular` is shipping the correct code needed for Angular's tools to work and for webpack to properly import things.

As it stands the core ionic components get both an ESM build and a ES5 build if the browser supports certain features. As far as using features like async/await, the project build tools will transpile this down to ES5 for browser that don't support it natively.
