### ISSUE TITLE
getBoundingClientRect returns 0 (zero) values

### ISSUE THREAD

**Issue by workswithweb** [ionic-team/ionic#15192]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[X] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**

Inside ngOnInit, if I try to getBoundingClientRect() of ViewChild element, I receive all DOMRect values as zero (0).
However if I add delay(timeout of 2 second), then try to get getBoundingClientRect(), I get valid values.

IONIC APP -  DOES NOT WORK:
```
export class HomePage {
  @ViewChild('testnode') private chartContainer: ElementRef;
  ngOnInit() {
     console.log('ngOnInit = ', this.chartContainer.nativeElement.getBoundingClientRect());
  }
}
```
`OUTPUT: DOMRect {x: 0, y: 0, width: 0, height: 0, top: 0, …}`

IONIC APP -  THIS WORKS:
```
export class HomePage {
  @ViewChild('testnode') private chartContainer: ElementRef;
  ngOnInit() {
    setTimeout(()=>{
      console.log('ngOnInit = ', this.chartContainer.nativeElement.getBoundingClientRect());
    }, 2000);
  }
}
```
`OUTPUT: DOMRect {x: 16, y: 16, width: 1648, height: 761, top: 16, …}`

ANGULAR APP -  WORKS:
```
export class HomePage {
  @ViewChild('testnode') private chartContainer: ElementRef;
  ngOnInit() {
     console.log('ngOnInit = ', this.chartContainer.nativeElement.getBoundingClientRect());
  }
}
```
`OUTPUT: DOMRect {x: 16, y: 16, width: 1648, height: 761, top: 16, …}`

**Expected behavior:**

Should return valid DOMRect values for below code
```
export class HomePage {
  @ViewChild('testnode') private chartContainer: ElementRef;
  ngOnInit() {
     console.log('ngOnInit = ', this.chartContainer.nativeElement.getBoundingClientRect());
  }
}
```

**Comment by paulstelzer** [comment]
This seems not Ionic related, more Angular related
