### ISSUE TITLE
[Ionic v4-beta.3] ion-menu-button opens right menu instead of the left menu

### ISSUE THREAD

**Issue by JoeBoxr** [ionic-team/ionic#15206]
# Bug Report
Ionic Framework : @ionic/angular 4.0.0-beta.3
@angular-devkit/core : 0.7.2
@angular-devkit/schematics : 0.7.2
@angular/cli : 6.0.8
@ionic/ng-toolkit : 1.0.0
@ionic/schematics-angular : 1.0.1

**Describe the Bug**
With a split-pane and left menu on app.component and having another split-pane and right menu on a tab if you click on ion-menu-button it now opens the right menu instead of the left menu.

**Steps to Reproduce**

1. Create a tabs project from the iconic v4 templates

2. Place this code in app.component.html

```
<ion-app>
  <ion-split-pane>
    <ion-router-outlet main></ion-router-outlet>
    <ion-menu side="start">
      <ion-header>
        <ion-toolbar>
          <ion-title>Left Menu</ion-title>
        </ion-toolbar>
      </ion-header>
    </ion-menu>
  </ion-split-pane>
</ion-app>
```

3. Place this code in home.page.html

```
<ion-header>
    <ion-toolbar>
        <ion-buttons slot="start">
            <ion-menu-button></ion-menu-button>
          </ion-buttons>
      <ion-title>Home</ion-title>
    </ion-toolbar>
</ion-header>

<ion-split-pane>
    <ion-menu side="end" contentId="content">
      <ion-header>
        <ion-toolbar>
          <ion-title>Right Menu</ion-title>
        </ion-toolbar>
      </ion-header>
    </ion-menu>
  
    <ion-content main id="content">
        <p>Hello World!</p>
    </ion-content>
 </ion-split-pane>

```

**Expected Behavior**
ion-menu-button should open the left menu

**Comment by redwolf2** [comment]
Can't reproduce with [Ionic v4-beta.5], seems to be fixed.

**Comment by redwolf2** [comment]
<div class="ion-page" main>
  <ion-header>
      <ion-toolbar>
          <ion-buttons slot="start">
              <ion-menu-button></ion-menu-button>
          </ion-buttons>
        <ion-title>Home</ion-title>
    </ion-toolbar>
  </ion-header>
  <ion-content id="content">
    <p>Hello World!</p>
  </ion-content>
</div>

<ion-menu side="end" contentId="content">
  <ion-header>
    <ion-toolbar>
      <ion-title>Right Menu</ion-title>
    </ion-toolbar>
  </ion-header>
</ion-menu>

**Comment by JoeBoxr** [comment]
Hey redwolf2.  The two split-panes are intentional because I have a left menu which needs to expand with the browser and a right menu that appears and disappears (depending on the browser width) on a Tab.

I can't accomplish this with just 1 split pane and i'm able to do this with ionic 3 just fine.

Regards

**Comment by redwolf2** [comment]
Ok, without tabs the above implementation would work. I didn't gave it a try.
