### ISSUE TITLE
[Ionic 4] when I use tabs component the Attribute "tabbar-layout","scrollable" are not working

### ISSUE THREAD

**Issue by microwin168** [ionic-team/ionic#15201]
when I use tabs component the Attribute "tabbar-layout","scrollable" are not working.

**Comment by brandyscarney** [comment]
Thanks for the issue! Please update to `beta.3` in order to fix `tabbar-layout`. This was fixed by this issue: https://github.com/ionic-team/ionic/issues/14611

The `scrollable` property has been temporarily removed.

**Comment by microwin168** [comment]
Which version  the  scrollable property will be added  again?  And I want to know the planning when the release version will be release.
@brandyscarney Thank you so much.

**Comment by confused-pv** [comment]
Hi @brandyscarney,
Which version the scrollable property will be added again?

**Comment by brandyscarney** [comment]
Scrollable was added to the segment component in the [4.0.0-beta.15](https://blog.ionicframework.com/ionic-release-v4-beta-15-out-today/) release by the following PR: https://github.com/ionic-team/ionic/pull/16273.
