### ISSUE TITLE
[4.0.0-beta.11] Life cycle destroy does not run

### ISSUE THREAD

**Issue by 777wills** [ionic-team/ionic#15205]
# Bug Report

**Ionic Info**
![image](https://user-images.githubusercontent.com/36114477/45642785-e545c280-ba7e-11e8-82be-1a51b184eb61.png)

**Describe the Bug**
When I navigate from the home to user route, the life cycle destroy of the home is not executed

**Steps to Reproduce**
1. Go to '/home'
2. Click on 'GO USERS'
3. the ngOndestroy of the home is not executed

**Related Code**
https://github.com/777wills/destroy-ionicV4

**Expected Behavior**
When leaving the home component you should run ngOndestroy and show in console 'destroy'

![image](https://user-images.githubusercontent.com/36114477/44222070-0ac27200-a149-11e8-843c-93606d795bd3.png)

**Comment by 777wills** [comment]
In beta5 the problem continues

**Comment by paulstelzer** [comment]
Can confirm this issue in beta.7 too. For me it's only happening if I switch from one page to another very fast (few under 200ms). I deactivated the animation but the problem occurs that the component will not be destroyed and is so available so it is in front of the new component and no navigation on the page is possible

**Comment by 777wills** [comment]
The problem continues with the beta.7.
If I delay more than 200 ms, the component is not destroyed either.
I updated the repository [https://github.com/777wills/destroy-ionicV4](url)
Please try this repository

**Comment by 777wills** [comment]
The problem continues with the beta.8

**Comment by 777wills** [comment]
@paulstelzer

**Comment by 777wills** [comment]
The problem continues with the beta.11
@IonicProSupport

**Comment by paulstelzer** [comment]
@777wills you don't need to mention IonicProSupport, just mention the Ionic Core Dev team like @manucorporat so they put it on their board.

For me it's only happened if i switch very fast from one page to another

**Comment by 777wills** [comment]
Ok,
Did you try the github repository? [https://github.com/777wills/destroy-ionicV4](url).

Anyway, it should not happen if you go very fast from one page to another

**Comment by paulstelzer** [comment]
Ah okay, what you describe is normal behaviour and not a bug or something like that.

Take a look at the console and you see that the page is hidden:

![firefox_2018-09-18_08-11-21](https://user-images.githubusercontent.com/20501666/45667806-df052400-bb1a-11e8-8a68-7ea03ef33acc.jpg)

Why? Because Ionic can go back to the previous page and therefore the page has not to be destroyed. 

Add to your constructor (NavController imports from `@ionic/angular`)

`private nav: NavController`

and instead of `this.router.*` you use `this.nav.navigateRoot(['users']);`

Then the destroyHome will appear in console log

**Comment by 777wills** [comment]
Thanks for the clarification.
You're right that it works this way with Navcontroller, but it's not logical with Router.
IONIC specifies that you can use the Angular router and its methods, then, the page should be destroyed with this.router. *.
Is it possible that this is solved for those who want to use Router?
Thank you.

**Comment by paulstelzer** [comment]
@777wills I don't know, maybe it's already possible with Angular Router, you have to look into the source code. I am just a user of Ionic 4, not member of the Ionic Dev team, so I cannot answer your question

**Comment by 777wills** [comment]
Ok, thanks

**Comment by 777wills** [comment]
Cleared in #15633

**Comment by jmchaves** [comment]
@paulstelzer so how can we unsubscribe from observables? In angular this should be in `ngOnDestroy` function, but the previous page does not trigger it. 
 
https://angular.io/guide/lifecycle-hooks#ondestroy
