### ISSUE TITLE
[Ionic v4-beta.3] Ionic v4 won't work with older Android System WebViews

### ISSUE THREAD

**Issue by chrisbinnefeld** [ionic-team/ionic#15214]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.0 (/usr/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.4

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.2, (and 4 other plugins)

System:

   Android SDK Tools : 26.0.1
   NodeJS            : v10.8.0 (/usr/bin/node)
   npm               : 6.3.0
   OS                : Linux 4.4

Environment:

   ANDROID_HOME : /opt/android
```

**Describe the Bug**
Ionic v4 won't work with older Android System WebViews.

**Additional Context**

We are currently testing and developing with Ionic v4 on devices with older web views. 

One of them is a Android N (7.1.2) device without any Google Mobile Services (GMS). So we have to use the standard **Android System WebView** (version 52.0.2743.100). When running the _Ionic Blank Starter_ build with _Cordova_ we are getting following result: 

`Uncaught SyntaxError: Unexpected token function    vendor.js:65052 `

![image](https://user-images.githubusercontent.com/36038291/44256069-525c0300-a208-11e8-8ede-514c2897f4ec.png)

**Unfortunately the manufacturer of the device says we can't upgrade to more recent version.**

The other device is an Android L (5.1.1) which is also shipped without GMS. Here we have an **Android System WebView** version of  55.0.2883.91 with following result: 

![image](https://user-images.githubusercontent.com/36038291/44257171-7f5de500-a20b-11e8-9b49-eb779cb6fdbb.png)

The app is successfully loaded, but the icon in the button on the top right is not shown.

```
<ion-header>
  <ion-toolbar>
    <ion-title>
      Ionic Blank
    </ion-title>
    <ion-buttons slot="end">
      <ion-button>
        <ion-icon slot="icon-only" name="person"></ion-icon>
      </ion-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>

<ion-content padding>
  The world is your oyster.
  <p>If you get lost, the <a target="_blank" href="https://ionicframework.com/docs">docs</a> will be your guide.</p>
</ion-content>
```

Everything works while runinng on a more recent webview version (68.0.3440.91): 

![image](https://user-images.githubusercontent.com/36038291/44257336-fbf0c380-a20b-11e8-8bd1-42e674089a3b.png)

Maybe the problem is related to this issue #15191?

**Comment by netsesame2** [comment]
Confirm above issues.

**Comment by ugurozturk** [comment]
Just created new project and i had the same issue 

`Uncaught SyntaxError: Unexpected token function`

**Comment by dberniell** [comment]
ASW Android System Webview 52.0.2743.100 neither runs. Is there going to be a solution for old ASW?

**Comment by paulstelzer** [comment]
Related to #15438
