### ISSUE TITLE
[Ionic v4-beta.3] Bug navigation between tab page & no page tab - back button redirects to wrong tab

### ISSUE THREAD

**Issue by Anthony2539** [ionic-team/ionic#15216]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.2, (and 4 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.1.1
   NodeJS     : v10.6.0 (/usr/local/bin/node)
   npm        : 6.4.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
I have an application with a tabs ( 5 pages home, search, map , info and tarif).
From the search page i can go on a non-tab page like this ```this.router.navigate(['station'], { queryParams: station}); ```
On the station page i have a back button to return to the search page ``` <ion-back-button text=""></ion-back-button> ```
The back button disappear at the second time.
Here are some additional informations:

**tabs.router.module.ts**
```
const routes: Routes = [
  {
    path: 'tabs',
    component: TabsPage,
    children: [
      {
        path: 'home',
        outlet: 'home',
        component: HomePage
      },
      {
        path: 'search',
        outlet: 'search',
        component: SearchPage
      },
      {
        path: 'map',
        outlet: 'map',
        component: MapPage
      },
      {
        path: 'info',
        outlet: 'info',
        component: InfoPage
      },
      {
        path: 'tarif',
        outlet: 'tarif',
        component: TarifPage
      }
    ]
  },
  {
    path: '',
    redirectTo: '/tabs/(home:home)',
    pathMatch: 'full'
  }
];
```

**app-routing.module.ts**
```
const routes: Routes = [
  { path: '', loadChildren: './tabs/tabs.module#TabsPageModule' },
  { path: 'map', loadChildren: './map/map.module#MapPageModule' },
  { path: 'search', loadChildren: './search/search.module#SearchPageModule' },
  { path: 'station', loadChildren: './station/station.module#StationPageModule' },
  { path: 'info', loadChildren: './info/info.module#InfoPageModule' },
  { path: 'tarif', loadChildren: './tarif/tarif.module#TarifPageModule' }
];
```

i don't know if it's my bad or a bug ?

**Steps to Reproduce**
1. Click on tab menu to go to search page
2. From search page go to station page ( a non-tab page)
3. Go back to search page with back button
4. Click on the same station to go on station page
5. The back button disappear, i can't go back on search page

**Expected Behavior**
Fix nav when i from a non-tab page

**Additional Context**
I have a log when i go to the station page at the second time
```ion-router-outlet.js:32 router-outlet destroyed```

And i have an another issue, how i can conserve the tab menu on my station page ?

**Comment by kensodemann** [comment]
Note that this sample app: https://github.com/kensodemann/test-prolea which I created to demo a different but related issue (#14861) also shows this behavior if the person picking this up needs a sample app to reproduce this.

**Comment by wesleyxiao** [comment]
same issue here: router-outlet destroyed

**Comment by magicfa** [comment]
any news on that?
I took a look at the ionic-conference app because it's working there.
Interesting implementation..

**Comment by patrickhofer** [comment]
Same issue here. Navigating from a subpage backwards lands on the first tab instead the last selected. 

More: https://stackoverflow.com/questions/52268092/navigate-back-to-tab-index-with-ionic-4/52268576#52268576

**Comment by Chethannp** [comment]
Any update on this ?

**Comment by kkagill** [comment]
I'm still having the same issue.

**Comment by contactjavas** [comment]
Same here, the `router-outlet destroyed` issue makes the page transition becomes rude, without animation (at least in ios).

Simple reproduce:

- Create page with tabs
- In first tab (say, home tab), create list of items.
- Set the item's `href` to item detail page.
- Click it, and you'll be redirected to the detail page.
- Now refresh browser, you will stay in detail page.
- Press `ion-back-button` (with `defaultHref`). You'll be moved to home tab.
- Now from home tab, click on that item again, and the issue will occur.

**Comment by shuki770** [comment]
I solved the problem by navigate with ionic NavController instead of angular router
I changed the following line:

this.router.navigateByUrl(url)

to

this.navController.navigateForward(url)

**Comment by danielehrhardt** [comment]
> I solved the problem by navigate with ionic NavController instead of angular router
> I changed the following line:
> 
> this.router.navigateByUrl(url)
> 
> to
> 
> this.navController.navigateForward(url)

Does not work for me

**Comment by jsalasdev** [comment]
I'm still having the same issue.

**Comment by bredexporno69** [comment]
removing routerDirection fixed the issue for me. No more router-outlet destroyed. Dobby is a free elf

**Comment by lampi87** [comment]
Same for me.
Neither navCtrl.navigateForward, nor router.navigateByUrl works for me

**Comment by anshnagrath** [comment]
this.navCtrl.goBack();
worked for me;
it is like subsitute to this.navCtrl.pop();
in ionic 4

**Comment by urbanjoe** [comment]
The "router-outlet destroyed" issue is a pain and we mixed it up with a tab problem on our side. The "router-outlet destroyed" appears, navigation between child pages:

https://forum.ionicframework.com/t/ionic-4-navigate-between-child-routes-router-outlet-destroyed/149902
!

**Comment by paulstelzer** [comment]
We've released beta.18 now with another refactor of tabs. Could you check if the issue is fixed? Please keep in mind the breaking changes: https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#400-beta18-2018-12-13

**Comment by lampi87** [comment]
Unfortunately issue is still reproducible for me.
Page structure:
Page 'test' defined in app-routing.module.ts
Tab 1 (no childs)
Tab 2 (no childs)
Tab 3, one child
If I change to Tab 3 -> Tab 3 child and click on ion-button to open page, e.g /test1, via routerLink. On click on <ion-back-button defaultHref="/tabs/tab3/child"></ion-back-button> the page /tabs/tab1 is opened
Same issue if tab 3 has no childs and page /test is opened. On clicking back button, tab1 is opened

**Comment by paulstelzer** [comment]
Then please create a repo so we can take a look at it

**Comment by lampi87** [comment]
You can find repo at: https://github.com/lampi87/ionic-bug-test
There are 3 pages in tabs "home", "calendar" and "user". On user page a button is shown to open "/settings" page. This page is intended to be shown without tabs at bottom. If you press back button on settings page, "home" is opened instead of "user"

**Comment by paulstelzer** [comment]
Ah okay, as you said: 

> This page is intended to be shown without tabs at bottom.

This will be the issue because you will destroy the tabs (without looking into it) and if you want to go back, he creates the tab component again and so you start at the first page.

**Comment by paulstelzer** [comment]
I tested it and yes, it's working. E.g. if you are using `routerlink`, just add `routerDirection="forward"`:

```
    <ion-item [routerLink]="p.link"  [routerDirection]="'forward'" routerLinkActive="highlight" [routerLinkActiveOptions]="{ exact: true }" color="primary" lines="none"
      button>
      <ion-icon [name]="p.icon" slot="start"></ion-icon>
      <ion-label text-wrap>{{p.title | translate}}</ion-label>
    </ion-item>
```

PS: My snippet contains some content from my app, so you cannot copy it 1:1 in your app

**Comment by lampi87** [comment]
I've updated my repo (https://github.com/lampi87/ionic-bug-test) and issue is still reproducible
I tried to open page with
`<ion-button color="primary" expand="block" routerLink="/settings" routerDirection="forward">Settings</ion-button>`
and
`<ion-button color="primary" expand="block" routerLink="/settings" [routerDirection]="'forward'">Settings</ion-button>`
but on ion-back-button tab1 is opened.

**Comment by paulstelzer** [comment]
You made everything right (btw, `[routerDirection]="'forward'`" is the same like `routerDirection="forward"`), but you have this route inside your routing:

```
      {
        path: '',
        redirectTo: '/tabs/home',
        pathMatch: 'full',
      },
```

This leads that the user will be redirected to the home. Remove it and run again, and you will see it's working:

![2018-12-14_15-01-46](https://user-images.githubusercontent.com/20501666/50007433-32b7ca00-ffb1-11e8-99ad-2be6594a38b3.gif)

**Comment by edoardoo** [comment]
We're facing the very same issue on iOS.
Is there any ETA on this? 
It makes the whole app completely unreliable.

**Comment by osmarjunior** [comment]
Still an issue in 4.0.0-rc.1

**Comment by bossjon** [comment]
I do not use tabs, because this error does not allow using pages without tabs.

For example, I have a search page, and I want to use it anywhere, on a users page, chats list, or where the data list is located. You can use the search page by passing only the parameter. I remember when on the second version of ionic we just hid tabs with styles.

Thank you guys, you are doing a great job.

**Comment by aftabkhatri** [comment]
i developing app in ionic4,  i have latest cli 4.8.
i am facing same issue, i have 3 page. 
page1, page2, page3.
i go to page1>page2>page3.
now if i use only hardware button then it working well, if i use only back button of app then its also working well. 

but if i use app back button for page3 to page2 and after that i used hardware back button then it go to page3 instant of page1.
and in page3 app back button is hide.

**Comment by deemi47** [comment]
+1 facing same issue

**Comment by imagineowl** [comment]
Not sure if this is the solution, but it worked for me.

Ionic CLI adds the child page to `app-routing.module.ts` instead of `tabs.router.module`. Makes sense since Ionic CLI wouldn't know if you have tabs or not. (or does it?)

I removed `{ path: 'station', loadChildren: './station/station.module#StationPageModule' }` from `app-routing.module.ts` and nested it under the corresponding tab in `tabs.router.module`

Referencing the original post, it'd look something like this
```
{
        path: 'search',
        outlet: 'search',
        component: SearchPage,
        children: [
          {
            path: 'station',
            loadChildren: './station/station.module#StationPageModule' }
          }
        ]
      },
```

I also had to update the router link to `/tabs/search/station` from ,in this case, the ion-item on the station page or the .ts page.

Now it should go 'back' to the tab it came from.

**Comment by epiphanatic** [comment]
I'm facing the same and couldn't get any of the above to work.

As a workaround, I put a parameter (:tab) in the path in the app routing module to hold the full path of the tab that I was on whenever an item is clicked to take you to the child. So when you click said item, you just pass the full path as a parameter that would take you back to the tab you were in, and do this for however many tabs you have. Then in the child ngOnInit I used `this.route.snapshot.paramMap.get('tab');` to get that path, set it as a class variable in the .ts file, put a button with a back icon in the template to simulate the real back button `<ion-button shape="round" (click)="goBack()"><ion-icon name="arrow-back"></ion-icon></ion-button>,` then on click use the router to navigate to the full path of what was stored on load `  goBack() {
    this.router.navigate([this.backHref]);
  }`

It doesn't fix the problem, but works for now. Also I'm sure that there are other workarounds using the router (like above), I'm just not that good with it.

**Comment by aftabkhatri** [comment]
Thanks for the issue! There were made some changes in the latest commits (#17182) - just install the latest dev build `(npm install @ionic/angular@4.0.0-dev.201901211351.59bd823).`

If you want to overwrite the default behaviour, you can also use:
`this.platform.backButton.subscribeWithPriority(9999, () => {
// You decide what happens 
});
`
Using hardware back button , go to back page, close menu, close alert, close action sheet, close toast, close popover, close model etc add this code app.component.ts

`hardwareBackButton() {
    let options: NativeTransitionOptions = {
        direction: 'right',
        duration: 500,
        slowdownfactor: 3,
        androiddelay: 150
    };
    this.platform.backButton.subscribeWithPriority(9999, async () => {
        // close toast
        try {
            const element = await this.toastController.getTop();
            if (element) {
                element.dismiss();
                return;
            }
        } catch (error) {}
        // close alert
        try {
            const element = await this.alertController.getTop();
            if (element) {
                element.dismiss();
                return;
            }
        } catch (error) {}
        // close action sheet
        try {
            const element = await this.actionSheetCtrl.getTop();
            if (element) {
                element.dismiss();
                return;
            }
        } catch (error) {}
        // close popover
        try {
            const element = await this.popoverCtrl.getTop();
            if (element) {
                element.dismiss();
                return;
            }
        } catch (error) {}
        // close modal
        try {
            const element = await this.modalCtrl.getTop();
            if (element) {
                element.dismiss();
                return;
            }
        } catch (error) {
            console.log(error);
        }
        // close side menua
        try {
            const element = await this.menu.getOpen();
            if (element) {
                this.menu.close();
                return;
            }
        } catch (error) {}
        if (this.router.url == '/startmain' || this.router.url == '/home') {
            if (this.lastTimeBackPress == 0) {
                const toast = await this.toastController.create({
                    message: 'Press back again to exit App.',
                    position: 'bottom',
                    duration: 2000,
                    color: 'medium',
                    animated: true,
                    mode: 'ios'
                });
                await toast.present().then(() => {
                    this.lastTimeBackPress = 1;
                });
                let TIME_IN_MS = 4000;
                let hideFooterTimeout = setTimeout(() => {
                    // somecode
                    this.lastTimeBackPress = 0;
                }, TIME_IN_MS);
            } else {
                navigator['app'].exitApp(); // work in ionic 4
            }
        } else if (this.routerOutlet && this.routerOutlet.canGoBack()) {
            this.nativePageTransitions.slide(options);
            this.routerOutlet.pop();
        } else {
            // this.platform.exitApp(); // Exit from app
            navigator['app'].exitApp(); // work in ionic 4
        }
    }) 
}`

Thanks

**Comment by bossjon** [comment]
@aftabkhatri Still not working. As @paulstelzer [#447334318](https://github.com/ionic-team/ionic/issues/15216#issuecomment-447334318) described.

I think the problem is in redirect in children tabs route. If you remove the redirect, then everything works.
```
const routes: Routes = [
  {
    path: 'tabs',
    component: TabsPage,
    children: [
      {
        path: 'tab1',
        children: [
          {
            path: '',
            loadChildren: '../tab1/tab1.module#Tab1PageModule'
          }
        ]
      },
      {
        path: 'tab2',
        children: [
          {
            path: '',
            loadChildren: '../tab2/tab2.module#Tab2PageModule'
          }
        ]
      },
      {
        path: 'tab3',
        children: [
          {
            path: '',
            loadChildren: '../tab3/tab3.module#Tab3PageModule'
          }
        ]
      },
      // {
      //  path: '',
      //  redirectTo: '/tabs/tab1',
      //  pathMatch: 'full'
      // }
    ]
  },
  {
    path: '',
    redirectTo: '/tabs/tab1',
    pathMatch: 'full'
  }
];
```
Ps: maybe I don’t understand something, but I think the problem is in the redirect and when you press the back button, the redirect goes.

**Comment by aftabkhatri** [comment]
use this will work @bossjon
<ion-button color="primary" expand="block" routerLink="/settings" routerDirection="forward">Settings</ion-button>

**Comment by bossjon** [comment]
@aftabkhatri Did you even read what @paulstelzer wrote? Without redirect everything works, but what about redirect? When the user goes to the` /tabs` page, the page is blank. @paulstelzer knows what the issue is.

I think you get confused and you are discussing another issue.

**Comment by qiluo** [comment]
still same issue on latest 4.0.0

**Comment by bossjon** [comment]
@manucorporat What do you think about this issue?

**Comment by proartti** [comment]
We are having this issue here as well. If I initiate the navigation outside the Tabs router or navigate to a page that is outside of the Tabs router I cannot access the pages nested over the Tabs router.

The only solution that worked for us is to nested all the pages inside the Tabs and hide the ion-tab-bar on the pages I don't want it to appears.

<ion-tab-bar slot="bottom" color="secondary" *ngIf="tabsLayout">

**Comment by qiluo** [comment]
> We are having this issue here as well. If I initiate the navigation outside the Tabs router or navigate to a page that is outside of the Tabs router I cannot access the pages nested over the Tabs router.
> 
> The only solution that worked for us is to nested all the pages inside the Tabs and hide the ion-tab-bar on the pages I don't want it to appears.
> 
> <ion-tab-bar slot="bottom" color="secondary" *ngIf="tabsLayout">
> 
> Of course, this is far from the ideal solution but it's a good way to work around this.

No, you don't have to do this. You can just not use ion-back-button, instead you add a normal button, a back style, and call `navCtrl.back()` in the click event. Then you get your expectation
```
<ion-button (click)="navCtrl.back()">
        <ion-icon slot="icon-only" name="arrow-round-back" color="dark"></ion-icon>
</ion-button>
```

**Comment by bossjon** [comment]
@qiluo I also thought for a long time why ionic uses the method nav.pop(), instead nav.back() method. [ion-back-button.ts:L26](https://github.com/ionic-team/ionic/blob/master/angular/src/directives/navigation/ion-back-button.ts#L26)

`nav.pop();`
This is the recommended way to go back when you are using `ion-router-outlet`

`nav.back();`
It will use the standard `window.history.back()` under the hood, but featuring a `back` animation.

Ps: Why not use the `window.history.back()` method, or maybe as it was tested and decided to use the `nav.pop()` method. In general, we will wait for an official response.

**Comment by qiluo** [comment]
@bossjon, it's `routerOutlet.pop()`, not `nav.pop()`, is there any difference?

Actually I tried nav.pop(), it caused weird navigation in my app, meanwhile `nav.back()` work around anyway. Wait for official fix

**Comment by bossjon** [comment]
@qiluo, there is no difference, but I think the issue is where `outlet` length checks. [stack-controller.ts#L78](https://github.com/ionic-team/ionic/blob/master/angular/src/directives/navigation/stack-controller.ts#L78)

**Comment by bossjon** [comment]
any news on that?

**Comment by servrox** [comment]
I expirienced same cause I didn't define the continuing routes in the child-block. 
Routing may seem to work, but things like ion-back-button are fucked up.

Created a demo using the ion-back-button and different approaches for route definition.
I also used lazy loading for every page.

Maybe my explanation + code helps here (before creating the demo I stumbled on this post).

https://github.com/servrox/demo-ionic-tab-routing

**Comment by bossjon** [comment]
@servrox, The way you did, it works, but we're talking about pages with no tabs. Like a global page that can be opened anywhere, and you can go back.

**Comment by anrip** [comment]
I'm still having the same issue.

**Comment by paul-landaeta-tierconnect-com** [comment]
This is a moment fix for me 
controller
`back() {
    this.router.navigate(['tabs/tab1']);
  }`
html 
`
 <ion-buttons slot="start">
      <ion-back-button (click)="back()"></ion-back-button>
    </ion-buttons>
`

**Comment by bossjon** [comment]
@paul-landaeta-tierconnect-com, The user can open the page from any tab or any other page, and how will you define the back url?
`ion-back-button` is created for this.

**Comment by TioChachi29** [comment]
In `tabs.router.module.ts` change this:

`const routes: Routes = [
  {
    path: 'tabs',
    component: TabsPage,
    children: [
...
{
        path: '',
        redirectTo: '/tabs/tab1',
        pathMatch: 'full'
}`

for this (remove `/tab1`):

`{
        path: '',
        redirectTo: '/tabs',
        pathMatch: 'full'
}`

This solves the back button of the topbar as the physical of android. It works well for me.

**Comment by servrox** [comment]
check this: https://github.com/servrox/demo-ionic-tabs-back-button

**Comment by webmozart** [comment]
I can confirm [the issue described in the gif by @paulstelzer](https://github.com/ionic-team/ionic/issues/15216#issuecomment-447334318) in Ionic 4.0.2.

**Comment by bossjon** [comment]
@servrox, Thanks for the answer. Your option works, but when you navigate back (swipe) on iOS, then the [ion-router-outlet.ts#L197](https://github.com/ionic-team/ionic/blob/master/angular/src/directives/navigation/ion-router-outlet.ts#L197) or [stack-controller.ts#L78](https://github.com/ionic-team/ionic/blob/master/angular/src/directives/navigation/stack-controller.ts#L78) function runs. Because of this, your solution does not work, I think the (ionic) developers will notice your decision and fix the `navigation`. @paulstelzer 

Ps: I also thought for a long time how to add a custom version of the `navigation` to the application, but I could not find a way.

**Comment by servrox** [comment]
@bossjon uh ur right 👍🏻 completely forgot about navigation back via swipe gesture..
I added this case to my [demo](https://github.com/servrox/demo-ionic-tabs-back-button).

[ion-back-button-tabs](https://github.com/servrox/demo-ionic-tabs-back-button#2-using-ion-back-button-tabs-component-s-global-page-two) fully support swipe gestures now!
For the [workaround](https://github.com/servrox/demo-ionic-tabs-back-button#1-passing-previous-page-s-global-page-one) it seemed easiest to disable the gesture for the particular page.

**Comment by bossjon** [comment]
@servrox I think this issue is not in the priority of the ionic team, but this issue makes the tabs unnecessary. I also tried a lot of ways like you, but I don’t want to write another component for this and maintain it.
Thanks again for the proposed solution to this issue.

**Comment by dafi** [comment]
@TioChachi29 workaround works for me, it sounds simple and I don't need to change html or ts files, so I can rearrange code (this already happened) without problem.
Honestly I don't understand if this can create some side effect

**Comment by TioChachi29** [comment]
@dafi yes, if it has a side effect, when `ionic serve` is executed on some occasions the content of the `tabs` is not displayed, but when executing it in Android or in iOS this does not happen.  I do not know if there is another problem.

**Comment by dafi** [comment]
@TioChachi29 if the problem occurs only with `ionic serve` I can tolerate it, thanks for the hint

**Comment by nicsaravanan** [comment]
> In `tabs.router.module.ts` change this:
> 
> `const routes: Routes = [ { path: 'tabs', component: TabsPage, children: [ ... { path: '', redirectTo: '/tabs/tab1', pathMatch: 'full' }`
> 
> for this (remove `/tab1`):
> 
> `{ path: '', redirectTo: '/tabs', pathMatch: 'full' }`
> 
> This solves the back button of the topbar as the physical of android. It works well for me.

Its solved the issue, Thanks

**Comment by epetre** [comment]
> In `tabs.router.module.ts` change this:
> 
> `const routes: Routes = [ { path: 'tabs', component: TabsPage, children: [ ... { path: '', redirectTo: '/tabs/tab1', pathMatch: 'full' }`
> 
> for this (remove `/tab1`):
> 
> `{ path: '', redirectTo: '/tabs', pathMatch: 'full' }`
> 
> This solves the back button of the topbar as the physical of android. It works well for me.

It solves the issue, but the url is the wrong one at the top, it's the root tab url (/tabs in my case). Also if you tap the current tab, it tries to load the root tab url.

**Comment by carlesferreiro** [comment]
> In `tabs.router.module.ts` change this:
> 
> `const routes: Routes = [ { path: 'tabs', component: TabsPage, children: [ ... { path: '', redirectTo: '/tabs/tab1', pathMatch: 'full' }`
> 
> for this (remove `/tab1`):
> 
> `{ path: '', redirectTo: '/tabs', pathMatch: 'full' }`
> 
> This solves the back button of the topbar as the physical of android. It works well for me.

Thanks!
It solves the issue but if you navigate forward to /tabs it will not select the default tab. So, you'll have always to specify the full url of the default tab (/tabs/tab1 or whatever).

**Comment by liamdebeasi** [comment]
Hi there,

This issue has been resolved, and I have published a nightly build of Ionic with the fix. You can install it with `npm i @ionic/angular@dev`.

Please let me know if you are still running into any issues with this. 

Thanks!

**Comment by evgeniyefimov** [comment]
@liamdebeasi hi!

Thank you for the fix. What about navigation back (pop) programmatically? When I call navCtrl.pop from a nested outlet which is not in a tab, it redirects back to the right tab which has some nav stack, but then navCtrl.pop doesn't work. With ion-back-button it works fine after fix.

**Comment by liamdebeasi** [comment]
Hi there,

Please [open a new Bug Report](https://github.com/ionic-team/ionic/issues/new?assignees=&labels=&template=bug_report.md&title=bug%3A+) for this issue.

Thanks!
