### ISSUE TITLE
[Ionic v4-beta.3] Slow page transition

### ISSUE THREAD

**Issue by meta0102** [ionic-team/ionic#15215]
Ionic:

   ionic (Ionic CLI)          : 4.0.6 (C:\Users\\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.3.0-next.0
   OS                : Windows 10

Environment:

   ANDROID_HOME : C:\Users\\AppData\Local\Android\Sdk

the page transitions are much slower than in ionic 3 (same css, code, ...)
check the toolbar (first is ionic 3, 2nd is ionic 4 beta 3)
![17-08-_2018_11-34-30](https://user-images.githubusercontent.com/14222016/44259556-1f1e7180-a212-11e8-93c5-41d9fb931268.gif)

thanks

**Comment by paulstelzer** [comment]
Is this issue still exist in beta.17?
