### ISSUE TITLE
My application don't launch after install ionic native push plugin

### ISSUE THREAD

**Issue by veronesecoms** [ionic-team/ionic#15222]
# Bug Report

**Ionic Info**
C:\Users\jsoftwares1\Desktop\Ionic\jcapp\appIonic>ionic info
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)  : 4.0.6 (C:\Users\jsoftwares1\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.2.0
   OS                : Windows 10

Environment:

   ANDROID_HOME : C:\Users\jsoftwares1\Desktop\tools\lib

**Describe the Bug**

After i installed the ionic push notification i get a message error and my application don't launch

**Steps to Reproduce**

I installed the ionic cordova plugin phone-gap-plugin-push:

> > cordova plugin add phonegap-plugin-push --save
> Unmet project requirements for latest version of phonegap-plugin-push:
>     cordova-android (7.0.0 in project, >=7.1.0 required)
> Fetching highest version of phonegap-plugin-push that this project supports: 2.1.3 (latest is 2.2.3)
> Installing "phonegap-plugin-push" for android
> Android Studio project detected
> Subproject Path: CordovaLib
> Subproject Path: app
> Adding phonegap-plugin-push to package.json
> Saved plugin info for "phonegap-plugin-push" to config.xml

After, i install the ionic native push:

> npm install --save @ionic-native/push
> + @ionic-native/push@4.12.0
> updated 1 package in 22.385s

Ok, i run ionic cordova run android and receive:

> File google-services.json is missing. The Google Services Plugin cannot function without it.
>    Searched Location:
>   C:\Users\jsoftwares1\Desktop\Ionic\jcapp\appIonic\platforms\android\app\src\debug\google-services.json
>   C:\Users\jsoftwares1\Desktop\Ionic\jcapp\appIonic\platforms\android\app\google-services.json

Ok, i go to the firebase google site and download my google-services.json and put in the same location of my build.gradle:

C:\Users\jsoftwares1\Desktop\Ionic\jcapp\appIonic\platforms\android\app

So now this message disappear, but now when i run ionic cordova run android my application don't launch:

> cordova run android
Android Studio project detected
ANDROID_HOME=C:\Users\jsoftwares1\Desktop\tools\lib
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_181
studio
Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_4sqffqfiker115umi95rt5oa1.run(C:\Users\jsoftwares1\Desktop\Ionic\jcapp\appIonic\platforms\android\app\build.gradle:144)
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:prepareLintJar UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:platformAttrExtractor UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:javaPreCompileDebug UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
:CordovaLib:processDebugJavaRes NO-SOURCE
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugAidl UP-TO-DATE
:CordovaLib:packageDebugRenderscript NO-SOURCE
:app:compileDebugRenderscript UP-TO-DATE
:app:checkDebugManifest UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:prepareLintJar UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:processDebugGoogleServices
Parsing json file: C:\Users\jsoftwares1\Desktop\Ionic\jcapp\appIonic\platforms\android\app\google-services.json
:app:mergeDebugResources
:app:createDebugCompatibleScreenManifests UP-TO-DATE
:app:processDebugManifest
:app:splitsDiscoveryTaskDebug UP-TO-DATE
:app:processDebugResources
:app:generateDebugSources
:app:javaPreCompileDebug
Note: C:\Users\jsoftwares1\Desktop\Ionic\jcapp\appIonic\platforms\android\app\src\main\java\com\adobe\phonegap\push\FCMService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\jsoftwares1\Desktop\Ionic\jcapp\appIonic\platforms\android\app\src\main\java\com\adobe\phonegap\push\PushPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:app:compileDebugJavaWithJavac
:app:compileDebugNdk NO-SOURCE
:app:compileDebugSources
:CordovaLib:mergeDebugShaders UP-TO-DATE
:CordovaLib:compileDebugShaders UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets
:app:transformClassesWithStackFramesFixerForDebug
:app:transformClassesWithDesugarForDebug
:app:transformClassesWithDexBuilderForDebug
:app:transformClassesWithMultidexlistForDebug
:app:transformDexArchiveWithDexMergerForDebug
:CordovaLib:compileDebugNdk NO-SOURCE
:CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
:CordovaLib:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
:CordovaLib:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNativeLibsWithMergeJniLibsForDebug
:app:processDebugJavaRes NO-SOURCE
:app:transformResourcesWithMergeJavaResForDebug
:app:validateSigningDebug
:app:packageDebug
:app:assembleDebug
:app:cdvBuildDebug

BUILD SUCCESSFUL in 1m 58s
47 actionable tasks: 16 executed, 31 up-to-date
Built the following apk(s):
        C:\Users\jsoftwares1\Desktop\Ionic\jcapp\appIonic\platforms\android\app\build\outputs\apk\debug\app-debug.apk
ANDROID_HOME=C:\Users\jsoftwares1\Desktop\tools\lib
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_181
No target specified, deploying to device 'EBAZB6009385'.
none
Skipping build...
Built the following apk(s):
        C:\Users\jsoftwares1\Desktop\Ionic\jcapp\appIonic\platforms\android\app\build\outputs\apk\debug\app-debug.apk
Using apk: C:\Users\jsoftwares1\Desktop\Ionic\jcapp\appIonic\platforms\android\app\build\outputs\apk\debug\app-debug.apk
Package name: japp.jcontrole

I do a CTRL + C and get this message:

TypeError: Invalid data, chunk must be a string or buffer, not object
    at WriteStream.Socket.write (net.js:704:11)
    at process.<anonymous> (C:\Users\jsoftwares1\AppData\Roaming\npm\node_modules\ionic\bin\ionic:9:63)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Expected Behavior**
Launch success my application

**Comment by paulstelzer** [comment]
This is related to Cordova / Cordova Plugin Push and not Ionic
