### ISSUE TITLE
[Ionic v4] migrate tabs from v3 do not work inside a modal

### ISSUE THREAD

**Issue by goelectricstations** [ionic-team/ionic#15226]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

Ionic:

   ionic (Ionic CLI)          : 4.1.0 (C:\Users\Computer\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.3.0-next.0
   OS     : Windows 10

Environment:

   ANDROID_HOME : not set

tabs.html

    <ion-tabs tabbarPlacement="top" tabbarLayout="icon-end">
      <ion-tab label="{{dict.itinerary_clear.toUpperCase()}}" icon="add" href="/itinerary-tabs/(home:home)">
        <ion-router-outlet name="home"></ion-router-outlet>
      </ion-tab>
      <ion-tab label="{{dict.itinerary_savedItinerary.toUpperCase()}}" icon="list" href="/itinerary-tabs/(list:list)">
        <ion-router-outlet name="list"></ion-router-outlet>
      </ion-tab>
      <ion-tab label="{{dict.menu_guida.toUpperCase()}}" icon="information" href="/itinerary-tabs/(guide:guide)">
        <ion-router-outlet name="guide"></ion-router-outlet>
      </ion-tab>
    </ion-tabs>

tabs.ts
const routes: Routes = [
  {
    path: 'itinerary-tabs',
    component: ItineraryTabsPage,
    children: [
      {
        path: 'home',
        outlet: 'home',
        component: ItineraryHomePage
      },
      {
        path: 'list',
        outlet: 'list',
        component: ItineraryListSavedPage
      },
      {
        path: 'guide',
        outlet: 'guide',
        component: ItineraryGuidePage
      }
    ]
  },
  {
    path: '',
    redirectTo: 'itinerary-tabs/(home:home)',
    pathMatch: 'full'
  }
];

The tabs are in a modal open on the Home page, when I click to the tabs load the component page in the home page instead to load inside the modal. Was working in ionic 3, is a bug or a mistake?

**Comment by goelectricstations** [comment]
tabs.html

  <ion-content no-padding>
    <ion-tabs tabbarPlacement="top" tabbarLayout="icon-end">
      <ion-tab label="{{dict.itinerary_clear.toUpperCase()}}" icon="add" href="/itinerary-tabs/(home:home)">
        <ion-router-outlet name="home"></ion-router-outlet>
      </ion-tab>
      <ion-tab label="{{dict.itinerary_savedItinerary.toUpperCase()}}" icon="list" href="/itinerary-tabs/(list:list)">
        <ion-router-outlet name="list"></ion-router-outlet>
      </ion-tab>
      <ion-tab label="{{dict.menu_guida.toUpperCase()}}" icon="information" href="/itinerary-tabs/(guide:guide)">
        <ion-router-outlet name="guide"></ion-router-outlet>
      </ion-tab>
    </ion-tabs>

**Comment by paulstelzer** [comment]
Is this issue still exist in beta.17?
