### ISSUE TITLE
[Ionic 4] Uncaught TypeError: Object(...) is not a function @ionic-native/file

### ISSUE THREAD

**Issue by HelloWei007** [ionic-team/ionic#15225]
Hey guys i am building a project with ionic 4 + angular 6, I'm trying use ionic file system on my project, 

https://ionicframework.com/docs/native/file/

following this page , after install all dependencies when I try to import "File" into my  "appModule.ts" i get this error:

Uncaught TypeError: Object(...) is not a function
    at index.js:1193
    at Object../node_modules/@ionic-native/file/index.js (index.js:1370)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/app.module.ts (app.component.ts:11)
    at __webpack_require__ (bootstrap:81)
    at Object../src/main.ts (environment.ts:21)
    at __webpack_require__ (bootstrap:81)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:81)
    at checkDeferredModules (bootstrap:43)

Enviorment: 

FilePackage:

"dependencies": {
  ...
    "@ionic-native/core": "5.0.0-beta.14",
    "@ionic-native/file": "^4.12.0",
    "@ionic-native/file-opener": "^4.12.0",
    "@ionic-native/file-path": "^4.12.0",
..]

Ionic:

   ionic (Ionic CLI)          : 4.1.0
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.2
   @angular-devkit/schematics : 0.7.2
   @angular/cli               : 6.1.2
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.4

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.3, (and 5 other plugins)

System:

   NodeJS : v8.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.2.0
   OS     : Windows 10

Environment:

   ANDROID_HOME : not set

**Comment by HelloWei007** [comment]
xxx = any native component
fix the issues, with:
` npm i -s @ionic-native/xxx@5.0.0-beta.14`

NOTE: if you are using ANGULAR 6 in you project you must import ionic component + `/ngx` , for example:  
- Use Angular 6

` import { xxx } from '@ionic-native/xxx/ngx'; ` 
` import { file } from '@ionic-native/file/ngx'; ` 

- Without Angular 

` import { xxx } from '@ionic-native/xxx'; ` 
` import { file } from '@ionic-native/file'; ` 

Lastly check the `@ionic-native/xxx`  versions on npm:
    https://www.npmjs.com/package/@ionic-native/xxx
    https://www.npmjs.com/package/@ionic-native/file

you have to use the version 5.x.x for ANGULAR and 4.x.x ANGULAR-IONIC.
Check your project type on your `ionic.config.json `file

**Comment by FlawaCLV** [comment]
@HelloWei007 is it deployed on all @ionic-native plugins ?
Because I still have the issue. No ngx folder or exports from there in these plugins: AppRate, EmailComposer, InAppPurchase, GoogleAnalytics. I have stoped at that point.

Is there a workaround while it's being deployed ?

**Comment by FlawaCLV** [comment]
@HelloWei007 sorry, my mistake. Haven't paid to much attention on the first 3 lines of your comment. Works great.
