### ISSUE TITLE
[ionic v4.beta.3] no-margin not working as expected on card

### ISSUE THREAD

**Issue by stalinkay** [ionic-team/ionic#15223]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v10.8.0 (/usr/local/Cellar/node/10.8.0/bin/node)
   npm               : 6.3.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /usr/local/share/android-sdk
```

**Describe the Bug**
The margin on the right side of the card is not updated to match the left side of the card.

**Steps to Reproduce**
1. Create a new ionic project with `ionic start myApp sidemenu`
2. Add a card with no-margin set

**Related Code**
```
<ion-content padding>
  <ion-card>
    <ion-img src="https://picsum.photos/200/300/?random"></ion-img>

    <ion-card-content>
      <ion-card-title>My Title</ion-card-title>
      <p>My description</p>
    </ion-card-content>
  </ion-card>
</ion-content>
```

**Expected Behavior**
With no-margin set, the card left and right margin should match.

**Additional Context**
See attached ![screen shot 2018-08-18 at 12 06 06 pm](https://user-images.githubusercontent.com/198020/44298299-c79b0700-a2e0-11e8-9b37-8688bed624f0.png)

**Comment by brandyscarney** [comment]
Thanks for the issue! This should be fixed in the `beta.4 release`.

**Comment by stalinkay** [comment]
You are welcome.
