### ISSUE TITLE
Hi, how may I change height of tabbar?

### ISSUE THREAD

**Issue by fazila-mehtab** [ionic-team/ionic#15238]
$ ionic info
√ Gathering environment info - done!
Ionic:

   ionic (Ionic CLI)          : 4.0.6
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.2.0-beta.2
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.4

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 5.5.1
   OS     : Windows 7

I created tabs project of ionic 4 using --type=angular, now i want to change height of tabbar how could I do this please help. I have changed height of title bar but unable to change height for tabbar.

**Comment by brandyscarney** [comment]
Thank you for the issue! This will be easier than ever with the latest release `4.0.0-beta.14` which allows full control over the tab bar and tab buttons. You'll be able to write the following to change it:

```
ion-tab-bar {
  height: 70px;
}
```

See my comment here for more information on the latest API: https://github.com/ionic-team/ionic/issues/15942#issuecomment-433429959
