### ISSUE TITLE
Sometimes icons are not loaded when switching with tabs

### ISSUE THREAD

**Issue by GRRook** [ionic-team/ionic#15235]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**

Sometimes the icons in lists are not loaded/rendered when selecting another tab, this only happens the first time when you click another tab (root page). After that the icons are loaded for other pages.. so it happens only the first time you enter another tab.

**Expected behavior:**

Always show icons when switching a tab, also the first time when entering a new tab.

**Steps to reproduce:**

Create a new application with 3 tabs. 
Create a list with icons in the 3 root pages.
Click on another tab.
If the bug doesnt appear, refresh and try again.
It happens sporadically!!

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by manucorporat** [comment]
This should be fixed in beta.5
