### ISSUE TITLE
[ionic v4] Select missing open() reference

### ISSUE THREAD

**Issue by goelectricstations** [ionic-team/ionic#15239]
Ionic Info
Run ionic info from a terminal/cmd prompt and paste the output below.

Ionic:

ionic (Ionic CLI) : 4.1.0 (C:\Users\Computer\AppData\Roaming\npm\node_modules\ionic)
Ionic Framework : @ionic/angular 4.0.0-beta.0
@angular-devkit/core : 0.7.0-rc.3
@angular-devkit/schematics : 0.7.0-rc.3
@angular/cli : 6.0.8
@ionic/ng-toolkit : 1.0.0
@ionic/schematics-angular : 1.0.1

Cordova:

cordova (Cordova CLI) : not installed
Cordova Platforms : none
Cordova Plugins : no whitelisted plugins (0 plugins total)

System:

NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
npm : 6.3.0-next.0
OS : Windows 10

Environment:

ANDROID_HOME : not set

This below, does not work anymore!

import { Select } from 'ionic-angular';

@Component({
  templateUrl: '<your template here>'
})
export class SelectOpeningClass {
  @ViewChild(Select) select: Select;

  constructor() { do something }
  ionViewWillEnter() { //or whatever method you want to use
    this.select.open()
  }
}

**Comment by lucasbasquerotto** [comment]
@goelectricstations If you are using Ionic 4 than I think you shouldn't import from `ionic-angular` anymore, but from `@ionic/core` or `@ionic/angular`, though you can't use `@ViewChild` in an `@ionic/core` reference directly.

To use `@ViewChild` with an `@ionic/core` component you use its selector (component tag) to access the `ElementRef`, like it's explained in the following link in the ionic forum:

https://forum.ionicframework.com/t/slides-viewchild/137328/4

In your case, you could try something like:

```typescript
@ViewChild('ion-select') select: ElementRef;

this.select.nativeElement.open();
```

(I haven't tested the above code, but it should be something similar)

**Comment by goelectricstations** [comment]
@lucasbasquerotto 

still does not work.

 this.select.nativeElement.open() is not a function

**Comment by brandyscarney** [comment]
Thanks for the issue! Please update to the latest version `4.0.0-beta.3` and let me know if you're still having issues. This should have been fixed in that release: https://github.com/ionic-team/ionic/releases/tag/v4.0.0-beta.3

**Comment by goelectricstations** [comment]
@brandyscarney 

to update to the latest version I simple have to do npm install -g ionic@latest ?

I ask because I still get @ionic/angular 4.0.0-beta.0

Thank you

**Comment by goelectricstations** [comment]
@brandyscarney installed the last beta is fixed now

**Comment by brandyscarney** [comment]
Running `npm install -g ionic@latest` will update the Ionic CLI, not the framework. 

You can update the framework by navigating to the root of your project and running the following:

```
npm i @ionic/angular@latest
```

or to install a specific version:

```
npm i @ionic/angular@4.0.0-beta.3
```

Running ionic info should give you something similar to this:

```
$ ionic info

Ionic:

   ionic (Ionic CLI)          : 4.0.1 (/Users/brandyscarney/.nvm/versions/node/v8.9.1/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
```

More on npm install here: https://docs.npmjs.com/cli/install

**Comment by brandyscarney** [comment]
@goelectricstations Glad it's fixed!

**Comment by goelectricstations** [comment]
@brandyscarney this issue is back. I open a new bug here: https://github.com/ionic-team/ionic/issues/15516
