### ISSUE TITLE
Ion input bad work  on ios ionic4

### ISSUE THREAD

**Issue by umberto12345** [ionic-team/ionic#15232]
Please visit for issue screen and version here https://forum.ionicframework.com/t/ion-input-work-bad-on-ionic-v-4-1-0/138922/5

**Comment by zapotocnylubos** [comment]
I experience same issue.
even global style mode changed to 'md' didn't helped.

**Comment by umberto12345** [comment]
And now wait new upgrade ?:c

**Comment by umberto12345** [comment]
I have fix 
Add on global.scss 

.native-input{
Position:relative;
top:6.5px;
left:-5px;
Border:0;
Outline:0;
Padding:5px;
}
