### ISSUE TITLE
[Ionic v4.0.0-beta.3] routerLink in Footer Animation Different than Side Menu

### ISSUE THREAD

**Issue by matthew-valenti** [ionic-team/ionic#15230]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.0 (C:\Users\matth\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

**Describe the Bug**
Side menu root routerLink has no animation between pages. Footer root routerLink does have animation.

**Steps to Reproduce**
1. Create Ionic 4 side menu project.
2. Add the following to /src/app/app.component.html
```
<ion-item routerDirection="root" routerLink="/home">
    <ion-icon slot="start" name="home"></ion-icon>
    <ion-label>Home</ion-label>
</ion-item>
```
3. Add the same html to /src/app/home.page.html but in the footer:
```
<ion-footer>
    <ion-item routerDirection="root" routerLink="/home">
        <ion-icon slot="start" name="home"></ion-icon>
        <ion-label>Home</ion-label>
    </ion-item>
</ion-footer>
```
4. 
Click the link in the side menu - there will be no animation between pages.
Click the link in the footer - there will be animation between pages.

**Expected Behavior**
Expecting animation to be consistent between side menu links and footer links.

**Comment by paulstelzer** [comment]
Is this issue still exist in beta.17?
