### ISSUE TITLE
Github import of default Ionic4Angular app to Stackblitz fails

### ISSUE THREAD

**Issue by Tommertom** [ionic-team/ionic#15231]
# Bug Report
Stackblitz import from Github gives error on Platform service injected

**Ionic Info**
Not applicable. Stackblitz

**Describe the Bug**
I created an Ionic 4 Angular app using `ionic start myApp sidemenu --type=angular`, uploaded it to Github and then tried to import in Stackblitz: ` https://stackblitz.com/github.com/Tommertom/ionic4angularSidemenu` 

Error message:
`
ERROR TypeError: core_2.detectPlatforms is not a function
    at new Platform (platform.js:8)
    at _createClass (ng_module.ts:171)
    at _createProviderInstance (ng_module.ts:143)
    at resolveNgModuleDep (ng_module.ts:104)
    at NgModuleRef_.get (refs.ts:505)
    at resolveDep (provider.ts:416)
    at createClass (provider.ts:270)
    at createDirectiveInstance (provider.ts:135)
    at createViewNodes (view.ts:303)
    at createRootView (view.ts:210)
`
(may be issue with Stackblitz). 

The app does not run until I removed the test specification, and all references (including DI) to Platform (changes in app.module.ts, app.component.spec.ts and app.component.ts). Also prior to this I need to add @angular/compiler package (prompted by Stackblitz)

**Steps to Reproduce**
See above

**Related Code**
See above

**Expected Behavior**
The simple starter app to be imported from Github to Stackblitz without errors

**Additional Context**
May be issue with Stackblitz. 

https://github.com/stackblitz/core/issues/219#issuecomment-414109797

**Comment by comfortme** [comment]
This is a issue after beta 7 again.

**Comment by paulstelzer** [comment]
Ups, a little to fast. is it working with beta.17 again or not?

**Comment by comfortme** [comment]
no it’s not working with beta 17

**Comment by paulstelzer** [comment]
Okay, I will close it here because it's the same issue in general and the other issue is better explained
