### ISSUE TITLE
[4.0.0-beta.3] Icons outline not appear

### ISSUE THREAD

**Issue by goelectricstations** [ionic-team/ionic#15245]
Ionic:

   ionic (Ionic CLI)          : 4.1.0 (C:\Users\Computer\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.3.0-next.0
   OS     : Windows 10

Environment:

   ANDROID_HOME : not set

The icon does not show if:
`<ion-icon name="ios-pin-outline" slot="start"></ion-icon>`

But shows if:
`<ion-icon name="ios-pin" slot="start"></ion-icon>`

**Comment by brandyscarney** [comment]
Thanks for the issue. Several outline icons were removed in Ionicons v4. You can search the current icons here: https://ionicons.com/

If you would like to request an icon please add an issue on the [ionicons repo](https://github.com/ionic-team/ionicons/issues).

There is also an issue requesting all outline icons here: https://github.com/ionic-team/ionicons/issues/550
