### ISSUE TITLE
[Ionic v4] Content ionScroll ScrollDetail contains only zero values

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#15244]
# Bug Report

**Ionic Info**
v4.0.0-beta.3

**Describe the Bug**
The `ScrollDetail` emitted from `Content. ionScroll` contains only zero values

**Related Code**

     <ion-content [scrollEvents]="true" (ionScroll)="test($event)">
     </ion-content>

     test($event) {
       console.log($event.detail.scrollTop); // -> 0
       console.log($event.detail.startY); // -> 0      
       console.log('etc.');
     }

**Expected Behavior**
The `ScrollDetail` emitted by `Content.ionScroll` should contains the scroll (position) information

**Comment by Nigdor** [comment]
Same problem here, 
The solution is to downgrade to 4.0.2 for now.

**Comment by peterpeterparker** [comment]
Could confirm the fix, it works perfectly in beta.7 👍
