### ISSUE TITLE
【ionic 4】try to autoplay slides, but wont make it works

### ISSUE THREAD

**Issue by wesleyxiao** [ionic-team/ionic#15242]
**these working on my ionic 3 app, but when i test on ionic 4 this won't working**
` <ion-slides pager="true"   autoplay="2000" loop="true" speed="3000" [options]="slideOpts">
      <ion-slide>
        <h1>Slide 1</h1>
      </ion-slide>
      <ion-slide>
        <h1>Slide 2</h1>
      </ion-slide>
      <ion-slide>
        <h1>Slide 3</h1>
      </ion-slide>
    </ion-slides>`

**i also try this, not working also**

`import { Component, ViewChild } from '@angular/core';
import { Slides } from '@ionic/angular';
@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss']
})
export class HomePage {
  @ViewChild('mySlider', { read: Slides }) slides: Slides;

  ionViewDidEnter() {
    this.slides.startAutoplay();
  }
}
`

`    <ion-slides #mySlider pager="true" [options]="slideOpts">
      <ion-slide>
        <h1>Slide 1</h1>
      </ion-slide>
      <ion-slide>
        <h1>Slide 2</h1>
      </ion-slide>
      <ion-slide>
        <h1>Slide 3</h1>
      </ion-slide>
    </ion-slides>`

**Comment by aam-antonio** [comment]
Hi, as you can see here #15046, they are working on fixing the ViewChild on such components.

By now, you could use this for your purpose:

```
<ion-slides #mySlider (ionSlidesDidLoad)="slidesDidLoad(mySlider)">
  ...
</ion-slides>


slidesDidLoad(slides: Slides) {
  slides.startAutoplay();
}
```

Also, if you are using Ionic 4, you should check the [Lifecycle Events changes](https://beta.ionicframework.com/docs/building/migration/#lifecycle-events).

**Comment by wesleyxiao** [comment]
thank you Antonio, it is woking 😀, and thank you for the information about lifecycle events changes
