### ISSUE TITLE
[ionic v4 beta.3] Can't apply virtualTrackBy on virtual-scroll component

### ISSUE THREAD

**Issue by favrio** [ionic-team/ionic#15258]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.0
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.2
   @angular-devkit/schematics : 0.7.2
   @angular/cli               : 6.1.2   @ionic/ng-toolkit          : 1.0.5
   @ionic/schematics-angular  : 1.0.4

Cordova:

   cordova (Cordova CLI) : 6.5.0   Cordova Platforms     : none   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.1.3
   NodeJS     : v8.9.4 (/usr/local/bin/node)
   npm        : 5.6.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : not set
```

**Describe the Bug**
I cant apply the virtualTrackBy function on this virtual scroll, it tells me `Can't bind to 'virtualTrackBy' since it isn't a known property of 'ion-virtual-scroll'.` on console. The IonicModule is imported in my module by default.

There is no any docs about virtualTrackBy in v4.

**Steps to Reproduce**
1. Create any virtual scroll component.
2. Just give a virtualTrackBy on this component.
3. It will return this error msg.

**Related Code**
```
<ion-virtual-scroll *ngIf="formattedRows.length" [items]="formattedRows" approxItemHeight="40px" [virtualTrackBy]="">
    <div class="data-row" *virtualItem="let item;">
      <div class="data-cell" *ngFor="let data of item | keyvalue" [innerHTML]="data.value"></div>
    </div>
  </ion-virtual-scroll>
```

**Comment by AVatch** [comment]
Agreed - after trying this out, same error was thrown. 

In the common scenario where the data is paginated, or the items are interactable, this is very necessary otherwise each pagination causes a re-render breaking the otherwise great experience w/ this virtual scroll

**Comment by Lx** [comment]
There actually is *one* mention of `virtualTrackBy` in the v4 documentation for `ion-virtual-scroll`:

https://github.com/ionic-team/ionic/blob/master/core/src/components/virtual-scroll/readme.md#changing-dataset-should-use-virtualtrackby

But I'm not sure whether this documentation is intentional though (perhaps accidentally copied from elsewhere?), because `virtualTrackBy` is mentioned nowhere else on the page, especially in the list of properties.

**Comment by ibnclaudius** [comment]
I'm facing the same error described by @hr1992. My `ionic info`:

```
Ionic:

   ionic (Ionic CLI)             : 4.4.0 (/Users/ibnclaudius/.config/yarn/global/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.3
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 5 other plugins)

System:

   NodeJS : v11.2.0 (/Users/ibnclaudius/.nvm/versions/node/v11.2.0/bin/node)
   npm    : 6.4.1
   OS     : macOS
```

**Comment by evertonrobertoauler** [comment]
Hello guys

I'm using @angular/cdk/scrolling, instead of ion-virtual-scroll.

It works perfectly, no performance issues with data update.

https://github.com/evertonrobertoauler/financas-pessoais/blob/master/src/app/paginas/inicio/extrato/extrato.component.html

I hope this can help some of you guys, while virtualTrackBy is missing.

**Comment by eduboxgithub** [comment]
Is this fixed on rc0 or rc1?

I'm still getting the same error.

**Comment by Ross-Rawlins** [comment]
Is this resolved>

**Comment by rdlabo** [comment]
Maybe, virtualTrackBy is be trackBy. But in my environment, This is not work well.
https://github.com/ionic-team/ionic/blob/master/angular/src/directives/virtual-scroll/virtual-scroll.ts#L89

```
Ionic:

   ionic (Ionic CLI)             : 4.10.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.1
   @angular-devkit/schematics    : 7.3.0
   @angular/cli                  : 7.2.1
   @ionic/angular-toolkit        : 1.2.2

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.17
   @capacitor/core           : 1.0.0-beta.17

System:

   NodeJS : v8.12.0 (/usr/local/bin/node)
   npm    : 6.5.0
   OS     : macOS Mojave
```

**Comment by Slavrix** [comment]
virtualTrackBy seems to still be missing.

trackBy does seem to work as intended in its place.

I keep getting what seem to be looping redraws also.

[https://imgur.com/a/hweMwY5](url)

I'm using angular to I might look into using @evertonrobertoauler solution above .

**Comment by evertonrobertoauler** [comment]
Hi guys, now using the stable release of @ionic/angular, trackBy it's finally working.

```html
<ion-virtual-scroll [items]="myList" [trackBy]="trackByFn">
```

```ts
  trackByFn(index, item) {
    return item ? item.id : index;
  }
```

I hope now this issue can be closed.

**Comment by gartorware** [comment]
`trackBy` seems to be working but the docs still refers to `virtualTrackBy`.
https://ionicframework.com/docs/api/virtual-scroll#changing-dataset-should-use-virtualtrackby

**Comment by FloryanFilip** [comment]
Can someone explain to me why trackBy function is used in the first place? Is this some kind of a filter function?

**Comment by sjregan** [comment]
@FloryanFilip trackBy is an Angular [feature for improving performance](https://netbasal.com/angular-2-improve-performance-with-trackby-cc147b5104e5).
