### ISSUE TITLE
 [Ionic V4] Can not override Ionic Sass Variables

### ISSUE THREAD

**Issue by 982964399** [ionic-team/ionic#15251]
I override variables from "src/theme/variables.scss" file, but it can not work; What should I do?
<img width="536" alt="86234ab2-6964-4f8d-ac6a-c0287e109290" src="https://user-images.githubusercontent.com/14900806/44379346-1393b900-a538-11e8-8b9c-77f19027d0fc.png">

**Comment by paulstelzer** [comment]
Ionic 4 is using css variables, so you have to override this and not the sass variables
