### ISSUE TITLE
missing custom transitions in ionic4

### ISSUE THREAD

**Issue by marcorinck** [ionic-team/ionic#15259]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.0.2 (/Users/mzrinck/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 2.0.1
   NodeJS            : v8.9.0 (/usr/local/bin/node)
   npm               : 6.2.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
Ionic 3 had the possibility to define custom page transitions on the IonicConfig class you can  inject in one of your components. This looked like this:

```` 
import {Config} from "@ionic/angular";
@Injectable()
class SomeService {
	constructor(private config: Config) {
		this.config.setTransition('slide-down', SlideDownTransition);
	}
}
```` 

SlideDownTransition was just a custom implementation of the ionic provided PageTransition class, just like the standard iosTransition and mdTransition did too. 

In Ionic4 I don't see how I can do this anywhere and the migration guide and breaking changes list don't mention this change either (like so many other changes).  

I can see that an mdTransitionAnimation and iosTransitionAnimation still exist in the repository and they are used internally to implement the standard transitions. But I don't see a possibility to define custom transitions anymore. 

Please bring this back because this is an essential feature for apps!

**Comment by svzi** [comment]
My Ionic 3 app also makes heavy usage of a custom PageTransition implementation and I agree with @marcorinck that this feature is essential for several apps (at least of mine and my clients). This is currently a stopper for trying out Ionic 4.

**Comment by paulstelzer** [comment]
If I am correct there is a commit, that you can add your own PageTransitions in Ionic 4, too. So I think this is done in beta.17
