### ISSUE TITLE
[Ionic v 4]  Ionic cli generated project executes on localhost instead of file:/// on android device

### ISSUE THREAD

**Issue by azpopov** [ionic-team/ionic#15264]
**Ionic Info**
![image](https://user-images.githubusercontent.com/10099422/44412528-122ab680-a561-11e8-8a02-0ae0edfb1bc4.png)

**Describe the Bug**
Built apk using ionic cordova run adroid --prod.

Opening the app on the android device and inspecting it unsing Chrome's Remote Devices it executes on localhost:8080 instead of the documented file://

**Steps to Reproduce**
ionic start
ionic cordova run adroid --prod.
Below is comparison between project generated using ionic 4.1.1 and ionic 2.2.3
![image](https://user-images.githubusercontent.com/10099422/44412159-1f937100-a560-11e8-9a50-de93d1e94123.png)

**Expected Behavior**
Executing on file:/// instead of localhost:8080

**Comment by dwieeb** [comment]
@azpopov Where is it documented that the app is on `file://` ? @kerosin is correct. New apps will be on `http://localhost:8080` for both iOS and Android.
