### ISSUE TITLE
[4.0.0-beta.3] encapsulation break classes

### ISSUE THREAD

**Issue by goelectricstations** [ionic-team/ionic#15269]
Ionic:

ionic (Ionic CLI) : 4.1.1 (C:\Users\Computer\AppData\Roaming\npm\node_modules\ionic)
Ionic Framework : @ionic/angular 4.0.0-beta.3
@angular-devkit/core : 0.7.0-rc.3
@angular-devkit/schematics : 0.7.0-rc.3
@angular/cli : 6.0.8
@ionic/ng-toolkit : 1.0.0
@ionic/schematics-angular : 1.0.1

Cordova:

cordova (Cordova CLI) : 8.0.0
Cordova Platforms : android 7.1.0, ios 4.5.4
Cordova Plugins : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 1.2.1, (and 11 other plugins)

System:

NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
npm : 6.3.0-next.0
OS : Windows 10

CODE TO TRY:
HMTL:
<div class="buttonCircle backgroundNCBluReserve ges-icon-calendar"></div>
ORIGINAL CSS:
.backgroundNCBluReserve {
    background-color: #00238C;   
}
CSS AFTER:
.backgroundNCBluReserve[_ngcontent-c0] {
  background-color: #00238C; }

RESULT 
backgroundNCBluReserve does not match anymore with the class

**Comment by manucorporat** [comment]
This is related with angular: https://angular.io/guide/component-styles#view-encapsulation

**Comment by goelectricstations** [comment]
Ok, but how to fix?
