### ISSUE TITLE
Scroll locking delay when use "ion-datetime"

### ISSUE THREAD

**Issue by jmsantosnetto** [ionic-team/ionic#15263]
# Bug Report

**Ionic Info**

Run `ionic info` from a terminal/cmd prompt and paste the output below.

	Ionic:
	
	    @ionic/cli-utils  : 1.19.2
	    ionic (Ionic CLI) : 3.20.0

	global packages:

	    cordova (Cordova CLI) : 8.0.0

	local packages:
	
	    @ionic/app-scripts : 3.1.10
	    Cordova Platforms  : android 7.0.0
	    Ionic Framework    : ionic-angular 3.9.2
	
	System:
	
	    Android SDK Tools : 26.1.1
	    Node              : v8.11.3
	    npm               : 5.6.0
	    OS                : Windows 10

	Environment Variables:
	
	    ANDROID_HOME : C:\Users\jmsan\AppData\Local\Android\Sdk
	
	Misc:
	
	    backend : pro

**Describe the Bug**

Scroll delay of 2 seconds when click in "Done" or "Cancel" an input of type "ion-datetime";
When "Done" or "Cancel" is clicked, an approximate 2-second delay occurs, thus preventing page scrolling during this time

**Steps to Reproduce**

1.Create a simple page that use scroll;
2.Add an "ion-item" with "ion-datetime" inside;
3.Run on ionic-serve or build for any Platforms;
4.Manipulate the date and click cancel or done;
5.Then try to scroll the page;

**Related Code**

	
	<ion-item>
	    <ion-label>Date</ion-label>
	    <ion-datetime displayFormat="MM/DD/YYYY" [(ngModel)]="myDate"></ion-datetime>
	</ion-item>

**Comment by paulstelzer** [comment]
Is this issue still exist in beta.17?
