### ISSUE TITLE
[v4.0.0-beta.3] ion-input autocomplete not setting input value in Chrome 68

### ISSUE THREAD

**Issue by btsiders** [ionic-team/ionic#15262]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.0 (C:\Users\Bryan\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.0
   OS     : Windows 10
```

**Describe the Bug**
When using Chrome [Version 68.0.3440.106 (Official Build) (64-bit)], ion-input with `autocomplete="on"` does not set the value of the ion-input when the input's value is set by the autocomplete.

**Steps to Reproduce**
1. Open app in Chrome.
2. If input is not auto-completed already, select it and choose a value from the auto-complete dropdown list.
3. Notice that the label that is tied to the value is still blank after the input value is set.
4. Edit the value in the input manually.
5. Notice that the label value is set when the input is manually set.

**Related Code**
```html
<ion-content>
    <form (ngSubmit)="signIn()">
      <ion-item>
        <ion-label >Username ({{ username }})</ion-label>
        <ion-input [(ngModel)]="username" name="username" autocomplete="on"></ion-input>
      </ion-item>
      <ion-button type="submit">Sign In</ion-button>
    </form>
</ion-content>
```

**Expected Behavior**
The value of the ion-input should be set when the input's value is set via autocomplete.

**Additional Context**
Broken: Chrome 68.0.3440.106 (Official Build) (64-bit)
Works: Microsoft Edge 44.17741.1000.0
Works: Firefox 61.0.2 (64-bit)

**Comment by nblum** [comment]
It's same behaviour with `Chrome Version 69.0.3497.81 (Official Build) (64-bit)` and  ` Ionic Framework            : @ionic/angular 4.0.0-beta.7`

**Comment by paulstelzer** [comment]
We had a similar issue and this is related to shadow dom that Ionic uses. So at the moment, there is no fix for that.
