### ISSUE TITLE
ionic4 ion-app class="md" not working

### ISSUE THREAD

**Issue by androidhoya** [ionic-team/ionic#15267]
ionic4 beta2

<ion-app class="md">
</ion-app>

not working... plz help me :(

**Comment by garygrossgarten** [comment]
@androidhoya have you tried setting the app mode to `const ionicConfig: IonicConfig = { mode: 'md' };` ?

And then in your AppModule:

```
@NgModule({
...
  imports: [...
    IonicModule.forRoot(ionicConfig),
    ...
  ],
  ...
})
export class AppModule { }
```

**Comment by manucorporat** [comment]
@garygrossgarten is right, class="md" is not longer a thing in ion-app
