### ISSUE TITLE
InfiniteScroll Vue + Ionic 4

### ISSUE THREAD

**Issue by jabbon** [ionic-team/ionic#15261]
I'm trying to implement infinite Scroll with Vue and ionic 4 Beta 2, but I can't capture ionInfinite event, in the VueJs documentation says that camelCase events won't be captured in Dom-templates beacuse the browser converts all template in lowercase here is my code, please help.

[https://vuejs.org/v2/guide/components-custom-events.html](url)

`<template>
    <ion-app>
        <ion-page class="show-page">
            <ion-header>
                <ion-toolbar>
                    <ion-title>Ionic 4 + Vue Application</ion-title>
                </ion-toolbar>
            </ion-header>

            <ion-content class="content" padding>

                <ion-list>
                    <ion-item v-for="item in items">
                        {{item}}
                    </ion-item>
                </ion-list>

                <ion-infinite-scroll threshold="100px" @ionInfinite="loadData">
                    <ion-infinite-scroll-content
                            loading-spinner="bubbles"
                            loading-text="Loading more data...">
                    </ion-infinite-scroll-content>
                </ion-infinite-scroll>

            </ion-content>

        </ion-page>
    </ion-app>
</template>
<script>
    export default {
        name: 'App',
        data() {
            return {
                items: []
            }
        },
        methods: {

            loadData() {
                setTimeout(function () {
                    console.log('Done');
                    $event.target.complete();
                    for (let i = 0; i < 30; i++) {
                        this.items.push(i);
                    }

                    // App logic to determine if all data is loaded
                    // and disable the infinite scroll
                    if (data.length == 1000) {
                        $event.target.disabled = true;
                    }
                }, 500);
            }
        },
        created() {
            for (let i = 0; i < 30; i++) {
                this.items.push(i);
            }
        }
    }

</script>`

**Comment by globophobe** [comment]
It seems to be working, but event only fires once. 

Tried 2 cases, abbreviated for clarity:

As per docs:
```
<ion-infinite-scroll @ionInfinite="loadMore" threshold="100px" position="bottom" >

loadMore(event) {
    this.$store.dispatch('loadMore')
    event.target.complete();    
}
```
As well as:

```
<ion-infinite-scroll ref="infiniteScroll" threshold="100px" position="bottom" >

mounted() {                                                                        
    this.$refs.infiniteScroll.addEventListener("ionInfinite", event => {             
    this.$store.dispatch('loadMore')
    event.target.complete();                                                       
  });                                                                              
}   
```

In both cases, the event listener fires only once.

**Comment by globophobe** [comment]
I realize that "my code is wrong", like the response to https://github.com/ionic-team/ionic/issues/15325  

It's working now as per the docs:

```
<ion-content>
  <ion-list v-for="item in items">
    <ion-item>{{ item }}</item>
  </ion-list>

  <ion-infinite-scroll @ionInfinite="loadMore" threshold="100px" position="bottom">
    <ion-infinite-scroll-content></ion-infinite-scroll-content>
  </ion-infinite-scroll>
</ion-content>

loadMore(event) {
    this.$store.dispatch('loadMore')
    event.target.complete();    
}
```

This issue can probably be closed.
