### ISSUE TITLE
Unable to style element properties for <ion-tab>, tab icons

### ISSUE THREAD

**Issue by osman144** [ionic-team/ionic#15271]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.1
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.0-beta.2
   @angular-devkit/schematics : 0.7.0-beta.2
   @angular/cli               : 6.0.3
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.0

System:

   NodeJS : v9.4.0 (/usr/local/Cellar/node/9.4.0/bin/node)
   npm    : 6.3.0
   OS     : macOS High Sierra

```

**Describe the Bug**
Unable to edit style properties of tab-icon-button. Tab bar icons aren't respecting the CSS as it should. Unable to modify the icon size and change change color when the tab-button active.

I'm able to edit element properties in the browser console, I would expect just to get the class of .tab-button-icon and set the same properties in the global.scss but it doesn't apply changes. 

```
.tab-button-icon{
    font-size:10px;
}
```

``` 
<ion-tab href="/app/(home:home)" icon="happy" label="Browse">
        <ion-router-outlet name="home"></ion-router-outlet>
    </ion-tab> 
```

**Steps to Reproduce**
1. Launch the App

**Related Code**
``` <ion-tabs tabbarLayout="bottom" color="light">
    <ion-tab href="/app/(home:home)" icon="happy" label="Browse">
        <ion-router-outlet name="home"></ion-router-outlet>
    </ion-tab>
    <ion-tab href="/app/(meal-plan:meal-plan)" icon="egg" label="Meal Plan">
        <ion-router-outlet name="meal-plan"></ion-router-outlet>
    </ion-tab>
    <ion-tab href="/app/(shopping:shopping)" icon="list" label="Shopping List">
        <ion-router-outlet name="shopping"></ion-router-outlet>
    </ion-tab>
    <ion-tab href="/app/(account:account)" icon="person" label="Account">
        <ion-router-outlet name="account"></ion-router-outlet>
    </ion-tab>
</ion-tabs>
```

**Expected Behavior**
I expect style changes to the tab icon classes or the tab itself to apply. 

**Additional Context**
iOS:

I'm able to adjust size and style the tab bar as desired using the browser console. Trying to make the same changes in the global scss file doesn't work. 

![screen shot 2018-08-21 at 2 49 06 pm](https://user-images.githubusercontent.com/25594064/44425468-92492000-a551-11e8-8178-dea9636c2547.png)

![screen shot 2018-08-21 at 2 49 33 pm](https://user-images.githubusercontent.com/25594064/44425474-96753d80-a551-11e8-8f2a-e2137a0189c2.png)

**Comment by mhartington** [comment]
This is most likely because of the move to Shadow DOM and using CSS variables for things. We're documenting this and adding a list of exposed variables you can modify. You can track the progress here #14850

**Comment by brandyscarney** [comment]
Thank you for the issue! This will be easier than ever with the latest release `4.0.0-beta.14` which allows full control over the tab buttons and icons. See my comment here for more information on the latest API: https://github.com/ionic-team/ionic/issues/15942#issuecomment-433429959

**Comment by NathanNovak** [comment]
@brandyscarney  The latest version that is installing is 4.0.0-beta.13.  I would like to control the size of the icons and according to your earlier post .14 does that.

**Comment by brandyscarney** [comment]
@NathanNovak Sorry, my comment was worded weird! `4.0.0-beta.14` hasn't been released yet. We're planning to release it this week.
