### ISSUE TITLE
Tab label not horizontally centered with icon

### ISSUE THREAD

**Issue by gabrielmaldi** [ionic-team/ionic#15273]
# Bug Report

**Ionic Info**

Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.6
   @capacitor/core           : 1.0.0-beta.6

System:

   NodeJS : v8.11.1 (/Users/gabrielm/n/bin/node)
   npm    : 6.4.0
   OS     : macOS High Sierra
```

**Describe the Bug**

<img width="391" alt="screen shot 2018-08-21 at 6 02 16 pm" src="https://user-images.githubusercontent.com/3728897/44428967-638c7300-a56c-11e8-964c-64dafcd7dfea.png">

Each tab's label is left aligned.

If the label is short (e.g. "Hi") you can see this clearly; but it's even noticeable with "normal" labels like "Home".

Labels should be horizontally aligned with icons.

This seems to get fixed adding `text-align: center;` to `.tab-btn-text`.

**Steps to Reproduce**

Just create an app based on the tabs template: `ionic start myApp tabs --type=angular`

**Comment by hr1992** [comment]
The same problem on 4.0.0-beta.12, the css rule about align is missing.

**Comment by mela93** [comment]
The same problem on 4.2.1,
and add below at `tabs.pages.scss`, not working.
![image](https://user-images.githubusercontent.com/17722672/47331042-0bc5d180-d6ad-11e8-930f-66731791567f.png)

```
.tab-btn-text {
    text-align: center !important;
}
```

Ionic info
```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.8.6
   @angular-devkit/schematics    : 0.8.6
   @angular/cli                  : 6.2.6
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.9.4 (/usr/local/Cellar/node/9.4.0/bin/node)
   npm        : 5.6.0
   OS         : macOS
   Xcode      : Xcode 10.0 Build version 10A255
```
