### ISSUE TITLE
[Ionic v4] Side menu becomes visible beyond breakpoint sm, v3 wasn't doing such thing

### ISSUE THREAD

**Issue by somq** [ionic-team/ionic#15278]
# Bug Report

**Ionic Info**

```
Ionic CLI 4.1.1
"@ionic/angular": "^4.0.0-beta.0" (same happens with beta 1,2 & 3)
```

**Describe the Bug**
Side menu becomes visible beyond breakpoint sm (768px/tablet), in v4, v3 wasn't doing such thing.

[v4 screenshots](https://imgur.com/a/bI3C0E0)
[v3 screenshots](https://imgur.com/a/MUE5eoy)

**Steps to Reproduce**
1. ionic start v4-test sidemenu --type=angular
2. ionic start v3-test sidemenu

**Expected Behavior**
Side menu should not become visible without an user action or either give a property to control it.

**Comment by mhartington** [comment]
Hi there! This actually is a result of the V4 starter project using split-pane in the layout. V3 did not have this, but we added it to the V4 starter as it is a common pattern when adapting sidemenu layouts to larger screens.

**Comment by somq** [comment]
Hi,
Thanks for you answer, I finally figured this one out.

For everyone having the same question and some trouble to understand the matter:
The only thing needed to avoid this behavior is to remove0 ```<ion-split-pane>``` tag in app.component.html

[Docs](https://beta.ionicframework.com/docs/layout/structure#split-pane-layout) explain this pretty well, I guess I have missed some when reading it:
> By default, the split pane view will show when the screen is larger than 768px

Thanks again
