### ISSUE TITLE
Tabs in iPhone X not displayed at the bottom of the screen until interaction

### ISSUE THREAD

**Issue by gabrielmaldi** [ionic-team/ionic#15275]
# Bug Report

**Ionic Info**

Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.6
   @capacitor/core           : 1.0.0-beta.6

System:

   NodeJS : v8.11.1 (/Users/gabrielm/n/bin/node)
   npm    : 6.4.0
   OS     : macOS High Sierra
```

**Describe the Bug**

Initially, there's a large gap between the tabs and the bottom of the screen. Once the user taps anywhere, the tabs are positioned correctly.

https://www.youtube.com/watch?v=niYPKcfvuJA

<img width="530" alt="screen shot 2018-08-21 at 6 53 48 pm" src="https://user-images.githubusercontent.com/3728897/44431240-9dad4300-a573-11e8-9e24-4e835ce8477c.png">

**Steps to Reproduce**

Create an app based on the tabs template: `ionic start myApp tabs --type=angular`, add Capacitor, and run on the iPhone X simulator (Xcode 9.4).

**Comment by osman144** [comment]
Hi this might help, it's a similar issue. 
https://github.com/ionic-team/ionic/issues/15147

**Comment by gabrielmaldi** [comment]
@osman144 you're right, it's the same issue. Gonna close this one in favor of #15147. Thanks!
