### ISSUE TITLE
Upgrade from 4.0.0-alpha.7 to latest breaks look-and-feel and navigation behavior

### ISSUE THREAD

**Issue by codyburleson** [ionic-team/ionic#15277]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   ionic (Ionic CLI) : 4.0.6

System:

   NodeJS : v8.11.3
   npm    : 6.2.0
   OS     : macOS High Sierra
```

**Describe the Bug**

**Steps to Reproduce**

1. Check out this repo: https://github.com/codyburleson/cburleson-pwa
2. First, to be able to compare, get the repo and do `npm install` and then `npm start` as-is. Navigate through the app and notice how it works and what it looks like.
3. Delete `node_modules` directory
4. Go to `package.json` and change the line `"@ionic/angular": "^4.0.0-alpha.7",` to the latest version (`4.0.0-beta.3`, for example)
5. Run `npm install`
6. Run `npm start`

**Expected Behavior**

The app, as-is, looks like this and navigation works...

![before-upgrade](https://user-images.githubusercontent.com/7317733/44437464-07334e80-a580-11e8-9bf3-802ed50c77b9.jpg)

After upgrading to the latest version of Ionic 4, I lose my fonts and the navigation doesn't seem to work right. Everything goes foobar...

![after-upgrade](https://user-images.githubusercontent.com/7317733/44437590-790b9800-a580-11e8-8e1e-3c9945d7f5f2.jpg)

**Additional Context**

There's a docs/devlog folder which provides some hints as to the history on how I built this project. I hope y'all can help give  me a clue so that I can upgrade ionic, but for now it breaks everything.

**Comment by mhartington** [comment]
There was some changes in between alpha and beta requiring user to include a global.scss file with these imports

https://github.com/ionic-team/starters/blob/master/angular/base/src/global.scss

You'll also want to add these to your styles array in the angular.json file


https://github.com/ionic-team/starters/blob/master/angular/base/angular.json#L34-L40
