### ISSUE TITLE
ion-back-button works only on first navigation with Angular router

### ISSUE THREAD

**Issue by berchik** [ionic-team/ionic#15284]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (C:\Users\jo\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

System:

   NodeJS : v8.9.3 (A:\Program Files\nodejs\node.exe)
   npm    : 6.1.0
   OS     : Windows 10

```

**Describe the Bug**
Using the recommended Angular router, the back button `<ion-back-button></ion-back-button>` in the Toolbar on the navigated page appears only on first time navigation. After navigating back home and again, its not showing on the second page.

**Additional Context**
It works as expected when using NavController (which is not recommended by the migration paper)

Thanks.

**Comment by Anthony2539** [comment]
#15216 same issue

**Comment by mhartington** [comment]
Closing and merging with #15216
