### ISSUE TITLE
Ionic 4  beta 3 - Tabs Method

### ISSUE THREAD

**Issue by ohrrkan** [ionic-team/ionic#15288]
# Bug Report

**Ionic Info**
   ionic (Ionic CLI)          : 4.0.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

**Describe the Bug**
ERROR TypeError: this.tab.getSelected is not a function
    at TabsPageComponent.push../src/app/tabs/tabs.page.ts.TabsPageComponent.tabChange

```
export class TabsPageComponent {
  @ViewChild("myTabs") public tab: Tabs | undefined;

  public tabChange(): void {
    if (typeof this.tab !== "undefined") {
      const selectedTab: HTMLIonTabElement | undefined = this.tab.getSelected();
    }
  }

}
```

**Comment by mhartington** [comment]
This is an angular quirk at the moment. You need to do

```
import { Component, ViewChild, ElementRef } from '@angular/core';
import { Tabs } from '@ionic/angular';

@Component({})
export class TabsPage {
  @ViewChild('myTabs') tab: ElementRef<Tabs>;
  public tabChange(): void {
    console.log(this.tab.nativeElement.getSelected());
  }
}
```

**Comment by ohrrkan** [comment]
This works. Thanks!
