### ISSUE TITLE
ionic 4 BETA :  ion-searchbar, ion-toggle - not able to use ngModel

### ISSUE THREAD

**Issue by sushmaGadget** [ionic-team/ionic#15281]
# Support Question

<ion-searchbar></ion-searchbar>
<ion-toggle><ion-toggle>
            in IONIC 4 - How do we do ngModel. NgModel on the following tags throws up the template error - No Provider for NgControl

ion-searchbar, ion-toggle

Can you please one of you help me
    
Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Comment by brandyscarney** [comment]
In addition to the forum & slack channel, please see the [conference app](https://github.com/ionic-team/ionic-conference-app/tree/core-update) for an example app using the above components in v4.
