### ISSUE TITLE
Ionic V3.9.2 page bouncing issue in IOS?

### ISSUE THREAD

**Issue by bhavinshiroya1994** [ionic-team/ionic#15298]
Hello team.

i develop App in Ionic V3.9.2,  and i am facing issue of Page bouncing while scrolling in IOS and in Android it was working fine.
please let me know how to solve this issue.

Thanks in advance.

**Comment by manucorporat** [comment]
>i am facing issue of Page bouncing while scrolling in IOS

is not enough for use to understand the issue. Please feel free to open a new issue following the issue template
