### ISSUE TITLE
[ionicV4]ion-input，has white rectangle

### ISSUE THREAD

**Issue by woodstream** [ionic-team/ionic#15294]
"@ionic/angular": "^4.0.0-beta.3"；
Test html using ion-input like this：

```
<div style="background-color: lightblue">
    <ion-item>
      <ion-label>Label1</ion-label>
      <ion-input></ion-input>
    </ion-item>
    <ion-item>
      <ion-label>Label2</ion-label>
      <ion-input></ion-input>
    </ion-item>
    <ion-item>
      <ion-label>Label3</ion-label>
      <ion-input></ion-input>
    </ion-item>
    <ion-item>
      <ion-label>Label4</ion-label>
      <ion-input></ion-input>
    </ion-item>
    <ion-item>
      <ion-label>Label5</ion-label>
      <ion-input></ion-input>
    </ion-item>
    <ion-item>
      <ion-label position="floating">Floating Label</ion-label>
      <ion-input></ion-input>
    </ion-item>
    <ion-item>
      <ion-label position="fixed">Fixed Label</ion-label>
      <ion-input></ion-input>
    </ion-item>
    <ion-item>
      <ion-label position="stacked">Stacked Label</ion-label>
      <ion-input></ion-input>
    </ion-item>
  </div>
````

When click the `<input>` element, before the third  one is normal，but after it，there will show a white rectangle，and the style will be added “pointer-events: none” and "transform"

**Comment by mhartington** [comment]
Hi there! How can I recreate this or what steps do I need to take?
I so far have not been able to recreate this issue. Could you please provide a sample project and post it to github? 
Thanks!

**Comment by woodstream** [comment]
First，just crete a new blank project by cli:
`ionic start findBug blank --type=angular`

Second，modify  the ion-content like this:
`<ion-content padding>
  <div style="background-color: lightblue">
    <ion-item>
      <ion-label>Label1</ion-label>
      <ion-input></ion-input>
    </ion-item>
    <ion-item>
      <ion-label>Label2</ion-label>
      <ion-input></ion-input>
    </ion-item>
    <ion-item>
      <ion-label>Label3</ion-label>
      <ion-input></ion-input>
    </ion-item>
    <ion-item>
      <ion-label>Label4</ion-label>
      <ion-input></ion-input>
    </ion-item>
    <ion-item>
      <ion-label>Label5</ion-label>
      <ion-input></ion-input>
    </ion-item>
    <ion-item>
      <ion-label>Label6</ion-label>
      <ion-input></ion-input>
    </ion-item>
    <ion-item>
      <ion-label position="floating">Floating Label</ion-label>
      <ion-input></ion-input>
    </ion-item>
    <ion-item>
      <ion-label position="fixed">Fixed Label</ion-label>
      <ion-input></ion-input>
    </ion-item>
    <ion-item>
      <ion-label position="stacked">Stacked Label</ion-label>
      <ion-input></ion-input>
    </ion-item>
  </div>
</ion-content>`
Third，click the ion-input one after one,  when click after the third,it will show a rectangle like this:
[img](https://discourse-cdn-sjc1.com/ionicframework/uploads/default/optimized/3X/6/d/6d62676779f5dd5da247e19b7f16f541e60030b6_1_281x500.gif)

**Comment by mhartington** [comment]
Perfect, thanks for the imgs! I can reproduce this now.

**Comment by hghammoud** [comment]
If you disabled the scrollAssist for IonicModule, the input clone does not get created and the flickering/white rectangle doesnt show.

This issue is related to calculation of the styles and position of the cloned input.

**Comment by carstenbaumhoegger** [comment]
Is there any ETA for a fix?

**Comment by aaronbach** [comment]
I always experience this behavior in almost every ion-input.  
Do anyone have at least a workaround? 
I have tried to set `opacity: 0` to the overlapping input, but since Ionic 4 is using the Shadow-Dom, I cannot access this properties, but through CSS4 variables.

**Comment by aaronbach** [comment]
Thanks @sean-perkins, it seems to do the trick! It is not perfect, but a lot better than before!
