### ISSUE TITLE
ion-item-option will not expand in Ionic 4.0.0-beta.3

### ISSUE THREAD

**Issue by paulsutherland** [ionic-team/ionic#15304]
# Bug Report

**Ionic Info**

```
Ionic:
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5

System:

   ios-deploy : 2.0.0
   ios-sim    : 7.0.0
   npm        : 6.3.0
   OS         : macOS
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
Adding the attribute expandable on an ion-item-option does not result in the expected behaviour of expanding the option to take up the full width of the item.

**Steps to Reproduce**
1. Create a blank Ionic 4 project
```
ionic start ion-item-expanded blank --type=angular
```
2. Add the follow to the page content 
```
    <ion-item-sliding>
      <ion-item>
        <ion-label>Item</ion-label>
      </ion-item>
      <ion-item-options side="end">
        <ion-item-option color="danger" expandable>Delete</ion-item-option>
      </ion-item-options>
    </ion-item-sliding>
```
3. Serve the app:
```
ionic serve
```
4. Observe the item will not expand the full width when sliding right to left.

**Expected Behavior**
The option should expand to take up the full width of the item.

**Comment by manucorporat** [comment]
Fixed by https://github.com/ionic-team/ionic/commit/127da1ac797a580c8be9b22b3dd93f52e007af87
