### ISSUE TITLE
[4.0.0-beta.3] ion-slides - input disabled

### ISSUE THREAD

**Issue by meta0102** [ionic-team/ionic#15307]
# Bug Report
Ionic:

   ionic (Ionic CLI)          : 4.0.6 (C:\Users\xx\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : not available

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.3.0-next.0
   OS                : Windows 10

**Describe the Bug**
Input's are no longer working within ion-slide. unable to input value

```
company = {
    name: '',
    name2: ''
  }
```

```
<ion-header>
  <ion-toolbar>
    <ion-title>testSlide</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content padding>
  <ion-slides #slides>
    <ion-slide>
      <ion-item>
        <ion-label color="primary" position="stacked">Company</ion-label>
        <ion-input [(ngModel)]="company.name" type="text">
        </ion-input>
      </ion-item>
    </ion-slide>
    <ion-slide>
      <ion-item>
        <ion-label color="primary" position="stacked">Company</ion-label>
        <ion-input [(ngModel)]="company.name2" type="text">
        </ion-input>
      </ion-item>
    </ion-slide>
  </ion-slides>
</ion-content>
```

**Comment by gfitas** [comment]
Same issue

**Comment by paulstelzer** [comment]
This issue should be fixed with beta.17, if not just write here
