### ISSUE TITLE
Angular Compiler requires TypeScript >=2.7.2 and <2.10.0 but 3.0.1

### ISSUE THREAD

**Issue by JamesVanWaza** [ionic-team/ionic#15308]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   NodeJS : v8.11.3 (/usr/local/bin/node)
   npm    : 5.6.0
   OS     : macOS High Sierra
   Xcode  : Xcode 9.1 Build version 9B55

Environment:

   ANDROID_HOME : not set
```

**Describe the Bug**
ERROR in The Angular Compiler requires TypeScript >=2.7.2 and <2.10.0 but 3.0.1 was found instead.

**Steps to Reproduce**
1. `yarn outdated`, `yarn update`
2. After I updated all the packages including typescript the error occurs. 

**Expected Behavior**
Unable to run `ionic serve -c`

**Comment by manucorporat** [comment]
As the error says, you can't update TS to 3.0.1, downgrade it to 2.9.2
