### ISSUE TITLE
White screen on device

### ISSUE THREAD

**Issue by AlexSeoven** [ionic-team/ionic#15317]
# Bug Report

**Ionic Info**
Ionic:

   ionic (Ionic CLI)          : 4.1.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.3, (and 3 other plugins)

System:

   NodeJS : v9.9.0 (/usr/local/bin/node)
   npm    : 5.6.0
   OS     : macOS High Sierra
   Xcode  : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : not set

**Describe the Bug**
when i run: ionic serve all works well
but on device(android), when i run prod apk, i have white screen and "Ion-page-invisible" class on my page

any suggestions?

**Comment by zxfred** [comment]
Same here. [#15282](https://github.com/ionic-team/ionic/issues/15282) not solved yet.

**Comment by c350156378** [comment]
refers to #15191

**Comment by AlexSeoven** [comment]
i.e. it means ionic v4 doesn't builds correctly?
