### ISSUE TITLE
Unable to submit form with button outside of form (Ionic 4)

### ISSUE THREAD

**Issue by kyleabens** [ionic-team/ionic#15326]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.9.4 (/usr/local/bin/node)
   npm        : 6.2.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
I use a modal to display a form and in the header of the modal I have a 'Done' button which I use to submit the form.  Because this button is in the header tags and the form is in the content tags I use ngForm like this to submit the form...

**Related Code**
```
<ion-header>
  <ion-toolbar>

    <ion-title>Title</ion-title>

    <ion-buttons slot="end">
      <ion-button button type="submit" form="ngForm" [disabled]="form.invalid">
        <ion-text class="done-btn">Done</ion-text>
      </ion-button>
    </ion-buttons>

  </ion-toolbar>
</ion-header>

<ion-content>

  <form [formGroup]="form" id="ngForm" (ngSubmit)="onSubmit()">
  </form>

</ion-content>
```

**Expected Behavior**
Users should be able to submit a form with an ion-button outside of the form.

**Additional Context**
It is important to mention that this method of submitting a form woks in ionic v3

**Comment by MrSparklle** [comment]
There is a workaround for this:

`<ion-button (click)="bookingForm.valid && saveForm()" [disabled]="!bookingForm.valid">`

```
<form [formGroup]="bookingForm">
</form>
````

**Comment by paulstelzer** [comment]
That's no bug, that's normal behaviour. You cannot have a button submit outside a form. If you do see, you have like @MrSparklle mentioned use a method for it
