### ISSUE TITLE
ionInfinite event only fires once for infinite scroll [v4 core]

### ISSUE THREAD

**Issue by lightbeard** [ionic-team/ionic#15325]
# Bug Report

**Ionic Info**
```
N/A - Ionic v4 CDN (latest)
```

**Describe the Bug**
The infinite scroll component works once, but then the `ionInfinite` event does not fire for subsequent scrolls to bottom of `ion-infinite-scroll-content`

**Steps to Reproduce**
http://jsfiddle.net/28oj4rvu/6/

**Expected Behavior**
For `ionInfinite` event to fire after subsequent scrolls to bottom of content

**Comment by manucorporat** [comment]
Your code is wrong, you are not supposed to add anything into ion-infinite-scroll-content:

This is the right way:
<img width="628" alt="screenshot 2018-08-24 at 21 11 36" src="https://user-images.githubusercontent.com/127379/44603220-537dc900-a7e2-11e8-8494-4bd2d0e46f40.png">
