### ISSUE TITLE
fingerPrintAio issue

### ISSUE THREAD

**Issue by Pankaj2109** [ionic-team/ionic#15320]
I am working on ionic 3 hybrid project in that I am using fingerprintaio plugin for fingerprint authentication. I am facing issue, following are the scenario:

**- At device level, passcode is TURNED ON
- No fingerPrint is enrolled/available**

The function isAvailable() present at plugin does not return error message or flag for no fingerPrints are enroll.
please suggest me on this.

**Comment by manucorporat** [comment]
This issue does not seem related with ionic angular, but an cordova plugin, the issue might be better reported here: https://github.com/ionic-team/ionic-native

Thanks!
