### ISSUE TITLE
error TS2307: Cannot find module '../../interface'.

### ISSUE THREAD

**Issue by 1784196067** [ionic-team/ionic#15338]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report

**Current behavior:**

ERROR in node_modules/@ionic/angular/dist/types/components/picker/picker.d.ts(2,30): error TS2307: Cannot find module '../../stencil.core'.
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 656 bytes [initial] [rendered]
node_modules/@ionic/angular/dist/types/components/picker/picker.d.ts(3,125): error TS2307: Cannot find module '../../interface'.
**Expected behavior:**

**Steps to reproduce:**

**Related code:**
import {Picker} from '@ionic/angular/dist/types/components/picker/picker';

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
Thanks for the issue! Could you please provide more code on how you are using Picker? Ideally you should be using `PickerController` and not importing from `dist`. See my comment here: https://github.com/ionic-team/ionic/issues/15099#issuecomment-411879817

**Comment by DBnR1** [comment]
I get the same error from the ToastController. `Ionic serve` still works, but cannot build. Using @ionic/angular 4.0.0-beta.7.

`import { ToastController } from '@ionic/angular';`
...
`constructor(private toastCtrl: ToastController)  {}`
``` typescript
const opts: ToastOptions = {
    message: this.translate.instant('Session saved'),
    duration: 3000
};

this.toastCtrl.create(opts).then(toast => {
    toast.present();
});
```

Results in:

```
ionic build --prod --platform=android
> ng run app:build:production

Date: 2018-09-02T06:44:14.717Z
Hash: eaf2b0b44b951e55fc35
Time: 12360ms
chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.52717a6a7245b513d21e.css (styles) 17.4 kB [initial] [rendered]
chunk {2} polyfills.207dcc605630215505f5.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} main.f58b96bf9bf614ca37d4.js (main) 128 bytes [initial] [rendered]

ERROR in node_modules/@ionic/angular/dist/types/components/toast/toast-interface.d.ts(1,34): error TS2307: Cannot find module '../../interface'.

[ERROR] An error occurred while running subprocess ng.

        ng run app:build:production exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
```

**Comment by brandyscarney** [comment]
@DBnR1 Thanks for the further info, please see my comment here: https://github.com/ionic-team/ionic/issues/15421#issuecomment-418470766

If anyone could provide a repository or way for us to reproduce it would be helpful.
