### ISSUE TITLE
Sliding items nth-child 1+ slides out of view during sliding gesture [v4]

### ISSUE THREAD

**Issue by IsaacSomething** [ionic-team/ionic#15335]
# Bug Report

**Ionic Info**

```
ionic (Ionic CLI)          : 4.1.1 (C:\Users\arkade\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.7
   @capacitor/core           : 1.0.0-beta.7

System:

   NodeJS : v8.9.0 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

**Describe the Bug**
When creating a `ion-item-sliding` and you add more then one `ion-item-option` when the user slides the item left or right, if there are more then one `ion-item-option` 's the items ( other then the first one ) will slide off the view of the item. This only occurs during the sliding transition and reverts to the correct state once sliding gesture has stopped. Also note that the `ion-item-option` 's only start to slide out of view once the `ion-item-sliding` has passed the point of the last item.

**Steps to Reproduce**
1. The issue is actually visible on the docs page, take a look and the example with the title **"On Line w/ Avatar, div only text"**

**Expected Behavior**
The child `ion-item-option`'s should not slide out of view during the sliding gesture

**Additional Context**
This only occurs if the `ion-item-option` has the `expandable` directive

**Comment by paulstelzer** [comment]
Is this issue still exist in beta.17?

**Comment by IsaacSomething** [comment]
No .. looks fixed
https://beta.ionicframework.com/docs/api/item-sliding
