### ISSUE TITLE
Alert and action has no addbutton function v4

### ISSUE THREAD

**Issue by comfortme** [ionic-team/ionic#15333]
# Feature Request

```
**Ionic Info**
Ionic:
   ionic (Ionic CLI) : 4.1.0
System:
   NodeJS : v8.11.1
   npm    : 5.6.0
   OS     : Windows 10
```

**Describe the Feature Request**
alert and action had addbutton functions previously in ionic 3.
please add missing functions to ionic 4

**Describe Preferred Solution**
please add missing functions to ionic 4

**Comment by manucorporat** [comment]
Whats the use case for this? The array of buttons can be configured using the create() method

**Comment by comfortme** [comment]
instead of configuring controllers per page I use a presentAlert(buttons,header) function in a service and return selected option index to the page.
since button texts are dynamic I was using addButton function but I figured out a way to make it work like below.


```

  async presentActionSheet(buttons: Array<ActionSheetButton>, header?: string, subHeader?: string): Promise<any>  {
    const actionSheet: any = await this.actionSheetCtrl.create({ buttons: buttons, header: header, subHeader: subHeader });
    await actionSheet.present();
    return new Promise((resolve) => {
      for (let i = 0; i < buttons.length; i++) {
        buttons[i].handler = () => {
          let navTransition = actionSheet.dismiss();
          navTransition.then(() => {
            resolve(i);
          });
          return false;
        }
      }
    });
  }
```
