### ISSUE TITLE
popover positioning near bottom only works once

### ISSUE THREAD

**Issue by A-Industry** [ionic-team/ionic#15331]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.0

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.7
   @capacitor/core           : 1.0.0-beta.7

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   NodeJS : v8.10.0 (/usr/local/Cellar/node@8/8.10.0/bin/node)
   npm    : 6.4.0
   OS     : macOS High Sierra
   Xcode  : Xcode 9.3 Build version 9E145

```

**Describe the Bug**
The popover appears at the correct position the first time (although without arrow), all following clicks result in popover being shown mostly below the viewport. See gif for unexpected behaviour:

![screen recording 2018-08-25 at 10 32 pm](https://user-images.githubusercontent.com/7711959/44622349-f7d13f80-a8b6-11e8-8093-df999fd4a684.gif)

**Expected Behavior**
I would expect the popover to appear at the same position every time.

**Additional Context**
I suspect the containing HTML element has become longer after showing the popover once, therefore allowing the popover to show under the icon the next time.

**Comment by A-Industry** [comment]
The bottom popover in the documentation has the same problem, so easily reproducible: https://beta.ionicframework.com/docs/api/popover

**Comment by bleuscyther** [comment]
related: https://github.com/ionic-team/ionic/issues/15237
