### ISSUE TITLE
Extend NavController to support Angular's router.navigate calls (rather than just router.navigateByUrl)

### ISSUE THREAD

**Issue by ChrisPearce** [ionic-team/ionic#15332]
# Feature Request

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/Users/chris/.npm-global/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.3, (and 3other plugins)

System:

   NodeJS : v10.9.0 (/usr/local/bin/node)
   npm    : 6.2.0
   OS     : macOS
   Xcode  : Xcode 10.0 Build version 10L232m
```

**Describe the Feature Request**

Extend the navigateForward and navigateBack functionality of the NavController to support both Angular's router.navigateByUrl and Angular's router.navigate.

Currently, navigateForward and navigateBack call Angular's router.navigateByUrl.

The difficult posed by this is that Angular's router.navigateByUrl does not implement some of the NavigationExtras such as { queryParams: { foo: fooValue } }. 
See https://github.com/angular/angular/issues/22611

**Describe Preferred Solution**
It would be very helpful to extend the navController to have 4 methods:
- navigateForward - that uses Angular's router.navigate call
- navigateForwardByUrl - that uses Angular's router.navigateByUrl call
- navigateBack - that uses Angular's router.navigate call
- navigateBackByUrl - that uses Angular's router.navigateByUrl call

This would allow developers to use all the functionality provided by Angular's router navigation functionality.

Currently, developers can't use the Ionic Nav Controller methods if they want to use common application features such as query params. 

**Describe Alternatives**

Workaround is to use Angular's router.navigate call directly but then developers don't get the animation benefits of the Ionic NavController. 

**Related Code**
None

**Additional Context**
https://github.com/angular/angular/issues/22611

**Comment by ptitjes** [comment]
@manucorporat, in https://github.com/ionic-team/ionic/commit/7aa4f1310522ae37165808c54f95baba6a07b43c, you forgot to add `| any[]` to the signature of the first parameter of the methods `navigateBack()` and `navigateRoot()`. You only did it on `navigateForward()`.
