### ISSUE TITLE
ion-select with ngModel and ion-select-options using ngFor will not default correctly when values are numerical

### ISSUE THREAD

**Issue by coreykouns** [ionic-team/ionic#15344]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
My template contains an ion-select with an ngModel tied to a variable of my .ts file. The variable itself is a number, and the ion-select-option (using *ngFor to iterate over items) [value] fields are also numbers. After confirming my variables were being set correctly, the ion-select does not populate with my defaulted value.

**Expected behavior:**
Setting a default value to my ngModel variable will set the default selected value of the attached ion-select.

**Steps to reproduce:**
Create an ion-select with an ngModel attribute, containing an ion-select-option (using *ngFor as an iterator) with its [value] pertaining to a number. Set the ngModel to a number on page init. The ion-select will not show the selected value.

**Related code:**

```
<ion-select [(ngModel)]="record.value">
                                  <ion-select-option *ngFor="let earnCode of earnCodes [value]="earnCode.value">
                                    {{earnCode.description}}
                                  </ion-select-option>
                                </ion-select>
```

**Other information:**
None

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/Users/coreykouns/.nvm/versions/node/v8.11.4/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 6.4.0
   Cordova Platforms     : browser 5.0.3, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic 2.0.3, cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.2, (and 11 other plugins)

System:

   ios-deploy : 1.9.0
   ios-sim    : 5.0.13
   NodeJS     : v8.11.4 (/Users/coreykouns/.nvm/versions/node/v8.11.4/bin/node)
   npm        : 6.4.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

**Comment by kiko555** [comment]
I had the same problem with 4.1.2.

**Comment by kiko555** [comment]
After I change the async data to non-async data, then I can make the select show default value.

**Comment by kiko555** [comment]
> I had the same problem with 4.1.2.
After I change the async data to non-async data, then I can make the select show default value.

**Comment by kiko555** [comment]
> I had the same problem with 4.1.2.

After I change the async data to non-async data, then I can make the select show default value.
