### ISSUE TITLE
ion-refresher in Chrome on iOS activates Chrome's overscroll pull-to-refresh

### ISSUE THREAD

**Issue by rcolinray** [ionic-team/ionic#15346]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)  : 4.1.0 (C:\Users\Colin\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 7.0.1
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   NodeJS : v8.11.1 (C:\Program Files\nodejs\node.exe)
   npm    : 3.10.6
   OS     : Windows 10

Environment:

   ANDROID_HOME : not set
```

**Describe the Bug**
Using pull to refresh in Chrome on iOS activates Chrome's built-in pull-to-refresh which refreshes the entire page.

**Steps to Reproduce**
1. Open the app in Chrome on iOS
2. Pull the app to refresh the page
3. See that Chrome's pull-to-refresh is activated in addition to the ionic refresher

**Related Code**
https://github.com/rcolinray/bug_ionic_refresher_chrome_ios

**Expected Behavior**
Only the ionic refresher is activated

**Additional Context**
I attempted to disable it using `overscroll-behavior-y: contain` as described [here](https://developers.google.com/web/updates/2017/11/overscroll-behavior), but that did not have any effect.

**Comment by mhartington** [comment]
This appears to still be an issue in V4. 
`overscroll-behavior-y` cannot be used in WKWebview as it is not supported.
