### ISSUE TITLE
On iOS the slider is nog displayed correctly after orientation change

### ISSUE THREAD

**Issue by EdwinRikkers** [ionic-team/ionic#15342]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

Ionic:

   ionic (Ionic CLI)          : 4.1.1 
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.3, (and 13 other plugins)

System:

   Android SDK Tools : 26.1.1 
   ios-deploy        : 2.0.0
   NodeJS            : v8.11.3
   npm               : 6.4.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

**Describe the Bug**
In a fullscreen slider (with images) after the change of orientation from portrait to landscape the slider is not displayed correctly anymore (only on iOS)

**Steps to Reproduce**
1. Go to Slider (fullscreen)
2. Change device orientation
3. Slider is not shown correctly

**Comment by mhartington** [comment]
Hi there! Do you have a sample app that we can test against? Can push something to github?
