### ISSUE TITLE
[4.0.0-beta.5] ion-back-button wrong text position in RTL

### ISSUE THREAD

**Issue by berchik** [ionic-team/ionic#15357]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (C:\Users\jo\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.5
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 7.0.1
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (A:\Users\Jo\AppData\Local\Android\sdk)
   NodeJS            : v8.9.3 (A:\Program Files\nodejs\node.exe)
   npm               : 6.1.0
   OS                : Windows 10
```

**Describe the Bug**

Using `dir="rtl"`, the back button text is located on the wrong side of the icon on IOS, 

Top left toolbar showing this **`Back<`**
instead of **`<Back`**

**Comment by AbbasTallaq** [comment]
Same here, even in android the arrow showing in wrong direction

**Comment by Guillerbr** [comment]
ok

**Comment by AbbasTallaq** [comment]
Am working on ionic 4 dev, if this will be fix soon please update... if going to takes time.. then I will role back to ionic 3... 
thanks everybody

**Comment by abennouna** [comment]
I'm currently using this workaround:

```CSS
[dir="rtl"] {
  ion-icon {
    &[name="arrow-forward"],
    &[name="arrow-back"] {
      transform: rotateY(180deg);
    }
  }
}
```

**Comment by abennouna** [comment]
Yes: in RTL mode & out of the box, the icons don't rotate by themselves.

You can check the [demo here](https://abennouna.github.io) and the [demo repository here](https://github.com/abennouna/ionic4-rtl-issue)

**Comment by paulstelzer** [comment]
Yeah, there are a lot of issues related to RTL mode. It would be great if someone can add a PR to resolve this issue
