### ISSUE TITLE
[4.0.0-beta.5] updating results in Maximum call stack size exceeded during startup

### ISSUE THREAD

**Issue by RHinderiks** [ionic-team/ionic#15358]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/Users/rhinderiks/.nvm/versions/node/v8.11.4/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.5
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.0

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.1, (and 13 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/rhinderiks/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.0.0
   NodeJS            : v8.11.4 (/Users/rhinderiks/.nvm/versions/node/v8.11.4/bin/node)
   npm               : 5.6.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
Updating from beta 3 to beta 5 results in the following error when running ionic serve:

ERROR RangeError: Maximum call stack size exceeded
    at isEventTarget (fromEvent.js:60)
    at setupSubscription (fromEvent.js:29)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)

**Steps to Reproduce**
1. update to ionic 4.0.0-beta.5
2. ionic serve

**Comment by abennouna** [comment]
Have you updated the dependencies (Angular / TypeScript) as per the [release notes](https://github.com/ionic-team/ionic/releases/tag/v4.0.0-beta.5)?

**Comment by RHinderiks** [comment]
Yup, Weird thing is beta.4 also has breaking changes for us but not are stated ?

**Comment by RHinderiks** [comment]
Still an issue in beta.7. The app does run however so not blocking at the moment. just a bit weird.

**Comment by RHinderiks** [comment]
In the end just ended up going over all our dependencies and changing versions. works fine now
