### ISSUE TITLE
[4.0.0-beta.5] new issues 

### ISSUE THREAD

**Issue by goelectricstations** [ionic-team/ionic#15352]
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (C:\Users\Computer\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.5
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.0, ios 4.5.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 1.2.1, (and 11 other plugins)

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.3.0-next.0
   OS     : Windows 10

MISSING errors:

content DOES NOT EXIST in:
  async presentLoading() {
    const loading = await this.loadingController.create({
      content: 'Hellooo',
      duration: 2000
    });
    return await loading.present();
  }
willAnimate DOES NOT EXIST in:
  async presentModal(component, componentProps, enableBackdropDismiss, willAnimate) {
    const modal = await this.modalCtrl.create({
      component: component,
      componentProps:  componentProps,
      backdropDismiss: enableBackdropDismiss,
      willAnimate: willAnimate
    });
    return await modal.present();
  }

**Comment by ptitjes** [comment]
@goelectricstations Since beta.5, those properties have changed name.

`LoadingOptions.content` is now `LoadingOptions.message`,
and `ModalOptions.willAnimate` is now `ModalOptions.animated`.
(See https://github.com/ionic-team/ionic/commit/8b768fb73d54923005b82326453aa0ee77fcdbb3)

I believe this issue can be closed.

**Comment by goelectricstations** [comment]
@ptitjes it works, the guide need to be update as well. Thank you

**Comment by manucorporat** [comment]
Awesome! closing..
