### ISSUE TITLE
[4.0.0-beta.5] Content's scrollToPoint() takes 2 parameters instead of 3

### ISSUE THREAD

**Issue by doender** [ionic-team/ionic#15350]
Since updating to beta.5, I cannot use the 3rd `duration` parameter for ``content.scrollToPoint()``

**Comment by ptitjes** [comment]
Idem for the first argument of `content.scrollToTop()` and `content.scrollToBottom()`.

**Comment by RHinderiks** [comment]
If i'm not mistaken scrollTo already was reduced to 2 params leaving out duration. Last time they where available was ionic 3 as far as i remember.

 It looks like these changes have been applied to similar functions.

**Comment by ptitjes** [comment]
@RHinderiks It was added again (see https://github.com/ionic-team/ionic/blob/e0f12598aa22c91f42b3c724b5700740aed2d742/core/src/components/content/content.tsx#L171 and https://github.com/ionic-team/ionic/blob/master/core/src/components.d.ts#L1135).

However, I believe that the signature manipulations in Angular proxies (see https://github.com/ionic-team/ionic/blob/master/angular/src/directives/proxies.ts#L9) makes the optional parameters unusable.

**Comment by ptitjes** [comment]
@doender This is fixed in beta.6.
