### ISSUE TITLE
Page scss not working

### ISSUE THREAD

**Issue by moldstadt** [ionic-team/ionic#15367]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

Adding page-specific styles in the page's scss file doesn't have any effect.  Putting the same styles in the global scss works as expected.

**Expected behavior:**

Adding page-specific styles in the page's scss file should modify the styles for the page.

**Steps to reproduce:**

1. Clone the blank starter.
2. Add the following to home.page.scss:
```
app-home {
	ion-content {
		background-color: aquamarine !important;
	}
}
```
3. This has no effect, but placing the same code in global.scss changes the background colour for the page. 

**Other information:**

It seems like it is incorrectly adding the _ngcontent-c0 attribute on app-home, in the generated style (`app-home[_ngcontent-c0] ...`), but app-home only has an `_nghost-c0` attribute.
When placing the styles in global.scss, it doesn't add any attributes to the generated style.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
$ ionic info
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)          : 4.1.1
   Ionic Framework            : @ionic/angular 4.0.0-beta.5
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

System:

   NodeJS : v8.9.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.1.0
   OS     : Windows 8.1
```

**Comment by fperez-eypscap** [comment]
This is normal in Ionic 4 (Angular 6). Take a look at Shadow Root. You should probably be using :host. If you have many changes in deep HTML elements in Ionic directives, expect big CSS issues.

**Comment by moldstadt** [comment]
Thanks, that pointed me in the direction of [Josh Morony's Shadow DOM tutorial](https://www.joshmorony.com/shadow-dom-usage-in-ionic-web-components/).  I will change my app to use CSS4 variables.

There does, however, seem to be some inconsistency between his tutorial and what I am experiencing.
1. I AM able to change the style of the components if I place the rules in global.scss.
2. I also had a look at the conference app, and changing the page-specific rules seems to work there.

**Comment by manucorporat** [comment]
You can just use encapsulation: Encapsulation.None, in the angular Component decorator
