### ISSUE TITLE
[V4] Missing ion-popover props in Interface

### ISSUE THREAD

**Issue by bleuscyther** [ionic-team/ionic#15366]
in @ionic/core/dist/types/components/popover/popover-interface.d.ts
some of the properties described on the [documentation](https://github.com/ionic-team/ionic/blob/master/core/src/components/popover/readme.md) are missing in the Interface.
```` typescript
export interface PopoverOptions<T extends ComponentRef = ComponentRef> {
    component: T;
    componentProps?: ComponentProps<T>;
    showBackdrop?: boolean;
    backdropDismiss?: boolean;
    translucent?: boolean;
    enterAnimation?: AnimationBuilder;
    leaveAnimation?: AnimationBuilder;
    cssClass?: string | string[];
    event?: Event;
    delegate?: FrameworkDelegate;
    animated?: boolean;
}

````

Missing:

- color
- keyboardClose
- mode
- overlayId

Typescript will not compile unless i either manually add the missing prop or i remove it. It's a small fix.

**Comment by manucorporat** [comment]
Which prop of those are you really interesting in using?

**Comment by bleuscyther** [comment]
hi @manucorporat only the mode.
