### ISSUE TITLE
[4.0.0.beta-5] @HosListener event.preventDefault does not work on ion-button

### ISSUE THREAD

**Issue by dalepo** [ionic-team/ionic#15363]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:
   ionic (Ionic CLI)          : 4.0.5 (/usr/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.5
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5
System:
   NodeJS : v9.8.0 (/usr/bin/node)
   npm    : 6.4.0
   OS     : Linux 4.9
```

**Describe the Bug**
I created a directive to prevent clicks from happening in a component. event.preventDefault or stopPropagation does not seem to work if used within a @HostListener click event.

**Steps to Reproduce**
1. Create any Ionic v4 project
2. Create a directive with @HostListener click event, and prevent default the event from there.
3. Use the directive in any button
4. See behaviour

**Related Code**
I made a [stackblitz](https://stackblitz.com/edit/ionic-4-event-propagation)

This is the directive, it contains a hostlistener for the click events.
```
  @Directive({
      selector: '[appDisable]'
  })
  export class DisableDirective {
      
      @Input() ifTruthy: boolean = false;

      @HostListener('click', ['$event']) clickEvent(event: Event): boolean {
          if (this.ifTruthy) {
              console.log('Preventing click');
              console.log('This should prevent further clicks from happening?');
              event.preventDefault();
              event.stopPropagation();
              return false;
          }

          return true;
      }

      constructor(
          private element: ElementRef,
          protected renderer: Renderer2) {
      }

  }
```
And then I added it to an ionic button.

`<ion-button appDisable [ifTruthy]="1 === 1" (click)="presentAlert()">Disabled</ion-button>`

**Expected Behavior**
It is expected that the common (click) button from the component is not executed.

**Additional Context**
[StackOverflow](https://stackoverflow.com/questions/52029616/event-preventdefault-on-ion-button-click-not-working/)
[IonicForum](https://forum.ionicframework.com/t/ionic-4-event-preventdefault-on-ion-button-click-not-working/139788)

**Comment by manucorporat** [comment]
The execution order of events is this case is not ensured, the best way you have to fix this event is using CSS or the disabled prop.

**Comment by dalepo** [comment]
@manucorporat could you elaborate? I added a console log on both methods and the @Hostlistener executes first.
