### ISSUE TITLE
 [v4.beta-5] ion-datetime month and day names can't be defined globally

### ISSUE THREAD

**Issue by MrSparklle** [ionic-team/ionic#15374]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/Users/xxx/.nvm/versions/node/v8.11.3/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.5
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.2, (and 7 other plugins)

System:

   ios-deploy : 2.0.0
   NodeJS     : v8.11.3 (/Users/xxx/.nvm/versions/node/v8.11.3/bin/node)
   npm        : 6.4.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4 Build version 9F1027a
```

**Describe the Bug**
The [official v4 documentation](https://beta.ionicframework.com/docs/api/datetime/#month-names-and-day-of-the-week-names) say that the ion-datetime month and day names can be defined globally.

> "The month names and day names can be either configured at the app level, or individual ion-datetime level"

How I can do that?  Docs need to either be updated or that functionality needs to be added.

In v3 the can define these values at IonicModule.forRoot(MyApp, { monthNames: ['janeiro', ..., ... ] }) inside app.module.ts but this way doesn't work in v4.

**Comment by paulstelzer** [comment]
You can add a const, for example in a constants.ts, and then use it in every component.

export const monthNames = ...

And then in your component import this monthNames and use it in the ion-datetime component
