### ISSUE TITLE
[4.0.0-beta.6] closeSlidingItems() was removed

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic#15378]
We removed closeSlidingItems() in this commit: https://github.com/ionic-team/ionic/commit/1d46973785aa204e13a44a740c9df75751d9f88d#diff-18371551b2381093b54fbcd55f8ebe87L50

It needs to be
A) documented in breaking changes with the new way or
B) added back because this is breaking the conference app

Also we should add some documentation on the new way to use the methods

**Comment by brandyscarney** [comment]
cc @manucorporat

**Comment by manucorporat** [comment]
```
  @Method()
  closeSlidingItems() {
    const item = this.el.querySelector('ion-item-sliding');
    if (item && item.closeOpened) {
      item.closeOpened();
    }
  }
```
