### ISSUE TITLE
[4.0.0-beta.6] ionic serve

### ISSUE THREAD

**Issue by goelectricstations** [ionic-team/ionic#15384]
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (C:\Users\Computer\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.6
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.0, ios 4.5.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 1.2.1, (and 11 other plugins)

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.3.0-next.0
   OS     : Windows 10

after migrate from 4.0.0-beta.5 to 4.0.0-beta.6
Reproduce the error
1) ionic serve
2) error below
[ng] ERROR in ./src/global.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/global.scss)
[ng] Module build failed: Error: Can't resolve '@ionic/angular/css/colors.css'

If I comment /*@import "~@ionic/angular/css/colors.css";*/ works

**Comment by Anthony2539** [comment]
You have to change  the import
``` @import "~@ionic/angular/css/colors.css"; ```  by ``` @import "~@ionic/angular/css/core.css"; ``` in global.scss

It's not a bug, look at in change.log ;)

**Comment by goelectricstations** [comment]
thanks all good now I will close

**Comment by peterennis** [comment]
The bug was in starters.
https://github.com/ionic-team/starters/commit/e58d353c185a0fa02db962888f2332f7377ffea3
