### ISSUE TITLE
Issue with Ionic 4 Slides 

### ISSUE THREAD

**Issue by akkitheakhil** [ionic-team/ionic#15380]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.1
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 4 other plugins)

System:

   NodeJS : v9.5.0 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10

```
**Bug**
- Ionic slides having same scroll height for all slide and height becomes as big as the biggest slide..
- If i scroll down in one slide and then i go to the other one. It will be automatically scrolled to the same position as the first slide, which is just stupid. 

**Steps to Reproduce**
1. Make 3 slides 
2. Add different content dynamically to all slides
3. Scroll down in one and go to the other one. 
4. You will see big chunk of white space and it have automatically scrolled to the same position as the slide you scrolled down on. 

**Expected Behavior**
- Each slide should scroll independently. So, scrolling content in one slide wont affect the other one. 
- Height should be different for different slides. Won't be as the height of the biggest slide.

**Any workaround to fix this issue?**
I have a page 3 or 4 slides. I want each slide to have its own individual scroll height rather than slide taking the scroll height to slide with maximum content and I want it to scroll individually as well.

**Comment by paulstelzer** [comment]
This issue should be fixed with beta.17, if not just write here
