### ISSUE TITLE
Menu is destroyed when we detach the view using CustomRouteReuseStrategy

### ISSUE THREAD

**Issue by GuilhermeBCC** [ionic-team/ionic#15383]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1
   Ionic Framework            : @ionic/angular 4.0.0-beta.5
   @angular-devkit/core       : 0.7.1
   @angular-devkit/schematics : 0.7.1
   @angular/cli               : 6.1.1
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5
```

**Describe the Bug**
**Situation:**

Page1 => Page2

Page 1: Contains an ion-split-pane + ion-pane,

Before we go to Page2 we detach Page1 and save.
When return to Page 1 we reattach the view that we saved before

**Problem:**

Ion-menu is disappearing when we reattach Page1.

**Symptoms:**

The menu-enabled class is there, but not the menu-pane-visible.

In MenuController the ion-menu disappears from menus.

I looked at the ion-menu and ion-menu-controller code all and only in the ion-menu componentDidUnload method is removing a menu (MenuController).

**Conclusion:**

When we reattach Page1 ion-menu calls componentDidUnload even though the page is saved in my CustomRouteReuseStrategy.

**Comment by redwolf2** [comment]
Try downgrading to` @ionic/angular@4.0.0-beta.5`

The current version doesn't seem to open the side navigation via swipe or the toggle button at all.

**Comment by paulstelzer** [comment]
I know your issue is older, but #15565 is already in the project backlog, so I close this here
