### ISSUE TITLE
[4.0.0.-beta.6] ion-back-button color can not be changed

### ISSUE THREAD

**Issue by RHinderiks** [ionic-team/ionic#15391]
# Bug Report

**Describe the Bug**
Trying to overrride --ion-color-base to change the color of the ion-back-button since currently its the same color as our header background. However no color change is applied.

When overriding color with !important directly on ion-back-button it does work but this seems hacky

**Expected Behavior**
When overriding a variable i expect this value to be applied ?

**Comment by brandyscarney** [comment]
Thanks for the issue! Please do not override the `--ion-color-base` variable (see https://github.com/ionic-team/ionic/issues/14808). We are working on updating our components to include a `--color` and `--background` variable that can be used to override.

Please follow this issue to track which components still need to be updated: https://github.com/ionic-team/ionic/issues/14850
