### ISSUE TITLE
v4: CSS Style issues

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#15395]
# Bug Report

IMO we need a container to keep all problems for CSS and style issues instead of opening always one new ? What do you think?

- [ ] ion-card in v3 had on MD a default `background-color rgb(255, 255, 255)` in `.card-md`, now there is no color loaded
- [ ] inequality on font between v3 and v4 #14707

**Comment by paulstelzer** [comment]
This is issue should be resolved in beta.17. If I am wrong, please write here!
