### ISSUE TITLE
v4.beta5+6 form submit is broken again

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#15392]
# Bug Report

**Describe the Bug**
Today we migrate from alpha to beta.6 version and all our forms does not work we can not submit the form. There was a similar bug also before which should be closed at the end of July.
But it seems the forms are broken again, for sure from beta.5.

**Steps to Reproduce**
You can test your `conference-app` on the login page, it does not work anymore.
https://github.com/ionic-team/ionic-conference-app/tree/master/src/app/pages/login

**Comment by mhartington** [comment]
I think this is just an issue with the why the form was built, I made some changes to better follow angular guidelines with forms, using `ngSubmit`.

```html

  <form #loginForm="ngForm" novalidate (ngSubmit)="onLogin(loginForm)">
 .....
    <ion-row responsive-sm>
      <ion-col>
        <ion-button type="submit" expand="block">Login</ion-button>
      </ion-col>
      <ion-col>
        <ion-button (click)="onSignup()" color="light" expand="block">Signup</ion-button>
      </ion-col>
    </ion-row>
  </form>
``` 

And things worked fine.
