### ISSUE TITLE
[4.0.0-beta.6] css Range does not properly fit

### ISSUE THREAD

**Issue by goelectricstations** [ionic-team/ionic#15393]
Ionic:

ionic (Ionic CLI) : 4.1.1 (C:\Users\Computer\AppData\Roaming\npm\node_modules\ionic)
Ionic Framework : @ionic/angular 4.0.0-beta.6
@angular-devkit/core : 0.7.5
@angular-devkit/schematics : 0.7.5
@angular/cli : 6.1.5
@ionic/ng-toolkit : 1.0.0
@ionic/schematics-angular : 1.0.1

Cordova:

cordova (Cordova CLI) : 8.0.0
Cordova Platforms : android 7.1.0, ios 4.5.4
Cordova Plugins : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 1.2.1, (and 11 other plugins)

System:

NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
npm : 6.3.0-next.0
OS : Windows 10

Range does not properly fit
![image](https://user-images.githubusercontent.com/20230407/44854226-48a2b880-ac68-11e8-94ed-283bab2a3c47.png)

      <ion-item>
          <ion-range min="-200" max="200" color="secondary">
            <ion-label slot="start">-200</ion-label>
            <ion-label slot="end">200</ion-label>
          </ion-range>
        </ion-item>

**Comment by mhartington** [comment]
This looks to be an issue with the flex properties of the labels and range-slider. Will look into this.

**Comment by goelectricstations** [comment]
@mhartington 

this fix the issue:

ion-range > ion-label {
    flex: initial !important;
}

**Comment by brandyscarney** [comment]
I've confirmed this issue still exists in latest. The following CSS is not being applied: https://github.com/ionic-team/ionic/blob/master/core/src/components/range/range.scss#L30-L32

I can fix this by moving the code to label, but I'm not sure if this is the right solution:

```
:host-context(ion-range.in-item) {
  flex: initial;
}
```

cc @manucorporat
