### ISSUE TITLE
[4.0.0-beta.7] [iOS] Menu doesn't open on pages other than root

### ISSUE THREAD

**Issue by michaeltintiuc** [ionic-team/ionic#15405]
**This is an iOS specific issue, this is not an issue on Android**

When navigating away from the landing page and trying to open the menu, it does not respond to either swipe gesture or controller's `open` method

**Steps to Reproduce**
1. Open the menu on landing page either by swiping or via controller's `open` method
2. Navigate to another page
3. Try to open the menu either by swiping or via controller's `open` method
4. Notice menu does not open
5. Navigate back to previous page
6. Try to open the menu either by swiping or via controller's `open` method
7. Notice menu does not open

**Expected Behavior**
Menu should open on all pages

**Comment by paulstelzer** [comment]
This issue should be fixed with beta.17, if not just write here
