### ISSUE TITLE
Ionic v4 tab page lifecycle events not firing

### ISSUE THREAD

**Issue by jordanpurinton** [ionic-team/ionic#15402]
# Bug Report

**Ionic Info**
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (path/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.3, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (path/Android/Sdk)
   NodeJS            : v8.10.0 (/usr/bin/node)
   npm               : 6.4.0
   OS                : Linux 4.15

**Describe the Bug**
I've been having a lot of issues with lifecycle events such as `ionViewDidEnter`, `ionViewDidLoad`, etc when using tab pages.

For example, I have an app where I'm updating a component in a view, then kicking pack to a home page. When I load the home page it's supposed to call an API to get the updated component. (FYI I'm using angular routing). When I go to the home page however, the call is never fired - not `ngOnInit` or any of the other ones I've mentioned. 

I removed the tab view in my app and everything went back to normal and I'm having no problems. 

**Steps to Reproduce**
Create a tab view, update some data in a page and go back to the tab page and determine whether or not these lifecycle events have triggered.

**Expected Behavior**
For these lifecycle event to happen in a tab view.

**Comment by cthos** [comment]
Related to #15260 methinks?

**Comment by yuricamara** [comment]
Same here with 4.0.0-beta.13

**Comment by paulstelzer** [comment]
See #14566
