### ISSUE TITLE
[V4-beta.7] ion-col is not working inside ion-item

### ISSUE THREAD

**Issue by ferreiraandy** [ionic-team/ionic#15416]
# Bug Report

**Ionic Info**

Ionic:

   ionic (Ionic CLI)          : 4.1.1
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 24.4.1
   NodeJS            : v10.7.0
   npm               : 6.1.0
   OS                : Linux 4.13

**Describe the Bug**

The grid system is not working well when cols are used inside ion-item

**Related Code**

When used grid column inside ion-item the ion-col sizes is ignored

  example:

    <ion-grid padding>
      <ion-item-sliding>
        <ion-item>
          <ion-row>
            <ion-col size-sm="2" size="4">
              item 1
            </ion-col>

            <ion-col size-sm="10" size="8">
              item 2
            </ion-col>        
          </ion-row>
        </ion-item>
      </ion-item-sliding>
    </ion-grid>

However, removing the ion-item, the cols are respecteds

    <ion-grid padding>
      <ion-item-sliding>
        <ion-row>
          <ion-col size-sm="2" size="4">
            item 1
          </ion-col>

          <ion-col size-sm="10" size="8">
            item 2
          </ion-col>        
        </ion-row>
      </ion-item-sliding>
    </ion-grid>

**Expected Behavior**

The ion-col sizes must be interpreted correct.

**Additional Context**

In previous Ionic versions, it was working pretty well

**Comment by bashoogzaad** [comment]
Maybe placing the grid in the ion-item helps?

**Comment by brandyscarney** [comment]
`<ion-item>` requires content to be wrapped in an `<ion-label>` in v4. This is a breaking change: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#label-required

I see it working properly with the following:

```
<ion-grid padding>
  <ion-item>
    <ion-label>
      <ion-row>
        <ion-col size-sm="2" size="4">
          item 1
        </ion-col>

        <ion-col size-sm="10" size="8">
          item 2
        </ion-col>
      </ion-row>
    </ion-label>
  </ion-item>
</ion-grid>
```
