### ISSUE TITLE
[Ionic v4.0.0-beta.7] ion-back-button with defaultHref does not work when starting app on detail page

### ISSUE THREAD

**Issue by pwespi** [ionic-team/ionic#15410]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
This is an ionic-pwa-toolkit project:
"@ionic/core": "4.0.0-beta.7",
"@stencil/core": "0.12.4"
```

**Describe the Bug**
ion-back-button with defaultHref does not work when starting app on detail page

**Steps to Reproduce**
1. clone ionic-pwa-toolkit
2. `npm start`
3. go directly to detail page using the url `http://localhost:3333/profile/ionic`
4. click the `ion-back-button`
5. error:
```
You can't remove all the pages in the navigation stack. nav.pop() is probably called too many times. 
Uncaught (in promise) Error: navigation stack needs at least one root page
```

**Related Code**
https://github.com/ionic-team/ionic-pwa-toolkit

**Expected Behavior**
ion-back-button click should go back to url specified in `defaultHref`

**Comment by pwespi** [comment]
BTW, this used to work in `"@ionic/core": "4.0.0-beta.3"`.

**Comment by corysmc** [comment]
Ran into this issue as well. Here's a codepen reproducing the bug. happens on beta.6 and beta.7 (worked on beta.5)
https://codepen.io/corysmc/pen/BOZYre?editors=1010

**Comment by corysmc** [comment]
fixed in beta.8

**Comment by manucorporat** [comment]
Thanks Cory!
