### ISSUE TITLE
[4.0.0-beta.7] Sliding Items: ionSwipe & exapandable not working properly

### ISSUE THREAD

**Issue by macchie** [ionic-team/ionic#15427]
**Ionic version:**
[ x ] **4.0.0-beta.7**

**I'm submitting a ...**
[ x ] bug report

**Current behavior:**
Sliding Items are not working correctly.
ion-options are not invoking **ionSwipe** method.
ion-item-options are not handling **expandable** prop.

**Expected behavior:**
On full item swipe **ionSwipe** should be called.
ion-item-option should expand on full swipes. 

**Steps to reproduce:**
Add a new Sliding Item with ion-options on both slots with one button each.

**Related code:**
```
<ion-item-sliding>
  <ion-item>
    ...
  </ion-item>

  <ion-item-options side="start" (ionSwipe)="onAddOne()">
    <ion-item-option (click)="onAddOne()" expandable="true">
      ...
    </ion-item-option>
  </ion-item-options>

  <ion-item-options side="end" (ionSwipe)="onVoid()">
    <ion-item-option (click)="onVoid()" expandable="true">
      ...
    </ion-item-option>
  </ion-item-options>
</ion-item-sliding>
```

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.5
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

System:

   NodeJS : v10.9.0 (/usr/bin/node)
   npm    : 6.2.0
   OS     : Linux 4.15

```

**Comment by manucorporat** [comment]
Fixed by https://github.com/ionic-team/ionic/commit/127da1ac797a580c8be9b22b3dd93f52e007af87
