### ISSUE TITLE
ion-select not selecting falsy values

### ISSUE THREAD

**Issue by comfortme** [ionic-team/ionic#15420]
# Bug Report

**Describe the Bug**
ion-select is not selecting if value is 0 or false

**Steps to Reproduce**
1.select 1 first.
2.see it is selected normally
3.select 0 and see its not selected.
4.change 0 to false and see its not selected also.

**Related Code**
https://stackblitz.com/edit/github-igwscn

**Expected Behavior**
select should select falsy values.

**Comment by brandyscarney** [comment]
Note to team: I was able to reproduce this in the core branch using latest. If you add a log in the `@Watch` function of the `value` you will see the value is ` ` where it should be `0`. To reproduce this go to `select/test/basic` and look at the Numbers example here: https://github.com/ionic-team/ionic/blob/master/core/src/components/select/test/basic/index.html#L210-L220

I believe this may be an issue with Stencil but it needs more digging. cc @manucorporat

**Comment by brandyscarney** [comment]
Found the source of the problem. This is actually a problem with the way we set the value in the Alert. Working on a fix.

**Comment by brandyscarney** [comment]
This will be fixed for select using the `alert` interface in the `4.0.0-beta.12` release. I confirmed it is also working using the `popover` or `action-sheet` interface. 

Thank you for the issue!
