### ISSUE TITLE
[4.0.0-beta.7] Undefined variable: "$colors"

### ISSUE THREAD

**Issue by marticrespi** [ionic-team/ionic#15437]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (C:\Users\XXXX\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5
```

**Describe the Bug**
I have followed the migration guide from: https://beta.ionicframework.com/docs/building/migration/
and in the styles part, I moved my css code from my v3 version and I have added the following imports lines only in the global.scss ( from `src/app/app.scss` (v3) to `src/global.scss` (v4))

```
@import '@ionic/angular/css/normalize.css';
@import '@ionic/angular/css/structure.css';
@import '@ionic/angular/css/typography.css';
@import '@ionic/angular/css/colors.css';
@import '@ionic/angular/css/padding.css';
@import '@ionic/angular/css/float-elements.css';
@import '@ionic/angular/css/text-alignment.css';
@import '@ionic/angular/css/text-transformation.css';
@import '@ionic/angular/css/flex-utils.css';
```

And then all the css code..

```
body {
	-webkit-font-smoothing: antialiased;
	font-family: 'Open Sans', sans-serif;
}
```

On the other hand, I have copy my `\src\theme\variables.scss` from my v3 app to v4 (same location).

Where in this file in my v3 app, I had a few imports that they don't work on my v4.

```
@import "ionic.globals";
@import "ionic.theme.default";
```

And all the rest of the code including my $colors declaration

```
// Ionic Variables and Theming. For more info, please see:
// http://ionicframework.com/docs/v2/theming/
// @import "ionic.globals";
// Shared Variables
// --------------------------------------------------
// To customize the look and feel of this app, you can override
// the Sass variables found in Ionic's source scss files.
// To view all the possible Ionic variables, see:
// http://ionicframework.com/docs/v2/theming/overriding-ionic-variables/
$text-color:        #000;
$background-color:  #fff;
// Named Color Variables
// --------------------------------------------------
// Named colors makes it easy to reuse colors on various components.
// It's highly recommended to change the default colors
// to match your app's branding. Ionic uses a Sass map of
// colors so you can add, rename and remove colors as needed.
// The "primary" color is the only required color in the map.
$colors: (
  primary:    #f185cf,
  white: 			#ffffff,
  secondary:  #32db64,
  danger:     #f53d3d,
  light:      #f4f4f4,
  dark:       #222,
  favorite:   #69BB7B,
  twitter:    #53ACEB,
  github:     #000000,
  instagram:  #235D8D,
  facebook:   #307bbe,
  google:     #fd5459,
  vibrant:    #663399
);
```

And my angular.json from my fresh instalation project (with blank option)

```
"styles": [
              {
                "input": "src/theme/variables.scss"
              },
              {
                "input": "src/global.scss"
              }
            ]
```

And when I serve the app, `ionic serve` any component (global.scss included) don't find the $colors array.

```
[ng]       Undefined variable: "$colors".
[ng]       in E:\xxxxxx\src\global.scss (line 32, column 23)

[ng] ERROR in ./src/app/profile/components/orders-component/orders-component.scss
[ng] Module build failed:
[ng]       color: color($colors, white);
```

I think that I have not forgotten anything, and it should work as expected as in my v3 app.

**Comment by tja4472** [comment]
Hi 

colors is now core

> colors.css has been renamed to core.css, the global stylesheet needs to be updated:

https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#400-beta6-2018-08-29

**Comment by marticrespi** [comment]
Hi, thank you for your response.

I have changed the colors line to core, and is still failing..

> [ng] ERROR in ./src/global.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/global.scss)
[ng] Module build failed:
[ng] undefined
[ng]                      ^
[ng]       Undefined variable: "$colors".
[ng]       in E:\Projects\app-ionic4\src\global.scss (line 31, column 23)

It's talking about postcss-loader and sass-loader..

Thanks!

**Comment by bashoogzaad** [comment]
You can not use sass color variables in ionic v4, only CSS variables. See https://beta.ionicframework.com/docs/theming/css-variables

**Comment by peterennis** [comment]
@Medtrack 
Have a look here: https://aesvg.adaept.com/
Repo: https://github.com/peterennis/ae-svg-components
Code: https://github.com/peterennis/ae-svg-components/blob/master/src/ae-icons-component/ae-icons-component.css

It is a Stencil component sample using CSS and extends the icons using css-variables
following the beta docs from here: https://beta.ionicframework.com/docs/theming/color-generator

If you want to do your own theme with ionic/angular then
this is a good start: https://angularfirebase.com/lessons/css-variables-in-ionic-4/#Building-a-Custom-Theme-Generator-with-Ionic-4

**Comment by brandyscarney** [comment]
Thanks for the issue. In Ionic 4 all Sass variables have become internal. This prevents having to rebuild the Ionic source on every style change and allows users to update colors at runtime. You can still use Sass in your own projects (in fact, we still use it in the [conference app](https://github.com/driftyco/ionic-conference-app)). However, we are now taking advantage of CSS variables and CSS to style Ionic components. 

Please take a look at how the conference app sets the colors and global application variables: https://github.com/ionic-team/ionic-conference-app/blob/master/src/theme/variables.scss

I also recommend going through all sections of the [theming documentation](https://beta.ionicframework.com/docs/theming/basics)
  - [Basics](https://beta.ionicframework.com/docs/theming/basics): overview of each section with links to each of them
  - [Platform Styles](https://beta.ionicframework.com/docs/theming/platform-styles): describes the different platforms and how to customize their styles
  - [CSS Variables](https://beta.ionicframework.com/docs/theming/css-variables): describes what CSS variables are, how to set/use them, and has a brief explanation of the Ionic variables
  - [Color Generator](https://beta.ionicframework.com/docs/theming/color-generator): tool that makes it easy to change all variations of an Ionic color
  - [Advanced](https://beta.ionicframework.com/docs/theming/advanced): describes colors and theming variables in depth, lists all global Ionic CSS variables

We also have some more information on this in our breaking changes file: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#theming

If you still have questions on theming, please ask [on the forums](http://forum.ionicframework.com/). If you have ideas for how we can improve the documentation, please create a new issue [on the ionic-docs repository](https://github.com/ionic-team/ionic-docs). Thanks!
