### ISSUE TITLE
[4.0.0-beta.7] ion-item ionChange event firing for every keypress

### ISSUE THREAD

**Issue by ajmchambers** [ionic-team/ionic#15442]
# Bug Report

**Ionic Info**
@ionic/core : 4.0.0-beta.7

**Describe the Bug**
ion-input fires the ionChange event for every keypress, rather than when the input's value has changed and has been committed.

**Steps to Reproduce**
Add an ionChange event listener to an ion-input element, then type into the input

**Related Code**
[a JSFiddle example](https://jsfiddle.net/mbLvn70e/2/) with ion-input and regular input for comparison (check console output):

```html
<ion-card>
   <ion-item>
     <ion-label position="stacked">Test Field</ion-label>
     <ion-input></ion-input>
   </ion-item> 
</ion-card>
<input type="text" />
```

```javascript
var ionInput = document.querySelector('ion-input');
var input = document.querySelector('input');

ionInput.addEventListener('ionChange', function() {
  console.log('ionChange event fired');
});
input.addEventListener('change', function() {
  console.log('change event fired'); 
});
```

**Expected Behavior**
'ionChange' event should behave like a regular input 'change' event where the event is only fired when the value has changed and the field is exited.

**Comment by manucorporat** [comment]
This is by design, `ionChange` is fired every time the `input.value` changes, feel free to use the debounce prop, in order to reduce the number of times ionChange is called!

**Comment by Matttaylor8910** [comment]
> feel free to use the debounce prop

Hello @manucorporat, I agree with @ajmchambers that this is a bug, or at the very least a feature request, I am using (ionChange)="someFunction()" with debounce="500" on an <ion-input>, and the function is still called immediately. Debounce doesn't seem to be implemented for <ion-input>. Could you clarify what you meant?

`<ion-input type="text" placeholder="Email Address" [(ngModel)]="service.user.email" (ionChange)="emailChanged()" debounce="500"></ion-input>`
