### ISSUE TITLE
[4.0.0-beta.7] Top padding toolbar on iOS

### ISSUE THREAD

**Issue by doender** [ionic-team/ionic#15445]
On iOS with beta.7, the toolbar is displayed with too much padding at the top:

![image](https://user-images.githubusercontent.com/4175777/44977665-e21fe200-af68-11e8-95bc-5514604562ec.png)

I am using `statusbar.overlaysWebView(false)`. 

As a workaround, I've added the following CSS rule:
```
html.plt-ios.plt-hybrid, html.plt-ios.plt-pwa {
  --ion-statusbar-padding: 0px !important;
}
```

**Comment by manucorporat** [comment]
unfortunately, it's not a bug. We can not detect when you have a statusbar or not.
You can also use:
```
:root {
 --ion-safe-area-top: 0px;
}
```
