### ISSUE TITLE
Users have to reinstall after every app update, or get infinite loading/splash screen.

### ISSUE THREAD

**Issue by Levy4u** [ionic-team/ionic#15443]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)  : 4.1.1 (/Users/admin/.nvm/versions/node/v10.6.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1, browser 5.0.3, ios 4.5.4
   Cordova Plugins       : cordova-plugin-ionic 5.0.0, cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.0, (and 12 other plugins)

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.6.0 (/Users/admin/.nvm/versions/node/v10.6.0/bin/node)
   npm        : 6.2.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
After updating any part (html, js, css, etc) of the ionic project and uploading the build to test flight and/or the app store, users get an infinite loading/splash screen if they update the app. The only way it works is if you delete the app and re-download. If done, everything works perfectly (until an update comes out).

Edit:

To add to this, restarting the phone seems to allows access without having to reinstall app. I assume most users are going to update and try to open the app shortly after if not immediately. Debugging via xcode doesn't really help me with anything. It shows the device as ready but the root page never loads.

Also, ionic serve does NOT have this issue. It's only when uploading a complete build to TestFlight or the App Store.

**Comment by kael** [comment]
I'm getting a similar behaviour with a PWA using `@stencil/core v0.11.4`.

In some unidentified cases, when opening the webapp from the homescreen, the splash screen appears as frozen and never switches to the main page.

Trying to debug using Chrome remote device debugger, the webapp is detected by the debugger, but the app content (elements, networks, etc) appears as blank, there's no way to know what's happening while the splash screen is freezing.

I'd suspect that it'd be related to SW caching with the splash screen freezing while Workbox is fetching and saving resources in IndexedDB, but there's no hint.

**Comment by Levy4u** [comment]
To add to this, restarting the phone seems to allows access without having to reinstall app. I assume most users are going to update and try to open the app shortly after if not immediately. Debugging via xcode doesn't really help me with anything. It shows the device as ready but the root page never loads.

**Comment by Levy4u** [comment]
Could use some assistance with this. Is there any other place I could post the issues? Any paid support options?

**Comment by kael** [comment]
Can you grab an Android device and watch what's happening using ADB with a faulty build ?

There's perhaps a frozen process that blocks the update, or maybe a problem with WebViews (assuming that's what's used). Try to grep for `chrom*`or for the name of the web engine used by the app.

**Comment by schmitzt3** [comment]
@Levy4u are you using Ionic Pro? I had this same issue using cordova-plugin-ionic. Once I removed it everything started working again. There seems to be an issue with one of the dependencies (cordova-plugin-ionic-webview). I'm using beta.5, but I also tried to upgrade to beta.7 and was having the same issues.

**Comment by Levy4u** [comment]
@kael I made it for iOS but i guess I could package it for android and see.

@schmitzt3 I am using Ionic Pro (deploy). Don't I need the ionic plugin? 

Will try these solutions and report back. Thanks so much, first client job and it's 99% done... just need the users to be able to use the dang thing after updating.

**Comment by schmitzt3** [comment]
@Levy4u yes - you would need it, but we may to report this bug elsewhere.

**Comment by kael** [comment]
@Levy4u To debug WebViews with ADB, you'll need to modify some code and add explicit debug according to that [HowTo](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews) (never used).

**Comment by paulstelzer** [comment]
For me it's more support question than a bug because I have different apps build with Ionic and don't see such a behaviour. So I think you coded something not correct what causes this issue
