### ISSUE TITLE
[4.0.0-beta.7] paths are not correct

### ISSUE THREAD

**Issue by goelectricstations** [ionic-team/ionic#15447]
Ionic:

ionic (Ionic CLI) : 4.1.1 (C:\Users\Computer\AppData\Roaming\npm\node_modules\ionic)
Ionic Framework : @ionic/angular 4.0.0-beta.7
@angular-devkit/core : 0.7.5
@angular-devkit/schematics : 0.7.5
@angular/cli : 6.1.5
@ionic/ng-toolkit : 1.0.0
@ionic/schematics-angular : 1.0.1

Cordova:

cordova (Cordova CLI) : 8.0.0
Cordova Platforms : none
Cordova Plugins : no whitelisted plugins (0 plugins total)

System:

NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
npm : 6.3.0-next.0
OS : Windows 10

after ionic build --prod and run on browser, I get this error:

[INFO] Looks like @angular/cli isn't installed in this project.
![image](https://user-images.githubusercontent.com/20230407/44980695-e9e38480-af70-11e8-83fb-90dabc11a0f6.png)

@mhartington sorry but because you close and block my messages  when I was try to help ionic and  help to fix bugs. I reopen a BUG. I never used hash or router and everthing working on the previews version v3. Why Ionic cannot find his own scripts?
Preview:
https://github.com/ionic-team/ionic/issues/15430

 I will change the paths manual even if this is a clear bug.

**Comment by danieldugger** [comment]
Hosting in IIS? Located in a subdirectory under Default Website? If yes, you’ll need to modify the base href in index.html. You will also have to add a URL rewrite rule in IIS. Angular’s site has the rule to use for IIS.

**Comment by goelectricstations** [comment]
@danieldugger  thank you just fixed by replace:
  <base href="/" />
with 
  <base href="./" />

**Comment by danieldugger** [comment]
No problem!

**Comment by trollanfer** [comment]
In fact, it's not a bug, but a missing feature : instead of 

`ionic build --prod `
 type
`ng build --prod --base-href=/www/`
and you can serve the PWA at yoursite/www/
