### ISSUE TITLE
[Ionic4-beta.6] Datetime restrictions based on maxDate do not update while modal is open

### ISSUE THREAD

**Issue by UVKApps** [ionic-team/ionic#15452]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (C:\Users\Dani\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.6
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

System:

   NodeJS : v8.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.2.0
   OS     : Windows 10
```

**Describe the Bug**
The fields in the selector do not update while the popup is open when a max value is set. 
Example: max value is 15.09.2018 (dd.MM.yyyy), so only 1-15d in month 9, 1-9m in year 2018 should be able to be selected, while in other months all days, and in other years all months should be available for selection. Change the year to 2017, fields do not update and month is still only 1-9 available. Accept the date, reopen the modal and you can select all months. 
Day is completely ignored there are always 31 days available for every month.

**Steps to Reproduce**
1. create datetime with maxDate set.
2. open modal
3. change date around to a date where there should be more selectable options based on maxDate restriction. 
4. restriction did not update
5. accept date
6. reopen modal, restrictions did update

**Expected Behavior**
Restrictions update while selecting date.

**Comment by paulstelzer** [comment]
Does this issue still exist in `beta.17`?

**Comment by UVKApps** [comment]
I updated to beta.17 and the issue is still present. 

I startet a new project from template to record a .gif showing the issue. 

![datetime](https://user-images.githubusercontent.com/40800987/49440476-10a99500-f7c4-11e8-9202-bdebd88af23f.gif)

Whats happening in this gif:
max for ion-datetime is set to "2018-07-08" and min is set to "2016-01-01". 
when selecting in the year 2018 months and days above 07-08 are present but can't be selected. 
After switching to a previous year where they should be able to be selected they are still shown but can't be selected. 
Closing the modal on year 2016 and reopening it lets me select all dates even in the year 2018. Leading me to select 2018-12-31 at the end. Reopening then and the date jumps to 2018-07-08

**Comment by gregor-srdic** [comment]
I am also experiencing this issue in 4.0.0-beta.17

**Comment by paulstelzer** [comment]
Thanks for your response and confirming it. I already added it as bug, so it should fixed until the v4 release :)

**Comment by shomid** [comment]
I have also this issue in 4.0.0-rc-0

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us. I am going to close this for now, but we will be re-evaluating the `ion-datetime` functionality and bugs soon during which we will take a closer look at this issue.

Thanks for using Ionic!
