### ISSUE TITLE
v4: ion-icons are not showing in stackblitz project

### ISSUE THREAD

**Issue by comfortme** [ionic-team/ionic#15456]
# Bug Report

**Ionic Info**

```
ionic/angular 4.0.0-beta.7
```

**Describe the Bug**
icons are not showing in a stackblitz project

**Steps to Reproduce**
1. Go to below project and see the behavior

**Related Code**
https://stackblitz.com/edit/github-igwscn

**Expected Behavior**
icons should show as normal

**Additional Context**
Since ionic fetches the icons on demand I think this might be related to CORS

**Comment by auriou** [comment]
we still do not have the icons.
as for example in the menus.
thx
````
<ion-icon slot="start" [name]="p.icon"></ion-icon>
````

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you take a look if this is fixed in `@ionic/angular@beta.17`?
