### ISSUE TITLE
[Ionic 4.0.0-beta.6] ion-range know vertical alignment while in minimum position

### ISSUE THREAD

**Issue by gregor-srdic** [ionic-team/ionic#15451]
# Bug Report

**Ionic Info**
```
   ionic (Ionic CLI)          : 4.1.1
   Ionic Framework            : @ionic/angular 4.0.0-beta.6
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.0
```

**Describe the Bug**
Knob in ion range is moved down a few pixels in min position.

**Steps to Reproduce**
Create an ion-range element and drag the knob to the min position.

**Related Code**
I believe this is due to applying the border to the range-knob element while in minimum position but not appropriately adapting margin-top setting. 

**Expected Behavior**
Range knob should also be vertically centred when in minimum position.

![zajeta slika](https://user-images.githubusercontent.com/3057225/44991249-c2ea7a00-af93-11e8-888c-eddb020909aa.PNG)

**Comment by paulstelzer** [comment]
So should be resolved with `beta.17`, so I close this issue here. If I am wrong just write here and I reopen it!
