### ISSUE TITLE
Support (click) or (tabClick) for ion-tab item in Ionc 4.0.0-beta.7

### ISSUE THREAD

**Issue by redplane** [ionic-team/ionic#15457]
# Feature Request

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.13 (C:\Users\leoli\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.2
   @angular-devkit/schematics : 0.7.2
   @angular/cli               : 6.1.2
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   Android SDK Tools : 25.2.5
   NodeJS            : v9.8.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

Environment:

   ANDROID_HOME : D:\android-sdk_r24.4-windows\android-sdk-windows
```

**Describe the Feature Request**
I would like to request (click) or (tabClick) support for `ion-tab`.
I'm making an application whose interface is:

![ionic-tab-click](https://user-images.githubusercontent.com/7974095/45024428-8ee28800-b06b-11e8-9705-9499212c41f7.png)

Everything related to navigation was perfect. I could navigate to all tab's content using `ionic-router-outlet`.  Until I tried implementing (click) event for hamburger button (top left of the screen) to display a `ion-menu` on my page.

Previously, on ionic 3, I could use (ionSelect) to catch the event and display the menu using code. 
But now:
- when I click on that button, it displays a blank page to me.
- if I set `href` to `<ion-tab href></ion-tab>`, `(ionSelect)` is not trigger.

I don't understand why ionic doesn't support (click) event for tab item, it is very useful when a developer wants to do something else without navigating to another view.

**Comment by TrayserCassa** [comment]
Maybe you can use the lifecycle events.

But the problem with the menu ist the same as when you use an Action floating Button. The Navigation for the next Page doesn't work.

**Comment by AhmetFUsta** [comment]
Does `(tap)` not work either?

**Comment by redplane** [comment]
I havent tried (tap) since the document doesnt mention anything about it. Ionic angular code doesnt either

**Comment by siva563** [comment]
@redplane  can you help me out paste code here because same code i tried it is not loading tabs (components ) at all.could you please help me out. thanks !!

**Comment by redplane** [comment]
@AhmetFUsta , I tried `tap` event on `tab` but it doesn't work.
By reading ionic angular source code, I don't see any `tap` event emitter.

**Comment by redplane** [comment]
Hello ?? 
Anyone here ?

**Comment by redplane** [comment]
@siva563 , for the code.
Can you send me an email to redplane_dt@yahoo.com.vn. I'll reply you the src.
For this topic, I just want to focus on the `click` event for tab.

**Comment by redplane** [comment]
@Luukschoen , there are 2 things I'm thinking about : 
1. Write a custom directive and listen to `click` or something like that.
2. Use a toolbar and custom its style to be similar to `tab`

I'm following these 2 solutions to check whether any of them is possible or not.
But, to conclude, it is better to have a `tap` or `click` event in `tab` :|

**Comment by Luukschoen** [comment]
@redplane I thought of those options as well. But I like the fact there's this easy to implement UI TabBar and I feel it wouldn't be to much of a hassle to let the tab press/click/tap fire an event, disregarded of the fact you use it to open a page or not. Keep us posted!

**Comment by siva563** [comment]
@redplane it seems mail id is wrong, could you please give me right mail id, or else you can forward code 
[gsivaprasad2009@gmail.com](url)

**Comment by redplane** [comment]
Hello ?

**Comment by paulstelzer** [comment]
Tabs have been developed new in Ionic 4, so this should possible now. Please open a new issue or feature request, if it's still not what you think about
