### ISSUE TITLE
ERROR in node_modules/@ionic/core/dist/types/components/picker/picker.d.ts(119,15): error TS2503: Cannot find namespace 'JSX'.

### ISSUE THREAD

**Issue by 1784196067** [ionic-team/ionic#15468]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
insert the output from ionic info here
```

**Describe the Bug**
When I use 'Picker' in the code and build the project.

**Steps to Reproduce**

**Related Code**
import {Picker} from '@ionic/core/dist/types/components/picker/picker';
import {PickerButton, PickerColumn} from '@ionic/core';

**Expected Behavior**

**Additional Context**
Ionic4
"rxjs": "6.2.2",
"typescript": "~2.7.2"

**Comment by netsesame2** [comment]
Yes, it is there. But seems no affect on building.
