### ISSUE TITLE
[4.0.0-beta.7] [Toast] dismiss function doesn't pass data and role data to onDidDismiss

### ISSUE THREAD

**Issue by TheAppField** [ionic-team/ionic#15477]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/home/linuxbrew/.linuxbrew/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

System:

   NodeJS : v10.7.0 (/home/linuxbrew/.linuxbrew/Cellar/node/10.7.0/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.17
```

**Describe the Bug**
When a Toast message gets dismissed the `ondidDismiss()` `data` and `role` properties are both undefined. But they're passed into it

**Steps to Reproduce**
Simply create a Toast message, present it and call the `onDidDismiss()` Method.
```
const toast = await this.toastCtrl.create({
  message: 'A new version is available',
  showCloseButton: true,
  position: 'bottom',
  closeButtonText: 'Update'
});

toast.present();

const dismiss = await toast.onDidDismiss();
console.log('Dismissed toast', dismiss);
if(dismiss.role === 'close') {
  console.log('Close button pressed!');
}
```

**Related Code**
Sample project can be found here: [GitHub](https://github.com/TheAppField/toast-demo).
Important code is in [home.ts](https://github.com/TheAppField/toast-demo/blob/master/src/app/home/home.page.ts)

**Expected Behavior**
When the toast gets dismissed should at least the role parameter be set. E.g. when it gets dismissed automatically (duration) it can be set to `'automatic'`. When closing via the close Button `'close'`.
So we can perform some action based on whether the user clicked the button or not. E.g. reload the page to update the service worker.

**Additional Context**
I guess the issue can be fixed in the [toast.tsx file](https://github.com/ionic-team/ionic/blob/master/core/src/components/toast/toast.tsx)
The `dismiss` has both arguments (`data` and `role`) but when it gets called none are passed. (Also the button doesn't pass anything)

**Comment by russcarver** [comment]
I believe this is also affection `onDidDismiss` for both `loading` and `modal` components.  Related, is the fact that `onDidDismiss` should take a callback as a parameter in each case.  However, between beta5 and beta7, we see this for each:

```
'onDidDismiss': () => Promise<OverlayEventDetail<any>>;
```
where it used to be 
```
'onDidDismiss': (callback?: ((detail: OverlayEventDetail<any>) => void) | undefined) => Promise<OverlayEventDetail<any>>;
```
The comment states that it should accept a callback.

**Comment by doender** [comment]
@TheAppField I'm not sure, but maybe `await toast.present();` instead of just `toast.present();`  works?

**Comment by TheAppField** [comment]
@russcarver 
I guess you're right. I've already tried to implement a `modal`  to select one item and it seems like, there are also some events missing.

@doender 
`await toast.present();` is just waiting for showing the toast. Not dismissing.
Therefore it will immediately fire after the toast has shown up (not dismissed!)

**Comment by mhashmi** [comment]
@russcarver The following works:
```
const toast = await toastCtrl.create(...
toast.onDidDismiss().then(callback);
```
