### ISSUE TITLE
ion-searchbar doesn't emit ionCancel event

### ISSUE THREAD

**Issue by corysmc** [ionic-team/ionic#15476]
# Bug Report

**Ionic Info**
```
ionic/core@4.0.0-beta.7
```

**Describe the Bug**
ion-searchbar doesn't emit ionCancel event. Typings are there, but doesn't actually emit an event.

**Steps to Reproduce**
1. Create new ion-searchbar element
2. add event listener to the element 'ionCancel'
3. type something in
4. tap cancel (ios) or tap back arrow (android)

**Related Code**
[https://codepen.io/corysmc/pen/EevgMa](https://codepen.io/corysmc/pen/EevgMa)

**Expected Behavior**
onCancel event emitted.

**Additional Context**
Notice in the codepen that other events are emitted as expected.

**Comment by gabfiocchi** [comment]
If you add the event (ionCancel) in Angular it does not work either.
