### ISSUE TITLE
V4 - beta 7 ion-ripple-effect not working on div

### ISSUE THREAD

**Issue by hghammoud** [ionic-team/ionic#15470]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.7
   @capacitor/core           : 1.0.0-beta.7
```

**Describe the Bug**
on beta.3 I was able to have a ripple effect on a component. Since I upgraded to beta7 the ripple only works in a `<ion-button>`

**Comment by JMMgit** [comment]
I tried adding "ion-activable" attribute in the parent element and it seems to work, I don't know if its the right way though.

**Comment by hghammoud** [comment]
@JMMgit Thanks for this lovely workaround!

**Comment by giacomocerquone** [comment]
@hghammoud which workaround did you find?

I can confirm this is a bug, as already said it doesn't even work on browser. @paulstelzer on chrome 69 it works for buttons, but not for divs

**Comment by geferon** [comment]
@giacomocerquone the workaround that they had found, which was for divs and other elements in which the ion-ripple-effect didn't work, was by adding the ion-activable attribute to the parent of the ion-ripple-effect.

**Comment by hghammoud** [comment]
its ion-activatable now. :D

**Comment by giacomocerquone** [comment]
beta7: both ion-activable and ion-activatable are not known elements, so what? @geferon

**Comment by giacomocerquone** [comment]
@hghammoud wrong, on beta7 it works with ion-activable!
Thanks a lot guys!

**Comment by amitairos** [comment]
Beta 12 it's ion-activatable, but it makes the whole ion-content ripple, even though I put it on a div...

**Comment by raymond-yan** [comment]
> Beta 12 it's ion-activatable, but it makes the whole ion-content ripple, even though I put it on a div...

I have the same issue with you on beta 12. It works fine on android devices with ion-activatable but makes the whole page ripple on iOS devices.

**Comment by paulstelzer** [comment]
I think this issue has resolved in `beta.17`. Can anyone confirm? Or is this still an issue?

**Comment by amitairos** [comment]
Indeed it works with adding ion-activatable to the parent element
