### ISSUE TITLE
Feature request: IonChange or similar for ion-select-option [v4 beta 7]

### ISSUE THREAD

**Issue by webprofusion-chrisc** [ionic-team/ionic#15488]
# Feature Request

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.2
   @angular-devkit/schematics : 0.7.2
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.2, (and 7 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/chrisc/Library/Android/sdk)
   ios-deploy        : 2.0.0
   ios-sim           : 7.0.0
   NodeJS            : v8.11.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000
```

**Describe the Feature Request**
Currently in v4 ion-select cannot implement a Select All/Deselect-All option, previously this would have been possible using custom code on the change event for  `ion-select-option`, currently there is no event to bind to. There is currently no other UI provision for Select All.

**Describe Preferred Solution**
Ideally an `ion-select-option` change event for `selected` state would allow custom 'Select All' behaviour to be implemented.

**Describe Alternatives**
An alternative would be to provide official Select All/Deselect all UI and events in ion-select.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! `ion-select` now provides an `ionChange` event. Additionally, you can use the `value` property to implement the select all/select none functionality you described. I am going to close this as the functionality you requested has been implemented.

If you have any more questions regarding how to implement this, feel free to post on our [slack](https://ionicworldwide.herokuapp.com) or on our [forums](http://forum.ionicframework.com).

Thanks for using Ionic!
