### ISSUE TITLE
Can not apply css to ion-select

### ISSUE THREAD

**Issue by parthnayak7448** [ionic-team/ionic#15480]
In ionic 4 I can not apply css to ion-select
For example :- I want to hide the value that has been selected. Just want to show dropdown icon.
I saw there is class has been used to selected value which is name as 'select-text' and i try to apply 

> display:none

 but when i am trying to override in css its not overriding the css.

**Comment by paulstelzer** [comment]
I do not know what you want select (in DOM) directly, but keep attention to shadow dom what is Ionic 4 using of Angular 6. So you need to set `::ng-deep` before

**Comment by parthnayak7448** [comment]
Thanks @paulstelzer  for your help. 
Still facing issue. 
as per your note I have open topic in Ionic forum if you or someone can help. 

[https://forum.ionicframework.com/t/how-to-use-css-on-ionic-4/136785/3](url)

**Comment by matheushf** [comment]
Actually that's not an issue, read this https://www.joshmorony.com/shadow-dom-usage-in-ionic-web-components/. It explains how to style Shadow Dom elements.
