### ISSUE TITLE
<ion-input> located in the lower half of screen are displayed with focus

### ISSUE THREAD

**Issue by marcelusDSA** [ionic-team/ionic#15497]
**Ionic Info**
   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 6.2.0
   Cordova Platforms     : ios 4.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.3, (and 4 other plugins)

System:

   ios-deploy : 1.9.1
   ios-sim    : 5.0.13
   NodeJS     : v10.8.0 (/usr/local/bin/node)
   npm        : 6.2.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

**Describe the Bug**
When i use FormBuilder, FormGroup and  Validators from @angular/forms, ion-input elements contained in the lower half of the screen appear with some pointer event effect on Xcode simulator and in google chrome (in device view) after refreshing the page.

**Steps to Reproduce**
1. Go to home page where the angular form is located 
2. Click on several ion-input's
3. A pointer event effect appears in the 3d and 4th input

**Related Code**

![xcode](https://user-images.githubusercontent.com/14362868/45211222-02fe7500-b292-11e8-8237-2befb2459c1f.gif)

![simulator-chrome](https://user-images.githubusercontent.com/14362868/45211308-3e00a880-b292-11e8-8e81-f2fd544dc977.gif)

![pointer-event 1](https://user-images.githubusercontent.com/14362868/45215170-f16e9a80-b29c-11e8-937d-ae3e07c94237.gif)

https://github.com/marcelusDSA/ionic4-test

**Expected Behavior**
No pointer event effect on any ion-input. 

**Additional Context**
This does not happen on firefox browser.

**Comment by RHinderiks** [comment]
same
