### ISSUE TITLE
[v4.0.0-beta.8] ion-col size not supported

### ISSUE THREAD

**Issue by paulstelzer** [ionic-team/ionic#15495]
# Bug Report

If you use `<ion-col>` with the size property (size-md etc), it's not working. I already did some research and found the issue:

In col.tsx (https://github.com/ionic-team/ionic/blob/master/core/src/components/col/col.tsx) the following `const columns = this.getColumns('size');` always returns "undefined" (in method `calculateSize() `). So it fails and he falls back to auto.

The root cause problem is the `matchBreakpoint();` function. That should be:

```
  if (breakpoint === undefined || breakpoint === '') {
    return true;
  }
```

I will make a PR, will see if they merge this :D

**Comment by comino** [comment]
I can confirm that and just posted the same issue moments after yours. 

https://github.com/ionic-team/ionic/issues/15496

**Comment by paulstelzer** [comment]
@comino I presented the fix above and you could be right: They made changes to that function on 31st August ;)
