### ISSUE TITLE
Picker's onChnage has no effect

### ISSUE THREAD

**Issue by 1784196067** [ionic-team/ionic#15493]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
this.picker.onChange = function () {
        _self.validate(_self.picker);
 }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

```

**Comment by netsesame2** [comment]
As I know, picker has no method or event as the name onChange....

**Comment by 1784196067** [comment]
> As I know, picker has no method or event as the name onChange....
**In ionic3,it exists,but in ionic4 it is canceled.**
In Ionic3:
export declare class Picker extends ViewController {
    private _app;
    **ionChange: EventEmitter<any>;**
    constructor(app: App, opts: PickerOptions, config: Config);
    /**
    * @hidden
    */
    getTransitionName(direction: string): any;
    /**
     * @param {any} button Picker toolbar button
     */
    addButton(button: any): void;
    /**
     * @param {PickerColumn} column Picker toolbar button
     */
    addColumn(column: PickerColumn): void;
    getColumns(): PickerColumn[];
    getColumn(name: string): PickerColumn;
    refresh(): void;
    /**
     * @param {string} cssClass CSS class name to add to the picker's outer wrapper.
     */
    setCssClass(cssClass: string): void;
    /**
     * Present the picker instance.
     *
     * @param {NavOptions} [navOptions={}] Nav options to go with this transition.
     * @returns {Promise} Returns a promise which is resolved when the transition has completed.
     */
    present(navOptions?: NavOptions): Promise<any>;
}

**Comment by pbrain19** [comment]
Have you attempted to use listen for changes via a formcontrol?
