### ISSUE TITLE
[Ionic v4.0.0-beta.7] Top safe area variable is incorrect on angular prod builds

### ISSUE THREAD

**Issue by sbannigan** [ionic-team/ionic#15502]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : not installed
   @ionic/schematics-angular  : 1.0.6

System:

   NodeJS : v8.11.2 (/usr/local/bin/node)
   npm    : 6.0.1
   OS     : macOS
```

**Describe the Bug**
When building an Ionic 4 Angular app with the `--prod` flag, the `--ion-safe-area-top` variable which is set to either the `constant` or `env` inside of the `@supports` block is being overridden by:
```
html {
    --ion-safe-area-top: var(--ion-statusbar-padding)
}
```
This does not occur on regular dev builds and the expected behavior occurs. Something is happening with prod builds that is causing the `@supports` block to not take priority over the pre-defined status bar padding safe area.

See comparisons of a dev build:
<img width="291" alt="screen shot 2018-09-07 at 9 26 43 am" src="https://user-images.githubusercontent.com/15218748/45221675-2c160a00-b280-11e8-8e20-6bb261942c33.png">

And a build with the `--prod` flag:
<img width="295" alt="screen shot 2018-09-07 at 8 40 24 am" src="https://user-images.githubusercontent.com/15218748/45221689-33d5ae80-b280-11e8-983c-b5f59fce1d6e.png">

Not sure what the best fix for this would be since I don't really understand why it is happening. Either not using `@supports` and just let the unsupported variables fall off normally, or wrap the status bar padding section in another `@supports` block like so:
```
@supports (not (padding-top: constant(safe-area-inset-top))) and (not (padding-top: env(safe-area-inset-top))) {
    html{--ion-safe-area-top: var(--ion-statusbar-padding)}
}
```

**Expected Behavior**
CSS should be consistent between dev and prod builds

**Comment by mixuala** [comment]
I had the same problem. Is this an appropriate workaround, or are there other unintended consequences when deploying to other platforms?

`--ion-safe-area-top: var(--ion-statusbar-padding, 0px);`

**Comment by manucorporat** [comment]
Is this still a problem in latest beta?
