### ISSUE TITLE
[Ionic v4.0.0-beta.8] Overlay (modal) remains on top if closed too early

### ISSUE THREAD

**Issue by fperez-eypscap** [ionic-team/ionic#15506]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\fperez\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.8
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.2.1
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-webview 2.1.0, (and 28 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\fperez\AppData\Local\Android\Sdk)
   NodeJS            : v10.8.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Describe the Bug**
Overlay (modal) remains on top if closed too early. The overlay appears without any content, it's transparent but is on top, preventing clicks below it.

**Steps to Reproduce**
Create a modal.
Call await modal.present();
Call dismiss quickly.

**Related Code**
-

**Expected Behavior**
The modal is closed.

**Additional Context**
I should say I have an event handler for an asynchronous operation (message from server) that dismisses the modal. I guess it is been called before finishing await present. I could create some logic to wait until it finishes presenting in order to dismiss it, but should this kind of behavior be managed internally by the framework? Thanks

**Comment by manucorporat** [comment]
Can you share some code example that reproduces the issue?

**Comment by fperez-eypscap** [comment]
I'll try to extract the offending part, as the app is quite bulky and full of plugins.

**Comment by godenji** [comment]
Have seen similar in v4 beta 7, modal is transparent, haven't been able to track down the cause yet.
