### ISSUE TITLE
[Ionic v4.0.0-beta.8] Can't ion-list scroll if ion-items have (tap) or (press)

### ISSUE THREAD

**Issue by fperez-eypscap** [ionic-team/ionic#15504]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\fperez\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.8
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.2.1
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-webview 2.1.0, (and 28 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\fperez\AppData\Local\Android\Sdk)
   NodeJS            : v10.8.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Describe the Bug**
Can't ion-list scroll if ion-items have (tap) or (press)

**Steps to Reproduce**
Create a page with ion-header, ion-content, and whatnot.
Place an ion-list inside the ion-content.
Put several ion-items inside the ion-list, enough to overflow the screen.
Bind events (tap) and/or (press)

**Related Code**
-

**Expected Behavior**
The list can be scrolled to view overflowing items. Tap and press handlers are called when performing those actions.

**Additional Context**
I have seen multiple issues regarding Ionic 4, hammerjs, gestures, etc. But I haven't really seen an official procedure. Tap and press events work, scrolling works if not combined with these. Why not together? What should we do in this case? Thanks!

**Comment by pjhartin** [comment]
This also happens on iOS. Trying to find a solution.

**Comment by manucorporat** [comment]
This issue does not seem related with ionic, but the fact that HammerJs is preventingDefault. We can't do nothing about it, needs to be fixed in the hammerjs side.
