### ISSUE TITLE
where is the Scroll components

### ISSUE THREAD

**Issue by jegged** [ionic-team/ionic#15503]
# Feature Request

**Ionic Info**
in ionic3 i can find Scroll in api ,but i can not find it in ionic 4 beta docs , or is there any other solution

**Describe the Feature Request**
to view some maps or some big image

**Comment by mhartington** [comment]
The ion-scroll component has been removed and is listed in the breaking changes docs.

https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#scroll

Since ion-content is now flex-box based, there was no need to have multiple components that did the same thing.
