### ISSUE TITLE
Ionic 4 beta documentation missing ion-icon component

### ISSUE THREAD

**Issue by codyburleson** [ionic-team/ionic#15518]
Bug template removed as this is not environment specific and pertains only to beta documentation.

At https://beta.ionicframework.com/docs/components , there doesn't seem to be anything about ion-icon. I would expect to see Icon between DateTime and Fab.

**Comment by paulstelzer** [comment]
The reason ion-icon is not presenting in components documentation is that ion-icon is NOT part of the `@ionic/core` instead it is a seperate package. For documentation take a look at https://ionicons.com/ / https://ionicons.com/usage

**Comment by codyburleson** [comment]
That's fair enough. It could be helpful to mention that in the documentation, however, and link over to it. Because the ion-icon component appears in a lot of the sample code. People will be looking for it and they may have no idea that it's not part of the core and that they need to look somewhere else. Personally, I would create a heading for it and at least write one sentence or two and provide a hyperlink. Closing this issue anyway as now I understand. Thank you!
