### ISSUE TITLE
ionic 4 beta 7 loading component didn't show correct on 360 mobile brower in china

### ISSUE THREAD

**Issue by jegged** [ionic-team/ionic#15513]
# Bug Report

**Ionic Info**
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\Jegged\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (C:\android_sdk)
   NodeJS            : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.0
   OS                : Windows 10

360 mobile brower version 8.2.0.128
```
insert the output from ionic info here
```

**Describe the Bug**
link the image down to see the gif effect
http://crmparty-1251004656.picsh.myqcloud.com/loading.gif

**Steps to Reproduce**
 const loading = await this.loadingController.create({
 });

**Comment by netsesame2** [comment]
It seems to just meet in some special customized browsers.
I've the same issue, on Huawei mobile, made in China, too.

During the animation, the SVG circle itself not from the center point, but from top-left point, so it gives a stranger  ugly curve as the GIF shows.

From the code view, the inner <cricle> has an attribute as "transform=translate(32,32)" which seems raise the bug in such browser. 
```
<circle transform="translate(32,32)" r="26"></circle>
```
Remove the attribute, and add some offset to svg, wich can resolve it temporarily.

**Comment by horelvis** [comment]
I have the same issue in emulator with Android 8
<img width="364"  src="https://user-images.githubusercontent.com/7170658/59907305-163a9580-940b-11e9-98ca-e7b5fb5132f4.png">
