### ISSUE TITLE
Universal element visibility based on view size

### ISSUE THREAD

**Issue by johneast** [ionic-team/ionic#15517]
# Feature Request

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

System:

   NodeJS : v8.9.3 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Sierra
```

**Describe the Feature Request**
Now that Ionic4 is targeting desktop just as much as mobile devices, it would be nice if the layout of the grid and other items could be customised based on view size. Quite often, several items on a page need to change their position or visibility based on view size. The `ion-grid` can resize columns based on view width, which is great, but sometimes you want to completely change the layout and hide columns for a small screen. Also other items, such as an `ion-buttons` item in a toolbar would benefit from changing on smaller screens vs larger screens.

I would like the ability to universally show/hide items based on view size

**Describe Preferred Solution**
I would like to do something like the following
```html
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="secondary" hide-md="true" hide-lg="true" hide-xl="true">
        <ion-button>secondary menu button for small screens</ion-buttons>
    </ion-buttons>
    <ion-title>My page title</ion-title>
    <ion-buttons slot="primary" hide-xs="true" hide-sm="true">
      <ion-button>Menu item 1</ion-button>
      <ion-button>Menu item 2</ion-button>
      <ion-button>Menu item 3</ion-button>
    </ion-buttons>
    <ion-buttons slot="primary" hide-md="true" hide-lg="true" hide-xl="true">
      <ion-button>Collapsed menu button</ion-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>
<ion-content padding>
  <ion-grid>
      <ion-row>
          <ion-col hide-xs="true" hide-sm="true" size-md="3" size-lg="2">Left column</ion-col>
          <ion-col size-sm="12" size-md="6" size-lg="5">Middle column</ion-col>
          <ion-col hide-xs = "true" hide-sm="true" size-md="3" size-lg="2">Right column</ion-col>
      </ion-row>
  </ion-grid>
</ion-content>
```
This would result in a grid that removes the left and right column on small devices and also collapses the menu into a single button in the toolbar.

**Describe Alternatives**
I can achieve the above effect by listening to window size changes, setting a variable such as `small` to true once the width of the window gets to the small breakpoint and then use `*ngIf="small"` to hide or show elements as need be. For instance:

app.component.ts
```javascript
import { Component, HostListener } from '@angular/core';

import { Platform } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html'
})
export class AppComponent {

  private small: boolean;

  constructor(
    private platform: Platform,
    private splashScreen: SplashScreen,
    private statusBar: StatusBar
  ) {
    this.initializeApp();
  }

  @HostListener('window:resize', ['$event'])
  onResize(event) {
    this.small = event.target.innerWidth < 576;
  }

  initializeApp() {
    this.platform.ready().then(() => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();
      this.small = this.platform.width() < 576;
    });
  }
}
```

app.component.html
```html
<ion-header>
  <ion-toolbar>
    <ion-title>My page title</ion-title>
    <ion-buttons slot="primary" *ngIf="small">
      <ion-button>Menu item 1</ion-button>
      <ion-button>Menu item 2</ion-button>
      <ion-button>Menu item 3</ion-button>
    </ion-buttons>
    <ion-buttons slot="primary" *ngIf="!small">
      <ion-button>Collapsed menu button</ion-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>
<ion-content padding>
  <ion-grid>
      <ion-row>
          <ion-col *ngIf="!small" size-md="3" size-lg="2">Left column</ion-col>
          <ion-col size-sm="12" size-md="6" size-lg="5">Middle column</ion-col>
          <ion-col *ngIf="!small" size-md="3" size-lg="2">Right column</ion-col>
      </ion-row>
  </ion-grid>
</ion-content>
```
But it seems a shame (and a possible point of errors) that I have to manually listen to size changes for some elements (such as ion-buttons), but not for some others, such as the ion-col width.

**Related Code**
If you are able to illustrate the feature request with an example, please provide a sample application via an online code collaborator such as [StackBlitz](https://stackblitz.com), or [GitHub](https://github.com).

**Additional Context**
Something similar is available in Angular flex-layout, where a flex item can be shown or hidden based on the size of the screen.

e.g.
```html
<div fxShow="true" fxHide.xs="true">
  <div>Column 1</div>
  <div>Column 2</div>
  <div>Column 3</div>
</div>
```

**Comment by jblakeney** [comment]
+1
