### ISSUE TITLE
[ionic 4.0.0, beta 8] Menu disappear

### ISSUE THREAD

**Issue by GuilhermeBCC** [ionic-team/ionic#15527]
And it continues to disappear, I think this behavior is inappropriate, because it restricts the use of the ion-menu and ion-split-pane to just the use case that Ionic proposes (which was not the intention when this component was created). It's best to let us choose the best time to hide the ion-menu.

I would not want to waste any more time creating my own ion-menu. Please fix this.

**Comment by paulstelzer** [comment]
Please upload a repository to verify it because for me the ion-menu with ion-split-pane is working

**Comment by GuilhermeBCC** [comment]
Hello Paul,

I created a stackblitz with this problem: https://stackblitz.com/edit/angular-ionic4-test-hfnc2w?file=src%2Fapp%2Fapp.component.html

Just increase the window until both menus appear. 

The second and the first do not appear at the same time.

Thanks for your attention

**Comment by paulstelzer** [comment]
Ah okay, you not mentioned that you use two split panes, if you just use one it will work with the two menus. So I cannot help you and you have to hope that one of the Ionic Devs take care of this

**Comment by GuilhermeBCC** [comment]
Hello @paulstelzer this problem still occurs. Please you have some news on the solution of this problem.

**Comment by paulstelzer** [comment]
I am just a user of Ionic and I didn't work with two split panes, so I cannot help you and have no news for you. Maybe @brandyscarney or another member of the Ionic Core team can help you

**Comment by GuilhermeBCC** [comment]
sorry for my confusion I was able to solve the problem

**Comment by GuilhermeBCC** [comment]
sorry for my confusion I was able to solve the problem
