### ISSUE TITLE
[ionic 4] ion-button inherits --width var from ion-menu

### ISSUE THREAD

**Issue by AVatch** [ionic-team/ionic#15522]
# Bug Report

**Ionic Info**

```
ionic 4.0.0-beta.8
```

**Describe the Bug**
```ion-button``` inherits the ```width``` var set in the ```ion-menu``` component, breaking any usage of the button inside the menu. Specifically in toolbars/header components, because the button now has the same width as the sidemenu.

**Expected Behavior**
Resolve the name conflict either by renaming the menu's --width to --menu-width or ensure that variable does not propagate down

**Comment by netsesame2** [comment]
I confirm this issue.
@ionic/angular 4.0.0-beta.8 introduce many new css variables. After updated, many unexpected UI changed.

Can be fixed by:
```
ion-button {
    --width: none;
}
```
