### ISSUE TITLE
[ionic 4.0.0, beta 8] ion-col size doesn't work as col-X directive

### ISSUE THREAD

**Issue by marticrespi** [ionic-team/ionic#15526]
# Bug Report

**Ionic Info**
			   ionic (Ionic CLI)          : 4.1.1 (C:\Users\XXX\AppData\Roaming\npm\node_modules\ionic)
			   Ionic Framework            : @ionic/angular 4.0.0-beta.8
			   @angular-devkit/core       : 0.7.5
			   @angular-devkit/schematics : 0.7.5
			   @angular/cli               : 6.1.5
			   @ionic/ng-toolkit          : 1.0.7
			   @ionic/schematics-angular  : 1.0.5

**Describe the Bug**
The parameter size doesn't work as col directive in ionic 3. 
![2018-09-09_22h26_21](https://user-images.githubusercontent.com/6670879/45268618-6ac5e300-b47f-11e8-8135-7ba65cb347fb.png)

You can see two ion-col's inside an ion-row in ionic 3. The bigger tagged with col-9 and the smaller with col-3. They are placed well, respecting their expected size.

But in ionic 4, I have used size 9 or 10 (the second ion-col without size property as explained in http://ionic-docs.herokuapp.com/docs/layout/grid/) and they aren't placed as expected.

![2018-09-09_22h32_57](https://user-images.githubusercontent.com/6670879/45268672-56ceb100-b480-11e8-9709-90c2446a2a72.png)

**Related Code**
Code in v3

		<ion-row>
			<ion-col col-9>
				<h4>Promociones Especiales</h4>
			</ion-col>
			<ion-col col-3>
				<p (click)="ViewAll('promotions')">Ver todo</p>
			</ion-col>
		</ion-row>

Code in v4

			<ion-row>
				<ion-col size="10">
					<h4>Promociones Especiales</h4>
				</ion-col>
				<ion-col>
					<p (click)="ViewAll('promotions')">Ver todo</p>
				</ion-col>
			</ion-row>

Besides that, if you go at the link above in the example where explain the size, you can see that it's the same size than the others, it showed as wider but it's exactly the same size.

![2018-09-09_22h37_05](https://user-images.githubusercontent.com/6670879/45268732-4f5bd780-b481-11e8-9398-daf27f480ba5.png)

**Expected Behavior**
Working as  version 3.

**Comment by patwaswapnil** [comment]
Same problem here. It was working till beta 7 but stopped working when I updated to beta 8. Please address this issue.

**Comment by paulstelzer** [comment]
This will be fixed in next beta release (i pushed a PR what is merged already). So it will work then as  expected:

```
  <ion-row>
    <ion-col size="10">
      <h4>Lorem ipsum title</h4>
      <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et
        dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet
        clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet,
        consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,
        sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea
        takimata sanctus est Lorem ipsum dolor sit amet.</p>
    </ion-col>
    <ion-col>
      <h4>Lorem ipsum title</h4>
      <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et
        dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet
        clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet,
        consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,
        sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea
        takimata sanctus est Lorem ipsum dolor sit amet.</p>
    </ion-col>
  </ion-row>
![chrome_2018-09-10_09-40-15](https://user-images.githubusercontent.com/20501666/45283219-89f35d80-b4dd-11e8-9d79-2704ed9a4626.jpg)

```

**Comment by woodstream** [comment]
@patwaswapnil I have found the ‘size‘ in ion-col is not work in beta8, and I roll-back to beta7, but someone had solved it: https://github.com/ionic-team/ionic/issues/15496

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this since it will be resolved in `beta.9`.
