### ISSUE TITLE
Ionic Beta 7 to 8

### ISSUE THREAD

**Issue by jrayga** [ionic-team/ionic#15528]
# Support Question

I'm new to ionic so i don't what happened. I started my project from 4.0 beta.6 up to now (beta 8). It was working and installing in my phone fine, until I upgraded it to beta 8. When building my app on android platform using the cmd ionic cordova build android --prod there were no errors but I can't install it to my phone. I have this error after installing the app on my phone "App can't be installed". I don't know what happened. Should i just wait for beta 9? Thank you for answering. :)

**Comment by paulstelzer** [comment]
That has (in general) nothing to do with Ionic because export to Android is done by Cordova. Just remove the app from your device and try again

**Comment by jrayga** [comment]
@paulstelzer Yup that was dumb. Thank you. :)
