### ISSUE TITLE
bug(v4-menu): Menu: must have a "content" element to listen for drag events on.

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#15536]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\amitm\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   NodeJS : v10.1.0 (C:\Program Files\nodejs\node.exe)
   npm    : 5.3.0
   OS     : Windows 10
```

**Describe the Bug**
When putting the menu inside a custom component, (`app-menu`) to make the app component less busy, I get the following error:
> Menu: must have a "content" element to listen for drag events on.

Even though I am passing a `[content]` input containing element ref for `ion-router-outlet`

+ The menu icon doesn't show anymore.

**Steps to Reproduce**
1. Generate a new app with menu
2. `ionic g component menu`
3. Put the `ion-menu` in the `app-menu`
4. Put the following in `app.component`:
```html
<ion-app>
  <ion-split-pane>
    <app-menu [content]="content"></app-menu>
    <ion-router-outlet #content main [swipeBackEnabled]="true"></ion-router-outlet>
  </ion-split-pane>
</ion-app>
```

**Expected Behavior**
Menu to show, no error to apear

**Comment by AmitMY** [comment]
Thank you, that solves it mostly. Now It shows the menu, but doesn't respect the split-pane, and never shows it side by side.

**Comment by kael** [comment]
Seems the `<ion-split-pane>`  and/or the `<ion-menu>` are broken. Using a former code sample, it's not rendered anymore with `@stencil/core v0.12.4`.

**Comment by paulstelzer** [comment]
I think the original issue is solved, please open a new issue for this other issue or open a feature request if something should changed

**Comment by beaubrewer** [comment]
@AmitMY if you would like the menu to show over the split-pane you will need to add it to the ion-split-pane and not the ion-router-outlet. I have a working example I just created to confirm.

_Give an id to your ion-split-pane_
`<app-menu></app-menu>
  <ion-split-pane id="main-content">
    <ion-router-outlet main></ion-router-outlet>`

_Set the contentId in your app-menu.component.html_
`<ion-menu type="overlay" side="start" contentId="main-content">`

Hope that helps!

**Comment by paulstelzer** [comment]
This is correct and works since beta.18
