### ISSUE TITLE
Ionic serve taking too much time like 4 to 6 minutes while compiling ionic 3 project

### ISSUE THREAD

**Issue by abinash012** [ionic-team/ionic#15531]
I am using ionic-3 and when I am compiling ionic project through ionic serve command, Its taking 4-6 mins for me.

Versions of following components:

@ionic/cli-utils : 1.19.2
ionic (Ionic CLI) : 3.20.0
global packages:

cordova (Cordova CLI) : 7.0.1 
local packages:

@ionic/app-scripts : 2.1.4
Cordova Platforms  : android 7.1.0
Ionic Framework    : ionic-angular 3.7.1
System:

Android SDK Tools : 26.1.1
Node              : v7.10.1
npm               : 5.4.2 
OS                : Linux 4.4
Environment Variables:

ANDROID_HOME : /home/spaneos/Android/Sdk
Misc:

backend : pro
node version: 7.10.0
npm version: 5.4.2

**Comment by marcelorl** [comment]
same issue

**Comment by ydorea** [comment]
Same issue for me, but it's not 4 to 6 minutes, it's 1 to 1.5 minutes. Yet, compared to the previous ionic versions, it's too long...

**Comment by leandro-hermes** [comment]
Updating Node to version 10 solved for me
