### ISSUE TITLE
[ionic-4] ion-slides not working correctly, infinite horizontal scroll

### ISSUE THREAD

**Issue by Adrian-AGM** [ionic-team/ionic#15533]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   NodeJS : v8.11.3 (/usr/local/bin/node)
   npm    : 5.6.0
   OS     : macOS High Sierra
   Xcode  : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**

ORIGINAL DESCRIPTION:
Ion-slides not working correctly, it is working like an infinite horizontal scroll. Any additional property like _pager_ or properties inside _options_ are ignored.

UPDATED DESCRIPTION:
When resizing screen, ion-slide updates and works fine (See updated example gif below). On device, ion-slide also updates when changing device orientation.

**Steps to Reproduce**
1. Create new project: 
`ionic start slides-demo tabs --type=angular`
2. Add simple ion-slides in HomePage:
```
<ion-slides pager="true">
  <ion-slide>
    Hi
  </ion-slide>
  <ion-slide>
    Hey
  </ion-slide>
</ion-slides>
```
3. Run it on browser or device.

**Additional Context**

ORIGINAL EXAMPLE:
<img src="https://user-images.githubusercontent.com/12048068/45292309-1eb58580-b4f5-11e8-8251-d7403fb47244.gif" width="200"/>

UPDATED EXAMPLE:
<img src="https://user-images.githubusercontent.com/12048068/45358295-52fa7600-b5c9-11e8-8594-b52cbc245625.gif" width="215"/>

**Comment by Adrian-AGM** [comment]
Issue updated:
When resizing screen (browser) or changing device orientation (device) ion-slides updates its view and displays and works fine.

Any tip or solution?

**Comment by bitflower** [comment]
Could be related https://github.com/ionic-team/ionic/pull/15576

**Comment by Adrian-AGM** [comment]
> Could be related #15576

Solved with this fix.
