### ISSUE TITLE
Add platform error for new project

### ISSUE THREAD

**Issue by leoshuaige** [ionic-team/ionic#15549]
**Ionic Info**
![image](https://user-images.githubusercontent.com/26239202/45340483-f98e4900-b5c0-11e8-9dd6-355ef2268607.png)

1、ionic cordova platform add android 
2、See error
![image](https://user-images.githubusercontent.com/26239202/45340635-7caf9f00-b5c1-11e8-81df-ca50482a4d62.png)

I really need your help

**Comment by kerosin** [comment]
Seems to be a cordova related issue.

Just start a new project without adding any platform at first.
Execute  `cordova platform add android --verbose` manually and see further error logs.

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it seems to be resolved but if you are still having issues please create an issue on our [Ionic CLI repo](https://github.com/ionic-team/ionic-cli/issues).
