### ISSUE TITLE
toast should include an overlayIndex according to the documentation

### ISSUE THREAD

**Issue by dangerdan** [ionic-team/ionic#15553]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**
[x] 5.0.0-beta.15

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
overlayIndex isn't included in the ToastOptions interface but is called out in the documentation: https://beta.ionicframework.com/docs/api/toast/

**Expected behavior:**
The overlay index would be accepted and respected

**Steps to reproduce:**
Attempt to create a toast item with an index:

this.toastCtrl.create({
                message: 'test.',
                duration: 3000,
                position: 'top',
                overlayIndex: '1000'
              })

**Other information:**
I only had to look up this property as the toast is no longer on top of modal windows. If the previous behaviour returns so toasts are displayed on top of modals, this isn't needed.
```

**Comment by peterblazejewicz** [comment]
I don't think that's implemented, that's probably the reason why it is hidden from creation options. Current details:
https://github.com/ionic-team/ionic/blob/bf486e2c99c74db7dcaa752d7d46446f9fbe5f11/core/src/utils/overlays.ts#L13-L14

**Comment by manucorporat** [comment]
Fixed: https://github.com/ionic-team/ionic/commit/ac42180f144130a33caa09df150751d387054322

`overlayIndex` is an internal property, it should not be handled manually
