### ISSUE TITLE
Critical: Ionic 4 Android platform.is('capacitor') returns false 

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/ionic#15556]
# Bug Report

```
"@capacitor/android": "^1.0.0-beta.7",
"@capacitor/cli": "^1.0.0-beta.7",
"@capacitor/core": "^1.0.0-beta.7",
"@capacitor/ios": "^1.0.0-beta.7",
"@ionic/angular": "^4.0.0-alpha.7",
```

**Describe the Bug**
On Android (emulator) the platform check for `platform.is('capacitor')` always returns false. When accessing the `window.Capacitor` object in the debug tools I see that the platform is "web". 

Although the `window.Ionic` object has `android` listed in the platforms array.

**Steps to Reproduce**
1. Add a check for `platform.is('capacitor')`
2. Emulate on Android device or emulator
3. See that the check is always false

**Related Code**
```
import { Platform } from '@ionic/angular';

constructor(private platform: Platform) {}

ngOnInit() {
    if (this.platform.is('capacitor')) {
        console.log('running in capacitor');
    } else {
        console.log('not running in capacitor');
    }
}
```

**Expected Behavior**
The platform check should return `true` on Android devices/emulators.

**Comment by manucorporat** [comment]
Seems like a capacitor bug then, cc @jcesarmobile

**Comment by jcesarmobile** [comment]
Can you try with `"@ionic/angular": "4.0.0-beta.7"` instead of alpha 7? I can't reproduce there.

Also, what do you mean by "emulate"?

**Comment by sean-perkins** [comment]
Resolved with updating the dependencies - what an error on my part. 

& by emulate I mean running on the emulator. Thanks for the quick responses!
