### ISSUE TITLE
Page changed to does not display (prior page does instead) - beta 8

### ISSUE THREAD

**Issue by russcarver** [ionic-team/ionic#15552]
# Bug Report
```
**Ionic Info**
Ionic:

   ionic (Ionic CLI)          : 4.1.2
   Ionic Framework            : @ionic/angular 4.0.0-beta.8
   @angular-devkit/core       : 0.8.1
   @angular-devkit/schematics : 0.8.1
   @angular/cli               : 6.2.1
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/me/Library/Android/sdk)
   NodeJS            : v8.11.4 (/Users/me/.nvm/versions/node/v8.11.4/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
When you navigate from one page to the next, the transition occurs, but then the first page remains on the screen.

**Steps to Reproduce**
1. Have multiple pages in an app
2. Click on something in the 1st page (I used home/start page) to go to the 2nd
3. Notice the page transition
4. 1st page loads up

**Related Code**
```
const routes: Routes = [
  { path: '', redirectTo: 'lobby', pathMatch: 'full' },
  { path: 'game/:tournamentId/:gameId/:playerId', loadChildren: './game-page/game.module#GamePageModule' },
  { path: 'lobby', loadChildren: './lobby-page/lobby.module#LobbyPageModule' }
];
```

**Expected Behavior**
The second page should appear.

**Additional Context**
My app routing module has not changed since upgrading from beta 5. Both pages are lazy loaded in routing but the 1st page is in the imports of `app.module.ts`.

I noticed the first page remains in the DOM and has the `ion-page-hidden` class added to it when the page is navigated away from.

The temporary fix for me is to add this to my global CSS:
```
.ion-page.ion-page-hidden {
  display: none;
}
```

**Comment by manucorporat** [comment]
Can you share your `global.css` file?

**Comment by russcarver** [comment]
I think I took out colors.scss and forgot to put in core.scss with the iupgrade.

**Comment by paulstelzer** [comment]
So it's resolved, correct?
