### ISSUE TITLE
In need of Ionic expert contractor to help with slow responsiveness of app

### ISSUE THREAD

**Issue by jonathanwoahn** [ionic-team/ionic#15563]
We're having some serious responsiveness performance issues with our app, and are in need of an ionic expert who can help us diagnose what we're doing wrong. We're willing to pay someone to come help us figure this out.

Just as a high level description of what's going on--we're seeing an issue with our product where in certain cases, the app doesn't respond to a user clicking for 1-3 seconds. It's causing all sorts of unanticipated effects on the stability of the app, we need some help!

If you or someone you know can help us, please respond to this post or send me an email directly at jonathan@ampogee.com.

Thanks!

**Comment by bleuscyther** [comment]
Check the slack : https://ionicworldwide.herokuapp.com/
