### ISSUE TITLE
Split pane breaks with nested views beta.8

### ISSUE THREAD

**Issue by corysmc** [ionic-team/ionic#15565]
# Bug Report

**Ionic Info**
```
@ionic/core@4.0.0-beta.8
```

**Describe the Bug**
Prior to beta.8 ion-split-pane rendered as expected.
Now the split pane is closed and can't be reopened again. For our app this happens on init, for the demo it happens after navigating.

**Steps to Reproduce**
1. Create a nested route that renders an ion-split-pane within another component
2. Navigate to that page
3. Navigate back to the main page
4. Observe the menu is not longer accessible.

**Related Code**
[https://codepen.io/corysmc/pen/EeLeKV?editors=1010](https://codepen.io/corysmc/pen/EeLeKV?editors=1010)

**Expected Behavior**
Ion split pane can be used within a nested route as a nested component. Menu is visible when on larger screens, and can be opened on smaller screens.

**Additional Context**
@manucorporat

**Comment by GuilhermeBCC** [comment]
A few weeks ago I tried to track down the problem, but I did not succeed.

https://github.com/ionic-team/ionic/issues/15383

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm not able to reproduce this using the Codepen in `4.4.2`. Please let me know if this is still a problem and I'll reopen.
