### ISSUE TITLE
Ionic 4 tabs page - Lazy Loading

### ISSUE THREAD

**Issue by abhijitdhobale** [ionic-team/ionic#15560]
# Bug Report

```
Ionic:

   ionic (Ionic CLI) : 4.1.2

System:

   NodeJS : v8.9.4
   npm    : 6.2.0
   OS     : macOS Sierra
```

Ionic 4 tabs page - Lazy Loading
I am using ionic 4. In lazy loading structure after navigating to tab my whole component moves to the bottom. As per my findings 

```<router-outlet></router-outlet>```

is the reason.

![screen shot 2018-09-12 at 3 24 21 pm](https://user-images.githubusercontent.com/35101981/45419319-a1c90e00-b6a4-11e8-95b9-da8ff5f960b8.png)

**Comment by tskweres** [comment]
Created a working example of Ionic 4 lazy loaded tabs that render properly.

https://github.com/tskweres/ionic-lazy-tabs

**Comment by mhartington** [comment]
Closing as duplicate of https://github.com/ionic-team/ionic/issues/14566

Please track that issue instead of opening new issues.

**Comment by siva563** [comment]
> Created a working example of Ionic 4 lazy loaded tabs that render properly.
> 
> https://github.com/tskweres/ionic-lazy-tabs

this url is not working

**Comment by tskweres** [comment]
sorry @siva563 found a bug where it was not lazy afterall and page transitions to child pages did not work, removed
