### ISSUE TITLE
Blank Screen Issue on logout

### ISSUE THREAD

**Issue by soniabehal** [ionic-team/ionic#15569]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (H:\v2-unirely-app\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.10.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Describe the Bug**
For my application i need to restart the ionic app after logout. I am using "window.location.reload()" to achieve the goal. App is restarted, every service and observable is also re-inited. But the issues is when "window.location.reload()" executes my application shows a blank screen (white or black) for few seconds and then main page is loaded.

**Steps to Reproduce**
1. After clearing storage add window.location.reload()
2. app will show a blank screen before main page

**Expected Behavior**
Ionic app should not show the blank screen after reload and should work smooth.

**Comment by webprofusion-chrisc** [comment]
Sounds like you're forcing a browser refresh and reloading your app, which is a little bit of a hack - your view and app state should just be reseting itself to your logged out UI (usually by clearing user state and navigating back to login UI).

**Comment by webprofusion-chrisc** [comment]
@soniabehal that's difficult without seeing your code but in whichever component has the logout UI/button, add your provider to the constructor (if it's not already there) so you can call methods on it. Then add a method (such as `logout()`) to your provider that sets any relevant information back to the defaults (such as user details). Then call that method from your component that has the logout UI.

**Comment by webprofusion-chrisc** [comment]
For further questions like this (support and tips) you should use the Ionic forum: https://forum.ionicframework.com/ - creating issue on the ionic github repository creates unnecessary extra work for the  small team that look after Ionic.
