### ISSUE TITLE
[ionic 4 beta] ion-picker column UI bug

### ISSUE THREAD

**Issue by louis-raine** [ionic-team/ionic#15579]
# Bug Report Ion-picker

UI bug with ion picker, When the picker is opened the individual column items all stack on top of each.

<img width="785" alt="screen shot 2018-09-13 at 10 52 15" src="https://user-images.githubusercontent.com/32838528/45481325-2bc7b400-b743-11e8-8e98-42bab0db11bf.png">

double clicking on a column then expands the column.

<img width="774" alt="screen shot 2018-09-13 at 10 52 27" src="https://user-images.githubusercontent.com/32838528/45481339-32562b80-b743-11e8-9cb4-9d2f9b3d6945.png">

I appreciate that ionic 4 is still in beta.

Steps to reproduce the behaviour:
1. Create a picker instance and present() it

**Comment by manucorporat** [comment]
which ionic version are you using? can you update to latest beta.8 and test?

**Comment by louis-raine** [comment]
> which ionic version are you using? can you update to latest beta.8 and test?

I have updated to beta.8 and the bug still exists.

<img width="387" alt="screen shot 2018-09-14 at 08 55 33" src="https://user-images.githubusercontent.com/32838528/45537763-13b46b00-b7fd-11e8-8673-48a2feb15e04.png">

I have made a project demoing the bug here -- https://github.com/louis-raine/picker-bug

**Comment by louis-raine** [comment]
Have updated to beta.11 and am still experiencing the bug :(

**Comment by netsesame2** [comment]
I got it. It sure works.
All is one missing param set.
```
selectedIndex: 0
```
Above field for PickColumn must be set manually, otherwise it is not working.
