### ISSUE TITLE
Black screen is appearing while app starting in ionic 4?

### ISSUE THREAD

**Issue by amit-dubey-2018** [ionic-team/ionic#15577]

**Comment by kael** [comment]
Which version ?

**Comment by amit-dubey-2018** [comment]
> Which version ?

Version 4, Which is in beta release!

**Comment by kael** [comment]
Please, read how to open a ticket and follow the steps suggested for bug report, specially by adding the **precise** version used and the OS environment.

**Comment by amit-dubey-2018** [comment]
Ok sorry for that, I'm closing this ticket. But can you help me regarding this?

**Comment by kael** [comment]
You don't need to close the ticket.

Provide the info returned by `ionic info`.

Search for [issues mentioning "blank screen"](https://github.com/ionic-team/ionic/issues?utf8=%E2%9C%93&q=is%3Aissue+blank+screen).
