### ISSUE TITLE
[Ionic v4.0.0-beta.8] Swiper not available on ion-slides

### ISSUE THREAD

**Issue by paulstelzer** [ionic-team/ionic#15575]
**Describe the Bug**
Error if swiper is still undefined if you try to call a method of `<ion-slides>`

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'update' of undefined
TypeError: Cannot read property 'update' of undefined
```

**Steps to Reproduce**
Add `<ion-slides>` with some slides. Add `@ViewChild(Slides) slides: Slides;` in your code and in your `ngOnInit` try to call a method, e.g.  `this.slides.update();` or anything else.

Swiper is undefined and so an error occurs

**Comment by manucorporat** [comment]
Fixed!

**Comment by bitflower** [comment]
Can you add the commit? Would like to see if it fixes a possible issue I'm having too..
