### ISSUE TITLE
[Ionic 4 Beta8] - Navigation animation not the same speed for ion-content and footer

### ISSUE THREAD

**Issue by hghammoud** [ionic-team/ionic#15574]
When we go forward and backward the  ion-content the slide animation is slower then the footer.

The footer slides to full width first.

**Comment by manucorporat** [comment]
Please, can you open the issue following the issue template? It’s hard to tell what the behavior your are expecting, and why the current one is wrong. Screenshot or even a video can help to solve the issue. Closing for the moment.

**Comment by hghammoud** [comment]
Hope this helps ?
