### ISSUE TITLE
[4.0.0-beta.8] missing git tag and GitHub release

### ISSUE THREAD

**Issue by ghybs** [ionic-team/ionic#15571]
# Bug Report

**Ionic Info**
N/A

**Describe the Bug**
No [git tag](https://github.com/ionic-team/ionic/tags) "`v4.0.0-beta.8`" and no [GitHub release](https://github.com/ionic-team/ionic/releases) "4.0.0-beta.8", whereas version [`4.0.0-beta.8`](https://www.npmjs.com/package/@ionic/core/v/4.0.0-beta.8) is published on npm.

**Steps to Reproduce**
- List of git tags (as reported on GitHub): https://github.com/ionic-team/ionic/tags
- List of GitHub releases: https://github.com/ionic-team/ionic/releases

**Related Code**
N/A

**Expected Behavior**
Whenever a version is published on npm, we would expect a corresponding git tag.
A common practice is also to publish an associated GitHub release.

**Additional Context**
So far ionic publications have followed these practices, so we would guess this situation to be a mistake.

**Comment by RHinderiks** [comment]
Agree, was a bit confused seeing beta 8 bug tickets rolling in

**Comment by manucorporat** [comment]
yep, we had some troubles with the release script, next beta.9 will have it right!
