### ISSUE TITLE
[v4 JS] ion-ripple effect still broken in Firefox

### ISSUE THREAD

**Issue by ghybs** [ionic-team/ionic#15570]
# Bug Report

**Ionic Info**
Directly using @ionic/core version 4.0.0-beta.8 from CDN (e.g. unpkg or jsdelivr)
Firefox 61.0.1.

**Describe the Bug**

**Steps to Reproduce**
1. Go to https://beta.ionicframework.com/docs/api/ripple-effect/ **with Firefox**
2. Switch to MD mode.
3. Click on any of the buttons of the device simulator.
4. No ripple effect on click, but only a kind of "tainting" similar to iOS mode.

**Related Code**
- v4.0.0-beta.8 (MD mode): https://next.plnkr.co/edit/385AsRBy7q9ABFhg?preview

**Expected Behavior**
On user click / tap, buttons should have their full ripple effect in MD mode.

**Additional Context**
Was totally broken previously (https://github.com/ionic-team/ionic/issues/15008), now works fine in Chrome but not fully in Firefox in MD mode.
Also buggy on other Elements than `<ion-button>`, as reported in https://github.com/ionic-team/ionic/issues/15470.

**Comment by paulstelzer** [comment]
I think that has to do with shadow DOM. This is supported in Firefox at version 63 or already the Firefox developer edition (see https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM ). If you use this, the ripple effect will work.
