### ISSUE TITLE
Segment in desktop

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#15586]
Polish ion-segment in desktop:

<img width="1353" alt="screenshot 2018-09-13 at 20 14 00" src="https://user-images.githubusercontent.com/127379/45507184-ab7c6f80-b791-11e8-9e9a-56bcc2a9f281.png">

NOTE:
add a max-width to ion-segment-button might help

**Comment by bensperry** [comment]
Yeap, going to turn MD segment essentially into tabs-top. Per @brandyscarney:

> The plan is to make our MD segment take on the scrollable tabs that just change div / content and then the “tabs” component is the bottom navigation in MD

Probably a post-v4 thing

**Comment by brandyscarney** [comment]
This was completed as part of https://github.com/ionic-team/ionic/issues/16232

Max width matches the spec which is 360px.

<img width="805" alt="screen shot 2018-11-20 at 3 53 35 pm" src="https://user-images.githubusercontent.com/6577830/48802201-7aae3e80-ecdc-11e8-874c-c894cff00bb5.png">
