### ISSUE TITLE
App crash after adding Code-push plugin

### ISSUE THREAD

**Issue by soniabehal** [ionic-team/ionic#15592]
# Bug Report

**Ionic Info**
```
cli packages: (H:\v2-unirely-app\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.10.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Describe the Bug**
Ionic app crashes after adding "cordova-plugin-code-push" plugin to app. A blank screen appears for few seconds and then app crashes, splash screen is also not shown. Ionic serve works fine. 

**Steps to Reproduce**
1. Create an ionic app
2. install ionic cordova plugin add cordova-plugin-code-push
3. build and test

**Expected Behavior**
The application should not crash. There is not code added yet.

**Comment by rodo593** [comment]
Same issue here, with:
`Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.8.2
   @angular-devkit/schematics : 0.8.2
   @angular/cli               : 6.2.2
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.4.0, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic 5.1.5, cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.3, (and 15 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/user/Library/Android/sdk)
   NodeJS            : v10.7.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra`

**Comment by paulstelzer** [comment]
That's an issue of the Cordova Plugin, not Ionic
