### ISSUE TITLE
Ionic 4: Beta 8, PWA Production Build not working 

### ISSUE THREAD

**Issue by bkarv** [ionic-team/ionic#15590]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.8
   @angular-devkit/core       : 0.8.1
   @angular-devkit/schematics : 0.8.1
   @angular/cli               : 6.2.1
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   ios-deploy : 1.9.1
   NodeJS     : v10.10.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
```

**Describe the Bug**
Ionic 4 trying to do a production build on the starting template (ie tab app with 'World your oyster'). I update my script in package.json to allow for production outputs. I run 'ionic build'. Everything renders as expected. But when I go to the www folder and open index.html I get the following error in the console:

[Error] Not allowed to load local resource: file:///runtime.js
[Error] Not allowed to load local resource: file:///polyfills.js
[Error] Not allowed to load local resource: file:///styles.js
[Error] Not allowed to load local resource: file:///vendor.js
[Error] Not allowed to load local resource: file:///main.js

<img width="446" alt="screen shot 2018-09-14 at 8 57 09 am" src="https://user-images.githubusercontent.com/10624315/45520693-e3210100-b7fd-11e8-9608-aa90c19668e9.png">

**Steps to Reproduce**
1. ionic start myApp tabs --type=angular
2. Update package.json scripts for production output => "build": "ng build --prod",
3. Run ionic build in terminal
4. Open index.html file in www

**Related Code**
Using defaul myApp tabs template.

**Expected Behavior**
In Ionic 3 I usually deploy the files in www folder to my webserver to run as PWA. I expect opening the index.html file in www should run the PWA as per Ionic 3.

**Comment by manucorporat** [comment]
You should always use a http server in order to open your app!
