### ISSUE TITLE
[4.0.0-beta.11] Hardware back button closes overlay but doesn't navigate back

### ISSUE THREAD

**Issue by ptitjes** [ionic-team/ionic#15601]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/opt/npm/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.9
   @angular-devkit/core       : 0.8.1
   @angular-devkit/schematics : 0.8.1
   @angular/cli               : 6.2.1
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.7
   @capacitor/core           : 1.0.0-beta.7

System:

   NodeJS : v8.9.1 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.18
```

**Describe the Bug**
On Android, the hardware back button is now working as expected (closing an overlay, if necessary, or navigating back). However, the capture of the back button events seem to be lost when you send your app to background and then back to foreground.

**Steps to Reproduce**
1. Run an application that have multiple pages navigation and/or use of overlays
2. Enjoy the working hardware back button
3. Send the application to background and then back to foreground
4. Observe that the hardware back button does not respond anymore

**Related Code**
None.

**Expected Behavior**
I would expect it to work for as long as the application is used ;)

**Additional Context**
None.

**Comment by manucorporat** [comment]
This might a bug related to capacitor itself (or maybe not) cc @jcesarmobile 

could you debug if the event 'backbutton' is still emitted in `document`?

**Comment by ptitjes** [comment]
@manucorporat So I am unable to reproduce what happened yesterday. So I will close this issue.

I still don't understand what is the behavior you assigned to the back button. It looks like you rely on `navigator.back()` where you should IMHO do
```
  @ViewChildren(IonRouterOutlet) routerOutlets: QueryList<IonRouterOutlet>;

  // ...

  // And in the handler
  let canGoBack = this.routerOutlets.find((outlet: IonRouterOutlet) => outlet && outlet.canGoBack());
  if (canGoBack) {
    this.navCtrl.goBack();
    return;
  }
```

Is it possible to override the logic set by Ionic for the back button ?

**Comment by ptitjes** [comment]
OK @manucorporat, I had a chance to debug it on `beta.11`. (So I'll edit the title of this ticket.)

Here is the code that I added in my project:
```ts

    if (this.platform.is('android') || this.platform.is('ios')) {
      App.addListener('backButton', data => {
        console.log('>>>>>>>>>>>>>>>>>>>>>> App#backButton', data);
      });

      window.document.addEventListener('backbutton', () => {
        console.log('>>>>>>>>>>>>>>>>>>>>>> window.document#backbutton');
      });

      window.document.addEventListener('ionBackButton', () => {
        console.log('>>>>>>>>>>>>>>>>>>>>>> window.document#ionBackButton');

        // Override Ionic's default behavior
        // (ev as BackButtonEvent).detail.register(50, () => this.goBack());
      });
    }
```

I launch my app on my phone and it initially navigates to the home page of my app. Then I do the following:
1. navigate to a detail page
2. open a modal page from that detail page
3. open a popover select in that modal page
4. press three times the hardware back button (letting some time to process between each press)

The first two press on the back button work as expected (the first one closes the popover and the second one closes the modal). But the third one fails and does nothing even after a period of 20 seconts. Just to be sure, I then click on my own button widget with a `navCtrl.goBack()` call and it succeeds.

Here is the log I get:

```
17:00:48.676 capacitor-runtime.js:365 result App.addListener (#28930351)
17:00:48.679 capacitor-runtime.js:365 result App.addListener (#28930354)
17:00:48.682 capacitor-runtime.js:70 >>>>>>>>>>>>>>>>>>>>>> App#backButton {}
17:00:48.688 capacitor-runtime.js:365 result App.addListener (#28930355)
17:00:48.692 capacitor-runtime.js:365 result App.addListener (#28930356)
17:00:48.696 capacitor-runtime.js:70 >>>>>>>>>>>>>>>>>>>>>> window.document#backbutton
17:00:48.701 capacitor-runtime.js:70 >>>>>>>>>>>>>>>>>>>>>> window.document#ionBackButton
17:00:51.095 capacitor-runtime.js:365 result App.addListener (#28930351)
17:00:51.099 capacitor-runtime.js:365 result App.addListener (#28930354)
17:00:51.102 capacitor-runtime.js:70 >>>>>>>>>>>>>>>>>>>>>> App#backButton {}
17:00:51.110 capacitor-runtime.js:365 result App.addListener (#28930355)
17:00:51.113 capacitor-runtime.js:365 result App.addListener (#28930356)
17:00:51.116 capacitor-runtime.js:70 >>>>>>>>>>>>>>>>>>>>>> window.document#backbutton
17:00:51.121 capacitor-runtime.js:70 >>>>>>>>>>>>>>>>>>>>>> window.document#ionBackButton
17:00:56.045 capacitor-runtime.js:365 result App.addListener (#28930351)
17:00:56.049 capacitor-runtime.js:365 result App.addListener (#28930354)
17:00:56.053 capacitor-runtime.js:70 >>>>>>>>>>>>>>>>>>>>>> App#backButton {}
17:00:56.060 capacitor-runtime.js:365 result App.addListener (#28930355)
17:00:56.065 capacitor-runtime.js:365 result App.addListener (#28930356)
17:00:56.068 capacitor-runtime.js:70 >>>>>>>>>>>>>>>>>>>>>> window.document#backbutton
17:00:56.073 capacitor-runtime.js:70 >>>>>>>>>>>>>>>>>>>>>> window.document#ionBackButton
```
As you can see, both `backbutton` and `ionBackButton` is correctly triggered the three times. So I believe this is the `Handler` code (https://github.com/ionic-team/ionic/blob/master/core/src/utils/hardware-back-button.ts#L28) that is failing.

**Comment by ptitjes** [comment]
Looking at the code in `overlays.tsx` and in `hardware-back-button.ts`, it seems that this is always the handlers of overlays that is executed.

It seems to me that the code is designed so that:
- either listeners should be added/remove every time they are needed (but the one from overlays is added once and for all on the creation of the first overlay).
- or the listeners should register handlers when needed (but there is no conditional in the listener of overlays).

Shouldn't there be a conditional such as `!!getOverlay(doc)` to guard the handler registration ?
Something along the lines:
```ts
export function connectListeners(doc: Document) {
  if (lastId === 0) {
    lastId = 1;
    doc.addEventListener('ionBackButton', ev => {
      if (!!getOverlay(doc)) {
        (ev as BackButtonEvent).detail.register(100, () => closeTopOverlay(doc));
      }
    });

    doc.addEventListener('keyup', ev => {
      if (ev.key === 'Escape') {
        closeTopOverlay(doc);
      }
    });
  }
}
```
