### ISSUE TITLE
[Ionic v4 beta 9] swiper esm import warning

### ISSUE THREAD

**Issue by bitflower** [ionic-team/ionic#15600]
# Bug Report

**Ionic Info**
Using `@ionic/core` in a ui kit that is then imported into a Stencil app.

**Describe the Bug**
After updating from beta 8 to beta 9 I get this:
```
[ WARN  ]  build warn
           'swiper/dist/js/swiper.esm' is imported by
           node_modules/@ionic/core/dist/collection/components/slides/swiper/swiper.js, but could not be resolved –
           treating it as an external dependency
```

**Steps to Reproduce**
Run `npm run dev`

**Comment by manucorporat** [comment]
Please update to beta.11, it was a bad release! thanks
