### ISSUE TITLE
Placeholder not displayed for ion-select due to strict type checking

### ISSUE THREAD

**Issue by admdly** [ionic-team/ionic#15605]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.8.2
   @angular-devkit/schematics : 0.8.2
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 8 other plugins)

System:

   NodeJS : v10.10.0 (/usr/local/Cellar/node/10.10.0/bin/node)
   npm    : 6.4.1
   OS     : macOS High Sierra
   Xcode  : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
Placeholders are not displayed for ion-select components in certain situations using forms. This began with ba2230510e95b31d8a6a6ab103ca09888f8237b5 and is due to strict checking the selectText variable.

I haven't yet pinned down the specifics of when this occurs due to time restrictions and complex use of formBuilder which may be a contributing factor. However, I can confirm that specifying a form control with an initial value of 'undefined' ends up with an actual value of type 'null', which prevents the placeholder from being displayed.

Forcing the value to be undefined, with setValue(undefined) on the control enables the placeholder to be shown.

**Expected Behavior**
The placeholder specified for the ion-select component should be shown when no value is selected.

**Comment by brandyscarney** [comment]
Thanks for the issue! I pushed a fix to change our checks from `=== undefined` to `== null`. I believe this should fix the problem but if you are able to provide a way for us to reproduce this for you I can be certain of it. 

If it is still an issue in `4.0.0-beta.12` I will reopen this. Thank you!
