### ISSUE TITLE
ion-item-sliding not sliding on iOS

### ISSUE THREAD

**Issue by ormejere** [ionic-team/ionic#15608]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI) : 4.1.2

System:

   NodeJS : v8.11.1
   npm    : 5.6.0
   OS     : macOS Sierra

```

**Describe the Bug**
Nothing happens when swiping left on an `<ion-item-sliding>` except for the following error being produced in the console:

```
Uncaught (in promise) Error: navigation stack needs at least one root page
    at Nav.postViewInit (ion-item.ios.js:926)
    at Nav.runTransition (ion-item.ios.js:799)
    at Nav.nextTrns (ion-item.ios.js:782)
    at Nav.queueTrns (ion-item.ios.js:731)
    at Nav.onStart (ion-item.ios.js:1068)
    at fireOnStart (gesture.js:510)
    at tryToCapturePan (gesture.js:504)
    at HTMLBodyElement.pointerMove (gesture.js:469)
```

**Steps to Reproduce**
1. Open the app containing an `<ion-item-sliding>` in a Chrome browser using iOS device simulation (or in Safari on an iOS device)
2. Show Chrome DevTools (or Safari dev tools if running on an iOS device)
3. Show the Console output
4. Swipe left on the sliding item
5. Observe that the item does not slide and the console output shows the above exception

**Related Code**
Clone ionic-pwa-toolkit:
```
git clone https://github.com/ionic-team/ionic-pwa-toolkit my-pwa
```
Apply the following change:
```
diff --git a/src/components/app-profile/app-profile.tsx b/src/components/app-profile/app-profile.tsx
index d9b4db7..b0e7c9e 100644
--- a/src/components/app-profile/app-profile.tsx
+++ b/src/components/app-profile/app-profile.tsx
@@ -32,6 +32,17 @@ export class AppProfile {
           <ion-toggle checked={this.state} onIonChange={(ev) => this.state = ev.detail.checked} />
         </ion-item>
 
+        <ion-list>
+          <ion-item-sliding>
+            <ion-item>
+              Some item
+            </ion-item>
+            <ion-item-options>
+              Some options
+            </ion-item-options>
+          </ion-item-sliding>
+        </ion-list>
+
       </ion-content>
     ];
   }
```

**Expected Behavior**
The item should slide left to reveal the options and no exception should appear in the console output

**Additional Context**
It looks like in iOS the swipe to go back gesture is enabled and the exception is thrown because the current page is the last in the stack.
I have tried setting swipeGesture to false on the `<ion-nav>` but inspecting the value at runtime reveals that it is being forced back to true.
Overwriting swipeGesture with false at runtime (from the console), does disable the swipe back and then the sliding item does slide correctly.
I haven't found a place where I can successfully set this in the code without it being subsequently overwritten, so I currently have no viable workaround.

**Comment by mhartington** [comment]
Actually, what's really doing on here is that the markup is incorrect.

```
        <ion-list>
          <ion-item-sliding>
            <ion-item>Some item</ion-item>
            <ion-item-options>
              <ion-item-option>
                Some options
              </ion-item-option>
            </ion-item-options>
          </ion-item-sliding>
        </ion-list>
``` 

You're missing the child `ion-item-option` component, which is required for sliding items
