### ISSUE TITLE
[4.0.0-beta.11] mobileweb does not exist

### ISSUE THREAD

**Issue by goelectricstations** [ionic-team/ionic#15616]
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\Computer\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 1.2.1, (and 11 other plugins)

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.3.0-next.0
   OS     : Windows 10

![image](https://user-images.githubusercontent.com/20230407/45595746-90d41180-b9b0-11e8-85ca-75238b35007b.png)

also on build phase

ERROR in src/app/pages/home/home.page.ts(273,28): error TS2345: Argument of type '"mobileweb"' is not assignable to parameter of type '"ios" | "ipad" | "iphone" | "android" | "phablet" | "tablet"
| "cordova" | "capacitor" | "electro...'.

**Comment by paulstelzer** [comment]
This is fixed in beta.17
