### ISSUE TITLE
[Ionic v4.0.0-beta.11] ion-checkbox in ngx-datatable issues

### ISSUE THREAD

**Issue by matthew-valenti** [ionic-team/ionic#15614]
# Bug Report

**Ionic Info**
```
Ionic:
   ionic (Ionic CLI)          : 4.1.2 (C:\Users\matth\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

System:
   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

**Describe the Bug**
The ion-checkbox component does not work correctly with ngx-datatable. This ngx-datatable demo shows the use of custom checkboxes to select rows: https://swimlane.github.io/ngx-datatable/#chkbox-selection-template.

When using a standard checkbox component it works:
<input type="checkbox" [checked]="isSelected" (change)="onCheckboxChangeFn($event)"/>

When using an ion-checkbox it breaks:
<ion-checkbox [checked]="isSelected" (ionChange)="onCheckboxChangeFn($event)"></ion-checkbox>

**Steps to Reproduce**
1. Download and "ionic serve" the sample app: https://github.com/Cymetrik/ionic4-ngx-table
2. Click the 1st row checkbox.
3. Click to goto page 2.
4. Click the last row checkbox.
5. Click to goto page 1.

Selected items = 2. Can move back and forth from page 1 to 2 and selection is still correct.

6. In home.page.html, replace ion-checkbox with commented out standard checkbox.
2. Click the 1st row checkbox.
3. Click to goto page 2.
4. Click the last row checkbox.

The first checkbox on row 2 is also checked. This should not occur.

![2018-09-15_2019](https://user-images.githubusercontent.com/8585839/45592528-e95dcd00-b924-11e8-8804-ada6500444db.png)

**Related Code**
Sample Ionic v4.0.0-beta.11 app: https://github.com/Cymetrik/ionic4-ngx-table

**Expected Behavior**
Expecting ion-checkbox to behave the same as standard checkbox when used by third party components.

**Additional Context**

Interestingly, this ion-checkbox behavior changed from 4.0.0-beta.7 to 4.0.0-beta.11. Using ionBlur instead of ionChange almost worked in beta.7 but produces bad results in beta.11.

The column header checkbox (commented out) shows that both a checkbox and ion-checkbox work correctly.

**Comment by bryce13950** [comment]
Thanks for the bug report. Sorry for a late response to this. Do you know if this is still an issue in beta 17?
