### ISSUE TITLE
[4.0.0-beta.11] Input Focus does not work with nativeElement

### ISSUE THREAD

**Issue by chrisbinnefeld** [ionic-team/ionic#15625]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:
   ionic (Ionic CLI)          : 4.1.2 (/usr/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.4

Cordova:
   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.2, (and 4 other plugins)

System:
   Android SDK Tools : 26.0.1 (/opt/android)
   NodeJS            : v10.10.0 (/usr/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.4
```

**Describe the Bug**
A IonInput field won't be focused after calling focus() on the nativeElement.

**Steps to Reproduce**

1. Add ion-input to html
```
<ion-input #input></ion-input>
``` 

2. Use ViewChild for accessing ElementRef of ion-input.
```
@ViewChild('input', { read: ElementRef }) input: ElementRef;
ngAfterViewInit(): void {
   this.input.nativeElement.focus();
}
```
3. Input Element won't be focus after page load.

4. Not using ElementRef will result in a focused element (but this isn't an option in my use case :( ):

```
@ViewChild('input') input: Input;
ngAfterViewInit(): void { 
   this.input.focus();
}
```

**Expected Behavior**
The Input Element should be focused after calling focus() on the native Element.

**Related Issues**

#15268
#15266

**Possible Workaround**

Calling focus() of the native input element which is contained by the ShadowRoot of the IonInput Element results in expected behavior:

```
ngAfterViewInit(): void {
    // Wait for shadowRoot
    setTimeout(() => {
      (this.input.nativeElement.shadowRoot as ShadowRoot).querySelector('input').focus();
    }, 100);
  }
```

**Comment by mhartington** [comment]
Not sure I understand why you need to use ` { read: ElementRef }` here, as we're proxying all method through Angular Component, so the read as ElementRef is not really needed.

**Comment by chrisbinnefeld** [comment]
In the example, you are right, the way over `{ read: ElementRef }` is not needed. But the problem starts where we can only access the element over an `ElementRef`, e.g. in an directive. Maybe there is another way to retrieve the element which I don't know at the moment.

Besides that it should work with the `ElementRef` or am I wrong?

Keep up the good work and thank you!

**Comment by pickfire** [comment]
What about `<input autofocus>`? It does not work in Ionic 3 but I think it probably works in Ionic 4.

**Comment by chrisbinnefeld** [comment]
After updating to `4.0.0-beta.12` everythings works. Thanks!
