### ISSUE TITLE
[ionic.4] ion-item more slots

### ISSUE THREAD

**Issue by RHinderiks** [ionic-team/ionic#15627]
# Feature Request
**Describe the Feature Request**
We would like more slots, For example for keeping things at the top-left of a list item. This is quite normal behaviour when for example using avatars (github being one of those examples

**Describe Preferred Solution**
More slots

**Describe Alternatives**
Change current behaviour so elements aren't centered vertically.

**Comment by brandyscarney** [comment]
Thanks for the issue! This can be done using CSS, like the following:

```html
<ion-item>
  <ion-avatar slot="start"></ion-avatar>
  <ion-label>
    <h1>Heading</h1>
    <h2>Heading</h2>
    <h3>Heading</h3>
  </ion-label>
</ion-item>
```

```css
ion-avatar {  
  align-self: flex-start;
}
```

Here's a Codepen example: https://codepen.io/brandyscarney/pen/qwdJRJ?editors=1100

Is this what you're looking for?
