### ISSUE TITLE
[v4 beta-11] A disabled ion-button executes his (click) function

### ISSUE THREAD

**Issue by MrSparklle** [ionic-team/ionic#15623]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/Users/XXXX/.nvm/versions/node/v8.12.0/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.8.2
   @angular-devkit/schematics : 0.8.2
   @angular/cli               : 6.2.2
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

System:

   NodeJS : v8.12.0 (/Users/XXXX/.nvm/versions/node/v8.12.0/bin/node)
   npm    : 6.4.1
   OS     : macOS High Sierra
```

**Describe the Bug**
A function associated with a `(click)` on DISABLED ion-button was executed.

**Steps to Reproduce**
1. Add a button in the toolbar in the slot=primary
2. Associate any function to event (click) of this button
3. Disabled this button
4. When you click this button, the function associated to this button is executed normally, like it was activated.

**Related Code**
The disabled ion-button in the Toolbar:
```
<ion-header>
  <ion-toolbar>
    <ion-title>
      Ionic Blank
    </ion-title>
    <ion-buttons slot="primary">
      <ion-button (click)="saveData()" disabled>
        <ion-label>
          Save Outside Form
        </ion-label>
      </ion-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>
```

The button "SAVE OUTSIDE FORM" is disabled in the toolbar:
![image](https://user-images.githubusercontent.com/992049/45600576-516bec00-b9d5-11e8-8b39-114daf51a046.png)

When click it, the function associated `saveData()` was executed like we can see on console:
`Save was Executed with a disabled button`

**Expected Behavior**
A disabled button can't be executed.

**Additional Context**
Working example here on Github: https://github.com/MrSparklle/Inc4

**Comment by mhartington** [comment]
Thanks!

**Comment by simonhaenisch** [comment]
@mhartington still happens to me, just updated to `@ionic/core@4.0.0-beta.12`...

Example:

```jsx
<ion-button disabled onClick={(e: any) => console.log(e.target.disabled)} />
```

This actually logs `true`.

I would expect it to not execute the handler on click, or am I supposed to manually check that?

**Comment by mhartington** [comment]
This appears to be a stencil/JSX issue vs an issue with the component.

In a vanilla example, the button renders correctly and pointer events are disabled.

https://codepen.io/mhartington/pen/VEZGBL?editors=1011

![screen shot 2018-09-27 at 9 50 03 am](https://user-images.githubusercontent.com/2835826/46150514-bc6dbc00-c23a-11e8-94f5-e51224e2aecc.png)

But in a stencil app setup, the `disabled` attr/prop is not getting passed to the ion-button

![screen shot 2018-09-27 at 9 50 46 am](https://user-images.githubusercontent.com/2835826/46150556-d3aca980-c23a-11e8-9345-6ed62e9204f2.png)


cc @jthoms1 and @adamdbradley
