### ISSUE TITLE
[4.0.0-beta.11]ion-select not work

### ISSUE THREAD

**Issue by woodstream** [ionic-team/ionic#15626]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
   ionic (Ionic CLI)          : 4.1.2 (/Users/woodstream/.nvm/versions/node/v9.5.0/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.2.2
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6
```

**Describe the Bug**
ion-select not work, show this error:
```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
'ion-option' is not a known element:
```
**Steps to Reproduce**
1. put this content in a page:
```
<ion-item>
  <ion-label>Gender</ion-label>
  <ion-select [(ngModel)]="gender">
    <ion-option value="f">Female</ion-option>
    <ion-option value="m">Male</ion-option>
  </ion-select>
</ion-item>
```
2. Run project
3. See error

**Additional Context**
Does ion-option not export?

**Comment by copaste** [comment]
Yes, there's no such element any more instead you should use 
`<ion-select-option value="f">Female</ion-select-option>`
Check the documentation: [Docs](https://beta.ionicframework.com/docs/api)

**Comment by brandyscarney** [comment]
@copaste is correct, it should be `ion-select-option` now. Thank you for replying! 

If you are coming from v3, we have a list of breaking changes here that may be helpful: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md

🙂
