### ISSUE TITLE
[4.0.0-beta.11] Various Edge Browser Styling Issues 

### ISSUE THREAD

**Issue by ajmchambers** [ionic-team/ionic#15621]
# Bug Report
**Info**
@ionic/core : 4.0.0-beta.11
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134
Chrome Version 69.0.3497.92 (Official Build) (64-bit)

**Describe the Bug**
Been doing some testing in edge and noticed some graphical inconsistencies between edge and chrome, here are some of the things I've noticed:

1. **ion-icon** and **ion-button** in **ion-toolbar** have incorrect color.
2. Material ripple animation not working in edge, not a big deal (though could be an issue with buttons in the toolbar as they display no visual change to indicate that they have been pressed, if no ripple maybe should have a slight dim).
3. **ion-checkbox** appears small and has strange spacing.
4. **ion-input**, **ion-searchbar** placeholder text is not visible in edge, however placeholder is visible for **ion-datetime**.
5. **ion-select-option** text is center-aligned on edge but left-aligned on chrome (looks like edge doesn't like the: `text-align:start` in `.alert-tappable.sc-ion-alert-md`).

Here are some images:
<img width="642" alt="edge-styling-issues" src="https://user-images.githubusercontent.com/5426717/45597949-cb977300-b9cb-11e8-801f-fe6011b071b3.png">
<img width="545" alt="edge-select-issue" src="https://user-images.githubusercontent.com/5426717/45597950-d4884480-b9cb-11e8-8365-d8996bc484dc.png">

**Related Code**
```html
<ion-app>
  <ion-header>
    <ion-toolbar>
      <ion-title>Edge Testing</ion-title>

      <ion-buttons slot="end">
        <ion-button>
          <ion-icon slot="start" name="add"></ion-icon>
          Button Icon &amp; Text
        </ion-button>
      </ion-buttons>

    </ion-toolbar>
  </ion-header>
  <ion-content>

    <ion-card>
      <ion-card-header>
        <ion-card-title>Material Ripple Effect Missing:</ion-card-title>
      </ion-card-header>

      <ion-card-content>
        <ion-button>Click Me</ion-button>
      </ion-card-content>
    </ion-card>

    <ion-card>
      <ion-card-header>
        <ion-card-title>Checkbox looks odd:</ion-card-title>
      </ion-card-header>

      <ion-item>
        <ion-label>Checked</ion-label>
        <ion-checkbox slot="end" checked></ion-checkbox>
      </ion-item>
    </ion-card>

    <ion-card>
      <ion-card-header>
        <ion-card-title>Placeholder text not visible:</ion-card-title>
        <ion-card-subtitle>not always the case like for datetime</ion-card-subtitle>
      </ion-card-header>
        
      <ion-item>
        <ion-label position="stacked">Name</ion-label>
        <ion-input placeholder="Enter your name"></ion-input>
      </ion-item>

      <ion-item>
        <ion-label position="stacked">Date Of Birth</ion-label>
        <ion-datetime placeholder="Enter DOB" display-format="MM/YYYY" picker-format="MMMM YYYY"></ion-datetime>
      </ion-item>

      <ion-searchbar></ion-searchbar>
    </ion-card>

    <ion-card>
        <ion-card-header>
          <ion-card-title>Select option text alignment:</ion-card-title>
          <ion-card-subtitle>Left aligned in chrome, centered in edge</ion-card-subtitle>
        </ion-card-header>

      <ion-item>
        <ion-label>Hair Color</ion-label>
        <ion-select value="brown" okText="Okay" cancelText="Dismiss">
          <ion-select-option value="brown">Brown</ion-select-option>
          <ion-select-option value="blonde">Blonde</ion-select-option>
          <ion-select-option value="black">Black</ion-select-option>
          <ion-select-option value="red">Red</ion-select-option>
        </ion-select>
      </ion-item>
    </ion-card>

  </ion-content>
</ion-app>
```

**Expected Behavior**
Above examples in edge should look the same or close to how they appear in chrome.

**Comment by paulstelzer** [comment]
Thanks for your issue! I think the most issues has been fixed since then, coul you please check in `beta.17`?

**Comment by ajmchambers** [comment]
Closing this, see https://github.com/ionic-team/ionic/issues/16189#issuecomment-445205845
