### ISSUE TITLE
interface IonSlides.slideNext parameters should optional

### ISSUE THREAD

**Issue by aavelyn** [ionic-team/ionic#15622]
@ionic/angular": "4.0.0-beta.11"

'slideNext': (speed: number, runCallbacks: boolean) => Promise<void>;

should be like slidePrev?

 'slidePrev': (speed?: number | undefined, runCallbacks?: boolean | undefined) => Promise<void>;

**Comment by mhartington** [comment]
Fixed in master. https://github.com/ionic-team/ionic/commit/681981fc8997d6b72e6e878cff099fc71da6977a
