### ISSUE TITLE
Ionic HTTP Request Ignoring HTTPS

### ISSUE THREAD

**Issue by ashutoshpw** [ionic-team/ionic#15634]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.2.0
    Cordova Platforms  : android 7.0.0 browser 5.0.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v10.1.0
    npm  : 5.6.0
    OS   : macOS High Sierra

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Describe the Bug**
I am using https://apiserver.com for my API serving. It is working fine until I am using *ionic serve* or building the application for android or iOS.

Problem is when I am serving the **www** files directly from a normal server (like nginx server), that https://apiserver.com becomes http://apiserver.com and browser given the following error 

`Mixed Content: The page at 'myurl' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://apiserver.com'. This request has been blocked; the content must be served over HTTPS.`

**Steps to Reproduce**
1. Use this kind of snipped anywhere : this.http.get('https://apiserver.com')
2. Run `ionic build`
3. Server **www** folder in root folder via nginx or apache
4. Open Console and you will get mix-content error

**Related Links**
[Stackoverflow Question](https://stackoverflow.com/questions/49987444/angular-ionic-http-request-ignoring-https)

**Expected Behavior**
The application should send request to https://apiserver.com instead of http://apiserver.com

**Additional Context**

**Comment by mhartington** [comment]
In the latest CLI release, we have a beta feature that you can test 

```
ionic ssl generate
```

Which will create a ssl cert and key for you.

Then you can serve over https with 

```
$ ionic serve -- --ssl --ssl-key .ionic/ssl/key.pem --ssl-cert .ionic/ssl/cert.pem
```


You'll need to open the browser and direct it to `https://localhost:8100/<start url>` to add an exception for the self-signed certificate, but it will be https
