### ISSUE TITLE
ion-spinner DO NOT rotate around it's centre. 

### ISSUE THREAD

**Issue by netsesame2** [ionic-team/ionic#15630]
ion-spinner type of 'bubbles' and 'crescent',  presenting in a loading component doesn't work correctly, normally it should rotate by it's center, however, it seems rotate around one of it's corner point. 

Test it on Webview of Chrome 55.0.2883.91 on Android 6.0.1 Phone.
Works well on my MAC and Windows browser.

Don't know how to take the animating picture. Hope to tell it clear.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/Cellar/nvm/0.26.1/versions/node/v8.11.3/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.8.2
   @angular-devkit/schematics : 0.8.2
   @angular/cli               : 6.2.2
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1


```

**Comment by hghammoud** [comment]
On iOS it looks off.

![image](https://user-images.githubusercontent.com/8034427/46150548-18513880-c26d-11e8-95a7-c8a040797219.png)

**Comment by wenisy** [comment]
Have you solved this issue? I have the same problem on Android device.

@hghammoud

**Comment by hghammoud** [comment]
Nope we just dropped ios 10 support as we only supporting the last 2 version of ios. :( there are alot of other issues with 10 and flexbox support.
