### ISSUE TITLE
[4.0.0-beta.11] Life cycle destroy does not run

### ISSUE THREAD

**Issue by 777wills** [ionic-team/ionic#15633]
# Bug Report

**Ionic Info**
![image](https://user-images.githubusercontent.com/36114477/45642472-e62a2480-ba7d-11e8-81fb-2fa34ce80743.png)

**Describe the Bug**
When I navigate from the home to user route, the life cycle destroy of the home is not executed

**Steps to Reproduce**
1. Go to '/home'
2. Click on 'GO USERS'
3. The ngOndestroy of the home is not executed

**Related Code**
[https://github.com/777wills/destroy-ionicV4](url)

**Expected Behavior**
When leaving the home component you should run ngOndestroy and show in console 'destroy'

![image](https://user-images.githubusercontent.com/36114477/45642636-63559980-ba7e-11e8-98ed-3d1c75c6568f.png)

**Comment by mhartington** [comment]
This is expected, as `ion-router-outlet` has the same "stack" functionality we had in V3.
Meaning that as you navigate forward in your app, back views are not destroyed. 
Views are only destroyed when you "go back"

So....

View 1 => View 2 => View 3


Views 1 and 2 will not be destroyed.

View 1 <= View 2 <= View 3

But as you navigate back from V3 and use the stack, View 3 will call ngOnDestroy, and when you go from 2 to 1, OnDestroy will also be called.
