### ISSUE TITLE
NPM still shows ionic beta 7 not beta 11 which is ionic@4.1.2 please update

### ISSUE THREAD

**Issue by MrBokeh** [ionic-team/ionic#15637]
NPM still shows ionic beta 7 not beta 11 which is ionic@4.1.2 please update

**Comment by mhartington** [comment]
Npm is showing beta.11 for me 

https://www.npmjs.com/package/@ionic/core
https://www.npmjs.com/package/@ionic/angular

As for `ionic@4.1.2`, that is the Ionic CLI.

https://www.npmjs.com/package/ionic
