### ISSUE TITLE
[Ionic-v4] Image Resizer Not Work on Android Device

### ISSUE THREAD

**Issue by AhmadAlrossan123** [ionic-team/ionic#15645]
When install image resizer:
$ ionic cordova plugin add info.protonet.imageresizer
$ npm install --save @ionic-native/image-resizer

Not Work Run on Android Device

C:\Users\AHMAD\Desktop\myApp\platforms\android\app\src\main\java\info\protonet\imageresizer\ImageResizer.java:15: error: package org.apache.cordova.camera does not exist
import org.apache.cordova.camera.FileHelper;
                                ^
C:\Users\AHMAD\Desktop\myApp\platforms\android\app\src\main\java\info\protonet\imageresizer\ImageResizer.java:92: error: cannot find symbol
            BitmapFactory.decodeStream(FileHelper.getInputStreamFromUriString(uriString, cordova), null, options);
                                       ^
  symbol:   variable FileHelper
  location: class ImageResizer
C:\Users\AHMAD\Desktop\myApp\platforms\android\app\src\main\java\info\protonet\imageresizer\ImageResizer.java:99: error: cannot find symbol
            Bitmap unscaledBitmap = BitmapFactory.decodeStream(FileHelper.getInputStreamFromUriString(uriString, cordova), null, options);
                                                               ^
  symbol:   variable FileHelper
  location: class ImageResizer
3 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
27 actionable tasks: 1 executed, 26 up-to-date
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
(node:17236) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
C:\Users\AHMAD\Desktop\myApp\platforms\android\app\src\main\java\info\protonet\imageresizer\ImageResizer.java:15: error: package org.apache.cordova.camera does not exist
import org.apache.cordova.camera.FileHelper;
                                ^
C:\Users\AHMAD\Desktop\myApp\platforms\android\app\src\main\java\info\protonet\imageresizer\ImageResizer.java:92: error: cannot find symbol
            BitmapFactory.decodeStream(FileHelper.getInputStreamFromUriString(uriString, cordova), null, options);
                                       ^
  symbol:   variable FileHelper
  location: class ImageResizer
C:\Users\AHMAD\Desktop\myApp\platforms\android\app\src\main\java\info\protonet\imageresizer\ImageResizer.java:99: error: cannot find symbol
            Bitmap unscaledBitmap = BitmapFactory.decodeStream(FileHelper.getInputStreamFromUriString(uriString, cordova), null, options);
                                                               ^
  symbol:   variable FileHelper
  location: class ImageResizer
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
    at ChildProcess.whenDone (C:\Users\AHMAD\Desktop\myApp\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:17236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17236) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mhartington** [comment]
Hi there! This issue does not appear to be an issue with the framework itself, so it will be closes. Please review your issue and open a new ticket on the image resizer plugin repository, or feel free to post a question on the [Ionic Forum](http://forum.ionicframework.com). Thanks!
