### ISSUE TITLE
Ability to style ion-items' detail arrow/icon and lines

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic#15648]
**Describe the Feature Request**
The detail arrow and lines are no easily configurable. My primary issue is if the ion-item is medium is color, those elements 'vanish'.

**Describe Preferred Solution**
The ability to set the color of these items to provide enough contrast to be visible

**Comment by camwiegert** [comment]
@chrisgriffith I just merged some documentation of item's custom properties. I think you'll be interested in `--detail-icon-color` and `--border-color` :smile: Those docs will get pulled into the official docs in the next release.

**Comment by chrisgriffith** [comment]
I saw. :)

Cg
