### ISSUE TITLE
[Ionic 4] Toast shows behide the modal page

### ISSUE THREAD

**Issue by Elvincth** [ionic-team/ionic#15641]
Toast shows behide the modal page.
```
async function presentToastWithOptions() {
  const toastController = document.querySelector('ion-toast-controller');
  await toastController.componentOnReady();

  const toast = await toastController.create({
    message: 'Click to Close',
    showCloseButton: true,
    position: 'bottom',
    closeButtonText: 'Done'
  });
  return await toast.present();
}
```
![ezgif com-resize](https://user-images.githubusercontent.com/6602723/45671993-8e60eb80-bb59-11e8-80d9-08520f8b91a1.gif)

**Comment by Elvincth** [comment]
Same method tested with alert also no problems found.

**Comment by mhartington** [comment]
Do you have a sample test project for this? I did a quick test and was unable to replicate this


![toast-modal](https://user-images.githubusercontent.com/2835826/45698849-fbaf5500-bb36-11e8-807d-41c6d2ec0ce2.gif)

**Comment by harrylyh** [comment]
![gitoperate2](https://user-images.githubusercontent.com/26681969/45725980-f3672080-bbef-11e8-8b00-2fb827ebf67b.gif)

when I update to newest beta version,it is normal

**Comment by Elvincth** [comment]
Update to beta 4.0.0-beta.11 the bug should be fixed.
@mhartington  @harrylyh 
![image](https://user-images.githubusercontent.com/6602723/45757452-fbf24200-bc55-11e8-9797-1d62a80c3c80.png)

A codepen example:
https://codepen.io/elvincth/pen/RYEVJp
