### ISSUE TITLE
ionic 4.0.0-beta.11: <ion-reorder> not working

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/ionic#15652]
# Bug Report

**Ionic Info**

```

ionic 4.0.0-beta.11

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

System:

    Node : v8.9.1
    npm  : 5.7.1
    OS   : macOS High Sierra

Misc:

    backend : pro
```

**Describe the Bug**
When using the `<ion-reorder-group>` component the re-order icons are not displayed and the user is not able to drag and drop the items.

I am using code from the component usage documentation:

```tsx
<ion-content>
  <ion-list>
    <ion-reorder-group>
      <ion-item>
        <ion-label>
          Item 1
        </ion-label>
        <ion-reorder slot="end"></ion-reorder>
      </ion-item>
      <ion-item>
        <ion-label>
          Item 2
        </ion-label>
        <ion-reorder slot="end"></ion-reorder>
      </ion-item>
    </ion-reorder-group>
  </ion-list>
</ion-content>
```

When the list is displayed, the re-order icons are not displayed - only the label is displayed.  They do exist in the DOM but appear to be hidden.

The Chrome inspector shows:

```
<ion-item class="in-list item hydrated item-label">
  <ion-label class="sc-ion-label-ios-h sc-ion-label-ios-s hydrated">Item 1</ion-label>
  <ion-reorder slot="end" class="hydrated"></ion-reorder>
</ion-item>
```

Looking at the `<ion-reorder>` element is has `display: none`.  Maybe it is related to showing on hydration complete?

If I change the `<ion-reorder>` component to an`<ion-icon>` component then the icon is displayed.

```tsx
<ion-content>
  <ion-list>
    <ion-reorder-group>
      <ion-item>
        <ion-label>
          Item 1
        </ion-label>
        <ion-icon name="calendar" slot="end"></ion-icon>
      </ion-item>
      <ion-item>
        <ion-label>
          Item 2
        </ion-label>
        <ion-icon name="calendar" slot="end"></ion-icon>
      </ion-item>
    </ion-reorder-group>
  </ion-list>
</ion-content>
```

I am also not able to get `ionItemReorder` events but that is probably related to not being able to see the draggable elements.

**Comment by TrayserCassa** [comment]
You need to set disable="false" ..
See the Doku:
https://beta.ionicframework.com/docs/api/reorder-group

But the event ionItemReorder ist not working:
Error in the console = reorder node not found

**Comment by cjorasch** [comment]
Thanks.  I completely missed the default value of `true` since the other components default `disabled` to `false`.  May want to include that in the usage examples (https://github.com/ionic-team/ionic/blob/master/core/src/components/reorder/usage/javascript.md)

After making that change it now shows the reorder icons, allows drag and drop, and generates the event.

I did run into the `reorderNode not found` error sometimes but am having trouble reproducing it.

**Comment by mhartington** [comment]
Hi! Since the original issue has been address, I'm going to close this. @cjorasch if you do happen to isolate the `renderNode not found` issue, can you please open a new issue? Thanks
