### ISSUE TITLE
ion-img onerror

### ISSUE THREAD

**Issue by pickfire** [ionic-team/ionic#15659]
# Feature Request

**Ionic Info**

```
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)  : 4.1.1 (/usr/local/share/.config/yarn/global/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : no whitelisted plugins (12 plugins total)

System:

   Android SDK Tools : 26.1.1 (/opt/android-sdk)
   NodeJS            : v10.10.0 (/usr/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.18



   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 4.1.1 → 4.1.2    │
   │    Run npm i -g ionic to update     │
   │                                     │
   ╰─────────────────────────────────────╯

```

**Describe the Feature Request**

Add support for ion-img to handle error during lazy loading. Currently only `img` supports `onerror` but `ion-img` does not.

`onerror` is useful when we want to fallback to a default image. Such as:
```html
<ion-img [src]="image.src" onerror="this.src='assets/img/profile.svg'"></ion-img>
```

**Describe Preferred Solution**

`onerror` support.

**Describe Alternatives**

Use `img` but there is no lazy loading.

**Related Code**

-

**Additional Context**

-

**Comment by RHinderiks** [comment]
Could you use the angular way (error)="yourFunction()"

**Comment by pickfire** [comment]
> Could you use the angular way (error)="yourFunction()"

Where is that documented? Is it in angular?

**Comment by RHinderiks** [comment]
Yeah its angular. I cant seem to find documentation but i've used it my self recently.

Example html: 
`<img class="avatar" [src]="src" (error)="fallback()" />`

Example ts:
`fallback(){
    if(this.altSrc){
      this.src = this.altSrc;
    }
  }`

**Comment by pickfire** [comment]
@RHinderiks No, `<ion-img [src]="src" (error)="this.src=altSrc"></ion-img>` does not work.

**Comment by RHinderiks** [comment]
I'm using the code myself so i'm quite sure it works. Do you have a altSrc variable in your component.ts ?

**Comment by Hanzofm** [comment]
Any news about this?

Angular way `(error)` not works for me.
