### ISSUE TITLE
[4.0.0-beta.11] Object.values is not a function

### ISSUE THREAD

**Issue by xvs32x** [ionic-team/ionic#15668]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**

in android <7,1 my app not working because
./node_modules/@ionic/core/dist/esm/es5/ionic.core.js generate errors with Object,values 

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
ERROR Error: Uncaught (in promise): TypeError: Object.values is not a function
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\User\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.4, (and 3 other plugins)

System:

   NodeJS : v8.11.2 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10



```

**Comment by mhartington** [comment]
Can confirm, seeing this as well in a starter project on a Pixel emulator running Android 7.0.


![screen shot 2018-09-19 at 11 45 00 am](https://user-images.githubusercontent.com/2835826/45764783-793f9780-bc01-11e8-8cbe-3e440c1de598.png)

**Comment by Riyaz0001** [comment]
same problem here in my real android 6.0 device

**Comment by ratt** [comment]
Same issue with actual Android 6.0 device

ERROR Error: Uncaught (in promise): TypeError: Object.values is not a function(…)defaultErrorLogger @ vendor.js:34778push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ vendor.js:34824ngZone.onError.subscribe.next @ vendor.js:37416schedulerFn @ vendor.js:36656push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ vendor.js:85370push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ vendor.js:85308push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ vendor.js:85252push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ vendor.js:85229push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ vendor.js:84995push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ vendor.js:36640(anonymous function) @ vendor.js:36947push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.js:2710push../node_modules/zone.js/dist/zone.js.Zone.run @ polyfills.js:2460push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ vendor.js:36884zone._inner.zone._inner.fork.onHandleError @ vendor.js:36947push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError @ polyfills.js:2714push../node_modules/zone.js/dist/zone.js.Zone.runGuarded @ polyfills.js:2476_loop_1 @ polyfills.js:2999api.microtaskDrainDone @ polyfills.js:3008drainMicroTaskQueue @ polyfills.js:2924
vendor.js:34778 ERROR Error: Uncaught (in promise): TypeError: containerEl.commit is not a function(…)

Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/Users/jarratt/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : not installed
   @ionic/schematics-angular  : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 8 other plugins)

System:

   Android SDK Tools : 26.1.1 (/usr/local/share/android-sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v10.6.0 (/usr/local/Cellar/node/10.6.0/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.0 Build version 10A25

**Comment by deemi47** [comment]
same issue, any updates?

**Comment by paulstelzer** [comment]
Thanks for the issue! Are you still seeing this problem in latest, `4.0.0-beta.17`?
