### ISSUE TITLE
Sticky iOS :hover states on ion-button

### ISSUE THREAD

**Issue by robmacecs** [ionic-team/ionic#15667]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

System:

   NodeJS : v10.9.0 (/usr/local/Cellar/node/10.9.0/bin/node)
   npm    : 6.4.0
   OS     : macOS High Sierra
```

**Describe the Bug**
When clicking on an ion-button on the device/simulator, (or in the browser with Mobile emulation on) will trigger the :hover state until clicking elsewhere in the window. 
Meaning that the button remains set to `opacity: .6;`

**Steps to Reproduce**
1. Place an ion-button on a page
2. View on browser mobile-emulation, simulator, or on device
2. Click it

**Related Code**
https://stackblitz.com/edit/angular-ionic4-test-vgwruu

**Expected Behavior**
Button on device returns to `opacity: 1;` after clicking. More specifically the `--opacity` variable should

**Additional Context**
Possibly similar to https://github.com/ionic-team/ionic/issues/14934
It's probably a good idea to disable hover states on the device? But I opened a new issue as it seems this is a more specific scope of task

**Comment by manucorporat** [comment]
Fixed by @juanmiguelbesada !
