### ISSUE TITLE
[DOC][Ionic 4.0.0-beta.7] Popover's content does not appear when enclosed within `ion-content`

### ISSUE THREAD

**Issue by jadurani** [ionic-team/ionic#15677]
**Ionic version:**
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request

**Current behavior:**
Popover's content does not appear: 
![ionic-popover-issue](https://user-images.githubusercontent.com/11599005/45770779-ea209700-bc75-11e8-9b6d-0127a6a8a4a5.gif)

**Expected behavior:**
Popover should appear

**Steps to reproduce:**
1. Go to https://beta.ionicframework.com/docs/api/popover/
2. Click on the buttons as illustrated in the above gif.

**Related code:**
https://github.com/ionic-team/ionic/blob/master/core/src/components/popover/test/preview/index.html
```
    class ProfilePage extends HTMLElement {
      constructor() {
        super();
      }
      connectedCallback() {
        this.innerHTML = `
          <ion-content> <!-- remove this line -->
            <ion-list>
              <ion-list-header>Ionic</ion-list-header>
              <ion-item><ion-label>Item 0</ion-label></ion-item>
              <ion-item><ion-label>Item 1</ion-label></ion-item>
              <ion-item><ion-label>Item 2</ion-label></ion-item>
              <ion-item><ion-label>Item 3</ion-label></ion-item>
            </ion-list>
          </ion-content> <!-- remove this line -->
        `;
      }
    }
```

**Other information:**

* At https://beta.ionicframework.com/docs/api/popover/ :
![ionic-popover-issue-solution](https://user-images.githubusercontent.com/11599005/45771104-cd389380-bc76-11e8-9370-c856c0b7503a.gif)

* At https://beta.ionicframework.com/docs/components#popover :
![ionic-popover-issue-solution2](https://user-images.githubusercontent.com/11599005/45771105-cd389380-bc76-11e8-9510-36f6dfba8597.gif)
(works perfectly without `ion-content`)

* Same issue as https://github.com/ionic-team/ionic/issues/14911 but was left unsolved.

**Ionic info:**
(unapplicable)

**Comment by bleuscyther** [comment]
Also if you force it to display (apply inline height ) the style i the component is not applied to the elements like ion-list...

**Comment by manucorporat** [comment]
@jadurani can you test beta.11?

**Comment by jadurani** [comment]
@manucorporat works fine now, even when inside `ion-content` :) thanks!
