### ISSUE TITLE
ion-select ionChange event has no data - Ionic 4 beta 11

### ISSUE THREAD

**Issue by russcarver** [ionic-team/ionic#15679]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.2.3
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/Library/Android/sdk)
   ios-deploy        : 2.0.0
   ios-sim           : 7.0.0
   NodeJS            : v8.11.4 (/Users/.nvm/versions/node/v8.11.4/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
The `ionChange` event of an `ion-select` has no data.

**Steps to Reproduce**
1. Create an `ion-select` and wire up the the `ionChange` output event.
2. Print the `event` and `event.value` to the console
3. `event` shows `{"isTrusted":false}`
4. `event.value` is undefined.

**Related Code**
```
    <ion-select class="ati-reset__content_env-item_select" value="{{envUrl}}" ok-text="Okay" cancel-text="Dismiss"
      (ionChange)="changeEnvironment($event)">
      <ion-select-option value="https://myurl">Url1</ion-select-option>
      <ion-select-option value="https://myurl2">Url2</ion-select-option>
    </ion-select>

  public changeEnvironment(event: SelectInputChangeEvent): void {
    console.log(JSON.stringify(event));
    console.log(JSON.stringify(event.value));
  }
```

**Expected Behavior**
The `event` object should be populated and `event.value` should contain the corresponding `value` of the chosen `ion-select-option`.

**Additional Context**
The code-base of beta 11 shows a value being emitted. Not sure where it is getting lost.  https://github.com/ionic-team/ionic/blob/v4.0.0-beta.11/core/src/components/select/select.tsx#L170

**Comment by godenji** [comment]
I believe the value is under: `event.detail.value`

**Comment by russcarver** [comment]
According to the code I linked to, it's `event.value`. But either way, you can see above that event is only `{"isTrusted":false}`. So trying to reference anything other than `isTrusted` will be `undefined`.

**Comment by paulstelzer** [comment]
Thanks for your issue! It seems that you are right:

Current event value:
![chrome_2018-12-07_09-45-47](https://user-images.githubusercontent.com/20501666/49637164-e72b7c00-fa04-11e8-9c23-769d792b6ca3.jpg)

But it should "SelectInputChangeEvent" and this contains only a value, so it must be a bug!

**Comment by manucorporat** [comment]
Fixed https://github.com/ionic-team/ionic/commit/3d656ac3127278a7c9d3d4808c2806fde71e5d2b
