### ISSUE TITLE
[Ionic 4.0.0, beta 11]  nested ion-content does not render!

### ISSUE THREAD

**Issue by JoeBoxr** [ionic-team/ionic#15680]
# Bug Report

**Ionic Info**
Ionic Framework : @ionic/angular 4.0.0-beta.11
@angular-devkit/core : 0.7.2
@angular-devkit/schematics : 0.7.2
@angular/cli : 6.0.8
@ionic/ng-toolkit : 1.0.0
@ionic/schematics-angular : 1.0.1

**Describe the Bug**
If you have a ion-content within an ion-content, the nested ion-content does not render.  For example, ion-content can contain a custom component that has its own ion-content.  The custom component will not render correctly.

**Steps to Reproduce**
1. Create a tabs project from the iconic v4 templates
2. On the Home tab replace 

`<ion-content padding>
    The world is your oyster.
    <p>If you get lost, the <a target="_blank" rel="noopener" href="https://ionicframework.com/docs">docs</a> will be
      your guide.</p>
</ion-content>`

WITH

`<ion-content padding>
  <ion-content>
    The world is your oyster.
    <p>If you get lost, the <a target="_blank" rel="noopener" href="https://ionicframework.com/docs">docs</a> will be
      your guide.</p>
  </ion-content>
</ion-content>`

**Expected Behavior**
All nested content rendered correctly.

**Additional Context**
This worked with earlier builds of the beta.

**Comment by brandyscarney** [comment]
Possibly related to https://github.com/ionic-team/ionic/issues/15677

cc @manucorporat
