### ISSUE TITLE
Network Error : PolyFills

### ISSUE THREAD

**Issue by amaisonneuve** [ionic-team/ionic#15683]
![network error ios](https://user-images.githubusercontent.com/5480903/45793766-9efc8900-bc61-11e8-989d-439c3947626e.png)

# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/Users/alain/.npm-packages/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-webview 1.1.1, (and 31 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.1.2
   NodeJS     : v9.6.1 (/usr/local/Cellar/node/9.4.0/bin/node)
   npm        : 6.0.1
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
When i run ionic cordova run ios -lc

The emulator launches, and when the app launches i will get the following error:

**Steps to Reproduce**
1. run ionic cordova run ios -lc
2. app launches in emulator
3. wait

**Expected Behavior**
App should launch and well just sit there until user input

There was a bug open previously but it was locked 19 days ago..

**Comment by gersonmontenegro** [comment]
I have exactly the same error, and that only happens when I load AngularFirestore object, even in a new and clean Ionic project.

My info:

```
Ionic:

   ionic (Ionic CLI)  : 4.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 2.0.0
   NodeJS            : v8.11.2 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Sierra
   Xcode             : Xcode 9.2 Build version 9C40b

Environment:

   ANDROID_HOME : /Users/gersonmontenegro/Library/Android/sdk/
```

Any idea?
