### ISSUE TITLE
ionic cordova run android - Execution failed for task ':app:mergeDebugResources'.

### ISSUE THREAD

**Issue by kdinesh6767** [ionic-team/ionic#15685]
# Bug Report

**Ionic Info**
Ionic:

   ionic (Ionic CLI)  : 4.1.1 (C:\Users\kdinesh\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.1, (and 10 other plugins)

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 7

**Describe the Bug**
I am trying to run the app in android simulator using the CLI command '**ionic cordova run android**', but it always getting build failed.  

**Error Msg**
> ionic-app-scripts build --target cordova --platform android
[13:06:58]  ionic-app-scripts 3.2.0
[13:06:58]  build dev started ...
[13:06:58]  clean started ...
[13:06:58]  clean finished in 8 ms
[13:06:58]  copy started ...
[13:06:58]  deeplinks started ...
[13:06:58]  deeplinks finished in 118 ms
[13:06:58]  transpile started ...
[13:07:04]  transpile finished in 5.35 s
[13:07:04]  preprocess started ...
[13:07:04]  preprocess finished in less than 1 ms
[13:07:04]  webpack started ...
[13:07:04]  copy finished in 5.72 s
[13:07:10]  webpack finished in 6.21 s
[13:07:10]  sass started ...
[13:07:11]  sass finished in 1.58 s
[13:07:11]  postprocess started ...
[13:07:11]  postprocess finished in less than 1 ms
[13:07:11]  lint started ...
[13:07:11]  build dev finished in 13.47 s
[13:07:16]  lint finished in 4.33 s
> cordova run android
Android Studio project detected
Discovered plugin "cordova-plugin-ionic" in config.xml. Adding it to the project
Installing "cordova-plugin-ionic" for android
Plugin dependency "cordova-plugin-splashscreen@5.0.2" already fetched, using that version.
Dependent plugin "cordova-plugin-splashscreen" already installed on android.
Failed to install 'cordova-plugin-ionic': CordovaError: Version of installed plugin: "cordova-plugin-ionic-webview@2.1.1" does not satisfy dependency plugin requirement "cordova-plugin-ionic-webview@^2.1.4". Try --force to use installed plugin as dependency.
    at C:\Users\kdinesh\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:557:37
    at _fulfilled (C:\Users\kdinesh\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\kdinesh\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\kdinesh\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:749:13)
    at C:\Users\kdinesh\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:509:49
    at flush (C:\Users\kdinesh\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Failed to restore plugin "cordova-plugin-ionic" from config.xml. You might need to try adding it again. Error: Version of installed plugin: "cordova-plugin-ionic-webview@2.1.1" does not satisfy dependency plugin requirement "cordova-plugin-ionic-webview@^2.1.4". Try --force to use installed plugin as dependency.
Discovered plugin "cordova-plugin-dreamover-uid" in config.xml. Adding it to the project
Failed to restore plugin "cordova-plugin-dreamover-uid" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin cordova-plugin-dreamover-uid@~1.3.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 Not Found: cordova-plugin-dreamover-uid@~1.3.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kdinesh\AppData\Roaming\npm-cache\_logs\2018-09-20T07_37_49_895Z-debug.log
ANDROID_HOME=C:\Users\kdinesh\AppData\Local\Android\Sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_73
studio
Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_5qps5mbmc8rayapqg0mc5rmpo.run(D:\MHE\Society app\Code base\societyapp\platforms\android\app\build.gradle:145)
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:prepareLintJar UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:platformAttrExtractor UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:javaPreCompileDebug UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
:CordovaLib:processDebugJavaRes NO-SOURCE
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugAidl UP-TO-DATE
:CordovaLib:packageDebugRenderscript NO-SOURCE
:app:compileDebugRenderscript UP-TO-DATE
:app:checkDebugManifest UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:prepareLintJar UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources
Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
values_values.arsc.flat: error: failed to open.

:app:mergeDebugResources FAILED
21 actionable tasks: 1 executed, 20 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
(node:1056) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
values_values.arsc.flat: error: failed to open.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
    at ChildProcess.whenDone (D:\MHE\Society app\Code base\societyapp\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:1056) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1056) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[ERROR] An error occurred while running subprocess cordova.

        cordova run android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

**Comment by paulstelzer** [comment]
See the errorlog:

`Failed to install 'cordova-plugin-ionic': CordovaError: Version of installed plugin: "cordova-plugin-ionic-webview@2.1.1" does not satisfy dependency plugin requirement "cordova-plugin-ionic-webview@^2.1.4". Try --force to use installed plugin as dependency.`

if you update the `cordova-plugin-ionic-webview` to 2.1.4 it should work (please remember to update it in package.json + npm install // update it in config.xml // remove plugins folder // remove platforms folder and then try again)

**Comment by redwolf2** [comment]
It's a good advice to do
```
ionic cordova platform rm android
ionic cordova platform add android@7.1.1
```
after every plugin installation or update.

**Comment by AndrewProteo** [comment]
i have failures on the ionic pro packaging system it is failing on cordova-plugin-dreamover-uid@~1.3.0, error 404, it seems it cant find this module, ionic v4. and i cant specify what version to run on the build console.
