### ISSUE TITLE
Ionic 4 iOS12: No pasting into input fields possible

### ISSUE THREAD

**Issue by carstenbaumhoegger** [ionic-team/ionic#15689]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.2.3
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 2.0.0, (and 11 other plugins)

System:

   NodeJS : v10.10.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS High Sierra
   Xcode  : Xcode 10.0 Build version 10A255

```

**Describe the Bug**
When I select some text information on iOS (e.g. username), copy this information to the clipboard and then change into my Ionic app, there's no possibility to paste the information back into the input field. Nothing happens when I do a long click into the input field.
Pasting into `ion-searchbar` works, though.

When running on Android, everything works as expected.

**Steps to Reproduce**
1. Open Ionic 4 app with inputs on iPhone with iOS12
2. Try to paste something from the clipboard into the inputs

**Expected Behavior**
Pasting information works with iOS and Android

**Comment by carstenbaumhoegger** [comment]
I can still reproduce this error with Beta 12.

Does anyone have an idea, why this is happening?

**Comment by tayambamwanza** [comment]
@carstenbaumhoegger I found that if i press and hold the clipboard wont popup but when I press and hold, then drag in any direction it pops up :thinking: . 

I bumped into this issue because one of my clients uses a password generator, so he wanted to paste the result into the password field. Spent the whole day trying to find a workaround but to no avail, hopefully this gets fixed soon or some provision is made

**Comment by carstenbaumhoegger** [comment]
@tayambamwanza thanks for the tip! This workaround does the job!

I also bumped into this because one client that was using a password manager was not able to paste anything into the password field.

**Comment by carstenbaumhoegger** [comment]
This seems to be resolved with Beta 16.
It works for me with the following `ionic info`:

```
Ionic:

   ionic (Ionic CLI)             : 4.4.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 2.0.0, (and 11 other plugins)

System:

   NodeJS : v10.13.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS
   Xcode  : Xcode 10.1 Build version 10B61
```

**Comment by tayambamwanza** [comment]
> This seems to be resolved with Beta 16.
> It works for me with the following `ionic info`:
> 
> ```
> Ionic:
> 
>    ionic (Ionic CLI)             : 4.4.0 (/usr/local/lib/node_modules/ionic)
>    Ionic Framework               : @ionic/angular 4.0.0-beta.16
>    @angular-devkit/build-angular : 0.10.6
>    @angular-devkit/schematics    : 7.0.6
>    @angular/cli                  : 7.0.6
>    @ionic/angular-toolkit        : not installed
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
>    Cordova Platforms     : android 7.1.2, ios 4.5.5
>    Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 2.0.0, (and 11 other plugins)
> 
> System:
> 
>    NodeJS : v10.13.0 (/usr/local/bin/node)
>    npm    : 6.4.1
>    OS     : macOS
>    Xcode  : Xcode 10.1 Build version 10B61
> ```

Did you just update ionic? I'm on beta 16 right now although I can't remember if I tested it when I was on 15 or not.

**Comment by carstenbaumhoegger** [comment]
Yes, I updated to Beta 16 and Angular 7 etc. today and now I can't reproduce the bug anymore. Ca you test this with Beta 16?

**Comment by tayambamwanza** [comment]
@carstenbaumhoegger Yes I can confirm, it's working now. beta 16, and angular 7.1.0

**Comment by carstenbaumhoegger** [comment]
Great, I'll close this issue as it seems to be fixed with Beta 16.
Thanks for the contribution!
