### ISSUE TITLE
[4.0.0-beta.11] ion-select placeholder not working

### ISSUE THREAD

**Issue by jordanpurinton** [ionic-team/ionic#15694]
# Bug Report

**Ionic Info**
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.2.3
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Capacitor:

   capacitor (Capacitor CLI) : not installed
   @capacitor/core           : not installed

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 10 other plugins)

System:

   Android SDK Tools : 26.1.1 (path/Android/Sdk)
   NodeJS            : v8.10.0 (/usr/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.15

**Describe the Bug**
ion-select placeholders don't show up anymore since I've upgraded to the latest version of `@ionic/angular`.

**Steps to Reproduce**
Create an `ion-select` component, try to attach a placeholder.

**Related **
```
<ion-select formControlName="documentType" placeholder="Select Type" required>
                <ion-select-option *ngFor="let c of documentCategoriesStrings">{{c}}</ion-select-option>            
</ion-select>
```

**Expected Behavior**
For the placeholder to appear.

**Comment by brandyscarney** [comment]
Thank you for the issue! I believe this may be fixed by https://github.com/ionic-team/ionic/commit/29862e8259e375f159d552fc5951110ec371b3c7 but I need to test it out. If so, this would be in the `4.0.0-beta.12` release. 🙂

**Comment by brandyscarney** [comment]
Could you try this out in `4.0.0-beta.12` please? I can see it working in my example app. Thanks!

**Comment by jordanpurinton** [comment]
Looks great! Thanks :tada:
