### ISSUE TITLE
v4: ion-radio-group

### ISSUE THREAD

**Issue by wanderarce** [ionic-team/ionic#15693]
# Bug Report

**Ionic Info**
Version: 4.1.2
SO: Windows
Browser: Chrome

```
Template parse errors:
'ion-radio-group' is not a known element:
1. If 'ion-radio-group' is an Angular component, then verify that it is part of this module.
2. If 'ion-radio-group' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
<ion-content padding>
	<ion-list>
  		[ERROR ->]<ion-radio-group>
	    <ion-list-header>
	      <ion-label>Name</ion-label>
"): ng:///AppModule/ConfigPage.html@17:4
```

**Describe the Bug**

**Steps to Reproduce**
1. ionic start projectName sidemenu 
2. add ion-radio-group example: https://beta.ionicframework.com/docs/api/radio#usage

**Related Code**

<ion-header>

  <ion-navbar>
    <ion-title>Configurações</ion-title>
  </ion-navbar>

</ion-header>

<ion-content padding>
	<ion-list>
  		<ion-radio-group>
	    <ion-list-header>
	      <ion-label>Name</ion-label>
	    </ion-list-header>

	    <ion-item>
	      <ion-label>Biff</ion-label>
	      <ion-radio slot="start" value="biff" checked></ion-radio>
	    </ion-item>

	    <ion-item>
	      <ion-label>Griff</ion-label>
	      <ion-radio slot="start" value="griff"></ion-radio>
	    </ion-item>

	    <ion-item>
	      <ion-label>Buford</ion-label>
	      <ion-radio slot="start" value="buford"></ion-radio>
	    </ion-item>
	  </ion-radio-group>
	</ion-list>
</ion-content>
ps://stackblitz.com), or [GitHub](https://github.com).

**Comment by vlapo** [comment]
Hi @wanderarce,

`ionic start projectName sidemenu` command created ionic v3 app and you are using v4 `ion-radio-group` component. 

If you want to create ionic v4 app add `--type=angular` flag - `ionic start projectName sidemenu --type=angular`
