### ISSUE TITLE
angular lifecycles & ionic

### ISSUE THREAD

**Issue by RHinderiks** [ionic-team/ionic#15708]
In ionic 3 we used ngOnInit to get the height of the element and set a max height and apply some css to make it fade out at the bottom etc.

Now with ionic 4 this same logic does not seem to work and suddenly needs a timeout of x miliseconds which is variable per device etc so not an option.

I'd assume it would be a change in angular but could also maybe be a change in the way ionic renders content now ? 

Some of this content is off screen and maybe thats why they return a height of 0 because their not fully rendered yet or something.

If any one has any idea about this or another way to determine the height of an element which can vary based on the content loaded in to it  (loaded from a angular service not a server call)

**Comment by paulstelzer** [comment]
Please see #16152
