### ISSUE TITLE
Virtual Scroll: The items aren't rendered correctly

### ISSUE THREAD

**Issue by Losnen** [ionic-team/ionic#15706]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)  : 4.0.2
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.0, ios 4.5.5

System:

   NodeJS : v8.11.4 (/usr/local/bin/node)
   npm    : 6.4.0
   OS     : macOS High Sierra
   Xcode  : Xcode 10.0 Build version 10A255

Environment:

   ANDROID_HOME : not set
```

**Describe the Bug**
Problem when scrolling with Virtual Scroll 

I have two components, one is the list component and the other is the card component.

**Related Code**

```
<ion-list class="lista" [virtualScroll]="list" approxItemHeight="153px" approxItemWidth="352px">
    <div *virtualItem="let item">
      <itinerary-card 
        [route]="item"
      >
      </itinerary-card>
    </div>
</ion-list>
```
**Expected Behavior**
The elements of the virtual scroll list aren't rendered correctly

**Additional Context**
A video where u can see the problem.

https://drive.google.com/file/d/1GLOx5Jhhr79QnG-XysLcdcMaMH9WmNf8/view?usp=sharing

**Comment by kelvinjp** [comment]
+1

**Comment by paulstelzer** [comment]
Thanks for your issue! Virtual scroll has some issues, so the dev teams know of it, but i cannot say when this will be fixed
