### ISSUE TITLE
Build do not update iOS app in IONIC3

### ISSUE THREAD

**Issue by ruben82** [ionic-team/ionic#15709]
App on iOS device is not updated where I execute ionic cordova run ios. No problem encountered on Android

```
cli packages: (/Users/ruben/.nvm/versions/node/v7.8.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.0.0 
    Node              : v7.8.0
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 10.0 Build version 10A255 

Environment Variables:

    ANDROID_HOME : /Library/Android

Misc:

    backend : legacy
```

**Describe the Bug**

I try to execute My IONIC 3 app on a real device and I have some problems to do it on iOS device.
When I try to do it, App is run on iOS device but not with the latest version but with the previous. 
All works fine if I make it from XCode.

I don't have any problems on Android

**Steps to Reproduce**

1. Add a new variable in statement and put a breakpoint there
2. Run app
3. Breakpoint is called but variable is not visible in the list
4. No error highlighted

**Comment by SquallX** [comment]
Hi,

I've same problem since iOS 12

**Comment by mhartington** [comment]
This sound like XCode 10 issues. Please see this issue here 

http://github.com/apache/cordova-ios/issues/407

It is being address in a future cordova-ios release.
