### ISSUE TITLE
ItemReorder wont keep original index position

### ISSUE THREAD

**Issue by julianCast** [ionic-team/ionic#15703]
# Bug Report

**Ionic Info**
```
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.2 
    ios-sim           : 5.0.13 
    Node              : v8.2.1
    npm               : 5.7.1 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4.1 Build version 9F2000 

Environment Variables:

    ANDROID_HOME : /Users/julian/Library/Android/sdk
```

**Describe the Bug**
Using [ItemReorder](https://ionicframework.com/docs/api/components/item/ItemReorder/), if we drag an element around and, without droping it, move it back to the original position and drop it, the element will move to any other last position it was moved.

**Steps to Reproduce**
1. Go to the Ionic demo sample [ItemReorder](https://ionicframework.com/docs/api/components/item/ItemReorder/)
2. Click on edit, drag an element up and down without droping it, then drop it in the original position.
3. The element wont be in the right position.

**Expected Behavior**
The element should  just stay in the original position due we didnt dropped anywhere else.

**Additional Context**
Somehow while we are dragging the element, an event must be getting index ids, instead of listening  that on drop. Once we have dragged the element to a different position than original, the original position index will be lost.

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
