### ISSUE TITLE
[Ionic 4 Beta11] - Navigation animation only applies to elements inside ion-content and not the page itself

### ISSUE THREAD

**Issue by hghammoud** [ionic-team/ionic#15707]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.8.1
   @angular-devkit/schematics : 0.8.1
   @angular/cli               : 6.2.1
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.7
   @capacitor/core           : 1.0.0-beta.7

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, (and 3 other plugins)

System:

   ios-sim : 6.1.3
   NodeJS  : v8.11.3 (/usr/local/Cellar/node@8/8.11.3_1/bin/node)
   npm     : 5.6.0
   OS      : macOS High Sierra
   Xcode   : Xcode 9.4.1 Build version 9F2000
```

When we go forward and backward only elements inside the ion-content are animated. ion-footer has a different animation speed (faster to show) then the ion content.

Other elements outside do not slide with the page at all.

In the next video you see how the footer is faster the ion-content and on the next page the filter button is shown before the slide complete.

Since ion-fixed is not working anymore, i was forced to place a button outside the scroll area=> I got the animation issue

![ezgif-2-1260cf6c65](https://user-images.githubusercontent.com/8034427/45878707-5b5d6880-bda2-11e8-87c0-c8138f8e3fb8.gif)

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
