### ISSUE TITLE
use LocalStorage to count the number of clicks on a specific button

### ISSUE THREAD

**Issue by falcosama** [ionic-team/ionic#15717]
Hello everyone, I’m a young student and I’m moving my first steps into the world of Ionic. I’m delevoping a simple application, and I need to use LocalStorage to count the number of clicks on a specific button, and use this value in another page of the application. How can I do that?

Thanks for your support!

**Comment by RomeoDenis** [comment]
Why have you chosen localstorage?, ithink for your case a service is a better option if you want to share data between pages

- advice To get that kind of help You should use stackoverflow, this place is for reporting framework issues!!!

**Comment by mhartington** [comment]
Hi there! As this doesn't appears to really an issue, and more of a question, so Im going to close this. Please check out the [forum](https://forum.ionicframework.com) as this is a better place for questions. Thanks!
