### ISSUE TITLE
API Demo Source links go to a 404 from https://beta.ionicframework.com/docs/api/

### ISSUE THREAD

**Issue by mharrisn** [ionic-team/ionic#15719]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[X] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
The 'Demo Source' links provided on https://beta.ionicframework.com/docs/api/ all seem to resolve to a 404 page on Github. It appears that there are duplicate '/component' paths in the URL that are causing the issue

**Expected behavior:**
I would be able to access the Demo Source link

**Steps to reproduce:**

1. Access https://beta.ionicframework.com/docs/api/menu
2. Select the Demo Source icon to the top right of the preview area has an icon that looks like two brackets < >

The link attempts to load https://github.com/ionic-team/ionic/tree/master/core/src/components/components/menu/test/preview/index.html
The correct link appears to be https://github.com/ionic-team/ionic/tree/master/core/src/components/menu/test/preview/index.html

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by damienallen** [comment]
Interesting, the demo pages work for me but the Ionic Native docs are 404, such as:
https://beta.ionicframework.com/docs/native/camera/

> Unable to fetch native/camera: Not Found

**Comment by LucaTerzaghi** [comment]
Same for me!

**Comment by vlapo** [comment]
I think, this issue is related to [ionic-docs](https://github.com/ionic-team/ionic-docs).
