### ISSUE TITLE
Ion-Select not selected after API Call

### ISSUE THREAD

**Issue by abhilashbr92** [ionic-team/ionic#15716]
# Bug Report

**Describe the Bug**
I have a select box which display usernames. The list of usernames is got from a API call.

I have a Form Control which is assigned to the select box.

I have value in the form control but the item is displayed in the select box.

I have made a demo in stackblitz below.

https://stackblitz.com/edit/github-igwscn-8kylvc?file=src%2Fapp%2Fapp.component.ts

**Steps to Reproduce**
1. In app.component.ts there is a variable called delay which has value 3000.Now you see the select box has not selected any value
2. Change delay value to 0 and save.Now you see the select box has value selected.

**Expected Behavior**
With delay value 3000, after the username list is returned the name should be displayed in the box.
The issue doesn't exist if I use v3 ion-select or HTML5 select. It is occuring after updating app to v4.

**Comment by vlapo** [comment]
Have a same issue. It looks like `this.text` property is not updated properly after selected option is loaded. 
https://github.com/ionic-team/ionic/blob/master/core/src/components/select/select.tsx#L189

**Comment by abhilashbr92** [comment]
Hello Ionic team, any update on this. When can we expect the issue to be fixed?

**Comment by abhilashbr92** [comment]
@vlapo Have you found any alternative about this issue?

**Comment by vlapo** [comment]
Not at all. I think it is simple problem with render selected text after load options. But it has to be fixed in stencil component and I do not have experience with it.

**Comment by andleer** [comment]
Providing another example. This is not API bound per se but simply time based.

My example has 3 separate `<ion-select>` elements each with a different delay for loading the respective bound arrays. The selection `<ion-select [(ngModel)]="selectedWidgetId">` is loaded before any delay is introduced. It doesn't seem to matter if this is set before or after the binding array is set. Each of the 3 controls is bound after a delay. The 10ms delay seems to never cause the issue. The 65 is intermittent and the 200 always causes the issue.

As the OP stated, this bug results in the selected element not being shown on the UI but it does immediately appear when you click on the item to change the selection and the popup does show the correct default selection.

I do wonder if this is simply a time issue or if there is some other event (hook?) occurring before the binding array is completed that causes the issue.

This repo contains a simple, single page that demonstrates the issue.
https://github.com/andleer/ionic4-select-bug/

The attached recording was made in the DevApp but I get the same results when running in Chrome locally. The iPhone is a XS running iOS 12.1.2 and whatever the current DevApp version is. Running on Win10, VSCode.

In the recording, I first select Widget2, then Widget3. Then I select and change the value of Widget1. All three widget selects are bound to the same selection ID and they all update as expected when the value is changed. Notice that when Widget2 and Widget3 are displayed no value is shown but then as you select them, the value appears right before the dialog is shown. The dialog has the correct default selected.

https://youtu.be/BX27D3p78KE

Please let me know if there is anything else you need on this.



>>>

$ ionic --version
4.0.0-rc.2

>>>

Angular CLI: 7.1.4
Node: 10.15.0
OS: win32 x64
Angular: 7.1.4
... cli, common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

**Comment by liamdebeasi** [comment]
Hi there,

This issue has been resolved and will be available in the next release of Ionic. I have pushed a nightly build in case you would like to try it out and provide feedback. (`npm i @ionic/core@dev @ionic/angular@dev`)

Thanks for your patience as we worked to resolve this issue!
