### ISSUE TITLE
[Ionic 4.1.2] Ion-Slides doesn't show pager, doesn't swipe over.

### ISSUE THREAD

**Issue by GeorgeL9** [ionic-team/ionic#15713]
# Bug Report

**Ionic Info**
```
   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.4, (and 4 other plugins)

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.10.0 (/usr/local/Cellar/node/10.10.0/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
Ion-Slides with 3 Ion-Slide (local images) don't show the paginator, nor page when running on iOS12 (iPhone 7), but does allow to drag to next slide. The slider does work correctly on Chrome when using ionic serve.

**Steps to Reproduce**

**Related Code**
Simple base app, just with ion slides:

```
<ion-content padding>
  <ion-slides pager="true">
    <ion-slide>
      <img src="/assets/imgs/slide1.png">
    </ion-slide>

    <ion-slide>
      <img src="/assets/imgs/slide2.png">
    </ion-slide>

    <ion-slide>
      <img src="/assets/imgs/slide3.png">
    </ion-slide>
  </ion-slides>
</ion-content>

```

**Expected Behavior**
Slides should show pager, and paginate when swiped.

**Comment by GeorgeL9** [comment]
Interesting discovery, if I tilt the phone into landscape, the pager appears and the functionality works 100%, and returning back to portrait everything works as well.

**Comment by realappie** [comment]
Yeah if you trigger any resize it gets fixed.

**Comment by realappie** [comment]
My testing of this issue was done on ionic 4 beta 5 and 7. I have tested it on later versions and can confirm it works correctly there, checkout `4.0.0-beta.12`

**Comment by GeorgeL9** [comment]
My team has decided to stick with Ionic 3, so I can't test to confirm, but I'll take your word for it.
