### ISSUE TITLE
Ionic 3 Component inside Modal not working

### ISSUE THREAD

**Issue by facundocollado** [ionic-team/ionic#15712]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.9.2**
[] **4.x**

**I'm submitting a ...** 
[X] bug report
[ ] feature request

**Current behavior:**
I have a component called ContactsListComponent, it is imported within the app.module.ts like so:

```
import { ContactsListComponent } from '../components/contacts-list/contacts-list';
import { ContactsListModalPageModule } from '../pages/contacts-list-modal/contacts-list-modal.module';

@NgModule({
  declarations: [
    MyApp,
    ...,
    ContactsListComponent,
    ...
  ],
 imports: [
   ...
    ContactsListModalPageModule
  ],
```

And i can call it using `<contacts-list></contacts-list>` anywhere in my app without any issue.

Problem is, when i add it within a modal which is called from home.ts page, i get an error message saying it is not a known element

> Template parse errors:  'contacts-list' is not a known element: 
> 1. If 'contacts-list' is an Angular component, then verify that it is part of this module. 
> 2. If 'contacts-list' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the @NgModule.schemas' of this component to suppress this message.

My home.ts 
```
import { NavController, ModalController, FabContainer } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(
    ...
    public modalCtrl: ModalController,
    ...
  ) {}

   locateContact(fab: FabContainer) {
    fab.close();
    const myModal = this.modalCtrl.create('ContactsListModalPage', null, {cssClass: "modalStyle", enableBackdropDismiss: true});
    myModal.present();
  }
```

contacts-list-modal.html
```
<ion-content padding>
    <contacts-list></contacts-list> <!-- if i remove the component tag, the modal works -->
</ion-content>
```

contacts-list-modal.ts

```
import { Component } from '@angular/core';
import { IonicPage, ViewController, NavParams } from 'ionic-angular';

@IonicPage()
@Component({
  selector: 'page-contacts-list-modal',
  templateUrl: 'contacts-list-modal.html',
})
export class ContactsListModalPage {

  constructor(private viewCtrl: ViewController, private navParams: NavParams) {
  }

  ionViewDidLoad() {
  }

  closeModal(){
    this.viewCtrl.dismiss();
  }
}
```

contacts-list-modal.module.ts

```
import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { ContactsListModalPage } from './contacts-list-modal';

@NgModule({
  declarations: [
    ContactsListModalPage,
  ],
  imports: [
    IonicPageModule.forChild(ContactsListModalPage),
  ],
})
export class ContactsListModalPageModule {}
```

**Expected behavior:**
Modal should inject the component like any other element whitin the app currently does. Perhaps i am missing something ?

**Steps to reproduce:**
Add the `<contacts-list></contacts-list>` tag inside the "ContactsListModalPage"

**Other information:**
I have already tried calling the modal without lazy-loading it, and importing a shared module for ContactsListComponent inside app.module.ts, but when i do it tells me that ion-refresher is not a known element (i use ion-refresher inside my contacts-list component)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 11 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/yaher/Android/Sdk)
   NodeJS            : v10.10.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.15

```

**Comment by vlapo** [comment]
Hi @facundocollado,

Your problem is `ContactsListModalPageModule` do not know your `ContactsListComponent` because this module is lazy loaded and have own "context". You have to import module with exported `ContactsListComponent`. For example move `ContactsListComponent` to some `SharedModule` and import this module to `ContactsListModalPageModule` (and every module where you want to use this component e.g. AppModule).

I made some example for you https://stackblitz.com/edit/ionic-k8x4e4.

Btw GitHub issues are for bug reports and feature requests. Next time create some stackblitz.com example and ask your question on:
- https://forum.ionicframework.com/
- https://stackoverflow.com/
- slack - https://ionicworldwide.herokuapp.com/

Hope my answer will help you.

**Comment by facundocollado** [comment]
Hello @vlapo , thank you for for your reply!
I updated my code and now the modal loads just about fine.
Regardless the <ion-refresher> not working, like you just said, since the modal has its own "contect", i hace to declare the ionic components in the shared module as well and everything works just about fine.

Here are the changes inside the shared module in case someone else had this issue:

```
import { IonicModule } from 'ionic-angular';
import { ContactsListComponent } from './contacts-list/contacts-list';
...
@NgModule({
	...
	imports: [
		IonicModule.forRoot(ContactsListComponent), //now i can use ionic stuffs inside my modal
	],
	...
})
```
