### ISSUE TITLE
Popover cssClass does not target correct area. (Ionic V4)

### ISSUE THREAD

**Issue by wterrill** [ionic-team/ionic#15711]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (/Users/williamterrill/Library/Android/sdk/)
   ios-deploy        : 1.9.2
   NodeJS            : v8.11.1 (/usr/local/bin/node)
   npm               : 5.6.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
when using the popover components, the cssClass: "popover_class" targets the parent page and not the popover itself.

**Steps to Reproduce**
1. Create new ionic 4 project
2. generate new component: (ionic generate component testPopover)
3. Create button in home page that points to ts file:
```
      <ion-button icon-only solid *ngIf="admin" (click)="presentTest($event)">
          <ion-icon name="menu"></ion-icon>
        </ion-button>
```
4. In home.page.ts file, add this code (and all associated imports):
```
import { PopoverController } from "@ionic/angular";
import { TestPopoverComponent } from "../test-popover/test-popover.component"


  async presentTest(args) {
    const popover = await this.popoverCtrl.create({
      component: TestPopoverComponent,
      event: args,
      componentProps: args,
      translucent: true,
      cssClass: "popover_class"
    });
    return await popover.present();
  }
```

5. in global.scss or variable.scss add:
```
.popover_class{
  --background: blue;  // to take care of a possible css4
  background: blue;     // to treat it as normal css

}
```
4. After an 'ionic serve' press the menu button.  Instead of just the background color of the popover container turning blue, the background of the parent page turns blue.

**Expected Behavior**
the cssClass property of the popover Component should only affect the container of the popover component, and not the parent container

FWIW: The only way that I can see to change the background color (or any other property) of the popover is by placing:
.popover-content.sc-ion-popover-ios{
    background: yellow;
}
in either variable.scss or global.scss.

**Comment by brandyscarney** [comment]
The class is being properly applied to the `ion-popover` element. The problem here is when you style the `background` you are changing the background of the element that takes up the full width/height over the content. If you were to set the background to something with transparency, for example:

```
.popover_class {
  background: rgba(0, 0, 0, 0.4);
}
```

You'll see the page itself isn't getting the background. Because the overlay components (alert, action sheet, popover, etc) aren't using shadow DOM, you can use normal CSS to target whichever element you want to style. So to style just the content:

```
.popover_class .popover-content {
    background: lightsteelblue;
}
```

Whether or not we will be adding CSS Variables to target certain elements is something we still need to discuss internally though.

**Comment by wterrill** [comment]
outstanding.  That makes more sense.  Thank you for the help.

**Comment by james11a** [comment]
@brandyscarney Don't know if anything changed between when you commented and `Ionic v4.0.0-beta.19`, but the solution you provided is not working currently with the beta.19. However, I did notice that it does work if I have my `ViewEncapsulation` set to **None**. Is this normal?

Also, the solution you provided, is this a clean approach as we are directly accessing the component's internal class (`.popover-content`)? The ionic team could decide to change this class name any time without notice, as `.popover-content` in a way isn't a publicly documented class, which would break this implementation for many people.
