### ISSUE TITLE
Alert Options

### ISSUE THREAD

**Issue by marvtdawson** [ionic-team/ionic#15721]
# Support Question

Revisiting Ionic from v3 to v4 now.  The beta API documentation references a 'header' and 'subHeader' option in the example.  I got an error in my editor (WebStorm) following the example, assuming that this is a new change with the Alert API.   

My question is:  Shouldn't the beta documentation reference a 'title' and 'subTitle' option?   

Just wondering if this a small mistake or is there something new coming down the pipeline.

Thanks in advance

**Comment by vlapo** [comment]
Hi @marvtdawson,

Ionic 4 is major release and there are a lot breaking changes. This is one of them. See https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#alert
