### ISSUE TITLE
Page(Screen) is not showing variable value on next page after routing (IONIC 4 Beta)

### ISSUE THREAD

**Issue by amit-dubey-2018** [ionic-team/ionic#15731]
When i navigate from one page to another via routing then on next page dynamic variables values not showing on page(screen). If i touch anywhere on screen it displays on screen immediately. I have tried several methods for displaying value on screen but none is working. I have tried NgZone but also not working. Please help me.
  
Here is HTML File Code
<div class="selected-date">{{scheduled_date}}</div>
<div class="selected-time">{{scheduled_time}}</div><br><br>

Here is TS File Code

  ngOnInit() { 
    this.zone.run(() => {
      this.scheduled_date = this.common.formatDate(new Date());   // '22/09/2018'
      this.scheduled_time = this.common.formatTime(new Date());   // '11:30 AM'
    });
  }

  ngAfterViewInit() {
    this.zone.run(() => {
      this.scheduled_date = this.common.formatDate(new Date());
      this.scheduled_time = this.common.formatTime(new Date());
    });
  }

  ngAfterContentInit() {
    this.zone.run(() => {
      this.scheduled_date = this.common.formatDate(new Date());
      this.scheduled_time = this.common.formatTime(new Date());
    });
  }

**Comment by lzoubek** [comment]
Perhaps ng* lifecycle methods are not called at all when you navigate back to your page.
