### ISSUE TITLE
[Ionic 4 beta11] Labels are not shown on ios mode

### ISSUE THREAD

**Issue by quynh-ng** [ionic-team/ionic#15732]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.2.3
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 10 other plugins)

System:

   Android SDK Tools : 26.0.2 (/usr/local/share/android-sdk)
   ios-deploy        : 1.9.2
   NodeJS            : v10.8.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
When the app runs under iOS mode, all labels are not shown

![ionic-lab](https://user-images.githubusercontent.com/2505599/45940843-809de100-c005-11e8-88ce-666cd4d65409.jpg)

I tried downgrade to beta.7, everything work fine.

**Comment by manucorporat** [comment]
Can you provide a small demo that reproduces the issue? I can't reproduce it

**Comment by quynh-ng** [comment]
> Can you provide a small demo that reproduces the issue? I can't reproduce it

Hi,

Here my sample app to reproduce the bug => https://github.com/quynh-ng/ionic-labels

But I found something:
- color value of labels are set to empty string (""), on Android the labels are shown, but on iOS that not.
- the color (CSS) of the labels == var(--ion-color-base), but the value of "--ion-color-base" is empty string, then iOS mode doesn't known the color value (and set as transparent), but Android doesn't acts like this way.

**Comment by manucorporat** [comment]
@quynh-ng if you don't want a color, do not pass an empty string, but `null` or `undefined`, thanks!
