### ISSUE TITLE
ion-toggle not clickable in ion-buttons in ion-toolbar

### ISSUE THREAD

**Issue by gydammin** [ionic-team/ionic#15739]
When in header, <ion-toggle> is not clickable. In ion-content, it's working without problem. It's seems it is related to **ion-buttons** as placing <ion-toggle> inside a floating div works:

**Not working for header placement:**

```
<ion-header>
    <ion-toolbar>
        <ion-title>My title</ion-title>
        <ion-buttons slot="end">
            <ion-toggle [(ngModel)]="autopilot"></ion-toggle>
        </ion-buttons>
    </ion-toolbar>
</ion-header>
```

**Working with a floating div:**

```
<div style="float:right">
    <ion-toggle [(ngModel)]="autopilot" (ionChange)="flashMessage()"></ion-toggle>
</div>
```

**Comment by pos7hink** [comment]
I think 'pointer-events: none' causes this problem.
So here is another workaround without adding 'div' tag:

```
<ion-toggle [(ngModel)]="autopilot" (ionChange)="flashMessage()" style="pointer-events: auto"></ion-toggle>
```

**Comment by manucorporat** [comment]
Fixed in master by: https://github.com/ionic-team/ionic/commit/9d6169acdd4f46e001eec8f55f4f34af7bf5c3db
