### ISSUE TITLE
[Ionic 4 beta11] Grid breakpoints not work when sreen width is under 576 pixels

### ISSUE THREAD

**Issue by quynh-ng** [ionic-team/ionic#15746]
**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.2.3
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 10 other plugins)

System:

   Android SDK Tools : 26.0.2 (/usr/local/share/android-sdk)
   ios-deploy        : 1.9.2
   NodeJS            : v10.8.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
***ion-grid*** breakpoints not work as expected when the screen width is under 576 pixels (means 575 pixels and lower), all columns had no breakpoint (just like the attachment image below).
![575](https://user-images.githubusercontent.com/2505599/46021410-d60fe600-c10a-11e8-955c-35a9b2b7ab84.jpg)

**Steps to Reproduce**
1. Create any page with ion-gird
2. Here my markups:
```xml
<ion-grid>
	<ion-row>
		<ion-col *ngFor="..." size-sx="6" size-sm="4" size-md="4" size-lg="4" size-xl="3">
			<ion-item>...</ion-item>
		</ion-col>
	</ion-row>
</ion-grid>
```
**Additional**
This is grid at 576 px sreen width
![576](https://user-images.githubusercontent.com/2505599/46021438-e0ca7b00-c10a-11e8-9db3-3baee98aa13d.jpg)

**Comment by rtpHarry** [comment]
In your example you have used `size-sx="6"` when it should be `size-xs="6"`. 

Is this pulled from your app or just an example you typed out?

**Comment by quynh-ng** [comment]
Wow, just update "-sx" to "-xs", seem everything are fine.
Thanks.
