### ISSUE TITLE
ionImgDidLoad fires too early

### ISSUE THREAD

**Issue by robmacecs** [ionic-team/ionic#15748]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI) : 4.1.2

System:

   NodeJS : v10.9.0
   npm    : 6.4.0
   OS     : macOS High Sierra
```

**Describe the Bug**
When using `ion-img` with `ionImgDidLoad` on large images, the event is triggered before the image is actually loaded in the browser. I'm not 100% sure this is a bug? Maybe it's not possible to know when the browser has painted the image? But if not, then the event ought to be `ionImgWillLoad` right? 

**Steps to Reproduce**
1. Create `ion-img` with a large img src
2. Log a message to the console so show when the event has been triggered
3. View in browser (Mobile emulation + throttling makes the effect more obvious)
4. Log will be shown before the image is displaying fully

**Related Code**
https://stackblitz.com/edit/angular-ionic4-test-rq72qb

**Expected Behavior**
Either the event is triggered when the browser actually loads the image (preferred), or the event be renamed ionImgWillLoad (not ideal, but less misleading than current state)

**Comment by goelectricstations** [comment]
same issue:

Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\Computer\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 1.2.1, (and 12 other plugins)

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.3.0-next.0
   OS     : Windows 10

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
