### ISSUE TITLE
iPhone6 background app crash experienced after in background for 2 hours or less

### ISSUE THREAD

**Issue by ComputerGuruInTraining** [ionic-team/ionic#15754]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
ionic info
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)  : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.1, (and 4 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.0.0
   NodeJS     : v6.11.2 (/usr/local/bin/node)
   npm        : 3.10.10
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

```

**Describe the Bug**
I created a brand new app built using the command "ionic start myApp tabs" sourced from https://ionicframework.com/getting-started#cli on the 6th September 2018. The app crashed on iPhone6 after the app had been in the background for about 40 minutes.

I tested the brand new app because an ionic app I have built and that is on the app store crashes on iPhone6 and on a new Samsung Android Phone too, after being in the background for various periods. Sometimes 2 hours, sometimes 30 minutes. Has not been found to crash on iPhone5 when in the background for long periods, nor on an older version of android (Samsung Galaxy J3).

Same local environment was used to develop both the app store ionic app and the brand new ionic app (though no changes were made to the brand new ionic app, just added the platform and built for ios with --prod flag ie ionic cordova build ios --prod).

Xcode console log provides the message "failed due to memory issue" or something to that effect when crash occurs.

**Steps to Reproduce**
Steps to reproduce the behavior (note, doesn't just occur on ios):
1. Start a new ionic app with command 'ionic start myApp tabs'
2. ionic cordova platform add ios
3. ionic cordova build ios --prod
4. Open XCode, run to a connected iPhone6
5. Keep the app running in the background of the phone and use other apps on phone, check periodically (every 2 hours) until reloads with the splashscreen. Should occur on the first or second check, perhaps a third needed.
6. Error on Console (Xcode) "Terminated due to memory issue" 

**Related Code**
If you are able to illustrate the bug with an example, please provide a sample application via an online code collaborator such as [StackBlitz](https://stackblitz.com), or [GitHub](https://github.com).

**Expected Behavior**
The app should not reload and display the splashscreen. The app should show the same screen that was showing when the app was moved into the background.

**Additional Context**
Xcode console log. 

Note: ionic was used to build an app which is on the app store and the background crash error was discovered. Upon testing, a brand new ionic project with no changes made was tested and also experienced the background crash. The Xcode console log below was gathered for the app store app, but some details would apply to the starter app, in particular "Terminated due to memory issue" 

https://lh3.googleusercontent.com/GzjlFR4yWC9hhSowJqkBvuY2FWtnEAEI2HiUO2yAV-AXdX3ucT2P4SgaEN1UTR3pyd_1OBSbfhFLzFMCtwo65vfzvUHEOjcuh45NbMlQcXhycTGMKccgv-Cgo_SCf0LfwFbk1TEX

**Comment by mhartington** [comment]
Hi there! So this is actually a "feature" in iOS.

https://github.com/swisspol/GCDWebServer/issues/386#issuecomment-418134261

Any app that is in the background will eventually get suspended by the OS to preserve memory. This is beyond anyones control.
