### ISSUE TITLE
Toast not showing over an active modal

### ISSUE THREAD

**Issue by Tochukwuibe** [ionic-team/ionic#15753]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
$ ionic info
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\Toch\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.4, (and 10 other plugins)

System:

   NodeJS : v8.11.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.0.0
   OS     : Windows 10

```

**Describe the Bug**
When using the toast controller in a modal, the toast does not show as you would expect, instead, it shows on the page behind it.

**Steps to Reproduce**
1. create a modal
2. open modal
3. create a toast

**Related Code**
If you are able to illustrate the bug with an example, please provide a sample application via an online code collaborator such as [StackBlitz](https://stackblitz.com), or [GitHub](https://github.com).

**Expected Behavior**
The toast is supposed to be visible on the modal page

**Additional Context**
I created a feedback which abstracts the toastcontroller api and a few others into a simpler api

**Comment by Tochukwuibe** [comment]
I could, but would I have to update my ionic cli then start a new project ?

**Comment by manucorporat** [comment]
@Tochukwuibe no, just update the `package.json` to beta.11 and run `npm install`

**Comment by Tochukwuibe** [comment]
the update fixed the issue, Thank You!

**Comment by manucorporat** [comment]
thanks!
