### ISSUE TITLE
Compile Ionic3 with iOS12 failed

### ISSUE THREAD

**Issue by mchenx** [ionic-team/ionic#15762]
After upgraded Xcode from 9 to 10 (iOS11.3 to 12), I cannot compile ionic for ios any longer, the build completed immerdiately after setting a fewer variables like 
**...
PODS_ROOT = ${SRCROOT}/Pods
SWIFT_OBJC_BRIDGING = ${PROJECT_DIR}/$(PROJECT_NAME)/Bridging-Header.h**

then 

**No scripts found for hook "after_commpile".
No scripts found for hook "after_build".**

If I open the xcode project and build in xcode, I can see one error saying:

**ld: library not found for -lstdc++.6
clang: error: linker command failed with exit code 1 (use -v to see invocation)**

Here is the ionic info for my project:

**Ionic CLI: 4.1.2
Ionic Framework: 3.9.2
@ionic/app-script: 3.1.9
Cordova CLI : 8.0.0
Cordova Platforms: ios 4.5.5
Xcode: 10.0 Build vrsion 10A255**

Any one encountered similar issue?

**Comment by mhartington** [comment]
Hi there! This issue does not appear to be an issue with the framework itself, so it will be closes. Please review your issue and open a new ticket on the appropriate project repository, or feel free to post a question on the [Ionic Forum](http://forum.ionicframework.com). Thanks!
