### ISSUE TITLE
Ionic App crashes in background of iPhone6 and Samsung5 mobile. Fix Ionic apps so they can run in the background because apple documentation specifies possible

### ISSUE THREAD

**Issue by ComputerGuruInTraining** [ionic-team/ionic#15769]
The Ionic App starter project crashes if left in the background for periods from 30 minutes to 2 hours, not usually sooner. It crashes on iPhone6 and a Samsung5, but not on iPhone5.

Apple Documentation regarding Background Apps and what must be done:

"Most apps can move to the suspended state easily enough but there are also legitimate reasons for apps to continue running in the background. A hiking app might want to track the user’s position over time so that it can display that course overlaid on top of a hiking map. An audio app might need to continue playing music over the lock screen. Other apps might want to download content in the background so that it can minimize the delay in presenting that content to the user. When you find it necessary to keep your app running in the background, iOS helps you do so efficiently and without draining system resources or the user’s battery. The techniques offered by iOS fall into three categories:

*Apps that start a short task in the foreground can ask for time to finish that task when the app moves to the background.
*Apps that initiate downloads in the foreground can hand off management of those downloads to the system, thereby allowing the app to be suspended or terminated while the download continues.
*Apps that need to run in the background to support specific types of tasks can declare their support for one or more background execution modes."

(Source: https://developer.apple.com/library/archive/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html)

**Comment by ComputerGuruInTraining** [comment]
It seems reasonable that the default for an ionic mobile app would be to not continue running in the background. What I propose is a native plug-in that takes options for background-execution addressing the 3 sorts: short task, hand off to system to complete the task, and long task (such as location). Apps running in the background are common enough.

**Comment by paulstelzer** [comment]
I think this is more problem related to Cordova instead of Ionic, isn't it?

**Comment by mhartington** [comment]
So there's a few things...

Apps "crashing" in the background

iOS does terminate app process once they've been in the background for some time. Meaning by default, any app (native or cordova-base) will be killed at some point.

Background modes in iOS

You can add this plugin if you want to support background modes in your app

https://github.com/katzer/cordova-plugin-background-mode

But iOS/Apple is pretty picky about what apps can do in the background. They tend to take it case-by-case and your app _needs_ to have a good reason for needing to run in the background.

Also, as @paulstelzer has said, this is more or a cordova/capacitor question, not the UI framework. With that in mind, I'm going to close this. Thanks!
