### ISSUE TITLE
[v4] ionic/angular not working properly on Microsoft Edge 38 (missing polyfills?)

### ISSUE THREAD

**Issue by mmlleevvyy** [ionic-team/ionic#15763]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
ionic4.beta-11
Microsoft EdgeHTML 14.14393
Microsoft Edge 38.14393.2068.0
```

**Describe the Bug**
App that was build with ionic4.beta.11 and angular (latest) is not working properly on Microsoft Edge. Tried with simple ionic starters and no luck - page is loading, but ionic components are not styled. It looks like shadowdom is not supported and polyfill is not loaded. Documentation (https://beta.ionicframework.com/docs/components) for ionic beta  is not working on Edge as well.

**Steps to Reproduce**
1. Run any ionic starter for angular
2. Check in Microsoft Edge

**Expected Behavior**
For Microsoft Edge, polyfill should be loaded for missing features.

**Comment by manucorporat** [comment]
Which missing feature are you referring too? can you share some screenshot/error?

**Comment by mmlleevvyy** [comment]
@manucorporat I was referring to features like ShadowDom, custom elements or array functions. As I wrote - create ionic/angular starter app and run it in Microsoft Edge v38 - it will start, but the components are not styled.

Chrome:
![localhost_4200_home](https://user-images.githubusercontent.com/10324672/46094744-00b97780-c1bb-11e8-99c7-a7da8c3d1000.png)

Edge 38:
<img width="1182" alt="zrzut ekranu 2018-09-26 o 18 36 46" src="https://user-images.githubusercontent.com/10324672/46094794-2d6d8f00-c1bb-11e8-8980-1c7a4160d043.png">
In Edge, the starter app throws dozen of "ERROR TypeError: Object doesn't support property or method 'forEach'":
<img width="760" alt="zrzut ekranu 2018-09-26 o 18 44 56" src="https://user-images.githubusercontent.com/10324672/46095226-50e50980-c1bc-11e8-882b-60d218037a38.png">

So it looks like missing polyfill. In my app, the forEach error is not raised, but rather "TypeMismatchError undefined" (but the result is the same - components are not styled and no ShadowDom):
<img width="873" alt="zrzut ekranu 2018-09-26 o 18 43 32" src="https://user-images.githubusercontent.com/10324672/46095157-1d09e400-c1bc-11e8-90e2-ba485aff75b1.png">

**Comment by royanon** [comment]
Test on  42.17134.1.0 it work on
ionic4.beta-16
Microsoft EdgeHTML 17.17134
Microsoft Edge 42.17134.1.0

But it doesn't work in IE 9,10,11.
Same error of 'forEach' and all style missing.

**Comment by paulstelzer** [comment]
Thanks for your issue!  The original issue was related to Egde and this seems to be working, so I close this issue here. If you need IE 9 support, please add a feature request. Thank you!
