### ISSUE TITLE
[Ionic 4] Back button not present in the navbar

### ISSUE THREAD

**Issue by sirhaplo** [ionic-team/ionic#15764]
# Bug Report

**Ionic Info**
```
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\Daniele\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : none
   Cordova Plugins       : not available

System:

   NodeJS : v10.9.0 (C:\Program Files (x86)\nodejs\node.exe)
   npm    : 5.7.1
   OS     : Windows 10
```

**Describe the Bug**
Starting from a blank project, it doesnt works the back functionality.
After navigate to another page it does not show the back button on the navbar and on android the hardware back doesnt work

**Steps to Reproduce**
1. `ionic start backbutton blank --type=angular`
2. `ionic g page second`
3. In `/src/app/home/home.page.html` add `<ion-button [routerLink]="['/second']">Go to Page Two</ion-button>` in the content
4. `ionic serve`

**Related Code**
```
<ion-header>
  <ion-toolbar>
    <ion-title>
      Ionic Blank
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content padding>
  <ion-button [routerLink]="['/second']">Go to Page Two</ion-button>
</ion-content>
```

If i add 
````
<ion-buttons slot="start">
      <ion-back-button></ion-back-button>
</ion-buttons>
````
in the second page i see the arrow to go back.
But the android hardware button still not works

**Expected Behavior**
After clicking the link, in the new page, should be present the back arrow button on the navbar.
And the hardware back button should work

**Comment by jordanpurinton** [comment]
Seconded, have had this same issue from the get go.

**Comment by mhartington** [comment]
Hi there! Please update to the latest version of ionic/angular

```
npm i @ionic/angular@latest

```

This is fixed there.
