### ISSUE TITLE
Ionic v4 Beta 12 - goBack() not triggering ChangeDetection and removing element after animation

### ISSUE THREAD

**Issue by hghammoud** [ionic-team/ionic#15778]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.8.1
   @angular-devkit/schematics : 0.8.1
   @angular/cli               : 6.2.1
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.7
   @capacitor/core           : 1.0.0-beta.7

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, (and 3 other plugins)

System:

   ios-sim : 6.1.3
   NodeJS  : v8.11.3 (/usr/local/Cellar/node@8/8.11.3_1/bin/node)
   npm     : 5.6.0
   OS      : macOS High Sierra
   Xcode   : Xcode 9.4.1 Build version 9F2000

```

**Describe the Bug**
When navigating using NavController.navigateForward, pressing the back button in the header goes back and the temporary ion-page used for animation is destroyed properly.

However if we have a custom button, and we call the NavController.goBack() the animation triggers but the element stays rendered until we try to  click/scroll on the view.

Here is the state of the component when open
![image](https://user-images.githubusercontent.com/8034427/46174250-c62e0880-c2a8-11e8-9522-6403a3f02489.png)

Here is the state after goBack()
![image](https://user-images.githubusercontent.com/8034427/46174289-e231aa00-c2a8-11e8-84a3-e92137fcdea1.png)

You can clearly see that the element is still there and z-index: 100.
So if this element has a background-color, you wont see the page behind and if background color is transparent you can not click on the elements. You have to double click. 
One click to trigger change detection and remove the element and the next one for the actual click.

**Expected Behavior**
The element should be removed after the animation is finished.
The result of goBack() should be the same as clicking the back button in the header.

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
