### ISSUE TITLE
ion-show-when / ion-hide-when with size improperly shows/hides size and up

### ISSUE THREAD

**Issue by btsiders** [ionic-team/ionic#15776]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\Bryan\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.2.3
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
The `ion-show-when` and `ion-hide-when` components, when used with the size attribute, show/hide their contents for the given breakpoint size **and up**. They should only show/hide their content for the given breakpoint size itself.

**Steps to Reproduce**
1. Go to https://beta.ionicframework.com/docs/content/api//hide-when-demo.html
2. Size your browser down to md.
3. "Only hide on lg" and "Only hide on xl" show up.

OR

1. Go to https://beta.ionicframework.com/docs/content/api//show-when-demo.html
2. Size your browser up to xl.
3. "Only render on xs", "Only render on sm", "Only render on md", "Only render on lg", "Only render on xl", "Only render on XS or m" all show up.

**Related Code**
Demo pages show issue.

**Expected Behavior**
* For `ion-hide-when` and size = 'md', the first set of steps should also show 'Only hide on xs' and 'Only hide on sm'
* For `ion-show-when` and size = 'xl', the second set of steps should only render 'Only render on xl'

**Additional Context**
***Workaround***
Nesting `ion-hide-when` and 'ion-show-when` can give me the desired output, but it looks like it shouldn't be required.

```
<ion-show-when size="sm">
  <ion-hide-when size="md">
    <div>Workaround to show only show on sm</div>
  </ion-hide-when>
</ion-show-when>
```

**Comment by mhartington** [comment]
This was a design decision made a while back to make show-when/hide-when similar to iron-query from polymer. IMO, I think that it should be have closer to how we had it in v3, vs this newer way. @brandyscarney and I will have to discuss this.
