### ISSUE TITLE
Ionic beta 12 footer issue for iPhoneX

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic#15774]
Header is good but footer is not right.

`https://unpkg.com/@ionic/core@4.0.0-beta.12/dist/ionic.js`

[
<img width="307" alt="screen shot 2018-09-27 at 11 23 47 pm" src="https://user-images.githubusercontent.com/8480351/46164792-8c5f0100-c2ac-11e8-9812-0f6adc1482ec.png">
](url)

**Comment by mhartington** [comment]
Hi there! Can you please provide some markup or a sample app on github to debug/test against? Kind of hard to debug without it.

**Comment by stripathix** [comment]
Hi @mhartington, Please find below  GitHub repo in which issue can be reproduced easily. I created it to reproduce any Ionic4 based issue i'll  face.

https://github.com/stripathix/ionic-vue

**Comment by stripathix** [comment]
This works now in current version of ionic.
