### ISSUE TITLE
Ionic4 beta12: By default slides are having autoplay and behaviour on stopping it is intermittent

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic#15770]
Sometimes it works sometime it doesnt
```
imageryUtility.stopAutoPlay = function () {
    if (!slides) {
        slides = document.querySelector("ion-slides");
    }
    slides.stopAutoplay();
};
```

**Comment by stripathix** [comment]
I want to disable swipe gesture and disable autoPlay.

If I do this then auto play stops:
```
slides = document.querySelector("ion-slides");
slides.stopAutoplay();
```

If I do this then swipe gesture is disabled:
```
slides = document.querySelector("ion-slides");
slides.options = {
       allowTouchMove: false
 };
```

But when I try to use both of the above code then autoplay starts again.

This is also not working:
```
 slides.options = {
         allowTouchMove: false,
         loop: false
};

```

**Comment by mhartington** [comment]
This is fixed in master via https://github.com/ionic-team/ionic/commit/db6ddb0d66974a370c2a26ede630d08446c362f9

**Comment by mhartington** [comment]
No, not yet, but your solution of calling `stopAutoplay` is pretty close to what we did internally. Another way is to copy what we have with 

```
slides.options.autoPlay = false
```

**Comment by stripathix** [comment]
stopAutoplay() does solves it but as soon as i set allowTouchMove: false, then again autoplay starts.

**Comment by netsesame2** [comment]
```
slides.options.autoPlay = false
```
doesn't work.

**Comment by stripathix** [comment]
I have used swiper.js till it's not fixed in ionic 4.
