### ISSUE TITLE
[4.0.0-beta.12]: split pane breaks responsive grid stacking

### ISSUE THREAD

**Issue by bitjson** [ionic-team/ionic#15780]
# Bug Report

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

System:

   NodeJS : v8.12.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS
```

**Describe the Bug**
When using split pane (e.g. in the `sidemenu` starter project), the `Stacked to horizontal` Responsive Grid example from the docs doesn't work when the browser window is adjusted more than once.

**Steps to Reproduce**
1. Create a project using the `sidemenu` starter
2. Add the following to the `ion-content` of `home.page.html`:
```
 <ion-grid>
    <ion-row>
      <ion-col size="12" size-md>
        <div>
          Left on big screens, top on little screens
        </div>
      </ion-col>
      <ion-col size="12" size-md>
        <div>
          right on big screens, bottom on little screens
        </div>
      </ion-col>
    </ion-row>
  </ion-grid>
```
3. `npm start`
4. Widen the browser window to see the behavior at large sizes.
5. Narrow to see the stacking. 
6. Widen to see the items unstack.
7. Narrow the window and note that the items no longer stack (staying at 50% width of the container).

**Expected Behavior**
The layout should respond the same way each time the browser window is widened and narrowed.

**Additional Context**
Confirmed on Chrome, Safari, and Firefox.

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)

**Comment by bitjson** [comment]
@paulstelzer I can't reproduce anymore after upgrading. Seems to be fixed, thanks!
