### ISSUE TITLE
[v4 beta.12] SCSS files are missing in the installed package

### ISSUE THREAD

**Issue by genadis** [ionic-team/ionic#15783]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

System:

   NodeJS : v8.9.3 (/usr/local/bin/node)
   npm    : 5.5.1
   OS     : macOS High Sierra
```

**Describe the Bug**
In previous versions @ionci/angular contained the scss files in the the dist folder so by including:
```
@import "~@ionic/angular/dist/themes/ionic.globals.scss";
```
We could use the mixins and other useful stuff.

Now it's gone breaking existing apps.

**Steps to Reproduce**

**Related Code**

**Expected Behavior**
@ionic/angular or core should contain the scss in the package.

**Additional Context**

Thanks!

**Comment by brandyscarney** [comment]
Thanks for the issue! We do not plan to include the Sass files at this time. The Ionic Sass is used internally and if we supported it as a public API we would have to include any changes to it as a breaking change. If you are using Sass in your app you can always re-create any mixins that you find useful. If you have questions on theming please create a post on our [forum](https://forum.ionicframework.com). 

Please see my comment here for more information on theming: https://github.com/ionic-team/ionic/issues/15437#issuecomment-433505373. Thanks! 🙂
