### ISSUE TITLE
[Ionic V4-beta.12] app.getActiveNav() was deleted 

### ISSUE THREAD

**Issue by mohamedsharaf** [ionic-team/ionic#15782]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```

Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.4, (and 42 other plugins)

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.10.0 (/usr/local/Cellar/node/10.10.0/bin/node)
   npm        : 6.4.1
   OS         : macOS
   Xcode      : Xcode 10.0 Build version 10A255

```

**Describe the Bug**
app.getActiveNav()  removed from v4 also same issue on old version 
https://github.com/ionic-team/ionic/issues/12362

**Steps to Reproduce**
Update to Ionic 4.0.0-beta.12
Use this.app.getActiveNav()

**Related Code**
this.app.getActiveNav()

**Expected Behavior**
put this function back 

**Additional Context**
https://github.com/ionic-team/ionic/issues/12362

@danbucholtz

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please open this as feature request and provide more information (why are need it etc) and fill out the feature request issue form. That would be great :)
