### ISSUE TITLE
[Ionic V4-beta.12] some removed functions by error 

### ISSUE THREAD

**Issue by mohamedsharaf** [ionic-team/ionic#15786]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.4, (and 42 other plugins)

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.10.0 (/usr/local/Cellar/node/10.10.0/bin/node)
   npm        : 6.4.1
   OS         : macOS
   Xcode      : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
some function removed was exist in v3.9.2
i will make it simple and list how to produce error for explained description #15782

**Steps to Reproduce**

this.platform.setLang
this.platform.setDir
 this.app.getActiveNav()

**Expected Behavior**
add the functions back

**Comment by muratcorlu** [comment]
Is `platform.setLang` removed in purpose? Will we get this back?

**Comment by paulstelzer** [comment]
For me it's not a bug report. That are features. Please open a new issue what features do you like to have

**Comment by paulstelzer** [comment]
@manigujjula Thanks for your report! I don't know what you want to say. What is "app"? And getActiveNav() is no method in Ionic 4.

**Comment by manigujjula** [comment]
I'm Using GetActiveNav() for hardware back button to exit the app. Any thanks for your Docs.

**Comment by mohamedsharaf** [comment]
by app we mean

```
import {
    Events,
    App,
    Platform
} from 'ionic-angular';
 constructor(
        public events: Events,
        public app: App,
        public platform: Platform,
) {
}

```

**Comment by manigujjula** [comment]
Please Check Out this Code .

` backButtonEvent(){
    this.platform.backButton.subscribe(async () => {
      this.routerOutlets.forEach((outlet: IonRouterOutlet) => {
          if (outlet && outlet.canGoBack()) {
              outlet.pop();

          } else  {
              if (new Date().getTime() - this.lastTimeBackPress < this.timePeriodToExit) {
                  // this.platform.exitApp(); // Exit from app
                  navigator['app'].exitApp(); // work in ionic 4

              } else {
                this.showAlert()
                  this.lastTimeBackPress = new Date().getTime();
              }
          }
      });
      this.lastBack = Date.now();
  });
  }`
 showAlert() {
    this.snackBar.open('Press back again to exit', '', {
      duration:3000,
    });
  }
