### ISSUE TITLE
[Ionic V4-beta.17] ion-datetime starts on max date

### ISSUE THREAD

**Issue by RHinderiks** [ionic-team/ionic#15792]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/Users/robinhinderiks/.nvm/versions/node/v8.11.4/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.2.3
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 13 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/robinhinderiks/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.0.0
   NodeJS            : v8.11.4 (/Users/robinhinderiks/.nvm/versions/node/v8.11.4/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
When settings a max date the first date you see when selecting a date field is the max date.

**Steps to Reproduce**
1. Create page with ion-datetime
2. set max date to 2100 for example
3. open datepicker

**Related Code**
```<ion-datepicker max="2100"></ion-datepicker>```

**Expected Behavior**
Personally i would like them infinite by default maybe stopping at 9999 like the real datepickers of ios (i think) and only limit them when setting a min and or max date. Also starting at today would seem like the logical solution.

**Comment by bkarv** [comment]
Plus one to having it start on todays date it’s poor user experience for having to scroll down from max date

**Comment by RHinderiks** [comment]
The current work around is to set the current date when you tap on it but this is also not visually appealing

**Comment by RHinderiks** [comment]
Still an issue in beta.17

**Comment by bkarv** [comment]
@RHinderiks Have you found a work around solution? I am desperate on passing an initial view value like today's date but can not find a solution, it keeps opening on max date. I've tried setting an initial value with ionFocus prior to opening but no luck (4.0.0 Neutronium)

**Comment by RHinderiks** [comment]
@bkarv too be honest the date picker ionic provides has way to many issues ( date picker are complex ) . We decided to use a paid third party date picker (and many other features) called mobiscrol (https://mobiscroll.com/ionic-components). They even got an entire page that list what components they have that ionic does not (or work poorly in ionic). They have a free version which sadly does not contain the date picker, however you can try their pro version for free for a month to try it out

**Comment by liamdebeasi** [comment]
Hi there,

This has been fixed with the latest version of Ionic! To get the latest changes, run `npm i @ionic/core@latest @ionic/angular@latest`.

Thanks!
