### ISSUE TITLE
[v4.0.0-beta.12] Header height still doesn't work fine on iPhone X

### ISSUE THREAD

**Issue by babaru** [ionic-team/ionic#15807]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 4 other plugins)

System:

   ios-deploy : 1.9.2
   NodeJS     : v10.10.0 (/usr/local/Cellar/node/10.10.0/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
After updated @ionic/angular@4.0.0-beta.12, the header of starter app still not work fine on iPhone X simulator.

**Steps to Reproduce**
1. ionic start myApp tabs --type=angular
2. npm i @ionic/angular@4.0.0-beta.12 // upgrade ionic/angular to beta.12 since `ionic start` command uses beta.7 be default
3. ionic cordova build ios --prod
4. build the app in Xcode and run it in iPhone X simulator

**Related Code**
n/a

**Expected Behavior**
It's expected to display a correct header height on iPhone X/XR/XS/XS Max.

**Additional Context**
Please find a screenshot as follow.

![image](https://user-images.githubusercontent.com/60080/46243293-436e9000-c405-11e8-85ca-c285d476133a.png)

**Comment by babaru** [comment]
This issue is indeed related to #14940 , and I tried the solution provided at the end, however there is no luck for me.

Please help on this and thank you very much in advance!

**Comment by mhartington** [comment]
This appears to be a build issue with the CSS process in Angular. Seems to be collapsing similar css selectors into one block, which is not correct. Will look into this.

**Comment by stripathix** [comment]
I am also getting same issue with Ionic CDN using with VueJs. Header is having a padding of 20px which is too close to notch.

<img width="265" alt="screen shot 2018-10-04 at 4 01 55 pm" src="https://user-images.githubusercontent.com/8480351/46468707-db49f080-c7ee-11e8-836e-b4595d907417.png">

**Comment by sbannigan** [comment]
Logged the same issue here: [#15502](https://github.com/ionic-team/ionic/issues/15502) with a temporary fix.
