### ISSUE TITLE
v4: Migrate end-to-end tests to Puppeteer

### ISSUE THREAD

**Issue by camwiegert** [ionic-team/ionic#15803]
We're moving all of the end-to-end tests from our old Selenium setup to Stencil's built-in testing tools.

- [x] action-sheet
- [x] alert
- [x] app
- [x] avatar
- [x] badge
- [x] button
- [x] card
- [x] checkbox
- [x] chip
- [x] content
- [x] datetime
- [x] fab
- [x] grid
- [x] icon
- [x] img
- [x] infinite-scroll
- [x] input
- [x] item
- [x] item-sliding
- [x] label
- [x] list
- [x] loading
- [x] menu
- [x] modal
- [x] nav
- [x] popover
- [x] radio
- [x] radio-group
- [x] range
- [x] refresher
- [x] reorder
- [x] router
- [x] searchbar
- [x] segment
- [x] select
- [x] slides
- [x] spinner
- [x] split-pane
- [ ] tabs
- [x] text
- [x] textarea
- [x] thumbnail
- [x] toast
- [x] toggle
- [x] toolbar

**Comment by brandyscarney** [comment]
:tada:
