### ISSUE TITLE
[ion-select 4.0.0-beta.12] ionFocus event didn't trigger on safari 12.0(13606.2.11) with mac

### ISSUE THREAD

**Issue by jegged** [ionic-team/ionic#15808]
# Bug Report

**Ionic Info**
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.2.3
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 3 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/Sophire/Library/Android/sdk)
   NodeJS            : v8.11.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 9.1 Build version 9B55
```
insert the output from ionic info here
```

**Steps to Reproduce**
<ion-checkbox slot="end" [(ngModel)]="entry.isChecked" (ionFocus)="logs(entry.val)"></ion-checkbox>

the ionfocus can't trigger with safari

**Comment by paulstelzer** [comment]
Thanks for the issue! Are you still seeing this problem in latest, `4.0.0-beta.17`?

**Comment by jegged** [comment]
@paulstelzer  no,it's still didn't triggerd also with install 4.0.0_rc
