### ISSUE TITLE
[v4.0.0-beta.12] ionViewDidEnter not triggered in modals

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#15806]
# Bug Report

**Ionic Info**

Ionic Angular v4-beta.12

**Describe the Bug**
Neither `ionViewDidEnter` nor `ionModalDidPresent` are triggered modals in v4-beta.12

I created a dummy project to reproduce the issue. Per default the dummy project was created with v4-beta.7 and therefore I was able to also test that effectively these events were still triggered in previous version

**Steps to Reproduce**
    
     git clone https://github.com/peterpeterparker/ionic-modal-did-enter
     cd ionic-modal-did-enter
     npm install
     ionic serve
     open the modal

**Related Code**

```
https://github.com/peterpeterparker/ionic-modal-did-enter
```

**Expected Behavior**
`ionViewDidEnter` nor `ionModalDidPresent` should be still triggered in modals too

**Comment by paulstelzer** [comment]
All of them is not valid in Ionic 4 as far as I know. You have to use the Angular lifecycle
```
    ionViewDidEnter() {
        console.log('ionViewDidEnter page');
    }

    ionViewWillEnter() {
        console.log('ionViewWillEnter page');
    }

    ionViewDidLeave() {
        console.log('ionViewDidLeave page');
    }

    ionViewWillLeave() {
        console.log('ionViewWillLeave page');
}
```

**Comment by peterpeterparker** [comment]
@paulstelzer only `ionViewDidLoad` as been replaced with Angular lifecycle. Other events still exists, for reference/example https://github.com/ionic-team/ionic/blob/37c9be7453ceb0e34b28f9c7338c77b90b626d19/core/src/index.ts

In case of the modal, see lifecycle map https://github.com/ionic-team/ionic/blob/c49d896e085278a4ece521a22d983a4fa745adc2/core/src/components/modal/modal.tsx

**Comment by paulstelzer** [comment]
I am shocked :D I do not understand why they left the lifecycles in it - ngOnInit etc are already included in Angular, so no need to leave it in

**Comment by peterpeterparker** [comment]
@paulstelzer I'm really happy they did, easier to migrate and also I think `ionViewDidEnter` and `ionViewWillEnter` are really super easy to understand, you know exactly just by the name what they those and what you could to with them

anyhow, maybe I'm totally wrong you know ;) let's see what they say

P.S.: In any case for me no rush anymore, I've already modified my upcoming app in order to not use anymore `ionViewDidEnter` in case of modal (I still really on it for some pages)

**Comment by paulstelzer** [comment]
Just use ngOnInit instead of ionViewDidEnter at modals, it's working ;)

**Comment by iharris78** [comment]
I don't think ngOnInit() takes account of the animation of the modal.

I've been trying to hook onto an event that's fired once the modal is presented (ionModalDidPresent), in order to measure some of the elements inside and do a bit of re-sizing - I always get 0 size back when doing this in ngOnInit().

For the time being, I have had to add a setTimeout of 0.5s from ngOnInit() being fired until I do the measuring to allow for the animation delay.
