### ISSUE TITLE
[v4.0.0-beta.12] ion-input unable to style - missing css vars

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#15812]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\Dylan van der Merwe\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (7 plugins total)

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
There are currently no defined css vars to style `ion-input`.

Often we will need to style inputs on specific screens, such as this:
![image](https://user-images.githubusercontent.com/2852839/46256732-f1824480-c4ae-11e8-8c57-7cc06881f29f.png)

In order to do this on v3 the styling would look as follows:
```
.item-inner {
    padding-right: 0 !important;
    border-bottom: 0 !important;
    box-shadow: none !important;

    input {
      background-color: lighten(color($colors, light, base), 1);
      border-radius: 5px;
      border: solid 1px color($colors, primary, base);
      text-align: center;
      font-size: 1.3em;
      padding: 10px;
      letter-spacing: 8px;
      color: #333;
      margin-left: 0 !important;
      margin-right: 0 !important;
      width: 100%;
    }
  }
```

As far as I can tell, there is [no way to accomplish this in v4](https://beta.ionicframework.com/docs/api/input). This becomes extremely limiting when trying to make forms look decent.

**Comment by camwiegert** [comment]
@dylanvdmerwe Thanks for your feedback. I'm able to set all of those styles, apart from padding, directly on `ion-input`:
```
ion-input {
    background-color: red;
    border-radius: 5px;
    border: solid 1px blue;
    text-align: center;
    font-size: 1.3em;
    letter-spacing: 8px;
    color: blue;
    margin-left: 10px;
    margin-right: 10px;
    width: 100%;
}
```
And padding can be set using these custom properties:
```
--padding-top
--padding-end
--padding-bottom
--padding-start
```
Could this just be a documentation issue? I'm working on documenting the input custom properties at the moment and they should get pulled into the docs with the next release.

**Comment by dylanvdmerwe** [comment]
@camwiegert Yes I think this is primarily a documentation issue. You are correct, input can be styled as per your suggestion.
