### ISSUE TITLE
v4: Fixed Background content moving with <ion-refresher>

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic#15816]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.1.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.4, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/chrisgriffith/Documents/android-sdk-macosx)
   ios-deploy        : 1.9.2
   ios-sim           : 7.0.0
   NodeJS            : v8.11.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
I have a background image set on my <ion-content>, however, when I do a pull to referesh, the <ion-content> is pushed down for this component. <ion-content fullscreen="true"> is also set. 

**Steps to Reproduce**
1. Have a page with a background image
2. Include a <ion-refresher> component
3. Pull down to expose the refresher
4. See the background image relocate.

**Related Code**
UI samples
![screencapture-localhost-8100-weather-2018-09-30-11_07_02](https://user-images.githubusercontent.com/527875/46260903-2d161200-c4a1-11e8-8fa9-084c80bbb63c.png)
![screencapture-localhost-8100-weather-2018-09-30-11_08_13](https://user-images.githubusercontent.com/527875/46260906-2f786c00-c4a1-11e8-85e9-7808c94b0b3a.png)

**Expected Behavior**
We need to have fixed ion-content content that is not moved by the ion-refresher's usage.

**Additional Context**

**Comment by crazyserver** [comment]
Something similar is happening to us. We got that report: https://tracker.moodle.org/browse/MOBILE-2742

All fixed elements inside the ion-content tag are scrollable after ion-refresh finishes.
As the report says this can be solved changing the setCss(0,...); function on the close action in the refresher component by one new function like: unsetCss that completely removes all the css inserted and leaves the styles like before starting the refresh action.

According to the current code, v4 will have the same problem: https://github.com/ionic-team/ionic/blob/master/core/src/components/refresher/refresher.tsx#L328

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you take a look if this is fixed in `@ionic/angular@beta.17`?

**Comment by crazyserver** [comment]
Code does not seem to be changed since my last message. So I think error is still there.

**Comment by paulstelzer** [comment]
It would be great if someone can create a repo for that to explore the issue.

**Comment by chrisgriffith** [comment]
https://github.com/chrisgriffith/ion-refresh-demo

**Comment by paulstelzer** [comment]
Thank you!
