### ISSUE TITLE
[v4.0.0-beta.12] show-when not working properly

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#15813]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\Dylan van der Merwe\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (7 plugins total)

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
When testing on a browser, `show-when` is always displayed. In Chrome inspect the page, and change between iPhone and Pixel devices - I would expect that this handled correctly. 

In the code below the `show-when` for `ios` is always displaying which is not right when testing in browser.
![image](https://user-images.githubusercontent.com/2852839/46257991-b9d1c780-c4c3-11e8-8665-1f713c22f758.png)

**Related Code**
```
 <ion-toolbar>
    <ion-buttons *ngIf='step > 1 && !checking && step < 3' slot='start'>
      <ion-show-when mode='ios'>
        <ion-button (click)='back()'>
          <ion-icon name='arrow-back' class='back-button-icon-ios'></ion-icon> Back
        </ion-button>
      </ion-show-when>
      <ion-show-when mode="android,windows,core,mobileweb">
        <ion-button (click)='back()'>
          <ion-icon name='arrow-back' class='back-button-icon-md'></ion-icon>
        </ion-button>
      </ion-show-when>
    </ion-buttons>
```

**Expected Behavior**
`show-when` should work properly when inspecting in a browser. Same behaviour expected for `hide-when`.

**Comment by OJ7** [comment]
This seems to only be for "mode" which looks like it always evaluates to true. You can see here for [hide-when](https://beta.ionicframework.com/docs/api/hide-when) that it is always hidden for "mode".

@dylanvdmerwe, I noticed in your example that you have `mode="android,windows,core,mobileweb"` which I think should be `platform="android,windows,core,mobileweb"`

**Comment by manucorporat** [comment]
@OJ7  you are correct!
