### ISSUE TITLE
When i am doing:  npm install --save @ionic-native/image-picker i get an error

### ISSUE THREAD

**Issue by benag** [ionic-team/ionic#15821]
UNMET PEER DEPENDENCY @angular/core@5.2.11
└── @ionic-native/image-picker@4.15.0

**Comment by benag** [comment]
also when i include ImagePicker in imports i get white screen  when i run on device.

import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import { ListPage } from '../pages/list/list';
import { RegisterPage } from '../pages/register/register';
import { FeedPage } from '../pages/feed/feed';
import { HealerProfilePage } from '../pages/healer-profile/healer-profile';
import { UserProfilePage } from '../pages/user-profile/user-profile';
import { HttpClientModule } from '@angular/common/http';
import { IonicStorageModule } from '@ionic/storage';

import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { GlobalProvider } from '../providers/global/global';
import { ConditionsProvider } from '../providers/conditions/conditions';
import { PracticesProvider } from '../providers/practices/practices';
import { UsersProvider } from '../providers/users/users';

import { Ng4GeoautocompleteModule } from 'ng4-geoautocomplete';
import { ImagePicker } from '@ionic-native/image-picker';


@NgModule({
  declarations: [
    MyApp,
    HomePage,
    ListPage,
    RegisterPage,
    FeedPage,
    HealerProfilePage,
    UserProfilePage
  ],
  imports: [
    BrowserModule,
    HttpClientModule,
    IonicModule.forRoot(MyApp),
    IonicStorageModule.forRoot(),
    Ng4GeoautocompleteModule.forRoot(),
    ImagePicker
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    ListPage,
    RegisterPage,
    FeedPage,
    HealerProfilePage,
    UserProfilePage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler},
    GlobalProvider,
    ConditionsProvider,
    PracticesProvider,
    UsersProvider
  ]
})
export class AppModule {}

**Comment by brandyscarney** [comment]
The first log is a warning, `UNMET PEER DEPENDENCY @angular/core@5.2.11` is saying you need to have that version of `@angular/core` installed as a peer dependency. 

The white screen could be caused by any number of things, please check out the posts on our forums for more assistance: https://forum.ionicframework.com/search?q=white%20screen

Thanks!
