### ISSUE TITLE
[v4.0.0-beta.12] ion-select popover radio styling

### ISSUE THREAD

**Issue by dgerritsen** [ionic-team/ionic#15827]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/Users/***/.nvm/versions/node/v10.1.0/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-webview 2.1.4, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/***/Library/Android/sdk/)
   ios-deploy        : 1.9.2
   NodeJS            : v10.1.0 (/Users/***/.nvm/versions/node/v10.1.0/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
I'm unable to style the radio button in an ion-select popover. 

**Steps to Reproduce**
1. Create an ion-select with interface="popover"
2. Generate different styles for the ion-select radio button
3. See the radio still has default styling applied

**Related Code**
```
<ion-select [interfaceOptions]="" interface="popover" placeholder="None">
      <ion-select-option value="-" selected>None</ion-select-option>
      <ion-select-option value="1">Printer 1</ion-select-option>
      <ion-select-option value="2">Printer 2</ion-select-option>
</ion-select>
```

```
* {
  --ion-color-base: #75D154;
  --color-checked: #75D154;
}

:host(.radio-checked) .radio-icon {
  border-color: #75D154!important;
  --color-checked: #75D154;
}

ion-radio, ion-select-popover, .radio-icon, .radio-checked {
  border-color: #75D154!important;
  --color-checked: #75D154;
}
```

**Expected Behavior**
I expect the radio button in the popover list to be the specified color (#75D154) instead of the default.

**Additional Context**
Not available.

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)

**Comment by dgerritsen** [comment]
@paulstelzer As far as I can tell this still seems to be an issue.

**Comment by dgerritsen** [comment]
@paulstelzer 
Thanks for your response!
With your explanation I've managed to get the desired result.
However, this doesn't really feel like a logical way to do it.

What's the point of modular styling, e.g. a stylesheet for each component, if some styles are only to be assigned globally? In my current application I'm using different colors for different modules. 
I thinks it's very useful to define the ion-primary-color in the module stylesheet, and import the stylesheet in each of the module's components. This makes it easy to change colors and enforces DRY.

Placing some of the styling in a global stylesheet completely defeats this purpose. 
Wouldn't it be better to make inheritance possible in some way?

**Comment by paulstelzer** [comment]
It's the way a popover works (the same like a toast). These controllers are always out of the scope of a component. If you don't like it, open a new issue and choose "Feature Request". Then a member of the dev team can say more about it :)
