### ISSUE TITLE
Different behavior for .swiper-wrapper in rtl mode.

### ISSUE THREAD

**Issue by Daithi1** [ionic-team/ionic#15823]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (C:\Users\david.synnott\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v10.10.0
    npm               : 6.4.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\david.synnott\AppData\Local\Android\Sdk

Misc:

    backend : pro
```

**Describe the Bug**
Bug mightn't be the best description, more like unusual and annoying behavior.

div.swiper-wrapper which is the direct parent of any ion-slide inside ion-slides sets it's width differently in RTL mode.

**Steps to Reproduce**
Set up some ion-slides in horizontal slide mode (default), note .swiper-wrapper width. Change to RTL mode (might need to reinitialize component).

**Related Code**
https://github.com/ionic-team/ionic/blob/c463b065c79481939de958ec6eb9c7827c62ec2f/src/components/slides/swiper/swiper.ts#L494-L504

**Expected Behavior**
I would expect the width to be the same on RTL and LTR.

**Additional Context**

**Comment by abennouna** [comment]
Is it the same behavior when the document is originally in RTL mode? In our case, with automatic slides per view / carrousel mode, the only workaround is to reload the page after LTR/RTL direction change. Otherwise, swiping itself is messed up.

**Comment by Daithi1** [comment]
This behaviour happens regardless of the original direction.
