### ISSUE TITLE
[v4-beta.12] Chrome & Firefox have different styles

### ISSUE THREAD

**Issue by sergiomilici** [ionic-team/ionic#15830]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

System:

   NodeJS : v10.11.0 (/Users/chicho/.nvm/versions/node/v10.11.0/bin/node)
   npm    : 6.4.1
   OS     : macOS High Sierra
```

**Describe the Bug**
Android and Firefox have different styles. Both browsers seem to be loaded in `md` mode based on styles and node `html[mode="md"]`. The problem is that Firefox adds classes like if it was on Android.
For example, check the 2 images for the `ion-tabbar` which have different classes on each browser.
This happens with almost all ion-components, like `ion-avatar`, `ion-content`, etc.

Chrome

![ion-tabbar-chome](https://user-images.githubusercontent.com/2365168/46371428-320fc880-c63d-11e8-9329-c6b1dad1723c.png)

Firefox

![ion-tabbar-firefox](https://user-images.githubusercontent.com/2365168/46371724-017c5e80-c63e-11e8-8d11-f648da68abd4.png)

**Steps to Reproduce**
1. Create a new project like `ionic start myApp tabs --type=angular`
2. Open dev tools and inspect the elements

**Related Code**
No code changes needed.

**Expected Behavior**
I assume the default platform is android, so android classes should be loaded in chrome too.
Both browsers should show the same.

**Additional Context**
In Safari, it behaves exact as Chrome, loading `md` styles.

**Comment by manucorporat** [comment]
Firefox does not support shadow-dom, meaning the shadow-dom polyfill kick in adding that classes.

**Comment by sergiomilici** [comment]
Thanks for the quick response.
