### ISSUE TITLE
Ionic 4  - Add feature to pass css to ionic components

### ISSUE THREAD

**Issue by dhsont** [ionic-team/ionic#15841]
**It is not easy to customise components design**
   It is tough to work with shadow dom, we can't change components behaviour, we can only change its colour with variables.

It is nearly impossible to select individual element , change their size , border, border thickness, etc.
or we have to create our own component which is also extra work for developer. 
So it is setback for app designing.  

**Solution for this**
As we can pass attributes to components we should allow css to be passed while calling components.
this way it still has advantages of shadow dom as wel as it gives flexibility to change appearance easily as user wants.

ex.
Instead of this
~~~
<ion-button shape="round" color="primary" fill="outline">Hello World</ion-button>
~~~
we can use this
~~~
<ion-button shape="round" css="color:primary ; border:1px solid green">Hello World</ion-button>
~~~

**Comment by comfortme** [comment]
I agree. Since you cant target shadow dom, passing a class to manipulate it would be fine also.

**Comment by mhartington** [comment]
Hi there! This is not something we want to support. Many aspects of Ionic's components and their styles are accessible through vanilla CSS alone, without modifying css variables.

https://github.com/ionic-team/ionic/issues/15812#issuecomment-426782663

This is more of a documentation issue with V4-beta. If you had some docs that could show how to modify components, would that be helpful?

**Comment by brandyscarney** [comment]
Thanks for the feedback! Could you explain further where you are running into problems? You can set the border on a button by using the available custom CSS properties, for example:

```html
<ion-button 
  shape="round" 
  style="--border-width: 10px; --border-style: solid; --border-color: green">
    Hello World
</ion-button>
```

Results in:

<img width="174" alt="screen shot 2018-10-03 at 4 34 40 pm" src="https://user-images.githubusercontent.com/6577830/46437858-57c6cb80-c72a-11e8-953c-7195d0d91cb7.png">

You can also customize the properties via JavaScript by using `setProperty()`. More on that here: https://beta.ionicframework.com/docs/theming/css-variables#variables-set-via-javascript 

There is a custom properties section for the components that have them in their API reference, button's is here: https://beta.ionicframework.com/docs/api/button#css-custom-properties

I recommend reading through our [Theming documentation](https://beta.ionicframework.com/docs/theming/basics), especially the [Advanced](https://beta.ionicframework.com/docs/theming/advanced) section to get a better understanding of custom properties. 🙂 

I would love to hear more on what all you are customizing though so we can make sure to have variables available, as well as where you think we could improve our documentation. Thank you!

**Comment by manucorporat** [comment]
We are not doing this at this point, the whole point of shadow-dom is to avoid developers messing with internal parts, this way we can maintain ionic without breaking users.

If something is not customizable about a component, please open an issue or a PR adding proper CSS variables
