### ISSUE TITLE
ion-modal source code link is missing

### ISSUE THREAD

**Issue by agnaveen** [ionic-team/ionic#15843]
Hi team,

I am trying to use ion-modal from beta v4, but the provided link seems broken,

https://github.com/ionic-team/ionic/tree/master/core/src/components/components/modal/test/preview/index.html

Could you please help me with the source code link ?

**Comment by paulstelzer** [comment]
Yes, that's another issue inside the ionic-docs. There is an additional 'components' path, so just remove one and it works -> https://github.com/ionic-team/ionic/blob/master/core/src/components/modal/test/preview/index.html -

Isseu at ionic-docs: https://github.com/ionic-team/ionic-docs/issues/132
