### ISSUE TITLE
[4.0.0-beta.12] ion-button with color is white when wrapped in stencil component with Shadow DOM enabled

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic#15863]
# Bug Report

**Versions**

```
"@ionic/core": "4.0.0-beta.12"
"@stencil/core": "0.13.2"
```

**Describe the Bug**

When creating a Stencil component with Shadow DOM enabled and using an `ion-button` within it with the `color` attribute set, the button has white text on white background.

<img src="https://user-images.githubusercontent.com/3410759/46514720-09493680-c8bc-11e8-8347-fa2deda52db0.png" width="164">

**Steps to Reproduce**

1. Create a new Stencil component with Shadow DOM enabled
2. Use an `ion-button` in it
3. Set the `color` attribute

**Related Code**

```tsx
// my-component.tsx

@Component({ tag: 'my-component', shadow: true })
export class MyComponent {
  render() {
    return <ion-button color="primary">A Button</ion-button>;
  }
}
```

```tsx
// some-page.tsx

@Component({ tag: 'some-page' })
export class SomePage {
  render() {
    return <my-component />;
  }
}
```

**Expected Behavior**

The button should still look like a button when adding the `color` attribute. Removing `shadow: true` fixes it:

<img src="https://user-images.githubusercontent.com/3410759/46515292-67c3e400-c8bf-11e8-8edd-735744f730df.png" width="142">

**Additional Context**

It works when disabling Shadow DOM on the component. Maybe it has something to do with how CSS variables are passed through Shadow DOMs?

BTW, the button is also aligned to the center when enabling Shadow DOM but left when not.

**Comment by brandyscarney** [comment]
Thanks for the issue! This is unfortunately a problem for any components using `color` inside of a 
 Shadow DOM component because the CSS to change the colors is not passed down. It is related to https://github.com/ionic-team/ionic/issues/14840.

cc @manucorporat

**Comment by manucorporat** [comment]
Yep, definitively a duplicated of https://github.com/ionic-team/ionic/issues/14840

We recommend to use `scoped` or no encapsulation when using Ionic
