### ISSUE TITLE
Variable used to set ion-item's border color is different in ios & md

### ISSUE THREAD

**Issue by contactjavas** [ionic-team/ionic#15864]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI) : 4.1.2

System:

   NodeJS : v10.11.0
   npm    : 6.4.1
   OS     : Windows 10
```

**Additional Context**
Im using chrome devtools to check ios & md. So, what i mean with ios is chrome with ios device mode. And what i mean with md is chrome devtools with android device mode.

So, it's not about `mode="ios"` or `mode="md"` 😀 

**Describe the Bug**
Variable used to set `ion-item`'s border color is different in ios & md.

- in ios: it uses `--ion-item-border-color` (as expected, this is the semantic naming)
- in md: it uses `--border-color` (it's too broad compared to `--ion-item-border-color`)

**Steps to Reproduce**
1. Create list (complete with: `ion-list`, `ion-list-header`, `ion-item`, `ion-thumbnail`, and `ion-label`)
2. Set `ion-list` item to use `lines="true"`
3. Try to change the border using `--ion-item-border-color`. It will only affect ios mode.

**Related Code** (I cut & modify the codes, just to be simple)
The markups
```
<ion-list lines="full" padding class="product-list">
    <ion-list-header>
      <ion-label>
        Electrical mechanics
      </ion-label>
    </ion-list-header>
    <ion-item detail="false" href="/products/1" routerDirection="forward">
      <ion-thumbnail slot="start">
        <img alt="AC" src="assets/images/icons/icon-ac-min.png">
      </ion-thumbnail>
      <ion-label>AC</ion-label>
    </ion-item>
</ion-list>
```
The scss
```
.product-list {
  ion-item {
    --ion-item-border-color: var(--ion-color-light);
    // patch: i need this to override md mode.
    --border-color: var(--ion-color-light);
  }
}
```

**Expected Behavior**
In [this documentation page](https://beta.ionicframework.com/docs/theming/advanced/), there is `--ion-item-border-color` variable available. That means, the `ion-item` should be using **it** instead of using `--border-color` which is too general.
It's already correct in ios, but not in md.

**Comment by brandyscarney** [comment]
Thank you for the issue! This will be fixed in `4.0.0-beta.14` by this PR: https://github.com/ionic-team/ionic/pull/16003. See the *Changed Values* section for which variables/fallbacks are used for each mode. Please note the renamed CSS variables. 🙂
