### ISSUE TITLE
Ion-refresher stops working when navigating between pages

### ISSUE THREAD

**Issue by harikvpy** [ionic-team/ionic#15861]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\hari\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.4, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (c:\androidsdk)
   NodeJS            : v8.11.2 (C:\Program Files (x86)\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10
```

**Describe the Bug**
When an app has two pages with ion-refresher, both displaying multiple objects (using cards, in this case), the refresher only works for the first page. When navigated to the second page with refresher, pulling the page down does not cause refresher to be activated.

**Related Code**
Please see the sample project [here](https://github.com/harikvpy/ionic4app1) 

**Expected Behavior**
Page refresher should work on all pages where it's defined.

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
