### ISSUE TITLE
No Type Definitions available

### ISSUE THREAD

**Issue by michaelcamper** [ionic-team/ionic#15867]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.2.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.1.0
   @ionic/schematics-angular  : 1.0.7

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v8.12.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS

```

**Describe the Bug**
There are no type definitions available for components` in WebStorm.

**Steps to Reproduce**
1. Setup a new project
2. Import a component (eg: `import { ModalController } from '@ionic/angular';`)
3. Create a modal
4. Try to access the `present` method

**Expected Behavior**
Being hinted with available object properties and methods.

**Comment by alan-albuquerque** [comment]
Hi! I realized this also when I updated to the BETA.12 version, mainly the components in the template were highlighted and when you put the mouse on it says something like "Unidentified component"

**Comment by michaelcamper** [comment]
It is the [snippet](https://beta.ionicframework.com/docs/api/modal/#usage) from the new beta docs.
It works perfectly but there is no support for IntelliSense.

Here you find a demo:

![demo](https://user-images.githubusercontent.com/39185098/46569606-0b60d300-c958-11e8-9f52-a93b5fb8cbd4.gif)

**Comment by paulstelzer** [comment]
Maybe a webstorm editor issue? In VS Code everything works as expected
![code_2018-10-06_14-33-25](https://user-images.githubusercontent.com/20501666/46571408-d9119e80-c974-11e8-8d86-f31b9ef52b1c.jpg)

**Comment by alan-albuquerque** [comment]
@paulstelzer are you in version beta.12?

**Comment by paulstelzer** [comment]
yes

**Comment by michaelcamper** [comment]
@paulstelzer That's weird, because it works perfectly when using Ionic 3, so I'd expect that to work in v4 as well.
<img width="617" alt="screenshot 2018-10-06 at 16 13 57" src="https://user-images.githubusercontent.com/39185098/46572276-44626d00-c983-11e8-81c2-26d9f3708405.png">

**Comment by DavidDudson** [comment]
@michaelcamper have you tried invalidating caches and reloading? It works for me in Webstorm.
