### ISSUE TITLE
[4.0.0-beta.12] index theme color does not match --ion-color-primary

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#15872]
# Bug Report

**Ionic Info**
```

Ionic:

   ionic (Ionic CLI)          : 4.2.0 (C:\Users\Dylan van der Merwe\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 12 other plugins)

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
When you create a blank project, the following files are added:
 - manifest.json
 - variables.scss
 - index.html

In index.html there is a theme-color tag that does not match the new `--ion-color-primary` variable.

```
  <meta name="theme-color" content="#1976d2">
```

**Comment by brandyscarney** [comment]
Thank you for the issue! Could you tell me what steps you're taking to get this? 

I tried reproducing but I am seeing the following when creating a blank starter using v3:

```
<meta name="theme-color" content="#4e8ef7">
```

and I am not seeing this entry at all in v4, which matches the index file here: https://github.com/ionic-team/starters/blob/master/angular/base/src/index.html

**Comment by dylanvdmerwe** [comment]
Hmmm, this must come from the `ng add @angular/pwa` command then. 

![image](https://user-images.githubusercontent.com/2852839/46562614-3833cc80-c8fd-11e8-8c1c-61a6ce925862.png)

**Comment by paulstelzer** [comment]
> Hmmm, this must come from the `ng add @angular/pwa` command then.

Yes, this files were generated by `@angular/pwa` because they are needed for a PWA and in the meta tag you have to use a valid css color -> https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android
