### ISSUE TITLE
Tabs with all the nested pages with lazy loading ion-content doesn't render

### ISSUE THREAD

**Issue by alexverdaguer** [ionic-team/ionic#15877]
When I create a tabs page with all the pages with lazy loading, the <ion-content> of every page doesn't render, just renders the <ion-header> just above the tabs section.

If I import the page with regular components works just fine.

<img width="1012" alt="captura de pantalla 2018-10-06 a las 11 16 07" src="https://user-images.githubusercontent.com/8429850/46569716-41528700-c959-11e8-901e-78f709b2ba7f.png">

Is this behaviour correct ?

**Comment by orlyapps** [comment]
same issue here
