### ISSUE TITLE
[4.0.0-beta.12] Change detection with ion-list and AlertController

### ISSUE THREAD

**Issue by szerner** [ionic-team/ionic#15871]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.2.0 (C:\Users\Stephan\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.1.0
   @ionic/schematics-angular  : 1.0.7

System:

   NodeJS : v10.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
Change detection doesn't fire when adding items to an `<ion-list>` using an Alert component.

**Steps to Reproduce**
Create a dynamically generated <ion-list> and use an overlay component (i.e. Alert) to add an` <ion-item>` to the list. The item doesn't display but after clicking on any other UI element.

See my github example (below):
The left button directly adds an item to the list (using a service), and the item is immediately shown.
The right button triggers an Alert Component to show up for the input and adds the item too, but the new item is only shown after clicking one of either buttons again.

For debugging purposes the service logs the actual item list to the console after adding an item.

**Related Code**
https://github.com/szerner/ionic4-change-detection.git

**Expected Behavior**
The list should reflect changes to the `<ion-list>` immediately after adding new items.

**Additional Context**
Perhaps it is related to issue #15855.

**Comment by szerner** [comment]
Hi @bkarv,
thank you for your workaround, though I will wait for a 'official' bug fix (if there ever will be one...).

As I want to have a loose coupling between my components, they shouldn't be dependent on some sort of event exchange for the mere purpose of sharing the same data (I would have to call `this.changeRef.detectChanges()` explicitly when the service or modal component changes the data). 
That's we have Observables for.

But thanks again, it's good to know a work around if there is no other long term solution.

**Comment by manucorporat** [comment]
This issue should be fixed in next release!
