### ISSUE TITLE
Beta 12 - Ion Content Overflow. Content is not rendering.

### ISSUE THREAD

**Issue by oberoivarun** [ionic-team/ionic#15873]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.2.0 (C:\**\**\**\**\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Android\android-sdk)
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10
```

**Describe the Bug**
Content beyond viewport is not rendering inside `ion-content` tag.

**Steps to Reproduce**

1. Add `*ngFor` to an ion-card element inside an ion-content tag. Add a 20-25 elements in the array variable. And `ionic serve` .

I have my content routed to another component using:

```
<ion-content [forceOverscroll]="'true'" [scrollY]="true">
    <div class="ion-page">
        <ion-router-outlet></ion-router-outlet>
    </div>
</ion-content>
```
I have tried combinations of options and properties using the docs. But overflow content does not render.

**Expected Behavior**
It should render beyond the viewport and should allow scrolling along y-axis.

**Comment by paulstelzer** [comment]
Thanks for your issue! Unfortunatly I don't understand what the problem is. Could you please add a repo to reproduce thie issue and add screenshots?
