### ISSUE TITLE
[Ionic V4.0.0-beta.12] [ios] [ion-searchbar] showCancelButton has style issue in RTL

### ISSUE THREAD

**Issue by samirebrahim** [ionic-team/ionic#15884]
# Bug Report

**Ionic Info**
Ionic:

ionic (Ionic CLI) : 4.1.2 (/usr/local/lib/node_modules/ionic)
Ionic Framework : @ionic/angular 4.0.0-beta.12
@angular-devkit/core : 0.8.4
@angular-devkit/schematics : 0.8.4
@angular/cli : 6.2.4
@ionic/ng-toolkit : 1.0.8
@ionic/schematics-angular : 1.0.6

**System**
NodeJS : v10.1.0 (/usr/local/bin/node)
npm : 6.4.1
OS : macOS High Sierra

**Describe the Bug**
on [ios] RTL cancel button on searchbar dosent have padding-right
![localhost_8100_home iphone 5_se 1](https://user-images.githubusercontent.com/15379533/46580043-9360de80-ca25-11e8-9526-691adafe4b9f.png)

 

**Additional Context**
Searchbar has this styling 
`.searchbar-cancel-button.sc-ion-searchbar-ios { 
      padding: 0 0 0 8px;
}`
**Expected Behavior**

When switching to  RTL it should be 
`.searchbar-cancel-button.sc-ion-searchbar-ios { 
      padding: 0 8px 0 0;
}`

**Comment by abennouna** [comment]
The searchbar, as other components, has several issues in RTL. In your screenshot shows the wrong position of the search icon as well: it should be on the right side.

**Comment by paulstelzer** [comment]
I close this here because @abennouna has a nice list of RTL issues here -> #17012
