### ISSUE TITLE
[v4 feature] export all types definitions

### ISSUE THREAD

**Issue by paulsouche** [ionic-team/ionic#15889]
# Feature Request

**Ionic Info**
I don't use ionic-cli sorry

**Describe the Feature Request**
Export all types from `@ionic/core`

For example

![image](https://user-images.githubusercontent.com/5860504/46606582-f6be3f80-cafd-11e8-81d9-db59f365ca8a.png)

But it's [here](https://github.com/ionic-team/ionic/blob/0983f95d9f9f01bf17e573c5757d66e56b57dae5/core/src/components/datetime/datetime-util.ts#L462)

**Describe Preferred Solution**
Any interface / type / declaration, ... should be exported

Thank you for the great job anyway !

**Comment by manucorporat** [comment]
Please, can you explain your use case for `LocateData`?

**Comment by paulsouche** [comment]
Hi,

When I use an `ion-datetime` for example

```html
<ion-datetime
  [cancelText]="'cancel' | translate"
  [displayFormat]="localeData.dateFormat"
  [doneText]="'ok' | translate"
  [formControlName]="control.formControlName"
  [monthNames]="localeData.monthNames"
  [monthShortNames]="localeData.monthShortNames"
>
</ion-datetime>
```

I have a property `localeData` in my component and I don't want to type it as `any` but `LocaleData`...

Anyway, this issue is not about `LocaleData` only, there are lot of utils typings available privately that can't be used... I just wonder why ??

Thanks

**Comment by drekinov** [comment]
issue is as simple as autocomplete not working in phpstorm / webstorm 

```typescript
const modal = await this.modalController.create({
                component: ModalPage,
            });
```
`modal` is not autocompleted anyway .. phpstorm states that modal is "HTMLIonModalElement" which has nothing from everything really available at `@ionic/core/dist/types/components/modal/modal`.
Not possible to use that typehint because then complier complain about Modal not beeing HTMLIonModalElement. In ionic 3 project which i am migrating typehinting is perfect.

**Comment by manucorporat** [comment]
@drekinov the looks like a different issue, could you please open a new issue?

I am closing this issue since LocaleData is an internal interface used by ionic, and does not have anything to do with the public API of ionic, LocaleData could change at any time.

**Comment by paulsouche** [comment]
Hi,

Sorry but I'm not OK with this... LocaleData is used [here](https://github.com/ionic-team/ionic/blob/0983f95d9f9f01bf17e573c5757d66e56b57dae5/core/src/components/datetime/datetime.tsx#L21) and as I said it's really usefull to have this type public (please see examples above).

> LocaleData could change at any time.

Right ! And hopefully I will detect changes using this interface as I won't by copy pasting it.

But anyway this is not about LocaleData only here, this is about lot of typings that could be exported for free. And again, if this typings could change any time, it's better to detect it.

Thanks
