### ISSUE TITLE
[Ionic V4.0.0-beta.12] minor ui fix - footer height in sidemenu with tabbar height

### ISSUE THREAD

**Issue by not-a-designer** [ionic-team/ionic#15887]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.
```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (%APP_DATA%\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.2.3
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : none
   Cordova Plugins       : cordova-plugin-ionic-webview 2.1.4, (and 3 other plugins)

System:

   Android SDK Tools : 26.1.1 (F:\adt-bundle-windows-x86-x64\sdk)
   NodeJS            : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Describe the Bug**
ion-footer height in the ion-menu/split pane is not the same height as the tabs bar in the main ion-router-outlet

**Steps to Reproduce**
1. add tabs to a sidemenu project (create both and copy paste the tabs +3 child tab  page folder into your sidemenu and update the routes
2. add `<ion-split-pane>`
3. add  to the `<ion-menu>`:
```
<ion-footer>
    <ion-toolbar></ion-toolbar>
</ion-footer>
```

4. open in browser past md/lg breakpoint

**Related Code**

**APP.COMPONENT.HTML**
```
<ion-split-pane>
    <ion-menu #mainMenu>
        <!-- menu content -->
        <ion-footer>
            <ion-toolbar>
            </ion-toolbar>
        </ion-footer>
    </ion-menu>
    <ion-router-outlet main></ion-router-outlet> <!-- TABS PAGE -->
```
**TABS.PAGE.HTML**
```
<ion-tabs>
    <ion-tab icon="home" href="/tabs/home">
        <ion-router-outlet stack name="home"></ion-router-outlet>
    </ion-tab>
    ....
```

**Expected Behavior**
if the app contains a ion menu with a footer and a tab bar, there should be no difference in height between the 2 and the top border should be 1 smooth continuous line

**Additional Context**
[screenshot(imgur)](https://imgur.com/a/MFvun8x)

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
