### ISSUE TITLE
ion-select triggers a ionChange event when the list of options are updated.

### ISSUE THREAD

**Issue by VinitSarvade** [ionic-team/ionic#15885]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.2.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.2.3
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.7
   @capacitor/core           : 1.0.0-beta.7

System:

   NodeJS : v9.11.2 (/usr/local/bin/node)
   npm    : 5.6.0
   OS     : macOS
```

**Describe the Bug**
I have a ion-select which by default has no options. The options are dynamically added on a API response. On updating the options, the `ionChange` event is triggered even though there is no value being selected. It does trigger the event after a value selection, but the initial change event when no value is selected just because the options were updated, is not desirable.

**Expected Behavior**
`ionChange` event must be triggered only when an option is selected, not when the options list are updated dynamically.

**Comment by paulstelzer** [comment]
Thanks for your issue! I know this issue is older, but at #16453 are some more information, so I close this here
