### ISSUE TITLE
[Ionic v4] [ios] Cookies are not passed when loading components chunk files

### ISSUE THREAD

**Issue by sneko** [ionic-team/ionic#15894]
Hi!

I'm using the 4.0.0-beta.12.

I'm not using the remote Ionic files from your CDN, I stored the `@ionic/core` within my app folder. Like that when deploying the app on Android or whatever, it's not doing remote requests.

Everything was working well until I test my app on browsers on iOS (Safari AND Chrome)... blank page 😢 . I was able to debug it by looking at network calls and I figured out that the requests to load components chunk files were not including cookies (that are required to access my protected development environment).

Since they are loaded through a script, it's like CORS requests. The HTTP client need to have `withCredentials: true` or something similar.

What's weird in my case is that when looking at networks call for my Desktop browsers and my Android browsers, they are including cookies to do these remote calls.

I'm totally lost... Why this is happening just on iOS hmmm...? Anyone could help with this issue please?

BTW: I already asked on Slack but never received any answer, is it possible to do something like `import '@ionic/core'` inside the top script of my App instead of dealing with `<script>` tag and related static folder? Like that it would be included in my bundled script (except components?)... Same question for `<style>` tag.

Thank you,

**Comment by sneko** [comment]
Any thoughts @mhartington @mlynch?

**Comment by godenji** [comment]
@sneko see here for the gory details: https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/22

If you can ignore iOS 10 then you might be able to continue using cookies; otherwise, switch to JWT + native/local storage to workaround the issue.
