### ISSUE TITLE
[Ionic v4.0.0-beta.12] Router redirectTo not working when not using lazy loading

### ISSUE THREAD

**Issue by johneast** [ionic-team/ionic#15896]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.12
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : 1.0.0

System:

   NodeJS : v8.9.3 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Sierra
```

**Describe the Bug**
Router redirect is not working when the target route is not using the `loadChildren` property but is instead referencing the component directly. This results in the wrong page being displayed, sometimes bypassing the auth guard altogether

**Steps to Reproduce**

1. Create a simple application with some basic routes. Critically the root should redirect to some other route and that route should not use lazy loading but should instead reference the component directly.

```typescript
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { AuthGuardService } from './auth-guard.service';
import { HomePage } from './home/home.page';
import { LoginPage } from './login/login.page';

const routes: Routes = [
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: 'home', component: HomePage, canActivate: [AuthGuardService] },
  { path: 'login', component: LoginPage}
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

The auth guard simulates checking a valid authentication session by introducing a 2s delay and then failing. A redirect to `login` then occurs.
```typescript
import { Injectable } from '@angular/core';
import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot, Router } from '@angular/router';

@Injectable({
  providedIn: 'root'
})
export class AuthGuardService implements CanActivate {

  constructor(public router: Router) { }

  canActivate(next: ActivatedRouteSnapshot,
    state: RouterStateSnapshot): Promise<boolean> {
      console.log('Checking auth...');
      return new Promise(res => setTimeout(() => {
        console.log('Auth check failed');
        this.router.navigate(['/login']);
        res(false);
      }, 2000));
  }
}
```

app.component.html
```html
<ion-app>
  <ion-router-outlet></ion-router-outlet>
</ion-app>
```

home.page.html
```
<ion-header>
  <ion-toolbar>
    <ion-title>
      Ionic Blank
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content padding>
  The world is your oyster.
  <p>If you get lost, the <a target="_blank" rel="noopener" href="https://ionicframework.com/docs">docs</a> will be your guide.</p>
</ion-content>
```

login.page.html
```html
<ion-header>
  <ion-toolbar>
    <ion-title>Login</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content padding>
<p>This is the login page</p>
</ion-content>
```

2. Serve the application. Navigating to `http://localhost:8100` the contents of the home page are displayed. The expectation here would be the auth guard is invoked, which should cause a redirect to the `login` page. Checking the console there is no sign of the log entries expected. Also checking the address bar it can be seen that no redirect has occurred and the app is still 'at' `http://localhost:8100`

3. Navigate to `http://localhost:8100/home` manually, the auth guard is invoked and the login page is displayed.

**Expected Behavior**
Navigating to `http://localhost:8100` should redirect to `/home` and this should invoke the auth guard.

**Additional Context**
Setting up similar routes in a plain Angular application works. Also setting up routes in the Ionic app with lazy loading works. For instance, the following works:
```typescript
const routes: Routes = [
   { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: 'home', loadChildren: './home/home.module#HomePageModule', canActivate: [AuthGuardService] },
   { path: 'login', loadChildren: './login/login.module#LoginPageModule' }
];
```

**Comment by dimalahbal** [comment]
i have other issue , i add this auth garde to my app , it's work fine untill i click the back button , the home page show up

**Comment by paulstelzer** [comment]
If you have another issue, please open a new one and please add a repo so we can check

**Comment by johneast** [comment]
I've checked this with rc0 and can confirm it is no longer an issue. Thanks.
