### ISSUE TITLE
Having both md and ios style mode for ion-list/ion-item results in issue

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [ionic-team/ionic#15891]
# Bug Report

In my application, I am using `md` mode for `ion-list/ion-item` in sidemenu.
Also, in one of my page, i am using ion-list without any mode settings.

When I run this in ios device, i can see that only `md` mode styles are loaded and thus `ion-list` inside my page is broken.

**Ionic Info**

```
Ionic:

ionic (Ionic CLI) : 4.1.2 (/usr/local/lib/node_modules/ionic)
Ionic Framework : @ionic/angular 4.0.0-beta.12
@angular-devkit/core : 0.8.4
@angular-devkit/schematics : 0.8.4
@angular/cli : 6.2.4
@ionic/ng-toolkit : 1.0.8
@ionic/schematics-angular : 1.0.6

System:

NodeJS : v10.1.0 (/usr/local/bin/node)
npm : 6.4.1
OS : macOS High Sierra
```

**Describe the Bug**

**Steps to Reproduce**
1. Add ion-list with mode='md' in sidemenu
2. Add one more ion-list without any mode specified in a lazyloaded module/page
3. Open application in ios device
4. List inside lazy-loaded page will not have styling

**Expected Behavior**
We should be able to use both the modes in single app.

Here we can see that list in sidemenu list is working , but not working with ios mode in page

![mmain-qa talabat com_list iphone 6_7_8](https://user-images.githubusercontent.com/5632217/46608370-3dfffc80-cb0d-11e8-8cbc-7ba736f8f5e9.png)

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
