### ISSUE TITLE
[v4.0.0-beta.12] sc-ion-* style class added to ion-elements in Firefox only => difficult to style across browsers

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#15908]
# Bug Report

**Ionic Info**
Ionic Angular v4-beta.12

**Describe the Bug**
sc-ion-* style class are added to ion-elements in Firefox only. This has for effect that the cascaded CSS are then different only in Firefox which makes it difficult to style the app across browsers

**Related Code**

For example, Chrome and Safari rendered navbar:

    <ion-header class="header header-md hydrated">
       <ion-toolbar class="hydrated">

Firefox rendered navbar:

    <ion-heaver class="header header-md hydrated">
       <ion-toolbar class="sc-ion-toolbar-md-h hydrated">

**Expected Behavior**
I would except a consistent CSS style class behavior across browsers. In best case I would be happy that style class would behave for Firefox like for Safari and Chrome because I would be happy to not restyle again my app ;)

**Additional Context**

Chrome:

<img width="959" alt="capture d ecran 2018-10-10 a 08 23 00" src="https://user-images.githubusercontent.com/16886711/46716825-cee9eb80-cc65-11e8-805f-d46587655d72.png">

Safari:

<img width="1260" alt="capture d ecran 2018-10-10 a 08 23 28" src="https://user-images.githubusercontent.com/16886711/46716847-dc06da80-cc65-11e8-96bc-a4952fbbdc39.png">

Firefox:

<img width="1409" alt="capture d ecran 2018-10-10 a 08 22 30" src="https://user-images.githubusercontent.com/16886711/46716874-f9d43f80-cc65-11e8-8498-c2159760239d.png">

**Comment by manucorporat** [comment]
No sure why firefox having scope classes make it harder, you should be using CSS variables to customize the app, which should work the same in all browsers.

Theses classes are just scoped CSS, because native shadow-dom is not available yet in firefox.

**Comment by peterpeterparker** [comment]
@manucorporat 

let's say I want to style the ion-toolbar background color, in Safari and Chrome the following works well:

    ion-header ion-toolbar {
      --background: red;
    }

but doesn't work in Firefox because Firefox give more priority to `.sc-ion-toolbar-md-h` than to `ion-header ion-toolbar`

    .sc-ion-toolbar-md-h {
       --background: var(--ion-toolbar-background-color, #f8f8f8);
    }

    ion-header ion-toolbar {
      --background: red;
    }
      
so yes of course I could set `--ion-toolbar-background-color` for that particular case but that's not the only one aka it means that I should and will always have go thru the all app "just" for Firefox to double check because it doesn't render like Safari and Chrome
