### ISSUE TITLE
Ionic 4 type=angular project gives blank screen when run on windows OS

### ISSUE THREAD

**Issue by Hasin96** [ionic-team/ionic#15905]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
insert the output from ionic info here
```

Ionic:

   ionic (Ionic CLI) : 4.1.2

System:

   NodeJS : v10.5.0
   npm    : 6.3.0
   OS     : Windows 10

**Describe the Bug**

after running ionic v4 and adding windows platform which creates a cordova app. I run this cordova app in vs 2017 and it gives me a blank screen. Doing the same steps with ionic v3 it shows me correct ui (default starter ui).

**Steps to Reproduce**
1. download node and npm.
2. download ionic v4 cli using npm install -g ionic
3. ionic start myApp tabs --type=angular
4. added support for android and ios by answering yes on the cmd option
4. navigate to app in cmd and open in vs code using code .
5. then I added 
     Preference with name=“windows-phone-target-version” value=“10.0”
     Preference name="windows-phone-target-version" value="10.0" 
to the config.xml file 
6. navigate to the app in cmd and type the command ionic cordova platform add windows and this should create a folder called platforms and www. 
7. I then ran ionic cordova build windows
8. inside of the platforms folder there is a windows folder. Inside of there is a sln file (mine was called CordovaApp.
8. I ran this CordovaApp.sln file using vs2017. Inside are two projects, one has an appended .Windows10
10. I ran this project using the green play button with the option under loca machine and it opened up a blank application. Other doing the exact same with an ionic 3 app works just fine(displays all the ui and changes).

**Expected Behavior**
I expected the code to run and display the ionic default ui.

**Additional Context**
I think the issue is something to do with the javascript files not loading as in the ionic 3 windows app, multiple javascript files were loaded however, in the ionic 4 windows app, there was only base.js.

**Comment by Hasin96** [comment]
I've found a solution! Navigating into the www directory and then going into the index.html that lives inside of there. I change the < base href="/" > to this < base href="./" > and this now allows all of the javascript files to be found and runs on the browser and on windows platform 10. We also checked routing and page loads and everything should be ok. It seems like there is a issue of directories going on.

**Comment by paulsutherland** [comment]
You could add a windows npm script with ng build --base-href ./ that would prevent you from manually updating the index.html file.

```
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:windows": "ng build --base-href ./",         <---- Add this in package.json
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
```

**Comment by paulstelzer** [comment]
Thanks for your issue! unfortunately this is related to Cordova, not Ionic, so I close this here
