### ISSUE TITLE
[Ionic V4.0.0-beta.12] menuController.get() with 'left' or 'right' returns undefined

### ISSUE THREAD

**Issue by JupiterSymphony** [ionic-team/ionic#15917]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.2.1
   Ionic Framework               : @ionic/angular 4.0.0-beta.12
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.2.4
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : android 6.4.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 7 other plugins)

System:

   NodeJS : v10.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
Using menuController.get() with either 'left' or 'right' as the menuID returns undefined. I had a default left side menu enabled so that should be returned. 

**Steps to Reproduce**
1. Create a menu on one page
2. Call menuController.get().then(activeMenu => { ... }), activeMenu is undefined
3. Also tried within afterViewInit() & discrete timeOut, still undefined

**Expected Behavior**
[Documentation](https://beta.ionicframework.com/docs/api/menu-controller) states the following when calling get() on menuController with either 'left' or 'right' passed in:

> If the specified menu is left or right, then it will return the enabled menu on that side.

**Comment by netsesame2** [comment]
Try @ViewChild notable tag

**Comment by manucorporat** [comment]
Use 'start' and 'end' instead, 'left' and 'right' was removed!

**Comment by JupiterSymphony** [comment]
Ahh thank you for the clarification. Please update docs to reflect this for future reference.
