### ISSUE TITLE
nav.NavigateBack('/page') in ionViewDidEnter() doesn't destroy page navigating away from

### ISSUE THREAD

**Issue by Nick-lab** [ionic-team/ionic#15911]
not too big of a problem just figured i can help widle out bugs. i have two pages one for signup and if the user is "loged in" already if going to that **URL** manually does a logged in check like.

    ionViewDidEnter() {
        if (this.dataMgr.load('user-data')) {
            this.nav.navigateBack('/home');
        }
    } 

if it is `navigateForward()` it works as expected and if its `navigateBack()` the view navigating away from is not destroyed and is opacity: 0.
 
**Ionic Info**
``` Ionic:

   ionic (Ionic CLI)          : 4.2.0 (C:\Users\Brian\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.1.0
   @ionic/schematics-angular  : 1.0.7

System:

   NodeJS : v9.2.0 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10```

```

love your work guys keep it up 👍

**Comment by paulstelzer** [comment]
For me it happens if I switch the page too fast. Can you try it with a setTimeout(), e.g

```
setTimeout(() => {
    if (this.dataMgr.load('user-data')) {
        this.nav.navigateBack('/home');
    }
}, 1000);
```

If it now works you have the same issue like me ;)

**Comment by Nick-lab** [comment]
@paulstelzer yes i have a routerGuard for the pages where they need to be logged in otherwise is just redirect them to their dashboard if they go to `site.com/signin` its not a big issue i just used nav.navigateForward() and it doesn't happen i figure its just a missed snippet of code they forgot to put in the function or something really simple
