### ISSUE TITLE
A platform agnostic way for touch feedback. Similar to ion-ripple-effect

### ISSUE THREAD

**Issue by davl3232** [ionic-team/ionic#15914]
# Feature Request

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
✔ Gathering environment info - done!
[WARN] You are not in an Ionic project directory. Project context may be 
       missing.

Ionic:

   ionic (Ionic CLI) : 4.2.1

System:

   NodeJS : v8.11.3
   npm    : 6.4.1
   OS     : macOS High Sierra


```

**Describe the Feature Request**
A platform agnostic ripple would be useful to give touch feedback in non-button components that have click event listeners but can't be a an ion-button for any reason (e.g. styling ion-button to wrap other elements is rather bothersome if not impossible).

The current behavior has a ripple effect applied to the parent element, no matter the platform. But it doesn't feel native to have MD ripples in iOS. It'd be nice to have the same styling `<ion-item button></ion-item>` gets when touched, taking into account the current platform.

**Describe Preferred Solution**
A platform agnostic way to highlight html elements when touched.
It could be a wrapper or a class that applies the effect.

**Describe Alternatives**
It could be a wrapper or a class that applies the effect.

**Comment by manucorporat** [comment]
This feature already exists!

```
<div ion-activatable>
  <ion-ripple-effect></ion-ripple-effect>
</div>
```

**Comment by davl3232** [comment]
I know about ion-ripple, but it is not platform agnostic. In iOS the effect on tap is a fade of the element, not a md ripple.

Ionic already takes these platform differences into account for buttons, but wrapping elements with a button to get this tappable feedback is unpractical since it applies more undesired styles.
