### ISSUE TITLE
[Ionic V4.0.0-beta.12] Multiple menus - menuController.enable() not disabling others

### ISSUE THREAD

**Issue by JupiterSymphony** [ionic-team/ionic#15916]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1
   Ionic Framework               : @ionic/angular 4.0.0-beta.12
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.2.4
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : android 6.4.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 7 other plugins)

System:

   NodeJS : v10.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
Using menuController.enable(true, "menu-name") does not disable other menus that exist on the same side. Currently need to explicitly disable other same side menus via menuController.enable(false, 'menu-name') then enable desired menu for desired menu to work.

**Steps to Reproduce**
1. Create a menu on one page with it's own menuID etc. (e.g. "menu1")
2. On a separate page, create a second menu with it's own distinct menuID (e.g. "menu2")
3. First menu works fine. To use second menu, call menuController.enable(true, "menu2"). Then toggling menu or drag from side, menu1 still shows, not menu2. Menu2 should show, not menu1
4. First calling menuController.enable(false, "menu1") then menuController.enable(true, "menu2") works, however

**Expected Behavior**
[Documentation](https://beta.ionicframework.com/docs/api/menu-controller) states simply enabling via true & menuID as first & second params, respectively, should do the trick and is preferred.

**Comment by Celtiore** [comment]
hi,
i do some tests with 4 ion-menu : 

https://github.com/Celtiore/ionicV4-multiples-sidemenus

I'm not sure there are bugs, I see a problem with timing, when I play fast with <ion-menu-button>.

The only bug that I see in my example, when I start in home.page.ts: this.menuCtrl.enable (true, 'Menu1'), which is not logical, because home.html contains menu-id = "Menu3"

sorry for my english, google translate is my friend

**Comment by Celtiore** [comment]
Update 19.10.2018

refactoring code after trying to analyze : 
    this.menuCtrl.getMenus().then(res => {
      console.log(res);
    })

**Comment by longgt** [comment]
Same as #13496

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
