### ISSUE TITLE
Bookmarking an Ionic v4 app in browser leads to invalid URL

### ISSUE THREAD

**Issue by ddhille** [ionic-team/ionic#15915]
I‘m not sure if this is a problem related to my host but I‘m facing following issue:

Got an Ionic app running with the Angular router (blank template). Contains one site; HomePage.
The route therefore is `““ redirect to “home“` This works as expexted.

Though when I bookmark the site in browser, the URL will be `.../home`. When I now call this URL, I get a `404` from my host. This is because the host is looking for an `index.html` in the folder `/home`, right? How am I supposed to get this to work?

It is working with `$ ionic serve`.

**Comment by godenji** [comment]
@ddhille you'll need to handle routing at the web server layer; here's an example for Nginx:
```
location / {
  root /path/to/www;
  index index.html;
  try_files $uri /index.html =404;
}
```
The above will route all files to target `$uri` if the file exists (e.g. an asset img, js, css, etc. file) or to `index.html` if it doesn't (which will be all of your "virtual" routes, `/home`, `/foo`, etc.)

**Comment by ddhille** [comment]
Cheers! Thanks for the clarification. I thought so already.
Just wondering why I didnt have to do so when I used Ionic 3..

**Comment by godenji** [comment]
> Just wondering why I didnt have to do so when I used Ionic 3.

Because you probably weren't using lazing loading in v3, which means you effectively had one route: `www.company.com`

**Comment by ddhille** [comment]
You‘re right, thanks again!
