### ISSUE TITLE
ion-alert-controller is not a known element

### ISSUE THREAD

**Issue by wiggitamoo** [ionic-team/ionic#15929]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/Users/andre/.nvm/versions/node/v8.11.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.12
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : 1.0.0

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.8
   @capacitor/core           : 1.0.0-beta.8

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/andre/Library/Android/sdk)
   NodeJS            : v8.11.3 (/Users/andre/.nvm/versions/node/v8.11.3/bin/node)
   npm               : 6.3.0
   OS                : macOS
   Xcode             : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
The ion-alert-controller is not recognized as a known element.

**Steps to Reproduce**
1. Add an <ion-alert-controller></ion-alert-controller> element to any page.
4. See error: "ng: 'ion-alert-controller' is not a known element."

**Related Code**
![image](https://user-images.githubusercontent.com/1783757/46876092-69cffa80-ce0b-11e8-9b80-c217bb685264.png)

**Expected Behavior**
The ion-alert-controller should be recognized by the ionic project.

**Comment by rtpHarry** [comment]
I'm new to this but the docs show that its something that's used by code not as a tag (not sure the correct terms for these distinctions).

There is some partial documentation here:

https://beta.ionicframework.com/docs/api/alert-controller

But I think it's more clearly described here:

https://beta.ionicframework.com/docs/api/alert/

**Comment by kensodemann** [comment]
You shouldn't need to put `ion-alert-controller` in your markup if you are using Angular, you should just be able to inject it as noted in the second link @rtpHarry shared. Putting it in the markup like that is more for if you are using @ionic/core without a JS framework.

I am going to close this as I do not think this is a bug in Ionic. If you modify your code as mentioned in the second link and remove the controller tag from your HTML and still have an issue related to this we can re-evaluate whether this should be re-opened or a new issue created.
