### ISSUE TITLE
AlertController (OverlayBaseController) handler not running in Angular zone

### ISSUE THREAD

**Issue by frederikprijck** [ionic-team/ionic#15920]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/Users/frederikprijck/.nvm/versions/node/v10.11.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.12
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : 1.0.0

System:

   NodeJS : v10.11.0 (/Users/frederikprijck/.nvm/versions/node/v10.11.0/bin/node)
   npm    : 6.4.1
   OS     : macOS
```

**Describe the Bug**
Whenever an alert's handler is executed, it's being executed outside of the NgZone.

**Steps to Reproduce**
1. Create a new application using the ionic cli (`ionic start blank tabs --type=angular`)
2. Update `HomePage` to the following:
```
export class HomePage implements OnInit {
  constructor(
      private alertCtrl: AlertController
  ) { }

  ngOnInit() {
      console.log(`Is in Angular Zone (outer): ${NgZone.isInAngularZone()}`);
      this.alertCtrl
          .create({
              buttons: [
                  {
                      text: 'OK',
                      handler: () => {
                          console.log(`Is in Angular Zone (inner): ${NgZone.isInAngularZone()}`);
                      }
                  }
              ]
          })
          .then(alert => {
              alert.present();
          });
  }
}
```
3. Run the application and press `Ok` on the alert
4. Inspect the browser's console

```
Is in Angular Zone (outer): true
Is in Angular Zone (inner): false
```

**Related Code**
I've added a reproduction sample, based on the ionic cli as mentioned in the reproduction steps: https://github.com/frederikprijck/ionic-issue-overlay-ngzone

You can find all the changes I made to the starter in a seperate commit: https://github.com/frederikprijck/ionic-issue-overlay-ngzone/commit/5f01d3a7c0160363519e9e178d85182128b1bc10

**Expected Behavior**
The handler is executed inside the Angular zone to allow Change Detection to pick up any changes as part of closing an alert (or any related overlay).

**Additional Context**
As the AlertController shares a base class with other controllers (`OverlayBaseController `), I expect this also to affect the other controllers.

**Comment by manucorporat** [comment]
Fixed in master!
