### ISSUE TITLE
Multiple Ionic Apps on IOS Crash When Using More Than 1 at same time

### ISSUE THREAD

**Issue by jtmgio** [ionic-team/ionic#15923]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/Users/jgonzalez/.nvm/versions/node/v8.9.4/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 18 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/jgonzalez/Library/Android/sdk)
   NodeJS            : v8.9.4 (/Users/jgonzalez/.nvm/versions/node/v8.9.4/bin/node)
   npm               : 6.3.0
   OS                : macOS High Sierra
   Xcode             : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
I have multiple ionic apps built from a template app that i am using on my IOS. Each app basically using the same exact code, but just connects to a different backend api. When running app 1, the app works perfect, when i open app 2, app 2 will crash. I have to close all ionic apps to use an an ionic app at a time. 

Not sure if this means there is something up with me using the same ionic base app and copying to a "new app" for distribution. 

**Steps to Reproduce**

1. Create a app as your base
1. Copy app folder and name foobar
1. Remove plugins, node modules, platforms etc
1. Reinstall platform/plugins
1. Deploy to IOS

--
1. Do this again as a different app
1. Try to run both apps on IOS device at same time

**Expected Behavior**
To be able to run 2 apps at the same time

**Comment by netsesame2** [comment]
Does each app use the same APP_ID?

**Comment by jtmgio** [comment]
@netsesame2 all the app_ids in .io-config.json are 
`{"app_id":""}`

Think this is the issue?

**Comment by jtmgio** [comment]
The actually config.xml ID is unique per app. com.foobar.name1, com.foobar.name2, etc

**Comment by netsesame2** [comment]
Just a guess. Seems that  you copy something sharing between each App, which leads to the crash.

**Comment by paulstelzer** [comment]
Maybe you have to change the port of Ionic Webview cordova plugin (see at https://github.com/ionic-team/cordova-plugin-ionic-webview#wkport )

**Comment by netsesame2** [comment]
Sound like reasonable.

**Comment by jtmgio** [comment]
@paulstelzer You are a genius my friend! worked like a charm. Thanks yall!!!

**Comment by paulstelzer** [comment]
@jtmgio No problem. Could you please close this issue?
