### ISSUE TITLE
[ionic v4-beta.12] Back button does not display 

### ISSUE THREAD

**Issue by ZenPylon** [ionic-team/ionic#15921]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/Users/zenpylon/.nvm/versions/node/v10.7.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.12
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.7.0 (/Users/zenpylon/.nvm/versions/node/v10.7.0/bin/node)
   npm        : 6.3.0
   OS         : macOS High Sierra
   Xcode      : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
The back button is not displayed, as there is a `display: none` style being added. 

**Steps to Reproduce**
1. Clone the MRE repo [here](url) and run `ionic serve -c`
2. No back button is visible

**Expected Behavior**
I should see the back button in the left corner of the screen

**Additional Context**
Screenshot attached showing the `display: none` style and the invisible button.
![screen shot 2018-10-11 at 2 43 29 pm](https://user-images.githubusercontent.com/1970004/46829719-21113680-cd64-11e8-9670-c68a92508d5c.png)

Thanks for your support!

**Comment by ZenPylon** [comment]
Upon further investigation, I see that the back button does display when `canGoBack()` returns true, which is likely the expected behavior.  I even see [here](https://github.com/ionic-team/ionic/tree/master/core/src/components/back-button) that 

> It is smart enough to know what to render based on the mode and when to show based on the navigation stack.

Maybe a small suggestion would be to explicitly state that the back button won't render in when there is nowhere for the back button to navigate to.  I'll leave this open so that someone from the ionic team can confirm.

**Comment by paulstelzer** [comment]
The back button will only visible if there is a page to go back. Just use the NavController of `@ionic/angular`. If you use `navigateForward()` then the back button will be visible. If you use `navigateRoot()` then no back button will be visible. As always: You need to add the back button to each page you want to use it. The back button will not added by default.
