### ISSUE TITLE
[Ionic v4] page switching animation fades to long when ion-content has background color 

### ISSUE THREAD

**Issue by TrayserCassa** [ionic-team/ionic#15925]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
[ERROR] Error loading @ionic/angular-toolkit package.json: Error: Cannot find module '@ionic/angular-toolkit/package'
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.2
   @angular-devkit/build-angular : 0.7.3
   @angular-devkit/schematics    : 0.7.3
   @angular/cli                  : 6.1.3
   @ionic/angular-toolkit        : not installed

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.6
   @capacitor/core           : 1.0.0-beta.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (3 plugins total)

System:

   Android SDK Tools : 26.1.1 (/home/patrick/Android/Sdk)
   NodeJS            : v10.11.0 (/usr/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.18

```

**Describe the Bug**
Well my english is not the best, so i provided a gif. We want to set the background color for ion-content from white to grey. I set that in the variable.scss. ion-items we colored white. But the animation on page transitions are to slow, when changing colors. You can see that last page when you look to "Arbeitsschein" on page transitions.
See:
![error](https://user-images.githubusercontent.com/12298964/46863104-cb499680-ce16-11e8-940d-d4f3f0fb1e3f.gif)

**Steps to Reproduce**
1. varibale.scss
> ion-content {
  background-color: rgba(221, 221, 221, 0.23);
}
ion-item {
  background-color: #FFFFFF;
}
.sc-ion-card-md-h {
  background-color: #FFFFFF;
}

2. Create two pages
3. Fill in a Label and then a list

**Expected Behavior**
Should fade in and out when background color is changed for ion-content

**Additional Context**

**Comment by TrayserCassa** [comment]
well, it is a small bug. I found out that opacity is used for animation. Well that was a little bit stupid from me.. I will use no opacity for now.

**Comment by paulstelzer** [comment]
Thanks for your issue! So I think this can be closed here
