### ISSUE TITLE
Breaking: Keyboard doesn't work correctly on ion footer ONLY IOS (video of issue)

### ISSUE THREAD

**Issue by klifa90** [ionic-team/ionic#15932]
**I'm submitting a ...** 
[X] bug report
[ ] feature request

### Video of issue:
https://imgur.com/a/PRLPJYw

### Description:
When opening the keyboard all the ion footer stuff disappears. Just tapping again on the field will make it appear again. Check video.
THIS DOES NOT HAPPEN ON ANDROID. Only on iOS simulator and real device
Also, if using safari development mode and inspecting elements, any css modification via safari will make the footer look good again. It seems it's the initial drawing that gets broken.

### What I tried:
Adding in config.xml
`<preference name="CordovaWebViewEngine" value="CDVUIWebViewEngine" />`
So ionic uses UIWebView instead of WKWebView. It works but app is very slow and other things don't work correctly as the app was built using WKWebView in mind.

Other thing that works is changing to old cordova ionic keyboard (deprecated) but when closing the keyboard all actions (button taps, navigation, etc) stops working on the app...

Tried forcing css/html rerender on keyboard opening, playing with field focus and changing between different plugin versions. Noone worked.

### Code Setup:
```
<ion-footer *ngIf="chatSession && chatSession.IsComplete != 'True'" >
<ion-toolbar  color="white" style="border-top: 1px solid #4a87ee; min-height: 45px !important">
  <ion-grid no-padding>
    <ion-row>
        <ion-col col-1 style="margin:auto">
            <ion-icon style="padding: 5px;" name="menu" class="icon-chat" (click)="openCannedMessages()"></ion-icon>
          </ion-col>
          <ion-col col-9 style="margin:auto">
              <ion-textarea #inputRef [(ngModel)]="chatText" 
              name="chat" id="chattextarea" autocorrect="on" class="chat-area" style="padding: 0px; margin:0px" [placeholder]="this.placeholderText" ></ion-textarea>
            </ion-col>
          <ion-col col-2 style="margin:auto">
            <button ion-button outline class="btn-send" (click)="actionChat(inputRef)" style="margin: 0px; font-size: 16px;">
              <ion-label >Send</ion-label>
            </button>
          </ion-col>
    </ion-row>
  </ion-grid>
</ion-toolbar>
</ion-footer>
```
### Ionic Info:
```
"@ionic-native/keyboard": "^4.15.0",
<plugin name="cordova-plugin-ionic-keyboard" spec="^2.1.3" />
```
```
Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-webview 2.1.4, (and 10 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.1.2
   NodeJS     : v8.5.0 (/usr/local/bin/node)
   npm        : 6.1.0
   OS         : macOS High Sierra
   Xcode      : Xcode 10.0 Build version 10A255
```

**Comment by zakton5** [comment]
+1 This is an issue I am facing as well. There doesn't seem to be a straightforward explanation. I tried removing all bindings/output from my footer content so that it was all static content and it still blanks it out.

**Comment by paulstelzer** [comment]
Thanks for your issue! I think this is more related to Cordova Plugin Keyboard ( https://github.com/ionic-team/cordova-plugin-ionic-keyboard ). If I am wrong, let me know

**Comment by zakton5** [comment]
@paulstelzer It's hard to tell what the cause is because it is such a strange issue. It could be Ionic, it could be the plugin, it could be both. Please consider looking into it before closing it hastily.

**Comment by paulstelzer** [comment]
@zakton5 Thanks for your answer! I will tell you why I closed this here :)

`@ionic/core` has nothing to do with the keyboard (in this case a cordova plugin), so this cannot be fixed here. Instead it's a problem of the Cordova Plugin.

This issue is also opened on the other repo https://github.com/ionic-team/cordova-plugin-ionic-keyboard/issues/47 and there you also found a fix -> https://github.com/ionic-team/cordova-plugin-ionic-keyboard/issues/47#issuecomment-440923331
