### ISSUE TITLE
[Ionic V4.0.0-beta.12] searchbar css vars missing

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#15938]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (C:\Users\Dylan van der Merwe\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.12
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 12 other plugins)

System:

   NodeJS : v10.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
There need to be more css vars for the [ion-searchbar](https://beta.ionicframework.com/docs/api/searchbar#css-custom-properties).

I need to be able to style the text color and placeholder color per platform. 

Currently there are only:
`--color`
`--placeholder-color`

The styling of the search bar changes dramatically between ios and md modes and they should be able to be styled independently of one another.

**Comment by ansarikhurshid786** [comment]
This is ionic 3 branch.

**Comment by brandyscarney** [comment]
Thanks for the issue! I am seeing some more CSS variables as of the latest beta, `beta.18`:

<img width="704" alt="screen shot 2018-12-14 at 1 09 14 pm" src="https://user-images.githubusercontent.com/6577830/50019657-7c98b400-ffa1-11e8-88c5-e6edb0211aac.png">

Is this still an issue or do these accomplish what you need? Thanks 🙂

**Comment by brandyscarney** [comment]
I'm going to close this since there hasn't been any request for specific variables, but please let me know if it's still a problem and I can reopen. Thanks!
