### ISSUE TITLE
[Ionic v4.0.0-beta.12] Add method to open ion-sliding item

### ISSUE THREAD

**Issue by shreeshbhat** [ionic-team/ionic#15949]
# Feature Request

Add a public method to close an ion-sliding item. 

```
Ionic:

   ionic (Ionic CLI)          : 4.2.0
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.9.0-beta.3
   @angular-devkit/schematics : 0.9.0-beta.3
   @angular/cli               : 6.2.4
   @ionic/ng-toolkit          : 1.1.0
   @ionic/schematics-angular  : 1.0.7

System:

   NodeJS : v8.12.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Sierra
```

**Description**

Currently, there is a method to close an ion-sliding item : [ item-sliding.tsx source link](https://github.com/ionic-team/ionic/blob/master/core/src/components/item-sliding/item-sliding.tsx#L119).
Would like a public method to open an ion-sliding item on click of a button for accessibility.

**Demo**
In the docs, there is a [demo](https://beta.ionicframework.com/docs/api/item-sliding) of closing ion-sliding item using a button click.

**Comment by shreeshbhat** [comment]
This request is not visible in the list for some reason.
@manucorporat : Tagging for visibility.
I noticed that you added some bugfixes to item sliding recently.
Please consider this request.

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
