### ISSUE TITLE
Ionic 4 ion-slide width is wrong

### ISSUE THREAD

**Issue by frontendraiden** [ionic-team/ionic#15946]
Hi!

I don’t know if this is a bug or I’m doing something wrong, but the size of the slide on a 360px screen sets to more then 2000 px. What could be the problem?

The content is not even this long if it’s in one row. In case of short slide content, the slide is shorter then the screen. It won’t set to full width, eventhough it’s only supposed to show one at a time.

Thank you!

(this is full new, empty project)

Ionic:

ionic (Ionic CLI) : 4.2.1
Ionic Framework : @ionic/angular 4.0.0-beta.12
@angular-devkit/build-angular : 0.7.5
@angular-devkit/schematics : 0.7.5
@angular/cli : 6.1.5
@ionic/angular-toolkit : 1.0.0

Cordova:

cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
Cordova Platforms : not available
Cordova Plugins : not available

System:

NodeJS : v8.11.2 (C:\Program Files\nodejs\node.exe)
npm : 6.4.1
OS : Windows 10

**Comment by viksakshum** [comment]
i have the same problem plz advise

**Comment by jtushar53** [comment]
For me its 794px

![image](https://user-images.githubusercontent.com/5780117/50778475-0b100500-12c4-11e9-9dd1-bda0bbf72a09.png)
