### ISSUE TITLE
ion-range with dualKnobs="true" is not validating properly

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [ionic-team/ionic#15950]
# Bug Report
**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)  : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 12 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/rattkin/Library/Android/sdk)
   ios-deploy        : 1.9.2
   NodeJS            : v10.6.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
When ion-range is used within `<form>` and has dualKnobs set to true, its validators doesn't seem to handle this situation properly. Even despite the fact that current upper and lower value is set and is within min/max bounds, control still reports as invalid with errors object :
```
{
actualValue: NaN
min: true,
max: true,
expectedValue: (random number)
}
```

I think that validators expect the value to be a single number, rather than being an object { upper: number, lower: number} tied to NgModel.

**Steps to Reproduce**
Create ion-range with dualKnobs and attempt to validate a form it is put in.

**Related Code**
```
<form #createForm="ngForm" novalidate>
<ion-range name="estimatedArrivalTime" #estimatedArrivalTime="ngModel" [(ngModel)]="arrivalTimeRangeMinutes" min="0" max="300" step="15" dualKnobs="true" snaps="true" required></ion-range>
</form>
```
```
 public arrivalTimeRangeMinutes: any = {
    lower: 30,
    upper: 90
  };
```

**Expected Behavior**
Control should be valid and not return any validation errors.

**Additional Context**
-

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)

**Comment by sebastian-zarzycki-es** [comment]
I'm sorry, I'm not using Ionic 4.

**Comment by paulstelzer** [comment]
AHH, sry - i put this to Ionic 3 :)
