### ISSUE TITLE
[Ionic v4.0.0-beta.13] Tabbar not reacting while overscrolling on iOS

### ISSUE THREAD

**Issue by IgorMilivojevic** [ionic-team/ionic#15952]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

The tabbar is not reacting while overscrolling the ion-content. You need to wait till the overscroll-animation has finished to switch the current tab. This feels very slow and not native-like.

**Expected behavior:**

**Steps to reproduce:**

Clone the v4.0.0-beta13 tabs template and open in DevApp on a iOS Device (also tested with cordova build).
Overscroll the HomeTab Content and after releasing try to click on an other tab. It will only switch the tab if the animation has finished.

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
