### ISSUE TITLE
Tabs is not working as expected.

### ISSUE THREAD

**Issue by siva563** [ionic-team/ionic#15964]
Example : 4 Tabs --> Each tab has their own `Rest api call `to update the data from DB (latest Data).

But Now it is not working as expected.

if you go from `Tab1` to `Tab2`, if before coming to `tab1` (`**tab 1 data is updated in DB new recode is added**`) But latest data is not updating, Means` Rest api call not calling`. so where we need call the `rest api call` to everytime update the data (`call rest api call`), now I am calling into `ngOninIt()`

**Comment by arielgpe** [comment]
I'm not sure if I don't understand the issue correctly but It seems you want the API calls to be done when you change the tabs. If so, you shouldn't do that on the ngOnInit, you should use the provided event for the tab change. https://ionicframework.com/docs/api/components/tabs/Tabs/#output-events

**Comment by siva563** [comment]
Yup, I was tried but it is ionic 4 with Lazy loading tabs, it is not working
