### ISSUE TITLE
Touch and click are disabled after swipe from left to right on restored application (android)

### ISSUE THREAD

**Issue by airstep** [ionic-team/ionic#15967]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI) : 4.1.2

System:

   NodeJS : v8.11.4
   npm    : 5.6.0
   OS     : Linux 4.18

```

**Describe the Bug**
Touch and click is disabled after fast swipe from left to right on restored application (android)

When click only get: 'mousedown event dropped because of previous touch'

**Steps to Reproduce**
1. Go to app
2. Close app from task manager
3. Open app
4. Make fast swipe from left to right and try after to click any control element

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
