### ISSUE TITLE
Slides inside tab

### ISSUE THREAD

**Issue by petver** [ionic-team/ionic#15966]
# Bug Report

**Ionic Info**
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 6.5.0
   Cordova Platforms     : ios 4.3.1
   Cordova Plugins       : cordova-plugin-ionic 5.2.5, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 13 other plugins)

System:

   ios-deploy : 1.9.1
   NodeJS     : v8.12.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

**Describe the Bug**
I have a tabbed application where the last tab consists of a slides component with 30 slides containing text and images. I run this app on an iOS device. When I go to the last tab, the first slide is shown. As soon as I swipe to the next slide, I see a completely blank screen. The footer containing the tab icons and the header are also gone. The slides have no pager. On Android, everything works fine.

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
