### ISSUE TITLE
Ionic DevApp在中国区的android设备是不是不能正常调试？

### ISSUE THREAD

**Issue by harrylyh** [ionic-team/ionic#15984]
# Support Question

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/
就是我从谷歌商店下载了Ionic DevApp，然后安装在我的android设备上，是通过Ionic DevApp正常打开了调试的项目app，但是无法调用native的功能，比如我要调用相机就无法显示出来，我在想是不是因为中国区禁用了谷歌服务的原因？因为我ios设备是正常可以的

Translated version: 
I downloaded the Ionic DevApp from the Google Store and installed it on my android device. I started the debugging app through Ionic DevApp, but I can't call the native function. For example, I can't display it if I want to call the camera. I am I wonder if it is because of the ban on Google services in China? Because my ios device is normal

**Comment by UTSOURCE** [comment]
不是的这个原因，因为Ionic DevApp并不支持所有的native功能，只支持部分，支持的部分你可以在他的官网上查到

**Comment by harrylyh** [comment]
> 不是的这个原因，因为Ionic DevApp并不支持所有的native功能，只支持部分，支持的部分你可以在他的官网上查到
这个我知道，问题就是同样都插件，ios设备可以输出device信息，打开相机，，android设备就不行，就没反应，也没报错，，然后用ionic cordova run android这个命令另外安装就都可以

**Comment by UTSOURCE** [comment]
真机上可以用，你就不要纠结这个问题了

**Comment by brandyscarney** [comment]
Thanks for the issue! This is most likely an issue with your specific plugin or plugin version. Please take a look at the following doc: https://ionicframework.com/docs/pro/devapp/#native-cordova-plugin-support

If you have more questions please visit https://ionic.zendesk.com/hc/en-us. Thanks!
