### ISSUE TITLE
segments stay appear for seconds when navigating from tab that have segments to another tab page

### ISSUE THREAD

**Issue by joesleiman** [ionic-team/ionic#15982]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)  : 4.0.2 (C:\Users\jsleiman\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.3.0

System:

   Android SDK Tools : 25.2.5
   NodeJS            : v8.9.3 (C:\Program Files\nodejs\node.exe)
   npm               : 5.4.2
   OS                : Windows 10

Environment:

   ANDROID_HOME : C:\android-sdk\sdk

```

**Describe the Bug**
I have main tabs "A" and "B" .

"A" have 2 segments 1 and 2 .
"B" is another tabs page that include 2 tabs 3 and 4.
so what I do is moving from "A" to "B" , so the segments 1 and 2 still appear for about 2 seconds in the page tag"B", then disappear and the tabs 3 and 4 appear for the current page tab "B".

html :

**Steps to Reproduce**
just make main-tabs include tab A and tab B , tab A include ion-segment-button 1 and ion-segment-button 2 ,  and for tab B :  a tab page that have 2 tabs denote for 2 different page
and try to navigate between A and B. u will see the how the segment 1 and 2 from page A will still appear for seconds in page B.

**Related Code**
```
<ion-toolbar>
  <ion-buttons class="footer-buttons">
    <!--A-->
    <button ion-button block color="icons-color" (click)="footerClick('A')">
      <div>
        <ion-icon name="icon-A"></ion-icon>
        <label>A</label>
      </div>
    </button>
    <!--B-->
    <button ion-button block color="icons-color" (click)="footerClick('B')">
      <div>
        <ion-icon name="icon-B"></ion-icon>
        <label class="title-icon-footer">B</label>
      </div>
    </button>
  </ion-buttons>
</ion-toolbar>

footerClick(page) {
    switch (page) {
      case 'A'://  page A
        this._app.getRootNav().setRoot('A', {tabIndex: 0}, {updateUrl: true});
        break;
      case 'B':
        this._app.getRootNav().setRoot('B');
        break;
    }
  }
<ion-tabs name="myAccountTabs"
          tabsPlacement="top"
          tabsLayout="icon-hide"
          tabsHighlight="true"
          [selectedIndex]="mySelectedIndex"
          [ngClass]="showTabs? 'appear-tabs':'disappear-tabs'">
  <ion-tab [root]="'my-library'" tabTitle="3" [tabsHideOnSubPages]="true"></ion-tab>
  <ion-tab [root]="'my-profile'" tabTitle="4" [tabsHideOnSubPages]="true"></ion-tab>
</ion-tabs>
```

**Expected Behavior**
when navigate from page A to B , the segments 1 and 2 should disappear immediately and segment 3 and 4 appear in the page we navigate to.

**Additional Context**
i tried also to hide the ion-segment when viewWillLeave viewDidLeave run with adding on html [hidden]= "booleanVariable", also i did an event before we move to the page "B" that change the value of booleanVariable to true, but nothing work. any help ?
also when move from B to A a white page appear for second

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
