### ISSUE TITLE
ReportViewer1.ServerReport.Render byte content cannot be displayed in iframe

### ISSUE THREAD

**Issue by baljeetkalsi** [ionic-team/ionic#15991]
Hello all , 
I trying to display ReportViewer1.ServerReport.Render byte cannot be displayed in iframe.
i check my API it is working good in web browser.
But the when trying in ionic cordova run browser.
it is giving error:
 **Error: exec proxy not found for :: Printer :: print**

Thanks

**Comment by webprofusion-chrisc** [comment]
Sound like you are using SQL Server Reporting Services in an iframe. This is not an Ionic bug but may be related to Cordova browser support.
