### ISSUE TITLE
Ion-menu width size is not adjustable with split-pane visible

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic#15997]
# Bug Report

**Ionic Info**
I am using ionic via CDN with vuejs
```
<link rel="stylesheet" href="https://unpkg.com/@ionic/core@4.0.0-beta.13/css/ionic.bundle.css">
    <script src="https://unpkg.com/@ionic/core@4.0.0-beta.13/dist/ionic.js"></script>
```

**Describe the Bug**
When the split pane is visible then --width parameter in CSS is not having any effect because of below CSS having hardcoded value for min-width.

**Related Code**
```
.split-pane-md.split-pane-visible>.split-pane-side {
    min-width: 270px;
    max-width: 28%;
    border-right: var(--border);
    border-left: 0;
}
```

**Expected Behavior**
--width variable works for ion-menu to adjust the width of side menu. Same should be used for adjusting the width of the menu with split pane visible.

Maybe I have to adjust min-width when split-pane is visible. But I am not sure if that is the right approach. Because when I was using min-width side menu was not closing when I was clicking on content area.

**Comment by jepiqueau** [comment]
the way i do it is to adjust the max-width of the ion menu as follows:
with split-pane visible for large screens
@media screen and (max-width: 815px) {
  ion-menu{
    max-width:33% !important;
  }
}
when split-pane not visible for smaller screen
@media only screen and (max-width: 500px) {
  ion-menu{
    max-width:90% !important;
  }
}

**Comment by stripathix** [comment]
I have done like this

```
.split-pane-ios.split-pane-visible>.split-pane-side,
.split-pane-md.split-pane-visible>.split-pane-side{
  max-width: 225px;
  min-width: 225px;
}
```
