### ISSUE TITLE
tabbarPlacement: 'top' not working in Ionic v4

### ISSUE THREAD

**Issue by Manivannandurairaj** [ionic-team/ionic#16009]
Hello Team,

I am using ionic v4-beta13 version. In this last beta ionic tabbarPlacement:'top' not working in IonicConfig. Here I have attached the details.

**Ionic version:**  (check one with "x")
[ ] **4.x**

**Current behavior:**
![image](https://user-images.githubusercontent.com/22704944/47209888-1df2f780-d3af-11e8-8f91-e7ebcd701517.png)

**Expected behavior:**

The tabbarPlacement should be positioned in **TOP**

**Steps to reproduce:**
Here am declare IonicConfig in app.module.ts. I am attached with my code for more details.

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouteReuseStrategy } from '@angular/router';

import { IonicModule, IonicRouteStrategy } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { IonicConfig } from '../../node_modules/@ionic/core';


const ionAppConfig: IonicConfig = {
  tabbarPlacement: 'top'
}
@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [BrowserModule, IonicModule.forRoot(ionAppConfig), AppRoutingModule],
  providers: [
    StatusBar,
    SplashScreen,
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

**Related code:**
![image](https://user-images.githubusercontent.com/22704944/47209818-f3a13a00-d3ae-11e8-9c00-3d66a63d8bba.png)

```
insert short code snippets here
```

**Comment by VectraSA** [comment]
experiencing same issue - The tabbarHighlight property doesn't work either. 
`<ion-tabs  tabbar-placement="top" tabbar-highlight="true">`

**Comment by Tochukwuibe** [comment]
Same issue here, plus adding a color to the ion-tabs isn't working either

**Comment by OAnouman** [comment]
Same issue as @Tochukwuibe

**Comment by yuricamara** [comment]
Same issue here with "@ionic/angular": "4.0.0-beta.13"

**Comment by yuricamara** [comment]
![tempsnip](https://user-images.githubusercontent.com/846066/47303148-8cc39100-d5f9-11e8-9844-30753b2cae2b.png)

**Comment by yuricamara** [comment]
A workaround, until the problem is not solved: 

```
export class TabsPage implements AfterViewChecked {
  ngAfterViewChecked() {
    const ionTabsEl = document.querySelector('ion-tabs');
    const ionTabbarEl = ionTabsEl.shadowRoot.querySelector('ion-tabbar');

    if(ionTabbarEl){
      ionTabbarEl.placement = 'top';
    }
  }
}
```

**Comment by chrisgriffith** [comment]
Heard there is some refactoring occurring with the tabs for Vue and React compatibility. Suspect that might have caused this to break. Did this work in earlier betas?

**Comment by FdezRomero** [comment]
@chrisgriffith No, it didn’t work in beta.7 and newer. I think it’s just a bug 🐛

**Comment by Tochukwuibe** [comment]
@FdezRomero actually it worked fine in every beta and just broke in 4.0.0.beta13. At least for me anyways.

**Comment by FdezRomero** [comment]
Sorry! I meant alpha.7 🙏😅 Here is the original issue I opened at the time, albeit not exactly the same: https://github.com/ionic-team/ionic/issues/14610

**Comment by manucorporat** [comment]
We have take the decition to make `ion-tab-bar` a "bottom" only component, since it models the tabs of iOS (bottom only) and the Bottom Bar navigation of material design.

There are important technical limitations that makes it impossible to project the tab-bar behind the tab's toolbar.

However, we are investing to make ion-segment more powerful and integrate better with navigation, so developers could implement a top navigation like MD. Stay tuned! Thanks!
