### ISSUE TITLE
[Ionic v4.0.0-beta.13] Tabbar highlight does not display correctly

### ISSUE THREAD

**Issue by am** [ionic-team/ionic#16001]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.
N/A
Using js version, loading from CDN:
https://unpkg.com/@ionic/core@4.0.0-beta.13/dist/ionic.js

**Describe the Bug**
When setting the tabbar hightlight to true it does not display correctly the hightlight under the selected tab.

**Steps to Reproduce**
1. Add the component `tabs`
2. Add a child `tabbar` to be able to customize the tabbar
3. Add the property of `hightlight="true"`
4. The highlight does not display correctly

**Related Code**
https://codepen.io/a--m/pen/mzxvWW?editors=1010

**Expected Behavior**
The highlighted line should be displayed under the selected tab and animate to a different one when selected.

**Additional Context**
https://github.com/ModusCreateOrg/ionic-vue/issues/47#issuecomment-431070061

**Comment by brandyscarney** [comment]
Thanks for the issue! With the latest version of Ionic 4 beta, we have removed the `highlight` property from tabs to closely follow the Material Design spec: https://material.io/design/components/bottom-navigation.html

Our Segment component has been re-designed to follow the Material Design tabs spec: https://material.io/design/components/tabs.html

It doesn't currently animate the highlight, but the highlight is displaying.

**Comment by am** [comment]
Thank you @BrandonShar for your support.
I do see your point regarding the bottom-navigation and it does make sense. 

Nevertheless, I do miss the animation on the highlight, and it very well defined regarding the guidelines:
https://material.io/design/components/tabs.html#behavior

Understand that you want to cut some complexity off.

**Comment by brandyscarney** [comment]
We do plan to add the animation in. 🙂 It will just require some additional work and we have to focus on some other things first. It will most likely be added in after v4 final.

**Comment by am** [comment]
Since it's not a bug and this is already acknowledged by the team, please feel free to close the issue.
