### ISSUE TITLE
Input has 0,1 sec blink when being focused

### ISSUE THREAD

**Issue by nikotrall** [ionic-team/ionic#16008]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```

Ionic:

   ionic (Ionic CLI)          : 4.1.2
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic 5.2.5, cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.2.0, (and 9 other plugins)

System:

   ios-deploy : 2.0.0
   NodeJS     : v8.11.1 (/Users/A2/.nvm/versions/node/v8.11.1/bin/node)
   npm        : 6.2.0
   OS         : macOS
   Xcode      : Xcode 10.0 Build version 10A255

```

**Describe the Bug**
Hi there
I faced one serious bug when I was working on making layout for my app.
So when I focus some input (only on iphone devices/emulators/emulators in chrome), I see some blinks
I think this is connected with css property pointer-events, which is set to “auto”. Is there any way to fix this ?
I’ve attached screenshot so you can see the bug
![image](https://user-images.githubusercontent.com/24766748/47189213-2eba5380-d344-11e8-991e-b2b1338889db.png)
![image](https://user-images.githubusercontent.com/24766748/47189219-32e67100-d344-11e8-97ea-1f74188a7dd5.png)

**Comment by sean118** [comment]
Hey, this issue should be related and has a nice quick fix in the comments: https://github.com/ionic-team/ionic/issues/15294#issuecomment-419742294
