### ISSUE TITLE
[Ionic 4.0.0, beta 13] content.scrollToBottom() hangs browser

### ISSUE THREAD

**Issue by JoeBoxr** [ionic-team/ionic#16005]
# Bug Report

**Ionic Info**
Ionic Framework : @ionic/angular 4.0.0-beta.13
@angular-devkit/core : 0.7.2
@angular-devkit/schematics : 0.7.2
@angular/cli : 6.0.8
@ionic/ng-toolkit : 1.0.0
@ionic/schematics-angular : 1.0.1

**Describe the Bug**
When calling scrollToBottom from within an ion-list, the loop hangs the browser.  We want to have the ion-list always at the bottom of the list.  This works fine in Ionic 3 so we are looking for ways to accomplish the same thing in Ionic 4.

**Steps to Reproduce**
1. Create a ion-list and bind it to an array or observable
2. Create a method called scrollBottom() to call this.content.scrollToBottom()
3. In the *ngFor have the last record identified and have scrollBottom() called when the last record is reached.
4. The continuous scrollToBottom() call hangs the browser

**Related Code**
`  <ion-list lines="none">
    <ion-item button *ngFor="let message of messages | async; let last = last">
      <ion-text>
        {{message.content}}{{last ? scrollBottom() : ''}}
      </ion-text>
    </ion-item>
  </ion-list>`

In the typescript

`public scrollBottom() {   
   this.content.scrollToBottom();    
}`

**Expected Behavior**
The ion-list remains at the bottom as new items are added

**Additional Context**
Works fine in Ionic 3

**Comment by royanon** [comment]
Polyfill enabled, but it also not working with IE 11 with error when this.content.scrollToBottom() is called.
TypeError: Object [object Object] has no method 'forEach'

**Comment by rpanadero** [comment]
Same here. The 'scrollBottom' function is infinitely fired.

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)

**Comment by JoeBoxr** [comment]
Hello.
Yes this issue still exists in beta.17.  What we are trying to accomplish is to use an ion-list for a chat.  We would like to keep the list at the bottom as new list items are added.  We were able to accomplish this with Ionic 3 but its a challenge with Ionic 4 to come up with a solution.  

Thanx in advance

**Comment by JoeBoxr** [comment]
Hello.

Using setTimeout helped with the issue.

` public scrollBottom() {
    if (this._scrolling === false) {
      setTimeout(() => {
        this._scrolling = false;
        this.contentArea.scrollToBottom(100);
      }, 1000);
    }
    this._scrolling = true;
  }`
