### ISSUE TITLE
App crashes on splash screen while opening

### ISSUE THREAD

**Issue by nikotrall** [ionic-team/ionic#16024]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic 5.2.5, cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.2.0, (and 10 other plugins)

System:

   ios-deploy : 2.0.0
   NodeJS     : v8.11.1 (/Users/A2/.nvm/versions/node/v8.11.1/bin/node)
   npm        : 6.2.0
   OS         : macOS
   Xcode      : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
When I build app in Xcode and then launch it on emulator/device it loads fine, but when I do the same and app is already installed on emulator/device it won't load, it gets stuck on splash screen with error: 
```
ERROR: Unhandled Promise rejection: cancelled ; Zone: <root> ; Task: Promise.then ; Value: TypeError: cancelled
```
I made sure that I'm handling all the errors, and still there is unhandled promise, so I guess it occurs somewhere inside cordova/ionic

**Steps to Reproduce**
1. Build app using command `ionic cordova build ios`
2. If app was built on emulator/device before, build and launch it Xcode (cmd + shift + U, cmd + R)
3. Wait a bit, and then scroll to the bottom of Xcode console, you will see an error, that I attached above

**Expected Behavior**
App should be loaded successfully after reopening. 

Thank you in advance

**Comment by n0mer** [comment]
same here for `@ionic/angular 4.0.0-beta.13`
