### ISSUE TITLE
Does ionic4 plans to support Angular7?

### ISSUE THREAD

**Issue by woodstream** [ionic-team/ionic#16025]
The Angular7 had been published,  it bring a lot of new features such as Virtual Scroll, Drag and Drop and more, any plans for supporting it?

**Comment by gbelmm** [comment]
ionic3 support??

**Comment by ptitjes** [comment]
@woodstream, Angular 7, as per se, is already supported. I use Ionic 4 and Angular 7 in my app.

As for the new features of Angular 7, is there anything to be done on the Ionic side ?

**Comment by laserus** [comment]
@ptitjes have you tried cdk virtual scroll vs ionic virtual scroll?

**Comment by mhartington** [comment]
Angular 7 support should be good. We're aware of a few type-related issues due to typescript 3.x, which we will address in a future release.

**Comment by woodstream** [comment]
Ionic beta16 has suport angular7
