### ISSUE TITLE
ion-slides not making transitions correct 

### ISSUE THREAD

**Issue by Joselyngab** [ionic-team/ionic#16034]
Hi, I have an ion-slide and when I have more than 20 images it doesn't makes de transitions correctly. How Could I fix this?
![slide](https://user-images.githubusercontent.com/22640731/47304038-85998480-d5f3-11e8-8cac-6671266b1b89.png)
![slide1](https://user-images.githubusercontent.com/22640731/47304048-892d0b80-d5f3-11e8-8137-2a5bf966f415.png)

Here's my code.
`<ion-slides pager="true" id="sliderhome" autoplay="6000" slidesPerView="1" loop="true" effect="coverflow"  *ngIf="slides.length" paginationClickable>
       <ion-slide *ngFor="let slide of slides"  >
         <img src="{{slide}}" imageViewer />
    </ion-slide>      
  </ion-slides> 
`

**Comment by q735423841** [comment]
Please~ How did you solve this problem?

**Comment by Joselyngab** [comment]
> Please~ How did you solve this problem?

I haven't solved it yet. It's not a problem of the image size, I tried to give it width and height 100% but it's still not working. Have any advice?

**Comment by q735423841** [comment]
> > Please~ How did you solve this problem?
> 
> I haven't solved it yet. It's not a problem of the image size, I tried to give it width and height 100% but it's still not working. Do you have any advice?

sorry.I haven't solved it either. But if  the number of your pictures  is under three,this problem does not  present, or when you use the autoplay attribute, you can use the events ionSlideAutoplayStop，and get the slides object, try to use this.slides.startAutoPlay() code.

**Comment by Joselyngab** [comment]
> > > Please~ How did you solve this problem?
> > 
> > 
> > I haven't solved it yet. It's not a problem of the image size, I tried to give it width and height 100% but it's still not working. Do you have any advice?
> 
> sorry.I haven't solved it either. But if the number of your pictures is under three,this problem does not present, or when you use the autoplay attribute, you can use the events ionSlideAutoplayStop，and get the slides object, try to use this.slides.startAutoPlay() code.

I did, but it's still presenting the same problem :( if you solved it plesae let me know how you did it.
