### ISSUE TITLE
[v4.0.0-Beta.13] Floating ion-label styles conflict ion-input with placeholder text

### ISSUE THREAD

**Issue by selipso** [ionic-team/ionic#16049]
The following block of code cases the floating label to float directly on top of the placeholder (with both being visibly overlapping) while there is no focus on the input.

Once focus is added to the input, the label floats to the top as expected. The expected behavior is that the default placement of the label is further up and with smaller font so as not to cover the input.

```html
<ion-item>
    <ion-label position="floating">Search</ion-label>
    <ion-input required type="text" 
      placeholder="Enter search term"
      autofocus="true"
    >
    </ion-input>
</ion-item>
```

**Comment by selipso** [comment]
Was just looking through the code to see if I could help solve this. I think it was already fixed as part of: https://github.com/ionic-team/ionic/pull/16036

Keeping this open until that commit gets into the next release.

**Comment by manucorporat** [comment]
Fixed by https://github.com/ionic-team/ionic/commit/a8be5291bb9b460530d143d8606c5dfa02e75343
