### ISSUE TITLE
[Ionic 4.0.0, beta 13] ion-item-option and reorder the list

### ISSUE THREAD

**Issue by TrayserCassa** [ionic-team/ionic#16043]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.8.6
   @angular-devkit/schematics    : 0.8.6
   @angular/cli                  : 6.2.6
   @ionic/angular-toolkit        : 1.0.0

System:

   NodeJS : v10.12.0 (/usr/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.18
```

**Describe the Bug**
I want an ion-item-option on the left side to push this item to the top of the list. Kind of sorting. We used also the reorder list, but we want to provide a user friendly quick method for moving stuff up. 
If it moved up, then the swipe is disabled..

By the way... the expandable (ion-item-option) and the ionSwipe (ion-item-options) isn't working yet. We will use the click event, but sliding would be more user friendly then clicking.

**Steps to Reproduce**
I have written a small blank application. See related Code:
1. Ionic serve
2. Swipe to the right and click the left Button with the arrow.
3. The Item will moved up
4. Try to swipe the moved Item again

**Related Code**
https://github.com/TrayserCassa/issue_item_options

**Expected Behavior**
Well the swipe need to work after a reorder

**Additional Context**
Maybe I am doing it wrong, but I didn't find anything in the issues and by googleing. 
If you need more information, let me now.

best regards
Trayser

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)

**Comment by eweren** [comment]
Having an issue close to that one. I have an ion-list with ion-item-sliding in it. Each of these items has an option to delete itself from the list. When that button is triggered and the request to the server succeeded, the list gets filled from ground up again. Even then -> First time sliding and deleting works just as expected, every next time i don't even see a sliding animation, nor the button of the sliding item...

```
<ion-list>
  <ion-item-sliding *ngFor="let alarm of alarms">
    <ion-item  detail="true">
      <ion-label>{{alarm.time}}</ion-label>
    </ion-item>
    <ion-item-options side="end">
      <ion-item-option (click)="deleteAlarm(alarm._id)" color="danger">
        <ion-icon name="trash"></ion-icon>
      </ion-item-option>
    </ion-item-options>
  </ion-item-sliding>
</ion-list>`
