### ISSUE TITLE
[Ionic v4] Grid Responsiveness Breaks During Resizing

### ISSUE THREAD

**Issue by gabrielthomasjacobs** [ionic-team/ionic#16042]
# Bug Report

**Ionic Info**
   ionic (Ionic CLI)                 : 4.2.1
   Ionic Framework               : @ionic/angular 4.0.0-beta.12

**Describe the Bug**
Ionic grid will re-adjust to fit content as you scale down. If you scale back up, and then down again, it no longer fits the content properly.

**Steps to Reproduce**
I've ran into this locally, but it can be reproduced on the docs:
https://beta.ionicframework.com/docs/layout/grid/#stacked-to-horizontal

1. go to _Stacked to Horizontal_ section of docs
2. in chrome dev, switch to mobile view
3. bring the size down until the items in that section are vertically aligned
4. bring the size up until the items are horizontally aligned
5. bring the size down once more to vertically align the items and notice that they do not stack anymore.

**Expected Behavior**
Responsiveness should be consistent, regardless of how many times the user re-sizes the window/app.

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
