### ISSUE TITLE
[Ionic Beta 4] Firefox Showing Input Elements With Red Border

### ISSUE THREAD

**Issue by shivarajnaidu** [ionic-team/ionic#16054]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/home/shivaraj/.nvm/versions/node/v8.12.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.8.6
   @angular-devkit/schematics    : 0.8.6
   @angular/cli                  : 6.2.6
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v8.12.0 (/home/shivaraj/.nvm/versions/node/v8.12.0/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.15

```

**Describe the Bug**
The below shown code producing input component with red borders in firefox 62.0.3 (64-bit)
 ```
<ion-item>
          <ion-input color="primary" required type="text" placeholder="First Name"></ion-input>
 </ion-item>
```

![image](https://user-images.githubusercontent.com/12374494/47401168-d2996a00-d75d-11e8-9dd9-581d22355627.png)

**Steps to Reproduce**
1. Start Ionic Dev server 
2. Place Above Code In Home Page 
3. And Open The App In Firefox

**Expected Behavior**
Expecting Proper Input MD view in Firefox

**Comment by manucorporat** [comment]
This issue was already fixed, please update to latest beta!
