### ISSUE TITLE
[4.0.0-beta.13] ion-reorder-group/ion-reorder: buggy list after item is dropped

### ISSUE THREAD

**Issue by GillesMontyne** [ionic-team/ionic#16068]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.10.2
   @angular-devkit/schematics    : 7.0.2
   @angular/cli                  : 7.0.2
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic 5.2.5, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 11 other plugins)

System:

   ios-deploy : 2.0.0
   ios-sim    : 7.0.0
   NodeJS     : v10.12.0 (/usr/local/Cellar/node/9.11.1/bin/node)
   npm        : 6.4.1
   OS         : macOS
   Xcode      : Xcode 10.0 Build version 10A255


```

**Describe the Bug**
When I drag an <ion-reorder> element and drop it (within the <ion-reorder-group>) the <ion-list> view gets messed up/buggy. 

_Before interaction:_

![image](https://user-images.githubusercontent.com/10937624/47447297-736b4200-d7bd-11e8-98e1-f50be2b76b9a.png)

_After (drag &) dropping an item:_

![image](https://user-images.githubusercontent.com/10937624/47447349-90a01080-d7bd-11e8-8b29-419089a05806.png)

**Steps to Reproduce**
1. make basic re-ordable list 
2. drag & drop an item
3. See messed up list view
##### **NO ERRORS ARE THROWN DURING THESE ACTIONS**
**Related Code**
html code:
```
<ion-content>
  <ion-list>
        <ion-list-header>
            <ion-label>INCLUDE</ion-label>
        </ion-list-header>
        <ion-reorder-group (ionItemReorder)="reorder($event)" [disabled]="false">
            <ion-item *ngFor="let accessory of accessories">
                <ion-label>{{accessory}}</ion-label>
                <ion-reorder></ion-reorder>
            </ion-item>
        </ion-reorder-group>
   </ion-list>
</ion-content>
```
typescript code:
```
 accessories = ['test', 'test1', 'test2'];

reorder(event) {
        const itemToMove = this.accessories.splice(event.detail.from, 1)[0];
        this.accessories.splice(event.detail.to, 0, itemToMove);
    }
```
**Expected Behavior**
no messed up view

**Comment by gentleen** [comment]
i face the same issue with use broswer to test the feature.
![image](https://user-images.githubusercontent.com/31028503/47474637-6fd1cc80-d84a-11e8-8971-970c3110b52d.png)
after i drag & drop 
![image](https://user-images.githubusercontent.com/31028503/47474651-82e49c80-d84a-11e8-8365-13797c5c9114.png)
and the items can't dragged anymore

**Comment by mmlleevvyy** [comment]
@gentleen @GillesMontyne You have to complete reordering by calling complete on ReorderGroup instance. Read the docs:
https://github.com/ionic-team/ionic/tree/master/core/src/components/reorder-group

```Once the data structure has been updated to reflect the reorder change, the complete() method must be called. This method finishes the reorder operation and resets all the CSS transforms applied by the ion-reorder-group component.```

**Comment by GillesMontyne** [comment]
thx, this solved my issue!

**Comment by TrayserCassa** [comment]
> @gentleen @GillesMontyne You have to complete reordering by calling complete on ReorderGroup instance. Read the docs:
> https://github.com/ionic-team/ionic/tree/master/core/src/components/reorder-group
> 
> `Once the data structure has been updated to reflect the reorder change, the complete() method must be called. This method finishes the reorder operation and resets all the CSS transforms applied by the ion-reorder-group component.`

Should this not moved to the ionic Doku beta page?

**Comment by mmlleevvyy** [comment]
@TrayserCassa It should and I guess that it will be... but can't tell why it is not present in docs website. @brandyscarney ?

**Comment by brandyscarney** [comment]
We will have the API documentation updated soon. It hasn't been deployed since `beta.11` so it is out of sync with the current API reference. I created an issue for the description being cut off: https://github.com/ionic-team/ionic-docs/issues/160

In the future if you see any issues with documentation (outdated, incomplete, etc.) please create an issue on the [ionic-docs repository](https://github.com/ionic-team/ionic-docs/issues). Thank you!

**Comment by yuricamara** [comment]
Hi @brandyscarney!

[The example in the doc](https://beta.ionicframework.com/docs/api/reorder-group) is freezing when the element is dropped. The page says 4.0.0-beta.15.

**Comment by emgould** [comment]
Same here.  I get an error:  reorder node not found and it freezes

**Comment by emgould** [comment]
Resolved.   Add  implements OnInit to my page component.  Then added the reorder event listener.  All good now.

**Comment by TrayserCassa** [comment]
@yuricamara 

> Zitat:
 In the future if you see any issues with documentation (outdated, incomplete, etc.) please create an issue on the ionic-docs repository. Thank you!

This is the wrong issue tracker for doc errors ...

**Comment by yuricamara** [comment]
@TrayserCassa , thank you for your advice but this was **NOT** about doc. I was talking about an official example by chance in the doc.

**Comment by yuricamara** [comment]
Thanks, @brandyscarney
