### ISSUE TITLE
Missing variables

### ISSUE THREAD

**Issue by agustinhaller** [ionic-team/ionic#16069]
# Support Question

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

It seems these variables ([$toolbar-ios-height](https://github.com/ionic-team/ionic/blob/v4.0.0-beta.13/core/src/themes/ionic.theme.default.ios.scss#L21)) were removed in the latest commits. How can we use them now?

I was using them to adjust the heigh of my content so it's full height like this:
``` scss
:host-context(.ios) {
  ion-grid {
    height: calc(100vh - #{$toolbar-ios-height});
  }
}
```

**Comment by agustinhaller** [comment]
Hi @brandyscarney I was wondering if with this move you are deprecating the use of this internal variables or if there's a way we can keep using them.

**Comment by brandyscarney** [comment]
Thanks for the issue! We do not recommend using our internal Sass variables in v4. At this time we will not provide support or list them as a breaking change if they are removed/added. Instead, we recommend using CSS/CSS Variables. You shouldn't need to calculate the height of the toolbar to create a full height grid, see this codepen: https://codepen.io/brandyscarney/pen/YJdVMJ/
