### ISSUE TITLE
[4.0.0-beta.13] ion-checkbox click / ngModel update event order inconsistency between browser and iOS

### ISSUE THREAD

**Issue by kzjkd6** [ionic-team/ionic#16066]
# Bug Report

**Ionic Info**

Ionic:

   ionic (Ionic CLI)          : 4.1.2 
   Ionic Framework            : @ionic/angular 4.0.0-beta.13
   @angular-devkit/core       : 0.9.0-beta.3
   @angular-devkit/schematics : 0.9.0-beta.3
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.1.0
   @ionic/schematics-angular  : 1.0.7

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic 5.2.5, cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.4, (and 7 other plugins)

System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 7

```

**Describe the Bug**
I have a model bound to ion-checkbox via [(ngModel)].  The (click) event is also bound to a handler.  When handling the (click) event the data bound to the ion-checkbox in the browser will not yet have been updated to the true/false state that the click is intending to set.  On iOS however, by the time the click handling code is triggered the model will have the final true/false state.

**Steps to Reproduce**
Steps to reproduce the behavior:
1. Create page with <ion-checkbox> control with both [(ngModel)] and (click) bound.
2. Put console / debugging logging in the (click) handler that prints the state of the model bound to the control
3. Run in browser
2. Click on the <ion-checkbox> and note that the model will have the initial state of the checkbox not the resultant clicked state.
3. Build and deploy to iOS device
4. Click on the <ion-checkbox> on the iOS device and note that the model will now be in the final state of the checkbox instead.

**Related Code**

**Expected Behavior**
In Ionic v3 the behaviour in the browser matched what I'm currently seeing in iOS only.  I don't care which way it is as long as it is consistent between browser and devices.

**Comment by adamtester** [comment]
I can confirm this bug! See attached Gif.

Heres my code:

```
<ion-list>
  <ion-item *ngFor="let tag of tags" (click)="toggleTag(tag)">
    <ion-label>{{tag.name}} {{selectedTags.indexOf(tag)}}</ion-label>
    <input type="checkbox" name="{{ tag.slug }}" [checked]="selectedTags.indexOf(tag) !== -1">
    <ion-checkbox slot="end" [checked]="selectedTags.indexOf(tag) !== -1"></ion-checkbox>
  </ion-item>
</ion-list>
```

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2249484/48802573-8400d080-ed07-11e8-8c39-2c7b65e49add.gif)

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
