### ISSUE TITLE
Ionic serve recompilation  is incredibly slow  since upgrade to V4

### ISSUE THREAD

**Issue by Tochukwuibe** [ionic-team/ionic#16064]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)             : 4.2.1 (C:\Users\Toch\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.8.5
   @angular-devkit/schematics    : 0.8.5
   @angular/cli                  : 6.2.5
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v8.11.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.0.0
   OS     : Windows 10
```

**Describe the Bug**
The slightest change to the code during the ionic serve process consistently takes at least 5ms to build, this makes it incredibly frustrating to build and debug apps. This issue only started once I upgraded the cli to a version that supports V4 projects. This happens for every V4 app. 

**Steps to Reproduce**
1. create a new V4 app
2. run ionic serve 
3. see bug

**Related Code**
If you are able to illustrate the bug with an example, please provide a sample application via an online code collaborator such as [StackBlitz](https://stackblitz.com), or [GitHub](https://github.com).

**Expected Behavior**
Should not take more than 1min to build, as compared to the angular dev server, flutter hot reload/ build.

**Additional Context**

**Comment by tja4472** [comment]
try Node 10
https://github.com/ionic-team/ionic/issues/15844#issuecomment-426967884

**Comment by Tochukwuibe** [comment]
@tja4472  thank you, node 10(10.10.0 to be specific) has fixed the issue.
