### ISSUE TITLE
Date Chooser update too slow

### ISSUE THREAD

**Issue by FarkasAndras93** [ionic-team/ionic#16079]
# Bug Report

**Ionic Info**
Ionic:

   ionic (Ionic CLI)  : 4.2.1 (C:\Users\FarkasAn\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

**Describe the Bug**
Months update is slow when I have [min] in <ion-datetime>. For example the min is 2016-06-06 12:12 when I select 2017 then the 1-12 months will be load very slow. Attached a little video which shows the bug.
[Date Chooser.zip](https://github.com/ionic-team/ionic/files/2513538/Date.Chooser.zip)

**Steps to Reproduce**
1. Create <ion-datetime> with minimum value 2016-06-06, set the value with 2016-06-07 12:12.
2. Click on ion datetime to load the date picker.
3. Modify the date from 2016 to 2017 
4. Months will be loaded slow for the year 2017.

**Related Code**
date = new Date().toISOString();

<ion-datetime [(ngModel)]="date" [min]="2018-10-24" [max]="2020"></ion-datetime>

**Expected Behavior**
Months load should not load so slow.

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
