### ISSUE TITLE
[v4] ion-input focus on iOS pushes input behind ion-header when keyboard presented

### ISSUE THREAD

**Issue by pjhartin** [ionic-team/ionic#16076]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/Users/philliphartin/.nvm/versions/node/v8.11.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.7.4
   @angular-devkit/schematics    : 0.7.4
   @angular/cli                  : 6.1.4
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.4, (and 7 other plugins)

System:

   ios-deploy : 2.0.0
   ios-sim    : 7.0.0
   NodeJS     : v8.11.3 (/Users/philliphartin/.nvm/versions/node/v8.11.3/bin/node)
   npm        : 5.6.0
   OS         : macOS
   Xcode      : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
When tapping on an ion-input the view is scroll assisted to the very top of the screen, resulting in the input being located behind the ion-header and it fixes the in behind the ion-header.
A video demo of the bug in an app we're working on: https://youtu.be/BCSvphDrEzo

**Steps to Reproduce**
1. Create a standard page, using an ion-header and ion-content.
2. Create a number of ion-inputs, enough that they cover 75% of the screen.
3. Run the app on an iOS device with smaller screen size (i.e. iPhone 5s)
4. Click/focus on an input
5. Watch the keyboard appear
6. See that in some cases the input that is focused on appears behind the ion header when the keyboard appears

**Related Code**
I've added a gist of the markup to test: https://gist.github.com/pjhartin/06ac14785e12ea109f1183c69e57e2e5

**Expected Behavior**
I would expect the scroll assist when the keyboard appears to fix the input inside the viewport with a bit of margin/padding from the top, or at least not behind the header.

**Additional Context**
It would seem that from playing around with different amounts of content on the screen: if there is enough content for the keyboard to want to "push up" then the bug occurs.

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
