### ISSUE TITLE
[4.0.0.-beta.13] ion-toggle always returns "on" as its value

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic#16074]
# Bug Report

**Ionic Info**

```
"@ionic/core": "4.0.0-beta.13"
```

**Describe the Bug**

`ion-toggle` always returns `"on"` as its value, even when switching it off.

**Related Code**

```tsx
<ion-toggle onIonChange={e => console.log(e.detail.value) />
```

**Expected Behavior**

I'd actually prefer if the returned value was a boolean (currently the boolean is in `event.detail.checked` and that behaves correctly). But there must be some reason to use `"on"` and `"off"` for the toggle value?

**Comment by manucorporat** [comment]
The `value` of a ion-toggle or a ion-checkbox might be only used when it's participating in a form. It can be any value. Going to update docs to make that clear
