### ISSUE TITLE
Not able to invoke custom method in Toast Message.

### ISSUE THREAD

**Issue by siva563** [ionic-team/ionic#16080]
Hi, I am using Ionic 4  Toast Messages.  Custom method is not invoking after dismiss Toast.

Below is the code 👍 
```
async presentToastWithOptions() {
    const toast = await this.toastController.create({
      message: 'Click to Close',
      showCloseButton: true,
      position: 'top',
      closeButtonText: 'Done',
      mode: 'md'
    });

    toast.dismiss(() => {
      console.log("Toast buton clicked");
    });

    toast.present();
  }
```
after click on Done button on Toast the console.log value is not printing even I tried with call Custom method it is not working.

Could you please some body help me Thanks in advance !!!

**Comment by leandro-hermes** [comment]
@siva563 The correct usage is:

```
toast.onDidDismiss().then(() => {
  console.log("Toast buton clicked");
});
```

**Comment by manucorporat** [comment]
@leandro-hermes 's response is correct! please checks the docs
