### ISSUE TITLE
[4.0.0-beta.13] Adding side attribute hide the menu button in tool bar

### ISSUE THREAD

**Issue by almothafar** [ionic-team/ionic#16085]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (C:\Users\almothafar\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.10.3
   @angular-devkit/schematics    : 7.0.3
   @angular/cli                  : 7.0.3
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (D:\Android\sdk)
   NodeJS            : v10.11.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

```

**Describe the Bug**
When I add `side` to the menu `<ion-menu side="right" menu-id="mainMenu">` the menu button in the toolbar disappear, I'm trying to get 2 menus for my application, one on the left and one on the right, for the first time I thought it was 2 menus conflicts, but I found the issue happens even for a single menu.

**Steps to Reproduce**
1. Get started with any application got side menu.
2. Add `side` attribute to `ion-menu`
3. The toolbar menu icon disappear.

**Related Code**

```
<ion-app>
  <ion-split-pane>

    <ion-menu side="left" menu-id="filtersMenu">
      <ion-header>
        <ion-toolbar color="dark">
          <ion-title>Filters</ion-title>
        </ion-toolbar>
      </ion-header>
      <ion-content>
        <ion-list>
          <ion-list-header>
            Wells
          </ion-list-header>
          <ion-checkbox color="primary" checked></ion-checkbox>
        </ion-list>
      </ion-content>
    </ion-menu>

    <ion-router-outlet main></ion-router-outlet>

  </ion-split-pane>
</ion-app>
```

In header:

<ion-header>
  <ion-toolbar color="dark">
    <ion-buttons slot="start">
      <ion-menu-button [menu]="'filtersMenu'"></ion-menu-button>
    </ion-buttons>
  </ion-toolbar>

  <ion-toolbar color="dark">
    <ion-searchbar [(ngModel)]="queryText" placeholder="Search"></ion-searchbar>
  </ion-toolbar>
</ion-header>

**Expected Behavior**
I should be able to see the menu icon, also if I added 2 menus I should be able to see them, one on the left and the other on the right.

**Additional Context**
Without `side='left'`: 
![image](https://user-images.githubusercontent.com/13887564/47511200-65332980-d882-11e8-96bd-a07c1091af1b.png)

With it:
![image](https://user-images.githubusercontent.com/13887564/47511255-7da34400-d882-11e8-973d-aa28f23c01f9.png)

**Comment by robingenz** [comment]
Can not reproduce it. Try `side='start'` instead of `side='left'` ( [docs](https://beta.ionicframework.com/docs/api/menu#properties) ).

**Comment by almothafar** [comment]
@robingenz I tried that, and was not helpful for me

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
