### ISSUE TITLE
html that has double hyphens e.g -- breaks the template in iOS only 

### ISSUE THREAD

**Issue by stevebrowndotco** [ionic-team/ionic#16084]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)  : 4.1.1 (/Users/Steve/.nvm/versions/node/v8.11.1/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 9 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/Steve/Library/Android/sdk)
   ios-deploy        : 1.9.2
   NodeJS            : v8.11.1 (/Users/Steve/.nvm/versions/node/v8.11.1/bin/node)
   npm               : 6.0.1
   OS                : macOS
   Xcode             : Xcode 10.0 Build version 10A255

```

**Describe the Bug**
I am facing an extremely weird bug. 

*IF* HTML has double hyphens such as 
`<div class="bem bem--class"></div>`

*or*

`<!-- I am a comment-->`

*AND* a portion of the template is **deferred** with async events such as using *ngIf with a scope variable from an observable 

**...the entirety of ion-content refuses to render!** 

Then, when I switch between ion-tabs and back again, the template renders correctly.

Only happens in iOS. Both on the emulator AND real devices.

**Steps to Reproduce**
As above (see related code below)

**Related Code**
```html
<div>
   <ion-grid *ngIf="asyncVariableFromPromiseOrObservable">
      <ion-row>
         <ion-col>
             <div class="test test--test"></div>
         </ion-col>
      </ion-row>
   </ion-grid>
</div>
```

**Expected Behavior**
The template should not be blank

**Additional Context**
I am using <ion-grid> row, col on the page

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)

And could you check if this issue occurs in plain angular, too?
