### ISSUE TITLE
Revisit --width and --height in all components

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#16097]
Sizing might work better as a intrinsic property of the host element.

cc @brandyscarney

**Comment by brandyscarney** [comment]
Problem components:

- Checkbox
  - Checkbox uses the `--height` variable to determine the border-radius.
- Radio
  - Radio has a `--width`/`--height` and an `--inner-width`/`--inner-height`. While we could remove the `--width` and `--height`, the inner width controls the checked state (iOS checkmark / MD dot). We could just hardcode these, or keep the `inner-*` variables. I can't find a good way to use the parent width and not expose these. 
- TODO
