### ISSUE TITLE
Revisit :hover styles across all components

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#16108]
- **Any :hover styling should be disabled in device (iphone) or any touchable device, it does not feel native. It's an important regression from v3, needs to be fixed before final.!**
- :hover is key for a good UI in desktop, revisit how :hover is implemented across all components in desktop (low priority, post 4.0)

**Comment by camwiegert** [comment]
Maybe it would make sense to wrap these styles in a `@media (pointer: fine)` query? These are the stylesheets with hover styles:

```
src/components/searchbar/searchbar.ios.scss
src/components/buttons/buttons.ios.scss
src/components/chip/chip.scss
src/components/button/button.scss
src/components/button/button.md.scss
src/components/button/button.ios.scss
src/components/tab-button/tab-button.scss
src/components/segment-button/segment-button.md.scss
src/components/segment-button/segment-button.ios.scss
```

**Comment by manucorporat** [comment]
Maybe! can you verify it works in chrome/safari and for device/desktop?
