### ISSUE TITLE
link ionic.bundle.css breaks scroll

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic#16114]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
C:\ae\adaept.com\ae-svg-components>ionic info
√ Gathering environment info - done!
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   ionic (Ionic CLI) : 4.2.1

System:

   NodeJS : v8.12.0
   npm    : 6.4.1
   OS     : Windows 10
```

```
C:\ae\adaept.com\ae-svg-components>npm list @stencil/core
ae-svg-components@0.15.0 C:\ae\adaept.com\ae-svg-components
`-- @stencil/core@0.15.0
```

**Describe the Bug**
Related: https://github.com/ionic-team/ionic/issues/14840
Implemented based on this:
https://github.com/ionic-team/ionic/issues/16045

**Steps to Reproduce**
Further testing shows that it is not shadow that breaks scroll, but linking
the ionic.bundle.css

**Related Code**
https://github.com/peterennis/ae-svg-components/releases/tag/ScrollBroke

**Expected Behavior**
Scroll should work
![capture422](https://user-images.githubusercontent.com/140737/47600086-9be76d80-d970-11e8-96b6-5fcd096ae9a3.png)

**Additional Context**

@brandyscarney 
This seems to be a side effect of linking ionic.bundle.css.
Tagged in the repo to revisit after a fix for https://github.com/ionic-team/ionic/issues/14840
Scroll does not work on PC or mobile (android)
I reverted the shadow false and set it true.
Also reverted link for ionic.bundle.css
https://github.com/peterennis/ae-svg-components/commit/fd409b38aac8db947b013e8aeaa581c5b09a780d
I will continue other testing

**Comment by peterennis** [comment]
@brandyscarney 
Updated ticket as scroll is broken with the ionic.bundle.css link
and not related to shadow setting.

**Comment by brandyscarney** [comment]
So the ionic bundle is meant to be used as a quick way to demo an Ionic app, meaning the application it is in should use an `ion-app` element (which controls the app scrolling). If you're maintaining a website that just includes Ionic components here and there and you don't need all of this css, you can include the css files as needed. Our standalone tests do this by only including the core css file: https://github.com/ionic-team/ionic/blob/master/core/src/components/button/test/standalone/index.html#L8

All of the information on the different CSS files that can be included is listed in our breaking changes document: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#theming

And I have an open issue to document these better: https://github.com/ionic-team/ionic-docs/issues/54

**Comment by brandyscarney** [comment]
I'm going to close this since it is a documentation issue and one has been created, thanks!
