### ISSUE TITLE
Menu: Error when no `content-id` set and `swipe-gesture="false"`

### ISSUE THREAD

**Issue by tricki** [ionic-team/ionic#16127]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

n/a

**Describe the Bug**
When using the menu without adding a `content-id` the error "Menu: must have a "content" element to listen for drag events on." is thrown in the console even if swipe gestures have been disabled with `swipe-gesture="false"`

**Steps to Reproduce**
1. Go to https://codepen.io/anon/pen/mzgRBj?editors=1011
2. See error in the console

**Expected Behavior**
No error is thrown if the gesture is disabled and content-id missing.

**Additional Context**
Code: https://github.com/ionic-team/ionic/blob/master/core/src/components/menu/menu.tsx#L163

StackOverflow issue: https://stackoverflow.com/questions/53003274/ionic4-component-menu-must-have-a-content-element-to-listen-for-drag-events

**Comment by manucorporat** [comment]
Menu needs a content container regardless it has a gesture or not.
