### ISSUE TITLE
input type=number does not work on ios

### ISSUE THREAD

**Issue by thomasferns** [ionic-team/ionic#16139]
<ion-input type="number"> </ion-input>
This works fine on android but on ios it allows numbers as well as all symbols and letters

**Comment by dylanvdmerwe** [comment]
This is an iOS specific issue for any html input of type number. You will find many many stackoverflow questions about this and potential hacks around it.

Unrelated to ionic specifically.

**Comment by mhartington** [comment]
Hi there! This issue does not appear to be an issue with the framework itself, so it will be closes. This is a quirk of iOS, as the UI is much different than other platforms. 


https://caniuse.com/#feat=input-number


Thanks!
