### ISSUE TITLE
[V4 beta4.0.0.13] cordova not available when running on android with the -l flag

### ISSUE THREAD

**Issue by Tochukwuibe** [ionic-team/ionic#16137]
# Bug Report

**Ionic Info**
```
$ ionic info
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)             : 4.2.1 (C:\Users\Toch\AppData\Roaming\nvm\v10.10.0\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.8.6
   @angular-devkit/schematics    : 0.8.6
   @angular/cli                  : 6.2.6
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 18 other plugins)

System:

   NodeJS : v10.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
Whenever I try to run my ionic app with live-reloading enabled on my Android device (ionic cordova run android -l), None of my plugins work, and I get the warning message, Cordova not available. If I run the same command without the -l flag  it runs fine, but one can imagine how frustrating development can be without live reloading

**Steps to Reproduce**
1. create a new ionic app 
2. add the Android platform with some plugins
3. run the command "ionic cordova run android -l"
4. try to access any native feature

**Expected Behavior**
Cordova should be available when running on a real native device

**Additional Context**
I am using nvm to manage different versions of Node on my machine.

**Comment by pvskasyrskiy** [comment]
I have downgraded to 
"@ionic/ng-toolkit": "1.0.8",
"@angular-devkit/architect": "0.8.6",
"@angular-devkit/build-angular": "0.8.6",
"@angular-devkit/core": "0.8.6",
"@angular-devkit/schematics": "0.8.6"
and it helped for me

**Comment by rushabhsooni** [comment]
> I have downgraded to
> "@ionic/ng-toolkit": "1.0.8",
> "@angular-devkit/architect": "0.8.6",
> "@angular-devkit/build-angular": "0.8.6",
> "@angular-devkit/core": "0.8.6",
> "@angular-devkit/schematics": "0.8.6"
> and it helped for me


what plugin have you successfully installed, and do you run on android phone or web browser?

**Comment by pvskasyrskiy** [comment]
> > I have downgraded to
> > "@ionic/ng-toolkit": "1.0.8",
> > "@angular-devkit/architect": "0.8.6",
> > "@angular-devkit/build-angular": "0.8.6",
> > "@angular-devkit/core": "0.8.6",
> > "@angular-devkit/schematics": "0.8.6"
> > and it helped for me
> 
> what plugin have you successfully installed, and do you run on android phone or web browser?
I did`t installed any plugins... just upgraded to beta13 and ionic/ng-toolkit: "1.1.0 and got problem with -livereload on android

**Comment by Tochukwuibe** [comment]
no ng-toolkit in my dev-dependencies, I think they either changed or renamed the package to @ionic/angular-toolkit a few versions back.


   "@angular-devkit/architect": "~0.8.5",
    "@angular-devkit/build-angular": "~0.8.5",
    "@angular-devkit/core": "~0.8.5",
    "@angular-devkit/schematics": "~0.8.5",
    "@angular/cli": "~6.2.5",
    "@angular/compiler": "~6.1.1",
    "@angular/compiler-cli": "~6.1.1",
    "@angular/language-service": "~6.1.1",
    "@ionic/angular-toolkit": "^1.0.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.12.0",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
