### ISSUE TITLE
[v4-beta.13] back-button disappears when route's componentProps change

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic#16142]
# Bug Report

**Ionic Info**

```
"@ionic/core": "4.0.0-beta.13"
"@stencil/core": "0.15.1"
```

**Describe the Bug**

In a Stencil/Ionic PWA project, I add an array as a state to my `app-root` component which I pass into a page as a prop (via `componentProps` on its `ion-route`). Through an event emitted from the page (child) I update the array in the component (root), e. g. removing an item.

This causes the `app-root` as well as the page to re-render, and makes the `ion-back-button` disappear.

**Related Code**

Source: https://github.com/simonhaenisch/stencil-global-state-issue
Deployment: https://stencil-global-state-issue.now.sh

```ts
interface Item {
  id: number;
  label: string;
}
```

```tsx
// app-root.tsx

@State() list: Item[] = [ /* ... */ ];

@Listen('remove')
onRemove({detail: item}: CustomEvent<Item>) {
  this.list = this.list.filter(el => el !== item);
});

render() {
  const { list } = this;

  return (
    <ion-app>
      <ion-router>
        <ion-route url="/" component="app-home" />
        <ion-route url="/list" component="app-list" componentProps={{ list }} />
      </ion-router>
      <ion-nav />
    </ion-app>
  );
}
```

```tsx
// page-list.tsx

@Prop() list: Item[];

@Event() remove: EventEmitter<Item>;

render() {
  return (
    <ion-content>
      <ion-list>
        {this.list.map(item => (
          <ion-item key={item.id} onClick={() => this.remove.emit(item)}>
            <ion-label>{item.label}</ion-label>
          </ion-item>
        )}
      </ion-list>
    </ion-content>
  );
}
```

**Steps to Reproduce**

1. Go to https://stencil-global-state-issue.now.sh
2. Click the "Slow List" button
3. Remove an item from the list by clicking the `X` button
4. The back button disappears

**Expected Behavior**

The re-render shouldn't cause the current view to lose its back view.

**Additional Context**

The re-render also causes the page to lose its scroll position; to reproduce: scroll down and remove the last element, which will cause the page to scroll to top.

**Comment by simonhaenisch** [comment]
**Update:** I just looked into the `ion-route` source and found that there is a `componentProps` watcher:

https://github.com/ionic-team/ionic/blob/00544e910692b0b5b271ac5c1a54524cb7f43e25/core/src/components/route/route.tsx#L42-L59

`this.onUpdate` emits an `ionRouteDataChanged` event:

https://github.com/ionic-team/ionic/blob/00544e910692b0b5b271ac5c1a54524cb7f43e25/core/src/components/route/route.tsx#L36-L40

That probably means that a prop change is treated as a route change (?) and that's why the back button disappears and the scroll position is lost...

Is that intended? If so, we need to state that somewhere in the docs, cause I was expecting the following:

```jsx
<ion-route component="my-page-component" componentProps={{ foo: 'bar', bar: 'foo' }} />
```

renders out my component as something like

```jsx
<my-page-component { ...componentProps } />
```

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)

**Comment by simonhaenisch** [comment]
Yup, still happens... see https://stencil-global-state-issue-mna3a43vz.now.sh/.
