### ISSUE TITLE
[v4-beta.15-0] No example available on using multiple "ion-router-outlet" elements with the new tab system

### ISSUE THREAD

**Issue by maddada** [ionic-team/ionic#16166]
Please provide an example on how a tabs page like the one bellow would be converted to the new system.
Thanks!

**Comment by maddada** [comment]
<ion-tabs color="secondary" tabbarLayout="label-hide" tabbarPlacement="bottom" tabbarHighlight="true">

  <ion-tab label="{{'common.home' | translate}}" icon="browsers" href="/tabs/(home:home)">
    <ion-router-outlet name="home"></ion-router-outlet>
  </ion-tab>

  <ion-tab label="{{'common.featured' | translate}}" icon="bookmarks" href="/tabs/(contact:contact)">
    <ion-router-outlet name="contact"></ion-router-outlet>
  </ion-tab>

  <ion-tab label="{{'common.search' | translate}}" icon="search" href="/tabs/(search:search)">
    <ion-router-outlet name="search"></ion-router-outlet>
  </ion-tab>

  <ion-tab label="{{'common.profile' | translate}}" icon="person" href="/tabs/(profile:profile)">
    <ion-router-outlet name="profile"></ion-router-outlet>
  </ion-tab>

</ion-tabs>

**Comment by brandyscarney** [comment]
We'll have better documentation published on this soon. We're currently working on getting rid of some bugs that slipped in, and then we'll also have a blog posted. You can see the updated documentation in the tabs directory: https://github.com/ionic-team/ionic/tree/master/core/src/components/tabs

Here's an example of how yours would change:

```html
<ion-tabs>
  <ion-tab tab="home">
    <ion-router-outlet name="home"></ion-router-outlet>
  </ion-tab>

  <ion-tab tab="featured">
    <ion-router-outlet name="contact"></ion-router-outlet>
  </ion-tab>

  <ion-tab tab="search">
    <ion-router-outlet name="search"></ion-router-outlet>
  </ion-tab>

  <ion-tab tab="profile">
    <ion-router-outlet name="profile"></ion-router-outlet>
  </ion-tab>

  <!-- placement is bottom by default, highlight has been removed -->
  <ion-tab-bar color="secondary" layout="label-hide">

    <ion-tab-button tab="home" href="/tabs/(home:home)">
      <ion-label>{{'common.home' | translate}}</ion-label>
      <ion-icon name="browsers"></ion-icon>
    </ion-tab-button>

    <ion-tab-button tab="featured" href="/tabs/(contact:contact)">
      <ion-label>{{'common.featured' | translate}}</ion-label>
      <ion-icon name="bookmarks"></ion-icon>
    </ion-tab-button>

    <ion-tab-button tab="search" href="/tabs/(search:search)">
      <ion-label>{{'common.search' | translate}}</ion-label>
      <ion-icon name="search"></ion-icon>
    </ion-tab-button>

    <ion-tab-button tab="profile" href="/tabs/(profile:profile)">
      <ion-label>{{'common.profile' | translate}}</ion-label>
      <ion-icon name="profile"></ion-icon>
    </ion-tab-button>

  </ion-tab-bar>

</ion-tabs>
```

We do still need to update the usage examples though. I created an issue to do that over on our ionic-docs repo: https://github.com/ionic-team/ionic-docs/issues/163. Please track this issue for documentation updates, thanks!

**Comment by maddada** [comment]
Hey @brandyscarney , I'm sorry, but why was the tabbarHighlight removed? Is it possible to add it back in a future version?
Thank you.
