### ISSUE TITLE
Capacitor Electron error related to toast

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic#16165]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
https://unpkg.com/@ionic/core@4.0.0-beta.13/dist/ionic.js
```

**Describe the Bug**
npm run electron:start

**Steps to Reproduce**
Just run app packaged as electron via capacitor
<img width="552" alt="screenshot 2018-11-01 at 12 08 24 am" src="https://user-images.githubusercontent.com/8480351/47810927-7c828300-dd6a-11e8-9ead-0d4c9bf1c7e7.png">

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? Furthermore, I think this issue is maybe more related to Capacitor ( https://github.com/ionic-team/capacitor )
