### ISSUE TITLE
[4.0.0-beta.15-0] MD outline border width

### ISSUE THREAD

**Issue by ptitjes** [ionic-team/ionic#16174]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.3.0 (/opt/npm/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15-0
   @angular-devkit/build-angular : 0.10.3
   @angular-devkit/schematics    : 7.0.3
   @angular/cli                  : 7.0.3
   @ionic/angular-toolkit        : 1.1.0

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.8
   @capacitor/core           : 1.0.0-beta.8

System:

   NodeJS : v10.13.0 (/usr/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.18
```

**Describe the Bug**
Since `4.0.0-beta.15-0`, the border width of the outline of buttons is `2px`.
However, looking at the documentation of Material Design it seems the outline should remain `1px`:
https://material.io/design/components/buttons.html#outlined-button

**Related Code**
The commit that sets the border width to `2px` is https://github.com/ionic-team/ionic/pull/16160/commits/ef8c9331636558ed3d1cce17a2fa0bada511844a.

**Comment by brandyscarney** [comment]
Thanks for the issue! This was a design decision we made to match the Material Components for the Web implementation here: https://material-components.github.io/material-components-web-catalog/#/component/button

<img width="450" alt="screen shot 2018-11-01 at 11 49 07 am" src="https://user-images.githubusercontent.com/6577830/47862965-a79dbe80-ddcc-11e8-9367-5037e25e0176.png">

We're going to continue to match the implementation, but if it changes we will definitely update it.

**Comment by brandyscarney** [comment]
Also, just to add to this - we found an example in the Play store where it is using 2px, but if you have seen it different elsewhere please let us know!

![screenshot_20181101-110530](https://user-images.githubusercontent.com/6577830/47866653-c3599280-ddd5-11e8-84e6-adef13a1d402.png)

**Comment by ptitjes** [comment]
@brandyscarney Thanks for your answer. I guess they did not update their documentation :D
