### ISSUE TITLE
[4.0.0-beta.15] ion-input, ion-searchbar, ion-textarea styling inconsistencies

### ISSUE THREAD

**Issue by ajmchambers** [ionic-team/ionic#16189]
# Bug Report

**Info**
```
@ionic/core : 4.0.0-beta.15
```

**Describe the Bug**
`<ion-input>`, `<ion-searchbar>`, `<ion-textarea>` have a larger placeholder font-weight in edge.

Side-by-side image of Chrome, Edge, IE11:
![placeholder-issue](https://user-images.githubusercontent.com/5426717/47879440-84006580-de18-11e8-96f4-4bf466c04c97.png)

`<ion-searchbar>` has content clear button positioned incorrectly.
![search-edge-clear](https://user-images.githubusercontent.com/5426717/47879828-81ead680-de19-11e8-9842-d0bd4e9e2c74.png)

`<ion-searchbar>` has a smaller height and content clear button styling issues in IE11, and placeholder text is not visible when the input is focused but empty.
![search-ie11-clear](https://user-images.githubusercontent.com/5426717/47879832-87482100-de19-11e8-90b7-27aa24932231.png)

**Related Code**
```tsx
import { Component } from '@stencil/core';

@Component({
  tag: 'app-root',
  styleUrl: 'app-root.css'
})
export class AppRoot {
  render() {
    return (
      <ion-app>
        <ion-content padding>
          <ion-input type="text" placeholder="Input placeholder" />
          <ion-searchbar />
          <ion-textarea placeholder="Textarea placeholder" />
        </ion-content>
      </ion-app>
    );
  }
}
```

**Expected Behavior**
`<ion-input>`, `<ion-searchbar>`, `<ion-textarea>` should look consistent across browsers.

**Comment by kinggolf** [comment]
Seeing same with ion-toolbar.
From theme/variables.scss:
```
:root {
  --ion-color-primary: #455a64;
  --ion-color-primary-rgb: 69, 90, 100;
  --ion-color-primary-contrast: #fff;
  --ion-color-primary-contrast-rgb: 255, 255, 255;
  --ion-color-primary-shade: #718792;
  --ion-color-primary-tint: #1c313a;

  --ion-color-danger: #f04141;
  --ion-color-light: #ffffff;

  --ion-color-medium: #0b2db5;
  --ion-color-medium-rgb: 11, 45, 181;

  --ion-toolbar-md-background-color: #43697c;
  --ion-toolbar-background-color: #43697c;
  --ion-toolbar-md-text-color: #ffffff;
  --ion-toolbar-text-color: #ffffff;
```
ion-toolbar styling not coming through anymore.

**Comment by ptitjes** [comment]
@kinggolf This is the result of https://github.com/ionic-team/ionic/commit/b2021fd, and is unrelated to the present issue. (I agree this should have been more explicitly mentioned in the release notes. The moral of the story is that you should scrutinize the change-log at each release... :p)

**Comment by brandyscarney** [comment]
Thanks for the issue! We will look into this.

Sorry that the breaking changes didn't make the changelog from https://github.com/ionic-team/ionic/commit/b2021fd! That was my fault - I formatted it wrong in the commit so it didn't make it into the changelog. 🙁 I updated the release tag here: https://github.com/ionic-team/ionic/releases/tag/v4.0.0-beta.15

Will merge this PR to update the changelog once the checks pass: https://github.com/ionic-team/ionic/pull/16201

**Comment by kinggolf** [comment]
It's all good @brandyscarney. [Docs](https://beta.ionicframework.com/docs/theming/advanced) look good, which is very cool! Thanks for great framework and all the super support. Take it easy. :)

**Comment by paulstelzer** [comment]
Thanks for your reponse. Is the issue solved or are there still any issues?

**Comment by ajmchambers** [comment]
I've noticed improvements in beta 17 but I'm still having a few issues in edge and ie11 which I'll try and get documented.

Anyway I'm going to close this issue and https://github.com/ionic-team/ionic/issues/15621. I'll do some fresh testing in beta 17 and create some new issue(s).

Cheers

**Comment by paulstelzer** [comment]
Thank you! Yes, a summarized issue would be the best!
