### ISSUE TITLE
NPM Registry dist-tag for "next" is pointing to an older release than the "latest" dist-tag for @ionic/angular package

### ISSUE THREAD

**Issue by ChrisPearce** [ionic-team/ionic#16195]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.0 (/Users/user1/.npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.10.4
   @angular-devkit/schematics    : 7.0.4
   @angular/cli                  : 7.0.4
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.3, (and 5 other plugins)

System:

   NodeJS : v11.0.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS
   Xcode  : Xcode 10.1 Build version 10B61
```

**Describe the Bug**
The @next tag in the NPM registry is pointing to v0.0.2-29 rather than 4.0.0-beta.15.
**Steps to Reproduce**
1. Type 'npm info @ionic/angular' on the command line
2. The output shows the @next dist-tag as pointing to 0.0.2-29 rather than 4.0.0-beta.15

**Related Code**
N/A

**Expected Behavior**
The @next dist-tag in the NPM registry should point to the latest beta release.

**Additional Context**
N/A

**Comment by paulstelzer** [comment]
Thanks for your issue! @ionic/angular has NO UPDATED next tag, so you just need to install @ionic/angular@latest
