### ISSUE TITLE
[4.0.0-beta.15] New ion-tabs not showing correctly on iPhone X devices

### ISSUE THREAD

**Issue by yuyinitos** [ionic-team/ionic#16196]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15-0
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.0.0, (and 12 other plugins)

System:

   ios-deploy : 2.0.0
   ios-sim    : 6.1.2
   NodeJS     : v8.12.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS
   Xcode      : Xcode 10.1 Build version 10B61
```

**Describe the Bug**
The icons of the tabbar are not displayed on iPhone X (and up) devices.

**Steps to Reproduce**
Use the new tabs syntax as below.
```
<ion-tabs (ionNavDidChange)="onChangeTab()" #tabs>
  <ion-tab-bar layout="icon-bottom">
    
    <ion-tab-button tab="home" href="/tabs/(home:home)">
      <ion-icon name="home"></ion-icon>
      <ion-label>{{ 'dashboard' | translate }}</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="request" href="/tabs/(request:repair)">
      <ion-icon name="build"></ion-icon>
      <ion-label>{{ 'request' | translate }}</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="status" href="/tabs/(status:status)">
      <ion-icon name="list"></ion-icon>
      <ion-label>{{ 'status' | translate }}</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="settings" href="/tabs/(settings:settings)">
      <ion-icon name="person"></ion-icon>
      <ion-label>{{ 'settings' | translate }}</ion-label>
    </ion-tab-button>

  </ion-tab-bar>

  <ion-tab tab="home" icon="home">
    <ion-router-outlet name="home"></ion-router-outlet>
  </ion-tab>

  <ion-tab tab="request" icon="build">
    <ion-router-outlet name="request"></ion-router-outlet>
  </ion-tab>

  <ion-tab tab="status" icon="status">
    <ion-router-outlet name="status"></ion-router-outlet>
  </ion-tab>

  <ion-tab tab="settings" icon="person">
    <ion-router-outlet name="settings"></ion-router-outlet>
  </ion-tab>

</ion-tabs>
```

Use `ionic cordova prepare ios` and open the workspace file in Xcode. Run on iPhone X simulator. See screenshot for iPhone X and iPhone 6 comparison.

<img width="951" alt="schermafbeelding 2018-11-02 om 12 33 57" src="https://user-images.githubusercontent.com/4574988/47913986-434b2f80-de9e-11e8-892a-c92af8c6d2c6.png">

**Comment by maddada** [comment]
![image](https://user-images.githubusercontent.com/1892053/48225756-32774e00-e3b7-11e8-901a-fc34d6baae00.png)

Same here!

**Comment by kelvinjp** [comment]
+1

**Comment by orlyapps** [comment]
+1

**Comment by maddada** [comment]
Is this fixed with beta 16? I can't release my app on the App Store because of this bug.

**Comment by orlyapps** [comment]
yep, critical bug :-/

**Comment by orlyapps** [comment]
Hello everyone,

dont forget to use the slot:
`<ion-tab-bar slot="bottom" color="dark">`
Then it works on the iPhone X. But the initial position is wrong. After a short scroll it rearranges 

![img_0124](https://user-images.githubusercontent.com/5220826/48720205-8425a100-ec1f-11e8-9164-c195785049f6.png)

**Comment by kelvinjp** [comment]
> Hello everyone,
> 
> dont forget to use the slot:
> `<ion-tab-bar slot="bottom" color="dark">`
> Then it works on the iPhone X. But the initial position is wrong. After a short scroll it rearranges
> 
> ![img_0124](https://user-images.githubusercontent.com/5220826/48720205-8425a100-ec1f-11e8-9164-c195785049f6.png)

Not Works.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. I am not seeing this anymore on the latest version of Ionic. Are you still running into this issue?

Thanks!
