### ISSUE TITLE
[4.0.0-rc.0] - Menu - Click while scrolling

### ISSUE THREAD

**Issue by JumBay** [ionic-team/ionic#16191]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)             : 4.3.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.8.6
   @angular-devkit/schematics    : 0.8.6
   @angular/cli                  : 6.2.6
   @ionic/angular-toolkit        : 1.1.0

System:

   NodeJS : v8.12.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS
```

**Describe the Bug**
While the menu is open you can still scroll the content (only once), this is similar to #13282.
But the difference with ionic 3 is that you cannot click anymore on other buttons while the content is scrolling. See the demo

![screen recording 2018-11-02 at 10 19 22](https://user-images.githubusercontent.com/216573/47906791-4805e880-de8a-11e8-962f-cbb69f3e964a.gif)

When you use the app on a real device with your fingers it happens quite often.

**Steps to Reproduce**
Create a new ionic 4 project with sidemenu starter template.
In src/app/list/list.page.ts, increase the number of generated items and try on a simulator.

**Expected Behavior**
1. Stop scrolling while clicking on the menu button
2. Prevent scrolling if menu opened.

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)

**Comment by JumBay** [comment]
Still presents on `beta.17`
