### ISSUE TITLE
Ionic 4 theming: review stepped colors to remove some

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic#16202]
Review the stepped colors to see if we can remove half of them and just have one set. Since background moves towards text and vice versa, they are the same in reverse. For example, instead of having:

```
--ion-background-color-step-700: #4d4d4d;

--ion-text-color-step-300: #4d4d4d;
```

we could just have:

```
--ion-color-step-3: #4d4d4d;
```

(naming is not decided on)

# Summary of Steps

## Background Color Steps

| Used               | Step                               | Value          |
|--------------------|------------------------------------|----------------|
| :white_check_mark: | `--ion-background-color-step-50`   | `#f2f2f2`      |
| :red_circle:       | `--ion-background-color-step-100`  | `#e6e6e6`      |
| :white_check_mark: | `--ion-background-color-step-150`  | `#d9d9d9`      |
| :red_circle:       | `--ion-background-color-step-200`  | `#cccccc`      |
| :white_check_mark: | `--ion-background-color-step-250`  | `#bfbfbf`      |
| :red_circle:       | `--ion-background-color-step-300`  | `#b3b3b3`      |
| :red_circle:       | `--ion-background-color-step-350`  | `#a6a6a6`      |
| :red_circle:       | `--ion-background-color-step-400`  | `#999999`      |
| :red_circle:       | `--ion-background-color-step-450`  | `#8c8c8c`      |
| :red_circle:       | `--ion-background-color-step-500`  | `#808080`      |
| :red_circle:       | `--ion-background-color-step-550`  | `#737373`      |
| :red_circle:       | `--ion-background-color-step-600`  | `#666666`      |
| :red_circle:       | `--ion-background-color-step-650`  | `#595959`      |
| :red_circle:       | `--ion-background-color-step-700`  | `#4d4d4d`      |
| :red_circle:       | `--ion-background-color-step-750`  | `#404040`      |
| :red_circle:       | `--ion-background-color-step-800`  | `#333333`      |
| :red_circle:       | `--ion-background-color-step-850`  | `#262626`      |
| :red_circle:       | `--ion-background-color-step-900`  | `#1a1a1a`      |
| :red_circle:       | `--ion-background-color-step-950`  | `#0d0d0d`      |
| :red_circle:       | `--ion-background-color-step-1000` | `#000000`      |

## Text Color Steps

| Used               | Step                               | Value          |
|--------------------|------------------------------------|----------------|
| :red_circle:       | `--ion-text-color-step-50`         | `#0d0d0d`      |
| :white_check_mark: | `--ion-text-color-step-100`        | `#1a1a1a`      |
| :white_check_mark: | `--ion-text-color-step-150`        | `#262626`      |
| :white_check_mark: | `--ion-text-color-step-200`        | `#333333`      |
| :red_circle:       | `--ion-text-color-step-250`        | `#404040`      |
| :red_circle:       | `--ion-text-color-step-300`        | `#4d4d4d`      |
| :red_circle:       | `--ion-text-color-step-350`        | `#595959`      |
| :white_check_mark: | `--ion-text-color-step-400`        | `#666666`      |
| :white_check_mark: | `--ion-text-color-step-450`        | `#737373`      |
| :red_circle:       | `--ion-text-color-step-500`        | `#808080`      |
| :white_check_mark: | `--ion-text-color-step-550`        | `#8c8c8c`      |
| :white_check_mark: | `--ion-text-color-step-600`        | `#999999`      |
| :white_check_mark: | `--ion-text-color-step-650`        | `#a6a6a6`      |
| :red_circle:       | `--ion-text-color-step-700`        | `#b3b3b3`      |
| :red_circle:       | `--ion-text-color-step-750`        | `#bfbfbf`      |
| :white_check_mark: | `--ion-text-color-step-800`        | `#cccccc`      |
| :red_circle:       | `--ion-text-color-step-850`        | `#d9d9d9`      |
| :red_circle:       | `--ion-text-color-step-900`        | `#e6e6e6`      |
| :red_circle:       | `--ion-text-color-step-950`        | `#f2f2f2`      |
| :red_circle:       | `--ion-text-color-step-1000`       | `#ffffff`      |

## Proposed Combined Steps

| Used               | Step                    | Value          | Default Mix Amount |
|--------------------|-------------------------|----------------|--------------------|
| :white_check_mark: | `--ion-background-color`| `#ffffff`      | 0%                 |
| :white_check_mark: | `--ion-color-step-50`   | `#f2f2f2`      | 5%                 |
| :red_circle:       | `--ion-color-step-100`  | `#e6e6e6`      | 10%                |
| :white_check_mark: | `--ion-color-step-150`  | `#d9d9d9`      | 15%                |
| :white_check_mark: | `--ion-color-step-200`  | `#cccccc`      | 20%                |
| :white_check_mark: | `--ion-color-step-250`  | `#bfbfbf`      | 25%                |
| :red_circle:       | `--ion-color-step-300`  | `#b3b3b3`      | 30%                |
| :white_check_mark: | `--ion-color-step-350`  | `#a6a6a6`      | 35%                |
| :white_check_mark: | `--ion-color-step-400`  | `#999999`      | 40%                |
| :white_check_mark: | `--ion-color-step-450`  | `#8c8c8c`      | 45%                |
| :red_circle:       | `--ion-color-step-500`  | `#808080`      | 50%                |
| :white_check_mark: | `--ion-color-step-550`  | `#737373`      | 55%                |
| :white_check_mark: | `--ion-color-step-600`  | `#666666`      | 60%                |
| :red_circle:       | `--ion-color-step-650`  | `#595959`      | 65%                |
| :red_circle:       | `--ion-color-step-700`  | `#4d4d4d`      | 70%                |
| :red_circle:       | `--ion-color-step-750`  | `#404040`      | 75%                |
| :white_check_mark: | `--ion-color-step-800`  | `#333333`      | 80%                |
| :white_check_mark: | `--ion-color-step-850`  | `#262626`      | 85%                |
| :white_check_mark: | `--ion-color-step-900`  | `#1a1a1a`      | 90%                |
| :red_circle:       | `--ion-color-step-950`  | `#0d0d0d`      | 95%                |
| :white_check_mark: | `--ion-text-color`      | `#000000`      | 100%               |

**Comment by manucorporat** [comment]
Then we could have two SCSS utils like:

```scss
@function background-step-color($step) {
    @return var(--ion-color-step-#{$variation});
}

@function text-step-color($step) {
    @return var(--ion-color-step-#{1000 - $variation});
}
```

**Comment by manucorporat** [comment]
Also:
- consider removing half-step: 150, 250, 350
- using a more compact CSS vars? --ion-step-1, --ion-step-2, --ion-step-3...
