### ISSUE TITLE
[4.0.0-beta.15] 'ion-show-when' is not a known element

### ISSUE THREAD

**Issue by RafaelKr** [ionic-team/ionic#16214]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/home/rafael/.nvm/versions/node/v10.7.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 10 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/rafael/android-sdk-linux)
   NodeJS            : v10.7.0 (/home/rafael/.nvm/versions/node/v10.7.0/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.10
```

**Describe the Bug**
After the update to `@ionic/angular@4.0.0-beta.15` I get the following output in my DevTools console:
```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
'ion-show-when' is not a known element:
1. If 'ion-show-when' is an Angular component, then verify that it is part of this module.
2. If 'ion-show-when' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

**Steps to Reproduce**
1. Install  `@ionic/angular@4.0.0-beta.15`
2. Use the following element:
```html
<ion-show-when platform="md">
  <ion-item>
    <ion-label>This should only show on Android.</ion-label>
  </ion-item>
</ion-show-when>
```

**Comment by gabfiocchi** [comment]
It does not work `ion-hide-when`

**Comment by paulstelzer** [comment]
It was removed -> https://github.com/ionic-team/ionic/commit/6a138a6c550f83ba96ed5aa235ee517564fba194

But do not ask me why. Manu did not mentioned this refactor and no word in the changelog

**Comment by MrSparklle** [comment]
I talk with Mike Hartington in Slack about this. For now the `ion-show-when` and `ion-hidden-when` has been removed from v4. They are evaluating it's usage.

As alternative you can use the framework equivalent like `ngIf` or `hidden`.

file.ts
```
import {  Platform } from '@ionic/angular';
....
constructor(private platform: Platform) {}
...
public isMD = this.platform.is('md');
```

template.html
```
<ion-item *ngIf="isMD">
    <ion-label>This should only show on Android.</ion-label>
</ion-item>
```

I agree. This should be documented in Beta.15 release notes.

**Comment by corysmc** [comment]
Could ion-show-when be replaced with some documentation around classes or attributes that can be added? @manucorporat

**Comment by comino** [comment]
The original feature was quite useful. I would vote for a comeback. Just my 2 cents.

**Comment by corysmc** [comment]
Here's some snippets I created to replace the `ion-show-when size="sm"` if anyone else finds it useful:

```
.show-when-lg {
  display: none;
}
.show-when-sm {
  display: none;
}

@media (min-width: 992px) {
  .show-when-lg {
    display: block;
  }
  .hide-when-lg {
    display: none;
  }
}

@media (min-width: 576px) {
  .show-when-sm {
    display: block;
  }
  .hide-when-sm {
    display: none;
  }
}
```

Just add the class `show-when-sm` to a div to show/hide based on size.

**Comment by brandyscarney** [comment]
Thanks for the issue! `ion-show-when` and `ion-hide-when` have indeed been removed.

I've started documenting this for our breaking changes in this PR: https://github.com/ionic-team/ionic/pull/16463/files

I also created a Codepen showing some examples here: https://codepen.io/brandyscarney/pen/ZmjJgV?editors=1100

I don't think this is something we will be adding back in the form of components, but I could see the argument for it being added as utility classes/attributes in the future that are optional to include (see https://beta.ionicframework.com/docs/layout/css-utilities). Could you please let me know if you think of any other use cases that I am missing from my examples? Thanks!! 🙂

**Comment by brandyscarney** [comment]
@paulstelzer Yeah unfortunately it isn't possible right now. ☹️ It would be really beneficial to us if it were.
