### ISSUE TITLE
Cannot start new project in beta 15

### ISSUE THREAD

**Issue by nathantaal** [ionic-team/ionic#16213]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI) : 4.3.0

System:

   NodeJS : v10.12.0
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
When running something like ```ionic start myApp tabs --type=angular``` the terminal get stuck after ```√ Preparing directory .\myApp - done!```

**Steps to Reproduce**
1. Run ```ionic start myApp tabs --type=angular```
2. Wait forever

**Expected Behavior**
MyApp to be created with tabs

**Additional Context**
I think its platform dependend (Will try this later on my laptop also running Windows) and later this week at my Ubuntu workstation. But it does happen in my specific case.

**Comment by kerosin** [comment]
duplicate of https://github.com/ionic-team/ionic-cli/issues/3722

**Comment by nathantaal** [comment]
Closed because of duplicate
