### ISSUE TITLE
[4.0.0-beta.15] ion-item occasionally not rendering correctly in ios mode

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#16222]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (C:\Users\Dylan van der Merwe\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 12 other plugins)

System:

   NodeJS : v10.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
New in beta 15. 

When I navigate to a very simple page with `ion-item` in iOS mode, the structure of the ion-item is all weird. However if I load the page directly the ion-item is rendered correctly. Only happens in iOS mode. 

Rendered weirdly:
![image](https://user-images.githubusercontent.com/2852839/47970774-9a195a80-e092-11e8-9572-aae3eb2c26bc.png)

![image](https://user-images.githubusercontent.com/2852839/47970822-0e53fe00-e093-11e8-9257-b1300f3b0b30.png)

Rendered properly:
![image](https://user-images.githubusercontent.com/2852839/47970775-a8677680-e092-11e8-8181-e3b0d4979bff.png)

![image](https://user-images.githubusercontent.com/2852839/47970835-35123480-e093-11e8-9901-8788cf3db557.png)

**Related Code**
```
   <ion-list lines="inset">
      <ion-item *ngFor="let booking of bookings">
        <ion-icon name='body' slot='start'></ion-icon>
        <ion-label>
          <h1>{{booking.facilityName}}</h1>
          <div class='date'>
            <h4>{{booking.date}}</h4>
            <p>{{booking.startTime}} - {{booking.endTime}}</p>
            <p *ngIf='booking.billedAmount > 0'>{{booking.billedAmount | zarCurrency}}</p>
          </div>
        </ion-label>
      </ion-item>
    </ion-list>
```

**Expected Behavior**
Should look the same every time I go onto the page.

**Comment by mhartington** [comment]
Are you able to isolate this in a small test case? Just copying the code provided and adding it to an app does not reproduce the issue.

**Comment by dylanvdmerwe** [comment]
I still have this on beta 16. Struggling to reproduce in a sample app, but is 100% reproducible in my actual application.

**Comment by mhartington** [comment]
try pulling pieces our from your main app into a demo. Otherwise, it's hard to know what could be the issue without a reproducible test case.

**Comment by dylanvdmerwe** [comment]
Fixed in beta 17 thanks to https://github.com/ionic-team/stencil/commit/d7d1914a0a09f5f884a7e49eb9cb36a25ea2c156
