### ISSUE TITLE
[4.0.0-beta.15] Ion-content has margin at the bottom on iOS 12

### ISSUE THREAD

**Issue by adrynov** [ionic-team/ionic#16229]
**Steps to Reproduce**

1. Create a new blank Ionic project using V4 Beta 15 
2. Add color="dark" to ion-content on Home page
3. Add Capacitor and build for iOS
4. Observe a white stripe at the bottom 

(it disappears if you scroll the screen, but can be seen through the dark background)

**Expected Behavior**
ion-content should cover the full area

![Imgur](https://i.imgur.com/e55XOtz.png)

**Comment by JumBay** [comment]
Check this https://github.com/ionic-team/capacitor/pull/740#issuecomment-416606895 (worked for me)

**Comment by sahyun1** [comment]
this happens to me without capacitor the link in the above comment doesn't work for me.

**Comment by adrynov** [comment]
I added 

`html[mode="ios"] { height: 100vh; }`

to global.scss, as suggessted and that worked.
