### ISSUE TITLE
Native: tried calling Camera.getPicture, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator

### ISSUE THREAD

**Issue by aadriann** [ionic-team/ionic#16221]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.0
   Ionic Framework               : @ionic/angular 4.0.0-beta.12
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 9 other plugins)

System:

   NodeJS : v8.9.0 (C:\Program Files\nodejs\node.exe)
   npm    : 5.5.1
   OS     : Windows 10
```

**Describe the Bug**
When i try to choose some option to upload a photo i have this error: "Native: tried calling Camera.getPicture, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator"

Only happend when i generate an APK with ionic pro, in my local with ionic cordova build/run android and with cap open android works.

My imports: import { Camera, CameraOptions, PictureSourceType } from '@ionic-native/camera/ngx';

Code: 
this.takePicture(this.camera.PictureSourceType.PHOTOLIBRARY);

takePicture(sourceType: PictureSourceType) {
        const options: CameraOptions = {
            quality: 100,
            sourceType: sourceType,
            saveToPhotoAlbum: false,
            correctOrientation: true,
            allowEdit: true
        };

        // Get the data of an image
        this.camera.getPicture(options).then((imagePath) => {
            // Special handling for Android library
            if ((this.platform.is('android') || this.platform.is('ios')) && sourceType === this.camera.PictureSourceType.PHOTOLIBRARY) {
                this.filePath.resolveNativePath(imagePath)
                    .then(filePath => {
                        let correctPath = filePath.substr(0, filePath.lastIndexOf('/') + 1);
                        let currentName = imagePath.substring(imagePath.lastIndexOf('/') + 1, imagePath.lastIndexOf('?'));
                        this.copyFileToLocalDir(correctPath, currentName, this.createFileName());
                    });
            } else {
                var currentName = imagePath.substr(imagePath.lastIndexOf('/') + 1);
                var correctPath = imagePath.substr(0, imagePath.lastIndexOf('/') + 1);
                this.copyFileToLocalDir(correctPath, currentName, this.createFileName());
            }
        }, (err) => {
            console.error("error", err);
            this._imageService.presentToast(err);
        });
    }

Previously to this error, this functionality works, but i update to ionic 4.3.0 and fails

**Comment by MrSparklle** [comment]
Cordova doesn't seams to work outside the mobile platforms (iOS and Android).
This is the normal behaviour when try to execute a Cordova app in a computer web browser.

As workaround, you can try to add the browser platform. 
`ionic cordova platform add browser`

Some Cordova plugins like camera works fine in browsers, I usually use it for test purposes.

**Comment by aadriann** [comment]
I know, but my problem is in the generated APK...
