### ISSUE TITLE
[v4.0.0-beta.15] You can pick wrong date with the ion-datetime component

### ISSUE THREAD

**Issue by sasos90** [ionic-team/ionic#16234]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (C:\Users\++++\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.10.1
   @angular-devkit/schematics    : 7.0.1
   @angular/cli                  : 7.0.1
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.4, (and 9 other plugins)

System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

```

**Describe the Bug**
Seems like you are able to chose the wrong date for example: 31.2.2018. When I translate this into the ISO format, it even outputs me the date 3.3.2018 instead.
Is this intended feature, or is it a bug?
And how could we go pass it?

```html
<ion-item>
  <ion-label>Date</ion-label>
  <ion-datetime #datePick displayFormat="DD.MM.YYYY" pickerFormat="DD MM YYYY" formControlName="date"></ion-datetime>
</ion-item>
```

**Expected Behavior**
It should prevent chosing the wrong date eg. 31.2.2018

**Additional Context**
https://beta.ionicframework.com/docs/api/datetime/

**Comment by paulstelzer** [comment]
Thanks for your issue! I know that there are currently more issues related to the datetime

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us. I'm not seeing this issue anymore on v4.0.1. Would you be able to try this again with the latest version of Ionic, and let me know if you are still experiencing this issue?

**Comment by sasos90** [comment]
Hm I will try, but we first have to upgrade to Ionic4. Thanks for the heads up!

**Comment by pwespi** [comment]
@liamdebeasi  I can still reproduce this issue in v4.0.1. If the initial date is January 31, and then you only change the month to February, the component shows February 31.
Tested with:
https://stackblitz.com/edit/typescript-1xegxy?file=index.ts

**Comment by liamdebeasi** [comment]
Hi @sasos90,

Thanks for providing the code example. So I can see that the component is outputting February 31, but I am not seeing it output the incorrect ISO string as you suggested in your original post: 
```
When I translate this into the ISO format, it even outputs me the date 3.3.2018 instead.
```

Is that still happening for you?

**Comment by sasos90** [comment]
Currently, I am not working on the project, where I had the problem, and at that time we haven't updated to  Ionic4 unfortunately. I will definitely reply when I update the version and try it out there.

Thanks!
