### ISSUE TITLE
Flicker when rendering ion-grid in webkit (works in Chrome)

### ISSUE THREAD

**Issue by scornflake** [ionic-team/ionic#16236]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.8.7
   @angular-devkit/schematics    : 0.8.7
   @angular/cli                  : 6.2.7
   @ionic/angular-toolkit        : 1.1.0

System:

   NodeJS : v10.13.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Sierra
```

**Describe the Bug**
Rendering flickers when rendering the ion-grid with a *ngFor. Appears in webkit only (tested on browser and ios device). Works if you use, say, ul/li with *ngFor

**Steps to Reproduce**
1. Download https://github.com/scornflake/ionic4-refresh-test
2. Run on webkit

Sample video also provided.

**Related Code**
https://github.com/scornflake/ionic4-refresh-test

**Expected Behavior**
Should not flicker when data is refreshed

**Comment by scornflake** [comment]
Edited to show that the issue exists specifically for ion-grid render.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I have confirmed that this issue is fixed in the latest version of Ionic. If you are still running into this, please open a new issue. Thanks!
