### ISSUE TITLE
v4: Ionic Capacitor screen placement 

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/ionic#16235]
**Description:**
I have been building an app with Ionic and Capacitor for around 5 months now and all has been great. out of nowhere, when I build and run the app on my IOS Device (iphone 7 plus), there is a small space under the app, about the size of the status bar. I tried debugging with safari and there is nothing that indicated why this space would suddenly be there.

To try and see if I had done something along the way to cause this, I created a brand new project and installed capacitor, as per the guide. Built and ran on the device and exactly the same issue

![white](https://user-images.githubusercontent.com/6772168/47951730-a7ccc400-df5c-11e8-9913-7423cb12f395.jpg)

**Steps to Reproduce:**
- Run Ionic start
- Init capacitor
- remove ionic splash screen plugin as instructed
- build
- run on device

**Comment by dwieeb** [comment]
@oliverandersencox Just to confirm, you're using an actual device?

On the simulator for iPhone 7, we see it getting rid of the white space whenever the DevTools loads. Does this happen for you?

**Comment by oliverandersencox** [comment]
@dwieeb yeah this happens on the device and inconsistently on the simulator - very odd.

Screen adjustments will fix the problem, such as turning on tethering which brings the bigger blue status bar, will push it down. It's very random when it decides to fix itself.

**Comment by TrayserCassa** [comment]
I can confirm that for my iPhone 6 / Version A1586

**Comment by oliverandersencox** [comment]
@jcesarmobile - You don't suppose capacitor has any involvement in this issue?

**Comment by paulstelzer** [comment]
Thanks for the issue! if the issue isn't resolved yet, could you please open the issue at the Capacitor repository? That would be great -> https://github.com/ionic-team/capacitor
