### ISSUE TITLE
[v4] feature: close button icon for toasts

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic#16237]
# Feature Request

**Ionic Info**

```
"@ionic/core": "4.0.0-beta.15"
```

**Describe the Feature Request**

Add an option `closeButtonIcon: string` to [`ToastOptions`](https://github.com/ionic-team/ionic/blob/master/core/src/components/toast/toast-interface.ts) that renders an icon instead of `closeButtonText`, or next to the `closeButtonText`.

**Describe Preferred Solution**

I mainly want to modify this part of the `ion-toast` template

https://github.com/ionic-team/ionic/blob/fda48a0e52556ca624e9641adbe851ebbd7ea92d/core/src/components/toast/toast.tsx#L206-L210

to something like this:

```tsx
<ion-button>
  {this.closeButtonIcon && (
    <ion-icon name={this.closeButtonIcon} slot={this.closeButtonText ? 'end' : 'icon-only'} />
  )}
  {this.closeButtonText || (this.closeButtonIcon ? '' : 'Close')}
</ion-button>
```

**Describe Alternatives**

None?

**Additional Context**

I'll make a PR for this, just don't have the time right now, and wanted to have a reminder for myself...

**Comment by zakton5** [comment]
@simonhaenisch Check out #17147. Do you think that will work for you?
