### ISSUE TITLE
[v4.0.0-beta.15] Documentation UI not helpful

### ISSUE THREAD

**Issue by iAmAnkeeta** [ionic-team/ionic#16243]
Hi,

I am working on the Ionic 4 app. Looks like the documentation with the UI is broken in https://beta.ionicframework.com/docs/api/searchbar
![screen shot 2018-11-06 at 10 35 37 am](https://user-images.githubusercontent.com/18538734/48074792-ba8b0700-e1af-11e8-8d88-b3330f85454b.png)

**Comment by almothafar** [comment]
Yes, it is broken, it seems something missing from distributed file: 

![image](https://user-images.githubusercontent.com/13887564/48074984-d52ea180-e1ea-11e8-9243-749fd95d1f58.png)

**Comment by brandyscarney** [comment]
Thanks for the issue! We'll have a fix in for this soon, but in the meantime please track it on this issue: https://github.com/ionic-team/ionic-docs/issues/168
