### ISSUE TITLE
4.0.0-beta.15 Support SSR

### ISSUE THREAD

**Issue by aaronsalva27** [ionic-team/ionic#16255]
# Bug Report
Ionic not supporting server side rendering

# Additional Context
After a few month waiting for an answer I decided to open this issue. The configuration and the deployment with angular universal was imposible, I saw that another users have requested this feature, any update or date to release a fix?. Has Ionic another way to work with crawler and make SEO more friendly?

**Comment by peterpeterparker** [comment]
This one too https://github.com/ionic-team/ionic/issues/14574

**Comment by brandyscarney** [comment]
Closing as a duplicate of #14574 and #15041
