### ISSUE TITLE
[4.0.0-beta.15] ion-virtual-scroll inside ion-split-pane rendering issue

### ISSUE THREAD

**Issue by berchik** [ionic-team/ionic#16256]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
 ionic (Ionic CLI)             : 4.3.1 (C:\Users\jo\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.8.6
   @angular-devkit/schematics    : 0.8.6
   @angular/cli                  : 6.2.6
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 7.0.1
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   Android SDK Tools : 26.1.1 (A:\Users\Jo\AppData\Local\Android\sdk)
   NodeJS            : v10.11.0 (A:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Describe the Bug**
Having ion-virtual-scroll inside the left-side menu of ion-split-pane: 
when the menu is collapsed the items on the virtual-scroll are not rendered correctly, items are missing and/or several items are painted over each other on the first line.

**Comment by Slavrix** [comment]
When using a header function, I have seen the items overlap each other in a virtual scroll in the main area also (not just the side menu).

![screen shot 2019-03-07 at 5 09 07 pm](https://user-images.githubusercontent.com/11223551/53935777-c6ee8480-40fb-11e9-9c26-ea612387aa8f.png)

**Comment by nice2seeu** [comment]
I had the same problem when I had the ion-virtual-scroll inside the content menu of ion-split-pane.
It works for me when 'the main content' just comes first, as below. The ion-virtual-scroll inside the content menu and the side menu works fine. Is this also a bug?

`<ion-split-pane contentId="menu-content">`
  ` <!-- the main content -->`
` <ion-router-outlet id="menu-content"></ion-router-outlet>`
  `<!--  our side menu  -->`
  `<ion-menu contentId="menu-content">`
    `<ion-header>`
      `<ion-toolbar>`
        `<ion-title>Menu</ion-title>`
      `</ion-toolbar>`
    `</ion-header>`
  `</ion-menu>`
`</ion-split-pane>`
