### ISSUE TITLE
[4.0.0-beta.15] Several bugs within ion-refresher

### ISSUE THREAD

**Issue by toxsickcoder** [ionic-team/ionic#16254]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (C:\Users\freek\AppData\Roaming\nvm\v8.12.0\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.8.7
   @angular-devkit/schematics    : 0.8.7
   @angular/cli                  : 6.2.7
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
The refresher in `@ionic/angular@4.0.0-beta.15` has serveral bugs:
- There is a `console.log('start')` still in compiled `@ionic/core` code which triggers when starting to you start to drag on a page with the refresher.
- The refresher itself lies above the content, instead of below. This means that the instant you start to pull, it is completely visible above your content, instead of sliding out from underneath it.
- After completing the refresher action, the content jumps back instantly, instead of sliding back up.

**Steps to Reproduce**
Go to https://beta.ionicframework.com/docs/components/#refresher and test it out. It has the same bugs as described above.

**Comment by skined90** [comment]
I agree with @toxsickcoder I have same issues with refresher and it's really annoying, especially instant jump back to top.

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)

**Comment by skined90** [comment]
@paulstelzer Problem is still there for me in `beta.17`

**Comment by toxsickcoder** [comment]
@paulstelzer I still have the problem in `beta.17` as well.

**Comment by mnbattaglia** [comment]
Me too! The problem remains in beta.17
