### ISSUE TITLE
[4.0.0-beta.15] content resize method missing

### ISSUE THREAD

**Issue by meta0102** [ionic-team/ionic#16258]
# Bug Report

Ionic:

   ionic (Ionic CLI) : 4.0.6

System:

   NodeJS : v8.11.3
   npm    : 6.4.1
   OS     : Windows 10

**Describe the Bug**
the resize method for ion-content is missing. i need to call this method to resize the searchbar
see https://github.com/ionic-team/ionic/issues/7706

**Comment by brandyscarney** [comment]
Thanks for the issue! In Ionic 4, the `ion-content` layout is based on flex. This means the size of the content will automatically adjust without the need to call `resize()`.  I'm not able to see any issues with this and removing the toolbar. Could you please provide a way for us to reproduce if you're seeing issues with this? Thanks!

**Comment by meta0102** [comment]
hi, sure.
the problem appears only on big screens, on mobile width all looks fine
```
<ion-header no-border>
  <ion-toolbar class="transparent-toolbar">
    <ion-buttons slot="end">
      <ion-button *ngIf="!showSearchBar" icon-only (click)="presentSearch()">
        <ion-icon class="md-icon" name="search"></ion-icon>
      </ion-button>
    </ion-buttons>
    <ion-title *ngIf="!showSearchBar">{{title}}</ion-title>
    <ion-searchbar showCancelButton *ngIf="showSearchBar" placeholder="Suchen" (ionClear)="onSearchCancel($event)" [(ngModel)]="searchstring" (search)="search()"></ion-searchbar>
  </ion-toolbar>
</ion-header>

<ion-content fullscreen>
</ion-content>


presentSearch() {
      this.showSearchBar = true;
}
onSearchCancel() {
      this.showSearchBar = false;
      this.searchstring = '';
}
search() {

}
```
thanks

**Comment by peterpeterparker** [comment]
I think resize is not needed anymore in v4, duplicate https://github.com/ionic-team/ionic/issues/14875

**Comment by peterpeterparker** [comment]
@bossjon because I used to use it in v3 but don't use it anymore in v4, even in pages where I use `scrollToBottom` with dynamic content aka in my chat

**Comment by brandyscarney** [comment]
I tried to reproduce the problem using the code above but I am not seeing any issues with content where it would need to be resized. If anyone could please provide code that I can use to reproduce this or confirm it is no longer an issue that would be great. Thank you!!

Codepen: https://codepen.io/brandyscarney/pen/GeoazQ?editors=1010
