### ISSUE TITLE
[Ionic v4-Beta.15] config / <ion-tabs> missing "tabsHideOnSubPages"

### ISSUE THREAD

**Issue by olivermuc** [ionic-team/ionic#16267]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/Users/os/.npm-packages/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15-0
   @angular-devkit/build-angular : 0.8.1
   @angular-devkit/schematics    : 0.8.1
   @angular/cli                  : 6.2.1
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.3, (and 19 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/os/Library/Android/sdk)
   ios-deploy        : 2.0.0
   ios-sim           : 7.0.0
   NodeJS            : v8.9.1 (/usr/local/Cellar/node/8.9.1/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.1 Build version 10O45e
```

**Describe the Bug**
Can't hide tab-bar on sub pages of tabs.

**Steps to Reproduce**
Tap on any tab, drill down into sub page and still see the tab-bar element.

**Expected Behavior**
Have a means to enable/disable tabs on sub pages of tabs.

This used to be available.

**Comment by paulstelzer** [comment]
We've released beta.18 now with another refactor of tabs. https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#400-beta18-2018-12-13

Yoo can already hide the `<ion-tab-bar>` using a service if you are on a childpage or something like this.  So I put this under feature request

**Comment by Bengejd** [comment]
I was running into the same issue, so I wrote up a quick Medium article about how to programmatically hide the tabs on certain pages, without having to manually hide/show them everytime you navigate. 

https://medium.com/@JordanBenge/ionic-4-hiding-showing-tabs-on-certain-pages-31cf2380a5db

**Comment by manucorporat** [comment]
We will not add this feature, since now the router is handled by angular, and it's much harder for us to implement this functionality.

In addition, we made it super easy to hide the `ion-tab-bar` programatically whenever the developer wants!
