### ISSUE TITLE
I cannot get full (click) $event on ios - ionic4

### ISSUE THREAD

**Issue by diver2** [ionic-team/ionic#16263]
I also posted this on stackoverflow, 
https://stackoverflow.com/questions/53199458/i-cannot-get-full-click-event-on-ios-ionic4

as for my config, this happens with ionic start --type=angular... in any case:

Ionic:

   ionic (Ionic CLI)             : 4.3.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.8.7
   @angular-devkit/schematics    : 0.8.7
   @angular/cli                  : 6.2.7
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.1, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/emiliomaciel/Library/Android/sdk)
   NodeJS            : v10.8.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61

I am using ionic 4 "@ionic/angular": "^4.0.0-beta.15", and cordova. I am doing a simple button:

<ion-button (click)="myFunc($event)"> My button </ion-button>

and its handler

myFunc($event) {
  console.log($event);
}

In the computer, running ionic serve, I can see the whole event, access Parent Nodes, etc (the main purpose of this is styling objects with the renderer later) BUT... in ios, the event is only composed of

{"isTrusted":true}

Same thing happens if you change the ion-button for a div, or a span, for example. I am trying to understand why. I run this with

ionic cordova prepare ios

And then build/run it on Xcode (latest 10.1 (10B61) )

Any ideas? If you need more info... It happens if you just build a ionic starter project.

ionic start testIOS blank --type=angular
ionic cordova platform add ios
ionic cordova prepare ios

Run in Xcode

Only added the ion-button in home page, and the click event. Works in ionic serve, not in ios.

Cheers! Thanks! Emilio

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)
