### ISSUE TITLE
Genereted version android with Ionic 4

### ISSUE THREAD

**Issue by juanluis89** [ionic-team/ionic#16276]
Hello, I just started to try Ionic4, and when generating the apk it is only compatible for android 7.1 or more. How can I generate it so that it supports previous versions forward, for example 4.2?. Regards

**Comment by dylanvdmerwe** [comment]
Hi there. This is not an ionic specific issue - it's a general cordova issue that can be asked in the [forums](https://forum.ionicframework.com).

**Comment by nathantaal** [comment]
But it would be useful to know what the Ionic team thinks their targets SDK on the first stable ionic 4 release is going to be.

**Comment by dylanvdmerwe** [comment]
Minimum is Android 5 (API level 20 and up). Unless you use Crosswalk plugin (which is no longer actively developed).

https://beta.ionicframework.com/docs/intro/browser-support

**Comment by juanluis89** [comment]
@dylanvdmerwe  I appreciate your answer, but I was looking for something to tell me how to solve that problem that I have now to generate the apk to a lower version, which you tell me is from Cordova and I understand it, but still I have not found, if you or someone you knew of a success test, I would appreciate it if you shared it with me. Greetings and thanks.

**Comment by Gargamil** [comment]
Maybe this could be helpful: https://ionic.zone/debug/ionic-and-android-4#downgrade

Also remind of the polyfills.js in angular.

**Comment by shaxxx** [comment]
Duplicate of #15438

**Comment by brandyscarney** [comment]
Thanks, closing as a duplicate of #15438
