### ISSUE TITLE
Ionic 4: Not being able to style disabled ion-fab-button

### ISSUE THREAD

**Issue by michaelcamper** [ionic-team/ionic#16288]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.8.7
   @angular-devkit/schematics    : 0.8.7
   @angular/cli                  : 6.2.7
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   ios-deploy : 2.0.0
   NodeJS     : v8.12.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS
   Xcode      : Xcode 10.1 Build version 10B61
```

**Describe the Bug**
Neither pseudo, nor attribute selector for `disabled` is applied to `ion-fab-button`

**Steps to Reproduce**
1. Add disabled attribute to `ion-fab-button`
2. Style it via pseudo or attribute selector of `disabled`
3. Css rules are not applied

**Related Code**
```
<ion-fab slot="fixed" [vertical]="'bottom'" [horizontal]="'start'">
  <ion-fab-button [disabled]="true">A</ion-fab-button>
</ion-fab>

<ion-fab slot="fixed" [vertical]="'bottom'" [horizontal]="'end'">
  <ion-fab-button [disabled]="false">B</ion-fab-button>
</ion-fab>
```

```
/* Check if it's a view encapsulation issue*/
ion-fab-button {
  transform: rotate(90deg);
}

/* Not applied */
ion-fab-button[disabled],
ion-fab-button[disabled="true"],
ion-fab-button:disabled {
  transform: rotate(180deg);
}
```

**Expected Behavior**
The 'disabled' rules (rotate by 180 deg) should be applied.

**Additional Context**
Screenshot:
![localhost_8100_home iphone 6_7_8 1](https://user-images.githubusercontent.com/39185098/48300396-ecb4a580-e4dc-11e8-8a08-7270a96e9b09.png)

It works as expected with`ion-button`

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm not able to reproduce this in either `core` or an `angular` project using `4.0.0-beta.16`. Are you using ViewEncapsulation by chance? Or are you still able to reproduce this using latest? 

Here's an example of it running in core (without Angular) see the bottom right FAB: https://codepen.io/brandyscarney/pen/BGqGMM?editors=1100
