### ISSUE TITLE
[Ionic v4] The android keyboard is overlapping the ion-input on the screen

### ISSUE THREAD

**Issue by iurevguimaraes** [ionic-team/ionic#16282]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.15
   @angular-devkit/core       : 0.8.7
   @angular-devkit/schematics : 0.8.7
   @angular/cli               : 6.2.7
   @ionic/ng-toolkit          : not installed
   @ionic/schematics-angular  : not installed

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.1, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/iureguimaraes/Android/Sdk)
   NodeJS            : v10.8.0 (/usr/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.15
```
**Describe the Bug**
The android keyboard overlay the input on the screen intermittently.

**Steps to Reproduce**
1. Go to any screen with ion-inputs
2. Click on the input sometimes
3. See error

**Error example**
![screenshot_20181109-152433](https://user-images.githubusercontent.com/6683251/48280919-d3a3ea00-e433-11e8-9792-0b8d344d1d45.png)
```
In this case I clicked in "teste 11" but it is after the keyboard.
```

**Expected Behavior**
Show the android keyboard and focus in the input on the screen.

**Comment by NoirD** [comment]
I have the same problem.

**Comment by Lehren** [comment]
Same issue here.

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please open an issue on https://github.com/ionic-team/cordova-plugin-ionic-keyboard ?  It's more related to them because `@ionic/core` has no cordova plugins in it
