### ISSUE TITLE
[4.0.0-beta.15] Where is "consolelogs" option?

### ISSUE THREAD

**Issue by freeintelligence** [ionic-team/ionic#16287]
# Support Question

In "ionic3" there was the option of "consolelogs" when running on a device:
`ionic cordova run android -c`
And now?

**Comment by zaarheed** [comment]
Duplicate of [this issue](https://github.com/ionic-team/ionic-cli/issues/3169) in the CLI repo. It needs to be re-implemented.

For most cases you can use Safari Dev Tools or Chrome Dev Tools to view `console.log()` statements. [Skip to Step 3 in this tutorial](https://webdesign.tutsplus.com/articles/quick-tip-using-web-inspector-to-debug-mobile-safari--webdesign-8787) if you're using the Xcode simulator.
