### ISSUE TITLE
Inner Scroll element background introduced in beta.12 breaks cordova-plugin-googlemaps

### ISSUE THREAD

**Issue by zaarheed** [ionic-team/ionic#16284]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.7.0-rc.3
   @angular-devkit/schematics    : 0.7.0-rc.3
   @angular/cli                  : 6.1.0
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.1, (and 5 other plugins)

System:

   ios-deploy : 2.0.0
   NodeJS     : v8.11.2 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61
```

**Describe the Bug**
The [cordova-plugin-googlemaps](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc) package used with `ionic-native` relies on transparent backgrounds to [work](https://github.com/mapsplugin/cordova-plugin-googlemaps#how-does-this-plugin-work-android-ios). Commit [f68c457](https://github.com/ionic-team/ionic/commit/f68c457c06839c7d6dffc8624bc061533bf54478) as part of v4.0.0-beta.12 introduced a change on L46 in `core/src/components/content/content.scss` which results in the map not appearing.

I have verified this by running the app in an Xcode simulator, and using Safari developer tools to set `background:transparent` on the `div.inner-scroll` element to display the map. @brandyscarney's response [here](https://github.com/ionic-team/ionic/issues/15849#issuecomment-427081054) makes a valid justification of why this change was made. So, what's the most elegant way to make `.inner-scroll` transparent again? Using CSS to add the property `background:transparent` causes elements below to be rendered on screen transitions which is undesirable.

cc @wf9a5m75 

**Steps to Reproduce**
1. Clone [this demo](https://github.com/mapsplugin/ionic-googlemaps-quickdemo-v4) and run in an iPhone emulator and see how the maps work.
2. Clone [this branch](https://github.com/zaarheed/ionic-googlemaps-quickdemo-v4/tree/update-to-beta15) where I have updated to `beta.15` and run in an iPhone emulator and see how the maps do not appear.
3. Use Safari Developer Tools to add the `background: transparent` style to the `.inner-scroll` element and the maps will appear.
4. Press the side menu button to execute a transition and notice the effect of the transparency

**Related Code**
Pre-beta.15: https://github.com/mapsplugin/ionic-googlemaps-quickdemo-v4
After updating to beta.15: https://github.com/zaarheed/ionic-googlemaps-quickdemo-v4/tree/update-to-beta15

**Expected Behavior**
Google map to appear.

**Additional Context**
Gif attached display blank screen for map, but HTML elements (markers on the map) are rendering and being display fine.
![cordova-googlemaps-regression-bug](https://user-images.githubusercontent.com/17533006/48291556-d96af100-e46e-11e8-9a7a-45cab07604bd.gif)

**Comment by wf9a5m75** [comment]
Use the multiple_maps branch version.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...
```

**Comment by zaarheed** [comment]
Thanks @wf9a5m75 that worked. How stable in the `multiple_maps` branch and whats the best way of knowing when it is merged in to `master`?
