### ISSUE TITLE
Datetime flips HH:mm to mm:HH in RTL

### ISSUE THREAD

**Issue by Newbie012** [ionic-team/ionic#16294]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (C:\Users\Eliya\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.8.7
   @angular-devkit/schematics    : 0.8.7
   @angular/cli                  : 6.2.7
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.1, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (E:\android-sdk)
   NodeJS            : v10.11.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Describe the Bug**
Using:

```
<html dir="rtl">
...
<ion-datetime display-format="HH:mm"></ion-datetime>
```

Will flip the numbers from HH:mm to mm:HH. This shouldn't be happen even on RTL languages.

**Steps to Reproduce**
1. add `[dir="rtl"]` to `<html>`
2. add `<ion-datetime display-format="HH:mm"></ion-datetime>`
4. See occurence

**Related Code**
Showed above

**Expected Behavior**
HH:mm should stick as HH:mm even on RTL.

**Additional Context**

![image](https://user-images.githubusercontent.com/10504365/48317455-3eebe880-e5fb-11e8-9170-6d0e42db7a86.png)

**Comment by paulstelzer** [comment]
Thanks for your issue! I saw you created different issues for RTL issues. There are many more issues related to RTL, so it will take some time to fix all!

**Comment by mohamedsharaf** [comment]
I agree date default reading is ltr 

But i think for global make right to left as the default for both date and time and who need ltr add direction to the element to force ltr
