### ISSUE TITLE
Ionic 4 library build - BUILD ERROR error TS5060: Option 'paths' cannot be used without specifying '--baseUrl' option.

### ISSUE THREAD

**Issue by ebeling** [ionic-team/ionic#16298]
I like to build a library for sharing it with team. Since Angular 6 this is possible. So I created a new blank ionic project with:
`ionic start myApp blank --cordova`
Then I created a library with:
`ng generate library xxxlib`
if I try to package the library with:
`ionic build --project xxxlib`
an error occures:

```
...
Building Angular Package
Building entry point 'xxxlib'
Compiling TypeScript sources through ngc

BUILD ERROR
error TS5060: Option 'paths' cannot be used without specifying '--baseUrl' option.
```

I found following bug and fix for angular-cli:
https://github.com/angular/angular-cli/issues/11258

This is not the same problem, because here was speaking about a migration but can it be, that the ionic starter script is also not writing the necessary baseUrl to tsconfig.json ?

`ionic info`

Ionic:

   ionic (Ionic CLI)             : 4.3.1 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.8.6
   @angular-devkit/schematics    : 0.8.6
   @angular/cli                  : 6.2.6
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   NodeJS : v8.12.0 (/usr/bin/node)
   npm    : 6.4.1
   OS     : Linux 3.16

**Comment by paulstelzer** [comment]
Thanks for your issue! I think you missed something. Could you please create a new Ionic 4 project?

Keep i mind to update the ionic cli to the latest version before!

**Comment by paulstelzer** [comment]
UPDATE: I saw you try to create a library, this is a feature of Angular. So it can be not implemented on Ionic. If you need library support, please open this a Feature Request and tell us the use case and more information about it!

**Comment by ebeling** [comment]
I implement services, which I like to use in more than one ionic project. That's why I need library support. 
And the problem above I solved with adding a compilerOption in tsconfig.json:
` "compilerOptions": {
    "baseUrl": "./projects",
...
}`

It should be possible to add this automatically while generating Ionic project!
