### ISSUE TITLE
using multiple pages as one module

### ISSUE THREAD

**Issue by ghonche-yqr** [ionic-team/ionic#16293]
### **how can i have multiple pages as one module?**
For example, if I have 2 pages: first page shows all users as a list and the second one shows the user's details which has been selected.
these two pages perform as one component called _user-page_  **and also share common functions and variables.**
 
using **Ionic v1**, I could use one controller in multiple pages of html. how can i have structure like this in **Ionic v3**?
i also care about the code being well-structured and clean.

@jgw96 posted in https://github.com/ionic-team/ionic/issues/12333# :

>The next version of generators, which is coming out soon, is going to make it optional to add a separate module for each page, therefore allowing you to customize it however you would like it. Thanks for using Ionic!

any news??

**Comment by dylanvdmerwe** [comment]
This is something that can be done in v4.

**Comment by ghonche-yqr** [comment]
> This is something that can be done in v4.

Can you help me how? I would appreciate  If it's possible to send a link to a tutorial.

**Comment by paulstelzer** [comment]
If you need it with Ionic 3, please use the v3 repository (https://github.com/ionic-team/ionic-v3). This issues are v4 only!

As @dylanvdmerwe said using Ionic 4 is no problem because it uses Angular Router and there you have all this possibilities -> https://angular.io/guide/lazy-loading-ngmodules

**Comment by dylanvdmerwe** [comment]
I think this is something that should be moved to the forums. However a v4 app is just an Angular app. Modules behave exactly as they do with any Angular app in v4. 

As such, you define the routes in the module and then declare in the module's declarations the pages/components you want to include in the module.

**Comment by ghonche-yqr** [comment]
Thanks you very much. I can fix my problem using ionic v4👌🏼
