### ISSUE TITLE
Ionic 4: ion-item-sliding not working with ion-sgement

### ISSUE THREAD

**Issue by Hasilt** [ionic-team/ionic#16290]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (C:\Users\justlabtech1\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.8.7
   @angular-devkit/schematics    : 0.8.7
   @angular/cli                  : 6.2.7
   @ionic/angular-toolkit        : 1.1.0

System:

   NodeJS : v8.11.3
   npm    : 5.6.0
   OS     : Windows 10
```

**Describe the Bug**
ion-item-sliding stop responding to touches and click events if user switches segment while one of the list item is open (slided left or right).

**Steps to Reproduce**
1. Create a ion-segment with more than one ion-segment buttons, then create another div with `ngSwitch` directive to switch segments. for each switch case add some `ion-item-sliding` with `ion-item-options`.
2. Switch segments while one of the `ion-item-sliding` is in open position (slided condition).
4. See that click item-sliding won't make it slide.

**Additional Context**
A quick work around is to close the list item programmatically whenever a segment change event is fired.

**Comment by CRivasGomez** [comment]
Hey @Hasilt 🙂

Probably the workaround solution for this issue is the same as the workaround for #15486 (closing all `ion-item-sliding`s from the `ion-list` previously).

**Comment by brandyscarney** [comment]
Thanks for the issue! Is this still an issue in latest (`4.1.1`)? Issue #15486 has been closed. 🙂

**Comment by Hasilt** [comment]
I'm not seeing any problems mentioned on this issue in the latest version (4.1.1). I'm closing this issue now.
