### ISSUE TITLE
Ionic.beta15 iPhone X issue with popover list

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic#16306]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Beta.15
```

**Describe the Bug**
In iPhoneX for popever if it contains list item then safe-area-padding is been applied to it

![Uploading Screenshot 2018-11-13 at 12.51.10 PM.png…]()

**Comment by maddada** [comment]
Can't see the screenshot

**Comment by stripathix** [comment]
Attaching it again.
<img width="126" alt="screenshot 2018-11-13 at 12 49 54 pm" src="https://user-images.githubusercontent.com/8480351/48406817-6d80d500-e75b-11e8-99c9-b6bef85341d1.png">
<img width="695" alt="screenshot 2018-11-13 at 12 51 10 pm" src="https://user-images.githubusercontent.com/8480351/48406832-77a2d380-e75b-11e8-95ac-49dcf3cb1dbe.png">

**Comment by stripathix** [comment]
It looks good on other devices but iPhoneX has this issue.

**Comment by paulstelzer** [comment]
Thanks for your issue! But I didn't understand what's the issue?

**Comment by stripathix** [comment]
Look at these screenshots If I remove html var safe-area padding left/right in iphoneX landscape mode. Then popover list is right.
<img width="966" alt="screenshot 2018-12-07 at 8 17 18 pm" src="https://user-images.githubusercontent.com/8480351/49654183-28e81100-fa5d-11e8-8bf8-79d81a36ecc0.png">
<img width="945" alt="screenshot 2018-12-07 at 8 16 59 pm" src="https://user-images.githubusercontent.com/8480351/49654184-28e81100-fa5d-11e8-9f0d-bdbd6c5720be.png">
