### ISSUE TITLE
[ionic 4-beta.15] ion-label doesnt float properly with ion-textarea

### ISSUE THREAD

**Issue by idanzapp** [ionic-team/ionic#16303]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (C:\Users\Samir\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.10.5
   @angular-devkit/schematics    : 7.0.5
   @angular/cli                  : 7.0.5
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (C:\Users\Samir\AppData\Local\Android\Sdk)
   NodeJS            : v10.9.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Describe the Bug**
you need to actively focus on `<ion-textarea>` to get a working `<ion-label position=float>`

in this image `<ion-input>` the label is floating well into a form with the default data
but on  `<ion-textarea>`  the label isnt floating
![floating](https://user-images.githubusercontent.com/26038595/48370244-06aadf80-e6b9-11e8-815e-531d2816fcd4.png)

in this one after select the `<ion-textarea>`
the floating start working
![focusontextarea](https://user-images.githubusercontent.com/26038595/48370246-07437600-e6b9-11e8-9b0c-29cf064175b9.png) 

**Expected Behavior**
When `<ion-textarea>` got default data, his label should float.

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm not able to reproduce this in latest using `4.0.0-beta.16` in either `core` or `angular`. If you are still seeing this in latest, please create a new issue with a repository or way for us to reproduce. Thanks!
