### ISSUE TITLE
在ionic4 variables.scss 如何自定义颜色，像ionic3中一样

### ISSUE THREAD

**Issue by wangli1992** [ionic-team/ionic#16316]
# Support Question

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Comment by thcathy** [comment]
This two link on ionic 4 documented how to override the color by css variable,

https://beta.ionicframework.com/docs/theming/css-variables
https://beta.ionicframework.com/docs/theming/color-generator
