### ISSUE TITLE
Ionic input fields are not compatible with with lastpass

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic#16310]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Using ionic beta.15 via CDN
```

**Describe the Bug**
Last pass does not fills any input fields and i dont even see any lastpass icons in my email/password fields

**Related Code**
```
<form id="loginregisterformprimary" name="loginregisterformprimary" novalidate>
             <ion-item>
              <ion-label>Email</ion-label>
              <ion-input autocomplete="on" type="email" v-on:keyup.13="accountFormSubmit"  v-validate="'required|email'" name="username" :value="accountDetail.useremail"  @ionInput="accountDetail.useremail = $event.target.value" placeholder="Enter Your Email"></ion-input>
            </ion-item>
            
            <ion-item>
              <ion-label>Password</ion-label>
              <ion-input autocomplete="on" v-validate="'required'" v-on:keyup.13="accountFormSubmit" name="password"  type="password" :value="accountDetail.userpassword" @ionInput="accountDetail.userpassword = $event.target.value" placeholder="Enter Your Password"></ion-input>
            </ion-item>
            <ion-button shape="round" color="warning" id="loginbutton" :disabled="errors.any() || !isLoginFormComplete"  v-if="visibleViewIndex == 2" v-on:click="loginNow()" expand="full">
                Login
            </ion-button>
          </form>
```

**Expected Behavior**
Should be compatible with LastPass as it is pretty commonly used extension.

I am not sure if it is Ionic issue or lastpass issue.

**Comment by paulstelzer** [comment]
I think this is not a problem of lastpass, I think it's a problem because Ionic uses shadow dom and so Lastpass has to access to it

**Comment by paulstelzer** [comment]
Talked with the Ionic Dev team, this could be fixed with the next beta :)

**Comment by mmlleevvyy** [comment]
@paulstelzer any chance it will be fixed in in next rc/final release? for cordova/capacitor app is not a problem, but for web app it is, as password cannot be remembered by the browser.

**Comment by paulstelzer** [comment]
if it's not fixed with rc.0, then it's a problem with shadow dom and cannot be fixed. could you check?

**Comment by mmlleevvyy** [comment]
@paulstelzer Not fixed in rc.0 for sure and yes it is well known problem of shadow dom, but it can be fixed, either by disabling shadow for input component or allowing to add `<input>` as child element of `<ion-input>` and using making that child "native-input", although I don't if it is possible in stencil write "conditional render" function. @manucorporat any thought on that issue?

**Comment by paulstelzer** [comment]
ion-input has already no shadow dom, if you analyze in DOM, there you can see a native input field

**Comment by paulstelzer** [comment]
@mmlleevvyy I know, see my feature request -> https://github.com/ionic-team/ionic/issues/17020

**Comment by mmlleevvyy** [comment]
@paulstelzer Great! Thanks for FR, it is exactly how I see it.

**Comment by manucorporat** [comment]
This should be fixed in master!
