### ISSUE TITLE
[ionic 4-beta.15]Tabs is not working on ios10[safari10]

### ISSUE THREAD

**Issue by hr1992** [ionic-team/ionic#16317]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.0
   Ionic Framework            : @ionic/angular 4.0.0-beta.15
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.1.0
   @ionic/schematics-angular  : 1.0.7

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.3.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, (and 11 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 6.1.3
   NodeJS     : v10.13.0 (/Users/favrio/.nvm/versions/node/v10.13.0/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : not set
```

**Describe the Bug**

Tabs is not working on ios10, the :host style is disappeared on the ion-tab-bar elements.

**Steps to Reproduce**
1. Just use safari10 of the simulator to visit the official demo url linked below.
`https://beta.ionicframework.com/docs/content/api/tabs-demo.html?ionic:mode=ios&ionic:statusbarPadding=true`
2. See error

![image](https://user-images.githubusercontent.com/4222261/48472222-be163200-e830-11e8-8571-1ef613dd1c5d.png)

**Comment by paulstelzer** [comment]
Thanks for the issue! Could you please check if this is still an issue in `beta.17` and is this also happening on a REAL device (no simulator)? That would be very nice :)

**Comment by hr1992** [comment]
> Thanks for the issue! Could you please check if this is still an issue in `beta.17` and is this also happening on a REAL device (no simulator)? That would be very nice :)

Thanks for your reply, i will try this later and  give a feedback to this issue.
