### ISSUE TITLE
Ionic bug: click on button to open alert and keep pressing enter unlimited numbers of popup will open as you keep pressing enter.

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic#16313]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Beta.15
```

**Describe the Bug**
Ionic bug: click on the button to show alert and keep pressing enter unlimited numbers of popup will open as you keep pressing enter.

**Steps to Reproduce**
1. Go to https://beta.ionicframework.com/docs/components#alert
2. Click on Show Alert
3. Press Enter multiple times

**Expected Behavior**
It should not open new alert when already previous is open

**Comment by KevinKelchen** [comment]
The same behavior occurs with pressing spacebar.
