### ISSUE TITLE
ion-input support for the list attribute

### ISSUE THREAD

**Issue by badpenguin** [ionic-team/ionic#16321]
# Feature Request

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1( ~/.npm-packages/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.8.7
   @angular-devkit/schematics    : 0.8.7
   @angular/cli                  : 6.2.7
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (~/.bin/android-sdk-linux)
   NodeJS            : v10.13.0 (/usr/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.15

```

**Describe the Feature Request**
Looking at the source of the ion-input component there is no way to add custom attributes.
I need the "list" attribute to be passed down to the HTML input in order to use datalist with ion-input.

**Describe Preferred Solution**
Add @Prop to the stencil component to suppot the list attribute.

**Comment by virgil-av** [comment]
This is still not included.

**Comment by virgil-av** [comment]
I find a workaround to make this work, but it is very annoying that there is no simple way to pass attributes, well to save others from spending time on finding a temporary solution here is an example on how to add a datalist to an ion-input type text.

I created a directive to manage this for me.

import {AfterViewInit, Directive, Renderer2} from '@angular/core';
import {IonInput} from '@ionic/angular';


@Directive({
    selector: '[addListAttribute]'
})
export class AddListAttributeDirective implements AfterViewInit {

    constructor(private el: IonInput, private renderer: Renderer2) {
    }

    ngAfterViewInit() {
        this.getInputElement(this.el);
    }

    getInputElement(elRef: IonInput) {
        elRef.getInputElement().then((input: HTMLInputElement) => {
            this.renderer.setAttribute(input, 'list', 'idOfdataList');
        });
    }

}

**Comment by Maikell84** [comment]
> I find a workaround to make this work, 

Thank you for this workaround.

>but it is very annoying that there is no simple way to pass attributes, 

+1


Is there any chance, that this feature will be added in ionic in the future?
