### ISSUE TITLE
[4.0.0-beta.15] dual knob range component doesn't function properly

### ISSUE THREAD

**Issue by maartun** [ionic-team/ionic#16342]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.8.7
   @angular-devkit/schematics    : 0.8.7
   @angular/cli                  : 6.2.7
   @ionic/angular-toolkit        : 1.2.0

System:

   NodeJS : v8.11.3 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS High Sierra
   Chrome: 70.0.3538.102
```

**Describe the Bug**
This bug occurs in Chrome(I'm using 70.0.3538.102) while using a dual knob range component. The left knob doesn't move while dragging and the active range bar is drawn incorrectly when dragging the left knob to the right.

**Steps to Reproduce**
1. Go to https://ionicframework.com/docs/api/components/range/Range/
2. Click on the Android button above the mobile screen
3. Drag the left knob in the fourth range component to the left.
4. The knob stays put and doesn't move while dragging but the active range bar and pin are drawn correctly.
5. Release the knob and the knob stays put.
6. Now drag the knob to the right, again the knob stays put but this time the active range bar is drawn incorrectly.

**Expected Behavior**
While dragging the left knob, the knob should move along the bar with the mouse. Secondly, the active range bar should be drawn correctly when moving the left knob to the right.

**Comment by paulstelzer** [comment]
You refer to Ionic v3. For the range v4 see -> https://beta.ionicframework.com/docs/api/range

There is also a dual knob and this is working

**Comment by bryce13950** [comment]
Is this still an issue in the current beta?

**Comment by paulstelzer** [comment]
@bryce13950 I think it's fixed

**Comment by bryce13950** [comment]
Cool
