### ISSUE TITLE
[v4] ion-checkbox .checked not reflected in aux-input

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic#16365]
# Bug Report

**Ionic Info**

```
@ionic/core@4.0.0-beta.15
```

**Describe the Bug**

I'm using an `ion-checkbox` inside a form and access the input's `checked` value, however it always returns `false`.

**Steps to Reproduce**

```tsx
@Component({ tag: 'my-page' })
export class MyPage {
  @Method()
  getData() {
    return { checkbox: this.form.checkbox.checked };
  }

  form: HTMLFormElement | undefined;

  render = () => (
    <form ref={el => (this.form = el)}>
      <ion-checkbox name="checkbox" />
    </form>
  );
}
```

**Expected Behavior**

It should return the proper value, i. e. `true` if checked.

**Additional Context**

Accessing the value of the `input[type="checkbox"]` inside the Shadow DOM returns the correct value. Seems that it's not reflected to the `input[type="hidden"].aux-input` (outside the Shadow DOM) properly. Similar thing might happen with `ion-toggle`, but haven't tried.

BTW @manucorporat in #16074 you said that `value` of checkboxes/toggles can only be used inside forms, however that would mean i would need to manually toggle the `value` property from `on` to `off`, right? Because it doesn't just update when toggling the input (as it's an immutable prop within the component).

**Comment by manucorporat** [comment]
This should be fixed in beta.16
