### ISSUE TITLE
"TypeError: Cannot read property 'forEach' of undefined" in IE 11.

### ISSUE THREAD

**Issue by royanon** [ionic-team/ionic#16368]
# Bug Report

**Ionic Info**

Ionic:

   ionic (Ionic CLI)             : 4.2.1 
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10

**Describe the Bug**
Ionic element such as ion-input use with ngModel will cause "TypeError: Cannot read property 'forEach' of undefined" in IE 11. (Polyfill for IE 11 has been enabled)

**Steps to Reproduce**
1. add a ngModel in ion-input <ion-input type="text" [(ngModel)]="message"><ion-input>
2. ng serve and view in IE 11
3. See error "TypeError: Cannot read property 'forEach' of undefined"

**Related Code**
setIonicClasses

**Additional Context**
To fix the problem, Transform DOMTokenList to array in ion-input, then the problem can be fixed.

**Comment by paulstelzer** [comment]
Add the polyfills to your polyfills.ts - this is related to Angular, not Ionic

**Comment by manucorporat** [comment]
Fixed by https://github.com/ionic-team/ionic/commit/e76544d0f4e4bb31664d83d335156418b1fcea98
