### ISSUE TITLE
ion-back-button Unable to display， why？

### ISSUE THREAD

**Issue by wangli1992** [ionic-team/ionic#16369]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

根据api文档，使用ion-back-button，页面返回按钮无法显示

**Related Code**

<ion-header >
  <ion-toolbar mode="ios" color="primary">
      <ion-buttons slot="start" >
           <ion-back-button   icon="arrow-back" >  
          </ion-back-button>  
        </ion-buttons>
    <ion-title>意见反馈</ion-title>
  </ion-toolbar>
</ion-header>

**Comment by homeportcz** [comment]
ion-back-button is not showed with 4.0.0-beta.16, works with 4.0.0-beta.15 (after router.navigate()).
