### ISSUE TITLE
Ionic beta.15 modal on iPads have status bar padding

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic#16374]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Using CDN beta.15
```

**Describe the Bug**
iPad modal headers have a status bar padding

**Steps to Reproduce**
1) Open any modal with a header on iPad.

<img width="1280" alt="screenshot 2018-11-19 at 4 43 23 pm" src="https://user-images.githubusercontent.com/8480351/48703767-c6001880-ec1a-11e8-8163-0243a3954712.png">

**Expected Behavior**
iPad modals are not fullscreen so they should not have status bar padding.

**Comment by stripathix** [comment]
I am using below CSS to handle this issue till ionic fix it

```
@media only screen and (min-height: 600px) and (min-width: 768px){
  ion-modal ion-header ion-toolbar:first-child{
    padding-top: 0px;
  }
}
```

**Comment by bryce13950** [comment]
Is this still an issue with beta 17?

**Comment by manucorporat** [comment]
This was fixed by https://github.com/ionic-team/ionic/commit/235c6859d27b06c9c71fabc896cdc930e2a99643!
