### ISSUE TITLE
有关论坛账号使用的问题

### ISSUE THREAD

**Issue by gdongy** [ionic-team/ionic#16386]
你好，我知道这个问题不应该放在这里，但是我通过论坛找到找到邮箱（max@drifty.com）进行反馈但是没有回应，所以在这里希望能被看到，帮助解决，谢谢；
问题是这样的，我的ionic  name dongyang username gdongy 邮箱 992443408@qq.com可以登录进入到项目（https://dashboard.ionicframework.com/apps），但是进入论坛的时候会登录失败，提示账号有问题，请联系管理员，谢谢

**Comment by UTSOURCE** [comment]
我之前也是，然后换邮箱，不用qq邮箱了

**Comment by gdongy** [comment]
换成163还是谷歌邮箱？

**Comment by UTSOURCE** [comment]
我用的微软的邮箱，你可以用谷歌的邮箱
