### ISSUE TITLE
ios app crashes on simulator while running proper on real devices

### ISSUE THREAD

**Issue by amitqfix1947** [ionic-team/ionic#16387]
Steps to reproduce:
Ran the command - ionic cordova emulate ios
After installing the app on simulator it opens for few seconds(around 3-5 sec.) and then app automatically crashes.

Again each time if try to open app on simulator then it shows blank screen then app crash. 

ionic information
ionic 3.20.0
cordova 6.5.0

ios information
xcode- 10

**Comment by paulstelzer** [comment]
This is the wrong repository: You ae using ionic-v3, this is related to v3 -> https://github.com/ionic-team/ionic-v3

And from my point of view, this issue is related to Cordova not Ionic
