### ISSUE TITLE
ion-toolbar with translucent set has broken back animation

### ISSUE THREAD

**Issue by ctcampbell** [ionic-team/ionic#16382]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (/Users/ccampbell/.nvm/versions/node/v10.12.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 0.8.7
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.3, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/ccampbell/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 7.0.0
   NodeJS            : v10.12.0 (/Users/ccampbell/.nvm/versions/node/v10.12.0/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.1 Build version 10B61
```

**Describe the Bug**
ion-toolbar does not animate back properly if translucent is enabled

**Steps to Reproduce**
Create a master/detail view. Set ion-toolbar to translucent on detail page.

**Expected Behavior**
Back animation should appear to be smooth

**Additional Context**

![toolbar](https://user-images.githubusercontent.com/808531/48733527-ce684b80-ec3a-11e8-8a82-9babd0c174ae.gif)

**Comment by olivermuc** [comment]
It gets even much worse when on top of the translucent header you add a background to `ion-content`, eg `--background: linear-gradient(-205deg, var(--oia-page-background-from) 0%, var(--oia-page-background-to) 50%)`.

There is a ton of flickering and page backgrounds briefly shining through the animation / page transition.
