### ISSUE TITLE
[4.0.0-beta.16] unable to load local assets

### ISSUE THREAD

**Issue by berchik** [ionic-team/ionic#16397]
**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (C:\Users\jo\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0

System:

   NodeJS : v10.11.0 (A:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
I'm trying a PWA and the following not working in development nor when deployed:
`<img src="assets/img/t.jpg" />`

The image is there, the path is correct, and any other experiments with images/paths are not working as well. Using firebase storage it works and the image is loaded. Seems like the assets folder is not created correctly.

**Comment by redwolf2** [comment]
Try `<img src="/assets/img/t.jpg" />`

**Comment by paulstelzer** [comment]
Check your angular.json that the assets folder is included

**Comment by berchik** [comment]
@paulstelzer that’s one of the first places I've looked.

Anyway, I've started a **new project, angular, blank** (CLI 4.4.0 / @ionic/angular 4.0.0-beta.16) Then added `img` to the home page, pointing to the auto-created assets folder. Serving, I get 404 just like before.

**Comment by paulstelzer** [comment]
As you can see image is shown:

![code_2018-11-21_15-10-35](https://user-images.githubusercontent.com/20501666/48846518-9b8b9800-ed9f-11e8-95a2-3f1b71e45e6e.jpg)

**Comment by berchik** [comment]
And this is what I get:
![image1](https://user-images.githubusercontent.com/13700472/48850693-deef0200-edb1-11e8-9ede-0c7529f1e3a1.jpg)

Any ideas?

**Comment by berchik** [comment]
This is yours:

![image2](https://user-images.githubusercontent.com/13700472/48851548-05ae3800-edb4-11e8-8bfb-95fb3b1c1b36.jpg)

**Comment by berchik** [comment]
I've found the problem. My project is inside Dropbox folder which imposes the name - 

> H:\Dropbox (Personal)\

and the compilation skips some packing. Even when creating a folder alias and working from there it fails. The only solution was to take it out of Dropbox. It used to work on win10 machine but not anymore I guess.

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this since it doesn't seem like it's an Ionic problem, but let me know if you think this is incorrect and it should be looked into. Thanks!
