### ISSUE TITLE
ion-datetime returns Object in ngModel

### ISSUE THREAD

**Issue by Nick-lab** [ionic-team/ionic#16398]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (C:\Users\Brian\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.12
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.3, (and 5 other plugins)

System:

 (C:\Users\Brian\AppData\Local\Android\android-sdk)
   NodeJS            : v9.2.0 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10

```

**Describe the Bug**
ion-datetime output is object and in the docs there is a mixture of camel case and hyphen so un-clear of which to use. 

```
{
    ampm: {text: "PM", value: "pm", columnIndex: 2},
    hour: {text: "10", value: 22, columnIndex: 0},
    minute: {text: "10", value: 10, columnIndex: 1}
}
```

**Steps to Reproduce**
just use a datetime component and console out the result.

**Related Code**
`<ion-datetime name="out" display-format="hh:mm A" picker-format="hh:mm A" [(ngModel)]="task.out" placeholder="Default Clock Out Time"></ion-datetime>`

**Expected Behavior**
String Output of time e.x "09:00 AM"

**Comment by manucorporat** [comment]
could you please update to beta.16 and try again?

**Comment by manucorporat** [comment]
I will close since I can't longer reproduce, feel free to reopen
