### ISSUE TITLE
Ionic Team there is lots of issues with ionic. I feel waste of time using iconic.

### ISSUE THREAD

**Issue by baljeetkalsi** [ionic-team/ionic#16402]
Ionic Team there is a lot of issue with ionic. 
I feel waste of time using iconic.

1. There is no proper documentation

2.  Base64 , InAppBrowser, InAppBrowserOptions , FileOpener and all file related library does not work. 

3. It take days on forum to get a answer (Even the posted  answer is not correct)

4. No proper example are provided.

5. Issue are pending from months but no solution.

6. Cannot open PDF in android. 

7. JavaScript functions are not working

Please reply, why there is so much issue on this platform. 

If you cannot solve problems or give update please stop doing drama and tell us clear so we can move to other framework.

**Comment by manucorporat** [comment]
1. Ionic is an open source community that develops a collection of UI components to build applications, we don't give free courses of software development.

2. Github issues should be used by users to report legit issue reports.

3. Github is not the place for trolling

4. Any member of the community includes the Ionic Team needs to follow the Code of Conduct.

5. Be nice!

Closing issue for now following the CoC
https://github.com/ionic-team/ionic/blob/master/CODE_OF_CONDUCT.md

I encourage you to approach your questions with a nicer tone! check out the [forum](https://forum.ionicframework.com) or our [slack channel](https://ionicworldwide.herokuapp.com/).
