### ISSUE TITLE
[4.0.0-beta.16] Checkbox ignoring model state

### ISSUE THREAD

**Issue by jsessink** [ionic-team/ionic#16400]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\ND20334\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.16
   @angular-devkit/core       : 7.0.6
   @angular-devkit/schematics : 7.0.6
   @angular/cli               : 7.0.6
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : browser 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 12 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Android\android-sdk)
   NodeJS            : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm               : 6.3.0
   OS                : Windows 10
```

**Describe the Bug**
Upgraded from beta.15 to beta.16 and no longer have initially set checkboxes through Angular (both, ngModel, or ReactiveForms's setValue on a formControl).

**Steps to Reproduce**
Add ion-checkbox to a page with an ngModel hooked up.  Change the property on init. Checkbox stays with initial value, even though form control updates.

**Related Code** 

_HTML_
```html
<ion-checkbox [(ngModel)]="test"></ion-checkbox>
```

_TS_
```javascript
public test = false;

public ngOnInit() {
    this.test = true;
}
```

**Expected Behavior**
Checkbox to appear as checked.

**Comment by manucorporat** [comment]
This is already fixed in master!
