### ISSUE TITLE
[4.0.0-beta.16] ion-router-outlet issue tabs split-pane navigation broken / stops working

### ISSUE THREAD

**Issue by paulstelzer** [ionic-team/ionic#16411]
**Describe the Bug**
If you have a project with different layouts (with splitpane / without or another), pages with the same splitpane layout will not work. It's hard to describe, so I've added a repository (see below) and a gif:

![2018-11-21_15-23-59](https://user-images.githubusercontent.com/20501666/48847352-9891a700-eda1-11e8-9466-6861ebcbf87e.gif)

**Steps to Reproduce**
1. Click on "Open Dashboard". The splitpane appears.
2. Click on "Page 1" - everything is working
3. Click on "Fullscreen" and go back by tapping on "Open Dashboard".
4. Now try to open "Page 1" or "Page 2" again - it's not working
5. If I go back to home and open this route again, it's working until I leave the route, open a page with another layout and the same issue comes back

**Related Code**
https://github.com/paulstelzer/test-splitpane

**Comment by romain10009** [comment]
@paulstelzer I have the same issue, I have a split pane, I login, i logout, now all the split pane overlaps the app, the issue seems to be with the .menu-content-open 
![image](https://user-images.githubusercontent.com/7512202/49009271-7072c100-f170-11e8-8f64-125b5684b6c2.png)

**Comment by paulstelzer** [comment]
Found a workaround (or maybe this will be the one and only working solution):

I removed the `<ion-router-outlet>` from `app.component.html ` - so only one ion-router-outlet exist and then it's working

**Comment by paulstelzer** [comment]
@urbanjoe it's correct that you see the router-outlet destroyed message because I am destroy it (one page with sidebar -> going to fullscreen without sidebar, so the router oulet has to be destroyed). I make you a branch with a router-outlet destroyed and the navigation will still work ;) one moment

**Comment by paulstelzer** [comment]
@urbanjoe Is mentioned above I added an ISSUE, so my repo isn't working of course ;)

I added a new branch WORKING -> https://github.com/paulstelzer/test-splitpane/tree/working

This includes my workaround described here -> https://github.com/ionic-team/ionic/issues/16411#issuecomment-443186868

As you can see there is still the router-outlet destroyed, but this is CORRECT, because I destroy the ion-router-outlet if I change from one page to another. But as you can still see: the navigation is working ;)

![2018-12-14_14-46-26](https://user-images.githubusercontent.com/20501666/50006810-3ea28c80-ffaf-11e8-9f0e-40ae02cf247c.gif)

**Comment by paulstelzer** [comment]
@MattiLehtinen I think so, too that the root cause is `ion-router-outlet`. Many people describe this problem with `ion-tabs` (where `ion-router-outlet` is inside), too. I adjust the title of this issue

**Comment by paulstelzer** [comment]
That's no problem. We have maybe a fix for it and will test it with beta.19 which I hope will coming soon :)
