### ISSUE TITLE
What is the minimum supported version of Android and iOS version

### ISSUE THREAD

**Issue by ZeroxLim** [ionic-team/ionic#16412]
# Support Question

Hi ionic Team,

I developed an app with ionic v4 only to find out that the app doesn't work for iOS 10.2 and Android 6 (White screen after splash screen issue). I searched all over your documentation, doesn't seem to find the compatibility matrix. I found an issue for android, minimum version 7.1 is needed (https://github.com/ionic-team/ionic/issues/15426). What about iOS?

My App need to work in Android 6 and above and iOS 10 and above.

I am closing into the due date, only left 11 days before i need to deliver. Do you recommend me to downgrade to v3? I will really appreciate a quick reply on this, I need to take swift action now. 

Thanks,
Lim

**Comment by ZeroxLim** [comment]
Thanks for the quick reply, I really appreciate it.

Are there details steps on doing so? I not familiar with polyfills.

**Comment by RomeoDenis** [comment]
@ZeroxLim  ../src/polyfills.ts,  uncomment the required ones

**Comment by JayzeeHuang** [comment]
Some plugins caused the crash on Android 9, so will be better stay on ionic 3.

**Comment by c350156378** [comment]
https://ionicframework.com/docs/intro/browser-support/
https://beta.ionicframework.com/docs/intro/browser-support/#mobile

**Comment by ZeroxLim** [comment]
@RomeoDenis Thanks for the tips

Added core-js solve the iOS 10 white screen issue. But not android 6.0

I will proceed to downgrade to v3. Thanks everyone

**Comment by ZeroxLim** [comment]
@JayzeeHuang What is the recommended Angular version to go with ionic 3? (I am hoping for atleast v6)

**Comment by JayzeeHuang** [comment]
@ZeroxLim Ionic 3 comes with ng5, so latest 5.x working fine. Ionic 4 default with ng6, keep away from this just wait until the v4 get stable.

**Comment by ZeroxLim** [comment]
@JayzeeHuang Thanks a lot for your help.
