### ISSUE TITLE
[4.0.0-beta.16] Checkbox needs second tap to work

### ISSUE THREAD

**Issue by RHinderiks** [ionic-team/ionic#16410]
**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (/Users/rh/.nvm/versions/node/v8.11.4/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.5
   @angular-devkit/schematics    : 7.0.5
   @angular/cli                  : 7.0.5
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.2, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 13 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/rh/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.0.0
   NodeJS            : v8.11.4 (/Users/rh/.nvm/versions/node/v8.11.4/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61
```

**Describe the Bug**
When tapping a checkbox it no longer gets a color and a checkmark, it just stays "off" untill you tap it again. However the value itself does change to true and on the second tap stays true. Reverting to beta 15 makes it work again.

**Steps to Reproduce**
Just add a checkbox to a page and try to select it.

**Expected Behavior**
That it works like beta 15 did. You tap a checkbox, it turns a color and shows a checkmark, tap it again to remove the color and remove the checkmark

**Comment by paulstelzer** [comment]
Couldn't verfiy this. Or what do you mean? See:

![2018-11-21_15-06-31](https://user-images.githubusercontent.com/20501666/48846300-10aa9d80-ed9f-11e8-8620-046684b6e721.gif)

**Comment by RHinderiks** [comment]
Huh thats weird this does not work in our application on beta 16 but does work on beta 15. (both ios and android).

**Comment by paulstelzer** [comment]
Without a repo or code, I cannot help you

**Comment by RHinderiks** [comment]
I understand, ill work on trying to reproduce it on a simpler app. Right now i don't quite have the time to so.

**Comment by camwiegert** [comment]
@RHinderiks There were some changes to checkbox in beta-16, so please let me know if you're able to reproduce elsewhere. For what it's worth, I wasn't able to reproduce. I'll leave this open for a bit. Thanks!

**Comment by genadis** [comment]
maybe it's related to https://github.com/ionic-team/ionic/issues/16435 ?

**Comment by RHinderiks** [comment]
It could be, will be waiting for next release to see if its fixed
