### ISSUE TITLE
Shadow Dom not supported in Edge

### ISSUE THREAD

**Issue by majorbenks** [ionic-team/ionic#16414]
We migrated to ionic 4.3.1 and found that many components use shadow dom. Edge doesn't have shadow dom and ionic controls end up not working in Edge.
 
Will there be support for Edge / Browsers not having shadow dom?
Is there a way to disable shadow dom (even in production mode) or better, based on the used browser?
Can this issue be solved by configuration?

Thank you!

**Comment by paulstelzer** [comment]
ionic 4.3.1 is just the cli, you have to use `@ionic/angular` and if you update to beta.16, it's working in Edge, too

**Comment by majorbenks** [comment]
Yes, it was @ionic/angular beta.15, I updated now to beta.16. Sorry about that!

Unfortunately, it looks like Edge still doesn't work with beta.16. 
e.g. radios and checkboxes do not work in Edge. If you click exactly on the tick mark/checkbox, it doesn't do anything (even in the demo in the docs: https://beta.ionicframework.com/docs/api/button)
Also, buttons with expand="full" and slot="start"/"end" inside a ion-toolbar (and toolbar is inside a ion-footer) are stacked in Edge instead of next to each other like in Chrome or FF. 

I'm not sure though, if this is actually because of shadow dom, but I believe so, because Firefox ESR (not having shadow dom either) behaves the same way.

**Comment by paulstelzer** [comment]
@majorbenks my app is made with Ionic 4 -> https://game.iqtest-app.de/settings

And it looks good in Edge:
![applicationframehost_2018-11-22_09-59-41](https://user-images.githubusercontent.com/20501666/48892046-58800200-ee3d-11e8-8ade-678ab698422c.jpg)

**Comment by majorbenks** [comment]
Interesting.. I do the same thing, but clicking on the circle doesn't do anything. I have Edge 42 / EdgeHTML 17.
By the way, I found a work around: It works when I set the z-index to 0 on ion-radio and ion-checkbox.

**Comment by paulstelzer** [comment]
The Edge team seems to fixed it. I am already on Edge 44 / EdgeHTML 18

![applicationframehost_2018-11-22_11-17-13](https://user-images.githubusercontent.com/20501666/48896573-3344c100-ee48-11e8-8c05-be1400583e16.jpg)
