### ISSUE TITLE
[Angular Beta 16] Build performance degradation

### ISSUE THREAD

**Issue by Tiberriver256** [ionic-team/ionic#16423]
# Bug Report

**Ionic Info**
I am using the Angular CLI instead of the Ionic CLI so I will include my package.json instead to be hopefully helpful

```
﻿{
  "name": "testapp",
  "version": "0.0.0",
  "scripts": {
    "ng": "npm run copy-ionic-angular && ng",
    "serve": "npm run copy-ionic-angular && ng serve",
    "serve.aot": "npm run copy-ionic-angular && ng serve --aot",
    "build": "npm run copy-ionic-angular && ng build",
    "build.aot": "npm run copy-ionic-angular && ng build --aot",
    "build.prod": "npm run copy-ionic-angular && ng build --prod --aot",
    "test": "npm run copy-ionic-angular && ng test",
    "lint": "npm run copy-ionic-angular && ng lint",
    "e2e": "npm run copy-ionic-angular && ng e2e",
    "copy-ionic-angular": "node ../../scripts/link-copy.js ionic/angular/test/testapp"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.1.0",
    "@angular/common": "^7.1.0",
    "@angular/compiler": "^7.1.0",
    "@angular/core": "^7.1.0",
    "@angular/forms": "^7.1.0",
    "@angular/http": "^7.1.0",
    "@angular/platform-browser": "^7.1.0",
    "@angular/platform-browser-dynamic": "^7.1.0",
    "@angular/router": "^7.1.0",
    "@ionic/angular": "^4.0.0-beta.16",
    "core-js": "^2.5.7",
    "rxjs": "^6.3.3",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.10.6",
    "@angular/cli": "^7.0.6",
    "@angular/compiler-cli": "^7.1.0",
    "@angular/language-service": "^7.1.0",
    "@types/jasmine": "^2.8.12",
    "@types/jasminewd2": "^2.0.6",
    "@types/node": "~8.9.4",
    "codelyzer": "^4.5.0",
    "ionicons": "^4.4.7",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.4.3",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.4.1",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~3.1.6"
  }
}

```

**Describe the Bug**
When using ```ng serve`` or ```ng build --watch=true``` you make a change to a file and save it. It will take 12-15 seconds to recompile compared to just over 1 second on beta 6.

**Steps to Reproduce**
Upgrade the Angular test app in this project to the latest and greatest and then run ```ng serve``` and make any changes.

**Related Code**
My sample:
https://github.com/Tiberriver256/ionic/tree/master/angular/test/testapp

**Expected Behavior**
I would love to have it back down near 1 second as it makes the developer experience not very fun waiting so long. I have a different project that is larger than the testapp and I'm getting upwards of 40-50 seconds to recompile.

Hopefully it's just something I am doing wrong. Thank you!

**Comment by Tiberriver256** [comment]
Could be a duplicate of #15844 although upgrading to Node 10 does not improve it much. I tried Node 8, 10 and 11 and all still way slower than it was previously.

**Comment by paulstelzer** [comment]
Can confirm on beta.16 - Fork this repository and build the latest version of ionic - the build time to recompile decrease by 50 percent.

**Comment by manucorporat** [comment]
We updates to Angular 7 and TS 3.0, that's the only relevant change i can think of

**Comment by Tiberriver256** [comment]
Possibly related:
https://github.com/angular/angular-cli/issues/12646

**Comment by manucorporat** [comment]
Going to close since it does not seem related with ionic!
