### ISSUE TITLE
Using the ion-navbar shows empty blank

### ISSUE THREAD

**Issue by YXMagnuMXY** [ionic-team/ionic#16426]
I've just created a new project using ionic 4.4.0 and when I add a ion-navbar in the header, the page gets white.

I'm new in using Ionic, but I'm very interested in using it.
I am just reading the documentation and I want to add a navbar, but is not working for me...
I want to add two buttons, one at the start and other at the end of ion-navbar. I was trying to use ion-toolbar, but the icons are very cheap, even if I use the ion-button attribute in the button.

This code gives me white page:
```
<ion-header>
    <ion-navbar>
      <ion-buttons left>
        <button ion-button icon-only>
          <ion-icon name="contact"></ion-icon>
        </button>
      </ion-buttons>
      <ion-buttons end>
        <button ion-button icon-only>
          <ion-icon name="search"></ion-icon>
        </button>
      </ion-buttons>
    </ion-navbar>
  </ion-header>
```

Please help!

**Comment by JayzeeHuang** [comment]
Looks like you are using ionic 4 but reading ionic 3 document. 
[https://beta.ionicframework.com/docs](url)
