### ISSUE TITLE
ReferenceError: tslib_1__default is not defined

### ISSUE THREAD

**Issue by Cypaubr** [ionic-team/ionic#16428]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)  : 4.4.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 10 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/cyprien/Library/Android/sdk)
   ios-sim           : 6.1.3
   NodeJS            : v10.11.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61
```

**Describe the Bug**
When I deploy my app on my Android Device, right after the splashscreen this error is thrown and a blank screen appears.

**Steps to Reproduce**
1. Run `ionic cordova run android -l -c -s --debug`
2. Do nothing

**Related Code**
Confidential

**Expected Behavior**
I expected the app to start.

**Additional Context**
Stack trace obtained from Sentry.io :
```
ReferenceError: tslib_1__default is not defined
  at ? (/android_asset/www/index.html)
```

**Comment by manucorporat** [comment]
Can you provide a repo case?
