### ISSUE TITLE
[4.0.0-beta.16] does not work in IE 11 

### ISSUE THREAD

**Issue by royanon** [ionic-team/ionic#16430]
# Bug Report

**Ionic Info**
Ionic:

   ionic (Ionic CLI)             : 4.2.1 
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10

**Describe the Bug**
css does not appear to be correct even css-vars-ponyfill is used and all polyfills in polyfills.ts has been enabled. Content scrollToBottom() failed due to css problems.

**Steps to Reproduce**
1. ionic 4 start with sidemenu, tab
2. Add a button with function this.content.scrollToBottom();
3. ng serve in IE 11
4. All CSS does not appear correctly, and scrollToBottom failed.

**Related Code**
N/A

**Expected Behavior**
Expected to be working as in Pure Angular 7 with pollyfill enabled or any stenciljs demo in IE 11.

**Additional Context**
N/A

**Comment by manucorporat** [comment]
Next release should fix most of the issue with Android 4.4 and IE11! Thanks for the issue!
