### ISSUE TITLE
ion-checkbox: binding with ngModel doesn't set checkbox on initial loading

### ISSUE THREAD

**Issue by majorbenks** [ionic-team/ionic#16435]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (C:\Users\dst\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.10.3
   @angular-devkit/schematics    : 7.0.3
   @angular/cli                  : 7.0.3
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
When I bind a value / model to a ion-checkbox using [(ngModel)] the initial value is not set. So if the value is true when the control gets loaded, the checkbox is not checked. I have to add [checked]="value" in order to make that work. In my opinion, the checked value should be set automatically when ngModel value is set to true initially. 

**Related Code**
// when myModel.hasAdditionalAddress is true when the form loads, the checkbox is not checked. After toggling once, it works normally.
<ion-checkbox color="secondary" [(ngModel)]="myModel.hasAdditionalAddress"></ion-checkbox>

// it only works, when checked is set to myModel.hasAdditionalAddress
<ion-checkbox color="secondary" [(ngModel)]="myModel.hasAdditionalAddress" [checked]="myModel.hasAdditionalAddress"></ion-checkbox>

**Comment by kensodemann** [comment]
I have a sample app where the `[ngModel]` binding works fine for `ion-toggle` and `ion-checkbox` with beta.15 but does not work at all with beta.16.

https://github.com/kensodemann/test-toggle

Probably tied to this change: https://github.com/ionic-team/ionic/commit/bfbbeca

Here is my ion info:

```
Ionic:

   ionic (Ionic CLI)             : 4.4.0 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0

System:

   NodeJS : v10.13.0 (/home/kensodemann/.nvm/versions/node/v10.13.0/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.15
```

**Comment by mmlleevvyy** [comment]
@kensodemann I tested [(ngModel)] for checkbox after my commit https://github.com/ionic-team/ionic/commit/429e08344afb8a0e2b4c43c031d04fceced462e0 and it works as expected, so will be fixed in next release.

**Comment by manucorporat** [comment]
YEp, this should be fixed in beta.17!

**Comment by scotthardin** [comment]
I found the same problem exists in beta.17 for ion-toggle (for reactive forms)
