### ISSUE TITLE
Ionic capacitor {undefined is not a function}

### ISSUE THREAD

**Issue by salemdomain** [ionic-team/ionic#16434]
Please help my app is working just fine in the browser but when am launching the apk in real device its showing the following error { undefined is not a function } . Thanks
![screenshot_2018-11-23-11-41-43](https://user-images.githubusercontent.com/40359993/48934779-7705fc00-ef16-11e8-8411-d0849a710b10.png)

**Comment by ptitjes** [comment]
@salemdomain The ticket you opened on Capacitor (ionic-team/capacitor#995) is more appropriate than here. You should close this one.

**Comment by salemdomain** [comment]
@paulstelzer

I tried to uncomment the following lines in polyfill.ts and the problem is gone but i lost the style { shadow dom } is not working.

import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';
