### ISSUE TITLE
Ion search bar cursor point not moving with the content properly?

### ISSUE THREAD

**Issue by saty932** [ionic-team/ionic#16431]
we are right now testing our app in ios11. Whenever I scroll the content in ios searchbar with cursor also moving. Searchbar is somewhere and content is somewhere.anybody have fix for this??

//code

```
<ion-content class="outer-content" no-padding overflow-scrolling="false" has-bouncing="true">
<div class="main-content" style="background:#f0f0f0;">
  <ion-searchbar [disabled]="true" [(ngModel)]="searchQuery"   (ionInput)="onInput($event)"   autocorrect="off"> 
  </ion-searchbar> 

</div>
</ion-content>
```
ionic info--

Avantsys-MacBook-Pro:promonear avantsytechuser$ ionic info

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 2.0.0 
    Node       : v8.11.3
    npm        : 5.7.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4 Build version 9F1027a 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by manucorporat** [comment]
It's a known Safari bug with the caret, very little we can do about it, in ion-input we hide the caret during scrolling. Please feel free to reopen the issue if more information is provided!
https://bugs.webkit.org/show_bug.cgi?id=138201
