### ISSUE TITLE
[4.0.0-beta.16] [iOS] Swipe Back (go back): how to disable?

### ISSUE THREAD

**Issue by olivermuc** [ionic-team/ionic#16441]
I realize this feature was newly added to beta.16 - however it may not be wanted all the time.
How can I disable this behavior?

Both in the template (categorically) for eg the home page of an app (to avoid swiping back to the login page, which is what happens now!)

But also programmatically?

Thanks,
Oliver

EDIT:
_I did skim across the last commits and searched the source...couldn't find anything.._

**Comment by mmlleevvyy** [comment]
@olivermuc If you use ionic/angular then set [swipeGesture]="false" for ion-router-outlet.

**Comment by manucorporat** [comment]
@mmlleevvyy is right! you should use the swipeGesture input of ion-router-outlet!

**Comment by olivermuc** [comment]
Works like a charm, thx @mmlleevvyy
