### ISSUE TITLE
【Ionic 4】ionic fast back issues

### ISSUE THREAD

**Issue by AIxiuxiu** [ionic-team/ionic#16449]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.4.0 (/Users/xayq-fanxl/.nvm/versions/node/v8.11.2/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0
```

**Describe the Bug**
After navigate into a detail page,I quickly click the back button，this details page will not destroy

**Steps to Reproduce**
1. Use `ionic start ionic_app blank  --type=angular`  create a new project，Add a new page 'me' with `ionic g page`
2. Home page add code to jump to me page
```
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-button color="primary" href="/me" routerDirection="forward">
        <ion-icon slot="icon-only" name="contact"></ion-icon>
      </ion-button>
    </ion-buttons>
    <ion-title>
      Ionic Blank
    </ion-title>
  </ion-toolbar>
</ion-header>
```
me page add code to back
```
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button color="primary" text="&nbsp;&nbsp;&nbsp;&nbsp;"></ion-back-button>
    </ion-buttons>
    <ion-title>me</ion-title>
  </ion-toolbar>
</ion-header>
```
3. Click button navigate to me page and quickly click the back button
me page not destroy ,home page toobar showing the me page toobar
![](https://raw.githubusercontent.com/AIxiuxiu/readme_add_pic/master/ionic_back.png)

The right situation
![](https://raw.githubusercontent.com/AIxiuxiu/readme_add_pic/master/ionic_back_right.png)

**note**
I found that only use mode="ios" will happen, when I use  mode="md" to index.html `<html lang="en" mode="md">` no problem

**Comment by bossjon** [comment]
@AIxiuxiu, + on android, after 2 or 3 attempts (quickly click the back button), the application freezes and nothing works.

**Comment by AIxiuxiu** [comment]
I  testing Android and iOS with device today, there will be problems, which seriously affects  use . hopes to have a solution.

**Comment by paulstelzer** [comment]
I can confirm this issue, but couldn't reproduce it. Can you create a repo where this can be reproduced?

**Comment by AIxiuxiu** [comment]
@paulstelzer very busy recently, just saw,I created a simple [demo](https://github.com/AIxiuxiu/ionic_back_issues) based on my description.
You can view https://github.com/AIxiuxiu/ionic_back_issues

**Comment by paulstelzer** [comment]
Thanks. Could reproduce it

![2018-12-05_09-51-30](https://user-images.githubusercontent.com/20501666/49501578-799c1600-f873-11e8-949c-0f16105312e0.gif)

**Comment by AIxiuxiu** [comment]
My English is not very good, `ngOnDestroy` is my log, I just want to tell you when I fast click back button the subpage sometimes does not destroy

**Comment by paulstelzer** [comment]
I just updated your repo to latest rc.0 -> https://github.com/paulstelzer/ionic-back-issue

The problem is still here

**Comment by AIxiuxiu** [comment]
Ask for help, is there any solution?

**Comment by georgechr** [comment]
Expanding from @AIxiuxiu 's solution, overriding IonBackButtonDelegate's onclick event seems to work consistently, even when a defaultHref path is declared:
```
IonBackButtonDelegate.prototype.onClick = function (ev) {
            if (!that.canGoBack) {
                return false
            }
            if (this.routerOutlet && this.routerOutlet.canGoBack()) {
                this.routerOutlet.pop();
                ev.preventDefault();
            }
            else if (this.defaultHref != null) {
                this.navCtrl.navigateBack(this.defaultHref);
                ev.preventDefault();
            }
        };
```

But yes, this is a workaround at best, this needs to be fixed properly as it puts the app in a non-recoverable state and the user has to kill it and restart

**Comment by qingxo** [comment]
In the 4.0.0-rc2,the problem is still there,nobody care this? the problem is effect so huge...
