### ISSUE TITLE
[v4] Searchbar with `ion-title`

### ISSUE THREAD

**Issue by pjc0247** [ionic-team/ionic#16442]
`ion-searchbar` with `ion-title` breaks UI layout

(platform : ios )

![image](https://user-images.githubusercontent.com/1961216/48971203-ef290a80-f059-11e8-96b7-18f70932c5b0.png)

```html
<ion-toolbar>
      <ion-title>{{'chat-list.title' | translate}}</ion-title>
      <ion-searchbar></ion-searchbar>
</ion-toolbar>
```

**Comment by dylanvdmerwe** [comment]
Shouldn't the `ion-title` and `ion-searchbar` live in two separate toolbars?

**Comment by Silvest89** [comment]
@pjc0247 
`
<ion-toolbar>
      <ion-title>{{'chat-list.title' | translate}}</ion-title>
</ion-toolbar>
<ion-toolbar>
      <ion-searchbar></ion-searchbar>
</ion-toolbar>
`
