### ISSUE TITLE
Page Transition on Android looks like modal transition.

### ISSUE THREAD

**Issue by lassesteffen** [ionic-team/ionic#16447]
# Bug Report

**Describe the Bug**
The page transition on Android looks weird. Should be left to right and right to left for back and forth.

**Steps to Reproduce**
1. Go to https://beta.ionicframework.com/docs/api/nav/
2. Click on Material Design for the preview
3. Change pages and see it looks like a modal

**Expected Behavior**
IMO it should look more like the iOS Transition, the Android transition does not feel right at all. Should look like this https://material.io/design/navigation/navigation-transitions.html#peer-transitions.

**Comment by manucorporat** [comment]
They are hierarchical transitions:
https://material.io/design/navigation/navigation-transitions.html#hierarchical-transitions
