### ISSUE TITLE
Lazy loading in Tabs will not render the view correctly

### ISSUE THREAD

**Issue by zcd0000** [ionic-team/ionic#16451]
### Ionic Info
```
Ionic:

   ionic (Ionic CLI)             : 4.4.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.3, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/cundongzhang/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v8.12.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.1 Build version 10B61
```

I have updated to the latest in my package.json. 

Issue I am having is: 

- The main tab page can be lazy loaded. Attempting to lazy load modules in Tabs will not render the view correctly. Everything is rendering right above the tabs on bottom of the screen. Ion content doesn't show. Ion header will show.  
```
const routes: Routes = [
  {
    path: 'tabs',
    component: TabsPage,
    children: [
      {
        path: 'list',
        outlet: 'goods',
        loadChildren: '@pages/goods/goods.module#GoodsPageModule'
        // component: GoodsListPage
      },
      {
        path: 'list',
        outlet: 'order',
        loadChildren: '@pages/order/order.module#OrderPageModule'
        // component: OrderListPage
      },
      {
        path: 'index',
        outlet: 'mine',
        loadChildren: '@pages/mine/mine.module#MinePageModule'
        // component: MineIndexPage
      },
      {
        path: '',
        redirectTo: '/tabs/(mine:index)',
        pathMatch: 'full'
      }
    ]
  },
  {
    path: '',
    redirectTo: '/tabs/(goods:list)',
    pathMatch: 'full'
  }
];
```
![wx20181126-182553](https://user-images.githubusercontent.com/18573209/49008460-dc711b80-f1a8-11e8-8315-d8014bc05851.png)

_Originally posted by @Jscott388 in https://github.com/ionic-team/ionic/issues/15370#issuecomment-424529051_ #

**Comment by alhilali** [comment]
It seems to be an issue with core.scss
Try commenting out

`
@import "~@ionic/angular/css/core.css";
`

in theme/global.scss

**Comment by zcd0000** [comment]
> It seems to be an issue with core.scss
> Try commenting out
> 
> `@import "~@ionic/angular/css/core.css";`
> 
> in theme/global.scss

That's worked! Thanks!

**Comment by alhilali** [comment]
This is only a workaround and I believe it should be fixed

**Comment by ASHFAQPATWARI** [comment]
@alhilali Yes, this is an issue and it should stay open.

**Comment by mhartington** [comment]
This is less of an issue with the CSS and how Angular lazyLoads components . Please see this issue. 

https://github.com/ionic-team/ionic/issues/14566

Going to close as it is a duplicate, and we need a proper fix in Angular.
