### ISSUE TITLE
Why does Ionic 4 use CSS property “contain” when it is not supported on iOS 10?

### ISSUE THREAD

**Issue by Moelgaard85** [ionic-team/ionic#16475]
Ionic 4 uses css property "contain" on ion-content. As far as I understand, this is not supported on iOS 10 and marked as experimental on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/contain). In my build for iOS 10, it results in layout quirks such as not being able to scroll to the bottom in scrollable content. iOS 11+ builds works fine.

I am confused Ionic 4 uses this property, since the documentation says iOS 10 is supported [browser support](https://beta.ionicframework.com/docs/intro/browser-support#ios-10)

[StackOverflow question](https://stackoverflow.com/questions/53501934/why-does-ionic-4-use-css-property-contain-when-it-is-not-supported-on-ios-10)

**Comment by manucorporat** [comment]
CSS containment does not have any effect in Safari, either for good or bad. Unknown CSS properties are skipped completely.

**Comment by Moelgaard85** [comment]
> CSS containment does not have any effect in Safari, either for good or bad. Unknown CSS properties are skipped completely.

It seems to work in iOS 11 and iOS 12. But not in iOS 10. This confuses me if it shouldn't work in Safari at all.
