### ISSUE TITLE
[angular 4.0.0-beta.16] PWA performance audit shows no text compression enabled

### ISSUE THREAD

**Issue by trainingnote** [ionic-team/ionic#16489]
# Bug Report

Ionic:

```
   ionic (Ionic CLI)             : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.0.7
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.0

System:

   NodeJS : v10.12.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.15
```

**Describe the Bug**
When building with ` ionic build --prod` the audit performance score on lighthouse is bad (61/100 on a new project).
_However it seemed that with `ionic serve --prod` there is no such problem and the score is reasonable (93/100)._

**Steps to Reproduce**
1. Create a fresh new project : `ionic start myApp tabs --type=angular`
2. Add a service worker : `ng add @angular/pwa --project app`
3.Build the project with prod : ` ionic build --prod`
4. Run a lighthouse audit

**Related Code**
Here is the lighthouse report : [https://res.cloudinary.com/training-note/raw/upload/v1543404193/ionicPWAAudit_2018-11-28_12-19-30.html](https://res.cloudinary.com/training-note/raw/upload/v1543404193/ionicPWAAudit_2018-11-28_12-19-30.html
)

**Expected Behavior**
`ionic build --prod` should handle text compression

![screenshot from 2018-11-28 12-15-39](https://user-images.githubusercontent.com/30081782/49149187-c0d15680-f309-11e8-85bc-0e75a0a1464c.png)

**Comment by manucorporat** [comment]
This is not related to ionic itself, but the server you are using to serve the website, using firebase for hosting will provide a good performance.

Never use ionic serve as production server!

**Comment by trainingnote** [comment]
What is wrong by hosting on a private server ?
