### ISSUE TITLE
[4.0.0-beta.17] Adding day of the week in the ion-datepicker does not show in selector

### ISSUE THREAD

**Issue by RHinderiks** [ionic-team/ionic#16487]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.4.0 (/Users/rh/.nvm/versions/node/v8.11.4/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.5
   @angular-devkit/schematics    : 7.0.5
   @angular/cli                  : 7.0.5
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.2, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 13 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/rh/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.0.0
   NodeJS            : v8.11.4 (/Users/rh/.nvm/versions/node/v8.11.4/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B6
```

**Describe the Bug**
When setting the display-format to "DDDD D MMMM YYYY" it results in the input box showing Wednesday 28 November 2018. However when changing the date the date wheel still shows 238 november 2018

**Related Code**
`<ion-datetime display-format="DDDD D MMMM YYYY"></ion-datetime>`

**Expected Behavior**
I expected it to work like ios (and android) since thats why we use ionic to get a native feel. Which would be something like this:

![image](https://user-images.githubusercontent.com/26223525/49146458-7c8e8800-f302-11e8-94bd-9885b2c59843.png)

**Comment by bryce13950** [comment]
Can you try setting that as a picker-format to see if that changes what the picker shows?

**Comment by RHinderiks** [comment]
@bryce13950 For a moment i thought i had dun goofed, however setting the picker-format does not seem to do anything.

**Comment by bryce13950** [comment]
Well we will look into it to see what we can find.

**Comment by NiklasMerz** [comment]
We already looked into this shortly. [These lines](https://github.com/ionic-team/ionic/blob/1a27bce7fdc3a100a14576bc5f701435f9c6804d/core/src/components/datetime/datetime.tsx#L314-L323) explicitly do this.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us. I am going to close this for now, but we will be re-evaluating the `ion-datetime` functionality and bugs soon during which we will take a closer look at this issue.

Thanks for using Ionic!
