### ISSUE TITLE
[4.0.0-beta.16] <ion-popover> implementation: flexible positioning options requested

### ISSUE THREAD

**Issue by olivermuc** [ionic-team/ionic#16486]
# Feature Request
I realize that `<ion-popover>` isn't yet fully implemented, but while at it, would like to point out current shortcomings and request more positioning flexibility.

**Describe the Feature Request**
Currently the positioning attempts to position the popover either relative to the element clicked or centered on the page based on **available content height** (at the time!).

This is the problem, oftentimes there are delays in acquiring data that have an affect the popover overall height and this position.
 
**Describe Preferred Solution**
Ideally two things:
(1) A popover _create_ option `{autoHight: true}` that allows the popover to dynamically be centered on screen at all times.
(2) A popover-controller method to request `resize()/repositioning()` of the popover: 

**Describe Alternatives**
I can currently apply a CSS workaround:
```
  .popover-content {
            top: 50% !important;
            max-height: 80%;
            transform: translateY(-50%);
        }
```
Which works rather well, but will become non-functional once popover goes WC (shadow-root).

I guess the question is also, how much modal-like does a popover have to be?!
Well, modals wouldn't be a great fit in many of the cases, hence the needed content-resize / repositioning request imho make sense.

Thoughts?

**Comment by liamdebeasi** [comment]
Thanks for the issue! I am going to merge this feature request with https://github.com/ionic-team/ionic/issues/21599.
