### ISSUE TITLE
Transpile Errors in @ionic/react with Babel Transpiling

### ISSUE THREAD

**Issue by jthoms1** [ionic-team/ionic#16497]
Create React App uses Babel for Typescript transpilation. In order for this to work it requires that tsconfig has `isolatedModules` set to true. In doing so you are not allowed to have const enums in dependent modules.  More information can be found here https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/.

During compilation of an Ionic React application you will receive the following error.

```
/Users/joshthomas/Workspace/ionic-react-conference-app/node_modules/@ionic/core/dist/types/components/nav/view-controller.d.ts
Type error: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.  TS1209

    1 | import { ComponentProps, FrameworkDelegate } from '../../interface';
  > 2 | export declare const enum ViewState {
      |                           ^
    3 |     New = 1,
    4 |     Attached = 2,
    5 |     Destroyed = 3
```

**Comment by nkprince007** [comment]
I'm still facing the same issue with `@ionic/core 4.0.0-beta.17`. Is this planned to be released in the next update?

**Comment by jthoms1** [comment]
That release was before this fix was merged.  It should be good in the next release.  beta.18
