### ISSUE TITLE
Ionic 4 - Add css variable for ion range bar border-radius

### ISSUE THREAD

**Issue by lukejoliat** [ionic-team/ionic#16508]
# Feature Request: add a css variable to set border radius on ion-range bars.

**Describe the Feature Request**
The shadow DOM limits customization of Ionic Components. Thus, changes are typically made via exposed css variables that a component may use. Fort example, the ion range bar uses `--bar-background` to set the background color. It would also be useful to be able to customize border radius of the bar.

**Describe Preferred Solution**
Create and use a css variable called `--bar-border-radius` akin to `--knob-border-radius`.

**Comment by manucorporat** [comment]
Can you submit a PR?

**Comment by lukejoliat** [comment]
Yes will do!

**Comment by manucorporat** [comment]
Thanks @lukejoliat! let me know if you need any assistance, i am happy to help

**Comment by lukejoliat** [comment]
PR has been created, locally confirmed that it's working, and checks are passing. Do I need to request a review or is it all set? https://github.com/ionic-team/ionic/pull/16519

**Comment by brandyscarney** [comment]
@lukejoliat PR looks good! I approved it. @manucorporat could you review? Thanks!

**Comment by paulstelzer** [comment]
Merged by #16519
