### ISSUE TITLE
Update style.css when ng add @ionic/angular

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#16514]
- Currently `ng add @ionic/angular` is not updating the project's styles.css
- Research if we can just use: `~@ionic/angular/css/[file].css` instead of `node_modules/...`
  - webpack CSS loader can do it: https://github.com/webpack-contrib/css-loader#import
  - ionic vue without sass uses it and it works
  - consistency between starter and `ng add`

**Comment by mhartington** [comment]
Not particularly a fan of modding the projects styles.css.
- what if styles.css name has changed? 
- what if there is no styles.css listed in the angular.json?


Declaring the styles in the styles array of the angular.json seems to be the preferred way of handling this in ng-add.

>ionic vue without sass uses it and it works
