### ISSUE TITLE
Allow Ionic Icons to be use in AlertControl

### ISSUE THREAD

**Issue by newuser44** [ionic-team/ionic#16525]
This is really the same thing that was wanted here.
https://github.com/ionic-team/ionic/issues/7874

Code:
```
 let popupMessage = "<span>" + "Use the Search icon to do a search" + "</span>" + '<ion-icon name="ios-search"></ion-icon>';

        let welcomePopup = this.alertCtrl.create({
            title: "Popup Title"
            message: popupMessage,
            inputs: [
                {
                    type: 'checkbox',
                    label: "Don't show again",
                    value: 'Yes',
                    checked: false
                }],
            buttons: [{
                text: this.translateService.instant('OKBTN'),
                handler: data => {          
                  //don't show popup
                }
            }]
        });
        welcomePopup.present(); 
```

No Ionic Icon shows up.  
Inspecting the HTML the tag doesn't even show up. 

  

>  @ionic/cli-utils  : 1.19.1
>     ionic (Ionic CLI) : 3.19.1
> 
> global packages:
> 
>     cordova (Cordova CLI) : 7.0.1
> 
> local packages:
> 
>     @ionic/app-scripts : 3.2.0
>     Cordova Platforms  : android 6.3.0 browser 4.1.0
>     Ionic Framework    : ionic-angular 3.9.2
> 
> System:
> 
>     Android SDK Tools : 26.1.1
>     Node              : v6.12.3
>     npm               : 3.10.10
>     OS                : Linux 3.13

**Comment by brandyscarney** [comment]
Thanks for the issue! This is no longer an issue in the latest version `4.4.2` so I am going to close this. If you're still having problems please open a new issue. Here's a Codepen where I was able to see the icon: https://codepen.io/brandyscarney/pen/yWWYoJ

Thanks! 🙂
