### ISSUE TITLE
[4.0.0-beta.17] backdropDismiss doesn't works

### ISSUE THREAD

**Issue by stewwan** [ionic-team/ionic#16527]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
   ionic (Ionic CLI)             : 4.4.0 (/Users/stewan/.nvm/versions/node/v10.11.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.11.0
   @angular-devkit/schematics    : 7.1.0
   @angular/cli                  : 7.1.0
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3,cordova-plugin-ionic-webview 2.2.5, (and 11 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/stewan/Library/Android/sdk/)
   ios-deploy        : 1.9.4
   ios-sim           : 7.0.0
   NodeJS            : v10.11.0 (/Users/stewan/.nvm/versions/node/v10.11.0/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.1 Build version 10B61
```

**Describe the Bug**
looks like it doesn't even exists in typescript

![screen shot 2018-11-29 at 20 15 00](https://user-images.githubusercontent.com/719763/49255579-9f5c9180-f413-11e8-9a64-c5fb9d55f6f6.png)

**Comment by peterpeterparker** [comment]
On which element, just had a look in my app with bet.a17 and it still seems ok with `alertController` or `popoverController` 

<img width="453" alt="capture d ecran 2018-11-30 a 08 31 09" src="https://user-images.githubusercontent.com/16886711/49275015-4f64e580-f47a-11e8-9d57-dded201cf2e0.png">

**Comment by peterpeterparker** [comment]
@stewwan yep agree, there isn't this option for Loading. Don't know if it's correct and then the doc should be modified or if it should be implemented

https://github.com/ionic-team/ionic/blob/0680fe925145fbff927f1b0a73b3dd6f3ccee46e/core/src/components/loading/loading-interface.ts

https://github.com/ionic-team/ionic/tree/0680fe925145fbff927f1b0a73b3dd6f3ccee46e/core/src/components/loading

**Comment by stewwan** [comment]
Sad but true, it was working before. hope they can implement it sooner because I need this option for a killer feature

**Comment by stewwan** [comment]
I think I found the problem, but I have no time to PR today :( if no one does until Monday, I will.

`tappable={false}` should be `{this.backdropDismiss}`

https://github.com/ionic-team/ionic/blob/0680fe925145fbff927f1b0a73b3dd6f3ccee46e/core/src/components/loading/loading.tsx#L204

**Comment by paulstelzer** [comment]
Then please post a PR :)
