### ISSUE TITLE
[4.0.0-beta.17] ion-toolbar background not set in Edge

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#16536]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.0.7
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 20 other plugins)

System:

   NodeJS : v10.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
Setting `--background` color onto an `ion-toolbar` does not work on Edge browser. It's probably css var related.

![image](https://user-images.githubusercontent.com/2852839/49288657-088ee400-f4aa-11e8-925d-c8f325b1a104.png)

**Related Code**
```
ion-header ion-toolbar {
  --background: red;
}
```

**Comment by paulstelzer** [comment]
Which version of Edge you are using? For me it's working (Edge 44, EdgeHTML 18)

![applicationframehost_2018-11-30_13-18-02](https://user-images.githubusercontent.com/20501666/49288916-65869c00-f4a2-11e8-8131-2628e1a83e6e.jpg)

**Comment by dylanvdmerwe** [comment]
Edge 44.17763.1.0
EdgeHTML 18.17763

**Comment by paulstelzer** [comment]
Do you have a color-attribute in your html file?

```
<ion-header>
  <ion-toolbar>
    <ion-title>
      Ionic Blank
    </ion-title>
  </ion-toolbar>
</ion-header>
```

**Comment by dylanvdmerwe** [comment]
I have created a repo for this issue that is reproducible in RC0. 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (C:\Users\dylan\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v10.14.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

So the point of the issue is to put a style in global.scss to apply look and feel to the nav bar across the app. 

Yes if I go into each page and set the style manually it does in fact work in Edge. 
```
ion-header ion-toolbar {
  // uncomment this to apply the toolbar color properly
  //--background: var(--ion-color-primary);
}
```

But what I have done is added a line to `global.scss` such as:
`@import "./theme/navbar.scss";`

This file looks as follow:
```
$gradient-color-1: red;
$gradient-color-2: blue;

ion-header ion-toolbar {
  --background: var(--ion-color-primary);
  --background: -webkit-linear-gradient(to right, #{$gradient-color-1},#{$gradient-color-2});
  --background: -moz-linear-gradient(to right,#{$gradient-color-1},#{$gradient-color-2});
  --background: -o-linear-gradient(to right, #{$gradient-color-1}, #{$gradient-color-2});
  --background: linear-gradient(to right, #{$gradient-color-1}, #{$gradient-color-2});
  --ion-toolbar-color: white;
  --ion-color-base: white;
}
```

Again the goal is to set a global style across the app. This does in fact work on Chrome. However on Edge the navbar is not being styled using the included `navbar.scss` file described above. 

![image](https://user-images.githubusercontent.com/2852839/50687363-b7828a80-1029-11e9-9001-13913f8bf9af.png)


Repo here:
[navbar.zip](https://github.com/ionic-team/ionic/files/2726881/navbar.zip)

**Comment by brandyscarney** [comment]
I discussed this more with Dylan offline. I was able to reproduce this in the conference app using the following CSS in variables.scss:

```
$gradient-color-1: red;
$gradient-color-2: blue;

ion-header ion-toolbar {
  --background: linear-gradient(to right, #{$gradient-color-1}, #{$gradient-color-2});
  --color: white;
}
```

It works fine in Chrome, but running in Edge on Browserstack it is showing a white background. Adding `!important` to the `--background` variable works fine. My best guess is this is an issue with the order of the included styles. As a workaround I've asked Dylan to use the global CSS variables like the following:

```
$gradient-color-1: red;
$gradient-color-2: blue;

ion-header {
  --ion-toolbar-background: linear-gradient(to right, #{$gradient-color-1}, #{$gradient-color-2});
  --ion-toolbar-color: white;
}
```

This works fine in both browsers, but I still think we should look into why Edge is different. cc @manucorporat @adamdbradley

**Comment by carlosnewmusic** [comment]
this in the latest ionic version is still happening

on edge
![edge](https://user-images.githubusercontent.com/19379457/59673125-0596df00-91c1-11e9-85aa-b06da4a66420.jpg)

in chrome or firefox
![header y boton menu navegador pc](https://user-images.githubusercontent.com/19379457/59673197-23fcda80-91c1-11e9-95c9-f0999f98b851.jpg)

**ionic info**
`Ionic:

   Ionic CLI                     : 5.0.2 (C:\Users\Administrador\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 5 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.5

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
`

**Comment by almothafar** [comment]
The issue still here with ionic 4.6.1 as well:

Ionic:

   Ionic CLI                     : 5.2.1 (C:\Users\almothafar\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.1
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : not installed
   @capacitor/core : not installed

Cordova:

   Cordova CLI       : 9.0.0
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 14 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (D:\Android\sdk)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.10.0
   OS                : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as we recently released Ionic Framework v5 which dropped support for IE11 and older versions of Edge. Moving forward, Ionic Framework v4 will only receive critical security patches.
