### ISSUE TITLE
updating phonegap to ionic 3 app making localStorage clear

### ISSUE THREAD

**Issue by akshgods** [ionic-team/ionic#16548]
# Bug Report
Updating phonegap app to ionic 3 app. New app making localStorage clear.

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)  : 4.1.1 (C:\Users\Ganesh\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 12 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\\Users\\Ganesh\\AppData\\Local\\Android\\sdk)
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10
```

**Describe the Bug**
Updating phonegap app to ionic 3 app making localStorage clear. so i'm not able to get previous values stored by phonegap app with localStorage. (note: i'm not clearing localStorage anywhere in my app)

**Steps to Reproduce**
1.  Make any phonegap app 
2.  Use localStorage to save something, like ('login','true') and install app on mobile device
3.  Make ionic 3 app with same id, use same localStaorage to retrive data .
4. log or alert data you will get null instead of some vlaue

**Expected Behavior**
When we update the app , app must persist the localStorage. ionic should not clear the app storage.
We must able to use previously store data.

**Comment by paulstelzer** [comment]
Ionic 3 has it's own repository -> https://github.com/ionic-team/ionic-v3

This issues are only related to Ionic 4
