### ISSUE TITLE
[4.0.0-beta.17] Expand full button with wrap option

### ISSUE THREAD

**Issue by paulstelzer** [ionic-team/ionic#16552]
**Describe the Bug**
Sometimes it's necessary to wrap the text of a button because you want to have a long text on this button. If the button is expand="full" or expand="block", this will not working

**Steps to Reproduce**
Add the following css:
```
ion-button.wrap {
    white-space: normal;
    --height: auto;
}
```

And the button is this:

v1:

```
<ion-button expand="full" class="wrap">
Imagine a very long text here that is very long and will need more than one line
</ion-button>
```

v2:

```
<ion-button expand="block" class="wrap">
Imagine a very long text here
</ion-button>
```

This will lead to (on Chrome):

![expand-full-button](https://user-images.githubusercontent.com/20501666/49338426-2fbbf180-f621-11e8-8552-4effb07b4568.jpg)

**Related Code**
Problem is the following: `contain: strict;` on full and block

**Expected Behavior**
The text should be shown correctly

![chrome_2018-12-02_11-01-20](https://user-images.githubusercontent.com/20501666/49338487-eb7d2100-f621-11e8-8b3c-c1bb9954c911.jpg)

**Comment by manucorporat** [comment]
Fixed by https://github.com/ionic-team/ionic/commit/802a3d14e75a26ef7c6c4677ff4705401009df73!
