### ISSUE TITLE
App Freezing due to keyboard not closing on page change on device.

### ISSUE THREAD

**Issue by themightysapien** [ionic-team/ionic#16556]
# App Freezing due to keyboard not closing on page change on device.

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/home/optima/.nvm/versions/node/v10.3.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.3
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/optima/Android/Sdk)
   NodeJS            : v10.3.0 (/home/optima/.nvm/versions/node/v10.3.0/bin/node)
   npm               : 6.1.0
   OS                : Linux 4.15

```

**Describe the Bug**
My app freezes whenever i submit a form which navigates to another page without closing the keyboard that pops up after tapping the input field. I have tested it numerous times, my app freezes only when i don't close the keyboard before submitting the form.
Has never happened to me before, i don't know if this is the real reason. Or is it because of the beta ??

**Steps to Reproduce**
1. Go to any form page  '...'
2. put random input fields '....'
3. before you submit your form don't close the keyboard '....'
4. navigate to another page after that

**Comment by paulstelzer** [comment]
Could you please create a repo for that? My app not freezes when I submit a form and the keyboard is open
