### ISSUE TITLE
Ionic Keyboard - keyboard.hide() not working on iOS device.

### ISSUE THREAD

**Issue by samachola** [ionic-team/ionic#16568]
# Bug Report

**Ionic Info**

```
Ionic:

	ionic (Ionic CLI)          : 4.1.2
	Ionic Framework            : @ionic/angular 4.0.0-beta.15
	@angular-devkit/core       : 0.7.5
	@angular-devkit/schematics : 0.7.5
	@angular/cli               : 6.1.0
	@ionic/ng-toolkit          : 1.0.7
	@ionic/schematics-angular  : 1.0.5

Cordova:

  cordova (Cordova CLI) : 8.0.0
  Cordova Platforms     : ios 4.5.5
  Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.3, (and 10 other plugins)

System:

  ios-deploy : 1.9.2
  NodeJS     : v8.9.3 (/usr/local/bin/node)
  npm        : 6.4.1
  OS         : macOS
  Xcode      : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
On a text input field, the keyboard does not hide when user hits `enter` key on device.

**Related Code**

```
	- Template .html

	<ion-input 
		formControlName="name" 
		autocapitalize="off" 
		autocomplete="off" 
		type="text" 
		(keyup.enter)="hideKeyboard()">
       </ion-input>

	- Component .ts

	hideKeyboard() {
           this.keyboard.hide();
        }

```

**Expected Behavior**
The keyboard should close/hide when user hits `enter` key.

**Comment by paulstelzer** [comment]
Mh, I think this is hard to implement because keyboard is a native cordova plugin, so it cannot be integrated (from my point of view) into Ionic directly. So i think you have to make it manually (write a service for example).

**Comment by olivermuc** [comment]
It can, I'm using the above, too.

@samachola did you include the keyboard this way:
`import { Keyboard } from '@ionic-native/keyboard/ngx';`

Another thought, perhaps you want to apply a slight `setTimeout()` delay to your `this.keyboard.hide(); ` call - could be a timing issue?

**Comment by paulstelzer** [comment]
Ionic native plugins cannot be added to the core / angular package of ionic, so I close it here because such a feature you have to include by yourself like @olivermuc described
