### ISSUE TITLE
Theme (template) to ionic and web application with angular 6

### ISSUE THREAD

**Issue by ester-gonzalez-c** [ionic-team/ionic#16563]
Hi,

I'm doing a web application with fuse theme, but it does not have ionic's support. I want to know if there is any template or theme valid for angular 6 web application like that, and ionic 3 or 4.

Thank you so much!

**Comment by mhartington** [comment]
Hi there! I'm going to be closing this issue as this is more of a question than an actual issue.

For templates, I would suggest looking at something like Ionic Themes.

https://ionicthemes.com
