### ISSUE TITLE
Problem with your release notes on version 4.0.0-beta.16

### ISSUE THREAD

**Issue by plchampigny** [ionic-team/ionic#16567]
# Bug Report

The release notes of 4.0.0-beta.16 are missing a key breaking change in the release notes page:
https://github.com/ionic-team/ionic/releases/tag/v4.0.0-beta.16

Missing section:

```
Simplifying Chip
Because of updates to the Material Design spec, ion-chip no longer requires a chip-specific version of ion-icon or ion-button. Chips themselves should be interactive and don't require a nested button.

Old usage:

<ion-chip>
  <ion-chip-icon name="checkmark"><ion-chip-icon>
</ion-chip>
New usage:

<ion-chip>
  <ion-icon name="checkmark"></ion-icon>
</ion-chip>
```

**Describe the Bug**
Missing section about ion-chip changes. Now changes are in the master changelog: https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md

**Expected Behavior**
Have proper documentation in the release notes

**Comment by brandyscarney** [comment]
Thank you! Updated the release notes.
