### ISSUE TITLE
App Id depending platform

### ISSUE THREAD

**Issue by Genarito** [ionic-team/ionic#16588]
# Feature Request

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)  : 4.4.0 (/opt/node-v8.10.0-linux-x64/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 18 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/genaro/Android/Sdk)
   NodeJS            : v8.10.0 (/opt/node-v8.10.0-linux-x64/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.18
```

**Describe the Feature Request**
I've developed an app for Android which is already in the Play Store since a year ago. This week I was asked for upload the app to App Store, to my surprise the id already exists! So I had to make a new branch just to change the id for iOS. It would be so cool if We could define the app id (as the version and related info) in the config.xml file specifing the platform.

**Describe Preferred Solution**
As we can define hooks, icons, resource-file by platform, It would be nice to define the id too.

Thanks in advance and sorry about my English

**Comment by paulstelzer** [comment]
Thanks for your issue and the time reporting it. Unfortunately your issue is not related to Ionic. Instead this is something that concerns Apache Cordova.

After a short search I found this -> https://stackoverflow.com/questions/19069674/cordova-is-it-possible-to-have-different-app-ids-for-android-and-ios-platforms

I hope this will help you :)

**Comment by Genarito** [comment]
Thank you so much!
