### ISSUE TITLE
[beta 17] ion-*-controller don't have async componentOnReady() method

### ISSUE THREAD

**Issue by bitflower** [ionic-team/ionic#16591]
# Bug Report

**Describe the Bug**
In a clean Stencil project with just `@ionic/core` using any of the controller methods is not possible.

Example: `<ion-loading-controller>` when used as described in the docs/github https://github.com/ionic-team/ionic/tree/master/core/src/components/loading-controller#javascript does not wait at the `componentOnReady` call with `await`. Instead the code runs over it and tries to immedaitely call the `create()` function below.

Error:
```
Uncaught (in promise) TypeError: loadingController.create is not a function
    at AppHome.presentLoading (app-home.entry.js:12)
``` 

**Steps to Reproduce**
Clone repo at: https://github.com/bitflower/ionic-controller-bug

**Related Code**
```
    componentDidLoad() {
        this.presentLoading();
    }
    async presentLoading() {
        const loadingController = document.querySelector('ion-loading-controller');
        await loadingController.componentOnReady();
        const loadingElement = await loadingController.create({
            message: 'Please wait...',
            spinner: 'crescent',
            duration: 2000
        });
        return await loadingElement.present();
    }
```
**Expected Behavior**
Code stops at await and only continues after `componentOnReady` is finished.

**Comment by bryce13950** [comment]
Did you setup the build scripts yourself? This seems like it could be an issue with the source not transpiling to something like es6

**Comment by bitflower** [comment]
Hi, no the repos was setup using npm init stencil. In step 2 I installed ionic and added it to global.ts. Then the code in the component.
