### ISSUE TITLE
[ionic 4-beta.17] <ion-tab-button> && <ion-badge> buggy CSS for Android

### ISSUE THREAD

**Issue by olivermuc** [ionic-team/ionic#16598]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/Users/os/.npm-packages/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 18 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/os/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.13.0 (/usr/local/Cellar/node@10/10.13.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61```
```

**Describe the Bug**
Empty badge rendering in a `<ion-tab-button>` is wrong for Android.
It does work as iOS.
It also works outside `<ion-tabs>` for Android, just not when part of a <ion-tab-button>.

**Steps to Reproduce**
1. Add empty `<ion-badge></ion-badge>`element to `<ion-tab-button>`
2. Review rendered tab page / tab bar

**Related Code**
![image](https://user-images.githubusercontent.com/10549895/49518938-1d032000-f8a0-11e8-8962-73d7aa9bdd89.png)
Here is the `<styles>` part of `<ion-tab-button>` responsible for the above.
```
::slotted(ion-badge:empty) {
    display: block;
    min-width: 8px;
    height: 8px
}
```
Recommendation: just remove the entire block above, I can't think of any reason that justifies this code block.

**Expected Behavior**
An empty badge should not display anywhere in the app. 
It does it right in all the other places, except here.

**Additional Context**
**I hope** this is not a "feature", as I can't think of any reason why I would show an empty badge a small "bubble". If that was the case, one would have to add `*ngIf` for each `<ion-badge` which is bad  imho.

**Comment by bryce13950** [comment]
What version of android is this?

**Comment by brandyscarney** [comment]
This is not a bug. This is on purpose to match the Material Design spec: https://material.io/design/components/bottom-navigation.html#badges

<img width="807" alt="screen shot 2018-12-05 at 10 39 38 am" src="https://user-images.githubusercontent.com/6577830/49524619-19f53900-f87a-11e8-9b25-e62b04dc38e0.png">

We try to match the spec as much as possible. If you want different behavior please modify the badge using CSS. Thanks!
