### ISSUE TITLE
创建项目的时候出现这种问题，是什么原因？

### ISSUE THREAD

**Issue by harrylyh** [ionic-team/ionic#16595]
![image](https://user-images.githubusercontent.com/26681969/49492767-a6acf080-f894-11e8-8b3f-9391c4d2e1e2.png)
然后一值卡在这了，nodejs环境我都重新安装了也还不行，网上也找不到原因，求解？该怎么解决

**Comment by HankXu** [comment]
如果你用的node版本是10.x.x的，那换成8.x.x的试一下，似乎是10.x.x之后Node移除了低版本TLS协议的支持，出现这个问题可能是你正在安装的某些包的来源服务器只支持低版本的TLS协议，所以产生了这个错误。

还有一些小建议，老哥你这个问题跟ionic框架关系不大，就没必要在这边提issue了，这种可以在论坛里提问题。issue主要是用来提框架的bug和请求开发新特性的。另外外国框架维护者也大都是外国人，用中文提issue比较难得到帮助的，所以还是用英文提吧。
