### ISSUE TITLE
Ionic Vue TODOs

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic#16599]
List of things to take care of in the Vue binding

### Code

- [x] Finalize router integration
- [x] Review modals and props being passed down
- [x] Review deps and devDeps
- [x] Finalize CSS imports 
- [ ] Unit tests

### Docs

- [x] Create section about using Vue
- [x] Add Vue usage examples to core components
- [x] Create Demos section that can highlight Vanilla, Angular, and Vue sample projects (Conference App, Star Track, BEEP)

### CLI

- [x] Create Vue Project Type
- [ ] Create standard starter project (blank, sidemenu, tabs)
- [x] Create Vue add-on plugin for Ionic

cc @jthoms1 @michaeltintiuc

**Comment by paulohenriqu** [comment]
Great. I'm really excited about that.
Do you guys plan full integration with the ionic cli? Like ionic serve and integration with DevApp?
