### ISSUE TITLE
v4: add a few css variables to ion-card components

### ISSUE THREAD

**Issue by zakton5** [ionic-team/ionic#16592]
# Feature Request

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.0.7
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, (and 5 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 7.0.0
   NodeJS     : v10.11.0 (/usr/local/Cellar/node/10.11.0/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61
```

**Describe the Feature Request**
- Add margin variables (--margin-start, --margin-top, etc.) to ion-card
- Add padding variables (--padding-start, --padding-top, etc.) to ion-card-header and ion-card-content
- Add font-size variable (--font-size) to ion-card-title and ion-card-subtitle

**Comment by paulstelzer** [comment]
Thanks for your issue! Not always css variables are necessary. I think @brandyscarney explains this very well here -> https://github.com/ionic-team/ionic/issues/16341#issuecomment-443814627

So in your case just add 

```
ion-card-title {
    font-size: 40px;
}
```

or

```
ion-card {
    margin: 80px 20px;
}
```

And then it looks like you want :)

Before:
![chrome_2018-12-05_09-06-01](https://user-images.githubusercontent.com/20501666/49498958-0394b080-f86d-11e8-9c34-4d3ab48c5202.jpg)

After:
![chrome_2018-12-05_09-06-01](https://user-images.githubusercontent.com/20501666/49498969-0abbbe80-f86d-11e8-978c-621679f274bd.jpg)

If you're seeing problems where this isn't working, please let me know. Thanks!

**Comment by brandyscarney** [comment]
@paulstelzer is correct! We try to avoid adding CSS variables when the styles can be achieved using pure CSS. I'm going to close this but let us know if you are seeing issues with this and we can investigate. Thank you. 🙂
