### ISSUE TITLE
[v4, core] alert message displays a "square" at the end of the message

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#16608]
# Bug Report

**Ionic Info**

Ionic Core v4.0.0-beta.16

**Describe the Bug**
I use an `Alert` from Ionic Core in a vanilla project and when the alert is displayed, it displays a "square" at the end of the message (see screenshot)

**Steps to Reproduce**

1. https://deckdeckgo.com
2. click the "question mark" button in the bottom right fab list of actions

or

1. git clone http://github.com/fluster/deckdeckgo-website
2. cd deckdeckgo-website
3. npm install
4. npm start
5. open localhost:3000
6. click the "question mark" button in the bottom right fab list of actions

**Related Code**

```
presentAlert = async () => {
    const alertController = document.querySelector('ion-alert-controller');

    if (!alertController) {
        return;
    }

    await alertController.componentOnReady();

    const alert = await alertController.create({
        header: 'Hey!',
        subHeader: 'Nice to meet you',
        message: 'To navigate, just swipe the slides, use the left and right arrows keys of your keyboard or use the actions available at the bottom right.️',
        buttons: ['OK']
    });

    return await alert.present();
};
```

**Expected Behavior**
No square displayed

**Screenshot**
<img width="1116" alt="capture d ecran 2018-12-06 a 08 54 24" src="https://user-images.githubusercontent.com/16886711/49569579-9f3d2400-f934-11e8-9ff5-b246d3f7b6ff.png">

**Comment by bryce13950** [comment]
I just checked the demo, and I did not see this square. What version of Chrome is this?

**Comment by peterpeterparker** [comment]
@bryce13950 well spotted, I just noticed too that I don't face it with Safari neither.

just tested with Chrome 70, faced the problem. then actualized it to v71.0.3578.80 and still face it...weird

**Comment by brandyscarney** [comment]
There is a square in the code block you pasted above:

<img width="686" alt="screen shot 2018-12-06 at 12 45 53 pm" src="https://user-images.githubusercontent.com/6577830/49601837-e9360200-f954-11e8-904d-3ac46959bf2f.png">

but when I copy/paste it it shows as a period. Maybe some weird copy/paste bug? Can you try backspacing the period in your code and retyping it?

**Comment by peterpeterparker** [comment]
@brandyscarney and @bryce13950 thx you for your time, you are right there was something weird in the encoding of the file, don't know exactly why but I've deleted the all row and begin again and now it's good

sorry for the lost of your time, for my defense, even vim and the raw file from GitHub didn't displayed the character, but still I should have seen it, so please accept my apologies for the wrong issue

<img width="1233" alt="capture d ecran 2018-12-06 a 21 31 17" src="https://user-images.githubusercontent.com/16886711/49610507-0f808f80-f99f-11e8-8a1b-3640ca1b778b.png">

**Comment by brandyscarney** [comment]
@peterpeterparker It's okay! I didn't see the square when I opened your demo but I noticed it in the HTML so I knew it was something weird going on. It happens. 🙂

**Comment by peterpeterparker** [comment]
thx for your understanding
