### ISSUE TITLE
[4.0.0-beta.17 / Stencil 0.16.0] ion-spinner does not show with Stencil 0.16.0

### ISSUE THREAD

**Issue by pwespi** [ionic-team/ionic#16603]
# Bug Report

**Ionic Info**
This is a Ionic PWA toolkit project.
```
    "@ionic/core": "4.0.0-beta.17",
    "@stencil/core": "0.16.0",
```

**Describe the Bug**
`<ion-spinner></ion-spinner>` does not show.

**Steps to Reproduce**
1. Clone the Ionic PWA toolkit
2. Change dependencies to:
```
"dependencies": {
    "@ionic/core": "4.0.0-beta.17"
  },
  "devDependencies": {
    "@stencil/core": "0.16.0"
  }
```
3. Add `<ion-spinner></ion-spinner>`

**Expected Behavior**
`ion-spinner` should show.

**Additional Context**
Everything works as expected with Stencil 0.15.2.

**Comment by peterpeterparker** [comment]
If that could help too, the related screenshot I posted on the Slack channel:

<img width="1116" alt="capture d ecran 2018-12-05 a 21 04 48" src="https://user-images.githubusercontent.com/16886711/49542650-75edab00-f8d6-11e8-844d-3d0fe0315cee.png">

**Comment by manucorporat** [comment]
It's a bug in stencil, fixed in next release: https://github.com/ionic-team/stencil/commit/53089313dfd23d6761db9cdab808ae9a8cab1fca
