### ISSUE TITLE
`this.platform.exitApp();` doesn't work for ionic v4.1.2

### ISSUE THREAD

**Issue by manigujjula** [ionic-team/ionic#16609]
_Originally posted by @Riyaz0001 in https://github.com/ionic-team/ionic/issues/14803#issuecomment-421638592_
This is Working only in login Page .Other Pages just going back to previous page

**Comment by paulstelzer** [comment]
Feature request is: Add exitApp() to Platform again to close a cordova app

**Comment by manucorporat** [comment]
Sorry but I am closing the issue since it does not follow the issue template and does not explain what are the expectations.

Closing an app programmatically is not possible, the only way is to crash the app, and Apple could reject your app if you do that on purpose.
