### ISSUE TITLE
Run project ionic failed command ionic cordova run android

### ISSUE THREAD

**Issue by giresse21** [ionic-team/ionic#16613]
i get this error when running command ionic cordova run android

ANDROID_HOME=C:\androidsdk JAVA_HOME=C:\Program Files\Java\jdk1.8.0 Subproject Path: CordovaLib Starting a Gradle Daemon, 2 incompatible and 2 stopped Daemons could not be reused, use --status for details

FAILURE: BUILD FAILED

Total time: 57.141 secs Build failed with an exception.

Where: Build file ‘C:\Users\User\Desktop\doc\blank\platforms\android\build.gradle’ line: 20
What went wrong: A problem occurred evaluating root project ‘android’.
java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

i used android studio 3.2.1 and build tool 25.0.3
i need help please

**Comment by paulstelzer** [comment]
Thanks for your issue and your time to reporting it. Your issue is more related to Cordova and is more a support question because Ionic has to influence to it. You could open a support request in the forum or use any other source for your Cordova issue.

If you need further help, just let me :)
