### ISSUE TITLE
ion-segment mode attribute stopped working after updating to beta.16-17 

### ISSUE THREAD

**Issue by uncvrd** [ionic-team/ionic#16621]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.12.0-beta.0
   @angular-devkit/schematics    : 0.8.8
   @angular/cli                  : 7.2.0-beta.0
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 7 other plugins)

System:

   ios-deploy : 1.9.2
   NodeJS     : v10.13.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61
```

**Describe the Bug**
Hi all, I am using `ion-segments` within my project, I wanted to force the style to Material Design so I added `mode="md"` to my segment and it worked great up until I upgraded to betas 16 and 17. The styling is no longer forced to Material Design when I'm on iOS (it displays the native iOS style).

Here is a demo of related code where I added the `mode` and a screenshot of what it looks like now:

```
  <ion-segment (ionChange)="segmentChanged($event)" mode="md">
    <ion-segment-button value="upcoming" checked>
      <ion-label>Upcoming</ion-label>
    </ion-segment-button>
    <ion-segment-button value="released">
      <ion-label>Released</ion-label>
    </ion-segment-button>
  </ion-segment>
```

![img_73a070516e81-1](https://user-images.githubusercontent.com/25097099/49621233-34faa280-f979-11e8-8e77-c922236402e1.jpeg)

It also appears that the universal attributes used to modify segments styles also no longer work, for example: 

```
ion-segment {
    --border-color: rgba(255,255,255,0.1);
    --border-color-checked: rgba(107,157,250, 1);
    --color-checked: #fff;
    --color: #fff;
} 
```

**Expected Behavior**
Expected to see the `ion-segment` design in Material Design on iOS.

**Comment by paulstelzer** [comment]
Thanks for your issue and your time to reporting it!

It seems that you made a mistake on declaring the right mode and the css variables.

First: You have to add the mode to the segment-buttons, too:

```
    <ion-segment (ionChange)="segmentChanged($event)" mode="md">
        <ion-segment-button value="upcoming" checked  mode="md">
          <ion-label>Upcoming</ion-label>
        </ion-segment-button>
        <ion-segment-button value="released"  mode="md">
          <ion-label>Released</ion-label>
        </ion-segment-button>
      </ion-segment>
```

Second: The css variables has to be set to the `ion-segment-button`, so it's

```
ion-segment-button {
    --border-color: rgba(255,255,255,0.1);
    --border-color-checked: rgba(107,157,250, 1);
    --color-checked: #fff;
    --color: #fff;
} 
```

And if you do so, it's working :)

![chrome_2018-12-07_09-10-17](https://user-images.githubusercontent.com/20501666/49635411-f2c87400-f9ff-11e8-8977-fdd4e093b0f1.jpg)

If you have any further questions, let me know :)

**Comment by uncvrd** [comment]
@paulstelzer ah of course, thank you very much for your time and for catching my mistake!
