### ISSUE TITLE
Property 'overlayIndex' doesn't exist on ModalController and AlertController options

### ISSUE THREAD

**Issue by Titoune** [ionic-team/ionic#16628]
**Property 'overlayIndex' doesn't exist on ModalController and AlertController options**

The overlayIndex property exist on the documentation but is missing in the code.

Version: Ionic 4 beta17

 const modal = await this.modalCtrl.create({
          _overlayIndex: 10,_
           component: xxxxxxxxComponent,
            componentProps: {model: model, foreign_id: foreign_id},
            backdropDismiss: false
           .....
        });

**Comment by paulstelzer** [comment]
Thanks for your issue! overlayIndex is only internal, could you please open a feature request, for what you are need it?

**Comment by paulstelzer** [comment]
UPDATE: You said in documentation. If this is only a docs issue, I can add it to the https://github.com/ionic-team/ionic-docs/

**Comment by manucorporat** [comment]
You are right @paulstelzer, this is an internal API, it will be removed from the website in next release!
