### ISSUE TITLE
IonConfig swipeBackEnabled not working on 4.0.0-beta17

### ISSUE THREAD

**Issue by homeportcz** [ionic-team/ionic#16624]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.4.0
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.8.4
   @angular-devkit/schematics    : 0.8.4
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 7.1.2, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 15 other plugins)

System:

   Android SDK Tools : 26.0.1 (/Users/jirik/Library/Android/sdk)
   ios-deploy        : 2.0.0
   ios-sim           : 7.0.0
   NodeJS            : v8.12.0 (/usr/local/bin/node)
   npm               : 2.15.12
   OS                : macOS High Sierra
   Xcode             : Xcode 10.0 Build version 10A255

```
**Describe the Bug**
IonConfig swipeBackEnabled:false does not work. Still can swipe to go back.
Same behaviour for Android and iOS.
```
@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  exports: [],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    IonicModule.forRoot({
      mode: 'ios',
      swipeBackEnabled: false,
      backButtonText: ''
    })
]})
```

**Expected Behavior**
swipeBackEnabled configuration should be respected

**Comment by KevinKelchen** [comment]
I was able to disable swipe-to-go-back by adding `[swipeGesture]="false"` to `ion-router-outlet` like so:
`<ion-router-outlet main [swipeGesture]="false"></ion-router-outlet>`

I have not tried configuring it in `IonicConfig` like the OP.

**Comment by vosecek** [comment]
> I was able to disable swipe-to-go-back by adding `[swipeGesture]="false"` to `ion-router-outlet` like so:
> `<ion-router-outlet main [swipeGesture]="false"></ion-router-outlet>`
> 
> I have not tried configuring it in `IonicConfig` like the OP.

Thanks, this works too. Anyway, thanks @manucorporat for fixing it globally.
