### ISSUE TITLE
Application breaking on IE.11

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic#16627]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Beta.16
```

**Describe the Bug**
An application does not load at all as chunk file fails to load.

![whatsapp image 2018-12-07 at 2 17 13 pm 1](https://user-images.githubusercontent.com/8480351/49637364-2d93d180-fa2b-11e8-977f-4c2041cde26f.jpeg)
![whatsapp image 2018-12-07 at 2 17 13 pm](https://user-images.githubusercontent.com/8480351/49637366-2e2c6800-fa2b-11e8-8a36-25673db27a2c.jpeg)

It works on all other browsers. Not sure what should i do.

**Comment by stripathix** [comment]
Using :
"@ionic/core": "4.0.0-beta.17",
"@ionic/vue": "0.0.1",

**Comment by stripathix** [comment]
Looks like this information is not enough to debug. But if you can tell what's going on.

**Comment by patrickmcd** [comment]
IE isn't supported.

https://beta.ionicframework.com/docs/intro/browser-support/
