### ISSUE TITLE
MD mode: letter-spacing in toolbar buttons breaks cursive text

### ISSUE THREAD

**Issue by abennouna** [ionic-team/ionic#16633]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (~/.nvm/versions/node/v10.12.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.0.7
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.0

System:

   NodeJS : v10.12.0 (~/.nvm/versions/node/v10.12.0/bin/node)
   npm    : 6.4.1
   OS     : macOS High Sierra
```

**Describe the Bug**
The `letter-spacing` applied in Material Design mode breaks cursive text in *toolbar buttons*, and is always visible in Arabic script for instance.

I'm not sure whether the spacing is visible elsewhere.

**Steps to Reproduce**
1. Insert Arabic text in a toolbar button, for instance "مشتقة", which is a word where all letters are glued together,
2. See letters slightly separated by blanks, instead of being glued together

**Expected Behavior**
Although in MD specs, `letter-spacing` should not apply to cursive text. But is is the distinction possible in CSS?

**Additional Context**
If the behavior is as intended, we may need to tell the developers that they should care about reversing it for cursive text.

**Comment by manucorporat** [comment]
I don't think this is possible with CSS, and to me, looks like a browser bug. Fortunately, you can customize the letter-spacing of ion-title:

```
ion-title {
  letter-spacing: 0;
}
```
that should fix the issue for you!
