### ISSUE TITLE
[4.0.0-beta.17] ion-input number to hidden issue

### ISSUE THREAD

**Issue by Jbz797** [ionic-team/ionic#16635]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.11.2
   @angular-devkit/schematics    : 7.1.2
   @angular/cli                  : 7.1.2
   @ionic/angular-toolkit        : 1.2.0

System:

   NodeJS : v10.13.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS High Sierra
```

**Describe the Bug**
When I use an "ion-input" in an "*ion-item" the type changes from "number" (but its the same for "text" type) to "hidden".

![capture d ecran 2018-12-07 a 16 31 05](https://user-images.githubusercontent.com/10371362/49656429-9f751680-fa3d-11e8-990e-f9b12b4e62a7.png)

**Related Code**
```
<ion-reorder-group (ionItemReorder)="moveIngredients($event)" disabled="false">

  <ion-item *ngFor="let ingredient of ingredients; let i = index;">
    <ion-reorder slot="start"></ion-reorder>
    <ion-label>
      <div>{{ i }}</div>
      <div>{{ ingredient.title }}</div>
      <div>{{ ingredient.density }}</div>
      <div>
        <ion-input type="number" [(ngModel)]="ingredient.quantityMB" name="quantityMB{{ i }}" padding required></ion-input>
      </div>
      <div>
        <ion-button fill="fill" (click)="deleteIngretient(i)">
          <ion-icon color="danger" slot="icon-only" name="close"></ion-icon>
        </ion-button>
      </div>
    </ion-label>
  </ion-item>

</ion-reorder-group>
```

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please explain what's your issue?

As you can see, the input inside the shadow root has the input type number and so only numbers are allowed:

![chrome_2018-12-08_11-32-45](https://user-images.githubusercontent.com/20501666/49685053-08f83200-fadd-11e8-8a6a-e1bbd421c45b.jpg)

**Comment by manucorporat** [comment]
The hidden input is to handle issue around shadow-dom! the real input will still have the correct type!
