### ISSUE TITLE
Ionic 4.0.0-beta17 Android hardware (headache) back button

### ISSUE THREAD

**Issue by bogdanbaghiu** [ionic-team/ionic#16636]
# Bug Report

**Ionic version:**
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (C:\Users\bogdan\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.0.7
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 4 other plugins)

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

**Current behavior:**
Nothing

**Expected behavior:**
Closed app

**Steps to reproduce:**
 1 - Create a new ionic app with `ionic start app blank --type=angular``
 2 - Launch `ionic cordova run android --device`
 3 - Open the app
 4 - Press Android hardware (headache) back button

**Other information:**
Tested on Android 8.1 (Xiaomi Mi A2 Lite)

**Comment by paulstelzer** [comment]
Thanks for your issue! But there is already an issue for that. Please follow this issue #16611
