### ISSUE TITLE
[v4] Range with dual knobs failed to detect property changes

### ISSUE THREAD

**Issue by pjc0247** [ionic-team/ionic#16646]
I found that `ion-range` with `dual-knobs` not working as expected in some cases.

```html
<ion-range [(ngModel)]="age" dual-knobs=true min=1 max=100>
</ion-range>
```
__Not Working__
```js
this.age.lower = 1;
this.age.upper = 10;
```

__Working__
```js
this.age = {lower: 1, upper: 10};
```

Is this a language limitation or just a bug?

Thanks.

```
Ionic:

   ionic (Ionic CLI)             : 4.4.0 
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0
```

**Comment by manucorporat** [comment]
Unfortunately change detection in properties use equal comparison, if it's the same object, it's not able to detect the change. You should always pass a new object, not mutate the existing one
