### ISSUE TITLE
[4.0.0-beta.17] ion-select issues in edge

### ISSUE THREAD

**Issue by ajmchambers** [ionic-team/ionic#16659]
# Bug Report

**Info**
@ionic/core : 4.0.0-beta.17
@stencil/core : 0.16.0
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
Chrome Version 71.0.3578.80 (Official Build) (64-bit)

**Describe the Bug**
Issues with ion-select in edge:
- the placeholder/input fields are taking clicks instead of opening the selection
- selection options are left aligned in chrome, but centered in edge
- selected option(s) are not correctly displayed in edge 

![select-ionic](https://user-images.githubusercontent.com/5426717/49739562-14d52700-fc8a-11e8-9cb2-c821a1c69b86.gif)

**Related Code**
```html
<ion-content padding>
  <ion-item>
    <ion-label>Hair Color</ion-label>
    <ion-select value="brown" okText="Okay" cancelText="Dismiss">
      <ion-select-option value="brown">Brown</ion-select-option>
      <ion-select-option value="blonde">Blonde</ion-select-option>
      <ion-select-option value="black">Black</ion-select-option>
      <ion-select-option value="red">Red</ion-select-option>
    </ion-select>
  </ion-item>
  <ion-item>
    <ion-label>Pets</ion-label>
    <ion-select multiple>
      <ion-select-option value="bird" selected>Bird</ion-select-option>
      <ion-select-option value="cat">Cat</ion-select-option>
      <ion-select-option value="dog" selected>Dog</ion-select-option>
      <ion-select-option value="honeybadger">Honey Badger</ion-select-option>
    </ion-select>
  </ion-item>
</ion-content>
```

**Expected Behavior**
Should behave the same as chrome.

**Comment by paulstelzer** [comment]
Thanks! Yes, this is an issue in Edge.

**Comment by heyligengregory** [comment]
Any update ?

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as we recently released Ionic Framework v5 which dropped support for IE11 and older versions of Edge. Moving forward, Ionic Framework v4 will only receive critical security patches.
