### ISSUE TITLE
Using Slides.isEnd in template causes browser to crash

### ISSUE THREAD

**Issue by TwitchBronBron** [ionic-team/ionic#16657]
# Bug Report

**Ionic version:**

[x] **@ionic/angular 4.0.0-beta.17**

**Current behavior:**

When using `Slides.isEnd()` in a template, this causes the browser tab to crash. 

**Expected behavior:**

I should be able to do something like this: 

```html
<ion-slides #slides>...</ion-slides>
<button *ngIf="slides.isEnd()|async">Do something when at last slide</button>
```

**Steps to reproduce:**
1. Create a new ionic project
2. Add the code below to an html template and run the project using `npm run start`
3. Open the project in chrome (default http://localhost:4200)
4. Notice that the browser tab locks up and eventually crashes

**Related code:**
```html
<ion-content>
  <ion-slides #slides pager="true">
    <ion-slide>
      Slide 1
    </ion-slide>
  </ion-slides>
  <button *ngIf="slides.isEnd()|async">End slideshow</button>
</ion-content>
```

**Other information:**
It seems this issue is caused because `slides.isEnd()` returns a NEW promise on every call. Running this code validates my theory: `slides.isEnd() === slides.isEnd()` equals false every time. This means that that on every change detection loop, angular will detect a new promise and will watch/await that promise, repeating infinitely.

I recommend doing something like this:

1. The first time `slides.isEnd` is called, generate a promise with the result. Store that promise internally to slides, and then return the promise.
2. Any subsequent calls to `slides.isEnd` should return that same promise.
3. Anytime the `ionSlideDidChange` event fires, wipe out the stored promise. Back to step 1.

The issue may be related to the fact that [the method](https://github.com/ionic-team/ionic/blob/ecc2c55370e73239d775e921ceb8ba22a755c6fc/core/src/components/slides/slides.tsx#L223) is marked as async, and typescript will auto-generate a new promise on every call. So to mitigate this, you may have to use raw promise code instead. Something like this:

```typescript
private isEndPromise: Promise<boolean>;
public isEnd(): Promise<boolean>{
   if(!this.isEndPromise){
       this.isEndPromise = new Promise((resolve,reject) => {
           var value = calculateIsEndSomehow();
           resolve(value);
       });   
    }
    return this.isEndPromise;
}
```

**Ionic info:** 

```

Ionic:

   ionic (Ionic CLI)             : 4.5.0 (C:\Users\bronley\AppData\Roaming\nvm\v11.4.0\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.0.7
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.0

System:

   NodeJS : v11.4.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 7
```

**Comment by manucorporat** [comment]
This issue might not only apply to isEnd, but any other method. We can't the same promise, because that would always return the same value. I would suggest to resolve the value into an instance variable of you component, and use that variable instead of calling a method directly from the template.

**Comment by TwitchBronBron** [comment]
@manucorporat I'm not sure you totally understood my proposed solution, because, unless I'm missing something, it solves the "always return the same value" issue. 

In a nutshell, return the same promise until the underlying value changes, then return a new promise with the new value. Repeat. 

Step 3 of my above solution says "Anytime the ionSlideDidChange event fires, wipe out the stored promise". That's the trick here. 

Am I missing something where this wouldn't work?

**Comment by manucorporat** [comment]
@TwitchBronBron there are dozens of similar methods in Ionic, we can't add 30 lines of code for each one to solve an angular problem.

I would rather look why angular async itself does not "wait" for the promise to be resolved, and ask for a new promise every single time.

https://stackoverflow.com/questions/49843791/async-pipe-with-a-method-call-in-angular-4-calls-infinitely

**Comment by TwitchBronBron** [comment]
> I would rather look why angular async itself does not "wait" for the promise to be resolved, and ask for a new promise every single time.

There's nothing wrong with Angular in this situation. It's working as expected; this is pretty standard change detection stuff. Angular calls `slides.isEnd()` and gets a promise. Then Angular waits for that promise to resolve. Once that promise resolves, Angular runs another change detection cycle which includes running `slides.isEnd()` again (as it should), and notices that the promise reference has changed, so it now awaits that new promise (repeat until forever).

> we can't add 30 lines of code for each one to solve an angular problem

While ionic works as a standalone product now, isn't the majority of your user base still using Angular, meaning "an angular problem" is "your users' problem"? It feels to me like that is enough of a reason to fix it in Ionic. Plus, it's would be closer to 8 lines for each affected method, not 30. Minified and gzipped, I wouldn't expect the size increase to
