### ISSUE TITLE
Cannot add a border to fab-button

### ISSUE THREAD

**Issue by Maistho** [ionic-team/ionic#16652]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Cannot add a border or change the border-radius of `fab-button`

**Expected behavior:**
Can add a border or change the border-radius, as [the documentation states is possible.](https://beta.ionicframework.com/docs/api/fab-button/#css-custom-properties)

**Steps to reproduce:**
```
ion-fab-button {
  --border-radius: 10px;
  --border-color: white;
  --border-width: 4px;
  --border-style: solid;
}
```

**Related code:**
This line sets border to be zero, not taking the custom properties in account: https://github.com/ionic-team/ionic/blob/master/core/src/components/fab-button/fab-button.scss#L94

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/home/maistho/.config/yarn/global/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.11.2
   @angular-devkit/schematics    : 7.1.2
   @angular/cli                  : 7.1.2
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 5 other plugins)

System:

   NodeJS : v10.14.1 (/usr/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.19

```

**Comment by Maistho** [comment]
If that's OK, I can open a PR in order to get this fixed sooner. Already have it fixed on my fork. :slightly_smiling_face:

**Comment by paulstelzer** [comment]
That would be the best way :)
