### ISSUE TITLE
[4.0.0-beta.17] ion-input issues in edge

### ISSUE THREAD

**Issue by ajmchambers** [ionic-team/ionic#16662]
# Bug Report

**Info**
@ionic/core : 4.0.0-beta.17
@stencil/core : 0.16.0
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
Chrome Version 71.0.3578.80 (Official Build) (64-bit)

**Describe the Bug**
Issues with ion-input in edge:
- the placeholder text is styled incorrectly
- focused input has label colored in edge

![inputs-ionic](https://user-images.githubusercontent.com/5426717/49756083-7e1c6080-fcb1-11e8-8fc9-efc41bd8fcba.png)

**Related Code**
```html
<ion-content padding>
  <ion-item>
    <ion-label>Name</ion-label>
    <ion-input placeholder="This is the placeholder"></ion-input>
  </ion-item>
  <ion-item>
    <ion-label position="fixed">Name</ion-label>
    <ion-input placeholder="This is the placeholder"></ion-input>
  </ion-item>
  <ion-item>
    <ion-label position="floating">Name</ion-label>
    <ion-input></ion-input>
  </ion-item>
  <ion-item>
    <ion-label position="stacked">Name</ion-label>
    <ion-input placeholder="This is the placeholder"></ion-input>
  </ion-item>
  <ion-item>
    <ion-label position="stacked">Name</ion-label>
    <ion-input clear-input placeholder="This is the placeholder" value="clear me"></ion-input>
  </ion-item>
</ion-content>
```

**Expected Behavior**
Should behave the same as chrome.

**Comment by paulstelzer** [comment]
Thanks for the issue! The focused input has to be colored to match Material Design -> https://github.com/ionic-team/ionic/issues/15602#issuecomment-444795665 (this is wrong in browser who support shadom dom)

Edge is not using shadow dom, so it's a little bit different there.  But the placeholder should not be displayed bold.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as we recently released Ionic Framework v5 which dropped support for IE11 and older versions of Edge. Moving forward, Ionic Framework v4 will only receive critical security patches.
