### ISSUE TITLE
FormPage component, or Page smart enough to allow a root form

### ISSUE THREAD

**Issue by patrickmcd** [ionic-team/ionic#16661]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**

Whenever I have a form in Ionic, it's almost always the entire page. And I don't think I've ever had the need for two forms in a single page. This makes sense, given the mobile environment where it's better UX to follow the single-responsibilty principle down the page level.

Additionally, 75%+ of the time that I make a form, my submit button is in the header as a save/done/add/create button. This is pretty typical UX for list>detail CRUD apps.

Unfortunately, the layout of a page means the submit button will be outside of the form, leading to some hackery.

```html
<ion-header>
  <!-- Submit button outside of the form -->
</ion-header>
<ion-content>
  <form>...</form>
</ion-content>
<ion-footer>...</ion-footer>
```

It would be a nice option to have a form tag wrap the entire page. Maybe a new "FormPage" component. Or perhaps the Ionic Page component could be smart enough to allow a form tag as the single root tag rather than the three currently allowed (header, content, footer).

```html
<form>
  <ion-header>
    <!-- Toolbar with Submit button within the form -->
  </ion-header>
  <ion-content>
    <!-- Typical form controls -->
  </ion-content>
  <ion-footer>
    <!-- I can imagine form controls in a footer as well
    (perhaps a checkbox for accepting terms) -->
  </ion-footer>
</form>
```

**Comment by manucorporat** [comment]
That can be done, just ass the `ion-page`  class to the `<form>` itself. `.ion-page` just creates a flex box.

```
<form class="ion-page">
  <ion-header>
    <!-- Toolbar with Submit button within the form -->
  </ion-header>
  <ion-content>
    <!-- Typical form controls -->
  </ion-content>
  <ion-footer>
    <!-- I can imagine form controls in a footer as well
    (perhaps a checkbox for accepting terms) -->
  </ion-footer>
</form>
```
