### ISSUE TITLE
Ionic 4 with capacitor on iPhone landscape keyboard focus not right: iphone 8

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic#16676]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

On clicking on any input field on the iPhone landscape page shift is wrong. input field goes out of view and even on some screens keyboard is hidden behind a keyboard.

https://youtu.be/kveJ663r-oA

<img width="512" alt="screenshot 2018-12-11 at 3 03 45 pm" src="https://user-images.githubusercontent.com/8480351/49791214-f9cfe900-fd55-11e8-9134-9f890e4b3fb8.png">

**Expected behavior:**
On clicking on input field focus should be right

**Steps to reproduce:**

**Related code:**

```
<div class="ion-page">
  <ion-header>
    <ion-toolbar color="dark">
      <ion-buttons slot="start">
        <menu-button></menu-button>
      </ion-buttons>
      <ion-title>
        Developer
      </ion-title>
    </ion-toolbar>
  </ion-header>
  <ion-content class="hasfooter">
    <ion-list>
      <ion-item>
        <ion-label position="stacked">Service Host</ion-label>
        <ion-input :value="serviceHost" @ionInput="serviceHost = $event.target.value" placeholder="Enter Service Host"></ion-input>
      </ion-item>
      <ion-item>
        <ion-label position="stacked">Test1</ion-label>
        <ion-input :value="serviceHost" @ionInput="serviceHost = $event.target.value" placeholder="Enter Service Host"></ion-input>
      </ion-item>
      <ion-item>
        <ion-label position="stacked">Test2</ion-label>
        <ion-input :value="serviceHost" @ionInput="serviceHost = $event.target.value" placeholder="Enter Service Host"></ion-input>
      </ion-item>
      <ion-item>
        <ion-label position="stacked">test3</ion-label>
        <ion-input :value="serviceHost" @ionInput="serviceHost = $event.target.value" placeholder="Enter Service Host"></ion-input>
      </ion-item>
    
    </ion-list>
  </ion-content>
  <ion-footer>
    <ion-toolbar color="dark">
    </ion-toolbar>
  </ion-footer>
</div>

```

**Other information:**

**Ionic info:** 

```
"@capacitor/android": "1.0.0-beta.11",
		"@capacitor/cli": "1.0.0-beta.11",
		"@capacitor/core": "1.0.0-beta.11",
		"@capacitor/ios": "1.0.0-beta.11",
"@ionic/core": "4.0.0-beta.17",
		"@ionic/vue": "0.0.1",
```

**Comment by paulstelzer** [comment]
Thanks for your issue! This is related to Capacitor. Please see here -> https://github.com/ionic-team/capacitor/issues/814

**Comment by stripathix** [comment]
Thanks, @paulstelzer  for a response. Is this is issue discussing the same thing? I think they are discussing the solution of when keyboard is hidden then UI comes back to right position. But I am pointing out that when keyboard is opened then the input box goes out of view box.

Should I open separate issue with Cordova?

Solutions suggested in this thread (https://github.com/ionic-team/capacitor/issues/814) did not fix my issue

**Comment by paulstelzer** [comment]
If this is an issue for Cordova keyboard, too, then you can open an issue ticket here -> https://github.com/ionic-team/cordova-plugin-ionic-keyboard 

If you think you found a new issue, that nobody has mentioned yet, so feel free to open a new issue here at Capacitor -> https://github.com/ionic-team/capacitor/issues
