### ISSUE TITLE
[v4] Contribution Guide

### ISSUE THREAD

**Issue by pjc0247** [ionic-team/ionic#16672]
It's time to update your __Contribution Guide__.

https://github.com/ionic-team/ionic/blob/master/.github/CONTRIBUTING.md#typescript-changes

It seems that you don't use `gulp` in v4 anymore...

**Comment by paulstelzer** [comment]
Thanks for your time to mention this! You are right, it's a little bit outdated :D

**Comment by mburger81** [comment]
Can someone please help a little bit on how we can contribute. I also noticed the documentation is complete out of date, for example there is no gulp integration.

If we checkout repository and after doing `npm install` we try to start with `npm start ` as described in https://github.com/ionic-team/ionic/blob/e402766d03ceeae75cb9576e0a2c02fb5e82008d/core/CONTRIBUTING.md but in `package.json` there is no `start` script.

Also `npm run dev` or `npm run devapp` is not working as expected.

So the main question is, how can we run the dev server to develop the component, and how we can we test only this single controller or component?

**Comment by mburger81** [comment]
Thx, but for me remains the same problem
on `npm run start` I get the error 
`error missing script: start`
and there is no start script in `package.json`,  this should run stencil server right? Do we need have installed something other globally, except `npm` and `node`?

**Comment by paulstelzer** [comment]
Read again -> https://github.com/ionic-team/ionic/blob/b44c5c8bbd173f5bf7517b5793e12102487ca35c/.github/CONTRIBUTING.md#viewing-changes

First step is to switch to the `core `folder, then` npm start`

**Comment by mburger81** [comment]
Obviously I'm in the core folder and I had run before npm install from core folder :)
