### ISSUE TITLE
The display is blank screen in QQ mobile browers, huawei mobile browser is so too

### ISSUE THREAD

**Issue by eric812** [ionic-team/ionic#16671]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

It is right show on Chrome in mobile ,but display is blank screen on QQ browser, and browse of  huawei mobile display is blank too.

**Steps to reproduce:**

I press F12 found that the visibility of all ion elements is hidden

**Other information:**

bug url: 152.101.24.217:9900

**Ionic info:** 

Ionic:

   ionic (Ionic CLI)             : 4.2.1 (C:\Users\eric\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.8.6
   @angular-devkit/schematics    : 0.8.6
   @angular/cli                  : 6.2.6
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.3, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (F:\android_sdk\sdk)
   NodeJS            : v8.9.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.2.0
   OS                : Windows 10

**Comment by paulstelzer** [comment]
Thanks for your issue! I think this is related to #15438 that these browsers do not support specific javascript features.

**Comment by manucorporat** [comment]
We will accept PRs that might fix the issues in that browsers, but we don't officially support the mentioned browsers, sorry :(
