### ISSUE TITLE
[v4] Failed to load resources on mobile devices

### ISSUE THREAD

**Issue by pjc0247** [ionic-team/ionic#16670]
https://github.com/ionic-team/starters/issues/451

There is an old issue on `ionic/starters` repository, but nobody takes a look and actually not related to `starters`, So I made an issue here.

Every asset failed to load excepts `index.html`.

![image](https://user-images.githubusercontent.com/1961216/49772137-697ead80-fd2f-11e8-9c43-da78e70b31ee.png)

**Comment by pjc0247** [comment]
I've checked both `v3` and `v4` with same `ionic` version. (4.4.0)
`v3` works well.

**Comment by paulstelzer** [comment]
There is already an issue at the starter: https://github.com/ionic-team/starters/issues/451 - So I close this here

**Comment by pjc0247** [comment]
@paulstelzer That issue is old, nobody responds.
