### ISSUE TITLE
Ionic 4 DateTime lag when scrolling especially on year with format MMM DD, YYYY

### ISSUE THREAD

**Issue by voltairebiton** [ionic-team/ionic#16681]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Scrolling is slow especially on year.

**Expected behavior:**

Scrolling should be fast. It is slow if i scroll on year. This is my format MMM DD, YYYY

**Steps to reproduce:**
Just add this on your ionic 4 app
`<ion-datetime display-format="MMM DD, YYYY"></ion-datetime>`
then run on your android device. Try playing with the scroll. I have tested on android 7 honor lite and android 8 samsung j4 phone. In android 7 phone, scrolling to all is slow, while on samsung j4, its slow on year only. I think it gets slower the more the characters are like the year format which has 4 and also probably depending on how fast the device is. 

**Ionic info:** 

Ionic:

   ionic (Ionic CLI)             : 4.3.1 (C:\Users\Jams\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.1.2
   @angular/cli                  : 7.1.2
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (9 plugins total)

System:

   Android SDK Tools : 26.1.1 (C:\Android\android-sdk)
   NodeJS            : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 7

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us. I am going to close this for now, but we will be re-evaluating the `ion-datetime` functionality and bugs soon during which we will take a closer look at this issue.

Thanks for using Ionic!
