### ISSUE TITLE
V4-beta17 : Hardware BackButton doesn't close the App

### ISSUE THREAD

**Issue by trollanfer** [ionic-team/ionic#16689]
The blank app doesn't close when hitting the hardware backButton on my Xiaomi phone.
In V3, it did.

I tried this : 
`backButtonEvent(){
        this.platform.backButton.subscribe(()=>{
            navigator['app'].exitApp();
    })`

Which is working, but EVERYWHERE in the app, so the classic 'back' is overrriden and the app closes everytime the backbutton is hit.

I think this should be handled by the framework with a different behaviour according to the possibility of going back or not to close the app ?

**Comment by paulstelzer** [comment]
Thanks for your issue! Please use the issue template next time :)

Your issue is already on our list for the back button, see #16611

So I close this here because it's better to have only one issue opened for the same topic! If you found another issue, feel free to open a new one!
