### ISSUE TITLE
Ionic v4 beta17 Select box value is displayed after clicking the select box.

### ISSUE THREAD

**Issue by Balaraju1** [ionic-team/ionic#16696]
# Bug Report

**Ionic version:**

[x] **4.0 beta 17**

**Current behavior:**

The selected value is not displayed in ion-select. It gets displayed after clicking the field.
**Expected behavior:**

The value should be displayed without clicking the field.
**Steps to reproduce:**

1.Create Ionic v17 project with below code.
2.Click on Get List button, You can see the value is not displayed for select box.
3.Click on the field and the value gets displayed now.
**Related code:**
TS Code:
```
@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
})
export class AppComponent {

  Names: any[] = [];

  NameCtrl: FormControl = new FormControl('1');

  constructor() {

  }

  GetList(){
    this.GetNames().subscribe((names: any) => {
      this.Names = names;
      console.log('got list of names but the value is not displayed yet');
      console.log('now click on the select box');
    });
  }

  GetNames() {
    return Observable.of([{ key: '1', value: 'Abhi' }, { key: '2', value: 'Rahul' }]);
  }

}

```

HTML Code

```
<ion-content>
    <ion-card>
        <ion-item>
            <ion-label>Name:</ion-label>
            <ion-select interface="popover" [formControl]="NameCtrl">
                <ion-select-option *ngFor="let name of Names" [value]="name.key">{{name.value}}</ion-select-option>
            </ion-select>
        </ion-item>
        <ion-button (click)="GetList()">Get List</ion-button>
    </ion-card>
</ion-content>
```
The list of options that should be displayed in Select box is got after clicking a button. Even after getting the list the value is not updated.I replaced ion-select with material select and HTML5 select and they work as expected.

I have made a video which demonstrates the above issue. In the video you can see the value is not selected but after clicking the field, the value is displayed:
https://www.useloom.com/share/489354412a5d4f6fa561713ead6739ef

**Comment by paulstelzer** [comment]
Thanks for the issue! I think this is the same like #15716 

If you confirm, I would close this issue here because it's better to only have one issue about the same thing

**Comment by Balaraju1** [comment]
The code is inspired from the same issue. In the bug i mentioned, the value gets selected after clicking the select box which was not occurring before.(In the bug you mentioned, the value is not selected even after clicking the select box).

**Comment by paulstelzer** [comment]
But then I do not understand why you are opening a new issue instead of add a comment there?

**Comment by Balaraju1** [comment]
@paulstelzer I think this is a new issue or sub issue of the existing one. When can i expect this to be fixed?
