### ISSUE TITLE
Ionic v4-beta17 Input boxes valuechange fired when formcontrol is reset

### ISSUE THREAD

**Issue by Balaraju1** [ionic-team/ionic#16695]
# Bug Report

**Ionic version:**

[x] **4.0 beta 17**

**Current behavior:**

When angular form reset is called with {emitEvent:false} the control pristine status is changed to dirty and valuechanges is fired. This behavior occurs when ion-input is used. And reset event on select box works as expected. I tried replacing the ion-input with Angular material input and HTML5 input field.And they work as expected. This issue exists if i use Ion-Input.

**Expected behavior:**

When reset is called with {emitEvent:false} the valuechanges should not be fired and control should be pristine.

**Steps to reproduce:**

1.Create Ionic v4 beta17 app with the below code.
2.Open console and click on reset button.
3.In the console window, you will see the value changes of input box is fired and the pristine status is false.And the selectbox valuechanges is not fired which is working as expected.
4.Replace the ion-input with html5 input, and repeat step2. Now the valuechanges of textbox is not fired.

**Related code:**

HTML Code:
```
<ion-content>
    <ion-card>
        <ion-item>
            <ion-label>Amount</ion-label>
            <ion-input type="number" [formControl]="Amount"></ion-input>
        </ion-item>

        <ion-item>
            <ion-label>Gender</ion-label>
            <ion-select [formControl]="Gender">
                <ion-select-option value="Select">Select</ion-select-option>
                <ion-select-option value="Male">Male</ion-select-option>
                <ion-select-option value="Female">Female</ion-select-option>
            </ion-select>
        </ion-item>

        <ion-button (click)="ResetValues()">Reset</ion-button>
    </ion-card>
</ion-content>
```
TS Code:
```
@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
})
export class AppComponent {

  Amount: FormControl = new FormControl();

  Gender: FormControl = new FormControl('Select');

  constructor(public fb: FormBuilder) {
    this.Amount.valueChanges.subscribe((val: any) => {
      console.log('text box value changed');
      console.log('Is textbox pristine? ' + this.Amount.pristine);
    });

    this.Gender.valueChanges.subscribe((val: any) => {
      console.log('select box value changed');
      console.log('Is selectbox pristine? ' + this.Gender.pristine);
    });
  }

  ngOnInit() {
  }

  ResetValues() {
    this.Amount.reset(Math.random(), { emitEvent: false });
    this.Gender.reset('Male', { emitEvent: false });
  }

}
```

I have done a recording which shows the bug.
https://www.useloom.com/share/b573711e565740b2bfa55e2f73106e99

This issue occurs only when I use Ionic inputs. Can any one from the Ionic team tell me when this issue will be fixed?

Thank you
Balaraju

**Comment by paulstelzer** [comment]
Thanks for your issue! There is already an issue about the ignoring of emitEvent, so I close this here

Related to #16452

Please follow this issue and if you found another issue, feel free to open a new one :)
