### ISSUE TITLE
ts-jest with cleared cache is reading package.json in node_modules over and over - start takes forever

### ISSUE THREAD

**Issue by Farbdose** [ionic-team/ionic#16703]
# Bug Report

I just updated to ts-jest@23.10.5 from somewhere around ~23.1.3 which increased the runtime of my test suite from 10ish seconds [on the first run / with cleared cache] to over 40 seconds - with cache around 2.5s.

It's possible that this is a ts-jest (or even typescript) issue BUT after I created a demo-repository I realized that the problem went away after I removed ionic from the project. 
So ionic probably has something to do with it.

**Ionic version:**

[x] **4.x**

**Current behavior:**
The initial start of jest takes around 30 seconds on an almost empty repository with ionic included.

**Expected behavior:**
The initial start of jest shouldn't take that long.

**Steps to reproduce:**

- Have js files that need to be processed by ts-jest (as they contain import statements) being present in one of the modules you import
- have ts-jest@>=23.10.1
- import the IonicModule in one of you angular modules

**Related code:**
https://gitlab.com/Farbdose/ts-jest-multiple-fileread

```
git clone git@gitlab.com:Farbdose/ts-jest-multiple-fileread.git
npm install && npm run test
```

**Other information:**

You can find the original issue at https://github.com/kulshekhar/ts-jest/issues/908
Possibly related https://github.com/ionic-team/ionic/issues/15695: I had to use the fix described there to actually get jest running at all.

**Ionic info:** 

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   ionic (Ionic CLI) : 4.3.1

System:

   NodeJS : v8.11.2
   npm    : 6.1.0
   OS     : Linux 4.15
```

**Comment by Farbdose** [comment]
**Update:** I played a bit around and wrote a very basic cache into `getPackageJsonInfo` see [here](https://github.com/kulshekhar/ts-jest/issues/908#issuecomment-448265415) ...which got the time down to around 24s again.

The interesting thing though is, that after that I got a much clearer cpu profile:
[CPU-20181218T162138.zip](https://github.com/kulshekhar/ts-jest/files/2691199/CPU-20181218T162138.zip)

**Comment by Farbdose** [comment]
Update3: This was caused by a combination of uncached file reads and now by default enabled language services. It has nothing to do with ionic, ionic was just the the package with the most require statements in node_modules.

**Comment by Farbdose** [comment]
yes

**Comment by paulstelzer** [comment]
Thank you for the resarch :)

**Comment by Farbdose** [comment]
@paulstelzer I think the only thing you could have realistically done is what you alread did: remove the icons from the build chain.
