### ISSUE TITLE
Picker of ion-datetime not apply "md" mode in Ionic v4

### ISSUE THREAD

**Issue by duyetnk** [ionic-team/ionic#16717]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I set whole app in ios mode,
and set mode="md" in pickerOptions of ion-datetime
but only buttons have md's style, columns still have ios's style like image:

![ion-picker_bug](https://user-images.githubusercontent.com/34903895/49923532-5e21b280-fee6-11e8-969c-3904abfbc0b4.png)

**Expected behavior:**

When set mode="md" in pickerOptions of ion-datetime, whole picker should display in md's style

**Steps to reproduce:**

Insert code bellow to reproduce

**Related code:**
In app.module.ts:
```
IonicModule.forRoot({
     mode: 'ios',
}),
```
in home.page.html:
```
<ion-item no-lines mode="md">
	<ion-label class="">Select Time</ion-label>
	<ion-datetime displayFormat="hh:mm A" [(ngModel)]="selectTime"[pickerOptions]="pickerOptions"></ion-datetime>
</ion-item>
```
in home.page.ts
```
pickerOptions: any = {
	mode: "md",
};
```

```
insert short code snippets here
```

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (C:\Users\naugh\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 7.0.3
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 13 other plugins)

System:

   NodeJS : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by paulstelzer** [comment]
Thanks for you issue! I have not tested it yet, but you have to add the mode to the ion-datetime directly.

`<ion-datetime mode="md">/ion-datetime>`

**Comment by duyetnk** [comment]
yeah, i also add mode="md" to ion-datetime directly but it's still not working.

**Comment by paulstelzer** [comment]
So I take a further look again and you are right. If you want to style the picker, you have to use the picker options (my first answer was wroong) and as I saw, you set them to the datetime, but I think you missed a whitespace before ` [pickerOptions]` :

`<ion-datetime displayFormat="hh:mm A" [(ngModel)]="selectTime" [pickerOptions]="pickerOptions"></ion-datetime>`

For me everything works as expected:

ios mode, only the picker is in md mode

![chrome_2018-12-13_10-56-29](https://user-images.githubusercontent.com/20501666/49931016-36baed80-fec6-11e8-8b18-1dc6457854a9.jpg)

**Comment by duyetnk** [comment]
in your image only buttons in md mode, columns(months, days, years) is still have some style of ios mode.
in md mode, columns's style is flat,
in our case columns will rotate when scroll
you can check the different here: https://beta.ionicframework.com/docs/api/datetime

**Comment by paulstelzer** [comment]
This is iOS. Complete different style:

![chrome_2018-12-13_10-57-09](https://user-images.githubusercontent.com/20501666/49933554-3887af80-fecc-11e8-9c74-5e632a517d35.jpg)

**Comment by duyetnk** [comment]
yes, i know.
like i said above, in md mode the columns still have some style of ios mode.
it rotate when scroll, not flat
you can see 2 images bellow to see the different (notice red rectangle):
here the picker with true md style:
![md-picker](https://user-images.githubusercontent.com/34903895/49933957-aef1d500-feff-11e8-9390-11fe589694f6.png)
and here the picker when app in ios mode, but picker in md mode
![md ios -picker](https://user-images.githubusercontent.com/34903895/49933965-b6b17980-feff-11e8-8df1-48ae9676872e.png)

**Comment by paulstelzer** [comment]
Okay the second I see, what you want to say with the first image? The margin is bigger?

**Comment by duyetnk** [comment]
in the first image, i mean the style is flat
i want the second have the style like the first, it is md mode.

**Comment by paulstelzer** [comment]
Ah oaky, it the end it's only this issue - correct? Could you please adjust your issue to make it clear

**Comment by duyetnk** [comment]
yes, correct
