### ISSUE TITLE
[4.0.0-beta.18] A non-existing date can be selected

### ISSUE THREAD

**Issue by duyetnk** [ionic-team/ionic#16733]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
You can select a non-existing date:
![ion-datetime-wrongdate](https://user-images.githubusercontent.com/34903895/49980012-2f5a1980-ff84-11e8-801c-842725696a32.png)
![ion-datetime_wrongdate 2](https://user-images.githubusercontent.com/34903895/49980016-32eda080-ff84-11e8-97cf-b69004463874.png)

**Expected behavior:**

All non-existing dates will not show when picking months

**Related code:**
```
<ion-item>
	<ion-label>Select Date</ion-label>
	<ion-datetime displayFormat="MM/DD/YYYY" [(ngModel)]="selectDate"  min="2018" max="2023"></ion-datetime>
</ion-item>
```
**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (C:\Users\naugh\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.18
   @angular-devkit/build-angular : 0.10.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 7.0.3
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 13 other plugins)

System:

   NodeJS : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us. I am going to close this for now, but we will be re-evaluating the `ion-datetime` functionality and bugs soon during which we will take a closer look at this issue.

Thanks for using Ionic!
