### ISSUE TITLE
ion-toggle onIonChange is not being called

### ISSUE THREAD

**Issue by nkprince007** [ionic-team/ionic#16735]
```
import React, { Component } from 'react';
import PropTypes from 'prop-types';

class SimpleComponent extends Component {
  constructor(props) {
    super(props);
    this.state = {
      ioToggle: true,
    }

    this.toggleIO = this.toggleIO.bind(this);
  }

  toggleIO() {
    console.log('toggled');
    this.setState((prevState) => {
      return { ioToggle: !prevState.ioToggle };
    });
  }

  render() {
    const { ioToggle } = this.state;
    return (
      <ion-card color="dark">
        <ion-card-content no-padding>
          <ion-toggle
            color="success"
            checked={ioToggle}
            mode="ios"
            onIonChange={this.toggleIO}
          />
        </ion-card-content>
      </ion-card>
    );
  }
}

export default SimpleComponent;
```

The console does not log anything and the state isn't updated as well.

I'm using `@ionic/core 4.0.0-beta.16` in a pure javascript application.

**Comment by nkprince007** [comment]
Also, the documentation here https://beta.ionicframework.com/docs/api/toggle/ does not show how to bind event callbacks in vanilla Javascript apps.

**Comment by paulstelzer** [comment]
Thanks for your issue! I am not using it in a vanilla javascript app, but in Angular this is working:

```
    <ion-item>
        <ion-label>Pepperoni</ion-label>
        <ion-toggle (ionChange)="toggleChanged($event)" slot="end" value="pepperoni" checked></ion-toggle>
      </ion-item>
```

And in ts:

```
  toggleChanged($event) {
    console.log($event);
  }
```

Maybe this help you already.

**Comment by nkprince007** [comment]
Hey @paulstelzer, looks like it's more of a React issue with web components.

Reference: https://reactjs.org/docs/web-components.html

As a work around, I'm able to hook in `addEventListener('ionChange', () => { /* do something */ })`. But, since you guys are planning on supporting integration into react, this might be something you wanna look into as well. 

However, please add in the vanilla javascript example into the documentation as mentioned earlier. I could send in a PR if you'd like.

**Comment by paulstelzer** [comment]
That would be great if you add a PR :)
