### ISSUE TITLE
Extra space in the toolbar of footer

### ISSUE THREAD

**Issue by tjpatange** [ionic-team/ionic#16740]
# Bug Report

**Ionic version:**

**4.3.0**

**Current behavior:**Extra space under the toolbar of the footer

**Expected behavior:** No such space irrespective of screen height

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

    <ion-footer [hidden]="selectedData.Cts == 0">
        <ion-toolbar>
          <ion-row>
            <ion-col col-2 text-center>Pcs</ion-col>
           <ion-col col-2 text-center>Cts</ion-col>
           <ion-col col-2 text-center>Disc %</ion-col>
           <ion-col col-3 text-center>Price</ion-col>
           <ion-col col-3 text-center>Amt $</ion-col>
         </ion-row>
         <ion-row>
           <ion-col col-2 text-center>{{selectedData.Pcs}}</ion-col>
          <ion-col col-2 text-center>{{selectedData.Cts}}</ion-col>
          <ion-col col-2 text-center>{{selectedData.Disc}}</ion-col>
          <ion-col col-3 text-center>{{selectedData.Price}} $</ion-col>
          <ion-col col-3 text-center>{{selectedData.Amt}} $</ion-col>
         </ion-row>
     </ion-toolbar>
    </ion-footer>
**Other information:**

This issue is on Iphone XS or may on mobile with safe-area
Also showing the screen shot of mobile on which application is running below:

![whatsapp image 2018-12-14 at 12 22 30](https://user-images.githubusercontent.com/16642633/50002155-6984e480-ff9f-11e8-8fe4-f8c8408187cc.jpeg)

**Comment by manucorporat** [comment]
You meant you expect something like this:
![image](https://user-images.githubusercontent.com/127379/50002594-e2d10700-ffa0-11e8-8425-89482fe84b5f.png)
?

This extra space is what it needs to be in iPhone X according to the Apple's guidelines.
![image](https://user-images.githubusercontent.com/127379/50002637-01370280-ffa1-11e8-93ca-07c36fc574ac.png)

**Comment by manucorporat** [comment]
Oh! if you meant the second toolbar, the problem might be that

**Comment by tjpatange** [comment]
But it is too much, on google chrome it appears proper(in the device toolbar):
![localhost_8100_ iphone xs](https://user-images.githubusercontent.com/16642633/50003008-60494700-ffa2-11e8-8d6d-835f05db9a93.png)

Just see the difference between the above picture and the one provided in the 
issue

**Comment by manucorporat** [comment]
yep, @tjpatange I am sorry, my fault. I am looking into it!
