### ISSUE TITLE
Styles don't copy with ionic 4

### ISSUE THREAD

**Issue by dxvladislavvolkov** [ionic-team/ionic#16742]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I want to copy some styles to assets folder. For this, I used the copy.config.js in version 3.
I created a file copy.config.js and add a code:

```js
var copy = require('@ionic/app-scripts/config/copy.config.js');

copy.copyStyleSheets = {
  src: ['{{ROOT}}/node_modules/devextreme/dist/css/**/*'],
  dest: '{{WWW}}/assets/css'
};

module.exports = copy;
 ```
And then add the config to package.json:
```js

"config" : {
    "ionic_copy": "./copy.config.js"
},
```
Add links to the required stylesheets to the head section of the "src\index.html" file
`<link href="assets/css/some-styles.css" rel="stylesheet">`
This does not work in the ionic 4

**Expected behavior:**

The above example works in ionic 3.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by paulstelzer** [comment]
Thanks for your issue! This method is not needed with Ionic 4 and if your are using Angular 6 or 7.

Just open the angular.json and you can add whatever css file you want to your assets folder
