### ISSUE TITLE
[v4-beta.18] platform.resume should not emit void but the event object

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#16747]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
`Platform.resume` emit currently `void` (see https://github.com/ionic-team/ionic/blob/master/angular/src/providers/platform.ts)

I think that this isn't correct. For example, Cordova will emit an event when resume is triggered. This is notably useful when an app is stopped and restarted after the camera would have been use, see:

Cordova documentation -> https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#lifecycle-guide

Particulary:

```
{
    action: "resume",
    pendingResult: {
        pluginServiceName: string,
        pluginStatus: string,
        result: any
    }
}
```

Camera quirks on the forum -> https://forum.ionicframework.com/t/solved-camera-plugin-restart-app-on-android/117828/15

Old related repo -> https://github.com/peterpeterparker/ionic-zurich-cordova-android-quirks

**Expected behavior:**
`Platform.resume` should emit an event object

**Comment by peterpeterparker** [comment]
@paulstelzer sorry but not sure that it's a "feature request" as it's a breaking change in comparison to Ionic v3 and how Cordova behave

source of `platform` in v3: https://github.com/ionic-team/ionic-v3/blob/20dfbdd3037fa86dcda2a5ce07a2476ae344a9ee/src/platform/platform.ts

```
resume: EventEmitter<Event> = new EventEmitter<Event>();
```

**Comment by paulstelzer** [comment]
Yes, but it's not a bug ;) Bug is when something isn't working. But it's uninteresting how I label it. More important is if it will be added or not. Could you make a PR?

**Comment by peterpeterparker** [comment]
@paulstelzer you are right of course, I just allowed my self to point that out in terms of priority you know, just to be sure that this would not be saved somewhere as a "nice to have" or at least marked somewhere as a breaking change

about the PR to be honest I'm not sure if the solution is "just" a typing thing or more...

**Comment by manucorporat** [comment]
paused/resumed might be also used by capacitor, or other native layers, we have to be careful with the interface of the events
