### ISSUE TITLE
[4.0.0-beta.18] 'ion-anchor' is not a known element

### ISSUE THREAD

**Issue by viccatoff** [ionic-team/ionic#16743]
After I've updated from beta-17 to beta-18 I got this error for all `ion-anchor` elements on template:

```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
'ion-anchor' is not a known element:
1. If 'ion-anchor' is an Angular component, then verify that it is part of this module.
2. If 'ion-anchor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

If I'm reverting back to beta-17 - the error is gone.

**Comment by manucorporat** [comment]
Ion-anchor is only used in the context of web components using the ion-router for angular, you should use:

```html
<a routerLink="/path">Link</a>
```

**Comment by moose4lord** [comment]
@manucorporat, I'm not sure I understand your comment. Did you mean to write two sentences:
"Ion-anchor is only used in the context of web components using the ion-router. For angular, you should use: `<a routerLink="/path">Link</a>`"

If using Angular, does `<a>` support the router-direction attribute?

**Comment by manucorporat** [comment]
@moose4lord yep, that right. And yep, `<a>` does support routerDirection in angular
