### ISSUE TITLE
[v4-beta.18] New lazy loaded tabs unexpected page transition animation

### ISSUE THREAD

**Issue by uncvrd** [ionic-team/ionic#16754]
# Bug Report

**Ionic version:**
[x] **4.0-beta.18**

**Current behavior:**
Using the updated lazy loading tabs method specified by Manu in the beta.18 release notes, transitioning from one page to the next within a lazy loaded tab produces a popover animation (with the tab bar at the bottom).

**Expected behavior:**
I am expecting an animation that slides from the right to left when using the `navigateForward` method from `NavControl`.

**Steps to reproduce:**
As specified by Manu in the beta.18 release notes, I have refactored my tabs page to lazy load 4 different tabs. For this example, I'll just focus on the `Home` tab..in my `tabs.router.module.ts` I have: 

```
const routes: Routes = [
  {
    path: 'tabs',
    component: TabsPage,
    children: [
      {
        path: 'home',
        loadChildren: '../home/home.module#HomePageModule'
      },
      {
        path: '',
        redirectTo: '/tabs/home',
        pathMatch: 'full',
      }
    ]
  },
  {
    path: '',
    redirectTo: '/tabs/home',
    pathMatch: 'full'
  }
```

and a `home.module.ts` with the following routes:

```
const routes: Routes = [
      {
        path: '',
        component: HomePage
      },
      {
        path: 'artist/:artist',
        component: ArtistPage
      }
]
```

I should expect to be routed to the `HomePage` with a url such as `tabs/home` and I should be routed to an artist page when I click on a profile from the home page with a url like `tabs/home/artist/uid` by using `this.navCtrl.navigateForward(`tabs/home/artist/${this.artist.artistUID})`);` within my `home.page.ts`. 

I am successfully routed to the artist page, but the transition animation is not the one I expected. I attached a gif of the transition. Notice how the animation slides up from the bottom instead of from the side? That is not the animation I would expect from using the `NavigateForwad` method. Unless my routes are incorrectly configured, let me know what else you need!

![demo1](https://user-images.githubusercontent.com/25097099/50040320-1ab66980-fff6-11e8-9189-ef1c28599a10.gif)

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.18
   @angular-devkit/build-angular : 0.12.0-beta.2
   @angular-devkit/schematics    : 0.8.8
   @angular/cli                  : 7.2.0-beta.2
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   ios-deploy : 1.9.2
   NodeJS     : v10.13.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61
```

**Comment by uncvrd** [comment]
Hey @paulstelzer , I have a bit of an update on this as well. I tried running the same code on iOS and the animation (from right to left) works as expected HOWEVER, I found two issues. 

The first issue is that sometimes the transition between home pages and artist pages will stutter and you can see a white background as you animate between pages. You can see this just about every time I click on an artist profile.

The second issue occurs when I swipe back to return pages, sometimes when I swipe back but hold my finger on the screen near the edge and then let go, and I try and click on an artist profile, it simply does not transition pages anymore. TIMESTAMP: 0:21

Streamable link displaying the issues: https://streamable.com/s/m5rw1/hsbcvm

Let me know if you need any more info

**Comment by manucorporat** [comment]
It's the expected behaviour, that's the material design "transition" animation.

Regarding this issue:

>The second issue occurs when I swipe back to return pages, sometimes when I swipe back but hold my finger on the screen near the edge and then let go, and I try and click on an artist profile, it simply does not transition pages anymore. TIMESTAMP: 0:21

Can you open a new issue?

**Comment by uncvrd** [comment]
@manucorporat oh thanks! Coming from iOS, was not aware there were platform specific animation transitions. Yes I'll open an issue for that!
