### ISSUE TITLE
not exist popToRoot for NavController[ionic4-beta19]

### ISSUE THREAD

**Issue by shomid** [ionic-team/ionic#16756]
exist popToRoot method in beta ionic 4 document for NavController.
but not exist popToRoot in coding.
[https://forum.ionicframework.com/t/ionic4-beta17-pop-all-pages-except-root/150111/9](url)

**Comment by paulstelzer** [comment]
> Nav is a standalone component
Source: https://beta.ionicframework.com/docs/api/nav/

NavController is not nav. What you need is NavController. I did not found a documentation, so I post the source file -> https://github.com/ionic-team/ionic/blob/master/angular/src/providers/nav-controller.ts
