### ISSUE TITLE
v4-beta.18 - Error: Template parse errors: 'ion-tab' is not a known element

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic#16764]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Update from beta.17 to beta.18

**Expected behavior:**

Site would work

**Steps to reproduce:**

**Related code:**

A sample application via GitHub

Ref: https://github.com/peterennis/aetabs/commit/ed7286315edc575b5bfa7691c710868903ee1b6e
Current site running beta.17 : https://aetabs.adaept.com
![capture468](https://user-images.githubusercontent.com/140737/50051092-9c72c980-00c0-11e9-8f20-3b87443b6aeb.png)

Result running beta.18
![capture466](https://user-images.githubusercontent.com/140737/50051097-ae546c80-00c0-11e9-9ce5-f7fb611477e7.png)

**Other information:**

I am using tabs with sidemenu.
There is no official sample.
I read breaking changes, tried the suggestions, but could not get it to work.

@manucorporat 
Possibly related: https://github.com/ionic-team/ionic/issues/16343

**Ionic info:** 

```
C:\ae\adaept.com\aetabs>ionic info

Ionic:

   ionic (Ionic CLI)             : 4.5.0 (C:\Users\peter\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.18
   @angular-devkit/build-angular : 0.11.3
   @angular-devkit/schematics    : 7.1.3
   @angular/cli                  : 7.1.3
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (2 plugins total)

System:

   NodeJS : v10.14.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by paulstelzer** [comment]
`ion-tab` is not a known element in beta.18 / beta.19. Remove this and read the breaking changes again -> https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#angular-tabs

There you see that you have to remove the `ion-tab`. I close this here but you can still comment here if you don't get it work

**Comment by Freelane-team** [comment]
Sorry, I miss something here for the angular part: following your advice, I get this error:
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'tabs/tab1'
Error: Cannot match any routes. URL Segment: 'tabs/tab1'

Did you change something respective to path and outlet ?

const routes: Routes = [
  {
    path: 'tabs',
    component: TabsPage,
    children: [
      {
        path: '',
        redirectTo: '/tabs/(tab1:tab1)',
        pathMatch: 'full',
      },
      {
        path: 'tab1',
        outlet: 'tab1',
        component: Tab1Page
      },
      {
        path: 'tab2',
        outlet: 'tab2',
        component: Tab2Page
      },
      {
        path: 'tab3',
        outlet: 'tab3',
        component: Tab3Page
      }
    ]
  },
  {
    path: '',
    redirectTo: '/tabs/(tab1:tab1)',
    pathMatch: 'full'
  }
];

**Comment by paulstelzer** [comment]
Thanks for your response! I can still tell you to look at the breaking changes :) https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#angular-tabs

Remove all outlets and fix the redirectTo

**Comment by Freelane-team** [comment]
ok my mistake, was looking at this:

https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md
