### ISSUE TITLE
bug: modal entrycomponent - Error: Cannot find module './undefined.entry.js'

### ISSUE THREAD

**Issue by paulstelzer** [ionic-team/ionic#16768]
# Bug Report

**Ionic version:**

[x] **4.0.0@beta.19**

**Current behavior:**
If you create a modal and put it inside the entryComponents and inside is `<ion-progress-bar>` it will show you an error if you want to open the modal: `Error: Cannot find module './undefined.entry.js'`. The modal will not be opened. If I remove `<ion-progress-bar>` everything is working again.

![chrome_2018-12-16_14-12-11](https://user-images.githubusercontent.com/20501666/50053962-0335c880-013d-11e9-86da-06c97d33f4e0.jpg)

**Expected behavior:**
The modal should work. If I remove  `<ion-progress-bar>` it will work. There are still ionic elements in it like ion-button, ion-header and ion-footer - working without problems.

![chrome_2018-12-16_14-15-22](https://user-images.githubusercontent.com/20501666/50053964-09c44000-013d-11e9-88d2-62de481c8be3.jpg)

**Steps to reproduce / Related code:**
I created a repo here: https://github.com/paulstelzer/test-ionic

1. Tap on "Show Modal". You get the error
2. Open test-modal.component.html and comment out the first line
3. It will work without `<ion-progress-bar>`

**Comment by paulstelzer** [comment]
Wrong code

**Comment by doncabron** [comment]
So what was the cause/solution? I'm having the same error message, and I got no bloody clue, where it's coming from...

**Comment by paulstelzer** [comment]
Show your code. In my case I added `mode="somestring"` and so this happened :D

**Comment by doncabron** [comment]
I literally figured it out a minute ago! Yeah [mode] was the culprit indeed ;)
