### ISSUE TITLE
[4.0.0-beta.19] Page with tabs opened from tab destroying outlet

### ISSUE THREAD

**Issue by amitairos** [ionic-team/ionic#16765]
# Bug Report

**Ionic version:**
4.0.0-beta.19

**Current behavior:**
I have a tab based app.
Inside it I open, upon clicking a button, another page that contains tabs. Everything works fine before I open it, and inside that page it works fine. The problem is when I navigate from that page back to the main app, navigation in the app stops working. In console: `router-outlet destroyed`

**Expected behavior:**
Navigation should not stop working

**Steps to reproduce:**
See behavior and code

**Related code:**
Main tabs:
```
<ion-tabs #tabs>
  <ion-tab-bar slot="bottom" color="secondary" selected-tab="home">
    <ion-tab-button tab="home">
      <ion-icon name="home"></ion-icon>
      <ion-label>home</ion-label>
    </ion-tab-button>
    <ion-tab-button tab="search">
      <ion-icon name="search"></ion-icon>
      <ion-label>search</ion-label>
    </ion-tab-button>
    <ion-tab-button tab="library" >
      <ion-icon src="/assets/ic_books.svg"></ion-icon>
      <ion-label>library</ion-label>
    </ion-tab-button>
  </ion-tab-bar>
</ion-tabs>
```

Page with tabs:
```
  <ion-tabs>
    <ion-tab-bar slot="top" color="primary">
      <ion-tab-button tab="tab1">
        <ion-label>tab1</ion-label>
      </ion-tab-button>
      <ion-tab-button tab="tab2">
        <ion-label>tab2</ion-label>
      </ion-tab-button>
    </ion-tab-bar>
</ion-tabs>
```

Routers:

```
const routes: Routes = [
  {
    path: 'tabs',
    component: TabsPage,
    children: [
      {
        path: 'home',
        children: [
          {
            path: '',
            loadChildren: '../home/home.module#HomePageModule'
          },
        ]
      },
      {
        path: 'library',
        children: [
          {
            path: '',
            loadChildren: '../library/library.module#LibraryPageModule'
          },
        ]

      },
  {
    path: '',
    redirectTo: '/tabs/home',
    pathMatch: 'full'
  },
  {
    //This is the page with the tabs:
    path: 'kitzur',
    component: KitzurSubjectsPage,
    children: [
      {
        path: ':chelek',
        children: [
          {
            path: '',
            loadChildren: '../kitzur/kitzur-tab/kitzur-tab.module#KitzurTabPageModule'
          }
        ]
      },
      {
        path: '',
        redirectTo: '/kitzur/Chol',
        pathMatch: 'full',
      },
    ]
  },
];
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by paulstelzer** [comment]
Thanks for your issue! I believe you have the same issue described here -> #16411 (see the gif if this is the same problem for you). There I have a workaround to make it work -> https://github.com/ionic-team/ionic/issues/16411#issuecomment-443186868

**Comment by amitairos** [comment]
@paulstelzer I'm not sure if it's the same issue. I tried removing ```  <ion-router-outlet></ion-router-outlet>``` from app.component.html, but now everything is blank... Did I misunderstand the workaround?

**Comment by paulstelzer** [comment]
Same issue is if you cannot switch the pages anymore. Tapping on the link the page stays the same. If you have this issue, then it's the same.

**Comment by amitairos** [comment]
@paulstelzer I tried what you did, and in ```app.component.html``` instead of:
```
<ion-app>
  <ion-router-outlet></ion-router-outlet>
</ion-app>
```
I put:
```
<router-outlet></router-outlet>
```

It indeed solves the problem.
1. Is this OK and won't result in performance issues? Should I use ```ion-router-outlet```?
2. Why isn't this a bug? I think there should be some official guidance when people try similar navigation.

**Comment by paulstelzer** [comment]
@amitairos of course it's a bug :D it's the reason why I opened #16411 . This is just a workaround until the bug is fixed

btw, router-outlet is from Angular and is not using the stack functionality. So in performance it's better than the Ionic outlet

**Comment by amitairos** [comment]
@paulstelzer I see. Thanks. Then why not use router-outlet always?

**Comment by paulstelzer** [comment]
It's depend on you. ion-router-outlet brings you the stack functionality and animations between page transitions ;)
