### ISSUE TITLE
[v4-beta.19] routerLink doesn't work if use in a component

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#16779]
# Bug Report

**Ionic version:**
[x] Ionic Angular v4-beta.19

**Current behavior:**
For navigating purpose, `[routerLink]` works fine if use in a page but doesn't if use in a component. 

For example:

```
<ion-button routerLink="/subpage">Navigate from page</ion-button>
```

Works fine if use in a page but doesn't if use in a component

**Expected behavior:**
Being able to use the directive/attribute `[routerLink]` in component too

**Related code:**

https://github.com/peterpeterparker/test-routing

respectively:

OK: https://github.com/peterpeterparker/test-routing/blob/master/src/app/home/home.page.html
NOT OK: https://github.com/peterpeterparker/test-routing/blob/master/src/app/my-component/my-component.component.html

**PS**

Maybe I should describe what I mean with "doesn't work". With doesn't work I mean that if you click on the button just nothing happens, no navigation, nothing happens

**Comment by paulstelzer** [comment]
I really hope you have the same issue like me #16411 - This is fixed in #16774

I let it open here, so please check in next beta if this is fixed for you, too (It should^^)

**Comment by peterpeterparker** [comment]
@paulstelzer thx for the feedback, might be, I'll check

**Comment by paulstelzer** [comment]
I checked your repo and you want to use routerLink and did not add RouterModule. If you add it to my-component.module.ts, everything is working ;)

**Comment by peterpeterparker** [comment]
@paulstelzer fck me. Sorry Paul and thx a lot for your time, of course you are fully correct, that solves the issue
