### ISSUE TITLE
[4.0.0-beta.19] side menu hidden when navigate between modules

### ISSUE THREAD

**Issue by maximelefort** [ionic-team/ionic#16783]
**Ionic version:**
[x] **4.0.0-beta.19**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
Side menu disappear when I navigate between 2 pages with side menu who contains 2 subpages each.

**Expected behavior:**
Side menu shouldn't disappear when I navigate between pages.

**Steps to reproduce:**
Use this public repo : https://github.com/maximelefort/routeBetweenModulesWithSideMenu
step 1 :
`ng serve`
You should be at this url http://localhost:4200/a/a1

step 2 :
click on "goto B1 (absolute path)"
You should be at this new url http://localhost:4200/b/b1

step 3 :
click on "goto A1 (absolute path)"
You should be back at http://localhost:4200/a/a1
**but the side menu is hidden**

**Related code:**
A sample is available at : https://github.com/maximelefort/routeBetweenModulesWithSideMenu

**Other information:**
none

**Ionic info:** 
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.19
   @angular-devkit/build-angular : 0.11.3
   @angular-devkit/schematics    : 7.1.3
   @angular/cli                  : 7.1.3
   @ionic/angular-toolkit        : 1.2.0

System:

   NodeJS : v10.13.0 (/usr/local/bin/node)
   npm    : 6.5.0
   OS     : macOS Mojave

**Comment by paulstelzer** [comment]
Thanks for your issue! I will take a look at it
