### ISSUE TITLE
Ionic 4 Official Tabs with Side Menu Starter, i.e. PWA

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic#16794]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

It would be nice to have an official Ionic Starter that shows a side menu
with tabs, and provides best practice guidance for PWA setup in Angular.

**Describe Preferred Solution**

A basic starter that demonstrates the recommended solution for
side menu/tabs/PWA.

It could be further developed to demonstrate React, Vue, Stencil integration.

**Describe Alternatives**

**Related Code**

https://github.com/peterennis/aetabs

**Additional Context**

Ref: https://github.com/ionic-team/ionic/issues/16793

**Comment by manucorporat** [comment]
We are currently working to improve our starters and provide more!

**Comment by peterennis** [comment]
Thanks!
