### ISSUE TITLE
[4.0.0-beta.19] feature tab no router removed after 4.0.0-beta.17

### ISSUE THREAD

**Issue by goelectricstations** [ionic-team/ionic#16795]
Ionic:

   ionic (Ionic CLI)             : 4.5.0 
   Ionic Framework               : @ionic/angular 4.0.0-beta.19
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 1.2.1, (and 12 other plugins)

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.3.0-next.0
   OS     : Windows 10

HTML
  <ion-tabs tabbarLayout="icon-end" useRouter="false">
    <ion-tab-bar slot="top">
      <ion-tab-button tab="tabListSaved" disabled="true" class="tabListSaved">
        <ion-icon name="list"></ion-icon>
        <ion-badge color="danger" id="badgeSavedItinerary">{{dataItineraryUser.itinerariesSaved.length}}</ion-badge>
        <ion-label>{{dict.itinerary_savedItinerary.toUpperCase()}}</ion-label>
      </ion-tab-button>
      <ion-tab-button tab="guideItinerary">
        <ion-icon name="information"></ion-icon>
        <ion-label>{{dict.menu_guida.toUpperCase()}}</ion-label>
      </ion-tab-button>
    </ion-tab-bar>

    <ion-tab tab="tabListSaved">
        <ion-nav id="savedItineraries"></ion-nav>
    </ion-tab>
    <ion-tab tab="guideItinerary">
        <ion-nav id="guideItinerary"></ion-nav>
    </ion-tab>
    
  </ion-tabs>

Uncaught Error: Template parse errors:
'ion-tab' is not a known element:
1. If 'ion-tab' is an Angular component, then verify that it is part of this module.
2. If 'ion-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    </ion-tab-bar>

Is a bug? If is not a bug what is the replacement?

**Comment by paulstelzer** [comment]
Thanks! But this is not a feature request :(

Please use this and fill out like stated in this file -> https://github.com/ionic-team/ionic/issues/new?template=feature_request.md
