### ISSUE TITLE
[4.0.0-beta.19][iOS] Keyboard overlays ion-input but not input elements

### ISSUE THREAD

**Issue by sneko** [ionic-team/ionic#16797]
Hi everyone,

I got a problem with previous Ionic releases but that's still present in the beta.19. I use Ionic inside my Capacitor project and get my keyboard overlaying focused elements that are at the bottom of my page. I get different cases:

- if I use a ion-input inside a ion-content, the keyboard will overlay
- if I use a ion-input WITHOUT ion-content, the webview scrolls to the focused ion-input so that it is visible
- if I use a input inside a ion-content, the web view scrolls to the focused ion-input so that it is visible

I'm a bit lost about how to manage that :/ does anyone have already experienced that on iOS?

Thank you,

**Comment by tomfebry** [comment]
Are you using an ion-footer on that page?  Could you copy in the HTML? Can't say I have experienced this problem

**Comment by sneko** [comment]
I'm just using a basic:
```
  ion-app
    ion-content
      br
      br
      br
      br
      br
      br
      br
      br
      br
      br
      br
      br
      br
      br
      br
      br
      br
      br
      br
      br
      br
      br


      span aaaaa
      ion-input(type="text" placeholder="here")
      br
      br
      br
      br
      br

      span bbbbb
```

Note that I think in the first case I described, the webview is probably not pushing the content with the right padding so that's why it's still hidden.

That's funny because sometimes I get the problem of the wrong offset to click on elements (https://github.com/ionic-team/capacitor/issues/814). That means that I need to click around 200px above the input to click it and make it focused, and by doing so the content is pushed up and the keyboard is not overlaying the input.

So strange... I'm not able to determine the origin of the problem :( I hope someone could help on it

**Comment by paulstelzer** [comment]
This could be fixed #17043 . Could you please check after rc.2 release if this problem still occurs?

**Comment by sneko** [comment]
@paulstelzer I will, thank you

**Comment by EricKit** [comment]
I still have the same issue on rc.2

**Comment by paulstelzer** [comment]
@EricKit Did you have test it with normal input? Did it workt there? This is important because otherwise we cannot say if this is Ionic or the cordova keyboard plugin

**Comment by EricKit** [comment]
@paulstelzer Here is the code I'm using: 

```
<ion-header>
  <ion-toolbar color="primary">
    <ion-buttons slot="start"> <ion-back-button defaultHref="/tabs/account/"></ion-back-button> </ion-buttons>
    <ion-title><img src="assets/wp-toolbar.png"/></ion-title>
  </ion-toolbar>
</ion-header>

<ion-content padding>
  <ion-card>
    <ion-card-header> New Password </ion-card-header>
    <ion-card-content> Change the password for {{ username }}. </ion-card-content>
  </ion-card>
  <form [formGroup]="changePasswordForm" (ngSubmit)="changePassword()">
    <ion-item no-padding margin>
      <ion-label position="stacked">Current Password</ion-label>
      <ion-input
        formControlName="oldPassword"
        type="password"
        (keyup.enter)="changePasswordForm.valid && changePassword()"
      ></ion-input>
    </ion-item>
    <ion-item no-padding margin>
      <ion-label position="stacked">New Password</ion-label>
      <ion-input
        formControlName="password"
        type="password"
        (keyup.enter)="changePasswordForm.valid && changePassword()"
      ></ion-input>
    </ion-item>
    <ion-item no-padding margin>
      <ion-label position="stacked">Confirm New Password</ion-label>
      <ion-input
        formControlName="confirmPassword"
        type="password"
        (keyup.enter)="changePasswordForm.valid && changePassword()"
      ></ion-input>
    </ion-item>
    <ion-button type="submit" [disabled]="!changePasswordForm.valid" margin>Reset</ion-button>
  </form>
</ion-content>
```

Here is a screenshot with that code:

![img_0958](https://user-images.githubusercontent.com/4143477/51427361-38fb2080-1bc5-11e9-9ece-50c4bac5d1b2.jpg)

Here is simply removing ion-content (It's cropped below the top of the keyboard). It pushes the content up correctly and the right amount:

![img_0955](https://user-images.githubusercontent.com/4143477/51427369-3ef10180-1bc5-11e9-87de-a1d4bdca4b67.jpg)

Here is changing ion-input to input, I took two, one before the keyboard and one after (it pushes it up further):

![img_0957](https://user-images.githubusercontent.com/4143477/51427373-43b5b580-1bc5-11e9-97d3-9c345e4eecb8.jpg)
and after
![img_0956](https://user-images.githubusercontent.com/4143477/51427375-47e1d300-1bc5-11e9-9866-33dd0aa5a351.jpg)

**Comment by paulstelzer** [comment]
@EricKit I could not see if something is wrong. for me everything looks good - keyboard not hides the input :)

**Comment by EricKit** [comment]
@paulstelzer The keyboard is hidden in the first screen shot (Focus is in the one below the keyboard). When clicking on it, it does not move up at all. If I remove ion-content or change ion-input to input, it moves up (differently in each case).

**Comment by paulstelzer** [comment]
Do you use a new iPhone? because there is so much space on the bottom (the gray at the bottom). If this would be smaller everything would be okay. The question is: Is it Ionic or is it cordova keyboard plugin

 @jcesarmobile do you have an idea?

**Comment by EricKit** [comment]
@paulstelzer Yes it's one with a notch (XS). I've attempted adding multiple inputs below the 3rd one to click on something at the very bottom of the page (so the size of the screen or keyboard would not be a factor). Same result. It does not attempt to move up at all when the focus is placed on the input.

**Comment by EricKit** [comment]
I'm using Capacitor and Ionic Native. When I sync I only use 3 Cordova plugins.

```
  Found 3 Cordova plugins for ios
    ComSarriaromanPhotoviewer (1.2.0)
    CordovaSqliteStorage (2.6.0)
    Cordova.plugins.diagnostic (4.0.10)
```

 Here is my info:

```
Ionic:

   ionic (Ionic CLI)             : 4.8.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.2
   @angular-devkit/build-angular : 0.12.2
   @angular-devkit/schematics    : 7.2.2
   @angular/cli                  : 7.2.2
   @ionic/angular-toolkit        : 1.2.2

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.13
   @capacitor/core           : 1.0.0-beta.13

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   ios-deploy : 2.0.0
   ios-sim    : 7.0.0
   NodeJS     : v11.6.0 (/usr/local/bin/node)
   npm        : 6.5.0-next.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61
```

**Comment by paulstelzer** [comment]
I think you should mention that :D Then it will be a issue of capacitor

**Comment by EricKit** [comment]
@paulstelzer I thought it was independent of Capacitor since it happened to the original post with Cordova, me with Capacitor. Now I have verified it's the same with Safari on an iPhone. If I post my site and remove ion-content or change ion-input to input, it moves for the keyboard. Otherwise it does not. This is with Safari on an iPhone not through an app.

**Comment by paulstelzer** [comment]
@EricKit I have checked in my app (native ios, native android - both created with cordova - and pwa in safari browser) and input will not be hidden by keyboard.

So it can be three reasons: it's an issue with cordova keyboard / capacitor or happens random (means sometimes it works, sometimes not). So it's hard to find this issue.

**Comment by EricKit** [comment]
@paulstelzer thanks for the update and information. Here is how I can reproduce it if it helps, hopefully it's the same for everyone:

```
npm install -g ionic@latest
ionic start updateApp blank --type=angular
cd updateApp
ionic cap add ios
```

Modify home.page.html to read:

```
<ion-header>
  <ion-toolbar> <ion-title> Ionic Blank </ion-title> </ion-toolbar>
</ion-header>

<ion-content padding>
  <br /><br /><br /><br /><br /><br /><br /><br />
  <br /><br /><br /><br /><br /><br /><br /><br />
  <br /><br /><br /><br /><br /><br /><br />
  <form>
    <ion-item><ion-input type="text"></ion-input></ion-item>
    <input />
  </form>
</ion-content>
```

`ionic build && ionic cap sync`

Run on an iPhone from Xcode and click on each input. One will raise the input into view, one will not. It works in the simulator or on an iPhone.

**Comment by sneko** [comment]
Same for me, the rc.2 update did not solve the issue I described (looks the same than the @EricKit 's one)

**Comment by EricKit** [comment]
Here is some more data. When the normal input is clicked a style is set on ion-content which is --keyboard-offset: 290px;
When I click on ion-input, it is 0px. So I attempted to follow the code in Ionic in the Safari debugger on the phone. The ion-input is all properly running in input-shims.ts and scroll-assist.ts to include when I click on it, the clone is made, then it attempts to scroll. When it attempts to scroll, no scroll occurs. I took a screen shot of the local environment at that time.

<img width="985" alt="screen shot 2019-01-21 at 17 49 19" src="https://user-images.githubusercontent.com/4143477/51507867-cb5b1a00-1da7-11e9-8f70-98fcf25aa0ba.png">

**Comment by paulstelzer** [comment]
I just wonder why it's working perfect on my iPad (iOS 12.1). The scrolling works without hiding an input. Maybe a browser issue in older versions?

If there is a notch, maybe the 290px keyboard offset are not enough?

**Comment by sneko** [comment]
@paulstelzer I'm also experiencing this issue on iOS 12.1.2

**Comment by paulstelzer** [comment]
@sneko - yes, but what a device - with or without a notch?

**Comment by sneko** [comment]
@paulstelzer no notch, I have the iPhone 6

**Comment by paulstelzer** [comment]
I invited @manucorporat to this issue, he knows more about the code :)

**Comment by sneko** [comment]
@manucorporat don't you think this issue could be related to the merged PR https://github.com/ionic-team/capacitor/pull/1119 ?

The PR solves Keyboard issue on native Capacitor projects, but since me and @EricKit also have this issue in browsers, maybe it was more relative to Ionic no?

Thanks,

**Comment by EricKit** [comment]
Upgrading to Ionic 4.0 and Capacitor Beta 17 fixed my issue. There is a black background behind the keyboard now when it's going up, but at least it moves the text up.

**Comment by sneko** [comment]
@EricKit oh I never saw new Capacitor versions since they were not tagged as "latest release":
![image](https://user-images.githubusercontent.com/8195958/51791807-3a21e400-21a9-11e9-86d2-879d461fce6a.png)

I will try to upgrade tonight, thanks for the information Eric 👍

**Comment by sneko** [comment]
Just to confirm that the Capacitor beta.17 helped with https://github.com/ionic-team/capacitor/pull/1119 to start solving this issue on native projects.

But inside the mobile browser on iOS, the issue persists even with Ionic 4.0 😢

**Comment by EricKit** [comment]
@sneko that is the case. I didn't test the browser assuming it was fixed until your comment. Still an issue.

**Comment by jesperbjerke** [comment]
We still have the issue running iOS emulator, with latest ionic and capacitor

**Comment by gnanasuriyan** [comment]
Seems, when I focus on ion-text the internal text element is not getting focused but it looks fine in ion-textarea.

**Comment by gnanasuriyan** [comment]
This is how I resolved this issue.

1. I have added ionic keyboard plugin
2. In config.xml i have set KeyboardResizeMode as ionic
`<preference name="KeyboardResizeMode" value="ionic" />`

That solved all the issues expect textarea. So I hacked like this 
`initializeApp() {
    this.platform.ready().then(() => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();
      if (this.platform.is('ios')) {
        window.addEventListener('keyboardDidShow', () => {
          setTimeout(() => {
              const activeEle: any = document.activeElement;
              if (activeEle.type === 'textarea') {
                activeEle.scrollIntoView();
              }
          }, 200);
        });
      }
      this.keyboard.hideFormAccessoryBar(false);
    });
  }`

Please share any better solution for this issue.
