### ISSUE TITLE
Integration of ion-tab in @ionic/angular to display custom content without using routes

### ISSUE THREAD

**Issue by goelectricstations** [ionic-team/ionic#16796]
# Feature Request

**Ionic version:**
[x] **4.0.0**

**Describe the Feature Request**
Please include reinclude ion-tab removed in 4.0.0 beta 18 in order to use with useRouter="false"

**Describe Preferred Solution**
ion-tab to display the content when useRouter="false" for example: 

    <ion-tab tab="test" active="true">
        <ion-nav id="test"></ion-nav>
    </ion-tab>

**Describe Alternatives**
I do not have alternatives

**Related Code**

      <ion-tab-button tab="test">
        <ion-icon name="add"></ion-icon>
        <ion-label</ion-label>
      </ion-tab-button>

    <ion-tab tab="test" active="true">
        <ion-nav id="test"></ion-nav>
    </ion-tab>

**Comment by goelectricstations** [comment]
@paulstelzer I hope now is correct.

**Comment by paulstelzer** [comment]
Perfect :) But i cannot promise you if this will be integrated

**Comment by manucorporat** [comment]
You can use `ion-tab-bar` as a standalone component, you don't need tabs in order to implement your own "tabs" solution, that does not use routing!!

**Comment by manucorporat** [comment]
We will extend the docs to explain how this is possible!

**Comment by goelectricstations** [comment]
@manucorporat the latest docs is still wrong I would like to see the changes thanks so mutch

https://beta.ionicframework.com/docs/api/tabs

**Comment by paulstelzer** [comment]
I talked with @manucorporat about this and the solution is very simple. Just use the ion-tab-bar

```
  <div class="my-tabs">
    <div class="my-tabs-inner">
      <ng-container *ngIf="tab === 'calendar'">
        Your calendar content
      </ng-container>

      <ng-container *ngIf="tab === 'speakers'">
        Your speakers content
      </ng-container>

      <ng-container *ngIf="tab === 'map'">
        Your map content
      </ng-container>
    </div>

    <ion-tab-bar slot="bottom">
      <ion-tab-button (click)="show('calendar')">
        <ion-icon name="calendar"></ion-icon>
        <ion-label>Schedule</ion-label>
        <ion-badge>6</ion-badge>
      </ion-tab-button>

      <ion-tab-button (click)="show('speakers')">
        <ion-icon name="contacts"></ion-icon>
        <ion-label>Speakers</ion-label>
      </ion-tab-button>

      <ion-tab-button (click)="show('map')">
        <ion-icon name="map"></ion-icon>
        <ion-label>Map</ion-label>
      </ion-tab-button>
    </ion-tab-bar>

  </div>
```

And inside your ts:

```
  tab = 'calendar';

  show(tab) {
    this.tab = tab;
  }
```

![chrome_2018-12-20_18-59-29](https://user-images.githubusercontent.com/20501666/50302235-c6920600-0489-11e9-9648-30823eaaef34.jpg)

**Comment by goelectricstations** [comment]
@paulstelzer thank you so mutch, This should be a typical use case for me and should be possible because i set useRouter="false"  in order to call tab content without router. I was able to make it works without work around from ionic 3.x.x to ionic 4.0.0 beta 17, after beta 18 no anymore.

However I used your code but I get the error below, how is possible that you do not get this error?
Missing "tab" property in <ion-tab-button>

I am using the latest version 4.0.0-rc.0

**Comment by goelectricstations** [comment]
@paulstelzer in my case the docs confuse me, I use angular but I will like to use:

  <ion-tab tab="home">Home Content</ion-tab>
  <ion-tab tab="settings">Settings Content</ion-tab>

WIth that was so easy before 4.0.0 beta 18

**Comment by goelectricstations** [comment]
@paulstelzer  any news?

**Comment by paulstelzer** [comment]
I presented you a working solution -> https://github.com/ionic-team/ionic/issues/16796#issuecomment-449085001

A fix can be made to ion-tab-bar to reduce the css boilerplate. And related to tabs see this comment https://github.com/ionic-team/ionic/issues/16267#issuecomment-450417435

**Comment by goelectricstations** [comment]
@paulstelzer  does not work because an error come up: 

Missing "tab" property in ion-tab-button

**Comment by paulstelzer** [comment]
That must be just a warning and the app should work without problems. This log will be removed soon

**Comment by goelectricstations** [comment]
@paulstelzer I just want to say thank you for all including the example now is working perfect, v4 rc1
