### ISSUE TITLE
ion-checkbox: Add custom stroke-width

### ISSUE THREAD

**Issue by kalicki** [ionic-team/ionic#16803]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

I think it interesting to edit the `stroke-width` on class `.checkbox-icon path` (ion-checkbox) this is good in situations of customization of the theme.
![checkbox](https://user-images.githubusercontent.com/3674885/50177478-3b7a0a00-02e9-11e9-88d6-1a27bece2c88.png)

**Describe Preferred Solution**

```
# variable on css
stroke-width: --stroke-width;
```

**Comment by manucorporat** [comment]
Hey, @kalicki would you be up to submit a PR? I can assist you if you need any help

**Comment by alexarvanitidisalpha** [comment]
@manucorporat I have a PR ready for this. Can you give me rights on the repo to create it?

**Comment by alexarvanitidisalpha** [comment]
@manucorporat I created a PR to fix this issue https://github.com/ionic-team/ionic/pull/19933

**Comment by liamdebeasi** [comment]
This has been resolved via https://github.com/ionic-team/ionic/pull/19933 and will be available in an upcoming release of Ionic Framework.
