### ISSUE TITLE
[4.0.0-beta.19] Ion-select Action sheet height

### ISSUE THREAD

**Issue by amitairos** [ionic-team/ionic#16801]
# Bug Report

**Ionic version:**
4.0.0-beta.19

**Current behavior:**
When I have many items in an ```ion-select``` and I display it in an action-sheet, the height overflows the top of the screen, and scrolling is disabled.

Example: 

![image](https://user-images.githubusercontent.com/19995393/50171433-1c847380-02fb-11e9-9f25-64f3a8d37885.png)
It shows the second half of the items, and the first is cut off, without being able to scroll,

**Expected behavior:**
Height should be normal, like in previous versions

**Steps to reproduce:**
See explanation

**Related code:**

```
 <ion-select interface="action-sheet" [(ngModel)]="chapterPointer" okText="בחר" cancelText="סגור" (ionChange)="changeChapter($event)">
      <ion-select-option *ngFor="let chapter of chapters; let i = index" [value]="i">{{chapter.Title}}</ion-select-option>
    </ion-select>
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
Thanks for the issue! The height should be fixed in the next release via this PR: https://github.com/ionic-team/ionic/pull/16789

I am looking into some of the issues with the scrolling.
