### ISSUE TITLE
Segment scroll behavior is not working iOS and Desktop 

### ISSUE THREAD

**Issue by DILEEP-YADAV** [ionic-team/ionic#16808]
Hi Team,

Segment scroll behavior is working fine with Android. But same code base is not working with iOS and Desktop version. 

Android : 
![asag](https://user-images.githubusercontent.com/8583769/50196653-f649ec80-0369-11e9-85a4-2bcd7813d29a.PNG)

iOS :   Scroll working but button is not looking good. like ios
![sag](https://user-images.githubusercontent.com/8583769/50196680-18436f00-036a-11e9-9f1a-cb21f6777d13.PNG)

Desktop :   Scroll is not working . after adding more and more button. 

![desag](https://user-images.githubusercontent.com/8583769/50196692-25f8f480-036a-11e9-9dc5-2700be43a1e0.PNG)

Thanks
DILEEP YADAV

**Comment by manucorporat** [comment]
I don’t think iOS has the concept of scrollable segment.
cc @brandyscarney

**Comment by manucorporat** [comment]
well, you can have the same codebase, but iOS and MD are different design system, you have to make adjustments, otherwise it might look "weird", but you can do whatever you want.

The concepts are not 1-to-1 between iOS and MD, it's a engineering thing, it's a design issue.

**Comment by DILEEP-YADAV** [comment]
Thanks, @manucorporat

**Comment by brandyscarney** [comment]
Thanks for the issue! This is actually a rather simple fix in iOS, you just need to add a `min-width` to the button:

```
ion-segment-button {
  min-width: 70px;
}
```

This is something we could probably add, but I'd have to look into the iOS design more to see what they would use as a min-width. However, what Manu was trying to say is that the application should be designed for the device it's running on, iOS design guidelines for segment state:

> Limit the number of segments to improve usability. Wider segments are easier to tap. On iPhone, a segmented control should have **five or fewer** segments.

https://developer.apple.com/design/human-interface-guidelines/ios/controls/segmented-controls/

If you want to use more than five segments that is entirely up to you, of course. 🙂 

I'm concerned by this though: 

> Desktop : Scroll is not working . after adding more and more button.

At what point does the scroll stop working? Or is it not working at all? If the latter, could you please provide the markup or a way for us to reproduce this. Make sure you have the `scrollable` property added to the `ion-segment`. Thanks!

Here is a Codepen example of it working with `min-width` added: https://codepen.io/brandyscarney/pen/maOabQ?editors=1100&ionic:mode=ios

**Comment by DILEEP-YADAV** [comment]
ion-segment mode="md" is not work with 4.x

**Comment by DILEEP-YADAV** [comment]
Thanks @brandyscarney
