### ISSUE TITLE
Disabled ion-checkbox Tab and Space activated 

### ISSUE THREAD

**Issue by Nick-lab** [ionic-team/ionic#16815]
# Bug Report

**Ionic version:**
#16805 accidentally ran `ionic info` in wrong project console sorry @manucorporat 
[x] **4.x**

**Current behavior:**
ion-checkbox with **disabled attribute** ex `<ion-checkbox disabled></ion-checkbox>` can be Tabbed to and activated with space bar

**Expected behavior:**
ion-checkbox should have no tab index and should not be toggled through space bar

**Steps to reproduce:**
start ionic 4 blank project put ion-checkbox component with disabled attribute and press `Tab` button then `Space Bar` and should get checked.

**Related code:**
`N/A`

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (C:\Users\Brian\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.0.7
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (2 plugins total)

System:

 (C:\Users\Brian\AppData\Local\Android\android-sdk)
   NodeJS            : v9.2.0 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10
```

**Comment by manucorporat** [comment]
Thanks for the issue! I will take a look!
