### ISSUE TITLE
Removing service worker for Cordova builds

### ISSUE THREAD

**Issue by askilondz** [ionic-team/ionic#16827]
# Bug Report

**Ionic version:**

[x] **4.0.0-rc.0**

**Current behavior:**
After adding Angular's service worker with `ng add @angular/pwa` then building a Cordova build (tested on Android only) with the serviceWorker flag in `angular.json`  removed (or set to false) the cordova build still outputs in the console how the service worker failed to install (which it should) but it shouldn't be trying to install the service worker in the first place.

**Expected behavior:**
Setting the serviceWorker field to false or removing it in angular.json should then not include the service worker in Cordova builds. Ideally, would be nice if the cli handles this automatically based on if a pwa or cordova build is being made so we don't even had to switch a boolean between builds.

**Steps to reproduce:**
- Setup an ionic project for Cordova and also ad PWA suppter with `ng add @angular/pwa`
- Build a PWA with `ionic build --prod`
- Build and run a Cordova Android app with `ionic cordova run android --prod`
- In the console log on Android seeing output: 
`"ERROR Error: Uncaught (in promise): TypeError: Failed to register a ServiceWorker: An unknown error occurred when fetching the script.
TypeError: Failed to register a ServiceWorker: An unknown error occurred when fetching the script."`

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.3, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/andrew/workspace/android-sdk)
   ios-deploy        : 1.9.2
   NodeJS            : v10.13.0 (/usr/local/Cellar/node@10/10.13.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by paulstelzer** [comment]
I think you will have a code in your `app.module.ts` that still registers the service worker. I have two branches - one native branch and one PWA branch. the PWA branch ist the master branch btw, so the native branch removes all PWA related stuff. Then I just merge the master into the native branch.

What I wrote is just a workaround, what you describe is a feature request and belongs to the Ionic CLI -> https://github.com/ionic-team/ionic-cli . Please open a feature request over there

So I close this here.

**Comment by askilondz** [comment]
Added it as a feature request and thanks for the workaround tip!
