### ISSUE TITLE
Error: Unable to load app.

### ISSUE THREAD

**Issue by Mobiletainment** [ionic-team/ionic#16828]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

After putting the app into the background and re-opening it, a blank white page appears with the text:
```
Error
Unable to load app.
```

**Expected behavior:**

Re-opening the app displays the last shown page.

**Steps to reproduce:**

* `ionic cordova build ios --prod --release`.
* Deploy to an actual device
* Start the app without any debugger
* Put the app in the background and interact with other apps
* re-open the app

I only got this problem on the prod build without debugging enabled and I can't reliably tell what leads to this issue.

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.3
   @angular-devkit/schematics    : 7.1.3
   @angular/cli                  : 7.1.3
   @ionic/angular-toolkit        : 1.2.1

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.11
   @capacitor/core           : 1.0.0-beta.11

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic 5.2.7, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 8 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 7.0.0
   NodeJS     : v10.12.0 (/usr/local/Cellar/node/10.12.0/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61
```

**Comment by paulstelzer** [comment]
Thanks for your issue! From my point of view it's looking more like an issue with capacitor because I could not verify it (creating apps with cordova). So create an issue over there, I think they will have more information.

https://github.com/ionic-team/capacitor/issues
