### ISSUE TITLE
'Slides' missing from @ionic/angular

### ISSUE THREAD

**Issue by AceLondon** [ionic-team/ionic#16822]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by manucorporat** [comment]
Components has been renamed to match their name in the markup and to be more consistent between Ionic in other frameworks and the docs:
https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#angular-prefixed-ion--components

**Comment by AceLondon** [comment]
@manucorporat Prefixing with "Ion" did the trick. Thanks. 

`import { IonSlides } from "@ionic/angular";`
