### ISSUE TITLE
ion-reorder documentation seems incomplete

### ISSUE THREAD

**Issue by IsaacSomething** [ionic-team/ionic#16839]
# Bug Report

**Ionic version:**
[x] **4.x** documentation 

The documentation for the `ion-reorder` for ionic 4 seems to be incomplete. After the code snippet it ends with "The position of the"

https://beta.ionicframework.com/docs/api/reorder

**Comment by brandyscarney** [comment]
Thanks for the issue! Added a comment for this on the issue here: https://github.com/ionic-team/ionic-docs/issues/160#issuecomment-449421639
