### ISSUE TITLE
Livereload took at least 25sec to appear

### ISSUE THREAD

**Issue by clankiPad** [ionic-team/ionic#16837]
Hi everybody !

# Bug Report

**Ionic version:**
[x] **4.6.0**

**Steps to reproduce:**
`ionic start myApp tabs --type=angular`
Run `ng serve` and do some change in your code to genere a livereload

**Other information:**
The problem is not only on RC

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.0.7
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.1

System:

   NodeJS : v8.4.0 (/usr/local/bin/node)
   npm    : 5.3.0
   OS     : macOS High Sierra
```

**Comment by hiepxanh** [comment]
aw, maybe we can update more detail that developer should use node 10 ✌️

**Comment by clankiPad** [comment]
@abennouna After update to Node.js 10+, livereload is fastest (6sec), but still poor. How many seconds livereload took you?

**Comment by abennouna** [comment]
Well I guess it depends on the machine, I'm on a i5/8GB MBP and for [this project](https://github.com/abennouna/ionic4-rtl-issue), a simple template modification takes 7.5s:
```
[ng] ℹ ｢wdm｣: Compiling...
[ng]
[ng] Date: 2018-12-21T13:48:06.150Z - Hash: f30c6d43bc6045e42824 - Time: 7462ms
[ng] 172 unchanged chunks
[ng] ℹ ｢wdm｣: Compiled successfully.
```

However, a simple .scss change is a bit faster:
```
[ng] ℹ ｢wdm｣: Compiling...
[ng]
[ng] Date: 2018-12-21T13:50:31.532Z - Hash: f30c6d43bc6045e42824 - Time: 4670ms
[ng] 172 unchanged chunks
[ng] ℹ ｢wdm｣: Compiled successfully.
```

**Comment by brandyscarney** [comment]
Thanks for the issue! `ng serve` is an Angular command. 

As of Ionic 4, Ionic no longer ships with custom Angular build tools. This means any build issues you experience should be considered Angular build issues and should be brought up with the Angular team.

- [Angular GitHub Issues](https://github.com/angular/angular/issues)
- [Angular CLI Issues](https://github.com/angular/angular-cli/issues)

I'm going to close this as I do not think it is an Ionic issue. Thanks!
