### ISSUE TITLE
Ionic 4 RC - Huge fab button when routerLink directive is used

### ISSUE THREAD

**Issue by Axdron** [ionic-team/ionic#16833]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
When using the routerLink directive in a fab-button, it became huge in the screen. Without the directive, it's ok.

**Expected behavior:**
I expect the button having the same size with or without the routerLink directive.

**Steps to reproduce:**

**Related code:**
The huge button code:
<ion-fab-button [routerLink]="'/categorias'" color="success">

The normal button code:
  <ion-fab-button (click)='true' color="success">

```
insert short code snippets here
```

**Other information:**
Huge:
![huge](https://user-images.githubusercontent.com/35466619/50285680-1f3eb000-0444-11e9-862e-3d679042f261.PNG)

Normal:
![normal](https://user-images.githubusercontent.com/35466619/50285694-282f8180-0444-11e9-87ba-03dd137621c1.PNG)

**Ionic info:** 
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (C:\Users\APPELSOFT\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : not available

**Comment by eatyourpeas** [comment]
I am getting the same behaviour after changing to RC today

**Comment by eatyourpeas** [comment]
Before:
![screenshot 2018-12-22 at 18 48 18](https://user-images.githubusercontent.com/1058647/50377724-5ff02200-061a-11e9-8565-a935cc5b6850.png)

After:
![screenshot 2018-12-22 at 18 50 28](https://user-images.githubusercontent.com/1058647/50377739-93cb4780-061a-11e9-9614-3d9897ba941c.png)
