### ISSUE TITLE
<ion-router-outlet> is not working in ionic 4

### ISSUE THREAD

**Issue by Ramakrishna1064** [ionic-team/ionic#16831]
# Support Question

Hi i am trying to add two child pages in parent page with two tabs in ionic 4 using below code but i was confused about <ion-router-outlet> not showing admin with two tabs,when i select tabs respective pages have to show but its directly showing child1 page

I wan wondering when i use <router-outlet></router-outlet> its working fine please suggest me some one where did i do wrong? 

 

admin.html
-------

    <ion-content padding>
      <ion-row>
        <ion-col col-4><button ion-button color="secondary" (click)="child1()">Child1</button></ion-col>
        <ion-col col-4><button ion-button color="secondary" (click)="child2()">Child2</button></ion-col>
      </ion-row>
      <ion-router-outlet></ion-router-outlet>
    
    </ion-content> 

admin-router.module.ts
-----

    const routes: Routes = [
        {
            path: 'Admin',
            component: AdminPage,
            children: [
                { path: '',redirectTo: '/Admin/Child1',pathMatch: 'full'},
                { path: 'Child1', component: Child1Page },
                { path: 'Child2', component: Child2Page },
            ]
        }
    ];

adminModule.ts
----

    @NgModule({
        imports: [
            CommonModule,
            IonicModule,
            AdminRoutingModule
        ],
        declarations: [
            AdminPage,
            Child1Page,
            Child2Page
        ]
    })
    export class AdminModule {
    
    }

**Comment by paulstelzer** [comment]
Thanks for your issue! But your code is wrong. You have to make a correct redirectTo, then it will works. But this is a support question, not an issue. So I will close it with this reason!
