### ISSUE TITLE
[4.0.0-rc.0] Opening modal in the documentation causes an error

### ISSUE THREAD

**Issue by ThomasMout** [ionic-team/ionic#16853]
# Bug Report

**Ionic version:**
4.0.0-rc.0

**Current behavior:**
Clicking on the item Frodo Baggins or Sam in the documentation of the modal component causes an error. After the error occurred the examples freeze and the page must be reloaded.
https://beta.ionicframework.com/docs/components/#modal

**Expected behavior:**
Clicking on one of the two items should open a modal.

**Comment by kalicki** [comment]
Similar a this problem: https://github.com/ionic-team/ionic-docs/issues/219
