### ISSUE TITLE
ion segment mode not working after routing to page

### ISSUE THREAD

**Issue by wholzapfel** [ionic-team/ionic#16861]
# Bug Report

**Ionic version:**
[x] "4.0.0-rc.0"

**Current behavior:**
When creating ion-segments with mode="md" when I run the app and I navigate to the page with the ion-segment, the buttons are not shown and working. The text is above each other.

**Expected behavior:**
ion-segments are shown in MD mode.

**Steps to reproduce:**

create a small app, with ion-segments. Load the app and navigate to the page with ion-segments.
It is important to navigate, because when you load the page with ion-segments directly it works as expected.

`<ion-segment mode="md" (ionChange)="segmentChanged($event)">
                <ion-segment-button mode="md" value="first" [checked]="activeSegment === 'first'">
                    First
                </ion-segment-button>
                <ion-segment-button mode="md" value="second" [checked]="activeSegment === 'second'">
                    second
                </ion-segment-button>
            </ion-segment>`

**Comment by bkarv** [comment]
I’m using ion segment and no issues when navigating. I noticed in your code the inner text is not wrapped in  with ion-label. This was a breaking change in 4.0.0-beta.16 see changelog. Not sure if this is the issue but maybe try this first?

<ion-segment-button>
 <ion-label>Item One</ion-label>
</ion-segment-button>
