### ISSUE TITLE
[4.0.0-rc.0] ion-select-option selected not work in dynamic source with ngFor

### ISSUE THREAD

**Issue by polarisGitHub** [ionic-team/ionic#16867]
Ionic Info
Run ionic info from a terminal/cmd prompt and paste the output below.
   ionic (Ionic CLI)             : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

i want to set property 'selected' to first ion-select-option when data changes(loadCategories).but it can not work well, and html tag 'select' and 'option' work well.

    <ion-item class="spacing">
        <ion-label>品牌</ion-label>
        <ion-select #select_brands multiple="true" ok-text="确认" cancel-text="取消"
                    (ionChange)="loadCategories(select_brands.value)">
            <ion-select-option *ngFor="let brand of brands;let i=index;"
                               [value]='brand.code'
                               [selected]="i===0">
                {{brand.name}}/{{brand.code}}
            </ion-select-option>
        </ion-select>
    </ion-item>

    <ion-item class="spacing">
        <ion-label>类别</ion-label>
        <ion-select multiple="true" ok-text="确认" cancel-text="取消">
            <ion-select-option *ngFor="let category of categories;let i=index;"
                               [value]='category.code'
                               [selected]="i===0"
            >
                {{category.name}}
            </ion-select-option>
        </ion-select>
    </ion-item>
![ion-select](https://user-images.githubusercontent.com/9389651/50376643-defd4e80-064a-11e9-8388-d2d5c8ef5aa2.gif)
![select](https://user-images.githubusercontent.com/9389651/50376644-df95e500-064a-11e9-8623-a28ea3538456.gif)

**Comment by manucorporat** [comment]
Duplicated/related with https://github.com/ionic-team/ionic/issues/16453
