### ISSUE TITLE
[4.0.0-rc.0] iOS swipe to go back

### ISSUE THREAD

**Issue by JumBay** [ionic-team/ionic#16864]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Since `beta.18`, we can no longer swipe to go back to the previous page. It opens the menu. It seems it behaves like that when there is a side menu.

**Steps to reproduce:**

1. Start a new project with **sidemenu** starter template.
2. Add a child route/component to the list 
3. Navigate to it
4. Try to go back by swiping to the left.

**Ionic info:** 

```

Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v8.12.0 (/usr/local/bin/node)
   npm    : 6.5.0
   OS     : macOS Mojave
```

**Comment by JumBay** [comment]
Twitter or amazon app for exemple. If you open a tweet or a product and you swipe, you go back. Swiping again opens the menu.

**Comment by manucorporat** [comment]
Alright! I will check it out and implement a fix, thanks for the research work!

**Comment by JumBay** [comment]
Thanks

**Comment by patrickmcd** [comment]
Apps that want to use swipe-to-go-back but retain access to the menu in nested pages usually have both a back arrow and a hamburger on nested pages. I think it's clunky, but it works.

Here's the header on Amazon's root page:
![image](https://user-images.githubusercontent.com/764290/50385014-9d48c400-069b-11e9-884e-6fc498bca54b.png)

And here's one level in where STGB still works:
![image](https://user-images.githubusercontent.com/764290/50385019-a33ea500-069b-11e9-98f6-5ce82b52e04d.png)

**Comment by paulstelzer** [comment]
An Google Play Store always shows the menu on swipe ;)

**Comment by JumBay** [comment]
Yes it depends which device you're using, I forgot to mention, this is about iOS not android
