### ISSUE TITLE
[4.0.0_rc.0] version property is missing from Ionic object

### ISSUE THREAD

**Issue by moose4lord** [ionic-team/ionic#16866]
In Ionic v3 I am able to display the Ionic version number at runtime with this code
```
console.log('Running Ionic v' + (<any>window).Ionic.version);
```
However there doesn't appear to be a 'version' property anymore in Ionic 4. Is there a new/different way to display the version?

**Comment by paulstelzer** [comment]
Thanks for your issue! Can you open a feature request and tell us why you need the ionic version?
