### ISSUE TITLE
[4.0.0-rc.0] onIonRouteWillChange should be cancellable

### ISSUE THREAD

**Issue by JCKodel** [ionic-team/ionic#16870]
# Bug Report

**Ionic version:**

[x] **4.x** 4.0.0-rc.0

**Current behavior:**

I'm trying to implement a navigation guard, cancelling the navigation for a specific route (so I can popup a login page, for example).

The event is cancelled, but the router still navigates.

**Expected behavior:**

When I cancel the `ionRouteWillChange` event, the navigation should be cancelled.

**Steps to reproduce:**

Implement a `onIonRouteWillChange` and call `event.preventDefault()`.

**Related code:**

```
<ion-app>
    <ion-router useHash={true} onIonRouteWillChange={this.onRouteWillChange}>
        <ion-route url="/menu/:menuHash" component="page-menu" />
        <ion-route url="/test" component="page-test" />
    </ion-router>

    <ion-nav main />
</ion-app>
```

```
private onRouteWillChange(e: CustomEvent<RouterEventDetail>)
{
    console.warn("RouteWillChange");
    console.dir(e);

    if(e.detail.to.startsWith("/menu"))
    {
        console.warn("CANCELLING");
        e.preventDefault();
        e.stopImmediatePropagation();
        e.stopPropagation();
        return false;
    }
}
```

Console output:
```
/!\ RouteWillChange (for /)
/!\ RouteWillChange (for /menu/xxxx)
/!\ CANCELLING
```

**Other information:**

**Ionic info:** 

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   ionic (Ionic CLI) : 4.5.0

System:

   NodeJS : v10.13.0
   npm    : 6.4.1
   OS     : Windows 10
```
NOTE: It's a Ionic Core/StencilJS project

**Comment by Silvest89** [comment]
What about using the Ionic nav guards, ionViewCanEnter and ionViewCanLeave

**Comment by Silvest89** [comment]
What about using ionViewCanEnter at the component level?

**Comment by JCKodel** [comment]
> or handling Router Guards, the older ionViewCanEnter and ionViewCanLeave have been replaced with their framework specific equivalent. For Angular, there are Router Guards.

There is no such thing in Ionic Core.

And that's not the issue. The issue is a cancellable event not cancelling anything (the fix is either cancel the navigation or mark the event as non cancellable).

**Comment by manucorporat** [comment]
You can't cancel a URL change, but what you can do is to implement guards in the way of redirects to protect parts of your application.

```tsx
<ion-app>
    <ion-router useHash={true}>
        { this.isLoggedIn && <ion-route-redirect from="/menu*" to="/test" /> }
        <ion-route url="/menu/:menuHash" component="page-menu" />
        <ion-route url="/test" component="page-test" />
    </ion-router>

    <ion-nav main />
</ion-app>
```
