### ISSUE TITLE
[4.0.0-rc.0] Android back button can unexpectedly switch tabs

### ISSUE THREAD

**Issue by qiluo** [ionic-team/ionic#16875]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When you tap on Android back button, it can unexpectedly switch tabs

**Expected behavior:**

On the tabs layout, Android back button should do nothing, since tabs layout is root component already

**Steps to reproduce:**

1. create a new project from tabs starter
2. add platform android
3. run app on Android device
4. randomly tap on any tab to generate a navigation history
5. keep tapping on Android back button, the app just went way back of all its navigation history

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/Dev/Android/android-sdk-macosx)
   ios-deploy        : 1.9.4
   ios-sim           : 6.1.2
   NodeJS            : v10.14.2 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Sierra
   Xcode             : Xcode 9.2 Build version 9C40b
```

**Comment by amitairos** [comment]
I would suggest differentiating between top tabs to bottom tabs. Top tabs should not respond to back button, while bottom tabs should maybe navigate to the home button.

**Comment by qiluo** [comment]
> I would suggest differentiating between top tabs to bottom tabs. Top tabs should not respond to back button, while bottom tabs should maybe navigate to the home button.

In my case, it's bottom tabs. But if you look at native apps, they don't switch either top or bottom tabs by Android back button

**Comment by paulstelzer** [comment]
This is something for #16611
