### ISSUE TITLE
vendor.js: Line 47032 : Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by qdd188** [ionic-team/ionic#16873]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
 Running  basic blank app on android 5.1.1(API 22),throws vendor.js: Line 47032 : Uncaught TypeError: undefined is not a function.

**Expected behavior:**
Android 8.0 is works well.

**Steps to reproduce:**

1. ionic start myApp blank
2. ionic cordova run android -l -c

**Other information:**
vendor.js: Line 47032 : Uncaught TypeError: undefined is not a function

**Ionic info:** 
    "@ionic-native/core": "5.0.0-beta.21",
    "@ionic-native/splash-screen": "5.0.0-beta.21",
    "@ionic-native/status-bar": "5.0.0-beta.21",
    "@ionic/angular": "4.0.0-rc.0",
    "cordova-android": "7.1.4",

**System** 
   npm:6.4.1
   node:v10.14.2

**Comment by paulstelzer** [comment]
Please add repo so we can check.

**Comment by qdd188** [comment]
Perfect
Thank you so much @paulstelzer 
This really helps a lot!
