### ISSUE TITLE
[4.0.0-rc.0][DOC] ion-tab still in doc

### ISSUE THREAD

**Issue by pavillet** [ionic-team/ionic#16871]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

The first exemple still features <ion-tab> on https://beta.ionicframework.com/docs/api/tabs and my understanding is that it has been removed.

While I'm at it, it's unclear to me how to create tabs without using router, we used to have tabs holding the content, I'm not sure how we should do it now.

EDIT : related to https://github.com/ionic-team/ionic/issues/16796 I guess, depending on the status of this one my issue can be closed if not relevant.

<img width="748" alt="capture d ecran 2018-12-24 a 00 13 21" src="https://user-images.githubusercontent.com/22885020/50388262-0ae30780-0711-11e9-8c65-d4bef5db0b4a.png">

**Comment by paulstelzer** [comment]
THere is a difference between `@ionic/core` (used in vanilla javascript projects) and `@ionic/angular`. So ion-tab still exist, but not in Angular. 

There is an information when you want to use it with Angular -> https://beta.ionicframework.com/docs/api/tabs/#angular-router-integration
