### ISSUE TITLE
Horrible ion-infinite-scroll example

### ISSUE THREAD

**Issue by jagomf** [ionic-team/ionic#16874]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
Existing example for `ion-infinite-scroll` is close to the least helpful ever. Using an embedded item that sums up is actually never going to be really helpful. You don't see any relationship at all between the list, how to fill up items in the list, and the infinite-scroll.

**Describe Preferred Solution**
Use a component that gets repeated in the HTML rather than programmatically inlining an increasing number. Something more complete, that actually uses at least an `*ngFor` in the list so that you see what is happening, pretty much like in v3 docs.

**Comment by NG-tylerholden** [comment]
Agreed. v4 docs are horrible guys cmon. I'm also getting infinite scroll has no exported member with angular and I copied exact documentation example.

**Comment by paulstelzer** [comment]
Fixed by #16914

**Comment by paulstelzer** [comment]
Okay, the typing is fixed, the example could be better, you are right ;)
