### ISSUE TITLE
Ionic 4 RC-0 - ion-anchor is showing error

### ISSUE THREAD

**Issue by Manivannandurairaj** [ionic-team/ionic#16889]
# Bug Report

**Ionic version:**

[x] **4.0.0.rc.0**

**Current behavior:**

ion-anchor tag is showing parsing error in ionic v4 release candidate. But, When I import CUSTOM_ELEMENTS_SCHEMA in my signin module, it is working fine.

**Expected behavior:**

ion-anchor tag is work without adding any CUSTOM_ELEMENTS_SCHEMA in my signin module

**Steps to reproduce:**

Implemented ion-anchor tag in my signin page html. Below i have added my code.

**Related code:**

```
<ion-anchor color="primary" routerDirection="forward" href="/forget">Forget your password?</ion-anchor>
```
**Error**
![image](https://user-images.githubusercontent.com/22704944/50451627-2e998e00-095b-11e9-9fab-afca5e03d4a9.png)

**Other information:**

**Ionic info:** 

![image](https://user-images.githubusercontent.com/22704944/50451668-61438680-095b-11e9-8657-435d51923e70.png)

**Comment by manucorporat** [comment]
`<ion-anchor>` is not exported in `@ionic/angular` since a simple `<a>` might have the same effect, what's your use case?

**Comment by contactjavas** [comment]
I also use `ion-anchor`, and my intent is to use Ionic's elements when available than using default HTML element.

But for now (because of this issue), i will use `<a>` instead

**Comment by ffMathy** [comment]
This also happens for 4.0 that was just released.

**Comment by joelcogen** [comment]
The doc isn't clear about it but it seems `ion-anchor` is redundant and the same properties can be applied to an `a` tag.

**Comment by SalehG91** [comment]
Had the same issue, i dont think its provided by Ionic anymore. Just use a regular a tag.
Its confusing because it still exists in the documentation.

**Comment by MarkJAmes1217** [comment]
had the same issue, Any updates ?

**Comment by ziftytodd** [comment]
If it's no longer a support element, it should be removed from the docs.

**Comment by manucorporat** [comment]
@MarkJAmes1217 <ion-anchor> does not make sense in angula land. it's only useful for ionic/core.

```html
<a [routerLink]="/path">Link</a>
```

<ion-anchor> will not be available in `@ionic/angular`, we will update the docs. But it's still a supported component, it is just not available in @ionic/angular
