### ISSUE TITLE
[v4.0.0-rc.0] ion-input type=number can still enter all characters on mobile.

### ISSUE THREAD

**Issue by Silvest89** [ionic-team/ionic#16899]
### Ionic version:
[x] 4.0.0-rc.0

### Current behavior:
The ion input with type number still accepts all characters on ios and android. Also there is no arrow up/down shown to increase and decrease number.

### Expected behavior:
Only numbers should be accepted

**Comment by paulstelzer** [comment]
By saying "accepts all characters on ios and android." do you mean in a native app or mobile browser? If it's a native app and you are using cordova-plugin-ionic-keyboard, then you should mention it here -> https://github.com/ionic-team/cordova-plugin-ionic-keyboard

**Comment by bkarv** [comment]
For me it is in the web browser ie PWA

**Comment by paulstelzer** [comment]
I cannot confirm this:

![screenshot_20190103-100201](https://user-images.githubusercontent.com/20501666/50585498-94af7500-0e75-11e9-9487-fa8ddb0b7c58.png)

**Comment by bkarv** [comment]
This is a screenshot on iPhone X. As you can see all characters are allowed for the input set to number. So are you saying this is a Cordova issue not ionic?

![0c3b3361-f167-48a6-bb2f-4825286d4270](https://user-images.githubusercontent.com/10624315/50612457-3abeb600-0f2e-11e9-88e7-9d57a2f5f8ea.jpeg)

**Comment by paulstelzer** [comment]
This is neither a cordova issue nor an Ionic issue, it's an iOS issue ;)

Check https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number -> If you see there a numpad on iPhone, then it's an ionic issue

**Comment by bkarv** [comment]
@paulstelzer do you mind confirming in a normal desktop PWA browser (ie Chrome) when type="number", non-numbers entries are locked from being entered like in the demo app in:

[Beta Input Api](https://beta.ionicframework.com/docs/api/input/) 

I've tried the following code and both still allows non-integers to be entered unlike the demo in link above.

```
<ion-item>
                    <ion-label position="stacked">
                      Default - Expiry Reminder (days)                      
                    </ion-label>  
                    <ion-input type="number"  placeholder="Reminder in days" [(ngModel)]="record.default_expiry_reminder"></ion-input>                                 
                  </ion-item>
```
```
<ion-item>
                      <ion-label position="stacked">
                        Default - Qualification Due Reminder (days)
                      </ion-label>     
                      <ion-input type="number" min="0" inputmode="numeric" pattern="[0-9]*" title="Non-negative integral number" placeholder="Reminder in days" [(ngModel)]="record.default_due_reminder"></ion-input>                 
                    </ion-item>
```

**Comment by paulstelzer** [comment]
What do you want to say? It depends on the browser if you can enter non-numbers in an input with type number (e.g. in Firefox):

![Uploading firefox_2019-01-04_17-11-12.jpg…]()

This is a normal input field with type number (not ion-input)

**Comment by bkarv** [comment]
Thanks I am using Chrome and input allows non-number when type="number". But I can confirm this is occurs with both ion-input and input so it's not an ionic issue. I think at the end of the day to handle all browsers a keypress function to remove non-number is required.
