### ISSUE TITLE
"loading.present is not a function"

### ISSUE THREAD

**Issue by mohitmdn** [ionic-team/ionic#16891]
# Bug Report

**Ionic version:**

[x] **"@ionic/angular": "4.0.0-rc.0",**

**Current behavior:**
Loading spinner is not working. It throw an error "loading.present is not a function"

**Steps to reproduce:**

**Related code:**
import { LoadingController } from '@ionic/angular';
 constructor(private http: HttpClient, public loadingController: LoadingController) {

 }

presentLoadingWithOptions() {
    const loading = this.loadingController.create({
      spinner: null,
      duration: 5000,
      message: 'Please wait...',
      translucent: true,
      cssClass: 'custom-class custom-loading'
    });
    return loading.present();
  }

**Comment by paulstelzer** [comment]
Thanks for your report! please take a look at the documentation -> https://beta.ionicframework.com/docs/api/loading#usage

You have to use async / await (or then) because it's asynchronous

```
async presentLoadingWithOptions() {
const loading = await this.loadingController.create({
spinner: null,
duration: 5000,
message: 'Please wait...',
translucent: true,
cssClass: 'custom-class custom-loading'
});
return loading.present();
}
```
