### ISSUE TITLE
[v4.0.0-rc.0] Ion-router-outlet style issue when used as sub-page

### ISSUE THREAD

**Issue by btsiders** [ionic-team/ionic#16897]
# Bug Report

**Ionic version:**
[x] **4.0.0-rc.0**

**Current behavior:**
`ion-router-outlet` is being forced to fullscreen size even when it is used with a sub-page.

**Expected behavior:**
`ion-router-outlet` should act like `router-outlet`

**Steps to reproduce:**
In the sample application, select the Router-Outlet page from the menu to see how it is laid out, then select the Ion-Router-Outlet page to see its layout. They should be close to the same, but the Ion-Router-Outlet page does not show the page header.

*With `router-outlet`*
![2018-12-27](https://user-images.githubusercontent.com/715672/50485086-c762f480-09c1-11e9-84ff-9c0df76a7fe3.png)

*With `ion-router-outlet`*
![2018-12-27 1](https://user-images.githubusercontent.com/715672/50485087-c762f480-09c1-11e9-9b4d-52588a2eae55.png)

**Related code:**

https://github.com/btsiders/ionic-sub-page

*General Page Layout (swap router-outlet for ion-router-outlet)*
```
<ion-header>
    <ion-toolbar>...</ion-toolbar>
</ion-header>
<ion-content class="ion-router-outlet">
    <ion-card class="header-card">
        Top-level page header of some sort. Normally not a card, but the card is used here for simplicity.
    </ion-card>
    <ion-router-outlet></ion-router-outlet>
</ion-content>
```

**Other information:**
I would use the Angular Router Outlet for the sub-page (and have been up until this point) except for the fact that the root-level router is using the Ionic Router Outlet for styling. Using the Angular one inside of the Ionic one really messes up navigation, especially when using the ion-back-button or the browser's back navigation. If the Ionic Router Outlet could style just like the Angular one when used as a sub-page, everything would be great. Or if the Angular Router Outlet could keep navigation working, that would be great as well.

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (C:\Users\Bryan\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.1

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.5.0
   OS     : Windows 10
```

**Comment by paulstelzer** [comment]
Thanks for your issue! You don't have to use ion-router-outlet, just use router-outlet then. Ion-router-outlet is for pages only, so if you don't want to use it as page, just use router-outlet :)

**Comment by btsiders** [comment]
In an Ionic 4 app, routing is *more* messed up when using the router-outlet for sub-pages than with the ion-router-outlet or I wouldn't even be trying to use ion-router-outlet.

#16923 #16928 #16534 all seem to be related. #16928 is actually trying to do the exact same thing that I am.
