### ISSUE TITLE
ASSERT: can not be animating

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic#16898]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Getting error related to menu swipeGesture

**Related code:** On component mounted I am doing this to disable swipe of of menu because view is having leaflet map and on panning map menu is opening.
```
const menu = document.querySelector("ion-menu-controller");
            menu.swipeGesture(status);
```

**Other information:**
<img width="593" alt="screenshot 2018-12-28 at 12 17 09 pm" src="https://user-images.githubusercontent.com/8480351/50505585-8ee31980-0a9a-11e9-8adf-a4cc16d32298.png">
<img width="317" alt="screenshot 2018-12-28 at 12 15 55 pm" src="https://user-images.githubusercontent.com/8480351/50505586-8ee31980-0a9a-11e9-86fc-28390d714fb0.png">

**Ionic info:** 

```
Ionic rc.0
```

**Comment by paulstelzer** [comment]
Could you add a repo here on Github to check it?
