### ISSUE TITLE
[4.0.0-4c.0] Promise Bug with Virtual Scroll

### ISSUE THREAD

**Issue by oliveirafilipe** [ionic-team/ionic#16890]
# Bug Report

**Ionic version:**

[x] **4.0.0-rc.0**

**Current behavior:**

When following the **Usage** example from [Virtual Scroll Readme](https://github.com/ionic-team/ionic/tree/master/core/src/components/virtual-scroll#usage) the app crash with the following error:
```
ERROR Error: "[object Object]"
	resolvePromise http://localhost:4200/polyfills.js:3159:31
	resolvePromise http://localhost:4200/polyfills.js:3116:17
	scheduleResolveOrReject http://localhost:4200/polyfills.js:3218:17
	invokeTask http://localhost:4200/polyfills.js:2766:17
	onInvokeTask http://localhost:4200/vendor.js:49534:24
	invokeTask http://localhost:4200/polyfills.js:2765:17
	runTask http://localhost:4200/polyfills.js:2533:28
	drainMicroTaskQueue http://localhost:4200/polyfills.js:2940:25
```
**Expected behavior:**

The application shows an virtual list of Cards. Including a picture, name and content

**Steps to reproduce:**

1 - Create a Component just like the Usage example
2 - Implements the `component.ts` and `component.html` just like in the Usage example
3 - Crate a Route to point to that component `  { path: 'home', component: MyComponent },` 
4 - Crash

**Related code:**

[Virtual Scroll Example](https://github.com/ionic-team/ionic/tree/master/core/src/components/virtual-scroll#usage)

**Other information:**

Project created by `ionic ionic start myApp blank --type=angular`
**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v10.14.0 (/usr/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.15

```

**Comment by paulstelzer** [comment]
Thanks for your issue! I tried the example code from https://github.com/ionic-team/ionic/tree/master/core/src/components/virtual-scroll#usage and it's working (maybe you forget something to copy):

![chrome_2019-01-02_10-31-52](https://user-images.githubusercontent.com/20501666/50586436-b4e13300-0e79-11e9-9855-016691f84b89.jpg)
