### ISSUE TITLE
Ionic v4 opening url not working ios 

### ISSUE THREAD

**Issue by alphagamer7** [ionic-team/ionic#16893]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Opens up in-app itself with no close button although code says to open in a safari browser
![image](https://user-images.githubusercontent.com/17358908/50478604-280d2400-09f8-11e9-82d0-dfc4d45b4c27.png)

**Expected behavior:**

Should open in a new safari window
**Steps to reproduce:**

Ionic 4 app, with mentioned code.

**Related code:**

Template --
```
      <a class="ion-home color-primary item" href="#" (click)="openUrl(contactUrl)"> SalesForceOne</a>
```
Ts file --
```
openUrl(url){
    window.open(url, '_blank'); 
}
```

**Other information:**

Even tried with InAppBrowser plugin similar result.
**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)  : 4.4.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   NodeJS : v10.13.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS
   Xcode  : Xcode 10.1 Build version 10B61
```

**Comment by paulstelzer** [comment]
Thanks! But this is not related to Ionic. Is this a native app? Then use Cordova plugin in app browser

Furthermore, you are using ionic-angular 3.9.2, not `@ionic/angular` 4
