### ISSUE TITLE
Platform Specific Styles in the app's config not working in ionic 4

### ISSUE THREAD

**Issue by nrnaveen** [ionic-team/ionic#16896]
Short description of the problem:
From the Platform Specific Styles docs and the Config API docs, I'm trying to force a control to use ios design style for my app, regardless of platform selected. But it does not seem to be working.

imports: [
		BrowserModule,
		IonicModule.forRoot({
			mode: 'ios',
		}),
		AppRoutingModule
	],

**Comment by qiluo** [comment]
You can add it in your root index.html
```
<html mode="ios">

```
however, there's a bug for docs which says `class="ios"`

**Comment by nrnaveen** [comment]
Yes, I already used this attribute. but iOS styles not applied.

**Comment by paulstelzer** [comment]
This should work, are you using Ionic 4? Please add a repo so we can check and please fill out the issue template next time
