### ISSUE TITLE
[Ionic 4 RC.0] cssClass not work for Toast

### ISSUE THREAD

**Issue by qiluo** [ionic-team/ionic#16907]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I want to customise some style of toast, here's my cssClass
```
ion-toast {
  --max-width: 50%;
  --background: lightgray;
}
.my-toast {
    .toast-message {
          text-align: center;
     }
}
```
The max-width and background was successfully changed. However the cssClass style didn't work.

Since v4 components have completely moved to web components and shadow dom, I can understand why max-width and background worked (the component exposes variables), but looks like cssClass is broken.

I'm really confused with how to style components now, it lost flexibility as before

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/Dev/Android/android-sdk-macosx)
   ios-deploy        : 1.9.4
   ios-sim           : 6.1.2
   NodeJS            : v10.14.2 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by paulstelzer** [comment]
Just use 

```
ion-toast.your-css-class {
// Your css code or css custom properties
}
```

**Comment by qiluo** [comment]
@paulstelzer , thanks, but I tried your way, still not work. This time I apply a cssClass to try to change text color of Alert, 
```
ion-alert.my-alert {
    color: red !important;
  }

const alert = await this.alertController.create({
      header: 'Confirm!',
      message: 'Message <strong>text</strong>!!!',
      buttons: [
        {
          text: 'Cancel',
          role: 'cancel',
          cssClass: 'my-alert',
          handler: (blah) => {
            console.log('Confirm Cancel: blah');
          }
        }, {
          text: 'Okay',
          handler: () => {
            console.log('Confirm Okay');
          }
        }
      ]
    });

    await alert.present();
```

I've inspected the button element, the class `my-alert` was applied, but the color was still `var(--ion-color-primary,#3880ff)`, not changed

**Comment by paulstelzer** [comment]
Thanks, but you have to check your code again (in your first issue you asked for toast, now you ask for a cssClass inside button).

You added the cssClass to the button, so it's NOT `ion-alert.my-alert`, instead it's `button.my-alert`:

```
button.my-alert {
    color: red !important;
}
```

Working:

![chrome_2019-01-02_08-56-23](https://user-images.githubusercontent.com/20501666/50583904-48ac0280-0e6c-11e9-97b3-e255fa67ea35.jpg)

**Comment by cre91** [comment]
Same issue for me, how do you css customize components now ?

ion-toast.my_custom_class {
  .toast-wrapper {
      whatever rules (not working!)
  }
}

I'm having the same problem with ion-button, I cant put a justify-content: flex-start; on the button-inner class...

**Comment by paulstelzer** [comment]
Do not use .toast-wrapper this is inside shadow dom and cannot be customized. You have to use  css custom properties (see docs https://beta.ionicframework.com/docs/api/toast#css-custom-properties ) or if it's the host element you can style it with normal css

```
ion-toast.my_custom_class {
      // Css rules or using css custom properties
}
```
