### ISSUE TITLE
Platform compatibility: iOS 10 in docs, iOS 11 in WebView plugin

### ISSUE THREAD

**Issue by kamilbrk** [ionic-team/ionic#16909]
# Bug Report

**Ionic version:**
[x] **1.x**
[x] **2.x**
[x] **3.x**
[x] **4.x**

**Current behavior:**
ionic-webview plugin requires iOS 11, whilst Ionic as a platform claims iOS 10 support

**Expected behavior:**
ionic-webview plugin to revert removal of GCDWebServer and support iOS 10 again
OR
update Ionic (prod) and Ionic (4/beta) requirements documentation to iOS 11 and leave roughly 7% of iOS devices out of support (see link below)

**Steps to reproduce:**
Create an Ionic app using any of the available starter templates and update cordova-plugin-ionic-webview from 2.0.0 (default in templates, but deprecated) to 3.0.0

**Other information:**

I tried forums, Slack and ionic-webview plugin repository to no avail. At first I thought about filing a ticket with plugin repository, but:
1) That's a wider problem that I think Ionic team should to look into.
2) Recent issues about platform compatibility were closed without further discussion.

Please see forum post with more details and links: https://forum.ionicframework.com/t/ionic-webview-plugin-version-compatibility/151218

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/Users/X/.nvm/versions/node/v10.11.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (/Users/X/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.11.0 (/Users/X/.nvm/versions/node/v10.11.0/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.1 Build version 10B6
   None of this matters, but ticket would be marked as invalid otherwise.
```

**Comment by paulstelzer** [comment]
Thanks for your issue! Keep in mind the following: Ionic is not limited to any device nor any iOS Version. Ionic itself is a collection of components and offers features which are nice to have (like the platform service). 

So Ionic 4 is more limited to a browser and what this browser offers for features, but Polyfills help to support older browsers, too.

From my point of view Ionic 4 is runnable in older iOS versions. What limits the use is Cordova / Capacitor and its use of webview. So it's up to you what you use. If you are using cordova-plugin-ionic-webview, so this cordova plugins define which iOS version is supported or not supported.
