### ISSUE TITLE
Ionic 4 DateTime picker does not display am/pm

### ISSUE THREAD

**Issue by samrat-bhandari** [ionic-team/ionic#16912]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

Ionic 4 datetime picker shows three dots (like this: ...) instead of am/pm when using the picker-format="hh mm a". 
Similarly for picker-format="hh mm A" it displays PM correctly but still has the three dots instead of AM

**Expected behavior:**
Should show the text "am/pm" or "AM/PM" instead of "..."

**Steps to reproduce:**
Insert the code presented in the Related code section bellow 

**Related code:**

```
          <ion-datetime
            display-format="hh mm A"
            picker-format="hh mm A"
            [(ngModel)]="timePickerValue"
            (ionChange)="pickerChanged()"
          ></ion-datetime>
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/home/samrat/.nvm/versions/node/v8.11.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   NodeJS : v8.11.3 (/home/samrat/.nvm/versions/node/v8.11.3/bin/node)
   npm    : 5.6.0
   OS     : Linux 4.15
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us. I'm not seeing this issue anymore on v4.0.1. Would you be able to try this again with the latest version of Ionic, and let me know if you are still experiencing this issue?
