### ISSUE TITLE
Change in v4 event handlers

### ISSUE THREAD

**Issue by gregd** [ionic-team/ionic#16924]
# Bug Report

**Ionic version:**

[x] **4.x**

Angular event handlers get CustomEvent object from Ion components. This is a big change compared to Ionic v3. For example: <ion-select "onMyEvent($event)" ...> will trigger onMyEvent method, not with select value as a parameter, but with the CustomEvent object where the selected value is stored in event.detail.value property.

There is no a single word about above change in migration guide so I report this as a bug.

**Comment by paulstelzer** [comment]
Thanks! That is something for #16819 - so it will be added to the breaking changes page

**Comment by paulstelzer** [comment]
BRR! Wanted to add iontron:docs.... @brandyscarney
