### ISSUE TITLE
importing files into variable.scss using ionic 4 issues 

### ISSUE THREAD

**Issue by m7ammad7assan** [ionic-team/ionic#16922]
It cannot find these imports when importing files into variable.scss using ionic 4 issues 
@import “ionic.globals”;
@import “ionic.theme.default”;
@import “ionic.ionicons”;
@import “roboto”;
@import “noto-sans”;

what is the issue or the correct paths !

**Comment by abennouna** [comment]
This does not look like v4, but rather looks like v3.

**Comment by paulstelzer** [comment]
As @abennouna wrote you try to add something from Ionic 3, which of course not exist in v4. Please take a look at the v4 starter packages.

For example this is the default scss import:

// http://ionicframework.com/docs/theming/
@import "~@ionic/angular/css/core.css";
@import "~@ionic/angular/css/normalize.css";
@import "~@ionic/angular/css/structure.css";
@import "~@ionic/angular/css/typography.css";
@import "~@ionic/angular/css/padding.css";
@import "~@ionic/angular/css/float-elements.css";
@import "~@ionic/angular/css/text-alignment.css";
@import "~@ionic/angular/css/text-transformation.css";
@import "~@ionic/angular/css/flex-utils.css";
