### ISSUE TITLE
Firefox angular error message stringified

### ISSUE THREAD

**Issue by pickfire** [ionic-team/ionic#16932]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Error messages is displayed as `ERROR Error: "[object Object]"` which is not expandable, somehow this only happen locally on new ionic 4 project but not on stackblitz ionic 3.

**Expected behavior:**

`ERROR Error: Uncaught (in promise): ReferenceError: _isAuthenticated is not defined...`, at least better than just `"[object Object]"`.

**Steps to reproduce:**

Just randomly break an ionic angular application by just adding `<test>` in html anywhere or do any other things that break at runtime.

**Related code:**

```
<hello></world>
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/local/share/.config/yarn/global/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (/opt/android-sdk)
   NodeJS            : v11.6.0 (/usr/bin/node)
   npm               : 6.5.0
   OS                : Linux 4.19

```

**Comment by paulstelzer** [comment]
Thanks for your issue! This is not Ionic, that's Angular if you add a not known element 

![chrome_2019-01-02_09-01-21](https://user-images.githubusercontent.com/20501666/50584010-fae3ca00-0e6c-11e9-90bd-5cf602eda03c.jpg)

If this is not what you want to say, please add a repo and I will reopen it
