### ISSUE TITLE
Quite slow incremental build performance

### ISSUE THREAD

**Issue by romain10009** [ionic-team/ionic#16937]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Curently it takes about 3-7 seconds (depending on CPU) to see the updated code after you edit one line in an ionic serve. I have a xps15 with a i7 8750H and CPU is fully available to webpack. I guess it is also a big draw on the battery for our mobile fellow devs. 

![image](https://user-images.githubusercontent.com/7512202/50605604-006bff00-0ec3-11e9-9855-1abfb45dc062.png)

**Expected behavior:**
As a developer, it is important to see as close to instant feedback ideally of how stuff looks like, would make the Ionic developer experience much better / be a big + for the project. Not too sure if Ionic can improve the webpack process or if we need to wait for angular to use bazel for instance.

**Steps to reproduce:**
Just follow the ionic beta documentation, setup an ionic 4.x.x project with the following command : 
```
ionic start myApp tabs --type=angular
cd ./myApp
ionic serve
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (C:\Users\romai\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 7.2.0-beta.2
   @ionic/angular-toolkit        : 1.2.2 (C:\Users\romai\ideaProjects\gitalye\node_modules\@ionic\angular-toolkit)

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.1, (and 6 other plugins)

System:

   NodeJS : v11.6.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.5.0
   OS     : Windows 10

```

**Comment by romain10009** [comment]
> I can confirm. I need (for a small-medium-sized project) 9 to 16 seconds to build with Ionic. But I think Angular can be optimized, too

I meant incremental build, the one that happens when you run ionic serve, and you change a line, I clarified my first post.

**Comment by paulstelzer** [comment]
I mean that, too ;) The initial build takes longer for me ;)

**Comment by romain10009** [comment]
What I meant is not 4 seconds for a simple change, but less than 300-500 ms would be a juicy target.

**Comment by paulstelzer** [comment]
Yeah, but this is not the task of Ionic, this is a task for Angular ;)

**Comment by brandyscarney** [comment]
Thanks for the issue! `ionic serve` runs `ng serve` directly which is an Angular command.

As of Ionic 4, Ionic no longer ships with custom Angular build tools. This means any build issues you experience should be considered Angular build issues and should be brought up with the Angular team.

- [Angular Issues](https://github.com/angular/angular/issues)
- [Angular CLI Issues](https://github.com/angular/angular-cli/issues)

I'm going to close this as I do not think it is an Ionic issue. Thanks!
