### ISSUE TITLE
[v4] Add ability to get the Ionic version number at runtime

### ISSUE THREAD

**Issue by moose4lord** [ionic-team/ionic#16942]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
When investigating a bug report it's often helpful to know the version of Ionic used to build the failing app. In the present-day dev environment the "ionic info" command is handy, but at runtime, perhaps long after the app is deployed, this isn't necessarily helpful.

Ionic v3 had a property that would contain the version number, and it could be displayed in the console with this line of code:
`console.log('Running Ionic v' + (<any>window).Ionic.version);`
Ionic v4.0.0-rc.0 does not have this property.

**Describe Preferred Solution**
Something like v3's version property would be nice.

**Comment by redwolf2** [comment]
Related to: https://github.com/ionic-team/ionic/issues/16866#event-2049954523
