### ISSUE TITLE
Indeterminate state for checkboxes

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic#16943]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Implement an indeterminate state for the `ion-checkbox` component. We need this for a nested checkbox tree structure.

![different checkbox states](https://user-images.githubusercontent.com/3410759/50620772-5b0a6700-0f66-11e9-8ce0-53b1e3dde3e7.png)

**Describe Preferred Solution**

The easiest way is probably to add an `indeterminate` prop, because the indeterminate state is visual only and doesn't effect the actual value of the checkbox.

**Related Code**

```tsx
@Component()
export class NestedCheckboxes {
  render = () => [
    <ion-checkbox indeterminate={true} />
    <ion-checkbox onClick={e => (e.target.indeterminate = true)} />
  ];
}
```

**Additional Context**

[Article on CSS Tricks](https://css-tricks.com/indeterminate-checkboxes/).

#11601 is the same (closed) request, just linking here for context.

I will try make a PR for this later today.

**Comment by brandyscarney** [comment]
Released dev build `4.1.0-dev.201903041631.c641ae1` with this in it if you'd like to test it out in your app, thanks again for the PR!
