### ISSUE TITLE
[4.0.0-rc.0] ionic tabs routing issue with named router outlets

### ISSUE THREAD

**Issue by glongchi** [ionic-team/ionic#16944]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

clicking  the different tabs throws error; see error logs section below: error logs indicate the router outlet portion of the url is dropped. but if I specifically copy and paste the correct url for each tab, it renders ok; but seems every content on the page is disabled.
**Expected behavior:**

clicking the different tabs should render the the linked components as expected. 
**NOTE:** This worked fine before I upgrade to from 4.0.0-beta.16 to 4.0.0-rc.0

**Steps to reproduce:**

**Related code:**
**app-routing.module.ts**
```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { AuthGuard } from '@auth/guards/auth.guard';

const routes: Routes = [
  { path: '', redirectTo: 'welcome', pathMatch: 'full' },
  { path: 'home', loadChildren: './features/home/home.module#HomePageModule' },
  { path: 'settings', loadChildren: './features/settings/settings.module#SettingsModule' },
  { path: 'todos', loadChildren: './features/todo/todo.module#TodoPageModule', canActivate: [AuthGuard] },
  {
    path: 'push-notification',
    loadChildren: './features/push-notification/push-notification.module#PushNotificationModule'
  }

];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule {}

```

//lazy-loaded module: routing module(media-campaign.module)

//note all the routed components are within this module

**settings-routing.module.ts**
```
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { SettingsPage } from './settings.page';
import { ThemeComponent } from './containers/theme.component';
import { GeneralComponent } from './containers/general.component';

const routes: Routes = [
  {
    path: 'tabs',
    component: SettingsPage,
    children: [
      {
        path: 'general',
        outlet: 'general',
        component: GeneralComponent
      },
      {
        path: 'account',
        outlet: 'account',
        component: GeneralComponent
      },
      {
        path: 'about',
        outlet: 'about',
        component: GeneralComponent
      },
      {
        path: 'support',
        outlet: 'support',
        component: ThemeComponent
      }
    ]
  },

  {
    path: '',
    redirectTo: '/settings/tabs/(general:general)',
    pathMatch: 'full'
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class SettingsPageRoutingModule {}
```
**settings.page.ts**
```
<ion-tabs>
  <ion-tab tab="general"> <ion-router-outlet name="general"></ion-router-outlet> </ion-tab>
  <ion-tab tab="account"> <ion-router-outlet name="account"></ion-router-outlet> </ion-tab>
  <ion-tab tab="about"> <ion-router-outlet name="about"></ion-router-outlet> </ion-tab>
  <ion-tab tab="support"> <ion-router-outlet name="support"></ion-router-outlet> </ion-tab>

  <ion-tab-bar slot="bottom">
    <ion-tab-button tab="general" href="/settings/tabs/(general:general)">
      <ion-icon name="settings"></ion-icon>
      <ion-label>General</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="account" href="/settings/tabs/(account:account)">
      <ion-icon name="person"></ion-icon>
      <ion-label>Acccount</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="about" href="/settings/tabs/(about:about)">
      <ion-icon name="information-circle"></ion-icon>
      <ion-label>About</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="support" href="/settings/tabs/(support:support)">
      <ion-icon name="help-circle"></ion-icon>
      <ion-label>Support</ion-label>
    </ion-tab-button>
  </ion-tab-bar>
</ion-tabs>
```

**error logs**:
core.js:14597 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'settings/tabs/general'
Error: Cannot match any routes. URL Segment: 'settings/tabs/general'
    at ApplyRedirects.push../node_modules/@angular/router/fesm5/router.js.ApplyRedirects.noMatchError (router.js:2469)
    at CatchSubscriber.selector (router.js:2450)
    at CatchSubscriber.push../node_modules/rxjs/_esm5/internal/operators/catchError.js.CatchSubscriber.error (catchError.js:34)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._error (Subscriber.js:80)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.error (Subscriber.js:60)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._error (Subscriber.js:80)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.error (Subscriber.js:60)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._error (Subscriber.js:80)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.error (Subscriber.js:60)
    at TapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/tap.js.TapSubscriber._error (tap.js:61)
    at resolvePromise (zone.js:814)
    at resolvePromise (zone.js:771)
    at zone.js:873
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:16147)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:500)
    at invokeTask (zone.js:1540)

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**ionic info**
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (C:\Users\lkanouo\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.0

**Comment by paulstelzer** [comment]
Thanks for your issue! You have to check the breaking changes for beta.18 -> https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#breaking-changes-1

It was a refactor of tabs, so it changed!

**Comment by glongchi** [comment]
@paulstelzer , thanks for the quick response.  that resolved it.
