### ISSUE TITLE
4.0.0-rc.0 ModalController - creating and presenting a modal does nothing

### ISSUE THREAD

**Issue by imadbakir** [ionic-team/ionic#16968]
# Bug Report

**Ionic version:**
4.0.0-rc.0

**Current behavior:**
Creating & presenting a modal does nothing.
No Modal is shown on screen.

**Expected behavior:**
Modal gets displayed on screen.

**Steps to reproduce:**
create an app with these packages
 "@angular/animations": "~7.1.0",
    "@angular/cdk": "~7.1.0",
    "@angular/common": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/http": "~7.1.0",
    "@angular/material": "~7.1.0",
    "@angular/material-moment-adapter": "~7.1.0",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/pwa": "^0.11.4",
    "@angular/router": "~7.1.0",
    "@angular/service-worker": "~7.1.0",
    "@ionic-native/core": "^4.18.0",
    "@ionic-native/splash-screen": "^4.18.0",
    "@ionic-native/status-bar": "^4.18.0",
    "@ionic/angular": "^4.0.0-rc.0",
    "@ionic/angular-toolkit": "^1.2.2",
    "@ionic/core": "^4.0.0-rc.0",

Run the app and present a modal
**Related code:**

```
async presentFilter() {
    const modal = await this.modalController.create({
      component: FilterModalComponent,
      showBackdrop: true,
      backdropDismiss: true,
      animated: true
    });
    return await modal.present();
  }
```

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Capacitor:

   capacitor (Capacitor CLI) : not installed
   @capacitor/core           : not installed

System:

   NodeJS : v8.12.0 (/usr/local/bin/node)
   npm    : 6.5.0
   OS     : macOS Mojave
```

**Comment by paulstelzer** [comment]
Presenting a modal should work (I use it a lot). Please add a repo because your displayed code is correct, did you add FilterModalComponent to entrycomponents?

**Comment by imadbakir** [comment]
> Presenting a modal should work (I use it a lot). Please add a repo because your displayed code is correct, did you add FilterModalComponent to entrycomponents?

@paulstelzer Yes I did add it to entryComponents, it was working it stopped working after updating to 4.0.0-rc.0
repo : https://github.com/imadbakir/casemanagement

**Comment by imadbakir** [comment]
> > Presenting a modal should work (I use it a lot). Please add a repo because your displayed code is correct, did you add FilterModalComponent to entrycomponents?
> 
> @paulstelzer Yes I did add it to entryComponents, it was working it stopped working after updating to 4.0.0-rc.0
> repo : https://github.com/imadbakir/casemanagement

it turned out it was because of bootstrap css overriding ionic css regarding modals. 
can be closed.

**Comment by paulstelzer** [comment]
Thanks for answering :)
