### ISSUE TITLE
Subscribe to a component output event(created in a modal) from outside the modal.

### ISSUE THREAD

**Issue by glongchi** [ionic-team/ionic#16963]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

My use case in summary:
I have a  parent component TagAdminComponent(a smart component that is able to call a Tagservice or state management store). This parent component houses  child components;  list(generic-list) and form(generic-form) components. These child components are dumb reusable components which communicate with the parent through inputs and output. I need to be able to handle the child output event from; when created in the modal; from the parent component.

**Related Code**

```
  <ion-content padding>
    <ion-grid>
      <ion-row>
        <ion-col size="12" size-md="6">  
            <generic-list
              [hasCustomTemplate]="false"
              [isApp]="isApp"
              [itemList]="modelList"
              (viewItem)="onViewItem($event)"
              (updateItem)="onUpdateItem($event)"
              (deleteItem)="onDeleteItem($event)"
              (archiveItem)="onArchiveItem($event)"
            >
            </generic-list>
        </ion-col>
        <ion-col *ngIf="!isApp" size="12" size-md="6">
          <generic-form [config]="config" (created)="onCreated($event)"> </generic-form>
        </ion-col>
      </ion-row>
    </ion-grid>
  
    <ion-fab *ngIf="isApp" vertical="bottom" horizontal="end" slot="fixed" (click)="presentItemForm(config)">
      <ion-fab-button> <ion-icon name="add"></ion-icon> </ion-fab-button>
    </ion-fab>
  </ion-content>
```
So on a larger screens the two child components are rendered side by side but on small sreens(usually on mobile phone), I render just the list component and launch the form component through modal and I need to be able to handle the created event(in the child form component)  through the oncreate method defined in the parent. I am using these generic child components accross the application hence the dumb-smart components design approach. 

In ionic v3, I could easily handle this implementation with the code snippet below. Not sure why this ability missing ionic 4
```
const modal = this.modalCtrl.create(MyComponent);
modal.didEnter.subscribe(() => {
    modal.instance.create.subscribe( //call this.onCreate(event) )
});
```

**Describe Preferred Solution**

It would be great to add this ionic v3 feature back.

**Describe Alternatives**

With the current state, there is no alternative to handle this address this scenario

**Additional Context**

**Comment by orochies** [comment]
This feature is important, it is assumed that events are the means of communication between components.

If the modal windows change this behavior, it seems wrong to me.
