### ISSUE TITLE
ionSlideProgress missing on ionic4 IonSlides

### ISSUE THREAD

**Issue by Farbdose** [ionic-team/ionic#16964]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
With ionic4 it has become impossible to access the swipers progress event of an IonSlide

**Expected behavior:**
Make `progress` event of `swiper` available over `ionSlideProgress` proxy event (like in Ionic3)

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 28 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/user/Android/Sdk)
   NodeJS            : v8.11.2 (/usr/bin/node)
   npm               : 5.6.0
   OS                : Linux 4.15

```

**Comment by glenntws** [comment]
This feature indeed is missing. I need it too, would be nice if it would be implemented again!

**Comment by Farbdose** [comment]
I have a workaround, but its very messy and you should only use it if you really need it. <br>**I strongly recommend to wait for ionic to add the event back instead:**

1. track if and where the user is currently dragging the the swiper, then use the deltaX to estimate the sliding direction...
```
this.slides.ionSlideTouchStart.subscribe((data) => {
	this.touchStartX = (data.detail.changedTouches[0] || {clientX: 0}).clientX;
});

this.slides.ionSlideDrag.subscribe((data) => {
	this.touchDeltaX = (data.detail.changedTouches[0] || {clientX: 0}).clientX - this.touchStartX;

        // while the user is still dragging the slider around, update the progress depending on the position
	this.progressChange(this.lastActiveIndex - this.touchDeltaX / document.body.clientWidth);
});
```

After that wait for the user to stop touching the slider ... by default we expect to be transitioning back to the active slide:
```
this.slides.ionSlideTouchEnd.subscribe((data) => {
	// on touchEnd, assume we are transitioning to the currently active slide
	this.slides.getActiveIndex().then(i => {
		this.progressChange(i);
	});
});
```

Then wait for the willChange event that will only fire if we are actually moving to a different slide and overwrite our assumption of moving back to the current slide (we can estimate the direction of the change based on the deltaX ... not tested with a pager...):
```
this.slides.ionSlideWillChange.subscribe((data) => {
	// on willChange (fires after touchEnd), assume we are transitioning in the direction of the swipe
	if (this.touchDeltaX < 0) {
		this.progressChange((this.lastActiveIndex + 1));
	} else if (this.touchDeltaX > 0) {
		this.progressChange((this.lastActiveIndex - 1));
	}
	this.touchDeltaX = 0;
});
```

And finally: after transitionEnd update the last known index:
```
this.slides.ionSlideTransitionEnd.subscribe((sli) => {
	// on transition end (like didChange but firing always) overwrite progress with current index
	this.slides.getActiveIndex().then(i => {
		this.lastActiveIndex = i;
		this.progressChange(i);
	});
});
```

This in combination with a 300ms transition on what ever progressChange is changing manages to create a smooth transition of the background color while sliding...

**Comment by Farbdose** [comment]
@glenntws @juny58 I found a proper solution: You can access the unerlying swiper instance with `ionSlides.el.swiper`

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as you can now access the main swiper instance using the `getSwiper()` method. From there, you can listen for the slides progress. For more info, please see: https://ionicframework.com/docs/api/slides#methods. Thanks!
