### ISSUE TITLE
when use browser back button has no page transition

### ISSUE THREAD

**Issue by lightman0215** [ionic-team/ionic#16971]
**Ionic version:**
4.0.0-rc.0

**Current behavior:**
using browser back button has no page transition

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Capacitor:

   capacitor (Capacitor CLI) : not installed
   @capacitor/core           : not installed

System:

   NodeJS : v10.14.2 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**ionic4.0.0 beta 15**
![avatar](http://47.99.88.191/1.gif)

**ionic4.0.0 rc-0**
![avatar](http://47.99.88.191/2.gif)

**Comment by KevinKelchen** [comment]
This issue may have some relation to #16569.

**Comment by manucorporat** [comment]
This is the expected behaviour, unfortunately there is not reliable APIs provided by the browser to know the direction, we decided to go with no animation for the moment, it's much safer!
