### ISSUE TITLE
[v4-rc0] Misaligned text only buttons inside toolbars

### ISSUE THREAD

**Issue by ptitjes** [ionic-team/ionic#16975]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Text only buttons in toolbars are misaligned w.r.t. the toolbar title.
See this jsfiddle: http://jsfiddle.net/ptitjes/xbzsgkmr/10/.

**Expected behavior:**
Text only buttons should be baseline aligned w.r.t. the toolbar title as defined by the Material spec.
See [Full-screen dialog](https://material.io/design/components/dialogs.html#specs).

**Steps to reproduce:**
Use a text only button in a toolbar.

**Related code:**

C.f. http://jsfiddle.net/ptitjes/xbzsgkmr/10/.
```
    <ion-toolbar color="primary">
      <ion-buttons slot="start">
        <ion-button>
          <ion-icon name="close"></ion-icon>
        </ion-button>
      </ion-buttons>

      <ion-title>
        Page title
      </ion-title>

      <ion-buttons slot="primary">
        <ion-button>
          Action
        </ion-button>
      </ion-buttons>
    </ion-toolbar>
```

**Other information:**
I have not enough CSS skills to fix this. :(
Maybe related to https://github.com/ionic-team/ionic/issues/14444.

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.3.0 (/opt/npm/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0 (/home/didier/Code/cabasvert/cabasvert/node_modules/@ionic/angular)
   @angular-devkit/build-angular : 0.11.4 (/home/didier/Code/cabasvert/cabasvert/node_modules/@angular-devkit/build-angular)
   @angular-devkit/schematics    : 7.1.4 (/home/didier/Code/cabasvert/cabasvert/node_modules/@angular-devkit/schematics)
   @angular/cli                  : 7.1.4 (/home/didier/Code/cabasvert/cabasvert/node_modules/@angular/cli)
   @ionic/angular-toolkit        : 1.2.2 (/home/didier/Code/cabasvert/cabasvert/node_modules/@ionic/angular-toolkit)

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.13
   @capacitor/core           : 1.0.0-beta.13 (/home/didier/Code/cabasvert/cabasvert/node_modules/@capacitor/core)

System:

   NodeJS : v10.15.0 (/usr/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.19
```

**Comment by ptitjes** [comment]
@paulstelzer The text of the text button `ACTION` is not aligned to the title text of the toolbar. It is supposed to be baseline aligned. See the spec details (the link provided in the issue description), specifically the "Full-screen dialog" screenshot (there is an horizontal rule to exhibit the vertical baseline alignment).

I tried to fix it to make a PR but I am not good enough with CSS flex...

**Comment by ptitjes** [comment]
@paulstelzer This is how it is supposed to look:
![Full-screen dialog](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1JptW_fp8opA8xhP50x4mP46mKGuG8yhh%2Fspecs-dialog-mobile-fullscreen.png)

**Comment by paulstelzer** [comment]
Ah okay, we have an issue for that, maybe I found it :)
