### ISSUE TITLE
@ionic/angular 4.0.0-rc.0

### ISSUE THREAD

**Issue by pairmix** [ionic-team/ionic#16970]
Hi there,
Following components are missing:

- Content
- Slides

How can i replace them ?

Best regards

**Comment by glongchi** [comment]
All components now prefixed with the Ion Keyword. Now: IonContent, IonSlides

**Comment by pairmix** [comment]
Thank you very much @glongchi

**Comment by abennouna** [comment]
Are you referring to the `resize()` method from Ionic 3?

If it's that one, it has been removed as you can see from the [breaking changes](https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#resize-was-removed).

**Comment by pairmix** [comment]
Thanx @abennouna !
