### ISSUE TITLE
ng serve is about 5 times slower when compiling with IonicModule (Angular 7)

### ISSUE THREAD

**Issue by tonyawad88** [ionic-team/ionic#16979]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
A brand new angular project has a compile time < 1 second. When I add `@ionic/angular` , the compile time becomes on average > 5 seconds when using it with `ng serve`

Any idea why this happens? Is this an ionic issue?

**Expected behavior:**
Expected compile time to be as fast as Ionic3 or faster.

**Steps to reproduce:**
1, Start a new angular project
2. run ng serve, change app.component.htm multiple times and notice how the compile time is < 1seconds after a couple compiles
2. run `npm i @ionic/angular`
3. Add IonicModule to the angular module
4. run ng serve and notice how the average time is now > 5 seconds.

**Related code:**

**Other information:**

**Ionic info:** 
```
Ionic:
   ionic (Ionic CLI) : 4.6.0
System:
   NodeJS : v10.15.0
   npm    : 6.5.0
   OS     : Windows 10
```

**Comment by hiepxanh** [comment]
please provide `package.json` and try replace `angular-devkit` to this version `"@angular-devkit/build-angular": "~0.10.7",`

**Comment by tonyawad88** [comment]
I tried it and it's about the same. Here's my package.json after adding your suggestion:
```
{
  "name": "test-ionic4-speed",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~7.1.4",
    "@angular/core": "~7.1.4",
    "@angular/forms": "~7.1.4",
    "@angular/http": "~7.1.4",
    "@angular/platform-browser": "~7.1.4",
    "@angular/platform-browser-dynamic": "~7.1.4",
    "@angular/router": "~7.1.4",
    "@ionic-native/core": "5.0.0-beta.21",
    "@ionic-native/splash-screen": "5.0.0-beta.21",
    "@ionic-native/status-bar": "5.0.0-beta.21",
    "@ionic/angular": "4.0.0-rc.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.10.7",
    "@angular-devkit/build-angular": "^0.10.7",
    "@angular-devkit/core": "~7.1.4",
    "@angular-devkit/schematics": "~7.1.4",
    "@angular/cli": "~7.1.4",
    "@angular/compiler": "~7.1.4",
    "@angular/compiler-cli": "~7.1.4",
    "@angular/language-service": "~7.1.4",
    "@ionic/angular-toolkit": "~1.2.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.12.0",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.12.0",
    "typescript": "~3.1.6"
  },
  "description": "An Ionic project"
}
```

**Comment by tonyawad88** [comment]
Demo of the above case:
![angularcompiletime-with-ionic-and-without](https://user-images.githubusercontent.com/3638322/50767805-3a832b00-124c-11e9-8a01-3bc8d43bdfb7.gif)

**Comment by paulstelzer** [comment]
It's because IonicModule imports a lot of modules and so every time you make a change it needs a lot of time to compile

**Comment by manucorporat** [comment]
Tracking progress here: https://github.com/ionic-team/ionic/issues/17001

Thanks for the issue report!
