### ISSUE TITLE
[4.0.0-rc.0] Last item in ion-list not receiving correct line

### ISSUE THREAD

**Issue by RHinderiks** [ionic-team/ionic#16983]
# Bug Report

**Ionic version:**
[4.0.0-rc.0]

**Current behavior:**
A regular list with items does not show its bottom line correctly which is too short.

**Expected behavior:**
The last item in the list should have a full line as bottom border
The first item in a list should have a full line as top border

![img_52f7a56a5ac9-1](https://user-images.githubusercontent.com/26223525/50769282-c95f6a00-1283-11e9-9966-d91d7c277b91.jpeg)

**Steps to reproduce:**
Create a list of items

**Related code:**

```
<ion-list>
<ion-item>Item 1</ion-item>
<ion-item>Item 2</ion-item>
<ion-item>Item 3</ion-item>
<ion-list>
```

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/Users/rh/.nvm/versions/node/v8.11.4/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.0
   @angular-devkit/schematics    : 7.1.0
   @angular/cli                  : 7.1.0
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.3.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 14 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/rh/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.0.0
   NodeJS            : v8.11.4 (/Users/rh/.nvm/versions/node/v8.11.4/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by brandyscarney** [comment]
Thanks for the issue! This is now the default in v4. It's too error prone to determine which item is the "last item" in a list using purely CSS, especially when the list gets more complex with wrappers such as custom components wrapping the item, item sliding, or a menu toggle. There are also many use cases where the last item in a list does *not* have a full border, as seen in the iOS Health app (Health Data tab) or the Reminders app. For these reasons, we have decided to let the user control how the border should act. To achieve a full line on the last item, you could use the following markup:

```
<ion-list>
  <ion-item>
    <ion-label>Item 1</ion-label>
  </ion-item>
  <ion-item>
    <ion-label>Item 2</ion-label>
  </ion-item>
  <ion-item lines="full">
    <ion-label>Item 3</ion-label>
  </ion-item>
<ion-list>
```

See this PR for more information: https://github.com/ionic-team/ionic/pull/16456

Updating the list header is on our TODO list though!

**Comment by RHinderiks** [comment]
Thanks for the fast response! Totally makes sense now.
