### ISSUE TITLE
Checkbox bottom line different than other elements

### ISSUE THREAD

**Issue by dkrahn** [ionic-team/ionic#16986]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Adding the ion-checkbox to an ion-item behaves different than with an ion-input or other interactive components.
The ion-item does not get the class .item-interactive applied, so the styling get a bit different from the other components. 

**Expected behavior:**
With a list of interactive components(input, datetime, select) the checkbox should have the same styling so that the line separator does not get applied differently.

**Steps to reproduce:**
Use the related code and you will see the line under the checkbox item is different from the other kind of components.

**Related code:**
```
<ion-content>
  <ion-list>

    <ion-item>
      <ion-label>Select</ion-label>
      <ion-select></ion-select>
    </ion-item>

    <ion-item>
      <ion-label>Input</ion-label>
      <ion-input></ion-input>
    </ion-item>

    <ion-item>
      <ion-label>Checkbox</ion-label>
      <ion-checkbox></ion-checkbox>
    </ion-item>

    <ion-item>
      <ion-label>Datetime</ion-label>
      <ion-datetime></ion-datetime>
    </ion-item>

  </ion-list>
</ion-content>
```

**Other information:**
Looks to me like the class `.item-interactive` is not being applied to the `ion-item` element.

**Ionic info:** 
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (C:\Users\Daniel\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (C:\Users\Daniel\AppData\Local\Android\Sdk)
   NodeJS            : v8.11.4 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

**Comment by mburger81** [comment]
Same for **4.1.2**

This looks quite strange (as the new line for the whole `ion-item` length)

![image](https://user-images.githubusercontent.com/3778892/54289764-06105000-45aa-11e9-9685-b9da64a3e284.png)
