### ISSUE TITLE
Template parse errors: 'ion-tab' is not a known element:

### ISSUE THREAD

**Issue by thezeeshanasghar** [ionic-team/ionic#16995]
# Bug Report

**Ionic version:**
[x] **4.x**

**Ionic Info:**
Ionic:

   ionic (Ionic CLI)             : 4.7.0 (C:\Users\NBLHRZEESHAN\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.5.0
   OS     : Windows 10

**Current behavior:**
I just copy paste the default tab code provided in 4.0.0-rc.0 docs https://beta.ionicframework.com/docs/api/tabs and it gives me the error
ERROR Error: Uncaught (in promise): Error: Template parse errors:
'ion-tab' is not a known element:

**Expected behavior:**
It should show the tabs pages with proper layout

**Steps to reproduce:**

1. Go to https://beta.ionicframework.com/docs/api/tabs/ and copy paste the tab code found under the 'Usage' heading into any lazy or eagerly loaded component
2. run 'ionic serve'
3. see error in console
4. see error in visual studio code

**Related code:**
```
<ion-tabs>
  <ion-tab tab="home">Home Content</ion-tab>
  <ion-tab tab="settings">Settings Content</ion-tab>

  <ion-tab-bar slot="bottom">

    <ion-tab-button tab="home">
      <ion-label>Home</ion-label>
      <ion-icon name="home"></ion-icon>
      <ion-badge>6</ion-badge>
    </ion-tab-button>

    <ion-tab-button tab="settings">
      <ion-label>Settings</ion-label>
      <ion-icon name="settings"></ion-icon>
    </ion-tab-button>

  </ion-tab-bar>
</ion-tabs>

```

**Additional Context:**
my package json is 
    "@ionic-native/core": "5.0.0-beta.21",
    "@ionic-native/splash-screen": "5.0.0-beta.21",
    "@ionic-native/status-bar": "5.0.0-beta.21",
    "@ionic/angular": "4.0.0-rc.0",
    "@ionic/pro": "2.0.4",

**Comment by paulstelzer** [comment]
Thanks for your issue. ion-tab is not available for `@ionic/angular`. See the breaking changes at the changelog -> https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#angular-tabs

Just remove ion-tab and adjust your routing
