### ISSUE TITLE
inner-scroll or ion-background-color to support background color to set transparent for qrscanner

### ISSUE THREAD

**Issue by lim-enhui** [ionic-team/ionic#16991]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I have attempt to declare .inner-scroll { background: transparent none !important } and also i have set 
  --ion-background-color {
    background: transparent none !important;
  }
 however I dont get the expected result to display the camera.. I only get to view camera display when i manually remove it on the inspect tools.
**Expected behavior:**

To view Camera output

**Steps to reproduce:**

append the code onto the html element attributes

html.cameraView {

  background: transparent none !important;

  body, ion-app, ion-content, .modal-wrapper, .ion-page, .inner-scroll {
    background: transparent none !important;
  }

  --ion-background-color {
    background: transparent none !important;
  }

  app-home {
    visibility: hidden;
  }

}

**Related code:**
https://github.com/bitpay/cordova-plugin-qrscanner/issues/204

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by lim-enhui** [comment]
ion-content {
    --background: var(--ion-background-color, transparent);
}

solution to work on shadow dom but would advise an introduction to cover shadow dom

**Comment by paulstelzer** [comment]
You already found the correct solution

ion-content {
--background: transparent; // you don't need to use custom property, but you can of course
}

Because .inner-scroll is inside shadow dom, you have no access to it by using `ion-content .inner-scroll`. This is not working
