### ISSUE TITLE
Ionic is not upgradable to latest version of Angular

### ISSUE THREAD

**Issue by adamduren** [ionic-team/ionic#16990]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Ionic lists a `@angular/router` peerDependency locked to a specific minor version. (patch upgradeable)

**Expected behavior:**
For Angular to be at least minor version upgradeable without requiring a new release of Ionic

**From @ionic/angular package.json**
```
  "peerDependencies": {
    ...
    "@angular/router": "~7.1.4",
    ...
  },
```

**Comment by adamduren** [comment]
I should note it's the only angular `peerDependency` using a `~` vs `^`, possibly by mistake. If so, easy fix!

**Comment by manucorporat** [comment]
Fixed by paul!
