### ISSUE TITLE
ionic building the wrong app when emulate is ran without live reload

### ISSUE THREAD

**Issue by bryce13950** [ionic-team/ionic#16996]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

OK, so this is a really weird bug. I have a number of projects on my system, and whenever I run my ionic app onto my iOS emulator with live reload enabled, everything works fine. However, when I run the app without live reload I then get a completely different app loading. This isn't even just a different app, but it isn't even an ionic app. The app that shows up after the expected splash page is an elm 0.19 single page app that I have been developing.

http://www.pomeloproductions.com/example.mov

The above video clip is taken directly from the simulator. You can see that when the app is opened, one brand is shown as the splash page, but then after the splash page goes away we are left with an app with completely different branding. The app with different branding is the elm application I am referring to, and you can clearly see the elm reactor running on the bottom right of the simulator.

**Expected behavior:**

The ionic app should run.

**Steps to reproduce:**

Create an elm app, and an ionic app. Run the elm app, and then run the ionic app onto an emulator without live reload enabled. The directory structure I have is as follows...

~/Projects/Project1/www/ <- root elm app directory
~/Projects/Project2/merchant/ <- root ionic app directory

**Related code:**

Heres the repo to the elm app https://github.com/TheHaeckelSociety/Athenia-www/tree/develop. Any ionic app seems to do the same thing.

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/Users/brycemeyer/.nvm/versions/node/v11.2.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.0.7
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 8 other plugins)

System:

   Android SDK Tools : 26.1.1 (/usr/local/share/android-sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 7.0.0
   NodeJS            : v11.2.0 (/Users/brycemeyer/.nvm/versions/node/v11.2.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode   
```

**Comment by bryce13950** [comment]
After removing the iOS platform and running it again, I can confirm that this is still happening.

**Comment by bryce13950** [comment]
This is also not happening on the android emulator, so it seems as if this is something specific to iOS

**Comment by paulstelzer** [comment]
This is not an issue of Ionic, instead it's an issue of https://github.com/ionic-team/cordova-plugin-ionic-webview

You are using Version 2.2.0, here you have to set a custom port. But Version 3 is already available. Here you can set a custom hostname. Change it and the problem is solved -> https://github.com/ionic-team/cordova-plugin-ionic-webview#hostname
