### ISSUE TITLE
Ionic 4 RC: no errors into console

### ISSUE THREAD

**Issue by pairmix** [ionic-team/ionic#16999]
Hi there,
I used to use ionic-app-scripts to build/compile my ionic projet but it seems that ionic-app-scripts is not maintained anymore, and doesn't work with ionic 4.
So now i'm using ng build and ng serve.
Ng build return no errors but i think it should because all my packages are not installed.
Then Ng serve does not redirect to my current route with no reason, i've got no error in the console.
How can i activate full errors in the console?

**Comment by manucorporat** [comment]
Ionic 4 uses ng CLI, not ionic-app-script anymore.
