### ISSUE TITLE
[4.0.0-rc.0] slidemenu template

### ISSUE THREAD

**Issue by Juexro** [ionic-team/ionic#16992]
version: 
"@ionic/angular": "4.0.0-rc.0"

behavior:
1. choose slidemenu template
2. ionic cordova run android -l -c
3. slideslip to open the menu, but all click events will have no effect. bug ?

**Comment by Juexro** [comment]
in ionic3, it works ok.

**Comment by paulstelzer** [comment]
This could a duplicate of #16863 - I think it's the same root cause

**Comment by paulstelzer** [comment]
As said before I htink it's a duplicate so I close this here
