### ISSUE TITLE
Flat modules for ionic/angular

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#17001]
- Ship fesm5.js (es5) legacy build
- Ship fesm2015.js (es2017) modern build
- Use angular's flatModule feature, exporting a single .metadata.json file

https://github.com/angular/angular/blob/f5471107d94a5a2ec9d024e076cc4f1a4882013f/packages/core/tsconfig-build.json#L28-L29

GOAL:

- Speed up build using ionic/angular
- Reduce webpack overhead
- Improve treeshakability
- Ship untranspiled async/await and classes for modern build

**Comment by adamduren** [comment]
@manucorporat did this PR have the desired effect of reducing build times? Would you mind sharing any stats?

**Comment by tonyawad88** [comment]
@manucorporat #16979 great job! thank you, the compile time has improved by about 2 seconds for me, much more acceptable. Any ideas if there's time for another round of optimizations before the final release?
