### ISSUE TITLE
No errors into the console

### ISSUE THREAD

**Issue by pairmix** [ionic-team/ionic#17002]
# Bug Report

**Ionic version:**
4.6

**Current behavior:**
http://localhost:8100/, blank page, without any errors into console

**Expected behavior:**
Redirection to http://localhost:8100/myroute

**Steps to reproduce:**
configure app-routing.module.ts:
{ path: '', redirectTo: 'myroute', pathMatch: 'full' },
{ path: 'myroute', loadChildren: './pages/myroute/myroute.module#MyRoutePageModule' },
Then execute http://localhost:8100/

myroute.module.ts:
````
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { IonicModule } from '@ionic/angular';
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
import { MyroutePage } from './myroute';
import {PipesModule} from '../../pipes/pipes.module';

@NgModule({
  declarations: [
    MyroutePage,
  ],
  imports: [
    CommonModule,
    IonicModule,
    TranslateModule.forChild(),
    RouterModule.forChild([
      {
        path: '',
        component: MyroutePage
      }
    ]),
    PipesModule
  ],
  exports: [
    MyroutePage
  ]
})
export class MyroutePageModule {}
````

PipesModule :
````
import { NgModule } from '@angular/core';
import { DomainImgPipe } from './domain-img/domain-img';

@NgModule({
	declarations: [
            DomainImgPipe,
        ],
	imports: [],
    providers: [
        DomainImgPipe
    ],
	exports: [
            DomainImgPipe,
        ]
})
export class PipesModule {}
````

DomainImgPipe :
````
import { Pipe, PipeTransform } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import { ConfigProvider } from '../../services/config/config';

@Pipe({
  name: 'domainImg'
})
export class DomainImgPipe implements PipeTransform {
  lang: string;
  HOSTID: string;
  constructor(
      public translate: TranslateService,
      private configProvider: ConfigProvider,
  ) {
    //this.lang = translate.getDefaultLang();
      this.lang = 'fr';
      this.HOSTID = this.configProvider.getHostID();
  }
  transform(name: string, args?: any): string {
    let domainImg = 'assets/domains/' + this.HOSTID;
    return domainImg + '/' + name; // + '/' + this.lang
  }
}
````
First of all, i realised that i can't use NavParams => error:

````
import { Component } from '@angular/core';
import { NavController, NavParams } from '@ionic/angular';

@Component({
  selector: 'myroute',
  templateUrl: 'myroute.html',
  styleUrls: ['myroute.scss'],
})
export class MyroutePage {
constructor(
      public navCtrl: NavController, 
      //public navParams: NavParams, => error if uncomment
  )
}
````

myroute.html
```
<ion-header>

  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button></ion-back-button>
    </ion-buttons>
    <ion-title>{{'Vos abonnements' | translate}}</ion-title>
    <ion-buttons slot="primary">
        <div class="header-logo">
            <img src="{{'logo_small.gif' | domainImg}}"/>
        </div>
    </ion-buttons>
  </ion-toolbar>

</ion-header>

<ion-content padding>
OK
</ion-content>

```

Redirection towards /myroute does not work and absolutly no error message in the console.

**Comment by pairmix** [comment]
If i remove pipes,
redirection is ok

````
<ion-header>

  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button></ion-back-button>
    </ion-buttons>
    <ion-title>{{'Vos abonnements'}}</ion-title> <!-- | translate-->
    <ion-buttons slot="primary">
        <div class="header-logo">
            <img src="{{'logo_small.gif'}}"/> <!-- | domainImg-->
        </div>
    </ion-buttons>
  </ion-toolbar>

</ion-header>


<ion-content padding>
OK
</ion-content>
````

So issue is relative to :
1 - NavParams that cannot be injected into compoent constructor
2 - pipes that seem not be recognized into my view

Whatever, i get no error into console .

**Comment by paulstelzer** [comment]
Thanks for your issue! 

#16787 - The issue in fact of navparams (btw, you don't need this anymore because angular can do this)

What's affected the pipes, I cannot say and that you get no error in console is maybe because there is no error he can show

You can enable tracing to check if there is a route change:

```
    RouterModule.forRoot(
      routes,
      { enableTracing: true } // <-- debugging purposes only
    )
```

I think (exept navparams) the root cause is not related to Ionic, more to Angular, so this issue can be closed

**Comment by pairmix** [comment]
I get no errors even with these debug params.
I don't think this issue is relative to angular because if i remove IonicModule, from my imports into myroute.module.ts, it doesn't work and i don't have errors in my console.

**Comment by paulstelzer** [comment]
You will not get any error with enableTracing, it's just for you to see routing.

Please create a repo so we can check

**Comment by pairmix** [comment]
It's easy to test it.
Just do :
> ionic start myproject
choose blank

Then >ionic serve -w firefox

When all is ok, homepage is http://localhost:8100/home

THEN:
- comment IonicModule in home.module.ts

````
@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    //IonicModule,
    RouterModule.forChild([
      {
        path: '',
        component: HomePage
      }
    ])
  ],
  declarations: [HomePage]
})
export class HomePageModule {}
````
After rebuild => http://localhost:8100
http://localhost:8100/home doesn't work anymore

BUT NO ERROR IN CONSOLE

**Comment by paulstelzer** [comment]
If I do something like this (in my project), I will get an error that xxx is not a known element (in my case ion-menu because it's the first unknown element)

![chrome_2019-01-08_20-20-35](https://user-images.githubusercontent.com/20501666/50853591-e890f100-1382-11e9-80f0-715b984b7b70.jpg)

**Comment by pairmix** [comment]
i can't get errors.
So i'm going to uninstall node_modules, ionic, cordova and node/npm and reinstall them.
thank you @paulstelzer

**Comment by pairmix** [comment]
I uninstalled et reinstalled node/ionic/cordova.
![info](https://user-images.githubusercontent.com/33130887/50901751-61428c80-1419-11e9-8afa-ca2ee0f985dd.png)


i commented IonicModule in home.module.ts (ionic starter kit "blank"):
````
@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    //IonicModule,
    RouterModule.forChild([
      {
        path: '',
        component: HomePage
      }
    ])
  ],
  declarations: [HomePage]
})
export class HomePageModule {}
````

Build is OK without any errors.
I don't understand why i can't get errors into console!!!

![compilation](https://user-images.githubusercontent.com/33130887/50901944-dca43e00-1419-11e9-8e45-227be75da878.png)

**Comment by pairmix** [comment]
i'm sorry, as i said, there is no error in my browser.
My root page / is blank and redirection to /home is not done.
This happening with ionic starter kit named blank thats why i ask here.

**Comment by paulstelzer** [comment]
then please share your repo and I will take a look into it

**Comment by pairmix** [comment]
No it's ok, i got errors in firebug.
I forgot to watch there because with ionic-app-script my errors were displayed in console.
Sorry.
