### ISSUE TITLE
ionic 4 - replace dinamically (for page/component) font family

### ISSUE THREAD

**Issue by sante85** [ionic-team/ionic#17006]
i want replace dinamically (for page/component) font family

Instead --ion-font-family: override my style.

How to do?
Thanks

Best regards

---------------------------------------
this is a my bad!!! workaroud...

document.querySelector('body').style.cssText = '--ion-font-family:' + this.eatMenu.font;

is this possible or exists another elegant solution?

thanks

**Comment by manucorporat** [comment]
You can do this:
```js
document.body.style.setProperty('--ion-font-family', this.eatMenu.font);
```
