### ISSUE TITLE
Enable fesm2015 for ionic/angular

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#17013]
Looks like Angular and TS emit nonoptimal ES2015 when using decorators, so tools like Terser and uglify can not remove the dead-code, since webpack uses terser to remove dead-code, this leads to bigger bundlers.

**EXPECTED:**
ES2015 should have at least the same treeshaking capabilities than es5.

**Comment by brandyscarney** [comment]
Can you please label this if it is still something we want to do or close it if not? Thanks!
