### ISSUE TITLE
Import of css files into angular project

### ISSUE THREAD

**Issue by paulstelzer** [ionic-team/ionic#17014]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
At the moment you have to add

```
@import '~@ionic/angular/css/core.css';
@import '~@ionic/angular/css/normalize.css';
@import '~@ionic/angular/css/structure.css';
@import '~@ionic/angular/css/typography.css';

@import '~@ionic/angular/css/padding.css';
@import '~@ionic/angular/css/float-elements.css';
@import '~@ionic/angular/css/text-alignment.css';
@import '~@ionic/angular/css/text-transformation.css';
@import '~@ionic/angular/css/flex-utils.css';
```
to your *.scss / *.css file. Now I noticed there is a `ionic.bundle.css` inside which bundles all this 9 files to one.

Second: All this css files are duplicated, one time inside `@ionic/angular/css/*` and one time in `@ionic/core/css/*`

**Describe Preferred Solution**

One solution could be to add this ionic.bundle.css directly inside the `angular.json` and use the ionic/core path like below:
```
"styles": [
....
              {
                "input": "node_modules/@ionic/core/css/ionic.bundle.css"
              },
...
]
```

So it's not needed to copy the css files again from core to angular. But this is just a few kB of filesize and to support older projects, who not want to to change the path, it can be still included inside `@ionic/angular`

This can also fix https://github.com/ionic-team/ionic/issues/16514 and will the preferred solution of https://github.com/ionic-team/ionic/issues/16514#issuecomment-442967729 of  @mhartington 

What do you guys think?

**Comment by mhartington** [comment]
I don't think we want to do this to allow for flexibility when importing styles into an Ionic project. cc @brandyscarney

**Comment by paulstelzer** [comment]
You can import all css one by one by adding it into styles inside angular.json ;) Then you still have the flexibility and you can addd it easily with `ng add @ionic/angular`

**Comment by manucorporat** [comment]
I don't think in the context of the starter is better to modify the angular.json instead of just commenting out some @import's in the CSS.

**Comment by paulstelzer** [comment]
Alright, was just an idea ;)
