### ISSUE TITLE
[4.0.0-rc.1] IonContent.scrollToTop is not work in production build

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic#17029]
# Bug Report
IonContent.scrollToTop and IonContent.scrollToBottom is worked in development environment ( `$ ionic serve` ). But not work production build.

**Ionic version:**
[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
This is sample.
```ts
import { IonContent } from '@ionic/angular'
export class Tab1Page {
  @ViewChild(IonContent)
  content: IonContent;

  methodHoge() {
    this.content.scrollToTop();
  }
```

**Other information:**

<img width="529" alt="2019-01-10 13 47 13" src="https://user-images.githubusercontent.com/9690024/50946868-d3c97000-14de-11e9-8723-95ac0d9b5eac.png">

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.7.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.12.1
   @angular-devkit/schematics    : 7.2.1
   @angular/cli                  : 7.2.1
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v8.12.0 (/usr/local/bin/node)
   npm    : 6.5.0
   OS     : macOS Mojave
```

**Comment by Silvest89** [comment]
When are you calling this method?

**Comment by paulstelzer** [comment]
RC.1 isn't working in produciton mode, I can confirm and collect everything under one issue -> #17034
