### ISSUE TITLE
swipe or drag event is not working 

### ISSUE THREAD

**Issue by jratiwanich** [ionic-team/ionic#17026]
# Bug Report

**Ionic version:**

[x] **4.7.1**

**Current behavior:**

Trying to implement the swipe or drag event for vertical swipe up or down.

**Expected behavior:**

Ability to swipe a `<div>` or ionic content up or down   (similar to Apple Map or Waze)

**Steps to reproduce:**

1) Create a new page.
2) Add a `<div>` content in the footer section
3) Add (swipe)="" event

**Related code:**

```
<ion-footer>
<div (swipe)="dragToolbar($event)">.......<div>
</ion-footer>
```

**Other information:**
No output, the event does not listen to the finger gesture when trying to swipe or drag. In my code snippet above, `dragToolbar()` is not being called.

**Comment by manucorporat** [comment]
Ionic does not longer include hammerjs by default in order to reduce the bundle size, however you can still add it to your angular project:

https://blog.angularindepth.com/gestures-in-an-angular-application-dde71804c0d0
