### ISSUE TITLE
[v4rc1] css animations bug related with NavController (angular)

### ISSUE THREAD

**Issue by stewwan** [ionic-team/ionic#17025]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

while using tabs routed, css animations doesn't works if you go to a route outside the tabs module using `nav.navigateRoot()`

![img_5714trim](https://user-images.githubusercontent.com/719763/50980822-b7c6ce00-14e0-11e9-92df-53335251a18d.gif)

**Expected behavior:**

css animation with NavigationController

**Steps to reproduce:**

- git clone https://github.com/stewwan/ionic-v4-nav-regression
- ionic cap run ios --livereload

I think this might be related with NavController, the same approach was working just fine in last ionic beta 19

**Related code:**

- https://github.com/ionic-team/ionic/commit/8ee9205629cfa432d36f5b7e5617fac65734b1b4#diff-68c0efda98168f58059a80de770871e5
- https://github.com/ionic-team/ionic/commit/320eb03168ef3a9726f484b7088efbf758741002#diff-68c0efda98168f58059a80de770871e5

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.7.1 (/Users/stewan/.nvm/versions/node/v10.11.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.13
   @capacitor/core           : 1.0.0-beta.13

System:

   NodeJS : v10.11.0 (/Users/stewan/.nvm/versions/node/v10.11.0/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by hmonarch** [comment]
I am getting no animation when using <ion-tab-button (click)="animateNavigation()">

and putting navigateRoot in a method of animateNavigation();

**Comment by stewwan** [comment]
@manucorporat as this regression came up from your commit, can you please take a look?

**Comment by manucorporat** [comment]
I am not sure it's a regression, what's the expected behaviour for you? to have animation using `navigateRoot()`?

**Comment by stewwan** [comment]
@manucorporat thanks for paying attention here

If you run the example on your phone, you should understand. it's built from ionic cli tabs template.

 https://github.com/stewwan/ionic-v4-nav-regression

tab1 has two links, one using NavController and other using HREF attribute

when you click on href link, it works fine, going to the "outside page"  with animations in the header 

but when you click on link with the NavController, you get the outside page but no animations

**Comment by stewwan** [comment]
just updated the gif, the first one was weird

![img_5714trim](https://user-images.githubusercontent.com/719763/50980864-d4630600-14e0-11e9-8a02-251b499273e9.gif)

**Comment by hmonarch** [comment]
> I am not sure it's a regression, what's the expected behaviour for you? to have animation using `navigateRoot()`?

How do you simply apply navigateForward + backward between tabs? I have 

<ion-tab-button (click)="navigateForward()"> going to a new tab, but that animation is not working at all.

**Comment by stewwan** [comment]
if this is not a regression, I don't know what it is. all I know is that if you try the same example in ionic beta 19 it works. we're close to launch a major update here [@INFLCR](https://twitter.com/inflcr)

any thoughts @manucorporat

**Comment by stewwan** [comment]
okay I managed to workaround that by using Ng Router instead of Ionic Nav Controller. feel free to close this issue if you really find this is not a regression.

for those who are getting the same

```js
 // this.nav.navigateRoot(["/page-outside-tabs"]); // avoid
 this.router.navigate(["/page-outside-tabs"]);
```

**Comment by paulstelzer** [comment]
I wonder why the first one is not working:

`this.nav.navigateRoot(["/page-outside-tabs"]);` should be exactly the same like `this.router.navigate(["/page-outside-tabs"]);`

https://github.com/ionic-team/ionic/blob/master/angular/src/providers/nav-controller.ts#L64

but maybe the animations overwrite it. I think if you disable the animation by adding options to navigateRoot it should work too!
