### ISSUE TITLE
[4.0.0-rc.1]Slides do not work in production build

### ISSUE THREAD

**Issue by toriphes** [ionic-team/ionic#17032]
# Bug Report
This problem seems to be related to the angular build optimizer.

**Ionic version:**
[x] **4.0.0-rc.1**

**Current behavior:**
When serving the app with the command `ionic serve --prod` ion-slides show only the first of N° slides and the browser get an error in the console:

![schermata 2019-01-10 alle 09 36 07](https://user-images.githubusercontent.com/4192159/50957093-a02a1e00-14bd-11e9-9fc4-69807ab25f5f.png)

**Expected behavior:**
Shows all the slides without errors in the console

**Steps to reproduce:**
Serve the template code below with `--prod` flag

**Related code:**

```html
<ion-header>
  <ion-toolbar>
    <ion-title>Slider</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>

  <ion-slides pager="true">
    <ion-slide>slide 1</ion-slide>
    <ion-slide>slide 2</ion-slide>
  </ion-slides>

</ion-content>

```

**Other information:**
Setting `buildOptimizer: false` In the `angular.json` file solves the problem but this is a silly workaround.

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.7.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2
```

**Comment by paulstelzer** [comment]
RC.1 isn't working in produciton mode, I can confirm and collect everything under one issue -> #17034
