### ISSUE TITLE
[RC1] has no exported member 'CheckedInputChangeEvent

### ISSUE THREAD

**Issue by RafaelKr** [ionic-team/ionic#17036]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
After the update from RC0 to RC1 I get the error `[ts] Module '"../../../node_modules/@ionic/core/dist/types/interface"' has no exported member 'CheckedInputChangeEvent'. [2305]`
I had to replace `CheckedInputChangeEvent` with `CheckboxChangeEventDetail`.

**Expected behavior:**
The changes made in commit https://github.com/ionic-team/ionic/commit/3d656ac3127278a7c9d3d4808c2806fde71e5d2b should be mentioned as Breaking Changes in the [CHANGELOG.md](https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md)

**Other information:**
I'm using Ionic in an stencil application, so you'll get my dependencies instead of an ionic info.

**package.json:** 

```
"dependencies": {
  "@ionic/core": "^4.0.0-rc.1",
  "@ionic/pwa-elements": "^1.0.0"
},
"devDependencies": {
  "@stencil/core": "^0.16.2",
  "@stencil/sass": "^0.1.1",
  "@types/jest": "23.3.12",
  "@types/puppeteer": "1.11.1",
  "jest": "23.6.0",
  "jest-cli": "23.6.0",
  "puppeteer": "1.8.0",
  "tsconfig-paths-jest": "0.0.1",
  "tslint": "^5.12.0",
  "tslint-react": "^3.6.0"
}
```

**Comment by manucorporat** [comment]
I has been renamed to:
`ToggleChangeEventDetail`
or 
`CheckboxChangeEventDetail`

I am going to update the CHANGELOG, thanks for the issue!
