### ISSUE TITLE
4.0.0-rc.1 missing svg in node_modules/@ionic/angular/dist/ionic/svg 

### ISSUE THREAD

**Issue by jegged** [ionic-team/ionic#17031]
![2019-01-10 153715](https://user-images.githubusercontent.com/5977574/50953230-b9e35980-14ed-11e9-8e5b-4d819d4eae68.jpg)
after upgrade to rc1, can not find the svg in the modues path.

the code from angular.json
{
         "glob": "**/*.svg",
         "input": "node_modules/@ionic/angular/dist/ionic/svg",
         "output": "./svg"
 }

**Comment by paulstelzer** [comment]
Thanks! Please look into the changelog -> https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#angularjson

It's the following:
```

             {
               "glob": "**/*.svg",
               "input": "node_modules/ionicons/dist/ionicons/svg",
               "output": "./svg"
             }
```
