### ISSUE TITLE
[4.0.0-rc.1] Slides not working in production build

### ISSUE THREAD

**Issue by abennouna** [ionic-team/ionic#17033]
# Bug Report

**Ionic version:**
[x] **4.0.0-rc.1**

**Current behavior:**
- In dev mode, no issue.
- In prod mode, the `ion-slides` is populated, but is not functional (swiping, pagination...). The following error can be seen in the console:
**`Unhandled Promise rejection: c.data is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: c.data is not a function`**
![capture d ecran 2019-01-10 a 09 55 14](https://user-images.githubusercontent.com/1470318/50957520-51c55100-14b6-11e9-8d80-a0a9358137a9.png)

**Expected behavior:**
Slides functional in production build.

**Steps to reproduce:**
- Start a new blank rc.1 app
- Include the demo code from the docs (problem is reproductible with other `ion-slides` templates)
- Build for production (`ionic build --prod`)
- Start app in browser — tested in:
  - Chrome 71.0.3578.98 (Official Build) (64 bits)
  - Safari 12.0.1 (13606.2.104.1.2)
  - Firefox 64.0.2 (64 bits)

**Related code:**
_home.page.ts_
```javascript
export class HomePage {
  public slideOpts = {
    effect: 'flip',
  };
}
```

_home.page.html_
```html
<ion-slides pager="true" [options]="slideOpts">
  <ion-slide>
    <h1>Slide 1</h1>
  </ion-slide>
  <ion-slide>
    <h1>Slide 2</h1>
  </ion-slide>
  <ion-slide>
    <h1>Slide 3</h1>
  </ion-slide>
</ion-slides>
```

**Other information:**
Not an issue in rc.0

**Ionic info:** 
```
Ionic:

   ionic (Ionic CLI)             : 4.7.1 (~.nvm/versions/node/v10.12.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v10.12.0 (~/.nvm/versions/node/v10.12.0/bin/node)
   npm    : 6.4.1
   OS     : macOS High Sierra
```

**Comment by abennouna** [comment]
@toriphes was faster (#17032) I think this one can be closed 😁

**Comment by paulstelzer** [comment]
RC.1 isn't working in produciton mode, I can confirm and collect everything under one issue -> #17034
