### ISSUE TITLE
ionic 4 rc1 : ion-icons not working in iOS

### ISSUE THREAD

**Issue by charlesRms** [ionic-team/ionic#17035]
# Bug Report

**Ionic version:**
[x] **4 rc1**

**Current behavior:**
ion-icons are not displayed in iOS 10.3.3. Icons are used in pages and in components, none of them are displayed

**Expected behavior:**
the icons are displayed

**Steps to reproduce:**
use icons in html
ionic cordova build ios
run on device from xcode

**Other information:**

**Ionic info:** 

```

Ionic:

   ionic (Ionic CLI)             : 4.7.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.13
   @capacitor/core           : 1.0.0-beta.13

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 15 other plugins)

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.3.0 (/usr/local/Cellar/node/10.3.0/bin/node)
   npm        : 6.1.0
   OS         : macOS Mojave
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

**Comment by dylanvdmerwe** [comment]
Did you follow the [breaking changes changelog](https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md) notes when upgrading to RC1?

**Comment by paulstelzer** [comment]
Few seconds ago I run my app on iOS (no production build because this is broken) and all icons are shown

**Comment by charlesRms** [comment]
@dylanvdmerwe I did not... It's working like a charm.
