### ISSUE TITLE
ion-content overflow scroll issue

### ISSUE THREAD

**Issue by glongchi** [ionic-team/ionic#17047]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I have a bespoke dynamic form(kz-dynamic-form ) that is generated off JSON config data. This works ok. For large forms part of the form that flows off the screen is hidden( i.e the portion of form the overflows the parent ion-content view area) is hidden instead of being visible with a y-scrollable axis.

**work around**
For the overflow part to be visible, I have to add style: overflow-y: scroll; to enable scrolling across the y-axis. This styling, however, add the ugly default scrolling pane

**Expected behavior:**

When child content overflows the parent ion-content view area it  should automatically enable y-axis scrolling

**Steps to reproduce:**

**Related code:**
```
    <ion-conent padding>
      <kz-dynamic-form [title]="" [config]="config" (submitted)="onSubmit($event)"> </kz-dynamic-form>
    </ion-conent>
```

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 9 other plugins)

System:

   Android SDK Tools : 25.2.5 (C:\Android\sdk)
   NodeJS            : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Comment by manucorporat** [comment]
ion-content already scroll in the y-axis. I believe it's something wrong in your CSS, just check any example only, you will see ion-content scrolls by default.

Also, in the provided code example, you are using `ion-conent`, it should be `ion-content`.

**Comment by glongchi** [comment]
sorry, a careless overlook on my part was doing this in a hurry. Thanks @manucorporat
