### ISSUE TITLE
[FR] Disable the backdrop catching clicks when hidden

### ISSUE THREAD

**Issue by sneko** [ionic-team/ionic#17040]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Hi,

When using the PopoverController I put the property `showBackdrop: false` to hide the translucent background around the popover. It works well but it feels weird from an user perspective to click 2 times to trigger another button on the page.

I think it could be great to have a settings to disable the hidden backdrop catching click events.

Like that if a user clicks on a navigation button while having a popover opened, the navigation will be triggered and there is no need to:
1. Click the first time aside the popover to close it
2. Click on the appropriate element

Thank you 👍 ,

EDIT: I guess it would also allow the user to scroll.

**Comment by manucorporat** [comment]
so... do you still want the click to dismiss the popover and trigger the click in the appropriate element?

**Comment by sneko** [comment]
Yes, but maybe we could let the developer the possibility to hide the popover manually?

I mean, in my case I use the popover to show additional information about points on a chart. So even if I click on another area (like copying text, trigger a button without switching the page, scrolling...), it could be interesting for me to keep the popover opened.

But in the case the user clicks on a navigation button or something that requires the popover to be closed, I would need to close it.

Maybe like for the "WillDismiss" and "DidDismiss", we could have something like "BackdropClicked" (= the zone around the popover) receiving as parameter the area clicked, and then depending on my own code logic I could or not dismiss the popover.

I hope it's not confusing. I hope others will give their thoughts and if it makes sense 😄

**Comment by manucorporat** [comment]
I think you are looking for the `backdropDismiss` property of popover:
https://github.com/ionic-team/ionic/tree/master/core/src/components/popover#properties

```
popoverController.create({
...
  backdropDismiss: false,
  showBackdrop: false,
});
```

**Comment by sneko** [comment]
Hi @manucorporat,

This property enabled by default doesn't prevent me from cliking 2 times to trigger a button "under" the hidden backdrop (that's the point I think annoying for the user).

The most important feature for me would be to let clicks "pass through" the hidden backdrop to directly trigger underlying elements, or even more, make the user able to scroll while the popover is opened.
