### ISSUE TITLE
bug(navigation): when opening from url, and has default-back-href, no can-go-back class

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#17044]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
If you open a page from a page, there is a "can-go-back" class added to the app.
If you open from a link, and the page has a back button, with default href to go back, it doesn't add that class.

**Expected behavior:**
That class should be added in that scenario

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (C:\Users\amitm\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.12
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic 5.2.1, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 15 other plugins)

System:

   NodeJS : v10.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by paulstelzer** [comment]
Thanks for the issue! Could you first update to the latest @ionic/angular version and second add a repo so we can check?

**Comment by manucorporat** [comment]
Hi Amit! I am sorry but the class is an implementation detail and could go away anytime. It's only added when there is at least a page to go back in the stack.
