### ISSUE TITLE
could not remove file (code EBUSY) google-services

### ISSUE THREAD

**Issue by wanderarce** [ionic-team/ionic#17046]
hello, when I perform the following steps I can not remove or proceed with the build:

ionic cordova platform add android
ionic cordova run android
ionic cordova platform remove android

 In the console displays the

> rm:could not remove file (cod EBUSY): C:\Users.../google-services.json

This way it is necessary to restart the machine at all times when this behavior occurs

npm: 6.4.1
node: 8.12.0
ionic: 4.7.1
SO: windows 7

`{
  "name": "falacampogrande",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~6.1.1",
    "@angular/core": "~6.1.1",
    "@angular/forms": "~6.1.1",
    "@angular/http": "~6.1.1",
    "@angular/platform-browser": "~6.1.1",
    "@angular/platform-browser-dynamic": "~6.1.1",
    "@angular/router": "~6.1.1",
    "@ionic-native/app-version": "^5.0.0-beta.21",
    "@ionic-native/base64": "^5.0.0-beta.21",
    "@ionic-native/browser-tab": "^4.15.0",
    "@ionic-native/call-number": "^5.0.0-beta.21",
    "@ionic-native/camera": "^5.0.0-beta.21",
    "@ionic-native/core": "5.0.0-beta.21",
    "@ionic-native/diagnostic": "^5.0.0-beta.21",
    "@ionic-native/file": "^5.0.0-beta.21",
    "@ionic-native/file-chooser": "^5.0.0-beta.21",
    "@ionic-native/file-path": "^5.0.0-beta.21",
    "@ionic-native/file-picker": "^5.0.0-beta.21",
    "@ionic-native/firebase": "^5.0.0-beta.23",
    "@ionic-native/geolocation": "^5.0.0-beta.21",
    "@ionic-native/in-app-browser": "^5.0.0-beta.21",
    "@ionic-native/splash-screen": "5.0.0-beta.21",
    "@ionic-native/sqlite": "^5.0.0-beta.21",
    "@ionic-native/status-bar": "5.0.0-beta.21",
    "@ionic/angular": "4.0.0-beta.7",
    "angularfire2": "^5.1.1",
    "call-number": "1.0.1",
    "com-badrit-base64": "^0.2.0",
    "cordova-plugin-app-version": "0.1.9",
    "cordova-plugin-browsertab": "^0.2.0",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-file": "6.0.1",
    "cordova-plugin-filechooser": "1.0.1",
    "cordova-plugin-filepath": "1.4.2",
    "cordova-plugin-filepicker": "1.1.5",
    "cordova-plugin-firebase": "^2.0.5",
    "cordova-plugin-geolocation": "4.0.1",
    "cordova-plugin-inappbrowser": "~3.0.0",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^2.2.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "2.5.0",
    "cordova.plugins.diagnostic": "4.0.10",
    "core-js": "^2.5.3",
    "firebase": "^5.7.2",
    "moment-timezone": "^0.5.21",
    "mx.ferreyra.callnumber": "~0.0.2",
    "rxjs": "6.2.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.7.2",
    "@angular-devkit/build-angular": "~0.7.2",
    "@angular-devkit/core": "^0.7.5",
    "@angular-devkit/schematics": "~0.7.2",
    "@angular/cli": "~6.1.1",
    "@angular/compiler": "^6.1.10",
    "@angular/compiler-cli": "^6.1.10",
    "@angular/language-service": "^6.1.10",
    "@ionic/lab": "1.0.9",
    "@ionic/ng-toolkit": "^1.1.0",
    "@ionic/schematics-angular": "^1.0.7",
    "@types/jasmine": "^2.8.9",
    "@types/jasminewd2": "^2.0.5",
    "@types/node": "~10.9.2",
    "codelyzer": "~4.4.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-app-version": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-browsertab": {},
      "cordova-sqlite-storage": {
        "GEOLOCATION_USAGE_DESCRIPTION": "To locate you"
      },
      "cordova-plugin-camera": {},
      "cordova-plugin-file": {},
      "cordova-plugin-filechooser": {},
      "cordova-plugin-filepath": {},
      "cordova-plugin-filepicker": {},
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "To locate you"
      },
      "cordova.plugins.diagnostic": {},
      "mx.ferreyra.callnumber": {},
      "com-badrit-base64": {},
      "cordova-plugin-firebase": {}
    },
    "platforms": []
  }
}
`

**Comment by paulstelzer** [comment]
Thanks for your issue! This is not related to Ionic. I cannot say what going wrong but it seems that deleting the google-services.json is not possible from the platform folder
