### ISSUE TITLE
ion-input clearOnEdit not working

### ISSUE THREAD

**Issue by RobotBroer** [ionic-team/ionic#17055]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

ion-item clearOnEdit property has no effect. 

**Expected behavior:**

If property clearOnEdit is set then on selecting the input the current value of the input should be replaced by the new value being inserted. 

**Steps to reproduce:**

1. Set Property clearOnEdit on ion-input 
2. Set a value on the input
3. Set a new value on the input 

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/christo/Library/Android/sdk)
   ios-deploy        : 1.9.2
   NodeJS            : v11.6.0 (/Users/christo/.nvm/versions/node/v9.10.1/lib/node_modules/node/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

```

**Comment by paulstelzer** [comment]
You are right (can be easily check on the docs simulator -> https://beta.ionicframework.com/docs/api/input/ )
