### ISSUE TITLE
[4.0.0-rc.1] build --prod kills <ion-slides>

### ISSUE THREAD

**Issue by olivermuc** [ionic-team/ionic#17056]
# Bug Report

**Ionic version:**
[4.0.0-rc.1]

**Current behavior:**
run `ionic serve --prod` for a project that includes `<ion-slides>`

**Expected behavior:**
`ion-slides` elements should work.

**Steps to reproduce:**
run `ionic serve --prod` for a project that includes `<ion-slides>`

**Other information:**
I tried debugging the production code, and only found that the `<ion-slides>` element is not initialized at all, and hence doesn't function at all, the "slide child/object" is simply not instantiated. 

A wild guess: Since it works in dev-mode, I suspect the web packer to introduce the error.

**Ionic info:** 
```
Ionic:

   ionic (Ionic CLI)             : 4.7.1 (/Users/.../.npm-packages/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 18 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/.../Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.13.0 (/usr/local/Cellar/node@10/10.13.0/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by paulstelzer** [comment]
Production mode is not working in rc.1 (see https://github.com/ionic-team/ionic/issues/17034 ), but it's already fixed and rc.2 will be released very soon (hopefully today) :)

**Comment by olivermuc** [comment]
Thanks, a warning in the **Changelog** would have save me a ton of time -  unless I missed it.

**Comment by paulstelzer** [comment]
Good idea! I pinned the issue, so nobody will miss it ;)
