### ISSUE TITLE
Ionic 4 Folder Structure

### ISSUE THREAD

**Issue by mayurdandekar** [ionic-team/ionic#17052]
Hello,

I am using ionic framework since 2 years and i have knowledge of all the versions so far.
I found ionic 2 and 3 versions very helpful for development.
But i have recently gone through ionic 4 version and i didn't found the folder structure convenient.
And why you added routing again?
Please fix this, i would not want to move to ionic 4 with this folder structure.

**Comment by NG-tylerholden** [comment]
I liked the separated pages, components, directives folders project structure from ionic 3 better too especially when doing `ionic g page myPage` - Manually moving them is annoying

**Comment by paulstelzer** [comment]
Ionic 4 does not define any folder structure, it's using the framework folder structure. If you use Ionic with Angular, you get the Angular folder structure, but you can set the path on generating, e.g. `ionic g page page/myPage`. Ionic is just using the Angular compiler behind, so just search for Angular compiler and you will find all options you can use
