### ISSUE TITLE
ion-segment-buttton disabled property - when set to false, css does not update initially 

### ISSUE THREAD

**Issue by RobotBroer** [ionic-team/ionic#17054]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When switching between false and true for the disabled property on ion-segment-button, the opacity of the tab remains low, and only returns to 1 after selecting the tab. Giving the impression the tab is disabled while it is not.

**Expected behavior:**

Be able to apply the disable property of ion-segment-button true and false and instantly see the tab css opacity lower when disabled and apply back to 1 when enabled.

**Steps to reproduce:**

1. Set disabled property on ion-segment-button
2. bind disabled property to variable which can be interactively changed to true or false
3. When set to true the tab becomes active but the tab gives the impression of being disabled.
4. Select the tab, and see the opacity change back to normal.

**Related code:**

```
<ion-segment-button  [disabled]="!activateTab">
            <ion-icon name="card"></ion-icon>
            <ion-label>Payment</ion-label>
 </ion-segment-button>
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/default/Library/Android/sdk)
   ios-deploy        : 1.9.2
   NodeJS            : v11.6.0 (/Users/default/.nvm/versions/node/v9.10.1/lib/node_modules/node/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

```

**Comment by brandyscarney** [comment]
I'm sorry but I'm not understanding your steps to reproduce. Could you please provide a repository, codepen or plunker that has a minimal amount of code to reproduce this?

I created one in Codepen using Vanilla JS to try and reproduce: https://codepen.io/brandyscarney/pen/ebQNpq?editors=1010

**Comment by RobotBroer** [comment]
Apologies - Could not reproduce the error on another project, will check next time before logging, must be my shoddy css.
