### ISSUE TITLE
[4.0.0-rc.1] IonTabBar.selectedTab returns the original tab rather than selected one

### ISSUE THREAD

**Issue by jing-zhou** [ionic-team/ionic#17051]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

upon clicking a tab button, IonTabBar.selectedTab returns the original tab rather than the tab clicked
**Expected behavior:**

upon clicking a tab button, IonTabBar.selectedTab should return the clicked tab 
**Steps to reproduce:**

> ionic start myApp tabs --type=angular

replace 'tabs.page.ts" with the following contents
```
import { Component, OnInit, ViewChild } from '@angular/core';
import { IonTabBar } from '@ionic/angular';

@Component({
  selector: 'app-tabs',
  templateUrl: 'tabs.page.html',
  styleUrls: ['tabs.page.scss']
})
export class TabsPage implements OnInit {
  @ViewChild(IonTabBar) tabBar: IonTabBar;
  constructor() {}
  ngOnInit() {
    this.tabBar.el.onclick = () => {
      console.log(this.tabBar.selectedTab);
    };
  }
}
```

**Related code:**

[Github](https://github.com/jing-zhou/ion-tab-bar-selectedTab)
**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.7.1 (/home/wjz/.nvm/versions/node/v10.7.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v10.7.0 (/home/wjz/.nvm/versions/node/v10.7.0/bin/node)
   npm    : 6.5.0
   OS     : Linux 4.15

Environment:

   HTTP_PROXY  : http://127.0.0.1:37245/
   http_proxy  : http://127.0.0.1:37245/
   HTTPS_PROXY : http://127.0.0.1:37245/
   https_proxy : http://127.0.0.1:37245/

```

**Comment by paulstelzer** [comment]
I think it's because if you click on it, the tab is not changed yet. If you wait a bit and then check again for selected tab, it should be correct

**Comment by jing-zhou** [comment]
suppose there are 3 tabs: 'tab1', 'tab2', 'tab3'; and  'selectedTab' = 'tab1',
click on 'tab2', 'selectedTab' = 'tab1'
click on 'tab3', 'selectedTab' = 'tab2'
click on 'tab1', 'selectedTab' = 'tab3'
...
the 'IonTabBar.selectedTab' always changes one click behind;  I guess the status change and return are somehow  reversed;

you may try it by cloning from  [https://github.com/jing-zhou/ion-tab-bar-selectedTab](https://github.com/jing-zhou/ion-tab-bar-selectedTab)

**Comment by paulstelzer** [comment]
You could use `@ViewChild(IonTabs) tabs: IonTabs;` and then `this.tabs.onPageSelected($event)` in This event you find the selected tab: `$event.view.stackId`

Could you try that?

**Comment by paulstelzer** [comment]
Perfect. This is the way you should use it because the tab not instant change on click, instead you have to wait and this will reached with onPageSelected
