### ISSUE TITLE
[Request] Adding setVelocity for <ion-menu>

### ISSUE THREAD

**Issue by SnaiCrys** [ionic-team/ionic#17059]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
Requires setting the minimum swipe velocity required to open the side menu `<ion-menu>` (now 0.2).
**Describe Preferred Solution**
Make the property `setVelocity` the same as `maxEdgeStart`

**Comment by manucorporat** [comment]
what's your use case to change the min-velocity?

**Comment by SnaiCrys** [comment]
Actually, I want to set this parameter by self because right now this action takes so much time and needs to swipe for a long distance
