### ISSUE TITLE
Rendering issues when inspecting app with Chrome

### ISSUE THREAD

**Issue by ndrake** [ionic-team/ionic#17062]
# Bug Report

**Ionic version:**

[x] **4.0.0-rc.1**

**Current behavior:**

While I'm running an app on an Android device (Pixel 2 XL) and using Chrome's inspector (71.0.3578.98 on Mac OS Mojave), occasionally the app content won't be rendered properly (for example, text will be very blurry/pixelated).  

See the following screenshots:

Blurry image: 

![blurry](https://user-images.githubusercontent.com/73789/51042470-670baf80-158a-11e9-81cb-d2e01c8c71e4.png)

Good:

![good](https://user-images.githubusercontent.com/73789/51042550-991d1180-158a-11e9-8056-3229194e1ad3.png)

**Expected behavior:**

App will render without issues while inspecting with Chrome.

**Steps to reproduce:**

* Create new app based on sidemenu template: `ionic start inspecttest sidemenu --type=angular`
* Add Android platform: `ionic cordova platform add android`
* Build for Android: `ionic cordova build android`
* Copy APK to device
* Launch App on device
* Open Chrome inspector for the App: `chrome://inspect/#devices`
* Click around in the app. I've had success reproducing by opening the side menu and tap/dragging on one of the menu options.  Maybe it's related to the animations?

Once I close the inspector window, I'm unable to reproduce the issue

**Related code:**

None

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.7.1 (/Users/ndrake/.nvm/versions/node/v10.15.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/ndrake/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.15.0 (/Users/ndrake/.nvm/versions/node/v10.15.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by paulstelzer** [comment]
Thanks for your issue! This is normal behaviour and has nothing to do with Ionic. It's more related to cordova. Just close the inspector, the performance increase again and everything is normal
