### ISSUE TITLE
ionTabs getSelected() does not exist

### ISSUE THREAD

**Issue by NG-tylerholden** [ionic-team/ionic#17068]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

ionTabs getSelected() does not exist like the docs say it does

**Describe Preferred Solution**

add getSelected() or remove from docs

**Describe Alternatives**

**Related Code**

**Additional Context**

see <a href='https://github.com/ionic-team/ionic/issues/16933'>#16933</a>

**Comment by manucorporat** [comment]
where does the docs mention `getSelected()`?

**Comment by NG-tylerholden** [comment]
looks like it was changed today.

**Comment by NG-tylerholden** [comment]
on the ion-tabs documentation page...

**Comment by manucorporat** [comment]
`onPageSelected` is private, it's only public because AOT
