### ISSUE TITLE
[ionic4.rc1] [ios] ion-segment-button doesn't align with icon

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic#17069]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
If you have a row of segments with text and one with an icon, the new rc1 (upgraded from beta 13) has very different paddings setup.

One effect of this is that the icon only button is taller than the text only button:

![image](https://user-images.githubusercontent.com/1038062/51063334-70306700-15f2-11e9-921a-28df27276bbd.png)

**Expected behavior:**

It should align nicely more like this (screenshot from beta 13):

![image](https://user-images.githubusercontent.com/1038062/51063469-0d8b9b00-15f3-11e9-8753-4cee8511c85d.png)

**Steps to reproduce:**

Drop the snippet below into an app.

**Related code:**

```
    <ion-segment mode="ios">
          <ion-segment-button value="330" mode="ios">
            <ion-label>330ml</ion-label>
          </ion-segment-button>
          <ion-segment-button value="440" mode="ios">
            <ion-label>440ml</ion-label>
          </ion-segment-button>
          <ion-segment-button value="500" mode="ios">
            <ion-label>500ml</ion-label>
          </ion-segment-button>
          <ion-segment-button value="custom" mode="ios">
            <ion-icon name="create"></ion-icon>
          </ion-segment-button>
    </ion-segment>  
```
Note that wrapping the icon in an `ion-label` does make the row align nicely but makes the icon crazy small:

![image](https://user-images.githubusercontent.com/1038062/51063451-f482ea00-15f2-11e9-88fa-721b7e1acb3d.png)

However, the docs have been updated for the `ion-label` wrapper and dont include it around the `ion-icon`:

https://github.com/ionic-team/ionic/blob/master/core/src/components/segment/readme.md

**Other information:**

**Ionic info:** 

```

Ionic:

   ionic (Ionic CLI)             : 4.7.1 (C:\Users\rtpha\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by paulstelzer** [comment]
Thanks for the issue! You are right, I can confirm it.

As a workaround you can set the min-height and the icon yourself by css, e.g. so:

```
ion-segment-button {
    min-height: 30px;

    ion-icon {
        font-size: 20px;
    }
}
```
![chrome_2019-01-12_09-09-14](https://user-images.githubusercontent.com/20501666/51070931-c67cc480-1649-11e9-8db1-6d05cb87ee83.jpg)

I cannot say what the correct way is (with or without ion-label). I would prefer something like that (keep in mind the following is an idea and is currently not working:

```
    <ion-segment-button value="custom">
      <ion-icon slot="start" name="create"></ion-icon>
      <ion-label>Test</ion-label>
    </ion-segment-button>
    <ion-segment-button value="custom">
      <ion-icon slot="icon-only" name="create"></ion-icon>
    </ion-segment-button>
```

I labeled it as needs design decision. So we will wait for an official statement :)

**Comment by santoshyadav198613** [comment]
Hi @brandyscarney ,

Is it still open, can i take this issue.

**Comment by brandyscarney** [comment]
@santoshyadav198613 Yes it is still open, if you'd like to take a look that would be great, thank you!

**Comment by santoshyadav198613** [comment]
Hi @brandyscarney ,
Was a small css fix, let me know if any changes needed.
