### ISSUE TITLE
Ionic 4 problem on iOS Safari

### ISSUE THREAD

**Issue by DarisIT** [ionic-team/ionic#17064]
Hi,
testing a simple Desktop webapplication,  I encounter problems with the "ion-menu" in Safari 10.0.3.
With the following code, I get an empty menu with no overlay:

```
<ion-app>
  <ion-menu contentId="mycontent" side="start" menuId="first">
    <ion-header>
      <ion-toolbar color="primary">
        <ion-title>Start Menu</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content>
      <ion-list>
        <ion-item>Menu Item</ion-item>
        <ion-item>Menu Item</ion-item>
        <ion-item>Menu Item</ion-item>
      </ion-list>
    </ion-content>
  </ion-menu>
  
  <ion-content id="mycontent" ><ion-header>
    <ion-toolbar>
      <ion-buttons slot="start">
        <ion-menu-button autoHide="false"></ion-menu-button>
      </ion-buttons>
      <ion-title>Back Button</ion-title>
    </ion-toolbar>
  </ion-header>
 </ion-content>
</ion-app>
```

**Framework Details:**

 

-   ionic (Ionic CLI)             : 4.7.1
-    Ionic Framework               : @ionic/angular 4.0.0-rc.1
-    @angular-devkit/build-angular : 0.11.4
-    @angular-devkit/schematics    : 7.1.4
-    @angular/cli                  : 7.1.4
-    @ionic/angular-toolkit        : 1.2.2

**Comment by paulstelzer** [comment]
Thanks for the issue! Did you a production build? Then please see this issue -> https://github.com/ionic-team/ionic/issues/17034

If you run `ng serve` and the problem occurs, we will look into it. Does other browsers have the same issue (e.g. Chrome)?

**Comment by DarisIT** [comment]
The same issue occour with the command ng serve, testing on iPhone 6 in browser Chrome and Safari.

**Comment by DarisIT** [comment]
### **Test on iPhone 6s (IOS 10.0.2), Chrome browser:**
![iphone6s_chromeinfo](https://user-images.githubusercontent.com/32907540/51102378-01643100-17df-11e9-96c0-a0caf98248c3.png)

### **Main Page (menù button is not visible):**
![iphone6s_chromemainpage](https://user-images.githubusercontent.com/32907540/51102379-01fcc780-17df-11e9-8982-6f54388de97e.png)

### **Open Menù:**
![iphone6s_chromeopenmenu](https://user-images.githubusercontent.com/32907540/51102380-01fcc780-17df-11e9-8050-b2bbb0176c08.png)

### **Same problem on Mac using Safari:**
![safarionmac](https://user-images.githubusercontent.com/32907540/51102381-01fcc780-17df-11e9-9280-40f542bdc119.png)

**Thanks for your help!**

**Comment by DarisIT** [comment]
Hi, 
on iPhone 6s - iOS 10.0.2 - Chrome 71, the problem also exists with the latest Ionic release:

**Tested with Starter template: sidemenuapp.**
Problem: sidemenu is not visible.

>   ionic (Ionic CLI)             : 4.9.0 
>    Ionic Framework               : @ionic/angular 4.0.0
>    @angular-devkit/build-angular : 0.12.3
>    @angular-devkit/schematics    : 7.2.3
>    @angular/cli                  : 7.2.3
>    @ionic/angular-toolkit        : 1.2.2

![sidemenu](https://user-images.githubusercontent.com/32907540/51678672-40fbfb80-1fdd-11e9-91b5-071bcb448e35.png)

**Comment by DarisIT** [comment]
Hi, 
I verified that if I set the “type” property of the “ion-menu” element to “overlay” and if I set the element “ion-content” with "style = 'height: 2000px '“the” sidemenu "is displayed correctly. Instead the overlay on the page is not displayed and therefore it is not possible to close the menu by clicking on the overlay.
Testing on an updated iPhone the page is displayed correctly without making changes to the starting template. The problem is that with the 10.0.2 version of ios it is not possible to update Chrome over the v.71.0.3578.89.

See code:

```
<ion-app>
  <ion-split-pane>
    <ion-menu type="overlay">
      <ion-header>
        <ion-toolbar>
          <ion-title>Menu</ion-title>
        </ion-toolbar>
      </ion-header>
      <ion-content style="height: 2000px">
        <ion-list >
          <ion-menu-toggle auto-hide="false" *ngFor="let p of appPages" >
            <ion-item [routerDirection]="'root'" [routerLink]="[p.url]">
              <ion-icon slot="start" [name]="p.icon"></ion-icon>
              <ion-label>
                {{p.title}}
              </ion-label>
            </ion-item>
          </ion-menu-toggle>
        </ion-list>
      </ion-content>
    </ion-menu>
    <ion-router-outlet main></ion-router-outlet>
  </ion-split-pane>
</ion-app>

```

**Comment by DarisIT** [comment]
Another problem if I try to set the "side" property of the "ion-menu" element to "end". It is not minimally considered and the menu is still displayed on the left.
