### ISSUE TITLE
hash

### ISSUE THREAD

**Issue by calidion** [ionic-team/ionic#17061]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Visiting https://vigcoin.org/ will direct url to https://vigcoin.org/tabs/home.
It is correct.
But direct visiting https://vigcoin.org/tabs/home will get a 404 from github pages.

**Expected behavior:**

Direct visiting https://vigcoin.org/tabs/home will succeed as visiting https://vigcoin.org/

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by manucorporat** [comment]
This is an issue with github pages, it self. I would suggest to use hash routing if your server does not support to resolve index.html instead of 404
