### ISSUE TITLE
[4.0.0-rc.1] ion-nav - broken back button animation [Safari / iOS]

### ISSUE THREAD

**Issue by daniel-7235** [ionic-team/ionic#17074]
# Bug Report

**Ionic version:**
[x] 4.0.0-rc.*

**Current behavior:**
After navigating back to a previous page, an ugly shadow appears in the middle of the header during the animation. This problem occurs only under Safari in iOS mode. Here's a video of the problem: https://www.dropbox.com/s/ghbhyrmx9ox8i7k/broken_back_button_animation.mov?dl=0

**Expected behavior:**
The animation should be same in Chrome and in Safari.

**Steps to reproduce:**
Open https://beta.ionicframework.com/docs/content/api/nav-demo.html?ionic:mode=ios in safari and navigate forth and back.

**Comment by paulstelzer** [comment]
Thanks for the issue! I think it's happening because the preview has not the best performance. Did you test it inside a REAL app (native or browser)? I would say there this should not happen
