### ISSUE TITLE
[v4, core] ion-chip doesn't inherit CSS4 variables values when shadowed

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#17078]
# Bug Report

**Ionic version:**
[x] **4.x** - CORE

**Current behavior:**
`ion-chip` used in shadowed component don't inherit the CSS4 variables values. For example, if I set an `ion-chip` color to `primary`, it will remains not styled

**Expected behavior:**
`ion-chip` should inherit styles in shadowed components too

**Related code:**

With Stencil:

Style OK:

```
@Component({
    tag: 'app-stopwatch-time',
    styleUrl: 'app-stopwatch-time.scss'
})
export class AppStopwatchTime {
    render {
      return <ion-chip color="primary"><ion-label>Hello</ion-label></ion-chip>
    }
}
```

Style NOT OK:

```
@Component({
    tag: 'app-stopwatch-time',
    styleUrl: 'app-stopwatch-time.scss',
    shadow: true // <-------------- ion-chip don't inherit styles
})
export class AppStopwatchTime {
    render {
      return <ion-chip color="primary"><ion-label>Hello</ion-label></ion-chip>
    }
}
```

**Other information:**

<img width="1125" alt="capture d ecran 2019-01-13 a 13 22 05" src="https://user-images.githubusercontent.com/16886711/51085256-fbb31080-1736-11e9-88a8-fade288cc90e.png">

<img width="1125" alt="capture d ecran 2019-01-13 a 13 21 35" src="https://user-images.githubusercontent.com/16886711/51085262-08cfff80-1737-11e9-9141-9c86d144f16d.png">

**Comment by brandyscarney** [comment]
This is actually a problem with the `color` styles only in any component that is inside of shadow DOM. Because the styles for color are global, they won't apply if the component is used inside of a shadow component. See this issue for more details: https://github.com/ionic-team/ionic/issues/14840

**Comment by peterpeterparker** [comment]
@brandyscarney you are right, it's a duplicate of https://github.com/ionic-team/ionic/issues/14840

as there is no solution and it's a bad practice, I close my issue

thx for your feedback
