### ISSUE TITLE
[ionic4.rc1] ion-segment-button doesn't inherit ion-segment mode="ios"

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic#17070]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

In Beta 13 I had an `<ion-segment mode="ios" ...>` and it applied it to all the segment-buttons, now after updating to rc1, to recreate the same visual effect I have to add `mode="ios"` to all of the `<ion-segment-buttons>` as well.

**Expected behavior:**

I think setting the mode on the segment should apply to all segment-buttons as well shouldn't it?

**Steps to reproduce:**

**Related code:**

In beta 13 this would make a row of ios style pill segments:

```
    <ion-segment mode="ios">
          <ion-segment-button value="330">
            330ml
          </ion-segment-button>
          <ion-segment-button value="440">
            440ml
          </ion-segment-button>
          <ion-segment-button value="500">
            500ml
          </ion-segment-button>
          <ion-segment-button value="custom">
            <ion-icon name="create"></ion-icon>
          </ion-segment-button>
    </ion-segment>  
```

Gives this:

![image](https://user-images.githubusercontent.com/1038062/51063641-c3ef8000-15f3-11e9-8587-48369194c189.png)

After upgrading to rc1 I added the `<ion-label>` around them:

```
    <ion-segment mode="ios">
          <ion-segment-button value="330">
            <ion-label>330ml</ion-label>
          </ion-segment-button>
          <ion-segment-button value="440">
            <ion-label>440ml</ion-label>
          </ion-segment-button>
          <ion-segment-button value="500">
            <ion-label>500ml</ion-label>
          </ion-segment-button>
          <ion-segment-button value="custom">
            <ion-icon name="create"></ion-icon>
          </ion-segment-button>
    </ion-segment>  
```
Gives this:

![image](https://user-images.githubusercontent.com/1038062/51063808-80e1dc80-15f4-11e9-9b2f-94f4326dd54d.png)

Only adding the mode="ios" to every `ion-segment-button` is the only way to get it to display how it originally did:

```
    <ion-segment mode="ios">
          <ion-segment-button value="330" mode="ios">
            <ion-label>330ml</ion-label>
          </ion-segment-button>
          <ion-segment-button value="440" mode="ios">
            <ion-label>440ml</ion-label>
          </ion-segment-button>
          <ion-segment-button value="500" mode="ios">
            <ion-label>500ml</ion-label>
          </ion-segment-button>
          <ion-segment-button value="custom" mode="ios">
            <ion-icon name="create"></ion-icon>
          </ion-segment-button>
    </ion-segment>  
```

![image](https://user-images.githubusercontent.com/1038062/51063660-d5d12300-15f3-11e9-939d-b0407e97720c.png)

Note: I have raised as a separate issue the height / spacing / alignment differences between earlier betas and the new rc1 - #17069

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.7.1 (C:\Users\rtpha\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by paulstelzer** [comment]
Thanks for your issue! From my point of view, it's necessary to add mode="ios" to EVERY component you want to set the other style because each is indipendent. So the child will not inherit from the parent.

But I am not 100% sure, so maybe @brandyscarney can say more about it :)

**Comment by manucorporat** [comment]
Yep @paulstelzer is right! each component is self-contained and mode can't be inherit, there are important technical constraints that makes it hard for ion-segment-button to inherit the mode.

The mode must be applied to all the components involved!
