### ISSUE TITLE
[4.0.0-rc.1] Scrolling Bug [iOS / Safari]

### ISSUE THREAD

**Issue by daniel-7235** [ionic-team/ionic#17073]
# Bug Report

**Ionic version:**
[x] 4.0.0-rc.*

**Current behavior:**
After scrolling down and up again, the app freezes for a few seconds. This behavior only occurs on iOS devices. See the video for better understanding: https://www.dropbox.com/s/kflr3566fipetqg/scrolling_problem.mov?dl=0

**Expected behavior:**
App should not freeze after scrolling.

**Steps to reproduce:**
Open https://beta.ionicframework.com/docs/content/api/list-demo.html in safari on a iOS device.

**Comment by paulstelzer** [comment]
I can confirm this behaviour on my app. Have to wait a few moments, but cannot say what is the reason for this

**Comment by manucorporat** [comment]
Duplicated of https://github.com/ionic-team/ionic/issues/16929
