### ISSUE TITLE
4.0.0-rc.1 ion-datetime, event ionFocus does not work in PWA

### ISSUE THREAD

**Issue by bkarv** [ionic-team/ionic#17089]
# Bug Report

**Ionic version:**
[x] **4.0.0-rc.1**

**Current behavior:**
ionFocus event not fired when focus on Ion-Date time component. 

**Expected behavior:**
Presumably when clicking on ion-datetime within item, the ionFocus event should fire. 

**Steps to reproduce:**
See related code

**Related code:**

**HTML**       
```
<ion-item>
 <ion-datetime (ionFocus)="focusDatetime()" [pickerOptions]="customPickerOptions" class="word-wrap" max="2100-12-31" [(ngModel)]="value">
                </ion-datetime>
</ion-item>
```

**Component**
```
focusDatetime() {
    console.log('Focus')
      this.value = this.setupService.getTodayDate(0);
  }
customPickerOptions = {
    buttons: [{
      text: 'Cancel',
      role:'cancel',
      handler: () => console.log('Clicked Save!')
    }, {
      text: 'Save',
      handler: () => {
        console.log('Cancel Date');
      }
    }]
  }
  cancelDateTime() {
    this.value = null;
  }
```
  

**Other information:**
Ultimately I am trying to find a work around solution for the below bugs where ionic datetime starts on max date not on today's date. When datetime value is null, I am trying to set the value to today's date when the datetime has focus and hopefully the selector will display the today's date. If cancelled I can then return the value to null by setting up a cancel button via custompicker (as above code). 

https://github.com/ionic-team/ionic/issues/16436

https://github.com/ionic-team/ionic/issues/15792

**Ionic info:** 
```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.12.1
   @angular-devkit/schematics    : 7.1.2
   @angular/cli                  : 7.1.3
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 9 other plugins)

System:

   ios-deploy : 1.9.1
   NodeJS     : v10.10.0 (/usr/local/bin/node)
   npm        : 6.5.0
   OS         : macOS High Sierra


```

**Comment by paulstelzer** [comment]
Thanks for your issue! I tested with the latest dev build and there the focus event is triggered. So it's already fixed :)
