### ISSUE TITLE
ionic 4rc 1 - in forms -formGroup not working 

### ISSUE THREAD

**Issue by pioneersingh321** [ionic-team/ionic#17083]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```
![image](https://user-images.githubusercontent.com/10599858/51087894-f7aae100-177e-11e9-8205-8c1da3d02060.png)

login.html code

<ion-header>

  <ion-navbar>
    <ion-title>login</ion-title>
  </ion-navbar>

</ion-header>

<ion-content padding >
  <form  [formGroup]="loginForm"  style="margin-top: 50%" (submit)="onLogin()" >
    <ion-list>

      <ion-item class="radius_top">
        <ion-label >E-mail</ion-label>
        <ion-input type="email"  formControlName="email" ></ion-input>
      </ion-item>

      <ion-item>
        <ion-label >Password</ion-label>
        <ion-input type="password" formControlName="password"></ion-input>
      </ion-item>

       <ion-item text-center class="radius_bottom">
        <button ion-button round  [disabled]="!loginForm.valid" style="padding: 15px 40px;" >Login</button>
       </ion-item>
    </ion-list>

  </form>
</ion-content>

login.ts

import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { FormBuilder, FormControl, Validators } from '@angular/forms';
import { RestProvider } from '../../providers/rest/rest';

/**
 * Generated class for the LoginPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-login',
  templateUrl: 'login.html',
})
export class LoginPage {
 // Loginform: FormGroup;
 submitAttempt=false;
  constructor(public navCtrl: NavController, public navParams: NavParams,
    public fb:FormBuilder,public restProvider: RestProvider) {
  
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad LoginPage');
  }

  loginForm = this.fb.group({
   email: new FormControl('', Validators.compose([
    Validators.required,
    Validators.pattern('^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$')
    ])),
    password: ['', Validators.required],
  });

  onLogin() {
    this.submitAttempt = true;
    console.log(this.loginForm.value);
    // this.restProvider.login(this.loginForm.value).then(data => {
    //   console.log(data);
    // })
  }

}
app.module.ts

import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import { ListPage } from '../pages/list/list';
import {LoginPage} from '../pages/login/login';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { IonicStorageModule } from '@ionic/storage';
import { HttpClientModule } from '@angular/common/http';

import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { RestProvider } from '../providers/rest/rest';

@NgModule({
  declarations: [
    MyApp,
    HomePage,
    ListPage,
    LoginPage
  ],
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,HttpClientModule,
    IonicModule.forRoot(MyApp),
    IonicStorageModule.forRoot()
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    ListPage,LoginPage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler},
    RestProvider
  ]
})
export class AppModule {}

**Comment by paulstelzer** [comment]
Thanks for your Issue. For me it seems that you not updated correctly from Ionic 3 to Ionic 4

For example Ionic 4 do not use a @IonicPage decorator anymore , the imports of the following is wrong:

```
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
```

and I think you have to import the ReactiveFormsModule from Angular. All in all the issue is not related to Ionic.

If you need help, please take a look at the Ionic Forum :) Thanks!
