### ISSUE TITLE
[4.0.0-rc.1] The status bar renders as black text on a black background for Android versions >= Nougat (7.0)

### ISSUE THREAD

**Issue by moose4lord** [ionic-team/ionic#17086]
# Bug Report

**Ionic version:**
[x] 4.0.0-rc.1

**Current behavior:**
When deploying an Ionic 4 app to Android v7.0 (Nougat) or higher, the status bar renders as black text on a black background.

![image](https://user-images.githubusercontent.com/15672113/51089870-1a6ad480-1742-11e9-89fa-091b5f82cbd6.png)

**Expected behavior:**
Should render the status bar as white text on a black background, like Ionic 3.

**Steps to reproduce:**
Generate a starter app and deploy to a device or emulator running Android Nougat (7.0) or higher.

**Related code:**
The problem stems from this line of code in the app.component.ts file:
`this.statusBar.styleDefault();`
changing it to
`this.statusBar.styleLightContent();`
causes the status bar to render properly with white text on a black background.

![image](https://user-images.githubusercontent.com/15672113/51089893-48501900-1742-11e9-9a7f-d150a3f13656.png)

**Other information:**
The status bar renders properly with Ionic 3, which does not use the "cordova-plugin-statusbar" plugin, so maybe it's a bug in the statusbar plugin and not Ionic 4 per se.

**Ionic info:** 
```
Ionic:

   ionic (Ionic CLI)             : 4.7.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.12.1
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/klord/Library/Android/sdk)
   NodeJS            : v10.15.0 (/usr/local/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by paulstelzer** [comment]
Thanks for the issue! You could also use the cordova statusbar plugin in Ionic 3, just for your information ;)

What you described is related to cordova plugin statusbar because Ionic has no method to change the native status bar
