### ISSUE TITLE
Icons not working on 4.0.0-RC1

### ISSUE THREAD

**Issue by lampi87** [ionic-team/ionic#17084]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
After updating "@ionic/angular@4.0.0-rc.0" to rc.1 the icons aren't working anymore (at least on Android, not tested on iOS). In console I get error 404.
Back button icon, Tab icons,... are not visible

**Ionic info:** 
```
Ionic:

   ionic (Ionic CLI)             : 4.7.1 (C:\Users\...\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.12.1
   @angular-devkit/schematics    : 7.2.1
   @angular/cli                  : 7.2.1
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.0.0, (and 12 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\...\AppData\Local\Android\Sdk)
   NodeJS            : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Comment by paulstelzer** [comment]
Thanks for the issue! Did you changed the import like mentioned in the changelog breaking changes? https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#breaking-changes

If you do that it will working again on browser, android and ios :)

**Comment by jrayga** [comment]
My icons are also missing but i already changed my angular.json into this.

 "projects": {
    "app": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "progress": false,
            "outputPath": "www",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "assets"
              },
              {
                "glob": "**/*.svg",
                "input": "node_modules/ionicons/dist/ionicons/svg",
                "output": "./svg"
              }
            ]}
