### ISSUE TITLE
Ionic 4 - How to open URL in web browser instead of webview in app on Android App?

### ISSUE THREAD

**Issue by Aravin** [ionic-team/ionic#17081]
How to open URL in a web browser instead of webview in-app on Android App?

I used,

```
<ion-button  href="https://stackoverflow.com">StackOverFlow</ion-button>
```

The URL is opening in the in-app browser, I need to open an android system's default browser.

I have gone through the official document, I couldn't find useless information from there.

1. https://beta.ionicframework.com/docs/api
2. https://beta.ionicframework.com/docs/components#button
3. https://beta.ionicframework.com/docs/api/button/

**Comment by paulstelzer** [comment]
I would make it inside the ts file and then use _system as target on window.open. But this is more for the support forum and not an issue :)
