### ISSUE TITLE
ion icon not working in 4.0.0-rc.1 if npm audit fix called against 2 vulnerabilities 

### ISSUE THREAD

**Issue by AmbroiseVuaridel** [ionic-team/ionic#17097]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

ion icons not visible if npm audit fix
**Expected behavior:**

ion icons visible
**Steps to reproduce:**

download ionic-team's conference-app : https://github.com/ionic-team/ionic-conference-app
run npm i;npm audit fix;ionic cordova build ios;ionic serve;
icons show in the ionic serve opened in firefox or chrome on localhost:8100 but not on the simulator of ios. if ionic build is ran and deployed by a node server, icons cannot be seen as well
**Related code:**

```
-
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.7.1 (/Users/ambroise/.nvm/versions/node/v11.1.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.12.1
   @angular-devkit/schematics    : 7.1.2
   @angular/cli                  : 7.1.0
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 5 other plugins)

System:

   NodeJS : v11.1.0 (/Users/ambroise/.nvm/versions/node/v11.1.0/bin/node)
   npm    : 6.5.0
   OS     : macOS Mojave
   Xcode  : Xcode 10.1 Build version 10B61

```

**Comment by manucorporat** [comment]
It probably breaks some deps, we will update ionicons. Thanks for the issue!

**Comment by AmbroiseVuaridel** [comment]
any update? still not icon showing with below versions, if I go back to "@ionic/angular": "4.0.0-rc.0" icons come back,

    "@angular/animations": "^7.2.0",
    "@angular/common": "7.2.2",
    "@angular/core": "7.2.2",
    "@angular/forms": "7.2.2",
    "@angular/http": "~7.2.0",
    "@angular/platform-browser": "7.2.2",
    "@angular/platform-browser-dynamic": "7.2.2",
    "@angular/pwa": "^0.12.1",
    "@angular/router": "7.2.2",
    "@angular/service-worker": "7.2.2",
    "@ionic-native/core": "5.0.0",
    "@ionic-native/in-app-browser": "5.0.0",
    "@ionic-native/splash-screen": "5.0.0",
    "@ionic-native/status-bar": "5.0.0",
    "@ionic/angular": "4.0.0",
    "@ionic/ng-toolkit": "1.1.0",
    "@ionic/schematics-angular": "1.0.7",
    "@ionic/storage": "^2.2.0",
    "cordova-android": "^7.1.4",
    "cordova-browser": "^5.0.4",
    "cordova-ios": "^4.5.5",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^3.0.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "core-js": "^2.5.3",
    "rxjs": "6.3.3",
    "zone.js": "^0.8.26"

**Comment by paulstelzer** [comment]
@AmbroiseVuaridel Please take a look at the breaking changes. I summarized here -> https://github.com/ionic-team/ionic/issues/17019#issuecomment-452828443
