### ISSUE TITLE
TypeError: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by eric812** [ionic-team/ionic#17092]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Lazy load modal component , build it with "ng serve --aot",  the  modal component create is failure . angularDelegete is undefined . but run is ok with  "ng serve" .
![image](https://user-images.githubusercontent.com/11305981/51101580-2758f800-1816-11e9-873c-381296a9f178.png)

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

Ionic:

   ionic (Ionic CLI)             : 4.7.1 (C:\Users\eric\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.12.1
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (F:\android_sdk\sdk)
   NodeJS            : v8.9.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.2.0
   OS                : Windows 10

**package.json:** 
 "dependencies": {
    "@angular/common": "~7.1.4",
    "@angular/core": "~7.1.4",
    "@angular/forms": "~7.1.4",
    "@angular/http": "~7.1.4",
    "@angular/platform-browser": "~7.1.4",
    "@angular/platform-browser-dynamic": "~7.1.4",
    "@angular/router": "~7.1.4",
    "@ionic-native/core": "5.0.0-beta.21",
    "@ionic-native/splash-screen": "5.0.0-beta.21",
    "@ionic-native/status-bar": "5.0.0-beta.21",
    "@ionic/angular": "4.0.0-rc.1",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "bowser": "^1.9.4",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^3.0.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "core-js": "^2.5.4",
    "js-md5": "^0.7.3",
    "ngx-cookie-service": "^2.1.0",
    "ngx-translate-multi-http-loader": "^2.1.2",
    "rxjs": "6.3.3",
    "timers": "^0.1.1",
    "x2js": "^3.2.3",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.11.4",
    "@angular-devkit/build-angular": "^0.12.1",
    "@angular-devkit/core": "~7.1.4",
    "@angular-devkit/schematics": "~7.1.4",
    "@angular/cli": "~7.1.4",
    "@angular/compiler": "~7.1.4",
    "@angular/compiler-cli": "~7.1.4",
    "@angular/language-service": "~7.1.4",
    "@biesbjerg/ngx-translate-extract": "^2.3.4",
    "@ionic/angular-toolkit": "~1.2.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.12.0",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.12.0",
    "typescript": "~3.1.6"
  },

**Comment by sante85** [comment]
please you can add HoldingDetailModalComponent code, because in my modal page i have problem to open.

thanks

**Comment by sante85** [comment]
this.loaderAndSaveService.showModal(ModalImage, {'headImage': headImage}).subscribe();

// showModal call
return fromPromise(this.modalCtrl.create({
      component: component,
      componentProps: componentProps
    })).pipe(flatMap((modal: HTMLIonModalElement) => {
      this.modal = modal;
      return fromPromise(modal.present());
    }));

is present as entryComponent and import module

**Comment by sante85** [comment]
@Component({
  selector: 'modal-image',
  templateUrl: 'modal-image.html'
})
export class ModalImage implements AfterViewInit {
  @Input()
  public headImage: string;

  constructor() {

  }

  public close() {
  }

  ngAfterViewInit(): void {
  }
}

**Comment by sante85** [comment]
@NgModule({
  declarations: [
    ModalImage,
  ],
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    IonicModule,
    AngularHalModule.forRoot(),
    TranslateModule.forChild({
      loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [HttpClient]
      }
    }),
    RouterModule.forChild(
      [{
        path: '',
        component: ModalImage
      }])
  ]
})
export class ModalImageModule {
}

**Comment by paulstelzer** [comment]
aot is not working in rc.1 (see #17034). This issue is already fixed, but you have to wait until rc.2.

If you need aot support, revert back to rc.0
