### ISSUE TITLE
Ionic v4 BETA Issue in - InAppBrowser

### ISSUE THREAD

**Issue by dpadilla20** [ionic-team/ionic#17100]
Hello,
My application is showing issue when i will add "InAppBrowser" in provider.
$ ionic cordova plugin add cordova-plugin-inappbrowser
$ npm install --save @ionic-native/in-app-browser

![screen shot 2019-01-14 at 11 53 51 am](https://user-images.githubusercontent.com/2941957/51127269-18ad1980-17f3-11e9-92ca-91df890fb460.png)

IONIC INFO
<img width="826" alt="screen shot 2019-01-14 at 11 55 28 am" src="https://user-images.githubusercontent.com/2941957/51127401-61fd6900-17f3-11e9-9426-4335bdd06ace.png">

**Comment by paulstelzer** [comment]
Thanks for the issue! I am using InAppBrowser too and have no problems with it. 

Keep in mind that you have to install the beta version ( `npm install --save @ionic-native/in-app-browser@beta` ) and then you have to import with ngx at the end:

`import { InAppBrowser } from '@ionic-native/in-app-browser/ngx';`
