### ISSUE TITLE
NavCtroller navigateForward and navigateBack broken after refactor by commit #8ee9205

### ISSUE THREAD

**Issue by kevin-barrientos** [ionic-team/ionic#17103]
**4.0.0-rc.1:**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**
The methods ```navigateForward``` and ```navigateBack``` of the ```NavController``` returns void instead of returning the value returned by ```navigate```. See commit https://github.com/ionic-team/ionic/commit/8ee9205629cfa432d36f5b7e5617fac65734b1b4#diff-68c0efda98168f58059a80de770871e5

This is a breaking change not listed in the release notes.

**Expected behavior:**
In Ionic **4.0.0-rc.0** these methods returned a promise that resolved when the navigation was successfull. These is usefull to close dialogs or menus after a navigation has been completed. 

**Steps to reproduce:**
1. Start a fresh new project with two pages.
2. Inject NavController on the first page and use it to navigate forward (i.e. ```this.navCtrl.navigateForward('secondPage').then(() => console.log('succeded'))```. 

**Related code:**

- Ionic 4.0.0-rc.0 NavController source code:

```
  navigateForward(url: string | UrlTree | any[], options: NavigationOptions = {}) {
    this.setDirection('forward', options.animated, options.animationDirection);
    if (Array.isArray(url)) {
      return this.router!.navigate(url, options);
    } else {
      return this.router!.navigateByUrl(url, options);
    }
  }
```
- Ionic 4.0.0-rc.1 NavController source code 

```
  navigateForward(url: string | UrlTree | any[], options: NavigationOptions = {}) {
    this.setDirection('forward', options.animated, options.animationDirection);
    this.navigate(url, options);
  }

  navigate(url: string | UrlTree | any[], options: NavigationOptions) {
    if (Array.isArray(url)) {
      return this.router!.navigate(url, options);
    } else {
      return this.router!.navigateByUrl(url, options);
    }
  }
```

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.7.1 (C:\Users\Kevin Barrientos\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.12.1
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : android 7.1.2
   Cordova Plugins       : not available

System:

   NodeJS : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by manucorporat** [comment]
Thanks for the issue! already created a PR that fixes it: https://github.com/ionic-team/ionic/pull/17106
