### ISSUE TITLE
White screen of death on build - Starter Template

### ISSUE THREAD

**Issue by NG-tylerholden** [ionic-team/ionic#17105]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When building platform and then deploying, several assets are net::ERR_FILE_NOT_FOUND
By building I mean `ionic cordova build (platform)`
Running/live reload works fine.

This happens on starter tabs app with the below ionic info.
Occurs for atleast iOS and Browser platforms.

**Expected behavior:**

no white screen of death.

**Steps to reproduce:**

tried updating plugins, changing the base tag to "." (which fixes the asset location issue) but then it messes up the router.

**Related code:**

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.8.0
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 4 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v11.4.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61
```

**Comment by d3vhound** [comment]
Getting the same error with every starter project. Might have something to do with the build system and relative paths.

**Comment by paulstelzer** [comment]
Thanks for the issue! As said earlier rc1 is not working in production build (see here -> #17034). It's already fixed, but you have to wait until next release. Then everything should work again :)

**Comment by NG-tylerholden** [comment]
This does not seem to be fixed in rc2

**Comment by paulstelzer** [comment]
Could you make a screenshot of the error? I have multiple apps created with Ionic (build for Android, iOS and PWA) and could you reproduce it

**Comment by NG-tylerholden** [comment]
Trying to debug right now. Must be a cordova plugin we have or something because the starter app works now.

**Comment by NG-tylerholden** [comment]
Was cordova code push plugin in case anyone cares. Can't wait for capacitor to be more stable.
