### ISSUE TITLE
(ionChange) - unexpected behavior

### ISSUE THREAD

**Issue by kamenkurtev** [ionic-team/ionic#17123]
# Bug Report

**Ionic version:**
[x] **4.0.0-rc.0**

**Current behavior:**
(ionChange) trigger event without user interaction

**Expected behavior:**
(ionChange) should trigger event after user interaction

**Steps to reproduce:**

```
// Toggle or checkbox
// <ion-toggle (ionChange)="changeStatus($event)" [(ngModel)]="status"></ion-toggle>

status = true;

ngOnInit() {
  // this case work
  // this.status = false;
  
  // fetch status from a server
  // trigger change event without user interaction
  setTimeout(() => {
     this.status = false;
   }, 1000);
}

changeStatus($event) {
  // result: unnecessary request to the server
}
```

**Comment by manucorporat** [comment]
This is the expected behaviour, ionChange is emitted whatever the value of any input changes, no matter how it changed :)

**Comment by kamenkurtev** [comment]
In my case I have a confirm dialog in change status method. It opens when a page is refreshed. How should I prevent that?
