### ISSUE TITLE
[4.0.0-rc0-1] iOS 10 Tabs not working and sidepanel is blank

### ISSUE THREAD

**Issue by Silvest89** [ionic-team/ionic#17127]
**Current behavior:**
Please see screenshot
![simulator screen shot - iphone 5s - 2019-01-15 at 22 03 47](https://user-images.githubusercontent.com/2388338/51209824-7899e200-1911-11e9-905c-138b95a9b518.png)
![simulator screen shot - iphone 5s - 2019-01-15 at 22 03 52](https://user-images.githubusercontent.com/2388338/51209825-7899e200-1911-11e9-9b10-0bb21be4f5a3.png)

Everything works from iOS 11. Tested both on devices and emulators :)

**Expected behavior:**
I expect the side panel to be properly working and the tabs layout:P

You will get the same output using the ionic starter projects "tabs" and "sidemenu"

**Comment by supperdsj** [comment]
same issue here
