### ISSUE TITLE
Ripple effect not working properly

### ISSUE THREAD

**Issue by lucia-blanco** [ionic-team/ionic#17143]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When clicking on _ion-segment-button_ it creates `<div class="ripple-effect">`, but too many (up to 26), without deleting previous divs in other _ion-segment-button_ elements, making it impossible to read the tag after 10 clicks or so.

![screenshot_2019-01-17 ionic app 1](https://user-images.githubusercontent.com/32088542/51318187-e81ae900-1a59-11e9-8aab-77d59c90a69e.png)

**Expected behavior:**

Creating the `<div class="ripple-effect">` when clicking _ion-segment-button_, and deleting it after a few milliseconds.

**Steps to reproduce:**

**Related code:**

```
<ion-segment [(ngModel)]="segment" (click)="function()">
    <ion-segment-button value="first" >First</ion-segment-button>
    <ion-segment-button value="second">Second</ion-segment-button>
    <ion-segment-button value="third">Third</ion-segment-button>
</ion-segment>
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.7.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v8.11.0 (/usr/local/bin/node)
   npm    : 5.6.0
   OS     : Linux 4.15
```

**Comment by redwolf2** [comment]
Can't reproduce. Try to update to angular 4.0.0-rc.2

**Comment by lucia-blanco** [comment]
I tried updating and it still doesn't work, this is what happens in the Ionic DevApp
file:///home/lucia/Downloads/Screenshot_2019-01-17%20Ionic%20App(1).png.part

**Comment by lucia-blanco** [comment]
I tried updating and it didn't work. This is what happens in the Ionic DevApp
![img_3021](https://user-images.githubusercontent.com/32088542/51332773-a485a680-1a7c-11e9-9eef-9bf9e8193196.gif)

**Comment by paulstelzer** [comment]
I can confirm this issue, BUT it's hard to reproduce - sometimes it happens, sometimes not :(

**Comment by lucia-blanco** [comment]
It didn't fix mine.
