### ISSUE TITLE
[Regression][4.0.0-rc.2] Select interface popover broken

### ISSUE THREAD

**Issue by hakimio** [ionic-team/ionic#17142]
# Bug Report

**Ionic version:**
[x] **4.0.0-rc.2**

**Current behavior:**
Select with interface set to "popover" results in an error when upgrading from RC0 to RC1:

> Select interface cannot be a "popover" without passing an event. Using the "alert" interface instead.

**Expected behavior:**
Select with interface set to "popover" to work

**Steps to reproduce:**
- Create select with interface popover
```html
    <ion-select
        interface="popover"
        [value]="'this-month'"
    >
      <ion-select-option [value]="'this-month'">This Month</ion-select-option>
      <ion-select-option [value]="'last-month'">Last Month</ion-select-option>
    </ion-select>
```
- Click on the select in the app.

**Other information:**
The code above used to work fine in RC0.

**Ionic info:** 
```
Ionic:
   ionic (Ionic CLI)             : 4.6.0
   Ionic Framework               : @ionic/angular 4.0.0-rc.2
   @angular-devkit/build-angular : 0.12.2
   @angular-devkit/schematics    : 7.2.2
   @angular/cli                  : 7.2.2
   @ionic/angular-toolkit        : 1.2.2

System:
   NodeJS : v10.1.0
   npm    : 6.5.0
   OS     : Windows 10
```

**Comment by brandyscarney** [comment]
Thank you! Added a PR for this: https://github.com/ionic-team/ionic/pull/17146

Will get this merged when the build & tests pass and into rc.3.
