### ISSUE TITLE
[4.0.0-rc.2] usage of router-outlet instead of ion-router-outlet breaks the layout

### ISSUE THREAD

**Issue by EnricoVogt** [ionic-team/ionic#17140]
# Bug Report

**Ionic version:**
4.0.0-rc.2

**Current behavior:**
When you create a new project "sidemenu" with the ionic-cli and replace ion-router-outlet with router-outlet, the layout breaks

**Expected behavior:**
since the description of the ion-router-outlet component states to behave exactly like the router-outlet except for the differences for a "stacked-navigation" and for "animations", the expected behavior would be that using router-outlet does not break the layout

**Steps to reproduce:**
1. Create a "sidemenu" app with ionic cli 4.7.1
2. replace ion-router-outlet with router-outlet

**Related code:**
app.component.html
```
<ion-app>
  <ion-split-pane>
    <ion-menu>
      <ion-header>
        <ion-toolbar>
          <ion-title>Menu</ion-title>
        </ion-toolbar>
      </ion-header>
      <ion-content>
        <ion-list>
          <ion-menu-toggle auto-hide="false" *ngFor="let p of appPages">
            <ion-item [routerDirection]="'root'" [routerLink]="[p.url]">
              <ion-icon slot="start" [name]="p.icon"></ion-icon>
              <ion-label>
                {{p.title}}
              </ion-label>
            </ion-item>
          </ion-menu-toggle>
        </ion-list>
      </ion-content>
    </ion-menu>
    <router-outlet main><router-outlet> <!-- this line breaks the layout -->
  </ion-split-pane>
</ion-app>
```

**Comment by EnricoVogt** [comment]
Thanks for your replay. I removed 
`{ provide: RouteReuseStrategy, useClass: IonicRouteStrategy },`
But encounter now the problem that it still stack all pages into the DOM. But this is probable because i `use this.router.navigate(['home'])` instead of `[routerDirection]="'root'" [routerLink]="[p.url]"`. Is there an option to set the routerDirection programaticly?

**Comment by paulstelzer** [comment]
I created my own class (Service) for it. So I can fastly switch if I want to use Ionic navcontroller or normal Angular router. I don't know if there is a setting to set the routerDirection to root by default

**Comment by paulstelzer** [comment]
I think this issue has to be closed because it's important to use ion-router-outlet because it adds some necessary styles. To set routerDirection to root by default, could you add a feature request?
