### ISSUE TITLE
[RC.2] ion-searchbar: search icon disappears when focussing the input

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic#17151]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When focussing an `ion-searchbar`, the search icon disappears.

<img src="https://user-images.githubusercontent.com/3410759/51365515-8637ad80-1b45-11e9-9db4-1b023c67f84a.png" width="519">

**Expected behavior:**

The search icon should remain visible.

**Steps to reproduce:**

| RC.1 | RC.2 |
| - | - |
| [codepen.io/simonhaenisch/pen/dwBPwJ](https://codepen.io/simonhaenisch/pen/dwBPwJ) | [codepen.io/simonhaenisch/pen/EGBaMW](https://codepen.io/simonhaenisch/pen/EGBaMW) |

**Related code:**

```
<ion-searchbar />
```

**Other information:**

**Ionic info:** 

```
https://unpkg.com/@ionic/core@4.0.0-rc.2/dist/ionic.js
```

**Comment by manucorporat** [comment]
fixes by https://github.com/ionic-team/ionic/pull/17154
