### ISSUE TITLE
@Ionic/angular 4.0.0: EventEmitter doesn't emit to parent component

### ISSUE THREAD

**Issue by pairmix** [ionic-team/ionic#17159]
````
Ionic:

   ionic (Ionic CLI)             : 4.8.0 (C:\Users\lbzc4600\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.12.0
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.1.4, browser 5.0.4
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (C:\Users\lbzc4600\AppData\Local\Android\Sdk)
   NodeJS            : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 7
````
Angular EventEmitters doesn't emit to parent component

git clone https://github.com/pairmix/IonicBlankWithEventEmitters.git
npm install

I added angular code example (https://angular.io/api/core/EventEmitter) into ionic blank project.
````
    @Component({
      selector: 'zippy',
      template: `
      <div class="zippy">
        <div (click)="toggle()">Toggle</div>
        <div [hidden]="!visible">
          <ng-content></ng-content>
        </div>
     </div>`})
    export class Zippy {
      visible: boolean = true;
      @Output() open: EventEmitter<any> = new EventEmitter();
      @Output() close: EventEmitter<any> = new EventEmitter();
     
      toggle() {
        this.visible = !this.visible;
        if (this.visible) {
          this.open.emit(null);
        } else {
          this.close.emit(null);
        }
      }
    }
````
````
<zippy (open)="onOpen($event)" (close)="onClose($event)"></zippy>
````

But Angular EventEmitters doesn't emit to parent component.

I don't know why.

**Comment by manucorporat** [comment]
I tested your repo and it works perfectly, both alerts() are called when the components opens and closes.

Closing since this issue is not related with Ionic, but angular :)

**Comment by pairmix** [comment]
@manucorporat
Are you sure it works perfectly ?
First click must generate 2 alerts: "emit open"  and "open"
Second click must generate 2 alerts: "emit close" and "close"

**Comment by manucorporat** [comment]
@pairmix Alert() pauses the execution of JavaScript until the alert is closed. Do not use alert() and you will see it works fine.
https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-alert

**Comment by pairmix** [comment]
Impossible to let it work, event is not propagated.
onOpen($event) and onClose($event) are never called.
