### ISSUE TITLE
[4.0.0-rc.2] ion-icon not showing in Ionic DevApp & Capacitor Android

### ISSUE THREAD

**Issue by rahadur** [ionic-team/ionic#17169]
# Bug Report

**Ionic version:**

[x] **4.0.0-rc.2**

**Current behavior:**

Ion-Icon not showing on **Ionic DevApp** & **Capacitor Android Platform** but perfectly work on **Web Browser**.

**Expected behavior:**

Ion-Icon must be show in all platform or device.

**Steps to reproduce:**

1. Create a new ionic 4 app using **Sidemanu** template add some menu with ion-icon and update Ionic 4 to  4.0.0-rc.2.
2. Run command `ionic serve -c`
3. Open you Ionic DevApp App in your android device.
4. Build and Open Ionic project into **Android Studio** run app in your physical device.

**Ionic info:** 

```
Ionic:                                                                                             
                                                                                                   
   ionic (Ionic CLI)             : 4.8.0 (C:\Users\Rahadur\AppData\Roaming\npm\node_modules\ionic) 
   Ionic Framework               : @ionic/angular 4.0.0-rc.2                                       
   @angular-devkit/build-angular : 0.12.2                                                          
   @angular-devkit/schematics    : 7.2.2                                                           
   @angular/cli                  : 7.2.2                                                           
   @ionic/angular-toolkit        : 1.2.2                                                           
                                                                                                   
Capacitor:                                                                                         
                                                                                                   
   capacitor (Capacitor CLI) : 1.0.0-beta.13                                                       
   @capacitor/core           : 1.0.0-beta.13                                                       
                                                                                                   
System:                                                                                            
                                                                                                   
   NodeJS : v10.5.0 (C:\Program Files\nodejs\node.exe)                                             
   npm    : 6.5.0                                                                                  
   OS     : Windows 10
```

**Comment by shaaafi** [comment]
"ion-icon" is not working after i have upgraded from ionic 4 rc.0 to ionic 4 rc.2

**Comment by paulstelzer** [comment]
@shaaafi Did you read the breaking changes? or look here -> https://github.com/ionic-team/ionic/issues/17019#issuecomment-452828443

**Comment by rahadur** [comment]
@paulstelzer thank you. this [#17019 (comment)](https://github.com/ionic-team/ionic/issues/17019#issuecomment-452828443)  solution fixed my problem.

**Comment by CreativeArtDesign** [comment]
> "ion-icon" is not working after i have upgraded from ionic 4 rc.0 to ionic 4 rc.2

Hi, how did you upgrade the rc0 to rc.2 i can not find any comandline for that?

**Comment by paulstelzer** [comment]
@CreativeArtDesign like usual - `npm update` or `npm install @ionic/angular@latest` or changing the version in package.json and run `npm install`
