### ISSUE TITLE
[Ionic 4 rc.2] ion-toggle is not working with Reactive Forms

### ISSUE THREAD

**Issue by marlonpatrick10** [ionic-team/ionic#17171]
# Bug Report

**Ionic version:**

[x] **4.x** (rc.0, rc.1 and rc.2)

**Current behavior:**

ion-toggle is not working with Reactive Forms. Even defining a formControlName in the ion-toggle does not seem to respond to any event and thus the FormControl is not updated (invalid, dirty, touched, etc).

**Expected behavior:**

The FormControl associated with the ion-toggle should respond to the changes made in the ion-toggle in order to update fields such as invalid, dirty, touched.

**Steps to reproduce:**

Create a formGroup with a formControl bound to an ion-toggle. Notice that the formControl does not react to any ion-toggle state modification.

**Related code:**

```
export class TestPage {

  pageFormGroup: FormGroup;

  constructor(formBuilder: FormBuilder) {

    this.pageFormGroup = formBuilder.group(
      {
        agree: [false]
      },
      { updateOn: 'blur' }
    );
  }

  test(){
    console.log('Testing...');
  }
}

<ion-content>

  <form [formGroup]="pageFormGroup" (ngSubmit)="test()">
    <ion-list>

      <ion-item>
        <ion-toggle formControlName="agree"></ion-toggle>
        <ion-label>Agree</ion-label>
      </ion-item>

      <p>
          pageFormGroup.agree.value: {{pageFormGroup.get('agree').value}}
          pageFormGroup.agree.dirty: {{pageFormGroup.get('agree').dirty}}
          pageFormGroup.agree.pristine: {{pageFormGroup.get('agree').pristine}}
          pageFormGroup.agree.touched: {{pageFormGroup.get('agree').touched}}
      </p>

      <ion-row>
        <ion-col>
          <ion-button type="submit" expand="block" size="large">Test</ion-button>
        </ion-col>
      </ion-row>
    </ion-list>
  </form>
</ion-content>
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.8.0 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.2
   @angular-devkit/build-angular : 0.12.2
   @angular-devkit/schematics    : 7.2.2
   @angular/cli                  : 7.2.2
   @ionic/angular-toolkit        : 1.2.2

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.13
   @capacitor/core           : 1.0.0-beta.13

System:

   NodeJS : v10.15.0 (/usr/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.15

```

**Comment by manucorporat** [comment]
I cant' reproduce the problem you are reporting, can you share some source code? I created a new tests using ReactiveForm and ion-toggle works. The value of the form changes.

**Comment by marlonpatrick10** [comment]
I did some tests and I noticed 2 situations:

1 - FormBuilder with {updateOn: 'blur'}
In this case, none of the properties of the formControl appear to be updated: value, dirty, pristine, touched.

2 - FormBuilder with {updateOn: 'change'}
In this case, some properties of the formControl are updated (value, dirty, pristine) whereas formControl.touched is NOT updated.

**Comment by CreativeArtDesign** [comment]
How do i update the Rc version to the latest?
Is there any comandline for that? I am new at this.
