### ISSUE TITLE
Ion back button not showing in rc0 - rc2

### ISSUE THREAD

**Issue by WHeesters** [ionic-team/ionic#17187]
# Bug Report

**Ionic version:**
[x] **4.8.0**

**Current behavior:**
Since rc0 my ion-back-buttons stopped showing up. I've created a new project and added a back button, but there it doesn't show up either.

**Expected behavior:**
For the ion-back-button to show up (and work) when used.

**Steps to reproduce:**

Running the following project:
[repo](https://github.com/WHeesters/backButtonTest)
And navigating to the testpage, the back button won't show up even though it should.

**Related code:**

```
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button class="back-button"></ion-back-button>
    </ion-buttons>
    <ion-title>test</ion-title>
  </ion-toolbar>
</ion-header>
```

**Other information:**
I haven't seen anyone else with this issue. I've already asked on the ionic slack but no one had the same issue.

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.8.0 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v8.15.0 (/usr/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.15

```

**Comment by nathantaal** [comment]
```
<ion-header>
  <ion-toolbar>
    <ion-title>Hide specific cards from deck</ion-title>
    <ion-buttons slot="start">
      <ion-back-button  defaultHref="/tabs/(settings:settings)"></ion-back-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>
```
this is working for me on rc0, rc1 and rc2

**Comment by WHeesters** [comment]
Thanks for your reply. 

While looking at the changelogs I noticed a breaking change that I'd missed:

**[ANGULAR] href does not cause Angular Router to navigate**
For consistency sake, the href attribute of ion-button, ion-item and ion-anchor no longer
trigger navigation using the Angular’s Router,instead use angular’s [routerLink]:

```
- <ion-button href="/path/to/page">
+ <ion-button routerLink="/path/to/page">
```

**Comment by paulstelzer** [comment]
Thanks for the issue! Please keep in mind to add a defaultHref, if you want a back button everytime a user visits this page. Otherwise a back button will only be shown if you pushed (navigate forward) a new page

**Comment by nathantaal** [comment]
> Thanks for the issue! Please keep in mind to add a defaultHref, if you want a back button everytime a user visits this page. Otherwise a back button will only be shown if you pushed (navigate forward) a new page

There was a time that without a default href navigating didn't work (Early early Ionic 4) but for me there always should be a back button ;)
