### ISSUE TITLE
Ionic 4.0.0-beta.15 - <ion-toolbar mode="ios> not rendering properly on chrome & android.

### ISSUE THREAD

**Issue by epicazo** [ionic-team/ionic#17189]
# Bug Report

**Ionic version:**
```
ionic (Ionic CLI)             : 4.8.0 
Ionic Framework               : @ionic/angular 4.0.0-beta.15
@angular-devkit/build-angular : 0.8.8
@angular-devkit/schematics    : 0.8.8
@angular/cli                  : 6.2.8
@ionic/angular-toolkit        : 1.2.1
```

**Current behavior:**
When forcing the `<ion-toolbar>` to `mode="ios"`, on android devices and ionic serve in chrome, the toolbar elements are not displayed properly. But when forcing the mode ios in `app.module.ts` with the `IonicModule.forRoot({mode:"ios"})` there is no problem

**Expected behavior:**
The toolbar should have the same display on android & ios devices

**Steps to reproduce:**
Start a new project (I used the sidemenu project), add `color="primary"` and `mode="ios"` on the `<ion-toolbar>` element in home.html

**Comment by manucorporat** [comment]
Could you share a screenshot, update to latest rc.2 and tell us which brower are you using?

**Comment by epicazo** [comment]
https://ibb.co/qJq7gKS

This is the result I have using the `ionic serve --lab` command in chrome Version 71.0.3578.98 but I have the same output when sending the app on my android phone.

Can't update to rc.2 yet because i have some dependencies with angular up to version 6 (angular google map) and this should be updated soon so I will try with it.
