### ISSUE TITLE
navAnimation Enter and Leave

### ISSUE THREAD

**Issue by JumBay** [ionic-team/ionic#17192]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
In `IonicConfig` there are properties for animation enter and leave like `actionSheetEnter/actionSheetLeave`, `alertEnter/alertLeave` ... but only one for `navAnimation`. I know we can manage to do so by checking `opts.enteringEl/leavingEl` from `TransitionOptions` but it's not really handy.

It also should be nice to have a specific animation when the user swipes to go back `navAnimationSwipeBack`? For exemple, on `md` mode, swiping to go back runs an animation that doesn't feel natural (it doesn't follow the finger), it should be like the one in `ios`.  

As mentioned #16829, could you export default AnimationBuilder you built?

Thanks

**Comment by liamdebeasi** [comment]
Hey there,

With the launch of Ionic Framework v5 we launched new animation docs that should give you a better idea of how to manage animations in your application: https://ionicframework.com/docs/utilities/animations

Also, for nav animations there is only one animation as you noted. We pass in `direction` into the options object so you can tell if you are navigating forwards or backwards.
