### ISSUE TITLE
[Ionic v4.0.0-rc.2] Virtual Scroll does not implement virtualTrackBy

### ISSUE THREAD

**Issue by shajeeck** [ionic-team/ionic#17190]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Implementing a virtual scroll with virtualTrackBy does not effect. But beta docs shows virtualTrackBy implementation.

**Expected behavior:**
virtualTrackBy was working as intended in ionic 3, expecting same with ionic 4

**Comment by lincolnthree** [comment]
same issue here. has this property name changed?

**Comment by lincolnthree** [comment]
Looks like this is just a docs issue. There is a "trackBy" property:

https://github.com/ionic-team/ionic/blob/master/angular/src/directives/virtual-scroll/virtual-scroll.ts#L89
