### ISSUE TITLE
Streaming media plugin doesn't work

### ISSUE THREAD

**Issue by Morbakos** [ionic-team/ionic#17205]
# Support Question

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Hi,

After successfully installing the component, when I run the application on my smartphone, I get an error message in the terminal telling me that I did not install the component. How do I do that?

**Comment by kensodemann** [comment]
This is most likely an issue with the plugin and not with Ionic. However, if you believe the issue has something to do with the Ionic framework and not a bug with the plugin, please fully fill out the bug report template and provide a sample application that demonstrates the issue, including a clear indication on why this is a framework issue.
