### ISSUE TITLE
Calendar widget not showing/allowing selection from correct number of days

### ISSUE THREAD

**Issue by brylie** [ionic-team/ionic#17203]
**Ionic version:**
[x] **4.x**

**I'm submitting a ...** 
[x ] bug report
[ ] feature request

**Current behavior:**
On 4.x docs site, the calendar day select is not updating with number of days in selected month, after changing month. E.g. if I open the calendar when a day in February is already selected and change to any other month, the max day value I can select is 28. Higher day numbers are visible, even when February is selected, which is a bit counter-intuitive.

**Expected behavior:**
When a month is selected, only the correct number of days would be visible. Any day in the correct range could be selected.

**Steps to reproduce:**
In Firefox for Android, open the 4.x docs. Navigate to the calendar widget docs. Interact with the calendar.

**Comment by manucorporat** [comment]
Which one is the calendar component? Which exact version of ionic are you using?

**Comment by paulstelzer** [comment]
Thanks for issue! I close this because we are aware of some issues to datetime (see #16630). 

Yours is a duplicate of #14233

**Comment by brylie** [comment]
Thanks. FWIW, I had some difficulty adding this on mobile, but thought it important nonetheless.
