### ISSUE TITLE
Android hardware back button doesn't work

### ISSUE THREAD

**Issue by aftabkhatri** [ionic-team/ionic#17200]
# Bug Report

**Ionic version:**

[x] **4.8.0**

**Current behavior:**
back from Page3 to page 2 using ion ion-back-button, now i use hardware back button then it go to page page3 and ion-back-button is hide.

Working well if use only hardware back button or ion-back-button, if used both together then not working.

**Expected behavior:**
back from Page3 to page 2 using ion ion-back-button, now i use hardware back button then it go to page page1.

**Other information:**

**Ionic info:** 
i used this all code :- https://medium.com/@reviloera.../ionic-framewok-4-hardware-back-button-9b45df233414
https://stackoverflow.com/questions/51700879/handling-hardware-back-button-in-ionic3-vs-ionic4/51729093#51729093

also used NavController and trigger ion-back-button by hardware backbutton.

```
Issue open back for :- https://github.com/ionic-team/ionic/issues/14803#issuecomment-436767639

Thanks in advance.

**Comment by paulstelzer** [comment]
Thanks for the issue! There were made some changes in the latest commits (https://github.com/ionic-team/ionic/pull/17182) - just install the latest dev build (`npm install @ionic/angular@4.0.0-dev.201901211351.59bd823`).

If you want to overwrite the default behaviour, you can also use:

```
this.platform.backButton.subscribeWithPriority(9999, () => {
// You decide what happens 
});
```

Would be nice if you could check again

**Comment by aftabkhatri** [comment]
i did this all boss, 
you can check using this step in browser.

Create page 1, page 2 , page 3
add button in page1 set routerLink for page2.
add button in page2 set routerLink for page3

now go to page 3 and click on ion-back-button. It will visit to page 2.
after this click on browser back button or hardwareback button it will go to page 3.
` this.platform.backButton.subscribe(async () => {
     
      if (this.router.url == '/startmain') {
        /* this.router.navigate(['/startmain'],{ replaceUrl: true });
        if(this.lastTimeBackPress==0){
          const alert = await  this.alertController.create({
            header: 'Confirm!',
            message: 'Do you want to exit the app?1',
            buttons: [
              {
                text: 'Cancel',
                role: 'cancel',
                cssClass: 'secondary',
                handler: (blah) => {
                 // this.router.navigate(['/startmain'],{ replaceUrl: true });
                  console.log('Confirm Cancel: blah');
                  this.lastTimeBackPress=1;
                }
              }, {
                text: 'Exit',
                handler: () => {       
                // this.platform.exitApp(); // Exit from app
                navigator['app'].exitApp(); // work in ionic 4
                }
              }
            ]
          });
          await alert.present();
        }else{
          navigator['app'].exitApp(); // work in ionic 4
        }*/
        navigator['app'].exitApp();

      }else if (this.routerOutlet && this.routerOutlet.canGoBack()) {
        this.routerOutlet.pop();
      }else {
        
         // this.platform.exitApp(); // Exit from app
         navigator['app'].exitApp(); // work in ionic 4
      }
    });`

**Comment by aftabkhatri** [comment]
subscribeWithPriority working well.
