### ISSUE TITLE
[Ionic v4.0.0-rc.0] ModalController doesn't allow navigation within itself

### ISSUE THREAD

**Issue by dani-inside** [ionic-team/ionic#17207]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When creating and presenting a modal view via ModalController, it is not possible to navigate within that modal, e.g. like navigating to another View within that Modal. When using the Router to navigate by URL, it will open that URL behind the modal instead of the modal itself.

**Expected behavior:**

When creating and presenting a modal view via ModalController and navigating by URL (or similar) the navigation should take place in the Modal, not in the main router outlet.

**Steps to reproduce:**

First open a page in a Modal:
```
 const loginModal = this.modalController.create({
        component: LoginPage
      });
      loginModal.then((modal) => {
        modal.present();
      });
```
Then navigate within that modal to a new page using the router:
```
this.router.navigateByUrl('/tests/products-list');
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.12.1
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.13
   @capacitor/core           : 1.0.0-beta.13

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 25.2.5 (/Users/<username>/Library/Android/sdk)
   ios-deploy        : 2.0.0
   NodeJS            : v8.12.0 (/usr/local/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by manucorporat** [comment]
No, you can't use the router to navigate inside a modal, however you can use the URL-less component `ion-nav` which allows you to have stack based navigation!
