### ISSUE TITLE
ion-input destroys vanilla-text-mask on focus

### ISSUE THREAD

**Issue by JCKodel** [ionic-team/ionic#17215]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I used the following code to create a mask-input for an ion-input, using https://github.com/text-mask/text-mask:

```
...
<ion-input type="tel" ref={(el: HTMLIonInputElement) => maskedInput(el, phoneMaskInput)} />
...
import maskInput from "vanilla-text-mask";

export function maskedInput(ionInputElement: HTMLIonInputElement, maskFunction: (value: string) => Array<string | RegExp>)
{
	if(!ionInputElement)
	{
		return;
	}

	ionInputElement.getInputElement().then((nativeInput: HTMLInputElement) =>
	{
		const anyNativeInput = <any>nativeInput;

		anyNativeInput.maskedController = maskInput({
			inputElement: nativeInput,
			mask: maskFunction,
			placeholderChar: "_",
			showMask: true,
		});

		nativeInput.addEventListener("ionInputDidUnload", ionInputDidUnload);

		const input = document.createElement("input");

		nativeInput.parentElement.appendChild(input);
		maskInput({ inputElement: input, mask: maskFunction, placeholderChar: "_", showMask: true });
	});
}
```
This is the result:
![image](https://user-images.githubusercontent.com/379339/51573161-464b3000-1e8f-11e9-8416-c7a6d7a0e069.png)

But, when I focus the ion-input, all the mask, events, etc. is cleaned (like there were never a mask input attached to it):

![image](https://user-images.githubusercontent.com/379339/51573208-74c90b00-1e8f-11e9-825f-5da69a2ca6b5.png)

The other mask input is a native HTML input element, just to make sure it's not a bug from someone else.

**Expected behavior:**

Everything I do with the native input element should be left untouched.

**Steps to reproduce:**

Apply the code above.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
ionic/core 4.0.0.rc.3
```

**Comment by kevenjson** [comment]
I have that same problem too 🙏

**Comment by JCKodel** [comment]
Is there any way to implement something like this?

```
<ion-input placeholder="Foo bar">
    <slot>
        <input type="text" onChange={(e) => this.works} />
    </slot>
</ion-input>
```
`<ion-input>` would detect and manipulate the native input automatically (but not interfere with my `onChange` event handler, for instance). Perhaps event bubbling could be used here somehow (it would be useful, for example, to block ion-input from changing the focus line beneath the component (I would just stop the event's propagation)).

**Comment by Aquima** [comment]
I also have that same problem. Solve it please.

**Comment by anthonyjuarezsolis** [comment]
It is a priority error, solve it please.

**Comment by JuanHuertaB** [comment]
Fix it please, it´s not a minor issue.
