### ISSUE TITLE
Please publish an npm update to @ionic/vue to bump the @ionic/core dependency version.

### ISSUE THREAD

**Issue by Giwayume** [ionic-team/ionic#17229]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When installing @ionic/vue version 0.0.1, the typescript build complains about multiple inheritance issues (typescript version 3.2.4).

**Expected behavior:**
Typescript should compile. Updating the @ionic/core dependency from 4.0.0-beta.12 to 4.0.0-rc.3 fixes this.

**Steps to reproduce:**
Initialize a typescript vue application with vue-cli and install @ionic/vue as a dependency.

**Ionic info:** 
```
Ionic:

   ionic (Ionic CLI) : 4.8.0 (/usr/local/lib/node_modules/ionic)

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/developer/Library/Android/sdk)
   NodeJS            : v10.15.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by dholth** [comment]
Is it correct for @modus/ionic-vue (recently updated) to send everyone to to @ionic/vue (updated months ago?)

**Comment by ilyen85** [comment]
I think not, the @modus/ionic-vue package is working better (but not perfect) than the @ionic/vue version. Can we get some help here, maybe some documentation or something.

What I have at the moment is not working too well, every tutorial I have found seems to be outdated.

**Comment by mhartington** [comment]
This should be fixed now with `@ionic/vue`.
