### ISSUE TITLE
Problems logging in

### ISSUE THREAD

**Issue by capgarrapata** [ionic-team/ionic#17223]
**Ionic version:**

[x] **4.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**
 When trying to log, after entering email and password screen refreshes.

**Expected behavior:**
 It would normally let me in.

**Steps to reproduce:**
 Go to https://creator.ionic.io and try to log in.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by jcesarmobile** [comment]
Should be fixed now, can you check?
