### ISSUE TITLE
repeat fast back, freeze  other tab page on ios

### ISSUE THREAD

**Issue by qingxo** [ionic-team/ionic#17237]
# Bug Report

**Ionic version:**
4.0.0

**Current behavior:**
Step1: navigating to a page with navigateForward, if I immediately go back to previous page.
Step2: repeat the Step1 for several time(4 or 6 maybe)
Step3: Click the other tab button, the tab page just don't change anymore, like freeze.
Step4: go back to the first tab ,repeat Step1 a time, then click the other tab button, all page show right.

Only show in the IOS, Android is work fine, web is also right. 
And the problem is sometime show quick, sometime is hard to reappear.

**Related code:**
to Detail page:
        this.navController.navigateForward(['/msg', { userId: this.userId, shoeId: this.shoeId }]);
back to tab page:
            this.navController.back();

**Ionic info:** 
Ionic:

   ionic (Ionic CLI)             : 4.9.0 (/Users/karas/.nvm/versions/node/v10.15.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.2
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 7.0.1
   Cordova Platforms     : android 7.1.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 16 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/karas/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.15.0 (/Users/karas/.nvm/versions/node/v10.15.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

**Comment by manucorporat** [comment]
Can you provide a repo case that reproduces the issue?

It’s hard for us to priorize the issue if we have to build our sample app trying to blindly reproduce your issue.

More if it happens randomly

**Comment by qingxo** [comment]
> Can you provide a repo case that reproduces the issue?
> 
> It’s hard for us to priorize the issue if we have to build our sample app trying to blindly reproduce your issue.
> 
> More if it happens randomly

Here is my code: https://github.com/qingxo/ionicTest.git.
You should install the app on the IOS, you will find the error. on web app  occur low probability. on android is ok.

**Comment by qingxo** [comment]
> Can you provide a repo case that reproduces the issue?
> 
> It’s hard for us to priorize the issue if we have to build our sample app trying to blindly reproduce your issue.
> 
> More if it happens randomly

[4.0.1] version ,the problem is not solved.
