### ISSUE TITLE
Some Ionic icons are missing in the V4 build

### ISSUE THREAD

**Issue by Bengejd** [ionic-team/ionic#17235]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
The icons do not display

**Expected behavior:**
The icons should display.

**Steps to reproduce:**
Add the related code to your build, and you'll see what I mean.
**Related code:**
```
    <ion-icon name="add"></ion-icon>
    <ion-icon name="arrow-dropdown"></ion-icon>
    <ion-icon name="close-circle"></ion-icon>
    <ion-icon name="close"></ion-icon>
    <ion-icon name="contacts"></ion-icon>
    <ion-icon name="heart"></ion-icon>
    <ion-icon name="home"></ion-icon>
    <ion-icon name="more"></ion-icon>
    <ion-icon name="navigate"></ion-icon>
    <ion-icon name="notifications"></ion-icon>
    <ion-icon name="search"></ion-icon>
    <ion-icon name="text"></ion-icon>
```
**Ionic info:** 
```
   ionic (Ionic CLI)             : 4.9.0 (/Users/bengejd/.npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v11.5.0 (/usr/local/Cellar/node/11.5.0/bin/node)
   npm    : 6.6.0
   OS     : macOS Mojave

```

Some of these are the most used icons, of the entire Ionic icons pack, so this is a major issue for those updating to V4 release.

**Comment by kensodemann** [comment]
What version of `@ionic/angular` did you upgrade your project from? If before rc.1, did you do this bit mentioned in the breaking changes here:

https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#400-rc1-2019-01-09


I just tried your code with a newly generated blank v4 app and it worked correctly.

**Comment by Bengejd** [comment]
Hmmm. I tried it in a new v4 app, and it wasn't working originally, then I disabled cache in the network, and it started working. Tried to do the same in my current V4 app, and it isn't fixing the issue, so I'm not sure what is going on anymore.

I upgraded from `@ionic/angular": "4.0.0-beta.18` to `@ionic/angular": "4.0.0`. I'll see if those build steps were already added now though.

**Comment by Bengejd** [comment]
The build step was not added. After adding it, everything was fixed. Thanks for the help!

**Comment by kensodemann** [comment]
Excellent!! Glad to hear it.
