### ISSUE TITLE
IonIcons 404 Error after upgrade

### ISSUE THREAD

**Issue by hvlg-blaire** [ionic-team/ionic#17230]
# Bug Report

**Ionic version:**

[x] **4.9**

**Current behavior:**

After running npm ionic i -g --save on a project the ionicons can not be found (404)

**Expected behavior:**

In Ionic version 4.8.0 icons would show up.

**Steps to reproduce:**

After running npm ionic i -g --save on a project the ionicons can not be found (404)
    "ionic": "^4.9.0",
    "ionicons": "^4.5.5",
**Related code:**

```
 <ion-icon name="medal"></ion-icon>
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.9.0
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.2
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
![ionicon-404](https://user-images.githubusercontent.com/45851367/51633384-86f28a00-1f1f-11e9-9130-c1d77a7e3ca2.PNG)

```

**Comment by hvlg-blaire** [comment]
Just the Ionic CLI. I went back and ran `npm i -g @ionic/angular` but still no luck

**Comment by zdennis** [comment]
I am having this issue on OSX as well. I updated both today. I tried reverted to ionic 4.8.0 but the problem has persists. I also downgrqaded @ionic/angular back to 4.0.0.rc.3 but still no luck. 

I am going to check my Angular version as well. That also got updated recently.

**Comment by manucorporat** [comment]
You have to update the angular.json to copy the icons into the final www:
https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#breaking-changes-2

**Comment by Yogeshk25** [comment]
I am also experiencing similar issue.

**This is working**
`<ion-icon name="checkmark-circle"></ion-icon>`

**This is not**
`<ion-icon name="checkmark-circle-outline"></ion-icon>`

**here is my Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.9.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v10.14.2 (/usr/local/bin/node)
   npm    : 6.5.0
   OS     : macOS Mojave
```

PS.
I also updated my angular.json file as suggested in release note of 4.0.0-rc.1 (BREAKING CHANGE)

**Comment by zdennis** [comment]
Thanks @manucorporat! That resolved the issue for me. You get all of the internet points today. 🎉

**Comment by brandyscarney** [comment]
<img width="378" alt="screen shot 2019-01-23 at 3 53 58 pm" src="https://user-images.githubusercontent.com/6577830/51636402-29fad200-1f27-11e9-8b2b-5856ac75f6e2.png">

The above is a new Ionic 4 blank project that includes these icons:

```
<ion-icon name="heart"></ion-icon>
<ion-icon name="medal"></ion-icon>
<ion-icon name="checkmark-circle"></ion-icon>
<ion-icon name="checkmark-circle-outline"></ion-icon>
```

**Comment by hvlg-blaire** [comment]
Thank you @brandyscarney  and @manucorporat. I added the breaking change and cleared cache and all is working again.
