### ISSUE TITLE
'disable' property on ActionSheetController button

### ISSUE THREAD

**Issue by not-a-designer** [ionic-team/ionic#17236]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Add an optional property to dynamically disable an actionsheet button 

**Describe Preferred Solution**

```
ActionsheetController.create({
    header: 'Header',
    buttons: [{
        text: 'Button',
        icon: 'home',
        disabled: true,  // defaults to FALSE if no value
        handler: () => console.log('handler')
    }]
})
```
**Describe Alternatives**

Have not found any solutions besides conditionally removing the disabled button

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the feature request. After discussing with the team, we have decided not to add this feature.

When adding features to the framework we try to follow the iOS and MD specs as closely as possible. There is nothing in either spec that calls for disabled action sheet buttons. The MD spec states that action sheet buttons should not inherit disabled states: https://material.io/design/interaction/states.html#disabled.

I am going to close this issue. Thank you!
