### ISSUE TITLE
[4.0.0] ion-button changes disabled state only once on Chrome

### ISSUE THREAD

**Issue by jeroenklein** [ionic-team/ionic#17246]
# Bug Report

**Ionic version:**
[x] **4.0.0**

**Current behavior:**
On Chrome (71.0.3578.98) the ion-button changes the disabled/enabled state only once.
On Safari and Firefox everything is working fine.

**Steps to reproduce:**
See https://codepen.io/jeroenklein/pen/GzpRrQ

**Related code:**
https://codepen.io/jeroenklein/pen/GzpRrQ

**Other information:**
Related issues: 

- https://github.com/ionic-team/ionic/issues/17193
- https://github.com/ionic-team/ionic/issues/16892

**Comment by Giwayume** [comment]
Not exactly. The button is being enabled again, however it doesn't look visibly enabled until you hover over it or tab to it. 

Looks like an issue with redraw.

**Comment by millerf** [comment]
I have the same issue with Ionic V4

**Comment by millerf** [comment]
For information, the only 'dirty' work around I found was to "change" the button on disable state.
It is ugly AF, but it works like a charm.
```
 <ng-container *ngIf="buttonValid">
                    <ion-button [disabled]="false" (click)="save()">
                        <ion-icon slot="icon-only" name="checkmark"></ion-icon>
                    </ion-button>
</ng-container>
<ng-container *ngIf="!buttonValid">
                    <ion-button [disabled]="true" (click)="save()">
                        <ion-icon slot="icon-only" name="checkmark"></ion-icon>
                    </ion-button>
</ng-container>

```

**Comment by millerf** [comment]
Maybe it should be linked with #17012 ?

**Comment by millerf** [comment]
HAppens on Android as well, btw

**Comment by bedinsky** [comment]
> For information, the only 'dirty' work around I found was to "change" the button on disable state.
> It is ugly AF, but it works like a charm.
> 
> ```
>  <ng-container *ngIf="buttonValid">
>                     <ion-button [disabled]="false" (click)="save()">
>                         <ion-icon slot="icon-only" name="checkmark"></ion-icon>
>                     </ion-button>
> </ng-container>
> <ng-container *ngIf="!buttonValid">
>                     <ion-button [disabled]="true" (click)="save()">
>                         <ion-icon slot="icon-only" name="checkmark"></ion-icon>
>                     </ion-button>
> </ng-container>
> ```

Thank you ! hiding and showing divs did the trick 
... but in my case is **ionic-angular 3.9.2**
I did not found anyone complaining for this issue and I'm pretty sure it arose a few months ago

**Comment by millerf** [comment]
@bedinsky I have seen similiar issues on the ionic forum dated way back... Not sure if it is only a few months old...

**Comment by manucorporat** [comment]
Seems like a bug introduced the chrome, the disabled styles are being removed, but Chrome does not update, idk what is going on

**Comment by millerf** [comment]
Yes, sounds like chrome doesn't repaint the button when the disabled state is changed...

**Comment by millerf** [comment]
@bedinsky I am starting to wonder if some code is not running outside the Angular Zone in Ionic...
It does look more and more like a Change Detection issue...

**Comment by jeroenklein** [comment]
As @manucorporat suspected, it's a Chrome bug...
With the new Chrome Version `72.0.3626.81` the bug seems to be resolved.
See https://codepen.io/jeroenklein/pen/GzpRrQ

**Comment by brandyscarney** [comment]
I can confirm this issue is working in latest Chrome. If anyone is still seeing it, please let me know, thanks!
