### ISSUE TITLE
Compiling with ionic react takes too long

### ISSUE THREAD

**Issue by stilren** [ionic-team/ionic#17249]
# Bug Report

**Ionic version:**
Ionic react (version 0.0.3)

**Current behavior:**
Compiling app takes a long time (1 min+) when referencing '@ionic/react' 

**Expected behavior:**
Compiling should take a second or two

**Steps to reproduce:**
create-react-app myapp (using CRA 2.1.3)
cd myapp
npm install @ionic/react @ionic/core
add to index.js:
```
import { registerIonic } from '@ionic/react';
registerIonic()
```
npm start

**Comment by kerosin** [comment]
Which NodeJS version are you running? There had been several issues regarding slow build times with node < 10 (e.g. https://github.com/ionic-team/ionic/issues/15868)

**Comment by stilren** [comment]
@kerosin actually upgrading nodejs got the compile time down to a manageable time (couple of secnds) - thanks!
