### ISSUE TITLE
Ionic Inline Calendar (Not a datepicker) with swipe feature to navigate forward and backward

### ISSUE THREAD

**Issue by tonyawad88** [ionic-team/ionic#17255]
# Feature Request
I have been an Ionic fan since Ionic 1 and have always wished you guys develop an ionic calendar, different from the Datepicker you have today. There are a couple options out there, but the finesse that you guys have for well-polished components, I haven't seen anywhere else.

It would be great to have the following features:

- [ ] Ability to swipe left / right to navigate to a future month or previous month (in month view, same for day / week / year view)
- [ ] Ability to show calendar view per day/ per week / per month / per year
- [ ] Ability to add multiple events per day and ability to customize event template
- [ ] Ability to tap a day to expand events inline on that particular day
- [ ] Theming 
- [ ] Internationalization

**Ionic version:**
[x] **4.x**

**Describe Alternatives**
The alternative today has been repos maintained by community members, with not that great of finesse with no swipe support. 

Please let me know if I should provide more info.
Cheers!

**Comment by SkogDev** [comment]
I agree, this would have been a great addition to the already excellent set of ionic components.
