### ISSUE TITLE
Color Generator missing in Docs

### ISSUE THREAD

**Issue by mateusduraes** [ionic-team/ionic#17254]
This is not a bug with Ionic code. My question is about the docs.
Seems like the Color Generator is no longer in the new docs.
Is this right?

**Comment by paulstelzer** [comment]
Yes, you are right. I will send it to the docs repo

You can still use the beta version -> https://beta.ionicframework.com/docs/theming/color-generator - but as you said in the new one ( https://ionicframework.com/docs/theming/color-generator/ ), it's missing
