### ISSUE TITLE
How to upgrade from ionic beta to ionic 4

### ISSUE THREAD

**Issue by Aravin** [ionic-team/ionic#17250]
How to upgrade from ionic beta to ionic 4

**Comment by jayordway** [comment]
They have included a migration guide in the documentation here:

https://ionicframework.com/docs/building/migration#migrating-from-ionic-3-0-to-ionic-4-0-overview

**Comment by paulstelzer** [comment]
`npm install @ionic/angular@latest` and don't forget to add Ionicons to angular.json ( https://github.com/ionic-team/ionic/issues/17019#issuecomment-452828443 )
