### ISSUE TITLE
Ionic v4 searchbar cancel Button is behind the search icon

### ISSUE THREAD

**Issue by ricrps** [ionic-team/ionic#17252]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Cancel button is appearing behind search icon

**Expected behavior:**
The searchicon disappears when the cancel button appears

**Related code:**
`<ion-content padding>
  <ion-searchbar showCancelButton></ion-searchbar>
</ion-content>`

**Example**
https://github.com/ricrps/ionic4-searchbar-issue

![image](https://user-images.githubusercontent.com/30167439/51699174-3b111500-1ff3-11e9-96de-d8a7a4a3f058.png)

**Comment by Giwayume** [comment]
Ionic is fluffy about desktop browser support, but they don't list any version of IE as supported at all.

https://ionicframework.com/docs/intro/browser-support/

**Comment by ricrps** [comment]
> Ionic is fluffy about desktop browser support, but they don't list any version of IE as supported at all.
> 
> https://ionicframework.com/docs/intro/browser-support/

I see the error even in device

**Comment by Giwayume** [comment]
@ricrps I was replying to TreatDarren about the "double cancel" issue mentioned.
