### ISSUE TITLE
 when opening from url, and set default-back-href, click invalid

### ISSUE THREAD

**Issue by kittencup** [ionic-team/ionic#17264]
# Bug Report

**Ionic version:**
Ionic:
   ionic (Ionic CLI)             : 4.9.0
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.2

System:
   NodeJS : v10.10.0
   npm    : 6.4.1
   OS     : macOS Mojave

**Current behavior:**
 when opening from url, and has default-back-href, click invalid

```
<ion-back-button
                    color="dark"
                    text="&nbsp;"
                    default-href="placeholder"
            ></ion-back-button>
```

**Speculate on the reasons**
https://github.com/ionic-team/ionic/blob/v4.0.0-rc.3/core/src/utils/theme.ts#L45

Because angular router is used, `win.document.querySelector('ion-router');` is null

**Comment by tobika** [comment]
same here. I had to add routerLink to make it work after a page reload.
`<ion-back-button default-href="/" routerLink="/"></ion-back-button>`

If I didn't put the `default-href` the back button would disappear.

**Comment by brandyscarney** [comment]
Angular properties should be written in camelCase. Please try using `defaultHref` and let me know if you are still seeing this issue. Thanks!
