### ISSUE TITLE
[4.0.0] External data files no longer seem to open

### ISSUE THREAD

**Issue by RHinderiks** [ionic-team/ionic#17265]
We load blocks of user created content in our app, these blocks sometimes contain links to excel files or images which we used to be able to click on and it would open the external browser with the file. Somehow along the beta -> rc -> stable line it broke and we can't seem to get it to work again. In xcode it throws an error saying its missing allow-intent for url=blob:... which seems fair but adding <allow-intent href="blob:*" /> to the config only solves the error being shown, when pressing a link nothing happens. On Android it shows the following error "Blocked (possibly sub-frame) navigation to non-allowed URL:" which seems a bit like the same error which would make sense.

We were wondering if anything has changed in the recent patches that could have caused this problem.

With best regards,
Robin

**Comment by manucorporat** [comment]
Can you please properly fulfil the issue template? how to reproduce this issue?

Seems like an issue related with cordova whitelist: https://cordova.apache.org/docs/en/latest/guide/appdev/whitelist/

**Comment by RHinderiks** [comment]
Trying to replicate this in a example proofed difficult. Just adding a <a href /> to an external xlsx seemed to work both on a fresh app, as well is my own app. However the links in my app i was referring to contain this in their href:  blob:http://localhost:8080/f2194f60-b5d2-42dd-aba3-70d329842d87

this also happens on web when using ionic serve however the port number is different then (and the browser downloads the file when clicked
