### ISSUE TITLE
 Implement Sidemenu in ionic 4 like in ionic 3

### ISSUE THREAD

**Issue by yasar-salim** [ionic-team/ionic#17262]
# Support Question

I installed ionic 4 default sidemenu app, when I navigate between menu pages i can go back to previous page by pressing back button. But in ionic3 default sidemenu app, we cant go back because setRoot is working. How to implement navigation like ionic3 in ionic4.
![screenshot 2019-01-25 at 4 05 18 pm](https://user-images.githubusercontent.com/20369407/51740830-28621300-20bb-11e9-9d42-74d96e6d7fed.png)
 

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Comment by yasar-salim** [comment]
@mlynch stucked in this for 2 days need help

**Comment by Giwayume** [comment]
It sounds like you want to use the `ion-nav` component instead of setting up the Angular router.

https://ionicframework.com/docs/api/nav

The other option would be to intercept the back button using a native API.

**Comment by brandyscarney** [comment]
Thanks for the issue! I added a new issue on the docs site to include navigating with menus in our documentation here: https://github.com/ionic-team/ionic-docs/issues/355

This is something we need to fix in the menu starter though, so I will keep this open.

**Comment by mhartington** [comment]
👋 hey @yasar-salim. Can you try adding ` replaceUrl="true"` to the menu item?

```
          <ion-menu-toggle auto-hide="false" *ngFor="let p of appPages">
            <ion-item routerDirection="root" [routerLink]="[p.url]"  replaceUrl="true">
              <ion-icon slot="start" [name]="p.icon"></ion-icon>
              <ion-label>
                {{p.title}}
              </ion-label>
            </ion-item>
          </ion-menu-toggle>
```

This seems to fix the behavior you're describing. I wonder if we should make this part of the 'routerDirection' input in the angular release? cc @manucorporat 

Our routerDirections could act as a short hand for predefined options

```
const BACK = {
  animation: true,
  direction: false,
  replaceUrl: true
}

const FORWARD = {
  animation: true,
  direction: 'forward',
  replaceUrl: false
}

const ROOT = {
  animation: false,
  direction: 'root' | 'swap',
  replaceUrl: true
}
```

**Comment by yasar-salim** [comment]
Hey @mhartington, 
Thanks for the reply and that works perfectly. How to do this programmatically?  nav.navigateRoot() is not working for me.

**Comment by mhartington** [comment]
Going to close this. IF there's anymore more questions, please post them on the ionic forum

http://forum.ionicframework.com
