### ISSUE TITLE
ion-icon not shown on firefox

### ISSUE THREAD

**Issue by daneyexpo** [ionic-team/ionic#17272]
# Bug Report

**Ionic version:**
"@ionic/angular": "4.0.0",

**Current behavior:**

Ionic icon will not work on firefox unless a src is provided.

`<ion-icon name="information-circle"></ion-icon>`

Will show up on chrome, but not firefox. Firefox will only register the element in the dom. You can change the background color, but the icon will not be there.

**Expected behavior:**

Icon should appear on firefox and chrome.

**Steps to reproduce:**

Use `<ion-icon name="information-circle"></ion-icon>` without `src` on the Angular `component.html`.

Check on firefox if it is rendered.

Check on chrome if it is rendered.

**Comment by paulstelzer** [comment]
Thanks for the issue! Ionicons is working well in Firefox, Chrome and other browsers, as well as in native apps. Please take a look here -> https://github.com/ionic-team/ionic/issues/17019#issuecomment-452828443

Then your icons will show in Firefox, too
