### ISSUE TITLE
<ion-button> link issue

### ISSUE THREAD

**Issue by aftabkhatri** [ionic-team/ionic#17273]
# Bug Report

**Ionic version:**

[x] **4.0.0**
cli : 4.9.0

**Current behavior:**
`<ion-button  color="light" expand="block" shape="round" fill='solid' class="lgbtn" href="/home" >Login</ion-button>`
this is not working, if we use "href" then <ion-back-button> not visible in home page.
You mention "href" to use in https://ionicframework.com/docs/api/button/
**Expected behavior:**
`<ion-button  color="light" expand="block" shape="round" fill='solid' class="lgbtn" routerLink="/home" routerDirection="root" >Login</ion-button>`

 this is working well, if i use "routerLink" then <ion-back-button> visible in home page.

@adamdbradley 
@bensperry
@dotNetkow
@brandyscarney
@bensperry

**Comment by paulstelzer** [comment]
Thanks for the issue! href is not allowed for ion-button, you have to use routerlink. You can read more here -> https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#angular-href-does-not-cause-angular-router-to-navigate
