### ISSUE TITLE
ion-back-button doesn't appears in tabs

### ISSUE THREAD

**Issue by rafalschmidt97** [ionic-team/ionic#17282]
# Bug Report

**Ionic version:**

[x] **4.0.0**

**Current behavior:**

Back button only appears in non tab pages. Even when i have some history to back (i can use the browser back button).

![screenshot 2019-01-27 at 10 41 15](https://user-images.githubusercontent.com/14861637/51799316-5f9e0480-2220-11e9-9b6e-0efd0248e3ae.png)
![screenshot 2019-01-27 at 10 41 39](https://user-images.githubusercontent.com/14861637/51799323-688ed600-2220-11e9-9c0b-7a5019f00478.png)
![screenshot 2019-01-27 at 10 43 50](https://user-images.githubusercontent.com/14861637/51799325-747a9800-2220-11e9-980b-7b186114ba5d.png)

**Expected behavior:**

It should works on every page.

**Steps to reproduce:**

- two tabs with with a toolbar and a back button - super simple to reproduce

**Related code:**

Just the most important stuff:

```
tab1.page.html

<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-butto></ion-back-button>
    </ion-buttons>
    <ion-title>Profile</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  <h1>Profile</h1>
</ion-content>

tabs-routing.module.ts

const routes: Routes = [
  {
    path: '',
    component: TabsComponent,
    children: [
      {
        path: 'profile',
        loadChildren: '../profile/overview/overview.module#OverviewPageModule',
      },
      {
        path: 'profile2',
        loadChildren: '../profile2/overview/overview.module#OverviewPageModule',
      },
    ],
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class TabsRoutingModule {}


tabs.component.html

<ion-tabs>
  <ion-tab-bar slot="bottom">
    <ion-tab-button tab="profile">
      <ion-icon name="person"></ion-icon>
      <ion-label> Profile</ion-label>
    </ion-tab-button>
    <ion-tab-button tab="profile2">
      <ion-icon name="person"></ion-icon>
      <ion-label>Profile2</ion-label>
    </ion-tab-button>
  </ion-tab-bar>
</ion-tabs>

```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.9.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, (and 2 other plugins)

System:

   NodeJS : v10.15.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

Good luck 😇

**Comment by brandyscarney** [comment]
Thanks for the issue! Could you please provide a repository to reproduce this if you're still running into it in latest? Our conference app uses a back button in tabs and it seems to work fine: https://github.com/ionic-team/ionic-conference-app

Unless you mean the back button is not showing when you're navigating to a tabs page?

**Comment by LokeSonne** [comment]
@brandyscarney the back-button only works when the defaultHref is set to the page the user navigated from. If there is more than one way for the user to navigate to the page this gets very complicated.

I wrote my own back-button that will use pop on ion-nav if canGoBack() is true and history.go(-1) otherwise. However, when it resorts to history.go(-1) the page I navigate back to will reload. If this page is a list the scroll reset.

This only happens when the routes are nested within tabs. If I remove the tabs the back-button works just fine.
