### ISSUE TITLE
ion-input ion-datetime ion-select have different placeholder opacity

### ISSUE THREAD

**Issue by RobbHerman** [ionic-team/ionic#17287]
**Ionic version:**

[x] **4.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**

When using ion-input, ion-datetime, and ion-select on the same page and using placeholder (not floating), the opacity of the fields prior to selecting a value are different.  This becomes more apparent when changing the font color to white for the field input/selection

**Expected behavior:**

The opacity should be the same and it would be helpful to have access to placeholder color and opacity on each of the objects.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.9.0 (C:\Users\robhe\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic 5.2.1, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.2, (and 15 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\robhe\AppData\Local\Android\Sdk)
   NodeJS            : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.5.0
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment]
![image](https://user-images.githubusercontent.com/2721089/52370900-22a4ef80-2a22-11e9-8b11-172b1fe10c03.png)

Seen on Chrome 72 macOS 10.14.3 (18D42)
