### ISSUE TITLE
Can I make a slack-like sidemenu in ionic?

### ISSUE THREAD

**Issue by wiadev** [ionic-team/ionic#17290]
Hi
I'm building a mobile app in ionic and I wanna make a slack-like side menu by placing slides.

For example, when you click on main menu item, it will slide out another slide in the sidemenu as slack does.

I tried to use ion-slides in ion-menu but slides is not working.

Check out the screenshot, please.

![stack](https://user-images.githubusercontent.com/18234060/51825520-d0cdce00-2299-11e9-974a-f0d7fab0c9db.gif)

Here is the code snippet.

```
<ion-menu [content]="mycontent" [swipeEnabled]="false">
    <ion-content>

      <ion-slides>
        <ion-slide>
          <h1>Slide 1</h1>
        </ion-slide>
        <ion-slide>
          <h1>Slide 2</h1>
        </ion-slide>
        <ion-slide>
          <h1>Slide 3</h1>
        </ion-slide>
      </ion-slides>

  </ion-content>

</ion-menu>

<ion-nav #mycontent [root]="rootPage"></ion-nav>

```

Here is what I'm trying to build.

<img width="380" alt="qqpib" src="https://user-images.githubusercontent.com/18234060/51825565-e5aa6180-2299-11e9-9974-0c3eb1f292b5.png">

Any thoughts on how to implement this?

Thanks.

**Comment by wiadev** [comment]
Is it possible in ionic 4? eventually, I need to upgrade to ionic 4. Thanks.

**Comment by manucorporat** [comment]
If it was possible in Ionic 3, it's in ionic 4 too :)
