### ISSUE TITLE
Ionic 4.9.0 not native Functions

### ISSUE THREAD

**Issue by tatylopes** [ionic-team/ionic#17304]
Hi, after update for 4.9.0 the native functions not working. 

![ionic](https://user-images.githubusercontent.com/46934905/51936963-24e6c880-23e8-11e9-95d5-387c5b125092.PNG)

No present message fail.

**Comment by brandyscarney** [comment]
There was an error when you installed `ionic`, see the top where it says `no matching version found for 4.60`. I believe you left off a period. It's likely this bad install messed up the `ionic` calls. Please try re-installing latest `npm install -g ionic@latest`. If you're still running into this I will reopen, thanks!
