### ISSUE TITLE
<ion-content> scroll function become invalid if router from other page.

### ISSUE THREAD

**Issue by zchking** [ionic-team/ionic#17309]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I use <ion-content> Methods -> scrollToPoint to scroll to my list position.

If this is as start page ( I visit it directly with url), it works as expected.
But If I router to it from other page, it will not work.
![image](https://user-images.githubusercontent.com/5665818/51959211-426e6d80-248e-11e9-8075-61ab65f78a6e.png)

![image](https://user-images.githubusercontent.com/5665818/51959248-5dd97880-248e-11e9-9d7d-613c54591854.png)

**Expected behavior:**

it should scroll to the position I give.

**Steps to reproduce:**

**Related code:**

![image](https://user-images.githubusercontent.com/5665818/51959359-ec4dfa00-248e-11e9-8d40-f67b7f851939.png)

**Comment by zchking** [comment]
I can sure that it is **_scrollToPoint_** problem. As I console log the Y point it is right.

**Comment by paulstelzer** [comment]
Thanks for your issue! Can you log content? It's a better way not to use querySelector. Could you test it with ViewChild from Angular?
