### ISSUE TITLE
Unable to type in input/ion-input fields on iOS and Safari

### ISSUE THREAD

**Issue by maddada** [ionic-team/ionic#17307]
# Bug Report

**Ionic version:**

[x] **4.0.0**

**Current behavior:**

I can't type in ion-input AND input fields in Safari and on iOS simulator (tried both virtual and hardware keyboard), however when I type in Chrome or Firefox (mobile/desktop) text is showing up perfectly.

**Expected behavior:**

Text should show up normally when typing in input fields.

**Steps to reproduce:**

This is a very simple page with 1 input field, it can be tested on iOS and Safari and then on Chrome.
Inputting works on chrome but won't work on Safari and iOS (even on chrome in iOS)

https://memar.ae/forgot-password

**Related code:**
https://github.com/maddada/engappm7/tree/master/src/app/pages/login/forgot-password

**Other information:**

I've tried uninstalling/reinstalling cordova-plugin-ionic-keyboard, tried removing and readding iOS, tried uninstalling/reinstalling the cordova webview plugin, all to no avail.

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.9.0 (C:\Users\madda\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.2, (and 7 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\madda\AppData\Local\Android\Sdk)   NodeJS            : v10.10.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

Any help with this problem would be greatly appreciated, I have been trying to fix it for 2 days now without any progress.
I can't be the only one that faced this issue.

**Comment by maddada** [comment]
Btw, after trying to fix the input problem for a very long time, I downgraded to 4.0.0-rc.1 and now I can type in inputs in Safari. I thought 4.0.0 was stable and it couldn't be a problem with the newer version, silly old me, I forgot I was dealing with Ionic here.
The issue is with 4.0.0-rc.2 and above.

Please someone fix this issue =_=

**Comment by maddada** [comment]
Hey, this is still an issue with v4.0.1, just wanted to bump this incase it wasn't noticed.. Really important bug.

**Comment by paulstelzer** [comment]
Thanks for your issue! Does this problem still exist?
