### ISSUE TITLE
Safari Mac & iOS - ionic/core (npm module) - ionic scripts load issue - 'TypeError: 'text/html' is not a valid JavaScript MIME type'

### ISSUE THREAD

**Issue by PrasannaaSanthanam** [ionic-team/ionic#17301]
Hi All,
I am using just the ionic/core package in my angular app (v1.5.x) using the **npm module.** (https://www.npmjs.com/package/@ionic/core)

I use webPack to copy the ionic and the related directories from node modules to  required destination (libs/ionic) and load just the ionic.js from my libs/ionic in my app's index.html, this internally loads the the dependent ionic scripts from the same libs/ionic dir.

The above works fine on chrome(v 71.x) & FF (v64.x), but fails on Safari (11.x, on both Mac & iOS).

On Safari, once the ionic.js gets loaded, it tries to load the additional files but fails with the below error 
**TypeError: 'text/html' is not a valid JavaScript MIME type**,  because of which  ionic components fails to render.

**Note: This issue does NOT happen when I use the CDN version of ionic js like below.**
_<script src="https://unpkg.com/@ionic/core@4.0.0/dist/ionic.js"></script>_

thanks 
Prasannaa

**Comment by paulstelzer** [comment]
Thanks for your issue! It seems that Safari not founds the js file. Could you create a repo so we can check it?
