### ISSUE TITLE
ion-slides don't load all the time and sliding don't work

### ISSUE THREAD

**Issue by juny58** [ionic-team/ionic#17310]
# Bug Report

**Ionic version:**

[x] **4.7**

**Current behavior:**

On the first ever slides page, the sliding does not always work. It is very late sometimes. Or does not even work. But all other sequential pages are fine. After a research I found that the slides are not loaded from web.

**Expected behavior:**

It should work nomatter the web connection is there or not. The vendor js should be static and not loaded. I can see it is there in the core>ion-slides>vendor folder. But it still takes dependency from web.

**Steps to reproduce:**

Turn off the internet connection and load slides on any page with examplary two or three ion-slide inside

**Comment by liamdebeasi** [comment]
Hi @juny58,

The Ionic codebase should not be loading anything from the web. Can you verify that you haven't added any assets that link out to the web? Additionally, can you provide a repository with the code necessary to reproduce this issue?

Thanks for using Ionic!
