### ISSUE TITLE
ion-select not scrollable on iOS

### ISSUE THREAD

**Issue by oal** [ionic-team/ionic#17311]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
ion-select with lots of select options is not scrollable on iOS.

![img_8270](https://user-images.githubusercontent.com/371103/51972033-d9312f00-247a-11e9-9e2a-e35aa842bb64.PNG)

**Expected behavior:**
ion-select should be scrollable when the number of select options don't fit in view.

**Steps to reproduce:**
Create a ion-select with 20 select options and run the app on iOS.

**Other information:**
It works on Android. Multiple select `<ion-select multiple>` also seem to work on iOS, so it only happens on single-select ion-select.

**Ionic info:**
```
Ionic:
   ionic (Ionic CLI)             : 4.8.0 (/home/olav/.npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.0

Cordova:
   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 9 other plugins)

System:
   Android SDK Tools : 26.1.1 (/home/olav/Android/Sdk)
   NodeJS            : v11.7.0 (/usr/bin/node)
   npm               : 6.6.0
   OS                : Linux 4.18
```

**Comment by maddada** [comment]
Hey, I see that no one is answering issues these days.
I had a problem with iOS where I couldn't write in ion-inputs on iOS and Safari.
The temporary fix I did was to downgrade to @ionic/angular version 4.0.0-rc.1
(make sure to revert nav.goBack() to nav.back() )
Commands:
npm uninstall @ionic/angular
npm install @ionic/angular@4.0.0-rc.1

Good luck!

**Comment by oal** [comment]
Thanks, @brandyscarney. I can confirm that the workaround works!

**Comment by oal** [comment]
![image](https://user-images.githubusercontent.com/371103/52402814-803e4800-2ac5-11e9-94ea-90c84e5daed1.png)

I tested in the Xcode simulator now, and the carrier / time bar seems to be rendered on top of the ion-select still. But at least it's scrollable now. :+1:

**Comment by brandyscarney** [comment]
@oal Good catch! Will also look into adding the safe-area for it. 🙂

**Comment by vyelamanchi** [comment]
Hi, We are using ionic 4.3.0 version & the issue still exists in iphones. We are getting the node_modules dynamically for every build so we can't just the update the css file in node_modules. What is the best way to handle this ?

**Comment by Antoine38660** [comment]
@vyelamanchi You can add it to your `global.scss` file.

With the `!important` rule, it will override the default style defined in your node_modules :slightly_smiling_face:

**Comment by vyelamanchi** [comment]
@Antoine38660 
Thank you. that worked

**Comment by dylan-westbury** [comment]
```
.action-sheet-group.sc-ion-action-sheet-ios {
  overflow: auto;
}

In global file, will just target iOS and no need for !important
```

Any timeframe for a fix? For ion-select with a large list of options, user cannot select the first option.

![ion-select can't select first option](https://i.imgur.com/70owXUN.png)

**Comment by danbeckner** [comment]
> @oal Good catch! Will also look into adding the safe-area for it. 🙂

Any timeframe on this? Still having this issue with IOS.

**Comment by krabien** [comment]
Adding the below to `src/global.scss` seems to fix both issues for me:

```
// workaround: full screen action sheet scrolling background on iOS
.action-sheet-group.sc-ion-action-sheet-ios {
  overflow: auto;
}
// workaround: action sheet not honoring safe area margins
.action-sheet-wrapper.sc-ion-action-sheet-ios {
  top: 0;
  height: auto;
}
```
