### ISSUE TITLE
Implement MD pull to refresh style

### ISSUE THREAD

**Issue by seang96** [ionic-team/ionic#17316]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
Ion-Refresher does not conform to MD Swipe to refresh. Guidelines are here: [https://material.io/design/platform-guidance/android-swipe-to-refresh.html#usage](https://material.io/design/platform-guidance/android-swipe-to-refresh.html#usage)

**Describe Preferred Solution**
Have built in functionality similar to [https://github.com/omelsoft/ion-refresh-native](https://github.com/omelsoft/ion-refresh-native) for Ionic v3 and SVG crescent as default.

**Describe Alternatives**
Updating the project for v4 above, however it still isn't completely up to spec and is more of a custom solution.

**Related Code**
[https://github.com/omelsoft/ion-refresh-native](https://github.com/omelsoft/ion-refresh-native) does most of it for V3.

**Comment by Scobee** [comment]
@seang96  - did you ever find a solution for this ?

**Comment by seang96** [comment]
@Scobee the ion-refresh-native repo mentioned above might work with Ionic 4 still, might have to change it a little bit though. It uses 3 callback functions, so if those below are still named correctly then it should still work.

```
      '(ionStart)': 'handleStart($event)',
      '(ionPull)': 'handlePull($event)',
      '(ionRefresh)': 'handleRefresh($event)'
```

 It still doesn't seem to be exactly right to me, swapping to the default crescent looks awful in the demo. The arrow also seems more complete than standard and should need to be pulled down more.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This has been resolved via https://github.com/ionic-team/ionic/pull/20096 and will be available in an upcoming release of Ionic Framework.
