### ISSUE TITLE
Tabs pages with implemented OnInit executed once

### ISSUE THREAD

**Issue by rafalschmidt97** [ionic-team/ionic#17312]
# Bug Report

**Ionic version:**

[x] **4.0.0**

**Current behavior:**

As is the title OnInit is only executed once. Maybe it's related to the outlet but it is annoying because every other pages behave differently.

**Expected behavior:**

I would love to see the same behaviour on every pages - regardless of whether it is.

**Steps to reproduce:**

- two pages in tabs with implemented OnInit
- try at least to execute console.log

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.9.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.2, (and 6 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 7.0.0
   NodeJS     : v10.15.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61
```

**Comment by liamdebeasi** [comment]
Hi @rafalschmidt97,

Thanks for opening an issue with us! Would you be able to clarify the issue you are experiencing? Additionally, can you create a repository that has the code required to reproduce this issue?

Thanks for using Ionic!

**Comment by rafalschmidt97** [comment]
Hi @liamdebeasi,
Repo: https://github.com/rafalschmidt97/ionic-issue-17312.

Take a look. console.log is executed only once for tab pages. But for example page it runs every single time.

Thanks for your response! 🙆‍♂️

**Comment by liamdebeasi** [comment]
Hi there,

This functionality is intentional. When going from Page 1 to Page 2, Page 1 is cached and does not need to be re-initialized when clicking the back button on Page 2.

If you are looking for a way to run code every time Page 1 becomes the active page, I recommend you use a lifecycle hook such as `ionViewWillEnter` or `ionViewDidEnter`: https://ionicframework.com/docs/building/migration/#lifecycle-events

Can you try one of the lifecycle hooks and let me know if it works for your use case? Thanks!

**Comment by rafalschmidt97** [comment]
@liamdebeasi - yeah I know about them. But I don't like an idea of keeping logic outside of component where it's not related to him. It's just a container for other routes (I think). I understand that this was a choice which you did as a developers (maybe tradeoff?). I hope you get my point of view that all other pages behave differently (they are not cached and OnInit works perfectly).

There are just my thoughts 🚀 Thanks for a discussion and your time. We can close this thread 😇
