### ISSUE TITLE
[Ionic 4] ion-footer slot="end" places content at the beginning of the following line

### ISSUE THREAD

**Issue by burggraf** [ionic-team/ionic#17334]
# Bug Report

**Ionic version:**

[x] **4.0.0**

**Current behavior:**

Items placed inside **slot="end"** do not appear on the lower-right portion of the screen (in the footer) but instead wrap around to the beginning of a new line, so they appear just under the items placed inside **slot="start"**.

**Expected behavior:**

Items placed inside **slot="end"** should appear at the lower-right area of the screen.

**Steps to reproduce:**

```
ionic start footer-bug blank
```

Add the following code to the end of home.page.html:

```
<ion-footer>

  <ion-buttons slot="start">
    <ion-button>
      <ion-icon slot="icon-only" name="arrow-round-back"></ion-icon>
    </ion-button>back
  </ion-buttons>

  <ion-buttons slot="end">
    <ion-button>
      <ion-icon slot="icon-only" name="arrow-round-forward"></ion-icon>
    </ion-button>forward
  </ion-buttons>

</ion-footer>

```

**See screenshot of result below:**

![image](https://user-images.githubusercontent.com/225717/52079020-84101e80-2549-11e9-9f82-b8d97297763a.png)

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.10.1 (/Users/markb/.nvm/versions/node/v11.8.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

System:

   NodeJS : v11.8.0 (/Users/markb/.nvm/versions/node/v11.8.0/bin/node)
   npm    : 6.5.0
   OS     : macOS Mojave
```

**Comment by brandyscarney** [comment]
Thanks for the issue! The footer is just a container for one or more toolbars. The `ion-buttons` element should be placed in an `ion-toolbar` to take advantage of slots. You should also set `slot` to `start` and `end` on the icons. Please try the following:

```
<ion-footer>
    <ion-toolbar>
      <ion-buttons slot="start">
        <ion-button>
          <ion-icon slot="start" name="arrow-round-back"></ion-icon>
          back
        </ion-button>
      </ion-buttons>

      <ion-buttons slot="end">
        <ion-button>
          <ion-icon slot="end" name="arrow-round-forward"></ion-icon>
          forward
        </ion-button>
      </ion-buttons>
    </ion-toolbar>
  </ion-footer>
```

Here's a Codepen example: https://codepen.io/brandyscarney/pen/OdxWzx?editors=1100

More info on toolbars: https://ionicframework.com/docs/api/toolbar#buttons
