### ISSUE TITLE
Producing duplicated images in the --prod build

### ISSUE THREAD

**Issue by anasvn** [ionic-team/ionic#17347]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Producing duplicated images in the --prod build.

**Steps to reproduce:**

Add background image for an element in the scss file
eg. style.scss
```
background-image: url('../../../assets/images/bg/background-texture-repeat.jpg');
```
Apart from the original image file its producing a duplicate background-texture-repeat.jpg file in the www folder.

**Comment by brandyscarney** [comment]
Thanks for the issue! Do you have a way to reproduce this? Is this an Angular project? Please run and paste the results of the following:

```
ionic info
```

**Comment by anasgvr** [comment]
Ionic:

   ionic (Ionic CLI)             : 4.10.1 (C:\Users\Anas\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   NodeJS : v10.14.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

**Comment by paulstelzer** [comment]
Thanks for your issue! What you describe has nothing to do with Ionic, it's part of the building of Angular. Normally the image in the www folder will get a hash and your background-image in styles.scss will be automatically changed with it.
