### ISSUE TITLE
[4.0.0][iOS] Positioning element to bottom as fixed "vibrates" when scrolling

### ISSUE THREAD

**Issue by sneko** [ionic-team/ionic#17349]
Hi,

I would like to simulate the behavior of the `ion-footer` by having a button stuck at the bottom of my screen **inside** my `ion-content`:
```
ion-content
  .bottom-button
    ion-button Test button
```

I set to this element the following style:
```
  .bottom-button {
    pointer-events: none;
    position: fixed;
    width: 100%;
    height: 100px;
    bottom: 0;
    text-align: center;

    ion-button {
      margin-bottom: 15px;
    }
  }
```

It works well on all desktop browsers (including Safari) and also on Android browsers... but not really well on the mobile Safari.

When scrolling on iOS:
- the button will either "vibrate" to "catch" the scroll move
- and sometimes stays totally stuck at its initial position. I mean, like if it has an absolute position with `top: Ypx`

Anyone has already encounter this issue ? And maybe a way to fix this issue please?

**Comment by duyetnk** [comment]
your button should be outside ion-content

**Comment by brandyscarney** [comment]
Thanks for the issue! I am going to close this as it is more of a support question, but I believe what you are looking for is `slot="fixed"`. This will place the button outside of the scroll element but still inside of the content and in a fixed position.

```
<ion-content>
  <ion-button slot="fixed">Fixed</ion-button>
</ion-content>
```
