### ISSUE TITLE
Cannot override config per platform

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic#17353]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

We currently provide ways to set certain config options on app boot (https://github.com/ionic-team/ionic/blob/master/core/src/utils/config.ts), but we do not provide a way to do it on a per-platform basis.

We used to provide this functionality in v3: https://ionicframework.com/docs/v3/api/config/Config/

**Expected behavior:**

I would expect to have the ability to override config options on a per-platform basis.

**Comment by ASHFAQPATWARI** [comment]
@liamdebeasi any update on this one? This per platform config really comes in handy.

**Comment by buko106** [comment]
We use workaround overriding ionic config based on platform using APP_BOOTSTRAP_LISTENER. 
However,  Config.set() method is deprecated (https://github.com/ionic-team/ionic/pull/19104).

So we hope this feature will be included in ionic 5.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. This has been resolved via https://github.com/ionic-team/ionic/pull/21308, and this feature will be available in an upcoming release of Ionic Framework.

When the feature ships, the documentation will be updated to reflect this new functionality. Here is an example of how you would do this in your app:

Ionic Angular:
```typescript
import { isPlatform, IonicModule } from '@ionic/angular';

@NgModule({
  ...
  imports: [
    BrowserModule,
    IonicModule.forRoot({
      animated: !isPlatform('mobileweb') // Disable animations when running in a mobile browser
    }),
    AppRoutingModule
  ],
  ...
});
```

Ionic React:
```typescript
import { isPlatform, setupConfig } from '@ionic/react';

setupConfig({
  animated: !isPlatform('mobileweb') // Disable animations when running in a mobile browser
});
```

You can view all the docs changes here: https://github.com/ionic-team/ionic-docs/pull/1423. They contain several more usage examples that may be helpful when developing. For any bugs you encounter when trying to use these utilities, please open a new issue. Thanks!
