### ISSUE TITLE
Image/Graphics glitch when using App

### ISSUE THREAD

**Issue by glenntws** [ionic-team/ionic#17364]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

The icons of several items get moved or really glitchy after using the app for a while. No error is given in the console. The glitch can be seen on iPhone (android not tested) (tested on iOS 12.1.3 / iPhone 6S).
The keyboard plugin puts out a error (_UIKBCompatInputView), but the starting of the glitches and the error don't seem to be related.

**Expected behavior:**

The buttons should stay with their correct icons and they also shouldn't move. The graphical glitches obviously shouldn't be there.

**Steps to reproduce:**

Application with fullscreen tabs-inner. tab-bar is transparent and uses backdrop-filter, as well as the input box in the tab. Side menus (left and right) also use the dackdrop-filter for the containing ion-content. The tab includes a video-html tag playing a video in fullscreen. The config.xml preferences have keyboard-resize set to "body".

1. Start the app
2. Switch between some tabs, start typing in the input box in the tab, press the buttons randomly.
3. Without any warning/error in the console, the icons start to play weird.
4. A complete restart of the app seems to help with the issue.

**Related code:**

**Other information:**

The error in the console that happens when starting to type

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.10.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.0.7
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 4 other plugins)

System:

   NodeJS : v10.15.0 (/usr/local/bin/node)
   npm    : 6.7.0
   OS     : macOS Mojave
   Xcode     : Xcode 10.1 Build version 10B61
```

**Comment by glenntws** [comment]
Missed a bit in the part "Other information": 

API error: <_UIKBCompatInputView: 0x1009358c0; frame = (0 0; 0 0); layer = <CALayer: 0x28337fbe0>> returned 0 width, assuming UIViewNoIntrinsicMetric

Oh and here are some pics showing the glitches:
![img_0054 1](https://user-images.githubusercontent.com/19694869/52165827-10ffd700-2706-11e9-91bf-caf5eeb56bbb.PNG)
![img_0055 1](https://user-images.githubusercontent.com/19694869/52165830-18bf7b80-2706-11e9-8298-604e3136f19f.PNG)
![img_0056 1](https://user-images.githubusercontent.com/19694869/52165833-1fe68980-2706-11e9-88f1-3c9af3780dbd.PNG)

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you add a repo so we can test it?
