### ISSUE TITLE
Lots of Ionicons not loaded in V4

### ISSUE THREAD

**Issue by JerryBels** [ionic-team/ionic#17366]
[x] **4.x**

**Current behavior:**
Lots of Ionicons are not loading. `arrow-up`, `log-out`, `people`, `alarm`, `paper-plane`...

**Expected behavior:**
Well... Icons should load :)

**Steps to reproduce:**
1/ Create a new blank project `ionic start myApp tabs --type=angular`
2/ Add to home `<ion-icon name="arrow-up"></ion-icon>` and `<ion-icon name="settings"></ion-icon>`
3/ Witness the desperately empty place of `arrow-up` icon. Try not to cry. Cry a lot.

**Other information:**
Was working perfectly with Ionic 3. Doesn't change anything to `npm install --save ionicons`.

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.10.1 (C:\Users\me\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 7
```

**Comment by tja4472** [comment]
Hi,
Try emptying the browser cache.

See
https://github.com/ionic-team/ionic/issues/17019#issuecomment-452828443

**Comment by JerryBels** [comment]
Actually I had to delete my www folder as well, thanks for the link !
