### ISSUE TITLE
Sidemenu starter: Unexpected animation when using split-pane in other component than app component

### ISSUE THREAD

**Issue by mahnuh** [ionic-team/ionic#17362]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
I used the sidemenu starter and moved the split-pane from the AppComponent to a separate component so I can have a login page at root level and make all the stuff with the side menu available to authenticated users only. This seems to work so far, but there is a page transition animation only in the first click on any side menu link. It does not matter which link I click first. See [this video](https://share.heidrich.io/Screen-Recording-2019-02-02-08-30-57-1549092659/#e7a9e4c38df6b33e12f9e91c5ab188cbfa34b616c7b8a6af94ef5274bea11209).
The browser (tested with Firefox and Chrome) as well as the platform (iOS or MD) does not matter, the issue stays the same.

**Expected behavior:**
I would expect this animation not to happen.

**Steps to reproduce:**
See related code.

**Related code:**
I published the code from the demo app shown in the video here: https://github.com/mahnuh/ionic4-sidemenu-issue-demo

**Ionic info:** 
```
Ionic:

   ionic (Ionic CLI)             : 4.9.0 (/Users/manuel/.nvm/versions/node/v10.15.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

System:

   NodeJS : v10.15.0 (/Users/manuel/.nvm/versions/node/v10.15.0/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by redwolf2** [comment]
Implement your side menu like the sidemenu starter project. Implement your login as a guard and show a component as a modal in your canActivate() method, using `modalController.create()`.

**Comment by mahnuh** [comment]
@redwolf2 Thanks for your input, but I do not think that is an ideal solution. I'm not even sure a modal would work without the AppComponent as the main component being loaded.
In the AppComponent there would be lots of stuff that should not be executed for unauthorised users (hello 401), so using a modal to just "hide" all that stuff does not work either.

**Comment by redwolf2** [comment]
It's not in the app component. Default route redirects to home. Home has a guard applied.

See: https://medium.com/@ryanchenkie_40935/angular-authentication-using-route-guards-bf7a4ca13ae3

**Comment by mahnuh** [comment]
Sure, but when redirected to home, AppComponent will be loaded as the main router outlet is in AppComponent. The menu is in AppComponent as well including the stuff only authenticated users should see or are allowed to execute. Thats why the menu and other stuff needs to be in a separate component only accessible for authenticated users (with the help of guards).

**Comment by redwolf2** [comment]
I understand, I only figured it would be easier for you to have a landing page and then use the guard from there.

In your app.component.html you have:

`<ion-router-outlet main></ion-router-outlet>`

and inside side-menu.page.html

` <ion-router-outlet main id="foo"></ion-router-outlet>`

Try to remove the attribute `main` from app.component.html, because that might be what freaks out the ion-split-pane.

**Comment by paulstelzer** [comment]
Thanks for the issue! I do not use the main anymore. This is my code:

```
<ion-split-pane when="lg" contentId="abc-sidebar">
  <ion-menu #leftSidebar contentId="abc-sidebar" menuId="left" type="reveal" side="start">
    <app-sidebar-menu></app-sidebar-menu>
  </ion-menu>

  <ion-router-outlet id="abc-sidebar"></ion-router-outlet>

</ion-split-pane>
```

Inside app.component.html I only have `<ion-app><ion-router-outlet></ion-router-outlet></ion-app>` and this is working without problems
