### ISSUE TITLE
<Video> Tag doesn't respect playsinline on iOS

### ISSUE THREAD

**Issue by NG-tylerholden** [ionic-team/ionic#17368]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Referencing this because I'm assuming it is a webview bug but I don't know that for sure.
I'm wondering if by some reason this is by design.
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/294

**Expected behavior:**

`<video playsinline />` will always open fullscreen video player on iOS when it comes into view

**Steps to reproduce:**

Just add a video to new ionic project see 
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/294

**Other information:**

**Ionic info:** 

Ionic:

   ionic (Ionic CLI)             : 4.9.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.1, (and 14 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v11.6.0 (/usr/local/bin/node)
   npm        : 6.5.0-next.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61

**Comment by tmk1991** [comment]
use this in the config.xml for ios
`<preference name="AllowInlineMediaPlayback" value="true" />`
