### ISSUE TITLE
ion-img horizontal lazy loading not working 

### ISSUE THREAD

**Issue by RonCan** [ionic-team/ionic#17378]
# Bug Report

**Ionic version:**

[x] **4.0**

**Current behavior:**
ion-img in a horizontal scroll div does not lazy load. Instead everything is loaded eagerly

**Expected behavior:**
ion-img should lazy load.

**Steps to reproduce:**
I have a horizontal scroller that I built with `FlexLayoutModule` that basically let's me have a horizontally scrollable list where every item is a column of image and text. Here's the relevant code from my `scroller.component.html`

      <div class="ion-activatable container" fxLayout="column" fxLayoutAlign="start center" fxLayoutGap="10px" *ngFor="let item of items">
        <ion-ripple-effect></ion-ripple-effect>
        <div *ngIf="item.movie || item.title" [routerLink]="'/tabs/discover/movie/'+ (item.movie? item.movie.ids.tmdb: item.ids.tmdb)">
          <ion-img class="poster" [src]="(images$[item.movie? item.movie.ids.tmdb: item.ids.tmdb] | async) || preloaderGif"></ion-img>
          <div class="item-titles">
            {{item.movie? item.movie.title: item.title}}
          </div>
        </div>
    </div>

But when the page loads up, all the hundreds of image requests are fired which I can see from the network tab as well as my API reporting I have hundreds of pending requests and that I have hit rate-limiting. Maybe I'm not using the ion-img right or maybe some of the styles are messing with it? Here's my `scroller.component.scss`:

    .horizontal {
      white-space: nowrap;
      overflow-x: auto;
    }
    .poster {
      width: 92px;
      height: 138px;
    }
    .container {
      position: relative;
      cursor: pointer;
      user-select: none;
    }
    .item-titles {
      width: 100px;
      white-space: normal;
      text-align: center;
    }

I'm open to suggestions. Maybe I should use `virtual-scroll`? But I don't see how I can make that horizontal.

**Other information:**

**Ionic info:** 

Ionic:

   ionic (Ionic CLI)             : 4.10.1 (/home/ronniekinsley/.nvm/versions/node/v8.15.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

System:

   NodeJS : v8.15.0 (/home/ronniekinsley/.nvm/versions/node/v8.15.0/bin/node)
   npm    : 6.7.0
   OS     : Linux 4.15

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still a bug in the latest version of Ionic Framework?

I tried this using Ionic Framework v5.1.1, and was unable to reproduce the issue: https://codepen.io/liamdebeasi/pen/dyGGojo

**Comment by RonCan** [comment]
It appears to be fixed, thanks
