### ISSUE TITLE
Can't view a child page of a different tab outlet in other tabs and keep tab bar visible

### ISSUE THREAD

**Issue by tmk1991** [ionic-team/ionic#17370]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
You can't view a child page of a different tab outlet in other tabs

**Expected behavior:**
I should be able to pull up a child page of a different outlet in any tab and keep the tab bar visible

How do you view pages that are children of another tab (or the tab main page itself), from within another tab and keep the tab bar up? 

For example:

If I have: 
*  `Home Page` tab 
* sub page of `Home Page` called `Child1`
* `Library Page` tab
* sub page of `Library Page` called `Child2`

How do I view `Child2` from the `Child1` page while keeping the tab bar visible?
How do I view the `Library Page` from the `Child1` page while keeping the tab bar visible?

It looks like routing was changed to remove that weird (one:one) syntax and I'm not sure how to view a page thats served from one tab's outlet vs another to keep the tab bar up.

A real world example would be how in Facebook you can view the profile page from different tab routes and the tab bar stays visible. This was obviously possible with the old v3 `nav.push()`

**Comment by REPTILEHAUS** [comment]
Also hitting this

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
