### ISSUE TITLE
Ionic 4.0.0 +  Vue ionicons sometimes not showing

### ISSUE THREAD

**Issue by lassesteffen** [ionic-team/ionic#17374]
# Bug Report

**Ionic version:**

[x] **4.x** in combination with @ionic/vue

**Current behavior:**

On some pages some icons are not loaded even though correctly defined. Sometimes all the icons are shown, sometimes only a subset. This image for example misses the arrow-back icon in the top left and the "images" icon next to 'Galerie' 

![image](https://user-images.githubusercontent.com/29383763/52210615-e6d62280-2887-11e9-8751-4a8d3da8af26.png)

This is the DOM-tree that is created, as you can see it is showing the svg for the camera icon but not for the images icon. I have not idea whats going on.

![image](https://user-images.githubusercontent.com/29383763/52210713-1e44cf00-2888-11e9-8365-84eb51a8af11.png)

**Expected behavior:**

I want to see all icons.

**Steps to reproduce:**

**Related code:**
The code for creating the action sheet.
```
showAddImageActionSheet() {
      this.$ionic.actionSheetController
        .create({
          header: this.$t('order.referencePhotos.actionSheet.header'),
          buttons: [
            {
              text: this.$t('order.referencePhotos.actionSheet.openCamera'),
              icon: 'camera',
              handler: () => {
                this.getPictureFromCamera();
              },
            }, {
              text: this.$t('order.referencePhotos.actionSheet.openGallery'),
              icon: 'images',
              handler: () => {
                this.getPictureFromGallery();
              },
            }, {
              text: this.$t('buttons.cancel'),
              icon: 'close',
              role: 'cancel',
            },
          ],
        })
        .then(a => a.present());
    },
```

If you need me to, I can try to provide you with a sample application, via GitHub let me know!

**Comment by jachno** [comment]
I am getting the same issue, I find that if I run it in the browser emulator, on multiple refreshes it will have different behaviours

**Comment by lassesteffen** [comment]
I solved the problem by fully using (@modus/ionic-vue)[https://github.com/ModusCreateOrg/ionic-vue]. And updating to the latest version. Maybe this commit fixed it https://github.com/ModusCreateOrg/ionic-vue/commit/31aeb928c451a7ba606d47e3aeeb4dd7966d72cb, it mentions streamlining the ionicons import
