### ISSUE TITLE
[4.0.0] android simulator icon svg do not appear

### ISSUE THREAD

**Issue by goelectricstations** [ionic-team/ionic#17388]
# Bug Report

**Ionic version:**
[x] **4.0.0**

Ionic:

   ionic (Ionic CLI)             : 4.10.2 (\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, android test, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 1.2.1, (and 12 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Program Files (x86)\Android\android-studio\sdk)
   NodeJS            : v11.9.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.7.0
   OS                : Windows 10

On Android device simulator icon does not appear see error console:
![image](https://user-images.githubusercontent.com/20230407/52270987-c028f200-2942-11e9-93e6-a05e003be8ad.png)

**Comment by tvb** [comment]
Perhaps related to https://github.com/ionic-team/ionic/issues/17245 ?

**Comment by goelectricstations** [comment]
Unfortunatly not, in my case is already like that:
            "assets": [
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "assets"
              },
              {
                "glob": "**/*.svg",
                "input": "node_modules/ionicons/dist/ionicons/svg",
                "output": "./svg"
              }
            ]

**Comment by goelectricstations** [comment]
@manucorporat @paulstelzer  Hi Guys, do you know when will be fixed? Thank you for your excellent work.

**Comment by goelectricstations** [comment]
I fixed like this:

npm uninstall -g cordova
npm install -g cordova
ionic cordova platform remove android
ionic cordova platform add android
npm i cordova-plugin-ionic-webview@^2.1.3
ionic cordova platform rm .idea
cordova plugin rm cordova-plugin-ionic-webview
cordova plugin add cordova-plugin-ionic-webview
ionic cordova emulate android
