### ISSUE TITLE
display css property of ion-grid is not as `display: flex`

### ISSUE THREAD

**Issue by serkon** [ionic-team/ionic#17395]
I read the current documentation of [`ion-grid`](https://ionicframework.com/docs/api/grid/). That document says: `ion-grid` uses mobile first flexbox system.

When i inspect to `ion-grid` using Chrome DevTools then looks computed styles, it seems as `display: block`. I can add manually `display: flex` to ion-grid in component scss, but some directives as `justify-content-center` and other flexbox directive's not works without it. 

If I'm wrong, can you tell me the truth?
Thanks

**Comment by brandyscarney** [comment]
The grid is a flex system, but the actual flex is on the row component. The grid component itself is mainly just a container that adds some padding and holds the rows together.

There is some better documentation surrounding grid here: https://ionicframework.com/docs/layout/grid

This includes attributes that can be added to position the columns.
