### ISSUE TITLE
Input box and components around flickers when scrolling & focusing the input

### ISSUE THREAD

**Issue by hamzahalvanaa** [ionic-team/ionic#17390]
Apologies in advance if this is not the correct place to posting the issue.

#### Short description of the problem ####
**Issue 1**: **Flickers when tapping on an input box after long scrolling.**
Emulator Gif:

![giphy](https://user-images.githubusercontent.com/25146891/52275760-069e4100-2983-11e9-9f7b-5133bbcb1b99.gif)

`<ion-item *ngIf="hasil.opsi == '' || hasil.opsi == null || hasil.opsi == undefined " [ngClass]="itemClass(hasil.value,hasil.parameter)">
    <ion-label class="label-input" text-capitalize text-wrap> {{ hasil.parameter }}
        <br/>
        <small *ngIf="hasil.tagNo != ''" > ( {{hasil.tagNo}} )</small>
    </ion-label>
    <ion-input [ngClass]="changeClass(hasil.value,'','',hasil.min,hasil.max)" type="number"  placeholder="{{hasil.min}} / {{hasil.max}} - {{ hasil.satuan }}" [(ngModel)]="hasil.value"></ion-input>
</ion-item>
`
**Run `ionic info` from terminal/cmd prompt:**
My system information:

Ionic:

   ionic (Ionic CLI)  : 4.10.1 (/usr/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 19 other plugins)

System:

   NodeJS : v8.11.2 (/usr/bin/node)
   npm    : 6.7.0
   OS     : Linux 4.15

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! Would you be able to provide a repository with the code required to reproduce this issue?

Thanks for using Ionic!

**Comment by hamzahalvanaa** [comment]
@liamdebeasi here is check on my repository, https://github.com/hamzahalvanaa/bocplus/blob/master/src/pages/scanner/scanner.html

**Comment by liamdebeasi** [comment]
Hi there,

My apologies, I did not realize this was an Ionic 3 application. This repo is used bug tracking for Ionic 4+. I'll transfer this issue to the appropriate repository. 

Thanks for using Ionic!
