### ISSUE TITLE
No IntelliSense in WebStorm for all HTMLIon*Elements in an angular project

### ISSUE THREAD

**Issue by StefanRein** [ionic-team/ionic#17404]
# Support Question

## Solution

https://youtrack.jetbrains.com/issue/WEB-37192

> `node_modules\@ionic\core` is excluded from indexing, because this module is not listed in project dependencies in `package.json`. Un-excluding it ( Mark directory as/Not excluded) should make typings from `node_modules\@ionic\core\dist\types` available to the IDE, making completion work

Doing this or adding `"@ionic/core": "^4.0.0"` to the `package.json` will work.

## Question

Why cannot we add this dependency directly by generating the project?

--------------------

**Ionic version: 4.x**

**Current behavior:**
Using any Ionic Controller (e.g. AlertController, ToastController) and creating HTMLIonElements, e.g. HTMLIonAlertElement or HTMLIonToastElement, there is no IntelliSense in Webstorm.

**Expected behavior:**
There should be IntelliSense / hints for these classes and theirs members or methods.

**Steps to reproduce:**

1.  Setup a new project with angular type:

`ionic start myApp tabs --type=angular`

2. Open WebStorm, open the `Tab2Page` class and create an alert and try to get IntelliSense for example the `dismiss` method of the `HTMLIonAlertElement`.

**Related code:**

```javascript
import { Component } from '@angular/core';
import { AlertController, ToastController } from '@ionic/angular';

@Component({
    selector: 'app-tab2',
    templateUrl: 'tab2.page.html',
    styleUrls: ['tab2.page.scss']
})
export class Tab2Page {
    constructor(private alertController: AlertController, public toastController: ToastController) {
    }

    private async showLoading() {
        const loading = await this.alertController.create({header: 'test header'});
        // const ionAlertElement: HTMLIonAlertElement;

        loading.dismiss();
    }
}

```

**Other information:**

**WebStorm Info:**
I already Invalidated Caches and Restarted WebStorm. (at least two times)
Version 2018.3.4

### Mac OS

![image](https://user-images.githubusercontent.com/4970737/52364050-922bd680-2a44-11e9-8a69-8ba836180542.png)

If I click on the HTMLIonAlertElement I land here: **components.d.ts**

```javascript
interface HTMLIonAlertElement extends Components.IonAlert, HTMLStencilElement {}
var HTMLIonAlertElement: {
    prototype: HTMLIonAlertElement;
    new (): HTMLIonAlertElement;
};
```

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

System:

   NodeJS : v8.11.3 (/usr/local/bin/node)
   npm    : 6.7.0
   OS     : macOS Mojave
```

### Windows
Also happening on a windows machine:

![image](https://user-images.githubusercontent.com/4970737/52407427-8be33c00-2ad0-11e9-8c59-bba393298973.png)

```
Ionic:
 
   ionic (Ionic CLI)             : 4.10.2 (C:\Users\K.Shah.KS1\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0
 
System:
 
   NodeJS : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

Is WebStorm not able to parse something or is the default tsconfig.json or something wrong?

Maybe this is related: https://github.com/ionic-team/ionic/issues/14784
and https://github.com/ionic-team/ionic/issues/15867

Thank you very much in forward.

@michaelcamper mentioning you here, because you had the same problem.

**Comment by brandyscarney** [comment]
Thanks for the issue! Are you still seeing this with latest? The linked issues seem to have been closed.

**Comment by StefanRein** [comment]
@brandyscarney 
Thank you, the issue is resolved.

![image](https://user-images.githubusercontent.com/4970737/56466863-bed27600-6417-11e9-9157-90599ec48b08.png)
