### ISSUE TITLE
[ionic 4.0.0]: App hangs at White Screen after Splash Screen.

### ISSUE THREAD

**Issue by hemantsain0811** [ionic-team/ionic#17412]
I upgraded my project from v4 beta to stable v4 and trying to run my app in Android 5.0 but it stuck on white screen just after splash screen.

Here is my ionic info

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.3, (and 10 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/hsain/Library/Android/sdk)
   NodeJS            : v10.11.0 (/usr/local/Cellar/node/10.11.0/bin/node)
   npm               : 6.7.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

I am getting error `The key "viewport-fit" is not recognized and ignored.

<img width="1308" alt="screenshot 2019-02-07 at 3 43 02 pm" src="https://user-images.githubusercontent.com/43957411/52404480-1fc40080-2aef-11e9-89a7-2d1bff07ad4d.png">

**Comment by EugeneNews** [comment]
have you tried to un-comment lines in polyfills.js ?

**Comment by hemantsain0811** [comment]
Yes, I tried to un comment lines from polyfills.js but still getting the same error.
Here is my polyfill.ts file:

`import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

import 'core-js/es6/array';
import 'classlist.js';
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
import 'web-animations-js';
import 'zone.js/dist/zone';`

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! Would you be able to try on the latest version of `cordova-plugin-ionic-webview`? Here are instructions for upgrading from 2.x to 3.x: https://github.com/ionic-team/cordova-plugin-ionic-webview#migrating-to-3x

Also, are you testing on an Android emulator or on an actual device?

Thanks for using Ionic!

**Comment by hemantsain0811** [comment]
I tested on both real device as well as on emulators but getting same white screen.

**Comment by liamdebeasi** [comment]
Hi @hemantsain0811,

Thanks for the additional info! Would you be able to provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by blazekas** [comment]
This problem has been known for at least 6 months (see #15438).
The solution was to close issue due to too many frustrated comments.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the follow up. This appears to be a different problem than the one you linked to, since you have already uncommented the polyfills in `polyfills.ts`.

Would you be able to:

1. Test in a *new* project (`ionic start myApp blank`) and see if this issue persists.
2. Send over your user agent string to verify your WebView/Chrome version. (you can log `window.navigator.userAgent` to the console to see this) 

After that, if things are still broken, can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by xpunch** [comment]
I fixing the white blank issue by adding "**es5BrowserSupport**" to **angular.json**
{
  "$schema": "./node_modules/@angular-devkit/core/src/workspace/workspace-schema.json",
  "version": 1,
  "defaultProject": "app",
  "newProjectRoot": "projects",
  "projects": {
    "app": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "www",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "assets"
              },
              {
                "glob": "**/*.svg",
                "input": "node_modules/ionicons/dist/ionicons/svg",
                "output": "./svg"
              }
            ],
            "styles": [
              {
                "input": "src/theme/variables.scss"
              },
              {
                "input": "src/global.scss"
              }
            ],
            "scripts": [],
            **"es5BrowserSupport": true**
          },

**Comment by liamdebeasi** [comment]
Hi @blazekas,

Can you confirm whether or not the solution posted by @xpunch works for you?

Thanks!

**Comment by xpunch** [comment]
@blazekas , I also upgrade ionic-webview to 3.0.0
After compare my project with newest ionic blank app, I found this solution. Maybe you can test whether ionic blank app can work fine in your mobile.
