### ISSUE TITLE
Expose more ionic date time/picker controller methods

### ISSUE THREAD

**Issue by Ross-Rawlins** [ionic-team/ionic#17416]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
The current ion date time does not expose all of the classes functions to the angular wrapper. In my case I need to set the valid days based on the current date, NOT the date emited but the current one in the date picker. So I would like to emit every change as an option and expose the method to re generate the column values.

After further investigation with another ionic dev I see that the datepicker is built on top of the picker controller. 

**Describe Preferred Solution**
Add an extra event that emits every value while the datepicker is open. 
Expose all functions to the angular wrapper

The request would be a function to refresh column values and to add a handler to each button in the columns

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by jorrit-wehelp** [comment]
I'd say the feature would be to 'support dynamic columns in ion-picker'.

Currently they are all 'static', created when you open the picker.
This causes e.g. bugs like https://github.com/ionic-team/ionic/issues/15794, where if you open with feb-29, the date ranges don't update when you change the month (so can't pick 30 in march).

So from the perspective of that bug, the datetime component also needs to be able to react to selections inside the picker and change the ranges/columns.

So exposing a way (probably through the PickerOption.columns) to get a callback would be nice.
Secondly, allow setting/changing the columns, and have the picker react to these changes while it is open.
