### ISSUE TITLE
Searchbar CSS Property: --border-radius

### ISSUE THREAD

**Issue by Kleinhummel** [ionic-team/ionic#17426]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Custom CSS Property for the **ion-searchbar**: --border-radius

**Comment by wedodesign** [comment]
why don't have that???

**Comment by Kensed** [comment]
Same here

**Comment by gbrits** [comment]
This works (Ionic4) in `global.scss`
```
.sc-ion-searchbar-ios {
  border-radius: 0px !important;
}
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20662 and will be available in an upcoming release of Ionic Framework.
