### ISSUE TITLE
Update popover to match MD spec (placement below trigger element)

### ISSUE THREAD

**Issue by daem0ndev** [ionic-team/ionic#17427]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Currently the ion-popover and popover controller positions overlays OVER the triggering / target element.
https://media.giphy.com/media/2A1KjUxeiYyn4rAZUk/giphy.gif

**Expected behavior:**

As per the MD spec, Default placement for a dropdown menu is typically positioned below the element that generates it.
https://puu.sh/CIKPM/21c27b4953.png

**Steps to reproduce:**

Use popover controller and pass in $event from the (click) event on an element.

**Related code:**

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.8.0 (/Users/daem0n/.nvm/versions/node/v11.6.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.2.1
   @angular/cli                  : 7.2.1
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 23 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/daem0n/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v11.6.0 (/Users/daem0n/.nvm/versions/node/v11.6.0/bin/node)
   npm               : 6.7.0
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61

```

**Comment by brandyscarney** [comment]
It looks like this was fixed by your PR: https://github.com/ionic-team/ionic/pull/17429

Thanks for the issue and PR!
