### ISSUE TITLE
Add 404 route to ion-router

### ISSUE THREAD

**Issue by corysmc** [ionic-team/ionic#17423]
# Feature Request

**Ionic version:**
[x] **4.0.1**

**Describe the Feature Request**
When a given URL route doesn't match the provided routes, there's a `console.error('[ion-router] the path does not match any route');` and nothing renders on the page. No component means that it's a dead page. The only way to get around this is to manually add `ion-route-redirect`s for each route you have changed, or anticipate the user might _accidentally_ navigate to.

**Describe Preferred Solution**
Provide a way to declare a default redirect for missing routes, via a default component string.
For example add a `@Prop() missingRouteComponent: string` so that any missing route can render the missing route component (e.g. a 404 page).

**Describe Alternatives**
Perhaps additional logic might be needed for other use cases, so maybe an event could be emitted instead, such as:
`@Event() ionRouteDidFail!: EventEmitter<RouterEventDetail>;`

**Related Code**
https://github.com/ionic-team/ionic/blob/master/core/src/components/router/router.tsx#L202

**Additional Context**
Provide 404 page for missing routes. So users NEVER get a blank page (which results in a dead app - has to restart/refresh to fix) - even if it doesn't match any routes.

**Comment by paulstelzer** [comment]
Thanks for the issue! This is not needed to be add to Ionic because you can do this with Angular Routing. Just add a wildcard and set it to your 404 page component.
