### ISSUE TITLE
ion-range does not respect steps

### ISSUE THREAD

**Issue by distante** [ionic-team/ionic#17435]
# Bug Report

**Ionic version:**

[x] **4.0.1**

**Current behavior:**
`ion-range` does not respect the `step` property

**Expected behavior:**
`ion-range` should respect the `step` property

**Related code:**
```
 <ion-range
          min="maxPeakDuration"
          [max]="maxPeak"
          step="1"
          [value]="peakDuration"
          color="secondary"
          (ionChange)="peakDurationChangeTo($event)"
        >
          <ion-label range-left>0s</ion-label>
          <ion-label range-right>{{ maxPeakDuration }}s</ion-label>
        </ion-range>
```
![code](https://user-images.githubusercontent.com/5490201/52460979-4f195280-2b6d-11e9-8d29-3e5a949e384a.gif)

**Ionic info:** 
```
Ionic:

   ionic (Ionic CLI)             : 4.10.1 (C:\Users\distante\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.0
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (12 plugins total)

System:

   Android SDK Tools : 26.1.1 (C:\Users\distante\AppData\Local\Android\sdk)
   NodeJS            : v10.14.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.5.0
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment]
Hi @distante,

Thanks for opening an issue with us!

As per the [ion-range docs](https://ionicframework.com/docs/api/range/), `step` specifies the value granularity. In this case, the value of the range is going to change by 1.

This does not affect "snapping" to a value which is what I believe you may be referring to here. The `snaps` property causes the range knob to snap to tick marks that are evenly spaced based on the `step` property value. You can see how this would work in the demos on the docs.

I am going to close this issue, but feel free to reply if you still think there may be a bug. Thanks for using Ionic!

**Comment by distante** [comment]
I see this has changed from v3 to v4.  Sorry for the wrong bug report.
