### ISSUE TITLE
ion-select readonly property

### ISSUE THREAD

**Issue by Sarfarazsajjad** [ionic-team/ionic#17439]
# Feature Request

**Ionic version:** **4.0.0**

**Feature**
ion-select readonly property

**Feature Request Description**
There needs to be a way to make ion-select field read-only, and not just disabled because disable also changes color of the field and make it un-selectable for copying its value etc.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! `readonly` on a select is not currently part of the native `select` spec, so I'm going to close this for now.

Thanks for using Ionic!
