### ISSUE TITLE
ionic4 autocomplete component missing

### ISSUE THREAD

**Issue by sivakumar55** [ionic-team/ionic#17440]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by bossjon** [comment]
duplicate of [#17181](https://github.com/ionic-team/ionic/issues/17181)

**Comment by liamdebeasi** [comment]
I am going to close this as a duplicate of #17181. Thanks for using Ionic!
