### ISSUE TITLE
Ionic Back Button Not appearing if clicked on a link same as current route.

### ISSUE THREAD

**Issue by arihantdaga** [ionic-team/ionic#17445]
# Bug Report

**Ionic version:**
[x] **4.0.0**

**Current behavior:**

I have a sidebar application. in the side menu i have router links like this
```
<ion-menu-toggle auto-hide="false" *ngFor="let p of appPages">
<ion-item [routerDirection]="'root'" [routerLink]="[p.url]" lines="none">
              <ion-icon slot="start" [name]="p.icon"></ion-icon>
              <ion-label>
                {{p.title}}
              </ion-label>
</ion-item>
</ion-menu-toggle>
// appPages - 
appPages = [
    {
      title: 'Home',
      url: '/home',
      icon: 'home'
    },
    {
      title: 'Order History',
      url: '/myorders',
      icon: 'basket'
    }
]
```
I have pages like this - 
Home Page
Order List Page
Order Detail Page
 
If i go from my orders list page to Order detail page by clicking an order it shows back button in order detail page. Thats expected behavior.  Now, if i am in order list page and from side menu i again clicked on order list page(/myorders), after that when i click on an order, i am navigated to order detail page but ion back button is not appearing in the order detail page now. 

**Expected behavior:**
Ion back button should appear in the order detail page. 

**Steps to reproduce:**
Above pasted code should be sufficient. 

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.10.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.0.7
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 4.1.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 8 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/xman/Library/Android/sdk)
   NodeJS            : v10.15.1 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

```

**Comment by liamdebeasi** [comment]
Hi there,

As of Ionic 4, the back button is not added by default to the navigation bar. Here is a link to the list of breaking changes, along with an example of how to include the back button: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#back-button

You'll need to explicitly include the back button on every page that you want it to show up on. Let me know if you are still running into issues after trying that. Thanks!

**Comment by arihantdaga** [comment]
I did include the <ion-back-button> in the page. And then somewhere i read about the new back button that <ion-back-button> is smart enough to know when to show the button or not based on location history. But if router direction is root - a.k.a.` [routerDirection]="'root'"` Then if we click the same link where we are right now, after that whatever page we navigateForward to , it doesnt show the back button in that next page, while it should have.

**Comment by liamdebeasi** [comment]
Thanks for the additional info! Would you be able to provide a repository that has the code necessary to reproduce this issue?

Thanks!

**Comment by juanparadox** [comment]
I'm having the same issue. I have a list of items that all have an href. I click on an item, navigate to the page, then hit the back button in the UI to go back to the list. If I click on the same item again the animation comes in from the left instead of the right and the back button is gone.

**Comment by juanparadox** [comment]
I got my back button to start showing again by ditching the `href` attribute and using `routerLink` and `routerDirection="forward"` (in this case I was going forwards and then backwards). This no longer removes my back button when revisiting a page.

**Comment by liamdebeasi** [comment]
Hi @juanparadox,

Are you able to provide a repository with the code required to reproduce this issue? 

Thanks!
