### ISSUE TITLE
Remove circular Dependencies

### ISSUE THREAD

**Issue by Kikketer** [ionic-team/ionic#17456]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Compiling with Webpack will throw a circular dependency error.  Currently I'm unable to run the webpack build as it is, and with that unable to get Ionic to work.
Maybe something in the project needs to change (see the git repo link below) since the Ionic conference app seems to work fine (I just don't want to convert to typescript).

**Expected behavior:**
No circular dependencies

**Steps to reproduce:**
Similar to https://github.com/ionic-team/ionic/issues/13797 but with Ionic 4.

Using the following plugin:
```
const CircularDependencyPlugin = require('circular-dependency-plugin')
...
  plugins: [
    new CircularDependencyPlugin({
      // `onDetected` is called for each module that is cyclical
      onDetected({ webpackModuleRecord, paths, compilation }) {
        console.log('circular dependencies', paths)
      },
      // set the current working directory for displaying module paths
      cwd: process.cwd()
    }),
```
in my webpack, I'm getting the report:

```
circular dependencies [ 'node_modules/@ionic/react/dist/components/index.js',
  'node_modules/@ionic/react/dist/components/navigation/IonTabs.js',
  'node_modules/@ionic/react/dist/components/index.js' ]
circular dependencies [ 'node_modules/@ionic/react/dist/components/navigation/IonTabs.js',
  'node_modules/@ionic/react/dist/components/index.js',
  'node_modules/@ionic/react/dist/components/navigation/IonTabs.js' ]
circular dependencies [ 'node_modules/@ionic/react/dist/components/navigation/IonTabBar.js',
  'node_modules/@ionic/react/dist/components/index.js',
  'node_modules/@ionic/react/dist/components/navigation/IonTabBar.js' ]
circular dependencies [ 'node_modules/@ionic/react/dist/components/navigation/IonRouterOutlet.js',
  'node_modules/@ionic/react/dist/components/index.js',
  'node_modules/@ionic/react/dist/components/navigation/IonRouterOutlet.js' ]
/Users/n0148094/Documents/projects/aws-workgrid-saas-clients/node_modules/toposort/index.js:35
      throw new Error('Cyclic dependency' + nodeRep)
```

**Related code:**

https://github.com/Kikketer/CapacitorTest/tree/with-react

Clone the repo (with-react branch).  Run `yarn` to install the dependencies then run `yarn build`.

**Other information:**
https://github.com/ionic-team/ionic/issues/13797

The 13797 issue states that it will be addressed in version 4.

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI) : 4.10.1

System:

   NodeJS : v8.12.0
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by jthoms1** [comment]
Could you please try with the latest release? @ionic/react@0.0.5

Thanks!
