### ISSUE TITLE
Spellcheck not working on iOS and not showing red dot underline

### ISSUE THREAD

**Issue by jassiwalia001** [ionic-team/ionic#17466]
# Bug Report

**Ionic version:**

[x] **3.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

I tried spellcheck="true" and also autocorrect="on".  But it not showinf red dotted lines

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us!

Would you be able to post the output of running `ionic info`?

**Comment by nikz38** [comment]
Hi there, I have the same problem with Ionic 4. I've tried on blank project. Here is the output of `ionic info`:
```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/Users/nikola/.nvm/versions/node/v10.4.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.5
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 4 other plugins)

System:

   NodeJS : v10.4.0 (/Users/nikola/.nvm/versions/node/v10.4.0/bin/node)
   npm    : 6.1.0
   OS     : macOS Mojave
   Xcode  : Xcode 10.1 Build version 10B61
```

**Comment by liamdebeasi** [comment]
Hi there,

Which device/browser are you testing this on? The following example is working for me in Chrome 72:

```
<ion-input value="this is an misspelled exampull"></ion-input>
```

**Comment by nikz38** [comment]
Hello, 

Yes its working in Chrome but it doesn't work on ios simulator or ios device.

**Comment by liamdebeasi** [comment]
Hi there,

I am seeing the red dots on iOS. A few thoughts:

1. The red dots do _not_ work for me when using a third-party keyboard (such as Gboard). The red dots only seem to work when using the built in Apple keyboard. This was true for for the Mail application as well as Mobile Safari and an Ionic app.

2. You will need to put `spellcheck="true"` on the `ion-input` for spellcheck to be turned on. By default, spellcheck is turned off: https://ionicframework.com/docs/api/input#properties

Can you try these two things out and let me know if you are still running into this issue? Thanks!

**Comment by nikz38** [comment]
Hi, thank you for your answer. 

I'm not using any third party keyboard on ios (I'm aware that there are problems with third party keyboard on android concerning this issue).

Also I was trying with `spellcheck="true` on the `ion-input` but still can't get red dots. 

So basically I just created empty tab based project and added this code on the second tab:
```
<ion-header>
  <ion-toolbar>
    <ion-title>
      Tab Two
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  <ion-item>
    <ion-input
    type="text"
    value="this is an misspelled exampull"
    spellcheck="true"></ion-input>
  </ion-item>
</ion-content>
```

This is screen shot of the emulator:
![Screen Shot 2019-03-18 at 4 14 31 PM](https://user-images.githubusercontent.com/12057220/54541344-06d62700-499a-11e9-8dec-936e183f8821.png)

and this one is screen shot of the device:
![IMG_0052](https://user-images.githubusercontent.com/12057220/54541371-181f3380-499a-11e9-839d-43f313ffc8c9.PNG)

**Comment by liamdebeasi** [comment]
Hi there,

I was able to test on iOS 12.1 as well as the iOS 12.2 beta. It seems like this works on iOS 12.2, but not on iOS 12.1 (I have not tested previous version of iOS).

When tapping a misspelled word on both of these versions, the text will highlight red and iOS will suggested alternative spellings.

I tested this on a device running iOS 12.2 and the result was consistent with what I got running on an iOS 12.2 simulator. I do not have a device running iOS 12.1 with me currently, but I can give that a try when I get access to it later.

**iOS 12.2**
![Simulator Screen Shot - iPhone SE - 2019-03-19 at 09 09 48](https://user-images.githubusercontent.com/2721089/54608301-d1c3e600-4a26-11e9-805f-ba6bbcc24560.png)

**iOS 12.1**
![Simulator Screen Shot - iPhone 5s - 2019-03-19 at 09 10 07](https://user-images.githubusercontent.com/2721089/54608328-da1c2100-4a26-11e9-8dc5-3d9560b31ee7.png)

**Comment by nikz38** [comment]
Hi and thanks for the answer,
I don't have 12.2 beta on simulator or device, I have 12.1.4 on device and 12.1 on simulator. But when I click on misspelled word, it doesn't get red dots. I don't know why is that, it should show red dots.
Please let me know know when you test on 12.1 ios version.

**Comment by liamdebeasi** [comment]
Hi there,

I tested this on iOS 12.1 on a device and was unable to get the red dots. I think this may just be an issue in iOS 12.1. I am going to research this issue a bit more to see if it is indeed that.

For reference, here's the website I used if you would like to test on your device: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck

**iOS 12.1 (Device)**
![Image from iOS](https://user-images.githubusercontent.com/2721089/54619052-65eb7880-4a3a-11e9-82c1-c4fcfe07ce7a.png)

**Comment by nikz38** [comment]
I think there was a problem with previous versions also but I don't have a device to check if that is the case. I've tested my ios device on the link that you send, I also cant get red dots.

**Comment by liamdebeasi** [comment]
I checked the MDN spellcheck example on iOS 12.0 and iOS 11.4 simulators and got the same result of no red dotted underline.

I am going to close this as it doesn't appear to be an Ionic issue. For further questions feel free to post on our [forums](http://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com). Thanks!
