### ISSUE TITLE
Cannot get componentProps in subpage when using ion-nav

### ISSUE THREAD

**Issue by qiluo** [ionic-team/ionic#17465]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I'm building a modal with sub navigation (some subpages). From first sub page to another sub page, I need ionNav instance to push another sub page, then I'm thinking about how can I get ionNav in the first sub page.

For the ion-nav root, I did
```
this.nav.setRoot(FirstSubPage, {
      componentProps: {
        ionNav: this.nav,
      },
    });
```

in FirstSubPage, I tried to get componentProps either by an input or NavParams, however it's always undefined
```
export class FirstSubPage implements OnInit {
  @Input() ionNav: IonNav;

  constructor(
    private navParams: NavParams,
  ) { }

  ngOnInit() {
    console.log(this.ionNav);
    console.log(this.navParams.get('ionNav'));
  }

  goAnother() {
    // need ionNav here
    this.ionNav.push(AnotherSubPage);
  }
}
```

Does anyone know how to do sub navigation when using ion-nav?

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.1, (and 9 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/Dev/Android/android-sdk-macosx)
   ios-deploy        : 1.9.4
   ios-sim           : 6.1.2
   NodeJS            : v10.14.2 (/usr/local/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by KevinKelchen** [comment]
If you're using something like `@ViewChild(IonNav) ionNav: IonNav;` to get a handle to the `IonNav` before passing it into `componentProps`, make sure you wait until at least `ngOnInit` to access that `ViewChild` property or it may be undefined.

**Comment by qiluo** [comment]
I figured out how to get such params, actually the whole second parameter
```
this.nav.setRoot(FirstSubPage, {
      componentProps: {
        ionNav: this.nav,
      },
    });
```

was in navParam.data, so I should get it by `navParams.get('componentProps')['ionNav']`, or I should
```
this.nav.setRoot(FirstSubPage, {
        ionNav: this.nav,
    });

this.navParams.get('ionNav')
```

I don't know if it's implementation bug or document bug

**Comment by BDominik** [comment]
Hi, I have a question.
I'm really struggling to use ion-nav in ionic 4 tabs.
Can you help me where I need to put the ion-nav tag, in order to be abble to push and pop pages inside tabs page.
Also the tabs page using angular router.
But inside the tabs I want to push and pop pages.
Is it possible?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
