### ISSUE TITLE
IonicDev App Error

### ISSUE THREAD

**Issue by GleidsonHenrique** [ionic-team/ionic#17469]
After update IonicDev App, I'm getting a error. IonicDev stop after I click on a button to login on my app, but at last version or app installed on android it works correctly.

IonicDev works perfectly on IOS, this issue it's happening just on 2 Android. App Store shows version 1.0.2.
https://itunes.apple.com/us/app/ionic-devapp/id1233447133?mt=8

**ionic info:**
ionic (Ionic CLI)  : 4.3.1 (/usr/local/lib/node_modules/ionic)
Ionic Framework    : ionic-angular 3.9.2
@ionic/app-scripts : 3.2.2

**IonicDev App version (error):**
[x] **1.0.4**

**IonicDev App version (works perfectly):**
[x] **1.0.2**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Comment by tommyarn** [comment]
I am getting the same issue . @GleidsonHenrique  did you solve the issue ?

**Comment by GleidsonHenrique** [comment]
@tommyarn, I solved it by downloading an earlier version. Probably is not the best way, but I did not want to waste time. Maybe in the next update they fix it.

https://apk.tools/details-ionic-dev-app-apk/

**Comment by tommyarn** [comment]
@GleidsonHenrique - thanks . sorry for the late reply but I also followed what you mentioned

**Comment by brandyscarney** [comment]
Thanks for the issue! Are you still experiencing problems with DevApp?
