### ISSUE TITLE
[UIWebView] Input fields inside iframe doesn't accept input on iOS

### ISSUE THREAD

**Issue by sanidkpc** [ionic-team/ionic#17468]
**Ionic version:**

[x] **4.x**

**I'm submitting a ...** 

[x ] bug report
[ ] feature request

**Current behavior:**

On iOS, text input inside an `<iframe>` won't receive any text value when typing using device keyboard. Immediately after tapping on the text input, the device keyboard popup then typing on keyboard, text input won't receive any value.

**Expected behavior:**

Input fields inside an iframe should behave as they do in a mobile web browser. The user should be able to drag the cursor and select/delete text and then be able to continue typing in the text field.

**Other information:**

Using `WkWebView cordova-plugin-ionic-webview` from https://github.com/ionic-team/cordova-plugin-ionic-webview. I can type in the input field inside the iframe but this plugin has some major issues with **cookies set/stored in iOS**. In our app authentication, **cookies are not set/stored in iOS or ignored on First Application Execution** [simulator or physical device].
WkWebView cookies related issues:
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/22
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/300

**Iframe Content:**

Iframe remote src content are written in AngularJS.

**System info:**
```
xcode: Version 10.1 (10B61)
Device: iPhone 7 plus v 11.4
```

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)  : 4.0.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : browser 5.0.4, ios 4.5.4

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.4
   NodeJS            : v8.11.2 (/usr/local/bin/node)
   npm               : 6.2.0
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61

Environment:

   ANDROID_HOME : /Users/bs228/Library/Android/sdk
```

**Comment by maddada** [comment]
Same issue since 4.0.0-rc.2 of @ionic/angular.
I downgraded to version 4.0.0-rc.1 and I can now type in input fields on iOS and Safari.
I posted this as an issue a while ago and didn't receive any replies.
