### ISSUE TITLE
ion-alert does not properly adjust when keyboard resize mode is set to body

### ISSUE THREAD

**Issue by kyleabens** [ionic-team/ionic#17471]
# Bug Report

**Ionic version:**

[x] **4.0.1**

**Current behavior:**

Changing the keyboard resize mode in the config.xml with
`<preference name="KeyboardResizeMode" value="body" />`
results in the alert dialog box staying stationary when keyboard is opened.

**Expected behavior:**

The alert should be centered vertically when the keyboard is opened because ion-alert is within the body.

I am aware that this works when the keyboard resize mode is set to native but there are serious issues when focusing inputs.  That issue can be found here #17457

**Steps to reproduce:**

1. Create a new ionic app
2. Add `<preference name="KeyboardResizeMode" value="body" />` to config.xml
3. Add a button that opens ion-alert with an input.
4. $ ionic cordova run ios -l -c -- --buildFlag="-UseModernBuildSystem=0"

**Other information:**

Also while we're at it the input line within an alert that uses md mode appears to have some sort of radius along the edges.  See below image.

<img width="272" alt="screen shot 2019-02-12 at 9 43 16 am" src="https://user-images.githubusercontent.com/25699262/52643303-bbb48a00-2eaa-11e9-9259-2280d4cf9dcc.png">

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.3.1
   @angular/cli                  : 7.3.1
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 8 other plugins)

System:

   ios-deploy : 2.0.0
   ios-sim    : 7.0.0
   NodeJS     : v10.15.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61
```

**Comment by ippeiukai** [comment]
dup of #17776?
