### ISSUE TITLE
Ability to change ion-button text-decoration to none

### ISSUE THREAD

**Issue by welshcathy** [ionic-team/ionic#17470]
# Feature Request

**Ionic version:**
[x] **4.0.1**

**Describe the Feature Request**
All the ion-buttons are in capitals. I'd like to have buttons have no text-decoration and are not capitals.

Ion-button .button-native text-decoration style is in the shadow dom and not exposed via any of the custom CSS properties provided.
https://ionicframework.com/docs/api/button#css-custom-properties

I see that other attributes were added during beta testing.
https://forum.ionicframework.com/t/css4-ion-button-height-how-to-change/141419

Can you add custom CSS property --text-decoration too please?
I don't want all my buttons to have upper case text :)

**Describe Preferred Solution**
You should be able to use this in your scss to remove capitalisation from button texts:
```
ion-button {
    --text-decoration: none;
}
```

**Describe Alternatives**
I can't see any other way to get around this.

**Additional Context**
https://ionicframework.com/docs/api/button#css-custom-properties

Someone else has already asked how to style the button inner text 
https://forum.ionicframework.com/t/how-to-add-styles-to-ion-button-inner-text/148987

**Comment by brandyscarney** [comment]
Thanks for the issue! So you're actually looking for `text-transform` for uppercase, see the mdn docs here: https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform

All of the text properties that can be inherited *are* inherited in a button. So the following will work in the case of a button:

```
ion-button {
  text-transform: none;
}
```

Here's a larger list of the inheritable font properties:

```
font-family: inherit;
font-size: inherit;
font-style: inherit;
font-weight: inherit;
letter-spacing: inherit;
text-decoration: inherit;
text-overflow: inherit;
text-transform: inherit;
text-align: inherit;
white-space: inherit;
```

And a codepen example of styling them: https://codepen.io/brandyscarney/pen/gqKGNv?editors=1100#0

I'll also add this to the forum post, thanks!
