### ISSUE TITLE
ion-range dualknob's position is not updating while dynamically changing their values 

### ISSUE THREAD

**Issue by maedewiza** [ionic-team/ionic#17475]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Dynamically update values (upper, lower) of dual knobs and the position of knobs will not change. They will stuck at the same place, although the values ​​show that they should be somewhere else.

**Expected behavior:**

Change position of knobs, while changing their values.

**Steps to reproduce:**

Create ion-range with dual knob. Next change their values from code.

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.13.1
   @angular-devkit/schematics    : 7.3.1
   @angular/cli                  : 7.3.1
   @ionic/angular-toolkit        : 1.3.0

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.17
   @capacitor/core           : 1.0.0-beta.17
```

**Comment by KillerCodeMonkey** [comment]
@maedewiza as a workaround try to wrap your "dynamic change" in a timeout. Maybe this helps.

**Comment by abennouna** [comment]
@maedewiza can you show your code or post a repo?

**Comment by maedewiza** [comment]
After several ionic serve, it repaired itself. Still, thank you for the answer.

**Comment by andleer** [comment]
I believe I have seen this behavior. Happy to research and code up a simple repo.

**Comment by andleer** [comment]
I can confirm I am having issues. The single range slider updates as expected. The dual slider does not. Binding via `[(ngModel)]` and changing the bound variable.

https://github.com/andleer/ionic4-range-bug

Ionic:

   ionic (Ionic CLI)             : 4.10.3 (C:\Users\andrew.robinson\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

System:

   NodeJS : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.8.0
   OS     : Windows 10

**Comment by andleer** [comment]
I would love to take a stab at fixing this and creating a PR. Not sure where to start but will read about it tonight... If you guys feel this is urgent, have at it.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! So this behavior is by design. Mutating an object will not trigger a view update, but returning a new copy of the object will. (see: https://stenciljs.com/docs/reactive-data/#updating-an-object)

The following will not work:

```
dualKnobElement.value.lower += 1;
```

The following will work:

```
dualKnobElement.value = {
  lower: lower + 1,
  upper: upper
}
```

This is not explained very clearly in the documentation, so I will be sure that gets updated.

Are you able to confirm whether or not returning a new copy of the object resolves this issue for you? Thanks!
