### ISSUE TITLE
ion-header on tabs page overlays content 

### ISSUE THREAD

**Issue by maedewiza** [ionic-team/ionic#17472]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

&lt;ion-header> overlays content, when it is placed on tabs page globally, instead of specific tabs.

**Expected behavior:**

&lt;ion-content>, which fit to &lt;ion-header> placed globally on tabs page, as it is fitting to &lt;ion-tabs>

**Steps to reproduce:**

Use default tabs template and place into tabs.page.html &lt;ion-header>, next remove &lt;ion-header> from tab1, tab2, tab3. &lt;ion-header> will overlay the content.

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.13.1
   @angular-devkit/schematics    : 7.3.1
   @angular/cli                  : 7.3.1
   @ionic/angular-toolkit        : 1.3.0

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.17
   @capacitor/core           : 1.0.0-beta.17
```

**Comment by garyganyang** [comment]
i dont think you should add header in tabs.page.html

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
