### ISSUE TITLE
Ionic V4 ion-select default model value not showed

### ISSUE THREAD

**Issue by MiguelSyll** [ionic-team/ionic#17485]
Hello Ionic Team

I have this code:

`<ion-grid>`						
`  <ion-row align-items-center>`
`    <ion-col size="3"><ion-label>Objekt</ion-label></ion-col>`
`    <ion-col size="9">`
`      <ion-select [(ngModel)]="currentObjektId" placeholder="Objekt Auswahl" class="myCustomSelect" (ionChange)="changeObjekt()" multiple="false" okText="OK" cancelText="abbrechen" [interfaceOptions]="selectOptions">`
`        <ion-select-option *ngFor="let o of objekte" [value] = "+(o.id)">{{o.kurzname}}</ion-select-option>	`					
`      </ion-select>`
`    </ion-col>`
`  </ion-row>`			
`</ion-grid>`

I load currentObjektId (number) and the select does not show the element, however when one clicks the select and the object is already selected.

objekte			: { id: number,kurzname: string, online_id: number, admin: number,bilder: number }[];

Ionic Information:

   ionic (Ionic CLI)             : 4.10.2 (C:\Users\----\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.0.0, (and 23 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\----\AppData\Local\Android\android-sdk)
   NodeJS            : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm               : 4.6.1
   OS                : Windows 10

**Comment by LuizTokuhara** [comment]
Yes I got the same problem since RC.
If you have 3 ion-selects with default values, the first one will be blank and the other 2 will show the default value.
It shows blank but the value is already selected.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! Would you be able to provide a repository with the code required to reproduce this issue?

Thanks for using Ionic!

**Comment by MarkRabey** [comment]
I'm seeing this as well, specifically when running on a device or simulator. Both iOS and Android. I'm trying to make a repo to duplicate the error, and of course it's working in that repo. Unfortunately, I am not able to share my actual project, but I'll keep working on this repo. @MiguelSyll Are you able to share your repo?

**Comment by MiguelSyll** [comment]
Hello guys

I am sick and I have some problems now. Can someone of you create a repo?

Am Do., 21. Feb. 2019, 17:12 hat Mark Rabey <notifications@github.com>
geschrieben:

**Comment by MarkRabey** [comment]
@MiguelSyll I'm working on it. It seems to be working in that repo though. Trying to break it now! Hahahaha

**Comment by pipoa** [comment]
**not able to show form value with formcontrol too**
It used to be okay in Ionic3, after changed tag name for Ionic4 required,  selected value not show anymore.

```
<ion-select formControlName="selectedOpt" (ionChange)="onOptChange($event)" multiple="false">
    <ion-select-option value="0">Option1</ion-select-option>
    <ion-select-option value="1">Option2</ion-select-option>
    <ion-select-option value="2">Option3</ion-select-option>
    <ion-select-option value="3">Option4</ion-select-option>
</ion-select>
```

**Comment by MiguelSyll** [comment]
I created a new Ionic project with two ion-selects and I tried to reproduce the problem. But I could not repeat it.
I do not know what can be the reason for this problem, but in my real project it is still happening that the selected Object is not showed.

Regards 

Miguel

**Comment by MiguelSyll** [comment]
I created this Repo: https://github.com/MiguelSyll/ion-select-repo

**Comment by liamdebeasi** [comment]
Hi @MiguelSyll,

Does the repo you posted have a reproduction of this issue? I know you said in your previous post that you were unable to reproduce the problem again.

Thanks!

**Comment by MiguelSyll** [comment]
Hello. No, my Repo works fine, I mean, without the Problem. I thought that
maybe someone else could uses the Repo to introduce his Code and reproduces
the problem.


Am Do., 7. März 2019 um 15:22 Uhr schrieb Liam DeBeasi <
notifications@github.com>:
