### ISSUE TITLE
ion-datetime with no value set shows the first January of the current year when opened

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic#17481]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

ion-datetime control within a reactive form with no value set shows 1st of January 2019 (current year) when opened

**Expected behavior:**

It should default to the current date (this is how it works in Ionic 3)

**Steps to reproduce:**

See below

**Related code:**
Here is ion-datetime control inside a reactive form
`<ion-datetime formControlName="<FIELD_NAME>" pickerFormat="MM/DD/YYYY" displayFormat="DDD, D MMM YYYY"></ion-datetime>`
Please note that the control is set to null in the reactive form

StackBlitz (https://stackblitz.com)
Not possible due to this bug https://github.com/ionic-team/ionic/issues/16354

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/Users/alexryltsov/.nvm/versions/node/v10.14.2/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.17
   @capacitor/core           : 1.0.0-beta.17

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (5 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/alexryltsov/Library/Android/sdk/)
   NodeJS            : v10.14.2 (/Users/alexryltsov/.nvm/versions/node/v10.14.2/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by ryaa** [comment]
This bug could be related to https://github.com/ionic-team/ionic/issues/16436 and https://github.com/ionic-team/ionic/issues/15792

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! I currently have a PR open that will fix this: https://github.com/ionic-team/ionic/pull/17443

Hoping to get this merged in soon.

Thanks for using Ionic!
