### ISSUE TITLE
Ionic4 multi tab were activated, which should not happen

### ISSUE THREAD

**Issue by garyganyang** [ionic-team/ionic#17480]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
use tabs example project, runs on android device, while tab1 is active, press&hold tab2 for seconds then release, you will see tab1 and tab2 are both in active state/color

**Expected behavior:**
expect page changes to tab2, and only tab2 is active

**Steps to reproduce:**
use tabs example project, runs on android device, while tab1 is active, press&hold tab2 for seconds then release, you will see tab1 and tab2 are both in active state/color

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.9.0 (C:\Users\admin\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 4 other plugins)

System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 7

```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for filing an issue with us! Would you be able to provide a repository with the code required to reproduce this issue?

**Comment by garyganyang** [comment]
> Hi there,
> 
> Thanks for filing an issue with us! Would you be able to provide a repository with the code required to reproduce this issue?

i followed instruction on https://ionicframework.com/getting-started#cli and run "ionic start myApp tabs" to get it startup
