### ISSUE TITLE
Date picker warnings and errors (prod mode) when scrolling

### ISSUE THREAD

**Issue by Jock-G** [ionic-team/ionic#17497]
**Ionic version:**

[x] **4.0.1.**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**

Date picker scrolling is really slow and imprecise on android emulators and android devices it also causes warnings in developent mode and errors in production builds. Those errors are probably causing the performance problem. 
I have experienced this issue in a real project using ion-datetime and using the picker controller but it occurs also in a blank project adding only an ion-datetime in its home.page.html.

The warnings/errors are:
Development mode (emulator):
Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
![image](https://user-images.githubusercontent.com/45603603/52782548-a2990e00-304f-11e9-8e6c-ba0e09e37625.png)

Production mode in an android phone I am getting erros not warnings (in emulator they are still warnings):

![image](https://user-images.githubusercontent.com/45603603/52784435-69fc3300-3055-11e9-84c9-a123932af107.png)

**Expected behavior:**

Fast and smooth scrolling and without throwing errors.

**Steps to reproduce:**

Create a new project and add an ion-date time in its home page.
Build without production mode and run the app in an android emulator or android device and scroll through options of the pickers to get the warnings.
Build in production mode and run the app in an android device and scroll through options of the pickers  to get the errors.

**Related code:**

```

// In a new blank project:
Just add an <an ion-datetime> at home.page.html:

<ion-header>
  <ion-toolbar>
    <ion-title>
      Ionic Blank
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content padding>
  The world is your oyster.
  <p>If you get lost, the <a target="_blank" rel="noopener" href="https://ionicframework.com/docs/">docs</a> will be your guide.</p>

  <ion-item>
    <ion-label>Date</ion-label>
    <ion-datetime display-format="MMM DD, YYYY HH:mm"></ion-datetime>
  </ion-item>
</ion-content>



// Using the picker controller (in my real project) I am getting the exact same behaviour and errors. The code I am using is:

async onSelectDuration() {
    this.duration_options = [ ];
    this.createDurationOptions();

    const picker = await this.picker_controller.create({
      buttons: [{
        text: 'Cancel',
        role: 'cancel'
      },
        {
          text: 'OK',
          handler: (data) => {
            this.my_form.controls['duration'].setValue(data.minutes.value);
            this.changeSelectedIndex(data.minutes.value);
            this.change_detector.detectChanges();
          }
        }],
      columns: [
        {
          name: 'minutes',
          options: this.duration_options,
          selectedIndex: this.duration_selected_index
        }
      ],
      cssClass: 'select-minute-picker'
    });
    await picker.present();
  }

// Both codes from  <ion-datetime> and picker controller works fine receiving options for the pickers and emmiting the selected option but the scroll behaviour and errors are ruinig the UX.

```

**Other information:**

This issue may be related with #15256 wich is about ion-refresher but it seems to have the same problem than ion-datetime and the picker controller.

It also may be related with #16681.

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/xx/Android/Sdk)
   NodeJS            : v10.0.0 (/usr/local/bin/node)
   npm               : 6.7.0
   OS                : Linux 4.15

```

**Comment by liamdebeasi** [comment]
Hi @Jock-G,

Thanks for opening an issue with us! I can confirm these are duplicates of #15256 and #16681, so I am going to close this.

For the datetime performance, we are collecting all datetime issues into a [central list](https://github.com/ionic-team/ionic/issues/16630) so that we can address them all at once. We're not forgetting about your issue, just trying to keep them all together. 🙂 

Thanks for using Ionic!
