### ISSUE TITLE
linear-gradient does not work with CSS Variables

### ISSUE THREAD

**Issue by alexdhill** [ionic-team/ionic#17491]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When creating a button using --color and --border-color cannot be set to linear-gradient. The only variable that displays a gradient is --background for solid fill buttons.

**Expected behavior:**

When setting --border-color: linear-gradient(...) the gradient should appear on the line around the outlined button, however it just displays as the primary color from the global CSS Variables.

**Steps to reproduce:**

Create an ion-button with fill="outline". In the CSS set ion-button variable --border-color: linear-gradient(to left, #fff 0%, #000 100%);

**Related code:**

```
ion-button.login {
    position: absolute;
    right: 4in;
    top: .1in;
    width: 2in;
    height: .5in;
    font-weight: bolder;
    --border-color: linear-gradient(to left, #fff 0%, #000 100%);
}

<ion-button class="login" shape="round" fill="outline" (click)="login()" box-shadow="false">
    Log In
</ion-button>
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

System:

   NodeJS : v10.14.2 (/usr/local/bin/node)
   npm    : 6.7.0
   OS     : macOS Mojave
```

**Comment by brandyscarney** [comment]
Thanks for the issue!

So, that gradient doesn't work as a border color on a native button either. As far as I know you can't pass a gradient to `border-color`, see this blog here: https://css-tricks.com/gradient-borders-in-css/

However, you can use a `border-image`. The downside is it won't work with `border-radius`. There are resources available online though with workarounds to this (one is mentioned in the blog above).

In your case your best bet would likely be to just add the border-image to the `ion-button` itself and hide our border color, so the following CSS:

```
ion-button.login {
  border-style: solid;
  border-width: 2px;
  border-image: linear-gradient(to left, #fff, #000);
  border-image-slice: 1;
  
  --border-color: transparent;
}
```

with the HTML:

```
<ion-button fill="outline" class="login">
  Ionic Border Gradient
</ion-button>
```

I don't think `border-image` is a CSS variable we will be adding. We like to keep our CSS variables limited to things we are overriding, but it's not totally out of the question.

I created a Codepen representing the different examples of a native button and Ionic button: https://codepen.io/brandyscarney/pen/aXjryX?editors=1100
