### ISSUE TITLE
[@ionic/core 4.0.1] Spinner follows an out of bounds track

### ISSUE THREAD

**Issue by wcmhc** [ionic-team/ionic#17501]
# Bug Report

**Ionic version:**
[x] **4.0.1**

**Current behavior:**
The spinner that appears in the loader (among other places, including the spinner tag itself) follows a path which is not correct. See the gif hosted on Imgur below for exactly what is happening. This occurs on only one of the devices we've tested

https://i.imgur.com/BRU7VaY.gif - Recorded from the Chrome Dev Tools screencasting tool, but occurs on the device itself

**Expected behavior:**
The spinner should follow a concise circular pattern, rather than the stretched variation shown in the gif

**Steps to reproduce:**
1. Install Ionic Core on a barebones Cordova project
2. Include some form of the `<ion-spinner></ion-spinner>` tag on a working page. The test repo uses the LoadingController to demonstrate other components are working as intended.
3. Load the app onto a phone (may or may not show incorrectly)

**Related code:**
I realize now that I originally named the repo wrong. The actual issue is the Spinner, **_not_** the Loading container
https://github.com/wcmhc/IonLoadingOffCenter

**Other information:**
Device: Physical `Blu Pure XR` running Android 6.0

**Ionic info:**
We are running a Cordova stack without the Ionic CLI due to specific requirements. We use `@ionic/core` from NPM, currently installed is v4.0.1

**Comment by bashoogzaad** [comment]
I recognize this behaviour when building my Ionic4 app for Electron. In the browser and on iOS and Android the spinner works fine, but in Electron it also follows this path outside the loading square. Maybe this information is helpful when trying to find why this happens.

**Comment by chrisbinnefeld** [comment]
I recognized the same behaviour on older Android WebViews e.g. 61.

**Comment by wcmhc** [comment]
One of our QA testers reported the same issue with the following emulator. I successfully reproduced locally
```
Build: OSM1.180201.007
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:8.1.0/OSM1.180201.007/4586646:user/release-keys'
Release Name: Android Oreo 8.1
Bootloader: unknown
Radio: (unknown)
Network: Android
Kernel: Linux version 3.18.91+ (android-build@wpdv8.hot.corp.google.com) (gcc version 4.9 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Tue Jan 9 20:32:02 UTC 2018

Name: Nexus_5X_API_27
CPU/ABI: x86
Target: google_apis_playstore [Google Play] (API level 27)
Skin: nexus_5x
AvdId: Nexus_5X_API_27
avd.ini.displayname: Nexus 5X API 27

```
