### ISSUE TITLE
menu.componetn problem

### ISSUE THREAD

**Issue by zajcman** [ionic-team/ionic#17507]
# Bug Report

**Ionic version:**

[x] **4.10.2

**Current behavior:**
Good morning

I have got strange problem with **ion-menu** when i use it as component inside **ion-split-pane**.

I see Menu title but i can't see menu elements (see print screen)

Can be bug ?

Thank you for your help!

[Printscreen  1](https://discourse-cdn-sjc1.com/ionicframework/uploads/default/original/3X/d/3/d302558479fdff7cfce009a150327c6de4b1fb88.png)

[Printscreen 2](https://discourse-cdn-sjc1.com/ionicframework/uploads/default/original/3X/3/8/38da344ce3f6e9a23c84bb8abdd8b9d56c2e1289.png)

**Expected behavior:**
Menu see in correct mode

**Steps to reproduce:**
1) Create blank app
2) create menu ( ionic g component menu ) 
3) insert menu code in menu component 
4) insert menu as component  in ion-split-pane ( app.component.html)

**Related code:**
**app.component.html**
```


<ion-app>
  <ion-split-pane contentId="menu-content">
    <!--  our side menu  -->
    <ion-menu contentId="menu-content">
      <app-menu>

      </app-menu>


     
    </ion-menu>





    <!-- the main content -->
    <ion-router-outlet id="menu-content"></ion-router-outlet>


  </ion-split-pane>
</ion-app>
```
**menu.component.html** 
```


 
      <ion-header>
        <ion-toolbar>
          <ion-title>Menu 1</ion-title>
        </ion-toolbar>
      </ion-header>
     
          <ion-content>
              6 <br> 
              7<br>
              4<br>
      
            </ion-content>
```

**Comment by liamdebeasi** [comment]
Hi there,

You likely need to import `MenuComponent` into `app.module.ts`. I am going to close this as it is more of a support question. If you have other questions feel free to post in our [Slack](https://ionicworldwide.herokuapp.com) or on our [forums](http://forum.ionicframework.com).

Thanks for using Ionic!
