### ISSUE TITLE
ion-item text-center not working ionic 4

### ISSUE THREAD

**Issue by PurpleEdge2214** [ionic-team/ionic#17509]
# Bug Report

**Ionic version:**
[x] **4.10.3**

**Current behavior:**
`<ionic-item text-center>This is some centered text</ion-item>
`
Text is still left aligned

**Expected behavior:**
As per docs...
"Text Alignment
Items left align text and add an ellipsis when the text is wider than the item. See the Utility Attributes Documentation for attributes that can be added to <ion-item> to transform the text."

If text-center is not a valid Utility Attribute for an ion-item, please update the docs.

**Steps to reproduce:**
As above

**Comment by brandyscarney** [comment]
Thanks for the issue! Could you please run `ionic info` and paste that output when you create issues? The `4.10.3` version is the CLI version which doesn't explain as much when it's a framework issue. 🙂 

As for the original issue, the item is required to be wrapped in an `ion-label` in v4:

```
<ion-item text-center>
  <ion-label>Text centered</ion-label>
</ion-item>
```

I am seeing the above working here: https://codepen.io/brandyscarney/pen/XOOJzv

All of our usage examples show the item is using an `ion-label`: https://ionicframework.com/docs/api/item#usage

And we have it added to the breaking changes here: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#label-required

If you find any uses where this is missing in the docs please create a new issue on our [ionic-docs](https://github.com/ionic-team/ionic-docs/issues) repository. Thank you!

**Comment by PurpleEdge2214** [comment]
Thanks, I missed that "text" must be contained within a label...

"Items are elements that can contain text, icons, avatars, images, inputs, and any other native or custom elements."
