### ISSUE TITLE
User can choose February 31 in ion-datetime

### ISSUE THREAD

**Issue by maedewiza** [ionic-team/ionic#17510]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

In the ion-datetime user can choose dates that do not exist, for example, February 31. Only after selecting February, closing ion-datetime and clicking again on the ion-datetime, the number of days is updated to 28.

**Expected behavior:**

Dynamically update the number of days in ion-datetime.

**Steps to reproduce:**

Create ion-datetime. Select February. In days will be 29-31. Exit ion-datetime. Select ion-datetime again. Only now the number of days will update to 28.

**Related code:**

-->

```
<ion-datetime display-format="DD/MM/YYYY">
```

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.13.1
   @angular-devkit/schematics    : 7.3.1
   @angular/cli                  : 7.3.1
   @ionic/angular-toolkit        : 1.4.0

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.17
   @capacitor/core           : 1.0.0-beta.17
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! I’ve added this to issue #16630 to keep track of. We’re going to close out the individual issues and address all of the Datetime issues at once. We’re not forgetting about your issue, just trying to keep them all together. 🙂 

Thanks for using Ionic!
