### ISSUE TITLE
[ionic v4] <a [routerLink]="./sub"> doesn't work if it was re-clicked 

### ISSUE THREAD

**Issue by Chambers0415** [ionic-team/ionic#17511]
# Bug Report

**Ionic version:**
ionic 4.0.1
angular/router 7.2.5

**Current behavior:**
I was testing the V4 page navigition, here, in Page 'tab1' I want to navigate a subPage(Tab1SubPageComponent) using <a [routerLink]="./sub">, the 'sub' children-router was defined in tabsModule. Here is the problem, the 'sub' page can not navigate when the tag <a/> was re-clicked, actually when i re-click it , there is nothing happens. 

HERE is the project link https://github.com/Chambers0415/ionicV4-router-test
Page 'tab1' is in folder /src/app/tab1
component 'Tab1SubPageComponent' is in folder /src/app/tab1-sub-page
'sub' children-router is in file /src/app/tabs/tabs.router.modules.ts

Thanks for your time

**Comment by liamdebeasi** [comment]
Thanks for the issue. Does this still occur with the latest version of Ionic Framework?
