### ISSUE TITLE
[ionic v4] - The background color of toobar and input is white below Android 7.0, and the custom background cannot be loaded.

### ISSUE THREAD

**Issue by yangqian0817** [ionic-team/ionic#17529]
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (C:\Users\yangqian\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.0, (and 10 other plugins)

System:

 (G:\workspace\Android_SDK).6
   NodeJS            : v10.13.0 (D:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

The background of ion-content can be modified as follows:

```
ion-content {
    --background: url('../assets/imgs/background.png') no-repeat center center / cover;
}

ion-toolbar {
    --background:  url('../assets/imgs/toolbar.png') no-repeat center center / cover;
}
```

This problem has been bothering me for many days. Everything works well on the web, but that's what happens when it's packaged as an Android app. Cordova-plugin-ionic-webview has been updated to the latest, and this problem still exists.

**Comment by phfoxer** [comment]
U can use .scroll-content to change the background image in your project

**Comment by YsmDad** [comment]
@phfoxer Background images in the content area can be displayed through the -- background settings. Background images of ion-toolbar and ion-input cannot be loaded.

**Comment by barocsi** [comment]
I have generated colors with the https://ionicframework.com/docs/theming/color-generator
but it's not reflected in my app at all, especially primary color is not reflected in the background color of the toolbar.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
