### ISSUE TITLE
ion-datepicker triggering Reachability on iOS 

### ISSUE THREAD

**Issue by nvahalik** [ionic-team/ionic#17526]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Reachability will be activated and the application will slide down when you scroll down within the datetime picker.

**Expected behavior:**
The component should allow the user to enter the date and time easily without activating Reachability.

**Steps to reproduce:**
1. Trigger an `<ion-datetime>` element on an iPhone X or other device with [Reachability](https://support.apple.com/en-us/HT208204) enabled.
2. Scroll down several items. 

This happens on every `ion-datetime` element in the application and, obviously, only when running on the device itself. Not sure if Dev App would reproduce it or not as this is a bug reported to me by someone else.

![ionic-datetime-issue](https://user-images.githubusercontent.com/632120/52971097-c7f18900-337b-11e9-869a-d97c9078c95e.gif)

**Related code:**
None

**Other information:**
Wish I could help here!

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.7.1 (/Users/nvahalik/.nvm/versions/node/v10.15.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic 5.2.9, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 14 other plugins)

System:

   NodeJS : v10.15.0 (/Users/nvahalik/.nvm/versions/node/v10.15.0/bin/node)
   npm    : 6.6.0
   OS     : macOS Mojave
   Xcode  : Xcode 10.1 Build version 10B61
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! I’ve added this to issue #16630 to keep track of. We’re going to close out the individual issues and address all of the Datetime issues at once. We’re not forgetting about your issue, just trying to keep them all together. 🙂 

Thanks for using Ionic!
