### ISSUE TITLE
Datetime Picker Min/Max Displays Incorrectly

### ISSUE THREAD

**Issue by blakezeisler** [ionic-team/ionic#17521]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
If Datetime picker Min and Max values are set, then the user can not select a day that is a valid date within the bounds of the min/max, but outside the min/max day range.

**Expected behavior:**
User should be able to select a day between the Min and Max date rage set.

**Steps to reproduce:**
Set the Datetime picker Min = '2019-02-17', Set a Max = '2020-02-17'. As a user try to select '2019-03-05'.

**Related code:**
https://angular-ionic4-test-nvde1r.stackblitz.io

**Other information:**

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.0.7
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.0

System:

   NodeJS : v10.14.2 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS High Sierra
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! I’ve added this to issue #16630 to keep track of. We’re going to close out the individual issues and address all of the Datetime issues at once. We’re not forgetting about your issue, just trying to keep them all together.

Thanks for using Ionic!
