### ISSUE TITLE
No "content" property in Loading Component options. No way to put custom HTML in IonLoading

### ISSUE THREAD

**Issue by distante** [ionic-team/ionic#17520]
In the [Loading Docs  'creating' part](https://ionicframework.com/docs/api/loading#creating)  there is this part:

>> any optional HTML can be passed in the `content` property.

But there is no `content` property exposed:

![image](https://user-images.githubusercontent.com/5490201/52911601-3532ea80-32a6-11e9-8ef4-5bc2a63ca3c3.png)

Using HTML in the `message` property will just render the `html` as string and using angular safeHTML will yield this:
```
const loader = this.loadingCtrl.create({
        message: this.sanitizer.bypassSecurityTrustHtml(loadingText) as string + 'test',
        spinner: 'dots'
});
```
>>SafeValue must use [property]=binding: 

That worked in Ionic 3

Ionic Info
```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (C:\Users\distante\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.0
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.3, (and 21 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\distante\AppData\Local\Android\sdk)
   NodeJS            : v10.14.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.5.0
   OS                : Windows 10
```

**Comment by kensodemann** [comment]
Closing this as PR #18126 fixes the documentation as it currently stands, and Feature Request #18135 addresses the need to address this in some way, whether it is through the reinstatement of the `content` parameter mechanism or some other mechanism is an open question.
