### ISSUE TITLE
Add support for Capacitor's Haptics plugin

### ISSUE THREAD

**Issue by sbannigan** [ionic-team/ionic#17528]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
Support Capacitor's built-in Haptics plugin for ionic components.

**Describe Preferred Solution**
Add support for Capacitor Haptics in [haptic.ts](https://github.com/ionic-team/ionic/blob/master/core/src/utils/haptic.ts). This should be supported since it is included out of the box with capacitor to avoid needing another Cordova plugin to accomplish the same thing.

**Comment by liamdebeasi** [comment]
Support for Capacitor's Haptics plugin has been added: https://github.com/ionic-team/ionic/blob/33be1f061ebbe27ee22e357c394f112af42ec360/core/src/utils/native/haptic.ts. Thanks!
