### ISSUE TITLE
ion-range with dual knob fails to update knobs on changes to bound ngModel variable

### ISSUE THREAD

**Issue by andleer** [ionic-team/ionic#17563]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Using `ng-model` binding, a single knob `ion-range` control works correctly. Using the dual knob config fails to move the sliders or emit `ionChange()` events when the bound variable is changed.

NOTE: This bug has been partially detailed in [issue #17475](https://github.com/ionic-team/ionic/issues/17475) but this write up is more complete. I would suggest closing that issue. Your call.

**Expected behavior:**
Both single and dual knob renderings should update the knobs and emit `ionChange()` when the bound variable is changed.

See attached animated GIF. Notice that changes to both single and dual sliders results in logged data. Clicking on the single slider buttons logs twice (once from the button click and once from the onChange event). Clicking on the dual buttons only generates a single log entry from the button click code.

![ionic4-range-bug](https://user-images.githubusercontent.com/1568494/53174107-d7e8b300-359d-11e9-9837-f3d66047913d.gif)

**Steps to reproduce:**
See [github repo](https://github.com/andleer/ionic4-range-bug)

**Related code:**

https://github.com/andleer/ionic4-range-bug

**Ionic info:**

Ionic:

   ionic (Ionic CLI)             : 4.10.3 (C:\Users\andrew\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

System:

   NodeJS : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! So this behavior is by design. Mutating an object will not trigger a view update, but returning a new copy of the object will. (see: https://stenciljs.com/docs/reactive-data/#updating-an-object)

The following will not work:

```
dualKnobElement.value.lower += 1;
```

The following will work:

```
dualKnobElement.value = {
  lower: lower + 1,
  upper: upper
}
```

This is not explained very clearly in the documentation, so I will be sure that gets updated.

Are you able to confirm whether or not returning a new copy of the object resolves this issue for you? Thanks!

**Comment by andleer** [comment]
Yes. Issue resolved. Further confusing because I am pretty sure my code did work with v4.0.1 but I will review it and create a new issue if I am still having issues there. I think my original issue was related min and max changes.

This code work as as desired with 4.0.2:
`this.bindingDual = { lower: this.bindingDual.lower + change, upper: this.bindingDual.upper, };`

Thanks. Let me know if there are other bugs that might need documenting. I will continue to write up the ones I come across. Again, close this issue for now. Also close #17475. Not mine but the same non-issue.
