### ISSUE TITLE
Problems when I press the back button several times on android. Ionic v4

### ISSUE THREAD

**Issue by jacastellanosc** [ionic-team/ionic#17578]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

Problems when I press the back button several times on android.
Example: I have 3 Pages (Home, Profile and Chat)
When I am in the chat page and I press the back button of the device twice, the Profile page is leaving the z-index higher than that of the Home page. This makes the Profile page "transparent" on top of the home page and does not allow you to interact with the elements on the Home page.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for filing an issue with us! Can you provide a repository with the code required to reproduce this issue? Also can you provide the output of running `ionic info`?

Thanks!
