### ISSUE TITLE
hardware back button doesnt work

### ISSUE THREAD

**Issue by Rainson12** [ionic-team/ionic#17589]
# Bug Report

**Ionic version:**
[x] **4.0.2**

**Current behavior:**
The hardware back is pressed nothing happens.

**Expected behavior:**
The navigation should go back one item in the history

**Steps to reproduce:**
* Create a new ionic app using ionic cli.
* Add new page using ionic cli
* Add ion-button to the home page and add href tag and refer to the newly created page
* use Back button

**Other information:**

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (C:\Users\dev\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\dev\AppData\Local\Android\Sdk)
   NodeJS            : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Comment by Rainson12** [comment]
I have figured out that outlet.canGoBack() is always false. Why is that?

**Comment by dylanvdmerwe** [comment]
https://github.com/ionic-team/ionic/issues/16611

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! I’ve added this to issue #16611 to keep track of. We’re going to close out the individual issues and address all of the hardware back button issues at once. We’re not forgetting about your issue, just trying to keep them all together. 🙂

Thanks for using Ionic!
