### ISSUE TITLE
Bug: iOS Input shows ugly box on click

### ISSUE THREAD

**Issue by lassesteffen** [ionic-team/ionic#17584]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

A random input box appears in an input field when clicking it. Same for iOS on phone and in chrome.
[Bug Video](https://youtu.be/aKcOw52oALg)

**Expected behavior:**

There should be no box appearing

**Steps to reproduce:**

Just click the input field and it appears.

**Related code:**

If you need some I can provide it.

**Other information:**

Appears on the phone (capacitor) and in the browser (chrome)

**Ionic info:**

@ionic/core 4.0.2 in combination with Vue and @ionic/vue

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! Can you provide a repository with the code required to reproduce this issue? Thanks!

**Comment by lassesteffen** [comment]
[Repo](https://github.com/lassesteffen/ionic-ios-input-bug )

If you need more assistance let me know! Happy to help.

**Comment by lassesteffen** [comment]
Run npm run serve and click in the login field
