### ISSUE TITLE
native diagnostic  error

### ISSUE THREAD

**Issue by PraveenBiradar** [ionic-team/ionic#17598]
//  native plugins
import { Diagnostic } from '@ionic-native/diagnostic/ngx';

  ionViewWillEnter(){

  
      this.diagnostic.isLocationEnabled().then(enabled=>{
        alert("Location setting is " + (enabled ? "enabled" : "disabled"));
      }).catch(error=>{

        console.log("isLocationEnabled error: "+JSON.stringify(error));
      });
    
  }

error:
ERROR TypeError: Object(...) is not a function
    at Diagnostic.isLocationEnabled (vendor.js:127427)
    at ListPage.webpackJsonp.11.ListPage.ionViewWillEnter (main.js:506)
    at ViewController._lifecycle (vendor.js:35671)
    at ViewController._willEnter (vendor.js:35569)
    at NavControllerBase._willEnter (vendor.js:73491)
    at vendor.js:73384
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:5135)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)

**Comment by duyetnk** [comment]
native plugins can not run in browsers,
you must run your app in device

**Comment by PraveenBiradar** [comment]
FYI,
I am running it on  device (MI A1).

In device only it's throwing error.

**Comment by duyetnk** [comment]
do you run it on ios platform,
some methods work only on android

**Comment by PraveenBiradar** [comment]
No its a Android(version 9) Mobile

**Comment by duyetnk** [comment]
can you show app.module.ts and page.ts

**Comment by PraveenBiradar** [comment]
PFA.


*Regards,*
*Praveen Biradar*

**Comment by duyetnk** [comment]
sorry, can't see anythings

**Comment by PraveenBiradar** [comment]
PFA  ZIP
*Regards,*
*Praveen Biradar*

**Comment by PraveenBiradar** [comment]
PFA zip file,it has app.module.ts and page.ts
[diagnostic.zip](https://github.com/ionic-team/ionic/files/2900279/diagnostic.zip)

**Comment by PraveenBiradar** [comment]
I shared you the zip in git hub..

Please have a look

**Comment by duyetnk** [comment]
nothing wrong in your files,
may be you should reinstall the plugin

**Comment by PraveenBiradar** [comment]
for native location accuracy  also its throwin same error

*Regards,*
*Praveen Biradar*

**Comment by PraveenBiradar** [comment]
> nothing wrong with your files,
> may be you should reinstall the plugin

after reinstall also  i am facing  the same issue 
PFA zip which has confi.xml  and package.json

[config_xml_package_json.zip](https://github.com/ionic-team/ionic/files/2900503/config_xml_package_json.zip)

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us. I am going to close this as this is for an Ionic 3 application. This issue tracker is only for v4 issues.

Additionally, it looks like you were following plugin setup instructions for Ionic 4, which could be why you are running into these issues. Be sure to follow the instructions for Ionic 3 here: https://ionicframework.com/docs/v3/native/

**Comment by PraveenBiradar** [comment]
I didn't understand why you closed the issue.

The ionic version used is 4.2.1

**Comment by liamdebeasi** [comment]
Hi there,

`4.2.1` is the version of the Ionic CLI, not Ionic Framework. In the package.json file you posted, you are requiring Ionic Framework version `3.9.2`.

**Comment by PraveenBiradar** [comment]
Okay ...
I will check and let you know

**Comment by PraveenBiradar** [comment]
Hi there,
I am new to ionic,please forgive me if I do any mistakes...

These are  the  versions I used
'ionic": "^4.2.1",
"ionic-angular": "^3.9.2",
"ionic-img-viewer": "^2.9.0",
"ionic-native": "^2.9.0",

Is this 3v app or 4v app?

**Comment by liamdebeasi** [comment]
Hi there,

No worries at all! 🙂 

`"ionic": "^4.2.1"` is the version of the Ionic Command Line Interface (the utility that helps you setup an Ionic app)
`"ionic-angular": "^3.9.2"` is the version of Ionic Framework (what you actually use to build the application)

So, you are using a v3 application.

**Comment by PraveenBiradar** [comment]
Oh !!

Thanks a lot

**Comment by PraveenBiradar** [comment]
Hi there,

Thanks a lot..

I implemented the code with reference to https://ionicframework.com/docs/v3/native/location-accuracy/ and it's working fine😊
