### ISSUE TITLE
Ionic v4 ion-slides content not scrolling

### ISSUE THREAD

**Issue by johnV65** [ionic-team/ionic#17595]
I have a component inside of ion-slide and its is the scroll not working

here is my code :

<ion-slide style="height:100%">
  <main-search></main-search>
</ion-slide>

<ion-slide>

    <div style="height:100%">Page 2 </div>

</ion-slide>

The main-search component contain a list element that not scrolling vertical

**Comment by PraveenBiradar** [comment]
i am also facing the same error
