### ISSUE TITLE
Native location accuracy

### ISSUE THREAD

**Issue by PraveenBiradar** [ionic-team/ionic#17601]
I have implemented the same with reference to ionic docs but it's throwing error.

PFA PDF file which has source code+ error information.
[DOC-20190220-WA0004 (2).pdf](https://github.com/ionic-team/ionic/files/2900259/DOC-20190220-WA0004.2.pdf)

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us. I am going to close this as this is for an Ionic 3 application. This issue tracker is only for v4 issues.

Additionally, it looks like you were following plugin setup instructions for Ionic 4, which could be why you are running into these issues. Be sure to follow the instructions for Ionic 3 here: https://ionicframework.com/docs/v3/native/
