### ISSUE TITLE
Cannot override mode styles on many components

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic#17608]
The docs for [overriding mode styles](https://ionicframework.com/docs/theming/platform-styles#overriding-mode-styles) aren't accurate for several components, e.g.

```css
.ios ion-item {
  ...
}
```

**Comment by brandyscarney** [comment]
I believe certain components need be updated to include the following:

```
...createThemedClasses(this.mode, 'item'),
```

I'm not sure why this was removed as it looks intentional, but will look into this.

**Comment by brandyscarney** [comment]
This has been added for the `4.3.0` release. The full list of components that have the mode class now can be seen in the table at the bottom of this PR: https://github.com/ionic-team/ionic/pull/17838

It can be used like the following:

```
ion-item.md {
  // MD styles
}

ion-item.ios {
  // iOS styles
}
```

Note that this is only a problem for components that are being used inside of a shadow element. If using light DOM you can still use the documented way to style modes.
