### ISSUE TITLE
React: Implement VirtualScroll Component

### ISSUE THREAD

**Issue by jthoms1** [ionic-team/ionic#17613]
The virtual scroll component needs to be updated for the react api.

On completion the usage example needs to be updated.

**Comment by markhoward02** [comment]
You can do it jthoms1!

**Comment by markhoward02** [comment]
I used this easy to use package to implement a virtualized item list with sticky headers that works well.  This is why I am so happy Ionic opened itself up to React... It opens up a large pool of react components to bring into our Ionic apps.
react-tiny-virtual-list
https://github.com/clauderic/react-tiny-virtual-list
(https://github.com/clauderic/react-tiny-virtual-list/issues/53  (sticky headers example at this link)

**Comment by elylucas** [comment]
Closing as this won't be implemented. We will offer a guide in the docs on the recommended approach to virtual scrolling in the near future.

**Comment by voliva** [comment]
It's a bit disappointing that ionic won't support this component on React...
