### ISSUE TITLE
ion-ripple-effect is not working inside ion-item

### ISSUE THREAD

**Issue by arrian0511** [ionic-team/ionic#17618]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When trying to add a ripple effect inside ion-item for a click event, the ion-ripple-effect is not working as expected.

**Expected behavior:**
ion-ripple-effect should work inside ion-item element.

**Related code:**
```
<ion-item (click)="navigateToDetailsPage()">
    <ion-label>Details page label</ion-label>
    <div class="ion-activatable">
        <ion-ripple-effect type="bounded"></ion-ripple-effect>
    </div>
</ion-item>
```

**Other information:**
I found out that the one that causing the issue is the ```pointer-events: none``` that was modified in this fixed. https://github.com/ionic-team/ionic/pull/16955, so setting ```pointer-events: unset``` will solve the problem. However, I'm not sure if that will cause an issue on 16955 fixed?

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! The `ion-activatable` class should be applied to `ion-item`. Your code should look like this:

```
<ion-item (click)="navigateToDetailsPage()" class="ion-activatable">
    <ion-label>Details page label</ion-label>
    <ion-ripple-effect type="bounded"></ion-ripple-effect>
</ion-item>
```

Can you confirm this works for you?

**Comment by arrian0511** [comment]
Thanks for your answer @liamdebeasi , it's now working. Cheers.
