### ISSUE TITLE
Animation applied with delay less than 1s causes flickering and hanging in iOS and Safari

### ISSUE THREAD

**Issue by devzone88** [ionic-team/ionic#17627]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Go to this repository and run it in Safari or in iOS build (iPhone using Cordova platform). You will see that when you navigate to sub page and come back to home page, the animation will lag and hang up. Please notice the first card specially i.e Any animation whose delay is less than 400ms will causes this in browser (Safari) but in iPhone 8 Plus till 900ms delay causes hanging while applying 1s delay in animation, the effect is not noticeable. Look at the following:
[Video](https://imgur.com/a/D8OPDon)

**Expected behavior:**
The animation should be smoother on coming back to home page. 

**Steps to reproduce:**

Add new ionic project, Apply zoomIn animation from animate.css library. 

**Related code:**
[https://github.com/devzone88/myTestApp](https://github.com/devzone88/myTestApp
)

```
<ion-card class="animated delay-400ms zoomIn" routerLink="/about">
    <ion-card-content>
      <h3>Card 3</h3>
    </ion-card-content>
  </ion-card>
```

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 4 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.0
   NodeJS     : v10.13.0 (/usr/local/bin/node)
   npm        : 6.8.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61
```

**Comment by dotnetdreamer** [comment]
Any workaround for this ??
