### ISSUE TITLE
Ionic 4: ion-item-sliding not working on page destroy

### ISSUE THREAD

**Issue by derickfelix** [ionic-team/ionic#17622]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
ion-item-sliding stop responding to touches and click events if the user closes the page using back-button or clicking two times on an ion-tab-button to go back to home if one of the list items is open (slided left or right).

**Steps to reproduce:**
1. The app must have tabs, and one item of some tab (say tab A) opens another page on top of it (Page B), so page B is a child of the page on the tab A.
2. Add an `ion-item-sliding` with `ion-item-options` on the page B.
3. Click on the tab A two times so you can back to the page of the tab A or click on the ion-back-button of page B, and then open the page B again.
4. See that click item-sliding won't make it slide.

**Additional Context:**
A quick workaround is to close the list item programmatically whenever an ion-back-button click event is fired, but I have no idea about how can I do that when the user clicks two times on the tab instead of using the ion-back-button. Closing the list on ngOnDestroy() doesn't work.

**Comment by leszekkadlof** [comment]
Same issue as #15599

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! Can you provide a repository with the code required to reproduce this issue? Also, can you post the output of running `ionic info`? Thanks!

**Comment by derickfelix** [comment]
I was using the version 4.0.0-rc.0 and it seems like it was already solved on the version 4.0.2, thanks for the reply.
