### ISSUE TITLE
[Improved Desktop Support] MouseOver (Hover) Effect

### ISSUE THREAD

**Issue by heinzburgstaller** [ionic-team/ionic#17624]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
Ionic components (ion-button, ion-item, etc.) do not have a (ripple) effect when the mouse cursor hovers over the component. A desktop app is more user friendly if the user has a visual clue which components are interactable.

**Describe Preferred Solution**
Ionic simple adds those effects to existing components, or has a configuration property to enable hover effects globally.

**Describe Alternatives**
Provide directives/CSS classes to help implement effects on behalf of a third party developer.

**Comment by brandyscarney** [comment]
Thank you for the issue! I'm going to close this in favor of https://github.com/ionic-team/ionic/issues/18279. I am tracking all of the components needing updates there. This PR will also make some big changes to hover, focused and activated: https://github.com/ionic-team/ionic/pull/19440
