### ISSUE TITLE
IE11 content projection with ngContent loses items styles 

### ISSUE THREAD

**Issue by domiSchenk** [ionic-team/ionic#17648]
# Bug Report

**Ionic version:**

[x] **4.0.2**

**Current behavior:**

In IE11 (only browser as far / Edge works) when an ionic component is used inside an ng-content and the content can be toggled the component losses its style.
In IE style are added to head, when the component is first rendered (visible) the styles are inside the head.
When its toggled(hidden) styles are removed and never added again, only if its complete destroyed.

Angular does parse what's inside an ng-content even if its not shown (templates are different).
so i think the problem may be the component thinks its still in DOM and therefore does not load the styles again,

Also in IE the style are special generated with a class something like `.sc-ion-button-md-64-h`
Why is it different in EDGE?

**Expected behavior:**

Style should be added again to HEAD.

If don't have time to fix could you point out were the magic happens?

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (C:\Users\dos\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.13.2
   @angular-devkit/schematics    : 7.3.2
   @angular/cli                  : 7.3.2
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.7.0
   OS     : Windows 10
```

**Comment by domiSchenk** [comment]
no response?

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! Would you be able to provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by domiSchenk** [comment]
i cant create a reproducible Repo right know :-(
(the bug is not shown when a new repo is created)
maybe it is fixed with the newest version.
