### ISSUE TITLE
V4 -Icon size not working

### ISSUE THREAD

**Issue by Entrecampos** [ionic-team/ionic#17657]
Ionic Framework               : @ionic/angular 4.0.2
**Bug: Doesn't resize the icon**

.html
`<ion-icon slot="start" color="green" class="iconSize" name="warning"></ion-icon>`

.scss
```
  .iconSize {
      font-size: 512px;
    }
```

 ionic info:

```
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0
```

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm not able to reproduce this on an icon, or an icon in an item. Judging by the `slot` I am guessing it is inside of another component. Could you please provide the full markup or a Codepen/repository that we can use to reproduce this? Thanks!

Here is a Codepen example using vanilla JS, but I also tried in the Angular conference app and couldn't reproduce: https://codepen.io/brandyscarney/pen/gEwbMq

**Comment by Entrecampos** [comment]
Thank you @brandyscarney ! 
It was a great help. 
I tried in the home page and did not give the error....
I am upgrading from 3 to 4 and the mistake was in the .scss
I was putting a 

```
page-my-modal {
.iconSize {
      font-size: 512px;
    }
}
```

Now is just

```
.iconSize {
      font-size: 512px;
    }
```

and works !

**Comment by brandyscarney** [comment]
@Entrecampos No worries! Glad it works now. 🙂
