### ISSUE TITLE
Loader/Modal Interaction iphone/ipad

### ISSUE THREAD

**Issue by trevordowdle** [ionic-team/ionic#17654]
# Bug Report

**Ionic version:**

[x] **4.x**
Ionic CLI 4.10.3

**Current behavior:**

When you present a loader
`loader.present();`
Then before dismissing the loader you open a modal to go on top.
```
 let modal = this.modalCtrl.create(LoginPinPage,{user:this.user,type:'pinCreate'});
 modal.present();
```
In chrome the modal inputs are accessible, you can type in them etc..
But in safari like on an iphone or ipad.  The fields are unresponsive.
**Expected behavior:**

Fields would be responsive on iphone/ipad

**Steps to reproduce:**

Present a loader and then show a modal with a form on top of the loader.
use iphone/ipad (safari) and the modal form/buttons can't be clicked.

**Related code:**

```
`loader.present();`
 let modal = this.modalCtrl.create(LoginPinPage,{user:this.user,type:'pinCreate'});
 modal.present();
```

**Other information:**
Not a huge deal, I find that I can dismiss the loader before showing the modal and the experience stays the same.  But it was misleading because chrome works when coding like this and so I didn't catch it right away.

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI) : 4.10.3

System:

   NodeJS : v10.15.0
   npm    : 6.6.0
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for this issue! Would you be able to provide a repository with the code required to reproduce this issue?

Thanks!
