### ISSUE TITLE
[ionic v4] ion-slides keyboard option

### ISSUE THREAD

**Issue by combefis** [ionic-team/ionic#17662]
**Ionic version:**
[x] **4.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
I added the keyboard options, described in the Swiper doc, to my ion-slides and it does not seem to work. Are all the options of Swiper supported by the ion-slides wrapping it? Nothing is mentioned in the Ionic doc about any limitations about the supported Swiper options.

**Expected behavior:**
I would have expected the keyboard "right arrow" and "left arrow" to change the visible slide of my ion-slides component.

**Steps to reproduce:**
I just created a ion-slides component and added:
```
slideOpts = {
    keyboard: {
    enabled: true,
    onlyInViewport: false,
  }
  };
```

**Related code:**
See previous section.

**Other information:**
N/A

**Ionic info:** 
```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (C:\Users\...\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.6.0
   OS     : Windows 10
```

**Comment by DamenQuixotic** [comment]
I am having the same issue. Whether or not I wait for the ionSlidesDidLoad or not I cannot enable keyboard navigation.

I believe it is more tied to any swiper options not working. For example, trying to set autoplay or effect flip with options does not seem to work.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! We support most of the Swiper options, but I can confirm that keyboard control is not working with `ion-slides`. We typically try to stay away from 3rd party libraries having control over keyboard inputs as they tend to interfere with the built-in Ionic components.

That being said, you should be able to add your own keyboard control layer in if you need that support (listen for keyboard events, respond by calling the appropriate slide methods, etc), though I realize this is not as ideal as being able to use the keyboard support provided by Swiper.

I am going to close this for now, but we are working on some improvements with how we handle `ion-slides` so we will definitely keep this issue in mind. Thanks for using Ionic!

**Comment by DamenQuixotic** [comment]
In the case of keyboard functionality I can recreate it pretty easily.

However the ionic documentation for ion-slides should be updated to state
two things.

One you don't support all of the swiper-api. And two, what parts of it's
API do you support.

Otherwise just straight up linking to their API is confusing and not
helpful.

**Comment by combefis** [comment]
@liamdebeasi thanks for you fast answer!

And @DamenQuixotic I agree that it should be made clear in the documentation that the options parameter is not just passed to Swiper as is, but is somewhat filtered.

**Comment by liamdebeasi** [comment]
Yes, I agree! We will update the documentation to make this clear. Thanks for the feedback!
