### ISSUE TITLE
ion-progress-bar with overlay

### ISSUE THREAD

**Issue by jtushar53** [ionic-team/ionic#17665]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
there should be provision to present ion-progress-bar with an overlay. 

**Describe Preferred Solution**

**Describe Alternatives**
Currently i can wrap ion-progress-bar in a div like below code

 
**Related Code**
```
.wrapper{
position: absolute;
  z-index: 99;
  height: 100%;
  width: 100%;
}

  <div class="progress-bar" *ngIf="loading">
    <ion-progress-bar type="indeterminate"></ion-progress-bar>
  </div>

```
**Additional Context**

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for submitting a feature request! I am going to close this as `ion-progress-bar` is meant to just be a basic component, not something that is tied to an overlay. If you need a progress bar in an overlay, you can create a modal and put an `ion-progress-bar` component in it.

Thanks for using Ionic!
