### ISSUE TITLE
ion-item should allow overflow css variable

### ISSUE THREAD

**Issue by tompap** [ionic-team/ionic#17670]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**

Currently item-inner and input-wrapper add some overflow:hidden, but due to webcomponent and how there are working it's not possible to override this settings.
We have a custom input that should be over the input but not possible due to overflow:hidden

**Comment by brandyscarney** [comment]
Thank you for the issue! Do you have an example of the HTML / CSS you are using so we can reproduce the issue and make sure we understand the use case? Here's a sample Ionic 4 Codepen if you would like to fork it: https://codepen.io/pen?template=aXENNW

**Comment by uniquejava** [comment]
I have the same request. My `.error` class has a style of absolute and I'd like my nested `.error` element sit on top of ion-item border. 
However the `ion-item`'s overflow is hidden. I'd like to set `ion-item`'s over flow as `visible`.



```html
  <ion-item>
        <ion-label position="fixed">口座番号</ion-label>
        <ion-input
          type="number"
          pattern="[0-9]*"
          (keydown)="onKeyDownLimitLength($event, 7)"
          inputmode="numeric"
          formControlName="acct_no"
          placeholder="数字7桁"
        ></ion-input>
        <span class="error">半角数字7桁で入力してください</span>
      </ion-item>
```

**Comment by uniquejava** [comment]
@brandyscarney Hi, I created some sample codepen code snippet here: https://codepen.io/uniquejava/pen/OqqyOj

You see the message `Please you need to enter 7 digits!` is not showing correctly.

The following are some visual effect we'd like to implement.
![image](https://user-images.githubusercontent.com/1049271/54897263-9fbcf300-4f02-11e9-953f-25f8bafe8e55.png)

**Comment by anagstef** [comment]
Hello! I have a case where overflow is needed for `ion-item` here: https://codepen.io/masimakopoulos/pen/oRPyKx

Also, I've opened a PR (#18410) adding this feature, where overflow css variable is exposed.
