### ISSUE TITLE
Keyboard overlaps with footer on iPhone XS

### ISSUE THREAD

**Issue by doender** [ionic-team/ionic#17675]
# Bug Report

**Ionic version:**
4.0.2

**Current behavior:**
On my iPhone XS, incorrect bottom padding is applied in action sheets and when the keyboard is expanded and a footer is used.

![padding-keyboard](https://user-images.githubusercontent.com/4175777/53738473-930f2700-3e8f-11e9-8e16-fb824916bde1.jpg)
![padding-actionsheet](https://user-images.githubusercontent.com/4175777/53738479-96a2ae00-3e8f-11e9-9a52-1052b4e1e2ee.jpg)

**Expected behavior:**
Enough padding is used so that the keyboard doesn't overlap the footer.

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (~/.nvm/versions/node/v10.6.0/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.2
   @angular-devkit/core       : 7.2.1
   @angular-devkit/schematics : 7.2.1
   @angular/cli               : 7.2.1
   @ionic/ng-toolkit          : not installed
   @ionic/schematics-angular  : 1.0.7

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.0, (and 19 other plugins)

System:

   Android SDK Tools : 26.1.1 (~/Library/Android/sdk)
   ios-sim           : 5.0.13
   NodeJS            : v10.6.0 (~/.nvm/versions/node/v10.6.0/bin/node)
   npm               : 6.1.0
   OS                : macOS
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! Would you be able to provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by jaco-terbraak** [comment]
Having the same issue.

It's caused by `src/components/input/input.ts:276`: `this._keyboardHeight = config.getNumber('keyboardHeight');`, which gets the value from `src/platform/platform-registry.ts`, which for ios has a keyboardHeight of 250. This is incorrect, as on the iPhone X, the keyboard height is 291.

**Comment by jaco-terbraak** [comment]
Here's a minimal Ionic v3 blank project which reproduces the problem: 
https://github.com/jaco-terbraak/ionic-ios-keyboard-height-bug

iPhone 8 (12.1):
![Simulator Screen Shot - iPhone 8 - 2019-03-20 at 11 33 05](https://user-images.githubusercontent.com/34056076/54677858-196c6f80-4b04-11e9-8d9d-81bfd8ad6540.png)

iPhone X (12.1):
![Simulator Screen Shot - iPhone X - 2019-03-20 at 11 31 45](https://user-images.githubusercontent.com/34056076/54677870-1f625080-4b04-11e9-8350-22222ef9e818.png)

**Comment by jaco-terbraak** [comment]
This happens on any iPhone X* model

**Comment by jaco-terbraak** [comment]
Also: note that the `KeyboardResize` preference in config.xml needs to be set to `"false"`

**Comment by liamdebeasi** [comment]
Hi @jaco-terbraak,

This issue tracker is only for Ionic 4 issues. If you are seeing this in an Ionic 4 application, can you provide a repository with the code required to reproduce that issue?

Thanks!

**Comment by jaco-terbraak** [comment]
@liamdebeasi I'm sorry -- I accidentally posted this in the wrong repo. I've moved the relevant info to https://github.com/ionic-team/ionic-v3/issues/993

**Comment by liamdebeasi** [comment]
Hi @doender,

Just wanted to follow up and see if you were still running into this issue. If so, can you provide a repository with the code required to reproduce this issue?

Thanks!
