### ISSUE TITLE
ionic4 not work android5 

### ISSUE THREAD

**Issue by zhiwo** [ionic-team/ionic#17683]
36/5000  
Ionic4 has been officially released, but this bug has not been fixed. Is there a good solution

**Comment by zhiwo** [comment]
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (/Users/zxdeer/Applications/install/node-v10.13.0-darwin-x64/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 4 other plugins)

System:

   NodeJS : v10.13.0 (/Users/zxdeer/Applications/install/node-v10.13.0-darwin-x64/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave

**Comment by liamdebeasi** [comment]
Hi there,

Would you be able to describe the issue you are seeing in more detail?

Answers to the following questions would be very helpful:
1. What part of your app does not work on Android 5?
2. Are you testing this on an actual device or an emulator?
3. Have you uncommented the polyfills in `polyfills.ts`? 
4. What is your device's user agent string? (you can log `window.navigator.userAgent` to the console to see this)

Thanks!

**Comment by zhiwo** [comment]
> Hi there,
> 
> Would you be able to describe the issue you are seeing in more detail?
> 
> Answers to the following questions would be very helpful:
> 
> 1. What part of your app does not work on Android 5?
> 2. Are you testing this on an actual device or an emulator?
> 3. Have you uncommented the polyfills in `polyfills.ts`?
> 4. What is your device's user agent string? (you can log `window.navigator.userAgent` to the console to see this)
> 
> Thanks!

Thank you very much. All right,polyfills.ts File comments not all open，now all open can
