### ISSUE TITLE
@ionic/react IonBackButton goBack: () => void

### ISSUE THREAD

**Issue by not-a-designer** [ionic-team/ionic#17688]
# Bug Report

**Ionic version:**

[x] **4.x**  ->  @ionic/react

**Current behavior:**
Using @ionic/react, the IonBackButton has an attribute 'goBack' and intellisense says it is of type '() => void' and it is a required. I am not sure what the expected method here is supposed to be. 'defaultHref' is also a required attribute that seeming provides the same function.
I have tried using `props.history.goBack/replace/push` and `() => <Redirect to="/" />` and none of these seem to work. this throws a browser console error:
```
TypeError: newView is undefined
```
It is unclear what method is required here
my work around is using the following: 
```
const goBack = () => {
    props.history.push('/components')
};

<IonButton fill="clear" onClick={goBack}>
    <IonIcon name="arrow-back" />
</IonButton>
```

**Expected behavior:**

**Steps to reproduce:**
```
<IonBackButton 
    defaultHref="/" //required
    goBack=         // required, accepts a method () => void
/>
```

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by jthoms1** [comment]
Here is an example of the usage. https://github.com/ionic-team/ionic-react-conference-app/blob/4a65a9400d006ff7df61a32cefb42bd586821887/src/pages/SpeakerDetail.tsx

Notice that goBack is a prop that is passed to the Route based Component and this method will need to be passed to the Button.

We are currently working on the navigation docs for Ionic React and hope to have more information available for developers soon.

**Comment by elylucas** [comment]
`goBack` has been removed and defaultHref is no longer a required but should be supplied. Look for these changes in the next beta release.
