### ISSUE TITLE
@ionic/react breaking React Router back and forward button

### ISSUE THREAD

**Issue by o-t-w** [ionic-team/ionic#17709]
# Bug Report

**Ionic version:**
 "@ionic/react": "0.0.5",
    "react": "^16.8.3",
    "react-dom": "^16.8.3",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1"

**Current behavior:**
I am using react-router. When I use the IonSelect element the back button is unreliable. The forward button of the browser is disabled. When I use a HTML select element I have _no problems_, which is why I think this is an Ionic bug. 

**Expected behavior:**
Back and forward buttons should work. 

**Related code:**
My application is _very_ small and simple so is basically a reduced test case. 
https://github.com/o-t-w/reonic

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI) : 4.10.2

System:

   NodeJS : v10.15.2
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by jthoms1** [comment]
What is actually happening here is that anytime the value changes for an IonSelect it fires the onIonChange event. This occurs whether it is user based action or a change to the 'selected' value.

I am currently working on updating our docs to denote this.  I would recommend that you compare the changed value to that of the incoming prop params and decide whether to navigate to the new component/page based on those values being different.

```tsx
  handleComponentPick = (event: any) => {
    if (event.detail.value === this.props.match.params.component) {
      return;
    }
...
```
