### ISSUE TITLE
"showBackdrop:false" not work with ModalController

### ISSUE THREAD

**Issue by eddyshn** [ionic-team/ionic#17701]
# Bug Report

**Ionic version:**

[x] 4.0.2

**Current behavior:**

showBackdrop:false not work with Modal Controller

**Expected behavior:**

The modal component should be like a popup window with an overlay layer behind it.

**Steps to reproduce:**

set 'showBackdrop' to false and open the modal component.

**Related code:**

```
 async presentModal() {
    const modal = await this.modalController.create({
      component: ShiftAdminComponent,
      showBackdrop:false,
      mode:'md',
      componentProps: { value: 123 },
      
    });
    modal.onDidDismiss().then((detail: any) => {
      if (detail !== null) {
        console.log('The result:', detail.data);
      }
   });

    await modal.present();
  }
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.17
   @capacitor/core           : 1.0.0-beta.17

System:

   NodeJS : v10.15.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm not able to reproduce this on latest. Could you please provide a repository we can use to reproduce? I tried in both master and the ionic conference app.

With `showbackDrop: false`:

<img width="847" alt="screen shot 2019-03-06 at 2 07 36 pm" src="https://user-images.githubusercontent.com/6577830/53906574-4d7e6580-4019-11e9-8c76-34b1c21149c1.png">

Without it:

<img width="845" alt="screen shot 2019-03-06 at 2 07 55 pm" src="https://user-images.githubusercontent.com/6577830/53906583-5838fa80-4019-11e9-83cc-e17df388e7d3.png">

**Comment by eddyshn** [comment]
Seems it is only displayed as a modal dialog in tablet and in mobile phone it will always display as full screen page.
There is no differences when i set showbackDrop to ture or false.
