### ISSUE TITLE
ion-select z-index conflicts with custom UI element

### ISSUE THREAD

**Issue by Nudelsieb** [ionic-team/ionic#17726]
# Bug Report

**Ionic version:**

[x] **4.1.1**

**Current behavior:**

I have an element with `ion-select` on the page. Also, there is a custom drawer element with a drawer button sitting over the `ion-select` when the drawer is open. Because the is a `z-index: 2` on the `ion-select` it takes precedence (in terms of visibility and event handling) over the button of my drawer, despite the button being higher in the DOM hierarchy. I see no reason why `z-index: 2` would be needed on that element.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! Would you be able to provide a repository with the code required to reproduce this issue?

Thanks!
