### ISSUE TITLE
Menu not working on Android 4.4.4

### ISSUE THREAD

**Issue by SchneMa** [ionic-team/ionic#17729]
# Bug Report

**Ionic version:**
[x] **4.0.2**

**Current behavior:**
Instead if displaying the Menu on Android 4.4.4 only the "gray" overlay is vissible. Menu isn't visible.

**Expected behavior:**
Menu is beeing displayed like expected.

**Steps to reproduce:**

1.  ionic start test sidemenu
2.  ionic cordova run android on an adnroid 4.4.4 device

**Other information:**
Tryed to add Polyfills but it didn't fixed the display bug.
We're in need to Support Android 4.4.4 because we use specific equipments that can't be upgraded above 4.4.4...

**Ionic info:**
```
Ionic:
   ionic (Ionic CLI)             : 4.10.3 (C:\Users\mvs\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.5
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.4.0

Cordova:
   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 4 other plugins)

System:
   NodeJS : v10.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by armanbisembaev** [comment]
I tested on the emulator with Android 4.4.4 and found that when I clicked on the menu button, the `transform` property is not applied to the css class `.menu-inner`.

If manually apply the `transform: translateX(0px)` via remote debug in the chrome, it will report an unknown property.

Then manually apply the `-webkit-transform: translateX(0px)` menu appeared and worked.
I hope this information will be useful for solving the problem.

**Comment by royanon** [comment]
It does not work in iOS 10 too.

**Comment by shomid** [comment]
how to fix the problem ?

**Comment by deniscesar** [comment]
I'am need sidemenu in android 4.4

**Comment by liamdebeasi** [comment]
Hi there,

This issue has been resolved via https://github.com/ionic-team/ionic/pull/18128. I have published a nightly build of Ionic if you would like to test these changes out (`npm i @ionic/angular@dev`).

Thanks!
