### ISSUE TITLE
[Ionic 4.1.1] Scroll state not preserved after back navigation in Firefox

### ISSUE THREAD

**Issue by pwespi** [ionic-team/ionic#17730]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
In Firefox, when navigating back to a previous page, the scroll position is at the top instead of at the position it was before. 

**Expected behavior:**
Scroll position is preserved when navigating back in Firefox (as it is in Chrome).

**Steps to reproduce:**

* git clone https://github.com/pwespi/ion-list-test
* cd ion-list-test
* npm i
* npm run start
* open http://localhost:3333/ in Firefox
* scroll down, click an item, click back button
* scroll position is at top

**Related code:**
A sample application via GitHub
https://github.com/pwespi/ion-list-test

**Other information:**

Tested with Firefox 65.0.2 in Windows 10.

**Ionic info:**

Ionic PWA toolkit project with
```
"dependencies": {
    "@ionic/core": "4.1.1"
  },
  "devDependencies": {
    "@stencil/core": "0.18.0"
  }
```

```
Ionic:

   ionic (Ionic CLI) : 4.10.3

System:

   NodeJS : v10.15.0
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! I am able to reproduce this -- we will look into it. Thanks!
