### ISSUE TITLE
Ionic & Stencil Component Methods error OnInit or AfterViewInit

### ISSUE THREAD

**Issue by Jefftopia** [ionic-team/ionic#17735]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

Calls to methods (`@Method`) from components authored in Stencil _always_ error when called in Angular Component `OnInit` and `AfterViewInit` lifecycle hooks.

Using `async`, `await`, or checking  `componentOnReady()`, make no difference.

Calls to `componentOnReady` throw the following error:

```
TypeError: Cannot read property 'componentOnReady' of undefined
```

Attempting to call the method directly (through an elementRef) also throws an error:

```
open is not a function
```

**Expected behavior:**

Ionic & stencil component methods should invocable with expected behavior within at least one angular lifecycle hook that occurs during a "setup" phase.

Perhaps introduce a new lifecycle hook, or monkey-patch an existing lifecycle hook to wait for ionic rendering. I'm not sure yet, but method calls shouldn't fail in `afterViewInit`.

**Steps to reproduce:**
1. create a new angular app using the angular cli, `ng new my-app`
2. Add deps, `@ionic/core`, `@ionic/angular` 
3. Add an ionic-angular controller injectable to app-component.
4. `npm run start`
5. View above error in console.

**Related code:**

```
import {
  Component,
  HostListener,
  AfterViewInit,
} from '@angular/core';

import { AlertController } from '@ionic/angular';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements AfterViewInit {
  title = 'test';

  constructor(public alertController: AlertController) {}

  async ngAfterViewInit() {
    await this.presentAlert(); // error
  }

  async presentAlert() {
    const alert = await this.alertController.create({
      header: 'Alert',
      subHeader: 'Subtitle',
      message: 'This is an alert message.',
      buttons: ['OK']
    });

    await alert.present();
  }
}
```

*Related Issue*: https://github.com/ionic-team/stencil/issues/1338

**Ionic info**
```
Ionic:

   ionic (Ionic CLI) : 4.5.0

System:

   NodeJS : v9.5.0
   npm    : 6.5.0
   OS     : macOS High Sierra
```

**Comment by adamdbradley** [comment]
What do the imports for the `NgModule` within the `app.module.ts` look like? Is it calling `IonicModule.forRoot()` like this example? https://github.com/ionic-team/ionic-conference-app/blob/9250a0910ba36048c4d3e7f4e3bb74fe44f5ec0d/src/app/app.module.ts#L20

**Comment by Jefftopia** [comment]
@adamdbradley Perfect - thanks! Solves the problem. 

Looks like that module is something needed for _any_ stencil-to-angular app, not just Ionic!

**Comment by adamdbradley** [comment]
Ok great, reminds us to better document this, thanks for opening the issue.
