### ISSUE TITLE
when calling lockSwipeToNext() the slide left animation can be stopped in the middle

### ISSUE THREAD

**Issue by AleCat83** [ionic-team/ionic#17731]
**Ionic version:**

Hello,
I have three ion-slide inside an ion-slides. I want to disable the swipe left when I am in the first slide and the slide right when I am in the second slide. So I'm using this code that get executed on "ionSlideDidChange" callback:

`  onSlideDidChange() {
    switch (this.slides.getActiveIndex()) {
      case 0:
        this.slides.lockSwipeToPrev(true);
        break;
      case 1:
        this.slides.lockSwipes(false);
        break;
      case 2:
        this.slides.lockSwipeToNext(true);
        break;
    }
  }`

The code works fine but when I am in the third slide, the animation during the slide itself is not working properly: user can swipe left  but the slide animation can be stopped in the middle if the user does not swipe completely (normally, when swiping, if the swipe is wider than a threshold it goes in the next/prev slide otherwise it stays in the current but it is not possible to stop the slide in the middle)

**Steps to reproduce:**

Create a view with 3 slides
`<ion-slides
  pager="false"
  initialSlide="1"
  (ionSlideDidChange)="onSlideDidChange()"
>
  <ion-slide>
slide 1
  </ion-slide>
  <ion-slide>
   slide 2
  </ion-slide>
  <ion-slide>
slide 3
  </ion-slide>
</ion-slides>`

 call lockSwipeToNext() on ionSlideDidChange callback when the last slide is open;
`onSlideDidChange() {
    switch (this.slides.getActiveIndex()) {
      case 0:
        this.slides.lockSwipeToPrev(true);
        break;
      case 1:
        this.slides.lockSwipes(false);
        break;
      case 2:
        this.slides.lockSwipeToNext(true);
        break;
    }
  }`

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! Would you be able to provide a repository with the code required to reproduce this issue? Thanks!

**Comment by AleCat83** [comment]
Hello, 
thanks for the reply. I try to put together a repo with the specific problem. You can also reproduce it by adding a slider in a view and the following code in the:
`
 ionViewDidEnter(){
onSlideDidChange() { switch (this.slides.getActiveIndex()) { case 0: this.slides.lockSwipeToPrev(true); break; case 1: this.slides.lockSwipes(false); break; case 2: this.slides.lockSwipeToNext(true); break; } }}`

the problem appear when this.slides.lockSwipeToNext(true); is executed.

**Comment by AleCat83** [comment]
Hello, I created the following repository:

https://github.com/AleCat83/ionic-slide-test

to test it just call "ionic serve" or deploy on IOS. You can see 3 slides (green, yellow, red), the default one will be the one in the middle (yellow) so you can slide left and right. Try to slide to the third one (red) and then slide back, you will notice that the slide animation is not "sticky" so you can stop it in the middle. The same is not happening for the first two slides (you can't stop the slide in the middle, it either slides to the next/prev one or get back).

thanks

**Comment by liamdebeasi** [comment]
Hi there,

Apologies, I did not realize this was an Ionic 3 application. This repo is for Ionic 4 issues, so I am going to transfer this. Additionally, if you would like to disable the rubber-band effect, it's recommended that you set `resistanceRatio: 0` in the slides options instead of disabling swiping: http://idangero.us/swiper/api/ https://ionicframework.com/docs/api/slides
