### ISSUE TITLE
Css not applied to ionic components (through component properties)

### ISSUE THREAD

**Issue by Chimmis** [ionic-team/ionic#17749]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Component properties e.g color="primary" not working. I can see the classes applied using chrome dev-tools. However they are not rendered. 
Able to replicate with a fresh boilerplate project with tabs option.

**Expected behavior:**
Ionic component css styles applied.

**Steps to reproduce:**
1. Create a new ionic project (I replicated this with tabs)
2. In tab1.page.html add an ion button, I used this:

```
<ion-button color="primary" expand="full" type="submit" button-type="block">Test</ion-button>
```

3. Run the project, the primary color is not applied, the button is not expanded to full width.

**Related code:**

package.json dependencies:
"dependencies": { 
  "@angular/common": "^7.2.2", 
  "@angular/core": "^7.2.2", 
  "@angular/forms": "^7.2.2", 
  "@angular/http": "^7.2.2", 
  "@angular/platform-browser": "^7.2.2", 
  "@angular/platform-browser-dynamic": "^7.2.2", 
  "@angular/router": "^7.2.2", 
  "@ionic-native/core": "^5.0.0", 
  "@ionic-native/splash-screen": "^5.0.0", 
  "@ionic-native/status-bar": "^5.0.0", 
  "@ionic/angular": "^4.1.0", 
  "core-js": "^2.5.4", 
  "rxjs": "~6.3.3", 
  "zone.js": "~0.8.29"
 }

**Other information:**
I've tested this with different browser, devapp, compiling using ionic android, issue stays the same

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (C:\Users\Paulius\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.5
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.4.0

System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! I am seeing these styles applied and rendered appropriately in a the tabs starter app: 
![image](https://user-images.githubusercontent.com/2721089/54125315-0d353380-43db-11e9-8908-52b91f4d9bf5.png)


I am using the following code:

```
<ion-button color="secondary" expand="full">my button</ion-button>
```

Would you be able to provide a repository with the code required to reproduce this issue? Thanks!

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! When trying to set the type of a button, please use the `type` property instead of `button-type`. Additionally `block` is not a valid value for both `button-type` and `type`. (Perhaps you are thinking of `expand`?)

`button-type` is an internal prop and should not have been in the documentation. I will make sure that it gets marked as internal before I close this issue.

Thanks for using Ionic!

**Comment by Chimmis** [comment]
Hello,
Thanks for the speedy reply! Indeed, the button-type was the issue here. I thought either this was a bug, or I'm missing something very obvious. Thank you!
