### ISSUE TITLE
ionic4 popover position 

### ISSUE THREAD

**Issue by zhiwo** [ionic-team/ionic#17755]
popover How to customize the location，The popup position is always in the middle of the screen how do you popup where you click

```
import { Component } from '@angular/core';
import { PopoverController } from '@ionic/angular';
import { PopoverComponent } from '../../component/popover/popover.component';

@Component({
  selector: 'popover-example',
  templateUrl: 'popover-example.html',
  styleUrls: ['./popover-example.css']
})
export class PopoverExample {
  constructor(public popoverController: PopoverController) {}

  async presentPopover(ev: any) {
    const popover = await this.popoverController.create({
      component: PopoverComponent,
      event: ev,
      translucent: true
    });
    return await popover.present();
  }
}

 this.mapView.on("click", event => {
 presentPopover(event);
});
```

**Comment by Langstra** [comment]
In the presentPopover function you have this `ev: any`. This must be the click event.

So in your popover-example.html you have some element where you have the click event listener. Add something like this:
```
<ion-button (click)="presentPopover($event)">Click me!</ion-button>
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! I am going to close this as it is more of a support question. For help setting the position of the popover, please refer to the [Popover Documentation](https://ionicframework.com/docs/api/popover). For further help implementing this, feel free to post on our [forums](http://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com).

Thanks for using Ionic!
