### ISSUE TITLE
Sub tab navigation not working

### ISSUE THREAD

**Issue by WisePlatypus** [ionic-team/ionic#17765]
# Bug Report

**Ionic version:**

[x] **4.10.3**

**Current behavior:**
Sub tab (tab in a tab) router get a navigation cancel and then try to route to another url level.

**Expected behavior:**
On clicking on a sub tab route to the right page and component

**Steps to reproduce:**
create a parent tabs "tabs"

create a subTabs page "subTabs"

create a subTab1 page

define in tabs module the subTabs tab children route and subTab1 children route for subTabs

in the html follow the tab doc it should look like this

```
<ion-tabs>
  <ion-tab-bar slot="bottom">

    <ion-tab-button tab="tab1">
      <ion-label>tab1</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="subTabs">
      <ion-label>subTabs</ion-label>
    </ion-tab-button>

  </ion-tab-bar>
</ion-tabs>
```
apply same principle for sub tab.

then run the application navigate to subtab then to the first tab (that is also not selected by default) and nothing happens. The console shows errors.

I worked around by mannually setting a click event to the tab button and navigating using angular router. And selecting manually the buttons

**Other information:**

angular router debug log
```
Router Event: NavigationStart platform-browser.js:216
NavigationStart(id: 7, url: '/tabs/subTabs/subtab1') platform-browser.js:211
Object { id: 7, url: "/tabs/subTabs/subtab1", navigationTrigger: "imperative", restoredState: null }
platform-browser.js:211
Router Event: NavigationCancel platform-browser.js:216
NavigationCancel(id: 7, url: '/tabs/subTabs/subtab1') platform-browser.js:211
Object { id: 7, url: "/tabs/subTabs/subtab1", reason: "Navigation ID 7 is not equal to the current navigation id 8" }
platform-browser.js:211
Router Event: NavigationStart platform-browser.js:216
NavigationStart(id: 8, url: '/tabs/subtab1') platform-browser.js:211
Object { id: 8, url: "/tabs/subtab1", navigationTrigger: "imperative", restoredState: null }
platform-browser.js:211
Router Event: NavigationError platform-browser.js:216
NavigationError(id: 8, url: '/tabs/subtab1', error: Error: Cannot match any routes. URL Segment: '/tabs/subtab1') platform-browser.js:211
Object { id: 8, url: "/tabs/subtab1", error: Error }
```

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (C:\Users\Félix Cortès\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (5 plugins total)

System:

   Android SDK Tools : 26.1.1 (C:\sdk-tools)
   NodeJS            : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! Would you be able to provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by WisePlatypus** [comment]
here you go

https://github.com/WisePlatypus/IonicSubTab

I also implemented my work around in it dunno if it might help

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the follow up!

I am going to close this as sub tab navigation is not something we currently support. Having nested tabs in a mobile app is generally considered a bad user experience practice. You might want to consider presenting your second set of tabs in an alternative way to make it easier/less confusing for your users to navigate you app.

Thanks!

**Comment by WisePlatypus** [comment]
yeah I deffinitly won't let it as the exemple provided I'm just migrating from v3 now and try to leave the things as they were. Thanks for the reply anyway
