### ISSUE TITLE
Feature Request: Trusted Web Activities instead of webview wherever possible

### ISSUE THREAD

**Issue by IamManchanda** [ionic-team/ionic#17766]
# Feature Request 

## #PWA + #TWA === ❤️ 

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Trusted Web Activities instead of webview wherever possible

**Describe Preferred Solution**

https://developers.google.com/web/updates/2019/02/using-twa

**Comment by IamManchanda** [comment]
Mainly Latest Android (Chrome) as of now!

**Comment by mhartington** [comment]
Hi there! Thanks for the issue. Though as this the repo for the UI portion of the framework. Any issue/feature request/question regarding the native layer should be opened on the cordova repo or capacitor repo.


A small note here, TWA are not a perfect solution for everything. While they are a nice feature, there are some limitations. Not being able to extend a web apps capabilities with native plugins being one of them. So while they may work for some people, they're not a drop in replacement for everyone. 

Closing this for now, as again, this is not an issue for the UI portion of the framework.
