### ISSUE TITLE
Popover is always in the middel of the page and can't be moved

### ISSUE THREAD

**Issue by reyno-strategix** [ionic-team/ionic#17768]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
if you try to parse a 3rd argument in the create method.

**Expected behavior:**
The popover would be able to be moved around in the code or as a argument throught the create method.

**Steps to reproduce:**
Just add a page with a popover component.  Then try to parse a css class in the function.

```
async openPopover(ev:Event) {
    const popover =  await this.popoverController.create({
      component: ChatChannelOptionsPage,  
    });
    popover.present();
  }
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! You can override the popover in two ways:

1. Provide an `event` property in the picker options:
```
async openPopover(ev:Event) {
    const popover =  await this.popoverController.create({
      component: ChatChannelOptionsPage,  
      event: ev
    });
    popover.present();
}
```

2. Provide a 'cssClass' property in the picker options, and set the `left` and `top` of the `.popover-content` class:

```
async openPopover(ev:Event) {
    const popover =  await this.popoverController.create({
      component: ChatChannelOptionsPage,  
      cssClass: "my-fun-popover"
    });
    popover.present();
}
```

```
.my-fun-popover .popover-content {
  top: 0 !important;
  left: 0 !important;
}
```

Can you clarify the issue you are having? Are you unable to do either of these methods?

Thanks!

**Comment by zhiwo** [comment]
> Hi there,
> 
> Thanks for opening an issue with us! You can override the popover in two ways:
> 
> 1. Provide an `event` property in the picker options:
> 
> ```
> async openPopover(ev:Event) {
>     const popover =  await this.popoverController.create({
>       component: ChatChannelOptionsPage,  
>       event: ev
>     });
>     await popover.present();
> }
> ```
> 1. Provide a 'cssClass' property in the picker options, and set the `left` and `top` of the `.popover-content` class:
> 
> ```
> async openPopover(ev:Event) {
>     const popover =  await this.popoverController.create({
>       component: ChatChannelOptionsPage,  
>       cssClass: "my-fun-popover"
>     });
>     await popover.present();
> }
> ```
> ```
> .my-fun-popover .popover-content {
>   top: 0 !important;
>   left: 0 !important;
> }
> ```
> Can you clarify the issue you are having? Are you unable to do either of these methods?
> 
> Thanks!

Passing an event still won't do

**Comment by liamdebeasi** [comment]
Thanks for the follow up! Would you be able to provide a repository with the code required to reproduce this issue?

Thanks!
