### ISSUE TITLE
Add button attribute to ion-card

### ISSUE THREAD

**Issue by Spinnenzunge** [ionic-team/ionic#17773]
# Feature Request
Add button attribute to ion-card like ion-item so it adds activated styles and ripple-effects on android without custom css.

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
ion-card should have the opportunity to be used as "button" and be activatable like it used to be in Ionic 3 with ripple effect on android and tab effect on ios.

**Describe Preferred Solution**
Same attributes as on ion-item (button, routerOutlet, etc.)

**Comment by jlbeard84** [comment]
I'd be happy to take a look at this one if nobody else has picked it up.
