### ISSUE TITLE
Mixins are no longer globally available?

### ISSUE THREAD

**Issue by Bengejd** [ionic-team/ionic#17779]
# Bug Report

**Ionic version:** -->
[x] **4.x**

**Current behavior:**
You cannot access global mixins imported into the `global.scss` file, without having to manually import their relative path into the component you want to use them in.

**Expected behavior:**
When you go to import a mixin that is imported into the `global.scss` file, you would expect it to be used globally without having to manually import the mixin file into the component that you want to use it in. This was how it worked in Ionic V2, V3 but for whatever reason, it is not accessable in V4 without having to manually import them everytime...

**Steps to reproduce:**
Create a mixin.scss file, import it into `globabl.scss`, and attempt to use it in a component/page. Then you'll be met with an error.

**Comment by brandyscarney** [comment]
Thanks for the issue! As of Ionic 4, Ionic no longer ships with custom Angular build tools. We let Angular (or the framework of your choice) handle compiling the Sass. Here's an issue for the Angular CLI that may help explain it: https://github.com/angular/angular-cli/issues/3700

Here is a comment on a different issue that explains how to make it easier to reference the file without writing out a relative path: https://github.com/angular/angular-cli/issues/1253#issuecomment-352481681

Please create an issue on one of the Angular repositories for any build issues you experience.

- [Angular Issues](https://github.com/angular/angular/issues)
- [Angular CLI Issues](https://github.com/angular/angular-cli/issues)

Thanks!
