### ISSUE TITLE
class attribute on ion-content prevents hydrated class to be set

### ISSUE THREAD

**Issue by 7freaks-otte** [ionic-team/ionic#17789]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Having a class attribute on `ion-content` of the initial loaded page prevents it from getting the "hydrated" class. Means that the content inherits `visibility: hidden` and stays invisible.

```
<ion-content class="tpl-search {{uiClass}}">
```

Changing `class` to `[ngClass]` seems to help:

```
<ion-content [ngClass]="['tpl-search', uiClass]">
```

**Expected behavior:**

Should work reliable. Sometimes it works and the "hydrated" class is added, sometimes not. Seems to be a timing issue when rendering the first page.

**Other information:**

Maybe it's just my fault and I was lucky when using `class` in the last years. Easily fixed by using `ngClass`, but then I thought it should be noted somewhere, just in case someone else stumbles on this issue.

**Ionic info:**

```
   ionic (Ionic CLI)             : 4.11.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.5
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.4.0
```

**Comment by 16am** [comment]
Also
`[class]="condition ? 'class-a' : 'class-b'"`
is not working

**Comment by adamtester** [comment]
I have a similar issue, but no class is set on `ion-content`

On iOS hydrated class is not added, but the content is there in the inspector. When I open the side menu or PTR it shows it properly.

I'll update if I find the cause, might be something completely different!

**Comment by brandyscarney** [comment]
Is this still an issue in latest? I'm not able to reproduce it in an Angular application.

**Comment by 7freaks-otte** [comment]
Seems to be resolved in the meantime
