### ISSUE TITLE
Multiple value ion-select initialized with list of values not being selected

### ISSUE THREAD

**Issue by jofravelo** [ionic-team/ionic#17785]
# Bug Report

**Ionic version:**
**4.1.1**

**Current behavior:**
An `ion-select` with multiple values (attribute `multiple` set to `true`) is initialized with a list of values (comma-separated) to select by default. No value is selected at all.

**Expected behavior:**
If a multiple-value `ion-select` is initialized with a list of values, the specified values are selected and shown.

**Steps to reproduce:**
- Use the component `ion-select` with `multiple=true` and `value` initialized with a list of comma-separated values. The values are valid values in the children `ion-select-option`.
- With only one value in the `value` property, the component works as expected.

**Related code:**
https://plnkr.co/edit/jM9n133SomSdpRhrQH47?p=preview

```
  <ion-select multiple="true" value="1000,1001">
    <ion-select-option value="1000">
      Geralt of Rivia
    </ion-select-option>
    <ion-select-option value="1001">
      Yennefer of Vengerberg
    </ion-select-option>
    <ion-select-option value="1002">
      Triss Merigold
    </ion-select-option>
    <ion-select-option value="1003">
      Emiel Regis Rohellec Terzieff-Godefroy
    </ion-select-option>
  </ion-select>
```

**Other information:**
Only `@ionic/core` is being used. Vanilla Javascript, no Angular.

**Ionic info:**
No logic is needed. Only CDN link to `@ionic/core` dependency and HTML component initialization.

**Comment by brandyscarney** [comment]
Thanks for the issue! The `value` property accepts an array when `multiple` is `true`. Here's your plunker example updated to use an array: https://plnkr.co/edit/K9l3rrZEroXkxg8uiV7N?p=preview

Here is the documentation on the multiple value select: https://ionicframework.com/docs/api/select#multiple-selection. This may be a documentation issue, however, I am not able to find any documentation or usage examples showing it as accepting a comma separated string. Could you please let me know if you found it written this way somewhere? Thanks!

**Comment by jofravelo** [comment]
Thanks a lot for the quick reply!

Indeed I didn't find it in the documentation but rather observing how the values were being handled in the HTML element, using the developer console in the browser.

I tried assigning the value to the input inside the component and it didn't work. I guess I missed trying to assign the value to the value field in the component itself.

Works like a charm. Sorry for reporting it as a bug, but it wasn't really clear to me in the documentation how to do it so I thought it was a wrong behavior.

Thanks again!

**Comment by brandyscarney** [comment]
That's okay! We want to fix the documentation when it is missing or inaccurate. I went ahead and created a docs issue for this: https://github.com/ionic-team/ionic-docs/issues/564

Thanks for bringing this to our attention. 🙂
