### ISSUE TITLE
routerDirection not working like push or pop

### ISSUE THREAD

**Issue by RezaT1994** [ionic-team/ionic#17806]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
I think **routerDirection** does not have the same behavior as the **push** or **pop** that exists in ionic 3.
It's not working well with the browser history when using **back** or **forward** as the property value.

**Expected behavior:**
When I use **forward**, It's working fine, but when using **back**, It should simulate the back button of the browser.

**Related code:**
```html
<ion-button routerLink="/support" routerDirection="back">
	<ion-icon slot="icon-only" name="arrow-forward"></ion-icon>
</ion-button>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue using the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue. Thanks!
