### ISSUE TITLE
ion-spinner DO NOT rotate around it's centre

### ISSUE THREAD

**Issue by Desever** [ionic-team/ionic#17811]
![52957598-51ac5100-3392-11e9-805d-1390d9a9afab](https://user-images.githubusercontent.com/16665064/54521611-3a1eb300-49a6-11e9-8d5a-3384e037d345.gif)

**Comment by liamdebeasi** [comment]
Continuing discussion here: #17524

**Comment by Desever** [comment]
i do not know add to where  

> svg:not(:root) {
  transform-origin: 0px 0px 0px;
}

**Comment by Desever** [comment]
global.scss or variables.scss? please help me,online
