### ISSUE TITLE
Firebase is added to Android project, even when the plugin is not added

### ISSUE THREAD

**Issue by vance** [ionic-team/ionic#17816]
# Bug Report

**Ionic version:**
[x] CLI 4.10.2

**Current behavior:**
Building and running iOS works fine (dev and release). However, my Android project always gets created with Firebase, and the repositories for that do not resolve.  
```
Could not resolve com.google.firebase:firebase-iid:[17.0.4] 
```
doing ionic cordova plugin remove doesn't work `Plugin "firebase-messaging" is not present in the project. See 'cordova plugin list'.` I also nuked the android folder altogether. I upgraded android studio. I tried switching repo urls manually to see if the dep would download.

**Expected behavior:**
This library should not be present, or at the very least, be compilable and runnable with the standard maven/android code repositories. 

**Steps to reproduce:**

```
npx cap add android
ng build --project foo --configuration=myenv 
cap.copy
```

It generates a gradle project with firebase, gradle fails on this dependency.

**Related code:**

The generated code. I also notice the versions don't match up (17.3.4) in the iml, but 17.1.0 in gradle. Nowhere in my project is a reference to Firebase. Global search turns up nothing. It only appears in generated code.  

app.iml
```
<orderEntry type="library" name="Gradle: com.google.firebase:firebase-messaging:17.3.4@aar" level="project" />
```

gradle dependencies:
```
    implementation 'com.google.firebase:firebase-messaging:17.1.0'
```

**Other information:**
This is an angular 7 app.

**Ionic info:**

```
ionic (Ionic CLI)             : 4.10.2
   Ionic Framework               : @ionic/angular 4.0.1 (/Users/f-user/code/fooapp/packages/fooapp/node_modules/@ionic/angular)
   @angular-devkit/build-angular : 0.12.4 (/Users/f-user/code/fooapp/packages/fooapp/node_modules/@angular-devkit/build-angular)
   @angular-devkit/schematics    : 7.2.4 (/Users/f-user/code/fooapp/packages/fooapp/node_modules/@angular-devkit/schematics)
   @angular/cli                  : 7.3.0 (/Users/f-user/code/fooapp/packages/fooapp/node_modules/@angular/cli)
   @ionic/angular-toolkit        : 1.3.0 (/Users/f-user/code/fooapp/packages/fooapp/node_modules/@ionic/angular-toolkit)

Capacitor:

   capacitor (Capacitor CLI) : not installed
   @capacitor/core           : 1.0.0-beta.17 (/Users/f-user/code/aa-xplat/packages/aa-xplat/node_modules/@capacitor/core)

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/f-user/Library/Android/sdk)
   ios-sim           : 6.1.3
   NodeJS            : v10.12.0 (/Users/f-user/.nvm/versions/node/v10.12.0/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61

✨  Done in 2.23s.
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. We do not bundle anything Firebase-related into the framework. I would suggest looking at your `package.json` and `config.xml` to ensure that the Firebase plugin is not referenced there. I am going to close this as it is more of a support issue. For further questions, feel free to ask on our [forums](http://forum.ionicframework.com) or on our [slack](https://ionicworldwide.herokuapp.com).

Thanks for using Ionic!

**Comment by vance** [comment]
Absolutely, 100% no firebase in our src config.xml, plugins.xml, or any of our package.json or dependencies. I do find a reference in the AndroidManifest in `@capacitor/android/capacitor/src/main/AndroidManifest` Isn't Capacitor part of the Ionic tooling? 

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.getcapacitor.android">
    <uses-feature android:name="android.hardware.camera"
        android:required="false" />

    <application>
        <service android:name="com.getcapacitor.plugin.background.BackgroundTaskService" android:exported="false" />
        <receiver android:name="com.getcapacitor.plugin.notification.TimedNotificationPublisher" />
        <receiver android:name="com.getcapacitor.plugin.notification.NotificationDismissReceiver" />
        <meta-data android:name="firebase_messaging_auto_init_enabled" android:value="false" />
        <service android:name="com.getcapacitor.CapacitorFirebaseMessagingService" android:stopWithTask="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
    </application>
</manifest>
```

**Comment by liamdebeasi** [comment]
Hi there,

Capacitor is a different project than the framework. If you think you've found a bug with Capacitor, feel free to open an issue on the Capacitor repo: https://github.com/ionic-team/capacitor

Thanks!
