### ISSUE TITLE
Ion-menu isn't working as intended

### ISSUE THREAD

**Issue by jakub-cywka** [ionic-team/ionic#17810]
# Bug Report

**Ionic version:**

[x] **4.12.0**

**Current behavior:**
The ion-menu should be visible and working, but it doesn't.

**Expected behavior:**
Ion-menu should be working

**Steps to reproduce:**
Simply try this code:

**Related code:**

```
<ion-content class='ion-no-padding' fullscreen='true'>
  <ion-grid class='ion-no-padding is-fullheight'>
    <ion-row class='is-fullheight'>
      <ion-col style='background-color: #f8f8f8' size-sm='12' size-xs='12' size-md='12' size-lg='3' size-xl='3' class='ion-float-left ion-no-padding ion-no-margin'>
          <ion-menu side="start" menuId="first">
              <ion-header>
                <ion-toolbar color="primary">
                  <ion-title>Start Menu</ion-title>
                </ion-toolbar>
              </ion-header>
              <ion-content>
                <ion-list>
                  <ion-item>Menu Item</ion-item>
                  <ion-item>Menu Item</ion-item>
                  <ion-item>Menu Item</ion-item>
                  <ion-item>Menu Item</ion-item>
                  <ion-item>Menu Item</ion-item>
                </ion-list>
              </ion-content>
            </ion-menu>
      </ion-col>   
      <ion-col size-sm='12' size-xs='12' size-md='12' size-lg='9' size-xl='9' class='ion-float-right ion-no-padding ion-no-margin'>
        test
      </ion-col>
    </ion-row>
  </ion-grid>
</ion-content>
```

**Other information:**

**Ionic info:**

```
`Menu: must have a "content" element to listen for drag events on.`
```
![image](https://user-images.githubusercontent.com/39415217/54495602-4bec5180-48e5-11e9-9b49-684ebe1e3f0d.png)
![image](https://user-images.githubusercontent.com/39415217/54495610-5dcdf480-48e5-11e9-9e7e-2a89f5864ed4.png)

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. This is not the intended usage of `ion-menu`. The component should not exist within an `ion-content` component.

For further examples on how to use `ion-menu` please see the [Menu Component Documentation](https://ionicframework.com/docs/api/menu). Additionally, see the [Ionic Conference App example](https://github.com/ionic-team/ionic-conference-app/blob/master/src/app/app.component.html) for how `ion-menu` should be implemented. If you have any questions on how to implement this, feel free to ask on our [forums](http://forum.ionicframework.com) or on our [slack](https://ionicworldwide.herokuapp.com).

Thanks for using Ionic!

**Comment by jakub-cywka** [comment]
It helped :) This was just my issue of using **_ion-menu_** without **_ion-split-pane_** component. However, i found that on _Ionic_ docs website in **_ion-menu_** documentation, there is no example with Ion-split-pane, so i think this could be an issue (the code snippet is wrong and this could be misleading) but i'm not sure about it.
![image](https://user-images.githubusercontent.com/39415217/55273280-5cc79a80-52c9-11e9-94fd-743e28c52103.png)

By the way, thanks for your support! It was very helpful :)
