### ISSUE TITLE
 An error occurred while running git rev-parse HEAD (exit code 128)

### ISSUE THREAD

**Issue by amrendraPandey** [ionic-team/ionic#17828]
[myApp.zip](https://github.com/ionic-team/ionic/files/2986759/myApp.zip)

Please find file and try to build apk using vs code in windos 8 environment.
then i got error of An error occurred while running git rev-parse HEAD (exit code 128) for release mode option .
for build apk follow below link:
 https://medium.com/@dineshuthakota/how-to-generate-android-apk-without-android-studio-using-ionic-b3a2ae0edc86.
Hope reply soon.

**Comment by liamdebeasi** [comment]
Hi there,

Please fill out the [bug report template](https://github.com/ionic-team/ionic/issues/new?assignees=&labels=&template=bug_report.md&title=) completely. We use this to gather more information and to better assist you.

Thanks!
