### ISSUE TITLE
Platform.isMobile check

### ISSUE THREAD

**Issue by karaggeorge** [ionic-team/ionic#17833]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

- Visit an ionic site on a Microsoft laptop that supports touch (not a 2-in-1, just a regular laptop with touch screen)
- Log platform.is('mobile')
- Returns `true`
- Log platform.is('desktop')
- return `false`

**Expected behavior:**

- platform.is('desktop') should be `true`, since this is a laptop

**Related code:**

The error is here: https://github.com/ionic-team/ionic/blob/master/core/src/utils/platform.ts#L69

The check says that a device is mobile if it has *any* coarse input methods. If you have a mouse/trackpad (which is a fine input method) and also have a coarse input (like touch), it should return false.

I think that check should be `!matchMedia(win, '(any-pointer:fine)');`

Happy to open a PR if you agree with the above logic.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us. This is a known issue, and will potentially require breaking changes. As a result, a feature request has been created here: https://github.com/ionic-team/ionic/issues/17631.

I will make note of your issue in the thread.

Thanks for using Ionic!

**Comment by karaggeorge** [comment]
Ah, I searched with keywords mobile and didn't get that issue. It was too generic. Everything seems to be well summed up there. Thanks for the quick response!

Still willing to contribute if needed once there's a decision made
