### ISSUE TITLE
ion-range tapping on android does not trigger ionChange

### ISSUE THREAD

**Issue by jhoogeboom** [ionic-team/ionic#17831]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

On android, when tapping instead of clicking or dragging, an ionFocus and ionBlur event is emitted, but not an ionChange. Longer drags do emit this event. 

**Expected behavior:**

An ionChange should occur even with a tap.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

current workaround, access the html element value directly

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Hi there,

The `ionChange` event is emitted when the `value` property has changed. When you tap the `ion-range`, does the value of it change? 

Thanks!

**Comment by jhoogeboom** [comment]
Hi!

So the value changes, only the event is not emitted. I edited my ticket and added my current workaround which is accessing the `value` property from `ion-range` directly.

**Comment by liamdebeasi** [comment]
Thanks for the follow up! That's very interesting. Do you have a repository/code snippet that I could use to try and reproduce this?

Thanks!

**Comment by jhoogeboom** [comment]
nothing publicly, but I'll see if I can make a codepen for this.
