### ISSUE TITLE
ion-textarea doesn't reposition itself when keyboard appears on iOS

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/ionic#17847]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When you tap an `ion-textarea` and the keyboard appears it remains behind the keyboard.
Happens on both Capacitor and Cordova when running on iOS.

**Expected behavior:**

When using `ion-input` the view is scrolled to show the field. I think`ion-textarea` should behave the same way.

**Steps to reproduce:**

See sample app
https://github.com/jcesarmobile/focus-input-control-opens-keyboard-which-covers-it

1. Click TEST
2. Scroll down to Note `ion-textarea` and focus it. The keyboard appears and the field is not vissible
3. Now focus Default Label. The keyboard appears but the field is still visible.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by Nazirovich** [comment]
I'm facing the same issue on iOS while using tabs
