### ISSUE TITLE
clicking on a menu item causes flicker

### ISSUE THREAD

**Issue by alainbelez** [ionic-team/ionic#17849]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Clicking a menu item causes flickering

**Expected behavior:**
it should not cause flickering

**Steps to reproduce:**
run `ionic serve`
When the page is loaded, selecting other menu item cause flicker, it only happens once on freshly loaded page. a refresh triggers it again

**Related code:**
https://github.com/alainbelez/ionic-starter

**Other information:**
this is not happening to me on Angular, and i tested removing this `{ provide: RouteReuseStrategy, useClass: IonicRouteStrategy },` and it fixed the problem, i just don't know the side effects.

**Ionic info:**
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.3.6
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.0, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/alain/Android/Sdk)
   NodeJS            : v10.15.3 (/usr/bin/node)
   npm               : 6.9.0
   OS                : Linux 4.18

**Comment by alainbelez** [comment]
upon checking the file `ionic-router-reuse-strategy.ts` on first load, curr.component is `null`, and clicking a link on the menu bar will return `true` to this expression thus `shouldReuseRoute` will return `false`: 
```
    if (future.component !== curr.component) {
      return false;
    }
```
suceeding clicks will cause `false`, thus skipping.

**Comment by mburger81** [comment]
Hello, I thin this is the same issue as mine #17732

**Comment by alainbelez** [comment]
@mburger81 checked the repo and adding a trackBy in ngFor seems to fix your problem, i think it happens because angular is recreating the ion-item every time.

```
//view
    <ion-item *ngFor="let gw of gws; trackBy: trackByFn" button>
        <ion-avatar slot="start">
            <img src="assets/img/lanthings-hdpi-icon.png">
        </ion-avatar>
        <ion-label>
            <h2>{{ gw.description }}</h2>
            <p>{{ gw.serialNumber }}</p>
        </ion-label>
    </ion-item>

//controller
  trackByFn(index: number, item: any): number {
    return item.serialNumber;
  }
```
