### ISSUE TITLE
ion-img set the height of the img

### ISSUE THREAD

**Issue by Cifyger** [ionic-team/ionic#17843]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

I have images, which are to big for the viewport and I like to set the height of a img inside the ion-img tag. Right now the image get cut off.

**Describe Preferred Solution**

Add css variable for the inner image

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the feature request. Can you provide an example of what you're trying to do? Additionally, are you able to just set the `height` on the main `img` via CSS?

Thanks!
