### ISSUE TITLE
@ionic/react Missing ionEvent listener

### ISSUE THREAD

**Issue by guertz** [ionic-team/ionic#17855]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
ionChange does not trigger

**Expected behavior:**
It should trigger handler for ionChange event

**Steps to reproduce:**
- Open a React project
- Add @ionic/react dependency
- Create a plain React component
- Register method to handle ionChange event

**Related code:**
```
<IonSelect placeholder="Select One" ionChange={this.handleChange}>
      <IonSelectOption value="f">Female</IonSelectOption>
      <IonSelectOption value="m">Male</IonSelectOption>
</IonSelect>
```

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI) : 4.12.0

System:

   NodeJS : v10.15.0
   npm    : 6.4.1
   OS     : Linux 4.9
```

**Comment by jthoms1** [comment]
The event name is actually 'onIonChange'. https://github.com/ionic-team/ionic/blob/master/core/src/components.d.ts#L4103

I would expect you to have received a TS error.
