### ISSUE TITLE
Datetime should be refreshed based on changes and max/min

### ISSUE THREAD

**Issue by rafalschmidt97** [ionic-team/ionic#17858]
Hi! 🙆‍♂️

# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Would be cool if datetime will be updated when I change a year - the component should show then show all months. Today is 22 march so it means that if the user changes year to 2000 then he can use to use all months (in my case for maxdate = adult date [now - 18 years]).

![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/14861637/54821976-04c6dd80-4ca4-11e9-8c7e-32ec7eb9d9d1.gif)

**Steps to reproduce:**

- Datetime with maxdate to date - 18 years. I use moment for this

```js
adultDate = moment().add(-18, 'years'); // use .toDate() or .format() depending of your needs
```

**Related code:**

```
btw: please prepare StackBlitz template
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.0, (and 12 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/rafalschmidt/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 7.0.0
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. We have merged in some datetime fixes into a nightly build. Would you be able to install the nightly and see if you are still running into these issues (`npm i @ionic/core@dev @ionic/angular@dev`)? Thanks!

**Comment by rafalschmidt97** [comment]
Great! Thanks for super quick response 🚀 So I'll just wait for next release.

I've updated them as you said. Here's what I got:

```json
"@ionic/angular": "^4.1.3-dev.201903211309.b656925",
"@ionic/core": "^4.1.3-dev.201903211309.b656925",
```

**Comment by jayordway** [comment]
@liamdebeasi I tested the new dev branch and this appears to be working well.

**Comment by liamdebeasi** [comment]
Thanks for checking everyone! I am going to close this issue since we have a fix that's been merged in. Feel free to open any new issues with bugs you find.

Thanks!
