### ISSUE TITLE
platform.ready() in APP_INITIALIZER never triggered

### ISSUE THREAD

**Issue by digaus** [ionic-team/ionic#17856]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Useing platform.ready() in APP_INITIALIZER does not work. It never resolves.

**Expected behavior:**

platform.ready() should resolve in the APP_INITIALIZER aswell

**Steps to reproduce:**

Create an APP_INITIALIZER and wait for platform.ready()

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you provide a repository with the code required to reproduce this issue? Additionally, can you provide the output of running `ionic info`? Thanks!
