### ISSUE TITLE
ionic login won't respond..when i want to login into my ionic account in order to use ionic cordova resources

### ISSUE THREAD

**Issue by tcha-the-great** [ionic-team/ionic#17866]
**Ionic version:**

[x] **4.x**

**I'm submitting a ...** 

[ ] bug report
[ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Hi there,

Just wanted to follow up and let you know that any bugs with the Ionic CLI (running things such as `ionic login`) should be reported here: https://github.com/ionic-team/ionic-cli.

Thanks!
