### ISSUE TITLE
[Ionic 4.1.2] Datetime picker is set to current time instead of 0 when value is 0

### ISSUE THREAD

**Issue by pwespi** [ionic-team/ionic#17868]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Datetime picker is set to current time instead of 0 when value is 0.

**Expected behavior:**

Datetime picker should be set to 0 instead of current time when value is 0.

**Steps to reproduce:**

* open stackblitz below
* click datetime to open picker

**Related code:**
https://stackblitz.com/edit/typescript-op5vnq?file=index.html

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by pwespi** [comment]
PR submitted here https://github.com/ionic-team/ionic/pull/17869

**Comment by liamdebeasi** [comment]
Merged! Thanks for submitting this PR! 🚀
