### ISSUE TITLE
Dual knob IonRange default values in Vue and React

### ISSUE THREAD

**Issue by michaeltintiuc** [ionic-team/ionic#17878]
When following the usage examples for IonRange and trying to set default values to an object both knobs remain at 0.

I've tested this with the latest versions of ionic/vue and ionic/react.
It seems  that the element's value attribute is being set to `NaN` when an object is passed it.

Interestingly enough I was able to find a temporary solution for Vue:

```vue
<template>
  <ion-range ref="range" dual-knobs min="1" max="100" step="1" snaps="true"></ion-range>
</template>

<script>
export default {
  mounted() {
    this.$refs.range.value = { lower: 20, upper: 60 };
  },
}
</script>
```

Initially reported here: https://github.com/ModusCreateOrg/ionic-vue/issues/83

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! Can you provide the output of running `ionic info`? Additionally, can you provide a code sample or a repo that shows this issue?

Thanks!

**Comment by michaeltintiuc** [comment]
Hey @liamdebeasi after talking to @brandyscarney this is not an issue. There is no other way of setting the default values. I've updated the usage docs
