### ISSUE TITLE
tab-bar app freezes after scrolling from bottom (on tab-bar)

### ISSUE THREAD

**Issue by olivero86** [ionic-team/ionic#17872]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

when trying to scroll (and start on the bottom of the page, where the tab-bar is, instead of the content area) the app freezes (not being able to scroll or navigate) until you let it rest for 1 or 2 seconds.

**Expected behavior:**

app scrolls content and/or doesn't freeze 

**Steps to reproduce:**

1. use the sample app: `ionic start myApp tabs`
2. to make it more obvious I cloned the existing ion-items in the list to have more content (area to scroll).
3. then run `ionic serve` and start ios simulator
4. start safari in the ios simulator and visit the localhost url provided in the console when running ionic serve

**Other information:**

here is a video of the problem in the ios simulator:
[https://s3.eu-west-2.amazonaws.com/ionic-tab-problem/tabs-swipe-freeze.mp4]

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.4.1

System:

   NodeJS : v10.13.0 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! So the issue you are describing is a longstanding bug with Safari. What seems to be happening is the scroll focus switches from `ion-content` to `body` (even though `body` can't scroll). As of now we haven't found any reliable work arounds.

If you were to run this app on a device (via Cordova or Capacitor), the issue should not appear (I don't think WKWebView is affected by this issue).

I am going to close this issue, but I will talk with the team about revisiting this issue to see if we can find another work around.

Thanks for using Ionic!
