### ISSUE TITLE
React is not defined error in @ionic/react 

### ISSUE THREAD

**Issue by o-t-w** [ionic-team/ionic#17874]
# Bug Report

**Ionic version:**
"@ionic/react": "0.0.5",

**Current behavior:**
I get the error React is not defined. Removing  `<IonApp>` and `<IonContent>` resolves the issue (but obviously I need to be able to use these components).

**Steps to reproduce:**
A very small 'app' is here (its just some cards in a grid): https://github.com/o-t-w/lrs-react-newsfeed

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI) : 4.12.0

System:

   NodeJS : v10.15.2
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by jthoms1** [comment]
I cloned your repo and built and had no issues.  Everything looked fine to me.  Can you try cleaning your node_modules directory and running `npm install`.

**Comment by o-t-w** [comment]
Deleting and reinstalling my node_modules directory was the first thing I tried. It usually fixes things _temporarily_ and then the error occurs again.

**Comment by elylucas** [comment]
Hi @o-t-w, can you report if you are still seeing this issue? I tried the repo out as well and didn't run into any issues. If you do, any more details on how the error might be coming up would be helpful.

Thanks

**Comment by elylucas** [comment]
Going to close this issue, if you still see it let us know
