### ISSUE TITLE
[Vue] Color attribute on ion-button does not work

### ISSUE THREAD

**Issue by sneko** [ionic-team/ionic#17880]
Hi,

I'm using the core package 4.1.x and also the vue package 0.0.2

I'm unable to make working the color attribute on `ion-button` elements. It was perfectly working before when I was using `script / link` tags to import Ionic.

I created a starter project so you can reproduce the issue:
https://github.com/sneko/ionic-debug

From my point of view, the `.button-native` element within the shadow is not able to retrieve the color variable. Here is the style it tries to take:
```
:host(.button-solid.ion-color) .button-native {
    background: var(--ion-color-base);
    color: var(--ion-color-contrast);
}
```

Unfortunately `--ion-color-base` and `--ion-color-contrast` does not reflect the real values of the color attribute.

I hope someone will be able to help me because it breaks my whole project UI 🤣 

Thank you,

**Comment by brandyscarney** [comment]
Hello! Are you importing the following files somewhere?

```
/* Core CSS required for Ionic components to work properly */
@import "~@ionic/core/css/core.css";

/* Basic CSS for apps built with Ionic */
@import "~@ionic/core/css/normalize.css";
@import "~@ionic/core/css/structure.css";
@import "~@ionic/core/css/typography.css";

/* Optional CSS utils that can be commented out */
@import "~@ionic/core/css/padding.css";
@import "~@ionic/core/css/float-elements.css";
@import "~@ionic/core/css/text-alignment.css";
@import "~@ionic/core/css/text-transformation.css";
@import "~@ionic/core/css/flex-utils.css";
@import "~@ionic/core/css/display.css";
```

**Comment by sneko** [comment]
@brandyscarney you are right! Shame on me...

I saw this kind of imports several months ago but totally forgot about it. Is it precised somewhere in the documentation (didn't find)?

Thank you,

**Comment by brandyscarney** [comment]
@sneko I actually have a pull request open to add more documentation on those. This issue just reminded me to make some updates to it. :smile: 

If you'd like to add any feedback on there please do so! https://github.com/ionic-team/ionic-docs/pull/535
