### ISSUE TITLE
Menu Button not showing

### ISSUE THREAD

**Issue by ernest0galdamez** [ionic-team/ionic#17898]
Ionic Info

**Ionic:**

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\ErnestoDesktop\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.5
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.4.0

**Describe the Bug**

I'm new to Ionic and ive been working in a mobile hybrid app, and i followed this tutorial https://ionicacademy.com/ionic-side-menu-with-sub-items/ its about how to Create an Ionic 4 Side Menu with Sub Menu Items.
The problem i have right now is that the side menu button doesnt show on the first show for example if i do the Ionic Serve Command, it doesn't show the menu button ive read in several forums about the auto-hide="false" and persistent="true" but still not showing on first try.

![menu button](https://user-images.githubusercontent.com/17624864/55091982-5fcb4c80-5077-11e9-8b65-5cded772ed4e.png)

As you can see in the image above the image on the left is the first show of the page and the right side image is when i refresh the page.According to the tutorial this is my Menu.ts

Only happens in my first try, the first time i run the Ionic serve, the first time i open the app on android after installing.

According to the tutorial this is my Menu.ts

    import { Component, OnInit } from '@angular/core';
     
    @Component({
      selector: 'app-menu',
      templateUrl: './menu.page.html',
      styleUrls: ['./menu.page.scss'],
    })
    export class MenuPage implements OnInit {
     
      pages = [
        {
          title: 'Home',
          url: '/menu/main',
          icon: 'home'
        },
        {
          title: 'Menu',
          children: [
            {
              title: 'Premios',
              url: '/menu/premios',
              icon: 'gift'
            },
            {
              title: 'Canje de Puntos',
              url: '/menu/canjepuntos',
              icon: 'cash'
            },
            {
              title: 'Consulta de Puntos',
              url: '/menu/puntos',
              icon: 'card'
            },
            {
              title: 'Historial de Compras',
              url: '/menu/historial',
              icon: 'cart'
            },
            {
              title: 'Premios Reclamados',
              url: '/menu/premiosreclamados',
              icon: 'calendar'
            },
            {
              title: 'Contactanos',
              url: '/menu/contactanos',
              icon: 'mail'
            }
          ]
        }
      ];
     
      constructor() { }
     
      ngOnInit() {
      }
     
    }

Menu module ts

    import { NgModule } from '@angular/core';
    import { CommonModule } from '@angular/common';
    import { FormsModule } from '@angular/forms';
    import { Routes, RouterModule } from '@angular/router';
     
    import { IonicModule } from '@ionic/angular';
     
    import { MenuPage } from './menu.page';
     
    const routes: Routes = [
      {
        path: '',
        redirectTo: '/menu/main',
        pathMatch: 'full'
      },
      {
        path: '',
        component: MenuPage,
        children: [
          {
            path: 'main',
            loadChildren: '../main/main.module#MainPageModule'
          },
          {
            path: 'premios',
            loadChildren: '../premios/premios.module#PremiosPageModule'
          },
          {
            path: 'canjepuntos',
            loadChildren: '../canjepuntos/canjepuntos.module#CanjepuntosPageModule'
          },
          {
            path: 'puntos',
            loadChildren: '../puntos/puntos.module#PuntosPageModule'
          },
          {
            path: 'historial',
            loadChildren: '../historial/historial.module#HistorialPageModule'
          },
          {
            path: 'premiosreclamados',
            loadChildren: '../premiosreclamados/premiosreclamados.module#PremiosreclamadosPageModule'
          },
          {
            path: 'contactanos',
            loadChildren: '../contactanos/contactanos.module#ContactanosPageModule'
          },
          { path: 'premio',
           loadChildren: '../premio/premio.module#PremioPageModule' },
          { path: 'premio-single', 
           loadChildren: '../premio-single/premio-single.module#PremioSinglePageModule' },
        ]
      }
    ];
     
    @NgModule({
      imports: [
        CommonModule,
        FormsModule,
        IonicModule,
        RouterModule.forChild(routes)
      ],
      declarations: [ MenuPage ]
    })
    export class MenuPageModule { }

My Menu template:

    <ion-menu contentId="content" auto-hide="false" persistent="true" >
      <ion-header>
        <ion-toolbar color="dark">
          <ion-title>Menu</ion-title>
        </ion-toolbar>
      </ion-header>
     
      <ion-content>
     
        <div *ngFor="let p of pages">
     
          
          <ion-menu-toggle *ngIf="p.url">
            <ion-item [routerLink]="p.url" routerDirection="root" routerLinkActive="active">
              <ion-icon [name]="p.icon" slot="start"></ion-icon>
              <ion-label>
                {{ p.title }}
              </ion-label>
            </ion-item>
          </ion-menu-toggle>
          
     
          <ion-item button *ngIf="p.children?.length > 0" (click)="p.open = !p.open" [class.parent-active]="p.open" detail="false">
            <ion-icon slot="start" name="arrow-forward" *ngIf="!p.open"></ion-icon>
            <ion-icon slot="start" name="arrow-down" *ngIf="p.open"></ion-icon>
            <ion-label>{{ p.title }}</ion-label>
          </ion-item>
     
          
          <ion-list *ngIf="p.open">
            <ion-menu-toggle>
              <ion-item *ngFor="let sub of p.children" class="sub-item" [routerLink]="sub.url" routerDirection="root"
                routerLinkActive="active">
                <ion-icon [name]="sub.icon" slot="start"></ion-icon>
                <ion-label>
                  {{ sub.title }}
                </ion-label>
              </ion-item>
            </ion-menu-toggle>
          </ion-list>
     
        </div>
      </ion-content>
     
    </ion-menu>
     
    <ion-router-outlet id="content" main></ion-router-outlet>

This is the Main page where i'm showing the menu (only logged in users can see it).

    <ion-header>
      <ion-toolbar color="dark">
        <ion-buttons slot="start">
          <ion-menu-button></ion-menu-button>
        </ion-buttons>
        <ion-title>Home</ion-title>
        <ion-buttons slot="end">
          <ion-button>
            <ion-icon slot="end" name="barcode"></ion-icon>        
          </ion-button>
        </ion-buttons>
      </ion-toolbar>
    </ion-header>
     
    <ion-content padding>
        <div class="welcomeTextDiv">
            <h1 class="welcomeText">BIENVENIDO</h1><br><br>
          </div>
          <h5 style="font-size: 25px; margin: auto; color: red !important; text-transform: uppercase; text-align: center" class="errorMessage">
            {{ error }}
          </h5> 
          <div class="userDiv">
            <h2 class="userText">{{ cliente }}</h2>
          </div>
          <div class="messageDiv">
            <h2 class="messageText">Felicidades has ganado {{ points }} puntos</h2>
          </div>
    </ion-content>

I've followed the whole tutorial but it doesn't seems to work for me your help will be much appreciated.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by ernest0galdamez** [comment]
> Hi there,
> 
> Thanks for the issue. Can you provide a repository with the code required to reproduce this issue?
> 
> Thanks!

Hello i added a repository in my account, thanks for your fast reply
https://github.com/ernest0galdamez/micliente-app

**Comment by brandyscarney** [comment]
@ernest0galdamez Can you please try using `autoHide`? Angular [properties](https://ionicframework.com/docs/api/menu-button#properties) should be camelCase not kebab-case. 

For future support questions, please refer to our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for quick help with questions. :smile:

**Comment by ernest0galdamez** [comment]
> @ernest0galdamez Can you please try using `autoHide`? Angular [properties](https://ionicframework.com/docs/api/menu-button#properties) should be camelCase not kebab-case.
> 
> For future support questions, please refer to our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for quick help with questions. 😄

Hello Brandy, thanks for your reply i tried both ways (autoHide and auto-hide) even the "persistent" cause i read in older forums they solved using it that way but still doesn't work.

**Comment by brandyscarney** [comment]
@ernest0galdamez Are you placing it on the `ion-menu-button`? Here's how it would look in Angular:

```
<ion-menu-button autoHide="false"></ion-menu-button>
```

Menu button properties: https://ionicframework.com/docs/api/menu-button#properties

`persistent` does not exist in the latest versions. 🙂 

I tried running your project but without diving into the code I can't get past the login screen. Adding this shows the menu button though:

```
<ion-header>
	<ion-toolbar color="dark">
		<ion-buttons slot="start">
			<ion-menu-button autoHide="false"></ion-menu-button>
		</ion-buttons>
		<ion-title>Login</ion-title>
	</ion-toolbar>
</ion-header>
```

If you are still seeing this as a bug it would be helpful to provide a repository with a **minimal amount of code** and simple steps to reproduce. Thank you. 🙂 

<img src="https://user-images.githubusercontent.com/6577830/55109120-6f648880-50ab-11e9-9eae-efefb0e742cf.png" width="300">

**Comment by ernest0galdamez** [comment]
> @ernest0galdamez Are you placing it on the `ion-menu-button`? Here's how it would look in Angular:
> 
> ```
> <ion-menu-button autoHide="false"></ion-menu-button>
> ```
> Menu button properties: https://ionicframework.com/docs/api/menu-button#properties
> 
> `persistent` does not exist in the latest versions. 🙂
> 
> I tried running your project but without diving into the code I can't get past the login screen. Adding this shows the menu button though:
> 
> ```
> <ion-header>
> 	<ion-toolbar color="dark">
> 		<ion-buttons slot="start">
> 			<ion-menu-button autoHide="false"></ion-menu-button>
> 		</ion-buttons>
> 		<ion-title>Login</ion-title>
> 	</ion-toolbar>
> </ion-header>
> ```
> If you are still seeing this as a bug it would be helpful to provide a repository with a **minimal amount of code** and simple steps to reproduce. Thank you. 🙂
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/6577830/55109120-6f648880-50ab-11e9-9eae-efefb0e742cf.png">

Brandy, thanks again for your reply, i updated my repository with this setting i was setting up the autoHide="false"in the main menu html, i added it on the home page and now i see the button BUT, now shows the button but its not working.

I click the button but nothing happens, until i refresh the page.
Just to make myself clear this is only on the first run after the ionic serve or when i install the app on android and run it.

I think its because of the same issue maybe the button action is not ready at this time i really don't know, if you are still interested in helping me you can use this username and password on the login page:
user: tony
pass: er25fr14

**Comment by ernest0galdamez** [comment]
Thanks for all your help Brandy, the issue was with the app-routing. Its fixed and i think its working as intended now.
