### ISSUE TITLE
ionic-angular: ion-range and horizontal scroll

### ISSUE THREAD

**Issue by saoron** [ionic-team/ionic#17894]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Horizontal scroll acts funny with range bar on iOS device (Chrome works as expected)

![IMG_0638 TRIM](https://user-images.githubusercontent.com/4144775/55085294-1991df80-50af-11e9-96ad-c1e792d173d9.gif)

**Expected behavior:**
Range should get priority on scroll, now the cards and range bar scroll together

**Steps to reproduce:**

**Related code:**

https://stackblitz.com/edit/ionic-ptblad

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (/Users/saoron/.npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/saoron/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 7.0.0
   NodeJS            : v10.14.1 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Which version of iOS are you testing this on? I am testing on iOS 12.2 and I am unable to reproduce the issue.

Thanks!

**Comment by saoron** [comment]
I've just upgraded to 12.2 to confirm, still having the same issue, iPhone XS max.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the follow up. Are you seeing this issue in Safari or when running in a standalone application? (or both?)

**Comment by saoron** [comment]
When running as an app.

**Comment by liamdebeasi** [comment]
Ok, I am able to reproduce it in a standalone app.

Thanks for filing this issue! We will take a look.

**Comment by sneko** [comment]
@liamdebeasi I'm also getting the same behavior with vertical scroll.

I mean, the range is horizontal but if I start sliding its cursor diagonally my page will start scrolling vertically a bit. It renders a weird behavior from user perspective.

Have you encounter the same issue? I'm on Ionic 4.4.0 with iOS 12.2.

Thank you,

**Comment by saoron** [comment]
Any news on this?

**Comment by saoron** [comment]
Looks like this has been fixed on the latest Ionic release.
