### ISSUE TITLE
Ionic 4 no ion-icons after upgrade to iOS 12.2 on device

### ISSUE THREAD

**Issue by dominikse** [ionic-team/ionic#17908]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

After upgrading iOS to 12.2 the unchanged ionic v4 app does not show icons anymore on the device. 

Before iOS 12.2 icons placed in HTML with "ion-icon" were displayed. Now there is empty space. They are not completely gone because they are still allocating their spaces but they are not rendered anymore.

**Expected behavior:**

Icons placed in HTML with "ion-icon" are displayed.

**Steps to reproduce:**

**Related code:**

```
<ion-icon name="code-working"></ion-icon>
```

**Other information:**

If served in browser via ionic serve everything is fine. Looks like iOS 12.2 changed something in handling/rendering of svg's?
Other jpg/png-images or unicode emoji's are still in place.

**Ionic info:**

```
Ionic:
   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.2.9
   @ionic/angular-toolkit        : not installed

Cordova:
   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5

System:
   NodeJS : v10.8.0
   npm    : 6.2.0
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by dominikse** [comment]
Hi,

I just created a blank starter app and this one looks good... hm.
The only difference is here:
```
@angular-devkit/build-angular : 0.13.7
@angular-devkit/schematics    : 7.2.4
@angular/cli                  : 7.3.7
@ionic/angular-toolkit        : 1.4.1
```
I'll try to update those packages, maybe it solves my issue...

**Comment by dominikse** [comment]
All right, I found a solution for the issue:
Basically a strange behaviour and I'm not aware why it suddenly happens on the device but I was able to reproduce it with my colleague: App was fine, iOS upgrade to 12.2 and the icons were gone.

To fix it I found these comments:
[https://github.com/ionic-team/ionic/issues/17245#issuecomment-457309291](https://github.com/ionic-team/ionic/issues/17245#issuecomment-457309291)
[https://github.com/ionic-team/ionic/issues/17019#issuecomment-452828443](https://github.com/ionic-team/ionic/issues/17019#issuecomment-452828443)

So I changed the angular.json, rebuild the app and after updating the apps on the devices the icons were back.

My fault I overlooked this note/change in the release docs of 4.0.0-rc.1.
