### ISSUE TITLE
ion-label wrapping text when inside ion-item

### ISSUE THREAD

**Issue by swavans** [ionic-team/ionic#17910]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When I create a label inside an ionic item the text automatically wraps.
Even when specifyinh no wrap on the item and or label and/or assinging class
ion-text-nowrap

**Expected behavior:**
I expect the text inside the label to not wrap 

**Steps to reproduce:**
Create grid with rows and cols and fill them with an item and label.

**Related code:**
```
<ion-grid>
<ion-row><ion-col size="1"><ion-item>
<ion-label>Extremely long text</ion-label>
<ion-item>
</ion-col>
</ion-row>
</ion-grid>


**Ionic info:**
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 5 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.15.2 (/usr/local/bin/node)
   npm        : 6.8.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61

**Comment by brandyscarney** [comment]
Thanks for the issue! Please provide a Codepen, Plunker, or repository with the minimal amount of code to reproduce the problem. I am not able to reproduce using the code provided: https://codepen.io/brandyscarney/pen/XGvpLE?editors=1010

**Comment by swavans** [comment]
<p class="codepen" data-height="265" data-theme-id="0" data-default-tab="html,result" data-user="brandyscarney" data-slug-hash="XGvpLE" style="height: 265px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid black; margin: 1em 0; padding: 1em;" data-pen-title="XGvpLE">
  <span>See the Pen <a href="https://codepen.io/brandyscarney/pen/XGvpLE/">
  XGvpLE</a> by Brandy Carney (<a href="https://codepen.io/brandyscarney">@brandyscarney</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
</p>
<script async src="https://static.codepen.io/assets/embed/ei.js"></script>

**Comment by brandyscarney** [comment]
I think there is a misunderstanding here. The items are currently *not* wrapping, they are adding an ellipsis `...`. Are you looking to have them wrap to the next line like this? https://codepen.io/brandyscarney/pen/aMeJwX?editors=1000

**Comment by swavans** [comment]
Mybad
