### ISSUE TITLE
Fullscreen attribute on ion-content breaks back animation for ion-header elements

### ISSUE THREAD

**Issue by dalemugford** [ionic-team/ionic#17918]
# Bug Report

**Ionic version:**

[x] **4.1.2**

**Current behavior:**
`ion-content` with `fullscreen` attribute causes a flicker in text/elements in the `ion-header`'s `ion-toolbar` when navigating back from another view (on device— iPhone 6s, and iPhone X).

**Expected behavior:**
`ion-content` with `fullscreen` attribute will behave like `ion-content` without the attribute, with `ion-title` and buttons fading/sliding smoothly.

**Steps to reproduce:**
Navigate back from any page to a page with the fullscreen `attribute` on `ion-content`. Observe the ion-header appearance vs. w/o the fullscreen attribute.

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 5 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 7.0.0
   NodeJS     : v10.15.0 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2 Build version 10E125
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. I am not seeing any flickering when testing this on an iOS device. Are you able to provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by dalemugford** [comment]
Damn— ok I’ll put one together for you.


Dale M.
905.966.3693
dalemugford@me.com

**Comment by jayordway** [comment]
I am experiencing this same problem. There is a slight difference thats quite noticeable when navigation back from pages that have the fullscreen attribute set to true.
