### ISSUE TITLE
@ionic/vue controllers don't pass componentProps properly

### ISSUE THREAD

**Issue by lherman-cs** [ionic-team/ionic#17916]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

If the componentProps are passed like below
```javascript
          componentProps: {
            data: {
              content: 'New Content',
            },
            propsData: {
              title: 'New title',
            },
          },
```

I need to access the props by
```javascript
this.propsData.title
```

**Expected behavior:**

According to this documentation, https://ionicframework.com/docs/api/modal, `propsData` will be proxied to the vue component's props

I expect to access the props by
```javascript
this.title
```

**Steps to reproduce:**

**Related code:**

Parent.vue

```javascript
...
  methods: {
    async openModal() {
      console.log(Modal);
      const m = await this.$ionic.modalController.create({
        component: Modal,
        componentProps: {
          id: this.$route.params.id,
          doc: this.doc
        }
      });
      console.log(m.componentProps);
      return m.present();
    }
  }
...
```

Modal.vue

```
...
  mounted() {
    console.log(this.propsData.id);
  },
...
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI) : 4.12.0

System:

   NodeJS : v11.12.0
   npm    : 6.9.0
   OS     : Linux 4.19
```

**Comment by lherman-cs** [comment]
I think that before this line, https://github.com/ionic-team/ionic/blob/master/vue/src/util.ts#L5, the `propsData` and `data` should be expanded so that there's no need to access `propsData` and `data` in the modal component since later everything will be assigned to the element here, https://github.com/ionic-team/ionic/blob/master/core/src/utils/overlays.ts#L11.

**Comment by michaeltintiuc** [comment]
The way to pass props and data should be done in this way:
```js
      return this.$ionic.modalController
        .create({
          component: () => import('@/components/modal/index.vue'),
          componentProps: {
            parent: this,
            data: {
              content: 'New Content',
            },
            propsData: {
              title: 'New title',
              closeMe: () => {
                this.$ionic.modalController.dismiss()
              },
            },
          },
        })
        .then(m => m.present())
```

as it hooks into Vue here: https://github.com/ionic-team/ionic/blob/master/vue/src/controllers/vue-delegate.ts#L35
[Docs on propsData](https://vuejs.org/v2/api/#propsData
)
so the whole `componentProps` object is being passed to a newly created [Vue instance](https://vuejs.org/v2/guide/instance.html)
