### ISSUE TITLE
Components placed inside ion-content have zero size after view init

### ISSUE THREAD

**Issue by vially** [ionic-team/ionic#17920]
# Bug Report

**Ionic version:**

[x] **4.1.2**

**Current behavior:**

The initial size of a component placed inside `<ion-content></ion-content>` is `0 x 0` (`offsetWidth = 0`, `offsetHeight = 0`) when read in `ngAfterViewInit`. This happens when the component is configured to fill up its container (e.g.: `style="width: 100%; height: 100%"`).

This is particularly problematic for elements that need to know their actual size for initializing a drawing context (e.g.: a `<canvas />` element). In Angular components `ngAfterViewInit` seems the right place for initializing a canvas element that fills its parent with the proper size. But in Ionic projects this doesn't work and the element size is initially reported as 0.

**Expected behavior:**

The component should be able to read its **actual size** in `ngAfterViewInit`. Or at least a different hook should be provided that allows a component to know when it can ***reliably detect its size***.

During some tests I noticed that reading the element size after `ionViewDidEnter` gets called, the size is reported correctly. However, this is not a good solution as the `ionViewDidEnter` hook is only available in `pages` so it can not be used in normal (e.g.: non-page) `components`.

**Steps to reproduce:**

1. Clone https://github.com/vially/ionic-bugs-demos
1. `npm install`
1. `ng serve`

Open `http://localhost:4200` and click the `Go to canvas page (using ion-content)` link. The console logs will print:
```
canvas size on view init: 0x0
canvas size after timeout: 996x950
```

Then go back to the homepage and click the `Go to canvas page (using div content)`. Notice how the console logs have changed to:

```
canvas size on view init: 1011x510
canvas size after timeout: 1011x510
```

The only difference between the two pages/routes is that on the first page the component is placed inside an `<ion-content></ion-content>` element, while on the second page the component is placed inside a plain `<div></div>`.

**Related code:**

https://github.com/vially/ionic-bugs-demos

**Other information:**

Ideally the components should be able to reliably read their size in `ngAfterViewInit`. However, if that's not possible due to various reasons (e.g.: the way `<ion-content />` or the ionic router transitions are implemented) I think at least some kind of hook should be provided to ***all*** components which would allow them to know when it's safe to read their size.

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/home/vially/.config/yarn/global/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.13.7
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.7
   @ionic/angular-toolkit        : 1.4.1

System:

   NodeJS : v10.15.3 (/usr/bin/node)
   npm    : 6.9.0
   OS     : Linux 5.0
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. The reason this is happening is because `ion-content` has not finished loaded yet.

If you need to find the size of the `canvas` once `ion-content` has loaded, you'll need to do `await contentElem.componentOnReady()` where `contentElem` is the `ion-content` that wraps the `canvas`.

Thanks for using Ionic!

**Comment by vially** [comment]
Thanks for the reply. However, I don't think that's a very good solution because the canvas might be deep down in a component tree which doesn't have direct access to `ion-content`.

```
<ion-content>
  <component-foo>
    <component-bar>
      <canvas></canvas>
    </component-bar>
  </component-foo>
</ion-content>
```
If you have a DOM tree similar to the one above it's not trivial for the `canvas` element to get a hold of the `<ion-content>` instance so it can listen to its `componentOnReady` promise.

And even it the `canvas` can get a hold of the `ion-content` instance, making a child component listen for  `<ion-content />` specific events makes for a poor design and creates undesirable tight coupling between components.

Also, is there any documentation about this `componentOnReady` function and how it fits into the Angular lifecycle hooks?

**Comment by liamdebeasi** [comment]
Hi there,

I agree, it's not a perfect solution. We typically don't recommend checking the element dimensions right at the beginning as it will cause jank, but that's probably the easiest way to do it. 

The Stencil docs have more info on methods and how `componentOnReady` works: https://stenciljs.com/docs/methods/

**Comment by vially** [comment]
> We typically don't recommend checking the element dimensions right at the beginning as it will cause jank

What would then be an appropriate time to check them? I mean which event/hook can be used to check the dimensions which guarantees that the dimensions are actually set at that point?

**Comment by liamdebeasi** [comment]
Hi there,

The `DomController` should be able to help with this. The main issue stems from the fact that checking things such as `offsetWidth` forces a layout/reflow in the browser. When this happens at the same time as other reflows/calculations, jank is created.

What you can do to avoid jank as much as possible is `await contentElem.componentOnReady()` and then get the canvas dimensions via the `read` method in the `DomController`. You'd do something like:

```
import { DomController } from '@ionic/angular';

...

constructor(
  private domController: DomController
) {}

...

async ngAfterViewInit() {
  await contentElem.componentOnReady();
  this.domController.read(() => {
    this.printCanvasSize('canvas in dom controller');
  });
}

...
```

When the `read` method gets called, the callback function you pass in gets queued up to be run using `requestAnimationFrame`. 

For more info on how `DomController` works, you can read: https://www.joshmorony.com/increasing-performance-with-efficient-dom-writes-in-ionic-2/

The article is for Ionic 2, so method names may have changed, but the underlying concepts remain the same. 

For more info on `requestAnimationFrame`, check out its MDN page: https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame

Hope this helps!

**Comment by vially** [comment]
Thanks, this is helpful. I didn't know about the `DomController` and it seems really useful.

I think your code example should be good enough for now as a workaround. Although it still seems a bit clunky for a child component to call a function on an `<ion-content />` element just so it can know when its size can be safely computed. But I guess that will have to do for now.

**Comment by vially** [comment]
I've [implemented](https://github.com/vially/ionic-bugs-demos/commit/9f98f1efb2f797a5aefe5b9a985d88425b44d4c3) the workaround you suggested and now the original demo works as expected. However, this doesn't completely solve the problem because now if the *exact same page* is shown in a modal the initial size is again zero.

I've created another [branch](https://github.com/vially/ionic-bugs-demos/tree/canvas-inside-modal) on the demo repository to showcase this problem.

With your workaround in place you'll notice that **navigating** to the canvas demo page (using the first two links) correctly prints the initial size to the console:

```
canvas size on view init: 973x950
canvas size after timeout: 973x950
```

However, showing the exact same page inside a modal (by clicking the `Open canvas modal` button) gives back the erroneous result:
```
canvas size on view init: 0x0
canvas size after timeout: 585x544
```
Also, in our production app, just waiting for the ion-content's `componentOnReady()` promise is sometimes not enough. Depending on the components sitting between the `canvas` element and the `ion-content` in the DOM tree we sometimes have to listen for multiple `componentOnReady` promises. In one particular example we need to listen for this method on an `ion-col` component. However, I couldn't reproduce this in the demo repository, so I'll need to investigate this a bit further.

Overall this whole approach seems a bit too complicated for something that I feel should have a more trivial solution. Could it be that we're missing something or we're using some of these components "wrong"?

All we need is for a child component (e.g.: a canvas) to *reliably know when its size is "stable"* so it can begin its work.

**Comment by liamdebeasi** [comment]
When in a modal you should only need to wait for the modal's `ion-content` to be ready. It might be worth implementing logic that that finds the "nearest" `ion-content`: https://developer.mozilla.org/en-US/docs/Web/API/Element/closest

**Comment by vially** [comment]
But that's exactly what the [current demo code](https://github.com/vially/ionic-bugs-demos/blob/995cadf9feb9c2e1cbf62d6805a2c5a7eeaff66b/src/app/demo-canvas/demo-canvas.component.ts#L13) that I've linked above is doing and it still gives the erroneous result.

**Comment by liamdebeasi** [comment]
Try waiting for `ion-app` to be ready: 

```
await document.querySelector('ion-app').componentOnReady();
```

**Comment by vially** [comment]
Waiting for `ion-app` to be ready does not seem to make any difference. Also, I kind of expected it to not make any difference because by the time the user clicks the `Open canvas demo` button, the `ion-app` component should have long been ready.

**Comment by liamdebeasi** [comment]
Hi there,

With modals you should be using `ionViewDidEnter` as one of the lifecycle hooks. I believe you can use it with the main page as well.

I posted an example here using `ionViewDidEnter`, and the canvas is reporting the correct dimensions: https://github.com/liamdebeasi/modal-example 

If you are still having issues then it's possible that another component you are using is interfering. Please let me know if this solution works for you.

**Comment by vially** [comment]
Yes, we've been using `ionViewDidEnter` as a workaround to this issue for some time now and it kind of works. The main issue with it is that it's not available to `components`, it's only available to `pages`.

In your example the `canvas` element is placed directly inside the `page` component. This means, in that component, you have direct access to both 1) the element for which you want calculate the dimension and 2) the `ionViewDidEnter` event.

However, moving the canvas to a separate component where you no longer have access to the `ionViewDidEnter` event makes the implementation more inconvenient and creates tight coupling between components as you now have to pass this event to the component somehow.

Also, making a component aware that it needs to wait for either `ionViewDidEnter` or the `componentOnReady` events of some other components up in the DOM tree doesn't seem right.

PS: As a side note, it also looks like the `ionViewDidEnter` event only fires when the browser tab gets focus which is undesirable in some cases. This can be tested by refreshing a page and letting it load in the background by switching to another browser tab. What we've noticed is that the `ionViewDidEnter` event only fires once the tab is reopened/focused.

**Comment by liamdebeasi** [comment]
Hi there,

The child component shouldn't have to worry about whether or not the parent component is loaded. Additionally, I don't think passing props through child components is a maintainable solution. In the parent component, you can do: `<canvas-component *ngIf="loaded"></canvas-component>` and then set `loaded = true` in the `ionViewDidEnter` method in the parent page/modal.

Since this isn't a bug in Ionic, so I would suggest you post on our [forum](http://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com) if you need assistance implementing your specific use case.

Thanks!

**Comment by vially** [comment]
Thanks for the feedback. 

So what you're saying is that there's no way in Ionic for a **component** (which is not a **page**) to know when its size is known, other than:
a) doing all the plumbing of passing down the "ionViewDidEnter" event to the component somehow (not necessarily though props), or
b) listening for one or more `componentOnReady` events (*but this only works if the component is not inside a modal*)

Are these two the only options available in Ionic at the moment?

**Comment by liamdebeasi** [comment]
Hi there,

This particular issue is something you'll likely find in Web Components in general, not specifically Ionic (Ionic is built using Web Components). It might be worth doing more research to see if the wider community has other strategies for dealing with this. We offer `ionViewDidEnter` and `ionViewWillEnter` as a way of helping users deal with the asynchronous nature of something of these components (especially when animations are involved).

I think the simplest approach would be `<canvas-component *ngIf="loaded"></canvas-component>` (assuming you're using Angular). It doesn't require passing anything down to child components and only requires a boolean to be managed from the parent component. So maintenance of this will be pretty minimal.
