### ISSUE TITLE
[ionic 4.1.2]Tabs is not working on ios10 [safari10] 

### ISSUE THREAD

**Issue by royanon** [ionic-team/ionic#17924]
# Bug Report

**Ionic version:**
[x] **4.1.2**

**Current behavior:**
Tabs is not working on ios10, the :host style is disappeared on the ion-tab-bar elements.

**Expected behavior:**
Tabs should work.

**Steps to reproduce:**
Just use safari10 to visit the official demo url linked below.
https://ionicframework.com/docs/demos/api/tabs/index.html?ionic:mode=ios
Test with simulator iphone 5s with ios 10 and also real device iphone 5s, iphone 7 with ios 10. Same problems appeared.

See error
![ionic-iphone-ios10](https://user-images.githubusercontent.com/16112016/55341056-8571af00-54d8-11e9-9d4e-da052ff3869d.png)

**Ionic info:**
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v10.14.0 
   npm               : 6.9.0
   OS                : Windows 10

**Comment by royanon** [comment]
Try 4.1.2 with hardware.

![WhatsApp Image 2019-04-03 at 18 46 14](https://user-images.githubusercontent.com/16112016/55473284-e5836500-5640-11e9-8033-7c3d3662d8a0.jpeg)

**Comment by supperdsj** [comment]
same issue here

**Comment by royanon** [comment]
Tested that all shadow dom does not work in iOS 10.x. 
Is it possible to work like what ionic 4 does in IE?

**Comment by royanon** [comment]
Test with two version.
- iOS 10.0 not work
- iOS 10.2 not work

**Comment by royanon** [comment]
Also tested with ionic v4.2.0 also not working.

**Comment by royanon** [comment]
Is there a fix in the plan? because there is a majority of user still using iOS 10.x

**Comment by royanon** [comment]
Test with 1 more version
- iOS 10.3 working.

It doesn't work for iOS 10.2, 10.0.

**Comment by royanon** [comment]
Also test iOS 10.1 not work.

Sum up
- iOS 10.3 working
- iOS 10.2 not work
- iOS 10.1 not work
- iOS 10.0 not work

**Comment by supperdsj** [comment]
> Also test iOS 10.1 not work.
> 
> Sum up
> 
> * iOS 10.3 working
> * iOS 10.2 not work
> * iOS 10.1 not work
> * iOS 10.0 not work

Ionic 4.3.0 released, did this bug resolved?

**Comment by royanon** [comment]
Test with v4.3.0

- iOS 10.3 working
- iOS 10.2 not work
- iOS 10.1 not work
- iOS 10.0 not work

**Comment by royanon** [comment]
Is there a schedule for fixing this issue?  A lot of user complaints about this. Besides tab issue, the icons and css also not working. The number of user using IOS below 10.3 is surprising high. Its like 5 to 10 complaint per day. Please fix this issue, thx

**Comment by royanon** [comment]
Test with @ionic/angular v4.4.0
- iOS 10.2 not work
- iOS 10.1 not work
- iOS 10.0 not work

Let's use google flutter instead.

**Comment by supperdsj** [comment]
finally on deck

**Comment by royanon** [comment]
oh .... backlog again

**Comment by liamdebeasi** [comment]
Thanks for the issue! We recently released Ionic Framework v5 which brings a lot of exciting new features to the framework. In keeping with how iOS and Android are evolving, we have decided to drop support for Android 4.4 and iOS 10 with this latest release.

Because all our efforts are now focused on Ionic 5, Ionic 4 will only receive security patches moving forward. As a result I am going to close this issue.

Please see https://ionicframework.com/docs/intro/browser-support  for an up to date list of supported browsers and platforms.

Additionally, please see https://ionicframework.com/blog/announcing-ionic-5/ for more info regarding Ionic Framework v5.

For anything regarding our supported platforms, please open a new issue.
