### ISSUE TITLE
Error when build with --prod flag

### ISSUE THREAD

**Issue by joao-jr** [ionic-team/ionic#17946]
I'm getting following error when build --prod

ERROR in : Unexpected value 'NavParams in PROJECT_FOLDER/node_modules/@ionic/angular/dist/directives/navigation/nav-params.d.ts' imported by the module 'SendMessagePageModule in PROJECT_FOLDER/src/app/send-message/send-message.module.ts'. Please add a @NgModule annotation.

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Steps to reproduce:**
Add a modal controller and pass parameters.
At modal component :
import { NavParams, ModalController } from '@ionic/angular';

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : 9.0.0
   Cordova Platforms     : android 8.0.0, browser 5.0.4, ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 17 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/developer/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 7.0.0
   NodeJS            : v11.12.0 (/usr/local/Cellar/node/11.12.0/bin/node)
   npm               : 6.7.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2 Build version 10E125
```

**Comment by liamdebeasi** [comment]
Hi there, 

Can you try this again on a more recent version of Ionic? A lot of changes have gone into navigation even in the release candidates.

If the issue still persists, please post your modal component code as well as its corresponding `.module` file if it exists.

Thanks!

**Comment by joao-jr** [comment]
Same problem, when try build --prod

**Comment by liamdebeasi** [comment]
Hi there,

Can you describe your problem a bit more? Also a repo with the code required to reproduce this issue would be very helpful.

Thanks!
