### ISSUE TITLE
Keyboard push up, footer animation laggy

### ISSUE THREAD

**Issue by ejerskov** [ionic-team/ionic#17947]
# Bug Report

**Ionic version:**
[x] **4.10.2**

**Current behavior:**
When a footer is being pushed up by the keyboard, the animation is very clunky and laggy. See gif below:
![keyboard](https://user-images.githubusercontent.com/18116039/55509921-62bcd300-565d-11e9-8282-4a7ec882ab97.gif)

**Expected behavior:**
Expected behaviour is that the footer resides on top of the keyboard all the way up and isn't moving in steps.

**Steps to reproduce:**
Simply having a <ion-footer> element that is pushed up by the keyboard:
<preference name="KeyboardResize" value="true" />

**Related code:**
```
<ion-footer>
  <ion-toolbar>
     Toolbar on top of keyboard
  </ion-toolbar>
</ion-footer>
```

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.13.7
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.7
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 6 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : ios-sim/9.0.0-dev.1 darwin-x64 node-v10.15.1
   NodeJS     : v10.15.1 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61

```

**Comment by ejerskov** [comment]
Bump?

**Comment by sjmellor39** [comment]
Any update on this? I'm doing similar with 2 CTA's in ion-footer and the lag is bad at best.

**Comment by ahmadwa** [comment]
same problem here.

`Ionic:

   Ionic CLI                     : 5.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.803.22
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 14 other plugins)

Utility:

   cordova-res : 0.8.1 
   native-run  : 0.2.7 (update available: 0.3.0)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v12.14.0 (/usr/local/bin/node)
   npm        : 6.13.4
   OS         : macOS Catalina
   Xcode      : Xcode 11.2.1 Build version 11B500
`

**Comment by ejerskov** [comment]
@liamdebeasi or anyone else from ionic who can provide som help? :)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Do you have viewport resizing enabled? If so, then it's likely this is just the viewport resizing (which can be a bit janky) causing the footer to be pushed up. It might be better if you disable the viewport resizing and use a CSS transform to move the footer yourself.

Please see https://github.com/ionic-team/cordova-plugin-ionic-keyboard#preferences for info on how to enable/disable viewport resizing.

**Comment by ejerskov** [comment]
Thanks @liamdebeasi 
Do you have any example of how to place the footer above the keyboard with css without resizing the viewport? I thought thats only possible with the resizing viewport

**Comment by liamdebeasi** [comment]
You should be able to listen for keyboard open/close events: https://github.com/ionic-team/cordova-plugin-ionic-keyboard. The event payload will tell you the height of the keyboard, and you can translate the footer element by that amount.
