### ISSUE TITLE
ion-datetime allows to select non existing dates ionic v4

### ISSUE THREAD

**Issue by narendrasinghrathore** [ionic-team/ionic#17952]
ion-datetime is allowing to select or not displaying correct data when we change selection in datetime picker.
@jgw96 
![ionic-datetime](https://user-images.githubusercontent.com/4208015/55553039-bc280f00-56fc-11e9-9276-aeb66a0f0104.gif)

**Comment by liamdebeasi** [comment]
Hi there,

Please update to Ionic 4.2 - this issue was fixed in that release. 

Thanks!

**Comment by narendrasinghrathore** [comment]
Updated to 4.2.0 
It's working as expected 

Thanks @liamdebeasi ✔

![datetime-ion](https://user-images.githubusercontent.com/4208015/55556907-47f26900-5706-11e9-9599-8f9d88ac3190.gif)
