### ISSUE TITLE
Missing nowrap attribute on ion-row

### ISSUE THREAD

**Issue by mikaelkaron** [ionic-team/ionic#17955]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

Missing attribute `nowrap` on `ion-row`.

**Expected behavior:**

Adding `nowrap` on `ion-row` should not cause ts errors.

**Related code:**

```
<ion-row nowrap></ion-row>
```

**Comment by brandyscarney** [comment]
Thanks for the issue! We have moved away from using attributes for CSS styling in Ionic 4 for this reason. While the styles still exist in our code in the form of attributes, we have added classes that we are recommending to use instead. Our documentation has been updated to the proper classes: https://ionicframework.com/docs/layout/css-utilities#flex-container-properties
