### ISSUE TITLE
Ionic 4 - Native camera plugin issues

### ISSUE THREAD

**Issue by Dak1411** [ionic-team/ionic#17958]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Gallery is not opening
Captured image is not returning.
Application crashes after taking picture

**Expected behavior:**
Camera plugin should work as expected

**Related code:**

```
html
-----
`<img [src]="studentImage!==null ? studentImage: 'assets/icon/ic_avatar.png'" class="add-picture" (click)="addImage()">`

.ts file
------
 public addImage() {
    this.genericServices.presentActionSheet(this.openGallery, this.openCamera);
  }

private openCamera = () => {
    this.studentImage = this.genericServices.selectPicture('camera');
    console.log('Captured Image:=>' + this.studentImage);
  }
  private openGallery() {
    this.studentImage = this.genericServices.selectPicture('gallery');
  }

service.ts
------
public async selectPicture(source) {
    let base64Image = null;
    const cameraOptions: CameraOptions = {
      quality: 75,
      destinationType: this.camera.DestinationType.DATA_URL,
      encodingType: this.camera.EncodingType.PNG,
      mediaType: this.camera.MediaType.PICTURE,
      sourceType: source === 'camera' ? this.camera.PictureSourceType.CAMERA : this.camera.PictureSourceType.PHOTOLIBRARY,
      correctOrientation: true
    };

    await this.camera.getPicture(cameraOptions).then((imageData) => {
      console.log('Returned Image=>' + base64Image);
      return base64Image = 'data:image/jpeg;base64,' + imageData;
    }).catch(() => {
    });
  }
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you provide the follow pieces of information?

1. The output of running `ionic info`
2. Which platform you are testing on (iOS, Android, etc)
3. If on Android, your user agent string (you can log window.navigator.userAgent while running the app)

Thanks!

**Comment by Dak1411** [comment]
@liamdebeasi Please find the info
1. Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\User\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.13.7
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.7
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (C:\Users\User\AppData\Local\Android\Sdk)
   NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

2. Android
3. (taken from ionic serve) Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Mobile Safari/537.36

Thanks

**Comment by liamdebeasi** [comment]
Hi there,

If you were to use the Cordova plugin directly (without Ionic Native) does it work?

Thanks!

**Comment by Dak1411** [comment]
@liamdebeasi, I didn't get what you said. I have only  tried using Ionic Native.

Thanks and Regards
Anand Raj

**Comment by liamdebeasi** [comment]
Hi there,

Ionic Native is just a convenience wrapper around the Cordova Camera plugin: https://github.com/apache/cordova-plugin-camera

I am trying to determine if this is an issue with the underlying plugin or with the Ionic Native wrapper. To use the Cordova plugin directly, you would do `navigator.camera.getPicture` instead of `this.camera.getPicture`.

Thanks!

**Comment by Dak1411** [comment]
Hi @liamdebeasi,

Does it makes any performance difference if I go with Cordova plugin directly?

Thanks and Regards
Anand Raj

**Comment by liamdebeasi** [comment]
Hi there,

There should be no performance impact when going with the plugin directly.

**Comment by Dak1411** [comment]
Hi @liamdebeasi,

Please give me some time as I am traveling i cannot check right now. Will reply back soon. 

Thanks and Regards
Anand Raj

**Comment by Dak1411** [comment]
Hi @liamdebeasi ,

When I sue the plugin directly I am getting error [error TS2339: Property 'camera' does not exist on type 'Navigator'.](url)

**Comment by Dak1411** [comment]
Hi @liamdebeasi,
I got the solution. The issue was because I wrote the camera function on a Common Service file and calling that service from my `.ts` page. So when I select the option 'Camera', even before capturing the image the function will returns an `[Object Object]`. 

To avoid it I had to write the camera function on my .ts file. This solved my issue. But Its not a right method of duplicating the same methods on multiple pages

**Comment by liamdebeasi** [comment]
Hi there,

I am glad to hear you were able to resolve this issue. I am going to close this issue as it doesn't seem to be related to the framework.

For further help with the Camera plugin, feel free to post on our [forum](http://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com)

Thanks!
