### ISSUE TITLE
@ionic/react `Uncaught TypeError: Cannot read property 'location' of undefined ...` IonRouterOutlet.js:40

### ISSUE THREAD

**Issue by d3vhound** [ionic-team/ionic#17954]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Following the conference react app structure nested routes sometimes throw this error randomly. Could be multiple things since both props don't seem to work at all on the IonBackButton component (defaultHref and goBack).

**Expected behavior:**
The back button on the IonBackButton component should not throw this error and should navigate to the defaultHref if no history exists.

**Steps to reproduce:**
You can reproduce this error by visiting the already live demo app here at this exact url https://ionic-react-conference-app.firebaseapp.com/schedule/sessions/1 then pressing the back button in the header.

**Other information:**
Both react apps side by side throwing the same error from pressing back button with no router history.

<img width="1401" alt="Screen Shot 2019-04-04 at 7 45 03 AM" src="https://user-images.githubusercontent.com/17565159/55557085-adb30680-56ae-11e9-80b5-df49e0e551e9.png">
<img width="1400" alt="Screen Shot 2019-04-04 at 7 44 37 AM" src="https://user-images.githubusercontent.com/17565159/55557098-b4da1480-56ae-11e9-8ad5-bef4a407b590.png">

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI) : 4.12.0

System:

   NodeJS : v11.4.0
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by mattrothenberg** [comment]
I can confirm this issue as well. Neither the `defaultHref` nor the `goBack` props seem to be doing anything on my Ionic React app.

**Comment by elylucas** [comment]
Fixes for this will be coming up in the next beta release
