### ISSUE TITLE
bug: Ion-refresher is disabled even if disabled property value is changed to 'false' from 'true'

### ISSUE THREAD

**Issue by Damini17** [ionic-team/ionic#17965]
# Bug Report

**Ionic version:**
ionic (Ionic CLI)             : 4.11.0
Ionic Framework               : @ionic/angular 4.1.1
@angular-devkit/build-angular : 0.13.6
@angular-devkit/schematics    : 7.2.4
@angular/cli                  : 7.3.5
@ionic/angular-toolkit        : 1.3.0

**Current behavior:**
Ion-refresher is disabled even if disabled property value is changed to 'false' from 'true'.

**Expected behavior:**
Ion-refresher has to work if disabled property has value equal to false.

**Steps to reproduce:**
1. Set disabled property of ion-refresher equal to true.
2. Change that property value to false.
3. Ion-refresher is still hidden/not working.

**Related code:**
HTML:
 ```
<ion-refresher slot='fixed' (ionRefresh)="doRefresh($event)">
    <ion-refresher-content pullingIcon="arrow-down">
    </ion-refresher-content>
  </ion-refresher>

  <ion-slides pager="true" loop="false" [options]='sliderConfig' (ionSlideTransitionStart)='transitionStart()'>

```
ts file:

```
@ViewChild(IonRefresher) refresherInstance: IonRefresher;
ngOnInit(){
    this.refresherInstance.disabled = false;
}

 async transitionStart() {
  const currentIndex = await this.slides.getActiveIndex();
  if (currentIndex === 0) {    
         this.refresherInstance.disabled = false;        
      } else {           
        this.refresherInstance.disabled = true;        
    }
  }
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. I am unable to reproduce the issue you have described. Can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by Damini17** [comment]
Hi @liamdebeasi,

Thanks for the reply. I have created a github repository which has the code to reproduce this issue. Please have a look to it : https://github.com/Damini17/ion-refresher-demo

1. Go to tab 2 page. I want the refresher to be enabled only for the first slide(index 0) and hidden/not working for the rest of the slides.
2. I have used checkRefresherDisabled boolean variable for the [disabled] property of ion-refresher.
3. By default I set the property as false, and set it to be true for other slides index.

Steps to reproduce the issue:
1. The refresher will work fine for the first time for the first time.
2. Swipe to the other slides, which sets the checkRefresherDisabled property as true.
3. Swipe back to first slide again, the refresher is not working even though I have set the disabled property as false back again.

Thanks!

**Comment by liamdebeasi** [comment]
Hi there,

Is this issue still reproducible on Ionic Framework 4.11.1?
