### ISSUE TITLE
Unable to access localstorage inside firebase.database

### ISSUE THREAD

**Issue by harpreet2602** [ionic-team/ionic#17960]
this.storage is not accessible inside firbase.database function. Throws below error:

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'storage' of undefined
TypeError: Cannot read property 'storage' of undefined

```
{
	this.storage.set('I am able to access storage', "uid");

	firebase.database().ref('/userProfile/' + uid).once('value').then(function(snapshot) {
	  const userDetails = snapshot.val();
	  this.storage.set('I am able NOT* to access storage', "uid");
	});
}
```

**Comment by liamdebeasi** [comment]
Hi there,

I am going to close this as it is a support request, but my bet is that you'll need to use an arrow function:

```
(snapshot) => {
```

instead of 

```
function(snapshot) {
```

Thanks for using Ionic!
