### ISSUE TITLE
checked default not working on value change ion-segment ionic v4

### ISSUE THREAD

**Issue by narendrasinghrathore** [ionic-team/ionic#17966]
[x] **4.x**

**Current behavior:**

On initialization of ion-segment , we can set the value property of ion-segment using component property and also set value property of ion-segment-button.

> Segment buttons are groups of related buttons inside of a Segment. They are displayed in a horizontal row. A segment button can be checked by default by adding the checked attribute or by **_setting the value of the segment to the value of the segment button._** Only one segment button should be selected at a time.

But if component property get new value, ion-segment value property doesn't update or allow to select default one .

ion-segment value="home"
ion-segment-button value="home"

Not selecting default one. 
![image](https://user-images.githubusercontent.com/4208015/55611891-7fafee00-57a4-11e9-8e03-1cb5e9545e24.png)

**Expected behavior:**

It should update.

You can find code here:
[Parent ](https://github.com/narendrasinghrathore/todo_app_ionic/tree/master/src/app/calendar)component that update/ passes property

[Child ](https://github.com/narendrasinghrathore/todo_app_ionic/tree/master/src/app/calendar/component/week)component that contain ion-segment

![ion-segment](https://user-images.githubusercontent.com/4208015/55611909-90606400-57a4-11e9-9e00-4077236e797c.gif)

@liamdebeasi

**Comment by narendrasinghrathore** [comment]
styling the content

**Comment by JVanloofsvelt** [comment]
I am experiencing the same problem. When using *ngFor to generate the ion-segment-button elements, the active slide loses its focus color whenever the collection (over which the ngFor iterates) changes.

**Comment by dozsolti** [comment]
I found a way. This will set the scroll manually to that element.

**First** you have to get the ion-segment: 
in HTML:
`<ion-segment #mySegment [(ngModel)] ...`
in TS:
`@ViewChild("mySegment", { read: ElementRef }) private mySegment: ElementRef;`

**Second** you will need the AfterViewChecked Angular hook, [see here more details](https://angular.io/guide/lifecycle-hooks#afterview)

**After** that you have to find the checked ion-segment-button:

_let activedChild = null;
for (let i = 0; i < this.mySegment.nativeElement.children.length; i++) {
      if (this.mySegment.nativeElement.children[i].checked)
        activedChild = this.mySegment.nativeElement.children[i];
    }_

**And after all that** you can set the scroll of ion-segment to that ion-segment-button, but first checking for activedChild(just to be sure that it exists):
_if (activedChild)
                        this.mySegment.nativeElement.scrollLeft = activedChild.offsetLeft;_

**Full function here**
`ngAfterViewChecked(): void {`
`    let activedChild = null;`
`    for (let i = 0; i < this.mySegment.nativeElement.children.length; i++) {`
`      if (this.mySegment.nativeElement.children[i].checked)`
`        activedChild = this.mySegment.nativeElement.children[i];`
`    }`
`    if (activedChild)`
`      this.mySegment.nativeElement.scrollLeft = activedChild.offsetLeft;`
`  }`

**Comment by narendrasinghrathore** [comment]
It's working with new update of ionic framework
You can review the [html](https://github.com/narendrasinghrathore/todo_app_ionic/blob/master/src/app/calendar/component/week/week.component.html) [ts](https://github.com/narendrasinghrathore/todo_app_ionic/blob/master/src/app/calendar/component/week/week.component.ts) file

For full code check the repository [here ](https://github.com/narendrasinghrathore/todo_app_ionic)
