### ISSUE TITLE
ion-loading-controller TypeError: Cannot read property 'componentOnReady' of null

### ISSUE THREAD

**Issue by barocsi** [ionic-team/ionic#17969]
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.13.1
   @angular-devkit/schematics    : 7.3.1
   @angular/cli                  : 7.3.1
   @ionic/angular-toolkit        : 1.4.0

System:

   NodeJS : v8.11.1 
   npm    : 5.6.0

***

```
async function presentLoading() {
  const loadingController = document.querySelector('ion-loading-controller');
  await loadingController.componentOnReady();

  const loadingElement = await loadingController.create({
    message: 'Please wait...',
    spinner: 'crescent',
    duration: 2000
  });
  return await loadingElement.present();
}
```
Please clarify why is this call is overcomplicated?
Why can't async nature be optional of such calls?
Where should 'ion-loading-controller' be defined? 
It's used to be dependency injected, if not, 
```const loadingController = document.querySelector('ion-loading-controller');``` gives undefined

Any ideas?

**Comment by liamdebeasi** [comment]
Hi there,

If you are using Angular, you should be following the Angular-specific instructions for `ion-loading`: https://ionicframework.com/docs/api/loading#usage

The usage you included above is for a vanilla JS project. Please give the Angular usage a try and let me know if you are still running into issues.

Thanks!
