### ISSUE TITLE
feat: Open/begin refresher programmatically

### ISSUE THREAD

**Issue by untilbit** [ionic-team/ionic#17972]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

We need a method to open ion-refresher programatically. This is a very useful feature we need to migrate our Ionic 3 app to Ionic 4.

**Describe Preferred Solution**

Method to open ion-refresher.

**Comment by liamdebeasi** [comment]
Hi there,

I am going to close this as a duplicate of #16542.

Thanks for using Ionic!
