### ISSUE TITLE
bug: ion-button MD hover too transparent

### ISSUE THREAD

**Issue by btsiders** [ionic-team/ionic#17974]
# Bug Report

**Ionic version:**

[x] **4.2.1**

**Current behavior:**

When hovering over `ion-button`s that are clear or outlined, the button always looks very light and washed out, way more than expected.

**Expected behavior:**

The color should be easier to see.

**Steps to reproduce:**

1. Put a button on a page.
2. Set its fill to outline or clear.
3. Hover over it.
4. The hover color should be about a 40% transparency, but it is a 4% transparency.

**Related code:**

```
<ion-button fill="clear">Hover over me</ion-button>
<ion-button fill="outline">Hover over me</ion-button>
```

**Other information:**

I will submit a PR to fix this. It just seems to be a typo, really.

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\Bryan\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.3.7
   @angular/cli                  : 7.3.7
   @ionic/angular-toolkit        : 1.5.0

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by brandyscarney** [comment]
Thanks for the issue! The opacity of `0.04` follows the Material Design spec and the Material Web Implementation of the button found here: https://material-components.github.io/material-components-web-catalog/#/component/button

<img width="374" alt="Screen Shot 2019-04-05 at 5 18 19 PM" src="https://user-images.githubusercontent.com/6577830/55657027-f362f280-57c6-11e9-92f3-5d589fc085cb.png">
<img width="356" alt="Screen Shot 2019-04-05 at 5 18 22 PM" src="https://user-images.githubusercontent.com/6577830/55657029-f3fb8900-57c6-11e9-9840-23a3ab4c906a.png">
<img width="383" alt="Screen Shot 2019-04-05 at 5 18 35 PM" src="https://user-images.githubusercontent.com/6577830/55657030-f3fb8900-57c6-11e9-85e9-a13cb03d60b6.png">
<img width="355" alt="Screen Shot 2019-04-05 at 5 18 39 PM" src="https://user-images.githubusercontent.com/6577830/55657031-f3fb8900-57c6-11e9-8a10-f6796b673621.png">

I can't find anywhere in the spec that uses `.4` as the opacity, and it looks a bit too dark here:

<img width="383" alt="Screen Shot 2019-04-05 at 5 19 34 PM" src="https://user-images.githubusercontent.com/6577830/55657067-11c8ee00-57c7-11e9-996b-fbb633357d01.png">

Are you seeing this opacity somewhere?

**Comment by btsiders** [comment]
Sorry. I just assumed 4% was a typo since it seems extremely light in the specific case I'm looking at, so then I also assumed it should have been 40% instead. It looks like 4% is more right in most cases, but this number really needs to be variable. 4% is the default starting opacity in their examples, but sometimes the number needs to be different.

From https://material.io/design/interaction/states.html#hover:
> The opacity value of the overlay should be adjusted for each different combination of text on surface in order to ensure proper visibility and color contrast accessibility. Hover overlays should be at lower opacities to avoid distracting from content.

![overlays-hover](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F0B9msDEx00QXmaXVISkJtS0dlSlU%2Foverlays-hover.png)

Specifically, I'm looking at buttons with `color="medium"` set. I use a custom color scheme but haven't changed the medium colors yet.

```
  /** medium **/
  --ion-color-medium: #989aa2;
  --ion-color-medium-rgb: 152, 154, 162;
  --ion-color-medium-contrast: #ffffff;
  --ion-color-medium-contrast-rgb: 255, 255, 255;
  --ion-color-medium-shade: #86888f;
  --ion-color-medium-tint: #a2a4ab;
```

The hover in this case is very difficult to see.

![2019-04-08](https://user-images.githubusercontent.com/715672/55735465-5d5de080-59ef-11e9-8fbc-872c3dc5f29a.png)

I would propose that a new CSS variable be added so that we can override the hover overlay.

In the mean time, for my specific case, I can also discontinue using the medium color for lightened buttons. I can probably work around this by using the "dark" color and setting overall button opacity.

**Comment by brandyscarney** [comment]
I have added the `--background-hover` and `--color-hover` variables to button. You will be able to now write the following in the `4.5.0` release:

```html
<ion-button fill="clear" class="medium">custom medium</ion-button>
```

```css
.medium {
  --color: #989aa2;
  --background-hover: rgba(152, 154, 162, 0.4);
}
```

Note that this will not override buttons that use the `color` property. The reason for this is the following could be written to change all of the default buttons:

```
ion-button {
  --color: #989aa2;
  --background-hover: rgba(152, 154, 162, 0.4);
}
```

And this would apply to all buttons *except* those with color.

**Comment by btsiders** [comment]
Looks great! Thanks!
