### ISSUE TITLE
ionic component(s) styling not working  when shared ionic v4.x

### ISSUE THREAD

**Issue by narendrasinghrathore** [ionic-team/ionic#17982]
If we are creating a  component in shared module and using in other feature module component(s) then, it miss the styling part also doesn't function as expected.

1) ion-fab-button in home component module.
![ion-fab-button-home](https://user-images.githubusercontent.com/4208015/55664651-fbff0b80-584e-11e9-9133-9e487dffc55e.gif)

```
<app-header title="Home" [online]="appState | async"></app-header>
<ion-content>
    <ion-fab vertical="bottom" horizontal="end" slot="fixed">
        <ion-fab-button color="secondary">
          <ion-icon color="light" name="add" (click)="addTodo()"></ion-icon>
        </ion-fab-button>
      </ion-fab>
  <!-- <app-add-todo-container></app-add-todo-container> -->
  <ng-container *ngIf="todoList$ | async as list else loading">
    <app-todo-list [list]="list"></app-todo-list>
  </ng-container>
  <ng-template #loading>
    <app-loading>
    </app-loading>
  </ng-template>
</ion-content>
```

2) same ion-fab-button in shared module component that's been called from our home module component.
![ion-fab-button-shared](https://user-images.githubusercontent.com/4208015/55664676-8182bb80-584f-11e9-9ac4-947dadefabe7.gif)

```
<app-header title="Home" [online]="appState | async"></app-header>
<ion-content>
    <!--<ion-fab vertical="bottom" horizontal="end" slot="fixed">
        <ion-fab-button color="secondary">
          <ion-icon color="light" name="add" (click)="addTodo()"></ion-icon>
        </ion-fab-button>
      </ion-fab>-->
   <app-add-todo-container></app-add-todo-container>
  <ng-container *ngIf="todoList$ | async as list else loading">
    <app-todo-list [list]="list"></app-todo-list>
  </ng-container>
  <ng-template #loading>
    <app-loading>
    </app-loading>
  </ng-template>
</ion-content>
```

Home component
1) [Template](https://github.com/narendrasinghrathore/todo_app_ionic/blob/master/src/app/home/home.page.html)
2) [Component](https://github.com/narendrasinghrathore/todo_app_ionic/blob/master/src/app/home/home.page.ts)
3) [Module](https://github.com/narendrasinghrathore/todo_app_ionic/blob/master/src/app/home/home.module.ts)

Shared component
1) [Template](https://github.com/narendrasinghrathore/todo_app_ionic/blob/master/src/app/shared/container/add-todo-container/add-todo-container.component.html)
2) [Component ](https://github.com/narendrasinghrathore/todo_app_ionic/blob/master/src/app/shared/container/add-todo-container/add-todo-container.component.ts)
3) [Module](https://github.com/narendrasinghrathore/todo_app_ionic/blob/master/src/app/shared/shared.module.ts)

![ion-fab-button-shared-2](https://user-images.githubusercontent.com/4208015/55696774-203c2300-59dc-11e9-8497-d15c60e1da03.gif)

**Comment by brandyscarney** [comment]
Thanks for the issue! This is happening because your component that is including fab is a shadow component. The colors are in a global stylesheet and they are not able to be passed through to the fab component. You can see more information on this in the comment here: https://github.com/ionic-team/ionic/issues/14840#issuecomment-439365125

Unfortunately we don't have a way to fix this yet, but we have been experimenting with constructable stylesheets which would solve this.

**Comment by narendrasinghrathore** [comment]
@brandyscarney 
v6.1.0 onward in angular

> **ViewEncapsulation.Native  is deprecated.**

![image](https://user-images.githubusercontent.com/4208015/56009982-6c020b80-5cff-11e9-91e3-8c4d6abd66e4.png)
 
**Currently using scss of component itself that host fab-button to apply ### styling.**

![image](https://user-images.githubusercontent.com/4208015/56010168-3ad60b00-5d00-11e9-80ef-b40a9a72f07a.png)



> **Snapshot of ionic app**

![ion-fab-button-shared-3](https://user-images.githubusercontent.com/4208015/56010326-e1baa700-5d00-11e9-8500-88ffed5f3a57.gif)

**Comment by brandyscarney** [comment]
Yes, there is also ViewEncapsulation `None` and `Emulated`: https://angular.io/api/core/ViewEncapsulation

This should only affect using `color` on an Ionic component inside of a Shadow root.

**Comment by narendrasinghrathore** [comment]
@brandyscarney  any update, is it being patched in new releases ?
