### ISSUE TITLE
bug: Changing skeleton-text color variables doesn't change the skeleton-text (animation) color.

### ISSUE THREAD

**Issue by dtaalbers** [ionic-team/ionic#17983]
# Bug Report

**Ionic version:**

[x] **4.2.0**

**Current behavior:**
Colors don't change when changing css variables

**Expected behavior:**
See some color change when changing the css variables

**Steps to reproduce:**

1) Change the background to a dark color
2) Add the `ion-skeleton-text` component to the page
3) Change the variables provided by the [docs](https://ionicframework.com/docs/api/skeleton-text#css-custom-properties).

**Related code:**

I've been trying to change the color of the animated `ion-skeleton-text` component to get some more contracts with my dark background. See below. It is hardly visible now.

<img width="379" alt="Screen Shot 2019-04-06 at 13 09 02" src="https://user-images.githubusercontent.com/6512556/55668843-69229900-586f-11e9-8fdc-2b2b2d318cf1.png">

```
ion-skeleton-text {
  --background: var(--ion-color-gray-100);
  --background-rgb: var(--ion-color-gray-100);
}
```

When I change the `--background` variable, nothing happens. When I change the `background-rgb` variable, the entire skeleton text disappears. 

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/Users/dtaalbers/.nvm/versions/node/v10.13.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.4.0

System:

   NodeJS : v10.13.0 (/Users/dtaalbers/.nvm/versions/node/v10.13.0/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by brandyscarney** [comment]
Thanks for the issue! What are you setting the `--ion-color-gray-100` variable to? Any variables ending in `-rgb` need to be in the following format: `255,255,255`. Here's an example: https://codepen.io/brandyscarney/pen/MRJqjJ

Maybe the problem is with the opacity of the animation?

**Comment by dtaalbers** [comment]
That was indeed the problem! Was setting the variable incorrectly. Thank you for your effort!
