### ISSUE TITLE
bug: Ionic-v4, usage of APP_INITIALIZER makes Ionic app to fail load modules: Error: Cannot find module './home/home.module'

### ISSUE THREAD

**Issue by imedvedev75** [ionic-team/ionic#17993]
Version: 4.12.0

1. create new Ionic app: ionic start test. Select Blank app.

2. Add APP_INITIALIZER. In app.module.ts add the following code:
-------
export class LoaderService {
  constructor() {   }
   public load(): Promise<any> {
      return new Promise((resolve, reject) => {
            console.log(`initializeApp:: inside promise`);
    }
}
function myInit(gl: LoaderService) {
  return () => gl.load();
};
-------

and in 'providers':
----
providers: [
    LoaderService,
    {
      provide: APP_INITIALIZER,
      useFactory: myInit,
      deps: [LoaderService],
      multi: true
    },
------

Compile and start, app fails with error:

ERROR Error: Uncaught (in promise): Error: Cannot find module './home/home.module'
Error: Cannot find module './home/home.module'
    at $_lazy_route_resource lazy namespace object:5
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.js:17299)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:390)

**Comment by REPTILEHAUS** [comment]
I think Im hitting something similar, any solutions ?

**Comment by imedvedev75** [comment]
no I dropped it.

Am So., 28. Apr. 2019 um 18:25 Uhr schrieb DAS REPTIL <
notifications@github.com>:

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
