### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by untilbit** [ionic-team/ionic#17991]
# Bug Report

[x] **4.x**

**Current behavior:**

When using the ion-spinner component in angular with a duration the animation of the spinner is very slow:
  `<ion-spinner duration="5000"></ion-spinner>`

If I pass the duration from a property it works well:
  `<ion-spinner [duration]="duration"></ion-spinner>`

**Expected behavior:**

It should work well in either case withoud a slow animation/rotation of the spinner.

**Steps to reproduce:**

**Related code:**

```
<ion-spinner duration="5000"></ion-spinner>

<ion-spinner [duration]="duration"></ion-spinner>
```

**Other information:**

**Ionic info:**

```
Ionic:
   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.2.0
```

**Comment by untilbit** [comment]
Tested in Firefox and Chrome.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. The `duration` prop is used to specify the duration of the spinner animation. So when you say that the animation is slow when providing a duration of "5000", that is expected behavior.

Additionally, I saw no difference in animation duration when using the two methods you showed:

```
public duration: number = 5000;

...

<ion-spinner duration="5000"></ion-spinner>
<ion-spinner [duration]="duration"></ion-spinner>
```

I am going close this, but feel free to follow up if you think this is still an issue. Thanks!

**Comment by untilbit** [comment]
I understand that the duration prop is used to specify the duration of the spinner animation.

This is the bug I'm reporting. When you specify the duration directly in the view, the spinner spins very slowly like below:

![Slow spinner](https://user-images.githubusercontent.com/12769948/55730666-fe14c600-5a18-11e9-9486-d3f85aded389.gif)

**Comment by liamdebeasi** [comment]
Hi there,

Can you clarify what you mean by "works properly" when binding the duration value in Angular? Is it just ignoring the duration value?

Thanks!

**Comment by untilbit** [comment]
> Hi there,
> 
> Can you clarify what you mean by "works properly" when binding the duration value in Angular? Is it just ignoring the duration value?
> 
> Thanks!


## Working properly
![spinner ok](https://user-images.githubusercontent.com/12769948/55862094-0b949200-5b78-11e9-9771-ace984d1fe21.gif)

##  NOT working properly
![spinner-slow](https://user-images.githubusercontent.com/12769948/55862131-223ae900-5b78-11e9-8bd9-e6e6e16a027b.gif)

**Comment by liamdebeasi** [comment]
Hi there,

When providing a duration to the spinner, the spinner is supposed to animate slowly (depending on what the value of `duration` is).

So when providing a value to `duration`, the following example is what you are supposed to see: 
![](https://user-images.githubusercontent.com/12769948/55862131-223ae900-5b78-11e9-8bd9-e6e6e16a027b.gif)

**Comment by untilbit** [comment]
Hi,

Understood now. It's not a bug. The name is confusing. I was thinking it was the time before it's hidden.

This issue can remain closed
