### ISSUE TITLE
bug: iOS keyboard hide after few seconds of focus in input

### ISSUE THREAD

**Issue by emidev98** [ionic-team/ionic#18000]
# Bug Report

**Ionic version:**

Ionic:
   ionic (Ionic CLI)                           : 4.12.0
   Ionic Framework                         : @ionic/angular 4.1.1
   @angular-devkit/build-angular  : 0.12.4
   @angular-devkit/schematics      : 7.2.4
   @angular/cli                               : 7.2.4
   @ionic/angular-toolkit               : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms       : android 8.0.0, ios 5.0.0
   Cordova Plugins          :  cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
                                          cordova-plugin-android-permissions 1.0.0 "Permissions"
                                          cordova-plugin-console 1.1.0 "Console"
                                          cordova-plugin-device 2.0.2 "Device"
                                          cordova-plugin-file 6.0.1 "File"
                                          cordova-plugin-file-opener2 2.2.0 "File Opener2"
                                          cordova-plugin-file-transfer 1.7.1 "File Transfer"
                                          cordova-plugin-fingerprint-aio 1.6.0 "FingerprintAllInOne"
                                          cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
                                          cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
                                          cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"
                                          cordova-plugin-printer 0.8.0 "Printer"
                                          cordova-plugin-secure-storage 3.0.1 "SecureStorage"
                                          cordova-plugin-splashscreen 5.0.2 "Splashscreen"
                                          cordova-plugin-statusbar 2.4.2 "StatusBar"
                                          cordova-plugin-whitelist 1.3.3 "Whitelist" 
 
System:

   Android SDK Tools : 26.1.1 
   ios-deploy              : 1.9.4
   ios-sim                    : 7.0.0
   NodeJS                   : v11.3.0
   npm                        : 6.4.1
   OS                           : macOS High Sierra
   Xcode                     : Xcode 10.0 Build version 10A255 

**Current behavior:**
This issue is only reproducible in iOS, so Android platform works correctly. When I tap the input as expected behavior the Keyboard slide up from the bottom of the screen. The issue appears few seconds after because **input lose the focus and Keyboard hides without me touching anything**. But if I tap the input and after I scroll down the Keyboard did not hide.

**Expected behavior:**
The Keyboard should not hide after few seconds, because there is no other event of change focus or stop focus.

**Steps to reproduce:**
1. Simulate the ionic project in iOS simulator (or build the Ionic app and send to iPhone)
2. Tap the input and do not touch anything more.

Thanks so much

**Comment by RHinderiks** [comment]
Are you able to reproduce this with a new/clean app? 

ps: Your ionic is not entirely up-to-date, i don't think this will fix your issue but it's never a bad idea to be up-to-date

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by RHinderiks** [comment]
I've fixed it exactly, running to the process to create a pull request right now (first time so may take a while)

**Comment by emidev98** [comment]
Dear Support,

I'm sorry I can't provide the code, but i'll update Ionic and notify you if it makes some changes. If it does not make any change i'll try creating a new app.

Thanks

**Comment by emidev98** [comment]
Dear comunity,

The bug where created by [re-capcha](https://github.com/DethAriel/ng-recaptcha). Because we instanced this component before use it, and this component creates a iframe which makes us lose the focus of inputs and hide the keyboard only in iOS.

**The solution were** to instance the component only when need to use the capcha and not before. Once the capcha is completed should destroy the component to do not let any subscription without control.

I hope this help someone.

**Comment by liamdebeasi** [comment]
Glad to hear this issue was resolved. Going to close this as it is not an Ionic issue.

Thanks for using Ionic!
