### ISSUE TITLE
bug: angular app targeting es2015 gets @ionic/core for es2017

### ISSUE THREAD

**Issue by ippeiukai** [ionic-team/ionic#18001]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When app is targeting `"target": "es2015"`, `@ionic/core` is loaded from `dist/esm/es2017/index.js` for which browsers with only es2015 support throws a SyntaxError.

For instance, Crosswalk 23, which we still use for supporting old Android devices, is Chromium 53 equivalent and es2015 is supported but not es2017.

**Expected behavior:**

Targeting `"target": "es2015"` in tsconfig.json is safe when the app needs to run on browsers that only support es2015.

**Steps to reproduce:**

Specify `"target": "es2015"` in tsconfig.json of any ionic/angular app, run it on Chromium 53.

**Related code:**

https://github.com/ionic-team/ionic/blame/046ca8f732dd72828ffe237ebdf54bcb580b5363/core/package.json#L21

**Other information:**

The error is:

> `Uncaught SyntaxError: Unexpected token (`

It was thrown from `vendor.js` on the line where webpack has placed `./node_modules/@ionic/core/dist/esm/es2017/ionic.core.js`.

It includes async/await syntax which is not part of es2015.

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.3.6
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.4, browser 6.0.0, ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic 4.1.7, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 22 other plugins)

System:

   Android SDK Tools : 26.0.2 (/■■■■■■■■/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 7.0.0
   NodeJS            : v8.9.1 (/■■■■■■■■/node/v8.9.1/bin/node)
   npm               : 6.8.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you post your `tsconfig.json` file?

Thanks!

**Comment by ippeiukai** [comment]
@liamdebeasi 
https://github.com/ippeiukai/ionic-issue18020/blob/issue-18001/tsconfig.json#L13

![Screenshot 2019-04-16 23 47 23](https://user-images.githubusercontent.com/1222990/56219928-8858cc00-60a2-11e9-89f3-9f3e11e3440b.png)

**Comment by liamdebeasi** [comment]
Hi @ippeiukai,

Can you try targeting `es5` instead of `es2015`? Any browser that supports `es2015` also supports `es5`.

Thanks!

**Comment by ippeiukai** [comment]
Yes, we did just use `es5` indeed, so no worries about workaround. It was just unexpected and we thought better report it.

**Comment by liamdebeasi** [comment]
Ok glad everything is working for you. I spoke with the team and it looks like this change is intentional, so I am going to close this issue.

Thanks! 🙂

**Comment by ippeiukai** [comment]
> I spoke with the team, and it looks like this change is intentional, so I am going to close this issue.

If intentional, shouldn’t it be documented somewhere?
It would be helpful to know the reasoning behind as well.
