### ISSUE TITLE
bug: ion-datetime not setting minutes properly

### ISSUE THREAD

**Issue by andremarchezini** [ionic-team/ionic#18012]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
If value is set to a full hour e.g. 07:00 the component sets the hour properly but the minutes get set to the current minute

**Expected behavior:**
Set minutes to 00

**Steps to reproduce:**

**Related code:**

    <ion-datetime display-format="hh:mm A" pickerFormat="h mm a" class="standard-input" [(ngModel)]="time"></ion-datetime>

  public time = '07:00'

**Ionic info:**
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\Andre\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.13.7
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.7
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.0.2 (E:\SDK)
   NodeJS            : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10

**Comment by andremarchezini** [comment]
same happens to simulator on https://ionicframework.com/docs/api/datetime
If you set it to a full hour the minutes do not get set properly

**Comment by immament** [comment]
The same with hour in format "HH:mm". Hour 00 is replaced to current hour.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Please update to Ionic 4.2 and let me know if you are still experiencing this issue. We shipped several datetime improvements with that update.

Thanks!

**Comment by immament** [comment]
After update to @ionic/angular@4.2.0 issue is solved.  
Thanks
