### ISSUE TITLE
bug: reorderArray is not exported

### ISSUE THREAD

**Issue by jasonwirth** [ionic-team/ionic#18016]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

`reorderArray` utility function isn't exported.

On a side note, in this file the enum has a typo... `const enum ReordeGroupState {...` Should probably be `ReorderGroupState`

**Expected behavior:**

export the function

**Steps to reproduce:**

[Github Source](https://github.com/ionic-team/ionic/blob/352797e93295a228e3033bcb370e253b641efac8/core/src/components/reorder-group/reorder-group.tsx)

**Related code:**

In Ionic-v3 the function was exportable: 

```
import { reorderArray } from 'ionic-angular';
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

System:

   NodeJS : v11.13.0 (/usr/bin/node)
   npm    : 6.9.0
   OS     : Linux 4.4

```

**Comment by liamdebeasi** [comment]
Hi there,

As per the [ion-reorder-group Documentation](https://ionicframework.com/docs/api/reorder-group) you can provide your array to the `complete` method and it will return the array re-ordered:

```
this.dataList = reorderGroup.complete(this.dataList);
```

I think the vanilla JS example with 
```
this.dataList = reorderArray(this.dataList, ev.detail.from, ev.detail.to);
ev.detail.complete();
```

either is outdated or (confusingly) implies that you already had a `reorderArray` function. Does this resolve your issue?

Thanks!
