### ISSUE TITLE
feat: add variable for translucent ion-tab-bar alpha value

### ISSUE THREAD

**Issue by RafaelKr** [ionic-team/ionic#18014]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Hi folks, I would like to have a variable for the alpha value of the `tab-bar-translucent` class of ion-tab-bar.

**Describe Preferred Solution**
If you want I can do a PR for that. But I need some more info if this would be the way to go:
- https://github.com/ionic-team/ionic/blob/374bd77219c6f47085a8d044132fa839e62a536d/core/src/components/tab-bar/tab-bar.ios.vars.scss#L8
Change to `$tab-bar-ios-translucent-background-color-alpha:    var(--translucent-background-color-alpha,.8) !default;`
- I think this is unused and can be removed: https://github.com/ionic-team/ionic/blob/374bd77219c6f47085a8d044132fa839e62a536d/core/src/components/tab-bar/tab-bar.ios.vars.scss#L11
- For Android is no translucent styling added, is this intentional? Or should I also add that styling for md?
- Can you point me to the place where I can update the docs? I couldn't quickly find it right now. (Would it maybe be possible to add an edit button to each docs page?)

**Comment by liamdebeasi** [comment]
Hey there,

Thanks for the feature request. What would be the benefit of just adding a variable to control the alpha levels? For the translucent tabbar, it's represented as `rgba` so why not just override the `background-color` value entirely?

**Comment by RafaelKr** [comment]
Yes, that's probably better.
What about the other points?

**Comment by liamdebeasi** [comment]
Hi there,

Can you clarify what you mean by "other points"?

Thanks!

**Comment by RafaelKr** [comment]
The other points I asked for:
- For Android is no translucent styling added, is this intentional? Or should I also add that styling for md?
- Can you point me to the place where I can update the docs? I couldn't quickly find it right now. (Would it maybe be possible to add an edit button to each docs page?)

**Comment by liamdebeasi** [comment]
Ah right, sorry - misunderstood what you meant.

The translucent tabbar is meant for iOS. We intentionally did not add translucent styles to the tabbar on Android because the MD spec does not call for it.

The documentation for each component can be found as a `README` file in each component directory. For example, here is the tabbar documentation: https://github.com/ionic-team/ionic/blob/master/core/src/components/tab-bar/readme.md

**Comment by RafaelKr** [comment]
Awesome, thank you! I will add a PR for that within the next days.

I think it would be best to add the following variables:
```
--ios-translucent-background-color
--md-translucent-background-color
```

So on Android it isn't translucent when translucent prop is true, but we have the possibility to customize this. I would also add this to the description of the translucent prop. What do you think?

**Comment by liamdebeasi** [comment]
Hi there,

We already expose a `--background` variable for the tabbar component. Why not just use that?

**Comment by RafaelKr** [comment]
That's even better. I didn't think of this yet. I can close this now.

### Solution for the Community
You could use the following in a global scss file. I'm using my variables.scss file for that.
```
html {
	&.ios {
		--tab-bar-translucent-background: rgba(var(--ion-color-dark-rgb), 0.5)
	}

	&.md {
		--tab-bar-translucent-background: rgba(var(--ion-color-primary-rgb), 0.5)
	}
}
```

And then in the component scss with the tabbar:
```
ion-tab-bar.tab-bar-translucent {
	background: var(--tab-bar-translucent-background);
}
```
