### ISSUE TITLE
bug: Angular not picking up changes in alert handler with timeout

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic#18025]
# Bug Report

Originally reported here: https://github.com/ionic-team/ionic/issues/17371#issuecomment-482590873 Thanks, @martijnlutgens!

**Ionic version:**

[x] **4.x**

**Current behavior:**

When mutating data in the handler of an alert button using a timeout, Angular is not picking up the changes and running change detection accordingly. Mutating the data in the handler without a timeout works fine.

**Expected behavior:**
I would expect that Angular change detection is run when mutating the data and the view is updated.

**Steps to reproduce:**

Example repo: https://github.com/martijnlutgens/ionicListRemoveItem/

This works:
```
...
handler: () => {
  this.itemlist.splice(this.itemlist.length-1, 1);
  this.itemlist = [...this.itemlist];
}
...
```

This does **_not_** work:

```
handler: () => {
  setTimeout(() => {
    this.itemlist.splice(this.itemlist.length-1, 1);
    this.itemlist = [...this.itemlist];
  }, 500);
});
```

**Related code:**

As a temporary workaround, users can wrap their code in the handler as an `NgZone.run` callback:

```
this.zone.run(() => {
  setTimeout(() => {
    this.itemlist.splice(this.itemlist.length-1, 1);
    this.itemlist = [...this.itemlist];
  }, 500);
});
```

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.11.0 (/Users/liamdebeasi/.nvm/versions/node/v10.15.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

System:

   NodeJS : v10.15.0 (/Users/liamdebeasi/.nvm/versions/node/v10.15.0/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by JiaLiPassion** [comment]
@liamdebeasi, I am using the `reproduce repo`, but I can't reproduce this issue, the `setTimeout` is running in `ngZone` without `zone.run`.

**Comment by liamdebeasi** [comment]
@JiaLiPassion,

Thanks for taking a look at this! I just double checked, and I am still seeing the issue.

From what I understand, clicking "Add Item" works fine, but clicking "Delete Item" does not immediately delete an item. This is what I am seeing:

1. Add a few items
2. Click "Delete Item"
3. An alert will open asking to confirm deletion.
4. Click "Yes" in the alert
5. The alert will disappear, but the last item in the list will not disappear from the view until you click somewhere in the DOM.

I am seeing this happen in both the "normal" list and the Observable list. What is the behavior you are experiencing?

**Comment by JiaLiPassion** [comment]
@liamdebeasi, thanks for your response, I can reproduce now, sometimes it can refresh the items, sometimes it can not, could you tell me how I can run this `ionic project` so I can see the `source map` of `ionic.core.js`? I would like to debug into the `ionic code`, thanks!

**Comment by liamdebeasi** [comment]
Better source map handling is something we still need to improve when working with the Ionic Core, but if you want to debug the Angular-specific portion of an Ionic app, you should be able to just use the `fesm5.js` file that is created in the `@ionic/angular` in your node_modules.

**Comment by JiaLiPassion** [comment]
@liamdebeasi , thanks, I can debug into `fesm5.js`, but I really want is some code inside `node_modules/@ionic/core/dist/esm/es5/build/devt5yhg.entry.js`, is that possible you can just give me a `dev version` of those files under `@ionic/core`, so I can just replace them and be able to debug.

**Comment by liamdebeasi** [comment]
Hi there,

We currently do not have that (The work to do that is on the Stencil side, and it needs some more development time).

One alternative could be to clone the `ionic` repo and create a symlink between `@ionic/core` in your app and the `core` directory that you are developing. Then start a live-reload session that compiles down to es5 and debug that way.

Thanks!

**Comment by JiaLiPassion** [comment]
thanks, I think I may know the reason, the code here https://github.com/ionic-team/ionic/blob/master/core/src/components/app/app.tsx#L25, when will this `componentDidLoad` will be called? And will it be called inside `ngZone`?

**Comment by liamdebeasi** [comment]
Updated to 4.11.1 and am no longer able to reproduce this issue. For anyone who runs into this issue on 4.11.1+ feel free to open a new issue.
