### ISSUE TITLE
feat: ion-col sizes should take menu width(s) into account

### ISSUE THREAD

**Issue by joelmeaders** [ionic-team/ionic#18030]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
ion-col sizing appears to take the full screen width into account, but not active menus. I have a view with a left and a right menu (within an ion-split-pane) and on desktop I can't get good column widths with certain screen sizes where both menus are active. Max-width on the menus is set to 330px each in my setup.

**Describe Preferred Solution**
Add a property to subtract the column widths from the screen-size used for calculations. For Instance:
`<ion-grid screenSizeDeduction="-660px">`
or...
`<ion-grid deductActiveMenus="true">`

**Related Code**
None

**Additional Context**
None

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the feature request! Can you give us an example of your current use case?

**Comment by joelmeaders** [comment]
Thanks for the response. I'll put together a code example with screenshots tonight.
