### ISSUE TITLE
bug: popover ion-select control states aren't changing properly on "md" platform

### ISSUE THREAD

**Issue by ghost** [ionic-team/ionic#18049]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When an ion-select with interface="popover" or interface="action-sheet" is visited and nothing was chosen from options and the field is required, then it is not showing the error message as soon as ion-select is dismissed, requires one more click (anywhere) for the error to be visible, works fine on "ios" platform but not on "md". **Basically, as soon as backdrop is clicked on "md" platform, control states (ion-valid, ion-touched, ion-pristine etc.) aren't changing when the dropdown is dismissed. It changes after an additional click.**

**Expected behavior:**

As soon as dropdown backdrop is clicked without any option selected, it should dismiss dropdown and change control states without requiring an additional click.

**Steps to reproduce:**

1. Implement ion-select without ion-item. (it was necessary for our design)
2. add an attribute interface="popover" or "action-sheet".
3. write eror msg to be visible in case nothing was selected from options.

**Related code:**

```
<ion-col>
<ion-select no-padding interface="popover" [interfaceOptions]="InterfaceOpt" placeholder="Select One" formControlName="dummy" class="input-border p-3">
   <ion-select-option value="one">One</ion-select-option>
   <ion-select-option value="two">Two</ion-select-option>
   <ion-select-option value="three">Three</ion-select-option>
</ion-select>
<p [hidden]="dummyForm.controls['dummy'].valid || !dummyForm.controls['dummy'].touched" class="validator-error">
Please select one
</p>
</ion-col>
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.0 (C:\Users\Pixelbrook\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (C:\Users\Pixelbrook\AppData\Local\Android\Sdk)
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.7.0
   OS                : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
