### ISSUE TITLE
feat:  a real retina line and screen adaptation

### ISSUE THREAD

**Issue by coldpc** [ionic-team/ionic#18046]
# Feature Request
I am wondering why our 1px is so thick.This is too thick to be visually pleasing, so we can use the viewport scale and turn 1px into a real retina line.Then all of our layouts use rem, which ADAPTS to the screen very easily.
I believe this change does not require much adjustment, but the feeling is huge.
**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

**Comment by liamdebeasi** [comment]
Thanks for the feature request. Can you please clarify what your request is? Rendering of all CSS is handled by the browser, so that is not something Ionic Framework has control over.
