### ISSUE TITLE
feat: Strongly typed Ionic life cycle hooks for ionic/angular

### ISSUE THREAD

**Issue by HaidarZ** [ionic-team/ionic#18043]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Make the ionic life cycle hooks strongly typed to act the same way as the angular life cycle hooks.
It adds the advantage of being less error-prone, readable, IDE friendly... 
I didn't like the idea of the function being grayed out as if it's not used 😋 

**Describe Preferred Solution**

Export interfaces that must be implemented when a life cycle hook is required
```
export interface ViewWillEnter {
    /**
     * Fired when the component being routed to is about to animate in.
     */
    ionViewWillEnter(): void;
}
export interface ViewDidEnter {
    /**
     * Fired when the component being routed to has animated in.
     */
    ionViewDidEnter(): void;
}
export interface ViewWillLeave {
    /**
     * Fired when the component being routed from is about to animate.
     */
    ionViewWillLeave(): void;
}
export interface ViewDidLeave {
    /**
     * Fired when the component being routed from has animated.
     */
    ionViewDidLeave(): void;
}

```

**Comment by steebchen** [comment]
What's preventing #18044 from being merged? This is an important change because you currently don't have any type safety for lifecycle hooks.
