### ISSUE TITLE
bug: IOS 12.2/12.3 - Text field in an iframe not focusing on tap

### ISSUE THREAD

**Issue by TarekSalahUddinMahmud** [ionic-team/ionic#18050]
I am facing an issue on focusing an input field under an iframe. It only focuses when I long press on an input field. Here is the [link of the video](https://youtu.be/SxjlstB6YWc)
[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/SxjlstB6YWc/0.jpg)](http://www.youtube.com/watch?v=SxjlstB6YWc)

the src I am using in the iframe is [https://checkout.paystand.co/v4/?publishableKey=ioond5qdfwarj1f24f8ss3x6](https://checkout.paystand.co/v4/?publishableKey=ioond5qdfwarj1f24f8ss3x6)

I have updated my iPhone 7 plus from 11.3 to 12.2. After updating I am facing this problem. I have updated my cordova-plugin-ionic-webview version 3.1.2 to 4.0.1. But the problem persists. This problem also occurs on iPhone 6s v12.3. We are currently using cordova-plugin-ionic-keyboard v2.1.3. We upgraded it from ionic-plugin-keyboard v2.2.1.

Previously I faced the same issue when I updated my phone to 11.3. I was using ionic-plugin-webview at that time. Moving to cordova-plugin-ionic-webview version 3.1.2 solved the problem at that time.

Here is my Ionic info:
Ionic:

   ionic (Ionic CLI)  : 4.0.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61

Environment:

   ANDROID_HOME : /Users/bs221/Library/Android/sdk

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Is this issue you are describing happening when running as a standalone app, or is it also happening when you run the app in Safari? I tried the link above on mobile Safari and everything seemed to work fine.

If the issue is happening only when running as a standalone app, can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by TarekSalahUddinMahmud** [comment]
This is happening when I use paystand in the ios app.

The public repository link is [https://github.com/TarekSalahUddinMahmud/webviewTest](https://github.com/TarekSalahUddinMahmud/webviewTest). Hope you can reproduce this issue here.

**Comment by liamdebeasi** [comment]
Hi there,

Apologies, I did not realize this was an Ionic 3 application. This issue tracker is only for Ionic 4 issues. I will move this issue to the correct repository.

Thanks!
