### ISSUE TITLE
bug: ion-searchbar does not get focus in iOS 12.2

### ISSUE THREAD

**Issue by carlesferreiro** [ionic-team/ionic#18054]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When trying to focus ion-searchbar in ionViewDidEnter nothing happens.
Then, if you switch to another app and then return to the ionic app, the searchbar gets focused and the keyboard is shown.
In iOS 12.1 the same code works fine.

**Expected behavior:**
The searchbar should get focus immediately after calling .focus() and the keyboard should be displayed.

**Steps to reproduce:**
- Create ionic blank project
- Add ion-searchbar component in the toolbar
- Call .focus() function of the searchbar
- Test in iOS 12.2 safari app or iOS 12.2 with cordova and see that nothing happens
- If you switch to another app and then return to the ionic app, the searchbar gets focused and the keyboard is shown

**Related code:**

.html
```html
<ion-header>
  <ion-toolbar>
    <ion-title>
      Ionic Blank
    </ion-title>
    <ion-searchbar #searchInput></ion-searchbar>
  </ion-toolbar>
</ion-header>
```

.ts
```javascript
import { Component, OnInit, ViewChild } from '@angular/core';
...
@ViewChild('searchInput') searchInput;
...
ionViewDidEnter() {
  this.searchInput.setFocus();
}
```

**Comment by rossholdway** [comment]
@carlesferreiro I believe this is an issue with the webview, not Ionic itself. You should try updating to the latest Ionic webview. See https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/332

**Comment by carlesferreiro** [comment]
Thanks for the feedback @rossholdway, but I'm using the latest npm version already :(
I tried updating also the @ionic-native/ionic-webview but I got the same results

**Comment by hooliy** [comment]
this same issue in the Safari brower!

**Comment by masimplo** [comment]
Same issue on latest Ionic (4.11) and latest Capacitor (1.2.1) and latest iOS (13.1). If I add a timeout of 300-500ms the focus succeeds.

**Comment by ws1993** [comment]
> Same issue on latest Ionic (4.11) and latest Capacitor (1.2.1) and latest iOS (13.1). If I add a timeout of 300-500ms the focus succeeds.

it works for me! i test it in emulator of iphone 11(iOS 13.3), but i confused about why it works.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this an issue with the latest version of Ionic Framework? If so, can you provide a repo with the code required to reproduce the issue?
