### ISSUE TITLE
bug: iOS document picker not pulling the latest code from the repository

### ISSUE THREAD

**Issue by jasvindersingh-evon** [ionic-team/ionic#18057]
![Screen Shot 2019-04-12 at 11 43 16 AM](https://user-images.githubusercontent.com/10975369/56289106-d53db080-613d-11e9-9696-a1c03f7cb8c0.png)

# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Plugin **iOS DocumentPicker** is not pulling the latest code from the GitHub repo which is causing issues in compiling the code in Xcode 9.4.1 or in Xcode 10.2

**Expected behavior:**
While adding plugin, it should pull the latest code from the Github repo.

**Steps to reproduce:**
1. Create a new blank Ionic project 
2. Add the plugin using commands 
`ionic cordova plugin add cordova-plugin-documentpicker` and 
`npm install --save @ionic-native/document-picker@4`
3. Add the platform iOS using command 
`ionic cordova platform add ios`
4. If there is any error for '../cordova/platform_metadata' then remove the plugin 
`cordova plugin rm cordova-plugin-add-swift-support --force`
5. After removing add the plugin again using command
`cordova plugin add cordova-plugin-add-swift-support`
6. Build the project using command
`ionic cordova build ios`
7. Open the project in Xcode 9.4.1 or in Xcode 10.2, It selects the default swift compile version as 4.1. Now run command to build the project. Error is generated in `DocumentPicker.swift` file as displayed in attachment

**Other information:**
If the plugin is added directly as mentioned in the GitHub repository then the issue is not there as it pulls the latest code base.
Command to add plugin directly - `cordova plugin add https://github.com/iampossible/Cordova-DocPicker.git`

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/ankit/Library/Android/sdk)
   ios-deploy        : 2.0.0
   NodeJS            : v8.11.1 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000


```

**Comment by liamdebeasi** [comment]
Hi there,

I am going to close this as this is not an Ionic issue. Running `cordova plugin add [plugin name]` will pull the plugin from npm. It looks like the plugin author has not updated their npm listing with the latest version of the plugin:

GitHub: https://github.com/iampossible/Cordova-DocPicker
NPM: https://www.npmjs.com/package/cordova-plugin-documentpicker

If you want to pull the latest from the GitHub repo instead of npm run `cordova plugin add https://github.com/iampossible/Cordova-DocPicker.git`.

Thanks!
