### ISSUE TITLE
bug: Android : Object.values is not a function

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic#18053]
# Bug Report

**Ionic version:**
```
		"@ionic/core": "4.2.0",
		"@ionic/vue": "0.0.4",
```

**Current behavior:**
Keeps throwing error only for Android device. There have been 200 logs for this error. Note: this only occurs on android.

<img width="690" alt="Screenshot 2019-04-17 at 12 00 23 AM" src="https://user-images.githubusercontent.com/8480351/56234863-d3bfaa00-60a3-11e9-8005-4a73ad437a0e.png">

**Comment by stripathix** [comment]
<img width="689" alt="Screenshot 2019-04-17 at 12 02 13 AM" src="https://user-images.githubusercontent.com/8480351/56234986-11bcce00-60a4-11e9-832c-0e607554a76a.png">

**Comment by brandyscarney** [comment]
Please provide steps to reproduce or a repository with a minimal amount of code that we can use to reproduce the problem. It is hard to help with only error messages. Thank you!
