### ISSUE TITLE
bug: ion-title not vertical centered

### ISSUE THREAD

**Issue by jtushar53** [ionic-team/ionic#18076]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

ion-title is not vertically centered
**Expected behavior:**

ion-title should vertically centered

**Steps to reproduce:**

**Related code:**

```
<ion-header>
  <ion-toolbar color="primary">
    <ion-buttons slot="start">
      <ion-back-button></ion-back-button>
    </ion-buttons>
    <ion-title
      >Product Details
      <ion-buttons expand="block" float-right>
        <ion-icon size="large" class="button" name="search"></ion-icon>
      </ion-buttons>
    </ion-title>
  </ion-toolbar>
</ion-header>
```

**Other information:**

![image](https://user-images.githubusercontent.com/5780117/56393839-1ecbef80-6253-11e9-8452-c18b75e433a3.png)

**Ionic info:**

Using Ionic 4.1.0
```
Ionic:

   ionic (Ionic CLI) : 4.12.0

System:

   NodeJS : v10.15.0
   npm    : 6.4.1
   OS     : macOS Mojave

```

**Comment by 7freaks-otte** [comment]
Without testing I think this is due to your search button inserted within the `ion-title` tag which affects the actual height of the title.

Wouldn't the following code fix your problem?

```
<ion-header>
  <ion-toolbar color="primary">
    <ion-buttons slot="start">
      <ion-back-button></ion-back-button>
    </ion-buttons>
    <ion-title>Product Details</ion-title>
      <ion-buttons slot="end">
        <ion-button>
          <ion-icon name="search"></ion-icon>
        </ion-button>
      </ion-buttons>
  </ion-toolbar>
</ion-header>
```

**Comment by liamdebeasi** [comment]
Hi there,

What @7freaks-otte said is correct. You need to use a slotted `ion-buttons` that is a sibling of `ion-title`, not a child. I am going to close this as this is a support request. I attached a CodePen demonstrating your usage vs. the correct usage: https://codepen.io/liamdebeasi/pen/LvmOoj

For any follow up questions feel free to post on our [forum](http://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com).

Thanks for using Ionic!

**Comment by jtushar53** [comment]
Yes my bad, it fine now
