### ISSUE TITLE
bug: ion-reorder button not working at all

### ISSUE THREAD

**Issue by barocsi** [ionic-team/ionic#18086]
# Bug Report

**Ionic version:**

[x] **4.3.0**

**Current behavior:**
using the markup at
https://ionicframework.com/docs/api/reorder-group
1. the drag icon is displayed only when slot="start|end" is omitted
2. dragging the drag icon the ion-item is not dragged at all, no event fired

**Expected behavior:**

using the markup at
https://ionicframework.com/docs/api/reorder-group
1. the drag icon should be displayed
2. dragging the drag icon the item should be moving

**Comment by brandyscarney** [comment]
Thanks for the issue! The reorder gesture is disabled by default, you need to add the following:

```
<ion-reorder-group disabled="false">
```

I have a PR open to update the documentation here: https://github.com/ionic-team/ionic/pull/18084

Here's the updated README: https://github.com/ionic-team/ionic/blob/aa10cebfb85abf462ac8110ced98ec87ed68d9b5/core/src/components/reorder-group/readme.md#usage

Please let me know if that solves your problem!

**Comment by barocsi** [comment]
Works, thanks.
