### ISSUE TITLE
bug: ion-slides options for centeredSlides has no effect

### ISSUE THREAD

**Issue by jtth** [ionic-team/ionic#18081]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Ion slides, when passed options that include `centeredSlides: true`, does not actually use that option.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
https://github.com/jtth/ionic-slides-center

```
insert short code snippets here
```

**Other information:**

All the other options seem to be passed fine. Mike said in Slack it seems like that option in particular isn't being passed through, maybe?

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/Users/jtth/.nvm/versions/node/v10.13.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

System:

   NodeJS : v10.13.0 (/Users/jtth/.nvm/versions/node/v10.13.0/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave```

**Comment by brandyscarney** [comment]
Thanks for the issue! It seems like this only works when `slidesPerView` is set. Here's an example with the following option:

```
slidesPerView: 2
```

<img width="524" alt="Screen Shot 2019-04-19 at 2 23 47 PM" src="https://user-images.githubusercontent.com/6577830/56437830-df32f100-62ae-11e9-84b1-720650badc3e.png">

Then if I add in `centeredSlides` like this:

```
slidesPerView: 2,
centeredSlides: true
```

it changes to this:

<img width="521" alt="Screen Shot 2019-04-19 at 2 24 07 PM" src="https://user-images.githubusercontent.com/6577830/56437843-e9ed8600-62ae-11e9-8c9e-d2498e05e242.png">

Looking through the API documentation for swiper and the demos, it seems this is always used with more than 1 slide per view: 

https://idangero.us/swiper/demos/
https://github.com/nolimits4web/Swiper/blob/master/demos/130-centered.html

I don't think this is an issue with Ionic, but rather with how the variable should be used. Please let me know if I'm wrong though!

**Comment by jtth** [comment]
While this actually does solve my issue in my actual application, it doesn't seem to fix the demo I made, and it doesn't seem to work when you also specify `width` in the slide options, either in the demo I provided or in my application. Weird. Oh well. It works well enough now.

**Comment by mhartington** [comment]
@jtth verify first that the issues doesn't not exist upstream in swiper. This could be on their end.

**Comment by jtth** [comment]
I mean, no, it's working for me even if the component is still wonky. And it's not my component, it's Ionic's.
