### ISSUE TITLE
Set null to datetime value breaks

### ISSUE THREAD

**Issue by dkrahn** [ionic-team/ionic#18099]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Pass `null` value to `datetime` breaks component.

**Expected behavior:**
Be able to pass `null` to component without breaking it.

**Steps to reproduce:**
Add `<ion-datetime [value]="null"></ion-datetime>`, the console will show error, once opened, cannot close it.

**Related code:**
From what I can see the problem is in this point:
https://github.com/ionic-team/ionic/blob/a5b9066fee1a3cc01fc2aab524bb979fb0096de2/core/src/components/datetime/datetime-util.ts#L280-L285
The test `!newData` is true for null and undefined, but the method getLocalDateTime has a default value when `undefined` is passed, but not when null is.

**Other information:**
`<ion-datetime [value]="undefined"></ion-datetime>` works fine.

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (****\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (****\AppData\Local\Android\Sdk)
   NodeJS            : v8.11.4 (****\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! I've created a PR for it here: https://github.com/ionic-team/ionic/pull/18105

**Comment by liamdebeasi** [comment]
This issue has been fixed by https://github.com/ionic-team/ionic/pull/18105 and will be in the next release of Ionic.

Thanks for using Ionic!
