### ISSUE TITLE
bug: ion-footer overlap another. Same for ion-tab-bar

### ISSUE THREAD

**Issue by SerhiDi** [ionic-team/ionic#18103]
# Bug Report

**Ionic version:**

[x] **4.3.0**

**Steps to reproduce:**
Open next page in route. Back to the previous page in route. If you have `ion-footer` on previous and current pages you will have this bug. If the previous page with `ion-footer` and current page without - all correct, animation working fine.

I created a simple app with 4 pages (but this bug between two pages). Same layout and logic on each of these pages.
Simple page. Header (First page without `ion-back-button`). Content. Footer

**Related code:**

HTML
```
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button></ion-back-button>
    </ion-buttons>
    <ion-title>
      HEADER 2
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  CONTENT 2
</ion-content>

<ion-footer>
  <ion-button
    (click)="openTest3()">
    <ion-label>OPEN 3</ion-label>
  </ion-button>
</ion-footer>
```

TS
```
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  templateUrl: './test.component.html',
  styleUrls: ['./test.component.scss'],
})
export class Test2Component {

  constructor(private router: Router) {
  }

  openTest3() {
    this.router.navigateByUrl(`index/test3`);
  }

}
```

ROUTES
```
export const testRoutes: Routes = [
  {
    path: 'test',
    component: TestComponent,
  },
  {
    path: 'test2',
    component: Test2Component,
  },
  {
    path: 'test3',
    component: Test3Component,
  },
  {
    path: 'test4',
    component: Test4Component,
  }
];
```

https://gyazo.com/5241574a02561afb0709b8d2cc173621

Same issue with ion-tab-bar.

**Comment by SerhiDi** [comment]
With `ion-toolbar`
```
<ion-footer>
  <ion-toolbar>
    FOOTER
  </ion-toolbar>
</ion-footer>
```

https://gyazo.com/62eea20eec353c2e231225ca64ef2e4a

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
