### ISSUE TITLE
bug: App won't start using starter project

### ISSUE THREAD

**Issue by srnec** [ionic-team/ionic#18111]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
By using any starter project (e.g. `ionic start photo-gallery tabs --type=angular`), after building it and running it in browser, app wont' start successfully.

This issue is a blocker for projects that want to use Ionic v4 only as browser web apps (on desktop, or wrapped by Electron).

The issue is not seen during running the app via 'npm run start' (serve).

**Expected behavior:**
After setting up any starter project, building it and running `www/index.html` in the browser it should start the app without any issues.

**Steps to reproduce:**
1. Create a new project: e.g. `ionic start photo-gallery tabs --type=angular`
2. Execute `npm run build`
3. Open `www/index.html` in browser (Chrome)
4. Check console in browser:
```
runtime.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
polyfills.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
styles.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vendor.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
main.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/C:/assets/icon/favicon.png:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
```

**Other information:**
I know that several related issues were already created but this bug report is even simpler and more straightforward in comparison to others. This uses IONIC v4 only as front-end for a angular web app (no Android, no iOS, only browser). 
This can be reproduced also by removing any dependencies to native packages (`@ionic-native/*`) since for web app in browser they are not needed.
Based on the other related issues the resource loading issue can be fixed via changing base href in index.html: `<base href="." />` but this is not acceptable workaround since on one hand the app proceeds further but on the other hand stops on a new problem with routing.

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\XXX\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v8.11.4 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

**Comment by mhartington** [comment]
👋 Hey there! Are you just trying to open the index.html? If so, it sounds like this is happening.

- Opening index.html from `www/index.html` would actually conflict with the base-href, since it doesn't actually load the files correctly and treat the paths as being relative. Deploying to a production server the behaviour is correct, as seen [here](http://startrack-ng.firebaseapp.com/)

If you want to test the app locally before deploying to a server, you need to test it via a small web-server.
https://github.com/lwsjs/local-web-server

```bash
npm install -g local-web-server

ws --dir www --spa index.html
```
