### ISSUE TITLE
feat: ion-button border-radius for each corner

### ISSUE THREAD

**Issue by batesy87** [ionic-team/ionic#18120]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

It's not currently possible to define the border radius for each corner of a button and since it's shadowed it's not possible to override with CSS, it would be nice to have variables for each corner similar to how padding can be controlled on each side

**Describe Preferred Solution**
Allow more control like padding
e.g. --border-radius-top-left, --border-radius-top-right, --border-radius-bottom-right and --border-radius-bottom-left

**Comment by brandyscarney** [comment]
Thanks for the issue! The border radius can be overridden using the `--border-radius` CSS variable. This accepts the same values as the CSS `border-radius` property: https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius

If you're looking to have more control you can always create your own CSS variables:

```
.custom {
  --border-top-left-radius: 10%;
  --border-top-right-radius: 30%;
  --border-bottom-left-radius: 50%;
  --border-bottom-right-radius: 70%;
  
  --border-radius: 
    var(--border-top-left-radius) 
    var(--border-top-right-radius) 
    var(--border-bottom-right-radius)
    var(--border-bottom-left-radius);
}
```

Here's a Codepen example: https://codepen.io/brandyscarney/pen/ZZqZVd
