### ISSUE TITLE
bug: the toast `translucent` property has no effect

### ISSUE THREAD

**Issue by pastcompute** [ionic-team/ionic#18129]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
If I set the `translucent` property for a toast, there is no visual difference

**Expected behavior:**
I would assume that the background should be transparent somehow and I can see what is underneath it through

**Steps to reproduce:**
1. Create a new blank app
2. Add a toast controller to the main page, and show a toast in `ionViewDidEnter()` with a message, and the `translucent` property set to true
3. Put some other content in the page that would be obscured by the toast
3. Run `ionic serve` and observe that the toast is entirely opaque

**Related code:**

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v10.14.2 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! Which mode are you testing this on (Material Design or iOS)? The `translucent` styling only applies to iOS. The Material Design spec does not call for translucency like this.

Thanks!

**Comment by pastcompute** [comment]
OK, thanks. I've been using plain web browser, and Android. I guess that makes this a documentation bug, https://ionicframework.com/docs/api/toast makes no mention of this constraint.

**Comment by brandyscarney** [comment]
Thanks! I created a documentation issue for this: https://github.com/ionic-team/ionic-docs/issues/666
