### ISSUE TITLE
bug: ion-datetime - setting min value limits pickable days when trasitioning to another month

### ISSUE THREAD

**Issue by terranmarine** [ionic-team/ionic#18124]
# Bug Report

Setting `<ion-datetime>` `min` attribute results in limitation of available  days when the max value transitions in the next month.

**Ionic version:**
[x] **4.12**

**Current behavior:**
Available days are limited from `min` value  day to last day of the month.

**Expected behavior:**
Available days should include all days from `min` value day to last day of the month AND from first day of next month to `max` value day.

**Steps to reproduce:**
1. Add `<ion-datetime>` web component to any ionic project html view.
2. Set the `value` attribute to the last they of the current month.
3. Set the `min` attribute to 3 days before the date in `value` attribute.
4. Set the `max` attribute to 3 days after the date in `value` attribute.

**Related code:**
```
<ion-datetime min="2019-04-27T06:50:09.282Z" max="2019-05-03T06:50:09.282Z" value="2019-04-30T06:50:09.282Z"></ion-datetime>
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic 5.3.0, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 12 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 7.0.0
   NodeJS     : v11.12.0 (/usr/local/Cellar/node/11.12.0/bin/node)
   npm        : 6.7.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! Can you clarify the issue you are seeing? I am unable to reproduce it.

I would expect that I have a range of dates from 2019-04-27 to 2019-05-03 to choose from. I would also expect that the datetime component defaults to 2019-04-30. This is what I am seeing from my end:

![flKvP1yQnq](https://user-images.githubusercontent.com/2721089/56739872-be9ae900-673d-11e9-9d88-6fac1e3fffbf.gif)

Thanks!

**Comment by terranmarine** [comment]
Ahh, I thought the days are displayed universally for all months and I didn't even bother to switch the months.

Closing and sorry for wasting your time.
Have a great week.

Alex.
