### ISSUE TITLE
ion-virtual-scroll use ion-item-divider but cant sticky~

### ISSUE THREAD

**Issue by auron105** [ionic-team/ionic#18139]
# Bug Report

**Ionic version:**

[x] 4.3.0

**Current behavior:**

I tried the following code in docs:

<ion-virtual-scroll [items]="items" [headerFn]="myHeaderFn">
  <ion-item-divider *virtualHeader="let header">
    {{ header }}
  </ion-item-divider>
  <ion-item *virtualItem="let item">
    Item: {{ item }}
  </ion-item>
</ion-virtual-scroll>

but divider cant sticky ,
i try <ion-item-divider sticky  *virtualHeader="let header">
but not work ~!

**Expected behavior:**

Can make the sticky work?

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! Items in `ion-virtual-scroll` are given `position: absolute` values, which override the `position: sticky` value. `ion-virtual-scroll` currently relies on the assumption that all items have `position: absolute` set.

I am going to close this as this is not something we currently support. If you feel this functionality is important, please fill out [Feature Request](https://github.com/ionic-team/ionic/issues/new?assignees=&labels=&template=feature_request.md&title=feat%3A+), and we can take a look.

Thanks!
