### ISSUE TITLE
@ionic/react bug: With hooks pages are not unmounted

### ISSUE THREAD

**Issue by Kikketer** [ionic-team/ionic#18136]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When using React Hooks a secondary window is not unmounted and cleanup effects are not triggered.

**Expected behavior:**
After a secondary style window is hidden allow a hook to unmount the contents so the cleanup can occur.

**Steps to reproduce:**
Simply create a react app that has two pages.  Navigate to the second page from the first then tap the "back" button.  The second page will animate away but not unmount.  This leaves the secondary page mounted and the cleanup effects are not fired.

When the second page is opened again, the effects fire again but leave the old items lingering because cleanup didn't happen.

**Related code:**

https://github.com/Kikketer/ionic-react-bugger/blob/master/src/SecondPage.js#L8

Basically I have an effect that should fire on mount of a page.  Things that happen within this effect need to be cleaned up (the example is incredibly simplified).  When the second page is displayed again the effect is fired again but the cleanup is never fired.

```
useEffect(() => {
  // Some sort of listener or other item that needs cleanup
  return () => {
    // This isn't called to clean up
  }
}, [])
```

**Other information:**
This may half be a general React Hooks issue as this could possibly be seen elsewhere but I wanted to present it here as a possible upgrade/feature for Ionic React to help developers stop leaks.

Perhaps provide an "unmount on hide" type of option on pages.  Or something as simple as "page animation has finished" so developers could manually unmount items.  I've done a work-around by re-creating the back button:

```
      <IonHeader>
        <IonToolbar>
          <IonButtons slot="start">
            <IonLabel color={'medium'} onClick={navigateBack}>
              &lt; Back
            </IonLabel>
          </IonButtons>
```

And with `navigateBack` something as simple as:

```
  const navigateBack = () => {
    // the visible state variable makes the item within the content not be rendered triggering the unmount:
    setVisible(false)
    goBack()
  }
```

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI) : 4.12.0

System:

   NodeJS : v8.12.0
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by elylucas** [comment]
Fixes for this will be coming up in the next beta release
