### ISSUE TITLE
bug: ion-datetime not bind as ISO-8601 format when using pickerOptions

### ISSUE THREAD

**Issue by MatthiasVanMeerbeek-r0670805** [ionic-team/ionic#18142]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
This bug is basically the same as [ISSUE:15408](https://github.com/ionic-team/ionic/issues/15408#issue-355718218), but my issue applies to when you use custom pickerOptions. I need to be able to clear an ion-datetime because it isn't required, so I would add this option by using pickerOptions. But when I use picker options, the date isn't in the format of ISO-8601 anymore, but rather the weird object form.
![Aantekening 2019-04-26 161240](https://user-images.githubusercontent.com/28530170/56815593-0c991500-6842-11e9-87fd-60ca258b145e.jpg)

**Expected behavior:**
What I would expect is that when you use pickerOptions, the format would still be in the ISO-8601 format like when you are not using pickerOptions on a datetime, but this isn't the case for me.

**Steps to reproduce:**

`
My pickerOptions:
    
    public customStartDate: any = {
        buttons: [
            {
                text: 'Clear',
                handler: () => this.eventForm.controls['startDate'].setValue(null)
            },
            {
                text: 'Done',
                handler: (data: string) => {
                    console.log("date data:", data);
                    this.eventForm.controls['startDate'].setValue(data);
                }
            }
        ]
    }

    public customStartTime: any = {
        buttons: [
            {
                text: 'Clear',
                handler: () => this.eventForm.controls['startTime'].setValue(null)
            },
            {
                text: 'Done',
                handler: (data: Date) => {
                    this.eventForm.controls['startTime'].setValue(data);
                }
            }
        ]
    };

`

Replacing the "this.eventForm.controls..." part with a console.log(data) would be enough te be able to see the issue when you somehow trigger it.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. To get around JS Date's implementation of timezones, we use our own object for storing the datetime data, which is what you are seeing. The value that is emitted from the component is valid ISO-8601, but we use that custom object internally.

To get the proper ISO-8601 string, you will want to listen for the `ionChange` event.

So you would end up doing something like: `<ion-datetime (ionChange)="updateDate($event, formGroup)"></ion-datetime>`

Does this resolve your issue?
Thanks!

**Comment by MatthiasVanMeerbeek-r0670805** [comment]
> Hi there,
> 
> Thanks for the issue. To get around JS Date's implementation of timezones, we use our own object for storing the datetime data, which is what you are seeing. The value that is emitted from the component is valid ISO-8601, but we use that custom object internally.
> 
> To get the proper ISO-8601 string, you will want to listen for the `ionChange` event.
> 
> So you would end up doing something like: `<ion-datetime (ionChange)="updateDate($event, formGroup)"></ion-datetime>`
> 
> Does this resolve your issue?
> Thanks!

I don't really see how `(ionChange)="updateDate($event, formGroup)"` would be able to help me. What is the difference between using `(ionChange)` and the handler inside the pickerOption? I also don't know what this `updateDate($event, formGroup)"` needs to contain to be able to work properly.

In my opinion these are things that all should be explained inside the documentation of ionic (4). The documentation contains UI component examples, but it lacks the information on how to implement it properly or how to customize it (not only for `ion-datetime`). But that's somewhat another topic...

**Comment by liamdebeasi** [comment]
Hi there,

`ionChange` is the event emitted from the datetime component when the value of the date has been changed (i.e. after the date has been selected and "Done" has been clicked). The result of that is a valid ISO-8601 string. This can be found in the [Events section of the ion-datetime docs](https://ionicframework.com/docs/api/datetime#events).

The `pickerOptions` property is something that is passed through to the `ion-picker` component, which is what `ion-datetime` is built on. The property allows you to customize the underlying picker component. Details on this can be found in the [Properties section of the ion-picker docs](https://ionicframework.com/docs/api/picker#properties).

All the `updateDate` function needs to contain is the code you originally has in the `Done` button handler. In this case `$event` is an object containing the ISO-8601 date that was selected. 

Hopefully that clears things up a bit 🙂 . I am going to close this as it is not an Ionic issue.

For further details on how to implement or customize the datetime and picker components, please see the [ion-datetime Docs](https://ionicframework.com/docs/api/datetime) and the [ion-picker Docs](https://ionicframework.com/docs/api/picker).

For further assistance implementing your code, feel free to post on the [forums](http://forum.ionicframework.com) or on our [slack](https://ionicworldwide.herokuapp.com).

Thanks!

**Comment by MatthiasVanMeerbeek-r0670805** [comment]
Thank you for your answer.
`$event` indeed contains a valid ISO-8601 object when you work with f.e. `picker-format="DD MMMM YYYY"`. 
![Aantekening 2019-04-29 162848](https://user-images.githubusercontent.com/28530170/56903170-10c06f00-6a9c-11e9-9904-dccf415eacbe.jpg)

But it doesn't work when you want the time only f.e. `picker-format="HH mm ss"` (or at least it does not for me):
**With pickerOptions:**
![Aantekening 2019-04-29 162912](https://user-images.githubusercontent.com/28530170/56903212-20d84e80-6a9c-11e9-940f-154ba91e66b1.jpg)

**Without pickerOptions:**
![Aantekening 2019-04-29 163504](https://user-images.githubusercontent.com/28530170/56903582-e28f5f00-6a9c-11e9-922c-8567b3f7d284.jpg)


Is this really not a bug?


Thanks in advance!

**Comment by liamdebeasi** [comment]
Hi there,

Can you post your code? It's hard to say just seeing the output.

**Comment by MatthiasVanMeerbeek-r0670805** [comment]
HTML with pickerOptions:
```
<ion-item>
	<ion-label for="startTime" position="stacked">Starttijd</ion-label>
	<ion-datetime placeholder="hh:mm:ss" display-format="HH:mm:ss" picker-format="HH mm ss" formControlName="startTime" class="form-control" id="startTime" (ionChange)="updateStartTime($event, eventForm)" [pickerOptions]="customStartTime">
	</ion-datetime>
</ion-item>
```
HTML without pickerOptions:
```
<ion-item>
	<ion-label for="startTime" position="stacked">Starttijd</ion-label>
	<ion-datetime placeholder="hh:mm:ss" display-format="HH:mm:ss" picker-format="HH mm ss" formControlName="startTime" class="form-control" id="startTime" (ionChange)="updateStartTime($event, eventForm)">
	</ion-datetime>
</ion-item>
```
TS:
```
public customStartTime: any = {
	buttons: [
		{
			text: 'Clear',
			handler: () => this.eventForm.controls['startTime'].setValue(null)
		},
		{
			text: 'Bewaar',
			handler: (data: string) => {
				this.eventForm.controls['startTime'].setValue(data);
			}
		}
	]
};

eventForm = new FormGroup({
		id: new FormControl('', []),
		eventTypeId: new FormControl('', [Validators.required]),
		name: new FormControl('', [Validators.required]),
		description: new FormControl('', [Validators.required]),
		startDate: new FormControl('', [Validators.required]),
		startTime: new FormControl({ value: '', disabled: false }),
		endDate: new FormControl('', [Validators.required]),
		endTime: new FormControl({ value: '', disabled: false }),
		isFullDay: new FormControl(false),
		location: new FormControl('')
	});

updateStartTime($event, eventForm) {
	console.log($event);
	console.log(eventForm);
}
```
That is all the code that is relevant.
And you can see the results of `$event` both with and without pickerOptions above.

If you need more, just ask me 😃 .

Thanks!

**Comment by liamdebeasi** [comment]
Hi there,

The reason why this is happening is that `data` in button handler is not a string. As I mentioned before, that is the custom object we use internally to parse dates.

You are setting the `value` of the datetime to this object, and so the datetime component is just going to emit that object back. The `value` property expects a valid ISO-8601 string, as stated in the `ion-datetime` documentation.

**Comment by MatthiasVanMeerbeek-r0670805** [comment]
>  `ionChange` is the event emitted from the datetime component when the value of the date has been changed (i.e. after the date has been selected and "Done" has been clicked). The result of that is a valid ISO-8601 string. This can be found in the Events section of the ion-datetime docs.

> The reason why this is happening is that data in the button handler is not a string. As I mentioned before, that is the custom object we use internally to parse dates.

> You are setting the value of the datetime to this object, and so the datetime component is just going to emit that object back. The value property expects a valid ISO-8601 string, as stated in the ion-datetime documentation.

This is creating the problem, ionChange doesn't trigger when you don't update the value of the datetime. So I'm not able to get $event when I don't somehow change something of the datetime object...

I am completely lost. For a date (year, month, day) it works perfectly, but for time (hour, minute, second) it doesn't when I do exactly the same for both except for the picker-format. And [as stated in the documentation](https://ionicframework.com/docs/api/datetime#iso-8601-datetime-format-yyyy-mm-ddthh-mmz), HH:mm:ss is a valid ISO-8601 format.

I don't know what else I can say or try to do, would creating a small public GitHub project be interesting for you?

**Comment by liamdebeasi** [comment]
Hi there,

Do you have an example where the date formatting is working properly? I have the time example, and that has the behavior you described, but the date formatting is also returning the custom object.

Thanks!

**Comment by MatthiasVanMeerbeek-r0670805** [comment]
I'm wrong. I'm so sorry. Date has the same behavior as time. Sorry.

But still, how would I be able to trigger ionChange without using the handler? How am I able to get an ISO-8601 without setting the value to the custom object?

**Comment by liamdebeasi** [comment]
Hi there,

When you select a date in the datetime component and then click "Done", `ionChange` is triggered. If you want to use a custom handler, you will need to parse the date object yourself.

Ideally, there would be a "clear" option built into `ion-datetime`. There is a feature request open for that functionality: https://github.com/ionic-team/ionic/issues/17482.

**Comment by MatthiasVanMeerbeek-r0670805** [comment]
Project where everything can be seen:
https://github.com/MatthiasVanMeerbeek-r0670805/Ionic4IonDatetime

(Don't know how to properly link a project to an issue.)
