### ISSUE TITLE
bug: ToastController don't work as expected with await

### ISSUE THREAD

**Issue by emidev98** [ionic-team/ionic#18147]
Dear Support,

I'm creating a wrapper class for ToastController. The method create() from toast controller does not accept await keyword as explained in documentation. Using the code autocomplete in Visual Studio it show me that this function return a promise. Also when I use console to print the value of the variable the return value is a promise.

### Code Example

![image](https://user-images.githubusercontent.com/49301655/56824744-9acbc600-6857-11e9-911c-acc0471c0584.png)

### Visual Studio autocomplete

![image](https://user-images.githubusercontent.com/49301655/56824875-09108880-6858-11e9-9e66-b7610d19c733.png)

### Ionic Version

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\Emi\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

If you need more information I also can provide it. 

Thanks,
Emilian

**Comment by kensodemann** [comment]
That all looks correct...

You need to use async if you are going to use await.

```TypeScript
private async show( ... ) {
  const toast = await this.toastCtrl.create( ... );
  ...
}```
