### ISSUE TITLE
bug: App crash in Iphone 6 whith IOS 9.3

### ISSUE THREAD

**Issue by juanqui66** [ionic-team/ionic#18160]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
The application does not start, and the following exception occurs:

019-04-26 23:08:52.861 atenea[352:132838] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///private/var/mobile/Containers/Data/Application/267200A0-D595-4A0F-84AC-27EC5EA73C25/Library/Cookies/Cookies.binarycookies
2019-04-26 23:08:53.150 atenea[352:132838] Apache Cordova native platform version 4.5.5 is starting.
2019-04-26 23:08:53.161 atenea[352:132838] Multi-tasking -> Device: YES, App: YES
2019-04-26 23:08:53.221 atenea[352:132838] CDVWKWebViewEngine: trying to inject XHR polyfill
2019-04-26 23:08:53.240 atenea[352:132838] -[WKWebViewConfiguration setMediaTypesRequiringUserActionForPlayback:]: unrecognized selector sent to instance 0x17779d90
2019-04-26 23:08:53.243 atenea[352:132838] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[WKWebViewConfiguration setMediaTypesRequiringUserActionForPlayback:]: unrecognized selector sent to instance 0x17779d90'
*** First throw call stack:
(0x2267391b 0x21e0ee17 0x226792b5 0x22676ee1 0x225a2238 0xff1ad 0xff9fb 0x242831 0x241f43 0x2423e1 0x23fa81 0x6b56f 0x26beed8b 0x26bee971 0x26bf5639 0x26bf2b3d 0x26c67a5d 0x2440dd 0x6b345 0x26c63785 0x26e8b2d1 0x26e8f285 0x26ea383d 0x26e8c7b3 0x23d16c07 0x23d16ab9 0x23d16db9 0x22635dff 0x226359ed 0x22633d5b 0x22583229 0x22583015 0x26c5cc3d 0x26c57189 0x6b243 0x2222b873)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

**Expected behavior:**
It is expected that the application starts just like it does on an Android device, where the App starts without problems.

**Steps to reproduce:**
- ionic start sidemenu sidemenu
- ionic cordova platform add ios
- sudo npm -g install ios-deploy --unsafe-perm=true
- sudo ionic serve  (runs ok in Opera).
- sudo ionic cordova build ios -- --buildFlag="-UseModernBuildSystem=0"
   ...running in XCode, crash.
- sudo ionic cordova run ios -- --buildFlag="-UseModernBuildSystem=0"
   ..cashes also.

**Related code:**
Ionic sidemenu sample code.

**Other information:**
![image](https://user-images.githubusercontent.com/28297694/56838927-5d2f6300-6880-11e9-81d3-3cfb57e4e366.png)

**Ionic info:**

```
   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 17 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 5.0.13
   NodeJS     : v10.15.3 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61

```

**Comment by liamdebeasi** [comment]
Hi there,

As per the `cordova-plugin-ionic-webview` requirements (https://github.com/ionic-team/cordova-plugin-ionic-webview#plugin-requirements), only iOS 11+ is supported for version 4 of the plugin. If you need to support iOS 9, you will need to use version 1 of the plugin: https://github.com/ionic-team/cordova-plugin-ionic-webview/tree/1.x

I am going to close this as this is not an Ionic issue.

Thanks!

**Comment by juanqui66** [comment]
Okay, I was not aware of it. Thank you very much for your dedication.
