### ISSUE TITLE
bug: ion-toast doesn't have a buttons property in react

### ISSUE THREAD

**Issue by hntrl** [ionic-team/ionic#18164]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
`Typescript error: Property 'buttons' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<{ element: HTMLIonToastElement; ...`

**Expected behavior:**
Should compile without error.

**Steps to reproduce:**
Use the component below and try to compile it. I'm working off of the react documentation [here](https://ionicframework.com/docs/api/toast)

**Related code:**

```
<IonToast
    isOpen={this.state.cartPreview}
    onDidDismiss={() => this.setState({ cartPreview: false })}
    buttons={[{
        side: 'start',
        icon: 'star',
        text: 'Favorite',
        handler: () => {
            console.log('Favorite clicked');
        }
    }]}
/>
```

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI) : 4.12.0 (/usr/local/lib/node_modules/ionic)

System:

   NodeJS : v10.14.2 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by elylucas** [comment]
Hi @hntrl, could you verify which version of @ionic/core you are on? Version > 4.3 should have the updated interfaces for the toast buttons.

Thanks

**Comment by elylucas** [comment]
Going to close, if you still find issues with this let us know.  Thanks!
