### ISSUE TITLE
bug: ion-datetime don't return iso value

### ISSUE THREAD

**Issue by kareem289** [ionic-team/ionic#18175]
# Bug Report
Bug related to 
```
ion-datetime 
```
after I update to 4.0.3 the return value is not iso date iso  it's a normal string equal to display format 

**Ionic version:**

[x] **4.x**
4.0.3

**Current behavior:**

if display-format "y" the value return 2019

**Expected behavior:**

it should when we add display-format="y" it return full date iso "2019-05-01T00:00:00"

**Steps to reproduce:**

**Related code:**

**Ionic info:**

```

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.3
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 18 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v11.12.0 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2 Build version 10E125
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. This bug has already been fixed in a newer version of Ionic. You can update using `npm i @ionic/angular@latest`.

Thanks!
