### ISSUE TITLE
bug: the color="anything-shade/tint/contrast" attribute is not working

### ISSUE THREAD

**Issue by sarizu99** [ionic-team/ionic#18177]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
the color="anything-shade/tint/contrast" attributes is not working.

**Expected behavior:**
The attribute above to be working as expected. For example, color="primary-shade" producing color theme of #3171e0, and also the other color="anything-shade/tint/contrast" (based on default /src/theme/variables.scss).

**Steps to reproduce:**
1. Create new tabs project
2. Modify the ion-toolbar with color="primary-shade"

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\sariz\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.3.1
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 4 other plugins)

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by brandyscarney** [comment]
Thanks for the issue! This is not how the `color` property works. It only accepts the 9 default colors and any colors that are added. There is documentation on colors here: https://ionicframework.com/docs/theming/advanced#colors

If you have the new color defined and it is still not working please let me know, thanks!
