### ISSUE TITLE
bug: ion-input needs 2 click/tap to trigger event

### ISSUE THREAD

**Issue by lordcoste** [ionic-team/ionic#18171]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
The (click) event is only triggered after the second tap. Someone suggested to use (focus) event but I need to trigger the click on a **readonly** input.

**Expected behavior:**
The (click) event should be triggered on the first tap.

**Steps to reproduce:**

**Related code:**

```
<ion-input (click)="onClick($event)" type="tel" name="phone" placeholder="Phone" [attr.readonly]="!editing"></ion-input>
```

**Other information:**
There was an older issue: https://github.com/ionic-team/ionic/issues/6169

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic 5.3.0, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.3, (and 18 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/lordcoste/Library/Android/sdk/)
   ios-deploy        : 1.9.4
   NodeJS            : v10.15.0 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by lordcoste** [comment]
Right now I've solved importing hammerjs and using tap event.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you describe your issue a bit more? Is this happening on a mobile device? If so, which device/software version? Additionally, have you tried this with the latest version of Ionic?

Thanks!
