### ISSUE TITLE
bug: [ionic4+vue] toastController not accessible from an external javascript file

### ISSUE THREAD

**Issue by alterhu2020** [ionic-team/ionic#18174]
# Bug Report

**Ionic version:**

 "@ionic/core": "4.3.1",
 "@ionic/vue": "^0.0.4",

**Current behavior:**

`toastController` can call with `this.$ionic.toastController` but cannot access from external javascript.
**Expected behavior:**

in an external javascript, like my javascript file `test.js`, there's no way to access the `toastController` object.

**Steps to reproduce:**

Call the below `toastController` code from external javascript code, will throws  exceptions:
```
import {Controllers} from '@ionic/vue'
Controllers.toastController.create({
    message: message,
    position: 'center'
  }).then(t => t.present())
```

**Related code:**

```
No
```

**Other information:**

**Ionic info:**

```
no
```

**Comment by alterhu2020** [comment]
any update for this issue team

I know we can use the mixin to invoke `this`, but we need to add the mixin everytime in the vue component. 
How we can export the `toastController` to a common javascript function instead. thanks .

**Comment by michaeltintiuc** [comment]
You should be able to access the `$ionic` object via the global Vue instance `Vue.$ionic` this is handy in situations when `this` is not available. 

![Screenshot from 2019-05-28 00:27:51](https://user-images.githubusercontent.com/1321256/58439924-922d1080-80df-11e9-860c-d3d15efd957e.png)

**Comment by alterhu2020** [comment]
thanks @michaeltintiuc , I forgot that we can use the Vue instance instead here ,currently i use the` mixin` to put ionic common function in a file .  thanks again.
