### ISSUE TITLE
bug: Popover not working correctly with 'press' event

### ISSUE THREAD

**Issue by CoolM8** [ionic-team/ionic#18180]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When the popover.present() method is bound to a 'press' event, then there is a problem when the user presses the button long enough to open the popover but if the press is released a little bit to early, the popover gets directly closed again because the backdrop tap is triggered as well.

**Expected behavior:**
The event 'ionBackdropTap' should not be triggered within the same press action. It should only trigger when the popover is fully displayed and a new user interaction happens.

**Steps to reproduce:**
1. Include HammerJS
1. Bind (press) function and present a popover.
2. Press the button but do not wait until the popover is displayed. -> Sometimes the popover shows up shortly and gets directly closed again.

**Other information:**
This issue was already in ionic 3 but the workaround posted here: https://forum.ionicframework.com/t/popover-triggers-backdrop-dismiss-when-using-press-event/118148/4
does not seem to work with ionic 4. 

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.11.0 (C:\Users\meis\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.3.3
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 14 other plugins)

System:

 (D:\WebDevPlatform\tools\android-sdks)
   NodeJS            : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10
```

**Comment by vincekd** [comment]
I am also getting this with modals. Does the ionic team have any solution for this?

**Comment by Eptick** [comment]
Can confirm this also happens with tap events
This issue is not present in ionic 4.5.0 for me on the tap event
happens only on a mobile device

**Comment by Eptick** [comment]
[popover-test.zip](https://github.com/ionic-team/ionic/files/3583188/popover-test.zip)
Sample application tested on android

**Comment by marcorinck** [comment]
This happens for me too for popover and modal components but very sporadically. 

I have a button which opens a dropdown menu from which modals can be opened. Most of the times they are working as expected but sometimes when I tap one of the elements which are listening to tap events to open the popover/modal its doing apparently nothing. I see a glimpse of the backdrop and thats it. 

The popover.onWillDidMiss()  callbacks are NOT getting called when it happens and the popover.present() promise is not being resolved either. 

It seems to be working fine when I use the click event.

**Comment by daviddickson** [comment]
This is possibly related to what I'm seeing using `tap()`.  The initial call to the popover works, but subsequent calls do not.

**Comment by liamdebeasi** [comment]
Thanks for the issue. We caution against using HammerJS in Ionic apps. It tends to be "heavy handed" in the sense that it sometimes will prevent events from propagating, causing Ionic components to not receive the proper click/touch events.

With the launch of Ionic Framework v5, we introduced our own gesture solution that you could use to mimic the behavior HammerJS has: https://ionicframework.com/docs/utilities/gestures.

Thanks!
