### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by thesurya9** [ionic-team/ionic#18200]
Ionic 4 application is not working on Android 5.0, Android 5.1, Android 6.0.

But ionic official claims it will support android 4.4 or greater.
But it’s not working. I m searching for a solution from last week.

I have decided to make an app in Ionic 4. I made very blunders mistake. Now I can not go back. it took me 2 months to develop the app from scratch, I very much disappointed.
Can someone please help me?

**Comment by ElianCordoba** [comment]
What kind of error are you getting? It's hard to know if you don't explain what's happening :/
Also, try to put a more explanatory title next time so it's easy to help you.
