### ISSUE TITLE
ionic4。 camera  plugin error

### ISSUE THREAD

**Issue by zhiwo** [ionic-team/ionic#18205]
const options: CameraOptions = {
            quality: 100,
            destinationType: this.camera.DestinationType.FILE_URI,
            encodingType: this.camera.EncodingType.JPEG,
            mediaType: this.camera.MediaType.PICTURE,
        };

FILE_URI: error: can't find local picture,base64 Type is normal

**Comment by liamdebeasi** [comment]
Hey there!

I've noticed you have opened a few issues here that have been closed as `missing template`. Filling out the completed template helps us better assist you. When creating issues, please fill out the complete template. 

Thanks! 🙂
