### ISSUE TITLE
feat: Per page animation configurability

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic#18209]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

I am working with a user whose app requires the use a custom animation on a per page basis. Most pages will use the regularly defined animations for page transitions, but some pages will need to have their own. Here is the specific use case:

> The idea is that some user flows for logged in users are "process flows" rather than standard page navigation and these process flows should animate the first page of that flow from bottom to top (and subsequent  page animation from right to left)

**Describe Preferred Solution**

Ideally, allowing an "AnimationBuilder" animation to be specified via the options of a `navController.navigate*` method call would likely be the best option for this use case.

**Describe Alternatives**

I have considered the possibility of using the `animation` property on the `ion-router-outlet`, however, this has not been provided via `@ionic/angular` (https://github.com/ionic-team/ionic/issues/18208) and it is not entirely clear to me that changing the animation on the outlet before the navigation took place would actually work (would require experimentation that I cannot do without the property being exposed).

**Comment by marcorinck** [comment]
Sadly, we had this feature in Ionic 3 but its gone in Ionic 4. You could register custom transitions and use those in the navigate methods of the navController.

For ionic4, I'm currently thinking about a 'hack' solution with the help of the user provided navAnimation in the root ionic config: IonicModule.forRoot({...., navAnimation: YourCustomAnimationBuilder}). 

Though, you can only specify ONE AnimationBuilder for the whole application. So this Builder somehow had to 'guess' the current page specific transition on some misused config option or property in the DOM somewhere and change its behaviour accordingly. 

Sadly, I'm not beyond the stage of thinking about it.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. This has been resolved via https://github.com/ionic-team/ionic/pull/21433 and will be available in an upcoming release of Ionic Framework.

Please note that this PR has support for Vanilla JS, Stencil, and Angular apps. Support for this feature will be coming to React in a future version. We are working on updates to the Ionic React Router, so the feature will be available when that ships.

For most components, you will be able to provide a value to the `routerAnimation` property when using `routerLink`.

For the `NavController` in Ionic Angular, you can provide the animation via the `animation` property in an `options` object:

```javascript
this.navController.navigateForward('/child', { animation: animationBuilder });
```

`animationBuilder` is a reference to an Ionic Animation Builder function: https://ionicframework.com/docs/utilities/animations#overriding-ionic-component-animations
