### ISSUE TITLE
bug: ion-router `animation` property not bound in `@ionic/angular`

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic#18208]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
In `@ionic/core`, the `ion-router-outlet` contains an `animation` property that allows users to customize the animations used for that outlet (https://github.com/ionic-team/ionic/blob/master/core/src/components/router-outlet/route-outlet.tsx#L37-L41). This has not been exported via the corresponding `@ionic/angular` directive (https://github.com/ionic-team/ionic/blob/master/angular/src/directives/navigation/ion-router-outlet.ts#L15)

**Expected behavior:**
The `animation` property would be included in the `ion-router-outlet` directive in `@ionic/angular`

**Steps to reproduce:**

Create an app, try to set the property, you will be denied...

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/Users/kensodemann/.nvm/versions/node/v10.15.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.3.1
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.3 (cordova-lib@9.0.2)
   Cordova Platforms     : android 8.0.0, ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/kensodemann/Library/Android/sdk/)
   ios-deploy        : 1.9.2
   ios-sim           : 8.0.1
   NodeJS            : v10.15.1 (/Users/kensodemann/.nvm/versions/node/v10.15.1/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by liamdebeasi** [comment]
Fixed via https://github.com/ionic-team/ionic/pull/20767 and released in Ionic Framework 5.0.6.
