### ISSUE TITLE
bug: ion-menu onclick does not exist on type IonButtonAttributes

### ISSUE THREAD

**Issue by p3sn** [ionic-team/ionic#18206]
Hi all, 

Although the example at https://ionicframework.com/docs/api/menu does work. When I try to implement this in my stencil-ionic-app, I get the following error message:
```
Type '{ onclick: string; href: string; expand: "block"; }' is not assignable to type 'IonButtonAttributes'.
  Property 'onclick' does not exist on type 'IonButtonAttributes'.ts(2322)
```

Regards, Peter

**Comment by brandyscarney** [comment]
Thanks for the issue! The `onclick` property is required to be written as `onClick` in JSX. If you change that it should remove the error.
