### ISSUE TITLE
feat: Label for Fab buttons

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#18207]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
I think it would be cool to be able to provide optionally labels to `Fab` buttons too.

Often when I speak about accessibility with designer I get the feedback "It's hard for users to understand icons, specially on mobile devices". Therefore I think that being able to provide a floating label next to fab actions would be helpful.

**Additional Context**
Something like my poor screenshot/mockup:

<img width="1403" alt="Capture d’écran 2019-05-06 à 15 45 37" src="https://user-images.githubusercontent.com/16886711/57229609-d19f9a00-7016-11e9-82e3-8db52090e844.png">

**Comment by cjorasch** [comment]
Some other related FAB issues:
https://github.com/ionic-team/ionic/issues/14648
