### ISSUE TITLE
bug: backdropDismiss option does not work for IonSelect

### ISSUE THREAD

**Issue by pjc2007** [ionic-team/ionic#18203]
# Bug Report

**Ionic version:**
  4.3
**Current behavior:**
I have a ion-select in my markup as follows..
```
<ion-select interfaceOptions='opts'
```
Where in the component ts file, the opts is
```
public opts = { backdropDismiss: false };
```
as per documentation [here](https://ionicframework.com/docs/api/alert), and using the `interfaceOptions` as suggested in the ion-select documentation.

**Expected behaviour:**
Would like the select alert to stay open until the user clicks a button, and not dismiss when they click the backdrop

**Ionic info:**
```
ionic (Ionic CLI)             : 4.12.0 (C:\Users\Latitudeuser\AppData\Roaming\nvm\v10.15.0\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.3.1
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (C:\Android\android-sdk)
   NodeJS            : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

```

**Comment by jaipresto** [comment]
Wrap the attribute in square brackets and it should work.

So:
```typescript
<ion-select [interfaceOptions]="opts">
```

Right now, you're just assigning the string 'opts' to ion-select.

[Property Binding](https://stackoverflow.com/questions/46368382/angular-property-binding)

**Comment by pjc2007** [comment]
@jaipresto - it does work! It was my bad.

Thank you very much for that, I will close the issue (as it is not an issue).
