### ISSUE TITLE
bug:  i am using ionic 4.1.12 there are lots of issues camera  plugins  .

### ISSUE THREAD

**Issue by virusismine** [ionic-team/ionic#18232]
via remote
npm WARN @ionic-native/camera@5.5.1 requires a peer of rxjs@^6.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/camera@5.5.1 requires a peer of @ionic-native/core@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/device@5.4.0 requires a peer of rxjs@^6.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/device@5.4.0 requires a peer of @ionic-native/core@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/network@5.5.1 requires a peer of rxjs@^6.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/network@5.5.1 requires a peer of @ionic-native/core@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/fire@5.1.2 requires a peer of @angular/common@>=6.0.0 <8 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/fire@5.1.2 requires a peer of @angular/core@>=6.0.0 <8 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/fire@5.1.2 requires a peer of @angular/platform-browser@>=6.0.0 <8 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/fire@5.1.2 requires a peer of @angular/platform-browser-dynamic@>=6.0.0 <8 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/fire@5.1.2 requires a peer of rxjs@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/fire@5.1.3 requires a peer of @angular/common@>=6.0.0 <8 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/fire@5.1.3 requires a peer of @angular/core@>=6.0.0 <8 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/fire@5.1.3 requires a peer of @angular/platform-browser@>=6.0.0 <8 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/fire@5.1.3 requires a peer of @angular/platform-browser-dynamic@>=6.0.0 <8 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/fire@5.1.3 requires a peer of rxjs@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by virusismine** [comment]
Please Help

**Comment by AndreasGassmann** [comment]
Well it looks like you are missing a lot of packages that are required as peer dependencies. (rxjs, ionic-native/core, etc). But because there are so many, are you sure that your project setup is correct?
