### ISSUE TITLE
bug: ion-input ignores min value for validation

### ISSUE THREAD

**Issue by swavans** [ionic-team/ionic#18240]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When an ion-input is defined with either min or max values specified

**Expected behavior:**
I expect the validation to fail when the user is below min or above max, and therefor the parent ion-item to show a red border on the bottom.

**Steps to reproduce:**
Create an ion-input inside an ion-item in a template driven form.

**Related code:**
https://stackblitz.com/edit/ionic-6pxtfl
(pattern is added to show expected validation behaviour)

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. I noticed the StackBlitze references Ionic 3. Is this issue happening with an Ionic 3 app, or an Ionic 4 app?

Thanks!

**Comment by swavans** [comment]
Woeps my bad
It's supposed to be Ionic 4, but if it also happens in the stack blitz than I guess it's in both.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you post a repo with the code required to reproduce this issue running inside an Ionic 4 application?

Thanks!

**Comment by swavans** [comment]
Sure thing https://github.com/swavans/ionic-zjip2h

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the follow up. Angular handles the form validation, and currently min/max is not supported using template-driven forms: https://github.com/angular/angular/issues/16352.

I would recommend using reactive form validation for now if you need this support: https://angular.io/guide/form-validation#reactive-form-validation.

I am going to close this as this is not an Ionic issue. Thanks!
