### ISSUE TITLE
bug: IonImg label in Android version 7 can not work!

### ISSUE THREAD

**Issue by sixiaodong123** [ionic-team/ionic#18259]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

the IonImg in Android version 7.0 is not taking effects.
**Expected behavior:**

IonImg in Android version 7.0 can load img
**Steps to reproduce:**
 1. import a picture 
 2. use IonImg to loading this img
**Related code:**

```
  import iconCode from './coding.png';
 <IonImg src={iconCode} />
```

**Other information:**

**Ionic info:**

```
@ionic/react": "^0.0.5",
```

**Comment by elylucas** [comment]
Closing this issue as its old on a pre-beta version of Ionic/React. If the problem still persists on the latest version, please create a new issue and link this one for reference.
