### ISSUE TITLE
bug: ion-label is "blury" when stacked because of transform

### ISSUE THREAD

**Issue by eduboxgithub** [ionic-team/ionic#18255]
# Bug Report

**Ionic version:**

[x] **4.4.0** latest version

**Current behavior:**
When using a ion-label with position="stacked" the text on the label gets "blurry" like it's an image.

**Expected behavior:**
It should be clear and crispy.

**Steps to reproduce:**
Use an ion-label with position stacked. 

For example:
```
<ion-grid>
      <ion-row>
		<ion-col size="4" no-padding no-margin>
			<ion-item>
				<ion-label position="stacked">{{ 'POSTALCODE' | translate}}</ion-label>
				<ion-input type="tel" maxlength="4" [(ngModel)]="Data.Cp4" name="searchPostal"
								placeholder="{{ 'POSTALCODE' | translate}}" full></ion-input>
			</ion-item>
		</ion-col>
		<ion-col size="4" no-padding no-margin>
			<ion-item>
				<ion-label position="stacked">{{ 'EXTENSION' | translate}}</ion-label>
				<ion-input type="tel" maxlength="3" [(ngModel)]="Data.Cp3" name="searchExtension" (keypress)="onKeyPressed($event.keyCode)" placeholder="{{ 'EXTENSION' | translate}}"full></ion-input>
			</ion-item>
		</ion-col>
		<ion-col size="4" padding-top no-margin>
			<ion-button fill="solid" shape="round" float-right (click)="filterAddress()">
				<ion-icon name="locate"></ion-icon>
			</ion-button>
		</ion-col>
	</ion-row>
</ion-grid>
```
![image](https://user-images.githubusercontent.com/13800439/57545519-7c36f600-7352-11e9-8c04-76f91148c6eb.png)

![image](https://user-images.githubusercontent.com/13800439/57545600-c1f3be80-7352-11e9-92dc-e4c80ec55861.png)

**Other information:**
I'm using the latest version of Chrome and Chrome Canary.

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\hsantos\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (C:\Users\hsantos\AppData\Local\Android\Sdk)
   NodeJS            : v11.12.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Comment by eduboxgithub** [comment]
I was checking the docs and notice this is also happning on the exemples provided in the docs:

![image](https://user-images.githubusercontent.com/13800439/58412042-915b9680-806d-11e9-8abb-7b0e275424b0.png)

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. What kind of display are you seeing this on?

Thanks!

**Comment by eduboxgithub** [comment]
I'm developing on a "regular" monitor... Benq GL2460 and also my Asus laptop monitor.
But this algo happens on other monitors (Philips, Lg, etc).

It seems a rendering problem... I tested in MS Edge, Chrome and Firefox. Chrome (my main browser)  is where the blur happens...

![Capture](https://user-images.githubusercontent.com/13800439/58708038-875bcf80-83ae-11e9-9182-26118dd77a97.JPG)

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the follow up. It's hard to tell what the issue is -- in the examples you provided the entire screenshot looks blurry to me. 

What operating system + version are you using?

Thanks!
