### ISSUE TITLE
bug: ion-card as a button has some UI issues

### ISSUE THREAD

**Issue by tmk1991** [ionic-team/ionic#18252]
# Bug Report

**Ionic version:**
[x] **4.4.0**

**Current behavior:**
Love the feature! It needs a tweak 

The button of the card isn't inheriting the card styling. If you have any sort of height changes, background image, etc on the ion-card, the button portion maintains original ion-card styling, overlapping the ion-card.

**Expected behavior:**
ion-button styling should match ion-card styling

**Steps to reproduce:**
Make CSS changes to the ion-card and enable button attribute.

**Related code:**

Fixed with:
```
ion-card {
    button {
       height: 100%;
       border-radius: inherit;
       background: transparent !important;
    }
}
```

**Comment by brandyscarney** [comment]
Could you please provide the html and CSS used to reproduce this? I am not able to reproduce: https://codepen.io/brandyscarney/pen/bypjVY

**Comment by tmk1991** [comment]
Thanks for the pen! Global settings overrode the button. I had a --background: color !important somewhere. My apologies.

**Comment by brandyscarney** [comment]
That's okay! Glad it's fixed 🙂
