### ISSUE TITLE
ion-range: Type 'string' is not assignable to type 'number'.

### ISSUE THREAD

**Issue by ktamiola** [ionic-team/ionic#18268]
# Bug Report
There seems to be an issue with parsing numeric input to `ion-range` component.

**Ionic version:**
  "@ionic/core": "^4.0.0"

**Current behavior:**
```
[ ERROR ]  TypeScript: src/components/predictors/uis/pepkalc/app-pepkalc.tsx:57:35
           Type 'string' is not assignable to type 'number'.

     L56:  <ion-item>
     L57:    <ion-range pin min="0" max="400" color="primary">
     L58:      <ion-label slot="start">0K</ion-label>
```
**Expected behavior:**
The range slider works and parses number arguments.

**Steps to reproduce:**
```
                  <ion-item>
                    <ion-range pin min="0" max="400" color="primary">
                      <ion-label slot="start">0K</ion-label>
                      <ion-label slot="end">400K</ion-label>
                    </ion-range>
                  </ion-item>
```
Because of the above the compilation process stops and reports an error.

**Comment by brandyscarney** [comment]
Thanks for the issue! Could you please provide a Codepen, Plunker, etc. that I can use to reproduce? I am not able to see this using latest `@ionic/core@4.4.0`: https://codepen.io/brandyscarney/pen/QRKxqj

**Comment by ktamiola** [comment]
I have used a PWA template initiated using `@stencil/core: ^0.17.2`. I will try to provide a code pen tomorrow (CET).

**Comment by brandyscarney** [comment]
@ktamiola Oh! Are you using JSX? If so it needs to be written like the following:

```
<ion-range pin min={0} max={400} color="primary">
```

We don't have Stencil usage docs yet but we have some examples of React and that is a similar syntax when it comes to setting properties.

**Comment by ktamiola** [comment]
:man_facepalming: Thank you so much @brandyscarney . How embarrassing... All works like a charm now.

**Comment by brandyscarney** [comment]
@ktamiola No worries! I've done it too. 😅
