### ISSUE TITLE
bug: ion-back-button with no text prop shows no text when running in the browser and shows Back text when running on a real device

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic#18261]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

<ion-back-button></ion-back-button> shows only back icon and no text when running in the browser (ionic serve) and shows back icon and 'Back' text when running on real device (Android or iOS).
This problem seems to appear in the latest build 4.4.0 and it used to work differently in 4.3.0
Please note that if i add text="" (`<ion-back-button text=""></ion-back-button>`) the behavior seems to be consistent when running in the browser and on real devices

**Expected behavior:**

The behavior should be consistent when running in the browser and on a real device.

**Steps to reproduce:**
Create a component with `<ion-back-button></ion-back-button>` in the header and then run in a browser using ionic serve or build and deploy on a real device.

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (/Users/alexryltsov/.nvm/versions/node/v10.14.2/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.19
   @capacitor/core           : 1.0.0-beta.19

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (9 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/alexryltsov/Library/Android/sdk/)
   NodeJS            : v10.14.2 (/Users/alexryltsov/.nvm/versions/node/v10.14.2/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by paulstelzer** [comment]
Thanks for your issue! This is by design. If you do not want it, take a look at the config -> https://ionicframework.com/docs/utilities/config#config-options

Here you can set a "backButtonText" and set it to an empty string if you want. Back button text is the default on native devices.
