### ISSUE TITLE
bug: Some components are rarely not rendered when scrolling down on android device

### ISSUE THREAD

**Issue by nyamage** [ionic-team/ionic#18275]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Some components are rarely not rendered when scrolling down on android device.
These components are rendered when device orientation is changed.
We confirmed that elements exists in DOM tree (and should be visible) by using inspector.

![image](https://user-images.githubusercontent.com/1564952/57682445-da264f00-766c-11e9-9ba6-5d6c90764db9.png)

**Expected behavior:**
Components are rendered when scrolling down on android device

**Steps to reproduce:**
- Scroll down on page that has many elements 

* we haven't seen this issue on elements above the fold

**Related code:**

**Other information:**
Device Type: HUAWEI MediaPad T3 10
Device Model: AGS-W09
Android : 7.0
Chrome: 74.0.3729.136

```
$cordova plugin list
cordova-android-support-gradle-release 2.1.0 "cordova-android-support-gradle-release"
cordova-plugin-advanced-http 2.0.5 "Advanced HTTP plugin"
cordova-plugin-allow-backup 0.0.2 "cordova-plugin-allow-backup"
cordova-plugin-app-update 1.6.0 "AppUpdate"
cordova-plugin-appversion 1.0.0 "App Version"
cordova-plugin-buildinfo 2.0.2 "BuildInfo"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-device-motion 2.0.1 "Device Motion"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic 4.1.7 "IonicCordova"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.4.1 "cordova-plugin-ionic-webview"
cordova-plugin-localization-strings 2.0.0 "Localization"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-market-availability 1.0.0 "Play Store Availability"
cordova-plugin-remove-arm64 0.0.1 "cordova-plugin-remove-arm64"
cordova-plugin-shake 0.6.0 "Shake Gesture Detection"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
phonegap-plugin-barcodescanner 7.1.0 "BarcodeScanner"
```

**Ionic info:**

```
ionic info

Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.3.6
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.4, ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic 4.1.7, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.1, (and 21 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 7.0.0
   NodeJS     : v8.9.4 (/Users/tsukamotojunichi/.nodebrew/node/v8.9.4/bin/node)
   npm        : 5.6.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001

```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you provide a repository with the code required to reproduce this issue? Also, how much memory does your device have?

Thanks!

**Comment by nyamage** [comment]
> Can you provide a repository with the code required to reproduce this issue
I'm sorry but we cannot provide it since it's in our private repo. we will try to create code to reproduce the issue.

> how much memory does your device have?
it has 2GB memory.

we have seen this issue only in ionic v4 (not happen in v3).

**Comment by nyamage** [comment]
@liamdebeasi 
I sent a movie (it's screen capture of this issue) via e-mail to hi@ionic.io. please check it.

**Comment by liamdebeasi** [comment]
Hi @nyamage,

I do not have access to that email account. Are you able to just create a small reproduction on GitHub and send me a link?

Thanks!

**Comment by liamdebeasi** [comment]
Hi there,

I was able to get someone to forward me the email. Are you using virtual scrolling in your application?

**Comment by nyamage** [comment]
NO, I'm not using ion-virtual-scroll.

**Comment by liamdebeasi** [comment]
Thanks for the follow up! Do you have a code sample where this issue happens?
