### ISSUE TITLE
bug: I can change footer to any color, but I can’t set it to transparent

### ISSUE THREAD

**Issue by SanduCuragau** [ionic-team/ionic#18274]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
So I have this footer
![image](https://user-images.githubusercontent.com/18098208/57682618-27350180-762a-11e9-8895-58846f3441b5.png)
through the chrome dev tools I can play around with its style and I can totally see how setting its color to anything works perfectly
![image](https://user-images.githubusercontent.com/18098208/57682638-2ef4a600-762a-11e9-8337-a230d9874d4b.png)
![image](https://user-images.githubusercontent.com/18098208/57682643-30be6980-762a-11e9-83f5-a0d9286d505b.png)
But setting it to transparent doesn’t work, it stays white
![image](https://user-images.githubusercontent.com/18098208/57682656-34ea8700-762a-11e9-93f8-1d0dbd6f49c4.png)
![image](https://user-images.githubusercontent.com/18098208/57682661-374ce100-762a-11e9-85ed-0979c625fa1b.png)

**Expected behavior:**
I expected the footer itself to be transparent and the components on it to stay visible

**Steps to reproduce:**
Just create a footer, try setting it's background-color to red and see it working, and then try setting it to transparent and it'll be white.

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\SCuragau\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! Translucency is not enabled for Material Design as there is nothing that calls for it in the spec. Are you testing this with Material Design-style elements or iOS-style elements?

Thanks!

**Comment by SanduCuragau** [comment]
Cheers,
This is what I currently have raw without any attempts of making it transparent
![image](https://user-images.githubusercontent.com/18098208/57701749-8445ad00-7654-11e9-8c54-4c0fbf478c59.png)
If I understand your question correctly, then I've tested both options and making it transparent hasn't worked on neither, I thought it totally was possible tho, but giving it color works fine
Alright if there's no way to do this then I guess thread is over, thanks for the reply

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the follow up. When running on an iOS device/Safari, translucency should work regardless of component color. I created a CodePen here: https://codepen.io/liamdebeasi/pen/LobXZX?&ionic:mode=ios

You will need to view this on iOS/Safari (Chrome does not support `backdrop-filter` without any flags yet).

Does this answer your question?
Thanks!

**Comment by SanduCuragau** [comment]
Yeah one last question, will footer's translucency ever work for android and chrome? (in the future)

**Comment by liamdebeasi** [comment]
We would be open to discussing exposing the `backdrop-filter` value as a CSS variable in the future. However, that would could only really happen once Chrome supports it out of the box.

I am going to close this as this issue is resolved. Thanks for using Ionic!
