### ISSUE TITLE
bug: deploying installs & launches app but doesn’t create launcher on android

### ISSUE THREAD

**Issue by SanduCuragau** [ionic-team/ionic#18276]
# Bug Report

**Ionic version:**
[x] **4.x**

**Expected behavior:**
Behaviour I used to have for the past month and a half developing in ionic:
-> Plug my phone to the PC
-> Make sure it’s connected and working using adb devices
-> Start developing something
-> Deciding it’s time to test it
-> Deploy the app to the phone by using: ionic cordova run android --target
-> If the app was installed, it would update, if it wasn’t, it would be installed, and stay installed even after closing it, I could open it up again using the launcher if I ever wanted to, it would be literally installed as any other app
-> Whenever I made big alterations to the sqlite local database such as creating new tables I’d completely wipe it's data and uninstall the app, since updating it created conflicts, and deployed again clean
-> Everything worked, happy dev

**Current behavior:**
Behaviour now:
-> I deploy using: ionic cordova run android --target
-> I’m watching the terminal
-> I see app building logs
-> I see app deployment logs
-> app opens up on my phone
-> app works PERFECTLY
-> going to settings -> installed apps, app is there
-> when I go to my home menu, app is no where to be found, I go and even search for it by name, nothing, apparently it is installed but something is going on and not creating the launcher

**Steps to reproduce:**
I don't know what caused this to start happening, but it is happening and I don't know how to reproduce it, or how to stop it from happening to me, it's driving me crazy, I close the app by mistake and then I have to deploy again just to open it up.

Any ideas what could be causing this bug? This is somewhat tolerable when I’m on my pc working since I can open the app by deploying it again, but when I’m not near my computer I literally have no way to open up the app
Here's the app installed
![image](https://user-images.githubusercontent.com/18098208/57709776-86fbce80-7663-11e9-837a-049781b14a82.png)

**Ionic info:**
```
   ionic (Ionic CLI)             : 4.12.0 (C:\Users\SCuragau\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. I am going to close this as this is not an Ionic issue. 

For help with Cordova issues, feel free to post on our [forum](https://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com).

Thanks!
