### ISSUE TITLE
bug: version 4.4.0 breaks our custom stencil 0.18.1 web components.

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#18270]
# Bug Report

We have created several web components with stencil js **0.18.1** which we consumes in our ionic app.
After upgrading to ionic **4.4.0** we have an issue with our components.
Some webcomponents are not hydrated anymore.

Have a look to component` lan-iot-widget,` it has now class hydrated and so lan-drag and subcomponents are hidden.

Downgrade to **4.3.0** resolve the problem again

![image](https://user-images.githubusercontent.com/3778892/57631997-d6c59180-75a0-11e9-87e0-86c9dfebcf4a.png)

We have the same problem in our stencil tests if we load latest dist from unpk.

What can we do to help to debug the bug?

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm not really sure how the core components would break your custom components as we haven't had any dependency updates. Is there a project you could share with us to reproduce this?

**Comment by mburger81** [comment]
I can understand your point. In future we would like to make our stencil web components open source but still we are not ready to share them. 

We have 4 main projects
a) stencil dnd components
b) stencil public components
c) stencil private components
d) stencil masonry dashboard component

All loads ionic in index.html to simulate an ionic app. 
All projects have a strange behavior using 4.4 and no problems using 4.3

I have to check if I can reproduce it in a simple proj I can share with you. 

But what we have figuret out in one of the problems, is that some stencil components does are not hydrated. 

So I would like to make a question if I can, who is adding this classes? Ionic core or who?

**Comment by brandyscarney** [comment]
Stencil is adding the hydrated classes which is why I am not sure how Ionic would interfere with that. You can see a full list of every file that changed in 4.4.0 here: https://github.com/ionic-team/ionic/pull/18223/files
