### ISSUE TITLE
feat: ion-input property to select the text in the input on focus

### ISSUE THREAD

**Issue by Kernolsie** [ionic-team/ionic#18282]
# Feature Request

**Ionic version:**
4.10.3 cli

**Describe the Feature Request**
I need a property on ion-input that would autoselect (and thus highlight) the text/number in the input when you click on the input so you can edit the value straight away. Note however that the options (like in Android: copy, select all etc.) should not come up as they would normally when you long-press a text/number value.

**Describe Preferred Solution**
A property autoselect() needs to be added to ion-input. I do NOT mean autofocus(). Text copy options should also not be shown.

**Related Code**
In Ionic **3** I used to do it like this:
html:
<ion-input  type='tel' [(ngModel)]='unit.noUnits' (ionFocus)='selectValueInside($event)'>
ts:
selectValueInside(event) { event.srcElement.select(); }

Now in Ionic **4** the closest I have come is to use this [because the select() method does not exist in the same places it did in Ionic3]:
event.srcElement.children[0].select();
This selects the text of the input but it also brings up the options of what to do with the selected text and that is unwanted

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the feature request. I am going to close this as this functionality already exists.

On input focus, developers can call the `getInputElement` method on the `ion-input` and then call `select()` on it. For more info, please see the [ion-input Documentation](https://ionicframework.com/docs/api/input#methods).

Thanks!
