### ISSUE TITLE
bug: Ion-Refresher displays the page underneath when swiping down

### ISSUE THREAD

**Issue by uncvrd** [ionic-team/ionic#18284]
# Bug Report

**Ionic version:**

[x] **4.1.0**

**Current behavior:**

(Text explanation is a bit confusing, I added a video demonstrating the issue below) 

While on iOS, if I route to a page, swipe to go back to the home page, but cancel my gesture halfway and try to swipe down to refresh the content on the page, the page underneath my current content is shown. Here's a quick video displaying the problem. 

Video here: https://streamable.com/g52na

**steps taken in video above**
1. Route to details page
2. Swipe down to refresh, no problem
3. Try partial swipe to go back to the home page, but don't go all the way
4. I try to swipe down to refresh and now see the home page content where the refresher is being pulled from.

**Expected behavior:**

I don't expect to see previous page content when swiping down from a refresh. 

**Steps to reproduce:**

This can be replicated using my sample repo: https://github.com/uncvrd/ion-refresher-bug

Please build on iOS using: 

`ionic cordova platform add ios` and `ionic cordova build ios --prod`

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 6 other plugins)

System:

   ios-sim : 7.0.0
   NodeJS  : v10.15.3 (/usr/local/bin/node)
   npm     : 6.4.1
   OS      : macOS Mojave
   Xcode   : Xcode 10.2.1 Build version 10E1001
```

**Comment by dromedaryCase** [comment]
This is what you can do to 'fix' this:

```
.ios ion-content {
  background: white;
  z-index: 0;
}
```

As far as I understand the issue, the problem has two components:

1) `ion-content` has no background. So if a page in the view stack is behind the active page after a cancelled edge swipe it peeks through when you pull down the refresher. But setting the background alone is not enough.
2) During the edge swipe gesture the `ion-content` is 'lifted' up by a translateZ(0px) transform effect. This translateZ(0px) is still lingering on the `ion-content` when the edge swipe is cancelled, which leads to this weird cosmetic bug.

So if you just set the background for `ion-content` and ignore the z-index, the refresher content is only visible if you cancel the edge swipe gesture. If you set the z-index of `ion-content` to 0 from the beginning, everything behaves ok. Setting the z-index is like applying transform: translateZ(0px). In fact it works just the same as a fix.

**Comment by uncvrd** [comment]
@dromedaryCase thanks for the quick workaround, I'll test to see if this fixes my "freezing" issue too. I am interested to hear what the Ionic team will do for an official fix

**Comment by uncvrd** [comment]
Just continuing here, but I was able to trigger the page "freezing" shown in the second video link for the first time, without swiping away from the app. I simply "half-swiped" the gesture as displayed in my first video link. Thus confirming my suspicion that these two issues were related and belonged under one ticket!
