### ISSUE TITLE
bug: Navigating back too quickly causes page to stop being updated

### ISSUE THREAD

**Issue by matthewspencerboxuk** [ionic-team/ionic#18293]
# Bug Report

**Ionic version:**

[x] **4.12.0**

**Current behavior:**

When pressing the back button too quickly through the navigation stack, this causes the parent tab's view to stop updating when bound properties change. This seems to happen when the previous back animation hasn't fully finished before pressing the back button again.

An example of expected behaviour when not navigating too quickly:
![May-16-2019 23-59-41](https://user-images.githubusercontent.com/33422729/57892859-8ff1c900-7838-11e9-897a-cf1c40799ca3.gif)
As you can see after navigating back to the parent tab the page text is still updated when changing segment.

An example of the page text not being updated after navigating too quickly:
![May-16-2019 23-58-44](https://user-images.githubusercontent.com/33422729/57892898-b152b500-7838-11e9-9ca1-1875347b95d8.gif)

I've been able to reproduce this issue in the browser as well as on iOS and Android devices.

**Expected behavior:**

That the parent tab's view will be updated by changes to properties it is bound to.

**Steps to reproduce:**

1. Select the segments and see the text on the page be updated
2. Click the "Go to child 1" button
3. Click the "Go the child 2" button
4. Select the back button quickly navigating back to the parent tab
5. Select the segments and the text on the page will not be updated

**Related code:**

https://github.com/matthewspencerboxuk/ionic-segment-demo

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI) : 4.12.0

System:

   NodeJS : v8.15.0
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by taipeiwu** [comment]
+1

**Comment by liamdebeasi** [comment]
Thanks for the issue! This has been resolved via https://github.com/ionic-team/ionic/pull/18299 and will be in the next release of Ionic.

In the meantime, I have created a nightly build if people would like to test it out and provide feedback. (`npm i @ionic/angular@dev`).

Thanks!
