### ISSUE TITLE
bug: @ionic/react hot reload not work

### ISSUE THREAD

**Issue by NaccOll** [ionic-team/ionic#18301]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

@ionic/react can not work with hot-reload due to undefined behavior in `IonTabs`. 

![image](https://user-images.githubusercontent.com/26819913/57966458-bf155100-7984-11e9-82f4-56b3bcb5cfc3.png)
![image](https://user-images.githubusercontent.com/26819913/57966459-c177ab00-7984-11e9-8f3f-235e7b44b424.png)
![image](https://user-images.githubusercontent.com/26819913/57966462-c4729b80-7984-11e9-9bbd-8d24e1e29bcf.png)

**Expected behavior:**

@ionic/react can work with hot-reload

**Steps to reproduce:**

example https://github.com/NaccOll/ionic-react-conference-app/tree/try-hot-reload

```
git clone -b try-hot-reload https://github.com/NaccOll/ionic-react-conference-app
cd ionic-react-conference-app
npm install
npm start
```

There is a error about undefined.

**Related code:**

`node_modules/@ionic/react/dist/components/navigation/IonTabs.js`

error
```javascript
        React.Children.forEach(this.props.children, child => {
            if (typeof child === 'object' && child.type === IonRouterOutlet) {
                outlet = child;
            }
            if (typeof child === 'object' && child.type === IonTabBar) {
                tabBar = child;
            }
        });
```

normal
```javascript
        React.Children.forEach(this.props.children, child => {
            if (typeof child === 'object' && child.type.displayName === IonRouterOutlet.displayName) {
                outlet = child;
            }
            if (typeof child === 'object' && child.type.displayName === IonTabBar.displayName) {
                tabBar = child;
            }
        });
```

**Other information:**

A pull request that attempts to fix. #18296

**Comment by elylucas** [comment]
Closing this issue as its old on a pre-beta version of Ionic/React. If the problem still persists on the latest version, please create a new issue and link this one for reference.
