### ISSUE TITLE
bug: Ionic routing within tabs to a different outlet causes a lot of issues 

### ISSUE THREAD

**Issue by rizzla22** [ionic-team/ionic#18303]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Navigating to pages not within the tabs group causes issues such as the transition is not smooth, the back button is either missing or will skip and intermediary page to go back to the main tabs page

**Expected behavior:**
A user visits a tab, clicks a link which opens a page outside of the tab group.
Then click another link in that page and goes to a child page. navigation should be smooth and animated forward/back and should not skip pages

**Steps to reproduce:**
app.routing.ts
```import { NgModule } from '@angular/core';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';

  
const routes: Routes = [
{ path: '', redirectTo: 'tab', pathMatch: 'full' },
{ path: 'tab',  loadChildren: "./pages/tabs/tabs.module#TabsPageModule"  },
{ path: 'account',  loadChildren: "./pages/secondary/account-settings/account-settings.module#AccountSettingsPageModule"  },
];

@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
  ],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

tabs.routing.ts
```
import { ErrorHandler, NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { TabsPage } from '@pages/tabs/tabs.page';
import { HomePageModule } from "@pages/tabs/home/home.module";
import { InterestsPageModule } from "@pages/tabs/interests/interests.module";

const routes: Routes = [
  {
    path: '',
    component: TabsPage,
    children: [{
        path: 'home',
        children: [{ path: '', loadChildren: () => HomePageModule }]
      }, {
        path: 'interests',
        children: [{ path: '', loadChildren: () => InterestsPageModule }]
      },            
      { path: '', redirectTo: '/tab/home', pathMatch: 'full' }
    ]}, 
    { path: '', redirectTo: '/tab/home', pathMatch: 'full' }
];


@NgModule({
  imports: [
    RouterModule.forChild(routes)
  ],
 providers: [],  
  exports: [RouterModule]
})
export class TabsPageRoutingModule {}
```

account.routing.ts
```import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { AccountSettingsPage } from './account-settings.page';


const routes: Routes = [
  {
    path: '',
    component: AccountSettingsPage,
    children: [{
        path: 'personal',
        children: [{ path: '', loadChildren: './personal-info/personal-info.module#PersonalInfoPageModule' }]
      },
      { path: '', redirectTo: '/account', pathMatch: 'full' }
    ]}, 
    { path: '', redirectTo: '/account', pathMatch: 'full' }
];


@NgModule({
  imports: [
    RouterModule.forChild(routes)
  ],
 providers: [],  
  exports: [RouterModule]
})
export class AccountPageRoutingModule {}
```

main account settings page has its own router-outlet, its the only way i could get its child page to display, otherwise the url would change but nothing woudl display - is this the right way to to do this ? there is also a router-outlet in app.component.ts and I think the tabs are doing this behind the scenes.
```

<ion-content>
    <router-outlet></router-outlet>

        <ion-item class="o-linkList__item" routerLink="personal" routerDirection="root">
            <ion-icon slot="start" name="sunny"></ion-icon>
          <ion-label>
            internal page with issue
          </ion-label>    
        </ion-item> 
</ion-content>
```

I see a lot of stuff about named outlets including that they are not necessary anymore with the latest angular (Im running very latest) 5.6.0 should i be using them in order to open a subset of pages with an ionic tab page ?

If you need anything else let me know, also would appreciate if you can tell me if this is a known issue with Ionic as ive come across some other posts saying it is

**Comment by rizzla22** [comment]
It makes sense that in an app there is a core group of tab pages which might be related, but they you should be able to navigate to pages that might not be related to the main tab page like for instance a user settings page by clicking a thumbnail in the header toolbar. I should be able to click this and be directed to the account settings module (which is separate to the generic tabs) and have its pages lazy loaded. I should then be able to navigate between these pages and on the root page of account settings i should be able to click back and end up on the tab page I started at.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you provide the output of running `ionic info`? Also, can you provide a repository with the code required to reproduce this issue?

Thanks!
