### ISSUE TITLE
bug: Unable to set ARIA role to 'navigation' on menu component

### ISSUE THREAD

**Issue by amymarsh4work** [ionic-team/ionic#18318]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
I’m working on a new Ionic 4 app that is based on the sidemenu starter template. We have members on the team that specialize in UX and accessibility, and my app was recently tested and I got some feedback. 

It was pointed out that the component used for the left pane (ion-menu) has an ARIA landmark role of ‘complementary’, and that this would mislead users of screen-readers. They would likely assume that section of the app is informative, yet non-essential content about the current page, which it is not - its function is navigation and critical for usage of the app as a whole. 

I was asked to change the ARIA role from ‘complementary’ to ‘navigation’ which accurately reflects the functionality. As you can see from my [repo app](https://stackblitz.com/edit/ionic4-angular6-sidemenu-starter-tny9ue?file=src%2Fapp%2Fapp.component.html) on Stackblitz, I was unable to do so. When adding role=“navigation” to ion-menu, it simply gets overwritten to role=“complementary”.

**Expected behavior:**
Adding ARIA landmark roles to ion-menu would be unnecessary; it would already have the most appropriate role for a component intended to be used as a navigation drawer : 'navigation'.

**Steps to reproduce:**
Add an ARIA role="navigation" to an ion-menu component. It will be overwritten with the "complementary" role.

**Related code:**
[Repo app on StackBlitz](https://stackblitz.com/edit/ionic4-angular6-sidemenu-starter-tny9ue?file=src%2Fapp%2Fapp.component.html)

**Other information:**
Proposed Solution: 
Changing the ARIA role from ‘complementary' to ‘navigation’ would improve the implementation by accurately reflecting the component’s intended purpose. Another option would be to remove the ARIA role completely, and let the developer add which ever role they choose. My personal preference leans toward the former. The reasoning behind this is that the fundamental purpose of an ion-menu is for navigation. This is supported by the [Ionic documentation](https://ionicframework.com/docs/api/menu): “The Menu component is a navigation drawer…” and the [Material Guidelines](https://material.io/design/components/navigation-drawer.html): “Navigation drawers provide access to destinations in your app”.

I’m interested in submitting a pull request that fixes this issue by making the proposed change. I’ve searched the Ionic GitHub repo for an existing open or closed issue, and have found none. This will be my first time contributing.

**Ionic info:**
Ionic:
   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

System:
   NodeJS : v8.9.4 (/usr/local/bin/node)
   npm    : 6.5.0
   OS     : macOS Mojave

**Comment by amymarsh4work** [comment]
It might also be helpful to see an example of a use-case for using the ARIA role of "complementary". Here's a write-up and demo: [Using ARIA Landmarks](https://accessibility.oit.ncsu.edu/using-aria-landmarks-a-demonstration/)

**Comment by amymarsh4work** [comment]
I've submitted a PR fix for this issue: https://github.com/ionic-team/ionic/pull/18330

**Comment by brandyscarney** [comment]
Thank you for the detailed issue and the PR! I have merged your PR in and it should make it into our `4.6.0` release. 🙂
