### ISSUE TITLE
bug: Clear fill setting does not show icons in toolbar buttons.

### ISSUE THREAD

**Issue by Eraldo** [ionic-team/ionic#18329]
# Bug Report

**Ionic version:**

[x] **4.4.1-dev.201905212016.fb63a6f**

**Current behavior:**

The icon is not visible. Only the button text is shown.

**Expected behavior:**

The icon and the text of the button are shown.

**Steps to reproduce:**

Look at code below with same version of ionic as stated above.

**Related code:**

```
<ion-toolbar>
  <ion-buttons slot="secondary">
    <ion-button fill="clear">
      <ion-icon slot="start" name="contact"></ion-icon>
      Contact
    </ion-button>
  </ion-buttons>
</ion-toolbar>
```

**Other information:**

I noticed this issue as a side-effect of upgrading to the new nightly build to fix #16834
After some inspection I figured out that in this new version the `icon-only` buttons got a fixed height and width. This seems to have to do with this issue.

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.1-dev.201905212016.fb63a6f
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v11.0.0 (/usr/local/Cellar/node/11.0.0/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by brandyscarney** [comment]
Thanks for the issue! I am not able to reproduce this with the code provided. Could you please provide some code I can use to reproduce? https://codepen.io/brandyscarney/pen/YbYVMo

**Comment by brandyscarney** [comment]
Nevermind I was able to reproduce this using a setTimeout on the button text, thanks! Will have a fix in soon.

**Comment by Eraldo** [comment]
Awesome @brandyscarney. I confirm everything working and looking pretty too: Sweeeet!
Thank's for digging into it and fixing it so quickly.
