### ISSUE TITLE
bug: ion-card[button] white space at bottom of button cards

### ISSUE THREAD

**Issue by studioromeo** [ionic-team/ionic#18327]
# Bug Report

**Ionic version:**
[x] **4.4**

**Current behavior:**
When the `<ion-card button>` element has a button attribute it adds a `<button>` element around the cards contents. On Chrome (and possibly other browsers) buttons are displayed inline and this causes the `<button>` element to not fill the `<ion-card>` element as it honours the white space between the `<button>` and closing `</ion-card>` tag. This is most noticeable when we place an image as the cards contents as we'll see a blank line before the end of the card (see below for an example)

<img width="332" alt="Screenshot 2019-05-21 at 22 30 54" src="https://user-images.githubusercontent.com/846587/58132236-ade47280-7c18-11e9-8422-8d84a333edc7.png">

**Expected behavior:**
Setting the display property of the `<button>` element to `block` ensures the `<button>` fills the available space and ignores any white space between the tags.

<img width="335" alt="Screenshot 2019-05-21 at 22 31 04" src="https://user-images.githubusercontent.com/846587/58132399-1895ae00-7c19-11e9-9100-0302ed4c12a8.png">

**Steps to reproduce:**
Using the below code we should see the issue described

```html
<ion-card button>
  <img src="...">
</ion-card>
```

**Other information:**
Pull request: https://github.com/ionic-team/ionic/pull/18328

Thanks!

**Comment by liamdebeasi** [comment]
Hi there,

This issue has been resolved via https://github.com/ionic-team/ionic/pull/18328 and will be in the next release of Ionic.

Thanks!
