### ISSUE TITLE
bug: ERR_CLEARTEXT_NOT_PERMITTED livereload Android api 28

### ISSUE THREAD

**Issue by clickdaily** [ionic-team/ionic#18322]
# Bug Report

**Ionic version:**
[x] **4.12.0**

**Android API version**
28 (Android 9.0)

**Cordova Version**
9.0.0

**Current behavior:**
the command `ionic cordova run android -l` deploys on my emulator but I have an alert :
```
Application Error
net::ERR_CLEARTEXT_NOT_PERMITTED
(http://192.168.1.132:8100)
```
and the application does not launch

If I deploy without the livereload option, it works fine

**Expected behavior:**
No error 

**Steps to reproduce:**
- create a new blank app
- try to deploy it with livereload option on an emulator with Android 9.0

```
ionic cordova run android -l
```

**Other information:**
I have already tried to add the attribut android:usesCleartextTraffic="true"  to the <application> tag in the config.xml (and it apears in the manifest.xml) but it did not fix my problem

Also tried to add 
<domain>192.168.1.132</domain> 
to the network_security_config.xml but the file is overwritten so I can not say if it would work

=> Maybe the tag <domain>LOCAL_IP</domain> could be added to the `network_security_config.xml` durring build

**Ionic info:**
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\Jérôme\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 4 other plugins)

System:

   NodeJS : v12.2.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

![Capture](https://user-images.githubusercontent.com/4943249/58123471-e2850980-7bd9-11e9-9593-b0b701569bb9.JPG)

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. I am going to close this as this is not an Ionic issue. Ionic Framework does not deal with the webview when running in-app. This is most likely a configuration issue or an issue with the ionic webview plugin (which [is a different repo](https://github.com/ionic-team/cordova-plugin-ionic-webview)).

For further help debugging this issue, feel free to post on our [forum](https://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com).

Thanks for using Ionic!
