### ISSUE TITLE
bug: Ionic 4 content does not scroll when you add press gesture

### ISSUE THREAD

**Issue by flybabynuonuo** [ionic-team/ionic#18335]
# Ionic 4 content does not scroll when you add press gesture

This does not work....scrolling fails

```
<ion-item *ngFor="let list of lists"  (press)="functiona()">
```

This works fine

```
<ion-item *ngFor="let list of lists">
```

**Comment by remisture** [comment]
+1

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Is `press` a HammerJS functionality? If so, HammerJS has been known to intercept certain events and not let them propagate.

**Comment by nicolasrhone** [comment]
This is definitely a HammerJS problem... It can be easily solved by adding  [style.touch-action]="'pan-y'" at the element with (press)
Ex:  
`<ion-item *ngFor="let list of lists"  (press)="functiona()" [style.touch-action]="'pan-y'">`

**Comment by flybabynuonuo** [comment]
> This is definitely a HammerJS problem... It can be easily solved by adding [style.touch-action]="'pan-y'" at the element with (press)
> Ex:
> `<ion-item *ngFor="let list of lists" (press)="functiona()" [style.touch-action]="'pan-y'">`

thank you

**Comment by liamdebeasi** [comment]
Thanks for the workaround, @nicolasrhone!

I am going to close this as this is not an Ionic issue. Thanks!
