### ISSUE TITLE
bug: ion-toggle md bug

### ISSUE THREAD

**Issue by hhasenauer** [ionic-team/ionic#18337]
# Bug Report

**Ionic version:**

[x] **4.1.1**

**Current behavior:**
When the toggle button is toggled it correctly changes the color but only moves to a middle state and not completely to the right.

This behaviour only happens for mode="md"
![image](https://user-images.githubusercontent.com/16212806/58155333-f3825900-7c73-11e9-9782-b35651d6a712.png)

**Expected behavior:**

The toggle button moves completely to the right when toggled.
![image](https://user-images.githubusercontent.com/16212806/58155476-3cd2a880-7c74-11e9-8962-6d8b4e6bc2bb.png)

**Steps to reproduce:**
Make an empty application with a default ion-toggle control

**Related code:**

```
<ion-content>
  <ion-toggle></ion-toggle>
</ion-content>
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. I am not seeing this happen with `ion-toggle`. Can you provide a repository with the code required to reproduce this issue? Thanks!

**Comment by hhasenauer** [comment]
@liamdebeasi Sorry can be closed. Was a error in a global .css file.
