### ISSUE TITLE
bug: .ion-hide-md-down has wrong max-width value

### ISSUE THREAD

**Issue by bvamos** [ionic-team/ionic#18341]
# Bug Report

**Ionic version:**
[x] **4.4.0**

**Current behavior:**
.ion-hide-md-down has wrong max-width value:

`@media (max-width: 991px)
.ion-hide-md-down {
    display: none !important;
}`

**Expected behavior:**
Documentation says: 
Applies the modifier to the element when min-width: 768px (up) or max-width: 768px (down).

**Steps to reproduce:**
Add css class ion-hide-md-down to an element.

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\user\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

**Comment by brandyscarney** [comment]
Thanks for the issue! This is actually the correct code but it is a documentation issue. We have an issue to fix this here: https://github.com/ionic-team/ionic-docs/issues/616
