### ISSUE TITLE
bug: ionicons don't respect platform

### ISSUE THREAD

**Issue by corysmc** [ionic-team/ionic#18355]
# Bug Report

**Ionic version:**
[x] **4.5.0-dev.201905212141.24e9cf0**

**Current behavior:**
Ionicons only show md style of icons. All other styles work correctly. 

**Expected behavior:**
On iOS ionicons should be iOS

**Steps to reproduce:**

1. npm init stencil
2. update to latest stencil
3. update to latest ionic@one
4. Add `<ion-icon name="share" />` to home page
5. emulate iOS

Notice buttons are rendering iOS, but icon is still showing android share icon.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Are you trying this with the latest stable version of Ionic? The `ionic@one` tag is still under development.

Thanks!

**Comment by corysmc** [comment]
Nope, version:  `4.5.0-dev.201905212141.24e9cf0` when I filed this... but still exists on version `^4.5.0-dev.201905231138.1ad37d1`. @mhartington said to still file an issue even though it was under development.

**Comment by brandyscarney** [comment]
Thanks Cory! Just to be clear, this is only happening on the `@ionic/one` builds, not the `dev` or `latest` builds?

**Comment by rafamel** [comment]
Hi, just my 2 cents. I'm seeing this happen on @beta too (@5.0.0-beta.3).

**Comment by brandyscarney** [comment]
Hi @rafamel, which package are you referring to?

**Comment by rafamel** [comment]
Hi there, sorry about this, I hadn't been thorough enough. [My issue is probably not the same.](https://github.com/ionic-team/ionic-cli/issues/3989)

**Comment by brandyscarney** [comment]
Oh okay! So you're talking about the CLI version. Yeah this issue is likely caused by the Ionic Framework or Stencil. 🙂

**Comment by corysmc** [comment]
That's correct @brandyscarney I'm referring to the `ionic/core@one` builds

**Comment by brandyscarney** [comment]
Thanks @corysmc. Ping @manucorporat

**Comment by brandyscarney** [comment]
Thanks @corysmc. Deleted my last comment, I forgot Adam said he was working on this earlier in Stencil. 🙂

**Comment by corysmc** [comment]
Fixed in 4.6.0-dev.201906131724.645b9a9 (probably sooner)
