### ISSUE TITLE
bug: ionic themes website

### ISSUE THREAD

**Issue by hooloom** [ionic-team/ionic#18353]
Your website: https://market.ionicframework.com/themes
keeps crashing - you are having problems with heroku.  Not a good look for your organization.

**Comment by liamdebeasi** [comment]
Hi there,

I am going to close this as this is repo is for issues regarding the framework itself, not the Ionic website. I will pass along your feedback regarding the marketplace website.

Thanks!

**Comment by hooloom** [comment]
No worries
