### ISSUE TITLE
feat: There should and  selected="true" parameter on ion-tab-button which selects default tab

### ISSUE THREAD

**Issue by ayoubkhan558** [ionic-team/ionic#18360]
# Feature Request

**Ionic version:**
version: 4.*

**Describe the Feature Request**
`<ion-tabs>
    <ion-tab-bar slot="top" color="light">
      <ion-tab-button tab="tab1"> 
        <ion-label [innerHTML]="item.title"></ion-label>
      </ion-tab-button>
      <ion-tab-button tab="tab2" **_### selected="true"_**>
        <ion-label> static </ion-label>
      </ion-tab-button>
    </ion-tab-bar>
  </ion-tabs>`

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the feature request. I am going to close this as this functionality already exists in the framework. Please see the `selectedTab` property on `ion-tab-bar` for more info: https://ionicframework.com/docs/api/tab-bar#properties

Thanks for using Ionic!
