### ISSUE TITLE
feat: disable scroll on ion-content

### ISSUE THREAD

**Issue by gnesher** [ionic-team/ionic#18362]
feture Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
<ion-content> automatically adds an inner-scroll div which is often not necessary / painful.
The common solution to this is to use CSS to hide the unnecessary div (for example https://forum.ionicframework.com/t/how-to-disable-scrollbars-on-ion-content-in-ionic-4/142266/2) which I don't think is an acceptable solution.

**Describe Preferred Solution**
A flag that will be passed to ion-content to disable scrolling. I believe it was present in Ionic 1

**Describe Alternatives**
It's also possible to have two types of containers - scroll-able / static

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the feature request! Would something like the `fixed` slot in `ion-content` work for you?

I created a CodePen here: https://codepen.io/liamdebeasi/pen/pmaWBN
Additional documentation here: https://ionicframework.com/docs/api/content#slots
