### ISSUE TITLE
Datetime min/max minute field not updated

### ISSUE THREAD

**Issue by dkrahn** [ionic-team/ionic#18370]
# Bug Report
Datetime with `min` value to now with date and time. When you change the date part, it updates the hour and minute fields, but changing the hour does not update the minute field.

**Ionic version:**
[x] **4.x**

**Current behavior:**
When you change the hour field, the minute field does not get updated(cannot select before/after now).

**Expected behavior:**
When you change the hour field, the minute field should get updated to allow all values.

**Steps to reproduce:**
1. Insert a datetime component with min/max value as in the related code
3. Change the hours field

**Related code:**
```
<ion-datetime placeholder="Date" display-format="DD/MM/YYYY HH:mm" [value]="'2019-05-23T14:34'" [min]="'2019-05-23T14:34'" [max]="'2020-05-23T14:34'"></ion-datetime>
```

**Other information:**

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v8.11.4
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This has been resolved via https://github.com/ionic-team/ionic/pull/18380 and will be in the next release of Ionic.

Thanks!
