### ISSUE TITLE
bug: Unknown Error after compiling the application

### ISSUE THREAD

**Issue by josuelmm** [ionic-team/ionic#18376]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

Good day. I have an error in HttpClient after compiling the application.
When entering the apk it works perfect, but I give login or register does not progress. I was able to extract the error back and the following comes out:
{"header": {"normalizedNames": {}, "lazyUpdate": null, "headers": {}}}, "status": 0, "statusText": "unknown error", "url": "MY_URL_API" , "ok": false, "name": HttpErrorResponse "," message ":" Http failure response for MY_URL_API: 0 Unknown Error "," error ": {" isTrusted ": true}}

It should be noted that running ionic serve everything works perfect.

**Expected behavior:**
That works the same as it works in the browser.

**Steps to reproduce:**
The problem is based on the fact that the post, get requests do them perfectly in the browser, but when compiling the app and executing it, it does not perform the actions.

**Related code:**

```
login(email: String, password: String) {
    const headers = new HttpHeaders({
      'Accept': 'application/json'
    });

    return this.http.post(this.env.API_URL + 'auth/login',
      {email: email, password: password}, { headers: headers }
    ).pipe(
      tap(token => {
        this.nativeStorage.setItem('token', token)
        .then(
          () => {
            console.log('Token Stored');
          },
          error => console.error('Error storing item', error)
        );
        this.token = token;
        this.isLoggedIn = true;
        return token;
      }),
    );
  }
```
The problem is that it always returns the following error, but only when running the app on the cell phone or emulator.

{"header": {"normalizedNames": {}, "lazyUpdate": null, "headers": {}}}, "status": 0, "statusText": "unknown error", "url": "MY_URL_API" , "ok": false, "name": HttpErrorResponse "," message ":" Http failure response for MY_URL_API: 0 Unknown Error "," error ": {" isTrusted ": true}}

### **With Error**
<img src="https://camo.githubusercontent.com/b80df4e6804a306defe136a743d63e437138de4d/68747470733a2f2f692e696d6775722e636f6d2f4d4459474251752e706e67">

### **Without Error**
<img src="https://camo.githubusercontent.com/8f4a53ae0abf23e445638b6552cbfcadd300c4ee/68747470733a2f2f692e696d6775722e636f6d2f676b4b6b514a652e706e67">

**Comment by KillerCodeMonkey** [comment]
Status Code 0 without any details indicates a cors or some similar problem

https://github.com/angular/angular/issues/22022

I see you are trying to send requests to to a non ssl-endpoint, so i think the app blocks unsafe connections.

Check if it works when adding the cordova-whitelist-plugin and allow requests to your endpoint.
https://github.com/apache/cordova-plugin-whitelist#network-request-whitelist

**Comment by josuelmm** [comment]
All the configuration is correct, I just realized that the problem is presented when running on Android 9.0, in Android versions inferior mail bien.todo without problems.

**Comment by josuelmm** [comment]
**I just found the solution here:**
https://stackoverflow.com/questions/51902629/how-to-allow-all-network-connection-types-http-and-https-in-android-9-pie

I hope this post is not forgotten.
Inside the **AndroidManifest.xml** add the android **tag: usesCleartextTraffic = "true"**

<application
    android: usesCleartextTraffic = "true"
    .
    .
    .>

**Comment by KillerCodeMonkey** [comment]
Thanks for sharing the solution!

> I hope this post is not forgotten.

You and that post will live on in our hearts :D

**Comment by josuelmm** [comment]
Nice, for the rest of eternity.
