### ISSUE TITLE
bug: Rxjs MergeMap not respecting concurency limit

### ISSUE THREAD

**Issue by blemaire** [ionic-team/ionic#18385]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I created logic to limit the number of concurent observables using the MergeMap rxjs operator (with the concurency limit): http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-mergeMap
This is working fine on browsers (event mobile browsers), however, when build as an apk, the concurency limit is not respected.

**Expected behavior:**

RxJs operators should have the same behaviour on android apps

**Steps to reproduce:**

**Related code:**

```
from(ids).pipe(
   mergeMap(id => this.doSomething(id), 4)
);
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\Bastien\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.7
   @angular-devkit/schematics    : 7.3.7
   @angular/cli                  : 7.3.7
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 9.0.0
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (C:\Users\Bastien\AppData\Local\Android\Sdk)
   NodeJS            : v11.11.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. I am going to close this as rxjs is not something we manage. If you feel you have found a bug, I would recommend creating an issue on the rxjs github repo.

Thanks!

**Comment by blemaire** [comment]
Ok i'm not sure how they would be able to help, RxJs functions work fine before building the ionic APK but not after, seems to me the issue comes from something happening to the code when built for android?

**Comment by liamdebeasi** [comment]
Hi there,

The WebView that is used when running your Android APK can vary from device to device. It's possible that your device is using an older version of Chromium that does not support certain APIs that rxjs depends on (not all Android devices are guaranteed to be running the latest version of Chromium).

I would recommend looking at the rxjs documentation or reaching out on the Ionic (or rxjs) community forums for further assistance.

Thanks!
