### ISSUE TITLE
bug: ion-tabs not show with setRoot ion-nav vanilla

### ISSUE THREAD

**Issue by FranciscoCarbonell** [ionic-team/ionic#18397]
index.html
```
<ion-app>
<ion-nav></ion-nav>
</ion-app>
```
js
```
class TabsPage extends HTMLElement {
  async connectedCallback(){
    this.innerHTML = `
<ion-tabs>

  <ion-tab tab="tab-schedule">
    text example
  </ion-tab>

   <ion-tab-bar slot="bottom" selected-tab="tab-schedule">
    <ion-tab-button tab="tab-schedule">
      <ion-icon name="cart"></ion-icon>
      <ion-label>Productos</ion-label>
      <ion-badge>6</ion-badge>
    </ion-tab-button>

    <ion-tab-button tab="tab-speaker">
      <ion-icon name="contacts"></ion-icon>
      <ion-label>Speakers</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="tab-map">
      <ion-icon name="map"></ion-icon>
      <ion-label>Map</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="tab-about">
      <ion-icon name="information-circle"></ion-icon>
      <ion-label>About</ion-label>
    </ion-tab-button>
  </ion-tab-bar>

</ion-tabs>
    `
    const navschedule = document.getElementById('schedule')
    await navschedule.componentOnReady()
    navschedule.setRoot('tab-nav-schedule')
  }
}
async function init(){
    await nav.componentOnReady()
    nav.setRoot('app-tabs')
}
customElements.define('app-tabs',TabsPage)

document.body.onload = init
```

4.4.0 found , 4.4.1 NOT FOUND

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you please provide a full code reproduction and description of the issue you are seeing?

Thanks!

**Comment by FranciscoCarbonell** [comment]
this repository https://github.com/techiediaries/ionic-javascript-starter
not found in 4.4.1 but found in 4.4.0

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I am not seeing the issue you are describing. The tabs appears to be properly set when using `setRoot`.

Can you describe the issue you are experiencing, as well as provide steps to reproduce?

Thanks!

**Comment by FranciscoCarbonell** [comment]
Yes, the code is fine, but it does not work in version 4.4.1, but found in 4.4.0

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you try upgrading to Ionic 4.5.0 and see if you are still encountering this issue?

Thanks!

**Comment by FranciscoCarbonell** [comment]
yes, the problem persists in 4.5.0

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Are you able to reproduce this with one of the Ionic starters? Also, it looks like the repo you linked to previously was built for an Ionic 4 alpha version. A lot has changed between the Ionic 4 alphas and the release of Ionic 4.0.0, so it is likely the application itself might need an update.
