### ISSUE TITLE
feat: permanent cancel button on ion-searchbar

### ISSUE THREAD

**Issue by aballet** [ionic-team/ionic#18399]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Being able to keep the cancel button of the ion-searchbar visible, even when there's no focus on the searchbar. Comportment of the button doesn't change.

**Describe Preferred Solution**

A simple attribute would do the trick: `<ion-searchbar permanentCancelButton></ion-searchbar>`.

**Additional Context**

Use case: A user clicks on a search icon in the toolbar; the toolbar is dismissed to give space to the invoked searchbar. Now the user needs a way to go back to the previous toolbar if the searchbar is not focused.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the feature request. Can you explain your use case a bit more? I'm not sure I fully understand the benefit of having the `Cancel` button always visible even if the input is not focussed.

Thanks!

**Comment by aballet** [comment]
Sure @liamdebeasi ! Have a look at the following GIF, it's showing the latest comportment of the Facebook search bar that I was trying to reproduce. Imagine this with the actual implementation in Ionic: we click on the search icon, and end up with the expanded search bar. If the user clicks on anything but the bar, it will lose its focus, hence leaving the user with no way of getting back to the previous screen with the search icon (except clicking again on the bar to let the cancel button appear, but it's really bad in terms of UX). Hence the permanent cancel button that would be needed in that case.

![O6yKjmASymi063IR5vLngBf8KLJXYGb7ZbKYvl6S](https://user-images.githubusercontent.com/17181237/58577412-b0f9e700-8246-11e9-992f-456cdd4caf8d.gif)

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the follow up! The behavior in the GIF is actually just autofocusing the searchbar when it appears, which is why the cancel button is visible.

I am going to close this issue, but I think this functionality could be accomplished with the following feature request: https://github.com/ionic-team/ionic/issues/17745.

Thanks for using Ionic!

**Comment by aballet** [comment]
Hi @liamdebeasi, I think you closed it too soon. Let me explain:

Agreed, it is autofocus, and that's why the cancel button is visible. However, when we loose the focus (like in this new GIF, the user simply clicks on the background), the cancel button disappears, leaving the user with the search bar, but no way to come back to the other interface except clicking on the bar again, and hitting cancel.

Of course, I could also dismiss the search bar when `(ionBlur)` fires, but in my case, I'd rather not, because I want the search bar to stay until the user explicitly clicks on cancel. Hence the permanent cancel button, that stays whether the search bar is focused or not.

If you agree with me on that, my PR might also be reopened (#18401).

Here's the GIF:
![ezgif-4-2fd03612f1c4](https://user-images.githubusercontent.com/17181237/58648424-f4695980-8309-11e9-89a0-5faa833453a2.gif)

**Comment by liamdebeasi** [comment]
Ahh you're right - I misunderstood your previous explanation. Reopening! 

I will take a look at your PR shortly. 👍 Thanks for clarifying!
