### ISSUE TITLE
Can't set placement of Ionic Popover in React

### ISSUE THREAD

**Issue by J-Cat** [ionic-team/ionic#18394]
There doesn't seem to be any way to set the placement for a popover (to emulate a menu) when using in React.

**Comment by shagulameed298** [comment]
Use event like this to set the anchor of the clicked element 
 
 clickMe = (event :any) => {
        event.persist();
        this.setState((() => ({ showPopover: true,popoverEvent:event })));
     }

<IonPopover
        isOpen={this.state.showPopover} 
        event={this.state.popoverEvent} 
        onDidDismiss={() => this.setState(() => ({ showPopover: false,showBackdrop:false}))}>
      <p>This is popover content</p>
</IonPopover>

**Comment by elylucas** [comment]
Thanks, @shagulameed298, that is the recommended way to position the popover. @J-Cat take a look at that and if it doesn't work for you let us know.
