### ISSUE TITLE
Error when run command ionic start project tabs/blank

### ISSUE THREAD

**Issue by tomavic** [ionic-team/ionic#18392]
# Bug Report
Error when run command ionic start project tabs/blank

Can't install nod-modules
```SyntaxError: Unexpected end of JSON input while parsing near '...e","version":"2.8.15"'```

**Ionic version:**
[x] **4.x**

**Current behavior:**
Can't install node-modules 

**Expected behavior:**
Should install node-modules and start the app

**Steps to reproduce:**
1- install ionic globally
2- run command `ionic start project tabs` or `ionic start myApp blank`

**Ionic info:**

```

Ionic:

   ionic (Ionic CLI)  : 4.12.0 (C:\Users\tomavic\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\tomavic\AppData\Local\Android\Sdk)
   NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 8.1


```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! I am going to close this as this is not something the framework manages. It sounds like there's a syntax error in the `package.json` for a dependency.

For further help debugging this issue, feel free to post on our [forum](https://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com).

Thanks!

**Comment by tomavic** [comment]
@liamdebeasi This could be from `package.json` in the template itself. Could you please help on that?

**Comment by liamdebeasi** [comment]
Hi there,

Are you able to paste the full error you are seeing?

**Comment by favourodoyo** [comment]
hello friends, i also encounter the same errors here is the full list of errors am having.
> npm.cmd i
npm ERR! Unexpected end of JSON input while parsing near '...","version":"2.8.15",'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\favour\AppData\Roaming\npm-cache\_logs\2019-06-25T18_06_11_096Z-debug.log
[ERROR] An error occurred while running subprocess npm.

        npm.cmd i exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

C:\Users\favour\myappfolder>

**Comment by favourodoyo** [comment]
$tomavic  please how do i set up package.json to stop the errors? thank you.

**Comment by tomavic** [comment]
@favourodoyo It seems that it was a problem with the template repo itself. I believe now it's working fine. You could try again. Please share your `ionic info` for more clarification 

Mine is
```cmd
Ionic:

   Ionic CLI : 5.1.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.0
   npm    : 6.9.0
   OS     : Windows 10

```

**Comment by favourodoyo** [comment]
@tomavic...mine is the same...that means i need to uninstall cordova
because am also using windows 10 with latest nodjs npm with ionic cli 5.1.0

**Comment by favourodoyo** [comment]
> npm.cmd i
npm ERR! Unexpected end of JSON input while parsing near '...b8Rvnc6VPvexeair+OD1m'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\favour\AppData\Roaming\npm-cache\_logs\2019-06-26T10_16_06_048Z-debug.log
[ERROR] An error occurred while running subprocess npm.

        npm.cmd i exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

**Comment by favourodoyo** [comment]
am still getting the errorsz
