### ISSUE TITLE
bug: React Router 5.0 breaks with "You should not use <Route> or withRouter() outside a <Router>"

### ISSUE THREAD

**Issue by mlynch** [ionic-team/ionic#18400]
# Bug Report

**Ionic version:**

[x] **4.x** (master: 292b24ad8f8ab5f0e1410586fd9af9566cc0af18)

**Current behavior:**

Use `react-router` and `react-router-dom` version `^5.0.0` and the following error will be thrown:

![image (25)](https://user-images.githubusercontent.com/11214/58506689-9ac02e00-8155-11e9-9830-4a846acc9cc8.png)

**Expected behavior:**

**Steps to reproduce:**

Clone the react conference app
`npm install react-router@^5.0.0 react-router-dom@^5.0.0`
`npm link @ionic/react`
`npm start`

**Comment by elylucas** [comment]
upcoming react beta release has been updated to react router > 5.0.0 and should resolve this issue
