### ISSUE TITLE
[Ionic-React] <IonSkeletonText /> doesn't have property 'animated'. Cannot set animation to ion-skeleton-text.

### ISSUE THREAD

**Issue by vpuonti** [ionic-team/ionic#18406]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

Cannot set `animated={true}` to `<IonSkeletonText />`. The property `width` works fine though.

**Expected behavior:**

`IonSkeletonText` should become animated.

**Steps to reproduce:**

Add  `animated={true}` to `<IonSkeletonText />`.

**Related code:**

`<IonSkeletonText width={"100%"} animated={true} />`

**Other information:**

```
"dependencies" : {
    "@ionic/core": "^4.4.2",
    "@ionic/pwa-elements": "^1.2.7",
    "@ionic/react": "0.0.5",
}
```

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI) : 4.12.0 (/home/[REDACTED]/.nvm/versions/node/v12.2.0/lib/node_modules/ionic)

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.24
   @capacitor/core           : 1.0.0-beta.24

System:

   NodeJS : v12.2.0 (/home/[REDACTED]/.nvm/versions/node/v12.2.0/bin/node)
   npm    : 6.9.0
   OS     : Linux 4.4
```

**Comment by elylucas** [comment]
This is fixed in the upcoming beta release of ionic/react, check for it soon.
