### ISSUE TITLE
bug: Modal backdrop doesn't behave like Alert backdrop

### ISSUE THREAD

**Issue by JCKodel** [ionic-team/ionic#18417]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When using Ionic on a "normal" web page, html scroll corrupts a modal (see this screenshot):
![image](https://user-images.githubusercontent.com/379339/58600169-de03c500-8259-11e9-837e-8862d3ab8bba.png)

That's caused when the user have the BODY scrolled down a bit and a modal is opened.

Alert doesn't have this behavior (i.e.: it works fine, even we are on a page where BODY is scrollable).

**Expected behavior:**

Have the same behavior on components that blocks the screen with a backdrop (either both work or both breaks).

**Steps to reproduce:**

1) Open https://www.ecopeca.com.br (the form is a Stencil web component using Ionic), the rest is Wordpress.
2) Fill the form (select a car model, type years 2019 and 2019, any number on the last box (it have a mask) and add some text using the big (+) button, then hit the big green button.
3) If you are using a 1080p monitor, you won't scroll, everything looks ok, but resize the window keeping > 1200px on width and a bit of height (the scrollbar will appear). Scroll down a bit, then hit the same button.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you describe the issue you are having a bit more? I am unable to scroll even after I have resized the window in step 3.

Thanks!
