### ISSUE TITLE
feat: add prefixes and suffixes to input

### ISSUE THREAD

**Issue by FrutasLuna** [ionic-team/ionic#18429]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

It would be really nice to have the possibility of adding pre- and suffixes to input fields. This is useful for adding units to input for example.

**Describe Preferred Solution**

Here's a concrete example of what I mean: https://material.angular.io/components/form-field/overview#prefix-amp-suffix

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by IngAjVillalon** [comment]
It is an excellent idea!
Because one solution is to use masks, but it would be best if it were a native characteristic of ion-input,
that would give a better user experience!

**Comment by jaipresto** [comment]
I raised this issue not long back. The ion-item _slots_ attribute is not exactly the same as Material's suffix/prefix, but IMO it beats using mat-form-field and all that goes with it for just a single form field.

More info here: https://github.com/ionic-team/ionic/issues/18089

**Comment by IngAjVillalon** [comment]
Currently, I solve it using the slots and with details Scss:
.preffix {
    position: absolute;
    bottom: 9px;
    left: 12px;
}

.ios .preffix {
    left: 15px;
    bottom: 8px;
}

**Comment by FrutasLuna** [comment]
Thanks, @IngAjVillalon , with that I was able to solve my current problem.
