### ISSUE TITLE
bug: Ionic native-run error ERR_UNSUITABLE_API_INSTALLATION: No suitable API installation found.

### ISSUE THREAD

**Issue by lajos93** [ionic-team/ionic#18427]
# Bug Report

**Ionic version:**

[x] **5.0**

**Current behavior:**

Trying to run a blank project on Android 8 with "ionic cordova run android", during deployment I get the following error:

        ERR_UNSUITABLE_API_INSTALLATION: No suitable API installation found.
        [ERROR] An error occurred while running subprocess native-run.

        native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-d... exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

It runs fine with 

        ionic cordova build android
        

**Expected behavior:**

To run with the command "ionic cordova run android"

**Steps to reproduce:**

**Related code:**

           

```
ionic cordova run android
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```
ERR_UNSUITABLE_API_INSTALLATION: No suitable API installation found.
    [ERROR] An error occurred while running subprocess native-run.

    native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-d... exited with exit code 1.

    Re-running this command with the --verbose flag may provide more information.

**Comment by dkrahn** [comment]
Happening with me too.
It's something with update 5.0.0.

**Comment by lajos93** [comment]
Great, yes it works with ionic@4.12.0
