### ISSUE TITLE
bug: Ionic 4: this.platform.is('desktop') returns wrong value when installed apk in android 4.4.4

### ISSUE THREAD

**Issue by Topiya** [ionic-team/ionic#18421]
# Bug Report

**Ionic version:**
Ionic 4

**Current behavior:**

When I installed ionic 4 app in android 4.4.4 device and emulator, it is showing the this.platform.is('desktop') value as **true** instead of **false**. Whereas In other higher android OS version device it is showing as false.

**Expected behavior:**

this.platform.is('desktop')  should return false in android app in android 4.4.4 device.

**Related code:**

```
  constructor(public platform: Platform) {
    alert('desktop ' + this.platform.is('desktop'));
  }
```

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\user1\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 31 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\user1\AppData\Local\Android\sdk)
   NodeJS            : v10.14.2 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

Also I have tried with  ionic (Ionic CLI)   : 5.0.0 , but getting the same result.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. We are aware of inaccurate results being given for platform detection. In order to fix some of these issues breaking changes are required, so we will be fixing them in the next major release of Ionic.

I created a feature request for this update (https://github.com/ionic-team/ionic/issues/17631), so I am going to close this issue in favor of the existing one. I will be sure to link this issue so that we take your use case into consideration.

Thanks!

**Comment by Topiya** [comment]
Can you please let me know when can we expect new major release with this bug fix, because we have already made live our app with Ionic 4 and it stopped working in android 4.4.4 devices. So our end users are complaining about this. It would be great if we know how long it will take to fix this issue.
