### ISSUE TITLE
ion-textarea auto-grow="true" not working with iOS/Mac

### ISSUE THREAD

**Issue by AndreDriesel** [ionic-team/ionic#18433]
**Ionic version:**
```Ionic:

   ionic (Ionic CLI)          : 4.1.2
   Ionic Framework            : @ionic/angular 4.0.2
   @angular-devkit/core       : 7.2.4
   @angular-devkit/schematics : 7.2.4
   @angular/cli               : 7.2.4
   @ionic/ng-toolkit          : not installed
   @ionic/schematics-angular  : not installed

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   NodeJS : v10.3.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS
   Xcode  : Xcode 8.0 Build version 8A218a
```

**I'm submitting a ...** 
[x] bug report

**Current behavior:**
I tried the new feature "auto-grow" of ion-textarea and all is working fine on Win10/Ubuntu/Linux with Chrome or Opera.
But when i tried it on iOS 12 or on my Mac, it just raises the textarea to 2 rows and thats it.
More rows are not possible currently.

**Expected behavior:**
Grow the textarea as long as needed for the text.

**Steps to reproduce:**
Use auto-grow on Mac/iPhone.

**Related code:**
```
<ion-content>
  <ion-card mode="md">
    <ion-card-content>
      <ion-list lines="none">
        <ion-item>
          <ion-icon size="small" slot="start"></ion-icon>
          <ion-textarea inputmode="text" auto-grow="true"></ion-textarea>
        </ion-item>
      </ion-list>
    </ion-card-content>
  </ion-card>
</ion-content>
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! I noticed your `ionic info` says you are using Ionic 4.0.2. `auto-grow` was added in Ionic 4.4.0.

Can you update your Ionic project to use the latest version and let me know if that resolves your issue?

Thanks!
