### ISSUE TITLE
bug: Http call only work on browser

### ISSUE THREAD

**Issue by MhmdKorhani** [ionic-team/ionic#18432]
# Bug Report

**Ionic version:**
[ ] **3.x**
[x] **4.x**
[x] **5.x**

**Current behavior:**
While running the application on mobile (debug mode), http calls return error as if they are not even called.
Error: status: 0 Unknown error.

**Expected behavior:**
Sending/Receiving data should take place, i have been calling the APIs from my browser and it worked just fine.

**Related code:**
```
    this.getPetTypesSub = this.myService.API_NAME(param).subscribe((data) => {
//doSomething
 }, (error) => {
      alert(JSON.stringify(error));
    });
```
```
  API_NAME(Param): Observable<any> {
   let url = 'API_URL/API_NAME';
    const headers = new HttpHeaders({ 'Content-Type': 'application/json' });
    const options = { headers: headers };
    return this.api.post(url , JSON.stringify(Param), options)
      .pipe(map(response => {  return response.; }));
  }
```

**Other information:**
I tried to call an api that is working on another ionic application (Ionic 3). But calling it from (Ionic 4 - 5) application is not working especially on device.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.0.0 
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 4 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : not installed

System:

   NodeJS : v10.15.3
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by KillerCodeMonkey** [comment]
looks like more a config issue
https://docs.microsoft.com/en-us/visualstudio/cross-platform/tools-for-cordova/security/whitelists?view=toolsforcordova-2017

maybe you are using a non ssl endpoint or something?

**Comment by paulstelzer** [comment]
Thanks for your issue! Please aware that this Repo are only for Ionic issues. What you describe is more related to Angular and Cordova or Cordova Plugin Ionic Webview. What @KillerCodeMonkey says I also believe the API server needs CORS set correctly.

**Comment by MhmdKorhani** [comment]
thank you @KillerCodeMonkey that really helped. After reviewing Cordova's documentation and Android's new privacy documentation the config.xml whitelists worked well for me.

And @paulstelzer no it is not CORS related since i mentioned that the same api is working on ionic 3 projects but not ionic 4. Also it not related to Cordova plugin Webview 😂.

**Comment by paulstelzer** [comment]
@MhmdKorhani Do you use cordova plugin webview version 4 in your ionic 3 app, too?

**Comment by rizzla22** [comment]
Im also hitting this issue,

Its not CORS related, Ive set a CSP in index, enabled full open CORS on the server, its a new app using cordova-plugin-ionic-webview 

I try to make requests using ionic native http and all i get is undefined in the results for everything, furthermore it does not even hit the server, switching to Angular http client i see the request hit the server but no data gets returned back to the running application - its so strange - NSAppTransportSecurity seems to be correct in the plist file also... this is hugely blocking me right now, I dont have the time to put together a working example. Is there anything else i should be checking here ?
