### ISSUE TITLE
bug: Could not find the implementation for builder @ionic/angular-toolkit:cordova-build

### ISSUE THREAD

**Issue by Ketec** [ionic-team/ionic#18431]
# Bug Report

**Ionic version:**

[x] **5.0.0*

**Current behavior:**

running "ionic cordova run android" gives that error.
Could not find the implementation for builder @ionic/angular-toolkit:cordova-build

```
insert the output from ionic info here
```
Ionic:

   Ionic CLI                     : 5.0.0 (C:\Users\Mauro\AppData\Roaming\nvm\v10.16.0\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.800.1
   @angular-devkit/schematics    : 8.0.1
   @angular/cli                  : 8.0.1
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 7.1.4, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 7 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.1

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

**Comment by mmmmyers** [comment]
Seeing this too after upgrading to Angular 8 and trying to run an ionic cordova build.

Could not find the implementation for builder @ionic/angular-toolkit:cordova-build
    at WorkspaceNodeModulesArchitectHost.resolveBuilder
(/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:49:19)
 at RunCommand.runSingleTarget (/node_modules/@angular/cli/models/architect-command.js:176:55)

**Comment by TomCosta** [comment]
[SOLUTION] I think is not permanently, just for a while solution.
`npm remove -g angular-cli`
Delete the node_modules folder and the package-lock.json file. After that come back the last package.json file configuration.
`rm -rf node_modules dist`
`npm install --save-dev @angular/cli@7`

> Then:

`npm install`

> Run Ionic:

`ionic serve`

**Comment by gustavoborboleta** [comment]
I'm having the same problem

**Comment by xecheverri** [comment]
I have the same problem after upgrading to Angular 8
`ng run app:ionic-cordova-build:production --platform=android
Could not find the implementation for builder @ionic/angular-toolkit:cordova-build
Error: Could not find the implementation for builder @ionic/angular-toolkit:cordova-build
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (/Users/.../node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:49:19)
    at RunCommand.runSingleTarget (/Users/.../node_modules/@angular/cli/models/architect-command.js:176:55)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[ERROR] An error occurred while running subprocess ng.`

**Comment by UTSOURCE** [comment]
I have the same problem after upgrading to Angular 8

**Comment by paulstelzer** [comment]
Thanks for your issue! This is not related to Ionic itself. The issue is Angular 8 because they have changed the builder API. A PR for @ionic/angular-toolkit is already available but not published so far (see https://github.com/ionic-team/angular-toolkit/pull/132 )

At the moment Angular 8 is not supported.

If you cannot wait (like me ;)), just replace `@ionic/angular-toolkit` inside angular.json with `paulstelzer-ionic-angular-toolkit` and run `npm i paulstelzer-ionic-angular-toolkit`. This is the build of the mentioned branch

**Comment by AkyBreez** [comment]
> 
> 
> Thanks for your issue! This is not related to this repo. The reason: The builder API has changed with Angular 8. A PR for `@ionic/angular-toolkit` is already available but not published so far (see [ionic-team/angular-toolkit#132](https://github.com/ionic-team/angular-toolkit/pull/132) )
> 
> At the moment Angular 8 is not supported.
> 
> If you cannot wait (like me ;)), just replace `@ionic/angular-toolkit` inside angular.json with `paulstelzer-ionic-angular-toolkit` and run `npm i paulstelzer-ionic-angular-toolkit`. This is the build of the mentioned branch. After `@ionic/angular-toolkit` got the new release you can use this again

I did what you said but I got this  after running: ionic cordova emulate android

> ng.cmd run app:ionic-cordova-build --platform=android
Could not find module "@ionic/angular-toolkit" from "C:\\Users\\mbado\\Documents\\Nucleo\\WORK\\ETUDIANT\\2018-2019_M1MIAGE\\S8\\AL3C_Professionalisation\\Application\\ToBeFound".
Error: Could not find module "@ionic/angular-toolkit" from "C:\\Users\\mbado\\Documents\\Nucleo\\WORK\\ETUDIANT\\2018-2019_M1MIAGE\\S8\\AL3C_Professionalisation\\Application\\ToBeFound".
    at Object.resolve (C:\Users\mbado\Documents\Nucleo\WORK\ETUDIANT\2018-2019_M1MIAGE\S8\AL3C_Professionalisation\Application\ToBeFound\node_modules\@angular-devkit\core\node\resolve.js:151:11)
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (C:\Users\mbado\Documents\Nucleo\WORK\ETUDIANT\2018-2019_M1MIAGE\S8\AL3C_Professionalisation\Application\ToBeFound\node_modules\@angular-devkit\architect\node\no
de-modules-architect-host.js:31:40)
    at RunCommand.runSingleTarget (C:\Users\mbado\Documents\Nucleo\WORK\ETUDIANT\2018-2019_M1MIAGE\S8\AL3C_Professionalisation\Application\ToBeFound\node_modules\@angular\cli\models\architect-command.js:176:55)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[ERROR] An error occurred while running subprocess ng.

**Comment by Ketec** [comment]
Not sure whos maintaining toolkit - but it seems there is no progress on this breaking issue.
The pull request seems to have gone stagnant.

**Comment by miguelwisse** [comment]
> Gracias por tu problema! Esto no está relacionado con este repositorio. El motivo: la API del constructor ha cambiado con Angular 8. `@ionic/angular-toolkit`Ya se encuentra disponible un PR para la obra, pero no se ha publicado hasta ahora (consulte [ionic-team / angular-toolkit # 132](https://github.com/ionic-team/angular-toolkit/pull/132) )
> 
> Por el momento no se soporta Angular 8.
> 
> Si no puedes esperar (como yo;)), simplemente reemplaza `@ionic/angular-toolkit`dentro de angular.json `paulstelzer-ionic-angular-toolkit`y ejecuta `npm i paulstelzer-ionic-angular-toolkit`. Esta es la compilación de la rama mencionada. Después de `@ionic/angular-toolkit` obtener el nuevo lanzamiento puedes usar esto de nuevo.

No me funciona estimado
![image](https://user-images.githubusercontent.com/44144275/59294829-51d9a080-8c50-11e9-814d-b1f1236df11d.png)

**Comment by jugbeep** [comment]
Still experiencing this. @paulstelzer, I can't seem to get your quick fix to work. I followed your steps and got the same error.

**Comment by morrisonbrett** [comment]
> Thanks for your issue! This is not related to this repo. The reason: The builder API has changed with Angular 8. A PR for `@ionic/angular-toolkit` is already available but not published so far (see [ionic-team/angular-toolkit#132](https://github.com/ionic-team/angular-toolkit/pull/132) )
> 
> At the moment Angular 8 is not supported.
> 
> If you cannot wait (like me ;)), just replace `@ionic/angular-toolkit` inside angular.json with `paulstelzer-ionic-angular-toolkit` and run `npm i paulstelzer-ionic-angular-toolkit`. This is the build of the mentioned branch. After `@ionic/angular-toolkit` got the new release you can use this again

Thanks @paulstelzer for addressing this. Your fix worked for me.

**Comment by Crypt0Graphic** [comment]
> Still experiencing this. @paulstelzer, I can't seem to get your quick fix to work. I followed your steps and got a new error:
> 
> ```
> architect_1.createBuilder is not a function
> TypeError: architect_1.createBuilder is not a function
>     at Object.<anonymous> (../node_modules/paulstelzer-ionic-angular-toolkit/builders/cordova-build/index.js:17:31)
>     at Module._compile (internal/modules/cjs/loader.js:701:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
>     at Module.load (internal/modules/cjs/loader.js:600:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Promise.resolve.then (../node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:79:61)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> [ERROR] An error occurred while running subprocess ng.
> ```

Did you make replacament in angular.json or in package.json?

**Comment by paulstelzer** [comment]
As I wrote above:  just replace `@ionic/angular-toolkit` inside `angular.json` with `paulstelzer-ionic-angular-toolkit` and run `npm i paulstelzer-ionic-angular-toolkit`.

**Comment by SebaPaciorek** [comment]
Hey @paulstelzer. I replaced as you wrote. 
This is my angular.json:
`{
  "$schema": "./node_modules/@angular-devkit/core/src/workspace/workspace-schema.json",
  "version": 1,
  "defaultProject": "app",
  "newProjectRoot": "projects",
  "projects": {
    "app": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "www",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "assets"
              },
              {
                "glob": "**/*.svg",
                "input": "node_modules/ionicons/dist/ionicons/svg",
                "output": "./svg"
              }
            ],
            "styles": [
              {
                "input": "src/theme/variables.scss"
              },
              {
                "input": "src/global.scss"
              }
            ],
            "scripts": [],
            "es5BrowserSupport": true
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            },
            "ci": {
              "progress": false
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "app:build:production"
            },
            "ci": {
              "progress": false
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "app:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [],
            "scripts": [],
            "assets": [
              {
                "glob": "favicon.ico",
                "input": "src/",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "/assets"
              }
            ]
          },
          "configurations": {
            "ci": {
              "progress": false,
              "watch": false
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": ["src/tsconfig.app.json", "src/tsconfig.spec.json"],
            "exclude": ["**/node_modules/**"]
          }
        },
        "ionic-cordova-build": {
          "builder": "paulstelzer-ionic-angular-toolkit:cordova-build",
          "options": {
            "browserTarget": "app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "app:build:production"
            }
          }
        },
        "ionic-cordova-serve": {
          "builder": "paulstelzer-ionic-angular-toolkit:cordova-serve",
          "options": {
            "cordovaBuildTarget": "app:ionic-cordova-build",
            "devServerTarget": "app:serve"
          },
          "configurations": {
            "production": {
              "cordovaBuildTarget": "app:ionic-cordova-build:production",
              "devServerTarget": "app:serve:production"
            }
          }
        }
      }
    },
    "app-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "app:serve"
          },
          "configurations": {
            "ci": {
              "devServerTarget": "app:serve:ci"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": ["**/node_modules/**"]
          }
        }
      }
    }
  },
  "cli": {
    "defaultCollection": "paulstelzer-ionic-angular-toolkit"
  },
  "schematics": {
    "paulstelzer-ionic-angular-toolkit:component": {
      "styleext": "scss"
    },
    "paulstelzer-ionic-angular-toolkit:page": {
      "styleext": "scss"
    }
  }
}
`
then i run `npm i paulstelzer-ionic-angular-toolkit`
Error after `ionic cordova run android`
`> ng.cmd run app:ionic-cordova-build --platform=android
architect_1.createBuilder is not a function
TypeError: architect_1.createBuilder is not a function
    at Object.<anonymous> (D:\Ionic\PROJECTS\Tours\node_modules\paulstelzer-ionic-angular-toolkit\builders\cordova-build\index.js:17:31)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Promise.resolve.then (D:\Ionic\PROJECTS\Tours\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:80:61)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:ionic-cordova-build --platform=android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.`

`ionic serve` works well, but I need to build to android.

**Comment by SebaPaciorek** [comment]
Hey @paulstelzer. I replaced as you wrote.
This is my angular.json:
`
{
  "$schema": "./node_modules/@angular-devkit/core/src/workspace/workspace-schema.json",
  "version": 1,
  "defaultProject": "app",
  "newProjectRoot": "projects",
  "projects": {
    "app": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "www",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "assets"
              },
              {
                "glob": "**/*.svg",
                "input": "node_modules/ionicons/dist/ionicons/svg",
                "output": "./svg"
              }
            ],
            "styles": [
              {
                "input": "src/theme/variables.scss"
              },
              {
                "input": "src/global.scss"
              }
            ],
            "scripts": [],
            "es5BrowserSupport": true
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            },
            "ci": {
              "progress": false
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "app:build:production"
            },
            "ci": {
              "progress": false
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "app:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [],
            "scripts": [],
            "assets": [
              {
                "glob": "favicon.ico",
                "input": "src/",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "/assets"
              }
            ]
          },
          "configurations": {
            "ci": {
              "progress": false,
              "watch": false
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": ["src/tsconfig.app.json", "src/tsconfig.spec.json"],
            "exclude": ["**/node_modules/**"]
          }
        },
        "ionic-cordova-build": {
          "builder": "paulstelzer-ionic-angular-toolkit:cordova-build",
          "options": {
            "browserTarget": "app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "app:build:production"
            }
          }
        },
        "ionic-cordova-serve": {
          "builder": "paulstelzer-ionic-angular-toolkit:cordova-serve",
          "options": {
            "cordovaBuildTarget": "app:ionic-cordova-build",
            "devServerTarget": "app:serve"
          },
          "configurations": {
            "production": {
              "cordovaBuildTarget": "app:ionic-cordova-build:production",
              "devServerTarget": "app:serve:production"
            }
          }
        }
      }
    },
    "app-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "app:serve"
          },
          "configurations": {
            "ci": {
              "devServerTarget": "app:serve:ci"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": ["**/node_modules/**"]
          }
        }
      }
    }
  },
  "cli": {
    "defaultCollection": "paulstelzer-ionic-angular-toolkit"
  },
  "schematics": {
    "paulstelzer-ionic-angular-toolkit:component": {
      "styleext": "scss"
    },
    "paulstelzer-ionic-angular-toolkit:page": {
      "styleext": "scss"
    }
  }
}


`
then i run npm i paulstelzer-ionic-angular-toolkit
Error after ionic cordova run android
`> ng.cmd run app:ionic-cordova-build --platform=android
architect_1.createBuilder is not a function
TypeError: architect_1.createBuilder is not a function
at Object. (D:\Ionic\PROJECTS\Tours\node_modules\paulstelzer-ionic-angular-toolkit\builders\cordova-build\index.js:17:31)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Promise.resolve.then (D:\Ionic\PROJECTS\Tours\node_modules@angular\cli\node_modules@angular-devkit\architect\node\node-modules-architect-host.js:80:61)
at process._tickCallback (internal/process/next_tick.js:68:7)
at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
at startup (internal/bootstrap/node.js:283:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
[ERROR] An error occurred while running subprocess ng.

    ng.cmd run app:ionic-cordova-build --platform=android exited with exit code 1.

    Re-running this command with the --verbose flag may provide more information.`
ionic serve works well, but I need to build to android.

**Comment by paulstelzer** [comment]
You have to use 0.800.0 of @angular-devkit

**Comment by redplane** [comment]
Any official annoucement about this please ?

**Comment by paulstelzer** [comment]
It's on the way :) maybe a few weeks

- https://github.com/ionic-team/ionic/pull/18577
- https://github.com/ionic-team/angular-toolkit/pull/132

**Comment by redplane** [comment]
@paulstelzer , I installed the plugin you mentioned `paulstelzer-ionic-angular-toolkit`, but I received an error: *Could not find module "@ionic/angular-toolkit"*.

Any solutions please ?

I'm using `ionic 4` and `angular 8`

**Comment by heikomat** [comment]
> @paulstelzer , I installed the plugin you mentioned `paulstelzer-ionic-angular-toolkit`, but I received an error: _Could not find module "@ionic/angular-toolkit"_.
> 
> Any solutions please ?
> 
> I'm using `ionic 4` and `angular 8`

As @paulstelzer said, installing the package isn't enough, you need to also use it in the angular.json instead of @ionic/angular-toolkit

**Comment by redplane** [comment]
@heikomat , thank you, after having read the comment, I made it worked 👍

**Comment by mhartington** [comment]
Hey folks! Angular-toolkit 2.0 has been released, please move off of the unofficial version.

**Comment by paulstelzer** [comment]
Correct, please REMOVE my package and use the official one again

**Comment by Lertis** [comment]
My package.json

`"dependencies": {
    "@angular/animations": "^8.0.2",
    "@angular/cdk": "~8.0.1",
    "@angular/common": "^8.0.2",
    "@angular/core": "^8.0.2",
    "@angular/forms": "^8.0.2",
    "@angular/http": "^7.2.15",
    "@angular/material": "^8.0.1",
    "@angular/platform-browser": "^8.0.2",
    "@angular/platform-browser-dynamic": "^8.0.2",
    "@angular/router": "^8.0.2",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.1.0",
    "cordova-android": "^8.0.0",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "paulstelzer-ionic-angular-toolkit": "^2.0.0",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "0.801.0",
    "@angular-devkit/build-angular": "~0.800.4",
    "@angular-devkit/core": "~7.3.8",
    "@angular-devkit/schematics": "~7.3.8",
    "@angular/cli": "~8.0.4",
    "@angular/compiler": "~8.0.2",
    "@angular/compiler-cli": "~8.0.2",
    "@angular/language-service": "~8.0.2",
    "@ionic/angular-toolkit": "~1.5.1",
    "@ionic/lab": "2.0.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~12.0.0",
    "codelyzer": "~4.5.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^4.1.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~8.3.0",
    "tslint": "~5.17.0",
    "typescript": "~3.4.5"
  }`

ionic info
`Ionic:

   Ionic CLI                     : 5.2.1 (C:\Users\Medved-PC\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.800.6
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 8.0.6
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.3 (cordova-lib@9.0.2)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)

Utility:

   cordova-res : 0.5.1
   native-run  : 0.2.2

System:

   Android SDK Tools : 26.1.1 (C:\Users\Medved-PC\AppData\Local\Android\Sdk)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.10.0
   OS                : Windows 10
`

ng v

`Angular CLI: 8.0.6
Node: 10.16.0
OS: win32 x64
Angular: 8.1.0
... animations, common, core, forms, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      8.0.2
@angular/cli                      8.0.6
@angular/compiler                 8.0.3
@angular/compiler-cli             8.0.3
@angular/http                     7.2.15
@angular/language-service         8.0.3
@angular/material                 8.0.2
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
`

For example `ionic cordova build android` successfully completed.

**Comment by patrickbussmann** [comment]
I don't know why but I have the same issue with recommended @ionic/angular-toolkit version 2.

```
$ npm "install" "-g" "cordova@latest"
$ npm "install" "-g" "ionic@latest"

cordova version: 9.0.0
ionic version: 5.2.3

$ ionic "cordova" "build" "--release" "--device" "ios" "--buildConfig" "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/__bitrise-cordova-build-config__380555088/build.json" "--" "--buildFlag=-UseModernBuildSystem=0"
> cordova platform add ios --save
Using cordova-fetch for cordova-ios@^5.0.0
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: org.example
	Name: Example
iOS project created with cordova-ios@5.0.1
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-statusbar' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-device' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-splashscreen' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-ionic-webview' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-mauron85-background-geolocation' found in config.xml... Migrating it to package.json
Plugin 'ionic-plugin-deeplinks' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-geolocation' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-telerik-imagepicker' found in config.xml... Migrating it to package.json
Plugin 'onesignal-cordova-plugin' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-camera' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-facebook4' found in config.xml... Migrating it to package.json
Discovered saved plugin "cordova-plugin-file". Adding it to the project
Installing "cordova-plugin-file" for ios
Adding cordova-plugin-file to package.json
Discovered saved plugin "cordova-plugin-ionic-keyboard". Adding it to the project
Installing "cordova-plugin-ionic-keyboard" for ios
Adding cordova-plugin-ionic-keyboard to package.json
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Discovered saved plugin "cordova-plugin-statusbar". Adding it to the project
Installing "cordova-plugin-statusbar" for ios
Adding cordova-plugin-statusbar to package.json
Discovered saved plugin "cordova-plugin-device". Adding it to the project
Installing "cordova-plugin-device" for ios
Adding cordova-plugin-device to package.json
Discovered saved plugin "cordova-plugin-splashscreen". Adding it to the project
Installing "cordova-plugin-splashscreen" for ios
Adding cordova-plugin-splashscreen to package.json
Discovered saved plugin "cordova-plugin-ionic-webview". Adding it to the project
Installing "cordova-plugin-ionic-webview" for ios
Adding cordova-plugin-ionic-webview to package.json
Discovered saved plugin "cordova-plugin-mauron85-background-geolocation". Adding it to the project
Installing "cordova-plugin-mauron85-background-geolocation" for ios
Adding cordova-plugin-mauron85-background-geolocation to package.json
Discovered saved plugin "ionic-plugin-deeplinks". Adding it to the project
Installing "ionic-plugin-deeplinks" for ios
Adding ionic-plugin-deeplinks to package.json
Discovered saved plugin "cordova-plugin-geolocation". Adding it to the project
Installing "cordova-plugin-geolocation" for ios
Adding cordova-plugin-geolocation to package.json
Discovered saved plugin "cordova-plugin-telerik-imagepicker". Adding it to the project
Installing "cordova-plugin-telerik-imagepicker" for ios
Adding cordova-plugin-telerik-imagepicker to package.json
Discovered saved plugin "onesignal-cordova-plugin". Adding it to the project
Installing "onesignal-cordova-plugin" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose
     Cloning into '/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/d20190801-2536-mt1bq'...
     Note: checking out '9271672bd77326df1063393451948b456ed9cbea'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     
Adding onesignal-cordova-plugin to package.json
Discovered saved plugin "cordova-plugin-camera". Adding it to the project
Installing "cordova-plugin-camera" for ios
Adding cordova-plugin-camera to package.json
Discovered saved plugin "cordova-plugin-facebook4". Adding it to the project
Installing "cordova-plugin-facebook4" for ios
Adding cordova-plugin-facebook4 to package.json
> ng run app:ionic-cordova-build --platform=ios
An unhandled exception occurred: Could not find the implementation for builder @ionic/ng-toolkit:cordova-build
See "/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/ng-9GGUs2/angular-errors.log" for further details.
[ERROR] An error occurred while running subprocess ng.
        
        ng run app:ionic-cordova-build --platform=ios exited with exit code 127.
        
        Re-running this command with the --verbose flag may provide more information.
command failed, error: exit status 127
```

**An unhandled exception occurred: Could not find the implementation for builder @ionic/ng-toolkit:cordova-build**

**cordova version:** 9.0.0
**ionic version:** 5.2.3

    "@ionic/angular-toolkit": "^2.0.0"

**Comment by patrickbussmann** [comment]
Small information:
I found the solution here: https://github.com/ionic-team/ionic-cli/issues/3763#issuecomment-442177064

In `angular.json` change:
`@ionic/ng-toolkit` to `@ionic/angular-toolkit`
`@ionic/schematics-angular` to `@ionic/angular-toolkit`

Thanks @carstenbaumhoegger and @abennouna for this important information which is missing in some docs. 🥳
