### ISSUE TITLE
Missing imports in polyfills.ts

### ISSUE THREAD

**Issue by LuizTokuhara** [ionic-team/ionic#18437]
# Bug Report

**Ionic version:**

[x] **4.4.0**

**Current behavior:**

On previous version of ionic there were some browser polyfills imported in polyfills.ts.
But newer versions do not have it.

**Expected behavior:**

List the imports like older versions:

/** IE9, IE10, IE11, and older Chrome requires all of the following polyfills. **/

import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v10.15.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Sierra
```

**Comment by paulstelzer** [comment]
Thanks for your issue! You as developer have to set which polyfills do you want to use. In Angular 8 most of it will be automatically integrated. What you describe is not part of Ionic to do. Ionic handles polyfills on the fly without touching polyfills.ts
