### ISSUE TITLE
bug: open another page not working

### ISSUE THREAD

**Issue by sac23** [ionic-team/ionic#18436]
Ionic version: (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] 2.x
[ ] 3.x
[x ] 4.x

I'm submitting a ... (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Current behavior:
next page button does not do anything.

Expected behavior:
its suppose  to open page 2

Steps to reproduce:
Just create another page other than home page .

Related code:
Here's the code I used to create

html:
 <ion-buttons>
   <button ion-button (click)="goAnOtherPage()">Go an Other Page </button>
 </ion-buttons>

in TS:

import { NavController } from 'ionic-angular';
import { AnOtherPage } from '/anOtherPage';

anOtherPage: AnOtherPage;

 constructor(public navCtrl: NavController) {}

goAnOtherPage() {
  this.navCtrl.setRoot(anOtherPage);
}
      
    
Other information:
none 

Ionic info:

Ionic:

   Ionic CLI                     : 5.0.0 (C:\Users\sac23\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

Misc:
  none

**Comment by paulstelzer** [comment]
Thanks for your issue! You do not use the navcontroller correctly. NavController does not have a setRoot in Ionic 4. Instead you can use navigateRoot or navigateForward like so:

```
goAnOtherPage() {
this.navCtrl.navigateRoot(this.anOtherPage);
}
```

Please take a look at https://ionicframework.com/docs/navigation/angular for more information about routing
