### ISSUE TITLE
bug: ion-segment scrollable is not scorlling on web

### ISSUE THREAD

**Issue by theunreal** [ionic-team/ionic#18439]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
The <ion-segment scrollable> component works great on mobile, but on desktop it does not scrolling on mouse slide.

**Expected behavior:**
The <ion-segment scrollable> component should support scorlling on web.

**Steps to reproduce:**
try to scroll on <ion-segment scrollable> on a desktop.

**Related code:**
```
<ion-segment scrollable>
...
</ion-segment>
```

**Other information:**

**Ionic info:**

```
 Android SDK Tools : 26.1.1 (C:\Android\android-sdk)
   NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10

```

**Comment by snakone** [comment]
any solution to this?

**Comment by Yohandah** [comment]
It's fixed in v5.

**Comment by liamdebeasi** [comment]
Thanks for the issue. With the release of Ionic Framework v5 `ion-segment` went through a complete revamp of its functionality, including scrolling. I am going to close this issue, but if you run into any additional bugs please feel free to open a new issue. Thanks!
