### ISSUE TITLE
feat: Add --opacity to control ion-chip opacity

### ISSUE THREAD

**Issue by theunreal** [ionic-team/ionic#18438]
# Feature Request
feat: Add --opacity to control ion-chip opacity. The same as added to ion-button.

**Ionic version:**
[x] **4.x**
4.0

**Describe the Feature Request**
Add --opacity to control ion-chip opacity

**Describe Alternatives**
Not sure how to overwrite this.

**Related Code**
```
<ion-chip color="primary">
<ion-label>Hello</ion-label>
</ion-chip>
```

**Comment by paulstelzer** [comment]
Thanks for your issue! There is no custom property necessary. Just add it to the host of the ion-chip element like so:

```
ion-chip {
  opacity: 0.4;
}
```
