### ISSUE TITLE
bug: ion-loading doesn't work at all.

### ISSUE THREAD

**Issue by jakub-cywka** [ionic-team/ionic#18443]
# Bug Report

**Ionic version:**

[x] **4.4.2**

**Current behavior:**

The ion-loading component doesn't show at all, it isn't even visible on the DOM.

**Expected behavior:**

The ion-loading component should properly mount to the DOM and become visible.

**Steps to reproduce:**

Just try to use <IonLoading /> component in your React application.

**Related code:**

```
export default () => <IonLoading isOpen={true} onDidDismiss={() => {}} />
```

**Other information:**

**Ionic info:**

There's no info from Ionic.

**Comment by elylucas** [comment]
fixed in the next upcoming beta release
