### ISSUE TITLE
feat: ion-fab-button without ionicons

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#18442]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
It is currently not possible to use `ion-fab-button` without `ionicons` as the `close` button is "hard coded" an Ionicons respectively the following icon in the render method of its component:

```
<ion-icon name="close" lazy={false}></ion-icon>
```

See https://github.com/ionic-team/ionic/blob/4bba540311c6b089b3f53f6ba6932dea248f6a05/core/src/components/fab-button/fab-button.tsx#L128

**Describe Preferred Solution**
I suggest two solutions. One would be to add properties for the icon, like `src` and `ariaLabel` or two to replace the icon with a `slot`

**Additional Context**
Such feature is useful in a scenario were not all 900+ icons can be shipped on a server or app but only selected icons can be shipped with the app aka where all icons are provided through src without having a dependency on ionicons

For example, in the following screenshot, I was able to specify all icons as src except the close button:

<img width="1267" alt="Capture d’écran 2019-06-02 à 09 40 41" src="https://user-images.githubusercontent.com/16886711/58758351-9cee0800-851a-11e9-9a9a-efa1cd877988.png">

**Comment by topalavlad** [comment]
I think adding properties would not be complete. It would allow people to use images but not other icon packages for example.
A `slot="close"` sounds like a good idea to me. I'd like to try and implement this.

**Comment by peterpeterparker** [comment]
I just provided a PR https://github.com/ionic-team/ionic/pull/18827 to replace the icon by a slot

**Comment by peterpeterparker** [comment]
I provide a PR https://github.com/ionic-team/ionic-docs/pull/832 to update the documentation too once the PR merged and released (if `@ionic/core` is updated in the doc too)
