### ISSUE TITLE
bug: ion-tabs: Wrong tab is marked as "active"

### ISSUE THREAD

**Issue by theunreal** [ionic-team/ionic#18440]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
The wrong tab is marked as active 

**Expected behavior:**
The correct tab should be marked as the active tab

**Steps to reproduce:**
Create ion-tabs with angular router. One route should be: /some-route and the other one should be /some-route/page1

**Related code:**

```
<ion-tab-button tab="world">
            <ion-icon name="map"></ion-icon>
            <ion-label>World</ion-label>
        </ion-tab-button>

        <ion-tab-button tab="world/dungeons">
            <ion-icon name="flame"></ion-icon>
            <ion-label>Dungeons</ion-label>
        </ion-tab-button>
```

When clicking the "Dungeons" tab, the "World" tab is marked as active.

**Ionic info:**

```
Android SDK Tools : 26.1.1 (C:\Android\android-sdk)
   NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still a bug in the latest version of Ionic Framework?
