### ISSUE TITLE
[4.12.0] [ion-picker] dismiss function doesn't pass data and role data to onDidDismiss 

### ISSUE THREAD

**Issue by dletran** [ionic-team/ionic#18454]
# Bug Report

**Ionic version:**

 **4.12.0**

**Current behavior:**
When the ion-picker gets dismissed the onDidDismiss() data and role properties are both undefined.

**Expected behavior:**
When the picker gets dismissed it should have the role parameter set. E.g. When closing via a Button with that button's role.
So we can perform some action based on whether the user clicked the button or not

**Steps to reproduce:**
Create a picker, present it  and tap on one of the buttons so the onDidDismiss() method is called.
```
const picker = await this.pickerController.create({
  buttons: [
   {
     text: 'CANCEL',
     role: 'cancel'
   },
   {
     text: 'CONFIRM',
     role: 'confirm'
   }
  ],
  columns: [
    {
      name: 'column',
      options: [
        {
          text: 'First',
          value: 'first'
        },
        {
          text: 'Second',
          value: 'second'
        }
      ]
    }
  ]
});

picker.present();

const dismiss = await picker.onDidDismiss();
console.log('Dismissed picker', dismiss);
if(dismiss.role === 'close') {
  console.log('Close button pressed!');
}
```

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v10.16.0 (/home/dletran/.nvm/versions/node/v10.16.0/bin/node)
   npm    : 6.9.0
   OS     : Linux 4.13
```

**Comment by brandyscarney** [comment]
Thanks for the issue! I was able to reproduce this with the following: https://codepen.io/brandyscarney/pen/YbggLb

I believe this line of code is the problem: https://github.com/ionic-team/ionic/blob/master/core/src/components/picker/picker.tsx#L191

Also, the backdrop dismiss is wrong: https://github.com/ionic-team/ionic/blob/master/core/src/components/picker/picker.tsx#L114

**Comment by lukabers** [comment]
Any updates on this issue?

**Comment by jeffricks** [comment]
Also interested in a fix for this.  Cancelling a picker is a pretty fundamental operation for a core component.

**Comment by abalad** [comment]
Same issue here

**Comment by hobbydevs** [comment]
Any updates ? Having the same issue.

**Comment by RashmiChandran** [comment]
Hi Team, Any updates for this issue?

**Comment by hidertanure** [comment]
Hi guys, 
As a workarround, my issue was solved using the handler callback like this:

`{
    text: 'Done',
    role: 'select',
    handler: (value) => {
        console.log(value);
    }
}`

Don't need to use the picker.onDidDismiss(); anymore.

**Comment by BrunoUY** [comment]
Hi, Any news?

**Comment by LucaCorcella** [comment]
Hi, any news?


` picker.onDidDismiss().then(data => {
      console.log(data);
    });.`


return undefiined

**Comment by brandyscarney** [comment]
PR submitted here: https://github.com/ionic-team/ionic/pull/19787

Dev release is based on the `5.0.0-beta.0` release: `5.0.0-dev.201910292106.aebfdfc`

**Comment by claytongulick** [comment]
fix won't be backported to 4.x branch?
