### ISSUE TITLE
bug: ion-picker column options overlapping

### ISSUE THREAD

**Issue by pppp0836** [ionic-team/ionic#18458]
# Bug Report

**Ionic version:**

[x] **4.3**

**Current behavior:**
AddEventListener to catch ionPickerColChange event, when a Column item changed, filter another column, but those itmes overlapping
below is screen shot
[https://ibb.co/wKsPGWx](url)

**Expected behavior:**

I try set selectedIndex = 0,still not work
**Steps to reproduce:**

**Related code:**

```
    const picker =  await this.pickerCtrl.create({
      buttons: [{
        text: 'cancel',
      }, {text: 'ok', handler: (opt) => {
          const p = picker.getColumn('project')
              .then(data => {
                const index = data.selectedIndex;
                const grade = this.projectItems.items[index].grade;
                const param = {xmname: opt['project'].text,
                    grade: grade,
                    subject: opt['subject'].text,
                    tizuName: opt['tizu'].text,
                    tizuEnName: opt['tizu'].value,
                    fullHostName: window.location.hostname
                  };
                this.checkIsBackScore(param);
              });
        }}],
      columns: [
        {
          name: 'project',
          selectedIndex: 0,
          options: this.projects
        },
        {
          name: 'subject',
          selectedIndex: 0,
          options: this.subjects
        },
        {
          name: 'tizu',
          selectedIndex: 0,
          options: this.tiZus
        }
      ],
      // mode: 'ios'
    });
    picker.addEventListener('ionPickerColChange', async (event: any) => {
      const data = event.detail;
      if (data.name === 'project') {
        const curIndex = data.selectedIndex;

        this.subjects = [];
        Promise.all((data.options[curIndex] as PickerColumnOption).value.map((item) => {
          this.subjects.push({text: item.name, value: item.items, duration: 0, selected: true, disabled: false});
        }));

        this.tiZus = [];
        if (this.subjects.length > 0) {
          Promise.all(this.subjects.map((item) => {
            this.tiZus.push({text: (item as TizuItem).tizu_name, value: (item as TizuItem).tizu_enname, duration: 0,
              selected: true, disabled: false});
          }));
        }

        const columns = [];
        columns.push({name: 'project', selectedIndex: curIndex, options: this.projects, optionsWidth: '100px'});
        columns.push({name: 'subject', selectedIndex: 0, options: this.subjects, optionsWidth: '100px'});
        columns.push({name: 'tizu', selectedIndex: 0, options: this.tiZus, align: 'right', optionsWidth: '100px'});
        picker.columns = columns;


      } 
    });
    picker.present();
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you provide a repository with the code required to reproduce this issue? Also can you paste the output of running `ionic info`? 

Thanks!

**Comment by pppp0836** [comment]
Hi liamdebeasi,
I have uploaded Source Code on git: https://github.com/pppp0836/WebExam
And Ionic info:
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v11.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.7.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the follow up. I am unable to get past the login screen in your application. Can you provide a repo that only contains a reproduction of the `ion-picker` issue you are seeing

Thanks!

**Comment by pppp0836** [comment]
Hi liamdebeasi,
Can we hold this issue,Because I will go out for a few days,Thank you

**Comment by pppp0836** [comment]
Hi liamdebeasi,
  I am so sorry  to keep you waiting, and I made a simple demo to test Picker,[https://github.com/pppp0836/testPicker](url) 
After run this demo, you can select Item on Column 1 ,Column 2 will be refresh,and items of Column occur overlapping.
Thank you very much.
