### ISSUE TITLE
Bug: [Ionic-React]. <IonInput/> Controlled component doesn't work.

### ISSUE THREAD

**Issue by vpuonti** [ionic-team/ionic#18452]
# Bug Report

**Ionic version:**

[x] **4.4.2**

**Ionic-React version**

[x] **0.0.5**

**Current behavior:**

`<IonInput />`'s onChange is not fired.

`<IonInput />`'s value is set to state from `onInput`, but the state is not set to `value={}`. The `<IonInput />`-component's state is not really being controlled. 

**Expected behavior:**

Input's value is same as state.

1. Input is handled by `onChange` method
2. Input length is checked.
* If `length <= 5` then update state
* else don't
3. `<IonInput />`'s value is same as state

**Steps to reproduce:**

I created two state variables, `value1` and `value2`, and setters using the `useState()`-hook. I created a controlled `<IonInput />` and a controlled `<input />`. The regular `<input />` is controlled as expected. No more than 5 characters can be placed there. The `<IonInput />`'s input is correctly set to state and restricted to 5 characters, however the `<IonInput />` continues to take in characters. 

I ran in to the issue by following the guide from: https://ionicframework.com/blog/using-react-hooks-in-an-ionic-react-app/

**Related code:**

https://ionicframework.com/blog/using-react-hooks-in-an-ionic-react-app/

![image](https://user-images.githubusercontent.com/25032592/58863875-56381380-86bc-11e9-9406-15f471e3c15f.png)

![image](https://user-images.githubusercontent.com/25032592/58864333-2b01f400-86bd-11e9-8277-d8ff79dd164b.png)

**Other information:**

**Ionic info:**

```
➜  ionic-react-test git:(valtsuDev) ✗ ionic info

Ionic:

   ionic (Ionic CLI) : 4.12.0 (/home/[redacted]/.nvm/versions/node/v12.2.0/lib/node_modules/ionic)

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.24
   @capacitor/core           : 1.0.0

System:

   NodeJS : v12.2.0 (/home/[redacted]/.nvm/versions/node/v12.2.0/bin/node)
   npm    : 6.9.0
   OS     : Linux 4.4
```

**Comment by SulimanTwfiq** [comment]
Change  onChange  to onIonChange .

**Comment by calendee** [comment]
Here's a working demo: https://stackblitz.com/edit/ionic-react-ion-input-issue-18452

**Comment by calendee** [comment]
Per a comment from https://twitter.com/VictorDev92, I tested `onInput` vs `onChange` in the original sample.  `onInput` *does* work properly.  However, I still feel this is a bug as `onChange` is pretty standard in the React world.

**Comment by calendee** [comment]
After looking at the [docs](https://ionicframework.com/docs/api/input#events) ☺️, maybe we shouldn't be using these React events? 

Instead, you can do this:

```
<IonInput
  id="firstName"
  name="firstName"
  onIonChange={setFirstName}
  onSubmit={() => {
    login(null);
  }}
  placeholder="Enter your first name"
  value={firstName}
></IonInput>
```

**Comment by elylucas** [comment]
Closing this issue as its old on a pre-beta version of Ionic/React. If the problem still persists on the latest version, please create a new issue and link this one for reference.
