### ISSUE TITLE
bug: navigateForward, navigateBack in navigation controller not passing options to angular router

### ISSUE THREAD

**Issue by MarkChrisLevy** [ionic-team/ionic#18469]
# Bug Report
When navigateForward or navigateBack is called with url as string or UrlTree, navigation options are not passed to angular router. When url is an array, options are passed properly.

**Ionic version:**
[x] **4.4.2**

**Current behavior:**
When navigateForward or navigateBack is called with url as string or UrlTree, navigation options are not passed to angular router. When url is an array, options are passed properly.

**Expected behavior:**
Navigation options must be always passed to angular router.

**Steps to reproduce:**
navigateForward("/some/url", {replaceUrl: true});

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic 4.4.2
```

**Comment by liamdebeasi** [comment]
Good catch -- thank you! I left you some comments on your PR. 🎉
