### ISSUE TITLE
bug: Package "@ionic/angular" has an incompatible peer dependency to "zone.js" (requires "^0.8.26", would install "0.9.1").

### ISSUE THREAD

**Issue by romelgomez** [ionic-team/ionic#18470]
# Bug Report

**Ionic version:**

[x] **4.4.2**

**Current behavior:**

Try update from angular 7 to 8 with the Cli

`ng update @angular/cli @angular/core`

```bash
Package "@ionic/angular" has an incompatible peer dependency to "zone.js" (requires "^0.8.26", would install "0.9.1").
Incompatible peer dependencies found. See above.
```

Angular CLI: 7.3.9
Node: 11.14.0
OS: linux x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/flex-layout              7.0.0-beta.24
@angular/material                 7.3.7
@angular/pwa                      0.13.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.29.0

**Related code:**

https://github.com/ionic-team/ionic/blob/master/angular/package.json#L63

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/home/rextie/.config/yarn/global/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0-dev.201905311531.e014c6a
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (/home/rextie/Android/Sdk)
   NodeJS            : v11.14.0 (/home/rextie/NODE/node-v11.14.0-linux-x64/bin/node)
   npm               : 6.7.0
   OS                : Linux 4.15
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! I am going to close this in favor of https://github.com/ionic-team/ionic/issues/18414. We are looking into what it would take to update `@ionic/angular` to work with Angular 8. I will post in the thread I linked to when I have more to share.

Thanks!
