### ISSUE TITLE
bug: Ionic 4 won't work in android 6

### ISSUE THREAD

**Issue by JeongJun-Lee** [ionic-team/ionic#18474]
# Bug Report

**Ionic version:**

[x] **4.2**

**Current behavior:**

At real Android device with Android 6.0.1 , it emit like this "Uncaught TypeError: (intermediate value).fill is not a function" from vendor.js.

**Expected behavior:**

Should be started normally

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

Chrome version: 71

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.0.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.0.0, browser 5.0.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 4.0.1, (and 6 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.3

System:

   Android SDK Tools : 25.2.4 (/Users/comseong/Library/Android/sdk)
   ios-deploy        : 2.0.0
   ios-sim           : 7.0.0
   NodeJS            : v10.16.0 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

```

**Comment by kensodemann** [comment]
Can you please provide a sample application via GitHub that demonstrates your issue? I have a Galaxy Tab that is running Android 6.0.1 that I run Ionic v4 applications on all the time for testing, so I would be interested in seeing what the difference is between whatever is not working for you and my typical applications.

**Comment by JeongJun-Lee** [comment]
![image](https://user-images.githubusercontent.com/11474775/59036763-59ccc580-8889-11e9-81b6-ee788686ffcb.png)

**Comment by JeongJun-Lee** [comment]
https://github.com/ionic-team/capacitor/issues/1388#issuecomment-479865253, Like the comment, if the android system webview is upgraded, the error will be disappeared.

**Comment by liamdebeasi** [comment]
@JeongJun-Lee,

Does upgrading the WebView resolve your issue?

**Comment by JeongJun-Lee** [comment]
Yes, after upgrading WebView, the error will be disappeared.

**Comment by liamdebeasi** [comment]
Great! I am going to close this issue as it has been resolved.

Thanks for using Ionic!
