### ISSUE TITLE
bug: ion-item-divider (iOS) has no "--padding-inline-end" variable

### ISSUE THREAD

**Issue by davideas** [ionic-team/ionic#18484]
# Bug Report

**Ionic version:**
**4.4.2**

**Current behavior:**
For element `<ion-item-divider>` when I set `--padding-inline-end: 0;` in the styles it doesn't not work for iOS because no variable exists for the _padding-inline-end_ that now has 8px hard coded (no issues for Android):

![image](https://user-images.githubusercontent.com/12213847/59110510-96f38f00-893f-11e9-8fd7-2f4931a91178.png)

**Expected behavior:**
Please make _padding-inline-end_ a variable: `--padding-inline-end`

**Comment by brandyscarney** [comment]
Thanks for the issue! The `item-divider-inner` code needs to be changed to use the following to match item:

```
  @include padding(
    var(--inner-padding-top),
    calc(var(--ion-safe-area-right, 0px) + var(--inner-padding-end)),
    var(--inner-padding-bottom),
    var(--inner-padding-start)
  );
```
