### ISSUE TITLE
bug: fullscreen="true" property doesn't work on ion-content

### ISSUE THREAD

**Issue by ekzotech** [ionic-team/ionic#18480]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
With "fullscreen" attribute <ion-content> doesn't take full height. There's still an empty space beneath <ion-header>.

**Expected behavior:**
ion-content should respect fullscreen property and take full height and also empty space beneath <ion-header>

**Steps to reproduce:**
1.Any page with ion-header and ion-content
2. Add fullscreen property to ion-content, so it'll be: ion-content fullscreen (or fullscreen="true" doesn't matter)
3. Set in SCCS: ion-toolbar { --opacity: 0.5; }
4. Voila! There's nothing changed on the page.
5. Go to developer tools and set for entire ion-content position: absolute; And now you'll see the content of ion-content beneath ion-header.
I can reproduce this behaviour in 100% cases, also with latest ionic package.

**Related code:**

This works for me on any Ionic 4 project and also for Ionic 4 starter with side menu.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.0.1 (/Users/ekzotech/.nvm/versions/node/v12.3.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.3.1 (/Users/ekzotech/.nvm/versions/node/v12.3.1/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! Can you provide a code reproduction of the issue you are seeing? I created a CodePen here and everything seems to be working fine: https://codepen.io/liamdebeasi/pen/LobXZX?ionic:mode=ios.

Thanks!

**Comment by ekzotech** [comment]
Here's example from Ionic starter template: https://codepen.io/ekzotech/pen/RmzdWj
Shouldn't "fullscreen" make ion-content take full height of page?
Because this is the issue I'm facing with. In my app I had an component with map, and I want to have semitransparent header, but ion-content doesn't take full height, though it has no margin and no paddings.
Even if I set --offset-top to 0 - it doesn't help.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the follow up. The `ion-content` documentation says that setting `fullscreen` to `true` makes the content scroll behind the headers and footers, which is what is happening in the CodePen you sent.

What browser/version are you testing this on? This is what I am seeing when I test in Chrome 74:

![image](https://user-images.githubusercontent.com/2721089/59108428-d81c7c80-8908-11e9-9221-969a39dab915.png)

**Comment by ekzotech** [comment]
I'm using Google Chrome 74.0.3729.169. I can scroll page down and then content of the ion-content will be visible behind ion-header. But shouldn't it render ion-content behind ion-header at startup?
And if no - how I can get the same behaviour as here: https://medium.com/@paulstelzer/ionic-4-how-to-make-a-transparent-header-toolbar-38405f2e4a74
Here you can see that content of page renders behind ion-header.

**Comment by liamdebeasi** [comment]
Hi there,

The content should not be behind the header at start up. All `fullscreen` does is allow the content to scroll under the header and footer.

In terms of the article you linked to, I would recommend asking that question on the [forum](https://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com) as that is more of a support question rather than a bug in Ionic.

Thanks!
