### ISSUE TITLE
bug: @ionic/react: returning <Redirect> from <Route>'s render prop fails tests

### ISSUE THREAD

**Issue by ebk46** [ionic-team/ionic#18489]
I normally auth-guard my routes by returning <Redirect> from <Route>'s render prop if a user is not authenticated. This design pattern is used in many react examples including the ionic conference app. However, when using <IonRouterOutlet> this pattern fails unit tests.

**Ionic version:**
4.4.2

**Current behavior:**
Failed unit tests when returning <Redirect> from <Route>'s render prop when using <IonRouterOutlet>. If I used a component instead of <Redirect> it works fine.

**Expected behavior:**
Returning <Redirect> should be acceptable and pass unit tests.

**Steps to reproduce:**
When using <IonRouterOutlet>, return <Redirect> from a <Route>'s render prop (see code)

**Related code:**

```
<div id="app">
  <IonApp>
    <IonRouterOutlet>
      <Route path="/login" render={(props): ReactElement => <Login/>} />
      <Route path="/" render={(props): ReactElement => {
        return <Redirect to={{pathname: '/login', state: {from: props.location}}}/>;
      }/>
    </IonRouterOutlet>
  </IonApp>
</div>
```

**Other information:**
Error: 
```
Error: Uncaught [TypeError: this.containerEl.current.commit is not a function]
...
The above error occurred in the <RouterOutlet> component:
        in RouterOutlet (created by Context.Consumer)
        in withRouter(RouterOutlet) (at App.tsx:113)
...
```

**Ionic info:**
```
Ionic:

   Ionic CLI       : 5.0.1 (/Users/evan/.config/yarn/global/node_modules/ionic)
   Ionic Framework : @ionic/react 0.0.5

Capacitor:

   Capacitor CLI   : 1.0.0
   @capacitor/core : 1.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.1.0 (/usr/local/Cellar/node/12.1.0/bin/node)
   npm    : 2.15.12
   OS     : macOS High Sierra
```

**Comment by blazery** [comment]
Hey ebk

Im currently switching from our own routing and page management system to the ionic-react-router, and im having alot of issues with auth protected routes.

I can't seem to find the correct way of rendering routes based on auth.

`<div id="app">
  <IonApp>
     <IonRouterOutlet>
                <Route path={'/login'} component={Login} />
                <Route path={'/viewer'} component={Viewer} />
                <Route path={'/config'} component={ConfigSelection} />
                <Route path={'/agreement'} component={Agreement} />
                <Route path={'/rights'} component={Copyright} />
                <Route path={'/menu'} component={Menu} />
                <Route path={'/search' component={Search} />
                <Route path={'/time' component={Time} />
                <Route path={'/tools'} component={Tools} />
                <Redirect from={'/'} to={'/login'} />
            </IonRouterOutlet>
  </IonApp>
</div>`

I tried all sorts of ways to get the auth protected routes, 

- I tried only rendering routes when authentication was completed.
- I tried always rendering the <Route /> tags, but include a render function which returns a page or a <Redirect />, but this didn't work as the outlet started throwing warnings about not returning a page from a route
- I tried creating new outelets based on logged in state, but nothing helped.

how did you implement your auth protected routes?

**Comment by elylucas** [comment]
Closing this issue as its old on a beta version of Ionic/React. If the problem still persists on the latest version, please create a new issue and link this one for reference.
