### ISSUE TITLE
bug: ionScrollEnd fires twice on Android

### ISSUE THREAD

**Issue by cremfert** [ionic-team/ionic#18488]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Sometimes, when scrolling on an ion-content element not to slow and not to fast, the ionScrollEnd event is fired twice - once shortly before scroll ends and once the scroll really ends. While this is not that problematic, is runs the internal ionScrollStart function twice, and hence, two times the watchdog and the timer is running. It is this function here:
in [`ionic/core/src/components/content/content.tsx`, line 276](https://github.com/ionic-team/ionic/blob/master/core/src/components/content/content.tsx#L276)

This leads to a high cpu usage on slow android devices and hence, scrolling is interrupted shortly, which makes scrolling feeling not native.

**Expected behavior:**
Event should only fired once and hence watchdog and timer should also.

**Steps to reproduce:**
Create a page with ion-content, put a list with around 100 items and scroll with medium speed. Let the scroll end without touching the screen. You will notice a bump at the end.

**Related code:**
https://github.com/ionic-team/ionic/blob/master/core/src/components/content/content.tsx#L276

**Other information:**
Is there any chance to override or disable the onScrollStart function?

Could be related to #15726, but we are not using virtual-scroll

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! Can you provide a repository with the code required to reproduce this issue?

Thanks!
