### ISSUE TITLE
Routing to an article from another article does not working 

### ISSUE THREAD

**Issue by m7ammad7assan** [ionic-team/ionic#18494]
I am using
    "@ionic/angular": "^4.4.2",
 "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.15",
    "@angular/http": "^7.2.15",

and In my project there is a page of articles which also contains routes to other articles, I can from home page to navigate to an article page using [routerlink] directive but when the current route is /article/:article_id I cannot navigate to another article route when click on [routerlink] directive, the link on browser's address bar changing correctly with not navigation, I am sure it was working some days ago, but I do not know why is it not working now ?!

also I used (click) event to navigate using this.route.navigateByUrl but even this not working 

my paths:

  <div [routerLink]="['/p/',post.hashed_id]"    </div>

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by m7ammad7assan** [comment]
Hi, I found I commented these two lines in app.module

   {
            provide: RouteReuseStrategy,
            useClass: IonicRouteStrategy
        }

sorry ..

**Comment by m7ammad7assan** [comment]
Hi, I found I commented these two lines in app.module

{
provide: RouteReuseStrategy,
useClass: IonicRouteStrategy
}

sorry ..
