### ISSUE TITLE
bug: ion-textarea wrap="off" is not working 

### ISSUE THREAD

**Issue by scrpgil** [ionic-team/ionic#18495]
Bug Report

I can not do English. This sentence uses Google translation.

**Ionic version:**
[x] **4.4.2**

**Current behavior:**

Line feed will occur even if the attribute of `wrap="off"` is added to ion-textarea.
The reason is that `white-space: pre-wrap` is set in src/components/textarea/textarea.scss.

https://github.com/ionic-team/ionic/blob/10de1da9480896c58bedde06ee022c1456d68354/core/src/components/textarea/textarea.scss#L92

Also, even if this `white-space: pre-wrap` is deleted, `white-space: inherit` is set in ionic.mixins.scss, so the line feed is always Will occur.

https://github.com/ionic-team/ionic/blob/10de1da9480896c58bedde06ee022c1456d68354/core/src/themes/ionic.mixins.scss#L32

If you have `wrap="off"` attribute to solve this problem, it would be better to add CSS to set `white-space: nowrap`.

I am ready for a pull request to solve this problem.
https://github.com/scrpgil/ionic/pull/1

**Expected behavior:**

If `wrap="off"` the text is not broken.

**Steps to reproduce:**

1. Add the `wrap="off"` attribute to ion-textarea.

2. Enter text in ion-textarea that you do not want to break. For example, like ASCII art.

3. Make sure that the line breaks and the display is broken.

line wrap(Current behavior)
![Screen Shot 2019-06-10 at 3 25 10](https://user-images.githubusercontent.com/26167770/59162759-9f132080-8b31-11e9-8948-0f45b8315476.png)

It should be displayed as below.

line no wrap(Expected behavior:)
![Screen Shot 2019-06-10 at 3 24 59](https://user-images.githubusercontent.com/26167770/59162765-c4079380-8b31-11e9-84b4-2f3d7b22b1b3.png)

**Related code:**

```
<ion-textarea wrap="off"></ion-textarea>
```

not working text wrap.

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v10.15.3 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by brandyscarney** [comment]
Thank you for the issue! I believe this can be fixed by changing the code to the following in `textarea.scss`:

```
:host {
  white-space: pre-wrap;
}
```

And removing the `white-space` rule here: https://github.com/ionic-team/ionic/blob/master/core/src/components/textarea/textarea.scss#L92

**Comment by scrpgil** [comment]
Thank you!
I tried the content of the comment I received.
But the problem did not go away.

I found a way to solve the problem.
It seems necessary to delete `@include text-inherit ()` as well as `white-space`.
https://github.com/ionic-team/ionic/blob/055e12570d65056c29d9ac192493add7095ddb70/core/src/components/textarea/textarea.scss#L75

I would like to send a pull request with this content.

**Comment by brandyscarney** [comment]
@scrpgil So the solution in my comment above will still make the text wrap, as that is the default for the textarea. The `text-inherit()` mixin makes it so that the native textarea will inherit the `white-space` value from the host element. By moving the `white-space` rule from the native textarea to the host (`ion-textarea`) element, it will allow you to write the following:

```
ion-textarea {
  white-space: nowrap;
}
```

And then the textarea will be customized to your liking. Let me know if you have any questions. 🙂

**Comment by scrpgil** [comment]
@brandyscarney I confirmed that I would solve it with a comment.

However, I want to wrap the line only with `wrap="off"`, so I thought I wanted to remove `@include text-inherit ()`.

**Comment by brandyscarney** [comment]
We need to keep `@include text-inherit()`. The default of a textarea should be to wrap, and it can be turned off by adding `white-space: nowrap`

**Comment by scrpgil** [comment]
@brandyscarney I understand!  Create a pull request referring to the comments.
