### ISSUE TITLE
bug: ionic studio ver 0.0.63 and 0.0.64 saving files

### ISSUE THREAD

**Issue by SebaPaciorek** [ionic-team/ionic#18497]
in ionic studio ver 0.0.63 and 0.0.64 cant change any file
when you want to write sth and save then cursor back to begin of file

**Comment by liamdebeasi** [comment]
Thanks for the issue! I am going to close this as this repo is for issues related to Ionic Framework. For support with Ionic Studio, please use the in-app Intercom chat.

Thanks!
