### ISSUE TITLE
bug: transluscent (header) & no-border (toolbar) not working

### ISSUE THREAD

**Issue by Incubbus** [ionic-team/ionic#18510]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

The header is not translucent.
The toolbar has a border.

**Expected behavior:**

The header should be translucent.
The toolbar should have no border.

**Steps to reproduce:**

`ionic start test blank`

**Related code:**

```
<ion-header translucent="true">
  <ion-toolbar no-border>
    <ion-title>
      Title
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content fullscreen="true">

  <div>Lorem ipsum.... [a loooooot of content to force scroll behind toolbar]</div>

</ion-content>

```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.0.2 (C:\Users\\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : 0.3.0
   native-run  : not installed

System:

   NodeJS : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! Are you testing this on MD mode or iOS mode? By default, MD mode will not show `ion-header` as translucent as there is nothing in the MD spec that calls for this behavior.

Thanks!

**Comment by Incubbus** [comment]
So the translucense has no effect on md design at all? Would be nice to have this info in the documentation.

Nontheless: serving it in the browser (Chrome) does not have any in either mode.
Same applies to `no-border`...

**Comment by liamdebeasi** [comment]
Hi there,

I have an example of translucency working in iOS mode here: https://codepen.io/liamdebeasi/pen/LobXZX?ionic:mode=ios

In regards to `ion-toolbar`, the `no-border` property does not exist. I see a mention of it in the docs that should not be there, so I will remove that. Instead, you can customize the border using CSS variables: https://ionicframework.com/docs/api/toolbar#css-custom-properties

**Comment by Incubbus** [comment]
Ok, thank you for the fast responses!.
