### ISSUE TITLE
feat: Please provide a method to distinguish cordova browser platform by platform.is('browser)

### ISSUE THREAD

**Issue by JeongJun-Lee** [ionic-team/ionic#18513]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

I am developing a App at cordova browser platform for simulating like a App in real device with cordova plugins. But there is no way to distinguish if the platform is browser by the function platform.is(). So it's really uncomfortable.
Please provide a method to distinguish cordova browser platform by platform.is('browser).

**Describe Preferred Solution**

I want to check if current platform is cordova browser platform, not android or ios platform.

**Describe Alternatives**

**Related Code**

 constructor(
    private platform: Platform
  ) {
  if (this.platform.is('browser')) ...
 }

**Additional Context**

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the feature request. Are you able to use `this.platform.is('cordova')` for your use case?

Thanks!

**Comment by JeongJun-Lee** [comment]
Thanks, but platform.is('cordova') includes 3 platforms(android, ios, browser)

**Comment by liamdebeasi** [comment]
Thanks for the follow up. What is "browser" in this case? There is no "browser" platform in the [Platform Documentation](https://ionicframework.com/docs/utilities/platform).

**Comment by JeongJun-Lee** [comment]
https://github.com/apache/cordova-browser

**Comment by liamdebeasi** [comment]
Thanks for the follow up. You should be able to write a function similar to:

```
isCordovaBrowser() {
  return (
    this.platform.is('cordova') && 
    !this.platform.is('ios') && 
    !this.platform.ios('android')
  )
}
```

Can you let me know if this example works for your use case?

**Comment by JeongJun-Lee** [comment]
Sorry it doesn't work because when I test my App on emulated mode at Chrome dev tool like attached image, it returns [cordova, android, mobile, hybrid] by this.platform.platforms().

![image](https://user-images.githubusercontent.com/11474775/59378427-b6d6e880-8d6d-11e9-9b62-788592f776a0.png)

**Comment by liamdebeasi** [comment]
Thanks for testing that out. I noticed that Cordova exposes the platform it is running. Are you able to check to see if `cordova.platformId === 'browser'`?

**Comment by JeongJun-Lee** [comment]
It works!!! Thanks a lot.

**Comment by liamdebeasi** [comment]
Great! I am going to close this as this issue has been resolved.

Thanks for using Ionic!
