### ISSUE TITLE
bug: Menu can not be closed by clicking backdrop

### ISSUE THREAD

**Issue by heinerlamprecht** [ionic-team/ionic#18520]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

When clicking the backdrop area of an overlay menu, the menu is not closed in MS Edge.  Other browsers like Chrome, Firefox or Safari are working properly.

**Expected behavior:**

The menu should be closed.

**Steps to reproduce:**

Open an app with a menu in MS Edge, open the menu, click the backdrop area.

**Related code:**

The issue can be reproduced even in the example of the official documentation:

https://ionicframework.com/docs/api/menu

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as we recently released Ionic Framework v5 which dropped support for IE11 and older versions of Edge. Moving forward, Ionic Framework v4 will only receive critical security patches.
