### ISSUE TITLE
bug: Header and Footer hides when using "In app browser" on iOS

### ISSUE THREAD

**Issue by eulerchavez** [ionic-team/ionic#18523]
# Bug Report

**Ionic version:**
```

Ionic:

   Ionic CLI                     : 5.0.0
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.3.1
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 14 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (C:\AndroidSDK)
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.7.0
   OS                : Windows 10

```
**Current behavior:**

When app is opened using "in app browser", header and footer hides.

**Expected behavior:**

When app is opened using "in app browser", it display correctly header, footer and content.

**Steps to reproduce:**

An email is send to client and clicks the URL (in iPhone X using Yahoo native app), ionic app is opened by Yahoo using "in app browser" then header and footer hides

![Error 1](https://user-images.githubusercontent.com/18647380/59371506-ce30ba00-8d0a-11e9-9351-eee175f2aeb4.jpg)

![Error 2](https://user-images.githubusercontent.com/18647380/59371521-d7ba2200-8d0a-11e9-9e46-6ffc07a05791.jpg)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.

**Comment by eulerchavez** [comment]
Really? 1 year later. No Thanks

**Comment by liamdebeasi** [comment]
Hi there, we have a small team looking through these issues, so it is impossible for us to get to every single issue in a timely manner.

Is this still an issue in Ionic Framework? I am happy to take a look if you can provide a repo.
