### ISSUE TITLE
Input focus not working cordova-plugin-ionic-webview ***

### ISSUE THREAD

**Issue by realweb** [ionic-team/ionic#18539]
Related to cordova-plugin-ionic-webview

Hi,

After iOS 12.2 update when I tap into any input field, the cursor (focus) dont appear on the input. No matter I tap into it, I cant start typing.

If I press the down arrow on the acessory bar, it changes between the input elements and focus occurs.

If I remove cordova-plugin-webview from the project, things work normally, without any problem.

Problem seens to be this one: apache/cordova-plugin-wkwebview-engine#71

I tried to install cordova-plugin-wkwebview-inputfocusfix and also added but did not work.

Any clue?

thanks

**Comment by liamdebeasi** [comment]
Hi there,

I am going to close this as this is not an Ionic Framework bug. Additionally, it looks like this bug has been fixed in `cordova-plugin-ionic-webview`, so you may just need to update the webview plugin.

Thanks!
