### ISSUE TITLE
bug: ion-fab displays behind toolbar/footer

### ISSUE THREAD

**Issue by jaipresto** [ionic-team/ionic#18554]
ion-fab doesn't seem to function properly when seated inside ion-toolbar, inside ion-footer. 

I won't bother with detailed code/examples because it's ~exactly the same as this: https://github.com/ionic-team/ionic/issues/16780. The fab opens up behind the toolbar like so:

<img width="188" alt="Screenshot 2019-06-16 at 11 58 56" src="https://user-images.githubusercontent.com/20077437/59563188-6b069680-902e-11e9-8219-63f4edf6c5ea.png">

I have the latest ionic, and have tested in various latest-version browsers. I have tried setting slot=fixed (which causes it to disappear), vertical=bottom, side=top -- nothing works. Playing with the z-index or position does nothing either.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you post the output of running `ionic info` from your project directory?

Thanks!

**Comment by jaipresto** [comment]
Hi Liam

```
Ionic:

   Ionic CLI                     : 5.0.2 (/Users/Jai/.nvm/versions/node/v10.15.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 4 other plugins)

Utility:

   cordova-res : 0.1.0
   native-run  : not installed

System:

   NodeJS : v10.15.3 (/Users/Jai/.nvm/versions/node/v10.15.3/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the follow up. Can you provide a repo with the code required to reproduce this issue? I am not able to see this happening from my reproductions.

Thanks!
