### ISSUE TITLE
bug: no styling on disabled "icon-only ion-button" in ion-toolbar

### ISSUE THREAD

**Issue by jeroenklein** [ionic-team/ionic#18555]
# Bug Report

**Ionic version:**
[x] **4.5.0**

**Current behavior:**
If the ``disabled`` attribute on the ``icon-only ion-button`` is set programatically or via HTML, there is no styling to reflect this. The button cannot be clicked, but there is no indicator to show the disabled status.

**Expected behavior:**

On ``V4.4.2`` everything is working fine. See https://codepen.io/jeroenklein/pen/BgoOqY

**Steps to reproduce:**

https://codepen.io/jeroenklein/pen/GzpRrQ

**Related code:**

https://codepen.io/jeroenklein/pen/GzpRrQ

**Other information:**

Related issues:
https://github.com/ionic-team/ionic/issues/18542

**Comment by KillerCodeMonkey** [comment]
should be fixed with: #18560
