### ISSUE TITLE
feat: make ion-fab-button size configurable via CSS variable

### ISSUE THREAD

**Issue by date80** [ionic-team/ionic#18558]
# Feature Request

**Ionic version:**
[x] 4.5

**Describe the Feature Request**
A standard _ion-fab-button_ has a hard-coded size of 56px - see _fab-button.vars.scss_:
`$fab-size:                              56px !default;`

For the button texts I want to display this is a little bit too small. Are there any plans/ would it be possible to introduce a CSS variable which can be overwritten by users of the framework?

**Comment by brandyscarney** [comment]
Thank you for the issue! The width/height is added to the host `ion-fab-button` element. You can style this element directly, see the Codepen here: https://codepen.io/brandyscarney/pen/gOPbXaQ?editors=1100

Please let me know if I am misunderstanding you and I will reopen this issue. Thanks!
