### ISSUE TITLE
White blank screen after splash screen on Android with Ionic 4

### ISSUE THREAD

**Issue by fer-fullstackdev** [ionic-team/ionic#18563]
I see that there are many developers who are facing this problem with ionic 4 project.
I have created new ionic 4 starter project
`ionic start myApp tabs`
and then added android platform, tried to run. 
But I get white screen after splash screen and app is never loaded.
I see many bug reports for this issue, but can't find right answer yet. 
Please answer for this issue, so that I can decide if I should use ionic latest version or not!
Thank you.

**Comment by Noaber** [comment]
I am (still) doing it like this (don't know if it's still needed).

In config.xml, I set AutohideSplashScreen = false en SplashScreenDelay = 30000 and in app.component.ts I do this.splashScreen.hide(); in this.platform.ready()

So when the the app is booted, the splash screen will disappear.
Ps: I faced this issue also in Ionic 3

**Comment by fer-fullstackdev** [comment]
Thanks, Noaber. 
But I am sure that this is related to Ionic v4. 
When I run the app, app.compoment.ts *constructor* function is not fired.

**Comment by indraraj26** [comment]
test this app and report : https://github.com/ionic-team/ionic-conference-app

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you run `ionic info` and post the output?

Thanks!

**Comment by pookdeveloper** [comment]
I have the same problem I execute: ionic cordova run android --device
And the app show blank:

![image](https://user-images.githubusercontent.com/3384734/59777373-da8db780-92b4-11e9-91e2-535179d79bfe.png)

Thanks

**Comment by liamdebeasi** [comment]
A few things for people to try:

1. If you have a `polyfills.ts` file, be sure to enable any polyfills in there.
2. Ensure you are on the latest version of Ionic.

If after doing both of those things, you are still unable to get your app to work, please post a repo with the code required to reproduce this issue.

Thanks!
