### ISSUE TITLE
[ionic v4] build for browser. Could not find cordova.js script tag.

### ISSUE THREAD

**Issue by gudtkd928** [ionic-team/ionic#18565]
# Bug Report
**Ionic version:**
[x] **4.12.0**

**Current behavior:**
My project offers Android, web services as ionic.
I used v3 and I recently migrated to v4.

Android is no problem.
The web service uses firebase hosting, and the following error is displayed on the console.
Could not find cordova.js script tag. Plugin loading may fail.
This.platform.is('cordova') also returns true.

This does not occur in the development environment (local deployment).

**Expected behavior:**
On the web, this.platform.is('cordova') should be false.
And cordova_plugins.js should not be added automatically.

**Steps to reproduce:**
We have built the following for web deployment:
ionic cordova build browser --prod

**Other information:**
After the build, the script is added automatically as shown below.
platforms/browser/www/index.html
```
<script type="text/javascript" src="runtime.2e60a16c6e117d385511.js"></script><script type="text/javascript" src="es2015-polyfills.b6a15bd967a1a7dbe1a0.js" nomodule></script><script type="text/javascript" src="polyfills.3b992854afcaadf84bec.js"></script><script type="text/javascript" src="cordova.be00a3c9f5babbb22844.js"></script><script type="text/javascript" src="main.d1dd04adbe6dd750e532.js"></script>
```

After the deploy, cordova_plugins.js was added automatically in the head tag.
```
<script src="cordova_plugins.js"></script>
```

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.5
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.0.0, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 17 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/hscho/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v10.12.0 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by kensodemann** [comment]
@gudtkd928 - how are you doing your builds for the Firebase hosted deployment vs. the Android deployment?

For my PWA's, I will generally do `ionic build --engine=browser --prod`, though honestly I do not think the `--engine=browser` is required in this case. I will have to experiment without it. This does not try to load `cordova.js` in the `index.html` file.

For my Android build, I would then do `ionic cordova build android` which will include the `cordova.js` stuff.

**Comment by gudtkd928** [comment]
@liamdebeasi The following is reproduced. It's easier to reproduce than git repo.
```
ionic start myApp tabs
ionic cordova build browser --prod
```

After the build, script tag was added automatically in the body tag in www/index.html.
```
<script type="text/javascript" src="runtime.6cced9481d5a37bff851.js"></script><script type="text/javascript" src="es2015-polyfills.504a17b42164056589df.js" nomodule></script><script type="text/javascript" src="polyfills.9ccc9e25ed7d36fbe127.js"></script><script type="text/javascript" src="cordova.be00a3c9f5babbb22844.js"></script><script type="text/javascript" src="main.01a922b5560420e45fe6.js"></script>
```

I did the same in v3 and it does not happen.
```
ionic start myApp tabs --type=ionic-angular
ionic cordova build browser --prod
```

**Comment by kensodemann** [comment]
@gudtkd928 - I just noticed you are using Cordova's `browser` platform. That is not really a good practice for deploying a web application. Instead, you should develop your application to use Cordova plugins in a cordova context (`this.platform.is('cordova')`) and a web API in a non-cordova context.

The browser platform is more or less a "testing" platform and not really something that is good for deployment. Many plugins do not work with the browser platform, and others provide fake testing data when used with the browser platform. Web APIs, or using Capacitor instead of Cordova, are far better options if you want to do a web deployment and target browsers as well as doing a hybrid native implementation.

If you want to target the browser without a hybrid native target (which I have done with a couple of apps), then I would remove the Cordova layer entirely and just use web APIs.

**Comment by gudtkd928** [comment]
All Cordova related my api are used in the context of the cordova (this.platform.is ('cordova')). 
The problem is this.platform.is ('cordova') on the web return true.
It should return false.
I think that Cordova .js is not added on the web.

My project is currently serviced by android and web, and plans to support iOS (on pwa) soon. It is not web only.

I am migrated from v3 to v4 according to the guide (it took 3 months).
Should I go back to v3? Does it support only pwa on the web? Or is it not supported in this case, do I have to use additional capacitor?

All of them worked normally in v3.
I would like to ask you not to add cordova.js automatically as in v3 when ionic cordova build browser, or to let me know by options or at least how I can control this.

thanks

**Comment by gudtkd928** [comment]
This is the Republic of Korea. It 's three o'clock in the morning.
I can not wait any longer, so I'm going home.

I would like to hear whether this is a my mistake, a ionic bug, support for this issue,
Or does not officially support web distribution without pwa in ionic v4 and so on.

For information, our plan to:
android: ionic android app on google play store (working)
web: web deploy on firebase hosting (working in v3. but problem now)
ios: ionic pwa on ionic hub. (developing soon)

Both android and web worked fine in v3, but web is a problem with v4.
Let us know what we need to do.

thank you.

**Comment by kensodemann** [comment]
@gudtkd928 - let me try explaining what I was saying a little more plainly

When building for the web, do not use `ionic cordova build browser --prod`. This uses the Cordova "browser" platform. This is bad. Don't do it. This is probably why `this.platform.is('cordova')` is returning true for you.

Instead, try using just `ionic build --prod` as I stated in my first response.

**Comment by gudtkd928** [comment]
I misunderstood your answer.
I understood you to say the following:
Do not use cordova to develop  web application. for web application, redevelop without cordova. 
Sorry.

The issue is resolved using:
```
ionic build --prod
```

thank you.

**Comment by kensodemann** [comment]
Excellent! I am going to close this issue then.
