### ISSUE TITLE
bug: ion-safe-area-top excesive Edge

### ISSUE THREAD

**Issue by carlosnewmusic** [ionic-team/ionic#18574]
# Bug Report

**Ionic version:**
[x] **4.5**

**Current behavior:**
![image](https://user-images.githubusercontent.com/19379457/59700827-87543000-91f4-11e9-91c9-bb8a94650538.png)

**Expected behavior:**
![image](https://user-images.githubusercontent.com/19379457/59701248-75bf5800-91f5-11e9-9dd4-66170cd70c32.png)

**Related code:**
https://pastebin.com/6TXrkFQf

**Other information:**
referenced error
https://github.com/ionic-team/ionic/issues/15502

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.0.2 (C:\Users\Administrador\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 5 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.5

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Which device/browser are you testing this on?

Thanks!

**Comment by carlosnewmusic** [comment]
Windows 10 V 10.0.17763 compilation 17763, microsoft edge 44.17763.1.0

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as we recently released Ionic Framework v5 which dropped support for IE11 and older versions of Edge. Moving forward, Ionic Framework v4 will only receive critical security patches.
