### ISSUE TITLE
bug: Unexpected layout break on split-pane menu on iOS

### ISSUE THREAD

**Issue by Orionnss** [ionic-team/ionic#18583]
# Bug Report

**Ionic version:**

[x] **4.4.2**

**Current behavior:**

My Split-pane menu break when viewing on devapp on iOS (devapp and using "Inspect element").
Screenshots : 
![ionic small screen bug](https://user-images.githubusercontent.com/7023282/59857274-e6db4880-9378-11e9-80a8-303ffca918db.png)

**Expected behavior:**

Should have the layout it has on bigger screens.
![ionic small screen expected behaviour](https://user-images.githubusercontent.com/7023282/59857307-f5296480-9378-11e9-8415-211e91b6c0b5.png)

**Steps to reproduce:**

Load a split-pane menu using a small screen preview 'iPhone 6/7/8s' with Firefox.

**Related code:**

**app.component.html**
```
<ion-split-pane>
    <ion-menu class="menu">
      <ion-header>
        <ion-toolbar>
          <img class="menu-logo" src="../assets/logo.png" />
        </ion-toolbar>
      </ion-header>
      <ion-content color="menu" class="menu-content">
        <ion-list>
          <ion-menu-toggle auto-hide="false">

            <ion-item-divider>
              <ion-label>
                Matchs
              </ion-label>
            </ion-item-divider>
            <ion-item class="menu-item" routerLinkActive="active-menu-item" [routerDirection]="'root'" [routerLink]="[menuAct.url]" *ngFor="let menuAct of mainMenu">
              <ion-icon slot="start" [name]="menuAct.icon"></ion-icon>
              <ion-label>
                {{menuAct.title}}
              </ion-label>
            </ion-item>

            <ion-item-divider *ngIf="isSubscribed">
              <ion-label>
                Chat
              </ion-label>
            </ion-item-divider>
            <div *ngIf="isSubscribed">
              <ion-item class="menu-item" routerLinkActive="active-menu-item" [routerDirection]="'root'" [routerLink]="[chatAct.url]" *ngFor="let chatAct of chatMenu">
                <ion-icon slot="start" [name]="chatAct.icon"></ion-icon>
                <ion-label>
                  {{chatAct.title}}
                </ion-label>
              </ion-item>
            </div>


            <ion-item-divider>
              <ion-label>
                Autres
              </ion-label>
            </ion-item-divider>
            <ion-item class="menu-item" routerLinkActive="active-menu-item" [routerDirection]="'root'" [routerLink]="[otherAct.url]" *ngFor="let otherAct of otherMenu">
              <ion-icon slot="start" [name]="otherAct.icon"></ion-icon>
              <ion-label>
                {{otherAct.title}}
              </ion-label>
            </ion-item>

          </ion-menu-toggle>
        </ion-list>
      </ion-content>
    </ion-menu>
    <ion-router-outlet main></ion-router-outlet>
  </ion-split-pane>
```

**app.component.ts**
```
import { Component } from "@angular/core";

import { Platform } from "@ionic/angular";
import { SplashScreen } from "@ionic-native/splash-screen/ngx";
import { StatusBar } from "@ionic-native/status-bar/ngx";
import { SettingsPage } from './settings/settings.page';

@Component({
  selector: "app-root",
  templateUrl: "app.component.html"
})
export class AppComponent {
  isSubscribed: Boolean = (localStorage.getItem('is_subscribed') == "true");
  public mainMenu = [
    {
      title: "Calendrier",
      url: "/matchs",
      icon: "calendar"
    },
    {
      title: "Matchs en attente",
      url: "/waiting-matchs",
      icon: "alarm"
    }
  ];

  public chatMenu = [
    {
      title: "Annonces",
      url: "/chat/annonces",
      icon: "megaphone"
    }, {
      title: "Par match",
      url: "/match-chatroom-selector",
      icon: "football"
    }, {
      title: "Fans du complexe",
      url: "/chat/complexe",
      icon: "star"
    }, {
      title: "Page de test",
      url: "/test-page",
      icon: "list"
    }
  ];

  public otherMenu = [
    {
      title: "Paramètres",
      url: "/settings",
      icon: "settings"
    }
  ]

  constructor(
    private platform: Platform,
    private splashScreen: SplashScreen,
    private statusBar: StatusBar
  ) {
    this.initializeApp();
  }

  initializeApp() {
    this.platform.ready().then(() => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();
    });
  }

  ngOnInit() {
  }
}

```

It's one of my first issues so feel free to help me improve it.

I'm on an internship so I'm limited about the screens I can post .

UPDATE : I noticed that it only happens on iOS.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.0.2 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 6 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v11.15.0 (/usr/bin/node)
   npm    : 6.9.0
   OS     : Linux 4.18
```

**Comment by ranjeetmca** [comment]
Hi @Orionnss Can you please try  html code of app.component.html inside <ion-app></ion-app>

Hope it will work!

**Comment by Orionnss** [comment]
> Hi @Orionnss Can you please try html code of app.component.html inside
> 
> Hope it will work!

I'm sorry I did not understand what you meant :/

**Comment by ranjeetmca** [comment]
@Orionnss I'm sorry for my mistake. Please replace your code with this one-:
<ion-app>
<ion-split-pane>
    <ion-menu class="menu">
      <ion-header>
        <ion-toolbar>
          <img class="menu-logo" src="../assets/logo.png" />
        </ion-toolbar>
      </ion-header>
      <ion-content color="menu" class="menu-content">
        <ion-list>
          <ion-menu-toggle auto-hide="false">

            <ion-item-divider>
              <ion-label>
                Matchs
              </ion-label>
            </ion-item-divider>
            <ion-item class="menu-item" routerLinkActive="active-menu-item" [routerDirection]="'root'" [routerLink]="[menuAct.url]" *ngFor="let menuAct of mainMenu">
              <ion-icon slot="start" [name]="menuAct.icon"></ion-icon>
              <ion-label>
                {{menuAct.title}}
              </ion-label>
            </ion-item>

            <ion-item-divider *ngIf="isSubscribed">
              <ion-label>
                Chat
              </ion-label>
            </ion-item-divider>
            <div *ngIf="isSubscribed">
              <ion-item class="menu-item" routerLinkActive="active-menu-item" [routerDirection]="'root'" [routerLink]="[chatAct.url]" *ngFor="let chatAct of chatMenu">
                <ion-icon slot="start" [name]="chatAct.icon"></ion-icon>
                <ion-label>
                  {{chatAct.title}}
                </ion-label>
              </ion-item>
            </div>


            <ion-item-divider>
              <ion-label>
                Autres
              </ion-label>
            </ion-item-divider>
            <ion-item class="menu-item" routerLinkActive="active-menu-item" [routerDirection]="'root'" [routerLink]="[otherAct.url]" *ngFor="let otherAct of otherMenu">
              <ion-icon slot="start" [name]="otherAct.icon"></ion-icon>
              <ion-label>
                {{otherAct.title}}
              </ion-label>
            </ion-item>

          </ion-menu-toggle>
        </ion-list>
      </ion-content>
    </ion-menu>
    <ion-router-outlet main></ion-router-outlet>
  </ion-split-pane>
</ion-app>

**Comment by Orionnss** [comment]
> @Orionnss I'm sorry for my mistake. Please replace your code with this one-:
> 
> 
> 
> 
> 
> ![](../assets/logo.png)
> 
> 
> 
> 
> ```
>         <ion-item-divider>
>           <ion-label>
>             Matchs
>           </ion-label>
>         </ion-item-divider>
>         <ion-item class="menu-item" routerLinkActive="active-menu-item" [routerDirection]="'root'" [routerLink]="[menuAct.url]" *ngFor="let menuAct of mainMenu">
>           <ion-icon slot="start" [name]="menuAct.icon"></ion-icon>
>           <ion-label>
>             {{menuAct.title}}
>           </ion-label>
>         </ion-item>
> 
>         <ion-item-divider *ngIf="isSubscribed">
>           <ion-label>
>             Chat
>           </ion-label>
>         </ion-item-divider>
>         <div *ngIf="isSubscribed">
>           <ion-item class="menu-item" routerLinkActive="active-menu-item" [routerDirection]="'root'" [routerLink]="[chatAct.url]" *ngFor="let chatAct of chatMenu">
>             <ion-icon slot="start" [name]="chatAct.icon"></ion-icon>
>             <ion-label>
>               {{chatAct.title}}
>             </ion-label>
>           </ion-item>
>         </div>
> 
> 
>         <ion-item-divider>
>           <ion-label>
>             Autres
>           </ion-label>
>         </ion-item-divider>
>         <ion-item class="menu-item" routerLinkActive="active-menu-item" [routerDirection]="'root'" [routerLink]="[otherAct.url]" *ngFor="let otherAct of otherMenu">
>           <ion-icon slot="start" [name]="otherAct.icon"></ion-icon>
>           <ion-label>
>             {{otherAct.title}}
>           </ion-label>
>         </ion-item>
> 
>       </ion-menu-toggle>
>     </ion-list>
>   </ion-content>
> </ion-menu>
> <ion-router-outlet main></ion-router-outlet>
> ```

@ranjeetmca 

Thank you but the code is truncated

**Comment by ranjeetmca** [comment]
`﻿<ion-app>
<ion-split-pane>
    <ion-menu class="menu">
      <ion-header>
        <ion-toolbar>
          <img class="menu-logo" src="" />
        </ion-toolbar>
      </ion-header>
      <ion-content color="menu" class="menu-content">
        <ion-list>
          <ion-menu-toggle auto-hide="false">

            <ion-item-divider>
              <ion-label>
                Matchs
              </ion-label>
            </ion-item-divider>
            <ion-item class="menu-item" routerLinkActive="active-menu-item" [routerDirection]="'root'" [routerLink]="[menuAct.url]" *ngFor="let menuAct of mainMenu">
              <ion-icon slot="start" [name]="menuAct.icon"></ion-icon>
              <ion-label>
                {{menuAct.title}}
              </ion-label>
            </ion-item>

            <ion-item-divider *ngIf="isSubscribed">
              <ion-label>
                Chat
              </ion-label>
            </ion-item-divider>
            <div *ngIf="isSubscribed">
              <ion-item class="menu-item" routerLinkActive="active-menu-item" [routerDirection]="'root'" [routerLink]="[chatAct.url]" *ngFor="let chatAct of chatMenu">
                <ion-icon slot="start" [name]="chatAct.icon"></ion-icon>
                <ion-label>
                  {{chatAct.title}}
                </ion-label>
              </ion-item>
            </div>


            <ion-item-divider>
              <ion-label>
                Autres
              </ion-label>
            </ion-item-divider>
            <ion-item class="menu-item" routerLinkActive="active-menu-item" [routerDirection]="'root'" [routerLink]="[otherAct.url]" *ngFor="let otherAct of otherMenu">
              <ion-icon slot="start" [name]="otherAct.icon"></ion-icon>
              <ion-label>
                {{otherAct.title}}
              </ion-label>
            </ion-item>

          </ion-menu-toggle>
        </ion-list>
      </ion-content>
    </ion-menu>
    <ion-router-outlet main></ion-router-outlet>
  </ion-split-pane>
  <ion-router-outlet></ion-router-outlet>
</ion-app>`

**Comment by ranjeetmca** [comment]
![Screenshot](https://user-images.githubusercontent.com/13328687/60066832-e6023800-9725-11e9-8579-9521040c68c3.png)

**Comment by Orionnss** [comment]
> ![Screenshot](https://user-images.githubusercontent.com/13328687/60066832-e6023800-9725-11e9-8579-9521040c68c3.png)

It's exactly my own code

**Comment by Orionnss** [comment]
Ok, in fact it was just some CSS values that are needed on iOS and not on Android (--color, --background, and a ion-toolbar misplaced).
