### ISSUE TITLE
bug: Conference app crashes after one week on iOS device

### ISSUE THREAD

**Issue by santhoshraje** [ionic-team/ionic#18594]
# Bug Report

**Ionic version:**

[x] **5.0.2**

**Current behavior:**

The ionic conference app crashes after being installed on an iPhone 8 Plus (iOS version: 12.3.2). App runs fine for one week before the crash happens.
**Video of the behaviour: **https://youtu.be/3MuIB666U-Y

**Expected behavior:**

App should load and run instead of crashing. 

**Steps to reproduce:**

1. Create a new project using the ionic CLI and select the conference app
2. Follow the steps listed here: https://ionicframework.com/docs/building/ios
3. Open the Xcode project, sign the app and deploy it to the device.
4. Let it be installed on the device for one week.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```
Ionic:

   Ionic CLI : 5.0.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v11.5.0
   npm    : 6.9.0
   OS     : macOS Mojave

**Comment by ranjeetmca** [comment]
Hi, @santhoshraje please try below

ionic cordova platform rm ios
ionic cordova platform add ios

**Comment by santhoshraje** [comment]
@ranjeetmca Hi! Thanks for the advice. I will try removing and adding the platform and testing it on my device for one week again. Will update here after my testing.

**Comment by santhoshraje** [comment]
@ranjeetmca thanks for the suggestion. Unfortunately this did not work. 

Quick update: I tried factory resetting both my iPhone and development environment and reinstalling ionic and the app (just the basic blank app this time), but the same thing happened. 

Giving up on ionic for now. Will be trying Flutter next.

**Comment by santhoshraje** [comment]
It took a really long time but I figured it out. iOS apps stop working on the device after 7 days if you are using a free developer account. Looks like it was not a problem with ionic after all.

https://stackoverflow.com/questions/38307356/iphone-app-under-test-crashes-after-a-few-days
