### ISSUE TITLE
feat: ion-video - component to autoplay & pause videos on scroll

### ISSUE THREAD

**Issue by Bengejd** [ionic-team/ionic#18603]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
A component that users can quickly drop in, to include inline videos with auto play & pause functionality on scroll.

**Describe Preferred Solution**
A custom component, utilizing the intersectionObserver api to handle pausing & playing the video as it enters the viewport.

**Describe Alternatives**
Native `<video>` element with intersectionObserver hooked into a component. Similar to what i've described above.

**Additional Context**
Related [medium](https://medium.com/@JordanBenge/ionic-4-autoplay-videos-on-scroll-6eb00213cdb4) article.

I am willing to submit a PR request for this feature, and have already mocked up the desired behavior. Submitting PR here soon.

**Comment by liamdebeasi** [comment]
Thanks for the feature request! I am going to close this for the reason explained here: https://github.com/ionic-team/ionic/pull/18604#issuecomment-551976755
