### ISSUE TITLE
bug: ion-textarea or textarea doesn't reposition itself when keyboard appears on iOS 

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic#18613]
# Bug Report
The problem describe in this ticket https://github.com/ionic-team/ionic/issues/17847 is not fixed and still reproducible on iOS
I installed the latest ionic 4.5.0 and the problem is still there.

Note - the fix seems to be working when the ion-textarea is NOT the last control on the page. However the problem is clearly reproducible when it is the last one on the page (see the sample project).

**Ionic version:**

[x] **4.x**

**Current behavior:**

See https://github.com/ionic-team/ionic/issues/17847

**Expected behavior:**

See https://github.com/ionic-team/ionic/issues/17847

**Steps to reproduce:**

See https://github.com/ionic-team/ionic/issues/17847

**Related code:**
See https://github.com/ionic-team/ionic/issues/17847

See https://github.com/ionic-team/ionic/issues/17847

**Ionic info:**

See https://github.com/ionic-team/ionic/issues/17847

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this issue was resolved in Ionic Framework v5.1.1. If you are still running into issues after updating to the latest version of Ionic Framework, please open a new issue. Thanks!
