### ISSUE TITLE
bug: href on ion-card / ion-item navigates and reloads the page 

### ISSUE THREAD

**Issue by AVatch** [ionic-team/ionic#18616]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Add an `href` attribute to the `ion-card` or `ion-item` component and when clicking you see the entire app navigate and reload.

**Expected behavior:**

The app should navigate without reloading

**Steps to reproduce:**

**Related code:**

Github Repo: https://github.com/AVatch/href-issue

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.1.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v11.5.0 (/usr/local/Cellar/node/11.5.0/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by abennouna** [comment]
It looks that you use routes as `href` values, correct? In that case, you're probably looking for `routerLink` instead.
Also: https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#angular-href-does-not-cause-angular-router-to-navigate

**Comment by AVatch** [comment]
Thanks @abennouna - it seems though that the `ion-card` component does not have the `routerLink` attribute defined for it, So it does not seem to behave like the `ion-button` example.

**Comment by abennouna** [comment]
@AVatch I've changed the `href`s with `routerLink`s in your demo repo, and it works as advertised.

```
<ion-content>
  <ng-container *ngFor="let i of [0, 1, 2, 3, 4, 5]">
    <ion-card routerLink="/list/{{ i }}">
      <ion-card-content> Hello {{ i }} </ion-card-content>
    </ion-card>
  </ng-container>

  <ion-list>
    <ng-container *ngFor="let i of [0, 1, 2, 3, 4, 5]">
      <ion-item routerLink="/list/{{ i }}"> ITEM {{ i }} </ion-item>
    </ng-container>
  </ion-list>
</ion-content>
```

What does not work exactly?

**Comment by AVatch** [comment]
@abennouna you are correct - I needed to import the angular `RouterModule` into my feature module. 

I will close this as the feature works as advertised.

I would just suggest a note be added to the documentation since `href` is the only prop documented for `ion-card` https://ionicframework.com/docs/api/card

Thanks!
