### ISSUE TITLE
bug: unable to load images android

### ISSUE THREAD

**Issue by ctfrancia** [ionic-team/ionic#18619]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

there are three things that shows when trying to show images that are on the page. These images were taken from a phone, sent as base64 and then decoded.
1. Not allowed to load local resource: file:///storage/emulated/0/Android/data/io.ionic.dicus/cache/1561460070933.jpg
2. core.js:11210 WARNING: sanitizing unsafe URL value (the base 64 string)
3. GET unsafe:data:image/*charset=utf-8;base64,9j/adskfjhalsdkjdhflajdhsfljhaduiu net::ERR_UNKNOWN_URL_SCHEME

**Expected behavior:**

I would expect that the images are loaded

**Steps to reproduce:**

**Related code:**

#### component.html
```
<img *ngIf="message.image" [src]="message.image" />
```

#### chat.service.ts
```
// receiving messages
  public messages$(): Observable<Message[]> {
    this.socket.fromEvent<Message>('message').subscribe((msg: Message): void => {
      if (msg.image) {
        msg.image = 'data: image/jpg; base64,' + msg.image;
        this.activeConversation.messages.push(msg);
        this.bsMessages$.next(this.messages);
        this.conversationStorage.set(this.activeConversation.id, this.activeConversation);
      } else {
        // else code
      }
    });
    return this.bsMessages$.asObservable();
  }


//sending
  public sendMessage(msg: Message): void {
    if (msg.image) {
      const filePath: string = msg.image;
      this.base64.encodeFile(filePath).then((base64File: string): void => {
        msg.image = base64File;
        this.socket.emit('message', msg, (callback: string): void => {
          // callback stuff
        });
      });
    }
  }
```

**Other information:**

since this is issue is currently with Android the issues the solutions that I am getting are done in Java.
**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.1.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 7.1.4, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 12 other plugins)
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! Can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by ctfrancia** [comment]
oops sorry, meant to close this before. The main issue that I was having is that the Base64 has a default of `data:image/*;base64,` and the `*` isn't valid. However there is still the issue of the warning regarding `WARNING: sanitizing unsafe URL value`
