### ISSUE TITLE
bug: Some ionic components of the page do not show up for the first time when they are packaged and run on android

### ISSUE THREAD

**Issue by Mooiq** [ionic-team/ionic#18612]
Everything worked fine in chrome, but some parts of the page didn't show up when the package was running, and it didn't show up until I re-entered the page. I don't know what went wrong...
Ionic modules with problems:
Ion-segment: show only one ion-partition-button for the first time
Sometimes it also appears in this component: ion-item

ionic info：
- Ionic:
  - Ionic CLI                     : 5.0.0
  - Ionic Framework               : @ionic/angular 4.4.2
  - @angular-devkit/build-angular : 0.13.9
  - @angular-devkit/schematics    : 7.3.9
  - @angular/cli                  : 7.3.9
  - @ionic/angular-toolkit        : 1.5.1

- Cordova:
  - Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
  - Cordova Platforms : android 8.0.0
  - Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 8 other plugins)

- Utility:
  - cordova-res : 0.3.0
  - native-run  : not installed

- System:
  - NodeJS            : v8.12.0 
  - npm               : 6.9.0
  - OS                : Windows 10

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by Mooiq** [comment]
Thanks for your reply. I am not sure what went wrong.
you can run this [demo ](https://github.com/Mooiq/ionic5.0case)
