### ISSUE TITLE
bug: Annoying error that can only be solved by ctrl-s (re-build) 

### ISSUE THREAD

**Issue by aldwnesx** [ionic-team/ionic#18622]
Steps to reproduce:
Pops up randomly, only way I can "prevent" it is to hit ctrl s for it to build again, and then after that it appears randomly.

Picture : https://www.reddit.com/r/ionic/comments/c5912f/annoying_error_whenever_i_encounter_this_issue_i/

"dependencies": {
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@ionic-native/core": "^4.8.0",
    "@ionic-native/geolocation": "^4.8.0",
    "@ionic-native/google-maps": "^5.5.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.1.0",
    "cordova-plugin-geolocation": "4.0.1",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.1",
    "rxjs-compat": "^6.5.2",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.29"
  },

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! Can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by aldwnesx** [comment]
Hi,

I followed this tutorial 

https://www.joshmorony.com/using-google-maps-and-geolocation-in-ionic-with-capacitor/

**Comment by liamdebeasi** [comment]
Hi there,

The tutorial you linked to was developed with Ionic 3 in mind, so some of the dependencies and code requirements are going to be different for Ionic 4.

Can you provide a link to an already built project that has this issue?
