### ISSUE TITLE
[ionic v4 ]bug: build pwa. but not detect pwa

### ISSUE THREAD

**Issue by gudtkd928** [ionic-team/ionic#18621]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
I made a pwa build in ionic v4.
However, the platform does not recognize it as pwa.

**Expected behavior:**
this.platform.is('pwa') return true.

**Steps to reproduce:**
```
ionic start pwaTalk sidemenu
cd ./pwaTalk  && ng add @angular/pwa --project app
ionic build --prod
ws -p 7777 -d ./www
Connect to localhost:7777 in Chrome mobile mode.
```

**Related code:**

```
  initializeApp() {
    this.platform.ready().then(() => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();
      console.log('AppComponent', { pwa: this.platform.is('pwa') });
    });
  }
```

**Other information:**
The lighthouse test also recognizes it as pwa.
In Chrome devTools, both Manifest and Service Workers are recognized as pwa.

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI) : 4.12.0

System:

   NodeJS : v10.12.0
   npm    : 6.9.0
   OS     : macOS Mojave

johyeongsang-ui-MacBook-Pro:ionic hscho$ cd pwaTalk/
johyeongsang-ui-MacBook-Pro:pwaTalk hscho$ ionic info

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v10.12.0 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Which device/operating system version are you testing this on?

Thanks!

**Comment by gudtkd928** [comment]
In both of the following cases:

- iphone on chrome devTools
User Agent Mozilla / 5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit / 604.1.38 (KHTML, like Gecko) Version / 11.0 Mobile / 15A372 Safari / 604.1

- iphone x (simulator) os 12.2
I can not get a use agent because I do not know how to view the log on the iphone on simulator.

Is there a way to view the logs in pwa on iPhone?
Perhaps it is not going to be except for Chrome devtools.

Thanks

**Comment by gudtkd928** [comment]
Correction.

In chrome devtools, platform.is('pwa') is returned as false.
on iphone x (simulator) os 12.2, platform.is('pwa') is returned as true.
I guess I was mistaken for something or a cache on Safari.

Sorry for the confusion.

And because the simulator can not see the console logs
In chrome devtools, i will be developing with tricks like /?mode=standalone.

Thanks.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you provide a repo with the code required to reproduce this issue?
