### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by shrihari1999** [ionic-team/ionic#18648]
**Current behavior:**
ion select's alert interface option not accepting css class.

**Expected behavior:**
Accepts custom css class and shows alert accordingly.

**Steps to reproduce:**
For ion select with alert interface, pass interface options with custom css class

```
<ion-select interface="alert" [interfaceOptions]="customOptions" placeholder="Select Item">
          <ion-select-option>A</ion-select-option>
          <ion-select-option>B</ion-select-option>
          <ion-select-option>C</ion-select-option>
</ion-select>
```
.ts
```
//imports

export class Sample{
//....
customOptions: any = {
    header:'Header works, class doesnt!',
    cssClass:'dropdown'
  };
//....
}
```
.scss
```
ion-select.dropdown{
    --background:green;
    --min-width:500px;
    --min-height:500px;
}
```

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.7
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. I am going to close this as this is a support question.

The `cssClass` is applied to the `ion-alert` element that appears, not the `ion-select` element. Your CSS should target `ion-alert.dropdown` instead.

Thanks!

**Comment by shrihari1999** [comment]
Hey liam!,

I tried applying the cssClass to ion-alert previously as well, in v4.5 as well as v5.2. Are you sure the issue is unable to be reproduced?

**Comment by liamdebeasi** [comment]
If you provide a repo with the code required to reproduce this issue, I can take another look. Thanks!

**Comment by shrihari1999** [comment]
Sure! Here is a test repo... 

https://github.com/shrihari1999/testApp

**Comment by liamdebeasi** [comment]
Thanks for the follow up. A few things I noticed:

1. When setting the cssClass property, you don't need to put a period before the class name. So just do `cssClass: "dropdown"` instead of `cssClass: ".dropdown"`.
2. You should place your alert's custom css in `global.scss` not in `home.page.scss`.

After making those two changes, the styles were properly applied.

**Comment by shrihari1999** [comment]
Thanks! Worked perfectly.
