### ISSUE TITLE
bug: Ionic/vue ionicons error

### ISSUE THREAD

**Issue by jepiqueau** [ionic-team/ionic#18640]
# Bug Report

**Ionic version:**

[x] **4.x**
@ionic/vue@0.0.4 or @ionic/vue@next
 
**Current behavior:**

When updating vue apps developed with Ionic/vue@0.0.4 and running the 
``` 
npm install 
``` 
after having deleted the node_modules folder, i got the following error 
```  
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at addIcons (chunk-ea2b3dce.js?d602:13)
    at appInitialize (ionic-vue.esm.js?481b:279)
    at Object.install (ionic-vue.esm.js?481b:687)
    at Function.Vue.use (vue.runtime.esm.js?2b0e:5101)
    at eval (main.js?56d7:12)
    at Module../src/main.js (app.js:10193)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at Object.1 (app.js:10267)  
``` 

**Expected behavior:**

Should be able to load ionicons. this was working perfect when @ionic/core@4.4.0 and ionicons@4.5.6 were dependencies. Now when you reinstall from scratch the dependencies are @ionic/core@4.6.0 and ionicons@4.5.10-2 and it is failing both for @ionic/vue@0.0.4 and @ionic/vue@next 

**Steps to reproduce:**

- take an existing vue apps running with @ionic/core@4.4.0 and ionicons 4.5.6
- delete the folder node_modules
- delete the package-lock.json
- npm install

**Related code:**
look at 
```  
https://github.com/jepiqueau/vue-test-stencil-svgpaths-morphing 
```  
which fails
look at 
```  
https://github.com/jepiqueau/vue-test-stencil-colorpicker 
``` 
which works

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI : 5.0.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by Westclair** [comment]
I'm seeing the same issue. It is probably related to the warning that appears when running `ionic serve`:

```
warning  in ./node_modules/@ionic/vue/dist/ionic-vue.esm.js
"export 'ICON_PATHS' was not found in 'ionicons/icons'
```

**Comment by jakubkoje** [comment]
Same here.

**Comment by jepiqueau** [comment]
the work around i found is to first install
``` 
npm install @ionic/core@one 
npm install @ionic/vue@0.0.4
```
modify the main.js file 
``` 
import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
//import Ionic from "@ionic/vue"; // comment this line 
import { defineCustomElements as ionic } from "@ionic/core/loader"; // add a direct link to @ionic/core
import { defineCustomElements as svgmorphing } from "stencil-svgpaths-morphing/dist/loader";

import "@ionic/core/css/ionic.bundle.css";

//Vue.config.ignoredElements = [/jeep-\w*/]; // comment this line
Vue.config.ignoredElements = [/^ion-/, /^jeep-/];   // add this line

//Vue.use(Ionic);  // comment this line
ionic(window); // add this line
svgmorphing(window);

Vue.config.productionTip = false;

new Vue({
  router,
  store,
  render: h => h(App)
}).$mount("#app");
``` 
and keep the file router.js as it is meaning still using the IonicVueRouter

and it works fine.
Now if you look at package-lock.json , 
``` 
@ionic/core is version "4.6.0-dev.201906131724.645b9a9" requiring "ionicons": "4.5.9-1"
@ionic/vue is version 0.0.4 with dependencies @ionic/core@4.6.0 requiring "ionicons": "4.5.10-2
```

**Comment by jepiqueau** [comment]
In fact to see the icons  the main.js should be :
``` 
import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import { defineCustomElements as ionic } from "@ionic/core/loader"; // added line
import { defineCustomElements as svgmorphing } from "stencil-svgpaths-morphing/dist/loader";

//import Ionic from "@ionic/vue"; // commented line
import { addIcons } from "ionicons"; // added line
import { ICON_PATHS } from "ionicons/icons"; // added line
import "@ionic/core/css/ionic.bundle.css";

//Vue.config.ignoredElements = [/jeep-\w*/];  // commented line
Vue.config.ignoredElements = [/^ion-/, /^jeep-/]; // added line

//Vue.use(Ionic); // commented line
ionic(window); // added line
svgmorphing(window);
addIcons(ICON_PATHS); // added line
Vue.config.productionTip = false;

new Vue({
  router,
  store,
  render: h => h(App)
}).$mount("#app");
``` 
Now the icons are displayed
This can be use as workaround till @ionic/vue is updated to @ionic/core@one

**Comment by jepiqueau** [comment]
see for a complete implementation
``` 
https://github.com/jepiqueau/vue-test-stencil-svgpaths-morphing/tree/ionicone
```

**Comment by Abdlrahmansaber** [comment]
I'm facing  the same issue. Cant serve freshly created app.

**Comment by mbilbao** [comment]
Same here

**Comment by Abdlrahmansaber** [comment]
Temporarily, 
- common anything related to Icons in these file (ionic-vue.esm.js, chunk file that's show in console)

I did this,  and app worked for me but that's not the right solution, but you can do this now to can continue your work 

if you can't find these file go to project directory and from computer/lap search right the first name of file. (if you search for ionic-vue.esm.js write -> ionic and will appear all files/folders started with ionic then choose the file you're looking for in this case (you should choose ionic-vue.esm.js ).

![Screenshot_15](https://user-images.githubusercontent.com/24596397/60303012-9eea9180-9935-11e9-9166-4f96d2b3af7a.png)
![Screenshot_16](https://user-images.githubusercontent.com/24596397/60303013-9eea9180-9935-11e9-8a6d-405bc8ea787d.png)
![Screenshot_17](https://user-images.githubusercontent.com/24596397/60303014-9f832800-9935-11e9-9e6f-05ebc2177b48.png)
![Screenshot_18](https://user-images.githubusercontent.com/24596397/60303016-9f832800-9935-11e9-958c-e7b04b292bc0.png)

**Comment by Adrianmed** [comment]
Abdlrahmansaber's solution works, 
(He means "Comment" not "Common") You want to comment out the lines he commented out in his screenshots.

**Comment by Abdlrahmansaber** [comment]
Thank you Adrianmed :)

**Comment by Abdlrahmansaber** [comment]
probably I know the reason of this bug 

the reason because if you trying to import the {ICON_PATH} it's return nothing, try to print it in console it will return nothing.



![Screenshot_13](https://user-images.githubusercontent.com/24596397/60377866-c5362d00-9a1a-11e9-8747-4aa8eaf06829.png)


![Screenshot_11](https://user-images.githubusercontent.com/24596397/60377574-9cad3380-9a18-11e9-895e-7d6d181c224f.png)

**Comment by wannymiarelli** [comment]
@Adrianmed @Abdlrahmansaber yes it works but kill the icons so this is not a temporary solution for a released app :)

**Comment by mbilbao** [comment]
I've applied the solution of @Abdlrahmansaber. But it's not working properly.
I'm trying to follow that: https://ionicframework.com/blog/announcing-the-ionic-vue-beta/
But in the moment I add 
`import Ionic from '@ionic/vue';
import '@ionic/core/css/ionic.bundle.css';

Vue.use(Ionic);` 
 to main.js all I get is a "blank" page.
![image](https://user-images.githubusercontent.com/7300293/60383984-fe04ef00-9a78-11e9-9562-e9d1a3de3f1a.png)

Current dependencies versions:
`"dependencies": {
    "@ionic/vue": "0.0.4",
    "vue": "^2.6.10",
    "vue-router": "^3.0.3"
  },
  "devDependencies": {
    "@vue/cli-service": "^3.8.0",
    "vue-template-compiler": "^2.6.10"
  }`

**Comment by wannymiarelli** [comment]
> I've applied the solution of @Abdlrahmansaber. But it's not working properly (the compile warning and console error disapeared).
> I'm trying to follow that: https://ionicframework.com/blog/announcing-the-ionic-vue-beta/
> But in the moment I add
> 
> ```
> import Ionic from '@ionic/vue';
> import '@ionic/core/css/ionic.bundle.css';
> 
> Vue.use(Ionic);
> ```
> 
> to **main.js** all I get is a "blank" page.
> ![image](https://user-images.githubusercontent.com/7300293/60383984-fe04ef00-9a78-11e9-9562-e9d1a3de3f1a.png)
> 
> Current dependencies versions:
> "dependencies": {
> "@ionic/vue": "0.0.4",
> "vue": "^2.6.10",
> "vue-router": "^3.0.3"
> },
> "devDependencies": {
> "@vue/cli-service": "^3.8.0",
> "vue-template-compiler": "^2.6.10"
> }

The solution of @Abdlrahmansaber does not tell you to re-add the icons package :)
It works fine but as i said before kills out the icons. I think that there is some kind of issues with the icons package so reimporting it manually is not going to work.

**Comment by jepiqueau** [comment]
You should use the one I suggested two days ago it works and you see the icons

**Comment by Abdlrahmansaber** [comment]
@wannymiarelli I know it's killed the icon but you can develop whole app without icon until fix the bug

as you're right it's not solution for released app

**Comment by Abdlrahmansaber** [comment]
@mbilbao can you show me the console ?

**Comment by daarioautumn** [comment]
I get this  resolved by changing ionicons version in package-lock.json
![Screenshot from 2019-06-30 20-25-49](https://user-images.githubusercontent.com/13251413/60397673-55888500-9b75-11e9-9e51-246c1ef8e897.png)

**Comment by mbilbao** [comment]
> @mbilbao can you show me the console ?

Hey, the console was clear, without any error, warnings or whatever shows when you check verbose mode.
I already downgraded the ionicons package as @daarioautumn posted and it works.
Thank you @Abdlrahmansaber anyway.

**Comment by yasin-mesut** [comment]
Just add `ionicons@4.5.9-1` to your package.json. This just overrides any peer dependency and can be used as a workaround.

**Comment by liucf** [comment]
same issue... how to fix it?

**Comment by travega** [comment]
> I've applied the solution of @Abdlrahmansaber. But it's not working properly (the compile warning and console error disapeared).
> I'm trying to follow that: https://ionicframework.com/blog/announcing-the-ionic-vue-beta/
> But in the moment I add
> 
> ```
> import Ionic from '@ionic/vue';
> import '@ionic/core/css/ionic.bundle.css';
> 
> Vue.use(Ionic);
> ```
> 
> to **main.js** all I get is a "blank" page.
> ![image](https://user-images.githubusercontent.com/7300293/60383984-fe04ef00-9a78-11e9-9562-e9d1a3de3f1a.png)
> 
> Current dependencies versions:
> "dependencies": {
> "@ionic/vue": "0.0.4",
> "vue": "^2.6.10",
> "vue-router": "^3.0.3"
> },
> "devDependencies": {
> "@vue/cli-service": "^3.8.0",
> "vue-template-compiler": "^2.6.10"
> }

@mbilbao I have the same issue. Did you find a fix?

**Comment by hakanpinar** [comment]
I have the same issue. I looked couple hours on internet to find a solution but I didn't find a proper way to resolve this problem. Can someone help me?

**Comment by mbilbao** [comment]
> > I've applied the solution of @Abdlrahmansaber. But it's not working properly (the compile warning and console error disapeared).
> > I'm trying to follow that: https://ionicframework.com/blog/announcing-the-ionic-vue-beta/
> > But in the moment I add
> > ```
> > import Ionic from '@ionic/vue';
> > import '@ionic/core/css/ionic.bundle.css';
> > 
> > Vue.use(Ionic);
> > ```
> > 
> > 
> > to **main.js** all I get is a "blank" page.
> > ![image](https://user-images.githubusercontent.com/7300293/60383984-fe04ef00-9a78-11e9-9562-e9d1a3de3f1a.png)
> > Current dependencies versions:
> > "dependencies": {
> > "@ionic/vue": "0.0.4",
> > "vue": "^2.6.10",
> > "vue-router": "^3.0.3"
> > },
> > "devDependencies": {
> > "@vue/cli-service": "^3.8.0",
> > "vue-template-compiler": "^2.6.10"
> > }
> 
> @mbilbao I have the same issue. Did you find a fix?

Yes, I applied the solution of @daarioautumn just downgrade the ionicons package to 4.5.8

**Comment by grzegorz-bielski** [comment]
@yasin-mesut solution works for me

**Comment by mbougarne** [comment]
Just install the ionic package: `npm install ionicons@4.5.9-1 --save-dev` as @yasin-mesut suggested

**Comment by adida** [comment]
@jepiqueau your workaround worked for me but now I have content added to the end of every ion-item in my app:
![image](https://user-images.githubusercontent.com/8125790/60543162-40028f00-9d1e-11e9-849c-fa7d42fad006.png)
Have you encountered this issue? Do you know how to solve it?

**Comment by hakanpinar** [comment]
I just moved to normal Ionic with Angular. But  I still want to develope my project with vue framework *sad*

**Comment by woodstream** [comment]
> > > I've applied the solution of @Abdlrahmansaber. But it's not working properly (the compile warning and console error disapeared).
> > > I'm trying to follow that: https://ionicframework.com/blog/announcing-the-ionic-vue-beta/
> > > But in the moment I add
> > > ```
> > > import Ionic from '@ionic/vue';
> > > import '@ionic/core/css/ionic.bundle.css';
> > > 
> > > Vue.use(Ionic);
> > > ```
> > > 
> > > 
> > > to **main.js** all I get is a "blank" page.
> > > ![image](https://user-images.githubusercontent.com/7300293/60383984-fe04ef00-9a78-11e9-9562-e9d1a3de3f1a.png)
> > > Current dependencies versions:
> > > "dependencies": {
> > > "@ionic/vue": "0.0.4",
> > > "vue": "^2.6.10",
> > > "vue-router": "^3.0.3"
> > > },
> > > "devDependencies": {
> > > "@vue/cli-service": "^3.8.0",
> > > "vue-template-compiler": "^2.6.10"
> > > }
> > 
> > 
> > @mbilbao I have the same issue. Did you find a fix?
> 
> Yes, I applied the solution of @daarioautumn just downgrade the ionicons package to 4.5.8

I found this style:
```
html:not(.hydrated) body {
    display: none;
}
```

**Comment by jepiqueau** [comment]
this is solve in using @ionic/vue@0.0.9. so i close the issue

**Comment by woodstream** [comment]
Could publish the latest version (@ionic/vue@0.0.9 ) to npm?  now in npm is v0.0.4.

**Comment by jepiqueau** [comment]
It is published on npm do npm install --save @ionic/vue@next

**Comment by anderfernandes** [comment]
@jepiqueau's solution worked perfectly for me. Thank you!!!

**Comment by Sacrekin** [comment]
It works fine in @ionic/vue@0.0.9 but only with the ions added in vue appInitialize, ie:
        close, reorder, menu, arrow-forward, arrow-back,   arrow-down, search & close-circle.     

When can we hope to have the full access to all icons?

**Comment by Sacrekin** [comment]
Of course one can edit ionic-vue.esm.js but not sure this is the recommended way....

**Comment by jepiqueau** [comment]
the solution for having other icons is to add them in the main.js file ie for icons "star","trash","create" you do this
```
// after import Ionic from "@ionic/vue"; 

import { addIcons } from "ionicons";
import { star, trash, create } from "ionicons/icons";

// after Vue.use(Ionic);
addIcons({
  "ios-star": star.ios,
  "md-star": star.md,
  "ios-trash": trash.ios,
  "md-trash": trash.md,
  "ios-create": create.ios,
  "md-create": create.md
});
``` 

that's it and it works so do it for any icons you want to use even for the one you want to add in a ion-item
hope it's help

**Comment by jepiqueau** [comment]
Have a look at branch ``` ionicone ```  of 
``` https://github.com/jepiqueau/vue-test-stencil-svgpaths-morphing ``` 
 i add a TestIcons button in Home.Vue and a TestIcons.Vue showing the desired icons

**Comment by Sacrekin** [comment]
It works fine. Thanks for the help. Is it a temporary fix or is the way forward to access icons?

**Comment by jepiqueau** [comment]
I do not know the plans of the Ionic team but for me it is logical to import only the icons you need in your app instead of all the icons which will increase the size of your app for no value

**Comment by dalezak** [comment]
@jepiqueau how to import icons with filenames that have dashes, for example `log-out`?

```
import { addIcons } from "ionicons";
import { log-out } from "ionicons/icons";
addIcons({
  "ios-log-out": log-out.ios,
  "md-log-out": log-out.md
});
```

I'm getting a syntax error trying to import any icons with dashes.

**Comment by jepiqueau** [comment]
that's the way

**Comment by shamoons** [comment]
Has this been resolved?

**Comment by hunterloftis** [comment]
For people running into this in the future, the fix is somewhat buried above. Just update your version of @ionic/vue, eg:

```
$ npm install @ionic/vue@0.0.9
```

**Comment by shamoons** [comment]
@hunterloftis - thanks. That did it. I hope it gets officially updated before I go to prod, but it works for now.

**Comment by ReaganRealones** [comment]
Thanks guys, you really made it easy for me
