### ISSUE TITLE
bug: A hardware back button doesn't work if a current page is the only one in the DOM.

### ISSUE THREAD

**Issue by maciejkoch** [ionic-team/ionic#18651]
# Bug Report

**Ionic version:**

[x] **4.4.2**

**Current behavior:**
A hardware back button doesn't work if current page is the only one in the DOM. It doesn't work even when defaultHref is set. Back button in left top corner works as expected

**Expected behavior:**
Clicking a hardware back button should works exactly the same way as a back button in the left top corner when a defaultHref is set. It should be possible to navigate forward just when app starts or page has been refreshed and then navigate back with a hardware back button.

**Steps to reproduce:**
1. Open app on Android device
2. Navigate to any page (home -> any page)
3. Refresh the app (I go to chrome://inspect, open app and click f5)
4. back button in top left corner works but hardware back button doesn’t

or

1. Open app on Android device
2. Navigate to any page just when app starts (just after platform.ready())
3. back button in top left corner works but hardware back button doesn’t

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\UnBackedUp_Data\Applications\nvm\v10.15.3\node_modules\ionic)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 21 other plugins)

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! Are you trying this in a Cordova/Capacitor application, or in a web browser?

**Comment by maciejkoch** [comment]
Hi. I'm trying it only in the cordova app.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I believe this is expected behavior. If you were to open a new tab in Chrome (assume you can bypass the start page), the browser's back button would not be active since there is nothing to "navigate back to".

The same goes for a Cordova application. When starting an application, there is nothing in the navigation history stack, so there is nothing to navigate back to. The `defaultHref` property on `ion-back-button` does not alter your navigation stack.

Does this resolve your issue?

**Comment by liamdebeasi** [comment]
Also, I understand that some users expect the app to exit when using the hardware back button when there is nothing to navigate back to. Are you referring to this instead?

**Comment by maciejkoch** [comment]
Hi,

Sorry for the delay. I was on the holidays.

I don't believe that it is expected behavior. In my case, one of the details page is being opened when user clicks on the push notification. Then user is not able to go back (details -> list -> home page) using hardware back button. It is interesting because back button in the top left corner works as expected (it is navigating back to the list). From technical point of view, I'm listening for click a push notification event just after platform.ready. 

``` js
this.platform.ready().then(() => {
   this.appCenterPush.addEventListener('notificationReceived').subscribe(() => {
       this.router.navigate(['detailsPage']);
   });
});
```

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you provide a repo with the code required to reproduce this issue?

What I am seeing is that when either refreshing the application or when navigating right after `platform.ready` the `ion-back-button` does not appear. The hardware back button does let me go back, but that is because the browser/webview's internal state still has data from my previous session (before I refreshed).

**Comment by maciejkoch** [comment]
Here is a repo with the code required to reproduce the issue: https://github.com/maciejkoch/ionic4-hardware-back-button-issue

Please run this code on the android using cordova.

At the beginning I'm simulating click on the push notification which open custom page:

``` js

this.platform.ready().then(() => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();

      // I'm simulating user clicks on the push notification and then custom page is being opened
      this.router.navigate(['details']);
    });

```

**Comment by liamdebeasi** [comment]
Thanks for the repo! I am getting a few errors on compilation. Can you resolve the errors in your test repo?

**Comment by maciejkoch** [comment]
I didn't push all files.. sorry my bad.

You can check it now.

**Comment by maciejkoch** [comment]
Any update?

**Comment by alexbonhomme** [comment]
Hey!

I'm facing the same issue. Did you have any update ?

Thx

**Comment by liamdebeasi** [comment]
Hi everyone,

There have been numerous back button updates since this issue was created. Does this issue still occur with the latest version of Ionic Framework?
