### ISSUE TITLE
feat: iOS 13 Card-style Modal Presentation

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic#18660]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Add the iOS 13 Modal UI and gesture. It should go over the content, shrinking the content behind it, and optionally be swiped down to close. 

**Describe Preferred Solution**

![1_MCSE7hgvyyyHbm3IZ0pVtg](https://user-images.githubusercontent.com/6577830/60365581-18769400-99b7-11e9-804a-1ba6a4e273ee.png)

**Comment by iconio** [comment]
I can't wait for that!! 👏

**Comment by brtwister2** [comment]
Is this feature already available?

**Comment by liamdebeasi** [comment]
Not yet. It will be available in an upcoming release of Ionic Framework.

**Comment by brtwister2** [comment]
> Not yet. It will be available in an upcoming release of Ionic Framework.

Can't wait for it :D !!!!

**Comment by ludufre** [comment]
@brandyscarney  I was able to test on Ionic 5 Beta and it is working perfectly. Will this be released only on Ionic 5 or will we still have version 4? Thanks

**Comment by liamdebeasi** [comment]
This will be released as part of Ionic 5 only.
