### ISSUE TITLE
feat: updated iOS Page Transition box-shadow

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic#18661]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

The iOS page transition includes a box-shadow that fades in-out/out-in while animating between pages. We need to add it in, perhaps using a data uri (?)

**Describe Preferred Solution**

<img width="269" alt="Screen Shot 2019-06-28 at 3 20 28 PM" src="https://user-images.githubusercontent.com/6577830/60366034-4ad4c100-99b8-11e9-9f07-2408ddc40e54.png">

**Comment by adamdbradley** [comment]
https://github.com/ionic-team/ionic/pull/18695
