### ISSUE TITLE
bug: Disabled fab-buttons no longer have an opacity set

### ISSUE THREAD

**Issue by date80** [ionic-team/ionic#18682]
# Bug Report

**Ionic version:**
[x] 4.6.0

**Current behavior:**
If the _disabled_ attribute is set on a _ion-fab-button_, the opacity of the fab-button is no longer set to _0.5_.

**Expected behavior:**
As in _v.4.5.0_ the button should be displayed with an opacity of _0.5_

**Other information:**
Seems like the problem is related to a wrong style definition in _fab-button.[ios|md].css_:
`
:host(.fab-button-disabled) {
  --opacity: .5;
  pointer-events: none;
}
`

I guess this should be something like:
`
:host(.fab-button-disabled) {
 opacity: .5;
  pointer-events: none;
}
`

or

`
:host(.fab-button-disabled) {
  opacity: var(--opacity);
  pointer-events: none;
}
`

**Comment by liamdebeasi** [comment]
Thanks for the issue! I was able to reproduce this: https://codepen.io/liamdebeasi/pen/zVWBjY

We will look into this! cc @brandyscarney

**Comment by brandyscarney** [comment]
Fixed by #18685 will be in our `4.6.1` hotfix release, please follow for updates on this issue: #18655
