### ISSUE TITLE
feat: ability to remove ion-icons

### ISSUE THREAD

**Issue by thinkdj** [ionic-team/ionic#18680]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Sometimes we do not use ion-icons at all in the projects. 

The framework options should be dynamic enough to remove ion-icons package from the build completely. 

**Describe Preferred Solution**

Solution: Separate out ion-icons as a package requirement. 

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by RafaelKr** [comment]
If you're using Angular, you should be able to follow the following steps to remove them from your bundle:
1. Open the angular.json file in the root of your project directory
2. Search for the object containing the key-value pair `"input": "node_modules/ionicons/dist/ionicons/svg"` (`projects.app.architect.build.options.assets`)
3. Remove that object from the assets array

**Comment by thinkdj** [comment]
I'm on Ionic 4 and I have not seen any reference to ion-icons in either package.json or angular.json

**Comment by RafaelKr** [comment]
I just created a new project to check if it's there:

![image](https://user-images.githubusercontent.com/14234815/60424494-bef9a980-9bf0-11e9-91ce-ec2300057b4b.png)

**Comment by thinkdj** [comment]
@RafaelKr Thanks for that! I upgraded from Ionic beta version. Maybe because of that. My files (apart from package-lock.json) has no reference to ionicons

**Comment by RafaelKr** [comment]
Ah, good to know. From which beta version did you upgrade? Did you always follow the "Breaking Changes" in the release notes? Especially for the 4.0.0-rc.1?

If not, the icons shouldn't be included anyway.
Build the project and see if you have a `www/svg/` folder including the icons. If not you can close the issue.

**Comment by manucorporat** [comment]
Components are lazy loaded, what are you trying to achieve by removing ionicons?

**Comment by thinkdj** [comment]
@manucorporat I personally do not prefer adding 100s of svg files into the final bundle when it is not going to be used at all. Also, in my case, there is no configuration of "assets" via angular.json and all the SVG files comes into the build's root

**Comment by thinkdj** [comment]
@RafaelKr I created a fresh app using latest ionic cli and whatever you have mentioned above works. I guess these changes did not reflect for me as I started off from Ionic Beta. 
Closing as there exists away to remove ionicons from the bundle.
