### ISSUE TITLE
bug: ion-tabs selected state not working

### ISSUE THREAD

**Issue by tanoabeleyra** [ionic-team/ionic#18689]
# Bug Report

**Ionic version:**
[x] **4.6**

**Current behavior:**
When opening a page that is linked to a tab it isn't being selected.

**Expected behavior:**
When opening a page linked to a tab it should be selected (by default blue).

**Steps to reproduce:**
Start a new project: `ionic start myApp tabs`. Open `tab1.page.html` and remove the `href`'s of the `ion-item`'s. Open `http://localhost:4200/tabs/tab1` (change the port accordingly) and the tab isn't selected (it was working before this change).

Another scenario, open `tab2.page.html` and add some component inside the `<ion-content>`, for example a `<ion-spinner>`. Open `http://localhost:4200/tabs/tab2` and the tab isn't selected (it was working before this change).

**Other information:**
The two scenarios are really different, so I don't really know the cause of this bug.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.0 (/home/tanoabeleyra/.config/yarn/global/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v11.14.0 (/home/tanoabeleyra/.nvm/versions/node/v11.14.0/bin/node)
   npm    : 6.7.0
   OS     : Linux 4.19

Done in 0.90s.
```

![localhost_8100_tabs_tab1(Galaxy S5)](https://user-images.githubusercontent.com/6851095/60451560-b14d1f80-9c02-11e9-885d-b3ec08a536b5.png)

**Comment by brandyscarney** [comment]
Thanks for the issue! Fixed by https://github.com/ionic-team/ionic/pull/18700. This will be in the `4.6.1` release.
