### ISSUE TITLE
Testing Improvements

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic#18686]
## **_WIP_**

This document is intended to track tests we need to add to various components in Ionic. 

#### Action Sheet
- [ ] Ensure all events are being emitted correctly ('ionActionSheetWillDismiss', etc)

#### Alert
- [ ] Ensure all events are being emitted correctly ('ionAlertWillDismiss', etc)

#### Button
- [ ] Ensure all events are being emitted correctly ('ionFocus', etc)
- [ ] Ensure disabled buttons are not clickable/cannot receive tab focus

#### Checkbox
- [ ] Ensure all events are being emitted correctly ('ionChange', etc) 

#### Content
- [ ] Ensure all events are being emitted correctly ('ionScroll', etc) 

#### Searchbar
- [ ] Ensure all events are being emitted correctly (`ionInput`, `ionChange`, etc) 

#### DateTime
- [ ] Changing selected values refreshes available values when `max` and `min` are set (be sure to specifically check this case when switching AM/PM)
- [ ] Ensure all events are being emitted correctly ('ionCancel', 'ionFocus', etc)

#### Infinite Scroll
- [ ] Check that `ionInfinite` is fired when enabled
- [ ] Check that `ionInfinite` is not fired when disabled
- [ ] Check that `ionInfinite` is fired when setting both % and px thresholds

#### Button
- [ ] Add default, activated, focused, activated-focused states for buttons styled using CSS variables (not `color="dark"`). This should be done for clear, outlined, and filled buttons
- [ ] Add default, activated, focused, activated-focused states for buttons in a toolbar. Include default buttons and buttons styled using `color=` and CSS variables

#### Chip
- [ ] Add chips styled with CSS Variables

#### FAB
- [ ] Add default, activated, focused, activated-focused states for FAB buttons styled using CSS variables (not `color="dark"`). Be sure to include translucent tests

**Comment by brandyscarney** [comment]
I think we should add a desktop sized screenshot test that switches through the themes for the css-variables theming test at `ionic/core/src/themes/test/css-variables/index.html`
