### ISSUE TITLE
ionic start myApp --type=react

### ISSUE THREAD

**Issue by psw0714** [ionic-team/ionic#18697]
Why do I use ionic start myApp --type=react to create a project that prompts after ionic serve
![image](https://user-images.githubusercontent.com/26177875/60496590-b636cf80-9ce5-11e9-8585-cfb1e576853b.png)

**Comment by elylucas** [comment]
Hi @psw0714,

I think this might of been caused by an errant dev build that got out. Could you update to 0.0.6 and see if that fixes the issue?

Thanks

**Comment by psw0714** [comment]
@elylucas Thank you, the problem has been solved.
