### ISSUE TITLE
bug: Overscroll on all pages from ios

### ISSUE THREAD

**Issue by carlosnewmusic** [ionic-team/ionic#18706]
[x] **4.5~4.6**

**Current behavior:**
Scrolling on pages where the content does not leave the page
![overscroll tanto en menu como en historial](https://user-images.githubusercontent.com/19379457/60586385-46325300-9d92-11e9-8db6-0a5edc0ba450.jpg)
![overscroll](https://user-images.githubusercontent.com/19379457/60586386-46cae980-9d92-11e9-9291-254c7b6c8062.jpg)

**Expected behavior:**
the vertical scroll bar should not appear if the page content fits in the viewport

**Steps to reproduce:**
move from top to bottom on a page where the content does not exceed the space on the page

**Related code:**
https://stackblitz.com/edit/ionic-jbzes5?file=src%2Fapp%2Fpages%2Ffichaje%2Ffichaje.page.html

**Other information:**

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.1.0 (C:\Users\Administrador\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 5 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.5

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! This behavior is intentional. It exists so users get the "rubber band" effect when running the app on an iOS device.

This behavior can be disabled. Please see the [ion-content Documentation](https://ionicframework.com/docs/api/content#properties) for more information.

I am going to close this as this is not an Ionic bug. Thanks!
