### ISSUE TITLE
[4.6] No longer possible to bind value to ion-icon's name attribute

### ISSUE THREAD

**Issue by biesbjerg** [ionic-team/ionic#18707]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

In 4.5 I could change the `ion-icon` based on a property set in the component. It is no longer working in 4.6 (4.6.1-dev.201907022006.a656dad)

```
<ion-button (click)="isPlaying ? onPause() : onPlay()" fill="clear" class="base-btn solid-btn">
	<ion-icon slot="icon-only" [name]="isPlaying ? 'pause' : 'play'"></ion-icon>
</ion-button>
```

![image](https://user-images.githubusercontent.com/230182/60591203-40db0580-9d9e-11e9-8ff7-df88c13798b7.png)

**Expected behavior:**

![image](https://user-images.githubusercontent.com/230182/60591249-57815c80-9d9e-11e9-9430-40a8bafe1cab.png)

**Steps to reproduce:**

This minimal code example doesn't show an icon:
```
<ion-icon [name]="'pause'"></ion-icon>
```
Source looks like it's missing the `svg` element.
![image](https://user-images.githubusercontent.com/230182/60592432-e98a6480-9da0-11e9-8c04-b20b0d518116.png)

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.1 (/Users/kim/.npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.1-dev.201907022006.a656dad
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 8 other plugins)

Utility:

   cordova-res : 0.5.1
   native-run  : 0.2.7

System:

   Android SDK Tools : 26.1.1 (/Users/kim/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v10.15.0 (/usr/local/bin/node)
   npm               : 6.9.2
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! Are you able to provide a code reproduction? I am using the code snippets you provided with `@ionic/angular@4.6.0` and it seems to be working fine.

**Comment by biesbjerg** [comment]
It's working in 4.6.0 but not in 4.6.1-dev, and I was missing a `Modal` to trigger the behavior.

You can check out the code here: https://github.com/biesbjerg/ion-icon-bug

**Comment by liamdebeasi** [comment]
Can you test this using Ionic 4.6.1 and see if this issue is resolved? Thanks!

**Comment by biesbjerg** [comment]
I can confirm this is fixed. Thanks! :)
