### ISSUE TITLE
bug: ion-radio checked="true" ERROR

### ISSUE THREAD

**Issue by gminhaneli** [ionic-team/ionic#18719]
# Bug Report

**Ionic version:**
[x] **5.2.1**

**Current behavior:**
```
<ion-list>
   <ion-radio-group> 
     <ion-item>
       <ion-label> teste</label>
         <ion-radio checked="true"></ion-radio>
     </ion-item> 
   </ion-radio-group> 
  </ion-list>    
```    

**Expected behavior:**
it was to be expected that the default value with checked = true was checked

**Comment by rdlabo** [comment]
@gminhaneli This is worked at my environment.
Maybe this is typo?

> <ion-label> teste</label>
`<ion-label> teste</ion-label>`

**Comment by liamdebeasi** [comment]
Hi there,

The code snippet you provided is working fine for me. Which version of Ionic are you seeing this on?

**Comment by gminhaneli** [comment]
consegui resolver. obrigado
