### ISSUE TITLE
feat: Common node module for multiple ionic app with same type project struture.

### ISSUE THREAD

**Issue by krunal9421** [ionic-team/ionic#18722]
I want know is it possible that can we have common node module for multiple ionic apps with same package.json.
Is it possible then what are the precaution I have to take for it's full functional working.
I am having push notification plugin as common in every project.
I am running out of space on my development server.

Please help me out

**Comment by liamdebeasi** [comment]
Thanks for the issue! I am going to close this as this is more of a support question.

Feel free to post your question on our [forum](forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com/).

Thanks!

**Comment by krunal9421** [comment]
@liamdebeasi  
Thanks for the reply. I have already added this on ionic form but no one replied on that.
So, I have posted is here. Below is the link for it.

https://forum.ionicframework.com/t/common-node-module-folder-for-multiple-ionic-projects/166726

**Comment by liamdebeasi** [comment]
Hi there,

Unfortunately we do not provide support on GitHub. Additionally, the scenario you described is typically just how node/npm functions. There is probably something you could do with symlinks to save space, but that would be something the user would need to implement, not Ionic.

**Comment by krunal9421** [comment]
@liamdebeasi 
Thanx for your update.
