### ISSUE TITLE
Uncaught SyntaxError: Unexpected token async

### ISSUE THREAD

**Issue by gaurangkela** [ionic-team/ionic#18725]
**Ionic version:**
[x] **4.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**
while normal running ionic cordova run android works fine, but while building --prod it builds successfully but throws error at run time "Uncaught SyntaxError: Unexpected token async" only blank white screen nothing else.

**Expected behavior:**
it should be installed and work as normal build.

**Steps to reproduce:**
ionic cordova run android --prod

**Other information:**
                                                                                 
Date: 2019-07-08T07:53:41.949Z
Hash: 95aa4d4442d94004b757
Time: 22764ms
chunk {0} common.5b9a25e6d9e3c35424a4.js (common) 14.6 kB  [rendered]
chunk {1} runtime.30fb27e937f9b89cede8.js (runtime) 4.69 kB [entry] [rendered]
chunk {2} 2.f2de434cd2626a8c1294.js () 12.1 kB  [rendered]
chunk {3} 3.85888092de05811927de.js () 835 bytes  [rendered]
chunk {4} 4.bf825ed88a49a2d93172.js () 841 bytes  [rendered]
chunk {5} 5.b2028430c5c419ac6cf1.js () 3.77 kB  [rendered]
chunk {6} 6.81533da8a30553c76baf.js () 463 bytes  [rendered]
chunk {7} 7.daec3d6556e5ff00d4af.js () 615 bytes  [rendered]
chunk {8} 8.1c8d9e952b1a5ee2a30c.js () 89.5 kB  [rendered]
chunk {9} 9.6f0de4347ba19011a150.js () 2 kB  [rendered]
chunk {10} es2015-polyfills.e625d4638d49dde159c0.js (es2015-polyfills) 56.4 kB [initial] [rendered]
chunk {11} main.49cfa9bbdcb488a0ecef.js (main) 660 kB [initial] [rendered]
chunk {12} polyfills.e69dd9ba31c163038613.js (polyfills) 41.1 kB [initial] [rendered]
chunk {13} styles.183bf6a323f745eed1fd.css (styles) 25.8 kB [initial] [rendered]
chunk {14} 14.72829f09cf53322a1b67.js () 4.44 kB  [rendered]
chunk {15} 15.2b1dd257c7553312afa8.js () 14.3 kB  [rendered]
chunk {16} 16.1b05b4add6ee2f26c3d1.js () 35.1 kB  [rendered]
chunk {17} 17.3cdd0f97615c93abae89.js () 8.59 kB  [rendered]
chunk {18} 18.ea73ce186013f5ecd0cb.js () 35 kB  [rendered]
chunk {19} 19.5843303b0ec979298e7e.js () 3.07 kB  [rendered]
chunk {20} 20.f728fd57f08dc2488709.js () 7.59 kB  [rendered]
chunk {21} 21.1e21975bb53647f61fd7.js () 17.3 kB  [rendered]
chunk {22} 22.f80e626fccf9b3d3b6a4.js () 2.99 kB  [rendered]
chunk {23} 23.46b7faf273037298bd41.js () 12.4 kB  [rendered]
chunk {24} 24.1b5b4d1b4872ed2ec428.js () 9.47 kB  [rendered]
chunk {25} 25.6d3a2f3edd53ca88bba6.js () 19.2 kB  [rendered]
chunk {26} 26.a5eb79dac9e13a8363dd.js () 19.3 kB  [rendered]
chunk {27} 27.37afd203872c81c508e3.js () 17.1 kB  [rendered]
chunk {28} 28.2fbc1194e8890c4b771b.js () 20.7 kB  [rendered]
chunk {29} 29.c3aaf40d47f4e0865360.js () 20.9 kB  [rendered]
chunk {30} 30.5d9e3d3183762a7bf4d9.js () 3.03 kB  [rendered]
chunk {31} 31.dbb04f250268758a5f1e.js () 3.09 kB  [rendered]
chunk {32} 32.8a6c91940e7403a1c7e2.js () 7.45 kB  [rendered]
chunk {33} 33.1e6f97798390aa600d52.js () 8 kB  [rendered]
chunk {34} 34.ac7ba62d2dd134ac6309.js () 1.58 kB  [rendered]
chunk {35} 35.59819c173261d6e6e574.js () 1.58 kB  [rendered]
chunk {36} 36.165c94d45cc263ed9f1d.js () 14.5 kB  [rendered]
chunk {37} 37.7c7de8384fca454facb0.js () 14.7 kB  [rendered]
chunk {38} 38.f16a7366ba6ff60b4e04.js () 8.17 kB  [rendered]
chunk {39} 39.4b0b9301b5043c275e2f.js () 7.79 kB  [rendered]
chunk {40} 40.438924f4287341b87630.js () 4.95 kB  [rendered]
chunk {41} 41.78497d7f52ffcf948ec6.js () 5.01 kB  [rendered]
chunk {42} 42.78eed4e17342fd6289f1.js () 4.15 kB  [rendered]
chunk {43} 43.ab96107ddd97c6a99fcc.js () 4.15 kB  [rendered]
chunk {44} 44.5f590e073683c29a548b.js () 11.8 kB  [rendered]
chunk {45} 45.66530303e489800b95ce.js () 31.2 kB  [rendered]
chunk {46} 46.77b322cbe5c58140a475.js () 30.9 kB  [rendered]
chunk {47} 47.cc0d10af6fb649ad3065.js () 14.4 kB  [rendered]
chunk {48} 48.85073e5d7a863ad4f293.js () 13.5 kB  [rendered]
chunk {49} 49.3c1af8da11cc90ab3599.js () 1.85 kB  [rendered]
chunk {50} 50.8fb124ce3c089ea8bd12.js () 5.09 kB  [rendered]
chunk {51} 51.faf7ed056f3c244d8e55.js () 5.08 kB  [rendered]
chunk {52} 52.a655f450d43ec5604923.js () 9.03 kB  [rendered]
chunk {53} 53.0be5b3c404aebbed46c5.js () 8.92 kB  [rendered]
chunk {54} 54.10001731a970943b835b.js () 15.5 kB  [rendered]
chunk {55} 55.305abf81f2f95c804991.js () 15.4 kB  [rendered]
chunk {56} 56.6007e4558747245d433d.js () 30.7 kB  [rendered]
chunk {57} 57.1331fae4ab084374f425.js () 34.3 kB  [rendered]
chunk {58} 58.2601587f7618b8ccba95.js () 5.86 kB  [rendered]
chunk {59} 59.3d334a4968ba4f83e815.js () 5.65 kB  [rendered]
chunk {60} 60.9ea6c8c0f906521dccf9.js () 21.1 kB  [rendered]
chunk {61} 61.0c364d3bcdac9d211fd3.js () 21.2 kB  [rendered]
chunk {62} 62.517016e05ed807429eba.js () 5.74 kB  [rendered]
chunk {63} 63.5b449ac8cae9c42ff86d.js () 5.78 kB  [rendered]
chunk {64} 64.54147633e6e468b62045.js () 13.2 kB  [rendered]
chunk {65} 65.3653a47b0e9a7fac4d42.js () 8.07 kB  [rendered]
chunk {66} 66.14f247462ef7fe837898.js () 7.5 kB  [rendered]
chunk {67} 67.d460e42e5ac4a17bc71b.js () 9.63 kB  [rendered]
chunk {68} 68.478e28f99195af11d513.js () 9.63 kB  [rendered]
chunk {69} 69.0915440e44ee878b739c.js () 6.51 kB  [rendered]
chunk {70} 70.83be5365bdabe70fbb31.js () 6.74 kB  [rendered]
chunk {71} 71.167c9a2b466c1ce11441.js () 12.2 kB  [rendered]
chunk {72} 72.c9e97bb2ee7221beb438.js () 13.6 kB  [rendered]
chunk {73} 73.637c31ae98ab6e1f4ed5.js () 7.74 kB  [rendered]
chunk {74} 74.f3bffbee074a57a51e93.js () 7.73 kB  [rendered]
chunk {75} 75.554a2d7bcdbbbe13a11a.js () 6.08 kB  [rendered]
chunk {76} 76.2ae8b0aaf15710726900.js () 6.08 kB  [rendered]
chunk {77} 77.66a12cae717b4a2ee29d.js () 3.46 kB  [rendered]
chunk {78} 78.c3f875986b8a12274507.js () 15.8 kB  [rendered]
chunk {79} 79.24bbc6681c8c677f2b3f.js () 13.5 kB  [rendered]
chunk {80} 80.145bd9e5ca7ebdcb9c81.js () 12.4 kB  [rendered]
chunk {81} 81.f424b4aa476b554d2dd5.js () 12 kB  [rendered]
chunk {82} 82.fd1572c36d135967a183.js () 11.9 kB  [rendered]
chunk {83} 83.877c021654ce29766e7e.js () 11.9 kB  [rendered]
chunk {84} 84.732cfa2f793bda990770.js () 29.7 kB  [rendered]
chunk {85} 85.a838c49d471bd95284ef.js () 29.7 kB  [rendered]
chunk {86} 86.b789e6073aa4f24a83a1.js () 4.97 kB  [rendered]
chunk {87} 87.da8322aefcabf39b6b5a.js () 3.4 kB  [rendered]
chunk {88} 88.3c3887083f16a1152da7.js () 3.4 kB  [rendered]
chunk {89} 89.2990c8fc27b329f06b08.js () 11.2 kB  [rendered]
chunk {90} 90.a22e1a0ef2fa88113629.js () 11.4 kB  [rendered]
chunk {91} 91.905ec7a3f1dc5db20b05.js () 5.4 kB  [rendered]
chunk {92} 92.0f5d3f037fe5b728904e.js () 677 bytes  [rendered]
chunk {93} 93.c1cb4a8b0e54142bb5ca.js () 7.41 kB  [rendered]
chunk {94} 94.ef730bda7c626799c11d.js () 7.44 kB  [rendered]
chunk {95} 95.bda19a4158cba1259536.js () 9.5 kB  [rendered]
chunk {96} 96.084b45db3f141c0a43c4.js () 10.2 kB  [rendered]
chunk {97} 97.2f619490488b3b1d2e6d.js () 7.63 kB  [rendered]
chunk {98} 98.facdcaef0e9f7c2d4b17.js () 7.03 kB  [rendered]
chunk {99} 99.fe5f892a3bcdd8b87c83.js () 8.48 kB  [rendered]
chunk {100} 100.6dfb4385e09eaf1bcf05.js () 3.13 kB  [rendered]
chunk {101} 101.4e967d8b7ac6a806eaf0.js () 920 bytes  [rendered]
chunk {102} 102.23c3c085d646a2f30e6e.js () 6.02 kB  [rendered]
chunk {103} 103.8313caade591690731ee.js () 134 kB  [rendered]
chunk {104} 104.a426eda64eca46c8c69e.js () 7.59 kB  [rendered]
chunk {105} 105.c5ee06afe9fe02fb3357.js () 17.3 kB  [rendered]
chunk {cordova} cordova.b04376d424a21d95d017.js (cordova) 20.9 kB [entry] [rendered]
> cordova run android
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=/software/Android/Sdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app
> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:checkDebugManifest UP-TO-DATE
> Task :CordovaLib:processDebugManifest UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :CordovaLib:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript UP-TO-DATE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources UP-TO-DATE
> Task :CordovaLib:compileDebugRenderscript UP-TO-DATE
> Task :CordovaLib:generateDebugBuildConfig UP-TO-DATE
> Task :CordovaLib:generateDebugResValues UP-TO-DATE
> Task :CordovaLib:generateDebugResources UP-TO-DATE
> Task :CordovaLib:packageDebugResources UP-TO-DATE
> Task :CordovaLib:generateDebugRFile UP-TO-DATE
> Task :CordovaLib:prepareLintJar UP-TO-DATE
> Task :CordovaLib:generateDebugSources UP-TO-DATE
> Task :CordovaLib:javaPreCompileDebug UP-TO-DATE
> Task :CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
> Task :CordovaLib:processDebugJavaRes NO-SOURCE
> Task :CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:compileDebugNdk NO-SOURCE
> Task :app:compileDebugSources UP-TO-DATE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders UP-TO-DATE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :CordovaLib:mergeDebugShaders UP-TO-DATE
> Task :CordovaLib:compileDebugShaders UP-TO-DATE
> Task :CordovaLib:generateDebugAssets UP-TO-DATE
> Task :CordovaLib:packageDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:signingConfigWriterDebug UP-TO-DATE
> Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE
> Task :app:transformDexArchiveWithDexMergerForDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :CordovaLib:compileDebugNdk NO-SOURCE
> Task :CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
> Task :CordovaLib:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
> Task :CordovaLib:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
> Task :app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
> Task :app:packageDebug UP-TO-DATE
> Task :app:assembleDebug UP-TO-DATE
> Task :app:cdvBuildDebug UP-TO-DATE

BUILD SUCCESSFUL in 2s
42 actionable tasks: 42 up-to-date
Built the following apk(s): 
        /local_dir/ionic/productivity/simpleLists/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=/software/Android/Sdk (DEPRECATED)
No target specified, deploying to device '4b80eef07ce5'.
Using apk: /local_dir/ionic/productivity/simpleLists/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Package name: ***.***.****
LAUNCH SUCCESS

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/home/gaurangkela/.nvm/versions/node/v10.15.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 11 other plugins)

System:

   Android SDK Tools : 26.1.1 (/software/Android/Sdk)
   NodeJS            : v10.15.3 (/home/gaurangkela/.nvm/versions/node/v10.15.3/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.15
```

**Comment by liamdebeasi** [comment]
Hi there,

Which device/version of Android are you testing this on?

**Comment by gaurangkela** [comment]
i'm using redmi 5A and os version is 8.1.0

**Comment by liamdebeasi** [comment]
Can you provide a repo with the code required to reproduce this issue? Thanks!

**Comment by gaurangkela** [comment]
https://github.com/gaurangkela/testProdApp
i have find out some problem with xmppMsgProvider in home.ts, if i remove the provider then i'm able to build prod, but if i use that provider in home.ts it throws error 

> Uncaught SyntaxError: Unexpected token async

**Comment by liamdebeasi** [comment]
The repo you sent looks to be a blank Ionic starter. Did you publish your code changes?

**Comment by gaurangkela** [comment]
yes code is in homepage module as you can see in image you just have to download it and install node_modules using npm install
![Screenshot from 2019-07-12 09-12-08](https://user-images.githubusercontent.com/33948328/61100856-44008080-a485-11e9-8c9a-77d9512a8c96.png)

**Comment by gaurangkela** [comment]
ok updated now you can check https://github.com/gaurangkela/testProdApp

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I was able to reproduce this issue in a standalone Angular application without Ionic. Additionally, I got a `global is not defined` error from the `@xmpp/client` library when running the application in development mode.

I am going to close this as this is not an Ionic issue. I would recommend contacting the author of `@xmpp/client` for further support/to file a bug.
