### ISSUE TITLE
bug: Unable to type in input/ion-input fields on iOS and Safari

### ISSUE THREAD

**Issue by maddada** [ionic-team/ionic#18729]
### Bug Report
Ionic version:

[x] 4.6.0

**Current behavior:**

I can't type in ion-input AND input fields in Safari and on iOS simulator (tried both virtual and hardware keyboard), however when I type in Chrome or Firefox (mobile/desktop) text is showing up perfectly.

**Expected behavior:**

Text should show up normally when typing in input fields.

**Steps to reproduce:**

This is a very simple page with 1 input field, it can be tested on iOS and Safari and then on Chrome.
Inputting text works on chrome but won't work on Safari and iOS (even on chrome in iOS)

https://memar.ae/forgot-password

**Related code:**
https://github.com/maddada/engappm7/tree/master/src/app/pages/login/forgot-password

**Other information:**

I've tried uninstalling/reinstalling cordova-plugin-ionic-keyboard, tried removing and readding iOS, tried uninstalling/reinstalling the cordova webview plugin, all to no avail.

The issue is with 4.0.0-rc.2 and above. If I downgrade to @ionic/angular@4.0.0-rc.1 then the inputs work perfectly on both iOS and Safari.

Please advise me on what I can do to fix this issue.

**Ionic info:**

Ionic:

   ionic (Ionic CLI)             : 5.2.1 (C:\Users\madda\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.2, (and 7 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\madda\AppData\Local\Android\Sdk)   NodeJS            : v10.10.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you experiencing this issue in a standalone application (Cordova or Capacitor) or are you experiencing this issue in mobile Safari (web browser)?
