### ISSUE TITLE
bug: ion-item with (click) attribute should also a clickable item

### ISSUE THREAD

**Issue by Jannnnnn** [ionic-team/ionic#18723]
# Bug Report

**Ionic version:**
[x] **4.6**

**Current behavior:**
`ion-item` with `(click)` attribute doesn't have pointer cursor and no hover/focus style

**Expected behavior:**
`ion-item` with `(click)` attribute have `ion-activatable ion-focusable` class

**Steps to reproduce:**
- Create a `sidemenu` starter from cli `ionic start myApp sidemenu` 
- Append the related code to `app.component.html:19`
- run `ionic serve` 
- open the menu
- hover over the list items in the side menu

**Related code:**

```html
<ion-item  (click)="someMethode()">
    <ion-label>Hello World</ion-label>
</ion-item>
```

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.801.0
   @angular-devkit/schematics    : 8.1.0
   @angular/cli                  : 8.1.0
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   capacitor (Capacitor CLI) : 1.1.0
   @capacitor/core           : 1.1.0

System:

   NodeJS : v11.12.0 (/usr/local/bin/node)
   npm    : 6.10.0
   OS     : macOS Mojave
```

**Comment by manucorporat** [comment]
You should add the "button" attribute:
```
<ion-item button (click)="">
```

it's not possible to reliably know if there are click listeners attached or not
