### ISSUE TITLE
bug: IOS Network Error axios request

### ISSUE THREAD

**Issue by medicmilos** [ionic-team/ionic#18738]
# Bug Report

**Ionic version:**

[x] **5.1**

**Current behavior:**

Currently any axios request doesn't work, even simplest ones. The strange part is that it works fine on android devices, and the error only occurs on ios devices.
Tested on ios devices (with error output):
- iPhone 5s ios 11.1.1.
- iPhone 7 ios 12.1.
- iPhone Xr ios 12.3.1.

Tested on android devices (successfully):

- Xiaomi Redmi Note 7 android 9
- Samsung Galaxy S7 android 8

In 'Related code' section is related error output when I run `ionic serve --devapp`. Even after build with Xcode it doesn't work on ios devices.

**Expected behavior:**

I'm expecting axios request to work, or even give me some more details about error, because I couldn't find any valuable solution on the web.

**Steps to reproduce:**

**Create simple blank app** with the command `ionic start <name> <template> [options]`, add axios and in provided example (home.page.ts) on `ngOnInit()` run simple axios post request.

**Related code:**

- Axios Request:

```
 axios.post('https://path-to-my-api/api/login',{username:"test",password:"test123"})
    .then(response => {
        console.log(response);
    })
    .catch(err => {
        console.log(err.response);
    })
```
- Output error:

```
"message": "Network Error",
"name": "Error",
"stack":
    "createError@http://192.168.1.33:8100/vendor.js:82560:24" +
    "handleError@http://192.168.1.33:8100/vendor.js:82095:25" +
    "wrapFn@http://192.168.1.33:8100/polyfills.js:3694:44" +
    "onInvokeTask@http://192.168.1.33:8100/vendor.js:51333:43" +
    "runTask@http://192.168.1.33:8100/polyfills.js:2557:57" +
    "invokeTask@http://192.168.1.33:8100/polyfills.js:2860:41" +
    "invokeTask@http://192.168.1.33:8100/polyfills.js:4106:20" +
    "globalZoneAwareCallback@http://192.168.1.33:8100/polyfills.js:4132:27",
"config": {
    "url": "https://path-to-my-api/api/login",
    "method": "post",
    "data": "{\"username\":\"test\",\"password\":\"test123\"}",
    "headers": {
        "Accept": "application/json",
        "Authorization": {},
        "Content-Type": "application/json"
    },
    "baseURL": "https://path-to-my-api/api",
    "transformRequest": [null],
    "transformResponse": [null],
    "timeout": 0,
    "withCredentials": false,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1
}
```
**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.1.0 (/home/milos/.nvm/versions/node/v11.13.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 6 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.7 

System:

   Android SDK Tools : 26.1.1 (/home/milos/Android/Sdk)
   NodeJS            : v11.13.0 (/home/milos/.nvm/versions/node/v11.13.0/bin/node)
   npm               : 6.7.0
   OS                : Linux 4.18

```
**Server info:**
Ngnx server information where api is located:
```
nginx version: nginx/1.14.0 (Ubuntu)
built with OpenSSL 1.1.0g  2 Nov 2017
TLS SNI support enabled
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is more of a support request.

For further help with your issue, feel free to post on our [forum](https://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com).

Additionally I would recommend looking at the documentation for the WebView plugin regarding the difference in behavior between iOS and Android: https://github.com/ionic-team/cordova-plugin-ionic-webview.

Thanks!

**Comment by medicmilos** [comment]
**Thanks for the quick replay and the recommendation.** I have resolved the issue by using "Cordova Advanced HTTP" instead of axios. It is basically workaround because I'm short with the time.
