### ISSUE TITLE
bug: cannot inspect ionic 4 app in Chrome running on iOS 12.3.1 device

### ISSUE THREAD

**Issue by ruslan-bikkinin** [ionic-team/ionic#18733]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Unable to inspect ionic 4 app on iOS 12.3.1 device via Chrome - I see only empty DevTools screen.

**Expected behavior:**

Able to inspect ionic 4 app on iOS 12.3.1 device via Chrome - I see webview content, source code etc in DevTools window.

**Steps to reproduce:**
* Create basic ionic angular app
* Run it on a device
* Try to inspect it via Chrome (open `chrome://inspect/#devices`)

![image](https://user-images.githubusercontent.com/30265843/60827962-03b9ad80-a1ba-11e9-82ee-7216f44d2f83.png)

**Related code:**

Demo application:
https://github.com/ruslan-bikkinin/ionic4demoapp

**Other information:**

Originally, we got similar bug report in vscode-cordova repo: https://github.com/microsoft/vscode-cordova/issues/546. After further investigation we found out that ionic chrome webview runtime exposes no domains via JSON RPC by websocket url `ws://127.0.0.1:9223/devtools/page/1`. Chrome webview that is used in latest Cordova app do expose such domains like 'Log', 'Debugger' etc (it uses other url).

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.1 (/Users/akvelon/.nvm/versions/node/v12.6.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, browser 6.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.7 

System:

   Android SDK Tools : 26.1.1 (/Users/akvelon/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v12.6.0 (/Users/akvelon/.nvm/versions/node/v12.6.0/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you seeing this issue when running the Ionic app in a browser or in a standalone app?

**Comment by ruslan-bikkinin** [comment]
@liamdebeasi I am running the app on iPhone 6 (iOS 12.3.1) via `ionic cordova run ios`. AFAIK on lower versions of iOS there were no such problems.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. From what I understand, a Cordova/Capacitor app on iOS uses WKWebView and is only debuggable via Safari.

**Comment by ruslan-bikkinin** [comment]
@liamdebeasi I am afraid, yes, I completely forgot that I was using ios-web-debug-proxy... Do you guys have any plans to make ionic app more friendly to IWDP, since latest Cordova app is even debuggable through IWDP+Chrome?

**Comment by isnowrain** [comment]
@ruslan-bikkinin is it possible for those who want to debug iOS Ionic apps on VSCode use https://github.com/microsoft/vscode-ios-web-debug in order to debug ?

**Comment by liamdebeasi** [comment]
I would recommend posting a feature request in the Ionic WebView Plugin repo. The code required to make this happen probably needs to come from there: https://github.com/ionic-team/cordova-plugin-ionic-webview.

I am going to close this as this is a webview issue, not an issue with the framework. Thanks!

**Comment by ruslan-bikkinin** [comment]
@isnowrain I think I am not a right person to address your question since I maintain only Cordova Tools extension for VS Code.

@liamdebeasi thanks for the answer.
