### ISSUE TITLE
bug: Autogrow should reset back to number of rows specified when text is cleared

### ISSUE THREAD

**Issue by AVatch** [ionic-team/ionic#18744]
# Bug Report

**Ionic version:**

[x] **4.6.1**

**Current behavior:**

Create an `ion-textarea` with `autoGrow` set to `true`. Then on submit or another action set the value to an empty string. The textarea does not revert to its original height. 

**Expected behavior:**

The textarea should reset to the height specified by `rows` or just 1 row.  (This worked in `4.5.0`)

**Steps to reproduce:**

**Related code:**

https://github.com/AVatch/autogrow-bug

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.1
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v11.5.0 (/usr/local/Cellar/node/11.5.0/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by GerardoTovar** [comment]
hello, I discovered that if you put this css, it helps to return to the original size

**in the global css file**
```
    .native-textarea.sc-ion-textarea-md{
       border-width: 0.5px !important;
       border-top-style: solid !important;
    }
```
and you can make it transparent
```
    .native-textarea.sc-ion-textarea-md{
        border-top-color: transparent;
        border-width: 0.5px !important;
        border-top-style: solid !important;
    }
```
![Sin títulsasdo](https://user-images.githubusercontent.com/35576675/61258055-f0b25a80-a730-11e9-9eec-cec88d33d0a8.png)


**You can also use angular Auto-resizing textarea in your ionic application**

[https://material.angular.io/components/input/examples](url)

this is while, the ionic equipment repair the problem :3

English is not my native language, if something is not very clear, let me know
