### ISSUE TITLE
bug: icons not shown since 4.6.0 update

### ISSUE THREAD

**Issue by heinerlamprecht** [ionic-team/ionic#18742]
# Bug Report

**Ionic version:**
[x] **4.6.0**

**Current behavior:**
Icons (ion-icon) are not not shown anymore if the application is not installed in the root directory of the web server.  Reason is, that since version 4.6.0, the icons use a wrong url:

/svg/icon_name.svg

instead of 

./svg/icon_name.svg

The base href is set to "./" in our applications.

**Expected behavior:**

The path of the icons shall be relative to the index.html.

**Steps to reproduce:**

Install any application in some sub directory of the web server.

**Comment by brandyscarney** [comment]
Can you please try with the `dev` version of Ionic?

If using core:

```
npm i @ionic/core@dev
```

If using Angular:

```
npm i @ionic/angular@dev
```

Let me know if that solves it, thank you!

**Comment by heinerlamprecht** [comment]
Just checked it:  The bug is fixed in `4.6.1` and `dev`.
