### ISSUE TITLE
bug: ion-input's cursor jumps to the end after the first key in Safari when text is inserted

### ISSUE THREAD

**Issue by maxtacco** [ionic-team/ionic#18757]
# Bug Report

**Ionic version:**
[x] **4.6.x**

**Current behavior:**
In Safari on Mac when trying to insert text in the middle of`ion-input` the cursor jumps to the end after the first keystroke.

**Expected behavior:**
The cursor should not jump to the end after the first keystroke when text is inserted in `ion-input`.

**Steps to reproduce:**
Open `ion-input`'s demo at [https://ionicframework.com/docs/api/input](https://ionicframework.com/docs/api/input) in Safari on Mac, type text into any of the form ion-inputs, then try to insert text in the middle.

Note:
- Seems to work in 4.5.0
- This bug also effects native iOS apps.
- Everything works fine in Chrome, Firefox.
- Textarea seems to work fine.  

**Other information:**
Safari version: 12.1.1 (14607.2.6.1.1)
macOS Mojave version: 10.14.5 (18F132)

**Comment by maxtacco** [comment]
Not sure if this is 100% related but there is a similar issue open with Angular: https://github.com/angular/angular/issues/21782

**Comment by trevor10032** [comment]
Having the same **critical** issue.  Please fix this

**Comment by eliseocastilla** [comment]
+1 We are experiencing this same issue

**Comment by MiguelSyll** [comment]
I have this problem but in IOS 12 in my app.

**Comment by murito** [comment]
I had this behavior too, i fixed it with @ionic/angular: "^4.7.4"
