### ISSUE TITLE
bug: ion-select popover items in radio group not updating

### ISSUE THREAD

**Issue by AshleyJBartlett** [ionic-team/ionic#18751]
# Bug Report

**Ionic version:**

[x] **4.4.2** (@ionic/angular)

**Current behavior:**

When the ion-select-options are updated, the popover radio options aren't updated to reflect that.

**Expected behavior:**

I would expect the popover radio options to be updated to match the ion-select-options.

**Steps to reproduce:**

On this occasion I am using ion-select in a header component to present a list of languages. When a user logs in, they may not have the full array of languages available to then you the list is updated. I can see that in the HTML markup that the ion-select-options are updated but the ion-items in the popover aren't.

**Related code:**

**header-bar.component.html**
```
<ion-header>
  <ion-toolbar>
    <ion-buttons>
      <ion-select *ngIf="(router.url === '/' && languagesRadioGroup.length > 1) || (router.url === '/log-in' && languagesRadioGroup.length > 1) || (global.session.activeUser.languages.length > 1)" interface="popover" placeholder="{{ 'labels.language' | translate }}" [(ngModel)]="global.currentLanguage" (ionChange)="selectLanguage($event)">
        <ion-select-option *ngFor="let language of languagesRadioGroup" value="{{language.value}}">{{language.label}}</ion-select-option>
      </ion-select>
    </ion-buttons>
  </ion-toolbar>
</ion-header>
```

**log-in.page.html** and **home.page.html**
```
<app-header-bar [languagesRadioGroup]="global.languagesRadioGroup"></app-header-bar>
```

**global.service.ts** (imported into each page)
```
this.languages = [
  {
    label: 'English',
    value: 'en'
  },
  {
    label: 'Deutsche',
    value: 'de'
  },
  {
    label: 'Español',
    value: 'es'
  },
  {
    label: 'Français',
    value: 'fr'
  },
  {
    label: 'Italiano',
    value: 'it'
  },
  {
    label: 'Nederlands',
    value: 'nl'
  }
]

this._session = {
  "activeLanguage":"en",
  "activeUser":{
    "languages":["en","es"],
    "countries":["GB"],
    "defaults":{"language":"en","country":"GB"}
  },
  "activeCountry":""
}

public loadLanguages() {
    this.languagesRadioGroup = [];
    return new Promise((resolve) => {
      if (!(this._session.activeUser === undefined || this._session.activeUser.languages === undefined)) {
        for (let i = 0; i < this.languages.length; i++) {
          const language = this.languages[i];
          let defaultLanguage;
          if (this._session.activeUser.languages.includes(this._session.activeLanguage)) {
            defaultLanguage = this._session.activeLanguage;
            this.currentLanguage = this._session.activeLanguage;
          } else {
            defaultLanguage = this._session.activeUser.defaults.language;
            this.currentLanguage = this._session.activeUser.defaults.language;
          }
          if (this._session.activeUser.languages.includes(language.value)) {
            language.name = 'language' + i;
            language.type = 'radio';
            if (language.value === defaultLanguage) {
              language.checked = true;
            } else {
              language.checked = false;
            }
            this.languagesRadioGroup.push(language);
          }

          if (i === (this.languages.length - 1)) {
            resolve(this.languagesRadioGroup);
          }
        }
      } else {
        for (let i = 0; i < this.languages.length; i++) {
          const language = this.languages[i];
          language.name = 'language' + i;
          language.type = 'radio';
          this.languagesRadioGroup.push(language);

          if (i === (this.languages.length - 1)) {
            resolve(this.languagesRadioGroup);
          }
        }
      }
    });
  }
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.0.2 (C:\Users\xxxxxx\AppData\Roaming\nvm\v12.4.0\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4, browser 5.0.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 17 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.3

System:

   Android SDK Tools : 26.1.1 (C:\Users\xxxxxx\AppData\Local\Android\Sdk)
   NodeJS            : v12.4.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. How are you updating the `languagesRadioGroup ` array?

**Comment by AshleyJBartlett** [comment]
@liamdebeasi - Thank you for your response. I have edited the above to provide various code snippets so hopefully it will make a little more sense. Essentially I am actually maintaining this array elsewhere in a 'global' service and then it is updated in the component through a binding. The header component appears on the Log In page where the full array of languages is available (generated by `loadLanguages()`). Once the user logs in, part of the authentication process calls `loadLanguages()` (to re-generate the array based on the languages available to the user once logged in) and the user is presented with the Home page.

Please let me know if you require any more details.

**Comment by AshleyJBartlett** [comment]
@liamdebeasi - Sorry, I have just added `this.languages` above as I had missed this array out.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. For performance reasons, Stencil (the web component compiler that Ionic uses) only compares references for running change detection, not the data inside of arrays or objects.

This means that the standard mutable array operations such as `this.languagesRadioGroup.push(language);` will not trigger change detection.

In your scenario, you will want to do something like:

```
  this.languagesRadioGroup = [
    ...this.languagesRadioGroup,
    language
  ]
```

The `...` is the Spread operator which "expands" the given object in place: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

You can learn more about how Stencil handles change detection here: https://stenciljs.com/docs/reactive-data

Does this resolve your issue?

**Comment by btsiders** [comment]
I'm interested to see if this is resolved as well. The suggested solution didn't work for me. If it does work for @AshleyJBartlett, I'll open a new ticket. :-)

**Comment by AshleyJBartlett** [comment]
@liamdebeasi and @btsiders - I haven't had chance to try the suggested solution yet but as soon as I have tried it I will let you know of the outcome.

**Comment by AshleyJBartlett** [comment]
Okay, so I have tried the solution that @liamdebeasi suggested and that didn't resolve the issue. Upon testing, I think I may need to update my **steps to reproduce** and maybe add some more code.

Upon first log in the languages are loaded fine. However, when you log out and log back in, if the Home page is the last page the user was on before logging out, then the languages don't load correctly. Otherwise, they do load correctly. It's like its there is some kind of 'caching' going on.

I am also using tabs so maybe this might have an influence. When I get a chance, I'll edit the section above for **steps to reproduce** and various **code snippets**.

**Comment by btsiders** [comment]
My simplified test of what I am doing worked, so I've got something else going on.

**Comment by AshleyJBartlett** [comment]
So, it turns out that @liamdebeasi managed to point me in the right direction so thank you very much for your suggestion.

In the end, in addition to changing how I was updating the arrays, I also had to change how I was updating the properties of the objects as well.

So in the end I updated `loadLanguages()` to the following:

```
public loadLanguages() {
  this.languagesRadioGroup = [];
  return new Promise((resolve) => {
    if (!(this._session.activeUser === undefined || this._session.activeUser.languages === undefined)) {
      for (let i = 0; i < this.languages.length; i++) {
        let language = this.languages[i];
        let defaultLanguage;
        if (this._session.activeUser.languages.includes(this._session.activeLanguage)) {
          defaultLanguage = this._session.activeLanguage;
          this.currentLanguage = this._session.activeLanguage;
        } else {
          defaultLanguage = this._session.activeUser.defaults.language;
          this.currentLanguage = this._session.activeUser.defaults.language;
        }
        if (this._session.activeUser.languages.includes(language.value)) {
          language = {
            ...language,
            name: 'language' + i,
            type: 'radio'
          };
          if (language.value === defaultLanguage) {
            language = {
              ...language,
              checked: true
            };
          } else {
            language = {
              ...language,
              checked: false
            };
          }
          this.languagesRadioGroup = [
            ...this.languagesRadioGroup,
            language
          ];
        }

        if (i === (this.languages.length - 1)) {
          resolve(this.languagesRadioGroup);
        }
      }
    } else {
      for (let i = 0; i < this.languages.length; i++) {
        let language = this.languages[i];
          language = {
            ...language,
            name: 'language' + i,
            type: 'radio'
          };
          this.languagesRadioGroup = [
            ...this.languagesRadioGroup,
            language
          ];

        if (i === (this.languages.length - 1)) {
          resolve(this.languagesRadioGroup);
        }
      }
    }
  });
}
```

@btsiders - Maybe you need to do something the same. Good luck! Please let me know if it works for you as if it doesn't I'd like to know if there is another bug I should be aware of.

I am happy my issue has been resolved now so will close this issue.

**Comment by btsiders** [comment]
My issue has to do with updating the array with an empty array. See https://github.com/btsiders/ion-select-test. I suppose I could make a new bug report for this. I just spent hours trying to get a StackBlitz to work. 😞

**Comment by liamdebeasi** [comment]
@btsiders,

Your scenario looks like a bug. `ion-select` relies on `ionSelectOptionDidUnload` and `ionSelectOptionDidLoad` to be called from `ion-select-option` for the component to update. When switching to the empty array, the `Unload` event is not being seen by `ion-select`.

I believe this is a similar issue as https://github.com/ionic-team/ionic/issues/17344. We were hoping that this issue would be fixed with the Stencil One update, but unfortunately it was not, so I'll have to do some more digging to figure out what the solution would be.
