### ISSUE TITLE
bug: temporary red outline remains after "un-sliding" an ion-item-sliding element

### ISSUE THREAD

**Issue by andy-rash** [ionic-team/ionic#18778]
# Bug Report

**Ionic version:**

[x] **4.6.2**

**Current behavior:**

When using ion-item-sliding with a red, "danger"-colored ion-item-option, after un-sliding a list item, a red outline remains (temporarily) where the ion-item-option was at.

**Expected behavior:**

In this scenario, a list item should not have a red outline after un-sliding it.

**Steps to reproduce:**

Please run the demo from the repository linked below to reproduce the bug.

**Related code:**

Demo repository [here](https://github.com/andy-rash/IonItemSlidingDemo).

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.2 (/Users/andy/.nvm/versions/node/v11.15.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 5 other plugins)

Utility:

   cordova-res : 0.3.0 (update available: 0.6.0)
   native-run  : 0.2.2 (update available: 0.2.7)

System:

   Android SDK Tools : 26.1.1 (/Users/andy/Documents/SDKs/Android)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v11.15.0 (/Users/andy/.nvm/versions/node/v11.15.0/bin/node)
   npm               : 6.10.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Which platform/browser are you seeing this on?

**Comment by andy-rash** [comment]
macOS Mojave (10.14.5), Chrome Version 75.0.3770.100

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Are you able to post a screenshot of what the issue looks like? I am unable to reproduce this issue, but perhaps I am looking for the wrong thing.

**Comment by andy-rash** [comment]
@liamdebeasi I tried this out in Safari (probably should have been one of the first steps, tbh), and the problem isn't showing up there. It must be related to the way Chrome's responsive inspector renders things.

I talked about this with Mike on the Slack channel as well, and that's what he guessed before I tried it on Safari.

Thanks for your help! Sorry if I clogged up the issue tracker at all
