### ISSUE TITLE
bug: [Ionic4.6.x] alertController.dismiss don't send data

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic#18772]
# Bug Report

**Ionic version:**
[x] **4.6.x**

**Current behavior:**
expect `dismiss` be able to send data to `onDidDismiss`.

```ts
const alert = await this.alertCtrl.create({
  header: 'Header',
  message: 'Message',
  buttons: [
    {
      text: 'Close',
      role: 'cancel',
    },
    {
      text: 'Delete',
      handler: () => {
        alert.dismiss({ deleted: true });
      },
    },
  ],
});
await alert.present();
const { data } = await alert.onDidDismiss();
console.log(data);   // expect { deleted: true } , but undefined.
```

**Expected behavior:** 
alertController.dismiss can send data

**Other information:**
- @ionic/angular@4.5.0 is worked.
- modalController is worked.

**Ionic info:**

```
   Ionic CLI                     : 5.2.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.7
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : 1.1.0
   @capacitor/core : 1.1.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.0 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave

```

**Comment by manucorporat** [comment]
The alert-controller handler dismisses the alert already, since the dismiss method is async and you are not waiting, it's actually happening in the next microtask. While this is a regression it was not using the Ionic APIs correct. Just `return false` to prevent the handler to close the alert with undefined data, before, alert.dismiss() happens!
