### ISSUE TITLE
bug: [Ionic 4.6.x] ion-input isn't work expected in @capacitor/ios

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic#18770]
# Bug Report

**Ionic version:**
[x] **4.6.x**

**Current behavior:**
in @capacitor/ios, ion-input is enter duplicate characters.
input `abc` is changed to `aababc`.

This is animation gif.
https://gyazo.com/7728140ec47948396e6bc341c15d8ff8

**Expected behavior:**
input `abc` is `abc`.

**Steps to reproduce:**

**Related code:**

```
  <form #f="ngForm" >
    <ion-list>
      <ion-item>
        <ion-label position="floating">メールアドレス</ion-label>
        <ion-input required type="text" [(ngModel)]="email" name="login.email"></ion-input>
      </ion-item>
    </ion-list>
  </form>
```

**Other information:**

- @ionic/angular@4.5.0 don't have this behavior.
- @ionic/angular@dev(4.7.0-dev.201907111702.67c0d82) have this bug.
- There is no problem with keyboards other than iOS default flick input. 

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : 1.1.0
   @capacitor/core : 1.1.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.0 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This appears to be the same issue as https://github.com/ionic-team/ionic/issues/18770, so I am going to close this issue in favor of that one. You can follow the linked issue for updates regarding this issue.

Thanks!
