### ISSUE TITLE
bug: ion-select with [interfaceOptions] has different margins then rest of ion elements

### ISSUE THREAD

**Issue by ctfrancia** [ionic-team/ionic#18774]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

when using `<ion-select [interfaceOptions]="actionSheetOptions">` the margin takes up full width of screen, while elements inside a `<ion-item>` are consistent.

You can't just place it inside of an `<ion-item>` as then the css get's all messed up and kinda breaks.

**Expected behavior:**

to have an even margin

**Steps to reproduce:**

**Related code:**

```html
<ion-content>
  <ion-item>
    <ion-label position="floating" color="primary">Email</ion-label>

    <ion-input
      type="email"
      [(ngModel)]="email"
      (keydown.enter)="$event.target.blur()"
    ></ion-input>
  </ion-item>

  <ion-list>
    <ion-item lines="none">
      <ion-label>Motivo: </ion-label>
      <ion-select
        (ionChange)="motiveSelect($event)"
        [(ngModel)]="message"
        [interfaceOptions]="actionSheetOptions"
        interface="action-sheet"
      >
        <ion-select-option *ngFor="let reason of listOfReasons" [value]="reason.value">
          {{ reason.content }}
        </ion-select-option>
      </ion-select>
    </ion-item>
  </ion-list>
</ion-content>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.4.1
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Does this issue only happen when including `interfaceOptions`? If so, what does your `interfaceOptions` object look like?

**Comment by ctfrancia** [comment]
Hi, yes it only happens with the [interfaceOptions] because if not I can just place the button in there and have the margin the same as the the others.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you post the value of `actionSheetOptions`?

**Comment by ctfrancia** [comment]
Sure here you go:
```javascript
  public actionSheetOptions: ActionSheetOptions = {
    header: 'header',
    subHeader: 'subheaders',
    handler: (): void => {
      console.log('clicked');
      this._optionSelected();
    },
  };
```

**Comment by liamdebeasi** [comment]
Hey there, sorry for the delay in response. Is this still an issue with Ionic 4.11.2?

**Comment by ctfrancia** [comment]
I don't know if it is still continuing or not. I decided to just use a different method for this in order to not waste time
