### ISSUE TITLE
bug: @ionic/vue vue-router's scrollbehaviour not working

### ISSUE THREAD

**Issue by sotisoti** [ionic-team/ionic#18783]
**Ionic version:**
[x] 4.x
"@ionic/vue": "0.0.9", or @ionic/vue@next

**Current behavior:**
vue-router has a scrollBehavior function that keeps scroll position when returning to page. (eg, after navigating away from another route/ closing a page). However, it doesn't work when using @ionic/vue package.
 
**Expected behavior:**
vue-router's scrollBehaviour will be able to keep track of the scroll position

**Steps to reproduce:**
1) Clone repo: https://github.com/sotisoti/ionic_vue_router_scrollbehaviour and run the app
2) Go to the page bottom and click "Open Page" button
3) Close the new page
4) The home page is visible again, it should scroll to the bottom but it doesn't.
5) In comparison, remove or comment out the following 3 lines from main.js so that vue can remember the scroll position
```
import Ionic from '@ionic/vue';
Vue.use(Ionic);
import '@ionic/core/css/ionic.bundle.css';
```

A sample application via GitHub
https://github.com/sotisoti/ionic_vue_router_scrollbehaviour

**Comment by Livijn** [comment]
Experiencing the same issue.

**Comment by sotisoti** [comment]
Migrating to flutter. Closing this ticket...
