### ISSUE TITLE
bug: Navigation by URL does not work with new IonReactRouter

### ISSUE THREAD

**Issue by ebk46** [ionic-team/ionic#18804]
In ionic/react 0.0.7 the IonReactRouter was introduced as a mandatory replacement for BrowserRouter, but it does not allow navigation by URL. Behavior seems to differ based on surrounding implementation. In my case, it always loads the root page even if the URL is correct. 

However, it is also broken in the ionic-react-conference-app project which is the easiest example to use here. In that case going to /map displays a blank page, and going to /speakers shows the left navigation panel as well as the bottom tabs, but the main content is blank. In both of those cases, the pages work fine when accessed via UI navigation.

EDIT: I found what I think to be the issue. Normally routes are processed in order, so if a route for "/page-name" was found before "/" and the url was "domain.com/page-name", it would stop at that route. With IonReactRouter it doesn't go in order, so every URL gets caught by "/" even if it's last in the list (at least on first load). In my case, adding "exact" to the root route fixed it for me but I believe routing should still work in order (and the conference app is still broken).

**Ionic version:**
[x] 4.6

**Current behavior:**
Navigation by URL does not work. Navigation by UI does. It seems to only match the "/" URL on first load.

**Expected behavior:**
Visiting a URL should match to a route with that URL. 

**Steps to reproduce:**
For the ionic-react-conference-app:
1. Visit https://ionic-react-conference-app.firebaseapp.com/map directly
2. A blank page is shown.
OR
1. Visit https://ionic-react-conference-app.firebaseapp.com/speakers directly
2. A page is shown with the content missing.

Navigating to either via the root page works fine.

**Related code:**
https://ionic-react-conference-app.firebaseapp.com/

**Other information:**
This is absolutely critical to my app and I'm sure to others. IonReactRouter seems to be required in the project where BrowserRouter was working fine. 

**Ionic info:**
```
Ionic:

   Ionic CLI       : 5.2.1 (/Users/evan/.config/yarn/global/node_modules/ionic)
   Ionic Framework : @ionic/react 0.0.7

Capacitor:

   Capacitor CLI   : 1.1.0
   @capacitor/core : 1.1.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.1.0 (/usr/local/Cellar/node/12.1.0/bin/node)
   npm    : not installed
   OS     : macOS High Sierra
```

**Comment by elylucas** [comment]
Closing this issue as its old on a beta version of Ionic/React. If the problem still persists on the latest version, please create a new issue and link this one for reference.
