### ISSUE TITLE
support: Is UIWebView still supported?

### ISSUE THREAD

**Issue by sebastianludwig** [ionic-team/ionic#18803]
The official documentation still lists [downgrading to `UIWebView`](https://ionicframework.com/docs/v3/wkwebview/#downgrading-to-uiwebview) as an option. 

However there was https://github.com/ionic-team/ionic/issues/15134 containing 

> Ionic 4 does not longer support UIWebView

While Cordova still lists many reasons why `WKWebView` might not yet be production ready for everybody: https://cordova.apache.org/news/2018/08/01/future-cordova-ios-webview.html

What's the status here? Is `UIWebView` still supported or is it not?

**Comment by kensodemann** [comment]
FWIW, your first link is to the v3 docs, not the v4 docs. #15134 is far more accurate as to the true state which is basically that UIWebview has been deprecated by Apple for quite some time and should not be used in modern applications.
