### ISSUE TITLE
bug: Ion-Range issue after update to carbon 4.6.0

### ISSUE THREAD

**Issue by IsaacSomething** [ionic-team/ionic#18807]
# Bug Report

**Ionic version:**
[x] **4.6.0**

**Current behavior:**
Please note: This might be a very edge use case. I understand if this issue is closed.

I have a component that has a dynamic `ion-range`. This component is nested in a another component that is a google map control. It holds a lot of things, basically its the menu for the page
```
this.map.controls[ControlPosition.TOP_LEFT].push(document.getElementById('map-menu'));
```

Everything else that the menu does is working, its just the `ion-range`. To be more specific it is just the `ion-range` when the user drops into street view, the `ion-range` is not draggable anymore. The values are in the correct positions. So if i change the range value to 2 then when in street view the range value is 2 but it doesn't work, i cant change the value.

**Expected behavior:**
The `ion-range` should work as expected when the menu component is pushed onto the map when then user enters street view

**Related code:**
```
<ion-item *ngFor="let range of rangeDetails.items;let idx = index; let lst = last"
    [lines]="lst ? 'none' : 'full'">
    <ion-range #rangeSlider snaps="true" pin="true" min="0" color="primary" [max]="rangeDetails.maxValue"
      (ionChange)="rangeChanged(rangeSlider.value,idx)">
      <ion-label slot="start">
        <h4>
          <ion-text color="primary"> {{rangeSlider.value}} </ion-text>
        </h4>
      </ion-label>
      <ion-label slot="end">
        <p> {{rangeDetails.maxValue}} </p>
      </ion-label>
    </ion-range>
  </ion-item>
```

**Other information:**
Everything was working fine until the update to ` "@ionic/angular": "^4.6.0",`. I wasn't  going to post this issue, because it seems like a very specific edge case, but when i was looking at the commits for `4.6.0` in the file `core/src/components/range/range.tsx` there is an import for the letter h
```
, h } from '@stencil/core';
```
Im not sure if that is an actual thing that is used in stencil/core, it does seem a little odd though.
I dont know if that is the cause of the issue ( probably not .. i dont know ), i just trying to narrow down what could be causing it to break like it is.  I have tried updating to the most recent versions, that being `4.6.1` and `4.6.2` but it is still not working.

Unfortunately i dont have a demo to show - So yeah i understand if this issue is unresolved and closed.

**Ionic info:**

```
Ionic CLI : 5.1.1
Ionic Framework: @ionic/angular 4.6.0
@angular-devkit/build-angular: 0.13.9
@angular/cli: 7.3.9
@ionic/angular-toolkit: 1.5.1

NodeJs: v10.12.0
npm: 6.5.0
OS: Windows 10
```

**Comment by brandyscarney** [comment]
Thanks for the issue! The `h` being added was added to every component as part of the update to Stencil One. Unfortunately, if we can't reproduce this, it's hard to fix it. If there's any way you can create a new starter app and just add the page with the map + range it would be helpful, or if you can try and reproduce it in Codepen without Angular at all: https://codepen.io/pen?template=aXENNW
