### ISSUE TITLE
bug: ion-textarea cursor is moved to first position in UWP windows apps

### ISSUE THREAD

**Issue by SchneMa** [ionic-team/ionic#18809]
# Bug Report

**Ionic version:**
[x] **4.12.0**

**Current behavior:**

When using ion-textareawith ionic Platform windows and ionic cordova run windows -- --arch="x84" the cursor stays at position 0. So by just writing or tipping the newest Key is always placed at the start of the ion-textarea.
E.g. if you type the numbers 1 to 0 on your keyboard instead of 
1234567890 
the textarea holds the string
0987654321

When you hit backspace or reenter the textarea the textarea behavior is correct. So its just placing key by key on the correct position without moving the cursor to its start.

**Expected behavior:**

The cursor should stay at the end like in every other platform.

**Steps to reproduce:**

1. ionic start blank
2. ionic serve
3. ionic platform add windows 
4. replace index.html base href with:   `<base href="./" />`
5. replace home.page.html ion-content with:
```
<ion-content>
  <ion-item>
    <ion-label position="floating">Notice</ion-label>
    <ion-textarea type="text"></ion-textarea>
  </ion-item>
</ion-content>
```
6. `ionic cordova run windows -- --arch="x86"`
7. Type something into the textarea 

**Ionic info:**

```
Ionic:
   ionic (Ionic CLI)             : 4.12.0 (C:\pathTo\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:
   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : windows 6.0.1
   Cordova Plugins       : not available

System:
   NodeJS : v10.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as we do not currently support UWP Apps. The engine that powers UWP apps is an older version of Microsoft Edge that we do not support as of Ionic Framework v5.

There are plans to bring the new Chromium Edge engine to UWP apps at which point this issue should be resolved: https://blogs.windows.com/msedgedev/2019/06/18/building-hybrid-applications-with-the-webview2-developer-preview/.

Thanks!
