### ISSUE TITLE
feat: Hide vertical scrollbar (WKWebView)

### ISSUE THREAD

**Issue by roman-rr** [ionic-team/ionic#18811]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

My current application is required some way to hide a vertical scroll bar from ion-content component for improve UX. 

**Describe Preferred Solution**
`::-webkit-scrollbar { width: 0 !important; display:none !important; }` isn't works. 

Objective-C solution for WKWebView plugin ? 
Editing CDVWKWebViewEngine.m ? 

<img width="374" alt="Screen Shot 2019-07-17 at 06 03 24" src="https://user-images.githubusercontent.com/10646478/61335748-d5426f00-a858-11e9-8512-28c33ca5c0ad.png">

**Comment by liamdebeasi** [comment]
Thanks for the feature request! This is not something we are going to provide an API for. Hiding the scrollbar typically degrades the user experience as users do not know what is and what is not scrollable.

If you need this functionality, you should be able to apply the styling in your original post to the `.inner-scroll` element in `ion-content` via JS.

Thanks!
