### ISSUE TITLE
bug: ion-range ionBlur does not fire after change

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/ionic#18818]
# Bug Report

**Ionic version:**
[x] **4.6.2**

**Current behavior:**

If you add a normal ion-range Component with the (ionBlur)="log()" Function. The log Function only gets called, if you drag and then click somewhere else.

**Expected behavior:**

When you move the Slider and then leave the Knob it should call the Function directly. 

**Steps to reproduce:**

ionic start
add `<ion-range [(ngModel)]="distance" (ionBlur)="log()"></ion-range>` to the html and move the slider.

**Comment by liamdebeasi** [comment]
Thanks for the issue. The current `ionBlur` behavior isn't quite right, and we are interested in fixing this. Unfortunately, this will likely require a breaking change so it will have to be done with the next major release of Ionic.

Linking https://github.com/ionic-team/ionic/issues/17839 since it discusses a similar problem.

**Comment by liamdebeasi** [comment]
Thanks for the issue! The `ionBlur` event is supposed to fire when the `ion-range` element loses focus. When dragging `ion-range` and then releasing your mouse, the element is still focussed until you click outside of it. (there is a bug where this does not always happen which we are aware of)

We understand that this is not what people would expect, so we are interested in doing something similar to https://github.com/ionic-team/ionic/issues/17839. This would allow users to detect changes in the value of `ion-range`.

I am going to close this issue in favor of the one I linked to. Feel free to continue the discussion in that thread. Thanks!
