### ISSUE TITLE
bug: Can't scroll if press gesture added

### ISSUE THREAD

**Issue by ocsi94** [ionic-team/ionic#18829]
Scrolls not work when adding press gesture to an element.

Scroll work when : 
`<ion-card  *ngFor="let item of meta.list"  >
  ...
</ion-card>`

Scroll doesn't work when : 
`<ion-card  *ngFor="let item of meta.list" (press)="showSheet(item)" >
  ...
</ion-card>`

Tested on iOS 12.1.4
"hammerjs": "^2.0.8"
"@ionic/angular": "^4.6.2"

I know its maybe a duplications of https://github.com/ionic-team/ionic/issues/18335

[style.touch-action]="'pan-y'" is doesn't work on iOS, because safari does't support it.
ref : https://caniuse.com/#search=touch-action

**Comment by liamdebeasi** [comment]
Thanks for the issue! As I mentioned in https://github.com/ionic-team/ionic/issues/18335, HammerJS has been known to intercept certain events and not let them propagate by default.

I am going to close this as this is not an Ionic issue.
