### ISSUE TITLE
feat: hide modal with gesture

### ISSUE THREAD

**Issue by rafalschmidt97** [ionic-team/ionic#18828]
# Feature Request

**Ionic version:**

[x] **4.6.2**

**Describe the Feature Request**

I would love to see a way to hide a [modal](https://ionicframework.com/docs/api/modal) with gesture instead of just clicking on a button which triggers .dismiss.

**Describe Preferred Solution**

I really like how for example Facebook handled that:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14861637/61445879-82e37a00-a94e-11e9-9f11-152e1718446f.gif)

**Comment by liamdebeasi** [comment]
Thanks for the feature request! We're already working on it 🙂. Here's a preview: https://twitter.com/maxlynch/status/1151592726921658368

**Comment by rafalschmidt97** [comment]
@liamdebeasi Love it 🥰 I'm gonna close this issue because you're already have that!
