### ISSUE TITLE
bug: @ionic/react similar href gets overwritten

### ISSUE THREAD

**Issue by kvzivn** [ionic-team/ionic#18830]
# Bug Report

**Ionic version:**

[x] **4.x**
[x] **@ionic/react: 0.0.7** 

**Current behavior:**

In `<IonTabBar>`, the first `<IonTabButton>` href-value gets overwritten by the second tab button href-value. First tab href-value is "/ana" second is "/analysis". Both become "/analysis".

**Expected behavior:**

The href-values should remain the same after compilation.

**Related code:**

```html
<IonTabButton tab="ana" href="/ana"></IonTabButton>
<IonTabButton tab="analysis" href="/analysis"></IonTabButton>
```

becomes

```html
<ion-tab-button tab="ana" href="/analysis" role="tab" tabindex="0" id="tab-button-ana" class="hydrated ios tab-selected tab-has-label tab-has-icon tab-layout-icon-top ion-activatable ion-selectable ion-focusable" aria-selected="true"></ion-tab-button>
<ion-tab-button tab="analysis" href="/analysis" role="tab" tabindex="0" id="tab-button-analysis" class="ios tab-has-label tab-has-icon tab-layout-icon-top ion-activatable ion-selectable ion-focusable hydrated"></ion-tab-button>
```

**Comment by emindeniz99** [comment]
`exact={true}` can be solution for the problem. Did you add this at Route lines?

For example
`<Route path="/:tab(ana)" component={Tab2} exact={true} />`
`<Route path="/:tab(analysis)" component={Tab3} exact={true} />`

You can read this [https://stackoverflow.com/questions/49162311/react-difference-between-route-exact-path-and-route-path](https://stackoverflow.com/questions/49162311/react-difference-between-route-exact-path-and-route-path)

**Comment by kvzivn** [comment]
Yep, that solved it. Thanks @emindeniz99 !

Closing.
