### ISSUE TITLE
bug: ion-button inside ion-list-header is not visible

### ISSUE THREAD

**Issue by varogonz95** [ionic-team/ionic#18833]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I wanted to have a button inside an ion-list-header, ut it doesn't seem to work since is not visible

**Expected behavior:**

Visible ion-button inside ion-list-header

**Steps to reproduce:**

Just write the following markup

**Related code:**
```html
<ion-list>
    <ion-list-header>
        <ion-label>Some Text</ion-label>
        <!-- Button -->
        <ion-button slot="end" size="small" fill="clear" shape="round" color="danger">
            <ion-icon color="danger" name="trash"></ion-icon>
        </ion-button>
    </ion-list-header>
    <!-- Some items -->
    <ion-item>...</ion-item>
</ion-list>
```

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. `ion-list-header` does not have slots, so doing `slot="end"` will cause the button to not show up. I was able to reproduce this on my end, and removing `slot="end"` fixed the issue.

Here is a CodePen with a working example: https://codepen.io/liamdebeasi/pen/oKNarB
