### ISSUE TITLE
bug: ToastController options type conflict at position key/value

### ISSUE THREAD

**Issue by ctfrancia** [ionic-team/ionic#18872]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I have a rather simple toast controller and when putting in the options for where the toast will be displayed it goes red and gives the error:
> Argument of type '{ header: string; message: string; duration: number; position: string; cssClass: string; }' is not assignable to parameter of type 'ToastOptions'.
  Types of property 'position' are incompatible.
    Type 'string' is not assignable to type '"top" | "bottom" | "middle"'.ts(2345)

**Expected behavior:**

to accept 'top' as a valid location as it says [here](https://ionicframework.com/docs/api/toast#usage)
**Steps to reproduce:**

create a toast with a 'top' position
**Related code:**

###  component.ts
```typescript
    const options = {
      header: 'header,
      message: 'message'
      duration: 6000,
      position: 'top', //<- error here commenting out removes error
      cssClass: 'toastSuccess',
    };
    this.toastService.openToast(options);
```
### toaster.service
```typescript
  public async openToast(options: ToastOptions): Promise<void> {
    const { header, message, duration, position, cssClass } = options;
    const toaster = await this.toast.create({
      header,
      message,
      duration,
      position,
      cssClass,
    });
    await toaster.present();
  }
```

**Other information:**

**Ionic info:**

```
   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.4.1
```

**Comment by cjpollard** [comment]
You've got a type mismatch. In component.ts, you need to set the type of options to ToastOptions.

`const options: ToastOptions = {...};`

**Comment by ctfrancia** [comment]
@cjpollard akjsdfhlaksudhfpiap3yapuyfaiuhdslf hsdljkffh
yep dangit, that was killing me!
