### ISSUE TITLE
bug: Tabs page active state

### ISSUE THREAD

**Issue by rolinbos** [ionic-team/ionic#18889]
# Bug Report

**Ionic version:**

 **4.6**

**Description:**

If you are on a android device with a back button the active stays on the nav button wich is preset last. So in the code if you are first on home and then goes to more and then press on your back button he goes to home but the more is also active but don't show any text only the color is active.

Here you can see that the 'meer' is active but also the image before the 'meer'.

![IMG_7498](https://user-images.githubusercontent.com/34242298/61871787-f69efd00-aee1-11e9-97a9-02f1b06f817e.JPG)

**Related code:**

```
<ion-tabs>

  <ion-tab-bar slot="bottom" color="dark">
    <ion-tab-button tab="landing">
      <ion-icon class="tab-icons" src="img.svg"></ion-icon>
      <ion-label>Home</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="match-center">
      <ion-icon class="tab-icons" src="img.svg"></ion-icon>
      <ion-label>Text</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="selection">
      <ion-icon class="tab-icons" src="img.svg"></ion-icon>
      <ion-label>Select</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="more">
      <ion-icon class="tab-icons" src="img.svg"></ion-icon>
      <ion-label>more</ion-label>
    </ion-tab-button>
  </ion-tab-bar>

</ion-tabs>
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 8 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 6.1.3
   NodeJS     : v9.11.2 
   npm        : 5.6.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? Additionally, which Android version are you testing this issue on?

**Comment by rolinbos** [comment]
This is the repo: https://github.com/rolinbos/ionic-tab-bug 
I use android version 7.0.

**Comment by liamdebeasi** [comment]
Thanks for the follow. This looks like a blank Ionic starter. Is there supposed to be additional code, or should I be able to reproduce the issue with this?

**Comment by rolinbos** [comment]
Yes it's a blank ionic starter. I can't share the exact code because it's private and can't share it. But the blank ionic starter have it also. If you run this on android device then you can reproduce this.

**Comment by liamdebeasi** [comment]
I'm not seeing this issue on the blank starter. What is the user agent string of the device you are testing this on? You can find this by logging `window.navigator.userAgent`.

**Comment by rolinbos** [comment]
Mozilla/5.0 (Linux; Android 7.0; Moto G (5) Build/NPPS25.137-93-8; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/75.0.3770.143 Mobile Safari/537.36 Ionic View/1.0.4

**Comment by liamdebeasi** [comment]
Thanks for the follow up, and apologies for the delay in response. Are you able to post your Angular routing code?

From what I understand, you start on the "Home" tab, go to the "More" tab, and then go "back" causing the issue to occur. Are you using the Android hardware back button, or `ion-back-button` in this case?
