### ISSUE TITLE
bug: ion-button disabled property

### ISSUE THREAD

**Issue by libattistella** [ionic-team/ionic#18901]
# Bug Report

**Ionic version:**

[x] **4.7.0**

**Current behavior:**

Disabled porperty for <ion-button [disabled]="condition"> not change when condition changes. This bug presents to me as a direct result of update @ionic/angular from version 4.6.0 to 4.7.0

**Expected behavior:**

Button changes his state depending of condition value
**Steps to reproduce:**

**Related code:**

```
<form [formGroup]="form"
          (ngSubmit)="onSubmit()">
      <ion-list lines="none">
        <ion-item lines="none">
          <ion-label position="floating" color="medium"><ion-icon name="person"></ion-icon> User code</ion-label>
          <ion-input type="text" formControlName="affiliate"></ion-input>
        </ion-item>
        <div *ngFor="let validation of validationMsg.affiliate">
          <ion-item lines="none"
                    *ngIf="form.get('affiliate').hasError(validation.type) && (form.get('affiliate').dirty && form.get('affiliate').touched)">
            <ion-label>
              <ion-text color="danger" class="ion-text-wrap"><p>{{ validation.message }}</p></ion-text>
            </ion-label>
          </ion-item>
        </div>
      </ion-list>
      <ion-row class="ion-padding">
        <ion-col offset="2" size="8" offset="2">
          <ion-button expand="block"
                      type="submit"
                      [disabled]="!form.valid">
            Log in
          </ion-button>
        </ion-col>
      </ion-row>
    </form>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.3 (C:\Users\Lucas\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.0
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.1.2
   @angular/cli                  : 8.1.2
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 6 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.5

System:

   NodeJS : v12.4.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by manucorporat** [comment]
Are you using tabs?

**Comment by libattistella** [comment]
Not in that page. If the user log in successfully then I navigate to another page where I use tabs

**Comment by libattistella** [comment]
This is my complete html
`<ion-header>
  <ion-toolbar color="primary">
    <ion-title>Iniciar sesión</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content class="ion-padding ion-text-center" scroll="false">
  <div *ngIf="form">
    <form [formGroup]="form"
          (ngSubmit)="onSubmit()">
      <ion-list lines="none">
        <ion-item lines="none">
          <ion-label position="floating" color="medium"><ion-icon name="person"></ion-icon> User code</ion-label>
          <ion-input type="text" formControlName="affiliate"></ion-input>
        </ion-item>
        <div *ngFor="let validation of validationMsg.affiliate">
          <ion-item lines="none"
                    *ngIf="form.get('affiliate').hasError(validation.type) && (form.get('affiliate').dirty && form.get('affiliate').touched)">
            <ion-label>
              <ion-text color="danger" class="ion-text-wrap"><p>{{ validation.message }}</p></ion-text>
            </ion-label>
          </ion-item>
        </div>
      </ion-list>
      <ion-row class="ion-padding">
        <ion-col offset="2" size="8" offset="2">
          <ion-button expand="block"
                      type="submit"
                      [disabled]="!form.valid">
            Log in
          </ion-button>
        </ion-col>
      </ion-row>
    </form>
  </div>
</ion-content>`

**Comment by libattistella** [comment]
Btw, this bug only happens to me when I run my app on android device (API 24). In the browser, when I run ionic serve, the button works fine

**Comment by brandyscarney** [comment]
Is this still an issue in latest? I'm not able to reproduce this using the core components: https://codepen.io/brandyscarney/pen/GRgebeb
