### ISSUE TITLE
bug: date AM/PM with property min does not show the hours well

### ISSUE THREAD

**Issue by GerardoTovar** [ionic-team/ionic#18908]
**Ionic version:**
[x] **4.x**

**Current behavior:**

when you use the min property and switch between AM / PM it does not show the corresponding hours

**Expected behavior:**

if the current time is 5 am you should be able to select any time if you are in PM

**Steps to reproduce:**
you only need the code that I leave below

**Related code:**

```
//dont work
<ion-datetime  
     display-format="h:mm:a"
     value="2019-07-26T04:43:30.048-06:00" 
     min="2019-07-26T04:43:30.048-06:00">
</ion-datetime>

//work
<ion-datetime  
     display-format="HH:mm:a"
     value="2019-07-26T04:43:30.048-06:00" 
     min="2019-07-26T04:43:30.048-06:00">
</ion-datetime>
```

**Other information:**

I think this is also a bug, if you use these formats below it shows a correct value but when you open it shows another time or nothing
```
<ion-datetime 
      display-format="hh:mm:a" 
      value="2019-07-26T13:15:30Z" 
      min="2019-07-26T13:15:30Z" >
</ion-datetime>

<ion-datetime 
      display-format="HH:mm" 
      value="2019-07-26T13:15:30Z" 
      min="2019-07-26T13:15:30Z" >
</ion-datetime>
```

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.3 (C:\Users\L_Z0K\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 8 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.6

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.0.0
   OS     : Windows 10
```

My native language is not English if something is not clear, let me know

**Comment by liamdebeasi** [comment]
Thanks! I can reproduce this issue. I have added this issue to our `ion-datetime` issue tracker: https://github.com/ionic-team/ionic/issues/16630

I am going to close this issue in favor of the main tracker so we can keep all the issues in one place. 🙂
