### ISSUE TITLE
bug: android 4.4.2 white screen

### ISSUE THREAD

**Issue by auron105** [ionic-team/ionic#18905]
android 5,6,7,8,9 is work. but i need run on android 4! 
please help thx!

# Bug Report

**Ionic version:**

[x] **4.7.0**

**Current behavior:**

I run the debug and I get an error.
  Viewport argument key "viewport-fit" not recognized and ignored. 

**Steps to reproduce:**

i'm use ionic cordova run android -l  and use chrome devtools.
and package debug.apk run chrome devtools. still white screen

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.0 (C:\Users\auron\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 0.2.7

System:

   NodeJS : v10.11.0 (D:\soft\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 7
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by henkkelder** [comment]
I have the same problem (white screen) on Android 5.1 since build 4.6.0. 
Build 4.5.0 does run although it also gives the viewport-fit error, but that does not seem to be a problem.

You can simply use ionic start and generate a 'sidemenu' app. That already shows the error when the app is run on Android 5.1.

**Comment by liamdebeasi** [comment]
Thanks for the issue! I was able to reproduce this. I am going to combine this issue with https://github.com/ionic-team/ionic/issues/18939. Please follow that thread for any updates regarding this issue. Thanks!
