### ISSUE TITLE
bug: css rules not working

### ISSUE THREAD

**Issue by BeliliFahem** [ionic-team/ionic#18913]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

CSS properties don't work with ionic 4 project, when work fine with an ionic 3 project or a simple web project (html/css).

Ionic 4 project with one commit that add an html div and css class : https://github.com/BeliliFahem/ionic4-lab

**Expected behavior:**

display text on two lines, and if it goes beyond that, I'll show an ellipsis. As in this PEN code https://codepen.io/belilifahem/pen/eqdOYY or in this ionic 3 project https://github.com/BeliliFahem/ionic3-labs

**Related code:**

```
CSS/SCSS

.nlines-ellipsis {
  max-width: 200px;
  line-height: 1em;
  max-height: 2em;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
  overflow: hidden;
}

HTML

<div class='nlines-ellipsis'>This text must be in two lines with ellipsis. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et.</div>
```

**Other information:**

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 5.2.3 (/Users/fahembelili/.nvm/versions/node/v8.13.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 

System:

   NodeJS : v8.13.0 (/Users/fahembelili/.nvm/versions/node/v8.13.0/bin/node)
   npm    : 6.10.1
   OS     : macOS Mojave
```

**Comment by danielsogl** [comment]
Maybe the Angular view encapsulations is the problem.
Try it this way

```css
:host(.nlines-ellipsis) {
  max-width: 200px;
  line-height: 1em;
  max-height: 2em;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
  overflow: hidden;
}
```

**Comment by Sunny41** [comment]
Hi, ich have a similar problem. I wanted to style a button with the page's scss but it is ignored. when i put the css doce in the global scss it works just fine, but that's not where I want to use the styling... 
i tried adding :host() and css 4 variables. nothing worked for me :/ 
`<button class="button" ion-button color="primary" (click)='skip()'>ButtonText</button>`
`.button{
        font-family: verdana;
        font-weight: bold;
        color: #FFFFFF !important;
        font-size: 14px;
        padding: 8px 19px;
        -moz-border-radius: 22px;
        -webkit-border-radius: 22px;
        border-radius: 22px;
        border: 2px solid #3866A3;
        --ion-background: #009090;
        background: linear-gradient(top,  #00CCCC,  #009090);
        background: -ms-linear-gradient(top,  #00CCCC,  #009090);
        background: -webkit-gradient(linear, left top, left bottom, from(#00CCCC), to(#009090));
        background: -moz-linear-gradient(top,  #00CCCC,  #009090);
    }`
