### ISSUE TITLE
bug: Update to 4.7 incompatible angular peer dependency 

### ISSUE THREAD

**Issue by Siedlerchr** [ionic-team/ionic#18911]
# Bug Report
I followed the upgrade guide to 4.7 
Probably related to https://github.com/angular/angular-cli/issues/14980
(While this is probably an angular problem I thought it's important to have this info here or in the upgrade guide)

```shell
npx ng update @angular/core @angular/cli
```

**Ionic version:**

[x] **4.x**

**Current behavior:**

Running the described command results in error. I can't update to angular 8 correctly.
```
npx ng update @angular/core @angular/cli
                  Package "@angular/compiler-cli" has an incompatible peer dependency to "@angular/compiler" (requires "8.2.0-next.2", would install "8.1.3")
                  Package "@ionic/angular" has an incompatible peer dependency to "@angular/compiler-cli" (requires "7.2.1 - 8" (extended), would install "8.2.0-next.2").
                  Package "@angular/compiler-cli" has an incompatible peer dependency to "@angular/compiler" (requires "8.2.0-next.2" (extended), would install "8.1.3").

```

**Expected behavior:**

The update would not throw an error.

**Steps to reproduce:**

Have an ionic 4.x angular 7 application and run the update commands.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.0 (C:\Users\CS\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.0
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.1.2
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 7 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (C:\Users\CS\AppData\Local\Android\Sdk)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.10.0
   OS                : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Did you follow our Angular 8 Upgrade Guide? https://docs.google.com/document/d/1QOpQeDifPSg6F9WycDLcbQnpqjN96ew-Ap0_CB7CcCQ/edit

**Comment by liamdebeasi** [comment]
Update: Was able to get this myself. Looks like the issue that you linked to. I am going to close this issue, but I will add a note in the upgrade guide regarding this. Thanks!

**Comment by liamdebeasi** [comment]
I updated the guide. Looks like the workaround for now is:

```shell
npm install -g @angular/cli@latest
npx ng update @angular/core
```
