### ISSUE TITLE
bug: White screen in capacitor/electron app after migration to Ionic 4.7 / Angular 8

### ISSUE THREAD

**Issue by eduboxgithub** [ionic-team/ionic#18920]
**Ionic version:**
[x] **4.7.1**

**Current behavior:**
I followed the migrate step from Ionic 4.5/Angular 7 to Ionic 4.7/Angular 8.
The migration was strait forward and the app runs fine in the browser when I run "ionic serve". 
But when I copy www content to my capacitor electron app and run the project I get an white screen with the following error:

```
Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.
polyfills-es2015.491de8af1ffe55992902.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.
main-es2015.b0ace934eaafbfa1fe5e.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.
```

![image](https://user-images.githubusercontent.com/13800439/61975356-cdb16180-afe0-11e9-9e21-200ad0e49e44.png)

**Expected behavior:**
The app should boot and load the necessary scripts.

**Steps to reproduce:**
Migrate an app from an old version of Ionic. You can reproduce this using the sample Ionic projects:

Start a new ionic project (for example a sidemenu sample project);

- Migrate to the new versions;
- Add capacitor to the project;
- Build the project as prod;
- Copy the files to the electron project;
- Run the the electron app. 

You will see a white page.

**Ionic info:**
```
Ionic:
   Ionic CLI                     : 5.2.3 (C:\Users\myuser\AppData\Roaming\nvm\v12.6.0\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.1.2
   @angular/cli                  : 8.1.2
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (C:\Users\myuser\AppData\Local\Android\Sdk)
   NodeJS            : v12.6.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Comment by JeongSeho** [comment]
me too

**Comment by eduboxgithub** [comment]
@JeongSeho check this issue on Capacitor:

https://github.com/ionic-team/capacitor/issues/1813

You have to change the build to es5 in the tsconfig.json.

I will close this issue, and hope for electron suport type="module" in a near future.
