### ISSUE TITLE
bug: Tab page not redrawing when variable value changes

### ISSUE THREAD

**Issue by damirarh** [ionic-team/ionic#18930]
# Bug Report

**Ionic version:**

[x] **4.7.0**

**Current behavior:**

A page inside `ion-tabs` doesn't re-render as a bound variable value changes.

**Expected behavior:**

Every time a bound variable value changes the page should re-render. This happens when the page is not placed in `ion-tabs`

**Steps to reproduce:**

Create a new Ionic 4 project using the `tabs` template. Modify `Tab2Page` to have some dynamic content. E.g. a button incrementing a counter and the value of the counter shown on the same page. Run the application using `ionic serve`, Click Tab Two, start clicking the button. The rendered counter value doesn't change. 

Press F5 in browser to refresh the page so that it now automatically opens on Tab Two. Start clicking the button. The rendered counter value increments as expected.

**Related code:**

Ionic project reproducing the issue:
https://github.com/damirarh/ionic4-tabs-redraw

Relevant code from `Tab2Page`:

```html
<ion-content>
  <ion-button (click)="onClick()">Click</ion-button>
  <p>Clicked {{count}} times.</p>
</ion-content>
```

```typescript
  count = 0;
 
  onClick() {
    this.count++;
  }
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.2 (C:\Users\damir\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : 0.2.7

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by manucorporat** [comment]
This issue was fixed in 4.7.1, please update!
