### ISSUE TITLE
bug: ion-datetime ignores mode when set after initial render

### ISSUE THREAD

**Issue by RafaelKr** [ionic-team/ionic#18952]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When setting the `mode` attribute on `ion-datetime` after it has already rendered, the wrong `mode` is used.

**Expected behavior:**

`ion-datetime` should respect an dynamically changed `mode` attribute.

**Related code:**
https://stackblitz.com/edit/ionic-v4-angular-tabs-qskzhg

The `ios`-mode is forced in the app.module.ts by setting
```
IonicModule.forRoot({
  mode: 'ios'
})
```

I want to open the `ion-datetime` picker with `md`-mode.  
The green items behave correctly, they open in `md`-mode.  
The red item uses the wrong mode (`ios`).  

I also noticed that the red item is slightly shifted to the left.

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.3 (/home/rafael/.nvm/versions/node/v11.9.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : 0.3.0 (update available: 0.6.0)
   native-run  : 0.2.7 (update available: 0.2.8)

System:

   NodeJS : v11.9.0 (/home/rafael/.nvm/versions/node/v11.9.0/bin/node)
   npm    : 6.10.0
   OS     : Linux 4.15
```

Edit: BTW thank you for Ionic v4 Stackblitz, that makes sharing little prototypes so much easier!  
It would be even better to have the link to the v4-stackblitz in the issue template instead of the link to the homepage :wink:

**Comment by RafaelKr** [comment]
/cc @paulstelzer @liamdebeasi
I just found your collection of `ion-datetime` issues #16630. Probably you want to add this one?

**Comment by manucorporat** [comment]
Unfortunately this cannot be done with the current architecture, the mode can't be changed on the fly, creating a new component is required. This happens because different mode means downloading the component again (with different styles). It's not a `ion-datetime` issue, same happens with all the existing components.

**Comment by RafaelKr** [comment]
Okay, thank you for clarification.
So I'll go with ngIf solution.
