### ISSUE TITLE
bug: Hardware Back Button does not update property-binding

### ISSUE THREAD

**Issue by jonashammerschmidt** [ionic-team/ionic#18959]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When I subscribe to the "Hardware Back Button"-Event I can do stuff, like showing a toast with an increasing counter, but the property-binding to the view does not refresh the value.

**Expected behavior:**
When the property is bound to the view and the "Hardware Back Button" is subscribed the view should update its properties after the subscribed event occured.

**Steps to reproduce:**
Repo: https://github.com/jonashammerschmidt/ionic-issue-hardware-back-button

1. Clone, Build and deploy the repo on an android device.
2. Press the "Add"-button to increase the counter.
3. Press the "Hardware Back Button" to show a toast with the counter value, but the content-view is not updating.

## Ionic Info
```
Ionic:

   Ionic CLI                     : 5.2.3 (/Users/b600609/npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/Users/b600609/Library/Android/sdk)
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

I hope you can help me guys!

**Comment by jonashammerschmidt** [comment]
## Ionic Info
Ionic:

   Ionic CLI                     : 5.2.3 (/Users/b600609/npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/Users/b600609/Library/Android/sdk)
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001

**Comment by liamdebeasi** [comment]
Thanks for the issue. We have published a dev build of Ionic with this fix. You can install it using `npm i @ionic/angular@4.8.0-dev.201907311410.3d6c56d`.

Can you give that dev build a try and let me know if it resolves your issue? Thanks!

**Comment by jonashammerschmidt** [comment]
Yeah, the issue got resolved by this change!
