### ISSUE TITLE
bug: ion-grid - you can't centre-align contents in a col with ion-justify-content-center

### ISSUE THREAD

**Issue by AndrWeisR** [ionic-team/ionic#18958]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
When you add `class="ion-justify-content-center"` to an ion-row, I'd expect that the _content_ of each ion-col is centred, but that doesn't happen. The col itself is centred in the row, but not the col contents.

**Expected behavior:**

I expect "ion-justify-content-center" to do as it says, and justify the _content_ within each column in the row.

**Steps to reproduce:**

**Related code:**

This snippet shows a bordered col, which is centred within the row, but the col contents are not centred.
```
<ion-grid>
    <ion-row class="ion-justify-content-center">
        <ion-col style="border: 1px solid;" size="6">
            I am not centred.
        </ion-col>
    </ion-row>
</ion-grid>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.2 (C:\Users\xxxx\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : not available
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 12 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (C:\Android)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 8.1
```

**Comment by brandyscarney** [comment]
The grid uses flexbox, specifically the row is the "container" and the columns are the "items". There's a complete guide to flexbox here that should explain this more in depth: https://css-tricks.com/snippets/css/a-guide-to-flexbox/

If you want the text in the column centered, you can use the class `<ion-col class="ion-text-center">` or apply it to all columns:

```
ion-col {
  text-align: center;
}
```
