### ISSUE TITLE
bug: Application upgraded from ionic 4.6 to 4.7 is not compiling

### ISSUE THREAD

**Issue by iamkinetic** [ionic-team/ionic#18966]
# Bug Report

**Ionic version:**

[x] **4.7.1**

**Current behavior:**
Application was running correctly with Ionic 4.6.* and is not compiling anymore after upgrading to Ionic 4.7.1.  The upgrade went well without a problem.

This is the error : 

> [ng] ERROR in ./node_modules/@ionic/core/dist/esm/loader.mjs 5:9-17
> [ng] Can't import the named export 'a' from non EcmaScript module (only default export is available)
> [ng] ERROR in ./node_modules/@ionic/core/dist/esm/loader.mjs 7:4-17
> [ng] Can't import the named export 'b' from non EcmaScript module (only default export is available)
> [ng] ERROR in ./node_modules/@ionic/core/dist/esm/loader.mjs 6:4-11
> [ng] Can't import the named export 'g' from non EcmaScript module (only default export is available)
> [ng] ERROR in ./node_modules/@ionic/core/dist/esm/index.mjs 3:0-202
> [ng] Can't reexport the named export 'a' from non EcmaScript module (only default export is available)
> [ng] ERROR in ./node_modules/@ionic/core/dist/esm/index.mjs 3:0-202
> [ng] Can't reexport the named export 'b' from non EcmaScript module (only default export is available)
> [ng] ERROR in ./node_modules/@ionic/core/dist/esm/index.mjs 3:0-202
> [ng] Can't reexport the named export 'c' from non EcmaScript module (only default export is available)
> [ng] ERROR in ./node_modules/@ionic/core/dist/esm/index.mjs 3:0-202
> [ng] Can't reexport the named export 'l' from non EcmaScript module (only default export is available)
> [ng] ERROR in ./node_modules/@ionic/core/dist/esm/index.mjs 3:0-202
> [ng] Can't reexport the named export 'm' from non EcmaScript module (only default export is available)
> [ng] ERROR in ./node_modules/@ionic/core/dist/esm/index.mjs 3:0-202
> [ng] Can't reexport the named export 'p' from non EcmaScript module (only default export is available)
> [ng] ERROR in ./node_modules/@ionic/core/dist/esm/index.mjs 3:0-202
> [ng] Can't reexport the named export 't' from non EcmaScript module (only default export is available)
> [ng] ERROR in ./node_modules/@ionic/core/dist/esm/chunk-d83bfeae.js 143:28
> [ng] Module parse failed: Unexpected token (143:28)
> [ng] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> [ng] |     baseEl.classList.remove('overlay-hidden');
> [ng] |     const aniRoot = baseEl.shadowRoot || overlay.el;
> [ng] >     const animation = await import('./index-d9adb105.js').then(mod => mod.create(animationBuilder, aniRoot, opts));
> [ng] |     overlay.animation = animation;
> [ng] |     if (!overlay.animated || !config.getBoolean('animated', true)) {
> [ng] ERROR in ./node_modules/@ionic/core/dist/esm/chunk-84f6bf13.js 65:11
> [ng] Module parse failed: Unexpected token (65:11)
> [ng] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> [ng] |         return module[exportName];
> [ng] |     }
> [ng] >     return import(
> [ng] |     /* webpackInclude: /\.entry\.js$/ */
> [ng] |     /* webpackExclude: /\.system\.entry\.js$/ */
> [ng] ERROR in ./node_modules/@ionic/core/dist/esm/polyfills/index.js 7:18
> [ng] Module parse failed: Unexpected token (7:18)
> [ng] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> [ng] | 
> [ng] |   if (!win.customElements || (win.Element && (!win.Element.prototype.closest || !win.Element.prototype.matches || !win.Element.prototype.remove))) {
> [ng] >     promises.push(import('./dom.js'));
> [ng] |   }
> [ng] | 
> [ng] ERROR in ./src/app/app-routing.module.ts 8:40
> [ng] Module parse failed: Unexpected token (8:40)
> [ng] File was processed with these loaders:
> [ng]  * ./node_modules/@ngtools/webpack/src/index.js
> [ng] You may need an additional loader to handle the result of these loaders.
> [ng] | const routes = [
> [ng] |     { path: '', redirectTo: 'login', pathMatch: 'full' },
> [ng] >     { path: 'home', loadChildren: () => import('./home/home.module').then(m => m.HomePageModule) },
> [ng] |     { path: 'login', loadChildren: () => import('./login/login.module').then(m => m.LoginPageModule) /*, canActivate: [LoginActivate]*/ },
> [ng] |     {
> [ng] i ｢wdm｣: Failed to compile.

**Expected behavior:**
It should compile and run.

**Steps to reproduce:**
`ionic serve`, `ionic build`, `ng serve` and `ng build` all give the same error.

This is the application I'm trying to build : https://github.com/CAUCA-9-1-1/survip-mobile/tree/Ionic47%2BAngular8

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.1 (C:\Users\someuser\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 0.2.7

System:

   NodeJS : v11.4.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Did you follow our Angular 8 Upgrade Guide? https://docs.google.com/document/d/1QOpQeDifPSg6F9WycDLcbQnpqjN96ew-Ap0_CB7CcCQ/edit

**Comment by iamkinetic** [comment]
Yes, I did follow the guide.  I didn’t get any of the potential issues while upgrading.

**Comment by iamkinetic** [comment]
It's now compiling correctly, but here is what was different from yesterday attempts (yes, I did restart the whole process a couple of time yesterday):
* Upgraded npm from 6.4.1 to 6.10.2
* Apparently Angular 8.2 got released since yesterday and this is the version I upgraded to this morning.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you try upgrading to Angular 8.2.0 and see if that helps?https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by AlluNandaKishore** [comment]
It didn't solved with the above approach, can anyone help me on this.
