### ISSUE TITLE
feat: Demo repo for ionic/vue

### ISSUE THREAD

**Issue by d0peCode** [ionic-team/ionic#18960]
Can someone share working demo with ionic/vue? I had error with icons, then error with blank page I'm not able to create fresh ionic/vue project with CLI. I can not find any demo or anything. If you have working empty project with vue/ionic please create repo and share so I can fork. Please

**Comment by liamdebeasi** [comment]
Thanks for the issue. We have ported the Ionic Conference App to `@ionic/vue` which you can view here: https://github.com/ionic-team/ionic-vue-conference-app. There's also a blog post about the `@ionic/vue` beta: https://ionicframework.com/blog/announcing-the-ionic-vue-beta/.

`@ionic/vue` is still under development, so there might be some bugs. Feel free to open issues for any bugs you find. Thanks!
