### ISSUE TITLE
bug: cordova camera plugin gallery image upload duplicate

### ISSUE THREAD

**Issue by shraddha-khalekar** [ionic-team/ionic#18961]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by shraddha-khalekar** [comment]
Ionic version:
4.12.0

Current behavior:

 My app allows users to select 2 images from gallery / camera using navigator.camera.getPicture, then retrieves the Camera.DestinationType.FILE_URI, which is later used for uploading via the FileTransfer plugin, sending the file to server in sequence. Now, the weird problem is the 2 photos uploaded by our Android app users ended up with BOTH being the second photo. That means, after user selected photo 1 and 2, and uploaded both, the server end received the images as both being photo 2. Please advise, thanks!

Expected behavior:
multiple images uploaded by cordova camera plugin and file transfer plugin should not override with one another. It should separate. 

Related code:
async upload(sourceType: PictureSourceType) {

    let options: CameraOptions = {
      quality: 50,
      sourceType: sourceType,
      saveToPhotoAlbum: true,
      correctOrientation: true,
      destinationType: this.camera.DestinationType.FILE_URI,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE,
      allowEdit: true
    };

    //clicking image or getting image from gallery.
    await this.camera.getPicture(options).then((imageData) => {

      this.album.push(imageData);
      this.dataService.setData(this.album);

      if (this.plt.is('android') && sourceType === this.camera.PictureSourceType.PHOTOLIBRARY) {
        this.filePath.resolveNativePath(imageData)
          .then(filePath => {
            let correctPath = filePath.substr(0, filePath.lastIndexOf('/') + 1);
            let currentName = imageData.substring(imageData.lastIndexOf('/') + 1, imageData.lastIndexOf('?'));
            this.copyFileToLocalDir(correctPath, currentName, this.createFileName());
          });
      } else {
        var currentName = imageData.substr(imageData.lastIndexOf('/') + 1);
        var correctPath = imageData.substr(0, imageData.lastIndexOf('/') + 1);
        this.copyFileToLocalDir(correctPath, currentName, this.createFileName());
      }
    });
  }
Other information:

Ionic info:

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 14 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/ttpl34/Documents/Android-sdk/)
   NodeJS            : v10.15.3 (/usr/bin/node)
   npm               : 6.9.0
   OS                : Linux 4.15

insert the output from ionic info here

**Comment by liamdebeasi** [comment]
Thanks for the issue. Ionic Framework does not manage the camera plugin. I would recommend filing a bug on the [cordova-plugin-camera GitHub](https://github.com/apache/cordova-plugin-camera) instead.

I am going to close this as this is not an Ionic issue. Thanks!
