### ISSUE TITLE
bug: IonReactRouter is not exported from @ionic/react

### ISSUE THREAD

**Issue by Joshua-Schecker** [ionic-team/ionic#18964]
# Bug Report

**Ionic version:**

[x] **4.7.1**

**@ionic/react version:** 

[x] **0.0.9**

**Current behavior:**

When importing IonReactRouter component, the following error message results:
```Attempted import error: 'IonReactRouter' is not exported from '@ionic/react'.```

**Expected behavior:**

It should be able to import the component from the library without an error.

**Steps to reproduce:**

- Create starter app with CRA
- Import IonReactRouter

**Related code:**

```
import React from 'react';
import { Redirect, Route } from 'react-router-dom';
import { IonReactRouter, IonApp, IonPage } from '@ionic/react';
import UserList from 'routes/UserList';
import Navbar from 'components/Navbar';
import '@ionic/core/css/core.css';
import '@ionic/core/css/ionic.bundle.css';
import 'theme.css';

export default class App extends React.Component {
  public render() {
    return (
      <IonApp>
        <IonReactRouter>
          <IonPage>
            <Navbar />
            <Route path="/userlist" component={UserList} />
            <Redirect exact from="/" to="/userlist" />
          </IonPage>
        </IonReactRouter>
      </IonApp>
    );
  }
}
```

**Other information:**

I followed the guide for [react routing](https://ionicframework.com/docs/react/navigation) and it worked fine in version 0.0.7.
After updating to 0.0.9, I am unable to import IonReactRouter component.

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI) : 4.12.0 (/usr/local/lib/node_modules/ionic)

Capacitor:

   capacitor (Capacitor CLI) : 1.1.1
   @capacitor/core           : 1.1.1


System:

   NodeJS : v10.10.0 (/usr/local/Cellar/node/10.10.0/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by elylucas** [comment]
Hi @Joshua-Schecker,

Sorry for the confusion. In React Beta 9, IonReactRouter was moved to its own package. Try to import it like so:

import { IonReactRouter } from '@ionic/react-router';

Let us know if that fixes the issue.

Thanks

**Comment by Joshua-Schecker** [comment]
> Hi @Joshua-Schecker,
> 
> Sorry for the confusion. In React Beta 9, IonReactRouter was moved to its own package. Try to import it like so:
> 
> import { IonReactRouter } from '@ionic/react-router';
> 
> Let us know if that fixes the issue.
> 
> Thanks

Hi,
Thank you for the fast response.
I tried your suggestion, but it was unable to find the module.
```
Module not found: Can't resolve '@ionic/react-router' in '/Users/josh/Repos/application-user-management/src/components/App'
```

**Comment by elylucas** [comment]
@Joshua-Schecker You might have to install @ionic/react-router manually if you used CRA and not the CLI to start the project.

**Comment by Joshua-Schecker** [comment]
Ah of course! That was the problem.
Thank you for your help!
