### ISSUE TITLE
feat: set `pointer-events: none` while dismissing a select popover

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic#18978]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**

I have an `ion-select` with interface type set to `popover`. After selecting one of the options, during the dismiss animation of the popover, the popover is still clickable (and in fact it's still possible to change the selection). This happens for a specific UI where an action button is underneath the select popover and when I'm very fast to click the button, I accidentally change the selected option. It would be nice if the interaction with the popover would stop as soon as an option is selected and the dismiss animation has started.

**Describe Preferred Solution**

It's probably as simple as adding `pointer-events: none` via CSS during the dismiss animation. As far as I can tell the animation style gets injected into the popover-content div anyway, so should be pretty straight-forward to implement.

**Describe Alternatives**

No other ideas so far.

**Related Code**

Not an example of the feature request, but here's an example of the issue this would solve:

https://codepen.io/simonhaenisch/pen/KOvNem?editors=1000

<img src="https://user-images.githubusercontent.com/3410759/62325706-90e7dd80-b4ac-11e9-99ee-941c846f280b.gif" alt="screen capture" width="500">

Even though "Foo" has been selected, and the popover is already visible, it's still clickable and changes the option to "Bar".

**Additional Context**

Could probably do the same for other dismiss animations like modals and action sheets.

I can submit a PR if you let me know that you'd like this, please.

**Comment by liamdebeasi** [comment]
Thanks for the feature request! This was fixed in Ionic Framework v5.1.
