### ISSUE TITLE
forceOverscroll not working with card

### ISSUE THREAD

**Issue by KyDenZ** [ionic-team/ionic#18979]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
The attribute: forceOverscroll with the value false works well without cards. But if I add cards with ion-card-header, forceOverscroll does not work anymore.

**Expected behavior:**
If we set forceOverscroll to false, it should not activate it if there are cards

**Steps to reproduce:**
The basic application with tabs generated with Ionic is enough. Open with Safari. Add the forceOverscroll attribute with the false value.

The bug does not appear if you were removed the component: ion-card-header on card

**Ionic info:**
Ionic CLI : 5.2.3
Ionic Framework : ionic-angular 4.7.1

Thanks

**Comment by manucorporat** [comment]
ion-card does not have anything to do with ion-content, I am not sure what you mean. What do you expect from forceOverscroll=false?

**Comment by KyDenZ** [comment]
On my pages I try to disable the bounce on IOS (equivalent to the no-bounce attribute of Ionic3):
https://forum.ionicframework.com/t/ionic-4-disable-bounce-effect-on-ios/153513

Except that when I put a card with a header, the bounce appears

**Comment by manucorporat** [comment]
Is the card large enough to cause scrolling?

**Comment by KyDenZ** [comment]
Actually .. So my page is less high ... Sorry ....

But suddenly, how to have the equivalent of no-bounce Ionic 3? Since forceOverscroll to false does not work

**Comment by manucorporat** [comment]
I can't reproduce the issue, can you provide a repo case?

On the other side, bounding can not be disabled in iOS once the content of ion-content becomes scrollable.

when forceOverscroll===true, it forces scroll even though the content fits without scrolling.

**Comment by manucorporat** [comment]
forceOverscroll = [no-bounce], but it was renamed to better fit what it actually does.

**Comment by KyDenZ** [comment]
Okay.

I saw on the side of capacitor a solution to prevent the bounce when the scroll is activated. Thank you for your answers.
