### ISSUE TITLE
feat: "Custom splash screen" or "not hiding the index.html content on app start"

### ISSUE THREAD

**Issue by moshe5745** [ionic-team/ionic#18971]
It would be nice if the index.html wasn't hidden in angular + ionic application.

In clean Angular project without Ionic the index.html content (div elements, etc.) isn't hidden on start-up. So it's possible to insert some content within the <app-root> tag and make a nice splash screen.

In Ionic project the content you place in <app-root> is hidden until all the *.js files are loaded. So all the "splash screen" effect is lost.

Angular only app generated by the Angular CLI:
![angular-only](https://user-images.githubusercontent.com/7037149/62477235-39e64f00-b7b1-11e9-9778-38750dd9cdaa.gif)

Ionic+Angular app generated by the Ionic CLI:
![ionic-angular](https://user-images.githubusercontent.com/7037149/62477245-4074c680-b7b1-11e9-91cd-d7d9a5ed39c4.gif)

The content added to the app-root tag in index.html:
`
<app-root>
    <div style="display: flex; justify-content: center; align-content: center">
      <h1>INDEX.HTML</h1>
    </div>
  </app-root>
`

As you can see the content is gone in  the ionic+angular app.

Article that i used to make splash-screen:
https://medium.com/@tomastrajan/how-to-style-angular-application-loading-with-angular-cli-like-a-boss-cdd4f5358554

Maybe it is possible not to hide this content?

**Comment by moshe5745** [comment]
Article that i used to make splash-screen: 
https://medium.com/@tomastrajan/how-to-style-angular-application-loading-with-angular-cli-like-a-boss-cdd4f5358554

**Comment by moshe5745** [comment]
Any comments about this?

**Comment by mhartington** [comment]
So I did a quick check to see if the content is actually getting rendered in `app-root`, which it is.

![Screen Shot 2019-09-09 at 10 16 50 AM](https://user-images.githubusercontent.com/2835826/64538630-f79db980-d2ea-11e9-9bdd-26af9ad73855.png)


What I think is happening here is the initial rendering of app-root shows "INDEX.HTML" quickly, but the app has been bootstrapped, so it's only visible for a few milliseconds. You can more visibly see that index.html is there if you emulate slower networks.

![loading-index](https://user-images.githubusercontent.com/2835826/64539011-ad690800-d2eb-11e9-91b8-4a91da680be0.gif)


And a live example can be seen at 

https://startrack-ng.web.app


So I'm not sure this is an actual issue, but more just the app is bootstrapping so fast.

**Comment by moshe5745** [comment]
@mhartington Thanks for the reply.
I saw that the index.html is been rendered. But after small amount of time the <body> content is been hidden for some reason of ionic bootstrap/startup. My suggestion was not to hide the index.html <body> content. So we can make dynamic splash screen and not use static cordova splash screen. Now you can only add css to the index.html <body> tag that would not be "hidden".

**Comment by mhartington** [comment]
Again the reason is not from Ionic, just that Angular and everything is bootstrapped and ready to load.

In theory, you could defer the main bootstrapping in `main.ts` and have something. Play an animation, fire an event, then on the event fire, you load the app. But that's beyond the scope of this issue and does not have anything to do with Ionic.


Going to close this is this as this is not an issue with broken functionality or feature request. You should ask this on the Ionic forum

https://forum.ionicframework.com
