### ISSUE TITLE
bug: ion-slides android: no pager is shown

### ISSUE THREAD

**Issue by explofish** [ionic-team/ionic#18983]
# Bug Report

**Ionic version:**

[x] **4.7.1**

**Current behavior:**

When using ion-slides on android (simulator and device) only the first slide is displayed and no pager is shown. If you lock and wake the device, its behaving correctly.

**Expected behavior:**

the pager is shown

**Steps to reproduce:**

install the latest ionic with cordova on android

**Comment by explofish** [comment]
Okay i got some more insight:

I have Matter.js in my project (http://brm.io/matter-js/)

As soon as i initialize the canvas, ion-slides stop working in android.

When i destory the canvas, it is working again!

So my workaround will now be to only activate matter when it is needed.

The interesting thing is, the pager is being shown without any re-creation of the ion-slider. The instance of ion-slider recovers itself when the matter.js canvas is destroyed!

What i'm wondering now is, is there any special android implementation which uses canvas or something? Or is this something matter.js should be fixing?

Thanks so much :)

**Comment by brandyscarney** [comment]
Thanks for the issue! I am going to close this as it sounds like you were able to resolve the issue. If this is still an issue with the latest version of Ionic Framework, please open a new issue with a sample codebase that reproduces the problem. There is no special implementation with canvas in our slides components and it is a 3rd party dependency (located [here](https://swiperjs.com/api/)).
