### ISSUE TITLE
bug: Appflow Deploy fails update on certain 2G WiFi Networks

### ISSUE THREAD

**Issue by ChampRay** [ionic-team/ionic#18987]
Bug Report

**Ionic version:**

[x] @ionic/pro ^2.0.3

**Current behavior:**
Appflow Deploy manual updater will work on most WiFi networks, however some 2G WiFi networks the appflow will pend an update and never follow through. We've launched our software across 100 tablets and know its WiFi network based.

**Expected behavior:**
For the appflow deploy updater to work regardless of WiFi network type.

**Steps to reproduce:**
It's random, not exactly sure why appflow decides to fail with certain WiFi networks and its not that the internet is not connected because everything else loads perfectly besides specifically appflow updater.

**Related code:**

```
 forceAppUpdate(channelId) {
        return new Promise((resolve, reject) => {
            try {
                Pro.deploy.configure({
                    'channel': channelId
                }).then(() => {
                    Pro.deploy.sync({updateMethod: 'auto'}).then((resp) => {
                        if (!resp) {
                            reject("No response");
                            return;
                        }

                        if (this.currentVersion < resp.versionId) {
                            resolve();
                            // We found an update, and are in process of redirecting you since you put auto!
                        } else {
                            reject("No update available");
                        }
                    }).catch(() => {
                        reject("Sync failed");
                    });
                }).catch(() => {
                    reject("Configure failed");
                });
            } catch (err) {
                reject("forceAppUpdate failed");
            }
        })
    }
```

**Comment by CitizenBeta** [comment]
I'm also running into this issue and its creating major problems. If this can't be fixed we'll need to find another solution as an alternative to Ionic Appflow for rapid deployment.

**Comment by liamdebeasi** [comment]
Thanks for the issue. If you are running into an issue with AppFlow, please contact AppFlow support. This issue tracker is dedicated to bugs and feature requests for Ionic Framework.
