### ISSUE TITLE
bug: ion-label is "blury" when stacked inside ion-item, not scaling otherwise

### ISSUE THREAD

**Issue by kgdiem** [ionic-team/ionic#18986]
# Bug Report

**Ionic version:**

[x] **4.6.2**, **4.7.0**

**Current behavior:**

When using a ion-label with position="stacked" the text on the label gets "blurry" like it's an image.

**Expected behavior:**

It should be clear and crispy.

**Steps to reproduce:**

Use an ion-label with position stacked nested inside ion-item 

**Related code:**
https://stackblitz.com/edit/ionic-v4-angular-tabs-gzg5b1

**Other information:**

Similar to https://github.com/ionic-team/ionic/issues/18255 

Isn't reproducible on https://ionicframework.com/docs/api/input anymore

**Ionic info:**

```
$ ionic info

Ionic:

   Ionic CLI                     : 5.2.2 (C:\Users\kdiem\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.2 (D:\Websites\ngx-esp\node_modules\@ionic\angular)
   @angular-devkit/build-angular : 0.801.0 (D:\Websites\ngx-esp\node_modules\@angular-devkit\build-angular)
   @angular-devkit/schematics    : 7.3.9 (D:\Websites\ngx-esp\node_modules\@angular-devkit\schematics)
   @angular/cli                  : 8.1.0 (D:\Websites\ngx-esp\node_modules\@angular\cli)
   @ionic/angular-toolkit        : 2.0.0 (D:\Websites\ngx-esp\node_modules\@ionic\angular-toolkit)

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 7.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 9 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.7

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. What kind of display and browser are you testing this on? I am unable to reproduce this issue on Chrome on my Mac's internal screen using the link you gave me.

**Comment by kgdiem** [comment]
Windows 10, Chrome. Internal display of Lenovo. 

![image](https://user-images.githubusercontent.com/13109365/62644568-6799d800-b918-11e9-8231-d46c091ab095.png)

**Comment by tantebootsy** [comment]
I can confirm this issue on my local Chrome and Firefox on a Mac within my own project /w ionic 4.6.0

@liamdebeasi can you reproduce if you set the following for example:

`ion-item{ font-size: inherit;}
  .item .sc-ion-label-md-h{font-size: 12px}
`

You should be able to see, that the 12px of the ion-label is scaled down additionally – so that in the end it's much less than 12px – at least it looks like that to me.

**Comment by liamdebeasi** [comment]
@tantebootsy Thanks for the follow up. What kind of display are you testing this on?
