### ISSUE TITLE
feat: Wearables using IONIC

### ISSUE THREAD

**Issue by tvvignesh** [ionic-team/ionic#18988]
Hi there. I was wondering if IONIC can be used to make apps for wearables WearOS (https://wearos.google.com) and WatchOS (https://www.apple.com/in/watchos/watchos-preview/)

Tried searching through the documentation but was not able to find enough information on the same. Is it possible to use IONIC 4 for the same? If yes, may I know where to find the relevant documentation for it? And if not, any alternative you would like to suggest? Or is it in your roadmap?

Btw, kudos to the amazing work you guys have been doing - Really love IONIC 4 and the way you have made everything framework independent. One suggestion I have is that you might have to create more examples and tutorials around vanillajs since most of them are around Angular or other frameworks being used with IONIC.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. We do not have any official support for wearable apps. If you are interested in trying to get an Ionic app to work on a wearable, we would love to hear about your experience!
