### ISSUE TITLE
bug: Uncaught SyntaxError: Identifier 'originalPrompt' has already been declared     at prompt.js:1

### ISSUE THREAD

**Issue by MrBokeh** [ionic-team/ionic#18991]
# Bug Report

**Ionic version:**
[x] **4.7.1**

**Current behavior:**
If you create and run a new project and inspect the code with the developer tool console on Chrome, you will see this error:
```
Uncaught SyntaxError: Identifier 'originalPrompt' has already been declared
    at prompt.js:1
```

**Expected behavior:**
No error

**Steps to reproduce:**
1) Create a new ionic app
2) run ionic serve
3) check out the developer tool console
4) find the red error:
```
Uncaught SyntaxError: Identifier 'originalPrompt' has already been declared
    at prompt.js:1
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : not installed
   native-run  : 0.2.7 (update available: 0.2.8)

System:

   NodeJS : v10.16.1 (/usr/local/bin/node)
   npm    : 6.10.2
   OS     : macOS Mojave
```

**Comment by manucorporat** [comment]
`originalPrompt` is not part of the ionic codebase and we can't reproduce the issue in a new started app. Please provide a repo case and review your dependencies
