### ISSUE TITLE
[native-run] ERR_UNKNOWN: Non-zero exit code from adb: 1 [ERROR] An error occurred while running subprocess native-run.

### ISSUE THREAD

**Issue by abhishek3999** [ionic-team/ionic#18995]
I am trying to run app using ionic cordova run android.
So facing above errror.

Tried all solutions like :
1.Ionic,cordova update
2. platform remove and reinstall.

Please help me!

**Comment by BeastPhoenix** [comment]
Hi there, 
I faced the same Issue on my device "Samsung Galaxy J7 Prime"
I run the command with --verbose and realized its either a problem with not enough storage on the phone or a restriction from the device itself
so if you don't have enough space on the phone make sure to make a space on your storage 
a plus to that I figured there is an option in my device under Settings->Developer Options->Verify application via USB ( it verifies if the app installed via adb or adt before really woring on the phone ) so you have to disable it 
PS: I've tried running the app on other devices and it was built and run successfuly, So, I figured its device related problem
