### ISSUE TITLE
bug: Can't click on buttons/links after opening external link

### ISSUE THREAD

**Issue by MoeGH7** [ionic-team/ionic#18996]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

After opening an external link (target="_blank") in my Ionic PWA on my iPad (Safari), and subsequently closing the resulting new tab, I can't click on any buttons/links in my PWA to activate them; I have to click *below* the buttons/links to activate them.
To restore the expected behaviour, I have several possibilites: (1) Opening the tab overview and selecting the tab with the PWA again, (2) zooming in and out, (3) reloading the page.
This behaviour shows only if my PWA is the only open tab - if there are two tabs open, everything works as expected.

**Expected behavior:**

I should be able to click *on* the buttons/links and not *below* them to activate them.

**Steps to reproduce:**

0. Start a new project ("ionic start myApp blank" will do as it already contains a link) and serve it.
1. Use an iPad.
2. Close all tabs - this is important.
3. Open the new project on the iPad with Safari.
4. Click *on* the link on the page to open it - this works as expected.
5. Close the new tab by either clicking back or by clicking on the "Close" button.
6. Click *on* the link again to open it - nothing happens.
7. Click *below* the link - the link will open...

**Other information:**

This behaviour only shows on my iPad (I don't own/have access to an iPhone) - Android is working fine.
I'm not sure, but I think that this bug started showing beginning with iOs 12.*4*.
**Ionic info:**

```
$ ionic info

Ionic:

   Ionic CLI                     : 5.2.3 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3 (/usr/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.9
```

**Comment by MoeGH7** [comment]
Hi,
it seems that this is related to the ~ionic/angular/css/structure.css stylesheet.
If I remove the corresponding `@import` from my global.scss file the mentioned bug disappears. However, obviously this solution is not optimal.
If I paste the content of the structure.css file into my global.scss file, the bug reappears. This enabled me to narrow the cause down to this line:

```
body {
  position: fixed;
  /*
  and so on
  */
}
```
`position: fixed;` is the culprit, when I remove this line everything is working as expected, at least concerning the bug.
However, as removing `position: fixed` is not a great idea - what can I do now? Any ideas?
Thanks!

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
