### ISSUE TITLE
feat: --color-hover property on ion-segment-button

### ISSUE THREAD

**Issue by matthew-valenti** [ionic-team/ionic#18990]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
Add new CSS custom property to ion-segment-button component: --color-hover

**Describe Preferred Solution**
Add new CSS custom property and update documentation here: https://ionicframework.com/docs/api/segment-button

**Describe Alternatives**
```
ion-segment-button {
    &:hover {
        --color: #000000;
    }
}
```

**Comment by indraraj26** [comment]
Ionic Team, 

is there anyway to do it our self?

**Comment by brandyscarney** [comment]
Here is a workaround: https://codepen.io/brandyscarney/pen/yLBgwYM

```
ion-segment {
  --color-hover: red;
}

@media (any-hover: hover) {
  ion-segment-button:hover {
    color: var(--color-hover);
  }
}
```

**Comment by brandyscarney** [comment]
I'm going to close this as it seems it has been added to segment button with the latest changes for Ionic 5. We currently have a beta out but expect a release candidate next week. If you'd like to try out the latest beta see the following:

Releases: https://github.com/ionic-team/ionic/releases
Breaking changes for v5: https://github.com/ionic-team/ionic/blob/master/BREAKING.md
Breaking changes for Segment (on my TODO to add these to the file above): https://gist.github.com/brandyscarney/e6cfe43c359bb2c932e12f8d615e1669

Some big changes coming to the button states here as well: https://github.com/ionic-team/ionic/pull/19440
