### ISSUE TITLE
bug: ion-textarea autoGrow=“true” on modal, work only the first time

### ISSUE THREAD

**Issue by IterationCorp** [ionic-team/ionic#18993]
**Expected behaviour:**
Each time the ion-textarea should be the same size.

**Actual behaviour:**
I have a strange behaviour with ion-textarea autoGrow="true" that was introduced in ionic 4.4, the first time the autoGrow is made correctly. The 2nd time the textarea is less than 1 row. We can't even see the text. This bug is only on "modal".

I open the modal like this

 ```
displayModal(data) {
this.modalCtrl.create({
  component: EventDetailModalComponent, componentProps: {
    event: data.appointmentData,
    timeFormat: this.timeFormat,
    dateFormat: this.dateFormat
  }
}).then(modalElement => {
  modalElement.present();
});  }
```
And close like this :

   `onCancel() { this.modalCtrl.dismiss(); }`
View contains :

```
 <ion-item lines="none">
        <ion-label position="floating">{{'DESCRIPTION' | translate }}</ion-label>
        <ion-textarea readonly disabled autoGrow="true" class="ion-text-justify" value="{{ description }}" ></ion-textarea>
 </ion-item>
```
For info, the text is inserted manually by the programme in value="x", not entered by the user.

I'm running the last version of ionic ("@ionic-native/core": "^5.11.0") and Angular (8.2).
Same problem tested on last version of Chrome, Safari and FireFox on Mac.

You can test here : 
https://stackblitz.com/edit/ionic-v4-angular-ion-textarea-autogrowth

This was already reported on "stackoverflow":
https://stackoverflow.com/questions/57336796/ion-textarea-autogrow-true-on-modal-work-only-the-first-time
They came to the conclusion that should be a bug.

**Comment by Domvel** [comment]
Confirmed. Still present in `@ionic/angular: 4.11.1`

**Comment by mden-crf** [comment]
Hello, this issue is still present in `@ionic/angular: 5.0.5`.

**Comment by onsetsoftware** [comment]
For some reason or another, I am only seeing this on `md`, not `ios`.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20971, and a fix will be available in an upcoming release of Ionic Framework.
