### ISSUE TITLE
bug: ion-item-sliding slides entire list of ion-items

### ISSUE THREAD

**Issue by wenindoubt** [ionic-team/ionic#19001]
# Bug Report

**Ionic version:**

[x] **4.6.2**

**Current behavior:**

When sliding an `<ion-item>` within `<ion-item-sliding>`, all of the items slide a bit when I'm only sliding a single element.

**Expected behavior:**

When sliding an `<ion-item>` within `<ion-item-sliding>`, I expect the only element that moves is the one I slide.

**Steps to reproduce:**

**Related code:**

https://stackblitz.com/edit/ionic-v4-angular-tabs-hdltbd

<img src="https://i.imgur.com/G25Np8m.png"/>

**Other information:**

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 5.2.3 (/Users/jeffreywen/.nvm/versions/node/v10.15.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : 1.1.0
   @capacitor/core : 1.1.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3 (/Users/jeffreywen/.nvm/versions/node/v10.15.3/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by manucorporat** [comment]
Please provide a sample code that reproduces the issue

**Comment by manucorporat** [comment]
you are sliding the wrapping ion-slides

**Comment by wenindoubt** [comment]
> The iteams are sliding because they are wrapped around an ion-slides

Thank you very much. Indeed it was because my items were wrapped in slides.
