### ISSUE TITLE
Ionic React Iteration Plan

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#19003]
List of things to be done before @ionic/react final is released 💪 

- [ ] Binding integrated
- [x] Platform use isPlatform()
- [x] Clean up unit tests
- [x] Create test app
- [ ] Automate e2e testing
- [x] One more beta
- [ ] Lifecycle guide for react (wip)
- [ ] Reviews public APIs and add jsdocs
- [x] Move the react folder into then packages folder
   - Before review for open PRs
- [x] Make sure it works in preact
- [ ] Stackblitz links react https://stackblitz.com/edit/ionic-v4-react (edited) 
- [x] Remove attributes being mapped to props 
- [x] Export CSS from ionic/react and update starters to use new imports
- [x] Remove node-sass from starters and remove global.scss
- [x] Remove crypto from generateUniqueId function
- [x] add missing component for ion-infinte
- [x] fix type error where onDidDismiss is required for IonLoading

**Comment by ebk46** [comment]
How about basic support for Edge/IE? Any app using ionic/react is completely inaccessible to those ~8% of users at the moment.

**Comment by brandyscarney** [comment]
Closing this as it was created while we worked to RC and now that we have released RC versions the list has changed. If you find any issues with the RC versions please create new issues, thank you!

Link to Ionic React Release Candidate blog: https://ionicframework.com/blog/announcing-ionic-react-release-candidate/
