### ISSUE TITLE
bug: semicolon was automatically added in ion-card-title

### ISSUE THREAD

**Issue by jonathanli2** [ionic-team/ionic#19035]
Version:
 <script src="https://unpkg.com/@ionic/core@latest/dist/ionic.js"></script>
 <link href="https://unpkg.com/@ionic/core@latest/css/ionic.bundle.css" 

For a very simple html page with ionic library, when loading the html file in chrome on windows box, the text for ion-card-title was automatically changed to have semicolon at the end.

The html is attached below

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Budget Planner</title>
    <script src="https://unpkg.com/@ionic/core@latest/dist/ionic.js"></script>
    <link href="https://unpkg.com/@ionic/core@latest/css/ionic.bundle.css" rel="stylesheet">
</head>
<body>
    <ion-app>
        <ion-header>
            <ion-toolbar color="primary">
                <ion-title>Budget Planner</ion-title>
            </ion-toolbar>
        </ion-header>
        <ion-content>
            <ion-card>
                <ion-card-header>
                <ion-card-title>New Expense</ion-card-title>
                </ion-card-header>
            <ion-card-content>
            <ion-item>
                <ion-label position="floating">Expense Reason</ion-label>
                <ion-input type = "text"></ion-input>
            </ion-item>
            <ion-item>
                    <ion-label position="floating">Expense Reason</ion-label>
                    <ion-input type = "number"></ion-input>
                </ion-item>
            </ion-card-content>
            </ion-card>
        </ion-content>
    </ion-app>
</body>
</html>

**Comment by jonathanli2** [comment]
The ion-card-title shows as "New Expense;" on the browser, instead of "New Expense" as expected.

**Comment by jonathanli2** [comment]
[index.zip](https://github.com/ionic-team/ionic/files/3478318/index.zip)
![Capture](https://user-images.githubusercontent.com/5530532/62646151-a3826c80-b91b-11e9-8cab-14e3340121d7.PNG)

**Comment by jonathanli2** [comment]
html file and screen shot attached.

**Comment by jonathanli2** [comment]
I also tried by changing the ionic library CDN to 
   <script type="module" src="https://unpkg.com/@ionic/core@latest/dist/ionic/ionic.esm.js"></script>
<script nomodule="" src="https://unpkg.com/@ionic/core@latest/dist/ionic/ionic.js"></script>
    <link href="https://unpkg.com/@ionic/core@latest/css/ionic.bundle.css" rel="stylesheet">
But the issue still happens.

**Comment by jonathanli2** [comment]
However, if I change the CDN link to below url, then it works as expected:

<script type="module" src="https://cdn.jsdelivr.net/npm/@ionic/core@4.6.2/dist/ionic/ionic.esm.js"></script>
<script nomodule src="https://cdn.jsdelivr.net/npm/@ionic/core@4.6.2/dist/ionic/ionic.js"></script>
<link href="https://cdn.jsdelivr.net/npm/@ionic/core@4.6.2/css/ionic.bundle.css" rel="stylesheet">

**Comment by angek37** [comment]
I have the same problem in Ionic Angular

**Comment by adaoust** [comment]
Same issue in ion-grid, a semi-colon is added at the end.

**Comment by AVatch** [comment]
<img width="562" alt="Screen Shot 2019-08-07 at 3 16 14 PM" src="https://user-images.githubusercontent.com/1807958/62651179-6a9bc500-b926-11e9-8f1b-3e6a0bee3639.png">

Yup, `ion-grid` has a stray semicolon

**Comment by mmp7700** [comment]
Have the same problem.

**Comment by liamdebeasi** [comment]
Thanks for the issue! Please update to Ionic 4.7.4. This issue was fixed in that release.
