### ISSUE TITLE
bug: @ionic/vue uses page transitions for Android, but not for iOS

### ISSUE THREAD

**Issue by hunterloftis** [ionic-team/ionic#19042]
# Bug Report

**Ionic version:** 4 (`@ionic/vue@0.0.9`)

**Current behavior:** An app using `IonicVueRouter` will correctly follow Android transitions, but will ignore iOS transitions. Navigating in iOS sometimes leaves a "ghost" of the previous page's components as they are kept around for the transition animation that never happens.

**iOS:**
![ionic-vue-ios](https://user-images.githubusercontent.com/364501/62674137-1bc64d80-b96f-11e9-815a-fa633d6d3212.gif)

**Android:**
![ionic-vue-android](https://user-images.githubusercontent.com/364501/62674138-1bc64d80-b96f-11e9-802a-1b75416e051f.gif)

**Expected behavior:** Navigating through the same app in Android and iOS should always include page transitions, regardless of client platform.

**Steps to reproduce:** Run any `@ionic/vue` app in chrome with emulation on. Toggle between iPhone 6/7/8 and Nexus 5X, refreshing between each toggle. Navigate through the pages in the app and observe animations on Android but not on iOS.

**Ionic info:**

```
Ionic:

   Ionic CLI : 5.2.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.4.0
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by hunterloftis** [comment]
Additionally, setting `<html mode="md">` restores transitions on an emulated iOS device (with incorrect window sizing, though).

**Comment by hunterloftis** [comment]
@michaeltintiuc is there anything else I can provide to help triage? I've been trying to debug the issue myself, but I'm not expert at either vue or ionic.

Digging into `node_modules/@ionic/core/dist/esm-es5` I have found that treating everything in `getAnimationBuilder` as `{ mode: 'md' }` at least allows iOS to have some kind of transitions, even though they're Android-like. I haven't been able to narrow down whether the issue is with `iosTransitionAnimation` or the use of it in transitions, though.

**Comment by hunterloftis** [comment]
After digging through tons of examples, I noticed some with `<ion-page class="ion-page">`:

- https://github.com/ionic-team/ionic/blob/master/vue/cookbook/mixed-transitions.html#L50

`ion-page` isn't documented in [the components list](https://ionicframework.com/docs/components) and is only used in a couple of specific cases on the [structure doc](https://ionicframework.com/docs/layout/structure), but it appears to be necessary to achieve iOS transition animations in ionic 4 + vue at the moment. The same isn't true of Android animations.

After wrapping all of my pages in `<ion-page>`, ios transitions have started working, so I'm closing the issue.

**Comment by michaeltintiuc** [comment]
That's a great find, I've never tried without `ion-page`, it's been ages since I wrote those cookbook examples.
