### ISSUE TITLE
bug: Modal panels and other overlays seem to only open once (ios/android)

### ISSUE THREAD

**Issue by RHinderiks** [ionic-team/ionic#19045]
# Bug Report

**Ionic version:**
[x] **4.7.4**

**Current behavior:**
On ios when opening a modal it works fine, closing the modal with modalCtrl.dismiss closes the modal as expected. However after that no other modal panel will open untill the app is restarted. Page navigation still work fine.

On android the same happens when using a actionsheet

**Expected behavior:**
Expected behaviour would be being to open and close a modal and after that open another and repeat

**Steps to reproduce:**
On ios open a modal panel and dismiss it, try to open another
On android open a actionsheet and close it, try to open it again

**Related code:**
```
  async loadRequestDayModal(){
    let requestDayModel = await this.modalController.create({"component":  RequestDayPage, "animated": true});
    requestDayModel.present();
  }
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.802.0
   @angular-devkit/schematics    : 8.2.0
   @angular/cli                  : 8.2.0
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : browser 6.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 22 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.6 (update available: 0.2.8)

System:

   Android SDK Tools : 26.1.1 (/Users/rh/Library/Android/sdk)
   ios-sim           : 8.0.1
   NodeJS            : v12.7.0 (/Users/rh/.nvm/versions/node/v12.7.0/bin/node)
   npm               : 6.10.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by RHinderiks** [comment]
I can't seem to reproduce it in a blank app and its not possible for me to share the source code of my company's app. I could share an old and new package.json if that would help? since these issues started after a update

**Comment by RHinderiks** [comment]
I reverted every change back to my working version, updating only ionic from 4.4.2 to 4.7.4 is enough to cause these issues

**Comment by RHinderiks** [comment]
4.6.0 And below seem to be working fine, anything above seems to cause this issue

**Comment by liamdebeasi** [comment]
If you can provide a simplified reproduction of the bug (without any of your company's proprietary code), that would be the best. Otherwise, it's tricky for us to verify if this is a bug or not.

**Comment by stewwan** [comment]
same here. I think to reproduce you have to use angular and create the sheet dynamically

sheet will show only once. after dismissed, it does never show again. already tried angular change detection or ng.zone with no luck. running on latest ionic

this is how I'm handling it

![Screen Shot 2019-08-13 at 13 17 00](https://user-images.githubusercontent.com/719763/62958383-fac98680-bdcc-11e9-8856-5418b0aa59fa.png)

**Comment by stewwan** [comment]
I'm convinced the problem lives in this file, but have no time to debug stencil or create demos.

https://github.com/ionic-team/ionic/blob/master/core/src/utils/overlays.ts

downgrading to 4.6.0 as mentioned by @RHinderiks

**Comment by stewwan** [comment]
update: just noticed this problem was introduced at `4.7.0`. so `4.6.2` works fine as well

**Comment by KorbinianKuhn** [comment]
Hey, I don't know if it's actually related, but maybe it helps. I had a similar problem, with all kinds of overlays. Everything worked fine, but switching to a mobile view in chrome prevented all overlays after the first one from opening.

Found out, the problem was that I bound the trigger via (tap) in the template. Using (click) solved the it. Event was still fired and the function was executed. I inspected the dom and new overlay nodes were created, but remained invisible.

**Comment by bop10** [comment]
Same problem here

**Comment by liamdebeasi** [comment]
Hi everyone,

If someone could provide a code reproduction of the issue that would be great. Otherwise, we are unable to fix this issue as we cannot reproduce it.

**Comment by stewwan** [comment]
just updated to ionic/angular 4.9.0 and this problem suddenly disappeared.

**Comment by konnectappdev** [comment]
I still have the same issues in 4.9.0

**Comment by konnectappdev** [comment]
> Hey, I don't know if it's actually related, but maybe it helps. I had a similar problem, with all kinds of overlays. Everything worked fine, but switching to a mobile view in chrome prevented all overlays after the first one from opening.
> 
> Found out, the problem was that I bound the trigger via (tap) in the template. Using (click) solved it. Event was still fired and the function was executed. I inspected the dom and new overlay nodes were created, but remained invisible.

This indeed does the trick however we use tap for a reason so

**Comment by DavidWiesner** [comment]
> Hey, I don't know if it's actually related, but maybe it helps. I had a similar problem, with all kinds of overlays. Everything worked fine, but switching to a mobile view in chrome prevented all overlays after the first one from opening.
> 
> Found out, the problem was that I bound the trigger via (tap) in the template. Using (click) solved it. Event was still fired and the function was executed. I inspected the dom and new overlay nodes were created, but remained invisible.

It will only fail if you are in an ios mode (e.g.: chrome dev console in iPad mobile view). 
Seems to work if you will use set `mode: 'md'` or disable the animation via `animated: false` in the `ModalOptions`.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
