### ISSUE TITLE
bug: Angular CDK Drag & Drop doesn't work with latest Ionic 4 (Angular Core 8.2.0)

### ISSUE THREAD

**Issue by paulalbertdev** [ionic-team/ionic#19058]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Angular CDK Drag & Drop doesn't work with latest Ionic 4 (Angular Core 8.2.0)

**Expected behavior:**
Drag & Drop should work

**Steps to reproduce:**
Try it out by yourself here : 
https://stackblitz.com/edit/ionic-v4-njjncn?file=src%2Fapp%2Fpages%2Faction-sheet%2Faction-sheet.component.html

**Comment by paulstelzer** [comment]
Thanks for your issue! CDK Drag and Drop is working. You only have to add "DragDropModule" to your module. See the following gif:

![2019-08-10_09-03-36](https://user-images.githubusercontent.com/20501666/62818875-c6946280-bb4d-11e9-95ca-327f0b18f7ee.gif)

**Comment by paulalbertdev** [comment]
Oh, my bad, thanks, sorry for the disturbance
