### ISSUE TITLE
bug: Don't send email to me please!Don't send email to me please!Don't send email to me please! 

### ISSUE THREAD

**Issue by dntzhang** [ionic-team/ionic#19056]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Please don't write up issues here that have nothing to do with either bug in or feature requests for the Ionic Framework

If you are talking Ionic marking or studio or whatever e-mails, try the unsubscribe link at the bottom of the e-mail.

If you are talking GitHub notifications, make sure you are not following and/or watching things and you won't get e-mails.
