### ISSUE TITLE
bug: ion-icon are 404 in Ionic Framework CDN

### ISSUE THREAD

**Issue by HonamiHoshino** [ionic-team/ionic#19053]
**Ionic version:**
Ionic Framework CDN

`    <script src="https://unpkg.com/@ionic/core@latest/dist/ionic.js"></script>
    <link href="https://unpkg.com/@ionic/core@latest/css/ionic.bundle.css" rel="stylesheet">
`

**Current behavior:**
Ionicons are 404, Not Found. (probably all the icons)
`https://unpkg.com/@ionic/core@4.7.4/dist/svg/...`

**Sample code:**
` <ion-button>
<ion-icon slot="start" name="add"></ion-icon>Add
</ion-button>
`

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide steps to reproduce? Ionicons are working fine for me when using Ionic 4.7.4 via CDN: https://codepen.io/liamdebeasi/pen/MNqprw.

**Comment by BarneyG77** [comment]
I have the same error

**Comment by gdheller42** [comment]
Exactly the same error. If I use core@4.6.2 it works fine
<script src="https://unpkg.com/@ionic/core@4.6.2/dist/ionic.js"></script>
<link href="https://unpkg.com/@ionic/core@latest/css/ionic.bundle.css" rel="stylesheet">

thanks

**Comment by gdheller42** [comment]
Exact same error with same script and link in header as @HonamiHoshino 
if I user core@4.6.2 instead of core@latest it works fine.

-Thanks

**Comment by HonamiHoshino** [comment]
Sorry for this late replay. Here's a sample HTML.
`<!DOCTYPE html>`
`<html lang="en">`
`<head>`
`    <meta charset="UTF-8">`
`    <meta name="viewport" content="width=device-width, initial-scale=1.0">`
`    <meta http-equiv="X-UA-Compatible" content="ie=edge">`
`    <title>Sample</title>`
`    <script src="https://unpkg.com/@ionic/core@latest/dist/ionic.js"></script>`
`    <link href="https://unpkg.com/@ionic/core@latest/css/ionic.bundle.css" rel="stylesheet">`
`</head>`
`<body>`
`    <ion-app>`
`        <ion-content>`
`            <ion-button>`
`                <ion-icon slot="start" name="close"></ion-icon>Cancel`
`            </ion-button>`
`            <ion-button>`
`                <ion-icon slot="start" name="add"></ion-icon>Add`
`                </ion-button>`
`            </ion-content>`
`    </ion-app>`
`</body>`
`</html>`

@gdheller42 
Thanks! It works!

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm not able to reproduce this using the code provided & latest `4.11.9` at the time of this writing. If this is still an issue please let us know. Thanks!
