### ISSUE TITLE
bug: Footer toolbar shouldn't use --ion-safe-area-bottom when tabs are below

### ISSUE THREAD

**Issue by ndhbr** [ionic-team/ionic#19060]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

iPhone X/Xs....:
The footer inside of a toolbar has following line CSS:
`padding-bottom: var(--ion-safe-area-bottom,0);`
Sadly this padding is applied even there is a tab-bar under footer. In my example the calculated padding-bottom equals 34px.

Example image:
![Bildschirmfoto 2019-08-09 um 15 01 26](https://user-images.githubusercontent.com/13482230/62781657-be3e1800-bab8-11e9-8503-e2e35cee562b.png)

**Expected behavior:**
If there is a tab-bar under the footer, the padding-bottom should only be applied on the tab-bar.

**Steps to reproduce:**
Take any Ionic tab-bottom-project. Insert a footer with a toolbar inside and execute this on e.g. IPhone Xs.

**Other information:**
I found a related thread about this topic for an older version of Ionic: https://github.com/ionic-team/ionic/issues/13615

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.1

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   NodeJS : v12.6.0 (/usr/local/Cellar/node/12.6.0/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by biesbjerg** [comment]
There’s already a ticket for it here (and a hack to work around it): https://github.com/ionic-team/ionic/issues/17560

**Comment by ndhbr** [comment]
Okay thanks. I will close this issue.
