### ISSUE TITLE
bug: [react] IonLoading does not dismiss on Android

### ISSUE THREAD

**Issue by jesobreira** [ionic-team/ionic#19064]
# Bug Report

**Ionic version:**  (React)

[x] **5.2.4**

**Current behavior:**

An `<IonLoading isOpen={true} />` that gets its `isOpen` attribute switched to `false` dismisses correctly on the browser (Google Chrome) as well as in iOS (tested with Ionic DevApp) but does not dismiss (still visible) on Android with Ionic DevApp. Strangely, it works well on Android when using Samsung Browser or Google Chrome for Android.

**Expected behavior:**

The loading animation should dismiss on Android's Ionic DevApp, just as it does on iOS.

**Steps to reproduce:**

Run the code below in two different phones: an Android phone and an iOS phone.

Notice that, on the iOS phone, the loading animation closes after 100ms seconds, while in Android, it never disappears.

**Related code:**
```
import React, { Component } from 'react'
import { IonLoading } from '@ionic/react'

class Home extends Component {
  state = {
    show: true
  }

  componentDidMount = () => {
    setTimeout(() => this.setState({ show: false }), 100)
  }

  render = () => (
    <IonLoading isOpen={this.state.show} />
  )

  // this does not work in any of the environments
  // however I'm not sure whether this is really supposed to work or not
  alternative_render = () => (
    <>
    { this.state.show && <IonLoading isOpen={true} /> }
    </>
  )

  // this also does not work
  // because this.loadingElement.dismiss() is undefined
  alternative2_render = () => (
    <IonLoading isOpen={true} ref={el => this.loadingElement = el} />
  )
}

export default Home
```

**Comment by topcatcreatives** [comment]
Im experiencing something similar in the chrome browser intermittently when isOpen prop is set to true to quickly. It sometimes stays open (hangs) even though the boolean has switched back to false. Feels like some kind of timing issue.

**Comment by jesobreira** [comment]
Strangely, delaying a few hundreds ms before dismissing it works:

```
setTimeout(() => this.setState({ show: false }), 300)
```

This indeed looks like a timing issue, @topcatcreatives .

Another thing I found weird is that, while you can use React callback references to call component methods, you can't do this with IonLoading.

For example, if you have a IonItemSliding and wants to call its .closeOpened() method, you can do:

```
<IonItemSliding ref={el => this.example = el} />
```
```
this.example.closeOpened()
console.log(this.example) // <ion-item-sliding... a DOM node
```

But you can't do the same with IonLoading:

```
<IonLoading ref={el => this.example = el} />
```
```
this.example.dismiss() // is not a function
console.log(this.example) // class { props, state ... } a JS object
```

**Comment by elylucas** [comment]
Closing this issue as its old on a beta version of Ionic/React. If the problem still persists on the latest version, please create a new issue and link this one for reference.
