### ISSUE TITLE
bug: fab button partly hidden below screen edge

### ISSUE THREAD

**Issue by peanussbutter** [ionic-team/ionic#19068]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

The floating action button is mostly hidden below the screen edge.

![image](https://user-images.githubusercontent.com/53979493/62826657-60e0be80-bbbf-11e9-95e8-4aa9ad32e0e7.png)

**Expected behavior:**

"Normal" floating action button.

![image](https://user-images.githubusercontent.com/53979493/62826660-69d19000-bbbf-11e9-96ac-2a8100e2b41d.png)

**Steps to reproduce:**

In a react app, add a floating action button and set the vertical alignment to "bottom".

**Related code:**

[StackBlitz](https://stackblitz.com/edit/ionic-v4-react-wbivf1)

**Other information:**

I've been following the tutorial about building an app with React [here](https://ionicframework.com/docs/react/your-first-app).

**Ionic info:**

```

Ionic:

   Ionic CLI       : 5.2.3
   Ionic Framework : @ionic/react 0.0.10

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 

System:

   NodeJS : v11.15.0 (/usr/bin/node)
   npm    : 6.10.2
   OS     : Linux 5.2
```

**Comment by phpanos** [comment]
Facing the same issue following the ionic react documentation.

**Comment by elylucas** [comment]
Hello,

If you surround the content with a <IonApp> or an <IonPage> it fixes the display issue with the fab. I updated the stackblitz example to show it here: https://stackblitz.com/edit/ionic-v4-react-gjfqzk.

Going to close this issue, but if something else pops up let us know.

**Comment by Kimeiga** [comment]
You mean surround the `<IonHeader>` and `<IonContent>` with a `<IonPage>` right? That fixed it for me

**Comment by aviyadeveloper** [comment]
@elylucas How can this Issue be closed when the actual documentation tutorial will lead every single user following it to reproduce the exact same error. We need to fix the tutorial with your solution before closing the issue.

**Comment by aviyadeveloper** [comment]
I updated the corrections to the tutorial and made a pull request:
https://github.com/ionic-team/ionic-docs/pull/934
