### ISSUE TITLE
bug: Google Play Games Services is broken 

### ISSUE THREAD

**Issue by doug1e** [ionic-team/ionic#19061]
# Bug Report

**Ionic version:**

[x] **4.6.2**

**Current behavior:**

**Expected behavior:**

Ionic build throws the following error:

Task :app:compileReleaseJavaWithJavac FAILED /home/AndroidProject/platforms/android/app/src/main/java/com/berriart/cordova/plugins/BaseGameActivity.java:21: error: cannot find symbol import android.support.v4.app.FragmentActivity;

**Steps to reproduce:**

1) Create a blank project by: ionic start AndroidProject blank --cordova
2) Install the google-play-games-services by:
    ionic cordova plugin add cordova-plugin-play-games-services --variable APP_ID=“XXXX”
    npm install @ionic-native/google-play-games-services
3) ionic cordova build android --release --prod

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.4 (/home/dx/.npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 5 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/home/dx/Android/Sdk)
   NodeJS            : v12.6.0 (/usr/bin/node)
   npm               : 6.10.3
   OS                : Linux 4.18

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. `@ionic-native/google-play-games-services` is a wrapper around the `cordova-plugin-play-games-services` plugin. We do not manage the `cordova-plugin-play-games-services` plugin itself.

I recommend you contact the plugin author for this issue: https://github.com/artberri/cordova-plugin-play-games-services

Thanks!
