### ISSUE TITLE
bug: ionInfinite event only fires once

### ISSUE THREAD

**Issue by kyleabens** [ionic-team/ionic#19077]
# Bug Report

**Ionic version:**

[x] **4.7.4**

**Current behavior:**

The ionInfinite event on the ion-infinite-scroll component only fires the first time and fails to emit anything after that.

**Expected behavior:**

The ionInfinite event should fire every time.

**Steps to reproduce:**

Create an app with the ion-infinite-scroll component at the end of a list long enough to fire ionInfinite twice. Console.log the $event emitted from ionInfinite and you'll notice it only fires once.

**Related code:**
```
<ion-infinite-scroll threshold="50px" (ionInfinite)="nextBatch()">
    <ion-infinite-scroll-content
      loadingSpinner="crescent">
    </ion-infinite-scroll-content>
  </ion-infinite-scroll>
```

**Other information:**

This began when I upgraded to Ionic 4.7.4 and Angular 8.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.802.1
   @angular-devkit/schematics    : 8.2.1
   @angular/cli                  : 8.2.1
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.15.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8
```

**Comment by paulstelzer** [comment]
Thanks for your issue! I am using infinite scroll too (with ionic 4.7.4 and angular 8) and it's working without problem. Could you please create an example in stackblitz (you can use this template https://stackblitz.com/edit/ionic-v4-angular-tabs) or  send a repo so we can check it?

**Comment by kyleabens** [comment]
@paulstelzer I noticed that another one of my components which uses infinite scroll is working so this is clearly an issue on my end.  I'll keep digging into this and see what's going on.
