### ISSUE TITLE
bug: SSR doesn't work

### ISSUE THREAD

**Issue by JustasKuizinas** [ionic-team/ionic#19073]
# Bug Report

**Ionic version:**
[x] 4.7.4

**Current behavior:**
SSR doesn't work with ionic, error `const win = window; `

**Expected behavior:**
Ionic should work with SSR

**Steps to reproduce:**
1. Install blank ionic template
2. Add angular SSR https://angular.io/guide/universal
3. npm run build:ssr && npm run serve:ssr

**Other information:**
**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.4 (C:\Users\Justas\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.10.3
   OS     : Windows 10
```

**Comment by mhartington** [comment]
Merging with #15041
