### ISSUE TITLE
bug: Native: tried calling SplashScreen.hide, but the SplashScreen plugin is not installed.

### ISSUE THREAD

**Issue by justwezzz** [ionic-team/ionic#19079]
**Ionic version:**
5.2.4

**Current behavior:**
when i call this.splashScreen.hide(); in AppComponent，android studio prompt
“Native: tried calling SplashScreen.hide, but the SplashScreen plugin is not installed.”
"Install the SplashScreen plugin: 'ionic cordova plugin add cordova-plugin-splashscreen'"

then i install  cordova-plugin-splashscreen but still the same waring

**Expected behavior:**
 this.splashScreen.hide();  work

**Steps to reproduce:**

1. ionic start myApp tabs --capacitor
2. ionic cordova plugin add cordova-plugin-splashscreen
3. npx cap init [appName] [appId]
4. ionic build
5. npx cap add android
6. npx cap open android
7. run

**Comment by dwasyluk** [comment]
Same issue here....

**Comment by bongartzc** [comment]
I am having the same problem. Any news or solutions on this?

**Comment by justwezzz** [comment]
any body to process the issue?

**Comment by kensodemann** [comment]
Based on your step to repro, you are using Capacitor and not Cordova. The starter there isn't fully baked and requires some mods.

Status bar and Splash Screen are both listed as incompatible plugins, so you should not use them: https://capacitor.ionicframework.com/docs/cordova/known-incompatible-plugins

Instead, you should use the APIs:
https://capacitor.ionicframework.com/docs/apis/splash-screen
https://capacitor.ionicframework.com/docs/apis/status-bar

Here is an example using actual code:
https://github.com/ionic-team/iv-training-starter/blob/master/src/app/app.component.ts

You should uninstall:
1. the Cordova plugins for Splash Screen and Status Bar
1. the Cordova plugins for basically anything else that has a Capacitor API to use instead
1. any Cordova plugins you may be using that are in the incompatible list shared above
1. any @ionic-native wrapper associated with Cordova plugins that were removed
