### ISSUE TITLE
feat: add ability to change label on accessory bar

### ISSUE THREAD

**Issue by Livijn** [ionic-team/ionic#19075]
# Feature Request

**Ionic version:**

[x] **4**

**Describe the Feature Request**
Right now, when displaying the accessory bar `Keyboard.setAccessoryBarVisible({isVisible: false});` you cannot change the "Done" label. 

This is an accessory bar:
![](https://www.oreilly.com/library/view/the-core-ios/9780133510119/graphics/06fig03.jpg)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This feature would be managed by the Keyboard Plugin, so I recommend you add this feature request on the Keyboard Plugin repo: https://github.com/ionic-team/cordova-plugin-ionic-keyboard.

I am going to close this as this is not something that would be managed by Ionic Framework. Thanks!
