### ISSUE TITLE
feat: Close keyboard on PWA

### ISSUE THREAD

**Issue by lucianojs** [ionic-team/ionic#19098]
# Feature Request

**Ionic version:**
[x] **4.7.1**

**Describe the Feature Request**
Allow hide the virtual keyboard on mobile devices when focus on ion-input and click on Enter using the project as website/PWA.
When I run via cordova works with keyboard.hide()
`<ion-input formControlName="test" (keyup.enter)="keyboard.hide()"></ion-input>`

**Describe Preferred Solution**
Allow to define blur on ion-input
`<ion-input #test formControlName="test" (keyup.enter)="test.blur()"></ion-input>`

**Describe Alternatives**
Other possibility is add setFocus() on ion-button.

**Comment by rafalschmidt97** [comment]
It's a native functionality. Correct me if I'm wrong but the only way to show/hide keyboard on your "website" is to work with javascript input .focus() method. So you can't just show keyboard in your browser without focusing input. It means that your feature might be impossible to implement.

**Comment by lucianojs** [comment]
I need hide, not show keyboard.

HTML input works. I need same behavior on ion-input.

**Comment by rafalschmidt97** [comment]
@lucianojs - maybe focusing div/container instead of input will hide device keyboard?

**Comment by lucianojs** [comment]
@rafalschmidt97 - It probably works, but it is not very clear what the real intention is when another developer reads the code.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. There is no Web API currently available that lets us directly close the keyboard. The closest thing we can do is programmatically blur an input.

To do this you will need to access the native element:

```html
<ion-input #input (keyup.enter)="blurInput(input)"></ion-input>
```

```typescript
import { IonInput } from '@ionic/angular';

...

async blurInput(input: IonInput) {
  const nativeEl = await input.getInputElement();
  nativeEl.blur();
}
```

Some platforms such as iOS place restrictions on programmatically focusing/blurring inputs. Beyond blurring the input, there is not much we can do right now without the help of the native Keyboard plugin in Cordova/Capacitor apps. Thanks!
