### ISSUE TITLE
bug: white flash on overlay (iOS)

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#19102]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
This is an issue for iOS specifically. If you have a dark background image set, whenever an overlay is added by the framework to darken the `ion-content`, there is an annoying white flash. Because the app is dark, this is extremely apparent. 

**Expected behavior:**
There should be no white flash.

**Steps to reproduce:**
On iOS.

1) Add the following image to assets. 
![back_background](https://user-images.githubusercontent.com/2852839/63033657-49078400-beb8-11e9-9139-ffd70485c8d3.jpg)

2) Use the following scss on a page:
```
ion-content {
  --background: linear-gradient( rgba(0, 0, 0, 0.45), rgba(0, 0, 0, 0.45) ), url('../../../assets/images/back_background.jpg') no-repeat center center / cover;
}
```

This should set the image to fill the entire content.

3) Open a side menu or display a popup. Anything that will add a darker overlay on top of the `ion-content`. You will notice the white flash.

See an example video here:
![ezgif com-optimize](https://user-images.githubusercontent.com/2852839/63034580-deefde80-beb9-11e9-98cd-069cd6bd69f1.gif)

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 18 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.0
   NodeJS     : v10.15.3 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2 Build version 10E125

```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This is a known bug in WebKit, unfortunately. Please see https://github.com/ionic-team/ionic/issues/17494#issuecomment-492647992 for a workaround.

I am going to close this as this is not an Ionic issue. Thanks!
