### ISSUE TITLE
bug: no view animations when migrating to react 4.8.0-rc.0

### ISSUE THREAD

**Issue by mattrosno** [ionic-team/ionic#19110]
# Bug Report

**Ionic version:**

[x] **4.8.0-rc.0**

**Current behavior:**

Here's a Stackblitz that has the React release candidate and there are no view transitions when you click the login button: https://stackblitz.com/edit/ionic-react-480-rc0

**Expected behavior:**

Same Stackblitz but using `@ionic/react` 0.0.6: https://stackblitz.com/edit/ionic-react-006

I expect there to be view transitions when you click the login button. Did I miss something during the migration or is there a bug? Thanks!

**Comment by elylucas** [comment]
@mattrosno,

There is a new ViewManager component from ionic/react-router that is required for the page transitions to work outside of tabs. It hasn't been documented well yet so sorry this change wasn't relayed in your upgrade. I updated your stackblitz example with the RC to show how to use it:

https://stackblitz.com/edit/ionic-react-480-rc0

Thanks!

**Comment by mattrosno** [comment]
Thanks! I noticed the new component but makes sense that I didn't see it in the tabs example as I was looking to how that view transition was working.

P.S. did you mean to share a different Stackblitz URL that's using ViewManager?

**Comment by elylucas** [comment]
That I did, heres the correct one: https://stackblitz.com/edit/ionic-react-480-rc0-vvnday
