### ISSUE TITLE
bug: What is the problem?? Send email to me all the time !

### ISSUE THREAD

**Issue by dntzhang** [ionic-team/ionic#19129]
dnt,

You might be facing similar challenges to other tech-leaders I work with:

Modernizing legacy apps at the highest quality / lowest cost
Doing more with less; repurposing current resources for “digital transformation” efforts
Marginalizing risk by ensuring today’s decisions will meet tomorrow’s challenges

If so, you are not alone.

Panera, Amtrak, USAA, and many others are working with Ionic to leverage the power of the web to solve the above challenges and more while saving time, resources, and budget.

Do you have 15 minutes Tuesday or Wednesday morning to learn more?

Thanks,
Melissa

Melissa Raddatz
Sales Development Leader/App Strategist
Melissa@ionic.io
608-313-7265
Connect on LinkedIn

# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by pppp0836** [comment]
广告？

**Comment by dntzhang** [comment]
@pppp0836  不是，ionic team 天天跟我发邮件，我贴的是他们发我的邮件。我已经说过好多次不要跟我发邮件了，他们销售团队根本就不看我回复的邮件。

**Comment by DazChong** [comment]
開個過濾把它直接進垃圾桶吧

**Comment by dntzhang** [comment]
嗯，我公司邮件每封都看的。几个月来老是夹杂着这种邮件让人郁闷。

**Comment by DazChong** [comment]
已厭倦類似ionic官網的各種营销字眼.

另談: 這幾年都在維護當初的ionic 1 apps, hack 這hack那.毫無價值毫無成就感可言. 
已把專注力移去Swift & Flutter.
不想再浪費時間在這無價值的過期工具.

**Comment by dntzhang** [comment]
我没有用过 ionic，所以对 ionic 本身不评论。但是 ionic 的销售真的很烦。

**Comment by dotNetkow** [comment]
你好。对太多电子邮件道歉。请点击电子邮件底部的“取消订阅”以选择停用。我们将检查是否存在问题。谢谢。
