### ISSUE TITLE
bug: Calling ion-reorder-group's complete with false doesn't reset ion-reorder's position

### ISSUE THREAD

**Issue by MarkSill** [ionic-team/ionic#19128]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Passing false to ion-reorder-group's complete doesn't reset the position of the dragged ion-reorder component.

**Expected behavior:**
Passing false to ion-reorder-group's complete should reset the position of the dragged ion-reorder component to its pre-dragged state.

**Steps to reproduce:**
StackBlitz: https://stackblitz.com/edit/ionic-v4-angular-tabs-nudxur
```ts
event.detail.complete(false); // should reset the reorder component's position
```

**Other Information:**
Looks like this broke in bd96491d03c98c9ac422baf9bdf52850c4cfd7b2 ([see this line](https://github.com/ionic-team/ionic/commit/bd96491d03c98c9ac422baf9bdf52850c4cfd7b2#diff-55788926a15bf640a67304db064ca3fdR231)).

Could presumably be fixed by changing
```ts
if (toIndex !== fromIndex && (!listOrReorder || listOrReorder === true)) {
```
to
```ts
if (toIndex !== fromIndex && (listOrReorder === undefined || listOrReorder === true)) {
```
or similar.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/home/marksill/Android/Sdk)
   NodeJS            : v10.15.2 (/usr/bin/node)
   npm               : 6.10.3
   OS                : Linux 5.0
```

**Comment by Yogatopia** [comment]
This worked for me:
`event.detail.complete({ listOrReorder: false });`

**Comment by MarkSill** [comment]
Looks like the documentation needs to be updated.

**Comment by vadim-shb** [comment]
> Looks like the documentation needs to be updated.

I believe it's still a bug.
@Yogatopia provided nice workaround, but we can use any nonempty object to get the same effect.
`event.detail.complete({ any: "thing" });`
works for me as well, which doesn't seem a proper API.

**Comment by MarkSill** [comment]
> > Looks like the documentation needs to be updated.
> 
> I believe it's still a bug and your first fix suggestion is correct.
> @Yogatopia provided nice workaround, but we can use any nonempty object to get the same effect.
> `event.detail.complete({ any: "thing" });`
> works for me as well, which doesn't seem a proper API.

Yeah, that definitely doesn't look like intended behavior.
