### ISSUE TITLE
bug: Ionic popover has wrong vertical position (without click) after updates

### ISSUE THREAD

**Issue by choenden** [ionic-team/ionic#19123]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

The popover is vertically off screen, because it has the wrong top position.

**Expected behavior:**

The popover should be centered vertically

**Steps to reproduce:**

I create a popover

This popover has wrong value for 'top' on popover-content.

If I resize the screen, then the top value is sometimes calculated correctly.

The popover contains a different component, and that component contains a ion-list (not virtual) which is populated through an observable (async).

**Related code:**

```
const popover = await this.popoverCtrl.create({
      component: SelectAccountComponent,
      componentProps: {},
      cssClass: 'medium-popover'
    });

await popover.present();

```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.4 (C:\Users\stck\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.1.2
   @angular/cli                  : 8.1.2
   @ionic/angular-toolkit        : 2.0.0```

**Comment by choenden** [comment]
This override worked for me:
https://github.com/ionic-team/ionic/issues/15036

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you passing in `event` to the creation method? That is required for the popover to be positioned properly.

See the docs here: https://ionicframework.com/docs/api/popover#usage
