### ISSUE TITLE
bug: When using ion-nav-push the animation lags on iOS devices only!

### ISSUE THREAD

**Issue by Bandito11** [ionic-team/ionic#19125]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When using ion-nav-push the animation lags on iOS devices only!
This was used using StencilJS App framework.
**Expected behavior:**

 No lag when navigating.
**Steps to reproduce:**

In a StencilJS app start the app and then navigate to the button, press it and thus the lag.

https://github.com/Bandito11/Millefollium
**Related code:**

```
const ionNav = document.querySelector('ion-nav');
ionNav.push('app-food-list');
npm start 
```

**Other information:**

No error messages
**Ionic info:**

```
Ionic:

   Ionic CLI : 5.2.4

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.6.0
   npm    : 6.10.3
   OS     : macOS Mojave
```

**Comment by Bandito11** [comment]
I ran ionic info but I don't see how this helps.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework?

**Comment by Bandito11** [comment]
It is not an issue anymore
