### ISSUE TITLE
bug: Modal frame is not dismissed if IonModal is not present on the page anymore

### ISSUE THREAD

**Issue by leechy** [ionic-team/ionic#19135]
# Bug Report

**Ionic version:**
[x] **0.0.7**
[x] **4.8.0-rc.0**

**Current behavior:**
The modal frame element (`<ion-modal>` in the root of the app) is not dismissed if the `IonModal` react component is not present in the component tree anymore due to navigation or just rerender.

**Expected behavior:**
If by some reason, the `IonModal` component is not rendered anymore, the frame becomes hidden or removed from the DOM.

**Steps to reproduce:**
Easier to show with the navigation on the demo Conference app.

1. Start from a page without modals, let's say the Login page:
https://ionic-react-conference-app.firebaseapp.com/login

2. Navigate to the Schedule page.

3. Press the settings button in the top-right corner.
The modal will be available to the user.

4. Press the Back button in the browser.
The empty frame still stays on top of the application.

The issue is critical for the users on mobile devices (no backdrop available to click, just a blank screen) or if `backdropDismiss` is set to false.

**Related code:**
None. It can be seen in the demo app.

**Other information:**
Can be similar to `@ionic/angular` bug #16946 since the same behavior can be noticed with other overlay components.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.2.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.8.0-rc.0

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (/usr/local/bin/node)
   npm    : 6.9.0
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
