### ISSUE TITLE
bug: Ion-content does not take footer into height calculation

### ISSUE THREAD

**Issue by SatoAV** [ionic-team/ionic#19146]
# Bug Report

**Ionic version:**
[x] **4.7.4**
**Ionic React version:**
[x] **4.8.0-rc.0**

**Current behavior:**
After updating to latest version of @ionic/core and @ionic/react, `IonFooter` on all of my pages got pushed down by `IonContent`, which doesn't account for footer below it.
The issue is present on both iOS and MD styles, desktop and mobile.

Adding `display: flex; flex-direction: column` to `<IonRouterOutlet>` component fixes this.

On the left: current behavior. On the right: expected behavior.
![bug](https://user-images.githubusercontent.com/1641218/63431668-07cb2300-c428-11e9-99d0-7bdce5919986.jpg)

**Expected behavior:**
`IonContent` should accompany both `IonHeader` and `IonFooter` when calculating its height.

**Steps to reproduce:**
Start a new Ionic React app with `sidemenu` template.
Add the footer after `IonContent` in `scr/pages/Home.tsx`

```
<IonFooter>
    <IonToolbar>
        <IonTitle>Footer</IonTitle>
    </IonToolbar>
</IonFooter>
```

**Additional information**
This is probably a duplicate of https://github.com/ionic-team/ionic/issues/15799
But this issue wasn't present on previous versions of @ionic/react (0.0.7)

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.2.3 (C:\Users\sato\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework : @ionic/react 4.8.0-rc.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by SatoAV** [comment]
Issue seems to be fixed in the `4.8.0-rc.1` release.

**Comment by elylucas** [comment]
Thanks! Let us know if anything else pops up.

**Comment by aagavin** [comment]
I'm seeing something similar where the bottom is cut off also.

**Comment by aagavin** [comment]
![Screenshot_2019-08-30 Movie Star](https://user-images.githubusercontent.com/1504170/63990127-5df83000-cad2-11e9-9c0b-5253ef1c8eb5.png)
