### ISSUE TITLE
bug: card wrong background when switching between pages

### ISSUE THREAD

**Issue by shadoWalker89** [ionic-team/ionic#19140]
# Bug Report

**Ionic version:**

[x] **4.7.4**
[x] **4.9.0**

**Current behavior:**
When i first open the app the card has the correct background color and the svg image is visible.
When i go to the list page and go back to the home page, the card has wrong background and the svg is not displayed. (check out the video)
After going back to the home page, if open and close the menu 3 times the card and the svg are displayed correctly.

https://www.youtube.com/watch?v=Z_qQeipYGw4

Edit: I also tried the conference starter and this is a video with the problem
https://www.youtube.com/watch?v=Ek4U888kKR4
The problem appears in the speakers tab where we have cards.
Also going back to the schedule tab, the fab button has bad background as well.

**Expected behavior:**
Background should not be affected when moving between pages.

**Steps to reproduce:**
Just using the sidemenu starter template with no changes at all.
Tried that with capacitor and cordova, and the i got the same problem.
`ionic start myApp sidemenu --capacitor`
`ionic build`
`ionic capacitor add android`
`ionic capacitor copy android`
`ionic capacitor open android`
Run the application from android studio
**Related code:**
The sidemenu starter template with no changes at all

```
insert short code snippets here
```

**Other information:**

Physical android phone : `huawei y5 2017 mya-l22`
Android version : `6.0`

I want to mention that i tried running the app on another device like mine and the problem exists so this is not related to my device only.
But i tried running the same app on two other samsung devices, infinix device (android 8.0), lenovo (android 5.0.2) and i didn't get this problem.
This appeared only on two huawei devices of the same model.

**Ionic info:**

```
Ionic:
  Ionic CLI                     : 5.2.5 (C:\Users\Melek\AppData\Roaming\npm\node_modules\ionic)
  Ionic Framework               : @ionic/angular 4.7.4
  @angular-devkit/build-angular : 0.801.3
  @angular-devkit/schematics    : 8.1.3
  @angular/cli                  : 8.1.3
  @ionic/angular-toolkit        : 2.0.0
Capacitor:
  Capacitor CLI   : 1.1.1
  @capacitor/core : 1.1.1
Utility:
  cordova-res : not installed
  native-run  : 0.2.8
System:
  NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
  npm    : 6.10.3
  OS     : Windows 10
```

**Comment by shadoWalker89** [comment]
ping @liamdebeasi

**Comment by liamdebeasi** [comment]
Thanks for the issue. When running the Capacitor app, what is the user agent provided by the webview? You can find this by logging `navigator.userAgent` in Chrome Dev Tools when inspecting the app on the device.

**Comment by shadoWalker89** [comment]
Thanks for your reply @liamdebeasi 
My user agent is `Mozilla/5.0 (Linux; Android 6.0; MYA-L22 Build/HUAWEIMYA-L22; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/76.0.3809.132 Mobile Safari/537.36`
Same issue exists when running with cordova as well

This is also a screenshot of the `navigator` object

![image](https://user-images.githubusercontent.com/1449151/64946870-1b757800-d874-11e9-9060-5dede9d3841d.png)

Sorry for the delay to reply, as i was very sick.

**Comment by blinkuz** [comment]
I have the same problem in a device with android 6, the model of the device is a JICAI Q2, previously everything worked fine but for a few weeks the cards lost all the style when opening the sidemenu.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.

**Comment by shadoWalker89** [comment]
I confirm that wih @ionic/angular 5.2.3 the problem is fixed.
