### ISSUE TITLE
bug: [Ionic React] Page transition animation missing after update to `4.8.0-rc.0`

### ISSUE THREAD

**Issue by SatoAV** [ionic-team/ionic#19147]
# Bug Report

**Ionic React version:**
[x] **4.8.0-rc.0**

**Current behavior:**
After updating `@ionic/react` to latest version, all page transition animations are missing, and pages change instantly with a noticeable flicker.
The issues also occurs when creating a fresh app with `sidemenu` template.
Changing `animated` prop on `IonRouterOutlet` or setting it with `setupConfig()` doesn't change anything.

**Expected behavior:**
Page transitions should be animated as in previous versions.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.2.3 (C:\Users\sato\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework : @ionic/react 4.8.0-rc.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by elylucas** [comment]
Hi @SatoAV,

If you are using views outside of tabs, try wrapping your IonRouterOutlet with a n<ViewManager> imported from @ionic/react-router. This isn't documented well yet but we will get that updated. 

I don't believe the sidemenu has any page transitions in the starters though. The pages are supposed to appear instantly when you switch between them from the side menu.

**Comment by SatoAV** [comment]
@elylucas,

I'm indeed using views outside of tabs.
I used `sidemenu` to start my current project, and it had page transition from the start.

There's no `IonRouterOutlet` exported from `@ionic/react-router` though.

**Comment by elylucas** [comment]
@SatoAV 

Sorry, looks like my last post got messed up somehow. Wrap your IonRouterOutlet with a ViewManager (which is imported from @ionic/react-router).

**Comment by SatoAV** [comment]
@elylucas, wrapping it like so doesn't change anything:
```
<ViewWrapper>
  <IonRouterOutlet />
</ViewWrapper>
```

Am I doing something wrong?

**Comment by SatoAV** [comment]
@elylucas, that solved the problem, thanks a lot!

Is there any kind of changelog for @ionic/react ? 
The only bits of information about recent updates I got were from Ionic Show on YouTube =\

**Comment by elylucas** [comment]
@SatoAV,

I started one in the /packages/react folder. When Ionic React goes final, the changelog will be a part of the main Ionic Repo changelog.

**Comment by aaronksaunders** [comment]
I am still seeing this error... and the stackblitz example you referenced @elylucas https://stackblitz.com/edit/ionic-react-480-rc0-vvnday

doesn't work.
