### ISSUE TITLE
bug: Ionic/React4.8.0-rc.0 the property 'mycomponent' does not exist on type 'JSX.IntrinsicElements'

### ISSUE THREAD

**Issue by jepiqueau** [ionic-team/ionic#19166]
# Bug Report

**Ionic version:**

[x] **"@ionic/react": "^4.8.0-rc.0"**

**Current behavior:**

When trying to use one of my Stencil Web Component 'jeep-colorpicker' in ionic/react i got this error at compilation time 
``` 
the property 'jeep-colorpicker' does not exist on type 'JSX.IntrinsicElements'
``` 
**Expected behavior:**

it should compile as the component was installed according to the Ionic/Stencil documentation for React framework.
**Steps to reproduce:**

The example has been stored in github  
```
https://github.com/jepiqueau/ionic-react-colorpicker
``` 
and the steps required to duplicate the issue are explained in the README.md file.

the 'stencil-colorpicker' web component has been built with @stenci/core1.3.0

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI : 5.2.5

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3
   npm    : 6.11.1
   OS     : macOS Mojave
```

**Comment by jepiqueau** [comment]
I found after a lot of trials a workaround, i had to add a declarations.d.ts file in the src folder of the React app containing:
``` 
declare namespace JSX {
  interface IntrinsicElements {
    "jeep-colorpicker": any;
  }
}
``` 
see https://github.com/jepiqueau/ionic-react-colorpicker

**Comment by elylucas** [comment]
Hi @jepiqueau,

Yes, that is how to get TypeScript to accept the custom element tag in JSX.

You might also be interested in our stencil bindings project that was just released. It will create native angular/react bindings based on your stencil components: https://github.com/ionic-team/stencil-ds-plugins

**Comment by jepiqueau** [comment]
@elylucas  Yes i will be interested by the stencil binding project. Is there any documentation or example to demonstrate the use of it. It is not really clear for me on how to create my own core stencil package name which i assume should contains all my stencil components. can you give me some help? thanks
