### ISSUE TITLE
bug: Page transition animations no longer work with ionic/react 4.8.0-rc.x

### ISSUE THREAD

**Issue by ebk46** [ionic-team/ionic#19164]
# Bug Report

**Ionic version:**
[x] **4.8** (@ionic/react@4.8.0-rc.1)

**Current behavior:**
When transitioning between pages using IonReactRouter, there is no transition animation.

**Expected behavior:**
In the previous beta versions (tested up til 0.0.7), there were animations.

**Steps to reproduce:**
Transition between pages in mobile view.

**Related code:**
https://stackblitz.com/edit/ionic-v4-react-pthm54

Setting up routes as follows:
```
<IonApp>
  <IonReactRouter>
    <IonPage>
      <Route exact path="/" component={Component1}/>
      <Route exact path="/page2" component={Component2}/>
    </IonPage>
  </IonReactRouter>
</IonApp>
```

**Other information:**
This was working as of 0.0.7 before IonReactRouter existed.

**Ionic info:**
```
Ionic:

   Ionic CLI       : 5.2.5 (/Users/evan/.config/yarn/global/node_modules/ionic)
   Ionic Framework : @ionic/react 4.8.0-rc.1

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.6.0 (/usr/local/Cellar/node/12.6.0/bin/node)
   npm    : not installed
   OS     : macOS High Sierra
```

**Comment by elylucas** [comment]
Hi @ebk46,

We added a new ViewManager component that needs to wrap your IonRouterOutlet and Routes. I've updated your stackblitz to show how it works. We are working on getting these into the docs.
https://stackblitz.com/edit/ionic-v4-react-eu11an

Thanks
