### ISSUE TITLE
bug: IOS only, Ionic 4.8, page will flash when navigate back.

### ISSUE THREAD

**Issue by netsesame2** [ionic-team/ionic#19170]
# Bug Report

**Ionic version:**

[x] **4.8**

**Current behavior:**

IOS only, after update to ionic 4.8, page will flash when navigate back.
BTW, I use md mode to navigate.
Degrade to 4.7.4, it works well.
 
**Expected behavior:**

**Steps to reproduce:**

Use navigation to push a page, then close it use back-button. a flash will appear.

**Related code:**

Use `<ion-back-button></ion-back-button>` to navigate back.

**Other information:**

I take a video to watch what happens. when slow down the video frame, I can see that when click back-button, the current page transit to dismiss, then suddenly appear half a second, then dismiss again, so in normal speed, we can see a flash.
**Ionic info:**

```
Ionic CLI                     : 5.2.5 
Ionic Framework               : @ionic/angular 4.8.0
@angular-devkit/build-angular : 0.802.2
@angular-devkit/schematics    : 8.2.2
@angular/cli                  : 8.2.2
@ionic/angular-toolkit        : 2.0.0
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been fixed and will be in the next release of Ionic.

In the meantime, you can use the dev build I have prepared with this fix if you would like to test it out.

If using Angular: `npm i @ionic/angular@4.9.0-dev.201908231742.f2cfdf1`
If using Ionic Core only: `npm i @ionic/core@4.9.0-dev.201908231742.f2cfdf1`

**Comment by netsesame2** [comment]
Thanks for your fast fix. 
I've installed both dev package,  it works well.
