### ISSUE TITLE
bug: Keyboard overlays app content (input) and have different behavior on platforms iOS and android

### ISSUE THREAD

**Issue by jammin197** [ionic-team/ionic#19189]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

On <ion-input> click keyboard overlays the input. Behavior is different on android and ios. It is working fine on portrait mode but broken on landscape. See attached screenshots. 
![bug_desc](https://user-images.githubusercontent.com/54538273/63698810-edc28380-c81f-11e9-875e-addc32161fc4.png)

I tried also 

'keyboardDidShow' of plugin name="cordova-plugin-ionic-keyboard" spec="^2.1.3".
It is **not** fired on landscape orientation (this is also buggy I think)
fromEvent(window, 'keyboardDidShow').subscribe((event) => {
                console.log('Keyboard is now open');
                console.log(event);
});

And added this to config.xml (also does not solve)
```xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
</xs:schema>
<preference name="KeyboardResize" value="true" />
<preference name="KeyboardResizeMode" value="ionic" />
```
**Expected behavior:**

Android:
There should be footer above the keyboard on android platform.

iOS:
Keyboard cursor definitely should not overlay form validation. 

Both:
When keyboard is opened the content should be at least scrollable. Function 'keyboardDidShow' should be fired when keyboard is shown. I tried only on android and this is not working in landscape orientation.

**Steps to reproduce:**

**Related code:**

```
<app-header label="Enrol Device" wizardSteps="true"
  stepsSubLabel="3 of 4">
</app-header>
<ion-item lines="full">
  <ion-label>
    <h6>{{'universal.devID' | applText}}</h6>
    <h4><strong>{{ deviceId }}</strong></h4>
  </ion-label>
</ion-item>
<ion-item detail="true" button="true" lines="full">
  <ion-label>
    <h3>{{'enrlwz.transStation' | applText}}</h3>
    <p *ngIf="transformerStationId">{{transformerStationId}},&nbsp;{{transformerStationName}}</p>
  </ion-label>
</ion-item>
<ion-item lines="full" mode="md">
  <ion-label position="floating">{{'universal.transID' | applText}}</ion-label>
  <ion-input name="transformerId" placeholder="{{'universal.clickToTypeManually' | applText}}" required="true"
    [(ngModel)]="transformerId"></ion-input>
</ion-item>
<ion-content>
</ion-content>
<ion-footer class="footer-color">
  <ion-button (click)="confirm()" expand="block" [disabled]="(!deviceId || !transformerStationId || !transformerId)">
    <ion-label style="padding-left: 0.5rem; padding-right: 0.5rem;">{{this.utils.getApplicationText('universal.ok')}}
    </ion-label>
  </ion-button>
</ion-footer>

.footer-color {
    background-color: #fff;
}

ion-label > h6 {
    font-size: 0.8rem;
}

ion-label > h4 {
    overflow-x: scroll; overflow-y: hidden; white-space: nowrap;
}
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.3 (C:\Users\z003dt3a\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : not available
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 12 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.1

System:

   NodeJS : v8.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 7

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
