### ISSUE TITLE
TypeError: Failed to set the 'currentTime' property on 'Animation': The provided double value is non-finite.

### ISSUE THREAD

**Issue by supersongpiao** [ionic-team/ionic#19181]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When using the gesture right slide back to half, then swiping left to return to the current page will report an error:
**_TypeError: Failed to set the 'currentTime' property on 'Animation': The provided double value is non-finite._**
At this time, the gesture cannot be returned, and the return using pop() does not take effect.

**Expected behavior:**

I hope that the gesture slide back can work normally.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.5.1, (and 13 other plugins)

```

**Comment by supersongpiao** [comment]
I have only seen this problem when debugging on the browser. I have not seen this problem on my mobile phone.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Which browser are you testing this on? Additionally, can you provide a repo with the code required to reproduce this issue?

**Comment by supersongpiao** [comment]
> I have created a fix for this issue. Can you try it out and let me know if it resolves your issue?
> 
> If using Angular: `npm i @ionic/angular@4.9.0-dev.201908261434.ec8f5be`
> If using Core: `npm i @ionic/core@4.9.0-dev.201908261434.ec8f5be`
> 
> Thanks!

Thank you, I have tried it and my problem is solved.
