### ISSUE TITLE
bug: ion-textarea autoGrow scroll to top on input

### ISSUE THREAD

**Issue by frabaddo** [ionic-team/ionic#19193]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
ionic textarea with autoGrow, scrolls to top on input, when user's input excedes screen height.

**Expected behavior:**
ionic textarea with autoGrow must scroll to key input position,

**Steps to reproduce:**
create a new project, add ion textarea with autogrow attribute and insert text

**Related code:**
Ionic Angular StackBlitz: https://stackblitz.com/edit/ionic-v4-angular-autogrow-error

```
    <ion-textarea
      [autoGrow]="true"
      placeholder="test">
    </ion-textarea>
```

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

System:

   NodeJS : v12.9.1 (/usr/local/bin/node)
   npm    : 6.10.2
   OS     : Linux 4.18
```

**Comment by frabaddo** [comment]
https://imgur.com/a/jAVBmTU

As you can see from the gif,  once you reach the bottom of the text area, it jumps back to the top every time you type.

**Comment by nicolasrhone** [comment]
I can confirm the issue, I have the same on my project. When the textarea get bigger than the screen, it scrolls back to the top at every new input. And then we cannot see the result of the input.

**Comment by haydenbr** [comment]
@liamdebeasi 

I can confirm the same issue: https://stackblitz.com/edit/angular-rter5n?file=src%2Fapp%2Fapp.component.html.

To be more specific, this problem affects the ion-textarea component when `autoGrow` is set to `true`

Steps to reproduce:

1. open the stackblitz
2. make your window height ~500px or less (this is just to make the issue more apparent)
3. scroll to the bottom of the texarea
4. Select the textarea
5. Type any, single key
6. DEFECT: You should notice the window scrolling back to the top of the page

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/19776 and will be available in an upcoming release of Ionic Framework.
