### ISSUE TITLE
bug: ion-page' is not a known element

### ISSUE THREAD

**Issue by ghost** [ionic-team/ionic#19209]
Ionic version:
[x] 4.x

Ionic Info:
Ionic:

ionic (Ionic CLI) : 4.7.0 (C:\Users\NBLHRZEESHAN\AppData\Roaming\npm\node_modules\ionic)
Ionic Framework : @ionic/angular 4.0.0-rc.0
@angular-devkit/build-angular : 0.11.4
@angular-devkit/schematics : 7.1.4
@angular/cli : 7.1.4
@ionic/angular-toolkit : 1.2.2

System:

NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
npm : 6.5.0
OS : Windows 10

Current behavior:
I just copy paste the default Menu Layout code provided in 4.0.0-rc.0 docs and it gives me the error
ERROR Error: Uncaught (in promise): Error: Template parse errors:
'ion-page' is not a known element:

Expected behavior:
It should show the side menu

Steps to reproduce:

Go to https://ionicframework.com/docs/layout/structure and copy paste the Menu Layout code found under the 'Structure' heading into any lazy or eagerly loaded component
run 'ionic serve'
see error in console
see error in visual studio code
Related code:

<ion-app>
  <ion-menu>
    <ion-header>
      <ion-toolbar color="primary">
        <ion-title>Menu</ion-title>
      </ion-toolbar>
    </ion-header>

    <ion-content>
      <ion-list>
        <ion-list-header>
          Navigate
        </ion-list-header>
        <ion-menu-toggle auto-hide="false">
          <ion-item button>
            <ion-icon slot="start" name='home'></ion-icon>
            <ion-label>
              Home
            </ion-label>
          </ion-item>
        </ion-menu-toggle>
      </ion-list>
    </ion-content>
  </ion-menu>

  <ion-page class="ion-page" main>
    <ion-header>
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-menu-toggle>
            <ion-button>
              <ion-icon slot="icon-only" name="menu"></ion-icon>
            </ion-button>
          </ion-menu-toggle>
        </ion-buttons>
        <ion-title>Header</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content padding>
      <h1>Main Content</h1>
      <p>Click the icon in the top left to toggle the menu.</p>
    </ion-content>
  </ion-page>
</ion-app>

<ion-menu-controller></ion-menu-controller>

**Comment by manucorporat** [comment]
`ion-page` is indeed, not a ionic component.

**Comment by Gladsons** [comment]
But it used in the documentation

**Comment by liamdebeasi** [comment]
Thanks for the follow up. It looks like the code snippet with `ion-page` was intended for vanilla JS apps, not Ionic Angular apps. For your use case, you can just use a `div` or a `section`. We will look into making that portion of the docs clearer.
