### ISSUE TITLE
Split pane menu disappears upon resize

### ISSUE THREAD

**Issue by NodeKing** [ionic-team/ionic#19203]
Split pane menu disappears after launching menu and resizing window. Issue exists in Chrome (Version 76.0.3809.132). Firefox 68 works fine.

Steps to reproduce:
npm install -g ionic
ionic start myApp sidemenu

ionic 5.2.6

![sidemenu](https://user-images.githubusercontent.com/29717873/63762141-a9111800-c905-11e9-8e28-3fb45f28eb2a.gif)

**Comment by NodeKing** [comment]
Ionic:
   Ionic CLI : 5.2.6
Utility:
   cordova-res : not installed
   native-run  : not installed
System:
   NodeJS : v10.16.0
   npm    : 6.9.0
   OS     : Linux 4.15

**Comment by NodeKing** [comment]
Gave it a crack. The hamburger menu icon doesn't show now..

**Comment by calvinckho** [comment]
I encountered the same issue. Installed @ionic/angular@4.9.0-dev.201908291313.6425bd9 but it still doesn't fix it. The problem occurs only in chrome.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I think I've identified the problem. Can you give the following dev build a try:

`npm i @ionic/angular@4.9.0-dev.201908301446.3d1aa26`

**Comment by calvinckho** [comment]
I just installed it and it fixed the issue. Thank you!

**Comment by calvinckho** [comment]
now i noticed another strange behavior. The side menu now opens (when pressing the menu-toggle) but doesn’t close in iOS and electron.

**Comment by liamdebeasi** [comment]
Are you trying to close via a gesture, or just by tapping the toggle again?

**Comment by calvinckho** [comment]
>> npm i @ionic/angular@4.9.0-dev.201908301446.3d1aa26

closing via gesture doesn’t work on iOS. it doesn’t close at all in chromium (electron). it closes via gesture fine in android, chrome, and safari.

**Comment by liamdebeasi** [comment]
@calvinckho  Ah interesting. Does this happen on the latest stable version of Ionic, or just on this dev build?

**Comment by liamdebeasi** [comment]
I am going to close this issue as the original issue has been resolved, but feel free to follow up here with more info regarding the gesture issue.

This fix will be available in the next stable release of Ionic.

**Comment by calvinckho** [comment]
It’s just the dev build. I will try it will the most recent stable release.

**Comment by calvinckho** [comment]
@liamdebeasi the issue persists after upgrading to the latest stable version. closing via gesture doesn’t work on iOS. it doesn’t close at all in chromium (electron). it closes via gesture fine in android, chrome, and safari.

**Comment by liamdebeasi** [comment]
Ah yep you know what someone reported this today: https://github.com/ionic-team/ionic/issues/19271

I found out that this bug has existed for a little while in the framework, was just easier to reproduce given some of the recent changes.
