### ISSUE TITLE
bug: Ionic/Angular 4.8.1 - IOS on device, slide menu pulls content off side of screen.

### ISSUE THREAD

**Issue by cparkinsonMYCM** [ionic-team/ionic#19207]
# Bug Report

**Ionic version:**

[x] **4.8.1**

**Current behaviour:**

On IOS, found in the Simulator, if I navigate to a page with ion-slides, and swipe over to the third slide, then open the slide menu at the left and navigate to another page, the content of that page is pulled off the left of the screen

**Expected behaviour:**

Content be placed correctly, regardless of previous animations/situations.

**Steps to reproduce:**

I'm not sure if the ion-slides are necessary, but it seems to be the way that I can semi-reliably reproduce the issue, it is not consistent.
I have recorded the process as I'm unsure of the specific conditions to reproduce it. Though the video isn't as fluid as was visible in the Simulator, at the point where the menu closes it seems to pause and then jump to the content being partially offscreen, however on the Simulator the content shows and is immediately moved offscreen, it doesn't jump out of place, it just moves with the menu and ends up placed incorrectly.
[content pulled off left.mov.zip](https://github.com/ionic-team/ionic/files/3550168/content.pulled.off.left.mov.zip)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.1
   @angular-devkit/build-angular : 0.802.2
   @angular-devkit/schematics    : 8.3.0
   @angular/cli                  : 8.2.2
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.0.0
   @capacitor/core : 1.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 8 other plugins)

Utility:

   cordova-res : 0.5.1 (update available: 0.6.0)
   native-run  : 0.2.7 (update available: 0.2.8)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v12.5.0 (/usr/local/bin/node)
   npm        : 6.10.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8
```

**Comment by cparkinsonMYCM** [comment]
Not easily, no.

I'm afraid I don't have the time spare currently to find the root and build a sample to exhibit it.
I only found it when checking that another issue had been resolved, though it was fine before I updated to 4.8.1.

I can't even say if it happens in browser, because I'm having to test in the ios simulator as some cordova plugins don't work in the browser.
And it doesn't happen on Android.

The project I found it in is built and ready for deployment, but now has 2 issues preventing further progress.
I appreciate that Ionic is a large project, but I'm now stuck waiting for more than I'd wish to be...

I'll tinker tonight out of work, and see if I can get a demo project to assist, but at present I have no idea what might be causing this so it may take a while.

**Comment by cparkinsonMYCM** [comment]
Sure, can do.
Will let you know how it goes.

---

_Written before 4.9.0-dev comment but figured I'd leave it here just in case something in there is useful;_

> If you have an application ready for deployment, I would recommend just sticking with Ionic 4.7.4 for now.

Heh, the trouble there is the initial issue that prevents the project going out is still not resolved, which was found in 4.5.0.

> Do you at least have general steps to reproduce?

The video and description in the issue shows the process, but to be a little more specific;

- From the 'home' screen, navigates to a list of items, loaded from a remote resource.
- Item is downloaded, then navigates a page that uses the downloaded data.
- Page contains ion-slides holding the main contents. It may not be necessary to reproduce, but I swipe across to the last slide.
- Open menu and navigate to the list, as in the first step but from the open side menu.
- As that page loads again, and the menu closes, the content slides with the menu but stops too far off to the left.

But I will try and put together a blank project to demonstrate the problem.

Oh, also, I don't know if #19203 is related, but from the view in the image presented there, where the menu itself is off to the left of the page, if that were the case here that would explain if the content is sitting next to the menu.

**Comment by cparkinsonMYCM** [comment]
@liamdebeasi No luck, the ion-menu-button is no longer present and swipes from the left navigate backwards so I can't open the menu at all to test it.

**Comment by cparkinsonMYCM** [comment]
Same deal, no menu button there either.
Can't verify whether resolved or not.

**Comment by peterpeterparker** [comment]
I couldn't test the dev build neither, no menu button is displayed

I kind of face the same error as OP. Without using a slider my menu is blank of the first opening on iOS simulator, that's why I follow this task and will also be happy to test

<img width="535" alt="Capture d’écran 2019-08-29 à 10 13 05" src="https://user-images.githubusercontent.com/16886711/63926337-fc8d7e00-ca4b-11e9-8ad5-7a7b7870e8f6.png">

**Comment by liamdebeasi** [comment]
🤔 Try this one:

`npm i @ionic/angular@4.9.0-dev.201908291313.6425bd9`

This is based off 4.8.1 with only the changes I've made so it shouldn't have that other menu bug.

**Comment by cparkinsonMYCM** [comment]
> 4.9.0-dev.201908291313.6425bd9
Looks good! Can't reproduce the issue anymore.

**Comment by liamdebeasi** [comment]
Great! This fix has been merged and will be available in the next release of Ionic. Until then, feel free  to continue to use this dev build.
