### ISSUE TITLE
bug: setFocus method doesn't work on iOS 13 Beta

### ISSUE THREAD

**Issue by eun-choi** [ionic-team/ionic#19224]
# Bug Report
.setFocus() method doesn't work on iOS 13 Beta 8
(Reproduced component: ion-input & ion-searchbar & ion-textarea )

**Ionic version:**
@ionic/core & @ionic/angular 4.4.2

**Steps to reproduce:**
1. Install iOS >= 12.4.1
2. Create setFocus method in code
3. Try it: work
4. Install iOS 13 developer beta 8
5. Try it: doesn't work

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a code reproduction of the issue? `setFocus` is working fine for me on both iOS 12 and iOS 13.
