### ISSUE TITLE
bug: Custom IonicModule.forRoot() settings doesn't work on >=4.6.0

### ISSUE THREAD

**Issue by eun-choi** [ionic-team/ionic#19223]
# Bug Report
Custom IonicModule.forRoot() settings doesn't work on @ionic/core & @ionic/angular >=4.6.0
(It works on @ionic/core & @ionic/angular <= 4.5.0)
I would like to use custom navAnimation transition.

**Ionic version:**
[o] <= 4.5.0
[x] >= 4.6.0 (include 4.7.x & 4.8.x)

**app.module.ts code:**
> @NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    BrowserModule,
    IonicModule.forRoot({
      backButtonText: '',
      rippleEffect: false,
      animated: true,
      mode: 'md',
      swipeBackEnabled: true,
      hardwareBackButton: false,
      backButtonIcon: 'ios-arrow-back',
      navAnimation: myTransitionAnimation
    }),

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a code reproduction of the issue?
