### ISSUE TITLE
I want to remove these two small buttons ( see attached image ) from ion-input 

### ISSUE THREAD

**Issue by atifgulzar** [ionic-team/ionic#19233]
Hi Ionic team, 

I want to remove these two little buttons from my desktop applications. 

![Screenshot 2019-08-30 at 2 42 49 PM](https://user-images.githubusercontent.com/572680/64011194-a1838600-cb34-11e9-8362-7e89a5d5b254.png)

**Comment by farsadx** [comment]
This is not an issue related to the Ionic framework, but you can remove them by using the following CSS snippet:
```
input[type=number]::-webkit-inner-spin-button, 
input[type=number]::-webkit-outer-spin-button { 
  -webkit-appearance: none; 
  margin: 0; 
}
```
As this issue is not related to the Ionic framework, kindly close this issue.

**Comment by atifgulzar** [comment]
Ah sorry to posting on the wrong channel. But your solution worked.

Thanks 
Cheers
