### ISSUE TITLE
bug: UIWebView Deprecation warning on AppStore

### ISSUE THREAD

**Issue by EdwinRozario** [ionic-team/ionic#19231]
# Bug Report

**Ionic version:**
**5.1.0**

**Current behavior:**
Receiving this email from Appstore

```Dear Developer,

We identified one or more issues with a recent delivery for your app, "SuperGold" 0.0.20 (0.0.20). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
```

**Related code:**
package.json
```
  "dependencies": {
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/free-regular-svg-icons": "^5.8.1",
    "@ionic-native/app-version": "^5.12.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/diagnostic": "^5.10.0",
    "@ionic-native/geolocation": "^5.8.0",
    "@ionic-native/ionic-webview": "^5.12.0",
    "@ionic-native/mobile-accessibility": "^5.5.1",
    "@ionic-native/network": "^5.9.0",
    "@ionic-native/open-native-settings": "^5.10.0",
    "@ionic-native/sms": "^5.12.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic-native/toast": "^5.9.0",
    "@ionic/angular": "^4.1.0",
    "@ionic/pro": "2.0.4",
    "@ionic/storage": "^2.2.0",
    "airbrake-js": "^2.0.0-beta.3",
    "cordova-android": "^8.0.0",
    "cordova-ios": "5.0.1",
    "cordova-open-native-settings": "^1.5.2",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-ionic-webview": "^4.1.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-sqlite-storage": "^3.2.0",
    "cordova.plugins.diagnostic": "^5.0.0",
    "core-js": "^2.5.4",
    "crypto-js": "^3.1.9-1",
    "lodash": "^4.17.14",
    "node-js-marker-clusterer": "^1.0.0",
    "phonegap-plugin-mobile-accessibility": "git+https://github.com/phonegap/phonegap-mobile-accessibility.git",
    "query-string": "^6.8.1",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "uk.co.workingedge.phonegap.plugin.launchnavigator": "^5.0.4",
    "zone.js": "~0.8.29"
  },```

**Other information:**
ReactNative community is also having the same conversation. https://github.com/react-native-community/react-native-webview/issues/819.

I tried an not sure if any of the dependancies are using UIWebView.

**Comment by developeromI89** [comment]
> # Bug Report
> **Ionic version:**
> **5.1.0**
> 
> **Current behavior:**
> Receiving this email from Appstore
> 
> ```
> 
> We identified one or more issues with a recent delivery for your app, "SuperGold" 0.0.20 (0.0.20). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
> ```
> 
> **Related code:**
> package.json
> 
> ```
>   "dependencies": {
>     "@angular/common": "^7.2.2",
>     "@angular/core": "^7.2.2",
>     "@angular/forms": "^7.2.2",
>     "@angular/http": "^7.2.2",
>     "@angular/platform-browser": "^7.2.2",
>     "@angular/platform-browser-dynamic": "^7.2.2",
>     "@angular/router": "^7.2.2",
>     "@fortawesome/angular-fontawesome": "^0.3.0",
>     "@fortawesome/free-regular-svg-icons": "^5.8.1",
>     "@ionic-native/app-version": "^5.12.0",
>     "@ionic-native/core": "^5.0.0",
>     "@ionic-native/diagnostic": "^5.10.0",
>     "@ionic-native/geolocation": "^5.8.0",
>     "@ionic-native/ionic-webview": "^5.12.0",
>     "@ionic-native/mobile-accessibility": "^5.5.1",
>     "@ionic-native/network": "^5.9.0",
>     "@ionic-native/open-native-settings": "^5.10.0",
>     "@ionic-native/sms": "^5.12.0",
>     "@ionic-native/splash-screen": "^5.0.0",
>     "@ionic-native/status-bar": "^5.0.0",
>     "@ionic-native/toast": "^5.9.0",
>     "@ionic/angular": "^4.1.0",
>     "@ionic/pro": "2.0.4",
>     "@ionic/storage": "^2.2.0",
>     "airbrake-js": "^2.0.0-beta.3",
>     "cordova-android": "^8.0.0",
>     "cordova-ios": "5.0.1",
>     "cordova-open-native-settings": "^1.5.2",
>     "cordova-plugin-app-version": "^0.1.9",
>     "cordova-plugin-file": "^6.0.1",
>     "cordova-plugin-file-transfer": "^1.7.1",
>     "cordova-plugin-ionic-webview": "^4.1.1",
>     "cordova-plugin-splashscreen": "^5.0.2",
>     "cordova-sqlite-storage": "^3.2.0",
>     "cordova.plugins.diagnostic": "^5.0.0",
>     "core-js": "^2.5.4",
>     "crypto-js": "^3.1.9-1",
>     "lodash": "^4.17.14",
>     "node-js-marker-clusterer": "^1.0.0",
>     "phonegap-plugin-mobile-accessibility": "git+https://github.com/phonegap/phonegap-mobile-accessibility.git",
>     "query-string": "^6.8.1",
>     "rxjs": "~6.5.1",
>     "tslib": "^1.9.0",
>     "uk.co.workingedge.phonegap.plugin.launchnavigator": "^5.0.4",
>     "zone.js": "~0.8.29"
>   },```
> 
> **Other information:**
> ReactNative community is also having the same conversation. https://github.com/react-native-community/react-native-webview/issues/819.
> 
> I tried an not sure if any of the dependancies are using UIWebView.
> ```

Did you resolve it?
I am also facing same issue.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is more of a Cordova/Capacitor issue.

That being said, we are definitely aware of this deprecation and are working on a solution.
