### ISSUE TITLE
bug: React proxied Ionic webcomponents do not support webcomponent properties

### ISSUE THREAD

**Issue by marcoromag** [ionic-team/ionic#19236]
Hi,

I noticed that whenever the components have properties that are NOT on{Event} or href, or ref, the proxy implementation does not pass them to the html webcomponent.

As an example: 
```
                        <IonItem lines="none">
                            <IonLabel>
                                <h3>Hello</h3>
                                <h4>world</h4>
                            </IonLabel>
                            <IonIcon color="primary" icon={heartEmpty} slot="end"/>
                        </IonItem>
```

Will always render with lines, also if the property `line` is `"none"`.
The reason seem to be in the implementation of `createReactComponent` that forwards only the generic well-known properties and on{Event} properties, but not the component-specific ones

**Comment by elylucas** [comment]
Hi @marcoromag,

I believe this has been fixed in a dev build that is going to be in the next RC release. If you could, try out 4.8.0-rc.2-1 and see if that fixes the issue.

Thanks

**Comment by marcoromag** [comment]
Hi Ely,

yes, it is fixed in that release! great!

Thanks a lot,
Marco

Il giorno ven 30 ago 2019 alle ore 18:20 Ely Lucas <notifications@github.com>
ha scritto:

**Comment by elylucas** [comment]
great, enjoy!
