### ISSUE TITLE
bug: Transparant overlay after two times transition

### ISSUE THREAD

**Issue by maxtor3569** [ionic-team/ionic#19248]
If I switch 2 times between pages, after transition a weird white overlay appears.
It only appears if I switch from page A to B and come back to page A.

The transition is made using routerLink between 2 pages.

The old page appeared on the background animation transition really fast, and after arriving on the new page, a white overlay is put on top of the page.

I'm using the latest ionic version with angular.
Here the white weird overlay. 

<img width="1680" alt="Capture d’écran 2019-09-01 à 21 57 34" src="https://user-images.githubusercontent.com/4617169/64081614-e0b40180-cd03-11e9-8145-010625577e0a.png">

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a code reproduction of the issue?

**Comment by maxtor3569** [comment]
Yes.   I switch from homepage to login and coming back to Homepage with the arrow located on top

Homepage
 `
<ion-content fullscreen padding scroll-y="false">
	<ion-slides class="slider">

		<ion-slide>
			<img src="./slide-1.png"/>

		</ion-slide>

		<ion-slide>
			<img src="./slide-2.png"/>
			<h2>What is Ionic?</h2>
			<p><b>Ionic Framework</b> is an open source SDK that enables developers to build high quality mobile apps with web technologies like HTML, CSS, and JavaScript.</p>
		</ion-slide>

		<ion-slide>
			<img src="./slide-3.png"/>
			<h2>What is Ionic Pro?</h2>
			<p><b>Ionic Pro</b> is a powerful set of services and features built on top of Ionic Framework that brings a totally new level of app development agility to mobile dev teams.</p>
		</ion-slide>

		<ion-slide>
			<img src="./slide-4.png"/>
			<h2>Ready to Play?</h2>
			<ion-button fill="clear">Continue <ion-icon slot="end" name="arrow-forward"></ion-icon></ion-button>
		</ion-slide>

	</ion-slides>

	<div>


		<ion-button expand="block" (click)="loginFacebook()" color="secondary" style="text-transform: uppercase;margin-bottom: 20px">
			đăng nhập Facebook
		</ion-button>

		<ion-button expand="block"  fill="outline" class="btn-tai-khoan" style="text-transform: uppercase;" [routerLink]="['/register']">
			Tạo tài khoản
		</ion-button>

		<div class="ion-text-center login-link" >
			<a [routerLink]="['/login']" style="text-decoration: none">
				Already have an account? <span style="text-decoration: underline">Log in</span>
			</a>
		</div>
	</div>
</ion-content>
`

Login Page

`<ion-content padding class="login">

	<a [routerLink]="['/']">
		<ion-icon name="arrow-dropleft" style="font-size:40px"></ion-icon>
	</a>

	<div class="logo-container">
		<img src="../../assets/logo.png" class="logo" />
	</div>

	<h3 style="" class="ion-text-left">Chào mừng trở lại</h3>

	<ion-input placeholder="Email" class="email"></ion-input>
	<ion-input placeholder="Mật khẩu"></ion-input>
	<div class="forgetLink">
		<a>
			Quên mật khẩu?
		</a>
	</div>

	<ion-button expand="block" class="primary-button">Đăng nhập</ion-button>
</ion-content>
`

Home routing 
`import {NgModule} from '@angular/core';
import {Routes, RouterModule} from '@angular/router';
import {AuthGuard} from '../core/services';
import {HomePage} from './home.page';

const routes: Routes = [
	{
		path: '',
		component: HomePage,
	}
];

@NgModule({
	imports: [RouterModule.forChild(routes)],
	exports: [RouterModule]
})
export class HomeRoutingModule {
}
`

**Comment by liamdebeasi** [comment]
Can you provide a repo with a reproduction of this issue? It's hard to reproduce an issue like this with just code snippets.

Also, in your original image I don't see a white overlay. What should I be looking for?

**Comment by maxtor3569** [comment]
Yes sorry I will push to a repo.
It's really hard to explain the issue.
You can see the difference here :  Before / After.
is it more clear ?

<img width="285" alt="Capture d’écran 2019-09-03 à 15 37 14" src="https://user-images.githubusercontent.com/4617169/64177982-d78c7700-ce60-11e9-8319-6bc70304df1b.png">
<img width="283" alt="Capture d’écran 2019-09-03 à 15 37 22" src="https://user-images.githubusercontent.com/4617169/64177983-d8250d80-ce60-11e9-92f0-d0a733eb160b.png">

**Comment by liamdebeasi** [comment]
Great, thanks! Another thing to try is the following dev build: 

`npm i @ionic/angular@4.9.0-dev.201908291313.6425bd9`

I fixed a bug in transitions that _might_ be related to this. Worth a shot!

**Comment by maxtor3569** [comment]
Yes it's seems working ! Thanks a lot !!

**Comment by liamdebeasi** [comment]
Great, glad to hear that! In that case, I am going to close this issue. The bug fix contained in that dev build will be available in the next stable release of Ionic.
