### ISSUE TITLE
bug: ion-virtual-scroll does not work on touch devices if gestures are defined on the item

### ISSUE THREAD

**Issue by julianpoy** [ionic-team/ionic#19244]
# Bug Report

**Ionic version:**
[x] **4.8.1**

**Current behavior:**
If you define a gesture (such as press or tap) on an item within virtual scroll, scrolling stops working on touch devices. It still works on devices with a scroll wheel.

**Expected behavior:**
Defining a gesture on an item should not break scrolling within a virtual scroll list.

**Steps to reproduce:**
Create a virtual scroll list with ion-virtual-scroll, create several virtualItems within that list, and add (tap)="test()" or (press)="test()" to them. Then try to scroll with touch in the chrome simulator (make sure that it's in touch/mobile mode) by dragging on the list.

**Related code:**

```
<ion-virtual-scroll [items]="myItems">
    <ion-item
      *virtualItem="let myItem"
      (tap)="test()"
      (press)="test()">
      <ion-label>
        Test Item
      </ion-label>
    </ion-item>
  </ion-virtual-scroll>
```

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 5.0.3 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.1
   @angular-devkit/build-angular : 0.803.2
   @angular-devkit/schematics    : 8.3.2
   @angular/cli                  : 8.3.2
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (/usr/bin/node)
   npm    : 6.9.0
   OS     : Linux 4.18


```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you using HammerJS? HammerJS has been known to capture certain events and not let them propagate, causing things like scrolling to break down.

**Comment by julianpoy** [comment]
Yep, this is with HammerJS. Only a problem within VirtualScroll.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Due to the reasons in my previous comment, we do not have any official support for HammerJS. I am going to close this issue, but we do have plans to introduce HammerJS-like functionality into Ionic in the future. Thanks!
