### ISSUE TITLE
bug: Blank screen with IonReactRouter and Electron

### ISSUE THREAD

**Issue by spidercatnat** [ionic-team/ionic#19246]
Description of the problem:

IonReactRouter does not work in Electron production builds. With Capacitor, it does not work whatsoever. The elements are present in the markup, but they are rendered invisible. Is it possible to allow IonReactRouter to have an additional API layer over the HashRouter instead of just BrowserRouter, which does not work with Electron?

Affected platform
- [ ] Android
- [ ] iOS
- [x] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ ] macOS
- [x] linux

Other information:

Capacitor version: `1.1.1`

node version: `10.16.3`

npm version: `6.9.0`

CocoaPods version: `N/A`

Steps to reproduce:
1. Generated boilerplate code with
 `ionic start ionic-electron sidemenu --capacitor --type=react`

2. Set homepage in `package.json`:
``` 
{
...
  "homepage": ".",
...
}
```
3. Created a build with `ionic build`

4. Initialized Electron project with `npx cap add electron`

5. Copied project contents to electron project with `npx cap copy`

6. Ran app with `npx cap open electron`

**This issue happens with the component regardless of whether or not the project was bootstrapped with Capacitor.**

**Comment by chrismatheson** [comment]
@bloom510 i don't know if your still having trouble with this, but i worked around it with

```
const Router:any = isPlatform("electron") ? IonReactHashRouter : IonReactRouter;

const App: React.FC = () => (
  <IonApp>
    <Router>
      <IonRouterOutlet>
        <Route path="/home" component={Home} exact={true} />
        <Route exact path="/" render={() => <Redirect to="/home" />} />
      </IonRouterOutlet>
    </Router>
  </IonApp>
);```

possibly the "default" react app for ionic could be updated? 

another option might be to have electron inject some code to push `/` onto the history just before booting the application ?

**Comment by elylucas** [comment]
Closing this issue as its old on a beta version of Ionic/React. If the problem still persists on the latest version, please create a new issue and link this one for reference.
