### ISSUE TITLE
support: Hardware back button returns to old pages

### ISSUE THREAD

**Issue by SaltyPotato** [ionic-team/ionic#19255]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
When I navigate from page to page, for example:
Home Page (Root) -> Details Page -> Account Page
And I click the back button 2 times, it will return like this:
Account Page -> Details Page -> Home Page (Root)

That works fine, BUT if I do the above multiple times and I click the back button when I'm on the home page, it will repeat the whole route history again! 
This only happens while using the hardware back-button.
**Expected behavior:**
I expect to see that the page I'm leaving is removed from the route history and that the hardware back button is disabled when there is no route history.

**Steps to reproduce:**
Navigate through multiple pages and use the hardware back-button to return. When on the root page, click the hardware back-button again multiple times.

**Related code:**
My app routing:
```
const routes: Routes = [
  {
    path: 'home',
    loadChildren: './pages/home/home.module#HomePageModule',
  },
  {
    path: 'login',
    loadChildren: './pages/login/login.module#LoginPageModule'
  },
  { path: 'details', loadChildren: './pages/details/details.module#DetailsPageModule' },
  { path: 'account', loadChildren: './pages/account/account.module#AccountPageModule' },
];
```

**Other information:**
Phone used: Samsung Galaxy s8

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 13 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.0
   NodeJS     : v12.9.0 (/usr/local/Cellar/node/12.9.0/bin/node)
   npm        : 6.11.2
   OS         : macOS
   Xcode      : Xcode 10.3 Build version 10G8
```

**Comment by SaltyPotato** [comment]
This issue is similair to the behavior I'm experiencing: https://stackoverflow.com/questions/54306319/ionic-4-angular-loops-in-router-history

**Comment by liamdebeasi** [comment]
Hi there,

Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue. Thanks!
