### ISSUE TITLE
bug: Problem when gesture returns

### ISSUE THREAD

**Issue by supersongpiao** [ionic-team/ionic#19254]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When using the gesture to swipe to the right to return yes, slide a short distance, then release your finger, the following page will disappear immediately, the moment you release your finger, immediately add .ion-page-hidden to the DOM, but the page will return Animation time

**Expected behavior:**

I want the gesture to return to cancel, the next page can be saved after the return animation is completed.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.1
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.5.1, (and 14 other plugins)

```

**Comment by supersongpiao** [comment]
![g25qj-6wcyc](https://user-images.githubusercontent.com/31645741/64160573-c21e4980-ce6e-11e9-9640-1d032fb06a12.gif)
In the gif, when I cancel the gesture and return, the following page will disappear immediately, instead of disappearing after the animation is finished.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This issue has been fixed and will be available in the next release of Ionic.
