### ISSUE TITLE
bug:  Anyone have encountered ionic4 page exit after stack does not remove the case like NGRX store listening after listening will always exist will not automatically eliminate. There is also a problem with the page stack. Routerlink does not show new pages on other pages and goes to the bottom

### ISSUE THREAD

**Issue by wennjie** [ionic-team/ionic#19253]
# Bug Report

**Ionic version:**

[x] **4.x**
 5.2.1

**Current behavior:**

A: Anyone have encountered ionic4 page exit after stack does not remove the case like NGRX store listening after listening will always exist will not automatically eliminate. There is also a problem with the page stack. Routerlink does not show new pages on other pages and goes to the bottom

**Expected behavior:**

A:Expect smooth page switching
**Steps to reproduce:**

A: In the case of network load continuously click switch page routing, after many times will appear to change the problem

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI : 5.2.1

Utility:

   cordova-res : not installed
   native-run  : 0.2.2 (update available: 0.2.8)

System:

   NodeJS : v10.15.3
   npm    : 6.9.0
   OS     : macOS Mojave


```

**Comment by ionicdeva** [comment]
I also had this problem, but I didn't completely fix it

**Comment by liamdebeasi** [comment]
Hi there,

Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue. Thanks!
