### ISSUE TITLE
bug: component reuse breaks ion-radio-group/ion-radio (stuck in infinite loop)

### ISSUE THREAD

**Issue by DavidStrausz** [ionic-team/ionic#19277]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Since @ionic/angular 4.9.0 ion-radio-group/ion-radio end up in an infinite loop when reused (e.g. navigating to the same page a second time).

**Expected behavior:**
Not to be stuck in an infinite loop.

**Steps to reproduce:**
1. Clone example repo
2. npm i
3. ionic serve
4. open dev-tools
5. on tab1 click on "push page with radio-group"
6. navigate back to tab1
7. click on "push page with radio-group" again
8. check console -> infinite loop

**Related code:**
https://github.com/DavidStrausz/radio-reusage-bug

**Other information:**
Probably cause by #18963 

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.7 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.4.0 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by EricKit** [comment]
Same issue here when Popover is presented a second time.

**Comment by DavidStrausz** [comment]
@manucorporat I'm sorry to ping you like that, but as there is already a bug fix release out for 4.9.0 I'm wondering if you guys are aware of this issue and if it is going to be fixed before the next major version.

Cheers

**Comment by JeramieHallyburton** [comment]
This is a pretty big issue. Multiple pages in my app have been completely frozen and killed by Chrome.

**Comment by liamdebeasi** [comment]
This issue has been fixed and will be available in the next release of Ionic. Thanks!
