### ISSUE TITLE
ion-back-button not displaying anything in Android or IOS

### ISSUE THREAD

**Issue by gigglegirl** [ionic-team/ionic#19273]
Bug Report : 

Ionic Info:

      Ionic CLI                     : 5.2.3 (C:\Users\lsingh\AppData\Roaming\npm\node_modules\ionic)
      Ionic Framework               : @ionic/angular 4.4.0
      @angular-devkit/build-angular : 0.13.9
      @angular-devkit/schematics    : 7.2.4
      @angular/cli                  : 7.3.9
      @ionic/angular-toolkit        : 1.4.1

     Cordova:

     Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
     Cordova Platforms : android 7.1.4, ios 4.5.5
     Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.0, 
     (and 10 other plugins)

     Utility:

     cordova-res : not installed
     native-run  : 0.2.8

     System:

      Android SDK Tools : 26.1.1 (C:\Users\lsingh\AppData\Local\Android\Sdk)
      NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
      npm               : 6.9.0
      OS                : Windows 10

Describe the Bug : 
The ion-back-button doesn't show the icon in Android . 

Steps to Reproduce: 

          1)<ion-header>
              <ion-toolbar>
                <ion-buttons slot="start">
                  <ion-back-button></ion-back-button>
               </ion-buttons>
              </ion-toolbar>
          </ion-header>
          2)run command in terminal :  ionic cordova run android -l

Expected Behavior

The icon should be visible.

Current Behavior : 
Icon is invisible but when clicked on particular area where button should exist, it navigates back to the last visited page.

Additional Context: 
1)My app is running in Android Simulator.
2)<ion-back-button defaultHref="home" ></ion-back-button>
When i mention property defaultHref="home"  the back icon shows up but i do not get navigated to last Visited Page. I get navigated to home page which is the expected behaviour i guess.In such case how do i navigate back to also visited page also.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try this again on the latest version of Ionic?

**Comment by gigglegirl** [comment]
Hi @liamdebeasi , i cloned one basic project from 'https://github.com/ionic-team/photo-gallery-tutorial-ionic4/'  and following code of tab1.page.html

          <ion-header>
             <ion-toolbar>
               <ion-title>
                    <ion-back-button ></ion-back-button>
                  Tab One
            </ion-title>
            </ion-toolbar>
            </ion-header>

Please let me know why it is not working here it has latest version of ionic.

**Comment by andypotato** [comment]
I can confirm this issue still exists with the latest version of Ionic

**Comment by gigglegirl** [comment]
Do you think is there any alternative @andypotato?

**Comment by liamdebeasi** [comment]
Thanks for the issue. You are not using `ion-back-button` correctly. `ion-back-button` only appears if there are other pages in the navigation stack. In the app you provided, tab 1 is the root page and has no other pages in the navigation stack, so the back button is not going to show up.

I am going to close this as this is more of a support request. For further questions I recommend posting on our [forums](https://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com).
