### ISSUE TITLE
bug: ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs 

### ISSUE THREAD

**Issue by shrivallabhDeshmukh** [ionic-team/ionic#19283]
Dear Team

I got below mail from apple after uploading app to testFlight

Dear Developer,
We identified one or more issues with a recent delivery for your app, "Michael Page FR" 1.0.0 (1.0.2). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . Seehttps://developer.apple.com/documentation/uikit/uiwebview for more information.
After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
Best regards,
The App Store Team

Please advice on this issue. 
your early response in this regard would be highly appreciated.
Thank you

**Comment by liamdebeasi** [comment]
This is an issue with Capacitor/Cordova, not with Ionic Framework. We are aware of this warning for Capacitor and are taking steps to resolve it.
