### ISSUE TITLE
bug: Multiple ionic side menus works fine on desktop browser but doesn't work in mobile browser. 

### ISSUE THREAD

**Issue by Shery11** [ionic-team/ionic#19282]
I am working on creating a PWA using ionic 4. What i need there is multiple menus which i open and close according to user state in the application.

I have build the app as PWA and deployed it to firebase everything is works fine in desktop browser but it doesn't seem to work in mobile browser. Like when you click on toggle button it open up the side menu but it doesn't close on swipe or even when i try to do it in the code.

I have included the source code which is on github and also deployed it on firebase for you guys to check on both desktop browser where it works fine and on mobile browser where it doesn't work as expected.

Here is the github link to code : https://github.com/Shery11/ionic-menu

Here is the link to PWA : https://redexs-28ea4.firebaseapp.com/home

**Comment by liamdebeasi** [comment]
Thanks for the issue. What device are you testing this on?

**Comment by Shery11** [comment]
So far i have tested on multiple android browsers.

**Comment by liamdebeasi** [comment]
Are you testing this on an actual device or a simulator?

**Comment by Shery11** [comment]
Actual device. It's a PWA you can also test it here on mobile browser  https://redexs-28ea4.firebaseapp.com/home

**Comment by liamdebeasi** [comment]
Ok thanks for the follow up. Does this bug occur on Ionic 4.7.4?

**Comment by liamdebeasi** [comment]
For context I'm trying to determine if this is related to https://github.com/ionic-team/ionic/issues/18974

**Comment by Shery11** [comment]
My cli version is 5.0.2 

Here is project package.json 

`{
  "name": "menutest",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@angular/service-worker": "~8.1.2",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.7.1",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@ionic/angular-toolkit": "~2.0.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project"
}
`

**Comment by liamdebeasi** [comment]
Thanks for the additional info, but does this bug occur on Ionic 4.7.4? The info in your package.json would indicate that the latest version of Ionic is installed.

**Comment by Shery11** [comment]
I don't think its related to that issue because it works fine in web browsers.

**Comment by Shery11** [comment]
No it occurs in the version that installed right now because i just created this project. So its the latest version.

**Comment by liamdebeasi** [comment]
Hmm I'm not sure I am able to reproduce the issue. When I use the PWA in the link you have provided, I can still close the menu when clicking the toggle button.

**Comment by liamdebeasi** [comment]
I'm testing this on Chrome 76 on a physical Android device

**Comment by Shery11** [comment]
Are you able to close menu by swipe as well ?

**Comment by Shery11** [comment]
When you open the menu are you able to open another one when you click on the button on the menu as it's suppose to open menu 2 when you do so. You can check the actual working in desktop browser and the issue appears in mobile browsers

**Comment by liamdebeasi** [comment]
Yes, when I click the button it opens Menu 1. From there, I can click "Open 2" which opens Menu 2. At both points I am able to swipe to close the menu.

**Comment by Shery11** [comment]
Can you please tell me which device is it ? It's screen size as well. 

I tested it on a tablet as it's screen is big it seems to work there but all mt tests failed while testing on mobiles.

**Comment by iamkinetic** [comment]
This doesn't seems to be related #18974

Btw, I'm not seeing your bug either on chrome 76 running on a Android 9 device or on Iphone XS with iOS 13.

**Comment by liamdebeasi** [comment]
I'm testing on a Moto G4 phone: https://www.gsmarena.com/motorola_moto_g4-8103.php

**Comment by Shery11** [comment]
OK so i just updated chrome it seems to work there now. It seems the problem is related to older versions of chrome. 

I just tested on version 55 and it shows the problem there.

**Comment by liamdebeasi** [comment]
Glad to hear it's working now! Can I close this issue?

**Comment by Shery11** [comment]
Can you please wait a bit i will testing on safari browser if it works there I will close it myself.

**Comment by Shery11** [comment]
It works on safari thanks for the help.
