### ISSUE TITLE
Need to add textarea in AlertController

### ISSUE THREAD

**Issue by pandeeswaran** [ionic-team/ionic#19286]
As of now not allowed textarea in AlertController.

We have customised in below node modules and added textarea input type, it has been working as expected in our project.
 
./node_modules/@ionic/core/dist/esm/ion-alert-md.entry.js
./node_modules/@ionic/core/dist/esm/ion-alert-ios.entry.js
./node_modules/@ionic/core/dist/types/components/alert/alert-interface.d.ts line:19 (type?: TextFieldTypes | 'checkbox' | 'radio' | 'textarea';)

Officially need to work for it. We have using appFlow that time, the above customised node_modules files are not rendered/build. It was throw an error.

Thanks.

**Comment by pandeeswaran** [comment]
This feature already discussed on 2years back yet not resolved
# Support for textarea in alert #8125

**Comment by longgt** [comment]
https://github.com/ionic-team/ionic/pull/16851

**Comment by liamdebeasi** [comment]
Thanks for the feature request. This was added in Ionic Framework v5.0.
