### ISSUE TITLE
feat: add a "live reload flag" 

### ISSUE THREAD

**Issue by distante** [ionic-team/ionic#19297]
# Feature Request

**Ionic version:**
[x] **4.7.1**

**Describe the Feature Request**
Provide a way to determine when we are running Ionic using the `--livereload` flag.

**Describe Preferred Solution**
When we are using the `--livereload` flag to debug the an in a Device, a way to recognize this should be available either with a `platform.isLiveReload()` or an `window.isIonicLiveReload` flag.

**Describe Alternatives**
For ionic 3 I was snipping the URL for see if `localhost` is not present. It does not work anymore.
Other options where to look into the window object for an `IonicDevServer` object. It does not work anymore.

As current workaround I am making a [proxy of the WebSocket class to check when a connection is made](https://www.saninnsalas.com/how-to-detect-when-an-ionic-app-is-running-on-device-with-livereload/?preview=true&_thumbnail_id=399). I wanted to put that code in a PR but I didn't knew in which file should I do it.

**Additional Context**
Some functionality needs workarounds or other way to handle. Example: Load media files from the device internal storage will throw CORS errors in livereload.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you describe your use case a bit more? Are you able to just set environment flags?

**Comment by distante** [comment]
Hi, yes of course.

I am working in an app that needs to load local audio files into an `<audio>` tag. I get the URLs using a mix of the `FileChooser` and `File` plugins. The paths obtained do not work on live reload for a CORS issue (in device) so when I am in `devMode` + `livereload` I have to take another route (`if`) so I can keep developing the that path. Without it I have to change the code manually each time i want to work in livereload and changing it again when I am not in live reload.

**Comment by sruthakeerthikotla** [comment]
Can this please be merged soon? It would help us implement a feature that we are using right now.

**Comment by liamdebeasi** [comment]
Thanks for the feature request! I discussed this request with the team, and we think that this can already be accomplished by using the environment configurations that various frameworks provide.

For example, Angular provides great build-specific configuration options for your projects: https://angular.io/guide/build. Using this, you could create a config that is only used when running in livereload mode.

Your CLI usage would look something like this: `ionic cordova run android --livereload --configuration=livereload`.
