### ISSUE TITLE
bug: Android 4.4.4 css problems and another log error

### ISSUE THREAD

**Issue by GerardoTovar** [ionic-team/ionic#19303]
**Ionic version:**
[x] **4.x**

**Current behavior:**
install an application on android 4.4.4 and several console errors appear, I don't know if one of them causes me to not display the button css correctly

**Expected behavior:**
I should correctly show the css of the button, I don't know if any of the console errors affect the operation of the application

**Steps to reproduce:**
create a project with the ionic start command and just add a button

**Related code:**

A sample application via GitHub:
https://github.com/GerardoTovar/BugAndroid4

![2019-09-09](https://user-images.githubusercontent.com/35576675/64509336-bda5c680-d29c-11e9-9609-14ec2239672e.png)

```
    <ion-card>
      <ion-card-content>
          <ion-button color="primary" (click)="fb_login()"><b>INICIAR CON FACEBOOK</b></ion-button>
      </ion-card-content>
    </ion-card>
```

**Other information:**
Android 4.4.4
WebView  33.0.0.0

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.7 (C:\Users\L_Z0K\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.6

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.0.0
   OS     : Windows 10


```

**Comment by andypotato** [comment]
@GerardoTovar Just curious why you closed this issue? I'm seeing the same problem on Android 5 devices using the latest version of Ionic.

**Comment by GerardoTovar** [comment]
I assumed that the problem was WebView in android 4.4.4 cannot be updated above 36.0.0.0. in android 5.0 up if it is possible to update WebView .. and read in other posts that ionic no longer supports android 4.4 ... I assumed that in android 5.0 it worked fine it was just a matter of updating the WebView
