### ISSUE TITLE
bug: Text not rendering on screen, it shows after tap

### ISSUE THREAD

**Issue by pateldi1524** [ionic-team/ionic#19301]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I have session timeout functionality in my app so after x minute or second if the app is idle, the user will be logged out from the app and redirected to the login page.
When the session is expired while the app is in the background, then all text/labels are showing blank on-screen until the user tap on the screen.

<br>This is how it looks
![before-tap](https://user-images.githubusercontent.com/28805399/64506668-06d63480-d2f6-11e9-8249-9e7e2d1b7a33.png)

<br>This is after a tap on the screen
![after tap](https://user-images.githubusercontent.com/28805399/64506702-1fdee580-d2f6-11e9-9ab6-16fb97a2811b.png)

**Expected behavior:**

It should render all the text correctly without tap

**Steps to reproduce:**

- Open the app and click the login button
- Press the device home button to put the application in background mode.
- Open the app from background after 20-30 second
- You will see the text is not rendering behind the alert, also after a click on login when you come to the home page, it will show blank initially

**Related code:**

[Here](https://github.com/pateldi1524/ionic-label-missing) git repo with minimum code to reproduce the issue.

**Other information:**

I am testing this on a physical device with android version 7.0

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.0.3
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : android 7.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 18 other plugins)

Utility:

   cordova-res : 0.4.0
   native-run  : 0.2.6

System:

   Android SDK Tools : 26.1.1 (/Users/divyesh/Library/Android/sdk)
   ios-deploy        : 1.9.2
   NodeJS            : v11.4.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by pateldi1524** [comment]
Does no one have a solution for this?

**Comment by liamdebeasi** [comment]
Hi there,

Is this still an issue on the latest version of Ionic Framework?

**Comment by pateldi1524** [comment]
No, with new version its resolved.
