### ISSUE TITLE
Click handler is undefined in production+release build

### ISSUE THREAD

**Issue by Yodio-Jeff** [ionic-team/ionic#19315]
**Ionic version:**
[x] **4.x**

**I'm submitting a ...** 

[ x] bug report
[ ] feature request

**Current behavior:**

In a release build, the compiled code references a non-existent name for a (click) handler.

**Expected behavior:**

debug and release builds should be consistent

**Steps to reproduce:**

The following snippets demonstrate the problem:

HTML

    <ion-list class="scroll-y striped" *ngSwitchCase="'instructor'">
        <ion-item *ngFor="let item of filteredList; let zi = index" (click)="beginReport(item)">
            <ion-label>{{ item.fullName }} - ID: {{ item.id }}</ion-label>
        </ion-item>
    </ion-list>

Component:

    async beginReport(item: Group) {
    } 

Output JS:

    return "click" === n && (t = !1 !== l.component.select(l.context.index) && t), t

This code works in debug builds.  When built with --release, the term "l.component.select" is undefined.  "l.component" corresponds to "this", and all the expected local variables exist.  However, there's no "select" property in the object or the prototype.

**Other information:**

Making one minor change makes the problem go away.  The issue appears to be with the async keyword.  The following runs correctly:

    beginReport(item: Group) {
        beginReport2(item);
    }
    async beginReport2(item: Group) {
    }

Event handlers are asynchronous, so that shouldn't be a concern.  If returning a Promise doesn't produce the correct return type, then it should flag an error instead of generating bad code.

**Ionic info:** 

   Ionic CLI                     : 5.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.7 (update available: 0.2.8)

System:

   NodeJS : v11.5.0 (/usr/local/Cellar/node/11.5.0/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am not able to reproduce this issue using the code snippets provided.
