### ISSUE TITLE
Ionic 4 <ion-input> doesn't support Google places Autocomplete!

### ISSUE THREAD

**Issue by KrishnaBura** [ionic-team/ionic#19320]
**Ionic version:**

[x] **4.x**

**I'm submitting a ...** 

[x] bug report
[] feature request

**Current behavior:**
Cannot use the  Google autocomplete places with <ion-input>. It gives the error as [InvalidValueError: not an instance of HTMLInputElement] when used <ion-input>. **Tried targeting the inner raw input in different ways as mentioned in previous/old solutions but the issue still persists.**

Below is the link for the old closed issue which didn't resolve the problem.

https://github.com/ionic-team/ionic/issues/6700 

**Expected behavior:**
<ion-input> to be responsive/work when using Google places autocomplete.

**Steps to reproduce:**

1. Create a HTML page with <ion-input>
2. It's component.ts file at the init

**Related code:**

```
insert short code snippets here
```@ViewChild("addresstext", { read: ElementRef }) private addresstext: ElementRef;
 ngAfterViewInit() {
    this.getPlaceAutocomplete();
  }
 const autocomplete = new google.maps.places.Autocomplete(
      this.addresstext.nativeElement,
      {
        componentRestrictions: { country: "US" },
        types: ["address"],
      },
    );
```
insert the output from ionic info here
```
Ionic:
   Ionic CLI : 5.1.0
Utility:
   cordova-res : not installed
   native-run  : not installed
System:
   NodeJS : v8.12.0
   npm    : 6.4.1
   OS     : Windows 10

**Comment by visiongeist** [comment]
@KrishnaBura google places works for me. I used to get the native element:

```
private elementRef: IonInput;
const nativeInput = await this.searchElementRef.getInputElement();
```

**Comment by TheCodeLives** [comment]
It is working also for me you can check with the Medium article if you want.

https://link.medium.com/JA4amAHFJ5

**Comment by tostro** [comment]
> It is working also for me you can check with the Medium article if you want.
> 
> https://link.medium.com/JA4amAHFJ5

does this work for ionic 4 too?

**Comment by kelpie278** [comment]
I've tried in ionic4 and it works with no problem.

**Comment by tostro** [comment]
> I've tried in ionic4 and it works with no problem.

Oh yeah it did. 
But the issue I had was in autocompleting address in a form while inputting address. 
Any way to go about that? 
I mean a form that has “enter pickup location” and “enter drop off location”

**Comment by liamdebeasi** [comment]
Hi everyone,

Is this still an issue in the latest version of Ionic Framework?
