### ISSUE TITLE
bug: Page navigation animation not working in iOS on child tab page 

### ISSUE THREAD

**Issue by andreas-aeschlimann** [ionic-team/ionic#19337]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
The iOS navigation animation does not behave as expected when clicking an `<ion-back-button>` on a tab page. 
Imagine an application that has a side menu at startup (or nothing), then navigates to a new page that contains several tabs. 
The navigation animation (slide left) to this tab page is working as expected, but when navigating back to the first page, there is no animation (slide right) on iOS. Instead, the page seems to be freezing for a second and then simply drops back without animation.

**Expected behavior:**
There should be an animation when going back.

**Steps to reproduce:**
- Create a new Ionic project with a simple menu or blank start page
- On any page, add a link to a new page
- On this new page, add tabs with an `<ion-back-button>`

**Related code:**
Example project: https://github.com/andreas-aeschlimann/ionic-page-navigation-animation-test
- Initial commit is the project directly from the CLI
- Second commit is the minimal changes necessary for testing

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.8 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : not installed
   native-run  : 0.2.8

System:

   NodeJS : v10.16.0 (/usr/local/bin/node)
   npm    : 6.11.2
   OS     : macOS Mojave
```

I am not sure if I have done something wrong in the tabs page setup, but for some reason the animation is not working well for me on iOS. I was able to reproduce the issue with Chrome debugging tools "iPhone" or "iPad" as device.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Yeah, it looks like this issue is related to https://github.com/ionic-team/ionic/issues/18181. I am going to close this issue in favor of that one, but I will be sure to link the two together so we have your repo test case. Thanks!
