### ISSUE TITLE
bug: Keyboard Scrolling Issue

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic#19338]
Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

If I have a page that has a bunch of inputs on it in the list, with nothing below it, and I click on the last input or two in the list it will be hidden by the keyboard and will not scroll into the viewable area until I start typing.

But, if I pad out the area under the list of inputs, say with a few paragraphs of cheesy text, I don't have the same issue. In that case, the final input scrolls into view immediately upon clicking it.

It seems like perhaps there is some issue with the code that tries to handle this scrolling, but only if the area that needs to be scrolled to is towards the physical bottom of the page.

**Expected behavior:**

Scrolling would work fine, even in the first scenario.

**Related code:**

https://github.com/kensodemann/test-inputs-scrolling

**Steps to reproduce:**

1. clone
1. npm i
1. ionic cordova build ios
1. run it on a device
1. scroll until "Description" is at the bottom of the screen
1. tap into it to show the keyboard
1. note that the view did not scroll
1. type something
1. now "Description" has scrolled into view

Now uncomment the cheesy text: https://github.com/kensodemann/test-inputs-scrolling/blob/master/src/app/home/home.page.html#L56-L71

Repeat the above steps. When tapping into "Description" to show the keyboard note that the scrolling takes place right away.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.8 (/Users/kensodemann/.nvm/versions/node/v10.16.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (/Users/kensodemann/Library/Android/sdk/)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/Users/kensodemann/.nvm/versions/node/v10.16.3/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8
```

**Comment by Stylemayster** [comment]
I can tell that I keep my app outdated because I've found a combination of package version that doesn't have that bug...

**Comment by rajiramamoorthi** [comment]
Still the above issue exist in iOS devices. 

**Ionic Info:**

Ionic:

   Ionic CLI                     : 5.2.8 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.2
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/apple/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8

**Comment by bryplano** [comment]
Possibly related... this issue is a Cordova app, but this Capacitor one sounds very similar: https://github.com/ionic-team/ionic/issues/16797

**Comment by liamdebeasi** [comment]
Thanks for the issue. This was fixed via https://github.com/ionic-team/ionic/pull/20742 and will be available in an upcoming release of Ionic Framework.
