### ISSUE TITLE
feat: ionic4 How do you implement the navCtrl.remove method?

### ISSUE THREAD

**Issue by C-racker** [ionic-team/ionic#19349]
# Feature Request

**Ionic version:**

[x] **4.9.0**

**Describe the Feature Request**

Google Translate：
Previously, returning any page in ionic3 is the corresponding page that needs to be removed from the stack and can return directly. However, if the corresponding remove method is not found in ionic4, it cannot be returned to any page. I try to use angular router `replaceUrl: true` Method but did not achieve the expected effect, he still can not replace the previous history, simply speaking, I have three pages of ABC, I now open the order A->B->C, currently want to directly from C->A How do you need to achieve this?

**Describe Preferred Solution**

I want something like `this.navctrl.remove();` method

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is more of a support request. I recommend you post your question on our [forums](https://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com).

Thanks!
