### ISSUE TITLE
bug: Searchbar backbutton does not respect config setting

### ISSUE THREAD

**Issue by masimplo** [ionic-team/ionic#19347]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Changing the back-button icon to a different icon than the default `arrow-back`, makes the searchbar back icon inconsistent in design with the rest of the app, since it uses a hard coded value of `md-arrow-back`.
You can set the button in each searchbar explicitly as a workaround, but I think it makes sense for the searchbar back to follow the rest of the app design (I might be wrong)

**Expected behavior:**

The searchbar component back icon (Android only) should be the same as the custom back icon.

**Steps to reproduce:**

Add a custom back icon through the config. 
Add a searchbar component.
The icon hasn't changed.

**Comment by UTSOURCE** [comment]
I also have the same problem.
