### ISSUE TITLE
bug: App close on hardware back button press when video is open in full screen.

### ISSUE THREAD

**Issue by pateldi1524** [ionic-team/ionic#19356]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
I have an HTML video player in my app, 
`<video controls>
                            <source [src]="videoUrl" type="video/mp4">
                        </video>`

Which loads video from device gallery and show in screen.
Video controls have option to open video in full screen. when the video is in full screen, the app closes instead of go back on click on device hardware back button.

**Expected behavior:**
It should close the video full screen and go back to the previous screen.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.0.3
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : android 7.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 18 other plugins)

Utility:

   cordova-res : 0.4.0
   native-run  : 0.2.6

System:

   Android SDK Tools : 26.1.1 (/Users/divyesh/Library/Android/sdk)
   ios-deploy        : 1.9.2
   NodeJS            : v11.4.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by yogeshpatil143** [comment]
Please use the Cordova video player plugin.

URL: https://ionicframework.com/docs/native/video-player

It helps you bro.

**Comment by pateldi1524** [comment]
I wants to display video gallery. which is not possible with the above plugin.

**Comment by yogeshpatil143** [comment]
Hi,

For video gallery, make sure bind thumbnails for interactive view and make sure video plat by click event. 
 That's i guess...

**Comment by josephlodero** [comment]
@pateldi1524  did you find a solution for this?

**Comment by pateldi1524** [comment]
No.

**Comment by pabloroxo** [comment]
I'm facing this problem too. My videos are in the assets folder, it's a video gallery for an interative book app. I've tried [this solution](https://forum.ionicframework.com/t/hardware-back-button-with-ionic-4/137905/26) but didn't work. I'll wait here. Thanks.

**Comment by pabloroxo** [comment]
Another behaviour I noticed:

1 - Open page
2 - Play video
3 - Go fullscreen
4 - Exit fullscreen
5 - Press back button
--> The entire app closes

But if we don't go fullscreen:

1 - Open page
2 - Play video
3 - Press back button
--> The back button works properly

------------------------------------------------------------------------------------

Now I'm using a modal just to store the player:

1 - Open page
2 - Open modal with the video
3 - Go fullscreen
4 - Exit fullscreen
5 - Press back button
6 - Close modal (pressing X button on top right corner)
7 - The page is showed again
8 - Press back button
--> The back button works properly

But if we press back button instead of closing modal:

1 - Open page
2 - Open modal with the video
3 - Go fullscreen
4 - Exit fullscreen
5 - Press back button
--> The entire app closes

**Comment by josephlodero** [comment]
@pabloroxo same problem with me.. but this problem will only happens with API 28 and 29. lower version is working fine

**Comment by Mr-Anonymous** [comment]
I have the same issue. I open Vimeo player that is embedded inside an iFrame through ionic android app and it works fine if the full screen button in the player is not clicked. But when playing the video in fullscreen, if the back button is pressed, it straight away closes the app. Although I have some code for `$ionicPlatform.registerBackButtonAction(function (e) { .. }, 100);`, it seems this event is not even fired and the app gets closed irrespective.

What can be done to get around this problem?

**Comment by clemishow** [comment]
Same here !

**Comment by r0b1337** [comment]
I'm facing the same problem !

**Comment by M-Rizk** [comment]
Any update???
I'm facing the same issue when opening: image, video or html page in full screen mode

**Comment by josephlodero** [comment]
Hi. If you guys using cordova here's a solution https://github.com/apache/cordova-android/issues/822 cheers

**Comment by paulstelzer** [comment]
As @josephlodero mentioned that is an issue with cordova android. There is already a PR, but hasn't merged yet -> https://github.com/apache/cordova-android/pull/823

So we need to hope they will add it soon - I am waiting for it, too :D
