### ISSUE TITLE
bug: @ionic/react IonLoading component does not dismiss correctly

### ISSUE THREAD

**Issue by ithieund** [ionic-team/ionic#19350]
I have to duplicate this issue as no one read the previous closed issue: https://github.com/ionic-team/ionic/issues/19252

**Ionic version:**
"@ionic/react": "^4.8.0-rc.0",

**Current behavior:**
It does not dismiss with setShowLoading(false) after http fetch.
It only work when wrapping inside a timeout :(

**Expected behavior:**
It should dismiss when calling setShowLoading(false); after http fetch

**Steps to reproduce:**
Show the loading and run the http fetch. After the promise resolve or reject, I need to hide the loading

**Related code:**
```
// This will not work
setShowLoading(true);

loadProducts().then((data) => {
    setShowLoading(false);
    console.log('Yaay!', data);
}).catch((e) => {
    setShowLoading(false);
    console.log('Oops!', e);
});

// This will work
setShowLoading(true);

loadProducts().then((data) => {
    setTimeout(() => {
        setShowLoading(false);
    }, 1000);
    console.log('Yaay!', data);
}).catch((e) => {
    setTimeout(() => {
        setShowLoading(false);
    }, 1000);
    console.log('Oops!', e);
});
```

**Other information:**
N/A

**Ionic info:**
```
Ionic:

   Ionic CLI       : 5.2.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.8.0-rc.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3 (/usr/local/Cellar/node/9.5.0/bin/node)
   npm    : 6.10.3
   OS     : macOS Mojave
```

**Comment by elylucas** [comment]
Hi @ithieund,

I would suggest updating to RC2 and see if the problem persists and let us know here. I put together a stackblitz that shows it working here: https://stackblitz.com/edit/ionic-react-loading
