### ISSUE TITLE
bug: react-router cycle

### ISSUE THREAD

**Issue by jsonz1993** [ionic-team/ionic#19351]
A page jumps to page B, and then jumps from page B to page A. At this time, the route will loop.
When you roll back, you will always be on the A and B pages.

version:
```
@ionic/react 4.9.0-rc.2

@ionic/react-router 4.9.0-rc.2

react 16.8.6

react-dom 16.8.6

react-router-dom 5.0.1

```

[online demo](https://codesandbox.io/s/ionic-demo-kclve)

**Comment by jsonz1993** [comment]
May be caused here  [link](https://github.com/ionic-team/ionic/blob/master/packages/react-router/src/ReactRouter/Router.tsx#L94)

In another version, it's working [link](https://github.com/ionic-team/ionic/blob/v4.8.1/packages/react-router/src/ReactRouter/Router.tsx#L117)

**Comment by elylucas** [comment]
Hi @jsonz1993, would you be able to put together a repo or a stackblitz to show the issue?

Thanks

**Comment by jsonz1993** [comment]
Hi @elylucas , I have created a new Repo to show this issues [repo link](https://github.com/jsonz1993/ionic-react-router-issues-19351-demo)

**Comment by elylucas** [comment]
Should be fixed in RC3, give it a try and let us know.
