### ISSUE TITLE
Events not getting called

### ISSUE THREAD

**Issue by PeterHdd** [ionic-team/ionic#19358]
Im doing the following:

```
    this.platform.ready().then(() => 
    {
      window.addEventListener("pause", (event)=>{
         console.log("pause");
      });
  
      window.addEventListener("beforeunload",(event)=>{
          console.log("beforeunload");
      });
    });
```

Im testing the following code on the android phone, and using `chrome://inspect` to check the log. But when I click on the home button and switch to another application or just keep the application running in the background neither the `pause` event nor the `beforeunload` event are getting called.

Ionic info:

```
Ionic:

   Ionic CLI                     : 5.0.1 (C:\Users\sleim\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-webview 3.1.2, (and 13 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v8.11.1 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10`
```

**Comment by PeterHdd** [comment]
This is the output of `navigator.userAgent`:

Mozilla/5.0 (Linux; Android 9; SM-G950F Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36

**Comment by PeterHdd** [comment]
Both `onunload` and `beforeunload` are getting called when using ionic serve and I refresh the browser. But they dont work when I kill the application on a physical device.

**Comment by liamdebeasi** [comment]
Hi there,

Do these events work in a regular cordova app? (I.e. add the event listeners to a page in a standalone Cordova app without any Ionic code).
