### ISSUE TITLE
bug: regression?! Scrolling within a modal dialog will cause the page beneath to also scroll

### ISSUE THREAD

**Issue by wilk-polarny** [ionic-team/ionic#19370]
# Bug Report

**Ionic version:**
[x] **4.9.0**

**Current behavior:**
When scrolling within a modal page, the view of the page beneath will also scroll

**Expected behavior:**
The view beneath should be unaffected

**Steps to reproduce:**
- In an app with Ionic 4.9 and wkwebview plugin >= 4.0.1
- Create a modal dialog with enough content to enable scrolling.
- Scroll, and close the modal.
- You can observe that the page beneath has also scrolled down

**Related code:**
No related code.

**Other information:**
This has always been a problem for us on iOS since Ionic 3. It was fixed in the early Ionic 4 versions, if I recall correctly, but appears again (at least in 4.9).
I'll try to go back to the versions we previously used to find out whether this has ever been fixed.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.8 (/Users/Wilk/.nvm/versions/node/v10.16.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.1.1
   @angular/cli                  : 8.1.1
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 5 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   Android SDK Tools : 25.2.2 (/Users/Wilk/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/Users/Wilk/.nvm/versions/node/v10.16.3/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8
```

**Comment by olivermuc** [comment]
I could have missed it, but I have never seen this fixed.
My workaround: if you have a modal or popover etc that includes scrollable areas, set underlying areas to `overflow:hidden` when they're active/shown. It's a simple workaround but works quite well.

**Comment by wilk-polarny** [comment]
@olivermuc - funny thing is, I cannot reproduce this with - for example - the Ionic conference app (when I add enough items to the schedule filter modal to scroll)

It would be nice to know what is causing this.

--> I'll check out your workaround, thank you - applying `overflow:hidden` to the `ion-content` should be enough?

**Comment by olivermuc** [comment]
I haven't cross checked with other apps but ran into this issue with all my projects. In my case with Popovers, which had scrollable content.
I believe I had read up on the phenomena when I first ran into it and found references to "non-fixable" iOS/(wk)webview related touch/scroll handling...I know this is vague, but it's been a while - and the workaround did the job.
All I do is, set a CSS class on the page element when popover (or modal) get's launched and have CSS control scrollable areas on that page. That CSS class gets removed again when the popover/modal controller triggers an `onDidDismiss` event:
`
  async showFeedbackPopover() {
    this.disableScrolling = true;
    const popover = await this._popoverController.create({
      component: FeedbackPopover,
      componentProps: { ... }
    });
    await popover.present();
    return await popover.onDidDismiss().then((data: any) => {
      this.disableScrolling = false;
    });
  }
`

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by wilk-polarny** [comment]
@liamdebeasi , I'm trying hard to reproduce this with the conference starter, but I can't. Currently I can't spot any difference between the way we create modals and the way they work in the conference app. I'll have to rebuild the structure we're using using a demo app, as I can't post our code anywhere.
I might have missed something and will investigate further once I'm back from vacation.

**Comment by C-racker** [comment]
+1
