### ISSUE TITLE
bug: Side menu animation throwing error on device

### ISSUE THREAD

**Issue by tricki** [ionic-team/ionic#19376]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Trying to open the side menu by swiping throws an error and the apps becomes unresponsive, so does clicking on the backdrop once it's open.

```
Cannot read property 'getComputedTiming' of undefined
```

This error only happens on my phone, not on desktop.

**Expected behavior:**
The menu opens correctly.

**Steps to reproduce:**
Open the sample with Google Chrome 71 on Android.

**Related code:**

Code that throws the error:
```
const setAnimationStep = (step) => {
    step = Math.min(Math.max(step, 0), 0.999);
    if (supportsWebAnimations) {
        getWebAnimations().forEach(animation => {
            // NEXT LINE CAUSES ERROR
            animation.currentTime = animation.effect.getComputedTiming().delay + (getDuration() * step);
            animation.pause();
        });
    }
    else {
        const animationDelay = getDelay() || 0;
        const animationDuration = `-${animationDelay + (getDuration() * step)}ms`;
        elements.forEach(element => {
            if (_keyframes.length > 0) {
                setStyleProperty(element, 'animation-delay', animationDuration);
                setStyleProperty(element, 'animation-play-state', 'paused');
            }
        });
    }
};
```

The `animation` variable:
![image](https://user-images.githubusercontent.com/523154/65056331-f9adeb00-d970-11e9-8fab-480d293bcd0a.png)

Sample application:

http://plnkr.co/edit/RJEGFzi3mnyAf4XSYIKI?p=preview

**Other information:**
The sample code works on my phone in Chrome Canary 79 and Firefox 68 but not in Chrome 71 (Android 9).

**Ionic info:**
```
Ionic:

   Ionic CLI : 5.2.4 (C:\Users\main\AppData\Roaming\npm\node_modules\ionic)

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 14 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (D:\ProgramFiles\Android\sdk)
   NodeJS            : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This issue has been fixed and will be available in the next release of Ionic. In the meantime, here is a dev build you can use that has the fix: `4.10.0-dev.201909061231.2ea728e`

If using Ionic Angular: `npm i @ionic/angular@4.10.0-dev.201909061231.2ea728e`
If using Ionic Core: `npm i @ionic/core@4.10.0-dev.201909061231.2ea728e`

Thanks!
