### ISSUE TITLE
List not scrollable in component

### ISSUE THREAD

**Issue by loanaalbisser** [ionic-team/ionic#19373]
**Ionic version:**

[x] **4.8.1**

**I'm submitting a ...** 

[ x] bug report
[ ] feature request

**Current behavior:**

List in component on a page not scrollable with fingertip. Only with mouse-wheel. 
The list is only scrollable when directly used on a page and not in a component. 

**Expected behavior:**

List is scrollable

**Steps to reproduce:**

- add component with ion-list
- add component to page

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am not able to reproduce the issue given the information you have provided.

**Comment by loanaalbisser** [comment]
The issue was that I used press and click event on the list-item. This prevent the list from scrolling.
