### ISSUE TITLE
bug: If one ion-item[position=floating] is be at ion-list has unnecessary border.

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic#19379]
# Bug Report
If one ion-item[position=floating] is be at ion-list has unnecessary border. When two ion-item is set, unnecessary border is none. It is ios only.

**Ionic version:**
[x] **4.9.1**

**Current behavior:**
![スクリーンショット 2019-09-18 10 13 08](https://user-images.githubusercontent.com/9690024/65096803-388b8180-da01-11e9-93c2-a4ff1d1d20f7.png)
![スクリーンショット 2019-09-18 10 13 17](https://user-images.githubusercontent.com/9690024/65096804-388b8180-da01-11e9-9c92-9dec4586e35e.png)

**Expected behavior:**
No unnecessary border.

**Steps to reproduce:**

**Related code:**

```
    <ion-list>
      <ion-item>
        <ion-label position="floating">タスク</ion-label>
        <ion-input type="text"></ion-input>
      </ion-item>
    </ion-list>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.7 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.2.0
   @capacitor/core : 1.2.0

Utility:

   cordova-res : 0.6.0 
   native-run  : not installed

System:

   NodeJS : v10.16.2 (/usr/local/bin/node)
   npm    : 6.10.3
   OS     : macOS Mojave
```

**Comment by brandyscarney** [comment]
Thanks for the issue! Are you able to reproduce this in Chrome or Safari or only on an iOS device?

**Comment by rdlabo** [comment]
@BrandonShar Thanks for reply. I confirmed at developer tool of Google Chrome.

**Comment by brandyscarney** [comment]
@rdlabo Could you please try to reproduce it in a Codepen? Here's one that you can fork and use: https://codepen.io/pen?template=aXENNW

**Comment by rdlabo** [comment]
I created, and I get it.
https://codepen.io/rdlabo/pen/ExYJGvz

Sorry. This phenomenon seems to occur only with `iPhone6/7/8 Plug` at Google Chrome. not Safari. This may not problem.
I will close this issue.
