### ISSUE TITLE
bug: IonModal doesn't properly close if unmounted from parent

### ISSUE THREAD

**Issue by ebk46** [ionic-team/ionic#19377]
# Bug Report

**Ionic version:**
[x] **4.9.0-rc.2**

**Current behavior:**
When a modal is closed via the parent, the content of the modal is removed but the modal stays on the page as a white screen overlaying everything.

**Expected behavior:**
The modal should disapepar.

**Steps to reproduce:**
1. Render modal from parent with conditional
2. Set conditional to false
(see stackblitz)

**Related code:**

https://stackblitz.com/edit/ionic-v4-react-rc2-modalbug

**Other information:**
This is also probably related to another bug where the modal doesn't close if you press "back" in the browser. The parent page will change but the modal turns white and stays as an overlay in the exact same way as this issue. It feels like both are because removing it from the dom isn't cleaning up properly.

**Ionic info:**
```
Ionic:

   Ionic CLI       : 5.2.8 (/Users/evan/.config/yarn/global/node_modules/ionic)
   Ionic Framework : @ionic/react 4.9.0-rc.2

Capacitor:

   Capacitor CLI   : 1.2.0
   @capacitor/core : 1.2.0

Utility:

   cordova-res : 0.6.0
   native-run  : not installed

System:

   NodeJS : v12.6.0 (/usr/local/Cellar/node/12.6.0/bin/node)
   npm    : not installed
   OS     : macOS High Sierra
```

**Comment by elylucas** [comment]
Thanks for the issue, and the great reproduction of it in the stackblitz, that helps immensely. This has been fixed and will be in the next release.
