### ISSUE TITLE
bug: I am unsure if this is a bug or not. But Vanilla JS routing using ionic is slow at first on the web (using Firebase hosting)

### ISSUE THREAD

**Issue by Bandito11** [ionic-team/ionic#19389]
Hi

I been using ionic core using Vanilla JS on Stencil. When going from page to page or opening a modal page (using the ionic core Routing module) it is really slow at first when on the web (doesn't happen locally). If you go to my app you could see what I mean https://millefollium.web.app (it is hosted on Firebase)

You will notice that at first tranversing through the pages and opening the modal is slow at first. But after that first time any time you open the same modal or go from the home page to the next page the pages open way faster. If I close and open a tab and go to the web page it works as expected but if I clear the cache the same thing happens again. Any info about this?

**Comment by manucorporat** [comment]
Components are lazy loaded when first used, this might explain why, you can create bundlers of components in the stencil.config.ts
