### ISSUE TITLE
bug: IonMenu's backdrop not displayed on iOS after upgrade from 4.8.1 to 4.9.0/4.9.1

### ISSUE THREAD

**Issue by maxtacco** [ionic-team/ionic#19387]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Ionic menu has no backdrop when opened on iOS since version 4.9.0

**Expected behavior:**
Ionic menu should have backdrop

**Other information:**
Android is fine. Works fine using 4.8.1

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.4 (/Users/[user]/.nvm/versions/node/v10.15.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : no whitelisted plugins (3 plugins total)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8
```

**Comment by maxtacco** [comment]
This can be related to https://github.com/ionic-team/ionic/issues/19271

**Comment by maxtacco** [comment]
It looks like both "overlay" and "push" menu types work fine on iOS (tested in Chrome). But, using "reveal" produces the issue. On Android, only "overlay" works fine, both "reveal" and "push" don't add the backdrop.

**Comment by tricki** [comment]
I have a similar problem where nothing in the menu is clickable on iOS because the `ion-content`'s `.transition-cover` overlays it.

Plunker: https://next.plnkr.co/edit/83Qz2MFr8B8lD4cc?preview

This demo forces iOS mode. Just open the menu and inspect any menu item which will wrongly select the following element:
![image](https://user-images.githubusercontent.com/523154/65263716-770e6280-db0d-11e9-9dc5-20288cb8de85.png)

```
Ionic:

   Ionic CLI : 5.2.4 (C:\Users\thomas\AppData\Roaming\npm\node_modules\ionic)

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 14 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (D:\ProgramFiles\Android\sdk)
   NodeJS            : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.11.3
   OS                : Windows 10
```

**Comment by VIMHaos** [comment]
Same problem on iOS after upgrade from 4.8.1 to 4.9.0/4.9.1

**Comment by liamdebeasi** [comment]
@tricki Can you open a separate issue for this?

I can reproduce the original issue. We will look into it and will post here when we have more to share. Thanks!

**Comment by liamdebeasi** [comment]
Thanks! This issue has been fixed and will be available in the next release of Ionic.

**Comment by maxtacco** [comment]
@liamdebeasi Thank you for a quick turnaround!

**Comment by calvinckho** [comment]
this is to confirm that @ionic/core 4.10.0 have fixed it.
