### ISSUE TITLE
.scss animation broken on ios when leave page and come back to page

### ISSUE THREAD

**Issue by ASHBAW** [ionic-team/ionic#19385]
I have an ionic 4 application where my main page has a row of blinking circles (LEDs) that give state information. The animated circles where created in the main page's .scss. When the application is launched the animation is working. I then leave the main page and go to another page. When I return to the main page the animation (circles - blinking) is no longer working. This ONLY occurs on ios devices. Android devices work correctly. I was able to create a simple ionic project that demonstrates this. You can see it in the following repo:

https://github.com/ASHBAW/animation.git

I have seen this issue on a iPhone 7 running 12.4.1.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Unfortunately, this is actually a bug in Safari. Animations are freezing in shadow roots when the layout is invalidated, which is the issue you are seeing here.

We have reported this issue to the WebKit team, so hopefully they can address it soon. Thanks!

**Comment by ASHBAW** [comment]
Thanks
