### ISSUE TITLE
bug: IonRouterOutlet seems to fall through even after finding a valid route

### ISSUE THREAD

**Issue by ebk46** [ionic-team/ionic#19392]
# Bug Report

**Ionic version:**

[x] **@ionic/react@4.9.0-rc.2**

**Current behavior:**
When assembling routes, if multiple routes match the URL, they are all rendered to the page simultaneously.

**Expected behavior:**
The only page rendered should be the first route that matches the URL. Falling through should not happen in that case.

**Steps to reproduce:**
The easiest way to reproduce is with a "Not Found" route that matches anything. This is included in the Stackblitz below.

**Related code:**
https://stackblitz.com/edit/ionic-v4-react-router-notfound

**Other information:**
This was encountered when trying to implement a "Not Found" page but is relevant in multiple use cases. 

**Ionic info:**
```
Ionic:

   Ionic CLI       : 5.2.8 (/Users/evan/.config/yarn/global/node_modules/ionic)
   Ionic Framework : @ionic/react 4.9.0-rc.2

Capacitor:

   Capacitor CLI   : 1.2.0
   @capacitor/core : 1.2.0

Utility:

   cordova-res : 0.6.0
   native-run  : not installed

System:

   NodeJS : v12.6.0 (/usr/local/Cellar/node/12.6.0/bin/node)
   npm    : not installed
   OS     : macOS High Sierra
```

**Comment by elylucas** [comment]
Hi @ebk46,

The IonRouterOutlet handles the rendering and lifetime of the pages, but it needs the routes to render an <IonPage> eventually. If you update your pages to have IonPages as the root element and not divs, it behaves as expected:

https://stackblitz.com/edit/ionic-v4-react-router-notfound-tk7mdw

Let me know if that helps.

Thanks

**Comment by ebk46** [comment]
Apologies for the flawed Stackblitz - my code has a bug with this functionality and I am using <IonPage> properly. The specific bug I have is very difficult to reproduce, but the summary is that if I have a <Route path="/" component={NotFound}/> as my last route, a "Go back Home" button that exists on that NotFound page is present but not visible from my Login screen, and it seems to disable my "Login" button.

That said, I was able to reproduce one variation of this bug here: 
https://stackblitz.com/edit/ionic-v4-react-router-notfound-2

As you can see in that Stackblitz, clicking "Bye" or "Hello" routes to the proper page, but as soon as you get to the "NotFound" route, it never de-renders it even if the URL changes to match the "Bye" or "Hello" routes. Should I make a new ticket for this? I believe it's all intertwined.

**Comment by elylucas** [comment]
Thanks, think I found the culprit and it will be in next release.
