### ISSUE TITLE
bug: IE11 Polyfill for CSS Variables Either Missing or Not Working

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic#19400]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
CSS variables are applied on all browsers on Windows with the exception of IE 11.

**Expected behavior:**
Styling works properly on IE11.

**Steps to reproduce:**

1. get a Windows machine if you don't already have one... :)
1. clone the app below on your Windows machine
1. npm i, npm serve, etc
1. load app in Chrome, Edge, and IE11

Note that the paragraph in Chrome and Edge is blue.

In IE 11, it is still black, and the styling of the header bar is also messed up.

**Related code:**

https://github.com/jeremyknight-me/ionic-css-test

This is a blank starter with the following CSS defined in `home.page.scss`

```
p {
    color: var(--ion-color-primary);
}
```

I also had a peek at the `polyfills.ts` file and everything appears to be in order there.

**Ionic info:**

```
   Ionic CLI                     : 5.2.5 (C:\Users\ken\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.9.1
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.11.3
   OS     : Windows 10

```

**Comment by kensodemann** [comment]
Closing as this is now irrelevant.

**Comment by kensodemann** [comment]
Original repo was deleted for some reason...
Recreated here: https://github.com/kensodemann/ionic-css-test

Reopening for a bit as it was stated that _maybe_ something could be done here, but not sure.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as we recently released Ionic Framework v5 which dropped support for IE11 and older versions of Edge. Moving forward, Ionic Framework v4 will only receive critical security patches.
