### ISSUE TITLE
feat: box-shadow to menu (menu-pane-visible)

### ISSUE THREAD

**Issue by jdnichollsc** [ionic-team/ionic#19414]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
I want to be able to set `box-shadow` when the menu is opened (for menu-pane-visible class).

**Describe Preferred Solution**
Is possible to know if the style/prop for **box-shadow** was applied to use instead of default style `none !important`? https://github.com/ionic-team/ionic/blob/master/core/src/components/menu/menu.scss#L129

Thanks in advance!

**Comment by liamdebeasi** [comment]
Thanks for the feature request. This will be resolved when we ship support for CSS Shadow Parts in Ionic Framework.

When this feature ships, you will be able to do:

```css
ion-menu::part(container) {
  box-shadow: 4px 0px 16px rgba(255, 0, 255, 0.18);
}
```

We plan on shipping support for this soon, and we will be providing more usage docs for this.
