### ISSUE TITLE
feat: add on disable click to components.

### ISSUE THREAD

**Issue by distante** [ionic-team/ionic#19415]
**Ionic version:**
[x] **4.7.1**

**Describe the Feature Request**
Add a ionOnDisabledClick event.

**Describe Preferred Solution**
When the user clicks a disabled component, an `ionOnDisabledClick` event should be triggered.

** Alternative **
Manually mock the disabled css style and toggle the logic inside the ionOnClick event.

**Additional Context**
In most apps, when we decide to show a component that is disabled it is an indication that somethings needs to be changed in another part of the app for the user to be able to use the disabled component. If an on disabled click event is available we can trigger some action that leads the user to the correct part of the app that needs to be changed.

**My Use case as example:**
I have a Fab button containing player controls (play, fwd, pause). This Fab is disabled if the user did not selected an audio file to reproduce. Currently if the user clicks the disabled FAB nothing happens. If an on disabled click event were available I would trigger a flash text saying "Please select an audio file to enable the music player"

**Comment by liamdebeasi** [comment]
Thanks for the feature request! Having a click event emitted on a disabled component kind of defeats the purpose of a having a disabled state, so I don't think this is something we are going to implement right now.

Thanks!

**Comment by distante** [comment]
Fair enough. In the angular project that I use in my work we have a "blocked" with "blockedReason" and I wanted to implement something similar with my ionic app.

Thanks anyway.
