### ISSUE TITLE
bug: IonInfiniteScroll not working

### ISSUE THREAD

**Issue by joshuafriso** [ionic-team/ionic#19426]
Hi, 

I tried do this tutorial in Ionic Framework 4.9.1 but the IonInfiniteScroll give me the error:

Expected 2 arguments, but got 1.ts(2554)
core.d.ts(8436, 47): An argument for 'opts' was not provided.

How I can correct this?

![image](https://user-images.githubusercontent.com/17890321/65425649-d8238800-dde4-11e9-90cb-7328e2782164.png)

![image](https://user-images.githubusercontent.com/17890321/65425685-e8d3fe00-dde4-11e9-8d79-cdea64e7e1c5.png)

![image](https://user-images.githubusercontent.com/17890321/65425696-f5585680-dde4-11e9-9f92-7bb75020c664.png)

**Comment by FernetB** [comment]
try this @ViewChild(IonInfiniteScroll, { static: false }) infinite: IonInfiniteScroll;

With angular 8 the decorator ViewChild changed and now takes 2 arguments insteads of 1.

https://angular.io/api/core/ViewChild

**Comment by joshuafriso** [comment]
Thanks, it's work
