### ISSUE TITLE
bug: Android app can't load resources

### ISSUE THREAD

**Issue by Zerokk** [ionic-team/ionic#19425]
# Bug Report

**Ionic version:**
5.2.5

**Current behavior:**
Build the app, and install the APK in the phone (Xiaomi Pocophone, Android 9). After this, when the app is opened, it just shows a blank screen. When inspected with Chrome DevTools/Remote Devices, it shows the following errors:

![errors](https://user-images.githubusercontent.com/10697745/65423144-a3c1c300-de08-11e9-8aee-0b18df77d2ed.PNG)

This ONLY happens in the **Android build**. In the web build that is used in `ionic serve`, it works perfectly.

**Expected behavior:**
It should open the app as normal. 

**IMPORTANT:** The app was working as expected in this phone, and also in an older, worse phone (although with some performance issues). But when I installed the Firebase FCM plugin, both the Ionic Native package and the Cordova plugin, also having put the `google-services.json` file in the `platforms/android/app` folder, it just started doing this behavior.

**Steps to reproduce:**
Installing the Firebase FCM plugin, both Ionic package and Cordova plugin. Also, setting up the google-services.json file. That's all the changes that led this app to stop working.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.5 (C:\Users\zerok\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.3.0
   @angular/cli                  : 7.1.0
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 14 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : not installed

System:

   NodeJS : v11.8.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.5.0
   OS     : Windows 10
```

**Comment by Zerokk** [comment]
I tried [the solutions suggested in this issue](https://github.com/ionic-team/starters/issues/451), but they just don't work.

I don't wanna be burdensome to the Ionic Dev team, but this is _quite_ urgent. And it also deeply worries me to find a different Ionic/Cordova bug almost each day, even more this time, since I can't find any info about this bug and some people are even whinning about it in the previously linked topic. 

Being this said, all help is welcome.

**Comment by FernetB** [comment]
Currently you have the 4.0.0 version of ionic Framework
5.2.5 is the CLI version.

Could you check if your problem was already solved in any of the updates? 

https://ionicframework.com/docs/release-notes

Ionic is currently in the 4.9.1 version.

**Comment by Zerokk** [comment]
Hello @FernetB !

I was going to post an update on the topic just as you posted this. It does not seem to be the central issue, since now I managed to get it working doing the linked solution again.

**Comment by FernetB** [comment]
Perfect my friend!

Still i recommend you to check the releases notes once in a while for seeing if any of your problems was already solved it in any of the updates.

Cheers!

**Comment by Zerokk** [comment]
You're right with that!

Anyways, in case somebody else falls into this annoying issue, [I recommend following these steps](https://github.com/ionic-team/starters/issues/451#issuecomment-459878855), not skipping any of them. It worked for me already twice.

Still, it's good to notice to @IonicProSupport that some Cordova plugins are causing this when installed. The FCM or generic Firebase plugins are one of those: when installed, they (sometimes) cause this error to happen, making the app unable to be loaded in Android. The only fix I could found for this, is indeed the one above.
