### ISSUE TITLE
Data Grid for Ionic 4

### ISSUE THREAD

**Issue by kyawswarthwin** [ionic-team/ionic#19433]
Can any one implement Data Grid for Ionic 4 like Kendo UI Grid?

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17629.

**Comment by rtpHarry** [comment]
You can use Angular grids in Ionic, for example I got this working in a clients project: https://github.com/swimlane/ngx-datatable
