### ISSUE TITLE
using @Prop with name "mode" results in NaN or "md" value in production build

### ISSUE THREAD

**Issue by FelschR** [ionic-team/ionic#19435]
**Stencil version:**
```
 @stencil/core@1.4.0
```

**I'm submitting a:**
[x ] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Using a @Prop in an component with name `mode` results in the property having a `NaN` or `"md"` value. In case of setting it to a numeric value it results in `NaN` and in case of a string it's `"md"`.
With the dev build it's working fine and once I change the variable name to something else it's also working with the production build.

**Expected behavior:**
Using a property with name `mode` should also work in production mode or at least behave in the same way as the development mode. In case `mode` shall stay a reserved name there should be a build error or warning.

**Steps to reproduce:**
Add a property named `mode` to a component and check its value in dev & prod builds:
```ts
@Prop() mode = 0; // results in NaN
@Prop() mode = "test"; // results in "md"
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
