### ISSUE TITLE
bug: Components stop working with keep-alive

### ISSUE THREAD

**Issue by Livijn** [ionic-team/ionic#19445]
# Bug Report

**Ionic version:**
[core] **4.6.2**
[vue] **0.0.9**

**Current behavior:**
When using [`keep-alive`](https://vuejs.org/v2/api/#keep-alive) some components break. The first time the component renders it works, but when it re-renders it doesn't. Here's a gif showing what happens with `ion-item-sliding`: https://gyazo.com/d2944977f8a25ddcf054fe935b3359c1

**Expected behavior:**
You should still be able to swipe.

**Comment by manucorporat** [comment]
Please, can you fill the issue template specifying which version of ionic you are using?

**Comment by Livijn** [comment]
Done

**Comment by manucorporat** [comment]
Can you update to the latest version of ionic?

**Comment by Livijn** [comment]
Updating to the latest version fixed it for me. Thanks.
