### ISSUE TITLE
bug: Capacitor install cordova plugin salesforce

### ISSUE THREAD

**Issue by jsitu** [ionic-team/ionic#19451]
# Bug Report

**Ionic version:**

[x] **4.7.4**

**Current behavior:**

iOS won't build after installing salesforce Cordova plugin

**Expected behavior:**

iOS should build successfully and be compatible with salesforce Cordova plugin. If I used Ionic 3 and this Cordova plugin works just fine.

**Steps to reproduce:**

1. Run `ionic cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin.git`
2. Run `npx cap sync`
3. Run `npx cap open ios`

Clean and build the project and got below error:

<img width="1398" alt="Screen Shot 2019-09-25 at 3 10 13 PM" src="https://user-images.githubusercontent.com/3535345/65632314-5d569a80-dfa7-11e9-9ed4-76754bdea9a9.png">

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.3.0 (/Users/johnnysitu/.nvm/versions/node/v10.16.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/johnnysitu/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.16.0 (/Users/johnnysitu/.nvm/versions/node/v10.16.0/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I would recommend contacting the plugin author as Ionic Framework does not manage any of the Cordova plugins. Thanks!
