### ISSUE TITLE
bug: progress bar stops animation when navigating back from another page (only on ios)

### ISSUE THREAD

**Issue by Horst1102** [ionic-team/ionic#19456]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
A progress bar (ion-progress-bar) stops moving (indeterminate) when navigating to another page and going back to the previous page (the one with the progress bar). This happens only on android - it works on android and in the web.

**Expected behavior:**
ion-progress-bar is animating

**Steps to reproduce:**
Insert a ion-progress-bar to your page. Open a new page from the page. Go back to the previous page using the back button. The progress-bar will stop animating.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.4.1
   Ionic Framework               : @ionic/angular 4.9.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.2.1
   @capacitor/core : 1.2.1

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.7

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Unfortunately, this is actually a bug in Safari. Animations are freezing in shadow roots when the layout is invalidated, which is the issue you are seeing here.

We have reported this issue to the WebKit team, so hopefully they can address it soon. Thanks!

**Comment by DavidStrausz** [comment]
@Horst1102 You can try to force a repaint like described [here](https://stackoverflow.com/questions/3485365/how-can-i-force-webkit-to-redraw-repaint-to-propagate-style-changes).

**Comment by liamdebeasi** [comment]
^ If you are going to use JavaScript to force a repaint, I'd also recommend wrapping it in a `requestAnimationFrame` to try and avoid any jank.

**Comment by Horst1102** [comment]
> @Horst1102 You can try to force a repaint like described [here](https://stackoverflow.com/questions/3485365/how-can-i-force-webkit-to-redraw-repaint-to-propagate-style-changes).

I really do not understand what to do.
