### ISSUE TITLE
bug: Back button disappears after tapping tab twice

### ISSUE THREAD

**Issue by Horst1102** [ionic-team/ionic#19455]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
If you tap twice on a tab in a tabbar and then open a new page from within this tabpage (like from a list or from a button) the opened page has no back button. This behaviour can be seen even when you open a page twice from a side-menu.

**Expected behavior:**
The opened page has a back button.

**Steps to reproduce:**
Tap twice on a tab in a tab bar or open a page from a side menu and then open the side menu again and open the same page again. Then open a page from the selected page.

You can just use the ionic tab starter, add a new page and navigate to this new page from within one tab. It will work, but if you go back and tap another time on the tab and then open the new page the back button is disappeared.

**Other information:**

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 5.4.1 
   Ionic Framework               : @ionic/angular 4.9.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.2.1
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 10 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.7

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.11.2
   OS     : Windows 10
```

**Comment by DavidStrausz** [comment]
I think you need to explicitly set the nav-direction to `forward` before navigating in a tab. 
This is because the second time you click on the tab-button, internally the nav-direction is set to `root` and when you navigate to your sub-page there is no history to navigate back to, which is why the `ion-back-button` is not visible.

**Comment by ctfrancia** [comment]
I think David is right. Are you somehow setting a new root?

**Comment by Horst1102** [comment]
I open the page like this: 
```
itemSelected(item) {
        const navigationExtras: NavigationExtras = {
            state: {
                belegArt: item.art,
                beleg: item.beleg
            }
        };
        this.router.navigateByUrl('menu/tabs/tabs/activityTab/belegPage', navigationExtras);
    } 
```

And in the new Page.html the backButton is implemented like this:

```
 <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button defaulthref="" text="Aktivitäten"></ion-back-button>
    </ion-buttons> 
</ion-toolbar>
```

And in the corresponding .ts i get the parameters from navigationextras:

```
this.route.queryParams.subscribe(params => {
            if (this.router.getCurrentNavigation().extras.state) {
                this.belegArt = this.router.getCurrentNavigation().extras.state.belegArt;
                this.beleg = this.router.getCurrentNavigation().extras.state.beleg;
                this.title = this.belegArt + ' ' + this.beleg;
            }
        }); 
```


How should I do it correctly?

**Comment by DavidStrausz** [comment]
Before you call `navigateByUrl` you have to import Ionics `NavController` and call the `setDirection` method with the value `forward` like this:

```
import { NavController } from '@ionic/angular';

constructor(private navCtrl: NavController) {}

itemSelected(item) {
 ...
 this.navCtrl.setDirection('forward');
 ...
 this.router.navigateByUrl(...);
 ...
}
```

**Comment by Horst1102** [comment]
Thanks man! That is the solution!
