### ISSUE TITLE
bug: Android USES ios style scrolling problem

### ISSUE THREAD

**Issue by C-racker** [ionic-team/ionic#19465]
# Bug Report

**Ionic version:**

[x] **4.x，3.x**

**Current behavior:**

Android's ios-style scroll interface has a 1px scrolling distance

I don't want to scroll when I don't have a scrollable distance

**Other information:**

![bug3](https://user-images.githubusercontent.com/20217449/65740694-32418780-e11c-11e9-85d1-ce413c36d60a.gif)

**Comment by liamdebeasi** [comment]
Thanks! This issue has been resolved and will be available in an upcoming release of Ionic.
