### ISSUE TITLE
Ionic 4 App freeze when open popover.

### ISSUE THREAD

**Issue by kyawswarthwin** [ionic-team/ionic#19467]
App freeze when open popover without showing any error log in console.

ionic info

Ionic:

   Ionic CLI                     : 5.2.8 (C:\Users\Kyaw Swar Thwin\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.9.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

System:

   Android SDK Tools : 26.1.1 (C:\Android\sdk)
   NodeJS            : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10

**Comment by DavidStrausz** [comment]
Duplicate, see #19277, #19302 
It is already fixed on master and will be in the next release :)
