### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic#19461]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When applying a dark mode, ion-range shows a white square around the knob when disabled.

**Expected behavior:**

The knob outline should not be visible. It seems the range-knob has an outline hard-coded to `#fff`. It should use the variable `--ion-background-color` instead or something similar.

**Steps to reproduce:**
See the codepen here
https://codepen.io/mhartington/pen/NWKmdEp

![Screen Shot 2019-09-26 at 12 34 46 PM](https://user-images.githubusercontent.com/2835826/65707202-0bbb1800-e05a-11e9-85d0-647c2e6e9b65.png)

**Ionic info:**

```
$ ionic info

Ionic:

   Ionic CLI                     : 5.4.1 (/Users/mhartington/n/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.10.0-dev.201909252008.cf223e4
   @angular-devkit/build-angular : 0.900.0-next.5
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 9.0.0-next.5
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.3 (cordova-lib@9.0.2)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.1 (update available: 0.2.8)

System:

   Android SDK Tools : 26.1.1 (/Users/mhartington/Library/Android/sdk)
   ios-deploy        : 2.0.0
   ios-sim           : 7.0.0
   NodeJS            : v12.7.0 (/Users/mhartington/n/bin/node)
   npm               : 6.10.0
   OS                : macOS Catalina
   Xcode             : Xcode 11.0 Build version 11M392r
```

**Comment by kerosin** [comment]
relates to https://github.com/ionic-team/ionic/issues/17549

**Comment by mhartington** [comment]
Closing in favor of  #17549
