### ISSUE TITLE
bug: Menu reveal issues with large title

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic#19483]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

On iOS, when there's menu and the large title is still visible, you can see the menu content when the menu is closed for a moment.

**Expected behavior:**

The menu content should not be visible.

**Steps to reproduce:**

**Related code:**

Apply this PR to the conference app and go to the schedule page to see the issue.

Here is the same issue in Star Track
https://www.youtube.com/watch?v=Dwq5tvDOJ18&feature=youtu.be

**Comment by liamdebeasi** [comment]
Sorry, tagged the wrong issue 😄
