### ISSUE TITLE
bug: ion-footer or ion-header prevent scroll on ion-content when page is opened as popup.

### ISSUE THREAD

**Issue by martinlombana** [ionic-team/ionic#19492]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Open Popup with a header OR footer.
<ion-content> does not scroll with mousewheel on chrome.

**Expected behavior:**
Being able to scroll.

**Steps to reproduce:**
Create a popup with this template :

`        <ion-header>

	        <ion-label>sdsds</ion-label>
	        
                <ion-button expand="block" appNoDoubleClick color="light"
                            class="ion-padding-horizontal">{{'generic.SAVE' | translate | uppercase}}</ion-button>

	        
        </ion-header>

        <ion-content color="primary">

	        <ion-list>
		        <ion-item *ngFor="let item of [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]">
			        <ion-label>Whaat? {{item}}</ion-label>
		        </ion-item>
	        </ion-list>

        </ion-content>

        <ion-footer>

	       
	        <ion-toolbar> <ion-label>sdsds</ion-label></ion-toolbar>

        </ion-footer>
`

Invoke it:
```
public async open_postal_code_search() {

		const modal: HTMLIonModalElement =
			await this.modalCtrl.create({
				component: PostalCodeSearchModal,
				componentProps: {}
			});

		modal.onDidDismiss().then((detail) => {
			if (detail !== null) {
				console.log('The result:', detail.data);
			}
		});

		await modal.present();
	};
``` 

Try to scroll with the mousewheel on chrome (latest version). 

Then remove the ion-header and ion-footer, and it works.

```
insert the output from ionic info here
```
Ionic:

   Ionic CLI                     : 5.2.6 (C:\Users\marti\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.10.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 0.2.6

System:

   Android SDK Tools : 26.1.1 (C:\Users\marti\AppData\Local\Android\sdk)
   NodeJS            : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.11.2
   OS                : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?
