### ISSUE TITLE
bug repeat:  Ionic 4.10.0, page will flash when navigate back sometimes.

### ISSUE THREAD

**Issue by netsesame2** [ionic-team/ionic#19491]
Bug Report
Ionic version:

[x] 4.10.0

I'v even post a bug to report the same isssue in ios: https://github.com/ionic-team/ionic/issues/19170#issue-484618988, which is resolved in a dev patch.

Current behavior:
However, when update to latest 4.10.0, the same issue raised again. This time is in android.
Sometimes, page will flash when navigate back, not always.

I test it in android device and emulator, android 8 and 9. 

Degrade @ionic/angular to 4.9.0-dev.201908231742.f2cfdf14.7.4, it will disappear.

Expected behavior:

Steps to reproduce:

Use navigation to push a page, then close it use back-button. sometimes a flash will appear.

Related code:
``
Use <ion-back-button></ion-back-button> to navigate back.
``
Other information:

I take a video to watch what happens. when slow down the video frame, I can see that when click back-button, the current page transit to dismiss, then suddenly appear half a second, then dismiss again, so in normal speed, we can see a flash.
Ionic info:

Ionic CLI                     : 5.4.1
Ionic Framework               : @ionic/angular 4.10.0
@angular-devkit/build-angular : 0.803.5
@angular-devkit/schematics    : 8.3.5
@angular/cli                  : 8.3.5
@ionic/angular-toolkit        : 2.0.0

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide more details on how to reproduce this? I am using `ion-back-button` to navigate back from a page on an Android device, but I am unable to reproduce this issue.

**Comment by liamdebeasi** [comment]
Never mind, I was able to reproduce now using a different device. I will investigate this and post more info here when I have it. Thanks!

**Comment by liamdebeasi** [comment]
Can you try this dev build and let me know if this fixes the issue for you? `npm i @ionic/angular@4.11.0-dev.201910041827.7768ab2`

**Comment by netsesame2** [comment]
Thanks, it is resovled in the latest patch.

**Comment by liamdebeasi** [comment]
Thanks! This issue has been fixed and will be available in the next release of Ionic.

**Comment by C-racker** [comment]
> Thanks! This issue has been fixed and will be available in the next release of Ionic.

4.11 The problem is still
