### ISSUE TITLE
bug: [4.10.0] Cannot use firebase analytics

### ISSUE THREAD

**Issue by Anthony2539** [ionic-team/ionic#19506]
# Bug Report

**Ionic version:**
Ionic:

   Ionic CLI                     : 5.4.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.10.0
   @angular-devkit/build-angular : 0.802.2
   @angular-devkit/schematics    : 8.3.6
   @angular/cli                  : 8.3.6
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 7.1.0
   Cordova Platforms : ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 12 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : not installed

System:

   ios-deploy : 1.9.2
   ios-sim    : 8.0.2
   NodeJS     : v11.8.0 (/usr/local/bin/node)
   npm        : 6.11.3
   OS         : macOS Mojave
   Xcode      : Xcode 11.0 Build version 11A420a
[x] **4.10.0**

**Current behavior:**
I have installed the firebase analytics native plugin, but when i build my app in Xcode, i have this error:

No known class method for selector 'resetAnalyticsData'

**Expected behavior:**
Firebase analytics, is it compatible with ionic 4.10.0 ?

**Comment by liamdebeasi** [comment]
Thanks for the issue. I would recommend contacting the firebase plugin author. Ionic Framework does not manage any of the native Cordova/Capacitor plugins, so it's possible something with your configuration is incorrect or there is a bug in the plugin.
