### ISSUE TITLE
bug: new sidemenu app will not run properly on Android 5.1

### ISSUE THREAD

**Issue by henkkelder** [ionic-team/ionic#19518]
# Bug Report

**Ionic version:**

[x] **4.10.0**

**Current behavior:**
Running a new sidemenu app on Android 5.1 starts ok, but clicking generates errors:

- Uncaught TypeError: undefined is not a function in 40-es5.js:171
- Uncaugh TypeError: undefined is not a function in ion-menu 4-md.entry.js:147

The latter occurs on each click.

**Expected behavior:**
Clicks/taps should not give errors and should be handled properly.

**Steps to reproduce:**
Generate new sidemenu app and run on Android 5.1

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.5 (C:\Users\henkkelder\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.10.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 5.0.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 21 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.5

System:

   Android SDK Tools : 26.1.1 (C:\Users\henkkelder\AppData\Local\Android\Sdk)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.11.2
   OS                : Windows 10```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you testing this on a physical device or a simulator? Additionally, can you provide the user agent of the device you are testing on? You can find this by logging `navigator.userAgent` in the Chrome dev tools.

**Comment by henkkelder** [comment]
Emulator, user agent is:
Mozilla/5.0 (Linux; Android 5.1.1; Android SDK built for x86_64 Build/LMY48X) AppleWebKit/537.36 
(KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36

**Comment by liamdebeasi** [comment]
Can you try this again on a physical device? We do not recommend testing on emulators as they ship with very outdated versions of the WebView (Most physical devices are able to auto-update their versions of the WebView).

**Comment by henkkelder** [comment]
I am working on getting a physical device. 
However in the mean time I updated my emulator with the newest webview. 
The error still occurs.

**Comment by henkkelder** [comment]
Using Browserstack and a Android 6.0 I was able to verify that my app works fine using Android 5 and 6.
This issue can be closed.
