### ISSUE TITLE
bug: ion-checkbox checked property binding not working

### ISSUE THREAD

**Issue by HibernantBear** [ionic-team/ionic#19513]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

when change checked property of checkbox right after click, sometimes the checked property won't work properly anymore as not binding or reversed. Especially when call Angular's ChangeDetectorRef.detectChanges() method right after change the checked property, this will cause ckecked property won't trigger any change detect out side the original function, and inside the original binding, the appearance always the invert one of checked value(when checked is true, appearance is no check mark, when checked is false, the check mark appeared)

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
<ion-checkbox style="position: relative;" slot="end" [checked]="item.selected" (click)="toggle_item($event, i)">
```
```
toggle_item(e: PointerEvent, index: number) {
  e.stopPropagation();
  item.selected = !item.selected;  // reverse the selected mark
  // this is simplified for undestanding, infact this part contain complex async logic
  // during click, the component changed its checked property and I change it mannuly
  // 'cause I need the property binding, finally after the async data come back
  // I implicity tell Angular to detect changes, all binding of checked perform weird
  this.cdr.detectChanges();
}
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by FortinFred** [comment]
ion-toggle has issues to with the checked prop

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a code reproduction I can use to reproduce this issue.
