### ISSUE TITLE
bug: Some components require constants instead of variables

### ISSUE THREAD

**Issue by andreas-aeschlimann** [ionic-team/ionic#19524]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Some component properties (settings) need to be given as constants and can not be given as variables. As far as my investigation goes, this happens only on an iOS device, not in the web or on Android.

**Expected behavior:**

I would expect to be able to use variables or inline constants.

**Steps to reproduce:**

Imagine an Ionic/Stencil component, such as refresher. Use it in this way
```
<ion-refresher [slot]="slot" (ionRefresh)="doSomething($event)">
    <ion-refresher-content></ion-refresher-content>
</ion-refresher>
```
, where slot is a variable defined as `'fixed'` in the component class. You can also directly set: 
```
<ion-refresher [slot]="'fixed'" (ionRefresh)="doSomething($event)">
    <ion-refresher-content></ion-refresher-content>
</ion-refresher>
```

While this works in Android and the web without problems, in an iPhone or iPhone Simulator I will get the following error: `[error] - Make sure you use: <ion-refresher slot="fixed">`. The refresher does not work at all on this device.

The only way to make the refresher work on iOS is the following:
```
<ion-refresher slot="fixed" (ionRefresh)="doSomething($event)">
    <ion-refresher-content></ion-refresher-content>
</ion-refresher>
```

It is not nice to use constants within templates, thus I usually use variable binding for all input properties. As this does not work on iOS, I consider this a bug.

If this is not a bug, probably the docs would need to specify that the properties need to be constants within the template?

I suspect this issue has something to do with change detection. The component is probably initialized before the property variable is passed and thus the property is ignored.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.10.0
   @angular-devkit/build-angular : 0.803.6
   @angular-devkit/schematics    : 8.3.6
   @angular/cli                  : 8.3.6
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.2.1
   @capacitor/core : 1.2.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 

System:

   ios-deploy : 1.9.2
   ios-sim    : 8.0.1
   NodeJS     : v10.16.0 (/usr/local/bin/node)
   npm        : 6.11.3
   OS         : macOS Mojave
   Xcode      : Xcode 11.0 Build version 11A420a
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am not able to reproduce the issue you are describing. Binding via `[slot]="slot"` and `[slot]="'fixed'"` both work for me on iOS. Additionally, I don't think binding brings you any benefit as the slot value always has to be `fixed` here. 

Are you able to provide steps to reproduce or a repo with the code required to reproduce this issue?
