### ISSUE TITLE
Animations don't work on ionic components

### ISSUE THREAD

**Issue by sachingarg05** [ionic-team/ionic#19536]
Animation when applied to a simple div works OK. But same animation is janky/choppy when applied to a div containing ion-button. And it doesn't animate at all when applied to div containing ion-grid.

**Sample angular animation:**
```
  animations: [
    trigger('panelInOut', [
      transition(':enter', [
        style({ height: '0px', opacity: 0, overflow: 'hidden' }),
        animate('2s ease-in', style({ height: '*', opacity: 1, overflow: 'hidden' }))
      ]),
      transition(':leave', [
        style({ height: '*', opacity: 1, overflow: 'hidden' }),
        animate('2s ease-out', style({ height: '0px', opacity: 0, overflow: 'hidden' }))
      ])
    ])
  ]
```
&nbsp;
&nbsp;
**1) With simple div, animation works OK:**
```
  <div class="row" style="background:chocolate" (click)="case3.show = !case3.show">
    <b>{{case3.name}}</b>
  </div>
  <div *ngIf="case3.show" [@panelInOut]>
    <div style="background:green; width:100%">
      <div *ngFor="let a of case3.courseid" class="row">
        <div>{{a}}</div><br>
      </div>
    </div>
  </div>
```
div animation on youtube:
[![ion-button animation on youtube](https://img.youtube.com/vi/o5YtprY-ffk/0.jpg)](https://www.youtube.com/watch?v=o5YtprY-ffk)

&nbsp;
&nbsp;
**2) With ion-buttons, janky/choppy animation:**
```
  <div class="row" style="background:chocolate" (click)="case2.show = !case2.show">
    <b>{{case2.name}}</b>
  </div>
  <div *ngIf="case2.show" [@panelInOut]>
    <div style="background:green; width:100%">
      <div *ngFor="let a of case2.courseid" class="row">
        <ion-button>{{a}}</ion-button><br>
      </div>
    </div>
  </div>
```
ion-button animation on youtube:
[![ion-button animation on youtube](https://img.youtube.com/vi/mtYsX26twPY/0.jpg)](https://www.youtube.com/watch?v=mtYsX26twPY)

&nbsp;
&nbsp;
**3) With ion-grid, animation doesn't work at all:**
```
  <div class="row" style="background:chocolate" (click)="case1.show = !case1.show">
    <b>{{case1.name}}</b>
  </div>
  <div *ngIf="case1.show" [@panelInOut]>
    <ion-grid style="background:green; width:100%">
      <ion-row *ngFor="let a of case1.courseid" class="row">
        <ion-col>
          {{a}}
        </ion-col>
      </ion-row>
    </ion-grid>
  </div>
```

ion-grid animation on youtube:
[![ion-grid animation on youtube](https://img.youtube.com/vi/FRtIqb1w7v4/0.jpg)](https://www.youtube.com/watch?v=FRtIqb1w7v4)

**Comment by sachingarg05** [comment]
Attaching Zip with sample code to reproduce this issue.
[animation-example.zip](https://github.com/ionic-team/ionic/files/3683911/animation-example.zip)

**Comment by liamdebeasi** [comment]
Thanks for the issue. It looks like you are using Angular Animations. I am going to close this issue as Ionic Framework does not manage Angular Animations.

Additionally, animating `ion-button` has more elements to animate than a simple `div` does, and animating the `height` property is known to not be very performant.

**Comment by sachingarg05** [comment]
This is a problem with all ionic components - ion-button, ion-grid etc... and it is not a performance issue. It is janky if animation is 200 milli-seconds or if animation is 2 seconds or 5 seconds. The 'jerks' in animation are at exactly the same spots regardless of speed.

Guess: It could be that because ionic is using web components which are also lazy-loaded, their size is not available (or set) till they are fully visible (or fully loaded) which causes them to not animate at all or animate with a delay. We have been trying to get this to work since a week now, and so far we couldn't find any way for animations to work.

If you can investigate the root cause for why this is happening, it might be possible to fix this within the ionic components, or at least find a workaround that we can implement to fix this in our app. I will be happy to run any experiments or tests to help you debug this faster.

I don't really care much about angular animations. If you can suggest any alternatives to angular animations which are known to work with ionic components, we can explore using those instead.

**Comment by liamdebeasi** [comment]
You are correct, the dimensions of the `ion-button` components are not known ahead of time because of lazy loading. In your example you are using the `*` to let Angular automatically set the height; however, the web components have not all rendered so the height Angular sees becomes invalid.

All components expose a `componentOnReady()` method that you could use to ensure all components have been rendered before proceeding with the animation.

**Comment by sachingarg05** [comment]
Does this issue need to be re-opened? Is this OK if animations can't be used inside anything using any ionic component?

**Comment by liamdebeasi** [comment]
Animations _can_ be used with Ionic Components, the developer just needs to ensure that animations that require knowing the height ahead of time aren't run until components have initialized.

**Comment by sachingarg05** [comment]
Thanks, that helps us understand things better. 

How to find out when ionic components have initialized/loaded and are ready to start the animation when there are multiple ionic components in a section. Like in the original question above, if there is an ion-grid or multiple ion-buttons or combination of both, like:

```
  <div class="row" style="background:chocolate" (click)="case2.show = !case2.show">
    <b>{{case2.name}}</b>
  </div>
  <div *ngIf="case2.show" [@panelInOut]>
    <div style="background:green; width:100%">
      <div *ngFor="let a of case2.courseid" class="row">
        <ion-button>{{a}}</ion-button><br>
      </div>
    </div>
  </div>
```

**Comment by liamdebeasi** [comment]
You will need to get the components and `await` the `componentOnReady` methods on them. If you have an `ion-grid` with `ion-button` elements inside of the grid, you _should_ only have to `await` the `componentOnReady` method for the `ion-grid`.
