### ISSUE TITLE
bug: Ionic CSS attributes are deprecated

### ISSUE THREAD

**Issue by alertcentric** [ionic-team/ionic#19555]
Upgrading to 4.10.0 I am getting the following CSS error:

```
fesm5.js:5006 [DEPRECATED][CSS] Ionic CSS attributes are deprecated.
Replace:
'<div text-wrap>'

With:
'<div class="ion-text-wrap">'
```
      
Looking at the documents I also noticed there is no longer text-wrap attribute but instead it is class="ion-text-wrap".

My question when was this breaking changed introduced and why isn't it stated in the changelog  releases as a breaking change? It's actually not trivial but a major rework for my project.

**Comment by henkkelder** [comment]
same here.

**Comment by bkarv** [comment]
I have the same issue! I don't understand why this is not in the changelog as a breaking change.

**Comment by Spinnenzunge** [comment]
They are just deprecated and still work right? The breaking change will probably be introduced in the version they change from deprecated to removing the attribute selectors all-together. Masking it deprecated in previous versions gives you time to migrate the code. Maybe somebody already wrote a search/replace script that could be run to change all the attributes to css classes?

**Comment by bkarv** [comment]
Yeah I can confirm they still work. If you have a class in the tag doing a simple replace won't help, hopefully some has created a better script, if there is one please let me know

**Comment by liamdebeasi** [comment]
Thanks for the issue. The deprecation warnings are not breaking changes. CSS Attributes currently work in Ionic v4 and will continue to work until the next major release of Ionic. Any breaking changes are done in major release versions (4.0, 5.0, etc).
