### ISSUE TITLE
bug: cursor not visible in input field within a slide on iOS 13 

### ISSUE THREAD

**Issue by chriswep** [ionic-team/ionic#19556]
# Bug Report

**Ionic version:**
[x] **4.8 - 4.10**

**Current behavior:**
When an input field within a slide is focused, text can be entered but no cursor is visible.

**Expected behavior:**
Cursor is visible on focus.

**Steps to reproduce:**
I see this issue on all my slide input fields since iOS 13 (also 13.1), tested iPhone7 device and iPhone 8 / 11 Pro Emulator. Android, all browsers and iOS12 works fine.

Trying to workaround this issue, the only way i could make the cursor appear was setting „position:fixed“ on the parent element.

**Comment by noxiousmobile** [comment]
Anyone working on this? I have the same issue, position:fixed works but not on a page with scrolling.

**Comment by giladrom** [comment]
Same issue here.

**Comment by lufengd3** [comment]
check your input style, remove user-select: none

**Comment by noxiousmobile** [comment]
> check your input style, remove user-select: none

This has nothing with user-select. It's not working, the issue is different.
The only way to get the cursor is to use position:fixed, but that will not work if you have like 10 input boxes inside scrollable ion-slide.

**Comment by chriswep** [comment]
> but that will not work if you have like 10 input boxes inside scrollable ion-slide.

See the comments in the linked issue here: https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/449 - some of us have successfully implemented this workaround. At least for me this also works with multiple inputs in a scrollable slide.

**Comment by giladrom** [comment]
Unfortunately using position: fixed completely ruins my grid. Looks like I'll have to get rid of the slides and just implement separate pages.

**Comment by danielehrhardt** [comment]
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/353#issuecomment-548464481

**Comment by liamdebeasi** [comment]
Hi there, is this still an issue with the latest version of Ionic Framework?
