### ISSUE TITLE
bug: 4.10.1 breaks ionViewDidEnter in modals

### ISSUE THREAD

**Issue by 7freaks-otte** [ionic-team/ionic#19576]
# Bug Report

**Ionic version:**

[x] **4.10.1**

**Current behavior:**

When a page is opened via modalCtrl ionViewDidEnter is not triggered anymore.

**Expected behavior:**

With the exact same code ionViewDidEnter is triggered in 4.10.0 and below.

**Comment by chrisbinnefeld** [comment]
Just wanted to create an issue about this topic.

I've created an stackblitz which is showcasing this bug: https://stackblitz.com/edit/ionic-v4-modal-didenter-bug

All lifecycles are called except **ionViewDidEnter**.

![image](https://user-images.githubusercontent.com/36038291/66396258-a95b0380-e9d9-11e9-9f9e-71fbc68672e4.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am able to reproduce this. It looks like `ionModalDidPresent` is not firing, which may be why `ionViewDidEnter` does not fire. I am investigating and will update this thread when I have more to share.

**Comment by liamdebeasi** [comment]
Can you all give this dev build a try, and let me know if it resolves the issue for your apps? 

`npm i @ionic/angular@4.11.0-dev.201910081329.02c1724`

Thanks!

**Comment by chrisbinnefeld** [comment]
I can confirm that with `@ionic/angular@4.11.0-dev.201910081329.02c1724` `ionViewDidEnter` is called again. 

Thanks for the quick fix!

**Comment by 7freaks-otte** [comment]
Thanks this resolves my issue. `ionViewDidEnter` is called again.

**Comment by liamdebeasi** [comment]
This issue has been fixed and is available now in Ionic 4.10.2. Thanks!
