### ISSUE TITLE
CoverFlow Animation not working...Followed Ionic Documentation

### ISSUE THREAD

**Issue by 08Thug** [ionic-team/ionic#19583]
I am working in my Ionic 4 app and I have added the CoverFlow effect to my slider but it is not working.
But it is not showing the coverflow effect. It is displaying simple effect slider.
It's not even showing any error.Eventhough i've set the duration still its showing the default slider
Any help is much appreciated.

**Comment by liamdebeasi** [comment]
Please see https://codepen.io/liamdebeasi/pen/vYYEwZM for an example of cover flow working on `ion-slides`.

**Comment by 08Thug** [comment]
Try this it helped me.......

https://codepen.io/liamdebeasi/pen/vYYEwZM

**Comment by 08Thug** [comment]
Thank you.....by removing the last two line its working for me
