### ISSUE TITLE
bug: IonTabButton href showing on browser as undefined when not defined

### ISSUE THREAD

**Issue by diogomateus** [ionic-team/ionic#19580]
**Bug Report**

**Ionic version:**
"@ionic/core": "^4.10.0",
"@ionic/react": "^4.10.0-rc.3",

**Current behavior:**
Having IonTabButton component and not passing an `href` prop, it's always returning undefined. This makes the page reload even if an onClick is passed. On documentation it says that href can be `string | undefined`.

**Expected behavior:**
Having IonTabButton component and its prop href is not defined, I expect the href not to show on the html.

**Ref:**
<img width="208" alt="Screenshot 2019-10-08 at 15 18 59" src="https://user-images.githubusercontent.com/4015038/66404375-3b660a80-e9e0-11e9-8b62-7a39c5a46cbd.png">

**Comment by elylucas** [comment]
Hi @diogomateus,

Could you provide a snippet of what your <IonTabButton> looks like? Curious whats going on inside of the onClick. 

Also, it is not advised to avoid the href, as behind the scenes the href is set dynamically to forward to the correct page that was last left on that particular tab. Trying to navigate with an onClick will always take you to the same page.

**Comment by elylucas** [comment]
Fixed in 4.11.0, thanks
