### ISSUE TITLE
feat: Angular 9 Support

### ISSUE THREAD

**Issue by godenji** [ionic-team/ionic#19587]
#Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
Angular 9 will be released in the next month or so; Ionic/Angular should extend support beyond current 7.x/8.x range.

**Additional Context**
Angular 9 will bring by-default Ivy based builds, latest TypeScript, and (finally) fast incremental compilation to Ionic/Angular projects. Let's stay ahead of the curve and not wait too long to support the latest & greatest from Angular + TypeScript.

**Comment by Noaber** [comment]
I have to agree, Angular 9 support as soon as possible would be awesome :)

**Comment by godenji** [comment]
First Angular 9 RC is now available.

Upgrade guide is here:
https://next.angular.io/guide/updating-to-version-9

Angular 9 GA scheduled for end of November.

**Comment by moxiaomomo** [comment]
now ionic cannot work well with threejs r0.109?

**Comment by godenji** [comment]
Angular 9 RC5 released a few days ago.

What's the ETA on Ionic + Angular 9 when the GA lands? Ideally Ionic users won't have to wait months for the latest and greatest from Angular.

Ideally Ionic itself will have full support for Angular 9 so all the benefits of Bazel + Ivy are realized both within Ionic and client apps (DCE/tree shaking are vastly improved, would be fantastic to reduce core bundle size, not to mention have much faster builds).

**Comment by dennisameling** [comment]
I just provided a PR for basic Angular 9 support. The library isn't compiled with Ivy yet in the commit, but it should allow you to upgrade your application to Angular 9 until actual Ivy support is introduced (currently being worked on in branch https://github.com/ionic-team/ionic/tree/angular-ivy). Existing Ionic applications (e.g. Angular 8) should continue to work with this commit.

**Comment by dennisameling** [comment]
PR has been closed by Ionic team, see https://github.com/ionic-team/ionic/pull/19515 for Ivy support

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be available in Ionic 5. For more information and if you'd like to start testing it out please see this blog: https://ionicframework.com/blog/ionic-5-0-0-release-candidate/

**Comment by pickfire** [comment]
angular 9 is here now

**Comment by godenji** [comment]
> angular 9 is here now

5.0 RCs are coming weekly, hope 5.0 release isn't far off.

**Comment by brandyscarney** [comment]
Hey everyone! Angular 9 & Ivy are supported in Ionic 5 which was released today. Read more on our blog here: https://ionicframework.com/blog/announcing-ionic-5/. 🙂
