### ISSUE TITLE
note: IOS13 causes issues with HammerJS

### ISSUE THREAD

**Issue by henkkelder** [ionic-team/ionic#19594]
This not a real bug report, but just a notice:

IOS 13 started supporting PointerEvents. HammerJS does not handle these properly. This caused Pinch logic in my app to fail. 

Disabling PointerEvents in HammerJS's code solved the problem for me.

[#1084](https://github.com/hammerjs/hammer.js/issues/1084)

**Comment by AtanasChachev** [comment]
I have similar issue but can't find fix.

I have the following element

```
<div tappable (click)="func1()" (press)="func2()"></div>
```

When I tap on a device, func2() is always executed.

On iOS12 I don't have that issue... (on tap func1 is executed and on press func2 is being executed) I've tried turning off the `Pointer events` from the iPad settings but that does not fix my issue :(

**Comment by jackyyuenahsay** [comment]
@henkkelder May I know how to disable the PointerEvents in HammerJS code? We are using ionic 3.

**Comment by henkkelder** [comment]
@jackyyuenahsay I cloned the respository and modified it so PointerEvents are disabled. 
See https://github.com/henkkelder/hammer.js

**Comment by jackyyuenahsay** [comment]
@henkkelder Since the hammer is built in Angular, how should I reference the modified one?

**Comment by henkkelder** [comment]
@jackyyuenahsay Sorry I am using IONIC 4. 
It was included in IONIC 3 but no longer in IONIC 4. 
I would not know how to solve it with IONIC 3.
You might want to report the bug for IONIC 3?
