### ISSUE TITLE
feat: Support React Native

### ISSUE THREAD

**Issue by KyDenZ** [ionic-team/ionic#19593]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
I am grateful for your work, and for the community I would continue to use Ionic for projects.
But Native React may be interesting for the community, and I would be interested to work with ionic on React Native.

Do you have plans for React Native?

**Comment by elylucas** [comment]
Hi @KyDenZ,

While we don't have plans to do any support directly with React Native, we do have a version of Ionic that works with React that can be used from within a React Native project (view a webview), or can be used on its own to develop apps with 100% web technologies. Check out Ionic React here: https://ionicframework.com/docs/react/overview
