### ISSUE TITLE
Ionic 4 - ion-segment has very high lag on some android devices bug: 

### ISSUE THREAD

**Issue by marcotoldo** [ionic-team/ionic#19597]
**Ionic version:**
[x] **4.x** ("@ionic/angular": "^4.10.0")

**Current behavior:**
On some Android devices (as far as we tested it seems to be a problem of Android 6, with Android 5 and above 6 there's no such problem, didn't test on iOS yet) when selecting an ion-segment-button within an ion-segment such as:

```
<ion-toolbar>
        <ion-segment (ionChange)="segmentChanged($event)" [value]="activeSegment">
            <ion-segment-button value="dashboard" checked>
              <ion-label>Dashboard</ion-label>
            </ion-segment-button>
            <ion-segment-button value="features">
              <ion-label>Features</ion-label>
            </ion-segment-button>
</ion-segment>
</ion-toolbar>
```
controlling an ion-content with segments managed with *ngIf statements such as:

```
<ion-content>
<ng-container *ngIf="activeSegment == 'dashboard'">Here goes the content if active segment is dashboard</ng-container>
<ng-container *ngIf="activeSegment == 'features'">Here goes the content if active segment is features</ng-container>
</ion-content>
```
there's a severe lag of some seconds before the variable 'activeSegment' updates its value.  On the UI the tapped segment gets highlighted immediately but it takes a very long time before the actual content associated with the selected segment is displayed.
We couldn't find a valid explanation for that because on many devices it works just fine (content is updated as soon as the segment is selected) but on others (running android 6, no matter which webview version they are running) we experienced such problem.

As far as we can see this has nothing to do with our app (memory leaks, heavy components or so on) because we experienced the lag on much more powerful devices than those on which we didn't experience it and other UI components run just fine (and fast) on any device as well

**Expected behavior:**
The variable binding the active segment should be updated immediately

**Steps to reproduce:**
Unfortunately there's no easy way to reproduce the problem.  I suppose this may have something to do with android 6 but I'm not sure about that.
Just wondering if anybody else has experienced the same issue or if anybody knows what could be wrong and how it could be fixed

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you testing this on a device or on an emulator? Additionally, which kinds of Android devices are you seeing this issue on?

**Comment by marcotoldo** [comment]
Hi @liamdebeasi I'm currently testing on an actual device.

Please find enclosed the hardware specifications of the device

Thank you

![1](https://user-images.githubusercontent.com/3941460/66483419-577faf80-eaa5-11e9-8c7f-0ba51f422c05.png)
![2](https://user-images.githubusercontent.com/3941460/66483527-87c74e00-eaa5-11e9-818d-043369d3b414.jpg)

**Comment by liamdebeasi** [comment]
Are you able to provide a repo with the code required to reproduce this issue? I am not aware of any existing performance issues with `ion-segment`.
