### ISSUE TITLE
feat: Allow button=false on ion-item to disable click takeover and button behavior

### ISSUE THREAD

**Issue by CitizenBeta** [ionic-team/ionic#19590]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
Right now, if I add an ion-checkbox inside an ion-item, it takes over the click function of the ion-item. If we add button=false on an ion-item, the expected result is that items placed within, such as a ion-checkbox, will not make the ion-item work like a button.

**Describe Preferred Solution**
Allow us to set button=false on ion-item and have it work regardless of whether there's an input inside.

**Describe Alternatives**
Right now, if I add an ion-checkbox inside an ion-item, it takes over the click function of the ion-item. A workaround is the place the ion-checkbox inside a <span> tag which has the shadowdom takeover the span instead of the ion-item, but this seems super janky and the ion-item itself still visually clicks like a button but just doesnt do anything. Setting button="false" doesn't solve the problem although it seems like it should based on the documentation.

**Related Code**

Temporary fix that doesn't quite do the job:

```
<ion-item mode="md">
    <span class="checkbox-container" slot="start"><ion-checkbox [(ngModel)]="allowEmailMarketing" class="ion-margin-end"></ion-checkbox></span>
    <ion-label class="ion-text-wrap"><p>Label text</p></ion-label>
    <ion-icon id="email-info" name="information-circle-outline" slot="end"></ion-icon>
</ion-item>
```

Ideal solution:

```
<ion-item button="false" mode="md">
    <ion-checkbox [(ngModel)]="allowEmailMarketing" class="ion-margin-end" slot="start"></ion-checkbox>
    <ion-label class="ion-text-wrap"><p>Label text</p></ion-label>
    <ion-icon id="email-info" name="information-circle-outline" slot="end"></ion-icon>
</ion-item>
```

**Additional Context**

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm kind of confused. You want the click events to remain on the checkbox, but not on the parent item? Or you want the click event to be disabled entirely?
