### ISSUE TITLE
bug: laggy page transition

### ISSUE THREAD

**Issue by ejerskov** [ionic-team/ionic#19605]
# Bug Report

**Ionic version:**
[x] **4.10.2**

**Current behavior:**
When using the default transition between pages, it appears laggy between some pages:

_Image removed_

It is very difficult to debug since it is only happens on the device and not in the browser or simulator.

**Related code:**
The two pages that are navigated to in the video above is very simple without much logic.

Navigation is done by:

`this.router.navigateByUrl('page');`

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 10 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : ios-sim/9.0.0-dev.1 darwin-x64 node-v10.15.1
   NodeJS     : v10.15.1 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8

```

**Comment by liamdebeasi** [comment]
Can you provide a repo where I can see this lag happening?

**Comment by ejerskov** [comment]
I can't share this repo unfortunately. Do you have any ideas what I could try to fix it?

**Comment by liamdebeasi** [comment]
I can't really provide any useful feedback if I am unable to reproduce the issue. Are you able to provide a simplified repo that still shows the bug? You can remove any secret/proprietary info.
