### ISSUE TITLE
bug: Cannot use --border-radius at ionic 4 with android 5.1

### ISSUE THREAD

**Issue by ktlee95** [ionic-team/ionic#19609]
First of all, thank you Ionic team for fixing color issue for button in ionic 4 for android 5.1. You have done a great job. However, the border-radius and other property in other element still cannot be run in android 5.1. One of the great example is --border-radius where it is not detect and ignored in android 5.1. Please take note on it and fix it. Thanks

**Comment by liamdebeasi** [comment]
Can you provide a repo with the code required to reproduce this issue?

**Comment by ktlee95** [comment]
Example of the code:
`<ion-button style="--border-radius: 26px;" expand="block" color="tertiary" >Log Out</ion-button>`

This code will produce the desired result in android 7 & above
![image](https://user-images.githubusercontent.com/19160574/66617610-69c62e80-ec08-11e9-950f-71738d989280.png)
Screenshot of android 7

However, the same line of code will produce this in android 5.1
![image](https://user-images.githubusercontent.com/19160574/66617957-c8d87300-ec09-11e9-8cfd-52fbecc17b8c.png)
Screenshot of android 5.1

Android 5.1 is unable to detect the --border-radius style and it uses the default border-radius.

**Comment by ktlee95** [comment]
Both physical device and emulator have this issue.

**Comment by hanning2014** [comment]
the screen is blank on Android 5，can help?

**Comment by ktlee95** [comment]
> the screen is blank on Android 5，can help?

@hanning2014 update your project package(@ionic/angular) to the latest version. Then u won't have blank screen but will have the unable to use --css issue
`npm install --save @ionic/angular@latest`

**Comment by liamdebeasi** [comment]
@ktlee95 Can you provide a repo with the code required to reproduce this issue?
