### ISSUE TITLE
bug: ion-textarea on edge and cordova-windows types reverse when typing for first time

### ISSUE THREAD

**Issue by rehannawab** [ionic-team/ionic#19614]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Whenever typing an input in ion-textarea on Edge or Windows Cordova, for the first time it types in reverse. When the input is erased and typed again, it works as expected

**Expected behavior:**
ion-textarea should not type in reverse.

**Related code:**

```
<ion-item lines="none">
  <ion-label position="stacked">Input</ion-label>
    <ion-textarea
      [(ngModel)]="input"
    ></ion-textarea>
</ion-item>
```

**Ionic info:**

```
Ionic:

   Ionic CLI : 5.4.1 (C:\Users\rnawab\AppData\Roaming\npm\node_modules\ionic)

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : none
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.5.1
   native-run  : 0.2.7

System:

   NodeJS : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by rehannawab** [comment]
Hi @liamdebeasi ,

I'm seeing this on 
Microsoft Edge 41.16299.1004.0
Microsoft EdgeHTML 16.16299

Thanks!

**Comment by keo9ren** [comment]
Hi, 
I'm seeing this on 
Microsoft Edge 44.18362.1.0
Microsoft EdgeHTML 18.18362
also.

**Comment by tmwrnr** [comment]
+1 
@liamdebeasi The [issue](https://github.com/ionic-team/ionic/issues/18984)  I opened is related to this one.

**Comment by tgangso** [comment]
Also seeing this issue 

Microsoft Edge 44.18362.387.0
Microsoft EdgeHTML 18.18362

Works fine in Edge Beta (Chromium)

**Comment by liamdebeasi** [comment]
Thanks for the follow up. As @tmwrnr suggested, this looks to be the same issue as https://github.com/ionic-team/ionic/issues/18984. I am going to close this issue in favor of that one.
