### ISSUE TITLE
ion-textarea placeholder shifted left by 2 pixels when label (stacked) and placeholder are both used

### ISSUE THREAD

**Issue by RobbHerman** [ionic-team/ionic#19616]
**Ionic version:**

[x] **4.11.0**

**I'm submitting a ...** 

[X] bug report
[ ] feature request

**Current behavior:**

When using ion-textarea placeholder and ion-label (stacked), then placeholder is shifted left.  Very apparent when using on a form with other controls.

**Expected behavior:**

Placeholder should line up with label like the other controls (input, datetime, select)

**Steps to reproduce:**

**Related code:**

```
<ion-content class="ion-padding" color="primary">
    <ion-item lines="none">
        <ion-label color="secondary" position="stacked">First Name</ion-label>
        <ion-input placeholder="Enter First Name"></ion-input>
    </ion-item>
    <ion-item lines="none">
        <ion-label color="secondary" position="stacked">Description</ion-label>
        <ion-textarea class="custom-textarea" placeholder="Enter Description" rows="1" cols="2"></ion-textarea>
    </ion-item>
    <ion-item lines="none">
        <ion-label color="secondary" position="stacked">Date and Time</ion-label>
        <ion-datetime displayFormat="MM/DD/YYYY" placeholder="Choose Month"></ion-datetime>
    </ion-item>
    <ion-item lines="none">
        <ion-label color="secondary" position="stacked">Hair Color</ion-label>
        <ion-select okText="Okay" cancelText="Dismiss" placeholder="Choose Hair Color" (ionChange)="onChange()">
            <ion-select-option value="brown">Brown</ion-select-option>
            <ion-select-option value="blonde">Blonde</ion-select-option>
            <ion-select-option value="black">Black</ion-select-option>
            <ion-select-option value="red">Red</ion-select-option>
        </ion-select>
    </ion-item>
</ion-content>
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```
Ionic:

   Ionic CLI                     : 5.4.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.0
   @angular-devkit/build-angular : 0.803.8
   @angular-devkit/schematics    : 8.3.8
   @angular/cli                  : 8.3.8
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.2.1
   @capacitor/core : 1.2.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3 (/usr/local/bin/node)
   npm    : 6.11.3
   OS     : macOS Mojave

**Comment by brandyscarney** [comment]
Thanks for the issue! I was able to reproduce it here: https://codepen.io/brandyscarney/pen/RwwGmzZ?editors=1100

It seems like an easy fix, will look into adding this.
