### ISSUE TITLE
bug: Ionic 4 / React history.push() is not changing pages

### ISSUE THREAD

**Issue by benallfree** [ionic-team/ionic#19622]
# Bug Report

**Ionic version:**
[x] **4.11.x**

**Current behavior:**
`history.push` does not change pages. 

I believe `<IonRouterOutlet>` is not working, because the kitchen sink React Ionic demo works with previous versions of Ionic, but upgrading to the latest version breaks it.

**Expected behavior:**
`history.push` changes pages.

**Steps to reproduce:**

Please see:

https://github.com/benallfree/ionic-react-conference-app/tree/history-push-working

https://github.com/benallfree/ionic-react-conference-app/tree/history-push-bug-broken

**Related code:**

```
`<IonButton onClick={() => history.push('/somePage')}>Go</IonButton>` does not change pages.
```

**Other information:**
Related  issues: https://github.com/ionic-team/ionic/issues/19246  and https://github.com/ionic-team/ionic/issues/18804

**Ionic info:**
```
Ionic:

   Ionic CLI       : 5.4.2 (/Users/uncovered/.nvm/versions/node/v10.15.0/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.6.0 (update available: 0.8.0)
   native-run  : not installed

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.15.0 (/Users/uncovered/.nvm/versions/node/v10.15.0/bin/node)
   npm        : 6.7.0
   OS         : macOS Catalina
   Xcode      : Xcode 11.1 Build version 11A1027
```

**Comment by elylucas** [comment]
Hi @benallfree,

Thanks for the issue. There was a change in one of the later RCs that requires each "page" to have `IonPage` be the root of the component (https://github.com/ionic-team/ionic/blob/master/packages/react/CHANGELOG.md#breaking-changes-1). 

So if you add `IonPage` to the master and detail components like so:  

```
const Master: React.FC<RouteComponentProps> = ({ history }) => {
  return (
    <IonPage>
      <IonContent>
        <IonButton onClick={() => history.push(`/detail`)}>Detail</IonButton>
      </IonContent>
    </IonPage>
  );
};

const Detail: React.FC<RouteComponentProps> = ({ history }) => {
  return (
    <IonPage>
      <IonContent className="ion-padding">
        <IonButton onClick={() => history.goBack()}>Back to Master</IonButton>
      </IonContent>
    </IonPage>
  );
};
```

The conference app starter is fairly out of date and we are working on updating it now.


The transitions will begin to work. Also, fyi, there is a prop on Buttons called `routerLink` that you can pass the url to have it do the transitions.

**Comment by benallfree** [comment]
Fantastic. For anyone else who comes here, this snippet works on 4.11.x:

```typescript

const Master: React.FC<RouteComponentProps> = ({ history }) => {
  return (
    <IonPage>
      <IonContent>
        <IonButton routerLink="/detail">Detail</IonButton>
      </IonContent>
    </IonPage>
  );
};

const Detail: React.FC<RouteComponentProps> = ({ history }) => {
  return (
    <IonPage>
      <IonContent className="ion-padding">
        <IonButton routerLink="/">Back to Master</IonButton>
      </IonContent>
    </IonPage>
  );
};

const App = () => (
  <IonApp>
    <IonReactRouter>
      <IonRouterOutlet>
        <Route path="/" component={Master} exact />
        <Route path="/detail" component={Detail} exact />
      </IonRouterOutlet>
    </IonReactRouter>
  </IonApp>
);

```
