### ISSUE TITLE
bug: React <IonPicker> is not working

### ISSUE THREAD

**Issue by marcoromag** [ionic-team/ionic#19620]
The IonPicker component in the React framework is not functional as it should be created out of the ion-picker-controller. Similar to IonAlert or the other controller-based components

The issue could be simply solved by creating the IonPicker with the createControllerComponent and removing it from the proxies:

```IonPicker.ts
import * as React from "react";
import {PickerOptions, pickerController} from '@ionic/core'

export const IonPicker = /*@__PURE__*/createControllerComponent<PickerOptions, HTMLIonPickerElement>('IonPicker', pickerController);

```

**Comment by elylucas** [comment]
Thanks for the issue. This has been fixed in #19643 and will release in 4.11.1 soon.
