### ISSUE TITLE
bug: list contents visible after navigating to next page

### ISSUE THREAD

**Issue by andy-rash** [ionic-team/ionic#19631]
# Bug Report

**Ionic version:**

[x] **4.11.0**

**Current behavior:**

When navigating from a page with a list view to a detail view (which contains a footer) part of the list's contents remain visible behind the footer. They do not remain visible for very long--maybe half a second--but it's long enough to be noticeable.

**Expected behavior:**

The list contents should never be visible after navigating away from the list.

**Steps to reproduce:**

Using the sample application, select one of the list items and watch the background of the footer on the page.

**Related code:**

Download the sample application here: [andy-rash/IonListAndFooterBug](https://github.com/andy-rash/IonListAndFooterBug).

**Other information:**

I thought that perhaps this was caused by running the app using the Chrome DevTools, but I was also able to reproduce the bug when running the app on my dev phone (Samsung Galaxy S8, Android 9 (Pie)).

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.2 (/Users/andy/.nvm/versions/node/v11.15.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.0
   @angular-devkit/build-angular : 0.803.9
   @angular-devkit/schematics    : 8.3.9
   @angular/cli                  : 8.3.9
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 4 other plugins)

Utility:

   cordova-res : 0.8.0
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (/Users/andy/Documents/SDKs/Android)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v11.15.0 (/Users/andy/.nvm/versions/node/v11.15.0/bin/node)
   npm               : 6.12.0
   OS                : macOS Catalina
   Xcode             : Xcode 10.3 Build version 10G8
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This issue is happening because:

1. You had `class="ion-padding"` applied to the footer (this added padding around the footer, making the leaving page visible under the footer)
2. You did not put your footer content in a toolbar.

Doing both of those things should resolve your issue. Can you try that and let me know how it goes?

**Comment by andy-rash** [comment]
@liamdebeasi  yes, that did help. I didn't realize .ion-padding would do that.

To replicate the look I had before, I applied a custom class to the `ion-toolbar` adding padding all around. When I was doing this, I noticed that `ion-toolbar` has this CSS rule applied to it:

```css
ion-footer ion-toolbar:last-child {
    padding-bottom: var(--ion-safe-area-bottom,0);
}
```

...which I assume is related to e.g. the iPhone X safe area.

In light of that, do you know if adding my own custom CSS rule to add uniform padding around the `ion-toolbar` would step on the toes of some other Ionic CSS functionality?

Thanks for your input!

**Comment by liamdebeasi** [comment]
I think if you added the `ion-padding` class as a div inside `ion-footer` and then gave that div a background color, that should be fine. The `ion-toolbar` element is what actually has the white background, not the `ion-footer`.
