### ISSUE TITLE
bug: ion-header ios 11 style only working on first tab

### ISSUE THREAD

**Issue by GeorgeBark** [ionic-team/ionic#19640]
# Bug Report

**Ionic version:**

[x] **4.11.0**

**Current behavior:**

The "condense" header is only working on the first loaded tab.
![out](https://user-images.githubusercontent.com/7204152/66699985-19280180-ecec-11e9-9fe0-64b55ab8ec65.gif)

**Expected behavior:**
The header should be hidden in all tabs.

**Related code:**
[Example in StackBlitz](https://stackblitz.com/edit/ionic-4-condense-ios-header)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.1 
   Ionic Framework               : @ionic/angular 4.11.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0


System:

   ios-deploy : 1.9.4
   ios-sim    : 6.1.3
   NodeJS     : v10.15.3 
   npm        : 6.11.3
   OS         : macOS Mojave
   Xcode      : Xcode 11.0 Build version 11A420a
```

**Comment by liamdebeasi** [comment]
Glad to see someone trying the new iOS 11 style header 🙂. Looks like it was selecting the wrong `ion-content` when in use on tabs that were not tab 1. I'll work on a fix for this.

**Comment by liamdebeasi** [comment]
Can you try this dev build and see if it fixes the issue for you?

`npm i @ionic/angular@4.12.0-dev.201910141832.776993c`

**Comment by GeorgeBark** [comment]
> Can you try this dev build and see if it fixes the issue for you?
> 
> `npm i @ionic/angular@4.12.0-dev.201910141832.776993c`

Now it fails from the beginning:

![image](https://user-images.githubusercontent.com/7204152/66811642-bc1d8d00-ef31-11e9-8d53-765d3e2915f7.png)

[New Stackblitz](https://stackblitz.com/edit/ionic-4-condense-ios-header-fix)

Did I miss anything?

**Comment by liamdebeasi** [comment]
Nope, I think I just gave you a bad build. Try this one:

`npm i @ionic/angular@4.12.0-dev.201910151255.dd0d993`

**Comment by rdlabo** [comment]
Good! This work well in my production environment!!

**Comment by GeorgeBark** [comment]
> Nope, I think I just gave you a bad build. Try this one:
> 
> `npm i @ionic/angular@4.12.0-dev.201910151255.dd0d993`

Now it works but somehow the fading animation is "flashing" the first time you enter a tab (I guess because after that it is on the stack so it is not initialised again), it is just a flash but doesn't look very nice...

![out3](https://user-images.githubusercontent.com/7204152/66873960-14907100-efaa-11e9-9bd1-d07d19fef47f.gif)


[Link to Stackblitz](https://stackblitz.com/edit/ionic-4-condense-ios-header-fix-ihhuyk)

**Comment by liamdebeasi** [comment]
Yeah that one is a known issue. I'm currently working on that separately 👍. Glad it's working now in your tabbed application.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This issue has been fixed and will be available in an upcoming release of Ionic Framework.
