### ISSUE TITLE
feat: option to enable/disable ripple effect on components

### ISSUE THREAD

**Issue by sebinbenjamin** [ionic-team/ionic#19648]
# Feature Request
Provide an option to enable/disable the ripple animation effect on Ionic components. 

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

The ripple effect animation on components in the Android platform does not look great in certain scenarios, especially when space is constrained. I could not find any option to disable the same in the documentation.

**Describe Preferred Solution**

Provide an option/property to disable the ripple effect on components like `<ion-button>`, `<ion-card>` etc.

**Describe Alternatives**

None I could find. Workarounds include setting platform `mode` to `ios`  or `pointer-events `to `none` in certain cases.

**Related Code**

A possible use of the proposed solution, 
```
<ion-button rippleEffect="false">
  <ion-icon slot="icon-only" name="star"></ion-icon>
</ion-button>
```

**Additional Context**

Refer the following SO questions
- [How do I disable/remove ion-ripple effect in ion-button Ionic 4?
]( https://stackoverflow.com/questions/58361692/how-do-i-disable-remove-ion-ripple-effect-in-ion-button-ioinic-4/58362117)
- [Disable ripple effect on element]( https://stackoverflow.com/questions/55865732/disable-ripple-effect-on-element)

**Comment by liamdebeasi** [comment]
Does this work for your use case: 

```javascript
import { IonicModule } from '@ionic/angular';

@NgModule({
  ...
  imports: [
    BrowserModule,
    IonicModule.forRoot({
      rippleEffect: false
    }),
    AppRoutingModule
  ],
  ...
})
```

Found in the docs: https://ionicframework.com/docs/utilities/config#basic-example

**Comment by sebinbenjamin** [comment]
Hmmm. No, I was looking for component level disabling. Config service disables it for the entire app  I guess.

**Comment by liamdebeasi** [comment]
You can use the `--ripple-color` CSS variable for things like buttons: https://codepen.io/liamdebeasi/pen/BaaKMxq. In this example I set `--ripple-color: transparent` on the first button.

Does that work for your use case?

**Comment by sebinbenjamin** [comment]
Yes, it works fine. Thanks.
