### ISSUE TITLE
bug: picker does not select closest option when released at low velocity

### ISSUE THREAD

**Issue by greimela** [ionic-team/ionic#19659]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When releasing the picker column while holding still it selects the next picker option.

![current_behavior](https://user-images.githubusercontent.com/11612483/66778782-fd2f8600-eecc-11e9-80ed-457e8c86f00a.gif)

**Expected behavior:**

When releasing the picker column while holding still it should select the closest picker option, similar to the default iOS behavior.

![expected_behavior](https://user-images.githubusercontent.com/11612483/66778776-f86ad200-eecc-11e9-8914-e89e44187bd2.gif)

**Steps to reproduce:**

Best experienced on mobile.

1. Pick up the picker column.
2. Move it to the option to select.
3. Release the picker column while not moving the finger up or down.

**Other information:**

I will provide a pull request with an implementation of the expected behavior.

**Ionic info:**

```
Ionic:

   Ionic CLI : 5.4.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.11.0
   npm    : 6.12.0
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This issue has been fixed via https://github.com/ionic-team/ionic/pull/19660 and will be available in an upcoming release of Ionic Framework.
