### ISSUE TITLE
bug: content jumps when starting ion-refresher on iOS

### ISSUE THREAD

**Issue by eternityBUG** [ionic-team/ionic#19650]
#19163 This question is very important
It will affect the user experience of ios users

But there has been no reply

I hope someone can solve this jitter problem

**Comment by eternityBUG** [comment]
#19352 That's the problem

**Comment by liamdebeasi** [comment]
Thanks for the issue. Let's try to keep issues contained to a single thread. I'm going to close this issue in favor of https://github.com/ionic-team/ionic/issues/19163. I replied there and am looking into the cause of that behavior.
