### ISSUE TITLE
bug: IonHeader above Ion Tabs when slot is top

### ISSUE THREAD

**Issue by mccabemj** [ionic-team/ionic#19666]
# Bug Report

**Ionic version:**
**4.11.0 React**

**Current behavior:**
When using the generated tab layouts, then setting the `slot` to top (to have the tabs at the top), any addition of a `IonHeader` causes it to overlap the tabs

**Expected behavior:**
Somehow, it would be possible to have a header above the tabs when the `IonTabs` slot is set to `top`

**Steps to reproduce:**
Take the generated tab app and do the following

**Related code:**

```
 <IonApp>
      <IonPage>
        <IonHeader>
          <IonToolbar>
            <IonTitle>Title of App</IonTitle>
          </IonToolbar>
        </IonHeader>
        <IonReactRouter>
          <IonTabs>
...
```

**Ionic info:**

```
Ionic:
   Ionic CLI       : 5.4.2 
   Ionic Framework : @ionic/react 4.11.1
```

**Comment by elylucas** [comment]
Hi @mccabemj,

It seems like part of your code sample got cut off. Could you update it or send an example repo?

**Comment by elylucas** [comment]
Going to close as we haven't heard back yet. If the problem persists please post here
