### ISSUE TITLE
feat: function to change the ion-back-button transition

### ISSUE THREAD

**Issue by Euxiniar** [ionic-team/ionic#19661]
# Feature Request

**Ionic version:**
4.10.0

**Describe the Feature Request**
Allow the user to modify the transition of the ion-back-button.

**Describe Preferred Solution**
Allow the user to override the function called when clicked, or add a function to modify the transition in an onView... function.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. Are you referring to the navigation animation when clicking the back button?

**Comment by Euxiniar** [comment]
Thanks for the reply ! Yes, I'm talking about it

**Comment by liamdebeasi** [comment]
You can specify a custom navigation animation via the `navAnimation` config option: https://ionicframework.com/docs/react/config#config-options

Here is an example of the MD transition: https://github.com/ionic-team/ionic/blob/master/core/src/utils/transition/md.transition.ts

Does this fit your use case?

**Comment by Euxiniar** [comment]
Oh, you're right, thank you! The Config class was not documented in the Ionic Angular docs, so I hadn't seen it, but that's what I was looking for. Thank you very much!

**Comment by liamdebeasi** [comment]
Oops sorry you're right. It was placed here: https://ionicframework.com/docs/utilities/config
