### ISSUE TITLE
bug: ion-title[size=large] does not support Japanese

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic#19663]
# Bug Report

**Ionic version:**
[x] **4.11.1**

**Current behavior:**
- The upper part of Japanese Title is not displayed.

![スクリーンショット 2019-10-15 11 49 41](https://user-images.githubusercontent.com/9690024/66796187-e5461980-ef41-11e9-8852-2600852e4e65.png)

- If font size is set smaller(ex: font-size: 30px), back-animation is rattling.
Gif Animation: https://gyazo.com/0cdf75cbe7dd8f3ded2dda238d79c4e9

**Expected behavior:**
- At default, All part of Japanese  is displayed.

![スクリーンショット 2019-10-15 11 52 16](https://user-images.githubusercontent.com/9690024/66796317-40780c00-ef42-11e9-8115-a4d583abc92a.png)

- or can be set font-size using css variables.

**Steps to reproduce:**
- The upper part of Japanese Title is not displayed.
https://ionic-v4-angular-tabs-eqcuds.stackblitz.io/tabs/tab1

- If font size is set smaller(ex: font-size: 30px), back-animation is rattling.
(after display, you should click item and navigation-back)
https://ionic-v4-angular-tabs-eqcuds.stackblitz.io/tabs/tab2

**Related code:**
https://stackblitz.com/edit/ionic-v4-angular-tabs-eqcuds

**Other information:**
I checked at chrome developer tool. using emulator of iPhone X.

**Ionic info:**
by local.

```
Ionic:

   Ionic CLI                     : 5.4.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.3.6
   @angular/cli                  : 8.3.6
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.6.0 (update available: 0.8.0)
   native-run  : not installed

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.16.2 (/usr/local/bin/node)
   npm        : 6.11.3
   OS         : macOS Catalina
   Xcode      : Xcode 11.1 Build version 11A1027
```

**Comment by rdlabo** [comment]
First aid method. But I don't know if this is correct.

```
<ion-title size="large" style="min-height: 41px;">スケジュール</ion-title>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. For the back animation issue, can you try setting the following in `globals.scss`:

```css
ion-title.title-large {
  font-size: 30px;
}
```

And then give the animation a try and see if that looks any better?

**Comment by rdlabo** [comment]
@liamdebeasi  Thanks for reply. 

Improved!!
Gif: https://gyazo.com/56fc25e93579dd8305992672a8e2a36b

But a few pixel is slide. ( It is same issue at English )
Gif: https://gyazo.com/fb15a8659df11b4073df4a9d5e1fcd58

**Comment by liamdebeasi** [comment]
Oh it looks like you had your `ion-title` wrapped in `ion-buttons`. Try removing the outer `ion-buttons`, and it should be fine.

**Comment by rdlabo** [comment]
Oh no! Thanks and Sorry. I remove `ion-buttons`, and this work well!!🙏

I will close this issue.

**Comment by liamdebeasi** [comment]
Glad to hear it works. I will add some documentation so that styling is a bit clearer for other developers.

**Comment by rdlabo** [comment]
@iampersistent Thanks!! And I found 2 issues.

- https://github.com/ionic-team/ionic/issues/19668
- In dark-mode, ion-header is not be dark if using Collapsible Large Titles => I will create Issue after more check.

`Collapsible Large Title` is great UI. Thanks for your work!!
