### ISSUE TITLE
bug: Unrecognized mobile platform for ALPS X23

### ISSUE THREAD

**Issue by nvelin-zaggo** [ionic-team/ionic#19664]
# Bug Report

**Ionic version:**
[x] **4.11.0**

**Current behavior:**
Application downloaded from Google Play Store
Using a ALPS X23 phone (A phone of a user, i don't have this phone)
`this.platform.is('android')`
return false

Using Device ionic native library
`this.device.manufacturer`
return ALPS
`this.device.model`
return X23

**Expected behavior:**
`this.platform.is('android')`
return true

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.4.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.0
   @angular-devkit/build-angular : 0.803.8
   @angular-devkit/schematics    : 8.3.8
   @angular/cli                  : 8.3.8
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-webview 2.5.2, (and 21 other plugins)

Utility:

   cordova-res : 0.6.0 (update available: 0.8.0)
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/Users/nvelin/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/usr/local/bin/node)
   npm               : 6.12.0
   OS                : macOS Mojave
   Xcode             : Xcode 11.1 Build version 11A1027
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Do you happen to know the user agent for the device?

**Comment by nvelin-zaggo** [comment]
Unfortunately, i don't have it.
I just save the device manufacturer and model in my database

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I've been trying to get access to an emulator of this device, but I haven't been able to find one.

It generally isn't possible for us to account for these edge cases without adding in device specific hacks while also ensuring that detection doesn't break for other devices. Many off-brand Android devices do not conform to a particular standard when identifying themselves on the web, which can be frustrating in situations like these.

I am going to close this issue as there is nothing actionable in terms of fixing this particular issue; however, I have proposed a new feature that would allow developers to override our platform detection methods with their own: https://github.com/ionic-team/ionic/issues/19737. With this feature, you would be able to add logic to the platform detection that would let you account for devices such as the ALPS X23. Thanks!

**Comment by nvelin-zaggo** [comment]
Sorry for the lack of information

Thanks
