### ISSUE TITLE
Back Button after FullScreen Mode crash the app

### ISSUE THREAD

**Issue by josephlodero** [ionic-team/ionic#19662]
# Bug Report

**Ionic version:**
4.11.1

**Current behavior:**
after the fullscreen mode and use the platform backbutton instead of going back to main page the app will exit, and it only happen on api 28 and up..

**Expected behavior:**
it should pop the page and back to main page after the fullscreen mode

**Steps to reproduce:**
https://github.com/josephlodero/cordova-fullscreen
1. clone
2. npm install
3. run it using android emulator (api 28)

**Ionic info:**
Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1

Utility:

   cordova-res : 0.4.0 (update available: 0.8.0)
   native-run  : 0.2.8 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.15.3 (/usr/local/bin/node)
   npm        : 6.10.3
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001

**Comment by itsvick** [comment]
Same issue for me.
I am using **Redmi Note 3** - **Marshmallow**( Android version 6)
I am using the html5 `video` tag, after clicking on fullscreen and then pressing back button app gets crashed or getting close.

**Comment by liamdebeasi** [comment]
When running attached to a debugger, are there any errors or warnings?

**Comment by josephlodero** [comment]
@liamdebeasi I tried it in pixel2 and in my phone (note 10). there is no sign of error it will just exit the app after the full screen. but if you use the back button in the navigation it will work fine.. its just happen when you use the platform backbutton

**Comment by cvharly** [comment]
Hello,
I have integrated next method on the main activity and this corrects the concern

  @Override
    public void onBackPressed() {

this.appView.loadUrl("javascript:if (document.webkitExitFullscreen) {document.webkitExitFullscreen();}");

    return;
    }

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I tried this example repo with both Cordova and Capacitor and got the following behaviors:

**Cordova**

1. Start on main screen, tap "Click here"
2. Enter fullscreen mode on video
3. Press hardware back button. This will exit the video from fullscreen mode.
4. Press hardware back button again. This will exit the app entirely.

**Capacitor**

1. Start on main screen, tap "Click here"
2. Enter fullscreen mode on video
3. Press hardware back button. This will exit the video from fullscreen mode and take you back to the main screen.

I see you have already opened an issue on the `cordova-android` repo: https://github.com/apache/cordova-android/issues/839. Does this issue happen in a Cordova application without Ionic?

**Comment by josephlodero** [comment]
Hi.. thank you for your time. 
The guy from cordova asked me to create an pure cordova app just to prove that the problem is within cordova.. sadly i never tried creating cordova app without ionic.. :(

**Comment by josephlodero** [comment]
@cvharly
can you please tell me what exact file to edit? thanks!

**Comment by l-hwen** [comment]
I also encountered this problem, the Mi Max 3 I used

**Comment by josephlodero** [comment]
I think this is not an ionic problem its more on cordova. I created a cordova app without ionic and this bug/error occurs. I already opened an issue on cordova : https://github.com/apache/cordova-android/issues/839

**Comment by josephlodero** [comment]
im going to close this issue. this issue is from cordova-android.
the solution is in the comment section : https://github.com/apache/cordova-android/issues/822
