### ISSUE TITLE
bug: swipe to go back flicker when using ios md on an android device

### ISSUE THREAD

**Issue by C-racker** [ionic-team/ionic#19674]
# Bug Report

**Ionic version:**

[x] **4.7** and **4.11.1**

**Current behavior:**

The tabs created through cli have not been changed

When the android platform USES the ios style, a splash screen will appear on the return page

**Expected behavior:**

Normal return page

**Other information:**

![bug2](https://user-images.githubusercontent.com/20217449/66897471-a7bcbb80-f029-11e9-894e-4568d39e665b.gif)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you give the following dev build a try and let me know if it resolves your issue?

`npm i @ionic/angular@4.12.0-dev.201910171448.fc6a754`.

**Comment by C-racker** [comment]
> Thanks for the issue. Can you give the following dev build a try and let me know if it resolves your issue?
> 
> `npm i @ionic/angular@4.12.0-dev.201910171448.fc6a754`.

Problem solved, thank you

**Comment by liamdebeasi** [comment]
Thanks! This issue has been fixed and will be available in an upcoming release of Ionic Framework.
