### ISSUE TITLE
bug: ionic cordova run ios --device does not deploy to device

### ISSUE THREAD

**Issue by reed-lawrence** [ionic-team/ionic#19681]
Ionic version: 5.4.2
Cordova ios: 5.0.1
iOS: 13.1.2

ionic cordova build ios > Xcode project > Run on device. (Works)
ionic cordova run ios --device (Does not live reload (with flag) or deploy to device)

No errors in console. File watcher for changes re-compiles as expected. But no changes are reflected on the device.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Ionic Framework does not manage deployment of the app to a device (The Cordova command does). I recommend you post your question on our [forum](https://forum.ionicframework.com) or our [slack](https://ionic-worldwide.slack.com).
