### ISSUE TITLE
cordova-plugin-ionic-webview

### ISSUE THREAD

**Issue by cissemy** [ionic-team/ionic#19688]
Plugin doesn't support this project's cordova-android version. cordova-android: 6.1.2, failed version requirement: >=6.4.0

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this issue tracker is for Ionic Framework, not the webview plugin.

Additionally, as per the webview documentation the required version is `cordova-android 6.4+`. To use an older version of `cordova-android`, you will need to use an older version of the webview plugin: https://github.com/ionic-team/cordova-plugin-ionic-webview#plugin-requirements
