### ISSUE TITLE
feat: Add a new lifecycle hook that runs once after ngOnInit

### ISSUE THREAD

**Issue by tristan-mastrodicasa** [ionic-team/ionic#19686]
# New Lifecycle Hook for Ionic Angular

**Ionic version:**
[x] **4.x**

I feel that it would be nice to include a new ionic lifecycle hook that runs only **one** time after the view enters or right after ngOnInit.

Currently, when calling Http services from ngOnInit it blocks the navigation button on the previous page from transitioning and can confuse the user as to whether the button has received their click or not.

## Possible solution
It would be nice to have the life cycle hooks go like
`ngOnInit() -> ionFirstViewEnter() -> ionViewWillEnter() -> ionViewDidEnter() -> ...`

## Current solution I am using
Right now to get around ngOnInit from blocking I have used this code
```javascript
  public userItemList: IUserItem[];
  private initialResultsShown = false;

  /**
   * Show recommended users
   */
  public ionViewDidEnter() {
    if (!this.initialResultsShown) {
      this.http.searchUsers('').toPromise().then((res) => {
        this.userItemList = res;
        this.initialResultsShown = true;
      }).catch(err => console.log(err));
    }
  }
```

## What I would like
```javascript
  public userItemList: IUserItem[];

  /**
   * Show recommended users
   */
  public ionFirstViewEnter() {
    this.http.searchUsers('').toPromise().then((res) => {
      this.userItemList = res;
      this.initialResultsShown = true;
    }).catch(err => console.log(err));
  }
```

Cheeeeeers

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you able to use the Angular lifecycle hooks here? 

For example, you could use `ngAfterContentInit` or `ngAfterViewInit` which are only called once: https://angular.io/guide/lifecycle-hooks.

**Comment by tristan-mastrodicasa** [comment]
I tried using all of the possible angular hooks, including the ones you suggested, none trigger when the view is shown unfortunately.

**Comment by liamdebeasi** [comment]
The `ngAfterViewInit` hook is called when the view is initialized, so that is likely one of the hooks you want to consider. I'm not sure that the solution here is to add another lifecycle hook when these hooks already exist. Can you provide an example of when these hooks/Ionic lifecycle hooks would not be sufficient for your use case?

**Comment by SatoAV** [comment]
Probably related to this issue:
In React `ionViewDidEnter` doesn't fire when the page is shown for the first time. I need to resort to use both `componentDidMount` and `ionViewDidEnter` methods. This seems counter-intuitive =\

**Comment by liamdebeasi** [comment]
@SatoAV That sounds like a separate bug. `ionViewDidEnter` should fire whenever the page has become the main view. Can you create a new issue for that?

**Comment by SatoAV** [comment]
@liamdebeasi OK, sure!
