### ISSUE TITLE
bug: When the page is scrolling, click to return，makes previous page scroll to top,help me

### ISSUE THREAD

**Issue by wanting615** [ionic-team/ionic#19697]
Current behavior:
On ios 13.1.2， I scroll somewhere on the list page，Then go to the details page，When I scroll through the details page, I return to the list page，theList page auto scroll to top；that On android and ios < 13 that works as expected.

Expected behavior:
 I don't expect the list page to scroll；

![1](https://user-images.githubusercontent.com/44287823/67136400-50e8f900-f258-11e9-8a23-1bfd07d5b072.gif)

Ionic info:
Ionic:

   Ionic CLI                     : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 4 other plugins)

Utility:

   cordova-res : 0.8.0 
   native-run  : 0.2.8 (update available: 0.2.9)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.1 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 9.4 Build version 9F1027a

**Comment by liamdebeasi** [comment]
Thanks for this issue. I am going to close this as this is a known bug in WebKit that will be fixed in iOS 13.2.
