### ISSUE TITLE
bug: IonMenu not appearing and throwing warnings

### ISSUE THREAD

**Issue by Kikketer** [ionic-team/ionic#19698]
# Bug Report

**Ionic version:**

[x] **4.11.1** @ionic/react

**Current behavior:**

Following the Ionic React documentation and staring with the tabs template.  First off it's not entirely clear where I should place the IonMenu: https://ionicframework.com/docs/api/menu

I placed it as a sibling of a `<IonPage` for the examples Tab1 page.  Copy and pasting the code from the example, the menu item does not appear.

**Expected behavior:**
The menu item should appear in the header.

**Steps to reproduce:**
Start with the react tabs project, add the IonMenu portion.  Notice that the menu icon does not appear in the header and you get a warning in the console that the `menuId` is now deprecated and you should use `containerId`.

I did try to update the code to use `contentId="first"` and then added an `id="first"` to the menu `<IonContent>` element.  That removed the warning and the icon actually appeared but clicking the button didn't do anything.

I'm sure I'm just missing something from the docs but it's not entirely clear how to add a menu item to a page. 

**Related code:**

```
const Tab1: React.FC = () => {
  return (
    <> // Notice the IonMenu is a sibling of the IonPage (I think that's what the docs implied)
      <IonMenu side="start" menuId="first">
        <IonHeader>
          <IonToolbar color="primary">
            <IonTitle>Start Menu</IonTitle>
          </IonToolbar>
        </IonHeader>
        <IonContent>
          <IonList>
            <IonItem>Menu Item</IonItem>
            <IonItem>Menu Item</IonItem>
            <IonItem>Menu Item</IonItem>
            <IonItem>Menu Item</IonItem>
            <IonItem>Menu Item</IonItem>
          </IonList>
        </IonContent>
      </IonMenu>

      <IonPage>
        <IonHeader>
          <IonToolbar>
            <IonButtons slot="secondary">
              <IonMenuButton/>  // The IonMenuButton is added here
            </IonButtons>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.4 (/Users/n0148094/.config/yarn/global/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v8.12.0 (/Users/n0148094/.nvm/versions/node/v8.12.0/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by elylucas** [comment]
Hi @Kikketer,

Thanks for the issue, this should be fixed in the upcoming 4.11.2 release which should be out today.

**Comment by Arrow7000** [comment]
I agree, it is very unclear how to control the state of the menu from the docs. Ideally there should be a declarative `isOpen` prop that can be controlled like this

```ts
const App = () => (
  <>
    <IonMenu isOpen={true}></IonMenu>
    <IonApp></IonApp>
  </>
);
```

**Comment by gugahoi** [comment]
Also struggling to understand how to use the `IonMenu` component with `IonTabs`. Documentation is not clear at all and I've been unable to find examples.

**Comment by elylucas** [comment]
The React Conference app shows a good example of using a menu along with a tabs component: https://github.com/ionic-team/ionic-react-conference-app. 

Going to close this issue as it doesn't seem to be a bug, but please post here if you have any questions.
