### ISSUE TITLE
stencil standalone component (composed of ionic core components) is throwing exception on ion-tabs in ionic/angular 4 application

### ISSUE THREAD

**Issue by sanaadostmuhammad** [ionic-team/ionic#19690]
**Ionic version:**

[x] **4.11**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

Stencil version:
@stencil/core@1.5.2

**Current behavior:**
I am trying to developing a stencil standalone component (using ionic core components) that can be used in an Ionic, angular, and Native Javascript Application.

**Debugging:**
Ionic 4: Getting an exception in the tabs entry file (ionic/core). It works as expected if I remove the “@ionic/core” import from index.ts file but then it won’t work in the angular and native javascript projects.

**Expected behavior:**
The component should successfully render in the ionic app

**Steps to reproduce:**

https://github.com/sanaadostmuhammad/stencil-ionic-angular
https://www.npmjs.com/package/sanaa-stencil-components

I am importing my custom component in the ionic photo-gallery project (https://ionicframework.com/docs/angular/your-first-app)
-You will see that the tabs are loaded but not the contents. An error is being thrown in the ion-tabs.entry.js file (ion-tabs.entry.js:141 tab with id: "undefined" does not exist)

**Related code:**

```
My stencil component:
Stencil-component: password-reset.tsx
import { Component, h } from '@stencil/core'; @Component({ tag: 'password-reset', styleUrl: 'password-reset.css', shadow: true }) export class PasswordReset { render() { return [ <ion-item> <ion-label position="floating">Floating Label</ion-label> <ion-input></ion-input> </ion-item> ]; } }

Stencil-component: src/index.ts
import '@ionic/core';

photo-gallery project: src/tab/tab3/tab3.page.html
<ion-content> <stock-finder></stock-finder> </ion-content>

photo-gallery project: src/tab/tab3/tab3.module.ts

import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core'; @NgModule({ .... schemas: [CUSTOM_ELEMENTS_SCHEMA] ... })

photo-gallery project: src/main.ts
import { defineCustomElements } from 'sanaa-stencil-components/loader'; platformBrowserDynamic() .bootstrapModule(AppModule) .catch(err => console.log(err)); defineCustomElements(window);

```

**Other information:**

**Ionic info:** 

```
Ionic:

   Ionic CLI : 5.2.7

Utility:

   cordova-res : 0.6.0 (update available: 0.8.0)
   native-run  : not installed

System:

   NodeJS : v10.16.3
   npm    : 6.11.3
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment]
Same issue as https://github.com/ionic-team/ionic/issues/19726
