### ISSUE TITLE
bug: Customize phonegap-plugin-barcodescanner and ionic cordova plugin add cordova-plugin-network-information

### ISSUE THREAD

**Issue by 08Thug** [ionic-team/ionic#19709]
Hi Team,
In our project we are using

> Customize phonegap-plugin-barcodescanner

and

> ionic cordova plugin add cordova-plugin-network-information

We are getting conflict issue between these two library.Once i Scan the Barcode after that i check for the presence of network at that time app gets crashed.I can't find crash log too!! could you please suggest some solution for this problem.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as Ionic Framework does not manage these native plugins. I recommend you post your question on our [forum](https://forum.ionicframework.com) or our [slack](https://ionic-worldwide.slack.com).
