### ISSUE TITLE
bug:  Angular HttpClient Android {"headers":{"normalizedNames":{},"lazyUpdate":null,"headers":{}},"status":0,"statusText":"Unknown Error","url":null,"ok":false,"name":"HttpErrorResponse","message":"Http failure response for (unknown url): 0 Unknown Error","error":{"isTrusted":true}}

### ISSUE THREAD

**Issue by Sakthivelkandasamy** [ionic-team/ionic#19705]
When I sent a HTTPS post request from and responses form:

{"headers":{"normalizedNames":{},"lazyUpdate":null,"headers":{}},"status":0,"statusText":"Unknown Error","url":null,"ok":false,"name":"HttpErrorResponse","message":"Http failure response for (unknown url): 0 Unknown Error","error":{"isTrusted":true}}

**Comment by Sakthivelkandasamy** [comment]
(_) ___  _ __ (_) ___
  | |/ _ \| '_ \| |/ __|
  | | (_) | | | | | (__
  |_|\___/|_| |_|_|\___|  CLI 4.0.0-rc.9


  Usage:

    $ ionic <command> [<args>] [--help] [--verbose] [--quiet] [--no-interactive] [--no-color] [--confirm] [options]

  Global Commands:

    config <subcommand> ...... Manage CLI and project config values (subcommands: get, set, unset)
    docs ..................... Open the Ionic documentation website
    info ..................... Print system/environment info
    login .................... Login to Ionic Pro
    logout ................... Logout of Ionic Pro
    signup ................... Create an account for Ionic Pro
    ssh <subcommand> ......... Commands for configuring SSH keys (subcommands: add, delete, generate, list, setup, use)
    start .................... Create a new project

  Project Commands:

    build .................... Build web assets and prepare your app for any platform targets
    cordova <subcommand> ..... Cordova functionality (subcommands: build, compile, emulate, platform, plugin, prepare,
                               requirements, resources, run)
    doctor <subcommand> ...... Commands for checking the health of your Ionic project (subcommands: check, list, treat)
    generate ................. Automatically create framework components (alias: g)
    git <subcommand> ......... Commands relating to git (subcommands: remote)
    integrations <subcommand>  Manage various integrations in your app (subcommands: disable, enable, list)
    link ..................... Connect your local app to Ionic Pro
    monitoring <subcommand> .. Commands relating to Ionic Pro error monitoring (subcommands: syncmaps)
    serve .................... Start a local dev server for app dev/testing (alias: s)

**Comment by Sakthivelkandasamy** [comment]
Web Browser Working Fine but Android Mobile Not Working

**Comment by sean118** [comment]
Check out these two issues. They'll probably have a solution for you. It might be a CORS related issue.
https://github.com/ionic-team/capacitor/issues/890
https://github.com/ionic-team/ionic/issues/14410
