### ISSUE TITLE
feat: Allow Ionic to use a custom babel config

### ISSUE THREAD

**Issue by aej11a** [ionic-team/ionic#19704]
# Feature Request

**Ionic version:** React

[x] **4.x**

**Describe the Feature Request**
Allow Ionic to use a custom babel config. This would allow users to use plugins and presets the same way other JS projects do, especially React projects.

**Describe Preferred Solution**
If a `.babelrc` or `babel.config.js` file is present at root, use that config instead of Ionic's built in config. Users may have to use an Ionic preset in custom babel configs along with the plugins and other setting they choose.

**Describe Alternatives**
Allow users to provide babel config in `package.json` or in the Ionic config file

**Related**
[Next.js allows babel config info to be added in a `.babelrc` file](https://nextjs.org/docs#customizing-babel-config)

**Comment by liamdebeasi** [comment]
Thanks for the feature request. Under the hood we just use the Angular CLI, Create React App, etc (depending on your framework). When using React, are you able to just configure your app as shown here: https://github.com/facebook/create-react-app/tree/master/packages/babel-preset-react-app

**Comment by liamdebeasi** [comment]
Actually, it sounds like you might have to eject from Create React App in order to customize the babel config. This is true even if you are not using Ionic React.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I discussed more with the team and you should be able to do this already just as you would with a regular React application. More info here: https://github.com/facebook/create-react-app/issues/167

**Comment by aej11a** [comment]
@liamdebeasi ah I didn’t realize it would behave just like CRA. Thanks for the response!
