### ISSUE TITLE
bug: Unable to parse svg gradient URLs

### ISSUE THREAD

**Issue by 13546777510** [ionic-team/ionic#19710]
# Bug Report

**Ionic version:**
- [x] **3.x**
- [x] **4.x**

**Current behavior:**
In ionic3 and ionic4, they work differently in svg gradient URLs.

**Expected behavior:**
Correctly parse svg gradient URLs and display RGB color selectors when plugins with iro.js are used.

**Steps to reproduce:**
Detailed description: [https://github.com/jaames/iro.js/issues/45](https://github.com/jaames/iro.js/issues/45)

Repository of related code:
[https://github.com/13546777510/iro-ionic3](https://github.com/13546777510/iro-ionic3)
[https://github.com/13546777510/iro-ionic4](https://github.com/13546777510/iro-ionic4)

**Related code:**
![image](https://user-images.githubusercontent.com/20255750/67203516-dd084580-f43d-11e9-949e-c0aa37673cb9.png)

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 4 other plugins)

System:

   ios-sim : 8.0.2
   NodeJS  : v10.16.0 (/usr/local/bin/node)
   npm     : 6.9.0
   OS      : macOS
   Xcode   : Xcode 11.1 Build version 11A1027

```

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 4 other plugins)

System:

   ios-sim : 8.0.2
   NodeJS  : v10.16.0 (/usr/local/bin/node)
   npm     : 6.9.0
   OS      : macOS
   Xcode   : Xcode 11.1 Build version 11A1027

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this issue as loading URLs in a webview is not something that Ionic Framework manages. For context, your application works fine when using Capacitor but does not load the SVG properly when using Cordova, so there is likely some configuration you will need to do when building your Cordova app.

**Comment by 13546777510** [comment]
@liamdebeasi Thank you for your reply. Is there any documentation for my reference?

I have nothing to do with this in google, I hope that your help, thank you very much.

**Comment by liamdebeasi** [comment]
Looks like your app is using the Cordova WebView plugin, so try here: https://github.com/ionic-team/cordova-plugin-ionic-webview
