### ISSUE TITLE
Fixing Page Transition with own fullscreen logic + ANSWER 

### ISSUE THREAD

**Issue by HansKrywaa** [ionic-team/ionic#19715]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior**
During the Page Transition is occours a bug, when using a own fullscreen logic 

<img src="https://user-images.githubusercontent.com/20899975/67207905-c699c400-f414-11e9-97ca-ccedfd92fcbe.gif" width=200>

**Steps to reproduce:**
I provided the Repository here: https://github.com/HansKrywaa/ionic-fullscreen-nav-bug

**Related code and Information:**

For my App i need to have a normal Header and a Scrollable Content, but both must be transparent and i need a Background-Image over the whole Height (Header and Content). And the Content should be not visible if scrolled under the Header. To achieve this i'm setting the Background Information on the ```app-home {}``` Element and the Background of the Header and the Toolbar to none. So far so good, but on a normal .pop Transition the Bug above appears. So i looked into and write my own Transition. I added two Lines to the iOS transition of Ionic, which animates the Contents Parent on the Leave-Page too. This could be seen in my Github Project. 

The added Lines are (about Line 380):
```
const leavingMain = leavingContentEl.offsetParent;
leavingContent.addElement(leavingMain);
```

I added the Transition to the Ionics Configuration "navTransition"

**Result:**

<img src="https://user-images.githubusercontent.com/20899975/67209226-458ffc00-f417-11e9-91b6-90bce4e5b56c.gif" width=200>

As you can see, it works now. So maybe you can go into that a little bit deeper and fix this? Also: I have to declare the Ionic Config as any, becuase it doesn't worked if i so not. The parameters so not match. Maybe you can fix that too?

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : 0.6.0 (update available: 0.8.0)
   native-run  : 0.2.8 (update available: 0.2.9)

System:

   NodeJS : v10.16.3 (/usr/local/bin/node)
   npm    : 6.12.0
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you explain what the original issue is? I'm not quite sure I understand.

**Comment by HansKrywaa** [comment]
@liamdebeasi I think maybe it's related to #16678?

The Page Transition fails when i set the Background Style on the Pages root Selector. That's the issue.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Your solution fixes it for your use case, but it would break the default iOS transition for everyone else. Is there a way to accomplish this without translating the leaving content's offsetParent?

**Comment by HansKrywaa** [comment]
I don't know, is there? Maybe to check in the Animation if the offsetParent has the Background set, because animating it? Is that possible?

Or maybe thinking about a better way to archive having a fullscreen Background and hide the Content Scroll behind the Header? In v3 it was easy possible to set the background to the ionic content because it was splitted in fixed and scrolled content.

**Comment by liamdebeasi** [comment]
Have you tried the suggestion here to set the background on the inner scroll element? https://github.com/ionic-team/ionic/issues/17494#issuecomment-492647992

Ideally, you could just use the `--background` variable on ion-content, but there's a bug in Safari that prevents that from working reliably, so that JavaScript workaround might be your best bet for now.

**Comment by HansKrywaa** [comment]
Both doesn't worked, because it doesn't set the Background behind the Header, only the Content. @liamdebeasi

**Comment by liamdebeasi** [comment]
You will likely need to set `fullscreen=true` on the content for this.

**Comment by HansKrywaa** [comment]
Yeah of course than it worked. But for my case it should not be possible to read Content behind the Header. So with the fullscreen it looks like this if i scroll:

<img width="200" src="https://user-images.githubusercontent.com/20899975/67230810-4d16cb80-f43e-11e9-8f1d-c95873a385bb.png">

But what i want to (and have with my solution) is:

<img width="200" src="https://user-images.githubusercontent.com/20899975/67230830-59028d80-f43e-11e9-8bc4-0d2c01c3560b.png">

**Comment by liamdebeasi** [comment]
Ok I see, thanks for the follow up. I don't think this fix is something we will be able to add to the framework as it breaks the navigation transition for users who are not using background images for their pages. We provide the `navAnimation` config so developers can customize the navigation transition as they see fit (like you are doing now), so I would recommend that approach moving forward.

Thanks!

**Comment by HansKrywaa** [comment]
@liamdebeasi Ok i understand. Thank you. Maybe you can think about an general option to set the Background fullscreen like in my case in a further update 😊
