### ISSUE TITLE
bug: Toast Button cssClass placed inside ShadowDom

### ISSUE THREAD

**Issue by dallastjames** [ionic-team/ionic#19722]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

The `ToastController` gives the user the ability to customize the button that gets rendered. One of these options is `cssClass`. The user is unable to adjust the styling of this button through this css class as the button rendered is inside of the shadow-dom of the `ion-toast` element.

**Expected behavior:**

A) The user can apply a css class to the button inside of the toast. Styles can then be applied to the element based on the CSS class.

OR

B) The user is not able to add a css class to the button inside of the toast element and (ideally) additional css variables are exposed through the ion-toast element similar to the `--button-color` variable to allow controlling the button styles.

**Steps to reproduce:**

https://stackblitz.com/edit/ionic-v4-angular-tabs-egx3ox?file=src%2Fapp%2Ftab1%2Ftab1.page.ts

**Comment by adonig** [comment]
The same applies to `.toast-container` and all the other toast CSS classes. I'm trying to make a good-looking GDPR cookie consent banner with Ionic React and it's just impossible :-(

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20146 and will be available in an upcoming release of Ionic Framework.
