### ISSUE TITLE
bug: Vulnerabilities after upgrading to 4.11.2

### ISSUE THREAD

**Issue by kyleabens** [ionic-team/ionic#19723]
# Bug Report

**Ionic version:**

[x] **4.11.2**

**Current behavior:**

After installing @ionic/angular 4.11.2 I receive "found 7 high severity vulnerabilities" from npm.
`$npm audit fix` does not take care of the issue since some need to be manually reviewed.

**Expected behavior:**

There should be no vulnerabilities with this latest release.

**Steps to reproduce:**

Install @ionic/angular 4.11.2

**Related code:**

Here is one of the vulnerabilities.  They all have to do with the https-proxy-agent package.

```
High            Machine-In-The-Middle                                         

Package         https-proxy-agent                                             

Patched in      >=3.0.0                                                       

Dependency of   @angular/cli [dev]                                            

Path            @angular/cli > @schematics/update > pacote >                  
                  make-fetch-happen > https-proxy-agent                         

More info       https://npmjs.com/advisories/1184
```

**Other information:**

[https://github.com/angular/angular-cli/issues/15878](https://github.com/angular/angular-cli/issues/15878)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.2
   @angular-devkit/build-angular : 0.802.1
   @angular-devkit/schematics    : 8.2.1
   @angular/cli                  : 8.2.1
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.2.1
   @capacitor/core : 1.2.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.15.0 (/usr/local/bin/node)
   npm        : 6.11.3
   OS         : macOS Mojave
   Xcode      : Xcode 11.1 Build version 11A1027
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. It looks like these are dependencies of the Angular CLI, not Ionic Framework. I do see these warnings, but I don't see anything related to Ionic Framework. Are there warnings for the framework that I should be seeing?

**Comment by kyleabens** [comment]
You are correct, sorry about that.
