### ISSUE TITLE
bug:,IonBackButton and browser back button have different behaviour

### ISSUE THREAD

**Issue by anuragnagardeveloper** [ionic-team/ionic#19724]
steps to reproduce:
Step1 : ionic start app1 --type=react (choose sidemenu from option)
Step2 : ionic serve
put a link in home page <Link to="/home/list">List</Link>

Now click on the link a and click on browser back button. It seems that the list page is not being popped from history.

**Comment by elylucas** [comment]
Hi @anuragnagardeveloper,

I'm not quite following what you are saying. Could you provide a sample repo to reproduce the issue?

**Comment by elylucas** [comment]
Hi @anuragnagardeveloper, I just tested your repo against 4.11.3 and it appears to be fixed. Let us know if any issues persist.

Thanks

**Comment by anuragnagardeveloper** [comment]
Hi @elylucas 
thanks it worked in 4.11.3 but swipe back is not working. how I could allow navigating back to previous page but just swiping in ios
