### ISSUE TITLE
Ionic4 After the screen page disappears, there will be a long time for the white screen to enter the home page.

### ISSUE THREAD

**Issue by AlwaysLoveme** [ionic-team/ionic#19738]
# Bug Report

**Ionic version:**
Ionic:

   Ionic CLI                     : 5.4.4 (C:\Users\admin\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 5 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (D:\Soft\Ionic_ENV\sdk)
   NodeJS            : v10.16.0 (D:\Soft\Nodejs\node.exe)
   npm               : 6.12.0
   OS                : Windows 10
[x] **4.x**

**Current behavior:**
After the screen page disappears, there will be a long time for the white screen to enter the home page. and console no errors, no warnings.

**Expected behavior:**
i wish when the screen page disappears, enter the home page immediately and no white screen；

**Steps to reproduce:**
1: ionic cordova platform add android 
2: ionic cordova build android --prod

```
1. config.xml
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="19" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="10000" />
    <preference name="FadeSplashScreenDuration" value="1000" />
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="FadeSplashScreen" value="true" />
    <preference name="ShowSplashScreen" value="true" />
    <preference name="ShowSplashScreenSpinner" value="false" />
```

**Comment by AlwaysLoveme** [comment]
there is my git code : [( https://github.com/AlwaysLoveme/demo.git)]

**Comment by AlwaysLoveme** [comment]
there is my git demo code: [https://github.com/AlwaysLoveme/demo.git](https://github.com/AlwaysLoveme/demo.git)

**Comment by liamdebeasi** [comment]
Thanks for the issue. It sounds like your app is just taking a long time to start up. I would recommend hiding the splash screen only once [Platform.ready](https://ionicframework.com/docs/utilities/platform#ready-promise-string-) has resolved. Is there a particular issue in Ionic Framework you are running into?

Otherwise, these kinds of situations are better suited for our [forums](https://forum.ionicframework.com) or our [slack](https://ionic-worldwide.slack.com).

**Comment by AlwaysLoveme** [comment]
Thanks for your reply and suggestion. Since i update my android google chrome webview to the latest version from google play, it happens like that my app is taking a long time to start up home page, so i turn back to the chrome version which is 74.0.3729.136, then it is normal.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I am going to close this as it doesn't sound like this is any particular bug in Ionic Framework. If you can point to part of Ionic Framework that you think is related to the issue, I'm happy to take a look. Thanks!
