### ISSUE TITLE
Ionic 4 app is slow in android 7.1

### ISSUE THREAD

**Issue by yogeshshsf** [ionic-team/ionic#19730]
Hi, I am developing an app ionic 4 with angular 7. It runs pretty good in desktop Chrome or android device with latest configuration (**4gb ram, 32gb storage, android version 8/9**). When I packaged it and installed in android device(**2gb ram, 8gb storage, android version 7.1**), It runs too slowly. for example: if you open a modal/popup in latest config device, it takes **1000-1500ms** whereas in another device it is taking **4000-6000ms**.
Cordova uses android’s Web view to run the applicaiton, the bad performance is due to default browser?
In old device the chromium version installed in 66.
if anyone have any suggestion it is much appreciated. thanks in advance

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you point to a particular component that you feel is slow? If you are looking for suggestions on how to speed up your app, that kind of question is better suited for our [forum](https://forum.ionicframework.com) or our [slack](https://ionic-worldwide.slack.com).

**Comment by barocsi** [comment]
There is a whole thread for it and it's a valid issue rendering all ionic features subtle in the aspect of having a fundamental perfomance issue with almost every app.
Please before releasing another totally useless feature (that would be also full of bugs) burn your tickets, the community had already put in a great effort to test this.
https://forum.ionicframework.com/t/ionic-4-slow-performance-on-user-interaction

**Comment by yogeshshsf** [comment]
It will be slow if i use third party lib ex:(https://www.npmjs.com/package/ionic2-calendar) is open book the schedule, to open the popup and load a library it takes 5-6 seconds. Even opening modal(ion-modal) takes 2-3 seconds.

**Comment by yogeshshsf** [comment]
My application size is 28mb and i use some 10 plugins in my application. i have around 35-40 pages includes(pages and modals). will the performance slow down if we use more library and plugins?

**Comment by liamdebeasi** [comment]
Yes, plugins and 3rd party libraries will definitely slow down the application.

Questions of performance are always tricky since the performance is going to vary from device to device. I would recommend removing 3rd party plugins and libraries from your application to see which ones are slowing down your application the most.

If, after removing all 3rd party components, you still feel your app if very slow please feel free to open a new issue with a code reproduction, and we can take a closer look. Thanks!
