### ISSUE TITLE
bug: [react] ionViewDidEnter event not firing the first time page shows on screen

### ISSUE THREAD

**Issue by SatoAV** [ionic-team/ionic#19741]
# Bug Report

**Ionic version:**
[x] **4.11.0**

**Current behavior:**
Somehow `ionViewDidEnter` event does not fire when the page first enters the screen.
To overcome this, I add `componentDidMount` with the same logic that I need for `ionViewDidEnter`, to handle the first appearance of the page. All the consecutive page appearances are handled just fine. Although this works, it seems like unnecessary duplication of code, and also counter-intuitive to what `ionViewDidEnter` event is representing

**Expected behavior:**
`ionViewDidEnter` should also fire on the first page appearance.

**Steps to reproduce:**
It should reproduce with any multi-page application.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.2
   Ionic Framework : @ionic/react 4.11.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am testing this with an Ionic React starter and `ionViewDidEnter` is being called as expected.

**Comment by SatoAV** [comment]
Seems like it is more of an issue with Redux `connect` HOC.

Although when trying to reproduce the issue on a fresh repo, I encountered another bug.
I'll close this issue and open another one.
