### ISSUE TITLE
bug: [React] `IonToolbar` placed outside of `IonContent` doesn't participate in page transitions

### ISSUE THREAD

**Issue by SatoAV** [ionic-team/ionic#19742]
# Bug Report

**Ionic version:**

[x] **4.11.0**

**Current behavior:**
I have a multi-page application with one page having a search bar above IonContent.
I basically reproduced example on this page of Ionic docs:
https://ionicframework.com/docs/api/searchbar

But probably because `IonToolbar` that is holding the searchbar is outside of `IonContent`, it doesn't participate in the page transition like the rest of components do. It just pops in when I navigate to the page with the searchbar.

Here's how it looks:
![bandicam 2019-10-24 14-43-46-216](https://user-images.githubusercontent.com/1641218/67482747-f17e5500-f66c-11e9-8558-e8b5304dfeb1.gif)

**Expected behavior:**
I couldn't find any other meaningful way to pin my toolbar to top of the content, so that it doesn't scroll. And since I pulled my layout straight from the docs, I assume it should animate like all the other pages, e.g. `IonToolbar` should animate just like the `IonContent`.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.2
   Ionic Framework : @ionic/react 4.11.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide the markup where you declare your IonToolbar? IonToolbar typically exists in either IonHeader or IonFooter components.

**Comment by SatoAV** [comment]
@liamdebeasi Indeed I wasn't placing that `IonToolbar` into `IonHeader`. I'll check if that fixes the issue and get back to you.

**Comment by SatoAV** [comment]
Yeah, It was my mistake, sorry for false alarm ^^"
