### ISSUE TITLE
bug: [ionic4] Ion Radio Icon not displayed on android

### ISSUE THREAD

**Issue by maerlynflagg** [ionic-team/ionic#19744]
# Bug Report

**Ionic version:**
 **4.11.2**

**Current behavior:**
<ion-radio> displayed not an icon on android, but on ios the icon is displayed. so the user doesn't know, the element on android is checked.

**Expected behavior:**
the icon should be displayed on android too.

**Steps to reproduce:**

i created ion-radio-group. in there are ion-item with ion-label and ion-radio.

**Related code:**

simply looks so:

***EDIT***

```
<ion-radio-group [(ngModel)]="element.value">
 <ion-item>
   <ion-label class="ion-text-wrap">{{listElement.label}}</ion-label>
   <ion-radio slot="start" [checked]="listElement.isChecked" [value]="listElement.value"
           [disabled]="element.singleControl ? element.singleControl.disabled : null"
           (click)="onRadioClicked(listElement, element)"></ion-radio>
   </ion-item>
</ion-radio-group>
```

runtime HTML of the working ios looks so:

![ionRadio2](https://user-images.githubusercontent.com/13437496/67496140-41184d00-f67c-11e9-9368-96d80d0f1a64.jpg)

![ionRadio1](https://user-images.githubusercontent.com/13437496/67496033-16c68f80-f67c-11e9-82c7-65cf310cf93b.jpg)

runtime HTML of the **not working** android looks so:

![ionRadio4](https://user-images.githubusercontent.com/13437496/67496172-4e353c00-f67c-11e9-9327-c8bbfc8a36b2.jpg)

![ionRadio3](https://user-images.githubusercontent.com/13437496/67496078-2514ab80-f67c-11e9-9668-6975e793d61a.jpg)

**the html output of the checked radio on android looks like the output of ios.**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.4
   Ionic Framework               : @ionic/angular 4.11.2
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v10.16.3
   npm               : 6.11.3
   OS                : Windows 10
```

**Comment by proemke** [comment]
remove  </ion-item>

**Comment by maerlynflagg** [comment]
> remove `</ion-item>` or add `<ion-item>` before `<ion-label>`

Oh Sorry, writing issue. in my original source, the ion-item is set (look to the pics).

the original source looks like this:

```
<ion-radio-group [(ngModel)]="element.value">
  <ion-item>
    <ion-label class="ion-text-wrap">{{listElement.label}}</ion-label>
    <ion-radio slot="start" [checked]="listElement.isChecked" [value]="listElement.value"
           [disabled]="element.singleControl ? element.singleControl.disabled : null"
           (click)="onRadioClicked(listElement, element)"></ion-radio>
   </ion-item>
</ion-radio-group>
```

**Comment by marpstar** [comment]
we had this issue after upgrading to 4.11 as well. We eventually threw away the `<ion-radio-group>` and handled the `checked` state on our own: 

before:

```
  <ion-radio-group [(ngModel)]="selectedBasemapId">
    <ion-item *ngFor="let map of basemaps" (click)="selectionChanged(map.id)">
        <ion-label [color]="selectedBasemapId === map.id ? 'secondary' : undefined" left>{{map.title}}</ion-label>
        <ion-radio slot="end" mode="ios" color="secondary" [value]="map.id"></ion-radio>
    </ion-item>
  </ion-radio-group>

```

after:

```
  <ion-item *cdkVirtualFor="let map of basemaps;" (click)="selectionChanged(map.id)" lines="full">
      <ion-label [color]="selectedBasemapId === map.id ? 'secondary' : undefined" left>{{map.title}}</ion-label>
      <ion-radio [checked]="selectedBasemapId === map.id" slot="end" mode="ios" color="secondary" value="{{map.id}}"></ion-radio>
  </ion-item>
```

**Comment by maerlynflagg** [comment]
thank for suggestion. i spend time to try different ionic 4 versions:

- 4.11.0
- 4.10.3
- 4.7.1 (like the ionic start blank template)

everywhere the android version of ion-radio not display an icon, but the radio is checked.

**Comment by maerlynflagg** [comment]
our temporary solution is to use mode="ios" to fix it.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you testing this on a physical device or an emulator? I am testing this on an Android device running Chrome 77, and everything appears to be rendering correctly.

**Comment by maerlynflagg** [comment]
> Thanks for the issue. Are you testing this on a physical device or an emulator? I am testing this on an Android device running Chrome 77, and everything appears to be rendering correctly.

First i found the issue in ionic:serve mode Chrome (Device View, Pixel 2). Chrome version is 77.0.3865.120.

so i hoped, is only a serve problem, so i checked out on real device, Google Pixel 3, Android 10. the was the issue too. The google chrome version of my android device is 78.0.3904.62.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you provide a repo with the code required to reproduce this issue? I am unable to reproduce this behavior.

**Comment by maerlynflagg** [comment]
> Thanks for the follow up. Can you provide a repo with the code required to reproduce this issue? I am unable to reproduce this behavior.

i will try to give you an example repo.
