### ISSUE TITLE
bug: @ionic/react IonBackButton on destination disappears after going back from origin

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic#19752]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Going from Page A -> Page B -> Page C -> ion-back-button to Page B causes the ion-back-button on Page B to disappear.

**Expected behavior:**

I would expect the back button on Page B to not disappear

**Steps to reproduce:**

Link to repo: https://github.com/liamdebeasi/ionic-react-bug

1. Run app. You will start on the Page A.
2. Click the + icon in the FAB button. This will bring you to Page B. Notice the IonBackButton that is visible.
3. Click "Go to Child Page". This will bring you to Page C.
4. Click the IonBackButton. This will bring you back to Page B.
5. Notice that the IonBackButton on Page B no longer shows up. It is still in the DOM, but has `display: none` set.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.4 (/Users/liamdebeasi/.nvm/versions/node/v10.15.0/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.2

Utility:

   cordova-res : 0.6.0 (update available: 0.8.0)
   native-run  : 0.2.7 (update available: 0.2.9)

System:

   NodeJS : v10.15.0 (/Users/liamdebeasi/.nvm/versions/node/v10.15.0/bin/node)
   npm    : 6.9.2
   OS     : macOS Mojave
```

**Comment by elylucas** [comment]
This appears to be fixed by the issue reported in #19731 and will be out soon in 4.11.3. If you want to test with a dev build, the fix is currently in @ioinic/react@4.12.0-dev.201910281628.f70e71a and @ionic/react-router@4.12.0-dev.201910281628.f70e71a
.

Thanks
