### ISSUE TITLE
bug: IonReactRouter does not keep query params after pushing a page

### ISSUE THREAD

**Issue by puku0x** [ionic-team/ionic#19753]
# Bug Report

**Ionic version:**

[x] **4.11.2**

**Current behavior:**

The query parameters of a page are cleared after pushing another page.

This bug seems to be caused by `IonReactRouter` and it has the previous page re-rendered with no query parameters.

**Expected behavior:**

The query parameters of the previous page are saved.

**Steps to reproduce:**

1. Make first page
2. Make second page
3. Routing pages like
```tsx
<IonReactRouter>
  <IonRouterOutlet>
    <Route exact path="/" render={() => <Redirect to="/users" />} />
    <Route exact path="/users" component={UserListPage} />
    <Route exact path="/users/:id" component={UserDetailPage} />
  </IonRouterOutlet>
</IonReactRouter>
```
4. Access the first page with query parameters `/users?name=test`
5. Push the second page `routerLink="/users/1"`
6. The query parameters are gone

**Related code:**
https://codesandbox.io/embed/ionicreact-sample-2e40r

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI : 5.4.4

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by puku0x** [comment]
If the page had some effects they were called after another page was pushed.
```tsx
const location = useLocation();
const params = new URLSearchParams(location.search); // ?name=test
const name = params.get("name") || "";

useEffect(() => {
  fetchUserList(...);  // called even after pushing a page 😵
}, [name]);            // `name` should not change during page transition
```

**Comment by elylucas** [comment]
Hi @puku0x,

I was able to get your sandbox to work with a few code changes to the users list page:

https://codesandbox.io/s/ionicreact-router-with-query-params-7qxzu?fontsize=14

The biggest thing was that the name variable was being set on each render, which is was causing the onChange event of the input search to fire, which was causing chaos when trying to navigate to the detail page. Take a look at the new sandbox and if you have more questions or think an issue still exists let us know.
