### ISSUE TITLE
bug: Ionic/react does not work with Electron

### ISSUE THREAD

**Issue by jepiqueau** [ionic-team/ionic#19767]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When running ```ionic cap open electron``` i got the following error 
```4 GET file:///static/css/10.dfc40163.chunk.css net: ERR_FILE_NOT_FOUND ``` 
and looking at Network in Chrome Dev tools i saw 
```10.dfc40163.chunk.css, main.437a334f.chunk.css, 10.a2f31e71.chunk.js, main.28c6e387.chunk.js failed to load ``` 
**Expected behavior:**

Should work
**Steps to reproduce:**

``` 
ionic start myapp blank --type=react
cd myapp
ionic init "My React App" --type=react --force
ionic integrations enable capacitor
npm run build
ionic cap add android
ionic cap add ios
ionic cap add electron
npm run build
ionic cap copy
ionic cap open electron
``` 
```ionic cap open ios``` and ```ìonic cap open android``` work fine
**Related code:**

```
insert short code snippets here
```

**Other information:**

in Capacitor#random Slack @velocissimo open the issue on October 26 2019
**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.2

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3 (/usr/local/bin/node)
   npm    : 6.12.0
   OS     : macOS Catalina


```

**Comment by jepiqueau** [comment]
changing the base href tag to ```<base href="./" /> ``` as it is required for an ionic/angular electron app doesn't help in that case

**Comment by BamButz** [comment]
Ive encountered the exact same problematic.
Did you find any workaround?

**Comment by JamesBrightman** [comment]
Same issue still ^^

**Comment by vinidiktov** [comment]
Same here ^^

**Comment by JamesBrightman** [comment]
By the looks of it, this hasn't worked since October last year and there doesn't seem to be a fix. I think it's a bit disingenuous to claim that ionic-react is compatible with Electron when there seems to be a huge issue in compatibility.

**Comment by mhartington** [comment]
Hey folks. This issue isn't necessarily related to Ionic, but a mix of path-based routing and capacitor-electrons way of loading files. I would open an issue on the capacitor repo so that we can track it and discuss ideas for handling this. 

https://github.com/ionic-team/capacitor

**Comment by elylucas** [comment]
Hi @JamesBrightman, @BamButz, @vinidiktov, @jepiqueau, 

There are a few things to do to get the asset loading and routes right in ionic react and electron:

1.  Update the base href in the index.html file to './':
`<base href="./" />`
2. In your React projects package.json file, add homepage: "./" to the JSON:
` "homepage": "./",` 
This instructs CRA to make the urls relative and not absolute
3. Add a route to handle the `/index.html` path that will load initially and have it redirect to your main route:
`<Redirect from='/index.html' to="/tab1" />`

There are quite a few things we can do in Capacitor to make the experience better, but these should get you up and running.

**Comment by jepiqueau** [comment]
@elylucas Can you explain a bit more the Point 3

**Comment by elylucas** [comment]
@jepiqueau 

When your app launches in electron, it will go to path_to_your_app/index.html, and react will see the index.html as the route it is trying to match, versus the normal '/' if you hit your app through a web server. Therefore, create a route that will route from '/index.html' to your normal root path.

**Comment by jepiqueau** [comment]
@elylucas trying to understand what you said, but could not succeed can you give us the code of the App.tsx where you declare the new route and its redirection to "/tab1" or "/home" Many thanks

**Comment by ArcticHen7** [comment]
@elylucas Thank you very much! Step 2 works perfectly for a React-based app importing both Ionic and Capacitor (not the original setup of this issue I know).
