### ISSUE TITLE
conditional col size  (size="8" or size="6" etc)

### ISSUE THREAD

**Issue by wallstudios** [ionic-team/ionic#19761]
I want to be able to set a fixed col size e.g. size="8" for a certain condition and then set to something else under another condition.

eg
<ion-col (size)="var"></ion-col>
or
<ion-col [size="8"]="someBooleanValue? true : null"></ion-col>

I can replace the col using an *ngIf statement but means a lot of extra code in the template.

Considered [ngClass]="{'first': true, 'second': true, 'third': false}"
But that means writing additional styles to override the default col widths.

thoughts?

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is already possible in Ionic Framework.

Example usage:

`<ion-col [size]="someBooleanValue ? '4' : '8'"></ion-col>`

**Comment by wallstudios** [comment]
Thank you. couldn't find any examples of this. Cheers, : )
