### ISSUE TITLE
bug: ion-item-sliding stops working, if page is closed with the slider open(exposed buttons)

### ISSUE THREAD

**Issue by aardrasystems** [ionic-team/ionic#19762]
Hi All

Please see my example code below.  When i swipe the ionic card so that i can see the two buttons but do not click on any of them, but was to exit the page. Then when i re launch the page, the slider do not work at all.

I got the latest version of ionic, but i can not manage to solve this issue. 

Please advice.

`   <ion-card >
      <ion-item-sliding>     
            <ion-item detail>    
            Name:{{nodedata.iot_devicename}}<br/>
            Description:{{nodedata.iot_description}}<br/>
            ID:{{nodedata.azureDeviceID}}<br/>        
            Version:{{nodedata.iot_version}}<br/>       
            IMEI:{{nodedata.iot_imei}}<br/>
            CCID:{{nodedata.iot_ccid}}<br/>
            IP:{{nodedata.iot_ip}}<br/>
            Message TimeStamp:Time: {{Azure.local_time(nodedata.iot_time_stamp)}}<br/><br/>
            </ion-item>
        <ion-item-options side="start" >                               
                  <ion-item-option  (click)="new_task()" class="newtask">New<br/> Task</ion-item-option>                   
                  <ion-item-option  (click)="task_list()" class="task">View<br/>Tasks</ion-item-option>                   
        </ion-item-options>                        
      </ion-item-sliding>    
    </ion-card>`

**Comment by liamdebeasi** [comment]
Please provide a repo with the code required to reproduce this issue. I am unable to reproduce this issue using the code snippet you have provided.
