### ISSUE TITLE
How to fix map wobbles during scrolling

### ISSUE THREAD

**Issue by MalikRizwanAwan** [ionic-team/ionic#19780]
**Ionic version:**

[x] **4.x**

**I am working on ionic 4 app.in my application Map section on venue page wobbles when moving at the moment if i scroll quick enough the map follows the screen and appears sticky. I dont know how to fix this issue. Any help would be appreciated..** 

[ ] bug report
[ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**
loadMap() {
        const location = new LatLng(this.venue.latitude, this.venue.longitude);

        this.map = GoogleMaps.create('map_canvas', {
            camera: {
              target: location,
              zoom: 18,
              tilt: 0
            }
        });

        const marker: Marker = this.map.addMarkerSync({
            title: this.venue.name,
            snippet: this.venue.strapline,
            position: location,
            animation: GoogleMapsAnimation.BOUNCE
        });
    }:
**

```
<div style="position: fixed; height: 30vh ;width: 100%">
        <div  id="map_canvas" ></div>
    </div>
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
You might need to disable scrolling on whatever container the map is in. I am going to close this as this is more of a support question. For further help with this, I recommend posting on our [forums](https://forum.ionicframework.com) or our [slack](https://ionic-worldwide.slack.com). Thanks!
