### ISSUE TITLE
bug: Ionic React with IonTabs throws "IonTabs must contain an IonRouterOutlet" error

### ISSUE THREAD

**Issue by abird** [ionic-team/ionic#19790]
I am using ion-tabs in an Ionic React app. Although I am using React routing, I am not using an IonRouterOutlet within ion-tabs because I am using IonRouterOutlet at a higher level, so I just use Switch within ion-tabs. 

If I try to use the React component, IonTabs, instead of the regular ion-tabs component, it throws the "IonTabs must contain an IonRouterOutlet" error. This error is incorrect since it is not necessary to use IonRouterOutlet within IonTabs.

**Comment by elylucas** [comment]
Hi @abird,

The IonRouterOutlet is typically required to let the tabs know where to render the tab you clicked on. Could you provide a sample repo with your use case and we can take a look and see if we can make it work?

Thanks

**Comment by abird** [comment]
Here's a test repository: [https://github.com/abird/IonTabs-Test/tree/master](https://github.com/abird/IonTabs-Test/tree/master)

**Comment by austin43** [comment]
This raises an interesting point.  The documentation of how you can use ion-tab here https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#rethinking-tabs is different from having IonRouterOutlet forced at the top level.  What makes this extra confusing is the IonRouterOutlet requirement is not shown in the example for react ion-tabs: https://ionicframework.com/docs/api/tabs.

**Comment by Alain00** [comment]
> IonTabs must contain an IonRouterOutlet

I was having this too, but even adding IonRouterOutlet i can't get it work, the ion-tabs documentation is't very clear respect to this, here is my code
`Tabs.tsx`
```tsx
<IonApp>
            <IonReactRouter>
                <IonPage id="main">
                    <IonTabs>
                        <IonRouterOutlet>
                            <Route path='/tabs/:tab(home)' component={Home} exact />
                            <Route path='/tabs/:tab(test)' component={Test} exact />
                            <Redirect from='/tabs' to='/tabs/home' />
                        </IonRouterOutlet>

                        <IonTabBar slot='bottom'>
                            <IonTabButton tab='home' href='/tabs/home'>
                                <IonLabel>Home</IonLabel>
                            </IonTabButton>
                            <IonTabButton tab='test' href='/tabs/test'>
                                <IonLabel>Test</IonLabel>
                            </IonTabButton>
                        </IonTabBar>
                    </IonTabs>
                </IonPage>
            </IonReactRouter>
        </IonApp>
```
But i can't switch between tabs, this is only showing the Home component, that is the default.
I'm using nested routers, so the Tabs component is't the root component. Please if someone can tell me what is wrong here

**Comment by austin43** [comment]
@elylucas Is there possibly some forthcoming guidance or updates surrounding ion-tabs documentation and/or bugfixes for ionic/react?

**Comment by elylucas** [comment]
Hello,

We are updating the tabs docs to fix the incorrect usage of them, thanks for pointing that out.

The best example right now of Tabs usage is from the latest ionic-react-conf app here https://github.com/ionic-team/ionic-react-conference-app/blob/master/src/pages/MainTabs.tsx#L17

Doing a new tabs starter shows how to use them in a simple tabs app as well.

Thanks!

**Comment by sabahang** [comment]
@Alain00 did you find any answers? my problem is the same that I'm using nested routers because the IonTabs page is't the root page (Login Page is where the app starts and then I redirect to IonTabs page). if I don't use IonRouterOutlet in IonTabs I get an error that "IonTabs must contain an IonRouterOutlet" and if I do use IonRouterOutlet in IonTabs it doesn't work. Is nesting Routers even a correct practice? If not, how else can I use router when IonTabs view isn't my main view

**Comment by abird** [comment]
Here is the solution that works for me. At the top level I do the regular:

```
    <IonApp>
      <IonReactRouter>
        <MainMenu />
        <IonRouterOutlet id="main">
          <Route ... ></Route>
          <Route ... ></Route>
        </IonRouterOutlet>
      </IonReactRouter>
    </IonApp>
```

On the page where I use tabs, I have:

```
		<ion-tabs>
			<IonPage>
				<Header ... />
				<Switch>
					<Route path="/:tab(red)"><Red /></Route>
					<Route path="/:tab(green)"><Green /></Route>
					<Route path="/:tab(blue)"><Blue /></Route>
				</Switch>
				<IonTabBar slot="bottom">
					{tabsData.map(([title, id, icon]) => (
						<IonTabButton tab={id} href={"/" + id} key={id}>
							<IonIcon icon={getIcon(icon)} />
							<IonLabel>{title}</IonLabel>
						</IonTabButton>
					))}
				</IonTabBar>
			</IonPage >
		</ion-tabs>
```
I'm using <ion-tabs> instead of <IonTabs> to work around the "IonTabs must contain an IonRouterOutlet" issue.
