### ISSUE TITLE
Ionic-4 web application does not work on windows-10

### ISSUE THREAD

**Issue by dixitsoftware** [ionic-team/ionic#19807]
**Ionic version:**

[x] **4.x**

**I'm submitting a ...** 

[ ] bug report

**Current behavior:**

When I open Ionic-4 web app on windows-10 platform having touchscreen laptops the ionic pages getting freeze,  it is not allowing me to key in any input and choose anything from drop-down. The side menu works fine. Not sure what is bothering here, is this issue with Ionic-4 or windows-10 or am I missing something here..

**Expected behavior:**
It should allow me to key in input and navigate in a page, it should not get freeze

**Steps to reproduce:**
I have just done prod build i.e. ionic build --prod --release and deployed to AWS

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

Ionic:

   Ionic CLI                     : 5.2.5 (C:\Users\Pavan\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 21 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (D:\softw\Android_dev_kit\Android_sdk\sdk)
   NodeJS            : v10.16.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 8.1

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by dixitsoftware** [comment]
Hi, thanks for your response, I resolved the issue by adding the browser platform to the project and I did production build of the app and deployed, and it is working fine.
