### ISSUE TITLE
hardwareBackButton not working

### ISSUE THREAD

**Issue by anuragnagardeveloper** [ionic-team/ionic#19819]
Hi

hardwareBackButton mentioned at https://ionicframework.com/docs/react/config is not working. When we move from one route to another then clicking on android back button must navigate to the previous route, but its not working. Although it is working on ionic-dev-app but not on the capacitor app.

**Comment by anuragnagardeveloper** [comment]
Hi 
Any updates over this?

**Comment by elylucas** [comment]
fix released in 4.11.4

**Comment by it-one-mm** [comment]
not working either
`
const App: React.FC = () => {
  
  setupConfig({
    hardwareBackButton: true
  });

return(<div><div>);
}
`
