### ISSUE TITLE
bug: ion-label floating error

### ISSUE THREAD

**Issue by Fanny0815** [ionic-team/ionic#19812]
# Bug Report

**Ionic version:**

[x] **4.11.2**

**Current behavior:**
The floating label is not shown on an input field if you set the background-color of the input field.

**Expected behavior:**
The label text should be visible on the input field.

**Steps to reproduce:**

Create an ion-label with floating attribute and an input field. Set the background-color of the input field to rgb(240, 240, 240).

**Related code:**

```
<ion-item lines="none">
   <ion-label position="floating">Password</ion-label>
   <ion-input type="password" value="" [(ngModel)]="password"</ion-input>
</ion-item>
```
```
    ion-label {
      color: black;
    }
    ion-input {
      background-color: rgb(240, 240, 240);
    }
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.11.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v10.15.1
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by brandyscarney** [comment]
I'm not able to reproduce this with the code provided: https://codepen.io/brandyscarney/pen/oNgErMJ

Could you please provide more information to reproduce? Thanks!
