### ISSUE TITLE
swipeBackEnabled not working

### ISSUE THREAD

**Issue by anuragnagardeveloper** [ionic-team/ionic#19818]
Hi

swipeBackEnabled mentioned at https://ionicframework.com/docs/react/config is not working on ios. When we move from one route to another then swiping back should go to previous route, but nothing happens. Following is the code I am using-

import {setupConfig} from '@ionic/react'
setupConfig({
	mode:'ios',
swipeBackEnabled:true
});

**Comment by anuragnagardeveloper** [comment]
Hi 
Any updates over this?

**Comment by elylucas** [comment]
fix released in 4.11.4
