### ISSUE TITLE
feat: @ionic/storage with React

### ISSUE THREAD

**Issue by not-a-designer** [ionic-team/ionic#19824]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

@ionic/storage has a dependency that comes from @angular/core, so it is incompatible to use in a React App
file: ./node_modules/@ionic/storage/index.d.ts
```
import { ModuleWithProviders } from '@angular/core';
```

**Describe Preferred Solution**

Platform-independent way to add key/value pairs to the local storage

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by ebk46** [comment]
Have you tried the Capacitor plugin? https://capacitor.ionicframework.com/docs/apis/storage/
That, or just using `localStorage` should work.

**Comment by elylucas** [comment]
Hi, yes, as @ebk46 suggested, give the Capacitor storage a try. We are focusing native and web api access for Ionic/React through Capacitor.
