### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by shyampatrick** [ionic-team/ionic#19835]
I was using Ionic Icons or IonIcons in my MOOC but it seems that it isn't working as it should - the <ion-button name="ioniconame"> doesn't show the icon - I used a workaround using class="md-ioniconname" but it stopped working as well. The slot is on the bar - it is highlighted when you run the mouse over it but it doesn't show - I thought it may be a good bug to report

**Comment by peanut-JXY** [comment]
> I was using Ionic Icons or IonIcons in my MOOC but it seems that it isn't working as it should - the doesn't show the icon - I used a workaround using class="md-ioniconname" but it stopped working as well. The slot is on the bar - it is highlighted when you run the mouse over it but it doesn't show - I thought it may be a good bug to report

what happen？

**Comment by shyampatrick** [comment]
Hi

Sorry I wasn’t detailed enough.

I used the icons (in a plain Ionic + JS project) in the way recommended on the webpage. <ion-icon name=”icon”> - It didn’t turn up. So I browsed around the web and found this: <ion-icon class=”icon >. Then I went into Angular/Ionic. It was supposed to be automatically included inside angular/ionic but it only worked when I added the Link attribute to the index page like in the plain Ionic + JS way, and only with <ion-icon class=”icon” > not name=”icon” like stated in the docs. The button is noticeable when you hover over it but it doesn’t display the icon. <I class=”icon”> works as well. I think it’s a bug.

Anyway, I was wondering – is there a dependency in package.json for ionicons? I didn’t see one – maybe my project is missing the dependency.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by brandyscarney** [comment]
Yes you need to install ionicons via npm or include it with a script tag. There's more info on ionicons usage here: https://ionicons.com/usage

**Comment by brandyscarney** [comment]
Closing this as there have been no updates for awhile so I assume it is working now. If you're still seeing an issue please let us know with more steps to reproduce, thanks!
