### ISSUE TITLE
Ionic 4, where is setPages ? 

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/ionic#19833]
Is there an equivalent to the old setPages in Ionic 4

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is more of a support question.

Ionic 4 (in particular Ionic Angular) uses the Angular Router, so `setPages` was removed in favor of the solutions that the Angular Router provides. I would recommend looking at the [Angular Router Documentation](https://angular.io/guide/router) or asking your question on our [forums](https://forum.ionicframework.com/) or our [slack](https://ionic-worldwide.slack.com/). Thanks!
