### ISSUE TITLE
bug: Cannot re-open IonAlert in React

### ISSUE THREAD

**Issue by schontz** [ionic-team/ionic#19841]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

After dismissing `IonAlert` it cannot be redisplayed when requested via `isOpen={true}`.

**Expected behavior:**

Every time `isOpen={true}` the alert should appear.

**Steps to reproduce:**

Code sample: https://stackblitz.com/edit/react-bd4qyi
1. Click "Show Alert" to display the alert.
2. Dismiss the alert via background or buttons
3. Click "Show Alert" again. No alert is shown.
4. View console, which says that `showAlert = true`

**Comment by elylucas** [comment]
fix released in 4.11.4

**Comment by schontz** [comment]
Thanks! 👍
