### ISSUE TITLE
Issue in Hardware backbutton...

### ISSUE THREAD

**Issue by 08Thug** [ionic-team/ionic#19844]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I’ve navigated every page,and made use of hardware back button for coming to previous page every thing is working fine only issue is while opening the app (Homepage) before making any changes on pressing the back button the app terminates without confirmation but on making changes like a click or navigating to other page and coming back to the home page if we now press back button the app terminates with the confirmation alert

**Expected behavior:**

I need that confirmation message  before terminating the app on the first push of backbutton on opening the application.

**Other information:**

I’ve used android version (OREO)8 in this application it shows these error on degrading the version to (LOLLIPOP) 5 its working perfectly without any issues.
**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.7 
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 7 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 (update available: 0.2.9)

System:

   Android SDK Tools : 26.1.1 (/home/bsetec/Android/Sdk)
   NodeJS            : v11.12.0 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : Linux 4.15

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has already been noted in https://github.com/ionic-team/ionic/issues/16611, but I will be sure to add your use case to our back button issue tracker. For further updates, feel free to follow the issue I linked to. Thanks!
