### ISSUE TITLE
bug: Async issue with IonLoading when unmounted causes it to stay on screen forever

### ISSUE THREAD

**Issue by aub** [ionic-team/ionic#19859]
# Bug Report

**Ionic version:**

[x] 4.11.3

**Current behavior:**
I wish I had a more accurate reproduction scenario, but what's happening is that in my app if I use the back button to move between pages and the page I am moving _to_ causes the loader to appear it will never go away. I really don't think this is particular to the back button but rather to how the loading states in my app interact with it. In my app, I can verify that the loader is correctly rendered with isOpen set to false though.

**Expected behavior:**
The loader goes away.

**Steps to reproduce:**
As noted above, this is tricky, but I do know what the problem is, so see below.

**Related code:**
What's happening is that in `createControllerComponent`, the `componentWillUnmount` function is called because the component is being unmounted between the call to create the overlay and its instantiation. After it is instantiated, the code does not check to see if the component has been unmounted before displaying the overlay it created.

**Other information:**
I will follow up shortly with a PR to address this issue.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.3

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.12.0 (/usr/local/Cellar/node/12.12.0/bin/node)
   npm    : 6.11.3
   OS     : macOS Catalina
```

**Comment by elylucas** [comment]
fix released in 4.11.4
