### ISSUE TITLE
bug: @ionic/react@4.11.4 changes behaviour of useIonViewDidEnter

### ISSUE THREAD

**Issue by burkmarr** [ionic-team/ionic#19873]
# Bug Report

**Ionic version:**

@ionic/react 4.11.4

**Current behavior:**
1. ```IonPage``` contains a component imported from another file - Component.
2. A ```useState``` setter is passed as a property to Component.
3. Component uses this setter to set the related property on the parent page.
4. If the parent page now accesses the value of the set property from within a function bound to ```useIonViewDidEnter```, the property is not set.

**Expected behavior:**
The parent page should be able to access the state set within Component. This behaved as expected in @ionic/react 4.11.3.

**Steps to reproduce:**
This sample code demonstrates the feature *working correctly* because it is implemented with @ionic/react 4.11.3: https://stackblitz.com/edit/react-c5ru7j.

The sample code implements a component with a Leaflet map (react-leaflet) on a tabbed page. This is pertinent because Leaflet maps can render incorrectly in a React environment, e.g. if not completely visible when rendering. The supported way around this is to invoke the ```invalidateSize``` method on the map element, which can be accessed from React, once your page is visible - hence the need to access the map element from the function bound to ```useIonViewDidEnter```.

See the effect of *not* calling ```invalidateSize``` by commenting out line 10 in page1.js.

To see the effect of trying to run this with @ionic/react 4.11.4 you would need to copy the code elsewhere since, at the time of writing this, version 4.11.4 wasn't available in StackBlitz.

A workaround is to bind the Leaflect map element to a global (window) variable instead of using the react useState setter, but this is not ideal.

**Related code:**
As referenced above: https://stackblitz.com/edit/react-c5ru7j

**Ionic info:**
```
Ionic:

   Ionic CLI : 5.4.5

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3
   npm    : 6.4.1
   OS     : Windows Server 2016
```

**Comment by elylucas** [comment]
Hi @burkmarr,

Thanks for reporting the issue. I think I got a fix in a dev build if you would like to try it and let me know how it goes. 

There is one change that you will need to make in how the lifecycle hooks work in this case. You will need to pass in a list of dependencies the hook relies on (kinda like how useEffect or useCallback works.) . In your case, this would look like:

```
  useIonViewDidEnter(function() {
    leafletElement && leafletElement.invalidateSize()
  }, [leafletElement])
```
Note the second parameter, which is an array of variables the hook needs to run

To install the dev build, run:

npm i @ionic/react@4.11.5-dev.201911082323.5ff786a @ionic/react-react@4.11.5-dev.201911082323.5ff786a

Let me know how it goes or if you have any questions.

Thanks

**Comment by burkmarr** [comment]
Thanks @elylucas - it does indeed fix it; I really appreciate your quick response. Are you able to give a ballpark estimate on when 4.11.5 might be released, e.g. is it likely to be measured in months, weeks or days?
