### ISSUE TITLE
bug: React NavContext always goes back to default href

### ISSUE THREAD

**Issue by aub** [ionic-team/ionic#19871]
# Bug Report

**Ionic version:**

[x] **4.11.4**

**Current behavior:**
If you use an IonBackButton, it won't display unless you give it a default href. But if you try to go back, it will always go to the default.

**Expected behavior:**
Clicking the back button takes you back to the last URL in the history.

**Steps to reproduce:**
Add an IonBackButton to the page, give it a default href, navigate around the page, click on the back button. Note that it goes to the default href.

**Related code:**

The click handler for `IonBackButton` is [here](https://github.com/ionic-team/ionic/blob/master/packages/react/src/components/navigation/IonBackButton.tsx#L19). It gets the navigation context and uses it by calling `goBack', passing the default href. The NavContext's `goBack` function is implemented [here](https://github.com/ionic-team/ionic/blob/9568f228b259c44414c39957df03bd5554c11e0d/packages/react/src/contexts/NavContext.ts#L19). Note that if a default href is passed, it always goes there rather than checking to see if history is available and going to the last thing on the stack.

In the Angular version, implemented [here](https://github.com/ionic-team/ionic/blob/master/angular/src/directives/navigation/ion-back-button.ts#L25), the check is reversed and it goes back in the history if there is any history in the stack.

```
insert short code snippets here
```

**Other information:**
I'll start working on a PR for this, but I'm a little confused about how to make the same check that the Angular code makes to see if there is any available history. I also haven't looked into it yet, so maybe it's easy but if there is a quick answer then a comment in here would help push me in the right direction.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.4

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.12.0 (/usr/local/Cellar/node/12.12.0/bin/node)
   npm    : 6.11.3
   OS     : macOS Catalina
```

**Comment by elylucas** [comment]
@aub are you using an IonReactRouter? The NavContext is overwritten in IonReactRouter and does much more in-depth looking about where it should go back, taking into consideration the page that created it, the history, and falling back to defaultHref if it can't determine.

**Comment by aub** [comment]
@elylucas Blargh, ok now it seems to be working fine.... maybe something changed there between 4.11.3 and 4.11.4? Still, it seems like the default handler ought to be changed so it goes back if there is any history right?

**Comment by elylucas** [comment]
There was quite a bit a work around this between .3 and .4, so something might of happened.

I think the problem with blindly using the history API to go back is you don't know where that will take you. If you land on a page from another website, hitting the IonBackButton could take you back to that previous site, which would not be the desired outcome.

**Comment by aub** [comment]
Gotcha, ok. I'll close this then, apologies for the distraction.
