### ISSUE TITLE
bug: toast opacity set to 0.01 when animated flag set to false in safari and ios native

### ISSUE THREAD

**Issue by adechant** [ionic-team/ionic#19879]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
on an ios device or in safari
toast opacity is set to 0.01 when animated flag is false and mode is "md"
toast is not displayed at all when animated flag is false and mode is "ios"
(note: works fine in chrome with "md" or "ios" mode)

**Expected behavior:**
toast should be visible when presented, even if not animated.

**Steps to reproduce:**
in safari or on ios device, create a new toast, set animated to false, toast is barely visible with opacity at 0.01 when run in safari with mode ="md", not displayed at all when mode="ios"

**Ionic info:**
Ionic:

   Ionic CLI                     : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 8 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-sim : 8.0.2
   NodeJS  : v12.13.0 (/usr/local/bin/node)
   npm     : 6.12.0
   OS      : macOS Catalina
   Xcode   : Xcode 11.1 Build version 11A1027

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try this on the latest version of Ionic (v4.11.4)?

**Comment by adechant** [comment]
Seems to be fixed in this version.

Thanks!

On Mon, Nov 11, 2019 at 9:01 AM Liam DeBeasi <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for the issue. Can you try this on the latest version of Ionic (v4.11.4)?
