### ISSUE TITLE
bug (picker | browser): Bunch of picker is getting created

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic#19882]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Press Enter(key) again and again picker will open and override existing picker with that it is creating bunch of picker. 
<img src="https://media.giphy.com/media/ZedYKczar9TClf34Vq/giphy.gif" width="100%" height="350" />

**Expected behavior:**

It should not trigger by Enter(key).

**Steps to reproduce:**
1. Press enter again and again after opening the picker.

**Related code:**
Html:
https://github.com/indraraj26/ionic4-starter-tabs-sidemenu/blob/picker/src/app/home/home.page.html
TS:
https://github.com/indraraj26/ionic4-starter-tabs-sidemenu/blob/picker/src/app/home/home.page.ts

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
D:\ionicv4-github\ionic4-tabs-sidemenu>ionic info

Ionic:

   Ionic CLI                     : 5.4.4 (C:\Users\indra26\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 6 other plugins)

Utility:

   cordova-res : 0.8.0
   native-run  : 0.2.9

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10


D:\ionicv4-github\ionic4-tabs-sidemenu>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. The default behavior of browsers is to keep the focus on the button you last clicked. In order to work around this you will need to manually call the `blur` method on the focussed element.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20997, and a fix will be available in an upcoming release of Ionic Framework.
