### ISSUE TITLE
bug: [react]: IonRouterOutlet fails to render page when a route contains a regex in a match and render() method

### ISSUE THREAD

**Issue by marcoromag** [ionic-team/ionic#19891]
Issue 1:

 In the following condition:  
- the route contains a match with a regex URL ex: `match="/articles/:articleId(.*)"`
- the router uses a render() method
- the render method may return different pages based on the match attribute
- a ion-button / ion-item routerLink changes URL and the new URL hits the same <Route>

the new page is rendered *but it is invisible* (ion-page has class _ion-page-invisible_)

Issue 2:
The render callback method of the <Route> might be invoked with an undefined object - this shall never happen by typescript specs. Therefore, every time, in the Render method I need to add something like: 
```javascript
<Route ... render={(props) => {
  if (!props) return <></>;
  ...
}}/>
```

In the example below, I have three pages that can be rendered by the same route. The first page is displayed, then as I click on the link to go to the second page, the browser shows an empty page because ion-page has the _ion-page_invisible_ class

```javascript
const createPage = (title: string, next: string) : React.FC => () => (
  <IonPage>
    <IonHeader>
      <IonToolbar>
          <IonButtons slot="start">
             <IonBackButton/>
          </IonButtons>
          {title}
      </IonToolbar>
    </IonHeader>
    <IonContent>
      <IonButton routerLink={`/article/${next}`}>Go to page <strong>{next}</strong></IonButton>
    </IonContent>
  </IonPage>
)

const allPages :{[k:string]: React.FC}= {
  'one' : createPage('Page one', 'two'),
  'two' : createPage('Page Two', 'three'),
  'three': createPage('Page Three', 'one')
}

const App: React.FC = () => (
  <IonApp>
    <IonReactRouter>
        <IonRouterOutlet>
          <Route path="/article/:articleId(.*)" render={(props) => {
            if (!props) return <></>;
            const currPage = props.match.params.articleId as string
            const MyPage = allPages[currPage]
            return <MyPage key={currPage}/>
          }}/>
          <Route exact path="/" render={() => <Redirect to="/article/one" />} />
        </IonRouterOutlet>
    </IonReactRouter>
  </IonApp>
);
```

**Comment by marcoromag** [comment]
@elylucas, I really appreciate the efforts you guys are making in this great framework! :)
However, this issue is like the most critical thing if someone (like me) is designing a CMS application that shows articles, because I cannot route between the articles. 
I am trying to dig into the ViewStacks / Router / NavManager hierarchy to try to solve the issue but I must admit I'm a bit lost into it. 
I believe the issue is that when the matched route is the same (as it happens with regex matches) the Router does not detect the page change, even if the route did change.

However this is for me right now a showstopper, and I just wanted to understand if you believe this issue could be solved somehow soon... 

Thanks really for all you guys are doing!

**Comment by marcoromag** [comment]
@elylucas : I think I found a way to fix the issue, however I don't really know how to setup a working development environment for Ionic. 
I tried to fork and then use the @ionic/react-router package locally but I always get a 'Uncaught Error: Invariant failed: You should not use <Route> outside a <Router>' when I use the locally-compiled version of Ionic. I'm using the branch 4.11.x.

As I suspected, the reason why the routing does not work is because the same ViewItem is matched always when the route matches, also if the url is different. This happens when we have a regexp in the match. Therefore /article/one and /article/two would hit the same ViewItem.

in the RouterManager.setActiveView, this is a problem: first of all because enteringView and leavingView are the same object, therefore it will set prevId = id in the same view (creating an endless loop), and then because there will be nothing to animate because the ViewItem is the same when it gets down to the commit.

I think that we could fix the issue by adding the location url in the equation: if a ViewItem is matched, but the ViewItem location is different

The idea is to change the setActiveView() method, to that if the ViewItem returned has a different location, the ViewItem is 'cloned' and added back into the ViewStack's items.
To do this, I first added a `location?: string` into the ViewItem

Then, I changed the ViewStacks matchView so that it will still set the view and the match correctly, but it will not stop until it finds a view with the same location as the current view. If the view with the same location is not found, it will return the last matched view. (i.e.: the view whose match is matching the location: we'll use this view later on as a 'template')

```
    function matchView(v: ViewItem) {
      const matchProps = {
        exact: v.routeData.childProps.exact,
        path: v.routeData.childProps.path || v.routeData.childProps.from,
        component: v.routeData.childProps.component
      };
      const myMatch : IonRouteData['match'] | null | undefined = matchPath(location.pathname, matchProps);
      if (myMatch) {
        view = v;
        match = myMatch;
        return view.location === location.pathname;
      }
      return false;
    }
```

In the setActiveView() method of the RouteManager, I check if the view that has been returned has the same location (url) as the requested route, If not, the view is cloned, pushed back in the viewStack and the new view is used.
The location is always set into the 

```
setActiveView(location: HistoryLocation, action: HistoryAction) {
...
 viewStackKeys.forEach(key => {
      const { view: _enteringView, viewStack: enteringViewStack, match } = viewStacks.findViewInfoByLocation(location, key);
      if (!_enteringView || !enteringViewStack) {
        return;
      }

      const enteringView = (_enteringView.location && _enteringView.location === location.pathname) ? _enteringView
        : {
          ..._enteringView,
          id: generateId(),
          key: generateId(),
          mount: true,
          show: true,
          isIonRoute: false
        }

      if (_enteringView !== enteringView) {
        enteringViewStack.views.push(enteringView);
      }
      enteringView.location = location.pathname
     ...
```

Unfortunately I'm really not able to do any test because if I do a 
`npm install ../ionic/packages/react-router`
in my app, I get the above error (even without my changes :( )

**Comment by elylucas** [comment]
Hi @marcoromag,

Just quickly looking at this, you should be able to test your changes fairly easy

1) Go into folder (packages/react or packages/react-router)
2) run `npm run build`
3) run `npm pack`
4) Go into a ionic/react project and install the tgz files made from pack locally `npm i ../../../ionic/packages/react/ionic-react-4.11.4.tgz` (the directory path will change based on your setup)
and run

I'll dive into this issue deeper soon, but wanted to pass along the above info.

**Comment by marcoromag** [comment]
thanks, it works :)

My approach seem to work: now I have a new page every time. However the back does not work, I'm investigating...
if you want, I'll make a commit on my fork and you could have a look from there once I'm done. But it seems really promising

**Comment by marcoromag** [comment]
Thanks, with your support I was able to compile, and... my fix solves the issue :)
I've submitted a pull request: https://github.com/ionic-team/ionic/pull/19899

**Comment by elylucas** [comment]
Hi @marcoromag, 

Thanks for your assistance in reporting and helping to fix the issue. I needed to go a different route to solve a few other issues as well, but this should work as expected now in 4.11.6. Give it a try and let me know.
