### ISSUE TITLE
bug: IonRouterOutlet/ Arrow function in Route render prop losses doesn't get rebinded to correct scope on rerender

### ISSUE THREAD

**Issue by OfriHarlev** [ionic-team/ionic#19901]
When Using IonRouterOutlet in Ionic React any <Route/> children with a render prop fail to have access to the correct scope and are stuck with the scope they binded to during initial render. If you remove IonRouterOutlet the children <Route/>'s work as expected. 

Here is a demo of the issue: https://codesandbox.io/s/reactfire-auth-protection-5-tsxvf?fontsize=14 
You can see the difference in behavior in the `user` variable by commenting `IonRouterOutlet` in and out and seeing the difference in what is printed to the console

**Comment by elylucas** [comment]
Hi @OfriHarlev, 

Yes, this is an unfortunate side effect from the way we are caching the routes at the moment. 

As a workaround, I would suggest getting the data directly in the component rendered by the route. Using a state manager like Redux or a shared Context would work well there.

**Comment by elylucas** [comment]
@OfriHarlev Also, we are going to look into this, I just wanted to give a suggestion for the meantime.

**Comment by elylucas** [comment]
fixed in #20034 and will be in the 4.11.6 update soon
