### ISSUE TITLE
bug: @ionic/react 4.11.4 changes behavour of IonTabBar and back button

### ISSUE THREAD

**Issue by marcoromag** [ionic-team/ionic#19900]
Between 4.11.3 and 4.11.4, something has broken with tabs and back button:
in 4.11.3, clicking a tab bar button would not enable the back button after the route change (correct behaviour)
in 4.11.4, clicking on the tab bar buttons enables the back button, and clicking back will also navigate back to the previous tab (incorrect behaviour)

**Comment by elylucas** [comment]
This should also be fixed in 4.11.6
