### ISSUE TITLE
feat: ion-refresher color attribute

### ISSUE THREAD

**Issue by ArrowsOff** [ionic-team/ionic#19903]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
Basically like any other component have an color option to match the ion-refresher with any ion-content background color.

**Describe Preferred Solution**
``` <ion-refresher (ionRefresh)="ptrRefresh($event)" color="secondary"> ```

**Additional Context**
Currently it will show white when pulling and while refreshing is active. This does not look very good on any different background color

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as you can already do this with `ion-refresher`. Since this component does not use the Shadow DOM, you can set the background directly:

```
ion-refresher {
  background: var(--ion-color-primary);
}
```

Additionally, we expose the CSS Variables for the built in theme colors if you would like to use them: https://ionicframework.com/docs/theming/colors.

**Comment by ArrowsOff** [comment]
@liamdebeasi thank you for that, that certainly does most of it. However it's not perfect that's why I opened the issue.

Right now when you use that method you will see a blink of white when scrolling. 

I noticed that when debugging and setting the `.ion-page` to `background: var(--ion-color-primary);` did solve the trick, but this is not possible within the scope of the component. I have fixed this right now by having this in my global styles for anyone that needs it:

```
app-news,
app-news ion-refresher {
  background: var(--ion-color-primary);
}
```

**Comment by liamdebeasi** [comment]
Have you also set the color on the background of `ion-content`?

**Comment by ArrowsOff** [comment]
No I have not currently

**Comment by liamdebeasi** [comment]
You should try setting the `--background` color variable on `ion-content`. I think that's why you may be seeing a flash of white.
