### ISSUE TITLE
bug: ion-select, 4.11.5, new features not working

### ISSUE THREAD

**Issue by marqroldan** [ionic-team/ionic#19919]
# Bug Report
#19893 introduced exposure of the shadow elements for the ion-select, but it doesn't seem to be working on the 4.11.5 release (I did an npm install, expecting for it to work) am I missing something?

**Ionic version:**

[x] **4.11.5**

**Current behavior:**

No changes to the html attributes for ion-select, shadow elements does not have the 'parts' attribute and new variables
![image](https://user-images.githubusercontent.com/11716376/68929132-aa483780-07c6-11ea-80aa-a4b739c30847.png)

**Expected behavior:**

Shadow elements should have the 'parts' attribute as well as the usage of new variables as in #19893

**Steps to reproduce:**

upgrade @ionic/angular to 4.11.5

**Other information:**

**Ionic info:**

```Ionic:

Ionic CLI : 5.2.7
Ionic Framework : @ionic/angular 4.11.5
@angular-devkit/build-angular : 0.801.3
@angular-devkit/schematics : 8.1.3
@angular/cli : 8.1.3
@ionic/angular-toolkit : 2.0.0

Cordova:

Cordova CLI : not installed
Cordova Platforms : android 8.0.0
Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 13 other plugins)

Utility:

cordova-res : 0.6.0
native-run : 0.2.8

System:

Android SDK Tools : 26.1.1
NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
npm : 6.9.0
OS : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This feature was not shipped as part of Ionic Framework 4.11.5. You can see the CHANGELOG for 4.11.5 here: https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md
