### ISSUE TITLE
feat: Support react-router MemoryRouter

### ISSUE THREAD

**Issue by schontz** [ionic-team/ionic#19910]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

I need to be able to change routes without changing the browser URL and history stack. Reason: when accessing the app in mobile Safari, swiping on the edges moves through history. Ionic apps with menus will register a lot of accidental backward navigations.

**Describe Preferred Solution**

Pass a prop to `IonReactRouter` to use memory, e.g.:
```jsx
<IonReactRouter memory>
  {/* ... */}
</IonReactRouter>
```

**Comment by schontz** [comment]
Nice. Super excited to have this.

**Comment by schontz** [comment]
For future readers: it is now available as `<IonReactMemoryRouter />`. 👍

**Comment by elylucas** [comment]
There will be a blog soon on some guidance around testing with react testing lib.
