### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by LalitKushwah** [ionic-team/ionic#19928]
# Bug Report

**Ionic version:**
[x] **4.x**

Hello All,
I am creating a ionic application in which I am trying to integrate the Azure AD B2C Login. I came across the related documentation in the official ionic website https://ionicframework.com/docs/enterprise/auth-connect/azure-ad-b2c
but the package used here @ionic-enterprise/auth-connect doesn't exists on the npm registry.
Can someone help me with this ?

**Comment by kensodemann** [comment]
Anything under the `@ionic-enterprise` scope is a commercial offering that is available to our customers under an Enterprise contract. We also have contracts available focused on just one of those solutions. If your company is interested in such a thing you can go to the following link and request a demo: https://ionicframework.com/auth-connect

If this is a personal app, you are going to want to use the community plugins to create your own solution.
