### ISSUE TITLE
bug: React component types created with createControllerComponent and createOverlayComponent don't support refs. 

### ISSUE THREAD

**Issue by aub** [ionic-team/ionic#19924]
# Bug Report

**Ionic version:**

[x] **4.11.4**

**Current behavior:**

For any of the component types created with `createControllerComponent` or `createOverlayComponent`, the typing is such that you cannot pass them a ref. As an example, the following code:

```
const alertRef = createRef<HTMLIonAlertElement>();
<IonAlert ref={alertRef} />
```

Produces an error like this when compiled by Typescript:

```TypeScript error in /Users/aubrey/code/grouplicate-app/src/components/IonSearchableSelect.tsx(72,17):
Type 'RefObject<HTMLIonAlertElement>' is not assignable to type 'string | ((instance: { overlay?: HTMLIonAlertElement | undefined; isUnmounted: boolean; componentDidMount(): Promise<void>; componentWillUnmount(): void; ... 8 more ...; refs: { ...; }; } | null) => void) | RefObject<...> | null | undefined'.
  Type 'RefObject<HTMLIonAlertElement>' is not assignable to type 'RefObject<{ overlay?: HTMLIonAlertElement | undefined; isUnmounted: boolean; componentDidMount(): Promise<void>; componentWillUnmount(): void; componentDidUpdate(prevProps: AlertOptions & ReactControllerProps): Promise<...>; ... 7 more ...; refs: { ...; }; }>'.
    Type 'HTMLIonAlertElement' is missing the following properties from type '{ overlay?: HTMLIonAlertElement | undefined; isUnmounted: boolean; componentDidMount(): Promise<void>; componentWillUnmount(): void; componentDidUpdate(prevProps: AlertOptions & ReactControllerProps): Promise<...>; ... 7 more ...; refs: { ...; }; }': isUnmounted, componentDidMount, componentWillUnmount, componentDidUpdate, and 6 more.  TS2322
```

**Expected behavior:**
These components should accept a ref.

**Steps to reproduce:**
See the code above.

**Related code:**
The `createComponent` function is used to make most of the React components, and it [returns the result of a call to `createForwardRef` based on the class it has defined](https://github.com/ionic-team/ionic/blob/master/packages/react/src/components/createComponent.tsx#L97).

The [createOverlayComponent](https://github.com/ionic-team/ionic/blob/master/packages/react/src/components/createOverlayComponent.tsx#L26) and [createControllerComponent](https://github.com/ionic-team/ionic/blob/master/packages/react/src/components/createControllerComponent.tsx#L24) functions return the component class directly. I am definitely not an expert, but it seems like they should be changed to work the way `createComponent` does w.r.t. the ref.

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.5

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.12.0 (/usr/local/Cellar/node/12.12.0/bin/node)
   npm    : 6.11.3
   OS     : macOS Catalina

```

**Comment by elylucas** [comment]
fixed in 4.11.6
