### ISSUE TITLE
bug: React IonTabs component doesn't support documented methods

### ISSUE THREAD

**Issue by Zanluca** [ionic-team/ionic#19935]
# Bug Report

**Ionic version:**

[x] **4.11.5**

**Current behavior:**
`getSelected is not a function`

**Expected behavior:**
Get the currently selected tab.

**Steps to reproduce:**
Create an app that tries to use the `getSelected` methods from `IonTab`

**Related code:**

```
const Tabs = () => {
  const tabRef = useRef(null)

  const handleChangeTabs = () => {
    console.log(tabRef.current.getSelected())
  }

  return (
    <IonTabs ref={tabRef} onIonTabsDidChange={() => handleChangeTabs()} >
	...
    </IonTabs>
  )
}
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.4 (C:\Users\gabri\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework : @ionic/react 4.11.5

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by Jaki117** [comment]
Any updates on this? I am having the same problem with getScrollElement Method on IonContent component.
