### ISSUE TITLE
bug: ios transition causes title to be hidden

### ISSUE THREAD

**Issue by C-racker** [ionic-team/ionic#19951]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

`-webkit-transition: all .2s ease-in-out;`This will cause `ion-title` to be hidden

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you describe the issue a bit more, including how to reproduce the issue? I applied the styles to `ion-title`, but am unable to reproduce the issue: https://codepen.io/liamdebeasi/pen/PooLwaY.
