### ISSUE TITLE
bug: Clicking the button in succession will perform multiple returns

### ISSUE THREAD

**Issue by C-racker** [ionic-team/ionic#19952]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Control `this.navctr.pop`  by button; To go back to the page, if you click too fast it will be executed multiple times
![bug201911201723 2019-11-20 17_32_36](https://user-images.githubusercontent.com/20217449/69226859-db0be080-0bbb-11ea-9bb3-ba8d8f390fdf.gif)

**Expected behavior:**

Execute`this.navCtrl.pop();` Should not be repeated for a short time

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this an issue with the latest version of Ionic Framework? If so, can you provide a repo with the code required to reproduce the issue?
