### ISSUE TITLE
support: How to use ion-modal-controller in Ionic React?

### ISSUE THREAD

**Issue by adonig** [ionic-team/ionic#19967]
# How to use ion-modal-controller in Ionic React?

I'm trying to rewrite some ionic v4 code to Ionic React. My old code is making use of ion-modal-controller. I found [some documentation](https://ionicframework.com/docs/api/modal-controller) that indicates the controller might be available. I couldn't find a way to import a modal controller and I didn't find a hint in Ionic React's source code. Is it possible or do I have to rethink the design and make use of the IonModal component only?

**Comment by elylucas** [comment]
Hi @adonig,

You should be able to do most everything you would want to do by passing props to the `IonModal` component. Most of the options you would pass into the controller method are available on the component. If you find something that you can't do let me know. Thanks
