### ISSUE TITLE
feat: Whether ionic4 can use ssr?

### ISSUE THREAD

**Issue by UTSOURCE** [ionic-team/ionic#19960]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

Whether ionic4 can use ssr

**Comment by liamdebeasi** [comment]
We are still working out some of the details with Ionic Angular SSR. We hope to have more to announce soon!

Blog post regarding SSR: https://ionicframework.com/blog/ionic-4-roadmap-new-features-release-schedule-goals-oh-my/
