### ISSUE TITLE
bug: Cannot disable splashscreen on browser

### ISSUE THREAD

**Issue by ilprima** [ionic-team/ionic#19962]
# Bug Report

**Ionic version:**

 Ionic CLI                     : 5.4.4
   Ionic Framework               : @ionic/angular 4.11.2
   @angular-devkit/build-angular : 0.803.2
   @angular-devkit/schematics    : 8.3.2
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

**Current behavior:**

I'm using my ionic code for both browser (as a normal website, not wpa) and mobile apps. On browser I would like to disable the splashscreen because it is a losing of time on browser and I dont like it on desktop.
I tried a lot of solutions but none works.

**Expected behavior:**

Not showing the splashscreen on browser.

**Steps to reproduce:**

**Related code:**

I tried adding this to the config.xml
`<preference name="SplashScreen" value="none" />
    <platform name="browser">
        <preference name="ShowSplashScreen" value="false" />
    </platform>`

They are totally ignored.

**Ionic info:**

```
 Ionic CLI                     : 5.4.4
   Ionic Framework               : @ionic/angular 4.11.2
   @angular-devkit/build-angular : 0.803.2
   @angular-devkit/schematics    : 8.3.2
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1
```

**Comment by asadullazadeh** [comment]
Do you try this code?

`<preference name="SplashScreenDelay" value="0"/>`
