### ISSUE TITLE
bug: Android hardware back button not closing the app after navigation. i dont want to use register back button on every page. is there any way to overcome this issue without forcing hardware back button programatically. please help

### ISSUE THREAD

**Issue by hmohit7** [ionic-team/ionic#19972]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by hmohit7** [comment]
@liamdebeasi please help in resolving this issue.

**Comment by liamdebeasi** [comment]
Hi there, 

Please fill out the issue template completely. This will help us triage your issue more effectively.
