### ISSUE TITLE
bug: ion-back-button triggers routerOutlet navigation when used in ion-nav

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [ionic-team/ionic#19974]
**Ionic version:**
[x] **4.x**

**Current behavior:**
ion-back-button, when clicked, triggers ion-nav pop (as expected) and, simultaneously, triggers router navigation one step back, to previous route.

![Nov-22-2019 18-28-14](https://user-images.githubusercontent.com/11352013/69447380-aed89700-0d56-11ea-8fc4-a4e5ab171df5.gif)

**Expected behavior:**
ion-back-button should only be concerned with current ion-nav it resides in (it should only trigger ion-nav pop). It shouldn't affect router.

**Steps to reproduce:**
Navigate from one route to another. On the target route, create component with ion-nav, set root and push another component to that ion-nav. Click ion-back-button on that newly pushed view.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.6 (/opt/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 7 other plugins)

Utility:

   cordova-res : 0.6.0 (update available: 0.8.1)
   native-run  : 0.2.8 (update available: 0.2.9)

System:

   Android SDK Tools : 26.1.1 (/Users/rattkin/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/opt/local/bin/node)
   npm               : 6.13.1
   OS                : macOS Catalina
   Xcode             : Xcode 11.2.1 Build version 11B500
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Having `ion-nav` nested in an `ion-router-outlet` is not a paradigm we recommend as it typically leads to a confusing user experience (as well as issues when interacting with the Angular Router as you've experienced). I am going to close this issue as this is not something we have plans to support at this time. Thank you!

**Comment by mhartington** [comment]
@sebastian-zarzycki-es Pull requests to update the docs are always welcomed if you are up for it 😄
