### ISSUE TITLE
bug: operation running outside ngZone on native and mobile web

### ISSUE THREAD

**Issue by javiermrz** [ionic-team/ionic#19993]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
I have a parent component with the following template:
```
 <app-graph-grouped-vertical
      [results]="graphRecords"
      [series]="graphPredictions"
      [seriesColors]="predictionColors"
      [xAxis]="xAxis"
></app-graph-grouped-vertical>
```

And, inside `GraphGroupedVerticalComponent`, I've got the following code:
```
export class GraphGroupedVerticalComponent extends GraphBaseComponent<GroupedResultDto>
  implements OnChanges, OnInit, OnDestroy, DoCheck {
...
 @Input() results!: GroupedResultDto[]

 ngOnChanges(changes: SimpleChanges){console.log('Triggered')}
...

}
```

In the parent component, I subscribe to a store and update the property `graphRecords` whenever a new value triggers the subscription. The problem is that when I'm in a computer browser, this works perfectly, and `NgZone.isInAngularZone()` will return `true`.

However, when I use the app in a mobile web browser, or compiled into a native app (physical phone or emulator) this code will run outside `ngZone` and I'm forced to use `ngZone.run()`.

This happens involuntarily and I haven't found anything in the Docs related to this issue, so in my opinion, it is a bug.

**Expected behavior:**
This operation should run inside `ngZone` without necessarily forcing it.

**Steps to reproduce:**
Unfortunately, I cannot give a complete example of this because it is a private project but, if needed, ask and I will try and give you all the possible information.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.4.6
   Ionic Framework               : @ionic/angular 4.11.4
   @angular-devkit/build-angular : 0.803.18
   @angular-devkit/schematics    : 8.3.18
   @angular/cli                  : 8.3.18
   @ionic/angular-toolkit        : 2.1.1

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (2 plugins total)

Utility:

   cordova-res : 0.8.1 
   native-run  : not installed

System:

   NodeJS : v10.16.0 (/Users/javier.marzan/.nvm/versions/node/v10.16.0/bin/node)
   npm    : 6.11.2
   OS     : macOS Mojave

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you able to provide a simplified reproduction without any of your project's confidential information?

**Comment by javiermrz** [comment]
Sorry for the late response. I was fiddling a bit, and I think it can be a problem with ngx-charts, as they use ngZone within their graph update methods, and this bug only occurs in screens where we are using their charts, so I think it's their problem. 

I will post a new issue if this happens in a screen without a graph, but I think it's okay for now. Thanks for answering to the issue anyway :)

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I will close this issue, but feel free to open a new issue later if you feel this is a bug in Ionic Framework. Thanks!
