### ISSUE TITLE
bug: Neither autofocus="true" nor setFocus using ViewChild on ion-input doesn't work on ios. M on ionic framework @ionic/angular 4.11.3 and Cordova CLI : 9.0.0 (cordova-lib@9.0.1)

### ISSUE THREAD

**Issue by memthoi-karam** [ionic-team/ionic#19998]
# Bug Report

**Ionic version:**
@ionic/angular 4.11.3

**Current behavior:**

After using autofocus="true" in ion-input tag, the input field wont be focused on page load. I have used  @ViewChild('searchInput') searchInput; by putting 'searchInput'  on the tag and call the setFocus() using timeOut on ngOnInit(), the input field won't still be focused and keyboard wont show up either. I had installed ionic native keyboard and included  <preference name="KeyboardDisplayRequiresUserAction" value="false" />

**Expected behavior:**

Input field should focused on page load and keyboard should be up. 

**Steps to reproduce:**

Step 1: Install keyboard plugin - 
ionic cordova plugin add cordova-plugin-ionic-keyboard
npm install @ionic-native/keyboard

Step 2:  Include this in config.xml file -     
<preference name="KeyboardDisplayRequiresUserAction" value="false" />

Step 3: HTML file - 
<ion-content [fullscreen]="true"
             scrollEvents="true">

  <ion-input type="text" #searchInput class="search-bar" style="caret-color: black;"></ion-input>
</ion-content>

**Related code:**

export class FreeSearchComponent implements OnInit {
  @ViewChild('searchInput') sInput;

 constructor(
               private keyboard: Keyboard
    ) {}

  ngOnInit() {
    setTimeout(() => {
      this.sInput.setFocus();
    }, 300);
}

}

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.3
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.0.1, (and 25 other plugins)

Utility:

   cordova-res : 0.7.0 (update available: 0.8.1)
   native-run  : 0.2.9 

System:

   ios-sim : 8.0.2
   NodeJS  : v10.16.3 (/usr/local/bin/node)
   npm     : 6.9.0
   OS      : macOS Mojave
   Xcode   : Xcode 11.0 Build version 11A420a
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am testing out both `autofocus="true"` and the `setFocus` method, and both seem to be working.

**Comment by memthoi-karam** [comment]
@liamdebeasi than you for checking it out. The problem doesn't exist in browser. It doesn't work in ios v12. I will set up a repo with the required code and will let you know. Thanks
