### ISSUE TITLE
ion-popover add --border-radius variable

### ISSUE THREAD

**Issue by rajiramamoorthi** [ionic-team/ionic#20000]
Could you add border radius variable for ion-popover?
--border-radius

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I am going to close this as this is already possible in Ionic Framework.

`ion-popover` is not a shadow component, so you can just style it directly. Here is an example of customizing the border radius for the popover: https://codepen.io/liamdebeasi/pen/VwwJWPo

**Comment by rajiramamoorthi** [comment]
Thank you
