### ISSUE TITLE
bug: IonBackButton icon missing on ios (React)

### ISSUE THREAD

**Issue by jordan-jarolim** [ionic-team/ionic#20005]
# Bug Report

**Ionic version:**

[x] **4.11.5**

**Current behavior:**
IonBackButton renders text without an icon. Even if the icon props is used to pass an icon component, the icon is not rendered. Also mentioned [here](https://github.com/ionic-team/ionic/issues/16315#issuecomment-480668357). ![IonHeader](https://i.imgur.com/0SKzRYe.png)

**Expected behavior:**
IonBackButton should render icon altogether with text.

**Steps to reproduce:**
Use `IonBackButton` as shown [here](https://ionicframework.com/docs/api/back-button)

```
	<IonPage>
		<IonContent>
			<IonHeader>
				<IonToolbar>
					<IonButtons slot="start">
						<IonBackButton defaultHref="/" />
					</IonButtons>
					<IonTitle>{title}</IonTitle>
				</IonToolbar>
			</IonHeader>
			{children}
		</IonContent>
	</IonPage>
```

**Other information:**

**Ionic info:**

```

Ionic:

   Ionic CLI       : 5.4.6
   Ionic Framework : @ionic/react 4.11.5

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.13.0 (/Users/jordan_jarolim/.asdf/installs/nodejs/12.13.0/bin/node)
   npm    : 6.12.0
   OS     : macOS Catalina
```

**Comment by elylucas** [comment]
Hi @jordan-jarolim,

I'm not seeing this bug currently (back button is appearing as it should for me). Would you be able to provide a repo that has the issue happening?

Thanks
