### ISSUE TITLE
feat: Add haptic feedback for ion-picker on iOS

### ISSUE THREAD

**Issue by rajiramamoorthi** [ionic-team/ionic#20003]
Please add ticker sound for picker like ios native picker.
Currently it is showing as a ion popover, Could provide option to integreate inside page like ion slider component.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you referring to the haptic feedback you whenever you select an item in the native iOS picker?

**Comment by rajiramamoorthi** [comment]
Yes you are correct.  I am looking haptic feedback sound only.

**Comment by rajiramamoorthi** [comment]
> Thanks for the issue. Are you referring to the haptic feedback you get whenever you select an item in the native iOS picker?

Yes you are correct. I am looking haptic feedback sound only.

**Comment by rajiramamoorthi** [comment]
> Thanks for the issue. Are you referring to the haptic feedback you get whenever you select an item in the native iOS picker?

Any update on this?

**Comment by byronaltice** [comment]
We also need haptic feedback for pickers. Any update?

**Comment by rajiramamoorthi** [comment]
Any update on this

**Comment by netsesame2** [comment]
It will haptic when scroll the column if you use capacitor mode.

**Comment by nikbabchenko** [comment]
> Currently, the only workaround is adding cordova-plugin-taptic-engine.
> 
> ```
> picker.onDidDismiss().then(() => {
>     this.tapTic.gestureSelectionEnd();
> });
> 
> picker.present().then(() => {
>     this.tapTic.gestureSelectionStart();
> });
> ```
> 
> BTW: Since ionic team encourage to use Capacitor instead of Cordova, and Haptics is a default plugin in Capacitor, this feature should be integrated when use Capacitor.

doesn't work with a capacitor for me. No haptic feedback.

**Comment by netsesame2** [comment]
@nikbabchenko 
Hi, what I said is a suggestion to ionic team, no capacitor support is avaluable now.

**Comment by nikbabchenko** [comment]
thank you, @netsesame2  :-)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21268, and a fix will be available in an upcoming release of Ionic Framework.
