### ISSUE TITLE
bug: App run crash on Android with Samsung

### ISSUE THREAD

**Issue by xuelabi123** [ionic-team/ionic#20001]
# Bug Report

**Ionic version:**

[x] **4.x**
**Current behavior:**
![WechatIMG15251](https://user-images.githubusercontent.com/16874935/69606740-9a4e1480-105e-11ea-9dd9-f0ef16ef2a22.jpeg)

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by cmaas** [comment]
This is a problem with Cordova and possibly some very specific Samsung devices. Is this a Samsung Galaxy A5? Please specify. It affected older Ionic versions as well and is not necessarily a bug in ionic/core.

See if this helps you: https://forum.ionicframework.com/t/application-error-the-connection-to-the-server-was-unsuccessful/67584/56
