### ISSUE TITLE
bug: Ionic deploy capacitor error in cordova project

### ISSUE THREAD

**Issue by FernetB** [ionic-team/ionic#20006]
# Bug Report

**Ionic version:**

[x] **4.7.4**

**Current behavior:**

When i make a new web build with ionic deploy i have the following error:

$ ionic deploy manifest
[12:35:00]: ▸ [ERROR] The webDir property must be set in the Capacitor configuration file (capacitor.config.json).
[12:35:00]: ▸ See the Capacitor docs for more information: https://capacitor.ionicframework.com/docs/basics/configuring-your-app

And at the beginning it says;
[12:33:44]: --- Step: detect_native_type ---
[12:33:44]: --------------------------------
[12:33:44]: Checking if cordova or capacitor project
[12:33:44]: Cordova project detected

**Expected behavior:**

Can make the web build without any problems
**Steps to reproduce:**

I do not know exactly the steps to reproduce beyond the described before, but i can add that i firstly used capacitor to build my project and then move to cordova.

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.3 (C:\Users\PC\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.1.2
   @angular/cli                  : 8.1.2
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : not installed
   @capacitor/core : not installed

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 7 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (C:\Users\PC\AppData\Local\Android\Sdk)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.12.0
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as it is more of a support question and not related to Ionic Framework. The error you are seeing tells you what you need to do to resolve it. In the `capacitor.config.json` file, you should have a `webDir` property with the correct build directory (typically `www`).

If you still feel this is a bug, please open a new issue on the Capacitor GitHub repo: https://github.com/ionic-team/capacitor/issues. Thanks!
