### ISSUE TITLE
remove frame around ion-input

### ISSUE THREAD

**Issue by Sunny41** [ionic-team/ionic#20015]
Ionic CLI                     : 5.4.5
   Ionic Framework               : @ionic/angular 4.11.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
The ion-input is showing a frame around the input field and I am not able to remove it. 
![image](https://user-images.githubusercontent.com/43843297/69797064-5f1f2300-11cf-11ea-8df1-000672523543.png)

**Expected behavior:**
the other inputs i am using do not show those frames

**Related code:**

```
<ion-item>
       <ion-input [(ngModel)]="eMail" type="email" placeholder="{{'Login.mail' | translate}}" class="input"></ion-input>
</ion-item>
```

Just that. there is no CSS in the page.css or in global.css

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am not seeing any frame around `ion-input` components: https://codepen.io/liamdebeasi/pen/oNgNZpv

**Comment by Sunny41** [comment]
it doesn't matter what is behind this html code, its just sometimes there and sometimes not. I even tried adding some CSS: 
```CSS
.input {
  background:none; 
  outline: none; 
  -webkit-appearance: none; 
  box-shadow: none !important; 
  border: none;
}

```

but that doens't work either

**Comment by liamdebeasi** [comment]
Thanks for the follow up. A code reproduction of the issue would be very helpful in this scenario. What browser/OS are you testing this on?

**Comment by Sunny41** [comment]
It's chrome, android and iOS, all of them show the same behaviour. 
All my other inputs are working. I will try to import the code to another page, maybe that helps

**Comment by Sunny41** [comment]
okay i might have found the error: 
when i started my project, there where issues with shadowDom. 
I added the ViewEncapsulation: ShadowDom and it seemed to be fine. 
Now I removed this line and removed the :host{} element around my css code and it seems to be working now.

**Comment by liamdebeasi** [comment]
Glad to hear everything is working now. I am going to close this issue. Thanks!
