### ISSUE TITLE
bug: animation not working on devices that require -webkit- prefix

### ISSUE THREAD

**Issue by DavidWiesner** [ionic-team/ionic#20017]
# Bug Report
On old devices the animation (page and overlay transition) did not work.

**Ionic version:**

[x] **4.x**

**Current behavior:**
When I run an app (e.g.: default ionic starter app) the page transition does not work on older devices (e.g.: android 5 with chrome 37). I discovered this devices will require an prefix to get the animation work. Even worst an popover will not be appear because its `popover-wrapper` has an initial opacity of zero. Without animation the popup will not appear.

**Expected behavior:**
Animations should also work on older devices.

**Steps to reproduce:**

1. `ionic start newApp blank`
2. `cd ./newApp`
3. `ionic serve --host=0.0.0.0 -- --disable-host-check`
4. open this page with your ip on an older device browser and navigate to a second page
5. no animation is triggered

**Related code:**

The `setStyleProperty`, `removeStyleProperty` and `createKeyframeStylesheet` should add an prefix (e.g.: `-webkit-`) for older devices if required. 

https://github.com/ionic-team/ionic/blob/d8161bc1297fe735b86cfe75ba135ef8aa8f09a5/core/src/utils/animation/animation-utils.ts#L2-L8

https://github.com/ionic-team/ionic/blob/d8161bc1297fe735b86cfe75ba135ef8aa8f09a5/core/src/utils/animation/animation-utils.ts#L80

**Other information:**
- Android 5.0 Chrome 37

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

System:

   NodeJS : v10.15.3 (/usr/local/Cellar/node@10/10.15.3/bin/node)
   npm    : 6.4.1
   OS     : macOS
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. You are correct, we need some prefixing for older browsers. I will look at your PR shortly.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20020 and will be available in an upcoming release of Ionic Framework.
