### ISSUE TITLE
bug: vertical scrolling ion-content prevents horizontal scroll of the parent element

### ISSUE THREAD

**Issue by haydenbr** [ionic-team/ionic#20010]
# Bug Report

**Ionic version:**
@ionic/angular: 4.10.0
@ionic/core: 4.10.0

**Current behavior:**
So this is admittedly an edge case ...

I have a parent element that is intended to scroll horizontally. On the page, I have a series of columns that scroll vertically (think Trello. Or see the attached GIF to get an idea of what I'm describing).

Previously, I was just using an *ngFor to place all the items in the scrolling columns, and everything worked fine. But then I updated the columns to use `ion-content` with `ion-virtual-scroll` for better performance.

After making this change, I was no longer able to scroll the page horizontally when my cursor was over top of one of the `ion-content`

**Expected behavior:**
I would expect to be able to scroll horizontally.

**Steps to reproduce:**

https://stackblitz.com/edit/ionic-virtual-scroll-overscroll-behavior?file=src%2Fapp%2Fapp.component.ts

To reproduce, when the page first loads, you'll see three ion-contents with virtual scrolls inside, all lined up horizontally. They will overflow the page, allowing a horizontal scroll. Place your cursor on top of one of the three ion-contents and attempt to scroll horizontally with your track pad. You'll notice that nothing happens. You have to move the cursor off of the ion-content to be able to scroll.

**Suggested fix:**

So it seems that the `overscroll-behavior: contain` in the vertically-scrolling is preventing the page as a whole from horizontally scrolling.

There's two fixes/updates I can think of:

One solution would be to provide css variables to update the value of `overscroll-behavior`, and possibly split out the one property into `overscroll-behavior-x` and `overscroll-behavior-y`. I don't know if that would make it too easy for developers to shoot ourselves in the foot though and muck with implementation details of `ion-content`.

The other solution I think would be to make the following change in `content.scss`:

change this:

```
.scroll-y,
.scroll-x {
  -webkit-overflow-scrolling: touch;
  will-change: scroll-position;
  overscroll-behavior: contain;
}

.scroll-y {
  touch-action: pan-y;
  overflow-y: var(--overflow);
}

.scroll-x {
  touch-action: pan-x;
  overflow-x: var(--overflow);
}
```

to this:

```
.scroll-y,
.scroll-x {
  -webkit-overflow-scrolling: touch;
  will-change: scroll-position;
}

.scroll-y {
  touch-action: pan-y;
  overflow-y: var(--overflow);
  overscroll-behavior-y: contain;
}

.scroll-x {
  touch-action: pan-x;
  overflow-x: var(--overflow);
  overscroll-behavior-x: contain;
}
```

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 5.4.1 (/Users/haydenbraxton/.config/yarn/global/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.10.0
   @angular-devkit/build-angular : 0.803.0
   @angular/cli                  : 8.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (/Users/haydenbraxton/.nvm/versions/node/v10.16.3/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20011 and will be available in an upcoming release of Ionic Framework.
