### ISSUE TITLE
While using Ionic Local Notification we can't achieve certain Features (If we add count in trigger parameters we are not get daily based schedules, and while we schedule previous reminder and that time we dont having) background App app will not respond our schedules and Sounds not working properly in assert foldeer.

### ISSUE THREAD

**Issue by Prasand-altius** [ionic-team/ionic#20022]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. We do not manage the Local Notifications plugin, so we recommend you ask your question on our [forums](http://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com/). Additionally, if you feel this is a bug you can file an issue with the plugin's author.
