### ISSUE TITLE
While using Ionic Local Notification we can't achieve certain Features:

### ISSUE THREAD

**Issue by Prasand-altius** [ionic-team/ionic#20021]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Closing as a duplicate of https://github.com/ionic-team/ionic/issues/20022.
