### ISSUE TITLE
bug: Getting weird error in Sentry logger that is occurring inside ionic core

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic#20024]
# Bug Report
e.animate is not a function
https://sentry.io/share/issue/7346a4e474af434c86cfac2b977e8ebc/

**Ionic version:**

[x] **4.x**
```
"@ionic/core": "4.11.5",
"@ionic/vue": "0.0.9",

And

		"@capacitor/android": "1.3.0",
		"@capacitor/cli": "1.3.0",
		"@capacitor/core": "1.3.0",
		"@capacitor/ios": "1.3.0",
```

**Current behavior:**
I am not able to reproduce it but i am getting these errors logged in sentry.

![image](https://user-images.githubusercontent.com/8480351/69912463-c77c3780-144f-11ea-9451-2572e8f53855.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?
