### ISSUE TITLE
bug: Toast 'showCloseButton' property no longer exists in 5.0.0-beta1

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic#20027]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

ToastOptions interface no longer has the "showCloseButton" property but this change is not listed in "breaking changes" in CHANGELOG.

**Expected behavior:**

Change should be listed in CHANGELOG / alternate behavior should be provided, or property should be restored.

**Steps to reproduce:**

Update to Ionic 5 beta 1

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Sorry for the confusion. The `showCloseButton` property was removed in beta 0, so it's listed in the changes for `5.0.0-beta.0`, not `5.0.0-beta.1`: https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#500-beta0-2019-10-15

**Comment by lincolnthree** [comment]
Ah! Got it. That makes more sense. Sorry for the noise.
