### ISSUE TITLE
bug: All about double tap zoom #IONIC 4.11.5

### ISSUE THREAD

**Issue by 08Thug** [ionic-team/ionic#20023]
# Bug Report

**Ionic version:**
Ionic:

   Ionic CLI                     : 5.4.6 (/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 5.0.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 3.1.2, (and 30 other plugins)

**Current behavior:**
Before updating to 4.11.5 Double tap zoom was working fine in Modal controller,after upgrading double tap zoom is not working

**Expected behavior:**
Expecting to perform Double tap Zoom

**Related code:**
followed this tutorial previously!
https://www.youtube.com/watch?v=yHDnVarTr2E

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by 08Thug** [comment]
```
 oenGallery(index, main_index) {
    this.modalController
      .create({
        component: GallerySliderModalComponent,
        cssClass: "app-gallery-slider-modal",
        componentProps: {
          imagesList: this.detailObj.gallery[main_index],
          index: index,
          imagePath: this.webServiceUrl.imagePathPropertyOriginal
        }       
      })
      .then(a => {
        a.present().then(() => {
          console.log("presented");
          a.onDidDismiss().then(data => {
            //  }
          });
        });
      });
      console.log("The Live Value Of The Image"+this.imagePath);
  }
```
And this is the modal controller

```
{
    this.imagesList = navParams.get("imagesList");
    console.log('this.imagesList length: ', this.imagesList.length);
    this.index = navParams.get("index");
    this.type = navParams.get("type");
    this.displayName = navParams.get("displayName");
    this.is_customized = navParams.get("is_customized");
    console.log(" this.index: ", this.index);
   // console.log("type", this.type);
    console.log("displayName", this.displayName);

    this.imagePath = navParams.get("imagePath");
    console.log('this.imagePath: ', this.imagePath);

    if (this.type === undefined || this.type === "undefined") {
      console.log(
        "this.imagePath: ",
        this.imagePath + this.imagesList[0].image_name
      );

      setTimeout(() => {
        if (this.imagesList.length === 1) {
          console.log("swipe locked");
          this.lockSwipe();
        } else {
          console.log("Swipe not Locked")
          this.goToSlide();
        }
      }, 500);
    }
    //because event_registration && && "event_redeemption" always contain single image
    else {
      console.log("this.imagePath: ", this.imagePath + this.imagesList);
      setTimeout(() => {
        this.lockSwipe();
      }, 500);
    }
  }
```

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Please provide the full app reproduction -- I am typically not able to reproduce the issue using a code snippet. An easy way to do this is to create a blank Ionic starter app and then copy over the required code.

**Comment by 08Thug** [comment]
Thanks for your time,i've already provided the URL link up I've followed the same but now i can't get the double tap zoom if you got time go thru the link

**Comment by liamdebeasi** [comment]
Is there a finished project .zip I can download?

**Comment by 08Thug** [comment]
Sorry i can't do that! I will do the thing you asked me previously will create a blank project and i will send the zip to you....asap!

**Comment by 08Thug** [comment]
thank you for your assistance i've done with my error after adding zoom in sliderOpts every thing is working fine!
