### ISSUE TITLE
bug: ion-img ionError not fired on 404 error

### ISSUE THREAD

**Issue by rastafan** [ionic-team/ionic#20039]
# Bug Report

**Ionic version:**
@ionic/angular 4.11.5

**Current behavior:**
Ion-img events do not seem to work at all. Binding to ionError, ionImgWIllLoad and ionImgDidLoad does not seem to work, as bound methods are not fired.

**Expected behavior:**
The events should fire as per [https://ionicframework.com/docs/api/img](this doc page).

**Related code:**

Full Stackblitz example:
https://stackblitz.com/edit/ionic-pj8ehj

home.html (Non-Existing image):
```
<ion-img style="width:100px; height:100px; border: 1px solid red;" [src]="nonexisting" (ionImgWillLoad)="willLoad($event)" (ionImgDidLoad)="loadSuccess($event)" (ionError)="loadError($event)"></ion-img>
```

home.html(Existing Image):
```
<ion-img style="width:100px; height:100px; border: 1px solid red;" [src]="existing" (ionImgWillLoad)="willLoad($event)" (ionImgDidLoad)="loadSuccess($event)" (ionError)="loadError($event)"></ion-img>
```

home.ts
```
willLoad(event){
   console.log("WILL LOAD");
}

loadError(event){
   console.log("ERRORE");
   console.log(event);
}

loadSuccess(event){
   console.log("SUCCESS");
}
```

**Other information:**
Seems like ionError was introduced with #15659 . Has anyone seen this working? Am i missing something?

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.9 (C:\Users\Matteo\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (2 plugins total)

Utility:

   cordova-res : not installed
   native-run  : 0.2.7

System:

   Android SDK Tools : 26.1.1 (C:\android_sdk)
   NodeJS            : v12.13.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.12.1
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. The StackBlitz you provided is running Ionic 3. Did you mean to create an Ionic 4 StackBlitz instead? The `ionError` event was introduced in Ionic 4.

**Comment by rastafan** [comment]
Yes, i'm sorry for the dumb mistake. Here is a ionic v4 stackblitz:

https://stackblitz.com/edit/ionic-4-template-eumbax

As you will see in Console, the **ionImgDidLoad** is correctly fired (unlike what i wrote in the original post), but neither **ionError** nor **ionImgWillLoad** is fired.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. The StackBlitz you sent over is using `@ionic/angular@4.0.0-beta.5`. Can you try this again using the latest stable version of Ionic Framework? `ionError` was added in 4.2.0, and `ionImgWillLoad` was added in 4.4.0.

**Comment by rastafan** [comment]
I'm quite embarassed.
I updated stackblitz to 4.11.5, and events are actually fired. 
I did a npm install on my project and everything seems to work fine now.
Closing, thanks for the kind replies and sorry for wasting your time.
