### ISSUE TITLE
bug (latest beta versions): datetime only sets current datetime - not selected value

### ISSUE THREAD

**Issue by corysmc** [ionic-team/ionic#20036]
# Bug Report

**Ionic version:**
[x] **`5.0.0-beta.1 (and beyond)`** 
tested on `5.0.0-beta.0` and it works
tested on `5.0.0-beta.1` and it doesn't
also tested on `5.0.0-dev.201912032102.fd4cfe7`

**Current behavior:**
1. Open datepicker
2. Select Time
3. notice the time updates to the current time.
4. The ionChange event is fired but it looks like the value is tied to the current time (not the time picked).

**Expected behavior:**
1. Open datepicker
2. Select Time
3. ionChange event is emitted with selected time
4. Time updates to time chosen in picker

**Steps to reproduce:**
Working 5.0.0-beta.0 https://codepen.io/corysmc/pen/zYxxzBK
Not Working 5.0.0-beta.1 https://codepen.io/corysmc/pen/ExaaXEX (renders current time only)
Not Working 5.0.0-dev.201912032102.fd4cfe7 https://codepen.io/corysmc/pen/LYEELmQ

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue for you?

`npm i @ionic/angular@5.0.0-dev.201912051453.e49df93`

**Comment by liamdebeasi** [comment]
We've merged a fix in for this. If you're still experiencing issues let me know, and I'll investigate further. Thanks!

**Comment by corysmc** [comment]
Yep that did the trick - FYI it's the latest core build - not angular that I needed:
`npm i @ionic/core@5.0.0-dev.201912051453.e49df93`

Updated codepen working: https://codepen.io/corysmc/pen/LYEELmQ

Thanks @liamdebeasi and @brandyscarney!
