### ISSUE TITLE
bug: Animation transitions aren't always respecting 'navAnimation' property

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [ionic-team/ionic#20046]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Sometimes (unfortunately, not consistent), the transition animation (from route to route) rendered on mobile device does not follow the animation specified in `navAnimation` of `IonicModule.forRoot` config. This is especially visible if you set mode to 'md' and then navAnimation to base ios animation.

**Expected behavior:**
The router/nav transition animation to always use the animation specified in `navAnimation` passed in `IonicModule.forRoot` config.

**Steps to reproduce:**
Sadly, so far I haven't been able to pinpoint a solid path to reproduce. I do realize this is very vague as a bug report, but I still hoped it would be good to provide some kind of reference. All I know is that it never happens in a browser (`ionic serve`). It sometimes happen on mobile, but it's not deterministic. I think it might be related to direction `root` of animation (happens more often for these cases), but I'm not sure.

**Related code:**
```
this.navController.setDirection('root', true, 'forward');
this.router.navigate([ urlToNavigateTo ])
      .catch((error) => {});
```

Router config I'm using:

```
{
  enableTracing: false,
  preloadingStrategy: PreloadAllModules,
  initialNavigation: 'disabled'
}
```
IonicConfig
```
import { iosTransitionAnimation } from '@ionic/core/dist/collection/utils/transition/ios.transition.js';

 {
  mode: 'md',         
  navAnimation: iosTransitionAnimation
};
```

**Other information:**
Nothing comes to mind

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.9
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 8 other plugins)

Utility:

   cordova-res : 0.8.1 
   native-run  : 0.2.9 (update available: 0.3.0)

System:

   Android SDK Tools : 26.1.1 (/Users/rattkin/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/opt/local/bin/node)
   npm               : 6.13.1
   OS                : macOS Catalina
   Xcode             : Xcode 11.2.1 Build version 11B500
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you able to provide a repo with the code required to reproduce this issue? (Even if the issue only happens some of the time)

**Comment by sebastian-zarzycki-es** [comment]
I can try (tomorrow).
