### ISSUE TITLE
feat: Could you provide all required CSS variables for all the ionic shadow components?

### ISSUE THREAD

**Issue by rajiramamoorthi** [ionic-team/ionic#20044]
Please provide all the CSS variables for all ionic shadow components.  

**Example:**

--backdrop-opacity
--background
--background-activated
--background-checked
--background-focused
--background-hover
--background-selected
--bar-background
--bar-background-active
--bar-border-radius
--bar-height
--border-color
--border-color-checked
--border-radius
--border-style
--border-width
--box-shadow
--checkmark-color
--color
--color-activated
--color-focused
--color-hover
--detail-icon-color
--detail-icon-font-size
--detail-icon-opacity
--height
--highlight-color-focused
--highlight-color-invalid
--highlight-color-valid
--highlight-height
--icon-font-size
--icon-font-weight
--icon-margin-bottom
--icon-margin-end
--icon-margin-start
--icon-margin-top
--icon-padding-bottom
--icon-padding-end
--icon-padding-start
--icon-padding-top
--inner-border-width
--inner-box-shadow
--inner-padding-bottom
--inner-padding-end
--inner-padding-start
--inner-padding-top
--ion-grid-padding
--ion-grid-padding-lg
--ion-grid-padding-md
--ion-grid-padding-sm
--ion-grid-padding-xl
--ion-grid-padding-xs
--ion-grid-width
--ion-grid-width-lg
--ion-grid-width-md
--ion-grid-width-sm
--ion-grid-width-xl
--ion-grid-width-xs
--keyboard-offset
--knob-background
--knob-border-radius
--knob-box-shadow
--knob-size
--margin-bottom
--margin-end
--margin-start
--margin-top
--max-height
--max-width
--min-height
--min-width
--offset-bottom
--offset-top
--opacity
--padding-bottom
--padding-end
--padding-start
--padding-top
--pin-background
--pin-color
--placeholder-color
--placeholder-font-style
--placeholder-font-weight
--placeholder-opacity
--ripple-color
--size
--transition
--width

and etc.....

Please add extra variables.

**Comment by troyanskiy** [comment]
That shadow components are pain in the ass if you want to customise css. And most of the time I need to customise them...

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is your request that all CSS variables listed there be added to each component?

**Comment by rajiramamoorthi** [comment]
> Thanks for the issue. Is your request that all CSS variables listed there be added to each component?

Add maximum CSS variables for all the ionic shadow components.The above list are example variables. Please add more variables.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I do not think adding a CSS variable for every CSS property to every Shadow DOM component is the right solution here.

Are there certain components you want to be able to style in a certain way? Use cases here would be very helpful, as the list you originally provided is not applicable for every component. For example, the `--checkbox-color` CSS variable that was mentioned would not be applicable for, say, `ion-datetime` as there are no checkboxes in that component.

We do also plan on adding support for CSS Shadow Parts which should greatly alleviate a lot of confusion with styling components in the Shadow DOM. Some browsers already support this, with most of the remaining browsers looking to ship support in January 2020 at the time of writing.

**Comment by rajiramamoorthi** [comment]
> Thanks for the follow up. I do not think adding a CSS variable for every CSS property to every Shadow DOM component is the right solution here.
> 
> Are there certain components you want to be able to style in a certain way? Use cases here would be very helpful, as the list you originally provided is not applicable for every component. For example, the `--checkbox-color` CSS variable that was mentioned would not be applicable for, say, `ion-datetime` as there are no checkboxes in that component.
> 
> We do also plan on adding support for CSS Shadow Parts which should greatly alleviate a lot of confusion with styling components in the Shadow DOM. Some browsers already support this, with most of the remaining browsers looking to ship support in January 2020 at the time of writing.

Thanks for the reply. I am looking maximum supported CSS variables for all the ionic shadow components. This will provide more flexibility to customize shadow components

**Comment by liamdebeasi** [comment]
I understand that you are looking for more flexibility in styling. What specifically are you looking to style? Adding a CSS Variable for every CSS Property increases the size and complexity of working with Ionic Framework and is not something we are looking to do at this time. However, we are more than happy to add specific variables for certain components once we understand the use cases for them.

**Comment by rajiramamoorthi** [comment]
> Thanks for the follow up. I do not think adding a CSS variable for every CSS property to every Shadow DOM component is the right solution here.
> 
> Are there certain components you want to be able to style in a certain way? Use cases here would be very helpful, as the list you originally provided is not applicable for every component. For example, the `--checkbox-color` CSS variable that was mentioned would not be applicable for, say, `ion-datetime` as there are no checkboxes in that component.
> 
> We do also plan on adding support for CSS Shadow Parts which should greatly alleviate a lot of confusion with styling components in the Shadow DOM. Some browsers already support this, with most of the remaining browsers looking to ship support in January 2020 at the time of writing.

Please add all the supported CSS variables for all the ionic shadow components.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I am going to close this issue as there is nothing actionable on our part regarding the addition of these CSS Variables.

As I explained before, we are not looking to add 50+ CSS Variables for each component at this time.

If you are able to determine the variables that you would like to see added (i.e. specific variables,  not just a list of variables to be applied to every component), feel free to open a new issue. Please be sure to include the components you would like to see these variables applied to as well as use cases for the variables. Thanks!
