### ISSUE TITLE
bug: When user click on button component, then button stay sticked (not returned to default state)

### ISSUE THREAD

**Issue by norbertbede** [ionic-team/ionic#20057]
# Bug Report
When user click on button component, then button stay sticked (not returned to default state)- stay light blue - see attached examples. Issue appear after upgrade OS from Android 7 (android webview 67) to Android 8.1 (android webview 73)

![IMG_20191210_082917](https://user-images.githubusercontent.com/3862461/70552931-80422500-1b7a-11ea-97da-01b95fd3b1e4.jpg)
![IMG_20191210_082850](https://user-images.githubusercontent.com/3862461/70552945-889a6000-1b7a-11ea-982a-416a55d1671e.jpg)

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**
Android 8.1 on Zebra MC33 Android 8.1 Non-GMS should have same behaviour as GMS devices - any device).

**Steps to reproduce:**

1. Create simple android 4 latest app to date 10.dec
2. add a component button
3. build android version API 26
4. upgrade Zebra MC33 to the latest U19 Android 8.1 - [Android O Non-GMS Update 19](https://www.zebra.com/apps/dlmanager?dlp=-227178c9720c025483893483886ea540bd07dd0f9873752cf891686eb495040ba85f97bf163f9fd12080ee1978f57c98463270ae549b1b54835db7ccc08954b22be55425ad0afa80eb71d1c0b6ff95bc7c18f15726acbbf96babeb737f993db0f8db45c5aedee25450b394da4a4660d233a53b86a54b8e40e7cceb0bf94848881299b8950e32f7b&c=us&l=en)
5. install app built in step 3.
6. click to button = button stay sticked (not returned to default state)- stay light blue - see attached examples

**Related code:**

**Other information:**

**Ionic info:**

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by norbertbede** [comment]
hi,

i found the cause. I had trouble in primary variables. i use ionic color generator, to fix the issue. 
however still not understand why this behave another way on zebra environment android 8.1 - chrome browser and huawei android 9 doesn't show any strange behaviour. Maybe ionic another interpret some style attributes ? maybe can improve this for other mistakes.

<img width="618" alt="zebracssvariable" src="https://user-images.githubusercontent.com/3862461/71398214-01d88f00-2620-11ea-9a03-591b7040eb1c.png">

norbert

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as it sounds like the original issue has been resolved. If you are still running into issues, please reply with a description of the issue, and I can take a look. Thanks!
