### ISSUE TITLE
bug: AlertController message property sanitizes html preventing accessibility attributes

### ISSUE THREAD

**Issue by MKhowaja** [ionic-team/ionic#20065]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When using alert controller, the message property sanitizes the html provided and prevents usage of aria-* attributes, alt text etc that are used to make apps accessible.

**Expected behavior:**
The sanitization process should not remove accessibility related attribute information thus allowing users to make their alerts accessible. 

**Related code:**
Sanitization code can be found here
https://github.com/ionic-team/ionic/blob/master/core/src/utils/sanitization/index.ts

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this in favor of being able to eject from the sanitization process altogether (https://github.com/ionic-team/ionic/issues/18277).

The benefit is that you would be able to use aria-* attributes, alt text, etc while still being able to take advantage of things like the Angular sanitizer. (Our built-in sanitizer is really only for vanilla JS apps or other frameworks that do not have sanitizers built in).
