### ISSUE TITLE
bug: keyboard in ion-searchbar not showing search button on real Android Device

### ISSUE THREAD

**Issue by kyubix** [ionic-team/ionic#20074]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Keyboard not showing search icon on real android device
![bug](https://user-images.githubusercontent.com/7147405/70748733-29e10c00-1d5d-11ea-9ee3-836ae83647d5.png)

**Expected behavior:**
Keyboard showing search icon 
![Screenshot_2019-12-13-03-29-55_com whatsapp](https://user-images.githubusercontent.com/7147405/70748763-38c7be80-1d5d-11ea-8b74-d6323f743d5d.png)

**Steps to reproduce:**

On documentation, the default type in `<ion-searchbar>` is search but it's not showing.
Also adding `type=search` and tag `<form>` based on this issue [#6161](https://github.com/ionic-team/ionic/issues/6161) doesn't work.

**Related code:**

```
 <form > 
  <ion-searchbar (search)="search($event)" 
  name="search" [type]="search" inputmode="search" type="search"
  (ionChange)="search($event)" debounce=1200></ion-searchbar>

</form>
```

**Other information:**

This bug maybe related to this issue [#14201](https://github.com/ionic-team/ionic/issues/14201)
And also I notice in this [#14967](https://github.com/ionic-team/ionic/issues/14967) screenshot,
in the keyboard section, it's not showing search icon

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.8 (C:\Users\kenz_\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 13 other plugins)

Utility:

   cordova-res : 0.8.1
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (C:\Users\kenz_\AppData\Local\Android\Sdk)
   NodeJS            : v11.4.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. While this is technically the correct behavior, I don't think there is a good way of opting out of it.

The search inputmode should be showing a carriage return icon when being used: https://css-tricks.com/everything-you-ever-wanted-to-know-about-inputmode

However, users that want to use the magnifying glass icon instead have to use a "hacky" way of opting out:

`<ion-searchbar inputmode=""></ion-searchbar>`

For now, you can use this workaround. I am going to consider this issue a feature/enhancement request and will look into a better way of approaching this.

**Comment by kyubix** [comment]
@liamdebeasi Thank you for your solution, using `<ion-searchbar inputmode=""></ion-searchbar> `solving the issue

**Comment by liamdebeasi** [comment]
Thanks for this issue! This has been resolved, and the new behavior will be available in an upcoming version of Ionic Framework. I have changed the `inputmode` property to `undefined`, which will cause the magnifying glass to show up instead of the carriage return. To get the old behavior, set `inputmode` to `"search"`.
