### ISSUE TITLE
bug: Ion slides get stuck on ios after popover

### ISSUE THREAD

**Issue by FernetB** [ionic-team/ionic#20070]
# Bug Report

**Ionic version:**

[x] **4.7.4**

**Current behavior:**

I have 2 pages A and B, the first one with 3 slides.
i go from A to B, when i want to go back from B to A, a popover is displayed and if i click "ok" the the location.back() is fired and i go back to A. Once in A if i try to swipe the slide, it gets stuck between the 2 slides.

**Expected behavior:**

I expect to swipe the slides when go back and do not get stuck.

**Steps to reproduce:**

Create 2 pages, the first one with an ion-slides, the second one with a button that triggers a popover that send me back to the first one with location.back(), then try to swipe the slide.

IMPORTANT: the bug occurs ONLY in ios and in a simulator/real device, in web and android this works as expected.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.3 (C:\Users\PC\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.1.2
   @angular/cli                  : 8.1.2
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : not installed
   @capacitor/core : not installed

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 7 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (C:\Users\PC\AppData\Local\Android\Sdk)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.12.0
   OS                : Windows 10
```

**Comment by FernetB** [comment]
Update: is something wrong with the dom, because when i go back to page A, if i swipe down activating the ion-refresher i can see the form of the page B behind. it's like the page B was never removed from the dom and i guess that is what is causing the bug.

**Comment by FernetB** [comment]
No one is going to take a look at this?
All the issues post that i made ends with no one answering.

**Comment by zamora95** [comment]
Check out this other open issue https://github.com/ionic-team/ionic/issues/19638
Maybe workarounds provided there will help you

**Comment by FernetB** [comment]
i saw it but is not the same bug, the bug i described was ony in ios devices, and was slightly different.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please provide a repo with the code required to reproduce this issue?

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
