### ISSUE TITLE
feat: add strong typing for ModalController dismiss values

### ISSUE THREAD

**Issue by RoopeHakulinen** [ionic-team/ionic#20088]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
Currently the dismissal data of a shown modal is not typed. `onWillDismiss` uses the following signature: 

```
'onWillDismiss': () => Promise<OverlayEventDetail<any>>;
```

`OverlayEventDetail` already supports the parametrization but `any` type is specified here. Instead it could be using a type specified when creating the modal so this

```
const modal = await this.modalController.create({
  component: EditDeviceSettingsPage
});
await modal.present();
const { settings } = await modal.onWillDismiss().then(({ data }) => data);
// settings is of type any
```

would become

```
const modal = await this.modalController.create<Settings>({
  component: EditDeviceSettingsPage
});
await modal.present();
const { settings } = await modal.onWillDismiss().then(({ data }) => data);
// settings is of type Settings
```

**Describe Preferred Solution**
Add type parameter for `ModalController::create` to specify the possible value returned upon dismissal.

**Additional Context**
This would not improve the typing in the modal component itself as it could still dismiss anything it wishes. I cannot foresee any chance to improve that with the current design but this would at least improve the ergonomics on the parent.

**Comment by tawfiek** [comment]
Interested .. I will investigate in this

**Comment by brandyscarney** [comment]
Thank you for the issue! This has been done with the following PR: https://github.com/ionic-team/ionic/pull/21393

Please let me know if this doesn't solve your use case and I will reopen, thanks!
