### ISSUE TITLE
feat: Migration tool for Ionic Angular to Ionic React

### ISSUE THREAD

**Issue by ShadeAJ1** [ionic-team/ionic#20090]
Is it possible for the team to develop a migration tool or a migration guide that details some core things that have changed and a pathway to migrate from Angular to React?

**Comment by liamdebeasi** [comment]
Thanks for the feature request. The main difference between Ionic Angular and Ionic React is with routing which you can learn more about here: https://ionicframework.com/docs/react/navigation. The main concepts of Ionic remain the same across frameworks. Is there a particular issue you are running into while migrating?

**Comment by ShadeAJ1** [comment]
Hey Liam. I took a look at the routing docs and they explain a lot! I have a few questions...

- Currently I am migrating an app that is using AWS Amplify to connect to an AWS backend. Would I migrate the project as an Ionic project or React (not React Native) project?

- Being completely new to react (but aware of its advantages), what is the difference between a js and a jsx file? 

- Also when implementing logic (such as queries, calculations, etc.) am I able to write in typescript, or do I have to use js?

- I use Ionic Studio as of now to do testing and debugging. Are there plans to support ionic react in the studio?

- Is there a docs section with descriptions of what goes in each react file and the files tree?

- Also, is it possible for a small sample app in Ionic React to be seen in the docs off of which we can learn from? 

I’m sorry, I know some of these aren’t really migration issues but just questions and there are a lot of questions. However I would highly appreciate your help. Thanks!

**Comment by liamdebeasi** [comment]
Glad the docs help clear some things up.

> Hey Liam. I took a look at the routing docs and they explain a lot! I have a few questions...
> 
> * Currently I am migrating an app that is using AWS Amplify to connect to an AWS backend. Would I migrate the project as an Ionic project or React (not React Native) project?

AWS Amplify supports both Ionic and React Native, so it’s really up to you. 

> * Being completely new to react (but aware of its advantages), what is the difference between a js and a jsx file?
> * Also when implementing logic (such as queries, calculations, etc.) am I able to write in typescript, or do I have to use js?

 I recommend reading this React intro: https://reactjs.org/tutorial/tutorial.html. Most of the answers to your questions are in “Overview”.

> * I use Ionic Studio as of now to do testing and debugging. Are there plans to support ionic react in the studio?

Studio's primary focus is Ionic Angular. We have not ruled out React support, we just don’t have anything to announce on that front at this time.

> * Is there a docs section with descriptions of what goes in each react file and the files tree?
> * Also, is it possible for a small sample app in Ionic React to be seen in the docs off of which we can learn from?
> 

The Ionic React docs have a tutorial that walks you through the basic application architecture as well as building an example app: https://ionicframework.com/docs/react. For further examples, you can use the Ionic CLI to generate blank, sidemenu, and tabs starter applications using `ionic start`.

For further help with these, the Ionic Forums is a great place to go with any other questions: http://forum.ionicframework.com/. Hope this helps! 🙂
