### ISSUE TITLE
bug: ionic support android 10

### ISSUE THREAD

**Issue by GravesDXD** [ionic-team/ionic#20099]
I want to know how the ionic3 project supports Android 10. I have downloaded the latest SDK29,and changed the config ToolsVersion to 29. but I found Android 10 mobile crash and is not compatible after downloaded and installed. but other Android is ok, like Android 9. how to fix it. thanks a lot

**Comment by danielsogl** [comment]
Ionic 3 depends on Cordova. There is an open issue about SDK29: https://github.com/apache/cordova-android/issues/830
