### ISSUE TITLE
bug: IonReactRouter - dynamically created routes aren't navigable

### ISSUE THREAD

**Issue by allforabit** [ionic-team/ionic#20109]
# Bug Report

**Ionic version:**
5.0.0-beta2
(but also affects current stable version)

**Current behavior:**
Dynamically created routes do not navigate correctly. I.e. by generating routes based on state for instance.

**Expected behavior:**
Routes should be navigable even if they are generated dynamically.

**Steps to reproduce:**
1. Setup a state variable
2. Based on this state generate some routes
3. Navigate to these routes

**Related code:**

A recreation of the issue can be seen here: https://codesandbox.io/s/ionic-dynamic-routes-65ok2

**Other information:**

This issue doesn't occur when using `react-router` and this works as expected.

**Comment by allforabit** [comment]
If you force the router to re-render by using a key it creates the route properly. Although this causes a slight visual glitch. I'm assuming something is being setup in the `RouteManager` class that isn't updating when the route children update. It's quite an involved class though so I haven't been able to figure out exactly what needs to be updated to keep it fully in sync.

**Comment by elylucas** [comment]
Hi @allforabit 

Could you test in the latest @ionic/react and let me know if this is still an issue? We did put some stuff in to update routes that are initially calculated in the first render.

Thanks

**Comment by allforabit** [comment]
Hi thanks for the update @elylucas that seems to have done the trick and it's working great now.
