### ISSUE TITLE
bug: How to attach picker inside the page like ios Native picker?

### ISSUE THREAD

**Issue by rajiramamoorthi** [ionic-team/ionic#20103]
I am not able to show picker inside the ionic page and ionic is providing option to show like model/popover/bottomsheet (top of the existing page). 
Here i have attached screenshot for iOS picker inside the page. 

![ios-picker](https://user-images.githubusercontent.com/22537172/71086670-79da2b80-21c0-11ea-8a59-3a25a5af1d5e.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This is currently not possible. There is a feature request to add this functionality: https://github.com/ionic-team/ionic/issues/19642.
