### ISSUE TITLE
bug: ion-select and ion-datetime cover the start and end slots of ion-item

### ISSUE THREAD

**Issue by mattsteve** [ionic-team/ionic#20112]
# Bug Report

**Ionic version:**
[x] **4.11.7**

**Current behavior:**
When an `ion-item` contains an `ion-select` or `ion-datetime`, the content of the start and end slots is not clickable. For example, if I want to add a button to the end slot that resets the value of an `ion-select`, that button cannot be clicked because the `ion-select` creates an absolutely positioned HTML button that covers the entire clickable area of the `ion-item`.

**Expected behavior:**
The `ion-select` clickable area should only cover itself and its `ion-label`, not the entire `ion-item`.

**Steps to reproduce:**
Create an `ion-item` with an `ion-label`, `ion-select`, and `ion-button` (with slot="end").

**Related code:**

JS FIDDLE: https://jsfiddle.net/qbu8njx0/

```
<ion-item>
    <ion-label position="floating">Choose One...</ion-label>
    <ion-select>
        <ion-select-option value="foo">Foo</ion-select-option>
        <ion-select-option value="bar">Bar</ion-select-option>
        <ion-select-option value="bat">Bat</ion-select-option>
    </ion-select>
    <ion-button slot="end" class="ion-align-self-end">
        <ion-icon name="close"></ion-icon>
    </ion-button>
</ion-item>
```

**Ionic info:**
N/A. Working out of jsfiddle with CDN.

**Comment by brandyscarney** [comment]
Thanks for the issue! This has actually been resolved in the `next` release so I am going to close this, check out this blog post on more information for the `5.0.0` release candidate: https://ionicframework.com/blog/ionic-5-0-0-release-candidate/

Here's a Codepen using `next`: https://codepen.io/brandyscarney/pen/xxbBozY
