### ISSUE TITLE
bug: back button mising in collapsible header

### ISSUE THREAD

**Issue by Sroose** [ionic-team/ionic#20113]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Using ion-back-button in a collapsible header structure, does not show the button. Using any other ion-button does show though.

**Expected behavior:**
Button should be shown at top left.

**Steps to reproduce:**
`Follow documentation at https://ionicframework.com/docs/api/title and add a back button`

**Related code:**

See my example at:
https://stackblitz.com/edit/ionic-4-template-wngkvb

```
<ion-header>
  <ion-toolbar>
    <ion-back-button></ion-back-button>
    <ion-title>Title</ion-title>               
  </ion-toolbar>
</ion-header>

<ion-content fullscreen="true" class="ion-padding">
  <ion-header collapse="condense">
    <ion-toolbar>
      <ion-title size="large">Title</ion-title>
    </ion-toolbar>
  </ion-header>
  <p>lot of text for scrolling</p>
</ion-content>
```

**Other information:**

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI) : 4.12.0

System:

   NodeJS : v10.16.3
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by amilamen** [comment]
Test this solution : 
 
<ion-buttons slot="start">
      <ion-back-button></ion-back-button>
</ion-buttons>

**Comment by amilamen** [comment]
` <ion-buttons slot="start">
      <ion-back-button></ion-back-button>
    </ion-buttons>`

**Comment by Sroose** [comment]
Hi @amilamen, using this code snippet, the button is invisible (in both scrolled as non scrolled state)

**Comment by amilamen** [comment]
Have you tried to navigate forward on your page which have a back button ? Because a back button will be visible if you make a forward navigation.

**Comment by Sroose** [comment]
@amilamen I had the issue even when navigating. However, I'm reproducing in the stackblitz and indeed it shows up after navigation. Let me try to reproduce it in my app and I'll get back on this.

**Comment by Sroose** [comment]
The navigation we did was indeed a tab navigation, which is the reason there was no back button! Closing this issue. Thanks for the help @amilamen.

**Comment by amilamen** [comment]
@Sroose you're welcome ! The pleasure is for me.
