### ISSUE TITLE
bug: Ionic Enterprise Auth plugin (Azure authentication) is not working in Android at China

### ISSUE THREAD

**Issue by goldshteinavi** [ionic-team/ionic#20118]
# Bug Report

**Ionic version:**

[x] **4.x**
Ionic version 4

**Current behavior:**

There is an option in our App that use Ionic Enterprise Auth plugin (Azure authentication).
This option is working fine in Android and Apple, however it is not working at China district in Android devices (it is working fine in Apple devices).

**Expected behavior:**
This option is open secured browser for login but there is no content displayed

**Steps to reproduce:**
Click on "Login To MyZIM" button (screen shots attached)

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by bryplano** [comment]
@goldshteinavi - if you have an issue with one of the Ionic Enterprise plugins, you will need to contact Ionic Support directly (this is the repository for the Ionic Framework).

Please send an email to support@ionic.io for assistance. Thanks!

**Comment by goldshteinavi** [comment]
OK thank you


Best Regards,

[cid:image001.png@01D5C57E.70326640]
Avi Goldshtein / Digital Development Department Manager
Information Technology, Global Architecture & Development (GAD) Division
ZIM Integrated Shipping Services Ltd. / www.ZIM.com<https://www.zim.com/>
goldshtein.avi@il.zim.com<mailto:goldshtein.avi@il.zim.com> / Office: +97248653319<tel:+97248653319> / Mobile: +972527773319<tel:+972527773319>
[cid:image009.png@01D5C57E.70466370]<https://www.facebook.com/zimshippingservices>[cid:image010.png@01D5C57E.70466370]<https://www.instagram.com/zimshipping/>[cid:image011.png@01D5C57E.70466370]<https://twitter.com/zimshipping/>[cid:image012.png@01D5C57E.70466370]<http://www.linkedin.com/company/zim>[cid:image013.png@01D5C57E.70466370]<https://www.youtube.com/ZIMShipping>[cid:image014.png@01D5C57E.70466370]<https://vimeo.com/zimshipping>[cid:image015.png@01D5C57E.70466370]<https://www.glassdoor.com/Overview/Working-at-ZIM-Integrated-Shipping-Services-EI_IE194592.11,43.htm>
