### ISSUE TITLE
BUG: iOS cannot load dependencies when their link starts with //, it uses ionic: protocol instead of http:

### ISSUE THREAD

**Issue by dusan-l9** [ionic-team/ionic#20119]
# Bug Report

[x] **4.x**

**Current behavior:**
iOS Smartphones cannot lazily load third party dependencies, when their links start with two slashes "//". The error code displayed in JWPlayer is (Error Code: 101104), which indicate that the dependencies were unable to load.

**Expected behavior:**
By default, `http` or `https` protocols should be used to load files from the internet.

**Steps to reproduce:**
Here is a bug repro: https://github.com/nmiticlevi9/jwplayer-cordova-ionic4-http-issue

It is an empty `Ionic4` project, with `JWPlayer` added.
`JWPlayer` tries to load it's dependencies using links such as this one: `//ssl.p.jwpcdn.com/player/v/8.11.1/jwpsrv.js`.

Notice that the link starts with `//....`. This makes the app use the default `ionic:` protocol, instead of `https` or `http`. This means that the request URL becomes `ionic://ssl.p.jwpcdn.com/player/v/8.11.1/jwpsrv.js`. Of course, those requests fail and the player is unable to load it's dependencies.

**Ionic info:**
```
$ ionic info
Ionic:
   Ionic CLI : 5.4.9
Utility:
   cordova-res : not installed
   native-run  : 0.2.9 (update available: 0.3.0)
System:
   NodeJS : v12.13.0
   npm    : 6.12.0
   OS     : macOS 10.15
```

Thank you Ionic team for all the work you've done,
Hopefully we will be able to resolve this issue as well!

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is more related to Cordova than Ionic Framework. I recommend checking the [Ionic Cordova WebView Plugin](https://github.com/ionic-team/cordova-plugin-ionic-webview) repo for related issues/posting your issue there instead.
