### ISSUE TITLE
Android Ionic DevApp missing from Play Store

### ISSUE THREAD

**Issue by mdkess** [ionic-team/ionic#20121]
The DevApp appears to be missing from the Google Play store.

https://ionicframework.com/docs/appflow/devapp links to https://play.google.com/store/apps/details?id=io.ionic.devapp&hl=en, which shows "We're sorry, the requested URL was not found on this server." Searching the store for DevApp also doesn't turn anything up. The iOS link appears to work.

**Comment by snsakib** [comment]
facing same issue

**Comment by alanlupsha** [comment]
Any updates on this? Missing since 12/26/2019 at least.

**Comment by joaocastro** [comment]
Is there at least an apk available for use while this problem isn't solved?

**Comment by liamdebeasi** [comment]
DevApp is back on the Play Store. Thanks for letting us know!
