### ISSUE TITLE
bug: Ionic popover component string not working

### ISSUE THREAD

**Issue by satheshk385** [ionic-team/ionic#20122]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Ionic popover working with component, but not with string
![image](https://user-images.githubusercontent.com/29550859/71498748-8c6cf880-2883-11ea-8615-061f5a0e8484.png)
![image](https://user-images.githubusercontent.com/29550859/71498770-a4447c80-2883-11ea-99df-bb269f6e812e.png)
Not accepting string

**Expected behavior:**
Need to accept string in popover

**Steps to reproduce:**
https://ionicframework.com/docs/api/popover
Follow the documentation change component to string

**Related code:**
May be you can change documentation a bit
async presentPopover(ev: any) {
    let popover;
    await this.popoverController.create({
      component: null,
      event: ev,
      translucent: true
    }).then((result)=>{
      popover = result;
    });
    return popover.present();
  }

**Comment by brandyscarney** [comment]
Thanks for the issue. The `component` property can accept a `string` it just only works for certain framework integrations (`JavaScript`, `Vue`). We recommend referring to the usage for the component instead: https://ionicframework.com/docs/api/popover#usage
