### ISSUE TITLE
bug: IonDateTime min/max does not respect UTC strings

### ISSUE THREAD

**Issue by pjc2007** [ionic-team/ionic#20134]
**Ionic version:**
[x] **4.x**

**Current behavior:**
If I supply a UTC date/time string to the min/max parameters of the IonDateTime, it is interpreted as local time. Also, it does not support decimals in the string

**Expected behavior:**
Would be good if the UTC conversion was done, so the the display of course shons local time

**Steps to reproduce:**
Supply a iso 8601 UTC date/time to the min/max parameters
**Related code:**

StackBlitz
[https://stackblitz.com/edit/iondatetime-min-max](https://stackblitz.com/edit/iondatetime-min-max)

In the tab 1 above, I have the following...
```
<ion-item >
    <ion-label>Date time</ion-label>
    <ion-datetime displayFormat="D MMM YYYY HH:mm"
      min='2018-06-25T09:00:00Z'
      max='2018-06-25T11:00:00Z'>
    </ion-datetime>
  </ion-item>
```

When we see this in the UI, I see the above interpreted as local time, except that max is out by 59 seconds, ie max is 11:59 instead of the minutes being restricted to just 0 (or perhaps being 10:59)

Eg my timezone is UTC+8.00 and I see the min time as 9am local time and 11 local time instead of min of 5pm local time, and max of 7pm.

My "hacky" workaround for this at the moment is

```
      const offset = -new Date().getTimezoneOffset();
      const start = new Date(this.minDateTime);
      start.setTime(start.getTime() + offset * 60000);
      this.minDateTime = start.toISOString();

  <ion-datetime displayFormat="D MMM YYYY HH:mm"
      [min]='minDateTime '
      [max]='maxDateTime '>
    </ion-datetime>
```

Also. it does not like decimals in the date/time string.

e.g. `min='2018-06-25T09:00:00.00Z'` causes an error

My work around is in code..
```
this.minTime = this.minTime.split('.')[0] + 'Z';
```
and then binding to this

**Ionic info:**

```
$ ionic info

Ionic:

   Ionic CLI                     : 5.2.3 (C:\Users\pchapman\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Utility:

   cordova-res : 0.7.0-testing.0
   native-run  : 0.2.8

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This was fixed in Ionic Framework 5.0.5.
