### ISSUE TITLE
bug: view not updated after changes ionic 4

### ISSUE THREAD

**Issue by web-ap** [ionic-team/ionic#20154]
Hi,

I'm currently developing an app using ionic cordova emulate browser. 
When I'm trying to change something on a view, the app compiles and reloads but the changes aren't displayed in view.
Here is my conf :
```
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : browser 6.0.0, ios 5.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.0, (and 18 other plugins)

System:

   Android SDK Tools : 26.1.1 
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.15.0 
   npm               : 6.4.1
   OS                : macOS Catalina
   Xcode             : Xcode 11.3 Build version 11C29
```

I tried to build on iOS, and the same issue occurs. 

What can I do ? I tried to disable Services workers as well in Chrome : no.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you trying to test this in a browser? If so, we recommend just using `ionic serve`. `ionic cordova emulate browser` is not intended for live reloading.

**Comment by web-ap** [comment]
Thanks for your reply.
Yes I do. Using ionic serve, I have an error in console which says (cordova is not available) : that's why I'm using emulate.

The issue is gone after doing a new ionic cordova prepare

I will see if this will happen again.
