### ISSUE TITLE
bug: ion-back-button does not work with angular

### ISSUE THREAD

**Issue by piernik** [ionic-team/ionic#20159]
In source code of `ion-back-button` (https://github.com/ionic-team/ionic/blob/master/core/src/components/back-button/back-button.tsx) I can see that onClick is dependent on `ion-nav`.
But when using with `angular` `ion-nav`is not used - I use `ion-router-outlet` So there is always no history so back button is not working at all.
Am I missing something?

**Comment by liamdebeasi** [comment]
For Angular you should look at the framework specific code we have written: https://github.com/ionic-team/ionic/blob/master/angular/src/directives/navigation/ion-back-button.ts. The `onClick` you are looking at is for vanilla JS apps without a framework.

We use the Angular Router in Ionic Angular apps, so `ion-back-button` should work seamlessly with it. If you are running into issues with navigation, I recommend you look at our navigation guide on our docs: https://ionicframework.com/docs/angular/navigation. Thanks!
