### ISSUE TITLE
bug: Global app.module  set "backButtonText" does not work

### ISSUE THREAD

**Issue by shamohai** [ionic-team/ionic#20164]
The latest version of ionic 4, global app.module  set "backButtonText" does not work.
You still need to change the text of the ion-back-button in the page.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by shamohai** [comment]
ionic 4 angular:

app.module.ts

![QQ图片20200109101020](https://user-images.githubusercontent.com/7419781/72031755-4c1c6a00-32c8-11ea-85fc-25324d5336a4.png)


html

![QQ图片20200109101217](https://user-images.githubusercontent.com/7419781/72031815-900f6f00-32c8-11ea-914b-1cdc9ab030d5.png)


In theory, the text of the back button should be "RETURN", but the actual display effect is still "Back"

![QQ图片20200109101500](https://user-images.githubusercontent.com/7419781/72031937-ec728e80-32c8-11ea-9aed-bc5a44b50cb2.png)

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Are you able to reproduce this in an Ionic starter application? I have been testing it in apps locally and am unable to reproduce the issue you have described.

**Comment by shamohai** [comment]
Still exist.
The text of the ion-back-button must be set on each page to override the original "Back" text.

**Comment by liamdebeasi** [comment]
Can you provide the source code for the starter app in which you reproduced the issue?
