### ISSUE TITLE
feat: Allow HTML in AlertInput checkbox label and or 

### ISSUE THREAD

**Issue by distante** [ionic-team/ionic#20168]
# Feature Request

**Ionic version:**

[x] **4.11.5** (Angular)

**Describe the Feature Request**

Some times a brief explanation is needed for alert inputs that will be better styled if it is separated of the label, if we can write html it can be done easily. The same if we get an "sublabel" property.

**Describe Preferred Solution**
Add a subLabel or allow HTML in AlertInput label.

**Describe Alternatives**
There are none.

**Example:**
![image](https://user-images.githubusercontent.com/5490201/72012213-d4b0f100-325b-11ea-9586-1e3c3116c53b.png)

That example is just an direct HTML edit in the browser.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I am going to close this as allowing arbitrary HTML in `ion-alert` is not something we are going to implement at this time.

Allowing for arbitrary HTML opens the door for many security issues including XSS attacks. We do allow for arbitrary HTML in some components already, but that is mostly for legacy application support and is not something we recommend. While we do provide some sanitization for those components, the HTML that is allowed is a very small subset of the wide variety of customization options developers would normally have.

We recommend instead using an `ion-modal` with `ion-checkbox` components. This will allow you to freely customize the checkbox dialog as you see fit.

Thanks!

**Comment by distante** [comment]
> Thanks for the feature request. I am going to close this as allowing arbitrary HTML in `ion-alert` is not something we are going to implement at this time.
> 
> Allowing for arbitrary HTML opens the door for many security issues including XSS attacks. We do allow for arbitrary HTML in some components already, but that is mostly for legacy application support and is not something we recommend. While we do provide some sanitization for those components, the HTML that is allowed is a very small subset of the wide variety of customization options developers would normally have.
> 
> We recommend instead using an `ion-modal` with `ion-checkbox` components. This will allow you to freely customize the checkbox dialog as you see fit.
> 
> Thanks!

Hi! Thanks for your reply. I totally understand the HTML issue. But how about the `subLabel` property?
