### ISSUE TITLE
bug: Ionic React: Doesn't work on MS Edge

### ISSUE THREAD

**Issue by SatoAV** [ionic-team/ionic#20160]
# Bug Report

**Ionic version:**

[x] **4.11.2**

**Current behavior:**
Although Ionic documentation states that MS Edge is supported, that seems to be wrong.
I tried to open sample Ionic React app in Edge, and got the following error:
`Unable to get property 'get' of undefined or null reference`

Unfortunately, Edge can't show proper stacktrace for the error
Sourcemaps seem to not work correctly on Edge too, since when I click on the error, debugger shows an empty line in compiled code. Around that is some code related to initializing custom components.

Installing `react-app-polyfill` and adding edge to development browserlist doesn't change anything.

**Expected behavior:**
Ionic React app should correctly run on MS Edge

**Steps to reproduce:**
Create a sample Ionic react app from CLI.
Try to launch it in MS Edge

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.2.3 (C:\Users\sato\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework : @ionic/react 4.11.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.12.1
   OS     : Windows 10
```

**Comment by ebk46** [comment]
I believe this is related to another ticket (https://github.com/ionic-team/ionic/issues/17679) that has been around for over 10 months now.

According to some conversation on the Slack group about compatibility, as well as Ionic's documentation (https://ionicframework.com/docs/intro/browser-support), Edge support should exist for ionic/react but unfortunately does not.

**Comment by SatoAV** [comment]
> According to some conversation on the Slack group about compatibility, as well as Ionic's documentation (https://ionicframework.com/docs/intro/browser-support), Edge support should exist for ionic/react but unfortunately does not.

Yeah, I came to this issue after seeing this information, so I was kinda confused.
I tested example CRA apps which Ionic React is built upon, and they work fine on Edge.

It seems that the main issue is with introduction of custom elements.
I wonder if something like this polyfill would help:
https://github.com/webcomponents/polyfills/tree/master/packages/custom-elements

**Comment by SatoAV** [comment]
> I wonder if something like this polyfill would help:
https://github.com/webcomponents/polyfills/tree/master/packages/custom-elements

The polyfill makes the app work, but all the Shadow DOM styles for components don't get applied.
According to ShadyDOM (which is used in webcomponents polyfills) docs, for proper styling, each component should be passed through ShadyDOM methods:
https://github.com/webcomponents/polyfills/blob/master/packages/shadycss/README.md#usage

Expected display (Chrome):
![image](https://user-images.githubusercontent.com/1641218/72423200-eb43d480-3794-11ea-9ca0-a31ec6ef9d63.png)

Edge with polyfills:
![image](https://user-images.githubusercontent.com/1641218/72423251-fe56a480-3794-11ea-9477-1d7fe3a8ef89.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. With the release of Ionic Framework v5 we updated our [Browser Support Table](https://ionicframework.com/docs/intro/browser-support#desktop-browsers) to state that Edge 79+ (Chromium Edge) is supported in Ionic Framework.

Chromium Edge has full support for custom elements, shadow DOM, etc so I am going to close this issue. If you run into any additional bugs, please feel free to create a new issue. Thanks!

**Comment by FangerZero** [comment]
@liamdebeasi so what you're saying is update to v5, and ionic react should work on edge? I'm on v4 currently, and had no idea that specifically ionic+react didn't work on MS products.

**Comment by liamdebeasi** [comment]
Ionic Framework v4 works with IE11 and all versions of Microsoft Edge. Ionic Framework v5 dropped support for IE11 and versions of Microsoft Edge older than v79.

For more information, please see our [Browser Support Documentation](https://ionicframework.com/docs/intro/browser-support).

**Comment by FangerZero** [comment]
Ionic Framework does work with Edge, as long as you're not using react.
