### ISSUE TITLE
Menu width in a split pane should be customizable ?

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic#20176]
Hello,

In the doc : https://ionicframework.com/docs/api/menu#css-custom-properties there's an example of a menu with a snippet to set its width :

```
.my-custom-menu {
  --width: 500px;
}
```

But when the menu is in a split pane (like most of the time ?) it doesn't work, I've done this but ..... it doesn't feel right, there should be an API to do that no ?
```
@media screen and (min-width: 992px) {
  ion-menu {
    max-width: 10% !important;
  }
} 
```

cross reference : https://forum.ionicframework.com/t/menu-width-in-a-split-pane/181225

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as the issue has already been addressed. In an upcoming version of Ionic Framework you will be able to customize the width of the menu using the `--side-width`, `--side-min-width`, and `--side-max-width` CSS variables by setting them directly on `ion-split-pane`.
