### ISSUE TITLE
bug: [react] ion-input does not allow values from type number

### ISSUE THREAD

**Issue by xQuai** [ionic-team/ionic#20173]
# Bug Report

**Ionic version:**

[x] **4.11.0**

**Current behavior:**

If i define a interface with a property from type number and create a state from this interface (class-based-component) or create a state with the hook useState and a default value of type number(function-based-component), the element ion-input says `type 'number' is not assigneable to type 'string | null | undefined'.`

**Expected behavior:**

ion-input should allow variables from type number on the attribute `value` like the normal html input.

**Steps to reproduce:**

1. Install ionic-cli `npm install -g ionic`
2. Create a project `ionic start myApp blank --capacitor --type=react`
3. Edit File `Home.tsx` like in the `Releated code` section

**Related code:**

```
const Home: React.FC = () => {

    const [numberInput, setNumberInput] = useState(0);

    return (
        <IonPage>
            <IonHeader>
                <IonToolbar>
                    <IonTitle>Ionic Blank</IonTitle>
                </IonToolbar>
            </IonHeader>
            <IonContent className="ion-padding">
                <p>Normal input with value of type number</p>
                <input value={numberInput}/>
                <p>ion-input with value of type number</p>
                <IonInput value={numberInput}/>
            </IonContent>
        </IonPage>
    );
};

export default Home;
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.13 (C:\Users\<Username>\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework : @ionic/react 4.11.7

Capacitor:

   Capacitor CLI   : 1.4.0
   @capacitor/core : 1.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.14.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10
```

**Comment by elylucas** [comment]
fixed in 4.11.9
