### ISSUE TITLE
bug[core, v5]: ion-content height 100% not inherited

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#20185]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
In Ionic v5.x (current status, tested with `@next` and `master`) it will not be possible anymore to assign an `height: 100%` to the slotted element of the `ion-content` respectively such property will be ignored.

This would for example have for effect to break the GUI of our editor (see attached Gif).

The root cause of the issue, I think, is the recent introduction of the `ion-content` shadowed child `<div id="scroll-content"/>` (see related [commit](https://github.com/ionic-team/ionic/commit/04e7c031326ec551531af291ef1a03878d168378#diff-b897261556647670dc4cc77479504b4f))

**Expected behavior:**
Still being able to use `height: 100%` for the content with Ionic v5.x.

**Steps to reproduce:**

```
git clone https://github.com/peterpeterparker/ionic-v5beta-content-height.git
cd ionic-v5beta-content-height
npm install
npm run start
```

**Related code:**

See demo repo

**Other information:**

Demo of our application (gif):

![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/16886711/72208099-42992a80-349f-11ea-8c24-1815eff4dec3.gif)

Screenshots of the provided repo:

<img width="1156" alt="Capture d’écran 2020-01-11 à 18 14 21" src="https://user-images.githubusercontent.com/16886711/72208112-68263400-349f-11ea-81ff-b346e7fdf3ad.png">

<img width="1156" alt="Capture d’écran 2020-01-11 à 18 14 28" src="https://user-images.githubusercontent.com/16886711/72208114-68263400-349f-11ea-8645-477e38870b68.png">

And a screenshot of the same repo with Ionic v4:

<img width="1156" alt="Capture d’écran 2020-01-12 à 08 35 12" src="https://user-images.githubusercontent.com/16886711/72215685-b1fe3100-3516-11ea-8f46-5290b0f10043.png">

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves your issue:

`npm i @ionic/core@5.0.0-dev.202001131408.8aeda3a`

**Comment by peterpeterparker** [comment]
@liamdebeasi thank you for your feedback. same problem with build `202001131408.8aeda3a`.

**Comment by liamdebeasi** [comment]
Hmm maybe I'm not quite sure what you are trying to do. From what I understand, you are expecting the scrollable content to take up 100% of the available containing height by default. From there, you want to be able to control the overall dimensions of `ion-content` by setting the dimension on `ion-content` directly. Is that correct?

**Comment by peterpeterparker** [comment]
@liamdebeasi yes

```
<ion-content>
    <div style="height: 100%">
    </div>
</ion-content>
```

`height` or `min-height` too I guess. 

here a screenshot from our editor in prod with v4:

<img width="1201" alt="Capture d’écran 2020-01-13 à 17 08 01" src="https://user-images.githubusercontent.com/16886711/72271557-65564b00-3627-11ea-9315-b4609c7b6088.png">

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Try this dev build:

`npm i @ionic/core@5.0.0-dev.202001131622.bfc6420`

**Comment by peterpeterparker** [comment]
super @liamdebeasi `202001131622.bfc6420` do solve the issue, thx!

I checked both the sample repo and our app.

<img width="1201" alt="Capture d’écran 2020-01-13 à 17 30 53" src="https://user-images.githubusercontent.com/16886711/72273334-76ed2200-362a-11ea-8f1a-dbcf37667e51.png">

**Comment by corysmc** [comment]
I'm noticing the problem as well @liamdebeasi also with build `202001131408.8aeda3a`

all my zero states don't center on the page anymore 😦 

![image](https://user-images.githubusercontent.com/6452188/72280755-4a1f1780-35f6-11ea-8178-e3db265caac8.png)

**Comment by liamdebeasi** [comment]
@corysmc Please try `@ionic/core@5.0.0-dev.202001131622.bfc6420`. That previous build had a mistake in it.

**Comment by corysmc** [comment]
should have refreshed the page before submitting my comments 😄 
The latest build works now `5.0.0-dev.202001131622.bfc6420`

Thanks @liamdebeasi!

**Comment by liamdebeasi** [comment]
Thanks! This issue has been resolved via https://github.com/ionic-team/ionic/pull/20194. We will be putting out a new beta soon that has this fix.

**Comment by peterpeterparker** [comment]
Thank you Liam 👍

**Comment by lincolnthree** [comment]
@liamdebeasi @peterpeterparker Unfortunately, this fix breaks elements with "position: sticky" inside the ion-content scroll-content div. Now that the height is set to 100%, once the div scrolls off screen, any sticky items (such as custom toolbars) scroll off screen with it.

This occurs when the height of the content exceeds 100% of the ion-content/viewport.

IMO: This should probably use the 'min-height: 100%' property, instead of 'height'.

Sample repo incoming.

**Comment by liamdebeasi** [comment]
@lincolnthree Can you open a new issue? Thanks!

**Comment by lincolnthree** [comment]
Sure thing.

**Comment by lincolnthree** [comment]
@liamdebeasi Done.

**Comment by LOUNNAS** [comment]
Hello, the problem still persists with the latest version 5.0.0-rc.0.

Any idea ? 

regards, 
Achille

**Comment by liamdebeasi** [comment]
@LOUNNAS Please open a new issue. Thanks!
