### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by victororlyk** [ionic-team/ionic#20193]
# Bug Report

**Ionic version:**

[4.11.5]

**Current behavior:**

after clicking <IonItem> inside of ionMenu it renders needed page with refresh of the page.

**Expected behavior:**

push new location to the history without page refresh

**Steps to reproduce:**

create basic app with side menu.

**Related code:**
```
 <IonMenu
      contentId='main'
      side='end'
    >

      <IonHeader>
        <IonToolbar color='calypso'>
          <IonTitle>
            Menu
          </IonTitle>
        </IonToolbar>
      </IonHeader>

      <IonContent color='calypso'>
        <IonList>
                <IonItem
                  key={index}
                  color='calypso'
                  routerLink='/some'
                >
                  <IonIcon
                    slot='start'
                    icon={icon}
                  />
                  <IonLabel>
                    {title}
                  </IonLabel>

                </IonItem>
              );
```

```
insert short code snippets here
```

**Other information:**
don't know if it is important but the tabs below are present

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by elylucas** [comment]
Hi @victororlyk,

Couple of things to try:

1) Update to latest @ionic/react and @ionic/react-router as there has been several bugs fixed around this since 4.11.5 that might help.
2) add  routerDirection="none" to the IonItem to get rid of the animation when changing routes from the menu.

Let me know if those don't work. 

Going to close for now but can reopen if a bug is found.

**Comment by victororlyk** [comment]
@elylucas 
I am on `    "@ionic/react": "^4.11.5",`
have updated code to look like this
```
<IonItem
                  key={index}
                  color='calypso'
                  routerLink={url}
                  routerDirection='none'
                >
```
but it still get's reloading

**Comment by elylucas** [comment]
@victororlyk are you able to upgrade to the latest ionic/react and try again?

**Comment by victororlyk** [comment]
yes it has fixed the issue, but the main problem was also with bad documentation for setting up routing in ionic. 
```
        <IonSplitPane contentId='main'>
          <IonReactRouter>
            <Menu {...{ appPages }} />
            <IonPage id='main'>
              <IonRouterOutlet>
                {mainPages.map(
                  ({ component, path, isExact, isPrivate }, index) => {
                    return isPrivate
                      ?
                      <PrivateRoute
                        key={index}
                        {...{ component, path }}
                        exact={isExact}
                      />
                      :
                      <Route
                        key={index}
                        {...{ path, component }}
                        exact={isExact}
                      />;
                  })}
              </IonRouterOutlet>
            </IonPage>
          </IonReactRouter>
        </IonSplitPane>

```
so the <Menu/> should be inside of IonReactRouter and there is no words about this in docs, otherwise it keeps reloading.
