### ISSUE TITLE
Navigating to an external link from an ionic 4 app makes the hardware back button close the app where there is navigation history?

### ISSUE THREAD

**Issue by AhmedEl-Atab** [ionic-team/ionic#20199]
Navigate to an external link or display an interstitial Ad (AdMob) and then return to the app by clicking on the hardware back button. At this stage where there are pages in the history (navigation stack), clicking on the hardware back button will cause the app to close! Knowing that I had tried to register to the back button by:

```
this.platform.backbutton.subscribe(()=>{
this.navCtrl.pop();
// Also tried: this.navCtrl.back();
});
```

But it is still exiting the app!

Any idea about how to solve this?!

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is more of a support request. I would recommend checking to see if the AdMob plugin you are using allows for any control over the hardware back button in terms of returning you to the app after displaying an ad.
