### ISSUE TITLE
bug: ngI18nClosureMode mode is not defined

### ISSUE THREAD

**Issue by norbertbede** [ionic-team/ionic#20195]
# Bug Report
production build shows white page and ngI18nClosureMode undefined error in logs

**Ionic version:**

[x] **4.x**

**Current behavior:**

When I run ionic build --prod, Generate Cordova based Apk in Android Studio, then  the app shows white page, in the log I found an error with angular ngI18nClosureMode. The same behavior I got in electron serve.

![ngI18nClosure](https://user-images.githubusercontent.com/3862461/72267824-01308880-3621-11ea-9a51-0749f8a586ef.png)

**Expected behavior:**

N/A

**Steps to reproduce:**

**Other information:**

https://github.com/angular/angular/blob/master/packages/core/src/util/ng_i18n_closure_mode.ts

**Ionic info:**

```
ionic info

Ionic:

   Ionic CLI                     : 5.4.13 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.803.22
   @angular-devkit/schematics    : 8.3.22
   @angular/cli                  : 8.3.21
   @ionic/angular-toolkit        : 2.1.1

Capacitor:

   Capacitor CLI   : 1.4.0
   @capacitor/core : 1.4.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-sim : 8.0.2
   NodeJS  : v10.16.3 (/usr/local/bin/node)
   npm     : 6.13.6
   OS      : macOS Catalina
   Xcode   : Xcode 11.1 Build version 11A1027

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?
