### ISSUE TITLE
feat: Apple Watch Support

### ISSUE THREAD

**Issue by AndreDriesel** [ionic-team/ionic#20190]
# Feature Request

**Ionic version:**
[x] **4.x** current/latest

**Describe the Feature Request**
Support to create Apple Watch Apps

**Additional Context**
My daughter has some critical hearth issues and i need the option to develop an app for apple watch, which could syncs the hearth-rate of the watch with other users, parents or any other family member.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Apple does not expose a public webview for running Capacitor/Cordova applications, so Ionic Framework currently cannot run on the Apple Watch.
