### ISSUE TITLE
bug: class attribute of ion-modal element doesn't change after updating cssClass property of IonModal component

### ISSUE THREAD

**Issue by alekseykarpenko** [ionic-team/ionic#20192]
# Bug Report

**Ionic version:**

[x] **4.x**

**Steps to reproduce:**
* Use the `IonModal` component from `@ionic/react` package in your app. 
* Update the `cssClass` property of the `IonModal` component. 

**Current behavior:**

Nothing happens. Attribute `class` of the `ion-modal` DOM element doesn't change

**Expected behavior:**

Updating the `cssClass` property of the `IonModal` component should update the `class` attribute of the `ion-modal` DOM element.

**Related code:**

```typescript
import * as React from 'react';
import {useState} from "react";
import {
  IonButton,
  IonContent,
  IonModal,
} from "@ionic/react";


export const TestModal = () => {

  const [showModal, setShowModal] = useState(false);
  const [modalClass, setModalClass] = useState("my-modal");

  return (
    <>
      <IonButton onClick={() => setShowModal(true)}>Show modal</IonButton>
      <IonModal isOpen={showModal} cssClass={modalClass} showBackdrop={false}>
        <IonContent>
          <IonButton onClick={() => setShowModal(false)}>Close modal</IonButton>
          <IonButton onClick={() => setModalClass("new-modal-class")} color="secondary">Change css class</IonButton>
        </IonContent>
      </IonModal>
    </>
  );
};
```

**Other information:**

I remember that `@ionic/react` is still a port from Angular. Looks like updating `cssClass` of `IonModal` should update `css-class` attribute (old Angular directive?), as direct updating `css-class` attribute causes updating `class`:
![image](https://user-images.githubusercontent.com/4648983/72256120-1ef5f180-3611-11ea-9bcc-0a46cc7ed14f.png)

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.11 (/Users/ak/.nvm/versions/node/v10.16.3/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.5

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (/Users/ak/.nvm/versions/node/v10.16.3/bin/node)
   npm    : 6.9.0
   OS     : macOS Catalina
```

**Comment by elylucas** [comment]
fixed in #20228 and will be in 4.11.9
