### ISSUE TITLE
bug: Interface 'HTMLIonIconElement' cannot simultaneously extend types 'IonIcon' and 'IonIcon'

### ISSUE THREAD

**Issue by ildar-icoosoft** [ionic-team/ionic#20208]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I'm trying to use Ionic components in my angular library (npm module). I've created the angular library using this [manual](https://angular.io/guide/creating-libraries). Then I've installed @ionic/angular to package.json dependencies. And if I import anything from "@ionic/angular" (for example "import { IonicModule } from "@ionic/angular";") I'm getting many errors like this in "node_modules/ionicons/dist/types/components.d.ts(63,13):":
```
TS2320: Interface 'HTMLIonIconElement' cannot simultaneously extend types 'IonIcon' and 'IonIcon'.
 Named property ''icon'' of types 'IonIcon' and 'IonIcon' are not identical.

TS2320: Interface 'HTMLIonIconElement' cannot simultaneously extend types 'HTMLStencilElement' and 'HTMLStencilElement'.
  Named property 'forceUpdate' of types 'HTMLStencilElement' and 'HTMLStencilElement' are not identical.
```

**Expected behavior:**

import should not cause errors

**Steps to reproduce:**

1. Generate new angular library:
```
ng new my-workspace --create-application=false
cd my-workspace
ng generate library my-lib
```
2. install "@ionic/angular" module in the library
```
npm i @ionic/angular --save
``` 
3. import anything from @ionic/angular:
```
import { IonicModule } from "@ionic/angular";
```

**Comment by joelmeaders** [comment]
I'm getting this error across the board when attempting to use Ionic 5 RC 1 in a project upgraded from Ionic 4.11.10.

`
[ng] ERROR in node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2676:13 - error TS2320: Interface 'HTMLIonActionSheetElement' cannot simultaneously extend types 'IonActionSheet' and 'IonActionSheet'.
[ng]   Named property ''enterAnimation'' of types 'IonActionSheet' and 'IonActionSheet' are not identical.
[ng] 2676   interface HTMLIonActionSheetElement extends Components.IonActionSheet, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2676:13 - error TS2320: Interface 'HTMLIonActionSheetElement' cannot simultaneously extend types 'IonActionSheet' and 'IonActionSheet'.
[ng]   Named property ''leaveAnimation'' of types 'IonActionSheet' and 'IonActionSheet' are not identical.
[ng] 2676   interface HTMLIonActionSheetElement extends Components.IonActionSheet, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2682:13 - error TS2320: Interface 'HTMLIonAlertElement' cannot simultaneously extend types 'IonAlert' and 'IonAlert'.
[ng]   Named property ''enterAnimation'' of types 'IonAlert' and 'IonAlert' are not identical.
[ng] 2682   interface HTMLIonAlertElement extends Components.IonAlert, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2682:13 - error TS2320: Interface 'HTMLIonAlertElement' cannot simultaneously extend types 'IonAlert' and 'IonAlert'.
[ng]   Named property ''inputs'' of types 'IonAlert' and 'IonAlert' are not identical.
[ng] 2682   interface HTMLIonAlertElement extends Components.IonAlert, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2682:13 - error TS2320: Interface 'HTMLIonAlertElement' cannot simultaneously extend types 'IonAlert' and 'IonAlert'.
[ng]   Named property ''leaveAnimation'' of types 'IonAlert' and 'IonAlert' are not identical.
[ng] 2682   interface HTMLIonAlertElement extends Components.IonAlert, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2784:13 - error TS2320: Interface 'HTMLIonDatetimeElement' cannot simultaneously extend types 'IonDatetime' and 'IonDatetime'.
[ng]   Named property ''pickerOptions'' of types 'IonDatetime' and 'IonDatetime' are not identical.
[ng] 2784   interface HTMLIonDatetimeElement extends Components.IonDatetime, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2844:13 - error TS2320: Interface 'HTMLIonInputElement' cannot simultaneously extend types 'IonInput' and 'IonInput'.
[ng]   Named property ''value'' of types 'IonInput' and 'IonInput' are not identical.
[ng] 2844   interface HTMLIonInputElement extends Components.IonInput, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2904:13 - error TS2320: Interface 'HTMLIonLoadingElement' cannot simultaneously extend types 'IonLoading' and 'IonLoading'.
[ng]   Named property ''enterAnimation'' of types 'IonLoading' and 'IonLoading' are not identical.
[ng] 2904   interface HTMLIonLoadingElement extends Components.IonLoading, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2904:13 - error TS2320: Interface 'HTMLIonLoadingElement' cannot simultaneously extend types 'IonLoading' and 'IonLoading'.
[ng]   Named property ''leaveAnimation'' of types 'IonLoading' and 'IonLoading' are not identical.
[ng] 2904   interface HTMLIonLoadingElement extends Components.IonLoading, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2928:13 - error TS2320: Interface 'HTMLIonModalElement' cannot simultaneously extend types 'IonModal' and 'IonModal'.
[ng]   Named property ''enterAnimation'' of types 'IonModal' and 'IonModal' are not identical.
[ng] 2928   interface HTMLIonModalElement extends Components.IonModal, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2928:13 - error TS2320: Interface 'HTMLIonModalElement' cannot simultaneously extend types 'IonModal' and 'IonModal'.
[ng]   Named property ''leaveAnimation'' of types 'IonModal' and 'IonModal' are not identical.
[ng] 2928   interface HTMLIonModalElement extends Components.IonModal, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2934:13 - error TS2320: Interface 'HTMLIonNavElement' cannot simultaneously extend types 'IonNav' and 'IonNav'.
[ng]   Named property ''animation'' of types 'IonNav' and 'IonNav' are not identical.
[ng] 2934   interface HTMLIonNavElement extends Components.IonNav, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2934:13 - error TS2320: Interface 'HTMLIonNavElement' cannot simultaneously extend types 'IonNav' and 'IonNav'.
[ng]   Named property ''insert'' of types 'IonNav' and 'IonNav' are not identical.
[ng] 2934   interface HTMLIonNavElement extends Components.IonNav, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2934:13 - error TS2320: Interface 'HTMLIonNavElement' cannot simultaneously extend types 'IonNav' and 'IonNav'.
[ng]   Named property ''insertPages'' of types 'IonNav' and 'IonNav' are not identical.
[ng] 2934   interface HTMLIonNavElement extends Components.IonNav, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2934:13 - error TS2320: Interface 'HTMLIonNavElement' cannot simultaneously extend types 'IonNav' and 'IonNav'.
[ng]   Named property ''pop'' of types 'IonNav' and 'IonNav' are not identical.
[ng] 2934   interface HTMLIonNavElement extends Components.IonNav, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2934:13 - error TS2320: Interface 'HTMLIonNavElement' cannot simultaneously extend types 'IonNav' and 'IonNav'.
[ng]   Named property ''popTo'' of types 'IonNav' and 'IonNav' are not identical.
[ng] 2934   interface HTMLIonNavElement extends Components.IonNav, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2934:13 - error TS2320: Interface 'HTMLIonNavElement' cannot simultaneously extend types 'IonNav' and 'IonNav'.
[ng]   Named property ''popToRoot'' of types 'IonNav' and 'IonNav' are not identical.
[ng] 2934   interface HTMLIonNavElement extends Components.IonNav, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2934:13 - error TS2320: Interface 'HTMLIonNavElement' cannot simultaneously extend types 'IonNav' and 'IonNav'.
[ng]   Named property ''push'' of types 'IonNav' and 'IonNav' are not identical.
[ng] 2934   interface HTMLIonNavElement extends Components.IonNav, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2934:13 - error TS2320: Interface 'HTMLIonNavElement' cannot simultaneously extend types 'IonNav' and 'IonNav'.
[ng]   Named property ''removeIndex'' of types 'IonNav' and 'IonNav' are not identical.
[ng] 2934   interface HTMLIonNavElement extends Components.IonNav, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2934:13 - error TS2320: Interface 'HTMLIonNavElement' cannot simultaneously extend types 'IonNav' and 'IonNav'.
[ng]   Named property ''setPages'' of types 'IonNav' and 'IonNav' are not identical.
[ng] 2934   interface HTMLIonNavElement extends Components.IonNav, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2934:13 - error TS2320: Interface 'HTMLIonNavElement' cannot simultaneously extend types 'IonNav' and 'IonNav'.
[ng]   Named property ''setRoot'' of types 'IonNav' and 'IonNav' are not identical.
[ng] 2934   interface HTMLIonNavElement extends Components.IonNav, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2952:13 - error TS2320: Interface 'HTMLIonPickerElement' cannot simultaneously extend types 'IonPicker' and 'IonPicker'.
[ng]   Named property ''enterAnimation'' of types 'IonPicker' and 'IonPicker' are not identical.
[ng] 2952   interface HTMLIonPickerElement extends Components.IonPicker, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2952:13 - error TS2320: Interface 'HTMLIonPickerElement' cannot simultaneously extend types 'IonPicker' and 'IonPicker'.
[ng]   Named property ''leaveAnimation'' of types 'IonPicker' and 'IonPicker' are not identical.
[ng] 2952   interface HTMLIonPickerElement extends Components.IonPicker, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2964:13 - error TS2320: Interface 'HTMLIonPopoverElement' cannot simultaneously extend types 'IonPopover' and 'IonPopover'.
[ng]   Named property ''enterAnimation'' of types 'IonPopover' and 'IonPopover' are not identical.
[ng] 2964   interface HTMLIonPopoverElement extends Components.IonPopover, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:2964:13 - error TS2320: Interface 'HTMLIonPopoverElement' cannot simultaneously extend types 'IonPopover' and 'IonPopover'.
[ng]   Named property ''leaveAnimation'' of types 'IonPopover' and 'IonPopover' are not identical.
[ng] 2964   interface HTMLIonPopoverElement extends Components.IonPopover, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:3048:13 - error TS2320: Interface 'HTMLIonRouterOutletElement' cannot simultaneously extend types 'IonRouterOutlet' and 'IonRouterOutlet'.
[ng]   Named property ''animation'' of types 'IonRouterOutlet' and 'IonRouterOutlet' are not identical.
[ng] 3048   interface HTMLIonRouterOutletElement extends Components.IonRouterOutlet, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:3048:13 - error TS2320: Interface 'HTMLIonRouterOutletElement' cannot simultaneously extend types 'IonRouterOutlet' and 'IonRouterOutlet'.
[ng]   Named property ''commit'' of types 'IonRouterOutlet' and 'IonRouterOutlet' are not identical.
[ng] 3048   interface HTMLIonRouterOutletElement extends Components.IonRouterOutlet, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:3060:13 - error TS2320: Interface 'HTMLIonSearchbarElement' cannot simultaneously extend types 'IonSearchbar' and 'IonSearchbar'.
[ng]   Named property ''inputmode'' of types 'IonSearchbar' and 'IonSearchbar' are not identical.
[ng] 3060   interface HTMLIonSearchbarElement extends Components.IonSearchbar, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:3060:13 - error TS2320: Interface 'HTMLIonSearchbarElement' cannot simultaneously extend types 'IonSearchbar' and 'IonSearchbar'.
[ng]   Named property ''searchIcon'' of types 'IonSearchbar' and 'IonSearchbar' are not identical.
[ng] 3060   interface HTMLIonSearchbarElement extends Components.IonSearchbar, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:3060:13 - error TS2320: Interface 'HTMLIonSearchbarElement' cannot simultaneously extend types 'IonSearchbar' and 'IonSearchbar'.
[ng]   Named property ''showCancelButton'' of types 'IonSearchbar' and 'IonSearchbar' are not identical.
[ng] 3060   interface HTMLIonSearchbarElement extends Components.IonSearchbar, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:3174:13 - error TS2320: Interface 'HTMLIonToastElement' cannot simultaneously extend types 'IonToast' and 'IonToast'.
[ng]   Named property ''enterAnimation'' of types 'IonToast' and 'IonToast' are not identical.
[ng] 3174   interface HTMLIonToastElement extends Components.IonToast, HTMLStencilElement {}
[ng]                  ~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@ionic/angular/node_modules/@ionic/core/dist/types/components.d.ts:3174:13 - error TS2320: Interface 'HTMLIonToastElement' cannot simultaneously extend types 'IonToast' and 'IonToast'.
[ng]   Named property ''leaveAnimation'' of types 'IonToast' and 'IonToast' are not identical.
[ng] 3174   interface HTMLIonToastElement extends Components.IonToast, HTMLStencilElement {}
`

**Comment by b3008** [comment]
I'm facing a similar issue after running `npm update` on an ionic 4 project.

my package.json is
```
{
  "name": "myProject",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.1.2",
    "@angular/cdk": "^8.2.0",
    "@angular/common": "^8.1.3",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/elements": "^8.2.2",
    "@angular/forms": "~8.1.2",
    "@angular/material": "^8.1.4",
    "@angular/platform-browser": "^8.1.3",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@ibm/plex": "^3.0.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.9.1",
    "@ionic/core": "^4.9.1",
    "@ionic/storage": "^2.2.0",
    "@mdi/font": "^4.1.95",
    "@types/socket.io-client": "^1.4.32",
    "@types/ua-parser-js": "^0.7.33",
    "core-js": "^2.5.4",
    "grapesjs": "^0.15.10",
    "hammerjs": "^2.0.8",
    "ngx-showdown": "^5.0.0",
    "ngx-swiper-wrapper": "^8.0.2",
    "rxjs": "~6.5.1",
    "sanitize-html": "^1.20.1",
    "showdown": "^1.9.0",
    "socket.io-client": "^2.2.0",
    "spinkit": "^1.2.5",
    "tslib": "^1.9.0",
    "ua-parser-js": "^0.7.20",
    "uuid": "^3.3.2",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@ionic/angular-toolkit": "~2.0.0",
    "@types/hammerjs": "^2.0.36",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "@types/showdown": "^1.9.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typedoc": "^0.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project"
}
```
I've tried using both 5.0.0 and 4.11.0 versions of the ionic global cli to run `ionic build`, the error I'm getting is 

```
[ng] ERROR in node_modules/@ionic/core/dist/types/components.d.ts:3190:13 - error TS2320: Interface 'HTMLIonMenuControllerElement' cannot simultaneously extend types 'IonMenuController' and 'IonMenuController'.
[ng]   Named property ''registerAnimation'' of types 'IonMenuController' and 'IonMenuController' are not identical.
[ng] 3190   interface HTMLIonMenuControllerElement extends Components.IonMenuController, HTMLStencilElement {}

```
 
I've tried reinstalling node_modules but have had no luck.
I'd be grateful for any suggestions

**Comment by LifeIsStrange** [comment]
I have the same issue using the defacto standard for creating a ionic vue app https://dev.to/aaronksaunders/build-your-first-ionic-vue-app-18kj

(ps: I'm using typescript)

**Comment by Chris2011** [comment]
Same here, update of ionic/core to 5.0.4, ionic/vue to 0.0.9 didn't fix it.

**Comment by dangerdan** [comment]
@Chris2011 did you manage to resolve this? Same problem here.

**Comment by Chris2011** [comment]
@dangerdan unfortunately not, after I tried to use Vue with Ionic and find my self that I don't like Ionic for the components and there interaction, I removed Ionic completely and use Vue + Vuetify + Cordova.

**Comment by dangerdan** [comment]
Thanks for the reply. I love Ionic with Angular, but finding it unusable with Vue. I'll check out Vuetify too. Thanks.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this an issue with the latest version of Ionic Framework? If so, can you provide a repo with the code required to reproduce the issue?

As for Vue, Ionic Vue is still in early beta, so this is not something we recommend for production apps. We are working on Ionic + Vue 3 integration, so expect more on that soon!
