### ISSUE TITLE
Changing ionic menu color for ios

### ISSUE THREAD

**Issue by lucascrandle** [ionic-team/ionic#20213]
[x] 4.11.5

[x] bug report
[ ] feature request

**Current behavior:**
I run the ionic start command for the side menu starter, and add these lines to the variables.scss file, inside of the :root object:
```
  --ion-toolbar-background: var(--ion-color-primary);
  --ion-toolbar-color: var(--ion-color-light);
```
For android, the ion-menu-button and ion-back-button change to the toolbar color property, but on ios they are still set to primary, making the buttons invisible.

I am arguing this is a bug because of the varied behaviors between ios and android

**Expected behavior:**
I would expect the colors to be the same between ios and android

**Steps to reproduce:**
ionic starter: side menu
Add this to the variables.scss file under :root object:
  --ion-toolbar-background: var(--ion-color-primary);
  --ion-toolbar-color: var(--ion-color-light);
Run in ios and android, they will be different

**Related code:**

**Other information:**

**Ionic info:** 
```
Ionic:

   Ionic CLI                     : 5.4.13 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.8
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.8.1
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/lucas.crandle/Library/Android/sdk)
   ios-deploy        : 2.0.0
   ios-sim           : 8.0.2
   NodeJS            : v12.14.1 (/usr/local/bin/node)
   npm               : 6.13.4
   OS                : macOS Mojave
   Xcode             : Xcode 11.3 Build version 11C29```

**Comment by lucascrandle** [comment]
I was able to find a workaround, documented it on the forum here:
https://forum.ionicframework.com/t/how-to-set-color-of-side-menu-button-hamburger-on-ios/163064/10

**Comment by brandyscarney** [comment]
Thanks for the issue! Are you talking about the buttons disappearing on hover? I can see them on this Codepen but I see them hiding on hover: https://codepen.io/brandyscarney/pen/YzPjoWp

**Comment by lucascrandle** [comment]
Sort of...
This is what I see when I run on ios:
![image](https://user-images.githubusercontent.com/16657988/72459089-006e3280-3798-11ea-9f8c-193fcaacd831.png)
The background color is taking affect and setting the color of the toolbar to the primary color. However, the menu button is not taking on the light color so it disappears. (I can still click on it and it opens the menu)


This is what I see on android with the same code base:
![image](https://user-images.githubusercontent.com/16657988/72460112-301e3a00-379a-11ea-93e9-13b84332979d.png)

It's confusing because android works well, and all of the other header buttons in ios take on the toolbar color, just not the menu or back buttons.

**Comment by lucascrandle** [comment]
Here's an example with buttons added.
ios:
![image](https://user-images.githubusercontent.com/16657988/72461168-6bba0380-379c-11ea-9f64-1f4ec999adb4.png)



Android:
![image](https://user-images.githubusercontent.com/16657988/72460766-72944680-379b-11ea-910a-4d6cf707c2dc.png)

Code for the header in home.page.html:

`
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-menu-button></ion-menu-button>
    </ion-buttons>
    <ion-buttons slot="end">
      <ion-button>
        <ion-icon name="funnel" slot="icon-only"></ion-icon>
      </ion-button>

      <ion-button>
        <ion-icon name="add" slot="icon-only"></ion-icon>
      </ion-button>
    </ion-buttons>
    <ion-title>
      Home
    </ion-title>
  </ion-toolbar>
</ion-header>
`

**Comment by brandyscarney** [comment]
Ahh okay! I can reproduce with Safari & using the `5.0.0-beta.4` release of Ionic. I'm working on some changes for all of this here so I will keep this in mind: https://github.com/ionic-team/ionic/pull/19440

**Comment by lucascrandle** [comment]
Awesome. Thank you for the quick response!

**Comment by brandyscarney** [comment]
So oddly enough I actually found that this may be a problem and put a TODO on my branch :grin: 

https://github.com/ionic-team/ionic/blob/fix-hover-states/core/src/components/menu-button/menu-button.scss#L161

Working on fixing this up but it will be part of that PR I linked 🙂
