### ISSUE TITLE
bug: Types are broken

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic#20221]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

In my app I force myself to put a type to everything. This is not possible with Ionic.

```
async showHelpModal(): Promise<void> {
    const modal = await this._modalController.create({
      component: MyModalComponent
    });

    return modal.present();
}
```

With the code above I would like to type `modal` like so :

```
const modal: Promise<HTMLIonModalElement> = await this._modalController.create({
      component: HelpModalComponent
});
```

But this throws : 

> TS2739: Type 'HTMLIonModalElement' is missing the following properties from type 'Promise<HTMLIonModalElement>': then, catch, [Symbol.toStringTag], finally

This is not a normal behavior.

Same with events, for example `<ion-refresher> (ionRefresh)` event is a CustomEvent :
```
doRefresh(event: CustomEvent): void {
    console.log("Begin async operation");

    setTimeout(() => {
      console.log("Async operation has ended");
      event.target.complete();
    }, 2000);
}
```
Will throw :

> TS2339: Property 'complete' does not exist on type 'EventTarget'

So you end up with `Any` everywhere and it takes away all the point of Typescript ...

**Expected behavior:**
There should be types for every ionic components

**Comment by elylucas** [comment]
Hi, in your modal controller sample, you are awaiting the call to modalController.create, so it Doesn't return a Promise<HTMLIonModalElement>, it just returns HTMLIonModalElement. You don't need to specify the type as the type inference will type the modal property properly.

For the doRefresh method, CustomEvent takes a generic argument, and if you pass in RefresherEventDetail (imported from @ionic/core), you can have a typed detail object off the event, which has that same complete method the target does: event.detail.complete();

Let me know if this makes sense. Going to close for now as there doesn't seem to be a bug.

**Comment by Yohandah** [comment]
@elylucas Ohhh OK thanks a lot, my mistake.

I didn't managed to make it work for the doRefresh method tho .. am I doing it right ?

```
import { RefresherEventDetail } from "@ionic/core";
...
...
...
doRefresh(event: CustomEvent<RefresherEventDetail>): void {
    console.log("Begin async operation");

    setTimeout(async () => {
      console.log("Async operation has ended");
      event.target.complete();
}
```

This throws the same error .complete does not exists.

I still wonder why my IDE (IntelliJ) doesn't tell me which precise type it is but once you know it's fine, (maybe we should add types to the doc ?) 
![image](https://user-images.githubusercontent.com/15921402/72628095-f1c97c00-394d-11ea-878b-9780374bc05f.png)

**Comment by elylucas** [comment]
@Yohandah 

The generic types the detail prop on event, so change your call to complete to `event.detail.complete()` and that should fix it.

Not sure about surfacing the types in IntelliJ.

Thanks for the suggestion on adding the types to the docs. We are discussing how to do this better internally.
