### ISSUE TITLE
Open a 2nd Modal and then close the 1st modal

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic#20239]
Hi,

 `@ionic/angular": "4.11.5"`

I have a series of Modal items. All are working fine. But the only issue here is how to close the current modal after 2nd modal has been opened.

I have tried this. But then it never opens the 2nd Modal.

This is within the 1st Modal

```
async next(): Promise<void> { // try to open 2nd Modal and after that close the 1st Modal

  await this.showSeeAgainModal();
  this.cancel();

  }

  cancel(): void {
    this.modalController.dismiss();
  }



async showSeeAgainModal(): Promise<void> { // This is the 2nd Modal
    const modal: HTMLIonModalElement = await this.modalController.create({
      component: SeeAgainPage,
    });

    modal.onDidDismiss().then(async (res) => {
    });

    return await modal.present();
  }
```
I can use simply like so:

But the problem here is it closes the 1st Modal before open the 2nd one. It gives bad UX.

```
next(): Promise<void> { // this is working fine. But bad UX

      this.showSeeAgainModal();
      this.cancel();

      }
```

**Comment by indraraj26** [comment]
This would be great if ionic team can implement this which will hide first modal behind the scene.

**Comment by root14** [comment]
Hi,

Solution 1: You could extend the modalController and save in a property the modal object in the present callback. Then check if there is a modal to dismiss before saving the new modal object. 

Solution 2: You could use router-outlet in a modal component to navigate throught different component without create a new modal at every step.

**Comment by NikolaPeevski** [comment]
@Sampath-Lokuge Can you give more information on your case ? What is the series of Modal items ?

**Comment by TheLazyHatGuy** [comment]
I think this is a similar problem to this one - https://github.com/ionic-team/ionic/issues/20610#issuecomment-598100879

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by Sampath-Lokuge** [comment]
After I have talked to my client I changed it to a series of pages. i.e. not using series fo Modals. So now I don't need this feature. Thanks @liamdebeasi
