### ISSUE TITLE
bug: statusBar.styleDefault() not working on iOS 13

### ISSUE THREAD

**Issue by Badyl1g** [ionic-team/ionic#20235]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When running the app on iOS 13 devices (tested on iPhone 11 Pro and iPhone SE) with `statusBar.styleDefault()` the status bar has white text color.

![IMG_1421](https://user-images.githubusercontent.com/27491471/72664445-488e8e80-39fe-11ea-9222-28dbdea121f8.jpg)

**Note:** It works well on simulators and devices with iOS <= 12

**Expected behavior:**
When settings StatusBar style to default text should be dark (for apps with light background)

**Steps to reproduce:**
1. Create new app via Ionic CLI: `ionic start ionic-test sidemenu`

**Related code:**
![image](https://user-images.githubusercontent.com/27491471/72664399-ae2e4b00-39fd-11ea-9eb9-10173e33c1a3.png)

**Other information:**

**Ionic info:**

```
iIonic:

   Ionic CLI                     : 5.4.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.8
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:

   cordova-res : 0.8.1 
   native-run  : 0.2.9 (update available: 0.3.0)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.15.3 (/usr/local/bin/node)
   npm        : 6.13.1
   OS         : macOS Mojave
   Xcode      : Xcode 11.3.1 Build version 11C504
```

**Comment by Badyl1g** [comment]
I found a workaround in a similar issue (https://github.com/apache/cordova-plugin-statusbar/issues/148). You can force dark text on status bar by adding following code to `config.xml`:

![image](https://user-images.githubusercontent.com/27491471/72729591-c59d3d80-3b8f-11ea-8464-787a655043cb.png)

Since the starter ionic app doesn't have a dark mode by default current behavior is very confusing.
Could you fix that or at least add a note in the docs?

**Comment by liamdebeasi** [comment]
Thanks for the issue. We will be updating the starters with dark mode support for Ionic Framework v5, which should address this issue.
