### ISSUE TITLE
feat: Use TypeScript 3.7 on Ionic 5

### ISSUE THREAD

**Issue by Majirefy** [ionic-team/ionic#20240]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
As Ionic 5 will come with Angular 9, can we use TypeScript 3.7?

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is all taken care of. The dependency for TypeScript within Ionic lies with Stencil (which is already updated). We will just need to update the starters with the proper TypeScript version once Ionic 5 launches.
