### ISSUE TITLE
Scrollbar on iOS sometimes dissapears

### ISSUE THREAD

**Issue by molinator84** [ionic-team/ionic#20245]
**Ionic version:**

[x] **4.x**

**I'm submitting a ...** 

[ x] bug report
[ ] feature request

**Current behavior:**

On IOS(13.3) sometimes scrollbar disappears(not rendered). It happens just sometimes in the pages, not always, that is, in the same page sometimes the scrollbar is rednered and sometimes not. I'm using the ionic-tabs to navigate between pages.

**Expected behavior:**

The scrollbar should be visible (or not) always, but not sometimes.
**Steps to reproduce:**

Create several pages (4-5) with an ionic-tabs component and try to navigate between them in a real IPhone (I'have a Iphone 6 for example)
**Related code:**

**Other information:**

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 5.4.13
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.803.21
   @angular-devkit/schematics    : 8.3.21
   @angular/cli                  : 8.3.21
   @ionic/angular-toolkit        : 2.1.1

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.4.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 21 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3 (C:\Users\santiago.gallego\AppData\Roaming\nvm\v10.14.2\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by EmersonBC** [comment]
I'm facing the same problem. In my case the scroll never appear and I am not able to do the scroll on the ion-list. 

I have a component with ion-list inside a ion-slides

Is important to say that this only happen in the IOS 13, if I run on the IOS 12 the scroll works perfectly.
