### ISSUE TITLE
bug: ion-backdrop opacity is hardcoded

### ISSUE THREAD

**Issue by ochikov** [ionic-team/ionic#20242]
# Bug Report

**Ionic version:**
```
 Ionic CLI                     : 5.4.13 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0
```

**Current behavior:**
Could not set ion-backdrop opacity. It is hardcoded and get from the host, where it is `0.3` globally.

![Screenshot 2020-01-20 at 13 44 14](https://user-images.githubusercontent.com/13587218/72724056-f8910280-3b8a-11ea-9e70-7d14921f0297.png)

**Expected behavior:**
Being able to set ion-backdrop background opacity

**Comment by liamdebeasi** [comment]
Thanks for the issue. This feature has already been added and will be available in an upcoming release of Ionic Framework.
