### ISSUE TITLE
bug: Angular change detection doesn't work

### ISSUE THREAD

**Issue by JeongJun-Lee** [ionic-team/ionic#20247]
# Bug Report

**Ionic version:**

[x] **4.11.8**

**Current behavior:**

The value which is added into array by alert controller is not shown.

**Expected behavior:**

The value which is added into array by alert controller should be shown normally.

**Steps to reproduce:**

https://stackblitz.com/edit/ionic-4-angular-8-start-template-l5as1d?file=src%2Fapp%2Ftab2%2Ftab2.page.ts

1. At preview, press tab2 
2. Press fab-button at the bottom
3. Press OK at alert dialog
4. The item in the list should be shown normally, but there is no changes

**Related code:**

https://stackblitz.com/edit/ionic-4-angular-8-start-template-l5as1d?file=src%2Fapp%2Ftab2%2Ftab2.page.ts

**Other information:**

**Comment by JeongJun-Lee** [comment]
Sorry, maybe it was from stackblitz itself. I’ll close this issue.

![image](https://user-images.githubusercontent.com/11474775/72785258-a1ebfd00-3c4c-11ea-94fb-52f8a9e5fc5a.png)

**Comment by yasser-kfupm** [comment]
change detection is not working with me on Hawaii devices, it is very strange. What is the reason?
