### ISSUE TITLE
Use ion-datetime selectors  without the popup

### ISSUE THREAD

**Issue by arpytoth** [ionic-team/ionic#20241]
Hi,
I don't know if this is the right place to ask questions but can we use the ion-datetime selector components without the popup? Just put them into a div or in ion content directly?

EDIT: Basically what I want to do is use ion-picker-column in a div directly.. not in popup.

Thanks,

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19642.
