### ISSUE TITLE
bug: ionic cordova build browser --aot Js file not minified, sizes too high

### ISSUE THREAD

**Issue by ilprima** [ionic-team/ionic#20248]
I build my mobile website using this command:
ionic cordova build browser --aot --prod --minifyjs --minifycss --release

But chrome says Angular js files are not minified and to check if the production version is active.
I'm using also lazy loading but the js files seems too heavy.
How can I optimise them? Is the --prod bugged?
Thank you.
![image](https://user-images.githubusercontent.com/18414951/72747080-f8592d00-3bb3-11ea-93a4-b4714ed5a4f4.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is more of a support request. For building your Ionic 4+ application for a web browser, we recommend using `ionic build --prod`.
