### ISSUE TITLE
Ionic 5:  Card-Style Modal behavior on iPad

### ISSUE THREAD

**Issue by mariusbolik** [ionic-team/ionic#20255]
# Bug Report

**Ionic version:**

[x] **5 Beta 5**

**Current behavior:**

First of all a big thanks to the whole Ionic Team for it's awesome Work! I really appreciate it!
I know, Ionic 5 is just in Beta, but it would very nice if the Card-Style Modal gets adjusted to the iPad Screen Size. Also there's a problem with tabs:
<img src="https://i.imgur.com/HbxgJh3.jpg" width="500px">

**Expected behavior:**

Here is a really interesting blog post regarding Modals on iPad: https://medium.com/@hacknicity/view-controller-presentation-changes-in-ios-13-ac8c901ebc4e

**Steps to reproduce:**

Just create a new Ionic 5 Project and implement the Modal like in the Code Snippet below.

**Related code:**

```
  async showModal() {
    const myModal = await this.modalController.create({
      component: MyModalComponent,
      swipeToClose: true,
      presentingElement: this.routerOutlet.nativeEl
    });
    return await myModal.present();
  }
```

**Ionic info:**

```
Ionic:

   Ionic CLI : 5.4.15

Utility:

   cordova-res : 0.8.1
   native-run  : 0.3.0

System:

   NodeJS : v10.16.3
   npm    : 6.13.4
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for testing out the betas! It looks like the card-style modals on iPad just need to take up 100% of the screen width in order to be compliant with the iOS spec. I will add a fix for this. (I will also look at that tabs issue).

**Comment by liamdebeasi** [comment]
Thanks for the issue. This issue has been fixed via https://github.com/ionic-team/ionic/pull/20256 and will be available in an upcoming release of Ionic Framework.

I have created a dev build if you would like to try the fix out now:

`npm i @ionic/angular@5.0.0-dev.202001211942.8d4dc58`

For the tabs issue you mentioned you should get the root router outlet using `this.routerOutlet.parentOutlet.nativeEl` instead. This was not mentioned in the docs, so I have updated it there as well.
