### ISSUE TITLE
bug: slot="fixed" was not required by ion-refresher, recently

### ISSUE THREAD

**Issue by buko106** [ionic-team/ionic#20269]
# Bug Report

**Ionic version:**

[x] **4.11.8**

**Current behavior:**

We upgraded `@ionic/angular` from 4.4 to 4.11.

According to documentation, ion-refresher must be used with `slot="fixed"`. However, it was not necessary in v4.4 to specify a slot explicitly because slot was set to fixed by [using hostData()](https://github.com/ionic-team/ionic/blob/9030dcc111cc6486d22b45852a9906d18fa51f0c/core/src/components/refresher/refresher.tsx#L364). In v4.11,  `slot="fixed"` must be manually specified.

We have trouble in debugging because `slot="fixed"` is set [using Host tag](https://github.com/ionic-team/ionic/blob/48a27636c76c1a05dc6d878be26cbe028552cbf7/core/src/components/refresher/refresher.tsx#L360) but [connectedCallback() shows this error](https://github.com/ionic-team/ionic/blob/48a27636c76c1a05dc6d878be26cbe028552cbf7/core/src/components/refresher/refresher.tsx#L102). I think this is a timing issue.

**Expected behavior:**

Stop setting `slot="fixed"` using Host tag, or make ion-refresher to work without `slot="fixed"`

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide some clarification on what the issue you are running into is? `ion-refresher` has required that developers set `slot="fixed"` on `ion-refresher` since Ionic Framework 4.0.0.
