### ISSUE TITLE
bug: "Disabled" property binding on <ion-item> not working for iOS.

### ISSUE THREAD

**Issue by rbrand21** [ionic-team/ionic#20260]
# Bug Report

**Ionic version:**

[x] **4.11.7**

**Current behavior:**

When using disabled property binding for ion-item: 
`<ion-item button (click)="listItemClicked(day)" [disabled]="!!completedWorkouts[day.id]">`
The ion-item is properly disabled (it is no longer clickable, changes the opacity, etc...) when debugging in Chrome. However, in the iOS simulator (and on an actual phone), the view is not properly being updated based on the "completedWorkouts" objects being set. It's as if the updating of "this.completedWorkout" is not causing the template to detect changes or re-render (I don't fully understand how this works as it is).  However, I notice that after about 15 seconds the page has some sort of re-render of the template where it picks up that this item has had the disabled property set and properly renders it as disabled.

I also tried a simpler property binding where completedWorkouts was just a simple boolean value instead of an object - I got the exact same, behavior on both iOS and web (meaning it worked fine on web, still didn't work on iOS)

**Expected behavior:**

Property binding in a template for ion-item should work in iOS the same as it does for web.

**Steps to reproduce:**

Specifically within iOS: Dynamically set the "disabled" property of an ion-item based on a variable inside the component's typescript. Notice that the item is not disabled when the attribute is set to true (or until about 15 seconds later).

**Related code:**

The entire template:
```
<ion-list lines="full">
  <ng-container *ngFor="let day of workoutDays" >
    <ion-list-header *ngIf="day.phase_day == 1">
      {{day.phase_name}}
    </ion-list-header>
    <ion-item button id="dayItem{{day.day_number}}" (click)="listItemClicked(day)" [disabled]="!!completedWorkouts[day.id]">
      <span slot="start">{{day.day_number}}.</span>
      <ion-label>
        <h2>
          Day {{day.phase_day}}
        </h2>
        <h3>
          <img src="../../../assets/clock.svg">
          {{day.time_to_complete}}
        </h3>
      </ion-label>
    </ion-item>
  </ng-container>
</ion-list>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.13
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 8 other plugins)

Utility:

   cordova-res : 0.8.1
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/robertbrand/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v13.2.0 (/Users/robertbrand/.nvm/versions/node/v13.2.0/bin/node)
   npm               : 6.13.6
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am unable to reproduce the issue using the code provided.

**Comment by rbrand21** [comment]
Having a difficult time reproducing this in a separate repo as well. I also managed to "fix" it in my main repo.
I had code on a separate page which controls the disabled flag of the main page by means of Firestore. I had an await call on the firestore update before navigating back to the page which would display the disabled list. I removed the await on that call and it started working as intended. I thought there was something going on with the page/component lifecycle not responding to subscription updates when the page is not active, but after testing that in a separate repo, I can't get that to reproduce the issue either.

This is what my code changed from/to in the separate page:
From: 
```
    async completeWorkout() {
        console.log('Completing workout for programId: ' + this.programId + ' the day being completed is: ' + this.data.id);
        const uid = await this.auth.uid();
        await this.db.updateAt(
            `user_progress/${uid}/completed_days/${this.programId}`,
            {[this.data.id]: true}
        );

        // Navigate back on the stack to get back to the programming page
        this.navController.back();
    }
```
To:
```    
async completeWorkout() {
        console.log('Completing workout for programId: ' + this.programId + ' the day being completed is: ' + this.data.id);
        const uid = await this.auth.uid();

        this.db.updateAt(
            `user_progress/${uid}/completed_days/${this.programId}`,
            {[this.data.id]: true}
        );

        // Navigate back on the stack to get back to the programming page
        this.navController.back();
    }
```

**Comment by rbrand21** [comment]
I will continue to try and reproduce the issue in the separate repo. Will add in firestore to replicate the same scenario as opposed to just using an RxJS observable. Can change the label back to needs reply :)
