### ISSUE TITLE
when keyboard is shown a gray empty box appear at the top of the keyboar in ios with ion-searchbar

### ISSUE THREAD

**Issue by monavarian** [ionic-team/ionic#20270]
As you can see in the two picture attached here an empty gray box appear upper the keyboard.
I think this issue is only appear when using ion-split-pane. 
And also in **android** phones it is fine. But only this is happen in **ios**.
I have searched a lot without any result so I thought it might be an issue . So please  help me if I did something wrong.
Thanks

![8d147d36-4a36-475f-9e71-4c1b54cbba58](https://user-images.githubusercontent.com/37533716/72962325-501cb180-3dc9-11ea-9d91-062aac2a4af8.jpg)
![d87c8099-b923-47ec-bf4f-47490feabe6a](https://user-images.githubusercontent.com/37533716/72962327-50b54800-3dc9-11ea-84b7-5466b3b7b7d9.jpg)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?
