### ISSUE TITLE
bug: ion-datetime appears below modal when using Javascript only.

### ISSUE THREAD

**Issue by Bandito11** [ionic-team/ionic#20280]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

In the Javascript platform when using ionic 4 (no Angular, React or Vue) when I call an ion-modal I cannot use an ion-datetime inside that modal because the modal will be front of the screen and the ion-datetime below. WHen you try the modal you will see nothing but when closing the modal you will see the modal there.
**Expected behavior:**

I should see the datetime on top of the modal (it does on Angular. I am trying to not use frameworks and I am remaking my app on Stencil)
**Steps to reproduce:**

**Related code:**
```
```
//This is how I open the modal
    function openEventCreateModal(): void {
        const modalElement = document.createElement('ion-modal');
        modalElement.component = 'app-event-create';
        modalElement.componentProps = {
            header: 'Create Event'
        };
        document.body.appendChild(modalElement);
        modalElement.present();
    }
```
//This snippet is on the modal. I think the z-index of the ion-datetime is the same one as the modal when I press the ion-datetime on the browser.
<ion-item>
    <ion-label position="fixed">{this.htmlControls.date}:</ion-label>
    <ion-datetime display-format="MM/DD/YYYY" value={this.date.toString()} onIonChange={ev => this.date = new Date(ev.detail.value)}></ion-datetime>
    </ion-item>
```

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by niqiukun** [comment]
The overlay element is appended inside `ion-app` instead of the document body, while modals are appended directly inside the document body. Since modals have higher `z-index` than `ion-app`, many components, including alerts, pickers, actionsheets, etc, will be hidden by the modal.

**Comment by Bandito11** [comment]
I see, thanks.

Yesterday I was updating to ionic 5 and this issue was fixed.

Marking it as complete.
