### ISSUE TITLE
5.0.0-rc.0: ion-content height 100% not inherited 

### ISSUE THREAD

**Issue by LOUNNAS** [ionic-team/ionic#20305]
Ionic version:
[x] 5.0.0-rc.0

Current behavior:
In Ionic 5.0.0-rc.0 it is no longer possible to assign a height: 100% to the split element of the ion-content property, respectively, this property will be ignored.

Expected behaviour:
Still able to use height: 100% for content with Ionic 5.0.0-rc.0.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a code example of what you are trying to do?

**Comment by LOUNNAS** [comment]
thank you for your reply.

I try : 

<ion-content>
    <ion-grid style="height: 100%">
    </ion-grid >
</ion-content>

and

<ion-content>
    <ion-grid style="min-height: 100%">
    </ion-grid >
</ion-content>

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you give the following dev build a try and let me know if it resolves your issue: `5.0.0-dev.202001271550.1c2d648`

**Comment by LOUNNAS** [comment]
It works as expected, thanks for your help.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20309 and will be available in an upcoming release of Ionic Framework.

**Comment by paulstelzer** [comment]
Thanks! Had the same issue with rc.0 and now it's working like before. good job!
