### ISSUE TITLE
bug: Ionic 4: Ionicons not shown on Android 5.0 or 5.1

### ISSUE THREAD

**Issue by SSuarezBrooktec** [ionic-team/ionic#20304]
# Bug Report

**Ionic version:**

[x] **4.x**

**Related code:**

 ```  
<ion-icon (click)="goBack()" name="ios-arrow-back"></ion-icon>
```

**Other information:**

**Ionic info:**

```
 Android SDK Tools : 26.1.1 (/Users/sergio/Library/Android/sdk)
   NodeJS            : v13.0.1 (/Users/user/.nvm/versions/node/v13.0.1/bin/node)
   npm               : 6.13.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

Here package.json

```
  "dependencies": {
    "@angular/common": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@capacitor/android": "^1.4.0",
    "@capacitor/core": "1.4.0",
    "@capacitor/ios": "^1.4.0",
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.26",
    "@fortawesome/free-solid-svg-icons": "^5.12.0",
    "@ionic-native/core": "^5.20.0",
    "@ionic-native/fingerprint-aio": "^5.20.0",
    "@ionic-native/http": "^5.20.0",
    "@ionic-native/keyboard": "^5.20.0",
    "@ionic-native/screen-orientation": "^5.20.0",
    "@ionic/angular": "^4.11.10",
    "@ng-idle/core": "^8.0.0-beta.4",
    "@ng-idle/keepalive": "^8.0.0-beta.4",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@types/jwt-decode": "^2.2.1",
    "angular-highcharts": "^8.0.3",
    "capacitor-fcm": "^1.0.0",
    "capacitor-secure-storage-plugin": "^0.3.0",
    "classlist.js": "^1.1.20150312",
    "cordova-plugin-advanced-http": "^2.4.0",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-fingerprint-aio": "^3.0.1",
    "cordova-plugin-screen-orientation": "^3.0.2",
    "core-js": "2.5.7",
    "es6-promise-plugin": "^4.2.2",
    "highcharts": "^7.2.1",
    "i18n-iso-countries": "^4.3.1",
    "jwt-decode": "^2.2.0",
    "ng2-fittext": "^1.2.8",
    "ngx-currency": "^2.2.2",
    "rxjs": "~6.5.4",
    "rxjs-compat": "^6.5.4",
    "tslib": "^1.10.0",
    "validator": "^12.1.0",
    "web-animations-js": "^2.3.2",
    "whatwg-fetch": "^3.0.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.803.23",
    "@angular-devkit/build-angular": "^0.803.23",
    "@angular-devkit/core": "^8.3.23",
    "@angular-devkit/schematics": "^8.3.23",
    "@angular/cli": "^8.3.23",
    "@angular/compiler": "~8.2.14",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@capacitor/cli": "1.4.0",
    "@ionic/angular-toolkit": "^2.1.2",
    "@types/big.js": "^4.0.5",
    "@types/jasmine": "~3.4.6",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "~8.10.59",
    "codelyzer": "^5.2.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.1",
    "protractor": "~5.4.2",
    "ts-node": "~7.0.1",
    "tslint": "~5.20.1",
    "typescript": "~3.5.3"
  }
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Which Android device(s) are you testing this on?

**Comment by SSuarezBrooktec** [comment]
We are trying with both:

- Android Studio 5.1 Emulator 
- Physical device: Huawei P8 Lite with Android 5.0.1 (2015)

**Comment by SSuarezBrooktec** [comment]
After many hours of testing I found the error

When i use the command ionic cap sync android
the cli install this dependency
 **[info] installing missing dependency plugin cordova-plugin-file**

After install this plugin, ionicons do not work on Android
How is possible? Is this plugin really necessary on Android?

**Comment by SSuarezBrooktec** [comment]
This plugin: cordova-plugin-file

Is a requirement of: 
cordova-plugin-advanced-http (2.4.0)

Would be possible?

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Do Ionicons show up properly if you do not have either of those plugins installed?

**Comment by SSuarezBrooktec** [comment]
If i **remove cordova-plugin-file** and after run **ionic cap run android** (works properly)

But the problem is when in android i execute this command: ionic cap update android
cli say this: **[info] installing missing dependency plugin cordova-plugin-file**
and the app is broken again

**Comment by liamdebeasi** [comment]
Do you also have `cordova-plugin-advanced-http` installed?

**Comment by SSuarezBrooktec** [comment]
Yes i have installed it

**Comment by liamdebeasi** [comment]
Ok it sounds like the plugin may be interfering with loading Ionicons. Can you provide a reproduction of the issue? A blank Ionic starter app with ionicons + these plugins installed would work fine.

**Comment by SSuarezBrooktec** [comment]
Yes, with blank project works fine. When i install ionic native http fails
https://ionicframework.com/docs/native/http

Should I open an issue in the original cordova plugin? Or could it be seen from the ionic core?

**Comment by liamdebeasi** [comment]
A code reproduction would be really helpful here. It sounds like having the plugins installed causes the issue, but maybe there's something we can do from our end to address this. Can you provide a GitHub repo with a reproduction?

**Comment by SSuarezBrooktec** [comment]
Here 2 screenshots, (working and error)

<img width="334" alt="Captura de pantalla 2020-01-28 a las 23 39 48" src="https://user-images.githubusercontent.com/56263935/73312225-81154000-4228-11ea-9f74-44221ca0b1cb.png">
<img width="348" alt="Captura de pantalla 2020-01-28 a las 23 08 44" src="https://user-images.githubusercontent.com/56263935/73312227-82466d00-4228-11ea-8073-25277a50ebd2.png">

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I took a look at the repo and was able to reproduce this behavior.

This looks to be an issue with a combination of the installed plugins and older Chrome webview versions. I would recommend opening an issue with the plugin author. Thanks!
