### ISSUE TITLE
bug: [@ionic/react]  align-items & justify-content props not working

### ISSUE THREAD

**Issue by cdes** [ionic-team/ionic#20302]
# Bug Report

**Ionic version:**

- [x] **^5.0.0-rc.0**

**Current behavior:**

Using the props align-items & justify-content does not have any effect neither on `IonCol` nor `IonRow`.

Ignored props:
- justify-content-start
- justify-content-center
- justify-content-end
- justify-content-around
- justify-content-between
- align-items-start
- align-items-center
- align-items-end
- align-items-stretch
- align-items-baseline

**Expected behavior:**

It should align them properly using css

**Steps to reproduce:**

Just copied the react example in https://ionicframework.com/docs/api/grid
Here's a sandbox:
https://codesandbox.io/s/ionic-react-issue-align-items-justify-content-props-not-working-4rrse

**Related code:**

```
import React from 'react';
import { IonGrid, IonRow, IonCol, IonContent } from '@ionic/react';

export const GridExample: React.FC = () => (
  <IonContent>
    <IonGrid>
      <IonRow>
        <IonCol>ion-col</IonCol>
        <IonCol>ion-col</IonCol>
        <IonCol>ion-col</IonCol>
        <IonCol>ion-col</IonCol>
      </IonRow>

      <IonRow>
        <IonCol size="6">ion-col size="6"</IonCol>
        <IonCol>ion-col</IonCol>
        <IonCol>ion-col</IonCol>
      </IonRow>

      <IonRow>
        <IonCol size="3">ion-col size="3"</IonCol>
        <IonCol>ion-col</IonCol>
        <IonCol size="3">ion-col size="3"</IonCol>
      </IonRow>

      <IonRow>
        <IonCol size="3">ion-col size="3"</IonCol>
        <IonCol size="3" offset="3">
          ion-col size="3" offset="3"
        </IonCol>
      </IonRow>

      <IonRow>
        <IonCol>ion-col</IonCol>
        <IonCol>
          ion-col
          <br />#
        </IonCol>
        <IonCol>
          ion-col
          <br />#
          <br />#
        </IonCol>
        <IonCol>
          ion-col
          <br />#
          <br />#
          <br />#
        </IonCol>
      </IonRow>

      <IonRow>
        <IonCol align-self-start>ion-col start</IonCol>
        <IonCol align-self-center>ion-col center</IonCol>
        <IonCol align-self-end>ion-col end</IonCol>
        <IonCol>
          ion-col
          <br />#
          <br />#
        </IonCol>
      </IonRow>

      <IonRow align-items-start>
        <IonCol>start ion-col</IonCol>
        <IonCol>start ion-col</IonCol>
        <IonCol align-self-end>start ion-col end</IonCol>
        <IonCol>
          ion-col
          <br />#
          <br />#
        </IonCol>
      </IonRow>

      <IonRow align-items-center>
        <IonCol>center ion-col</IonCol>
        <IonCol>center ion-col</IonCol>
        <IonCol>center ion-col</IonCol>
        <IonCol>
          ion-col
          <br />#
          <br />#
        </IonCol>
      </IonRow>

      <IonRow align-items-end>
        <IonCol>end ion-col</IonCol>
        <IonCol align-self-start>end ion-col start</IonCol>
        <IonCol>end ion-col</IonCol>
        <IonCol>
          ion-col
          <br />#
          <br />#
        </IonCol>
      </IonRow>

      <IonRow>
        <IonCol size="12" size-sm>
          ion-col size="12" size-sm
        </IonCol>
        <IonCol size="12" size-sm>
          ion-col size="12" size-sm
        </IonCol>
        <IonCol size="12" size-sm>
          ion-col size="12" size-sm
        </IonCol>
        <IonCol size="12" size-sm>
          ion-col size="12" size-sm
        </IonCol>
      </IonRow>

      <IonRow>
        <IonCol size="12" size-md>
          ion-col size="12" size-md
        </IonCol>
        <IonCol size="12" size-md>
          ion-col size="12" size-md
        </IonCol>
        <IonCol size="12" size-md>
          ion-col size="12" size-md
        </IonCol>
        <IonCol size="12" size-md>
          ion-col size="12" size-md
        </IonCol>
      </IonRow>

      <IonRow>
        <IonCol size="6" size-lg offset="3">
          ion-col size="6" size-lg offset="3"
        </IonCol>
        <IonCol size="3" size-lg>
          ion-col size="3" size-lg
        </IonCol>
      </IonRow>
    </IonGrid>
  </IonContent>
);
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. We recommend developers use CSS utility classes rather than the properties. The properties have been deprecated and will be removed in the next major version of Ionic Framework.

In the case of your app, you would remove props like `align-items-center` and add them back as classes such as `ion-align-items-center`.

More information on CSS utilities: https://ionicframework.com/docs/layout/css-utilities

Can you try that and let me know if it resolves your issue?

**Comment by brandyscarney** [comment]
Created a PR to update the usage documentation for this: https://github.com/ionic-team/ionic/pull/20312

**Comment by cdes** [comment]
> Thanks for the issue. We recommend developers use CSS utility classes rather than the properties. The properties have been deprecated and are removed in Ionic 5.
> 
> In the case of your app, you would remove props like `align-items-center` and add them back as classes such as `ion-align-items-center`.
> 
> More information on CSS utilities: https://ionicframework.com/docs/layout/css-utilities and https://github.com/ionic-team/ionic/blob/master/BREAKING.md#css
> 
> Can you try that and let me know if it resolves your issue?

Thanks! This works like a charm 🔥


> Created a PR to update the usage documentation for this: #20312

Thanks for updating the docs 🎉
