### ISSUE TITLE
bug: ion-segment-button disabled still clickable

### ISSUE THREAD

**Issue by Arturokin12** [ionic-team/ionic#20319]
# Bug Report

**Ionic version:**
Ionic CLI                     : 5.4.13 
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.2

**Current behavior:**
I created an ion-segment with 3 ion-segment buttons, with conditions when these have to be disabled, and they do, visually, but i can still click these buttons beign disabled.

**Expected behavior:**
ion-segment-button's should not be able to be clicked and trigger the change event

**Steps to reproduce:**
Just use a an ion-segment like bellow

**Related code:**

`<ion-segment mode="ios">
         <ion-row class="ion-no-padding">
            <ion-col size="4" class="ion-no-padding">
              <ion-segment-button [disabled]="true">
                <ion-label>Cuota 1</ion-label>
              </ion-segment-button>
            </ion-col>
            <ion-col size="4" class="ion-no-padding">
              <ion-segment-button [disabled]="true">
                <ion-label>Cuota 2</ion-label>
              </ion-segment-button>
            </ion-col>
            <ion-col size="4" class="ion-no-padding">
              <ion-segment-button [disabled]="true">
                <ion-label>Total&nbsp;</ion-label>
              </ion-segment-button>
            </ion-col>
          </ion-row>
        </ion-segment>`

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this issue has already been fixed and will be available in an upcoming release of Ionic Framework.
