### ISSUE TITLE
bug: IE11 ion-header

### ISSUE THREAD

**Issue by BorntraegerMarc** [ionic-team/ionic#20328]
# Bug Report

**Ionic version:**

[x] **4.7.1**

**Current behavior:**

The title in `<ion-header>`is too far up as compared to chrome. IE11:
<img width="1792" alt="Screenshot 2020-01-29 at 17 08 05" src="https://user-images.githubusercontent.com/7549295/73374083-ed8c4f80-42b9-11ea-93e5-a519ac327320.png">

Chrome:
<img width="1792" alt="Screenshot 2020-01-29 at 17 09 22" src="https://user-images.githubusercontent.com/7549295/73374194-1ad8fd80-42ba-11ea-9d58-a9f7adf80bac.png">

**Expected behavior:**

That IE11 looks the same as chrome

**Steps to reproduce:**

Generate a new `tabs` project with `ionic start`. Make a production build and run the app on IE11.

**Related code:**

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.15 (/Users/borntraegermarc/.nvm/versions/node/v12.13.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.13.0 (/Users/borntraegermarc/.nvm/versions/node/v12.13.0/bin/node)
   npm    : 6.13.6
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as we recently released Ionic Framework v5 which dropped support for IE11 and older versions of Edge. Moving forward, Ionic Framework v4 will only receive critical security patches.
