### ISSUE TITLE
bug:  Ionic 5 rc.1, Angular 9 rc.11 - An unhandled exception occurred: error TS5058: The specified path does not exist

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic#20336]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

```
C:\ae\ae-a9i5-side-tabs>npm test

> ae-a9i5-side-tabs@0.5.1 test C:\ae\ae-a9i5-side-tabs
> ng test

An unhandled exception occurred: error TS5058: The specified path does not exist: 'C:/ae/tsconfig.json'.

See "C:\Users\PETERE~1\AppData\Local\Temp\ng-izBywS\angular-errors.log" for further details.
npm ERR! Test failed.  See above for more details.

C:\ae\ae-a9i5-side-tabs>
```

I am running in the project folder but the error is referring to tcsonfig
in the parent folder.

The errors log file is:

```
[error] Error: [91merror[0m[90m TS5058: [0mThe specified path does not exist: 'C:/ae/tsconfig.json'.

    at Object.readTsconfig (C:\ae\ae-a9i5-side-tabs\node_modules\@angular-devkit\build-angular\src\angular-cli-files\utilities\read-tsconfig.js:27:15)
    at generateWebpackConfig (C:\ae\ae-a9i5-side-tabs\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:29:38)
    at Object.generateBrowserWebpackConfigFromContext (C:\ae\ae-a9i5-side-tabs\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Expected behavior:**

Test works.

**Steps to reproduce:**

The app works but test does not.

Also Angular error for undefined property null.

![Capture261](https://user-images.githubusercontent.com/140737/73412557-d18aad00-42bd-11ea-915e-03259bc74524.png)

![Capture262](https://user-images.githubusercontent.com/140737/73412566-d8192480-42bd-11ea-92ae-02e6e03004b1.png)

**Related code:**

Repo: https://github.com/adaept/ae-a9i5-side-tabs

**Other information:**

**Ionic info:**

```
C:\ae\ae-a9i5-side-tabs>ionic info

Ionic:

   Ionic CLI                     : 5.2.5 (C:\Users\peterennis\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.0.0-rc.1
   @angular-devkit/build-angular : 0.900.0-rc.11
   @angular-devkit/schematics    : 9.0.0-rc.11
   @angular/cli                  : 9.0.0-rc.11
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10


C:\ae\ae-a9i5-side-tabs>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Looks like there are two different errors you are seeing in this issue.

1. For the `The specified path does not exist` error, I am not able to reproduce that issue. It looks like there may be a project misconfiguration on your local machine. Can you reproduce this in a blank Ionic starter app?

2. For the  `innerHTML` error, it looks like that error is coming from within one of your own components and not from Ionic Framework. It seems to be trying to set the innerHTML of `document.getElementById("containerPara")` which does not exist.

**Comment by peterennis** [comment]
@liamdebeasi 
1. I will check with a blank project. Does it need Ionic 5 installed globally?
2. Thanks for the pointer. I will debug it.

**Comment by liamdebeasi** [comment]
You can just do `npm i @ionic/angular@next` in your project directory.

**Comment by peterennis** [comment]
@liamdebeasi 
Repo here: https://github.com/peterennis/A9I5-test
Ionic blank project, updated to A9 rc12 and I5 rc2

Test passes.

Differences I noticed are:

![Capture811](https://user-images.githubusercontent.com/140737/73587153-cc1f9500-446c-11ea-8c59-3583b58ee27c.PNG)

![Capture812](https://user-images.githubusercontent.com/140737/73587152-cb86fe80-446c-11ea-8e9b-ef1b1e8ec366.PNG)

![Capture813](https://user-images.githubusercontent.com/140737/73587151-cb86fe80-446c-11ea-9b40-3df88084e215.PNG)

I will use this as a baseline and move the assets for the next step.

I plan to use Capacitor.

**Comment by peterennis** [comment]
@liamdebeasi 

I used the same process and tested with the tabs starter.
Tests work.

A9 rc.12 and I5 rc.2

Repo: https://github.com/peterennis/A9I5-test

![Capture814](https://user-images.githubusercontent.com/140737/73603557-fdfe2d80-4538-11ea-8724-cc6527834b08.PNG)

Thanks 👍
