### ISSUE TITLE
BUG: Ionic 5 rc.1 doesn't compile to production

### ISSUE THREAD

**Issue by JoeBoxr** [ionic-team/ionic#20341]
[x ] **5.x**

**I'm submitting a ...** 

[ x] bug report

**Current behavior:**
Ionic 5 doesn't compile to production

**Expected behavior:**
Ionic 5 compiles to production

**Steps to reproduce:**
1) ionic start myApp tab
2) cd myApp
3) npm install "@ionic/angular@next" --save
4) ionic build --prod

**Related code:**

ERROR in ./node_modules/@ionic/angular/fesm2015/ionic-angular.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined

A sample application via GitHub

StackBlitz (https://stackblitz.com)

Plunker (http://plnkr.co/edit/cpeRJs?p=preview)

-->

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
Thank you for the issue! Could you please try updating the following dependencies and see if this fixes it for you:

dependencies:

```
"@angular/common": "8.2.13",
"@angular/core": "8.2.13",
"@angular/forms": "8.2.13",
"@angular/platform-browser": "8.2.13",
"@angular/platform-browser-dynamic": "8.2.13",
"@angular/pwa": "^0.803.23",
"@angular/router": "8.2.13",
"@angular/service-worker": "^8.2.14",
```

dev dependencies:

```
"@angular-devkit/architect": "^0.803.23",
"@angular-devkit/build-angular": "^0.803.23",
"@angular-devkit/core": "^8.3.23",
"@angular-devkit/schematics": "^8.3.23",
"@angular/cli": "^8.3.23",
"@angular/compiler": "8.2.13",
"@angular/compiler-cli": "8.2.13",
"@angular/language-service": "^8.2.14",
"@ionic/angular-toolkit": "^2.1.2",
```

**Comment by brandyscarney** [comment]
@JoeBoxr Thanks for confirming! We're actually going to look to see if this is something we can fix on older versions since we are looking to support all versions of Angular 8. 🙂

**Comment by brandyscarney** [comment]
I discussed this with the team and we have already begun requiring `8.2.x` as the lowest supported version. I'm going to close this since we have a PR for the starters to update this: https://github.com/ionic-team/starters/pull/1079/files

Thank you!
