### ISSUE TITLE
bug: 5.0.0-rc.2 padding top (safe-area-inset) not applied anymore

### ISSUE THREAD

**Issue by DavidStrausz** [ionic-team/ionic#20354]
# Bug Report

**Ionic version:**

[x] **5.0.0-rc.2**

**Current behavior:**
Safe area inset top is not applied to translucent `ion-header`s anymore.

**Expected behavior:**
Safe area inset top is applied.

**Steps to reproduce:**
Install 5.0.0-rc.2 -> open any page with an translucent `ion-header` on an iOS device with notch (e.g. iPhone X)

**Related code:**
https://github.com/ionic-team/ionic/blob/43d00415a5fd5044f821c4c8d60397f72b7bb96d/core/src/components/header/header.scss#L17

**Other information:**
I think because of the newly added `div.header-background` the CSS rule is not applied anymore, moving the div in inspector fixes the issue.

**Ionic info:**

```
Ionic:

  Ionic CLI                     : 5.4.15 (/usr/local/lib/node_modules/ionic)
  Ionic Framework               : @ionic/angular 5.0.0-rc.2
  @angular-devkit/build-angular : 0.900.0-rc.12
  @angular-devkit/schematics    : 9.0.0-rc.12
  @angular/cli                  : 9.0.0-rc.12
  @ionic/angular-toolkit        : 2.0.0

Cordova:

  Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
  Cordova Platforms : ios 5.0.1
  Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 27 other plugins)

Utility:

  cordova-res : not installed
  native-run  : not installed

System:

  ios-deploy : 1.9.2
  ios-sim    : 8.0.2
  NodeJS     : v12.4.0 (/usr/local/bin/node)
  npm        : 6.11.3
  OS         : macOS Catalina
  Xcode      : Xcode 11.3.1 Build version 11C504

```

**Comment by brandyscarney** [comment]
Thank you for the issue!

@liamdebeasi I can confirm this happens with a translucent header *without* the large title.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue? `5.0.0-dev.202002041614.e580b88`

**Comment by DavidStrausz** [comment]
@liamdebeasi Almost, now the padding is applied to the first toolbar in the secondary header in ion-content (see screenshot).

![image0](https://user-images.githubusercontent.com/7592254/73766467-58380200-4776-11ea-9925-2b077eb6b0de.jpeg)

Also, the color (or filter) of the primary header seems a bit off when using the large header + translucent whereas it works fine with only a small header + translucent (I can open an extra issue if you want to keep them separated).

**Comment by liamdebeasi** [comment]
Yep just noticed that. I'll fix that and push another dev build 👍

**Comment by liamdebeasi** [comment]
Ok can you give this dev build a try? `5.0.0-dev.202002041730.fbcf48c`

**Comment by DavidStrausz** [comment]
@liamdebeasi Padding works now :) thank you!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20375 and will be available in an upcoming release of Ionic Framework.
