### ISSUE TITLE
bug: ionChange event on ion-Range is a customEvent

### ISSUE THREAD

**Issue by NeckbreakerPascal** [ionic-team/ionic#20355]
# Bug Report

**Ionic version:**

[x] **4.11.10**

**Current behavior:**

By using (ionChange) with exampleFunction($event) the event Param is always a CustomEvent and not an event with information about the ion-range. 

**Expected behavior:**

In older versions of Ionic there has been infos about the range (like isFocus, value, etc.)

**Steps to reproduce:**

- create ionic starter project
- in template put `<ion-range></ion-range>` in ion-content section and add `(ionChange)=changeFunction($event)`. 
  `<ion-range (ionChange)="changeFunction($event)"></ion-range>`
- in .ts file add the changeFunction($event) to the class
- start ionic serve
- check browser console for Custom event

**Related code:**
Template: 
```
<ion-range (ionChange)="changeFunction($event)"></ion-range>
```

ts-File: 

```
changeFunction(event){
console.log(event);
}
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.0.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 5.0.4, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 26 other plugins)

Utility:

   cordova-res : 0.9.0
   native-run  : 0.3.0

System:

   ios-deploy : 1.9.2
   ios-sim    : 8.0.2
   NodeJS     : v12.14.1 (/usr/local/bin/node)
   npm        : 6.13.6
   OS         : macOS Mojave
   Xcode      : Xcode 11.3.1 Build version 11C504

```

**Comment by brandyscarney** [comment]
Thanks for the issue! All of our emitted events have been changed to emit any data for the component in the `detail` property of the `CustomEvent`. The `value` is still emitted in this, see this Codepen: https://codepen.io/brandyscarney/pen/gObNqRr?editors=1111

Is there something specific you're looking for in the `ionChange` event?

**Comment by NeckbreakerPascal** [comment]
> Thanks for the issue! All of our emitted events have been changed to emit any data for the component in the `detail` property of the `CustomEvent`. The `value` is still emitted in this, see this Codepen: https://codepen.io/brandyscarney/pen/gObNqRr?editors=1111
> 
> Is there something specific you're looking for in the `ionChange` event?

Thanks for the quick reply. 

Yeah, I saw that the value is in the `detail `property. I tried to use the "ion-range" as a progress-bar for a player. I used ngModel with a currentPosition variable. 

My problem was, that the ionChange event then get triggered everytime something changed. So I move on and tried ionFocus and ionBlur but both didn't send the value in the detail property. 

So maybe the problem is then more the ionBlur and ionFocus event. Sorry for that. I thought it was my failure or something with the "CustomEvent" itself. 

Is it correct that ionBlur and ionFocus do not send the value with the event?

**Comment by NikolaPeevski** [comment]
@NeckbreakerPascal Thinks of ionFocus and ionBlur as two focus related events. ionFocus will fire when the element is focused and ionBlur will fire after the focus of an element is removed. If you take the example of ion-range when you try to toggle the range (ie. click and drag) ionFocus will fire, when you let go and stop dragging the knob ionBlur will fire. Both events have a slight (I think 2 seconds) debounce timer so if you were to toggle the knob and then immediately toggle it again you'll still get only one ionFocus and ionBlur trigger. You can checkout https://ionicframework.com/docs/api/progress-bar it might fit your case better. And lastly they don't send the value. The ionChange emits the value every time there is a change in the range  component, one tip to reduce the event spam is to pipe-debounce it and return the ionChange result similarly to how ionFocus/Blur are implemented.

**Comment by NeckbreakerPascal** [comment]
@NikolaPeevski thanks for the info. Not sure with the progress-bar because I want to let the user click on the progress-bar to forward and backward the media. But anyway. For me this issue is resolved because I missunderstood those events ionFocus and ionBlur.

I thought they both should deliver the value, but if it was always planned that they don't it is fine. 

Thanks for the support and the quick answers.
