### ISSUE TITLE
Can't import the named export '' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by CacoCode** [ionic-team/ionic#20357]
_             _
  (_) ___  _ __ (_) ___
  | |/ _ \| '_ \| |/ __|
  | | (_) | | | | | (__
  |_|\___/|_| |_|_|\___| CLI 6.0.0

  Usage:

    $ ionic <command> [<args>] [--help] [--verbose] [--quiet] [--no-interactive] [--no-color] [--confirm] [options]

  Global Commands:

    completion ...................... (experimental) Enables tab-completion for Ionic CLI commands.
    config <subcommand> ............. Manage CLI and project config values (subcommands: get, set, unset)
    docs ............................ Open the Ionic documentation website
    info ............................ Print project, system, and environment information
    init ............................ (beta) Initialize existing projects with Ionic
    login ........................... Log in to Ionic
    logout .......................... Log out of Ionic
    signup .......................... Create an Ionic account
    ssh <subcommand> ................ Commands for configuring SSH keys (subcommands: add, delete, generate, list,
                                      setup, use)
    start ........................... Create a new project

  Project Commands:

    build ........................... Build web assets and prepare your app for any platform targets
    capacitor <subcommand> .......... Capacitor functionality (subcommands: add, copy, open, run, sync, update) (alias:
                                      cap)
    cordova <subcommand> ............ Cordova functionality (subcommands: build, compile, emulate, platform, plugin,
                                      prepare, requirements, resources, run)
    deploy <subcommand> ............. (paid) Appflow Deploy functionality (subcommands: add, build)
    doctor <subcommand> ............. Commands for checking the health of your Ionic project (subcommands: check, list,
                                      treat)
    enterprise <subcommand> ......... (paid) Manage Ionic Enterprise features (subcommands: register)
    generate ........................ Automatically create framework features (alias: g)
    git <subcommand> ................ Commands relating to git (subcommands: remote)
    integrations <subcommand> ....... Manage various integrations in your app (subcommands: disable, enable, list)
                                      (alias: i)
    link ............................ Connect local apps to Ionic
    package <subcommand> ............ (paid) Appflow package functionality (subcommands: build)
    repair .......................... Remove and recreate dependencies and generated files
    serve ........................... Start a local dev server for app dev/testing (alias: s)
    ssl <subcommand> ................ (experimental) Commands for managing SSL keys & certificates (subcommands:
                                      generate)

CacodeAir:students.ims caco$ sudo ionic -v
6.0.0
CacodeAir:students.ims caco$ sudo ionic serve
> ng run app:serve --host=localhost --port=8100
[ng] Browserslist: caniuse-lite is outdated. Please run next command `npm update`
[ng] ℹ ｢wds｣: Project is running at http://localhost:8100/webpack-dev-server/
[ng] ℹ ｢wds｣: webpack output is served from /
[ng] ℹ ｢wds｣: 404s will fallback to //index.html
[ng] chunk {main} main.js, main.js.map (main) 409 kB [initial] [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 278 kB [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 6.09 kB [entry] [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 117 kB [initial] [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 5.68 MB [initial] [rendered]
[ng] Date: 2020-02-02T07:28:14.094Z - Hash: 4c7ea2f127c5460c2b04 - Time: 24925ms
[ng] 
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/loader.mjs 5:9-17
[ng] Can't import the named export 'a' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/loader.mjs 7:4-17
[ng] Can't import the named export 'b' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/loader.mjs 6:4-11
[ng] Can't import the named export 'g' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/index.mjs 7:0-205
[ng] Can't reexport the named export 'a' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/index.mjs 7:0-205
[ng] Can't reexport the named export 'b' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/index.mjs 7:0-205
[ng] Can't reexport the named export 'c' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/index.mjs 7:0-205
[ng] Can't reexport the named export 'l' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/index.mjs 7:0-205
[ng] Can't reexport the named export 'm' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/index.mjs 7:0-205
[ng] Can't reexport the named export 'p' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/index.mjs 7:0-205
[ng] Can't reexport the named export 't' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/overlays-10640d86.js 151:26
[ng] Module parse failed: Unexpected token (151:26)
[ng] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[ng] |     let isAnimationBuilder = true;
[ng] |     try {
[ng] >         const mod = await import('./index-69c37885.js');
[ng] |         animation = await mod.create(animationBuilder, aniRoot, opts);
[ng] |     }
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/core-ca0488fc.js 75:11
[ng] Module parse failed: Unexpected token (75:11)
[ng] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[ng] |         return module[exportName];
[ng] |     }
[ng] >     return import(
[ng] |     /* webpackInclude: /\.entry\.js$/ */
[ng] |     /* webpackExclude: /\.system\.entry\.js$/ */
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/polyfills/index.js 7:18
[ng] Module parse failed: Unexpected token (7:18)
[ng] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[ng] | 
[ng] |   if (!win.customElements || (win.Element && (!win.Element.prototype.closest || !win.Element.prototype.matches || !win.Element.prototype.remove))) {
[ng] >     promises.push(import('./dom.js'));
[ng] |   }
[ng] | 
[ng] ERROR in ./src/app/app-routing.module.ts 7:28
[ng] Module parse failed: Unexpected token (7:28)
[ng] File was processed with these loaders:
[ng]  * ./node_modules/@ngtools/webpack/src/index.js
[ng] You may need an additional loader to handle the result of these loaders.
[ng] |     {
[ng] |         path: '',
[ng] >         loadChildren: () => import('./tabs/tabs.module').then(m => m.TabsPageModule)
[ng] |     }
[ng] | ];

[INFO] Development server running!
       
       Local: http://localhost:8100
       
       Use Ctrl+C to quit this process

[INFO] Browser window opened to http://localhost:8100!

[ng] ℹ ｢wdm｣: Failed to compile.

**Comment by NikolaPeevski** [comment]
@CacoCode Can you try running the following commands:

- ```npm remove -g ionic```
- ```npm install -g ionic```

In your project directory:

- ```rm -rf ./node_modules```
- ```npm i```
- ```ionic serve```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you able to reproduce this issue on a blank Ionic starter?
