### ISSUE TITLE
bug: Core Build Fail - [ ERROR ]  EBUSY: resource busy or locked, copyfile '...\swiper\swiper.bundle.js'

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic#20358]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

Local build on Windows 10.
Following this: https://github.com/ionic-team/ionic/tree/master/core/scripts

**Expected behavior:**

It builds.

**Steps to reproduce:**

Follow the documentation.

Result:

![Capture815](https://user-images.githubusercontent.com/140737/73621032-5856c700-45e9-11ea-9f57-f9d6bcae05d1.PNG)

```
C:\ae\ionic\core>npm start

> @ionic/core@5.0.0-rc.2 start C:\ae\ionic\core
> npm run build.css && stencil build --dev --watch --serve


> @ionic/core@5.0.0-rc.2 build.css C:\ae\ionic\core
> npm run css.sass && npm run css.minify


> @ionic/core@5.0.0-rc.2 css.sass C:\ae\ionic\core
> sass src/css:./css


> @ionic/core@5.0.0-rc.2 css.minify C:\ae\ionic\core
> cleancss -O2 -o ./css/ionic.bundle.css ./css/ionic.bundle.css

[14:22.6]  @stencil/core v1.8.3
[14:24.3]  build, ionic, dev mode, started ...
[14:24.7]  transpile started ...
[14:36.4]  transpile finished in 11.71 s
[14:36.5]  type checking started ...
[14:36.5]  copy started ...
[14:36.5]  generate styles started ...
[14:36.6]  bundling components started ...
[14:42.4]  copy finished (1239 files) in 5.96 s
[15:15.8]  type checking finished in 39.31 s
[15:18.6]  generate styles finished in 42.12 s

[ ERROR ]  EBUSY: resource busy or locked, copyfile 'C:\ae\ionic\core\src\components\slides\swiper\swiper.bundle.js' ->
           'C:\ae\ionic\core\dist\collection\components\slides\swiper\swiper.bundle.js'

[15:18.6]  dev server: http://localhost:3333/
[15:18.6]  build failed, watching for changes... in 54.32 s
```

**Related code:**

I saw this on the console after `npm i`

```
Downloading Chromium r686378 - 143 Mb [====================] 100% 0.0s
Chromium downloaded to C:\ae\ionic\core\node_modules\puppeteer\.local-chromium\win64-686378

> swiper@4.5.1 postinstall C:\ae\ionic\core\node_modules\swiper
> node -e "console.log('\u001b[35m\u001b[1mLove Swiper? Support Vladimir\'s work by donating or pledging on patreon:\u001b[22m\u001b[39m\n > \u001b[32mhttps://patreon.com/vladimirkharlampidi\u001b[0m\n')"

Love Swiper? Support Vladimir's work by donating or pledging on patreon:
 > https://patreon.com/vladimirkharlampidi

```

**Other information:**

**Ionic info:**

```
C:\ae\ionic\core>ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 6.0.0

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   NodeJS : v12.13.0
   npm    : 6.13.4
   OS     : Windows 10
```

**Comment by NikolaPeevski** [comment]
@peterennis If you're running from cmd/powershell can you try to open it as an administrator and run ```npm start``` again ?

**Comment by peterennis** [comment]
@NikolaPeevski 

Same error when cmd is run as administrator.

![Capture816](https://user-images.githubusercontent.com/140737/73624789-0157ee80-45f7-11ea-9dbe-913fd976f6a8.PNG)

**Comment by NikolaPeevski** [comment]
@peterennis with the terminal still opened as an administrator can you try running:
- ```npm cache clean```
- ``` npm start ```

Otherwise you can check out which process is locking the file as explained [here](https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows/643312#643312) and close it. It's a windows issue with npm.

**Comment by peterennis** [comment]
cache clean needs --force
same error

![Capture818](https://user-images.githubusercontent.com/140737/73625285-0322b180-45f9-11ea-86bf-869ddb7ed11a.PNG)

**Comment by peterennis** [comment]
terminated node process with resmon.exe
run again as administrator
same error

**Comment by NikolaPeevski** [comment]
Other things you can try are:

- If you have any anti-malware software disable it and reboot your system

-  Completely delete the repo, clone it, npm install and npm start as administrator

**Comment by peterennis** [comment]
@NikolaPeevski 

Shutdown/restart
Run `npm start` as administrator
now shows this:

![Capture819](https://user-images.githubusercontent.com/140737/73627654-5c431300-4602-11ea-9a11-014ae14a0d2d.PNG)

Is that what is expected?

**Comment by NikolaPeevski** [comment]
@peterennis Congrats and yes, that's what you should see. The [ReadMe](https://github.com/ionic-team/ionic/tree/master/core/scripts) explains what you could do from there on, for example check out some of the components.

**Comment by peterennis** [comment]
@NikolaPeevski 

Thanks for the tips.
