### ISSUE TITLE
bug: Ionicons are no longer displayed after updating to Ionic 5

### ISSUE THREAD

**Issue by raziel057** [ionic-team/ionic#20353]
# Bug Report

**Ionic version:**
[x] **5.0.0-rc.2*

**Current behavior:**
Using the last release of Ionic (4.11.7) all ionicons are displayed but when I upgrade to 5.x I have no more icons loaded. 

I checked in www/svg folder I have the icons prefixed by ``ios-`` and ``md-`` like as for ionic 4.x but when I brose the mobile app using my browser (ionic serve), I can see that requests are done to get the svg files without any prefix. with ionic 4 the request is done for the sema resource adding the "md-" prefix.

Html in template file:
```html
<ion-icon name="person" item-start></ion-icon>
```

Html of generated icon is the same for ionic 4 / 5:

```html
<ion-icon _ngcontent-osv-c1="" item-start="" mode="md" name="person" ng-reflect-mode="md" ng-reflect-name="person" role="img" class="md hydrated" aria-label="person"></ion-icon>
```

BR,

**Comment by wilk-polarny** [comment]
Have you tried upgrading ionicons to the version being used by Ionic 5?
You may need to do a clean build and/or also get rid of your caches when you use.

```
There will no longer be auto-switching for platform specificity when using Ionicons in an Ionic Framework app. If you'd like to switch icon styles based on the platform in Ionic use the md and ios attributes and provide the platform specific icon/variant name.

<ion-icon ios="heart-outline" md="heart-sharp"></ion-icon>
```

**Comment by brandyscarney** [comment]
Can you please provide more information for this? Are you using Angular or React? If you're using React, you need to update to the `ionicons@dev` version. There's more information on this here: https://ionicframework.com/blog/ionic-5-0-0-release-candidate/

Ionicons were updated to remove/rename many icons and platform specific icons no longer exist. There's more information on this in the Ionicons changelog, and we'll have a blog out soon about this: https://github.com/ionic-team/ionicons/blob/master/CHANGELOG.md#500-17-2020-01-27

**Comment by joselevelsup** [comment]
Using `@ionic/react` and using the `ionicons@dev` icons to not show. 

Code:
```
<IonButtons slot="primary">
	<IonButton>
		<IonIcon slot="start" name="alert-circle" />
	</IonButton>
</IonButtons>
```

Ionic Info:
```
Ionic:

   Ionic CLI       : 6.1.0 (~/.nvm/versions/node/v10.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.0.0

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.19.0 (/home/skippy/.nvm/versions/node/v10.19.0/bin/node)
   npm    : 6.13.4
   OS     : Linux 5.3

```

**Comment by joselevelsup** [comment]
So after doing some looking around in the docs and the issues, what we are supposed to do is import the ionicon icons then use it in the component as so:
```
import { arrowBack } from "ionicons/icons";
import { IonIcon } from "@ionic/react";

<IonIcon icon={arrowBack} />
```

It's not clearly stated in the docs since it says we can use the `name` prop.

@raziel057 I don't know if you are using react with this. If so, try this out. If not, I hope you find your answer soon!

Ref: #19673

**Comment by elylucas** [comment]
Hi @raziel057,

If you upgrade to the latest version of Ionic (5.0.1 at this time) and the latest version of ionicons (5.0.0), does the problem still happen? 

Also, make sure you are using the icon prop on IonIcon and importing the icon from 'ionicons/icons' and not the name attribute. 

We are working on better clarifying that in the docs now.

Thanks

**Comment by skmohammadi** [comment]
> import { arrowBack } from "ionicons/icons";

This worked for me. thank you @joselevelsup

**Comment by brandyscarney** [comment]
@elylucas Can you weigh in on the React side of things?

**Comment by jackflyer** [comment]
Same issue exists with Vue "@ionic/core": "5.0.4" or "@ionic/core": "5.0.7"  , "@ionic/vue": "0.0.9".

**Comment by inspire22** [comment]
I can't get the above solution to work with vue (importing from @ionic/vue instead), using "<IonIcon :icon="arrowBack"></IonIcon>" gives "The "arrowBack" component has been registered but not used".

Ion-icon & Icon aren't listed in the v4 or v5 docs even, though they are mentioned inside https://ionicframework.com/docs/api/button  It seems surprising icons have been broken for this long without much outcry?

Including <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script> in the head also doesn't seem to work with vue for some reason, though it works for me on a test plain html file.

**Comment by brandyscarney** [comment]
I'm going to close this issue as the original poster has not replied to requests for more information & the code provided looks like Ionic 3 source code. Ionicons has been working fine in our starters for Angular & React. I've also created a vanilla JS Codepen with them here: https://codepen.io/brandyscarney/pen/qBExRwv

If you are using Ionic React you must import the icon you want to use from the ionicons package & use the `icon` property to set it. See this issue troubleshooting the usage: https://github.com/ionic-team/ionic/issues/18847

```
import {close} from 'ionicons/icons';
...
<IonBackButton icon={close} />
```

We have documentation for this in individual components (https://ionicframework.com/docs/api/fab#usage), but I created an issue to improve the overall documentation for this: https://github.com/ionic-team/ionic-docs/issues/1384

Ionic Vue is still in beta and Ionicons 5 is not currently set up to work with it. We are actively discussing devoting more time to it now that Vue 3 is in beta, but I don't have a timeline right now. However, if you are experiencing problems using Ionicons *with Vue* and an issue doesn't already exist (https://github.com/ionic-team/ionic/issues/19078 or https://github.com/ionic-team/ionic/issues/18837) please create a separate issue so we can track it. Thank you!

**Comment by inspire22** [comment]
Thanks!  I only need 3 icons so I just found a site that exported them directly as svg and am using them as an image, it seemed simpler for now.

**Comment by mavyfaby** [comment]
> If you are using `ionic/vue` with `Ionic 5` and `ionicons` don't show. Try doing this
> 
> Do this to use ionicons in Ionic 5
> 
> ```
> import { iosEye, mdEye } from "ionicons/icons";
> import { addIcons } from "ionicons";
> 
> addIcons({
>   "ios-eye": iosEye,
>   "md-eye": mdEye
> });
> ```
> 
> In the HTML
> `<ion-icon name="eye"></ion-icon>`

This works for me❤ I'm using @ionic/vue v0.0.4
