### ISSUE TITLE
bug: month name array cannot be changed after ion-datetime created

### ISSUE THREAD

**Issue by Wingzzzzz** [ionic-team/ionic#20367]
# Bug Report

**Ionic version:**
4.11.10

**Current behavior:**
After component init, change of month name does not reflect in the date picker

**Expected behavior:**
when date picker is being opened, month name is the newest value from input  

**Steps to reproduce:**
Change monthNames after page loaded and open date picker again to see if monthNames changed

**Related code:**
https://stackblitz.com/edit/ionic-v4-datetime-monthname

**Other information:**
This is an issue across ionic 2/3/4.
In ionic 3, my workaround is to force user to reenter the page with date picker again when language changed.
In ionic 4, from https://github.com/ionic-team/ionic/blob/master/core/src/components/datetime/datetime.tsx,
```
line 162: @Prop() monthNames?: string[] | string;
line 168: @Prop() monthShortNames?: string[] | string;
```
<del>my wide guess is without ```@Prop({ mutable: true })```, the new value does not reflect in the picker.
And</del> 
**Cause:** 
```this.locale.[monthNames/monthShortNames/dayNames/dayShortNames] ``` updated by ```convertToArrayOfStrings()``` is only loaded once in ```componentWillLoad()```
<del>One solution may be ```convertToArrayOfStrings()``` on the fly when ```open()``` called</del>
__________________________________________________________________
<del>if i misunderstand the ```mutable``` in stencil and the value is actually updated in ```ion-datetime```,</del>
just copy line 241-247 to ```generatePickerOptions()```
p.s. small performance defect applying the change

To ionic ion-datetime development member:
this is question raised in ionic 2/3 and the logic remains,
hope to see member to add some inputs here,
maybe explaining why not apply simple fix on it

**Comment by antoinecfmws** [comment]
@Wingzzzzz did you figure out a way to work around this? Same issue, updating an array of monthShortNames in angular does not reflect when the ion-datetime is opened. This happens in an instance when switching languages and we need to re-render the ion-datetime months.

**Comment by Wingzzzzz** [comment]
@antoinecfmws no, users currently accept the behavior.

**Comment by antoinecfmws** [comment]
@Wingzzzzz I pushed a PR to fix it, hopefully the ionic team can take a look at it and merge it. Thank you for replying.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20826, and a fix will be available in an upcoming release of Ionic Framework.
