### ISSUE TITLE
bug: Redirect in nested IonRouterOutlet creates a blank page.

### ISSUE THREAD

**Issue by OoDeLally** [ionic-team/ionic#20363]
# Bug Report

**Ionic version:**
4.11.10

**Current behavior:**
Adding a (specific) `<Redirect />` in a `<IonRouterOutlet>` leads to a blank page. The console shows no error or warning.

**Expected behavior:**
It should instead render the expected route, since the `Redirect`'s `from` doesn't even exactly match the location.

**Steps to reproduce:**
I created a minimal repo to reproduce the bug:
https://github.com/OoDeLally/ion-router-redirect-bug
  
The bug does not happen with "@ionic/react-router": "4.11.7",
The bug appears from "@ionic/react-router": "4.11.8",

The issue is possibly related to https://github.com/ionic-team/ionic/issues/20349

**Ionic info:**

```
▶ ionic info

Ionic:

   Ionic CLI       : 5.4.4 (/home/user/.nvm/versions/node/v8.16.0/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.10

Capacitor:

   Capacitor CLI   : not installed
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : 0.2.9 (update available: 0.3.0)

System:

   NodeJS : v8.16.0 (/home/user/.nvm/versions/node/v8.16.0/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.15


  ────────────────────────────────────────────────

     Ionic CLI update available: 5.4.4 → 5.4.15
            Run npm i -g ionic to update

  ────────────────────────────────────────────────



```

**Comment by elylucas** [comment]
Hi @OoDeLally,

I found the issue and fixed it, however, it is not recommended to do Redirects directly in IonRouterOutlet.

Redirects with the from prop have issues when not used from within a Switch, and IonRouterOutlet doesn't support switches. See: https://reacttraining.com/react-router/web/api/Redirect/from-string

To get around this, we suggest doing what you did with the Route and doing a redirect in the render prop.

**Comment by OoDeLally** [comment]
Thanks @elylucas , will do!

**Comment by OoDeLally** [comment]
Hi @elylucas I've replaced 

```
        <Redirect exact from={routes.profile.edit} to={firstPageInSequence} />
```

by

```
<Route
          path="/profile/:profileName"
          exact
          render={
            () => {
              console.log(`Redirect ${location.pathname} => ${firstPageInSequence}`)
              return <Redirect to={ firstPageInSequence } /> ;
            }
          } />

```

The console shows me 
```
Redirect /profile/new/permissions => /profile/new/permissions
```

Which means the redirection route was used despite the `exact` attribute, which imho should prevent `/profile/:profileName` to match `/profile/new/permissions`, isnt it?
