### ISSUE TITLE
bug:  background-activated css property is not working for ion-tab-button

### ISSUE THREAD

**Issue by rajiramamoorthi** [ionic-team/ionic#20360]
Hi,

--background-activated css property is not working for ion-tab-button.

ion-tab-button{
 --background-activated:rgb(73, 177, 187,0.2);
}

**Comment by NikolaPeevski** [comment]
@rajiramamoorthi There isn't a `background-activated `property for this component according to the [official docs](https://ionicframework.com/docs/api/tab-button) and according to [github's readme](https://github.com/ionic-team/ionic/tree/master/core/src/components/tab-button).

**Comment by brandyscarney** [comment]
Thanks for the issue! @NikolaPeevski is correct, tabs does not have this CSS variable. We do have an issue open here to update these components to have the variables they need: https://github.com/ionic-team/ionic/issues/18279. Please subscribe to this issue for updates!

Note that the activated class is only added on press in iOS, and in Material Design it uses a ripple upon activation/press.
