### ISSUE TITLE
bug: Ionic 5 native refresher stops working when ion-item-sliding is present

### ISSUE THREAD

**Issue by Unkn0wn0x** [ionic-team/ionic#20379]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
The new, native `<ion-refresher>`, stops working completely, if the pan down / pull to refresh event is triggered on a `<ion-item-sliding>` element. On the other hand, a "custom" `<ion-refresher>` (with icon, text, etc.), works like a charm.

**Expected behavior:**
The native `<ion-refresher>` works on `<ion-item-sliding>` elements like a "custom" `<ion-refresher>`.

**Steps to reproduce:**
See fiddle here: [https://jsfiddle.net/2bxft0qk/](https://jsfiddle.net/2bxft0qk/)
Video: [https://streamable.com/t64qo](https://streamable.com/t64qo)

**Other information:**
It looks like the pan / pull to refresh gesture of the native `<ion-refresher>` gets stucked when triggered on a `<ion-item-sliding>`.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.0.1 (/Users/[my-user]/.nvm/versions/node/v13.7.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0-rc.2
   @angular-devkit/build-angular : 0.803.24
   @angular-devkit/schematics    : 8.3.24
   @angular/cli                  : 8.3.24
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/[my-user]/Library/Android/sdk/)
   ios-sim           : 8.0.2
   NodeJS            : v13.7.0 (/Users/[my-user]/.nvm/versions/node/v13.7.0/bin/node)
   npm               : 6.13.7
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue? `5.0.0-dev.202002042100.5911842`

**Comment by Unkn0wn0x** [comment]
Thanks for your fast response!

I did the following steps which did not lead to the expected behavior:

1. Modify `package.json`
  `"@ionic/angular": "^5.0.0-dev.202002042100.5911842"`
2. Run `ionic repair` to cleanup the workspace.
3. Run `ionic serve` and check behavior.

`ionic info` returns the following version of the npm package:
`Ionic Framework               : @ionic/angular 5.0.0-rc.2` 

But that should be fine, as your fix branch is created from the master branch.

Let me know, if I can support you.

**Comment by liamdebeasi** [comment]
You should be installing `5.0.0-dev.202002042100.5911842` exactly. Using the `^` is going to cause `5.0.0-rc.2` to be installed.

Please try again by running `npm i @ionic/angular@5.0.0-dev.202002042100.5911842`.

**Comment by Unkn0wn0x** [comment]
Yeah, you're right, my bad.

Works like a charm, great job, thanks for your efforts! 👏
