### ISSUE TITLE
feat: Property to disable :hover effects on ion-item/button/* components

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic#20376]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

A property `[hoverEffect]=false` to disable pointer hover effects entirely, on ion-item, ion-button, etc, is necessary to complete full style/theme buildouts.

**Describe Preferred Solution**

A property `[hoverEffect]=false` to disable pointer hover styles.

**Describe Alternatives**

Setting `pointer-events: none` in CSS, however this has the unusable side-effect of disabling all click and touch-scrolling events.

**Related Code**

`<ion-item [hoverEffect]=false routerLink="/foo" class=no-hover>...</ion-item>`

**Additional Context**

This could also be used to disable hover effects when ion-content is scrolling, which can be a performance impact if complex compositing is required for non-trivial layouts.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This should already be possible via the use of CSS variables.

You could do something like this:

```css
ion-button {
  --background-hover: var(--background);
}
```

Here is a CodePen with an example: https://codepen.io/liamdebeasi/pen/QWbLRPp

Does this work for your use case?

**Comment by lincolnthree** [comment]
Yes, that actually works. Very clever :) Thanks for the tip. I guess this issue is probably unnecessary if that's all it takes.

Much appreciated, as usual @liamdebeasi .
