### ISSUE TITLE
bug: ng-content doesn't populate on android

### ISSUE THREAD

**Issue by barrcodes** [ionic-team/ionic#20374]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
If I create a component with ng-content, I can populate some inner html based on context. This works fine on iOS, but on Android, nothing appears.

**Expected behavior:**
I expect ng-content to show on all platforms

**Related code:**

In the following Special Component, the "Left" and "Right" buttons will appear on iOS, but not Android

*header.component.html*
```
<ion-header>
  <ion-toolbar>
    
    <!-- Left Buttons -->
    <ion-buttons slot="start">
      <ion-back-button
        [text]="backText || 'Back'"
        routerDirection="back">
      </ion-back-button>
      <ng-content select="[left-buttons]"></ng-content>
    </ion-buttons>

    <ion-title>
        {{titleText}}
    </ion-title>

    <!-- Right Buttons -->
    <ion-buttons slot="end">
      <ng-content select="[right-buttons]"></ng-content>
    </ion-buttons>

  </ion-toolbar>
</ion-header>
```

*special-header.component.html*
```
<header titleText="I'm a special header">
    <div left-buttons>
        <ion-button>Left</ion-button>
    </div>
    <div right-buttons>
        <ion-button>Right</ion-button>
    </div>
</header>
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.0.1
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.803.24
   @angular-devkit/schematics    : 8.3.20
   @angular/cli                  : 8.3.20
   @ionic/angular-toolkit        : 2.1.1

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (4 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-sim : 8.0.2
   NodeJS  : v13.5.0 (/Users/matthewbarr/.nvm/versions/node/v13.5.0/bin/node)
   npm     : 6.13.4
   OS      : macOS Catalina
   Xcode   : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by NikolaPeevski** [comment]
@liamdebeasi I would assume he's trying to do something similar to this: https://github.com/NikolaPeevski/ionic-ng-content-repo populating the ng content dynamically with ViewContainerRef and ComponentFactoryResolver although I have some local issues simulating an android device and cannot test it. It works without issues in ios

**Comment by barrcodes** [comment]
I always hate that question, but when you're right you're right.

Made a new repo, no bug. Realized that the issue I had was related to 
https://github.com/angular/angular/issues/22972

The issue (which was not properly stated in my report) was that in my component I had two `ion-header` blocks with `*ngIf="platform.is('...')"` to determine which one to show. Since I did that, I had duplicate `ng-content` blocks with duplicate select statements. Angular selects the first `ng-content` block it finds, regardless of whether or not the `*ngIf` directive specifies that the `ng-content` block should be shown.

Since the iOS header was first, even when it was not shown due to a negative `*ngIf`, its `left-buttons` and `right-buttons` blocks were being selected. This caused my Android buttons to not be shown.

Hope that helps anyone who comes upon this issue.
