### ISSUE TITLE
bug/feat: Make cascading mode configurable

### ISSUE THREAD

**Issue by Unkn0wn0x** [ionic-team/ionic#20370]
**Ionic version:**

[x] **5.x**

**I'm submitting a ...** 

[x] bug report
[x] feature request

**Current behavior:**
The new Ionic 5 RC (is great!) but the feature for cascading `modes` does not help (in my case), on the contrary, it causes more code to be added to the markup.

For example I want(ed) the styling of the `<ion-card>` in `mode="ios"`, but keep it for the childs (f. e. `<ion-item>`, `<ion-avatar>`, `<ion-label>`, `<ion-text>`, `<ion-button>`, etc. (profile card)) in `mode="md"`.

Now I have to add `mode="md"` to all of the `<ion-card>`'s child elements instead of just `mode="ios"` on the `<ion-card>`.

**Expected behavior:**
Make it configurable on the component level, f. e. with `cascadeMode="true"` /  `cascadeMode="false"` with default set to true, like the new Ionic 5 RC expects it.

**Steps to reproduce:**
Run a Ionic 4 Application with the example code of the [ion-card](https://ionicframework.com/docs/api/card) in `mode="ios"` and on the other hand with a Ionic 5 Application.

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 6.0.1 (/Users/[my-user]/.nvm/versions/node/v13.7.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0-rc.2
   @angular-devkit/build-angular : 0.803.24
   @angular-devkit/schematics    : 8.3.24
   @angular/cli                  : 8.3.24
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/[my-user]/Library/Android/sdk/)
   ios-sim           : 8.0.2
   NodeJS            : v13.7.0 (/Users/[my-user]/.nvm/versions/node/v13.7.0/bin/node)
   npm               : 6.13.7
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment]
Thanks for the feature request. We opted to have `mode` cascade in order to make theming more consistent for our users. As a result, we do not currently have plans to add an option to disable mode cascading.

In your case; however, I think it would make more sense to just style the `ion-card` as you see fit rather than set the `mode` property on each component.

I have created a CodePen with an example: https://codepen.io/liamdebeasi/pen/MWwgOwG
