### ISSUE TITLE
bug: infinite-scroll will not scroll up after complete() is called [5.0.0-rc.2, MD mode]

### ISSUE THREAD

**Issue by ogix** [ionic-team/ionic#20371]
# Bug Report

**Ionic version:**

[x] **5.0.0-rc.2**

**Current behavior:**

Now when I scroll down to load more items - infinite-scroll loader appears and disappears but scroll position remains at the bottom so in order to trigger loading more items I have to scroll up a bit and then scroll down. I can only reproduce this behavior in MD mode.

**Expected behavior:**

After calling complete() on infinite-scroll I expect scroll position to be higher so I can scroll down again and trigger loading more items. Like in this example: https://ionicframework.com/docs/api/infinite-scroll

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am unable to reproduce this issue using the information you have provided.
