### ISSUE TITLE
feat: could you add background press color to div tag for IOS ( mode="ios")

### ISSUE THREAD

**Issue by rajiramamoorthi** [ionic-team/ionic#20373]
Hi
could you add background press color for div tag similarly like ion-ripple-effect

<div class="ion-activatable" >
      A plain div with an unbounded ripple effect
      <ion-ripple-effect type="unbounded" mode="ios"><ion-ripple-effect>
    </div>

**Comment by brandyscarney** [comment]
This is already possible using ripple effect, see the following codepen: https://codepen.io/brandyscarney/pen/BaNBwoB?editors=1100

Usage for ripple effect: https://ionicframework.com/docs/api/ripple-effect#usage

**Comment by rajiramamoorthi** [comment]
Thanks for your reply. I am expecting background press color only not ripple effect in ios device.  Material design ripple effect is not required for ios device. could you please provide solution for how add background press color only not ripple effect.

**Comment by brandyscarney** [comment]
The `activated` class is added by Ionic to any element that has the `ion-activatable` class on press. You can use this to style for iOS on press: https://codepen.io/brandyscarney/pen/mdJddGR

Please note that in v5 `activated` is being renamed to `ion-activated`: https://github.com/ionic-team/ionic/blob/master/BREAKING.md#activated-focused-hover-states

If you have more questions on using Ionic Framework please ask on the forums: https://forum.ionicframework.com. Thank you!

**Comment by rajiramamoorthi** [comment]
Thank you so much.
