### ISSUE TITLE
bug: improve selection of highlighted option in picker

### ISSUE THREAD

**Issue by loopezz** [ionic-team/ionic#20397]
# Bug Report

**Ionic version:**

[x] **4.11.8**

**Current behavior:**
While trying to select the highlighted option with a minimal drag it simply overscrolls it.
![picker](https://user-images.githubusercontent.com/11312418/73948510-5f3b4d80-48f9-11ea-8beb-55e19f5c821b.gif)

**Expected behavior:**
Snap to the current highlighted option (like in Ionic v3.x).
![picker_pref](https://user-images.githubusercontent.com/11312418/73948525-64989800-48f9-11ea-9e29-0038f8f6c8fd.gif)

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this has already been fixed and will be available in an upcoming release of Ionic Framework 😄
