### ISSUE TITLE
bug: Switch with React Router does't re-render children on prop change

### ISSUE THREAD

**Issue by mirkonasato** [ionic-team/ionic#20390]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
Having a `<Switch>` inside `<IonRouterOutlet>` causes the `<Route>`s not to be re-rendered when props change.

**Expected behavior:**
`Switch` should work like it does in standalone React Router without Ionic.

**Steps to reproduce:**

TODO: I'll create a Github repo shortly then come back and edit this line...

**Other information:**
The [React Navigation](https://ionicframework.com/docs/react/navigation#switches-in-ionrouteroutlet) page in the Ionic documentation says

> Since IonRouterOutlet takes over the job in determining which routes get rendered, using a Switch from React Router has no effect when used inside of an IonRouterOutlet. Switches still function as expected when used outside an IonRouterOutlet.

As far as I can see it's not true that using a `Switch` has no effect. Without a `Switch` multiple `Route`s can be matched, e.g.

```jsx
<IonRouterOutlet>
  <Route exact path="/"><Home /></Route>
  <Route path="/"><NotFound /></Route>
</IonRouterOutlet>
```

would render both `Home` and `NotFound` when `"/"` is requested. But with a `Switch` inside `IonRouterOutlet` only the first route is rendered. That's why I need to use `Switch`.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.0.1 (/home/mirko/.nvm/versions/node/v12.14.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.0.0-rc.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.14.1 (/home/mirko/.nvm/versions/node/v12.14.1/bin/node)
   npm    : 6.13.6
   OS     : Linux 5.3
```

**Comment by elylucas** [comment]
Hello,

Switches are not supported in IonRouterOutlets, sorry the documentation is confusing around that. I'll get it updated.

To do a not found route, see this issue:  #20105

**Comment by mirkonasato** [comment]
Oh, I see.  The "not found" was just one use case really, I was also trying to get tabs on some pages but not others... need to try some other way I guess.

**Comment by elylucas** [comment]
You can put switches around routes further down the component tree, they just can't be direct children of IonRouterOutlet.
