### ISSUE TITLE
bug: ion-item box-shadow

### ISSUE THREAD

**Issue by LOUNNAS** [ionic-team/ionic#20392]
# Bug Report

**Ionic version:**

[x] **5.0.0-rc.3**

**Current behavior:**

The variable css --box-shadow does not have the same effect as box-shadow of css

**Expected behavior:**
The varibale --box-shadow  will have the same effect as box-shadow css.

**Example:**

1- 

```
ion-item {
    box-shadow: 0 0 3px 0 var(--ion-color-medium);
}
```
![wihout](https://user-images.githubusercontent.com/18683428/73925095-ca6f2a80-48cd-11ea-8ef4-e302f6472442.PNG)

2- 
```
ion-item {
    --box-shadow: 0 0 3px 0 var(--ion-color-medium);
}
```
![with](https://user-images.githubusercontent.com/18683428/73925196-f8ed0580-48cd-11ea-9cb1-e717562b62ef.PNG)

Thanks for your help.
Achille.

**Comment by liamdebeasi** [comment]
Thanks for the issue. It looks like this `--box-shadow` property never worked and wasn't supposed to be in there anyways. Moving forward, we suggest that developers just use `box-shadow` directly on `ion-item`.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20412.
