### ISSUE TITLE
ion-slide calculated width is not correct on Chrome 80 with slidesPerView greater than 1

### ISSUE THREAD

**Issue by vfportero** [ionic-team/ionic#20396]
**Ionic version:**
[] **4.x**
[x] **5.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
Since the last update of Chrome (v80, February 4, 2020) the ion-slide width, when `slidesPerView: 1.02` is broken:

![image](https://user-images.githubusercontent.com/1107782/73936086-5428f300-48e2-11ea-8411-55404321b917.png)
![image](https://user-images.githubusercontent.com/1107782/73936116-64d96900-48e2-11ea-9712-c95d82cf0bb8.png)

Before this Chrome update the slide width was ~340px for a viewport of 375px with is correct to show the current slide and the beggining of the next one.

I've solved this setting a max-width on .swiper-wrapper and .swiper-slide but I've rather prefer the native solution that's calculates the slide width based on viewport & the slidesPerView property.

**Expected behavior:**

The slide must be fit in the viewport because the slidesPerView property is greater than 1.

**Steps to reproduce:**

Create 2 or more <ios-slide> inside a <ion-slides> with the property slidesPerView with a value greater than 1.

**Related code:**

Example Code
```
<ion-slides [options]="{slidesPerView : 1.02}" >
  <ion-slide>SLIDE1</ion-slide>
  <ion-slide>SLIDE2</ion-slide>
</ion-slides>
```

**Other information:**

Temp fix:

```
.swiper-wrapper {
        max-width: calc(100vw - 30px);
        .swiper-slide {
            max-width: calc(100vw - 30px);
        }
    }
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by vfportero** [comment]
Hi Liam!

Nevermind, is an issue with Chrome 80 and the css-grid in some cases... the ion-slides only make the situation worse.

Thanks for your response and sorry for the inconvenience.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Is this an already reported bug in Chrome, or did you just test in an older version of Chrome and saw that it worked there?

**Comment by jonashammerschmidtkrz** [comment]
> Thanks for the follow up. Is this an already reported bug in Chrome, or did you just test in an older version of Chrome and saw that it worked there?

This is definitely a problem with Chrome 80. I have the same issue. For me this bug appears in Chrome 80.0.3987.87 but not in Chrome 79.0.3945.79.
