### ISSUE TITLE
feat: need a new version of @ionic/vue that has support for ionicons v5. 

### ISSUE THREAD

**Issue by boboldehampsink** [ionic-team/ionic#20409]
It is already on master, just needs a new bump in npm

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as we are waiting for Vue 3 to stabilize before we push forward with Ionic Vue development. Once Vue 3 stabilizes we will look into providing an update that brings better support for Ionicons (namely Ionicons v5). Thanks!
