### ISSUE TITLE
bug: --box-shadow on ion-searchbar not working, despite PR #19838

### ISSUE THREAD

**Issue by tnishimura** [ionic-team/ionic#20404]
# Bug Report

**Ionic version:**
Master @ionic/core. Also present as far back as 4.11.7

**Current behavior:**
--box-shadow on ion-searchbar seems to do nothing. 

**Expected behavior:**
According to [PR #19838](https://github.com/ionic-team/ionic/pull/19838) box-shadow should work, but --box-shadow does seemingly nothing.

**Steps to reproduce:**
Please see https://gist.github.com/tnishimura/c8d01c199c28100e5ec85967ead6fa95. Basically, I took the [search bar example from the docs](https://github.com/ionic-team/ionic-docs/blob/master/src/demos/api/searchbar/index.html), changed the cdn links to 4.11.10, and applied the --box-shadow style to the ion-searchbar (via the red-box class). The red-box class style is copied from the example/test case given in #19838. 

**Related code:**
Please see https://gist.github.com/tnishimura/c8d01c199c28100e5ec85967ead6fa95

**Other information:**

**Ionic info:**
Not relevant, since I am using the CDN and plain JS.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This feature was added to Ionic Framework 5, which has not been released yet. Please see https://ionicframework.com/blog/ionic-5-0-0-release-candidate/ for more information.

**Comment by tnishimura** [comment]
Ok, I understand. However, it does seem that the PR is merged into the 4.11.10 release... Is --box-shadow currently deactivated or something?
