### ISSUE TITLE
bug: ion-select deafults values not getting set when multiple=true

### ISSUE THREAD

**Issue by aardrasystems** [ionic-team/ionic#20418]
I am using Ionic 4.

I am not sure if this is a bug, but can not manage to solve it, unless there is a solution.

I have created a <Ion-select> selection option , the default selection is set on page load up with values from an api. This works well when multiple is false.

If i set multiple to true, so that more then one option can be selected, then on page load , those values do not get selected. This my code. Please adv

`<div *ngIf="(outputportcon !='None') && ZoneMode !='Relayswitch' ">
    <ion-item-divider class="divider_custom">
      <ion-grid fixed="true">
        <ion-row justify-content-start>
          <ion-col size="auto" align-self-center>
            <ion-label>Valve Sequencing Mode:</ion-label>
          </ion-col>
           <ion-col size="auto" align-self-center>
            <ion-toggle color="primary" [(ngModel)]="Valve_Sequencing_Mode"></ion-toggle>
          </ion-col> 
        </ion-row>
        <ion-row justify-content-start>
          <ion-col size="auto" align-self-center>
            <ion-label>Irrigation Valve Switch:</ion-label>
          </ion-col>
          <ion-col size="auto" align-self-center>            
              <ion-select  multiple="{{Valve_Sequencing_Mode}}" [(ngModel)]="irrgationswitch" >
              <div *ngIf="(outputportcon=='Standard')">
                <ion-select-option  value="No Valve">No Valve</ion-select-option>
                <ion-select-option  value="Output Set 1">Output Set 1</ion-select-option>
                <ion-select-option  value="Output Set 2">Output Set 2 </ion-select-option>
                <ion-select-option  value="Output Set 3">Output Set 3 </ion-select-option>
              </div>
              <div *ngIf="(outputportcon=='Relay Expansion 1')">
                <ion-select-option value="No Valve">No Valve</ion-select-option>
                <ion-select-option value="Output Set 1">Output Set 1</ion-select-option>
                <ion-select-option value="Output Set 2">Output Set 2 </ion-select-option>
                <ion-select-option value="Output Set 3">Output Set 3 </ion-select-option>
                <ion-select-option value="Output Set 4">Output Set 4</ion-select-option>
                <ion-select-option value="Output Set 5">Output Set 5 </ion-select-option>
                <ion-select-option value="Output Set 6">Output Set 6 </ion-select-option>
                <ion-select-option value="Output Set 7">Output Set 7 </ion-select-option>
                <ion-select-option value="Output Set 8">Output Set 8 </ion-select-option>
              </div>
            </ion-select>
          </ion-col>
        </ion-row>
      </ion-grid>
    </ion-item-divider>
  </div>`

Thank You

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? Additionally, please ensure that `Valve_Sequencing_Mode` and `irrgationswitch` are arrays that contain the values of the options that you would like to select.

For example:

```html
<ion-select multiple [(ngModel)]="selectedValues">
  <ion-select-option value="a">a</ion-select-option>
  <ion-select-option value="b">b</ion-select-option>
  <ion-select-option value="c">c</ion-select-option>
</ion-select>
```

```typescript
public selectedValues: string[] = ['a', 'c']; 
```
