### ISSUE TITLE
bug: ion-toast message with ion-icon 

### ISSUE THREAD

**Issue by albernaz** [ionic-team/ionic#20416]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

1) ion-toast message with ion-icon do not work when icon name has a slash.
2) ion-toast message with ion-icon do not work when icon has color and size attributes

**Expected behavior:**

ion-icon must appear as ion-icons [usage ](https://ionicons.com/usage/)suggests.

**Steps to reproduce:**

Add a toast with message that has a ion-icon within.

**Related code:**
```
  async presentToast(): Promise<void> {
    const toast = await this.toastController.create({
      message: 'Install this PWA on your iPhone: Tap <ion-icon name="share-social" color="warning" size="large"></ion-icon> icon bellow and Add to Home Screen. ',
    });
    toast.present();
  }
```

```
insert short code snippets here
```

**Other information:**

It’s not working because [sanitization ](https://github.com/ionic-team/ionic/blob/3403574f313ea66e62041e678ada4c290342b78d/core/src/utils/sanitization/index.ts) (line 125) made on message [toast ](https://github.com/ionic-team/ionic/blob/3403574f313ea66e62041e678ada4c290342b78d/core/src/components/toast/toast.tsx) (line 286) not allow color and size attributes.

**Ionic info:**

```
insert the output from ionic info here
```
Ionic:

   Ionic CLI                     : 5.4.15 (C:\Users\Fabiano Lemos\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.7
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this in favor of https://github.com/ionic-team/ionic/issues/18277. Rather than add exceptions for different use cases, we are leaning towards giving developers a way of ejecting from the sanitization process altogether.
