### ISSUE TITLE
bug: Ionic 5 rc.3 and Angular 9 - template form validation error

### ISSUE THREAD

**Issue by JoeBoxr** [ionic-team/ionic#20410]
# Bug Report

**Ionic version:**
[x] 5 rc.3

**Current behavior:**
Using Form validation on the template side I'm getting this for for all of my .valid calls for my ion-inputs...

error TS2339: Property 'valid' does not exist on type 'IonInput'.

**Expected behavior:**
compiles and runs as expected

**Steps to reproduce:**
Create a form using template validation and reference the .valid properties of the ion-input

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by JoeBoxr** [comment]
Looks as though Angular 9's template type checking is what is causing the issue.
https://angular.io/guide/template-typecheck

As it stands now Ionic will need to use type checking in Basic mode by
setting  "fullTemplateTypeCheck": false  in tsconfig.json.

Regards

**Comment by mhartington** [comment]
@JoeBoxr would you be able to provide a demo/test case for this? This would really help in us debugging your issue.

**Comment by JoeBoxr** [comment]
Here's the steps to reproduce.

1.  ionic start myApp tabs
2.  ng update @angular/cli @angular/core --force=true

3. Please this code on any tab
<ion-input #helloworld></ion-input>
<ion-text color="danger" [hidden]="helloworld.valid"></ion-text>

4. ionic build --prod

**Comment by mhartington** [comment]
This happens in Angular 8 as well. The issue is not related to ionic/angular, but the fact you are trying to bind to a property that does not exist on the component. `ion-input` does not have a `valid` property.

**Comment by JoeBoxr** [comment]
Ok.  I'll review how i do validation and close this ticket.  Thanks again

**Comment by mhartington** [comment]
Take a look at the guides provided by angular. They cover all the stuff you should need.

https://angular.io/guide/form-validation#template-driven-validation
