### ISSUE TITLE
bug: could you provide resolution on the hardware back issues in ionic 5?

### ISSUE THREAD

**Issue by rajiramamoorthi** [ionic-team/ionic#20417]
Hi,
Could you resolve this bug "Consolidated list of Android hardware back button issues #16611" in ionic 5 version.

**Comment by liamdebeasi** [comment]
Thanks for the issue. We are currently focused on releasing Ionic Framework v5 right now. Hardware back button issues are a priority for us post-v5 launch. We will provide any hardware back button related updates on this thread: https://github.com/ionic-team/ionic/issues/16611

**Comment by rajiramamoorthi** [comment]
Thank you.
