### ISSUE TITLE
bug: Failed to load resource: the server responded with a status of 404 (OK) [http://localhost/svg/paper.svg]

### ISSUE THREAD

**Issue by starlleytk** [ionic-team/ionic#20413]
# Bug Report

**Ionic version:**

[x] 5.0.0-rc.3

**Current behavior:**

This issue happens when i migrated ionic 4.11.10 to 5.0.0-rc.3!

**Expected behavior:**

**Related code:**

```
Failed to load resource: the server responded with a status of 404 (OK) [http://localhost/svg/paper.svg]
Failed to load resource: the server responded with a status of 404 (OK) [http://localhost/svg/chatboxes.svg]
Failed to load resource: the server responded with a status of 404 (OK) [http://localhost/svg/contacts.svg]
Failed to load resource: the server responded with a status of 404 (OK) [http://localhost/svg/pie.svg]
```

**Other information:**

**Ionic info:**

   Ionic CLI                     : 6.0.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0-rc.3
   @angular-devkit/build-angular : 0.803.24
   @angular-devkit/schematics    : 8.3.21
   @angular/cli                  : 8.3.21
   @ionic/angular-toolkit        : 2.1.1

**Cordova:**

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 23 other plugins)

**Utility:**

   cordova-res (update available: 0.9.0) : 0.8.1
   native-run (update available: 0.3.0)  : 0.2.9

**System:**

   Android SDK Tools : 26.1.1 (/home/starlley/Documents/Android)
   NodeJS            : v12.13.0 (/usr/local/bin/node)
   npm               : 6.13.7
   OS                : Linux 5.3
```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by starlleytk** [comment]
> Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

Sorry! This project is private I don't have permission to post any part!

**Comment by liamdebeasi** [comment]
I just double checked the changelog for Ionicons and it looks like you are still using the old Ionicons v4 names. As per the breaking changes doc, Ionic Framework v5 ships with Ionicons v5 where some icons have been renamed. See https://github.com/ionic-team/ionic/blob/master/BREAKING.md#ionicons for more information.

**Comment by starlleytk** [comment]
> I just double checked the changelog for Ionicons and it looks like you are still using the old Ionicons v4 names. As per the breaking changes doc, Ionic Framework v5 ships with Ionicons v5 where some icons have been renamed. See https://github.com/ionic-team/ionic/blob/master/BREAKING.md#ionicons for more information.

Thanks!
