### ISSUE TITLE
bug: Ionicon imports not in sync with Ionicons v5

### ISSUE THREAD

**Issue by Joshua-Sherer-Bose** [ionic-team/ionic#20428]
# Bug Report

**Ionic version: 4.11.10**

**Current behavior:**
Updated ionicons package to v5. When attempting to run `ionic serve` or `npm run start` the following error occurred:
```
node_modules/@ionic/react/dist/index.esm.js
Attempted import error: 'reorder' is not exported from 'ionicons/icons'.
```

**Expected behavior:**
Ionic project should have built successfully

**Steps to reproduce:**
Using the latest version of Ionic React, create a new Ionic project and add the `ionicons` v5 package. Attempt to run `ionic serve` or `npm run start`

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.15 (/Users/js19275/.nvm/versions/node/v12.10.0/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.10

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res : 0.9.0
   native-run  : 0.3.0

System:

   NodeJS : v12.10.0 (/Users/js19275/.nvm/versions/node/v12.10.0/bin/node)
   npm    : 6.13.1
   OS     : macOS Mojave

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. We will be pushing a new version of Ionic React soon that uses Ionicons v5 internally.

**Comment by SanderMuller** [comment]
I experience this issue using **ionic-vue@0.0.9** with ionicons@5.0.0
