### ISSUE TITLE
bug: How to set mode="ios" or mode="md" for page navigation?

### ISSUE THREAD

**Issue by rajiramamoorthi** [ionic-team/ionic#20425]
Hi,

Could you provide an example for page navigation to set custom mode option?
this.navController.navigateForward('/tabs/tab4/disclaimer');
this.navController.navigateBack('/tabs/tab4');

**Comment by liamdebeasi** [comment]
Thanks for the issue. The recommended way to set mode is via the global app config: https://ionicframework.com/docs/angular/config. From there, you can set the mode to be `ios` or `md`.

In the next major release of Ionic Framework you will also be able to set `mode` on a component such as `ion-content` and have each child component inherit that specific mode. For more information on this change in the next major version of Ionic Framework, please see: https://github.com/ionic-team/ionic/blob/master/BREAKING.md#mode

**Comment by rajiramamoorthi** [comment]
Thanks for your reply. I am expecting **mode option** for the below APIs
**this.navController.navigateForward
this.navController.navigateBack**
This will provide me flexibility to set ios transition for android devices using navController API. 
Could you please provide solution on this?

**Comment by liamdebeasi** [comment]
Is this for an Ionic 3 application? NavController does not exist in Ionic 4+ anymore.

**Comment by rajiramamoorthi** [comment]
Hi ,
   I am using ionic 4 for my application. The below mentioned APIs are working in ionic 4 
**this.navController.navigateForward
this.navController.navigateBack**
  How to do navigation programatically using ionic 4 using API with mode option? 
  Please provide solution.

**Comment by liamdebeasi** [comment]
As per the docs, you can provide a custom animation in `navAnimation`: https://ionicframework.com/docs/angular/config. You can either a) provide a separate animation per mode, or b) add some logic inside of your animation that changes depending on the mode.

It is not recommended that you set the animation when doing `navigateForward` or `navigateBack`. For follow up questions, I recommend asking your question on our [forums](http://forum.ionicframework.com/) as this is really more of a support question.
