### ISSUE TITLE
Open modal show blank white in ios  5.1.0 . I using ionic 4

### ISSUE THREAD

**Issue by nguyentrunghieutcu** [ionic-team/ionic#20422]
async createModal(data?) {
    const modal = await this.modal.create({
      component: CreateComponent,
      componentProps: data

    });
    return await modal.present();
![IMG_3773](https://user-images.githubusercontent.com/24294935/74121248-60ba8d80-4bf9-11ea-8b31-80c5bae95f23.PNG)

  }

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?
