### ISSUE TITLE
bug: How to override default navAnimation?

### ISSUE THREAD

**Issue by rajiramamoorthi** [ionic-team/ionic#20424]
HI,
       Could you provide an example for custom **AnimationBuilder** for config **navAnimation**?  
       We used the below code but there is no option to change the page transition type **left to right** and **right to left** vice versa.
            this.navController.navigateForward('/tabs/tab4/disclaimer');
            this.navController.navigateBack('/tabs/tab4');

**Comment by liamdebeasi** [comment]
Thanks for the issue. You can use the `navAnimation` configuration customize the transition animation: https://ionicframework.com/docs/angular/config#config-options.

Here is an example of the standard MD transition that you can copy/alter for your application: https://github.com/ionic-team/ionic/blob/4.11.x/core/src/utils/transition/md.transition.ts.

**Comment by liamdebeasi** [comment]
Also I should add that the next major release of Ionic Framework (which will be out very soon) will provide more guidance on this, including some animation API changes.

**Comment by rajiramamoorthi** [comment]
Thanks for your reply. I am not able to copy and edit the above code. It is throwing the below 
**import { TransitionOptions, getIonPageElement } from '../transition';**  is not available. Please provide the solution for the imports.
I am waiting for ionic 5 version which will provide more guidance on animation/transition

**Comment by liamdebeasi** [comment]
Those are local imports within Ionic, so you are going to need to copy those as well if you would like to use them.
