### ISSUE TITLE
bug: ion-tab-bar large middle button gets cut off vertically on Android and Chrome

### ISSUE THREAD

**Issue by jwqchen** [ionic-team/ionic#20421]
# Bug Report

**Ionic version:**

[x] **4.11.10**

**Current behavior:**

I want to create a tab bar with a large middle button whose height is taller than the tab bar:

![expected-tab](https://user-images.githubusercontent.com/8445536/74113477-37e2bb80-4b59-11ea-8dbe-0761de4e4e25.png)

It displays correctly on ios, but gets cut off vertically on android and on Chrome. I tried putting mode=”ios” on ion-tabs and also its child elements, but the android and Chrome versions still do not display correctly:

![bug-tab](https://user-images.githubusercontent.com/8445536/74113476-33b69e00-4b59-11ea-87e6-426a06509aa1.png)

**Expected behavior:**

Display the full middle button on Android and Chrome.

**Related code:**

Here is my tab bar code:

```
<ion-tabs mode="ios">
    <ion-tab-bar slot="bottom" mode="ios">
        <ion-tab-button tab="mycannas" mode="ios" layout="label-hide">
            <ion-icon name="basketball" mode="ios"></ion-icon>
        </ion-tab-button>

        <!-- Here is the button in question -->
        <ion-tab-button class="middle-btn" tab="search" mode="ios" layout="label-hide">
            <ion-icon name="aperture" mode="ios"></ion-icon>
        </ion-tab-button>

        <ion-tab-button tab="discover" mode="ios" layout="label-hide">
            <ion-icon name="clock" mode="md" mode="ios"></ion-icon>
        </ion-tab-button>
    </ion-tab-bar>
</ion-tabs>
```

Here is the CSS:

```
ion-tab-bar {
    --background: #0265ac;
    --color: rgba(255, 255, 255, 0.7);
    --color-selected: white;	
}

.middle-btn {
    height: 70px;
    border-radius: 50%;
    background: white;
    z-index: 100;
    max-width: 70px;
    color: #0265ac;
    border: 4px solid #0076c9;
    margin-top: -18px;
}
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. You will need to set `contain: none` on the `ion-tab-bar` component if you want that large button to overflow outside of the bounds of the `ion-tab-bar`.

**Comment by jwqchen** [comment]
Thank you so much for your help! Worked like a charm :)
