### ISSUE TITLE
bug: ion-input password clears itself on submit action if `clearOnEdit` is on

### ISSUE THREAD

**Issue by wilk-polarny** [ionic-team/ionic#20442]
# Bug Report

**Ionic version:**
[x] **4.11.9**

**Current behavior:**
When using `<ion-input>` fields for password, clearOnEdit will be automatically enabled by default and works as expected. But when focusing the element and trying to submit a form using the Enter Key on the device keyboard, the password field will clear.

**Expected behavior:**
I expect the form to get submitted instead of the password field being cleared.

**Steps to reproduce:**
- Create a form with a submit action and an `<ion-input>` like below
- Type in a password and focus some other element or close the keyboard
- Focus the password field and do a submit action (for example by tapping the "Enter" button)
- Observe the password field clearing itself

**Related code:**

Also added clearInput, because we use this feature too - clearOnEdit is true by default for the type password.

```html
<ion-item>
  <ion-label position="fixed">Fixed Label</ion-label>
  <ion-input clearOnEdit clearInput type="password"></ion-input>
</ion-item>
```
**Other information:**

none.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.15 (/Users/Wilk/.nvm/versions/node/v10.16.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.9
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:

   cordova-res : 0.8.1
   native-run  : 0.3.0

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/Users/Wilk/.nvm/versions/node/v10.16.3/bin/node)
   npm        : 6.9.0
   OS         : macOS Catalina
   Xcode      : Xcode 11.3.1 Build version 11C504```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20462 and will be available in an upcoming release of Ionic Framework.
