### ISSUE TITLE
bug: Unable to set the navigation back programatically in ionic 5 (no transition animation)

### ISSUE THREAD

**Issue by Sunil509** [ionic-team/ionic#20448]
Hi,

Below Api's were in ionic 3. can I use it in ionic 5 . Please find the screenshot. Below screenshot is showing the below api's are available in ionic 5. 
<img width="1054" alt="Screenshot 2020-02-12 at 3 06 12 PM" src="https://user-images.githubusercontent.com/13060486/74327692-9e164b00-4db2-11ea-8d1b-b617fb481209.png">

this.navCtrl.navigateForward('/route');
this.navCtrl.navigateBack('/route');

Below api working fine forward transition but not working for backward transition. 
this.router.navigateByUrl('/tabs/tab1');

**Please suggest us how to do "back" transition without nav controller api in ionic 5.**

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you trying to create a custom navigation animation?

**Comment by Sunil509** [comment]
Hi,

Thanks for your reply.


I don't want do any custom navigation. I just want to use this below mentioned ionic api to forward/back animations through programatically.

this.router.navigateByUrl('/tabs/tab1');

By using above mentioned API, could you please help me to navigate forward/back animations through programatically with consistent animations.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. The `navigateBack` method for `NavController` still exists in Ionic 4/5 and does use the "backwards" navigation transition. 

`navigateByUrl` on `Router` does not have any options for animations because that is a method within Angular and not within Ionic.

If you want to control the direction of the transition you will need to use the Ionic-supplied methods. Does this answer your question?

**Comment by Sunil509** [comment]
Hi,

Thanks for your reply.

We thought like this NavController API is deprecated in IONIC4/5.
There is no document is available for NavController API in IONIC4/5. Could you please update the documentation and it will be helpful for everybody. Going forward will use the same.

**Comment by liamdebeasi** [comment]
The NavController is not deprecated in Ionic 4+. It looks like the documentation is missing and that there is already an open issue: https://github.com/ionic-team/ionic-docs/issues/506.

I am going to close this issue in favor of the one I linked to. Thanks!

**Comment by Sunil509** [comment]
Thanks.
