### ISSUE TITLE
Ionic start uses old version

### ISSUE THREAD

**Issue by PeterHdd** [ionic-team/ionic#20443]
First, thank you for the update!

After updating the npm package `ionic/angular` to V5.0.0:
I execute this command to check the version: 
```
npm list @ionic/angular
```
output:

```
/Users/peter
└── @ionic/angular@5.0.0 
```

So ionic/angular@5.0.0 is installed globally in my machine. But when I do:

```
ionic start newProject blank
```

For some reason, it is still taking the old @ionic/angular version and thus creating a project using ionic 4. The `ionic info` output:

```
   Ionic CLI                     : 6.0.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.2

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   NodeJS : v10.15.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment]
Thanks! We were a little behind on getting the starter updates out, but they should be available soon 🙂
