### ISSUE TITLE
bug: Problem with Angular 9 + Ionic 5

### ISSUE THREAD

**Issue by nicobytes** [ionic-team/ionic#20459]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
When run `ionic serve` the app doesn't work 

![img](https://i.imgur.com/1RHY8vG.png[/img])

![img](https://i.imgur.com/5aetyej.png[/img])

**Steps to reproduce:**

I try upgrade with follow steps:

- `ng update @angular/cli@8 @angular/core@8`
- `npm install @ionic/angular@latest @ionic/angular-toolkit@latest --save`
-  ng update @angular/cli @angular/core`

Ionic info:

```
   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.900.1
   @angular-devkit/schematics    : 9.0.1
   @angular/cli                  : 9.0.1
   @ionic/angular-toolkit        : 2.1.2
```

Ng version

```
@angular-devkit/architect         0.801.2
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               8.3.25
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

my tsconfig.app.json

```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "src/test.ts",
    "src/**/*.spec.ts"
  ]
}
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by fristys** [comment]
Maybe it's not working because Ionic [doesn't support Angular 9 yet](https://github.com/ionic-team/ionic/blob/f61b671844f1e76a7adea2937bd2c201e9b46861/angular/package.json#L49-L51)?

**Comment by NikolaPeevski** [comment]
@nicobytes  I feel like the latest version of Ionic still handles up to Angular 8 (as tried to create any project lets me make only Angular 8 projects). If I try to make a blank app and update with the instructions you provided it compiles without any issues. Can you try ``` rm -rf ./node_modules && npm i && ionic serve``` ?

**Comment by nourkrimesh** [comment]
I have the same issue.
Is there any official way to add new project and then upgrade into angular v9? or the templates will be updated to default have angular v9?

**Comment by liamdebeasi** [comment]
You can upgrade an app to Angular 9 by running `ng update @angular/core @angular/cli`.

The starter apps currently ship with Angular 8 and will be updated to ship with Angular 9 by default soon.
