### ISSUE TITLE
ionic 5: SideMenu can be opened when Modal is present

### ISSUE THREAD

**Issue by HansKrywaa** [ionic-team/ionic#20467]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

I can open the Side Menu via Swipe Gesture when a Modal is present. On Android, you can see it after the Modal disappears, but in IOS with the new iOS13 Style, you can see the Menu behind the Modal.

**Expected behavior:**

I think the normal behavior is to not be able to open the side menu via swipe gesture when a Modal is present. Maybe you could design it as it is default off, but overridable with a parameter in modal.create(...).

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 53 other plugins)

Utility:

   cordova-res (update available: 0.9.0) : 0.8.1
   native-run                            : 0.3.0

System:

   Android SDK Tools : 25.2.3 (/Users/hanskrywalsky/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/usr/local/bin/node)
   npm               : 6.13.7
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

`npm i @ionic/angular@5.1.0-dev.202002181905.45d03ba`

**Comment by HansKrywaa** [comment]
Awesome, works! 🎉

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20546 and will be available in an upcoming release of Ionic Framework.
