### ISSUE TITLE
ionic 5: Modal Background with Google Maps Classes

### ISSUE THREAD

**Issue by HansKrywaa** [ionic-team/ionic#20469]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

In my Project this Modal "Background Color" (see Image from your Announcement Demo) is **white**:

<img width="200" alt="Bildschirmfoto 2020-02-13 um 15 36 43" src="https://user-images.githubusercontent.com/20899975/74445631-fe6ec080-4e76-11ea-8cb9-c4bf474e6430.png">

I figured out why and it is because i have the [Google Maps Plugin](https://github.com/ionic-team/ionic-native-google-maps) installed and this sets this:
```
background-image: none !important;
background: rgba(0,0,0,0) none !important;
background-color: rgba(0,0,0,0) !important;
```

This seems to be the Reason why it is white in my Case.

**Expected behavior:**

The Background should be black, even if i use the Google Maps Plugin.

**Steps to reproduce:**

Create a ionic v5 Project, use the Maps Plugin and create a Map. Than create a Modal (on another Page).

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 53 other plugins)

Utility:

   cordova-res (update available: 0.9.0) : 0.8.1
   native-run                            : 0.3.0

System:

   Android SDK Tools : 25.2.3 (/Users/hanskrywalsky/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/usr/local/bin/node)
   npm               : 6.13.7
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves your issue?

`npm i @ionic/angular@5.1.0-dev.202002131454.9b8b652`

**Comment by HansKrywaa** [comment]
@liamdebeasi Yes, this Dev Build resolves it. Awesome! 🎉

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20470 and  will be available in an upcoming release of Ionic Framework.
