### ISSUE TITLE
bug: ion-segment mode="md" 

### ISSUE THREAD

**Issue by danielpspring** [ionic-team/ionic#20473]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

The default segment (as set via code/model) when the ion-segment mode is explicitly set to md (mode="md") doesn't appear selected. Everything appears to work when the mode is not set or is set to "ios".

UPDATE: Same behavior on web and mobile devices

UPDATE: in some circumstances, the segments work the first time the screen is opened but then in subsequent openings the segments don't work.  

UPDATE: it appears that the style "segment-button-checked" is not being set

**Expected behavior:**

The default segment is selected

**Steps to reproduce:**

**Related code:**

```
<ion-segment [(ngModel)]="courseDetailSegment" mode="md">
    <ion-segment-button value="detail">
      <ion-label>Details</ion-label>
    </ion-segment-button>
    <ion-segment-button value="tees">
      <ion-label>Tees</ion-label>
    </ion-segment-button>
</ion-segment>
```

**Other information:**

**Ionic info:**

```
There is no output or error messages
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. What is the value of `courseDetailSegment`?

**Comment by danielpspring** [comment]
Hello, that's a model variable that will equate to one of the ion-segment-button values (either "detail" or "tees").

Thanks,
Dan

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you provide a repo with the code required to reproduce this issue? I am unable to reproduce the behavior you are describing using the code snippets provided.

**Comment by danielpspring** [comment]
The app is too big but let me see if I can re-create the issue in a new project.

**Comment by danielpspring** [comment]
Please see https://github.com/ionic-team/ionic/issues/20500.
