### ISSUE TITLE
bug: ionicons 5 - for some icons not able to change the color

### ISSUE THREAD

**Issue by nutangwari** [ionic-team/ionic#20471]
# Bug Report

**ionic 5**

[x] **4.x**

**Current behavior:**
after upgrade, some of the icons are not picking up the color through parent styles or even if directly applied to the ion-icon component

listing down the icons not picking up the color through CSS.

pencil, code-working, arrow-forward etc.

below rule not changing the color of 
ion-icon {
 color: '#333';
}

**Expected behavior:**
other icons are changing with respect to the CSS rules applied.

```
ion-icon {
 color: '#333';
}
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Your color value should not be surrounded by quotes (i.e. `color: #333` not `color: '#333'`. 

Can you try that again and let me know if it resolves the issue?

**Comment by nutangwari** [comment]
@liamdebeasi yeah correct, it's proper color without quotes in my code, lets say same variable is properly showing the correct color while other icons on the same page using same variable are not changing the color.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you provide a code reproduction of the issue?

I have a CodePen here and colors seem to be working fine: https://codepen.io/liamdebeasi/pen/VwLejrB

**Comment by nutangwari** [comment]
@liamdebeasi i saw your code snippet and i believe there are some difference between the icon version you are using, i am using ionicon 5 which is released with ionic v5. Reason am saying is because the underlaying shadow DOM for both the icons is different, in your case it is appearing as path and styles are not inlined, hence it is picking up the styles.

while in my case shadow DOM is using polygons and #000 stroke is added inline to HTML.
adding screenshot 
![not working 2](https://user-images.githubusercontent.com/9932923/74525021-2d079c80-4f46-11ea-9b18-b44ca8f90f90.PNG)
![working](https://user-images.githubusercontent.com/9932923/74525023-2e38c980-4f46-11ea-89be-5841de62fcf0.PNG)

**Comment by liamdebeasi** [comment]
I am using Ionicons 5 as well. Can you please provide a reproduction of this issue on your end? This will help us address any issues faster.
