### ISSUE TITLE
feat: Could you provide extra css variable properties for ion-toggle in ionic 5?

### ISSUE THREAD

**Issue by rajiramamoorthi** [ionic-team/ionic#20474]
In the below **.toggle-inner**  is not able to update because of shadow component.
`.toggle-inner {
    left: 2px;
    top: 2px;
    position: absolute;
    width: 28px;
    height: 28px;
    box-shadow: rgba(0, 0, 0, 0.16) 0px 3px 12px, rgba(0, 0, 0, 0.1) 0px 3px 1px;
    will-change: transform;
    contain: strict;
    transition: transform 0.3s ease 0s, width 0.12s ease-in-out 80ms, left 0.11s ease-in-out 80ms, right 0.11s ease-in-out 80ms, -webkit-transform 0.3s ease 0s;
}`
Please provide the following css variables **left, top, width, height and box-shadow** for more flexible customisation.

Thank you

**Comment by rajiramamoorthi** [comment]
Any update on this

**Comment by brandyscarney** [comment]
Thanks for the issue! Toggle has been improved to make it easier to customize as part of this PR: https://github.com/ionic-team/ionic/pull/21050

There is some new documentation for the customization added here (this will go live on the toggle API docs after we release): https://github.com/ionic-team/ionic/blob/master/core/src/components/toggle/readme.md#customization

This will be in the `5.1` release which is expected soon, but the following dev build can be used if you want to take a sooner look. Run one of the following commands based on your framework integration:

```bash
# core / vanilla JS
npm i @ionic/core@5.1.0-dev.202004292244.04ace4c --save

# angular
npm i @ionic/angular@5.1.0-dev.202004292244.04ace4c --save

# react
npm i @ionic/react@5.1.0-dev.202004292244.04ace4c --save
```
