### ISSUE TITLE
feat: Set Mode globally more dynamically

### ISSUE THREAD

**Issue by HansKrywaa** [ionic-team/ionic#20477]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

I want to be able to set the App's Mode via App Config for specific "things" (like Animations).

**Describe Preferred Solution**

Currently i can set 
```
{
  mode: "ios"
}
```

**Describe Alternatives**

I want to be able to set something like this:
```
{
  mode: {
    alert: "ios",
    "modal": "ios",
    "other": "md"
}
```
so mode could be type of `config | string` to support backwards compatibility. If other isn't set the default should be used.

**Comment by HansKrywaa** [comment]
@liamdebeasi @brandyscarney is that a Feature that is interesting for the Team? I would love to try to implement it my own. If yes, it would be great if you can answer my Question [here](https://forum.ionicframework.com/t/install-ionic-fork-locally/183338), that i can install ionic from a cloned fork locally.

**Comment by brandyscarney** [comment]
Thanks for the issue! Do you have more information about your use case for this? When calling the overlay components you can set the individual mode, for example calling the alert (in JS):

```javascript
function presentAlert() {
  const alert = document.createElement('ion-alert');
  alert.cssClass = 'my-custom-class';
  alert.header = 'Alert';
  alert.subHeader = 'Subtitle';
  alert.message = 'This is an alert message.';
  alert.buttons = ['OK'];
  alert.mode = 'ios';

  document.body.appendChild(alert);
  return alert.present();
}
```

**Comment by HansKrywaa** [comment]
To be honest, i don't remember why i thought this would be usefull 😃 I know there was a reason, but i solved it somehow^^ Thank you.
