### ISSUE TITLE
bug: ion-card button ignores set color

### ISSUE THREAD

**Issue by medfx** [ionic-team/ionic#20484]
If you set a ion-card to render as a button `<ion-card button="true">` the rendered button will ignore the background color coming from color: `<ion-card button="true" color="primary">`.

The button will show the right text color but only white as background color.

Ionic version 5.0.0

**Comment by liamdebeasi** [comment]
Thanks for the issue. This issue has already been resolved and will be available in an upcoming release of Ionic Framework.
