### ISSUE TITLE
bug: Ionslide API is not able to access in ionic 5

### ISSUE THREAD

**Issue by rajiramamoorthi** [ionic-team/ionic#20488]
The below example code is not working in ionic 5.  **sliderRef object is undefined**. I want move slide to programatically.

`@ViewChild('sliderRef', { static: true }) public sliderRef: IonSlides

this.sliderRef.slideTo(1)`

**Comment by HansKrywaa** [comment]
Can you post your html?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by chpalatinus** [comment]
same here!

**Comment by rajiramamoorthi** [comment]
Hi @liamdebeasi ,

Please check the sample code in the below  repo URL
https://github.com/rajiramamoorthi/Test.git

The below method **boreListSlider object is undefined.**

`  ngOnInit(): void {
    // this.boreListSlider object is undefined.
    this.boreListSlider.slideTo(4);
  }`

Thank you

**Comment by rajiramamoorthi** [comment]
This is working now.
