### ISSUE TITLE
bug: Fab close icon doens't appear on 5.0.0

### ISSUE THREAD

**Issue by AntoninBeaufort** [ionic-team/ionic#20489]
Hi, sorry for my english I'm french.

# Bug Report

**Ionic version:**

[x] **5.0.0**

**Current behavior:**

When I click the fab button, the more icon disappear but the close icon doesn't appear.
`Failed to load resource: the server responded with a status of 404 (OK)      svg/close.svg:1`

**Expected behavior:**

When I click the fab button, the close button should appear.

**Steps to reproduce:**

Create a React project with Ionic 5.0.0 and Ionicons 5.0.0 and use the code below.

**Related code:**
```
<IonFab vertical="bottom" horizontal="end" slot="fixed" style={{marginBottom: 20}}>
          <IonFabButton color="secondary" activated={fabOpen} onClick={toggleFab}>
            <IonIcon icon={ellipsisVertical} size="large" />
          </IonFabButton>
          <IonFabList side="top">
            <IonFabButton color="secondary">
              <IonIcon icon={book} />
            </IonFabButton>
            <IonFabButton color="secondary">
              <IonIcon icon={add} />
            </IonFabButton>
          </IonFabList>
        </IonFab>
```
I tried with and without activated, but before the update, it was working without activated and onClick.

**Other information:**
I've looked at the component source code in the repo but I haven't found a code related to the icon.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.1.0 (C:\Users\anton\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.0.0

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res : 0.9.0
   native-run  : 0.3.0

System:

   NodeJS : v12.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.7
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20490 and will be available in an upcoming release of Ionic Framework.

**Comment by AntoninBeaufort** [comment]
Wow you're fast, thank you !
