### ISSUE TITLE
bug: Ionic 5 // Android 5 // Ion-Segment errors

### ISSUE THREAD

**Issue by SSuarezBrooktec** [ionic-team/ionic#20487]
# Bug Report

Ionic-Segment do not work on Android 5.1

**Ionic version:**

[x] **5.x**

**Steps to reproduce:**
Click on segment button

**Related code:**

Check this repo: https://github.com/SSuarezBrooktec/Ionic5_ion_segment_error

**Other information:**

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 6.1.0 (/Users/sergio/.nvm/versions/node/v13.0.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res (update available: 0.9.0) : 0.8.1
   native-run                            : not installed

System:

   NodeJS : v13.0.1 (/Users/sergio/.nvm/versions/node/v13.0.1/bin/node)
   npm    : 6.13.7
   OS     : macOS Catalina
```

**Comment by SSuarezBrooktec** [comment]
ion-segment do not working due a queryselector error in console on change segment-button. Can't change segment.

![74525451-6d085880-4f21-11ea-8f30-71d07ed7ea14](https://user-images.githubusercontent.com/56263935/74528305-400b7400-4f28-11ea-9db1-7eabcc4001b2.png)

**Comment by liamdebeasi** [comment]
Did you upload the correct code? The repo looks like it is just the default tabs starter app.

**Comment by SSuarezBrooktec** [comment]
Yes, try to compile and check this app in Android 5.1 (tabs not work)

**Comment by liamdebeasi** [comment]
I tried the app and all I see is the default Ionic 5 starter. I do not see any `ion-segment` usage. Can you double check that you pushed the latest code?

**Comment by SSuarezBrooktec** [comment]
sorry! hehe.

Try now!

**Comment by liamdebeasi** [comment]
It looks like this is the same issue as https://github.com/ionic-team/ionic/issues/20466, so I am going to combine these two issues. I will post any updates regarding this on the linked thread. Thanks!

**Comment by gminhaneli** [comment]
@liamdebeasi consegui replicar o problema, é o uso do bloqueio do touch no ngOnInit ou ionViewDidEnter

      document.addEventListener("touchstart", () => { this.slides.lockSwipes(true); }, false);
      document.addEventListener("touchend", () => { this.slides.lockSwipes(true); }, false);
      document.addEventListener("touchcancel", () => { this.slides.lockSwipes(true); }, false);
      document.addEventListener("touchleave", () => { this.slides.lockSwipes(true); }, false);
      document.addEventListener("touchmove", () => { this.slides.lockSwipes(true); }, false);

**Comment by SSuarezBrooktec** [comment]
Olá Gustavo, eu entendo um pouco de portugues, mas seria melhor se a ionic team escrevesse em ingles :D
