### ISSUE TITLE
Ionic 5 is not support Events?

### ISSUE THREAD

**Issue by saoud77** [ionic-team/ionic#20498]
I'm using Event to publish some data. But it's not working i am getting this error message export 'Events' was not found in '@ionic/angular'

**Comment by danielpspring** [comment]
Events has been depreciated. The Ionic 5 upgrade document outlines this change.

**Comment by saoud77** [comment]
@danielpspring Thanks

**Comment by viplavsoni** [comment]
You can refer these, 
It can be useful for you 
https://medium.com/wizpanda/dealing-with-breaking-change-in-ionic-5-db3ba711dfcd
