### ISSUE TITLE
bug: Video is not playing on Android version 9 and v10 . 

### ISSUE THREAD

**Issue by saurabhpanwar67412** [ionic-team/ionic#20493]
Hi, I am working on ionic@2.2.1 framwork project with cordova@7.1.0 . i am having a issue that video are not playing on the android v9 and v10 only. The app is using moodle web api with code in angularJS (ionic v1). Please help me to resolve this issue. 

Cordova CLI: Not installed
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.10.0 
ios-sim version: 8.0.2 
OS: macOS
Node Version: v10.19.0
Xcode version: Xcode 10.3 Build version 10G8 

https://i.stack.imgur.com/2ZG0G.jpg . Please refer to the link to check the error.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This repo is for issues regarding Ionic 4/5 only. We are no longer developing Ionic 1, so we recommend you post your question on the [forums](https://forum.ionicframework.com/).
