### ISSUE TITLE
bug: Missing properties in Toast component

### ISSUE THREAD

**Issue by videmort** [ionic-team/ionic#20506]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
ToastController hasn't got showCloseButton and closeButtonText  properties.

**Expected behavior:**
To have that properties.

**Ionic info:**

```
  Ionic CLI                     : 6.1.0 (/Users/pc/.nvm/versions/node/v10.17.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 2.1.2

```

**Comment by HansKrywaa** [comment]
From the [Breaking Changes Document](https://github.com/ionic-team/ionic/blob/master/BREAKING.md#toast):

> The close button properties (showCloseButton and closeButtonText) have been removed. Use the buttons array instead with role: 'cancel'

**Comment by liamdebeasi** [comment]
As per the [Breaking Changes Document](https://github.com/ionic-team/ionic/blob/master/BREAKING.md#toast) these properties have been removed in Ionic 5.
