### ISSUE TITLE
bug: ion-segment initial state failed when using NgModel with Angular

### ISSUE THREAD

**Issue by tuif** [ionic-team/ionic#20500]
# Bug Report

**Ionic version:
[x] **5.x**

**Current behavior:**
1. We are using ion-segment in modal with Angular. For connivence, we use NgModel for two-way binding the checked value of ion-segment.

2. When showing the modal for the first time, the ion-segment-button is checked when its value matches the bound variable.
<img width="323" alt="Screen Shot 2020-02-15 at 2 06 41 PM" src="https://user-images.githubusercontent.com/10239308/74583604-add89e00-5003-11ea-9763-68ebbff3b0cc.png">

3. After closing the modal, enter again. The ion-segment-button is not checked even if its value matches the bound variable, leaving all buttons unchecked.
<img width="321" alt="Screen Shot 2020-02-15 at 2 07 53 PM" src="https://user-images.githubusercontent.com/10239308/74583608-b0d38e80-5003-11ea-8046-441e83226fbf.png">

**Expected behavior:**
button is checked when its value equals the bound variable.

**Steps to reproduce:**
1. download code from the following link
2. npm i
3. ionic s

**Related code:**
https://github.com/tuif/ionic5-segment

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 21 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   ios-sim : 8.0.2
   NodeJS  : v12.13.0 (/usr/local/bin/node)
   npm     : 6.13.7
   OS      : macOS Mojave
   Xcode   : Xcode 11.3.1 Build version 11C504
```

**Comment by danielpspring** [comment]
I'm experiencing the same issue using the ion-segment and NgModel. However, it's mixed. Some screens work all the time, some never and some only the first time.

**Comment by danielpspring** [comment]
Here's a sample project with two different segments. The first ion-segment works in the tab1 page (the default tab). The second ion-segment is in the modal screen that is opened via tab1 page. This segment does not work. 

[testTabs.zip](https://github.com/ionic-team/ionic/files/4209792/testTabs.zip)

**Comment by dotocean** [comment]
+1 I have the same problem. On first load my segment buttons correctly show my ngModel, but on second load no segment button is selected.

**Comment by drugoi7** [comment]
Same here.
I have the same problem with different pages and differente segments.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue for you? `5.1.0-dev.202002171727.172ee2d`

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue? `5.1.0-dev.202002171749.5c249d6`

**Comment by danielpspring** [comment]
I installed the dev version and am now getting this error. I've been messing around with my app so I'm not sure if this is something I caused or not.  Do I have to add IonRouterOutlet to the providers as it states?

NullInjectorError: No provider for IonRouterOutlet!

**Comment by danielpspring** [comment]
This appears to have fix the ion-segment issue. I'm still finding other (binding) issues but the segment is now working.

**Comment by dotocean** [comment]
@liamdebeasi Around when is the due date of 5.0.1 milestone?

**Comment by liamdebeasi** [comment]
We don't comment on the timeline of releases, but we do hope to have 5.0.1 out soon.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20495 and will be available in an upcoming release of Ionic Framework.

**Comment by dotocean** [comment]
> We don't comment on the timeline of releases, but we do hope to have 5.0.1 out soon.

Ok I'm sorry, Thanks for the fix!
