### ISSUE TITLE
bug: React IonBackButton redirect to another tab

### ISSUE THREAD

**Issue by AntoninBeaufort** [ionic-team/ionic#20507]
# Bug Report

**Ionic version:**

[x] **5.0.0**

**Current behavior:**

I'm having the following structure :
- Tab1
- Tab2
  - Tab2Details

When I navigate from :
- Tab2
- Tab2Details (by routerLink)
- Tab1 (by click on IonTabButton)
- Tab2Details (by click on IonTabButton)

Then click on the IonBackButton of Tab2Details I'm redirected to Tab 1.

I need something to allow me to handle the back button action by testing the previous page.
I know that I can use a simple routerLink but I need to restore previous page from others tabs but not all tabs, I think I want something like :

> If I came to this page by clicking on something other than the IonTabButton I want my IonBackButton go to this page, else go to the defaultHref.

**Expected behavior:**

I want that my back button redirect only to tabs or subtabs of the same tab, I don't want it to navigate between tabs.

**Steps to reproduce:**

Create a Ionic React project withs tabs and subtabs (with IonBackButton) and then try to reproduce the navigation in the order described above.

**Related code:**

**App.tsx**
``` 
<IonTabs>
            <IonRouterOutlet id="test">
              <Route exact path="/:tab(tab1)" component={Tab1} />
              <Route exact path="/" render={() => <Redirect to="/tab1" />} />
              <Route exact path="/:tab(tab2)" component={Tab2} />
              <Route exact path="/:tab(tab2)/details" component={Tab2Details} />
            </IonRouterOutlet>
            <IonTabBar slot="bottom" color="primary">
              <IonTabButton tab="tab1" href="/tab1">
                <IonIcon icon={flag} />
                <IonLabel>Tab1</IonLabel>
              </IonTabButton>
              <IonTabButton tab="tab2" href="/tab2">
                <IonIcon icon={globe} />
                <IonLabel>Tab2</IonLabel>
              </IonTabButton>
            </IonTabBar>
          </IonTabs>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.1.0 (C:\Users\anton\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.0.0

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res : 0.9.0
   native-run  : 0.3.0

System:

   NodeJS : v12.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.7
   OS     : Windows 10
```

**Comment by elylucas** [comment]
Hi @AntoninBeaufort,

Thanks for the issue. This should be fixed in #20431, which will be in the next patch release in the next couple of days. 

Going to close for now, but if the issue still persists in 5.0.1 let us know.
