### ISSUE TITLE
bug: Ionic 5 - Swipe to Close Modal Animation not working properly in android

### ISSUE THREAD

**Issue by osama-klabs** [ionic-team/ionic#20527]
# Bug Report

**Ionic version:**

[x] **5.0.0**

**Current behavior:**

Swipe to Close Modal animation not working properly in android
 
**Expected behavior:**

should work same as ios, see the video in the below link
https://ionicframework.com/blog/announcing-ionic-5/

**Steps to reproduce:**

- Create new project with angular
- add settings page, delete page router module and update module file with
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

import { IonicModule } from '@ionic/angular';


import { SettingsPage } from './settings.page';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule
  ],
  declarations: [SettingsPage],
  exports: [SettingsPage],
  entryComponents: [SettingsPage]
})
export class SettingsPageModule {}
```
- import and call settings page through modal

**Related code:**

```
async openSettings(){
    const modal = await this.modalController.create({
      component: SettingsPage,
      swipeToClose: true,
      presentingElement: this.routerOutlet.nativeEl
    });
    return await modal.present();
  }
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\sk\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 5 other plugins)

Utility:

   cordova-res (update available: 0.9.0) : 0.6.0
   native-run (update available: 0.3.0)  : 0.2.9

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by HansKrywaa** [comment]
I think it is because Modals in Android are in generally (natively) not SwipeToClosable? https://material.io/components/dialogs/#full-screen-dialog

**Comment by NikolaPeevski** [comment]
According to [the docs](https://ionicframework.com/docs/api/modal#swipeable-modals) the swipe to close only applies to iOS environments.

**Comment by liamdebeasi** [comment]
Thanks for the issue. We try to keep our components as close to the spec as possible. As a result, we currently have no plans to bring the card-style modal to MD mode as it is not part of the Material Design spec.
