### ISSUE TITLE
bug: Sidemenu hidden on large screen when using Microsoft Edge

### ISSUE THREAD

**Issue by DausShukor** [ionic-team/ionic#20526]
Ionic version: 5.0.0

Current behavior: Sidemenu works perfectly on Chrome & Firefox but not on Microsoft Edge. The menu will be totally hide when display on large screen.

Expected behavior: Sidemenu should remain on left/right screen of the split pane when display on large screen

Steps to reproduce:
Using ionic starter sidemenu to reproduce the problem

**Comment by liamdebeasi** [comment]
Thanks for the issue. What version of Microsoft Edge are you using?

**Comment by DausShukor** [comment]
Microsoft Edge 44.18362.449.0

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I am going to close this as Ionic Framework v5 supports Edge 79+ (Chromium-based Edge). This was not properly reflected on the docs site, so I have pushed an update to make that clearer: https://ionicframework.com/docs/intro/browser-support#desktop-browsers. Thanks!
