### ISSUE TITLE
bug: Pause on caught exceptions

### ISSUE THREAD

**Issue by danielpspring** [ionic-team/ionic#20534]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

This is not a specific defect but more of an observation. When running an Ionic project in Chrome with Chrome's debugging option "Pause on caught exceptions" turned on the browser breaks on multiple exceptions. Not sure if this did the same with Ionic 4. 

UPDATE: in my ionic 4 PWA the browser does break on the "no cordova" error which I would expect.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide an example of some of these exceptions?

**Comment by danielpspring** [comment]
Please check out this new issue https://github.com/ionic-team/ionic/issues/20544.
