### ISSUE TITLE
bug: Ionic v5 Ripple effect not disabled on segment component

### ISSUE THREAD

**Issue by molinator84** [ionic-team/ionic#20533]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

Ripple effect on segment button appears even if the ripple effect is disabled on app.module with 'IonicModule.forRoot({rippleEffect: false}),'

Anyway with the css class --ripple-color: transparent; on the ion-segment is disabled correctly.

**Expected behavior:**

Ripple effect should be disabled in the whole application

**Steps to reproduce:**

Just create a app and set the follow configuration on app.module and a segment component on a empty page.

**Related code:**

```
app-module ->

@NgModule({
....
imports: [
    ....
    IonicModule.forRoot({rippleEffect: false}),
    ....
]
....
})

On any page -> 

<ion-segment 
  [(ngModel)]="contractType" 
  (ionChange)="onChange()">
  <ion-segment-button value="electricity" layout="icon-start">
    <ion-icon src="/assets/icons/power-electric.svg"></ion-icon>
    <ion-label>Electricidad</ion-label>
  </ion-segment-button>
  <ion-segment-button value="gas" layout="icon-start">
    <ion-icon src="/assets/icons/power-gas.svg"></ion-icon>
    <ion-label>Gas</ion-label>
  </ion-segment-button>      
</ion-segment> 
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.13
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.21
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 22 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3 (C:\Users\santiago.gallego\AppData\Roaming\nvm\v10.14.2\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

`npm i @ionic/angular@5.1.0-dev.202002181601.7f19ece`

**Comment by molinator84** [comment]
Hello Liam, yes it works correctly now.

Thank you very much.

**Comment by liamdebeasi** [comment]
Glad to hear it is working. I am just going to keep this issue open until the PR has been merged.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20542 and will be available in an upcoming release of Ionic Framework.
