### ISSUE TITLE
bug: Ionic 5 some styles doesn't apply to segment button 

### ISSUE THREAD

**Issue by molinator84** [ionic-team/ionic#20539]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

For example, isn't possible change the border radius of the indicator, but in the documentation it says:
--border-radius: Radius of the segment button border
And seeing the code it only applies to ios mode and it apllies on the 'segment-button-indicator-background' class, but it always have a value of 7px.

**Expected behavior:**

--border-radius: 16px should change the radius of the indicator on ios mode.

**Steps to reproduce:**

Just inspect the code with chrome devtools of your documentation: https://ionicframework.com/docs/api/segment and put '--border-radius: 16px;' on any ion-segment-button and you can see that nothing changes.
**Related code:**

```
element.style {
    --border-radius: 16px;
}
```

**Other information:**

**Ionic info:**

```
You can do a live test it on your own webpage.
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

Angular
`npm i @ionic/angular@5.1.0-dev.202002181548.8e5fd71` 

React
`npm i @ionic/react@5.1.0-dev.202002181548.8e5fd71`

Vanilla JS
`npm i @ionic/core@5.1.0-dev.202002181548.8e5fd71`

**Comment by molinator84** [comment]
Hello Liam, I can try it with the Angular dev build and it works.

Thank you very much,

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20541 and will be available in an upcoming release of Ionic Framework.
