### ISSUE TITLE
bug: ion-datetime: Min and max properties of ion-datetime are not working properly

### ISSUE THREAD

**Issue by ddtch** [ionic-team/ionic#20538]
# Bug Report

**Ionic version:**

[x] 5.4.12

**Current behavior:**

When I set **max** date like current DateTime minus 12 years. I can not choose month higher than current. 
![gif of problem](https://s5.gifyu.com/images/ezgif-6-6a82bdf86bae.gif)

**Expected behavior:**

When I set **max** date like current DateTime minus 12 years. User should be able to choose month higher than current bcs user also can change the year. 

**Steps to reproduce:**

Here is StackBlitz (https://stackblitz.com/edit/ionic-v4-ssjv6n) with bug. All related code there.

**Other information:**
I know this topic related to [#17521](https://github.com/ionic-team/ionic/issues/17521) and [#17060](https://github.com/ionic-team/ionic/issues/17060) But did not find any solution there

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.12 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 0.8.5
   @angular/cli                  : 6.2.5
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 11 other plugins)

Utility:

   cordova-res (update available: 0.9.0) : 0.8.1
   native-run                            : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/dd/Library/Android/sdk)
   ios-deploy        : 2.0.0
   NodeJS            : v12.4.0 (/usr/local/bin/node)
   npm               : 6.13.6
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8



```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This was fixed in Ionic 4.2.0. Please upgrade your version of Ionic.
