### ISSUE TITLE
bug: Error is router.js

### ISSUE THREAD

**Issue by danielpspring** [ionic-team/ionic#20544]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

Not sure if this is an issue but if Chrome's "Pause on caught exceptions" is turned on an error presents itself when navigating between tabs. The error is within router.js method "match$1(segmentGroup, route, segments)".

**Expected behavior:**

Not sure. Without this exception ("Pause on caught exceptions" is turned off) the navigation between tabs seems to work properly.

**Steps to reproduce:**

**Related code:**

[testTabs.zip](https://github.com/ionic-team/ionic/files/4220196/testTabs.zip)

Run "npm i" before running app

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```
<img width="1440" alt="Screen Shot 2020-02-18 at 11 22 26 AM" src="https://user-images.githubusercontent.com/29068962/74755416-2a0bf500-5241-11ea-808b-2e679555554e.png">

**Comment by NikolaPeevski** [comment]
If it's running that should mean the exception is handled correctly? @danielpspring

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you clarify the bug you are running into? It sounds like the bug is originating from Angular Router, and Chrome is pausing on the exception, which would be the correct behavior.

**Comment by danielpspring** [comment]
Sorry for the false alarm. This was my issues. Closing ticket.
