### ISSUE TITLE
bug: Using IonFabButton causes a 404 for close.svg

### ISSUE THREAD

**Issue by schontz** [ionic-team/ionic#20549]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

Using an `IonFabButton` causes a request for `/svg/close.svg`, which does not exist.

**Expected behavior:**

Do not request SVG.

**Steps to reproduce:**

1. `ionic start` a React blank project.
2. Apply the following diff:

```diff
diff --git a/src/components/ExploreContainer.tsx b/src/components/ExploreContainer.tsx
index 0bbb3a9..7d992f7 100644
--- a/src/components/ExploreContainer.tsx
+++ b/src/components/ExploreContainer.tsx
@@ -1,13 +1,26 @@
-import React from 'react';
-import './ExploreContainer.css';
+import React from "react";
+import "./ExploreContainer.css";
+import { IonFab, IonFabButton } from "@ionic/react";
 
-interface ContainerProps { }
+interface ContainerProps {}
 
 const ExploreContainer: React.FC<ContainerProps> = () => {
   return (
     <div className="container">
       <strong>Ready to create an app?</strong>
       <p>Start with Ionic <a target="_blank" rel="noopener noreferrer" href="https://ionicframework.com/docs/components">UI Components</a></p>
+      <IonFab slot="fixed">
+        <IonFabButton>Hi</IonFabButton>
+      </IonFab>
     </div>
   );
 };
```
3. Load it up in the browser and see request for `/svg/close.svg` in Dev Tools.

**Other information:**

**Ionic info:**

```
$ ionic info

Ionic:

   Ionic CLI       : 6.1.0 
   Ionic Framework : @ionic/react 5.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.11.0 
   npm    : 6.11.3
   OS     : macOS Catalina```

**Comment by elylucas** [comment]
HI @schontz 

What do you mean by it doesn't exist? Are you getting a 404 in the dev tools?

The close icon does get loaded with the fab button as its used internally by the component.

**Comment by schontz** [comment]
It 404s (in dev the server returns index.html) because `localhost:3000/svg/close.svg` is not a valid path. The icons loaded via `IonIcon` are all turned into data URLs.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This issue was fixed by https://github.com/ionic-team/ionic/pull/20490 and will be available in an upcoming release of Ionic Framework.
