### ISSUE TITLE
feat: ion-datetime - Allow pickerFormat to show weekday

### ISSUE THREAD

**Issue by qduborper** [ionic-team/ionic#20567]
**Ionic version:**
[x] **4.x**

**Current behavior:**
When selecting a date with ion-datetime it is not possible to see the weekday, thus users need to check a calendar (which shows the weekdays) and select the right date.
The following code does not work as expected, the first DDDD is ignore:
```
<ion-datetime 
    picker-format="DDDD, D MM YYYY" 
    display-format="DDDD MMM D, YYYY" 
></ion-datetime>
```

Screenshot for version 3, same behaviour in 4x:
![26980167-9bd29f94-4d31-11e7-971c-7527570270d4](https://user-images.githubusercontent.com/13855062/74948700-f5dd3380-53fc-11ea-95a5-cdba11dc65b4.png)

**Expected behavior:**
The weekday should be shown next to the date. This would improve a lot the user experience of users that need to know which day of the week the selected is.

Screenshot for version 3, same behaviour in 4x:
![26980174-a1bcb142-4d31-11e7-97b4-c9bae3cf4a4e](https://user-images.githubusercontent.com/13855062/74948732-01305f00-53fd-11ea-97cb-afb322c265c3.png)

**Other information:**
* Related issue not resolved: [https://github.com/ionic-team/ionic/issues/11999](https://github.com/ionic-team/ionic/issues/11999)
* Example on native ios:

![af48349b97f3eac6f398042aed6fe41d501ef68b](https://user-images.githubusercontent.com/13855062/74949061-80259780-53fd-11ea-8f07-c9dc4072f76c.png)

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I have added your request to the main issue/feature request tracker: https://github.com/ionic-team/ionic/issues/16630.
