### ISSUE TITLE
bug: Not able to customise the ion-toggle component.I just want to adjust the height and toggle knob size as well.   

### ISSUE THREAD

**Issue by Sunil509** [ionic-team/ionic#20560]
Hi,

Looking for customisation of the ion-toggle component in ionic 5.I just want to adjust the height and toggle knob size as well.  Please suggest how to achieve this.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20474.
