### ISSUE TITLE
bug: iOS Swipable Modal causing Android to shrink statusbar

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic#20569]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
When enabling swipeToClose + presenting element on a modal, Android toolbar is shrinked into the statusbar.

**Expected behavior:**
It should be as when presentingElement isn't set.

**Steps to reproduce:**
- Configure a modal :
```
  async showEditModal(): Promise<void> {
    const modal: HTMLIonModalElement = await this._modalController.create({
      component: EditHomeModalComponent,
      swipeToClose: true,
      presentingElement: this.routerOutlet.nativeEl
    });

    await modal.present();
  }
```

- Open the modal on Android => The toolbar is in the statusbar
- Remove `presentingElement `property
- Open the modal on Android => The toolbar is fine

**Other information:**
With presentingElement
![swipable](https://user-images.githubusercontent.com/15921402/74956306-32f9f380-5406-11ea-8e72-f41c16c98cca.PNG)

Without presentingElement
![not_swipable](https://user-images.githubusercontent.com/15921402/74956309-342b2080-5406-11ea-8bf8-c3455b879d25.PNG)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.0.2 (C:\Users\YD7A0C5N\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.1
   @angular-devkit/build-angular : 0.900.3
   @angular-devkit/schematics    : 9.0.3
   @angular/cli                  : 9.0.3
   @ionic/angular-toolkit        : 2.1.2

Capacitor:

   Capacitor CLI   : 1.4.0
   @capacitor/core : 1.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.12.1
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

`npm i @ionic/angular@5.1.0-dev.202002201722.65941af`

**Comment by Yohandah** [comment]
@liamdebeasi When I do yarn add @ionic/angular@5.1.0-dev.202002201722.65941af it doesn't find it and ask me for this ? 
![image](https://user-images.githubusercontent.com/15921402/75017363-22409080-548d-11ea-9be2-a37a39e92af2.png)

**Comment by liamdebeasi** [comment]
Try this dev build: `5.1.0-dev.202002211438.65941af`

**Comment by Yohandah** [comment]
@liamdebeasi It's all good, resolved 👍 

Thanks

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20571 and will be available in an upcoming release of Ionic Framework.
