### ISSUE TITLE
bug [ionic 5] : collapsible header sometime it will not show 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic#20578]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

Sometime it is not showing, I have used docs code 
```
<ion-header translucent="true">
  <ion-toolbar>
    <ion-buttons collapse="true" slot="end">
      <ion-button>Click Me</ion-button>
    </ion-buttons>
    <ion-title>Settings</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content fullscreen="true">
  <ion-header collapse="condense">
    <ion-toolbar>
      <ion-title size="large">Settings</ion-title>
    </ion-toolbar>
  </ion-header>
```

**Expected behavior:**

It should show header every time i scroll;

**Steps to reproduce:**

Gist: https://gist.github.com/indraraj26/61620540c4f460dbc6c74b21f8c646bc
1. scroll nearby top again and again

![image](https://user-images.githubusercontent.com/23274631/75026131-6d28cb00-54c2-11ea-8f57-92f3fc6749d1.png)

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
ionic info
[WARN] Detected locally installed Ionic CLI, but it's too old--using global CLI.

Ionic:

   Ionic CLI                     : 5.4.4 (C:\Users\HP\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.0.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : 0.8.1
   native-run  : 0.3.0

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.10.2
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. What version of iOS are you testing this on?

**Comment by indraraj26** [comment]
testing on chrome browser with Iphone x (not real device)
Reproduce step: scroll up and down at top then sometime it will not show header text

**Comment by liamdebeasi** [comment]
What version of iOS are you using though? (iOS 12, iOS 13, etc)

**Comment by indraraj26** [comment]
Here is video: https://youtu.be/qIRsE-z9xy4
```
"Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1"
```

**Comment by liamdebeasi** [comment]
Can you provide some steps to reproduce the issue? I am unable to reproduce the issue in an Ionic starter.

**Comment by indraraj26** [comment]
As you can see on video it is randomly happening, 
Clone this repo : https://github.com/indraraj26/ionic4-starter-tabs-sidemenu/tree/ionic-5
Branch: ionic-5

Step to reproduce:  Scroll again and again at the top, You will see shrink header without text

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Are you testing this on a physical iOS device?

**Comment by indraraj26** [comment]
Anyway lets close this thread since it is working fine in real device but not in emulator or browser.

Thank you
