### ISSUE TITLE
bug: weird space at the top of a toolbar on desktop

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic#20570]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
Since v5 there is a margin at the top of my toolbars when I'm on desktop

**Expected behavior:**
It should be the same as v4 (see screenshots)

**Steps to reproduce:**
- Create Ionic sidemenu starter
- Open it with v4 as a dependency
- Then open it with v5 as a dependency

**Other information:**
Watch above the toolbar

v4
![accueil_desktop](https://user-images.githubusercontent.com/15921402/74957287-a18b8100-5407-11ea-8581-a30f987f2475.png)

v5
![toolbar_margin](https://user-images.githubusercontent.com/15921402/74957288-a2241780-5407-11ea-9572-9e50e173d0dc.png)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.0.2 (C:\Users\YD7A0C5N\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.1
   @angular-devkit/build-angular : 0.900.3
   @angular-devkit/schematics    : 9.0.3
   @angular/cli                  : 9.0.3
   @ionic/angular-toolkit        : 2.1.2

Capacitor:

   Capacitor CLI   : 1.4.0
   @capacitor/core : 1.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.12.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am unable to reproduce this issue using the v5 sidemenu starter.

**Comment by Yohandah** [comment]
Yeah it is a v4 side menu starter upgraded to v5. I’ll link you a repo ASAP.

**Comment by Yohandah** [comment]
Well, I don't know what to say, I just relaunched my project and now it's fine ... I can't reproduce it. Maybe it was related to some cache or something else. Sorry for the issue.
