### ISSUE TITLE
bug: scrollY="false" / --overflow: false on ion-content refresh a view

### ISSUE THREAD

**Issue by rafalschmidt97** [ionic-team/ionic#20582]
# Bug Report

**Ionic version:**

[] **4.x**
[x] **5.x** (TODO: add version 5 to the template)

**Current behavior:**

Hi,
After updating my application from the version 4.7 to 5 I've noticed an annoying bug. Whenever you change a page and then go back it is refreshing the content.

After some investigation I've realised that the problem is correlated with scrollY="false" / --overflow: false. Then I've tried to downgrade to 4.11 and the problem still existed there.

Version with disabled scroll (scrollY="false"):

![](https://user-images.githubusercontent.com/14861637/75042244-c8f55300-54c6-11ea-91f2-b7a1710dad43.gif)

...and without:

![](https://user-images.githubusercontent.com/14861637/75042238-c692f900-54c6-11ea-8322-98536664e462.gif)

**Steps to reproduce:**

- two views where one has disabled scroll and button to move to the second one

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.1
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 21 other plugins)

Utility:

   cordova-res (update available: 0.9.0) : 0.8.1
   native-run (update available: 0.3.0)  : 0.2.9

System:

   Android SDK Tools : 26.1.1 (/Users/rafalschmidt/Library/Android/sdk)
   ios-deploy        : 1.10.0.1234.3
   ios-sim           : 8.0.2
   NodeJS            : v10.16.0 (/usr/local/bin/node)
   npm               : 6.13.0
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?
