### ISSUE TITLE
bug: (Ionic + @ionic/vue) is failing completely in Microsoft Edge

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic#20589]
# Bug Report

**Ionic version:**

[x] **
    "@ionic/core": "4.11.7",
    "@ionic/vue": "0.0.9",
**

**Edge Version:**
Microsoft Edge 44.17763.831.0

**Current behavior:**
There is a white screen on Edge. In Chrome it works perfectly fine.
In Chrome it looks like this
![image](https://user-images.githubusercontent.com/8480351/75086166-0acdda00-5557-11ea-9cdb-ee41666e0f31.png)

In Edge, it looks like this
![image](https://user-images.githubusercontent.com/8480351/75086176-2afd9900-5557-11ea-8372-3bce915c7836.png)

You can notice in Edge everything is in DOM but nothing is visible.
I think Ionic is missing some polyfills to support Edge with vue due to which some JS files are failing and some classes are missing from DOM like Hydrated. 

Edge console is this
![image](https://user-images.githubusercontent.com/8480351/75086184-58e2dd80-5557-11ea-90ad-a0bd5f989172.png)

**Expected behavior:**
It should work just fine as in Chrome.

**Sample project to reproduce it**
https://github.com/stripathix/ionic-demo-for-edge

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as Ionic 5 dropped support for the old version of Microsoft Edge: https://ionicframework.com/docs/intro/browser-support#desktop-browsers. We are only providing critical security patches for Ionic 4 now. Thanks!
