### ISSUE TITLE
bug: ion-backdrop has no styling

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/ionic#20587]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When I add `ion-backdrop` I can't click any element any more because there is no styling for it to hide/disable it.

**Expected behavior:**

I expect that the styling is included in the component itself.

**Steps to reproduce:**

https://stackblitz.com/edit/ionic-tmhupy

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. If you would like to disable the backdrop you can just set `display: none` on it. If you would like to just disable and pointer events, you can set `pointer-events: none` on it.

**Comment by muuvmuuv** [comment]
Yes, sure. But shouldn‘t the backdrop has initial stiles for that? I see that ion-modal has a backdrop as well. Does the modal add the styles? I think it would be nice if the backdrop would provide some minimal functional css since all ionic components has them. Or at least it should be added to the docs, that additional css is needed to get the backdrop working standalone

**Comment by liamdebeasi** [comment]
The `ion-backdrop` component does get initial styles: https://github.com/ionic-team/ionic/blob/master/core/src/components/backdrop/backdrop.scss. `ion-modal` does not add extra styles other than modify the opacity of the backdrop.
