### ISSUE TITLE
feat: Disabling Animation on NavController#pop via options argument

### ISSUE THREAD

**Issue by TLBSoftware** [ionic-team/ionic#20586]
# Feature Request
Adding the ability to disable `NavController#pop` via an options object, this was allowed previously in Ionic v3 but is missing in Ionic v4. Here is a very elaborate analysis of this issue that I have posted on your alls forums with links to the source code. Post Follows

Looks like in the new Ionic v4 the [options](https://ionicframework.com/docs/v3/api/navigation/NavController/#pop) for disabling animation when using
```
this.navController.pop()
```
has unfortunately been removed. However in the source code of the [StackController](https://github.com/ionic-team/ionic/blob/4c8f32fae99db4022aa9dc75187e2f161e8e678e/angular/src/directives/navigation/stack-controller.ts) in its implementation of [pop](https://github.com/ionic-team/ionic/blob/4c8f32fae99db4022aa9dc75187e2f161e8e678e/angular/src/directives/navigation/stack-controller.ts#L135) which is called via `NavController`s [pop](https://github.com/ionic-team/ionic/blob/f94300cbb3403d73803cfa8ec1a4f54d9eb8a47d/angular/src/providers/nav-controller.ts#L131) the framework will eventually use `navigateBackward` and will pass in the [view.savedExtras](https://github.com/ionic-team/ionic/blob/4c8f32fae99db4022aa9dc75187e2f161e8e678e/angular/src/directives/navigation/stack-controller.ts#L158) which should allow someone to disable this pop animation. However these `RouteViews` are created via this controller and are not given an option to be created with these [savedExtras](https://github.com/ionic-team/ionic/blob/4c8f32fae99db4022aa9dc75187e2f161e8e678e/angular/src/directives/navigation/stack-controller.ts#L31)

AND unfortunately I am unable to directly inject the `StackController` into my class to perform this logic myself. Does anyone have a solution here to perform this? I am unable to directly use `navigateBackward` because in edge cases another view is navigated to from this page and added to the history and I don't want to go back in the history but back in the stack.

Thanks.

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
Add pop options to the NavController like in Ionic v3 so we can disable animation on only a single pop and not via the whole app

**Describe Preferred Solution**
being able to pass in options to NavController.pop to modify the animations just like in navigateBackward(which is eventually called via the pop method)

**Related Code**
Ionic v3 link above has the feature request code

**Comment by liamdebeasi** [comment]
Thanks for the feature request. The stack does not manage anything related to the animations, so I do not think it would make sense for the `pop` method to provide animation-related options.

If you need to use `pop`, you can temporarily disable animation on the current router outlet:

```typescript
import { NavController, IonRouterOutlet } from '@ionic/angular';

...

goBack() {
  this.routerOutlet.nativeEl.animated = false;
  this.navCtrl.pop();
}

ionViewDidLeave() {
  this.routerOutlet.nativeEl.animated = true;
}
```

Ideally, you would be able to use `navigateBack` where you can manage the animation directly, but it does not sound like your use case allows for this. Does the solution I provided work for your use case?

**Comment by TLBSoftware** [comment]
@liamdebeasi Yes this does work thank you. I however had to use `this.routerOutlet.animated = false` since typescript will not compile with usages of the private variable `nativeEl`

**Comment by liamdebeasi** [comment]
Ah sorry, I forgot `nativeEl` is public only on v5. I am going to close this as the issue appears to be resolved. Thanks!
