### ISSUE TITLE
feat: Swipeable Modals

### ISSUE THREAD

**Issue by KyDenZ** [ionic-team/ionic#20591]
# Feature Request

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
In my application I want to separate the page in two, a modal part and a page part.
I would like to display information by a simple slide upwards.

**Related Code**
I would like to have the same modal system as Apple in its stock market application

**Additional Context**
![image](https://user-images.githubusercontent.com/7247673/75101193-021de800-55d9-11ea-837c-eb1ca3364502.png)

Thanks

**Comment by HansKrywaa** [comment]
What you mention here is i think the **Drawer** Component, isn't it?. There is already a open PR for it: #20408 - Please read the Comments there for the current state

**Comment by KyDenZ** [comment]
ah I had not seen .. Super thank you
