### ISSUE TITLE
bug: ion-searchbar error icon svg

### ISSUE THREAD

**Issue by Mantaras96** [ionic-team/ionic#20596]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**

When I use the ion-search-bar  i can see error on console 
zone.js:1127 GET http://localhost:8100/svg/arrow-back-sharp.svg 404 (Not Found)
zone.js:1127 GET http://localhost:8100/svg/search-sharp.svg 404 (Not Found)

I have already imported ionicons: 
              {
                "glob": "**/*.svg",
                "input": "node_modules/ionicons/dist/ionicons/svg",
                "output": "./svg"
              },

**Steps to reproduce:**

**Related code:**

      <ion-card-content class="ion-margin">
        <ion-searchbar show-cancel-button="false"></ion-searchbar>
      </ion-card-content>

**Comment by HansKrywaa** [comment]
Which Ionicons Version so you have installed?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you using the latest version of Ionicons (v5)? Certain icons did not exist until v5.
