### ISSUE TITLE
bug [ionic5]: click twice on ion-item will dismiss swipeable modal 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic#20608]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

Click two times little bit fast on ion-item it will close the swipeable modal.
Tested on: Iphone 6 iOS: 12.4.4

**Expected behavior:**

It should not close the modal.

**Steps to reproduce:**

**Related code:**

Repo: https://github.com/indraraj26/ionic4-starter-tabs-sidemenu/tree/ionic-5
Dashboard: Click on first ion-item to open swipeable modal.

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
ionic info

Ionic:

   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 (update available: 0.3.0)

System:

   ios-deploy : 1.9.4
   NodeJS     : v12.13.0 (/usr/local/bin/node)
   npm        : 6.12.0
   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61


```

**Comment by indraraj26** [comment]
Hi @liamdebeasi , Can you please look into this.  This is really strange/weird behaviour.

Thank you

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

`npm i @ionic/angular@5.1.0-dev.202003031524.f64b142`

**Comment by indraraj26** [comment]
Hi @liamdebeasi , Today i left from office will definitely test tomorrow. Also iOS device is in office.

Thank you for your instant solution.

**Comment by tetkosimi** [comment]
Looks good @liamdebeasi !
Thanks!

**Comment by indraraj26** [comment]
Hi @liamdebeasi, This is working great but animation is not working properly now.

Tested on: Iphone 6 iOS: 12.4.4

ISSUE:
1. Parent page -> it doesnt have smooth animation for border-radius.
2. Sometime modal will open without any animation.
3. Sometime modal will overlap parent page.

Reproduce Video: https://youtu.be/RMYudiq9Dlc?t=20

Anyway for this i will create another issue template.

**Comment by liamdebeasi** [comment]
@indraraj26 Is the issue you are reporting only happening on the dev build provided, or is it happening on the latest stable version of Ionic too?

**Comment by indraraj26** [comment]
Hi @liamdebeasi ,

I have tested with your dev build what you have provided as you can see in ionic info for ionic framework version
Link: https://github.com/ionic-team/ionic/issues/20687




> Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?
> 
> `npm i @ionic/angular@5.1.0-dev.202003031524.f64b142`

**Comment by liamdebeasi** [comment]
@indraraj26 I understand that, but what I am trying to understand is whether or not the issue you mentioned in https://github.com/ionic-team/ionic/issues/20608#issuecomment-594384519 occurs in the latest stable version of Ionic Framework. If it occurs in the latest stable version, then that means it is not directly related to the fix in the dev build.

The reason I ask is I would like to get [this fix](https://github.com/ionic-team/ionic/pull/20683) merged into the framework code base.

**Comment by indraraj26** [comment]
Okay i will wait for merge and will directly test on latest ionic version.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20683 and will be available in an upcoming release of Ionic Framework.
