### ISSUE TITLE
bug: ion-slides RTL

### ISSUE THREAD

**Issue by 3alampro** [ionic-team/ionic#20609]
Hello,

ionic 4 slide component do not support RTL right now it was supported on ionic 3 
if I change the html direction from`ltr` to `rtl` the slide component stop sliding to the correct direction 

the Swiper.js do support RTL by adding `dir="rtl"` to the swiper container div and this was supported in ionic 3 but not any more in ionic 4 or ionic 5 

as showing here 
[https://swiperjs.com/demos/#RTL_layout](url) 

kindly can we have this back

Best wishes

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is already possible in Ionic Framework. To use RTL, you need to set `dir="rtl"` on the `body`. Additionally, you can set it on `ion-slides` if you want only the slides component to be RTL.

CodePen example: https://codepen.io/liamdebeasi/pen/GRJrbVW
