### ISSUE TITLE
bug: ionSelect of segment in Ionic 5.0.1 is not working

### ISSUE THREAD

**Issue by happinesszb** [ionic-team/ionic#20618]
I followed the document of segment-button, but ionSelect is not working on Ionic 5.0.1 and the method segmentButtonClicked is not invoked when clicking, but it works on Ionic 4.
I also tested the segment on Huawei Android 8.1, When I click the segment on the phone, the clicked segment is not checked.

**Comment by NikolaPeevski** [comment]
@happinesszb Can  you provide a repository that manages to successfully reproduce the error ? Also can you fill in the bug report template with the required information (eg. Ionic info) ?

**Comment by happinesszb** [comment]
The repository is listed below.
https://github.com/happinesszb/photo-gallery
I just followed the link below to start a test project and the segment works on Ionic 4. When I updated it to Ionic 5.0.1. then the segment button has problems.  Although I can build successfully with ionic serve, the segmentButtonClicked won't be called when clicking the segment button. I also tested the code in Android 8.1, the segment is not working when clicking the segment button.
https://ionicframework.com/docs/developer-resources/guides/first-app-v4/intro

The code is listed below:
<ion-segment>
  <ion-segment-button (ionSelect)="segmentButtonClicked($event)">
    <ion-label>Friends</ion-label>
  </ion-segment-button>
  <ion-segment-button (ionSelect)="segmentButtonClicked($event)">
    <ion-label>Enemies</ion-label>
  </ion-segment-button>
</ion-segment>

segmentButtonClicked(ev: any) {
    console.log('Segment button clicked', ev);
  }

**Comment by NikolaPeevski** [comment]
@happinesszb 
As per [the documentation](https://ionicframework.com/docs/api/segment) use ionChange on the ion-segment to get the click event. The code will look something like this:

```
<ion-segment (ionChange)="segmentButtonClicked($event)">
  <ion-segment-button>
    <ion-label>Friends</ion-label>
  </ion-segment-button>
  <ion-segment-button>
    <ion-label>Enemies</ion-label>
  </ion-segment-button>
</ion-segment>
```

**Comment by happinesszb** [comment]
I followed the link below 
https://ionicframework.com/docs/api/segment-button

<ion-segment>
  <ion-segment-button (ionSelect)="segmentButtonClicked($event)">
    <ion-label>Friends</ion-label>
  </ion-segment-button>
  <ion-segment-button (ionSelect)="segmentButtonClicked($event)">
    <ion-label>Enemies</ion-label>
  </ion-segment-button>
</ion-segment>

segmentButtonClicked can not work in Ionic 5.0.1, but it worked on ionic 4

**Comment by NikolaPeevski** [comment]
Yes in version 4 the segment button emitted a click event but that has been changed in version 5 https://ionicframework.com/docs/v4/api/segment-button

**Comment by happinesszb** [comment]
I see. Thank you..
Although I followed the link the documentation which use ionChange. the segment button has a problem on Android 8.1. When I clicked the segment button, the segment was not checked. I should slide the segment to enable the target segment button. The segment code can work on Android 7.1.

**Comment by liamdebeasi** [comment]
Thanks for the issue and thanks @NikolaPeevski for helping debug the issue. The `ionSelect` event was removed in v5, and developers should use the `ionChange` event instead. Additionally, there is another issue with `ion-segment` on Android, but a fix for that has been merged and will be available in an upcoming release of Ionic Framework.
