### ISSUE TITLE
Cannot to deploy ionic browser to CDN deploy-url doesn't work

### ISSUE THREAD

**Issue by ilprima** [ionic-team/ionic#20616]
Hi to everyone,
I'm trying to upload the build files to my cdn but I cannot set the deploy url, I tried with:

ionic build --platform=browser --optimization --prod --aot --deployUrl=cdn_url

But also with
--deployUrl cdn_url
--deploy-url cdn_url

or also with ionic cordova build browser

But nothing, in index.html the path are relative.

How can I do that?
Thank you

**Comment by NikolaPeevski** [comment]
@ilprima There does not seem to be a deployurl param in the [official build documentation](https://ionicframework.com/docs/cli/commands/build) Can you try following the explained steps [here](https://github.com/angular/angular-cli/issues/10736) and commenting your result ?

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is more of a support request. We use the Angular CLI under the hood, so I recommend looking at the CLI Build documentation: https://angular.io/cli/build. For further help regarding this I recommend posting this question on our [forums](https://forum.ionicframework.com/).
