### ISSUE TITLE
bug: [5.0.1] ion-segment-button event ionSelect not fired

### ISSUE THREAD

**Issue by MrSparklle** [ionic-team/ionic#20611]
# Bug Report

**Ionic version:**

[x] **5.0.1**

**Current behavior:**
Event `(ionSelect)` of `<ion-segment-button>` component has not been fired when the button was clicked

**Expected behavior:**
Event `(ionSelect)` fired

**Related code:**
```
<ion-toolbar no-border-top>
    <ion-segment value="profile">
      <ion-segment-button value="profile">
        <ion-label>Profile</ion-label>
      </ion-segment-button>
      <ion-segment-button value="bookings" (ionSelect)="selectedBookings($event)">
        <ion-label>Bookings</ion-label>
      </ion-segment-button>
      <ion-segment-button value="warnings" (ionSelect)="warnings($event)">
        <ion-label>Warnings</ion-label>
      </ion-segment-button>
    </ion-segment>
  </ion-toolbar>
```

```
export class Tab1Page {
  constructor() {}

  selectedBookings(ev: any) {
    console.log('selectedBookings clicked: ', ev);
  }

  warnings(ev: any) {
    console.log('warning clicked: ', ev);
  }
}
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.1.0 (/Users/joeldaros/.nvm/versions/node/v12.14.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.1
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.14.1 (/Users/joeldaros/.nvm/versions/node/v12.14.1/bin/node)
   npm    : 6.13.7
   OS     : macOS Catalina

```

**Comment by liamdebeasi** [comment]
Please see the [Breaking Changes Document for Segment](https://github.com/ionic-team/ionic/blob/master/BREAKING.md#segment). The `ionSelect` event was removed -- developers should listen for `ionChange` on the `ion-segment` element now.

**Comment by MrSparklle** [comment]
Ok, thanks for the info. 
Please, update the docs.

**Comment by liamdebeasi** [comment]
The documentation has already been updated for v5:

Segment: https://ionicframework.com/docs/api/segment#events
Segment Button: https://ionicframework.com/docs/api/segment-button

Maybe you were looking at the v4 docs by mistake?

**Comment by MrSparklle** [comment]
![image](https://user-images.githubusercontent.com/992049/75257908-736dbe80-57c4-11ea-949a-2f4a1bd92e06.png)

**Comment by liamdebeasi** [comment]
Dangit thanks 😄 I'll fix that
