### ISSUE TITLE
bug: Some ionic UI Components disappear after scrolling,Clicking on iphone X, ios version 13.3 

### ISSUE THREAD

**Issue by sagarnarode** [ionic-team/ionic#20622]
While scrolling the page some times my Options, Checkboxes, Radio button labels and badges disappear.
I am facing this issue only on devices running IOS 13. No problems faced on android as well as the browser.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21168800/75343792-33abe300-5867-11ea-8900-a867467e578a.gif)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?
