### ISSUE TITLE
bug: ion-refresher dismounting style attributes

### ISSUE THREAD

**Issue by elvisgraho** [ionic-team/ionic#20634]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**

If ion-refresher is active (pulled down) and the component using the refresher is dismounted, the main style attributes stay for iternity, which results in permanent content shift.

**Expected behavior:**

When dismounting ion-refresher, all css should be removed from the main tag.

**Steps to reproduce:**
Pull the refresher and dismount the component really fast (go to other route for example).

**Related code:**
When setCss method get's fired on dismounting (in close method) the this.scrollEl and  this.backgroundContentEl are undefined. Which means that we can no longer modify their css (set back changes by ion-refresher)

```
//both are undefined if called on close, especially the this.scrollEl (main tag element)
if (this.scrollEl && this.backgroundContentEl) {
```
```
Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.0.3
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (6 plugins total)

Utility:

   cordova-res : 0.9.0
   native-run  : 0.3.0

System:

   NodeJS : v12.14.1 (/Users/graholskise/.nvm/versions/node/v12.14.1/bin/node)
   npm    : 6.13.4
   OS     : macOS Catalina
   Xcode  : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by elvisgraho** [comment]
> Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

Sorry it wont be anytime soon. I created the pull request and solely from the code you can see that the last calls of setCss (dismounting calls that delete css) are useless, because the object is set to undefined before them.

I had a ion-refresher in the parent component. I polled it -> navigated to child route, and because ion-refresher could not properly dismount, everything was pulled down.
