### ISSUE TITLE
Error when running ionic build --prod

### ISSUE THREAD

**Issue by sachithd** [ionic-team/ionic#20644]
**Ionic version:**

[] **4.x**
[x] **5.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**
ionic build --prod throws an error An unhandled exception occurred: Maximum call stack size exceeded.

Works fine without the --prod flag.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
`
ionic build --prod
> ng run app:build:production
Generating ES5 bundles for differential loading...
An unhandled exception occurred: Maximum call stack size exceeded
See "/tmp/ng-6SoqBf/angular-errors.log" for further details.
[ERROR] An error occurred while running subprocess ng.
        
        ng run app:build:production exited with exit code 127.
        
        Re-running this command with the --verbose flag may provide more information.

```

**Other information:**

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 6.1.0 (/home/sachith/.nvm/versions/node/v12.16.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.1 (/home/sachith/.nvm/versions/node/v12.16.1/bin/node)
   npm    : 6.13.4
   OS     : Linux 5.3

```

**Comment by sachithd** [comment]
Was able to run ionic build --prod successfully by changing  "target": "es2015" to "target": "es5" on tsconfig.json.
https://forum.ionicframework.com/t/ionic-cordova-build-get-stuck-at-generating-es5-bundles-for-differential-loading/180202/4

The default ionic project setting was "es2015" so please advise.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by sachithd** [comment]
It turns out that , one of my functions which has about 650 lines of "text.replace()" methods. causing ionic build --prod to throw this exception.  

I was able to resolve it by writing the function in a different way or when I build it after changing the "target": "es2015" to "target": "es5" on tsconfig.json. (With the es5 method I'm not sure if it can cause issues when run on different devices)

It seems that this is an Angular issue rather than Ionic.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. In that case, I am going to close this issue. If you later determine that this is an Ionic issue please feel free to open a new issue. Thanks! 🙂
