### ISSUE TITLE
bug: @NikolaPeevski am getting blank screen in my ionic serve --lab

### ISSUE THREAD

**Issue by Navanee26** [ionic-team/ionic#20645]
[

# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by Navanee26** [comment]
This version (npm install @ionic/lab@3.0.1) is working, but latest version icons and some other things are not coming in it

**Comment by NikolaPeevski** [comment]
@Navanee26 Can you provide a repo ?

**Comment by Navanee26** [comment]
@NikolaPeevski i can't understand . tell me detaily

**Comment by liamdebeasi** [comment]
@Navanee26 Can you provide a GitHub repo with the code required to reproduce this issue?

**Comment by Navanee26** [comment]
@liamdebeasi  there is no issue with my code. 
if i create new project using ionic start myApp & angular am just getting blank screens for ionic serve --lab.
i am using ubuntu os . i don't have idea about window & ios.
 old version ionic serve --lab is working now.
with that only my project is running

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Is this happening with an Ionic Framework v4 applications as well, or just v5 apps?

**Comment by Navanee26** [comment]
@liamdebeasi everyday i am creating new project to check ionic serve --lab version issue sloved or not but still now its not sloved . i didnt have idea about its v4 or v5.

**Comment by Navanee26** [comment]
@liamdebeasi I am following this link page to create ( https://ionicframework.com/getting-started )

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Unfortunately I am unable to reproduce the issue using the steps you have provided. In your app's directory, can you please provide the output of running `ionic info`?

**Comment by Navanee26** [comment]
@liamdebeasi 
![Screenshot from 2020-03-04 09-19-37](https://user-images.githubusercontent.com/60693254/75843533-602ca580-5df9-11ea-8fb4-9d1224490965.png)

**Comment by Navanee26** [comment]
@liamdebeasi  latest version is not supporting i think in ubuntu

**Comment by Navanee26** [comment]
@liamdebeasi yes i think so
