### ISSUE TITLE
bug: ionic 5.0.4 doesn't use shadow-dom

### ISSUE THREAD

**Issue by pablomaurer** [ionic-team/ionic#20656]
# Bug Report

**Ionic version:**
[x] **5.0.4**

**Current behavior:**
Since version 5.0.4 ionic somehow doesn't create anymore shadow-doms and uses the fallback classes `sc-ion-*`

**Expected behavior:**
Expect to not see any `sc-ion-*` classes and expect to see shadow-doms.

**Steps to reproduce:**
Try to reproduce with version 5.0.4, if this should not work let me know and i will create a demo repository.

**Possible solution**
I would say this happened because of the stencil package update...

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.900.4
   @angular-devkit/schematics    : 9.0.4
   @angular/cli                  : 9.0.4
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 13 other plugins)

Utility:

   cordova-res : 0.9.0
   native-run  : 0.3.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.13.1 (/usr/local/bin/node)
   npm        : 6.14.1
   OS         : macOS Catalina
   Xcode      : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by pablomaurer** [comment]
OK, somebody in out team included the npm package `document-register-element` which conflicted with 5.0.4.
We got rid of it and now it works again, sorry for blaming you 😚
