### ISSUE TITLE
bug: ion-datetime max limitation doesn't work when hour or minute is set to 00

### ISSUE THREAD

**Issue by jiayeZhu** [ionic-team/ionic#20652]
# Bug Report

**Ionic version:**

[x] **5.0.1**

**Current behavior:**

ion-datetime with max limitation doesn't work at hour or minute when the hour or minute is set to 00.
![bug-report](https://user-images.githubusercontent.com/12003141/75569074-6ea64600-5a22-11ea-8d9a-8b3b8ccb4d56.png)

**Expected behavior:**

when the hour or minute of max limitation is 00, the datetime picker should not let users select any other hour or minute but 00.
**Steps to reproduce:**

https://stackblitz.com/edit/ionic-ssg5bc
**Related code:**

```
  <ion-item>
    <ion-label position="floating">Max limitation doesn't work at hour when it's 00 at hour</ion-label>
    <ion-datetime displayFormat="MMM D YYYY H:mm" min="2020-02-27T00:02:27.446-05:00" max="2020-02-28T00:02:27.446-05:00"></ion-datetime>
  </ion-item>
  <ion-item>
    <ion-label position="floating">Max limitation doesn't work at minute when it's 00 at minute</ion-label>
    <ion-datetime displayFormat="MMM D YYYY H:mm" min="2020-02-27T01:00:27.446-05:00" max="2020-02-28T01:00:27.446-05:00"></ion-datetime>
  </ion-item>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.1
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res : 0.9.0
   native-run  : 0.3.0

System:

   NodeJS : v13.9.0 (/usr/local/bin/node)
   npm    : 6.14.1
   OS     : Linux 5.3
```

**PS:**
English is not my native language. I've tried my best to describe and demonstrate the bug. Please let me know if you need any other information.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20665 and will be available in an upcoming release of Ionic Framework.
