### ISSUE TITLE
bug: Scrolling barely works running as android device with chrome inspector open.

### ISSUE THREAD

**Issue by Korthoutrody** [ionic-team/ionic#20659]
So I have not found anything on Google when I ran into this issue, and the issue being so obscure and unthinkable, it took me about 3 hours to fix this with lots of head-on-desk banging in the process.

It seems that using the Google Chrome inspector (to test out scss on elements without reloading) slightly blocks scrolling from working on my mobile application that I run on my android device (no emulator). 

I'm not sure if this is an ionic, browser or android issue. Don't even know how this even is a thing, seeing all functionality is blocked (You can't control the inspector copy of your app directly). Yet for scrolling it does, and destroys it's functionality on the mobile device.

Anyway, figured i'd put this here. Remove if not a bug I suppose!

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is more of a support request. For further help debugging your application, we recommend posting your question on our [forums](https://forum.ionicframework.com/).
