### ISSUE TITLE
Ionic 5 - async in ion-content

### ISSUE THREAD

**Issue by ZehnVon12** [ionic-team/ionic#20651]
I'm using a simple http get request in a service in an Ionic 5 application that returns an Observable. When I use that Observable with an async pipe inside ion-content in a template the ChangeDetection is not working on the data update of the Observable:

```
<ion-content>
  <div *ngIf="data$ | async as data>
    {{data.text}}
  </div>
</ion-content>
```
If I use the async pipe outside ion-content

```
  <div *ngIf="data$ | async as data>
    {{data.text}}
  </div>
  <ion-content>
  </ion-content>
```
the ChangeDetection works fine.

Is there anything (configuration?) I am missing?

**Comment by NikolaPeevski** [comment]
Have you tried to manually force change detection as a workaround ? ChangeDetectorRef.detectChanges() using RxJs, your code should look something like this.service.MyAwesomeRequest().pipe(res => { this.changeDetectorRef.detectChanges(); return res;});

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?
