### ISSUE TITLE
bug [ionic 5]: ion-split-pane is not working correctly for windows platform

### ISSUE THREAD

**Issue by savs90** [ionic-team/ionic#20657]
**Ionic version:**

[x] **4.x**
[x] **5.x**

**I'm submitting a ...** 

[ x] bug report
[ ] feature request

**Current behavior:**

On a newly created ionic 5 project with sidemenu template we add Windows platform. With ionic serve everything is normal and working as expected. When build and run for windows the split-pane is working as expected when the screen width is smaller then the borderline, but when is larger (e.g full screen) the toggle button disappears (as expected) and the side menu remains hidden (not expected).

**Expected behavior:**

When the screen width is larger then the borderline of the split-pane, it should split the screen in two parts. Left for the side menu and right for the content.

**Steps to reproduce:**

1. ionic start
2. choose angular framework
3. set some project name
4. select sidemenu starter template
5. Integrate your new app with Capacitor to target native iOS and Android? - N
6. Ionic cordova platform add windows
7. Are you sure you want to continue? Y
8. Change the line in src\index.html from "<base href=**"/"** />" to "<base href=**"./"** />"
9. Add 
`<platform name="windows">
        <preference name="windows-target-version" value="10.0" />
 </platform>`
to config.xml
9. ionic cordova run windows

**Related code:**

```
none
```

**Other information:**

I have project running under ionic 3.9.2 using split pane component and there it works as expected for all platforms.

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 6.1.0 (C:\Users\Siyan\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : windows 7.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (C:\Android\android-sdk)
   NodeJS            : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. What device are you testing this on?

**Comment by savs90** [comment]
My PC is running Windows 10 Pro Version 1903 (OS Build 18362.657). I can also confirm that this bug is presented on ionic v4.x also

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Are you building a Universal Windows Platform (UWP) app? Or are you running this app in a browser?

**Comment by savs90** [comment]
Sorry for not specifying, but I supposed it was clear from the reproduce steps - "6. Ionic cordova platform add windows". I am building UWP app. Also i missed one step ( i will edit the original description ) where i'm adding 
`<platform name="windows">
        <preference name="windows-target-version" value="10.0" />
 </platform>`
to config.xml

PS. I updated windows and now i get 
`No valid MSBuild was detected for the selected target: Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild: Command failed with exit code 1` . I will have to check what is going on

**Comment by savs90** [comment]
Because i will not have access to my computer next 2 weeks i have to use another one. I set up the same environment and the result is the same. Split-pane is not working corectly for UWP. Also one more note to make. When the width is under the borderline and we have the toggle button enabled the animation is not working correctly. Opening the side menu with gesture is hanging the animation in the begining.

**Comment by rehannawab** [comment]
@savs90 I don't know if this helps but we also faced the same issue until we realized that Ionic 5 isn't supported on Edge Browser, which a Windows UWP uses (EdgeHTML) for webview. So as long as we have clients using our Windows app, we cannot upgrade to Ionic 5 - at least until we have a Chromium based Webview for building UWP - but that also would require the clients to have latest Edge (v79+) installed on their windows.

Chromium based webview (Webview2) - 
https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes

**Comment by savs90** [comment]
@rehannawab I don`t think the problem with Split pane has something to do with the browser engine. After some debuging i can see that in browser platform for exmaple when a splitscreen trigger happens some classes and styles are altered , and this is only half true for windows. Adding some CSS can fix this bug. But this is temporary workaround until offical fix is released.
Adding this in the scss page where we have split screen fix it for UWP ( at least in a fresh application ):
`
.menu-pane-visible {
  display: flex;
  position: relative;
}

ion-router-outlet {
  display: flex;
  position: relative;
  flex: 1;
}
`

I`m not sure if this is not breaking something else or if it is okey for all other platforms.
@liamdebeasi can we have some input about this problem? Did someone already tried to reproduce it ? Thanks

**Comment by liamdebeasi** [comment]
@savs90 Does your app work in the latest version of Microsoft Edge (v80 I believe)? The Microsoft team switched over to using the Chromium engine for their browser, so the engine could actually be the main difference here.

**Comment by savs90** [comment]
I had Edge v44 installed. I installed v80 now and created a new project and the result is the same. I`m not sure if i have to do anything else except installing the new edge (some settings update) ?

**Comment by liamdebeasi** [comment]
The installation of Microsoft Edge that you have on your computer is not related to the engine that your UWP apps run.

It looks like UWP apps are stuck on EdgeHTML for now, but Microsoft has plans to support an updated webview powered by Chromium-based Edge: https://blogs.windows.com/msedgedev/2019/06/18/building-hybrid-applications-with-the-webview2-developer-preview/

I am going to close this as there is nothing actionable on our end. Thanks!
