### ISSUE TITLE
bug: IonTabBar Not Setting Button As Active On First Render After A Redirect

### ISSUE THREAD

**Issue by brandonhudson** [ionic-team/ionic#20667]
# Bug Report

**Ionic version:**

[x] **5.0.3**

**Current behavior:**
When loading an Ionic React app that uses the router in conjunction with a tab bar, the correct component renders, but the tab bar never updates the current tab to an "active" state (colored) until I tap on the tab manually. This appears to be a regression from v4, as the same code (provided below) showed the first tab activated/colored correctly.

("For You" should be active in the screenshot below)

![IMG_0837](https://user-images.githubusercontent.com/3893578/75654062-d4661e00-5c2c-11ea-9332-a34ccd9f6270.jpg)

**Expected behavior:**
When using a tab bar, the first tab should be colored as the active tab when the redirect occurs.

**Related code:**
Example from my project.
```javascript
...

render() {
    return (
      <IonTabs>
        <IonRouterOutlet>
          <Redirect exact path="/root" to="/root/home" />
          <Route
            path="/root/home"
            render={() => <HomeTab></HomeTab>}
            exact={true}
          />
          <Route
            path="/root/account"
            render={() => <AccountTab></AccountTab>}
            exact={true}
          />
          <Route
            path="/root/learn"
            render={() => <LearnTab></LearnTab>}
            exact={true}
          />
          <Route path="/root/learn/videos/:id" component={Video} />
          <Route path="/root/learn/categories/:id" component={Category} />
        </IonRouterOutlet>
        <IonTabBar slot="bottom" translucent={true}>
          <IonTabButton tab="home" href="/root/home">
            <IonIcon icon={reader} />
            <IonLabel>For You</IonLabel>
          </IonTabButton>
          <IonTabButton tab="learn" href="/root/learn">
            <IonIcon icon={school} />
            <IonLabel>Learn</IonLabel>
          </IonTabButton>
          <IonTabButton tab="account" href="/root/account">
            <IonIcon icon={person} />
            <IonLabel>Account</IonLabel>
          </IonTabButton>
        </IonTabBar>
      </IonTabs>
    );
  }

```

**Other information:**
It's worthwhile to note that this design pattern is directly from the reference [here](https://github.com/ionic-team/ionic-react-conference-app/blob/master/src/pages/MainTabs.tsx#L17) in a sample project.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.1.0 (/Users/brandonhudson/.nvm/versions/node/v11.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.0.3

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v11.15.0 (/Users/brandonhudson/.nvm/versions/node/v11.15.0/bin/node)
   npm    : 6.13.6
   OS     : macOS Catalina
```

**Comment by brandonhudson** [comment]
Any status updates on this? Thanks!

**Comment by elylucas** [comment]
Hi @brandonhudson 

Sorry about the late delay on this issue. I tried to recreate the issue and had a route from '/' forward to a route on a tabs, and it highlighted the icon properly for me. Could you try updating to the latest @ionic/react and @ionic/react-router and try again? If its still an issue, could you provide a reproduction either via a github repo or a stackblitz?

Thanks

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
