### ISSUE TITLE
on-hold doesn't work for even iteration in mobile app

### ISSUE THREAD

**Issue by 0stephen9980** [ionic-team/ionic#20666]
**Ionic version:**

[x] **4.x**
[ ] **5.x**

**I'm submitting a ...** 

[ ] bug report
[ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by NikolaPeevski** [comment]
@0stephen9980 Can you give a little bit more information regarding the issue and a repo for reproduction?
