### ISSUE TITLE
bug: ion-datetime time picker isn't consistent 

### ISSUE THREAD

**Issue by Et3rnal** [ionic-team/ionic#20664]
# Bug Report

**Ionic version:**
IONIC Angular 4.7.1

**Current behavior:**
If the ion-datetime has value, then it will return a string, if It doesn't it will return ISO!

The first will always return string `HH:mm`, the second will return iso datetime because it doesn't have value to start with

**Expected behavior:**
As much as I would love to be able to get the selected value in the display format, but this isn't consistent and causing issues and requires me to do extra checking.

**Related code:**
https://stackblitz.com/edit/ionic-v4-angular-time-picker-issue

```
<ion-datetime displayFormat="HH:mm" value="21:05" (ionChange)="timeChanged($event)"></ion-datetime>
<ion-datetime displayFormat="HH:mm" (ionChange)="timeChanged($event)"></ion-datetime>
```

**Comment by NikolaPeevski** [comment]
@Et3rnal Instead of passing a string like this, pass an actual ISO to the value property and it will consistently output an ISO format value. As the [docs](https://ionicframework.com/docs/api/datetime) state, the value should be of a correct ISO format.

**Comment by Et3rnal** [comment]
Okay so the documents do say that and this case effect dates as well:

> Any of the ISO formats below can be used, and after a user selects a new value, Ionic will continue to use the same ISO format which DateTime value was originally given as

This is useless unless you always have a value to start with. 
It would be really nice to be able to set the desired output of the component

thank you
