### ISSUE TITLE
bug:  stacked navigator don't work correctly

### ISSUE THREAD

**Issue by hongquan09dth5** [ionic-team/ionic#20660]
I have 4 pages and 1 menu as below:
- Dashboard : routerLink="/dashboard" routerDirection="forward"

- Time: routerLink="/time" routerDirection="forward"

- Timesheet: routerLink="/timesheet" routerDirection="forward"

- Payslip: routerLink="/payslip" routerDirection="forward"

When i click those item menu as steps: 
dashboard -> time -> timesheet -> payslip.
Then i try to click the ion-back-button on these page, it navigate back well as:
payslip -> timesheet -> time -> dashboard

The problem is when i clicked the menu item as steps below:
dashboard -> time -> timesheet -> payslip -> time
It seem to remove two stacked navigator timesheet and payslip, so now i try to click ion-back-button it will ignore timesheet and payslip page. It will nevigate time page back to dashboard page. I expect the back button should return as:
time -> payslip -> timesheet-> time -> dashboard

Here is the stacked page when i clicked at payslip steps: dashboard -> time -> timesheet -> payslip 
![FB_IMG_1583080218471](https://user-images.githubusercontent.com/10461288/75629432-ad035700-5c14-11ea-8e8d-3c3b5da9db4c.jpg)
 And here is stacked page when i continues to click "time" menu item again:
![FB_IMG_1583080332924](https://user-images.githubusercontent.com/10461288/75629473-f358b600-5c14-11ea-802f-08eabb46dc0e.jpg)
 It's missing stacked timesheet and payslip page
I'm using the ionic@lastest. Sorry, I'm posting by my phone because my laptop have a problem i can't give more information, i will update later but i really thank you if you help me. I'm searching for 3 days. THANKS

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?
