### ISSUE TITLE
Latest ionic 5 design updates do not work with stencil/vanilla JS apps

### ISSUE THREAD

**Issue by cambronjay** [ionic-team/ionic#20675]
**Stencil version:**

```
 @stencil/core@1.8.11
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Latest design update for iOS do not appear the same way in stencil/vanilla JS apps as they do for angular apps. For example larget titles and swipe to close modals etc.
**Expected behavior:**

The latest design/feature updates work for a stencil/vanilla JS app.
**Steps to reproduce:**

Create a stencil app and install the latest @ionic/core and then make a sample component with a large title. Run the app in chrome and use the developer tools to fake an iOS device. 
**Related code:**

```tsx
            <ion-header collapse="condense">
                <ion-toolbar>
                    <ion-title size="large">Profile</ion-title>
                </ion-toolbar>
            </ion-header>
```

**Other information:**

https://ionicframework.com/blog/announcing-ionic-5/
![stenciljs(iPhone X)](https://user-images.githubusercontent.com/10892549/75601723-f2484d00-5a8b-11ea-86c8-59972345f170.png)
![angular(iPhone X)](https://user-images.githubusercontent.com/10892549/75601724-f3797a00-5a8b-11ea-9a2f-8c3df0922aec.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am unable to reproduce the issue using the code snippet provided.

**Comment by cambronjay** [comment]
@liamdebeasi Use the ionic stencil conference app repo. This is a stenciljs/ionic app issue not an angular/ionic app issue. It's not reproducible in an angular project. That is the point I am making.  https://github.com/ionic-team/ionic-stencil-conference-app use that repo and upgrade the ionic core package.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I am unable to reproduce this issue using the Ionic Stencil Conference App. Can you please provide a repo with the code required to reproduce this issue?

**Comment by brandyscarney** [comment]
The code provided in the original issue is displaying an accurate toolbar, but it looks like you may be missing the header that goes on top of the content. The Stencil conference app hasn't been updated to Ionic 5 yet, so the usage in that app does not reflect the proper large title usage.

Please verify that you are following the usage examples here, notice that there are two `ion-header` elements: https://ionicframework.com/docs/api/title#collapsible-large-titles

If this doesn't solve the problem please provide more code or a repo as Liam requested, thank you!
