### ISSUE TITLE
bug: ionic 5 -  Native: tried calling...

### ISSUE THREAD

**Issue by ctfrancia** [ionic-team/ionic#20671]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

getting a series of `Native: tried calling (StatusBar.statusDefault/Spashscreen.hide()/Android Permissions) but Cordova is not available. Make sure to include cordova.js or run in a device/simulator. I am running this on a native device.

**Expected behavior:**

not to get these errors as they are causing side effects especially when `this.platform.is('cordova')` is returning false.
**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 6.1.0 (/Users/me/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 17 other plugins)

Utility:

   cordova-res : 0.9.0
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/me/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v13.8.0 (/usr/local/Cellar/node/13.8.0/bin/node)
   npm               : 6.13.7
   OS                : macOS Mojave
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is `cordova.js` being included in your output bundle's HTML file?

**Comment by ctfrancia** [comment]
I don't know, I wasn't having this issue before I upgraded to v5. so maybe in the upgrade someone got changed? How would I check for this?

**Comment by liamdebeasi** [comment]
You can either just check Web Inspector to see if it is getting loaded. Ionic Framework does not manage Cordova dependencies, so it is likely something is wrong in the build process.

**Comment by ctfrancia** [comment]
In that case it is not, anything related to the cordova is not getting loaded/called

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you provide a repo with the code required to reproduce this issue?

**Comment by ctfrancia** [comment]
Sure, I will do that, it might be after the weekend, as I am sick and unable to think straight

**Comment by ctfrancia** [comment]
So I the error comes when I launch on android with `$ ionic cordova run android --device --livereload` with ionic 4.x this was never an issue, but, now with ionic 5.0.4 it appears that it is not being compiled correctly?

**Comment by liamdebeasi** [comment]
Ah ok that's good to know. This might be an issue with https://github.com/ionic-team/angular-toolkit instead. Ionic Framework does not manage including Cordova in your apps. 

There was an older issue with `cordova.js` not being included. I would ensure you have the latest version of `@ionic/angular-toolkit` installed. If the issue persists, I would recommend opening an issue on the repo I linked to. Thanks!
