### ISSUE TITLE
bug: Ionic 5 ion-refresher only works once in Android devices

### ISSUE THREAD

**Issue by ondergur** [ionic-team/ionic#20670]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

In Android devices `<ion-refresher>` only works once. 
I encounter with this in Android 10 emulator and Android 8 and 7 physical devices.

**Expected behavior:**

Before migrating to Ionic5 from 4, I was able to pull the refresher at any frequency. Bu now, I can only pull it once. Than I have to go to any other page then get back to the page with refresher (probably unmount and mount the page) to work it again.

**Ionic info:**

```

   Ionic CLI       : 5.4.9 (/usr/local/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 5.0.0

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.0 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Catalina

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by ondergur** [comment]
It's going to take time to reproduce for me because my current repo is belongs to my company which is confidential. I can provide a repo in few days to reproduce i hope. But until that time, what i did was just `<ion-refresher>` inside a `<ion-content>`

**Comment by liamdebeasi** [comment]
Ok thanks. I will keep the `needs: reply` label until a reproduction is provided.

**Comment by ondergur** [comment]
I try to reproduce the bug. But it was working fine in a new project. So you can close the issue. I think bug is in my code.
