### ISSUE TITLE
bug [ionic5]: Swipeable Modal animation and overlap on parent page (border-radius transition).

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic#20687]
# Bug Report

**Ionic version:**

[] **4.x**
[x] **5.x**

**Current behavior:**

Tested on: Iphone 6 iOS: 12.4.4

ISSUE:
1. Parent page -> it doesnt have smooth animation for border-radius.
2. Sometime modal will open without any animation.
3. Sometime modal will overlap parent page.

Reproduce Video: https://youtu.be/RMYudiq9Dlc?t=20

**Expected behavior:**

Parent page -> should have smooth animation for border-radius.
Everytime i open modal it should have animation.
It should not overlap parent page 
**Steps to reproduce:**

**Related code:**

Repo: https://github.com/indraraj26/ionic4-starter-tabs-sidemenu/tree/ionic-5
Dashboard: Click on first ion-item to open swipeable modal.

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
ionic info

Ionic:

   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.1.0-dev.202003031524.f64b142
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 (update available: 0.3.0)

System:

   ios-deploy : 1.9.4
   NodeJS     : v12.13.0 (/usr/local/bin/node)
   npm        : 6.12.0
   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61


```
https://github.com/ionic-team/ionic/issues/20608

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide some clarification regarding the performance issues you are seeing? I am testing your repo on an iPhone 5s on iOS 12.4 and do not see the behavior you are reporting.

**Comment by indraraj26** [comment]
Hi @liamdebeasi  , Sometime i do not see parent page animation (border-animation transition) as you can see in video.

Reproduce Video: https://youtu.be/RMYudiq9Dlc?t=20

Lets wait for other to comment regarding this animation issue.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I understand the issue regarding the animation; however, I am unable to reproduce the issue. Can you double check the repo you have provided to ensure that it reproduces the issue?

**Comment by indraraj26** [comment]
https://github.com/ionic-team/ionic/issues/20851
