### ISSUE TITLE
bug: footer not show in modal using stencil

### ISSUE THREAD

**Issue by edy-ap** [ionic-team/ionic#20693]
# Bug Report

**Ionic version:**
[x] **5.0.4**

**Current behavior:**
when using ionic with stencil, if I put a list and a footer inside a modal, the footer not displayed.
![image](https://user-images.githubusercontent.com/13421021/75933249-19619e80-5e3f-11ea-803b-b20d3407da8e.png)

**Expected behavior:**
the footer is shown in modal

**Steps to reproduce:**
1.- clone the repo
2.- npm i && npm start
3.- click on "Open modal"

**Related code:**
```tsx
<Host>
        <ion-header>
          <ion-toolbar>
            <ion-title slot="start">Modal</ion-title>
          </ion-toolbar>
        </ion-header>
        <ion-content>
          <ion-list>
            <ion-item>
              <ion-label>Gender</ion-label>
              <ion-select placeholder="Select One">
                <ion-select-option value="f">Female</ion-select-option>
                <ion-select-option value="m">Male</ion-select-option>
              </ion-select>
            </ion-item>
          </ion-list>
        </ion-content>
        <ion-footer>Footer</ion-footer>
  </Host>
```

https://github.com/edy-ap/stencil-ionic-modal

**Other information:**
Stencil: "@stencil/core": "^1.8.8"

**Ionic info:**
```
Ionic:

   Ionic CLI : 5.2.3

Utility:

   cordova-res : not installed
   native-run  : 0.2.8

System:

   NodeJS : v12.6.0
   npm    : 6.13.7
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. It looks like your app does not include a lot of the global styles required to make Ionic work properly. Can you make sure those are included and see if the issue persists? You see the global styles in our Ionic Stencil Conference App repo: https://github.com/ionic-team/ionic-stencil-conference-app/blob/master/src/global.css

**Comment by edy-ap** [comment]
thanks , for your answer. That was the solution, I forgot to add the styles.
you do a very good job with ionic.
