### ISSUE TITLE
bug: Cannot create modal with subnavigation in childpages using ion-nav

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic#20699]
# Bug Report

**Ionic version:**

[x] **^5.0.4**

**Current behavior:**

When you try to create a modal with subnavigation using ion-nav, you'll get an error in childpages. Using subnavigation in app.component.ts is working fine.

<img src="https://i.imgur.com/J1pg1HC.png">

**Expected behavior:**

Modal should appear in child pages
**Steps to reproduce:**

1. create a page which holds the ion-nav component and expects the component as input in .html file
```
<ion-nav [root]="component"></ion-nav>
```
2. set in the .ts file an input property for the component
```
@Component({
  selector: 'app-modal-outlet',
  templateUrl: './modal-outlet.page.html',
  styleUrls: ['./modal-outlet.page.scss'],
})
export class ModalOutletPage implements OnInit {

  @Input() component;

  constructor() { }

  ngOnInit() {}
}
```
3. create the modal using modalController in any component except app.component.ts
```
  public async onOpenModal() {
    const modal = await this.modalController.create({
      component: ModalOutletPage,
      componentProps: { component: Test2Page },
    });
    return await modal.present();
  }
```
4. Open the modal
```
<ion-button (click)="onOpenModal()">
        NESTED CHILD NAVIGATION BUG
      </ion-button>
```

[Link to repo](https://github.com/DwieDima/ionic-multiple-modal-bugs)

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.900.5
   @angular-devkit/schematics    : 9.0.5
   @angular/cli                  : 9.0.5
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.0 (/usr/local/bin/node)
   npm    : 6.13.4
   OS     : macOS Catalina
```

**Comment by DwieDima** [comment]
If you'll use the repo:
1. navigate to inbox page
2. click on the button bottom right "NESTED CHILD NAVIGATION BUG"
3. see the error message in console

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo again? It looks like the repo linked in the original post no longer exists.
