### ISSUE TITLE
bug: Modal dismiss animation not smooth on latest ionic/angular

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic#20697]
# Bug Report

**Ionic version:**

[x] **^5.0.4**

**Current behavior:**

Dismiss animation is flickering at the end of transition

[Link to video](https://i.imgur.com/0qvnvDw.mp4)

**Expected behavior:**

Dismiss animation should close smoothly
**Steps to reproduce:**
Just setup new ionic project using latest ionic and angular version (using Angular 9.0.2 at the moment)

[Link to repo](https://github.com/DwieDima/ionic-multiple-modal-bugs)

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.900.5
   @angular-devkit/schematics    : 9.0.5
   @angular/cli                  : 9.0.5
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.0 (/usr/local/bin/node)
   npm    : 6.13.4
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide some more information as to what device you are testing this on? Also the image/gif you tried to provide appears to be broken.

**Comment by DwieDima** [comment]
> Thanks for the issue. Can you provide some more information as to what device you are testing this on? Also the image/gif you tried to provide appears to be broken.

Sorry for broken gif. I replaced it by video link.
In the video i'm testing it on chrome browser.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

`npm i @ionic/angular@5.1.0-dev.202003051530.531d9e4`

**Comment by DwieDima** [comment]
> Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?
> 
> `npm i @ionic/angular@5.1.0-dev.202003051530.531d9e4`

I get following error message by npm:
```
anon@anons-macbook-pro ionic-multiple-modal-bugs-master % npm i @ionic/angular@5.1.0
-dev.202003051530.531d9e4
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @ionic/angular@5.1.0-dev.202003051530.531d9e4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dimitrikreik/.npm/_logs/2020-03-05T15_40_03_069Z-debug.log
```

**Comment by liamdebeasi** [comment]
Try this dev build: `5.1.0-dev.202003051551.531d9e4`.

**Comment by DwieDima** [comment]
Works! Thanks a lot! 👍
