### ISSUE TITLE
bug: Can't submit ANDROID KEYSTORE

### ISSUE THREAD

**Issue by mfragale** [ionic-team/ionic#20695]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Trying to upload my ANDROID KEYSTORE at https://dashboard.ionicframework.com/app/aea1c241/build/certs but get this error:

There was an error while submitting your credentials. Invalid keystore file. The file is not a valid keystore.

**Expected behavior:**

The keystore should be uploaded.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this repo is used only for reporting issues related to Ionic Framework. For help with this issue I recommend posting your question on our [forums](https://forum.ionicframework.com/).
