### ISSUE TITLE
bug: IE11 toolbar background color not changeable

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [ionic-team/ionic#20705]
# Bug Report

**Ionic version:**
[x] **4.11.10**

**Current behavior:**

**Expected behavior:**
When changing the background color of the toolbar, its should also have this color in IE11.

**Steps to reproduce:**
Change the toolbar background color (as described in the documentation) by applying following code in your CSS.

**Related code:**
```
ion-toolbar {
     --background: transparent !important;
     --ion-color-base: transparent !important;
 }
```
The toolbar color changes everywhere (android, chrome, firefox etc) except IE11.

**Other information:**

I tried workarounds like setting the background colour directly via a selector. This also gets ignored in IE11.
```
ion-toolbar .toolbar-background {
      background: transparent !important;
}

```
**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.17
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 9 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 0.3.0) : 0.2.9

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as we recently released Ionic Framework v5 which dropped support for IE11 and older versions of Edge. Moving forward, Ionic Framework v4 will only receive critical security patches.
