### ISSUE TITLE
bug: Swipeable iOS Modal not appearing in Firefox

### ISSUE THREAD

**Issue by mariusbolik** [ionic-team/ionic#20706]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

Only the Backdrop shows, but not the Modal.
<img src="https://i.imgur.com/y2s0NQF.gif" width="250px">

**Expected behavior:**

Modal should display like in Chrome.

**Steps to reproduce:**

I created this simple demo project: https://github.com/mariusbolik/ionic-5-swipeable-modal
Clone it, run `npm i` and open it in Firefox.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

`npm i @ionic/angular@5.1.0-dev.202003061445.314dbb1`

**Comment by mariusbolik** [comment]
Thank you Liam! Now the Modal appears in Firefox. But seems like the Backdrop is gone :(

**Comment by liamdebeasi** [comment]
Can you try this dev build and let me know if it is fixed? `5.1.0-dev.202003061708.08b6eca`

**Comment by mariusbolik** [comment]
Really good work. The Backdrop is showing. Thank you very much!
There is on small thing that would make the Modal perfect: On the iPad the Header of the normal Modal doesn't fade out correctly. This occurs in all browsers.

<img src="https://i.imgur.com/Myn51Kd.gif">

**Comment by liamdebeasi** [comment]
I fixed that yesterday 😄 https://github.com/ionic-team/ionic/pull/20702

Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20714 and will be available in an upcoming release of Ionic Framework.
