### ISSUE TITLE
bug: HttpClientModule has not been processed correctly by ngcc, Http module failed to import in Ionic v5.0.4 with Angular Core v9.0.5

### ISSUE THREAD

**Issue by edocbuhtig** [ionic-team/ionic#20716]
# Bug Report

**Ionic version:**

[x] **5.x**

**Steps to reproduce:**

I am trying to import 
```
import { HttpClientModule } from '@angular/common/http';'
```
 in app.module.ts and later in 
```
imports: [
    BrowserModule, 
    HttpClientModule,
    IonicModule.forRoot(), 
    AppRoutingModule
  ],
```
and there is a bug 
```
ERROR in node_modules/@angular/common/http/http.d.ts:2801:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
[ng]     
[ng]     This likely means that the library (@angular/common/http) which declares HttpClientModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
[ng]     
[ng]     2801 export declare class HttpClientModule {
```

**Ionic info:**

```
My Ionic App Package.json

"dependencies": {
    "@angular/common": "~9.0.5",
    "@angular/core": "~9.0.5",
    "@angular/forms": "~9.0.5",
    "@angular/platform-browser": "~9.0.5",
    "@angular/platform-browser-dynamic": "~9.0.5",
    "@angular/router": "~9.0.5",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.4",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.1",
    "tslib": "^1.10.0",
    "woocommerce-api": "^1.5.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.5",
    "@angular/cli": "~9.0.5",
    "@angular/compiler": "~9.0.5",
    "@angular/compiler-cli": "~9.0.5",
    "@angular/language-service": "~9.0.5",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.7.5"
  }

```

**Comment by NikolaPeevski** [comment]
@edocbuhtig Can you provide a repo ?

**Comment by edocbuhtig** [comment]
@NikolaPeevski - Please review similar unresolved issue https://github.com/angular/angular/issues/35747

**Comment by NikolaPeevski** [comment]
@edocbuhtig So that's not an explicit  **ionic** bug, it's just an issue with angular ? This means this is closable.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this does not appear to be a bug in Ionic Framework. If you have determined that this is a bug in the framework, please provide a repo that reproduces the issue. Thanks!

**Comment by FelipeChaconn** [comment]
These issue is from Angular no from Ionic

**Comment by samivic** [comment]
Try
npm cache clean --force

**Comment by christianemmanuel** [comment]
Thanks @samivic it's seem work from my end :)

**Comment by gdevkate34** [comment]
ERROR in node_modules/@angular/common/http/http.d.ts:81:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/common/http) which declares HttpClient has not been processed correctly by ngcc, or
is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

81 export declare class HttpClient {
                        
Help

**Comment by shemian** [comment]
> npm cache clean --force

what does this command do coz i am not sure about it

**Comment by samivic** [comment]
> > npm cache clean --force
> 
> what does this command do coz i am not sure about it

clean: Delete all data out of the cache folder.

**Comment by edocbuhtig** [comment]
@shemian There are two options:

```npm cache verify```
Verifies the contents of the cache folder, garbage collecting any unneeded data, and verifying the integrity of the cache index and all cached data.

```npm cache clean --force``` 
delete the entire cache. Please note, --force is a mandatory parameter, post npm v5. if you try to run npm cache clean without --force parameter, an error message will be shown.
