### ISSUE TITLE
bug: Cannot run CSS Keyframes animation on safari 13

### ISSUE THREAD

**Issue by weyuan989** [ionic-team/ionic#20719]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Keyframes animation is able to perform normally on any browser and android phones, but not in ios and safari 13.

**Expected behavior:**
Should be able to run keyframes animation on ios and safari 13 as well.

**Steps to reproduce:**
Create any ionic test project and copy paste the given related code.

**Related code:**

```
<div class="fill">
  <svg width="200%" height="100%" viewBox="0 0 240 140" version="1.1">
    <defs>
      <linearGradient x1="50%" y1="0%" x2="50%" y2="100%" id="linearGradient-1">
        <stop offset="0%"></stop>
        <stop offset="50%"></stop>
      </linearGradient>
    </defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
      <g id="widget-copy-2" fill="url(#linearGradient-1)">
        <g id="wave-copy" transform="translate(0.000000, 1.000000)">
          <path
            d="M0,140 L0,2.59259259 C0,2.6670255 28.08,-4.12156133 66,3.88888889 C83.6331044,8.10263543 102,6.61060503 120,2.59259259 L120,140 L0,140 Z M120,140 L120,2.59259259 C120,2.6670255 148.08,-4.12156133 186,3.88888889 C203.633104,8.10263543 222,6.61060503 240,2.59259259 L240,140 L120,140 Z"
            id="waveShape"></path>
        </g>
      </g>
    </g>
  </svg>
</div>
```

```
.fill {
    animation-name: fillAction;
    animation-timing-function: cubic-bezier(0.2, 0.6, 0.8, 0.4);
    animation-duration: 2s;
    animation-fill-mode: forwards;
  }
  #waveShape {
    animation-name: waveAction;
    animation-iteration-count: infinite;
    animation-timing-function: linear;
    animation-duration: 1.7s;
    width: 100%;
    height: 100%;
  }
  @-webkit-keyframes fillAction {
    0% {
      transform: translate(0, 90px);
    }
    100% {
      transform: translate(0, 0px);
    }
  }
  
  @-moz-keyframes fillAction {
    0% {
      transform: translate(0, 90px);
    }
    100% {
      transform: translate(0, 0px);
    }
  }
  
  @keyframes fillAction {
    0% {
      transform: translate(0, 90px);
    }
    100% {
      transform: translate(0, 0px);
    }
  }
  
  @-webkit-keyframes waveAction {
    0% {
      transform: translate(0, 0);
    }
    100% {
      transform: translate(-120px, 0);
    }
  }
  
  @-moz-keyframes waveAction {
    0% {
      transform: translate(0, 0);
    }
    100% {
      transform: translate(-120px, 0);
    }
  }
  
  @keyframes waveAction {
    0% {
      transform: translate(0, 0);
    }
    100% {
      transform: translate(-120px, 0);
    }
  }
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.13 (/home/we_yuan/.nvm/versions/node/v12.14.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.803.22
   @angular-devkit/schematics    : 8.3.22
   @angular/cli                  : 8.3.22
   @ionic/angular-toolkit        : 2.1.1

Capacitor:

   Capacitor CLI   : 1.4.0
   @capacitor/core : 1.4.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (2 plugins total)

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   NodeJS : v12.14.1 (/home/we_yuan/.nvm/versions/node/v12.14.1/bin/node)
   npm    : 6.13.4
   OS     : Linux 4.4
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Ionic Framework does not alter your CSS Animations (unless you are using Ionic Animations). Can you provide a repo with the code required to reproduce this issue?

**Comment by weyuan989** [comment]
Hi. Thanks for the reply. Here is the link of the repo.
https://github.com/weyuan989/waveanimation

Page of performing the animation is testing.page.html & testing.page.css

**Comment by weyuan989** [comment]
I just found out the issue. Apparently the linear gradient is not supported in ios and safari. Here is the fix.

> Change fill="url(#linearGradient-1)" to fill="blue"

`<div class="fill">
  <svg width="200%" height="100%" viewBox="0 0 240 140" version="1.1">
    <defs>
      <linearGradient x1="50%" y1="0%" x2="50%" y2="100%" id="linearGradient-1">
        <stop offset="0%"></stop>
        <stop offset="50%"></stop>
      </linearGradient>
    </defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
      <g id="widget-copy-2" fill="blue">
        <g id="wave-copy" transform="translate(0.000000, 1.000000)">
          <path
            d="M0,140 L0,2.59259259 C0,2.6670255 28.08,-4.12156133 66,3.88888889 C83.6331044,8.10263543 102,6.61060503 120,2.59259259 L120,140 L0,140 Z M120,140 L120,2.59259259 C120,2.6670255 148.08,-4.12156133 186,3.88888889 C203.633104,8.10263543 222,6.61060503 240,2.59259259 L240,140 L120,140 Z"
            id="waveShape"></path>
        </g>
      </g>
    </g>
  </svg>
</div>`
