### ISSUE TITLE
bug: icons not showing

### ISSUE THREAD

**Issue by visiongeist** [ionic-team/ionic#20712]
# Bug Report

**Ionic version:**
[x] 5.0 

**Current behavior:**
After migrating to Ionic 5, my icons are no longer loaded when using _ng serve_
(used with Angular)

**Expected behavior:**
Platform depending icons are shown (ios/md)

**Steps to reproduce:**
Add a tab button like this:
`<ion-tab-button tab="home">
      <ion-icon name="home"></ion-icon>
      <ion-label>Home</ion-label>
</ion-tab-button>`

You should see a 404 request to _http://localhost:4200/svg/home.svg_

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by jolugama** [comment]
me too.  
In mode develop it is working, that is to say, when i do ionic serve  but when i do ionic build --prod, that is the problem. not render svg inside ion-icon.  I check, and in ion-icon there is a div class icon-inner. inside must have the svg embedded but not, nothing svg, it is clean.

**Comment by visiongeist** [comment]
FIxed in newer version
