### ISSUE TITLE
bug: Unable to use ionic 5 + Bluetooth Serial + Capacitor to print on bluetooth printer

### ISSUE THREAD

**Issue by TiagoG** [ionic-team/ionic#20710]
Hi there,

I'm currently working on an app that requires some printing with bluetooth printers.
I setup everything as in the docs but when I try to test it on an ios device it logs the following message:
"
Error: Plugin MEGBluetoothSerial does not respond to method call discoverUnpaired:.
Ensure plugin method exists and uses @objc in its declaration
".
Versions:
- "@ionic/angular": "^5.0.0",
- "@ionic-native/bluetooth-serial": "^5.22.0",
- "cordova-plugin-bluetooth-serial": "^0.4.7",

Hope to hear from you soon,
Tiago

**Comment by NikolaPeevski** [comment]
@TiagoG Can you follow the template and post the full output of ionic info ?
