### ISSUE TITLE
Ionic 5, problem with dom.js in ionic/core

### ISSUE THREAD

**Issue by davvyy00** [ionic-team/ionic#20715]
Ionic:

   Ionic CLI                     : 6.2.0 (C:\Users\david.keane\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.900.5
   @angular-devkit/schematics    : 9.0.5
   @angular/cli                  : 9.0.5
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 6 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.9

System:

   Android SDK Tools : 26.1.1 (C:\Android)
   NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

After upgrading to ionic 5 and Angular 9, my pwa does not work on Edge, Microsoft Edge 44.17763.831.0

Error
[object Error]: {description: "Assignment to read-only properties is not allowed in strict mode", message: "Assignment to read-only properties is not allowed in strict mode", number: -2146823243, stack: "TypeError: Assignment to read-only properties is not allowed in strict mode at Anonymous function (http://localhost/dom-js.js:32:374) at ./node_modules/@ionic/core/dist/esm/polyfills/dom.js (http://localhost/dom-js.js:10:2) at __webpack_require__ (http://localhost/runtime.js:85:12) at __webpack_require__.t (http://localhost/runtime.js:183:25) at ZoneDelegate.prototype.invoke (http://localhost/polyfills.js:3748:17) at onInvoke (http://localhost/vendor.js:65709:17) at ZoneDelegate.prototype.invoke (http://localhost/polyfills.js:3748:17) at Zone.prototype.run (http://localhost/polyfills.js:3507:21) at Anonymous function (http://localhost/polyfills.js:4248:21) at ZoneDelegate.prototype.invokeTask (http://localhost/polyfills.js:3783:17)"}

If I edit ionic/core/dist/polyfills/dom.js and remove use strict it works

**Comment by liamdebeasi** [comment]
Thanks for the issue. As of Ionic Framework v5, we dropped support for older versions of Microsoft Edge. Please see the browser support page for more information: https://ionicframework.com/docs/intro/browser-support
