### ISSUE TITLE
feat: Scrollable ion-datetime

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic#20724]
# Feature Request

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
As a Ionic app is also deployable to desktop the ion-datetime component isn't really ergonomic when used with a mouse (on desktop, and mouse support on tablet), it would be really nice for it to be scrollable, currently we have to "swipe" but with the mouse.

**Describe Preferred Solution**
Make ion-datetime scrollable with a mouse wheel

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/15505.
