### ISSUE TITLE
bug: content is not getting proper offset-top on load

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic#20735]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

On initial load of a page in a Stencil app, the content offset-top is not being set properly which is causing bugs with the swipe to close modal & theming. After navigating around and back to the page, it is set properly. You can reproduce it on this PR: https://github.com/ionic-team/ionic-stencil-conference-app/pull/391

1) Opening the swipe to close modal by pressing the upper right button, notice the header becomes a black background

<img src="http://g.recordit.co/qM0TceLm1O.gif">

2) Setting dark mode in the side menu, notice the header is white

<img width="50%" src="https://user-images.githubusercontent.com/6577830/76326323-d8461000-62be-11ea-9706-4be775e81b7c.png">

Navigate around the app and try to reproduce it.

**Comment by liamdebeasi** [comment]
Possibly related to https://github.com/ionic-team/ionic/issues/20614
