### ISSUE TITLE
bug: Icon tabs are under white div in iPhone X

### ISSUE THREAD

**Issue by sbellver** [ionic-team/ionic#20748]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Icon tabs are under white block in iPhone X or upper

![Captura de pantalla 2020-03-11 a las 18 17 19](https://user-images.githubusercontent.com/8066456/76445239-64daf600-63c5-11ea-97a4-86970dd3011f.png)

**Expected behavior:**
Visible Icons , as in ionic serve

![Captura de pantalla 2020-03-11 a las 18 18 09](https://user-images.githubusercontent.com/8066456/76445249-699faa00-63c5-11ea-8f8d-6f98ecfa8c8f.png)

**Code**

app/components/tim-footer

```
<ion-footer no-border>
	<ion-toolbar mode="ios">
		<ion-tabs>
			<ion-tab-bar slot="bottom" class="no-border">
				<ion-tab-button (click)="goTo('orders')">
					<ion-icon [class]="'icon ico-market' + (tab == 1 ? '-filled' : '')" color="primary"></ion-icon>
				</ion-tab-button>
				<ion-tab-button (click)="goTo('home')">
					<ion-icon [class]="'icon ico-home' + (tab == 2 ? '-filled' : '')" color="primary"></ion-icon>
				</ion-tab-button>

				<ion-tab-button (click)="goTo('search')">
					<ion-icon [class]="'icon ico-search' + (tab == 3 ? '-filled' : '')" color="primary"></ion-icon>
				</ion-tab-button>
			</ion-tab-bar>
		</ion-tabs>
	</ion-toolbar>
</ion-footer>
```

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.2.1 (/Users/XXX/.nvm/versions/node/v10.18.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.7.0
   @angular-devkit/build-angular : 0.803.23
   @angular-devkit/schematics    : 8.3.21
   @angular/cli                  : 8.3.21
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 13 other plugins)

Utility:

   cordova-res (update available: 0.10.0) : 0.8.1
   native-run                             : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/XXX/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.18.0 (/Users/XXX/.nvm/versions/node/v10.18.0/bin/node)
   npm               : 6.13.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. `ion-tabs` works as a router outlet in order to handle navigation and does not have any styling. As a result, `ion-tabs` should not be used in an `ion-footer` or `ion-toolbar` component. This is likely why you are seeing visual glitches on your application.

For more information on `ion-tabs`, please see the documentation: https://ionicframework.com/docs/api/tabs

Feel free to take a look at the tabs Ionic starter for how to model your app: https://github.com/ionic-team/starters/tree/master/angular/official/tabs/src/app

Does this resolve your issue?
