### ISSUE TITLE
bug: scrollable ion-segment always shows scrollbar even if it doesn't overflow

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic#20758]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**

When having an `<ion-segment scrollable>`, the `overflow-x` is set to `scroll` and will therefore always render a scrollbar on windows, even if there's no overflow (i. e. even if all buttons fit).

**Expected behavior:**

The overflow should be set to `auto` so that the scrollbar only shows up when needed.

**Steps to reproduce/Related code::**

https://codepen.io/simonhaenisch/pen/MWwQRYd?editors=1000

**Other information:**

This is the line I'm talking about:

https://github.com/ionic-team/ionic/blob/f9f3095eb4a27b8023b318e59bfe835d6e7f0d0a/core/src/components/segment/segment.scss#L41

I can make a PR to fix this if you want.

**Comment by liamdebeasi** [comment]
A PR would be great. Thank you!

**Comment by simonhaenisch** [comment]
@liamdebeasi done ☝️

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20760 and will be available in an upcoming release of Ionic Framework.
