### ISSUE TITLE
Is building Windows UWP apps supported using Ionic 5?

### ISSUE THREAD

**Issue by srinidhirao** [ionic-team/ionic#20754]
# Bug Report

**Ionic version:**
[x] **4.x**
[x] **5.x**

**Current behavior:**
Building Windows UWP apps seems to be broken in Ionic 4 & 5.

**Expected behavior:**
Is Building Windows UWP apps supported in Ionic 5?

**Steps to reproduce:**
1. Create a new Ionic 5 app targeting Windows 10 UWP
2. Add a Camera Plugin.
3. Try to use the Camera Plugin.
4. You get an error saying JavaScript runtime error: Function expected

**Related code:**

https://github.com/srinidhirao/windows-10-sample

-->
Exception thrown while trying to use the plugin
```
Exception was thrown at line 3, column 19746 in ms-appx-web://io.ionic.starter/www/build/polyfills.js
0x800a139e - JavaScript runtime error: Uncaught (in promise): TypeError: Function expected
TypeError: Function expected
   at UnviredCordovaSDK.prototype.logError (ms-appx-web://io.ionic.starter/www/build/vendor.js:81543:86)
   at Anonymous function (ms-appx-web://io.ionic.starter/www/build/main.js:247:25)
   at step (ms-appx-web://io.ionic.starter/www/build/main.js:195:13)
   at Anonymous function (ms-appx-web://io.ionic.starter/www/build/main.js:176:46)
   at Anonymous function (ms-appx-web://io.ionic.starter/www/build/main.js:170:9)
   at t (ms-appx-web://io.ionic.starter/www/build/polyfills.js:3:21503)
   at Anonymous function (ms-appx-web://io.ionic.starter/www/build/main.js:166:5)
   at HomePage.prototype.OnSecondaryButtonClick (ms-appx-web://io.ionic.starter/www/build/main.js:229:9)
   at Anonymous function (Function code:43:15)
   at handleEvent (ms-appx-web://io.ionic.starter/www/build/vendor.js:14225:87)
```

**Other information:**
I had raised a similar issue for ionic 4, but the issue got closed since I couldn't get a sample project on time
https://github.com/ionic-team/ionic/issues/20325#event-3082052102

One of the replies indicated that its possible to build an app with Windows 10 UWP with Ionic & Cordova.

A issue was also raised in ionic-native regarding the same, but couldn't get any reply
https://github.com/ionic-team/ionic-native/issues/3275

I then added an issue in Apache Cordova site, but couldn't get an reply even there:
https://github.com/apache/cordova-plugin-camera/issues/542

We help developers build apps using our SDK, (https://ionicframework.com/docs/native/unvired-cordova-sdk). It is supported on all other platforms, ios, android & browser. We have issues integrating the plugin in Windows platform. A lot of our clients have been using Windows 10 machines and there is an urgent need to make the SDK compatible with Windows 10. Please help.

**Ionic info:**

```
$ ionic info

Ionic:

   Ionic CLI          : 5.4.16 (C:\Users\srinidhi\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : windows 7.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 6 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v8.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Ionic Framework is a collection of UI components that run on any of our supported platforms (see: https://ionicframework.com/docs/intro/browser-support).

Ionic Framework v4 applications should work in UWP applications. With Ionic Framework v5, we dropped support for IE11 and older versions of Microsoft Edge.

These older versions of Microsoft Edge were powered by an engine called EdgeHTML. Unfortunately, the webview for UWP apps is also powered by EdgeHTML. As a result, Ionic Framework v5 apps likely will not work in UWP applications. The newer versions of Edge are powered by Chromium, the same rendering engine that powers Google Chrome.

According to Microsoft, there are plans for the UWP webview to be upgraded to use Chromium instead of EdgeHTML, but that process has not taken place yet: https://blogs.windows.com/msedgedev/2019/06/18/building-hybrid-applications-with-the-webview2-developer-preview/

Hope this clears things up. Thanks!

**Comment by srinidhirao** [comment]
Hello @liamdebeasi, the issue is that we were able to get the UI components working even with Ionic 5 on a Windows 10 UWP app.

We are having issues integrating native plugins to Ionic 4 and 5 UWP apps. UI is not an issue. If you actually run the sample project, you can interact with the UI, but when you try to access the plugin functionality, it breaks. Can you please throw some light on this?

**Comment by liamdebeasi** [comment]
Ionic Framework does not manage the native plugins, so unfortunately I am not really sure what is going on there. If you are using something like https://github.com/apache/cordova-plugin-camera you could try reaching out to the developers.

If you are using Ionic Native, those are just wrappers around the cordova plugins to make using them easier and typically do not impact functionality of the plugins.

**Comment by srinidhirao** [comment]
Hi @liamdebeasi Looks like the ionic native wrapper is impacting the functionality in this case. I updated my project to use the camera plugin without ionic native and it works without any issues. 

I have captured a short video of the same which you can find here:
https://repo.unvired.io/unvired/ionic-native-camera-plugin-example.mp4

Please find the relevant code here:
```
declare var navigator: any;
// This works.
onCameraButtonWithoutIonicNativeClick() {
    console.log('Camera Button Clicked');
    navigator.camera.getPicture(function onSuccess(success) {
      console.log("Successfully clicked the picture:" + success);
    }, function onError(error) {
      console.log("Error Capturing the picture: " + error);
    }, {})
  }

// This doesn't.
  onCameraButtonWithIonicNativeClick() {
    const options: CameraOptions = {
      quality: 100,
      destinationType: this.camera.DestinationType.FILE_URI,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE
    }

    this.camera.getPicture(options).then((imageData) => {
      // imageData is either a base64 encoded string or a file URI
      // If it's base64 (DATA_URL):
      let base64Image = 'data:image/jpeg;base64,' + imageData;
      console.log("Base 64: " + base64Image);
    }, (err) => {
      // Handle error
      console.log("Error: " + err)
    });
  }

```
Can you please take a look at this once again? 
I'm reposting the link to the repository.
https://github.com/srinidhirao/windows-10-sample

**Comment by liamdebeasi** [comment]
If the Ionic Native wrapper is impacting functionality, I recommend opening an issue on the [Ionic Native repo](https://github.com/ionic-team/ionic-native). Ionic Framework does not manage Ionic Native plugins.
