### ISSUE TITLE
bug: App hangs on white screen after splash screen on devices and emulator

### ISSUE THREAD

**Issue by jplemieux66** [ionic-team/ionic#20769]
Ionic version: 5.0.3

The app hangs on a white screen after the splash screen (iOS and android). The debugger console gives no relevant information, however, I notice that in the Dom, app-root is empty. Sometimes, there is a 404 on all Javascript files, but that doesn’t seem to be consistent throughout all the changes I’ve made. The project works when running the emulator with live reload.
The project works fine when I run 'ionic serve'

Here is a repo that reproduces the issue
https://github.com/jplemieux66/ionic-blank-screen

Here is what I tried to fix this bug:

Followed the instructions on this link (in the white screen section):
https://ionicframework.com/docs/v3/wkwebview/

Tried the solutions mentioned in this issue:
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/95

Tried downgrading Cordova to 8.1.1
Tried downgrading Ionic CLI to 5.1.4
Tried removing all Cordova plugins and building again

**Other information:**
Dependencies:
"dependencies": {
    "@angular/animations": "9.0.3",
    "@angular/common": "9.0.3",
    "@angular/core": "9.0.3",
    "@angular/forms": "9.0.3",
    "@angular/platform-browser": "9.0.3",
    "@angular/platform-browser-dynamic": "9.0.3",
    "@angular/router": "9.0.3",
    "@ionic-native/clipboard": "5.22.0",
    "@ionic-native/core": "5.22.0",
    "@ionic-native/in-app-browser": "5.22.0",
    "@ionic-native/screen-orientation": "5.22.0",
    "@ionic-native/splash-screen": "5.22.0",
    "@ionic-native/status-bar": "5.22.0",
    "@ionic/angular": "5.0.3",
    "@ngrx/effects": "8.6.0",
    "@ngrx/entity": "8.6.0",
    "@ngrx/store": "8.6.0",
    "@ngrx/store-devtools": "8.6.0",
    "@swimlane/ngx-datatable": "16.0.3",
    "angular-gridster2": "9.0.2",
    "angular-svg-icon": "9.0.0",
    "cordova-android": "8.1.0",
    "cordova-clipboard": "1.3.0",
    "cordova-ios": "5.1.1",
    "cordova-ios-plugin-no-export-compliance": "~0.0.5",
    "cordova-plugin-device": "2.0.3",
    "cordova-plugin-inappbrowser": "3.2.0",
    "cordova-plugin-intercom": "^8.0.0",
    "cordova-plugin-ionic-keyboard": "2.2.0",
    "cordova-plugin-screen-orientation": "3.0.2",
    "cordova-plugin-splashscreen": "5.0.3",
    "cordova-plugin-statusbar": "2.4.3",
    "cordova-plugin-whitelist": "1.3.4",
    "core-js": "2.5.4",
    "d3": "5.0.0",
    "es6-promise-plugin": "4.2.2",
    "javascript-time-ago": "2.0.1",
    "logrocket": "1.0.6",
    "moment": "2.24.0",
    "moment-timezone": "0.5.26",
    "ng-intercom": "8.0.2",
    "ngx-avatar": "3.7.0",
    "ngx-infinite-scroll": "8.0.0",
    "ngx-spinner": "8.0.3",
    "ngx-stripe": "7.4.4",
    "ngx-toastr": "^12.0.0",
    "ngx-toggle-switch": "2.0.5",
    "normalize.css": "8.0.1",
    "prettier": "1.19.1",
    "prettier-tslint": "0.4.2",
    "resize-observer-polyfill": "1.5.1",
    "rollbar": "2.8.1",
    "rxjs": "6.5.4",
    "sancronos-validator": "1.2.0",
    "save-svg-as-png": "1.4.14",
    "tslib": "1.11.0",
    "zone.js": "0.10.2"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^8.4.0",
    "@angular-devkit/architect": "0.900.3",
    "@angular-devkit/build-angular": "0.900.3",
    "@angular-devkit/core": "9.0.3",
    "@angular-devkit/schematics": "9.0.3",
    "@angular/cli": "9.0.3",
    "@angular/compiler": "9.0.3",
    "@angular/compiler-cli": "9.0.3",
    "@angular/language-service": "9.0.3",
    "@ionic/angular-toolkit": "2.2.0",
    "@ngrx/schematics": "8.6.0",
    "@types/d3": "5.0.0",
    "@types/jasmine": "2.8.8",
    "@types/jasminewd2": "2.0.3",
    "@types/moment-timezone": "^0.5.12",
    "@types/node": "12.0.0",
    "codelyzer": "5.1.0",
    "jasmine-core": "2.99.1",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "2.0.1",
    "karma-jasmine": "1.1.2",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.4.0",
    "ts-node": "8.3.0",
    "tslint": "5.17.0",
    "typescript": "3.7.5"
  }

Config.xml:
```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="xxxxxx" version="2.2.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Example</name>
    <description>Example</description>
    <content src="index.html" />
    <access origin="*" />
    <allow-navigation href="https://*youtube.com/*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="21" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <preference name=“intercom-app-id” value=“xxxxxx” />
    <preference name=“intercom-ios-api-key” value=“ios_sdk-xxxxxx” />
    <preference name=“intercom-android-api-key” value=“android_sdk-xxxxxx” />
    <preference name="CordovaWebViewEngine" value="CDVUIWebViewEngine" />
    <platform name="android">
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:networkSecurityConfig="@xml/network_security_config" />
        </edit-config>
        <resource-file src="resources/android/xml/network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <icon height="20" src="resources/ios/icon/icon-20.png" width="20" />
        <icon height="40" src="resources/ios/icon/icon-20@2x.png" width="40" />
        <icon height="60" src="resources/ios/icon/icon-20@3x.png" width="60" />
        <icon height="48" src="resources/ios/icon/icon-24@2x.png" width="48" />
        <icon height="55" src="resources/ios/icon/icon-27.5@2x.png" width="55" />
        <icon height="29" src="resources/ios/icon/icon-29.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-29@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-29@3x.png" width="87" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="88" src="resources/ios/icon/icon-44@2x.png" width="88" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="172" src="resources/ios/icon/icon-86@2x.png" width="172" />
        <icon height="196" src="resources/ios/icon/icon-98@2x.png" width="196" />
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="1125" src="resources/ios/splash/Default-Landscape-2436h.png" width="2436" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="2436" src="resources/ios/splash/Default-2436h.png" width="1125" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
        <icon height="216" src="resources/ios/icon/icon-108@2x.png" width="216" />
        <splash height="2688" src="resources/ios/splash/Default-2688h~iphone.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-2688h~iphone.png" width="2688" />
        <splash height="1792" src="resources/ios/splash/Default-1792h~iphone.png" width="828" />
        <splash height="828" src="resources/ios/splash/Default-Landscape-1792h~iphone.png" width="1792" />
    </platform>
    <allow-navigation href="http://localhost:8100" sessionid="dd66d80a" />
    <allow-navigation href="http://localhost:8080/*" />
    <plugin name="cordova-plugin-intercom" spec="^8.0.0" />
    <plugin name="cordova-plugin-splashscreen" spec="~5.0.3" />
    <plugin name="cordova-clipboard" spec="~1.3.0" />
    <plugin name="cordova-ios-plugin-no-export-compliance" spec="~0.0.5" />
    <config-file parent="UIUserInterfaceStyle" platform="ios" target="*-Info.plist">
        <string>Light</string>
    </config-file>
    <engine name="android" spec="^8.1.0" />
    <engine name="ios" spec="^5.1.1" />
</widget>
```

**Ionic info:**

Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.3
   @angular-devkit/build-angular : 0.900.3
   @angular-devkit/schematics    : 9.0.3
   @angular/cli                  : 9.0.3
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, (and 9 other plugins)

Utility:

   cordova-res                          : 0.10.0
   native-run (update available: 0.3.0) : 0.2.9

System:

   ios-sim : 8.0.2
   NodeJS  : v12.16.1 (/usr/local/bin/node)
   npm     : 6.13.4
   OS      : macOS Catalina
   Xcode   : Xcode 11.3.1 Build version 11C504

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by jplemieux66** [comment]
I am unfortunately unable to provide the actual code that is causing the issue. I can try to reproduce it with another projectOn Mar. 12, 2020 6:46 p.m., Liam DeBeasi <notifications@github.com> wrote:
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by NikolaPeevski** [comment]
@jplemieux66 Does it work on a browser ? (ionic serve)

**Comment by jplemieux66** [comment]
Yes it works with ionic serve on a browser ! On Mar. 12, 2020 8:50 p.m., Nikola Peevski <notifications@github.com> wrote:
@jplemieux66 Does it work on a browser ? (ionic serve)

**Comment by NikolaPeevski** [comment]
@jplemieux66 Check the build directory, from the information you've provided you're not coping the right files to the simulator, can you provide the configuration files for cordova ?

**Comment by elvisgraho** [comment]
Same issue on real device. iPhone 11.

**Comment by jplemieux66** [comment]
I added the config.xml file to my original post

**Comment by jplemieux66** [comment]
<img width="300" alt="Screen Shot 2020-03-13 at 8 41 45 AM" src="https://user-images.githubusercontent.com/18087752/76621769-8abbe400-6506-11ea-8571-f4214ead8646.png">
<img width="293" alt="Screen Shot 2020-03-13 at 8 41 59 AM" src="https://user-images.githubusercontent.com/18087752/76621770-8bed1100-6506-11ea-8c67-d3799c54c5f0.png">
The files necessary seem to be copying to the www of the platform build

**Comment by jplemieux66** [comment]
I updated the original post with the Config.xml file

**Comment by liamdebeasi** [comment]
Unfortunately I am unable to reproduce the issue given just the config.xml file. Can you reproduce this in a blank Ionic starter app?

**Comment by jplemieux66** [comment]
Here is a repo that reproduces the issue
https://github.com/jplemieux66/ionic-blank-screen

**Comment by jplemieux66** [comment]
Update: I was able to solve the issue by updating my configurations. I am not sure what specifically caused the issue, but the commit is clearly identified and does not contain too many changes, for anyone experiencing this issue.

**Comment by elvisgraho** [comment]
Can we narrow down what exactly caused the issue and what exactly fixed it? I no longer have an access to IPhone device with the same issue, thus cannot do it myself.

**Comment by jplemieux66** [comment]
Regarding my specific problem, it can be easily reproduced with the repo mentioned above while emulating on an iOS device or Android device WITHOUT live reload. You can check out this commit and see if any of those changes can be applied to your project: 

https://github.com/jplemieux66/ionic-blank-screen/commit/fa7be8a34b945969767e7da9028e5710c57930b6

From what I can tell, what caused the issue was either using the custom webpack builder from Angular or forcing the UIWebView in the config.xml. 
I also recommend following the steps in the blank screen section: https://ionicframework.com/docs/v3/wkwebview/
