### ISSUE TITLE
bug: ion-router-outlet animation property issue

### ISSUE THREAD

**Issue by muzamilabbas** [ionic-team/ionic#20764]
# Bug Report

**Ionic version: 5.0.4**

[x] **4.x**

**Current behavior: animation is not a non property of ion-router-outlet**

**Expected behavior: as described in doc it should use custom animations using animation builder**

**Steps to reproduce: use animation property to ion-router-outlet**

**Related code: <ion-router-outlet [animation]=“routerAnimation”><ion-router-outlet>**

```
insert short code snippets here
```
![image](https://user-images.githubusercontent.com/26441541/76544653-37b44380-64aa-11ea-89bd-b67dabac44a2.jpg)

**Other information:**

As Ionic document suggest to use animation property for custom animations

![image](https://user-images.githubusercontent.com/26441541/76544923-b01b0480-64aa-11ea-9b8e-84e28f741815.jpg)

I am getting following error when I use ion-router-outlet property

![image](https://user-images.githubusercontent.com/26441541/76544827-8366ed00-64aa-11ea-9c4a-cc5a970e70fa.jpg)

When I have checked the ion-router-outlet.d.ts file than there is no property available for animation

![image](https://user-images.githubusercontent.com/26441541/76545073-e9537480-64aa-11ea-9bc2-9bc70110ed43.jpg)

Please fix this issue or suggest me how to use custom page animations .

Thanks 

**Ionic info:**

```
insert the output from ionic info here
```

![image](https://user-images.githubusercontent.com/26441541/76544427-d7250680-64a9-11ea-95b0-3d78a62d5123.jpg)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20767 and will be available in an upcoming release of Ionic Framework.
