### ISSUE TITLE
bug: ion-fab is behind header only on IPhone

### ISSUE THREAD

**Issue by elvisgraho** [ionic-team/ionic#20772]
# Bug Report

**Ionic version:**

[x] **5.0.5**

**Current behavior:**
Ion-fab hides behind header on IPhone but on IPad works just fine.
-- IPhone Horizontal
![IPhone Bad Vertical](https://user-images.githubusercontent.com/42517259/76604280-be9b0780-650e-11ea-999c-d3e63ffb41f4.gif)
-- IPhone Vertical
![IPhone Bad](https://user-images.githubusercontent.com/42517259/76604281-be9b0780-650e-11ea-83dc-1466e27d3bcc.gif)

**Expected behavior:**
Consistency between IPad and IPhone. Ion-fab not hiding behind objects.
-- IPad
![IPad Good](https://user-images.githubusercontent.com/42517259/76604276-bd69da80-650e-11ea-817e-4a4e0325581a.png)

**Steps to reproduce:**
Header and Ion-Fab on IPad and IPhone.

**Related code:**

-->

```
<ion-fab class="custom-fab" [class.active]="initialized" vertical="top" horizontal="end" slot="fixed">
  <ion-fab-button [color]="isFilterActive ? 'primary' : 'light' " (click)="openFilter()">
    <i *ngIf="!isFilterActive" class="far fa-filter"></i>
    <i *ngIf="isFilterActive" class="fas fa-filter"></i>
  </ion-fab-button>
</ion-fab>
```

**Other information:**
Both devices run latest IOS 13.3.1.  
This does not fix the issue.  
```css
ion-content {
  contain: size style;
}
```
When ion-header is outside of ion-content -> Bug.  
When ion-header is inside of ion-content -> No Bug.  

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.01)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : no whitelisted plugins (8 plugins total)

Utility:

   cordova-res (update available: 0.10.0) : 0.9.0
   native-run                             : 0.3.0

System:

   NodeJS : v12.14.1 (/Users/graholskise/.nvm/versions/node/v12.14.1/bin/node)
   npm    : 6.13.4
   OS     : macOS Catalina
   Xcode  : Xcode 11.3.1 Build version 11C504
```

**Comment by elvisgraho** [comment]
Seems to be an issue with ion-content because it causes another fixed element (footer) to visually glitch out. (ion-fab in the issue is not a visual glitch because it is behind the content).

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am unable to reproduce this issue using the code snippet provided.

**Comment by elvisgraho** [comment]
Hi. I already restructured the code to mitigate the issue. The thing was that my Header had fixed position applied. However, that does not change the issue. I encountered a lot of visual bugs (with fixed elements) when switching from IPad to an IPhone. Why isnt there consistency between platforms? (the screen size is irrelevant in this case).

**Comment by liamdebeasi** [comment]
There should not be any inconsistencies between platforms. If you could provide a code reproduction that would be very useful in helping us resolve this issue.
