### ISSUE TITLE
bug: Cannot pull to refresh in iOS with ionic 5

### ISSUE THREAD

**Issue by joshoconnor89** [ionic-team/ionic#20778]
**Ionic version:**

[ ] **4.x**
[x] **5.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**

Using ionic 5, the ion-refresher doesnt seem to work for ios.  It works for android, however.

**Expected behavior:**

You should be able to pull to refresh in ios with ionic 5

**Steps to reproduce:**

1) Add ion-refresher to project
2) run project on iOS using ionic 5
3) try to pull to refresh, nothing happens

**Related code:**

```
<ion-content>
  <ion-refresher
    slot="fixed"
    (ionRefresh)="doRefresh($event)"
    refreshing-icon="bubbles"
  >
    <ion-refresher-content> </ion-refresher-content>
  </ion-refresher>
```

**Other information:**

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 5.4.15
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.803.23
   @angular-devkit/schematics    : 8.3.23
   @angular/cli                  : 8.3.23
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 26 other plugins)

Utility:

   cordova-res (update available: 0.10.0) : 0.8.1
   native-run                             : 0.3.0

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.2 (/usr/local/bin/node)
   npm        : 6.13.1
   OS         : macOS Mojave
   Xcode      : Xcode 11.0 Build version 11A420a
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? Also what device are you testing this on?

**Comment by steavengong** [comment]
hi @joshoconnor89 
I think you have something wrong in use it

```
<ion-content>
  <ion-refresher
    slot="fixed"
    (ionRefresh)="doRefresh($event)"
    refreshing-icon="bubbles"
  >
    <ion-refresher-content> </ion-refresher-content>
  </ion-refresher>
```
1.refreshing-icon  change  refreshing-spinner
2. set it in ion-refresher-content

look this
```
<ion-refresher slot="fixed" >
    <ion-refresher-content
            refreshing-spinner="bubbles"></ion-refresher-content>
  </ion-refresher>

```

Hi @liamdebeasi 
I want to know  how to get the refresh state in ionPull event
i want to dynamic change refreshing-text when ionPull style with refresher-ready

**Comment by SSuarezBrooktec** [comment]
same here, this component do not work on ionic 5

**Comment by liamdebeasi** [comment]
@SSuarezBrooktec Please provide a repo with the code required to reproduce this issue.

**Comment by joshoconnor89** [comment]
@steavengong i tried your code and it didnt work.  and @liamdebeasi it iOS, I am on 13.3.1.

Ill get you a repo right now with it occurring, give me a little

**Comment by joshoconnor89** [comment]
okay i finally figured it out.  so basically this is the problematic code:

`@implementation UIScrollView (NoBounce)
- (void)didMoveToWindow {
    [super didMoveToWindow];
    self.bounces = NO;
    }
@end
`

this used to fix some strange glitching when scrolling for ios.  when I when I removed it, it works, seems like they fixed scrolling in ionic 5 for iOS
