### ISSUE TITLE
feat: Can you add the autofocus attribute for AlertInput

### ISSUE THREAD

**Issue by C-racker** [ionic-team/ionic#20779]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

The currently added inupt cannot automatically get the focus and needs to get the focus manually. I hope to add this option to facilitate user input

**Comment by netsesame2** [comment]
You can use @ViewChild decorator to refer to your input contol, then add focus  to this control when needed.

**Comment by C-racker** [comment]
> You can use @ViewChild decorator to refer to your input contol, then add focus to this control when needed.
It's created dynamically by AlertController, how do you use @ViewChild selection?

**Comment by liamdebeasi** [comment]
Thanks for the feature request. After discussing with the team, we have decided not to implement this feature.

According to the MDN documentation, the `autofocus` property "indicates that the input should automatically have focus when the page has finished loading". Using `autofocus` on an input that is not displayed on page load would not be proper usage (and typically would not work in certain browsers).

However, the `<dialog>` element was created for the use case that is described in this feature request. Unfortunately, not many browsers support it currently. Once `<dialog>` has better support, we would be more than happy to reconsider this feature. Thanks!

`autofocus` documentation: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefautofocus

`<dialog>` documentation: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
