### ISSUE TITLE
bug: Generating ES5 bundles for differential loading... 

### ISSUE THREAD

**Issue by ipehimanshu** [ionic-team/ionic#20780]
Hello 

here is my ionic info

`
Ionic:

   Ionic CLI                     : 6.2.1 (C:\Users\ipe\AppData\Roaming\npm\node_
modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic
-webview 4.1.3, (and 15 other plugins)

Utility:

   cordova-res : 0.10.0
   native-run  : not installed

System:

 (C:\Program Files\Android\android-sdk)
   NodeJS            : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 7

`

now when i try 
below command 
ionic build --prod --verbose

then 
it freeze to this line
Generating ES5 bundles for differential loading... 

Can anyone please help me?

Thanks

**Comment by netsesame2** [comment]
This is the Differential Loading feature added in Angular 8. 
You can edit the browerlist file, or you can change target to es5 only in tsconfig.json
