### ISSUE TITLE
bug: Swipeable Modals dismissed on click on Top

### ISSUE THREAD

**Issue by HansKrywaa** [ionic-team/ionic#20783]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

When i open a Swipeable Modal on ios, it is possible to dismiss this with a single Tap on the small Space of the underlaying Page.

**Expected behavior:**

I don't know if this is the expected behavior, but i think it should be, because it happens very fast and often without even knowing it. I expect to only be able to close the Modal via Swipe Gesture (or programmatically).  

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.2.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 53 other plugins)

Utility:

   cordova-res : 0.10.0
   native-run  : 0.3.0

System:

   Android SDK Tools : 25.2.3 (/Users/hanskrywalsky/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.16.1 (/usr/local/bin/node)
   npm               : 6.14.2
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. You are correct, the bit of space at the top should not be tappable.

**Comment by liamdebeasi** [comment]
Can you try the following dev build and let me know if it resolves the issue?

`npm i @ionic/angular@5.1.0-dev.202003172038.f0551ef`

**Comment by HansKrywaa** [comment]
Hey @liamdebeasi . Yeah seems to work, it doesn't dismiss anymore on tap. ☺️ But i noticed a second thing: Sometimes when i drag the Modal down and tap on the Backdrop while dragging the Modal gets stuck at the current Position. Sometimes the Modal goes to top again. I don't know what the behavior he should be, but i tested in a native iOS App and there nothing happens on a second backdrop click while dragging, i can just go on dragging.

I just tested with `v5.0.5` again and it is very very buggy there too when you drag a Modal down and while this tap on the Background. Should i open a new Issue or should be continue here?

**Comment by liamdebeasi** [comment]
Please open a separate issue with a code reproduction. Thanks!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20802 and will be available in an upcoming release of Ionic Framework.
