### ISSUE TITLE
bug: Ionic5  the refresher component did not work in Android

### ISSUE THREAD

**Issue by AlwaysLoveme** [ionic-team/ionic#20792]
# Bug Report

**Ionic version:**

5.0.5

**Current behavior:**

in MD theme , Refresh component did not work, but IOS theme worked
**Expected behavior:**

it can worke in MD theme or in Android
**Steps to reproduce:**

add ionRefresher component in IonContent, then  switch theme style to MD
**Related code:**

```
<ion-content>
    <ion-refresher #refresh slot="fixed" pullMin="50" pullMax="600">
        <ion-refresher-content pulling-icon="circular"></ion-refresher-content>
    </ion-refresher>
</ion-content>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.2.1 (C:\Users\admin\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.1
   @capacitor/core : 1.5.1

Utility:

   cordova-res : 0.9.0
   native-run  : 0.3.0

System:

   NodeJS : v12.15.0 (D:\Softs\Nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am unable to reproduce the issue using the code snippet provided.

**Comment by michielcrabbe96** [comment]
I'm experiencing a same type of problem. I have an ion-menu with an ion-content and inside this is my refresher
`<ion-refresher slot="fixed" (ionRefresh)="refresh($event)">
      <ion-refresher-content></ion-refresher-content>
    </ion-refresher>`
The refresher works on the iOS theme, but doesn't appear on the MD theme.

**Comment by michielcrabbe96** [comment]
I'm experiencing a similar problem. I have an `ion-refresher`  component implemented inside the `ion-content` of an `ion-menu`. When I'm in MD mode the refresher doesn't appear. However when the screen is large enough that the `ion-split-pane` kicks in and the menu stays visible, then the `ion-refresher` works.

I was able to simulate the problem in a newly created ionic project.

**Comment by liamdebeasi** [comment]
@michielcrabbe96 This sounds like a separate bug. Can you create a new issue for this?

**Comment by michielcrabbe96** [comment]
Sure no problem.

**Comment by AlwaysLoveme** [comment]
sorry for my late, there is my project git : https://github.com/AlwaysLoveme/ionic5DemoApp/blob/master/src/app/pages/home/goods-management/goods-list/goods-list.page.html,  in this page , if change the mode to md of refresher component, it can not work

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you reproduce this issue in an Ionic starter app? I am not familiar with your app's codebase so it will be difficult for me to debug.
