### ISSUE TITLE
bug: [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.#ion-slides

### ISSUE THREAD

**Issue by karthis668** [ionic-team/ionic#20796]
my ionic Info:
Ionic:

   Ionic CLI                     : 6.0.0 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.1
   @capacitor/core : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (1 plugins total)

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/home/developer/Android/Sdk)
   NodeJS            : v10.19.0 (/usr/bin/node)
   npm               : 6.13.4
   OS                : Linux 4.15

**Current behavior:**
ionic slides working properly in chrome browser but when i use to andriod device its not working properly..what happening looping is not working..

**Expected behavior:**
 i need to slides are looping properly 

**Steps to reproduce:**
Run the code to the android device .
then use chrome inspect .
use this url : chrome://inspect.
now you can see the error.

**Related code:**

This my code..
.html
<ion-slides pager="true" [options]="slideOpts" >
      <ion-slide *ngFor="let slider of slideimage;">
       <a>
       `    <img src="{{slider}}" title="title">`
       </a>
      </ion-slide>
</ion-slides>

.ts
slideOpts = {
    initialSlide: 1,
    loop:true,
    speed: 400,
    passiveListeners: false,
    centeredSlides: true,
    preloadImages:true,
    autoplay: true,
  };

You can see it via :https://stackblitz.com/edit/ionic4-slides?embed=1&file=pages/home/home.ts

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is there a particular bug you are running into? The screenshot you posted appears to be broken and the StackBlitz does not seem to exist.

**Comment by karthis668** [comment]
yes..sir,
now i update the link..you can see it now

**Comment by liamdebeasi** [comment]
Thanks for the issue. It looks like you are using Ionic 3 in this code reproduction. We are no longer actively developing Ionic Framework v3. We recommend you update to the latest version of Ionic Framework.

**Comment by karthis668** [comment]
No sir, i have used ionic 4 version,
Ionic CLI : 6.0.0 (/usr/lib/node_modules/@ionic/cli)
Ionic Framework : @ionic/angular 4.11.10
@angular-devkit/build-angular : 0.803.25
@angular-devkit/schematics : 8.1.3
@angular/cli : 8.1.3
@ionic/angular-toolkit : 2.2.0

**Comment by liamdebeasi** [comment]
Please provide a reproduction of the issue using Ionic 4/5. 

The StackBlitz you provided is using Ionic 3:

![image](https://user-images.githubusercontent.com/2721089/76867925-92e48e00-683c-11ea-94f1-7bd3205f9422.png)
