### ISSUE TITLE
bug: Modal flickers or stacked when tap on backdrop while dragging

### ISSUE THREAD

**Issue by HansKrywaa** [ionic-team/ionic#20808]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

When i drag down a iOS Card Style Modal and press on the Backdrop while dragging the Modal appears to be very very buggy, kinda flicker, stacked or go to the top again.

**Expected behavior:**

I tested in one native App, to see what happens there. And it happens nothing 😃 So you can tap with a second finger on the backdrop which get ignored and you can go on dragging.

**Steps to reproduce:**

I created a [Github Repo](https://github.com/HansKrywaa/ionic-modal-issue) but basically i just open a Card Style Modal^^

**Ionic info: (of the Demo Project)**

```
Ionic:

   Ionic CLI                     : 6.2.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:

   cordova-res : 0.10.0
   native-run  : 0.3.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.16.1 (/usr/local/bin/node)
   npm        : 6.14.2
   OS         : macOS Catalina
   Xcode      : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. What device/OS versions are you testing this on?

**Comment by HansKrywaa** [comment]
iPhone 11 Pro

**Comment by liamdebeasi** [comment]
Thanks! I was able to reproduce this behavior. This bug will be resolved via [this feature request](https://github.com/ionic-team/ionic/issues/20814) so I am going to close this issue in favor of the one I linked to.
