### ISSUE TITLE
bug: ionic 4 deal with modal when users click phone back button

### ISSUE THREAD

**Issue by yexinjia** [ionic-team/ionic#20806]
What should happen when users click over back button of phone? In case when modal opens.
Registered a back button:

// To prevent interference with ionic's own backbutton handling
// you can subscribe with a low priority instead
this.platform.backButton.subscribe(() => {
  // code that is executed when the user pressed the back button
  // and ionic doesn't already know what to do (close modals etc...)
  self.modalController.dismiss();
});

The problem with the code:

    It closes/dismiss modal is fine!

    But it also pushed back the page from where the modal is opened. Means it pop the page behind modal.

This should not happen the page should not pop - only modal should close.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? The current behavior in Ionic Framework is to dismiss the active modals first before navigating backwards when pressing the hardware back button.

**Comment by yexinjia** [comment]
I dismiss the active modals first, but there is no effect.

**Comment by liamdebeasi** [comment]
Ionic Framework will take care of dismissing any active modals first, so the custom code you have written above is not needed. If you remove the custom code, does that resolve your issue?

**Comment by yexinjia** [comment]
on my phone, is no effect.  Ionic Framework will take care of dismissing any but modal.

**Comment by liamdebeasi** [comment]
Can you provide a repo with the code required to reproduce this issue?

**Comment by AlwaysLoveme** [comment]
I wish when to click back button not close modal compoent, what should i do ? cause there is a login page in Modal component, and my project must be to login to use.

**Comment by AlwaysLoveme** [comment]
> Can you provide a repo with the code required to reproduce this issue?

I wish when I click the back button do not close modal compoent, what should i do ? because there is a login page in Modal component, and my project must be to login to use.
