### ISSUE TITLE
bug: refresher stop working if not in a delayed call 

### ISSUE THREAD

**Issue by RoyeA** [ionic-team/ionic#20803]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
When using an ion-refresher that needs to be canceled/complete in a non-delayed code, the ion-refresher will stop to respond for secondary pull/use. 

**Expected behavior:**
when calling on the event.target.complete() ( regardless if in delayed code, or direct ) the refresher needs to be ready for any future use/pull.

**Steps to reproduce:**
in the html:
.
.
.
<ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
    <ion-refresher-content></ion-refresher-content>
  </ion-refresher>
.
.
.

In the *.ts code:
doRefresh(event){
event.target.complete();
}

**Other information:**
The only solution that I found is to wrap the complete() in a setTimeout call as follows:
setTimeout(()=>{event.target.complete();},0);

**Ionic info:**

Ionic:

   Ionic CLI                     : 6.2.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   NodeJS : v12.14.1 (/usr/local/node-v12.14.1-linux-x64/bin/node)
   npm    : 6.13.4
   OS     : Linux 4.15

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by RoyeA** [comment]
Is there an online ionic5 that I can use like the https://stackblitz.com/edit/ionic-v4-angular-tabs ?
The refresher works in ionic4, but I moved to ionic5.

**Comment by liamdebeasi** [comment]
@RoyeA You can just install Ionic Framework v5 in that starter.

**Comment by RoyeA** [comment]
Hi @liamdebeasi, I tried to modify the code for v5, but I guess I truly don't know how to install ionic framework v5 in that starter :(
Do you have any sample of v5 that I can use?, or mabye, assist me ?
Sorry to bother you, 
Roye

**Comment by liamdebeasi** [comment]
It might be easier to create your project in a GitHub repo and send a link.

**Comment by RoyeA** [comment]
Here is the link to the repo
https://github.com/RoyeA/ionic5-refresh-issue

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

`npm i @ionic/angular@5.1.0-dev.202003182027.f86c826`

**Comment by RoyeA** [comment]
Same behavior :(

**Comment by liamdebeasi** [comment]
What device are you testing this on?

**Comment by RoyeA** [comment]
On a Ubuntu linux desktop, using "ionic serve".

**Comment by liamdebeasi** [comment]
Ok try this dev build:

`npm i @ionic/angular@5.1.0-dev.202003182304.a5f0dc3`

**Comment by RoyeA** [comment]
We have a winner.
It works.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20815 and will be available in an upcoming release of Ionic Framework.

**Comment by RoyeA** [comment]
Thank you
