### ISSUE TITLE
bug: ionic outline icons don't seem to work in ionic 5 react app.

### ISSUE THREAD

**Issue by CodeCurosity** [ionic-team/ionic#20817]
I am importing icons like this : 
`import { basket-outline, person, albums } from 'ionicons/icons';
`
and using like this in a sample tabs app
` <IonIcon icon={basket-outline} />
`
but i get this error 
./src/App.tsx
  Line 13:15:  Parsing error: ',' expected

**Comment by liamdebeasi** [comment]
Thanks for the issue. Imports should be camel case, not kebab case. The icon should be `basketOutline` not `basket-outline`.
