### ISSUE TITLE
custom ionicHistory 

### ISSUE THREAD

**Issue by Ibrahimkara92** [ionic-team/ionic#20812]
In my project that I want to work with ionic-react, I want to go to a different place by using the back button of the phones but I couldn't find anything about it.

**Comment by liamdebeasi** [comment]
In an upcoming version of Ionic Framework we will be providing more guidance on how to better utilize the hardware back button. For now, you can listen for the `ionBackButton` event to be emitted and call the `register` method:

```javascript
document.addEventListener('ionBackButton', ev => {
  // If using typescript, you may need to typecast ev as any
  ev.detail.register(100, () => {
    // Do your navigation in here
  });
});
```

The `100` value is a priority. Only 1 callback is called per `ionBackButton` event emission, and the callback with the largest priority value gets called first.

Please note that the `ionBackButton` event is only emitted in standalone Cordova/Capacitor applications and not in browsers.
