### ISSUE TITLE
bug: a navigation page opened behind the modal that opened it.

### ISSUE THREAD

**Issue by RoyeA** [ionic-team/ionic#20825]
# Bug Report

**Ionic version:**
[x] **4.x**
[x] **5.x**

**Current behavior:**
From my main page, I open a modal page. all good here.

From the modal page, I open a new page using navigateForward. The newly opened page is placed behind the modal page and is not visible to the user. 

After closing the modal ( modalCtrl.dismiss() ), the modal disappears and then the page that was open is visible with the back arrow to return to the main page.

**Expected behavior:**
Main page visible => open modal => modal is visible => open a page => new page is visible with back button => click on back buton => modal is visible => click on (x) => modal closed => main windows is visible.

**Steps to reproduce:**
Create two pages.
Open first page as modal, and from it, open a second page using navController and navigateForward.

**Related code:**
https://stackblitz.com/edit/ionic-v4-angular-tabs-qhhrdq

**Ionic info:**
Ionic:

   Ionic CLI                     : 6.2.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0-dev.202003182304.a5f0dc3
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   NodeJS : v12.14.1 (/usr/local/node-v12.14.1-linux-x64/bin/node)
   npm    : 6.13.4
   OS     : Linux 4.15

**Comment by liamdebeasi** [comment]
Thanks for the issue. If I am understanding correctly, it sounds like you want to push a page within the context of the modal.

Modals exist outside of the context of your `ion-router-outlet` (and therefore Angular Routing), so pushing a page from a modal will result in the new page appearing underneath the modal.

In this case, you will need to use `ion-nav`. We will definitely be providing more examples on this in the future, but all the methods you will need are in the docs: https://ionicframework.com/docs/api/nav.

Essentially, the template to your modal should just be `<ion-nav></ion-nav>`. Inside of the TS file for your modal, you should call the `setRoot` method on the nav to set the root component (pass in a reference to an Angular component). Each component from there should get a reference to the `ion-nav` and use the `push` method whenever you want to add a page to the stack.

Hope this clears things up!
