### ISSUE TITLE
feat: add attribute "color" to "ion-list"

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic#20820]
# Feature request

**Ionic version:**

[x] **5.0.5**

**Expected behavior:**

It should be possible to apply `color` attribute to `ion-list` to style all `ion-item` inside at once

**Example:**

```
  <ion-list color="primary>
    <ion-item detail="true">
      <ion-label>test</ion-label>
    </ion-item>
    <ion-item detail="true">
      <ion-label>test</ion-label>
    </ion-item>
  </ion-list>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. `ion-list` does not have a `color` property, so this would not have worked even in v4.

v5 example: https://codepen.io/liamdebeasi/pen/rNVrVBX
v4 example: https://codepen.io/liamdebeasi/pen/XWbBbXJ

Can you provide a repo of this working in a v4 application?

**Comment by DwieDima** [comment]
You're right. 
Maybe it was later back in Ionic 3.
I'll change this to a feature request!

**Comment by liamdebeasi** [comment]
Thanks for the follow up! I discussed this with the team and decided cascading the `color` property is not something we are looking to add to the framework at this time. In your use case, this can be achieved using CSS:

```css
:root {
  --ion-color-primary: #3880ff;
}

ion-list ion-item {
  --background: var(--ion-color-primary);
}
```
