### ISSUE TITLE
bug: Tabs + Footer transition timing off

### ISSUE THREAD

**Issue by dallastjames** [ionic-team/ionic#20823]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**

When using tabs and navigating to a child route of a tab that has a footer, the footer has some layering issues as it animates in/out with the child page.

![image](https://user-images.githubusercontent.com/16655763/77079188-3bb9f700-69bd-11ea-8d89-ae3d61cee352.png)

**Expected behavior:**

The footer animates in correctly

**Steps to reproduce:**

Run provided sample app. Click on any list item to navigate to a sub page that contains an ion-footer element. 

**Related code:**

https://github.com/logitimate/ionic-footer-issue

**Other information:**

**Ionic info:**

```
Ionic:
   Ionic CLI                     : 6.2.2 (/home/dallas/.nvm/versions/node/v13.7.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Utility:
   cordova-res : 0.10.0
   native-run  : 0.3.0

System:
   NodeJS : v13.7.0 (/home/dallas/.nvm/versions/node/v13.7.0/bin/node)
   npm    : 6.14.2
   OS     : Linux 5.5
```
```
Ionic:
   Ionic CLI                     : 6.2.2 (/Users/pairing/.n/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0
Utility:
   cordova-res : not installed
   native-run  : 0.3.0
System:
   NodeJS : v10.16.3 (/Users/pairing/.n/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by kensodemann** [comment]
In order for the animation to behave properly, I believe this needs to include an `ion-toolbar`:
https://github.com/logitimate/ionic-footer-issue/blob/master/src/app/tab1/footer-test/footer-test.component.html#L9-L11

example:

```html
<ion-footer>
  <ion-toolbar>
    <h3>This is a test footer</h3>
  </ion-toolbar>
</ion-footer>
```

You might want to give that a try and see if it makes things better.

**Comment by dallastjames** [comment]
Oh, you're totally right. Completely missed that in the demo. :man_facepalming: Thanks @kensodemann
