### ISSUE TITLE
bug: [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted. #ionic-slides

### ISSUE THREAD

**Issue by karthis668** [ionic-team/ionic#20837]
# Bug Report

Ionic info:
Ionic:

   Ionic CLI                     : 6.2.0 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.1
   @capacitor/core : 1.5.1

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.11.0 (/usr/bin/node)
   npm    : 6.13.7
   OS     : Linux 5.3

my original  app pakage.json:

{
  "name": "splurgify",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^9.0.6",
    "@angular/common": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@capacitor/android": "^1.5.1",
    "@capacitor/cli": "^1.5.1",
    "@capacitor/core": "^1.5.1",
    "@ionic-native/core": "^5.22.0",
    "@ionic-native/push": "^5.22.0",
    "@ionic-native/splash-screen": "^5.22.0",
    "@ionic-native/status-bar": "^5.22.0",
    "@ionic/angular": "^4.11.10",
    "@ionic/storage": "^2.2.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "angular-image-slider": "0.0.9",
    "cordova-support-google-services": "^1.4.0",
    "core-js": "^2.5.4",
    "ionic4-star-rating": "^1.1.1",
    "ng-image-slider": "^2.4.1",
    "ngx-order-pipe": "^2.0.4",
    "phonegap-plugin-multidex": "^1.0.0",
    "phonegap-plugin-push": "^2.3.0",
    "rxjs": "^6.5.4",
    "tslib": "^1.11.1",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "^0.803.25",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "^8.2.14",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@ionic/angular-toolkit": "^2.2.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.2.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.2",
    "protractor": "^5.4.3",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-support-google-services": {}
    }
  }
}

Current behavior:
ionic slides looping not working in android  devices it shows error as mentioned above.
Expected behavior:
i need slides are looping properly with error.

Steps to reproduce:
1.install the app into android device
2.in our app ,we have for sliders..after fourth slider it was not looping.if you force swipe , i shows [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

Other information:
stackblitz  demo: [https://stackblitz.com/edit/ionic4-slides](url)

Related code:
.html
`<ion-slides pager="true" [options]="slideOpts" >
      <ion-slide *ngFor="let slider of slideimage;">
        <p>{{slider}}</p>
       <a>
        <img src="{{slider}}" title="title">
       </a>
      </ion-slide>
    </ion-slides>`

```
.ts
slideOpts = {
    initialSlide: 1,
    loop:true,
    speed: 400,
    passiveListeners: false,
    centeredSlides: true,
    preloadImages:true,
    autoplay: true,
  };```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide the reproduction as a standalone GitHub repo? StackBlitz does not usually work very well on my mobile devices.
