### ISSUE TITLE
alertController.dismiss don't send data

### ISSUE THREAD

**Issue by nickwinger** [ionic-team/ionic#20838]
Ionic version:
[x] 5.4.5

Current behavior:
expect dismiss be able to send data to onDidDismiss.
```
const alert = await this.alertCtrl.create({
  header: 'Header',
  message: 'Message',
  buttons: [
    {
      text: 'Close',
      role: 'cancel',
    },
    {
      text: 'Delete',
      handler: () => {
        alert.dismiss({ deleted: true });
      },
    },
  ],
});
await alert.present();
const { data } = await alert.onDidDismiss();
console.log(data);   // expect { deleted: true } , but undefined.
```

Expected behavior:
alertController.dismiss can send data

Actually this is a copy of the issue [18772](https://github.com/ionic-team/ionic/issues/18772)
I find it quiet annoying to not be able to answer to a bug that was already published, why it gets locked ??

I don't understand the answer in the original issue and it is still not working as expected on my side.
Also, the modalController ist working the same way, you open a Page, you dismiss the page with data, you wait for the onDidDismiss and you get the data.
But the same approach is not working with the alert, so i don't understand why manucorporat answers in the original bug that it is not using the Ionic API correct.

So please tell me how to use the Ionic API correct, and why there is no example in the documentation of the alert to access the returned data when closing an alert ?!?

**Comment by liamdebeasi** [comment]
Thanks for the issue. The handlers in an alert already dismiss the alert for you, so doing `alert.dismiss({ deleted: true })` will not give you the results you want.

In order to have the data returned, you need to do:

```
handler: () => {
  return { deleted: true };
}
```
