### ISSUE TITLE
bug: Attempted import error: 'reorder' is not exported from 'ionicons/icons'

### ISSUE THREAD

**Issue by wangcode** [ionic-team/ionic#20848]
# Bug Report

**Ionic version:**
[x] **4.11.10 (v4-lts)**

**Ionicon version:**
[x]**5.0.1**

```
Attempted import error: 'reorder' is not exported from 'ionicons/icons'.
```

**Other information:**
I know this bug is fixed in v5 version or install Ionicon 4.6.x, but i can't use ionic5, the Mobile Browser Supposed Change ios 10.0 => 11.0+, this is unacceptable, can you fix this bug in v4,
Thanks

**Comment by liamdebeasi** [comment]
Thanks for the issue. As of the release of Ionic Framework v5, Ionic Framework v4 is only going to be receiving critical security fixes moving forward.
