### ISSUE TITLE
bug: Ionicons 5 not showing in Ionic/Vue

### ISSUE THREAD

**Issue by frontendjordan** [ionic-team/ionic#20841]
**Ionic version:**
[x ] **5.x**

**I'm submitting a ...** 
[ x ] bug report
[ ] feature request

**Current behavior:**
Using @ionic/vue 0.0.9, @ionic/core 5.0.4, and ionicons 5.0.1, I am unable to get any icons to appear in my application. It appears inside of <ion-icon> the div with class 'icon-inner' is empty.

**Expected behavior:**
With ionicons version 5, it appears the icons are included by default into the project and should work out of the box, but they are not displaying.

**Related code:**
```<ion-icon name="help-circle-outline" size="large" slot="end" color="primary" @click="showInfoModal()"></ion-icon>```

**Comment by Jangerlp** [comment]
Hi,
I had the same problem in ionic/react.
But this post fixed it for me: https://github.com/ionic-team/ionic/issues/18847
He did use icon="" instead of name="" and imported the icons manually.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as we are waiting for Vue 3 to stabilize before we push forward with Ionic Vue development. Once Vue 3 stabilizes we will look into providing an update that brings better support for Ionicons (namely Ionicons v5). Thanks!
