### ISSUE TITLE
feat: ionViewDidEnter event in vanilla javascript 

### ISSUE THREAD

**Issue by claytongulick** [ionic-team/ionic#20842]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**
Currently for both Angular and React, a developer is able to determine when the view has been hydrated and rendered, post transition, with the ionViewDidEnter event.

This doesn't seem to exist for vanilla / lit-html, which makes it very difficult to do any DOM manipulation post-render. All sizes and bounding rects are reported as 0px prior to full rendering. So, doing something like integrating with a masonry library etc... that needs to calculate bounds is very difficult (hacks like setTimeout() are needed).

**Describe Preferred Solution**
For vanilla js projects, there should be a way to know when a component has finished rendering. An even broadcast from ion-router or ion-route, or (like with angular) a check to see if ionViewDidEnter exists on the component, and if it does, call it.

**Describe Alternatives**
To make this work currently, I use an unholy mashup of setTimeout and intersection observers.

Thanks!

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide an example of what you are trying to do? Most Ionic components already provide lifecycle events that you can listen using `addEventListener`.
