### ISSUE TITLE
bug: Ionic React Router Memory Leak 

### ISSUE THREAD

**Issue by sorxrob** [ionic-team/ionic#20844]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When navigating through different routes using render method to check if authenticated, I am getting this warning:
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`

**Expected behavior:**
I have no async requests in my useEffects, so I'm expecting it to not log any warning/errors. I'm using firebase btw.

**Code**
```tsx
<IonReactRouter>
    <IonRouterOutlet>
        <Route
            exact
            path="/"
            render={props => {
            return !user ? <Login {...props} /> : <Redirect to="/dashboard" />
            }}
        />
        <Route
            exact
            path="/register"
            render={props => {
            return !user ? (
                <Register {...props} />
            ) : (
                <Redirect to="/dashboard" />
            )
            }}
        />
        <Route
            exact
            path="/dashboard"
            render={props => {
            return user ? <Dashboard {...props} /> : <Redirect to="/" />
            }}
        />
    </IonRouterOutlet>
</IonReactRouter>
```

Any help would be much appreciated.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?
