### ISSUE TITLE
bug: input focus scroll assist still broken on subpages and modals

### ISSUE THREAD

**Issue by informatikTirol** [ionic-team/ionic#20843]
HI Liam, input focus scroll assist is still broken on subpages and modals. 
You closed the bug report #19589, so here a new bug report

Here a video: https://www.dropbox.com/s/1viy1j9tv5j968f/RPReplay_Final1584872342.MP4?dl=0

And here the source code:  https://www.dropbox.com/s/073puji4hkvqvlu/scrollAssistBugSubpagesModal.zip?dl=0

> Ionic:
> 
>    Ionic CLI                     : 6.3.0 (/Users/aj/.nvm/versions/node/v13.11.0/lib/node_modules/@ionic/cli)
>    Ionic Framework               : @ionic/angular 5.1.0-dev.202003111427.fd8a9f0
>    @angular-devkit/build-angular : 0.803.25
>    @angular-devkit/schematics    : 8.3.25
>    @angular/cli                  : 8.3.25
>    @ionic/angular-toolkit        : 2.2.0
> 
> Cordova:
> 
>    Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
>    Cordova Platforms : android 8.1.0, ios 5.1.1
>    Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)
> 
> Utility:
> 
>    cordova-res                          : not installed
>    native-run (update available: 0.3.0) : 0.2.9
> 
> System:
> 
>    Android SDK Tools : 25.2.3 (/Users/aj/Library/Android/sdk)
>    ios-deploy        : 1.10.0
>    ios-sim           : 8.0.2
>    NodeJS            : v13.11.0 (/Users/aj/.nvm/versions/node/v13.11.0/bin/node)
>    npm               : 6.14.3
>    OS                : macOS Catalina
>    Xcode             : Xcode 11.3.1 Build version 11C504

**Comment by berchik** [comment]
I have a similar problem that might be related. Using as site/pwa on ios, both chrome and safari, when the input field gets focused and keyboard is scrolling up for the input, then when finished everything becomes unresponsive – no clicks no scroll, just freeze. 

If the input field is on top of the screen and the keyboard is not scrolling everything up it all works well.

Hope this give some further clues.

**Comment by liamdebeasi** [comment]
Closing as per https://github.com/ionic-team/ionic/issues/19589#issuecomment-602582501
