### ISSUE TITLE
bug: segment button checked = true

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic#20857]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

![image](https://user-images.githubusercontent.com/23274631/77457410-aab2a800-6e22-11ea-95e6-f399be2fdf5b.png)
```
         <ion-segment>
		<ion-segment-button checked="true">
			test
		</ion-segment-button>
		<ion-segment-button>test1</ion-segment-button>
	</ion-segment>
```
**Expected behavior:**

It should checked first segment

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
ionic info

Ionic:

   Ionic CLI                     : 5.4.4 (C:\Users\indra26\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.900.7
   @angular-devkit/schematics    : 9.0.7
   @angular/cli                  : 9.0.7
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 6 other plugins)

Utility:

   cordova-res : 0.8.0
   native-run  : 0.2.9

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10


D:\cordova-testing>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Please see the Ionic Framework v5 breaking changes file: https://github.com/ionic-team/ionic/blob/master/BREAKING.md#segment-button.

> The checked property has been removed. Developers should set the value property on the parent ion-segment to match the value of the desired checked segment button.

**Comment by indraraj26** [comment]
hi @liamdebeasi , but checked property is mentioned in components.d.ts for segment button checked

**Comment by liamdebeasi** [comment]
The `checked` property does not appear in `components.d.ts` for `ion-segment-button`: https://github.com/ionic-team/ionic/blob/master/core/src/components.d.ts#L2005-L2026

![image](https://user-images.githubusercontent.com/2721089/77459569-4c5fd800-6dd6-11ea-8f29-dd572b3ed4e6.png)



Are you sure you are looking at the correct branch?

**Comment by indraraj26** [comment]
my bad it is updated. it was ionic 4 app , will update my code according to breaking changes. Thank you.
