### ISSUE TITLE
bug: Modal border flat when setting fullscreen on ion-content 

### ISSUE THREAD

**Issue by ishaiavrahami** [ionic-team/ionic#20851]
# Bug Report

**Ionic version:**
[x] 5.0.5 (Latest)

**Current behavior:**
When setting the ion-content to fullscreen inside the ion-modal, the header turns flat without boarder radius. This is when im doing the shuffle modal effect

**Expected behavior:**
Boarder radius at all time when using 

**Steps to reproduce:**
inside the modal-content theres is ion-header, ion-content, and ion-footer. I make the ion content fullscreen and the border radius disappears and turns flat.
 

**Related code:**
 
```
<ion-content color="light" fullscreen ></ion-content> 
```

 
![IMG_1256](https://user-images.githubusercontent.com/33962719/77353701-d6953700-6d17-11ea-9d80-3d034c165714.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue? `5.1.0-dev.202003232043.c68160e`

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue? `5.1.0-dev.202003232057.c68160e`

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20852 and will be available in an upcoming release of Ionic Framework.

**Comment by ishaiavrahami** [comment]
Yes this worked. Thank you
