### ISSUE TITLE
bug: ChunkLoadError / Unhandled Promise rejection

### ISSUE THREAD

**Issue by PatrykJankowski** [ionic-team/ionic#20859]
**Ionic version:**
[x] 5.0.5 (Latest)

**Current behavior:**
Bug occurs if you click on an item (open a new window) in offline mode before you do it online.
The new window is not displayed correctly.
Maybe something with routing or module loading is wrong.

**Expected behavior:**
New window should be displayed correctly and there should be no errors in console.

**Steps to reproduce:**
- create a new project by using `ionic start testProject list --capacitor`
- `ionic serve`
- open app in chrome and set offline mode in developer tools
- click on one of the items from the list on scrren

It's the same if you try to open in example a modal window for `<ion-select>`
`index-2cd7e630.js:1961 ChunkLoadError: Loading chunk stencil-ion-alert-md-entry-js failed.`

![obraz](https://user-images.githubusercontent.com/16896903/77457525-1e41be80-6dfd-11ea-8d35-3192b0b80ff1.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. To improve load times, all components in Ionic Framework are lazy loaded by default. Disconnecting from the network before a certain chunk has been loaded is going cause an error to be thrown when the app tries to load that chunk.

If you are building an offline application, one approach we recommend is to use your app's service worker to prefetch the chunks/assets you need ahead of time. You will also want to have a way of updating the service worker if the data ever changes (if you update your version of Ionic Framework, for example).

**Comment by simplifyjs** [comment]
@liamdebeasi How can we prefetch chunks/assets ahead of time? Can you show some snippet please

**Comment by liamdebeasi** [comment]
https://github.com/ionic-team/ionic/issues/21379#issuecomment-634648519 shows how to lazy load specific components, which in turn loads the particular chunks.

A service worker might also be something to look into for this: https://angular.io/guide/service-worker-intro (Angular example)
