### ISSUE TITLE
Ionic Studio

### ISSUE THREAD

**Issue by fungkokting** [ionic-team/ionic#20866]
created a project for testing using Ionic studio. Currently the page are not displaying page preview in UI properly. It keep flickering and show blank most of the time despite sometimes it will shows the page preview.

I'm using macos Mojave with latest ionic studio. 

The impact now is I cannot page preview on how my html coding changes will affect the UI. 

![image](https://user-images.githubusercontent.com/15325101/77525877-eb241d00-6e46-11ea-920a-de2b3b8f025b.png)

# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. For any issues involving Ionic Studio, please send an email to support@ionic.io.
