### ISSUE TITLE
feat: Bring back small list headers

### ISSUE THREAD

**Issue by wilk-polarny** [ionic-team/ionic#20879]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

I would like to use the old style, thin list headers in Ionic 5, as they currently break the overall visual design of apps relying on the old headers. Especially in iOS, the old style list headers are still in use by native applications - I think there should be a way to decide which type of header to use.

**Describe Preferred Solution**
Preferrably the ability to choose via some kind of directive/parameter?

**Describe Alternatives**

A workaround would be to clone the styling from Ionic 4 and reapply custom styles to the list headers.

**Related Code**

None.

**Additional Context**

![Inkedsafariwebsitesettings-800x779_LI](https://user-images.githubusercontent.com/819238/77640946-7f7fa400-6f5b-11ea-89d3-78e9da0ec81b.jpg)

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is already possible in Ionic Framework. We updated the list headers to match the latest iOS spec, but you can still customize the list headers if you want a different style.

CodePen example: https://codepen.io/liamdebeasi/pen/RwPqMJQ
