### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by teuassuri2** [ionic-team/ionic#20881]
# Bug Report

**Ionic version:**

[x] 4.4.3

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**
ionic cordova resources android

**Related code:**

```
HTTP Error 503: POST https://res.ionic.io/api/v1/upload
```

**Other information:**

**Ionic info:**

```
HTTP Error 503: POST https://res.ionic.io/api/v1/upload
```

**Comment by liamdebeasi** [comment]
Spoke with the team regarding this. You just need to upgrade your Ionic CLI, and you should be good to go! 🙂 

You likely have an old CLI version, so you will need to do

```
npm uninstall -g ionic
npm i -g @ionic/cli
```
