### ISSUE TITLE
feat: Inline Edit with IONIC 5

### ISSUE THREAD

**Issue by tvvignesh** [ionic-team/ionic#20880]
Hi. I was wondering if inline edit can be made easier with IONIC (like X-editable which is no longer maintained - https://vitalets.github.io/x-editable/ )

There has been some questions on the forum for the older versions of IONIC related to this but not anything with concrete solution nor does it suit IONIC 5:
https://forum.ionicframework.com/t/inline-edit-with-ionic-2/67421
https://forum.ionicframework.com/t/need-a-tutorial-for-ng2-inline-editor/89997/4
https://forum.ionicframework.com/t/ionic-3-ion-item-edit-in-place/89815/2

Was wondering if something like this could be added. While I can write code to get this working, wanted to know if some standard approach from the IONIC team would be possible before I start to re-invent the wheel.

It may be an addition to already existing components like ion-input , ion-item, etc. or a new component by itself whichever suits.

Thanks.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. After discussion with the team, we have decided not to include this feature in Ionic Framework.

There are already a few well maintained libraries that allow for customizable inline editors such as https://www.tiny.cloud/ and https://ckeditor.com/. Both libraries should work in Ionic Framework. Thanks!
