### ISSUE TITLE
Possible to share example for ionic 5 modal as page also

### ISSUE THREAD

**Issue by ipehimanshu** [ionic-team/ionic#20894]
Hello all

i want to use ionic 5 modal as page also ,
Is there any way to use ionic 5 modal as page also ?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you clarify your question?

**Comment by ipehimanshu** [comment]
@liamdebeasi yes true i want to use modal as page also .
So is that type possible ?

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Modals cannot be part of routing. Since modals are temporary components, we made the decision to not integrate them with routing since that is part of an application's global state.
