### ISSUE TITLE
HTTP Error 503: POST https://res.ionic.io/api/v1/upload

### ISSUE THREAD

**Issue by camoi3** [ionic-team/ionic#20898]
error eject >ionic cordova platforms add android

Saving android@~7.1.4 into config.xml file ...
> ionic cordova resources android --force
√ Collecting resource configuration and source images - done!
√ Filtering out image resources that do not need regeneration - done!
HTTP Error 503: POST https://res.ionic.io/api/v1/upload

<!DOCTYPE html>
        <html>
          <head>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta charset="utf-8">
                <title>Application Error</title>
                <style media="screen">
                  html,body,iframe {
                        margin: 0;
                        padding: 0;
                  }
                  html,body {
                        height: 100%;
                        overflow: hidden;
                  }
                  iframe {
                        width: 100%;
                        height: 100%;
                        border: 0;
                  }
                </style>
          </head>
          <body>
                <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
          </body>
        </html>

**Comment by liamdebeasi** [comment]
Thanks for the issue. Please update your Ionic CLI. Very old versions of the CLI used an online version of resource generation. Newer versions of the CLI still have this, but the generation is all done on your machine.

```
npm uninstall -g ionic
npm i -g @ionic/cli
```

**Comment by suhailparad** [comment]
> Thanks for the issue. Please update your Ionic CLI. Very old versions of the CLI used an online version of resource generation. Newer versions of the CLI still have this, but the generation is all done on your machine.
> 
> ```
> npm uninstall -g ionic
> npm i -g @ionic/cli
> ```

It works,, Thank you
