### ISSUE TITLE
I can't build the app on android

### ISSUE THREAD

**Issue by vasquezdennisalon** [ionic-team/ionic#20892]
I am trying to build android app i run ionic cordova build android command on mac but it tells me

```
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT = undefined (recommended setting)
ANDROID_HOME = / Users / denisvasquez / Library / Android / sdk (DEPRECATED)
Requirements check failed for JDK 8 ('1.8. *')! Detected version: 11.0.5
Check your ANDROID_SDK_ROOT / JAVA_HOME / PATH environment variables.
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build android exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more
        information.
```

additionally I have the following environment variables
### Create a JAVA_HOME variable, determined dynamically 
export JAVA_HOME=$(/usr/libexec/java_home)  

### Add that to the global PATH variable
export PATH=${JAVA_HOME}/bin:$PATH

### Set Android_HOME
 export ANDROID_HOME=~/Library/Android/sdk/
 export ANDROID_SDK_ROOT=~/Library/Android/sdk/

### Add the Android SDK to the ANDROID_HOME variable
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=$ANDROID_SDK_ROOT:$PATH

### I also have the gradle with version installed
------------------------------------------------------------
Gradle 6.2.2
------------------------------------------------------------

Build time:   2020-03-04 08:49:31 UTC
Revision:     7d0bf6dcb46c143bcc3b7a0fa40a8e5ca28e5856

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.5 (Oracle Corporation 11.0.5+10-LTS)
OS:           Mac OS X 10.15.3 x86_64

and I don't know what the problem really is

### ionic info

Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 9 other plugins)

Utility:

   cordova-res (update available: 0.11.0) : 0.9.0
   native-run                             : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/denisvasquez/Library/Android/sdk/)
   ios-sim           : 8.0.2
   NodeJS            : v12.13.0 (/usr/local/bin/node)
   npm               : 6.12.0
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504

**Ionic version:**
5.4.16

**Mac version:**
10.15.3

**Comment by AlwaysLoveme** [comment]
the JDK version must be "1.8", but your mac current version is "11.0.5", so build failed, try to change the version to '1.8.0'
