### ISSUE TITLE
HTTP Error 503: POST https://res.ionic.io/api/v1/upload

### ISSUE THREAD

**Issue by yonghengBao** [ionic-team/ionic#20893]
运行ionic cordova platform add android报以下错误
HTTP Error 503: POST https://res.ionic.io/api/v1/upload

<!DOCTYPE html>
        <html>
          <head>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta charset="utf-8">
                <title>Application Error</title>
                <style media="screen">
                  html,body,iframe {
                        margin: 0;
                        padding: 0;
                  }
                  html,body {
                        height: 100%;
                        overflow: hidden;
                  }
                  iframe {
                        width: 100%;
                        height: 100%;
                        border: 0;
                  }
                </style>
          </head>
          <body>
                <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
          </body>
        </html>

**Comment by catosaurusrex** [comment]
i have the same issue,

**Comment by gabrigcl** [comment]
Same too

**Comment by gabrigcl** [comment]
I need to publish an app tomorrow but I can't create an android platform because of this issue, please help me Ionic team!

**Comment by liamdebeasi** [comment]
Thanks for the issue. Please update your Ionic CLI. Very old versions of the CLI used an online version of resource generation. Newer versions of the CLI still have this, but the generation is all done on your machine.

```
npm uninstall -g ionic
npm i -g @ionic/cli
```

**Comment by mobiliseapplabllp** [comment]
i m working on ionic 3 if i use "npm uninstall -g ionic
npm i -g @ionic/cli" this command so my all project working fine??

**Comment by mobiliseapplabllp** [comment]
> I need to publish an app tomorrow but I can't create an android platform because of this issue, please help me Ionic team! What can I do to overcome this urgently?



> I need to publish an app tomorrow but I can't create an android platform because of this issue, please help me Ionic team! What can I do to overcome this urgently?

have you found solution??

**Comment by mobiliseapplabllp** [comment]
> npm uninstall -g ionic
> npm i -g @ionic/cli


I do Ionic 3 users cli (4.12.0) If I update my cli then my project will not be tied??

**Comment by WorkspacePrateek** [comment]
> Thanks for the issue. Please update your Ionic CLI. Very old versions of the CLI used an online version of resource generation. Newer versions of the CLI still have this, but the generation is all done on your machine.
> 
> ```
> npm uninstall -g ionic
> npm i -g @ionic/cli
> ```

I have updated both ionic + cordova still facing this issue

**Comment by WorkspacePrateek** [comment]
Here is Ionic Info:

   ionic (Ionic CLI)  : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.4

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.3.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

System:

   ios-deploy : 1.9.2
   NodeJS     : v11.4.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave

**Comment by kensodemann** [comment]
@WorkspacePrateek 

> ionic (Ionic CLI) : 4.6.0 (/usr/local/lib/node_modules/ionic)

That is not the latest CLI. The latest CLI is 6.5.0.

```
npm uninstall -g ionic
npm install -g @ionic/cli
```

Be sure to uninstall the old one before installing the new one. This is because of the package name change.

If you have done that already but are still getting the above, then your Node installation is borked because the `4.6.0` version is in your path for some reason.

@mobiliseapplabllp 

> I do Ionic 3 users cli (4.12.0) If I update my cli then my project will not be tied??

No. The version of the CLI has _nothing_ to do with the version if the Ionic Framework you are using in your app. That is controlled by your project's `package.json` dependencies.
