### ISSUE TITLE
Modal Behaviour with safari is weird

### ISSUE THREAD

**Issue by assman** [ionic-team/ionic#20905]
I have uploaded a video at this link to explain the bug since github doesnt allow embedding videos.

https://streamable.com/s/y7lli/xmiubl

As it shows in the video, at the 00:01, the Ion Header appears with a backdrop blur at first. Subsequently, it does show up normally. Same behavior happens at 00:07 when I open another modal, the header demonstrates similar behavior.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by assman** [comment]
Here's the repo. However, its very inconsistent and it has not happened in the past one day.

https://github.com/assman/ticket-ionic

**Comment by liamdebeasi** [comment]
Thanks for the follow up. What version of Safari are you testing this on?

**Comment by assman** [comment]
> Thanks for the follow up. What version of Safari are you testing this on?

Version 13.1 on MacOS 10.15.4

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I am going to close this as it sounds like neither of us are able to reproduce the issue currently (I was not able to see the issue using the repo provided). If you find another way to reproduce the blurring behavior, feel free to open a new issue. Thanks!
