### ISSUE TITLE
bug: Template Driven Form validation

### ISSUE THREAD

**Issue by AmieJoni** [ionic-team/ionic#20900]
Hi,
Im facing a problem in my ionic project, to summarize in all my forms i have a strange behaviour when i put validation like required email ... and then i enter text to my inputs, the UI style stays red.
Behaviour noticed on android and on the browser when it just get loaded.

**Ionic info:**
Ionic:

   Ionic CLI                     : 5.4.16 (/home/jonatan/.npm-packages/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.803.24
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 10 other plugins)

Utility:

   cordova-res (update available: 0.11.0) : 0.10.0
   native-run                             : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/home/jonatan/Android/Sdk)
   NodeJS            : v12.14.1 (/usr/local/bin/node)
   npm               : 6.14.2
   OS                : Linux 4.15

**Current behavior:**
 - if i tap in each input many times the style get changed to green and the first button is activated.
- if i submit the form surprisingly it is valid.

**Expected behavior:**
- change the style once i enter a valid input
- form gets valid state if all input are valid without submitting the form

**Steps to reproduce:**

**Related code:**
```
<ion-content>
  <form (ngSubmit)="eLogin(logInUserForm)" #logInUserForm="ngForm">
    <ion-item>
      <ion-label position="floating">Email</ion-label>
      <ion-input clearInput required email name="email" ngModel></ion-input>
    </ion-item>
    <ion-item>
      <ion-label position="floating">Password</ion-label>
      <ion-input clearInput required minlength="6" name="password" type="password" ngModel>
      </ion-input>
    </ion-item>
    <ion-button expand="block" color="primary" type="submit" [disabled]="!logInUserForm.valid">
      <ion-icon slot="end" name="mail"></ion-icon>
      Sign In
    </ion-button>
    <ion-button expand="block" color="primary" type="submit">
      <ion-icon slot="end" name="mail"></ion-icon>
      Sign In
    </ion-button>
  </form>  
</ion-content>
```

**Comment by indraraj26** [comment]
Can you update to latest version of ionic 5 then report it along with repo to reproduce
