### ISSUE TITLE
bug: ion-input

### ISSUE THREAD

**Issue by vasquezdennisalon** [ionic-team/ionic#20902]
how to resize an ion-input, i tried from the sass file by placing

```
ion-input {
height: 45px;
}
```

and also try to put it like this
```
ion-input {
--height: 45px;
}
```

and also try to put it like this
```
ion-input input {
--height: 45px;
}
```

but it does not work

**Comment by indraraj26** [comment]
Right now it is not recommended to mess with ion input with height and also --height is not exposed you will not able to override. You can use viewEncapsulation.none but it will give some strange behaviour or :host ::ng-deep to override
