### ISSUE TITLE
bug: HTTP Error 503: POST https://res.ionic.io/api/v1/upload

### ISSUE THREAD

**Issue by pulsar001** [ionic-team/ionic#20908]
When i run this command: ionic cordova platform add android

I receive 

```
√ Filtering out image resources that do not need regeneration - done!
HTTP Error 503: POST https://res.ionic.io/api/v1/upload

<!DOCTYPE html>
        <html>
          <head>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta charset="utf-8">
                <title>Application Error</title>
                <style media="screen">
                  html,body,iframe {
                        margin: 0;
                        padding: 0;
                  }
                  html,body {
                        height: 100%;
                        overflow: hidden;
                  }
                  iframe {
                        width: 100%;
                        height: 100%;
                        border: 0;
                  }
                </style>
          </head>
          <body>
                <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
          </body>
        </html>
```
I need to continue to use the same version of ionic 

Info
```
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)  : 4.2.0 (C:\Users\Az\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.4

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.1.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\Az\AppData\Local\Android\Sdk)
   NodeJS            : v12.16.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.13.4
   OS                : Windows 10

```

I don't understand why it does that, a few days ago it worked well

**Comment by indraraj26** [comment]
> Thanks for the issue. Please update your Ionic CLI. Very old versions of the CLI used an online version of resource generation. Newer versions of the CLI still have this, but the generation is all done on your machine.
> 
> ```
> npm uninstall -g ionic
> npm i -g @ionic/cli
> ```

**Comment by shoerofi** [comment]
how can i fix this issue with old ionic?

i need to use old ionic version for my app. if i update it, i have to change a lot of codes.

**Comment by GiperProger** [comment]
The same problem for me, we have a lot of ionic 3 applications, and it's impossible for us to update the CLI version.

**Comment by Metroslim** [comment]
Hello, I am facing the same problem. I can't update my ionic project and my automated workflow on githug get stuck each timebecause of this error.

**Comment by abozhiy** [comment]
The same problem for ionic 4.

**Comment by kensodemann** [comment]
The answer is in this comment: https://github.com/ionic-team/ionic/issues/20908#issuecomment-605667157

It is just the CLI that needs updating, not you application. You can update the CLI to version 6 without changing your application from version 3 or whatever version you happen to be on.

**Comment by iAbhinav** [comment]
> The answer is in this comment: [#20908 (comment)](https://github.com/ionic-team/ionic/issues/20908#issuecomment-605667157)
> 
> It is just the CLI that needs updating, not you application. You can update the CLI to version 6 without changing your application from version 3 or whatever version you happen to be on.

I can confirm this, all my projects are in ionic 3. I have updated to the CLI and all are working fine without any changes to the code. I ran the following commands to update the CLI.

npm uninstall -g ionic
npm i -g @ionic/cli

npm install npm@latest -g 

sudo npm cache clean -f
sudo npm install -g n
sudo n stable

npm rebuild node-sass

npm i -g cordova-res

**Comment by iAbhinav** [comment]
I can confirm this, all my projects are in ionic 3. I have updated to the latest CLI 6.4.0 and all are working fine without any changes to the code. I ran the following commands to update the CLI.

1. Update Ionic CLI
```
npm uninstall -g ionic
npm i -g @ionic/cli
```

2. Update NPM
` npm install npm@latest -g `

3. Update Node to 10.15.0. I tried first with v12 but this version is not compatible with sharp 1.2 which is required to generate resources
```
sudo npm cache clean -f
sudo npm install -g n
sudo n 10.15.0
```

4. In your project you need to rebuild node-sass since the node environment has changed
` npm rebuild node-sass`
5. For generating resources you need to install cordova-res 
```
sudo npm uninstall cordova-res
sudo npm i -g cordova-res --unsafe-perm
```
6. If you want update these two for better user experience
```
"cordova-plugin-ionic-webview": "^4.1.3",
"@ionic/lab": "^3.1.3"
```
7. Install all node modules
`npm i`

8. Now you may generate resources locally
`ionic cordova resources android`

9. Add and remove platforms
```
cordova platform remove android

cordova platform add android
```


Additionally if you face javascript heap max out error increase the max space to 4096 or more

`export NODE_OPTIONS=--max-old-space-size=4096`


Also If you face Typescript error ‘=‘ expected. Update typescript to 2.7.2

`npm i typescript@2.7.2`

**Comment by hustyangyi** [comment]
> I can confirm this, all my projects are in ionic 3. I have updated to the latest CLI 6.4.0 and all are working fine without any changes to the code. I ran the following commands to update the CLI.
> 
> 1. Update Ionic CLI
> 
> ```
> npm uninstall -g ionic
> npm i -g @ionic/cli
> ```
> 
> 1. Update NPM
>    `    npm install npm@latest -g `
> 2. Update Node to 10.15.0. I tried first with v12 but this version is not compatible with sharp 1.2 which is required to generate resources
> 
> ```
> sudo npm cache clean -f
> sudo npm install -g n
> sudo n 10.15.0
> ```
> 
> 1. In your project you need to rebuild node-sass since the node environment has changed
>    `    npm rebuild node-sass`
> 2. For generating resources you need to install cordova-res
> 
> ```
> sudo npm uninstall cordova-res
> sudo npm i -g cordova-res --unsafe-perm
> ```
> 
> 1. If you want update these two for better user experience
> 
> ```
> "cordova-plugin-ionic-webview": "^4.1.3",
> "@ionic/lab": "^3.1.3"
> ```
> 
> 1. Install all node modules
>    `npm i`
> 2. Now you may generate resources locally
>    `ionic cordova resources android`
> 3. Add and remove platforms
> 
> ```
> cordova platform remove android
> 
> cordova platform add android
> ```
> 
> Additionally if you face javascript heap max out error increase the max space to 4096 or more
> 
> `export NODE_OPTIONS=--max-old-space-size=4096`
> 
> Also If you face Typescript error ‘=‘ expected. Update typescript to 2.7.2
> 
> `npm i typescript@2.7.2`
Dear iAbhinav ,
  Could you tell me your node-sass version. 
  when  I run npm rebuild node-sass, it show errors:
node_modules\@ionic\app-scripts\node_modules\node-sass\src\libsass\include\sass/base.h(20): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory

**Comment by iAbhinav** [comment]
@hustyangyi I have node-sass v6.4.1.

**Comment by passwhl** [comment]
不需要升级cli，按照https://github.com/ionic-team/cordova-res/issues/96#issuecomment-607724818
