### ISSUE TITLE
bug: Slider is broken when using Ionic 5 + Angular 9

### ISSUE THREAD

**Issue by mariusbolik** [ionic-team/ionic#20911]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

If you open the page on the first time, everything looks fine. But if you open the page a second time, the slider seems to be broken:

<img src="https://raw.githubusercontent.com/mariusbolik/ionic-slider-bug/master/preview.gif" height="500px">  
Same as Video: https://streamable.com/9smhk  

**Steps to reproduce:**

- Clone Repo
- run `npm i`
- run `ionic serve`

**Related code:**  
https://github.com/mariusbolik/ionic-slider-bug

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20356.
