### ISSUE TITLE
bug: iOS Transition Problems when using Tabs (Ionic 5)

### ISSUE THREAD

**Issue by mariusbolik** [ionic-team/ionic#20912]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

If a new page gets entered, the page in the background doesn't move:  
<img src="https://raw.githubusercontent.com/mariusbolik/ionic-transitions-bug/master/preview-1.gif" height="500px">

**Expected behavior:**

The page in the background (Page 1) should slide to left if a new page appears, like in this example:  
<img src="https://cdn.dribbble.com/users/24527/screenshots/4751446/juin-26-2018_13-57-14.gif" height="400px">

When going back everything works fine:  
<img src="https://raw.githubusercontent.com/mariusbolik/ionic-transitions-bug/master/preview-2.gif" height="500px">

**Steps to reproduce:**

- Clone Repo
- run `npm i`
- run `ionic serve`

**Related code:**  
https://github.com/mariusbolik/ionic-transitions-bug

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

`npm i @ionic/angular@5.1.0-dev.202003301653.e5e02d4`

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20918 and will be available in an upcoming release of Ionic Framework.
