### ISSUE TITLE
bug: If animated == false, swipeGesture does not pop page from stack

### ISSUE THREAD

**Issue by mgreg89** [ionic-team/ionic#20910]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

If `[animated]="false"` and `[swipeGesture]="true"` is set on `<ion-router-outlet>`-Tag, the swiped out page gets "invisible", but the page is not popped from the stack and no event hooks for leaving / destroying the page are fired (since it sill exists). Renavigating to that page is not possible afterwards. Also, swipe back to another page down the stack is not possible.

**Expected behavior:**

After swipe back gesture is performed, the page is popped from the stack (as it is the current behavior when `[animated]="true"` and `[swipeGesture]="true"` is set) and all according events are fired.

**Steps to reproduce:**

1. Set `[animated]="false"` and `[swipeGesture]="true"` on `<ion-router-outlet>`-Tag
2. Navigate to a second page from home page
3. Use swipe back gesture to navigate back
4. Inspect DOM elements with preferred dev tool and find, that the leaving page is still a child of `<ion-router-outlet>`

**Related code:**
In this line, Ionic checks if an animation exists:
https://github.com/ionic-team/ionic/blob/b3b33127115bb966980a1288a0005dfb09306881/core/src/components/router-outlet/route-outlet.tsx#L70
which is not the case, if `[animated]="false"` was given.
As a result
https://github.com/ionic-team/ionic/blob/b3b33127115bb966980a1288a0005dfb09306881/core/src/components/router-outlet/route-outlet.tsx#L77
is never called. However, that is the only call to 
https://github.com/ionic-team/ionic/blob/4c8f32fae99db4022aa9dc75187e2f161e8e678e/angular/src/directives/navigation/stack-controller.ts#L180
which will pop the leaving page.

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.803.20
   @angular-devkit/schematics    : 8.3.20
   @angular/cli                  : 8.3.20
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 27 other plugins)

Utility:

   cordova-res (update available: 0.11.0) : 0.9.0
   native-run                             : not installed

System:

   ios-sim : 8.0.2
   NodeJS  : v12.16.0 (/usr/local/bin/node)
   npm     : 6.13.4
   OS      : macOS Catalina
   Xcode   : Xcode 11.4 Build version 11E146
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am unable to reproduce the issue using the steps provided.

**Comment by mgreg89** [comment]
Hey Liam :)
While creating such an repo, I could see that this bug is kind of fixed in Ionic 5. The behavior is now that if `swipeGesture="true"` and `animated="false"` Ionic ignores the swipe back gesture at all. If instead `swipeGesture="true"` and `animated="true"` is used, swipe back is enabled.
Not sure, if that is the intended behavior, but at least the above described bug is not present anymore, so nevermind and thanks for having a look ;)
