### ISSUE TITLE
bug: card with button directive in infinite scroll page lags scroll up on ios

### ISSUE THREAD

**Issue by capc0** [ionic-team/ionic#20932]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

scrolling a page with multiple loaded cards with button directives inside a infinite scroll page has a janky scroll up animation on iOS . it feels like it jumps immediatly to the first element again.

**Expected behavior:**

scrolling should be smooth.

**Steps to reproduce:**

scroll to the top of the page. then continue to scroll up (as if you would try to reload the page).

**Related code:**

https://stackblitz.com/edit/ionic-v4-angular-tabs-1247a2

**Other information:**

only on iOS devices with a bundled/served app (not in browser environment)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.900.5
   @angular-devkit/schematics    : 9.0.5
   @angular/cli                  : 9.0.5
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 20 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 0.3.0) : 0.2.9

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.14.2
   OS         : macOS Catalina
   Xcode      : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide this reproduction as a standalone GitHub repo? I need to run this as a standalone app, but StackBlitz doesn't always export the project properly.

**Comment by capc0** [comment]
reproduction repo: https://github.com/capc0/ion-card-btn-infinite-scroll-lag

run with ```serve-ios-device``` (do not forget to set dev team in Xcode on first run)

I figured out that the scrolling issues disappears if I remove one or both of the following
* ```button``` directive of the card
* ```<ion-card-subtitle>``` in the card header

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Yeah, I've seen this behavior before. I think it is a bug in WebKit when using transitions (in this case the card button) and rubber band scrolling.

I will see if there is an open WebKit bug/a workaround.

**Comment by liamdebeasi** [comment]
I opened a new issue here: https://bugs.webkit.org/show_bug.cgi?id=209968.

It looks like this particular issue is related, but the workaround is slightly different. As a workaround, you will need to disable the `text-transform` on the `ion-card-subtitle`:

```css
ion-card-subtitle {
  text-transform: none;
}
```

You can either type the text in all caps yourself or call `.toUpperCase()` on the string if you are generating these cards dynamically.

For updates regarding the WebKit issue, please refer to the WebKit link I included above. Thanks!

**Comment by capc0** [comment]
I will keep track at the webkit issue.

Unfortunatly the workaround does not work in my particular environment. I even encounter the bug without any ```<ion-card-subtitle>```  or even the entire ```<ion-card-header>```

**Comment by liamdebeasi** [comment]
In that case you will likely need to also disable the scale effect on the card:

```css
ion-card.ion-activated {
  transform: none;
}
```

You can have it change its background color instead for an activated effect.
