### ISSUE TITLE
ionic cordova resources 

### ISSUE THREAD

**Issue by zhaoleisam** [ionic-team/ionic#20933]
I am using ionic 3. when I try to prepare images by using ionic cordova resources --force command I get next error

HTTP Error 503: POST https://res.ionic.io/api/v1/upload

<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>

**Comment by kensodemann** [comment]
You need to upgrade your CLI

```
npm uninstall -g ionic
npm install -g @ionic-team/cli
```

Details here: https://github.com/ionic-team/ionic-cli/issues/4370
