### ISSUE TITLE
feat (tab) : Multiple tab design 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic#20936]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

1. 
![image](https://user-images.githubusercontent.com/23274631/78149790-077e1600-7454-11ea-8d4f-7d6c5547a3af.png)

2. 
![image](https://i.pinimg.com/originals/b1/cc/1c/b1cc1c52679a5fda9611ff118e91c2ec.gif)

3. 
![image](https://i.pinimg.com/originals/1f/38/8d/1f388d1261729aeceefeb8725b982559.gif)

4. 
![image](https://user-images.githubusercontent.com/23274631/78150339-cb978080-7454-11ea-9705-ce05541cdaed.png)

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by lhk** [comment]
What are you even requesting as a feature here?

Surely the job of the ionic team is not to craft highly specific custom animations that mimic some random tech demo

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is already possible in Ionic Framework. When you place elements inside of `ion-tab-button`, you can also provide custom styles based upon the selected/unselected state of the tab button.

Additionally, we feel that specific tab-button selection animations are better handled at the application level rather than at the framework level. Thanks!

**Comment by indraraj26** [comment]
@liamdebeasi  I tried but could not do it for all screens of mobile, the curve design. At least curve design should be on framework. If you can guide me how to achieve responsiveness that will be great.

```
    border-bottom-left-radius: 159px;
    border-bottom-right-radius: 161px;
```
small screen: 
![image](https://user-images.githubusercontent.com/23274631/78166419-5d5db880-746a-11ea-87ae-f0287fc14354.png)


on pixel2 screen:
![image](https://user-images.githubusercontent.com/23274631/78166472-76666980-746a-11ea-9acb-414b3d1da793.png)

@lhk Thank you for your awesome comment.

**Comment by liamdebeasi** [comment]
As I mentioned previously these animations are pretty custom, and it would be better to implement these on a per-application basis. When adding designs/animations to the framework, we try to adhere to the iOS and MD specs where possible, and these animations are not found in either spec. Thanks!
