### ISSUE TITLE
bug: tabs not working correctly with @ionic/react 5.0.7

### ISSUE THREAD

**Issue by kutoman** [ionic-team/ionic#20939]
# Bug Report

**Ionic version:**

[x] **5.0.7**

**Current behavior:**
in advance, I'm not absolutely sure whether It's a bug or I'm missing something (since I'm new to ionic) but I did a lot of research and couldn't resolve this issue and it seems like a bug for me. The content of a newly selected tab is not shown.

I noticed that [this sample](https://stackblitz.com/edit/ionic-react-tabs-r2olcs?file=index.tsx) works properly with @ionic/react0.0.10 but not with @ionic/react5.0.7.

**Expected behavior:**
always displaying the content of the currently selected tab.

**Steps to reproduce:**
[open this sample](https://stackblitz.com/edit/ionic-react-tabs-r2olcs?file=index.tsx) and just update the @ionic/react dependency. Afterwards click on any unselected tab button and you'll notice that the content won't get displayed

**Related code:**

```
const App: React.FunctionComponent = () => (
  <IonApp>
    <IonReactRouter>
      <IonPage id="main">
        <IonTabs>
          <IonRouterOutlet>
            <Route path="/:tab(tab1)" component={Tab1} exact={true} />
            <Route path="/:tab(tab2)" component={Tab2} exact={true} />
            <Route path="/:tab(tab2)/details" component={Details} />
            <Route path="/:tab(tab3)" component={Tab3} />
            <Route exact path="/" render={() => <Redirect to="/tab1" />} />
          </IonRouterOutlet>
          <IonTabBar slot="bottom">
            <IonTabButton tab="tab1" href="/tab1">
              <IonIcon icon={flash} />
              <IonLabel>Tab One</IonLabel>
            </IonTabButton>
            <IonTabButton tab="tab2" href="/tab2">
              <IonIcon icon={apps} />
              <IonLabel>Tab Two</IonLabel>
            </IonTabButton>
            <IonTabButton tab="tab3" href="/tab3">
              <IonIcon icon={send} />
              <IonLabel>Tab Three</IonLabel>
            </IonTabButton>
          </IonTabBar>
        </IonTabs>
      </IonPage>
    </IonReactRouter>
  </IonApp>
);
```

A sample application via GitHub

as provided earlier [here](https://stackblitz.com/edit/ionic-react-tabs-r2olcs?file=index.tsx)

-->

**Ionic info:**

even though the sample I've provided is online. I'm sharing my local ionic info since it's also not working for me locally.
```
insert the output from ionic info hereIonic:

   Ionic CLI       : 6.4.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.0.7

Capacitor:

   Capacitor CLI   : 1.5.2
   @capacitor/core : 1.5.2

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   NodeJS : v12.16.1 (/usr/local/bin/node)
   npm    : 6.13.4
   OS     : macOS Mojave```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you able to reproduce this on one of the Ionic React starter applications? Ionic React 0.0.10 is very old and went through several breaking changes before coming out of beta. It is possible that the StackBlitz you are using needs to be updated to account for those.

**Comment by kutoman** [comment]
ok I detected the cause of the problem. Each Tab needs to be enclosed in its own IonPage. This seems to be one of the breaking changes. Thanks for the quick response.

**Comment by liamdebeasi** [comment]
Glad to hear it's working now! Also feel free to check out our [Ionic React Getting Started Guide](https://ionicframework.com/docs/react) if you haven't already. 😄
