### ISSUE TITLE
bug: resource api

### ISSUE THREAD

**Issue by igoreliasm** [ionic-team/ionic#20949]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Hi, there is something get wrong with the resource api:

![Captura de Tela 2020-04-02 às 10 46 46](https://user-images.githubusercontent.com/2879536/78257083-c7f50f80-74cf-11ea-9a5e-d70443d7a5fa.png)

```
$ ionic cordova resources
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Please update your Ionic CLI. Very old versions of the CLI used an online version of resource generation. Newer versions of the CLI still have this, but the generation is all done on your machine.

```
npm uninstall -g ionic
npm i -g @ionic/cli
```

**Comment by igoreliasm** [comment]
@liamdebeasi tks a lot
