### ISSUE TITLE
bug: sometime routerLink and ion-back-button is not working on ios,

### ISSUE THREAD

**Issue by wanting615** [ionic-team/ionic#20946]
please help me,thanks;
Current behavior:
When I enter from page1 to page2, and then return to page1, this loop operation is repeated，sometime routerLink and ion-back-button is not working on ios，I had to exit the app and reopen it to make it work；
You can see from the gif；
![1](https://user-images.githubusercontent.com/44287823/78219720-ac4f3080-74f2-11ea-936a-cb022ec9712d.gif)

Related code:
![page2-html](https://user-images.githubusercontent.com/44287823/78219888-0b14aa00-74f3-11ea-85b1-b717352088e7.png)
![page2-module](https://user-images.githubusercontent.com/44287823/78219892-0ea83100-74f3-11ea-82e3-ec4bac7455a0.png)

my ionic Info:
"dependencies": {
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@ionic-native/core": "^5.18.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.11.7",
    "cordova-ios": "^5.1.1",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.8",
    "@angular/cli": "~7.3.8",
    "@angular/compiler": "~7.2.2",
    "@angular/compiler-cli": "~7.2.2",
    "@angular/language-service": "~7.2.2",
    "@ionic/angular-toolkit": "~1.5.1",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~12.0.0",
    "codelyzer": "~4.5.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.1.3",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.1.6"
  },

**Comment by wanting615** [comment]
它出现概率不是很高，但是偶尔会出现

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by wanting615** [comment]
Hi,You can find it here: https://github.com/wanting615/ionic-bug.git
Thanks;

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am unable to reproduce the issue you are describing? Can you provide some steps to reproduce the issue?

**Comment by wanting615** [comment]
> Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?
thanks,it enter from page1 to page2, and then click ion-back-button return to page1,Repeat this operation。
It's not easy to reproduce，I clicked for 10 minutes and it came up once。Does it have a root memory relationship；
if you have any ideas，Please tell me

**Comment by wanting615** [comment]
It only happen on IOS mobile phones, normal in browsers and simulators

**Comment by liamdebeasi** [comment]
@wanting615 Is there anything else you can tell me that can help me more consistently reproduce the issue? Without a good reproduction of the issue, it is unlikely I will be able to fix it. Thanks!
