### ISSUE TITLE
bug: Infinite scroll threshold still not working

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/ionic#20947]
I have had this issue for over 5 months whilst working with Ionic:

- Version: Most recent Ionic 5
- Angular - 8
- Mac OS
- Applies to all devices!

- I have infinite scroll placed within my ion-content tag, and the threshold set to a value (I have tried multiple both % and px).

When scrolling, the infinitescroll event is only ever called when the page is scrolled right to the bottom. I need it to happen very early on in the scroll cycle so as not to have the user wait as they scroll. 

  ```
  <ion-infinite-scroll threshold="400px" position="bottom"
            (ionInfinite)="loadMore($event.target, places.nextToken)">
            <ion-infinite-scroll-content loadingSpinner="crescent">
            </ion-infinite-scroll-content>
          </ion-infinite-scroll>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by indraraj26** [comment]
Here is stackblitz : https://stackblitz.com/edit/ionic-angular-v5-zxydr3?file=src%2Fapp%2Fapp.component.html
Tried both pixels and percentage, You can see console log when you go to bottom then it will trigger.

Sharing repo soon.

**Comment by NikolaPeevski** [comment]
Try a higher pixel range, for example
```
         <ion-infinite-scroll  position="bottom"
          (ionInfinite)="loadMore($event)" threshold="1000px">
          <ion-infinite-scroll-content loadingSpinner="crescent"
            loadingText="Loading more data...">
          </ion-infinite-scroll-content>
        </ion-infinite-scroll>
```

**Comment by indraraj26** [comment]
@NikolaPeevski did you checked my stackblitz? still it is same with 1000px. It will trigger when you reach to bottom.

> Here is stackblitz : https://stackblitz.com/edit/ionic-angular-v5-zxydr3?file=src%2Fapp%2Fapp.component.html
> Tried both pixels and percentage, You can see console log when you go to bottom then it will trigger.
> 
> Sharing repo soon.

**Comment by NikolaPeevski** [comment]
I did check your stackblitz, no issues whatsoever.
![2020-04-11 11 36 58](https://user-images.githubusercontent.com/14194863/79049580-14d09880-7bea-11ea-9b05-b2b28f70f568.gif)

**Comment by indraraj26** [comment]
@NikolaPeevski , I see it works for you for the first time. After that there is no emission testing 9

In my scenario, 
I always have to go to bottom to trigger infinite scroll event.

```
The threshold distance from the bottom of the content to call the infinite output event when scrolled. 
Use the value 100px when the scroll is within 100 pixels from the bottom of the page.
```
