### ISSUE TITLE
Scroll bar doesn't follow dark mode in Chrome

### ISSUE THREAD

**Issue by assman** [ionic-team/ionic#20941]
When running my ionic app in Chrome Version 80.0.3987.162 on macOS 10.15.4, the scroll bar shows white in color even when the ionic app is in dark mode.

Repo to reproduce:

https://github.com/assman/ticket-ionic

<img width="1920" alt="Screen Shot 2020-04-02 at 12 08 02 AM" src="https://user-images.githubusercontent.com/14093665/78160235-386f4280-7476-11ea-8306-17869cc68b46.png">

**Comment by brandyscarney** [comment]
Thanks for the issue! We're working on adding some docs on how to fix this over here: https://github.com/ionic-team/ionic-docs/pull/1346

You can use the following meta tag:

```
<meta name="color-scheme" content="light dark" />
```

**Comment by assman** [comment]
Thank you very much
