### ISSUE TITLE
bug: Text selection does not happen on iOS 13.4

### ISSUE THREAD

**Issue by murilospinoza** [ionic-team/ionic#20956]
# Bug Report

**Ionic version:**
[x] **4.x**

**Problem:**

After updating the iPad and iPhone to version 13.4, selecting the text by holding and dragging is no longer working. we've tested it in 2 ionic 4 apps and in both, the text selection didn't work.

https://drive.google.com/file/d/12f-TX9VKKhXyt0hXb5bJCuKQhizGeZb0/view?usp=sharing

**Related code:**
```html
<div class="selectable">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, se
  eiusmod tempor incididunt ut labore et dolore magna aliqua.
  Ut enim ad minim veniam, quis nostrud exercitation laboris.
</div>
```
```css
.selectable {
  -webkit-user-select: text;
  -moz-user-select: text;
  -ms-user-select: text;
  user-select: text;
}
```

**Ionic info:**
```
Ionic:
   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.13.10
   @angular-devkit/schematics    : 7.3.10
   @angular/cli                  : 7.3.10
   @ionic/angular-toolkit        : 1.5.1

Cordova:
   Cordova CLI       : 8.0.0
   Cordova Platforms : ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 23 other plugins)

Utility:
   cordova-res : 0.11.0
   native-run  : not installed

System:
   NodeJS : v12.14.1 (/usr/local/bin/node)
   npm    : 6.14.2
   OS     : macOS Mojave
   Xcode  : Xcode 10.1 Build version 10B61
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by murilospinoza** [comment]
Hi @liamdebeasi!
Thanks for the answer.
I created this repository from scratch and made the following changes related to text selection:
https://github.com/murilospinoza/text-selection/commit/149b67bd7c5b7fa37a803434949aab65b2793e88

**Comment by liamdebeasi** [comment]
Thanks for the follow up. It looks like this is caused by https://github.com/ionic-team/ionic/blob/0379977e1bfefbe78121e247343159d3a1c619aa/core/src/components/app/app.scss#L3

With this commit (https://github.com/murilospinoza/text-selection/commit/149b67bd7c5b7fa37a803434949aab65b2793e88) does the text selection work?

**Comment by murilospinoza** [comment]
Text selection works with two taps on a word, for example. But with the gesture of holding and dragging, as in the video, no.

In other versions of iOS, the gesture works.
