### ISSUE TITLE
bug: show white screen while fast scrolling 

### ISSUE THREAD

**Issue by 08Thug** [ionic-team/ionic#20959]
# Bug Report

**Ionic version:**
Ionic:

   Ionic CLI                     : 6.0.1 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.10
   

**Current behavior:**
 while fast scrolling it shows white screen! and data appears after 1 or two sec it works fine on slow scrolling

**Expected behavior:**
should not show white screen while fast scrolling!not even for short period of time

**Steps to reproduce:**
put some data for scrolling --> on scrolling fast the white screen appears and data comes after a delay
I dont think it is an UI Issue

**Other information:**

**Ionic info:**
Ionic:

   Ionic CLI                     : 6.0.1 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 3.1.2, (and 41 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.0.0) : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/home/bsetec/Android/Sdk)
   NodeJS            : v10.14.0 (/usr/bin/node)
   npm               : 6.4.1
   OS                : Linux 3.13

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by indraraj26** [comment]
@08Thug, This will happen when you will have large list of data in dom even with infinite scroll. In iOS, You will have lag in scrolling. This is happening since ionic 3.

**Comment by 08Thug** [comment]
> @08Thug, This will happen when you will have large list of data in dom even with infinite scroll. In iOS, You will have lag in scrolling. This is happening since ionic 3.

is there is no solution for this!?

**Comment by 08Thug** [comment]
> Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

just put a huge list of data in ion-infinite scrolling on fast scrolling you will see the result i am inheriting the list of data from database so can't produce a repo

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I am still unable to reproduce the issue after following the steps you provided. Can you reproduce the issue in a blank Ionic starter application?

**Comment by NikolaPeevski** [comment]
It might not be an ion issue but a browser issue, try lazyloading/offloading your list entries to keep a smaller chunk. Also what's the length of your huge list?
