### ISSUE TITLE
bug: background-activated css property is not working for ion-button (md mode)

### ISSUE THREAD

**Issue by Damini17** [ionic-team/ionic#20958]
Hi,

--background-activated CSS property is not working for ion-button for Android platform.

ion-button{
--background-activated:red;
}

# Bug Report

**Ionic version:**
Ionic Framework               : @ionic/angular 5.0.7

**Current behavior:**
the --background-activated property is not working for Android platform but working as expected for iOS.

**Expected behavior:**
the background color of the button when clicked must be changed to the color provided in --the background-activated property of ion-button

**Steps to reproduce:**
1. Create a new blank project using ` ionic start myApp blank`
2. Add an ion-button component to the homePage
3. set --background-activated property for ion-button is sass file.

```
home.page.html

<div id="container">
    <ion-button expand="full">Button</ion-button>
    <strong>Ready to create an app?</strong>
    <p>Start with Ionic <a target="_blank" rel="noopener noreferrer" href="https://ionicframework.com/docs/components">UI Components</a></p>
  </div>

home.page.sass

#container ion-button{
  --background-activated: red;
}
```

**Other information:**

**Ionic info:**

```
ionic info

Ionic:

   Ionic CLI                     : 5.2.2 
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : 0.2.7 (update available: 0.3.0)

System:

   NodeJS : v10.16.0 
   npm    : 6.13.1
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. It looks like `--background-activated-opacity` needs to be set to `1` on the button. I need to look into this to see if that is expected.

**Comment by Damini17** [comment]
@liamdebeasi Thank you for the reply. 
I tried setting up --background-activated-opacity to 1 and the property --background-activated working as expected.
