### ISSUE TITLE
Ionic button not clickable in IOS Emulator, it does not trigger any method.

### ISSUE THREAD

**Issue by hcoderonly** [ionic-team/ionic#20964]
I am using IONIC 5
---
when I run the application on the browser (chrome or safari) I can click and get the click event gets triggered, but when I run it on the IOS device, either as build or emulator it does not get triggered:

Here is the ts code:

`triggerEvent() {
    this.changevar = 'This is a message set easily ';  //does not get changed
    this.openAlertBox();   //does not run
  }`

The HTML page is as follow:
``<ion-content>
          <ion-button ion-button expand="block" (click)="triggerEvent()">Trigger Button</ion-button>
           <p>{{changevar}}</p>
</ion-content>``

**Comment by indraraj26** [comment]
Can you provide repo to reproduce ?

**Comment by hcoderonly** [comment]
I don't have a repo, but this happens only when I am deploying it on IOS emulator

**Comment by indraraj26** [comment]
I am unable to reproduce with your code, Please provide repo to reproduce.

**Comment by hcoderonly** [comment]
Was able to get a workaround:
https://stackoverflow.com/questions/61004281/ionic-cordova-button-not-clickable-in-ios-emulator?noredirect=1#comment107939961_61004281
