### ISSUE TITLE
bug: 5.0 ion-tab-button --background-focused variable not working

### ISSUE THREAD

**Issue by nidiy** [ionic-team/ionic#20977]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

The background of ion-tab-button elements remains unchanged when they receive focus, even though the --background-focused CCS4 variable for ion-tab-button elements is set.
**Expected behavior:**

I expected the ion-tab-button elements' background to get the background color I set in the --background-focused variable.
This is supposed to happen if I understand the docs correctly, see
https://beta.ionicframework.com/docs/api/tab-button
**Steps to reproduce:**

1. Create an Ionic tabs starter.
2. In the tabs.page.scss file paste:
```
ion-tab-button {
    --background-focused:#ff600d;
    --background-focused-opacity:0.5;
}
```
3. Observe that when a tab button receives focus its background remains unchanged.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI) : 6.3.0
   Ionic Framework : @ionic/angular 5.0.0
   Angular CLI: 9.0.1
   angular/common: 9.0.0
   angular/core: 9.0.0
   angular-devkit/architect: 0.803.23
   angular-devkit/build-angular: 0.900.1
   angular-devkit/core: 9.0.1
   Node: 10.14.2
   OS: Windows10 x64

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try this again with the latest version of Ionic Framework? I am not able to reproduce the issue: https://codepen.io/liamdebeasi/pen/mdJNVRJ

**Comment by nidiy** [comment]
hi, Using the latest version `@ionic/angular": "^5.0.7` **ion-tab-button** is selected, it still cannot be displayed `--background-focused` a color

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you provide a repo with the code required to reproduce this issue?

**Comment by nidiy** [comment]
I think I found the problem. When using the Tab key, it can trigger `--background-focused`. When it is selected, it triggers `tab-selected`. I want to add the following code to the CSS of the tab-button to solve this problem.
```
:host(.tab-selected) {
  color: var(--color-selected);
  background: var(--background-selected);
}
```
Add a `--background-selected` attribute

**Comment by liamdebeasi** [comment]
@nidiy In order to change the tab button color when focused, you need to use the `--background-focused` CSS Variable. `--background-selected` is not a CSS Variable that exists on `ion-tab-button`. 

Can you provide a reproduction with the code required to reproduce this issue? Without a reproduction, it is unlikely I will be able to fix this issue. Thanks!

**Comment by nidiy** [comment]
Thanks @liamdebeasi
Use a simple method
`ion-tab-button.tab-selected{
    background:#ff600d;
}`
my problem is solved
![image](https://user-images.githubusercontent.com/9928382/78685940-04d46280-7925-11ea-8712-08af23578bd4.png)
