### ISSUE TITLE
ionic repair hardwires android gradle build tools plugin to 3.3.0

### ISSUE THREAD

**Issue by nhhockeyplayer** [ionic-team/ionic#20988]
this is IONIC REPAIR why is it insisting hardwiring lower archetypes to build against android gradle build tools plugin to 3.3.0 ?

surely someone in ionic-team knows the landscape

NOTES...
Just reinstalled android studio

to reset that

my ionic project pre-exists fine

when I perform ionic repair, ionic resets the android gradle build tools plugin from 3.6.2 back down to 3.3.0

```
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        classpath 'com.android.tools.build:gradle:3.3.0'
    }
}
```

subsequent build fail with strange corrupted errors as seen on this issue

https://github.com/ionic-team/ionic/issues/20985
cant build

if android studio fixes things up ionic resets it back

all associated maven artifact caches pertaining to gradle have been deleted and replenished

**Comment by liamdebeasi** [comment]
Thanks for the issue. The `ionic repair` and `ionic repair --cordova` commands just remove the platforms and plugins and then restore them by performing a `cordova prepare android` and `cordova prepare ios`, so any resetting you are seeing is being done by Cordova and not Ionic.

If you want more control over the Android Studio project, you should look into using Capacitor and not Cordova. Capacitor makes the Android Studio project a source artifact rather than a build artifact, so once it is created you can change it as you desire, including the Gradle setup. For more information, please see http://capacitor.ionicframework.com/.

 If you would prefer not to move to Capacitor, you might want to take a look at Cordova’s documentation on how to configure/extend Gradle: https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#configuring-gradle

I am going to close this as Ionic Framework does not control Cordova's project generation process.

**Comment by nhhockeyplayer** [comment]
ok i will look into capacitor
thanks friend

maybe shutdown and junking is the answer too much dependency has been done to offshore and the industry is suffering as a result

**Comment by nhhockeyplayer** [comment]
and I will comment with prejudice

I have seen the code offshore rite and especially the insourcing of offshore help and they dont know what they are doing

its out of control

management does not know how to write software 
all they know how to do is push emails & paper and huff and assign offshore and insource offshore to do the work

and I watched them not know what they heck they are doing lying as they go along with big talk fast talk fast think

but management knows what they are doing

NOT

management is why the industry is messed

and I watched them ship stuff that flat does not work... big insurance companies banked on the fast talkers and fast thinkers putting on a big FALSE FRONT
walking all over elite american engineers
but when they get home they laugh their asses off
because they know they dont know what they are doing

**Comment by nhhockeyplayer** [comment]
there isnt a ounce of validity to the gradle wrapper
its a brain damaged growth

im moving to capacitor and junking cordova

**Comment by nhhockeyplayer** [comment]
can you recommend an IDE for capacitor ?

thank you

**Comment by liamdebeasi** [comment]
A few of my colleagues use VSCode and like it a lot https://code.visualstudio.com/.

**Comment by nhhockeyplayer** [comment]
ok,

your in boston... im right in NH above the border

i appreciate the help sorry for sounding heated I been on too many projects run overwhelmed by offshore and insourcing armies of incompetents here and its out of control ruined the industry... one right in quincy to name one... they ruin everything

Im building now using what you suggested
capacitor looks fine and im running with it

im a webstorm guy

thanks for directing a new fork in the road for me its going great

peace

**Comment by nhhockeyplayer** [comment]
one last question

I avoided launching android studio due to its instability and the gradle mechanics

once I get my app built for iOS Android and sync'd with android studio

can I terminate android studio and just run the following from command line from here on out

ionic cordova run android
ionic cordova run android

agains emulator

OR is there a capacitor equivalent to run against emulator from command Line

thanks this was fast

**Comment by liamdebeasi** [comment]
You can use the `ionic capacitor run` command to bundle your app and prepare for your deployment platform, but we do not currently support launching the project on a device yet via CLI: (https://ionicframework.com/docs/cli/commands/capacitor-run).

The main goal of Capacitor is to get away from all of the additional complex CLI tooling that Cordova has (which is likely the source of many of your Cordova frustrations such as the gradle.build customization). In a sense, when you develop with Capacitor you should expect to follow the same build process that native Swift or Java/Kotlin developers use.

One of our community members has a great guide on how to deploy to Android: https://www.joshmorony.com/deploying-capacitor-applications-to-android-development-distribution/. 

Hope this helps!
