### ISSUE TITLE
bug: Updating item in reorder group restores old order

### ISSUE THREAD

**Issue by NiklasMerz** [ionic-team/ionic#20982]
# Bug Report

**Ionic version:**
5.0.7

**Current behavior:**
I have built an reorder group based of an array of objects with ngFor.

1. I drag the first item to the last postion
2. I click on the this item which replaces the object with a new one
3. The old order is restored and my new object is the first in the list

**Expected behavior:**

Replacing an object should not change the order

**Related code:**

See example code here: https://github.com/NiklasMerz/reorder-repro

**Other information:**
Seems like this is only an issue after updating to Angular 9.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.4.1 (/Users/niklasmerz/.nvm/versions/node/v12.14.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.901.0
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 9.1.0
   @ionic/angular-toolkit        : 2.2.0
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Instead of manually manipulating the array in `doReorder`, can you try using the built-in Ionic method to do it?

Your code would look like this:
```javascript
this.messages = ev.detail.complete(this.messages)
```

**Comment by NiklasMerz** [comment]
This fixes it. Thank you very much.
