### ISSUE TITLE
bug: ion-menu swipe works even if the menu is disabled. 

### ISSUE THREAD

**Issue by blahblehblah** [ionic-team/ionic#20989]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
When disabling ion-menu, swipe gesture still works.

**Expected behavior:**
on disabling ion-menu it should ignore swipe gestures by default.

**Steps to reproduce:**
this.menuController.enable(false);
try to swipe the menu it will still show.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by blahblehblah** [comment]
Unfortunately, i don't have the appropriate time to do so, however, A simple starter tabs with addition to ion-menu should do it.

for now i had to disable the swipeGesture so i don't get surprised by someone dragging it from where it's disabled.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I am unable to reproduce this issue using a menu starter application. Feel free to follow up here when you have a repo, and I will take a look.

**Comment by blahblehblah** [comment]
A 'tabs' starter app with ion-menu added.

Thanks for your time.

**Comment by liamdebeasi** [comment]
Thanks for the clarification. I created a tabs starter application and added a menu to it, but was still unable to reproduce the issue.

**app.component.html**
```html
<ion-app>
  <ion-menu contentId="content">
    ...
  </ion-menu>
  <ion-router-outlet id="content"></ion-router-outlet>
</ion-app>
```

And then in my tab1 page I call `this.menuController.enable(false)`.

**Comment by blahblehblah** [comment]
Actually after looking through one of the dev's code, there was an issue in enabling it again, i am sorry, sorry for your time. thank you
