### ISSUE TITLE
bug: IonInfiniteScroll problem when datasource is reloaded

### ISSUE THREAD

**Issue by icrocket** [ionic-team/ionic#20996]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
Hi, the IonInfiniteScroll fail when the datasource is reloaded.

It saves his position and making the component unusable.

We have two Pages:

Page A (a list of items loaded with infinitescrolling)
Page B (a detail page of list item)
I was in page A and next, click to item and go to page B for details. When i return back to page A i need to “refresh” the datasource of the ngFor. When the datasource is refreshed, the infinite scroller doesn’t work anymore.

The offsetHeight variable appears to retain the value obtained before the refresh.

**Expected behavior:**
IonInfiniteScroll reset it's position or height.

**Steps to reproduce:**
Load a list of items (100 items for example) with ngFor, next, empty the list and reaload data (only 10 items).

**Related code:**

**Ionic info:**

Ionic:

   Ionic CLI                     : 6.2.1 (C:\Users\X\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.1
   @capacitor/core : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.10.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by icrocket** [comment]
Hi, the "bug" is related to the number of the items on screen. If numbers of items don't cover the height of the viewport, infinite scroller don't fire event.

You can close the issue.
