### ISSUE TITLE
bug: in split-pane, border is invisible in RTL mode

### ISSUE THREAD

**Issue by ataramez** [ionic-team/ionic#20994]
# Bug Report

**Ionic version:**
5.x

**Current behavior:**
in split-pane component, the border between the two panes is invisible if you switched direction from LTR to RTL

**Expected behavior:**
border should be visible

**Steps to reproduce:**
create a new app with the sidemenu template. Run the application and make sure that the width is large enough for the menu pane to be visible. Change HTML direction to RTL.

**Related code:**

**Other information:**
Simple update to scss files in the component will fix the issue. pull request will be opened shortly

**Ionic info:**
Ionic:

   Ionic CLI : 6.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.13.0
   npm    : 6.13.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20995 and will be available in an upcoming release of Ionic Framework.
