### ISSUE TITLE
bug: Using ion-hide-{breakpoint}-up and ion-hide-{breakpoint}-down are both exclusive

### ISSUE THREAD

**Issue by bartboersma** [ionic-team/ionic#20993]
# Bug Report

**Ionic version:**
[x] **5.0.7**

**Current behavior:**
In case I want to show button X only on xs and sm devices so I use ion-hide-md-up. At the same time I want to show button Y only on  md, lg and xl screens so I use ion-hide-md-down. This causes both buttons to be hidden on the screen size with width: 768px. 

**Expected behavior:**
On md screens I expect to see the ion-hide-md-down button. So currently the ion-hide-md-up works fine (screens of 768px wide get hidden), but screens of 768px wide do not get shown with ion-hide-md-down (only screens of 769px and larger)

**Steps to reproduce:**
Copy paste below code, open browser and set width to 768px to see both buttons (left and right of ion-title) are hidden.

**Related code:**
```
<ion-header>
  <ion-toolbar color="dark">
      <ion-buttons class="ion-hide-md-up" slot="start">
        <ion-button>
          <ion-icon slot="icon-only" name="menu"></ion-icon>
        </ion-button>
      </ion-buttons>
      <ion-title class="ion-text-center ion-text-md-left">
        <ion-text class="title" color="tertiary">FAVOURITE</ion-text>
        <ion-text class="title" color="primary">XI</ion-text>
      </ion-title>
      <ion-buttons class="ion-hide-md-down" slot="end">
        <ion-button>
          Select pool
          <ion-icon name="caret-down-sharp"></ion-icon>
        </ion-button>
        <ion-button>
          <ion-icon slot="icon-only" name="person-circle-outline"></ion-icon>
        </ion-button>
      </ion-buttons>
  </ion-toolbar>
</ion-header>
```

The generated code (from display.css) is now:
```
@media (min-width: 768px) {
  .ion-hide-md-up {
    display: none !important;
  }
}
@media (max-width: 768px) {
  .ion-hide-md-down {
    display: none !important;
  }
}
```

In order for this to work .ion-hide-md-down should be max-width: 767px. This also goes for sm-down, lg-down and xl-down

**Comment by brandyscarney** [comment]
Thanks for the issue! I agree with this. I will look into fixing this soon.
