### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by gdevkate34** [ionic-team/ionic#20992]
ERROR in node_modules/@angular/common/http/http.d.ts:81:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/common/http) which declares HttpClient has not been processed correctly by ngcc, or
is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

81 export declare class HttpClient {

Help

**Comment by indraraj26** [comment]
Can you delete node_modules and re-run npm install
