### ISSUE TITLE
bug: IonSlider.getActiveIndex Promise never resolves on second page entry

### ISSUE THREAD

**Issue by pjc2007** [ionic-team/ionic#20999]
**Ionic version:**
[x] **5.0.7**

**Current behavior:**
I have an application using  `IonSlides` on a Page that is lazy loaded. I Have a handler for `ionSlideDidChange`, and in there I call `this.slider.getActiveIndex()`

The first time I enter the page, the call to `this.slider.getActiveIndex()` works fine. However, if I navigate away to another page, and then back to the page with the `slides`, the call to `await getActiveIndex` never returns. Ie the Promise never resolves. It enters the call, and then just hangs there.

This seems to have started after upgrading from Angular 8.1 to Angular 9

**Expected behavior:**
The call to getActiveIndex always has the promise resolve (ie it returns)

**Steps to reproduce / related code**
There is a sample app at `https://github.com/pjc2007/slides`

Run the app, the dev tools console showing so can see  the output.

Click the TO SLIDER PAGE button, and then swipe the slider from left to right, and will see the console output of `getting index`, and then always followed by the `got  index`.

Now click the `TO HOME` button, and then on the home page, click the TO SLIDER PAGE to re-enter the slider page.

Now, again swipe the slider. You will only see the `getting index` message, and no the `got  index`.

Adding a breakpoint you can see the line
```
const index = await this.slider.getActiveIndex();
```
never returns.

**Other information:**
This only occured after I update from Angular 8 to 9

**Ionic info:**

```
$ ionic info

Ionic:

   Ionic CLI                     : 5.2.3 (C:\Users\pchapman\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.901.1
   @angular-devkit/schematics    : 9.1.1
   @angular/cli                  : 9.1.1
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : 0.7.0-testing.0
   native-run  : 0.2.8

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as a fix has already been implemented and will be available in an upcoming release of Ionic Framework.
