### ISSUE TITLE
feat: Add clickable prop in ion-item to toggle 'ion-activatable'

### ISSUE THREAD

**Issue by AliAlmutawakel** [ionic-team/ionic#20990]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

There are scenarios where I would like the item to be _clickable_ **AND** I don't want to add `href` or `button` attributes.
_Simply_ a way to toggle the clicking effect.

**Describe Preferred Solution**

- In `core/src/components/item/item.tsx`
- Add `@Prop() clickable : 'default' | 'always' | 'never' = 'default';`
- Edit `canActivate()` function as so:
```typescript
  private canActivate(): boolean {
    switch(this.clickable){
      case 'always':
        return true;
      case 'never':
        return false;
      default:
        return (this.isClickable() || this.hasCover());
    }
  }
```

**Describe Alternatives**

- I've tried adding `button`, however it adds an arrow which could be misleading.
- I've tried (below), however, when I have anything in slot="start", ripple/highlight effect doesnt span the entire `ion-item`
  1. Wrapping `ion-item` with a `<div class="ion-activatable">`
  2. Adding `<ion-ripple-effect>` inside the item.
- I've trief `href="#"`, but that doesn't work in any single-page app.

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is already possible in Ionic Framework. When adding `button="true"` to the item, you can set `detail="false"` to remove the arrow icon.

CodePen example: https://codepen.io/liamdebeasi/pen/vYNBLZq

**Comment by AliAlmutawakel** [comment]
Thanks for the reply. Setting `detail="false"` leaves the item _unclickable_.

But I think you meant like this: `<ion-item button="true" detail="false">` which worked.
