### ISSUE TITLE
feat: Add iOS rounded list style to <ion-list> (iPad and landscape iPhone X, 11,...)

### ISSUE THREAD

**Issue by wilk-polarny** [ionic-team/ionic#21002]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**
It would be nice to have an optional tablet apperance for the `<ion-list>` element to match the style of iOS. In iOS, lists will have a different padding and border style noticable on tablets and on newer iPhones (iPhone X, 11,...) in landscape mode.

![image](https://user-images.githubusercontent.com/819238/78901472-a8825780-7a78-11ea-8896-cbbc62f93343.png)

**Describe Preferred Solution**
Preferably automatic adjustments based on the width, or some kind of directive/switch

**Describe Alternatives**
A DIY solution, which we actually implemented by restyling the components - but it would be better to have such a feature out of the box. 

**Related Code**
None.

**Additional Context**
None.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is already possible in Ionic Framework.

You do need to apply a few styles, but for the most part you can just use the existing infrastructure provided by our components: https://codepen.io/liamdebeasi/pen/dyYyzoe.
