### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by joshoconnor89** [ionic-team/ionic#21004]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When opening and closing the slider, it flickers sometimes (on chrome and android).  This only occurs when closing the slider without gesture.

**Expected behavior:**

No flicker when closing the app 

**Steps to reproduce:**

Install ionic 5
Run on Chrome or Android
When closing the slider, it flickers

**Related code:**

```
<ion-menu
  menuId="sliding-menu"
>
</ion-menu>

<div main class="cu-manager2__container">
```

**Other information:**

Here is a video of me reproducing this issue:
https://www.youtube.com/watch?v=t4K4dAP9KAA&feature=youtu.be

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce the issue?
