### ISSUE TITLE
bug: Cannot update a component from inside the function body of a different component.

### ISSUE THREAD

**Issue by selahattintoprak** [ionic-team/ionic#21005]
# Bug Report
setSelectedPage(props.match.params.name);

is causing the problem

**Ionic version:**
[x] **5.x**
ionic sidemenu project from ionic start
**Current behavior:**

index.js:1 Warning: Cannot update a component (`App`) while rendering a different component (`Context.Consumer`). To locate the bad setState() call inside `Context.Consumer`, follow the stack trace as described in https://fb.me/setstate-in-render
    in Route (at App.tsx:37)
    in View (created by StackManagerInner)
    in ViewTransitionManager (created by StackManagerInner)
    in ion-router-outlet (created by IonRouterOutlet)
    in IonRouterOutlet (created by ForwardRef(IonRouterOutlet))
    in ForwardRef(IonRouterOutlet) (created by StackManagerInner)
    in StackManagerInner (created by Context.Consumer)
    in Unknown (created by Component)
    in Component (created by ForwardRef(IonRouterOutlet))
    in ForwardRef(IonRouterOutlet) (at App.tsx:36)
    in ion-split-pane (created by IonSplitPane)
    in IonSplitPane (created by ForwardRef(IonSplitPane))
    in ForwardRef(IonSplitPane) (at App.tsx:34)
    in NavManager (created by RouteManager)
    in RouteManager (created by Context.Consumer)
    in RouteManager (created by IonReactRouter)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by IonReactRouter)
    in IonReactRouter (at App.tsx:33)
    in ion-app (created by IonApp)
    in IonApp (created by ForwardRef(IonApp))
    in ForwardRef(IonApp) (at App.tsx:32)
    in App (at src/index.tsx:6)
**Expected behavior:**

**Steps to reproduce:**

NPM Start 
**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.5.0 (C:\Users\Rob\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.0.7

Capacitor:

   Capacitor CLI   : 2.0.0
   @capacitor/core : 2.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.7
   OS     : Windows 10
```

**Comment by elylucas** [comment]
Thanks for the issue. I updated the sidemenu starter to fix the error. It should be available shortly for new Ionic apps. You can see the changes here if you want to implement them in your own project: https://github.com/ionic-team/starters/pull/1218
