### ISSUE TITLE
bug: div toolbar-title created by shadow root overwrites header z-index, causing graphical error

### ISSUE THREAD

**Issue by atlowell-smpl** [ionic-team/ionic#21011]
# Bug Report

**Ionic version:**
[x] **5.22.0**

**Current behavior:**
When using an ion-toolbar within an ion-header, using an ion-title sets the ion-toolbar's title. This causes the shadow root to apply a <div class="toolbar-title"> element. This element inherits the base z-index of 10, and is not overwritten by changing the z-index of the header, toolbar, or title. This leads to a strange graphical glitch where part of the header looks like it is at a different z-index from the rest.

**Expected behavior:**
The z-index should match the z-index of the parent elements.

**Steps to reproduce and related code:**
Using the following html:

```bash
<ion-header>
  <ion-toolbar>
    <ion-title>
      Test
    </ion-title>
  </ion-toolbar>
</ion-header>
```

and the following css class:

```bash
.z-change {
  z-index: 0;
}
```

Applying the "z-change" class to the ion-header, ion-toolbar, ion-title, or any combination of the above results in the aforementioned graphical issue, where part of the header is z-index 0 and part is z-index 10.

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\Austin\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.803.22
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by NikolaPeevski** [comment]
From my understanding the framework generates Z indexes on its own. Are you using Ion header/footer in your app component sandwitching an ion-router-outlet ?

**Comment by atlowell-smpl** [comment]
@liamdebeasi I've uploaded a version of the repository I was using, slimmed down as much as is reasonable to only have the necessary parts to demonstrate the issue.

https://github.com/atlowell-smpl/Ionic-Angular-Z-Index-Header-Toolbar-Demonstration

Interestingly, when removing some of the styling, it seemed to change the graphical glitch I was seeing. After some more testing, I realized that it had to do with how the margins of the ion-split-pane I was using below the header were being set.  Essentially, if the split pane contents were set to overlap with the header, the z-index difference disappeared, while as if the margins were set to push them down below the header, the z-index difference existed.

This is what I was seeing in my repository:

![image](https://user-images.githubusercontent.com/59400353/79053148-0d6cb780-7c09-11ea-9312-9c5901da6b4d.png)

Using the following code:
```bash
<ion-header class="z-page">
  <ion-toolbar>
    <ion-title>
      bevuu<span class="title-secondary">.app</span>
    </ion-title>
  </ion-toolbar>
</ion-header>
```

```bash
.z-page {
    z-index: 0 !important;
}

ion-toolbar {
    margin-top: 20px;
}

ion-title {
    margin-left: 3.5vw;
    font-family: 'Source Sans Pro';
    font-weight: bold;
    font-size: 46px;
    letter-spacing: 1.1px;
    line-height: 58px;
}

span.title-secondary {
    //color: #ffa737;
    color: var(--ion-color-secondary);
}
```

And this is what I see in the test repository I linked:

![image](https://user-images.githubusercontent.com/59400353/79053199-76542f80-7c09-11ea-9859-b94a172dd5e8.png)

As you can see, the main difference is how the margins are set. In my repository, an additional margin is placed at the top, causing the contents of the split pane to overlap with the contents of the header on the menu, causing that strange graphical glitch. Interestingly enough, the right side of the split pane doesn't have that issue. I find it likely that somewhere in my code an additional margin is set to cause this behavior.

Either way, I would still consider this a bug. As you can see, the shadow dom is still applying divs to the header with z-indexes of 10. This happens even if you extend the ".z-page" class to the ion-toolbar and ion-title.

**Comment by atlowell-smpl** [comment]
@NikolaPeevski not quite. I'm using a layout that looks similar to the following:

```bash
<ion-header>
  <ion-toolbar>
    <ion-title>Hello</ion-title>
  </ion-toolbar>
</ion-header>
<ion-split-pane contentId="main-content">
  <ion-menu contentId="main-content" type="overlay">
    <ion-content>
      Menu
    </ion-content>
  </ion-menu>
  <ion-router-outlet id="main-content"></ion-router-outlet>
</ion-split-pane>
```

The full details can be seen in the repository I linked.  I am using an ion-router, but only as part of an ion-split-pane. And I do not use an ion-footer.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. It looks like there is `margin: 8px` being applied to the `body` element via a user agent style sheet. 

Add the following to `global.scss`:
```css
body {
  margin: 0px;
}
```

Does that adding that CSS resolve the issue?

**Comment by atlowell-smpl** [comment]
Adding that seems to have no effect.

**Comment by liamdebeasi** [comment]
Are you adding this to `global.scss` in an Ionic application? I noticed that the repo you provided does not have that file added.

**Comment by atlowell-smpl** [comment]
Yes, I added it to the global.scss file in the project that I first noticed the issue on (screenshotted above).

**Comment by liamdebeasi** [comment]
Can you update the provided repo with the `global.scss` file? When I add it myself the issue is resolved.

**Comment by atlowell-smpl** [comment]
Added to the repository. It does not fix the issue on my end.  My thinking is that any margin-related solution would be similar to the bandaid "fix" I mentioned above, in that it will hide the problem in some cases but will not actually address the root issue, which is that the generated shadow root components have a different z-index.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Could you clarify what the issue you are running into is? Perhaps I misunderstood the original post. The application seems to be displaying fine for me.

![image](https://user-images.githubusercontent.com/2721089/79165892-0d5beb80-7db2-11ea-8efc-683e116f5c53.png)

**Comment by atlowell-smpl** [comment]
The ion-header in the example repository has a "z-page" class applied to it, which sets the "z-index" of the header to 0. Since 0 is also the z-index of the page, both components should be at the same level. If you inspect the ion-header in a developer console, you can see that the header itself has a z-index of 0, but that the generated shadow root components have z-indexes of 10 (what the header defaults to). As a result, you end up with the "height difference" separation bar below the header that you can see in that screenshot, despite the fact that the header is set to be at the same z-index of the page.

Maybe I'm misunderstanding how the ion-header is supposed to work?  I assumed that the ion-header is supposed to use the z-index to determine how/whether to show the separator. So for instance, a lower z-index than the page would cause an inverse height difference bar, and the same z-index would cause no bar (smooth transition). But I can't seem to get it to exhibit any of this behavior, the bar is always present unless it it written over by other components (such as in the margin example I mentioned earlier).

**Comment by atlowell-smpl** [comment]
As an example of the expected appearance, here is what I get when I remove the <ion-header> component but keep the toolbar and title:

![image](https://user-images.githubusercontent.com/59400353/79246788-a5f07b00-7e47-11ea-9f84-b6259b73ae68.png)

**Comment by liamdebeasi** [comment]
Thanks for the follow up. When running in MD mode, we do apply a background-image to the `::after` pseudo element for `ion-header` to give it a divider/drop shadow effect. Rendering an actual `box-shadow` is a bit less performant than rendering an image, so we just render a background image instead.

In order to get rid of the divider, you can just do:

```css
ion-header::after {
  content: initial !important;
}
```

Does this resolve your issue?

**Comment by atlowell-smpl** [comment]
Adding that does seem to cause the desired behavior, thank you!

I was under the impression that that background image in the ::after was conditional on the z-score, but I guess that was a faulty assumption on my part. Thanks for your help, I'll close the issue.
