### ISSUE TITLE
feat: ripple effect with color props

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic#21016]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

Right now you will get same ripple color as your text content color. Can we add color props to have different ripple color than text color.

**Describe Preferred Solution**

Do not inherit color from parent div text color.  
So new syntax can be 
```
      <ion-ripple-effect type="unbounded" color="yellow"></ion-ripple-effect>
```

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I am going to close this as customizing the ripple effect is already possible via CSS. 

CodePen example: https://codepen.io/liamdebeasi/pen/yLYNGMB

To use the Ionic theme colors, you can use the CSS variables provided in the documentation.
Themes: https://ionicframework.com/docs/theming/themes 
Color Generator: https://ionicframework.com/docs/theming/color-generator
