### ISSUE TITLE
feat: Could you provide all required CSS variables for all the ionic shadow components?

### ISSUE THREAD

**Issue by shyamal890** [ionic-team/ionic#21014]
I wonder why https://github.com/ionic-team/ionic/issues/20044 was closed in the first place. 

One end up needing to modify component styling for their own need. How is Ionic currently catering to this need when critical issues like these are closed?! 

For example, I wanted to set a CSS property `font-weight` for `Ion-chip` found out its not available. 

Kindly let me know how can I customize the style with just 2 CSS properties open for modification?

**Ionic version:**
4.x

**Comment by shyamal890** [comment]
I see that work is going on to add `CSS Shadow Parts` however, I don't see the same for `ion-chip` or `ion-label` kindly add those.

**Comment by NikolaPeevski** [comment]
Unless I've understood something wrong you can setup the font weight without any issues.

```
ion-chip {
  ion-label {
    font-weight: 900;
  }
}
```

**Comment by indraraj26** [comment]
Working fine for me without any hax : https://stackblitz.com/edit/ion-chip?file=src%2Fapp%2Fapp.component.html

**Comment by shyamal890** [comment]
Oh my bad, I am able to apply it thanks.
