### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by DaveRicho** [ionic-team/ionic#21025]
# Bug Report 
(with work around)

"@ionic/angular": "^5.0.7"
"@capacitor/core": "^2.0.1"
"@capacitor/ios": "^2.0.1"
"@angular/core": "~9.1.1"

**Current behavior:**
ios menu icon and back button in ion-toolbar are respectively disappearing and moving half way down the screen after the above upgrades (Web and Android seem fine).

Took me a while to work out what was going on with my ion-toolbars, but alas it was the buttons within the toolbar that seemed to be the issue (I think....)

**Expected behavior:**
Expect to be able to use menu button and back button in the toolbar after builds for ios (just as works in Android and Web)

**Steps to reproduce:**
I updated my project and found this problem.

I was able to work around (after many hours of learning and discovery!!) by adding the following to my variables.scss file:

```
.ios .can-go-back > ion-header ion-back-button {
  display: grid;
}

.ios ion-menu-button {
  display: grid;
}
```

In the case of ion-back-button, I think I remember seeing the display set to **flex**. As soon as I changed it to **grid**, the problem was solved.

I hope this helps the team to spot the ios issue and someone else upgrading.

This is my first issue post. I wish I knew more and could make a pull request to help the team fix this, but I am still learning....

 I love the ionic team and and the ionic community! Stay safe and productive everyone!!

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by DaveRicho** [comment]
Hi Liam,
I’m afraid that I won’t be able to easily post code as this comes from a private repo. I’m not going to get the chance to try to replicate the setup in the near term (now that the Easter break is over).
Hopefully no one else has the issue. 
Completely understand that I’ve been pretty useless in helping you solve this issue and that you may have to close the issue.
The work around posted above got me around the problem. 
Thanks,
Dave.

**Comment by liamdebeasi** [comment]
No worries! I will close the issue for now, but if you are able to get a reproduction feel free to open a new issue. Thanks!
