### ISSUE TITLE
bug: @ionic/angular 5.0.6 and 5.0.7 - ion-input laggy response on iOS

### ISSUE THREAD

**Issue by RichardPilbery** [ionic-team/ionic#21023]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

Reactive form is slow to respond when user taps an input fields on iOS (not Android). Noticeable delay between tapping on field and cursor appearing

**Expected behavior:**

Cursor appears in tapped field immediately.

**Steps to reproduce:**

1. Install demo app from GitHub link below
2. cd into folder
3. npm install
4. ionic serve
5. Open Developer Tools in Google Chrome
6. Toggle device toolbar
7. Choose an iOS device
8. Refresh page and tap on any input field (select fields work fine)
9. Choose an Android device
10. Refresh page and tap on any input field

**Related code:**

A sample application is available via GitHub: [https://github.com/RichardPilbery/ionic_angular_lag_issue](https://github.com/RichardPilbery/ionic_angular_lag_issue)

**Other information:**

Reverting the @ionic/angular version back to 5.0.5 resolves the issue.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.4.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.4.0 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This issue has already been resolved and a fix will be available in an upcoming release of Ionic Framework.

**Comment by jayordway** [comment]
@liamdebeasi Are you going to link any additional information about this fix to this issue? We have no way of tracking this fix otherwise.

**Comment by liamdebeasi** [comment]
PR that fixes the issue: https://github.com/ionic-team/ionic/pull/20987
Original issue reporting the bug: https://github.com/ionic-team/ionic/issues/20922

**Comment by liamdebeasi** [comment]
When the fix ships, we will mention it in our [CHANGELOG](https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md) file along with a link to the commit and #20922. We will also mention it on our [Releases Page](https://github.com/ionic-team/ionic/releases).
