### ISSUE TITLE
feat: Add ability to specify "enterkeyhint" attribute on ion-input and ion-searchbar components

### ISSUE THREAD

**Issue by dennismorello** [ionic-team/ionic#21034]
**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
Now that both Chrome and Safari support the "enterkeyhint" attribute on the `<input>` element, we could use it to specify the appearance of the Enter button when the virtual keyboard appears.

**Describe Preferred Solution**
The `ion-input` component accepts an "enterkeyhint" prop that is passed down to the underlying <input> HTML element.

**Additional Context**
Reference: https://html.spec.whatwg.org/multipage/interaction.html#input-modalities:-the-enterkeyhint-attribute

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21035 and https://github.com/ionic-team/ionic/pull/21036. This feature will be available in an upcoming release of Ionic Framework.
