### ISSUE TITLE
bug: after navigate between nested tabs, IonTabButton didn't work correctly

### ISSUE THREAD

**Issue by Yansuuu** [ionic-team/ionic#21031]
# Bug Report

**Ionic version:**

[x] **5.0.7**

**Current behavior:**

I have two tabs with sub tab:
- Tab1
  + SubTab1
- Tab2
  + SubTab2

What I do:
1. go to SubTab1 by history.push (in Tab1)
2. go to SubTab2 by history.push (in SubTab1)
3. click IonBackButton twice, go back to Tab1
4. click IonTabButton for Tab2, show me SubTab2 page
5. click IonBackButton in SubTab2, show me Tab1 page

**Expected behavior:**

1~3 the same as above
4. when I click IonTabButton for Tab2 show me Tab2, not SubTab2

**Steps to reproduce:**

[A sample](https://stackblitz.com/edit/react-ts-ha377s?file=src%2FApp.tsx)
**Related code:**

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.5.0 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.0.7

Capacitor:

   Capacitor CLI   : 2.0.1
   @capacitor/core : 2.0.1

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.6
   OS     : Windows 7
```

**Comment by elylucas** [comment]
Hi @Yansuuu,

We have a dev release that should fix this issue. If you can, could you try to install it and let us know if it fixes the issue and if you run into any others? To install it run:

`npm i @ionic/react@5.3.0-dev.202006222125.df37029 @ionic/react-router@5.3.0-dev.202006222125.df37029`

If all goes good this should be available in the next Ionic release.

Thanks!

**Comment by Yansuuu** [comment]
Hi @elylucas ,
Sorry for my late reply.
This exactly what i need!
And my code is simple, so i don't run into any other issues.
Thanks a lot!
