### ISSUE TITLE
feat: Add DOM ready/pre-add hooks for components using Shadow DOM

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic#21030]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

The use of Shadow DOM has many benefits, and without a doubt is a huge improvement; however, it often leaves developers lacking the fine-grained control to implement a production application theme -- sometimes also functionality. 

The current workaround for Shadow DOM has been to create afterViewInit hooks that inspect the component for a shadowRoot node, then manipulate it there. However, this often occurs asynchronously, and too late. 

Example A: shadowRoot element does not exist in context of normal Lifecycle Hooks
````
ngAfterViewInit() {
    const mainElmt = elmt.shadowRoot.querySelector('main'); // sometimes does not exist 
}
````

The shadow DOM element is sometimes not created at this time, and forces a timeout/wait loop until the node is ready. This is both bad for performance, and also bad for user experience, as the DOM element may be added to the view before hooks can act on it. The user may (and often does) see the pre-customized DOM before it is modified by the custom directive or lifecycle hook.

In the example of scroll bars. The native scroll bar will often appear before the hook takes place, which triggers reflow/browser layout once new styles are applied and the scroll bar is resized or hidden entirely.

In order to continue to use Shadow DOM functionality while still allowing for high-performance, consistent, reproducible customization and control of things like scrollbars (see https://github.com/ionic-team/ionic/issues/17685), advanced layout and styles, etc, I would like to propose the following feature for ALL stencil/Shadow DOM based components.

**Describe Preferred Solution**

Add a pre-DOM insertion or DOM ready hook to all Ionic components.

````
class MyDirective {
    // Component is provided to directive via Input, or via constructor injection.
    @Input() componentRef: IonContent;

    constructor( private cmp: StencilComponent ){

         // New hook - simple example usage
         cmp.onDomReady((el: ElementRef) => {
              const mainElmt = el.shadowRoot.querySelector('main'); // Guaranteed to exist if the component uses Shadow DOM.
              ....
         })
    }

    ngOnInit() {
        // For components passed via inputs
    }
}
````

This would ensure a consistent and deterministic ability to access component DOM nodes *before* they are added to the application DOM, and would allow safer, faster, more reliable customization of component styles without relying on timing loops and other "hacks/workarounds."

**Describe Alternatives**

Use a wait loop to assure that the DOM is ready. This has the aforementioned downside of causing flicker, reflow, and performance overhead:

Example B: Using Timeout loops to wait for shadowRoot element
````

  ngAfterViewInit() {
    this.styleScrollbars(...);
  }

  styleScrollbars(elmt: HTMLElement, style: ScrollStyle, retry: number) {
    const def = STYLES[style];
    const styleElmt = elmt.shadowRoot.querySelector('style');
    const mainElmt = elmt.shadowRoot.querySelector('main');

    if (styleElmt && mainElmt) {
      styleElmt.append(def.stylesheet);
    } else if (retry > 0) {
      setTimeout(() => {
        this.styleScrollbars(elmt, style, --retry);
      }, RETRY_DELAY = 15);
    } else {
      const barStyle = document.createElement('style');
      elmt.shadowRoot.appendChild(barStyle);
  }
````

**Related Code**

**Additional Context**

https://github.com/ionic-team/ionic/issues/17685

Although there are many other issues in the issue tracker from users asking how to properly customize (beyond CSS variables), elements that are locked behind the Shadow DOM.

A few:
https://github.com/ionic-team/ionic/issues/20044
https://github.com/ionic-team/ionic/issues/20177
https://github.com/ionic-team/ionic/issues/18021
https://github.com/ionic-team/ionic/issues/17425
https://github.com/ionic-team/ionic/issues/18476
https://github.com/ionic-team/ionic/issues/19991

Thank you for your consideration.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as Ionic Framework does not manage the Stencil lifecycle hooks. If you have a request for Stencil components, I recommend opening an issue at https://github.com/ionic-team/stencil.

Additionally, all Stencil components expose a `componentOnReady` method that resolves when the component has been initialized. You can use this for Ionic components as all Ionic components are built with Stencil.

**Comment by lincolnthree** [comment]
@liamdebeasi I don't see componentOnReady, but I do see the `ComponentInterface` interface which has 'componentDidLoad'. Is that what you're referring to?

**Comment by lincolnthree** [comment]
Found it:

https://github.com/ionic-team/stencil/blob/master/src/declarations/stencil-public-runtime.ts#L291

**Comment by lincolnthree** [comment]
Affirmative, this seems to work, though there is still a flicker as I believe the DOM has already been modified. I think we still may need to file an issue for an additional lifecycle hook.
