### ISSUE TITLE
Samsung S series keyboard , Input not appearing unless a special character is typed

### ISSUE THREAD

**Issue by mthizozo** [ionic-team/ionic#21033]
Hi 

I am experiencing an issue with ionic v4 where samsung s users cannot see the letters they type unless they type a special character, the keyboard also adds words from previous input into a field. 

Please assist urgently as users are really having a bad experience and i might have to move to another platform if i cannot resolve this promptly.

[Screen_Recording_20200414-065744.mp4.zip](https://github.com/ionic-team/ionic/files/4474103/Screen_Recording_20200414-065744.mp4.zip)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by mthizozo** [comment]
Hi There , 
<ion-header >
  <ion-toolbar>
  </ion-toolbar>
</ion-header>

<ion-content   class="background">
  <div class="top">
      <ion-buttons slot="start">
          &nbsp;&nbsp;&nbsp;<ion-back-button defaultHref="home" icon="backbtn" [text]="getBackButtonText()"></ion-back-button>
        </ion-buttons> 
  </div>
  
<h1> Sign in</h1>
  <ion-card>
    <ion-card-content class="login">
        <form [formGroup]="loginFormGroup">
          <mat-form-field>
            <input type="email" matInput placeholder="email" formControlName="email" required [errorStateMatcher]="matcher">
            <mat-error *ngIf="loginFormGroup.get('email').hasError('email')" >Invalid email</mat-error>
          </mat-form-field>
          <mat-form-field>
              <input type="password" matInput placeholder="password" formControlName="password" required>
            </mat-form-field>
            
            <ion-button expand="full" (click)="login()" [disabled]="loginFormGroup.invalid || isloading" class="submit" mat-button >Sign In</ion-button>
          
        </form>
        <a  [routerLink]="['/forgot-password']">Forgot Password ?</a>
      
    </ion-card-content>
  </ion-card>
  <p>By Signing in , I agree and sign the <a [routerLink]="['/termsand-conditions']"> Ts&amp;Cs</a></p>


</ion-content>


    <ion-footer class="hide-on-keyboard-open">
  
        <div class="footer">
          <div class="contact">
            <a [routerLink]="['/contact-page']"> <ion-icon name="contactlight"></ion-icon>
            </a>
            </div>
        </div>
       
     </ion-footer>

**Comment by mthizozo** [comment]
`<ion-header >
  <ion-toolbar>
    <ion-img src="../assets/images/DC-logo@3x.png"></ion-img>
  </ion-toolbar>
</ion-header>

<ion-content   class="background">
  <div class="top">
      <ion-buttons slot="start">
          &nbsp;&nbsp;&nbsp;<ion-back-button defaultHref="home" icon="backbtn" [text]="getBackButtonText()"></ion-back-button>
        </ion-buttons> 
  </div>
  
<h1> Sign in</h1>
  <ion-card>
    <ion-card-content class="login">
        <form [formGroup]="loginFormGroup">
          <mat-form-field>
            <input type="email" matInput placeholder="email" formControlName="email" required [errorStateMatcher]="matcher">
            <mat-error *ngIf="loginFormGroup.get('email').hasError('email')" >Invalid email</mat-error>
          </mat-form-field>
          <mat-form-field>
              <input type="password" matInput placeholder="password" formControlName="password" required>
            </mat-form-field>
            
            <ion-button expand="full" (click)="login()" [disabled]="loginFormGroup.invalid || isloading" class="submit" mat-button >Sign In</ion-button>
          
        </form>
        <a  [routerLink]="['/forgot-password']">Forgot Password ?</a>
      
    </ion-card-content>
  </ion-card>
  <p>By Signing in , I agree and sign the <a [routerLink]="['/termsand-conditions']"> Ts&amp;Cs</a></p>


</ion-content>


    <ion-footer class="hide-on-keyboard-open">
  
        <div class="footer">
          <div class="contact">
            <a [routerLink]="['/contact-page']"> <ion-icon name="contactlight"></ion-icon>
            </a>
            </div>
        </div>
       
     </ion-footer>
  `

**Comment by mthizozo** [comment]
`<ion-header >
  <ion-toolbar>
    <ion-img src="../assets/images/DC-logo@3x.png"></ion-img>
  </ion-toolbar>
</ion-header>

<ion-content   class="background">
  <div class="top">
      <ion-buttons slot="start">
          &nbsp;&nbsp;&nbsp;<ion-back-button defaultHref="home" icon="backbtn" [text]="getBackButtonText()"></ion-back-button>
        </ion-buttons> 
  </div>
  
<h1> Sign in</h1>
  <ion-card>
    <ion-card-content class="login">
        <form [formGroup]="loginFormGroup">
          <mat-form-field>
            <input type="email" matInput placeholder="email" formControlName="email" required [errorStateMatcher]="matcher">
            <mat-error *ngIf="loginFormGroup.get('email').hasError('email')" >Invalid email</mat-error>
          </mat-form-field>
          <mat-form-field>
              <input type="password" matInput placeholder="password" formControlName="password" required>
            </mat-form-field>
            
            <ion-button expand="full" (click)="login()" [disabled]="loginFormGroup.invalid || isloading" class="submit" mat-button >Sign In</ion-button>
          
        </form>
        <a  [routerLink]="['/forgot-password']">Forgot Password ?</a>
      
    </ion-card-content>
  </ion-card>
  <p>By Signing in , I agree and sign the <a [routerLink]="['/termsand-conditions']"> Ts&amp;Cs</a></p>


</ion-content>


    <ion-footer class="hide-on-keyboard-open">
  
        <div class="footer">
          <div class="contact">
            <a [routerLink]="['/contact-page']"> <ion-icon name="contactlight"></ion-icon>
            </a>
            </div>
        </div>
       
     </ion-footer>
  `

**Comment by mthizozo** [comment]
<mat-form-field>
            <input type="email" matInput placeholder="email" formControlName="email" required [errorStateMatcher]="matcher">
            <mat-error *ngIf="loginFormGroup.get('email').hasError('email')" >Invalid email</mat-error>
          </mat-form-field>
          <mat-form-field>
              <input type="password" matInput placeholder="password" formControlName="password" required>
            </mat-form-field>

Hi I am using material input fields , could that possibly be the issue?

**Comment by mthizozo** [comment]
` <mat-form-field>
            <input type="email" matInput placeholder="email" formControlName="email" required [errorStateMatcher]="matcher">
            <mat-error *ngIf="loginFormGroup.get('email').hasError('email')" >Invalid email</mat-error>
          </mat-form-field>
          <mat-form-field>
              <input type="password" matInput placeholder="password" formControlName="password" required>
            </mat-form-field>`

Hi I am using material input fields instead of ion-input, could that be the issue?

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Try using `ion-input` and see if that fixes the issue.
