### ISSUE TITLE
bug: ion-modal behavior with slow networks

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/ionic#21045]
# Bug Report

**Ionic version:**
[x] **5.0.7**

**Current behavior:**

If the user is working over a slow network with long latency then `ion-modal` (as well as alerts and other overlay components) do not provide async rendering indicators to help provide cues that an operation is in progress.

This bug is related to the usage of Ionic in a web application.

For example, if I simulate a Slow 3G network and then click on a button in the app to open a dialog it takes 6 seconds for the dialog to appear (even for a tiny component):
```
- 2 seconds to load the entry.js file that contains <ion-modal>
- 2 seconds to load the entry.js file for my modal component
- 2 seconds to load the import dependencies for my component
- Dialog appears (6 seconds have elapsed)
- 2 seconds to load icons
- Dialog fully rendered (8 seconds)
```

Issues:
- There is no visual indication that anything is happening.  This may cause the user to think it is not working.
- The underlying page is still fully interactive while waiting for the modal dialog to appear.  This allows the user to click on the button multiple times (and cause multiple instances of the dialog to eventually appear), click on other buttons that cause other dialogs to appear, navigate to another page, etc.
- There is no way to cancel the slow operation - even if it takes a very long time.  Using an extreme example with 30 second latency it took 90 seconds for the dialog to appear.
- Any async data loading in componentWillLoad can further add to the time to display the dialog
- Certain actions may have significant impact if invoked multiple times.  E.g. a "one click ordering" button that displays an alert to confirm the action.  If the alert does not appear and the user keeps clicking on the button they can generate multiple orders.

Note that slow latency is not limited to 3G network connections.  One recent example I have seen is a user with a Comcast cable modem running 50mb but seeing latency up to 500ms.  This resulted in a non responsive app that seemed like it was not working.

**Network errors:**

If there is a network request failure the problems are worse.
- There is no indication that there was a failure
- No dialog is displayed so the user is likely to keep clicking on the button
- If the network connection is restored the dialog will still not work.  The only way the user can get it to work again is to refresh the entire page.  If the user is running as a PWA then they will not be able to refresh the page and the app will stop working with no easy fix.

Network errors can occur when:
- Network connection is lost temporarily
- File is not found (e.g. deployed new version of app and did not keep old js files in place)
- Other http errors

**Desired behavior:**

Handle slow networks:
- ability to prevent further user actions from beginning (e.g. overlay).  Note that `<ion-modal>` may not yet be loaded so may need to ensure some baseline loading in `<ion-app>`
- ability to show progress indicator if taking too long
- ability to cancel if taking too long

Handle network errors:
- ability to show error indicators for errors loading ion-modal or the modal component
- ability to start working again if the network connection is restored

**Steps to reproduce:**

One way to simulate a slow network is to use Chrome DevTools:
```
1. Open Chrome DevTools
2. Select `Network` tab
3. Select `Disable cache` checkbox (to avoid loading from local disk cache)
4. Change pulldown from `Online` to `Slow 3G` to simulate loading latency
5. Open any Ionic based web app and click on buttons to display modal dialogs
```

To simulate network request failure:
```
1. Select `Disable cache` checkbox (to avoid loading from local disk cache)
2. Change pulldown from `Online` to `Offline`
3. Click on a button to display a dialog.  Http error is logged but nothing is displayed.
4. Change back to `Online` to see how the app handles trying again
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. All Ionic components are lazy loaded to improve initial render time. If you need to account for slow network conditions in a PWA, you should consider preloading the components needed by placing them inside of `ion-app` (with a `display: none`).

Example of a preloaded modal: https://codepen.io/liamdebeasi/pen/NWGxjNZ
Example of a non-preloaded modal: https://codepen.io/liamdebeasi/pen/QWjyvvw

For both, try throttling the network speed to "Slow 3g" in the `Network` tab in Chrome Developer Tools to see the difference.
