### ISSUE TITLE
feat: Add css variable for button color in ion-alert

### ISSUE THREAD

**Issue by jarrodkoch** [ionic-team/ionic#21048]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
I would like to have a css variable for the color attribute of the buttons within ion-alert.

**Describe Preferred Solution**
A css variable to represent the color css attribute for buttons within ion-alert.

**Describe Alternatives**
Nothing obvious comes to mind.  We have chosen to override --ion-color-primary for our application, but we do not want this to affect buttons in ion-alert, so we have had to add css which depends on class names internal to ionic's alert implementation to get the button color we prefer.

**Related Code**
This is how we have accomplished applying color to the buttons within ion-alert specifically.
`
ion-alert {
  .alert-button {
    color: var(--our-button-color)
  }
}
`

**Additional Context**
As this currently uses --ion-color-primary, it is difficult to adjust this color specifically without affecting other components.  We would like to have the ability to set the color for this specifically without affecting other styling.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is already possible in Ionic Framework. `ion-alert` is not a shadow component, so you can apply the styles directly to the element. In the event that they are getting overridden, you will need to add `!important` (see https://github.com/ionic-team/ionic/issues/17425 for more information).
