### ISSUE TITLE
bug:  ion-refresher in two different tabs does not work 

### ISSUE THREAD

**Issue by Epameinondas-Theodoropoulos** [ionic-team/ionic#21044]
# Bug Report

**Ionic version:**
    "@capacitor/android": "^1.4.0",
    "@capacitor/core": "1.4.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.7.1",
  

**Current behavior:**
I have 2 different pages with the ion-refresher which are in tabs. When I go to one page and start to pull the page, the refreshing operates properly.  But when i click the other tab an try to pull the page nothing happens. It does not show the spinner , or the text or something. It remains static. The same behavior is happening if i start with the other tab and continue then to the second tab.

**Expected behavior:**
The expected behavior is the ion-refresher to work in both tabs and to operate the same and to allow pulling.

**Steps to reproduce:**

**Related code:**

home.page.html
```<ion-tabs>
  <ion-tab-bar slot="bottom">
    <ion-tab-button tab="regular-posts">
      <ion-label>Regular Posts</ion-label>
      <ion-icon name="search"></ion-icon>
    </ion-tab-button>
    <ion-tab-button tab="science-posts">
      <ion-label>Science Posts</ion-label>
      <ion-icon name="card"></ion-icon>
    </ion-tab-button>
  </ion-tab-bar>
</ion-tabs>```

science.page.html

```<ion-content>
  <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)" [disabled]="false" >
    <ion-refresher-content
      refreshingSpinner="bubbles"
      refreshingText="Refreshing...">
    </ion-refresher-content>
  </ion-refresher>
<ion-content>```

regular.posts.html

```<ion-content>
  <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)" [disabled]="false" >
    <ion-refresher-content
      refreshingSpinner="bubbles"
      refreshingText="Refreshing...">
    </ion-refresher-content>
  </ion-refresher>
<ion-content>```


**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.13 (C:\Users\EPAMEINONDAS\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Capacitor:

   Capacitor CLI   : 1.4.0
   @capacitor/core : 1.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v11.5.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by Epameinondas-Theodoropoulos** [comment]
I am sorry about this, but it was my mistake and I feel stupid that I did not do more research on my code. The refresher do his job fine. It was my mistake. Sorry again about the commotion
