### ISSUE TITLE
feat: ion-card as button transparent background in shadow dom

### ISSUE THREAD

**Issue by Spinnenzunge** [ionic-team/ionic#21041]
# Feature Request
Ion-Card with the attribute button renders a button in the shadow dom. Could you please make the buttons element background transparent or expose it as a css variable.

As it is now the button in the shadow dom hides inner shadow set on the ion-card for example which limits styling.

**Ionic version:**

[x] **5.0.7**

**Describe the Feature Request**

Set background of shadow dom button of ion-card to transparent or expose as css variable

**Related Code**

<img width="308" alt="Screenshot 2020-04-15 at 09 12 50" src="https://user-images.githubusercontent.com/11189008/79308688-566a8780-7ef9-11ea-8cc1-61042523e93b.png">

**Comment by liamdebeasi** [comment]
Thanks for the issue. You can set the `::after` pseudo element to apply an inset box shadow. 

CodePen with example: https://codepen.io/liamdebeasi/pen/qBObaZO

Does this work for your use case? The inner `button` inherits the background color and covers the inset shadow if you set it directly on `ion-card`. Unfortunately, changing this behavior will likely lead to breaking changes.

**Comment by Spinnenzunge** [comment]
Hi liamdebasi.
Yes i thought about the after pseudo element as well but thought maybe making the button and a element transparent could fix this problem easily. If it would result in breaking changes then i will find a solution for styling such a card.
