### ISSUE TITLE
bug: setfocus with viewChild

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic#21047]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

It does not have setFocus method when you access ion-input element as ionInput;

```
  @ViewChild('testInput', {read: IonInput}) testInput: IonInput;

  
 ngAfterViewInit(): void {
   console.log((this.testInput as IonInput))
   console.log((this.testInput as IonInput).setFocus())
 }
```

output: 
```
IonInput {z: {…}, el: {…}, ionInput: {…}, ionChange: {…}…}
el: r
ionBlur: Observable
ionChange: Observable
ionFocus: Observable
ionInput: Observable
z: NgZone
```
**Expected behavior:**

It should have setFocus() to invoke focus programmatically.

**Steps to reproduce:**

**Related code:**

https://stackblitz.com/edit/ionic-angular-v5-y2wscm?file=src%2Fapp%2Fapp.component.html

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
5
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I can only reproduce this when using StackBlitz (a standalone app does not exhibit this behavior) so this is likely a StackBlitz bug. We will look into bringing this up with the StackBlitz team. Thanks!
