### ISSUE TITLE
feat: fast-scroll / alphabet scroll component for long lists

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic#21057]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

Many apps have the need to display long lists of information. When displaying such information, the Ionic framework does not provide a way to quickly navigate the list, between sections, list-divider/list-headers, or even simply by alphabetical/numerical order.

Users must swipe, and swipe... and swipe... to reach the top or bottom of the list.

**Describe Preferred Solution**

It is a common pattern to add a "scroll handle", that allows users to "grab" the scrollbar, which then displays the first letter of each group heading, or the first letter of the alphabet for each letter that has entries in the list.

The user can then drag this handle up or down to quickly navigate/scroll the list to the position desired. This can be seen on Android devices, when scrolling a long list of Contacts in the phone app, etc.

This implementation would need to work with, and probably also without, ion-virtual-scroll.

**Describe Alternatives**

Filters. Users can type into a filter bar, which requires more manual input / introduces keyboard jitter/issues.

A popover to select a section to navigate to, displaying either an alphabet, or section headers.

However, both of these options disrupt the users flow of usage, and result in poor user experience.

**Related Code**

None, this feature does not exist for Ionic 5.

Here is a basic example of the feature implemented in Ionic 2x:
https://www.npmjs.com/package/ionic2-alpha-scroll

**Additional Context**

Screenshot example of the drag handle:
![image](https://user-images.githubusercontent.com/362329/79482871-6eb4d200-7fdf-11ea-9836-de9abedc547e.png)

Here is a video example / explanation:
https://www.youtube.com/watch?time_continue=22&v=rcPIvGRwrxA&feature=emb_logo

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I discussed this with the team and we decided this is not something we are looking to implement at this time. Since the feature itself is very specific to the contact list use case, it would be better if this was implemented on an application-level. Thanks!

**Comment by lincolnthree** [comment]
Hmm, interesting. Thanks for discussing.

If it helps, my use-case is not a contact list. That was just one example. Perhaps I should not have included it :) My use-case just a LONG list with arbitrary (user-defined) groups. I also believe that implementing at the application level is nearly prohibitively complex for non-expert developers, unless I'm misunderstanding the factors involved:

Gestures,
Animation,
Scrolling/Positioning
then of course general integration with IonContent and the DOM itself.
