### ISSUE TITLE
bug: Interactive with Ion-slides doesn't work

### ISSUE THREAD

**Issue by nicobytes** [ionic-team/ionic#21051]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
- When going to slides page interactive with ion-slides work
- Then go back or the previous page
- Going to slides page again interactive with ion-slides doesn't work

**Expected behavior:**
- When going to slides page interactive with ion-slides work
- Then go back or the previous page
- Going to slides page again interactive with ion-slides work

**Steps to reproduce:**
- Make SlidesPages
- Go to Slides page
- Tests interactive with ion-slides with methods like slideNext()
- Go to back
- Tests interactive with ion-slides with methods like slideNext()

The code component is

```ts
@Component({
  selector: 'app-slides',
  templateUrl: './slides.page.html',
  styleUrls: ['./slides.page.scss'],
})
export class SlidesPage implements OnInit {

  @ViewChild(IonSlides) slides: IonSlides;

  constructor() { }

  ngOnInit() {
  }

  goToNextSlide() {
    this.slides.slideNext();
  }

  goToPrevSlide() {
    this.slides.slidePrev();
  }

}
```

**Related code:**

- Repo Sample:  https://github.com/nicobytes/bug-slides
- Video: https://www.loom.com/share/34b78c6e644f4a65a508ea67ca3840a0

**Ionic info:**

```
Ionic:

   Ionic CLI   : 6.5.0 (/Users/nicolas/.nvm/versions/node/v13.9.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.901.1
   @angular-devkit/schematics  : 8.3.26
   @angular/cli: 9.1.1
   @ionic/angular-toolkit : 2.2.0

Capacitor:

   Capacitor CLI   : 2.0.1
   @capacitor/core : 2.0.1

Utility:
   cordova-res : not installed
   native-run (update available: 1.0.0) : 0.2.9

System:

   NodeJS : v13.9.0 (/Users/nicolas/.nvm/versions/node/v13.9.0/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has already been resolved via https://github.com/ionic-team/ionic/pull/20899 and a fix will be available in an upcoming release of Ionic Framework.
