### ISSUE TITLE
More Native-Feeling swiping between Items (iOS)

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic#21052]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

A more Native-Feeling swipe between same Items on iOS.

**Describe Preferred Solution**

On native iOS You can swipe, for example in list items top and down (see video 1). What about that in Ionic? At the moment it is like that (video 2)

**Additional Context**

Video 1: 
https://youtu.be/TNjSsKEwwXY
Video 2:
https://youtu.be/BzTg6iY48t0

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you referring to being able to drag your finger over multiple buttons and have them activate?

**Comment by BerkeAras** [comment]
Hello,
yeah I mean touch a Button (e.G a button from 3d touch) and then swipe up and down to other buttons and leave finger to press. If you have an iPhone you can test them. It also works on actionbars, alerts,...

**Comment by BerkeAras** [comment]
It is not only alert, and action sheet. Try it on iOS. Press a Button, and swipe your finger down. It will unfocus. Swipe up again, and it will focus again. On ionic it never unfocuses

**Comment by liamdebeasi** [comment]
Action sheet/Alert buttons being activated vs regular buttons being activated are 2 different behaviors. We are going to limit the scope of the PR to addressing the behavior for action sheets and alerts. Ideally there would be a CSS-only solution that we could apply to all buttons, but unfortunately no such solution exists currently.

The solution for the action sheet/alert requires a custom gesture, and it would likely incur a large performance hit if we applied this to every single button.

I have prepared a dev build for the action sheet/alert updates if you are interested in testing:

Ionic Angular
`npm i @ionic/angular@5.1.0-dev.202004162054.6c28736`

Ionic React
`npm i @ionic/react@5.1.0-dev.202004162054.6c28736`

**Comment by BerkeAras** [comment]
Can I install it for @ionic/core too?

**Comment by liamdebeasi** [comment]
Yes `npm i @ionic/core@5.1.0-dev.202004162135.6c28736` 😊

**Comment by BerkeAras** [comment]
Thank you :)

**Comment by BerkeAras** [comment]
Btw: Is it possible to create iOS and Android Apps (No PWAs, Hybrid Apps) without using a Framework with Ionic? I think @ionic/core is just for PWAs

**Comment by liamdebeasi** [comment]
Yes you can create iOS/Android apps running in Capacitor or Cordova (in addition to PWAs or apps that run in a browser). Ionic Angular and Ionic React are just framework-specific wrappers around @ionic/core.

**Comment by BerkeAras** [comment]
But – Should I do it? Is the performance still good? And, how can I do it?

**Comment by BerkeAras** [comment]
And I have a question: I have a few question about Hybrid Apps with Cordova. If you could answer, It would be great If you could join a discord server to talk: https://discord.gg/QjrsPKT

**Comment by liamdebeasi** [comment]
You should still get great performance using only @ionic/core. We actually have an example application using just @ionic/core (no Angular or React) that you might want to check out: https://github.com/ionic-team/ionic-stencil-conference-app

**Comment by liamdebeasi** [comment]
For questions about hybrid apps with Cordova, the fastest way to get an answer would probably be to post it on our forums: http://forum.ionicframework.com/. We have a lot of helpful members who are very knowledgable on building Ionic apps.

**Comment by BerkeAras** [comment]
Okay thanks

**Comment by liamdebeasi** [comment]
I'm going to keep this issue open until https://github.com/ionic-team/ionic/pull/21060 gets merged. Thanks!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21060, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by BerkeAras** [comment]
Thanks! When is the next release coming?

**Comment by liamdebeasi** [comment]
We hope to have the next release out soon 😊
