### ISSUE TITLE
bug: ionContent scrollable while opening ionMenu

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic#21065]
# Bug Report

**Ionic version:**

[x] **4.x**
[x] **5.x**

**Current behavior:**

While opening Menu, the Content is still scrollable (see video)
**Expected behavior:**

Content should not be scrollable

**Steps to reproduce:**

While opening Menu scroll up and down content.

**Video**
[https://youtu.be/K-ImPdKFoiA](https://youtu.be/K-ImPdKFoiA) 

Cannot run ionic info, because using Ionic with CDN

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by BerkeAras** [comment]
Oh, at the moment, I don’t have a repo, I can give. If you wait a few Minutes, I could give you a jsfiddle.

**Comment by BerkeAras** [comment]
Okay, we can close Issue, the bug is just on my app (You can see on AppStore at "Marmaris Marktoberdorf")
