### ISSUE TITLE
bug: ionic v5 ion-footer pushed down, and not positioned fixed on bottom of screen

### ISSUE THREAD

**Issue by nutangwari** [ionic-team/ionic#21075]
# Bug Report

**Ionic version:**

v5.0.0

**Current behavior:**
I am adding ionic page with nothing but the ion-content and  ion-footer markup, before upgrade i was able to see the footer fixed to the bottom margin of screen but after upgrade footer is pushed down and not visible on screen

**Expected behavior:**
before upgrade i was able to see the footer on screen fixed at bottom.

**Steps to reproduce:**
1. create ionic page
2. add ion-content and ion-footer
3. footer is not visible, on inspect element you will see ion-content is stretched to the full screen and ion-footer is pushed down, i can absolute position ion-footer and setting bottom:0 shows footer in screen. attached screenshot below.

![image](https://user-images.githubusercontent.com/9932923/79682773-9657a480-8242-11ea-8822-2add3ad70651.png)

```
<ion-content>
   lorem ipsum....
</ion-content>

<ion-footer>
<button>Hello </button>
</ion-footer>
```

**Comment by NikolaPeevski** [comment]
https://github.com/NikolaPeevski/ionic-modal-service/commit/c9cfbc5dd3585c5f60405380f562f9f22b998a7a

![image](https://user-images.githubusercontent.com/14194863/79689110-4ebc2300-8218-11ea-8cc3-f0bdf81c275e.png)

Can you provide a repo for reproduction, it works here without any issues.

**Comment by nutangwari** [comment]
finally i found the silly mistake, application was not wrapped inside the ion-app tag. I've added and its working correctly. Closing the issue. Thanks.
