### ISSUE TITLE
feat: Interrupt/disable programmatic scroll (e.g scrollByPoint) when user interacts with view

### ISSUE THREAD

**Issue by didaktio** [ionic-team/ionic#21078]
The programmatic scroll methods provided with `ion-content` are quite useful. But it would be great if there was a simple way to disable or halt their execution midway through completion when the user engages with the view (moving the mouse, pressing, clicking).

**Comment by liamdebeasi** [comment]
Thanks for the issue. If you need to interrupt scrolling, it is recommended you use the scroll methods built into the browser so the browser/OS can handle it. Interrupting scrolling via JS typically leads to jank and other unintended side effects, so it is not something we are looking to implement at this time. Thanks!
