### ISSUE TITLE
bug: swipeToClose is not reactive

### ISSUE THREAD

**Issue by HansKrywaa** [ionic-team/ionic#21072]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

I want a Modal to don't be able to slideToClose until i do something in the modal, so i want to be able to change that option from the Modal itself. I tried: 

```
this.modal.getTop().then(modal => {
      modal.swipeToClose = true;
});
```
but that do not work.

**Describe Preferred Solution**

Setting it like i tried should work i think.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

Ionic Angular
`npm i @ionic/angular@5.1.0-dev.202004171738.7ac69ba`

Ionic React
`npm i @ionic/react@5.1.0-dev.202004171738.7ac69ba`

**Comment by HansKrywaa** [comment]
Hi @liamdebeasi,

seems like it doesn't work 🤔

**Comment by HansKrywaa** [comment]
hi @liamdebeasi , seems like it is not working for me. 🤔

**Comment by liamdebeasi** [comment]
Can you provide a repo with how you are using the modal?

**Comment by HansKrywaa** [comment]
Of course: https://github.com/HansKrywaa/ionic-issue-21072

**Comment by liamdebeasi** [comment]
Thanks! Here is a new dev build if you would like to test: `5.1.0-dev.202004171953.c7a35c2`

**Comment by HansKrywaa** [comment]
i would love to 😍 Yeah it works! Thank you 🎉

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21073, and a fix will be available in an upcoming release of Ionic Framework.
