### ISSUE TITLE
bug: modal dismiss by hardware button preventing the modal from being reshown

### ISSUE THREAD

**Issue by kutoman** [ionic-team/ionic#21070]
# Bug Report

**Ionic version:**

[x] **4.11.10**

**Current behavior:**

In the Music app demo you're providing on your page, the modal which is showing up when a music track is selected, won't be able to popup again when the modal was dismissed previously by hardware button (ESC on desktop computer). If the back arrow button from the header is clicked instead this won't happen. I assume this is a bug or at least an unintended issue for the demo.

**Expected behavior:**
In both cases, dismissing the modal by hardware or ui back button, the modal shouldn't be killed (at least not in the demo as it is not an expected behavior :) ) 

**Steps to reproduce:**
In the home view of the demo, click (for example) on the "Hound Dog" Track. Then press on the back arrow button in the header.
Second, click on another track. This time dismiss the modal by pressing ESC.
Now if you click on any other track that modal won't show up again.

**Related code:**

[Demo from https://ionicframework.com/react](https://stackblitz.com/edit/ionic-react-demo?file=package.json)

**Other information:**

**Ionic info:**
skipping this since the demo is on stackblitz

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is looks like a problem with the app itself and not Ionic Framework. I will pass this info along to make sure the demo is corrected. Thanks!

**Comment by liamdebeasi** [comment]
This has been fixed. Thanks!
