### ISSUE TITLE
bug: background-color of ion-toolbar appears lighter on iOS

### ISSUE THREAD

**Issue by sebsoftpak** [ionic-team/ionic#21081]
# Bug Report

**Ionic version:**

[x] **6.3.0**

**Current behavior:**

When deploying the app to iOS, the color of the toolbar appears in a lighter shade. On the Android version, and Ionic lab the color is as desired. 

**Expected behavior:**

The color of the toolbar should be the same on all platforms.

**Steps to reproduce:**

1. I gave the toolbar a color in variables.scss:
:host {
  --ion-toolbar-background: #00853f;
}
2. Build the application and run in XCode.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

Ionic:

   Ionic CLI                     : 6.3.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.24
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.1
   @capacitor/core : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.9.0 (/usr/local/bin/node)
   npm    : 6.14.4
   OS     : macOS Mojave

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?
