### ISSUE TITLE
bug: SideMenu not working

### ISSUE THREAD

**Issue by Rehan1579** [ionic-team/ionic#21087]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**
I’ve been using `ionic-core 4` in my project, everything was working fine, Few days ago, i migrated to `ionic5`, everything worked great (on latest browsers) after doing some minor changes, but my `SideMenu`stopped working. I noticed `ionic5` implementation(way of use) for `SideMenu` totally replaced `ionic4`.

**Expected behavior:**
Need backward compatible, `ionic5 SideMenu` should also be working easily like it was in `ionic4`.

**Steps to reproduce:**

**Related code:**

```
Ionic 4 Example:
----------------

const menuCtrl = document.querySelector('ion-menu-controller');

function openFirst() {
  menuCtrl.enable(true, 'first');
  menuCtrl.open('first');
}


Ionic 5 Example:
----------------

<script type="module">
    import { menuController } from '@ionic/core';
    window.menuController = menuController;
</script>

function openFirst() {
    menuController.enable(true, 'first');
    menuController.open('first');
}
```

**Other information:**
You see, the actual functions are same like open/enable etc but the way you gonna import `SideMenu` has changed. For some reasons, my (clients) project needs to run on old browsers which dont support import/module.

So is there a way to run `ionic5 SideMenu` on old browsers too like `ionic4` was ???
Client's project, need to support old browsers too

**Ionic info:**

```
IonicCore 5.0.5
VanillaJS
Goggle Chorme v51+
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. You can call the `open` method on the `ion-menu` element itself.

CodePen: https://codepen.io/liamdebeasi/pen/WNQGKVw
