### ISSUE TITLE
bug:  <ion-segment-button> and <ion-slides> causes Problems when used on multiple pages in tabs app

### ISSUE THREAD

**Issue by NeckbreakerPascal** [ionic-team/ionic#21089]
# Bug Report
**Ionic version:**
[x] **5.0.7**

**Current behavior:**

Control Ion-Slides via Ion-Segment-Button does not work when using it on multiple templates in an ion-tab navigated app. 

- 3 Tabs 
- On every Page 3 ion-slides and an ion-segment to switch them
- Only on the initial Page (First Called Page) the ion-segment buttons will change the sliders correctly

**Expected behavior:**

- 3 tabs
- On every Page 3 ion-slides and an ion-segment to switch them
- I can switch the slides on every page, no matter which on is the initial Page

**Steps to reproduce:**
- ionic serve (also testet on android and ios, same issue)
- Start in the first tab and use the ion-segment button on top to change the sliders
- switch to tab 2 and use the ion-segment button on top to change the sliders. 

Sliders will not move. No Error in console, just not move. When you go deeper you find out, that the getActiveIndex is not triggered anymore. 

Also the (ionSlidesDidLoad) is triggered multiple times. 

When you start on tab 2 as initital tab, the slides will change on that tab, but then after changing to tab 1 they will not move anymore, so it is somekind related to the initTab or Init Slide 

**Related code:**
Not able to do a full code example, but this could help to reproduce: 
I used this for the ion-slides. and added it to the different Tabs
- https://codepen.io/brandyscarney/pen/maOabQ?editors=1010

For the Tabbed-App I used the Ionic 5 starter App "tabs"
- ionic start myApp tabs

**Other information:**
- With Ionic4 it was working
- Tried to call the ionChange on ion-segment to get the activeIndex on the slide - Not working
- Checked my routes with loadChildren and stuff but it is all like it should be with preloadAll
- Tried with template events in the template too, same issue
- Is it maybe related to Angular 9? 

- Also some strange additional info: When I try to get the active index of the slide inside the constructor. The Console will tell me "Error cannot.. getActiveIndex() of undefined. That is correct, because it is not rendered yet. But for some reason, I am then able to move the Sliders like expected.

- I also tried it with #SwipedTabsSliders and ViewChild in the ts-file, but same issue

- ion-segment indicator works, so maybe it has something to do with the ion-slide events, or maybe that change to the onchange Event with ionic 5 on the ion-segment? 

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.6.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.901.1
   @angular-devkit/schematics    : 9.1.1
   @angular/cli                  : 9.1.1
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 27 other plugins)

Utility:

   cordova-res (update available: 0.12.1) : 0.12.0
   native-run                             : 1.0.0

System:

   ios-deploy : 1.10.0
   NodeJS     : v12.14.0 (/usr/local/bin/node)
   npm        : 2.15.12
   OS         : macOS Catalina
   Xcode      : Xcode 11.4 Build version 11E146


```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? The CodePen you provided uses a very old version of Ionic Framework. `ion-segment` went through a big refactor with v5.

**Comment by liamdebeasi** [comment]
Never mind, I think this issue is resolved by https://github.com/ionic-team/ionic/pull/20899. This fix will be available in an upcoming release of Ionic Framework. If the issue persists once the fix has shipped, feel free to open a new issue. Thanks!
