### ISSUE TITLE
Problem with ionic react 5 and IonModal 

### ISSUE THREAD

**Issue by WaelRabah** [ionic-team/ionic#21094]
**Description:**

I am working on this app using react with ionic 5 and I added a login modal to the header ,
![localhost_8100_page_home(Pixel 2 XL)](https://user-images.githubusercontent.com/47258198/79871483-b3c47400-83e4-11ea-936f-1c8a835e53a5.png)

at first load it works fine just like this :
![localhost_8100_page_home(Pixel 2 XL) (1)](https://user-images.githubusercontent.com/47258198/79871536-c3dc5380-83e4-11ea-9f65-e9e87f8759de.png)

But when I navigate to another page and I try to open the login modal it shows me a blank screen 
just like this :
![localhost_8100_page_home(Pixel 2 XL) (2)](https://user-images.githubusercontent.com/47258198/79871612-e2424f00-83e4-11ea-8fcc-8458d657ed24.png)

before I navigate from the home page to another page , I can open the modal as much as I want and there's no problem but when I go to another page I get a blank screen .

**Steps to Reproduce:**

1-create an ionic react 5 project with a header
2-put a modal component inside the header component and try to open the modal and then navigate to another page

**Output:**

**My `ionic info`:**

```
Ionic:

   Ionic CLI       : 6.6.0 (C:\Users\CAC Station\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.0.7

Capacitor:

   Capacitor CLI   : 2.0.1
   @capacitor/core : 2.0.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.8.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.6
   OS     : Windows 10
```

**Other Information:**

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by WaelRabah** [comment]
> Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

here you go https://github.com/WaelRabah/medClone

**Comment by liamdebeasi** [comment]
Thanks for the follow up. You need to make sure you are resetting the `showLoginModal` state when the modal is dismissed otherwise the modal will not notice the state change when `showLoginModal` gets set to `true` again.

```jsx
<IonModal isOpen={showLoginModal} onDidDismiss={closeModal}>
```

**Comment by WaelRabah** [comment]
> Thanks for the follow up. You need to make sure you are resetting the `showLoginModal` state when the modal is dismissed otherwise the modal will not notice the state change when `showLoginModal` gets set to `true` again.
> 
> ```js-jsx
> <IonModal isOpen={showLoginModal} onDidDismiss={closeModal}>
> ```

Thanks for the quick reply , apparently that's not it because the problem still exists even after resetting the state .
