### ISSUE TITLE
[React] Nested views in Tabs are removed on tab change

### ISSUE THREAD

**Issue by dborstelmann** [ionic-team/ionic#21097]
I have an app with 3 tabs.
```
/tab1
/tab2
/tab3
```

Each of those tabs can go to nested views like so:
```
/tab1
/tab1/somedetails
/tab2
/tab2/someotherdetails
/tab3
/tab3/evenotherdetails
```

But from those detail pages you can link to some other person's profile.  I would like this url to be something like
```
/profile/:id
```

However, due to Ionic tab navigation, the only way I know how to do this would be:
```
/tab1
/tab1/somedetails
/tab1/somedetails/profile component={Profile}
/tab2
/tab2/someotherdetails
/tab2/someotherdetails/profile component={Profile}
/tab3
/tab3/evenotherdetails
/tab3/evenotherdetails/profile component={Profile}
```

This replication is not ideal.  If it were only a mobile app it wouldn't be a big deal.  But this is a PWA.  And I want people to be able to share links.  If I share the link `/profile/:id` I want that page to be able to be rendered standalone on the web as well as deep within these tabs stacks on mobile.

I cannot solve this with the docs and github issues I have read.

1. Is this a bug?
2. Am I missing something that is obvious to solve this?
3. Is it not implemented to solve this?

**Comment by elylucas** [comment]
Hi @dborstelmann,

Would you be able to put together a sample repo that replicates the issue that I can look at?

**Comment by dborstelmann** [comment]
Here you go:
https://github.com/dborstelmann/ionic-tab-example/blob/master/src/App.tsx

1.  Run the app
2.  Click "Go to profile" on tab1
3.  Click Tab2 in the TabBar
4.  Click Tab1 in the TabBar
5.  Notice the profile is gone

I would expect it still to be loaded on top Tab1.  I understand this is because it's not at `tab1/profile`.  So how do you make a shared url keep a stack's navigation state?

**Comment by jamiechong** [comment]
I think you needed to look into [Nested Routes](https://tylermcginnis.com/react-router-nested-routes/) . You've defined the Profile page route to be a top level page - a sibling to the tab pages. Figure out your specific URL structure and it should give you a hint on how to define your Routes. Of course you can use the same component to render the Route, but you may need to define a route specific to each tab.

**Comment by dborstelmann** [comment]
That's what I want to avoid, having multiple routes for multiple tabs means things like the profile are not accessible from one url, but rather could be accessed in numerous locations

**Comment by jamiechong** [comment]
I think then maybe it's not clear exactly what specific pages you're trying to setup. Or there's a fundamental flaw in how you're organizing the hierarchy of your app/website. 

Think of a `route` as a type of ID. In fact it is. A URI is a uniform resource identifier. It's a unique ID to a specific page or state of your app. So it makes sense to have multiple routes for the varying states of your app. You can reuse the components, but likely you will want to have multiple routes. You need a unique route for every combination of page state you have for your tabs and profile pages.

**Comment by dborstelmann** [comment]
See this is where I am wondering if there is a better solution.  I understand the nested routes make sense for certain things (like showing a hierarchy within a page).  However in the case of Ionic Tabs, the stacks within them are really separate pages, not nested routes within a page.  But the way Ionic Tabs work in React is to hijack nested routes as the rails for getting pages to render inside of each other with transitions.

I guess my question is, can we use a different method for storing stack data so that pages within Ionic Tabs can be any URL and just load with the correct transitions (but don't unhighlight the tab or lost state on tab change).  This may be harder said than done.

But the goal would be to not have to have a separate URL scheme for your mobile Ionic app than you do for your web Ionic app.  For example:

Web: Feed -> Profile
Mobile: Feed Tab -> Profile (feed tab still highlighted because that's how you got to Profile)

Profile should be linkable at `.com/profile/:id`
If you click that link outside the browser on web it should load the profile page directly with no history.
On mobile it should load the profile page in some tab (maybe feed, Instagram loads a linked profile directly to the activity tab which doesn't really make sense to me but it works for them) and that tab should be highlighted.

The problem is that the way Ionic Tabs are setup now is you would have to say "if web, load `/profile/:id` directly, if mobile load `/feed/profile/:id`". If you don't specify `/feed` then it will load outside of a tab which is weird.

Maybe I am naive and there is no better solution tabs but this is what I was hoping the authors might be able to shed some light on.  Otherwise I will have to setup two different url mappings for mobile and web, as well as set up multiple `profile` routes per tab in mobile.

@elylucas

**Comment by elylucas** [comment]
Hi @dborstelmann,

Sorry about the delay getting back to you on this.

In order for the tabs to know which tab to highlight when going directly to a tab, it needs to match up the url with the url in the tab. So in your example, going straight to /profile won't highlight Tab1, but if you changed the route to go to /tab1/profile then it would.

I realize thats not the URL setup you want though.

To get around it, you could setup a redirect that when someone goes directly to /profile it can forward to /tab1/profile.
`<Redirect path="/profile" to="/tab1/profile" exact={true} />`
 Not sure if that will be ideal for you or not.

Let me know if I'm missing something. But as I don't think this is a bug in the framework, I'm going to close the issue, but we can keep the discussion open.

Thank

**Comment by dborstelmann** [comment]
Thanks for the reply @elylucas.  That's a good start.  It's not perfect because it changes the URL so when copying and pasting a url it's different but if you use that URL scheme mostly on mobile and then have a separate router for web it should cover most usage (although this is extra work).

It would be nice if there were a more elegant solve to this long term but I understand that's it's not vital.

Thanks for the advice.
