### ISSUE TITLE
bug: ion-picker --height attribute not working correctly

### ISSUE THREAD

**Issue by Pra3t0r5** [ionic-team/ionic#21098]
# Bug Report

**Ionic version:**
v5.0.4

**Current behavior:**
 I found no easy way to customize the picker height for lesser amounts of  options (~5-6) without wasting a lot of vertical space in md systems.
When adjusting the --height attribute, most of the picker attributes adjusts incorrectly.
The bug is visually worse in ios systems, where items overlap.
![Screenshot from 2020-04-21 22-12-01](https://user-images.githubusercontent.com/38087682/79930277-7bda2280-841e-11ea-8295-bb81751a116b.png)

**Expected behavior:**
The whole picker vertically downscalling to adjust correctly. Or at least a decreased height in the picker-column and picker above and below highlights.

**Steps to reproduce:**
![Screenshot from 2020-04-21 22-12-07](https://user-images.githubusercontent.com/38087682/79930281-7da3e600-841e-11ea-869e-3f1038dc1784.png)
![Screenshot from 2020-04-21 22-12-17](https://user-images.githubusercontent.com/38087682/79930285-7ed51300-841e-11ea-874a-d5a069681f79.png)

**Related code:**
component.ts:
```
  async elegirTarjetaCanjearPromocion(promocion: any) {
    const options: PickerOptions = {
      buttons: [
        {
          text: 'Volver',
          role: 'cancel'
        },
        {
          text: 'Continuar',
          handler: (choice: any) => {
          [...]
          }
        }
      ],
      columns: [{
        name: 'tarjeta',
        options: this.getColTarjetasCliente()
      }],
      cssClass: 'tarjeta-picker'
    };
    const picker = await this.pickerController.create(options);
    picker.present();
  }
```
global.scss:
```
.tarjeta-picker {
	--max-width: 90%;
	--height: 25%;
	--border-radius: 25px 25px 0px 0px;
	// .picker-above-highlight{
	// 	height: 25%;
	// }
	// .picker-below-highlight{
	// 	height: 25%;
	// }
	// .picker-wrapper {
	// 	border-radius: 25px 25px 0px 0px;
	// }
}
```

**Other information:**

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 6.2.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.900.6
   @angular-devkit/schematics    : 9.0.6
   @angular/cli                  : 9.0.6
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.1 (/usr/local/bin/node)
   npm    : 6.13.4
   OS     : Linux 4.19
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. You need to adjust the height of the `.picker-columns` as well since it is a fixed height. The component itself is not very responsive currently and we will be making changes in upcoming versions to address this. Thanks!
