### ISSUE TITLE
bug: User can choose from popover while it fades/is in Animation

### ISSUE THREAD

**Issue by felix-ulonska** [ionic-team/ionic#21092]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Issue is tested in Android and Web.

A User can chose an item while <ion-select interface="popover"> is in the closing animation
1) 
![image](https://user-images.githubusercontent.com/39523620/79901907-e3897100-8410-11ea-94ab-3fc19a0ef5db.png)
User clicks on one item
2) 
![image](https://user-images.githubusercontent.com/39523620/79901990-02880300-8411-11ea-998c-b862391d8fae.png)
While popover fades user clicks on a different item
3) 
![image](https://user-images.githubusercontent.com/39523620/79902023-0fa4f200-8411-11ea-81a5-511c036ae77b.png)
Last clicked item is used.

**Expected behavior:**

The user should be unable to pick something while the popover fades away.

**Steps to reproduce:**

Go to https://ionicframework.com/docs/api/select
and choose a item in the gaming popover. While the popover fades away, choose a different item.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21093, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by felix-ulonska** [comment]
Thank you very much for your work!
