### ISSUE TITLE
feat: ion-segment-button - CSS Custom Properties - --indicator-width

### ISSUE THREAD

**Issue by NeckbreakerPascal** [ionic-team/ionic#21091]
# Feature Request

**Ionic version:**

[x] **5.0.7*

**Describe the Feature Request**
Please add a CSS Custom Property for the width of the ion-segment-button indicator. 

**Describe Preferred Solution**
--indicator-width (like --indicator-height)

**Describe Alternatives**
Maybe some other way to do it simple. 

**Additional Context**
the --indicator-height was added with ionic5, maybe the width can be added too.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. Can you please describe your use case? Setting the width on the indicator to anything other than 100% would break with the iOS and MD specs.

| iOS | MD |
| ---- | ---- |
| <img width="181" alt="Screen Shot 2020-04-21 at 11 58 03 AM" src="https://user-images.githubusercontent.com/2721089/79886704-6be32400-83c7-11ea-9c16-efa11f4da209.png"> |<img width="372" alt="Screen Shot 2020-04-21 at 11 57 40 AM" src="https://user-images.githubusercontent.com/2721089/79886748-83221180-83c7-11ea-906c-230458b78ebe.png"> |

**Comment by NeckbreakerPascal** [comment]
Hey there, thanks for the quick response. 

I like to use the ion-segment in mode md on both systems and the indicator should designwise just be a litte bit smaller (maybe 10%). Like in this draft here: 

![screen_header_bar](https://user-images.githubusercontent.com/13185628/79968060-ec6d5780-848f-11ea-92b1-20537d8532b6.PNG)

**Comment by liamdebeasi** [comment]
Thanks for the follow up. We do not typically add CSS variables that only work on certain modes (this is likely not a desirable behavior on iOS). That being said you should be able to do this with the addition of shadow parts on the segment button. You can follow this issue to track its progress: https://github.com/ionic-team/ionic/issues/20916.

**Comment by NeckbreakerPascal** [comment]
Thanks, so do I understand you correctly, you want add those shadow parts to the segment button and I need to do that by myself? Or will you add those parts?

The truth is, I did not found a way to add these by myself, therefore I opened this feature request, if that was wrong I am sorry.

**Comment by liamdebeasi** [comment]
The shadow parts will be added by us. You would target in your CSS by doing something like:

```css
ion-segment-button::part(indicator) {
  width: 50px;
}
```

Don't be sorry 😄 we have not announced the shadow parts addition yet, but it is coming soon.

**Comment by NeckbreakerPascal** [comment]
Great thank you a lot! Looks like a good way to do it. :)
