### ISSUE TITLE
bug: ionic-react <IonRow className="ion-align-items-center"> doesn't work

### ISSUE THREAD

**Issue by gine** [ionic-team/ionic#21102]
**Ionic version:**
 5.0.7

With ion-align-items-center i  aspect that this row is in the center of the display(vertically), the class is applied but no way to put it in the middle.

```
const Home: React.FC<RouteComponentProps<{ name: string; }>> = ({ match }) => {
  return (
    <IonPage>
      <IonContent>
        <IonGrid>
          <IonRow>
          </IonRow>
          <IonRow className="ion-align-items-center">
            <IonCol></IonCol>
            <IonCol size="8">
              <IonImg src={vlogo}></IonImg>
            </IonCol>
            <IonCol></IonCol>
          </IonRow>
          <IonRow>
            <IonCol>
            </IonCol>
            <IonCol color="primary">
              <IonButton>
                Menú
              </IonButton>
            </IonCol>
            <IonCol>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonContent>
    </IonPage>
  );
};

export default Home;
```

Since yesterday i haven't found a way to do it. I'm started the project with the sidemenu template.

**Comment by liamdebeasi** [comment]
Thanks for the issue. The `ion-align-items-center` class aligns columns within the dimensions of the `ion-row`. If your row does not take up the full width of the screen, the columns will not appear centered in the context of the entire screen.

To do this you will need to customize the grid a bit:

```css
ion-row {
  flex: 1 1 auto;
}

ion-grid {
  height: 100%;

  display: flex;
  flex-direction: column;
}
```
