### ISSUE TITLE
Accessibility problem with ion-loading with VoiceOver and ionic 5/angular

### ISSUE THREAD

**Issue by terrancle** [ionic-team/ionic#21107]
When the ion-loading property is set, VoiceOver displays an alert type popup at the bottom of the screen.
In this popup, VoiceOver says a value of "50.00" just before the text message.
I tried to modify the attributes, without success.
Do you have an idea?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide an example of how you are using the component?

**Comment by terrancle** [comment]
Thank you,

Example :
async showLoader(msg: string) {
    this.isLoading = true;
    return await this.loadingController.create({
      translucent:true, //or false identical
      mode:'ios',
      message: msg,
      spinner: 'bubbles',
      showBackdrop:true, //identical in false
    }).then(a => {
      a.present().then(() => {
        //console.log('loading presented');
        if (!this.isLoading) {
          a.dismiss().then(() => {
            //console.log('abort laoding')
          });
        }
      });
    });
  }

  async showLoaderDismiss() {
    this.isLoading = false;
    return await this.loadingController.dismiss().then(() => {
      //console.log('loading dismissed')
    });
  }

**Comment by terrancle** [comment]
sorry, i closed this request by mistake when i replied.

**Comment by terrancle** [comment]
Hello,
The time to realize this is fast, because in the current configuration, it depends on the loading time.
I suggest that you set a duration to 500000 so that the message remains visible for 50 seconds.
You should notice that just before the text message a numeric value appears, in my case 50.00.

**Comment by liamdebeasi** [comment]
What is the actual problem you are running into? It sounds like the message in your `ion-loading` component is "50.00". Is the issue that VoiceOver is not reading the message?

**Comment by terrancle** [comment]
VoiceOver clearly states the message I send it "loading in progress".
But the ion-loading component adds a static message before the one I send which is 50.00.
I tested on another Ionic 5 project, the problem is identical.
The problem is not visual, only audio with VoiceOver.
If I send a "load problem" text message, VoiceOver says "50.00 load problem".
to try, you can deactivate the function:
 const { role, data } = await loading.onDidDismiss();
    console.log('Loading dismissed!');
![VoiceOver](https://user-images.githubusercontent.com/19683797/80116654-81eb1300-8586-11ea-8527-54587298f16e.jpg)

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I was able to reproduce the issue. Here is a dev build if you would like to test the fix:

Ionic Angular
`npm i @Ionic/angular@5.1.0-dev.202004231531.ae0a989`

Ionic React
`npm i @ionic/react@5.1.0-dev.202004231531.ae0a989`

**Comment by terrancle** [comment]
You are a boss !
The problem is fixed.
