### ISSUE TITLE
bug: npm install @ionic-enterprise/geolocation not found

### ISSUE THREAD

**Issue by noahsalvadordenjo** [ionic-team/ionic#21118]
hi when following the steps
https://ionicframework.com/docs/enterprise/geolocation
```
 npm install @ionic-enterprise/geolocation
```
turns into a not found 404

**Comment by nphyatt** [comment]
Hello @noahsalvadordenjo the reason you're getting the error is that our enterprise solutions require a subscription to access. If you're interested in our enterprise offering you can reach out [here](https://ionicframework.com/pricing/enterprise#) and someone from sales will be in touch to help get you set up.

Hope this helps!
