### ISSUE TITLE
feat: ion-tabs button overflow

### ISSUE THREAD

**Issue by rbalet** [ionic-team/ionic#21113]
**Ionic version:**
[x] **5.0.7**

**Describe the Feature Request**
adding the ability to let a tabs button overflow from them container.  
Ex : 
![image](https://user-images.githubusercontent.com/44493964/80079732-f5722d80-8550-11ea-91f2-6335cf45aa79.png)

**Describe Preferred Solution**
_(You'll surely have a better solution than that, but it's the faster one I found)_
Add an `--overflow` global variable to `ion-tab-button` (for his button-native) child
(It wont work directly though, because ion-tabs have a `contain: strict` css value.

But it would let those who want this feature change the contain to none, and then change the oveflow of the button

**Related Code**
![image](https://user-images.githubusercontent.com/44493964/80080009-4d109900-8551-11ea-94ca-c1dde5e06cf9.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is already possible in Ionic Framework.

CodePen example: https://codepen.io/liamdebeasi/pen/NWGdBKz
