### ISSUE TITLE
bug: Problems with dynamic tabs in an IonTabBar

### ISSUE THREAD

**Issue by aub** [ionic-team/ionic#21112]
# Bug Report

**Ionic version:**

[x] **5.0.7**

**Current behavior:**
We have an app with a number of sections that can be enabled and disabled by the manager, and each of those sections corresponds to a tab. When the sections are disabled, we would like to stop rendering the tabs and their corresponding routes. But when starting with a disabled section and then turning it on, the app will crash with an error about `originalHref` in the IonTabBar. I've already dropped a PR for this issue [here](https://github.com/ionic-team/ionic/pull/21096).

But there is another problem... with that issue fixed, the crash goes away and the tab will appear correctly but clicking on the newly-added tab doesn't do anything. I haven't been able to figure out this issue yet.

**Expected behavior:**
I should be able to dynamically add and remove both tabs and their corresponding routes from an IonTabBar.

**Steps to reproduce:**

I've created a sample application [here](https://github.com/pegulabs/ionic-dynamic-tab-issues). It is a simple app based on the starter app with tabs. The third tab is disabled by default, and the first and second tabs have links that turn it on. When clicking on it you'll see the bad behavior.

**Related code:**

Sample application at https://github.com/pegulabs/ionic-dynamic-tab-issues

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.13 (/usr/local/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 5.0.7

Capacitor:

   Capacitor CLI   : 2.0.1
   @capacitor/core : 2.0.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.12.0 (/usr/local/Cellar/node/13.12.0/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina
```

**Comment by elylucas** [comment]
Hi @aub,

We have a dev release that should fix this issue. If you can, could you try to install it and let us know if it fixes the issue and if you run into any others? To install it run:

`npm i @ionic/react@5.3.0-dev.202006222125.df37029 @ionic/react-router@5.3.0-dev.202006222125.df37029`

If all goes good this should be available in the next Ionic release.

Thanks!

**Comment by aub** [comment]
Yep, it does seem to be fixed. Thanks!
