### ISSUE TITLE
bug: White Space behind Collapsable Header

### ISSUE THREAD

**Issue by kartiksolanki** [ionic-team/ionic#21135]
# Bug Report

I am using collapsable header in my ionic app and while the header is displaying perfectly, but when I swipe down on my page, it displays white space between the main ion-header and ion-content. View the screenshot here: https://drive.google.com/open?id=1FLL9jkVId0a1I4XZN0HptH_4JX5Jkdxe

**Ionic version:**
 Ionic CLI                     : 5.2.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

**Current behavior:**
White Space between Collapsable Header and Content when page swiped down.

**Expected behavior:**
White Space should not be shown while swiping down.

**Related code:**
```
<ion-header [translucent]="false" no-border>
  <ion-toolbar>
    <ion-title>
      Requests
    </ion-title>
    <ion-buttons slot="primary">
      <ion-button class="person-icon" (click)="showProfile()">
        <ion-icon slot="icon-only" name="person-outline" mode="md" color="light"></ion-icon>
      </ion-button>
    </ion-buttons> 
  </ion-toolbar>
</ion-header>

<ion-content [fullscreen]="true">
  <ion-header collapse="condense" no-border>
    <ion-toolbar color="primary">
      <ion-title size="large">Requests</ion-title>   
    </ion-toolbar>
    <ion-searchbar class="ion-text-left"  style="padding-bottom:0px;" mode="ios" [(ngModel)]="searchReq" animated type="search" placeholder="Search"></ion-searchbar>
  </ion-header>
......
```

**Ionic info:**
```
 Ionic CLI                     : 5.2.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
