### ISSUE TITLE
Ionic react's hot update plugin USES its own server for hot updates

### ISSUE THREAD

**Issue by q5222777** [ionic-team/ionic#21131]
Does the ionic react project have plug-ins that can be hot updated?
 I want this hot update to be done on my own server, similar to the cordova-hot-code-push, but this plugin is no longer available in the ionic4 react project. 

Because ionic react's capacitor project doesn't even have config.xml anymore,and Ionic react doesn't have the WWW folder, just the build folder

So can't set in config.xml like:
![1587834994940](https://user-images.githubusercontent.com/35521129/80286034-9af8ed00-875b-11ea-9068-b49d0697efd6.jpg)

Are there alternatives?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Ionic React uses `create-react-app` under the hood, so any customization will likely need to be done there: https://github.com/facebook/create-react-app.

**Comment by q5222777** [comment]
> 谢谢你的问题。Ionic React `create-react-app`在幕后使用，因此任何自定义操作都可能需要在此处进行：[https](https://github.com/facebook/create-react-app) : [//github.com/facebook/create-react-app](https://github.com/facebook/create-react-app)。

I'm asking about the hot update plugin

**Comment by q5222777** [comment]
> Thanks for the issue. Ionic React uses `create-react-app` under the hood, so any customization will likely need to be done there: https://github.com/facebook/create-react-app.

I'm asking about the hot update plugin

**Comment by liamdebeasi** [comment]
We do not manage that plugin, so I do not know if it works with Capacitor. Additionally, the plugin looks to be deprecated: https://github.com/nordnet/cordova-hot-code-push. In general, Cordova plugins mostly work with Capacitor unless they are listed here: https://capacitor.ionicframework.com/docs/cordova/known-incompatible-plugins.

**Comment by liamdebeasi** [comment]
There is also a plugin provided by Microsoft that looks to be maintained. Not sure if it works for your use case though: https://github.com/Microsoft/cordova-plugin-code-push

**Comment by q5222777** [comment]
> There is also a plugin provided by Microsoft that looks to be maintained. Not sure if it works for your use case though: https://github.com/Microsoft/cordova-plugin-code-push
> 
> **edit:** looks like someone forked it to add Capacitor support: https://github.com/areo/capacitor-codepush

Thanks. I'll try
