### ISSUE TITLE
bug: the RTL direction does not work on ion-slides in ionic 5

### ISSUE THREAD

**Issue by hannata** [ionic-team/ionic#21140]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**
the slides does not slide correctly when thr dir="rtl" is set. first i had an issue with the re-initializing of the slides but this solution fixed my problem 
[https://github.com/ionic-team/ionic/issues/20356#issuecomment-605272125](url)
but now the rtl direction does not work 

**Expected behavior:**
i need the slides to be able to slide to the right when the direction is set to rtl because i have arabic images that i need to display it was working fine in the ionic 4 but when i upgraded to ionic 5 and added this dev build it seems not working anymore

**Steps to reproduce:**
add a slider and the dir="rtl" on it 

**Related code:**

```
        <ion-slides [dir]="direction" slider [options]="slideOpts" (ionSlideDidChange)="slideChanged($event)">
            <ion-slide *ngFor="let image of images">
                <img class="book-pages" [src]="image" alt="">
            </ion-slide>
          </ion-slides>
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\hanna\node_modules\ionic)
   Ionic Framework            : @ionic/angular 5.1.0-dev.202003271919.8a161f0
   @angular-devkit/core       : 9.1.1
   @angular-devkit/schematics : 9.1.1
   @angular/cli               : 9.1.1
   @ionic/ng-toolkit          : not installed
   @ionic/schematics-angular  : not installed


   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 13 other plugins)

System:

   NodeJS : v12.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.10.2
   OS     : Windows 10


   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 13 other plugins)

System:

   NodeJS : v12.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.10.2
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Can you provide a full reproduction? RTL is working fine for me when I test it.

**Comment by hannata** [comment]
i fixed it, the initialization of the direction for the slides was in the wrong place, thank you for your time and for checking it

**Comment by liamdebeasi** [comment]
Glad to hear it is working now!
