### ISSUE TITLE
bug: page gets pushed when keyboard opens

### ISSUE THREAD

**Issue by lucaslevin** [ionic-team/ionic#21143]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

![RPReplay_Final1588033453](https://user-images.githubusercontent.com/20550508/80433628-bc8edb80-88f7-11ea-8bc7-9fb179eba8c2.gif)

**Expected behavior:**

Shouldn't push the entire view.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.6.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.901.3
   @angular-devkit/schematics    : 9.1.3
   @angular/cli                  : 9.1.3
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.0.1
   @capacitor/core : 2.0.1

Utility:

   cordova-res (update available: 0.13.0) : 0.6.0
   native-run (update available: 1.0.0)   : 0.2.8

System:

   NodeJS : v12.16.2 (/usr/local/Cellar/node@12/12.16.2_1/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
