### ISSUE TITLE
New ionic 5 app doesn’t render correctly in browser

### ISSUE THREAD

**Issue by pkitatta** [ionic-team/ionic#21165]
# Bug Report

**Ionic version:**
5

**Current behavior:**
I have a problem accessing the sidemenu ionic app in browser. The screenshots below are of a new created ionic app with sidemenu.

In full screen mode:
![2020-04-30_12h45_03](https://user-images.githubusercontent.com/17586059/80716148-fc281400-8aff-11ea-83cf-efa27e755c99.png)

If the browser is a fraction of the screen size:
![2020-04-30_12h47_17](https://user-images.githubusercontent.com/17586059/80716238-1661f200-8b00-11ea-8fc3-34799253c552.png)
As you can see here the menu icon is shown as it’s supposed to be and I can access the sidemenu.
The only thing I added here for demonstration purposes is the fab button with an icon. But as you can see the icon inside the fab button is not show. In my other - recently created real ionic project, things like the back button don’t render correctly.

**Expected behavior:**
The app should show the menu button all the time to have access to the side menu

**Steps to reproduce:**
Install ionic starter app with sidemenu

**Related code:**

Ionic start app with sidemenu

**Other information:**
As a side note however, sometimes everything renders correctly. This is like 1 out of 50 times the app reloads when am going about my business. So majority of the time it’s as shown about then once in a blue moon everything works.

**Ionic info:**

```
Ionic:

Ionic CLI : 5.2.3 (C:\Users\Paul\AppData\Roaming\npm\node_modules\ionic)
Ionic Framework : @ionic/angular 5.0.7
@angular-devkit/build-angular : 0.803.26
@angular-devkit/schematics : 8.3.26
@angular/cli : 8.3.26
@ionic/angular-toolkit : 2.2.0

Utility:

cordova-res : 0.6.0
native-run : 0.2.8

System:

NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
npm : 6.10.2
OS : Windows 10
```

**Comment by pkitatta** [comment]
Google Chrome is up to date
Version 81.0.4044.129 (Official Build) (64-bit)

Microsoft Edge 42.17134.1.0

It's the same on both.

**Comment by liamdebeasi** [comment]
Can you provide a repo? I am not seeing this on my end.

**Comment by pkitatta** [comment]
https://github.com/pkitatta/myApp.git

It is really just the ionic starter app. Just added the fab button.

**Comment by pkitatta** [comment]
One thing though; It does work on Mozilla Firefox

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I tested your repo with Chrome 81 on macOS and Windows 10, and the fab icon appeared as expected on both platform. Can you double check your code to make sure you included everything I need to reproduce the bug?

**Comment by pkitatta** [comment]
The only thing I made an input was the fab button. The code is as clean as ionic's starter template itself. The reason I include the fab is to show that icons don't render properly.

As noted, chrome it works once in a while at random. But as I have mentioned above Firefox is excellent

[Screen shot failed to upload]

The reason am concerned is that am building a PWA so I can only image that some users will fail to access the menu or see an icon.

**Comment by liamdebeasi** [comment]
Unfortunately I am unable to fix the issue if I cannot reproduce it. Do you have any other way for me to reproduce the issue? Also, when the issue does happen do you see any errors in your console?

**Comment by pkitatta** [comment]
![2020-05-02_22h12_07](https://user-images.githubusercontent.com/17586059/80873646-bd8e8700-8cc2-11ea-95fa-36b45ef96329.png)
![2020-05-02_22h15_09](https://user-images.githubusercontent.com/17586059/80873651-c8e1b280-8cc2-11ea-97c1-e68085792f91.png)
![2020-05-02_22h18_19](https://user-images.githubusercontent.com/17586059/80873674-e9117180-8cc2-11ea-9a83-f822fc904ca6.png)

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I understand that you are experiencing this issue, but I am unable to reproduce it. Are there any error in the browser console?

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
