### ISSUE TITLE
bug: Backdrop when opening ion-modal only applies to the body, not sidebar (ios)

### ISSUE THREAD

**Issue by jakamusic** [ionic-team/ionic#21178]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Key info:
- Component: ion-modal with swipeToClose: true
- App with split pane enabled
- Platform: iOS (iPad)

When opening ion-modal under these circumstances, the backdrop only applies to the main content and not the ion-menu as well.

Before opening the modal:
![Screenshot 2020-05-01 at 11 43 38](https://user-images.githubusercontent.com/14140628/80797073-2251c080-8ba1-11ea-8fb7-bc6e4c540408.png)

After opening the modal: 
![Screenshot 2020-05-01 at 11 43 44](https://user-images.githubusercontent.com/14140628/80797076-2382ed80-8ba1-11ea-9d5b-aca94be0a194.png)

**Expected behavior:**
Backdrop applies to whole body, or a different (proper) design entirely. 

**Steps to reproduce:**
Create app with the above properties and open ion-modal. 

**Other information:**
My suggestion is to redesign the modal to fit the iPad OS guidelines (or their implementation). See picture below: 
![1*_wMQJDOyYpC94ekbfP-_JQ](https://user-images.githubusercontent.com/14140628/80797125-47deca00-8ba1-11ea-866d-ab3bc259d26c.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try this on the latest version of Ionic Framework? This was fixed in a recent release.

**Comment by jakamusic** [comment]
Thanks for the info. It did get fixed.
