### ISSUE TITLE
support: what does "add parts support" means in 5.1.0 changelog

### ISSUE THREAD

**Issue by abuassar** [ionic-team/ionic#21189]
first congrats on this wonderful release!
I just noticed that "add parts support" is mentioned many times in the changelog and I wonder what does it mean exactly?

thanks and keep up the beautiful work :-)

**Comment by brandyscarney** [comment]
It's the beginning of us adding support for [CSS Shadow Parts](https://developer.mozilla.org/en-US/docs/Web/CSS/::part). We still have more planned for this. Stay tuned for a blog explaining this soon. 🙂
