### ISSUE TITLE
bug: Getting Gesture To Work with Swiping Up and Down

### ISSUE THREAD

**Issue by aaronksaunders** [ionic-team/ionic#21187]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
using gesture api, the swipe up event is being intercepted before gesture function

**Expected behavior:**
same behavior as swiping left to right

**Steps to reproduce:**

**Related code:**

https://codesandbox.io/s/ionic-react-gesture-7s6yd

**Other information:**
https://forum.ionicframework.com/t/getting-gesture-to-work-with-swiping-up-and-down/188439

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.6.0 (/Users/aaronksaunders/.nvm/versions/node/v13.5.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.0.7

Capacitor:

   Capacitor CLI   : 2.0.1
   @capacitor/core : 2.0.1

Utility:

   cordova-res (update available: 0.14.0) : 0.11.0
   native-run                             : 1.0.0

System:

   NodeJS : v13.5.0 (/Users/aaronksaunders/.nvm/versions/node/v13.5.0/bin/node)
   npm    : 6.14.1
   OS     : macOS Catalina```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Gestures default to listening only on the x-axis. Since you want to be able to swipe up and down, you should set `direction: "y"` when creating your gesture.

**Comment by aaronksaunders** [comment]
apologies... will do a better job reviewing documentation in future

**Comment by liamdebeasi** [comment]
No worries! Glad it's working now.
