### ISSUE TITLE
bug: ion-input and autocapitalize words value

### ISSUE THREAD

**Issue by terrancle** [ionic-team/ionic#21195]
The "words" value of the autocapitalize attribute does not work normally.
The value words allows you to ask the keyboard to put the capital letter on the first character of each word.
In versio Ionic 5.0.7, the first two characters are capitalized.
Example: "Alain" and not "ALain".
Can you fix this bug please?

**Comment by terrancle** [comment]
<ion-input type="text" formControlName="libelle" aria-required="true" required="true" autocapitalize="words"></ion-input>

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
