### ISSUE TITLE
bug: ion-datetime value=""

### ISSUE THREAD

**Issue by Fc299684** [ionic-team/ionic#21191]
I am new to Ionic, it may be somewhat outdated.
Discard if so.

Working with ion-datetime.

set value = "2020" and when performing ionic serve and open in my browser value was -1.
Example:
value = "2020"
"2019" was displayed

no repro in Stackblitz >>>>>>>>>>>>>>>>
https://ionic-4zupt3.stackblitz.io/

ionic version with angular: 5.4.16
Google Chrome: Versión 81.0.4044.129 (Build oficial) (64 bits)
Win 10 

![ionic](https://user-images.githubusercontent.com/57307805/80852726-2281a880-8c01-11ea-9cea-98adff86ad1e.png)
![ionic2 ](https://user-images.githubusercontent.com/57307805/80852727-231a3f00-8c01-11ea-867c-352c52c13411.png)

Kind Regards!

**Comment by liamdebeasi** [comment]
Thanks for the issue. What is the bug you are running into?

**Comment by Fc299684** [comment]
> Thanks for the issue. What is the bug you are running into?


UI does not display date correctly

**Comment by liamdebeasi** [comment]
Can you be more specific? A detailed description of the bug would be very helpful.

**Comment by Fc299684** [comment]
> ¿Puedes ser mas específico? Una descripción detallada del error sería muy útil.

![image](https://user-images.githubusercontent.com/57307805/82065034-f0ae1e80-96a3-11ea-8d64-49a6e69b9373.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21309 and a fix will be available in an upcoming release of Ionic Framework.

I also noticed your example is using Ionic 3. Ionic 3 is only receiving critical security updates moving forward, so if you would like to get this fix we recommend upgrading your application to Ionic Framework v5.
