### ISSUE TITLE
bug: IonBackButton does not work with standard browser back

### ISSUE THREAD

**Issue by fyrstelin** [ionic-team/ionic#21197]
# Bug Report

**Ionic version:**
[x] **@ionic/react-router 5.1.0**

**Current behavior:**
When pressing back (physical button android or back in browser) after navigating to and from a child page, a transition to the same page happens.

**Expected behavior:**
When pressing back (physical button android or back in browser) after navigating to and from a child page, the browser navigate to the previous page.

**Steps to reproduce:**
Check out [this repo](https://github.com/fyrstelin/bug-ion-back-button) or create an app with:
- two routes: root and child
- root page with a button that navigates from root to child
- child page with a IonBackButton

then: 
- on root page, navigate to child
- on child page, press the IonBackButton
- now you should be on the root page again. Press back in your browser, and the unexpected transition will occour.

**Related code:**

```
const Root = () => {
  return <IonPage>
    <IonHeader>
      <IonToolbar>
        <IonTitle>Root</IonTitle>
      </IonToolbar>
    </IonHeader>
    <IonContent>
      <IonList>
        <IonItem>
          <IonLabel>1. Visit child page:</IonLabel>
          <IonButton routerLink='/child'>Child</IonButton>
        </IonItem>

        <IonItem>
          <IonLabel>3. Here stuff goes wrong:</IonLabel>
          <IonButton onClick={() => window.history.back()}>Go back</IonButton>
        </IonItem>
      </IonList>
    </IonContent>
  </IonPage>
}

const Child = () => <IonPage>
  <IonHeader>
    <IonToolbar>
      <IonButtons slot='start'>
        <IonBackButton/>
      </IonButtons>
      <IonTitle>
        Child
      </IonTitle>
    </IonToolbar>
  </IonHeader>
  <IonContent>
    2. go back using the IonBackButton
  </IonContent>
</IonPage>

const App = () => <IonReactRouter>
  <IonRouterOutlet>
    <Route exact path='/'>
      <Root/>
    </Route>
    <Route path='/child'>
      <Child/>
    </Route>
  </IonRouterOutlet>
</IonReactRouter>
```

**Other information:**
I believe that [this line](https://github.com/ionic-team/ionic/blob/9308f0329c4c0c0674a7f34b5be391c4690b6812/packages/react-router/src/ReactRouter/Router.tsx#L441) should be pop instead of replace. There may be a reason for the replace behavior, but I cannot figure out why.

**Ionic info:**
I do not have the Ionic cli installed, but I am using:
@ionic/core: 5.1.0
@ionic/react": 5.1.0
@ionic/react-router": 5.1.0

**Comment by elylucas** [comment]
Hi @fyrstelin 

We have a dev release that should fix this issue. If you can, could you try to install it and let us know if it fixes the issue and if you run into any others? To install it run:

`npm i @ionic/react@5.3.0-dev.202006222125.df37029 @ionic/react-router@5.3.0-dev.202006222125.df37029`

If all goes good this should be available in the next Ionic release.

Thanks!

**Comment by fyrstelin** [comment]
The bug seems fixed. Thank you very much :+1:
