### ISSUE TITLE
feat: AlertController inputs should be having minlength, maxlength options for text fields

### ISSUE THREAD

**Issue by almothafar** [ionic-team/ionic#21202]
# Feature Request

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
As sometimes I need to show alert user and asking him for inputs alert `AlertInput` got options for min/max and seems those working for numeric to date fields, but what if I want to limit the length of the text that user provide, so I think maxlength and minlength should be added.

**Describe Preferred Solution**
Just adding these to `AlertInput` and apply the change to the rendered input.

**Additional Context**
This is been requested in the forum and the solution provided with "hack" but seems is not working for some reason.
https://forum.ionicframework.com/t/ionic-unable-to-fix-maxlength-for-prompt-input-of-alert-controller/119472

**Comment by liamdebeasi** [comment]
While we are at it, we should find a way to make it easy for devs to add other input attributes beyond just max/min length.

**Comment by cerkiner** [comment]
@liamdebeasi perhaps we can have a new generic "attr" option that can set custom attributes for inputs. For example like this:


```
let alert = this.alertCtrl.create({
    title: 'Login',
    inputs: [
      {
        name: 'pin',
        placeholder: 'Pin Code',
        type: 'password',
        attr: { 
                maxLength: 4,
                inputmode: 'numeric',
                ...
        }
      }
    ],
    buttons: [
      {
        text: 'Cancel',
        role: 'cancel'
      },
      {
        text: 'Save',
        handler: data => {
          console.log('Save clicked');
        }
      }
    ]
  });
  alert.present();
}
```

**Comment by cerkiner** [comment]
Another approach could be having individual new options for inputs to set custom attributes while creating alerts;

```
alert.addInput({
      name: 'pin',
      placeholder: 'Pin Code',
      type: 'password',
      maxLength: 4,
      inputmode: 'numeric',
      ...
});
```

**Comment by cerkiner** [comment]
Is anyone interested in this feature? @liamdebeasi 

I can spend some time on it if I can learn which approach would be more approvable?

**Comment by liamdebeasi** [comment]
Hey there! I spoke with the team, and we like the approach found in https://github.com/ionic-team/ionic/issues/21202#issuecomment-628346708, though let's call it `attributes` instead of `attr` since we do not abbreviate any of the other names.

Here is our contributing guide that gives you an overview of how to make the changes, test, and create a PR: https://github.com/ionic-team/ionic/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request.

Let me know if you have any questions 😊.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. This has been resolved via https://github.com/ionic-team/ionic/pull/21365 and will be available in an upcoming release of Ionic Framework. Thanks to @cerkiner for all the hard work in getting this feature done! 🎉
