### ISSUE TITLE
feat: Whether ion-toggle can add functions that are completely controlled by the user

### ISSUE THREAD

**Issue by C-racker** [ionic-team/ionic#21208]
# Feature Request

**Ionic version:**

[x] **5.1**

**Describe the Feature Request**

Currently, whether checked is currently set or not, clicking checked will change the state of the switch

You want the final state to be user-defined after the component is clicked

**Describe Preferred Solution**

ion-toggle add Events ionControl

**Describe Alternatives**

>https://ng.ant.design/components/switch/en

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please describe your use case for this feature?

**Comment by C-racker** [comment]
> Thanks for the issue. Can you please describe your use case for this feature?

https://stackblitz.com/edit/ionic-v4-angular-tabs-atkvrd?file=src%2Fapp%2Ftab1%2Ftab1.page.html

I want to control toggle2 through the state of toggle1, but it has not reached my expectation. For example, when toggle1 is true, I can freely switch the state of toggle2

**Comment by liamdebeasi** [comment]
Thanks for the follow up. This should already be possible in Ionic Framework.

Here is a StackBlitz with an example: https://stackblitz.com/edit/ionic-v4-angular-tabs-ghj67w

In the example, changing `toggle1` will also change the value of `toggle2`; however, manually changing the value of `toggle2` will not change the value of `toggle1`. Is this the behavior you want?

**Comment by C-racker** [comment]
> Thanks for the follow up. This should already be possible in Ionic Framework.
> 
> Here is a StackBlitz with an example: https://stackblitz.com/edit/ionic-v4-angular-tabs-ghj67w
> 
> In the example, changing `toggle1` will also change the value of `toggle2`; however, manually changing the value of `toggle2` will not change the value of `toggle1`. Is this the behavior you want?

https://stackblitz.com/edit/ionic-v4-angular-tabs-6s7tp1?file=src/app/tab1/tab1.page.ts

您可能理解错我的意思了，我想要做的是，`toggle1`为`true`的时候才可以手动更改`toggle2`的值，`toggle1`为`false`的时候不允许更改`toggle2`的值，但是上面的例子可以看到，我打印的`toggle2`为`true`，但是界面上的`ion-toggle`并没有被勾选

----Google Translate
You may have misunderstood what I meant. What I want to do is that you can manually change the value of `toggle2` when`toggle1` is `true`, and you cannot change`toggle2` when `toggle1` is` false` Value, but as you can see in the above example, the `toggle2` I printed was`true`, but the `ion-toggle` on the interface was not checked

**Comment by liamdebeasi** [comment]
Thanks for the clarification. I am going to close this as what you described is already possible in Ionic Framework.

Here is a StackBlitz with an example: https://stackblitz.com/edit/ionic-v4-angular-tabs-l8wqfh

In the example, when `toggle1` is `true`, I am unable to change the value of `toggle2`. When `toggle1` is `false`, I can manually change the value of `toggle2`.  I was able to accomplish this by programmatically disabling `toggle2` depending on the state of `toggle1`.

**Comment by C-racker** [comment]
> Thanks for the clarification. I am going to close this as what you described is already possible in Ionic Framework.
> 
> Here is a StackBlitz with an example: https://stackblitz.com/edit/ionic-v4-angular-tabs-l8wqfh
> 
> In the example, when `toggle1` is `true`, I am unable to change the value of `toggle2`. When `toggle1` is `false`, I can manually change the value of `toggle2`. I was able to accomplish this by programmatically disabling `toggle2` depending on the state of `toggle1`.

我现在有业务上的需求，需要在切换前进行判断是否可以改变`toggle2`的值，并且`toggle1`是异步的，目前`disabled`属性解决不了实际问题，并且也会影响样式，目前希望开关的样式完全由用户自己决定

----Google Translate
I have business requirements now, and I need to judge whether the value of `toggle2` can be changed before switching. Besides, `toggle1` is asynchronous, and the `disabled` property cannot solve the actual problem at present, and it will also affect the style. At present, I hope the style of the switch is completely determined by the user
