### ISSUE TITLE
Is there a config.xml file? Because many plug-ins of cordova need to set parameters in it

### ISSUE THREAD

**Issue by q5222777** [ionic-team/ionic#21201]
Is there a config.xml file? Because many plug-ins of cordova need to set parameters in it

ionic react capacitor project
 "@types/react": "^16.9.17"
 "@capacitor/android": "^2.0.1"

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is more of a support request. Please see https://capacitor.ionicframework.com/docs/basics/configuring-your-app/.
