### ISSUE TITLE
https://res.ionic.io/api/v1/upload

### ISSUE THREAD

**Issue by beibei7278** [ionic-team/ionic#21217]
**Ionic version:**

[x] **4.x**
[ ] **5.x**

**I'm submitting a ...** 

[ ] bug report
[ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by beibei7278** [comment]
PS F:\workspace\tzWorkSpace\ionicWork\yqbApp> ionic cordova resources

? The Ionic CLI has an update available (3.20.0 => 5.4.16)! Would you like to install it? No
Not automatically updating your CLI.
√ Collecting resource configuration and source images - done!
√ Filtering out image resources that do not need regeneration - done!
× Uploading source images to prepare for transformations - failed!
HTTP Error 503: POST https://res.ionic.io/api/v1/upload

**Comment by indraraj26** [comment]
https://github.com/ionic-team/ionic/issues/20908#issuecomment-606865282

**Comment by liamdebeasi** [comment]
Thanks for the issue. Please update your Ionic CLI. Very old versions of the CLI used an online version of resource generation. Newer versions of the CLI still have this, but the generation is all done on your machine.

```
npm uninstall -g ionic
npm i -g @ionic/cli
```
