### ISSUE TITLE
feat: Allow custom grid breakpoints

### ISSUE THREAD

**Issue by frankcs** [ionic-team/ionic#21213]
# Feature Request

**Ionic version:**
[x] **4.x**
[x] **5.x**

**Describe the Feature Request**
Allow custom grid breakpoints

**Describe Preferred Solution**
- Just let us overwrite a SASS variable for it like [it was before](https://ionicframework.com/docs/v3/theming/responsive-grid/#default-breakpoints
). I get that CSS variables are the preferred way to go now, but this particular thing [should be configurable](https://ionicframework.com/docs/v3/theming/responsive-grid/#grid-tiers).

**Describe Alternatives**
Sorry, no alternatives :(

**Comment by liamdebeasi** [comment]
Thanks for the issue. We are currently unable to add support for customizing breakpoints. This is due to limitations when using CSS Variables + media queries and is not something we can workaround currently.

For more information, please see: https://ionicframework.com/docs/theming/advanced#variables-in-media-queries

**Comment by frankcs** [comment]
@liamdebeasi. Thanks for your quick response. I know about the issue with CSS variables and media queries that's why I suggested:

> Just let us overwrite a SASS variable for it like it was before. I get that CSS variables are the preferred way to go now, but this particular thing should be configurable.

Please this is really a core issue, not being able to overwrite breakpoints might render the ion-grid component useless, and it is great component. Please consider my suggestion before dismissing this. Thanks again!

**Comment by brandyscarney** [comment]
Unfortunately it is not possible for us to allow the Sass variables to be overwritten as the web components are distributed *after* this build step. The [custom media query spec](https://drafts.csswg.org/mediaqueries-5/#custom-mq) will make it possible to set the media query as a variable. This is not available in browsers yet, however there is a [PostCSS plugin](https://github.com/postcss/postcss-custom-media) to add a build step for it. We don't have the bandwidth to look into how this would work with our components right now, but if it's something you'd like to look into that could be a potential internal fix.
