### ISSUE TITLE
An error occurred while running git.exe rev-parse HEAD (exit code 128)

### ISSUE THREAD

**Issue by Asalerm** [ionic-team/ionic#21215]
When I run 
ionic package build android
and select release, it shows me this error::

An error occurred while running git.exe rev-parse HEAD (exit code 128)

Any help is needed thank you very much.

**Comment by liamdebeasi** [comment]
Thanks for the issue. If you are running into an issue with AppFlow, please contact AppFlow support. This issue tracker is dedicated to bugs and feature requests for Ionic Framework.
