### ISSUE TITLE
feat: make CanDeactivate guard work with stacked navigation

### ISSUE THREAD

**Issue by kamilchlebek** [ionic-team/ionic#21218]
# Feature Request

Assume that you have form with few controls. Inside that form there's a button that navigates to `SearchPage` which allows you to look for item to be selected. After clicking an element inside `SearchPage` you go back (pop) to the form. 

Additionally there's a `CanDeactivate` guard configured to prevent user from loosing unsaved data. 

The problem is that I wan't to display leave confirmation only when `FormPage` is about to be destroyed. Confirmation should not be shown while navigating to `SearchPage` since `FormPage` is not destroyed and it's still present in the DOM. 

**Related Code**

Currently `canDeactivate` is always called. Demo: https://stackblitz.com/edit/ionic-angular-v5-r8uzq2

In case I missed something and it's possible to do it, let me know. 

_Edit_
**Workaround**

I found temporary workaround. Inside my `CanDeactivateGuard` I'm accessing **private(!)** field of `NavController` - `direction`. If `direction=='forward'` then I'm skipping confirmation dialog. 

Maybe it'll be enough, if ionic would append `direction` to `ActivatedRouteSnapshot.data`. Then I could easily use it inside `canDeactivate` method.

**Comment by indraraj26** [comment]
You can hold state in one extra boolean to know where is about to go, Additional i use if form.dirty etc

**Comment by kamilchlebek** [comment]
Actually I'm using `form.dirty`, but it's not enough to decide whether show confirmation while pushing another page at the top of the stack. 

Surely I could hack it somehow by watching route events and disable `canDeactivate`, but I think it will introduce some issues. (ex. I'd need to "ignore" `navigateFoward` but `navigateRoot` shouldn't be ignored)

**Comment by indraraj26** [comment]
> Maybe it'll be enough, if ionic would append `direction` to `ActivatedRouteSnapshot.data`. Then I could easily use it inside `canDeactivate` method.

This will only handle back , what if there are 3 action on page, I want to allow him to go on 1 action but not on other action. and all action are forward navigation.

I think router.events would be better option here. 

Lets wait for **Liam** response on this.

**Comment by mhartington** [comment]
Hey, could you help us better understand? 

You're on Page 1
You navigate to Page 2
You navigate back to Page 1

Where in this "flow" are you trying to have a confirmation?

**Comment by kamilchlebek** [comment]
Sure. I've created mockup with flow that I'm trying to achieve.

Mockup: https://ninjamock.com/s/DLQGKGx

Flow: Appointment list -> Create new appointment -> here I want to assign user to new appointment, this user may be either selected from existing ones or newly created. 
Confirmation popup should be displayed only when form is dirty and you're trying to comeback to appointment list.

**Comment by mhartington** [comment]
Ahh ok, so the page in question is the middle index of an array of routes.
Hmm, not really something that is "broken" in my opinion, but it does seem like angular could use a "canDestroy" guard  or something a long those lines.

But given the flow you have, you could hard code the URL in there and make that part of your check.

https://stackblitz.com/edit/ionic-angular-v5-k5voiq?file=src%2Fapp%2Fapp.module.ts

**Comment by kamilchlebek** [comment]
This looks like good solution, thank you. 

At first I thought that it could be achieved with ionic. but you're right. I should either use `nextState` in my `canDeactivate` or angular could add `canDestroy` hook.

**Comment by liamdebeasi** [comment]
Glad to hear the solution works for your use case. I am going to close this issue. Thanks!
