### ISSUE TITLE
feat: for Pwa Side bar Menu draggable &/or button to manually hide

### ISSUE THREAD

**Issue by MInesGomes** [ionic-team/ionic#21219]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

For Pwa Side bar Menu have the possibility of a draggable &/or button to manually hide de sidebar Menu

**Additional Context**

In situations like this
https://github.com/MInesGomes/Ionic-Sidebar-Suggestion/blob/master/sidebar.gif

It would be nice the user be able to hide manually the sidebar or change the size manually

**Describe Preferred Solution**

Have a button like this to hide manually the side bar or/and change the size manually
https://github.com/MInesGomes/Ionic-Sidebar-Suggestion/blob/master/sidebarHide.png

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify your feature request?

You can hide the side menu by setting the `disabled` property on `ion-split-pane` to `true`: https://ionicframework.com/docs/api/split-pane#properties.

In addition, you can change the size of the side menu by setting the `--width` CSS variable: https://ionicframework.com/docs/api/menu#css-custom-properties

**Comment by MInesGomes** [comment]
Thanks @liamdebeasi for the css properties. 
The suggestion I am making is to let the user change dynamically the menu:
When the mouse is in the border, changes to draggable 
![PngItem_1083829](https://user-images.githubusercontent.com/3248158/81295292-7dd3f080-9070-11ea-94c8-b465cc7e203c.png)

and when pressed can drag to change the size. 
Something like this do drag:

https://github.com/MInesGomes/Ionic-Sidebar-Suggestion/blob/master/menuHidding.gif

And to hide the menu maybe in the borders button like:

<img width="803" alt="Screenshot 2020-05-07 at 14 51 38" src="https://user-images.githubusercontent.com/3248158/81296757-ad83f800-9072-11ea-88a3-296de15e2f6c.png">

And after clicked, the menu is hidden, but the button is not hidden, so the user is able to 'unhide' the menu
<img width="803" alt="Screenshot 2020-05-07 at 14 52 30" src="https://user-images.githubusercontent.com/3248158/81296869-d5735b80-9072-11ea-85b0-fed8110f5458.png">

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I discussed this feature request with the team, and while we definitely agree this is a useful feature, we feel this is better implemented on a per-app basis.

I made a CodePen that shows how you can implement this in your own application: https://codepen.io/liamdebeasi/pen/KKdodjd

The code that is responsible for updating the sizing of the menu uses the gesture utility that Ionic exposes: https://ionicframework.com/docs/utilities/gestures

Hope this helps!

**Comment by MInesGomes** [comment]
Thank you @liamdebeasi . Really nice!
