### ISSUE TITLE
bug: gracefully fail if IntersectionObserver is not available

### ISSUE THREAD

**Issue by DavidStrausz** [ionic-team/ionic#21221]
# Bug Report

**Ionic version:**
[x] **5.1**

**Current behavior:**
When using collapsible headers on iOS devices running iOS versions <12.2 without `IntersectionObserver` support an error is thrown:

`ReferenceError: Can't find variable: IntersectionObserver`

Which I also leads to another error while trying to animate the large title during page transition, which prevents the app from working correctly:

`TypeError: null is not an object (evaluating 'clonedTitleEl.innerText = largeTitleEl.innerText')`

**Expected behavior:**
As there is no reasonable polyfill available for the `IntersectionObserver` API the exception should at least be handled so it just fails silently and also the animation should make sure `clonedTitleEl` and `largeTitleEl` exist before accessing properties on them.

**Steps to reproduce:**
Run any app using collapsible headers on a device without `IntersectionObserver` support.

**Related code:**
https://github.com/ionic-team/ionic/blob/794c3d4e9608968d8d5ef8b77f9b024fa0131572/core/src/components/header/header.tsx#L117

https://github.com/ionic-team/ionic/blob/8a02b28efeca81c25176ff52508b4005441e8314/core/src/utils/transition/ios.transition.ts#L182

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21222, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by DavidStrausz** [comment]
@liamdebeasi Hi Liam, unfortunately only one part of the problem was fixed: the ReferenceError does not happen anymore in 5.1.1 but the exception in the page transition is still happening.

**Comment by liamdebeasi** [comment]
Fixed via https://github.com/ionic-team/ionic/pull/21339
