### ISSUE TITLE
Icons not rendered on prerender

### ISSUE THREAD

**Issue by VBagmut** [ionic-team/ionic#21228]
**Stencil version:**

```
 @stencil/core@5.0.7
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I've initialized empty project with `npm init stencil`, chose first option, made little changes (added simple button), ran `npm run build --prerender`, opened result HTML file with a local server (Live Server extension for VS Code) and found out that `ion-back-button` is not rendered - it is present in the DOM but not rendered visually as it was in dev mode. Possibly this affects all ionic icons.

**Expected behavior:**
All icons are rendered correctly at prerender step.

**Steps to reproduce:**
`npm init stencil`
`npm run build --prerender`
open HTML file with a local server
go to profile page and see empty button

**Other information:**
I've added red pointer to make to find button that I meant.
* screenshot on dev mode (`npm start`)
<img width="546" alt="Screenshot 2020-04-29 at 19 47 30" src="https://user-images.githubusercontent.com/29337902/80627331-69806a00-8a58-11ea-8baa-439eda299438.png">
* screenshot on prerender mode (`npm build --prerender`) and then opening with a local server
<img width="546" alt="Screenshot 2020-04-29 at 20 29 49" src="https://user-images.githubusercontent.com/29337902/80627339-6b4a2d80-8a58-11ea-8dac-4f7d9a39c6c1.png">

label: prepender

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
