### ISSUE TITLE
Accessibility: delete role="banner" on ion-header

### ISSUE THREAD

**Issue by terrancle** [ionic-team/ionic#21235]
Hello,

Screen readers are a little too verbose because of the role = "banner" of the ion-header tag.
This information is not useful for the header of an application.
For example, the ionBackButton back button is followed by textual information "Banner".
Perhaps you could just remove role = "banner" from the ion-header tag, so that screen readers can understand the page as an application and not as a web page.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Having `role="banner"` on `ion-header` is important as it identifies the main heading of a page to the screen reader. 

For developers that do not want this, they can customize it by setting `role="none"` on the `ion-header` element. Thanks!

**Comment by terrancle** [comment]
Hello,
I tried to add the role = "none" property to my ion-header tag, but the role = "none" is not taken into account, the role = "banner" is added forcefully.
How to do?

<ion-header [translucent]="true" mode="ios" role="none">

**Comment by liamdebeasi** [comment]
Hmm strange. I must have been doing something wrong when I tried it out last time.

I have created https://github.com/ionic-team/ionic/issues/21327 that should address this.
