### ISSUE TITLE
bug: AOT Build Does Not Have Access To environment in AppModule Imports

### ISSUE THREAD

**Issue by btate** [ionic-team/ionic#21241]
It's difficult to set this up in a plunker, but what I'm seeing is that environment variables don't seem to be acknowledged in AOT compilation. 

In my app module I am importing a custom service forRoot

`import { environment } from 'src/environments/environment';`

> ApiModule.forRoot({
>      someUrl: environment.someUrl
>      someOtherVariable: 'explicit text'
>   }),

When I do a build without AOT the environment variable is set appropriately. When I build with AOT the only configuration set is the 'explicit text'. 

I'm at a loss as to why. 

This is defined in the AppModule imports

Ionic Info:

Ionic:

   Ionic CLI                     : 5.4.15
   Ionic Framework               : @ionic/angular 4.11.0
   @angular-devkit/build-angular : 0.803.23
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 23 other plugins)

Utility:

   cordova-res (update available: 0.14.0) : 0.8.1
   native-run (update available: 1.0.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/btate/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.14.0 (/Users/btate/.nvm/versions/node/v12.14.0/bin/node)
   npm               : 6.13.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.4.1 Build version 11E503a

**Comment by btate** [comment]
This issue has recently surfaced. I'm confused as to why?

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
