### ISSUE TITLE
bug: ion-content is not visible on production build running on iPhone 11 Pro Max

### ISSUE THREAD

**Issue by hanibhat** [ionic-team/ionic#21252]
# Bug Report

**Ionic version:**

Ionic CLI: 6.6.0
ionic/angular: 5.1.0

**Current behavior:**

When building the project with the production flag using either one of the following commands:
`ionic cordova run ios --prod -l`
`ionic cordova build ios --prod --release`

**Expected behavior:**

`ion-content` displays properly and visibly under `ion-header`

**Steps to reproduce:**

Build or run an Ionic 5 project with the `--prod` flag

**Related code:**

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.6.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.901.4
   @angular-devkit/schematics    : 9.1.4
   @angular/cli                  : 9.1.4
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 28 other plugins)

Utility:

   cordova-res : 0.14.0
   native-run  : 1.0.0

System:

   ios-sim : 8.0.2
   NodeJS  : v12.16.2 (/usr/local/bin/node)
   npm     : 6.14.4
   OS      : macOS Catalina
   Xcode   : Xcode 11.4.1 Build version 11E503a
```

**Comment by capc0** [comment]
can you please check if it is also reproduceable in a simulator?

**Comment by hanibhat** [comment]
@capc0 it happens when I run it on iPhone 11 Pro Max in the simulator. I also noticed it happened on an actually Huawei Mate 30 Pro 5G!

**Comment by capc0** [comment]
Ok I guess that you have some specific code in your app that is leading to this problem than. I also tested some of my apps on the iPhone 11 Pro Max simulator and could not see the issue.

**Comment by hanibhat** [comment]
I dug a bit more and the issue appeared on all iOS devices when built with the `--prod` flag. The issue was in my code as @capc0 noted. I had an `ion-toolbar`, in an `ion-header`, styled with `height: 100%` in `global.scss`, which resulted in pushing `ion-content` out of the screen. Being only reproducible on iOS production build, made initially not think of my code as the reason. 
@capc0 Thank you!
Closing this issue.
