### ISSUE TITLE
ion-searchbar tag not working correctly

### ISSUE THREAD

**Issue by sandaramet** [ionic-team/ionic#21275]
# Bug Report
**Ionic version:**
6.8.0
**Current behavior:**
If add showCancelButton="always" in ion-searchbar it not show  always but it change ion-searchbar
search icon
Expected behavior:
The showCancelButton="always" show cancel icon always
**Steps to reproduce:**
add this <ion-searchbar showCancelButton="always"></ion-searchbar> in code 

**Related code:**
Template
```
 <ion-searchbar showCancelButton="always"></ion-searchbar>
```
**Other information:**
I use ionic and  angular 
**Ionic info:**
```

Ionic:

   Ionic CLI                     : 6.8.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.1.0

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   NodeJS : v10.19.0 (/usr/bin/node)
   npm    : 6.14.5
   OS     : Linux 5.4
```

**Comment by liamdebeasi** [comment]
Can you provide a reproduction of the issue? The code snippet you provided correctly shows the cancel button:

![image](https://user-images.githubusercontent.com/2721089/81609598-2acaa800-93a6-11ea-9ff9-26320efda543.png)

**Comment by sandaramet** [comment]
ion-searchbar.jpg --   <ion-searchbar ></ion-searchbar>
ion-searchbar-with-showCancelButton.jpg --  <ion-searchbar showCancelButton=
"always"></ion-searchbar>
If add showCancelButton="always"
 1. Cancel Button not showing always
 2. Changing search icon

 showCancelButton="always" is changeing search icon and not  always showing
cancel icon

**Comment by liamdebeasi** [comment]
@sandaramet Please provide a full code reproduction. As I mentioned before the code snippet does not reproduce the issue for me.

**Comment by sandaramet** [comment]
https://github.com/sandaramet/ionic-issue
You can see full code here

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you provide some steps to reproduce the issue?

This is what I see when I load your application:

| iOS | MD |
| ---- | ------- |
| ![localhost_8101_home_ionic_mode=ios(Galaxy S5)](https://user-images.githubusercontent.com/2721089/81613724-f4dcf200-93ac-11ea-8ca3-dc3cce04b688.png) | ![localhost_8101_home(Galaxy S5) (1)](https://user-images.githubusercontent.com/2721089/81613734-f9a1a600-93ac-11ea-9bf8-cfe3d7a0f618.png) |


Both screenshots show `show-cancel-button="always"` working as intended.

**Comment by sandaramet** [comment]
not correct search icon In MD mode if  `show-cancel-button="always"`

**Comment by sandaramet** [comment]
Why search icon changed ?

**Comment by liamdebeasi** [comment]
Can you please clarify what you mean? The cancel button on MD mode is supposed to be the arrow icon by default. The "cancel" icon is supposed to appear instead of the "search" icon when `showCancelButton="always"`.

**Comment by sandaramet** [comment]
[image: Screenshot from 2020-05-12 02-49-50.jpg]Ooh.I'm sorry I took your
time.I'm was thinking that showCancelButton="always" will be show this icon.
