### ISSUE TITLE
bug: accessibility problem with VoiceOver and segment-button

### ISSUE THREAD

**Issue by terrancle** [ionic-team/ionic#21271]
Hello,

Ionic 5.1 / angular.

When VoiceOver displays a page during the first load, the first button is correctly stated as selected, with an aria-pressed = "true".
However, when the user clicks on the second segment-button, VoiceOver no longer knows which segment-button is selected.
Probably aria-pressed is not updated when selecting another button.
Thank you.

<ion-segment (ionChange)="segmentChanged($event)" mode="ios" value="apple">
        <ion-segment-button value="apple">
          <ion-label>Apple</ion-label>
        </ion-segment-button>
        <ion-segment-button value="stripe">
          <ion-label>Stripe</ion-label>
        </ion-segment-button>
      </ion-segment>

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

`npm i @ionic/angular@5.2.0-dev.202005111937.1e6f923`

**Comment by terrancle** [comment]
Is good ! Thank you.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21273, and a fix will be available in an upcoming release of Ionic Framework.
