### ISSUE TITLE
feat: ion-segment-button width?

### ISSUE THREAD

**Issue by SvenBudak** [ionic-team/ionic#21284]
Currently it is not possible to change the width of a `ion-segment-button`: https://ionicframework.com/docs/api/segment-button

There is a web component button with class `.native-button`. So far I have not found a way to change the width of this element.

```css
.button-native {
    min-width: 90px;
}
```

Please use a css variable here to make the width editable.

I have already found other contributions from astonished developers.: https://forum.ionicframework.com/t/how-to-set-the-custom-width-of-a-ion-segment-button/174579

I have subsequently found an open issue on the topic: https://github.com/ionic-team/ionic/issues/21105

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/21105.
