### ISSUE TITLE
bug: history goBack in wrong direction if it was pushed with state

### ISSUE THREAD

**Issue by ChristineXYS** [ionic-team/ionic#21285]
# Bug Report

**Ionic version:**
6.8.0

**Current behavior:**
history push a page with state, then push another one. When go back, the animation direction is wrong.

**Expected behavior:**
work as normal mobile's push/pop direction.

**Steps to reproduce:**
Hi, I am using ionic react version 6.8.0, and I found you still have this kind of issue.

Assume we have page 1 pushing to page 2, page 2 pushing to page 3. The issue happens in this pseudo code:
In page 1:
history.push({
pathname: "page2",
state: {value:1}
});
In page 2:
history.push("page 3");

When navigate back from page 3 to page 2 using history.goBack(); , you can clearly see the action is PUSH instead of POP.

The bug is page 2 was pushed with a state, thus in your code, although setState {direction: "back"} previously, in the end it was replaced by the state {value: 1}, making wrong animation direction.

It can be visible by console.log every history in each page and check the location.state.

Please fix it as soon as possible, which causing push/pop nearly not usable in mobile.

**Related code:**

related to fix: https://github.com/ionic-team/ionic/commit/8b29e0933333d53766c8bdd31c64ed4687ee18b7

**Comment by ChristineXYS** [comment]
code reproduction:

In page 1:

history.push({
pathname: "page2",
state: {value:1}
});

In page 2:

history.push("page 3");

**Comment by liamdebeasi** [comment]
Hi there, I need a full code reproduction in order to reproduce this. The easiest way is to create a GitHub repo and include a link in this thread.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
