### ISSUE TITLE
feat: ion-picker with labels

### ISSUE THREAD

**Issue by nickwinger** [ionic-team/ionic#21280]
# Feature Request
It would be really good to have labels above the columns in the ion-picker.
e.g. if you want to present the user to select days, hours and minutes. How the user should know which column is which ??
They are all just numbers. So it would be really good to have an optional header/label above each column. I guess this could be implemented quit easy and then we could use the ion-picker more often, because it is a cool component. But without the labels we cannot use it...

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I am going to close this as this is already possible in Ionic Framework. You can use the `prefix` or `suffix` options when defining the picker columns for this.

CodePen with an example: https://codepen.io/liamdebeasi/pen/KKdeENR

![image](https://user-images.githubusercontent.com/2721089/81695231-585c3380-9430-11ea-9689-4909b35ccc7e.png)

**Comment by nickwinger** [comment]
pretty cool, thanks, maybe you can point that out a little bit better in the documentation, it was not obvious for me.
