### ISSUE TITLE
Ion-Slides blocked after navigating back

### ISSUE THREAD

**Issue by mufoyu** [ionic-team/ionic#21286]
**Ionic version:**

[ ] **4.x**
[x] **5.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**

I am currently using on a page the ion-slides, with buttons to slide to the described slide. When I navigate out of the page and navigate back the following slitTo function of the slides doesn't work anymore.
**Expected behavior:**

After navigating to the slides page, after click on the buttons it should slide to the described slide.
**Steps to reproduce:**

1. Navigate to slide page
2. Navigate to another page
3. Navigate back to slide page
4. The bug will appear

**Related code:**

Function:
```
public goToSlide(slide: number) {
    this.slides.slideTo(slide, 500);
  }
```
Button:
```
<ion-button *ngIf="this.workday.toDateString() != this.today.toDateString()" [color]="allSelectionsCheckedWorkday ? 'success' : 'dark'" fill="outline (click)="selectDay('workday');goToSlide(1)">{{workday | date: 'EEEE'}}<ion-icon *ngIf="allSelectionsCheckedWorkday" name="checkmark"></ion-icon></ion-button>
```

**Other information:**

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 6.1.0
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.900.2
   @angular-devkit/schematics    : 9.0.2
   @angular/cli                  : 9.0.2
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.7
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This was resolved in Ionic Framework 5.1. If you are still running into issues after updating, feel free to open a new issue. Thanks!
