### ISSUE TITLE
bug: ionic -V5: ion-contect background set image working, But while switching or navigating to another pages it was showing previous page for a while

### ISSUE THREAD

**Issue by Madhukumar1226** [ionic-team/ionic#21296]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

Navigating from one page to another page showing previous page  
**Expected behavior:**

without showing previous page redirect or navigate to new page

<img width="270" alt="issue" src="https://user-images.githubusercontent.com/53224537/81900622-d65c3e00-95da-11ea-9a19-a42b096bba50.png">

**Comment by cerkiner** [comment]
@Madhukumar1226 how are you adding the background image?

**Comment by Madhukumar1226** [comment]
> @Madhukumar1226 how are you adding the background image?

ion-content {
  --background: url("../theme/bg_overlay_graphic.png") no-repeat center/cover fixed;
}

**Comment by Madhukumar1226** [comment]
@cerkiner  By using --background

ion-content {
  --background: url("../theme/bg_overlay_graphic.png") no-repeat center/cover fixed;
}

**Comment by cerkiner** [comment]
@Madhukumar1226 how about this? same line with a default dark colour;

```
ion-content {
    --background: #10101A url("../theme/bg_overlay_graphic.png") no-repeat center/cover fixed;
}
```

The default background colour is transparent, I think that is the reason you are seeing what is in the background while your background image is not fully downloaded yet.

Here is a nice explanation; https://css-tricks.com/css-basics-using-fallback-colors/

**Comment by Madhukumar1226** [comment]
@cerkiner 
Thank You So much it's working fine
