### ISSUE TITLE
bug: Ion tabs navigate back doesnt animate 

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/ionic#21299]
Running:
Ionic 5
Angular 9

I have an app with a header bar and 2 buttons to the start and end, the first button at the start I would like to animate with navigate back however the page just jumps - the button at the end on the right navigates forward as expected.

Is there any way to make `this.navCtrl.navigateBack(['account'])` animate gracefully 

this issues seems to be related and similar https://github.com/ionic-team/ionic/issues/18181

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
