### ISSUE TITLE
bug: Strange live reload issue on IOS

### ISSUE THREAD

**Issue by dragoon000320** [ionic-team/ionic#21307]
# Bug Report

**Ionic version:**

[x] **5.24.0**
"@capacitor/android": "^2.0.2",
"@capacitor/core": "2.0.1",
"@capacitor/ios": "^2.0.2",

**Current behavior:**
when running with live reload on IOS, strange promise rejection happens:

[info] - [WDS] Live Reloading enabled.
[error] - ERROR Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'window['require'].on')
http://192.168.0.15:8101/home-home-module.js:244:45
ZoneAwarePromise@http://192.168.0.15:8101/polyfills.js:4226:37
requireModules@http://192.168.0.15:8101/home-home-module.js:242:29
onInvoke@http://192.168.0.15:8101/vendor.js:70644:39
run@http://192.168.0.15:8101/polyfills.js:3474:49
http://192.168.0.15:8101/polyfills.js:4205:39
onInvokeTask@http://192.168.0.15:8101/vendor.js:70625:43
runTask@http://192.168.0.15:8101/polyfills.js:3518:57
drainMicroTaskQueue@http://192.168.0.15:8101/polyfills.js:3909:42
invokeTask@http://192.168.0.15:8101/polyfills.js:3819:40
invokeTask@http://192.168.0.15:8101/polyfills.js:4953:20
globalZoneAwareCallback@http://192.168.0.15:8101/polyfills.js:4979:27

App doesn't crash, but doesn't work as expected.
On Android live reload works fine.

P.S. Strangely, live reload on IOS was functional yesterday, and today i ran it without any changes to source code, and it doesn't work. I also tried to normally build and sync ios and run without live reload server and it worked as expected...

**Expected behavior:**
Functional live reload on IOS

**Steps to reproduce:**
I don't have any clue

**Related code:**
I don't think that any specific code could be the reason for the error, as it worked fine perfectly with same source code

**Comment by elvisgraho** [comment]
I'v got the same error, but the reload works fine.

**Comment by dragoon000320** [comment]
@elvisgraho Same here. Maybe it's not clear from my report... I meant that live reload works on IOS, but everytime it reloads i get the reported issue. On Android I don't get that issue, and app works as expected.

**Comment by elvisgraho** [comment]
@dragoon000320 Issue was with my code. It happens where you use libs such as NatvieStorage or http and do not specify onError function when you load something or get request etc.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
