### ISSUE TITLE
bug: Ion Slides not functioning after navigating back to them

### ISSUE THREAD

**Issue by akilah007** [ionic-team/ionic#21305]
# Bug Report

**Ionic version:**
Ionic CLI                     : 6.8.0 (/Users/admin/.npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.901.1
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 9.1.1
   @ionic/angular-toolkit        : 2.2.0

**Current behavior:**
This will show first time 12 slides after navigating back to the same page it shows 1 slide even slides functions are not working

**Steps to reproduce:**

**Related code:**
slideOption = {
        slidesPerView: 1.2,
        spaceBetween: 0
      }

**Comment by elvisgraho** [comment]
Same issue with @ionic/angular 5.1.1
Does not work on the second initialization.

**Comment by akilah007** [comment]
I have reproduced using the below settings. It seems working fine.
Ionic CLI: 6.8.0
Ionic Framework : @ionic/angular 5.1.1
@angular-devkit/build-angular : 0.901.6
@angular-devkit/schematics    : 9.1.6
@angular/cli : 9.1.6
@ionic/angular-toolkit        : 2.2.0

**Comment by elvisgraho** [comment]
Same issue when using it in modal controller. @ionic/angular@latest @ionic/angular-toolkit@latest
