### ISSUE TITLE
bug: SwipeToClose not working on iOS

### ISSUE THREAD

**Issue by positiv-prod** [ionic-team/ionic#21306]
# Bug Report

**Ionic version:** Latest (5.1)

**Current behavior:**

When I want to open my modal, it's work like a charm, but when I want to swipe down to close it is impossible even if "SwipeToClose" is set to true (I've try with iPhone 11 Pro and with Google Chrome navigator in iOS mode too).

**Expected behavior:**

The normal behavior would be the ability to swipe down to close modal, it's simple.

**Steps to reproduce:**

- Start a new ionic project
- Create a component named modal
- Create a page named home
- In home.page.ts, create a function to call an ionic modal attached to modal component, add 'SwipeToClose' parameter (The code can be copied/pasted via StackBlitz)
- In home.page.html, create a button that call this function
- When you will try to swipe down, nothing happens

**Note : When I go in the HTML and delete ion-content (or add rule pointer-events:none) inside app-modal, it's work, but I need to have my component displayed ...**

**Related code:**

This is a Stackblitz for you to see by yourself : https://stackblitz.com/edit/ionic-angular-v5-u4wmun

-->

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
onic:

   Ionic CLI                     : 6.3.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.1
   @capacitor/core : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res (update available: 0.14.0) : 0.11.0
   native-run                             : not installed

System:

   ios-deploy : 1.10.0
   NodeJS     : v12.16.1 (/usr/local/bin/node)
   npm        : 6.13.4
   OS         : macOS Catalina
   Xcode      : Xcode 11.4 Build version 11E146
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. The Swipe To Close on your StackBlitz is working fine for me when running in iOS mode. Can you please check to see if you included all the code I need to reproduce the issue?

**Comment by camengadisaputra** [comment]
i think you need ion-header in your modal component
