### ISSUE TITLE
bug: ion-router back() fails second time (stencil app), including PR+reproduction

### ISSUE THREAD

**Issue by bitflower** [ionic-team/ionic#21300]
# Bug Report

**Ionic version:**

[x] **5.1.0**
[x] Stencil **1.12.7**

**Current behavior:**
When navigating to a sibling ion-route the `back()` method of the `ion-router` fails in such a way that the animations are not running the second and following times. The first time it works.

See this video: https://github.com/bitflower/ion-router-root-bug

![ion-router-rootbug](https://user-images.githubusercontent.com/6666636/81959322-8ba8e900-960f-11ea-86ff-e13632e8867e.gif)

**Expected behavior:**
The animations always run fine no matter how often a route was visited when we go back.

**Steps to reproduce:**
Run the repo with `npm i` then `npm start`. Navigate to the 2nd page with the link "Go to sibling". Navigate back to the root with the button. Repeat. The 2nd time the animation back to home isn't firing.

**Related code:**
Repo to easily reproduce: https://github.com/bitflower/ion-router-root-bug

**Comment by bitflower** [comment]
The same issue occurs when you use `window.history.back()`.

**Comment by bitflower** [comment]
@simonhaenisch refering to our Slack conversation - what do you think of this fix?

**Comment by Ravenstine** [comment]
I'm noticing this bug as well as a similar one with forward navigation.  For example, if I navigate to a URL, nagivate back, then use `.push('/my-url')` on the router, it may not animate the transition.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21301, and a fix will be available in an upcoming release of Ionic Framework.

Here is a dev build with the fix: `5.2.0-dev.202006081615.e0a066d`
