### ISSUE TITLE
how to build an APK from ionic/react to install on my android device or publish on google play?

### ISSUE THREAD

**Issue by hussein661** [ionic-team/ionic#21319]
I finished developed my app (ionic/react) what's next ? how to install that app on my device or on the google play ?

refering to docs : https://ionicframework.com/docs/deployment/play-store
on the first section #Generating a release build of an app

**I should get started with this command :**

`$ ionic cordova build android --prod --release`

**Im getting his error :**
```
[ERROR] Ionic doesn't support using Cordova with @ionic/react projects.
 We encourage you to try Capacitor (https://ion.link/capacitor)
```

> **on capacitor nothing is clear for me !**

**Comment by BerkeAras** [comment]
Did you try using this?
`cordova build android --prod --release`?
Try it without `ionic`. If that does not work try this:
```
npx cap copy android
npx cap open android
```

**Comment by lubakdev** [comment]
you can use capacitor, using command 
`ionic cap add android`
`ionic cap copy android`
`ionic cap run android`

after that android studio will open, you can build apk from android studio
