### ISSUE TITLE
bug: Build stuck on ionic appFlow

### ISSUE THREAD

**Issue by gartner90** [ionic-team/ionic#21312]
I am not able to create a new build because a before build is stuck 😢 
![Screen Shot 2020-05-16 at 2 08 48 AM](https://user-images.githubusercontent.com/4148505/82113270-6359e100-971a-11ea-9491-cfaccd578cb6.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. For issues with AppFlow, please get in touch with AppFlow Support via the web interface.
