### ISSUE TITLE
I am getting the following error while adding platforms i have tried almost everything that was found regarding this can anyone let me know what should be the solution to this 

### ISSUE THREAD

**Issue by Awais-mohammad** [ionic-team/ionic#21311]
Failed to fetch platform cordova-android@0.0.8
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Muhammad Awais\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "cordova-android@0.0.8" "--production" "--save-exact"
npm ERR! node v12.16.2
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: cordova-android@0.0.8
npm ERR! notarget Valid install targets:
npm ERR! notarget 9.0.0-nightly.2020.5.15.e86b211c, 9.0.0-nightly.2020.5.14.e86b211c, 9.0.0-nightly.2020.5.13.e86b211c, 9.0.0-nightly.2020.5.12.e86b211c, 9.0.0-nightly.2020.5.11.e86b211c, 9.0.0-nightly.2020.5.10.e86b211c, 9.0.0-nightly.2020.5.9.e86b211c, 9.0.0-nightly.2020.5.8.e86b211c,

**Comment by Awais-mohammad** [comment]
This is the picture of the error
![Screenshot (102)](https://user-images.githubusercontent.com/64267313/82103677-614d4d80-972d-11ea-8f53-23ee818be793.png)

**Comment by camengadisaputra** [comment]
try change your android cordova-android version
