### ISSUE TITLE
accessibility: Please repair the name of ion-menu-button

### ISSUE THREAD

**Issue by terrancle** [ionic-team/ionic#21315]
Hello,

It is not possible to give a name to a menu button.

With the following code, VoiceOver says "menu outline", when it should say "menu".

Is the aria-label attribute not taken into account? How to give a name to this tip we?

<ion-buttons slot="start">
       <ion-menu-button autoHide="false"></ion-menu-button>
     </ion-buttons>

# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

Ionic Angular
`npm i @ionic/angular@5.2.0-dev.202005181316.3937101`

Ionic React
`npm i @ionic/react@5.2.0-dev.202005181316.3937101`

**Comment by terrancle** [comment]
The button is no longer labeled at all. VoiceOver says "button".
I tried to add an aria-label on the definition of my button, but it is not taken into account.
Maybe resume the operation of ion-back-button which is perfect?

**Comment by liamdebeasi** [comment]
Are you using VoiceOver on macOS or iOS?

**Comment by terrancle** [comment]
iOS latest

**Comment by liamdebeasi** [comment]
Thanks! Can you try this dev build out?

`5.2.0-dev.202005181416.0c63676`

**Comment by terrancle** [comment]
Is good !

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21324, and a fix will be available in an upcoming release of Ionic Framework.
