### ISSUE TITLE
bug: White screen is displaying after loading the application

### ISSUE THREAD

**Issue by mbc-rajeshmp** [ionic-team/ionic#21313]
# Bug Report

When we load the application in emulator after splash screen. I have wait some time still white screen is displaying.

When i tried to run using CLI command "ionic cordova emulate ios --livereload-url=http://localhost:8100", this is working perfectly.

Please help me on this.

**Ionic version:**
Config xml file details
[config.txt](https://github.com/ionic-team/ionic/files/4637974/config.txt)

**Package JSON**
Package JSON
[package.txt](https://github.com/ionic-team/ionic/files/4637976/package.txt)
 file details

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by mbc-rajeshmp** [comment]
Still facing the same issue, please help me.

**Comment by camengadisaputra** [comment]
what command you use to create your project?
did you using this command
`ionic start myApp tabs`

i have same issue when using this command, i don't know why. but when i using
`ionic start myApp `

then i select conference as my starting template. every thing work just fine, event after i remove most of component

**Comment by mbc-rajeshmp** [comment]
The new application which i created through this  "ionic start myApp tabs" is working fine in both platforms.

There is no issue in new project.

Issue arises when platform is added in existing projects.

**Comment by camengadisaputra** [comment]
try removing this line
```
    <allow-navigation href="http://localhost:8100" sessionid="d1cdac2c" />
    <allow-navigation href="http://localhost:4200" sessionid="9b211fd7" />
```
i think it try to connect to localhost

**Comment by mbc-rajeshmp** [comment]
Tried, but not working.

Sharing IOS log file details, please check.


[ioslog.pdf](https://github.com/ionic-team/ionic/files/4644734/ioslog.pdf)

**Comment by camengadisaputra** [comment]
Hi @mbc-rajeshmp, did you find the solution?
after you remove that line did you run this command
`ionic cordova prepare ios`

i try add new platform on my existing project it's working just fine.
i using default config.xml by ionic.

**Comment by mbc-rajeshmp** [comment]
I have tried this, same result.

Sharing iOS log file.


[log.pdf](https://github.com/ionic-team/ionic/files/4650970/log.pdf)

**Comment by mbc-rajeshmp** [comment]
Thank you for your kind support.

I am able to solve the issue after upgrading the version.
