### ISSUE TITLE
CSS Utilities don't apply in pages (Ionic/stencil pwa starter)

### ISSUE THREAD

**Issue by JEricaM** [ionic-team/ionic#21321]
Hi to everyone :slightly_smiling_face:
I've started a Pwa Ionic + Stencil toolkit project
https://github.com/ionic-team/ionic-pwa-toolkit

And I've the Ionic css utils in my app.css

```
/** Optional CSS utils that can be commented out */
@import "~@ionic/core/css/padding.css";
@import "~@ionic/core/css/float-elements.css";
@import "~@ionic/core/css/text-alignment.css";
@import "~@ionic/core/css/text-transformation.css";
@import "~@ionic/core/css/flex-utils.css";
@import "~@ionic/core/css/display.css";
```
If I use the css utils classes like **ion-text-justify** or **ion-hide-sm-up** inside a page of my pwa, the util don't work unless I include the optionals @imports inside my page css.

I don't understand why I have this problem because I've included all the optionals css in app.css under /global

These are my ionic and stencil versions
**"@ionic/core": "^5.0.7",
"@stencil/core": "^1.12.2",**

Thank you for the help

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
