### ISSUE TITLE
Ion-Select is hidden behind Ion Modal 

### ISSUE THREAD

**Issue by JEricaM** [ionic-team/ionic#21338]
# Bug Report

**Ionic version:**
"@ionic/core": "^5.0.7",

**Current behavior:**
If I put an **ion-select** inside an **ion-modal**, the ion-select disappear behind the modal and it's impossibile to use.

**Expected behavior:**
**ion-select** is located in front of the modal.

**Steps to reproduce:**
Create an ion-modal and add an ion-select inside the modal

**Comment by JEricaM** [comment]
@liamdebeasi so there is no solution for this problem?

**Comment by liamdebeasi** [comment]
There is likely a solution to this issue, though it has not been implemented. I am only closing this issue because it is a duplicate of another issue (https://github.com/ionic-team/ionic/issues/21181).
