### ISSUE TITLE
bug: turbocolor is deprecated

### ISSUE THREAD

**Issue by aparajita** [ionic-team/ionic#21347]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

When installing the packages at the top level of the repo, the following warning is issued:

`turbocolor@2.6.1: Turbocolor has been deprecated.  Please upgrade to Colorette 'npm i colorette'`

**Expected behavior:**

Deprecated packages should not be used.

**Steps to reproduce:**

1. Clone repo.
1. cd into repo.
1. `pnpm/npm/yarn install`

**Comment by liamdebeasi** [comment]
All set. Thanks!
