### ISSUE TITLE
bug: processNextHandler is null (React)

### ISSUE THREAD

**Issue by Data5tream** [ionic-team/ionic#21356]
# Bug Report

**Ionic version:**
[x] **5.0.7**

**Current behavior:**
When using `ev.detail.register(prio, (processNextHandler) => {})`, `processNextHandler` is null.

**Expected behavior:**
 `processNextHandler` should be a function calling the next handler

**Steps to reproduce:**

Follow the [docs](https://ionicframework.com/docs/developing/hardware-back-button#calling-multiple-handlers) to set up a handler.

**Related code:**

```
  document.addEventListener('ionBackButton', ((ev: BackButtonEvent) => {
    ev.detail.register(0, (processNextHandler: Function) => {
      processNextHandler();
    });
  }) as EventListener);
```

**Other information:**
My current workaround is:
```
  document.addEventListener('ionBackButton', ((ev: BackButtonEvent) => {
    ev.detail.register(0, () => {
      if (history.length === 1) {
        Plugins.App.exitApp();
      } else {
        history.goBack();
      }
    });
  }) as EventListener);
```

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.5.0 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.0.7

Capacitor:

   Capacitor CLI   : 2.0.1
   @capacitor/core : 2.0.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.3.0 (/usr/bin/node)
   npm    : 6.14.5
   OS     : Linux 5.6

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This feature shipped in Ionic React 5.1.0, so you will need to update to the latest version of Ionic React in order to use it.
