### ISSUE TITLE
feat: pass T in onDidDismiss to OverlayEventDetail

### ISSUE THREAD

**Issue by nickwinger** [ionic-team/ionic#21368]
# Feature Request
the onDidDismiss, e.g. for a Modal, returns `OverlayEventDetail<any>.`
The any is poor for coding, it would be better to be able to pass T.
Right now onDidDismiss is defined like so:
`"onDidDismiss": () => Promise<OverlayEventDetail<any>>;`
please change to
`"onDidDismiss": <T = any>() => Promise<OverlayEventDetail<T>>;`

so T is still optional, but if you want, you can have it typed now.

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by aivinog1** [comment]
@liamdebeasi Hello, I would like to take this. May I do this issue?

**Comment by liamdebeasi** [comment]
Yes, thank you!

Here is our contributing guide that gives you an overview of how to make the changes, test, and create a PR: https://github.com/ionic-team/ionic/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request.

Let me know if you have any questions 😊.

**Comment by nickwinger** [comment]
Nice, didn‘t know that this is possible. Next time i contribute right away :)

**Comment by nickwinger** [comment]
@aivinog1  maybe you can look out for other locations where it‘s just `any` and change to `T=any` so we have the possibility to type it.

**Comment by aivinog1** [comment]
@nickwinger Yes, I'll try to find such methods, but if there are too many such methods I think that the best solution is to split such PR to many.

In the first iteration, I can find all the possible places and describe them in the comments of this task.

**Comment by aivinog1** [comment]
I've created a #21393 and I see other places when typing could be added:
- https://github.com/ionic-team/ionic/blob/53fc8e37c89cea793d0e00246d52805166730108/core/api.txt#L908
- https://github.com/ionic-team/ionic/blob/53fc8e37c89cea793d0e00246d52805166730108/core/api.txt#L1046
- https://github.com/ionic-team/ionic/blob/53fc8e37c89cea793d0e00246d52805166730108/core/api.txt#L1080

**Comment by liamdebeasi** [comment]
Thanks for the feature request. This has been added via https://github.com/ionic-team/ionic/pull/21393 and will be available in an upcoming release of Ionic Framework.
