### ISSUE TITLE
feat: ion-item-sliding open start and end options at the same time

### ISSUE THREAD

**Issue by Enteee** [ionic-team/ionic#21361]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
Open  `ion-item-sliding` on `start` and `end` using  `open("both")`. 

**Use case**
I would like to use this to implement a counter which can be changed by either clicking on the corresponding "+" / "-" option on either end or by swiping over the counter in the corresponding direction. Please see image below.

**Describe Preferred Solution**
I would like to open a `ion-item-sliding` on both sides using some programmatic API. This would help me implement a button which can either be clicked or using a slide motion to activate.

![slider-open](https://user-images.githubusercontent.com/5493775/82730394-7e6eb700-9cff-11ea-954d-738b1ad9e16a.png)

**Describe Alternatives**
Currently I am using a button on both sides of the slider to mimic the same behavior (see screenshot). This comes with the following downsides which I have to fix with custom JavaScript:
* when sliding to one side the other side's button is not hidden
![slide-no-close](https://user-images.githubusercontent.com/5493775/82730625-6009bb00-9d01-11ea-87dd-f07026393d4a.gif)
* the slider can still stay open which results in a button a bit wider on one side (ugly)
![slider-open-ugly](https://user-images.githubusercontent.com/5493775/82730634-68fa8c80-9d01-11ea-88fc-093e68281ce4.png)

-> Maybe some very dark CSS wizardry or using internal functions could be used to achieve the same.

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please describe your use case in more detail? This particular behavior is not something that is typically found in native applications. Additionally, I think the swipe gesture may get confusing since swiping at one end typically closes the other end of options (even in native applications).

**Comment by Enteee** [comment]
@liamdebeasi added use case to the  description.

**Comment by liamdebeasi** [comment]
Thanks for the use case. I discussed this with the team, and we decided this is not a feature we are looking to add at this time. The main reason is the requested behavior is not something that appears in native iOS and MD applications. When building our components, we try to follow the iOS and MD specifications as closely as possible.

Additionally, this is something that could be done on a per-application basis. I created a CodePen with an example: https://codepen.io/liamdebeasi/pen/dyYEQpo.

If you want the `ion-label` to appear over the buttons when dragging, there is a PR that we just merged that should fix this: https://github.com/ionic-team/ionic/pull/21282. It will be available in the next release of Ionic Framework. Once that ships, you can set `overflow: visible` on the `ion-item`. (You might still need to adjust the z-index of the `ion-label` though.)

Hope this helps!

**Comment by Enteee** [comment]
OK thx @liamdebeasi

**Comment by Enteee** [comment]
Just in case somebody is interested, I have now a first draft of a component which does this.

* [code](https://github.com/Enteee/count/blob/369633ece92ffdd6eb40402e7724f156a54ed55d/src/app/components/plus-minus-counter/plus-minus-counter.component.ts)
* [live preview](https://enteee.github.io/count/counters)
