### ISSUE TITLE
bug: ModalController doesn't work offline

### ISSUE THREAD

**Issue by Bretto** [ionic-team/ionic#21379]
# Bug Report
ModalController doesn't work offline
**Ionic version:**

[x] **5.x**

**Current behavior:**

ModalController doesn't work offline
**Expected behavior:**

ModalController should work offline
**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. All Ionic components are lazy loaded to improve initial render time. If you need to account for bad network conditions, you should consider preloading the components needed by placing them inside of `ion-app` (with a `display: none`).

Example of a preloaded modal: https://codepen.io/liamdebeasi/pen/NWGxjNZ
Example of a non-preloaded modal: https://codepen.io/liamdebeasi/pen/QWjyvvw

For both, try throttling the network speed to "Slow 3g" or "Offline" in the `Network` tab in Chrome Developer Tools to see the difference.

**Comment by Bretto** [comment]
I am doing this atm: ```import('../node_modules/@ionic/core/dist/esm/ion-modal-ios.entry');```

**Comment by liamdebeasi** [comment]
^ Just bear in mind this will only load the iOS version of `ion-modal`, and the MD version of `ion-modal` will not get loaded.
