### ISSUE TITLE
bug: Header is hidden when Number keyboard shows up

### ISSUE THREAD

**Issue by iconio** [ionic-team/ionic#21388]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**
When the user selects an input that has the property 'tel' the numeric keyboard hides completely the Header and even if the user dismiss the keyboard, it won't show again.
Html tag -> `<ion-input type="tel" formControlName="cellphone"></ion-input>`

**Expected behavior:**
The expected behaviour is to display the keyboard while the header is still visible. The same way it works with the regular keyboard.

**Related code:**
`<ion-input type="tel" formControlName="cellphone"></ion-input>`

**Other information:**
I have tried using the Keyboard plugin setting different types of resizeModes and nothing.
I also noticed that if you don't have the `translucent` and `fullscreen` properties on `ion-header` and `icon-content` it works fine.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.9.2 (/Users/wd/.nvm/versions/node/v12.11.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 15 other plugins)

Utility:

   cordova-res (update available: 0.14.0) : 0.8.1
   native-run (update available: 1.0.0)   : 0.3.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.11.1 (/Users/wd/.nvm/versions/node/v12.11.1/bin/node)
   npm        : 6.14.5
   OS         : macOS Catalina
   Xcode      : Xcode 11.5 Build version 11E608c
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
