### ISSUE TITLE
bug: @ionic-native/network 'onConnect' does not work as expected

### ISSUE THREAD

**Issue by UesleyCarossi** [ionic-team/ionic#21390]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
The `onConnect` subscription is firing when the application is opened, minimized> open, when connected to the internet.

**Expected behavior:**
The expected is to occur only when connecting to the internet.

**Steps to reproduce:**
Open the application, minimize and open that the `onConnect` event will be triggered.

**Related code:**
https://github.com/UesleyCarossi/test-network

-->

```
this.network.onConnect().subscribe(() => {
      alert('onConnect');
});
```

**Other information:**
The same implementation in other environments with the same settings as `ionic info` works.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.1 (C:\Users\****\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 5 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (C:\Android\sdk)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Plugins:**

`cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"`

**Comment by liamdebeasi** [comment]
Sorry, meant to comment before I closed this issue. The Ionic Native package for this plugin is a simple wrapper around the regular Cordova plugin. Any issues are likely bugs in the Cordova plugin itself, not with the Ionic Native wrapper.
