### ISSUE TITLE
ionViewWillEnter is triggering when navigating between tabs. It doesn't trigger when navigating back from different page to tab.

### ISSUE THREAD

**Issue by vitordhers** [ionic-team/ionic#21392]
ionViewWillEnter is triggering when navigating between tabs. It doesn't trigger when navigating back from different page to tab.

It doesn't work with RC0.

_Originally posted by @mbaric1 in https://github.com/ionic-team/ionic/issues/15260#issuecomment-451170065_

I'm facing the same issue that @mbaric1 as per related above. Did any fix has been implemented? Any work around? This issue continues in Ionic 5?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please provide a reproduction of the issue using the latest version of Ionic Framework?

**Comment by vitordhers** [comment]
> Thanks for the issue. Can you please provide a reproduction of the issue using the latest version of Ionic Framework?

Dear Liam, after more search I found the work around for this issue in your last comment at https://github.com/ionic-team/ionic/issues/16834

Since I'm using Ionic 4, the work around suffices my needs. Thanks for your support.
