### ISSUE TITLE
bug: How we can control the the ion-select arrow icon color?

### ISSUE THREAD

**Issue by herobarua** [ionic-team/ionic#21395]
So far i see  the select icon color inside the shadow dom, which is not editable or manageable

also there is no define "CSS Custom Properties" for that?

![image](https://user-images.githubusercontent.com/1532317/83144903-d0f00f00-a115-11ea-9c30-eb6623c1dcd0.png)

so is there any way to control the icon color or if next version if if any variable add, it will be good for us.

waiting for reply. @liamdebeasi 

Regards

**Comment by liamdebeasi** [comment]
Thanks for the issue! We are rolling out support for CSS Shadow Parts very soon which will resolve this issue. Specifically, this should be resolved via https://github.com/ionic-team/ionic/pull/19893/files.
