### ISSUE TITLE
bug: The hardware back button still not working properly

### ISSUE THREAD

**Issue by yogskumar** [ionic-team/ionic#21398]
# Bug Report

**Ionic version:** Ionic 5

[x] **4.x**

**Current behavior:** 
After click on back button , i will back to the my previous page.

**Expected behavior:**
It's not populate the console.log("Event clicked") in DOM.
And after click on back button, no any routing will work.

**Steps to reproduce:**

Just add the code in app.component.ts

```
this.platform.backButton.subscribe(() => {
        event.preventDefault();
        event.stopPropagation();
        console.log('Back button is clicked');
        return
      })
```

**Related code:**

```
this.platform.backButton.subscribe(() => {
        event.preventDefault();
        event.stopPropagation();
        console.log('Back button is clicked');
        return
      })
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
