### ISSUE TITLE
bug: Ionic 5 Can't create modal from another modal page

### ISSUE THREAD

**Issue by rcogal** [ionic-team/ionic#21406]
**Current behavior:**
Result to an error of undefined function when calling this.modal.create

**Expected behavior:**
Should display the modal on top of the existing modal

**Steps to reproduce:**

1. Created private modal: ModaController from the parent page
2. Created private modal: ModalController from the child page to call another modal
3. It result to an error of undefined function.

```

constructor(
    private modal: ModalController
  ) { }

  ngOnInit() {
  }

  async location() {
    const modal = await this.modal.create({
      component: ParkingLocationPage,
      id: 'testset'
    });

    modal.present();
  }
```
Child Page: ParkingLocationFilterPage
```

constructor(
    private modal: ModalController
  ) { }

  ngOnInit() {
  }

  async filter() {
    const modal = await this.modal.create({
      component: ParkingLocationLegendPage,
      id: 'testset'
    });

    modal.present();
  }
```

**Other information:**
I have changed the modal property from the constructor from modal to _modal: ModalController and it works, but I am confused why since it's declared as private on the component class

**Ionic info:**

```
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.901.5
   @angular-devkit/schematics    : 9.1.5
   @angular/cli                  : 9.1.5
   @ionic/angular-toolkit        : 2.2.0
```

Screenshot: 

![image](https://user-images.githubusercontent.com/29474267/83370518-426bde00-a3f2-11ea-8e32-0d0b10ddf72f.png)[]

**Comment by elvisgraho** [comment]
In your constructor:

``` ts
this.location = this.location.bind(this);
```

The undefined error might be a result of missing **context** for your class function.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
