### ISSUE TITLE
bug: Possible to swipe behind Ion Menu

### ISSUE THREAD

**Issue by denkomanceski** [ionic-team/ionic#21411]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
When Ion-Menu is used in a page that can be swiped back, its possible to drag behind the menu. 
While if the app initially loads on the same page (no navigating happened at this point), it works perfectly fine

**Expected behavior:**
It shouldnt be able to swipe behind the menu.

**Steps to reproduce:**
https://streamable.com/z2q1bc
In the video I am first presenting the bug -> in the first half of the video is the bug where when I navigate to the page and pull the menu, you can clearly see that I can swipe back the page below it. After that I am triggering a recompiling (you have to wait few seconds) and the same page loads but it loads directly on that page (not through navigation), and the menu works fine

I am setting contentId properly

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
