### ISSUE TITLE
bug: ion-img not working as docs said

### ISSUE THREAD

**Issue by weathon** [ionic-team/ionic#21413]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

Img not showing
**Expected behavior:**

Img should be shown
**Steps to reproduce:**

The document says I should use it like this    <ion-img [src]="./assets/demo.jpg"></ion-img>
But it doesn't work, and console output the error
```
core.js:6228 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Parser Error: Unexpected token . at column 1 in [./assets/demo.jpg] in ng:///Tab1Page/template.html@33:20 ("xabay.com/photo/2014/08/12/10/08/gleise-416460_960_720.jpg" width="100%" /> -->
    <ion-img [src]="[ERROR ->]./assets/demo.jpg"></ion-img>
    <ion-card-content style="font-size:18px;font-weight:bold;">
      <"): ng:///Tab1Page/template.html@33:20
Error: Template parse errors:
Parser Error: Unexpected token . at column 1 in [./assets/demo.jpg] in ng:///Tab1Page/template.html@33:20 ("xabay.com/photo/2014/08/12/10/08/gleise-416460_960_720.jpg" width="100%" /> -->
    <ion-img [src]="[ERROR ->]./assets/demo.jpg"></ion-img>
    <ion-card-content style="font-size:18px;font-weight:bold;">
      <"): ng:///Tab1Page/template.html@33:20
    at syntaxError (compiler.js:2387)
    at htmlAstToRender3Ast (compiler.js:15299)
    at parseTemplate (compiler.js:18076)
    at CompilerFacadeImpl.compileComponent (compiler.js:18932)
    at Function.get (core.js:39830)
    at getComponentDef (core.js:2170)
    at core.js:39558
    at Array.forEach (<anonymous>)
    at setScopeOnDeclaredComponents (core.js:39548)
    at flushModuleScopingQueueAsMuchAsPossible (core.js:39130)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41632)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
```
But when I use ```src``` instead of ```[src]``` it works

**Comment by liamdebeasi** [comment]
Thanks for the issue. When you do `[src]` you are using Angular's binding system to pass in a value. When you do that, it is expecting JavaScript such as a variable or a function.

You would either need to do `src="./assets/demo.jpg"` or `[src]="'./assets/demo.jpg'"`

The documentation example uses `<ion-img [src]="item.src"></ion-img>`, but that is because it is iterating through an array of `items` where each object in the array is `item`: https://ionicframework.com/docs/api/img

**Comment by weathon** [comment]
> Thanks for the issue. When you do `[src]` you are using Angular's binding system to pass in a value. When you do that, it is expecting JavaScript such as a variable or a function.
> 
> You would either need to do `src="./assets/demo.jpg"` or `[src]="'./assets/demo.jpg'"`
> 
> The documentation example uses `<ion-img [src]="item.src"></ion-img>`, but that is because it is iterating through an array of `items` where each object in the array is `item`: https://ionicframework.com/docs/api/img

Thanks, thus, your document is wrong.
https://ionicframework.com/docs/api/img
![image](https://user-images.githubusercontent.com/41298844/83465551-eaf16080-a439-11ea-8ac5-6fd4dd378985.png)
