### ISSUE TITLE
feat: iOS Context Menus

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic#21421]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

Native iOS (13) Apps includes the 3D-Touch-Context-Menu Function (See image). Why not ionic too?

**Describe Preferred Solution**

A new element which you can add into another element (like ion-ripple-effect) and configure a list with menu items.

**Describe Alternatives**

At the moment, there is no alternative, I know.

**Additional Context**

![image](https://user-images.githubusercontent.com/36629890/83531926-dd95ae00-a4ed-11ea-9cd1-7c213e840c29.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a use case for this feature? I think this may be able to be done using `ion-popover`.

**Comment by BerkeAras** [comment]
There are many use cases like, galleries, data-lists, ...
Is it possible to make `ion-popover` compatible with 3D-Touch?

**Comment by liamdebeasi** [comment]
Apple is removing 3D touch on newer devices, so it is unlikely we will add support specifically for that in the framework. There is, however, a Cordova plugin that adds support for 3D touch: https://ionicframework.com/docs/native/three-dee-touch.

Have you tried building this contextual menu with a popover?

**Comment by cjorasch** [comment]
I have used `ion-popover` for context menus and it works pretty well.  The tricky parts are that the location is based on a source element (rather than a mouse location) and what gesture to use on mobile (since there is no right click).

**Comment by liamdebeasi** [comment]
Yep those are both great points. I put together a CodePen to show how one might accomplish this: https://codepen.io/liamdebeasi/pen/abdbzKb. There are 2 important things we did here:

1. Created a custom animation to get a bounce/scale effect.
2. Positioned the popover such that it is relative to the `ion-card`.

I did not add a custom gesture, but you could create a long press gesture using the [Ionic Gesture Utility](https://ionicframework.com/docs/utilities/gestures).

See our [Ionic Animations Documentation](https://ionicframework.com/docs/utilities/animations) for more info on how to override component animations.

I am going to close this as I think this is better implemented outside of Ionic Framework. Thanks!

**Comment by BerkeAras** [comment]
Thanks for the CodePen, I will try it!!
