### ISSUE TITLE
bug: card modal height not set using css var

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic#21449]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Currently you can resize default modals with `--width` and `--height` set.
When modal is created with `presentingElement` applied, these variables will take no effect.

**Describe Preferred Solution**

`--width` and `--height` should also be applied to modal, when presentingElement is set.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21453, and a fix will be available in an upcoming release of Ionic Framework.
