### ISSUE TITLE
Ion-content background image blank issue

### ISSUE THREAD

**Issue by HardikDG** [ionic-team/ionic#21442]
**Ionic version:**

[x] **5.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

Current behavior:
If a page has a background image set to ion-content, then while navigating to that page is flickering.

Expected behavior:
Flickering should not happen.

Steps to reproduce:
Create a page with ion-content set with background-image like below -

`ion-content { --background: url('/assets/images/sky_background.png') 0 0/100% 100% no-repeat;`

Actually I want to get an update on the issue If this issue is fixed or we still need to patch it via JS as suggested in the post:
[https://github.com/ionic-team/ionic/issues/17494](https://github.com/ionic-team/ionic/issues/17494)
As it is closed I can't get an update on that 

In my case, When I use the background in ion-content for few milliseconds it's showing white and then it shows the background images, so it may be a similar issue 

**Ionic info:** 

```
   Ionic CLI                     : 6.6.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 7.1.0
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 6 other plugins)

Utility:

   cordova-res : 0.14.0
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/hardik.dg/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.16.3 (/usr/local/bin/node)
   npm               : 6.14.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.4.1 Build version 11E503a
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. What device are you testing this on?

**Comment by HardikDG** [comment]
I have checked it in the Web(ionic serve) and iPhone X

**Comment by liamdebeasi** [comment]
Can you provide a repo with the code required to reproduce this issue?

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
