### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by Alain00** [ionic-team/ionic#21441]
I'm using capacitor with @ionic/react and after execute `npx cap add android`, open the project, and sync gradle, Android Studio gives me the following error when i try to run the app
```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.2.0] AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-43:19 to override.
```
This is a repo to reproduce
https://github.com/Alain00/IonicTestApp

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/capacitor/issues/2744. You should update your Capacitor CLI to use v2 and then remove the Android platform/re-add it.
