### ISSUE TITLE
android back button  not work when  navigation from tab to child page in another tab 

### ISSUE THREAD

**Issue by 12ahmed12** [ionic-team/ionic#21454]
**Ionic version:**
[x] 4.x

**I'm submitting** 
Bug report 

**Bug description :**
i have app with side menu and tabs 
and i have first tab opens  'home'  inside this page i have buttons  that open a pages  from other tabs  so when i click one of this buttons  the tabs selection changed to the other tab that having this page  but when i click android hardware back button  **nothing happens**

i though  to make routes for this pages as child to 'home' tab  but i did not find it efficient !? 
 and i will need to set the child of this child also to be child of 'home' too which is not right i think ?

how can i handle this nested structure 

**Current behavior:**
 when i navigate from 'home' to any page  which is child of another tab and click back buttons 
 it do not navigate back to anything .

**Expected behavior:**
it expected  to navigate back to the last page user  was in  which is 'home' page 
for more description it expected when click back button to navigate from tab for example 'order'
to tab 'home'

**Steps to reproduce:**

**Related code:**

const routes: Routes = [
  {
    path: '',
    component: TabsPage,
    children: [
      {
        path: 'home',
        children: [
          {
            path: '',
            loadChildren: '../dashboard/home.module#HomePageModule'
          },
          {
            path: 'product-details',
            loadChildren: '../promotions/details/promotion-details.module#PromotionDetailsPageModule'
          },
        ]
      },
      {
        path: 'new-order',
        children: [
          {
            path: '',
            loadChildren: '../order/order-now/order-now.module#OrderNowPageModule'
          },
          {
            path: 'cash',
            loadChildren: '../order/cash-order/cash-order.module#CashOrderModule'
          },
          {
            path: 'cash-products',
            loadChildren: '../order/cash-products/cash-products.module#CashProductsModule'
          },
        ]
      },
      {
        path: 'cart',
        children: [
          {
            path: '',
            loadChildren: '../cart/cart-preview/cart.module#CartPageModule'
          },
          {
            path: 'insurance-details',
            loadChildren: '../cart/claim-details/claim-details.module#ClaimDetailsModule'
          },
          {
            path: 'details',
            loadChildren: '../product-details/product-details.module#ProductDetailsPageModule'
          }
        ],
      },
    ]
  },
  // /app/ redirect
  {
    path: '',
    redirectTo: 'app/home',
    pathMatch: 'full'
  },
  {
    path: '*',
    redirectTo: 'app/home',
    pathMatch: 'full'
  }
];

**Steps to reproduce:**
from the above code of tabs routing 
 navigate from 'app/home' to 'app/new-order/cash'
it while change selected tab from 'home'  to 'order'
then click hardware back buttons > nothing happens .

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
