### ISSUE TITLE
bug: Autofill is not working properly and autocomplete only accepts on/off so no work arounds are currently available (that I have found)

### ISSUE THREAD

**Issue by BrianBenninger** [ionic-team/ionic#21466]
# Bug Report

**Ionic version:**
   Ionic CLI       : 5.4.16
   Ionic Framework : @ionic/react 5.1.1

**Current behavior:**
autofill fills the ion inputs but does so in a way that will not validate and the values of the inputs come back as blank

**Expected behavior:**
autofill should fill the values of the input boxes properly

**Steps to reproduce:**
Currently I am using Formik and React, but this seems to happen regardless of project type. Create an IonInput for username and password and observe as Chrome and other browsers fill the box but do not activate proper validation (or in this case, activate validation but against a value of "" rather than the autofill value)

![Screen Shot 2020-06-09 at 1 52 40 PM](https://user-images.githubusercontent.com/29063944/84182503-8006e180-aa58-11ea-9e9d-1ffe2fbc9888.png)

**Related code:**
```
<Field name="email">
  {({ field, form }: FieldProps) =>
    <IonItem>
      <IonInput ref={emailRef} value={field.value} onIonChange={field.onChange} onIonBlur={field.onBlur} name={field.name} type="email" spellCheck={false} autocapitalize="off" placeholder="Email" />
    </IonItem>
  }
</Field>
```

**Other information:**
I have tried various work around to this but have not managed to get anything to work properly. One work around that could be fine is if the ion input simply accepted more strings than on and off for autocomplete. For instance I have read if you use autocomplete="newpassword" then it will essentially turn off the autofill for that box. At this point I would rather not have autofill than have it working as brokenly as it is not.

I have also tried just using autocomplete="off" but this seems to be ignored by most if not all browsers.

I've also tried polling the input boxes for values since I have read that autofill does not actually fire a change event. But since the inputs aren't actually receiving a value even polling their values on a timeout is not allowing me to properly activate validation on the autofilled boxes.

I have also tried just not disabling the login button and allowing the validation to "manually" be fired by clicking the login button. This however is still trying to fire validation against the empty value string of the input.

**Ionic info:**
```
Ionic:

   Ionic CLI       : 5.4.16
   Ionic Framework : @ionic/react 5.1.1

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res (update available: 0.14.0) : 0.9.0
   native-run                             : not installed

System:

   NodeJS : v12.13.0 (/Users/mbp2126chem/.nvm/versions/node/v12.13.0/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
