### ISSUE TITLE
feat: Make possible to disable lazy load

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic#21468]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**
It should be possible to disable Lazy Load in Ionic. That should be available for core users too.

**Describe Alternatives**

There is no alternative.

**Comment by liamdebeasi** [comment]
Thanks for the issue. All Ionic components are lazy loaded by default, and we do not currently have plans to disable this.

If you want to pre-load components, you can do so by placing the components in your app with `display: none`. Here is an example: 

Example of a preloaded toast: https://codepen.io/liamdebeasi/pen/pojZqWX
Example of a non-preloaded toast: https://codepen.io/liamdebeasi/pen/ZEbjVXE

In each example, try loading the CodePen and throttling the Network speed in Chrome DevTools. Then, click the "Show Toast" button. In the non-preloaded example, the toast should be slow to load, but in the pre-loaded example the toast should displayed almost instantly.

Additionally, you can also cache Ionic's JS files using a service worker which will help speed up loading time. If you are using Angular, there is a guide on how to get started with this: https://angular.io/guide/service-worker-intro.

**Comment by BerkeAras** [comment]
But how can I do this with whole pages? If I click on a button and the button should open a page (A static page) it takes a few milliseconds, but It feels so slow.

**Comment by liamdebeasi** [comment]
Are you using Ionic with a framework like Angular?

**Comment by BerkeAras** [comment]
No, I dont use any frameworks

**Comment by liamdebeasi** [comment]
In that case, you can use the same approach that I described before. If you have a `app-login` page, you can place the `<app-login>` component in your app before it is needed. Please note that this will likely increase the initial loading time.

I will caution that if the entire app is slow, this is usually indicative of a larger problem. For example, the device may be slow in general or the app itself may be slow.

**Comment by BerkeAras** [comment]
The code can't be slow, it is written very clean and I've checked it many times. The device is an iPhone 7 (the app is slow) and an iPhone 11 (app is slow too). The main problem is that, it takes long to open pages.

**Comment by liamdebeasi** [comment]
I would recommend trying to identify what is slow using Chrome/Safari Dev Tools. You can take performance tests that will show you a breakdown of what the source of the slowdown is.

**Comment by BerkeAras** [comment]
@liamdebeasi 
I tried that and it took 1.2 seconds to load a very small page (only with text).
Here you can see it:
![Bildschirmfoto 2020-06-09 um 22 09 34](https://user-images.githubusercontent.com/36629890/84195109-51abf500-aa9e-11ea-8d7a-294d03d11f2d.png)

**Comment by liamdebeasi** [comment]
Unfortunately, I am unable to debug your app for you. If you are able to point to something specific in your app that indicates this is bug in Ionic Framework, feel free to open a new issue with a code reproduction, and I can take a look.

Also 1.2 seconds is the total time for the selected segment of your Chrome timeline test. Chrome was idle for 752ms of the 1199ms, which means the browser was really only working for less then 0.5 seconds.

**Comment by BerkeAras** [comment]
How can I point to something specific? Can I do that sith DevTools?

**Comment by liamdebeasi** [comment]
Yes, Chrome should give you a list of all code that was called. See https://developers.google.com/web/tools/chrome-devtools/ for some tutorials on how to analyze runtime performance.
