### ISSUE TITLE
feat: Make IonSelect preselected

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic#21467]
# Feature Request

**Ionic version:**

[x] **4.x**
[x] **5.x**

**Describe the Feature Request**

IonSelectOption should have the attribute 'selected'. Otherwise there is (As far as I know) no option to make it preselected.

**Describe Preferred Solution**

IonSelectOption should have the attribute 'selected'.

**Comment by liamdebeasi** [comment]
Thanks for the issue. To accomplish this, you need to set the value of the `ion-select` to equal the value of the `ion-select-option` you want selected.

Example:

```
<ion-item>
  <ion-label>Fruit</ion-label>
  <ion-select placeholder="Select One" value="a">
    <ion-select-option value="a">Apples</ion-select-option>
    <ion-select-option value="o">Oranges</ion-select-option>
    <ion-select-option value="b">Bananas</ion-select-option>
  </ion-select>
</ion-item>
```

For more information, please see the [ion-selectDocs](https://ionicframework.com/docs/api/select)

**Comment by BerkeAras** [comment]
Thanks! I did not know this, I'm sorry :(
