### ISSUE TITLE
bug: Sliders getting stuck when manipulating data inside on it.

### ISSUE THREAD

**Issue by nazrulcse** [ionic-team/ionic#21480]
# Bug Report

**Ionic version:**

[x] **5.1.1**

**Current behavior:**

Sliders getting stuck during swipe left/right when manipulating huge amount of real time data inside slide container.  
**Expected behavior:**

It should smoothly swipe left/right
**Steps to reproduce:**

Simple sliders with huge amount to real time data manipulation and try to swipe left/right 
**Related code:**
```
<ion-content>
  <ion-slides *ngIf="didInit" class="main-app-slider" [options]="slideOpts" #tabSlider>
    <ion-slide>
      <app-home></app-home>
    </ion-slide>
    <ion-slide>
      <app-chat-rooms></app-chat-rooms>
    </ion-slide>
    <ion-slide *ngFor="let room of chat_rooms">
      <app-chat-room [room_id]="room.id"></app-chat-room>
    </ion-slide>
  </ion-slides>
</ion-content>
```

**Other information:**

**Ionic info:**

This is a chatting application personal and group chatting.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
