### ISSUE TITLE
Ion Refresher not hidding in IOS 

### ISSUE THREAD

**Issue by pedritobnk90** [ionic-team/ionic#21491]
**Describe the bug**
The refresher is not hiding in IOS until I tap anywhere on the screen.

**To Reproduce**
I run the refresher and when I finish loading the content I do 'event.taget.complete'.

**Expected behavior**
When the content is loaded, the refresher should hide. 

**Versions**
   Ionic CLI: 6.2.0 
   Ionic Framework: @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.900.5
   @angular-devkit/schematics: 8.1.3
   @angular/cli: 9.0.5
   @ionic/angular-toolkit: 2.0.0
   Cordova CLI: 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms: ios 5.1.1
   Iphone Xr  IOS 13.3.1

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
