### ISSUE TITLE
IonSlides doesn't work after app inactivity

### ISSUE THREAD

**Issue by pedritobnk90** [ionic-team/ionic#21492]
**Describe the bug**
<ion-slides> is not working after app inactivity.

**To Reproduce**
When I refresh the page the slides working perfectly, but if I leave the application inactive the <ion-slides> stop working.

My codes are:
_tab2.page.html_

```
<ion-slides class="mainSlide" #mainSlide dir="rtl">
     <ion-slide>
     </ion-slide>
     <ion-slide>
     </ion-slide>
</ion-slides>

<ion-col>
     <ion-button (click)="openCreateInstantPost()">
           <ion-icon name="add-circle"></ion-icon>
                instant
      </ion-button>
</ion-col>
<ion-col>
      <ion-button (click)="openCompetition()">
            <ion-icon name="help-circle"></ion-icon>
                  competition
       </ion-button>
</ion-col>
```
_tab2.page.ts_

```
@ViewChild('mainSlide', { static: true }) protected mainSlide: IonSlides;
...
....
async openCreateInstantPost(): Promise<void> {
    await this.mainSlide.slidePrev();
}

async openCompetition(): Promise<void> {
    await this.mainSlide.slideNext();
}
```

Versions
Ionic CLI: 6.2.0
Ionic Framework: @ionic/angular 5.0.4
@angular-devkit/build-angular : 0.900.5
@angular-devkit/schematics: 8.1.3
@angular/cli: 9.0.5
@ionic/angular-toolkit: 2.0.0
Cordova CLI: 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms: ios 5.1.1

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
