### ISSUE TITLE
ion-select using interface = "action-sheet" does not work mode = "Android" on IOS

### ISSUE THREAD

**Issue by pauloanalista** [ionic-team/ionic#21493]
** Describe the bug **
Ion-select component when using interface = "action-sheet" and adding support mode = "md" and running on IOS, Action-Sheet opens with the look of Ios ignoring Mode="Android".

**Reproduce**
<ion-item>
        <ion-label position = "stacked"> Periodicity </ion-label>
        <ion-select formControlName = "periodicity scheduler" placeholder = "Select the periodicity" mode = "md" interface = "action-sheet" [value] = "periodicity"
          cancel-text = "Exit" [(ngModel)] = "periodicity">
          <ion-select-option value = 0> Weekly </ion-select-option>
          <ion-select-option value = 1> Every hour </ion-select-option>
          <ion-select-option value = 2> Every minute </ion-select-option>
          <ion-select-option value = 3> Every second </ion-select-option>
          <ion-select-option value = 4> Once a month </ion-select-option>
        </ion-select>
      </ion-item>

**Expected behavior**
Action-Sheet should open with Android look
** Screenshots **
If applicable, add screenshots to help explain your issue.

** Browser and operating system (fill in the following information) **
- SO: IOS
- Browser: Chrome
- Version: 80

** Additional context **
I hope to help improve the product by reporting this bug

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
