### ISSUE TITLE
bug: ion-back-button doesn't work

### ISSUE THREAD

**Issue by pairmix** [ionic-team/ionic#21496]
# Bug Report

**Ionic version:**
[x] **5.1**

**Current behavior:**
ion-back-button is not visible and not clickable

**Expected behavior:**
ion-back-button should be visible and clickable

Back button is working when i go to page with 
````
<ion-button primary [routerLink]="['/login']" routerDirection="forward">{{'Login' | translate}}</ion-button>
````
But it isn't working (invisible and not clickable) 
when i go with @angular/router:
````
await this.router.navigateByUrl('/portail/fiche/' + candidat._id)

````
or with @ionic/angular: 
````
await this.navCtrl.navigateForward('/portail/fiche/' + candidat._id)
````

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
