### ISSUE TITLE
bug: @ionic/angular 5.2.0 - NullInjectorError: No provider for NgControl

### ISSUE THREAD

**Issue by avidan-chen** [ionic-team/ionic#21497]
# Bug Report

**Ionic version:**

[x] **5.2.0**

**Current behavior:**

After updating to @ionic/angular 5.2.0, I'm getting an error while loading the main screen of my app:
NullInjectorError: No provider for NgControl!

The cause seem to be from this line which was added in 5.2.0:
https://github.com/ionic-team/ionic/pull/21429/files#diff-82537c2dfeacfd22b040b201d025fb1bR65

I am importing Angular's FormsModuls in all of my modules using forms. I am not using ReactiveForms, although I did try to add ReactiveFormsModule to the imports sections in the relevant module, but I'm still getting the same error.

**Expected behavior:**

App will load without an error.

**Related code:**
https://github.com/ionic-team/ionic/pull/21429/files#diff-82537c2dfeacfd22b040b201d025fb1bR65

**Other information:**
Using latest Angular 9.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.0
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.3 (cordova-lib@9.0.2)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.14.0
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/Avidan/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.15.0 (/usr/local/bin/node)
   npm               : 6.14.5
   OS                : macOS Catalina
   Xcode             : Xcode 11.5 Build version 11E608c

**Comment by avidan-chen** [comment]
Duplicate of https://github.com/ionic-team/ionic/issues/21489

Closing this as the solution in my case was to change [value] to [ngModel].

**Comment by kensodemann** [comment]
5.2.1 was just released with a fix for this.

**Comment by avidan-chen** [comment]
Thanks!
