### ISSUE TITLE
bug: Components like date time etc seem to be not easily accessible for aria

### ISSUE THREAD

**Issue by saivishnutammineni** [ionic-team/ionic#21501]
# Bug Report
[x] **4.x**

**Current behavior:**
Components like date time pickers etc seem to have a button inside their template. When using screen reader the screen reader reads these components as buttons

**Expected behavior:**
the expected behavior is to have the screen reader read out something similar to html elements like input:date

**Steps to reproduce:**
https://ionicframework.com/docs/api/datetime 

the demo shown in the above link . when a screen reader is used while tabbing to the date picker the screen reader reads it out as button. I don't think this will be helpful to the user using assistive tech.

**Other information:**
angular 8

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify the issue you are seeing?

**Comment by saivishnutammineni** [comment]
HI, thanks for the quick response and sorry for the delay in reply.

We are working on a project using ionic 4 and angular 8. we want to make the app accessible.
But some ionic components don't seem to be accesible.

1. DateTime Picker

- navigate to https://ionicframework.com/docs/api/datetime. **enable screen reader**(i used nvd)
- focus on the first form control in the demo
- use tab navigation to navigate between form controls
- we hear proper labels for the input fields at the top from screen reader
- but when we reach the date pickers we hear **BUTTON** from screen reader
- this i think is not what a user using assistive technology should be hearing
- is there a way to make this more accesible. (am i missing something. stackoverflow question and 
slack questions had no answers

2. Ion Slides
- tried passing accessibility options to swiper via options to ion slides. Didn't work. sorry couldn't provide a repro due to laptop constraints
- i digged further into the source code of ion slides. found that ionic uses swiper via the bundle in the swiper folder. there was no accessibility code in the swiper bundle. (am i wrong? found all other options but not a11y)

**Comment by liamdebeasi** [comment]
Thanks for the follow up. What are you expecting to hear from the screen reader regarding the datetime component? Each item is a button that you can click, so I think it makes sense that the screen reader is saying "button".

Can you provide some steps to reproduce for the ion-slides issue?
