### ISSUE TITLE
bug: Ion-segment stopped working since update

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/ionic#21510]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
Anywhere i use the ion-segment component in my app now raises this error:

```
[NgControl -> NgControl -> NgControl -> NgControl -> NgControl]: 
  NullInjectorError: No provider for NgControl!
```

I updated using npm today, which also pulled through the most recent version of Angular, so I presume that has caused it as I use the component all through out my app and have never had issue. The snippet below is a how I have used the component:

```
          <ion-segment (ionChange)="segmentChanged($event.detail.value)" [value]="view">
            <ion-segment-button value="rewards">
              <ion-label>Rewards</ion-label>
            </ion-segment-button>
            <ion-segment-button value="venues">
              <ion-label>Venues</ion-label>
            </ion-segment-button>
            <ion-segment-button value="history">
              <ion-label>History</ion-label>
            </ion-segment-button>
          </ion-segment>
```

**Expected behavior:**
From navigating to a page with the component on, it should not break the app.

**Steps to reproduce:**

1. Add the ion-segment anywhere in an ionic project

**Ionic info:**

Ionic:

   Ionic CLI                     : 6.10.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.0
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.0.0 (/usr/local/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has already been fixed -- please update to Ionic Framework v5.2.1.
