### ISSUE TITLE
bug: actionSheet catch return function from 5.2.1, no problem with 5.1.1

### ISSUE THREAD

**Issue by terrancle** [ionic-team/ionic#21524]
Hello,

I have a problem since version 5.2.1, no problem with version 5.1.1.
I think fix # 21259 is a bug.
In an action sheet (no problem elsewhere), a button that executes a function returns to Catch, while the function executes correctly.
For example, I have an NFC function that executes by clicking a button from an actionSheet. The action works correctly, but the user got an error message as if the function had had a problem (catch).
If I test the exact same code with Ionic 5.1.1, no problem.

let message = this.ndef.textRecord(item.nfc, 'fr');
      this.nfc.write([message]).then((test: any) => {}).catch((e: any) => {
        console.log(e)
        this.ExplicationTagNfc(item);
      });

**Comment by terrancle** [comment]
Hello,

I continued to do long hours of testing.

The problem only occurs on iOS with @Ionic 5.2.1, no problem on Android.

When a function is executed via a button in an actionSheet, the function is executed twice.

This is why the return of the initial function works, but why the user falls into the Catch, because of the double execution.

You can make a clone of this test project to see it:
https://gitlab.com/easy-web/TestActionSheet
![Capture](https://user-images.githubusercontent.com/19683797/84697861-279b7c80-af4f-11ea-81b0-bbee3850f0cb.PNG)
![conf-mac](https://user-images.githubusercontent.com/19683797/84697865-28341300-af4f-11ea-9e60-bfef7c9d39e8.PNG)

**Comment by terrancle** [comment]
UP, for change triage label

**Comment by liamdebeasi** [comment]
Thanks for the follow up. This issue was resolved in Ionic Framework v5.2.2. Please upgrade to that version to receive this bug fix.
