### ISSUE TITLE
Ionic slides runtime rtl direction swiping issue on language change.

### ISSUE THREAD

**Issue by Husnain-Asharf** [ionic-team/ionic#21528]
**Ionic version:**
[ x] **5.x**

**I'm submitting a ...** 

[x ] bug report
[ ] feature request

**Current behavior:**
I have 4 tabs view. In first, second and third tab i am using ionic slides and 4th tab  contains setting stuff. When i change app language from English to Arabic in 4th tab and came back to first tab i cannot swipe slides in rtl direction untill i reload. I also checked on my document dir="rtl" coming.

**Expected behavior:**
 It should enable slides direction to rtl on runtime if document dir="rtl".

**Steps to reproduce:**
Create a tab project,create slides in one tab,make language switcher and change language from English to Arabic. On language change set document direction to rtl and see cannot swipe in rtl direction.

**Related code:**
![image](https://user-images.githubusercontent.com/40805304/84645975-1714e300-af0a-11ea-8a77-4a72eefc0acc.png)
 Above code on language selection

![image](https://user-images.githubusercontent.com/40805304/84646180-5f340580-af0a-11ea-83d6-32117bf3b7f1.png)
 Slides layout

insert short code snippets here

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 6.10.0 (C:\Users\sohai\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.2.1
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 24 other plugins)

Utility:

   cordova-res (update available: 0.15.0) : 0.8.1
   native-run (update available: 1.0.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (C:\sdk-tools-windows-4333796)
   NodeJS            : v12.14.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.13.4
   OS                : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
