### ISSUE TITLE
bug: wrong ion-segment-button class if no segement is checked initially 

### ISSUE THREAD

**Issue by NisStrom** [ionic-team/ionic#21546]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
If an ion-segment initially has no checked segment button, once you select the first segment it does not set the _segment-button-after-checked_ class to the following segment. This is due to the fact that in segment.tsx the checkButton method requires a previous element.

**Expected behavior:**
The ion-segment-button after the checked button should have the CSS class _segment-button-after-checked_.

**Steps to reproduce:**
1. Select second segment -> third segment should have class _segment-button-after-checked_

**Related code:**
https://stackblitz.com/edit/ionic-v4-angular-tabs-7kzv4u

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21547, and a fix will be available in an upcoming release of Ionic Framework.
