### ISSUE TITLE
bug: Ion-slides does not allow the user to navigate using keyboard only

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic#21554]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Ion-slides even though the pager is used, does not allow to navigate using keyboard alone. Even though there is an `options` to be given using the https://idangerous.us/swiper/api which has documentation about accessibility:

https://swiperjs.com/api/#a11y

Those options do not work with ionic-slides.

Refer to item 5 in the document shared in Slack for further details.
https://ionicteam.slack.com/archives/C7CGXAVTL/p1592319616186200

**Comment by NikolaPeevski** [comment]
@kensodemann I can't access the slack discussion, but @liamdebeasi has talked about this here before: https://github.com/ionic-team/ionic/issues/17662

**Comment by liamdebeasi** [comment]
Resolved via https://github.com/ionic-team/ionic/pull/21608.

**Comment by kensodemann** [comment]
I have received verification from the user that this is working correctly for them now.
