### ISSUE TITLE
bug: isPlatform not found

### ISSUE THREAD

**Issue by weathon** [ionic-team/ionic#21565]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

Base on the document https://ionicframework.com/docs/angular/config, the code 
`import { isPlatform } from '@ionic/angular';` should works. But now it gave me an error.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you on Ionic Framework 5.2.0? That feature was added in that version: https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md

**Comment by weathon** [comment]
I am using 6.9.3
```bash
user@vultr:~/NewTopicIM/myapp$ ionic --version
6.9.3```

**Comment by weathon** [comment]
Is that a different type of version?

**Comment by weathon** [comment]
And I uninstall ionic and install it again. Then I delete my node_models and use `npm install`, but t still doesn't work

**Comment by liamdebeasi** [comment]
That is the version of your Ionic CLI. What is the output of running `ionic info` in the project directory?

**Comment by weathon** [comment]
```
Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.1.1
   @capacitor/core : 2.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.21.0 (/usr/bin/node)
   npm    : 6.14.5
   OS     : Linux 4.19
```

How I can update my ionic

**Comment by liamdebeasi** [comment]
You will need to upgrade to Ionic Framework v5.2.0 or newer to use this feature:

```
npm install @ionic/angular@latest
```
