### ISSUE TITLE
feat: expose --placeholder-font-size for ion-input

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic#21574]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

--placeholder-font-size will apply font-size to placeholder only.

**Describe Preferred Solution**

 --placeholder-font-size

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is already possible in Ionic Framework. `ion-input` is not a shadow component, so you can target the placeholder directly in your CSS: https://css-tricks.com/almanac/selectors/p/placeholder/

**Comment by indraraj26** [comment]
Thank you let me try that 👍
