### ISSUE TITLE
ion-select-option -> ion-select interface="action-sheet"

### ISSUE THREAD

**Issue by webteambel** [ionic-team/ionic#21578]
**Description:**
disabled is working with default/popover interface , when you change it to action-sheet  it doesn't work , in fact the button is clickable but when you click it, ion-select choose another option.

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 6.10.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.1
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 11 other plugins)

Utility:

   cordova-res (update available: 0.15.0) : 0.9.0
   native-run (update available: 1.0.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/teamwebmobile/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.16.3 (/usr/local/bin/node)
   npm               : 6.14.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.5 Build version 11E608c
```

**Comment by webteambel** [comment]
Hello @liamdebeasi ,
Here is a bug production https://github.com/webteambel/ionic-action-sheet-select : [disbaled works fine with default and popover]

**Comment by NikolaPeevski** [comment]
@webteambel If you look into the documentation regarding action sheets you can't have disabled buttons there, so that's why the side-effects occur.

**Comment by webteambel** [comment]
@NikolaPeevski  : 
yes I see,  but at the doc of ion-select-option https://ionicframework.com/docs/api/select-option it says if you add disabled true  the user cannot interact with the select option , they didn't specify the interface of ion-select. That's a little bit confusing :/

**Comment by liamdebeasi** [comment]
Thanks! You are correct, this is confusing. `ion-action-sheet` **does not** allow for disabled buttons, so I will update the documentation to clarify this.

**Comment by webteambel** [comment]
@liamdebeasi I know this is not the good thread to speak about , but i would know if is this feature will be available soon https://github.com/ionic-team/ionic/issues/18067
thanks ^_^

**Comment by liamdebeasi** [comment]
We do have plans for something like this  👀 . It will likely require a breaking change, so we will release it with a major version update.

**Comment by NikolaPeevski** [comment]
You can Dom inject a disabled state to the buttons but it looks a bit out of place.

**Comment by webteambel** [comment]
@NikolaPeevski Thanks for the help , right now I think I will use the default interface ;)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21584.
