### ISSUE TITLE
bug: Animation flicker when using card-style modal

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic#21572]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When dismissing a card-style modal, the bottom border of the header on the underlying page has a "flicker" to it. This is most noticeable when the header has an "ion-no-border" class.

In the normal case, perhaps the flicker itself is a desired effect, I don't know, but in the "ion-no-border" case it just looks weird because there is no actual border there normally.

**Expected behavior:**
No border flicker, at least if the header has the "ion-no-border" class.

**Steps to reproduce:**

1. git clone git@github.com:kensodemann/test-bed.git
1. cd test-bed
1. npm i
1. npm run build
1. npx cap sync
1. npx cap open ios
1. Now run on device or sim
1. Press the "Show Modal" button
1. Press the "Close Modal" button
1. Note the weird little flicker of a border where no border usually is

This doesn't look so out of place in the case where you are not using the "ion-no-border" class.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.10.1 (/Users/kensodemann/.nvm/versions/node/v12.17.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.2.2

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res (update available: 0.15.0) : 0.14.0
   native-run (update available: 1.0.0)   : 0.3.0

System:

   NodeJS : v12.17.0 (/Users/kensodemann/.nvm/versions/node/v12.17.0/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Closing.

This is a browser rendering glitch, not a framework bug. It appears to have something to do with sub-pixel rendering (rendering non-integer pixel values), and is tied to scaling down the main content. The "line" that appears is actually a gap between the `ion-header` and `ion-content` elements that exposes the body. I was able to reproduce this in Chrome and Safari running on iOS mode.
