### ISSUE TITLE
bug: Infinite scroll only works if it's a direct child of ion-content

### ISSUE THREAD

**Issue by Gilbert1391** [ionic-team/ionic#21589]
I found another issue reporting this bug already, but it was closed. I'd like to know if there is any work around for this problem and if the there are any updates. 

# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
Infinite scroll only works if it's a direct child (and the list) of the ion-content element

**Expected behavior:**
It should work inside any element

**Steps to reproduce:**

someView.html:

```
<ion-content>
<ion-grid>
  <ion-row>
    <ion-col>
      <ion-card class="fixed-height">
       <ion-card-header></ion-card-header>
       <ion-card-content>
         <ion-list> ... </ion-list>
         <ion-infinite-scroll threshold="100px" (ionInfinite)="loadData($event)">
           <ion-infinite-scroll-content loadingText="Loading..."> </ion-infinite-scroll-content>
         </ion-infinite-scroll>
      </ion-card-content>
    </ion-card>
    </ion-col>
  </ion-row>
 </ion-grid>
</ion-content>
```

someView.component.ts

```
loadData(event) {
    console.log('loading more');
    event.target.complete();
  }
```
**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.7 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 (update available: 1.0.0)

System:

   NodeJS : v12.16.3 (/Users/Garh/.nvm/versions/node/v12.16.3/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina
```

**Comment by indraraj26** [comment]
what is the issue? 
if you are having two css tabs (not ion-tabs) that has one ion-content you can place infinitescroll as child element of ion-content. based on tap on css tab you can reset infinitescroll and call appropriate apis. Infinitescroll designed that way you will have to put as child element of ion-content

**Comment by Gilbert1391** [comment]
> what is the issue?
> if you are having two css tabs (not ion-tabs) that has one ion-content you can place infinitescroll as child element of ion-content. based on tap on css tab you can reset infinitescroll and call appropriate apis. Infinitescroll designed that way you will have to put as an child element of ion-content

The issue is that you cannot use infinite scroll inside any element that isn't ion content

**Comment by indraraj26** [comment]
> Infinitescroll designed that way you will have to put as an child element of ion-content

This isn't bug you can request for feature.

**Comment by Gilbert1391** [comment]
> > Infinitescroll designed that way you will have to put as an child element of ion-content
> 
> This isn't bug you can request for feature.

And how am I supposed to use it in the example I provided? According to Ionic docs, I can only have one ion content per page...

**Comment by indraraj26** [comment]
> if you are having two css tabs (not ion-tabs) that has one ion-content you can place infinitescroll as child element of ion-content. based on tap on css tab you can reset infinitescroll and call appropriate apis. Infinitescroll designed that way you will have to put as an child element of ion-content

**Comment by Gilbert1391** [comment]
> > if you are having two css tabs (not ion-tabs) that has one ion-content you can place infinitescroll as a child element of ion-content. based on tap on CSS tab you can reset infinitescroll and call appropriate apis. Infinitescroll designed that way you will have to put as a child element of ion-content

Would you mind to share the code? I'm not sure I fully understand what you mean.

**Comment by KevinKelchen** [comment]
We ran into the one `ion-content` in a single view limitation with `ion-virtual-scroll` because we wanted to have a virtual scroll that wasn't a direct child to the Page's singular `ion-content`. We began using the Angular CDK's virtual scroll control in those instances (https://material.angular.io/cdk/scrolling/overview).

I remember watching an Ionic video chat from around a year or so ago where they talked about some issues with their homegrown virtual scroll and that they were planning to recommend framework-specific implementations from the respective ecosystems (such as the CDK virtual scroll in the case of Angular). Not sure what the position is today.

Using the Angular CDK's virtual scroll might not be the best solution for you, but thought I'd pass along the info in case it's helpful. 🙂

**Comment by indraraj26** [comment]
> > > if you are having two css tabs (not ion-tabs) that has one ion-content you can place infinitescroll as a child element of ion-content. based on tap on CSS tab you can reset infinitescroll and call appropriate apis. Infinitescroll designed that way you will have to put as a child element of ion-content
> 
> Would you mind to share the code? I'm not sure I fully understand what you mean.

Could you provide reproduction i would be happy to apply some conditional logic there

**Comment by elvisgraho** [comment]
Try to put it inside <ion-list> tag.
Will it work?

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
