### ISSUE TITLE
bug: In new Ionic Angular version 5.2.1, in alert and action-sheet event any function call two times!! 

### ISSUE THREAD

**Issue by herobarua** [ionic-team/ionic#21588]
Here is my ionic info and screenshot for better clarification of issues
Ionic:

   Ionic CLI                     : 6.10.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.1
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.0.0) : 0.2.8

System:

   NodeJS : v12.18.0 (/usr/local/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina

<img width="877" alt="step_code" src="https://user-images.githubusercontent.com/1532317/85202715-3658a980-b32a-11ea-9a68-64825fac307b.png">
<img width="900" alt="step2" src="https://user-images.githubusercontent.com/1532317/85202733-58eac280-b32a-11ea-8973-644b8e10ef1a.png">

@liamdebeasi  Actually i am facing issue after update 5.1.1 to 5.2.1. can you help me solve the issue. 

Regards.

**Comment by conde2** [comment]
Just update to 5.2.2

**Comment by Spinnenzunge** [comment]
See https://github.com/ionic-team/ionic/issues/21503 this bug is only in chrome with platform set to iOS via dev tools it seems like and was fixed in 5.2.2.

**Comment by liamdebeasi** [comment]
Thanks! As other people have suggested, update to Ionic Framework 5.2.2. This bug was fixed in that version.
