### ISSUE TITLE
bug: app crash when using social sharing Facebook in ionic 5

### ISSUE THREAD

**Issue by amarkumar78** [ionic-team/ionic#21586]
# Bug Report
when I using the social sharing Facebook, My app is crash I don't know why it's happening , I have also tried social sharing plugin in the blank project using ionic 5, Please help me it's argent. thanks

**Ionic version:**
@ionic/angular 5.2.2

**Other information:**
Ionic:

   Ionic CLI                     : 6.10.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.901.9
   @angular-devkit/schematics    : 9.1.9
   @angular/cli                  : 9.1.9
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 5 other plugins)

Utility:

   cordova-res (update available: 0.15.0) : 0.9.0
   native-run (update available: 1.0.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/home/indrakumar/Android/Sdk)
   NodeJS            : v10.19.0 (/usr/bin/node)
   npm               : 6.14.5
   OS                : Linux 5.4

**Comment by amarkumar78** [comment]
I have also try blank project many times but it's not working
anyone please help me

**Comment by indraraj26** [comment]
Can you share repo ?
