### ISSUE TITLE
bug: Input Field onIonChange Event Triggers Button onClick Event

### ISSUE THREAD

**Issue by lttitus** [ionic-team/ionic#21583]
#Bug Report

**Ionic version:**
[x] 5.1.1

**Current behavior:**
onIonChange event on Text Input seems to also trigger onClick event on all buttons on the same page. Within a simple login page, you will be able to see this in action. I am unsure if this is due to the hooks that I am using, "setUser" and "setPass" though. In the code below, you can see that I have 3 buttons, the Login, 'submit' button, a regular button within the form, and another regular button outside of the form; All of these onClick events are triggered for each change made within the Input fields above it.

**Expected behavior:**
I would expect that the onClick events would only be triggered when the button is actually pressed.

**Steps to reproduce:**

1. Input the code below
2. Open up Console view in your browser; I am using Google Chrome 83.0.4103.61
3. Enter characters into either the Username or Password fields
4. All 3 Console Logs should appear for each character typed ("Login function", testing...." and "testing 2...."

**Related code:**

```
const App: React.FC = () => {
	
const [user, setUser] = useState('');
const [pass, setPass] = useState('');

return (
  <IonApp>
	<IonContent fullscreen>
		<form onSubmit={(e) => { e.preventDefault(); console.log("Login function"); }}>
			<IonInput placeholder="Login ID" name="loginid" onIonChange={(e:any) => setUser(e.target.value)} />
			<IonInput placeholder="Password" type="password" name="pass" onIonChange={(e:any) => setPass(e.target.value)} />
			<IonButton type="submit">Login</IonButton>
			<IonButton type="button" onClick={console.log("testing....")}>TEST</IonButton>
		</form>
		<IonButton type="button" onClick={console.log("testing 2....")}>TEST 2</IonButton>
	</IonContent>
  </IonApp>
  );
};

export default App;
```

**Other information:**

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.9.2 (C:\Users\Green\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.1.1

Capacitor:

   Capacitor CLI   : 2.1.1
   @capacitor/core : 2.1.1

Utility:

   cordova-res : 0.14.0
   native-run  : 1.0.0

System:

   NodeJS : v12.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 10
```

**Comment by lttitus** [comment]
After some further testing, it looks to be triggering on render as well. I have some Tabs that show different pieces of information, and one of the Tabs shows Account details, along with a Logout button. When I view this Tab, it triggers the onClick function of the Logout button automatically.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
