### ISSUE TITLE
bug: Ion-content cut off height with size="large" attr on ion-title

### ISSUE THREAD

**Issue by roman-rr** [ionic-team/ionic#21595]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
Margin bottom ignored for components inside `ion-content` if `size="large"` attribute specified for condense collapsed header. `--padding-bottom` also ignored for `ion-content`. 
Issues reproducible only on iOS device. Browsers are works as expect. 

**Expected behavior:**
Correct height calculation for entry ion-content components include margins

**Steps to reproduce:**
To reproduce [Repository](https://github.com/roman-rr/ionic-bugs)
```bash
git clone https://github.com/roman-rr/ionic-bugs.git
cd ionic-bugs
npm install
ionic cordova build ios
```
Run with browser/device and look up into height. 
Press button for remove `size` attr on ion-title and check how height will changed.
Note: height also calculated properly if call scrollTop()/scrollBottom() methods on init. 

![ezgif-1-0529a55c5818](https://user-images.githubusercontent.com/10646478/85237166-d7d91b80-b44e-11ea-9df2-16cf7654cea9.gif)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This looks to be a similar issue as https://github.com/ionic-team/ionic/issues/20614, so I am closing this in favor of that issue.
