### ISSUE TITLE
feat: ion-tab-bar add a clear navigation stack option

### ISSUE THREAD

**Issue by ThonyFD** [ionic-team/ionic#21591]
# Feature Request

**Ionic version:**
[x] **5.x**

**Feature Request:**
Add a clear navigation stack option in ion-tab-bar or ion-tab-button, currently there is no way to clear pages pushed in stack by an ion-router-outlet if it's used through ion-tab-bar without losing the tab bar.

**Preferred Solution:**
Adding a property in ion-tab-button that instruct the router outlet to clear stack, I think this could be performed.

**Describe Alternatives**
An option in ion-tab-bar level to instruct if always clear stack or not.

**Related Code**
Currently I don't know what changes this code needs to achieve this behavior. It's using the **this.navCtrl.navigateRoot** and it should clear the stack in every tab change, but it does not.

https://github.com/ionic-team/ionic/blob/master/angular/src/directives/navigation/ion-tabs.ts

**Additional Context**
a repo with simple ion tabs demostration
[https://github.com/ThonyFD/ionic-tabs-stack-erro-reproduce](url)

**Comment by liamdebeasi** [comment]
Thanks for the feature request. Can you please clarify the issue you are running into? There might be a workaround that can be applied to your use case. Each tab holds it own stack, and we are not currently looking to change this behavior as it closely matches the behavior on native iOS and Android.

**Comment by ThonyFD** [comment]
Hi @liamdebeasi it's not a specific issue. I only want be able to clear the navigation stack when I need it.

Think in this scenario. I loaded a component in one o my tabs that import an service inside of @component decorator.

How can I clear or reset the services data? 
should I to crear a method for this ever?

Sometimes we only needs to clear form the DOM from components that it's not in use, or clear memory for those service that we are no using anymore.

**Comment by liamdebeasi** [comment]
If you need to reset the services data, you can create a method that does so. I would caution against trying to manually manage the work the Angular Router does. If you are running into a performance issue with how the Angular Router works, I recommend filing an issue on their repo.

Using `navigateRoot` should clear all existing pages in the current stack. That being said, each tab holds its own stack so this may or may not work for your use case: https://github.com/ionic-team/ionic/blob/master/angular/src/providers/nav-controller.ts#L97-L114

Another option is you can use the `replaceUrl` option when using Angular Routing to replace states in your history: https://angular.io/api/router/NavigationExtras#replaceUrl

**Comment by ThonyFD** [comment]
@liamdebeasi  My motivation for open, this request was, show you that this component could be improved, but you sound like, "we don't want to extend or improve our component functionalities."

It's clear that developers have many alternatives to do it using Angular directly, but if Ionic Framework creates a stack for each tab, why not create a way to manage them through Ionic Framework? 

I love what you do with NavController, which is a very smart way to wrap an Angular capability, but the ion-tab-bar is out of this smart concept. 

And for last, ion-tab-bar It's very coupled with, Angular Router, maybe like no other of your components, however, it does no expose a way to control it.

I never use ion-tab-bar, cause it's a very limited component, and fits in very few UI cases. You have the opportunity to do it in a better way.

NOTE: You did it great yesterday in Ionic Conf.

**Comment by mhartington** [comment]
@ThonyFD the router and a lot of it's logic is dependent on angular router, so we're not about to go adding methods that go against the flow of how that router works.

Given the flow of how tabs work, clearing the stack when you tap a tab goes 100% against how tabs are supposed to work. They should not clear the stack when you navigate back to a given tab. That is the whole point of how tabs are supposed to work.
