### ISSUE TITLE
bug: iosTransitionAnimation and mode=md doesn't work on pop

### ISSUE THREAD

**Issue by lcaprini** [ionic-team/ionic#21604]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
`iosTransitionAnimation` in `navAnimation` Ionic's config works only to `push` when `mode` is `md`.

**Expected behavior:**
`iosTransitionAnimation` in `navAnimation` Ionic's config should work on `push` and `pop`.

**Steps to reproduce:**
Add `navAnimation: iosTransitionAnimation` and `mode: "md"` in `IonicModule.forRoot` configuration and try to navigate with `push` and `pop`.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
