### ISSUE TITLE
feat: expose createAnimation in @ionic/angular

### ISSUE THREAD

**Issue by CFT-Chris** [ionic-team/ionic#21615]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

Expose createAnimation to help create an AnimationBuilder inside of app.module.ts when we don’t have access to the Angular service, AnimationController.

There are many global properties for Ionic config that require AnimationBuilder type (see https://ionicframework.com/docs/angular/config). We should be able to create animations in the same fashion as using AnimationController's create() within the Config object supplied to IonicModule.forRoot() of app.module.ts.

**Describe Preferred Solution**

Expose createAnimation in the @ionic/angular project.

**Describe Alternatives**

Duplicate a lot of the lower-level code inside of @ionic/core createAnimation to create an Animation to return in an AnimationBuilder function.

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks! I merged your PR, and a fix will be available in Ionic Framework 5.2.3.
