### ISSUE TITLE
feat: Allow a background image on ion-toast

### ISSUE THREAD

**Issue by cesaresantiago** [ionic-team/ionic#21650]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

The Ion-toast component does not have a way to add a background on the toast message. Pre Ionic 4, we were able to get by this by defining custom CSS for ion-toast, making the icon image appeared on our desired area. After the CSS was moved behind the Shadow Dom, this is no longer possible.

**Describe Preferred Solution**

 CSS variables that allowed us to set an icon image an its position would work.
Exposing a Shadow Part that allowed us to keep using custom CSS to set an icon and position would work as well.

**Describe Alternatives**

Pre Ionic 4, custom CSS would do the job:

ion-toast.toast-wrapper.toast-bottom {
background-image: url("../assets/icon/toast_check.svg");
    background-position: 1.3rem;
    background-repeat: no-repeat;
    background-size: 24px 24px;
}

After the move to the use on Shadow Dom there is no way to use this alternative, so we need either CSS variables for the component or an exposed Shadow Part

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the feature request. This should be do-able with the upcoming shadow parts in Ionic Framework 5.3.0.

You will be able to do something like:

```css
ion-toast::part(container) {
  background-image: url(my_image.png);
}
```

The feature has already been implemented, we just need to update the docs. Thanks!

**Comment by cesaresantiago** [comment]
Greetings, @liamdebeasi . During our testing we've found that this works perfectly on iOS 13.6  However, on 13.3 and below, using the ion-toast::part(container)  selector has no effect. 

Is there a known issue about this? Thanks.

**Comment by liamdebeasi** [comment]
`::part` is only supported on iOS 13.4 and newer.

See the "Browser Support" section of our blog post for more information: https://ionicframework.com/blog/customize-your-ionic-framework-app-with-css-shadow-parts/

**Comment by FanYeeChok** [comment]
how to do if iOS lower then 13.4?

**Comment by liamdebeasi** [comment]
@FanYeeChok Use the `--background` CSS variable: https://ionicframework.com/docs/api/toast#css-custom-properties.
