### ISSUE TITLE
bug: ion-backdrop disable click even when visible=false

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic#21676]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**

I add a `<ion-backdrop>` to my `<ion-app>`, set the property visible to false, it's not visible anymore but still disable click ....

Maybe I misunderstood its usage and it should be used with *ngIf ? Then maybe the doc should be more precise ? And what's the point of the visible property ?

I found a workaround that consist in using `*ngIf="showBackdrop"` instead of `[visible]="showBackdrop"` and on `(ionBackdropTap)` I set `showBackdrop` to false but then I really don't get the point of the `visible` property ... 

Maybe I'd like a way to do [(visible)] with double bind

Thanks for you help

**Expected behavior:**

When the backdrop visible property is set to false, it should also enable interaction with the app ?

**Steps to reproduce:**

Add a `ion-backdrop`, set its property `visible` to false, put a button in your app and try to click it => it doesn't work

**Related code:**

https://stackblitz.com/edit/ionic-angular-v5-fdkdll

**Comment by liamdebeasi** [comment]
Thanks for the issue. The `ion-backdrop` still receives click events even though the backdrop is not visible. You need to set `pointer-events: none`.

**Comment by Yohandah** [comment]
@liamdebeasi Thanks for your response. I was wondering maybe it should be specified in the docs ? I don't know it doesn't seem crystal clear to me, I also needed to open the demo snippet to find out I needed to specify the opacity myself. Just a thought.
