### ISSUE TITLE
feat: ion-select[multiple] should have "Select/Deselect All" button

### ISSUE THREAD

**Issue by teh-botol** [ionic-team/ionic#21672]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
ion-select[multiple] might have a lot of options. It's a pain-in-the-a** of user to select/deselect all option.
Even for 2+ options make me lazy to select/deselect it.

**Describe Preferred Solution**
Please add "Select/Deselect All" button on the alert interface.
Since alert is the only interface for [multiple], it's should be no issue.

**Comment by indraraj26** [comment]
You dont have to open again ion-select to unselect one by one (which one you dont want).

But clear icon cant be added in ion-select like we have in searchbar.

It would be great to have in ion-select popup, when you use ion-select as a multiple select. first item will be select all/unselect all.

_Originally posted by @indraraj26 in https://github.com/ionic-team/ionic/issues/20998#issuecomment-611539413_

**Comment by teh-botol** [comment]
IMHO, alert is the only way for multiple select.

Clear icon is half the functionality I needed.

Any additional button beside ion-select is a waste of space and unclean for just one input.

IMHO again, "Select/Deselect All" is a mandatory functionality for any multiple select.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. We plan on allowing custom templates in `ion-select` in the future, which will more easily allow for this feature. Please see https://github.com/ionic-team/ionic/issues/18067
