### ISSUE TITLE
feat: ion-virtual-scroll support auto size

### ISSUE THREAD

**Issue by HyperLife1119** [ionic-team/ionic#21687]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

Sometimes, the height of each item in the virtual scroll is not consistent, so I cannot provide `approxItemHeight` property, I hope it supports automatic size. Similar features have been implemented in angular cdk.
https://stackblitz.com/edit/cdk-virtual-scroll-simple-autosize?file=app%2Fapp.component.html

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the feature request. With upcoming major releases of Ionic Framework, we are going to be transitioning users to Angular's CDK Virtual Scroller. As a result, we have a freeze on new features to `ion-virtual-scroll`.
