### ISSUE TITLE
bug: Ion item sliding bug with virtual scroll

### ISSUE THREAD

**Issue by pseudooriginal** [ionic-team/ionic#21689]
# Bug Report

**Ionic version:**
[x] **4.8.1**

**Current behavior:**
The bug occurs with the virtual scroll and sliding items. When a sliding item is opened and the user scroll down, many other items are open.

**Expected behavior:**
Other items should not be opened.

**Steps to reproduce:**
Open a sliding item with the button and scroll down.

**Related code:**
https://ionic-virtual-scroll-sliding.stackblitz.io

**Ionic info:**
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\GIT_TB\osapp\mobile\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.10.0 (C:\GIT_TB\osapp\mobile\node_modules\@ionic\angular)
   @angular-devkit/build-angular : 0.13.9 (C:\GIT_TB\osapp\mobile\node_modules\@angular-devkit\build-angular)
   @angular-devkit/schematics    : 7.3.9 (C:\GIT_TB\osapp\mobile\node_modules\@angular-devkit\schematics)    
   @angular/cli                  : 7.3.9 (C:\GIT_TB\osapp\mobile\node_modules\@angular\cli)
   @ionic/angular-toolkit        : 1.4.1 (C:\GIT_TB\osapp\mobile\node_modules\@ionic\angular-toolkit)        

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 22 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\t.barroso\AppData\Local\Android\Sdk)
   NodeJS            : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. With upcoming major versions of Ionic Framework, we are going to be transitioning to using Angular's CDK Scroller. As a result, we have a freeze on new features and bug fixes on `ion-virtual-scroll`. See https://material.angular.io/cdk/scrolling/overview for how to get started with CDK Scroller.
