### ISSUE TITLE
bug: Can't use the "color" CSS to chance the color of ionicons

### ISSUE THREAD

**Issue by MigueBlogs** [ionic-team/ionic#21682]
Hello! i'm using the v. 5.1.2 and i can't change the colors of my ionicons with the statement of "color" by CSS template.
`<script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>`

his is a pice of my code (CSS - HTML):
`ion-icon {
    font-size: 26px;
    color: #999;
  }`

`<td id="Hospitales">
                            <div class="row">
                                <div class="column1 clickable" id="Hospitales" data-sources="Hospitales">
                                    <ion-icon name="medkit-outline"></ion-icon>
                                </div>
                                <div class="column2">
                                Estab. de Salud:<br><span class="resultNumber"></span>
                                </div>
                            </div>    
                        </td>`

I've saw the latest post related to this issue and there are no answers for this issue, i wish you could fix this for a future.

Tanks!

**Comment by indraraj26** [comment]
Working fine here -> https://codepen.io/indraraj26/pen/MWKVYBx
