### ISSUE TITLE
[ionic2] onScrollEnd in ion-content only fire when register

### ISSUE THREAD

**Issue by kitkimwong** [ionic-team/ionic#5549]
#### Short description of the problem:

onScrollEnd in ion-content only fire when register
#### What behavior are you expecting?

onScrollEnd must fire when user finished the scroll behavior.

**Steps to reproduce:**
1. I register the onScrollEnd method in ngAfterViewInit
2. The onScrollEnd event only fire when  call ngAfterViewInit 
3. After that onScrollEnd will not fire in each scroll

`ngAfterViewInit(){
    this.app.getComponent("page1").onScrollEnd( () =>{
          console.log(this.app.getComponent("page1").scrollElement.scrollHeight);
    });
  }`

**Ionic Version**: 2.x

**Comment by adamdbradley** [comment]
Sorry but I was not able to replicate the the problem. Would you be able to provide a plunker so we can better debug this? /cc @jgw96

**Comment by kitkimwong** [comment]
In beta .9 it seem that onScrollEnd event is canceled.
I use `addScrollListener` to bind the scroll event every thing works fine, but I can know that the scroll event is finished? 
Now I just use `settimeout` to check whether the scroll is finished .

**Comment by jgw96** [comment]
@kitkimwong would you mind test this with beta.10 please? Also if you could provide a [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) that would be awesome. Thanks for using Ionic!

**Comment by kitkimwong** [comment]
@jgw96 
http://plnkr.co/edit/AgqhmDscziegeMKFj2w7?p=preview

In this demo, the `onScrollEnd` event just only fire when register. After that onScrollEnd will not fire in each scroll

**Comment by jgw96** [comment]
Note to team: Here is a testing plunker im using that uses our lifecycle events instead of Angular's. http://plnkr.co/edit/lQJSBi4b3zTe0cKVyMrl?p=preview

**Comment by kitkimwong** [comment]
So Is this is not regarded as a bug?
