### ISSUE TITLE
Implement MD pull to refresh style

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic#5557]
<img src="https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsOXZCd0M3bEFuMEU/patterns_swipetorefresh_position4.png" width="250">

https://www.google.com/design/spec/patterns/swipe-to-refresh.html#swipe-to-refresh-swipe-to-refresh

**Comment by gabrielbazan7** [comment]
This feature is working ?

**Comment by MatanYed** [comment]
Why removed from beta.12?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! The reason this was removed from beta.12 was because we decided to focus on big, breaking issues and aot compile/tree shaking in beta.12 and not add any big new features. Hope that makes sense. Thanks!

**Comment by MatanYed** [comment]
So when you will done big new features? (not only the MD-refresher)
after v2.0 will publish or RC?

**Comment by TheRealKira** [comment]
Any updates on this in a future 2.0.X build? The current pull to refresh makes the app feel very "webby". This would be a great addition to v2 to make it feel almost completely native. 

P.s. Thanks for the great work on v2 too you guys, loving it.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#115

**Comment by davideas** [comment]
The link for the request 115, is broken, but most important what is the status of this feature?

Cause, we don't want to switch view OR cover the current view with loading layer AND the _pull-to-refresh_ is causing the content jumping which misleads our eyes to follow the content.
We are also triggering the refresh on page entering (we only want 1 type of refresh view to be more consistent with the UI!).

The _swipe-to-refresh_ is THE solution.

**Comment by DeveloperMatheus** [comment]
Hello, what is there any update of this issue? I have a client that wants the refresher to work exactly like this, but i could just make a workaround but:

1) The ion-refresher still pushes the whole view down

2) Also shows the background color (I could not make it transparent no matter what because of the content background)

I guess this is still pending as i searched for something like this for 2 days ):
The community wants this feature, so you guys can go for it!

**Comment by JensNeocosmo** [comment]
I would also really love to have this feature. It makes the look & feel of the app more native. I also have a client who wants the refresher to work like that.

**Comment by senturkzuhtu11** [comment]
it should not be that hard

**Comment by peterlai107** [comment]
+1

**Comment by azharonline** [comment]
Is this feature coming anytime soon?
