### ISSUE TITLE
Ionic2 disables vertical swiping/dragging

### ISSUE THREAD

**Issue by godzsa** [ionic-team/ionic#5767]
#### Short description of the problem:

Vertical 'pan' and 'swipe' events won't fire.
`<ion-content (pan)="log($event)"> 
       ... 
</ion-content>`
It fires for horizontal swipes and pans but not for vertical.
#### What behavior are you expecting?

When I touch the screen and do a swiping or dragging motion, I expect a 'pan' or 'swipe' event to be fired, if set.

**Bug:**
Also there is a bug in Hammer.js events in Angular2, so I had to fix that manually, based on this issue-comment: https://github.com/angular/angular/issues/6993#issuecomment-187115690

**Ionic Version**:  2.x

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Distributor ID: Ubuntu Description: Ubuntu 15.04 
Node Version: v5.7.1
```

**Comment by godzsa** [comment]
I believe `<ion-content>` reserves firing these events on the vertical axis for `<ion-refresher>` I tried to look up this in the source code, but found nothing. If anyone has a suggestion/hint on which module prevents firing pan/drag events on the vertical axis I would be glad to fix this bug.

**Comment by godzsa** [comment]
I did further research on the case and found a problem might be that `touch-action` css properties are set to `manipulate` although I couldn't fix this so far. Another similar problem is that `webkit-user-drag` is set to `none`. I'm not sure on this, but I think these can cause the problem.

**Comment by royipressburger** [comment]
Im also experiencing the same issue.. Want to be able to catch the vertical swipe event. regardless if `ion-refresher` is present or not.

**Comment by danbucholtz** [comment]
Hi @godzsa and @royipressburger,

The reason for this is Angular supports the default set of Hammerjs events.

"By default it adds a set of tap, doubletap, press, horizontal pan and swipe, and the multi-touch pinch and rotate recognizers"

We are considering adding first-class support for Hammer and user configurable gestures but have not made a decision one way or another yet.  I'm going to close this issue for now.

Thanks,
Dan

**Comment by philmerrell** [comment]
@danbucholtz Is there another place we can track this issue?  I think you'll find that even in the Ionic 2 [Gesture Demo](http://ionicframework.com/docs/v2/components/#gestures), vertical panning is only recognized after it detects a horizontal pan first.

In other words, if your first pan gesture is vertical (and straight enough), no pan events are recognized.  If your vertical pan strays even slightly to the left or right, it will then unlock the vertical pan events and they will be recognized.

Other oddities are the events `(panLeft)=testPanEvent($event)` and `(panRight)=testPanEvent($event)` are recognized while `(panUp)=testPanEvent($event)` and `(panDown)=testPanEvent($event)` are not recognized

This gesture is obviously crucial for mobile applications, so I'd love to be able to follow the progress. 😄 

Thanks!

**Comment by danbucholtz** [comment]
Hi @philmerrell,

Thanks for reminding me about this.  We did end up overriding this configuration in Ionic.  Right now, it is using the default hammer configuration, so only the following gestures are enabled:

[From Hammer.js docs](http://hammerjs.github.io/getting-started/)
```
By default it adds a set of tap, doubletap, press, horizontal pan and swipe, and the multi-touch pinch and rotate recognizers. The pinch and rotate recognizers are disabled by default.
```

Basically, pinch and rotate won't work in Ionic right now.  We also need to enable vertical panning and swiping.

We are going to need to spend some time on this, but it may be delayed a bit.  I will check with Adam, the team lead, and see what he thinks.

Thanks,
Dan

**Comment by jgw96** [comment]
Hello all! I can confirm that in the latest release pinch, pan etc have been enabled. Thanks for using Ionic!

**Comment by jgw96** [comment]
Reopening for now to investigate.

**Comment by Despay** [comment]
Hello,

i'm currently experiencing this issue. 
The behaviour of this problem was very well explained by philmerrell. 
Did you guys found a trick ?

Thanks

**Comment by Despay** [comment]
Ok so i found nothing about this problem, so instead of using (pan) in html, i used Hammer directly in my component code, using this example http://codepen.io/jtangelder/pen/ABFnd and it works much better now for vertical pan

**Comment by 64jcl** [comment]
Yes we are experiencing the same issues. When listening to any pan event and then panning up or down, the system will deliver a single event object with center X and Y set to zero and not relative to the components corner, hence its impossible to know where the user is pointing.

However, if you first pan left or right and then up or down the events fire fine with the center coordinate initialized in the event object ! Very odd. Something is gobbling up the events for pan up and pan down unless you startet your panning by first moving left or right.

**Comment by godzsa** [comment]
I just realized it is not working on your demo page either.
http://ionicframework.com/docs/v2/components/#gestures
If you try to pan, or swipe vertically it won't work.

**Comment by matijse** [comment]
I haven't tried recently, but got it working some time ago by using Hammer directly.

```
import {Hammer, DIRECTION_VERTICAL} from "ionic-angular/gestures/hammer";
```

You can set listeners in your .ts file on an element by id:

```
let gesture = Hammer(document.getElementById("element-to-drag"), {direction: DIRECTION_VERTICAL});
gesture.get('pan').set({direction: DIRECTION_VERTICAL});
gesture.on('panstart', e => {
    ...
});
gesture.on('panmove', e => {
    ...
});
gesture.on('panend', e => {
     ...
});
```

**Comment by PavlosIsaris** [comment]
@matijse Does this work on your code? I tried it but I get the error "ERROR TypeError: Cannot read property 'addEventListener' of null", even tough there is an element with the specified id. My code is in the ionViewDidLoad method.

**Comment by matijse** [comment]
@PavlosIsaris This code did work, but I used it some time ago (Ionic 2 RC3). It might not work in more recent versions of Ionic...

Also my code is in the `ngAfterViewInit()` method, not sure if this makes a difference.

**Comment by mzl1988** [comment]
import { Hammer } from "ionic-angular/gestures/hammer";

hammer: any = Hammer;
ionViewDidEnter() {
		let gesture = Hammer(document.getElementById("element-to-drag"), { direction: this.hammer.DIRECTION_ALL });
		gesture.get('pan').set({ direction: this.hammer.DIRECTION_ALL });

		gesture.on('panup', e => {
		});
		gesture.on('pandown', e => {
		});
		gesture.on('panleft', e => {
		});
		gesture.on('panright', e => {
		});
	}

**Comment by mzl1988** [comment]
import { Hammer } from "ionic-angular/gestures/hammer";

hammer: any = Hammer;

ionViewDidEnter() {

		// gesture
		let gesture = this.hammer(document.getElementById("xxx"), { direction: this.hammer.DIRECTION_ALL });
		gesture.get('pan').set({ direction: this.hammer.DIRECTION_ALL });
		gesture.on('panleft panright panup pandown', e => {
			this.panEvent(e);
		});;
	}

**Comment by mzl1988** [comment]
import { Hammer } from "ionic-angular/gestures/hammer";

hammer: any = Hammer;

ionViewDidEnter() {
	// gesture
	let gesture = this.hammer(document.getElementById("xxx"), { direction: this.hammer.DIRECTION_ALL });
	gesture.get('pan').set({ direction: this.hammer.DIRECTION_ALL });
	gesture.on('panleft panright panup pandown', e => {
	});
}

**Comment by zds-jack** [comment]
pan etc have been enabled.？But how to use it?
http://ionicframework.com/docs/v2/components/#gestures，The document is too simple

**Comment by zds-jack** [comment]
@godzsa  because touch-action=:'pan-y’
![20170810184323](https://user-images.githubusercontent.com/16936239/29168929-ddb38f7e-7e03-11e7-8dee-d3dd5b77ef52.jpg)

**Comment by zds-jack** [comment]
@Palisanka  This may help you
https://stackoverflow.com/questions/29484146/simple-example-of-gesture-in-hammerjs
