### ISSUE TITLE
Ionic v2 - Full Screen Video then back - Causing Body to shift up

### ISSUE THREAD

**Issue by tonyawad88** [ionic-team/ionic#6151]
#### Short description of the problem:

I have an html5 video in an ionic2 application. When I go in full screen then I close the full screen to go back to the original view, the body seems to be shifted up. 
#### What behavior are you expecting?

Expecting it to go back to normal after exiting full screen.

**Steps to reproduce:**
1. Create an ionic2 app. (currently beta 4)
2. Add an html5 video
3. Not sure if this helps but here's my code snippet for the video:

```
<video controls poster="{{item.ad_landscape}}" preload="metadata">
          <source [src]="item.url_path" type="video/mp4">
</video>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
None. 

**Which Ionic Version?** 2.x
![screenshot_2016-04-13-06-28-03](https://cloud.githubusercontent.com/assets/3638322/14490732/912c36cc-0142-11e6-932f-3a3fd720c6c8.png)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
WARN: ionic.config.js has been deprecated, you can remove it.

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3 Build version 7D175 
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! What platforms is this happening on? IOS, Android ?

**Comment by tonyawad88** [comment]
@jgw96 Android.

**Comment by jgw96** [comment]
@tonyawad88 Thanks for the info! (:

**Comment by jgw96** [comment]
Hello! Is this still an issue with the latest version of ionic? Thanks!

**Comment by tonyawad88** [comment]
It is. It only happens when we exit the video's full screen mode. Again it's only in Android and I am using native <video> tag. If I navigate back to another view, the navbar re-adjusts and fix itself. 

Feel free if you need more from my end. Thanks

**Comment by phamduongnhatnam** [comment]
Hi, I meet the same problem with latest ionic version.

Outside, @tonyawad88 Can you trigger the video to view in fullscreen programatically? Not depend on user native control?

**Comment by renjit00** [comment]
Hi , Even i am facing the same Issue ,please suggest how to resolve this issue,its very helpful

**Comment by Sampath-Lokuge** [comment]
You need to upgrade your project to latest `3.8.0`.  @renjit00 

https://github.com/ionic-team/ionic/releases/tag/v3.8.0

**Comment by renjit00** [comment]
"dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/app-availability": "^4.3.1",
        "@ionic-native/camera": "^4.2.1",
        "@ionic-native/core": "^3.12.1",
        "@ionic-native/device": "^3.12.1",
        "@ionic-native/email-composer": "^4.2.1",
        "@ionic-native/file": "^4.2.1",
}
only need to upgrade angular CLI?
