### ISSUE TITLE
Radio alert's buttons were hidden in 5 inch android mobile landscape mode.

### ISSUE THREAD

**Issue by dheran** [ionic-team/ionic#6326]
**Ionic 2**

Middle part of the alert was scrollable but bottom part where buttons placed was not visible in landscape mode.

**Comment by dheran** [comment]
![screenshot_2016-05-23-21-53-18](https://cloud.githubusercontent.com/assets/15922996/15477197/fcb3328e-2130-11e6-9e93-79af5e055203.png)

**Comment by morrisonbrett** [comment]
This bug still exists.

**Comment by tagmat** [comment]
You can override scss variable $alert-md-content-max-height. It is set to 240px by default. 200px should fix your problem. This is not a perfect solution but a quick fix.

/// @prop - Maximum height of the alert content
$alert-md-content-max-height:                 200px !default;

Patch file is
[fix_6326.patch.zip](https://github.com/driftyco/ionic/files/900309/fix_6326.patch.zip)

Pull request according to fix is: #11073

**Comment by chandanch** [comment]
@tagmat overriding the Scss variable `$alert-md-content-max-height ` fixes the problem in landscape mode
For ios use:
`$alert-md-content-max-height : 180px !default`
