### ISSUE TITLE
virtualScroll + infiniteScroll not working in iOS

### ISSUE THREAD

**Issue by cfjedimaster** [ionic-team/ionic#6342]
#### Short description of the problem:

I've got an app using virtualScroll and infiniteScroll.  When I test, I expect that as I scroll down, infiniteScroll will fire off a request to fetch more data.
#### What behavior are you expecting?

In the browser and Android, it works. In iOS, it never fires off the request. I don't get an error - it just doesn't seem to recognize that it needs to fetch more data.

My blog post about the app is here: https://www.raymondcamden.com/2016/04/25/an-example-of-virtualscroll-and-infinite-scroll-in-ionic-2/

The specific code base is here: 

https://github.com/cfjedimaster/StrongLoopDemos/tree/master/superlongscroll 

**Which Ionic Version?** 
2

**Comment by Shadowfaxenator** [comment]
Are you trying to build for ios 9?

**Comment by cfjedimaster** [comment]
Yeah

**Comment by Shadowfaxenator** [comment]
Can be a problem with  iOS 9 App Transport Security?

**Comment by cfjedimaster** [comment]
Um... no idea. :) Thing is - if it was an issue hitting the API to get data, I would not have gotten the first 'page' of data at all.

**Comment by Shadowfaxenator** [comment]
any updates?

**Comment by daviddk** [comment]
+1 on this issue, also have a demo app running which showcases the issue. On Android it kinda works, but scroll back to top when adding new data to the list.

Ion-Refresher also doesn't work on iOs, seems to be working fine on Android. 

https://github.com/Euricom/tryout-ionic2/tree/virtualscroll

**Comment by bjakubiak** [comment]
infiniteScroll doesn't work on iOS even without virtualScroll. I took ionic2 tutorial starter, added http://ionicframework.com/docs/api/components/infinite-scroll/InfiniteScroll/ to main page, and it works on browser but not on iOS. doInfinite method doesn't even start there.

**Comment by nathan5x** [comment]
I tried exactly what @bjakubiak did. But am getting a different issue, looks like someone else had the same issue like me
Refer this - https://github.com/ionic-team/cordova-plugin-wkwebview-engine/issues/170

Any other workaround?
