### ISSUE TITLE
bug: Ionic2 ion-slides not properly working with *ngFor

### ISSUE THREAD

**Issue by 4ian** [ionic-team/ionic#6515]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hey Ionic 2 team,

Ionic 2 `ion-slides` component seems to be working properly when `ion-slide` are either hardcoded into the template or when they are created with a ngFor iterating over an array that is not empty/not modified.
If the ngFor is first iterating over an empty array and then the array is modified, the slides seems to be broken (in particular, looping is not working properly).

This bug can maybe be generalised to any `ion-slide`s that are dynamically added/removed after the first creation of the `ion-slides` but I have not tested this.

To reproduce the bug, clone, install and launch the sample app of this repo: https://github.com/4ian/ionic2-slides-test

Click on the button to fill the array used to generate the slides. The second slider won't work properly. The first slider will be working but I've used a workaround: the slider is not created when the array is empty.</span>

<span is-issue-template></span>

**Comment by teledemic** [comment]
Thank you for the workaround - helped a ton

**Comment by jorgercosta** [comment]
What was the workaround here?

**Comment by 4ian** [comment]
In my case, I delayed the creation of the slider until I have all the data needed (a simple `*ngIf="items.length"` to ensure that the items array was filled with fetched data).

**Comment by teledemic** [comment]
I found I was also having problems on update, so I am briefly (10ms) setting the binding source to empty whenever it changes, so the ngIf deletes and recreates the slides rather than updating them incorrectly.

**Comment by jorgercosta** [comment]
Thank's

**Comment by zefrench** [comment]
Really workarounds !! 
Thanks.

**Comment by morrisonbrett** [comment]
I had to replace <ion-slide-box> with <ion-slides> to get it working.

**Comment by t1gu1** [comment]
On the swipper api you can see what you can put in a slide options.
[http://idangero.us/swiper/api/#.WIandPHhCkA](http://idangero.us/swiper/api/#.WIandPHhCkA)

eg:
`mySlideOptions = {
      pager:true,
      paginationClickable: true,
      **onReachEnd : function(){
        console.log("end");
          this.showButton = true;
        }**
  };`

in the view you put the options:
`<ion-slides [options]="mySlideOptions">`

Voila

**Comment by iron9light** [comment]
@t1gu1 It seems ionic guys are rewriting slides component.

**Comment by raxim1** [comment]
I think ionic 2 is a nightmare, don't use it, you are risking your project to be failed. I was able to create the slider more easier than make the ionic slider work

**Comment by PunkHaz4rd** [comment]
There's the same problem using ionic 3

**Comment by Luzianadewi** [comment]
how to made slide dinamic from database with ionic 2 ?

**Comment by raxim1** [comment]
Two thing is really important when you are using ionic, and develop for mobile.

1, Try out your stuff without inspector window also on Chrome.
2, Instead of canvas use svg, as it's horrible performance wise. Now my virtual scrolling started to work smoothly - there are lot's of component which are not enough flexible, or just making me sad. (ng-lazyload-image) - it's a very heavy stuff, ionic one is not working. simply use <img> ... 4-5 times faster.

P.s.:
ion-slide is making a mysterious 2 additional slides on the fly, which is very sensitive when the data is dynamic.

**Comment by patrickdodgen** [comment]
+1

**Comment by PunkHaz4rd** [comment]
+1

**Comment by JunkyDeLuxe** [comment]
<ion-slides [options]="mySlideOptions">
=> Can't bind to 'options' since it isn't a known property of 'ion-slides'

**Comment by kinglionsoft** [comment]
``` html 
<ion-slides pager [autoplay]="2000" [loop]="true" #slides>
      <ion-slide *ngFor="#item of items">      
          {{ item}}
      </ion-slide>
</ion-slides>
```
``` js
items=[ 1, 2, 3]; // works fine so far
@ViewChild('slides') slides: Slides;
constructor(private http: Http) {
}

ionViewDidLoad() {
      this.http.get('...').then(r=>{
            this.items=r; 
      });
}

```

**Comment by kinglionsoft** [comment]
By the way, it works fine with ionic 1.

**Comment by erperejildo** [comment]
did you manage to fix this issue? I'm facing similar issue with `[hidden]` but `update()` doesn't help (I tried also with `setTimeout`)

**Comment by sijav** [comment]
I made the same kinda workaround, something like what has been already posted here.
1. I put `*ngIf="!isUpdatingSlides"` on `ion-slides` element,
2. And then on ts file I made a variable named `isUpdatingSlides: boolean = false;`
3. And after I'm done changing slides I do this
```
setTimeout(() => {
	this.updatingSlides = true;
	setTimeout(() => {
		this.updatingSlides = false;
	}, 10);
}, 10);
```
The time outs here make sure that element has been done changing and slides already updated so we don't get any more issues (I've encounter some).
This will recreate the element but however on every update you will encounter a disappearance for more than 50ms and even some funny temporary behaviors but the good thing is that it works and it gives the feelings of something changed!! It's good when you're gonna put some dummy contents or pre-cached contents before getting actual values from server and changing it or change it with every update user might want to see.

**Comment by aungthawdar** [comment]
I solve it with dirty way for the dynamic slides autoplay.
Ionic autoplay options for dynamic slides get the error
so I import the following library and solve it.

**import { Observable } from "rxjs/Rx";**

Add the following line,
in the 
**constructor(){
         Observable.interval(5000).subscribe(() => {
            if(this.slides.isEnd())
              this.slides.slideTo(0,1000);
            else
              this.slides.slideNext(1000);
      
          });
}**

**Comment by jQrgen** [comment]
+1

**Comment by gingerhero** [comment]
+1

**Comment by PunkHaz4rd** [comment]
+1

**Comment by jQrgen** [comment]
I have a component inside of a slider tag inside of a page with an *ngFor which does work the first time i route to the page with setRoot(). The 2. time it does not work so now i have to spend a lot of time to write my own hack on top of ionic. 

similar: https://stackoverflow.com/questions/38552261/ionic2-slider-is-not-working-with-ngfor-angular2

**Comment by EugeneSnihovsky** [comment]
After a lot of painful research I found solution. In my case I use several slides with list of items on each of them with infinite scroll. Here is info, that can be helpful for other developers:

1. To update `ngFor list`, that located inside slide you can add pipe that takes `listChanged` string argument and always return list
```
    public transform(items: Array<any>, listChanged: string): Array<any> {
        return items;
    }
```
And in your component define `public listChanged: string;` and change it to new value every time when list updated
```
this.listChanged = Math.random().toString(16).slice(2);
```

2. Note, that when you add some items in list, slide height will not change automatically and you need to change it manually. This [comment](https://github.com/ionic-team/ionic/issues/10690#issuecomment-285023887) can be helpful. In my case I call `"slideDidChange(); slideWillChange();"` on each infinite scroll calback

3. Unfortunately infinite scroll will not disappear manually inside slides. But you can hide it at all by css and it will still work
```
<ion-infinite-scroll class="component-infinite-scroll" ...

.component-infinite-scroll {
    height: 0;
    overflow: hidden;
}
```

Note: beware of side effects. I can't guarantee that this hack will work in all possible cases. I'm not sure that this can be used in production.

**Comment by glemiere** [comment]
Here is a copy of my post here : https://github.com/ionic-team/ionic/issues/10784

Hi!
When you're going from the last slide to the first one, use `this.slider.slideTo(1);`.
When you're going from the first slide to the last one, use `this.slider.slideTo(X);`

You can know which direction you're taking by using getActiveIndex() and getPreviousIndex().

X being the value of your last index.

Here is a working example :
```
<ion-slides #slider (ionSlideWillChange)="onChangeMonth()" >
...
</ion-slides>
```
```
import {Slides} from 'ionic-angular';

export class MyClass {
@ViewChild('slider') slider: Slides;

  private onChangeMonth() {
    this.doMyStuff().then((indexes) => {
      // Last slide to first slide
      if (indexes[0] == X + 1 && indexes[1] == X) { // Change X and X + 1
        this.slider.slideTo(1);
      }

      // First slide to last slide
      if (indexes[0] == 0 && indexes[1] == 1){
        this.slider.slideTo(X); // Change X to the last index of your slider
      }
    })
  }

  private doMyStuff() {
    return new Promise ((resolve, reject) => {
      // Here is where you update your values each time your slide change.
      ...
      return ([this.slider.getActiveIndex(), this.slider.getPreviousIndex()])
    })
  }
}
```

Enjoy.

PS : Thank you @AdhemarBouchet. I found out how to make it working because you found the fixLoop function that I did inspect, good job! ;-)

**Comment by josephilipraja** [comment]
In my case, a simple solution did the trick.

**My ion-slides Setup:**
```
<ion-slides #slides *ngIf="specialEventItems && specialEventItems.length" loop dir="ltr" pager autoplay="3000" speed="600" effect="slide">
    <ion-slide *ngFor="let splEvent of specialEventItems" tappable (tap)="showEvent(splEvent.id)">
        <img [src]="splEvent.banner">
    </ion-slide>
</ion-slides>
```

As you can see, I have a ngFor to load slides from httpAPI. Also my ion-slides loops & autoplays with slide effect.

I had an implementation of 'Pull to Refresh' to reload Slides from httpAPI; the above code worked without issues until the data is reloaded. Few duplicate ion-slide elements were the culprit, causing bad looping.

**Solution for me:**
```
getSpecialEvents () {
    this.specialEventItems = [];  // <===== THIS DID THE TRICK!!
    this.api.get('special-events').subscribe(
        (res) => {
            this.specialEventItems = res['events'];
        }
    );
}
```

Simply, I rest the slides variable to empty array before fetching new data from httpAPI.
I guess, the duplicated elements gets deleted once I reset the slides to an empty array.

Hope this helps someone.
