### ISSUE TITLE
Badge with ngFor has incorrect spacing

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#6593]
#### Short description of the problem:

When I try and create badges with ngFor, the spacing between them is different. 

An example demonstrating this:

```
   <ion-badge style="background-color:rgb(221,59,59)">Delivery</ion-badge>
   <ion-badge style="background-color:rgb(79,217,182)">Excellence</ion-badge>
   <ion-badge *ngFor="let value of user.coreValues" [style.background-color]="value.color">{{value.name}}</ion-badge>
```

![capture](https://cloud.githubusercontent.com/assets/2852839/15426503/5772006e-1e8f-11e6-9855-56c85f3015d5.PNG)
#### What behavior are you expecting?

The spacing between badges to be consistent. 

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v5.10.1

**Comment by AmitMY** [comment]
The spacing you see is white-space.
Doing the following, which does the same as setting all of the rows at the same line:
```html
<ion-badge style="background-color:rgb(221,59,59)">Delivery</ion-badge><!--
--><ion-badge style="background-color:rgb(79,217,182)">Excellence</ion-badge><!--
--><ion-badge *ngFor="let value of colors" [style.background-color]="value">{{value}}</ion-badge>
``` 
results with the "pure" behavior:
![image](https://user-images.githubusercontent.com/5757359/27455721-f6c06d94-57a6-11e7-84c9-11d792efa4e6.png)

so a fix would be to either use the weird `<!-- -->`, or a different hack would be to put all of the badges in a container with `font-size: 0;`
