### ISSUE TITLE
VirtualScroll inside angular2 component doesn't render virtual items

### ISSUE THREAD

**Issue by dvdbrink** [ionic-team/ionic#6632]
#### Short description of the problem:

Using VirtualScroll inside an angular2 component doesn't render the virtual items as expected. However, adding content before the tag using a virtualScroll does make the virtual items render. The workaround is outlined in the code below and in the plunker examples.

**Ionic Version:** 2.x

A component with the following template does **not** render the virtual items:

```
// test-list.html
<ion-list [virtualScroll]="items">
  <ion-item *virtualItem="let item">
      {{ item }}
  </ion-item>
</ion-list>
```

Adding any content before the list make the virtual items render

```
// test-list.html
1
<ion-list [virtualScroll]="items">
  <ion-item *virtualItem="let item">
      {{ item }}
  </ion-item>
</ion-list>
```
#### Plunker that shows an example of your issue

Example of the bug:
http://plnkr.co/edit/HUV1IDj3IxVOWOvp1KR8?p=preview

Example with the workaround:
http://plnkr.co/edit/WBGaxf61dmLaYYjxMyrB?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: empty (Windows 10 64bit)
Node Version: v6.2.0

**Comment by Natanael1234** [comment]
Same problem here.

**Comment by Athinodoros** [comment]
I have the same problem and can't use the work around because I read values from the localforage db :/ 

Any updates on this one ? 

I use ionic RC3 currently.

**Comment by justas-kuizinas** [comment]
I have the same problem but @dvdbrink  solution works 👍

**Comment by xiejiabao** [comment]
including <ion-list> in <ion-content> can solve this.
For example,
<ion-content>
<ion-list [virtualScroll]="list"></ion-list>
</ion-content>

**Comment by daveshirman** [comment]
This is still an issue.  How does this not have any input from the team?

Hello @jgw96  @brandyscarney @adamdbradley ?
