### ISSUE TITLE
Stacked setting for checkbox not working as expected

### ISSUE THREAD

**Issue by VR-Architect** [ionic-team/ionic#6642]
#### Short description of the problem:

When using the stacked setting, the label is still located to the right of the checkbox and not the top. Also the font color is black, while the font color of the inputs are grey. 

BTW, if you could give use a setting to put the label to the left of the checkbox, that would be great too!
#### What behavior are you expecting?

Label to located on top of the checkbox and matching fonts to the input controls on the same form.

**Steps to reproduce:**
1.  Insert code below and run

```
<ion-item>
    <ion-label for="is_active" stacked>Is Active</ion-label>
    <ion-checkbox id="is_active" [(ngModel)]="model.is_active"></ion-checkbox>
</ion-item>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Which Ionic Version?** 1.x or 2.x
2.0 latest beta

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v5.1.0

**Comment by brandyscarney** [comment]
> BTW, if you could give use a setting to put the label to the left of the checkbox, that would be great too!

You can use `item-right` on the checkbox to place it to the right of the label:

```
<ion-item>
  <ion-label>Checkbox right, checked, really long text that should ellipsis</ion-label>
  <ion-checkbox item-right danger checked></ion-checkbox>
</ion-item>
```

**Comment by adamduren** [comment]
@brandyscarney any update on this issue? This might not be related but it would be nice to place the label above or below in case of the checkbox which may look like this. 
![image](https://user-images.githubusercontent.com/581097/30113838-04e6c260-92e4-11e7-895a-5b98256058c2.png)

**Comment by brandyscarney** [comment]
@adamduren So that is probably not something that we will support by default in an item. There are multiple ways that you can do this though.

### Plain Checkbox

You can accomplish something similar by using a grid and just plain checkboxes:

```html
<ion-grid text-center>
  <ion-row>
    <ion-col>
      <ion-checkbox></ion-checkbox>
    </ion-col>
    <ion-col>
      <ion-checkbox checked></ion-checkbox>
    </ion-col>
    <ion-col>
      <ion-checkbox checked></ion-checkbox>
    </ion-col>
    <ion-col>
      <ion-checkbox checked></ion-checkbox>
    </ion-col>
    <ion-col>
      <ion-checkbox checked></ion-checkbox>
    </ion-col>
    <ion-col>
      <ion-checkbox checked></ion-checkbox>
    </ion-col>
    <ion-col>
      <ion-checkbox></ion-checkbox>
    </ion-col>
  </ion-row>
  <ion-row>
    <ion-col>
      S
    </ion-col>
    <ion-col>
      M
    </ion-col>
    <ion-col>
      T
    </ion-col>
    <ion-col>
      W
    </ion-col>
    <ion-col>
      T
    </ion-col>
    <ion-col>
      F
    </ion-col>
    <ion-col>
      S
    </ion-col>
  </ion-row>
</ion-grid>
```

<img width="410" alt="screen shot 2017-09-06 at 1 27 52 pm" src="https://user-images.githubusercontent.com/6577830/30125684-37e86434-9307-11e7-82f2-6e842634a126.png">

### Item

Or if you'd like to use item to take advantage of the full ripple and accessibility, you can do this with some tweaks to the HTML and Sass:

```html
<ion-grid class="checkbox-grid">
  <ion-row>
    <ion-col>
      <ion-item no-lines>
        <ion-label>S</ion-label>
        <div item-content><ion-checkbox id="sunday"></ion-checkbox></div>
      </ion-item>
    </ion-col>
    <ion-col>
      <ion-item no-lines>
        <ion-label>M</ion-label>
        <div item-content><ion-checkbox id="monday" checked></ion-checkbox></div>
      </ion-item>
    </ion-col>
    <ion-col>
      <ion-item no-lines>
        <ion-label>T</ion-label>
        <div item-content><ion-checkbox id="tuesday" checked></ion-checkbox></div>
      </ion-item>
    </ion-col>
    <ion-col>
      <ion-item no-lines>
        <ion-label>W</ion-label>
        <div item-content><ion-checkbox id="wednesday" checked></ion-checkbox></div>
      </ion-item>
    </ion-col>
    <ion-col>
      <ion-item no-lines>
        <ion-label>T</ion-label>
        <div item-content><ion-checkbox id="thursday" checked></ion-checkbox></div>
      </ion-item>
    </ion-col>
    <ion-col>
      <ion-item no-lines>
        <ion-label>F</ion-label>
        <div item-content><ion-checkbox id="friday" checked></ion-checkbox></div>
      </ion-item>
    </ion-col>
    <ion-col>
      <ion-item no-lines>
        <ion-label>S</ion-label>
        <div item-content><ion-checkbox id="saturday"></ion-checkbox></div>
      </ion-item>
    </ion-col>
  </ion-row>
</ion-grid>
```

```css
.checkbox-grid {
  .item {
    flex-flow: column-reverse;
    padding-left: 0;
  }

  .item-inner {
    padding-right: 0;
  }

  .item .checkbox {
    margin: 0;
  }

  .label {
    margin-right: 0;
  }
}
```

<img width="409" alt="screen shot 2017-09-06 at 4 14 03 pm" src="https://user-images.githubusercontent.com/6577830/30132474-7184042a-931e-11e7-84fd-ca30d0bde9f5.png">


The reason for the wrapper `div` is because the content projection for item places checkbox outside of the `input-wrapper` which it needs to be in in order to stack it properly. 

Note on this issue: this is something I will take a look at for v4, but it will most likely be resolved by the internal changes we've already made for v4 of Ionic.
