### ISSUE TITLE
iOS `cog` icon

### ISSUE THREAD

**Issue by racecarparts** [ionic-team/ionic#6668]
#### Short description of the problem:

When using tabs in iOS emulator or native device, the `cog` icon is incorrect.  It looks to be the TTF version of the fonts, as the `cog` outline icon (`f411`) works fine in the `--lab` browser rendering.  See images below in the glyph viewer.
#### What behavior are you expecting?

That the `cog` outline icon (`f411`) matches the browser rendering in an iOS emulator and native device.

**Steps to reproduce:** 
1. Add cog-outline to page
   - `<ion-icon name="cog-outline"></ion-icon>` 
   - `<ion-tab [root]="tab3Root" tabTitle="" tabIcon="cog"></ion-tab>`
2. Launch `ionic emulate ios`
3. `cog-outline` is incorrectly rendered on pages where it is used.

Browser `serve --lab`:
<img width="413" alt="browser-ios" src="https://cloud.githubusercontent.com/assets/10102926/15584000/38d1fd06-232d-11e6-851e-f994ba08009d.png">

iOS `emulate ios`
<img width="380" alt="emulator-ios" src="https://cloud.githubusercontent.com/assets/10102926/15583999/38d1d90c-232d-11e6-9b19-78244cd9c740.png">

```
<ion-tabs>
  <ion-tab [root]="tab3Root" tabTitle="" tabIcon="cog"></ion-tab>
</ion-tabs>
```

or

```
<ion-row>
  <ion-col>
    <button dark large>
      <ion-icon name="cog"></ion-icon>
     </button>
     <label>cog</label>
  </ion-col>
  <ion-col>
    <button dark large>
      <ion-icon name="cog-outline"></ion-icon>
    </button>
    <label>cog-outline</label>
  </ion-col>
</ion-row>
```

Here are some shots of the TTF glyphs from a glyph-viewer:

`cog-outline` - `f411`:
<img width="730" alt="cog-outline-ttf-glyph" src="https://cloud.githubusercontent.com/assets/10102926/15584215/721f396a-232e-11e6-9092-3a70ad5b09d5.png">

`cog` - `f412`
<img width="738" alt="cog-ttf-glyph" src="https://cloud.githubusercontent.com/assets/10102926/15584226/81d5653c-232e-11e6-86d5-5e080bedf801.png">

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.7

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.1.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by Bouzmine** [comment]
+1

**Comment by Bouzmine** [comment]
Any update on this ?

**Comment by jgw96** [comment]
@Bouzmine @wheelertom Are you all still having this issue with beta.10? Thanks for using Ionic!

**Comment by Bouzmine** [comment]
Yes

**Comment by huysamen** [comment]
+1 this is still an issue in beta.11

**Comment by Bouzmine** [comment]
@jgw96 @bensperry Could you add this to RC1 milestone and take a look at this. This bug has been there for a while and I use this icon in my tab bar so it's quite ugly (keeping me from releasing).

**Comment by marcelgoya** [comment]
Still happening in RC3. I'd need to get this fixed as well please.

**Comment by troyanskiy** [comment]
RC5 - still have the same problem

**Comment by matiastucci** [comment]
I'm still having this issue in 2.0.0 final

**Comment by tmvnk** [comment]
2.0.1 also having this issue.

**Comment by marlosirapuan** [comment]
same here

**Comment by felixus95** [comment]
Still not working..

**Comment by YannKauderer** [comment]
Still an issue today guys :/ can you fix this please ? I wanna release my app ASAP ty !

**Comment by andrewarchi** [comment]
I have this same issue. Please fix! Thanks.

**Comment by zeidlos** [comment]
Having the same issue. Any way to fix this soon?

**Comment by Nicolaidavies** [comment]
I'm also having this issue with Ionic version 4.4.0.

**Comment by igolka97** [comment]
Any news at this issue?

**Comment by zakton5** [comment]
+1 Please fix

**Comment by bensperry** [comment]
This is an old version of Ionicons and I will not be updating it. I recommend using the new version!
