### ISSUE TITLE
ion-textarea and android autocomplete don't play nicely

### ISSUE THREAD

**Issue by wli** [ionic-team/ionic#6672]
#### Short description of the problem:

Autocomplete moves cursor to the end of the line.
#### What behavior are you expecting?

The cursor should not move to the end of the line.

**Steps to reproduce:**
1. Make an ion-textarea with ngModel
2. Set autocorrect on
3. Set autocomplete on

```
<ion-textarea type="text" [(ngModel)]="_text"
              autocorrect="on"
              autocomplete="on"
              rows="8"
              placeholder="What do you need?"></ion-textarea>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
I am not modifying or watching `_text` with javascript. I only read the value after a submit button is pressed.

In addition, when typing too fast at the end of the line, I see strange behaviors with swapped letters sometimes. I've also heard of our users have a double-insertion of an autocompleted word when using a Swype-style keyboard (though this was back in beta4). Could be all related.

**Which Ionic Version?** 2.0.0.beta-7

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.8.0
Xcode version: Xcode 7.3 Build version 7D175 
```

![ezgif-2730015856](https://cloud.githubusercontent.com/assets/649892/15592216/cff8c876-2356-11e6-813d-1afe41853fb8.gif)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So, just a quick question, if your not grabbing the value of the `ion-textarea` until the user hits a submit button, then why are you using two way binding via `[(ngModel)] `?

**Comment by wli** [comment]
@jgw96 I can bypass it for this screen by just grabbing the value later, but it doesn't solve the underlying issue.

I have another screen that is set up the same way with two-way binding, but I keep track of a character count (12/30 characters remaining), and it exhibits the same problems.

**Comment by jgw96** [comment]
@wli Thanks for the info! Would you mind making a plunker that i can use to demonstrate this issue?

**Comment by wli** [comment]
@jgw96 It's just any textarea or input: http://plnkr.co/edit/CptdsTM5jMwFbfcxPupB?p=preview

**Comment by wli** [comment]
I can't figure out how to run the plunkr on my device, so it's a little difficult to verify.
