### ISSUE TITLE
Ionic2 ion-slides didChange event not triggering if animation interrupted with mouse/touch

### ISSUE THREAD

**Issue by antoineol** [ionic-team/ionic#6676]
**Platform**: browser
**version**: ionic-angular 2.0.0-beta.7
#### Short description of the problem:

When using the component ion-slides, adding a handler for the `didChange` event, the event `didChange` triggers when the user swipes to change of slide and waits until the end of the animation, but if stopping the animation with tap/press/start swiping, but still releasing on the new slide, the event `didChange` does not trigger.

**Example use-case**: I change of slides quickly and don't wait until the animation is finished before trying to go to the next slide. (In my case, slides are used to make a calendar, sliding to go to the next day).
#### What behavior are you expecting?

`didChange` always triggers when a slide changed, even if the animation was paused by the user in the middle of the change.

_**EDIT**_: when slides are quickly swiped without waiting the end of the animation, it would still trigger for each slide. Maybe not be obvious, but it would make events consistent regardless of how fast the user is swiping.

**Steps to reproduce:**
1. Create a new Ionic 2 app
2. in a page, insert a slider like `<ion-slides (didChange)="logMe($event)">` with a few slides
3. swipe and pause the animation by tapping the screen. When releasing and finishing the animation, the event is not triggered.

**Which Ionic Version?** 2.0.0-beta.7
#### Plunker that shows an example of your issue

http://plnkr.co/edit/c7N6KXP8vAkYgh5cZNo4?p=preview

Click the _Thanks!_ button, open the browser console and slide as described before. Logs are missing if the animation is paused.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Windows 7 SP1
Node Version: v6.2.0

Thanks for the great work around Ionic btw!

**Comment by architruc** [comment]
Hi! Any update about this issue? Will it be considered in a future release? Thanks a lot.
