### ISSUE TITLE
Scroll: the elastic bounce occurs on the page rather than the ion-content

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#6755]
#### Short description of the problem:

iOS Safari ONLY

if scrolling occurs at one of the extremes, top or bottom, the elastic bounce occurs on the page rather than the ion-content. This causes the `ion-content` to lose the scroll focus causing a terrible UX experience, since the scroll looks unresponsible.
#### What behavior are you expecting?

Smooth scrolling always.

**Steps to reproduce:**
1. /e2e/button/dynamic
2. scroll to top 
3. tap a button
4. try to scroll again

Possible solution: http://www.jaridmargolin.com/bouncefix.js/

**Which Ionic Version?** 2.x

**Comment by manucorporat** [comment]
There are not way to fix this in safari, but it works great in cordova (custom web view with scroll disabled).

**Comment by manucorporat** [comment]
@jgw96 when I was debugging this issue I found that a lot of WPA for iOS have this same problem, it would be awesome if ionic could fix it!

**Comment by jgw96** [comment]
![iosissue](https://cloud.githubusercontent.com/assets/8823093/16596685/bb6757be-42ba-11e6-90a0-048c0683da05.jpg) @manucorporat agreed! Here is an example of what im seeing with the emulator, happens on my iphone 5 too

**Comment by Jimmysh** [comment]
Any progress on this?

**Comment by FanYeeChok** [comment]
We are facing the same issue. Customer complaining this
