### ISSUE TITLE
bug: Changing the browser (viewport) width resets VirtualScroll position to top

### ISSUE THREAD

**Issue by mpaland** [ionic-team/ionic#6787]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>VirtualScroll: Changing the browser (viewport) width resets the list to its top position.
No cell widths and heights are provided.

Expected: Actual list position remains stable.

Tested with v2beta7</span>

<span is-issue-template></span>

**Comment by DomiR** [comment]
Related to #6423. 

[Resize](https://github.com/driftyco/ionic/blob/de12a4e9057e2f77536911b2ae891a7d81dba04c/src/components/virtual-scroll/virtual-scroll.ts#L348) triggers [update](https://github.com/driftyco/ionic/blob/de12a4e9057e2f77536911b2ae891a7d81dba04c/src/components/virtual-scroll/virtual-scroll.ts#L364), which [resets](https://github.com/driftyco/ionic/blob/de12a4e9057e2f77536911b2ae891a7d81dba04c/src/components/virtual-scroll/virtual-scroll.ts#L378-L382) position.
