### ISSUE TITLE
Slider falters when swiping

### ISSUE THREAD

**Issue by elineopsommer** [ionic-team/ionic#6825]
#### Short description of the problem:

When swiping a slide, it falters when I release my finger. You can see it happen in the video in the included zip.
#### What behavior are you expecting?

Smooth swiping when release your finger

[bug ionic slides.mp4.zip](https://github.com/driftyco/ionic/files/306917/bug.ionic.slides.mp4.zip)

```
this._calendarOfCategorySliderOptions = {
            initialSlide: 0,
            lazyLoadingInPrevNext: true,
            lazyLoading: true,
            resistance: true,
            resistanceRatio: 0, //speed: 250,
            slidesPerView: 1,
            centeredSlides: true
        };
<ion-slides [options]="_calendarOfCategorySliderOptions"
                    (ionWillChange)="calendarItemChanged()"
                    #CalendarOfCategorySlider>
            <ion-slide *ngFor="let events of _eventsGroupedByCategories; let i=index">
                <ion-list no-lines>
                    <scroll-content class="scrollContent">
                        <ion-content #ionContent+i [attr.id]="'ionContent'+i">
                            <ion-item (click)="showDetail(event)"
                                      *ngFor="let event of events" [attr.id]="event.getSortEvent()+event.getId()">
                                <p>{{event.getSortEvent()}}</p>
                                <h3>{{event.getDate()|date:"EEEE" | translate }} {{event.getDate()|date:"d"}}
                                    {{event.getDate()|date:"MMMM" | translate }}</h3>
                                <p><span
                                        *ngIf="event.getSortEvent()!='Verjaardag'">{{event.getDate() | date: 'HH mm'}} - </span>
                                    {{event.getDescription()}}</p>

                            </ion-item>
                        </ion-content>
                    </scroll-content>
                </ion-list>
            </ion-slide>
        </ion-slides>
```

**Which Ionic Version?** 2.x
#### Plunker that shows an example of your issue

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by ladmerc** [comment]
I can confirm I'm experiencing the same. I experience about 3-5 seconds flicker before transition.

@elineopsommer How did you implement the sliding tabs? I need that feature :D

**Comment by elineopsommer** [comment]
@ladmerc I just used 2 ion-slides, one for the menu and one for the content, when the menu changes, you changes the content and vice versa ;)

**Comment by ladmerc** [comment]
@elineopsommer Thanks for the tip. Tried implementing but hit some bricks. Can I get a codepen, please?
