### ISSUE TITLE
Item: clean up the content projection

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic#6849]
The content projection has been pretty confusing. I've updated the API docs to try to explain it better, but it is still confusing that if an `ion-label` exists it will ignore any other elements but if no `ion-label` is passed it will place it inside of the `ion-label`. Discuss! :wink:

Forum discussion: https://forum.ionicframework.com/t/confused-about-ion-item-usage/54116/

**Comment by brandyscarney** [comment]
I know the point of this was so that users could write a simple item like:

```
<ion-item>
  my item
</ion-item>
```

and they wouldn't have to wrap it in an `ion-label`, but I think this is causing more confusion than writing more markup would.

**Comment by xr0master** [comment]
I think if you add examples from the forum topic in the API item documentation, it will be enough. IMO

**Comment by jgw96** [comment]
This issue is related: https://github.com/driftyco/ionic/issues/6861

**Comment by brandyscarney** [comment]
I'm going to close this issue because the documentation has been updated for item to reflect where the content is projected. For more information on the current state of being able to nest components with content projection, see this comment: https://github.com/ionic-team/ionic/issues/12252#issuecomment-317062521
