### ISSUE TITLE
Selected text not showing before user interaction in ion-select (on binding)

### ISSUE THREAD

**Issue by Bouzmine** [ionic-team/ionic#6898]
#### Short description of the problem:

If I bind a variable to an `ion-option` value, the text of the selected option won't be visible until I open it and confirm the value. This is because the value of the text is dynamic (using ng2-translate).
#### What behavior are you expecting?

The value which to appear before opening the select. 

**Which Ionic Version?** 2.x
#### Plunker that shows an example of your issue

[Here it is](http://plnkr.co/edit/4x1TcVhD154IDjrXvni3?p=preview)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us! Since this seems to be an issue related to the ng2-translate library i would suggest either asking this question on our forum (forum.ionicframework.com) or on their repo or forums. Thanks for using Ionic!

**Comment by Bouzmine** [comment]
@jgw96 this is not only related to ng2-translate. As you can see in the demo, any binding will bug the same way. Could you please reopen this ?

**Comment by jgw96** [comment]
@Bouzmine sorry about that! I will take a second look at this (:
