### ISSUE TITLE
Alert input autofocus bugs when activated by a click near keyboard on iOS

### ISSUE THREAD

**Issue by Bouzmine** [ionic-team/ionic#7007]
#### Short description of the problem:

When the button activating an alert is in the same spot as the keyboard, the input doesn't autofocus or will quickly autofocus and blur before the keyboard is opened. This issue was only tested on iOS. Here's a video showing this behavior : 

[http://sendvid.com/blvkxyb5](http://sendvid.com/blvkxyb5)
#### What behavior are you expecting?

The keyboard to always autofocus correctly.

**Which Ionic Version?** 2.x

Here's a repo to clone which reproduce this issue : [Repo](http://sendvid.com/blvkxyb5)
On a 4 inch device (iPhone 5s, for example), click on the 6th and the 7th to see this behaviour reflected (the keyboard won't autofocus). Other list elements should autofocus the alert.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by devarg** [comment]
I recently published an issue pretty similar to this. Seeing the behaviour of your case I think that inputs that require keyboard, sould not pop it until user clicks on them, or at least it would be useful to have a built-in directive like
<input type="text" **explicit-input**> so to block automatic keyboard showup in cases like this.

#7005

**Comment by devarg** [comment]
I recently published an issue pretty similar to this. Seeing the behaviour of your case I think that inputs that require keyboard, sould not pop it until user clicks on them, or at least it would be useful to have a built-in directive like
`<input type="text" **explicit-input** />`
so to block automatic keyboard showup in cases like this.

**Comment by Bouzmine** [comment]
A directive would be useful, but in the alert case it's useful to have an autofocus. The thing that's really bugging me (pun intended) is the fact the autofocus won't work correctly in some cases.
