### ISSUE TITLE
Ionic Scroll with Nested Loops ( Ionic1 -> Ionic2)

### ISSUE THREAD

**Issue by aaronksaunders** [ionic-team/ionic#7021]
I have two pens, with the same code ported from ionic1 -> ionic2

The horizontal scroll works correctly in ionic1, but in ionic2 the objects overlap each other and are not rendered correctly
#### Plunker that shows an example of your issue

**Ionic 1 version which works fine** - 
http://plnkr.co/edit/Ttiqqh5d5ak10iLbofy6?p=preview

**Ionic 2 overlap of the images when window is compressed** 
http://plnkr.co/edit/ynVMwAXQt8sJsEJABp41?p=preview

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us, and thanks for providing the plunkers! I have confirmed this issue and will be looking more into it. I think theres a slight chance this is an Angular issue, but im not sure. Thanks for using Ionic!

**Comment by aaronksaunders** [comment]
I have another plnkr of this working plain ole angular2

**Comment by jgw96** [comment]
@aaronksaunders ahh ok, would you mind posting that plunker for me to see? Thanks!

**Comment by aaronksaunders** [comment]
https://jsfiddle.net/Aaronksaunders/Lpct16k5/
