### ISSUE TITLE
More native ion-searchbar and ion-list on iOS

### ISSUE THREAD

**Issue by Bouzmine** [ionic-team/ionic#7053]
#### Short description of the problem:
- [ ] Hidden searchbar (iOS) 

Could be implemented as a directive on `ion-content`

Video : [http://sendvid.com/llj8kmm6](http://sendvid.com/llj8kmm6)
- [ ] Sliding up searchbar animation (iOS)

I think it should be the default behavior on iOS.

Video : [http://sendvid.com/69f05din](http://sendvid.com/69f05din)
- [ ] Lines for empty items and scrolling (iOS)

Could be implemented as a directive on `ion-content`

Video : [http://sendvid.com/32vz08ph](http://sendvid.com/32vz08ph)
#### What behavior are you expecting?

A more native `ion-searchbar` and `ion-list`.

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#242
