### ISSUE TITLE
Ionic 2 Popover: Toolbar within ion-header or ion-footer doesn't stay fixed

### ISSUE THREAD

**Issue by szerner** [ionic-team/ionic#7098]
In a scrollable Popover (content size is larger than the window of the popover), a `<ion-toolbar>` within `<ion-header>` or `<ion-footer>` scrolls together with the content.

The toolbar should stay fixed on its relative position (top resp. bottom).

Popover template (with title and button to close):

```
<ion-header>
    <ion-toolbar>
        <ion-title>{{name}}</ion-title>
        <ion-buttons right>
            <button (click)="closeInfo()">
                <ion-icon name="close"></ion-icon>
            </button>
        </ion-buttons>
    </ion-toolbar>
</ion-header>
<ion-content>
    <p [innerHtml]="description"></p>
</ion-content>
```

Tested with Ionic 2 beta.10 on Android and Chrome browser.

Your system information:

```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS:
Node Version: v5.11.1
```

**Comment by jgw96** [comment]
Probably related to this issue: https://github.com/driftyco/ionic/issues/7084

**Comment by BradyLiles** [comment]
Is there any update on this? Seems to still be an issue in RC1

**Comment by jbagaresgaray** [comment]
Any update for this bug??

**Comment by BradyLiles** [comment]
Any update for this bug???

**Comment by szerner** [comment]
Meanwhile I tried to switch from Popups to Modals, but then I lose the [ability to style them individually](https://github.com/driftyco/ionic/issues/10020)...

**Comment by paragw09ckp** [comment]
Looks like it has not been fixed yet. Any idea if is in the plans?

**Comment by paragw09ckp** [comment]
Interesting, looks like this bug is still not fixed. A timeline would help. Thanks.

**Comment by siphiwe** [comment]
Bump.

**Comment by sarahtully** [comment]
For now I fixed this issue using ion-scroll: `<ion-content><ion-scroll scrollY="true">...</ion-scroll></ion-content>` and then using scss: `ion-scroll { height: calc(100vh - 68px)}` In our case .popover-content has a `height: 100%; max-height: calc(100% - 12px)`. So to get the available scroll height it's 100vh - 68px (68px = 56px (ion-header height) + 12px (amount subtracted from the .popover-content height)); Hope this helps some of you resolve this issue while the Ionic team works on a resolution.
