### ISSUE TITLE
virtualScroll with sortBy (or any other) pipe

### ISSUE THREAD

**Issue by lordgreg** [ionic-team/ionic#7103]
#### Short description of the problem:

Having an un-ordered list, I've decided to used pipe, which sorts my array by key and order (desc or asc). VirtualScroll doesn't take the ordering in consideration if you're filing your array from http responses (meaning it takes a bit longer to load). 
#### What behavior are you expecting?

VirtualScroll SHOULD properly take all pipes in consideration when loading items from array.

**Steps to reproduce:**
1. Have array of 50 elements (add them into array with loop using timeout of 100ms to duplicate the behavior of server responses. An element of your array should be set as:

```
this.items:Array<any> = [];
let item:any = {
  id: index,
  date: Date.now(),
  text: random
}
```
1. Have a pipe that sorts your array by key:

```
import {Pipe, PipeTransform} from '@angular/core';

@Pipe({
  name: 'orderBy'
})

export class OrderBy implements PipeTransform {

  transform(value: Array<any>, ...args) {
    if (value && args[0]) {
      let type = args[1] ? args[1] : 'asc';
      let key = args[0];

      let ordered = value.sort((a: any, b: any) => {
        if (a[key] > b[key] && type === 'asc') {
          return 1;
        }
        else if (a[key] > b[key] && type === 'desc') {
          return -1;
        }
        else if (a[key] < b[key] && type === 'asc') {
          return -1;
        }
        else if (a[key] < b[key] && type === 'desc') {
          return 1;
        }
        else {
          return 0;
        }
      });

      console.log(ordered);

      return ordered;
    }

    return value;
  }
}
```
1. Check the output of pipe with console log so you will see it sorts the array properly.
2. Use the pipe within your template and @Component:

```
[virtualScroll]="(items | orderBy:'time':'desc')"
```
1. You will see that, as soon as the page is rendered, it will show the results as they-are and won't wait for the array to be filled and ordered.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Suggestion? As I've found out from Ionic1/Angular1, there are some variables that have to be added to ionic as they are, without angular manipulation (ionic1: scroll on ion-content has to have `false` or `true` and not `{{myVar ? true : false}}`). So VirtualScroll shows the same behavior as Ionic1 quirks. Not much has changed :(

**Which Ionic Version?** 1.x or 2.x
Ionic2 beta9

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.2.0

Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS:
Node Version: v5.9.1
```
### UPDATE (5th july 2016)

I've added Plunker which represents this issue: http://plnkr.co/edit/sEZ3ZeeSYD8ygqGmOR5d?p=preview

**Comment by daveshirman** [comment]
@jgw96 The issue referenced above is not a duplicate of this issue.  Please double check my wording and explanation and reassess.

**Comment by jgw96** [comment]
@daveshirman sorry about that! I reopened your issue with an explanation of why i had closed it as a duplicate.

**Comment by TimeTravelersHackedMe** [comment]
any update on this?
