### ISSUE TITLE
ionic 2 popover Scroll not smooth and popover not close on Android Kitkat 

### ISSUE THREAD

**Issue by Malkiat-Singh** [ionic-team/ionic#7148]
I am using Ionic Beta 9 
Popover working fine on browser  with ionic serve 
Also working on iOS Simulator but having issue on android with kitkat OS . 

Not able to close the popover after select and Scroll is not smooth

Also Delay to comes up the popover

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Are you using crosswalk with your app?

**Comment by Malkiat-Singh** [comment]
no I am not using crosswalk :( Do I need to ?

**Comment by Malkiat-Singh** [comment]
Also Crosswalk is solution for Android only but what that issue stiil on IOS

**Comment by jgw96** [comment]
Hmm, would you be able to make a plunker or a repo that i can use to reproduce this issue with? Thanks!

**Comment by Malkiat-Singh** [comment]
Will do after my working hours .. otherwise angry on me :)

**Comment by Malkiat-Singh** [comment]
You can try code from 
https://github.com/driftyco/ionic-preview-app/tree/master/app/pages/popovers

**Comment by Malkiat-Singh** [comment]
What If I will give you access to my repo ... you can check on my repository
Please send Your username ... I will give you access

**Comment by jgw96** [comment]
Hello, is this still an issue?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
