### ISSUE TITLE
Keyboard overlaps the text input when the input is placed inside an <ion-footer>

### ISSUE THREAD

**Issue by chrskrchr** [ionic-team/ionic#7149]
#### Short description of the problem:

When an `<ion-input type="text">` is placed inside an `<ion-toolbar>` in an `<ion-footer>`, the iOS keyboard overlaps text inputs placed in an `<ion-footer>` and the entire page "jumps" when the input receives focus.

![keyboard](https://cloud.githubusercontent.com/assets/805780/16504945/3aaa4ce0-3ee0-11e6-8d14-89f78da3d1e1.gif)
#### What behavior are you expecting?

I would expect the text input to be shown above the keyboard so the user can see what they're typing, similar to what happens in the Messages app on iOS.  I also wouldn't expect the entire page to jump down immediately after the input receives focus.

**Steps to reproduce:**
1. Create a new project with the `blank` template
2. Add the following to `home.html`, run the app on iOS, and focus on the text input

```
<ion-footer>
    <ion-toolbar>
        <ion-input type="text" placeholder="Add a message..."></ion-input>
    </ion-toolbar>
</ion-footer>
```

**Which Ionic Version?** 1.x or 2.x
2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by chrskrchr** [comment]
Here's a .zip of a project that demonstrates the issue.

[keyboard.zip](https://github.com/driftyco/ionic/files/342424/keyboard.zip)

**Comment by AdrianTeh** [comment]
+1

**Comment by thomas1511** [comment]
+1

**Comment by jalef** [comment]
any news on this?I have the same issue, but not only when the input is in a footer
This is a plunker that if built in android device demonstrates the problem
[http://plnkr.co/edit/GFOUnEeitVpF6o8GSAxU?p=preview](url)

**Comment by Vasanth19** [comment]
any workaround till this gets fixed?

**Comment by babinc** [comment]
I am having the same issue. I need a fix ASAP. My app is already in production. I have a text input inside a <ion-footer-bar> It works fine on android. But on IOS the keyboard covers up the text input area.

**Comment by chrskrchr** [comment]
@babinc,
My temporary workaround was to replace the `<ion-input type="text">` with a plain `<input type="text">` and use the following CSS to give it a similar look and feel:

```
    input.messageDraft {
        width: 100%;
        background-color: transparent;
        border: none;
    }
```

I haven't seen any negative side effects using a regular input in place of the ion-input.

**Comment by curtisblanchette** [comment]
@chrskrchr the nice thing about <ion-input> is it allows the user to "blur" the input when tapping outside on iOS. in ionic 1 we implemented a directive to handle the blur on click outside to hide the keyboard. Curious if you found another solution to this?

**Comment by kuldeepantil** [comment]
I am facing the same issue.

**Comment by tianleios** [comment]
i have same issue. but android is good. this problem only appear  ios.  i have opend this problem.
this problem will resolve at beat12   ?????.

**Comment by borys** [comment]
+1

**Comment by borys** [comment]
Solution with changing ion-input to input doesn't work for me (ionic beta 11). My workaround, in app.ts, constructor, platform is ready:
```
if (platform.is('ios')) {
  let 
	appEl = <HTMLElement>(document.getElementsByTagName('ION-APP')[0]),
	appElHeight = appEl.clientHeight;

  Keyboard.disableScroll(true);

  window.addEventListener('native.keyboardshow', (e) => {
	appEl.style.height = (appElHeight - (<any>e).keyboardHeight) + 'px';
  });
  
  window.addEventListener('native.keyboardhide', () => {
	appEl.style.height = '100%';
  });
}
```
I'm scaling whole app when keyboard shows - it seems be working. 
I may add few words from me: when I open app on ios and focus on input in footer - keyboard covers footer. When I lose focus clicking on button (it doesn't happen when click on f.e. header) - keyboard hides, footer goes up first (it is placed above keyboard, when it was opened) and then goes again down (it happens really quickly). It looks like bug is connected with triggering. I hope it helps...

**Comment by Manduro** [comment]
I've posted my similar solution [here](https://github.com/driftyco/ionic/issues/5432#issuecomment-246996098).

**Comment by flyfj** [comment]
this happens to me even I'm just using <input> and in ionic v1

**Comment by rdlabo** [comment]
This happens too.

This is work.
`<ion-input type="text">` -> `<input type="text">`

This can't work.
`<ion-input type="text">` -> `<div contenteditable='true'></div>`

**Comment by corran2go** [comment]
Sadly this is still open in 2.0.0 on iOS devices

**Comment by jgw96** [comment]
Hello all! We are currently working with the chrome team on this issue. This is a pretty hard problem to solve because it dives into how keyboards interact with webviews, which is all on the native OS side of things. In the meantime there is this plugin https://github.com/EddyVerbruggen/cordova-plugin-native-keyboard which gives you a native chat input that works around the issue.

**Comment by dalemugford** [comment]
I appreciate that there's a plugin that works around the issue, but that plugin is $199USD, and as far as I can tell doesn't have typings for Ionic 2.

**Comment by shaarawy130** [comment]
I have the same problem.. any solution yet?

**Comment by alexmady** [comment]
Is there any update on this issue yet please? I first raised this with @mhartington a while ago and this really has been a very longstanding issue now. 

I put a lot of effort into demonstrating the issue here (https://github.com/driftyco/ionic/issues/5432
) but it seems that this has been close for a while. 

Ionic team - this is a really important issue for my apps - please can we have an update.

Apologies if I am unaware of a fix or workaround that has gone in. 

Look forward to hearing from you.

**Comment by Tiwaz89** [comment]
I'm my particular situation I had an input in `.bar-footer`. The following CSS seemed to fix the issue:

```
body.keyboard-open.platform-ios .bar-footer {
    bottom: 36px;
}
```

NOTE: There is a bit of a delay before `.bar-footer` jumps up above the keyboard because of there being a delay before the `.keyboard-open` class gets attached to the `body`.

But then when you start typing you'll notice that your text isn't reflecting in the input field. That's thanks to the "fix" Ionic puts in place for "some keyboard issues while scrolling". To disable this you can do the following:

```
window.ionic.tap.cloneFocusedInput = function () {
	return null;
};
```

That will overwrite and disable cloned inputs.

**Comment by alexmady** [comment]
Thanks @Tiwaz89 - any idea how to get the keyboard to stay open in-between messages. Problem demonstrated in gif below. 

Also both autocomplete and spellcheck options for the ion-input do not work....

![keyboard](https://cloud.githubusercontent.com/assets/6646394/25242450/93ad6dec-25f1-11e7-8647-254ddd4ba4ed.gif)

**Comment by jdnichollsc** [comment]
@alexmady check the following example https://github.com/jdnichollsc/Ionic-ElastiChat-with-Images

**Comment by maksengc** [comment]
import { Keyboard } from '@ionic-native/keyboard';
import { Component, ViewChild, Renderer2 } from '@angular/core';

@Component({
    templateUrl: 'chat.html',
    providers: [Keyboard]
})
export class ChatPage {
    @ViewChild(Content) content: Content;
     ....

ngAfterViewInit() {
        if (this.platform.is('ios') && this.platform.is('cordova')) {
            this.keyboard.disableScroll(true);
            this.keyboard.hideKeyboardAccessoryBar(true);
            this.keyboard.onKeyboardShow().subscribe(
                (e) => {    
                     let p = this.renderer.parentNode(this.content.getNativeElement());
                     let h = this.platform.height() - e['keyboardHeight'];
                     this.renderer.setStyle(p, 'height', h + 'px');
            });
            this.keyboard.onKeyboardHide().subscribe(
                (e) => {
                    let p = this.renderer.parentNode(this.content.getNativeElement());
                    this.renderer.removeStyle(p, 'height');
            });
 ....

**Comment by blacksmith77** [comment]
Found a solution here: https://stackoverflow.com/questions/32730171/ionic-footer-input-field-being-hidden-by-keyboard-in-chat-app

set "fullscreen" property to value "false" in config.xml

> 
> This goes out out to anyone that's had a similar problem with the ionic footer and inputs in cordova build. If you have this preference in config.xml
> 
>  <preference name="fullscreen" value="true" /> 
> 
> The keyboard will hide the input when it's activated. If you absolutely need to see that input when typing (that was a joke) than just set it to false and it should solve the problem.

**Comment by royalcheeseburger** [comment]
Anything better than a workaround or third-party solution?

**Comment by kiranNegiloni** [comment]
@Tiwaz89 : Can you please help where I need to place this code?
window.ionic.tap.cloneFocusedInput = function () {
    return null;
};
I am currently facing lag during the input as the footer takes time to appear on top of keyboard.

**Comment by justgeek** [comment]
This worked for me, assuming all you ion-input are wrapped with ion-content. Pure JS works with Typescript as well.

```
  var ionInputs = document.querySelectorAll("ion-input");
  Array.prototype.forEach.call(ionInputs, function (e) {
    e.addEventListener("focus", function (e) {
      let scroll=this.offsetTop;
       this.closest(".scroll-content").scrollTop=scroll;
      
    }, true);
  })
```

**Comment by sohandhaindwal** [comment]
I resolved this bug with my logic for all ionic 1 and ionic 2
$scope.checkheight = function(){
		console.log("BEFORE window.innerHeight",window.innerHeight)
		var new_height 		= window.innerHeight;
		var keyboard_height =  (old_height - new_height) ;
		$('.bar-footer').css('bottom',keyboard_height+'px')
		keyboard_height 	= (keyboard_height + 50) ;
		$('.chat-main').css('bottom',keyboard_height+'px')
        $ionicScrollDelegate.scrollBottom();
	}
keyboard =  $interval(function () {
			$scope.checkheight();
		}, 300);

Call this function into interval interval always check your keyboard height and showing your keyboard with input 
Thanks

**Comment by jdnichollsc** [comment]
take care using intervals, @sohandhaindwal you can degrade app performance...

**Comment by sohandhaindwal** [comment]
@jdnichollsc I was just give a logic , you can achieve this  without interval. like on focus or etc.

**Comment by onedou** [comment]
Ig is fixed?

**Comment by yaozuwang** [comment]
so I am still having this problem, any fix?

**Comment by rdlabo** [comment]
This directive worked for me at iOS11 & iPhoneX.

https://gist.github.com/rdlabo/942671d8c9cffb02676756cdd56aa1c0

**Comment by yaozuwang** [comment]
@rdlabo Thanks, i just tried that, it works great, but the header seems to slide with the content initially, is that how it works?

**Comment by rdlabo** [comment]
> the header seems to slide with the content initially
@yaozuwang  Sorry. I can't fix this problem... I expect you will fix !

**Comment by yaozuwang** [comment]
@rdlabo lol ok hahaha

**Comment by sohandhaindwal** [comment]
use ionic UI plugin for this issue ionic 2 provide default but ionic 1 not so you have to manually install this
thanks

**Comment by jeffminsungkim** [comment]
Any solutions for this issue guys?

**Comment by andreas-aeschlimann** [comment]
I could not reproduce the error, but I have a bad result when the keyboard is changed to "emoji". The keyboard height is bigger then and it overlaps the input and does not push it up at all.

**Comment by jeffminsungkim** [comment]
Thanks for the response.
I've posted our current issue here.
https://stackoverflow.com/questions/47948642/ionic-keyboard-overlaps-a-focused-text-input-on-ios-11
I hope someone could help us.
ᐧ

2017-12-23 10:31 GMT+09:00 Andreas Aeschlimann <notifications@github.com>:

**Comment by BorntraegerMarc** [comment]
@jgw96 you said quite some time ago that you are looking into the issue with the chrome dev team. Has there been any more insights?

**Comment by capcom-r** [comment]
I just joined the party and I can't believe how long everyone has been waiting on this. This seems like such an essential thing to get right. How have people been dealing with this in the meantime?

**Comment by renjithvk** [comment]
@borys You saved my day!!!! Good job, thanks https://github.com/ionic-team/ionic/issues/7149#issuecomment-246965922

**Comment by dulcelariz** [comment]
I have a related issue with the keyboard, first I had the problem with the overlaps on footer and after installing the plugging XKWebView the footer doesn't be hidden anymore, but when keyboard is open an space is added above it (between keyboard and footer)

Here is the image:
![img_0524b168f6a6-1](https://user-images.githubusercontent.com/5373272/34743016-de8cab62-f54d-11e7-8c51-f84f7007133b.jpeg)


Have someone this issue? How can I fix it?
I'm new on development with Ionic. Help!

**Comment by renjithvk** [comment]
@dulcelariz You can fix that by disabling the keyboard scroll.

1. Install ionic native keyboard plugins
```
$ ionic cordova plugin add ionic-plugin-keyboard
$ npm install --save @ionic-native/keyboard
```

2. Disable keyboard scroll in your component `constructor` or in `ionViewDidLoad` observer
```
this.keyboard.disableScroll(true);
```

That's it.

**Comment by dulcelariz** [comment]
@renjithvk thanks for your help, I did what you said and the issue still there. 😢

**Comment by renjithvk** [comment]
@dulcelariz I had that kind of issue. I fixed it by did that. Please try:

Disable scroll assist in ionicModule
```
IonicModule.forRoot(MyApp, { scrollAssist: false }),
```

**Comment by dulcelariz** [comment]
@renjithvk I tried what you did and the issue continue happening

This is my ionic info:
Will it be related to this?
![screen shot 2018-01-11 at 3 41 56 pm](https://user-images.githubusercontent.com/5373272/34848923-40df231e-f6e6-11e7-9658-5eb6f7f19d87.png)

**Comment by renjithvk** [comment]
@dulcelariz I'm sorry to hear that. I'd solved by did that. 

This is my ionic info. 
![screen shot 2018-01-12 at 10 21 34 am](https://user-images.githubusercontent.com/11629673/34860386-0b45bf54-f783-11e7-9964-98efeabc5c93.png)

**Comment by MiguelHernandezCh** [comment]
Still working with ionic 3 with @borys  solution (https://github.com/ionic-team/ionic/issues/7149#issuecomment-246965922)

Ionic Info
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.9.3
    npm        : 5.7.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : Users/gobae/Library/android/sdk

Misc:

    backend : pro
```

**Comment by Ross-Rawlins** [comment]
The proposed solution only applies to ios it seems but what about android? I am using the ionic cordova keyboard plugin and this isnt working.

**Comment by Hemanth-wtt** [comment]
@borys solution worked for me.But the transition is not so smooth in my case.Any way i can achieve that?

**Comment by BorntraegerMarc** [comment]
Just by installing this plugin https://github.com/ionic-team/cordova-plugin-ionic-keyboard fixed the issue for me

**Comment by caribeedu** [comment]
Add https://ionicframework.com/docs/native/keyboard/ plugin to ionic application
and add this imports in your module.ts file 

```
IonicModule.forRoot (MyApp, {
scrollPadding: false,
scrollAssist: true,
autoFocusAssist: true
})
```
