### ISSUE TITLE
Perf(Navigation): Use of visibility: hidden

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#7177]
We know `display: none` detaches a HTML node from the rendering scope completely so it's the best way to hide an element without removing it completely from the DOM, but it has negative performance implications when you need to show it again without delay.

That's the reason we keep at least two `ion-pages` at the same time, so transitions occur as fast as possible.

``` html
<ion-page hidden>...
<ion-page hidden>...
<ion-page hidden>...
<ion-page>... 
<ion-page>Last page</ion-page>
```
## Use of visibility: hidden

I tested with @danbucholtz that in backdrops the `visibility: hidden` rule does not have the performance penalty of `display: none` so we could use it in the previous ion-page instead of leaving it completely visible. See https://github.com/driftyco/ionic/commit/cb1cacab424a76847d33ff011e94e3a361c6e30f#diff-9422c4bf23326f470bb409e7ed77948dR25

``` html
<ion-page hidden>...
<ion-page hidden>...
<ion-page hidden>...
<ion-page style="visibility: hidden">... 
<ion-page>Last page</ion-page>
```

I think this could help the UA to focus rendering resources in the REAL visible content, improving performance. Thoughts @adamdbradley ?

**Comment by John-Luke** [comment]
I think this test (visibility: hidden) can be used in whole components to improve the performance or I'm talking bullshit?
