### ISSUE TITLE
Unnecessary padding for ion-item when creating inputs

### ISSUE THREAD

**Issue by oktav777** [ionic-team/ionic#7204]
#### Short description of the problem:

Here is a demo that shows how it looks with and without padding
![screenshot_1](https://cloud.githubusercontent.com/assets/5902211/16580386/ddb68be0-42ac-11e6-9102-caa274ffd7fe.png)

The padding for `ion-item` is unnecessary when it's a parrent for an `ion-input`, I have read the specs of Material design and there is no additional padding for text/inputs. Same I guess is for ios.

``` html
<ion-item>
    <ion-label primary floating>Username</ion-label>
    <ion-input placeholder="Some text"></ion-input>
</ion-item>

```

probably this should fix it, if this padding is not for other components 

``` css
ion-item.item-input {
    padding-left: 0;
}
```

**Which Ionic Version?** 1.x or 2.x ionic2 beta.10

**Comment by karlschwaier** [comment]
I am also wondering why this padding is defined.
Your fix removes it just from ``.item-input``, but it's still for ``.item-select``, ``.item-checkbox``, ``.item-datetime`` and others.

Using selector ``.item`` would interfere with http://ionicframework.com/docs/v2/components/#menus, but ``ion-item`` seems to be fine.

**Comment by cabralRodrigo** [comment]
Bump

**Comment by yordis** [comment]
Any updates on this @brandyscarney  ?

**Comment by brandyscarney** [comment]
I'll add this as something to look at as part of v4, but for now please use a css workaround. This will become easier to customize in v4, as well. Thank you!
