### ISSUE TITLE
v2:bug(Modal): Android back button doesn't invoke onDismiss

### ISSUE THREAD

**Issue by DavidWiesner** [ionic-team/ionic#7224]
#### Short description of the problem:

If I create a `Modal` an add an `onDismiss` listener. This won't be called if you press the back button on Android. 
#### What behavior are you expecting?

`onDismiss` should also be called when I hit the Backbutton on Android

**Steps to reproduce:**
1. Create an Modal and add `onDismiss` listener with e.g.: an `alert` call
2. Open modal
3. press the back button
4. no alert will be opened :cry: 

```
    let modal = Modal.create(Page1);
    this.greeting="";
    modal.onDismiss(()=>{
     alert("onDismiss called")
    });
    this.nav.present(modal);
```

**Which Ionic Version?**  2.0-beta.10
#### Plunker that shows an example of your issue

http://plnkr.co/edit/xZTtaAmv9D0JLugGIuXy?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS: Distributor ID: Debian Description: Debian GNU/Linux 8.5 (jessie) 
Node Version: v5.12.0

**Comment by jlsuarezs** [comment]
Any solution?

I have the same issue. :(
