### ISSUE TITLE
bug: select is not checking the option with checked on it

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic#7334]
The following test failed on snapshot: select/single-value

Relevant code:

```
<ion-item>
  <ion-label stacked>Label 6</ion-label>
  <ion-select [(ngModel)]="gender">
    <ion-option value="f" checked="true">Female</ion-option>
    <ion-option value="m">Male</ion-option>
  </ion-select>
</ion-item>
```

![screen shot 2016-07-15 at 5 42 22 pm](https://cloud.githubusercontent.com/assets/6577830/16889351/b94a6b78-4ab3-11e6-898a-ab9b78396a02.png)

**Comment by Kobzol** [comment]
I'm curious as to how this should behave. Let's say that the gender variable would be "m" in this situation. What should the select after initialization? Check "f" or "m"? Or set "gender" to "f" directly?

**Comment by brandyscarney** [comment]
@Kobzol That's true. I created this issue because it used to work, but it seems like a `select` element in an Angular 2 application behaves the same way. Here are my findings:

1) A native `option` element uses `selected` not `checked`: `<option value="all" selected>`
2) Native and Angular `select` elements with nothing `selected` choose the first option by default.
3) In a plain Angular app if you have the following it checks the last one:

```
<select>
  <option value="all">All</option>
  <option value="paid">Paid</option>
  <option value="free" selected>Free</option>
</select>
```

4) but if you add `ngModel` then it won’t select any of them unless you set the variable to one of the values in the component:

```
export class AppComponent {
  apps: string = "paid";
}
```

Here's a sample plunker that can be modified to show the above: http://plnkr.co/edit/x14JI1KGB4hUzpB9AYac?p=preview

**Comment by Kobzol** [comment]
I guess it's a reasonable behaviour to give precedence to the ngModel. Though Ionic's `ion-select` could emit a warning if there's a `selected` directive present with ngModel set (if that situation can be detected).

**Comment by mmazloum** [comment]
Hi,

I encounter similar problems with my ion-select components. for example : 
`            <ion-item>
                <ion-label>Pays</ion-label>
                <ion-select formControlName="countryCode" [ngModel]="appService.appDatas.currentAddress.countryCode">
                    <ion-option *ngFor="let code of countryCodes" value="{{code.iso2}}">{{code.name}}</ion-option>
                </ion-select>
            </ion-item>`

When built on targets iPhone or Galaxy sometimes I get **selection** issues, sometimes the **scroll** is not fluid or keeps frozen inside the select, sometimes everything works fine, it doesn't look like a performance issue because nothing heavy is running in the background of my app or my phones.

**Comment by Caff00** [comment]
why this dosent work but work with the `checkbox`
  <ion-item>
     
     <ion-label>max</ion-label>

      <ion-select [(ngModel)]="data.prixmax">
        <ion-option checked="true"value="1000">1000</ion-option>
        <ion-option value="2000">2000</ion-option>
        <ion-option value="3000">3000</ion-option>
        </ion-select>
      
    </ion-item>

**Comment by abrseq** [comment]
till now no solution found???

**Comment by abrseq** [comment]
what i did was after executing all the functions in the ionChange event i made [(ngModel)] value null..
After that its working fine

**Comment by brandyscarney** [comment]
I have tested this in the v4 version and I am no longer able to reproduce this:

<img width="434" alt="screen shot 2018-02-22 at 4 54 13 pm" src="https://user-images.githubusercontent.com/6577830/36566339-3024c836-17f1-11e8-8d67-3d00738a9539.png">

<details>

```
  <ion-row>
    <ion-col>
      <label for="stdSelect">Select</label>
      <select id="stdSelect" name="stdSelect" [(ngModel)]="selectValue" placeholder="YYYY-MM-DDTHH:mm:ssZ" [disabled]="disableInputs">
        <option value="bacon">Bacon</option>
        <option value="pepperoni">Pepperoni</option>
        <option value="ham" selected>Ham</option>
        <option value="sausage">Sausage</option>
        <option value="pineapple">Pineapple</option>
      </select>
    </ion-col>
    <ion-col>
      Value:
      <span id="selectOutput">{{selectValue}}</span>
    </ion-col>
  </ion-row>
  <ion-row>
    <ion-col>
      <ion-item>
        <ion-label>Ionic Select</ion-label>
        <ion-select id="ionSelectInput" [(ngModel)]="selectValue" [disabled]="disableInputs">
          <ion-select-option value="bacon">Bacon</ion-select-option>
          <ion-select-option value="pepperoni">Pepperoni</ion-select-option>
          <ion-select-option value="ham" selected>Ham</ion-select-option>
          <ion-select-option value="sausage">Sausage</ion-select-option>
          <ion-select-option value="pineapple">Pineapple</ion-select-option>
        </ion-select>
      </ion-item>
    </ion-col>
  </ion-row>
```

</details>

<br>

Please note that the correct property is `selected` _not_ `checked`. I am going to close this as it will be fixed in v4.

**Comment by saiprasad2595** [comment]
I did workaround.In constructor i have set ngModel value for which i thought of keeping default selected value.

```
<ion-select [(ngModel)]='selectBox'>
    <ion-option value='male'>Keep data from view</ion-option>
     <ion-option value='female'>Remove data from view</ion-option>
</ion-select>

---
constructor(){
 this.selectBox = 'male';
}

---
```
This way default value is getting selected
