### ISSUE TITLE
ion-list has mysterious 32px margin-bottom on iOS

### ISSUE THREAD

**Issue by martinjbaker** [ionic-team/ionic#7366]
For some reason there's a 32px margin-bottom applied on ion-list which causes an unnecessary gap after the last item.

Best seen by scrolling the list to the bottom on the demo page:
http://ionicframework.com/docs/v2/components/#lists

Ionic 2 beta 10

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This is actually by design as this is how the lists look on the native platforms. You can read more about it [here](https://github.com/driftyco/ionic/issues/6307). Thanks for using Ionic!

**Comment by biesbjerg** [comment]
Can you provide more info? I've been wondering about the gap too. I don't see a gap in lists on iPhone's native phone app, App Store etc?

**Comment by martinjbaker** [comment]
Sorry but at least on iOS that isn't the case. I made an example project in Xcode with a UITableView and there's no gap within the bounds of the tableview when it is scrolled to the bottom. The last item is aligned to the bottom of the tableview. See screenshot and attached project.

![uitableview](https://cloud.githubusercontent.com/assets/1586504/16975647/6253cafe-4e40-11e6-80e7-61abec53a005.png)
[SimpleTableView.zip](https://github.com/driftyco/ionic/files/372893/SimpleTableView.zip)

**Comment by martinjbaker** [comment]
Also worth mentioning that this problem is new in Ionic 2. I'm converting an Ionic 1 app at the moment and previously didn't have to set margin-bottom to 0 on ion-list.

**Comment by mpaland** [comment]
I'm facing the same issue due to
```css
ion-list {
  margin: -1px 0 32px 0;
}
```
in .ios.css
I know this margin should be a fix but isn't there a smarter solution? This big gap is really unwanted if other elements are below the list.

@jgw96 might you reopen this issue?

**Comment by jgw96** [comment]
Thanks for responding everyone! I have reopened this issue and will be discussing this with our design people.

**Comment by pietro909** [comment]
Hi, are there any updates? At least a suggestion about the best practice of how to fix it at a global level for the three different platforms. 

Thanks

**Comment by MessiasLima** [comment]
Set this variables in variables.scss

$list-ios-margin-bottom : 0px;
$list-md-margin-bottom : 0px;
