### ISSUE TITLE
hideBackButton attribute hides the menuToggle button too

### ISSUE THREAD

**Issue by HamzaLJ** [ionic-team/ionic#7417]
**The Problem**
I push the **Root Page** to **Page2** that supports a side menu, the issue is that when it opens **Page2** it shows the **back button** and hides the **menu button** for that I've tried to add `hideBackButton` to **Page2** in order to see the **menu button** but I both the **back button** and  **menu button** disappeared!

Here is my current code:

```
  <ion-navbar hideBackButton>
       <button menuToggle start>
       <ion-icon name="menu"></ion-icon>
       </button>
 </ion-navbar>
```
#### What behavior are you expecting?

Should hide the **back button**, and show the **menu button**.

**Which Ionic Version?** 
Ionic2

Cordova CLI: Not installed
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by esqew** [comment]
Having this issue as well, my code is similar:

`Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v6.3.0`

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by esqew** [comment]
I know you asked for a plnkr; I hope a CodePen will suffice. https://codepen.io/esqew/pen/QExGrE

The toggleMenu button is displayed on the first page - after clicking through to a list item, the left side navigation button is blank. This issue is only when using the hideBackButton directive.

**Comment by jgw96** [comment]
Hello @esqew unfortunately that codepen is using a very outdated version of ionic 2. Would you be able to use [this](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) plunker to make an example? Thanks for using Ionic!

**Comment by esqew** [comment]
Hi again, I've reproduced the issue in [this plunker](http://plnkr.co/edit/9j6yZSojFq1o7x9TZscd?p=preview). When you use `this.nav.push(Page1)` the page is pushed to the navigation stack, but the `hideBackButton` directive hides the menu item that's supposed to be displayed (and is in fact displayed on the rootPage).

**Comment by neslinesli93** [comment]
Did you guys manage to solve this?
I mean, this is a really basic use case, I am surprised this issue hasn't been fixed.

When using a side menu, I want to be able to cache the views as I transition between the menu entries.
This isn't possible using nav.setRoot() as it wipes the navigation stack. That's where nav.push() comes into place, pushing the sidemenu entries into the navigation stack, thus caching the views.
However, it shows the back button along with the menu toggle. The ion-navbar property hideBackButton seems perfect for this, but it hides both the back button AND the menu toggle.

How are we supposed to implement views caching when using sidemenu design? Is this a bug?
Thanks, and keep up with the good work!

**Comment by esqew** [comment]
This "basic use case" still exists in 2.1.2.

`Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X Sierra
Node Version: v7.0.0
Xcode version: Xcode 8.0 Build version 8A218a`

**Comment by esqew** [comment]
Update: if you wrap your `menuToggle` button in `<ion-buttons></ion-buttons>` it'll appear. The formatting is broken but you should be able to hack it together with a CSS `float: left;` and some `margin-top`.

**Comment by esqew** [comment]
Still not working even after updating to 2.1.2.

> Cordova CLI: 6.3.0
> Gulp version:  CLI version 3.9.1
> Gulp local:  
> Ionic Framework Version: 2.0.0-rc.1
> Ionic CLI Version: 2.1.4
> Ionic App Lib Version: 2.1.2
> Ionic App Scripts Version: 0.0.36
> ios-deploy version: 1.8.2 
> ios-sim version: 5.0.3 
> OS: Mac OS X Sierra
> Node Version: v7.0.0
> Xcode version: Xcode 8.0 Build version 8A218a

**Comment by Abhishek134** [comment]
Did anyone able to solve it?
I'm also troubling with the same.
I'm using ionic cli  V3.6.0.
ionic (Ionic CLI)               : 3.6.0
global packages:
    Cordova CLI : 7.0.1 
local packages:
    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0
System:
    Node       : v8.1.4
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    npm        : 5.0.3

**Comment by pertsenga** [comment]
This is ugly but what I did was call `this.navCtrl.setRoot(page)` twice and the menu button shows. idk why but it worked

**Comment by karmastudy** [comment]
Hi,
Using both this.navCtrl.push(page); and this.navCtrl.setRoot(page); I can see the menuToogle button, but it doesn't work. By clicking the button nothing happens.

**Comment by pevargasg** [comment]
@karmastudy 

put a clicker on the button of the menu 

```
onOpenMenu(){
    this.menuCtrl.open();    
  }
```
don't forget to import MenuController from ionic-angular and declare it in the contructor

**Comment by giovannipds** [comment]
It's also possible to avoid that with:

```sass
ion-navbar[hideBackButton] button[menuToggle] {
  display: block !important;
}
```

**Comment by pratik8490** [comment]
how to display menu i can't show menu after login screen to go home screen
