### ISSUE TITLE
Swipe back gesture on iOS and NavController.setPages doesn't scroll correctly

### ISSUE THREAD

**Issue by jvaclavik** [ionic-team/ionic#7498]
#### Short description of the problem:

If I will set navigation stack through **NavController.setPages** and then I use **gesture for getting back on iOS** there is problem with scrolling. After swiping back is not possible to scroll to the top of the page. 

![image](https://cloud.githubusercontent.com/assets/858321/17288415/5a2bd242-57d5-11e6-986b-5f9459808dce.png)

You can see it in following video:
https://dl.dropboxusercontent.com/u/25736835/swipe-back-scroll-problem.mp4

**Steps to reproduce:**
1) Create two pages - E. g. Home and Detail.
2) Implement some logic
**home.html**

```
<button (click)="showDetail()">Detail page</button>
```

**home.ts**

```
showDetail(){
  this.navController.setPages([
    {page: HomePage},
    {page: DetailPage}
  ], {
    animate: true,
    direction: 'forward'
  });
}
```

3) Try swipe back on iOS device (back button works correctly)

**Ionic info** 

Ionic version in project: 2.0.0-beta.10

**System information**

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.4 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) or repo that demonstrates this issue? Thanks for using Ionic!

**Comment by jvaclavik** [comment]
Repository is here: https://github.com/jvaclavik/ionic2-swipe-back-bug-demo

**Comment by tmvnk** [comment]
+1
https://github.com/driftyco/ionic/issues/8386

**Comment by danielrys** [comment]
Workaround using `remove()` instead of `setPages()` seems to do the right thing for me.

```
     this.nav.push(DetailPage).then(() => {
        this.nav.remove(1); // remove the page from stack instead of using setPages and leaving it out
      });
```
