### ISSUE TITLE
How to disable scroll for ion-content in ionic 2?

### ISSUE THREAD

**Issue by rhuldip** [ionic-team/ionic#7644]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/
#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Which Ionic Version?** 1.x or 2.x
#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by rhuldip** [comment]
i dont want to hijack my browser,any other option by ionic team?

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! We actually just documented a method called `setScrollDisabled` that will allow you to do this. You can see the documentation in [this](https://github.com/driftyco/ionic/commit/e244d09eaa3ca370c1ba84121b9c376a66735b21) commit. Thanks for using Ionic!

**Comment by rhuldip** [comment]
Hi,any example how can i use it?

**Comment by jgw96** [comment]
Hey @rhuldip ! Here is an example of how to use this method:

```
 import { app } from 'ionic-angular';

 constructor(private app: App) {};

 this.app.setScrollDisabled(true);
```
Hope that helps! Thanks!

**Comment by krz37** [comment]
Hi @rhuldip . As I understood on another page, you wanted to disable the scroll for <ion-content> and not for the whole app. In this case you can use :

`<ion-content [attr.noScroll]="shouldScroll"></ion-content>
`
and then your SCSS file :

```
[noScroll] {
  overflow: hidden;
}
```

credits to @mhartington for the guidance

**Comment by DrakeWitt** [comment]
Is there a directive for this? The documentation mentions it but it does not work.

**Comment by dgroh** [comment]
Below I show how this can also be solved>

Create thoses classes in some of zour scss files, i.e **app.scss**
```
.no-scroll {
    scroll-content {
        overflow-y: hidden;
    }
}

.scroll {
    scroll-content {
        overflow-y: scroll;
    }
}

```

Then just call:

`this.content.addCssClass("no-scroll");`

or

`this.content.addCssClass("scroll");`

Where content is:

`@Input("content") protected content: Content;`

Hope this helps

**Comment by haxpor** [comment]
Thanks @dgroh , it works really well on my end as of `Ionic Framework Version: 2.0.0-rc.1`.
Just curious, should `scroll-content` be `.scroll-content` as it's class? But it's not that important. Thanks again.

**Comment by 0x1ad2** [comment]
I used the following SO answer to fix it http://stackoverflow.com/a/40826366/1783311

Add this to your .scss file

```
.no-scroll .scroll-content{
     overflow: hidden;
}
```

then add the no-scroll class to your ion-content like this

```
<ion-content class="no-scroll">
..
</ion-content>
```

**Comment by iflagri** [comment]
I solved it as below.
`<ion-content><div ion-fixed></div></ion-content>`

**Comment by AjkP** [comment]
> Hello! Thanks for using Ionic! We actually just documented a method called setScrollDisabled that will allow you to do this. You can see the documentation in this commit. Thanks for using Ionic!

This does not work after RC4. Should we reopen this?

**Comment by shyamal890** [comment]
@jgw96 please consider adding this functionality, its much needed.

**Comment by theomathieubhvr** [comment]
@iflagri solution works. Thanks !

**Comment by larssn** [comment]
If anyone is still having trouble with this, add `no-bounce` to `ion-content`, and see if that fixes it.

`<ion-content no-bounce></ion-content>`

**Comment by primerproyecto** [comment]
@larssn fix it. Thanks !

**Comment by ccmolinac** [comment]
@larssn Fix it. ty!

**Comment by canhhuy88** [comment]
@ @ @ @ @ @ @ @ @ @rhuldip

**Comment by ayman-alkom** [comment]
If you don't want the scroll you may also don't need the ion-content itself, in my status for example I want to use the ion-grid directly.



    

    ion-app {
        &.md {
            .has-header {
                margin-top: $toolbar-md-height;
            }
        }
        &.wp {
            .has-header {
                margin-top: $toolbar-wp-height;
            }
        }
        &.ios {
            .has-header {
                margin-top: $toolbar-ios-height;
            }
        }
    }

**Comment by mlynch** [comment]
Need to support disabling scrolling through an attribute on <ion-content>

**Comment by pjc2007** [comment]
I have an issue on iOS, where if I have a **select** doing a scrolling gesture on it scrolls the contents underneath, so I want to disable the scroll when the select is up.

None of the above seems to work for me. I've tried the `no-bounce`, and also directly added an inline style of `style=overflow-y : hidden` just to see if this will stop the scrolling, but it doesn't.

**Comment by pjc2007** [comment]
In my case, I had to set this scroll in code, as it is the **nested** div with the class `scroll-content` that I needed to add the `overflow:hidden` to.

To do this in code, I did the following...

     @ViewChild(Content) content: Content;
      ....

      private setDisableScroll(disable: boolean) : void {       
	     let scroll = this.content.getScrollElement();
	     scroll.style.overflowY = disable ? 'hidden' : 'scroll';                    
        }

**Comment by gonzag** [comment]
@pjc2007, you made my day

**Comment by KeaganFouche** [comment]
@iflagri thank you so much! I was struggling for a few days now, the solution which worked for me was:

<ion-content>
  <span ion-fixed style="height: 100%; width: 100%">
 //all other HTML is here...
</span>
</ion-content>

**Comment by Sampath-Lokuge** [comment]
The only solution which works for me. Thanks @KeaganFouche

**Comment by sertal70** [comment]
The only working solution for me is @iflagri  one. I'm wondering why a div is needed, I tried to put `ion-fixed` directive directly on ion-content but it doesn't work.

`no-bounce` simply doesn't work all the time.

**Comment by saurabhschauhan** [comment]
Adding this in config.xml works or me.

`<preference name="webviewbounce" value="false" />
<preference name="UIWebViewBounce" value="false" />
<preference name="DisallowOverscroll" value="true" />`

**Comment by enriquerene** [comment]
I don't know why exactly you want to remove it, but if because of the fixed height of the `ion-content` when call `page-x` tags in a main html file, I solved this inserting `ion-grid` and after the page tags. Further, I removed the `ion-content` of the inner pages and all html are wrapped in `ion-row`, as my home.html (sorry, I couldn't put code in blocks, the preview always gave me inline):

`<ion-content no-padding>
    <ion-grid no-padding>
		<div class="bg-gradient-light">
			<img src="../../assets/imgs/logo.png" />
		</div>
		<page-features></page-features>
		<page-categories></page-categories>
		<page-social class="before-footer"></page-social>
	</ion-grid>
</ion-content>`

and all my `page-pageName` has this structure:

`<ion-row>
	<ion-col ...>
		
	</ion-col>
</ion-row>`

**Comment by shanemac10** [comment]
Here's how I handled it, which seems like the more natural approach to me. Just open your **src/app/app.scss** (Where your global styles _should_ live) and add...
`
.scroll-content {
		overflow-y: auto;
	}
`
Done. 

I don't know why you would want to force **scroll** or **hidden**, when your style should be dynamic to the content in most cases. If you have a special case, go ahead and hard code it, but in general, I don't understand why Ionic has this overridden to **scroll**.

**Comment by chriskuech** [comment]
Every single page has a scrollbar by default that only scrolls at most a couple pixels.  This should be considered a bug.  The `no-bounce` fix above appears to work, but should not need to be added to every non-scrolling view.
