### ISSUE TITLE
Bug: Ionic 2 - Round style does not apply to buttons in navbar

### ISSUE THREAD

**Issue by ungular** [ionic-team/ionic#7661]
How to make round buttons on navbar?
`<ion-navbar>
  <ion-buttons left>
    <button round>Home</button>
  </ion-buttons>
<ion-navbar>`

I tried this but I got a rectangular button: `<button solid round>`

**Comment by plul** [comment]
This issue is still present. Is any attention being devoted to it?

**Comment by bryan-oliveira** [comment]
+1 - Issue is still present.

**Comment by ps011** [comment]
The issue is present in ionic 3 as well.

**Comment by Piashsarker** [comment]
Ionic Version 3.20.0  , Not fixed : 

```
<ion-header>
  <ion-navbar>
    <button ion-button clear icon-only   left>
      <ion-icon name="menu" color="light"></ion-icon>
    </button>

    <ion-buttons end>

      <button ion-button round>
        <ion-icon name="star" color="light"></ion-icon>
        TAP FOR BALANCE
      </button>

    </ion-buttons>

  </ion-navbar>
</ion-header>
```

Issue Still Exist

**Comment by taofik-nos** [comment]
Still exists.
