### ISSUE TITLE
Searchbar behind a modal close button causes searchbar to focus.

### ISSUE THREAD

**Issue by tlaverdure** [ionic-team/ionic#7693]
#### Short description of the problem:

After closing a modal on top of a page with a searchbar, the click on the modal close button causes the searchbar to focus. This happens on an iOS device and emulator but not in a browser.
#### What behavior are you expecting?

Close modal without focusing the search bar behind the modal.

**Steps to reproduce:**
1. Create a page with ion-header, ion-navbar and ion-searchbar
2. Add a modal to the page with a close button in the top left.
3. Close the modal with the button and the searchbar becomes focused.

**Page** 

``` html
<ion-header>
  <ion-navbar>
    <ion-searchbar></ion-searchbar>
  </ion-navbar>
</ion-header>
```

**Modal**

``` html
<ion-header>
    <ion-toolbar>
      <ion-buttons start>
        <button (click)="close()">
           Close
        </button>
      </ion-buttons>
    </ion-toolbar>
  </ion-header>
```

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by TomasKatz** [comment]
Remove me please

**Comment by manucorporat** [comment]
@tlaverdure I confirmed this bug only happens in UIWebView. Can you try start using our WKWebView cordova plugin? https://github.com/driftyco/cordova-plugin-wkwebview-engine

You should expect a huge performance improvement.
http://blog.ionic.io/cordova-ios-performance-improvements-drop-in-speed-with-wkwebview/


I will close this a possible fix could be too complex, I don't think it would worth it.
Please reopen if you have an idea to fix this issue easily.

**Comment by tlaverdure** [comment]
@manucorporat I actually haven't had any issues with this since I did the wkwebview upgrade, it's a weird corner case so I'm fine with just using wkwebview to fix. Thanks!
