### ISSUE TITLE
Segment component auto-select with formControlName and numbers

### ISSUE THREAD

**Issue by TheBrockEllis** [ionic-team/ionic#7761]
#### Short description of the problem:

When using FormBuilder to create a form, the segment component will not auto-select the appropriate `ion-segment-button` based on the form control value **if it is numeric**. 
#### What behavior are you expecting?

A segment component that is hooked up to a model-based form with a `formControlName` would automagically select the segement that has a value that matches the control's value. This behavior works if the control's value is a string and the component's value is a string.

**Steps to reproduce:**
1. `ionic start segment-form-with-numbers --v2`
2. Create two forms and two segments in `app/pages/home/home.html`. One segment should have options where the values are strings, i.e. "one", "two" or "three". The other segment should have option values that are numeric, i.e. "123", "456", "789". 
3. Import all appropriate Angular form modules, add form directives, build two FormGroups. Each group should have one control that has either a numeric value or a string value.

`app/home/home.ts`

```
import {Component} from '@angular/core';
import {NavController} from 'ionic-angular';
import {FORM_DIRECTIVES, REACTIVE_FORM_DIRECTIVES, FormBuilder, FormArray, FormGroup, Validators, FormControl} from '@angular/forms';

@Component({
  templateUrl: 'build/pages/home/home.html',
  directives: [FORM_DIRECTIVES, REACTIVE_FORM_DIRECTIVES]
})
export class HomePage {
  public numericForm:FormGroup;
  public stringForm:FormGroup;

  constructor(public formBuilder:FormBuilder, private navCtrl: NavController) {
    this.numericForm = this.formBuilder.group({
      score: 3
    });

    this.stringForm = this.formBuilder.group({
      score: 'shiznit'
    });
  }
}
```

`app/home/home.html`

```
<ion-content padding class="home">

  <!-- Segment in a form -->
  <form [formGroup]="numericForm">
   <ion-segment formControlName="score">
     <ion-segment-button value=1>Pretty Good</ion-segment-button>
     <ion-segment-button value=2>Awesome</ion-segment-button>
     <ion-segment-button value=3>Da Shiznit!</ion-segment-button>
   </ion-segment>
  </form>

  <!-- Segment in a form -->
  <form [formGroup]="stringForm">
    <ion-segment formControlName="score">
      <ion-segment-button value="prettyGood">Pretty Good</ion-segment-button>
      <ion-segment-button value="awesome">Awesome</ion-segment-button>
      <ion-segment-button value="shiznit">Da Shiznit!</ion-segment-button>
    </ion-segment>
  </form>

</ion-content>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
@brandyscarney responded to a [forum post](https://forum.ionicframework.com/t/ion-select-with-dynamic-options/43720/10) requesting a user with a similar problem to create an issue, but I couldn't find any reference to the issue if it was created. 

**Which Ionic Version?** 1.x or 2.x
2.x
#### Plunker that shows an example of your issue

I am having 0 luck recreating the Angular 2 forms in Plunker. Here is my [latest attempt](http://plnkr.co/edit/YNqf0n?p=preview). The code is there, but the plunker doesn't work.

Here is a [git repo](https://github.com/TheBrockEllis/segment-form-with-numbers) of the code that I can run locally on my machine to replicate this issue.  

A screenshot of the issue can be seen [here](http://imgur.com/a/5hjBk).

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by jkeczan** [comment]
We are seeing the same issue with instantiated model objects as well.
