### ISSUE TITLE
Ionic2 tabs: using (ionSelect) to open ActionSheet

### ISSUE THREAD

**Issue by arsenslyusarchuk** [ionic-team/ionic#7769]
On beta.11 I still have the problem with using ActionSheet on Tabs.

```
<ion-tabs #myTabs class="nav-tabs">
  <ion-tab tabIcon="list-box" tabTitle="Receipts" [root]="receiptsRoot"></ion-tab>
  <ion-tab tabIcon="more" tabTitle="More" (ionSelect)="showMenu()"></ion-tab>
</ion-tabs>

showMenu() {
    let menuSheet = this._actionSheetController.create({
      title: 'Choose action',
      buttons: [
        {
          text: 'Logout',
          role: 'add',
          icon: !this.platform.is('ios') ? 'log-out' : null,
          handler: () => {
            menuSheet.dismiss().then(() => {
              this.logout();
            });
          }
        },
        {
          text: 'About',
          role: 'add',
          icon: !this.platform.is('ios') ? 'information-circle' : null,
          handler: () => {
            menuSheet.dismiss().then(() => {
              this.redirectToAboutPage();
            });
          }
        },
        {
          text: 'Cancel',
          role: 'cancel',
          icon: !this.platform.is('ios') ? 'close' : null
        }
      ]
    });
    menuSheet.present();
  }
```

After ActionSheet dismisses, I cannot do anything on the root tab. Any actions like edit/delete, even pull-to-refresh, don't display until I reload an app or open and the close modal. To add more, if using modal instead of actionSheet everything works good after modal dismisses.

Expected scenario: using ActionSheet on tabs with  (ionSelect), everything works after ActionSheet dismisses. (Again, all works if using modal instead)

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by arsenslyusarchuk** [comment]
To add more, when ActionSheet is dismissed none of the ionic page events are fired - like `ionViewDidEnter`. However, using modal (when it dismisses) event ARE fired.
Also when clicking such tab with (ionSelect) event, (ionChange) event on Tabs component fires. It shows such tab as non-selected

**Comment by mlynch** [comment]
Can reproduce on iOS. Doesn't happen on desktop chrome

**Comment by mlynch** [comment]
Only happens intermittently. I wonder if it's a flexbox issue

**Comment by mlynch** [comment]
I'm recommending pushing this to a later release as I don't think it's a major bug and it's going to be hard to nail down. It also relies on fairly obscure behavior. However, we should definitely still figure out what's up with it.

@arsenslyusarchuk if you have any stack traces to share when this happens we'd love to see it. Unfortunately I failed to grab one the first time it happened and I can no longer reproduce.

**Comment by arsenslyusarchuk** [comment]
@mlynch Thanks for looking at this. 
Try create 2 tabs - 1st is main page with list of items and pull-to-refresh; 2nd tab is a *button* which opens ActionSheet (smth like 'more' button).
Then, after dismissing ActionSheet you will see that 'pull-to-refresh' don't have any icons and text when pulling.
This is the easiest way to show that smth is wrong, other ways which I've mentioned, like 'edit/delete', require more code.

**Comment by arsenslyusarchuk** [comment]
@mlynch And again, when we change ActionSheet to Modal, everything is working good.
Also, I've noticed interesting thing in documentation http://ionicframework.com/docs/v2/api/components/tabs/Tab/
```
Sometimes you may want to call a method instead of navigating to a new page. You can use the (ionSelect) event to call a method on your class when the tab is selected. Below is an example of presenting a modal from one of the tabs.
```
But only modal is mentioned there - no other component (like ActionSheet, Alert and so on) )))

**Comment by arsenslyusarchuk** [comment]
@mlynch If u give me the boilerplate plunker with beta-11 Ionic (cause your default plunker is still with beta-10), I'll try to reproduce it there.

**Comment by jgw96** [comment]
@arsenslyusarchuk Unfortunately at the moment I am not able to get the plunker working with Ionic 2 beta.11, although im marking it down now as something to fix. Sorry for any hassle that causes. I am able to intermittently reproduce this issue though with your info, so we can definitely take a look into it! Thanks!

**Comment by arsenslyusarchuk** [comment]
@jgw96 That's great. Thanks

**Comment by cybertim** [comment]
I have the same issue when a Modal is created (on a tabs project) and you have a particular order of events when closing the modal. Especially when using `Promise`s and calling `.dismiss()` on the view (ViewController) in a `.then()`.

Resolved it by using `onDidDismiss()` if I used `dismiss().then()` the issue remained.
Maybe using `onDidDismiss` will solve the issue?

**Comment by asbelghith** [comment]
Hello, i can't see the solution here, why the issue is closed then ?

**Comment by janpio** [comment]
The issue is still open. It only has been referenced from two closed issues.
