### ISSUE TITLE
Expandable list item animation is not smooth backwards

### ISSUE THREAD

**Issue by Bouzmine** [ionic-team/ionic#7798]
#### Short description of the problem:

There's no animation when pulling an `expandable` list item (until the animation finishes) and then going backwards.

See [ItemSliding API Docs](http://ionicframework.com/docs/v2/api/components/item/ItemSliding/), try sliding one of the Login items until Mute button is gone and then back until it reappears.
#### What behavior are you expecting?

To have a smooth animation like on iOS.

For expected behaviour see Apple iOS' Mail animation.

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by manucorporat** [comment]
We are aware of this issue, there are technical challenges that prevented us to work as "Apple iOS' Mail" for example.

I keep this issue open to track the progress 👍
