### ISSUE TITLE
[ionic 2 enhancement] ion-searchbar: dynamically set colors for icons

### ISSUE THREAD

**Issue by szerner** [ionic-team/ionic#7826]
I would appreciate the possibility to set the colors of the `<ion-searchbar>` component icons on the fly. 

Currently we can use some ionic Sass variables to define the colors for some of them (`clear-icon` and `search-icon`, but **not** for the `cancel-button` icon) at build time, but we cannot set the colors at runtime.

This might be necessary in cases when the user should be able to choose a "color theme" for his app.

Thank you!

**Comment by okonon** [comment]
@jgw96 could you please point me to right direction how to change search icon and clear button colors with CSS? thanks a lot ! keep up the good job!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
