### ISSUE TITLE
Issue when I add new elements in the ion-header in ios

### ISSUE THREAD

**Issue by jmickvs** [ionic-team/ionic#7882]
Hello again, the previous trouble happened in android devices now i have a same trouble but now happens in ios devices, when I add a new element/component within header, the new component is overlap to searchbar that is there default, i don't know if i need do something like the resize method of ion-content for ion-header.

![img_0318](https://cloud.githubusercontent.com/assets/15081575/17982513/ac027570-6acd-11e6-9b81-e6b67fd8aae8.jpg)
![img_0319](https://cloud.githubusercontent.com/assets/15081575/17982514/ac06445c-6acd-11e6-9812-6646720b989e.jpg)

Other case is that the new component push up the searchbar but never resize the ion-header and ion-content. 

![img_0316](https://cloud.githubusercontent.com/assets/15081575/17980007/fb29b916-6ac2-11e6-959e-070c1749a77c.jpg)
![img_0317](https://cloud.githubusercontent.com/assets/15081575/17980008/fb2cd2cc-6ac2-11e6-9b2c-356d0a0f23a3.jpg)

Like extra information, recently I update my project to ionic2 beta 11

I hope you can help me, thank you

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Using the resize method like we did on Android should solve this issue too. Thanks!

**Comment by jmickvs** [comment]
But i have Already Implemented the resize method to the ion -content in android and ios like android and yet the issue happens.
The ion -header Also Have a resize method?

Thank you

**Comment by jgw96** [comment]
@jmickvs Would you mind providing a minimal code example or repo that i can use to reproduce this issue? Thanks!

**Comment by jmickvs** [comment]
My html code is

<ion-header>
    
    <ion-navbar>
      <ion-searchbar *ngIf="!isIos" [(ngModel)]="searchQuery" (ionInput)="performSearch($event)" placeholder='search'></ion-searchbar>
      <ion-title  *ngIf="isIos" style="padding-left: 0px;padding-right: 35px;">
        <ion-searchbar [(ngModel)]="searchQuery" (ionInput)="performSearch($event)" placeholder='search'></ion-searchbar>
      </ion-title>
      <button *ngIf="!InternetMsg" warning block class="minusculas noConnection">Aplication without connection</button>
      <button *ngIf="anonymous" danger block class="minusculas info-msg" (click)="someFunction()">Label</button>
    </ion-navbar>
</ion-header>

<ion-content>
    some content ...
</ion-content>

the functionality is basic, the saerchbar is always visible and when the device lost the internet connection the variable "InternetMsg" sets value "false" then the button with label "Aplication without connection" is visible.
The ion-content already have the resize function in the ts class and the same code works very well in android but in ios i have the troubles already shown previously, thank you.

**Comment by jmickvs** [comment]
My html code is

`<ion-header>`
   `<!--<ion-title>title</ion-title>-->`
   ` <ion-navbar>`
      `<ion-searchbar *ngIf="!isIos" [(ngModel)]="searchQuery" (ionInput)="performSearch($event)" placeholder='search'></ion-searchbar>`
      `<ion-title  *ngIf="isIos" style="padding-left: 0px;padding-right: 35px;">`
        `<ion-searchbar [(ngModel)]="searchQuery" (ionInput)="performSearch($event)" placeholder='search'></ion-searchbar>`
      `</ion-title>`
      `<button *ngIf="!InternetMsg" warning block class="minusculas noConnection">Aplication without connection</button>`
      `<button *ngIf="anonymous" danger block class="minusculas info-msg" (click)="someFunction()">Label</button>`
    `</ion-navbar>`
`</ion-header>`

`<ion-content>`
`</ion-content>`



the functionality is basic, the saerchbar is always visible and when the device lost the internet connection the variable "InternetMsg" sets value "false" then the button with label "Aplication without connection" is visible.
The ion-content already have the resize function in the ts class and the same code works very well in android but in ios i have the troubles already shown previously, thank you.

**Comment by jmickvs** [comment]
Hello, some solution for this issue, regards
