### ISSUE TITLE
ionic2: Modal - Dismiss - No validation/checks on attributes anymore

### ISSUE THREAD

**Issue by graphefruit** [ionic-team/ionic#7908]
#### Short description of the problem:

If you create a modal overlay, and you'll close this modal, special attributes are not validated/checked anymore like **[disabled]**
#### What behavior are you expecting?

The validations doesn't stop.

**Steps to reproduce:**
1. Create Modal window: 

```
@Page({
  templateUrl: 'build/modals/rating/rating.html',
})
export class RateModal
```
1. Call modal window from normal view

```
 let rateModal = this.modalCtrl.create(RateModal,{});
 rateModal.present();
```
1. Dismiss modal window

```
  this.viewCtrl.dismiss(); 
```
1. Having an [disabled] attribute in the view

```
<button [disabled]="!isEnabled()"></button>

public isEnabled()
{
  //Change it to whatever then.
  return true;
}
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
If you attach an breakpoint to "isEnabled" it gets called every time, but after showing and dismissing modal the breakpoint isn't jumped.
(click) events still work. 

**Which Ionic Version?** 2.0.0-beta.37

Greetings & Thanks in advance
Graphefruit

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Sorry but i'm misunderstanding the issue a little. Is the disabled button on the view that the modal is being pushed from or on the modal itself? Thanks!

**Comment by graphefruit** [comment]
Hi @jgw96 sorry for not beeing clear enough.

1. The button is enabled
2. User clicks button
3. Modal opens. 
4. Modal closes (after user clicks button)
5. The "isEnabled()" function now returns false

And here the problem comes -> The "isEnabled()" function isn't called anymore, so the button stays active and can be clicked.

Sorry I don't know the words for it but in Angular 1 it would be, that the digest cycle isn't executed for [disabled]
Greetings
Graphefruit

**Comment by jgw96** [comment]
Thanks for the info! Would you be able to post a repo that i can reproduce this issue with?

**Comment by graphefruit** [comment]
Sadly I can't attach a ZIP-File, because my chrome (don't know...)
So heres the download link: http://www.file-upload.net/download-11903415/app.zip.html
Thats the /app/ dir.

-> ionic serve
-> press button 
-> modal appears
-> dismiss modal
-> button should now be disabled -> but isn't

I've now found the problem, the problem is the **loadingCtrl**, because I need to make a server request and want to show the user a "Please wait" I implemeneted this loadingCtrl.
If you outcomment this line, the button will get disabled.

Thanks for your help, if you need anything more just let me know
PS: I wanted to do an online plunkr but didn't find a newest beta 37 plunkr.
