### ISSUE TITLE
Ionic 2 searchbar doesn't refocus on back

### ISSUE THREAD

**Issue by aggarwalankush** [ionic-team/ionic#8072]
#### Short description of the problem:

Consider ionic-conference-app, searching will filter list elements. Search for something and click on filtered result and come back, searchbar won't be in focus.
#### What behavior are you expecting?

Searchbar should refocus if coming back to component. Because when we come back, list elements are still filtered by search input but it's not in focus so user doesn't know whether search is still applied or not.

Also, if we see in other apps such as Settings app in iOS, search something and come back, it will refocus searchbar. 

**Which Ionic Version?** 1.x or 2.x
Ionic 2 beta 11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.3.0
Gulp version: CLI version 3.9.1
Gulp local: Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.1.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by aggarwalankush** [comment]
Hi @jgw96 , Sorry to bother you. 

I went through Searchbar docs and couldn't find any method to focus searchbar programatically. As you can see in this issue, I want to focus searchbar in `ionViewDidEnter`. By focus, I mean having cursor in search bar and display cancel button in case `showCancelButton` is set to true.

-Thanks

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! You can grab a reference to the `ion-searchbar` using the Angular 2 [@ViewChild](http://learnangular2.com/viewChild/) and then use the standard dom [focus()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) method to focus it. I am going to leave this issue open though as we may want to add a focus method to the keyboard for convenience. Thanks!

**Comment by mkoczka** [comment]
Is this still relevant?

`Searchbar` component now has the `setFocus` method.

http://ionicframework.com/docs/api/components/searchbar/Searchbar/#setFocus
