### ISSUE TITLE
Hammer breaks HTML5 drag and drop by overriding drag events

### ISSUE THREAD

**Issue by jimitndiaye** [ionic-team/ionic#8079]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/
#### Short description of the problem:

Drag events 'dragstart', 'dragend' used to work properly by using the native HTML 5 DND api. Now they are being overriden by Ionic's Hammer gestures meaning we can no longer access such things as `event.datatransfer`. This happens on elements/components that aren't even Ionic ones
#### What behavior are you expecting?

HTML5 DND events should work as normal, as they used to.

**Steps to reproduce:**
1. Use a HostListerner for the 'dragstart' event on a component.
2. The event object returned is no longer an instance of DragEvent. Instead it is a custom object produced by Ionic's hammer configuration
3. You get errors due to the object not being an instance of DragEvent as illustrated below

```
browser_adapter.js:84 TypeError: dragEvent.stopPropagation is not a function
    at DraggableDirective.handleDragEnd (draggable.directive.ts:46)
    at DebugAppView._View_EditorComponent2._handle_dragend_0_1 (EditorComponent.ngfactory.js:740)
    at view.js:381
    at dom_renderer.js:255
    at hammer_gestures.js:68
    at ZoneDelegate.invoke (zone.js:332)
    at Object.onInvoke (ng_zone_impl.js:53)
    at ZoneDelegate.invoke (zone.js:331)
    at Zone.runGuarded (zone.js:239)
    at NgZoneImpl.runInnerGuarded (ng_zone_impl.js:86)
    at NgZone.runGuarded (ng_zone.js:240)
    at Array.callback (hammer_gestures.js:68)
    at Object.emit (hammer.js:2089)
    at emit (hammer.js:1219)
    at PanRecognizer.emit (hammer.js:1231)
    at PanRecognizer.emit (hammer.js:1484)
    at PanRecognizer.tryEmit (hammer.js:1242)
    at PanRecognizer.recognize (hammer.js:1283)
    at Object.recognize (hammer.js:1965)
    at MouseInput.inputHandler [as callback] (hammer.js:409)
    at MouseInput.MEhandler [as handler] (hammer.js:670)
    at Input.domHandler (hammer.js:332)
    at ZoneDelegate.invokeTask (zone.js:365)
    at Zone.runTask (zone.js:265)
    at ZoneTask.invoke (zone.js:433)
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.10
#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jimitndiaye** [comment]
I may have found the problem. It seems that ```ion-item``` is now somehow being given an inline style of the following: 
```css
<ion-item style="touch-action: none; -webkit-user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);">```
This is disabling html5 drag and drop. I worked around it by using CSS to override that ```-webkit-user-drag: none;``` style to ```-webkit-user-drag: element !important;```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! When you say that this used to work do you mean that in beta.10 it worked?

**Comment by jimitndiaye** [comment]
Yes. The Drag gesture is now overriding the dragstart and dragend events. It didn't used to do that before. These two events are integral to HTML5 drag and drop. Instead of overriding those, it should really be overriding the drag event (if necessary). angular/material2 uses Hammer and they don't do this. It's only ionic2

**Comment by jgw96** [comment]
Thanks for the info! Would you be able to provide a repo or code snippet i can use to reproduce this issue? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by jimitndiaye** [comment]
Use the default ionic2 template and add an event handler for the dragstart event on any node. Inspect the event object instance that you receive in your event handler. It is **not** an instance of DragEvent. Instead it is a Hammer generated object that is missing the HTML5 drag and drop APIs (e.g ```event.datatransfer```)
