### ISSUE TITLE
bug: Hardware back pop pages in wrong order

### ISSUE THREAD

**Issue by MatanYed** [ionic-team/ionic#8149]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have tabs page, with 4 tabs.
I go to the 3rd tab, then open the menu and go to another page (which is with navCtrl.push() and not changing root).
Than I click hardware back, nothing happens, click again and the page is poping, and i am in the 1st tab, which means in the click that nothing happened - he returned to the 1st tab and only then poping the page.

With the back button on the navbar - its good, the problem is only with the hardware back.
Android 6.0.1 - Galaxy note 5.</span>

<span is-issue-template></span>

**Comment by sava999** [comment]
Hi,

Did you found solution for your problem? I am having similar problem.

I have page with two tabs and from those tabs I am opening new page using:

```
itemTapped(user) {
    let nav = this.app.getRootNav();
    nav.push(ProfilePage, {
        user: user
    });
}
```

As you can see ProfilePage will be open. Hardware back button is working as expected if I open profile page from first tab, but if I switch to second tab and open profile page first click on hardware back button will do nothing, second click will get me be back to first tab.

Anyone have any idea what could be the issue here?

Thanks!

**Comment by sava999** [comment]
Please ignore my question, I solved issue with:

```
platform.registerBackButtonAction(() => {
  if(this.nav.canGoBack()) {
    this.nav.pop();
  } else {
    this.showExitAlert();
  }
});
```

**Comment by PAFsec** [comment]
Hello, 

I have the exact same issue.
I am using Android 7.

I have a page with 3 tabs (T1, T2 and T3) and a right side menu. I can reproduce the bug everytime by doing the following: 

- From one tab (**T1**) (does not matter which one), I go to a new view (**V1**) by doing a **navCtrl.push()** from T1 controller ;
- From this new view I open the menu (by swipping) and I go to another view (**V2**)  with **this.appCtrl.getRootNav().push()**
- I push the _hardware back button_ (no effect on the screen, when it should **pop(V2)** and bring me back to **V1**)
- I push the _hardware back button_  another time (I am back at **T1**, so it actually **pop(V1)** )

In addition, doing the following makes my 
```
<ion-header>
  <ion-navbar></ion-navbar>
</ion-header>
```
temporarely disappear from my **T1** until I click on another tab button (T1, T2 or T3)

Tell me if you need more information.

Thank you,
