### ISSUE TITLE
bug: Picker buttons wrong align in iOS and Windows Phone

### ISSUE THREAD

**Issue by MatanYed** [ionic-team/ionic#8154]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Picture to understand:
https://s17.postimg.org/vn18lz6bh/picker_css_bug.png

Cancel button should have text-align: left

css to fix it:

```
.picker-toolbar-button:first-child {
    text-align: left;
}
```

</span>

<span is-issue-template></span>

**Comment by John-Luke** [comment]
You got fix it? if "yes", close that issue and send a PR
