### ISSUE TITLE
bug: iOS toast on top overlaps with status bar

### ISSUE THREAD

**Issue by ErkoKnoll** [ionic-team/ionic#8476]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.0.0 RC0</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>When toast is positioned on top then it overlaps a little bit with the iOS status bar. Additional margin is needed for top position in iOS.</span>

<span is-issue-template></span>

**Comment by kamok** [comment]
This is still open, btw. @manucorporat tried to fix it but I am unable to use the `statusBarPadding: true` under the options when you do `toastCtrl.create({})`.
