### ISSUE TITLE
DeepLinker - Navigate by Url

### ISSUE THREAD

**Issue by stephenlautier** [ionic-team/ionic#8482]
#### Short description of the problem:

Currently we're trying to navigate by URL, by consuming the `DeepLinker` (as an API), however there's no public API which does that; the closest thing I found was `urlChange(browserUrl: string)` which doesn't update the URL due to the below:

``` ts
// urlChange
appRootNav.goToRoot({
    updateUrl: false,   // <---
    isNavRoot: true
});
```

Another issue, the URL is not normalized when its a path, meaning the base will not be stripped out.
#### What behavior are you expecting?

Having an api within `DeepLinker` such as `navigateByUrl(url: string)`

NavigateByUrl 
- Normalize Url (to remove base)
- Update browser url
- Transition (setRoot)
  *pretty much what `DeepLinker.urlChange` does but `updateUrl: true` + normalization

**Which Ionic Version?** 2.x

**Comment by kleeb** [comment]
any news on this one?
