### ISSUE TITLE
Header applying toolbar-md on IOS(browser and device)

### ISSUE THREAD

**Issue by abartolo** [ionic-team/ionic#8577]
#### Short description of the problem:

 I am using "<ion-header>" on a page and its applying "header-md" on an iPad Mini device(both device and browser). Causing it to render in 2 lines.
#### What behavior are you expecting?

Expecing to apply correct CSS on the specifiic platform it is in.

**Steps to reproduce:**
1. Happens randomly on browser(refresh). But on device it does happen.

```
`
<!-- Toolbar-->
<ion-header>
  <ion-toolbar color="primary">

    <button ion-button (click)="showOptionsPopover($event)">
      <ion-icon name="more"></ion-icon>
    </button>

    <ion-title id="rg-title">
      <!-- Score -->
      <div id="rg-gameScoreContainer" class="sc-display-flex">
        <span class="rg-teamName">{{coachTeamName}}</span>
        <span class="rg-teamScore">{{teamScore}}</span>
        <span id="rg-scoreDivider">-</span>
        <span class="rg-teamScore">{{oppScore}}</span>
        <span class="rg-teamName">{{oppTeamName}}</span>
      </div>
      <!-- Timer -->
      <div id="rg-periodClockContainer" tappable (click)="mg($event)">
        <span id="rg-period">{{periodUI}}</span>
        <ion-icon name="md-time"></ion-icon>
        <span id="rg-clock">{{gameClockUI}}</span>
      </div>
    </ion-title>

  </ion-toolbar>
</ion-header>

<ion-content>
<!-- Some HTML -->
</ion-content>
`

```

**Images:**
![image](https://cloud.githubusercontent.com/assets/5394228/19214713/e6b3760e-8d57-11e6-89df-bc9533bb890e.png)

![image](https://cloud.githubusercontent.com/assets/5394228/19214723/185b5226-8d58-11e6-8c32-ba0e4ea20423.png)
# 

**Which Ionic Version?** 1.x or 2.x
2.1.0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1  
Ionic Framework Version: 2.0.0-rc.0  
Ionic CLI Version: 2.1.0  
Ionic App Lib Version: 2.1.0-beta.1  
OS: Windows 7 SP1  
Node Version: v6.2.0

**Comment by abartolo** [comment]
Anyone having this issue?

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind changing your `ion-toolbar` to `ion-navbar` and trying again?

**Comment by abartolo** [comment]
Thanks for the reply. 

I initially used ion-nav and had the same issue. I began to search if anyone had similar but no luck. So I then switched to ion-toolbar and issue kept occuring.

I figured it might be a browser issue but I saw it on my iPad mini

**Comment by manucorporat** [comment]
can you provide a repo that reproduces this issue?

**Comment by abartolo** [comment]
I am unable to replicate. I will reopen if I ever see it again. Thank you.

**Comment by abartolo** [comment]
Hello @manucorporat and  @jgw96 ,

Any luck trying out the repository I created replicating the issue?
