### ISSUE TITLE
Consistent ionic NgModel components

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#8578]
We should revisit:
- [ ] checkbox
- [ ] date-time
- [ ] input
- [ ] text-area
- [ ] radio-group
- [ ] searchbar
- [ ] segment
- [ ] selector
- [ ] toggle

and events like `(ionChange)`, `(ionSelect)` in across the framework: Tabs, SplitPane, SlidingItem...

Each one has a different policy when calling the callbacks.
- Some does not call onChange() when the value is changed from writeValue
- Some does fire the callbacks with the default value (others not)
- In general all these components are doing the same thing but from an implementation detail they are not consistent.

Examples:
Toggle: https://github.com/driftyco/ionic/blob/master/src/components/toggle/toggle.ts#L230-L246
Range: https://github.com/driftyco/ionic/blob/master/src/components/range/range.ts#L620-L649

I propose to create a new design document to describe how an ionic component should work through a base interface and a standarized behavior, we could even create "base unit tests" shared between all the inputs.

ping
@adamdbradley 
@brandyscarney 

I think this should be approached before ionic 2.0 final is released. Probably in 2.0rc2

**Comment by adamdbradley** [comment]
I started using abstract classes here for each of our input types, we can use this to come up with a standard. https://github.com/driftyco/ionic/blob/master/src/util/form.ts#L66

**Comment by manucorporat** [comment]
https://github.com/driftyco/ionic/issues/9472

**Comment by manucorporat** [comment]
Ionic inputs should not break if user land code crashes. i.e. we should wrap call to user's code with try{} catch

```
dispatchEvent() {
   try {
     this.userland();
   }catch() {
   }
}
```

**Comment by manucorporat** [comment]
https://github.com/driftyco/ionic/pull/10532

**Comment by manucorporat** [comment]
All inputs to implement `ionFocus` and `ionBlur`

**Comment by manucorporat** [comment]
All events in ionic should behave the same:

**Comment by manucorporat** [comment]
ng-valid handling inconsistency: https://github.com/driftyco/ionic/issues/10952

**Comment by manucorporat** [comment]
https://github.com/driftyco/ionic/issues/11005

**Comment by manucorporat** [comment]
https://github.com/driftyco/ionic/issues/7806

**Comment by manucorporat** [comment]
https://github.com/driftyco/ionic/issues/8935#issuecomment-291985636
