### ISSUE TITLE
ionic2 - bug(overlays) - After clicking to dismiss an overlay, the click propagates to whatever is beneath it.

### ISSUE THREAD

**Issue by zakton5** [ionic-team/ionic#8784]
#### Short description of the problem:

If I have an overlay open (modal confirmed, not sure about others), and click a dismiss button on it, the transition will run and then once it is dismissed it will click whatever is beneath it, such as an input, etc. This happens on iOS. Not sure about any other platforms.
#### What behavior are you expecting?

I expect there to not be duplicate clicks.

**Steps to reproduce:**
1. Create a page with some inputs on it (I am specifically using standard textareas)
2. Create a modal with a dismiss button directly over one of the textareas
3. Open the modal, click the dismiss button, and observe that the textarea is focused and the keyboard appears

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0  
Gulp version:  CLI version 3.9.1  
Gulp local:   Local version 3.9.1  
Ionic Framework Version: 2.0.0-rc.1  
Ionic CLI Version: 2.1.0  
Ionic App Lib Version: 2.1.0-beta.1  
ios-deploy version: 1.8.4  
ios-sim version: 5.0.6  
OS: Mac OS X El Capitan  
Node Version: v4.5.0  
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind posting a repo we can use to repro this issue?

**Comment by zakton5** [comment]
https://github.com/zakton5/ionic2-clickthrough-bug

Make sure to run it in an iOS emulator.

**Comment by m-spyratos** [comment]
This happens with Alert overlays as well.

**Comment by danishin** [comment]
This issue seems to be related to #10124. Having two alerts to show up consecutively is quite a pain and requires `setTimeout` hacks..

**Comment by zakton5** [comment]
I can't seem to reproduce this anymore. Not sure about #10124 though
