### ISSUE TITLE
Valid highlights don't account for ng-touched

### ISSUE THREAD

**Issue by patrickmcd** [ionic-team/ionic#8826]
#### Short description of the problem:

Inputs in an edit form shouldn't show any highlights, whether valid or invalid, until touched by the user. Currently, the valid highlight shows regardless, while the invalid highlight waits for ng-touched to be applied.

You don't notice this until pre-populating inputs with valid data from a server, or what have you. Perhaps I'm mistaken and this is the expected "native" behavior, but opening a form and seeing a bunch of green everywhere seems odd.

PR upcoming.
#### What behavior are you expecting?

I expect inputs to wait to be touched for valid values as they do for invalid values.

**Steps to reproduce:**
1. Use FormBuilder or ngModel to give an input a valid value before a user uses a form.
2. Notice green/valid highlights before touching input.

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: Mac OS X Sierra
Node Version: v6.6.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by brandyscarney** [comment]
I think this needs to be more customizable in general. We assume the user only wants the invalid to show when touched, but sometimes they may want it to show on submit. I was thinking we could add some variables that control when to add the valid/invalid highlights based on the `ng-*` classes. Thoughts?

**Comment by patrickmcd** [comment]
When submitting a form, you can always [`markAsTouched()`](https://angular.io/docs/ts/latest/api/forms/index/AbstractControl-class.html#!#markAsTouched-anchor) the controls that need to show as invalid, the idea being that submitting is equivalent to touching the whole form.

You could go overboard with all the variations of valid, touched, & dirty. This fix at least brings valid & invalid highlights inline so they act the same way.
