### ISSUE TITLE
<ion-searchbar> in <ion-toolbar color="dark"> missing md css style

### ISSUE THREAD

**Issue by eidng8** [ionic-team/ionic#8890]
#### Short description of the problem:

``` html
<ion-toolbar color="dark">
  <ion-searchbar></ion-searchbar>
</ion-toolbar>
```
#### What behavior are you expecting?

The search bar should have a dark background, but now it's all white.

There is a rule for ios: `.toolbar-ios-dark .searchbar-ios .searchbar-input`, which works fine after ported to md mode.

**Which Ionic Version?** 1.x or 2.x
v2 rc1

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
OS: Windows 7 SP1
Node Version: v4.3.1

**Comment by brandyscarney** [comment]
Hey, thanks for the issue! I'm not sure if I understand the problem. Are you saying the Material Design searchbar should have a dark background when placed inside of a dark toolbar? So you want this:

<img width="412" alt="screen shot 2016-10-28 at 12 53 44 pm" src="https://cloud.githubusercontent.com/assets/6577830/19814812/e3d9c530-9d0d-11e6-8db8-864329016b71.png">

to look more like iOS?

<img width="377" alt="screen shot 2016-10-28 at 12 54 21 pm" src="https://cloud.githubusercontent.com/assets/6577830/19814813/e3db15de-9d0d-11e6-99ea-44707738d4b9.png">

**Comment by eidng8** [comment]
Oh! A flash! I was engulfed by the fruit. Now I got the point. But frankly,
it's a bit too outstanding to have a white search box over on a dark
screen. Especially when I'm in dark, that white box jump out and hurt my
eyes a bit.
