### ISSUE TITLE
Ionic segment stop working when a alert is closed

### ISSUE THREAD

**Issue by marcelobotega** [ionic-team/ionic#8902]
#### Short description of the problem:

Closing an alert opened from a ion-tab will make a ion-segment stop working.
I think that using a toast or a modal will cause the same problem.
#### What behavior are you expecting?

The ion-segment continue to work.

**Steps to reproduce:**
1. Go to about page
2. test the ion-segment (it will work)
3. Click the contact tab (alert will open)
4. Close the alert.
5. The ion-segment will stop working
6. If the tabs are changed the ion-segment will work again

**Which Ionic Version?** 2.x rc.1
#### Plunker that shows an example of your issue

The alertController wont work on the plunker ( i don't know why ), so i made a github repo with the example, i hope that is not a problem for you guys.

https://github.com/marcelobotega/ionic-segment

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.36
OS: Distributor ID: LinuxMint Description:  Linux Mint 18 Sarah 
Node Version: v7.0.0

English is not my mother language, please excuse any errors on my part.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! No problem at all, your post was perfectly understandable. Could you try using the latest nightly (`npm install ionic-angular@nightly --save`) and see if you still get the issue?

**Comment by marcelobotega** [comment]
Hello, with the nightly build the issue persists. I added a new branch on the repo with the nightly.
When installing the ionic-angular nightly this error showed up:

nightly!ionic-segment *> npm install ionic-angular@nightly --save
ionic-hello-world@ /home/marcelo/workspace/ionic-segment
├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@2.0.0
└── ionic-angular@2.0.0-rc.1-201610241941 

The platform dependency is related with this somehow ?

**Comment by marcelobotega** [comment]
One more thing i only tested the nightly on the web.

**Comment by marcelobotega** [comment]
Any news on this issue ?

**Comment by xmellado** [comment]
Hello,
I found the problem described here in Ionic 3.1.1, too:
1) A tab has a button for searching using location, which opens a modal window if the user has not granted permissions. It is an educational modal window for letting the user know why we need location.
2) If the user say yes in the modal window, a location is obtained for triggering the system location permissions dialog. If the user says no, nothing happens. In both cases, the window is dismissed.
3) If the user said yes, after `onDidDismiss` a search is done using its location. And the results are in a new pushed page with two segments. Those segments do **not** allow to switch between them properly.
4) In a regular case without the modal window, everything works fine.

       Regards,
                            Xavi

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.6
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002
```
