### ISSUE TITLE
Searchbar Not Blurring

### ISSUE THREAD

**Issue by duncanreid** [ionic-team/ionic#8933]
#### Short description of the problem:

RC1. Device: iOS 10.0.2.

This only happens when testing on the device, it works as expected while testing in Chrome.

Searchbar input will not blur when tapping anywhere outside of the component, so the keyboard will not go away and the ionBlur event is not firing.  It will blur if you tap on a button or something else that gains focus. The only way I have been able to work around this is to add click listener directives to all of the elements around the Searchbar.  

I notice that the Searchbar is using a normal input as opposed to an ion-input, so it also inhibits the cursor peekaboo effect where the cursor can still be seen while scrolling underneath fixed elements like headers.
#### What behavior are you expecting?

Tapping anywhere outside the Search bar will remove the keyboard and fire the (ionBlur) event.

**Steps to reproduce:**
1. Fire up a basic v2 tabs project
2. Add a Searchbar
3. Tap Searchbar input, tap anywhere outside after keyboard is shown.

**Which Ionic Version?** 1.x or 2.x
2.X RC1

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v6.2.2
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment]
@manucorporat im thinking this is probably caused by the backrdop on iOS right?

**Comment by manucorporat** [comment]
@jgw96 I don't think so, hard to say without testing

**Comment by danielcrk-cn** [comment]
If it helps, the blurring works fine on Android but not on iOS.

**Comment by Xal3ph** [comment]
We are also seeing this in 2.x RC2

**Comment by biesbjerg** [comment]
Just to add to this issue, I'm seeing a delay (300ms tap delay?) when tapping the searchbar to gain focus, and similar when tapping clear or cancel.

**Comment by Xal3ph** [comment]
We added '(click)="return:"' or '(click)="{}"' to the 'ion-content' and this fixed it for us.

**Comment by biesbjerg** [comment]
@Xal3ph Nice. That seems to workaround the issue for me too. Btw, do you also experience input is slow to get focus on tap? I played around with the `tappable` property, but it does not make a difference.

**Comment by vincentgigandet** [comment]
I have a same issue - searchbar not blurring. 
ionic: 2.1.4
iOS 9.3

I couldn't understand the workaround. Add (click)="return;" to <ion-content>?

**Comment by Xal3ph** [comment]
Yes
`<ion-content (click)="return;">

</ion-content>`

or

`<ion-content (click)="{}">

</ion-content>`

**Comment by vincentgigandet** [comment]
@Xal3ph Thanks! It worked!

<ion-content (click)="return;"> produced error with below message when compile.
(Property 'return' does not exist on type 'MyPage')

<ion-content (click)="{}"> worked.

**Comment by comfortme** [comment]
very annoying issue.
in my app after user search, list of items are shown which items already have a click listener to push another page.
so users cant click anywhere to close keyboard.
keyboard is open, user scrolls and try to see the content through 100px window.

**Comment by alexdruk** [comment]
@comfortme  Exactly the same here!
Proposed by @Xal3ph workaround does not work

**Comment by ghenry22** [comment]
click events seem to hide the keyboard now for me, but scroll events don't so if the user wants to scroll through the filtered results to find what they want to click on the keyboard doesn't close, often meaning the user has a very small window to scroll.  This fixes it for me:

`<ion-content (ionScrollStart)="closeKB()">`

then
`closeKB(){ Keyboard.hide();}`

this uses the ionic-native Keyboard module to hide the keyboard if the user starts scrolling.

**Comment by liuwenzhuang** [comment]
I have a same issue - searchbar not blurring when scroll list, but click other part other than searchbar hide keyboard indeed.
ionic: 2.1.17
Android: 6.0.1/iOS 10.0.1

**Comment by ghenry22** [comment]
@liuwenzhuang I have posted simple steps just above to add a scrollStart listener and close the keyboard on scroll start.  Just follow those.

**Comment by chuchuva** [comment]
This issue still occurs on Ionic Framework 3.5.2 both on iOS and Android.

**Comment by camillesaury** [comment]
it's only when you compile that the problem occur
