### ISSUE TITLE
Alert: setCssClass doesn't work after alert.present()

### ISSUE THREAD

**Issue by gabriele-v** [ionic-team/ionic#8967]
#### Short description of the problem:
When setCssClass on an alert element after alert.present() class is not added

#### What behavior are you expecting?
Specified class added to element

#### Code
This works:
```
let alert = this.alertCtrl.create({
    title: "Title",
    message: "Message",
    buttons: ["OK"]
});
alert.setCssClass("alert-wide");
alert.present();
```

This doesn't work:
```
let alert = this.alertCtrl.create({
    title: "Title",
    message: "Message",
    buttons: ["OK"]
});
alert.present();
alert.setCssClass("alert-wide");
```

This doesn't work too, but instead alert.setMessage works also after present:
```
let alert = this.alertCtrl.create({
    title: "Title",
    message: "Message",
    buttons: [{
        text: "OK",
        handler: () => {
            alert.dismiss();
        }
    }, {
        text: "Details",
        handler: () => {
            alert.setCssClass("alert-wide");
            alert.setMessage("NewMessage");
            return false;
        }
    }]
});
alert.present();
```
 
**Which Ionic Version?**
2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 8.1
Node Version: v6.7.0

**Comment by gabriele-v** [comment]
If it won't be fixed, is there at least a workaround that I can use to solve it?
Thanks

**Comment by damsorian** [comment]
I have the same issue.
