### ISSUE TITLE
Config.set is not working with tabsHideOnSubPages

### ISSUE THREAD

**Issue by royipressburger** [ionic-team/ionic#8970]
#### Short description of the problem:
When initialising the application with `tabsHideOnSubPages: true`
If trying to change the value dynamically with `config.set` there is no effect.

**Steps to reproduce:**
1. start a tabs project
2. before pushing a new page do  `this.config.set('tabsHideOnSubPages', false)`
3. 

**Which Ionic Version?** 1.x or 2.x
2.rc1

#### Plunker that shows an example of your issue
http://plnkr.co/edit/LLnXgkRnxLeY1PItgual?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by manucorporat** [comment]
@royipressburger It is not a good idea to change configuration values at runtime. what's your use case?

**Comment by royipressburger** [comment]
@manucorporat Hi, I want to be able to show the tabs bar on some pages that are being pushed to the nav stack.
By default im using `tabsHideOnSubPages = true` but there are few pages that I still want to show the tabs.

**Comment by royipressburger** [comment]
Hi again @manucorporat Is see the commit you referred too.
As this solve some of the issue but there is still something that Im not quite sure how to do.

lets assume that I have a tag page with 2 buttons each one pushes a new page to the stack.
If I use the feature you added I guess that both pages will have (or not have, depending on the tabsHideOnSubPages value) tabs in them. 
If I want one to have tabs and the other not to have?

**Comment by manucorporat** [comment]
@royipressburger ok...  I see your use case. It can be done. But it is a tricky one from a API perspective.

maybe something like:
```
this.nav.push(Page, {
  tabsHideOnSubPages: true
});
```

NOTE this will not work, it just an idea of how we could make it work... 
Thinking...

**Comment by royipressburger** [comment]
@manucorporat This thing can work, But this might cause a little confusion with the `NavParams`.
Maybe we can make it nested under `pageOptions`?

`this.nav.push(Page, { pageOptions: { ConfigLikeObject } })`

With this I think it will be easier to extend all the config object like animation and maybe mode under specific page

What do you think?

**Comment by manucorporat** [comment]
sure, it should be in the 3rd parameter. I just forgot the API :)

**Comment by royipressburger** [comment]
@manucorporat The commit you referred too will give me the option to keep/hide the tabs per tab page? I mean if I got the default set to false and on one tab i change to true, every page that will be pushed from this tab will have the tabs?
Can I expect this on rc2?

**Comment by royipressburger** [comment]
@manucorporat Any news on that?

**Comment by manucorporat** [comment]
@royipressburger I am sorry for the inconvenience, but let's evaluate this once 2.0 final is released. It is a big internal change if we want to support your use case, and it is too late for new features or big changes.
