### ISSUE TITLE
ion-toggle displays "off" when using ngModel in disabled-state

### ISSUE THREAD

**Issue by 7freaks-otte** [ionic-team/ionic#8990]
When using a simple ionic2 ion-toggle in combination with ngModel everything is working fine.

`this.trueVar = true;`

The following Toggle displays in "on" state:

`<ion-toggle [(ngModel)]="trueVar"></ion-toggle>`

As soon as you want to disable user interaction, the toggle displays as "off" although trueVar = true:

`<ion-toggle [disabled]="true" [(ngModel)]="trueVar"></ion-toggle>`

**Comment by Elisabetta87** [comment]
Hi, 
I had the same issue. Anyone found out how to fix it?
