### ISSUE TITLE
ionic prepare ios in windows does not update the files in the platforms/ios folder. Same with Android.

### ISSUE THREAD

**Issue by mflmartin** [ionic-team/ionic#9001]
### Short description of the problem:
When Building for IOS with ionic build ios, the modified files of the build are not copied again into platforms/ios, in Windows 10

#### What behavior are you expecting?
That they are updated.

**Steps to reproduce:**
1. ionic start myapp --v2
2. ionic platform add ios
3. ionic prepare ios    OR   ionic prepare android
4. Test the platform (with a Mac). Ok. It works.
5. Modify something in your project
6. ionic build ios
7. Boom. No files updated.

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
OS: WINDOWS 10
Node Version: v6.4.0

**Comment by ghenry22** [comment]
Pretty sure you can only build iOS on osx as it needs xcode

**Comment by mflmartin** [comment]
I meant PREPARE not build, sorry.

**Comment by mflmartin** [comment]
The problem is that prepare should prepare & copy all the files into the www folder. But it doesn't. With android, if you delete .tmp folder and run build android, it copies the files. But prepare does nothing at all.

Same goes with iOS. And I like to develop in windows, do ionic prepare ios, and then go to a Mac and compile in XCode from there. Which should be doable...

**Comment by mflmartin** [comment]
I confirm that other times, the .tmp folder is NOT present in the root project, therefore I can not erase, and the command also fails to update the iOS files. 

When running: `ionic prepare ios`

this is the stacktrace:

```
Running command: "C:\Program Files\nodejs\node.exe" D:\Sync\Martin\inProgress\p4q\suntrack_home\hooks\after_prepare\010_add_platform_class.js D:\Sync\Martin\inProgress\p4q\suntrack_home


add to body class: platform-ios

Running command: "C:\Program Files\nodejs\node.exe" D:\Sync\Martin\inProgress\p4q\suntrack_home\hooks\after_prepare\020_remove_sass_from_platforms.js D:\Sync\Martin\inProgress\p4q\suntrack_home
```

Shouldn't it also add an indication of the files that it is copying or updating? Or at least just `copy started` & `copy eneded` Because there is no indication that it does the job or that it is copying files. It would be nice to see which files get updated.
