### ISSUE TITLE
Searchbar still seleted when opening a modal

### ISSUE THREAD

**Issue by neelz040** [ionic-team/ionic#9010]
I have a Searchbar within my (header) toolbar of a certain page. When I open a modal from that page (with searchbar selected), the Searchbar is still selected/active once the modal is open. I can also still see the cursor and the keyboard. I can also still type in the searchbar.

Anyone else having this issue? Thanks

`My system information:

WKWebview

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.8.1
Xcode version: Xcode 8.1 Build version 8B62 `

**Comment by niels1027** [comment]
This seems like an easy fix? Still an issue for me with the following system information:

> Cordova CLI: 6.3.1
> Ionic Framework Version: 2.0.0-rc.3
> Ionic CLI Version: 2.1.0
> Ionic App Lib Version: 2.1.0-beta.1
> ios-deploy version: 1.9.0 
> ios-sim version: 5.0.8 
> OS: Mac OS X Sierra
> Node Version: v6.8.1
> Xcode version: Xcode 8.1 Build version 8B62

**Comment by niels1027** [comment]
still an issue for 'Ionic Framework Version: 2.0.0-rc.6'
