### ISSUE TITLE
NavController pop don't work and webview black

### ISSUE THREAD

**Issue by tunxiaoqing** [ionic-team/ionic#9022]
when webview has ion-tabs, if current webview runs 'NavController pop', the target webview turns black.
ionic version : ionic2RC2.
looking forward your help!!!
as follows:
![1](https://cloud.githubusercontent.com/assets/16894961/20001311/95d68f5e-a2b6-11e6-9a3f-f9f435f0f2e8.png)
![2](https://cloud.githubusercontent.com/assets/16894961/20001316/97a6c42a-a2b6-11e6-9d7d-d825eb445902.png)
![3](https://cloud.githubusercontent.com/assets/16894961/20001318/9a220dae-a2b6-11e6-82b3-31784e6c5343.jpg)
![4](https://cloud.githubusercontent.com/assets/16894961/20001323/9c170024-a2b6-11e6-8503-5c5d103cdedc.jpg)

**Comment by manucorporat** [comment]
If you just have one view in the navigation stack and you pop it, there are 0 views in the stack right?
So it gets black. I will add some kind of error message. Leaving this open.

**Comment by tunxiaoqing** [comment]
I wrote a demo to illustrate my problem.The program has 5 component Page1 Page2 Page3 Page4 and TabsPage.The Page1 is the root page ,click [Click me to Tabpage] will push Page2 to the stack,and the stack length is 2  in Page2 click[Click me to TabPage] will push  TabPage to  the stack and it's length is 3., the TabPage has two tabs——Page3 and Page4. but when I enter the Page4 .the stack length is 0.I click [go back] It shows black screen jsut as follow.I can'tback to the Page2. Is there anything wrong with me?
Sorry my English is poor .
![vji4bvok9 kyh0qe d1uk k](https://cloud.githubusercontent.com/assets/16894961/20086916/1ddfe5da-a5af-11e6-87cf-d412fc328708.png)
![wda7kh37idu0 4_soqrgb t](https://cloud.githubusercontent.com/assets/16894961/20086917/1e43d7fc-a5af-11e6-8b64-260d36248f75.png)
![a me4n 6dw8 7s f6 c](https://cloud.githubusercontent.com/assets/16894961/20086918/1e766960-a5af-11e6-9830-3e86478d9f4e.png)
![eig ko8l bu 4k4dl 4y w](https://cloud.githubusercontent.com/assets/16894961/20086919/1f7c63e6-a5af-11e6-979f-ea1f12620537.png)
![5t6 69 boiu538 0 6 8](https://cloud.githubusercontent.com/assets/16894961/20086934/3cbe7fca-a5af-11e6-81e1-b4762efe82dc.jpg)
![5t6 69 boiu538 0 6 8 1](https://cloud.githubusercontent.com/assets/16894961/20086935/3cfb3bf4-a5af-11e6-93f2-5996a0f28b2d.jpg)

**Comment by tonyawad88** [comment]
I have a similar problem described in here as well: #8713 .

I am going to start calling it the black screen of death :-) . I basically have the following code on my tabs page.

***HTML***
```
<ion-tabs color="darkblue" #myTabs class="test">
  <ion-tab [root]="tab1Root" tabTitle="HOME" tabIcon="home2" class="home2" (ionSelect)="TabSelect(0)"></ion-tab>
</ion-tabs>
```
***TS***
```
@ViewChild('myTabs') tabRef: Tabs;
TabSelect(index){
    this.tabRef.getByIndex(index).popToRoot({animate:true});
  }
```

Any way of checking on our side if a tabs nav stack has any views in it before popping ? @manucorporat 

Thank you ! 

![blackbg-on-poptoroot](https://cloud.githubusercontent.com/assets/3638322/20121030/612e4740-a5dd-11e6-9698-e62d17c3b303.gif)

**Comment by tonyawad88** [comment]
As a workaround I ended up using this:
```
if(this.tabRef.getByIndex(index)._views.length > 1){
      this.tabRef.getByIndex(index).popToRoot({animate:false});
}
```

**Comment by solsticesurfer** [comment]
The cause of this seems to be a change in what the NavController is. When a tab controller is on a page, the TabController is passed to the page's constructor as the NavController. This is what's causing the pop to fail. The TabController has a different nav stack and when pop() is called, either explicity on the NavController instance or by using the navPop decorator, the request fails as the stack is empty.

The failure can be prevented, of course, by checking NavController.canGoBack(), but this doesn't solve the problem that the NavController provided to the constructor is not the one that is expected.

Knowing this, what is the more appropriate approach?

**Comment by BramDecuypere** [comment]
Is there any progress in this issue?

**Comment by seetadev** [comment]
We are observing this issue in ionic 3.0.1 as well i.e. black screen upon navigating back to the root page. 
This is my `package.json`
![Package.json](https://cloud.githubusercontent.com/assets/4952656/25220782/7cef1a7c-25d0-11e7-8d80-be8ab7fabb42.png)

The issue with the error log is shown below: 
![Issue](https://cloud.githubusercontent.com/assets/4952656/25220780/7ce74cd4-25d0-11e7-86a8-5df69aa409b1.png)
![Blank Screen](https://cloud.githubusercontent.com/assets/4952656/25221142/ae2f7f2c-25d1-11e7-9196-6f3ce05eef96.png)
