### ISSUE TITLE
 Select commponent display duplicate when you open 2 modal overlap

### ISSUE THREAD

**Issue by windwp** [ionic-team/ionic#9044]
#### Short description of the problem:
 Select component need two click for display when you open 2 modal overlap

**Steps to reproduce:**
1. Open a modal  by ModalController
2. Open second modal overlap first modal
3. Display select component in second modal.
4. First click in select component ( nothing happen) then click again it will display action sheet
5. Close second modal action sheet from first click still appear :)

**Which Ionic Version?** 1.x or 2.x
ionic 2 rc 2

#### My repo that shows an example of your issue
https://github.com/windwp/ionic2test

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
OS:
Node Version: v4.6.0

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
