### ISSUE TITLE
Components either do not render, or render incorrectly, without ion-item directive in the component template

### ISSUE THREAD

**Issue by mtycholaz** [ionic-team/ionic#9080]
#### Short description of the problem:
Using a component as a child of an ion-item requires that component to have the ion-item within the template. This results in rendering issues, or nothing being rendered at all, or only parts of the component being rendered.

#### What behavior are you expecting?
Component templates should not require the ion-item in their template, and they should render correctly.

**Steps to reproduce:**
1. Make a component with a template
2. Make an ion-list with an ion-item and put your component as a child of the ion-item 

**Which Ionic Version?**  2 RC 2

#### Plunker that shows an example of your issue

http://plnkr.co/edit/WknnS0?p=preview

**Comment by brandyscarney** [comment]
Thanks for the issue! This goes back to issue https://github.com/driftyco/ionic/issues/6849 and also https://github.com/driftyco/ionic/issues/6880. I've added some documentation behind how item looks for content here: http://ionicframework.com/docs/v2/api/components/item/Item/#item-placement

I also have a forum post on this here: https://forum.ionicframework.com/t/confused-about-ion-item-usage/54116/10

You can actually use `item-content` or `ngProjectAs` for your specific case, but you'd also need to apply `100%` width to your `child-expected`:

Using `item-content`: 

```
<ion-item *ngFor="let item of items">
  <child-expected item-content style="width: 100%"></child-expected>
</ion-item>
```

Using `ngProjectAs`:

```
<ion-item *ngFor="let item of items">
  <child-expected ngProjectAs="ion-range" style="width: 100%"></child-expected>
</ion-item>
```

**Comment by brandyscarney** [comment]
I'm going to close this issue since it isn't something that we will be able to fix in v3, but it will be fixed in v4. Please see my comment [here](https://github.com/ionic-team/ionic/issues/12252#issuecomment-317062521) for more information. 

The solution I provided above is our recommended solution for v3 projects. Stay tuned though, we'll be asking for alpha & beta testers for v4!
