### ISSUE TITLE
ionic2 - bug(item-sliding) - ion-item slightly covers the first option button

### ISSUE THREAD

**Issue by zakton5** [ionic-team/ionic#9083]
#### Short description of the problem:
See title. Here's a GIF:

![sliding-item-cover-button](https://cloud.githubusercontent.com/assets/7013396/20114795/ad64b0dc-a5c3-11e6-8b43-97a806b36f0c.gif)

#### What behavior are you expecting?
I expect the ion-item to not cover the buttons  at all when it is slid open.

**Which Ionic Version?** 2.0-rc.2

**Comment by ghenry22** [comment]
I see this as well but it seems to depend slightly on the speed of the slide, if I slide over quickly it tends to go to the correct position, if I slide it slowly it will tend to stick partially covering the first option item as shown.

**Comment by zakton5** [comment]
I can't reproduce this anymore, so I'm going to close it.
