### ISSUE TITLE
ion-item-sliding not working with *ngFor dynamic list

### ISSUE THREAD

**Issue by DonShirley** [ionic-team/ionic#9095]
#### Short description of the problem:
See code below. Without *ngFor directive the sliding motion to show buttons is working. When using the *ngFor it is not working anymore.

#### What behavior are you expecting?

**Steps to reproduce:**
1. run

```html
<ion-content>
   <ion-list>
      <ion-item-divider light>
         24.03.2016
      </ion-item-divider>
      <ion-item-sliding *ngFor="let ticket of ticket_service.tickets_aktuell" #slidingItem>
         <ion-item>
            <p>{{ticket.Name}}</p>
            <p>{{ticket.Street}}, {{ticket.Postalcode}} {{ticket.City}}</p>
         </ion-item>
         <ion-item-options side="right" icon-left>
            <button ion-button color="secondary" (click)="ticket_bearbeiten(ticket)">
               <ion-icon name="construct"></ion-icon>
               Bearbeiten
            </button>
            <button ion-button default (click)="ticket_details(ticket)">
               <ion-icon name="paper"></ion-icon>
               Details
            </button>
         </ion-item-options>
      </ion-item-sliding>
   </ion-list>
</ion-content>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
2.1.4

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
--------------------------------
--------------------------------

Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.1

Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
OS:
Node Version: v6.9.1

**Comment by jkinman** [comment]
Im having the same problem. Did you find a solution to this?

**Comment by bholben** [comment]
I'm having problems here too.  I did find that the `*ngFor` worked fine when I was doing a list like in the example on the component docs page.  However, when I combined this with a list divider and `ion-item-group`, it broke.  I'm running Ionic Framework Version 2.0.0-rc.3.

**Comment by DonShirley** [comment]
I changed to using <ion-list-header> instead of <ion-item-divider>. It's working for me right now.

**Comment by m5rk** [comment]
I ran into a similar issue:  sliding options stopped working with the RC3 upgrade, but only on Android. I reverted to RC2 and sliding options works once again.

**Comment by spinicrus** [comment]
same here, android.

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45

**Comment by manybothans** [comment]
also seeing it on iOS 10.2

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by shaneparsons** [comment]
I'm also having this problem on Android... Haven't tested iOS yet.

Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.3.2 Build version 8E2002

**Comment by shaneparsons** [comment]
@brandyscarney any progress on this? Any workarounds other than not using the sliding lists?

**Comment by qiluo** [comment]
hi all, I finally succeeded with below, put `ngFor` on `ion-item-sliding`
```
<ion-item-sliding *ngFor="let item of items">
        <ion-item>
          ...
        </ion-item>

        <ion-item-options side="right">
          <button ion-button>
            {{'MODIFY'|translate}}
          </button>
          <button ion-button color="danger">
            {{'DELETE'|translate}}
          </button>
        </ion-item-options>

      </ion-item-sliding>
```

**Comment by GunaSekhar1** [comment]
The below code worked for me. Hope it works for you also.
<ion-list>
    <ion-item-sliding *ngFor="let eachRecipe of allRecipes">
      <ion-item (click)="onItem(eachRecipe, 'favourite')">
        <img class="wid-hi-50" src="{{eachRecipe.pictures_link}}">
        <div>
          <p>{{eachRecipe.courses}}</p>
          <h2>{{eachRecipe.title}}</h2>
        </div>
        <ion-icon class="ios-add-size icon icon-md ios-arrow-forward"></ion-icon>
      </ion-item>
      <ion-item-options side="right">
       
       <button danger (click)="removeItem(eachRecipe)" ion-button color="danger"><ion-icon name="trash"></ion-icon> Delete</button>
      </ion-item-options>
    </ion-item-sliding>
  </ion-list>

**Comment by yoojene** [comment]
@GunaSekhar1's solution works well, moving the` *ngFor` up one level from `<ion-item>` to` <ion-item-sliding>`

**Comment by shamank** [comment]
Not working either. In my case, it reveals the options layer but there's no sliding effect at all and the item layer keeps in the same place, under the options one. I realized that `transform: translate3d(-30px, 0px, 0px);` is being applied to `<ion-item>`. If it's applied to `<item-inner>` it works (at least the layer is moved -30px, I don't know if the sliding effect would be correctly applied too).
![screenshot-localhost-8100-2017-06-28-15-04-36](https://user-images.githubusercontent.com/819192/27652954-ec4de8c0-5c13-11e7-9a35-d615273d497b.png)

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : Linux 3.19
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3 
```

**Comment by shaneparsons** [comment]
Yeah, moving the `*ngFor` didn't do anything for me either.

In my case, the problem was only there on android, and only when I was updating the messages from an observable. It seems that everytime the messages were updated, it would hide any sliding panel that was open.

e.g.

Innitial (problematic on android) code
```ts
this.events.subscribe('location:updated', () => {
    this.getMessages();
});
```
Current (working) code
```ts
this.events.subscribe('location:updated', () => {
    if (this.platform.is('ios')) {
        this.getMessages();
    });
});
```

Since it seems to be an android issue only, I left it as is for ios, and I'm now just using a _pull down to refresh_ implementation for android. It isn't ideal... but it works.

**Comment by shamank** [comment]
It looks like adding a custom class to `<ion-item>` broke the thing: `class="priority-{{ t.priority.level }}"`. After removing that, it worked as expected.

**Comment by felix9607** [comment]
`<ion-list>
        <ion-item-sliding *ngFor="let maschine of maschinenArray">
            <ion-item color='primary'>
                <ion-avatar item-start>
                    <img alt="Bild fehlt" src="assets/img/maschinen/maschine{{maschine.typ}}.jpg"></ion-avatar>
                <h2> {{maschine.name}}</h2>
                <h3>{{maschine.ip}}</h3>
            </ion-item>
            <ion-item-options>
                <button ion-button color="danger" icon-start>
                          <ion-icon name="trash"></ion-icon>
                          Delete             
                        </button>

                <button ion-button color="secondary" icon-start>
                          <ion-icon name="mail"></ion-icon>
                          Ticket
                        </button>
            </ion-item-options>
        </ion-item-sliding>
    </ion-list>`

this Code worked for me perfectly. i could even took a value to Display a specific img in the list
