### ISSUE TITLE
Feature request : full width fixed block in ion-content

### ISSUE THREAD

**Issue by movrack** [ionic-team/ionic#9110]
As explained in https://github.com/driftyco/ionic/issues/9071 , I would like element non scrollable in ion-content. 
Comportement look to be same as ion-header or ion-footer but could be inserted inside ion-content.

Example of used: a page with following structure
- ion-header
- ion-content
   -content-header (fixed)
   -content scroll (actually current ion-content)
   -content fixed
   -content-scroll (actually current ion-content)
   -content-footer (fixed)
-ion-footer

I know the existance of "ion-fixed" attribute (https://github.com/driftyco/ionic-site/issues/776#issuecomment-258487040), but my use look to be not the right behaviour and so, ion-fixed look to be more for a use like a fab button or something else who must be overlaps the scroll content.
In my case, the fixed element has the same level than the scroll part and don't have != z-index who make an overlaps.

example of rendering:
http://run.plnkr.co/NekFUEmOOw3k8z7P/

moreover, some other look for this and has some workarround:
https://forum.ionicframework.com/t/scroll-false-in-ionic-2/64571/12?u=mse

**Comment by melioring** [comment]
Any news on this issue? Still no solution for the overlaps?

**Comment by melioring** [comment]
@peter please look at the messages before closing an issue, the issue is not ion-content being fixed, we should be able to make a div element inside ion-content fixed so that the other elements inside the ion-content should not overlap that div when scrolling

**Comment by peterpeterparker** [comment]
@melioring I found a way to solve the issue #10291 I opened, therefore my issue didn't need to be solved and I closed it. 

But this issue #9110 remains open.

**Comment by wsjwong** [comment]
Could you update the plnkr? Just by looking at your text description, I think that @peterpeterparker 's solution could achieve it.
