### ISSUE TITLE
(bug): ion-input on iOS shows two inputs (aria-hidden issue)

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#9159]
#### Short description of the problem:
As discussed with @jgw96 and @brandyscarney, on iOS devices an `ion-input` control adds two input controls to the DOM. One has `aria-hidden`. However when styling the `ion-input` this second input can become visible. 

#### What behavior are you expecting?
The second ion-input added for accessibility on Safari needs to not show. 

![image](https://cloud.githubusercontent.com/assets/2852839/20283069/334f1024-aac0-11e6-8575-0638adc7ed1a.png)

The temporary SCSS fix for this is to add:
```
  ion-item:nth-child(3) {
    input {
      text-transform: none;
    }
  }
```
 

**Which Ionic Version?**  2.x

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.43
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by jsunshoshana** [comment]
I'm having this issue as well, except the second text field is one pixel in width. Your fix does not seem to be working for me. Did you figure anything more out about what's causing this, or how to fix it?

**Comment by dylanvdmerwe** [comment]
This is still an issue on ionic 3.1.0 when using WkWebview plugin.

**Comment by jsunshoshana** [comment]
For me, this this issue was caused because I applied the css
`input {
  background-color: white;
}`

I changed it to
`input[type=text].text-input {
  background-color: white;
}`
and it no longer applies the background color to the second input.
