### ISSUE TITLE
got a wrong value for margin-top of scroll-content 

### ISSUE THREAD

**Issue by izee** [ionic-team/ionic#9162]
when the ion-header's height fill up with inner elements and more than `min-height`, the margin-top of scroll-content got a wrong value compute with the min-height.
I think re-compute the margin-top of scroll-content after ion-header's height changed is better.

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.39
OS:
Node Version: v6.7.0

**Comment by tleguijt** [comment]
+1 for this one

**Comment by manucorporat** [comment]
Can you provide some code that reproduces the issue?

**Comment by izee** [comment]
any child element to be overflow on height of ion-header.
if overflow happened after scroll-content compute, this issue will reproduce.

**Comment by erperejildo** [comment]
I'm facing same issue. Working well on mobile fut sometimes (totally randomly) it gets a wrong calculation on desktop.

This issue still on latest version after 1 year

**Comment by soramister** [comment]
I have the same issue, when I add a segment in ion-header.

Here my code:
<ion-header>
	<ion-navbar>
		<ion-title>Title</ion-title>
	</ion-navbar>
	<header>
		<ion-segment [(ngModel)]="screen" (ionChange)="segmentChanged($event)">
			<ion-segment-button value="screen1">Screen 1</ion-segment-button>
			<ion-segment-button value="screen2">Screen 2</ion-segment-button>
			<ion-segment-button value="screen3">Screen 3</ion-segment-button>
		</ion-segment>
	</header>
</ion-header>

**Comment by kabus202** [comment]
any workarounds for this issue?

**Comment by nen155** [comment]
I have the same issue when I add a expandable header

**Comment by davidst2017** [comment]
Good to see I'm not alone. Right now I can think of some workarounds, however does anyone of you found an official solution?
