### ISSUE TITLE
ion-infinite-scroll will not load more items if initial batch does not make viewport large enough for scrolling

### ISSUE THREAD

**Issue by wwoods** [ionic-team/ionic#9209]
#### Short description of the problem:

The `ion-infinite-scroll` component works by listening for an `onScroll` event.  However, if the initial items loaded do not trigger such an event, then the ion-infinite-scroll will never trigger an `ionInfinite` callback, resulting in a broken page.

#### What behavior are you expecting?

I would expect that, when the `InfiniteScroll` object is enabled (listener added), and also after any `ionInfinite.complete()` call, that the current `onScroll` check would be manually run in order to see if another `ionInfinite` event needs to be triggered immediately.

Currently, to workaround this, I have two lines executed after both the initial page loading and after each `ionInfiniteEvent.complete()` call:

```ts
setTimeout(() => {
  this.infinite._lastCheck = 0;
  this.infinite._onScroll();
}, 0);
```

**Steps to reproduce:**
1. Put in an infinite component, but only load 1 or 2 items so that there is no scrolling on the page.
2. See that `ionInfinite` never gets triggered.
3. Dig into ionic's very clean source to figure out the workaround.

**Which Ionic Version?** 2.0 RC2

**Comment by suau** [comment]
@wwoods I'm running into the same issue, could you explain your workaround ?
I tried to get a reference to the InfiniteScroll object using `@ViewChild` but keep on getting `_onScroll() is not a function`

**Comment by wwoods** [comment]
@suau Sure, I'll share my exact approach.  Note that the code uses async/await, as I'm targeting ES6 right now (hopefully the Ionic team enables typescript 2.1 support soon).  You could adapt it to traditional callbacks, but that's up to you.  Async/await is so much cleaner.  

Look for the `setTimeout` in the below code if you want the crib notes.  Otherwise...

When I use `ion-infinite`, I attach a custom attribute that adds the loader logic, and bind `[items]` to the array (a property of the page `Component`) that will be populated and `[loadMore]` to a function that A) takes no arguments (has its own memory) and B) queries my database and yields an array of items to add to the `[items]` array:

```html
<ion-infinite-scroll streamer [items]="items" [loadMore]="getNextItems">
  <ion-infinite-scroll-content></ion-infinite-scroll-content>
</ion-infinite-scroll>
```

To get this working, copy the below file as e.g. `streamer.ts`, import `Streamer` to your `app.module.ts` and put `Streamer` in `@NgModule`'s `declarations` parameter.

** Warning ** - The dirtiest part of this code is probably the `(async()...)().catch(console.error)`.  Any errors in the loader will just go to the console, you'll want to hook that into your own error reporting (probably).

```ts
import {Directive, EventEmitter, Host, Input, Output} from '@angular/core';
import {InfiniteScroll} from 'ionic-angular';

export type Callback = {():Promise<Array<any>>}|undefined;

@Directive({
  selector: '[streamer]',
})
export class Streamer {
  @Input() items:Array<any> = [];
  @Output() loaded = new EventEmitter<Array<any>>();
  @Output() loadStart = new EventEmitter<void>();
  @Input() set loadMore(cb:Callback) {
    if (this._loadMore === cb) {
      return;
    }

    this._loadMore = cb;
    this._loadFirst();
  }
  _loadIndex:number = 0;
  _loadMore:Callback = undefined;


  constructor(@Host() public infinite:InfiniteScroll) {
  }


  ngOnInit() {
    this.infinite.ionInfinite.subscribe(this._loadNext.bind(this));
    this._loadFirst();
  }


  _loadFirst() {
    this.items.length = 0;
    this.infinite.enable(false);
    this._loadNext(null);
  }


  _loadNext(infiniteEvent:any|null) {
    this._loadIndex++;
    const loadIndex = this._loadIndex;
    (async() => {
      try {
        if (this._loadMore !== undefined) {
          this.loadStart.emit();
          let items = await this._loadMore();

          if (loadIndex !== this._loadIndex) {
            //This callback got replaced.
            return;
          }

          if (items.length === 0) {
            this.infinite.enable(false);
            this.loaded.emit([]);
          }
          else {
            //First load?
            if (this.items.length === 0) {
              this.infinite.enable(true);
            }
            this.items.push.apply(this.items, items);
            this.loaded.emit(items);

            //Shame on you, infinite.  Need to manually re-trigger _onScroll, Issue #1111
            setTimeout(() => {
              this.infinite._lastCheck = 0;
              this.infinite._onScroll();
            }, 0);
          }
        }
        else {
          this.loaded.emit([]);
        }
      }
      finally {
        if (infiniteEvent !== null) {
          infiniteEvent.complete();
        }
      }
    })().catch(console.error);
  }
}
```

**Comment by suau** [comment]
@wwoods thanks a lot !

Getting the component instance using `@Host() public infinite:InfiniteScroll` from a directive worked perfectly fine.
But I didn't really want to change my loading process and preferred to get an instance of InfiniteScroll directly from my Page component and just kick off the first loading cycle directly from `ionViewDidLoad()` with `_onScroll()`, after the loading is done, I would just call `complete()` and `_onScroll()` again.

The weird issue I ran into was following:

`
<ion-infinite-scroll #infinite (ionInfinite)="loadMoreData($event)"></ion-infinite-scroll>
...
...
@ViewChild(InfiniteScroll) infinite: InfiniteScroll; // THIS WORKS
@ViewChild('infinite') infinite: InfiniteScroll; // THIS DOES NOT` 

So I got it working with the first ViewChild method, but I'd still like to know why second one doesn't work.

**Comment by shprink** [comment]
this is still happening in 3.2.1. 

![image](https://cloud.githubusercontent.com/assets/1388706/26319209/60fd1690-3f1e-11e7-86cf-fe796e91d57d.png)

After loading 4 items, infinite scroll should be triggered a second time because within the viewport.

**Comment by znegva** [comment]
still happening in 3.9.2

my silly workaround is to force loading elements until the list height is greater than device-height

```
ngOnInit(){
  let tryLoadMoreData = () => {
    let l = document.getElementById('datalist');
    if( l &&	//is there a list?
        (this.platform.height() > l.scrollHeight) && //is the list shorter than the screen
        this.failedLoadAttempts < 20 //we should not try forever
    ){
      this.loadMoreData({ //dummy function
        complete: () => {},
        enable: () => {}
      });
    }else{
      clearInterval(dataListFillInterval);
    }
  }
  dataListFillInterval = setInterval(tryLoadMoreData, 500);
}

public loadMoreData(infiniteScroll){
 ... // load data and add to list here
 ... //count this.failedLoadAttempts here
}
```

**Comment by Snead** [comment]
Bump

**Comment by aelx311** [comment]
@suau What did you pass to _onScroll()?

**Comment by derWebdesigner** [comment]
Is this issue resolved with v4?
