### ISSUE TITLE
duplication add scrolling for scroll-content

### ISSUE THREAD

**Issue by izee** [ionic-team/ionic#9224]
#### Short description of the problem:
duplication add scrolling for scroll-content while the focus moved from `input a` to `input b`.

 
#### System information:

 ordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.7.0
Xcode version: Not installed

**Comment by finalxcode** [comment]
+1
