### ISSUE TITLE
Click(tappable) issue on scroll - IOS

### ISSUE THREAD

**Issue by ghost** [ionic-team/ionic#9239]
Hello , when i am scrolling down on the app and when i try to give a stop to the page by tapping my finger  , i enter to the page instead of giving a stop to the pages ( the app is a bit sensitive right now it doesn't understand whether of i want to stop on a page or if i want to enter to the page  )  Is it possible to put a freeze on the app when i am scrolling down or up to avoid tapping pages by a mistake instead of stoping on the page ?
 Thanks

```
<ion-list>
    <ion-card (click)="goNews(post)" tappable>
        ......
    </ion-card>
</ion-list>
```

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3-201611181540
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.44
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62 
```

**Comment by jwenzler** [comment]
Also happening here since RC2.  Huge issue when it comes to scrolling. Also causes issues while trying to use sliding items in a scrolling list.

**Comment by filipsuk** [comment]
This is still a problem in current version 2.1.0. It can be partially solved by removing `tappable`, however then there is a opposite problem – items are too difficult to click on. Huge pain for us :/
I think this is related to old issue https://github.com/driftyco/ionic/issues/1438 (and many others).
