### ISSUE TITLE
itemReorder not working with itemSliding on iOS

### ISSUE THREAD

**Issue by manuelroth** [ionic-team/ionic#9244]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
The combination of itemReorder and itemSliding doesn't seem to work on iOS. The HTML below won't properly reorder the items on the GUI on iOS. By "reorder the items on the GUI", I mean that the selected item can be moved, but no other items shift as you move the selected item:

![](https://cdn-enterprise.discourse.org/ionicframework/uploads/default/optimized/3X/8/5/858beacb98523c9d72c287e1d1e7b628f45d1153_1_690x300.png)

Am I doing somthing wrong? If I do the same sort of thing with a simple ion-item (non-sliding), reordering works fine on iOS. If I use the sliding item in this manner on non-iOS, it works fine.

**Expected behavior:**
Other items shift as you move the selected item.

**Steps to reproduce:**
- Create a list with reorder attribute set to true
- The list should consists of ion-item elements which are wrapped with ion-item-sliding
- Run the app on iOS and try to reorder items

**Related code:**

```
<ion-list reorder="true" (ionItemReorder)="reorderItems($event)">
    <ion-item-sliding *ngFor="let ski of skis">
      <ion-item>
        <ion-checkbox color="primary" item-left checked="false" (ionChange)="toggleCheckbox(ski.id)"></ion-checkbox>
        <ion-label>
          <h2>{{ski.name}}</h2>
          <p>{{ski.description}}</p>
        </ion-label>
      </ion-item>
      <ion-item-options>
          <button ion-button color="favorite" (click)="goToUpdatePage(ski)">Bearbeiten</button>
          <button ion-button color="danger" (click)="showRemoveAlert(ski)">Löschen</button>
      </ion-item-options>
    </ion-item-sliding>
</ion-list>
```

**Other information:**
There exists already a forum entry for this issue: https://forum.ionicframework.com/t/itemreorder-not-working-with-itemsliding-on-ios/64385

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.6.0
Xcode version: Xcode 8.1 Build version 8T61a
```

**Comment by manuelroth** [comment]
@manucorporat Just saw that RC4 was just released. Unfortunately I can still see this error. Are you intending to fix this in a future release?

**Comment by tzimpel** [comment]
Problem still exists in current stable ionic 2.0. Will this be fixed in a future release? In Browser and on Android, the combination is working, but not on iOS (device and simulator).

**Comment by snortblt** [comment]
Any update on this issue? Is there a recommended workaround?

**Comment by vignesh-nethaji** [comment]
i am also got that error . if any update ,just remind me

**Comment by Dennis-Do** [comment]
Same here!

**Comment by zkendall** [comment]
This works for me. Does it work for you when you test it on your desktop browser?

**Comment by vishalv26** [comment]
any fix?
