### ISSUE TITLE
Popover auto dismiss focus of active element by default

### ISSUE THREAD

**Issue by nitrotm** [ionic-team/ionic#9304]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When opening a popover from PopoverController, the default behavior is to automatically blur any focused element. Sometimes, it is not a wanted behavior.

**Expected behavior:**
An option should be available to tell the PopoverCmp if we want to dismiss automatically focus or not.

**Steps to reproduce:**
A typical use-case, is opening a popover when the user focus an input field. The popover is showing extra-information related to the user input and should be dismissed when the input field focus is removed. In this situation, we want to keep the focus in the input field (unless the user explicitly change the focus).

**Other information:**
I was able to 'patch' the PopoverCmp in a hackish way to accomplish what I wanted (getting rid of the code disabling active focus):

let popover = popoverCtrl.create(...);

popover.component.prototype.ionViewPreLoad = function() {
  this._load(this._navParams.data.component);
};

But a dedicated option 'dontBlurFocus' would be much better/safer on the long run (defaulting to false, so the default behavior would be the same as now).

**Comment by valivvvv** [comment]
Yes, I'm in the same situation, where showing a popover forces my input out of focus. Very annoying.

**Comment by AkshayAote** [comment]
duplicate symbol _OBJC_IVAR_$_APPLocalNotification.deviceready in:
    /Users/silicon/Library/Developer/Xcode/DerivedData/DVR-fkgopbggtilucbfhxvkyiibdatcy/Build/Intermediates.noindex/DVR.build/Debug-iphoneos/DVR.build/Objects-normal/arm64/APPLocalNotification-b9bdfeff695ce11db6a601bc1cc9a748ec1072cf45651f2b6564649f8c77286b.o
    /Users/silicon/Library/Developer/Xcode/DerivedData/DVR-fkgopbggtilucbfhxvkyiibdatcy/Build/Intermediates.noindex/DVR.build/Debug-iphoneos/DVR.build/Objects-normal/arm64/APPLocalNotification-b9bdfeff695ce11db6a601bc1cc9a74876cf0a019d5973dde97ba1ea0d9bf15f.o
duplicate symbol _OBJC_CLASS_$_APPLocalNotification in:
    /Users/silicon/Library/Developer/Xcode/DerivedData/DVR-fkgopbggtilucbfhxvkyiibdatcy/Build/Intermediates.noindex/DVR.build/Debug-iphoneos/DVR.build/Objects-normal/arm64/APPLocalNotification-b9bdfeff695ce11db6a601bc1cc9a748ec1072cf45651f2b6564649f8c77286b.o
    /Users/silicon/Library/Developer/Xcode/DerivedData/DVR-fkgopbggtilucbfhxvkyiibdatcy/Build/Intermediates.noindex/DVR.build/Debug-iphoneos/DVR.build/Objects-normal/arm64/APPLocalNotification-b9bdfeff695ce11db6a601bc1cc9a74876cf0a019d5973dde97ba1ea0d9bf15f.o
duplicate symbol _OBJC_METACLASS_$_APPLocalNotification in:
    /Users/silicon/Library/Developer/Xcode/DerivedData/DVR-fkgopbggtilucbfhxvkyiibdatcy/Build/Intermediates.noindex/DVR.build/Debug-iphoneos/DVR.build/Objects-normal/arm64/APPLocalNotification-b9bdfeff695ce11db6a601bc1cc9a748ec1072cf45651f2b6564649f8c77286b.o
    /Users/silicon/Library/Developer/Xcode/DerivedData/DVR-fkgopbggtilucbfhxvkyiibdatcy/Build/Intermediates.noindex/DVR.build/Debug-iphoneos/DVR.build/Objects-normal/arm64/APPLocalNotification-b9bdfeff695ce11db6a601bc1cc9a74876cf0a019d5973dde97ba1ea0d9bf15f.o
duplicate symbol _OBJC_IVAR_$_APPLocalNotification.eventQueue in:
    /Users/silicon/Library/Developer/Xcode/DerivedData/DVR-fkgopbggtilucbfhxvkyiibdatcy/Build/Intermediates.noindex/DVR.build/Debug-iphoneos/DVR.build/Objects-normal/arm64/APPLocalNotification-b9bdfeff695ce11db6a601bc1cc9a748ec1072cf45651f2b6564649f8c77286b.o
    /Users/silicon/Library/Developer/Xcode/DerivedData/DVR-fkgopbggtilucbfhxvkyiibdatcy/Build/Intermediates.noindex/DVR.build/Debug-iphoneos/DVR.build/Objects-normal/arm64/APPLocalNotification-b9bdfeff695ce11db6a601bc1cc9a74876cf0a019d5973dde97ba1ea0d9bf15f.o
ld: 4 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)



I am Getting the above error in xcode for IOS app
