### ISSUE TITLE
ionViewWillEnter not fire (push page out of popover and go back)

### ISSUE THREAD

**Issue by matzemoto77** [ionic-team/ionic#9306]
**Ionic version:**  (check one with "x")
[x] **2** RC01 - RC03

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
I have simple tab-layout. Inside Tab-Page i have a popover. Out of Popover i push a page into stack.
On pushed page i go back with default Back Button.
> On my Tab-Page ionViewWillEnter not fire.

I get this problem just if i push a page out of popover and go back. 

**Other information:**
Its my first post so be careful with criticism ._.

```
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

**Comment by falkoschumann** [comment]
Same here with a side menu based app. Select a page with list from side menu, push a new page with details, go back to list page does not trigger `ionViewWillEnter`.

This behavior is only on iOS device, not in desktop browser.

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by gnujeremie** [comment]
Same here, when opening a page from a popover menu, coming back to the previous page does not fire ```ionViewWillEnter```.

**Comment by josh-m-sharpe** [comment]
I've created a v3 demo app for this problem. @jgw96 could you please add the v3 label?

https://github.com/josh-m-sharpe/popoverdidload

Also, I've verified this happens while emulating both ios and android in Chrome -- I haven't tried on an actual device.

**Comment by josh-m-sharpe** [comment]
In the meantime - does anyone have a workaround for this?  My use case was figuring out some way to close the popover when the user comes back to the page where they opened it:

To be crystal clear:
1) user is on Page1
2) user opens popover
3) user clicks link in popover to go to Page2
4) on Page2, user clicks back button
5) user is back on Page1, but popover is still open.

.. I figured ionViewDidEnter() was a good place to close the popover, but.. it doesn't fire.

**Comment by CarlosRoig** [comment]
It's been a while since this bug appeared. Is anyone looking at this? Or is there any workaround to solve it?

**Comment by josh-m-sharpe** [comment]
It's still not tagged correctly either
