### ISSUE TITLE
Inputs Truncate for a Moment when they become active (tested on iOS mobile, Android Unknown, not affecting browser)

### ISSUE THREAD

**Issue by wbhob** [ionic-team/ionic#9319]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When activating an input, the label will truncate. For example, if the label is "Username", it becomes "Usern..." for about 700ms on activation, then is restored to "Username".
**Expected behavior:**

The label should not change.
**Steps to reproduce:**

http://plnkr.co/edit/VSMxsP?p=preview
**Related code:**

```
<ion-list>
    <ion-list-header hideWhen="android"></ion-list-header>
    <ion-item>
        <ion-label color="primary">Username</ion-label>
        <ion-input type="text"></ion-input>
    </ion-item>
</ion-list>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by dylanvdmerwe** [comment]
Does this happen on a device or in the browser?

**Comment by wbhob** [comment]
Device

**Comment by jgw96** [comment]
@wbhob Thanks for opening an issue with us! Unfortunately I am having trouble reproducing this issue. What device and OS are you testing with? Thanks!

**Comment by wbhob** [comment]
I am testing on iPhone 7, iOS 10(.1). Tested with RC3, and it does not happen in Ionic Serve.

**Comment by wbhob** [comment]
I think it has something to do with the keyboard.

**Comment by wbhob** [comment]
I know this has been open for a while, were you able to replicate this issue?
