### ISSUE TITLE
Events broken or not working on RC3

### ISSUE THREAD

**Issue by robgaleano** [ionic-team/ionic#9320]
**Ionic version:** 
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior & Steps to reproduce:**
From a view i'm making a push to another with some data, when the 2nd view pushes and loads it shows my data as expected, everything works fine here.
The view suppose to work as a list selection of items, i select 2 items for example and save the items into an array and press a button that calls a service that stores that items on DB.
Here's when it comes the event handling, when i press the save button and get success response from the service i'm publishing the event as public with the data i need and making a pop to the 1st view to get that data on the ionViewDidEnter method.
Inside the ionViewDidEnter i'm making the event.subscribe callback to that event but it never enters inside the callback. This was working perfectly when my app was in beta 11.

**Expected behavior:**
I'm expecting the event to enter inside the subscribe callback to do some extra logic that needs the data from the child view.

**Related code:**
1st view call to push to 2nd view
```
addFacebook() {
    let token;
    let loading;
    this.oauth.logInVia(this.facebookProvider).then((success) => {
      loading = this.loadingCtrl.create({
        dismissOnPageChange: true
      });
      loading.present();

      token = success;
      console.log(token);
      this.socialService.addFacebook(token.code).subscribe(response => {
        console.log(response);
        if (response.meta.code == 200) {
          let networkData = response.data;
          this.nav.push(SelectSocialPage, { selectedNetworks: networkData, networkType: '2' });
        }
      }, (error) => {
        if (error.meta.code == 107) {
          loading.dismiss();
          let toast = this.showToast('Error getting data please try again', 3000, null);
          toast.present();
        }
      });
    }, (error) => {
      loading.dismiss();
      let toast = this.showToast('Error with provider', 3000, null);
      toast.present();
    });
  }
```

then when opening 2nd view i call this method to close second view and to provide 1st view with the users selected data publishing the event entering on response success  meta.code == 201
```
saveSelectedNetworks() {
        this.socialservice.saveUsers(this.selectedNetworkUsers, this.networkType).subscribe((response) => {
            console.log(response,'tha response');
            
            //Get data from service
            if (response.meta.code == 201) {
                //Refresh data when a new network is added
                let data: any = [];
                data[0] = true;
                this.events.publish('modal:saveNetworks', data);
                console.log(data);
                console.log('before pop');
                                
                this.nav.pop();
            }
        }, (error) => {
            console.log(error,'error redes');
            switch (error.meta.code) {
                case 22: {
                    let data: any = [];
                    data[0] = false;
                    //Cannot add more users
                    data[1] = 1;
                    this.events.publish('modal:saveNetworks', data);
                    break;
                }
                case 23: {
                    let data: any = [];
                    data[0] = false;
                    //Some users could not be added
                    data[1] = 2;
                    this.events.publish('modal:saveNetworks', data);
                    break;
                }
                case 203: {
                    let data: any = [];
                    data[0] = false;
                    //General error
                    data[1] = 3;
                    this.events.publish('modal:saveNetworks', data);
                    break;
                }
            }
        });
    }
```

Then it pops to 1st view with the data array of users that were added expecting to catch on this but it prints the first console log but not the second inside the subscribe wich means it doesn't catch the event 
```
ionViewDidEnter() {
    console.log('ionViewDidEnter');
    this.events.subscribe('modal:saveNetworks', (data) => {
      console.log(data);
      if (data[0] == true) {
        this.refreshDataMessage('Users added successfully');
      } else if (data[0] == false) {
        switch (data[1]) {
          case 1: {
            this.showToast('You cannot add more users', 3000, false);
            break;
          }
          case 2: {
            this.showToast('Some users could not be added', 3000, false);
            break;
          }
          case 3: {
            this.showToast('Something went wrong, please try again', 3000, false);
            break;
          }
        }
      }
      this.events.unsubscribe('modal:saveNetworks', null);
    });
  }
```
Then i expect with the refreshDataMessage method to reload the page with the new users that where added on 2nd page but if it does not enter on the event i could not do anything

**Ionic info:**:

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by corran2go** [comment]
I have the same issue, in RC2 both click handlers were correctly called for chapters and subchapters, in RC3 only the chapters handler gets call in all cases:

```html
<ion-list>
  <ion-item *ngFor="let chapter of chapters" (click)="onSelect(chapter)">
    P{{chapter.nr}} {{chapter.title}}
    <ion-list>
      <ion-item *ngFor="let subchapter of chapter.subchapters" (click)="onSubSelect(subchapter, $event)">
        {{subchapter.nr}} {{subchapter.title}}
      </ion-item>
    </ion-list>
  </ion-item>
</ion-list>
```

```javascript
  onSelect(chapter: ChapterModel) {
    console.log('onSelect', chapter);
  }

  onSubSelect(subchapter: ChapterModel, event: Event) {
    event.stopPropagation();
    console.log('onSubSelect', subchapter);
  }
```

**Comment by ncapito** [comment]
@corran2go  your issue doesn't sound related to to the issue @robgaleano  is experiencing.  One is using the Events service and yours is likely an issue with something going on in your markup (html) that is gobbling up your click event.    I'm working on reproducing the issue now in an e2e test.

**Comment by corran2go** [comment]
@ncapito you're right, I've posted this in the wrong thread. My issue is already documented here  [#9327](https://github.com/driftyco/ionic/issues/9327)

**Comment by msaelices** [comment]
I found this same bug. After RC3, the `app:rotated` event is not fired:

    this.events.subscribe('app:rotated', (evts) => {
        console.log('Screen rotated');
    });
