### ISSUE TITLE
Ionic 2 - Bug datetime ?

### ISSUE THREAD

**Issue by ekwoue** [ionic-team/ionic#9371]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
When I emulate ionic app on iphone, the datetime field doesn't change value after select one.

**Expected behavior:**
It should change the date

**Related code:**
My fields are a string values :
```
<ion-content>
    <form [formGroup]="form">
        <ion-list>
            <ion-list-header>
                Title
            </ion-list-header>
            <ion-item>
                <ion-label stacked>Date</ion-label>
                <ion-datetime displayFormat="DD/MM/YYYY" formControlName="date" [(ngModel)]="calendar.date"></ion-datetime>
            </ion-item>
            <ion-item>
                <ion-label stacked>Start</ion-label>
                <ion-datetime displayFormat="HH:mm" formControlName="startHour" [(ngModel)]="calendar.startHour"></ion-datetime>
            </ion-item>
            <ion-item>
                <ion-label stacked>End</ion-label>
                <ion-datetime displayFormat="HH:mm" formControlName="endHour" [(ngModel)]="calendar.endHour"></ion-datetime>
            </ion-item>
        </ion-list>
    </form>
</ion-content>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.39
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 7.3.1 Build version 7D1014

It's a bug or a problem in my app ?

Thank you!

**Comment by graphefruit** [comment]
Have you set your data inside the controller?
`calender:any = {
startHour:""
}`
?
If yes, try to set `startHour:undefined`
