### ISSUE TITLE
iOS Allows overscroll behind ActionSheet

### ISSUE THREAD

**Issue by hotforfeature** [ionic-team/ionic#9426]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
It is possible to scroll the background when the app has presented a component, such as an action sheet.

![ios-overflow](https://cloud.githubusercontent.com/assets/14365924/20758330/0fa40f78-b6df-11e6-9667-cef0646705a8.gif)
-->

**Expected behavior:**
Background scrolling should be disabled when a `ViewController` is presented through `app.present()`

**Other information:**
This could be fixed by disabling scrolling on the `<div class="scroll-content">` of `<ion-content>` whenever the app presents something. I imagine this bug also affects `<ion-refresher>` and may allow refreshing to occur when something is presented.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.1 Build version 8B62 
```

**Comment by manucorporat** [comment]
@hotforfeature can you try against nightly?

```
npm install ionic-angular@nightly --save
```

**Comment by hotforfeature** [comment]
@manucorporat this still happens on nightly

**Comment by manucorporat** [comment]
>This could be fixed by disabling scrolling on the <div class="scroll-content"> of <ion-content> whenever the app presents something. I imagine this bug also affects <ion-refresher> and may allow refreshing to occur when something is presented.

There is not such API to disable scroll in Safari/Webkit.

Are you using the ionic's WKWebview plugin?

**Comment by hotforfeature** [comment]
I am using the default UIWebView component. No API is needed, `<div class="scroll-content">` in `<ion-content>` is the culprit. I have already verified that setting `overflow-y: hidden;` prevents scrolling while the backdrop is present.

This could be accomplished in CSS, perhaps by setting something like `<ion-app class="presenting">` and disabling scrolling when that class is present.

src/components/content/content.scss
```
.scroll-content {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: $z-index-scroll-content;
  display: block;

  overflow-x: hidden;
  overflow-y: scroll;
  -webkit-overflow-scrolling: touch;
  will-change: scroll-position;

  contain: size style layout;
}

.presenting .scroll-content {
  overflow-y: hidden;
}
```

I think this is the easiest solution to fix the problem, but there are a few ways architecturally to implement it, which is why I haven't offered a pull request.

**Comment by manucorporat** [comment]
@hotforfeature no, `overflow-y` can not be used, it causes flickering in UIWebView 100% of the times and in WK when there are a lot content: https://github.com/driftyco/ionic/issues/6857

**Comment by manucorporat** [comment]
what is stoping you to use WKWebView? We have implemented mechanism to disable scrolling that work properly in WK.

**Comment by hotforfeature** [comment]
What do you mean by overflow-y cannot be used? It cannot be set to hidden? Because it is being used currently in `<ion-content>`. The above `.scroll-content` is copied exactly from master.

I do not believe any of the problems outlined in #6857 would be an issue. This solution is changing `overflow-y: scroll;` to hidden after a view has been presented. The scroll content that is normally interacted with would no longer be interacted with while the view is presented. #6857 describes cases of flickering while interacting with the scroll content, or presenting an action sheet.

There is nothing stopping me from using WKWebView, it's just not the default. What is the method to disable scrolling in WK that works differently from UIWebView? This is all just CSS.

**Comment by manucorporat** [comment]
@hotforfeature we already do what you describe, actionsheet, alerts, etc. inject a class `disable-scroll` in order to disable the scroll. Previously we used the overflow:hidden trick. But it causes flickering.

**Comment by chanphillip** [comment]
I have the same issue on any actionsheet or alert. Any update now?

**Comment by hotforfeature** [comment]
I still need to try changing to WKWebView in the app that this problem was presenting itself in to confirm, but in a separate app that I'm working on that does use WKWebView the `disable-scroll` class is working. I was not able to scroll the page when an actionsheet was presented.

@chanphillip if you can I'd try installing and switching to WKWebView

**Comment by chanphillip** [comment]
@hotforfeature I read that there are other issues of using WKWebView which hasn't been solved yet (like CORS), so I don't want to waste time on it.

Is there no workaround without using WKWebView yet?

**Comment by hotforfeature** [comment]
@chanphillip the only other workaround would be to add some custom logic to change `.scroll-content` CSS from `overflow-y: scroll;` to `overflow-y: hidden;`, but as mentioned earlier it's been known to cause flickering. I didn't notice any flickering in my one particular use case, but your mileage may vary.

**Comment by chanphillip** [comment]
@hotforfeature Thanks! I'll try it out and get back here later.

**Comment by chiragebiztrait4** [comment]
+1, i am having same issue as described by @hotforfeature ,

But difference is, he is facing issue in webview, but i am facing in app.

In app, i have form with 10-12 fields, and one of them is presented in actionsheet, when actionsheet is open, background become scrollable.

Any update on this?
