### ISSUE TITLE
SCSS: Android platform title not respecting variable

### ISSUE THREAD

**Issue by myspivey** [ionic-team/ionic#9444]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Overriding $bar-title-font-size does nothing on Android devices.

**Expected behavior:**
Android title class respects $bar-title-font-size instead of hardcoding to 19px

**Steps to reproduce:**
1. Override $bar-title-font-size
2. Notice on Android is does not have an impact

**Related code:**

.platform-android {

  .nav-bar-has-subheader .bar {
    background-image: none;
  }

  .bar {

    .back-button .icon:before {
      font-size: 24px;
    }

    .title {
      font-size: 19px;
      line-height: $bar-height;
    }
  }

}

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by Manduro** [comment]
This is fixed in the latest version, you can use `$toolbar-md-title-font-size`.
