### ISSUE TITLE
Page header overlaps with the iOS status bar when it's pushed from a popover

### ISSUE THREAD

**Issue by maxt3r** [ionic-team/ionic#9450]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When pushing a new page from a PopoverController, that page header will overlap with the status bar on iOS. 

**Expected behavior:**
It's should have a proper padding and not overlap.

**Steps to reproduce:**

1. Push a child page with `this.navCtrl.push(ChildPage);` from a function inside of a popover controller.
2. ChildPage's header will overlap with the status bar. 

**Other information:**
This is an iOS-only issue.

**Ionic info:**
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

**Comment by onurburc** [comment]
Same here... Did you find any solution @maxt3r

**Comment by maxt3r** [comment]
@onurburc I'm pushing a new view from the parent controller, not the PopoverController itself. It works properly that way.
