### ISSUE TITLE
CSS on last-child p when used within an item

### ISSUE THREAD

**Issue by alexbainbridge** [ionic-team/ionic#9459]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[* ] **2.x**

**I'm submitting a ...**  (check one with "x")
[*] bug report
[ ] feature request

**Current behavior:**
On the layout code below, I am getting the p text not nicely vertically aligned

<img width="581" alt="categories_incorrect" src="https://cloud.githubusercontent.com/assets/1144763/20830261/a617ec38-b877-11e6-824a-51b63bf6f1b8.png">

You can see the text on the right is lower than the arrow, and lower than the corresponding text on the left

**Expected behavior:**
I expect it to look like this

<img width="491" alt="middle" src="https://cloud.githubusercontent.com/assets/1144763/20830276/bc12aad2-b877-11e6-99b9-7037da675333.png">

I can make it look like that with margin-bottom:8px on the p 

**Steps to reproduce:**

Create a list of buttons with a right aligned paragraph and should show as above

**Related code:**

```
  <ion-list>
    <button text-wrap ion-item *ngFor="let blah of blahs">
      <h2>{{field.name}}</h2>
      <p item-right padding-right>{{field.code}}</p>
    </button>
  </ion-list>
```

**Other information:**

Worked OK Beta 11
RC3 has introduced this (maybe introduced earlier, I jumped a few)
Something to do with p: last child setting bottom margin to 0 when was previously 8

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

Not the most major of problems (and perhaps I am using p unexpectedly here) - but might be a simple framework level fix....

**Comment by alexbainbridge** [comment]
Using a div (rather than a p) addresses the problem also, as no last child issue on that.......  Will leave you to decide if this is therefore needing resolution or not

**Comment by brandyscarney** [comment]
I pushed a fix for this for v4 that removes the margin top/bottom from elements positioned in an item. I would still recommend against using a `p` for this purpose though. :smile: 

Closing this issue, thank you!
