### ISSUE TITLE
ionic 2: scrollbar inside alerts 

### ISSUE THREAD

**Issue by mg1075** [ionic-team/ionic#9507]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Looking at the Alerts in v2 documentation, the content inside the alert always has a scrollbar, even though there is nothing to scroll. 

https://ionicframework.com/docs/v2/components/#alert

![image](https://cloud.githubusercontent.com/assets/2031435/20913291/019a8310-bb3c-11e6-903e-98ea0d7dfbd5.png)

**Expected behavior:**
Based on the examples, I would expect to see no scrollbar when there is not enough content to warrant scrolling.

**Comment by manucorporat** [comment]
Please, run `ionic info` and paste the results?

What browser are you using? Desktop or mobile? OS X, linux, windows?

**Comment by mg1075** [comment]
@manucorporat - this isn't me running an Ionic app; the screenshot is what I see when visiting the Ionic v2 documentation site on Windows 7, Chrome 54.

**Comment by mpaland** [comment]
This is due to a `overflow-y: scroll;` in the .alert-message class.
As far as I remember, this is a wanted behavior (momentum scrolling). See #6022 and the answer of @adamdbradley 
You may override `overflow-y` to `auto`.
