### ISSUE TITLE
 Pan gesture not working on first load

### ISSUE THREAD

**Issue by cryo243** [ionic-team/ionic#9513]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I migrated to Ionic 2 RC3 which has the panleft and panright gestures. When i put those  events on an element in my page, like so:
```<div (panleft)="move($event)" (panright)="move($event)"></div>``` 

it seems like they only get triggered after I refresh the browser not on the first app  load. 
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

 ordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.43
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.7.0
Xcode version: Not installed

```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you post a repo or [plunkr](http://plnkr.co/edit/GJte2b?p=preview) that we could use to reproduce this issue?

**Comment by cryo243** [comment]
Yes, here is the link to the repo:
https://github.com/cryo243/ionic-2-RC-3

**Comment by mzl1988** [comment]
import { Hammer } from "ionic-angular/gestures/hammer";

hammer: any = Hammer;

ionViewDidEnter() {

	// gesture
	let gesture = this.hammer(document.getElementById("xxx"), { direction: this.hammer.DIRECTION_ALL });
	gesture.get('pan').set({ direction: this.hammer.DIRECTION_ALL });
	gesture.on('panleft panright panup pandown', e => {
		this.panEvent(e);
	});;
}
