### ISSUE TITLE
Ionic 2: Virtual Scroll messed up when returning from camera plugin

### ISSUE THREAD

**Issue by daveshirman** [ionic-team/ionic#9514]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Virtual scroll contents are all bunched up after returning from the camera plugin.
Changing the orientation of the device forces the redraw, which solves the layout.

**Expected behavior:**
The layout shouldn't be affected from returning from the camera plugin

**Steps to reproduce:**

1. Load up a page with a virtual scroll list
2. Load up the camera
3. Dismiss the camera and go back to the list.
4. See that it's borked (the 2nd page titled 'Buildings' in the gif)

Please see attached gif:

![hammerheadm4b30xdaveshirman12062016141737](https://cloud.githubusercontent.com/assets/14280030/20928787/45a8d628-bbbf-11e6-84f3-c28415cd6a2c.gif)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Davids-Air:apphazard-app daveshirman$ ionic info

Your system information:

Cordova CLI: 6.2.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by toubacol** [comment]
Hello,
Any update about this ?

**Comment by daveshirman** [comment]
@jgw96 Seconded! I have several issues outstanding actually that I would to have an update on if possible please? Thanks.

**Comment by daveshirman** [comment]
@adamdbradley The team has been super silent with many of these outstanding issues and they need addressing. Any updates please?

**Comment by jgw96** [comment]
Hello @daveshirman , is this still reproducible with 3.0.1? There were some recent fixes in 2.3.0 that should help this issue.

**Comment by 8BallBomBom** [comment]
Getting the same issue with 3.0.1
Randomly after changing pages or going from something like the camera app.
All the virtualscroll ion-list ion-items bundle up overlayed on top of each other.
After checking the css for each ion-item i saw this `transform:` translate3d( 0, 0, 0 )`

**Comment by kitkimwong** [comment]
VirtualScroll Issue and Keyboard killed my app.

**Comment by arthurcaetanotb** [comment]
Getting the same issue with 3.2.0.
