### ISSUE TITLE
NavController last().name method not returning the right value on --prod

### ISSUE THREAD

**Issue by rodriguesgm** [ionic-team/ionic#9523]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
NavController returning wrong view name when doing .last().name
This issue only happens when running on prod mode.
I have the following code
```
if (this.nav.last().name !== 'Notifications') return;
```
and this works only when running _ionic serve_ or _build --dev_. 
I check the value returned by _this.nav.last().name_, using console.log(), and it printed 't', (yep, just the letter t)

**Expected behavior:**
When running build --prod, the method should return the same value as when running build --dev

**Steps to reproduce:**
In any view, just do a console.log(this.nav.last().name) running on ionic build --prod

**Comment by rodriguesgm** [comment]
any news on this?
thanks

**Comment by pdyraga** [comment]
`name` is marked with `@private` so I think it's not safe to use it from code other than Ionic internals. Instead, you can use `ViewController.component`.

**Comment by rodriguesgm** [comment]
@pdyraga thanks for the help. Even  ViewController.component.name has the same problem. I'm starting thinking this is not a bug. Anyway, I solve the problem doing _this.viewCtrl.component !== MyPage_

think this is a better solution

**Comment by pdyraga** [comment]
```
this.viewCtrl.component !== MyPage
```
this is what I was suggesting. I'm doing the same and it works like a charm.

> I'm starting thinking this is not a bug. 

Yes, I think so too. This is just a natural consequence of a minification.
