### ISSUE TITLE
Clickblock issues

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#9531]
https://github.com/driftyco/ionic/issues/9382
https://github.com/driftyco/ionic/issues/6481 (closed)
https://github.com/driftyco/ionic/issues/8416
https://github.com/driftyco/ionic/issues/7693
https://github.com/driftyco/ionic/issues/8784
https://github.com/driftyco/ionic/issues/9474

**Comment by manucorporat** [comment]
Added new e2e tests: https://github.com/driftyco/ionic/commit/d70d03588c48182131021c74bbb56f58f8b308a0

**Comment by jamboapp** [comment]
This makes the menu really annoying... can't click anything for 3 seconds after the menu is opened.
