### ISSUE TITLE
iOS: ion-select doesn't always focus 'next' input in form when onChange triggered

### ISSUE THREAD

**Issue by rtmruczek** [ionic-team/ionic#9535]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
in **iOS 10** (not sure if this happens in other versions of iOS, android seems fine): after changing the value of an `ion-select`,  the form input closest to the `ion-select` element in the DOM is not always focused if there are multiple subsequent `ion-input` elements. The behavior is intermittent, but oftentimes the input *after* the subsequent input is focused.

**Expected behavior:**
The `ion-select` should always focus the next immediate following input element in the DOM.  Either remove the auto-focus functionality from `ion-select` or ensure that this happens consistently.

**Steps to reproduce:**
It seems like it happens most often when you're focusing an input element and then immediately open the `ion-select` without blurring the input first. The most reliable way I've found to reproduce the bug is to:

1. Focus an `ion-input` below an `ion-select`
2. Tap the `ion-select` without blurring the `ion-input`.
3. Select a new value for the `ion-select`.
4. An incorrect `ion-input` is focused.

**Related code:**

```
<ion-header>
  <ion-navbar>
    <ion-title>Home</ion-title>
  </ion-navbar>
</ion-header>
<ion-content padding>
  <h2 id="title">Welcome!</h2>
  <p>
    This starter project comes with simple tabs-based layout for apps
    that are going to primarily use a Tabbed UI.
  </p>
  <p>
    Take a look at the <code>src/pages/</code> directory to add or change tabs,
    update any existing page or create new pages.
  </p>
      <form>

        <ion-list>
          <ion-item>
              <ion-label floating>input test a</ion-label>
              <ion-input>
              </ion-input>
            </ion-item>
            <ion-item>
              <ion-label floating>input test b</ion-label>
              <ion-input>
              </ion-input>
            </ion-item>
            <ion-item>
              <ion-label floating>Select</ion-label>
              <ion-select placeholder="default select">
                <ion-option>
                  test1
                </ion-option>
                <ion-option>
                  test2
                </ion-option>
              </ion-select>
            </ion-item>
            <ion-item>
              <ion-label floating>Select</ion-label>
              <ion-select placeholder="default select 2">
                <ion-option>
                  test1
                </ion-option>
                <ion-option>
                  test2
                </ion-option>
              </ion-select>
            </ion-item>
            <ion-item>
              <ion-label floating>input test</ion-label>
              <ion-input>
              </ion-input>
            </ion-item>
            
            <ion-item>
              <ion-label floating>input test 2</ion-label>
              <ion-input>
              </ion-input>
            </ion-item>
            <ion-item>
              <ion-label floating>input test 3</ion-label>
              <ion-input>
              </ion-input>
            </ion-item>
            <ion-item>
              <ion-label floating>input test 4</ion-label>
              <ion-input>
              </ion-input>
            </ion-item>
            <ion-item>
              <ion-label floating>input test 5</ion-label>
              <ion-input>
              </ion-input>
            </ion-item>
            <ion-item>
              <ion-label floating>input test 6</ion-label>
              <ion-input>
              </ion-input>
            </ion-item>
 
        </ion-list>
      </form>

</ion-content>

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.43
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v7.2.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by cyberbobjr** [comment]
Hi,
same problem here. I have a select with many options, when i select 1 option, the inputs are dynamically generated, and then a (random?) input is focused.

Tested with ios 10.1 emulator and real device (ios 10.1)

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3-201612062256
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by mhartington** [comment]
Hmm, seeing this as well, even in the nightly builds

**Comment by cookavich** [comment]
Experiencing the same issue here.

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: Mac OS X Sierra
Node Version: v7.0.0
Xcode version: Xcode 8.1 Build version 8B62

**Comment by ferozsho** [comment]
Still same error!!!
Even validation not highlighting the ion-select
----------------------------------------------------
ionic/cli-utils  : 1.19.0
ionic (Ionic CLI) : 3.19.0
global packages: cordova (Cordova CLI) : 8.0.0
local packages:
    ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2
System:
    Android SDK Tools : 26.1.1
    Node              : v8.9.3
    npm               : 5.6.0
    OS                : Windows 10
Environment Variables: ANDROID_HOME : D:\Android\sdk
Misc: backend : pro
