### ISSUE TITLE
bug(input): input controls in sliders are broken

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#9553]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
I have an `ion-slides` component which has some `ion-input` and `ion-textarea` controls in. On RC2 the way the form scrolled when a keyboard displayed on a device was bearable. In RC3 it is completely broken. In latest nightly it's better but still very bad. 

When a user touches an input, the input completely flies off the screen or is in the completely wrong position. When the keyboard is dismissed the screen is not returned to it's proper position. I have `ion-footer` elements in each `ion-slide` which show how the screen is not aligned after the keyboard is dismissed.

On iOS the footer and input are in the wrong positions, and sometimes the inputs do not even accept inputs from the keyboard.

Tested on Android 6.0.1 and iOS 10.1. No Crosswalk or WKWebView.

**Expected behavior:**
Scrolling to work correctly for form inputs on slides.

Similar to this issue. https://github.com/driftyco/ionic/issues/5744

See Android screenshots below. I will send a repro project to whichever team member requires it.

![screenshot_20161208-160805](https://cloud.githubusercontent.com/assets/2852839/21012939/ddb6367a-bd60-11e6-959b-de5f7f598797.png)
![screenshot_20161208-160809](https://cloud.githubusercontent.com/assets/2852839/21012944/e3328e78-bd60-11e6-99d2-80508f851c48.png)
![screenshot_20161208-160818](https://cloud.githubusercontent.com/assets/2852839/21012947/e75bcbf4-bd60-11e6-96ba-8de03418986d.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3-201612080433
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by dylanvdmerwe** [comment]
Removing the 300px padding helps in latest nightly. However on iPhone 5 things are horrible still.

![image](https://cloud.githubusercontent.com/assets/2852839/21116090/d7c006e2-c0bc-11e6-83a5-a5f9922286bc.png)

**Comment by jgw96** [comment]
Hey @dylanvdmerwe ! Would you mind trying this with `scrollAssist: false` in your config and seeing what the behavior is then please?

**Comment by jgw96** [comment]
So after some more testing I have tracked down this issue to being a css issue related to the [`height: 100%` on `ion-slides`](https://github.com/driftyco/ionic/blob/master/src/components/slides/slides.scss#L457). Not entirely sure why at the moment, but for some reason that bit of css breaks the world when a slide has an input.

**Comment by jgw96** [comment]
Update: i have a solution for this but its hacky and im not happy with it at the moment. Gonna try to clean it up.

**Comment by jgw96** [comment]
Working on this here https://github.com/driftyco/ionic/tree/inputSlides . Current strategy involves looking for the closest `ion-slides` from the container of the input. If there is an `ion-slides` then we simply focus the input and thats it, no fancy input scrolling. If there is no `ion-slides` then things just work normally.

**Comment by Schwoebel** [comment]
Hey @jgw96 how did the cleanup go?  

I noticed your inputSlides link you listed is gone now.

**Comment by nicksmithr** [comment]
Also having this issue with ionic@latest

**Comment by JoeriShoeby** [comment]
Link is dead ..

**Comment by ramzauchenna** [comment]
@dylanvdmerwe Your fix helped me so i went an extra step and added `overflow: scroll` on ths slide.

Next thing i want to do is listen on input focus and move to top.

**Comment by Qualinost1** [comment]
Hi,
any news or walkaround for this issue? The github link is not available anymore and I really would like to make this works.
An other weird thing happen to me, when I'm typing in one of this hidden input, the text is completely reversed:
Typed text : ISSUE
In the input : EUSSI
Can't know if it's a focus problem or so... it's hidden!

**Comment by dylanvdmerwe** [comment]
For iOS I recommend trying the [WkWebView](https://github.com/driftyco/cordova-plugin-wkwebview-engine) plugin. Should help quite a lot with scrolling issues. Also check out Ionic v3 which fixed a regression from 2.3.0.

**Comment by Qualinost1** [comment]
Thanks for the answer!
Sadly I'm working on android and tried to use the V3 CLI but things seems to be unchanged.
Any ideas for android ?

**Comment by kleeb** [comment]
Android and iOS still the same problem with newest wkwebview and Ionic 3.0.1

**Comment by jdm79** [comment]
still an issue with the input disappearing upon attempting to use keyboard. tested on my Android 5.1 MotoG too with same issue. 

ionic info: 
![screen shot 2017-05-04 at 18 00 10](https://cloud.githubusercontent.com/assets/11488167/25713026/991943fc-30f3-11e7-85df-401f3553b0c2.png)

**Comment by hg1** [comment]
Hey @jgw96 !

Do you still work on this issue. It still exists using the recent Ionic Release 3.2.0.
Some time ago you commented at this [pull request](https://github.com/driftyco/ionic/pull/9829) that you will want to do re-do it from scratch.

Thanks for replying soon.

**Comment by bogomips** [comment]
Same problem here.
When I put the focus on an input field, everything goes up and a big white space appears starting from the bottom of the page.
It seems that the ion-content keeps the right height but ion-slinde does not.
On focus, the following function is called:
Content.prototype.addScrollPadding = function (newPadding) {};
It adds a 300px of padding-bottom turning 
this <div class="scroll-content"> in  this <div class="scroll-content" style="padding-bottom:300px"> 
In that moment the black space appears.

**Comment by mtpultz** [comment]
This is still an issue in version 3.6.0.  @jgw96 are you able to share your hack as a temporary solution?

cli packages: (D:\Projects\progressa\demo\node_modules)

    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.2.1
    OS   : Windows 10
    npm  : 5.3.0

**Comment by jonstonis** [comment]
I am experiencing the same thing.  Latest of ionic seems to still have this problem.   I ended up having to go with a different UI design since I couldn't get this to work.

**Comment by MvRemmerden** [comment]
Also not working for me.

**Comment by chukwu** [comment]
For some reason the slide adds offsets to the input elements and all its children. Even my cursor position is wrong.
