### ISSUE TITLE
Refactor Swipe to Go back using app.navPop()

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#9566]
Right now each NavController (an app can have lots of them) instances a `SwipeBackGesture`. Right now it is hard to coordinate which SwipeBackGesture is the active one, for example swipe to go back is disabled inside modals because of this reason.

Fortunately we have a high level set of APIs (used by the android's hardware go back button) in app.ts:
```
navPop();
getActiveNav();
getRootNav();
```

We could use this APIs + an global swipe to go back gesture.

Advantages:

- Better performance (just one listener)
- More flexibility
- Less error prone
- Swipe to go back inside modals
- Swipeable tabs

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#244
