### ISSUE TITLE
Ionic 2 nightly-build - IOS 10 Keyboard (still buggy)

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#9594]
@adamdbradley @manucorporat I tried the nightly-build 2.0.0-rc.3-201612100458 to test the "IOS 10 Keyboard" fix https://github.com/driftyco/ionic/issues/8185

It seems that the situation really improved, thx a lot for your work. 

But in case of use of the keyboard in a modal, on dismissing the modal the keyboard still stay open. 

Could you plz try to reproduce the problem and fix it if needed?

With Xcode I simulated an iPhone 6S with OS 10.0

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3-201612100458
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v7.0.0
Xcode version: Xcode 8.0 Build version 8A218a

<img width="376" alt="capture d ecran 2016-12-12 a 10 29 01" src="https://cloud.githubusercontent.com/assets/16886711/21094309/b891d1d0-c056-11e6-8359-99d729634a8a.png">

**Comment by peterpeterparker** [comment]
I also opened following issue, which is also related to iOS Keyboard

https://github.com/driftyco/ionic/issues/9602

**Comment by peterpeterparker** [comment]
For the record, calling explicitly Keyboard.close() on each dismiss actions (each) of all modals where a keyboard is use is a way to fix the issue temporarily

**Comment by jgw96** [comment]
Hello @peterpeterparker ! Thanks for using Ionic! Could you try this with the latest nightly and see if that fixes the issue for you?

**Comment by peterpeterparker** [comment]
@jgw96 thx for your answer. with latest nightly, do you mean the current one or the on of tomorrow?

in case of the current one, unfortunately, I still face the same issue :(

**Comment by enraiser** [comment]
I tried latest nightly but I still see the issue

**Comment by peterpeterparker** [comment]
@enraiser in the meantime your could implement a call to Keyboard.close(); that made the trick till it will be solved

**Comment by enraiser** [comment]
where to put Keyboard.close(); ??
I am not even gettin gonBlue or onFocus event

     <ion-searchbar (focus)="onFocus($event)"  (click)="{}" (blur)="onBlur($event)" (ionInput)="getItems($event)"></ion-searchbar>

**Comment by peterpeterparker** [comment]
@enraiser depends of your business cas. in my case I call Keyboard.close() when user select something from the list. Maybe not the best place but at least I'm sure that at some point it will close itself.
