### ISSUE TITLE
bug(navbar): navbar not disappearing smoothly

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#9606]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
I have a screen with a bit of a larger `ion-header`. When popping back to the previous screen, the navbar has a delay before it goes away leading into a weird popping of the previous screen. 

On latest nightly on iOS simulator and device.

![navbar issue](https://cloud.githubusercontent.com/assets/2852839/21116965/7b673376-c0c0-11e6-935f-1f5b2c73593e.gif)

**Related code:**

```
<ion-header>

    <ion-navbar no-padding>
        <ion-title>Book Venue</ion-title>
    </ion-navbar>
    <div class='top-button-container'>
        <button ion-button full clear color="white" (click)="selectVenue()">
            {{venueTitle}}
        </button>
    </div>
    <ion-row class="schedule-nav-control" *ngIf="!loading && venueSchedule.length > 0">
        <ion-col width-10>
            <button *ngIf="canPrev" color="secondary" no-padding ion-button clear full (click)="prevDay()">
                <ion-icon name="arrow-back"></ion-icon>
            </button>
        </ion-col>
        <ion-col center>
            <p>{{scheduleSelectedDay.DateValue}}
                <p>
        </ion-col>
        <ion-col width-10>
            <button *ngIf="canNext" color="secondary" no-padding ion-button clear full (click)="nextDay()">
                <ion-icon name="arrow-forward"></ion-icon>
            </button>
        </ion-col>
    </ion-row>
</ion-header>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3-201612121605
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jgw96** [comment]
Hey @dylanvdmerwe would you try wrapping your `ion-row` in an `ion-toolbar` and see if that fixes the issue?

**Comment by dylanvdmerwe** [comment]
Yup, that fixes the issue. Can the documentation be enhanced or something as I've been using ionic 2 for a while and didn't know this?

**Comment by jgw96** [comment]
Hey @dylanvdmerwe, yep this can be added to the docs (:

**Comment by dylanvdmerwe** [comment]
Has this been documented? Can we close this issue yet?

**Comment by Flixt** [comment]
At least the ion-footer doc has a ion-toolbar in the code example:

[https://ionicframework.com/docs/v2/api/components/toolbar/Footer/](https://ionicframework.com/docs/v2/api/components/toolbar/Footer/)

```html
<ion-content></ion-content>

<ion-footer>
  <ion-toolbar>
    <ion-title>Footer</ion-title>
  </ion-toolbar>
</ion-footer>
```

**Comment by brandyscarney** [comment]
This issue was moved to ionic-team/ionic-site#1146
