### ISSUE TITLE
Mode: "wp" not working

### ISSUE THREAD

**Issue by loursbourg** [ionic-team/ionic#9616]
When i run "**ionic run windows**", ionic uses the material design style though i'm not deploying to android.
**Ionic version:**  (check one with "x")
[  ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[  ] feature request
[  ] support request

**Current behavior:**
Ionic puts **class="md"** instead of **class="wp"** 
**Expected behavior:**
Ionic puts **class="wp"** instead of **class="md"** 

**Ionic info:**:

```
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.36
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```
I added  mode: "wp" to the IonicModule (in the app.module.ts)  but it didn't work.
I added the "wp" class manually to the `<ion-app>` but it didn't work.
I added  mode="wp" attribute to the `<ion-app>` but it didn't work.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind updating to the latest release (rc.3) and then trying this again please? I cant seem to reproduce this issue with rc3.

**Comment by loursbourg** [comment]
@jgw96 Updated to the rc3 but that didn't work too.
I'll try to build in another PC and see if the issue persists.
I have this in my **app.module.ts** imports (seen this in the documentation):
`IonicModule.forRoot(MyApp, {
    mode: 'wp',
    }
)`
Am i doing it wrong?

**Comment by joshstrange** [comment]
I don't normally use windows but I just noticed this as well. I am using RC4 and still seeing the issue (I've also tried latest). I do see a JS runtime error when I debug the app "Unable to get property '_platform' of undefined or null reference"

**Comment by kensodemann** [comment]
Hello all! This will no longer be an issue with the next version of Ionic as wp will no longer be an option. Thus I am going to close this.

Thanks for using Ionic!
