### ISSUE TITLE
bug: scrollbar showing without enough content to scroll

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic#9637]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
A scrollbar appears when opening an alert or closing a sliding item from a page that doesn't have enough items to scroll.

**Expected behavior:**
No scrollbar to appear.

**Steps to reproduce:**
Clone the conference app: https://github.com/driftyco/ionic-conference-app

Run on an Android device:

1. Go to schedule and slide an item, favorite the item
2. Go to the Favorites tab
3. Slide open the item, click remove
4. An alert will appear and the scrollbar will show on the right
5. Click cancel, then slide the item open again
6. Click on the item body so the item will close itself, see the scrollbar on the right

**Other information:**
Nexus 5 running 6.0.1. I can't reproduce it in Chrome.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Framework Version: 2.0.0-rc.3-201612122136
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46-201612121701
```

I believe this is related to https://github.com/driftyco/ionic-conference-app/issues/198 and https://github.com/driftyco/ionic/issues/6416

<img src="https://cloud.githubusercontent.com/assets/6577830/21190091/b81da9ec-c1ee-11e6-848c-55612cc7e909.png" width="300">

<img src="https://cloud.githubusercontent.com/assets/6577830/21190090/b81a71be-c1ee-11e6-874f-46e91c4e24f1.png" width="300">

**Comment by jgw96** [comment]
On a `no-lines` list I cant seem to reproduce this.

**Comment by brandyscarney** [comment]
@jgw96 including the conference app?

**Comment by sumodevelopment** [comment]
This might be a bit late.. but i just checked out the sidemenu template and the same happens when you open the menu. It even shows on the actual menu.
