### ISSUE TITLE
Native keyboard blocks ion-input inside ion-item-sliding 

### ISSUE THREAD

**Issue by nilswieber** [ionic-team/ionic#9642]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If an ion-input is added inside an ion-item-sliding the content doesn't scroll correctly, if the input that is focused by the user, is in the area where native keyboard will popup (e.g. at the bottom of the screen) on Android or iOS.

So the ion-input remains overlapped by the keyboard.
**Expected behavior:**
The Content should scroll up, if the input that the user selected lays in the area, that the native keyboard will block on Android or iOS.

**Steps to reproduce:**
Here is a repository that demonstrates this issue [Github Repository](https://github.com/nilswieber/ionic-item-sliding-input-issue/tree/master)
[Plunker](http://plnkr.co/edit/w8AOIvzvXiUjNYt6o8YB?p=preview) NOTE: Issue is only reproducible with a software keyboard! So run the Plunker in Fullscreen on a mobile device.
The issue can be reproduced with an Android Emulator with the current Ionic Nightly or 2.0.0-rc.3

**Related code:**

```
<ion-content>
    <ion-list>
          <ion-item-sliding *ngFor="let i of items">
            <ion-item>
                  <ion-label>{{i}}</ion-label>
                  <ion-input></ion-input>
            </ion-item>
            <ion-item-options side="right">
              <button ion-button color="primary">
                <ion-icon name="trash"></ion-icon>
                Delete
              </button>
            </ion-item-options>
          </ion-item-sliding>
    </ion-list>
</ion-content>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3-201612122136
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by masimplo** [comment]
Maybe you should join the discussion on #5432

**Comment by nilswieber** [comment]
I just want to note that this issue is still present in RC4
