### ISSUE TITLE
RC.4 clear FAB button doesn't work

### ISSUE THREAD

**Issue by aces-tm** [ionic-team/ionic#9671]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Following code should give a clear button, but it actually clear class doesn't do anything.
     <button ion-fab mini clear><ion-icon name="more"></ion-icon></button>

 I have a workaround by putting this code in css. 

.fab[mini]{
        background-color: transparent;
        margin: 0px;
        box-shadow: none;
        color: #387ef5;
    }

**Expected behavior:**

I believe that in RC.2 clear function worked.

**Related code:**

```
     <button ion-fab mini clear><ion-icon name="more"></ion-icon></button>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: OS X El Capitan
Node Version: v6.9.2
Xcode version: Xcode 8.1 Build version 8B62```

**Comment by vkniazeu** [comment]
I have the same need, but FWIW the `clear` option is not documented for FABs:
http://ionicframework.com/docs//api/components/fab/FabButton/

**Comment by payen83** [comment]
You can try modify the ion-fab css:

```
ion-fab button[ion-fab] {
   background-color: transparent;
}
```
