### ISSUE TITLE
ion-slides with looping turned on: ion-slide loses click event on wrap

### ISSUE THREAD

**Issue by horo42** [ionic-team/ionic#9690]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Creating an ion-slides component with 3 ion-slide components inside, and setting the loop option to true, then navigating from the first slide to the last (by looping around), the click event stops working until I navigate to another slide by NOT looping around.

**Expected behavior:**
The onClick() method should get called after the ion-slides component wraps around and I click on the slide.

**Steps to reproduce:**
http://plnkr.co/edit/8PU8E7jjcxEAUgScegtl?p=preview

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Xcode 8.2 Build version 8C30a

**Comment by mhartington** [comment]
Can confirm. Will revisit post 2.0 final.
