### ISSUE TITLE
While typing or deleting, textbox automatically gets focus out and stops typing. Have to click on the textbox again to focus in.

### ISSUE THREAD

**Issue by KavishPeiris1** [ionic-team/ionic#9697]
**Ionic version:**  (check one with "x")
[ x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

While typing it automatically stops typing on the textbox. Have to click on it focus in again.

**Expected behavior:**

Smoothly type and delete text on the textbox

**Comment by vazad28** [comment]
I am seeing this behaviour too

**Comment by KavishPeiris1** [comment]
Can someone help us here

**Comment by jgw96** [comment]
Hello @KavishPeiris1 , thanks for opening an issue with us! Would you mind posting some sample code please?

**Comment by FdezRomero** [comment]
Hi @KavishPeiris1 and @vazad28! Is this still an issue? (I'm volunteering to triage issues). Thanks!
