### ISSUE TITLE
Ionic 2 - RC4 - Popover viewCtrl dismiss delay

### ISSUE THREAD

**Issue by tonyawad88** [ionic-team/ionic#9705]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
The current popover behaviour seems to have a delay from when I click a button inside the popover to when the dismiss event fires back / notifies the parent controller. The delay is about 1-2seconds, which is noticeable.

***Note: I haven't used Popover in previous Ionic RCs so I am not sure if this is new or it existing behaviour***

**Expected behavior:**
Reduce delay from when the popover dismissal occurs to when the parent controller receives the event. 

**Steps to reproduce:**
I tried creating a plunker but it is using RC2. There seems to be a bug in rc2 for this. But I added my code to the plunker. It's pretty basic. 

http://plnkr.co/edit/NOwo7GJBVgZl6qe0CfHf?p=info

```
import { Component } from '@angular/core';
import { NavParams, ViewController } from 'ionic-angular';

import { UIShared} from '../../providers/ui-shared';

@Component({
  template: `
  <section class="popover-page-1">
    <button clear ion-button full color="primary" icon-left (click)="close('language');">
      <i class="fa fa-language"></i>
      Lang: EN
    </button>
    <button clear ion-button full color="green" icon-left (click)="close('settings');">
      <ion-icon name="settings"></ion-icon>
      Settings
    </button>
    <button clear ion-button full color="red" icon-left (click)="close('signout');">
      <ion-icon name="power"></ion-icon>
      Sign Out
    </button>
  </section>
  `
})
export class Popover {
    constructor(private navParams: NavParams, public viewCtrl: ViewController,
                public uiShared:UIShared) {}
    ngOnInit() {}

    close(action:string) {
        if(action == 'signout'){
            let loading = this.uiShared.GenerateLoading("Signing Out...");
            loading.present().then(()=>{
                this.viewCtrl.dismiss(action).then(()=>{loading.dismiss();});
            });
            return;
        }
        this.viewCtrl.dismiss(action); //else just return action
        
    }
}
```

**Other information:**
N/A

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by benydc** [comment]
Hi @jgw96 ,

Do you still have this issue? I wonder if I upgrade the angular to RC5 or RC6 and see if it works... I need help with this issue as well.

**Comment by UrbanCondor** [comment]
This is still occurring for me

<img width="367" alt="screen shot 2017-06-01 at 6 47 48 pm" src="https://cloud.githubusercontent.com/assets/18430094/26676585/de645b82-46fa-11e7-8c66-18aa6d90235a.png">

**Comment by danielsogl** [comment]
@UrbanCondor can you update to ionic-angular 3.3 and check it again?

**Comment by UrbanCondor** [comment]
@danielsogl  - same result unfortunately

<img width="355" alt="screen shot 2017-06-01 at 9 54 20 pm" src="https://cloud.githubusercontent.com/assets/18430094/26682987/e8d7beb4-4714-11e7-8e75-77c05f5e7e54.png">

There is a noticeable delay experienced in the dismiss event notifying the parent element. I've created a very basic Ionic project with the following files:

**home.html**
```
<ion-header>
  <ion-navbar>
    <ion-title>
      Popover Test
    </ion-title>
    <ion-buttons end>
      <button ion-button icon-only (click)="showPopover($event)">
        <ion-icon name="arrow-dropdown-circle"></ion-icon>
      </button>
    </ion-buttons>
  </ion-navbar>
</ion-header>

<ion-content>
</ion-content>
```

**home.ts**
```
import { Component } from '@angular/core';
import { NavController, PopoverController } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, public popoverCtrl: PopoverController) {
  }

  showPopover(myEvent){
    let popover = this.popoverCtrl.create(
      'PopoverPage', {}, {
        cssClass: 'popover-edit-delete'
      });
    popover.onDidDismiss(data => {
      console.log('Item ' + data + ' clicked!')
    });
    popover.present({
      ev: myEvent
    });
  }
}
```

**popover.html**
```
<ion-list no-lines>
  <ion-item (click)="clickItem(1)">Item 1</ion-item>
  <ion-item (click)="clickItem(2)">Item 2</ion-item>
</ion-list>
```

**popover.ts**
```
import { Component } from '@angular/core';
import { IonicPage, ViewController } from 'ionic-angular';

@IonicPage()
@Component({
  selector: 'page-popover',
  templateUrl: 'popover.html',
})
export class PopoverPage {

  constructor(public viewCtrl: ViewController) {}

  clickItem(itemNbr){
    this.viewCtrl.dismiss(itemNbr);
  }
}
```

**Comment by nitinsh99** [comment]
I am also seeing this exact issue. Please fix this. Thanks!

**Comment by ValentinMerlet** [comment]
Hi same issue here, delay > 1 sec when dismiss call on ViewController


<img width="455" alt="ionic-info" src="https://user-images.githubusercontent.com/2642302/28724023-00137b9c-73b9-11e7-8313-991411fed5bc.png">

**Comment by benydc** [comment]
I think the issue is here:
https://github.com/ionic-team/ionic/blob/2273fb5d47eb64375f1608370d32b330cdc30bd9/src/components/popover/popover-transitions.ts

there is 500ms delay for popoverout

**Comment by ValentinMerlet** [comment]
Oh nice discovery @benydc, adding an animation should resolve the problem then ?

**Comment by benydc** [comment]
I'm testing now with 100ms and see how it goes.

**Comment by benydc** [comment]
Yess!!! it's a lot quicker now. 
Change inside this file:
node_modules/ionic-angular/components/popover/popover-transition.js
change under PopoverPopOut the duration to 100ms. I think we need to provide an option here that we can specify when creating the popover component. Also, this is not the correct way to make changes, will need to be build correctly using the contribution guide.

**Comment by ValentinMerlet** [comment]
It didn't do the trick for me, still having a delay after changing the duration to 100ms :/

**Comment by benydc** [comment]
are you using android/MD popover? change for that as well.

**Comment by ValentinMerlet** [comment]
Yes, I changed all the duration from 500ms to 100ms in popover-transition.js

**Comment by jonathanwoahn** [comment]
Any updates for this? Has the option been added?

**Comment by warri93** [comment]
No more updates? Or does anyone know a good way to 'overwrite' the file and change the delay myself?

**Comment by iwantwin** [comment]
This is still an issue! Needs to be fixed, we are struggling with this for every project we do!

**Comment by andrewvmail** [comment]
@benydc thanks for sharing!
@warri93 
```
sed -i 's/500/100/g' node_modules/ionic-angular/components/popover/popover-transitions.js
```
run manually or put that in a hook somewhere
