### ISSUE TITLE
Platform - Pixel C not detected as "tablet"

### ISSUE THREAD

**Issue by TomDemulierChevret** [ionic-team/ionic#9724]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I check the platform type of my tablet 'Pixel C' (eitheir with Platform.platforms and Platform.is(platformName)), the type "tablet" isn't returned.

**Expected behavior:**
Platform should detect the device type as "tablet" when it's the case.

**Other information:**
It might be linked with the same issue on iPad Pro (#9317).
In general, tablets don't seem to be well detected.

In my case this information is really important, since I force the screen orientation according to the device type (portrait for mobile, landscape for tablet), which is pretty common for mobile application.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by TomDemulierChevret** [comment]
This issue seem's to be related to the test made in [https://github.com/driftyco/ionic/blob/master/src/platform/platform-registry.ts](platform-registry.ts) :
`tablet: {
    isMatch(p: Platform) {
      let smallest = Math.min(p.width(), p.height());
      let largest = Math.max(p.width(), p.height());
      return (smallest > 460 && smallest < 820) &&
        (largest > 780 && largest < 1400);
    }
  },`

On my Pixel C, "platform.width()" returns 820, which doesn't pass the test since it a strict inequality.

Actually, I'm not even sur there should be an upper bound for the tablet since some model may returns bigger values (like 1980 x 1080).

**Comment by jgw96** [comment]
Thanks for posting this issue, we will look into this!
