### ISSUE TITLE
Fires click when stop scroll with tap/click

### ISSUE THREAD

**Issue by chrisyuyangshen** [ionic-team/ionic#9755]
The issue is related to https://github.com/driftyco/ionic/issues/1438. I have a tabbed app, and in each tab I have a scroll list. The first tab is fine, but the second is not. See demo http://codepen.io/chrisyuyangshen/pen/BQEzNj. open it with your mobile phone and you can replicate this issue. Btw I'm using ionic 2.0.0

**Comment by chrisguerrero** [comment]
+1

I'm experiencing the same issue with 2.0.0-rc.4:

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.6.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by cernym43** [comment]
+1

Ionic 2.0.0
