### ISSUE TITLE
Cannot interact with Modal if called from a Popover on iOS - V2 RC4

### ISSUE THREAD

**Issue by joshuaohana** [ionic-team/ionic#9779]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**  RC4

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have one modal which is called from various places to edit some data. It works all of the time unless it's presented from within a popover. From the popover 1) it takes two clicks to open the modal and 2) once the modal is open, I cannot interact with any elements on that page. Scrolling still works, and I can click back in the header, but I cannot touch or click on anything else.

This issue is specific to being ran on a device, iPhone 6 in this case, it works normally in all scenarios when running on desktop browser.

**Expected behavior:**
I would expect a Modal, when presented from a Popover, to behave normally just like it is when presented from any other page.

**Steps to reproduce:**
Unfortunately I cannot reproduce since the issue does not present itself when running in a browser, only on device. However, it is consistently misbehaving whenever ran on device. To reproduce simply;
1) From any page present a Popover
2) With that Popover have a link which presents a Modal
3) Throw a button on that Modal
4) Try to click that button, on that Modal, when presented from a popover

**Related code:**
Nothing interesting or out of the ordinary in my code but below lists the popover and modal present options. I have a selector to display the filter icon, on-click it displays the popover, then an on-click element inside the popover presents the modal.

Present Popover
```
    displayFilters(e) {
      this.popoverCtrl.create(FiltersPopover, {filters: this.filters, applyFilters: this.applyFilters, resetFilters: this.resetFilters}).present({
        ev: e
      });
    }
```

Present Modal
```
  selectType() {
    let typesModal = this.modalCtrl.create(TypesModal, {type:this.filters.selectedType, isSelector:true});
    typesModal.present();
    typesModal.onDidDismiss(data => {
      if(data) this.filters.selectedType = data;
    });
  }
```

And the modal itself is pretty brainless, just a little ngFor with (click) events on the elements.

**Other information:**
To repeat; this issue does not occur when testing on desktop browser. It only happens on the actual device (same exact code being ran of course).
I have tried to track down the problem since I'd guess it's z-index related, to no avail - tried to add z-index:99999 !important to modal in question. Also tried to trace around what was going on with backdrop or whatever.

Based on my preliminary investigations it's looking like the popover-overlay is capturing all clicks from the modal instead of allowing the click events to register on the modal.

I'd be content enough to just use nav.push(view) instead of displaying the modal; however, as you can see in the code snippet above I am passing data back via dismiss and catching on onDidDismiss, which is required, and I can't see an easy path to restructure to allow the desired functionality.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.9
OS: macOS Sierra
Node Version: v6.2.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by joshuaohana** [comment]
Update- issue is still exactly as I described. I was able to still get desired behavior with the mentioned workaround, pushing view instead of displaying as modal and catching data with eventEmitter. Code below incase anyone else needs it. With this setup is works fine sometimes as a modal and sometimes as a pushed view, I just pass in a param for isFromViewPush and route accordingly. Still thing it's a bug that should be fixed though...

Present the Modal (or now, push the View)
```
    // setup emitter
    var typeEmitter = new EventEmitter<Type>();
    // subscribe
    typeEmitter.subscribe(data => {
      if(data) this.filters.selectedType = data;
    })
    // push the view
    this.navCtrl.push(TypesModal, {type:this.filters.selectedType, isSelector:true, isFromViewPush:true, eventEmitter: typeEmitter});
```
Handle the selection and pass back data
```
    if(this.isFromViewPush) {
      this.typeEmitter.emit(type);
      this.navCtrl.pop();
    }
    else this.viewCtrl.dismiss(type);
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Did this work in RC3? The issue is most likely that the modal is being presented from the root nav of the popover instead of the root navcontroller.

**Comment by joshuaohana** [comment]
@jgw96 Hey I'm not sure about RC3, was building in browser on RC0 and jumped to RC4 when I started testing on device. Makes sense about the navcontroller, maybe could have navcontroller get pulled in from the presenter's scope instead of using root nav. P.S. even with the bugs here and there y'all have really made an amazing framework!

**Comment by brandyscarney** [comment]
I confirmed this issue using `2.0.0` and launching the `ScheduleFilterPage` from the `AboutPopover`. This is the rule preventing clicks:

<img width="271" alt="screen shot 2017-01-26 at 1 25 21 pm" src="https://cloud.githubusercontent.com/assets/6577830/22344668/02cba248-e3cb-11e6-95a5-fa4864ef0e3c.png">

**Comment by Arnaud49** [comment]
hi, have you got some news on this issue ? i'm using some popover instead of a modal to bypass this problem but I really want to use the modal view.

Thanx !

**Comment by m5rk** [comment]
Any known workarounds to this? Or other updates?

**Comment by Arnaud49** [comment]
hi there again, no news ?

**Comment by sim0629** [comment]
I added the below to `app.scss`.
```
.disable-scroll .ion-page {
    pointer-events: auto;
}
```
It works and no side-effects are found yet.
Does anyone know any possible side-effects for this workaround?

**Comment by aboosoyeed** [comment]
@sim0629 this worked for me . Any news on the side effects ?

**Comment by captainjim1** [comment]
This has been an issue for me as well. @sim0629 's fix is working for me without any ill-effects so far. 

The only change I made was to specify that the css change only is in effect on ios devices

`
.ios.disable-scroll .ion-page {
    pointer-events: auto;
}`

**Comment by shreeshbhat** [comment]
I m facing this issue with Ionic 3 as well.

Ionic info :
ionic/cli-utils : 1.19.0
ionic (Ionic CLI) : 3.19.0
Node : v6.11.5
npm : 3.10.10
OS : macOS Sierra

**Comment by andhadj** [comment]
> I added the css below to my `app.scss`.
> 
> ```
> .disable-scroll .ion-page {
>     pointer-events: auto;
> }
> ```
> It works and no side-effects are found yet.
> Does anyone know any possible side-effects for this workaround?

When the Popover is presented, the background Page becomes scrollable with this change.
