### ISSUE TITLE
Dynamically adjust the font size in the datetime component

### ISSUE THREAD

**Issue by infinnie** [ionic-team/ionic#9879]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

![screenshot_2017-01-05-10-14-11](https://cloud.githubusercontent.com/assets/8168391/21666936/1ca094fe-d330-11e6-8a06-bd5af3ebb17f.png)
Text in the `ion-datetime` component has a font size sometimes too large for the screen to contain without overflow.

**Expected behavior:**

I suggest the font size be adjusted dynamically depending on the screen size and the text length.

**Comment by pawelfrydrych** [comment]
div.picker-col:nth-child(4) {
  min-width: 80px !important;
} 
It helped me, but it shouldn't be a solution for this issue.

**Comment by bigbang4u2** [comment]
I am having the same issue on android phone

**Comment by bigbang4u2** [comment]
I figured out the solution by adding following to variables.scss for both ios and android 
$picker-md-column-padding:                    0 0px !default;
$picker-ios-column-padding:                    0 0px !default;
