### ISSUE TITLE
Side menu layout does not work correctly in landscape mode for devices with width <= 340px

### ISSUE THREAD

**Issue by aszmyd** [ionic-team/ionic#9885]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Side menu layout does not work properly for smaller screens (tested on iPhone 5s but it looks like its related to all < `340px` width screens). 
The issue is that after rotating the device into landscape mode, width of side menu changes to default `304px` but content navigation section translation remains `264px` which leads to content obscuring side menu.

**Expected behavior:**
It should behave consistently - the content translationX should albo be changed when side menu width has changed.

**Steps to reproduce:**
1. Run new app with sidemenu layout: `ionic start mySideMenu sidemenu --v2`
2. Add ios platform, build and run it on a device that viewport width is <= `340px`. I.e. iPhone 5
3. Open side menu
4. Rotate phone/simulator to landscape mode

**Screenshots:**
Portrait:
![image](https://cloud.githubusercontent.com/assets/3050805/21676990/78cfe6b4-d338-11e6-954d-66965e62db29.png)
Landscape:
![image](https://cloud.githubusercontent.com/assets/3050805/21677002/7f3f07be-d338-11e6-8327-d8433b7253a1.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We will take a look at this issue.

**Comment by jgw96** [comment]
Update: i can reproduce this with this e2e http://localhost:8000/dist/e2e/menu/basic/ on an iphone 5 running the latest iOS 10.
