### ISSUE TITLE
RC.4 Nightly Issue: Loading dismissOnPageChange = true ignored while dismissing a modal

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#9907]
**Ionic version:** 
2.0.0-rc.4-201701062325

**I'm submitting a ...** 
bug (minor there is a workaround)

**Current behavior:**
If I want to present a Loading component with the option "dismissOnPageChange: true" with the goals of doing some stuffs and then closing the modal, the Loading gonna hang after the modal close.

**Expected behavior:**
A Loading component with "dismissOnPageChange: true" should also be closed when a modal is dismissed.

**Steps to reproduce:**
In a modal, use a loading before the dismissing of the modal. Call the modal, close it, the Loading component is still open.

**Related code:**

        let loading: Loading = this.loadingController.create({
            dismissOnPageChange: true
        });

        loading.present().then(() => {
             // Do some stuffs

              this.viewController.dismiss().then(() => {
                    // => Modal is now closed but Loading hang
             });
         });
      

**Other information:**

There is a workaround, calling explicitly the dismissing of the loading. This could be achieved like following:

      let loading: Loading = this.loadingController.create({
            dismissOnPageChange: true
        });

        loading.present().then(() => {
             // Do some stuffs

              this.viewController.dismiss().then(() => {
                    // Call loading dismissing
                    if (loading != null) {
                        loading.dismissAll();
                    }
             });
         });

**Ionic info:**

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4-201701062325
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jsayol** [comment]
Using RC.4 an exception gets thrown when dismissing the modal, while with the 2.0.0-rc.4-201701062325 nightly nothing happens (no exception either). This is almost definitely due to the changes introduced with #9747.

To be honest, unless there's something I'm missing I'd file this one under "expected behavior".

Here's a simple repo to reproduce this, anyway: https://github.com/jsayol/ionic-issue-9907

**Comment by jsayol** [comment]
@peterpeterparker `viewController.dismiss()` doesn't take a callback, by the way. Just some data that will be passed to the `onDidDismiss()` method.

The proper way to do what you want is like this:

```ts
dismiss() {
  let loading: Loading = this.loadingController.create();

  loading.present().then(() => {
    this.viewController.dismiss().then(() => loading.dismissAll());
  });
}
```

**Comment by peterpeterparker** [comment]
@jsayol thx for pointing that out. Of course, I had a copy/paste mistake in my code example (which I just modified).

**Comment by jgw96** [comment]
Hello @peterpeterparker , thanks for opening an issue with us! We will take a look at this issue.
