### ISSUE TITLE
ion-range not updating view when ngModel values changed programatically

### ISSUE THREAD

**Issue by jsanchezgarcia** [ionic-team/ionic#9927]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Given a simple ion-range element as follows, when priceRange values are changed programmatically (for example, after clicking a button, we reset the values to defaults) the knobs do not reposition correctly.
<ion-range dualKnobs="true" min=0 max=100 [(ngModel)]="priceRange"></ion-range>

**Related code:**
See this plunker: http://plnkr.co/edit/06VOB1?p=preview

**Other information:**
The values in the model are changing and updating correctly (after clicking reset, the labels update as expected, but the knobs don't position correctly).

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.48
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by psysniffer** [comment]
I couldn't find the relevant code that you had above in the plunker, but I had a similar issue and you had to set the whole model instead of the upper and lower individually.

i.e.
instead of:
  reset() {
    this.priceRange.lower = this.defaultLower;
    this.priceRange.upper = this.defaultUpper;
  }

try:
  reset() {
    this.priceRange = {
      lower = this.defaultLower,
      upper = this.defaultUpper
  }

**Comment by jsanchezgarcia** [comment]
thanks @psysniffer. You're correct. It seems to be some kind of problem using ChangeDetectionStrategy.OnPush. In my actual use case, priceRange is an @input object. When I click reset, I create a new instance in the parent component (immutable), so change detection should work fine with OnPush strategy. Some hidden bug inside the ion-range component?

**Comment by jsayol** [comment]
Hey @jsanchezgarcia, that's actually how OnPush change detection works. It only triggers when the bound value changes. Changing a property of an object doesn't change it's value (which is just a reference to the object), so Angular doesn't see any changes.

**Comment by jsanchezgarcia** [comment]
@jsayol you're correct regarding the way OnPush detection works, but ion-range is not picking up the change even after creating a new instance. See this plunker for further clarification: http://plnkr.co/edit/06VOB1?p=preview

**Comment by biesbjerg** [comment]
@jsanchezgarcia Try using nightly, it seems to be fixed there for me.
