### ISSUE TITLE
"Uncaught TypeError: ele.hasAttribute is not a function" in FAB-list button on Android

### ISSUE THREAD

**Issue by hugomosh** [ionic-team/ionic#9942]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ X] **2.1.14**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When i click in a FAB list button i get `"Uncaught TypeError: ele.hasAttribute is not a function"` in the adb console.
In ionic serve works fine but not in native android

**Expected behavior:**
I just want a simple click

**Related code:**

```html
<ion-content>
    <ion-fab top right edge #fab>
        <button ion-fab mini (click)="searchInVisibleArea(null)">
            <ion-icon name="add"></ion-icon>
        </button>
        <ion-fab-list side="bottom">
            <button ion-fab (click)="searchInVisibleArea(fab)">
                <ion-icon name="search"></ion-icon>
            </button>
        </ion-fab-list>
    </ion-fab>
    <div id="native-map">
    </div>
</ion-content>
```

I think it has to do with something of the element selection. Maybe a case sensitive thing in the JS running in android

**Comment by brandyscarney** [comment]
Could you run `ionic info` from inside of your project folder and paste the output please? Thanks!

**Comment by hugomosh** [comment]
```
Your system information:

Cordova CLI: 6.2.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 
OS: OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by hugomosh** [comment]
6.0.1
And HTC Sense Version: 7.0_g

**Comment by jgw96** [comment]
Hey @hugomosh unfortunately i cannot seem to reproduce your issue with the latest nightly on either a Nexus 7 running Android 6.0.1 or a Nexus 6 running Android 7.1.1. Also used your exact markup you posted above in my tests. Do you have a repo that i can use to reproduce this issue?

**Comment by hugomosh** [comment]
Oh, I've just realize that is the (native) map absorbing the clicks. The FAB lead button inside the map div works fine but the expanded list of FABs are like in an hidden or lower layer*.

**Do you know any related problem?** 

I see the buttons but I am not able to click them.

And the error `"Uncaught TypeError: ele.hasAttribute is not a function"`seems like a common response when the map is clicked : / that is why i confused them.

**Comment by brandyscarney** [comment]
It seems like this may be a duplicate of https://github.com/driftyco/ionic/issues/9726

**Comment by jgw96** [comment]
Hey @hugomosh , thanks for posting that info. Since this seems to be the same issue that was already reported in #9726 I am going to close this issue for now. You can track the progress on this over on that issue. Thanks for using Ionic!

**Comment by hugomosh** [comment]
Not sure if related. What I am not able to do is click in the Fab buttons: 
the blue works fine but the gray ones are like in another layer . I am not sure if is the flex or diplay. I was not able to figure it out with the safari debugger. 

![captura de pantalla 2017-01-10 a las 4 08 37 p m](https://cloud.githubusercontent.com/assets/898426/21826943/20205a24-d74f-11e6-8169-5fba1060a88e.png)

**Comment by hugomosh** [comment]
Yes. [901#issuecomment](https://github.com/driftyco/ionic-native/issues/901#issuecomment-268740267) solved the error but I am still unable to click the gray FAB buttons : (

**Comment by jgw96** [comment]
Hello @hugomosh , so this is only happening with a google map correct? When you are using fab buttons without the google map it works correctly?

**Comment by heddanas** [comment]
Hello everyone,

It's my first contribution to the Ionic Community (also to the Github Comm.)

I am getting this error to.
Like you have said @jgw96, the error is related when using FAB buttons with Native Google Map. But when using Google Map Javascript Library, there is no error.

@hugomosh You can read this article from Josh Morony, where he faced the same problem (I think), and the solution that he proposed is to wrap the FAB button inside the map div element :
https://www.joshmorony.com/google-maps-in-ionic-2-native-or-web/ 

![Error_FAB_Google_Map](https://cloud.githubusercontent.com/assets/25275829/23103427/11584974-f6b3-11e6-9a7b-68f4de169930.jpg)

------
[Anas HEDDOUN](http://heddoun.com)
[Web Developer, UI/UX Designer & SEO Consultant](http://heddoun.com)

**Comment by heddanas** [comment]
Consider this also

**Comment by heddanas** [comment]
Read this from :
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#mapsetclickable

>  If you want to show your HTML above the map, such as a sidebar, you need to use map.setClickable( false ) before showing it. (otherwise the click will be passed to the map). You don't need to use this, when your content is inside of the map_canvas div, only when outside of it)
> 
> Because the plugin watches ONLY elements inside of the map_canvas div, not others. That's why you need to call map.setClickable( false ) to be clickable (eg. sidebar), then call map.setClickable( true ) after closing.

**Comment by wf9a5m75** [comment]
@hugomosh @heddanas

I think the latest version (v2) solves this issue without `map.setClickable()`.
