### ISSUE TITLE
RC4: Tapping on the screen while scrolling selects wrong item

### ISSUE THREAD

**Issue by AndreasGassmann** [ionic-team/ionic#9945]
**Ionic version:**
[x] **2.x**

**I'm submitting a ...**
[x] bug report

**Current behavior:**
When scrolling through a list of cards and tapping the screen, the wrong card gets selected.

**Expected behavior:**
Clicking on a card under any circumstances should trigger the click on that card.

**Steps to reproduce:**

I made a video to show what I mean (pay attention to the pictures visible when the scroll starts and the one that gets opened afterwards):
![scroll-select-issue](https://cloud.githubusercontent.com/assets/680814/21831536/c8bed412-d7a4-11e6-9640-eedb90110ab3.gif)
Sadly you can't see the taps, so I have to describe the steps in more detail:

1. You start scrolling by swiping up/down (take your finger off the screen).

2. While the content is still scrolling, tap and hold anywhere on the screen for at least ~0.2s, then release it.

3. The click will be triggered on the item that was visible at that position when you started scrolling.

**Other information:**
Github repo to reproduce the issue: https://github.com/AndreasGassmann/Ionic2ListDemo

**Ionic info:**

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0 
ios-sim version: 5.0.6 
OS: macOS Sierra
Node Version: v7.0.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us! We will take a look at this.

**Comment by AndreasGassmann** [comment]
After comparing it with other (native) apps I think the correct behaviour should be that the tap/click to stop the scrolling shouldn't trigger the click on the element at all.

I also have a feeling that there is an underlying issue with the scrolling. As you can see with the "scrollToTop" button in the bottom right, it only shows/hides when the scrolling stops. That might also be the reason why the wrong (old) picture gets selected.

**Comment by tmvnk** [comment]
Indeed. Tapping while scrolling should disable scroll. Tapping again can open an item. Now sometimes an item will open directly while you just want to stop scrolling or scroll more. Tested in several other native apps to find out expected behavior.

**Comment by tmvnk** [comment]
Any update on this one? While scrolling and tap to scrolll further but you touch the screen at for an image with (tap) then this tap is activated instead of scrolling more.

**Comment by jgw96** [comment]
Hello all! Thanks for all the info. @AndreasGassmann and @tmvnk , what platforms is this happening on?

**Comment by tmvnk** [comment]
iOS 10

**Comment by Chrysweel** [comment]
+1
I have the same problem!

**Comment by alexbainbridge** [comment]
Has anyone worked out how to code around this temporarily?

**Comment by ThorConzales** [comment]
I did upgrade to WKWebView and I don't seem to have that problem there.

**Comment by peter-bozovic** [comment]
I'm also struggling with this :(

I can't get WKWebView to work, and don't find this as normal solution since it solves maybe one problem but might cause many others. (Like my application unable to connect to the API with WKWebView)

Anyone found a solution without using WKWebView ?
