### ISSUE TITLE
RC4: ion-footer's content not animated with custom component

### ISSUE THREAD

**Issue by dbaq** [ionic-team/ionic#9947]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x** (RC 4)

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The `ion-footer` does not animate custom component during iOS transitions. It was working in beta-11.

**Expected behavior:**
The `ion-footer` component should animate its whole content, even a custom component.

As you can see on the animation, the footer's content of the first page is not animated but the second is. The only difference is the use of a custom component.

![vvb05cpp0w](https://cloud.githubusercontent.com/assets/1867703/21832716/e75efd0e-d761-11e6-9bcc-fb9276a0a462.gif)

**Steps to reproduce:**
please check out this repository with the 2 examples:

https://github.com/dbaq/ionfooteranimation-issue

You can use chrome dev tools and select an **iOS** device.

**Related code:**

1 - ANIMATION NOT WORKING
```
import { Component } from '@angular/core';

@Component({
  selector: 'custom',
  template: `<div style="height:40px; width:100%; background-color: red; color: white">:(</div>`
})
export class Custom {}
```

```
<ion-footer>
  <custom></custom>
</ion-footer>
```

2 - ANIMATION WORKING
```
<ion-footer>
  <div style="height:40px; width:100%; background-color: red; color: white">:(</div>
</ion-footer>
```

**Other information:**
Here is the forum discussiona about this issue: https://forum.ionicframework.com/t/nav-animations-for-ion-footer-bar-and-ion-header-bar/55645/19

It was working in beta-11.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Your system information:
```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by brettdorrans** [comment]
This is still occurring in newer versions of Ionic. Any fixes/workarounds?

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.1
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by philipgriffin** [comment]
I am also facing this issue and cannot solve it.

global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.0
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by mtshare** [comment]
Same here with `ionic-angular 3.6.1`

**Comment by yannbf** [comment]
You need to wrap your component in an `<ion-toolbar>` element, otherwise Ionic won't know what to animate.

**Comment by haifzhan** [comment]
@yannbf  I have tried wrap in ion-toolbar, no luck
