### ISSUE TITLE
RC5 Content Scroll Events don't trigger change detection

### ISSUE THREAD

**Issue by ghenry22** [ionic-team/ionic#9974]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Listen for the ionScrollStart event fired by content.
console.log to show that the listening method was called
update a variable in the called method
the change in variable isn't detected by change detection

To fix wrap the variable updated in ngzone and all works as expected.

**Expected behavior:**
when I update a variable in the called method change detection is triggered without needing to manually wrap it in a zone.

**Steps to reproduce:**
start a new blank project
add (ionScrollStart)="someMethod()" to ion-content
create a variable "showButton" and default to false
ngIf if a button (or whatever) on the page so it only shows when showButton is true
in the someMethod update showButton to true.

Button isn't shown.

Wrap the change to showButton in a zone manually and it updates correctly.

**Related code:**

n/a

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by Buuhuu** [comment]
+1 This happens because enableNativeScrolling() of ScrollView is somehow called in the <root> Zone not the NgZone and adds the event listeners with a reference to the wrong zone. I traced that down to the point where requestAnimationFrame is called in Animation#play. Outside the callback the Zone is angular inside its <root>.

**Comment by ghenry22** [comment]
recent commit noted that wrapping scroll events in zone.run was the way to go, means this behaviour is as expected.
