### ISSUE TITLE
Tab highlight not recalculated/repositioned when tab is shown/hidden

### ISSUE THREAD

**Issue by mmlleevvyy** [ionic-team/ionic#9982]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The tab button can be shown and hidden by its property "show". When tab highlight is enabled for tabs and one tab is hidden (set show=false), the tab highlight is not recalculated/repositioned until window resize event is triggered.

**Expected behavior:**
When tab is hidden, tab highlight is recalculated and repositioned.

**Steps to reproduce:**
https://github.com/lleevvyy/ionic-conference-app

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by mhartington** [comment]
Thanks for the heads up, we'll take a look
